FreeCAD: Part::Geometry Class Reference
Part::Geometry Class Reference abstract
#include <Geometry.h>
Public Member Functions
~Geometry () override
virtual TopoDS_Shape toShape () const =0
virtual const Handle (Geom_Geometry) &handle() const =0
unsigned int getMemSize () const override
void Save (Base::Writer &) const override
void Restore (Base::XMLReader &) override
virtual Geometry * copy () const =0
Geometry * clone () const
boost::uuids::uuid getTag () const
returns the tag of the geometry object
virtual bool isSame (const Geometry &other, double tol, double atol) const =0
bool hasSameExtensions (const Geometry &other) const
std::vector< std::weak_ptr< const GeometryExtension > > getExtensions () const
bool hasExtension (const Base::Type &type) const
bool hasExtension (const std::string &name) const
std::weak_ptr< const GeometryExtension > getExtension (const Base::Type &type) const
std::weak_ptr< const GeometryExtension > getExtension (const std::string &name) const
std::weak_ptr< GeometryExtension > getExtension (const Base::Type &type)
std::weak_ptr< GeometryExtension > getExtension (const std::string &name)
void setExtension (std::unique_ptr< GeometryExtension > &&geo)
void deleteExtension (const Base::Type &type)
void deleteExtension (const std::string &name)
void mirror (const Base::Vector3d &point) const
void mirror (const Base::Vector3d &point, const Base::Vector3d &dir) const
void rotate (const Base::Placement &plm) const
void scale (const Base::Vector3d &vec, double scale) const
void transform (const Base::Matrix4D &mat) const
void translate (const Base::Vector3d &vec) const
Geometry (const Geometry &)=delete
Geometry & operator= (const Geometry &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static std::unique_ptr< Geometry > fromShape (const TopoDS_Shape &s, bool silent=false)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Protected Member Functions
void createNewTag ()
create a new tag for the geometry object
void assignTag (const Part::Geometry *)
copies the tag from the geometry passed as a parameter to this object
void copyNonTag (const Part::Geometry *)
Geometry ()
Protected Attributes
boost::uuids::uuid tag
std::vector< std::shared_ptr< GeometryExtension > > extensions
Additional Inherited Members
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 103 of file Part/App/Geometry.h.
Constructor & Destructor Documentation
~Geometry()
Geometry::~Geometry () override default
Geometry() [1/2]
Part::Geometry::Geometry () protected
Geometry() [2/2]
Part::Geometry::Geometry (const Geometry &) delete
Member Function Documentation
assignTag()
void Geometry::assignTag (const Part::Geometry * geo) protected
copies the tag from the geometry passed as a parameter to this object
Definition at line 480 of file Part/App/Geometry.cpp.
References Base::Persistence::getTypeId(), and tag.
clone()
Geometry * Geometry::clone () const
returns a cloned object. A cloned object has the same tag (see getTag) as the original object. if you want a copy not having the same tag, you can use copy() instead. If you want a clone with another geometry handle, it is possible to clone an object and then assign another handle or to create an object via constructor and use assignTag to assign the tag of the other geometry. If you do not desire to have the same tag, then a copy can be performed by using a constructor (which will generate another tag) and then, if necessary (e.g. if the constructor did not take a handle as a parameter), set a new handle.
Definition at line 496 of file Part/App/Geometry.cpp.
References copy(), and tag.
Referenced by Sketcher::Sketch::addArc(), Sketcher::Sketch::addArcOfEllipse(), Sketcher::Sketch::addArcOfHyperbola(), Sketcher::Sketch::addArcOfParabola(), Sketcher::Sketch::addCircle(), Sketcher::Sketch::addEllipse(), Sketcher::Sketch::addLineSegment(), Part::GeomBezierCurve::getPyObject(), Part::GeomBSplineCurve::getPyObject(), Part::GeomTrimmedCurve::getPyObject(), Part::GeomCircle::getPyObject(), Part::GeomArcOfCircle::getPyObject(), Part::GeomEllipse::getPyObject(), Part::GeomArcOfEllipse::getPyObject(), Part::GeomHyperbola::getPyObject(), Part::GeomArcOfHyperbola::getPyObject(), Part::GeomParabola::getPyObject(), Part::GeomArcOfParabola::getPyObject(), Part::GeomLine::getPyObject(), Part::GeomLineSegment::getPyObject(), Part::GeomOffsetCurve::getPyObject(), Part::GeomBezierSurface::getPyObject(), Part::GeomBSplineSurface::getPyObject(), Part::GeomCylinder::getPyObject(), Part::GeomCone::getPyObject(), Part::GeomSphere::getPyObject(), Part::GeomToroid::getPyObject(), Part::GeomPlane::getPyObject(), Part::GeomOffsetSurface::getPyObject(), Part::GeomPlateSurface::getPyObject(), Part::GeomTrimmedSurface::getPyObject(), Part::GeomSurfaceOfRevolution::getPyObject(), Part::GeomSurfaceOfExtrusion::getPyObject(), Sketcher::SketchObject::insertBSplineKnot(), src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::integrated(), Sketcher::SketchObject::modifyBSplineKnotMultiplicity(), Sketcher::SketchObject::setGeometry(), Part::PropertyGeometryList::setValue(), and Part::GeomSurface::toPlane().
copy()
virtual Geometry* Part::Geometry::copy () const pure virtual
returns a copy of this object having a new randomly generated tag. If you also want to copy the tag, you may use clone() instead. For creation of geometry with other handles, with or without the same tag, you may use the constructors and the sethandle functions. The tag of a geometry can be copied to another geometry using the assignTag function.
Implemented in Part::GeomArcOfConic, Part::GeomConic, Part::GeomSurfaceOfExtrusion, Part::GeomSurfaceOfRevolution, Part::GeomTrimmedSurface, Part::GeomPlateSurface, Part::GeomOffsetSurface, Part::GeomPlane, Part::GeomToroid, Part::GeomSphere, Part::GeomCone, Part::GeomCylinder, Part::GeomBSplineSurface, Part::GeomBezierSurface, Part::GeomOffsetCurve, Part::GeomLineSegment, Part::GeomLine, Part::GeomArcOfParabola, Part::GeomParabola, Part::GeomArcOfHyperbola, Part::GeomHyperbola, Part::GeomArcOfEllipse, Part::GeomEllipse, Part::GeomArcOfCircle, Part::GeomCircle, Part::GeomTrimmedCurve, Part::GeomBSplineCurve, Part::GeomBezierCurve, and Part::GeomPoint.
Referenced by Sketcher::SketchObject::addCopy(), Sketcher::SketchObject::addGeometry(), Sketcher::SketchObject::carbonCopy(), clone(), Sketcher::SketchObject::getSymmetric(), Sketcher::SketchObject::split(), and Part::GeomSurface::toPlane().
copyNonTag()
void Geometry::copyNonTag (const Part::Geometry * src) protected
Definition at line 488 of file Part/App/Geometry.cpp.
References create_qrc::ext, and extensions.
Referenced by Part::GeomCircle::copy(), Part::GeomEllipse::copy(), Part::GeomHyperbola::copy(), Part::GeomParabola::copy(), Part::GeomLine::copy(), and Part::GeomOffsetCurve::copy().
createNewTag()
void Geometry::createNewTag () protected
create a new tag for the geometry object
Definition at line 460 of file Part/App/Geometry.cpp.
References tag.
Referenced by TYPESYSTEM_SOURCE_ABSTRACT().
deleteExtension() [1/2]
void Geometry::deleteExtension (const Base::Type & type)
Definition at line 437 of file Part/App/Geometry.cpp.
References create_qrc::ext, extensions, and Path.Post.scripts.grbl_post::type.
deleteExtension() [2/2]
void Geometry::deleteExtension (const std::string & name)
Definition at line 448 of file Part/App/Geometry.cpp.
References create_qrc::ext, and extensions.
fromShape()
std::unique_ptr< Geometry > Geometry::fromShape (const TopoDS_Shape & s, bool silent = false) static
Definition at line 248 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::e, SCL.SimpleDataTypes::f, FC_THROWM, Part::makeFromCurveAdaptor(), Part::makeFromSurfaceAdaptor(), buildPsets::p, and Part::TopoShape::shapeName().
Referenced by Attacher::AttachEngine3D::_calculateAttachedPlacement(), FC_LOG_LEVEL_INIT(), Part::Feature::getCameraAlignmentDirection(), and PartDesign::ProfileBased::getProfileNormal().
getExtension() [1/4]
std::weak_ptr< GeometryExtension > Geometry::getExtension (const Base::Type & type)
Definition at line 385 of file Part/App/Geometry.cpp.
References create_qrc::ext, extensions, and Path.Post.scripts.grbl_post::type.
getExtension() [2/4]
std::weak_ptr< const GeometryExtension > Geometry::getExtension (const Base::Type & type) const
Definition at line 405 of file Part/App/Geometry.cpp.
References Path.Post.scripts.grbl_post::type.
Referenced by getExtension(), and Restore().
getExtension() [3/4]
std::weak_ptr< GeometryExtension > Geometry::getExtension (const std::string & name)
Definition at line 395 of file Part/App/Geometry.cpp.
References create_qrc::ext, and extensions.
getExtension() [4/4]
std::weak_ptr< const GeometryExtension > Geometry::getExtension (const std::string & name) const
Definition at line 410 of file Part/App/Geometry.cpp.
References getExtension().
getExtensions()
std::vector< std::weak_ptr< const GeometryExtension > > Geometry::getExtensions () const
Definition at line 356 of file Part/App/Geometry.cpp.
References create_qrc::ext, and extensions.
getMemSize()
unsigned int Geometry::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Implements Base::Persistence.
Reimplemented in Part::GeomArcOfConic, Part::GeomConic, Part::GeomSurfaceOfExtrusion, Part::GeomSurfaceOfRevolution, Part::GeomTrimmedSurface, Part::GeomPlateSurface, Part::GeomOffsetSurface, Part::GeomPlane, Part::GeomToroid, Part::GeomSphere, Part::GeomCone, Part::GeomCylinder, Part::GeomBSplineSurface, Part::GeomBezierSurface, Part::GeomOffsetCurve, Part::GeomLineSegment, Part::GeomLine, Part::GeomArcOfParabola, Part::GeomParabola, Part::GeomArcOfHyperbola, Part::GeomHyperbola, Part::GeomArcOfEllipse, Part::GeomEllipse, Part::GeomArcOfCircle, Part::GeomCircle, Part::GeomTrimmedCurve, Part::GeomBSplineCurve, Part::GeomBezierCurve, and Part::GeomPoint.
Definition at line 243 of file Part/App/Geometry.cpp.
getTag()
boost::uuids::uuid Geometry::getTag () const
returns the tag of the geometry object
Definition at line 351 of file Part/App/Geometry.cpp.
References tag.
Referenced by Sketcher::SketchObject::deleteUnusedInternalGeometryAndUpdateGeoId().
Handle()
virtual const Part::Geometry::Handle (Geom_Geometry) const & pure virtual
Implemented in Part::GeomArcOfConic, Part::GeomConic, Part::GeomSurfaceOfExtrusion, Part::GeomSurfaceOfRevolution, Part::GeomTrimmedSurface, Part::GeomPlateSurface, Part::GeomOffsetSurface, Part::GeomPlane, Part::GeomToroid, Part::GeomSphere, Part::GeomCone, Part::GeomCylinder, Part::GeomBSplineSurface, Part::GeomBezierSurface, Part::GeomOffsetCurve, Part::GeomLineSegment, Part::GeomLine, Part::GeomArcOfParabola, Part::GeomParabola, Part::GeomArcOfHyperbola, Part::GeomHyperbola, Part::GeomArcOfEllipse, Part::GeomEllipse, Part::GeomArcOfCircle, Part::GeomCircle, Part::GeomTrimmedCurve, Part::GeomBSplineCurve, Part::GeomBezierCurve, and Part::GeomPoint.
Referenced by Part::GeomCurve::closestParameter(), Part::GeomCurve::closestParameterToBasisCurve(), Part::GeomSurface::curvature(), Part::GeomCurve::curvatureAt(), Part::GeomSurface::curvatureDirections(), Part::GeomCurve::firstDerivativeAtParameter(), Part::GeomElementarySurface::getDir(), Part::GeomSweptSurface::getDir(), Part::GeomSurface::getDN(), Part::GeomBoundedCurve::getEndPoint(), Part::GeomCurve::getFirstParameter(), Part::GeomCurve::getLastParameter(), Part::GeomElementarySurface::getLocation(), Part::GeomBoundedCurve::getStartPoint(), Part::GeomElementarySurface::getXDir(), Part::GeomElementarySurface::getYDir(), Part::GeomCurve::intersect(), Part::GeomCurve::isLinear(), Part::GeomSurface::isPlanar(), Part::GeomSweptSurface::isSame(), Part::GeomSurface::isUmbillic(), Part::GeomCurve::length(), Part::GeomSurface::normal(), Part::GeomCurve::normalAt(), Part::GeomCurve::pointAtParameter(), Part::GeomCurve::reverse(), Part::GeomCurve::secondDerivativeAtParameter(), Part::GeomCurve::tangent(), Part::GeomSurface::tangentU(), Part::GeomSurface::tangentV(), Part::GeomCurve::toBSpline(), Part::GeomCurve::toShape(), Part::GeomSurface::toShape(), and Part::GeomCurve::value().
hasExtension() [1/2]
bool Geometry::hasExtension (const Base::Type & type) const
Definition at line 367 of file Part/App/Geometry.cpp.
References extensions, and Path.Post.scripts.grbl_post::type.
Referenced by Restore().
hasExtension() [2/2]
bool Geometry::hasExtension (const std::string & name) const
Definition at line 376 of file Part/App/Geometry.cpp.
References extensions.
hasSameExtensions()
bool Geometry::hasSameExtensions (const Geometry & other) const
Definition at line 210 of file Part/App/Geometry.cpp.
References create_qrc::ext, and extensions.
isSame()
virtual bool Part::Geometry::isSame (const Geometry & other, double tol, double atol) const pure virtual
Implemented in Part::GeomSweptSurface, Part::GeomTrimmedSurface, Part::GeomPlateSurface, Part::GeomOffsetSurface, Part::GeomPlane, Part::GeomToroid, Part::GeomSphere, Part::GeomCone, Part::GeomCylinder, Part::GeomElementarySurface, Part::GeomBSplineSurface, Part::GeomBezierSurface, Part::GeomOffsetCurve, Part::GeomLine, Part::GeomParabola, Part::GeomHyperbola, Part::GeomEllipse, Part::GeomCircle, Part::GeomTrimmedCurve, Part::GeomConic, Part::GeomBSplineCurve, Part::GeomBezierCurve, and Part::GeomPoint.
mirror() [1/2]
void Geometry::mirror (const Base::Vector3d & point) const
Definition at line 506 of file Part/App/Geometry.cpp.
mirror() [2/2]
void Geometry::mirror (const Base::Vector3d & point, const Base::Vector3d & dir) const
Definition at line 512 of file Part/App/Geometry.cpp.
References Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
operator=()
Geometry& Part::Geometry::operator= (const Geometry &) delete
Restore()
void Geometry::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Reimplemented in Part::GeomSurfaceOfExtrusion, Part::GeomSurfaceOfRevolution, Part::GeomTrimmedSurface, Part::GeomPlateSurface, Part::GeomOffsetSurface, Part::GeomPlane, Part::GeomToroid, Part::GeomSphere, Part::GeomCone, Part::GeomCylinder, Part::GeomBSplineSurface, Part::GeomBezierSurface, Part::GeomOffsetCurve, Part::GeomLineSegment, Part::GeomLine, Part::GeomArcOfParabola, Part::GeomParabola, Part::GeomArcOfHyperbola, Part::GeomHyperbola, Part::GeomArcOfEllipse, Part::GeomEllipse, Part::GeomArcOfCircle, Part::GeomCircle, Part::GeomTrimmedCurve, Part::GeomBSplineCurve, Part::GeomBezierCurve, and Part::GeomPoint.
Definition at line 307 of file Part/App/Geometry.cpp.
References Base::Console(), Part::GeometryMigrationExtension::Construction, src.Mod.AddonManager.NetworkManager::count, create_qrc::ext, extensions, Base::Type::fromName(), Base::BaseClass::getClassTypeId(), getExtension(), hasExtension(), TechDrawTools.TaskFillTemplateFields::reader, Part::GeometryPersistenceExtension::Restore(), setExtension(), Path.Post.scripts.grbl_post::type, and Base::ConsoleSingleton::Warning().
Referenced by Part::GeomPoint::Restore(), Part::GeomBSplineCurve::Restore(), Part::GeomCircle::Restore(), Part::GeomArcOfCircle::Restore(), Part::GeomEllipse::Restore(), Part::GeomArcOfEllipse::Restore(), Part::GeomHyperbola::Restore(), Part::GeomArcOfHyperbola::Restore(), Part::GeomParabola::Restore(), Part::GeomArcOfParabola::Restore(), Part::GeomLine::Restore(), and Part::GeomLineSegment::Restore().
rotate()
void Geometry::rotate (const Base::Placement & plm) const
Definition at line 518 of file Part/App/Geometry.cpp.
References Base::Placement::getPosition(), Base::Placement::getRotation(), Base::Rotation::getValue(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Save()
void Geometry::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Reimplemented in Part::GeomSurfaceOfExtrusion, Part::GeomSurfaceOfRevolution, Part::GeomTrimmedSurface, Part::GeomPlateSurface, Part::GeomOffsetSurface, Part::GeomPlane, Part::GeomToroid, Part::GeomSphere, Part::GeomCone, Part::GeomCylinder, Part::GeomBSplineSurface, Part::GeomBezierSurface, Part::GeomOffsetCurve, Part::GeomLineSegment, Part::GeomLine, Part::GeomArcOfParabola, Part::GeomParabola, Part::GeomArcOfHyperbola, Part::GeomHyperbola, Part::GeomArcOfEllipse, Part::GeomEllipse, Part::GeomArcOfCircle, Part::GeomCircle, Part::GeomTrimmedCurve, Part::GeomBSplineCurve, Part::GeomBezierCurve, and Part::GeomPoint.
Definition at line 283 of file Part/App/Geometry.cpp.
References Base::Writer::decInd(), extensions, Base::BaseClass::getClassTypeId(), Base::Writer::incInd(), Base::Writer::ind(), and Base::Writer::Stream().
Referenced by Part::GeomPoint::Save(), Part::GeomBSplineCurve::Save(), Part::GeomCircle::Save(), Part::GeomArcOfCircle::Save(), Part::GeomEllipse::Save(), Part::GeomArcOfEllipse::Save(), Part::GeomHyperbola::Save(), Part::GeomArcOfHyperbola::Save(), Part::GeomParabola::Save(), Part::GeomArcOfParabola::Save(), Part::GeomLine::Save(), and Part::GeomLineSegment::Save().
scale()
void Geometry::scale (const Base::Vector3d & vec, double scale) const
Definition at line 532 of file Part/App/Geometry.cpp.
References SurfaceTests.TestBlendCurve::vec.
setExtension()
void Geometry::setExtension (std::unique_ptr< GeometryExtension > && geo)
Definition at line 416 of file Part/App/Geometry.cpp.
References create_qrc::ext, extensions, and Path.Post.scripts.opensbp_post::move().
Referenced by Restore().
toShape()
virtual TopoDS_Shape Part::Geometry::toShape () const pure virtual
Implemented in Part::GeomSurface, Part::GeomCurve, and Part::GeomPoint.
Referenced by Sketcher::SketchObject::getEdge().
transform()
void Geometry::transform (const Base::Matrix4D & mat) const
Definition at line 538 of file Part/App/Geometry.cpp.
translate()
void Geometry::translate (const Base::Vector3d & vec) const
Definition at line 547 of file Part/App/Geometry.cpp.
References SurfaceTests.TestBlendCurve::vec.
Member Data Documentation
extensions
std::vector<std::shared_ptr<GeometryExtension> > Part::Geometry::extensions protected
Definition at line 165 of file Part/App/Geometry.h.
Referenced by copyNonTag(), deleteExtension(), getExtension(), getExtensions(), hasExtension(), hasSameExtensions(), Restore(), Save(), and setExtension().
tag
boost::uuids::uuid Part::Geometry::tag protected
Definition at line 164 of file Part/App/Geometry.h.
Referenced by assignTag(), clone(), createNewTag(), Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.ChunkBase::dump_header(), getTag(), Part::GeomCurve::toLine(), Part::GeomCurve::toLineSegment(), and Part::GeomSurface::toPlane().
The documentation for this class was generated from the following files:
Part/App/Geometry.h
Part/App/Geometry.cpp