FreeCAD: femsolver.mystran.solver.Proxy Class Reference
femsolver.mystran.solver.Proxy Class Reference
Public Member Functions
def __init__ (self, obj)
def createMachine (self, obj, directory, testmode=False)
def editSupported (self)
def edit (self, directory)
def execute (self, obj)
Public Member Functions inherited from femsolver.solverbase.Proxy
def createEquation (self, obj, eqId)
def isSupported (self, equation)
def addEquation (self, obj, eqId)
Static Public Attributes
Type
Static Public Attributes inherited from femsolver.solverbase.Proxy
BaseType
Detailed Description
The Fem::FemSolver's Proxy python type, add solver specific properties
Definition at line 51 of file mystran/solver.py.
Constructor & Destructor Documentation
__init__()
def femsolver.mystran.solver.Proxy.__init__ (self, obj)
Reimplemented from femsolver.solverbase.Proxy.
Definition at line 56 of file mystran/solver.py.
Member Function Documentation
createMachine()
def femsolver.mystran.solver.Proxy.createMachine (self, obj, directory, testmode = False)
Reimplemented from femsolver.solverbase.Proxy.
Definition at line 66 of file mystran/solver.py.
edit()
def femsolver.mystran.solver.Proxy.edit (self, directory)
Reimplemented from femsolver.solverbase.Proxy.
Definition at line 80 of file mystran/solver.py.
editSupported()
def femsolver.mystran.solver.Proxy.editSupported (self)
Reimplemented from femsolver.solverbase.Proxy.
Definition at line 77 of file mystran/solver.py.
execute()
def femsolver.mystran.solver.Proxy.execute (self, obj)
Reimplemented from femsolver.solverbase.Proxy.
Definition at line 87 of file mystran/solver.py.
Referenced by src.Mod.PartDesign.Scripts.Spring.MySpring.onChanged(), src.Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid.onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped.onChanged(), src.Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt.onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder.onChanged(), MeasureCOM.MeasureCOM.onChanged(), and FeaturePython.DistanceBolt.onChanged().
Member Data Documentation
Type
femsolver.mystran.solver.Proxy.Type static
Definition at line 54 of file mystran/solver.py.
The documentation for this class was generated from the following file:
mystran/solver.py