FreeCAD: Path.Op.Gui.Pocket.TaskPanelOpPage Class Reference
Path.Op.Gui.Pocket.TaskPanelOpPage Class Reference
Public Member Functions
def pocketFeatures (self)
Detailed Description
Page controller class for Pocket operation
Definition at line 44 of file Gui/Pocket.py.
Member Function Documentation
pocketFeatures()
def Path.Op.Gui.Pocket.TaskPanelOpPage.pocketFeatures (self)
pocketFeatures() ... return FeaturePocket (see PathPocketBaseGui)
Definition at line 47 of file Gui/Pocket.py.
Referenced by Path.Op.Gui.PocketBase.TaskPanelOpPage.getFields(), Path.Op.Gui.PocketBase.TaskPanelOpPage.getSignalsForUpdate(), and Path.Op.Gui.PocketBase.TaskPanelOpPage.setFields().
The documentation for this class was generated from the following file:
Gui/Pocket.py