FreeCAD: MatGui::MaterialSave Class Reference
MatGui::MaterialSave Class Reference
#include <MaterialSave.h>
Public Member Functions
MaterialSave (const std::shared_ptr< Materials::Material > &material, QWidget *parent=nullptr)
~MaterialSave () override
void setLibraries ()
void createModelTree ()
void addExpanded (QTreeView *tree, QStandardItem *parent, QStandardItem *child)
void addExpanded (QTreeView *tree, QStandardItemModel *parent, QStandardItem *child)
void addMaterials (QStandardItem &parent, const std::shared_ptr< std::map< QString, std::shared_ptr< Materials::MaterialTreeNode >>> modelTree, const QIcon &folderIcon, const QIcon &icon)
void showSelectedTree ()
void onSelectModel (const QItemSelection &selected, const QItemSelection &deselected)
void currentTextChanged (const QString &value)
void onNewFolder (bool checked)
void onItemChanged (QStandardItem *item)
void onFilename (const QString &text)
void onContextMenu (const QPoint &pos)
void onDelete (bool checked)
void onInherited (int state)
void onOk (bool checked)
void onCancel (bool checked)
int confirmOverwrite (const QString &filename)
int confirmNewMaterial ()
int confirmCopy ()
void accept () override
void reject () override
Detailed Description
Definition at line 59 of file MaterialSave.h.
Constructor & Destructor Documentation
MaterialSave()
MaterialSave::MaterialSave (const std::shared_ptr< Materials::Material > & material, QWidget * parent = nullptr) explicit
Definition at line 42 of file MaterialSave.cpp.
References Gui::Application::commandManager(), draftgeoutils.intersections::connect(), createModelTree(), currentTextChanged(), Gui::CommandManager::getCommandByName(), Gui::Command::getShortcut(), Gui::Application::Instance, onCancel(), onContextMenu(), onDelete(), onFilename(), onInherited(), onItemChanged(), onNewFolder(), onOk(), onSelectModel(), setLibraries(), and showSelectedTree().
~MaterialSave()
MaterialSave::~MaterialSave () override
Definition at line 113 of file MaterialSave.cpp.
Member Function Documentation
accept()
void MaterialSave::accept () override
Definition at line 278 of file MaterialSave.cpp.
Referenced by onOk(), and MaterialEditor.MaterialEditor::verify().
addExpanded() [1/2]
void MaterialSave::addExpanded (QTreeView * tree, QStandardItem * parent, QStandardItem * child)
Definition at line 308 of file MaterialSave.cpp.
References Init::parent.
Referenced by addMaterials(), onNewFolder(), and showSelectedTree().
addExpanded() [2/2]
void MaterialSave::addExpanded (QTreeView * tree, QStandardItemModel * parent, QStandardItem * child)
Definition at line 314 of file MaterialSave.cpp.
References Init::parent.
addMaterials()
void MaterialSave::addMaterials (QStandardItem & parent, const std::shared_ptr< std::map< QString, std::shared_ptr< Materials::MaterialTreeNode >>> modelTree, const QIcon & folderIcon, const QIcon & icon)
Definition at line 320 of file MaterialSave.cpp.
References addExpanded(), Materials::FolderTreeNode< T >::DataNode, and Init::parent.
Referenced by showSelectedTree().
confirmCopy()
int MaterialSave::confirmCopy ()
Definition at line 238 of file MaterialSave.cpp.
References MengerSponge::box.
Referenced by onOk().
confirmNewMaterial()
int MaterialSave::confirmNewMaterial ()
Definition at line 211 of file MaterialSave.cpp.
References MengerSponge::box.
Referenced by onOk().
confirmOverwrite()
int MaterialSave::confirmOverwrite (const QString & filename)
Definition at line 183 of file MaterialSave.cpp.
References MengerSponge::box, and Path.Log::info().
Referenced by onOk().
createModelTree()
void MaterialSave::createModelTree ()
Definition at line 300 of file MaterialSave.cpp.
Referenced by MaterialSave().
currentTextChanged()
void MaterialSave::currentTextChanged (const QString & value)
Definition at line 430 of file MaterialSave.cpp.
References showSelectedTree().
Referenced by MaterialSave().
onCancel()
void MaterialSave::onCancel (bool checked)
Definition at line 271 of file MaterialSave.cpp.
References reject().
Referenced by MaterialSave().
onContextMenu()
void MaterialSave::onContextMenu (const QPoint & pos)
Definition at line 530 of file MaterialSave.cpp.
References RobotExample::pos.
Referenced by MaterialSave().
onDelete()
void MaterialSave::onDelete (bool checked)
Definition at line 539 of file MaterialSave.cpp.
Referenced by MaterialSave().
onFilename()
void MaterialSave::onFilename (const QString & text)
Definition at line 518 of file MaterialSave.cpp.
Referenced by MaterialSave().
onInherited()
void MaterialSave::onInherited (int state)
Definition at line 118 of file MaterialSave.cpp.
Referenced by MaterialSave().
onItemChanged()
void MaterialSave::onItemChanged (QStandardItem * item)
Definition at line 509 of file MaterialSave.cpp.
Referenced by MaterialSave().
onNewFolder()
void MaterialSave::onNewFolder (bool checked)
Definition at line 465 of file MaterialSave.cpp.
References addExpanded(), and SplineSurface::i.
Referenced by MaterialSave().
onOk()
void MaterialSave::onOk (bool checked)
Definition at line 125 of file MaterialSave.cpp.
References accept(), confirmCopy(), confirmNewMaterial(), confirmOverwrite(), Materials::MaterialManager::exists(), ifctree::filepath, and Materials::MaterialManager::saveMaterial().
Referenced by MaterialSave().
onSelectModel()
void MaterialSave::onSelectModel (const QItemSelection & selected, const QItemSelection & deselected)
Definition at line 394 of file MaterialSave.cpp.
Referenced by MaterialSave().
reject()
void MaterialSave::reject () override
Definition at line 283 of file MaterialSave.cpp.
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and onCancel().
setLibraries()
void MaterialSave::setLibraries ()
Definition at line 288 of file MaterialSave.cpp.
References Materials::MaterialManager::getMaterialLibraries().
Referenced by MaterialSave().
showSelectedTree()
void MaterialSave::showSelectedTree ()
Definition at line 352 of file MaterialSave.cpp.
References addExpanded(), addMaterials(), Gui::getMainWindow(), Materials::MaterialManager::getMaterialTree(), and Path.Log::warning().
Referenced by currentTextChanged(), and MaterialSave().
The documentation for this class was generated from the following files:
MaterialSave.h
MaterialSave.cpp