FreeCAD: Gui::NotificationArea Class Reference
Gui::NotificationArea Class Reference
#include <NotificationArea.h>
Classes
class ParameterObserver
Public Member Functions
NotificationArea (QWidget *parent=nullptr)
~NotificationArea () override
void pushNotification (const QString &notifiername, const QString &message, Base::LogStyle level)
bool areDeveloperWarningsActive () const
bool areDeveloperErrorsActive () const
Detailed Description
Definition at line 60 of file NotificationArea.h.
Constructor & Destructor Documentation
NotificationArea()
NotificationArea::NotificationArea (QWidget * parent = nullptr)
Definition at line 865 of file NotificationArea.cpp.
References draftgeoutils.intersections::connect(), Init::parent, NotificationsAction::size(), and NotificationsAction::synchroniseWidget().
~NotificationArea()
NotificationArea::~NotificationArea () override
Definition at line 963 of file NotificationArea.cpp.
Member Function Documentation
areDeveloperErrorsActive()
bool NotificationArea::areDeveloperErrorsActive () const
Definition at line 1009 of file NotificationArea.cpp.
Referenced by NotificationAreaObserver::SendLog().
areDeveloperWarningsActive()
bool NotificationArea::areDeveloperWarningsActive () const
Definition at line 1004 of file NotificationArea.cpp.
Referenced by NotificationAreaObserver::SendLog().
pushNotification()
void NotificationArea::pushNotification (const QString & notifiername, const QString & message, Base::LogStyle level)
Definition at line 1014 of file NotificationArea.cpp.
References NotificationsAction::count(), NotificationsAction::deleteLastItem(), toolbit-attributes::g, NotificationsAction::getUnreadCount(), NotificationsAction::isSameNotification(), level(), Path.Post.scripts.opensbp_post::move(), NotificationsAction::push_front(), and NotificationsAction::resetLastNotificationStatus().
Referenced by NotificationAreaObserver::SendLog().
The documentation for this class was generated from the following files:
NotificationArea.h
NotificationArea.cpp