FreeCAD: ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume Class Reference
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume Class Reference
Public Member Functions
def __init__ (self, projection_type, projection_point, view_plane_distance, front_plane_distance, front_plane_clipping, back_plane_distance, back_plane_clipping, view_volume_sides_clipping, view_window)
def projection_type ()
def projection_point ()
def view_plane_distance ()
def front_plane_distance ()
def front_plane_clipping ()
def back_plane_distance ()
def back_plane_clipping ()
def view_volume_sides_clipping ()
def view_window ()
Public Member Functions inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.founded_item
def users ()
def wr1 (self)
def wr2 (self)
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
projection_type
projection_point
view_plane_distance
front_plane_distance
front_plane_clipping
back_plane_distance
back_plane_clipping
view_volume_sides_clipping
view_window
Detailed Description
Entity view_volume definition.
:param projection_type
:type projection_type:central_or_parallel
:param projection_point
:type projection_point:cartesian_point
:param view_plane_distance
:type view_plane_distance:length_measure
:param front_plane_distance
:type front_plane_distance:length_measure
:param front_plane_clipping
:type front_plane_clipping:BOOLEAN
:param back_plane_distance
:type back_plane_distance:length_measure
:param back_plane_clipping
:type back_plane_clipping:BOOLEAN
:param view_volume_sides_clipping
:type view_volume_sides_clipping:BOOLEAN
:param view_window
:type view_window:planar_box
Definition at line 27923 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Constructor & Destructor Documentation
__init__()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.__init__ (self, projection_type, projection_point, view_plane_distance, front_plane_distance, front_plane_clipping, back_plane_distance, back_plane_clipping, view_volume_sides_clipping, view_window)
Definition at line 27953 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Member Function Documentation
back_plane_clipping()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.back_plane_clipping ()
Definition at line 28050 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume._back_plane_clipping, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.back_plane_clipping, SCL.SimpleDataTypes.BOOLEAN, and SCL.TypeChecker.check_type().
back_plane_distance()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.back_plane_distance ()
Definition at line 28036 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume._back_plane_distance, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.back_plane_distance, and SCL.TypeChecker.check_type().
front_plane_clipping()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.front_plane_clipping ()
Definition at line 28022 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume._front_plane_clipping, SCL.SimpleDataTypes.BOOLEAN, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.front_plane_clipping.
front_plane_distance()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.front_plane_distance ()
Definition at line 28008 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume._front_plane_distance, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.front_plane_distance.
projection_point()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.projection_point ()
Definition at line 27980 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume._projection_point, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.projection_point.
projection_type()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.projection_type ()
Definition at line 27966 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume._projection_type, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.projection_type.
view_plane_distance()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.view_plane_distance ()
Definition at line 27994 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume._view_plane_distance, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.view_plane_distance.
view_volume_sides_clipping()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.view_volume_sides_clipping ()
Definition at line 28064 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume._view_volume_sides_clipping, SCL.SimpleDataTypes.BOOLEAN, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.view_volume_sides_clipping.
view_window()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.view_window ()
Definition at line 28078 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume._view_window, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.view_window.
Member Data Documentation
back_plane_clipping
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.back_plane_clipping
Definition at line 27961 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.back_plane_clipping().
back_plane_distance
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.back_plane_distance
Definition at line 27960 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.back_plane_distance().
front_plane_clipping
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.front_plane_clipping
Definition at line 27959 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.front_plane_clipping().
front_plane_distance
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.front_plane_distance
Definition at line 27958 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.front_plane_distance().
projection_point
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.projection_point
Definition at line 27956 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.projection_point().
projection_type
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.projection_type
Definition at line 27955 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.projection_type().
view_plane_distance
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.view_plane_distance
Definition at line 27957 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.view_plane_distance().
view_volume_sides_clipping
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.view_volume_sides_clipping
Definition at line 27962 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.view_volume_sides_clipping().
view_window
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.view_window
Definition at line 27963 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.view_volume.view_window().
The documentation for this class was generated from the following file:
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py