FreeCAD: TopoAlgorithm.cpp File Reference
TopoAlgorithm.cpp File Reference
#include "PreCompiled.h"
#include <algorithm>
#include <boost/core/ignore_unused.hpp>
#include <cmath>
#include <queue>
#include <utility>
#include <Base/Console.h>
#include <Mod/Mesh/App/WildMagic4/Wm4MeshCurvature.h>
#include "Evaluation.h"
#include "Iterator.h"
#include "MeshKernel.h"
#include "TopoAlgorithm.h"
#include "Triangulation.h"
Typedefs
using FaceEdge = std::pair< FacetIndex, int >
using FaceEdgePriority = std::pair< float, FaceEdge >
Functions
static float cos_maxangle (const Base::Vector3f &v1, const Base::Vector3f &v2, const Base::Vector3f &v3)
static float swap_benefit (const Base::Vector3f &v1, const Base::Vector3f &v2, const Base::Vector3f &v3, const Base::Vector3f &v4)
Typedef Documentation
FaceEdge
using FaceEdge = std::pair<FacetIndex, int>
Definition at line 307 of file TopoAlgorithm.cpp.
FaceEdgePriority
using FaceEdgePriority = std::pair<float, FaceEdge>
Definition at line 308 of file TopoAlgorithm.cpp.
Function Documentation
cos_maxangle()
static float cos_maxangle (const Base::Vector3f & v1, const Base::Vector3f & v2, const Base::Vector3f & v3) static
Definition at line 252 of file TopoAlgorithm.cpp.
References RobotExample::A, a, RobotExample::B, SCL.SimpleDataTypes::b, RobotExample::C, SCL.SimpleDataTypes::c, Base::Distance(), and draftgeoutils.general::v1().
Referenced by swap_benefit().
swap_benefit()
static float swap_benefit (const Base::Vector3f & v1, const Base::Vector3f & v2, const Base::Vector3f & v3, const Base::Vector3f & v4) static
Definition at line 264 of file TopoAlgorithm.cpp.
References cos_maxangle(), and draftgeoutils.general::v1().
Referenced by MeshCore::MeshTopoAlgorithm::SwapEdgeBenefit().