FreeCAD: Base::ShapeHintsItem Class Reference
Base::ShapeHintsItem Class Reference
The ShapeHintsItem class supports the SoShapeHints node.
#include <Builder3D.h>
Public Member Functions
ShapeHintsItem (float creaseAngle=0.0F)
void setVertexOrdering (VertexOrdering::Ordering)
void setShapeType (ShapeType::Type)
void write (InventorOutput &out) const override
Public Member Functions inherited from Base::NodeItem
virtual ~NodeItem ()=default
Additional Inherited Members
Protected Member Functions inherited from Base::NodeItem
NodeItem ()=default
NodeItem (const NodeItem &)=default
NodeItem (NodeItem &&)=default
NodeItem & operator= (const NodeItem &)=default
NodeItem & operator= (NodeItem &&)=default
Detailed Description
The ShapeHintsItem class supports the SoShapeHints node.
Definition at line 453 of file Builder3D.h.
Constructor & Destructor Documentation
ShapeHintsItem()
ShapeHintsItem::ShapeHintsItem (float creaseAngle = 0.0F) explicit
Definition at line 657 of file Builder3D.cpp.
Member Function Documentation
setShapeType()
void ShapeHintsItem::setShapeType (ShapeType::Type value)
Definition at line 666 of file Builder3D.cpp.
References Base::ShapeType::type.
setVertexOrdering()
void ShapeHintsItem::setVertexOrdering (VertexOrdering::Ordering value)
Definition at line 661 of file Builder3D.cpp.
References Base::VertexOrdering::ordering.
write()
void ShapeHintsItem::write (InventorOutput & out) const override virtual
Implements Base::NodeItem.
Definition at line 671 of file Builder3D.cpp.
References Base::VertexOrdering::toString(), Base::ShapeType::toString(), and Base::InventorOutput::write().
The documentation for this class was generated from the following files:
Builder3D.h
Builder3D.cpp