FreeCAD: ModelRefine::FaceTypedCylinder Class Reference
ModelRefine::FaceTypedCylinder Class Reference
#include <modelRefine.h>
Public Member Functions
bool isEqual (const TopoDS_Face &faceOne, const TopoDS_Face &faceTwo) const override
GeomAbs_SurfaceType getType () const override
TopoDS_Face buildFace (const FaceVectorType &faces) const override
Protected Member Functions
void boundarySplit (const FaceVectorType &facesIn, std::vector< EdgeVectorType > &boundariesOut) const override
Protected Member Functions inherited from ModelRefine::FaceTypedBase
FaceTypedBase (const GeomAbs_SurfaceType &typeIn)
Friends
FaceTypedCylinder & getCylinderObject ()
Additional Inherited Members
Static Public Member Functions inherited from ModelRefine::FaceTypedBase
static GeomAbs_SurfaceType getFaceType (const TopoDS_Face &faceIn)
Protected Attributes inherited from ModelRefine::FaceTypedBase
GeomAbs_SurfaceType surfaceType
Detailed Description
Definition at line 106 of file modelRefine.h.
Member Function Documentation
boundarySplit()
void FaceTypedCylinder::boundarySplit (const FaceVectorType & facesIn, std::vector< EdgeVectorType > & boundariesOut) const override protected virtual
Reimplemented from ModelRefine::FaceTypedBase.
Definition at line 719 of file modelRefine.cpp.
References ModelRefine::boundaryEdges(), FirstVertex(), and LastVertex().
Referenced by buildFace().
buildFace()
TopoDS_Face FaceTypedCylinder::buildFace (const FaceVectorType & faces) const override virtual
Implements ModelRefine::FaceTypedBase.
Definition at line 620 of file modelRefine.cpp.
References boundarySplit(), fixFace(), Handle(), and wireEncirclesAxis().
getType()
GeomAbs_SurfaceType FaceTypedCylinder::getType () const override virtual
Implements ModelRefine::FaceTypedBase.
Definition at line 480 of file modelRefine.cpp.
isEqual()
bool FaceTypedCylinder::isEqual (const TopoDS_Face & faceOne, const TopoDS_Face & faceTwo) const override virtual
Implements ModelRefine::FaceTypedBase.
Definition at line 462 of file modelRefine.cpp.
References Handle().
Friends And Related Function Documentation
getCylinderObject
FaceTypedCylinder& getCylinderObject () friend
The documentation for this class was generated from the following files:
modelRefine.h
modelRefine.cpp