FreeCAD: CompoundTools.CompoundFilter Namespace Reference
CompoundTools.CompoundFilter Namespace Reference
Classes
class _CompoundFilter
class _ViewProviderCompoundFilter
Functions
def makeCompoundFilter (name, into_group=None)
def getNullShapeShape (scale=1.0)
Function Documentation
getNullShapeShape()
def CompoundTools.CompoundFilter.getNullShapeShape (scale = 1.0)
Obtains a shape intended as a placeholder in case null shape was produced by an operation
Definition at line 258 of file CompoundFilter.py.
References AssemblyImport.open().
Referenced by CompoundTools.CompoundFilter._CompoundFilter.execute().
makeCompoundFilter()
def CompoundTools.CompoundFilter.makeCompoundFilter (name, into_group = None)
makeCompoundFilter(name): makes a CompoundFilter object.
Definition at line 34 of file CompoundFilter.py.
Referenced by CompoundTools.Explode.explodeCompound(), and femexamples.constraint_section_print.setup().