FreeCAD: Path.Op.Util Namespace Reference
Path.Op.Util Namespace Reference
Functions
def debugEdge (label, e)
def makeWires (inEdges)
def debugWire (label, w)
def isWireClockwise (w)
def orientWire (w, forward=True)
def offsetWire (wire, base, offset, forward, Side=None)
Variables
Part
PrintWireDebug
translate
Function Documentation
debugEdge()
def Path.Op.Util.debugEdge (label, e)
debugEdge(label, e) ... prints a python statement to create e
Currently lines and arcs are supported.
Definition at line 51 of file Op/Util.py.
References Path.Post.scripts.grbl_post.type.
Referenced by Path.Op.Util.debugWire().
debugWire()
def Path.Op.Util.debugWire (label, w)
debugWire(label, w) ... prints python statements for all edges of w to be added to the object tree in a group.
Definition at line 91 of file Op/Util.py.
References Path.Op.Util.debugEdge(), Path.Geom.flipEdge(), Path.Geom.pointsCoincide(), Path.Log.track(), and Path.Post.scripts.grbl_post.type.
Referenced by Path.Op.Util.offsetWire().
isWireClockwise()
def Path.Op.Util.isWireClockwise (w)
isWireClockwise(w) ... returns True if the wire winds clockwise.
Definition at line 157 of file Op/Util.py.
makeWires()
def Path.Op.Util.makeWires (inEdges)
makeWires ... function to make non-forking wires from a collection of edges
Definition at line 84 of file Op/Util.py.
Referenced by draftfunctions.upgrade.upgrade().
offsetWire()
def Path.Op.Util.offsetWire (wire, base, offset, forward, Side = None)
offsetWire(wire, base, offset, forward) ... offsets the wire away from base and orients the wire accordingly.
The function tries to avoid most of the pitfalls of Part.makeOffset2D which is possible because all offsetting
happens in the XY plane.
Definition at line 178 of file Op/Util.py.
References Path.Log.debug(), Path.Op.Util.debugWire(), Path.Geom.edgesMatch(), Path.Geom.flipEdge(), Path.Geom.isRoughly(), Path.Geom.Side.of(), Path.Op.Util.orientWire(), Path.Geom.pointsCoincide(), Path.Log.track(), and Path.Post.scripts.grbl_post.type.
Referenced by FC_LOG_LEVEL_INIT(), Part::ExtrusionHelper.makeDraft(), Part::ExtrusionHelper.makeElementDraft(), and Part::TopoShape.makeOffsetShape().
orientWire()
def Path.Op.Util.orientWire (w, forward = True)
orientWire(w, forward=True) ... orients given wire in a specific direction.
If forward = True (the default) the wire is oriented clockwise, looking down the negative Z axis.
If forward = False the wire is oriented counter clockwise.
If forward = None the orientation is determined by the order in which the edges appear in the wire.
Definition at line 162 of file Op/Util.py.
References Path.Log.debug(), Path.Geom.flipWire(), and Path.Log.track().
Referenced by Path.Op.Util.offsetWire().
Variable Documentation
Part
Path.Op.Util.Part
Definition at line 32 of file Op/Util.py.
PrintWireDebug
Path.Op.Util.PrintWireDebug
Definition at line 40 of file Op/Util.py.
translate
Path.Op.Util.translate
Definition at line 48 of file Op/Util.py.