FreeCAD: MeshCore::MeshTopoAlgorithm Class Reference
MeshCore::MeshTopoAlgorithm Class Reference
#include <TopoAlgorithm.h>
Public Member Functions
MeshTopoAlgorithm (MeshKernel &rclM)
~MeshTopoAlgorithm ()
MeshTopoAlgorithm (const MeshTopoAlgorithm &)=delete
MeshTopoAlgorithm (MeshTopoAlgorithm &&)=delete
MeshTopoAlgorithm & operator= (const MeshTopoAlgorithm &)=delete
MeshTopoAlgorithm & operator= (MeshTopoAlgorithm &&)=delete
Topological Operations
bool InsertVertex (FacetIndex ulFacetPos, const Base::Vector3f &rclPoint)
bool InsertVertexAndSwapEdge (FacetIndex ulFacetPos, const Base::Vector3f &rclPoint, float fMaxAngle)
void SwapEdge (FacetIndex ulFacetPos, FacetIndex ulNeighbour)
bool SplitEdge (FacetIndex ulFacetPos, FacetIndex ulNeighbour, const Base::Vector3f &rP)
bool SplitOpenEdge (FacetIndex ulFacetPos, unsigned short uSide, const Base::Vector3f &rP)
void SplitFacet (FacetIndex ulFacetPos, const Base::Vector3f &rP1, const Base::Vector3f &rP2)
bool CollapseVertex (const VertexCollapse &vc)
bool IsCollapseEdgeLegal (const EdgeCollapse &ec) const
bool CollapseEdge (FacetIndex ulFacetPos, FacetIndex ulNeighbour)
bool CollapseEdge (const EdgeCollapse &ec)
bool CollapseFacet (FacetIndex ulFacetPos)
Topological Optimization
void OptimizeTopology (float fMaxAngle)
void OptimizeTopology ()
void DelaunayFlip (float fMaxAngle)
int DelaunayFlip ()
void AdjustEdgesToCurvatureDirection ()
bool SnapVertex (FacetIndex ulFacetPos, const Base::Vector3f &rP)
bool IsSwapEdgeLegal (FacetIndex ulFacetPos, FacetIndex ulNeighbour) const
bool ShouldSwapEdge (FacetIndex ulFacetPos, FacetIndex ulNeighbour, float fMaxAngle) const
float SwapEdgeBenefit (FacetIndex f, int e) const
void Cleanup ()
bool RemoveDegeneratedFacet (FacetIndex index)
bool RemoveCorruptedFacet (FacetIndex index)
void FillupHoles (unsigned long length, int level, AbstractPolygonTriangulator &, std::list< std::vector< PointIndex >> &aFailed)
void FillupHoles (int level, AbstractPolygonTriangulator &, const std::list< std::vector< PointIndex >> &aBorders, std::list< std::vector< PointIndex >> &aFailed)
void FindHoles (unsigned long length, std::list< std::vector< PointIndex >> &aBorders) const
void FindComponents (unsigned long count, std::vector< FacetIndex > &findIndices)
void RemoveComponents (unsigned long count)
void HarmonizeNormals ()
void FlipNormals ()
void BeginCache ()
void EndCache ()
Detailed Description
The MeshTopoAlgorithm class provides several algorithms to manipulate a mesh. It supports various mesh operations like inserting a new vertex, swapping the common edge of two adjacent facets, split a facet, ...
Author
Werner Mayer
Definition at line 66 of file TopoAlgorithm.h.
Constructor & Destructor Documentation
MeshTopoAlgorithm() [1/3]
MeshTopoAlgorithm::MeshTopoAlgorithm (MeshKernel & rclM) explicit
Definition at line 45 of file TopoAlgorithm.cpp.
~MeshTopoAlgorithm()
MeshTopoAlgorithm::~MeshTopoAlgorithm ()
Definition at line 49 of file TopoAlgorithm.cpp.
References Cleanup(), and EndCache().
MeshTopoAlgorithm() [2/3]
MeshCore::MeshTopoAlgorithm::MeshTopoAlgorithm (const MeshTopoAlgorithm &) delete
MeshTopoAlgorithm() [3/3]
MeshCore::MeshTopoAlgorithm::MeshTopoAlgorithm (MeshTopoAlgorithm &&) delete
Member Function Documentation
AdjustEdgesToCurvatureDirection()
void MeshTopoAlgorithm::AdjustEdgesToCurvatureDirection ()
Tries to adjust the edges to the curvature direction with the minimum absolute value of maximum and minimum curvature.
Note
This is a high-level operation and tries to optimize the mesh as a whole.
Definition at line 450 of file TopoAlgorithm.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, MeshCore::MeshFacet::_aulPoints, MeshCore::MeshKernel::CountFacets(), MeshCore::MeshKernel::CountPoints(), Base::Distance(), MeshCore::MeshKernel::GetFacets(), Wm4::MeshCurvature< Real >::GetMaxCurvatures(), Wm4::MeshCurvature< Real >::GetMaxDirections(), Wm4::MeshCurvature< Real >::GetMinCurvatures(), Wm4::MeshCurvature< Real >::GetMinDirections(), MeshCore::MeshGeomFacet::GetNormal(), MeshCore::MeshKernel::GetPoints(), SplineSurface::i, MeshCore::MeshPointIterator::Init(), MeshCore::MeshFacet::IsFlag(), IsSwapEdgeLegal(), MeshCore::MeshPointIterator::More(), MeshCore::MeshPointIterator::Next(), Base::Vector3< float_type >::Normalize(), MeshCore::MeshFacetArray::ResetFlag(), MeshCore::MeshFacet::SetFlag(), MeshCore::MeshFacet::Side(), SwapEdge(), Base::Vector3< float >, MeshCore::MeshFacet::VISIT, Wm4::Vector3< Real >::X(), Base::Vector3< float_type >::x, Wm4::Vector3< Real >::Y(), Base::Vector3< float_type >::y, Wm4::Vector3< Real >::Z(), and Base::Vector3< float_type >::z.
Referenced by Mesh::MeshObject::optimizeEdges().
BeginCache()
void MeshTopoAlgorithm::BeginCache ()
Caching facility.
Definition at line 831 of file TopoAlgorithm.cpp.
Cleanup()
void MeshTopoAlgorithm::Cleanup ()
Removes all invalid marked elements from the mesh structure.
Definition at line 899 of file TopoAlgorithm.cpp.
References MeshCore::MeshKernel::RemoveInvalids().
Referenced by MeshCore::MeshRemoveNeedles::Fixup(), MeshCore::MeshFixMergeFacets::Fixup(), MeshPart::MeshAlgos::offsetSpecial2(), Mesh::MeshObject::offsetSpecial2(), and ~MeshTopoAlgorithm().
CollapseEdge() [1/2]
bool MeshTopoAlgorithm::CollapseEdge (const EdgeCollapse & ec)
Convenience function that passes already all needed information.
Definition at line 1097 of file TopoAlgorithm.cpp.
References MeshCore::EdgeCollapse::_changeFacets, MeshCore::EdgeCollapse::_fromPoint, MeshCore::EdgeCollapse::_removeFacets, MeshCore::EdgeCollapse::_toPoint, SCL.SimpleDataTypes::f, MeshCore::FACET_INDEX_MAX, DraftVecUtils::find(), and MeshCore::MeshFacet::ReplaceNeighbour().
CollapseEdge() [2/2]
bool MeshTopoAlgorithm::CollapseEdge (FacetIndex ulFacetPos, FacetIndex ulNeighbour)
Collapses the common edge of two adjacent facets. This operation removes one common point of the collapsed edge and the facets ulFacetPos and ulNeighbour from the data structure.
Note
If ulNeighbour is the neighbour facet on the i-th side of ulFacetPos then the i-th point is removed whereas i is 0, 1 or 2. If the other common point should be removed then CollapseEdge() should be invoked with swapped arguments of ulFacetPos and ulNeighbour, i.e. CollapseEdge(ulNeighbour, ulFacetPos).
The client programmer must make sure that this is a legal operation.
This method marks the facets and the point as 'invalid' but does not remove them from the mesh structure, i.e. the mesh structure gets into an inconsistent stage. To make the structure consistent again Cleanup() should be called. The reason why this cannot be done automatically is that it would become quite slow if a lot of edges should be collapsed.
While the mesh structure has invalid elements the client programmer must take care not to use such elements.
Definition at line 975 of file TopoAlgorithm.cpp.
References MeshCore::MeshFacet::_aulNeighbours, MeshCore::MeshFacet::_aulPoints, MeshCore::FACET_INDEX_MAX, MeshCore::MeshFacet::IsValid(), MeshCore::MeshFacet::SetInvalid(), MeshCore::MeshFacet::Side(), and MeshCore::MeshFacet::Transpose().
Referenced by Mesh::MeshObject::collapseEdge(), and MeshCore::MeshRemoveNeedles::Fixup().
CollapseFacet()
bool MeshTopoAlgorithm::CollapseFacet (FacetIndex ulFacetPos)
Removes the facet with index ulFacetPos and all its neighbour facets. The three vertices that are referenced by this facet are replaced by its gravity point.
Note
The client programmer must make sure that this is a legal operation.
This method marks the facets and the point as 'invalid' but does not remove them from the mesh structure, i.e. the mesh structure gets into an inconsistent stage. To make the structure consistent again Cleanup() should be called. The reason why this cannot be done automatically is that it would become quite slow if a lot of facets should be collapsed.
While the mesh structure has invalid elements the client programmer must take care not to use such elements.
Definition at line 1139 of file TopoAlgorithm.cpp.
References MeshCore::MeshFacet::_aulNeighbours, MeshCore::MeshFacet::_aulPoints, MeshCore::FACET_INDEX_MAX, MeshCore::MeshKernel::GetGravityPoint(), MeshCore::MeshFacet::IsValid(), MeshCore::MeshFacet::SetInvalid(), MeshCore::MeshFacet::Side(), and MeshCore::MeshFacet::Transpose().
Referenced by Mesh::MeshObject::collapseFacet(), Mesh::MeshObject::collapseFacets(), MeshPart::MeshAlgos::offsetSpecial2(), and Mesh::MeshObject::offsetSpecial2().
CollapseVertex()
bool MeshTopoAlgorithm::CollapseVertex (const VertexCollapse & vc)
Collapse a vertex. At the moment only removing inner vertexes referenced by three facets is supposrted.
Definition at line 905 of file TopoAlgorithm.cpp.
References MeshCore::MeshFacet::_aulNeighbours, MeshCore::VertexCollapse::_circumFacets, MeshCore::VertexCollapse::_circumPoints, MeshCore::VertexCollapse::_point, MeshCore::FACET_INDEX_MAX, DraftVecUtils::find(), MeshCore::MeshFacet::HasPoint(), SplineSurface::i, MeshCore::POINT_INDEX_MAX, MeshCore::MeshFacet::ReplaceNeighbour(), MeshCore::MeshFacet::SetInvalid(), and MeshCore::MeshFacet::Transpose().
Referenced by MeshCore::MeshFixMergeFacets::Fixup().
DelaunayFlip() [1/2]
int MeshTopoAlgorithm::DelaunayFlip ()
Overloaded method DelaunayFlip that doesn't use ShouldSwapEdge to check for legal swap edge.
Definition at line 408 of file TopoAlgorithm.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, MeshCore::MeshFacet::_aulNeighbours, src.Mod.PartDesign.Scripts.Gear::c1, MeshCore::MeshGeomFacet::CenterOfCircumCircle(), Base::DistanceP2(), MeshCore::FACET_INDEX_MAX, MeshCore::MeshKernel::GetFacet(), SplineSurface::i, MeshCore::MeshFacet::IsFlag(), MeshCore::MeshFacetArray::ResetFlag(), MeshCore::MeshFacet::SetFlag(), MeshCore::MeshFacet::Side(), SwapEdge(), and MeshCore::MeshFacet::TMP0.
DelaunayFlip() [2/2]
void MeshTopoAlgorithm::DelaunayFlip (float fMaxAngle)
Tries to make a more beautiful mesh by swapping the common edge of two adjacent facets where needed. A swap is needed where two adjacent facets don't fulfill the Delaunay condition.
Definition at line 354 of file TopoAlgorithm.cpp.
References MeshCore::MeshFacet::_aulNeighbours, MeshCore::MeshFacet::_aulPoints, exportCSG::center(), MeshCore::MeshGeomFacet::CenterOfCircumCircle(), Base::DistanceP2(), MeshCore::FACET_INDEX_MAX, MeshCore::MeshKernel::GetFacet(), MeshCore::MeshKernel::GetPoint(), SplineSurface::i, ShouldSwapEdge(), MeshCore::MeshFacet::Side(), and SwapEdge().
EndCache()
void MeshTopoAlgorithm::EndCache ()
Definition at line 841 of file TopoAlgorithm.cpp.
Referenced by ~MeshTopoAlgorithm().
FillupHoles() [1/2]
void MeshTopoAlgorithm::FillupHoles (int level, AbstractPolygonTriangulator & cTria, const std::list< std::vector< PointIndex >> & aBorders, std::list< std::vector< PointIndex >> & aFailed)
This is an overloaded method provided for convenience. It takes as first argument the boundaries which must be filled up.
Definition at line 1660 of file TopoAlgorithm.cpp.
References Base::BoundBox3< Precision >::Add(), MeshCore::MeshKernel::AddFacets(), Base::Console(), MeshCore::MeshKernel::CountPoints(), MeshCore::MeshAlgorithm::FillupHole(), SplineSurface::i, level(), Base::ConsoleSingleton::Log(), MeshCore::AbstractPolygonTriangulator::NeedsReindexing(), and updateLeaderLines::newPoints.
FillupHoles() [2/2]
void MeshTopoAlgorithm::FillupHoles (unsigned long length, int level, AbstractPolygonTriangulator & cTria, std::list< std::vector< PointIndex >> & aFailed)
Closes holes in the mesh that consists of up to length edges. In case a fit needs to be done then the points of the neighbours of level rings will be used. Holes for which the triangulation failed are returned in aFailed.
Definition at line 1636 of file TopoAlgorithm.cpp.
References MeshCore::MeshAlgorithm::GetMeshBorders(), level(), and MeshCore::MeshAlgorithm::SplitBoundaryLoops().
Referenced by Mesh::MeshObject::fillupHoles().
FindComponents()
void MeshTopoAlgorithm::FindComponents (unsigned long count, std::vector< FacetIndex > & findIndices)
Find topologic independent components with maximum count facets and returns an array of the indices.
Definition at line 1752 of file TopoAlgorithm.cpp.
References src.Mod.AddonManager.NetworkManager::count, MeshCore::MeshComponents::OverEdge, MeshCore::MeshComponents::SearchForComponents(), and segments.
Referenced by Mesh::MeshObject::removeComponents(), and RemoveComponents().
FindHoles()
void MeshTopoAlgorithm::FindHoles (unsigned long length, std::list< std::vector< PointIndex >> & aBorders) const
Find holes which consists of up to length edges.
Definition at line 1739 of file TopoAlgorithm.cpp.
References MeshCore::MeshAlgorithm::GetMeshBorders().
FlipNormals()
void MeshTopoAlgorithm::FlipNormals ()
Flips the normals.
Definition at line 1782 of file TopoAlgorithm.cpp.
References SplineSurface::i.
Referenced by Mesh::MeshObject::flipNormals().
HarmonizeNormals()
void MeshTopoAlgorithm::HarmonizeNormals ()
Harmonizes the normals.
Definition at line 1774 of file TopoAlgorithm.cpp.
References MeshCore::MeshEvalOrientation::GetIndices().
Referenced by MeshCore::MeshFixOrientation::Fixup(), and Mesh::MeshObject::harmonizeNormals().
InsertVertex()
bool MeshTopoAlgorithm::InsertVertex (FacetIndex ulFacetPos, const Base::Vector3f & rclPoint)
Inserts a new vertex in the given triangle so that is split into three triangles. The given point must lie inside the triangle not outside or on an edge.
Definition at line 57 of file TopoAlgorithm.cpp.
References MeshCore::MeshFacet::_aulNeighbours, MeshCore::MeshFacet::_aulPoints, and MeshCore::FACET_INDEX_MAX.
Referenced by Mesh::MeshObject::insertVertex(), and InsertVertexAndSwapEdge().
InsertVertexAndSwapEdge()
bool MeshTopoAlgorithm::InsertVertexAndSwapEdge (FacetIndex ulFacetPos, const Base::Vector3f & rclPoint, float fMaxAngle)
This method is provided for convenience. It inserts a new vertex to the mesh and tries to swap the common edges of the newly created facets with their neighbours. Just inserting a new vertex leads to very acute-angled triangles which might be problematic for some algorithms. This method tries to swap the edges to build more well-formed triangles.
See also
InsertVertex(), ShouldSwapEdge(), SwapEdge().
Definition at line 548 of file TopoAlgorithm.cpp.
References MeshCore::MeshFacet::_aulNeighbours, MeshCore::FACET_INDEX_MAX, InsertVertex(), ShouldSwapEdge(), and SwapEdge().
Referenced by Mesh::MeshObject::refine().
IsCollapseEdgeLegal()
bool MeshTopoAlgorithm::IsCollapseEdgeLegal (const EdgeCollapse & ec) const
Checks whether a collapse edge operation is legal, that is fulfilled if none of the adjacent facets flips its normal. If this operation is legal true is returned, false is returned if this operation is illegal.
Definition at line 1040 of file TopoAlgorithm.cpp.
References MeshCore::EdgeCollapse::_adjacentFrom, MeshCore::EdgeCollapse::_adjacentTo, MeshCore::EdgeCollapse::_changeFacets, MeshCore::EdgeCollapse::_fromPoint, MeshCore::EdgeCollapse::_removeFacets, MeshCore::EdgeCollapse::_toPoint, SCL.SimpleDataTypes::f, MeshCore::MeshKernel::GetFacet(), and MeshCore::MeshGeomFacet::GetNormal().
Referenced by MeshCore::MeshRemoveNeedles::Fixup().
IsSwapEdgeLegal()
bool MeshTopoAlgorithm::IsSwapEdgeLegal (FacetIndex ulFacetPos, FacetIndex ulNeighbour) const
Checks whether a swap edge operation is legal, that is fulfilled if the two adjacent facets builds a convex polygon. If this operation is legal true is returned, false is returned if this operation is illegal or if ulFacetPos and ulNeighbour are not adjacent facets.
Definition at line 595 of file TopoAlgorithm.cpp.
References MeshCore::MeshFacet::_aulPoints, MeshCore::MeshDefinitions::_fMinPointDistanceP2, MeshCore::MeshGeomFacet::IsDegenerated(), and MeshCore::MeshFacet::Side().
Referenced by AdjustEdgesToCurvatureDirection(), and ShouldSwapEdge().
operator=() [1/2]
MeshTopoAlgorithm& MeshCore::MeshTopoAlgorithm::operator= (const MeshTopoAlgorithm &) delete
operator=() [2/2]
MeshTopoAlgorithm& MeshCore::MeshTopoAlgorithm::operator= (MeshTopoAlgorithm &&) delete
OptimizeTopology() [1/2]
void MeshTopoAlgorithm::OptimizeTopology ()
Definition at line 310 of file TopoAlgorithm.cpp.
References SCL.SimpleDataTypes::b, MeshCore::MeshKernel::CountFacets(), SCL.SimpleDataTypes::e, SCL.SimpleDataTypes::f, MeshCore::MeshKernel::GetFacets(), SplineSurface::i, SwapEdge(), SwapEdgeBenefit(), and draftutils.todo::todo.
OptimizeTopology() [2/2]
void MeshTopoAlgorithm::OptimizeTopology (float fMaxAngle)
Tries to make a more beautiful mesh by swapping the common edge of two adjacent facets where needed. fMaxAngle is the maximum allowed angle between the normals of two adjacent facets to allow swapping the common edge. A too high value might result into folds on the surface.
Note
This is a high-level operation and tries to optimize the mesh as a whole.
Definition at line 143 of file TopoAlgorithm.cpp.
References MeshCore::MeshFacet::_aulPoints, MeshCore::FACET_INDEX_MAX, SplineSurface::i, ShouldSwapEdge(), MeshCore::MeshFacet::Side(), and SwapEdge().
Referenced by Mesh::MeshObject::optimizeTopology().
RemoveComponents()
void MeshTopoAlgorithm::RemoveComponents (unsigned long count)
Removes topologic independent components with maximum count facets.
Definition at line 1765 of file TopoAlgorithm.cpp.
References src.Mod.AddonManager.NetworkManager::count, MeshCore::MeshKernel::DeleteFacets(), and FindComponents().
RemoveCorruptedFacet()
bool MeshTopoAlgorithm::RemoveCorruptedFacet (FacetIndex index)
Removes the corrupted facet at position index from the mesh structure. A facet is corrupted if the indices of its corner points are not all different.
Definition at line 1605 of file TopoAlgorithm.cpp.
References MeshCore::MeshFacet::_aulNeighbours, MeshCore::MeshFacet::_aulPoints, MeshCore::MeshKernel::DeleteFacet(), MeshCore::FACET_INDEX_MAX, and SplineSurface::i.
Referenced by MeshCore::MeshFixCorruptedFacets::Fixup().
RemoveDegeneratedFacet()
bool MeshTopoAlgorithm::RemoveDegeneratedFacet (FacetIndex index)
Removes the degenerated facet at position index from the mesh structure. A facet is degenerated if its corner points are collinear.
Definition at line 1529 of file TopoAlgorithm.cpp.
References MeshCore::MeshFacet::_aulNeighbours, MeshCore::MeshFacet::_aulPoints, MeshCore::MeshKernel::DeleteFacet(), MeshCore::FACET_INDEX_MAX, SplineSurface::i, and MeshCore::MeshFacet::Side().
Referenced by MeshCore::MeshFixDegeneratedFacets::Fixup().
ShouldSwapEdge()
bool MeshTopoAlgorithm::ShouldSwapEdge (FacetIndex ulFacetPos, FacetIndex ulNeighbour, float fMaxAngle) const
Checks whether the swap edge operation is legal and whether it makes sense. This operation only makes sense if the maximum angle of both facets is decreased and if the angle between the facet normals does not exceed fMaxAngle.
Definition at line 640 of file TopoAlgorithm.cpp.
References MeshCore::MeshFacet::_aulPoints, Base::Vector3< float_type >::GetAngle(), MeshCore::MeshGeomFacet::GetNormal(), IsSwapEdgeLegal(), MeshCore::MeshGeomFacet::MaximumAngle(), and MeshCore::MeshFacet::Side().
Referenced by DelaunayFlip(), MeshCore::MeshFixDeformedFacets::Fixup(), InsertVertexAndSwapEdge(), and OptimizeTopology().
SnapVertex()
bool MeshTopoAlgorithm::SnapVertex (FacetIndex ulFacetPos, const Base::Vector3f & rP)
Creates a new triangle with neighbour facet ulFacetPos and the vertex rclPoint whereat it must lie outside the given facet.
Note
The vertex rclPoint doesn't necessarily need to be a new vertex it can already be part of another triangle but the client programmer must make sure that no overlaps are created.
This operation might be useful to close gaps in a mesh.
Definition at line 107 of file TopoAlgorithm.cpp.
References MeshCore::MeshFacet::_aulNeighbours, MeshCore::MeshFacet::_aulPoints, MeshCore::MeshKernel::CountFacets(), Base::DistanceP2(), MeshCore::FACET_INDEX_MAX, FLOAT_EPS, MeshCore::MeshKernel::GetNormal(), MeshCore::MeshFacet::HasOpenEdge(), SplineSurface::i, Base::Vector3< float_type >::Length(), and SplitOpenEdge().
Referenced by Mesh::MeshObject::snapVertex().
SplitEdge()
bool MeshTopoAlgorithm::SplitEdge (FacetIndex ulFacetPos, FacetIndex ulNeighbour, const Base::Vector3f & rP)
Splits the common edge of the two adjacent facets with index ulFacetPos and ulNeighbour. The point rP must lie inside of one the given facets are on the common edge. The two facets get broken into four facets, i.e. that two new facets get created. If rP is coincident with a corner point nothing happens.
Definition at line 713 of file TopoAlgorithm.cpp.
References MeshCore::MeshFacet::_aulNeighbours, MeshCore::MeshFacet::_aulPoints, MeshCore::FACET_INDEX_MAX, and MeshCore::MeshFacet::Side().
Referenced by Mesh::MeshObject::splitEdge(), and Mesh::MeshObject::splitEdges().
SplitFacet()
void MeshTopoAlgorithm::SplitFacet (FacetIndex ulFacetPos, const Base::Vector3f & rP1, const Base::Vector3f & rP2)
Splits the facet with index ulFacetPos into up to three facets. The points rP1 and rP2 should lie on two different edges of the facet. This method splits up the both neighbour facets as well. If either rP1 or rP2 (probably due to a previous call of SplitFacet()) is coincident with a corner point then the facet is split into two facets. If both points are coincident with corner points of this facet nothing is done.
Definition at line 1207 of file TopoAlgorithm.cpp.
References MeshCore::MeshFacet::_aulPoints, Base::Distance(), and MESH_MIN_EDGE_LEN.
Referenced by MeshPart::MeshAlgos::cutByCurve(), and Mesh::MeshObject::splitFacet().
SplitOpenEdge()
bool MeshTopoAlgorithm::SplitOpenEdge (FacetIndex ulFacetPos, unsigned short uSide, const Base::Vector3f & rP)
Splits the facet with index ulFacetPos on the edge side uSide into two facets. This side must be an open edge otherwise nothing is done. The point rP must be near to this edge and must not be coincident with any corner vertices of the facet.
Definition at line 775 of file TopoAlgorithm.cpp.
References MeshCore::MeshFacet::_aulNeighbours, MeshCore::MeshFacet::_aulPoints, and MeshCore::FACET_INDEX_MAX.
Referenced by SnapVertex().
SwapEdge()
void MeshTopoAlgorithm::SwapEdge (FacetIndex ulFacetPos, FacetIndex ulNeighbour)
Swaps the common edge of two adjacent facets even if the operation might be illegal. To be sure that this operation is legal, check either with IsSwapEdgeLegal() or ShouldSwapEdge() before. An illegal swap edge operation can produce non-manifolds, degenerated facets or it might create a fold on the surface, i.e. geometric overlaps of several triangles.
Definition at line 681 of file TopoAlgorithm.cpp.
References MeshCore::MeshFacet::_aulNeighbours, MeshCore::MeshFacet::_aulPoints, MeshCore::FACET_INDEX_MAX, and MeshCore::MeshFacet::Side().
Referenced by AdjustEdgesToCurvatureDirection(), DelaunayFlip(), MeshCore::MeshFixCaps::Fixup(), MeshCore::MeshFixDeformedFacets::Fixup(), InsertVertexAndSwapEdge(), OptimizeTopology(), and Mesh::MeshObject::swapEdge().
SwapEdgeBenefit()
float MeshTopoAlgorithm::SwapEdgeBenefit (FacetIndex f, int e) const
Computes a value for the benefit of swapping the edge.
Definition at line 279 of file TopoAlgorithm.cpp.
References SCL.SimpleDataTypes::e, SCL.SimpleDataTypes::f, MeshCore::FACET_INDEX_MAX, MeshCore::MeshKernel::GetFacets(), MeshCore::MeshKernel::GetPoints(), toolbit-attributes::s, swap_benefit(), and draftgeoutils.general::v1().
Referenced by OptimizeTopology().
The documentation for this class was generated from the following files:
TopoAlgorithm.h
TopoAlgorithm.cpp