FreeCAD: Gui::SoFCVectorizeU3DAction Class Reference
Gui::SoFCVectorizeU3DAction Class Reference
#include <SoFCVectorizeU3DAction.h>
Public Member Functions
SoFCVectorizeU3DAction ()
~SoFCVectorizeU3DAction () override
SoU3DVectorOutput * getU3DOutput () const
Static Public Member Functions
static void initClass ()
Protected Member Functions
void beginTraversal (SoNode *node) override
void endTraversal (SoNode *node) override
void printHeader () const override
void printFooter () const override
void printBackground () const override
void printItem (const SoVectorizeItem *item) const override
void printViewport () const override
Friends
class SoFCVectorizeU3DActionP
Detailed Description
Definition at line 70 of file SoFCVectorizeU3DAction.h.
Constructor & Destructor Documentation
SoFCVectorizeU3DAction()
SoFCVectorizeU3DAction::SoFCVectorizeU3DAction ()
Definition at line 300 of file SoFCVectorizeU3DAction.cpp.
References SoFCVectorizeU3DActionP.
~SoFCVectorizeU3DAction()
SoFCVectorizeU3DAction::~SoFCVectorizeU3DAction () override
Definition at line 307 of file SoFCVectorizeU3DAction.cpp.
Member Function Documentation
beginTraversal()
void SoFCVectorizeU3DAction::beginTraversal (SoNode * node) override protected
Definition at line 325 of file SoFCVectorizeU3DAction.cpp.
endTraversal()
void SoFCVectorizeU3DAction::endTraversal (SoNode * node) override protected
Definition at line 330 of file SoFCVectorizeU3DAction.cpp.
getU3DOutput()
SoU3DVectorOutput * SoFCVectorizeU3DAction::getU3DOutput () const
Definition at line 313 of file SoFCVectorizeU3DAction.cpp.
Referenced by printHeader().
initClass()
void SoFCVectorizeU3DAction::initClass () static
Definition at line 294 of file SoFCVectorizeU3DAction.cpp.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
printBackground()
void SoFCVectorizeU3DAction::printBackground () const override protected
Definition at line 367 of file SoFCVectorizeU3DAction.cpp.
printFooter()
void SoFCVectorizeU3DAction::printFooter () const override protected
Definition at line 359 of file SoFCVectorizeU3DAction.cpp.
printHeader()
void SoFCVectorizeU3DAction::printHeader () const override protected
Definition at line 335 of file SoFCVectorizeU3DAction.cpp.
References Gui::SoU3DVectorOutput::getFileStream(), getU3DOutput(), Path.Post.scripts.refactored_centroid_post::str, and Base::tabs().
printItem()
void SoFCVectorizeU3DAction::printItem (const SoVectorizeItem * item) const override protected
Definition at line 386 of file SoFCVectorizeU3DAction.cpp.
References SoVectorizeItem::IMAGE, SoVectorizeItem::LINE, SoVectorizeItem::POINT, Gui::SoFCVectorizeU3DActionP::printImage(), Gui::SoFCVectorizeU3DActionP::printLine(), Gui::SoFCVectorizeU3DActionP::printPoint(), Gui::SoFCVectorizeU3DActionP::printText(), Gui::SoFCVectorizeU3DActionP::printTriangle(), SoVectorizeItem::TEXT, SoVectorizeItem::TRIANGLE, and SoVectorizeItem::type.
printViewport()
void SoFCVectorizeU3DAction::printViewport () const override protected
Definition at line 363 of file SoFCVectorizeU3DAction.cpp.
Friends And Related Function Documentation
SoFCVectorizeU3DActionP
friend class SoFCVectorizeU3DActionP friend
Definition at line 96 of file SoFCVectorizeU3DAction.h.
Referenced by SoFCVectorizeU3DAction().
The documentation for this class was generated from the following files:
SoFCVectorizeU3DAction.h
SoFCVectorizeU3DAction.cpp