FreeCAD: TechDrawGui::QGIViewDimension Class Reference
TechDrawGui::QGIViewDimension Class Reference
#include <QGIViewDimension.h>
Public Types
enum { Type = QGraphicsItem::UserType + 106 }
Public Types inherited from TechDrawGui::QGIView
enum { Type = QGraphicsItem::UserType + 101 }
Public Slots
void onPrettyChanged (int state)
void datumLabelDragged (bool ctrl)
void datumLabelDragFinished ()
void select (bool state)
void hover (bool state)
void updateDim ()
Public Member Functions
QGIViewDimension ()
~QGIViewDimension () override=default
void setViewPartFeature (TechDraw::DrawViewDimension *obj)
int type () const override
QRectF boundingRect () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
void drawBorder () override
void updateView (bool update=false) override
QColor prefNormalColor ()
QString getLabelText ()
void setPrettyPre ()
void setPrettySel ()
void setPrettyNormal ()
bool getGroupSelection () override
void setGroupSelection (bool isSelected) override
virtual QGIDatumLabel * getDatumLabel () const
void setNormalColorAll ()
TechDraw::DrawViewDimension * getDimFeat ()
Public Member Functions inherited from TechDrawGui::QGIView
QGIView ()
int type () const override
QRectF boundingRect () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
const char * getViewName () const
const std::string getViewNameAsString () const
void setViewFeature (TechDraw::DrawView *obj)
TechDraw::DrawView * getViewObject () const
MDIViewPage * getMDIViewPage () const
double getScale ()
void hideFrame ()
virtual bool getFrameState ()
virtual void toggleCache (bool state)
virtual void isVisible (bool state)
virtual bool isVisible ()
virtual void setGroupSelection (bool isSelected, const std::vector< std::string > &subNames)
virtual void drawCaption ()
virtual void rotateView ()
void makeMark (double xPos, double yPos, QColor color=Qt::red)
void makeMark (Base::Vector3d pos, QColor color=Qt::red)
void makeMark (QPointF pos, QColor color=Qt::red)
void setPosition (qreal xPos, qreal yPos)
qreal getY ()
bool isInnerView () const
void isInnerView (bool state)
QGIViewClip * getClipGroup ()
bool isSnapping ()
void snapPosition (QPointF &position)
void snapSectionView (const TechDraw::DrawViewSection *sectionView, QPointF &newPosition)
Base::Vector3d projItemPagePos (TechDraw::DrawViewPart *item)
void alignTo (QGraphicsItem *, const QString &alignment)
QColor prefNormalColor ()
QColor getNormalColor ()
void setNormalColor (QColor color)
QColor getPreColor ()
QColor getSelectColor ()
QColor getCurrentColor ()
void setCurrentColor (QColor color)
QColor getSettingColor ()
void setSettingColor (QColor color)
virtual void setStack (int z)
virtual void setStackFromVP ()
QFont getFont ()
void setFont (QFont font)
virtual void removeChild (QGIView *child)
virtual void addArbitraryItem (QGraphicsItem *qgi)
virtual void switchParentItem (QGIView *targetParent)
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
Protected Member Functions
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
Base::Vector2d getIsoRefOutsetPoint (const Base::BoundBox2d &labelRectangle, bool right) const
Base::Vector2d getIsoRefJointPoint (const Base::BoundBox2d &labelRectangle, bool right) const
Base::Vector2d getAsmeRefOutsetPoint (const Base::BoundBox2d &labelRectangle, bool right) const
Base::Vector2d getAsmeRefJointPoint (const Base::BoundBox2d &labelRectangle, bool right) const
bool constructDimensionLine (const Base::Vector2d &targetPoint, double lineAngle, double startPosition, double jointPosition, const Base::BoundBox2d &labelRectangle, int arrowCount, int standardStyle, bool flipArrows, std::vector< std::pair< double, bool >> &outputMarking) const
bool constructDimensionArc (const Base::Vector2d &arcCenter, double arcRadius, double endAngle, double startRotation, double handednessFactor, double jointRotation, const Base::BoundBox2d &labelRectangle, int arrowCount, int standardStyle, bool flipArrows, std::vector< std::pair< double, bool >> &outputMarking) const
void draw () override
void resetArrows () const
void drawArrows (int count, const Base::Vector2d positions[], double angles[], bool flipped, bool forcePoint=false) const
void drawSingleLine (QPainterPath &painterPath, const Base::Vector2d &lineOrigin, double lineAngle, double startPosition, double endPosition) const
void drawMultiLine (QPainterPath &painterPath, const Base::Vector2d &lineOrigin, double lineAngle, const std::vector< std::pair< double, bool >> &drawMarking) const
void drawSingleArc (QPainterPath &painterPath, const Base::Vector2d &arcCenter, double arcRadius, double startAngle, double endAngle) const
void drawMultiArc (QPainterPath &painterPath, const Base::Vector2d &arcCenter, double arcRadius, const std::vector< std::pair< double, bool >> &drawMarking) const
void drawDimensionLine (QPainterPath &painterPath, const Base::Vector2d &targetPoint, double lineAngle, double startPosition, double jointPosition, const Base::BoundBox2d &labelRectangle, int arrowCount, int standardStyle, bool flipArrows, bool forcePointStyle=false) const
void drawDimensionArc (QPainterPath &painterPath, const Base::Vector2d &arcCenter, double arcRadius, double endAngle, double startRotation, double jointAngle, const Base::BoundBox2d &labelRectangle, int arrowCount, int standardStyle, bool flipArrows) const
void drawDistanceExecutive (const Base::Vector2d &startPoint, const Base::Vector2d &endPoint, double lineAngle, const Base::BoundBox2d &labelRectangle, int standardStyle, int renderExtent, bool flipArrows) const
void drawDistanceOverride (const Base::Vector2d &startPoint, const Base::Vector2d &endPoint, double lineAngle, const Base::BoundBox2d &labelRectangle, int standardStyle, int renderExtent, bool flipArrows, double extensionAngle) const
void drawRadiusExecutive (const Base::Vector2d &centerPoint, const Base::Vector2d &midPoint, double radius, double endAngle, double startRotation, const Base::BoundBox2d &labelRectangle, double centerOverhang, int standardStyle, int renderExtent, bool flipArrow) const
void drawAreaExecutive (const Base::Vector2d &centerPoint, double area, const Base::BoundBox2d &labelRectangle, double centerOverhang, int standardStyle, int renderExtent, bool flipArrow) const
void drawDistance (TechDraw::DrawViewDimension *dimension, ViewProviderDimension *viewProvider) const
void drawRadius (TechDraw::DrawViewDimension *dimension, ViewProviderDimension *viewProvider) const
void drawDiameter (TechDraw::DrawViewDimension *dimension, ViewProviderDimension *viewProvider) const
void drawAngle (TechDraw::DrawViewDimension *dimension, ViewProviderDimension *viewProvider) const
void drawArea (TechDraw::DrawViewDimension *dimension, ViewProviderDimension *viewProvider) const
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
virtual void setSvgPens ()
virtual void setPens ()
Base::Vector3d findIsoDir (Base::Vector3d ortho) const
find the closest isometric axis given an ortho vector
Base::Vector3d findIsoExt (Base::Vector3d isoDir) const
find the iso extension direction corresponding to an iso dist direction
QString getPrecision ()
void arrowPositionsToFeature (const Base::Vector2d positions[]) const
void makeMarkC (double xPos, double yPos, QColor color=Qt::red) const
Protected Member Functions inherited from TechDrawGui::QGIView
QGIView * getQGIVByName (std::string name)
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
virtual QRectF customChildrenBoundingRect () const
void dumpRect (const char *text, QRectF rect)
Base::Reference< ParameterGrp > getParmGroupCol ()
Static Protected Member Functions
static double getAnglePlacementFactor (double testAngle, double endAngle, double startRotation)
static int compareAngleStraightness (double straightAngle, double leftAngle, double rightAngle, double leftStrikeFactor, double rightStrikeFactor)
static double getIsoStandardLinePlacement (double labelAngle)
static Base::Vector2d computePerpendicularIntersection (const Base::Vector2d &linePoint, const Base::Vector2d &perpendicularPoint, double lineAngle)
static Base::Vector2d computeExtensionLinePoints (const Base::Vector2d &originPoint, const Base::Vector2d &linePoint, double hintAngle, double overhangSize, double gapSize, Base::Vector2d &startPoint)
static double computeLineAndLabelAngles (const Base::Vector2d &rotationCenter, const Base::Vector2d &labelCenter, double lineLabelDistance, double &lineAngle, double &labelAngle)
static double computeLineStrikeFactor (const Base::BoundBox2d &labelRectangle, const Base::Vector2d &lineOrigin, double lineAngle, const std::vector< std::pair< double, bool >> &drawMarking)
static double computeArcStrikeFactor (const Base::BoundBox2d &labelRectangle, const Base::Vector2d &arcCenter, double arcRadius, const std::vector< std::pair< double, bool >> &drawMarking)
static double normalizeStartPosition (double &startPosition, double &lineAngle)
static double normalizeStartRotation (double &startRotation)
Additional Inherited Members
Static Public Member Functions inherited from TechDrawGui::QGIView
static Gui::ViewProvider * getViewProvider (App::DocumentObject *obj)
static ViewProviderPage * getViewProviderPage (TechDraw::DrawView *dView)
static int calculateFontPixelSize (double sizeInMillimetres)
static int calculateFontPixelWidth (const QFont &font)
static QString getPrefFont ()
static double getPrefFontSize ()
static double getDimFontSize ()
static int exactFontSize (std::string fontFamily, double nominalSize)
Static Public Attributes inherited from TechDrawGui::QGIView
static const double DefaultFontSizeInMM = 5.0
Detailed Description
Definition at line 160 of file QGIViewDimension.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 165 of file QGIViewDimension.h.
Constructor & Destructor Documentation
QGIViewDimension()
QGIViewDimension::QGIViewDimension ()
Definition at line 631 of file QGIViewDimension.cpp.
References draftgeoutils.intersections::connect(), datumLabelDragFinished(), datumLabelDragged(), ZVALUE::DIMENSION, TechDrawGui::QGIDatumLabel::dragFinished(), TechDrawGui::QGIDatumLabel::dragging(), TechDrawGui::QGIView::hideFrame(), TechDrawGui::QGIDatumLabel::hover(), hover(), onPrettyChanged(), select(), TechDrawGui::QGIDatumLabel::selected(), TechDrawGui::QGIDatumLabel::setPretty(), TechDrawGui::QGIDatumLabel::setQDim(), and TechDrawGui::QGIPrimPath::setStyle().
~QGIViewDimension()
TechDrawGui::QGIViewDimension::~QGIViewDimension () override default
Member Function Documentation
arrowPositionsToFeature()
void QGIViewDimension::arrowPositionsToFeature (const Base::Vector2d positions[]) const protected
Definition at line 1482 of file QGIViewDimension.cpp.
References TechDrawGui::QGIView::getViewObject().
Referenced by drawArrows().
boundingRect()
QRectF QGIViewDimension::boundingRect () const override
Definition at line 2946 of file QGIViewDimension.cpp.
References TechDrawGui::QGIDimLines::boundingRect(), TechDrawGui::QGIDatumLabel::boundingRect(), and result.
compareAngleStraightness()
int QGIViewDimension::compareAngleStraightness (double straightAngle, double leftAngle, double rightAngle, double leftStrikeFactor, double rightStrikeFactor) static protected
Definition at line 1016 of file QGIViewDimension.cpp.
References M_PI, and Base::sgn().
Referenced by drawAngle(), drawDiameter(), drawDistanceExecutive(), drawDistanceOverride(), and drawRadiusExecutive().
computeArcStrikeFactor()
double QGIViewDimension::computeArcStrikeFactor (const Base::BoundBox2d & labelRectangle, const Base::Vector2d & arcCenter, double arcRadius, const std::vector< std::pair< double, bool >> & drawMarking) static protected
Definition at line 1186 of file QGIViewDimension.cpp.
References M_2PI.
Referenced by drawAngle().
computeExtensionLinePoints()
Base::Vector2d QGIViewDimension::computeExtensionLinePoints (const Base::Vector2d & originPoint, const Base::Vector2d & linePoint, double hintAngle, double overhangSize, double gapSize, Base::Vector2d & startPoint) static protected
Definition at line 1093 of file QGIViewDimension.cpp.
References Base::Vector2d::FromPolar(), and Base::Vector2d::Length().
Referenced by drawAngle(), drawDistanceExecutive(), and drawDistanceOverride().
computeLineAndLabelAngles()
double QGIViewDimension::computeLineAndLabelAngles (const Base::Vector2d & rotationCenter, const Base::Vector2d & labelCenter, double lineLabelDistance, double & lineAngle, double & labelAngle) static protected
Definition at line 1120 of file QGIViewDimension.cpp.
References Base::Vector2d::Angle(), KDL::asin(), getIsoStandardLinePlacement(), Base::Vector2d::Length(), and M_PI.
Referenced by drawAreaExecutive(), drawDiameter(), and drawRadiusExecutive().
computeLineStrikeFactor()
double QGIViewDimension::computeLineStrikeFactor (const Base::BoundBox2d & labelRectangle, const Base::Vector2d & lineOrigin, double lineAngle, const std::vector< std::pair< double, bool >> & drawMarking) static protected
Definition at line 1153 of file QGIViewDimension.cpp.
Referenced by drawDiameter(), drawDistanceExecutive(), drawDistanceOverride(), and drawRadiusExecutive().
computePerpendicularIntersection()
Base::Vector2d QGIViewDimension::computePerpendicularIntersection (const Base::Vector2d & linePoint, const Base::Vector2d & perpendicularPoint, double lineAngle) static protected
Definition at line 1078 of file QGIViewDimension.cpp.
References Base::Vector2d::FromPolar().
Referenced by drawDistanceExecutive().
constructDimensionArc()
bool QGIViewDimension::constructDimensionArc (const Base::Vector2d & arcCenter, double arcRadius, double endAngle, double startRotation, double handednessFactor, double jointRotation, const Base::BoundBox2d & labelRectangle, int arrowCount, int standardStyle, bool flipArrows, std::vector< std::pair< double, bool >> & outputMarking) const protected
Definition at line 1325 of file QGIViewDimension.cpp.
References KDL::atan(), Base::Console(), Base::ConsoleSingleton::Error(), Base::BoundBox2d::GetCenter(), FreeCADInit::Length, TechDrawGui::ViewProviderDimension::STD_STYLE_ASME_INLINED, TechDrawGui::ViewProviderDimension::STD_STYLE_ASME_REFERENCING, TechDrawGui::ViewProviderDimension::STD_STYLE_ISO_ORIENTED, and Base::BoundBox2d::Width().
Referenced by drawAngle(), and drawDimensionArc().
constructDimensionLine()
bool QGIViewDimension::constructDimensionLine (const Base::Vector2d & targetPoint, double lineAngle, double startPosition, double jointPosition, const Base::BoundBox2d & labelRectangle, int arrowCount, int standardStyle, bool flipArrows, std::vector< std::pair< double, bool >> & outputMarking) const protected
Definition at line 1254 of file QGIViewDimension.cpp.
References Base::Console(), Base::ConsoleSingleton::Error(), Base::BoundBox2d::GetCenter(), FreeCADInit::Length, TechDrawGui::ViewProviderDimension::STD_STYLE_ASME_INLINED, TechDrawGui::ViewProviderDimension::STD_STYLE_ASME_REFERENCING, TechDrawGui::ViewProviderDimension::STD_STYLE_ISO_ORIENTED, and Base::BoundBox2d::Width().
Referenced by drawDiameter(), drawDimensionLine(), drawDistanceExecutive(), drawDistanceOverride(), and drawRadiusExecutive().
datumLabelDragFinished
void QGIViewDimension::datumLabelDragFinished () slot
Definition at line 866 of file QGIViewDimension.cpp.
References TechDrawGui::Rez::appX(), Gui::Command::commitCommand(), Gui::Command::Doc, doCommand, TechDrawGui::QGIView::getViewObject(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, MovieTool::x, TechDrawGui::QGIDatumLabel::X(), MovieTool::y, and TechDrawGui::QGIDatumLabel::Y().
Referenced by QGIViewDimension().
datumLabelDragged
void QGIViewDimension::datumLabelDragged (bool ctrl) slot
Definition at line 860 of file QGIViewDimension.cpp.
References draw().
Referenced by QGIViewDimension().
draw()
void QGIViewDimension::draw () override protected virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 897 of file QGIViewDimension.cpp.
References Base::Console(), drawAngle(), drawArea(), drawArrows(), drawDiameter(), drawDistance(), drawRadius(), Base::ConsoleSingleton::Error(), TechDrawGui::QGIView::getViewObject(), TechDrawGui::QGIView::getViewProvider(), TechDrawGui::Rez::guiX(), TechDraw::DrawViewDimension::has2DReferences(), TechDraw::DrawViewPart::hasGeometry(), ArchFence::hide(), TechDrawGui::QGIView::isVisible(), TechDrawGui::ViewProviderDimension::REND_EXTENT_NONE, resetArrows(), setPrettyNormal(), setPrettyPre(), setPrettySel(), and bimcommands.BimViews::show().
Referenced by datumLabelDragged(), hover(), itemChange(), select(), setViewPartFeature(), and updateView().
drawAngle()
void QGIViewDimension::drawAngle (TechDraw::DrawViewDimension * dimension, ViewProviderDimension * viewProvider) const protected
Definition at line 2582 of file QGIViewDimension.cpp.
References Base::Vector2d::Angle(), TechDrawGui::Rez::appX(), TechDrawGui::QGIDatumLabel::boundingRect(), compareAngleStraightness(), computeArcStrikeFactor(), computeExtensionLinePoints(), Base::Console(), constructDimensionArc(), drawDimensionArc(), Base::ConsoleSingleton::Error(), TechDraw::anglePoints::first(), TechDrawGui::ViewProviderDimension::FlipArrowheads, Base::Vector2d::FromPolar(), getAsmeRefJointPoint(), getAsmeRefOutsetPoint(), Base::BoundBox2d::GetCenter(), getIsoRefJointPoint(), getIsoRefOutsetPoint(), getIsoStandardLinePlacement(), App::PropertyEnumeration::getValue(), App::PropertyBool::getValue(), TechDrawGui::QGIView::getViewObject(), TechDrawGui::QGIView::getViewProvider(), Base::BoundBox2d::Height(), Base::Vector2d::Length(), M_2PI, M_PI, M_PI_2, normalizeStartRotation(), TechDrawGui::ViewProviderDimension::REND_EXTENT_CONFINED, TechDrawGui::ViewProviderDimension::REND_EXTENT_NORMAL, TechDrawGui::ViewProviderDimension::REND_EXTENT_REDUCED, TechDrawGui::ViewProviderDimension::RenderingExtent, TechDraw::anglePoints::second(), TechDrawGui::ViewProviderDimension::StandardAndStyle, TechDrawGui::ViewProviderDimension::STD_STYLE_ASME_INLINED, TechDrawGui::ViewProviderDimension::STD_STYLE_ASME_REFERENCING, TechDrawGui::ViewProviderDimension::STD_STYLE_ISO_ORIENTED, TechDrawGui::ViewProviderDimension::STD_STYLE_ISO_REFERENCING, and TechDraw::anglePoints::vertex().
Referenced by draw().
drawArea()
void QGIViewDimension::drawArea (TechDraw::DrawViewDimension * dimension, ViewProviderDimension * viewProvider) const protected
Definition at line 2774 of file QGIViewDimension.cpp.
References TechDraw::areaPoint::area, TechDrawGui::QGIDatumLabel::boundingRect(), TechDraw::areaPoint::center, drawAreaExecutive(), TechDrawGui::ViewProviderDimension::FlipArrowheads, App::PropertyEnumeration::getValue(), App::PropertyBool::getValue(), TechDrawGui::ViewProviderDimension::RenderingExtent, and TechDrawGui::ViewProviderDimension::StandardAndStyle.
Referenced by draw().
drawAreaExecutive()
void QGIViewDimension::drawAreaExecutive (const Base::Vector2d & centerPoint, double area, const Base::BoundBox2d & labelRectangle, double centerOverhang, int standardStyle, int renderExtent, bool flipArrow) const protected
Definition at line 2276 of file QGIViewDimension.cpp.
References Base::Vector2d::Angle(), TechDrawGui::QGIDatumLabel::boundingRect(), computeLineAndLabelAngles(), Base::Console(), KDL::cos(), drawDimensionLine(), Base::ConsoleSingleton::Error(), getAsmeRefJointPoint(), getAsmeRefOutsetPoint(), Base::BoundBox2d::GetCenter(), getIsoRefJointPoint(), getIsoRefOutsetPoint(), Base::BoundBox2d::Height(), Base::Vector2d::Length(), FreeCADInit::Length, M_PI, TechDrawGui::ViewProviderDimension::STD_STYLE_ASME_INLINED, TechDrawGui::ViewProviderDimension::STD_STYLE_ASME_REFERENCING, TechDrawGui::ViewProviderDimension::STD_STYLE_ISO_ORIENTED, TechDrawGui::ViewProviderDimension::STD_STYLE_ISO_REFERENCING, and Base::Vector2d::x.
Referenced by drawArea().
drawArrows()
void QGIViewDimension::drawArrows (int count, const Base::Vector2d positions[], double angles[], bool flipped, bool forcePoint = false) const protected
Definition at line 1444 of file QGIViewDimension.cpp.
References arrowPositionsToFeature(), TechDrawGui::ViewProviderDimension::Arrowsize, src.Mod.AddonManager.NetworkManager::count, TechDrawGui::QGIArrow::draw(), TechDrawGui::QGIArrow::getPrefArrowStyle(), App::PropertyQuantity::getValue(), TechDrawGui::QGIView::getViewObject(), TechDrawGui::QGIView::getViewProvider(), SplineSurface::i, TechDrawGui::QGIArrow::setDirection(), TechDrawGui::QGIArrow::setFlipped(), TechDrawGui::QGIArrow::setSize(), and TechDrawGui::QGIArrow::setStyle().
Referenced by draw(), drawDimensionArc(), and drawDimensionLine().
drawBorder()
void QGIViewDimension::drawBorder () override virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 2895 of file QGIViewDimension.cpp.
drawDiameter()
void QGIViewDimension::drawDiameter (TechDraw::DrawViewDimension * dimension, ViewProviderDimension * viewProvider) const protected
Definition at line 2417 of file QGIViewDimension.cpp.
References Base::Vector2d::Angle(), TechDrawGui::QGIDatumLabel::boundingRect(), TechDraw::arcPoints::center, compareAngleStraightness(), computeLineAndLabelAngles(), computeLineStrikeFactor(), Base::Console(), constructDimensionLine(), KDL::cos(), drawDimensionLine(), drawDistanceExecutive(), drawRadiusExecutive(), Base::ConsoleSingleton::Error(), TechDrawGui::ViewProviderDimension::FlipArrowheads, Base::Vector2d::FromPolar(), getAsmeRefJointPoint(), getAsmeRefOutsetPoint(), Base::BoundBox2d::GetCenter(), getIsoRefJointPoint(), getIsoRefOutsetPoint(), App::PropertyEnumeration::getValue(), App::PropertyBool::getValue(), TechDrawGui::Rez::guiX(), Base::BoundBox2d::Height(), Base::Vector2d::Length(), FreeCADInit::Length, M_2PI, M_PI, M_PI_2, TechDraw::arcPoints::midArc, TechDraw::arcPoints::radius, TechDrawGui::ViewProviderDimension::REND_EXTENT_CONFINED, TechDrawGui::ViewProviderDimension::REND_EXTENT_EXPANDED, TechDrawGui::ViewProviderDimension::REND_EXTENT_NORMAL, TechDrawGui::ViewProviderDimension::REND_EXTENT_REDUCED, TechDrawGui::ViewProviderDimension::RenderingExtent, TechDrawGui::ViewProviderDimension::StandardAndStyle, TechDrawGui::ViewProviderDimension::STD_STYLE_ASME_INLINED, TechDrawGui::ViewProviderDimension::STD_STYLE_ASME_REFERENCING, TechDrawGui::ViewProviderDimension::STD_STYLE_ISO_ORIENTED, TechDrawGui::ViewProviderDimension::STD_STYLE_ISO_REFERENCING, Base::Vector2d::x, and Base::Vector2d::y.
Referenced by draw().
drawDimensionArc()
void QGIViewDimension::drawDimensionArc (QPainterPath & painterPath, const Base::Vector2d & arcCenter, double arcRadius, double endAngle, double startRotation, double jointAngle, const Base::BoundBox2d & labelRectangle, int arrowCount, int standardStyle, bool flipArrows) const protected
Definition at line 1617 of file QGIViewDimension.cpp.
References constructDimensionArc(), drawArrows(), drawMultiArc(), Base::Vector2d::FromPolar(), M_2PI, M_PI, M_PI_2, and normalizeStartRotation().
Referenced by drawAngle().
drawDimensionLine()
void QGIViewDimension::drawDimensionLine (QPainterPath & painterPath, const Base::Vector2d & targetPoint, double lineAngle, double startPosition, double jointPosition, const Base::BoundBox2d & labelRectangle, int arrowCount, int standardStyle, bool flipArrows, bool forcePointStyle = false) const protected
Definition at line 1590 of file QGIViewDimension.cpp.
References constructDimensionLine(), drawArrows(), drawMultiLine(), Base::Vector2d::FromPolar(), M_PI, and normalizeStartPosition().
Referenced by drawAreaExecutive(), drawDiameter(), drawDistanceExecutive(), drawDistanceOverride(), and drawRadiusExecutive().
drawDistance()
void QGIViewDimension::drawDistance (TechDraw::DrawViewDimension * dimension, ViewProviderDimension * viewProvider) const protected
Definition at line 2349 of file QGIViewDimension.cpp.
References TechDrawGui::QGIDatumLabel::boundingRect(), drawDistanceExecutive(), drawDistanceOverride(), TechDraw::pointPair::extensionLineFirst(), TechDraw::pointPair::extensionLineSecond(), TechDraw::pointPair::first(), TechDrawGui::ViewProviderDimension::FlipArrowheads, App::PropertyEnumeration::getValue(), App::PropertyBool::getValue(), M_PI, M_PI_2, TechDrawGui::ViewProviderDimension::RenderingExtent, TechDraw::pointPair::second(), and TechDrawGui::ViewProviderDimension::StandardAndStyle.
Referenced by draw().
drawDistanceExecutive()
void QGIViewDimension::drawDistanceExecutive (const Base::Vector2d & startPoint, const Base::Vector2d & endPoint, double lineAngle, const Base::BoundBox2d & labelRectangle, int standardStyle, int renderExtent, bool flipArrows) const protected
Definition at line 1658 of file QGIViewDimension.cpp.
References TechDrawGui::Rez::appX(), TechDrawGui::QGIDatumLabel::boundingRect(), compareAngleStraightness(), computeExtensionLinePoints(), computeLineStrikeFactor(), computePerpendicularIntersection(), Base::Console(), constructDimensionLine(), drawDimensionLine(), Base::ConsoleSingleton::Error(), Base::Vector2d::FromPolar(), getAsmeRefJointPoint(), getAsmeRefOutsetPoint(), Base::BoundBox2d::GetCenter(), getIsoRefJointPoint(), getIsoRefOutsetPoint(), getIsoStandardLinePlacement(), TechDrawGui::QGIView::getViewObject(), TechDrawGui::QGIView::getViewProvider(), Base::BoundBox2d::Height(), M_PI, M_PI_2, normalizeStartPosition(), TechDrawGui::ViewProviderDimension::REND_EXTENT_CONFINED, TechDrawGui::ViewProviderDimension::REND_EXTENT_NORMAL, TechDrawGui::ViewProviderDimension::REND_EXTENT_REDUCED, TechDrawGui::ViewProviderDimension::STD_STYLE_ASME_INLINED, TechDrawGui::ViewProviderDimension::STD_STYLE_ASME_REFERENCING, TechDrawGui::ViewProviderDimension::STD_STYLE_ISO_ORIENTED, and TechDrawGui::ViewProviderDimension::STD_STYLE_ISO_REFERENCING.
Referenced by drawDiameter(), and drawDistance().
drawDistanceOverride()
void QGIViewDimension::drawDistanceOverride (const Base::Vector2d & startPoint, const Base::Vector2d & endPoint, double lineAngle, const Base::BoundBox2d & labelRectangle, int standardStyle, int renderExtent, bool flipArrows, double extensionAngle) const protected
Definition at line 1859 of file QGIViewDimension.cpp.
References TechDrawGui::Rez::appX(), TechDrawGui::QGIDatumLabel::boundingRect(), compareAngleStraightness(), computeExtensionLinePoints(), computeLineStrikeFactor(), Base::Console(), constructDimensionLine(), drawDimensionLine(), Base::ConsoleSingleton::Error(), Base::Vector2d::FromPolar(), getAsmeRefJointPoint(), getAsmeRefOutsetPoint(), Base::BoundBox2d::GetCenter(), getIsoRefJointPoint(), getIsoRefOutsetPoint(), getIsoStandardLinePlacement(), TechDrawGui::QGIView::getViewObject(), TechDrawGui::QGIView::getViewProvider(), Base::BoundBox2d::Height(), M_PI, M_PI_2, normalizeStartPosition(), TechDrawGui::ViewProviderDimension::REND_EXTENT_CONFINED, TechDrawGui::ViewProviderDimension::REND_EXTENT_NORMAL, TechDrawGui::ViewProviderDimension::REND_EXTENT_REDUCED, TechDrawGui::ViewProviderDimension::STD_STYLE_ASME_INLINED, TechDrawGui::ViewProviderDimension::STD_STYLE_ASME_REFERENCING, TechDrawGui::ViewProviderDimension::STD_STYLE_ISO_ORIENTED, TechDrawGui::ViewProviderDimension::STD_STYLE_ISO_REFERENCING, MovieTool::x, and MovieTool::y.
Referenced by drawDistance().
drawMultiArc()
void QGIViewDimension::drawMultiArc (QPainterPath & painterPath, const Base::Vector2d & arcCenter, double arcRadius, const std::vector< std::pair< double, bool >> & drawMarking) const protected
Definition at line 1550 of file QGIViewDimension.cpp.
References drawSingleArc(), and M_2PI.
Referenced by drawDimensionArc().
drawMultiLine()
void QGIViewDimension::drawMultiLine (QPainterPath & painterPath, const Base::Vector2d & lineOrigin, double lineAngle, const std::vector< std::pair< double, bool >> & drawMarking) const protected
Definition at line 1507 of file QGIViewDimension.cpp.
References drawSingleLine().
Referenced by drawDimensionLine().
drawRadius()
void QGIViewDimension::drawRadius (TechDraw::DrawViewDimension * dimension, ViewProviderDimension * viewProvider) const protected
Definition at line 2386 of file QGIViewDimension.cpp.
References TechDraw::arcPoints::arcCW, TechDraw::arcPoints::arcEnds, TechDrawGui::QGIDatumLabel::boundingRect(), TechDraw::arcPoints::center, drawRadiusExecutive(), TechDraw::pointPair::first(), TechDrawGui::ViewProviderDimension::FlipArrowheads, App::PropertyEnumeration::getValue(), App::PropertyBool::getValue(), TechDraw::arcPoints::isArc, M_2PI, M_PI, TechDraw::arcPoints::midArc, TechDraw::arcPoints::radius, TechDrawGui::ViewProviderDimension::RenderingExtent, TechDraw::pointPair::second(), and TechDrawGui::ViewProviderDimension::StandardAndStyle.
Referenced by draw().
drawRadiusExecutive()
void QGIViewDimension::drawRadiusExecutive (const Base::Vector2d & centerPoint, const Base::Vector2d & midPoint, double radius, double endAngle, double startRotation, const Base::BoundBox2d & labelRectangle, double centerOverhang, int standardStyle, int renderExtent, bool flipArrow) const protected
Definition at line 2066 of file QGIViewDimension.cpp.
References Base::Vector2d::Angle(), TechDrawGui::QGIDatumLabel::boundingRect(), compareAngleStraightness(), computeLineAndLabelAngles(), computeLineStrikeFactor(), Base::Console(), constructDimensionLine(), KDL::cos(), drawDimensionLine(), Base::ConsoleSingleton::Error(), Base::Vector2d::FromPolar(), getAnglePlacementFactor(), getAsmeRefJointPoint(), getAsmeRefOutsetPoint(), Base::BoundBox2d::GetCenter(), getIsoRefJointPoint(), getIsoRefOutsetPoint(), Base::BoundBox2d::Height(), Base::Vector2d::Length(), FreeCADInit::Length, M_PI, TechDrawGui::ViewProviderDimension::REND_EXTENT_NORMAL, TechDrawGui::ViewProviderDimension::STD_STYLE_ASME_INLINED, TechDrawGui::ViewProviderDimension::STD_STYLE_ASME_REFERENCING, TechDrawGui::ViewProviderDimension::STD_STYLE_ISO_ORIENTED, TechDrawGui::ViewProviderDimension::STD_STYLE_ISO_REFERENCING, and Base::Vector2d::x.
Referenced by drawDiameter(), and drawRadius().
drawSingleArc()
void QGIViewDimension::drawSingleArc (QPainterPath & painterPath, const Base::Vector2d & arcCenter, double arcRadius, double startAngle, double endAngle) const protected
Definition at line 1531 of file QGIViewDimension.cpp.
References M_2PI, Base::Vector2d::x, and Base::Vector2d::y.
Referenced by drawMultiArc().
drawSingleLine()
void QGIViewDimension::drawSingleLine (QPainterPath & painterPath, const Base::Vector2d & lineOrigin, double lineAngle, double startPosition, double endPosition) const protected
Definition at line 1492 of file QGIViewDimension.cpp.
References Base::Vector2d::FromPolar().
Referenced by drawMultiLine().
findIsoDir()
Base::Vector3d QGIViewDimension::findIsoDir (Base::Vector3d ortho) const protected
find the closest isometric axis given an ortho vector
Definition at line 2803 of file QGIViewDimension.cpp.
References Base::Vector3< float_type >::GetAngle(), SplineSurface::i, and KDL::min().
findIsoExt()
Base::Vector3d QGIViewDimension::findIsoExt (Base::Vector3d isoDir) const protected
find the iso extension direction corresponding to an iso dist direction
Definition at line 2827 of file QGIViewDimension.cpp.
References Base::Console(), TechDrawGui::QGIView::getViewObject(), Base::Vector3< float_type >::IsEqual(), and Base::ConsoleSingleton::Message().
getAnglePlacementFactor()
double QGIViewDimension::getAnglePlacementFactor (double testAngle, double endAngle, double startRotation) static protected
Definition at line 985 of file QGIViewDimension.cpp.
References M_2PI, and M_PI.
Referenced by drawRadiusExecutive().
getAsmeRefJointPoint()
Base::Vector2d QGIViewDimension::getAsmeRefJointPoint (const Base::BoundBox2d & labelRectangle, bool right) const protected
Definition at line 1064 of file QGIViewDimension.cpp.
References Base::BoundBox2d::GetCenter(), Base::BoundBox2d::MaxX, Base::BoundBox2d::MinX, and Base::Vector2d::y.
Referenced by drawAngle(), drawAreaExecutive(), drawDiameter(), drawDistanceExecutive(), drawDistanceOverride(), and drawRadiusExecutive().
getAsmeRefOutsetPoint()
Base::Vector2d QGIViewDimension::getAsmeRefOutsetPoint (const Base::BoundBox2d & labelRectangle, bool right) const protected
Definition at line 1057 of file QGIViewDimension.cpp.
References Base::BoundBox2d::GetCenter(), Base::BoundBox2d::MaxX, Base::BoundBox2d::MinX, and Base::Vector2d::y.
Referenced by drawAngle(), drawAreaExecutive(), drawDiameter(), drawDistanceExecutive(), drawDistanceOverride(), and drawRadiusExecutive().
getDatumLabel()
virtual QGIDatumLabel* TechDrawGui::QGIViewDimension::getDatumLabel () const inline virtual
Definition at line 187 of file QGIViewDimension.h.
getDimFeat()
TechDraw::DrawViewDimension* TechDrawGui::QGIViewDimension::getDimFeat () inline
Definition at line 190 of file QGIViewDimension.h.
Referenced by prefNormalColor().
getGroupSelection()
bool QGIViewDimension::getGroupSelection () override virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 704 of file QGIViewDimension.cpp.
getIsoRefJointPoint()
Base::Vector2d QGIViewDimension::getIsoRefJointPoint (const Base::BoundBox2d & labelRectangle, bool right) const protected
Definition at line 1051 of file QGIViewDimension.cpp.
References getIsoRefOutsetPoint().
Referenced by drawAngle(), drawAreaExecutive(), drawDiameter(), drawDistanceExecutive(), drawDistanceOverride(), and drawRadiusExecutive().
getIsoRefOutsetPoint()
Base::Vector2d QGIViewDimension::getIsoRefOutsetPoint (const Base::BoundBox2d & labelRectangle, bool right) const protected
Definition at line 1043 of file QGIViewDimension.cpp.
References Base::BoundBox2d::MaxX, Base::BoundBox2d::MinX, and Base::BoundBox2d::MinY.
Referenced by drawAngle(), drawAreaExecutive(), drawDiameter(), drawDistanceExecutive(), drawDistanceOverride(), drawRadiusExecutive(), and getIsoRefJointPoint().
getIsoStandardLinePlacement()
double QGIViewDimension::getIsoStandardLinePlacement (double labelAngle) static protected
Definition at line 1037 of file QGIViewDimension.cpp.
References M_PI.
Referenced by computeLineAndLabelAngles(), drawAngle(), drawDistanceExecutive(), and drawDistanceOverride().
getLabelText()
QString QGIViewDimension::getLabelText ()
Definition at line 884 of file QGIViewDimension.cpp.
References TechDrawGui::QGIDatumLabel::getDimText(), TechDrawGui::QGIDatumLabel::getTolTextOver(), and TechDrawGui::QGIDatumLabel::getTolTextUnder().
getPrecision()
QString TechDrawGui::QGIViewDimension::getPrecision () protected
hover
void QGIViewDimension::hover (bool state) slot
Definition at line 727 of file QGIViewDimension.cpp.
References draw().
Referenced by QGIViewDimension().
itemChange()
QVariant QGIViewDimension::itemChange (GraphicsItemChange change, const QVariant & value) override protected
Definition at line 682 of file QGIViewDimension.cpp.
References draw(), and TechDrawGui::QGIView::itemChange().
makeMarkC()
void QGIViewDimension::makeMarkC (double xPos, double yPos, QColor color = Qt::red) const protected
Definition at line 3005 of file QGIViewDimension.cpp.
References TechDrawGui::QGIPrimPath::setFillColor(), TechDrawGui::QGIPrimPath::setNormalColor(), TechDrawGui::QGIPrimPath::setPrettyNormal(), TechDrawGui::QGIVertex::setRadius(), TechDrawGui::QGIPrimPath::setWidth(), and ZVALUE::VERTEX.
mouseMoveEvent()
void QGIViewDimension::mouseMoveEvent (QGraphicsSceneMouseEvent * event) override protected
Definition at line 775 of file QGIViewDimension.cpp.
mousePressEvent()
void QGIViewDimension::mousePressEvent (QGraphicsSceneMouseEvent * event) override protected
Definition at line 769 of file QGIViewDimension.cpp.
mouseReleaseEvent()
void QGIViewDimension::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) override protected
Definition at line 780 of file QGIViewDimension.cpp.
normalizeStartPosition()
double QGIViewDimension::normalizeStartPosition (double & startPosition, double & lineAngle) static protected
Definition at line 1233 of file QGIViewDimension.cpp.
References M_PI.
Referenced by drawDimensionLine(), drawDistanceExecutive(), and drawDistanceOverride().
normalizeStartRotation()
double QGIViewDimension::normalizeStartRotation (double & startRotation) static protected
Definition at line 1244 of file QGIViewDimension.cpp.
Referenced by drawAngle(), and drawDimensionArc().
onPrettyChanged
void QGIViewDimension::onPrettyChanged (int state) slot
Definition at line 2860 of file QGIViewDimension.cpp.
References NORMAL, PRE, setPrettyNormal(), setPrettyPre(), and setPrettySel().
Referenced by QGIViewDimension().
paint()
void QGIViewDimension::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) override
Definition at line 2959 of file QGIViewDimension.cpp.
References setPens(), and setSvgPens().
prefNormalColor()
QColor QGIViewDimension::prefNormalColor ()
Definition at line 2786 of file QGIViewDimension.cpp.
References App::Color::asValue(), TechDrawGui::ViewProviderDimension::Color, TechDrawGui::PreferencesGui::dimQColor(), TechDrawGui::PreferencesGui::getAccessibleQColor(), getDimFeat(), TechDrawGui::QGIView::getNormalColor(), App::PropertyColor::getValue(), TechDrawGui::QGIView::getViewProvider(), and TechDrawGui::QGIView::setNormalColor().
Referenced by setNormalColorAll().
resetArrows()
void QGIViewDimension::resetArrows () const protected
Definition at line 1433 of file QGIViewDimension.cpp.
References TechDrawGui::QGIArrow::setDirMode(), and TechDrawGui::QGIArrow::setFlipped().
Referenced by draw().
select
void QGIViewDimension::select (bool state) slot
Definition at line 720 of file QGIViewDimension.cpp.
References draw().
Referenced by QGIViewDimension().
setGroupSelection()
void QGIViewDimension::setGroupSelection (bool isSelected) override virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 710 of file QGIViewDimension.cpp.
setNormalColorAll()
void QGIViewDimension::setNormalColorAll ()
Definition at line 756 of file QGIViewDimension.cpp.
References prefNormalColor(), TechDrawGui::QGIDatumLabel::setColor(), TechDrawGui::QGIPrimPath::setFillColor(), and TechDrawGui::QGIPrimPath::setNormalColor().
Referenced by TechDrawGui::ViewProviderDimension::onChanged(), and setViewPartFeature().
setPens()
void QGIViewDimension::setPens () protected virtual
Definition at line 2992 of file QGIViewDimension.cpp.
References TechDrawGui::QGIPrimPath::setWidth().
Referenced by paint().
setPrettyNormal()
void QGIViewDimension::setPrettyNormal ()
Definition at line 2888 of file QGIViewDimension.cpp.
References TechDrawGui::QGIPrimPath::setPrettyNormal().
Referenced by draw(), onPrettyChanged(), and setViewPartFeature().
setPrettyPre()
void QGIViewDimension::setPrettyPre ()
Definition at line 2874 of file QGIViewDimension.cpp.
References TechDrawGui::QGIPrimPath::setPrettyPre().
Referenced by draw(), and onPrettyChanged().
setPrettySel()
void QGIViewDimension::setPrettySel ()
Definition at line 2881 of file QGIViewDimension.cpp.
References TechDrawGui::QGIPrimPath::setPrettySel().
Referenced by draw(), and onPrettyChanged().
setSvgPens()
void QGIViewDimension::setSvgPens () protected virtual
Definition at line 2984 of file QGIViewDimension.cpp.
References TechDrawGui::QGIPrimPath::getWidth(), and TechDrawGui::QGIPrimPath::setWidth().
Referenced by paint().
setViewPartFeature()
void QGIViewDimension::setViewPartFeature (TechDraw::DrawViewDimension * obj)
Definition at line 733 of file QGIViewDimension.cpp.
References draw(), App::PropertyQuantity::getValue(), TechDrawGui::Rez::guiX(), setNormalColorAll(), TechDrawGui::QGIDatumLabel::setPosFromCenter(), setPrettyNormal(), TechDrawGui::QGIView::setViewFeature(), updateDim(), MovieTool::x, TechDraw::DrawView::X, MovieTool::y, and TechDraw::DrawView::Y.
type()
int TechDrawGui::QGIViewDimension::type () const inline override
Definition at line 171 of file QGIViewDimension.h.
updateDim
void QGIViewDimension::updateDim () slot
Definition at line 827 of file QGIViewDimension.cpp.
References TechDrawGui::QGIView::exactFontSize(), TechDrawGui::QGIDatumLabel::getFont(), TechDrawGui::QGIView::getViewObject(), TechDrawGui::QGIView::getViewProvider(), TechDrawGui::QGIDatumLabel::setDimString(), TechDrawGui::QGIDatumLabel::setFont(), TechDrawGui::QGIDatumLabel::setFramed(), TechDrawGui::QGIDatumLabel::setLineWidth(), TechDrawGui::QGIDatumLabel::setPosFromCenter(), TechDrawGui::QGIDatumLabel::setToleranceString(), TechDrawGui::QGIDatumLabel::X(), and TechDrawGui::QGIDatumLabel::Y().
Referenced by setViewPartFeature(), and updateView().
updateView()
void QGIViewDimension::updateView (bool update = false) override virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 786 of file QGIViewDimension.cpp.
References draw(), TechDrawGui::QGIView::getViewObject(), TechDrawGui::QGIView::getViewProvider(), TechDrawGui::Rez::guiX(), TechDrawGui::QGIDatumLabel::setPosFromCenter(), updateDim(), MovieTool::x, and MovieTool::y.
Referenced by TechDrawGui::TaskDimension::reject().
The documentation for this class was generated from the following files:
QGIViewDimension.h
QGIViewDimension.cpp