FreeCAD: CommandView.cpp File Reference
CommandView.cpp File Reference
#include "PreCompiled.h"
#include <sstream>
#include <Inventor/events/SoMouseButtonEvent.h>
#include <Inventor/nodes/SoOrthographicCamera.h>
#include <Inventor/nodes/SoPerspectiveCamera.h>
#include <QApplication>
#include <QDialog>
#include <QDomDocument>
#include <QDomElement>
#include <QFile>
#include <QFileInfo>
#include <QFont>
#include <QFontMetrics>
#include <QImageReader>
#include <QMessageBox>
#include <QPainter>
#include <QPointer>
#include <QTextStream>
#include <App/ComplexGeoDataPy.h>
#include <App/Document.h>
#include <App/DocumentObject.h>
#include <App/DocumentObjectGroup.h>
#include <App/GeoFeature.h>
#include <App/GeoFeatureGroupExtension.h>
#include <App/Part.h>
#include <App/Link.h>
#include <Base/Console.h>
#include <Base/Parameter.h>
#include "Command.h"
#include "Action.h"
#include "Application.h"
#include "BitmapFactory.h"
#include "Control.h"
#include "Clipping.h"
#include "DemoMode.h"
#include "DlgSettingsImageImp.h"
#include "Document.h"
#include "FileDialog.h"
#include "ImageView.h"
#include "Inventor/SoAxisCrossKit.h"
#include "Macro.h"
#include "MainWindow.h"
#include "NavigationStyle.h"
#include "OverlayParams.h"
#include "OverlayManager.h"
#include "SceneInspector.h"
#include "Selection.h"
#include "SelectionObject.h"
#include "SoFCOffscreenRenderer.h"
#include "TextureMapping.h"
#include "Tools.h"
#include "Tree.h"
#include "TreeParams.h"
#include "Utilities.h"
#include "View3DInventor.h"
#include "View3DInventorViewer.h"
#include "ViewParams.h"
#include "ViewProviderGeometryObject.h"
#include "WaitCursor.h"
Classes
class StdOrthographicCamera
class StdPerspectiveCamera
class StdCmdViewSaveCamera
class StdCmdViewRestoreCamera
class StdCmdFreezeViews
class StdCmdToggleClipPlane
class StdCmdDrawStyle
class StdCmdToggleVisibility
class StdCmdToggleTransparency
class StdCmdToggleSelectability
class StdCmdShowSelection
class StdCmdHideSelection
class StdCmdSelectVisibleObjects
class StdCmdToggleObjects
class StdCmdShowObjects
class StdCmdHideObjects
class StdCmdViewHome
class StdCmdViewBottom
class StdCmdViewFront
class StdCmdViewLeft
class StdCmdViewRear
class StdCmdViewRight
class StdCmdViewTop
class StdCmdViewIsometric
class StdCmdViewDimetric
class StdCmdViewTrimetric
class StdCmdViewRotateLeft
class StdCmdViewRotateRight
class StdCmdViewFitAll
class StdCmdViewFitSelection
class StdCmdViewGroup
class StdViewDock
class StdViewUndock
class StdMainFullscreen
class StdViewFullscreen
class StdViewDockUndockFullscreen
class StdCmdViewVR
class StdViewScreenShot
class StdViewLoadImage
class StdCmdViewCreate
class StdCmdToggleNavigation
class StdCmdAxisCross
class StdCmdViewExample1
class StdCmdViewExample2
class StdCmdViewExample3
class StdCmdViewIvStereoOff
class StdCmdViewIvStereoRedGreen
class StdCmdViewIvStereoQuadBuff
class StdCmdViewIvStereoInterleavedRows
class StdCmdViewIvStereoInterleavedColumns
class StdCmdViewIvIssueCamPos
class StdViewZoomIn
class StdViewZoomOut
class StdViewBoxZoom
class StdBoxSelection
class StdBoxElementSelection
class StdTreeSelection
class StdCmdTreeCollapse
class StdCmdTreeExpand
class StdCmdTreeSelectAllInstances
class StdCmdSceneInspector
class StdCmdTextureMapping
class StdCmdDemoMode
class StdCmdSelBack
class StdCmdSelForward
class StdTreeSingleDocument
class StdTreeMultiDocument
class StdTreeCollapseDocument
class StdTreeSyncView
class StdTreeSyncSelection
class StdTreeSyncPlacement
class StdTreePreSelection
class StdTreeRecordSelection
class StdTreeDrag
class StdCmdTreeViewActions
class StdCmdSelBoundingBox
class StdCmdDockOverlayAll
class StdCmdDockOverlayTransparentAll
class StdCmdDockOverlayToggle
class StdCmdDockOverlayToggleTransparent
class StdCmdDockOverlayToggleLeft
class StdCmdDockOverlayToggleRight
class StdCmdDockOverlayToggleTop
class StdCmdDockOverlayToggleBottom
class StdCmdDockOverlayMouseTransparent
class StdCmdDockOverlay
class StdStoreWorkingView
class StdRecallWorkingView
class StdCmdAlignToSelection
Namespaces
Gui
Macros
#define TREEVIEW_DOC_CMD_DEF(_name, _v)
#define TREEVIEW_CMD_DEF(_name)
Typedefs
using SelectionMode = enum { CENTER, INTERSECT }
Functions
static std::vector< std::string > getBoxSelection (ViewProviderDocumentObject *vp, SelectionMode mode, bool selectElement, const Base::ViewProjMethod &proj, const Base::Polygon2d &polygon, const Base::Matrix4D &mat, bool transform=true, int depth=0)
static void doSelect (void *ud, SoEventCallback *cb)
void Gui::CreateViewStdCommands ()
Macro Definition Documentation
TREEVIEW_CMD_DEF
#define TREEVIEW_CMD_DEF (_name)
Value:
DEF_STD_CMD_AC(StdTree##_name) \
void StdTree##_name::activated(int){ \
    auto checked = !TreeParams::get##_name();\
    TreeParams::set##_name(checked);\
    if(_pcAction) _pcAction->setChecked(checked,true);\
}\
Action * StdTree##_name::createAction(void) {\
    Action *pcAction = Command::createAction();\
    pcAction->setCheckable(true);\
    pcAction->setIcon(QIcon());\
    _pcAction = pcAction;\
    isActive();\
    return pcAction;\
}\
bool StdTree##_name::isActive() {\
    bool checked = TreeParams::get##_name();\
    if(_pcAction && _pcAction->isChecked()!=checked)\
        _pcAction->setChecked(checked,true);\
    return true;\
}
Definition at line 3374 of file CommandView.cpp.
TREEVIEW_DOC_CMD_DEF
#define TREEVIEW_DOC_CMD_DEF (_name, _v)
Value:
DEF_STD_CMD_AC(StdTree##_name) \
void StdTree##_name::activated(int){ \
    TreeParams::setDocumentMode(_v);\
    if(_pcAction) _pcAction->setChecked(true,true);\
}\
Action * StdTree##_name::createAction(void) {\
    Action *pcAction = Command::createAction();\
    pcAction->setCheckable(true);\
    pcAction->setIcon(QIcon());\
    _pcAction = pcAction;\
    isActive();\
    return pcAction;\
}\
bool StdTree##_name::isActive() {\
    bool checked = TreeParams::getDocumentMode()==_v;\
    if(_pcAction && _pcAction->isChecked()!=checked)\
        _pcAction->setChecked(checked,true);\
    return true;\
}
Definition at line 3302 of file CommandView.cpp.
Typedef Documentation
SelectionMode
using SelectionMode = enum { CENTER, INTERSECT }
Definition at line 2762 of file CommandView.cpp.
Function Documentation
doSelect()
static void doSelect (void * ud, SoEventCallback * cb) static
Definition at line 2887 of file CommandView.cpp.
References Gui::SelectionSingleton::addSelection(), Gui::SelectionSingleton::clearSelection(), toolbit-attributes::doc, App::Application::getActiveDocument(), App::GetApplication(), getBoxSelection(), App::GeoFeatureGroupExtension::getGroupOfObject(), Instance, importers.importIFCmulticore::objects, Gui::Selection(), and OfflineRenderingUtils::viewer().
Referenced by StdBoxSelection::activated(), and StdBoxElementSelection::activated().
getBoxSelection()
static std::vector<std::string> getBoxSelection (ViewProviderDocumentObject * vp, SelectionMode mode, bool selectElement, const Base::ViewProjMethod & proj, const Base::Polygon2d & polygon, const Base::Matrix4D & mat, bool transform = true, int depth = 0) static
Definition at line 2764 of file CommandView.cpp.
References Base::Polygon2d::Add(), Base::Polygon2d::CalcBoundBox(), src.Mod.AddonManager.NetworkManager::count, Gui::ViewProvider::getBoundingBox(), Base::BoundBox2d::GetCenter(), Gui::ViewProviderDocumentObject::getObject(), App::DocumentObject::GS_SELECT, SplineSurface::i, Instance, Init::parent, Base::BoundBox3< Precision >::ProjectBox(), importers.importIFCmulticore::subs, Base::BoundBox3< Precision >::Transformed(), Path.Post.scripts.grbl_post::type, and TestSpreadsheet::v.
Referenced by doSelect().