FreeCAD: Gui::PythonStderr Class Reference
Gui::PythonStderr Class Reference
#include <PythonConsolePy.h>
Public Member Functions
PythonStderr (PythonConsole *pc)
~PythonStderr () override
Py::Object getattr (const char *name) override
Py::Object repr () override
Py::Object write (const Py::Tuple &)
Py::Object flush (const Py::Tuple &)
Py::Object isatty ()
Static Public Member Functions
static void init_type ()
Detailed Description
Python class for redirection of stderr to FreeCAD's Python console window. This allows one to show all Python messages in the same window where the commands are performed.
See also
PythonStdout
PythonConsole
Author
Werner Mayer
Definition at line 68 of file PythonConsolePy.h.
Constructor & Destructor Documentation
PythonStderr()
PythonStderr::PythonStderr (PythonConsole * pc) explicit
Definition at line 106 of file PythonConsolePy.cpp.
~PythonStderr()
PythonStderr::~PythonStderr () override default
Member Function Documentation
flush()
Py::Object PythonStderr::flush (const Py::Tuple &)
Definition at line 147 of file PythonConsolePy.cpp.
Referenced by init_type().
getattr()
Py::Object PythonStderr::getattr (const char * name) override
Definition at line 113 of file PythonConsolePy.cpp.
References SplineSurface::i.
init_type()
void PythonStderr::init_type () static
Definition at line 95 of file PythonConsolePy.cpp.
References flush(), isatty(), and write().
Referenced by Gui::Application::Application().
isatty()
Py::Object PythonStderr::isatty ()
Definition at line 152 of file PythonConsolePy.cpp.
References femtools.tokrules::False.
Referenced by init_type().
repr()
Py::Object PythonStderr::repr () override
Definition at line 122 of file PythonConsolePy.cpp.
References toolbit-attributes::s, and src.Mod.Test.testmakeWireString::String.
write()
Py::Object PythonStderr::write (const Py::Tuple & args)
Definition at line 130 of file PythonConsolePy.cpp.
References toolbit-attributes::args, and ArchBuildingPart::unicode.
Referenced by init_type().
The documentation for this class was generated from the following files:
PythonConsolePy.h
PythonConsolePy.cpp