FreeCAD: Gui::CommandManager Class Reference
Gui::CommandManager Class Reference
#include <Command.h>
Public Member Functions
CommandManager ()
Construction.
~CommandManager ()
Destruction.
void addCommand (Command *pCom)
Insert a new command into the manager.
void removeCommand (Command *pCom)
Remove a command from the manager.
bool addTo (const char *Name, QWidget *pcWidget)
Adds the given command to a given widget.
std::vector< Command * > getModuleCommands (const char *sModName) const
std::vector< Command * > getAllCommands () const
std::vector< Command * > getGroupCommands (const char *sGrpName) const
Command * getCommandByName (const char *sName) const
void runCommandByName (const char *sName) const
const std::map< std::string, Command * > & getCommands () const
method is OBSOLETE use GetModuleCommands() or GetAllCommands()
void testActive ()
get frequently called by the AppWnd to check the commands are active.
void addCommandMode (const char *sContext, const char *sName)
void updateCommands (const char *sContext, int mode)
int getRevision () const
Return a revision number to check for addition or removal of any command.
const Command * checkAcceleratorForConflicts (const char *accel, const Command *ignore=nullptr) const
std::string newMacroName () const
Public Attributes
boost::signals2::signal< void()> signalChanged
Signal on any addition or removal of command.
boost::signals2::signal< void()> signalPyCmdInitialized
Signal to Python command on first workbench activation.
Detailed Description
The CommandManager class This class manage all available commands in FreeCAD. All Commands will registered here, also commands from Application modules. Also activation / deactivation, Icons Tooltips and so on are handles here. Further the Building of Toolbars and (Context) menus (connecting to a QAction) is done here.
See also
Command
Author
Jürgen Riegel
Definition at line 851 of file Gui/Command.h.
Constructor & Destructor Documentation
CommandManager()
CommandManager::CommandManager () default
Construction.
~CommandManager()
CommandManager::~CommandManager ()
Destruction.
Definition at line 1831 of file Gui/Command.cpp.
Member Function Documentation
addCommand()
void CommandManager::addCommand (Command * pCom)
Insert a new command into the manager.
Definition at line 1836 of file Gui/Command.cpp.
References FC_ERR, FC_LOG_INSTANCE, FC_LOGLEVEL_LOG, Gui::Command::getName(), and signalChanged.
Referenced by Gui::GroupCommand::addCommand(), CreateCloudCommands(), Gui::CreateDocCommands(), CreateDrawingCommands(), Gui::CreateFeatCommands(), CreateFemCommands(), CreateImportCommands(), CreateInspectionCommands(), Gui::CreateLinkCommands(), Gui::CreateMacroCommands(), CreateMaterialCommands(), CreateMeasureCommands(), CreateMeshCommands(), CreateMeshPartCommands(), CreateParamPartCommands(), CreatePartCommands(), CreatePartDesignBodyCommands(), CreatePartDesignCommands(), CreatePartDesignPrimitiveCommands(), CreatePartSelectCommands(), CreatePathCommands(), CreatePointsCommands(), CreateReverseEngineeringCommands(), CreateRobotCommands(), CreateRobotCommandsExport(), CreateRobotCommandsInsertRobots(), CreateRobotCommandsTrajectory(), CreateSandboxCommands(), CreateSimplePartCommands(), CreateSketcherCommands(), CreateSketcherCommandsAlterGeo(), CreateSketcherCommandsBSpline(), CreateSketcherCommandsConstraintAccel(), CreateSketcherCommandsConstraints(), CreateSketcherCommandsCreateGeo(), CreateSketcherCommandsOverlay(), CreateSketcherCommandsVirtualSpace(), CreateSpreadsheetCommands(), Gui::CreateStdCommands(), Gui::CreateStructureCommands(), CreateSurfaceCommands(), CreateTechDrawCommands(), CreateTechDrawCommandsAnnotate(), CreateTechDrawCommandsDecorate(), CreateTechDrawCommandsDims(), CreateTechDrawCommandsExtensionDims(), CreateTechDrawCommandsExtensions(), CreateTechDrawCommandsStack(), Gui::CreateTestCommands(), Gui::CreateViewStdCommands(), Gui::CreateWindowStdCommands(), Gui::MacroCommand::load(), StartGui::Manipulator::modifyMenuBar(), Gui::Dialog::DlgCustomActionsImp::onButtonAddActionClicked(), Gui::ApplicationPy::sAddCommand(), and StdViewDockUndockFullscreen::StdViewDockUndockFullscreen().
addCommandMode()
void CommandManager::addCommandMode (const char * sContext, const char * sName)
Definition at line 1968 of file Gui/Command.cpp.
addTo()
bool CommandManager::addTo (const char * Name, QWidget * pcWidget)
Adds the given command to a given widget.
Definition at line 1894 of file Gui/Command.cpp.
References Gui::Command::addTo(), Base::Console(), Base::ConsoleSingleton::Error(), and Base::ConsoleSingleton::Warning().
Referenced by Gui::Dialog::DlgCustomToolbarsImp::addCustomCommand(), src.Mod.PartDesign.WizardShaft.Shaft.Shaft::equilibrium(), Gui::ToolBoxManager::setup(), Gui::ToolBarManager::setup(), and SandboxGui::TaskPanelView::TaskPanelView().
checkAcceleratorForConflicts()
const Command * Gui::CommandManager::checkAcceleratorForConflicts (const char * accel, const Command * ignore = nullptr) const
Returns a pointer to a conflicting command, or nullptr if there is no conflict. In the case of multiple conflicts, only the first is returned.
Parameters
accel The accelerator to check
ignore (optional) A command to ignore matches with
Definition at line 1989 of file Gui/Command.cpp.
References Gui::Application::commandManager(), getAllCommands(), SplineSurface::i, Gui::Application::Instance, and KDL::min().
Referenced by Gui::Command::printConflictingAccelerators().
getAllCommands()
std::vector< Command * > CommandManager::getAllCommands () const
Returns all commands registered in the manager delivers a vector of all commands. If you intereted in commands of of a special app module use GetModuleCommands()
See also
Command
Definition at line 1924 of file Gui/Command.cpp.
Referenced by Gui::MainWindow::changeEvent(), checkAcceleratorForConflicts(), and Gui::Dialog::DlgCustomKeyboardImp::populateCommandList().
getCommandByName()
Command * CommandManager::getCommandByName (const char * sName) const
Returns the command registered in the manager with the name sName If nothing is found it returns a null pointer
See also
Command
Definition at line 1947 of file Gui/Command.cpp.
Referenced by Gui::ViewProviderLink::_setupContextMenu(), Gui::PythonGroupCommand::activated(), Gui::GroupCommand::addCommand(), MatGui::Array2D::Array2D(), Gui::CommandActionPy::CommandActionPy(), Gui::PythonGroupCommand::createAction(), StdViewDockUndockFullscreen::createAction(), NaviCubeImplementation::createContextMenu(), PartDesignGui::TaskDressUpParameters::createDeleteAction(), FemGui::TaskFemConstraint::createDeleteAction(), Gui::Workbench::createLinkMenu(), Gui::MainWindow::createPopupMenu(), Gui::MainWindow::event(), Gui::CommandActionPy::getAction(), Gui::CommandActionPy::getCommand(), Gui::Dialog::CommandModel::goAddMacro(), Gui::Dialog::DlgCustomKeyboardImp::initCommandCompleter(), Gui::PythonGroupCommand::languageChange(), MatGui::MaterialSave::MaterialSave(), StartGui::Manipulator::modifyMenuBar(), Gui::Dialog::DlgCustomActionsImp::onActionListWidgetItemActivated(), Gui::Dialog::DlgCustomActionsImp::onButtonReplaceActionClicked(), Gui::ShortcutManager::OnChange(), Gui::Dialog::DlgCustomKeyboardImp::onCommandTreeWidgetCurrentItemChanged(), Gui::Dialog::DlgCustomKeyboardImp::onEditShortcutTextChanged(), Gui::Dialog::DemoMode::onFullscreenToggled(), Gui::Dialog::DlgCustomToolbars::onModifyMacroAction(), Gui::TaskCSysDragger::open(), Gui::OverlayTabWidget::OverlayTabWidget(), runCommandByName(), SurfaceGui::SectionsPanel::SectionsPanel(), Gui::CommandActionPy::setattro(), PartDesignGui::TaskExtrudeParameters::setupDialog(), MeshGui::Workbench::setupMenuBar(), PartDesignGui::TaskTransformedParameters::setupUI(), Gui::ApplicationPy::sRunCommand(), PartDesignGui::TaskBooleanParameters::TaskBooleanParameters(), PartDesignGui::TaskLoftParameters::TaskLoftParameters(), PartDesignGui::TaskPipeOrientation::TaskPipeOrientation(), PartDesignGui::TaskPipeParameters::TaskPipeParameters(), PartDesignGui::TaskPipeScaling::TaskPipeScaling(), FemGui::TaskPostClip::TaskPostClip(), FemGui::TaskPostCut::TaskPostCut(), Gui::TaskView::TaskWatcherCommands::TaskWatcherCommands(), Gui::TaskView::TaskWatcherPython::TaskWatcherPython(), Gui::Command::testActive(), updateCommands(), Gui::MainWindow::updateEditorActions(), and Gui::TaskTransform::~TaskTransform().
getCommands()
const std::map<std::string, Command*>& Gui::CommandManager::getCommands () const inline
method is OBSOLETE use GetModuleCommands() or GetAllCommands()
Definition at line 897 of file Gui/Command.h.
Referenced by Gui::Dialog::DlgCustomKeyboardImp::populateCommandGroups().
getGroupCommands()
std::vector< Command * > CommandManager::getGroupCommands (const char * sGrpName) const
Returns all commands of a group delivers a vector of all commands in the given group.
Definition at line 1935 of file Gui/Command.cpp.
Referenced by Gui::Dialog::DlgCustomToolbars::changeEvent(), Gui::Dialog::DlgCustomKeyboardImp::changeEvent(), newMacroName(), Gui::Dialog::DlgCustomActionsImp::onButtonRemoveActionClicked(), Gui::Dialog::DlgCustomKeyboardImp::populateCommandList(), and Gui::MacroCommand::save().
getModuleCommands()
std::vector< Command * > CommandManager::getModuleCommands (const char * sModName) const
Returns all commands of a special App Module delivers a vector of all commands in the given application module. When no name is given the standard commands (build in) are returned.
See also
Command
Definition at line 1912 of file Gui/Command.cpp.
getRevision()
int Gui::CommandManager::getRevision () const inline
Return a revision number to check for addition or removal of any command.
Definition at line 905 of file Gui/Command.h.
newMacroName()
std::string CommandManager::newMacroName () const
Returns the first available command name for a new macro (e.g. starting from 1, examines the existing user preferences for Std_Macro_%1 and returns the lowest available numbered string).
Definition at line 1860 of file Gui/Command.cpp.
References Gui::Application::commandManager(), getGroupCommands(), and Gui::Application::Instance.
Referenced by Gui::Dialog::DlgCustomActionsImp::onButtonAddActionClicked().
removeCommand()
void CommandManager::removeCommand (Command * pCom)
Remove a command from the manager.
Definition at line 1849 of file Gui/Command.cpp.
References Gui::Command::getName(), and signalChanged.
Referenced by Gui::Dialog::DlgCustomActionsImp::onButtonRemoveActionClicked().
runCommandByName()
void CommandManager::runCommandByName (const char * sName) const
Runs the command
Definition at line 1953 of file Gui/Command.cpp.
References getCommandByName(), and Gui::Command::invoke().
Referenced by PartDesignGui::WorkflowManager::determineWorkflow(), Gui::MainWindow::event(), StartGui::StartLauncher::Launch(), SpreadsheetGui::SheetTableView::mergeCells(), StartGui::StartView::newArchFile(), StartGui::StartView::newAssemblyFile(), StartGui::StartView::newDraftFile(), StartGui::StartView::newEmptyFile(), StartGui::StartView::newPartDesignFile(), Gui::Dialog::DlgSettingsGeneral::onLinkActivated(), SketcherGui::TaskSketcherConstraints::onListWidgetConstraintsUpdateActiveStatus(), SketcherGui::TaskSketcherConstraints::onListWidgetConstraintsUpdateDrivingStatus(), StartGui::StartView::openExistingFile(), Gui::Dialog::DlgPreferencePackManagementImp::showAddonManager(), and SpreadsheetGui::SheetTableView::splitCell().
testActive()
void CommandManager::testActive ()
get frequently called by the AppWnd to check the commands are active.
Definition at line 1961 of file Gui/Command.cpp.
updateCommands()
void CommandManager::updateCommands (const char * sContext, int mode)
Definition at line 1973 of file Gui/Command.cpp.
References getCommandByName(), signalChanged, and Gui::Command::updateAction().
Member Data Documentation
signalChanged
boost::signals2::signal<void ()> Gui::CommandManager::signalChanged
Signal on any addition or removal of command.
Definition at line 908 of file Gui/Command.h.
Referenced by addCommand(), Gui::Dialog::DlgCustomKeyboardImp::initCommandList(), removeCommand(), and updateCommands().
signalPyCmdInitialized
boost::signals2::signal<void ()> Gui::CommandManager::signalPyCmdInitialized
Signal to Python command on first workbench activation.
Definition at line 911 of file Gui/Command.h.
Referenced by Gui::Workbench::activated().
The documentation for this class was generated from the following files:
Gui/Command.h
Gui/Command.cpp