FreeCAD: Circle Class Reference
Circle Class Reference
#include <Circle.h>
Public Member Functions
Circle (const Point &c, double radius)
Circle (const Point &p0, const Point &p1, const Point &p2)
bool PointIsOn (const Point &p, double accuracy)
bool LineIsOn (const Point &p0, const Point &p1, double accuracy)
Public Attributes
Point m_c
double m_radius
Detailed Description
Definition at line 34 of file Circle.h.
Constructor & Destructor Documentation
Circle() [1/2]
Circle::Circle (const Point & c, double radius) inline
Definition at line 40 of file Circle.h.
Circle() [2/2]
Circle::Circle (const Point & p0, const Point & p1, const Point & p2)
Definition at line 32 of file Circle.cpp.
References RobotExample::A, a, RobotExample::B, SCL.SimpleDataTypes::b, Path.Dressup.Gui.Dragknife::D, RobotExample::l, m_c, m_radius, KDL::sqrt(), MovieTool::x, Point::x, MovieTool::y, and Point::y.
Member Function Documentation
LineIsOn()
bool Circle::LineIsOn (const Point & p0, const Point & p1, double accuracy)
Definition at line 92 of file Circle.cpp.
References PointIsOn().
PointIsOn()
bool Circle::PointIsOn (const Point & p, double accuracy)
Definition at line 85 of file Circle.cpp.
References m_c, m_radius, and buildPsets::p.
Referenced by LineIsOn().
Member Data Documentation
m_c
Point Circle::m_c
Definition at line 37 of file Circle.h.
Referenced by Circle(), and PointIsOn().
m_radius
double Circle::m_radius
Definition at line 38 of file Circle.h.
Referenced by Circle(), and PointIsOn().
The documentation for this class was generated from the following files:
Circle.h
Circle.cpp