FreeCAD: Path.Post.scripts.slic3r_pre Namespace Reference
Path.Post.scripts.slic3r_pre Namespace Reference
Functions
def open (filename)
def insert (filename, docname)
def parse (inputstring)
Function Documentation
insert()
def Path.Post.scripts.slic3r_pre.insert (filename, docname)
Definition at line 41 of file slic3r_pre.py.
References Path.Post.scripts.slic3r_pre.parse().
Referenced by Path.Post.scripts.slic3r_pre.open().
open()
def Path.Post.scripts.slic3r_pre.open (filename)
Definition at line 34 of file slic3r_pre.py.
References Path.Post.scripts.slic3r_pre.insert().
parse()
def Path.Post.scripts.slic3r_pre.parse (inputstring)
Definition at line 53 of file slic3r_pre.py.
Referenced by Path.Post.scripts.slic3r_pre.insert().