FreeCAD: WriterInventorImp Class Reference
WriterInventorImp Class Reference
Public Member Functions
WriterInventorImp (Base::InventorBuilder &builder)
void setupStream (std::ostream &out)
void addInfoNode ()
void addLabel (const MeshCore::MeshKernel &kernel)
void addTransformNode (const Base::Matrix4D &mat, bool append)
void addNormalNode (const MeshCore::MeshKernel &kernel)
void addCoordinateNode (const MeshCore::MeshKernel &kernel)
void addMaterialNode (const Material *material)
void addMaterialBindingNode (const Material *material)
void addIndexedFaceSetNode (const MeshCore::MeshKernel &kernel)
Static Public Member Functions
static bool isStreamInvalid (std::ostream &out)
Detailed Description
Definition at line 34 of file WriterInventor.cpp.
Constructor & Destructor Documentation
WriterInventorImp()
WriterInventorImp::WriterInventorImp (Base::InventorBuilder & builder) inline explicit
Definition at line 44 of file WriterInventor.cpp.
Member Function Documentation
addCoordinateNode()
void WriterInventorImp::addCoordinateNode (const MeshCore::MeshKernel & kernel) inline
Definition at line 107 of file WriterInventor.cpp.
References Base::InventorBuilder::addNode(), and MeshCore::MeshKernel::GetPoints().
addIndexedFaceSetNode()
void WriterInventorImp::addIndexedFaceSetNode (const MeshCore::MeshKernel & kernel) inline
Definition at line 170 of file WriterInventor.cpp.
References Base::InventorBuilder::addNode(), and MeshCore::MeshKernel::GetFacets().
addInfoNode()
void WriterInventorImp::addInfoNode () inline
Definition at line 54 of file WriterInventor.cpp.
References Base::InventorBuilder::addNode(), and Path.Log::info().
addLabel()
void WriterInventorImp::addLabel (const MeshCore::MeshKernel & kernel) inline
Definition at line 60 of file WriterInventor.cpp.
References Base::InventorBuilder::addNode(), MeshCore::MeshKernel::CountFacets(), MeshCore::MeshKernel::CountPoints(), and Path.Post.scripts.refactored_centroid_post::str.
addMaterialBindingNode()
void WriterInventorImp::addMaterialBindingNode (const Material * material) inline
Definition at line 148 of file WriterInventor.cpp.
References Base::InventorBuilder::addNode(), MeshCore::Material::binding, Base::BindingElement::Overall, MeshCore::MeshIO::PER_FACE, MeshCore::MeshIO::PER_VERTEX, Base::BindingElement::PerFace, Base::BindingElement::PerVertex, and Base::MaterialBindingItem::setValue().
addMaterialNode()
void WriterInventorImp::addMaterialNode (const Material * material) inline
Definition at line 119 of file WriterInventor.cpp.
addNormalNode()
void WriterInventorImp::addNormalNode (const MeshCore::MeshKernel & kernel) inline
Definition at line 82 of file WriterInventor.cpp.
References Base::InventorBuilder::addNode(), MeshCore::MeshKernel::CountFacets(), MeshCore::MeshFacetIterator::End(), MeshCore::MeshGeomFacet::GetNormal(), Base::BindingElement::PerFace, and Base::NormalBindingItem::setValue().
addTransformNode()
void WriterInventorImp::addTransformNode (const Base::Matrix4D & mat, bool append) inline
Definition at line 69 of file WriterInventor.cpp.
References Base::InventorBuilder::addNode(), Path.Post.scripts.uccnc_post::append(), and Base::Placement::fromMatrix().
isStreamInvalid()
static bool WriterInventorImp::isStreamInvalid (std::ostream & out) inline static
Definition at line 39 of file WriterInventor.cpp.
Referenced by MeshCore::WriterInventor::Save().
setupStream()
void WriterInventorImp::setupStream (std::ostream & out) inline
Definition at line 48 of file WriterInventor.cpp.
The documentation for this class was generated from the following file:
WriterInventor.cpp