FreeCAD: Part::BRepOffsetAPI_MakeOffsetFix Class Reference
Part::BRepOffsetAPI_MakeOffsetFix Class Reference
The BRepOffsetAPI_MakeOffsetFix class This class works around a limitation of the BRepOffsetAPI_MakeOffset which returns unexpected results when an input wire has set a placement and consists of a single edge only.
#include <BRepOffsetAPI_MakeOffsetFix.h>
Public Member Functions
BRepOffsetAPI_MakeOffsetFix ()
BRepOffsetAPI_MakeOffsetFix (const GeomAbs_JoinType Join, const Standard_Boolean IsOpenResult)
~BRepOffsetAPI_MakeOffsetFix () override
void AddWire (const TopoDS_Wire &Spine)
Initializes the algorithm to construct parallels to the wire Spine.
void Perform (const Standard_Real Offset, const Standard_Real Alt=0.0)
void Build () override
Builds the resulting shape (redefined from MakeShape).
void Init (const TopoDS_Face &Spine, const GeomAbs_JoinType Join=GeomAbs_Arc, const Standard_Boolean IsOpenResult=Standard_False)
void Init (const GeomAbs_JoinType Join=GeomAbs_Arc, const Standard_Boolean IsOpenResult=Standard_False)
Initialize the evaluation of Offsetting.
Standard_Boolean IsDone () const override
const TopoDS_Shape & Shape () override
const TopTools_ListOfShape & Generated (const TopoDS_Shape &S) override
const TopTools_ListOfShape & Modified (const TopoDS_Shape &S) override
Standard_Boolean IsDeleted (const TopoDS_Shape &S) override
Returns true if the shape S has been deleted.
TopoDS_Shape Replace (GeomAbs_CurveType, const TopoDS_Shape &S) const
Detailed Description
The BRepOffsetAPI_MakeOffsetFix class This class works around a limitation of the BRepOffsetAPI_MakeOffset which returns unexpected results when an input wire has set a placement and consists of a single edge only.
Definition at line 63 of file BRepOffsetAPI_MakeOffsetFix.h.
Constructor & Destructor Documentation
BRepOffsetAPI_MakeOffsetFix() [1/2]
BRepOffsetAPI_MakeOffsetFix::BRepOffsetAPI_MakeOffsetFix () default
BRepOffsetAPI_MakeOffsetFix() [2/2]
BRepOffsetAPI_MakeOffsetFix::BRepOffsetAPI_MakeOffsetFix (const GeomAbs_JoinType Join, const Standard_Boolean IsOpenResult)
Definition at line 52 of file BRepOffsetAPI_MakeOffsetFix.cpp.
~BRepOffsetAPI_MakeOffsetFix()
BRepOffsetAPI_MakeOffsetFix::~BRepOffsetAPI_MakeOffsetFix () override default
Member Function Documentation
AddWire()
void BRepOffsetAPI_MakeOffsetFix::AddWire (const TopoDS_Wire & Spine)
Initializes the algorithm to construct parallels to the wire Spine.
Definition at line 59 of file BRepOffsetAPI_MakeOffsetFix.cpp.
Referenced by Part::ExtrusionHelper::createTaperedPrismOffset(), and Part::TopoShape::makeOffset2D().
Build()
void BRepOffsetAPI_MakeOffsetFix::Build () override
Builds the resulting shape (redefined from MakeShape).
Definition at line 105 of file BRepOffsetAPI_MakeOffsetFix.cpp.
Generated()
const TopTools_ListOfShape & BRepOffsetAPI_MakeOffsetFix::Generated (const TopoDS_Shape & S) override
returns a list of the created shapes from the shape .
Definition at line 217 of file BRepOffsetAPI_MakeOffsetFix.cpp.
Init() [1/2]
void BRepOffsetAPI_MakeOffsetFix::Init (const GeomAbs_JoinType Join = GeomAbs_Arc, const Standard_Boolean IsOpenResult = Standard_False)
Initialize the evaluation of Offsetting.
Definition at line 117 of file BRepOffsetAPI_MakeOffsetFix.cpp.
Init() [2/2]
void BRepOffsetAPI_MakeOffsetFix::Init (const TopoDS_Face & Spine, const GeomAbs_JoinType Join = GeomAbs_Arc, const Standard_Boolean IsOpenResult = Standard_False)
Initializes the algorithm to construct parallels to the spine Spine. Join defines the type of parallel generated by the salient vertices of the spine. The default type is GeomAbs_Arc where the vertices generate sections of a circle. If join type is GeomAbs_Intersection, the edges that intersect in a salient vertex generate the edges prolonged until intersection.
Definition at line 111 of file BRepOffsetAPI_MakeOffsetFix.cpp.
Referenced by Part::ExtrusionHelper::createTaperedPrismOffset().
IsDeleted()
Standard_Boolean BRepOffsetAPI_MakeOffsetFix::IsDeleted (const TopoDS_Shape & S) override
Returns true if the shape S has been deleted.
Definition at line 227 of file BRepOffsetAPI_MakeOffsetFix.cpp.
IsDone()
Standard_Boolean BRepOffsetAPI_MakeOffsetFix::IsDone () const override
Definition at line 122 of file BRepOffsetAPI_MakeOffsetFix.cpp.
Referenced by Part::ExtrusionHelper::createTaperedPrismOffset().
Modified()
const TopTools_ListOfShape & BRepOffsetAPI_MakeOffsetFix::Modified (const TopoDS_Shape & S) override
Returns the list of shapes modified from the shape .
Definition at line 222 of file BRepOffsetAPI_MakeOffsetFix.cpp.
Perform()
void BRepOffsetAPI_MakeOffsetFix::Perform (const Standard_Real Offset, const Standard_Real Alt = 0.0)
Computes a parallel to the spine at distance Offset and at an altitude Alt from the plane of the spine in relation to the normal to the spine. Exceptions: StdFail_NotDone if the offset is not built.
Definition at line 97 of file BRepOffsetAPI_MakeOffsetFix.cpp.
Referenced by Part::ExtrusionHelper::createTaperedPrismOffset(), and Part::TopoShape::makeOffset2D().
Replace()
TopoDS_Shape BRepOffsetAPI_MakeOffsetFix::Replace (GeomAbs_CurveType type, const TopoDS_Shape & S) const
Replaces the given curve type with a B-Spline. Input shape must be a wire or a compound of wires
Definition at line 232 of file BRepOffsetAPI_MakeOffsetFix.cpp.
References Path.Post.scripts.opensbp_post::move(), and Path.Post.scripts.grbl_post::type.
Referenced by Part::TopoShape::makeOffset2D().
Shape()
const TopoDS_Shape & BRepOffsetAPI_MakeOffsetFix::Shape () override
Returns a shape built by the shape construction algorithm. Raises exception StdFail_NotDone if the shape was not built.
Definition at line 184 of file BRepOffsetAPI_MakeOffsetFix.cpp.
References result.
Referenced by Part::ExtrusionHelper::createTaperedPrismOffset(), and Part::TopoShape::makeOffset2D().
The documentation for this class was generated from the following files:
BRepOffsetAPI_MakeOffsetFix.h
BRepOffsetAPI_MakeOffsetFix.cpp