FreeCAD: Data::MappedName Class Reference
Data::MappedName Class Reference
#include <MappedName.h>
Public Member Functions
MappedName (const char *name, int size=-1)
MappedName (const std::string &nameString)
MappedName (const IndexedName &element)
MappedName (const App::StringIDRef &sid)
MappedName ()
MappedName (const MappedName &other)=default
MappedName (const MappedName &other, int startPosition, int size=-1)
MappedName (const MappedName &other, const char *postfix)
MappedName (MappedName &&other) noexcept
Move constructor.
~MappedName ()=default
MappedName & operator= (const MappedName &other)=default
Share data with another MappedName.
MappedName & operator= (const std::string &other)
Create a new MappedName from a std::string: the string's data is copied.
MappedName & operator= (const char *other)
Create a new MappedName from a const char *. The character data is copied.
MappedName & operator= (MappedName &&other) noexcept
Move-construct a MappedName.
bool operator== (const MappedName &other) const
bool operator!= (const MappedName &other) const
MappedName operator+ (const MappedName &other) const
MappedName operator+ (const char *other) const
MappedName operator+ (const std::string &other) const
MappedName operator+ (const QByteArray &other) const
MappedName & operator+= (const char *other)
MappedName & operator+= (const std::string &other)
Appends other to this instance's postfix. The character data from the string is copied.
MappedName & operator+= (const QByteArray &other)
MappedName & operator+= (const MappedName &other)
void append (const char *dataToAppend, int size=-1)
void append (const MappedName &other, int startPosition=0, int size=-1)
std::string toString (int startPosition=0, int len=-1) const
const char * appendToBuffer (std::string &buffer, int startPosition=0, int len=-1) const
const char * toConstString (int offset, int &size) const
QByteArray toRawBytes (int offset=0, int size=-1) const
const QByteArray & dataBytes () const
Direct access to the stored QByteArray of data. A copy is never made.
const QByteArray & postfixBytes () const
Direct access to the stored QByteArray of postfix. A copy is never made.
const char * constPostfix () const
Convenience function providing access to the pointer to the beginning of the postfix data.
QByteArray toBytes () const
IndexedName toIndexedName () const
std::string toPrefixedString () const
const char * appendToBufferWithPrefix (std::string &buf) const
int compare (const MappedName &other) const
bool operator< (const MappedName &other) const
char operator[] (int index) const
int size () const
bool empty () const
bool isRaw () const
MappedName copy () const
void compact () const
Ensure that this data is unshared, making a copy if necessary.
operator bool () const
void clear ()
Reset this instance, clearing anything in data and postfix.
int find (const char *searchTarget, int startPosition=0) const
int find (const std::string &searchTarget, int startPosition=0) const
int rfind (const char *searchTarget, int startPosition=-1) const
int rfind (const std::string &searchTarget, int startPosition=-1) const
bool endsWith (const char *searchTarget) const
bool endsWith (const std::string &searchTarget) const
bool startsWith (const QByteArray &searchTarget, int offset=0) const
bool startsWith (const char *searchTarget, int offset=0) const
bool startsWith (const std::string &searchTarget, int offset=0) const
int findTagInElementName (long *tagOut=nullptr, int *lenOut=nullptr, std::string *postfixOut=nullptr, char *typeOut=nullptr, bool negative=false, bool recursive=true) const
std::size_t hash () const
Get a hash for this MappedName.
Static Public Member Functions
static MappedName fromRawData (const char *name, int size=-1)
static MappedName fromRawData (const QByteArray &data)
static MappedName fromRawData (const MappedName &other, int startPosition, int size=-1)
Friends
std::ostream & operator<< (std::ostream &stream, const MappedName &mappedName)
Detailed Description
The MappedName class maintains a two-part name: the first part ("data") is considered immutable once created, while the second part ("postfix") can be modified/appended to by later operations. It uses shared data when possible (see the fromRawData() members). Despite storing data and postfix separately, they can be accessed via calls to size(), operator[], etc. as though they were a single array.
Definition at line 73 of file MappedName.h.
Constructor & Destructor Documentation
MappedName() [1/9]
Data::MappedName::MappedName (const char * name, int size = -1) inline explicit
Create a MappedName from a C string, optionally prefixed by an element map prefix, which will be omitted from the stored MappedName.
Parameters
name The new name. A deep copy is made.
size Optional, the length of the name string. If not provided, the string must be null-terminated.
Definition at line 102 of file MappedName.h.
MappedName() [2/9]
Data::MappedName::MappedName (const std::string & nameString) inline explicit
Create a MappedName from a C++ std::string, optionally prefixed by an element map prefix, which will be omitted from the stored MappedName.
Parameters
name The new name. A deep copy is made.
Definition at line 119 of file MappedName.h.
MappedName() [3/9]
Data::MappedName::MappedName (const IndexedName & element) inline explicit
Create a MappedName from an IndexedName. If non-zero, the numerical part of the IndexedName is appended as text to the MappedName. In that case the memory is not shared between the original IndexedName and the MappedName.
Definition at line 134 of file MappedName.h.
MappedName() [4/9]
Data::MappedName::MappedName (const App::StringIDRef & sid) inline explicit
Definition at line 145 of file MappedName.h.
MappedName() [5/9]
Data::MappedName::MappedName () inline
Definition at line 151 of file MappedName.h.
Referenced by findTagInElementName().
MappedName() [6/9]
Data::MappedName::MappedName (const MappedName & other) default
MappedName() [7/9]
Data::MappedName::MappedName (const MappedName & other, int startPosition, int size = -1) inline
Copy constructor with start position offset and optional size. The data is not reused.
Parameters
other The MappedName to copy
startPosition an integer offset to start the copy from
size the number of bytes to copy.
See also
append() for details about how the copy behaves for various sizes and start positions
Definition at line 163 of file MappedName.h.
MappedName() [8/9]
Data::MappedName::MappedName (const MappedName & other, const char * postfix) inline
Copy constructor with additional postfix
Parameters
other The mapped name to copy. Its data and postfix become the new MappedName's data
postfix The postfix for the new MappedName
Definition at line 173 of file MappedName.h.
References size().
MappedName() [9/9]
Data::MappedName::MappedName (MappedName && other) inline noexcept
Move constructor.
Definition at line 180 of file MappedName.h.
~MappedName()
Data::MappedName::~MappedName () default
Member Function Documentation
append() [1/2]
void Data::MappedName::append (const char * dataToAppend, int size = -1) inline
Add dataToAppend to this MappedName. If the current name is empty, this becomes the new data element. If this MappedName already has data, then the data is appended to the postfix.
Parameters
dataToAppend The data to add. A deep copy is made.
size The number of bytes to copy. If omitted, dataToAppend must be null-terminated.
Definition at line 413 of file MappedName.h.
References size().
Referenced by operator!=().
append() [2/2]
void Data::MappedName::append (const MappedName & other, int startPosition = 0, int size = -1) inline
Treating both this and other as single continuous byte arrays, append other to this. If this is empty, then other's data is shared with this instance's data beginning at startPosition. If this is not empty, then all data is appended to the postfix. If the copy crosses the boundary between other's data and its postfix, then if this instance was empty, the new data stops where other's data stops, and the remainder of the copy is placed in the suffix. Otherwise the copy simply continues as though there was no distinction between other's data and suffix.
Parameters
other The MappedName to obtain the data from. The data is shared when possible, depending on the details of startPosition, size, and this->empty().
startPosition The byte to start the copy at. Must be a positive non-zero integer less than the length of other's combined data + postfix.
size The number of bytes to copy. Must not overrun the end of other's combined data storage when taking startPosition into consideration.
Definition at line 442 of file MappedName.h.
appendToBuffer()
const char* Data::MappedName::appendToBuffer (std::string & buffer, int startPosition = 0, int len = -1) const inline
Given a (possibly non-empty) std::string buffer, append this instance to it, starting at a specified position, and continuing for a specified number of bytes.
Parameters
buffer The string buffer to append to.
startPosition The position in this instance's data/postfix to start at (defaults to zero). Must be less than the total length of the data plus the postfix.
len The number of bytes to append. If omitted, defaults to appending all available data starting at startPosition.
Returns
A pointer to the beginning of the appended data within buffer.
Note
No effort is made to ensure that these are valid ASCII characters, and it is possible the data includes embedded null characters, non-ASCII data, etc.
Definition at line 528 of file MappedName.h.
Referenced by FC_LOG_LEVEL_INIT(), Sketcher::SketchObject::getElementName(), and Data::ComplexGeoData::getIndexedName().
appendToBufferWithPrefix()
const char* Data::MappedName::appendToBufferWithPrefix (std::string & buf) const inline
Append this MappedName to a provided string buffer, including the ComplexGeoData element map prefix if the MappedName cannot be converted to an IndexedName.
Parameters
buf A (possibly non-empty) string to append this MappedName to.
Returns
A pointer to the beginning of the buffer.
Definition at line 672 of file MappedName.h.
clear()
void Data::MappedName::clear () inline
Reset this instance, clearing anything in data and postfix.
Definition at line 777 of file MappedName.h.
Referenced by src.Mod.Test.Document.DocumentObserverCases.Observer::__init__(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::__init__(), and Data::ElementMap::addChildElements().
compact()
void Data::MappedName::compact () const
Ensure that this data is unshared, making a copy if necessary.
Definition at line 42 of file MappedName.cpp.
compare()
int Data::MappedName::compare (const MappedName & other) const inline
Equivalent to C++20 operator<=>. Performs byte-by-byte comparison of this and other, starting at the first byte and continuing through both data and postfix, ignoring which is which. If the combined data and postfix members are of unequal size but start with the same data, the shorter array is considered "less than" the longer.
Definition at line 685 of file MappedName.h.
Referenced by ArchVRM.Renderer::findPosition(), and ArchVRM.Renderer::sort().
constPostfix()
const char* Data::MappedName::constPostfix () const inline
Convenience function providing access to the pointer to the beginning of the postfix data.
Definition at line 621 of file MappedName.h.
copy()
MappedName Data::MappedName::copy () const inline
If this is shared data, a new unshared copy is made and returned. If it is already unshared no new copy is made, a new instance is returned that shares is data with the current instance.
Definition at line 755 of file MappedName.h.
Referenced by Data::ElementMap::getElementHistory().
dataBytes()
const QByteArray& Data::MappedName::dataBytes () const inline
Direct access to the stored QByteArray of data. A copy is never made.
Definition at line 609 of file MappedName.h.
Referenced by App::StringHasher::getID().
empty()
bool Data::MappedName::empty () const inline
Treat this MappedName as a single continuous array of bytes, returning true only if both data and prefix are empty.
Definition at line 739 of file MappedName.h.
Referenced by Data::MappedNameRef::MappedNameRef().
endsWith() [1/2]
bool Data::MappedName::endsWith (const char * searchTarget) const inline
Returns true if this MappedName ends with the search target. If there is a postfix, only the postfix is considered. If not, then only the data is considered. A search string that overlaps the two will not be found.
Definition at line 868 of file MappedName.h.
endsWith() [2/2]
bool Data::MappedName::endsWith (const std::string & searchTarget) const inline
Returns true if this MappedName ends with the search target. If there is a postfix, only the postfix is considered. If not, then only the data is considered. A search string that overlaps the two will not be found.
Definition at line 882 of file MappedName.h.
find() [1/2]
int Data::MappedName::find (const char * searchTarget, int startPosition = 0) const inline
Find a string of characters in this MappedName. The bytes must occur either entirely in the data, or entirely in the postfix: a string that overlaps the two will not be found.
Parameters
searchTarget A null-terminated C string to search for.
startPosition A byte offset to start the search at.
Returns
The position of the target in this instance, or -1 if the target is not found.
Definition at line 790 of file MappedName.h.
Referenced by Data::ElementMap::addChildElements(), FC_LOG_LEVEL_INIT(), Data::ElementMap::find(), findTagInElementName(), and Data::ElementMap::getAll().
find() [2/2]
int Data::MappedName::find (const std::string & searchTarget, int startPosition = 0) const inline
Find a string of characters in this MappedName. The bytes must occur either entirely in the data, or entirely in the postfix: a string that overlaps the two will not be found.
Parameters
searchTarget A string to search for.
startPosition A byte offset to start the search at.
Returns
The position of the target in this instance, or -1 if the target is not found.
Definition at line 821 of file MappedName.h.
findTagInElementName()
int Data::MappedName::findTagInElementName (long * tagOut = nullptr, int * lenOut = nullptr, std::string * postfixOut = nullptr, char * typeOut = nullptr, bool negative = false, bool recursive = true) const
Extract tagOut and other information from a encoded element name
Parameters
tagOut optional pointer to receive the extracted tagOut
lenOut optional pointer to receive the length field after the tagOut field. This gives the length of the previous hashed element name starting from the beginning of the give element name.
postfixOut optional pointer to receive the postfixOut starting at the found tagOut field.
typeOut optional pointer to receive the element typeOut character
negative return negative tagOut as it is. If disabled, then always return positive tagOut. Negative tagOut is sometimes used for element disambiguation.
recursive recursively find the last non-zero tagOut
Returns
Return the end position of the tagOut field, or return -1 if not found.
Definition at line 54 of file MappedName.cpp.
References Data::ELEMENT_MAP_PREFIX, find(), fromRawData(), MappedName(), RobotExample::pos, Data::POSTFIX_DECIMAL_TAG, Data::POSTFIX_TAG, Data::POSTFIX_TAG_SIZE, rfind(), size(), toConstString(), and toString().
Referenced by Data::ComplexGeoData::elementType(), Data::ElementMap::encodeElementName(), FC_LOG_LEVEL_INIT(), Data::ElementMap::find(), Data::ElementMap::getElementHistory(), Data::ElementMap::hashChildMaps(), and Data::ElementMap::traceElement().
fromRawData() [1/3]
static MappedName Data::MappedName::fromRawData (const char * name, int size = -1) inline static
Construct a MappedName from raw character data (including null characters, if size is provided). No copy is made: the data is used in place.
Parameters
name The raw data to use.
size The number of bytes to access. If omitted, name must be null-terminated.
Returns
a new MappedName with name as its data.
Definition at line 194 of file MappedName.h.
Referenced by Sketcher::SketchObject::buildShape(), Data::ComplexGeoData::elementType(), Data::ElementMap::find(), findTagInElementName(), Sketcher::SketchObject::getEdge(), Data::ElementMap::getElementHistory(), Sketcher::SketchObject::getSubObject(), and Data::ElementMap::hashChildMaps().
fromRawData() [2/3]
static MappedName Data::MappedName::fromRawData (const MappedName & other, int startPosition, int size = -1) inline static
Construct a MappedName from another MappedName
Parameters
other The MappedName to copy from. The data is usually not copied, but in some cases a partial copy may be made to support a slice that extends across other's data into its postfix.
startPosition The position to start the reference at.
size The number of bytes to access. If omitted, continues from startPosition to the end of available data (including postfix).
Returns
a new MappedName sharing (possibly a subset of) data with other.
See also
append() for details about how the copy behaves for various sizes and start positions
Definition at line 224 of file MappedName.h.
fromRawData() [3/3]
static MappedName Data::MappedName::fromRawData (const QByteArray & data) inline static
Construct a MappedName from QByteArray data (including any embedded null characters).
Parameters
data The original data. No copy is made, the data is shared with the other instance.
Returns
a new MappedName with data as its data.
Definition at line 209 of file MappedName.h.
hash()
std::size_t Data::MappedName::hash () const inline
Get a hash for this MappedName.
Definition at line 961 of file MappedName.h.
isRaw()
bool Data::MappedName::isRaw () const inline
Returns true if this is shared data, or false if a unique copy has been made. It is safe to access data only if it has been copied prior. To force a copy please
See also
compact()
Definition at line 747 of file MappedName.h.
Referenced by App::StringHasher::getID().
operator bool()
Data::MappedName::operator bool () const inline explicit
Boolean conversion is the inverse of empty(), returning true if there is data in either the data or postfix, and false if there is nothing in either.
Definition at line 771 of file MappedName.h.
operator!=()
bool Data::MappedName::operator!= (const MappedName & other) const inline
Definition at line 329 of file MappedName.h.
References append().
operator+() [1/4]
MappedName Data::MappedName::operator+ (const char * other) const inline
Returns a new MappedName whose data is the LHS argument's data and whose postfix is the LHS argument's postfix with the RHS argument appended to it. The character data is copied.
Definition at line 345 of file MappedName.h.
operator+() [2/4]
MappedName Data::MappedName::operator+ (const MappedName & other) const inline
Returns a new MappedName whose data is the LHS argument's data and whose postfix is the LHS argument's postfix with the RHS argument's data and postfix appended to it.
Definition at line 336 of file MappedName.h.
operator+() [3/4]
MappedName Data::MappedName::operator+ (const QByteArray & other) const inline
Returns a new MappedName whose data is the LHS argument's data and whose postfix is the LHS argument's postfix with the RHS argument appended to it.
Definition at line 363 of file MappedName.h.
References Path.Post.scripts.uccnc_post::append().
operator+() [4/4]
MappedName Data::MappedName::operator+ (const std::string & other) const inline
Returns a new MappedName whose data is the LHS argument's data and whose postfix is the LHS argument's postfix with the RHS argument appended to it. The character data is copied.
Definition at line 354 of file MappedName.h.
operator+=() [1/4]
MappedName& Data::MappedName::operator+= (const char * other) inline
Appends other to this instance's postfix. other must be a null-terminated C string. The character data from the string is copied.
Definition at line 372 of file MappedName.h.
operator+=() [2/4]
MappedName& Data::MappedName::operator+= (const MappedName & other) inline
Appends other to this instance's postfix, unless this is empty, in which case this acts like operator=, and makes this instance's data equal to other's data, and this instance's postfix equal to the other instance's postfix.
Definition at line 402 of file MappedName.h.
References size().
operator+=() [3/4]
MappedName& Data::MappedName::operator+= (const QByteArray & other) inline
Appends other to this instance's postfix. The data may be either copied or shared, depending on whether this->postfix is empty (in which case the data is shared) or non-empty (in which case it is copied).
Definition at line 393 of file MappedName.h.
operator+=() [4/4]
MappedName& Data::MappedName::operator+= (const std::string & other) inline
Appends other to this instance's postfix. The character data from the string is copied.
Definition at line 381 of file MappedName.h.
operator<()
bool Data::MappedName::operator< (const MappedName & other) const inline
See also
compare()
Definition at line 709 of file MappedName.h.
operator=() [1/4]
MappedName& Data::MappedName::operator= (const char * other) inline
Create a new MappedName from a const char *. The character data is copied.
Definition at line 272 of file MappedName.h.
operator=() [2/4]
MappedName& Data::MappedName::operator= (const MappedName & other) default
Share data with another MappedName.
operator=() [3/4]
MappedName& Data::MappedName::operator= (const std::string & other) inline
Create a new MappedName from a std::string: the string's data is copied.
Definition at line 265 of file MappedName.h.
operator=() [4/4]
MappedName& Data::MappedName::operator= (MappedName && other) inline noexcept
Move-construct a MappedName.
Definition at line 280 of file MappedName.h.
operator==()
bool Data::MappedName::operator== (const MappedName & other) const inline
Two MappedNames are equal if the concatenation of their data and postfix is equal. The individual data and postfix may NOT be equal in this case.
Definition at line 299 of file MappedName.h.
operator[]()
char Data::MappedName::operator[] (int index) const inline
Treat this MappedName as a single continuous array of bytes, beginning with data and continuing through postfix. No bounds checking is performed when compiled in release mode.
Definition at line 716 of file MappedName.h.
postfixBytes()
const QByteArray& Data::MappedName::postfixBytes () const inline
Direct access to the stored QByteArray of postfix. A copy is never made.
Definition at line 615 of file MappedName.h.
Referenced by App::StringHasher::getID().
rfind() [1/2]
int Data::MappedName::rfind (const char * searchTarget, int startPosition = -1) const inline
Find a string of characters in this MappedName, starting at the back of postfix and proceeding in reverse through the data. The bytes must occur either entirely in the data, or entirely in the postfix: a string that overlaps the two will not be found.
Parameters
searchTarget A null-terminated C string to search for.
startPosition A byte offset to start the search at. Negative numbers are supported and count back from the end of the concatenated data (as in QByteArray::lastIndexOf()).
Returns
The position of the target in this instance, or -1 if the target is not found.
Definition at line 834 of file MappedName.h.
Referenced by findTagInElementName().
rfind() [2/2]
int Data::MappedName::rfind (const std::string & searchTarget, int startPosition = -1) const inline
Find a string in this MappedName, starting at the back of postfix and proceeding in reverse through the data. The bytes must occur either entirely in the data, or entirely in the postfix: a string that overlaps the two will not be found.
Parameters
searchTarget A null-terminated C string to search for.
startPosition A byte offset to start the search at. Negative numbers are supported and count back from the end of the concatenated data (as in QByteArray::lastIndexOf()).
Returns
The position of the target in this instance, or -1 if the target is not found.
Definition at line 860 of file MappedName.h.
size()
int Data::MappedName::size () const inline
Treat this MappedName as a single continuous array of bytes, returning the combined size of the data and postfix.
Definition at line 732 of file MappedName.h.
Referenced by append(), Path.Post.Utils.GCodeEditorDialog::done(), FC_LOG_LEVEL_INIT(), findTagInElementName(), MappedName(), Data::ElementNameComparator::operator()(), operator+=(), and Data::ElementMap::setElementName().
startsWith() [1/3]
bool Data::MappedName::startsWith (const char * searchTarget, int offset = 0) const inline
Returns true if this MappedName starts with the search target. If there is a postfix, only the postfix is considered. If not, then only the data is considered. A search string that overlaps the two will not be found.
Parameters
searchTarget An array of bytes to match
offset An offset to perform the match at
Returns
True if this MappedName begins with the target bytes
Definition at line 916 of file MappedName.h.
startsWith() [2/3]
bool Data::MappedName::startsWith (const QByteArray & searchTarget, int offset = 0) const inline
Returns true if this MappedName starts with the search target. If there is a postfix, only the postfix is considered. If not, then only the data is considered. A search string that overlaps the two will not be found.
Parameters
searchTarget An array of bytes to match
offset An offset to perform the match at
Returns
True if this MappedName begins with the target bytes
Definition at line 894 of file MappedName.h.
Referenced by FC_LOG_LEVEL_INIT(), Data::ElementMap::getElementHistory(), and Data::ElementMap::traceElement().
startsWith() [3/3]
bool Data::MappedName::startsWith (const std::string & searchTarget, int offset = 0) const inline
Returns true if this MappedName starts with the search target. If there is a postfix, only the postfix is considered. If not, then only the data is considered. A search string that overlaps the two will not be found.
Parameters
searchTarget A string to match
offset An offset to perform the match at
Returns
True if this MappedName begins with the target bytes
Definition at line 933 of file MappedName.h.
References Data::MappedNameRef::compact(), Data::MappedNameRef::MappedNameRef(), Path.Post.scripts.opensbp_post::move(), Data::MappedNameRef::name, Data::MappedNameRef::next, Data::MappedNameRef::sids, and Data::MappedNameRef::~MappedNameRef().
toBytes()
QByteArray Data::MappedName::toBytes () const inline
Provide access to the content of this instance. If either postfix or data is empty, no copy is made and the original QByteArray is returned, sharing data with this instance. If this instance contains both data and postfix, a new QByteArray is created and stores a copy of the data and postfix concatenated together.
Definition at line 632 of file MappedName.h.
References Data::ELEMENT_MAP_PREFIX.
Referenced by Data::ElementMap::addChildElements(), and Data::ElementMap::hashChildMaps().
toConstString()
const char* Data::MappedName::toConstString (int offset, int & size) const inline
Definition at line 556 of file MappedName.h.
Referenced by findTagInElementName().
toIndexedName()
IndexedName Data::MappedName::toIndexedName () const inline
Create an IndexedName from the data portion of this MappedName. If this data has a postfix, the function returns an empty IndexedName. The function will fail if this->data contains anything other than the ASCII letter a-z, A-Z, and the underscore, with an optional integer suffix, returning an empty IndexedName (e.g. an IndexedName that evaluates to boolean false and isNull() == true).
Returns
a new IndexedName that shares its data with this instance's data member.
Definition at line 650 of file MappedName.h.
Referenced by Data::ComplexGeoData::elementType(), Part::Fillet::execute(), Part::Chamfer::execute(), and Data::ElementMap::find().
toPrefixedString()
std::string Data::MappedName::toPrefixedString () const inline
Create and return a string version of this MappedName prefixed by the ComplexGeoData element map prefix, if this MappedName cannot be converted to an indexed name.
Definition at line 660 of file MappedName.h.
toRawBytes()
QByteArray Data::MappedName::toRawBytes (int offset = 0, int size = -1) const inline
Get access to raw byte data. When possible, data is shared between this instance and the returned QByteArray. If the combination of offset and size results in data that crosses the boundary between this->data and this->postfix, the data must be copied in order to provide access as a continuous array of bytes.
Parameters
offset The start position of the raw data access.
size The number of bytes to access. If omitted, the resulting QByteArray includes everything starting from offset to the end, including any postfix data.
Returns
A new QByteArray that shares data with this instance if possible, or is a new copy if required by offset and size.
Definition at line 584 of file MappedName.h.
Referenced by Data::ElementMap::find().
toString()
std::string Data::MappedName::toString (int startPosition = 0, int len = -1) const inline
Create a std::string from this instance, starting at startPosition, and extending len bytes.
Parameters
startPosition The offset into the data
len The number of bytes to output
Returns
A new std::string containing the bytes copied from this instance's data and postfix (depending on startPosition and len).
Note
No effort is made to ensure that these are valid ASCII characters, and it is possible the data includes embedded null characters, non-ASCII data, etc.
Definition at line 511 of file MappedName.h.
Referenced by FC_LOG_LEVEL_INIT(), and findTagInElementName().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & stream, const MappedName & mappedName) friend
Write to a stream as the name with postfix directly appended to it. Note that there is no special handling for null or non-ASCII characters, they are simply written to the stream.
Definition at line 290 of file MappedName.h.
The documentation for this class was generated from the following files:
MappedName.h
MappedName.cpp