FreeCAD: PartGui::ReferenceHighlighter Class Reference
PartGui::ReferenceHighlighter Class Reference
The ReferenceHighlighter class.
#include <ReferenceHighlighter.h>
Public Member Functions
ReferenceHighlighter (const TopoDS_Shape &shape, const App::Color &color)
ReferenceHighlighter.
void setDefaultColor (const App::Color &c)
void setElementColor (const App::Color &c)
void setObjectColor (const App::Color &c)
void getVertexColors (const std::vector< std::string > &elements, std::vector< App::Color > &colors) const
getVertexColors
void getEdgeColors (const std::vector< std::string > &elements, std::vector< App::Color > &colors) const
getEdgeColors
void getFaceColors (const std::vector< std::string > &elements, std::vector< App::Color > &colors) const
getFaceColors
void getFaceMaterials (const std::vector< std::string > &elements, std::vector< App::Material > &materials) const
getFaceMaterials
Detailed Description
The ReferenceHighlighter class.
Author
Werner Mayer
Definition at line 61 of file ReferenceHighlighter.h.
Constructor & Destructor Documentation
ReferenceHighlighter()
ReferenceHighlighter::ReferenceHighlighter (const TopoDS_Shape & shape, const App::Color & color)
ReferenceHighlighter.
Parameters
shape The input shape.
color The standard edge color.
Definition at line 36 of file ReferenceHighlighter.cpp.
Member Function Documentation
getEdgeColors()
void ReferenceHighlighter::getEdgeColors (const std::vector< std::string > & elements, std::vector< App::Color > & colors) const
getEdgeColors
Parameters
elements The sub-element names. If this list is empty colors will be filled with the default color.
colors The size of the colors array is equal to the number of edges of the shape
Definition at line 181 of file ReferenceHighlighter.cpp.
References importers.importIFCmulticore::colors, and SCL.SimpleDataTypes::e.
Referenced by FemGui::ViewProviderFemConstraintOnBoundary::highlightReferences(), and PartDesignGui::ViewProviderDressUp::highlightReferences().
getFaceColors()
void ReferenceHighlighter::getFaceColors (const std::vector< std::string > & elements, std::vector< App::Color > & colors) const
getFaceColors
Parameters
elements The sub-element names. If this list is empty colors will be filled with the default color.
colors The size of the colors array is equal to the number of faces of the shape
Definition at line 224 of file ReferenceHighlighter.cpp.
References importers.importIFCmulticore::colors, and SCL.SimpleDataTypes::e.
Referenced by FemGui::ViewProviderFemConstraintOnBoundary::highlightReferences().
getFaceMaterials()
void ReferenceHighlighter::getFaceMaterials (const std::vector< std::string > & elements, std::vector< App::Material > & materials) const
getFaceMaterials
Parameters
elements The sub-element names. If this list is empty materials will be filled with the default color.
materials The size of the materials array is equal to the number of faces of the shape
Definition at line 241 of file ReferenceHighlighter.cpp.
References SCL.SimpleDataTypes::e, and importers.importIFCmulticore::materials.
Referenced by PartDesignGui::ViewProviderDressUp::highlightReferences(), and PartDesignGui::ViewProviderExtrude::highlightShapeFaces().
getVertexColors()
void ReferenceHighlighter::getVertexColors (const std::vector< std::string > & elements, std::vector< App::Color > & colors) const
getVertexColors
Parameters
elements The sub-element names. If this list is empty colors will be filled with the default color.
colors The size of the colors array is equal to the number of vertexes of the shape
Definition at line 110 of file ReferenceHighlighter.cpp.
References importers.importIFCmulticore::colors, and SCL.SimpleDataTypes::e.
Referenced by FemGui::ViewProviderFemConstraintOnBoundary::highlightReferences().
setDefaultColor()
void PartGui::ReferenceHighlighter::setDefaultColor (const App::Color & c) inline
Definition at line 91 of file ReferenceHighlighter.h.
setElementColor()
void PartGui::ReferenceHighlighter::setElementColor (const App::Color & c) inline
Definition at line 94 of file ReferenceHighlighter.h.
setObjectColor()
void PartGui::ReferenceHighlighter::setObjectColor (const App::Color & c) inline
Definition at line 97 of file ReferenceHighlighter.h.
The documentation for this class was generated from the following files:
ReferenceHighlighter.h
ReferenceHighlighter.cpp