FreeCAD: TechDraw::ewWire Class Reference
TechDraw::ewWire Class Reference
#include <EdgeWalker.h>
Public Member Functions
bool isEqual (ewWire w)
void push_back (WalkerEdge w)
void clear ()
std::size_t size (void)
Public Attributes
std::vector< WalkerEdge > wedges
Detailed Description
Definition at line 104 of file EdgeWalker.h.
Member Function Documentation
clear()
void TechDraw::ewWire::clear () inline
Definition at line 111 of file EdgeWalker.h.
Referenced by src.Mod.Test.Document.DocumentObserverCases.Observer::__init__(), and src.Mod.Test.Document.DocumentObserverCases.GuiObserver::__init__().
isEqual()
bool ewWire::isEqual (ewWire w)
Definition at line 479 of file EdgeWalker.cpp.
References SplineSurface::i, TechDraw::WalkerEdge::weCompare(), and wedges.
push_back()
void ewWire::push_back (WalkerEdge w)
Definition at line 495 of file EdgeWalker.cpp.
References src.Mod.PartDesign.fcgear.svggear::w.
size()
std::size_t ewWire::size (void)
Definition at line 500 of file EdgeWalker.cpp.
Referenced by Path.Post.Utils.GCodeEditorDialog::done().
Member Data Documentation
wedges
std::vector<WalkerEdge> TechDraw::ewWire::wedges
Definition at line 109 of file EdgeWalker.h.
Referenced by isEqual().
The documentation for this class was generated from the following files:
EdgeWalker.h
EdgeWalker.cpp