FreeCAD: Gui::Dialog::DlgPropertyLink Class Reference
Gui::Dialog::DlgPropertyLink Class Reference
#include <DlgPropertyLink.h>
Public Member Functions
DlgPropertyLink (QWidget *parent=nullptr)
~DlgPropertyLink () override
void accept () override
QList< App::SubObjectT > currentLinks () const
QList< App::SubObjectT > originalLinks () const
void init (const App::DocumentObjectT &prop, bool tryFilter=true)
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Static Public Member Functions
static QString linksToPython (const QList< App::SubObjectT > &links)
static QList< App::SubObjectT > getLinksFromProperty (const App::PropertyLinkBase *prop)
static QString formatObject (App::Document *ownerDoc, App::DocumentObject *obj, const char *sub)
static QString formatObject (App::Document *ownerDoc, const App::SubObjectT &sobj)
static QString formatLinks (App::Document *ownerDoc, QList< App::SubObjectT > links)
Protected Member Functions
void showEvent (QShowEvent *) override
void hideEvent (QHideEvent *) override
void closeEvent (QCloseEvent *e) override
void leaveEvent (QEvent *) override
bool eventFilter (QObject *obj, QEvent *ev) override
void keyPressEvent (QKeyEvent *ev) override
void detachObserver ()
void attachObserver ()
void onSelectionChanged (const Gui::SelectionChanges &msg) override
Detailed Description
Definition at line 39 of file DlgPropertyLink.h.
Constructor & Destructor Documentation
DlgPropertyLink()
DlgPropertyLink::DlgPropertyLink (QWidget * parent = nullptr) explicit
Definition at line 74 of file DlgPropertyLink.cpp.
References draftgeoutils.intersections::connect(), Gui::ExpressionParameter::instance(), and Gui::NoResolve.
~DlgPropertyLink()
DlgPropertyLink::~DlgPropertyLink () override
Destroys the object and frees any allocated resources
Definition at line 121 of file DlgPropertyLink.cpp.
References detachObserver().
Member Function Documentation
accept()
void DlgPropertyLink::accept () override
Definition at line 759 of file DlgPropertyLink.cpp.
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
attachObserver()
void DlgPropertyLink::attachObserver () protected
Definition at line 477 of file DlgPropertyLink.cpp.
References Gui::SelectionObserver::attachSelection(), Gui::SelectionObserver::isSelectionAttached(), Gui::NoResolve, buildPsets::p, Init::parent, Gui::Selection(), and Gui::SelectionSingleton::selStackPush().
Referenced by showEvent().
closeEvent()
void DlgPropertyLink::closeEvent (QCloseEvent * e) override protected
Definition at line 471 of file DlgPropertyLink.cpp.
References detachObserver().
currentLinks()
QList< App::SubObjectT > DlgPropertyLink::currentLinks () const
Definition at line 838 of file DlgPropertyLink.cpp.
References src.Mod.Test.testPathArray::items.
detachObserver()
void DlgPropertyLink::detachObserver () protected
Definition at line 526 of file DlgPropertyLink.cpp.
References Gui::SelectionSingleton::addSelection(), Gui::SelectionSingleton::clearSelection(), Gui::SelectionObserver::detachSelection(), SCL.SimpleDataTypes::e, Gui::SelectionObserver::isSelectionAttached(), and Gui::Selection().
Referenced by closeEvent(), hideEvent(), and ~DlgPropertyLink().
eventFilter()
bool DlgPropertyLink::eventFilter (QObject * obj, QEvent * ev) override protected
Definition at line 908 of file DlgPropertyLink.cpp.
References SCL.SimpleDataTypes::e.
formatLinks()
QString DlgPropertyLink::formatLinks (App::Document * ownerDoc, QList< App::SubObjectT > links) static
Definition at line 205 of file DlgPropertyLink.cpp.
References formatObject(), SplineSurface::i, and isLinkSub().
formatObject() [1/2]
QString DlgPropertyLink::formatObject (App::Document * ownerDoc, App::DocumentObject * obj, const char * sub) static
Definition at line 159 of file DlgPropertyLink.cpp.
References App::DocumentObject::getDocument(), App::DocumentObject::getFullName(), App::DocumentObject::getNameInDocument(), App::PropertyString::getStrValue(), App::DocumentObject::getSubObject(), App::PropertyString::getValue(), App::DocumentObject::isAttachedToDocument(), and App::DocumentObject::Label.
Referenced by formatLinks(), and formatObject().
formatObject() [2/2]
static QString Gui::Dialog::DlgPropertyLink::formatObject (App::Document * ownerDoc, const App::SubObjectT & sobj) inline static
Definition at line 60 of file DlgPropertyLink.h.
References formatObject(), App::DocumentObjectT::getObject(), and App::SubObjectT::getSubName().
getLinksFromProperty()
QList< App::SubObjectT > DlgPropertyLink::getLinksFromProperty (const App::PropertyLinkBase * prop) static
Definition at line 129 of file DlgPropertyLink.cpp.
References App::PropertyLinkBase::getLinks(), SplineSurface::i, replaceobj::objs, and importers.importIFCmulticore::subs.
Referenced by init().
hideEvent()
void DlgPropertyLink::hideEvent (QHideEvent * ev) override protected
Definition at line 465 of file DlgPropertyLink.cpp.
References detachObserver().
init()
void DlgPropertyLink::init (const App::DocumentObjectT & prop, bool tryFilter = true)
Definition at line 246 of file DlgPropertyLink.cpp.
References Gui::SelectionChanges::AddSelection, Gui::BitmapFactory(), toolbit-attributes::doc, App::GetApplication(), Base::Persistence::getClassTypeId(), App::Application::getDocuments(), getLinksFromProperty(), Base::Type::getName(), App::DocumentObjectT::getObject(), Base::Type::getParent(), App::DocumentObjectT::getProperty(), App::Hidden, Base::Type::isBad(), Base::Type::isDerivedFrom(), App::PropertyLinkBase::LinkSyncSubObject, onSelectionChanged(), and App::PropertyXLink::supportXLink().
Referenced by DocumentObject.DocumentObject::onChanged().
keyPressEvent()
void DlgPropertyLink::keyPressEvent (QKeyEvent * ev) override protected
Definition at line 923 of file DlgPropertyLink.cpp.
leaveEvent()
void DlgPropertyLink::leaveEvent (QEvent * ev) override protected
Definition at line 520 of file DlgPropertyLink.cpp.
References Gui::SelectionSingleton::rmvPreselect(), and Gui::Selection().
linksToPython()
QString DlgPropertyLink::linksToPython (const QList< App::SubObjectT > & links) static
Definition at line 853 of file DlgPropertyLink.cpp.
References Base::Tools::escapedUnicodeFromUtf8(), and isLinkSub().
onSelectionChanged()
void DlgPropertyLink::onSelectionChanged (const Gui::SelectionChanges & msg) override protected virtual
Implements Gui::SelectionObserver.
Definition at line 703 of file DlgPropertyLink.cpp.
References Gui::SelectionChanges::AddSelection, Path.Op.Surface::msg, App::ElementNamePair::oldName, and App::GeoFeature::resolveElement().
Referenced by init().
originalLinks()
QList< App::SubObjectT > DlgPropertyLink::originalLinks () const
Definition at line 848 of file DlgPropertyLink.cpp.
showEvent()
void DlgPropertyLink::showEvent (QShowEvent * ev) override protected
Definition at line 504 of file DlgPropertyLink.cpp.
References attachObserver().
The documentation for this class was generated from the following files:
DlgPropertyLink.h
DlgPropertyLink.cpp