FreeCAD: TechDraw::DrawUtil Class Reference
TechDraw::DrawUtil Class Reference
Convenient utility functions for TechDraw Module.
#include <DrawUtil.h>
Classes
struct vectorLessType
std::map require comparator to be a type not a function
Static Public Member Functions
static int getIndexFromName (const std::string &geomName)
static std::string getGeomTypeFromName (const std::string &geomName)
static std::string makeGeomName (const std::string &geomType, int index)
static bool isSamePoint (TopoDS_Vertex v1, TopoDS_Vertex v2, double tolerance=(2.0 *Precision::Confusion()))
true if v1 and v2 are the same geometric point within tolerance
static bool isZeroEdge (TopoDS_Edge e, double tolerance=(2.0 *Precision::Confusion()))
static double simpleMinDist (TopoDS_Shape s1, TopoDS_Shape s2)
static double sensibleScale (double working_scale)
static double angleWithX (TopoDS_Edge e, bool reverse)
static double angleWithX (TopoDS_Edge e, TopoDS_Vertex v, double tolerance=(2.0 *Precision::Confusion()))
find angle of edge with x-Axis at First/LastVertex
static double angleWithX (Base::Vector3d inVec)
returns 2d vector's angle with X axis. result is [0, 2pi].
static double incidenceAngleAtVertex (TopoDS_Edge e, TopoDS_Vertex v, double tolerance)
find angle of incidence at First/LastVertex
static bool isFirstVert (TopoDS_Edge e, TopoDS_Vertex v, double tolerance=(2.0 *Precision::Confusion()))
static bool isLastVert (TopoDS_Edge e, TopoDS_Vertex v, double tolerance=(2.0 *Precision::Confusion()))
static bool fpCompare (const double &d1, const double &d2, double tolerance=FLT_EPSILON)
static std::pair< Base::Vector3d, Base::Vector3d > boxIntersect2d (Base::Vector3d point, Base::Vector3d dir, double xRange, double yRange)
static bool apparentIntersection (const Handle(Geom_Curve) curve1, const Handle(Geom_Curve) curve2, Base::Vector3d &result)
static bool apparentIntersection (TopoDS_Edge &edge0, TopoDS_Edge &edge1, gp_Pnt &intersect)
static bool intersect2Lines3d (Base::Vector3d p0, Base::Vector3d d0, Base::Vector3d p1, Base::Vector3d d1, Base::Vector3d &intersect)
static Base::Vector3d vertex2Vector (const TopoDS_Vertex &v)
static std::string formatVector (const Base::Vector3d &v)
static std::string formatVector (const gp_Dir &v)
static std::string formatVector (const gp_Dir2d &v)
static std::string formatVector (const gp_Vec &v)
static std::string formatVector (const gp_Pnt &v)
static std::string formatVector (const gp_Pnt2d &v)
static std::string formatVector (const QPointF &v)
static bool vectorLess (const Base::Vector3d &v1, const Base::Vector3d &v2)
static bool vertexEqual (TopoDS_Vertex &v1, TopoDS_Vertex &v2)
static bool vectorEqual (Base::Vector3d &v1, Base::Vector3d &v2)
static TopoDS_Shape vectorToCompound (std::vector< TopoDS_Edge > vecIn, bool invert=true)
static TopoDS_Shape vectorToCompound (std::vector< TopoDS_Wire > vecIn, bool invert=true)
static TopoDS_Shape shapeVectorToCompound (std::vector< TopoDS_Shape > vecIn, bool invert=true)
static std::vector< TopoDS_Edge > shapeToVector (TopoDS_Shape shapeIn)
static Base::Vector3d toR3 (const gp_Ax2 &fromSystem, const Base::Vector3d &fromPoint)
convert fromPoint in coordinate system fromSystem to reference coordinate system
static bool checkParallel (const Base::Vector3d v1, const Base::Vector3d v2, double tolerance=FLT_EPSILON)
check if two vectors are parallel. Vectors don't have to be unit vectors
static Base::Vector3d vecRotate (Base::Vector3d vec, double angle, Base::Vector3d axis, Base::Vector3d org=Base::Vector3d(0.0, 0.0, 0.0))
rotate vector by angle radians around axis through org
static Base::Vector3d closestBasis (Base::Vector3d v)
returns stdX, stdY or stdZ.
static gp_Vec closestBasis (gp_Vec inVec)
static Base::Vector3d closestBasis (Base::Vector3d vDir, gp_Ax2 coordSys)
static Base::Vector3d closestBasis (gp_Dir gDir, gp_Ax2 coordSys)
static Base::Vector3d closestBasisOriented (Base::Vector3d v)
returns +/- stdX, stdY or stdZ.
static double getWidthInDirection (gp_Dir direction, TopoDS_Shape &shape)
find the size of a shape measured in a given (cardinal) direction
static gp_Vec maskDirection (gp_Vec inVec, gp_Dir directionToMask)
static Base::Vector3d maskDirection (Base::Vector3d inVec, Base::Vector3d directionToMask)
static double coordinateForDirection (Base::Vector3d inPoint, Base::Vector3d cardinal)
get the coordinate of inPoint for the cardinal unit direction.
static double getDefaultLineWeight (std::string s)
static bool isBetween (const Base::Vector3d pt, const Base::Vector3d end1, const Base::Vector3d end2)
is pt between end1 and end2?
static Base::Vector3d Intersect2d (Base::Vector3d p1, Base::Vector3d d1, Base::Vector3d p2, Base::Vector3d d2)
find intersection in 2d for 2 lines in point+direction form
static Base::Vector2d Intersect2d (Base::Vector2d p1, Base::Vector2d d1, Base::Vector2d p2, Base::Vector2d d2)
static Base::Vector3d toVector3d (const gp_Pnt gp)
static Base::Vector3d toVector3d (const gp_Dir gp)
static Base::Vector3d toVector3d (const gp_Vec gp)
static Base::Vector3d toVector3d (const QPointF gp)
static gp_Pnt togp_Pnt (const Base::Vector3d v)
static gp_Dir togp_Dir (const Base::Vector3d v)
static gp_Vec togp_Vec (const Base::Vector3d v)
static QPointF toQPointF (const Base::Vector3d v)
static std::string shapeToString (TopoDS_Shape s)
static TopoDS_Shape shapeFromString (std::string s)
static Base::Vector3d invertY (Base::Vector3d v)
static QPointF invertY (QPointF p)
static std::vector< std::string > split (std::string csvLine)
static std::vector< std::string > tokenize (std::string csvLine, std::string delimiter=", $$$, ")
static App::Color pyTupleToColor (PyObject *pColor)
static PyObject * colorToPyTuple (App::Color color)
static bool isCrazy (TopoDS_Edge e)
static Base::Vector3d getFaceCenter (TopoDS_Face f)
static bool circulation (Base::Vector3d A, Base::Vector3d B, Base::Vector3d C)
static Base::Vector3d getTrianglePoint (Base::Vector3d p1, Base::Vector3d d, Base::Vector3d p2)
static int countSubShapes (TopoDS_Shape shape, TopAbs_ShapeEnum subShape)
static void encodeXmlSpecialChars (std::string &inoutText)
static std::list< TopoDS_Edge > sort_Edges (double tol3d, std::list< TopoDS_Edge > &edges)
static int sgn (double x)
static double sqr (double x)
static void angleNormalize (double &fi)
static double angleComposition (double fi, double delta)
static double angleDifference (double fi1, double fi2, bool reflex=false)
static std::pair< int, int > nearestFraction (double val, int maxDenom=999)
static unsigned int intervalMerge (std::vector< std::pair< double, bool >> &marking, double boundary, bool wraps)
static void intervalMarkLinear (std::vector< std::pair< double, bool >> &marking, double start, double length, bool value)
static void intervalMarkCircular (std::vector< std::pair< double, bool >> &marking, double start, double length, bool value)
static int findRootForValue (double Ax2, double Bxy, double Cy2, double Dx, double Ey, double F, double value, bool findX, double roots[])
static bool mergeBoundedPoint (const Base::Vector2d &point, const Base::BoundBox2d &boundary, std::vector< Base::Vector2d > &storage)
static void findConicRectangleIntersections (double conicAx2, double conicBxy, double conicCy2, double conicDx, double conicEy, double conicF, const Base::BoundBox2d &rectangle, std::vector< Base::Vector2d > &intersections)
static void findLineRectangleIntersections (const Base::Vector2d &linePoint, double lineAngle, const Base::BoundBox2d &rectangle, std::vector< Base::Vector2d > &intersections)
static void findCircleRectangleIntersections (const Base::Vector2d &circleCenter, double circleRadius, const Base::BoundBox2d &rectangle, std::vector< Base::Vector2d > &intersections)
static void findLineSegmentRectangleIntersections (const Base::Vector2d &linePoint, double lineAngle, double segmentBasePosition, double segmentLength, const Base::BoundBox2d &rectangle, std::vector< Base::Vector2d > &intersections)
static void findCircularArcRectangleIntersections (const Base::Vector2d &circleCenter, double circleRadius, double arcBaseAngle, double arcRotation, const Base::BoundBox2d &rectangle, std::vector< Base::Vector2d > &intersections)
static void copyFile (std::string inSpec, std::string outSpec)
static std::string translateArbitrary (std::string context, std::string baseName, std::string uniqueName)
static method that provides a translated std::string for objects that are not derived from DrawView
static bool isCosmeticVertex (App::DocumentObject *owner, std::string element)
static bool isCosmeticEdge (App::DocumentObject *owner, std::string element)
static bool isCenterLine (App::DocumentObject *owner, std::string element)
static Base::Vector3d toAppSpace (const DrawViewPart &dvp, const Base::Vector3d &inPoint)
static Base::Vector3d toAppSpace (const DrawViewPart &dvp, const QPointF &inPoint)
static bool isWithinRange (double actualAngleIn, double targetAngleIn, double allowableError)
static std::string cleanFilespecBackslash (const std::string &filespec)
static void dumpVertexes (const char *text, const TopoDS_Shape &s)
static void dumpEdge (const char *label, int i, TopoDS_Edge e)
static void dump1Vertex (const char *label, const TopoDS_Vertex &v)
static void countFaces (const char *label, const TopoDS_Shape &s)
static void countWires (const char *label, const TopoDS_Shape &s)
static void countEdges (const char *label, const TopoDS_Shape &s)
static const char * printBool (bool b)
static QString qbaToDebug (const QByteArray &line)
static void dumpCS (const char *text, const gp_Ax2 &CS)
static void dumpCS3 (const char *text, const gp_Ax3 &CS)
static void dumpEdges (const char *text, const TopoDS_Shape &s)
Detailed Description
Convenient utility functions for TechDraw Module.
Definition at line 90 of file DrawUtil.h.
Member Function Documentation
angleComposition()
double DrawUtil::angleComposition (double fi, double delta) static
Definition at line 1418 of file DrawUtil.cpp.
References angleNormalize().
angleDifference()
double DrawUtil::angleDifference (double fi1, double fi2, bool reflex = false) static
Definition at line 1426 of file DrawUtil.cpp.
References angleNormalize(), M_2PI, and M_PI.
angleNormalize()
void DrawUtil::angleNormalize (double & fi) static
Definition at line 1408 of file DrawUtil.cpp.
References M_2PI, and M_PI.
Referenced by angleComposition(), angleDifference(), and intervalMarkCircular().
angleWithX() [1/3]
double DrawUtil::angleWithX (Base::Vector3d inVec) static
returns 2d vector's angle with X axis. result is [0, 2pi].
Definition at line 177 of file DrawUtil.cpp.
References KDL::atan2(), M_PI, result, Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
angleWithX() [2/3]
double DrawUtil::angleWithX (TopoDS_Edge e, bool reverse) static
assumes 2d on XY quick angle for straight edges
Definition at line 189 of file DrawUtil.cpp.
References KDL::atan2(), SCL.SimpleDataTypes::e, FirstVertex(), LastVertex(), M_PI, result, and buildPsets::u.
Referenced by TechDrawGui::_getAngle(), TechDrawGui::QGIWeldSymbol::getLastSegAngle(), TechDraw::DrawProjectSplit::removeDuplicateEdges(), and TechDrawGui::TaskCosmeticCircle::setUiPrimary().
angleWithX() [3/3]
double DrawUtil::angleWithX (TopoDS_Edge e, TopoDS_Vertex v, double tolerance = (2.0 * Precision::Confusion())) static
find angle of edge with x-Axis at First/LastVertex
Definition at line 210 of file DrawUtil.cpp.
References KDL::atan2(), SCL.SimpleDataTypes::c, Base::Console(), SCL.SimpleDataTypes::e, Handle(), isFirstVert(), isLastVert(), M_PI, Base::ConsoleSingleton::Message(), Init::param, draftutils.utils::tolerance(), and TestSpreadsheet::v.
apparentIntersection() [1/2]
bool DrawUtil::apparentIntersection (const Handle(Geom_Curve) curve1, const Handle(Geom_Curve) curve2, Base::Vector3d & result) static
Definition at line 382 of file DrawUtil.cpp.
References EWTOLERANCE, result, and toVector3d().
apparentIntersection() [2/2]
bool DrawUtil::apparentIntersection (TopoDS_Edge & edge0, TopoDS_Edge & edge1, gp_Pnt & intersect) static
Definition at line 397 of file DrawUtil.cpp.
References RobotExample::C, Base::Console(), Path.Dressup.Gui.Dragknife::D, SCL.SimpleDataTypes::e, EWTOLERANCE, SCL.SimpleDataTypes::f, FirstVertex(), formatVector(), fpCompare(), toolbit-attributes::g, Part::intersect(), LastVertex(), and Base::ConsoleSingleton::Message().
boxIntersect2d()
std::pair< Base::Vector3d, Base::Vector3d > DrawUtil::boxIntersect2d (Base::Vector3d point, Base::Vector3d dir, double xRange, double yRange) static
Definition at line 323 of file DrawUtil.cpp.
References fpCompare(), Base::Vector3< float_type >::IsEqual(), Base::Vector3< float_type >::Normalize(), result, Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
checkParallel()
bool DrawUtil::checkParallel (const Base::Vector3d v1, const Base::Vector3d v2, double tolerance = FLT_EPSILON) static
check if two vectors are parallel. Vectors don't have to be unit vectors
Definition at line 654 of file DrawUtil.cpp.
References dot(), fpCompare(), Base::Vector3< float_type >::Length(), draftutils.utils::tolerance(), and draftgeoutils.general::v1().
Referenced by TechDraw::DrawProjGroupItem::execute(), TechDraw::ShapeUtils::getViewAxis(), and TechDraw::ShapeUtils::legacyViewAxis1().
circulation()
bool DrawUtil::circulation (Base::Vector3d A, Base::Vector3d B, Base::Vector3d C) static
Definition at line 1229 of file DrawUtil.cpp.
References RobotExample::A, RobotExample::B, and RobotExample::C.
Referenced by TechDraw::CenterLine::calcEndPoints2Lines().
cleanFilespecBackslash()
std::string DrawUtil::cleanFilespecBackslash (const std::string & filespec) static
convert a filespec (string) containing '\' to only use '/'. prevents situation where '\' is interpreted as an escape of the next character in Python commands.
Definition at line 1903 of file DrawUtil.cpp.
Referenced by TechDrawGui::TaskActiveView::createActiveView(), TechDrawGui::TaskHatch::createHatch(), TechDrawGui::TaskGeomHatch::onFileChanged(), TechDrawGui::PagePrinter::printPdf(), TechDrawGui::PagePrinter::saveDXF(), TechDrawGui::PagePrinter::saveSVG(), and TechDrawGui::TaskHatch::updateHatch().
closestBasis() [1/4]
Base::Vector3d DrawUtil::closestBasis (Base::Vector3d v) static
returns stdX, stdY or stdZ.
Definition at line 676 of file DrawUtil.cpp.
References Base::Vector3< float_type >::GetAngle(), KDL::min(), result, and TestSpreadsheet::v.
Referenced by closestBasis(), TechDraw::DrawBrokenView::directionFromObj(), getWidthInDirection(), TechDraw::DrawComplexSection::sectionArrowDirs(), and TechDraw::DrawComplexSection::validateProfilePosition().
closestBasis() [2/4]
Base::Vector3d DrawUtil::closestBasis (Base::Vector3d vDir, gp_Ax2 coordSys) static
Definition at line 789 of file DrawUtil.cpp.
References closestBasis(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
closestBasis() [3/4]
Base::Vector3d DrawUtil::closestBasis (gp_Dir gDir, gp_Ax2 coordSys) static
Definition at line 795 of file DrawUtil.cpp.
References KDL::min().
closestBasis() [4/4]
gp_Vec DrawUtil::closestBasis (gp_Vec inVec) static
Definition at line 670 of file DrawUtil.cpp.
References closestBasis(), togp_Dir(), and toVector3d().
closestBasisOriented()
Base::Vector3d DrawUtil::closestBasisOriented (Base::Vector3d v) static
returns +/- stdX, stdY or stdZ.
Definition at line 733 of file DrawUtil.cpp.
References Base::Vector3< float_type >::GetAngle(), KDL::min(), result, and TestSpreadsheet::v.
Referenced by TechDraw::DrawBrokenView::mapPoint2dFromView(), and TechDraw::DrawBrokenView::mapPoint3dToView().
colorToPyTuple()
PyObject * DrawUtil::colorToPyTuple (App::Color color) static
Definition at line 1145 of file DrawUtil.cpp.
References App::Color::a, App::Color::b, App::Color::g, and App::Color::r.
coordinateForDirection()
double DrawUtil::coordinateForDirection (Base::Vector3d inPoint, Base::Vector3d cardinal) static
get the coordinate of inPoint for the cardinal unit direction.
Definition at line 916 of file DrawUtil.cpp.
References maskDirection(), and Base::Vector3< float_type >::x.
Referenced by TechDraw::DrawBrokenView::mapPoint2dFromView(), and TechDraw::DrawBrokenView::mapPoint3dToView().
copyFile()
void DrawUtil::copyFile (std::string inSpec, std::string outSpec) static
Definition at line 1835 of file DrawUtil.cpp.
References Base::Console(), Base::FileInfo::copyTo(), Base::FileInfo::isReadable(), and Base::ConsoleSingleton::Message().
countEdges()
void DrawUtil::countEdges (const char * label, const TopoDS_Shape & s) static
Definition at line 1942 of file DrawUtil.cpp.
References Base::Console(), Base::ConsoleSingleton::Message(), and toolbit-attributes::s.
countFaces()
void DrawUtil::countFaces (const char * label, const TopoDS_Shape & s) static
Definition at line 1925 of file DrawUtil.cpp.
References Base::Console(), Base::ConsoleSingleton::Message(), and toolbit-attributes::s.
countSubShapes()
int DrawUtil::countSubShapes (TopoDS_Shape shape, TopAbs_ShapeEnum subShape) static
Definition at line 1253 of file DrawUtil.cpp.
References src.Mod.AddonManager.NetworkManager::count.
countWires()
void DrawUtil::countWires (const char * label, const TopoDS_Shape & s) static
Definition at line 1934 of file DrawUtil.cpp.
References Base::Console(), Base::ConsoleSingleton::Message(), and toolbit-attributes::s.
dump1Vertex()
void DrawUtil::dump1Vertex (const char * label, const TopoDS_Vertex & v) static
Definition at line 1960 of file DrawUtil.cpp.
References Base::Console(), Base::ConsoleSingleton::Message(), and TestSpreadsheet::v.
dumpCS()
void DrawUtil::dumpCS (const char * text, const gp_Ax2 & CS) static
Definition at line 2018 of file DrawUtil.cpp.
References Base::Console(), formatVector(), and Base::ConsoleSingleton::Message().
Referenced by TechDraw::DrawViewSection::getCSFromBase().
dumpCS3()
void DrawUtil::dumpCS3 (const char * text, const gp_Ax3 & CS) static
Definition at line 2032 of file DrawUtil.cpp.
References Base::Console(), formatVector(), and Base::ConsoleSingleton::Message().
dumpEdge()
void DrawUtil::dumpEdge (const char * label, int i, TopoDS_Edge e) static
Definition at line 1967 of file DrawUtil.cpp.
References Base::Console(), SCL.SimpleDataTypes::e, SplineSurface::i, FreeCADInit::Length, and Base::ConsoleSingleton::Message().
Referenced by dumpEdges().
dumpEdges()
void DrawUtil::dumpEdges (const char * text, const TopoDS_Shape & s) static
Definition at line 1950 of file DrawUtil.cpp.
References Base::Console(), dumpEdge(), SCL.SimpleDataTypes::e, SplineSurface::i, Base::ConsoleSingleton::Message(), and toolbit-attributes::s.
dumpVertexes()
void DrawUtil::dumpVertexes (const char * text, const TopoDS_Shape & s) static
Definition at line 1914 of file DrawUtil.cpp.
References Base::Console(), SplineSurface::i, Base::ConsoleSingleton::Message(), toolbit-attributes::s, and TestSpreadsheet::v.
encodeXmlSpecialChars()
void DrawUtil::encodeXmlSpecialChars (std::string & inoutText) static
Definition at line 1267 of file DrawUtil.cpp.
Referenced by TechDraw::DrawViewSpreadsheet::getSheetImage().
findCircleRectangleIntersections()
void DrawUtil::findCircleRectangleIntersections (const Base::Vector2d & circleCenter, double circleRadius, const Base::BoundBox2d & rectangle, std::vector< Base::Vector2d > & intersections) static
Definition at line 1745 of file DrawUtil.cpp.
References findConicRectangleIntersections(), sqr(), Base::Vector2d::x, and Base::Vector2d::y.
Referenced by findCircularArcRectangleIntersections().
findCircularArcRectangleIntersections()
void DrawUtil::findCircularArcRectangleIntersections (const Base::Vector2d & circleCenter, double circleRadius, double arcBaseAngle, double arcRotation, const Base::BoundBox2d & rectangle, std::vector< Base::Vector2d > & intersections) static
Definition at line 1793 of file DrawUtil.cpp.
References findCircleRectangleIntersections(), Base::Vector2d::FromPolar(), SplineSurface::i, M_2PI, M_PI, and mergeBoundedPoint().
findConicRectangleIntersections()
void DrawUtil::findConicRectangleIntersections (double conicAx2, double conicBxy, double conicCy2, double conicDx, double conicEy, double conicF, const Base::BoundBox2d & rectangle, std::vector< Base::Vector2d > & intersections) static
Definition at line 1673 of file DrawUtil.cpp.
References findRootForValue(), and mergeBoundedPoint().
Referenced by findCircleRectangleIntersections(), and findLineRectangleIntersections().
findLineRectangleIntersections()
void DrawUtil::findLineRectangleIntersections (const Base::Vector2d & linePoint, double lineAngle, const Base::BoundBox2d & rectangle, std::vector< Base::Vector2d > & intersections) static
Definition at line 1730 of file DrawUtil.cpp.
References findConicRectangleIntersections(), Base::Vector2d::FromPolar(), Base::Vector2d::x, and Base::Vector2d::y.
Referenced by findLineSegmentRectangleIntersections().
findLineSegmentRectangleIntersections()
void DrawUtil::findLineSegmentRectangleIntersections (const Base::Vector2d & linePoint, double lineAngle, double segmentBasePosition, double segmentLength, const Base::BoundBox2d & rectangle, std::vector< Base::Vector2d > & intersections) static
Definition at line 1760 of file DrawUtil.cpp.
References findLineRectangleIntersections(), Base::Vector2d::FromPolar(), SplineSurface::i, and mergeBoundedPoint().
findRootForValue()
int DrawUtil::findRootForValue (double Ax2, double Bxy, double Cy2, double Dx, double Ey, double F, double value, bool findX, double roots[]) static
Definition at line 1606 of file DrawUtil.cpp.
References sqr(), and KDL::sqrt().
Referenced by findConicRectangleIntersections().
formatVector() [1/7]
std::string DrawUtil::formatVector (const Base::Vector3d & v) static
Definition at line 489 of file DrawUtil.cpp.
References Base::UnitsApi::getDecimals(), and TestSpreadsheet::v.
Referenced by apparentIntersection(), TechDraw::CenterLine::CenterLineBuilder(), TechDraw::edgeSortItem::dump(), TechDraw::PATLineSpec::dump(), TechDraw::pointPair::dump(), TechDraw::anglePoints::dump(), TechDraw::arcPoints::dump(), TechDraw::areaPoint::dump(), TechDraw::Vertex::dump(), dumpCS(), dumpCS3(), TechDrawGui::QGEPath::dumpGhostPoints(), TechDraw::DrawProjGroup::dumpISO(), TechDrawGui::QGEPath::dumpMarkerPos(), TechDrawGui::TaskLeaderLine::dumpTrackerPoints(), TechDraw::DrawProjectSplit::dumpVertexMap(), and TechDraw::DrawLeaderLine::dumpWaypoints().
formatVector() [2/7]
std::string DrawUtil::formatVector (const gp_Dir & v) static
Definition at line 497 of file DrawUtil.cpp.
References Base::UnitsApi::getDecimals(), and TestSpreadsheet::v.
formatVector() [3/7]
std::string DrawUtil::formatVector (const gp_Dir2d & v) static
Definition at line 505 of file DrawUtil.cpp.
References Base::UnitsApi::getDecimals(), and TestSpreadsheet::v.
formatVector() [4/7]
std::string DrawUtil::formatVector (const gp_Pnt & v) static
Definition at line 520 of file DrawUtil.cpp.
References Base::UnitsApi::getDecimals(), and TestSpreadsheet::v.
formatVector() [5/7]
std::string DrawUtil::formatVector (const gp_Pnt2d & v) static
Definition at line 528 of file DrawUtil.cpp.
References Base::UnitsApi::getDecimals(), and TestSpreadsheet::v.
formatVector() [6/7]
std::string DrawUtil::formatVector (const gp_Vec & v) static
Definition at line 512 of file DrawUtil.cpp.
References Base::UnitsApi::getDecimals(), and TestSpreadsheet::v.
formatVector() [7/7]
std::string DrawUtil::formatVector (const QPointF & v) static
Definition at line 536 of file DrawUtil.cpp.
References Base::UnitsApi::getDecimals(), and TestSpreadsheet::v.
fpCompare()
bool DrawUtil::fpCompare (const double & d1, const double & d2, double tolerance = FLT_EPSILON) static
Definition at line 316 of file DrawUtil.cpp.
References draftutils.utils::tolerance().
Referenced by TechDraw::DrawViewSection::alignSectionFaces(), apparentIntersection(), boxIntersect2d(), TechDraw::CenterLine::calcEndPoints(), TechDraw::CenterLine::calcEndPoints2Lines(), TechDraw::CenterLine::calcEndPoints2Points(), TechDraw::CenterLine::calcEndPointsNoRef(), TechDraw::DrawComplexSection::canBuild(), TechDraw::DrawViewPart::centerScaleRotate(), checkParallel(), TechDrawGui::TaskCenterLine::checkPathologicalEdges(), TechDrawGui::TaskCenterLine::checkPathologicalVertices(), TechDraw::DrawViewPart::checkXDirection(), TechDraw::edgeSortItem::edgeEqual(), TechDraw::edgeSortItem::edgeLess(), TechDraw::ShapeUtils::edgesAreParallel(), TechDraw::DrawViewMulti::execute(), TechDraw::DrawProjGroup::execute(), TechDraw::DrawViewDimension::getAnglePointsTwoEdges(), TechDraw::DimensionFormatter::getFormattedDimensionValue(), TechDraw::DrawProjGroupItem::getLegacyX(), TechDraw::DrawProjGroupItem::getXDirection(), TechDraw::DrawViewSection::getXDirection(), TechDraw::DrawViewPart::getXDirection(), TechDraw::DrawViewDimension::hasOverUnderTolerance(), TechDraw::DrawViewDimension::haveTolerance(), Intersect2d(), isBetween(), TechDraw::GeometryUtils::isLine(), TechDraw::DimensionFormatter::isTooSmall(), TechDraw::isValidMultiEdge(), TechDraw::isValidMultiEdge3d(), TechDraw::DrawViewDetail::makeDetailShape(), TechDrawGui::QGIHighlight::makeReference(), maskDirection(), TechDraw::DrawProjGroup::onChanged(), TechDraw::DrawViewPart::onChanged(), TechDrawGui::QGILeaderLine::onLineEditFinished(), TechDraw::DrawViewSection::postHlrTasks(), TechDraw::DrawComplexSection::prepareShape(), TechDraw::DrawViewSection::prepareShape(), TechDraw::DrawView::setPosition(), TechDrawGui::QGIView::setPosition(), TechDraw::DrawComplexSection::showSegment(), TechDrawGui::QGTracker::snapToAngle(), TechDrawGui::QGIView::updateView(), TechDraw::DrawView::validateScale(), and vectorLess().
getDefaultLineWeight()
double DrawUtil::getDefaultLineWeight (std::string s) static
Definition at line 969 of file DrawUtil.cpp.
References TechDraw::LineGroup::getDefaultWidth().
getFaceCenter()
Base::Vector3d DrawUtil::getFaceCenter (TopoDS_Face f) static
Definition at line 1214 of file DrawUtil.cpp.
References SCL.SimpleDataTypes::f, and draftgeoutils.general::v1().
Referenced by TechDraw::DrawGeomHatch::getTrimmedLinesSection().
getGeomTypeFromName()
std::string DrawUtil::getGeomTypeFromName (const std::string & geomName) static
Definition at line 104 of file DrawUtil.cpp.
References RobotExample::pos.
Referenced by _checkDirectPlacement(), _checkSelectionHatch(), TechDrawGui::_createThreadCircle(), TechDrawGui::_createThreadLines(), TechDrawGui::_getVertexInfo(), TechDrawGui::_getVertexPoints(), TechDraw::CenterLine::calcEndPoints(), TechDraw::CenterLine::calcEndPoints2Lines(), TechDraw::CenterLine::calcEndPoints2Points(), TechDraw::CenterLine::CenterLineBuilder(), TechDraw::checkGeometryOccurrences(), TechDraw::DrawViewDimension::checkReferences2D(), TechDraw::CosmeticExtension::deleteCosmeticElements(), execCircleCenterLines(), execExtendShortenLine(), TechDrawGui::execHoleCircle(), execLineParallelPerpendicular(), TechDraw::CommandHelpers::faceFromSelection(), faceFromSelection(), TechDraw::ReferenceEntry::geomType(), TechDraw::DrawViewDimension::getPointsEdgeVert(), TechDraw::DrawViewDimExtent::getPointsExtent(), TechDrawGui::QGIViewPart::getQGISubItemByName(), TechDraw::DrawViewDimension::getRefTypeSubElements(), TechDraw::CommandHelpers::getSelectedShapes(), getSelectedShapes(), TechDraw::CommandHelpers::getSelectedSubElements(), TechDraw::isValidHybrid(), TechDraw::isValidSingleEdge(), TechDraw::isValidSingleEdge3d(), TechDraw::isValidSingleFace(), TechDraw::isValidSingleFace3d(), TechDraw::DrawDimHelper::makeExtentDim(), TechDraw::DrawDimHelper::minMax(), TechDraw::refsMatchToken(), TechDrawGui::TaskProjGroup::rotateButtonClicked(), TechDrawGui::TaskCenterLine::TaskCenterLine(), TechDraw::DrawViewDimension::validateReferenceForm(), and TechDraw::validateSubnameList().
getIndexFromName()
int DrawUtil::getIndexFromName (const std::string & geomName) static
Definition at line 76 of file DrawUtil.cpp.
References RobotExample::pos.
Referenced by _checkDirectPlacement(), TechDrawGui::_createThreadCircle(), TechDrawGui::_createThreadLines(), TechDrawGui::_getVertexInfo(), TechDrawGui::_getVertexPoints(), TechDraw::DrawHatch::affectsFace(), TechDraw::CenterLine::calcEndPoints(), TechDraw::CenterLine::calcEndPoints2Lines(), TechDraw::CenterLine::calcEndPoints2Points(), TechDraw::DrawViewDimension::checkReferences2D(), TDHandlerDimension::createRadiusDiameterDimension(), execCircleCenterLines(), TechDrawGui::execHoleCircle(), execLineParallelPerpendicular(), execMidpoints(), execQuadrants(), TechDrawGui::QGIViewPart::faceIsGeomHatched(), TechDraw::DrawHatch::faceIsHatched(), TechDrawGui::QGIViewPart::faceIsHatched(), TechDraw::GeometryUtils::findHolesInFace(), TechDraw::ReferenceEntry::geomEdgeType(), TechDraw::DrawViewDimension::getAnglePointsThreeVerts(), TechDraw::DrawViewDimension::getAnglePointsTwoEdges(), TechDraw::DrawViewDimension::getArcParameters(), TechDraw::CosmeticExtension::getCenterLineBySelection(), TechDraw::CosmeticExtension::getCosmeticEdgeBySelection(), TechDraw::CosmeticExtension::getCosmeticVertexBySelection(), TechDraw::DrawViewPart::getEdge(), TechDraw::DrawViewPart::getFace(), TechDraw::CosmeticExtension::getGeomFormatBySelection(), TechDraw::DrawViewDimension::getPointsEdgeVert(), TechDraw::DrawViewDimension::getPointsOneEdge(), TechDraw::DrawViewDimension::getPointsTwoEdges(), TechDraw::DrawViewDimension::getPointsTwoVerts(), TechDrawGui::QGIViewPart::getQGISubItemByName(), TDHandlerDimension::getSelectionVector(), TechDraw::DrawViewPart::getVertex(), isCosmeticVertex(), TechDraw::isValidMultiEdge(), TechDraw::isValidSingleEdge(), TechDraw::DrawViewDimension::leaderIntersectsArc(), and TechDraw::DrawDimHelper::minMax().
getTrianglePoint()
Base::Vector3d DrawUtil::getTrianglePoint (Base::Vector3d p1, Base::Vector3d d, Base::Vector3d p2) static
Definition at line 1238 of file DrawUtil.cpp.
References a, SCL.SimpleDataTypes::b, src.Mod.PartDesign.Scripts.Gear::c1, MovieTool::x, Base::Vector3< float_type >::x, MovieTool::y, and Base::Vector3< float_type >::y.
Referenced by TechDrawTools.CommandPositionSectionView.CommandPositionSectionView::Activated().
getWidthInDirection()
double DrawUtil::getWidthInDirection (gp_Dir direction, TopoDS_Shape & shape) static
find the size of a shape measured in a given (cardinal) direction
Definition at line 852 of file DrawUtil.cpp.
References closestBasis(), Base::Console(), Base::ConsoleSingleton::Error(), EWTOLERANCE, Base::Vector3< float_type >::IsEqual(), toVector3d(), xMax, xMin, yMax, and yMin.
incidenceAngleAtVertex()
double DrawUtil::incidenceAngleAtVertex (TopoDS_Edge e, TopoDS_Vertex v, double tolerance) static
find angle of incidence at First/LastVertex
Definition at line 235 of file DrawUtil.cpp.
References KDL::atan2(), SCL.SimpleDataTypes::e, isFirstVert(), isLastVert(), M_2PI, draftutils.utils::tolerance(), TestSpreadsheet::v, vertex2Vector(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by TechDraw::EdgeWalker::makeEmbedding().
Intersect2d() [1/2]
Base::Vector2d DrawUtil::Intersect2d (Base::Vector2d p1, Base::Vector2d d1, Base::Vector2d p2, Base::Vector2d d2) static
Definition at line 1010 of file DrawUtil.cpp.
References Base::Console(), fpCompare(), Base::ConsoleSingleton::Message(), MovieTool::x, Base::Vector2d::x, MovieTool::y, and Base::Vector2d::y.
Intersect2d() [2/2]
Base::Vector3d DrawUtil::Intersect2d (Base::Vector3d p1, Base::Vector3d d1, Base::Vector3d p2, Base::Vector3d d2) static
find intersection in 2d for 2 lines in point+direction form
Definition at line 986 of file DrawUtil.cpp.
References Base::Console(), fpCompare(), Base::ConsoleSingleton::Message(), MovieTool::x, Base::Vector3< float_type >::x, MovieTool::y, and Base::Vector3< float_type >::y.
intersect2Lines3d()
bool DrawUtil::intersect2Lines3d (Base::Vector3d p0, Base::Vector3d d0, Base::Vector3d p1, Base::Vector3d d1, Base::Vector3d & intersect) static
Definition at line 452 of file DrawUtil.cpp.
References Base::Console(), Base::Vector3< float_type >::Cross(), Base::Vector3< float_type >::Dot(), toolbit-attributes::g, Part::intersect(), Base::Vector3< float_type >::Length(), Base::ConsoleSingleton::Message(), and Base::Vector3< float_type >::Normalize().
Referenced by TechDraw::DrawViewDimension::getAnglePointsTwoEdges().
intervalMarkCircular()
void DrawUtil::intervalMarkCircular (std::vector< std::pair< double, bool >> & marking, double start, double length, bool value) static
Definition at line 1570 of file DrawUtil.cpp.
References angleNormalize(), intervalMerge(), M_2PI, and M_PI.
intervalMarkLinear()
void DrawUtil::intervalMarkLinear (std::vector< std::pair< double, bool >> & marking, double start, double length, bool value) static
Definition at line 1550 of file DrawUtil.cpp.
References intervalMerge().
intervalMerge()
unsigned int DrawUtil::intervalMerge (std::vector< std::pair< double, bool >> & marking, double boundary, bool wraps) static
Definition at line 1517 of file DrawUtil.cpp.
References SplineSurface::i.
Referenced by intervalMarkCircular(), and intervalMarkLinear().
invertY() [1/2]
Base::Vector3d DrawUtil::invertY (Base::Vector3d v) static
Definition at line 1051 of file DrawUtil.cpp.
References TestSpreadsheet::v.
Referenced by TechDraw::CosmeticExtension::addCosmeticVertex(), TechDrawGui::QGIViewBalloon::balloonLabelDragFinished(), TechDraw::CenterLine::BaseGeomPtrFromVectors(), TechDraw::CenterLine::calcEndPoints2Lines(), TechDraw::CenterLine::calcEndPoints2Points(), TechDrawGui::TaskCosmeticLine::createCosmeticLine(), TechDrawGui::TaskLeaderLine::createLeaderFeature(), TechDrawGui::QGIViewPart::drawBreakLines(), TechDrawGui::QGIViewPart::drawComplexSectionLine(), execDrawCosmArc(), TechDrawGui::DrawGuiUtil::fromSceneCoords(), TechDrawGui::QGILeaderLine::getAttachPoint(), TechDrawGui::QGIWeldSymbol::getLocalAxes(), TechDraw::DrawLeaderLine::getScaledAndRotatedPoints(), TechDrawGui::QGIViewPart::highlightMoved(), TechDraw::DrawLeaderLine::horizLastSegment(), TechDraw::pointPair::invertY(), TechDraw::anglePoints::invertY(), TechDraw::arcPoints::invertY(), TechDraw::areaPoint::invertY(), TechDraw::DrawLeaderLine::lastSegmentDirection(), TechDraw::CosmeticVertex::makeCanonicalPointInverted(), TechDraw::DrawLeaderLine::makeCanonicalPointsInverted(), TechDraw::DrawDimHelper::makeDistDim(), TechDraw::DrawLeaderLine::makeLeader(), TechDraw::DrawViewDetail::mapPoint3dToDetail(), TechDraw::LandmarkDimension::projectPoint(), TechDraw::DrawViewPart::projectPoint(), TechDraw::CosmeticVertex::rotatedAndScaled(), TechDraw::CenterLine::scaledAndRotatedGeometry(), TechDrawGui::TaskLeaderLine::scenePointsToDeltas(), TechDrawGui::TaskCosmeticCircle::setUiPrimary(), TechDrawGui::QGIView::snapPosition(), TechDrawGui::QGIView::snapSectionView(), toAppSpace(), TechDrawGui::DrawGuiUtil::toGuiPoint(), TechDrawGui::DrawGuiUtil::toSceneCoords(), and TechDrawGui::TaskCosmeticLine::updateCosmeticLine().
invertY() [2/2]
QPointF DrawUtil::invertY (QPointF p) static
Definition at line 1056 of file DrawUtil.cpp.
References TestSpreadsheet::v.
isBetween()
bool DrawUtil::isBetween (const Base::Vector3d pt, const Base::Vector3d end1, const Base::Vector3d end2) static
is pt between end1 and end2?
Definition at line 974 of file DrawUtil.cpp.
References fpCompare(), src.Mod.PartDesign.Scripts.Gear::l1, src.Mod.PartDesign.Scripts.Gear::l2, and FreeCADInit::Length.
Referenced by TechDraw::DrawViewDimension::getAnglePointsTwoEdges().
isCenterLine()
bool DrawUtil::isCenterLine (App::DocumentObject * owner, std::string element) static
Definition at line 1890 of file DrawUtil.cpp.
Referenced by TechDraw::CosmeticExtension::deleteCosmeticElements().
isCosmeticEdge()
bool DrawUtil::isCosmeticEdge (App::DocumentObject * owner, std::string element) static
Definition at line 1879 of file DrawUtil.cpp.
Referenced by TechDraw::CosmeticExtension::deleteCosmeticElements().
isCosmeticVertex()
bool DrawUtil::isCosmeticVertex (App::DocumentObject * owner, std::string element) static
Definition at line 1867 of file DrawUtil.cpp.
References getIndexFromName().
Referenced by TechDraw::CosmeticExtension::deleteCosmeticElements().
isCrazy()
bool DrawUtil::isCrazy (TopoDS_Edge e) static
Definition at line 1165 of file DrawUtil.cpp.
References SCL.SimpleDataTypes::e, ParameterGrp::GetBool(), TechDraw::Preferences::getPreferenceGroup(), and FreeCADInit::Length.
Referenced by TechDraw::GeometryObject::addGeomFromCompound(), and TechDraw::BaseGeom::validateEdge().
isFirstVert()
bool DrawUtil::isFirstVert (TopoDS_Edge e, TopoDS_Vertex v, double tolerance = (2.0 * Precision::Confusion())) static
Definition at line 304 of file DrawUtil.cpp.
References SCL.SimpleDataTypes::e, FirstVertex(), isSamePoint(), draftutils.utils::tolerance(), and TestSpreadsheet::v.
Referenced by angleWithX(), and incidenceAngleAtVertex().
isLastVert()
bool DrawUtil::isLastVert (TopoDS_Edge e, TopoDS_Vertex v, double tolerance = (2.0 * Precision::Confusion())) static
Definition at line 310 of file DrawUtil.cpp.
References SCL.SimpleDataTypes::e, isSamePoint(), LastVertex(), draftutils.utils::tolerance(), and TestSpreadsheet::v.
Referenced by angleWithX(), and incidenceAngleAtVertex().
isSamePoint()
bool DrawUtil::isSamePoint (TopoDS_Vertex v1, TopoDS_Vertex v2, double tolerance = (2.0 * Precision::Confusion())) static
true if v1 and v2 are the same geometric point within tolerance
Definition at line 137 of file DrawUtil.cpp.
References draftutils.utils::tolerance(), and draftgeoutils.general::v1().
Referenced by isFirstVert(), isLastVert(), TechDraw::DrawProjectSplit::isOnEdge(), and isZeroEdge().
isWithinRange()
bool DrawUtil::isWithinRange (double actualAngleIn, double targetAngleIn, double allowableError) static
true if actualAngle(degrees) is within allowableError [0,360] of targetAngle (degrees)
Definition at line 276 of file DrawUtil.cpp.
isZeroEdge()
bool DrawUtil::isZeroEdge (TopoDS_Edge e, double tolerance = (2.0 * Precision::Confusion())) static
Definition at line 144 of file DrawUtil.cpp.
References SCL.SimpleDataTypes::e, FirstVertex(), isSamePoint(), LastVertex(), FreeCADInit::Length, and draftutils.utils::tolerance().
Referenced by TechDraw::GeometryObject::addGeomFromCompound(), TechDraw::DrawViewPart::findFacesOld(), TechDraw::DrawProjectSplit::getEdgesForWalker(), and TechDraw::DrawProjectSplit::scrubEdges().
makeGeomName()
std::string DrawUtil::makeGeomName (const std::string & geomType, int index) static
Definition at line 129 of file DrawUtil.cpp.
References draftgeoutils.general::geomType().
maskDirection() [1/2]
Base::Vector3d DrawUtil::maskDirection (Base::Vector3d inVec, Base::Vector3d directionToMask) static
Definition at line 910 of file DrawUtil.cpp.
References maskDirection(), togp_Vec(), and toVector3d().
maskDirection() [2/2]
gp_Vec DrawUtil::maskDirection (gp_Vec inVec, gp_Dir directionToMask) static
mask off one component of the input vector. input vector (a, b, c) with direction to mask (0, 1, 0) would return (a, 0.0, c). The mask is a cardinal direction or the reverse of a cardinal direction.
Definition at line 892 of file DrawUtil.cpp.
References Base::Console(), EWTOLERANCE, fpCompare(), and Base::ConsoleSingleton::Message().
Referenced by coordinateForDirection(), TechDraw::DrawComplexSection::makeAlignedPieces(), and maskDirection().
mergeBoundedPoint()
bool DrawUtil::mergeBoundedPoint (const Base::Vector2d & point, const Base::BoundBox2d & boundary, std::vector< Base::Vector2d > & storage) static
Definition at line 1656 of file DrawUtil.cpp.
References Base::BoundBox2d::Contains(), SplineSurface::i, and storage.
Referenced by findCircularArcRectangleIntersections(), findConicRectangleIntersections(), and findLineSegmentRectangleIntersections().
nearestFraction()
std::pair< int, int > DrawUtil::nearestFraction (double val, int maxDenom = 999) static
Definition at line 1440 of file DrawUtil.cpp.
References test::m, KDL::max(), result, InitGui::t, toolbit-attributes::val, and MovieTool::x.
Referenced by TechDraw::DrawTemplate::getAutofillValue().
printBool()
const char * DrawUtil::printBool (bool b) static
Definition at line 1997 of file DrawUtil.cpp.
References SCL.SimpleDataTypes::b.
pyTupleToColor()
App::Color DrawUtil::pyTupleToColor (PyObject * pColor) static
Definition at line 1121 of file DrawUtil.cpp.
References blue, green, and red.
qbaToDebug()
QString DrawUtil::qbaToDebug (const QByteArray & line) static
Definition at line 2002 of file DrawUtil.cpp.
References SCL.SimpleDataTypes::c, SplineSurface::i, and toolbit-attributes::s.
sensibleScale()
double DrawUtil::sensibleScale (double working_scale) static
Definition at line 924 of file DrawUtil.cpp.
References SplineSurface::i, and Base::pow().
Referenced by TechDraw::DrawProjGroup::autoScale(), and TechDraw::DrawView::autoScale().
sgn()
int DrawUtil::sgn (double x) static
Definition at line 1398 of file DrawUtil.cpp.
References MovieTool::x.
shapeFromString()
TopoDS_Shape DrawUtil::shapeFromString (std::string s) static
Definition at line 1042 of file DrawUtil.cpp.
References result, and toolbit-attributes::s.
shapeToString()
std::string DrawUtil::shapeToString (TopoDS_Shape s) static
Definition at line 1035 of file DrawUtil.cpp.
References toolbit-attributes::s.
shapeToVector()
std::vector< TopoDS_Edge > DrawUtil::shapeToVector (TopoDS_Shape shapeIn) static
Definition at line 630 of file DrawUtil.cpp.
Referenced by TechDraw::GeometryObject::addGeomFromCompound().
shapeVectorToCompound()
TopoDS_Shape DrawUtil::shapeVectorToCompound (std::vector< TopoDS_Shape > vecIn, bool invert = true) static
Definition at line 613 of file DrawUtil.cpp.
References draftgeoutils.edges::invert(), TechDraw::ShapeUtils::mirrorShape(), and TestSpreadsheet::v.
Referenced by TechDraw::ShapeExtractor::getShapesFused().
simpleMinDist()
double DrawUtil::simpleMinDist (TopoDS_Shape s1, TopoDS_Shape s2) static
Definition at line 161 of file DrawUtil.cpp.
References Base::Console(), src.Mod.AddonManager.NetworkManager::count, and Base::ConsoleSingleton::Message().
Referenced by TechDraw::GeometryUtils::findHolesInFace(), TechDraw::DrawProjectSplit::isOnEdge(), and TechDraw::BaseGeom::minDist().
sort_Edges()
std::list< TopoDS_Edge > DrawUtil::sort_Edges (double tol3d, std::list< TopoDS_Edge > & edges) static
Definition at line 1303 of file DrawUtil.cpp.
References TechDraw::EdgePoints::edge, Handle(), TechDraw::EdgePoints::it, TechDraw::EdgePoints::v1, and TechDraw::EdgePoints::v2.
Referenced by TechDraw::DrawComplexSection::makeNoseToTailWire().
split()
std::vector< std::string > DrawUtil::split (std::string csvLine) static
Definition at line 1091 of file DrawUtil.cpp.
References importOCA::getline(), and result.
sqr()
double DrawUtil::sqr (double x) static
Definition at line 1403 of file DrawUtil.cpp.
References MovieTool::x.
Referenced by findCircleRectangleIntersections(), and findRootForValue().
toAppSpace() [1/2]
Base::Vector3d DrawUtil::toAppSpace (const DrawViewPart & dvp, const Base::Vector3d & qtPoint) static
convert a gui point into its app space equivalent. this requires us to perform the invert, scale, rotate operations in the reverse order from that used to generate the qt point. Note: the centering operation is not considered here
Definition at line 1065 of file DrawUtil.cpp.
References TechDraw::DrawView::getScale(), App::PropertyQuantity::getValue(), invertY(), M_PI, Base::Vector3< float_type >::RotateZ(), and TechDraw::DrawView::Rotation.
Referenced by toAppSpace().
toAppSpace() [2/2]
Base::Vector3d DrawUtil::toAppSpace (const DrawViewPart & dvp, const QPointF & inPoint) static
Definition at line 1085 of file DrawUtil.cpp.
References toAppSpace(), and toVector3d().
togp_Dir()
static gp_Dir TechDraw::DrawUtil::togp_Dir (const Base::Vector3d v) inline static
Definition at line 193 of file DrawUtil.h.
References TestSpreadsheet::v.
Referenced by closestBasis(), TechDraw::DrawComplexSection::sectionArrowDirs(), and TechDraw::DrawViewSection::setCSFromLocalUnit().
togp_Pnt()
static gp_Pnt TechDraw::DrawUtil::togp_Pnt (const Base::Vector3d v) inline static
Definition at line 189 of file DrawUtil.h.
References TestSpreadsheet::v.
Referenced by TechDraw::GeometryUtils::asCircle(), TechDraw::Vertex::asTopoShape(), TechDraw::GeometryUtils::findHolesInFace(), TechDraw::DrawViewDimension::getAnglePointsTwoEdges(), TechDraw::DrawViewDimension::getArcAngle(), TechDraw::DrawViewSection::getChangePointsFromSectionLine(), TechDraw::DrawViewPart::getRotatedCS(), TechDraw::CosmeticEdge::makeCanonicalLine(), TechDraw::CosmeticEdge::makeLineFromCanonicalPoints(), TechDraw::DrawBrokenView::mapPoint2dFromView(), TechDraw::CenterLine::scaledAndRotatedGeometry(), and TechDraw::DrawViewSection::setCSFromLocalUnit().
togp_Vec()
static gp_Vec TechDraw::DrawUtil::togp_Vec (const Base::Vector3d v) inline static
Definition at line 197 of file DrawUtil.h.
References TestSpreadsheet::v.
Referenced by TechDraw::DrawViewDimension::arcPointsFromEdge(), TechDraw::DrawViewDimension::getArcAngle(), TechDraw::DrawGeomHatch::getTrimmedLines(), TechDraw::pointPair::mapToPage(), TechDraw::anglePoints::mapToPage(), TechDraw::arcPoints::mapToPage(), and maskDirection().
tokenize()
std::vector< std::string > DrawUtil::tokenize (std::string csvLine, std::string delimiter = ", $$$, ") static
Definition at line 1105 of file DrawUtil.cpp.
References RobotExample::pos, toolbit-attributes::s, and femtools.tokrules::tokens.
Referenced by TechDraw::LineGenerator::getLineDescriptions().
toQPointF()
static QPointF TechDraw::DrawUtil::toQPointF (const Base::Vector3d v) inline static
Definition at line 201 of file DrawUtil.h.
References TestSpreadsheet::v.
Referenced by TechDrawGui::QGITile::calcTilePosition(), TechDrawGui::QGILeaderLine::draw(), TechDrawGui::QGIViewBalloon::drawBalloon(), TechDrawGui::QGIWeldSymbol::drawFieldFlag(), TechDrawGui::QGIViewPart::drawSectionLine(), TechDrawGui::QGIWeldSymbol::drawTailText(), TechDrawGui::QGIWeldSymbol::getKinkPoint(), TechDrawGui::QGIWeldSymbol::getTailPoint(), TechDrawGui::QGIWeldSymbol::getTileOrigin(), TechDrawGui::QGILeaderLine::getWayPointsFromFeature(), TechDrawGui::TaskCosVertex::onTrackerFinished(), TechDrawGui::QGIView::snapPosition(), TechDrawGui::QGIView::snapSectionView(), and TechDrawGui::QGILeaderLine::startPathEdit().
toR3()
Base::Vector3d DrawUtil::toR3 (const gp_Ax2 & fromSystem, const Base::Vector3d & fromPoint) static
convert fromPoint in coordinate system fromSystem to reference coordinate system
Definition at line 641 of file DrawUtil.cpp.
References Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by TechDraw::DrawViewDetail::makeDetailShape().
toVector3d() [1/4]
static Base::Vector3d TechDraw::DrawUtil::toVector3d (const gp_Dir gp) inline static
Definition at line 176 of file DrawUtil.h.
toVector3d() [2/4]
static Base::Vector3d TechDraw::DrawUtil::toVector3d (const gp_Pnt gp) inline static
Definition at line 172 of file DrawUtil.h.
Referenced by TechDrawGui::TaskCosVertex::addCosVertex(), TechDraw::AOC::AOC(), apparentIntersection(), TechDraw::DrawViewDimension::arcPointsFromEdge(), TechDrawGui::QGIViewBalloon::arrowPosInDrag(), TechDraw::Vertex::asTopoShape(), TechDrawGui::QGIViewBalloon::balloonLabelDragged(), closestBasis(), TechDrawGui::QGSPage::createBalloon(), TechDraw::DrawViewDimension::getAnglePointsThreeVerts(), TechDraw::DrawViewDimension::getAnglePointsTwoEdges(), TechDraw::Face::getCenter(), TechDraw::GeometryUtils::getCircleParms(), TechDraw::DrawBrokenView::getCompressedCentroid(), TechDraw::DrawViewPart::getCurrentCentroid(), TechDraw::ShapeUtils::getEdgeEnds(), TechDraw::DrawViewDimension::getFaceCenter(), TechDraw::DrawViewDimension::getPointsOneEdge(), TechDraw::DrawViewDimension::getPointsTwoVerts(), getWidthInDirection(), TechDrawGui::QGIViewPart::highlightMoved(), TechDraw::BaseGeom::intersection(), TechDraw::GeometryUtils::isLine(), TechDraw::isValidMultiEdge3d(), TechDraw::isValidSingleEdge3d(), TechDraw::isValidVertexes3d(), TechDraw::DrawViewPart::localVectorToDirection(), TechDraw::DrawComplexSection::makeAlignedPieces(), TechDraw::DrawViewPart::makeGeometryForShape(), TechDraw::DrawBrokenView::mapPoint2dFromView(), TechDraw::DrawBrokenView::mapPoint3dToView(), TechDraw::pointPair::mapToPage(), TechDraw::anglePoints::mapToPage(), TechDraw::arcPoints::mapToPage(), maskDirection(), TechDrawGui::QGILeaderLine::onLineEditFinished(), TechDrawGui::TaskCosVertex::onTrackerFinished(), TechDrawGui::TaskLeaderLine::scenePointsToDeltas(), TechDraw::DrawComplexSection::sectionArrowDirs(), TechDraw::DrawViewSection::setCSFromLocalUnit(), TechDrawGui::QGIView::snapSectionView(), and toAppSpace().
toVector3d() [3/4]
static Base::Vector3d TechDraw::DrawUtil::toVector3d (const gp_Vec gp) inline static
Definition at line 180 of file DrawUtil.h.
toVector3d() [4/4]
static Base::Vector3d TechDraw::DrawUtil::toVector3d (const QPointF gp) inline static
Definition at line 184 of file DrawUtil.h.
translateArbitrary()
std::string DrawUtil::translateArbitrary (std::string context, std::string baseName, std::string uniqueName) static
static method that provides a translated std::string for objects that are not derived from DrawView
Definition at line 1856 of file DrawUtil.cpp.
Referenced by TechDraw::DrawWeldSymbol::onSettingDocument(), TechDraw::DrawHatch::translateLabel(), TechDraw::DrawGeomHatch::translateLabel(), TechDraw::DrawSVGTemplate::translateLabel(), TechDraw::DrawView::translateLabel(), and TechDraw::DrawPage::translateLabel().
vecRotate()
Base::Vector3d DrawUtil::vecRotate (Base::Vector3d vec, double angle, Base::Vector3d axis, Base::Vector3d org = Base::Vector3d(0.0, 0.0, 0.0)) static
rotate vector by angle radians around axis through org
Definition at line 662 of file DrawUtil.cpp.
References Base::Matrix4D::rotLine(), and SurfaceTests.TestBlendCurve::vec.
Referenced by TechDraw::DrawProjGroup::spin(), and TechDraw::DrawViewPart::spin().
vectorEqual()
bool DrawUtil::vectorEqual (Base::Vector3d & v1, Base::Vector3d & v2) static
test for equality of two vectors using the vectorLess comparator as used in sorts and containers
Definition at line 573 of file DrawUtil.cpp.
References draftgeoutils.general::v1(), and vectorLess().
Referenced by vertexEqual().
vectorLess()
bool DrawUtil::vectorLess (const Base::Vector3d & v1, const Base::Vector3d & v2) static
compare 2 vectors for sorting - true if v1 < v2 precision::Confusion() is too strict for vertex - vertex comparisons
Definition at line 546 of file DrawUtil.cpp.
References EWTOLERANCE, fpCompare(), FreeCADInit::Length, draftgeoutils.general::v1(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by TechDraw::edgeSortItem::edgeLess(), TechDraw::DrawUtil::vectorLessType::operator()(), TechDraw::DrawProjectSplit::removeDuplicateEdges(), and vectorEqual().
vectorToCompound() [1/2]
TopoDS_Shape DrawUtil::vectorToCompound (std::vector< TopoDS_Edge > vecIn, bool invert = true) static
Definition at line 582 of file DrawUtil.cpp.
References draftgeoutils.edges::invert(), TechDraw::ShapeUtils::mirrorShape(), and TestSpreadsheet::v.
Referenced by TechDraw::GeometryObject::addGeomFromCompound(), and TechDraw::CenterLine::calcEndPoints().
vectorToCompound() [2/2]
TopoDS_Shape DrawUtil::vectorToCompound (std::vector< TopoDS_Wire > vecIn, bool invert = true) static
Definition at line 597 of file DrawUtil.cpp.
References draftgeoutils.edges::invert(), TechDraw::ShapeUtils::mirrorShape(), and TestSpreadsheet::v.
vertex2Vector()
Base::Vector3d DrawUtil::vertex2Vector (const TopoDS_Vertex & v) static
Definition at line 482 of file DrawUtil.cpp.
References TestSpreadsheet::v.
Referenced by TechDraw::EdgeWalker::findUniqueVert(), TechDraw::ShapeExtractor::getLocation3dFromFeat(), incidenceAngleAtVertex(), TechDraw::EdgeWalker::makeUniqueVList(), and TechDraw::DrawProjectSplit::removeDuplicateEdges().
vertexEqual()
bool DrawUtil::vertexEqual (TopoDS_Vertex & v1, TopoDS_Vertex & v2) static
test for equality of two vertexes using the vectorLess comparator as used in sorts and containers
Definition at line 562 of file DrawUtil.cpp.
References draftgeoutils.general::v1(), and vectorEqual().
Referenced by TechDraw::EdgeWalker::makeEmbedding(), and TechDraw::DrawProjectSplit::sameEndPoints().
The documentation for this class was generated from the following files:
DrawUtil.h
DrawUtil.cpp