FreeCAD: Gui::View3DInventorSelection Class Reference
Gui::View3DInventorSelection Class Reference
#include <View3DInventorSelection.h>
Public Member Functions
View3DInventorSelection (SoFCUnifiedSelection *root)
~View3DInventorSelection ()
void setDocument (Gui::Document *pcDocument)
Gui::Document * getDocument () const
void checkGroupOnTop (const SelectionChanges &Reason)
void clearGroupOnTop ()
Detailed Description
Definition at line 39 of file View3DInventorSelection.h.
Constructor & Destructor Documentation
View3DInventorSelection()
View3DInventorSelection::View3DInventorSelection (SoFCUnifiedSelection * root)
Definition at line 45 of file View3DInventorSelection.cpp.
References Gui::SoFCSelectionRoot::selectionStyle, and SCL.Builtin::TRUE.
~View3DInventorSelection()
View3DInventorSelection::~View3DInventorSelection ()
Definition at line 88 of file View3DInventorSelection.cpp.
Member Function Documentation
checkGroupOnTop()
void View3DInventorSelection::checkGroupOnTop (const SelectionChanges & Reason)
Definition at line 96 of file View3DInventorSelection.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Gui::SoSelectionElementAction::All, Gui::SoSelectionElementAction::Append, clearGroupOnTop(), Gui::SelectionChanges::ClrSelection, Gui::coinRemoveAllChildren(), Gui::SoFCUnifiedSelection::colorHighlight, FC_LOG, Gui::ViewProvider::getChildRoot(), getDocument(), Gui::Document::getDocument(), App::GeoFeatureGroupExtension::getGroupOfObject(), App::Document::getObject(), App::PropertyEnumeration::getValue(), Gui::Application::getViewProvider(), toolbit-attributes::grp, Gui::Application::Instance, Data::isMappedElement(), Gui::SelectionSingleton::needPickedList(), Gui::SoSelectionElementAction::None, replaceobj::objs, App::ElementNamePair::oldName, Gui::ViewProviderDocumentObject::OnTopWhenSelected, Gui::SelectionChanges::pDocName, Gui::SelectionChanges::pObjectName, Gui::SelectionChanges::pSubName, Gui::SoSelectionElementAction::Remove, App::GeoFeature::resolveElement(), Gui::SelectionChanges::RmvPreselect, Gui::SelectionChanges::RmvPreselectSignal, Gui::SelectionChanges::RmvSelection, Gui::Selection(), Gui::SoFCPathAnnotation::setPath(), Gui::SelectionChanges::SetPreselect, Gui::SelectionChanges::SetSelection, and Gui::SelectionChanges::Type.
clearGroupOnTop()
void View3DInventorSelection::clearGroupOnTop ()
Definition at line 287 of file View3DInventorSelection.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Gui::coinRemoveAllChildren(), FC_LOG, and Gui::SoSelectionElementAction::None.
Referenced by checkGroupOnTop().
getDocument()
Gui::Document* Gui::View3DInventorSelection::getDocument () const inline
Definition at line 48 of file View3DInventorSelection.h.
Referenced by checkGroupOnTop().
setDocument()
void Gui::View3DInventorSelection::setDocument (Gui::Document * pcDocument) inline
Definition at line 45 of file View3DInventorSelection.h.
The documentation for this class was generated from the following files:
View3DInventorSelection.h
View3DInventorSelection.cpp