FreeCAD: Part::GeomArcOfHyperbola Class Reference
Part::GeomArcOfHyperbola Class Reference
#include <Geometry.h>
Public Member Functions
GeomArcOfHyperbola ()
GeomArcOfHyperbola (const Handle(Geom_Hyperbola)&)
~GeomArcOfHyperbola () override
Geometry * copy () const override
double getMajorRadius () const
void setMajorRadius (double Radius)
double getMinorRadius () const
void setMinorRadius (double Radius)
Base::Vector3d getMajorAxisDir () const
GeomArcOfHyperbola::getMajorAxisDir.
void setMajorAxisDir (Base::Vector3d newdir)
GeomArcOfHyperbola::setMajorAxisDir Rotates the hyperbola in its plane, so that its major axis is as close as possible to the provided direction.
Base::Vector3d getMinorAxisDir () const
GeomArcOfHyperbola::getMinorAxisDir.
void getRange (double &u, double &v, bool emulateCCWXY) const override
void setRange (double u, double v, bool emulateCCWXY) override
unsigned int getMemSize () const override
void Save (Base::Writer &) const override
void Restore (Base::XMLReader &) override
PyObject * getPyObject () override
GeomBSplineCurve * toNurbs (double first, double last) const override
void setHandle (const Handle(Geom_TrimmedCurve)&) override
void setHandle (const Handle(Geom_Hyperbola)&)
const Handle (Geom_Geometry) &handle() const override
Public Member Functions inherited from Part::GeomArcOfConic
~GeomArcOfConic () override
Base::Vector3d getStartPoint (bool emulateCCWXY) const
GeomArcOfConic::getStartPoint.
Base::Vector3d getEndPoint (bool emulateCCWXY) const
GeomArcOfConic::getEndPoint.
Base::Vector3d getStartPoint () const override
Base::Vector3d getEndPoint () const override
Base::Vector3d getCenter () const
getCenter
Base::Vector3d getLocation () const
void setLocation (const Base::Vector3d &Center)
void setCenter (const Base::Vector3d &Center)
setCenter
Base::Vector3d getAxisDirection () const
void getRange (double &u, double &v) const override
void setRange (double u, double v) override
bool isReversed () const
GeomArcOfConic::isReversed.
double getAngleXU () const
GeomArcOfConic::getAngleXU.
void setAngleXU (double angle)
GeomArcOfConic::setAngleXU complements getAngleXU.
Base::Vector3d getXAxisDir () const
GeomArcOfConic::getXAxisDir.
void setXAxisDir (const Base::Vector3d &newdir)
GeomArcOfConic::setXAxisDir Rotates the conic in its plane, so that its symmetry axis is as close as possible to the provided direction.
Public Member Functions inherited from Part::GeomTrimmedCurve
GeomTrimmedCurve ()
GeomTrimmedCurve (const Handle(Geom_TrimmedCurve)&)
~GeomTrimmedCurve () override
GeomCurve * createArc (double first, double last) const override
createArc Generates a curve that is an arc of this curve between given parameters
bool isSame (const Geometry &other, double tol, double atol) const override
bool intersectBasisCurves (const GeomTrimmedCurve *c, std::vector< std::pair< Base::Vector3d, Base::Vector3d >> &points, double tol=Precision::Confusion()) const
Public Member Functions inherited from Part::GeomBoundedCurve
GeomBoundedCurve ()
~GeomBoundedCurve () override
Public Member Functions inherited from Part::GeomCurve
GeomCurve ()
~GeomCurve () override
bool isLinear (Base::Vector3d *dir=nullptr, Base::Vector3d *base=nullptr) const
TopoDS_Shape toShape () const override
GeomBSplineCurve * toBSpline (double first, double last) const
toBSpline Converts the curve to a B-spline
bool tangent (double u, gp_Dir &) const
bool tangent (double u, Base::Vector3d &dir) const
Base::Vector3d pointAtParameter (double u) const
Base::Vector3d firstDerivativeAtParameter (double u) const
Base::Vector3d secondDerivativeAtParameter (double u) const
bool closestParameter (const Base::Vector3d &point, double &u) const
bool closestParameterToBasisCurve (const Base::Vector3d &point, double &u) const
double getFirstParameter () const
double getLastParameter () const
double curvatureAt (double u) const
double length (double u, double v) const
bool normalAt (double u, Base::Vector3d &dir) const
bool normalAt (const Base::Vector3d &curvepoint, Base::Vector3d &dir) const
bool intersect (const GeomCurve *c, std::vector< std::pair< Base::Vector3d, Base::Vector3d >> &points, double tol=Precision::Confusion()) const
void reverse ()
Base::Vector3d value (double u) const
GeomLine * toLine (KeepTag clone=CopyTag) const
GeomLineSegment * toLineSegment (KeepTag clone=CopyTag) const
Public Member Functions inherited from Part::Geometry
~Geometry () override
Geometry * clone () const
boost::uuids::uuid getTag () const
returns the tag of the geometry object
bool hasSameExtensions (const Geometry &other) const
std::vector< std::weak_ptr< const GeometryExtension > > getExtensions () const
bool hasExtension (const Base::Type &type) const
bool hasExtension (const std::string &name) const
std::weak_ptr< const GeometryExtension > getExtension (const Base::Type &type) const
std::weak_ptr< const GeometryExtension > getExtension (const std::string &name) const
std::weak_ptr< GeometryExtension > getExtension (const Base::Type &type)
std::weak_ptr< GeometryExtension > getExtension (const std::string &name)
void setExtension (std::unique_ptr< GeometryExtension > &&geo)
void deleteExtension (const Base::Type &type)
void deleteExtension (const std::string &name)
void mirror (const Base::Vector3d &point) const
void mirror (const Base::Vector3d &point, const Base::Vector3d &dir) const
void rotate (const Base::Placement &plm) const
void scale (const Base::Vector3d &vec, double scale) const
void transform (const Base::Matrix4D &mat) const
void translate (const Base::Vector3d &vec) const
Geometry (const Geometry &)=delete
Geometry & operator= (const Geometry &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Static Public Member Functions inherited from Part::GeomCurve
static bool isLinear (const Handle(Geom_Curve) &c, Base::Vector3d *dir=nullptr, Base::Vector3d *base=nullptr)
Static Public Member Functions inherited from Part::Geometry
static std::unique_ptr< Geometry > fromShape (const TopoDS_Shape &s, bool silent=false)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Protected Member Functions inherited from Part::GeomArcOfConic
GeomArcOfConic ()
Protected Member Functions inherited from Part::GeomTrimmedCurve
Handle (Geom_TrimmedCurve) myCurve
Protected Member Functions inherited from Part::Geometry
void createNewTag ()
create a new tag for the geometry object
void assignTag (const Part::Geometry *)
copies the tag from the geometry passed as a parameter to this object
void copyNonTag (const Part::Geometry *)
Geometry ()
Static Protected Member Functions inherited from Part::GeomCurve
static bool intersect (const Handle(Geom_Curve)&c, const Handle(Geom_Curve)&c2, std::vector< std::pair< Base::Vector3d, Base::Vector3d >> &points, double tol=Precision::Confusion())
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Part::Geometry
boost::uuids::uuid tag
std::vector< std::shared_ptr< GeometryExtension > > extensions
Detailed Description
Definition at line 703 of file Part/App/Geometry.h.
Constructor & Destructor Documentation
GeomArcOfHyperbola() [1/2]
GeomArcOfHyperbola::GeomArcOfHyperbola ()
Definition at line 3780 of file Part/App/Geometry.cpp.
References Handle().
GeomArcOfHyperbola() [2/2]
GeomArcOfHyperbola::GeomArcOfHyperbola (const Handle(Geom_Hyperbola)& h) explicit
Definition at line 3787 of file Part/App/Geometry.cpp.
References setHandle().
~GeomArcOfHyperbola()
GeomArcOfHyperbola::~GeomArcOfHyperbola () override default
Member Function Documentation
copy()
Geometry* Part::GeomArcOfHyperbola::copy () const override virtual
returns a copy of this object having a new randomly generated tag. If you also want to copy the tag, you may use clone() instead. For creation of geometry with other handles, with or without the same tag, you may use the constructors and the sethandle functions. The tag of a geometry can be copied to another geometry using the assignTag function.
Implements Part::GeomArcOfConic.
getMajorAxisDir()
Base::Vector3d GeomArcOfHyperbola::getMajorAxisDir () const
GeomArcOfHyperbola::getMajorAxisDir.
Returns
the direction vector (unit-length) of major axis of the hyperbola. The direction also points to the first focus.
Definition at line 3870 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::c, and Handle().
Referenced by Sketcher::Sketch::addArcOfHyperbola(), Sketcher::SketchObject::exposeInternalGeometry(), SketcherGui::makeTangentToArcOfHyperbolaviaNewPoint(), and SketcherGui::EditModeConstraintCoinManager::processConstraints().
getMajorRadius()
double Part::GeomArcOfHyperbola::getMajorRadius () const
Referenced by Sketcher::Sketch::addArcOfHyperbola(), Sketcher::SketchObject::exposeInternalGeometry(), SketcherGui::makeTangentToArcOfHyperbolaviaNewPoint(), and SketcherGui::EditModeConstraintCoinManager::processConstraints().
getMemSize()
unsigned int GeomArcOfHyperbola::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Implements Part::GeomArcOfConic.
Definition at line 3956 of file Part/App/Geometry.cpp.
getMinorAxisDir()
Base::Vector3d GeomArcOfHyperbola::getMinorAxisDir () const
GeomArcOfHyperbola::getMinorAxisDir.
Returns
the direction vector (unit-length) of minor axis of the hyperbola.
Definition at line 3882 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::c, and Handle().
getMinorRadius()
double GeomArcOfHyperbola::getMinorRadius () const
Definition at line 3846 of file Part/App/Geometry.cpp.
References Handle().
Referenced by Sketcher::Sketch::addArcOfHyperbola(), Sketcher::SketchObject::exposeInternalGeometry(), SketcherGui::makeTangentToArcOfHyperbolaviaNewPoint(), and SketcherGui::EditModeConstraintCoinManager::processConstraints().
getPyObject()
PyObject * GeomArcOfHyperbola::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Implements Part::GeomArcOfConic.
Definition at line 4047 of file Part/App/Geometry.cpp.
References Part::Geometry::clone().
getRange()
void GeomArcOfHyperbola::getRange (double & u, double & v, bool emulateCCWXY) const override virtual
Implements Part::GeomArcOfConic.
Definition at line 3916 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::c, SCL.SimpleDataTypes::e, Handle(), Part::GeomArcOfConic::isReversed(), THROWM, buildPsets::u, and TestSpreadsheet::v.
Referenced by Sketcher::Sketch::addArcOfHyperbola(), and SketcherGui::EditModeConstraintCoinManager::processConstraints().
Handle()
const Part::GeomArcOfHyperbola::Handle (Geom_Geometry) const & override virtual
Implements Part::GeomArcOfConic.
Referenced by getMajorAxisDir(), getMinorAxisDir(), getMinorRadius(), getRange(), Restore(), Save(), setHandle(), setMajorAxisDir(), setMinorRadius(), and setRange().
Restore()
void GeomArcOfHyperbola::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Reimplemented from Part::GeomTrimmedCurve.
Definition at line 3993 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::e, gce_ErrorStatusText(), Handle(), TechDrawTools.TaskFillTemplateFields::reader, Part::Geometry::Restore(), and THROWM.
Save()
void GeomArcOfHyperbola::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Reimplemented from Part::GeomTrimmedCurve.
Definition at line 3961 of file Part/App/Geometry.cpp.
References exportCSG::center(), Handle(), Base::Writer::ind(), Part::Geometry::Save(), and Base::Writer::Stream().
setHandle() [1/2]
void GeomArcOfHyperbola::setHandle (const Handle(Geom_Hyperbola)& h)
Definition at line 3802 of file Part/App/Geometry.cpp.
setHandle() [2/2]
void GeomArcOfHyperbola::setHandle (const Handle(Geom_TrimmedCurve)& c) override virtual
Reimplemented from Part::GeomTrimmedCurve.
Definition at line 3794 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::c, and Handle().
Referenced by GeomArcOfHyperbola().
setMajorAxisDir()
void GeomArcOfHyperbola::setMajorAxisDir (Base::Vector3d newdir)
GeomArcOfHyperbola::setMajorAxisDir Rotates the hyperbola in its plane, so that its major axis is as close as possible to the provided direction.
Parameters
newdir [in] is the new direction. If the vector is small, the orientation of the ellipse will be preserved. If the vector is not small, but its projection onto plane of the ellipse is small, an exception will be thrown.
Definition at line 3898 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::c, SCL.SimpleDataTypes::e, Handle(), RobotExample::pos, Base::Vector3< float_type >::Sqr(), THROWM, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
setMajorRadius()
void Part::GeomArcOfHyperbola::setMajorRadius (double Radius)
setMinorRadius()
void GeomArcOfHyperbola::setMinorRadius (double Radius)
Definition at line 3852 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::e, Handle(), and THROWM.
setRange()
void GeomArcOfHyperbola::setRange (double u, double v, bool emulateCCWXY) override virtual
Implements Part::GeomArcOfConic.
Definition at line 3936 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::c, SCL.SimpleDataTypes::e, Handle(), Part::GeomArcOfConic::isReversed(), THROWM, buildPsets::u, and TestSpreadsheet::v.
toNurbs()
GeomBSplineCurve* Part::GeomArcOfHyperbola::toNurbs (double first, double last) const override virtual
The default implementation does the same as toBSpline. In sub-classes this can be reimplemented to create a real NURBS curve and not just an approximation.
Reimplemented from Part::GeomCurve.
The documentation for this class was generated from the following files:
Part/App/Geometry.h
Part/App/Geometry.cpp