FreeCAD: MeshCore::Approximation Class Reference
MeshCore::Approximation Class Reference abstract
#include <Approximation.h>
Public Member Functions
Approximation ()
virtual ~Approximation ()
void AddPoint (const Base::Vector3f &point)
void AddPoints (const std::vector< Base::Vector3f > &points)
void AddPoints (const std::set< Base::Vector3f > &points)
void AddPoints (const std::list< Base::Vector3f > &points)
void AddPoints (const MeshPointArray &points)
const std::list< Base::Vector3f > & GetPoints () const
Base::Vector3f GetGravity () const
std::size_t CountPoints () const
void Clear ()
float GetLastResult () const
virtual float Fit ()=0
bool Done () const
Protected Member Functions
void GetMgcVectorArray (std::vector< Wm4::Vector3< double >> &rcPts) const
Approximation (const Approximation &)=default
Approximation (Approximation &&)=default
Approximation & operator= (const Approximation &)=default
Approximation & operator= (Approximation &&)=default
Protected Attributes
std::list< Base::Vector3f > _vPoints
bool _bIsFitted {false}
float _fLastResult {FLOAT_MAX}
Detailed Description
Abstract base class for approximation of a geometry to a given set of points.
Definition at line 122 of file Approximation.h.
Constructor & Destructor Documentation
Approximation() [1/3]
Approximation::Approximation () default
Construction
~Approximation()
Approximation::~Approximation () virtual
Destroys the object and frees any allocated resources.
Definition at line 56 of file Approximation.cpp.
References Clear().
Approximation() [2/3]
MeshCore::Approximation::Approximation (const Approximation &) protected default
Approximation() [3/3]
MeshCore::Approximation::Approximation (Approximation &&) protected default
Member Function Documentation
AddPoint()
void Approximation::AddPoint (const Base::Vector3f & point)
Add point for the fit algorithm.
Definition at line 70 of file Approximation.cpp.
References _bIsFitted, and _vPoints.
Referenced by MeshCore::MeshDistancePlanarSegment::AddFacet(), MeshCore::PlaneSurfaceFit::AddTriangle(), MeshCore::CylinderSurfaceFit::AddTriangle(), MeshCore::SphereSurfaceFit::AddTriangle(), Reen::ParameterCorrection::CalcEigenvectors(), MeshCore::MeshEigensystem::CalculateLocalSystem(), MeshCore::MeshRefPointToPoints::GetNormal(), MeshCore::AbstractPolygonTriangulator::GetTransformToFitPlane(), MeshCore::MeshDistancePlanarSegment::Initialize(), MeshCore::PlaneSurfaceFit::Initialize(), MeshCore::CylinderSurfaceFit::Initialize(), MeshCore::SphereSurfaceFit::Initialize(), MeshCore::MeshPlaneVisitor::MeshPlaneVisitor(), MeshCore::AbstractPolygonTriangulator::PostProcessing(), MeshCore::PlaneFitSmoothing::Smooth(), MeshCore::PlaneFitSmoothing::SmoothPoints(), and MeshCore::MeshPlaneVisitor::Visit().
AddPoints() [1/4]
void Approximation::AddPoints (const MeshPointArray & points)
Add points for the fit algorithm.
Definition at line 94 of file Approximation.cpp.
References _bIsFitted, and _vPoints.
AddPoints() [2/4]
void Approximation::AddPoints (const std::list< Base::Vector3f > & points)
Add points for the fit algorithm.
Definition at line 88 of file Approximation.cpp.
References _bIsFitted, and _vPoints.
AddPoints() [3/4]
void Approximation::AddPoints (const std::set< Base::Vector3f > & points)
Add points for the fit algorithm.
Definition at line 82 of file Approximation.cpp.
References _bIsFitted, and _vPoints.
AddPoints() [4/4]
void Approximation::AddPoints (const std::vector< Base::Vector3f > & points)
Add points for the fit algorithm.
Definition at line 76 of file Approximation.cpp.
References _bIsFitted, and _vPoints.
Referenced by ReverseEngineeringGui::Segmentation::accept(), MeshCore::FacetCurvature::Compute(), MeshCore::CylinderFit::Fit(), MeshCore::SphereFit::Fit(), MeshCore::CylinderFit::GetInitialAxisFromNormals(), MeshGui::PlaneFitParameter::getParameter(), MeshGui::CylinderFitParameter::getParameter(), MeshGui::SphereFitParameter::getParameter(), ReverseEngineeringGui::SegmentationManual::onCylinderDetectClicked(), ReverseEngineeringGui::SegmentationManual::onPlaneDetectClicked(), and ReverseEngineeringGui::SegmentationManual::onSphereDetectClicked().
Clear()
void Approximation::Clear ()
Deletes the inserted points and frees any allocated resources.
Definition at line 117 of file Approximation.cpp.
References _bIsFitted, and _vPoints.
Referenced by MeshCore::MeshDistancePlanarSegment::Initialize(), MeshCore::PlaneSurfaceFit::Initialize(), MeshCore::CylinderSurfaceFit::Initialize(), MeshCore::SphereSurfaceFit::Initialize(), and ~Approximation().
CountPoints()
std::size_t Approximation::CountPoints () const
Determines the number of the current added points.
Returns
Number of points
Definition at line 112 of file Approximation.cpp.
References _vPoints.
Referenced by MeshCoreFit::SphereFit::Fit(), MeshCoreFit::CylinderFit::Fit(), MeshCore::PlaneFit::Fit(), MeshCore::QuadraticFit::Fit(), MeshCore::SurfaceFit::Fit(), MeshCore::CylinderFit::Fit(), MeshCore::SphereFit::Fit(), MeshCore::PlaneFit::GetSignedStdDeviation(), MeshCoreFit::SphereFit::GetStdDeviation(), MeshCoreFit::CylinderFit::GetStdDeviation(), MeshCore::PlaneFit::GetStdDeviation(), MeshCore::CylinderFit::GetStdDeviation(), MeshCore::SphereFit::GetStdDeviation(), and MeshCore::AbstractPolygonTriangulator::PostProcessing().
Done()
bool Approximation::Done () const
Returns true if Fit() has been called for the current set of points, false otherwise.
Definition at line 128 of file Approximation.cpp.
References _bIsFitted.
Referenced by MeshCore::MeshPlaneVisitor::AllowVisit(), MeshCore::PlaneSurfaceFit::Done(), MeshCore::CylinderSurfaceFit::Done(), MeshCore::SphereSurfaceFit::Done(), MeshCore::CylinderSurfaceFit::GetDistanceToSurface(), and MeshCore::MeshDistancePlanarSegment::TestFacet().
Fit()
virtual float MeshCore::Approximation::Fit () pure virtual
Pure virtual function to fit the geometry to the given points. This function must be implemented by every subclass.
Implemented in MeshCore::PolynomialFit, MeshCore::SphereFit, MeshCore::CylinderFit, MeshCore::SurfaceFit, MeshCore::QuadraticFit, MeshCore::PlaneFit, MeshCoreFit::CylinderFit, and MeshCoreFit::SphereFit.
GetGravity()
Base::Vector3f Approximation::GetGravity () const
Returns the center of gravity of the current added points.
Returns
Base::Vector3f
Definition at line 100 of file Approximation.cpp.
References _vPoints.
Referenced by MeshGui::CylinderFitParameter::getParameter(), ReverseEngineeringGui::SegmentationManual::onCylinderDetectClicked(), and MeshCore::PlaneFit::ProjectToPlane().
GetLastResult()
float Approximation::GetLastResult () const
Returns the result of the last fit.
Returns
float Quality of the last fit.
Definition at line 123 of file Approximation.cpp.
References _fLastResult.
GetMgcVectorArray()
void Approximation::GetMgcVectorArray (std::vector< Wm4::Vector3< double >> & rcPts) const protected
Creates a vector of Wm4::Vector3 elements.
Definition at line 61 of file Approximation.cpp.
References _vPoints.
Referenced by MeshCore::QuadraticFit::Fit().
GetPoints()
const std::list<Base::Vector3f>& MeshCore::Approximation::GetPoints () const inline
Get all added points.
Definition at line 156 of file Approximation.h.
operator=() [1/2]
Approximation& MeshCore::Approximation::operator= (Approximation &&) protected default
operator=() [2/2]
Approximation& MeshCore::Approximation::operator= (const Approximation &) protected default
Member Data Documentation
_bIsFitted
bool MeshCore::Approximation::_bIsFitted {false} protected
Flag, whether the fit has been called.
Definition at line 203 of file Approximation.h.
Referenced by AddPoint(), AddPoints(), MeshCore::QuadraticFit::CalcEigenValues(), MeshCore::QuadraticFit::CalcZValues(), Clear(), MeshCoreFit::SphereFit::ComputeApproximations(), MeshCoreFit::CylinderFit::ComputeApproximationsLine(), Done(), MeshCoreFit::SphereFit::Fit(), MeshCoreFit::CylinderFit::Fit(), MeshCore::PlaneFit::Fit(), MeshCore::QuadraticFit::Fit(), MeshCore::SurfaceFit::Fit(), MeshCore::CylinderFit::Fit(), MeshCore::SphereFit::Fit(), MeshCoreFit::CylinderFit::GetAxis(), MeshCore::CylinderFit::GetAxis(), MeshCoreFit::CylinderFit::GetBase(), MeshCore::PlaneFit::GetBase(), MeshCore::CylinderFit::GetBase(), MeshCoreFit::SphereFit::GetCenter(), MeshCore::SphereFit::GetCenter(), MeshCore::QuadraticFit::GetCoeff(), MeshCore::QuadraticFit::GetCurvatureInfo(), MeshCore::SurfaceFit::GetCurvatureInfo(), MeshCore::PlaneFit::GetDirU(), MeshCore::PlaneFit::GetDirV(), MeshCoreFit::CylinderFit::GetDistanceToCylinder(), MeshCore::CylinderFit::GetDistanceToCylinder(), MeshCore::PlaneFit::GetDistanceToPlane(), MeshCoreFit::SphereFit::GetDistanceToSphere(), MeshCore::SphereFit::GetDistanceToSphere(), MeshCore::PlaneFit::GetLocalPoints(), MeshCore::PlaneFit::GetNormal(), MeshCoreFit::SphereFit::GetNumIterations(), MeshCoreFit::CylinderFit::GetNumIterations(), MeshCoreFit::SphereFit::GetRadius(), MeshCoreFit::CylinderFit::GetRadius(), MeshCore::SphereFit::GetRadius(), MeshCore::PlaneFit::GetSignedStdDeviation(), MeshCoreFit::SphereFit::GetStdDeviation(), MeshCoreFit::CylinderFit::GetStdDeviation(), MeshCore::PlaneFit::GetStdDeviation(), MeshCore::CylinderFit::GetStdDeviation(), MeshCore::SphereFit::GetStdDeviation(), MeshCoreFit::SphereFit::SetApproximations(), MeshCoreFit::CylinderFit::SetApproximations(), and MeshCore::SurfaceFit::Value().
_fLastResult
float MeshCore::Approximation::_fLastResult {FLOAT_MAX} protected
Stores the last result of the fit
Definition at line 204 of file Approximation.h.
Referenced by MeshCoreFit::SphereFit::ComputeApproximations(), MeshCoreFit::CylinderFit::ComputeApproximationsLine(), MeshCoreFit::SphereFit::Fit(), MeshCoreFit::CylinderFit::Fit(), MeshCore::PlaneFit::Fit(), MeshCore::QuadraticFit::Fit(), MeshCore::SurfaceFit::Fit(), MeshCore::CylinderFit::Fit(), MeshCore::SphereFit::Fit(), GetLastResult(), MeshCore::PlaneFit::GetLocalPoints(), MeshCoreFit::SphereFit::SetApproximations(), and MeshCoreFit::CylinderFit::SetApproximations().
_vPoints
std::list<Base::Vector3f> MeshCore::Approximation::_vPoints protected
Holds the points for the fit algorithm.
Definition at line 202 of file Approximation.h.
Referenced by AddPoint(), AddPoints(), Clear(), MeshCoreFit::SphereFit::ComputeApproximations(), MeshCoreFit::CylinderFit::ComputeApproximationsLine(), MeshCoreFit::SphereFit::computeResiduals(), MeshCoreFit::CylinderFit::computeResiduals(), CountPoints(), MeshCore::PlaneFit::Dimension(), MeshCore::PlaneFit::Fit(), MeshCore::CylinderFit::Fit(), MeshCore::SphereFit::Fit(), MeshCore::PolynomialFit::Fit(), MeshCore::CylinderFit::GetBounding(), GetGravity(), MeshCore::PlaneFit::GetLocalPoints(), GetMgcVectorArray(), MeshCore::PlaneFit::GetSignedStdDeviation(), MeshCoreFit::SphereFit::GetStdDeviation(), MeshCoreFit::CylinderFit::GetStdDeviation(), MeshCore::PlaneFit::GetStdDeviation(), MeshCore::CylinderFit::GetStdDeviation(), MeshCore::SphereFit::GetStdDeviation(), MeshCoreFit::CylinderFit::meanXObs(), MeshCoreFit::CylinderFit::meanYObs(), MeshCoreFit::CylinderFit::meanZObs(), MeshCoreFit::CylinderFit::ProjectToCylinder(), MeshCore::CylinderFit::ProjectToCylinder(), MeshCore::PlaneFit::ProjectToPlane(), MeshCoreFit::SphereFit::ProjectToSphere(), MeshCore::SphereFit::ProjectToSphere(), MeshCoreFit::CylinderFit::SetApproximations(), MeshCoreFit::SphereFit::setupNormalEquationMatrices(), and MeshCoreFit::CylinderFit::setupNormalEquationMatrices().
The documentation for this class was generated from the following files:
Approximation.h
Approximation.cpp