FreeCAD: ReverseEngineeringGui::SegmentationManual Class Reference
ReverseEngineeringGui::SegmentationManual Class Reference
#include <SegmentationManual.h>
Classes
class Private
Public Member Functions
SegmentationManual (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~SegmentationManual () override
void reject ()
void createSegment ()
void setupConnections ()
void onSelectRegionClicked ()
void onSelectAllClicked ()
void onSelectComponentsClicked ()
void onSelectTriangleClicked ()
void onDeselectAllClicked ()
void onVisibleTrianglesToggled (bool)
void onScreenTrianglesToggled (bool)
void onSelectCompToggled (bool)
void onPlaneDetectClicked ()
void onCylinderDetectClicked ()
void onSphereDetectClicked ()
Protected Member Functions
void changeEvent (QEvent *e) override
Detailed Description
Dialog to create segments from components, regions, the complete or single faces of a mesh.
Author
Werner Mayer
Definition at line 64 of file SegmentationManual.h.
Constructor & Destructor Documentation
SegmentationManual()
SegmentationManual::SegmentationManual (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags()) explicit
Definition at line 44 of file SegmentationManual.cpp.
References Gui::SelectionSingleton::clearSelection(), Gui::Selection(), MeshGui::MeshSelection::setCheckOnlyPointToUserTriangles(), MeshGui::MeshSelection::setCheckOnlyVisibleTriangles(), MeshGui::MeshSelection::setEnabledViewerSelection(), and setupConnections().
~SegmentationManual()
SegmentationManual::~SegmentationManual () override default
Member Function Documentation
changeEvent()
void SegmentationManual::changeEvent (QEvent * e) override protected
Definition at line 103 of file SegmentationManual.cpp.
References SCL.SimpleDataTypes::e.
createSegment()
void SegmentationManual::createSegment ()
Definition at line 273 of file SegmentationManual.cpp.
References Gui::Document::abortCommand(), Gui::Application::activeDocument(), App::Document::addObject(), Mesh::MeshObject::clearFacetSelection(), MeshGui::MeshSelection::clearSelection(), Gui::Document::commitCommand(), MeshCore::MeshAlgorithm::CountFacetFlag(), Mesh::MeshObject::deleteFacets(), Mesh::PropertyMeshKernel::finishEditing(), Gui::Document::getDocument(), MeshCore::MeshAlgorithm::GetFacetsFlag(), App::Document::getObjectsOfType(), Gui::Application::Instance, Mesh2Shape::mesh, Mesh::Feature::Mesh, Gui::Document::openCommand(), Arch::QT_TRANSLATE_NOOP, MeshCore::MeshFacet::SELECTED, App::PropertyBool::setValue(), Mesh::PropertyMeshKernel::startEditing(), Mesh::MeshObject::swap(), and App::DocumentObject::Visibility.
Referenced by ReverseEngineeringGui::TaskSegmentationManual::clicked().
onCylinderDetectClicked()
void SegmentationManual::onCylinderDetectClicked ()
Definition at line 229 of file SegmentationManual.cpp.
References MeshCore::Approximation::AddPoints(), ReverseEngineeringGui::SegmentationManual::Private::findGeometry(), MeshCore::CylinderFit::Fit(), FLOAT_MAX, MeshCore::CylinderFit::GetAxis(), MeshCore::CylinderFit::GetBase(), MeshCore::Approximation::GetGravity(), MeshCore::CylinderFit::GetInitialAxisFromNormals(), MeshCore::CylinderFit::GetRadius(), and MeshCore::CylinderFit::SetInitialValues().
Referenced by setupConnections().
onDeselectAllClicked()
void SegmentationManual::onDeselectAllClicked ()
Definition at line 122 of file SegmentationManual.cpp.
References MeshGui::MeshSelection::clearSelection().
Referenced by setupConnections().
onPlaneDetectClicked()
void SegmentationManual::onPlaneDetectClicked ()
Definition at line 210 of file SegmentationManual.cpp.
References MeshCore::Approximation::AddPoints(), ReverseEngineeringGui::SegmentationManual::Private::findGeometry(), MeshCore::PlaneFit::Fit(), FLOAT_MAX, MeshCore::PlaneFit::GetBase(), and MeshCore::PlaneFit::GetNormal().
Referenced by setupConnections().
onScreenTrianglesToggled()
void SegmentationManual::onScreenTrianglesToggled (bool on)
Definition at line 140 of file SegmentationManual.cpp.
References MeshGui::MeshSelection::setCheckOnlyPointToUserTriangles().
Referenced by setupConnections().
onSelectAllClicked()
void SegmentationManual::onSelectAllClicked ()
Definition at line 116 of file SegmentationManual.cpp.
References MeshGui::MeshSelection::fullSelection().
Referenced by setupConnections().
onSelectComponentsClicked()
void SegmentationManual::onSelectComponentsClicked ()
Definition at line 128 of file SegmentationManual.cpp.
References MeshGui::MeshSelection::selectComponent().
Referenced by setupConnections().
onSelectCompToggled()
void SegmentationManual::onSelectCompToggled (bool on)
Definition at line 145 of file SegmentationManual.cpp.
References MeshGui::MeshSelection::setAddComponentOnClick().
Referenced by setupConnections().
onSelectRegionClicked()
void SegmentationManual::onSelectRegionClicked ()
Definition at line 111 of file SegmentationManual.cpp.
References MeshGui::MeshSelection::startSelection().
Referenced by setupConnections().
onSelectTriangleClicked()
void SegmentationManual::onSelectTriangleClicked ()
Definition at line 326 of file SegmentationManual.cpp.
References MeshGui::MeshSelection::selectTriangle(), and MeshGui::MeshSelection::setAddComponentOnClick().
Referenced by setupConnections().
onSphereDetectClicked()
void SegmentationManual::onSphereDetectClicked ()
Definition at line 254 of file SegmentationManual.cpp.
References MeshCore::Approximation::AddPoints(), ReverseEngineeringGui::SegmentationManual::Private::findGeometry(), MeshCore::SphereFit::Fit(), FLOAT_MAX, MeshCore::SphereFit::GetCenter(), and MeshCore::SphereFit::GetRadius().
Referenced by setupConnections().
onVisibleTrianglesToggled()
void SegmentationManual::onVisibleTrianglesToggled (bool on)
Definition at line 135 of file SegmentationManual.cpp.
References MeshGui::MeshSelection::setCheckOnlyVisibleTriangles().
Referenced by setupConnections().
reject()
void SegmentationManual::reject ()
Definition at line 332 of file SegmentationManual.cpp.
References MeshGui::MeshSelection::clearSelection(), and MeshGui::MeshSelection::setEnabledViewerSelection().
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and ReverseEngineeringGui::TaskSegmentationManual::clicked().
setupConnections()
void SegmentationManual::setupConnections ()
Definition at line 61 of file SegmentationManual.cpp.
References draftgeoutils.intersections::connect(), onCylinderDetectClicked(), onDeselectAllClicked(), onPlaneDetectClicked(), onScreenTrianglesToggled(), onSelectAllClicked(), onSelectComponentsClicked(), onSelectCompToggled(), onSelectRegionClicked(), onSelectTriangleClicked(), onSphereDetectClicked(), and onVisibleTrianglesToggled().
Referenced by SegmentationManual().
The documentation for this class was generated from the following files:
SegmentationManual.h
SegmentationManual.cpp