FreeCAD: Base::InputStream Class Reference
Base::InputStream Class Reference
#include <Stream.h>
Public Member Functions
InputStream (std::istream &rin)
~InputStream () override
InputStream & operator>> (bool &b)
InputStream & operator>> (int8_t &ch)
InputStream & operator>> (uint8_t &uch)
InputStream & operator>> (int16_t &s)
InputStream & operator>> (uint16_t &us)
InputStream & operator>> (int32_t &i)
InputStream & operator>> (uint32_t &ui)
InputStream & operator>> (int64_t &l)
InputStream & operator>> (uint64_t &ul)
InputStream & operator>> (float &f)
InputStream & operator>> (double &d)
InputStream & read (char *s, int n)
operator bool () const
InputStream (const InputStream &)=delete
InputStream (InputStream &&)=delete
void operator= (const InputStream &)=delete
void operator= (InputStream &&)=delete
Public Member Functions inherited from Base::Stream
ByteOrder byteOrder () const
void setByteOrder (ByteOrder)
virtual ~Stream ()
Additional Inherited Members
Public Types inherited from Base::Stream
enum ByteOrder { BigEndian, LittleEndian }
Protected Member Functions inherited from Base::Stream
Stream ()
Stream (const Stream &)=default
Stream (Stream &&)=default
Stream & operator= (const Stream &)=default
Stream & operator= (Stream &&)=default
bool isSwapped () const
Detailed Description
The InputStream class provides reading of binary data from an istream.
Author
Werner Mayer
Definition at line 113 of file Stream.h.
Constructor & Destructor Documentation
InputStream() [1/3]
InputStream::InputStream (std::istream & rin) explicit
Definition at line 159 of file Stream.cpp.
~InputStream()
InputStream::~InputStream () override default
InputStream() [2/3]
Base::InputStream::InputStream (const InputStream &) delete
InputStream() [3/3]
Base::InputStream::InputStream (InputStream &&) delete
Member Function Documentation
operator bool()
Base::InputStream::operator bool () const inline explicit
Definition at line 133 of file Stream.h.
operator=() [1/2]
void Base::InputStream::operator= (const InputStream &) delete
operator=() [2/2]
void Base::InputStream::operator= (InputStream &&) delete
operator>>() [1/11]
InputStream & InputStream::operator>> (bool & b)
Definition at line 165 of file Stream.cpp.
References SCL.SimpleDataTypes::b.
operator>>() [2/11]
InputStream & InputStream::operator>> (double & d)
Definition at line 246 of file Stream.cpp.
References Base::Stream::isSwapped().
operator>>() [3/11]
InputStream & InputStream::operator>> (float & f)
Definition at line 237 of file Stream.cpp.
References SCL.SimpleDataTypes::f, and Base::Stream::isSwapped().
operator>>() [4/11]
InputStream & InputStream::operator>> (int16_t & s)
Definition at line 183 of file Stream.cpp.
References Base::Stream::isSwapped(), and toolbit-attributes::s.
operator>>() [5/11]
InputStream & InputStream::operator>> (int32_t & i)
Definition at line 201 of file Stream.cpp.
References SplineSurface::i, and Base::Stream::isSwapped().
operator>>() [6/11]
InputStream & InputStream::operator>> (int64_t & l)
Definition at line 219 of file Stream.cpp.
References Base::Stream::isSwapped(), and RobotExample::l.
operator>>() [7/11]
InputStream & InputStream::operator>> (int8_t & ch)
Definition at line 171 of file Stream.cpp.
operator>>() [8/11]
InputStream & InputStream::operator>> (uint16_t & us)
Definition at line 192 of file Stream.cpp.
References Base::Stream::isSwapped().
operator>>() [9/11]
InputStream & InputStream::operator>> (uint32_t & ui)
Definition at line 210 of file Stream.cpp.
References Base::Stream::isSwapped().
operator>>() [10/11]
InputStream & InputStream::operator>> (uint64_t & ul)
Definition at line 228 of file Stream.cpp.
References Base::Stream::isSwapped().
operator>>() [11/11]
InputStream & InputStream::operator>> (uint8_t & uch)
Definition at line 177 of file Stream.cpp.
read()
InputStream & InputStream::read (char * s, int n)
Definition at line 255 of file Stream.cpp.
References toolbit-attributes::s.
The documentation for this class was generated from the following files:
Stream.h
Stream.cpp