FreeCAD: Fem Namespace Reference
Fem Namespace Reference
Classes
class Constraint
Base class of all Constraint Objects of the Fem module.
class ConstraintBearing
class ConstraintContact
class ConstraintDisplacement
class ConstraintFixed
class ConstraintFluidBoundary
class ConstraintForce
class ConstraintGear
class ConstraintHeatflux
class ConstraintInitialTemperature
class ConstraintPlaneRotation
class ConstraintPressure
class ConstraintPulley
class ConstraintRigidBody
class ConstraintSpring
class ConstraintTemperature
class ConstraintTransform
class DocumentObject
class FemAnalysis
Container of objects relevant to one simulation.
class FemMesh
class FemMeshObject
class FemMeshShapeBaseObject
class FemMeshShapeNetgenObject
class FemMeshShapeObject
class FemPostBoxFunction
class FemPostClipFilter
class FemPostContoursFilter
class FemPostCutFilter
class FemPostCylinderFunction
class FemPostDataAlongLineFilter
class FemPostDataAtPointFilter
class FemPostFilter
class FemPostFunction
class FemPostFunctionProvider
class FemPostObject
class FemPostPipeline
class FemPostPlaneFunction
class FemPostScalarClipFilter
class FemPostSmoothFilterExtension
class FemPostSphereFunction
class FemPostWarpVectorFilter
class FemResultObject
Father of all result data in a Fem Analysis.
class FemSetElementNodesObject
class FemSetElementsObject
class FemSetFacesObject
class FemSetGeometryObject
class FemSetNodesObject
class FemSetObject
class FemSolverObject
Father of all result data in a Fem Analysis.
class FemVTKTools
class HypothesisPy
class Module
class PropertyFemMesh
class PropertyPostDataObject
class SMESH_HypothesisPy
class StdMeshers_Arithmetic1DPy
class StdMeshers_AutomaticLengthPy
class StdMeshers_CompositeSegment_1DPy
class StdMeshers_Deflection1DPy
class StdMeshers_Hexa_3DPy
class StdMeshers_LayerDistributionPy
class StdMeshers_LengthFromEdgesPy
class StdMeshers_LocalLengthPy
class StdMeshers_MaxElementAreaPy
class StdMeshers_MaxElementVolumePy
class StdMeshers_MaxLengthPy
class StdMeshers_MEFISTO_2DPy
class StdMeshers_NotConformAllowedPy
class StdMeshers_NumberOfLayersPy
class StdMeshers_NumberOfSegmentsPy
class StdMeshers_Prism_3DPy
class StdMeshers_Projection_1DPy
class StdMeshers_Projection_2DPy
class StdMeshers_Projection_3DPy
class StdMeshers_ProjectionSource1DPy
class StdMeshers_ProjectionSource2DPy
class StdMeshers_ProjectionSource3DPy
class StdMeshers_Quadrangle_2DPy
class StdMeshers_QuadranglePreferencePy
class StdMeshers_QuadraticMeshPy
class StdMeshers_RadialPrism_3DPy
class StdMeshers_Regular_1DPy
class StdMeshers_SegmentAroundVertex_0DPy
class StdMeshers_SegmentLengthAroundVertexPy
class StdMeshers_StartEndLengthPy
class StdMeshers_TrianglePreferencePy
class StdMeshers_UseExisting_1DPy
class StdMeshers_UseExisting_2DPy
class Tools
Typedefs
using FemAnalysisPython = App::FeaturePythonT< FemAnalysis >
using FeaturePython = App::FeaturePythonT< DocumentObject >
using ConstraintPython = App::FeaturePythonT< Constraint >
using SMESH_HypothesisPtr = std::shared_ptr< SMESH_Hypothesis >
using FemMeshObjectPython = App::FeaturePythonT< FemMeshObject >
using FemMeshShapeBaseObjectPython = App::FeaturePythonT< FemMeshShapeBaseObject >
using FemResultObjectPython = App::FeaturePythonT< FemResultObject >
using FemSolverObjectPython = App::FeaturePythonT< FemSolverObject >
using Hypothesis = Py::ExtensionObject< HypothesisPy >
Enumerations
enum ABAQUS_VolumeVariant {
ABAQUS_VolumeVariant::Standard, ABAQUS_VolumeVariant::Reduced, ABAQUS_VolumeVariant::Incompatible, ABAQUS_VolumeVariant::Modified,
ABAQUS_VolumeVariant::Fluid
}
enum ABAQUS_FaceVariant {
ABAQUS_FaceVariant::Shell, ABAQUS_FaceVariant::Shell_Reduced, ABAQUS_FaceVariant::Membrane, ABAQUS_FaceVariant::Membrane_Reduced,
ABAQUS_FaceVariant::Stress, ABAQUS_FaceVariant::Stress_Reduced, ABAQUS_FaceVariant::Strain, ABAQUS_FaceVariant::Strain_Reduced,
ABAQUS_FaceVariant::Axisymmetric, ABAQUS_FaceVariant::Axisymmetric_Reduced
}
enum ABAQUS_EdgeVariant { ABAQUS_EdgeVariant::Beam, ABAQUS_EdgeVariant::Beam_Reduced, ABAQUS_EdgeVariant::Truss, ABAQUS_EdgeVariant::Network }
Functions
PyObject * initModule ()
template<class TReader >
vtkDataSet * readVTKFile (const char *fileName)
template<class TWriter >
void writeVTKFile (const char *filename, vtkSmartPointer< vtkUnstructuredGrid > dataset)
void exportFemMeshEdges (vtkSmartPointer< vtkCellArray > &elemArray, std::vector< int > &types, const SMDS_EdgeIteratorPtr &aEdgeIter)
void exportFemMeshFaces (vtkSmartPointer< vtkCellArray > &elemArray, std::vector< int > &types, const SMDS_FaceIteratorPtr &aFaceIter)
void exportFemMeshCells (vtkSmartPointer< vtkCellArray > &elemArray, std::vector< int > &types, const SMDS_VolumeIteratorPtr &aVolIter)
App::DocumentObject * getObjectByType (const Base::Type type)
App::DocumentObject * createObjectByType (const Base::Type type)
std::map< std::string, std::string > _getFreeCADMechResultVectorProperties ()
std::map< std::string, std::string > _getFreeCADMechResultScalarProperties ()
Typedef Documentation
ConstraintPython
using Fem::ConstraintPython = typedef App::FeaturePythonT<Constraint>
Definition at line 252 of file FemConstraint.h.
FeaturePython
using Fem::FeaturePython = typedef App::FeaturePythonT<DocumentObject>
Definition at line 119 of file FemAnalysis.h.
FemAnalysisPython
using Fem::FemAnalysisPython = typedef App::FeaturePythonT<FemAnalysis>
Definition at line 118 of file FemAnalysis.h.
FemMeshObjectPython
using Fem::FemMeshObjectPython = typedef App::FeaturePythonT<FemMeshObject>
Definition at line 92 of file FemMeshObject.h.
FemMeshShapeBaseObjectPython
using Fem::FemMeshShapeBaseObjectPython = typedef App::FeaturePythonT<FemMeshShapeBaseObject>
Definition at line 95 of file FemMeshShapeObject.h.
FemResultObjectPython
using Fem::FemResultObjectPython = typedef App::FeaturePythonT<FemResultObject>
Definition at line 85 of file FemResultObject.h.
FemSolverObjectPython
using Fem::FemSolverObjectPython = typedef App::FeaturePythonT<FemSolverObject>
Definition at line 79 of file FemSolverObject.h.
Hypothesis
using Fem::Hypothesis = typedef Py::ExtensionObject<HypothesisPy>
Definition at line 51 of file HypothesisPy.h.
SMESH_HypothesisPtr
using Fem::SMESH_HypothesisPtr = typedef std::shared_ptr<SMESH_Hypothesis>
Definition at line 79 of file FemMesh.h.
Enumeration Type Documentation
ABAQUS_EdgeVariant
enum Fem::ABAQUS_EdgeVariant strong
Enumerator
Beam
Beam_Reduced
Truss
Network
Definition at line 71 of file FemMesh.h.
ABAQUS_FaceVariant
enum Fem::ABAQUS_FaceVariant strong
Enumerator
Shell
Shell_Reduced
Membrane
Membrane_Reduced
Stress
Stress_Reduced
Strain
Strain_Reduced
Axisymmetric
Axisymmetric_Reduced
Definition at line 58 of file FemMesh.h.
ABAQUS_VolumeVariant
enum Fem::ABAQUS_VolumeVariant strong
Enumerator
Standard
Reduced
Incompatible
Modified
Fluid
Definition at line 50 of file FemMesh.h.
Function Documentation
_getFreeCADMechResultScalarProperties()
std::map<std::string, std::string> Fem::_getFreeCADMechResultScalarProperties ()
Definition at line 740 of file FemVTKTools.cpp.
_getFreeCADMechResultVectorProperties()
std::map<std::string, std::string> Fem::_getFreeCADMechResultVectorProperties ()
Definition at line 718 of file FemVTKTools.cpp.
createObjectByType()
App::DocumentObject* Fem::createObjectByType (const Base::Type type)
Definition at line 583 of file FemVTKTools.cpp.
References Base::Console(), Base::ConsoleSingleton::Error(), SCL.SimpleDataTypes::f, App::Application::getActiveDocument(), App::GetApplication(), Base::ConsoleSingleton::Log(), Base::ConsoleSingleton::Message(), and RobotExample::Start.
exportFemMeshCells()
void Fem::exportFemMeshCells (vtkSmartPointer< vtkCellArray > & elemArray, std::vector< int > & types, const SMDS_VolumeIteratorPtr & aVolIter)
Definition at line 419 of file FemVTKTools.cpp.
exportFemMeshEdges()
void Fem::exportFemMeshEdges (vtkSmartPointer< vtkCellArray > & elemArray, std::vector< int > & types, const SMDS_EdgeIteratorPtr & aEdgeIter)
Definition at line 363 of file FemVTKTools.cpp.
exportFemMeshFaces()
void Fem::exportFemMeshFaces (vtkSmartPointer< vtkCellArray > & elemArray, std::vector< int > & types, const SMDS_FaceIteratorPtr & aFaceIter)
Definition at line 387 of file FemVTKTools.cpp.
getObjectByType()
App::DocumentObject* Fem::getObjectByType (const Base::Type type)
Definition at line 559 of file FemVTKTools.cpp.
initModule()
PyObject * Fem::initModule ()
Definition at line 355 of file AppFemPy.cpp.
Referenced by PyMOD_INIT_FUNC().
readVTKFile()
template<class TReader > vtkDataSet* Fem::readVTKFile (const char * fileName)
Definition at line 102 of file FemVTKTools.cpp.
References SplineSurface::i, and App::New.
writeVTKFile()
template<class TWriter > void Fem::writeVTKFile (const char * filename, vtkSmartPointer< vtkUnstructuredGrid > dataset)
Definition at line 115 of file FemVTKTools.cpp.