FreeCAD: PartGui::TaskChamferEdges Class Reference
PartGui::TaskChamferEdges Class Reference
#include <DlgFilletEdges.h>
Public Member Functions
TaskChamferEdges (Part::Chamfer *)
~TaskChamferEdges () override
void open () override
is called by the framework when the dialog is opened
void clicked (int) override
is called by the framework if a button is clicked which has no accept or reject role
bool accept () override
is called by the framework if the dialog is accepted (Ok)
bool reject () override
is called by the framework if the dialog is rejected (Cancel)
QDialogButtonBox::StandardButtons getStandardButtons () const override
tells the framework which buttons are wished for the dialog
bool needsFullSpace () const override
Public Member Functions inherited from Gui::TaskView::TaskDialog
TaskDialog ()
~TaskDialog () override
QWidget * addTaskBox (QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBox (const QPixmap &icon, QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBoxWithoutHeader (QWidget *widget)
void setButtonPosition (ButtonPosition p)
ButtonPosition buttonPosition () const
const std::vector< QWidget * > & getDialogContent () const
bool canClose () const
virtual void modifyStandardButtons (QDialogButtonBox *)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
bool isEscapeButtonEnabled () const
void setAutoCloseOnTransactionChange (bool on)
bool isAutoCloseOnTransactionChange () const
void setAutoCloseOnDeletedDocument (bool on)
bool isAutoCloseOnDeletedDocument () const
const std::string & getDocumentName () const
void setDocumentName (const std::string &doc)
void setAutoCloseOnClosedView (bool on)
bool isAutoCloseOnClosedView () const
void associateToObject3dView (App::DocumentObject *obj)
const Gui::MDIView * getAssociatedView () const
void setAssociatedView (const Gui::MDIView *view)
virtual bool isAllowedAlterDocument () const
virtual bool isAllowedAlterView () const
virtual bool isAllowedAlterSelection () const
virtual void closed ()
is called by the framework when the dialog is closed
virtual void autoClosedOnTransactionChange ()
virtual void autoClosedOnDeletedDocument ()
virtual void autoClosedOnClosedView ()
virtual void helpRequested ()
is called by the framework if the user press the help button
void emitDestructionSignal ()
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North, South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Protected Attributes inherited from Gui::TaskView::TaskDialog
QPointer< QDialogButtonBox > buttonBox
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Detailed Description
Definition at line 173 of file DlgFilletEdges.h.
Constructor & Destructor Documentation
TaskChamferEdges()
TaskChamferEdges::TaskChamferEdges (Part::Chamfer * chamfer) explicit
Definition at line 1124 of file DlgFilletEdges.cpp.
References Gui::TaskView::TaskDialog::addTaskBox(), and Gui::BitmapFactory().
~TaskChamferEdges()
TaskChamferEdges::~TaskChamferEdges () override
Definition at line 1130 of file DlgFilletEdges.cpp.
Member Function Documentation
accept()
bool TaskChamferEdges::accept () override virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 1143 of file DlgFilletEdges.cpp.
References PartGui::DlgFilletEdges::accept(), doCommand, and Gui::Command::Gui.
clicked()
void TaskChamferEdges::clicked (int) override virtual
is called by the framework if a button is clicked which has no accept or reject role
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 1139 of file DlgFilletEdges.cpp.
getStandardButtons()
QDialogButtonBox::StandardButtons PartGui::TaskChamferEdges::getStandardButtons () const inline override virtual
tells the framework which buttons are wished for the dialog
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 187 of file DlgFilletEdges.h.
needsFullSpace()
bool PartGui::TaskChamferEdges::needsFullSpace () const inline override virtual
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 189 of file DlgFilletEdges.h.
open()
void TaskChamferEdges::open () override virtual
is called by the framework when the dialog is opened
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 1135 of file DlgFilletEdges.cpp.
reject()
bool TaskChamferEdges::reject () override virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 1151 of file DlgFilletEdges.cpp.
References doCommand, and Gui::Command::Gui.
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action().
The documentation for this class was generated from the following files:
DlgFilletEdges.h
DlgFilletEdges.cpp