FreeCAD: Import::ImpExpDxfRead Class Reference
Import::ImpExpDxfRead Class Reference
#include <ImpExpDxf.h>
Classes
class Block
class BlockDefinitionCollector
class DrawingEntityCollector
class EntityCollector
class Layer
class ShapeSavingEntityCollector
Public Member Functions
ImpExpDxfRead (const std::string &filepath, App::Document *pcDoc)
ImpExpDxfRead (const ImpExpDxfRead &)=delete
ImpExpDxfRead (ImpExpDxfRead &&)=delete
void operator= (const ImpExpDxfRead &)=delete
void operator= (ImpExpDxfRead &&)=delete
~ImpExpDxfRead () override
bool ReadEntitiesSection () override
bool OnReadBlock (const std::string &name, int flags) override
void OnReadLine (const Base::Vector3d &start, const Base::Vector3d &end, bool hidden) override
void OnReadPoint (const Base::Vector3d &start) override
void OnReadText (const Base::Vector3d &point, double height, const std::string &text, double rotation) override
void OnReadArc (const Base::Vector3d &start, const Base::Vector3d &end, const Base::Vector3d &center, bool dir, bool hidden) override
void OnReadCircle (const Base::Vector3d &start, const Base::Vector3d &center, bool dir, bool hidden) override
void OnReadEllipse (const Base::Vector3d &center, double major_radius, double minor_radius, double rotation, double start_angle, double end_angle, bool dir) override
void OnReadSpline (struct SplineData &sd) override
void OnReadInsert (const Base::Vector3d &point, const Base::Vector3d &scale, const std::string &name, double rotation) override
void ExpandInsert (const std::string &name, const Base::Matrix4D &transform, const Base::Vector3d &point, double rotation, const Base::Vector3d &scale)
void OnReadDimension (const Base::Vector3d &start, const Base::Vector3d &end, const Base::Vector3d &point, double rotation) override
void OnReadPolyline (std::list< VertexInfo > &, int flags) override
std::string Deformat (const char *text)
std::string getOptionSource ()
void setOptionSource (const std::string &sourceName)
void setOptions ()
Public Member Functions inherited from CDxfRead
CDxfRead (const std::string &filepath)
CDxfRead (const CDxfRead &)=delete
CDxfRead (const CDxfRead &&)=delete
CDxfRead & operator= (const CDxfRead &)=delete
CDxfRead & operator= (const CDxfRead &&)=delete
virtual ~CDxfRead ()
bool Failed () const
void DoRead (bool ignore_errors=false)
virtual void StartImport ()
virtual void FinishImport ()
bool IgnoreErrors () const
bool LineTypeIsHidden () const
Protected Types
using FeaturePythonBuilder = std::function< App::FeaturePython *(const Base::Matrix4D &transform)>
Protected Types inherited from CDxfRead
using eEntityMergeType_t = enum { MergeShapes, SingleShapes, DraftObjects }
Protected Member Functions
PyObject * getDraftModule ()
CDxfRead::Layer * MakeLayer (const std::string &name, ColorIndex_t color, std::string &&lineType) override
virtual void ApplyGuiStyles (Part::Feature *) const
virtual void ApplyGuiStyles (App::FeaturePython *) const
Protected Member Functions inherited from CDxfRead
void SetAdditionalScaling (double scaling)
bool ExplodePolyline (std::list< VertexInfo > &, int flags)
bool ReadBlockContents ()
bool SkipBlockContents ()
template<typename... args>
void UnsupportedFeature (const char *format, args &&... argValues)
Additional Inherited Members
Static Public Member Functions inherited from CDxfRead
static App::Color ObjectColor (ColorIndex_t colorIndex)
Static Protected Member Functions inherited from CDxfRead
template<typename... args>
static void ImportError (const char *format, args &&... argValues)
template<typename... args>
static void ImportObservation (const char *format, args &&... argValues)
Protected Attributes inherited from CDxfRead
bool m_preserveLayers = true
bool m_preserveColors = true
eEntityMergeType_t m_mergeOption = DraftObjects
bool m_importAnnotations = true
bool m_importPoints = true
bool m_importPaperSpaceEntities = false
bool m_importHiddenBlocks = false
bool m_importFrozenLayers = false
bool m_importHiddenLayers = true
eDXFVersion_t m_version = RUnknown
std::map< std::string, Layer * > Layers
CommonEntityAttributes m_entityAttributes
Base::Matrix4D OCSOrientationTransform
Detailed Description
Definition at line 40 of file ImpExpDxf.h.
Member Typedef Documentation
FeaturePythonBuilder
using Import::ImpExpDxfRead::FeaturePythonBuilder = std::function<App::FeaturePython*(const Base::Matrix4D& transform)> protected
Definition at line 157 of file ImpExpDxf.h.
Constructor & Destructor Documentation
ImpExpDxfRead() [1/3]
ImpExpDxfRead::ImpExpDxfRead (const std::string & filepath, App::Document * pcDoc)
Definition at line 82 of file ImpExpDxf.cpp.
References setOptions(), and setOptionSource().
ImpExpDxfRead() [2/3]
Import::ImpExpDxfRead::ImpExpDxfRead (const ImpExpDxfRead &) delete
ImpExpDxfRead() [3/3]
Import::ImpExpDxfRead::ImpExpDxfRead (ImpExpDxfRead &&) delete
~ImpExpDxfRead()
Import::ImpExpDxfRead::~ImpExpDxfRead () inline override
Definition at line 48 of file ImpExpDxf.h.
Member Function Documentation
ApplyGuiStyles() [1/2]
virtual void Import::ImpExpDxfRead::ApplyGuiStyles (App::FeaturePython *) const inline protected virtual
Reimplemented in ImportGui::ImpExpDxfReadGui.
Definition at line 203 of file ImpExpDxf.h.
ApplyGuiStyles() [2/2]
virtual void Import::ImpExpDxfRead::ApplyGuiStyles (Part::Feature *) const inline protected virtual
Reimplemented in ImportGui::ImpExpDxfReadGui.
Definition at line 201 of file ImpExpDxf.h.
Referenced by ExpandInsert().
Deformat()
std::string ImpExpDxfRead::Deformat (const char * text)
Definition at line 699 of file ImpExpDxf.cpp.
References SplineSurface::i.
ExpandInsert()
void ImpExpDxfRead::ExpandInsert (const std::string & name, const Base::Matrix4D & transform, const Base::Vector3d & point, double rotation, const Base::Vector3d & scale)
Definition at line 459 of file ImpExpDxf.cpp.
References ApplyGuiStyles(), Part::TopoShape::convert(), CDxfRead::ImportError(), AssemblyImport::insert(), CDxfRead::m_entityAttributes, Base::Matrix4D::move(), CDxfRead::CommonEntityAttributes::ResolveByBlockAttributes(), Base::Matrix4D::rotZ(), Base::Matrix4D::scale(), and DrawingExample::Shape.
getDraftModule()
PyObject* Import::ImpExpDxfRead::getDraftModule () inline protected
Definition at line 122 of file ImpExpDxf.h.
Referenced by MakeLayer(), OnReadDimension(), and OnReadText().
getOptionSource()
std::string Import::ImpExpDxfRead::getOptionSource () inline
Definition at line 100 of file ImpExpDxf.h.
Referenced by setOptions().
MakeLayer()
CDxfRead::Layer * ImpExpDxfRead::MakeLayer (const std::string & name, ColorIndex_t color, std::string && lineType) override protected virtual
Reimplemented from CDxfRead.
Definition at line 643 of file ImpExpDxf.cpp.
References App::Color::b, App::Color::g, getDraftModule(), CDxfRead::m_preserveLayers, CDxfRead::MakeLayer(), Path.Post.scripts.opensbp_post::move(), CDxfRead::ObjectColor(), App::Color::r, and result.
OnReadArc()
void ImpExpDxfRead::OnReadArc (const Base::Vector3d & start, const Base::Vector3d & end, const Base::Vector3d & center, bool dir, bool hidden) override virtual
Reimplemented from CDxfRead.
Definition at line 226 of file ImpExpDxf.cpp.
References exportCSG::center(), Base::Console(), and Base::ConsoleSingleton::Warning().
OnReadBlock()
bool ImpExpDxfRead::OnReadBlock (const std::string & name, int flags) override virtual
Reimplemented from CDxfRead.
Definition at line 179 of file ImpExpDxf.cpp.
References CDxfRead::ImportError(), CDxfRead::m_importHiddenBlocks, CDxfRead::ReadBlockContents(), CDxfRead::SkipBlockContents(), and CDxfRead::UnsupportedFeature().
OnReadCircle()
void ImpExpDxfRead::OnReadCircle (const Base::Vector3d & start, const Base::Vector3d & center, bool dir, bool hidden) override virtual
Reimplemented from CDxfRead.
Definition at line 249 of file ImpExpDxf.cpp.
References exportCSG::center(), Base::Console(), and Base::ConsoleSingleton::Warning().
OnReadDimension()
void ImpExpDxfRead::OnReadDimension (const Base::Vector3d & start, const Base::Vector3d & end, const Base::Vector3d & point, double rotation) override virtual
Reimplemented from CDxfRead.
Definition at line 532 of file ImpExpDxf.cpp.
References getDraftModule(), CDxfRead::m_importAnnotations, draftmake.make_dimension::makeDimension(), and updateLeaderLines::point.
OnReadEllipse()
void ImpExpDxfRead::OnReadEllipse (const Base::Vector3d & center, double major_radius, double minor_radius, double rotation, double start_angle, double end_angle, bool dir) override virtual
Reimplemented from CDxfRead.
Definition at line 387 of file ImpExpDxf.cpp.
References exportCSG::center(), Base::Console(), and Base::ConsoleSingleton::Warning().
OnReadInsert()
void ImpExpDxfRead::OnReadInsert (const Base::Vector3d & point, const Base::Vector3d & scale, const std::string & name, double rotation) override virtual
Reimplemented from CDxfRead.
Definition at line 452 of file ImpExpDxf.cpp.
OnReadLine()
void ImpExpDxfRead::OnReadLine (const Base::Vector3d & start, const Base::Vector3d & end, bool hidden) override virtual
Reimplemented from CDxfRead.
Definition at line 206 of file ImpExpDxf.cpp.
OnReadPoint()
void ImpExpDxfRead::OnReadPoint (const Base::Vector3d & start) override virtual
Reimplemented from CDxfRead.
Definition at line 220 of file ImpExpDxf.cpp.
OnReadPolyline()
void ImpExpDxfRead::OnReadPolyline (std::list< VertexInfo > & vertices, int flags) override virtual
Reimplemented from CDxfRead.
Definition at line 577 of file ImpExpDxf.cpp.
References CDxfRead::ExplodePolyline().
OnReadSpline()
void ImpExpDxfRead::OnReadSpline (struct SplineData & sd) override virtual
Reimplemented from CDxfRead.
Definition at line 360 of file ImpExpDxf.cpp.
References Base::Console(), SplineData::control_points, SplineData::fit_points, Handle(), and Base::ConsoleSingleton::Warning().
OnReadText()
void ImpExpDxfRead::OnReadText (const Base::Vector3d & point, double height, const std::string & text, double rotation) override virtual
Reimplemented from CDxfRead.
Definition at line 412 of file ImpExpDxf.cpp.
References getDraftModule(), CDxfRead::m_importAnnotations, draftmake.make_text::makeText(), Base::Matrix4D::move(), updateLeaderLines::point, and Base::Matrix4D::rotZ().
operator=() [1/2]
void Import::ImpExpDxfRead::operator= (const ImpExpDxfRead &) delete
operator=() [2/2]
void Import::ImpExpDxfRead::operator= (ImpExpDxfRead &&) delete
ReadEntitiesSection()
bool ImpExpDxfRead::ReadEntitiesSection () override virtual
Reimplemented from CDxfRead.
Definition at line 90 of file ImpExpDxf.cpp.
References CDxfRead::Layers, CDxfRead::m_entityAttributes, CDxfRead::CommonEntityAttributes::m_Layer, CDxfRead::m_mergeOption, CDxfRead::m_preserveLayers, CDxfRead::Layer::Name, and CDxfRead::ReadEntitiesSection().
setOptions()
void ImpExpDxfRead::setOptions ()
Definition at line 140 of file ImpExpDxf.cpp.
References App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetFloat(), getOptionSource(), App::Application::GetParameterGroupByPath(), CDxfRead::m_importAnnotations, CDxfRead::m_importHiddenBlocks, CDxfRead::m_importPaperSpaceEntities, CDxfRead::m_importPoints, CDxfRead::m_mergeOption, CDxfRead::m_preserveColors, CDxfRead::m_preserveLayers, and CDxfRead::SetAdditionalScaling().
Referenced by ImpExpDxfRead().
setOptionSource()
void Import::ImpExpDxfRead::setOptionSource (const std::string & sourceName) inline
Definition at line 104 of file ImpExpDxf.h.
Referenced by ImpExpDxfRead().
The documentation for this class was generated from the following files:
ImpExpDxf.h
ImpExpDxf.cpp