FreeCAD: Part::ShapeHasher Struct Reference
Part::ShapeHasher Struct Reference
Shape hasher that ignore orientation.
#include <TopoShapeMapper.h>
Public Member Functions
size_t operator() (const TopoShape &s) const
size_t operator() (const TopoDS_Shape &s) const
bool operator() (const TopoShape &a, const TopoShape &b) const
bool operator() (const TopoDS_Shape &a, const TopoDS_Shape &b) const
size_t operator() (const std::pair< TopoShape, TopoShape > &s) const
size_t operator() (const std::pair< TopoDS_Shape, TopoDS_Shape > &s) const
bool operator() (const std::pair< TopoShape, TopoShape > &a, const std::pair< TopoShape, TopoShape > &b) const
bool operator() (const std::pair< TopoDS_Shape, TopoDS_Shape > &a, const std::pair< TopoDS_Shape, TopoDS_Shape > &b) const
Static Public Member Functions
template<class T >
static void hash_combine (std::size_t &seed, const T &v)
Detailed Description
Shape hasher that ignore orientation.
Definition at line 42 of file TopoShapeMapper.h.
Member Function Documentation
hash_combine()
template<class T > static void Part::ShapeHasher::hash_combine (std::size_t & seed, const T & v) inline static
Definition at line 69 of file TopoShapeMapper.h.
References TestSpreadsheet::v.
Referenced by operator()().
operator()() [1/8]
bool Part::ShapeHasher::operator() (const std::pair< TopoDS_Shape, TopoDS_Shape > & a, const std::pair< TopoDS_Shape, TopoDS_Shape > & b) const inline
Definition at line 103 of file TopoShapeMapper.h.
References a, and SCL.SimpleDataTypes::b.
operator()() [2/8]
size_t Part::ShapeHasher::operator() (const std::pair< TopoDS_Shape, TopoDS_Shape > & s) const inline
Definition at line 86 of file TopoShapeMapper.h.
References hash_combine(), and toolbit-attributes::s.
operator()() [3/8]
bool Part::ShapeHasher::operator() (const std::pair< TopoShape, TopoShape > & a, const std::pair< TopoShape, TopoShape > & b) const inline
Definition at line 97 of file TopoShapeMapper.h.
References a, and SCL.SimpleDataTypes::b.
operator()() [4/8]
size_t Part::ShapeHasher::operator() (const std::pair< TopoShape, TopoShape > & s) const inline
Definition at line 75 of file TopoShapeMapper.h.
References hash_combine(), and toolbit-attributes::s.
operator()() [5/8]
bool Part::ShapeHasher::operator() (const TopoDS_Shape & a, const TopoDS_Shape & b) const inline
Definition at line 64 of file TopoShapeMapper.h.
References a, and SCL.SimpleDataTypes::b.
operator()() [6/8]
size_t Part::ShapeHasher::operator() (const TopoDS_Shape & s) const inline
Definition at line 52 of file TopoShapeMapper.h.
References toolbit-attributes::s.
operator()() [7/8]
bool Part::ShapeHasher::operator() (const TopoShape & a, const TopoShape & b) const inline
Definition at line 60 of file TopoShapeMapper.h.
References a, and SCL.SimpleDataTypes::b.
operator()() [8/8]
size_t Part::ShapeHasher::operator() (const TopoShape & s) const inline
Definition at line 44 of file TopoShapeMapper.h.
References toolbit-attributes::s.
The documentation for this struct was generated from the following file:
TopoShapeMapper.h