FreeCAD: Gui::SoFCDB Class Reference
Gui::SoFCDB Class Reference
#include <SoFCDB.h>
Static Public Member Functions
static SbBool isInitialized ()
static void init ()
static void finish ()
static SoNode * replaceSwitches (SoNode *node)
static const std::string & writeNodesToString (SoNode *root)
helper to apply a SoWriteAction to a node and write it to a string
static bool writeToVRML (SoNode *node, const char *filename, bool binary)
static void writeToVRML (SoNode *node, std::string &buffer)
static bool writeToX3D (SoNode *node, const char *filename, bool binary)
static bool writeToX3D (SoNode *node, bool exportViewpoints, std::string &buffer)
static bool writeToX3DOM (SoNode *node, std::string &buffer)
static bool writeToFile (SoNode *node, const char *filename, bool binary)
static SoGroup * getStorage ()
Detailed Description
The FreeCAD database class to initialize all our own Inventor nodes.
Author
Werner Mayer
Definition at line 41 of file SoFCDB.h.
Member Function Documentation
finish()
void Gui::SoFCDB::finish () static
Definition at line 216 of file SoFCDB.cpp.
References Gui::SoFCColorLegend::finish(), Gui::SoFCBackgroundGradient::finish(), Gui::SoFCColorGradient::finish(), Gui::SoFCHighlightAction::finish(), Gui::SoFCColorBarBase::finish(), Gui::SoFCSelection::finish(), Gui::SoFCSelectionAction::finish(), Gui::SoFCBoundingBox::finish(), Gui::SoFCEnableSelectionAction::finish(), Gui::SoFCEnableHighlightAction::finish(), Gui::SoFCPathAnnotation::finish(), Gui::SoFCSelectionColorAction::finish(), Gui::SoFCSeparator::finish(), Gui::SoFCColorBar::finish(), Gui::SoFCHighlightColorAction::finish(), Gui::SoFCSelectionRoot::finish(), Gui::SoFCDocumentAction::finish(), Gui::SoFCDocumentObjectAction::finish(), Gui::SoUpdateVBOAction::finish(), and storage.
Referenced by drafttaskpanels.task_polararray.TaskPanelPolarArray::accept(), drafttaskpanels.task_orthoarray.TaskPanelOrthoArray::accept(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::accept(), draftguitools.gui_split.Split::action(), draftguitools.gui_splines.BSpline::action(), draftguitools.gui_beziers.BezCurve::action(), draftguitools.gui_lines.Line::action(), draftguitools.gui_subelements.SubelementHighlight::action(), draftguitools.gui_polygons.Polygon::action(), draftguitools.gui_rotate.Rotate::action(), draftguitools.gui_fillets.Fillet::action(), draftguitools.gui_move.Move::action(), draftguitools.gui_mirror.Mirror::action(), draftguitools.gui_stretch.Stretch::action(), draftguitools.gui_arcs.Arc::action(), draftguitools.gui_texts.Text::action(), draftguitools.gui_scale.Scale::action(), draftguitools.gui_rectangles.Rectangle::action(), draftguitools.gui_offset.Offset::action(), draftguitools.gui_ellipses.Ellipse::action(), draftguitools.gui_labels.Label::action(), draftguitools.gui_trimex.Trimex::action(), draftguitools.gui_beziers.CubicBezCurve::action(), draftguitools.gui_dimensions.Dimension::action(), draftguitools.gui_styles.ApplyStyle::Activated(), draftguitools.gui_join.Join::Activated(), draftguitools.gui_draft2sketch.Draft2Sketch::Activated(), draftguitools.gui_downgrade.Downgrade::Activated(), draftguitools.gui_upgrade.Upgrade::Activated(), draftguitools.gui_shape2dview.Shape2DView::Activated(), draftguitools.gui_facebinders.Facebinder::Activated(), draftguitools.gui_subelements.SubelementHighlight::Activated(), draftguitools.gui_wire2spline.WireToBSpline::Activated(), draftguitools.gui_clone.Clone::Activated(), draftguitools.gui_dimensions.Dimension::Activated(), draftguitools.gui_edit.Edit::Activated(), draftguitools.gui_selectplane.Draft_SelectPlane::check_selection(), DraftGui.DraftToolBar::checkSpecialChars(), draftguitools.gui_points.Point::click(), draftguitools.gui_orthoarray.OrthoArray::completed(), draftguitools.gui_polararray.PolarArray::completed(), draftguitools.gui_circulararray.CircularArray::completed(), draftguitools.gui_labels.Label::create(), bimcommands.BimText.BIM_Text::createObject(), draftguitools.gui_rectangles.Rectangle::createObject(), draftguitools.gui_ellipses.Ellipse::createObject(), draftguitools.gui_texts.Text::createObject(), draftviewproviders.view_text.ViewProviderText::createObject(), draftguitools.gui_stretch.Stretch::doStretch(), draftguitools.gui_fillets.Fillet::draw_arc(), draftguitools.gui_arcs.Arc::drawArc(), draftguitools.gui_polygons.Polygon::drawPolygon(), DraftGui.DraftToolBar::editUi(), DraftGui.DraftToolBar::escape(), draftguitools.gui_move.Move::get_object_selection(), draftguitools.gui_rotate.Rotate::get_object_selection(), draftguitools.gui_scale.Scale::get_object_selection(), draftguitools.gui_arcs.Arc_3Points::getPoint(), draftguitools.gui_edit.Edit::keyPressed(), draftguitools.gui_dimensions.Dimension::numericInput(), draftguitools.gui_offset.Offset::numericRadius(), draftguitools.gui_rotate.Rotate::numericRadius(), draftguitools.gui_trimex.Trimex::numericRadius(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_align(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_auto(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_center(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_front(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_move(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_next(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_previous(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_side(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_top(), bimcommands.BimShape2DView.BIM_Shape2DView::proceed(), draftguitools.gui_join.Join::proceed(), draftguitools.gui_draft2sketch.Draft2Sketch::proceed(), draftguitools.gui_subelements.SubelementHighlight::proceed(), bimcommands.BimSlab.BIM_Slab::proceed(), draftguitools.gui_upgrade.Upgrade::proceed(), draftguitools.gui_downgrade.Downgrade::proceed(), draftguitools.gui_pathtwistedarray.PathTwistedArray::proceed(), draftguitools.gui_facebinders.Facebinder::proceed(), draftguitools.gui_shape2dview.Shape2DView::proceed(), draftguitools.gui_clone.Clone::proceed(), draftguitools.gui_split.Split::proceed(), draftguitools.gui_pointarray.PointArray::proceed(), draftguitools.gui_patharray.PathArray::proceed(), draftguitools.gui_trimex.Trimex::proceed(), draftguitools.gui_edit.Edit::proceed(), draftguitools.gui_selectplane.Draft_SelectPlane::reject(), drafttaskpanels.task_orthoarray.TaskPanelOrthoArray::reject(), drafttaskpanels.task_polararray.TaskPanelPolarArray::reject(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::reject(), and draftguitools.gui_edit.Edit::setTrackers().
getStorage()
SoGroup * Gui::SoFCDB::getStorage () static
container for app lifetime storage. See SoFCCSysDragger for details on why this is needed.
Definition at line 710 of file SoFCDB.cpp.
References storage.
init()
void Gui::SoFCDB::init () static
Definition at line 95 of file SoFCDB.cpp.
References SIM::Coin3D::Quarter::Quarter::init(), Base::BaseClass::init(), init_done, SoDevicePixelRatioElement::initClass(), Gui::SoFCColorLegend::initClass(), SmSwitchboard::initClass(), Gui::SoFCBackgroundGradient::initClass(), Gui::SoFCColorGradient::initClass(), Gui::SoShapeScale::initClass(), Gui::SoFCHighlightAction::initClass(), Gui::ArcEngine::initClass(), SoMouseWheelEvent::initClass(), Gui::SoFCColorBarBase::initClass(), Gui::SoFCUnifiedSelection::initClass(), Gui::SoFCSelection::initClass(), Gui::SoFCTransform::initClass(), Gui::SoFCSelectionAction::initClass(), Gui::SoAutoZoomTranslation::initClass(), Gui::SoFCVectorizeU3DAction::initClass(), Gui::SoFCVectorizeSVGAction::initClass(), Gui::SoAxisCrossKit::initClass(), Gui::SoFCInteractiveElement::initClass(), Gui::SoGLWidgetElement::initClass(), Gui::So3DAnnotation::initClass(), Gui::SoTextLabel::initClass(), Gui::SoColorBarLabel::initClass(), Gui::SoFCBoundingBox::initClass(), Gui::Inventor::SoDrawingGrid::initClass(), Gui::SoRegPoint::initClass(), Gui::Inventor::MarkerBitmaps::initClass(), Gui::SoDatumLabel::initClass(), Gui::SoFCEnableSelectionAction::initClass(), Gui::SoSkipBoundingGroup::initClass(), Gui::SoStringLabel::initClass(), Gui::SoGLRenderActionElement::initClass(), Gui::SoFrameLabel::initClass(), Gui::SoFCEnableHighlightAction::initClass(), Gui::SoFCPathAnnotation::initClass(), Gui::SoGLWidgetNode::initClass(), Gui::SoGLVBOActivatedElement::initClass(), Gui::SoFCSelectionColorAction::initClass(), Gui::TranslateManip::initClass(), Gui::SoFCSeparator::initClass(), Gui::SoFCColorBar::initClass(), Gui::SoFCHighlightColorAction::initClass(), Gui::SoFCSelectionRoot::initClass(), Gui::SoFCDocumentAction::initClass(), Gui::SoFCDocumentObjectAction::initClass(), Gui::SoGLSelectAction::initClass(), Gui::SoFCCSysDragger::initClass(), Gui::SoVisibleFaceAction::initClass(), Gui::SoBoxSelectionRenderAction::initClass(), Gui::SoUpdateVBOAction::initClass(), Gui::SoHighlightElementAction::initClass(), Gui::SoSelectionElementAction::initClass(), Gui::SoVRMLAction::initClass(), and storage.
Referenced by Gui::Application::initOpenInventor(), and DocumentObject.DocumentObject::onChanged().
isInitialized()
SbBool Gui::SoFCDB::isInitialized () static
Definition at line 90 of file SoFCDB.cpp.
References init_done.
replaceSwitches()
SoNode * Gui::SoFCDB::replaceSwitches (SoNode * node) static
Definition at line 325 of file SoFCDB.cpp.
References replaceSwitchesInSceneGraph().
writeNodesToString()
const std::string & Gui::SoFCDB::writeNodesToString (SoNode * root) static
helper to apply a SoWriteAction to a node and write it to a string
Definition at line 258 of file SoFCDB.cpp.
Referenced by Gui::View3DInventorPy::dumpNode(), MeshGui::ViewProviderMesh::exportToVrml(), Gui::FreeCADGui_exportSubgraph(), Gui::View3DInventor::onMsg(), Gui::ViewProvider::toString(), writeToFile(), writeToVRML(), and Gui::View3DInventor::~View3DInventor().
writeToFile()
bool Gui::SoFCDB::writeToFile (SoNode * node, const char * filename, bool binary) static
Definition at line 663 of file SoFCDB.cpp.
References Base::FileInfo::hasExtension(), Path.Post.scripts.refactored_centroid_post::str, writeNodesToString(), writeToVRML(), writeToX3D(), and writeToX3DOM().
Referenced by Gui::View3DInventorViewer::dumpToFile(), and Gui::ApplicationPy::sExport().
writeToVRML() [1/2]
bool Gui::SoFCDB::writeToVRML (SoNode * node, const char * filename, bool binary) static
Definition at line 352 of file SoFCDB.cpp.
References Path.Post.scripts.refactored_centroid_post::str.
Referenced by Gui::FreeCADGui_exportSubgraph(), and writeToFile().
writeToVRML() [2/2]
void Gui::SoFCDB::writeToVRML (SoNode * node, std::string & buffer) static
Definition at line 330 of file SoFCDB.cpp.
References replaceSwitchesInSceneGraph(), Gui::SoVRMLAction::setOverrideMode(), and writeNodesToString().
writeToX3D() [1/2]
bool Gui::SoFCDB::writeToX3D (SoNode * node, bool exportViewpoints, std::string & buffer) static
Definition at line 416 of file SoFCDB.cpp.
References SplineSurface::i, replaceSwitchesInSceneGraph(), and Gui::SoVRMLAction::setOverrideMode().
writeToX3D() [2/2]
bool Gui::SoFCDB::writeToX3D (SoNode * node, const char * filename, bool binary) static
Definition at line 387 of file SoFCDB.cpp.
References Path.Post.scripts.refactored_centroid_post::str.
Referenced by writeToFile().
writeToX3DOM()
bool Gui::SoFCDB::writeToX3DOM (SoNode * node, std::string & buffer) static
Definition at line 621 of file SoFCDB.cpp.
References RobotExample::pos.
Referenced by writeToFile().
The documentation for this class was generated from the following files:
SoFCDB.h
SoFCDB.cpp