FreeCAD: ArchCommands Namespace Reference
ArchCommands Namespace Reference
Arch
Utility functions for the Arch Workbench.
Classes
class _SurveyObserver
class SurveyTaskPanel
Functions
def getStringList (objects)
def getDefaultColor (objectType)
def addComponents (objectsList, host)
def removeComponents (objectsList, host=None)
def makeComponent (baseobj=None, name=None, delete=False)
def cloneComponent (obj)
def setAsSubcomponent (obj)
def copyProperties (obj1, obj2)
def splitMesh (obj, mark=True)
def makeFace (wires, method=2, cleanup=False)
def closeHole (shape)
def getCutVolume (cutplane, shapes, clip=False, depth=None)
def getShapeFromMesh (mesh, fast=True, tolerance=0.001, flat=False, cut=True)
def projectToVector (shape, vector)
def meshToShape (obj, mark=True, fast=True, tol=0.001, flat=False, cut=True)
def removeCurves (shape, dae=False, tolerance=5)
def removeShape (objs, mark=True)
def mergeCells (objectslist)
def download (url, force=False)
def check (objectslist, includehidden=False)
def getHost (obj, strict=True)
def pruneIncluded (objectslist, strict=False, silent=False)
def getAllChildren (objectlist)
def survey (callback=False)
def toggleIfcBrepFlag (obj)
def makeCompoundFromSelected (objects=None)
def cleanArchSplitter (objects=None)
def rebuildArchShape (objects=None)
def getExtrusionData (shape, sortmethod="area")
def printMessage (message)
def printWarning (message)
def makeIfcSpreadsheet (archobj=None)
Detailed Description
Utility functions for the Arch Workbench.
This module provides general functions used by Arch tools and utility commands
Function Documentation
addComponents()
def ArchCommands.addComponents (objectsList, host)
addComponents(objectsList,hostObject): adds the given object or the objects
from the given list as components to the given host Object. Use this for
example to add windows to a wall, or to add walls to a cell or floor.
Definition at line 90 of file ArchCommands.py.
Referenced by importers.importIFClegacy.read().
check()
def ArchCommands.check (objectslist, includehidden = False)
check(objectslist,includehidden=False): checks if the given objects contain only solids
Definition at line 704 of file ArchCommands.py.
Referenced by Attacher::AttachEngine3D._calculateAttachedPlacement(), DrawingGui::TaskDlgOrthoViews.accept(), Base::ProgressIndicatorPy.check(), Base::Vector2dPy.check(), TechDrawGui::TaskSectionView.checkAll(), TechDrawGui::TaskComplexSection.checkAll(), Gui::Action.command(), Mesh::MeshObject.cut(), Inspection::Feature.execute(), WireJoiner::WireJoinerP.exhaustTightBoundUpdateWire(), WireJoiner::WireJoinerP.exhaustTightBoundWithAdjacent(), FC_LOG_LEVEL_INIT(), Part::TopoShape.findPlane(), StdOrthographicCamera.isActive(), StdPerspectiveCamera.isActive(), NaviCubeDraggableCmd.isActive(), Part::TopoShape.isPlanar(), Part::GeomSurface.isPlanar(), Part::TopoShape.makeShell(), Gui::ActionGroup.onToggled(), TechDrawGui::PathBuilder.pathArc(), ModelRefine::FaceUniter.process(), App.pyObjectToAny(), App::Metadata.removeContentItem(), App::Metadata.removeDepend(), Gui::Action.setCheckable(), Gui::Action.setChecked(), Gui::ActionGroup.setDisabled(), Data::ElementMap.setElementName(), Gui::ActionGroup.setEnabled(), Gui::UndoAction.setEnabled(), Gui::RedoAction.setEnabled(), Gui::ActionGroup.setExclusive(), Gui::ActionGroup.setVisible(), Gui::UndoAction.setVisible(), Gui::RedoAction.setVisible(), TechDrawGui::TaskCenterLine.TaskCenterLine(), CAMTests.TestPathHelix.TestPathHelix.testPathDirection(), CAMTests.TestPathHelix.TestPathHelix.testRecomputeHelixFromV021(), Gui::PythonWrapper.toCString(), and Mesh::MeshObject.trim().
cleanArchSplitter()
def ArchCommands.cleanArchSplitter (objects = None)
cleanArchSplitter([objects]): removes the splitters from the base shapes
of the given Arch objects or selected Arch objects if objects is None
Definition at line 1197 of file ArchCommands.py.
cloneComponent()
def ArchCommands.cloneComponent (obj)
cloneComponent(obj): Creates a clone of an object as an undefined component
Definition at line 258 of file ArchCommands.py.
References makeComponent().
closeHole()
def ArchCommands.closeHole (shape)
closeHole(shape): closes a hole in an open shape
Definition at line 380 of file ArchCommands.py.
copyProperties()
def ArchCommands.copyProperties (obj1, obj2)
copyProperties(obj1,obj2): Copies properties values from obj1 to obj2,
when that property exists in both objects
Definition at line 290 of file ArchCommands.py.
download()
def ArchCommands.download (url, force = False)
download(url,force=False): downloads a file from the given URL and saves it in the
macro path. Returns the path to the saved file. If force is True, the file will be
downloaded again evn if it already exists.
Definition at line 678 of file ArchCommands.py.
References AssemblyImport.open().
Referenced by Gui::Dialog::DownloadManager.download(), importDXF.errorDXFLib(), and importers.importIFClegacy.getSchema().
getAllChildren()
def ArchCommands.getAllChildren (objectlist)
Definition at line 799 of file ArchCommands.py.
getCutVolume()
def ArchCommands.getCutVolume (cutplane, shapes, clip = False, depth = None)
getCutVolume(cutplane,shapes,[clip,depth]): returns a cut face and a cut volume
from the given shapes and the given cutting plane. If clip is True, the cutvolume will
also cut off everything outside the cutplane projection. If depth is non-zero, geometry
further than this distance will be clipped off
Definition at line 408 of file ArchCommands.py.
References KDL.max(), DraftVecUtils.project(), and DraftVecUtils.scaleTo().
Referenced by ArchVRM.Renderer.cut(), ArchCutPlane.cutComponentwithPlane(), ArchPipe._ArchPipeConnector.execute(), ArchSectionPlane.getCutShapes(), ArchSpace._Space.getFootprint(), and ArchSpace._Space.getShape().
getDefaultColor()
def ArchCommands.getDefaultColor (objectType)
getDefaultColor(string): returns a color value for the given object
type (Wall, Structure, Window, WindowGlass)
Definition at line 63 of file ArchCommands.py.
Referenced by ArchRebar._ViewProviderRebar.__init__(), ArchBuildingPart.ViewProviderBuildingPart.__init__(), ArchSpace._ViewProviderSpace.__init__(), ArchPanel._ViewProviderPanel.__init__(), ArchPrecast._ViewProviderPrecast.__init__(), ArchStructure._ViewProviderStructure.__init__(), ArchWall._ViewProviderWall.__init__(), ArchCurtainWall.ViewProviderCurtainWall.colorize(), ArchWindow._ViewProviderWindow.colorize(), setAsSubcomponent(), ArchAxis._ViewProviderAxis.setProperties(), and ArchSectionPlane._ViewProviderSectionPlane.setProperties().
getExtrusionData()
def ArchCommands.getExtrusionData (shape, sortmethod = "area")
If a shape has been extruded, returns the base face, and extrusion vector.
Determines if a shape appears to have been extruded from some base face, and
extruded at the normal from that base face. IE: it looks like a cuboid.
https://en.wikipedia.org/wiki/Cuboid#Rectangular_cuboid
If this is the case, returns what appears to be the base face, and the vector
used to make that extrusion.
The base face is determined based on the sortmethod parameter, which can either
be:
"area" = Of the faces with the smallest area, the one with the lowest z coordinate.
"z" = The face with the lowest z coordinate.
a 3D vector = the face which center is closest to the given 3D point
Parameters
----------
shape: <Part.Shape>
    Shape to examine.
sortmethod: {"area", "z"}
    Which sorting algorithm to use to determine the base face.
Returns
-------
Extrusion data: list
    Two item list containing the base face, and the vector used to create the
    extrusion. In that order.
Failure: None
    Returns None if the object does not appear to be an extrusion.
Definition at line 1262 of file ArchCommands.py.
References Path.Dressup.Gui.Dogbone.getAngle().
Referenced by ArchComponent.Component.getExtrusionData().
getHost()
def ArchCommands.getHost (obj, strict = True)
getHost(obj,[strict]): returns the host of the current object. If strict is true (default),
the host can only be an object of a higher level than the given one, or in other words, if a wall
is contained in another wall which is part of a floor, the floor is returned instead of the parent wall
Definition at line 731 of file ArchCommands.py.
getShapeFromMesh()
def ArchCommands.getShapeFromMesh (mesh, fast = True, tolerance = 0.001, flat = False, cut = True)
Definition at line 489 of file ArchCommands.py.
References makeFace().
Referenced by ArchPanel._Panel.execute(), ArchWall._Wall.execute(), ArchStructure._Structure.execute(), meshToShape(), and removeCurves().
getStringList()
def ArchCommands.getStringList (objects)
getStringList(objects): returns a string defining a list
of objects
Definition at line 52 of file ArchCommands.py.
Referenced by ArchStructure.CommandStructuralSystem.Activated().
makeComponent()
def ArchCommands.makeComponent (baseobj = None, name = None, delete = False)
makeComponent([baseobj],[name],[delete]): creates an undefined, non-parametric BIM
component from the given base object
Definition at line 231 of file ArchCommands.py.
Referenced by cloneComponent().
makeCompoundFromSelected()
def ArchCommands.makeCompoundFromSelected (objects = None)
makeCompoundFromSelected([objects]): Creates a new compound object from the given
subobjects (faces, edges) or from the selection if objects is None
Definition at line 1180 of file ArchCommands.py.
makeFace()
def ArchCommands.makeFace (wires, method = 2, cleanup = False)
makeFace(wires): makes a face from a list of wires, finding which ones are holes
Definition at line 323 of file ArchCommands.py.
Referenced by ArchPanel._Panel.execute(), getShapeFromMesh(), and ArchVRM.Renderer.projectFace().
makeIfcSpreadsheet()
def ArchCommands.makeIfcSpreadsheet (archobj = None)
Definition at line 1354 of file ArchCommands.py.
mergeCells()
def ArchCommands.mergeCells (objectslist)
mergeCells(objectslist): merges the objects in the given list
into one. All objects must be of the same type and based on the Cell
object (cells, floors, buildings, or sites).
Definition at line 651 of file ArchCommands.py.
meshToShape()
def ArchCommands.meshToShape (obj, mark = True, fast = True, tol = 0.001, flat = False, cut = True)
meshToShape(object,[mark,fast,tol,flat,cut]): turns a mesh into a shape, joining coplanar facets. If
mark is True (default), non-solid objects will be marked in red. Fast uses a faster algorithm by
building a shell from the facets then removing splitter, tol is the tolerance used when converting
mesh segments to wires, flat will force the wires to be perfectly planar, to be sure they can be
turned into faces, but this might leave gaps in the final shell. If cut is true, holes in faces are
made by subtraction (default)
Definition at line 580 of file ArchCommands.py.
References getShapeFromMesh().
printMessage()
def ArchCommands.printMessage (message)
Definition at line 1344 of file ArchCommands.py.
Referenced by ArchFloor._CommandFloor.Activated(), and ArchBuilding._CommandBuilding.Activated().
printWarning()
def ArchCommands.printWarning (message)
Definition at line 1349 of file ArchCommands.py.
projectToVector()
def ArchCommands.projectToVector (shape, vector)
projectToVector(shape,vector): projects the given shape on the given
vector
Definition at line 562 of file ArchCommands.py.
References DraftVecUtils.project(), and DraftVecUtils.scaleTo().
Referenced by ArchRebar._Rebar.execute(), and ArchRebar._Rebar.getRebarData().
pruneIncluded()
def ArchCommands.pruneIncluded (objectslist, strict = False, silent = False)
pruneIncluded(objectslist,[strict]): removes from a list of Arch objects, those that are subcomponents of
another shape-based object, leaving only the top-level shapes. If strict is True, the object
is removed only if the parent is also part of the selection.
Definition at line 748 of file ArchCommands.py.
rebuildArchShape()
def ArchCommands.rebuildArchShape (objects = None)
rebuildArchShape([objects]): takes the faces from the base shape of the given (or selected
if objects is None) Arch objects, and tries to rebuild a valid solid from them.
Definition at line 1218 of file ArchCommands.py.
removeComponents()
def ArchCommands.removeComponents (objectsList, host = None)
removeComponents(objectsList,[hostObject]): removes the given component or
the components from the given list from their parents. If a host object is
specified, this function will try adding the components as holes to the host
object instead.
Definition at line 136 of file ArchCommands.py.
References Path.Op.Surface.msg, and setAsSubcomponent().
Referenced by ArchCutPlane.cutComponentwithPlane(), and importers.importIFClegacy.read().
removeCurves()
def ArchCommands.removeCurves (shape, dae = False, tolerance = 5)
removeCurves(shape,dae,tolerance=5): replaces curved faces in a shape
with faceted segments. If dae is True, DAE triangulation options are used
Definition at line 605 of file ArchCommands.py.
References getShapeFromMesh().
removeShape()
def ArchCommands.removeShape (objs, mark = True)
removeShape(objs,mark=True): takes an arch object (wall or structure) built on a cubic shape, and removes
the inner shape, keeping its length, width and height as parameters. If mark is True, objects that cannot
be processed by this function will become red.
Definition at line 617 of file ArchCommands.py.
References ArchStructure.makeStructure().
setAsSubcomponent()
def ArchCommands.setAsSubcomponent (obj)
Sets the given object properly to become a subcomponent (addition, subtraction)
of an Arch component
Definition at line 273 of file ArchCommands.py.
References getDefaultColor().
Referenced by removeComponents(), and ArchComponent.removeFromComponent().
splitMesh()
def ArchCommands.splitMesh (obj, mark = True)
splitMesh(object,[mark]): splits the given mesh object into separated components.
If mark is False, nothing else is done. If True (default), non-manifold components
will be painted in red.
Definition at line 303 of file ArchCommands.py.
survey()
def ArchCommands.survey (callback = False)
survey(): starts survey mode, where you can click edges and faces to get their lengths or area.
Clicking on no object (on an empty area) resets the count.
Definition at line 813 of file ArchCommands.py.
References Path.Post.scripts.refactored_centroid_post.str.
toggleIfcBrepFlag()
def ArchCommands.toggleIfcBrepFlag (obj)
toggleIfcBrepFlag(obj): toggles the IFC brep flag of the given object, forcing it
to be exported as brep geometry or not.
Definition at line 1160 of file ArchCommands.py.