FreeCAD: Gui::Dialog::ParameterFloat Class Reference
Gui::Dialog::ParameterFloat Class Reference
#include <DlgParameterImp.h>
Public Member Functions
ParameterFloat (QTreeWidget *parent, QString label1, double value, const Base::Reference< ParameterGrp > &hcGrp)
Constructor.
~ParameterFloat () override
void changeValue () override
void appendToGroup () override
void removeFromGroup () override
Public Member Functions inherited from Gui::Dialog::ParameterValueItem
ParameterValueItem (QTreeWidget *parent, const Base::Reference< ParameterGrp > &hcGrp)
Constructor.
~ParameterValueItem () override
void setData (int column, int role, const QVariant &value) override
Protected Member Functions
void replace (const QString &oldName, const QString &newName) override
Additional Inherited Members
Protected Attributes inherited from Gui::Dialog::ParameterValueItem
Base::Reference< ParameterGrp > _hcGrp
Detailed Description
The ParameterFloat class allows interaction with "float" parameter leaves.
Author
Werner Mayer
Definition at line 362 of file DlgParameterImp.h.
Constructor & Destructor Documentation
ParameterFloat()
ParameterFloat::ParameterFloat (QTreeWidget * parent, QString label1, double value, const Base::Reference< ParameterGrp > & hcGrp)
Constructor.
Definition at line 1288 of file DlgParameterImp.cpp.
References Gui::BitmapFactory().
~ParameterFloat()
ParameterFloat::~ParameterFloat () override default
Member Function Documentation
appendToGroup()
void ParameterFloat::appendToGroup () override virtual
Append this item as leaf to the parameter group.
Implements Gui::Dialog::ParameterValueItem.
Definition at line 1332 of file DlgParameterImp.cpp.
References Gui::Dialog::ParameterValueItem::_hcGrp, and ParameterGrp::SetFloat().
changeValue()
void ParameterFloat::changeValue () override virtual
Opens an input dialog to change the value.
Implements Gui::Dialog::ParameterValueItem.
Definition at line 1302 of file DlgParameterImp.cpp.
References Gui::Dialog::ParameterValueItem::_hcGrp, and ParameterGrp::SetFloat().
removeFromGroup()
void ParameterFloat::removeFromGroup () override virtual
Remove the leaf from the parameter group.
Implements Gui::Dialog::ParameterValueItem.
Definition at line 1320 of file DlgParameterImp.cpp.
References Gui::Dialog::ParameterValueItem::_hcGrp, and ParameterGrp::RemoveFloat().
replace()
void ParameterFloat::replace (const QString & oldName, const QString & newName) override protected virtual
Replaces the name of the leaf from oldName to newName.
Implements Gui::Dialog::ParameterValueItem.
Definition at line 1325 of file DlgParameterImp.cpp.
References Gui::Dialog::ParameterValueItem::_hcGrp, ParameterGrp::GetFloat(), ParameterGrp::RemoveFloat(), ParameterGrp::SetFloat(), and toolbit-attributes::val.
The documentation for this class was generated from the following files:
DlgParameterImp.h
DlgParameterImp.cpp