FreeCAD: automotive_design.gear_pair Class Reference
automotive_design.gear_pair Class Reference
Public Member Functions
def __init__ (self, inherited0__name, inherited1__description, inherited2__transform_item_1, inherited3__transform_item_2, inherited4__joint, radius_first_link, radius_second_link, bevel, helical_angle, gear_ratio)
def radius_first_link ()
def radius_second_link ()
def bevel ()
def helical_angle ()
def gear_ratio ()
Public Member Functions inherited from automotive_design.kinematic_pair
def __init__ (self, inherited0__name, inherited1__description, inherited2__transform_item_1, inherited3__transform_item_2, joint)
def joint ()
def pair_placement_in_first_link_context ()
def pair_placement_in_second_link_context ()
def wr1 (self)
def wr2 (self)
Public Member Functions inherited from automotive_design.item_defined_transformation
def __init__ (self, name, description, transform_item_1, transform_item_2)
def name ()
def description ()
def transform_item_1 ()
def transform_item_2 ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
radius_first_link
radius_second_link
bevel
helical_angle
gear_ratio
Public Attributes inherited from automotive_design.kinematic_pair
joint
Public Attributes inherited from automotive_design.item_defined_transformation
name
description
transform_item_1
transform_item_2
Detailed Description
Entity gear_pair definition.
:param radius_first_link
:type radius_first_link:length_measure
:param radius_second_link
:type radius_second_link:length_measure
:param bevel
:type bevel:plane_angle_measure
:param helical_angle
:type helical_angle:plane_angle_measure
:param gear_ratio
:type gear_ratio:REAL
Definition at line 5836 of file automotive_design.py.
Constructor & Destructor Documentation
__init__()
def automotive_design.gear_pair.__init__ (self, inherited0__name, inherited1__description, inherited2__transform_item_1, inherited3__transform_item_2, inherited4__joint, radius_first_link, radius_second_link, bevel, helical_angle, gear_ratio)
Definition at line 5854 of file automotive_design.py.
Member Function Documentation
bevel()
def automotive_design.gear_pair.bevel ()
Definition at line 5891 of file automotive_design.py.
References automotive_design.gear_pair._bevel, automotive_design.gear_pair.bevel, and SCL.TypeChecker.check_type().
gear_ratio()
def automotive_design.gear_pair.gear_ratio ()
Definition at line 5919 of file automotive_design.py.
References automotive_design.gear_pair._gear_ratio, SCL.TypeChecker.check_type(), and automotive_design.gear_pair.gear_ratio.
helical_angle()
def automotive_design.gear_pair.helical_angle ()
Definition at line 5905 of file automotive_design.py.
References automotive_design.gear_pair._helical_angle, SCL.TypeChecker.check_type(), and automotive_design.gear_pair.helical_angle.
radius_first_link()
def automotive_design.gear_pair.radius_first_link ()
Definition at line 5863 of file automotive_design.py.
References automotive_design.gear_pair._radius_first_link, SCL.TypeChecker.check_type(), and automotive_design.gear_pair.radius_first_link.
radius_second_link()
def automotive_design.gear_pair.radius_second_link ()
Definition at line 5877 of file automotive_design.py.
References automotive_design.gear_pair._radius_second_link, SCL.TypeChecker.check_type(), and automotive_design.gear_pair.radius_second_link.
Member Data Documentation
bevel
automotive_design.gear_pair.bevel
Definition at line 5858 of file automotive_design.py.
Referenced by automotive_design.gear_pair.bevel().
gear_ratio
automotive_design.gear_pair.gear_ratio
Definition at line 5860 of file automotive_design.py.
Referenced by automotive_design.gear_pair.gear_ratio().
helical_angle
automotive_design.gear_pair.helical_angle
Definition at line 5859 of file automotive_design.py.
Referenced by automotive_design.gear_pair.helical_angle().
radius_first_link
automotive_design.gear_pair.radius_first_link
Definition at line 5856 of file automotive_design.py.
Referenced by automotive_design.gear_pair.radius_first_link().
radius_second_link
automotive_design.gear_pair.radius_second_link
Definition at line 5857 of file automotive_design.py.
Referenced by automotive_design.gear_pair.radius_second_link().
The documentation for this class was generated from the following file:
automotive_design.py