FreeCAD: MeshFlatteningPy.cpp File Reference
MeshFlatteningPy.cpp File Reference
#include "PreCompiled.h"
#include <stdexcept>
#include <vector>
#include <TopoDS.hxx>
#include <TopoDS_Edge.hxx>
#include <TopoDS_Face.hxx>
#include <pybind11/eigen.h>
#include <pybind11/numpy.h>
#include <pybind11/operators.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <Mod/Part/App/TopoShapeFacePy.h>
#include <Mod/Part/App/TopoShapeEdgePy.h>
#include "MeshFlattening.h"
#include "MeshFlatteningLscmRelax.h"
#include "MeshFlatteningNurbs.h"
Functions
const TopoDS_Face & getTopoDSFace (py::object *face)
const TopoDS_Edge & getTopoDSEdge (py::object *edge)
Py::Object makeEdge (const TopoDS_Edge &edge)
py::object makeFace (const TopoDS_Face &face)
FaceUnwrapper * FaceUnwrapper_constructor (py::object *face)
ColMat< double, 3 > interpolateFlatFacePy (FaceUnwrapper &instance, py::object *face)
PYBIND11_MODULE (flatmesh, m)
Function Documentation
FaceUnwrapper_constructor()
FaceUnwrapper* FaceUnwrapper_constructor (py::object * face)
Definition at line 90 of file MeshFlatteningPy.cpp.
References getTopoDSFace().
Referenced by PYBIND11_MODULE().
getTopoDSEdge()
const TopoDS_Edge& getTopoDSEdge (py::object * edge)
Definition at line 67 of file MeshFlatteningPy.cpp.
References SCL.SimpleDataTypes::e.
getTopoDSFace()
const TopoDS_Face& getTopoDSFace (py::object * face)
Definition at line 55 of file MeshFlatteningPy.cpp.
References SCL.SimpleDataTypes::f.
Referenced by FaceUnwrapper_constructor(), and interpolateFlatFacePy().
interpolateFlatFacePy()
ColMat<double, 3> interpolateFlatFacePy (FaceUnwrapper & instance, py::object * face)
Definition at line 96 of file MeshFlatteningPy.cpp.
References getTopoDSFace(), and FaceUnwrapper::interpolateFlatFace().
Referenced by PYBIND11_MODULE().
makeEdge()
Py::Object makeEdge (const TopoDS_Edge & edge)
Definition at line 79 of file MeshFlatteningPy.cpp.
makeFace()
py::object makeFace (const TopoDS_Face & face)
Definition at line 84 of file MeshFlatteningPy.cpp.
References cast().
PYBIND11_MODULE()
PYBIND11_MODULE (flatmesh , m)
Definition at line 104 of file MeshFlatteningPy.cpp.
References FaceUnwrapper::A, nurbs::NurbsBase2D::computeFirstDerivatives(), nurbs::NurbsBase1D::computeFirstDerivatives(), Drawing::copy(), nurbs::NurbsBase2D::degree_u, nurbs::NurbsBase1D::degree_u, FaceUnwrapper_constructor(), FaceUnwrapper::findFlatNodes(), lscmrelax::LscmRelax::flat_vertices, lscmrelax::LscmRelax::get_area(), lscmrelax::LscmRelax::get_flat_area(), lscmrelax::LscmRelax::get_flat_vertices_3D(), nurbs::NurbsBase2D::getDuMatrix(), nurbs::NurbsBase1D::getDuMatrix(), nurbs::NurbsBase2D::getDuVector(), nurbs::NurbsBase1D::getDuVector(), nurbs::NurbsBase2D::getDvMatrix(), nurbs::NurbsBase2D::getDvVector(), FaceUnwrapper::getFlatBoundaryNodes(), nurbs::NurbsBase2D::getInfluenceMatrix(), nurbs::NurbsBase1D::getInfluenceMatrix(), nurbs::NurbsBase2D::getInfluenceVector(), nurbs::NurbsBase1D::getInfluenceVector(), nurbs::NurbsBase1D::getKnotSequence(), nurbs::NurbsBase1D::getUMesh(), nurbs::NurbsBase2D::getUVMesh(), nurbs::NurbsBase1D::getWeightList(), SIM::Coin3D::Quarter::Quarter::init(), interpolateFlatFacePy(), nurbs::NurbsBase2D::interpolateUBS(), lscmrelax::LscmRelax::lscm(), test::m, lscmrelax::LscmRelax::MATRIX, lscmrelax::LscmRelax::relax(), lscmrelax::LscmRelax::rhs, lscmrelax::LscmRelax::rotate_by_min_bound_area(), lscmrelax::LscmRelax::transform(), FaceUnwrapper::tris, nurbs::NurbsBase2D::u_knots, nurbs::NurbsBase1D::u_knots, FaceUnwrapper::uv_nodes, nurbs::NurbsBase2D::weights, nurbs::NurbsBase1D::weights, FaceUnwrapper::xyz_nodes, FaceUnwrapper::ze_nodes, and FaceUnwrapper::ze_poles.