FreeCAD: MeshCore::MeshEvalTopology Class Reference
MeshCore::MeshEvalTopology Class Reference
#include <Evaluation.h>
Public Member Functions
MeshEvalTopology (const MeshKernel &rclB)
bool Evaluate () override
void GetFacetManifolds (std::vector< FacetIndex > &raclFacetIndList) const
unsigned long CountManifolds () const
const std::vector< std::pair< FacetIndex, FacetIndex > > & GetIndices () const
const std::list< std::vector< FacetIndex > > & GetFacets () const
Public Member Functions inherited from MeshCore::MeshEvaluation
MeshEvaluation (const MeshKernel &rclB)
virtual ~MeshEvaluation ()=default
MeshEvaluation (const MeshEvaluation &)=delete
MeshEvaluation (MeshEvaluation &&)=delete
MeshEvaluation & operator= (const MeshEvaluation &)=delete
MeshEvaluation & operator= (MeshEvaluation &&)=delete
Protected Attributes
std::vector< std::pair< FacetIndex, FacetIndex > > nonManifoldList
std::list< std::vector< FacetIndex > > nonManifoldFacets
Protected Attributes inherited from MeshCore::MeshEvaluation
const MeshKernel & _rclMesh
Detailed Description
The MeshEvalTopology class checks for topologic correctness, i.e that the mesh must not contain non-manifolds. E.g. an edge is regarded as non-manifold if it is shared by more than two facets.
Note
This check does not necessarily cover any degenerations.
Definition at line 222 of file Evaluation.h.
Constructor & Destructor Documentation
MeshEvalTopology()
MeshCore::MeshEvalTopology::MeshEvalTopology (const MeshKernel & rclB) inline explicit
Definition at line 225 of file Evaluation.h.
Member Function Documentation
CountManifolds()
unsigned long MeshEvalTopology::CountManifolds () const
Definition at line 414 of file Evaluation.cpp.
References nonManifoldList.
Evaluate()
bool MeshEvalTopology::Evaluate () override virtual
Evaluates the mesh kernel with respect to certain criteria. Must be reimplemented by every subclass. This pure virtual function returns false if the mesh kernel is invalid according to this criterion and true if the mesh kernel is correct.
Implements MeshCore::MeshEvaluation.
Reimplemented in MeshCore::MeshEvalSingleFacet.
Definition at line 336 of file Evaluation.cpp.
References MeshCore::MeshEvaluation::_rclMesh, src.Mod.AddonManager.NetworkManager::count, MeshCore::MeshKernel::GetFacets(), SplineSurface::i, Base::SequencerLauncher::next(), nonManifoldFacets, nonManifoldList, MeshCore::Edge_Index::p0, and MeshCore::POINT_INDEX_MAX.
Referenced by MeshCore::MeshEvalSingleFacet::Evaluate(), MeshCore::MeshFixTopology::Fixup(), MeshCore::MeshKernel::HasNonManifolds(), Mesh::MeshObject::hasNonManifolds(), Mesh::MeshObject::load(), and Mesh::MeshObject::removeNonManifolds().
GetFacetManifolds()
void MeshEvalTopology::GetFacetManifolds (std::vector< FacetIndex > & raclFacetIndList) const
Definition at line 394 of file Evaluation.cpp.
References MeshCore::MeshEvaluation::_rclMesh, DraftVecUtils::find(), MeshCore::MeshKernel::GetFacets(), SplineSurface::i, and nonManifoldList.
Referenced by MeshCore::MeshFixTopology::Fixup().
GetFacets()
const std::list<std::vector<FacetIndex> >& MeshCore::MeshEvalTopology::GetFacets () const inline
Definition at line 236 of file Evaluation.h.
Referenced by Mesh::MeshObject::removeNonManifolds().
GetIndices()
const std::vector<std::pair<FacetIndex, FacetIndex> >& MeshCore::MeshEvalTopology::GetIndices () const inline
Definition at line 232 of file Evaluation.h.
Member Data Documentation
nonManifoldFacets
std::list<std::vector<FacetIndex> > MeshCore::MeshEvalTopology::nonManifoldFacets protected
Definition at line 244 of file Evaluation.h.
Referenced by Evaluate().
nonManifoldList
std::vector<std::pair<FacetIndex, FacetIndex> > MeshCore::MeshEvalTopology::nonManifoldList protected
Definition at line 243 of file Evaluation.h.
Referenced by CountManifolds(), Evaluate(), MeshCore::MeshEvalSingleFacet::Evaluate(), and GetFacetManifolds().
The documentation for this class was generated from the following files:
Evaluation.h
Evaluation.cpp