FreeCAD: Wm4::Mapper3< Real > Class Template Reference
Wm4::Mapper3< Real > Class Template Reference
#include <Wm4Mapper3.h>
Public Member Functions
Mapper3 (int iVQuantity, const Vector3< Real > *akVertex, Real fEpsilon)
~Mapper3 ()
const Vector3< Real > & GetMin () const
const Vector3< Real > & GetMax () const
Real GetMaxRange () const
int GetDimension () const
const Vector3< Real > & GetOrigin () const
const Vector3< Real > & GetDirection (int i) const
int GetExtremeIndex (int i) const
bool GetExtremeCCW () const
Detailed Description
template<class Real>
class Wm4::Mapper3< Real >
Definition at line 27 of file Wm4Mapper3.h.
Constructor & Destructor Documentation
Mapper3()
template<class Real > Wm4::Mapper3< Real >::Mapper3 (int iVQuantity, const Vector3< Real > * akVertex, Real fEpsilon)
~Mapper3()
template<class Real > Wm4::Mapper3< Real >::~Mapper3 ()
Member Function Documentation
GetDimension()
template<class Real > int Wm4::Mapper3< Real >::GetDimension () const
Referenced by Wm4::ConvexHull3< Real >::ConvexHull3(), and Wm4::Delaunay3< Real >::Delaunay3().
GetDirection()
template<class Real > const Vector3<Real>& Wm4::Mapper3< Real >::GetDirection (int i) const
Referenced by Wm4::ConvexHull3< Real >::ConvexHull3(), and Wm4::Delaunay3< Real >::Delaunay3().
GetExtremeCCW()
template<class Real > bool Wm4::Mapper3< Real >::GetExtremeCCW () const
Referenced by Wm4::ConvexHull3< Real >::ConvexHull3().
GetExtremeIndex()
template<class Real > int Wm4::Mapper3< Real >::GetExtremeIndex (int i) const
Referenced by Wm4::ConvexHull3< Real >::ConvexHull3().
GetMax()
template<class Real > const Vector3<Real>& Wm4::Mapper3< Real >::GetMax () const
Referenced by Wm4::Delaunay3< Real >::Delaunay3().
GetMaxRange()
template<class Real > Real Wm4::Mapper3< Real >::GetMaxRange () const
Referenced by Wm4::ConvexHull3< Real >::ConvexHull3(), and Wm4::Delaunay3< Real >::Delaunay3().
GetMin()
template<class Real > const Vector3<Real>& Wm4::Mapper3< Real >::GetMin () const
Referenced by Wm4::ConvexHull3< Real >::ConvexHull3(), and Wm4::Delaunay3< Real >::Delaunay3().
GetOrigin()
template<class Real > const Vector3<Real>& Wm4::Mapper3< Real >::GetOrigin () const
Referenced by Wm4::ConvexHull3< Real >::ConvexHull3(), and Wm4::Delaunay3< Real >::Delaunay3().
The documentation for this class was generated from the following file:
Wm4Mapper3.h