FreeCAD: Gui::RDragger Class Reference
Gui::RDragger Class Reference
Rotation Dragger.
#include <SoFCCSysDragger.h>
Public Member Functions
RDragger ()
Static Public Member Functions
static void initClass ()
Public Attributes
SoSFRotation rotation
set from outside and used from outside for single precision.
SoSFDouble rotationIncrement
set from outside and used for rounding.
SoSFInt32 rotationIncrementCount
number of steps. used from outside.
SoSFColor color
set from outside. non-active color.
Protected Member Functions
~RDragger () override
SbBool setUpConnections (SbBool onoff, SbBool doitalways=FALSE) override
void dragStart ()
void drag ()
void dragFinish ()
Static Protected Member Functions
static void startCB (void *, SoDragger *d)
static void motionCB (void *, SoDragger *d)
static void finishCB (void *, SoDragger *d)
static void fieldSensorCB (void *f, SoSensor *)
static void valueChangedCB (void *, SoDragger *d)
Protected Attributes
SoFieldSensor fieldSensor
SbPlaneProjector projector
float arcRadius
Detailed Description
Rotation Dragger.
used for rotating around an axis. Set the rotation increment to desired step. Use rotationIncrementCount multiplied with rotationIncrement for full double precision vector scalar.
Definition at line 164 of file SoFCCSysDragger.h.
Constructor & Destructor Documentation
RDragger()
RDragger::RDragger ()
Definition at line 728 of file SoFCCSysDragger.cpp.
References arcRadius, fieldSensor, fieldSensorCB(), finishCB(), M_PI, motionCB(), rotation, rotationIncrement, rotationIncrementCount, setUpConnections(), startCB(), SCL.Builtin::TRUE, and valueChangedCB().
~RDragger()
RDragger::~RDragger () override protected
Definition at line 773 of file SoFCCSysDragger.cpp.
References fieldSensor, finishCB(), motionCB(), startCB(), and valueChangedCB().
Member Function Documentation
drag()
void RDragger::drag () protected
Definition at line 927 of file SoFCCSysDragger.cpp.
References Base::Unit::Angle, SCL.SimpleDataTypes::f, Gui::getMainWindow(), Base::Quantity::getUserString(), M_PI, projector, rotationIncrement, rotationIncrementCount, and Gui::MainWindow::showMessage().
dragFinish()
void RDragger::dragFinish () protected
Definition at line 977 of file SoFCCSysDragger.cpp.
dragStart()
void RDragger::dragStart () protected
Definition at line 904 of file SoFCCSysDragger.cpp.
References projector, and rotationIncrementCount.
fieldSensorCB()
void RDragger::fieldSensorCB (void * f, SoSensor *) static protected
Definition at line 873 of file SoFCCSysDragger.cpp.
References SCL.SimpleDataTypes::f.
Referenced by RDragger(), and setUpConnections().
finishCB()
void RDragger::finishCB (void * , SoDragger * d) static protected
Definition at line 866 of file SoFCCSysDragger.cpp.
Referenced by RDragger(), and ~RDragger().
initClass()
void RDragger::initClass () static
Definition at line 723 of file SoFCCSysDragger.cpp.
Referenced by Gui::SoFCCSysDragger::initClass(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
motionCB()
void RDragger::motionCB (void * , SoDragger * d) static protected
Definition at line 859 of file SoFCCSysDragger.cpp.
Referenced by RDragger(), and ~RDragger().
setUpConnections()
SbBool RDragger::setUpConnections (SbBool onoff, SbBool doitalways = FALSE) override protected
Definition at line 984 of file SoFCCSysDragger.cpp.
References fieldSensor, fieldSensorCB(), and rotation.
Referenced by RDragger().
startCB()
void RDragger::startCB (void * , SoDragger * d) static protected
Definition at line 852 of file SoFCCSysDragger.cpp.
Referenced by RDragger(), and ~RDragger().
valueChangedCB()
void RDragger::valueChangedCB (void * , SoDragger * d) static protected
Definition at line 886 of file SoFCCSysDragger.cpp.
Referenced by RDragger(), and ~RDragger().
Member Data Documentation
arcRadius
float Gui::RDragger::arcRadius protected
Definition at line 194 of file SoFCCSysDragger.h.
Referenced by Path.Base.Language.MoveArc::pathLength(), and RDragger().
color
SoSFColor Gui::RDragger::color
set from outside. non-active color.
Definition at line 176 of file SoFCCSysDragger.h.
Referenced by draftguitools.gui_trimex.Trimex::finish(), importSVG.svgHandler::format(), DraftGui.DraftToolBar::getDefaultColor(), Path.Dressup.Gui.DogboneII.Marker::highlight(), Path.Dressup.Gui.Dogbone.Marker::highlight(), Path.Dressup.Gui.DogboneII.Marker::lowlight(), Path.Dressup.Gui.Dogbone.Marker::lowlight(), FeaturePython.ViewProviderOctahedron::onChanged(), ArchSpace._ViewProviderSpace::onChanged(), ArchPanel.ViewProviderPanelCut::onChanged(), ArchSite._ViewProviderSite::onChanged(), ArchPanel.ViewProviderPanelSheet::onChanged(), src.Mod.Test.unittestgui.ProgressBar::paint(), draftguitools.gui_trackers.Tracker::setColor(), draftguitools.gui_trackers.snapTracker::setColor(), draftguitools.gui_trackers.ghostTracker::setColor(), draftguitools.gui_trackers.editTracker::setColor(), Path.Dressup.Gui.Tags.HoldingTagMarker::setEnabled(), and DraftGui.DraftToolBar::setStyleButton().
fieldSensor
SoFieldSensor Gui::RDragger::fieldSensor protected
Definition at line 192 of file SoFCCSysDragger.h.
Referenced by RDragger(), setUpConnections(), and ~RDragger().
projector
SbPlaneProjector Gui::RDragger::projector protected
Definition at line 193 of file SoFCCSysDragger.h.
Referenced by drag(), and dragStart().
rotation
SoSFRotation Gui::RDragger::rotation
set from outside and used from outside for single precision.
Definition at line 173 of file SoFCCSysDragger.h.
Referenced by femtaskpanels.task_element_rotation1D._TaskPanel::accept(), RDragger(), femtaskpanels.task_element_rotation1D._TaskPanel::rotation_changed(), and setUpConnections().
rotationIncrement
SoSFDouble Gui::RDragger::rotationIncrement
set from outside and used for rounding.
Definition at line 174 of file SoFCCSysDragger.h.
Referenced by drag(), RDragger(), and Gui::SoFCCSysDragger::SoFCCSysDragger().
rotationIncrementCount
SoSFInt32 Gui::RDragger::rotationIncrementCount
number of steps. used from outside.
Definition at line 175 of file SoFCCSysDragger.h.
Referenced by drag(), dragStart(), RDragger(), and Gui::SoFCCSysDragger::SoFCCSysDragger().
The documentation for this class was generated from the following files:
SoFCCSysDragger.h
SoFCCSysDragger.cpp