FreeCAD: ifc2x3.ifcboundaryfacecondition Class Reference
ifc2x3.ifcboundaryfacecondition Class Reference
Public Member Functions
def __init__ (self, inherited0__name, linearstiffnessbyareax, linearstiffnessbyareay, linearstiffnessbyareaz)
def linearstiffnessbyareax ()
def linearstiffnessbyareay ()
def linearstiffnessbyareaz ()
Public Member Functions inherited from ifc2x3.ifcboundarycondition
def __init__ (self, name)
def name ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
linearstiffnessbyareax
linearstiffnessbyareay
linearstiffnessbyareaz
Public Attributes inherited from ifc2x3.ifcboundarycondition
name
Detailed Description
Entity ifcboundaryfacecondition definition.
:param linearstiffnessbyareax
:type linearstiffnessbyareax:ifcmodulusofsubgradereactionmeasure
:param linearstiffnessbyareay
:type linearstiffnessbyareay:ifcmodulusofsubgradereactionmeasure
:param linearstiffnessbyareaz
:type linearstiffnessbyareaz:ifcmodulusofsubgradereactionmeasure
Definition at line 33582 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcboundaryfacecondition.__init__ (self, inherited0__name, linearstiffnessbyareax, linearstiffnessbyareay, linearstiffnessbyareaz)
Definition at line 33594 of file ifc2x3.py.
Member Function Documentation
linearstiffnessbyareax()
def ifc2x3.ifcboundaryfacecondition.linearstiffnessbyareax ()
Definition at line 33601 of file ifc2x3.py.
References ifc2x3.ifcboundaryfacecondition._linearstiffnessbyareax, SCL.TypeChecker.check_type(), and ifc2x3.ifcboundaryfacecondition.linearstiffnessbyareax.
linearstiffnessbyareay()
def ifc2x3.ifcboundaryfacecondition.linearstiffnessbyareay ()
Definition at line 33615 of file ifc2x3.py.
References ifc2x3.ifcboundaryfacecondition._linearstiffnessbyareay, SCL.TypeChecker.check_type(), and ifc2x3.ifcboundaryfacecondition.linearstiffnessbyareay.
linearstiffnessbyareaz()
def ifc2x3.ifcboundaryfacecondition.linearstiffnessbyareaz ()
Definition at line 33629 of file ifc2x3.py.
References ifc2x3.ifcboundaryfacecondition._linearstiffnessbyareaz, SCL.TypeChecker.check_type(), and ifc2x3.ifcboundaryfacecondition.linearstiffnessbyareaz.
Member Data Documentation
linearstiffnessbyareax
ifc2x3.ifcboundaryfacecondition.linearstiffnessbyareax
Definition at line 33596 of file ifc2x3.py.
Referenced by ifc2x3.ifcboundaryfacecondition.linearstiffnessbyareax().
linearstiffnessbyareay
ifc2x3.ifcboundaryfacecondition.linearstiffnessbyareay
Definition at line 33597 of file ifc2x3.py.
Referenced by ifc2x3.ifcboundaryfacecondition.linearstiffnessbyareay().
linearstiffnessbyareaz
ifc2x3.ifcboundaryfacecondition.linearstiffnessbyareaz
Definition at line 33598 of file ifc2x3.py.
Referenced by ifc2x3.ifcboundaryfacecondition.linearstiffnessbyareaz().
The documentation for this class was generated from the following file:
ifc2x3.py