FreeCAD: PartGui::SoBrepFaceSet Class Reference
PartGui::SoBrepFaceSet Class Reference
#include <SoBrepFaceSet.h>
Classes
class VBO
Public Member Functions
SoBrepFaceSet ()
Static Public Member Functions
static void initClass ()
Public Attributes
SoMFInt32 partIndex
Protected Member Functions
~SoBrepFaceSet () override
void GLRender (SoGLRenderAction *action) override
void GLRenderBelowPath (SoGLRenderAction *action) override
void doAction (SoAction *action) override
SoDetail * createTriangleDetail (SoRayPickAction *action, const SoPrimitiveVertex *v1, const SoPrimitiveVertex *v2, const SoPrimitiveVertex *v3, SoPickedPoint *pp) override
void generatePrimitives (SoAction *action) override
void getBoundingBox (SoGetBoundingBoxAction *action) override
Detailed Description
First some words to the history and the reason why we have this class: In older FreeCAD versions we had an own Inventor node for each sub-element of a shape with its own highlight node. For more complex objects the number of nodes increased dramatically with the result that interactions with such objects was almost impossible because every little rotation or hovering caused a very time consuming redraw. The most time consuming part was not the OpenGL calls to render the elements but the traversal of these many nodes.
So, the idea was to have one node that handles all faces of a shape, one node that handles all edges and another node that handles the vertexes. And each of these nodes manages the highlighting and selection itself.
Now to SoBrepFaceSet in detail: The most complex nodes of them is SoBrepFaceSet because it adds some extra logic for the handling of faces. As you can see this class also has the attribute partIndex which is an array of integers. This basically expresses the logical grouping of the faces in the coordIndex field – the parts. This means that a part in SoBrepFaceSet corresponds to a face in a shape object. Each part value gives you the number of triangles a certain face consists of. That's also the reason why SoBrepFaceSet only renders triangles. If you want a quad to be rendered than create two triangles and set the corresponding part number to 2.
Example: Let's say you have a shape with two faces. When meshing face 1 it creates 10 triangles and face 2 creates 5 triangles. Then the partIndex attribute would be the array [10,5].
Highlighting/selection: The highlightIndex now defines which part of the shape must be highlighted. So, in the above example it can have the values 0, 1, or -1 (i.e. no highlighting). The highlightIndex is a SoSFInt32 field because only one part can be highlighted at a moment while selectionIndex is a SoMFInt32 field because several parts can be selected at a time. All the logic how to do the rendering is done inside renderHighlight()/renderSelection().
Actually you can access the highlightIndex directly or you can apply a SoHighlightElementAction on it. And don't forget: if you do some mouse picking and you got a SoFaceDetail then use getPartIndex() to get the correct part.
As an example how to use the class correctly see ViewProviderPartExt::updateVisual().
Definition at line 74 of file SoBrepFaceSet.h.
Constructor & Destructor Documentation
SoBrepFaceSet()
SoBrepFaceSet::SoBrepFaceSet ()
Definition at line 164 of file SoBrepFaceSet.cpp.
References partIndex.
~SoBrepFaceSet()
SoBrepFaceSet::~SoBrepFaceSet () override protected default
Member Function Documentation
createTriangleDetail()
SoDetail * SoBrepFaceSet::createTriangleDetail (SoRayPickAction * action, const SoPrimitiveVertex * v1, const SoPrimitiveVertex * v2, const SoPrimitiveVertex * v3, SoPickedPoint * pp) override protected
Definition at line 1871 of file SoBrepFaceSet.cpp.
References Path.Post.scripts.dynapath_4060_post::action, src.Mod.AddonManager.NetworkManager::count, SplineSurface::i, and draftgeoutils.general::v1().
doAction()
void SoBrepFaceSet::doAction (SoAction * action) override protected
Definition at line 178 of file SoBrepFaceSet.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Gui::SoSelectionElementAction::All, Gui::SoSelectionElementAction::Append, Gui::SoFCSelectionCounter::checkAction(), Gui::SoSelectionElementAction::Color, importers.importIFCmulticore::colors, src.Mod.AddonManager.NetworkManager::count, Gui::SoFCSelectionRoot::getActionContext(), Gui::SoHighlightElementAction::getColor(), Gui::SoSelectionElementAction::getColor(), Gui::SoSelectionElementAction::getColors(), Gui::SoHighlightElementAction::getElement(), Gui::SoSelectionElementAction::getElement(), Gui::SoSelectionElementAction::getType(), SplineSurface::i, Gui::SoHighlightElementAction::isHighlighted(), Gui::SoSelectionElementAction::isSecondary(), Gui::SoSelectionElementAction::None, partIndex, PRIVATE, Gui::SoSelectionElementAction::Remove, Gui::SoFCSelectionRoot::removeActionContext(), and TestSpreadsheet::v.
generatePrimitives()
void SoBrepFaceSet::generatePrimitives (SoAction * action) override protected
Definition at line 945 of file SoBrepFaceSet.cpp.
References Path.Post.scripts.dynapath_4060_post::action, DO_VERTEX, partIndex, MeshCore::MeshIO::PER_VERTEX, ClipperLib::pi, and draftgeoutils.general::v1().
getBoundingBox()
void SoBrepFaceSet::getBoundingBox (SoGetBoundingBoxAction * action) override protected
Definition at line 866 of file SoBrepFaceSet.cpp.
References Path.Post.scripts.dynapath_4060_post::action, SplineSurface::id, and partIndex.
GLRender()
void SoBrepFaceSet::GLRender (SoGLRenderAction * action) override protected
Definition at line 494 of file SoBrepFaceSet.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Gui::SoFCSelectionCounter::checkRenderCache(), create_qrc::ext, Gui::SoGLVBOActivatedElement::get(), Gui::SoFCSelectionRoot::getRenderContext(), SIM::Coin3D::Quarter::Quarter::init(), partIndex, and PRIVATE.
GLRenderBelowPath()
void SoBrepFaceSet::GLRenderBelowPath (SoGLRenderAction * action) override protected
Definition at line 861 of file SoBrepFaceSet.cpp.
References Path.Post.scripts.dynapath_4060_post::action.
initClass()
void SoBrepFaceSet::initClass () static
Definition at line 159 of file SoBrepFaceSet.cpp.
Referenced by PyMOD_INIT_FUNC().
Member Data Documentation
partIndex
SoMFInt32 PartGui::SoBrepFaceSet::partIndex
Definition at line 83 of file SoBrepFaceSet.h.
Referenced by PartDesignGui::ViewProviderDatumPlane::attach(), doAction(), generatePrimitives(), getBoundingBox(), GLRender(), PartGui::ViewProviderPartExt::setHighlightedFaces(), SoBrepFaceSet(), PartDesignGui::ViewProviderAddSub::updateAddSubShapeIndicator(), PartGui::ViewProviderPartExt::updateData(), and PartGui::ViewProviderPartExt::updateVisual().
The documentation for this class was generated from the following files:
SoBrepFaceSet.h
SoBrepFaceSet.cpp