FreeCAD: Import::SketchExportHelper Class Reference
Import::SketchExportHelper Class Reference
#include <SketchExportHelper.h>
Static Public Member Functions
static TopoDS_Shape projectShape (const TopoDS_Shape &inShape, const gp_Ax2 &projectionCS)
static bool isSketch (App::DocumentObject *obj)
true if obj is a sketch
static TopoDS_Shape getFlatSketchXY (App::DocumentObject *obj)
Detailed Description
Definition at line 38 of file SketchExportHelper.h.
Member Function Documentation
getFlatSketchXY()
TopoDS_Shape SketchExportHelper::getFlatSketchXY (App::DocumentObject * obj) static
return a version of a sketch's geometry mapped to the OXYZ coordinate system preferred by dxf
Definition at line 89 of file SketchExportHelper.cpp.
References App::PropertyPlacement::getValue(), isSketch(), Base::Rotation::multVec(), App::GeoFeature::Placement, projectShape(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
isSketch()
bool SketchExportHelper::isSketch (App::DocumentObject * obj) static
true if obj is a sketch
Definition at line 74 of file SketchExportHelper.cpp.
References Base::Type::getName(), and Base::Persistence::getTypeId().
Referenced by getFlatSketchXY().
projectShape()
TopoDS_Shape SketchExportHelper::projectShape (const TopoDS_Shape & inShape, const gp_Ax2 & projectionCS) static
project a shape so that it is represented as a flat shape on the XY plane. Z coordinate information is lost in this process, so it should only be used for flat objects like sketches. Note: this only returns hard and outline edges. Seam, smooth, isoparametric and hidden lines are not returned.
Definition at line 50 of file SketchExportHelper.cpp.
References Handle().
Referenced by getFlatSketchXY().
The documentation for this class was generated from the following files:
SketchExportHelper.h
SketchExportHelper.cpp