FreeCAD: Gui::TextDocumentEditorView Class Reference
Gui::TextDocumentEditorView Class Reference
#include <TextDocumentEditorView.h>
Public Member Functions
TextDocumentEditorView (App::TextDocument *textDocument, QPlainTextEdit *editor, QWidget *parent)
~TextDocumentEditorView () override
const char * getName () const override
returns the name of the view (important for messages)
bool onMsg (const char *msg, const char **output) override
Message handler.
bool onHasMsg (const char *msg) const override
Message handler test.
QPlainTextEdit * getEditor () const
App::TextDocument * getTextObject () const
QStringList undoActions () const override
QStringList redoActions () const override
Public Member Functions inherited from Gui::MDIView
MDIView (Gui::Document *pcDocument, QWidget *parent, Qt::WindowFlags wflags=Qt::WindowFlags())
~MDIView () override
void onRelabel (Gui::Document *pDoc) override
get called when the document is updated
virtual void viewAll ()
QString buildWindowTitle () const
build window title
bool canClose () override
overwrite when checking on close state
void deleteSelf () override
delete itself
PyObject * getPyObject () override
virtual void print ()
virtual void printPdf ()
virtual void printPreview ()
void savePrinterSettings (QPrinter *printer)
void restorePrinterSettings (QPrinter *printer)
QSize minimumSizeHint () const override
virtual void setCurrentViewMode (ViewMode mode)
ViewMode currentViewMode () const
template<typename _T >
_T getActiveObject (const char *name, App::DocumentObject **parent=nullptr, std::string *subname=nullptr) const
access getter for the active object list
void setActiveObject (App::DocumentObject *o, const char *n, const char *subname=nullptr)
bool hasActiveObject (const char *n) const
bool isActiveObject (App::DocumentObject *o, const char *n, const char *subname=nullptr) const
virtual bool containsViewProvider (const ViewProvider *) const
containsViewProvider Checks if the given view provider is part of this view. The default implementation returns false.
Public Member Functions inherited from Gui::BaseView
BaseView (Gui::Document *pcDocument=nullptr)
~BaseView () override
void setDocument (Gui::Document *pcDocument)
sets the view to another document (called by Application)
void onClose ()
is sent from the document in order to close the document
Gui::Document * getGuiDocument () const
returns the document the view is attached to
App::Document * getAppDocument () const
returns the document the view is attached to
bool isPassive () const
indicates if the view is in passive mode
virtual void onUpdate ()
get called when the document is updated
virtual void onRename (Gui::Document *)
get called when the document is renamed (change of its internal name)
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Member Functions
void showEvent (QShowEvent *event) override
void closeEvent (QCloseEvent *event) override
Protected Member Functions inherited from Gui::MDIView
void closeEvent (QCloseEvent *e) override
void changeEvent (QEvent *e) override
Additional Inherited Members
Public Types inherited from Gui::MDIView
enum ViewMode { Child, TopLevel, FullScreen }
MDI view mode enum.
Public Slots inherited from Gui::MDIView
virtual void print (QPrinter *printer)
virtual void setOverrideCursor (const QCursor &)
virtual void restoreOverrideCursor ()
Signals inherited from Gui::MDIView
void message (const QString &, int)
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Protected Slots inherited from Gui::MDIView
virtual void windowStateChanged (QWidget *)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Gui::MDIView
PyObject * pythonObject
Protected Attributes inherited from Gui::BaseView
Gui::Document * _pcDocument
bool bIsDetached {false}
bool bIsPassive {false}
Detailed Description
Definition at line 55 of file TextDocumentEditorView.h.
Constructor & Destructor Documentation
TextDocumentEditorView()
Gui::TextDocumentEditorView::TextDocumentEditorView (App::TextDocument * textDocument, QPlainTextEdit * editor, QWidget * parent)
~TextDocumentEditorView()
TextDocumentEditorView::~TextDocumentEditorView () override
Definition at line 63 of file TextDocumentEditorView.cpp.
Member Function Documentation
closeEvent()
void TextDocumentEditorView::closeEvent (QCloseEvent * event) override protected
Definition at line 76 of file TextDocumentEditorView.cpp.
References Gui::MDIView::closeEvent(), Gui::getMainWindow(), and NavigationIndicatorGui::mw.
getEditor()
QPlainTextEdit* Gui::TextDocumentEditorView::getEditor () const inline
Definition at line 93 of file TextDocumentEditorView.h.
Referenced by onHasMsg(), and onMsg().
getName()
const char* Gui::TextDocumentEditorView::getName () const inline override virtual
returns the name of the view (important for messages)
Reimplemented from Gui::BaseView.
Definition at line 86 of file TextDocumentEditorView.h.
getTextObject()
App::TextDocument* Gui::TextDocumentEditorView::getTextObject () const inline
Definition at line 97 of file TextDocumentEditorView.h.
onHasMsg()
bool TextDocumentEditorView::onHasMsg (const char * pMsg) const override virtual
Message handler test.
Reimplemented from Gui::MDIView.
Definition at line 148 of file TextDocumentEditorView.cpp.
References getEditor(), and Path.Op.Surface::msg.
onMsg()
bool TextDocumentEditorView::onMsg (const char * pMsg, const char ** ppReturn) override virtual
Message handler.
receive a message
Reimplemented from Gui::MDIView.
Definition at line 181 of file TextDocumentEditorView.cpp.
References getEditor(), Gui::BaseView::getGuiDocument(), Path.Op.Surface::msg, and Gui::Document::save().
redoActions()
QStringList TextDocumentEditorView::redoActions () const override virtual
Reimplemented from Gui::MDIView.
Definition at line 141 of file TextDocumentEditorView.cpp.
showEvent()
void TextDocumentEditorView::showEvent (QShowEvent * event) override protected
Definition at line 69 of file TextDocumentEditorView.cpp.
References Gui::getMainWindow(), and NavigationIndicatorGui::mw.
undoActions()
QStringList TextDocumentEditorView::undoActions () const override virtual
Reimplemented from Gui::MDIView.
Definition at line 134 of file TextDocumentEditorView.cpp.
The documentation for this class was generated from the following files:
TextDocumentEditorView.h
TextDocumentEditorView.cpp