FreeCAD: Gui::OverlaySplitterHandle Class Reference
Gui::OverlaySplitterHandle Class Reference
Splitter handle for dragging the splitter.
#include <OverlayWidgets.h>
Public Member Functions
OverlaySplitterHandle (Qt::Orientation, QSplitter *parent)
void setTitleItem (QLayoutItem *)
void retranslate ()
void refreshIcons ()
QDockWidget * dockWidget ()
void showTitle (bool enable)
bool isShowing () const
void endDrag ()
Protected Member Functions
void enterEvent (QEnterEvent *ev) override
void showEvent (QShowEvent *ev) override
void leaveEvent (QEvent *ev) override
void paintEvent (QPaintEvent *ev) override
void changeEvent (QEvent *ev) override
void mouseMoveEvent (QMouseEvent *ev) override
void mousePressEvent (QMouseEvent *ev) override
void mouseReleaseEvent (QMouseEvent *ev) override
void keyPressEvent (QKeyEvent *ev) override
QSize sizeHint () const override
void onAction ()
void onTimer ()
Friends
class OverlaySplitter
Detailed Description
Splitter handle for dragging the splitter.
Definition at line 482 of file OverlayWidgets.h.
Constructor & Destructor Documentation
OverlaySplitterHandle()
OverlaySplitterHandle::OverlaySplitterHandle (Qt::Orientation orientation, QSplitter * parent)
Definition at line 2279 of file OverlayWidgets.cpp.
References draftgeoutils.intersections::connect(), onAction(), onTimer(), refreshIcons(), and retranslate().
Member Function Documentation
changeEvent()
void OverlaySplitterHandle::changeEvent (QEvent * ev) override protected
Definition at line 2371 of file OverlayWidgets.cpp.
References SCL.SimpleDataTypes::e, and retranslate().
dockWidget()
QDockWidget * OverlaySplitterHandle::dockWidget ()
Definition at line 2348 of file OverlayWidgets.cpp.
References SCL.SimpleDataTypes::c, SplineSurface::i, and Init::parent.
Referenced by endDrag(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), onAction(), and paintEvent().
endDrag()
void OverlaySplitterHandle::endDrag ()
Definition at line 2453 of file OverlayWidgets.cpp.
References dockWidget(), and Sketcher::Horizontal.
Referenced by keyPressEvent(), mouseMoveEvent(), and mouseReleaseEvent().
enterEvent()
void OverlaySplitterHandle::enterEvent (QEnterEvent * ev) override protected
Definition at line 2313 of file OverlayWidgets.cpp.
References PersistentToolbarsGui::timer.
isShowing()
bool Gui::OverlaySplitterHandle::isShowing () const inline
Definition at line 495 of file OverlayWidgets.h.
keyPressEvent()
void OverlaySplitterHandle::keyPressEvent (QKeyEvent * ev) override protected
Definition at line 2469 of file OverlayWidgets.cpp.
References endDrag().
leaveEvent()
void OverlaySplitterHandle::leaveEvent (QEvent * ev) override protected
Definition at line 2320 of file OverlayWidgets.cpp.
References Gui::OverlayParams::getDockOverlaySplitterHandleTimeout().
mouseMoveEvent()
void OverlaySplitterHandle::mouseMoveEvent (QMouseEvent * ev) override protected
Definition at line 2475 of file OverlayWidgets.cpp.
References dockWidget(), Gui::OverlayManager::dragDockWidget(), endDrag(), Sketcher::Horizontal, Gui::OverlayManager::instance(), nativeifc.ifc_viewproviders::overlay(), and RobotExample::pos.
mousePressEvent()
void OverlaySplitterHandle::mousePressEvent (QMouseEvent * ev) override protected
Definition at line 2525 of file OverlayWidgets.cpp.
References dockWidget(), Gui::OverlayParams::getDockOverlayMinimumSize(), Gui::getMainWindow(), KDL::max(), and KDL::min().
mouseReleaseEvent()
void OverlaySplitterHandle::mouseReleaseEvent (QMouseEvent * ev) override protected
Definition at line 2548 of file OverlayWidgets.cpp.
References dockWidget(), Gui::OverlayManager::dragDockWidget(), endDrag(), and Gui::OverlayManager::instance().
onAction()
void OverlaySplitterHandle::onAction () protected
Definition at line 2338 of file OverlayWidgets.cpp.
References Path.Post.scripts.dynapath_4060_post::action, dockWidget(), Gui::OverlayManager::floatDockWidget(), and Gui::OverlayManager::instance().
Referenced by OverlaySplitterHandle().
onTimer()
void OverlaySplitterHandle::onTimer () protected
Definition at line 2296 of file OverlayWidgets.cpp.
References RobotExample::pos, and showTitle().
Referenced by OverlaySplitterHandle().
paintEvent()
void OverlaySplitterHandle::paintEvent (QPaintEvent * ev) override protected
Definition at line 2402 of file OverlayWidgets.cpp.
References dockWidget(), SCL.SimpleDataTypes::e, and Sketcher::Vertical.
refreshIcons()
void OverlaySplitterHandle::refreshIcons ()
Definition at line 2291 of file OverlayWidgets.cpp.
References Gui::BitmapFactory().
Referenced by OverlaySplitterHandle().
retranslate()
void OverlaySplitterHandle::retranslate ()
Definition at line 2366 of file OverlayWidgets.cpp.
Referenced by changeEvent(), and OverlaySplitterHandle().
setTitleItem()
void OverlaySplitterHandle::setTitleItem (QLayoutItem * item)
Definition at line 2378 of file OverlayWidgets.cpp.
showEvent()
void OverlaySplitterHandle::showEvent (QShowEvent * ev) override protected
Definition at line 2302 of file OverlayWidgets.cpp.
References Gui::OverlayParams::getDockOverlaySplitterHandleTimeout(), and RobotExample::pos.
showTitle()
void OverlaySplitterHandle::showTitle (bool enable)
Definition at line 2383 of file OverlayWidgets.cpp.
References Gui::OverlayParams::getDockOverlaySplitterHandleTimeout(), Sketcher::Horizontal, and RobotExample::pos.
Referenced by onTimer().
sizeHint()
QSize OverlaySplitterHandle::sizeHint () const override protected
Definition at line 2327 of file OverlayWidgets.cpp.
References KDL::max(), Sketcher::Vertical, and widgetMinSize().
Friends And Related Function Documentation
OverlaySplitter
friend class OverlaySplitter friend
Definition at line 486 of file OverlayWidgets.h.
The documentation for this class was generated from the following files:
OverlayWidgets.h
OverlayWidgets.cpp