FreeCAD: PartGui::DlgExportHeaderStep Class Reference
PartGui::DlgExportHeaderStep Class Reference
#include <DlgExportStep.h>
Public Member Functions
DlgExportHeaderStep (QWidget *parent=nullptr)
~DlgExportHeaderStep () override
void saveSettings () override
void loadSettings () override
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Protected Member Functions
void changeEvent (QEvent *e) override
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void resetSettingsToDefaults ()
Detailed Description
Definition at line 69 of file DlgExportStep.h.
Constructor & Destructor Documentation
DlgExportHeaderStep()
DlgExportHeaderStep::DlgExportHeaderStep (QWidget * parent = nullptr) explicit
Definition at line 140 of file DlgExportStep.cpp.
References src.Mod.AddonManager.addonmanager_devmode_license_selector::QRegularExpression, and src.Mod.AddonManager.addonmanager_devmode_license_selector::QRegularExpressionValidator.
~DlgExportHeaderStep()
DlgExportHeaderStep::~DlgExportHeaderStep () override default
Member Function Documentation
changeEvent()
void DlgExportHeaderStep::changeEvent (QEvent * e) override protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
Definition at line 182 of file DlgExportStep.cpp.
References SCL.SimpleDataTypes::e.
loadSettings()
void DlgExportHeaderStep::loadSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 169 of file DlgExportStep.cpp.
References Part::STEP::ImportExportSettings::getAuthor(), Part::STEP::ImportExportSettings::getCompany(), and Part::STEP::ImportExportSettings::getProductName().
Referenced by PartGui::DlgImportExportStep::loadSettings().
saveSettings()
void DlgExportHeaderStep::saveSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 160 of file DlgExportStep.cpp.
References Part::STEP::ImportExportSettings::setAuthor(), and Part::STEP::ImportExportSettings::setCompany().
Referenced by PartGui::DlgImportExportStep::saveSettings().
The documentation for this class was generated from the following files:
DlgExportStep.h
DlgExportStep.cpp