FreeCAD: BarThread Class Reference
BarThread Class Reference
Public Member Functions
BarThread (unsigned long s)
~BarThread () override=default
void run () override
Detailed Description
Definition at line 564 of file CommandTest.cpp.
Constructor & Destructor Documentation
BarThread()
BarThread::BarThread (unsigned long s) inline explicit
Definition at line 567 of file CommandTest.cpp.
~BarThread()
BarThread::~BarThread () override default
Member Function Documentation
run()
void BarThread::run () inline override
Definition at line 571 of file CommandTest.cpp.
References Base::Console(), SplineSurface::i, Base::ConsoleSingleton::Message(), and Base::SequencerLauncher::next().
Referenced by femexamples.examplesgui.FemExamples::clicked(), and femsolver.task.Task::protector().
The documentation for this class was generated from the following file:
CommandTest.cpp