FreeCAD: ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.draughting_callout Class Reference
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.draughting_callout Class Reference
Public Member Functions
def __init__ (self, inherited0__name, contents)
def contents ()
def wr1 (self)
Public Member Functions inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometric_representation_item
def __init__ (self, inherited0__name)
def dim ()
Public Member Functions inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.representation_item
def name ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
contents
Public Attributes inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.representation_item
name
Detailed Description
Entity draughting_callout definition.
:param contents
:type contents:SET(1,None,'draughting_callout_element', scope = schema_scope)
Definition at line 5680 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Constructor & Destructor Documentation
__init__()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.draughting_callout.__init__ (self, inherited0__name, contents)
Reimplemented in ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.angular_dimension, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.curve_dimension, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.structured_dimension_callout, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.draughting_elements, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimension_callout, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.datum_target_callout, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.linear_dimension, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometrical_tolerance_callout, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.radius_dimension, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.diameter_dimension, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimension_curve_directed_callout, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.datum_feature_callout, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_condition_callout, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.ordinate_dimension, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.projection_directed_callout, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.leader_directed_dimension, and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.leader_directed_callout.
Definition at line 5686 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Member Function Documentation
contents()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.draughting_callout.contents ()
Definition at line 5691 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.draughting_callout._contents, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.draughting_callout.contents.
wr1()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.draughting_callout.wr1 (self)
Reimplemented from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometric_representation_item.
Reimplemented in ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.structured_dimension_callout, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.draughting_elements, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimension_callout, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.radius_dimension, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimension_curve_directed_callout, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_condition_callout, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.projection_directed_callout, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.leader_directed_dimension, and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.leader_directed_callout.
Definition at line 5703 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF(), and SCL.Builtin.TYPEOF().
Referenced by config_control_design.week_in_year_number.__init__(), config_control_design.minute_in_hour.__init__(), config_control_design.dimension_count.__init__(), config_control_design.positive_length_measure.__init__(), config_control_design.hour_in_day.__init__(), config_control_design.positive_plane_angle_measure.__init__(), ifc2x3.ifctextalignment.__init__(), config_control_design.day_in_week_number.__init__(), ifc4.ifctextalignment.__init__(), ifc2x3.ifcspecularroughness.__init__(), config_control_design.month_in_year_number.__init__(), ifc2x3.ifcheatingvaluemeasure.__init__(), config_control_design.second_in_minute.__init__(), ifc4.ifcspecularroughness.__init__(), automotive_design.minute_in_hour.__init__(), ifc2x3.ifctexttransformation.__init__(), ifc4.ifcheatingvaluemeasure.__init__(), automotive_design.non_negative_length_measure.__init__(), ifc4.ifctexttransformation.__init__(), automotive_design.u_direction_count.__init__(), automotive_design.dimension_count.__init__(), automotive_design.positive_length_measure.__init__(), automotive_design.hour_in_day.__init__(), automotive_design.v_direction_count.__init__(), ifc2x3.ifcfontstyle.__init__(), ifc2x3.ifcboxalignment.__init__(), ifc2x3.ifcminuteinhour.__init__(), automotive_design.day_in_month_number.__init__(), ifc4.ifcfontstyle.__init__(), automotive_design.positive_plane_angle_measure.__init__(), ifc2x3.ifcpositiveplaneanglemeasure.__init__(), ifc4.ifcboxalignment.__init__(), ifc2x3.ifcdimensioncount.__init__(), automotive_design.presentable_text.__init__(), ifc4.ifcpositiveplaneanglemeasure.__init__(), ifc4.ifcdimensioncount.__init__(), ifc2x3.ifcdaylightsavinghour.__init__(), automotive_design.positive_ratio_measure.__init__(), ifc2x3.ifcmonthinyearnumber.__init__(), ifc2x3.ifcsecondinminute.__init__(), ifc2x3.ifcfontvariant.__init__(), automotive_design.month_in_year_number.__init__(), ifc2x3.ifcfontweight.__init__(), ifc2x3.ifchourinday.__init__(), ifc2x3.ifcnormalisedratiomeasure.__init__(), automotive_design.second_in_minute.__init__(), ifc2x3.ifcpositivelengthmeasure.__init__(), ifc2x3.ifcpositiveratiomeasure.__init__(), ifc4.ifcfontvariant.__init__(), ifc4.ifcfontweight.__init__(), ifc2x3.ifctextdecoration.__init__(), ifc4.ifcnormalisedratiomeasure.__init__(), ifc4.ifcpositivelengthmeasure.__init__(), ifc4.ifcpositiveratiomeasure.__init__(), and ifc4.ifctextdecoration.__init__().
Member Data Documentation
contents
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.draughting_callout.contents
Definition at line 5688 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.draughting_callout.contents().
The documentation for this class was generated from the following file:
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py