FreeCAD: TechDrawGui::QGVNavStyleRevit Class Reference
TechDrawGui::QGVNavStyleRevit Class Reference
#include <QGVNavStyleRevit.h>
Public Member Functions
QGVNavStyleRevit (QGVPage *qgvp)
~QGVNavStyleRevit () override
void handleMousePressEvent (QMouseEvent *event) override
void handleMouseMoveEvent (QMouseEvent *event) override
void handleMouseReleaseEvent (QMouseEvent *event) override
bool allowContextMenu (QContextMenuEvent *event) override
Public Member Functions inherited from TechDrawGui::QGVNavStyle
QGVNavStyle (QGVPage *qgvp)
~QGVNavStyle () override
void setViewer (QGVPage *qgvp)
QGVPage * getViewer ()
virtual void handleEnterEvent (QEvent *event)
virtual void handleFocusOutEvent (QFocusEvent *event)
virtual void handleKeyPressEvent (QKeyEvent *event)
virtual void handleKeyReleaseEvent (QKeyEvent *event)
virtual void handleLeaveEvent (QEvent *event)
virtual void handleWheelEvent (QWheelEvent *event)
virtual void pseudoContextEvent ()
virtual void startZoom (QPoint p)
virtual void zoom (double factor)
virtual void stopZoom ()
virtual double mouseZoomFactor (QPoint p)
virtual void zoomIn ()
virtual void zoomOut ()
virtual void startPan (QPoint p)
virtual void pan (QPoint p)
virtual void stopPan ()
virtual void startClick (Qt::MouseButton b)
virtual void stopClick ()
virtual void placeBalloon (QPoint p)
virtual void balloonCursorMovement (QMouseEvent *event)
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Protected Member Functions inherited from TechDrawGui::QGVNavStyle
virtual void initialize ()
virtual void setAnchor ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from TechDrawGui::QGVNavStyle
QGVPage * m_viewer
int m_currentmode
bool ctrldown
bool shiftdown
bool altdown
bool button1down
bool button2down
bool button3down
bool invertZoom
bool zoomAtCursor
double zoomStep
int m_reversePan
int m_reverseScroll
QPoint panOrigin
bool panningActive
QPoint zoomOrigin
bool zoomingActive
bool m_clickPending
bool m_panPending
bool m_zoomPending
Qt::MouseButton m_clickButton
KeyCombination m_keyCombo
QCursor m_saveCursor
int m_wheelDeltaCounter
int m_mouseDeltaCounter
Detailed Description
Definition at line 55 of file QGVNavStyleRevit.h.
Constructor & Destructor Documentation
QGVNavStyleRevit()
TechDrawGui::QGVNavStyleRevit::QGVNavStyleRevit (QGVPage * qgvp) explicit
Definition at line 37 of file QGVNavStyleRevit.cpp.
~QGVNavStyleRevit()
TechDrawGui::QGVNavStyleRevit::~QGVNavStyleRevit () override
Definition at line 42 of file QGVNavStyleRevit.cpp.
Member Function Documentation
allowContextMenu()
bool TechDrawGui::QGVNavStyleRevit::allowContextMenu (QContextMenuEvent * event) override virtual
Reimplemented from TechDrawGui::QGVNavStyle.
Definition at line 114 of file QGVNavStyleRevit.cpp.
References TechDrawGui::QGVNavStyle::m_clickPending.
handleMouseMoveEvent()
void TechDrawGui::QGVNavStyleRevit::handleMouseMoveEvent (QMouseEvent * event) override virtual
Reimplemented from TechDrawGui::QGVNavStyle.
Definition at line 53 of file QGVNavStyleRevit.cpp.
References TechDrawGui::QGVNavStyle::balloonCursorMovement(), TechDrawGui::QGVNavStyle::getViewer(), TechDrawGui::QGVNavStyle::m_clickPending, TechDrawGui::QGVNavStyle::pan(), TechDrawGui::QGVNavStyle::panningActive, TechDrawGui::QGVNavStyle::startPan(), and TechDrawGui::QGVNavStyle::stopClick().
handleMousePressEvent()
void TechDrawGui::QGVNavStyleRevit::handleMousePressEvent (QMouseEvent * event) override virtual
Reimplemented from TechDrawGui::QGVNavStyle.
Definition at line 46 of file QGVNavStyleRevit.cpp.
References TechDrawGui::QGVNavStyle::startClick().
handleMouseReleaseEvent()
void TechDrawGui::QGVNavStyleRevit::handleMouseReleaseEvent (QMouseEvent * event) override virtual
Reimplemented from TechDrawGui::QGVNavStyle.
Definition at line 88 of file QGVNavStyleRevit.cpp.
References TechDrawGui::QGVNavStyle::getViewer(), TechDrawGui::QGVNavStyle::m_clickButton, TechDrawGui::QGVNavStyle::m_clickPending, TechDrawGui::QGVNavStyle::panningActive, TechDrawGui::QGVNavStyle::placeBalloon(), TechDrawGui::QGVNavStyle::pseudoContextEvent(), TechDrawGui::QGVNavStyle::stopClick(), and TechDrawGui::QGVNavStyle::stopPan().
The documentation for this class was generated from the following files:
QGVNavStyleRevit.h
QGVNavStyleRevit.cpp