FreeCAD: Sketcher::SolverGeometryExtension Class Reference
Sketcher::SolverGeometryExtension Class Reference
#include <SolverGeometryExtension.h>
Classes
class Arc
class ArcOfEllipse
class ArcOfHyperbola
class ArcOfParabola
class BSpline
class Circle
class EdgeParameterStatus
class Ellipse
class Line
class Point
class PointParameterStatus
Public Types
enum SolverStatus { FullyConstraint = 0, NotFullyConstraint = 1, NumSolverStatus }
enum ParameterStatus { Dependent = 0, Independent = 1, NumParameterStatus }
Public Member Functions
SolverGeometryExtension ()
~SolverGeometryExtension () override=default
std::unique_ptr< Part::GeometryExtension > copy () const override
PyObject * getPyObject () override
void notifyAttachment (Part::Geometry *geo) override
SolverStatus getGeometry () const
ParameterStatus getEdge () const
Point & getPoint ()
Line & getLine ()
Arc & getArc ()
Circle & getCircle ()
ArcOfEllipse & getArcOfEllipse ()
Ellipse & getEllipse ()
ArcOfHyperbola & getArcOfHyperbola ()
ArcOfParabola & getArcOfParabola ()
BSpline & getBSpline ()
EdgeParameterStatus getEdgeParameters ()
void setEdge (ParameterStatus status)
void setEdge (int paramindex, ParameterStatus status)
ParameterStatus getStart () const
PointParameterStatus getStartPoint () const
void setStart (ParameterStatus xstatus, ParameterStatus ystatus)
void setStartx (ParameterStatus xstatus)
void setStarty (ParameterStatus ystatus)
ParameterStatus getMid () const
PointParameterStatus getMidPoint () const
void setMid (ParameterStatus xstatus, ParameterStatus ystatus)
void setMidx (ParameterStatus xstatus)
void setMidy (ParameterStatus ystatus)
ParameterStatus getEnd () const
PointParameterStatus getEndPoint () const
void setEnd (ParameterStatus xstatus, ParameterStatus ystatus)
void setEndx (ParameterStatus xstatus)
void setEndy (ParameterStatus ystatus)
PointParameterStatus getPoint (Sketcher::PointPos pos) const
void init (ParameterStatus status)
Public Member Functions inherited from Part::GeometryExtension
~GeometryExtension () override=default
PyObject * copyPyObject () const
void setName (const std::string &str)
const std::string & getName () const
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Member Functions
void copyAttributes (Part::GeometryExtension *cpy) const override
Protected Member Functions inherited from Part::GeometryExtension
GeometryExtension ()
GeometryExtension (const GeometryExtension &obj)=default
GeometryExtension & operator= (const GeometryExtension &obj)=default
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 56 of file SolverGeometryExtension.h.
Member Enumeration Documentation
ParameterStatus
enum Sketcher::SolverGeometryExtension::ParameterStatus
Enumerator
Dependent
Independent
NumParameterStatus
Definition at line 88 of file SolverGeometryExtension.h.
SolverStatus
enum Sketcher::SolverGeometryExtension::SolverStatus
Enumerator
FullyConstraint
NotFullyConstraint
NumSolverStatus
Definition at line 81 of file SolverGeometryExtension.h.
Constructor & Destructor Documentation
SolverGeometryExtension()
SolverGeometryExtension::SolverGeometryExtension ()
Definition at line 36 of file SolverGeometryExtension.cpp.
~SolverGeometryExtension()
Sketcher::SolverGeometryExtension::~SolverGeometryExtension () override default
Member Function Documentation
copy()
std::unique_ptr< Part::GeometryExtension > SolverGeometryExtension::copy () const override virtual
Implements Part::GeometryExtension.
Definition at line 51 of file SolverGeometryExtension.cpp.
References copyAttributes(), and Path.Post.scripts.opensbp_post::move().
copyAttributes()
void SolverGeometryExtension::copyAttributes (Part::GeometryExtension * cpy) const override protected virtual
Reimplemented from Part::GeometryExtension.
Definition at line 42 of file SolverGeometryExtension.cpp.
References Part::GeometryExtension::copyAttributes().
Referenced by copy().
getArc()
SolverGeometryExtension::Arc & SolverGeometryExtension::getArc ()
Definition at line 136 of file SolverGeometryExtension.cpp.
References Base::Persistence::getClassTypeId().
getArcOfEllipse()
SolverGeometryExtension::ArcOfEllipse & SolverGeometryExtension::getArcOfEllipse ()
Definition at line 148 of file SolverGeometryExtension.cpp.
References Base::Persistence::getClassTypeId().
getArcOfHyperbola()
SolverGeometryExtension::ArcOfHyperbola & SolverGeometryExtension::getArcOfHyperbola ()
Definition at line 160 of file SolverGeometryExtension.cpp.
References Base::Persistence::getClassTypeId().
getArcOfParabola()
SolverGeometryExtension::ArcOfParabola & SolverGeometryExtension::getArcOfParabola ()
Definition at line 166 of file SolverGeometryExtension.cpp.
References Base::Persistence::getClassTypeId().
getBSpline()
SolverGeometryExtension::BSpline & SolverGeometryExtension::getBSpline ()
Definition at line 172 of file SolverGeometryExtension.cpp.
References Base::Persistence::getClassTypeId().
getCircle()
SolverGeometryExtension::Circle & SolverGeometryExtension::getCircle ()
Definition at line 142 of file SolverGeometryExtension.cpp.
References Base::Persistence::getClassTypeId().
getEdge()
ParameterStatus Sketcher::SolverGeometryExtension::getEdge () const inline
Definition at line 426 of file SolverGeometryExtension.h.
getEdgeParameters()
EdgeParameterStatus Sketcher::SolverGeometryExtension::getEdgeParameters () inline
Definition at line 439 of file SolverGeometryExtension.h.
getEllipse()
SolverGeometryExtension::Ellipse & SolverGeometryExtension::getEllipse ()
Definition at line 154 of file SolverGeometryExtension.cpp.
References Base::Persistence::getClassTypeId().
getEnd()
ParameterStatus Sketcher::SolverGeometryExtension::getEnd () const inline
Definition at line 494 of file SolverGeometryExtension.h.
getEndPoint()
PointParameterStatus Sketcher::SolverGeometryExtension::getEndPoint () const inline
Definition at line 498 of file SolverGeometryExtension.h.
Referenced by getPoint().
getGeometry()
SolverStatus Sketcher::SolverGeometryExtension::getGeometry () const inline
Definition at line 418 of file SolverGeometryExtension.h.
getLine()
SolverGeometryExtension::Line & SolverGeometryExtension::getLine ()
Definition at line 130 of file SolverGeometryExtension.cpp.
References Base::Persistence::getClassTypeId().
getMid()
ParameterStatus Sketcher::SolverGeometryExtension::getMid () const inline
Definition at line 473 of file SolverGeometryExtension.h.
getMidPoint()
PointParameterStatus Sketcher::SolverGeometryExtension::getMidPoint () const inline
Definition at line 477 of file SolverGeometryExtension.h.
Referenced by getPoint().
getPoint() [1/2]
SolverGeometryExtension::Point & SolverGeometryExtension::getPoint ()
Definition at line 124 of file SolverGeometryExtension.cpp.
References Base::Persistence::getClassTypeId().
getPoint() [2/2]
SolverGeometryExtension::PointParameterStatus SolverGeometryExtension::getPoint (Sketcher::PointPos pos) const
Definition at line 70 of file SolverGeometryExtension.cpp.
References Sketcher::end, getEndPoint(), getMidPoint(), getStartPoint(), Sketcher::mid, RobotExample::pos, Sketcher::start, and THROWM.
getPyObject()
PyObject * SolverGeometryExtension::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Implements Part::GeometryExtension.
Definition at line 64 of file SolverGeometryExtension.cpp.
References THROWM.
getStart()
ParameterStatus Sketcher::SolverGeometryExtension::getStart () const inline
Definition at line 452 of file SolverGeometryExtension.h.
getStartPoint()
PointParameterStatus Sketcher::SolverGeometryExtension::getStartPoint () const inline
Definition at line 456 of file SolverGeometryExtension.h.
Referenced by getPoint().
init()
void Sketcher::SolverGeometryExtension::init (ParameterStatus status) inline
Definition at line 518 of file SolverGeometryExtension.h.
Referenced by DocumentObject.DocumentObject::onChanged().
notifyAttachment()
void SolverGeometryExtension::notifyAttachment (Part::Geometry * geo) override virtual
Reimplemented from Part::GeometryExtension.
Definition at line 85 of file SolverGeometryExtension.cpp.
References Base::Persistence::getClassTypeId(), Base::Persistence::getTypeId(), result, and THROWM.
setEdge() [1/2]
void Sketcher::SolverGeometryExtension::setEdge (int paramindex, ParameterStatus status) inline
Definition at line 447 of file SolverGeometryExtension.h.
setEdge() [2/2]
void Sketcher::SolverGeometryExtension::setEdge (ParameterStatus status) inline
Definition at line 443 of file SolverGeometryExtension.h.
setEnd()
void Sketcher::SolverGeometryExtension::setEnd (ParameterStatus xstatus, ParameterStatus ystatus) inline
Definition at line 503 of file SolverGeometryExtension.h.
setEndx()
void Sketcher::SolverGeometryExtension::setEndx (ParameterStatus xstatus) inline
Definition at line 507 of file SolverGeometryExtension.h.
setEndy()
void Sketcher::SolverGeometryExtension::setEndy (ParameterStatus ystatus) inline
Definition at line 511 of file SolverGeometryExtension.h.
setMid()
void Sketcher::SolverGeometryExtension::setMid (ParameterStatus xstatus, ParameterStatus ystatus) inline
Definition at line 481 of file SolverGeometryExtension.h.
setMidx()
void Sketcher::SolverGeometryExtension::setMidx (ParameterStatus xstatus) inline
Definition at line 485 of file SolverGeometryExtension.h.
setMidy()
void Sketcher::SolverGeometryExtension::setMidy (ParameterStatus ystatus) inline
Definition at line 489 of file SolverGeometryExtension.h.
setStart()
void Sketcher::SolverGeometryExtension::setStart (ParameterStatus xstatus, ParameterStatus ystatus) inline
Definition at line 460 of file SolverGeometryExtension.h.
setStartx()
void Sketcher::SolverGeometryExtension::setStartx (ParameterStatus xstatus) inline
Definition at line 464 of file SolverGeometryExtension.h.
setStarty()
void Sketcher::SolverGeometryExtension::setStarty (ParameterStatus ystatus) inline
Definition at line 468 of file SolverGeometryExtension.h.
The documentation for this class was generated from the following files:
SolverGeometryExtension.h
SolverGeometryExtension.cpp