FreeCAD: ifc2x3.ifcgeneralmaterialproperties Class Reference
ifc2x3.ifcgeneralmaterialproperties Class Reference
Public Member Functions
def __init__ (self, inherited0__material, molecularweight, porosity, massdensity)
def molecularweight ()
def porosity ()
def massdensity ()
Public Member Functions inherited from ifc2x3.ifcmaterialproperties
def __init__ (self, material)
def material ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
molecularweight
porosity
massdensity
Public Attributes inherited from ifc2x3.ifcmaterialproperties
material
Detailed Description
Entity ifcgeneralmaterialproperties definition.
:param molecularweight
:type molecularweight:ifcmolecularweightmeasure
:param porosity
:type porosity:ifcnormalisedratiomeasure
:param massdensity
:type massdensity:ifcmassdensitymeasure
Definition at line 22752 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcgeneralmaterialproperties.__init__ (self, inherited0__material, molecularweight, porosity, massdensity)
Definition at line 22764 of file ifc2x3.py.
Member Function Documentation
massdensity()
def ifc2x3.ifcgeneralmaterialproperties.massdensity ()
Definition at line 22799 of file ifc2x3.py.
References ifc2x3.ifcgeneralmaterialproperties._massdensity, SCL.TypeChecker.check_type(), and ifc2x3.ifcgeneralmaterialproperties.massdensity.
molecularweight()
def ifc2x3.ifcgeneralmaterialproperties.molecularweight ()
Definition at line 22771 of file ifc2x3.py.
References ifc2x3.ifcgeneralmaterialproperties._molecularweight, SCL.TypeChecker.check_type(), and ifc2x3.ifcgeneralmaterialproperties.molecularweight.
porosity()
def ifc2x3.ifcgeneralmaterialproperties.porosity ()
Definition at line 22785 of file ifc2x3.py.
References ifc2x3.ifcgeneralmaterialproperties._porosity, SCL.TypeChecker.check_type(), and ifc2x3.ifcgeneralmaterialproperties.porosity.
Member Data Documentation
massdensity
ifc2x3.ifcgeneralmaterialproperties.massdensity
Definition at line 22768 of file ifc2x3.py.
Referenced by ifc2x3.ifcgeneralmaterialproperties.massdensity().
molecularweight
ifc2x3.ifcgeneralmaterialproperties.molecularweight
Definition at line 22766 of file ifc2x3.py.
Referenced by ifc2x3.ifcgeneralmaterialproperties.molecularweight().
porosity
ifc2x3.ifcgeneralmaterialproperties.porosity
Definition at line 22767 of file ifc2x3.py.
Referenced by ifc2x3.ifcgeneralmaterialproperties.porosity().
The documentation for this class was generated from the following file:
ifc2x3.py