FreeCAD: getIfcElements Namespace Reference
getIfcElements Namespace Reference
Classes
class IfcElementHandler
Variables
string xsd_path = "IFC4_ADD2.xsd"
handler = IfcElementHandler()
parser = xml.sax.make_parser()
Detailed Description
This script converts the computer iterpretable listing ifcXML XSD into a list
of non-abstract children of IfcProduct
Variable Documentation
handler
getIfcElements.handler = IfcElementHandler()
Definition at line 87 of file getIfcElements.py.
parser
getIfcElements.parser = xml.sax.make_parser()
Definition at line 88 of file getIfcElements.py.
Referenced by ParameterManager.CheckDocument(), Cloud::CloudReader.CloudReader(), Cloud::CloudWriter.CloudWriter(), App::ProjectFile.loadDocument(), ParameterManager.LoadDocument(), Base::XMLReader.read(), and Base::XMLReader.~XMLReader().
xsd_path
string getIfcElements.xsd_path = "IFC4_ADD2.xsd"
Definition at line 86 of file getIfcElements.py.