FreeCAD: View3DInventorViewer.cpp File Reference
View3DInventorViewer.cpp File Reference
#include "PreCompiled.h"
#include <cfloat>
#include <GL/gl.h>
#include <GL/glext.h>
#include <GL/glu.h>
#include <fmt/format.h>
#include <Inventor/SbBox.h>
#include <Inventor/SoEventManager.h>
#include <Inventor/SoPickedPoint.h>
#include <Inventor/actions/SoGetBoundingBoxAction.h>
#include <Inventor/actions/SoGetMatrixAction.h>
#include <Inventor/actions/SoHandleEventAction.h>
#include <Inventor/actions/SoRayPickAction.h>
#include <Inventor/annex/HardCopy/SoVectorizePSAction.h>
#include <Inventor/details/SoDetail.h>
#include <Inventor/elements/SoLightModelElement.h>
#include <Inventor/elements/SoOverrideElement.h>
#include <Inventor/elements/SoViewportRegionElement.h>
#include <Inventor/errors/SoDebugError.h>
#include <Inventor/events/SoEvent.h>
#include <Inventor/events/SoKeyboardEvent.h>
#include <Inventor/events/SoMotion3Event.h>
#include <Inventor/manips/SoClipPlaneManip.h>
#include <Inventor/nodes/SoAnnotation.h>
#include <Inventor/nodes/SoBaseColor.h>
#include <Inventor/nodes/SoCallback.h>
#include <Inventor/nodes/SoCube.h>
#include <Inventor/nodes/SoDirectionalLight.h>
#include <Inventor/nodes/SoEventCallback.h>
#include <Inventor/nodes/SoLightModel.h>
#include <Inventor/nodes/SoMaterial.h>
#include <Inventor/nodes/SoOrthographicCamera.h>
#include <Inventor/nodes/SoPerspectiveCamera.h>
#include <Inventor/nodes/SoPickStyle.h>
#include <Inventor/nodes/SoScale.h>
#include <Inventor/nodes/SoSelection.h>
#include <Inventor/nodes/SoSeparator.h>
#include <Inventor/nodes/SoSphere.h>
#include <Inventor/nodes/SoSwitch.h>
#include <Inventor/nodes/SoTransform.h>
#include <Inventor/nodes/SoTranslation.h>
#include <QBitmap>
#include <QEventLoop>
#include <QKeyEvent>
#include <QMessageBox>
#include <QMimeData>
#include <QTimer>
#include <QVariantAnimation>
#include <QWheelEvent>
#include <App/Document.h>
#include <App/GeoFeatureGroupExtension.h>
#include <Base/Console.h>
#include <Base/FileInfo.h>
#include <Base/Sequencer.h>
#include <Base/Tools.h>
#include <Base/UnitsApi.h>
#include <Base/Tools2D.h>
#include <Quarter/devices/InputDevice.h>
#include <Quarter/eventhandlers/EventFilter.h>
#include "View3DInventorViewer.h"
#include "Application.h"
#include "Document.h"
#include "GLPainter.h"
#include "Inventor/SoAxisCrossKit.h"
#include "Inventor/SoFCBackgroundGradient.h"
#include "Inventor/SoFCBoundingBox.h"
#include "MainWindow.h"
#include "Multisample.h"
#include "NaviCube.h"
#include "NavigationStyle.h"
#include "Selection.h"
#include "SoDevicePixelRatioElement.h"
#include "SoFCDB.h"
#include "SoFCInteractiveElement.h"
#include "SoFCOffscreenRenderer.h"
#include "SoFCSelection.h"
#include "SoFCSelectionAction.h"
#include "SoFCUnifiedSelection.h"
#include "SoFCVectorizeSVGAction.h"
#include "SoFCVectorizeU3DAction.h"
#include "SoTouchEvents.h"
#include "SpaceballEvent.h"
#include "View3DInventorRiftViewer.h"
#include "View3DViewerPy.h"
#include "ViewParams.h"
#include "ViewProvider.h"
#include "ViewProviderDocumentObject.h"
#include "ViewProviderLink.h"
#include "NavigationAnimator.h"
#include "NavigationAnimation.h"
#include "Utilities.h"
#include "moc_View3DInventorViewer.cpp"
Classes
class Gui::ViewerEventFilter
class SpaceNavigatorDevice
Macros
#define ZOOM_WIDTH 16
#define ZOOM_HEIGHT 16
#define ZOOM_BYTES ((ZOOM_WIDTH + 7) / 8) * ZOOM_HEIGHT
#define ZOOM_HOT_X 5
#define ZOOM_HOT_Y 7
#define PAN_WIDTH 16
#define PAN_HEIGHT 16
#define PAN_BYTES ((PAN_WIDTH + 7) / 8) * PAN_HEIGHT
#define PAN_HOT_X 7
#define PAN_HOT_Y 7
#define ROTATE_WIDTH 16
#define ROTATE_HEIGHT 16
#define ROTATE_BYTES ((ROTATE_WIDTH + 7) / 8) * ROTATE_HEIGHT
#define ROTATE_HOT_X 6
#define ROTATE_HOT_Y 8
Functions
static QCursor createCursor (QBitmap &bitmap, QBitmap &mask, int hotX, int hotY, double dpr)
SbVec3f projectPointOntoPlane (const SbVec3f &point, const SbPlane &plane)
SbLine projectLineOntoPlane (const SbVec3f &p1, const SbVec3f &p2, const SbPlane &plane)
SbVec3f intersection (const SbVec3f &p11, const SbVec3f &p12, const SbVec3f &p21, const SbVec3f &p22)
Variables
static unsigned char zoom_bitmap [((16+7)/8) *ZOOM_HEIGHT]
static unsigned char zoom_mask_bitmap [((16+7)/8) *ZOOM_HEIGHT]
static unsigned char pan_bitmap [((16+7)/8) *PAN_HEIGHT]
static unsigned char pan_mask_bitmap [((16+7)/8) *PAN_HEIGHT]
static unsigned char rotate_bitmap [((16+7)/8) *ROTATE_HEIGHT]
static unsigned char rotate_mask_bitmap [((16+7)/8) *ROTATE_HEIGHT]
Macro Definition Documentation
PAN_BYTES
#define PAN_BYTES ((PAN_WIDTH + 7) / 8) * PAN_HEIGHT
Definition at line 170 of file View3DInventorViewer.cpp.
PAN_HEIGHT
#define PAN_HEIGHT 16
Definition at line 169 of file View3DInventorViewer.cpp.
PAN_HOT_X
#define PAN_HOT_X 7
Definition at line 171 of file View3DInventorViewer.cpp.
PAN_HOT_Y
#define PAN_HOT_Y 7
Definition at line 172 of file View3DInventorViewer.cpp.
PAN_WIDTH
#define PAN_WIDTH 16
Definition at line 168 of file View3DInventorViewer.cpp.
ROTATE_BYTES
#define ROTATE_BYTES ((ROTATE_WIDTH + 7) / 8) * ROTATE_HEIGHT
Definition at line 194 of file View3DInventorViewer.cpp.
ROTATE_HEIGHT
#define ROTATE_HEIGHT 16
Definition at line 193 of file View3DInventorViewer.cpp.
ROTATE_HOT_X
#define ROTATE_HOT_X 6
Definition at line 195 of file View3DInventorViewer.cpp.
ROTATE_HOT_Y
#define ROTATE_HOT_Y 8
Definition at line 196 of file View3DInventorViewer.cpp.
ROTATE_WIDTH
#define ROTATE_WIDTH 16
Definition at line 192 of file View3DInventorViewer.cpp.
ZOOM_BYTES
#define ZOOM_BYTES ((ZOOM_WIDTH + 7) / 8) * ZOOM_HEIGHT
Definition at line 146 of file View3DInventorViewer.cpp.
ZOOM_HEIGHT
#define ZOOM_HEIGHT 16
Definition at line 145 of file View3DInventorViewer.cpp.
ZOOM_HOT_X
#define ZOOM_HOT_X 5
Definition at line 147 of file View3DInventorViewer.cpp.
ZOOM_HOT_Y
#define ZOOM_HOT_Y 7
Definition at line 148 of file View3DInventorViewer.cpp.
ZOOM_WIDTH
#define ZOOM_WIDTH 16
Definition at line 144 of file View3DInventorViewer.cpp.
Function Documentation
createCursor()
static QCursor createCursor (QBitmap & bitmap, QBitmap & mask, int hotX, int hotY, double dpr) static
Definition at line 662 of file View3DInventorViewer.cpp.
intersection()
SbVec3f intersection (const SbVec3f & p11, const SbVec3f & p12, const SbVec3f & p21, const SbVec3f & p22)
Definition at line 2787 of file View3DInventorViewer.cpp.
References dot(), intersection(), and toolbit-attributes::s.
Referenced by Sketcher::SketchObject::addExternal(), PartDesign::Thickness::execute(), FC_LOG_LEVEL_INIT(), Sketcher::SketchObject::fillet(), MeshCore::MeshRefPointToFacets::GetIndices(), MeshCore::MeshRefFacetToFacets::GetIndices(), MeshCore::MeshEvalSelfIntersection::GetIntersections(), Gui::View3DInventorViewer::getPointOnLine(), intersection(), AdaptivePath::IntersectionPoint(), Part::TopoShape::makeElementOffset(), Part::TopoShape::makeElementOffset2D(), Part::TopoShape::makeElementThickSolid(), Part::TopoShape::makeOffset2D(), Part::TopoShape::makeOffsetShape(), Part::TopoShape::makeThickSolid(), SketcherGui::EditModeConstraintCoinManager::processConstraints(), Sketcher::SketchObject::rebuildExternalGeometry(), and MeshGui::ViewProviderMeshSelfIntersections::showDefects().
projectLineOntoPlane()
SbLine projectLineOntoPlane (const SbVec3f & p1, const SbVec3f & p2, const SbPlane & plane)
Definition at line 2781 of file View3DInventorViewer.cpp.
References WorkingPlane::plane, and projectPointOntoPlane().
Referenced by Gui::View3DInventorViewer::getPointOnLine().
projectPointOntoPlane()
SbVec3f projectPointOntoPlane (const SbVec3f & point, const SbPlane & plane)
Definition at line 2773 of file View3DInventorViewer.cpp.
References WorkingPlane::plane.
Referenced by projectLineOntoPlane().
Variable Documentation
pan_bitmap
unsigned char pan_bitmap[((16+7)/8) *PAN_HEIGHT] static
Initial value:
=
{
    0xc0, 0x03, 0x60, 0x02, 0x20, 0x04, 0x10, 0x08,
    0x68, 0x16, 0x54, 0x2a, 0x73, 0xce, 0x01, 0x80,
    0x01, 0x80, 0x73, 0xce, 0x54, 0x2a, 0x68, 0x16,
    0x10, 0x08, 0x20, 0x04, 0x40, 0x02, 0xc0, 0x03
}
Definition at line 174 of file View3DInventorViewer.cpp.
pan_mask_bitmap
unsigned char pan_mask_bitmap[((16+7)/8) *PAN_HEIGHT] static
Initial value:
=
{
    0xc0, 0x03, 0xe0, 0x03, 0xe0, 0x07, 0xf0, 0x0f,
    0xe8, 0x17, 0xdc, 0x3b, 0xff, 0xff, 0xff, 0xff,
    0xff, 0xff, 0xff, 0xff, 0xdc, 0x3b, 0xe8, 0x17,
    0xf0, 0x0f, 0xe0, 0x07, 0xc0, 0x03, 0xc0, 0x03
}
Definition at line 182 of file View3DInventorViewer.cpp.
rotate_bitmap
unsigned char rotate_bitmap[((16+7)/8) *ROTATE_HEIGHT] static
Initial value:
= {
    0xf0, 0xef, 0x18, 0xb8, 0x0c, 0x90, 0xe4, 0x83,
    0x34, 0x86, 0x1c, 0x83, 0x00, 0x81, 0x00, 0xff,
    0xff, 0x00, 0x81, 0x00, 0xc1, 0x38, 0x61, 0x2c,
    0xc1, 0x27, 0x09, 0x30, 0x1d, 0x18, 0xf7, 0x0f
}
Definition at line 198 of file View3DInventorViewer.cpp.
rotate_mask_bitmap
unsigned char rotate_mask_bitmap[((16+7)/8) *ROTATE_HEIGHT] static
Initial value:
= {
    0xf0, 0xef, 0xf8, 0xff, 0xfc, 0xff, 0xfc, 0xff,
    0x3c, 0xfe, 0x1c, 0xff, 0x00, 0xff, 0x00, 0xff,
    0xff, 0x00, 0xff, 0x00, 0xff, 0x38, 0x7f, 0x3c,
    0xff, 0x3f, 0xff, 0x3f, 0xff, 0x1f, 0xf7, 0x0f
}
Definition at line 205 of file View3DInventorViewer.cpp.
zoom_bitmap
unsigned char zoom_bitmap[((16+7)/8) *ZOOM_HEIGHT] static
Initial value:
=
{
    0x00, 0x0f, 0x80, 0x1c, 0x40, 0x38, 0x20, 0x70,
    0x90, 0xe4, 0xc0, 0xcc, 0xf0, 0xfc, 0x00, 0x0c,
    0x00, 0x0c, 0xf0, 0xfc, 0xc0, 0xcc, 0x90, 0xe4,
    0x20, 0x70, 0x40, 0x38, 0x80, 0x1c, 0x00, 0x0f
}
Definition at line 150 of file View3DInventorViewer.cpp.
zoom_mask_bitmap
unsigned char zoom_mask_bitmap[((16+7)/8) *ZOOM_HEIGHT] static
Initial value:
=
{
    0x00, 0x0f, 0x80, 0x1f, 0xc0, 0x3f, 0xe0, 0x7f,
    0xf0, 0xff, 0xf0, 0xff, 0xf0, 0xff, 0x00, 0x0f,
    0x00, 0x0f, 0xf0, 0xff, 0xf0, 0xff, 0xf0, 0xff,
    0xe0, 0x7f, 0xc0, 0x3f, 0x80, 0x1f, 0x00, 0x0f
}
Definition at line 158 of file View3DInventorViewer.cpp.