FreeCAD: MeshCore::SphereFit Class Reference
MeshCore::SphereFit Class Reference
#include <Approximation.h>
Public Member Functions
SphereFit ()
float GetRadius () const
Base::Vector3f GetCenter () const
float Fit () override
float GetDistanceToSphere (const Base::Vector3f &rcPoint) const
float GetStdDeviation () const
void ProjectToSphere ()
Public Member Functions inherited from MeshCore::Approximation
Approximation ()
virtual ~Approximation ()
void AddPoint (const Base::Vector3f &point)
void AddPoints (const std::vector< Base::Vector3f > &points)
void AddPoints (const std::set< Base::Vector3f > &points)
void AddPoints (const std::list< Base::Vector3f > &points)
void AddPoints (const MeshPointArray &points)
const std::list< Base::Vector3f > & GetPoints () const
Base::Vector3f GetGravity () const
std::size_t CountPoints () const
void Clear ()
float GetLastResult () const
bool Done () const
Additional Inherited Members
Protected Member Functions inherited from MeshCore::Approximation
void GetMgcVectorArray (std::vector< Wm4::Vector3< double >> &rcPts) const
Approximation (const Approximation &)=default
Approximation (Approximation &&)=default
Approximation & operator= (const Approximation &)=default
Approximation & operator= (Approximation &&)=default
Protected Attributes inherited from MeshCore::Approximation
std::list< Base::Vector3f > _vPoints
bool _bIsFitted {false}
float _fLastResult {FLOAT_MAX}
Detailed Description
Approximation of a sphere into a given set of points.
Definition at line 457 of file Approximation.h.
Constructor & Destructor Documentation
SphereFit()
SphereFit::SphereFit ()
Definition at line 1377 of file Approximation.cpp.
Member Function Documentation
Fit()
float SphereFit::Fit () override virtual
Fit a sphere into the given points. If the fit fails FLOAT_MAX is returned.
Implements MeshCore::Approximation.
Definition at line 1399 of file Approximation.cpp.
References MeshCore::Approximation::_bIsFitted, MeshCore::Approximation::_fLastResult, MeshCore::Approximation::_vPoints, MeshCore::Approximation::AddPoints(), Wm4::Sphere3< Real >::Center, exportCSG::center(), MeshCoreFit::SphereFit::ComputeApproximations(), Base::Console(), MeshCore::Approximation::CountPoints(), MeshCoreFit::SphereFit::Fit(), FLOAT_MAX, MeshCoreFit::SphereFit::GetCenter(), MeshCoreFit::SphereFit::GetNumIterations(), MeshCoreFit::SphereFit::GetRadius(), MeshCoreFit::SphereFit::GetStdDeviation(), GetStdDeviation(), Base::ConsoleSingleton::Message(), Wm4::Sphere3< Real >::Radius, result, Wm4::SphereFit3< double >(), TestSpreadsheet::v, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by MeshCore::SphereSurfaceFit::Fit(), MeshGui::SphereFitParameter::getParameter(), and ReverseEngineeringGui::SegmentationManual::onSphereDetectClicked().
GetCenter()
Base::Vector3f SphereFit::GetCenter () const
Definition at line 1390 of file Approximation.cpp.
References MeshCore::Approximation::_bIsFitted.
Referenced by MeshCore::SphereSurfaceFit::Fit(), MeshGui::SphereFitParameter::getParameter(), ReverseEngineeringGui::SegmentationManual::onSphereDetectClicked(), and MeshCore::SphereSurfaceFit::Parameters().
GetDistanceToSphere()
float SphereFit::GetDistanceToSphere (const Base::Vector3f & rcPoint) const
Returns the distance from the point rcPoint to the fitted sphere. If Fit() has not been called FLOAT_MAX is returned.
Definition at line 1456 of file Approximation.cpp.
References MeshCore::Approximation::_bIsFitted, FLOAT_MAX, and Base::Vector3< float_type >::Length().
Referenced by GetStdDeviation().
GetRadius()
float SphereFit::GetRadius () const
Definition at line 1381 of file Approximation.cpp.
References MeshCore::Approximation::_bIsFitted, and FLOAT_MAX.
Referenced by MeshCore::SphereSurfaceFit::Fit(), MeshGui::SphereFitParameter::getParameter(), ReverseEngineeringGui::SegmentationManual::onSphereDetectClicked(), and MeshCore::SphereSurfaceFit::Parameters().
GetStdDeviation()
float SphereFit::GetStdDeviation () const
Returns the standard deviation from the points to the fitted sphere. If Fit() has not been called FLOAT_MAX is returned.
Definition at line 1465 of file Approximation.cpp.
References MeshCore::Approximation::_bIsFitted, MeshCore::Approximation::_vPoints, MeshCore::Approximation::CountPoints(), FLOAT_MAX, GetDistanceToSphere(), and KDL::sqrt().
Referenced by Fit().
ProjectToSphere()
void SphereFit::ProjectToSphere ()
Projects the points onto the fitted sphere.
Definition at line 1490 of file Approximation.cpp.
References MeshCore::Approximation::_vPoints, and KDL::diff().
The documentation for this class was generated from the following files:
Approximation.h
Approximation.cpp