FreeCAD: draftguitools.gui_hyperlink.Draft_Hyperlink Class Reference
draftguitools.gui_hyperlink.Draft_Hyperlink Class Reference
DRAFT » draftguitools
Public Member Functions
def GetResources (self)
def Activated (self)
def find_hyperlinks (self)
def has_hyperlinks (self)
def open_hyperlink (self, hyperlink)
Public Attributes
hyperlinks_list
Detailed Description
The Draft_Hyperlink FreeCAD command definition.
Definition at line 52 of file gui_hyperlink.py.
Member Function Documentation
Activated()
def draftguitools.gui_hyperlink.Draft_Hyperlink.Activated (self)
Definition at line 62 of file gui_hyperlink.py.
References draftguitools.gui_hyperlink.Draft_Hyperlink.find_hyperlinks(), draftguitools.gui_hyperlink.Draft_Hyperlink.hyperlinks_list, and draftguitools.gui_hyperlink.Draft_Hyperlink.open_hyperlink().
find_hyperlinks()
def draftguitools.gui_hyperlink.Draft_Hyperlink.find_hyperlinks (self)
Definition at line 88 of file gui_hyperlink.py.
Referenced by draftguitools.gui_hyperlink.Draft_Hyperlink.Activated(), and draftguitools.gui_hyperlink.Draft_Hyperlink.has_hyperlinks().
GetResources()
def draftguitools.gui_hyperlink.Draft_Hyperlink.GetResources (self)
Definition at line 55 of file gui_hyperlink.py.
References draftguitools.gui_hyperlink.QT_TRANSLATE_NOOP().
has_hyperlinks()
def draftguitools.gui_hyperlink.Draft_Hyperlink.has_hyperlinks (self)
Definition at line 100 of file gui_hyperlink.py.
References draftguitools.gui_hyperlink.Draft_Hyperlink.find_hyperlinks(), and draftguitools.gui_hyperlink.Draft_Hyperlink.hyperlinks_list.
open_hyperlink()
def draftguitools.gui_hyperlink.Draft_Hyperlink.open_hyperlink (self, hyperlink)
Definition at line 105 of file gui_hyperlink.py.
Referenced by draftguitools.gui_hyperlink.Draft_Hyperlink.Activated().
Member Data Documentation
hyperlinks_list
draftguitools.gui_hyperlink.Draft_Hyperlink.hyperlinks_list
Definition at line 89 of file gui_hyperlink.py.
Referenced by draftguitools.gui_hyperlink.Draft_Hyperlink.Activated(), and draftguitools.gui_hyperlink.Draft_Hyperlink.has_hyperlinks().
The documentation for this class was generated from the following file:
gui_hyperlink.py