FreeCAD: ifc2x3.ifccurrencyrelationship Class Reference
ifc2x3.ifccurrencyrelationship Class Reference
Public Member Functions
def __init__ (self, relatingmonetaryunit, relatedmonetaryunit, exchangerate, ratedatetime, ratesource)
def relatingmonetaryunit ()
def relatedmonetaryunit ()
def exchangerate ()
def ratedatetime ()
def ratesource ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
relatingmonetaryunit
relatedmonetaryunit
exchangerate
ratedatetime
ratesource
Detailed Description
Entity ifccurrencyrelationship definition.
:param relatingmonetaryunit
:type relatingmonetaryunit:ifcmonetaryunit
:param relatedmonetaryunit
:type relatedmonetaryunit:ifcmonetaryunit
:param exchangerate
:type exchangerate:ifcpositiveratiomeasure
:param ratedatetime
:type ratedatetime:ifcdateandtime
:param ratesource
:type ratesource:ifclibraryinformation
Definition at line 4780 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifccurrencyrelationship.__init__ (self, relatingmonetaryunit, relatedmonetaryunit, exchangerate, ratedatetime, ratesource)
Definition at line 4798 of file ifc2x3.py.
Member Function Documentation
exchangerate()
def ifc2x3.ifccurrencyrelationship.exchangerate ()
Definition at line 4834 of file ifc2x3.py.
References ifc2x3.ifccurrencyrelationship._exchangerate, SCL.TypeChecker.check_type(), and ifc2x3.ifccurrencyrelationship.exchangerate.
ratedatetime()
def ifc2x3.ifccurrencyrelationship.ratedatetime ()
Definition at line 4848 of file ifc2x3.py.
References ifc2x3.ifccurrencyrelationship._ratedatetime, SCL.TypeChecker.check_type(), and ifc2x3.ifccurrencyrelationship.ratedatetime.
ratesource()
def ifc2x3.ifccurrencyrelationship.ratesource ()
Definition at line 4862 of file ifc2x3.py.
References ifc2x3.ifccurrencyrelationship._ratesource, SCL.TypeChecker.check_type(), and ifc2x3.ifccurrencyrelationship.ratesource.
relatedmonetaryunit()
def ifc2x3.ifccurrencyrelationship.relatedmonetaryunit ()
Definition at line 4820 of file ifc2x3.py.
References ifc2x3.ifccurrencyrelationship._relatedmonetaryunit, SCL.TypeChecker.check_type(), and ifc2x3.ifccurrencyrelationship.relatedmonetaryunit.
relatingmonetaryunit()
def ifc2x3.ifccurrencyrelationship.relatingmonetaryunit ()
Definition at line 4806 of file ifc2x3.py.
References ifc2x3.ifccurrencyrelationship._relatingmonetaryunit, SCL.TypeChecker.check_type(), and ifc2x3.ifccurrencyrelationship.relatingmonetaryunit.
Member Data Documentation
exchangerate
ifc2x3.ifccurrencyrelationship.exchangerate
Definition at line 4801 of file ifc2x3.py.
Referenced by ifc2x3.ifccurrencyrelationship.exchangerate().
ratedatetime
ifc2x3.ifccurrencyrelationship.ratedatetime
Definition at line 4802 of file ifc2x3.py.
Referenced by ifc2x3.ifccurrencyrelationship.ratedatetime().
ratesource
ifc2x3.ifccurrencyrelationship.ratesource
Definition at line 4803 of file ifc2x3.py.
Referenced by ifc2x3.ifccurrencyrelationship.ratesource().
relatedmonetaryunit
ifc2x3.ifccurrencyrelationship.relatedmonetaryunit
Definition at line 4800 of file ifc2x3.py.
Referenced by ifc2x3.ifccurrencyrelationship.relatedmonetaryunit().
relatingmonetaryunit
ifc2x3.ifccurrencyrelationship.relatingmonetaryunit
Definition at line 4799 of file ifc2x3.py.
Referenced by ifc2x3.ifccurrencyrelationship.relatingmonetaryunit().
The documentation for this class was generated from the following file:
ifc2x3.py