FreeCAD: Gui::Action Class Reference
Gui::Action Class Reference
#include <Action.h>
Public Slots
virtual void onActivated ()
virtual void onToggled (bool)
Public Member Functions
Action (Command *pcCmd, QObject *parent=nullptr)
Action (Command *pcCmd, QAction *action, QObject *parent)
Action takes ownership of the 'action' object.
~Action () override
virtual void addTo (QWidget *widget)
virtual void setEnabled (bool)
virtual void setVisible (bool)
void setCheckable (bool)
void setChecked (bool, bool no_signal=false)
bool isChecked () const
bool isEnabled () const
void setShortcut (const QString &)
QKeySequence shortcut () const
void setIcon (const QIcon &)
QIcon icon () const
void setStatusTip (const QString &)
QString statusTip () const
void setText (const QString &)
QString text () const
void setToolTip (const QString &, const QString &title=QString())
QString toolTip () const
void setWhatsThis (const QString &)
QString whatsThis () const
void setMenuRole (QAction::MenuRole menuRole)
QAction * action () const
Command * command () const
Static Public Member Functions
static QString createToolTip (QString helpText, const QString &title, const QFont &font, const QString &shortCut, const Command *command=nullptr)
static QString commandToolTip (const Command *cmd, bool richFormat=true)
static QString commandMenuText (const Command *cmd)
static QString cleanTitle (const QString &title)
Clean the title by stripping the mnemonic symbol '&' and ending punctuation.
Detailed Description
The Action class is the link between Qt's QAction class and FreeCAD's command classes (Command). So, it is possible to have all actions (from toolbars, menus, ...) implemented in classes instead of many slot methods in the class MainWindow.
Author
Werner Mayer
Definition at line 65 of file Action.h.
Constructor & Destructor Documentation
Action() [1/2]
Action::Action (Command * pcCmd, QObject * parent = nullptr) explicit
Constructs an action called name with parent parent. It also stores a pointer to the command object.
Definition at line 74 of file Action.cpp.
References draftgeoutils.intersections::connect(), Gui::Command::getName(), and onActivated().
Action() [2/2]
Action::Action (Command * pcCmd, QAction * action, QObject * parent)
Action takes ownership of the 'action' object.
Definition at line 83 of file Action.cpp.
References draftgeoutils.intersections::connect(), Gui::Command::getName(), and onActivated().
~Action()
Action::~Action () override
Definition at line 93 of file Action.cpp.
Member Function Documentation
action()
QAction* Gui::Action::action () const inline
Definition at line 97 of file Action.h.
Referenced by Gui::ActionGroup::addAction(), Gui::ActionGroup::addTo(), Gui::WorkbenchGroup::addTo(), Gui::UndoAction::addTo(), Gui::RedoAction::addTo(), Gui::DockWidgetAction::addTo(), Gui::ToolBarAction::addTo(), Gui::WindowAction::addTo(), commandMenuText(), commandToolTip(), Gui::WorkbenchGroup::onWorkbenchActivated(), Gui::WorkbenchGroup::refreshWorkbenchList(), Gui::Command::setupCheckable(), Gui::WorkbenchComboBox::WorkbenchComboBox(), and Gui::WorkbenchTabWidget::WorkbenchTabWidget().
addTo()
void Action::addTo (QWidget * widget) virtual
Adds this action to widget widget.
Reimplemented in Gui::WindowAction, Gui::ToolBarAction, Gui::DockWidgetAction, Gui::RedoAction, Gui::UndoAction, Gui::WorkbenchGroup, and Gui::ActionGroup.
Definition at line 101 of file Action.cpp.
Referenced by Gui::Command::addTo(), src.Mod.PartDesign.WizardShaft.Shaft.Shaft::equilibrium(), FemGui::TaskPostClip::TaskPostClip(), and FemGui::TaskPostCut::TaskPostCut().
cleanTitle()
QString Action::cleanTitle (const QString & title) static
Clean the title by stripping the mnemonic symbol '&' and ending punctuation.
Definition at line 230 of file Action.cpp.
References src.Mod.AddonManager.addonmanager_devmode_license_selector::QRegularExpression, text(), and Plot::title().
Referenced by commandMenuText(), createToolTip(), and Gui::Dialog::DlgCustomKeyboardImp::populatePriorityList().
command()
Command* Gui::Action::command () const inline
Definition at line 123 of file Action.h.
References ArchCommands::check(), Init::parent, and src.Mod.AddonManager.addonmanager_pyside_interface::QObject.
Referenced by createToolTip(), onActivated(), Gui::ActionGroup::onActivated(), onToggled(), and setToolTip().
commandMenuText()
QString Action::commandMenuText (const Command * cmd) static
Obtain the menu text of a given command
Parameters
cmd input command
Returns
Return the command menu text that is stripped with its mnemonic symbol '&' and ending punctuation
Definition at line 281 of file Action.cpp.
References action(), Gui::CommandBase::className(), cleanTitle(), Gui::CommandBase::getAction(), Gui::CommandBase::getMenuText(), Gui::Command::getName(), Plot::title(), and create_qrc::txt.
Referenced by Gui::Dialog::DlgCustomToolbars::onModifyMacroAction(), and Gui::Dialog::DlgCustomKeyboardImp::populateCommandList().
commandToolTip()
QString Action::commandToolTip (const Command * cmd, bool richFormat = true) static
Obtain tool tip of a given command
Parameters
cmd input command
richFormat whether to output rich text formatted tooltip
Definition at line 246 of file Action.cpp.
References action(), Gui::CommandBase::className(), createToolTip(), Gui::CommandBase::getAction(), Gui::CommandBase::getMenuText(), Gui::Command::getShortcut(), Gui::CommandBase::getToolTipText(), Plot::title(), CommandInsertLink::tooltip, and create_qrc::txt.
Referenced by Gui::Dialog::DlgCustomToolbars::onModifyMacroAction(), and Gui::Dialog::DlgCustomKeyboardImp::populateCommandList().
createToolTip()
QString Action::createToolTip (QString helpText, const QString & title, const QFont & font, const QString & shortCut, const Command * command = nullptr) static
Definition at line 309 of file Action.cpp.
References cleanTitle(), command(), Gui::CommandBase::getAction(), Gui::Command::getName(), Gui::QtTools::horizontalAdvance(), SplineSurface::i, shortcut(), Plot::title(), and CommandInsertLink::tooltip.
Referenced by commandToolTip(), and setToolTip().
icon()
QIcon Action::icon () const
Definition at line 191 of file Action.cpp.
Referenced by setIcon().
isChecked()
bool Action::isChecked () const
Definition at line 152 of file Action.cpp.
Referenced by draftguitools.gui_snaps.Draft_Snap_Lock::GetResources(), draftguitools.gui_snaps.Draft_Snap_Midpoint::GetResources(), draftguitools.gui_snaps.Draft_Snap_Perpendicular::GetResources(), draftguitools.gui_snaps.Draft_Snap_Grid::GetResources(), draftguitools.gui_snaps.Draft_Snap_Intersection::GetResources(), draftguitools.gui_snaps.Draft_Snap_Parallel::GetResources(), draftguitools.gui_snaps.Draft_Snap_Endpoint::GetResources(), draftguitools.gui_snaps.Draft_Snap_Angle::GetResources(), draftguitools.gui_snaps.Draft_Snap_Center::GetResources(), draftguitools.gui_snaps.Draft_Snap_Extension::GetResources(), draftguitools.gui_snaps.Draft_Snap_Near::GetResources(), draftguitools.gui_snaps.Draft_Snap_Ortho::GetResources(), draftguitools.gui_snaps.Draft_Snap_Special::GetResources(), draftguitools.gui_snaps.Draft_Snap_Dimensions::GetResources(), draftguitools.gui_snaps.Draft_Snap_WorkingPlane::GetResources(), NaviCubeDraggableCmd::isActive(), StdCmdAxisCross::isActive(), StdCmdSelBoundingBox::isActive(), StdCmdDockOverlayMouseTransparent::isActive(), and Gui::Command::setupCheckable().
isEnabled()
bool Action::isEnabled () const
Definition at line 165 of file Action.cpp.
Referenced by draftguitools.gui_snapper.Snapper::setArchDims(), draftguitools.gui_snapper.Snapper::snapToAngles(), draftguitools.gui_snapper.Snapper::snapToCenter(), draftguitools.gui_snapper.Snapper::snapToCenterFace(), draftguitools.gui_snapper.Snapper::snapToCrossExtensions(), draftguitools.gui_snapper.Snapper::snapToDim(), draftguitools.gui_snapper.Snapper::snapToElines(), draftguitools.gui_snapper.Snapper::snapToEndpoints(), draftguitools.gui_snapper.Snapper::snapToExtensions(), draftguitools.gui_snapper.Snapper::snapToExtOrtho(), draftguitools.gui_snapper.Snapper::snapToExtPerpendicular(), draftguitools.gui_snapper.Snapper::snapToGrid(), draftguitools.gui_snapper.Snapper::snapToHold(), draftguitools.gui_snapper.Snapper::snapToIntersection(), draftguitools.gui_snapper.Snapper::snapToMidpoint(), draftguitools.gui_snapper.Snapper::snapToNear(), draftguitools.gui_snapper.Snapper::snapToNearFace(), draftguitools.gui_snapper.Snapper::snapToNearUnprojected(), draftguitools.gui_snapper.Snapper::snapToObject(), draftguitools.gui_snapper.Snapper::snapToOrtho(), draftguitools.gui_snapper.Snapper::snapToPerpendicular(), draftguitools.gui_snapper.Snapper::snapToPerpendicularFace(), draftguitools.gui_snapper.Snapper::snapToPolar(), draftguitools.gui_snapper.Snapper::snapToPolygon(), draftguitools.gui_snapper.Snapper::snapToSpecials(), draftguitools.gui_snapper.Snapper::snapToVertex(), and draftguitools.gui_snapper.Snapper::toWP().
onActivated
void Action::onActivated () virtual slot
Activates the command.
Definition at line 109 of file Action.cpp.
References command(), Gui::Command::invoke(), and Gui::Command::TriggerAction.
Referenced by Action(), Gui::RedoAction::RedoAction(), setCheckable(), and Gui::UndoAction::UndoAction().
onToggled
void Action::onToggled (bool toggle) virtual slot
Sets whether the command is toggled.
Definition at line 117 of file Action.cpp.
References command(), Gui::Command::invoke(), and Gui::Command::TriggerAction.
Referenced by setCheckable().
setCheckable()
void Action::setCheckable (bool check)
Definition at line 122 of file Action.cpp.
References ArchCommands::check(), draftgeoutils.intersections::connect(), onActivated(), and onToggled().
Referenced by Gui::Command::addToGroup(), Gui::StdCmdDescription::createAction(), StdOrthographicCamera::createAction(), StdPerspectiveCamera::createAction(), StdCmdStatusBar::createAction(), Gui::PythonCommand::createAction(), NaviCubeDraggableCmd::createAction(), StdCmdSelBoundingBox::createAction(), StdCmdDockOverlayMouseTransparent::createAction(), and Gui::Command::setupCheckable().
setChecked()
void Action::setChecked (bool check, bool no_signal = false)
Definition at line 140 of file Action.cpp.
References ArchCommands::check().
Referenced by StdCmdSelBoundingBox::activated(), StdCmdDockOverlayMouseTransparent::activated(), StdCmdStatusBar::createAction(), Gui::PythonCommand::createAction(), FilterStatusBar::eventFilter(), StdCmdStatusBar::isActive(), NaviCubeDraggableCmd::isActive(), StdCmdAxisCross::isActive(), StdCmdSelBoundingBox::isActive(), StdCmdDockOverlayMouseTransparent::isActive(), and Gui::Command::setupCheckable().
setEnabled()
void Action::setEnabled (bool enable) virtual
Sets whether the action is enabled.
Reimplemented in Gui::RedoAction, Gui::UndoAction, and Gui::ActionGroup.
Definition at line 160 of file Action.cpp.
Referenced by Gui::ActionGroup::setDisabled(), Gui::ActionGroup::setEnabled(), Gui::UndoAction::setEnabled(), Gui::Command::setEnabled(), Gui::RedoAction::setEnabled(), Path.Dressup.Gui.Tags.HoldingTagMarker::setSelected(), and Gui::Command::testActive().
setIcon()
void Action::setIcon (const QIcon & icon)
Definition at line 186 of file Action.cpp.
References icon().
Referenced by StdCmdWorkbench::createAction(), Gui::StdCmdDownloadOnlineHelp::createAction(), StdCmdAbout::createAction(), Gui::Command::createAction(), Gui::PythonCommand::createAction(), Gui::MacroCommand::createAction(), StdCmdUndo::createAction(), StdCmdRedo::createAction(), StdCmdDockOverlayMouseTransparent::createAction(), Gui::ActionGroup::onActivated(), Gui::ActionGroup::setCheckedAction(), Gui::GroupCommand::setup(), CmdSketcherCompCreateArc::updateAction(), CmdSketcherCompCreateConic::updateAction(), CmdSketcherCompExternal::updateAction(), CmdSketcherCompSlot::updateAction(), CmdSketcherConstrainLock::updateAction(), CmdSketcherConstrainDistance::updateAction(), CmdSketcherConstrainDistanceX::updateAction(), CmdSketcherConstrainDistanceY::updateAction(), CmdSketcherConstrainRadius::updateAction(), CmdSketcherConstrainDiameter::updateAction(), CmdSketcherConstrainRadiam::updateAction(), and CmdSketcherConstrainAngle::updateAction().
setMenuRole()
void Action::setMenuRole (QAction::MenuRole menuRole)
Definition at line 421 of file Action.cpp.
Referenced by StdCmdAbout::createAction(), and StdCmdDlgPreferences::createAction().
setShortcut()
void Action::setShortcut (const QString & key)
Definition at line 175 of file Action.cpp.
References setToolTip().
Referenced by StdCmdWorkbench::createAction(), Gui::StdCmdDownloadOnlineHelp::createAction(), StdCmdAbout::createAction(), StdCmdUndo::createAction(), StdCmdRedo::createAction(), and Gui::Command::setShortcut().
setStatusTip()
void Action::setStatusTip (const QString & text)
Definition at line 196 of file Action.cpp.
Referenced by Gui::StdCmdDownloadOnlineHelp::createAction(), StdCmdAbout::createAction(), Gui::MacroCommand::createAction(), Gui::StdCmdDownloadOnlineHelp::languageChange(), and Gui::GroupCommand::setup().
setText()
void Action::setText (const QString & text)
Definition at line 206 of file Action.cpp.
References setToolTip().
Referenced by Gui::StdCmdDownloadOnlineHelp::activated(), Gui::StdCmdDownloadOnlineHelp::createAction(), StdCmdAbout::createAction(), Gui::MacroCommand::createAction(), Gui::StdCmdDownloadOnlineHelp::languageChange(), src.Mod.AddonManager.Widgets.addonmanager_widget_readme_browser.WidgetReadmeBrowser::setMarkdown(), and Gui::GroupCommand::setup().
setToolTip()
void Action::setToolTip (const QString & text, const QString & title = QString())
Definition at line 219 of file Action.cpp.
References command(), createToolTip(), text(), and Plot::title().
Referenced by Gui::StdCmdDownloadOnlineHelp::createAction(), StdCmdAbout::createAction(), Gui::MacroCommand::createAction(), Gui::StdCmdDownloadOnlineHelp::languageChange(), Gui::ActionGroup::onActivated(), Gui::ActionGroup::setCheckedAction(), setShortcut(), setText(), and Gui::GroupCommand::setup().
setVisible()
void Action::setVisible (bool visible) virtual
Reimplemented in Gui::RedoAction, Gui::UndoAction, and Gui::ActionGroup.
Definition at line 170 of file Action.cpp.
Referenced by Gui::ActionGroup::setVisible(), Gui::UndoAction::setVisible(), and Gui::RedoAction::setVisible().
setWhatsThis()
void Action::setWhatsThis (const QString & text)
Definition at line 411 of file Action.cpp.
Referenced by Gui::StdCmdDownloadOnlineHelp::createAction(), StdCmdAbout::createAction(), Gui::MacroCommand::createAction(), and Gui::StdCmdDownloadOnlineHelp::languageChange().
shortcut()
QKeySequence Action::shortcut () const
Definition at line 181 of file Action.cpp.
Referenced by createToolTip(), Path.Dressup.Gui.Dragknife.ObjectDressup::execute(), Gui::Command::getShortcut(), and Gui::Dialog::DlgCustomKeyboardImp::onEditShortcutTextChanged().
statusTip()
QString Action::statusTip () const
Definition at line 201 of file Action.cpp.
Referenced by Gui::MacroCommand::createAction().
text()
QString Action::text () const
Definition at line 214 of file Action.cpp.
Referenced by Gui::ActionGroup::addTo(), Gui::WorkbenchGroup::addTo(), cleanTitle(), and setToolTip().
toolTip()
QString Action::toolTip () const
Definition at line 406 of file Action.cpp.
Referenced by Gui::MacroCommand::createAction(), Gui::WorkbenchComboBox::WorkbenchComboBox(), and Gui::WorkbenchTabWidget::WorkbenchTabWidget().
whatsThis()
QString Action::whatsThis () const
Definition at line 416 of file Action.cpp.
The documentation for this class was generated from the following files:
Action.h
Action.cpp