FreeCAD: GCS::System Class Reference
GCS::System Class Reference
#include <GCS.h>
Public Member Functions
System ()
~System ()
void clear ()
void clearByTag (int tagId)
int addConstraint (Constraint *constr)
void removeConstraint (Constraint *constr)
int addConstraintEqual (double *param1, double *param2, int tagId=0, bool driving=true, Constraint::Alignment internalalignment=Constraint::Alignment::NoInternalAlignment)
int addConstraintProportional (double *param1, double *param2, double ratio, int tagId, bool driving=true)
int addConstraintDifference (double *param1, double *param2, double *difference, int tagId=0, bool driving=true)
int addConstraintP2PDistance (Point &p1, Point &p2, double *distance, int tagId=0, bool driving=true)
int addConstraintP2PAngle (Point &p1, Point &p2, double *angle, double incrAngle, int tagId=0, bool driving=true)
int addConstraintP2PAngle (Point &p1, Point &p2, double *angle, int tagId=0, bool driving=true)
int addConstraintP2LDistance (Point &p, Line &l, double *distance, int tagId=0, bool driving=true)
int addConstraintPointOnLine (Point &p, Line &l, int tagId=0, bool driving=true)
int addConstraintPointOnLine (Point &p, Point &lp1, Point &lp2, int tagId=0, bool driving=true)
int addConstraintPointOnPerpBisector (Point &p, Line &l, int tagId=0, bool driving=true)
int addConstraintPointOnPerpBisector (Point &p, Point &lp1, Point &lp2, int tagId=0, bool driving=true)
int addConstraintParallel (Line &l1, Line &l2, int tagId=0, bool driving=true)
int addConstraintPerpendicular (Line &l1, Line &l2, int tagId=0, bool driving=true)
int addConstraintPerpendicular (Point &l1p1, Point &l1p2, Point &l2p1, Point &l2p2, int tagId=0, bool driving=true)
int addConstraintL2LAngle (Line &l1, Line &l2, double *angle, int tagId=0, bool driving=true)
int addConstraintL2LAngle (Point &l1p1, Point &l1p2, Point &l2p1, Point &l2p2, double *angle, int tagId=0, bool driving=true)
int addConstraintAngleViaPoint (Curve &crv1, Curve &crv2, Point &p, double *angle, int tagId=0, bool driving=true)
int addConstraintAngleViaTwoPoints (Curve &crv1, Curve &crv2, Point &p1, Point &p2, double *angle, int tagId=0, bool driving=true)
int addConstraintAngleViaPointAndParam (Curve &crv1, Curve &crv2, Point &p, double *cparam, double *angle, int tagId=0, bool driving=true)
int addConstraintAngleViaPointAndTwoParams (Curve &crv1, Curve &crv2, Point &p, double *cparam1, double *cparam2, double *angle, int tagId=0, bool driving=true)
int addConstraintMidpointOnLine (Line &l1, Line &l2, int tagId=0, bool driving=true)
int addConstraintMidpointOnLine (Point &l1p1, Point &l1p2, Point &l2p1, Point &l2p2, int tagId=0, bool driving=true)
int addConstraintTangentCircumf (Point &p1, Point &p2, double *rd1, double *rd2, bool internal=false, int tagId=0, bool driving=true)
int addConstraintTangentAtBSplineKnot (BSpline &b, Line &l, unsigned int knotindex, int tagId=0, bool driving=true)
int addConstraintP2PCoincident (Point &p1, Point &p2, int tagId=0, bool driving=true)
int addConstraintHorizontal (Line &l, int tagId=0, bool driving=true)
int addConstraintHorizontal (Point &p1, Point &p2, int tagId=0, bool driving=true)
int addConstraintVertical (Line &l, int tagId=0, bool driving=true)
int addConstraintVertical (Point &p1, Point &p2, int tagId=0, bool driving=true)
int addConstraintCoordinateX (Point &p, double *x, int tagId=0, bool driving=true)
int addConstraintCoordinateY (Point &p, double *y, int tagId=0, bool driving=true)
int addConstraintArcRules (Arc &a, int tagId=0, bool driving=true)
int addConstraintPointOnCircle (Point &p, Circle &c, int tagId=0, bool driving=true)
int addConstraintPointOnEllipse (Point &p, Ellipse &e, int tagId=0, bool driving=true)
int addConstraintPointOnHyperbolicArc (Point &p, ArcOfHyperbola &e, int tagId=0, bool driving=true)
int addConstraintPointOnParabolicArc (Point &p, ArcOfParabola &e, int tagId=0, bool driving=true)
int addConstraintPointOnBSpline (Point &p, BSpline &b, double *pointparam, int tagId, bool driving=true)
int addConstraintArcOfEllipseRules (ArcOfEllipse &a, int tagId=0, bool driving=true)
int addConstraintCurveValue (Point &p, Curve &a, double *u, int tagId=0, bool driving=true)
int addConstraintArcOfHyperbolaRules (ArcOfHyperbola &a, int tagId=0, bool driving=true)
int addConstraintArcOfParabolaRules (ArcOfParabola &a, int tagId=0, bool driving=true)
int addConstraintPointOnArc (Point &p, Arc &a, int tagId=0, bool driving=true)
int addConstraintPerpendicularLine2Arc (Point &p1, Point &p2, Arc &a, int tagId=0, bool driving=true)
int addConstraintPerpendicularArc2Line (Arc &a, Point &p1, Point &p2, int tagId=0, bool driving=true)
int addConstraintPerpendicularCircle2Arc (Point &center, double *radius, Arc &a, int tagId=0, bool driving=true)
int addConstraintPerpendicularArc2Circle (Arc &a, Point &center, double *radius, int tagId=0, bool driving=true)
int addConstraintPerpendicularArc2Arc (Arc &a1, bool reverse1, Arc &a2, bool reverse2, int tagId=0, bool driving=true)
int addConstraintTangent (Line &l, Circle &c, int tagId=0, bool driving=true)
int addConstraintTangent (Line &l, Ellipse &e, int tagId=0, bool driving=true)
int addConstraintTangent (Line &l, Arc &a, int tagId=0, bool driving=true)
int addConstraintTangent (Circle &c1, Circle &c2, int tagId=0, bool driving=true)
int addConstraintTangent (Arc &a1, Arc &a2, int tagId=0, bool driving=true)
int addConstraintTangent (Circle &c, Arc &a, int tagId=0, bool driving=true)
int addConstraintCircleRadius (Circle &c, double *radius, int tagId=0, bool driving=true)
int addConstraintArcRadius (Arc &a, double *radius, int tagId=0, bool driving=true)
int addConstraintCircleDiameter (Circle &c, double *diameter, int tagId=0, bool driving=true)
int addConstraintArcDiameter (Arc &a, double *diameter, int tagId=0, bool driving=true)
int addConstraintEqualLength (Line &l1, Line &l2, int tagId=0, bool driving=true)
int addConstraintEqualRadius (Circle &c1, Circle &c2, int tagId=0, bool driving=true)
int addConstraintEqualRadii (Ellipse &e1, Ellipse &e2, int tagId=0, bool driving=true)
int addConstraintEqualRadii (ArcOfHyperbola &a1, ArcOfHyperbola &a2, int tagId=0, bool driving=true)
int addConstraintEqualRadius (Circle &c1, Arc &a2, int tagId=0, bool driving=true)
int addConstraintEqualRadius (Arc &a1, Arc &a2, int tagId=0, bool driving=true)
int addConstraintEqualFocus (ArcOfParabola &a1, ArcOfParabola &a2, int tagId=0, bool driving=true)
int addConstraintP2PSymmetric (Point &p1, Point &p2, Line &l, int tagId=0, bool driving=true)
int addConstraintP2PSymmetric (Point &p1, Point &p2, Point &p, int tagId=0, bool driving=true)
int addConstraintSnellsLaw (Curve &ray1, Curve &ray2, Curve &boundary, Point p, double *n1, double *n2, bool flipn1, bool flipn2, int tagId, bool driving=true)
int addConstraintC2CDistance (Circle &c1, Circle &c2, double *dist, int tagId, bool driving=true)
int addConstraintC2LDistance (Circle &c, Line &l, double *dist, int tagId, bool driving=true)
int addConstraintP2CDistance (Point &p, Circle &c, double *distance, int tagId=0, bool driving=true)
int addConstraintArcLength (Arc &a, double *dist, int tagId, bool driving=true)
int addConstraintInternalAlignmentPoint2Ellipse (Ellipse &e, Point &p1, InternalAlignmentType alignmentType, int tagId=0, bool driving=true)
int addConstraintInternalAlignmentEllipseMajorDiameter (Ellipse &e, Point &p1, Point &p2, int tagId=0, bool driving=true)
int addConstraintInternalAlignmentEllipseMinorDiameter (Ellipse &e, Point &p1, Point &p2, int tagId=0, bool driving=true)
int addConstraintInternalAlignmentEllipseFocus1 (Ellipse &e, Point &p1, int tagId=0, bool driving=true)
int addConstraintInternalAlignmentEllipseFocus2 (Ellipse &e, Point &p1, int tagId=0, bool driving=true)
int addConstraintInternalAlignmentPoint2Hyperbola (Hyperbola &e, Point &p1, InternalAlignmentType alignmentType, int tagId=0, bool driving=true)
int addConstraintInternalAlignmentHyperbolaMajorDiameter (Hyperbola &e, Point &p1, Point &p2, int tagId=0, bool driving=true)
int addConstraintInternalAlignmentHyperbolaMinorDiameter (Hyperbola &e, Point &p1, Point &p2, int tagId=0, bool driving=true)
int addConstraintInternalAlignmentHyperbolaFocus (Hyperbola &e, Point &p1, int tagId=0, bool driving=true)
int addConstraintInternalAlignmentParabolaFocus (Parabola &e, Point &p1, int tagId=0, bool driving=true)
int addConstraintInternalAlignmentBSplineControlPoint (BSpline &b, Circle &c, unsigned int poleindex, int tag=0, bool driving=true)
int addConstraintInternalAlignmentKnotPoint (BSpline &b, Point &p, unsigned int knotindex, int tagId=0, bool driving=true)
double calculateAngleViaPoint (const Curve &crv1, const Curve &crv2, Point &p) const
double calculateAngleViaPoint (const Curve &crv1, const Curve &crv2, Point &p1, Point &p2) const
double calculateAngleViaParams (const Curve &crv1, const Curve &crv2, double *param1, double *param2) const
void calculateNormalAtPoint (const Curve &crv, const Point &p, double &rtnX, double &rtnY) const
double calculateConstraintErrorByTag (int tagId)
void rescaleConstraint (int id, double coeff)
void declareUnknowns (VEC_pD &params)
void declareDrivenParams (VEC_pD &params)
void initSolution (Algorithm alg=DogLeg)
int solve (bool isFine=true, Algorithm alg=DogLeg, bool isRedundantsolving=false)
int solve (VEC_pD &params, bool isFine=true, Algorithm alg=DogLeg, bool isRedundantsolving=false)
int solve (SubSystem *subsys, bool isFine=true, Algorithm alg=DogLeg, bool isRedundantsolving=false)
int solve (SubSystem *subsysA, SubSystem *subsysB, bool isFine=true, bool isRedundantsolving=false)
void applySolution ()
void undoSolution ()
double getFinePrecision ()
int diagnose (Algorithm alg=DogLeg)
int dofsNumber () const
void getConflicting (VEC_I &conflictingOut) const
void getRedundant (VEC_I &redundantOut) const
void getPartiallyRedundant (VEC_I &partiallyredundantOut) const
void getDependentParams (VEC_pD &pdependentparameterlist) const
void getDependentParamsGroups (std::vector< std::vector< double * >> &pdependentparametergroups) const
bool isEmptyDiagnoseMatrix () const
bool hasConflicting () const
bool hasRedundant () const
bool hasPartiallyRedundant () const
void invalidatedDiagnosis ()
Public Attributes
int maxIter
int maxIterRedundant
bool sketchSizeMultiplier
bool sketchSizeMultiplierRedundant
double convergence
double convergenceRedundant
QRAlgorithm qrAlgorithm
DogLegGaussStep dogLegGaussStep
double qrpivotThreshold
DebugMode debugMode
double LM_eps
double LM_eps1
double LM_tau
double DL_tolg
double DL_tolx
double DL_tolf
double LM_epsRedundant
double LM_eps1Redundant
double LM_tauRedundant
double DL_tolgRedundant
double DL_tolxRedundant
double DL_tolfRedundant
Protected Member Functions
size_t _getNumberOfConstraints (int tagID=-1)
Detailed Description
Definition at line 105 of file GCS.h.
Constructor & Destructor Documentation
System()
GCS::System::System ()
Definition at line 459 of file GCS.cpp.
~System()
GCS::System::~System ()
Definition at line 504 of file GCS.cpp.
References clear().
Member Function Documentation
_getNumberOfConstraints()
size_t GCS::System::_getNumberOfConstraints (int tagID = -1) inline protected
Definition at line 620 of file GCS.h.
addConstraint()
int GCS::System::addConstraint (Constraint * constr)
Definition at line 556 of file GCS.cpp.
References GCS::Constraint::getTag(), Init::param, and GCS::Constraint::params().
Referenced by addConstraintAngleViaPoint(), addConstraintAngleViaPointAndParam(), addConstraintAngleViaPointAndTwoParams(), addConstraintAngleViaTwoPoints(), addConstraintArcLength(), addConstraintC2CDistance(), addConstraintC2LDistance(), addConstraintCurveValue(), addConstraintDifference(), addConstraintEqual(), addConstraintEqualFocus(), addConstraintEqualLength(), addConstraintEqualRadii(), addConstraintInternalAlignmentKnotPoint(), addConstraintInternalAlignmentPoint2Ellipse(), addConstraintInternalAlignmentPoint2Hyperbola(), addConstraintL2LAngle(), addConstraintMidpointOnLine(), addConstraintP2CDistance(), addConstraintP2LDistance(), addConstraintP2PAngle(), addConstraintP2PDistance(), addConstraintParallel(), addConstraintPerpendicular(), addConstraintPointOnBSpline(), addConstraintPointOnEllipse(), addConstraintPointOnHyperbolicArc(), addConstraintPointOnLine(), addConstraintPointOnParabolicArc(), addConstraintPointOnPerpBisector(), addConstraintProportional(), addConstraintSnellsLaw(), addConstraintTangent(), addConstraintTangentAtBSplineKnot(), and addConstraintTangentCircumf().
addConstraintAngleViaPoint()
int GCS::System::addConstraintAngleViaPoint (Curve & crv1, Curve & crv2, Point & p, double * angle, int tagId = 0, bool driving = true)
Definition at line 764 of file GCS.cpp.
References addConstraint(), buildPsets::p, GCS::Constraint::setDriving(), and GCS::Constraint::setTag().
addConstraintAngleViaPointAndParam()
int GCS::System::addConstraintAngleViaPointAndParam (Curve & crv1, Curve & crv2, Point & p, double * cparam, double * angle, int tagId = 0, bool driving = true)
Definition at line 791 of file GCS.cpp.
References addConstraint(), buildPsets::p, GCS::Constraint::setDriving(), and GCS::Constraint::setTag().
addConstraintAngleViaPointAndTwoParams()
int GCS::System::addConstraintAngleViaPointAndTwoParams (Curve & crv1, Curve & crv2, Point & p, double * cparam1, double * cparam2, double * angle, int tagId = 0, bool driving = true)
Definition at line 805 of file GCS.cpp.
References addConstraint(), buildPsets::p, GCS::Constraint::setDriving(), and GCS::Constraint::setTag().
addConstraintAngleViaTwoPoints()
int GCS::System::addConstraintAngleViaTwoPoints (Curve & crv1, Curve & crv2, Point & p1, Point & p2, double * angle, int tagId = 0, bool driving = true)
Definition at line 777 of file GCS.cpp.
References addConstraint(), GCS::Constraint::setDriving(), and GCS::Constraint::setTag().
addConstraintArcDiameter()
int GCS::System::addConstraintArcDiameter (Arc & a, double * diameter, int tagId = 0, bool driving = true)
Definition at line 1186 of file GCS.cpp.
References a, and addConstraintProportional().
addConstraintArcLength()
int GCS::System::addConstraintArcLength (Arc & a, double * dist, int tagId, bool driving = true)
Definition at line 892 of file GCS.cpp.
References a, addConstraint(), GCS::Constraint::setDriving(), and GCS::Constraint::setTag().
addConstraintArcOfEllipseRules()
int GCS::System::addConstraintArcOfEllipseRules (ArcOfEllipse & a, int tagId = 0, bool driving = true)
Definition at line 991 of file GCS.cpp.
References a, and addConstraintCurveValue().
addConstraintArcOfHyperbolaRules()
int GCS::System::addConstraintArcOfHyperbolaRules (ArcOfHyperbola & a, int tagId = 0, bool driving = true)
Definition at line 1009 of file GCS.cpp.
References a, and addConstraintCurveValue().
addConstraintArcOfParabolaRules()
int GCS::System::addConstraintArcOfParabolaRules (ArcOfParabola & a, int tagId = 0, bool driving = true)
Definition at line 1015 of file GCS.cpp.
References a, and addConstraintCurveValue().
addConstraintArcRadius()
int GCS::System::addConstraintArcRadius (Arc & a, double * radius, int tagId = 0, bool driving = true)
Definition at line 1176 of file GCS.cpp.
References a, and addConstraintEqual().
addConstraintArcRules()
int GCS::System::addConstraintArcRules (Arc & a, int tagId = 0, bool driving = true)
Definition at line 939 of file GCS.cpp.
References a, and addConstraintCurveValue().
addConstraintC2CDistance()
int GCS::System::addConstraintC2CDistance (Circle & c1, Circle & c2, double * dist, int tagId, bool driving = true)
Definition at line 868 of file GCS.cpp.
References addConstraint(), src.Mod.PartDesign.Scripts.Gear::c1, DraftVecUtils::dist(), GCS::Constraint::setDriving(), and GCS::Constraint::setTag().
addConstraintC2LDistance()
int GCS::System::addConstraintC2LDistance (Circle & c, Line & l, double * dist, int tagId, bool driving = true)
Definition at line 876 of file GCS.cpp.
References addConstraint(), SCL.SimpleDataTypes::c, DraftVecUtils::dist(), RobotExample::l, GCS::Constraint::setDriving(), and GCS::Constraint::setTag().
addConstraintCircleDiameter()
int GCS::System::addConstraintCircleDiameter (Circle & c, double * diameter, int tagId = 0, bool driving = true)
Definition at line 1181 of file GCS.cpp.
References addConstraintProportional(), and SCL.SimpleDataTypes::c.
addConstraintCircleRadius()
int GCS::System::addConstraintCircleRadius (Circle & c, double * radius, int tagId = 0, bool driving = true)
Definition at line 1171 of file GCS.cpp.
References addConstraintEqual(), and SCL.SimpleDataTypes::c.
addConstraintCoordinateX()
int GCS::System::addConstraintCoordinateX (Point & p, double * x, int tagId = 0, bool driving = true)
Definition at line 929 of file GCS.cpp.
References addConstraintEqual(), buildPsets::p, and MovieTool::x.
addConstraintCoordinateY()
int GCS::System::addConstraintCoordinateY (Point & p, double * y, int tagId = 0, bool driving = true)
Definition at line 934 of file GCS.cpp.
References addConstraintEqual(), buildPsets::p, and MovieTool::y.
addConstraintCurveValue()
int GCS::System::addConstraintCurveValue (Point & p, Curve & a, double * u, int tagId = 0, bool driving = true)
Definition at line 997 of file GCS.cpp.
References a, addConstraint(), buildPsets::p, GCS::Constraint::setDriving(), GCS::Constraint::setTag(), and buildPsets::u.
Referenced by addConstraintArcOfEllipseRules(), addConstraintArcOfHyperbolaRules(), addConstraintArcOfParabolaRules(), and addConstraintArcRules().
addConstraintDifference()
int GCS::System::addConstraintDifference (double * param1, double * param2, double * difference, int tagId = 0, bool driving = true)
Definition at line 627 of file GCS.cpp.
References addConstraint(), GCS::Constraint::setDriving(), and GCS::Constraint::setTag().
addConstraintEqual()
int GCS::System::addConstraintEqual (double * param1, double * param2, int tagId = 0, bool driving = true, Constraint::Alignment internalalignment = Constraint::Alignment::NoInternalAlignment)
Definition at line 602 of file GCS.cpp.
References addConstraint(), GCS::Constraint::setDriving(), GCS::Constraint::setInternalAlignment(), and GCS::Constraint::setTag().
Referenced by addConstraintArcRadius(), addConstraintCircleRadius(), addConstraintCoordinateX(), addConstraintCoordinateY(), addConstraintEqualRadii(), addConstraintEqualRadius(), addConstraintHorizontal(), addConstraintInternalAlignmentBSplineControlPoint(), addConstraintInternalAlignmentEllipseFocus1(), addConstraintInternalAlignmentHyperbolaFocus(), addConstraintInternalAlignmentParabolaFocus(), addConstraintP2PCoincident(), and addConstraintVertical().
addConstraintEqualFocus()
int GCS::System::addConstraintEqualFocus (ArcOfParabola & a1, ArcOfParabola & a2, int tagId = 0, bool driving = true)
Definition at line 1224 of file GCS.cpp.
References NavigationIndicatorGui::a1, NavigationIndicatorGui::a2, addConstraint(), GCS::Constraint::setDriving(), and GCS::Constraint::setTag().
addConstraintEqualLength()
int GCS::System::addConstraintEqualLength (Line & l1, Line & l2, int tagId = 0, bool driving = true)
Definition at line 1191 of file GCS.cpp.
References addConstraint(), src.Mod.PartDesign.Scripts.Gear::l1, src.Mod.PartDesign.Scripts.Gear::l2, GCS::Constraint::setDriving(), and GCS::Constraint::setTag().
addConstraintEqualRadii() [1/2]
int GCS::System::addConstraintEqualRadii (ArcOfHyperbola & a1, ArcOfHyperbola & a2, int tagId = 0, bool driving = true)
Definition at line 1214 of file GCS.cpp.
References NavigationIndicatorGui::a1, NavigationIndicatorGui::a2, addConstraint(), addConstraintEqual(), GCS::Constraint::setDriving(), and GCS::Constraint::setTag().
addConstraintEqualRadii() [2/2]
int GCS::System::addConstraintEqualRadii (Ellipse & e1, Ellipse & e2, int tagId = 0, bool driving = true)
Definition at line 1204 of file GCS.cpp.
References addConstraint(), addConstraintEqual(), src.Mod.PartDesign.Scripts.Gear::e1, GCS::Ellipse::radmin, GCS::Constraint::setDriving(), and GCS::Constraint::setTag().
addConstraintEqualRadius() [1/3]
int GCS::System::addConstraintEqualRadius (Arc & a1, Arc & a2, int tagId = 0, bool driving = true)
Definition at line 1237 of file GCS.cpp.
References NavigationIndicatorGui::a1, NavigationIndicatorGui::a2, and addConstraintEqual().
addConstraintEqualRadius() [2/3]
int GCS::System::addConstraintEqualRadius (Circle & c1, Arc & a2, int tagId = 0, bool driving = true)
Definition at line 1232 of file GCS.cpp.
References NavigationIndicatorGui::a2, addConstraintEqual(), and src.Mod.PartDesign.Scripts.Gear::c1.
addConstraintEqualRadius() [3/3]
int GCS::System::addConstraintEqualRadius (Circle & c1, Circle & c2, int tagId = 0, bool driving = true)
Definition at line 1199 of file GCS.cpp.
References addConstraintEqual(), src.Mod.PartDesign.Scripts.Gear::c1, and GCS::Circle::rad.
addConstraintHorizontal() [1/2]
int GCS::System::addConstraintHorizontal (Line & l, int tagId = 0, bool driving = true)
Definition at line 909 of file GCS.cpp.
References addConstraintEqual(), and RobotExample::l.
addConstraintHorizontal() [2/2]
int GCS::System::addConstraintHorizontal (Point & p1, Point & p2, int tagId = 0, bool driving = true)
Definition at line 914 of file GCS.cpp.
References addConstraintEqual(), and GCS::Point::y.
addConstraintInternalAlignmentBSplineControlPoint()
int GCS::System::addConstraintInternalAlignmentBSplineControlPoint (BSpline & b, Circle & c, unsigned int poleindex, int tag = 0, bool driving = true)
Definition at line 1609 of file GCS.cpp.
References addConstraintEqual(), SCL.SimpleDataTypes::b, SCL.SimpleDataTypes::c, and GCS::Constraint::InternalAlignment.
addConstraintInternalAlignmentEllipseFocus1()
int GCS::System::addConstraintInternalAlignmentEllipseFocus1 (Ellipse & e, Point & p1, int tagId = 0, bool driving = true)
Definition at line 1399 of file GCS.cpp.
References addConstraintEqual(), SCL.SimpleDataTypes::e, GCS::Constraint::InternalAlignment, GCS::Point::x, and GCS::Point::y.
addConstraintInternalAlignmentEllipseFocus2()
int GCS::System::addConstraintInternalAlignmentEllipseFocus2 (Ellipse & e, Point & p1, int tagId = 0, bool driving = true)
Definition at line 1412 of file GCS.cpp.
References addConstraintInternalAlignmentPoint2Ellipse(), SCL.SimpleDataTypes::e, GCS::EllipseFocus2X, and GCS::EllipseFocus2Y.
addConstraintInternalAlignmentEllipseMajorDiameter()
int GCS::System::addConstraintInternalAlignmentEllipseMajorDiameter (Ellipse & e, Point & p1, Point & p2, int tagId = 0, bool driving = true)
Definition at line 1297 of file GCS.cpp.
References addConstraintInternalAlignmentPoint2Ellipse(), SCL.SimpleDataTypes::b, SCL.SimpleDataTypes::e, GCS::EllipseNegativeMajorX, GCS::EllipseNegativeMajorY, GCS::EllipsePositiveMajorX, GCS::EllipsePositiveMajorY, Base::pow(), KDL::sqrt(), GCS::Point::x, and GCS::Point::y.
addConstraintInternalAlignmentEllipseMinorDiameter()
int GCS::System::addConstraintInternalAlignmentEllipseMinorDiameter (Ellipse & e, Point & p1, Point & p2, int tagId = 0, bool driving = true)
Definition at line 1355 of file GCS.cpp.
References addConstraintInternalAlignmentPoint2Ellipse(), SCL.SimpleDataTypes::b, SCL.SimpleDataTypes::e, GCS::EllipseNegativeMinorX, GCS::EllipseNegativeMinorY, GCS::EllipsePositiveMinorX, GCS::EllipsePositiveMinorY, Base::pow(), KDL::sqrt(), GCS::Point::x, and GCS::Point::y.
addConstraintInternalAlignmentHyperbolaFocus()
int GCS::System::addConstraintInternalAlignmentHyperbolaFocus (Hyperbola & e, Point & p1, int tagId = 0, bool driving = true)
Definition at line 1583 of file GCS.cpp.
References addConstraintEqual(), SCL.SimpleDataTypes::e, GCS::Constraint::InternalAlignment, GCS::Point::x, and GCS::Point::y.
addConstraintInternalAlignmentHyperbolaMajorDiameter()
int GCS::System::addConstraintInternalAlignmentHyperbolaMajorDiameter (Hyperbola & e, Point & p1, Point & p2, int tagId = 0, bool driving = true)
Definition at line 1421 of file GCS.cpp.
References addConstraintInternalAlignmentPoint2Hyperbola(), SCL.SimpleDataTypes::b, SCL.SimpleDataTypes::e, GCS::HyperbolaNegativeMajorX, GCS::HyperbolaNegativeMajorY, GCS::HyperbolaPositiveMajorX, GCS::HyperbolaPositiveMajorY, Base::pow(), KDL::sqrt(), GCS::Point::x, and GCS::Point::y.
addConstraintInternalAlignmentHyperbolaMinorDiameter()
int GCS::System::addConstraintInternalAlignmentHyperbolaMinorDiameter (Hyperbola & e, Point & p1, Point & p2, int tagId = 0, bool driving = true)
Definition at line 1503 of file GCS.cpp.
References addConstraintInternalAlignmentPoint2Hyperbola(), SCL.SimpleDataTypes::b, SCL.SimpleDataTypes::e, GCS::HyperbolaNegativeMinorX, GCS::HyperbolaNegativeMinorY, GCS::HyperbolaPositiveMinorX, GCS::HyperbolaPositiveMinorY, Base::pow(), KDL::sqrt(), GCS::Point::x, and GCS::Point::y.
addConstraintInternalAlignmentKnotPoint()
int GCS::System::addConstraintInternalAlignmentKnotPoint (BSpline & b, Point & p, unsigned int knotindex, int tagId = 0, bool driving = true)
Definition at line 1632 of file GCS.cpp.
References addConstraint(), addConstraintP2PCoincident(), SCL.SimpleDataTypes::b, SplineSurface::i, GCS::Constraint::InternalAlignment, buildPsets::p, GCS::Constraint::setDriving(), GCS::Constraint::setInternalAlignment(), and GCS::Constraint::setTag().
addConstraintInternalAlignmentParabolaFocus()
int GCS::System::addConstraintInternalAlignmentParabolaFocus (Parabola & e, Point & p1, int tagId = 0, bool driving = true)
Definition at line 1596 of file GCS.cpp.
References addConstraintEqual(), SCL.SimpleDataTypes::e, GCS::Constraint::InternalAlignment, GCS::Point::x, and GCS::Point::y.
addConstraintInternalAlignmentPoint2Ellipse()
int GCS::System::addConstraintInternalAlignmentPoint2Ellipse (Ellipse & e, Point & p1, InternalAlignmentType alignmentType, int tagId = 0, bool driving = true)
Definition at line 1271 of file GCS.cpp.
References addConstraint(), SCL.SimpleDataTypes::e, GCS::Constraint::InternalAlignment, GCS::Constraint::setDriving(), GCS::Constraint::setInternalAlignment(), and GCS::Constraint::setTag().
Referenced by addConstraintInternalAlignmentEllipseFocus2(), addConstraintInternalAlignmentEllipseMajorDiameter(), and addConstraintInternalAlignmentEllipseMinorDiameter().
addConstraintInternalAlignmentPoint2Hyperbola()
int GCS::System::addConstraintInternalAlignmentPoint2Hyperbola (Hyperbola & e, Point & p1, InternalAlignmentType alignmentType, int tagId = 0, bool driving = true)
Definition at line 1284 of file GCS.cpp.
References addConstraint(), SCL.SimpleDataTypes::e, GCS::Constraint::InternalAlignment, GCS::Constraint::setDriving(), GCS::Constraint::setInternalAlignment(), and GCS::Constraint::setTag().
Referenced by addConstraintInternalAlignmentHyperbolaMajorDiameter(), and addConstraintInternalAlignmentHyperbolaMinorDiameter().
addConstraintL2LAngle() [1/2]
int GCS::System::addConstraintL2LAngle (Line & l1, Line & l2, double * angle, int tagId = 0, bool driving = true)
Definition at line 742 of file GCS.cpp.
References addConstraint(), src.Mod.PartDesign.Scripts.Gear::l1, src.Mod.PartDesign.Scripts.Gear::l2, GCS::Constraint::setDriving(), and GCS::Constraint::setTag().
addConstraintL2LAngle() [2/2]
int GCS::System::addConstraintL2LAngle (Point & l1p1, Point & l1p2, Point & l2p1, Point & l2p2, double * angle, int tagId = 0, bool driving = true)
Definition at line 750 of file GCS.cpp.
References addConstraint(), GCS::Constraint::setDriving(), and GCS::Constraint::setTag().
addConstraintMidpointOnLine() [1/2]
int GCS::System::addConstraintMidpointOnLine (Line & l1, Line & l2, int tagId = 0, bool driving = true)
Definition at line 821 of file GCS.cpp.
References addConstraint(), src.Mod.PartDesign.Scripts.Gear::l1, src.Mod.PartDesign.Scripts.Gear::l2, GCS::Constraint::setDriving(), and GCS::Constraint::setTag().
Referenced by addConstraintP2PSymmetric().
addConstraintMidpointOnLine() [2/2]
int GCS::System::addConstraintMidpointOnLine (Point & l1p1, Point & l1p2, Point & l2p1, Point & l2p2, int tagId = 0, bool driving = true)
Definition at line 829 of file GCS.cpp.
References addConstraint(), GCS::Constraint::setDriving(), and GCS::Constraint::setTag().
addConstraintP2CDistance()
int GCS::System::addConstraintP2CDistance (Point & p, Circle & c, double * distance, int tagId = 0, bool driving = true)
Definition at line 884 of file GCS.cpp.
References addConstraint(), SCL.SimpleDataTypes::c, buildPsets::p, GCS::Constraint::setDriving(), and GCS::Constraint::setTag().
addConstraintP2LDistance()
int GCS::System::addConstraintP2LDistance (Point & p, Line & l, double * distance, int tagId = 0, bool driving = true)
Definition at line 669 of file GCS.cpp.
References addConstraint(), RobotExample::l, buildPsets::p, GCS::Constraint::setDriving(), and GCS::Constraint::setTag().
Referenced by addConstraintTangent().
addConstraintP2PAngle() [1/2]
int GCS::System::addConstraintP2PAngle (Point & p1, Point & p2, double * angle, double incrAngle, int tagId = 0, bool driving = true)
Definition at line 651 of file GCS.cpp.
References addConstraint(), GCS::Constraint::setDriving(), and GCS::Constraint::setTag().
Referenced by addConstraintP2PAngle(), addConstraintPerpendicularArc2Circle(), addConstraintPerpendicularArc2Line(), addConstraintPerpendicularCircle2Arc(), and addConstraintPerpendicularLine2Arc().
addConstraintP2PAngle() [2/2]
int GCS::System::addConstraintP2PAngle (Point & p1, Point & p2, double * angle, int tagId = 0, bool driving = true)
Definition at line 664 of file GCS.cpp.
References addConstraintP2PAngle().
addConstraintP2PCoincident()
int GCS::System::addConstraintP2PCoincident (Point & p1, Point & p2, int tagId = 0, bool driving = true)
Definition at line 903 of file GCS.cpp.
References addConstraintEqual(), GCS::Point::x, and GCS::Point::y.
Referenced by addConstraintInternalAlignmentKnotPoint(), addConstraintPerpendicularArc2Arc(), addConstraintPerpendicularArc2Line(), and addConstraintPerpendicularLine2Arc().
addConstraintP2PDistance()
int GCS::System::addConstraintP2PDistance (Point & p1, Point & p2, double * distance, int tagId = 0, bool driving = true)
Definition at line 639 of file GCS.cpp.
References addConstraint(), GCS::Constraint::setDriving(), and GCS::Constraint::setTag().
Referenced by addConstraintPerpendicularArc2Circle(), addConstraintPerpendicularCircle2Arc(), addConstraintPointOnArc(), and addConstraintPointOnCircle().
addConstraintP2PSymmetric() [1/2]
int GCS::System::addConstraintP2PSymmetric (Point & p1, Point & p2, Line & l, int tagId = 0, bool driving = true)
Definition at line 1242 of file GCS.cpp.
References addConstraintMidpointOnLine(), addConstraintPerpendicular(), and RobotExample::l.
addConstraintP2PSymmetric() [2/2]
int GCS::System::addConstraintP2PSymmetric (Point & p1, Point & p2, Point & p, int tagId = 0, bool driving = true)
Definition at line 1248 of file GCS.cpp.
References addConstraintPointOnLine(), addConstraintPointOnPerpBisector(), and buildPsets::p.
addConstraintParallel()
int GCS::System::addConstraintParallel (Line & l1, Line & l2, int tagId = 0, bool driving = true)
Definition at line 713 of file GCS.cpp.
References addConstraint(), src.Mod.PartDesign.Scripts.Gear::l1, src.Mod.PartDesign.Scripts.Gear::l2, GCS::Constraint::setDriving(), and GCS::Constraint::setTag().
addConstraintPerpendicular() [1/2]
int GCS::System::addConstraintPerpendicular (Line & l1, Line & l2, int tagId = 0, bool driving = true)
Definition at line 721 of file GCS.cpp.
References addConstraint(), src.Mod.PartDesign.Scripts.Gear::l1, src.Mod.PartDesign.Scripts.Gear::l2, GCS::Constraint::setDriving(), and GCS::Constraint::setTag().
Referenced by addConstraintP2PSymmetric(), and addConstraintPerpendicularArc2Arc().
addConstraintPerpendicular() [2/2]
int GCS::System::addConstraintPerpendicular (Point & l1p1, Point & l1p2, Point & l2p1, Point & l2p2, int tagId = 0, bool driving = true)
Definition at line 729 of file GCS.cpp.
References addConstraint(), GCS::Constraint::setDriving(), and GCS::Constraint::setTag().
addConstraintPerpendicularArc2Arc()
int GCS::System::addConstraintPerpendicularArc2Arc (Arc & a1, bool reverse1, Arc & a2, bool reverse2, int tagId = 0, bool driving = true)
Definition at line 1098 of file GCS.cpp.
References NavigationIndicatorGui::a1, NavigationIndicatorGui::a2, addConstraintP2PCoincident(), and addConstraintPerpendicular().
addConstraintPerpendicularArc2Circle()
int GCS::System::addConstraintPerpendicularArc2Circle (Arc & a, Point & center, double * radius, int tagId = 0, bool driving = true)
Definition at line 1079 of file GCS.cpp.
References a, addConstraintP2PAngle(), addConstraintP2PDistance(), exportCSG::center(), KDL::cos(), GCS::pi_2, and KDL::sin().
addConstraintPerpendicularArc2Line()
int GCS::System::addConstraintPerpendicularArc2Line (Arc & a, Point & p1, Point & p2, int tagId = 0, bool driving = true)
Definition at line 1043 of file GCS.cpp.
References a, addConstraintP2PAngle(), addConstraintP2PCoincident(), KDL::cos(), GCS::pi, KDL::sin(), GCS::Point::x, and GCS::Point::y.
addConstraintPerpendicularCircle2Arc()
int GCS::System::addConstraintPerpendicularCircle2Arc (Point & center, double * radius, Arc & a, int tagId = 0, bool driving = true)
Definition at line 1060 of file GCS.cpp.
References a, addConstraintP2PAngle(), addConstraintP2PDistance(), exportCSG::center(), KDL::cos(), GCS::pi_2, and KDL::sin().
addConstraintPerpendicularLine2Arc()
int GCS::System::addConstraintPerpendicularLine2Arc (Point & p1, Point & p2, Arc & a, int tagId = 0, bool driving = true)
Definition at line 1026 of file GCS.cpp.
References a, addConstraintP2PAngle(), addConstraintP2PCoincident(), KDL::cos(), GCS::pi, KDL::sin(), GCS::Point::x, and GCS::Point::y.
addConstraintPointOnArc()
int GCS::System::addConstraintPointOnArc (Point & p, Arc & a, int tagId = 0, bool driving = true)
Definition at line 1021 of file GCS.cpp.
References a, addConstraintP2PDistance(), and buildPsets::p.
addConstraintPointOnBSpline()
int GCS::System::addConstraintPointOnBSpline (Point & p, BSpline & b, double * pointparam, int tagId, bool driving = true)
Definition at line 974 of file GCS.cpp.
References addConstraint(), SCL.SimpleDataTypes::b, buildPsets::p, GCS::Constraint::setDriving(), and GCS::Constraint::setTag().
addConstraintPointOnCircle()
int GCS::System::addConstraintPointOnCircle (Point & p, Circle & c, int tagId = 0, bool driving = true)
Definition at line 945 of file GCS.cpp.
References addConstraintP2PDistance(), SCL.SimpleDataTypes::c, and buildPsets::p.
addConstraintPointOnEllipse()
int GCS::System::addConstraintPointOnEllipse (Point & p, Ellipse & e, int tagId = 0, bool driving = true)
Definition at line 950 of file GCS.cpp.
References addConstraint(), SCL.SimpleDataTypes::e, buildPsets::p, GCS::Constraint::setDriving(), and GCS::Constraint::setTag().
addConstraintPointOnHyperbolicArc()
int GCS::System::addConstraintPointOnHyperbolicArc (Point & p, ArcOfHyperbola & e, int tagId = 0, bool driving = true)
Definition at line 958 of file GCS.cpp.
References addConstraint(), SCL.SimpleDataTypes::e, buildPsets::p, GCS::Constraint::setDriving(), and GCS::Constraint::setTag().
addConstraintPointOnLine() [1/2]
int GCS::System::addConstraintPointOnLine (Point & p, Line & l, int tagId = 0, bool driving = true)
Definition at line 677 of file GCS.cpp.
References addConstraint(), RobotExample::l, buildPsets::p, GCS::Constraint::setDriving(), and GCS::Constraint::setTag().
Referenced by addConstraintP2PSymmetric().
addConstraintPointOnLine() [2/2]
int GCS::System::addConstraintPointOnLine (Point & p, Point & lp1, Point & lp2, int tagId = 0, bool driving = true)
Definition at line 685 of file GCS.cpp.
References addConstraint(), buildPsets::p, GCS::Constraint::setDriving(), and GCS::Constraint::setTag().
addConstraintPointOnParabolicArc()
int GCS::System::addConstraintPointOnParabolicArc (Point & p, ArcOfParabola & e, int tagId = 0, bool driving = true)
Definition at line 966 of file GCS.cpp.
References addConstraint(), SCL.SimpleDataTypes::e, buildPsets::p, GCS::Constraint::setDriving(), and GCS::Constraint::setTag().
addConstraintPointOnPerpBisector() [1/2]
int GCS::System::addConstraintPointOnPerpBisector (Point & p, Line & l, int tagId = 0, bool driving = true)
Definition at line 693 of file GCS.cpp.
References addConstraint(), RobotExample::l, buildPsets::p, GCS::Constraint::setDriving(), and GCS::Constraint::setTag().
Referenced by addConstraintP2PSymmetric().
addConstraintPointOnPerpBisector() [2/2]
int GCS::System::addConstraintPointOnPerpBisector (Point & p, Point & lp1, Point & lp2, int tagId = 0, bool driving = true)
Definition at line 701 of file GCS.cpp.
References addConstraint(), buildPsets::p, GCS::Constraint::setDriving(), and GCS::Constraint::setTag().
addConstraintProportional()
int GCS::System::addConstraintProportional (double * param1, double * param2, double ratio, int tagId, bool driving = true)
Definition at line 615 of file GCS.cpp.
References addConstraint(), GCS::Constraint::setDriving(), and GCS::Constraint::setTag().
Referenced by addConstraintArcDiameter(), and addConstraintCircleDiameter().
addConstraintSnellsLaw()
int GCS::System::addConstraintSnellsLaw (Curve & ray1, Curve & ray2, Curve & boundary, Point p, double * n1, double * n2, bool flipn1, bool flipn2, int tagId, bool driving = true)
Definition at line 1254 of file GCS.cpp.
References addConstraint(), buildPsets::p, GCS::Constraint::setDriving(), and GCS::Constraint::setTag().
addConstraintTangent() [1/6]
int GCS::System::addConstraintTangent (Arc & a1, Arc & a2, int tagId = 0, bool driving = true)
Definition at line 1143 of file GCS.cpp.
References NavigationIndicatorGui::a1, NavigationIndicatorGui::a2, addConstraintTangentCircumf(), and KDL::sqrt().
addConstraintTangent() [2/6]
int GCS::System::addConstraintTangent (Circle & c, Arc & a, int tagId = 0, bool driving = true)
Definition at line 1157 of file GCS.cpp.
References a, addConstraintTangentCircumf(), SCL.SimpleDataTypes::c, and KDL::sqrt().
addConstraintTangent() [3/6]
int GCS::System::addConstraintTangent (Circle & c1, Circle & c2, int tagId = 0, bool driving = true)
Definition at line 1129 of file GCS.cpp.
References addConstraintTangentCircumf(), src.Mod.PartDesign.Scripts.Gear::c1, GCS::Circle::center, GCS::Circle::rad, KDL::sqrt(), GCS::Point::x, and GCS::Point::y.
addConstraintTangent() [4/6]
int GCS::System::addConstraintTangent (Line & l, Arc & a, int tagId = 0, bool driving = true)
Definition at line 1124 of file GCS.cpp.
References a, addConstraintP2LDistance(), and RobotExample::l.
addConstraintTangent() [5/6]
int GCS::System::addConstraintTangent (Line & l, Circle & c, int tagId = 0, bool driving = true)
Definition at line 1111 of file GCS.cpp.
References addConstraintP2LDistance(), SCL.SimpleDataTypes::c, and RobotExample::l.
addConstraintTangent() [6/6]
int GCS::System::addConstraintTangent (Line & l, Ellipse & e, int tagId = 0, bool driving = true)
Definition at line 1116 of file GCS.cpp.
References addConstraint(), SCL.SimpleDataTypes::e, RobotExample::l, GCS::Constraint::setDriving(), and GCS::Constraint::setTag().
addConstraintTangentAtBSplineKnot()
int GCS::System::addConstraintTangentAtBSplineKnot (BSpline & b, Line & l, unsigned int knotindex, int tagId = 0, bool driving = true)
Definition at line 856 of file GCS.cpp.
References addConstraint(), SCL.SimpleDataTypes::b, RobotExample::l, GCS::Constraint::setDriving(), and GCS::Constraint::setTag().
addConstraintTangentCircumf()
int GCS::System::addConstraintTangentCircumf (Point & p1, Point & p2, double * rd1, double * rd2, bool internal = false, int tagId = 0, bool driving = true)
Definition at line 842 of file GCS.cpp.
References addConstraint(), GCS::Constraint::setDriving(), and GCS::Constraint::setTag().
Referenced by addConstraintTangent().
addConstraintVertical() [1/2]
int GCS::System::addConstraintVertical (Line & l, int tagId = 0, bool driving = true)
Definition at line 919 of file GCS.cpp.
References addConstraintEqual(), and RobotExample::l.
addConstraintVertical() [2/2]
int GCS::System::addConstraintVertical (Point & p1, Point & p2, int tagId = 0, bool driving = true)
Definition at line 924 of file GCS.cpp.
References addConstraintEqual(), and GCS::Point::x.
applySolution()
void GCS::System::applySolution ()
Definition at line 4853 of file GCS.cpp.
calculateAngleViaParams()
double GCS::System::calculateAngleViaParams (const Curve & crv1, const Curve & crv2, double * param1, double * param2) const
Definition at line 1735 of file GCS.cpp.
References KDL::atan2(), GCS::Curve::CalculateNormal(), GCS::DeriVector2::x, and GCS::DeriVector2::y.
calculateAngleViaPoint() [1/2]
double GCS::System::calculateAngleViaPoint (const Curve & crv1, const Curve & crv2, Point & p) const
Definition at line 1722 of file GCS.cpp.
References buildPsets::p.
calculateAngleViaPoint() [2/2]
double GCS::System::calculateAngleViaPoint (const Curve & crv1, const Curve & crv2, Point & p1, Point & p2) const
Definition at line 1728 of file GCS.cpp.
References KDL::atan2(), GCS::Curve::CalculateNormal(), GCS::DeriVector2::x, and GCS::DeriVector2::y.
calculateConstraintErrorByTag()
double GCS::System::calculateConstraintErrorByTag (int tagId)
Definition at line 1755 of file GCS.cpp.
References KDL::sqrt().
calculateNormalAtPoint()
void GCS::System::calculateNormalAtPoint (const Curve & crv, const Point & p, double & rtnX, double & rtnY) const
Definition at line 1745 of file GCS.cpp.
References GCS::Curve::CalculateNormal(), buildPsets::p, GCS::DeriVector2::x, and GCS::DeriVector2::y.
clear()
void GCS::System::clear ()
Definition at line 509 of file GCS.cpp.
References GCS::free().
Referenced by src.Mod.Test.Document.DocumentObserverCases.Observer::__init__(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::__init__(), and ~System().
clearByTag()
void GCS::System::clearByTag (int tagId)
Definition at line 540 of file GCS.cpp.
References removeConstraint().
declareDrivenParams()
void GCS::System::declareDrivenParams (VEC_pD & params)
Definition at line 1801 of file GCS.cpp.
References nativeifc.ifc_observer::params.
declareUnknowns()
void GCS::System::declareUnknowns (VEC_pD & params)
Definition at line 1791 of file GCS.cpp.
References SplineSurface::i, and nativeifc.ifc_observer::params.
Referenced by solve().
diagnose()
int GCS::System::diagnose (Algorithm alg = DogLeg)
Definition at line 4921 of file GCS.cpp.
References Base::Console(), Base::TimeElapsed::diffTimeF(), GCS::EigenDenseQR, GCS::EigenSparseQR, Base::ConsoleSingleton::Log(), GCS::SolverReportingManager::LogToFile(), GCS::SolverReportingManager::Manager(), qrAlgorithm, CAMTests.TestPathStock::R, and Base::ConsoleSingleton::Warning().
Referenced by initSolution().
dofsNumber()
int GCS::System::dofsNumber () const inline
Definition at line 573 of file GCS.h.
getConflicting()
void GCS::System::getConflicting (VEC_I & conflictingOut) const inline
Definition at line 577 of file GCS.h.
getDependentParams()
void GCS::System::getDependentParams (VEC_pD & pdependentparameterlist) const inline
Definition at line 589 of file GCS.h.
getDependentParamsGroups()
void GCS::System::getDependentParamsGroups (std::vector< std::vector< double * >> & pdependentparametergroups) const inline
Definition at line 594 of file GCS.h.
getFinePrecision()
double GCS::System::getFinePrecision () inline
Definition at line 567 of file GCS.h.
getPartiallyRedundant()
void GCS::System::getPartiallyRedundant (VEC_I & partiallyredundantOut) const inline
Definition at line 585 of file GCS.h.
getRedundant()
void GCS::System::getRedundant (VEC_I & redundantOut) const inline
Definition at line 581 of file GCS.h.
hasConflicting()
bool GCS::System::hasConflicting () const inline
Definition at line 603 of file GCS.h.
hasPartiallyRedundant()
bool GCS::System::hasPartiallyRedundant () const inline
Definition at line 611 of file GCS.h.
hasRedundant()
bool GCS::System::hasRedundant () const inline
Definition at line 607 of file GCS.h.
initSolution()
void GCS::System::initSolution (Algorithm alg = DogLeg)
Definition at line 1807 of file GCS.cpp.
References diagnose(), GCS::Equal, toolbit-attributes::g, SplineSurface::i, num_vertices(), and Init::param.
Referenced by solve().
invalidatedDiagnosis()
void GCS::System::invalidatedDiagnosis ()
Definition at line 533 of file GCS.cpp.
isEmptyDiagnoseMatrix()
bool GCS::System::isEmptyDiagnoseMatrix () const inline
Definition at line 598 of file GCS.h.
removeConstraint()
void GCS::System::removeConstraint (Constraint * constr)
Definition at line 574 of file GCS.cpp.
References DraftVecUtils::find(), GCS::Constraint::getTag(), and Init::param.
Referenced by clearByTag().
rescaleConstraint()
void GCS::System::rescaleConstraint (int id, double coeff)
Definition at line 1781 of file GCS.cpp.
References SplineSurface::id.
solve() [1/4]
int GCS::System::solve (bool isFine = true, Algorithm alg = DogLeg, bool isRedundantsolving = false)
Definition at line 1978 of file GCS.cpp.
References GCS::Converged, convergence, convergenceRedundant, GCS::Failed, KDL::max(), and GCS::Success.
Referenced by solve().
solve() [2/4]
int GCS::System::solve (SubSystem * subsys, bool isFine = true, Algorithm alg = DogLeg, bool isRedundantsolving = false)
Definition at line 2021 of file GCS.cpp.
References GCS::BFGS, GCS::DogLeg, GCS::Failed, and GCS::LevenbergMarquardt.
solve() [3/4]
int GCS::System::solve (SubSystem * subsysA, SubSystem * subsysB, bool isFine = true, bool isRedundantsolving = false)
Definition at line 4683 of file GCS.cpp.
References RobotExample::B, GCS::SubSystem::calcGrad(), GCS::SubSystem::calcJacobi(), GCS::SubSystem::calcResidual(), GCS::Converged, convergence, convergenceRedundant, GCS::SubSystem::cSize(), SCL.SimpleDataTypes::e, GCS::SubSystem::error(), SCL.SimpleDataTypes::f, GCS::Failed, GCS::SubSystem::getParamList(), GCS::SubSystem::getParams(), KDL::max(), maxIter, maxIterRedundant, GCS::SubSystem::maxStep(), KDL::min(), GCS::SubSystem::pSize(), qp_eq(), GCS::SubSystem::redirectParams(), GCS::SubSystem::revertParams(), GCS::SubSystem::setParams(), sketchSizeMultiplier, sketchSizeMultiplierRedundant, smallF, GCS::Success, MovieTool::x, MovieTool::y, and DrawingExample::Y.
solve() [4/4]
int GCS::System::solve (VEC_pD & params, bool isFine = true, Algorithm alg = DogLeg, bool isRedundantsolving = false)
Definition at line 1971 of file GCS.cpp.
References declareUnknowns(), initSolution(), nativeifc.ifc_observer::params, and solve().
undoSolution()
void GCS::System::undoSolution ()
Definition at line 4870 of file GCS.cpp.
Member Data Documentation
convergence
double GCS::System::convergence
Definition at line 223 of file GCS.h.
Referenced by Sketcher::Sketch::getDebugMode(), and solve().
convergenceRedundant
double GCS::System::convergenceRedundant
Definition at line 224 of file GCS.h.
Referenced by Sketcher::Sketch::setMaxIter(), and solve().
debugMode
DebugMode GCS::System::debugMode
Definition at line 228 of file GCS.h.
DL_tolf
double GCS::System::DL_tolf
Definition at line 234 of file GCS.h.
Referenced by Sketcher::Sketch::setLM_eps().
DL_tolfRedundant
double GCS::System::DL_tolfRedundant
Definition at line 240 of file GCS.h.
Referenced by Sketcher::Sketch::setLM_epsRedundant().
DL_tolg
double GCS::System::DL_tolg
Definition at line 232 of file GCS.h.
Referenced by Sketcher::Sketch::getQRAlgorithm().
DL_tolgRedundant
double GCS::System::DL_tolgRedundant
Definition at line 238 of file GCS.h.
Referenced by Sketcher::Sketch::setDL_tolx().
DL_tolx
double GCS::System::DL_tolx
Definition at line 233 of file GCS.h.
Referenced by Sketcher::Sketch::setQRPivotThreshold().
DL_tolxRedundant
double GCS::System::DL_tolxRedundant
Definition at line 239 of file GCS.h.
Referenced by Sketcher::Sketch::setDL_tolf().
dogLegGaussStep
DogLegGaussStep GCS::System::dogLegGaussStep
Definition at line 226 of file GCS.h.
LM_eps
double GCS::System::LM_eps
Definition at line 229 of file GCS.h.
Referenced by Sketcher::Sketch::setConvergence().
LM_eps1
double GCS::System::LM_eps1
Definition at line 230 of file GCS.h.
Referenced by Sketcher::Sketch::setConvergenceRedundant().
LM_eps1Redundant
double GCS::System::LM_eps1Redundant
Definition at line 236 of file GCS.h.
Referenced by Sketcher::Sketch::setLM_tau().
LM_epsRedundant
double GCS::System::LM_epsRedundant
Definition at line 235 of file GCS.h.
Referenced by Sketcher::Sketch::setLM_eps1().
LM_tau
double GCS::System::LM_tau
Definition at line 231 of file GCS.h.
Referenced by Sketcher::Sketch::setQRAlgorithm().
LM_tauRedundant
double GCS::System::LM_tauRedundant
Definition at line 237 of file GCS.h.
Referenced by Sketcher::Sketch::setDL_tolg().
maxIter
int GCS::System::maxIter
Definition at line 218 of file GCS.h.
Referenced by solve().
maxIterRedundant
int GCS::System::maxIterRedundant
Definition at line 219 of file GCS.h.
Referenced by solve().
qrAlgorithm
QRAlgorithm GCS::System::qrAlgorithm
Definition at line 225 of file GCS.h.
Referenced by diagnose(), GCS::SolverReportingManager::LogQRSystemInformation(), Sketcher::Sketch::setMaxIterRedundant(), and Sketcher::Sketch::setSketchSizeMultiplier().
qrpivotThreshold
double GCS::System::qrpivotThreshold
Definition at line 227 of file GCS.h.
Referenced by GCS::SolverReportingManager::LogQRSystemInformation(), and Sketcher::Sketch::setSketchSizeMultiplierRedundant().
sketchSizeMultiplier
bool GCS::System::sketchSizeMultiplier
Definition at line 220 of file GCS.h.
Referenced by solve().
sketchSizeMultiplierRedundant
bool GCS::System::sketchSizeMultiplierRedundant
Definition at line 222 of file GCS.h.
Referenced by solve().
The documentation for this class was generated from the following files:
GCS.h
GCS.cpp