FreeCAD: MeshCore::MeshFacetArray Class Reference
MeshCore::MeshFacetArray Class Reference
#include <Elements.h>
Public Types
using _TIterator = std::vector< MeshFacet >::iterator
using _TConstIterator = std::vector< MeshFacet >::const_iterator
Public Member Functions
Construction
MeshFacetArray ()=default
constructor
MeshFacetArray (FacetIndex ulSize)
constructor
MeshFacetArray (const MeshFacetArray &)
copy-constructor
MeshFacetArray (MeshFacetArray &&)
~MeshFacetArray ()=default
destructor
Flag state
Note
All flag methods are const as they do NOT change the actual properties of the object
void SetFlag (MeshFacet::TFlagType tF) const
Sets the flag for all facets.
void ResetFlag (MeshFacet::TFlagType tF) const
Resets the flag for all facets.
void ResetInvalid () const
Sets all facets invalid.
void SetProperty (unsigned long ulVal) const
Sets the property for all facets.
MeshFacetArray & operator= (const MeshFacetArray &rclFAry)
MeshFacetArray & operator= (MeshFacetArray &&rclFAry)
void Erase (_TIterator pIter)
void TransposeIndices (PointIndex ulOrig, PointIndex ulNew)
void DecrementIndices (PointIndex ulIndex)
Detailed Description
Stores all facets of the mesh data-structure.
Definition at line 762 of file Elements.h.
Member Typedef Documentation
_TConstIterator
using MeshCore::MeshFacetArray::_TConstIterator = std::vector<MeshFacet>::const_iterator
Definition at line 767 of file Elements.h.
_TIterator
using MeshCore::MeshFacetArray::_TIterator = std::vector<MeshFacet>::iterator
Definition at line 766 of file Elements.h.
Constructor & Destructor Documentation
MeshFacetArray() [1/4]
MeshCore::MeshFacetArray::MeshFacetArray () default
constructor
MeshFacetArray() [2/4]
MeshCore::MeshFacetArray::MeshFacetArray (FacetIndex ulSize) inline explicit
constructor
Definition at line 774 of file Elements.h.
MeshFacetArray() [3/4]
MeshFacetArray::MeshFacetArray (const MeshFacetArray &) default
copy-constructor
MeshFacetArray() [4/4]
MeshFacetArray::MeshFacetArray (MeshFacetArray &&) default
~MeshFacetArray()
MeshCore::MeshFacetArray::~MeshFacetArray () default
destructor
Member Function Documentation
DecrementIndices()
void MeshFacetArray::DecrementIndices (PointIndex ulIndex)
Decrements all point indices that are higher than ulIndex.
Definition at line 139 of file Elements.cpp.
Erase()
void MeshFacetArray::Erase (_TIterator pIter)
Removes the facet from the array the iterator points to. All neighbour indices of the other facets get adjusted.
Definition at line 110 of file Elements.cpp.
References MeshCore::FACET_INDEX_MAX, and SplineSurface::i.
Referenced by MeshCore::MeshKernel::DeleteFacet().
operator=() [1/2]
MeshFacetArray & MeshFacetArray::operator= (const MeshFacetArray & rclFAry) default
operator=() [2/2]
MeshFacetArray & MeshFacetArray::operator= (MeshFacetArray && rclFAry) default
ResetFlag()
void MeshFacetArray::ResetFlag (MeshFacet::TFlagType tF) const
Resets the flag for all facets.
Definition at line 156 of file Elements.cpp.
References SplineSurface::i.
Referenced by MeshCore::MeshTopoAlgorithm::AdjustEdgesToCurvatureDirection(), MeshCore::MeshAlgorithm::CheckBorderFacets(), MeshCore::MeshTopoAlgorithm::DelaunayFlip(), MeshCore::MeshKernel::GetPointFacets(), MeshCore::MeshAlgorithm::ResetFacetFlag(), and MeshCore::MeshAlgorithm::ResetFacetsFlag().
ResetInvalid()
void MeshFacetArray::ResetInvalid () const
Sets all facets invalid.
Definition at line 170 of file Elements.cpp.
Referenced by MeshCore::MeshRemoveNeedles::Fixup().
SetFlag()
void MeshFacetArray::SetFlag (MeshFacet::TFlagType tF) const
Sets the flag for all facets.
Definition at line 149 of file Elements.cpp.
References SplineSurface::i.
Referenced by MeshCore::MeshAlgorithm::GetFacetBorders(), MeshCore::MeshSearchNeighbours::NeighboursFacetFromFacet(), MeshCore::MeshSearchNeighbours::NeighboursFromFacet(), MeshCore::MeshSearchNeighbours::NeighboursFromSampledFacets(), MeshCore::MeshAlgorithm::SetFacetFlag(), MeshCore::MeshAlgorithm::SetFacetsFlag(), Mesh::MeshObject::splitEdges(), MeshCore::MeshKernel::VisitNeighbourFacets(), and MeshCore::MeshKernel::VisitNeighbourFacetsOverCorners().
SetProperty()
void MeshFacetArray::SetProperty (unsigned long ulVal) const
Sets the property for all facets.
Definition at line 163 of file Elements.cpp.
Referenced by MeshCore::MeshKernel::AddFacets(), and MeshCore::MeshAlgorithm::SetFacetsProperty().
TransposeIndices()
void MeshFacetArray::TransposeIndices (PointIndex ulOrig, PointIndex ulNew)
Checks and flips the point indices if needed.
See also
MeshFacet::Transpose().
Definition at line 129 of file Elements.cpp.
The documentation for this class was generated from the following files:
Elements.h
Elements.cpp