FreeCAD: Base::TimeElapsed Class Reference
Base::TimeElapsed Class Reference
#include <TimeInfo.h>
Public Member Functions
TimeElapsed ()
TimeElapsed (const TimeElapsed &)=default
TimeElapsed (TimeElapsed &&)=default
~TimeElapsed ()=default
void setCurrent ()
Static Public Member Functions
static float diffTimeF (const TimeElapsed &start, const TimeElapsed &end=TimeElapsed())
static std::string diffTime (const TimeElapsed &start, const TimeElapsed &end=TimeElapsed())
Detailed Description
Definition at line 120 of file TimeInfo.h.
Constructor & Destructor Documentation
TimeElapsed() [1/3]
Base::TimeElapsed::TimeElapsed () inline
Definition at line 123 of file TimeInfo.h.
Referenced by Base::TimeInfo::diffTime().
TimeElapsed() [2/3]
Base::TimeElapsed::TimeElapsed (const TimeElapsed &) default
TimeElapsed() [3/3]
Base::TimeElapsed::TimeElapsed (TimeElapsed &&) default
~TimeElapsed()
Base::TimeElapsed::~TimeElapsed () default
Member Function Documentation
diffTime()
static std::string Base::TimeElapsed::diffTime (const TimeElapsed & start, const TimeElapsed & end = TimeElapsed()) inline static
Definition at line 143 of file TimeInfo.h.
Referenced by Sketcher::Sketch::setUpSketch(), and Sketcher::Sketch::solve().
diffTimeF()
static float Base::TimeElapsed::diffTimeF (const TimeElapsed & start, const TimeElapsed & end = TimeElapsed()) inline static
Definition at line 137 of file TimeInfo.h.
Referenced by FemGui::ViewProviderFEMMeshBuilder::createMesh(), GCS::System::diagnose(), Gui::AutoSaver::saveDocument(), Sketcher::Sketch::solve(), and PartGui::ViewProviderPartExt::updateVisual().
setCurrent()
void Base::TimeElapsed::setCurrent () inline
Definition at line 132 of file TimeInfo.h.
Referenced by Base::TimeInfo::diffTime().
The documentation for this class was generated from the following file:
TimeInfo.h