FreeCAD: App::ExpressionModifier< P > Class Template Reference
App::ExpressionModifier< P > Class Template Reference
#include <Expression.h>
Public Member Functions
ExpressionModifier (P &_prop)
~ExpressionModifier () override=default
void aboutToChange () override
int changed () const override
void reset () override
App::PropertyLinkBase * getPropertyLink () override
Public Member Functions inherited from App::ExpressionVisitor
virtual ~ExpressionVisitor ()=default
virtual void visit (Expression &e)=0
Protected Attributes
P & prop
App::PropertyLinkBase * propLink
AtomicPropertyChangeInterface< P >::AtomicPropertyChange signaller
int _changed {0}
Additional Inherited Members
Protected Member Functions inherited from App::ExpressionVisitor
void getIdentifiers (Expression &e, std::map< App::ObjectIdentifier, bool > &)
bool adjustLinks (Expression &e, const std::set< App::DocumentObject * > &inList)
bool relabeledDocument (Expression &e, const std::string &oldName, const std::string &newName)
bool renameObjectIdentifier (Expression &e, const std::map< ObjectIdentifier, ObjectIdentifier > &, const ObjectIdentifier &)
void collectReplacement (Expression &e, std::map< ObjectIdentifier, ObjectIdentifier > &, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const
bool updateElementReference (Expression &e, App::DocumentObject *feature, bool reverse)
void importSubNames (Expression &e, const ObjectIdentifier::SubNameMap &subNameMap)
void updateLabelReference (Expression &e, App::DocumentObject *obj, const std::string &ref, const char *newLabel)
void moveCells (Expression &e, const CellAddress &address, int rowCount, int colCount)
void offsetCells (Expression &e, int rowOffset, int colOffset)
Detailed Description
template<class P>
class App::ExpressionModifier< P >
Definition at line 83 of file Expression.h.
Constructor & Destructor Documentation
ExpressionModifier()
template<class P > App::ExpressionModifier< P >::ExpressionModifier (P & _prop) inline explicit
Definition at line 85 of file Expression.h.
~ExpressionModifier()
template<class P > App::ExpressionModifier< P >::~ExpressionModifier () override default
Member Function Documentation
aboutToChange()
template<class P > void App::ExpressionModifier< P >::aboutToChange () inline override virtual
Reimplemented from App::ExpressionVisitor.
Definition at line 93 of file Expression.h.
References App::ExpressionModifier< P >::_changed, and App::ExpressionModifier< P >::signaller.
changed()
template<class P > int App::ExpressionModifier< P >::changed () const inline override virtual
Reimplemented from App::ExpressionVisitor.
Definition at line 98 of file Expression.h.
References App::ExpressionModifier< P >::_changed.
Referenced by Spreadsheet::PropertySheet::insertColumns(), Spreadsheet::PropertySheet::insertRows(), Spreadsheet::PropertySheet::pasteCells(), Spreadsheet::PropertySheet::removeColumns(), Spreadsheet::PropertySheet::removeRows(), and Spreadsheet::PropertySheet::updateElementReference().
getPropertyLink()
template<class P > App::PropertyLinkBase* App::ExpressionModifier< P >::getPropertyLink () inline override virtual
Reimplemented from App::ExpressionVisitor.
Definition at line 102 of file Expression.h.
References App::ExpressionModifier< P >::propLink.
reset()
template<class P > void App::ExpressionModifier< P >::reset () inline override virtual
Reimplemented from App::ExpressionVisitor.
Definition at line 100 of file Expression.h.
References App::ExpressionModifier< P >::_changed.
Referenced by ArchVRM.Renderer::__init__(), Spreadsheet::PropertySheet::insertColumns(), Spreadsheet::PropertySheet::insertRows(), Spreadsheet::PropertySheet::removeColumns(), Spreadsheet::PropertySheet::removeRows(), draftguitools.gui_trackers.gridTracker::set(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testAll(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testBuildings(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCommonPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCustom(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testExtrusions(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testHierarchy(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testIFC4(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testMaterials(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testQuantities(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testRectangleProfileDef(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSites(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSolid(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandardCases(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandards(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStoreys(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testTinyLines(), and bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testUndefined().
Member Data Documentation
_changed
template<class P > int App::ExpressionModifier< P >::_changed {0} protected
Definition at line 108 of file Expression.h.
Referenced by App::ExpressionModifier< P >::aboutToChange(), App::ExpressionModifier< P >::changed(), and App::ExpressionModifier< P >::reset().
prop
template<class P > P& App::ExpressionModifier< P >::prop protected
Definition at line 105 of file Expression.h.
Referenced by CAMTests.TestPathDressupDogboneII.MockFeaturePython::__getattr__(), CAMTests.TestPathDressupDogboneII.MockFeaturePython::addProperty(), Path.Base.Gui.Util.QuantitySpinBox::attachTo(), buildPsets.PropertyDefHandler::endElement(), Path.Base.Gui.Util.QuantitySpinBox::expression(), App::MoveCellsExpressionVisitor< P >::MoveCellsExpressionVisitor(), Path.Base.Gui.SetupSheetOpPrototype._PropertyEnumEditor::setEditorData(), Path.Base.Gui.SetupSheetOpPrototype._PropertyBoolEditor::setEditorData(), Path.Base.Gui.SetupSheetOpPrototype._PropertyStringEditor::setEditorData(), Path.Base.Gui.SetupSheetOpPrototype._PropertyAngleEditor::setEditorData(), Path.Base.Gui.SetupSheetOpPrototype._PropertyLengthEditor::setEditorData(), Path.Base.Gui.SetupSheetOpPrototype._PropertyPercentEditor::setEditorData(), Path.Base.Gui.SetupSheetOpPrototype._PropertyIntegerEditor::setEditorData(), Path.Base.Gui.SetupSheetOpPrototype._PropertyFloatEditor::setEditorData(), Path.Base.Gui.SetupSheetOpPrototype._PropertyFileEditor::setEditorData(), Path.Base.Gui.PropertyEditor._PropertyEditorEnumeration::setEditorData(), Path.Base.Gui.Util.QuantitySpinBox::setMinimum(), Path.Base.Gui.SetupSheetOpPrototype._PropertyEnumEditor::setModelData(), Path.Base.Gui.SetupSheetOpPrototype._PropertyBoolEditor::setModelData(), Path.Base.Gui.SetupSheetOpPrototype._PropertyStringEditor::setModelData(), Path.Base.Gui.SetupSheetOpPrototype._PropertyAngleEditor::setModelData(), Path.Base.Gui.SetupSheetOpPrototype._PropertyLengthEditor::setModelData(), Path.Base.Gui.SetupSheetOpPrototype._PropertyPercentEditor::setModelData(), Path.Base.Gui.SetupSheetOpPrototype._PropertyIntegerEditor::setModelData(), Path.Base.Gui.SetupSheetOpPrototype._PropertyFloatEditor::setModelData(), Path.Base.Gui.SetupSheetOpPrototype._PropertyFileEditor::setModelData(), Path.Base.Gui.PropertyEditor._PropertyEditor::setProperty(), buildPsets.PropertyDefHandler::startElement(), Path.Base.Gui.Util.QuantitySpinBox::updateProperty(), Path.Base.Gui.Util.QuantitySpinBox::updateSpinBox(), and Path.Base.Gui.SetupSheetOpPrototype._PropertyEnumEditor::widget().
propLink
template<class P > App::PropertyLinkBase* App::ExpressionModifier< P >::propLink protected
Definition at line 106 of file Expression.h.
Referenced by App::ExpressionModifier< P >::getPropertyLink().
signaller
template<class P > AtomicPropertyChangeInterface<P>::AtomicPropertyChange App::ExpressionModifier< P >::signaller protected
Definition at line 107 of file Expression.h.
Referenced by App::ExpressionModifier< P >::aboutToChange().
The documentation for this class was generated from the following file:
Expression.h