FreeCAD: SketcherGui::VisualLayer Class Reference
SketcherGui::VisualLayer Class Reference
#include <VisualLayer.h>
Public Member Functions
VisualLayer (unsigned int linePattern=0xFFFF, float lineWidth=3.0, bool visible=true)
unsigned int getLinePattern () const
float getLineWidth () const
void setLinePattern (unsigned int linepattern)
void setLineWidth (float linewidth)
bool isVisible () const
void setVisible (bool show)
void Save (Base::Writer &) const
void Restore (Base::XMLReader &)
Friends
bool operator== (VisualLayer const &lhs, VisualLayer const &rhs)
Detailed Description
Provides the visual layer configuration for a class of geometry. A class of geometry can be any grouping of geometry, for which the user wants to provide a per coin layer specific configuration.
Definition at line 43 of file VisualLayer.h.
Constructor & Destructor Documentation
VisualLayer()
VisualLayer::VisualLayer (unsigned int linePattern = 0xFFFF, float lineWidth = 3.0, bool visible = true) explicit
Definition at line 34 of file VisualLayer.cpp.
Member Function Documentation
getLinePattern()
unsigned int VisualLayer::getLinePattern () const
Definition at line 40 of file VisualLayer.cpp.
getLineWidth()
float VisualLayer::getLineWidth () const
Definition at line 45 of file VisualLayer.cpp.
isVisible()
bool VisualLayer::isVisible () const
Definition at line 60 of file VisualLayer.cpp.
Restore()
void VisualLayer::Restore (Base::XMLReader & reader)
Definition at line 79 of file VisualLayer.cpp.
References TechDrawTools.TaskFillTemplateFields::reader, and Path.Post.scripts.refactored_centroid_post::str.
Referenced by SketcherGui::PropertyVisualLayerList::Restore().
Save()
void VisualLayer::Save (Base::Writer & writer) const
Definition at line 70 of file VisualLayer.cpp.
References Base::Writer::ind(), and Base::Writer::Stream().
setLinePattern()
void VisualLayer::setLinePattern (unsigned int linepattern)
Definition at line 50 of file VisualLayer.cpp.
setLineWidth()
void VisualLayer::setLineWidth (float linewidth)
Definition at line 55 of file VisualLayer.cpp.
setVisible()
void VisualLayer::setVisible (bool show)
Definition at line 65 of file VisualLayer.cpp.
References bimcommands.BimViews::show().
Friends And Related Function Documentation
operator==
bool operator== (VisualLayer const & lhs, VisualLayer const & rhs) friend
Definition at line 70 of file VisualLayer.h.
The documentation for this class was generated from the following files:
VisualLayer.h
VisualLayer.cpp