FreeCAD: geoff_geometry::Vector3d Class Reference
geoff_geometry::Vector3d Class Reference
#include <geometry.h>
Public Member Functions
Vector3d ()
Vector3d (double x, double y, double z=0)
Vector3d (const double *x)
Vector3d (const double *x0, const double *x1)
Vector3d (const Point3d &p0, const Point3d &p1)
Vector3d (const Point3d &p)
Vector3d (const Vector2d &v)
bool operator== (const Vector3d &v) const
bool operator!= (const Vector3d &v) const
Point3d operator+ (const Point3d &p) const
Vector3d operator+ (const Vector3d &v) const
const Vector3d & operator+= (const Vector3d &v)
Vector3d operator- (const Vector3d &v) const
const Vector3d & operator-= (const Vector3d &v)
const Vector3d operator- (void) const
double operator* (const Vector3d &v) const
const Vector3d & operator*= (double c)
const Vector3d operator^ (const Vector3d &v) const
void get (double xyz[3]) const
double getx () const
double gety () const
double getz () const
void putx (double x)
void puty (double y)
void putz (double z)
double normalise ()
double magnitude (void) const
double magnitudeSq (void) const
void Transform (const Matrix &m)
void arbitrary_axes (Vector3d &x, Vector3d &y)
int setCartesianAxes (Vector3d &b, Vector3d &c)
double * getBuffer ()
const double * getBuffer () const
Friends
wostream & operator<< (wostream &op, Vector3d &v)
const friend Vector3d operator* (const Vector3d &v, double c)
const friend Vector3d operator* (double c, const Vector3d &v)
const friend Vector3d operator/ (const Vector3d &v, double c)
Detailed Description
Definition at line 568 of file geometry.h.
Constructor & Destructor Documentation
Vector3d() [1/7]
geoff_geometry::Vector3d::Vector3d () inline
Definition at line 577 of file geometry.h.
Vector3d() [2/7]
geoff_geometry::Vector3d::Vector3d (double x, double y, double z = 0) inline
Definition at line 584 of file geometry.h.
References MovieTool::x, and MovieTool::y.
Vector3d() [3/7]
geoff_geometry::Vector3d::Vector3d (const double * x) inline
Definition at line 589 of file geometry.h.
References MovieTool::x.
Vector3d() [4/7]
geoff_geometry::Vector3d::Vector3d (const double * x0, const double * x1) inline
Definition at line 594 of file geometry.h.
Vector3d() [5/7]
geoff_geometry::Vector3d::Vector3d (const Point3d & p0, const Point3d & p1) inline
Definition at line 599 of file geometry.h.
References geoff_geometry::Point3d::x, geoff_geometry::Point3d::y, and geoff_geometry::Point3d::z.
Vector3d() [6/7]
geoff_geometry::Vector3d::Vector3d (const Point3d & p) inline
Definition at line 605 of file geometry.h.
References buildPsets::p.
Vector3d() [7/7]
geoff_geometry::Vector3d::Vector3d (const Vector2d & v) inline
Definition at line 611 of file geometry.h.
References TestSpreadsheet::v.
Member Function Documentation
arbitrary_axes()
void Vector3d::arbitrary_axes (Vector3d & x, Vector3d & y)
Definition at line 584 of file Mod/CAM/libarea/kurve/Matrix.cpp.
References getx(), gety(), MovieTool::x, MovieTool::y, Y_VECTOR, and Z_VECTOR.
Referenced by setCartesianAxes().
get()
void geoff_geometry::Vector3d::get (double xyz[3]) const inline
Definition at line 707 of file geometry.h.
Referenced by draftguitools.gui_trackers.editTracker::move().
getBuffer() [1/2]
double* geoff_geometry::Vector3d::getBuffer () inline
Definition at line 760 of file geometry.h.
getBuffer() [2/2]
const double* geoff_geometry::Vector3d::getBuffer () const inline
Definition at line 764 of file geometry.h.
getx()
double geoff_geometry::Vector3d::getx () const inline
Definition at line 713 of file geometry.h.
Referenced by arbitrary_axes(), geoff_geometry::Intof(), geoff_geometry::Plane::Mirrored(), and geoff_geometry::Matrix::Rotate().
gety()
double geoff_geometry::Vector3d::gety () const inline
Definition at line 717 of file geometry.h.
Referenced by arbitrary_axes(), geoff_geometry::Intof(), geoff_geometry::Plane::Mirrored(), and geoff_geometry::Matrix::Rotate().
getz()
double geoff_geometry::Vector3d::getz () const inline
Definition at line 721 of file geometry.h.
Referenced by geoff_geometry::Line::atZ(), geoff_geometry::Intof(), geoff_geometry::Plane::Mirrored(), geoff_geometry::Matrix::Rotate(), and geoff_geometry::tangential_arc().
magnitude()
double geoff_geometry::Vector3d::magnitude (void) const inline
Definition at line 749 of file geometry.h.
References KDL::sqrt().
Referenced by ifc4.ifcaxis2placement3d::axistorefdirposition(), geoff_geometry::Dist(), geoff_geometry::Line::Line(), ifc2x3.ifcaxis2placement3d::wr4(), config_control_design.axis2_placement_3d::wr4(), automotive_design.axis2_placement_3d::wr4(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.axis2_placement_3d::wr4().
magnitudeSq()
double geoff_geometry::Vector3d::magnitudeSq (void) const inline
Definition at line 753 of file geometry.h.
Referenced by geoff_geometry::DistSq().
normalise()
double geoff_geometry::Vector3d::normalise () inline
Definition at line 737 of file geometry.h.
References SCL.SimpleDataTypes::e, and test::m.
Referenced by geoff_geometry::Triangle3d::Intof(), geoff_geometry::Plane::Plane(), and Transform().
operator!=()
bool geoff_geometry::Vector3d::operator!= (const Vector3d & v) const inline
Definition at line 624 of file geometry.h.
References TestSpreadsheet::v.
operator*()
double geoff_geometry::Vector3d::operator* (const Vector3d & v) const inline
Definition at line 674 of file geometry.h.
References TestSpreadsheet::v.
operator*=()
const Vector3d& geoff_geometry::Vector3d::operator*= (double c) inline
Definition at line 679 of file geometry.h.
References SCL.SimpleDataTypes::c.
operator+() [1/2]
Point3d geoff_geometry::Vector3d::operator+ (const Point3d & p) const inline
Definition at line 642 of file geometry.h.
References buildPsets::p.
operator+() [2/2]
Vector3d geoff_geometry::Vector3d::operator+ (const Vector3d & v) const inline
Definition at line 646 of file geometry.h.
References TestSpreadsheet::v.
operator+=()
const Vector3d& geoff_geometry::Vector3d::operator+= (const Vector3d & v) inline
Definition at line 650 of file geometry.h.
References TestSpreadsheet::v.
operator-() [1/2]
Vector3d geoff_geometry::Vector3d::operator- (const Vector3d & v) const inline
Definition at line 657 of file geometry.h.
References TestSpreadsheet::v.
operator-() [2/2]
const Vector3d geoff_geometry::Vector3d::operator- (void) const inline
Definition at line 669 of file geometry.h.
operator-=()
const Vector3d& geoff_geometry::Vector3d::operator-= (const Vector3d & v) inline
Definition at line 661 of file geometry.h.
References TestSpreadsheet::v.
operator==()
bool geoff_geometry::Vector3d::operator== (const Vector3d & v) const inline
Definition at line 619 of file geometry.h.
References geoff_geometry::FEQ(), geoff_geometry::UNIT_VECTOR_TOLERANCE, and TestSpreadsheet::v.
operator^()
const Vector3d geoff_geometry::Vector3d::operator^ (const Vector3d & v) const inline
Definition at line 699 of file geometry.h.
References TestSpreadsheet::v.
putx()
void geoff_geometry::Vector3d::putx (double x) inline
Definition at line 725 of file geometry.h.
References MovieTool::x.
puty()
void geoff_geometry::Vector3d::puty (double y) inline
Definition at line 729 of file geometry.h.
References MovieTool::y.
putz()
void geoff_geometry::Vector3d::putz (double z) inline
Definition at line 733 of file geometry.h.
setCartesianAxes()
int Vector3d::setCartesianAxes (Vector3d & b, Vector3d & c)
Definition at line 600 of file Mod/CAM/libarea/kurve/Matrix.cpp.
References a, arbitrary_axes(), SCL.SimpleDataTypes::b, SCL.SimpleDataTypes::c, KDL::epsilon, geoff_geometry::FAILURE(), and NULL_VECTOR.
Transform()
void Vector3d::Transform (const Matrix & m)
Definition at line 570 of file Mod/CAM/libarea/kurve/Matrix.cpp.
References test::m, and normalise().
Friends And Related Function Documentation
operator* [1/2]
const friend Vector3d operator* (const Vector3d & v, double c) friend
Definition at line 686 of file geometry.h.
operator* [2/2]
const friend Vector3d operator* (double c, const Vector3d & v) friend
Definition at line 690 of file geometry.h.
operator/
const friend Vector3d operator/ (const Vector3d & v, double c) friend
Definition at line 694 of file geometry.h.
operator<<
wostream& operator<< (wostream & op, Vector3d & v) friend
Definition at line 127 of file Construction.cpp.
The documentation for this class was generated from the following files:
geometry.h
Mod/CAM/libarea/kurve/Matrix.cpp