FreeCAD: Path.Post.scripts.wedm_post Namespace Reference
Path.Post.scripts.wedm_post Namespace Reference
Functions
def processArguments (argstring)
def export (objectslist, filename, argstring)
def linenumber ()
def parse (pathobj)
Variables
TOOLTIP
now
parser
prog
add_help
action = "store_true",
help = "don't pop up editor before writing output",
default = "",
TOOLTIP_ARGS
OUTPUT_COMMENTS
COMMENT_CHAR
COMMAND_SPACE
ENDLINE
OUTPUT_HEADER
OUTPUT_LINE_NUMBERS
SHOW_EDITOR
MODAL
USE_TLO
OUTPUT_DOUBLES
LINENR
USE_RAPIDS
OMIT_UNITS
RELATIVE_GCODE
TWO_DIGIT_CODES
FORCE_SIGN
UNITS
UNIT_SPEED_FORMAT
UNIT_FORMAT
MACHINE_NAME
CORNER_MIN
CORNER_MAX
PRECISION
PREAMBLE
POSTAMBLE
PRE_OPERATION
POST_OPERATION
TOOL_CHANGE
Function Documentation
export()
def Path.Post.scripts.wedm_post.export (objectslist, filename, argstring)
Definition at line 247 of file wedm_post.py.
References Path.Post.scripts.wedm_post.linenumber(), Path.Post.scripts.wedm_post.parse(), Path.Post.scripts.wedm_post.processArguments(), and Path.Post.scripts.refactored_centroid_post.str.
linenumber()
def Path.Post.scripts.wedm_post.linenumber ()
Definition at line 382 of file wedm_post.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.scripts.wedm_post.export(), and Path.Post.scripts.wedm_post.parse().
parse()
def Path.Post.scripts.wedm_post.parse (pathobj)
Definition at line 390 of file wedm_post.py.
References Path.Post.scripts.wedm_post.linenumber(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.scripts.wedm_post.export().
processArguments()
def Path.Post.scripts.wedm_post.processArguments (argstring)
Definition at line 165 of file wedm_post.py.
Referenced by Path.Post.scripts.wedm_post.export().
Variable Documentation
action
string Path.Post.scripts.wedm_post.action = "store_true",
Definition at line 51 of file wedm_post.py.
add_help
Path.Post.scripts.wedm_post.add_help
Definition at line 50 of file wedm_post.py.
COMMAND_SPACE
Path.Post.scripts.wedm_post.COMMAND_SPACE
Definition at line 119 of file wedm_post.py.
COMMENT_CHAR
Path.Post.scripts.wedm_post.COMMENT_CHAR
Definition at line 118 of file wedm_post.py.
CORNER_MAX
Path.Post.scripts.wedm_post.CORNER_MAX
Definition at line 141 of file wedm_post.py.
CORNER_MIN
Path.Post.scripts.wedm_post.CORNER_MIN
Definition at line 140 of file wedm_post.py.
default
string Path.Post.scripts.wedm_post.default = "",
Definition at line 54 of file wedm_post.py.
ENDLINE
Path.Post.scripts.wedm_post.ENDLINE
Definition at line 120 of file wedm_post.py.
FORCE_SIGN
Path.Post.scripts.wedm_post.FORCE_SIGN
Definition at line 132 of file wedm_post.py.
help
string Path.Post.scripts.wedm_post.help = "don't pop up editor before writing output",
Definition at line 51 of file wedm_post.py.
LINENR
Path.Post.scripts.wedm_post.LINENR
Definition at line 127 of file wedm_post.py.
MACHINE_NAME
Path.Post.scripts.wedm_post.MACHINE_NAME
Definition at line 139 of file wedm_post.py.
MODAL
Path.Post.scripts.wedm_post.MODAL
Definition at line 124 of file wedm_post.py.
now
Path.Post.scripts.wedm_post.now
Definition at line 48 of file wedm_post.py.
OMIT_UNITS
Path.Post.scripts.wedm_post.OMIT_UNITS
Definition at line 129 of file wedm_post.py.
OUTPUT_COMMENTS
Path.Post.scripts.wedm_post.OUTPUT_COMMENTS
Definition at line 117 of file wedm_post.py.
OUTPUT_DOUBLES
Path.Post.scripts.wedm_post.OUTPUT_DOUBLES
Definition at line 126 of file wedm_post.py.
OUTPUT_HEADER
Path.Post.scripts.wedm_post.OUTPUT_HEADER
Definition at line 121 of file wedm_post.py.
OUTPUT_LINE_NUMBERS
Path.Post.scripts.wedm_post.OUTPUT_LINE_NUMBERS
Definition at line 122 of file wedm_post.py.
parser
Path.Post.scripts.wedm_post.parser
Definition at line 50 of file wedm_post.py.
POST_OPERATION
Path.Post.scripts.wedm_post.POST_OPERATION
Definition at line 159 of file wedm_post.py.
POSTAMBLE
Path.Post.scripts.wedm_post.POSTAMBLE
Definition at line 150 of file wedm_post.py.
PRE_OPERATION
Path.Post.scripts.wedm_post.PRE_OPERATION
Definition at line 156 of file wedm_post.py.
PREAMBLE
Path.Post.scripts.wedm_post.PREAMBLE
Definition at line 145 of file wedm_post.py.
PRECISION
Path.Post.scripts.wedm_post.PRECISION
Definition at line 142 of file wedm_post.py.
prog
Path.Post.scripts.wedm_post.prog
Definition at line 50 of file wedm_post.py.
RELATIVE_GCODE
Path.Post.scripts.wedm_post.RELATIVE_GCODE
Definition at line 130 of file wedm_post.py.
SHOW_EDITOR
Path.Post.scripts.wedm_post.SHOW_EDITOR
Definition at line 123 of file wedm_post.py.
TOOL_CHANGE
Path.Post.scripts.wedm_post.TOOL_CHANGE
Definition at line 162 of file wedm_post.py.
TOOLTIP
Path.Post.scripts.wedm_post.TOOLTIP
Definition at line 37 of file wedm_post.py.
TOOLTIP_ARGS
Path.Post.scripts.wedm_post.TOOLTIP_ARGS
Definition at line 114 of file wedm_post.py.
TWO_DIGIT_CODES
Path.Post.scripts.wedm_post.TWO_DIGIT_CODES
Definition at line 131 of file wedm_post.py.
UNIT_FORMAT
Path.Post.scripts.wedm_post.UNIT_FORMAT
Definition at line 137 of file wedm_post.py.
UNIT_SPEED_FORMAT
Path.Post.scripts.wedm_post.UNIT_SPEED_FORMAT
Definition at line 136 of file wedm_post.py.
UNITS
Path.Post.scripts.wedm_post.UNITS
Definition at line 135 of file wedm_post.py.
USE_RAPIDS
Path.Post.scripts.wedm_post.USE_RAPIDS
Definition at line 128 of file wedm_post.py.
USE_TLO
Path.Post.scripts.wedm_post.USE_TLO
Definition at line 125 of file wedm_post.py.