FreeCAD: Gui::UIntSpinBoxPrivate Class Reference
Gui::UIntSpinBoxPrivate Class Reference
Public Member Functions
UIntSpinBoxPrivate ()=default
uint mapToUInt (int v) const
int mapToInt (uint v) const
Public Attributes
UnsignedValidator * mValidator {nullptr}
Detailed Description
Definition at line 277 of file SpinBox.cpp.
Constructor & Destructor Documentation
UIntSpinBoxPrivate()
Gui::UIntSpinBoxPrivate::UIntSpinBoxPrivate () default
Member Function Documentation
mapToInt()
int Gui::UIntSpinBoxPrivate::mapToInt (uint v) const inline
Definition at line 296 of file SpinBox.cpp.
References TestSpreadsheet::v.
Referenced by Gui::UIntSpinBox::setRange(), Gui::UIntSpinBox::setValue(), and Gui::UIntSpinBox::valueFromText().
mapToUInt()
uint Gui::UIntSpinBoxPrivate::mapToUInt (int v) const inline
Definition at line 283 of file SpinBox.cpp.
References TestSpreadsheet::v.
Referenced by Gui::UIntSpinBox::maximum(), Gui::UIntSpinBox::minimum(), Gui::UIntSpinBox::textFromValue(), and Gui::UIntSpinBox::value().
Member Data Documentation
mValidator
UnsignedValidator* Gui::UIntSpinBoxPrivate::mValidator {nullptr}
Definition at line 280 of file SpinBox.cpp.
Referenced by Gui::UIntSpinBox::UIntSpinBox(), Gui::UIntSpinBox::validate(), and Gui::UIntSpinBox::~UIntSpinBox().
The documentation for this class was generated from the following file:
SpinBox.cpp