FreeCAD: Base::ConsoleRefreshDisabler Class Reference
Base::ConsoleRefreshDisabler Class Reference
#include <Console.h>
Public Member Functions
ConsoleRefreshDisabler ()
~ConsoleRefreshDisabler ()
ConsoleRefreshDisabler (const ConsoleRefreshDisabler &)=delete
ConsoleRefreshDisabler (ConsoleRefreshDisabler &&)=delete
ConsoleRefreshDisabler & operator= (const ConsoleRefreshDisabler &)=delete
ConsoleRefreshDisabler & operator= (ConsoleRefreshDisabler &&)=delete
Detailed Description
Definition at line 928 of file Console.h.
Constructor & Destructor Documentation
ConsoleRefreshDisabler() [1/3]
Base::ConsoleRefreshDisabler::ConsoleRefreshDisabler () inline
Definition at line 931 of file Console.h.
References Base::Console(), and Base::ConsoleSingleton::EnableRefresh().
~ConsoleRefreshDisabler()
Base::ConsoleRefreshDisabler::~ConsoleRefreshDisabler () inline
Definition at line 936 of file Console.h.
References Base::Console(), and Base::ConsoleSingleton::EnableRefresh().
ConsoleRefreshDisabler() [2/3]
Base::ConsoleRefreshDisabler::ConsoleRefreshDisabler (const ConsoleRefreshDisabler &) delete
ConsoleRefreshDisabler() [3/3]
Base::ConsoleRefreshDisabler::ConsoleRefreshDisabler (ConsoleRefreshDisabler &&) delete
Member Function Documentation
operator=() [1/2]
ConsoleRefreshDisabler& Base::ConsoleRefreshDisabler::operator= (ConsoleRefreshDisabler &&) delete
operator=() [2/2]
ConsoleRefreshDisabler& Base::ConsoleRefreshDisabler::operator= (const ConsoleRefreshDisabler &) delete
The documentation for this class was generated from the following file:
Console.h