FreeCAD: Base::OutputStream Class Reference
Base::OutputStream Class Reference
#include <Stream.h>
Public Member Functions
OutputStream (std::ostream &rout)
~OutputStream () override
OutputStream & operator<< (bool b)
OutputStream & operator<< (int8_t ch)
OutputStream & operator<< (uint8_t uch)
OutputStream & operator<< (int16_t s)
OutputStream & operator<< (uint16_t us)
OutputStream & operator<< (int32_t i)
OutputStream & operator<< (uint32_t ui)
OutputStream & operator<< (int64_t l)
OutputStream & operator<< (uint64_t ul)
OutputStream & operator<< (float f)
OutputStream & operator<< (double d)
OutputStream & write (const char *s, int n)
OutputStream (const OutputStream &)=delete
OutputStream (OutputStream &&)=delete
void operator= (const OutputStream &)=delete
void operator= (OutputStream &&)=delete
Public Member Functions inherited from Base::Stream
ByteOrder byteOrder () const
void setByteOrder (ByteOrder)
virtual ~Stream ()
Additional Inherited Members
Public Types inherited from Base::Stream
enum ByteOrder { BigEndian, LittleEndian }
Protected Member Functions inherited from Base::Stream
Stream ()
Stream (const Stream &)=default
Stream (Stream &&)=default
Stream & operator= (const Stream &)=default
Stream & operator= (Stream &&)=default
bool isSwapped () const
Detailed Description
The OutputStream class provides writing of binary data to an ostream.
Author
Werner Mayer
Definition at line 80 of file Stream.h.
Constructor & Destructor Documentation
OutputStream() [1/3]
OutputStream::OutputStream (std::ostream & rout) explicit
Definition at line 57 of file Stream.cpp.
~OutputStream()
OutputStream::~OutputStream () override default
OutputStream() [2/3]
Base::OutputStream::OutputStream (const OutputStream &) delete
OutputStream() [3/3]
Base::OutputStream::OutputStream (OutputStream &&) delete
Member Function Documentation
operator<<() [1/11]
OutputStream & OutputStream::operator<< (bool b)
Definition at line 63 of file Stream.cpp.
References SCL.SimpleDataTypes::b.
operator<<() [2/11]
OutputStream & OutputStream::operator<< (double d)
Definition at line 144 of file Stream.cpp.
References Base::Stream::isSwapped().
operator<<() [3/11]
OutputStream & OutputStream::operator<< (float f)
Definition at line 135 of file Stream.cpp.
References SCL.SimpleDataTypes::f, and Base::Stream::isSwapped().
operator<<() [4/11]
OutputStream & OutputStream::operator<< (int16_t s)
Definition at line 81 of file Stream.cpp.
References Base::Stream::isSwapped(), and toolbit-attributes::s.
operator<<() [5/11]
OutputStream & OutputStream::operator<< (int32_t i)
Definition at line 99 of file Stream.cpp.
References SplineSurface::i, and Base::Stream::isSwapped().
operator<<() [6/11]
OutputStream & OutputStream::operator<< (int64_t l)
Definition at line 117 of file Stream.cpp.
References Base::Stream::isSwapped(), and RobotExample::l.
operator<<() [7/11]
OutputStream & OutputStream::operator<< (int8_t ch)
Definition at line 69 of file Stream.cpp.
operator<<() [8/11]
OutputStream & OutputStream::operator<< (uint16_t us)
Definition at line 90 of file Stream.cpp.
References Base::Stream::isSwapped().
operator<<() [9/11]
OutputStream & OutputStream::operator<< (uint32_t ui)
Definition at line 108 of file Stream.cpp.
References Base::Stream::isSwapped().
operator<<() [10/11]
OutputStream & OutputStream::operator<< (uint64_t ul)
Definition at line 126 of file Stream.cpp.
References Base::Stream::isSwapped().
operator<<() [11/11]
OutputStream & OutputStream::operator<< (uint8_t uch)
Definition at line 75 of file Stream.cpp.
operator=() [1/2]
void Base::OutputStream::operator= (const OutputStream &) delete
operator=() [2/2]
void Base::OutputStream::operator= (OutputStream &&) delete
write()
OutputStream & OutputStream::write (const char * s, int n)
Definition at line 153 of file Stream.cpp.
References toolbit-attributes::s.
The documentation for this class was generated from the following files:
Stream.h
Stream.cpp