FreeCAD: TechDrawGui::QGIDecoration Class Reference
TechDrawGui::QGIDecoration Class Reference
#include <QGIDecoration.h>
Public Types
enum { Type = QGraphicsItem::UserType + 173 }
Public Member Functions
QGIDecoration ()
~QGIDecoration () override=default
int type () const override
QRectF boundingRect () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
virtual void draw ()
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
virtual void onDragFinished ()
void setWidth (double w)
double getWidth ()
void setStyle (Qt::PenStyle s)
void setColor (QColor c)
QColor getColor ()
void setFill (Qt::BrushStyle bs)
void makeMark (double x, double y)
void makeMark (Base::Vector3d v)
Protected Member Functions
void setPrettyNormal ()
void setPrettyPre ()
void setPrettySel ()
virtual QColor prefNormalColor ()
virtual QColor prefPreColor ()
virtual QColor prefSelectColor ()
Protected Attributes
QPen m_pen
QBrush m_brush
QColor m_colCurrent
QColor m_colNormal
double m_width
Qt::PenStyle m_styleCurrent
Qt::BrushStyle m_brushCurrent
int m_dragState
Detailed Description
Definition at line 50 of file QGIDecoration.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 55 of file QGIDecoration.h.
Constructor & Destructor Documentation
QGIDecoration()
QGIDecoration::QGIDecoration () explicit
Definition at line 40 of file QGIDecoration.cpp.
References black, and setWidth().
~QGIDecoration()
TechDrawGui::QGIDecoration::~QGIDecoration () override default
Member Function Documentation
boundingRect()
QRectF QGIDecoration::boundingRect () const override
Definition at line 104 of file QGIDecoration.cpp.
draw()
void QGIDecoration::draw () virtual
Reimplemented in TechDrawGui::QGIHighlight, TechDrawGui::QGIBreakLine, TechDrawGui::QGISectionLine, TechDrawGui::QGICenterLine, and TechDrawGui::QGITile.
Definition at line 55 of file QGIDecoration.cpp.
getColor()
QColor TechDrawGui::QGIDecoration::getColor () inline
Definition at line 75 of file QGIDecoration.h.
Referenced by TechDrawGui::QGISectionLine::getSectionColor().
getWidth()
double TechDrawGui::QGIDecoration::getWidth () inline
Definition at line 72 of file QGIDecoration.h.
Referenced by TechDrawGui::QGISectionLine::makeChangePointMarks(), and TechDrawGui::QGISectionLine::makeExtensionLine().
makeMark() [1/2]
void QGIDecoration::makeMark (Base::Vector3d v)
Definition at line 120 of file QGIDecoration.cpp.
References makeMark(), and TestSpreadsheet::v.
makeMark() [2/2]
void QGIDecoration::makeMark (double x, double y)
Definition at line 110 of file QGIDecoration.cpp.
References TechDrawGui::QGICMark::setSize(), TechDrawGui::QGICMark::setThick(), ZVALUE::VERTEX, MovieTool::x, and MovieTool::y.
Referenced by makeMark().
mouseMoveEvent()
void QGIDecoration::mouseMoveEvent (QGraphicsSceneMouseEvent * event) override
Definition at line 133 of file QGIDecoration.cpp.
References DECORDRAGGING, DECORDRAGSTARTED, and m_dragState.
mousePressEvent()
void QGIDecoration::mousePressEvent (QGraphicsSceneMouseEvent * event) override
Definition at line 125 of file QGIDecoration.cpp.
References DECORDRAGSTARTED, and m_dragState.
Referenced by TechDrawGui::QGIGhostHighlight::mousePressEvent().
mouseReleaseEvent()
void QGIDecoration::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) override
Definition at line 141 of file QGIDecoration.cpp.
References DECORDRAGGING, DECORNODRAG, m_dragState, and onDragFinished().
Referenced by TechDrawGui::QGIGhostHighlight::mouseReleaseEvent().
onDragFinished()
void QGIDecoration::onDragFinished () virtual
Reimplemented in TechDrawGui::QGIHighlight.
Definition at line 152 of file QGIDecoration.cpp.
Referenced by mouseReleaseEvent().
paint()
void QGIDecoration::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) override
Definition at line 59 of file QGIDecoration.cpp.
Referenced by TechDrawGui::QGISectionLine::paint(), TechDrawGui::QGIHighlight::paint(), and TechDrawGui::QGIBreakLine::paint().
prefNormalColor()
QColor QGIDecoration::prefNormalColor () protected virtual
Definition at line 89 of file QGIDecoration.cpp.
References TechDrawGui::PreferencesGui::normalQColor().
Referenced by TechDrawGui::QGITile::QGITile().
prefPreColor()
QColor QGIDecoration::prefPreColor () protected virtual
Definition at line 94 of file QGIDecoration.cpp.
References TechDrawGui::PreferencesGui::preselectQColor().
Referenced by TechDrawGui::QGITile::setPrettyPre().
prefSelectColor()
QColor QGIDecoration::prefSelectColor () protected virtual
Definition at line 99 of file QGIDecoration.cpp.
References TechDrawGui::PreferencesGui::selectQColor().
Referenced by TechDrawGui::QGITile::setPrettySel().
setColor()
void QGIDecoration::setColor (QColor c)
Definition at line 81 of file QGIDecoration.cpp.
References SCL.SimpleDataTypes::c, m_brush, m_colCurrent, m_colNormal, and m_pen.
Referenced by TechDrawGui::QGIViewPart::drawCenterLines(), TechDrawGui::QGISectionLine::QGISectionLine(), and TechDrawGui::QGISectionLine::setSectionColor().
setFill()
void TechDrawGui::QGIDecoration::setFill (Qt::BrushStyle bs) inline
Definition at line 76 of file QGIDecoration.h.
References SplineSurface::bs.
setPrettyNormal()
void TechDrawGui::QGIDecoration::setPrettyNormal () protected
setPrettyPre()
void TechDrawGui::QGIDecoration::setPrettyPre () protected
setPrettySel()
void TechDrawGui::QGIDecoration::setPrettySel () protected
setStyle()
void QGIDecoration::setStyle (Qt::PenStyle s)
Definition at line 75 of file QGIDecoration.cpp.
References m_pen, m_styleCurrent, and toolbit-attributes::s.
setWidth()
void QGIDecoration::setWidth (double w)
Definition at line 69 of file QGIDecoration.cpp.
References m_pen, m_width, and src.Mod.PartDesign.fcgear.svggear::w.
Referenced by TechDrawGui::QGIViewPart::drawBreakLines(), TechDrawGui::QGIViewPart::drawCenterLines(), TechDrawGui::QGIViewPart::drawComplexSectionLine(), TechDrawGui::QGIViewPart::drawSectionLine(), QGIDecoration(), TechDrawGui::QGIHighlight::QGIHighlight(), and TechDrawGui::QGISectionLine::QGISectionLine().
type()
int TechDrawGui::QGIDecoration::type () const inline override
Definition at line 56 of file QGIDecoration.h.
Member Data Documentation
m_brush
QBrush TechDrawGui::QGIDecoration::m_brush protected
Definition at line 88 of file QGIDecoration.h.
Referenced by setColor(), TechDrawGui::QGISectionLine::setTools(), and TechDrawGui::QGIHighlight::setTools().
m_brushCurrent
Qt::BrushStyle TechDrawGui::QGIDecoration::m_brushCurrent protected
Definition at line 93 of file QGIDecoration.h.
Referenced by TechDrawGui::QGISectionLine::setTools(), and TechDrawGui::QGIHighlight::setTools().
m_colCurrent
QColor TechDrawGui::QGIDecoration::m_colCurrent protected
Definition at line 89 of file QGIDecoration.h.
Referenced by TechDrawGui::QGITile::makeText(), TechDrawGui::QGITile::QGITile(), setColor(), TechDrawGui::QGITile::setPrettyNormal(), TechDrawGui::QGITile::setPrettyPre(), TechDrawGui::QGITile::setPrettySel(), TechDrawGui::QGISectionLine::setTools(), and TechDrawGui::QGIHighlight::setTools().
m_colNormal
QColor TechDrawGui::QGIDecoration::m_colNormal protected
Definition at line 90 of file QGIDecoration.h.
Referenced by TechDrawGui::QGITile::QGITile(), setColor(), and TechDrawGui::QGITile::setPrettyNormal().
m_dragState
int TechDrawGui::QGIDecoration::m_dragState protected
Definition at line 95 of file QGIDecoration.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
m_pen
QPen TechDrawGui::QGIDecoration::m_pen protected
Definition at line 87 of file QGIDecoration.h.
Referenced by setColor(), TechDrawGui::QGISectionLine::setLinePen(), TechDrawGui::QGIHighlight::setLinePen(), setStyle(), TechDrawGui::QGISectionLine::setTools(), TechDrawGui::QGIHighlight::setTools(), and setWidth().
m_styleCurrent
Qt::PenStyle TechDrawGui::QGIDecoration::m_styleCurrent protected
Definition at line 92 of file QGIDecoration.h.
Referenced by setStyle().
m_width
double TechDrawGui::QGIDecoration::m_width protected
Definition at line 91 of file QGIDecoration.h.
Referenced by TechDrawGui::QGISectionLine::setTools(), TechDrawGui::QGIHighlight::setTools(), and setWidth().
The documentation for this class was generated from the following files:
QGIDecoration.h
QGIDecoration.cpp