FreeCAD: PartGui::DlgScale Class Reference
PartGui::DlgScale Class Reference
#include <DlgScale.h>
Public Member Functions
DlgScale (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~DlgScale ()=default
void accept () override
void apply ()
void reject () override
std::vector< App::DocumentObject * > getShapesToScale () const
bool validate ()
void writeParametersToFeature (App::DocumentObject &feature, App::DocumentObject *base) const
update a FeatureScale with the parameters from the UI
Protected Member Functions
void findShapes ()
bool canScale (const TopoDS_Shape &) const
return true if shape can be scaled.
void changeEvent (QEvent *e) override
Detailed Description
Definition at line 38 of file DlgScale.h.
Constructor & Destructor Documentation
DlgScale()
DlgScale::DlgScale (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags())
Definition at line 60 of file DlgScale.cpp.
References Gui::ItemViewSelection::applyFrom(), Base::Persistence::getClassTypeId(), Base::UnitsApi::getDecimals(), draftutils.utils::getObjectsOfType, and Gui::Selection().
~DlgScale()
PartGui::DlgScale::~DlgScale () default
Member Function Documentation
accept()
void DlgScale::accept () override
Definition at line 180 of file DlgScale.cpp.
References apply(), Base::Console(), and Base::ConsoleSingleton::Message().
Referenced by PartGui::TaskScale::accept().
apply()
void DlgScale::apply ()
Definition at line 192 of file DlgScale.cpp.
References App::Document::commitTransaction(), copyVisual, FC_ERR, FCMD_OBJ_DOC_CMD, FCMD_OBJ_HIDE, App::GetApplication(), ParameterGrp::GetBool(), App::Application::getDocument(), ParameterGrp::GetGroup(), getShapesToScale(), Part::Feature::getTopoShape(), App::Application::GetUserParameter(), draftgeoutils.general::isNull(), importers.importIFCmulticore::objects, App::Document::openTransaction(), src.Mod.AddonManager.Addon::translate, Gui::Command::updateActive(), validate(), Base::Exception::what(), and writeParametersToFeature().
Referenced by accept(), and PartGui::TaskScale::clicked().
canScale()
bool DlgScale::canScale (const TopoDS_Shape & shape) const protected
return true if shape can be scaled.
Definition at line 144 of file DlgScale.cpp.
References Path.Post.scripts.grbl_post::type.
Referenced by findShapes().
changeEvent()
void DlgScale::changeEvent (QEvent * e) override protected
Definition at line 85 of file DlgScale.cpp.
References SCL.SimpleDataTypes::e.
findShapes()
void DlgScale::findShapes () protected
find all the scalable objects in the active document and load them into the list widget
Definition at line 113 of file DlgScale.cpp.
References canScale(), App::Application::getActiveDocument(), App::GetApplication(), Gui::Application::getDocument(), Gui::ViewProvider::getIcon(), App::Document::getName(), App::Document::getObjectsOfType(), Part::TopoShape::getShape(), Part::Feature::getTopoShape(), App::PropertyString::getValue(), Gui::Document::getViewProvider(), Gui::Application::Instance, Part::TopoShape::isNull(), App::Document::Label, and replaceobj::objs.
getShapesToScale()
std::vector< App::DocumentObject * > DlgScale::getShapesToScale () const
retrieve the document objects associated with the selected items in the list widget
Definition at line 272 of file DlgScale.cpp.
References toolbit-attributes::doc, App::GetApplication(), App::Application::getDocument(), src.Mod.Test.testPathArray::items, and importers.importIFCmulticore::objects.
Referenced by apply().
reject()
void DlgScale::reject () override
Definition at line 265 of file DlgScale.cpp.
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and PartGui::TaskScale::reject().
validate()
bool DlgScale::validate ()
return true if at least one item in the list widget corresponds to an available document object in the document
Definition at line 292 of file DlgScale.cpp.
References toolbit-attributes::doc, App::GetApplication(), App::Application::getDocument(), src.Mod.Test.testPathArray::items, and importers.importIFCmulticore::objects.
Referenced by apply().
writeParametersToFeature()
void DlgScale::writeParametersToFeature (App::DocumentObject & feature, App::DocumentObject * base) const
update a FeatureScale with the parameters from the UI
Definition at line 310 of file DlgScale.cpp.
References Gui::Command::Doc, doCommand, App::DocumentObject::getDocument(), App::Document::getName(), and App::DocumentObject::getNameInDocument().
Referenced by apply().
The documentation for this class was generated from the following files:
DlgScale.h
DlgScale.cpp