FreeCAD: src.Mod.Show.SceneDetails.Pickability Namespace Reference
src.Mod.Show.SceneDetails.Pickability Namespace Reference
Classes
class Pickability
Functions
def getPickStyleNode (viewprovider, make_if_missing=True)
def getPickStyle (viewprovider)
def setPickStyle (viewprovider, pickstyle)
Variables
int PS_REGULAR = 0
int PS_BOUNDBOX = 1
int PS_UNPICKABLE = 2
Function Documentation
getPickStyle()
def src.Mod.Show.SceneDetails.Pickability.getPickStyle (viewprovider)
Definition at line 74 of file Pickability.py.
References src.Mod.Show.SceneDetails.Pickability.getPickStyleNode().
Referenced by src.Mod.Show.SceneDetails.Pickability.Pickability.scene_value().
getPickStyleNode()
def src.Mod.Show.SceneDetails.Pickability.getPickStyleNode (viewprovider, make_if_missing = True)
Definition at line 57 of file Pickability.py.
References getLength().
Referenced by src.Mod.Show.SceneDetails.Pickability.getPickStyle(), and src.Mod.Show.SceneDetails.Pickability.setPickStyle().
setPickStyle()
def src.Mod.Show.SceneDetails.Pickability.setPickStyle (viewprovider, pickstyle)
Definition at line 82 of file Pickability.py.
References src.Mod.Show.SceneDetails.Pickability.getPickStyleNode().
Referenced by src.Mod.Show.SceneDetails.Pickability.Pickability.apply_data().
Variable Documentation
PS_BOUNDBOX
int src.Mod.Show.SceneDetails.Pickability.PS_BOUNDBOX = 1
Definition at line 53 of file Pickability.py.
PS_REGULAR
int src.Mod.Show.SceneDetails.Pickability.PS_REGULAR = 0
Definition at line 52 of file Pickability.py.
PS_UNPICKABLE
int src.Mod.Show.SceneDetails.Pickability.PS_UNPICKABLE = 2
Definition at line 54 of file Pickability.py.