FreeCAD: TechDraw::LineFormat Class Reference
TechDraw::LineFormat Class Reference
general purpose line format specifier
#include <LineFormat.h>
Public Member Functions
LineFormat ()
general purpose line format specifier
LineFormat (const int style, const double weight, const App::Color &color, const bool visible, const int lineNumber)
LineFormat (const int style, const double weight, const App::Color &color, const bool visible)
~LineFormat ()=default
int getStyle () const
void setStyle (int style)
double getWidth () const
void setWidth (double width)
App::Color getColor () const
void setColor (App::Color color)
QColor getQColor () const
void setQColor (QColor qColor)
bool getVisible () const
void setVisible (bool viz)
int getLineNumber () const
void setLineNumber (int number)
void dump (const char *title)
std::string toString () const
Static Public Member Functions
static double getDefEdgeWidth ()
static App::Color getDefEdgeColor ()
static int getDefEdgeStyle ()
static void initCurrentLineFormat ()
static LineFormat & getCurrentLineFormat ()
static void setCurrentLineFormat (LineFormat &newformat)
Static Public Attributes
static constexpr size_t InvalidLine {0}
Detailed Description
general purpose line format specifier
Definition at line 58 of file LineFormat.h.
Constructor & Destructor Documentation
LineFormat() [1/3]
LineFormat::LineFormat ()
general purpose line format specifier
Definition at line 39 of file LineFormat.cpp.
References TechDraw::LineGenerator::fromQtStyle(), getDefEdgeColor(), getDefEdgeStyle(), and getDefEdgeWidth().
LineFormat() [2/3]
TechDraw::LineFormat::LineFormat (const int style, const double weight, const App::Color & color, const bool visible, const int lineNumber)
LineFormat() [3/3]
LineFormat::LineFormat (const int style, const double weight, const App::Color & color, const bool visible)
Definition at line 73 of file LineFormat.cpp.
~LineFormat()
TechDraw::LineFormat::~LineFormat () default
Member Function Documentation
dump()
void LineFormat::dump (const char * title)
Definition at line 85 of file LineFormat.cpp.
References Base::Console(), Base::ConsoleSingleton::Message(), Plot::title(), and toString().
getColor()
App::Color TechDraw::LineFormat::getColor () const inline
Definition at line 103 of file LineFormat.h.
Referenced by TechDraw::GeomFormat::copy(), TechDrawGui::QGIViewPart::drawAllEdges(), TechDrawGui::QGIViewPart::formatGeomFromCenterLine(), TechDrawGui::QGIViewPart::formatGeomFromCosmetic(), TechDraw::GeomFormat::GeomFormat(), TechDrawGui::TaskLineDecor::getDefaults(), TechDraw::CosmeticEdge::Save(), TechDraw::CenterLine::Save(), TechDraw::GeomFormat::Save(), setCurrentLineFormat(), and TechDrawGui::TaskCenterLine::setUiEdit().
getCurrentLineFormat()
LineFormat & LineFormat::getCurrentLineFormat () static
Definition at line 58 of file LineFormat.cpp.
Referenced by initCurrentLineFormat(), and setCurrentLineFormat().
getDefEdgeColor()
App::Color LineFormat::getDefEdgeColor () static
Definition at line 107 of file LineFormat.cpp.
References TechDraw::Preferences::normalColor().
Referenced by TechDraw::GeomFormat::GeomFormat(), initCurrentLineFormat(), and LineFormat().
getDefEdgeStyle()
int LineFormat::getDefEdgeStyle () static
Definition at line 112 of file LineFormat.cpp.
References ParameterGrp::GetInt(), and TechDraw::Preferences::getPreferenceGroup().
Referenced by TechDraw::GeomFormat::GeomFormat(), initCurrentLineFormat(), and LineFormat().
getDefEdgeWidth()
double LineFormat::getDefEdgeWidth () static
Definition at line 102 of file LineFormat.cpp.
References TechDraw::LineGroup::getDefaultWidth().
Referenced by TechDraw::GeomFormat::GeomFormat(), initCurrentLineFormat(), and LineFormat().
getLineNumber()
int TechDraw::LineFormat::getLineNumber () const inline
Definition at line 111 of file LineFormat.h.
Referenced by TechDraw::GeomFormat::copy(), TechDrawGui::QGIViewPart::drawAllEdges(), TechDrawGui::QGIViewPart::formatGeomFromCenterLine(), TechDrawGui::QGIViewPart::formatGeomFromCosmetic(), TechDraw::GeomFormat::GeomFormat(), TechDrawGui::TaskLineDecor::getDefaults(), TechDraw::CosmeticEdge::Save(), TechDraw::CenterLine::Save(), TechDraw::GeomFormat::Save(), and setCurrentLineFormat().
getQColor()
QColor TechDraw::LineFormat::getQColor () const inline
Definition at line 105 of file LineFormat.h.
getStyle()
int TechDraw::LineFormat::getStyle () const inline
Definition at line 97 of file LineFormat.h.
Referenced by TechDraw::GeomFormat::copy(), TechDrawGui::QGIViewPart::drawAllEdges(), TechDrawGui::QGIViewPart::formatGeomFromCenterLine(), TechDrawGui::QGIViewPart::formatGeomFromCosmetic(), TechDraw::GeomFormat::GeomFormat(), TechDrawGui::TaskLineDecor::getDefaults(), initCurrentLineFormat(), TechDraw::CosmeticEdge::Save(), TechDraw::CenterLine::Save(), TechDraw::GeomFormat::Save(), setCurrentLineFormat(), and TechDrawGui::TaskCenterLine::setUiEdit().
getVisible()
bool TechDraw::LineFormat::getVisible () const inline
Definition at line 108 of file LineFormat.h.
Referenced by TechDraw::GeomFormat::copy(), TechDrawGui::QGIViewPart::drawAllEdges(), TechDrawGui::QGIViewPart::formatGeomFromCenterLine(), TechDrawGui::QGIViewPart::formatGeomFromCosmetic(), TechDraw::GeomFormat::GeomFormat(), TechDrawGui::TaskLineDecor::getDefaults(), TechDraw::CosmeticEdge::Save(), TechDraw::CenterLine::Save(), TechDraw::GeomFormat::Save(), and setCurrentLineFormat().
getWidth()
double TechDraw::LineFormat::getWidth () const inline
Definition at line 100 of file LineFormat.h.
Referenced by TechDraw::GeomFormat::copy(), TechDrawGui::QGIViewPart::drawAllEdges(), TechDrawGui::QGIViewPart::formatGeomFromCenterLine(), TechDrawGui::QGIViewPart::formatGeomFromCosmetic(), TechDraw::GeomFormat::GeomFormat(), TechDrawGui::TaskLineDecor::getDefaults(), TechDraw::CosmeticEdge::Save(), TechDraw::CenterLine::Save(), TechDraw::GeomFormat::Save(), setCurrentLineFormat(), and TechDrawGui::TaskCenterLine::setUiEdit().
initCurrentLineFormat()
void LineFormat::initCurrentLineFormat () static
Definition at line 49 of file LineFormat.cpp.
References TechDraw::LineGenerator::fromQtStyle(), getCurrentLineFormat(), getDefEdgeColor(), getDefEdgeStyle(), getDefEdgeWidth(), getStyle(), setColor(), setLineNumber(), setStyle(), setVisible(), and setWidth().
Referenced by PyMOD_INIT_FUNC().
setColor()
void TechDraw::LineFormat::setColor (App::Color color) inline
Definition at line 104 of file LineFormat.h.
Referenced by TechDrawGui::_setLineAttributes(), TechDrawGui::TaskLineDecor::applyDecorations(), TechDraw::GeomFormat::copy(), TechDrawGui::TaskCenterLine::createCenterLine(), TechDraw::GeomFormat::GeomFormat(), initCurrentLineFormat(), TechDrawGui::TaskCenterLine::reject(), TechDraw::CosmeticEdge::Restore(), TechDraw::CenterLine::Restore(), TechDraw::GeomFormat::Restore(), and setCurrentLineFormat().
setCurrentLineFormat()
void LineFormat::setCurrentLineFormat (LineFormat & newformat) static
Definition at line 64 of file LineFormat.cpp.
References getColor(), getCurrentLineFormat(), getLineNumber(), getStyle(), getVisible(), getWidth(), setColor(), setLineNumber(), setStyle(), setVisible(), and setWidth().
setLineNumber()
void TechDraw::LineFormat::setLineNumber (int number) inline
Definition at line 112 of file LineFormat.h.
Referenced by TechDrawGui::_setLineAttributes(), TechDrawGui::TaskLineDecor::applyDecorations(), TechDraw::GeomFormat::copy(), TechDrawGui::TaskCenterLine::createCenterLine(), TechDraw::GeomFormat::GeomFormat(), initCurrentLineFormat(), TechDrawGui::TaskCenterLine::reject(), TechDraw::CosmeticEdge::Restore(), TechDraw::CenterLine::Restore(), TechDraw::GeomFormat::Restore(), and setCurrentLineFormat().
setQColor()
void TechDraw::LineFormat::setQColor (QColor qColor) inline
Definition at line 106 of file LineFormat.h.
setStyle()
void TechDraw::LineFormat::setStyle (int style) inline
Definition at line 98 of file LineFormat.h.
Referenced by TechDrawGui::_setLineAttributes(), TechDrawGui::TaskLineDecor::applyDecorations(), TechDraw::GeomFormat::copy(), TechDraw::GeomFormat::GeomFormat(), initCurrentLineFormat(), TechDraw::CosmeticEdge::Restore(), TechDraw::CenterLine::Restore(), TechDraw::GeomFormat::Restore(), and setCurrentLineFormat().
setVisible()
void TechDraw::LineFormat::setVisible (bool viz) inline
Definition at line 109 of file LineFormat.h.
Referenced by TechDrawGui::_setLineAttributes(), TechDrawGui::TaskLineDecor::applyDecorations(), TechDraw::GeomFormat::copy(), TechDrawGui::TaskCenterLine::createCenterLine(), TechDraw::GeomFormat::GeomFormat(), initCurrentLineFormat(), TechDrawGui::TaskCenterLine::reject(), TechDraw::CosmeticEdge::Restore(), TechDraw::CenterLine::Restore(), TechDraw::GeomFormat::Restore(), and setCurrentLineFormat().
setWidth()
void TechDraw::LineFormat::setWidth (double width) inline
Definition at line 101 of file LineFormat.h.
Referenced by TechDrawGui::_setLineAttributes(), TechDrawGui::TaskLineDecor::applyDecorations(), TechDraw::GeomFormat::copy(), TechDrawGui::TaskCenterLine::createCenterLine(), TechDraw::GeomFormat::GeomFormat(), initCurrentLineFormat(), TechDrawGui::TaskCenterLine::reject(), TechDraw::CosmeticEdge::Restore(), TechDraw::CenterLine::Restore(), TechDraw::GeomFormat::Restore(), and setCurrentLineFormat().
toString()
std::string LineFormat::toString () const
Definition at line 91 of file LineFormat.cpp.
References App::Color::asHexString().
Referenced by dump(), TechDraw::CosmeticEdge::toString(), TechDraw::CenterLine::toString(), and TechDraw::GeomFormat::toString().
Member Data Documentation
InvalidLine
constexpr size_t TechDraw::LineFormat::InvalidLine {0} static constexpr
Definition at line 81 of file LineFormat.h.
Referenced by TechDraw::GeomFormat::GeomFormat(), TechDraw::CosmeticEdge::Restore(), TechDraw::CenterLine::Restore(), and TechDraw::GeomFormat::Restore().
The documentation for this class was generated from the following files:
LineFormat.h
LineFormat.cpp