FreeCAD: Gui::TreeView Class Reference
Gui::TreeView Class Reference
#include <TreeView.h>
Public Member Functions
TreeView (QWidget *parent=nullptr)
~TreeView () override
Protected Member Functions
void mouseDoubleClickEvent (QMouseEvent *) override
void rowsInserted (const QModelIndex &parent, int start, int end) override
Detailed Description
Definition at line 52 of file TreeView.h.
Constructor & Destructor Documentation
TreeView()
TreeView::TreeView (QWidget * parent = nullptr)
Definition at line 39 of file TreeView.cpp.
~TreeView()
TreeView::~TreeView () override default
Member Function Documentation
mouseDoubleClickEvent()
void TreeView::mouseDoubleClickEvent (QMouseEvent * event) override protected
Definition at line 55 of file TreeView.cpp.
References toolbit-attributes::doc, Gui::getMainWindow(), Gui::Application::Instance, Base::BaseClass::is(), Base::BaseClass::isDerivedFrom(), and Gui::MainWindow::setActiveWindow().
rowsInserted()
void TreeView::rowsInserted (const QModelIndex & parent, int start, int end) override protected
Definition at line 76 of file TreeView.cpp.
References Base::Type::fromName(), SplineSurface::i, and Init::parent.
The documentation for this class was generated from the following files:
TreeView.h
TreeView.cpp