FreeCAD: Base::ConsoleSingleton Class Reference
Base::ConsoleSingleton Class Reference
#include <Console.h>
Public Types
enum ConsoleMode { Verbose = 1 }
enumeration for the console modes
enum ConnectionMode { Direct = 0, Queued = 1 }
enum FreeCAD_ConsoleMsgType {
MsgType_Txt = 1, MsgType_Log = 2, MsgType_Wrn = 4, MsgType_Err = 8,
MsgType_Critical = 16, MsgType_Notification = 32
}
Public Member Functions
template<Base::LogStyle , Base::IntendedRecipient = Base::IntendedRecipient::All, Base::ContentType = Base::ContentType::Untranslated, typename... Args>
void Send (const std::string &notifiername, const char *pMsg, Args &&... args)
template<typename... Args>
void Message (const char *pMsg, Args &&... args)
Prints a Message.
template<typename... Args>
void Warning (const char *pMsg, Args &&... args)
Prints a warning Message.
template<typename... Args>
void Error (const char *pMsg, Args &&... args)
Prints a error Message.
template<typename... Args>
void Log (const char *pMsg, Args &&... args)
Prints a log Message.
template<typename... Args>
void Critical (const char *pMsg, Args &&... args)
Prints a Critical Message.
template<typename... Args>
void UserNotification (const char *pMsg, Args &&... args)
Sends a User Notification.
template<typename... Args>
void UserTranslatedNotification (const char *pMsg, Args &&... args)
Sends an already translated User Notification.
template<typename... Args>
void Message (const std::string &notifier, const char *pMsg, Args &&... args)
Prints a Message with source indication.
template<typename... Args>
void Warning (const std::string &notifier, const char *pMsg, Args &&... args)
Prints a warning Message with source indication.
template<typename... Args>
void DeveloperWarning (const std::string &notifier, const char *pMsg, Args &&... args)
template<typename... Args>
void UserWarning (const std::string &notifier, const char *pMsg, Args &&... args)
template<typename... Args>
void TranslatedUserWarning (const std::string &notifier, const char *pMsg, Args &&... args)
template<typename... Args>
void Error (const std::string &notifier, const char *pMsg, Args &&... args)
Prints a error Message with source indication.
template<typename... Args>
void DeveloperError (const std::string &notifier, const char *pMsg, Args &&... args)
template<typename... Args>
void UserError (const std::string &notifier, const char *pMsg, Args &&... args)
template<typename... Args>
void TranslatedUserError (const std::string &notifier, const char *pMsg, Args &&... args)
template<typename... Args>
void Log (const std::string &notifier, const char *pMsg, Args &&... args)
Prints a log Message with source indication.
template<typename... Args>
void Critical (const std::string &notifier, const char *pMsg, Args &&... args)
Prints a Critical Message with source indication.
template<typename... Args>
void UserNotification (const std::string &notifier, const char *pMsg, Args &&... args)
Sends a User Notification with source indication.
template<typename... Args>
void UserTranslatedNotification (const std::string &notifier, const char *pMsg, Args &&... args)
Sends an already translated User Notification with source indication.
template<Base::LogStyle , Base::IntendedRecipient = Base::IntendedRecipient::All, Base::ContentType = Base::ContentType::Untranslated>
void Notify (const std::string &notifiername, const std::string &msg)
void AttachObserver (ILogger *pcObserver)
Attaches an Observer to FCConsole.
void DetachObserver (ILogger *pcObserver)
Detaches an Observer from FCConsole.
void SetConsoleMode (ConsoleMode mode)
Change mode.
void UnsetConsoleMode (ConsoleMode mode)
Change mode.
ConsoleMsgFlags SetEnabledMsgType (const char *sObs, ConsoleMsgFlags type, bool on)
Enables or disables message types of a certain console observer.
bool IsMsgTypeEnabled (const char *sObs, FreeCAD_ConsoleMsgType type) const
Checks if message types of a certain console observer are enabled.
void SetConnectionMode (ConnectionMode mode)
int * GetLogLevel (const char *tag, bool create=true)
void SetDefaultLogLevel (int level)
int LogLevel (int level) const
ILogger * Get (const char *Name) const
void Refresh ()
void EnableRefresh (bool enable)
constexpr FreeCAD_ConsoleMsgType getConsoleMsg (Base::LogStyle style)
ConsoleSingleton (const ConsoleSingleton &)=delete
ConsoleSingleton (ConsoleSingleton &&)=delete
ConsoleSingleton & operator= (const ConsoleSingleton &)=delete
ConsoleSingleton & operator= (ConsoleSingleton &&)=delete
Static Public Member Functions
static ConsoleSingleton & Instance ()
singleton
Static Public Attributes
static PyMethodDef Methods []
Friends
class ConsoleOutput
Detailed Description
The console class This class manage all the stdio stuff. This includes Messages, Warnings, Log entries, Errors, Criticals, Notifications. The incoming Messages are distributed with the FCConsoleObserver. The FCConsole class itself makes no IO, it's more like a manager.
ConsoleSingleton is a singleton! That means you can access the only instance of the class from every where in c++ by simply using:
#include <Base/Console.h>
Base::Console().Log("Stage: %d",i);
ConsoleSingleton is able to switch between several modes to, e.g. switch the logging on or off, or treat Warnings as Errors, and so on...
See also
ConsoleObserver
When sending error, warnings and notifications, preferably a notifier string should be provided, this enables the observer to identify the source. Any string is possible. It is common to use the DocumentObject::getFullLabel() or the label of the Document, when available. When using the Notification Framework of the Gui (Gui/Notifications.h) and a DocumentObject is passed as notifier, getFullLabel() is used. See example below.
It is important for the different observers to know whether an error/warning message is intended for a user, for a developer, or for both. This enables observers to provide distinctive behaviour. Similarly, different observers may treat differently messages if they carry translated, untranslated, or untranslatable messages.
While it is possible to create a tailored message, ConsoleSingleton provides convenience functions for most common messages. A custom message can be created as follows:
Send<Base::LogStyle::Error,
     Base::IntendedRecipient::Developer,
     Base::ContentType::Untranslatable>("OCCT", e.what());
That code is equivalent to:
DeveloperError("OCCT", e.what());
These convenience functions cover most common cases:
Unqualified convenience functions, such as Error() and Warning(), produce messages intended to both User and Developer with an untranslated message.
Functions qualified with Developer, such as DeveloperError are intended for a Developer and are untranslatable. Functions qualified with User, such as UserError are intended only for the User and a untranslated (leaving the responsibility to the observer to find the translation).
Functions qualified with Translated, such as TranslatedError, are intended for the User and the message is already translated.
An observer receiving an Untranslatable or Translated message should not attempt to translate it.
However, an observer receiving a Translatable message may or may not attempt to translate it, e.g. depending on whether it intends to show the message to a Log or on the UI.
Observers shall use the QT translation context "Notifications" to attempt to translate an Untranslated message, if they need the localized version. Users shall mark Untranslated messages for translation.
Untranslated messages have the inherent advantage that can be processed in English by observers needing the English version, while enabling other observers to retrieve a translated version.
However, untranslated messages have the limitation that need to be known to the QT framework, so in practice, they need be static strings (as opposed to dynamically generated ones).
Example:
Base::Console().UserError(this->getFullName(), QT_TRANSLATE_NOOP("Notifications",
                          "Impossible to migrate Parabolas!!\n"));
Currently dynamically generated strings can only be properly translated at the source. This is often the case in legacy UI code, where localized strings are already available. For these cases the solution is to indicate the translated status. For example:
Base::Console().TranslatedUserError(
                            this->getFullName(),
                            QObject::tr("The selected edge already has a Block constraint!"));
However, many of this legacy UI messages were previously a QMessageBox, and it is more convenient to use the Translations Framework provided by Gui/Notifications.h, as it takes the same arguments as QMessageBox. Additionally, the Notifications Framework takes into account the user preferences to receive intrusive (pop-ups) or non-intrusive (notification area) notifications.
Definition at line 703 of file Console.h.
Member Enumeration Documentation
ConnectionMode
enum Base::ConsoleSingleton::ConnectionMode
Enumerator
Direct
Queued
Definition at line 795 of file Console.h.
ConsoleMode
enum Base::ConsoleSingleton::ConsoleMode
enumeration for the console modes
Enumerator
Verbose
Definition at line 791 of file Console.h.
FreeCAD_ConsoleMsgType
enum Base::ConsoleSingleton::FreeCAD_ConsoleMsgType
Enumerator
MsgType_Txt
MsgType_Log
MsgType_Wrn
MsgType_Err
MsgType_Critical
MsgType_Notification
Definition at line 801 of file Console.h.
Constructor & Destructor Documentation
ConsoleSingleton() [1/2]
Base::ConsoleSingleton::ConsoleSingleton (const ConsoleSingleton &) delete
ConsoleSingleton() [2/2]
Base::ConsoleSingleton::ConsoleSingleton (ConsoleSingleton &&) delete
Member Function Documentation
AttachObserver()
void ConsoleSingleton::AttachObserver (ILogger * pcObserver)
Attaches an Observer to FCConsole.
Attaches an Observer to Console Use this method to attach a ILogger derived class to the Console. After the observer is attached all messages will also be forwarded to it.
See also
ILogger
Definition at line 303 of file Console.cpp.
Referenced by CmdTestConsoleOutput::activated(), NotificationAreaObserver::NotificationAreaObserver(), Gui::DockWnd::ReportOutput::ReportOutput(), Gui::SplashObserver::SplashObserver(), and Gui::StatusBarObserver::StatusBarObserver().
Critical() [1/2]
template<typename... Args> void Base::ConsoleSingleton::Critical (const char * pMsg, Args &&... args) inline
Prints a Critical Message.
Definition at line 1108 of file Console.h.
References toolbit-attributes::args, and Base::Critical.
Referenced by Sketcher::SketchObject::migrateSketch(), and Gui::ConsoleCriticalTask::run().
Critical() [2/2]
template<typename... Args> void Base::ConsoleSingleton::Critical (const std::string & notifier, const char * pMsg, Args &&... args) inline
Prints a Critical Message with source indication.
Definition at line 1115 of file Console.h.
References toolbit-attributes::args.
DetachObserver()
void ConsoleSingleton::DetachObserver (ILogger * pcObserver)
Detaches an Observer from FCConsole.
Detaches an Observer from Console Use this method to detach a ILogger derived class. After detaching you can destruct the Observer or reinsert it later.
See also
ILogger
Definition at line 316 of file Console.cpp.
Referenced by CmdTestConsoleOutput::activated(), App::Application::destructObserver(), NotificationAreaObserver::~NotificationAreaObserver(), Gui::DockWnd::ReportOutput::~ReportOutput(), Gui::SplashObserver::~SplashObserver(), and Gui::StatusBarObserver::~StatusBarObserver().
DeveloperError()
template<typename... Args> void Base::ConsoleSingleton::DeveloperError (const std::string & notifier, const char * pMsg, Args &&... args) inline
Definition at line 1077 of file Console.h.
References toolbit-attributes::args, Base::Developer, Base::Error, and Base::Untranslatable.
Referenced by Gui::cmdAppObjectShow(), SketcherGui::CurveConverter::CurveConverter(), SketcherGui::ViewProviderSketch::onDelete(), SketcherGui::EditModeConstraintCoinManager::processConstraints(), Base::PyException::ReportException(), SketcherGui::ViewProviderSketch::setEdit(), SketcherGui::ViewProviderSketch::setEditViewer(), and SketcherGui::ViewProviderSketch::unsetEdit().
DeveloperWarning()
template<typename... Args> void Base::ConsoleSingleton::DeveloperWarning (const std::string & notifier, const char * pMsg, Args &&... args) inline
Definition at line 1033 of file Console.h.
References toolbit-attributes::args, Base::Developer, Base::Untranslatable, and Base::Warning.
Referenced by Base::Subject< const char * >::Attach(), SketcherGui::ViewProviderSketch::camSensCB(), SketcherGui::ViewProviderSketch::deleteSelected(), SketcherGui::EditModeConstraintCoinManager::drawConstraintIcons(), Base::Observer< const char * >::Name(), App::PropertyEnumeration::Restore(), SketcherGui::ViewProviderSketch::setEdit(), Gui::EditableDatumLabel::setFocusToSpinbox(), and Gui::EditableDatumLabel::setSpinboxValue().
EnableRefresh()
void ConsoleSingleton::EnableRefresh (bool enable)
Definition at line 383 of file Console.cpp.
Referenced by Base::ConsoleRefreshDisabler::ConsoleRefreshDisabler(), and Base::ConsoleRefreshDisabler::~ConsoleRefreshDisabler().
Error() [1/2]
template<typename... Args> void Base::ConsoleSingleton::Error (const char * pMsg, Args &&... args) inline
Prints a error Message.
Definition at line 1064 of file Console.h.
References toolbit-attributes::args.
Referenced by ReverseEngineeringGui::Segmentation::accept(), TechDrawGui::TaskCosmeticCircle::accept(), Gui::Dialog::DlgRevertToBackupConfigImp::accept(), TechDrawGui::TaskWeldingSymbol::accept(), Gui::StdCmdDownloadOnlineHelp::activated(), Gui::PythonCommand::activated(), CmdTestConsoleOutput::activated(), Gui::PythonGroupCommand::activated(), Gui::Application::activateWorkbench(), Sketcher::Sketch::addAngleAtPointConstraint(), TechDraw::CosmeticExtension::addCenterLinesToGeom(), Sketcher::Sketch::addConstraints(), Sketcher::SketchObject::addCopy(), Sketcher::SketchObject::addExternal(), Materials::Material::addPhysical(), TechDraw::DrawProjGroup::addProjection(), Sketcher::Sketch::addSnellsLawConstraint(), Sketcher::Sketch::addTangentConstraint(), Sketcher::Sketch::addTangentLineAtBSplineKnotConstraint(), Sketcher::Sketch::addTangentLineEndpointAtBSplineKnotConstraint(), Gui::CommandManager::addTo(), TechDraw::AOE::AOE(), TechDrawGui::TaskSectionView::apply(), TechDrawGui::TaskComplexSection::apply(), TechDraw::DrawViewDimension::arcPointsFromBaseGeom(), Measure::Measurement::area(), TechDraw::DrawProjGroup::arrangeViewPointers(), TechDrawGui::QGIFace::buildPixHatch(), TechDraw::CenterLine::calcEndPoints(), TechDraw::DrawProjGroup::canDelete(), Sketcher::SketchObject::carbonCopy(), SurfaceGui::GeomFillSurface::changeFillType(), ParameterManager::CheckDocument(), App::DocumentP::checkStringHasher(), Cloud::Module::cloudRestore(), Gui::MacroManager::commit(), TechDraw::BaseGeom::completeEdge(), SpreadsheetGui::SheetView::confirmAliasChanged(), TechDrawGui::QGIViewDimension::constructDimensionArc(), TechDrawGui::QGIViewDimension::constructDimensionLine(), Sketcher::SketchObject::convertToNURBS(), Gui::PythonCommand::createAction(), Gui::PythonGroupCommand::createAction(), TechDrawGui::TaskActiveView::createActiveView(), TechDrawGui::QGISVGTemplate::createClickHandles(), Materials::MaterialLibrary::createFolder(), TechDrawGui::TaskHatch::createHatch(), Fem::createObjectByType(), Gui::WidgetFactoryInst::createPreferencePage(), Gui::WidgetFactoryInst::createPrefWidget(), Part::ExtrusionHelper::createTaperedPrismOffset(), Gui::WidgetFactoryInst::createWidget(), MatGui::Array3DModel::data(), Sketcher::SketchObject::decreaseBSplineDegree(), Sketcher::SketchObject::delAllExternal(), Measure::Measurement::delta(), Base::Subject< const char * >::Detach(), PartGui::ViewProviderPart::doubleClicked(), TechDrawGui::QGIViewDimension::draw(), TechDrawGui::QGIViewDimension::drawAngle(), TechDrawGui::QGIViewDimension::drawAreaExecutive(), TechDrawGui::QGIViewDimension::drawDiameter(), TechDrawGui::QGIViewDimension::drawDistanceExecutive(), TechDrawGui::QGIViewDimension::drawDistanceOverride(), TechDrawGui::QGIViewDimension::drawRadiusExecutive(), TechDrawGui::TaskDetail::editByHighlight(), Gui::ViewProvider::eventCallback(), TechDraw::DrawViewArch::execute(), Spreadsheet::Sheet::execute(), SpreadsheetGui::ViewProviderSheet::exportAsFile(), Fem::FemVTKTools::exportFreeCADResult(), Part::AttachExtension::extensionOnChanged(), StartGui::StartView::fileCardSelected(), PartDesignGui::TaskTransformedParameters::fillAxisCombo(), PartDesignGui::TaskTransformedParameters::fillPlanesCombo(), Assembly::AssemblyObject::generateSimulation(), TechDrawGui::PathBuilder::geomToPainterPath(), TechDraw::DrawGeomHatch::getDecodedSpecsFromFile(), TechDraw::DrawViewPart::getDirsFromFront(), Materials::MaterialLoader::getMaterialFromYAML(), Gui::PreferencePackManager::getPacksFromDirectory(), TechDraw::DrawProjGroup::getProjItem(), TechDraw::DrawProjGroup::getProjObj(), TechDraw::LineGroup::getRecordFromFile(), TechDraw::DrawViewSection::getSectionCS(), TechDraw::ShapeExtractor::getShapeFromXLink(), TechDraw::ShapeExtractor::getShapesFused(), TechDraw::DrawViewSpreadsheet::getSheetImage(), Sketcher::SketchObject::getSymmetric(), TechDraw::DrawSVGTemplate::getTemplateDocument(), TechDraw::DrawUtil::getWidthInDirection(), TechDraw::DrawProjGroup::hasProjection(), Fem::FemVTKTools::importVTKMesh(), Sketcher::SketchObject::increaseBSplineDegree(), Gui::Application::initApplication(), Sketcher::SketchObject::insertBSplineKnot(), TechDraw::DrawProjectSplit::isOnEdge(), Measure::Measurement::length(), TechDraw::LineGroup::lineGroupFactory(), Measure::Measurement::lineLineDistance(), MeshCore::MeshInput::LoadNastran(), TechDrawGui::QGIFace::loadSvgHatch(), PartDesignGui::TaskSketchBasedParameters::make2DLabel(), TechDrawGui::QGITile::makeSymbol(), Measure::Measurement::massCenter(), messageHandler(), Sketcher::SketchObject::modifyBSplineKnotMultiplicity(), Gui::GUIApplication::notify(), PartGui::SectionCut::onBFragTransparencyHSMoved(), Sketcher::SketchObject::onChanged(), PartGui::SectionCut::onCutXvalueChanged(), PartGui::SectionCut::onCutYvalueChanged(), PartGui::SectionCut::onCutZvalueChanged(), PartDesignGui::TaskExtrudeParameters::onDirectionCBChanged(), TechDraw::DrawViewPart::onHlrFinished(), Gui::Application::onLastWindowClosed(), PartGui::SectionCut::onRefreshCutPBclicked(), Gui::GestureNavigationStyle::onRollGesture(), TechDrawGui::TaskLeaderLine::onTrackerClicked(), TechDrawGui::TaskCosVertex::onTrackerFinished(), TechDrawGui::TaskLeaderLine::onTrackerFinished(), App::Application::openDocuments(), Gui::VectorTableModel::pasteFromClipboard(), TechDrawGui::QGSPage::postProcessXml(), Gui::Dialog::PreferenceUiForm::PreferenceUiForm(), MeshPartGui::Tessellation::process(), App::Application::processCmdLineFiles(), App::Application::processFiles(), TechDraw::GeometryObject::projectShape(), TechDraw::GeometryObject::projectShapeWithPolygonAlgo(), TechDraw::DrawProjGroup::purgeProjections(), PyMOD_INIT_FUNC(), Measure::Measurement::radius(), Base::XMLReader::readFiles(), App::Document::readObjects(), App::Document::recompute(), MeasureGui::ViewProviderMeasureAngle::redrawAnnotation(), TechDraw::DrawProjGroup::removeProjection(), Materials::MaterialLibrary::renameFolder(), Gui::View3DInventorViewer::resetEditingRoot(), TechDraw::PropertyCenterLineList::Restore(), TechDraw::PropertyGeomFormatList::Restore(), TechDraw::PropertyCosmeticEdgeList::Restore(), TechDraw::PropertyCosmeticVertexList::Restore(), Part::PropertyGeometryList::Restore(), App::Document::restore(), App::PropertyContainer::Restore(), Fem::PropertyPostDataObject::RestoreDocFile(), Gui::Document::RestoreDocFile(), App::ExtensionContainer::restoreExtensions(), Sandbox::PythonThread::run(), Gui::ConsoleErrorTask::run(), TechDraw::CenterLine::Save(), App::PropertyContainer::Save(), Fem::PropertyPostDataObject::SaveDocFile(), App::ExtensionContainer::saveExtensions(), Materials::MaterialLibrary::saveMaterial(), TechDraw::CenterLine::scaledAndRotatedGeometry(), TechDraw::CenterLine::scaledGeometry(), TechDraw::DrawProjectSplit::scrubEdges(), Sketcher::SketchObject::setConstraintExpression(), MatGui::Array3DModel::setData(), TechDrawGui::ViewProviderViewPart::setEdit(), Gui::PropertyEditor::PropertyItem::setPropertyValue(), Gui::ViewProviderCoordinateSystem::setTemporaryVisibility(), Gui::ApplicationPy::sExport(), Gui::ApplicationPy::sInsert(), Sketcher::SketchObject::solve(), Gui::ApplicationPy::sOpen(), Gui::NetworkRetriever::startDownload(), TechDrawGui::QGIViewSymbol::symbolToSvg(), Base::RedirectStdError::sync(), MeshPart::MeshingOutput::sync(), PartDesignGui::TaskBoxPrimitives::TaskBoxPrimitives(), TechDrawGui::TaskCenterLine::TaskCenterLine(), TechDrawGui::TaskCosmeticCircle::TaskCosmeticCircle(), TechDrawGui::TaskCosmeticLine::TaskCosmeticLine(), TechDrawGui::TaskDetail::TaskDetail(), TechDrawGui::TaskLeaderLine::TaskLeaderLine(), TechDrawGui::TaskRichAnno::TaskRichAnno(), TechDrawGui::TaskWeldingSymbol::TaskWeldingSymbol(), TechDrawGui::QGIFace::textureFromBitmap(), Gui::AutoSaver::timerEvent(), App::PropertyPythonObject::toString(), PartDesign::SubShapeBinder::update(), PartDesignGui::ViewProviderAddSub::updateAddSubShapeIndicator(), TechDraw::DrawProjGroup::updateChildrenEnforce(), TechDraw::DrawProjGroup::updateChildrenLock(), TechDraw::DrawProjGroup::updateChildrenSource(), Gui::ViewProviderVRMLObject::updateData(), PartGui::ViewProviderCurveNet::updateData(), FemGui::ViewProviderFemConstraintBearing::updateData(), TechDrawGui::TaskDetail::updateDetail(), Measure::Measurement::volume(), Gui::OutputStderr::write(), Gui::PythonDebugStderr::write(), App::FeatureTestAttribute::~FeatureTestAttribute(), PartDesignGui::TaskBoxPrimitives::~TaskBoxPrimitives(), PartDesignGui::TaskLinearPatternParameters::~TaskLinearPatternParameters(), PartDesignGui::TaskMirroredParameters::~TaskMirroredParameters(), and PartDesignGui::TaskPolarPatternParameters::~TaskPolarPatternParameters().
Error() [2/2]
template<typename... Args> void Base::ConsoleSingleton::Error (const std::string & notifier, const char * pMsg, Args &&... args) inline
Prints a error Message with source indication.
Definition at line 1071 of file Console.h.
References toolbit-attributes::args.
Get()
ILogger * ConsoleSingleton::Get (const char * Name) const
Definition at line 348 of file Console.cpp.
References Base::ILogger::Name().
Referenced by src.Mod.AddonManager.AddonManagerTest.app.mocks.MockPref::GetBool(), src.Mod.AddonManager.AddonManagerTest.app.mocks.MockPref::GetInt(), src.Mod.AddonManager.AddonManagerTest.app.mocks.MockPref::GetString(), IsMsgTypeEnabled(), Base::Builder3D::saveToLog(), and SetEnabledMsgType().
getConsoleMsg()
constexpr ConsoleSingleton::FreeCAD_ConsoleMsgType Base::ConsoleSingleton::getConsoleMsg (Base::LogStyle style) inline constexpr
Definition at line 915 of file Console.h.
References draftfunctions.array::array().
GetLogLevel()
int * ConsoleSingleton::GetLogLevel (const char * tag, bool create = true)
Definition at line 360 of file Console.cpp.
References importers.importIFClegacy::create(), and Dice3DS.dom3ds::tag.
Instance()
ConsoleSingleton & ConsoleSingleton::Instance () static
singleton
Definition at line 401 of file Console.cpp.
Referenced by Base::Console(), Gui::Translator::enableDecimalPointConversion(), CDxfRead::ImportError(), and CDxfRead::ImportObservation().
IsMsgTypeEnabled()
bool ConsoleSingleton::IsMsgTypeEnabled (const char * sObs, FreeCAD_ConsoleMsgType type) const
Checks if message types of a certain console observer are enabled.
Definition at line 259 of file Console.cpp.
References Base::ILogger::bCritical, Base::ILogger::bErr, Base::ILogger::bLog, Base::ILogger::bMsg, Base::ILogger::bNotification, Base::ILogger::bWrn, Get(), MsgType_Critical, MsgType_Err, MsgType_Log, MsgType_Notification, MsgType_Txt, MsgType_Wrn, and Path.Post.scripts.grbl_post::type.
Log() [1/2]
template<typename... Args> void Base::ConsoleSingleton::Log (const char * pMsg, Args &&... args) inline
Prints a log Message.
Definition at line 1153 of file Console.h.
References toolbit-attributes::args.
Referenced by Gui::Command::_doCommand(), Base::PyObjectBase::_repr(), MatGui::MaterialsEditor::accept(), Gui::Application::activateWorkbench(), Materials::Material::addAppearance(), Materials::MaterialYamlEntry::addToTree(), MatGui::Array2D::Array2D(), MatGui::Array3D::Array3D(), Sketcher::SketchAnalysis::autoconstraint(), Gui::Gui::GestureNavigationStyle ::AwaitingMoveState::AwaitingMoveState(), Gui::Gui::GestureNavigationStyle ::AwaitingReleaseState::AwaitingReleaseState(), TechDraw::BaseGeom::baseFactory(), Gui::MacroManager::cancel(), Gui::ViewProvider::canDropObject(), Sketcher::SketchObject::changeConstraintsLocking(), PartDesignGui::TaskHoleParameters::changedObject(), Gui::Dialog::DocumentRecoveryHandler::checkForPreviousCrashes(), Gui::MacroManager::commit(), App::PropertyFileIncluded::Copy(), FemGui::ViewProviderFEMMeshBuilder::createMesh(), Fem::createObjectByType(), Gui::WidgetFactoryInst::createPreferencePage(), Gui::WidgetFactoryInst::createWidget(), Gui::Dialog::ButtonModel::data(), debugprint(), Materials::MaterialLibrary::deleteFile(), Materials::MaterialLoader::dereference(), App::Application::destruct(), SketcherGui::EditModeConstraintCoinManager::detectPreselectionConstr(), GCS::System::diagnose(), MeshGui::ViewProviderMeshTransformDemolding::DragEndCallback(), SketcherGui::ViewProviderSketch::editDoubleClicked(), Gui::ViewerEventFilter::eventFilter(), TechDraw::DrawViewMulti::execute(), Part::ImportBrep::execute(), Part::CurveNet::execute(), Part::ImportIges::execute(), Part::ImportStep::execute(), Drawing::FeaturePage::execute(), Fem::FemMeshShapeNetgenObject::execute(), TechDraw::DrawViewDimension::execute(), Fem::FemVTKTools::exportFreeCADResult(), Gui::ViewProviderGroupExtension::extensionCanDropObject(), Sketcher::SketchObject::fillet(), MeshCore::MeshAlgorithm::FillupHole(), MeshCore::MeshTopoAlgorithm::FillupHoles(), MeshCore::CylinderFit::Fit(), MeshGui::SoFCMeshObjectShape::generatePrimitives(), MeshGui::SoFCMeshSegmentShape::generatePrimitives(), Gui::Gui::GestureNavigationStyle ::GestureState::GestureState(), Gui::Dialog::DlgSettingsWorkbenchesImp::getDisabledWorkbenches(), Gui::Dialog::DlgSettingsWorkbenchesImp::getEnabledWorkbenches(), getLocatedShape(), Materials::Material::getMaterialAppearance(), Materials::MaterialConfigLoader::getMaterialFromPath(), Materials::MaterialLoader::getMaterialLibraries(), Measure::MeasureBaseExtendable< Part::MeasureAreaInfo >::getMeasureInfo(), Fem::FemMesh::getNodesBySolid(), MeasureGui::ViewProviderMeasureBase::getTextDirection(), MeasureGui::ViewProviderMeasure::getTextPosition(), MeasureGui::ViewProviderMeasureBase::getViewScale(), PartGui::ViewProviderCurveNet::handleEvent(), Gui::Gui::GestureNavigationStyle ::IdleState::IdleState(), MatGui::ImageEdit::ImageEdit(), Base::Type::importModule(), Part::ImportStepParts(), Gui::GuiNativeEvent::initSpaceball(), Gui::Gui::GestureNavigationStyle ::InteractState::InteractState(), Gui::Command::invoke(), MeasureGui::ViewProviderMeasureBase::isSubjectVisible(), MatGui::ListEdit::ListEdit(), Fem::FemPostPipeline::load(), Mesh::MeshObject::load(), TechDraw::DrawViewSymbol::loadQDomDocument(), Gui::Gui::GestureNavigationStyle ::Event::log(), GCS::SolverReportingManager::LogToConsole(), MeshPart::CurveProjectorWithToolMesh::makeToolMesh(), TechDraw::DrawViewSection::mapToPage(), messageHandler(), Gui::GUIApplication::notify(), MatGui::MaterialsEditor::onAppearanceAdd(), SketcherGui::ViewProviderSketch::onCameraChanged(), MatGui::MaterialsEditor::onPhysicalAdd(), Gui::Document::onRelabel(), Gui::GestureNavigationStyle::onRollGesture(), MatGui::MaterialsEditor::onSelectMaterial(), Gui::PropertyView::onTimer(), Gui::View3DInventor::onUpdate(), Gui::Document::onUpdate(), Gui::MacroManager::open(), Gui::Gui::GestureNavigationStyle ::PanState::PanState(), Sketcher::SketchObject::port_reversedExternalArcs(), MeasureGui::ViewProviderMeasure::positionAnno(), Gui::GestureNavigationStyle::EventQueue::post(), App::Application::processFiles(), MeshPart::CurveProjectorShape::projectCurve(), MeshPart::CurveProjectorSimple::projectCurve(), MeshPart::MeshProjection::projectEdgeToEdge(), PyMOD_INIT_FUNC(), Base::PyObjectBase::PyObjectBase(), TestJtReader::read(), Materials::Material::removePhysical(), Gui::Gui::GestureNavigationStyle ::RotateState::RotateState(), Gui::ConsoleLogTask::run(), Gui::Application::runApplication(), App::Application::runApplication(), Gui::AutoSaver::saveDocument(), Materials::Material::saveModels(), Gui::Application::setActiveDocument(), Gui::ViewProviderTextureExtension::setCoinAppearance(), Gui::Translator::setLocale(), Sketcher::Sketch::setUpSketch(), Materials::MaterialProperty::setValue(), Materials::MaterialLoader::showYaml(), Gui::Application::slotDeleteDocument(), Sketcher::Sketch::solve(), FcLodHandler::startLod(), Gui::GUISingleApplication::Private::startServer(), Gui::Gui::GestureNavigationStyle ::StickyPanState::StickyPanState(), Base::RedirectStdOutput::sync(), Base::RedirectStdLog::sync(), FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary(), FemGui::TaskPostScalarClip::TaskPostScalarClip(), FemGui::TaskPostWarpVector::TaskPostWarpVector(), MatGui::TextEdit::TextEdit(), Gui::Gui::GestureNavigationStyle ::TiltState::TiltState(), SpaceNavigatorDevice::translateEvent(), MeshCore::AbstractPolygonTriangulator::TriangulatePolygon(), MatGui::MaterialTreeWidget::updateMaterial(), PartGui::ViewProviderPartExt::updateVisual(), Gui::Application::viewActivated(), Fem::FemMesh::write(), Fem::FemMesh::writeZ88(), Gui::GuiNativeEvent::xcbEventFilter(), Gui::Application::~Application(), Gui::GuiNativeEvent::~GuiNativeEvent(), and Base::PyObjectBase::~PyObjectBase().
Log() [2/2]
template<typename... Args> void Base::ConsoleSingleton::Log (const std::string & notifier, const char * pMsg, Args &&... args) inline
Prints a log Message with source indication.
Definition at line 1160 of file Console.h.
References toolbit-attributes::args.
LogLevel()
int Base::ConsoleSingleton::LogLevel (int level) const inline
Definition at line 828 of file Console.h.
References level().
Referenced by Base::LogLevel::level().
Message() [1/2]
template<typename... Args> void Base::ConsoleSingleton::Message (const char * pMsg, Args &&... args) inline
Prints a Message.
Prints a Message This method issues a Message. Messages are used to show some non vital information. That means when FreeCAD is running in GUI mode a Message appears on the status bar. In console mode a message is printed to the console.
You can use a printf like interface like:
Console().Message("Doing something important %d times\n",i);
See also
Warning
Error
Log
Critical
UserNotification
UserTranslatedNotification
Definition at line 1007 of file Console.h.
References toolbit-attributes::args.
Referenced by PartGui::DlgScale::accept(), CmdSandboxEventLoop::activated(), StdCmdViewIvIssueCamPos::activated(), TechDraw::CosmeticExtension::add1CEToGE(), TechDraw::CosmeticExtension::add1CVToGV(), TechDrawGui::QGSPage::addQView(), TechDraw::DrawUtil::angleWithX(), TechDraw::DrawUtil::apparentIntersection(), Gui::PreferencePack::apply(), TechDraw::BaseGeom::baseFactory(), buildAdapter(), TechDrawGui::QGIFace::buildPixHatch(), TechDrawGui::QGIFace::buildSvgHatch(), TechDraw::CenterLine::calcEndPoints(), TechDraw::CenterLine::calcEndPoints2Lines(), TechDrawGui::TaskRichAnno::calcTextStartPos(), TechDraw::CosmeticEdge::clone(), TechDraw::DrawUtil::copyFile(), TechDraw::DrawUtil::countEdges(), TechDraw::DrawUtil::countFaces(), TechDraw::DrawUtil::countWires(), TechDrawGui::QGISVGTemplate::createClickHandles(), Fem::createObjectByType(), MeshGui::ViewProviderMeshCurvature::curvatureInfoCallback(), TechDrawGui::QGILeaderLine::draw(), TechDrawGui::QGIViewPart::drawAllEdges(), TechDrawGui::QGIViewPart::drawComplexSectionLine(), TechDrawGui::QGIViewPart::drawSectionLine(), TechDrawGui::QGIWeldSymbol::drawTile(), TechDraw::CosmeticVertex::dump(), TechDraw::DashSpec::dump(), TechDraw::CosmeticEdge::dump(), TechDraw::LineGroup::dump(), TechDraw::PATLineSpec::dump(), TechDraw::pointPair::dump(), TechDraw::LineFormat::dump(), TechDraw::GeomFormat::dump(), TechDraw::anglePoints::dump(), TechDraw::CenterLine::dump(), TechDraw::arcPoints::dump(), TechDraw::areaPoint::dump(), TechDraw::Vertex::dump(), TechDraw::DrawUtil::dump1Vertex(), TechDraw::DrawViewPart::dumpCosEdges(), TechDraw::DrawViewPart::dumpCosVerts(), TechDraw::DrawUtil::dumpCS(), TechDraw::DrawUtil::dumpCS3(), TechDraw::DrawUtil::dumpEdge(), TechDraw::DrawUtil::dumpEdges(), TechDrawGui::QGEPath::dumpGhostPoints(), TechDraw::DrawProjGroup::dumpISO(), TechDrawGui::QGEPath::dumpMarkerPos(), TechDrawGui::QGIViewPart::dumpPath(), TechDrawGui::DrawGuiUtil::dumpPointF(), TechDrawGui::QGIView::dumpRect(), TechDrawGui::DrawGuiUtil::dumpRectF(), TechDrawGui::TaskLeaderLine::dumpTrackerPoints(), TechDraw::DrawUtil::dumpVertexes(), TechDraw::DrawProjectSplit::dumpVertexMap(), TechDraw::DrawViewPart::dumpVerts(), TechDraw::DrawLeaderLine::dumpWaypoints(), TechDraw::Ellipse::Ellipse(), Base::Debugger::exec(), Sandbox::SandboxObject::execute(), TechDraw::DrawBrokenView::execute(), TechDraw::DrawViewPart::execute(), Inspection::Feature::execute(), Import::ImpExpDxfWrite::exportBCurve(), Import::ImpExpDxfWrite::exportBSpline(), MeshGui::ViewProviderMesh::faceInfo(), MeshGui::ViewProviderMesh::faceInfoCallback(), FC_LOG_LEVEL_INIT(), MeshGui::ViewProviderMesh::fillHoleCallback(), TechDraw::BaseGeom::findEndPoints(), TechDrawGui::QGIViewDimension::findIsoExt(), MeshCore::SphereFit::Fit(), TechDrawGui::TaskDetail::getAnchorScene(), TechDraw::DrawProjectSplit::getEdgesForWalker(), TechDraw::BaseGeom::getEndPoint(), MeshGui::ViewProviderMesh::getFacetsFromPolygon(), TechDraw::LineGroup::getGroupNamesFromFile(), TechDraw::LineGenerator::getLineDescriptions(), MeshGui::CylinderFitParameter::getParameter(), TechDraw::PATLineSpec::getPatternList(), CDxfWrite::getPlateFile(), TechDraw::LineGroup::getRecordFromFile(), TechDraw::DrawViewDimension::getRefType(), TechDraw::DrawViewDimension::getSavedBox(), TechDraw::DrawViewSection::getShapeToCut(), TechDraw::PATLineSpec::getSpecsForPattern(), TechDraw::BaseGeom::getStartPoint(), TechDraw::DrawViewPart::getViewAxis(), TechDraw::DrawProjGroupItem::getXDirection(), TechDraw::ShapeExtractor::getXShapes(), CDxfRead::ImportObservation(), InspectionGui::ViewProviderInspection::inspectCallback(), TechDraw::DrawUtil::Intersect2d(), TechDraw::DrawUtil::intersect2Lines3d(), TechDraw::DrawBrokenView::isBreakObjectSketch(), ModelRefine::FaceTypedBSpline::isEqual(), TechDraw::DrawLeaderLine::isParentReady(), TechDraw::PATLineSpec::load(), Gui::MainWindow::loadUrls(), TechDraw::DrawLeaderLine::makeLeader(), TechDraw::DrawViewSection::makeLineSets(), Part::TopoShape::makeLoft(), TechDraw::DrawComplexSection::makeSectionCut(), TechDraw::DrawComplexSection::makeSectionLineWire(), MeshGui::ViewProviderMesh::markPartCallback(), TechDraw::DrawUtil::maskDirection(), MeasureAngleHandler(), MeasureAreaHandler(), MeasureDistanceHandler(), MeasureLengthHandler(), MeasurePositionHandler(), messageHandler(), PartDesignGui::ViewProviderBody::onChanged(), Sandbox::SandboxObject::onChanged(), Fem::ConstraintFluidBoundary::onChanged(), TechDraw::DrawPage::onChanged(), TechDrawGui::TaskDetail::onHighlightMoved(), FemGui::TaskCreateNodeSet::onSelectionChanged(), TechDrawGui::TaskLeaderLine::onTrackerClicked(), TechDrawGui::TaskLeaderLine::onTrackerFinished(), PartMeasureTypeCb(), MeshGui::ViewProviderMesh::partMeshCallback(), FemGui::TaskPostDataAlongLine::pointCallback(), FemGui::TaskPostDataAtPoint::pointCallback(), TechDraw::DrawProjectSplit::removeDuplicateEdges(), TechDrawGui::TaskLeaderLine::removeFeature(), Sandbox::SandboxObject::resetValue(), App::Document::Restore(), Part::TopoShape::revolve(), Sandbox::DocumentTestThread::run(), BarThread::run(), MeshTestJob::run(), Gui::ConsoleMessageTask::run(), TechDraw::CenterLine::Save(), TechDraw::DrawViewSection::sectionExec(), MeshGui::ViewProviderMesh::segmMeshCallback(), Sandbox::SandboxObject::setIntValue(), TechDrawGui::QGTracker::setPoint(), TechDrawGui::QGEPath::showMarkers(), TechDrawGui::ViewProviderDrawingView::showProgressMessage(), TechDraw::DrawUtil::simpleMinDist(), TechDraw::EdgeWalker::sortStrip(), TechDraw::DrawProjectSplit::split1Edge(), Gui::TaskMeasure::update(), TechDraw::DrawProjGroup::updateSecondaryDirs(), TechDrawGui::TaskWeldingSymbol::updateTiles(), Gui::OutputStdout::write(), TechDraw::DrawViewDetail::~DrawViewDetail(), TechDraw::DrawViewPart::~DrawViewPart(), and TechDraw::DrawViewSection::~DrawViewSection().
Message() [2/2]
template<typename... Args> void Base::ConsoleSingleton::Message (const std::string & notifier, const char * pMsg, Args &&... args) inline
Prints a Message with source indication.
Definition at line 1014 of file Console.h.
References toolbit-attributes::args.
Notify()
template<Base::LogStyle category, Base::IntendedRecipient recipient, Base::ContentType contenttype> void Base::ConsoleSingleton::Notify (const std::string & notifiername, const std::string & msg) inline
Definition at line 1188 of file Console.h.
References Path.Op.Surface::msg.
Referenced by Import::Tools::printLabel().
operator=() [1/2]
ConsoleSingleton& Base::ConsoleSingleton::operator= (ConsoleSingleton &&) delete
operator=() [2/2]
ConsoleSingleton& Base::ConsoleSingleton::operator= (const ConsoleSingleton &) delete
Refresh()
void ConsoleSingleton::Refresh ()
Definition at line 376 of file Console.cpp.
Send()
template<Base::LogStyle category, Base::IntendedRecipient recipient, Base::ContentType contenttype, typename... Args> void Base::ConsoleSingleton::Send (const std::string & notifiername, const char * pMsg, Args &&... args) inline
Sends a message of type LogStyle (Message, Warning, Error, Log, Critical or Notification). This function is used by all specific convenience functions (Send(), Message(), Warning(), Error(), Log(), Critical and UserNotification, without or without notifier id).
Notification can be direct or via queue.
Definition at line 1170 of file Console.h.
References toolbit-attributes::args, and Path.Post.scripts.grbl_post::type.
Referenced by Gui::Notify().
SetConnectionMode()
void ConsoleSingleton::SetConnectionMode (ConnectionMode mode)
Definition at line 284 of file Console.cpp.
References Base::ConsoleOutput::getInstance(), and Queued.
SetConsoleMode()
void ConsoleSingleton::SetConsoleMode (ConsoleMode mode)
Change mode.
sets the console in a special mode
Definition at line 175 of file Console.cpp.
References Verbose.
SetDefaultLogLevel()
void Base::ConsoleSingleton::SetDefaultLogLevel (int level) inline
Definition at line 823 of file Console.h.
SetEnabledMsgType()
ConsoleMsgFlags ConsoleSingleton::SetEnabledMsgType (const char * sObs, ConsoleMsgFlags type, bool on)
Enables or disables message types of a certain console observer.
type can be OR'ed with any of the FreeCAD_ConsoleMsgType flags to enable – if b is true – or to disable – if b is false – a console observer with name sObs. The return value is an OR'ed value of all message types that have changed their state. For example
// switch off warnings and error messages
ConsoleMsgFlags ret = Base::Console().SetEnabledMsgType("myObs",
                      Base:ConsoleSingleton::MsgType_Wrn|Base::ConsoleSingleton::MsgType_Err,
false);
// do something without notifying observer myObs
...
// restore the former configuration again
Base::Console().SetEnabledMsgType("myObs", ret, true);
switches off warnings and error messages and restore the state before the modification. If the observer sObs doesn't exist then nothing happens.
Definition at line 210 of file Console.cpp.
References Base::ILogger::bCritical, Base::ILogger::bErr, Base::ILogger::bLog, Base::ILogger::bMsg, Base::ILogger::bNotification, Base::ILogger::bWrn, Get(), MsgType_Critical, MsgType_Err, MsgType_Log, MsgType_Notification, MsgType_Txt, MsgType_Wrn, and Path.Post.scripts.grbl_post::type.
Referenced by Gui::MainWindowP::restoreWindowState().
TranslatedUserError()
template<typename... Args> void Base::ConsoleSingleton::TranslatedUserError (const std::string & notifier, const char * pMsg, Args &&... args) inline
Definition at line 1097 of file Console.h.
References toolbit-attributes::args.
TranslatedUserWarning()
template<typename... Args> void Base::ConsoleSingleton::TranslatedUserWarning (const std::string & notifier, const char * pMsg, Args &&... args) inline
Definition at line 1053 of file Console.h.
References toolbit-attributes::args.
UnsetConsoleMode()
void ConsoleSingleton::UnsetConsoleMode (ConsoleMode mode)
Change mode.
unsets the console from a special mode
Definition at line 185 of file Console.cpp.
References Verbose.
UserError()
template<typename... Args> void Base::ConsoleSingleton::UserError (const std::string & notifier, const char * pMsg, Args &&... args) inline
Definition at line 1088 of file Console.h.
References toolbit-attributes::args.
UserNotification() [1/2]
template<typename... Args> void Base::ConsoleSingleton::UserNotification (const char * pMsg, Args &&... args) inline
Sends a User Notification.
Definition at line 1121 of file Console.h.
References toolbit-attributes::args.
UserNotification() [2/2]
template<typename... Args> void Base::ConsoleSingleton::UserNotification (const std::string & notifier, const char * pMsg, Args &&... args) inline
Sends a User Notification with source indication.
Definition at line 1127 of file Console.h.
References toolbit-attributes::args, Base::Notification, Base::Untranslated, and Base::User.
UserTranslatedNotification() [1/2]
template<typename... Args> void Base::ConsoleSingleton::UserTranslatedNotification (const char * pMsg, Args &&... args) inline
Sends an already translated User Notification.
Definition at line 1137 of file Console.h.
References toolbit-attributes::args.
Referenced by AssemblyGui::ViewProviderAssemblyLink::setEdit().
UserTranslatedNotification() [2/2]
template<typename... Args> void Base::ConsoleSingleton::UserTranslatedNotification (const std::string & notifier, const char * pMsg, Args &&... args) inline
Sends an already translated User Notification with source indication.
Definition at line 1143 of file Console.h.
References toolbit-attributes::args, Base::Notification, Base::Translated, and Base::User.
UserWarning()
template<typename... Args> void Base::ConsoleSingleton::UserWarning (const std::string & notifier, const char * pMsg, Args &&... args) inline
Definition at line 1044 of file Console.h.
References toolbit-attributes::args.
Warning() [1/2]
template<typename... Args> void Base::ConsoleSingleton::Warning (const char * pMsg, Args &&... args) inline
Prints a warning Message.
Definition at line 1020 of file Console.h.
References toolbit-attributes::args, and Base::Warning.
Referenced by Attacher::AttachEngine3D::_calculateAttachedPlacement(), Attacher::AttachEngineLine::_calculateAttachedPlacement(), Part::TopoShape::_makeTransform(), ReverseEngineeringGui::Segmentation::accept(), FemGui::TaskDlgMeshShapeNetgen::accept(), RobotGui::TaskDlgEdge2Trac::accept(), MeshGui::GmshWidget::accept(), FemGui::TaskDlgCreateNodeSet::accept(), FemGui::TaskDlgCreateElementSet::accept(), FemGui::TaskDlgFemConstraintFluidBoundary::accept(), Gui::TaskView::TaskView::accept(), Sketcher::Sketch::addEqualConstraint(), Sketcher::Sketch::addPerpendicularConstraint(), Gui::CommandManager::addTo(), TechDraw::DrawPage::addView(), Sketcher::SketchAnalysis::analyseMissingPointOnPointCoincident(), PartDesignGui::TaskFilletParameters::apply(), PartDesignGui::TaskDraftParameters::apply(), PartDesignGui::TaskChamferParameters::apply(), PartDesignGui::TaskThicknessParameters::apply(), Gui::Dialog::PlacementHandler::applyPlacement(), TechDraw::DrawProjGroup::arrangeViewPointers(), TechDrawGui::ViewProviderDrawingView::attach(), PartDesignGui::TaskFeaturePick::buildFeatures(), TechDrawGui::QGIFace::buildPixHatch(), TechDrawGui::QGIFace::buildSvgHatch(), Gui::PropertyEditor::PropertyEditor::buildUp(), TechDraw::CenterLine::calcEndPoints(), TechDraw::CenterLine::calcEndPoints2Lines(), TechDraw::CenterLine::calcEndPoints2Points(), TechDraw::CenterLine::CenterLineBuilder(), Gui::Application::checkForDeprecatedSettings(), Gui::Application::checkForPreviousCrashes(), Part::ExtrusionHelper::checkInnerWires(), TechDraw::ShapeExtractor::checkShape(), FemGui::TaskDlgMeshShapeNetgen::clicked(), RobotGui::TaskDlgEdge2Trac::clicked(), Base::ConsoleObserverFile::ConsoleObserverFile(), TechDrawGui::QGISVGTemplate::createClickHandles(), ParameterGrp::CreateElement(), PartGui::ViewProvider2DObjectGrid::createGrid(), Gui::DocumentItem::createNewItem(), Gui::WidgetFactoryInst::createPreferencePage(), Gui::WidgetFactoryInst::createWidget(), TechDrawGui::PATPathMaker::dashedPPath(), FemGui::TaskCreateElementSet::DefineNodes(), App::Application::destruct(), GCS::System::diagnose(), TechDrawGui::QGIViewAnnotation::drawAnnotation(), TechDrawGui::QGIViewClip::drawClip(), TechDrawGui::QGIViewSection::drawSectionFace(), Gui::Translator::enableDecimalPointConversion(), Sketcher::SketchObjectSF::execute(), TechDraw::DrawViewSection::execute(), PartDesign::Transformed::execute(), Import::ImpExpDxfWrite::exportShape(), Gui::ViewProviderGroupExtension::extensionCanDropObject(), TechDraw::GeometryObject::extractGeometry(), TechDraw::DrawDimHelper::findClosestPoint(), ParameterGrp::FindElement(), TechDraw::DrawViewPart::findFacesNew(), TechDraw::DrawViewPart::findFacesOld(), TechDraw::DrawComplexSection::findSectionPlaneIntersections(), TechDraw::DrawViewSection::findSectionPlaneIntersections(), TechDraw::DimensionFormatter::formatValue(), Path::Toolpath::getCycleTime(), TechDraw::DrawViewDimension::getDimValue(), TechDraw::DrawProjGroup::getDirsFromFront(), TechDraw::DimensionFormatter::getPrefixSuffixSpec(), TechDrawGui::DrawGuiUtil::getProjDirFromFace(), TechDraw::DrawViewPart::getProjectionCS(), Assembly::AssemblyObject::getRackPinionMarkers(), AttacherGui::getUIStrings(), TechDraw::DrawProjGroup::getViewIndex(), Gui::View3DInventorViewer::getViewProviderByPath(), Gui::View3DInventorViewer::getViewProviderByPathFromTail(), Gui::View3DInventorViewer::getViewProvidersOfType(), TechDrawGui::QGILeaderLine::getWayPointsFromFeature(), Assembly::AssemblyObject::handleOneSideOfJoint(), Gui::View3DInventorViewer::imageFromFramebuffer(), CDxfRead::ImportError(), Gui::View3DInventorViewer::init(), AssemblyGui::ViewProviderAssembly::initMove(), TechDrawGui::TaskGeomHatch::initUi(), Sketcher::SketchObject::isCarbonCopyAllowed(), Sketcher::SketchObject::isExternalAllowed(), TechDraw::DimensionFormatter::isTooSmall(), TechDraw::isValidSingleFace3d(), TechDrawGui::PATPathMaker::lineSetToFillItems(), Mesh::MeshObject::load(), MeshCore::MeshInput::LoadAny(), Start::ExamplesModel::loadExamples(), MeshCore::MeshInput::LoadNastran(), TechDraw::DrawViewSymbol::loadQDomDocument(), loadTechDrawResource(), TechDraw::DrawComplexSection::makeCuttingTool(), TechDraw::DrawViewDetail::makeDetailShape(), TechDraw::DrawViewSection::makeFaceFromWires(), TechDraw::GeometryUtils::makePerforatedFace(), TechDraw::DrawViewSection::makeSectionCut(), messageHandler(), AssemblyGui::ViewProviderAssembly::mouseMove(), Part::Scale::nonuniformScale(), Gui::SelectionSingleton::notify(), App::Document::onChanged(), AssemblyGui::ViewProviderAssemblyLink::onDelete(), Import::ImpExpDxfRead::OnReadArc(), Import::ImpExpDxfRead::OnReadCircle(), Import::ImpExpDxfRead::OnReadEllipse(), Import::ImpExpDxfRead::OnReadSpline(), Gui::BitmapFactoryInst::pixmap(), TechDraw::DrawViewSection::prepareShape(), Gui::Command::printConflictingAccelerators(), TechDrawGui::PagePrinter::printPdf(), printPlacement(), App::Application::processCmdLineFiles(), App::Application::processFiles(), Base::ScriptFactorySingleton::ProduceScript(), TechDrawGui::Grabber3d::quickView(), Gui::Gui::GestureNavigationStyle ::GestureState::react(), PartDesign::FeatureAddSub::refineShapeIfActive(), Gui::TaskView::TaskView::reject(), TechDrawGui::TaskRichAnno::removeFeature(), Gui::View3DInventorViewer::resetEditingRoot(), App::PropertyPythonObject::Restore(), TechDraw::CosmeticEdge::Restore(), TechDraw::CenterLine::Restore(), Part::Geometry::Restore(), App::PropertyLink::Restore(), App::PropertyLinkSubList::Restore(), Fem::PropertyPostDataObject::RestoreDocFile(), TechDrawGui::QGIProjGroup::rotateView(), Gui::ConsoleWarningTask::run(), Gui::PythonDebugger::runFile(), TechDraw::CosmeticEdge::Save(), MeshCore::WriterOBJ::Save(), MeshCore::MeshOutput::SaveOFF(), TechDrawGui::PagePrinter::saveSVG(), TechDraw::CenterLine::scaledAndRotatedGeometry(), TechDraw::CenterLine::scaledGeometry(), TechDraw::DrawProjectSplit::scrubEdges(), Gui::Application::setActiveDocument(), SIM::Coin3D::Quarter::SoQTQuarterAdaptor::setCameraType(), Gui::PrefWidget::setParamGrpPath(), Gui::SelectionSingleton::slotSelectionChanged(), Sketcher::SketchObject::solve(), TechDraw::LineGroup::split(), Gui::ApplicationPy::sSendActiveView(), Gui::ApplicationPy::sSendFocusView(), FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary(), Gui::TaskView::TaskSelectLinkProperty::TaskSelectLinkProperty(), TechDraw::DrawProjGroupItem::unsetupObject(), TechDraw::DrawPage::unsetupObject(), TechDrawGui::QGILeaderLine::updateView(), TechDrawGui::QGIWeldSymbol::updateView(), Sketcher::SketchObject::validateExternalLinks(), Assembly::AssemblyObject::validateNewPlacements(), TechDrawGui::PreferencesGui::weldingDirectory(), PartGui::DlgProjectionOnSurface::~DlgProjectionOnSurface(), DocOpenGuard::~DocOpenGuard(), and App::Application::TransactionSignaller::~TransactionSignaller().
Warning() [2/2]
template<typename... Args> void Base::ConsoleSingleton::Warning (const std::string & notifier, const char * pMsg, Args &&... args) inline
Prints a warning Message with source indication.
Definition at line 1027 of file Console.h.
References toolbit-attributes::args.
Friends And Related Function Documentation
ConsoleOutput
friend class ConsoleOutput friend
Definition at line 902 of file Console.h.
Member Data Documentation
Methods
PyMethodDef ConsoleSingleton::Methods static
Definition at line 839 of file Console.h.
The documentation for this class was generated from the following files:
Console.h
Console.cpp