FreeCAD: ifc2x3.ifcmechanicalconcretematerialproperties Class Reference
ifc2x3.ifcmechanicalconcretematerialproperties Class Reference
Public Member Functions
def __init__ (self, inherited0__material, inherited1__dynamicviscosity, inherited2__youngmodulus, inherited3__shearmodulus, inherited4__poissonratio, inherited5__thermalexpansioncoefficient, compressivestrength, maxaggregatesize, admixturesdescription, workability, protectiveporeratio, waterimpermeability)
def compressivestrength ()
def maxaggregatesize ()
def admixturesdescription ()
def workability ()
def protectiveporeratio ()
def waterimpermeability ()
Public Member Functions inherited from ifc2x3.ifcmechanicalmaterialproperties
def __init__ (self, inherited0__material, dynamicviscosity, youngmodulus, shearmodulus, poissonratio, thermalexpansioncoefficient)
def dynamicviscosity ()
def youngmodulus ()
def shearmodulus ()
def poissonratio ()
def thermalexpansioncoefficient ()
def wr21 (self)
def wr22 (self)
Public Member Functions inherited from ifc2x3.ifcmaterialproperties
def __init__ (self, material)
def material ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
compressivestrength
maxaggregatesize
admixturesdescription
workability
protectiveporeratio
waterimpermeability
Public Attributes inherited from ifc2x3.ifcmechanicalmaterialproperties
dynamicviscosity
youngmodulus
shearmodulus
poissonratio
thermalexpansioncoefficient
Public Attributes inherited from ifc2x3.ifcmaterialproperties
material
Detailed Description
Entity ifcmechanicalconcretematerialproperties definition.
:param compressivestrength
:type compressivestrength:ifcpressuremeasure
:param maxaggregatesize
:type maxaggregatesize:ifcpositivelengthmeasure
:param admixturesdescription
:type admixturesdescription:ifctext
:param workability
:type workability:ifctext
:param protectiveporeratio
:type protectiveporeratio:ifcnormalisedratiomeasure
:param waterimpermeability
:type waterimpermeability:ifctext
Definition at line 9914 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcmechanicalconcretematerialproperties.__init__ (self, inherited0__material, inherited1__dynamicviscosity, inherited2__youngmodulus, inherited3__shearmodulus, inherited4__poissonratio, inherited5__thermalexpansioncoefficient, compressivestrength, maxaggregatesize, admixturesdescription, workability, protectiveporeratio, waterimpermeability)
Definition at line 9935 of file ifc2x3.py.
Member Function Documentation
admixturesdescription()
def ifc2x3.ifcmechanicalconcretematerialproperties.admixturesdescription ()
Definition at line 9973 of file ifc2x3.py.
References ifc2x3.ifcmechanicalconcretematerialproperties._admixturesdescription, ifc2x3.ifcmechanicalconcretematerialproperties.admixturesdescription, and SCL.TypeChecker.check_type().
compressivestrength()
def ifc2x3.ifcmechanicalconcretematerialproperties.compressivestrength ()
Definition at line 9945 of file ifc2x3.py.
References ifc2x3.ifcmechanicalconcretematerialproperties._compressivestrength, SCL.TypeChecker.check_type(), and ifc2x3.ifcmechanicalconcretematerialproperties.compressivestrength.
maxaggregatesize()
def ifc2x3.ifcmechanicalconcretematerialproperties.maxaggregatesize ()
Definition at line 9959 of file ifc2x3.py.
References ifc2x3.ifcmechanicalconcretematerialproperties._maxaggregatesize, SCL.TypeChecker.check_type(), and ifc2x3.ifcmechanicalconcretematerialproperties.maxaggregatesize.
protectiveporeratio()
def ifc2x3.ifcmechanicalconcretematerialproperties.protectiveporeratio ()
Definition at line 10001 of file ifc2x3.py.
References ifc2x3.ifcmechanicalconcretematerialproperties._protectiveporeratio, SCL.TypeChecker.check_type(), and ifc2x3.ifcmechanicalconcretematerialproperties.protectiveporeratio.
waterimpermeability()
def ifc2x3.ifcmechanicalconcretematerialproperties.waterimpermeability ()
Definition at line 10015 of file ifc2x3.py.
References ifc2x3.ifcmechanicalconcretematerialproperties._waterimpermeability, SCL.TypeChecker.check_type(), and ifc2x3.ifcmechanicalconcretematerialproperties.waterimpermeability.
workability()
def ifc2x3.ifcmechanicalconcretematerialproperties.workability ()
Definition at line 9987 of file ifc2x3.py.
References ifc2x3.ifcmechanicalconcretematerialproperties._workability, SCL.TypeChecker.check_type(), and ifc2x3.ifcmechanicalconcretematerialproperties.workability.
Member Data Documentation
admixturesdescription
ifc2x3.ifcmechanicalconcretematerialproperties.admixturesdescription
Definition at line 9939 of file ifc2x3.py.
Referenced by ifc2x3.ifcmechanicalconcretematerialproperties.admixturesdescription().
compressivestrength
ifc2x3.ifcmechanicalconcretematerialproperties.compressivestrength
Definition at line 9937 of file ifc2x3.py.
Referenced by ifc2x3.ifcmechanicalconcretematerialproperties.compressivestrength().
maxaggregatesize
ifc2x3.ifcmechanicalconcretematerialproperties.maxaggregatesize
Definition at line 9938 of file ifc2x3.py.
Referenced by ifc2x3.ifcmechanicalconcretematerialproperties.maxaggregatesize().
protectiveporeratio
ifc2x3.ifcmechanicalconcretematerialproperties.protectiveporeratio
Definition at line 9941 of file ifc2x3.py.
Referenced by ifc2x3.ifcmechanicalconcretematerialproperties.protectiveporeratio().
waterimpermeability
ifc2x3.ifcmechanicalconcretematerialproperties.waterimpermeability
Definition at line 9942 of file ifc2x3.py.
Referenced by ifc2x3.ifcmechanicalconcretematerialproperties.waterimpermeability().
workability
ifc2x3.ifcmechanicalconcretematerialproperties.workability
Definition at line 9940 of file ifc2x3.py.
Referenced by ifc2x3.ifcmechanicalconcretematerialproperties.workability().
The documentation for this class was generated from the following file:
ifc2x3.py