FreeCAD: TechDrawGui::QGIPrimPath Class Reference
TechDrawGui::QGIPrimPath Class Reference
#include <QGIPrimPath.h>
Public Types
enum { Type = QGraphicsItem::UserType + 170 }
Public Member Functions
QGIPrimPath ()
~QGIPrimPath () override=default
int type () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
QPainterPath shape () const override
virtual void setPrettyNormal ()
virtual void setPrettyPre ()
virtual void setPrettySel ()
virtual void setWidth (double w)
virtual double getWidth ()
Qt::PenStyle getStyle ()
void setStyle (Qt::PenStyle s)
void setStyle (int s)
virtual void setNormalColor (QColor c)
virtual void setCapStyle (Qt::PenCapStyle c)
void setFillStyle (Qt::BrushStyle f)
Qt::BrushStyle getFillStyle ()
void setFill (QColor c, Qt::BrushStyle s)
void setFill (QBrush b)
void resetFill ()
void setFillColor (QColor c)
QColor getFillColor ()
void setFillOverride (bool b)
virtual void setCurrentPen ()
Protected Member Functions
void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
virtual bool multiselectEligible ()
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
virtual QColor getNormalColor ()
virtual QColor getPreColor ()
virtual QColor getSelectColor ()
Base::Reference< ParameterGrp > getParmGroup ()
virtual Qt::PenCapStyle prefCapStyle ()
Protected Attributes
bool isHighlighted
bool multiselectActivated
QPen m_pen
QColor m_colCurrent
QColor m_colNormal
bool m_colOverride
Qt::PenStyle m_styleCurrent
Qt::PenStyle m_styleNormal
double m_width
Qt::PenCapStyle m_capStyle
QBrush m_brush
Qt::BrushStyle m_fillStyleCurrent
QColor m_fillColorCurrent
QColor m_colDefFill
QColor m_colNormalFill
Qt::BrushStyle m_fillDef
Qt::BrushStyle m_fillNormal
Qt::BrushStyle m_fillSelect
bool m_fillOverride
Detailed Description
Definition at line 42 of file QGIPrimPath.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 48 of file QGIPrimPath.h.
Constructor & Destructor Documentation
QGIPrimPath()
QGIPrimPath::QGIPrimPath () explicit
Definition at line 49 of file QGIPrimPath.cpp.
References getNormalColor(), isHighlighted, m_capStyle, m_colCurrent, m_colDefFill, m_colNormal, m_colOverride, m_fillDef, m_fillNormal, m_fillSelect, m_fillStyleCurrent, m_pen, m_styleCurrent, m_styleNormal, m_width, multiselectActivated, prefCapStyle(), setFillColor(), and setPrettyNormal().
Referenced by TechDrawGui::QGEPath::QGEPath().
~QGIPrimPath()
TechDrawGui::QGIPrimPath::~QGIPrimPath () override default
Member Function Documentation
getFillColor()
QColor TechDrawGui::QGIPrimPath::getFillColor () inline
Definition at line 73 of file QGIPrimPath.h.
getFillStyle()
Qt::BrushStyle TechDrawGui::QGIPrimPath::getFillStyle () inline
Definition at line 67 of file QGIPrimPath.h.
getNormalColor()
QColor QGIPrimPath::getNormalColor () protected virtual
Definition at line 142 of file QGIPrimPath.cpp.
References m_colNormal, m_colOverride, TechDrawGui::PreferencesGui::normalQColor(), and Init::parent.
Referenced by TechDrawGui::QGIArrow::QGIArrow(), QGIPrimPath(), and TechDrawGui::QGIEdge::setPrettyNormal().
getParmGroup()
Base::Reference< ParameterGrp > QGIPrimPath::getParmGroup () protected
Definition at line 231 of file QGIPrimPath.cpp.
getPreColor()
QColor QGIPrimPath::getPreColor () protected virtual
Definition at line 163 of file QGIPrimPath.cpp.
References Init::parent, and TechDrawGui::PreferencesGui::preselectQColor().
Referenced by setPrettyPre().
getSelectColor()
QColor QGIPrimPath::getSelectColor () protected virtual
Definition at line 179 of file QGIPrimPath.cpp.
References Init::parent, and TechDrawGui::PreferencesGui::selectQColor().
Referenced by setPrettySel().
getStyle()
Qt::PenStyle TechDrawGui::QGIPrimPath::getStyle () inline
Definition at line 59 of file QGIPrimPath.h.
getWidth()
virtual double TechDrawGui::QGIPrimPath::getWidth () inline virtual
Definition at line 58 of file QGIPrimPath.h.
Referenced by TechDrawGui::QGIViewBalloon::setSvgPens(), and TechDrawGui::QGIViewDimension::setSvgPens().
hoverEnterEvent()
void QGIPrimPath::hoverEnterEvent (QGraphicsSceneHoverEvent * event) override protected
Definition at line 101 of file QGIPrimPath.cpp.
References setPrettyPre().
Referenced by TechDrawGui::QGEPath::hoverEnterEvent().
hoverLeaveEvent()
void QGIPrimPath::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) override protected
Definition at line 110 of file QGIPrimPath.cpp.
References setPrettyNormal().
itemChange()
QVariant QGIPrimPath::itemChange (GraphicsItemChange change, const QVariant & value) override protected
Definition at line 88 of file QGIPrimPath.cpp.
References setPrettyNormal(), and setPrettySel().
Referenced by TechDrawGui::QGEPath::itemChange().
mousePressEvent()
void QGIPrimPath::mousePressEvent (QGraphicsSceneMouseEvent * event) override protected
Definition at line 242 of file QGIPrimPath.cpp.
References TechDrawGui::DrawGuiUtil::findObjectInSelection(), Gui::SelectionSingleton::getSelectionEx(), multiselectActivated, multiselectEligible(), TechDrawGui::PreferencesGui::multiSelection(), Init::parent, Path.Dressup.Utils::selection(), and Gui::Selection().
Referenced by TechDrawGui::QGMarker::mousePressEvent(), and TechDrawGui::QGTracker::mousePressEvent().
mouseReleaseEvent()
void QGIPrimPath::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) override protected
Definition at line 270 of file QGIPrimPath.cpp.
References multiselectActivated, and TechDrawGui::PreferencesGui::multiSelection().
Referenced by TechDrawGui::QGMarker::mouseReleaseEvent(), and TechDrawGui::QGTracker::mouseReleaseEvent().
multiselectEligible()
virtual bool TechDrawGui::QGIPrimPath::multiselectEligible () inline protected virtual
Reimplemented in TechDrawGui::QGIFace, TechDrawGui::QGIEdge, TechDrawGui::QGIVertex, and TechDrawGui::QGMarker.
Definition at line 83 of file QGIPrimPath.h.
Referenced by mousePressEvent().
paint()
void QGIPrimPath::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) override
Definition at line 318 of file QGIPrimPath.cpp.
References m_brush, m_fillColorCurrent, m_fillStyleCurrent, m_pen, and setCurrentPen().
Referenced by TechDrawGui::QGTracker::paint(), and TechDrawGui::QGIVertex::paint().
prefCapStyle()
Qt::PenCapStyle QGIPrimPath::prefCapStyle () protected virtual
Definition at line 237 of file QGIPrimPath.cpp.
Referenced by QGIPrimPath().
resetFill()
void QGIPrimPath::resetFill ()
Definition at line 298 of file QGIPrimPath.cpp.
References m_colDefFill, m_colNormalFill, m_fillDef, m_fillNormal, and m_fillStyleCurrent.
setCapStyle()
void QGIPrimPath::setCapStyle (Qt::PenCapStyle c) virtual
Definition at line 225 of file QGIPrimPath.cpp.
References SCL.SimpleDataTypes::c, m_capStyle, and m_pen.
setCurrentPen()
void QGIPrimPath::setCurrentPen () virtual
Reimplemented in TechDrawGui::QGIEdge.
Definition at line 311 of file QGIPrimPath.cpp.
References m_colCurrent, m_pen, m_styleCurrent, and m_width.
Referenced by paint().
setFill() [1/2]
void QGIPrimPath::setFill (QBrush b)
Definition at line 292 of file QGIPrimPath.cpp.
References SCL.SimpleDataTypes::b, m_fillNormal, m_fillStyleCurrent, and setFillColor().
setFill() [2/2]
void QGIPrimPath::setFill (QColor c, Qt::BrushStyle s)
Definition at line 286 of file QGIPrimPath.cpp.
References SCL.SimpleDataTypes::c, m_fillNormal, m_fillStyleCurrent, toolbit-attributes::s, and setFillColor().
Referenced by TechDrawGui::QGIFace::draw(), TechDrawGui::QGIWeldSymbol::drawAllAround(), TechDrawGui::QGIEdge::QGIEdge(), TechDrawGui::QGIFace::QGIFace(), TechDrawGui::QGIVertex::QGIVertex(), TechDrawGui::QGIViewBalloon::QGIViewBalloon(), and TechDrawGui::QGIWeldSymbol::QGIWeldSymbol().
setFillColor()
void QGIPrimPath::setFillColor (QColor c)
Definition at line 305 of file QGIPrimPath.cpp.
References SCL.SimpleDataTypes::c, m_colNormalFill, and m_fillColorCurrent.
Referenced by TechDrawGui::QGIViewPart::drawAllFaces(), TechDrawGui::QGIViewPart::drawAllVertexes(), TechDrawGui::QGIViewSection::drawSectionFace(), TechDrawGui::QGIView::makeMark(), TechDrawGui::QGIViewDimension::makeMarkC(), QGIPrimPath(), TechDrawGui::QGIViewBalloon::QGIViewBalloon(), setFill(), TechDrawGui::QGILeaderLine::setNormalColorAll(), TechDrawGui::QGIViewDimension::setNormalColorAll(), TechDrawGui::QGIViewBalloon::setNormalColorAll(), TechDrawGui::QGIViewBalloon::setPens(), and TechDrawGui::QGISectionLine::setTools().
setFillOverride()
void TechDrawGui::QGIPrimPath::setFillOverride (bool b) inline
Definition at line 74 of file QGIPrimPath.h.
References SCL.SimpleDataTypes::b.
Referenced by TechDrawGui::QGIViewBalloon::QGIViewBalloon().
setFillStyle()
void TechDrawGui::QGIPrimPath::setFillStyle (Qt::BrushStyle f) inline
Definition at line 66 of file QGIPrimPath.h.
References SCL.SimpleDataTypes::f.
Referenced by TechDrawGui::QGILeaderLine::draw(), TechDrawGui::QGIArrow::makeDot(), TechDrawGui::QGIArrow::makeFilledTriangle(), TechDrawGui::QGIArrow::makeForkArrow(), TechDrawGui::QGIArrow::makeHashMark(), TechDrawGui::QGIArrow::makeOpenArrow(), TechDrawGui::QGIArrow::makeOpenDot(), TechDrawGui::QGIArrow::makePyramid(), and TechDrawGui::QGIArrow::QGIArrow().
setNormalColor()
void QGIPrimPath::setNormalColor (QColor c) virtual
Definition at line 218 of file QGIPrimPath.cpp.
References SCL.SimpleDataTypes::c, m_colCurrent, m_colNormal, and m_colOverride.
Referenced by TechDrawGui::QGIWeldSymbol::drawAllAround(), TechDrawGui::QGIViewPart::drawAllEdges(), TechDrawGui::QGIViewPart::drawAllVertexes(), TechDrawGui::QGIViewPart::formatGeomFromCenterLine(), TechDrawGui::QGIViewPart::formatGeomFromCosmetic(), TechDrawGui::QGIView::makeMark(), TechDrawGui::QGIViewDimension::makeMarkC(), TechDrawGui::QGEPath::QGEPath(), TechDrawGui::QGIViewBalloon::QGIViewBalloon(), TechDrawGui::QGTracker::QGTracker(), TechDrawGui::QGILeaderLine::setNormalColorAll(), TechDrawGui::QGIViewDimension::setNormalColorAll(), TechDrawGui::QGIViewBalloon::setNormalColorAll(), TechDrawGui::QGIWeldSymbol::setPrettyNormal(), TechDrawGui::QGIWeldSymbol::setPrettyPre(), TechDrawGui::QGIWeldSymbol::setPrettySel(), and TechDrawGui::QGISectionLine::setTools().
setPrettyNormal()
void QGIPrimPath::setPrettyNormal () virtual
Reimplemented in TechDrawGui::QGIFace, TechDrawGui::QGIEdge, and TechDrawGui::QGICMark.
Definition at line 120 of file QGIPrimPath.cpp.
References m_colCurrent, m_colNormal, m_colNormalFill, and m_fillColorCurrent.
Referenced by TechDrawGui::QGIViewPart::drawAllVertexes(), hoverLeaveEvent(), TechDrawGui::QGEPath::hoverLeaveEvent(), itemChange(), TechDrawGui::QGEPath::itemChange(), TechDrawGui::QGIView::makeMark(), TechDrawGui::QGIViewDimension::makeMarkC(), TechDrawGui::QGEPath::QGEPath(), QGIPrimPath(), TechDrawGui::QGIViewBalloon::QGIViewBalloon(), TechDrawGui::QGTracker::QGTracker(), TechDrawGui::QGTracker::setCircleFromPoints(), TechDrawGui::QGTracker::setPathFromPoints(), TechDrawGui::QGTracker::setPoint(), TechDrawGui::QGIWeldSymbol::setPrettyNormal(), TechDrawGui::QGILeaderLine::setPrettyNormal(), TechDrawGui::QGIFace::setPrettyNormal(), TechDrawGui::QGIViewDimension::setPrettyNormal(), TechDrawGui::QGIViewBalloon::setPrettyNormal(), TechDrawGui::QGTracker::setSquareFromPoints(), and TechDrawGui::QGISectionLine::setTools().
setPrettyPre()
void QGIPrimPath::setPrettyPre () virtual
Reimplemented in TechDrawGui::QGIFace.
Definition at line 126 of file QGIPrimPath.cpp.
References getPreColor(), m_colCurrent, m_fillColorCurrent, and m_fillOverride.
Referenced by hoverEnterEvent(), TechDrawGui::QGEPath::hoverEnterEvent(), TechDrawGui::QGIWeldSymbol::setPrettyPre(), TechDrawGui::QGILeaderLine::setPrettyPre(), TechDrawGui::QGIFace::setPrettyPre(), TechDrawGui::QGIViewDimension::setPrettyPre(), and TechDrawGui::QGIViewBalloon::setPrettyPre().
setPrettySel()
void QGIPrimPath::setPrettySel () virtual
Reimplemented in TechDrawGui::QGIFace.
Definition at line 133 of file QGIPrimPath.cpp.
References getSelectColor(), m_colCurrent, m_fillColorCurrent, and m_fillOverride.
Referenced by itemChange(), TechDrawGui::QGEPath::itemChange(), TechDrawGui::QGIWeldSymbol::setPrettySel(), TechDrawGui::QGILeaderLine::setPrettySel(), TechDrawGui::QGIFace::setPrettySel(), TechDrawGui::QGIViewDimension::setPrettySel(), and TechDrawGui::QGIViewBalloon::setPrettySel().
setStyle() [1/2]
void QGIPrimPath::setStyle (int s)
Definition at line 210 of file QGIPrimPath.cpp.
References m_styleCurrent, m_styleNormal, and toolbit-attributes::s.
setStyle() [2/2]
void QGIPrimPath::setStyle (Qt::PenStyle s)
Definition at line 202 of file QGIPrimPath.cpp.
References m_styleCurrent, m_styleNormal, and toolbit-attributes::s.
Referenced by TechDrawGui::QGILeaderLine::draw(), TechDrawGui::QGIViewSection::drawSectionFace(), TechDrawGui::QGEPath::QGEPath(), TechDrawGui::QGIFace::QGIFace(), TechDrawGui::QGIViewBalloon::QGIViewBalloon(), TechDrawGui::QGIViewDimension::QGIViewDimension(), TechDrawGui::QGTracker::QGTracker(), and TechDrawGui::QGIFace::setDrawEdges().
setWidth()
void QGIPrimPath::setWidth (double w) virtual
Definition at line 195 of file QGIPrimPath.cpp.
References m_pen, m_width, and src.Mod.PartDesign.fcgear.svggear::w.
Referenced by TechDrawGui::QGILeaderLine::draw(), TechDrawGui::QGIWeldSymbol::drawAllAround(), TechDrawGui::QGIViewPart::drawAllEdges(), TechDrawGui::QGIWeldSymbol::drawFieldFlag(), TechDrawGui::QGIViewSection::drawSectionFace(), TechDrawGui::QGIViewPart::formatGeomFromCenterLine(), TechDrawGui::QGIViewPart::formatGeomFromCosmetic(), TechDrawGui::QGIView::makeMark(), TechDrawGui::QGIViewDimension::makeMarkC(), TechDrawGui::QGTracker::QGTracker(), TechDrawGui::QGILeaderLine::setArrows(), TechDrawGui::QGIEdge::setCosmetic(), TechDrawGui::QGIViewBalloon::setPens(), TechDrawGui::QGIViewDimension::setPens(), TechDrawGui::QGIViewBalloon::setSvgPens(), and TechDrawGui::QGIViewDimension::setSvgPens().
shape()
QPainterPath TechDrawGui::QGIPrimPath::shape () const inline override
Definition at line 52 of file QGIPrimPath.h.
type()
int TechDrawGui::QGIPrimPath::type () const inline override
Definition at line 50 of file QGIPrimPath.h.
Member Data Documentation
isHighlighted
bool TechDrawGui::QGIPrimPath::isHighlighted protected
Definition at line 94 of file QGIPrimPath.h.
Referenced by QGIPrimPath().
m_brush
QBrush TechDrawGui::QGIPrimPath::m_brush protected
Definition at line 106 of file QGIPrimPath.h.
Referenced by TechDrawGui::QGIFace::draw(), paint(), TechDrawGui::QGIFace::setPrettyNormal(), TechDrawGui::QGIFace::setPrettyPre(), and TechDrawGui::QGIFace::setPrettySel().
m_capStyle
Qt::PenCapStyle TechDrawGui::QGIPrimPath::m_capStyle protected
Definition at line 104 of file QGIPrimPath.h.
Referenced by QGIPrimPath(), and setCapStyle().
m_colCurrent
QColor TechDrawGui::QGIPrimPath::m_colCurrent protected
Definition at line 98 of file QGIPrimPath.h.
Referenced by QGIPrimPath(), setCurrentPen(), TechDrawGui::QGIEdge::setCurrentPen(), setNormalColor(), setPrettyNormal(), TechDrawGui::QGICMark::setPrettyNormal(), TechDrawGui::QGIEdge::setPrettyNormal(), setPrettyPre(), and setPrettySel().
m_colDefFill
QColor TechDrawGui::QGIPrimPath::m_colDefFill protected
Definition at line 110 of file QGIPrimPath.h.
Referenced by TechDrawGui::QGIArrow::QGIArrow(), TechDrawGui::QGIFace::QGIFace(), QGIPrimPath(), and resetFill().
m_colNormal
QColor TechDrawGui::QGIPrimPath::m_colNormal protected
Definition at line 99 of file QGIPrimPath.h.
Referenced by getNormalColor(), QGIPrimPath(), setNormalColor(), and setPrettyNormal().
m_colNormalFill
QColor TechDrawGui::QGIPrimPath::m_colNormalFill protected
Definition at line 111 of file QGIPrimPath.h.
Referenced by TechDrawGui::QGIFace::draw(), TechDrawGui::QGIArrow::QGIArrow(), resetFill(), setFillColor(), and setPrettyNormal().
m_colOverride
bool TechDrawGui::QGIPrimPath::m_colOverride protected
Definition at line 100 of file QGIPrimPath.h.
Referenced by getNormalColor(), QGIPrimPath(), and setNormalColor().
m_fillColorCurrent
QColor TechDrawGui::QGIPrimPath::m_fillColorCurrent protected
Definition at line 108 of file QGIPrimPath.h.
Referenced by paint(), setFillColor(), setPrettyNormal(), setPrettyPre(), and setPrettySel().
m_fillDef
Qt::BrushStyle TechDrawGui::QGIPrimPath::m_fillDef protected
Definition at line 112 of file QGIPrimPath.h.
Referenced by TechDrawGui::QGIFace::draw(), TechDrawGui::QGIFace::QGIFace(), QGIPrimPath(), and resetFill().
m_fillNormal
Qt::BrushStyle TechDrawGui::QGIPrimPath::m_fillNormal protected
Definition at line 113 of file QGIPrimPath.h.
Referenced by TechDrawGui::QGIFace::draw(), QGIPrimPath(), resetFill(), and setFill().
m_fillOverride
bool TechDrawGui::QGIPrimPath::m_fillOverride protected
Definition at line 116 of file QGIPrimPath.h.
Referenced by setPrettyPre(), and setPrettySel().
m_fillSelect
Qt::BrushStyle TechDrawGui::QGIPrimPath::m_fillSelect protected
Definition at line 114 of file QGIPrimPath.h.
Referenced by TechDrawGui::QGIFace::QGIFace(), and QGIPrimPath().
m_fillStyleCurrent
Qt::BrushStyle TechDrawGui::QGIPrimPath::m_fillStyleCurrent protected
Definition at line 107 of file QGIPrimPath.h.
Referenced by TechDrawGui::QGIFace::draw(), paint(), QGIPrimPath(), resetFill(), setFill(), TechDrawGui::QGIFace::setPrettyNormal(), TechDrawGui::QGIFace::setPrettyPre(), and TechDrawGui::QGIFace::setPrettySel().
m_pen
QPen TechDrawGui::QGIPrimPath::m_pen protected
Definition at line 97 of file QGIPrimPath.h.
Referenced by paint(), TechDrawGui::QGIFace::QGIFace(), QGIPrimPath(), setCapStyle(), setCurrentPen(), TechDrawGui::QGIEdge::setCurrentPen(), TechDrawGui::QGIEdge::setLinePen(), and setWidth().
m_styleCurrent
Qt::PenStyle TechDrawGui::QGIPrimPath::m_styleCurrent protected
Definition at line 101 of file QGIPrimPath.h.
Referenced by TechDrawGui::QGIFace::QGIFace(), QGIPrimPath(), setCurrentPen(), TechDrawGui::QGIEdge::setHiddenEdge(), and setStyle().
m_styleNormal
Qt::PenStyle TechDrawGui::QGIPrimPath::m_styleNormal protected
Definition at line 102 of file QGIPrimPath.h.
Referenced by QGIPrimPath(), and setStyle().
m_width
double TechDrawGui::QGIPrimPath::m_width protected
Definition at line 103 of file QGIPrimPath.h.
Referenced by TechDrawGui::QGICMark::QGICMark(), TechDrawGui::QGIEdge::QGIEdge(), QGIPrimPath(), setCurrentPen(), TechDrawGui::QGIEdge::setCurrentPen(), TechDrawGui::QGICMark::setThick(), and setWidth().
multiselectActivated
bool TechDrawGui::QGIPrimPath::multiselectActivated protected
Definition at line 95 of file QGIPrimPath.h.
Referenced by mousePressEvent(), mouseReleaseEvent(), and QGIPrimPath().
The documentation for this class was generated from the following files:
QGIPrimPath.h
QGIPrimPath.cpp