FreeCAD: App::color_traits< SbColor > Struct Reference
App::color_traits< SbColor > Struct Reference
#include <color_traits.h>
Public Types
using color_type = SbColor
Public Member Functions
color_traits ()=default
color_traits (const color_type &ct)
float redF () const
float greenF () const
float blueF () const
float alphaF () const
void setRedF (float red)
void setGreenF (float green)
void setBlueF (float blue)
void setAlphaF (float alpha)
int red () const
int green () const
int blue () const
int alpha () const
void setRed (int red)
void setGreen (int green)
void setBlue (int blue)
void setAlpha (int alpha)
Static Public Member Functions
static color_type makeColor (int red, int green, int blue, int alpha=255)
Detailed Description
Definition at line 55 of file color_traits.h.
Member Typedef Documentation
color_type
using App::color_traits< SbColor >::color_type = SbColor
Definition at line 76 of file color_traits.h.
Constructor & Destructor Documentation
color_traits() [1/2]
App::color_traits< SbColor >::color_traits () default
color_traits() [2/2]
App::color_traits< SbColor >::color_traits (const color_type & ct) inline explicit
Definition at line 78 of file color_traits.h.
Member Function Documentation
alpha()
int App::color_traits< SbColor >::alpha () const inline
Definition at line 125 of file color_traits.h.
alphaF()
float App::color_traits< SbColor >::alphaF () const inline
Definition at line 93 of file color_traits.h.
blue()
int App::color_traits< SbColor >::blue () const inline
Definition at line 121 of file color_traits.h.
References App::color_traits< color_type >::color_traits().
blueF()
float App::color_traits< SbColor >::blueF () const inline
Definition at line 89 of file color_traits.h.
green()
int App::color_traits< SbColor >::green () const inline
Definition at line 117 of file color_traits.h.
greenF()
float App::color_traits< SbColor >::greenF () const inline
Definition at line 85 of file color_traits.h.
makeColor()
static color_type App::color_traits< SbColor >::makeColor (int red, int green, int blue, int alpha = 255) inline static
Definition at line 145 of file color_traits.h.
References App::color_traits< color_type >::red().
red()
int App::color_traits< SbColor >::red () const inline
Definition at line 113 of file color_traits.h.
redF()
float App::color_traits< SbColor >::redF () const inline
Definition at line 81 of file color_traits.h.
setAlpha()
void App::color_traits< SbColor >::setAlpha (int alpha) inline
Definition at line 141 of file color_traits.h.
setAlphaF()
void App::color_traits< SbColor >::setAlphaF (float alpha) inline
Definition at line 109 of file color_traits.h.
References App::color_traits< color_type >::blue(), App::color_traits< color_type >::green(), and App::color_traits< color_type >::red().
setBlue()
void App::color_traits< SbColor >::setBlue (int blue) inline
Definition at line 137 of file color_traits.h.
setBlueF()
void App::color_traits< SbColor >::setBlueF (float blue) inline
Definition at line 105 of file color_traits.h.
setGreen()
void App::color_traits< SbColor >::setGreen (int green) inline
Definition at line 133 of file color_traits.h.
setGreenF()
void App::color_traits< SbColor >::setGreenF (float green) inline
Definition at line 101 of file color_traits.h.
setRed()
void App::color_traits< SbColor >::setRed (int red) inline
Definition at line 129 of file color_traits.h.
setRedF()
void App::color_traits< SbColor >::setRedF (float red) inline
Definition at line 97 of file color_traits.h.
The documentation for this struct was generated from the following file:
color_traits.h