FreeCAD: Inspection::InspectActualGeometry Class Reference
Inspection::InspectActualGeometry Class Reference abstract
#include <InspectionFeature.h>
Public Member Functions
InspectActualGeometry ()=default
virtual ~InspectActualGeometry ()=default
virtual unsigned long countPoints () const =0
Number of points to be checked.
virtual Base::Vector3f getPoint (unsigned long) const =0
Detailed Description
Delivers the number of points to be checked and returns the appropriate point to an index.
Definition at line 60 of file InspectionFeature.h.
Constructor & Destructor Documentation
InspectActualGeometry()
Inspection::InspectActualGeometry::InspectActualGeometry () default
~InspectActualGeometry()
virtual Inspection::InspectActualGeometry::~InspectActualGeometry () virtual default
Member Function Documentation
countPoints()
virtual unsigned long Inspection::InspectActualGeometry::countPoints () const pure virtual
Number of points to be checked.
Implemented in Inspection::InspectActualShape, Inspection::InspectActualPoints, and Inspection::InspectActualMesh.
Referenced by Inspection::Feature::execute().
getPoint()
virtual Base::Vector3f Inspection::InspectActualGeometry::getPoint (unsigned long) const pure virtual
Implemented in Inspection::InspectActualShape, Inspection::InspectActualPoints, and Inspection::InspectActualMesh.
Referenced by Inspection::Feature::execute(), and Inspection::DistanceInspection::mapped().
The documentation for this class was generated from the following file:
InspectionFeature.h