FreeCAD: Gui::LinkView Class Reference
Gui::LinkView Class Reference
#include <ViewProviderLink.h>
Classes
class Element
class SubInfo
Public Types
enum SnapshotType {
SnapshotTransform = 0, SnapshotVisible = 1, SnapshotChild = 2, SnapshotMax,
SnapshotContainer = -1, SnapshotContainerTransform = -2
}
Public Member Functions
LinkView ()
~LinkView () override
LinkView & operator= (const LinkView &)=delete
LinkView (const LinkView &)=delete
PyObject * getPyObject () override
void unlink (LinkInfoPtr) override
void onLinkedIconChange (LinkInfoPtr) override
void onLinkedUpdateData (LinkInfoPtr, const App::Property *) override
bool isLinked () const
SoFCSelectionRoot * getLinkRoot () const
QIcon getLinkedIcon (QPixmap overlay) const
void updateLink ()
void setLink (App::DocumentObject *obj, const std::vector< std::string > &subs=std::vector< std::string >())
void setLinkViewObject (ViewProviderDocumentObject *vpd, const std::vector< std::string > &subs=std::vector< std::string >())
std::vector< ViewProviderDocumentObject * > getChildren () const
void setMaterial (int index, const App::Material *material)
void setDrawStyle (int linePattern, double lineWidth=0, double pointSize=0)
void setTransform (int index, const Base::Matrix4D &mat)
void renderDoubleSide (bool)
void setSize (int size)
int getSize () const
void setNodeType (SnapshotType type, bool sublink=true)
void setChildren (const std::vector< App::DocumentObject * > &children, const boost::dynamic_bitset<> &vis, SnapshotType type=SnapshotVisible)
bool linkGetDetailPath (const char *, SoFullPath *, SoDetail *&) const
bool linkGetElementPicked (const SoPickedPoint *, std::string &) const
void setElementVisible (int index, bool visible)
bool isElementVisible (int index) const
ViewProviderDocumentObject * getOwner () const
void setOwner (ViewProviderDocumentObject *vpd)
bool hasSubs () const
std::vector< std::string > getSubNames () const
ViewProviderDocumentObject * getLinkedView () const
Base::BoundBox3d getBoundBox (ViewProviderDocumentObject *vpd=nullptr) const
void setInvalid ()
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static void setTransform (SoTransform *pcTransform, const Base::Matrix4D &mat)
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Protected Member Functions
void replaceLinkedRoot (SoSeparator *)
void resetRoot ()
bool getGroupHierarchy (int index, SoFullPath *path) const
Protected Member Functions inherited from Gui::LinkOwner
virtual ~LinkOwner ()=default
Protected Attributes
LinkInfoPtr linkOwner
LinkInfoPtr linkInfo
CoinPtr< SoFCSelectionRoot > pcLinkRoot
CoinPtr< SoTransform > pcTransform
CoinPtr< SoSeparator > pcLinkedRoot
CoinPtr< SoDrawStyle > pcDrawStyle
CoinPtr< SoShapeHints > pcShapeHints
SnapshotType nodeType
SnapshotType childType
bool autoSubLink
std::map< std::string, std::unique_ptr< SubInfo > > subInfo
std::vector< std::unique_ptr< Element > > nodeArray
std::unordered_map< SoNode *, int > nodeMap
Py::Object PythonObject
Friends
class SubInfo
Additional Inherited Members
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 78 of file ViewProviderLink.h.
Member Enumeration Documentation
SnapshotType
enum Gui::LinkView::SnapshotType
Enumerator
SnapshotTransform
SnapshotVisible
SnapshotChild
SnapshotMax
SnapshotContainer
SnapshotContainerTransform
Definition at line 119 of file ViewProviderLink.h.
Constructor & Destructor Documentation
LinkView() [1/2]
LinkView::LinkView ()
Definition at line 885 of file ViewProviderLink.cpp.
~LinkView()
LinkView::~LinkView () override
Definition at line 892 of file ViewProviderLink.cpp.
References linkInfo, linkOwner, and unlink().
LinkView() [2/2]
Gui::LinkView::LinkView (const LinkView &) delete
Member Function Documentation
getBoundBox()
Base::BoundBox3d LinkView::getBoundBox (ViewProviderDocumentObject * vpd = nullptr) const
Definition at line 931 of file ViewProviderLink.cpp.
References _getBoundBox(), LINK_THROW, linkOwner, and pcLinkRoot.
getChildren()
std::vector< ViewProviderDocumentObject * > LinkView::getChildren () const
Definition at line 1171 of file ViewProviderLink.cpp.
References Path.Log::info(), and nodeArray.
Referenced by bimcommands.BimIfcExplorer.BIM_IfcExplorer::getChildren(), bimcommands.BimIfcExplorer.BIM_IfcExplorer::getEntitiesTree(), and bimcommands.BimIfcExplorer.BIM_IfcExplorer::onSelectTree().
getGroupHierarchy()
bool LinkView::getGroupHierarchy (int index, SoFullPath * path) const protected
Definition at line 1459 of file ViewProviderLink.cpp.
References appendPath, Path.Log::info(), and nodeArray.
Referenced by linkGetDetailPath().
getLinkedIcon()
QIcon LinkView::getLinkedIcon (QPixmap overlay) const
Definition at line 1603 of file ViewProviderLink.cpp.
References autoSubLink, linkInfo, and subInfo.
Referenced by Gui::ViewProviderLink::getIcon().
getLinkedView()
ViewProviderDocumentObject * LinkView::getLinkedView () const
Definition at line 1205 of file ViewProviderLink.cpp.
References autoSubLink, linkInfo, and subInfo.
Referenced by Gui::ViewProviderLink::_setupContextMenu(), Gui::ViewProviderLink::doubleClicked(), and Gui::ViewProviderLink::startEditing().
getLinkRoot()
SoFCSelectionRoot* Gui::LinkView::getLinkRoot () const inline
Definition at line 95 of file ViewProviderLink.h.
Referenced by Gui::ViewProviderLink::applyColors(), Gui::ViewProviderLink::attach(), Gui::ViewProviderLink::onBeforeChange(), Gui::LinkView::Element::~Element(), and Gui::LinkView::SubInfo::~SubInfo().
getOwner()
ViewProviderDocumentObject * LinkView::getOwner () const
Definition at line 940 of file ViewProviderLink.cpp.
References linkOwner.
getPyObject()
PyObject * LinkView::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Definition at line 897 of file ViewProviderLink.cpp.
References Py::new_reference_to(), and PythonObject.
Referenced by Gui::ViewProviderLink::getPyLinkView().
getSize()
int Gui::LinkView::getSize () const inline
Definition at line 115 of file ViewProviderLink.h.
Referenced by Gui::ViewProviderLink::applyMaterial(), setMaterial(), and Gui::ViewProviderLink::updateDataPrivate().
getSubNames()
std::vector< std::string > LinkView::getSubNames () const
Definition at line 1212 of file ViewProviderLink.cpp.
References toolbit-attributes::s, subInfo, and TestSpreadsheet::v.
hasSubs()
bool LinkView::hasSubs () const
Definition at line 1612 of file ViewProviderLink.cpp.
References isLinked(), and subInfo.
Referenced by Gui::ViewProviderLink::initDraggingPlacement(), and Gui::ViewProviderLink::updateDataPrivate().
isElementVisible()
bool LinkView::isElementVisible (int index) const
Definition at line 1199 of file ViewProviderLink.cpp.
References nodeArray.
Referenced by linkGetElementPicked().
isLinked()
bool LinkView::isLinked () const
Definition at line 951 of file ViewProviderLink.cpp.
References linkInfo.
Referenced by Gui::ViewProviderLink::canDropObjectEx(), hasSubs(), Gui::ViewProviderLink::linkEdit(), linkGetDetailPath(), linkGetElementPicked(), setLinkViewObject(), setNodeType(), and updateLink().
linkGetDetailPath()
bool LinkView::linkGetDetailPath (const char * subname, SoFullPath * path, SoDetail *& det) const
Definition at line 1470 of file ViewProviderLink.cpp.
References appendPath, appendPathSafe(), autoSubLink, childType, dot(), DraftVecUtils::equals(), App::LinkBaseExtension::getArrayIndex(), getGroupHierarchy(), SplineSurface::i, Path.Log::info(), isLinked(), linkInfo, nodeArray, nodeType, pcLinkedRoot, pcLinkRoot, SnapshotTransform, subInfo, and TestSpreadsheet::v.
Referenced by Gui::ViewProviderLink::getDetailPath().
linkGetElementPicked()
bool LinkView::linkGetElementPicked (const SoPickedPoint * pp, std::string & subname) const
Definition at line 1363 of file ViewProviderLink.cpp.
References autoSubLink, childType, Path.Log::info(), isElementVisible(), isLinked(), linkInfo, nodeArray, nodeMap, nodeType, pcLinkedRoot, pcLinkRoot, RobotExample::pos, SnapshotTransform, subInfo, and TestSpreadsheet::v.
Referenced by Gui::ViewProviderLink::getElementPicked().
onLinkedIconChange()
void LinkView::onLinkedIconChange (LinkInfoPtr info) override virtual
Reimplemented from Gui::LinkOwner.
Definition at line 1274 of file ViewProviderLink.cpp.
References Path.Log::info(), linkInfo, and linkOwner.
Referenced by Gui::LinkView::SubInfo::onLinkedIconChange().
onLinkedUpdateData()
void LinkView::onLinkedUpdateData (LinkInfoPtr info, const App::Property * prop) override virtual
Reimplemented from Gui::LinkOwner.
Definition at line 1279 of file ViewProviderLink.cpp.
References create_qrc::ext, App::Property::getType(), Path.Log::info(), linkInfo, linkOwner, App::Property::Output, App::Prop_Output, and App::Property::testStatus().
operator=()
LinkView& Gui::LinkView::operator= (const LinkView &) delete
renderDoubleSide()
void LinkView::renderDoubleSide (bool enable)
Definition at line 985 of file ViewProviderLink.cpp.
References pcLinkRoot, and pcShapeHints.
Referenced by Gui::ViewProviderLink::updateDataPrivate().
replaceLinkedRoot()
void LinkView::replaceLinkedRoot (SoSeparator * root) protected
Definition at line 1249 of file ViewProviderLink.cpp.
References childType, Path.Log::info(), nodeArray, pcLinkedRoot, pcLinkRoot, and resetRoot().
Referenced by setNodeType(), and updateLink().
resetRoot()
void LinkView::resetRoot () protected
Definition at line 1097 of file ViewProviderLink.cpp.
References Gui::coinRemoveAllChildren(), pcDrawStyle, pcLinkRoot, pcShapeHints, and pcTransform.
Referenced by replaceLinkedRoot(), setChildren(), setSize(), and unlink().
setChildren()
void LinkView::setChildren (const std::vector< App::DocumentObject * > & children, const boost::dynamic_bitset<> & vis, SnapshotType type = SnapshotVisible)
Definition at line 1107 of file ViewProviderLink.cpp.
References childType, Gui::coinRemoveAllChildren(), App::DocumentObjectExtension::getExtensionClassTypeId(), App::GroupExtension::getGroupOfObject(), SplineSurface::i, Path.Log::info(), LINK_THROW, nodeArray, nodeMap, pcLinkedRoot, pcLinkRoot, resetRoot(), SnapshotContainer, SnapshotMax, and Path.Post.scripts.grbl_post::type.
Referenced by Gui::ViewProviderLink::updateElementList().
setDrawStyle()
void LinkView::setDrawStyle (int linePattern, double lineWidth = 0, double pointSize = 0)
Definition at line 955 of file ViewProviderLink.cpp.
References pcDrawStyle, and pcLinkRoot.
Referenced by Gui::ViewProviderLink::finishRestoring(), and Gui::ViewProviderLink::onChanged().
setElementVisible()
void LinkView::setElementVisible (int index, bool visible)
Definition at line 1194 of file ViewProviderLink.cpp.
References nodeArray.
Referenced by Gui::ViewProviderLink::updateDataPrivate().
setInvalid()
void LinkView::setInvalid ()
Definition at line 904 of file ViewProviderLink.cpp.
References PythonObject, and Base::PyObjectBase::setInvalid().
Referenced by Gui::ViewProviderLink::~ViewProviderLink().
setLink()
void LinkView::setLink (App::DocumentObject * obj, const std::vector< std::string > & subs = std::vector<std::string>())
Definition at line 1023 of file ViewProviderLink.cpp.
References Gui::Application::Instance, setLinkViewObject(), and importers.importIFCmulticore::subs.
Referenced by Gui::ViewProviderLink::updateDataPrivate().
setLinkViewObject()
void LinkView::setLinkViewObject (ViewProviderDocumentObject * vpd, const std::vector< std::string > & subs = std::vector<std::string>())
Definition at line 1029 of file ViewProviderLink.cpp.
References Data::findElementName(), Gui::LinkInfo::get(), isLinked(), linkInfo, subInfo, importers.importIFCmulticore::subs, unlink(), and updateLink().
Referenced by setLink().
setMaterial()
void LinkView::setMaterial (int index, const App::Material * material)
Definition at line 998 of file ViewProviderLink.cpp.
References SCL.SimpleDataTypes::c, App::Material::diffuseColor, getSize(), SplineSurface::i, Path.Log::info(), LINK_THROW, nodeArray, pcLinkRoot, and App::Material::transparency.
Referenced by Gui::ViewProviderLink::applyMaterial().
setNodeType()
void LinkView::setNodeType (SnapshotType type, bool sublink = true)
Definition at line 1225 of file ViewProviderLink.cpp.
References Path.Post.scripts.dynapath_4060_post::action, autoSubLink, isLinked(), LINK_THROW, linkInfo, nodeType, Gui::SoSelectionElementAction::None, pcLinkedRoot, replaceLinkedRoot(), SnapshotContainer, SnapshotContainerTransform, SnapshotMax, Path.Post.scripts.grbl_post::type, and updateLink().
Referenced by Gui::ViewProviderLink::setLinkType().
setOwner()
void LinkView::setOwner (ViewProviderDocumentObject * vpd)
Definition at line 946 of file ViewProviderLink.cpp.
References Gui::LinkInfo::get(), linkOwner, and unlink().
Referenced by Gui::ViewProviderLink::attach(), and Gui::ViewProviderLink::reattach().
setSize()
void LinkView::setSize (int size)
Definition at line 1063 of file ViewProviderLink.cpp.
References childType, SplineSurface::i, Path.Log::info(), nodeArray, nodeMap, pcLinkedRoot, pcLinkRoot, resetRoot(), and SnapshotContainer.
Referenced by Gui::ViewProviderLink::updateDataPrivate().
setTransform() [1/2]
void LinkView::setTransform (int index, const Base::Matrix4D & mat)
Definition at line 1180 of file ViewProviderLink.cpp.
References LINK_THROW, nodeArray, pcLinkRoot, and pcTransform.
Referenced by Gui::ViewProviderLink::updateDataPrivate(), and updateLink().
setTransform() [2/2]
void LinkView::setTransform (SoTransform * pcTransform, const Base::Matrix4D & mat) static
Definition at line 1054 of file ViewProviderLink.cpp.
References Base::Matrix4D::getGLMatrix(), and pcTransform.
unlink()
void LinkView::unlink (LinkInfoPtr info) override virtual
Reimplemented from Gui::LinkOwner.
Definition at line 1572 of file ViewProviderLink.cpp.
References Path.Log::info(), linkInfo, linkOwner, nodeArray, pcLinkedRoot, pcLinkRoot, resetRoot(), and subInfo.
Referenced by setLinkViewObject(), setOwner(), and ~LinkView().
updateLink()
void LinkView::updateLink ()
Definition at line 1300 of file ViewProviderLink.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Gui::SoSelectionElementAction::Append, appendPath, Gui::coinRemoveAllChildren(), FC_TRACE, App::DocumentObject::getSubObject(), isLinked(), linkInfo, linkOwner, nodeType, Gui::SoSelectionElementAction::None, pcLinkedRoot, pcLinkRoot, replaceLinkedRoot(), setTransform(), SnapshotContainer, SnapshotTransform, subInfo, and TestSpreadsheet::v.
Referenced by setLinkViewObject(), setNodeType(), and Gui::ViewProviderLink::updateDataPrivate().
Friends And Related Function Documentation
SubInfo
friend class SubInfo friend
Definition at line 176 of file ViewProviderLink.h.
Member Data Documentation
autoSubLink
bool Gui::LinkView::autoSubLink protected
Definition at line 174 of file ViewProviderLink.h.
Referenced by getLinkedIcon(), getLinkedView(), linkGetDetailPath(), linkGetElementPicked(), Gui::LinkView::SubInfo::onLinkedIconChange(), and setNodeType().
childType
SnapshotType Gui::LinkView::childType protected
Definition at line 173 of file ViewProviderLink.h.
Referenced by Gui::LinkView::Element::link(), linkGetDetailPath(), linkGetElementPicked(), replaceLinkedRoot(), setChildren(), and setSize().
linkInfo
LinkInfoPtr Gui::LinkView::linkInfo protected
Definition at line 166 of file ViewProviderLink.h.
Referenced by getLinkedIcon(), getLinkedView(), isLinked(), linkGetDetailPath(), linkGetElementPicked(), onLinkedIconChange(), Gui::LinkView::SubInfo::onLinkedIconChange(), onLinkedUpdateData(), setLinkViewObject(), setNodeType(), unlink(), updateLink(), and ~LinkView().
linkOwner
LinkInfoPtr Gui::LinkView::linkOwner protected
Definition at line 165 of file ViewProviderLink.h.
Referenced by getBoundBox(), getOwner(), onLinkedIconChange(), onLinkedUpdateData(), setOwner(), unlink(), updateLink(), and ~LinkView().
nodeArray
std::vector<std::unique_ptr<Element> > Gui::LinkView::nodeArray protected
Definition at line 180 of file ViewProviderLink.h.
Referenced by getChildren(), getGroupHierarchy(), isElementVisible(), linkGetDetailPath(), linkGetElementPicked(), replaceLinkedRoot(), setChildren(), setElementVisible(), setMaterial(), setSize(), setTransform(), and unlink().
nodeMap
std::unordered_map<SoNode*,int> Gui::LinkView::nodeMap protected
Definition at line 182 of file ViewProviderLink.h.
Referenced by linkGetElementPicked(), setChildren(), and setSize().
nodeType
SnapshotType Gui::LinkView::nodeType protected
Definition at line 172 of file ViewProviderLink.h.
Referenced by linkGetDetailPath(), linkGetElementPicked(), setNodeType(), and updateLink().
pcDrawStyle
CoinPtr<SoDrawStyle> Gui::LinkView::pcDrawStyle protected
Definition at line 170 of file ViewProviderLink.h.
Referenced by resetRoot(), and setDrawStyle().
pcLinkedRoot
CoinPtr<SoSeparator> Gui::LinkView::pcLinkedRoot protected
Definition at line 169 of file ViewProviderLink.h.
Referenced by linkGetDetailPath(), linkGetElementPicked(), replaceLinkedRoot(), setChildren(), setNodeType(), setSize(), unlink(), and updateLink().
pcLinkRoot
CoinPtr<SoFCSelectionRoot> Gui::LinkView::pcLinkRoot protected
Definition at line 167 of file ViewProviderLink.h.
Referenced by getBoundBox(), linkGetDetailPath(), linkGetElementPicked(), renderDoubleSide(), replaceLinkedRoot(), resetRoot(), setChildren(), setDrawStyle(), setMaterial(), setSize(), setTransform(), unlink(), and updateLink().
pcShapeHints
CoinPtr<SoShapeHints> Gui::LinkView::pcShapeHints protected
Definition at line 171 of file ViewProviderLink.h.
Referenced by renderDoubleSide(), and resetRoot().
pcTransform
CoinPtr<SoTransform> Gui::LinkView::pcTransform protected
Definition at line 168 of file ViewProviderLink.h.
Referenced by resetRoot(), and setTransform().
PythonObject
Py::Object Gui::LinkView::PythonObject protected
Definition at line 184 of file ViewProviderLink.h.
Referenced by getPyObject(), and setInvalid().
subInfo
std::map<std::string, std::unique_ptr<SubInfo> > Gui::LinkView::subInfo protected
Definition at line 178 of file ViewProviderLink.h.
Referenced by getLinkedIcon(), getLinkedView(), getSubNames(), hasSubs(), linkGetDetailPath(), linkGetElementPicked(), Gui::LinkView::SubInfo::onLinkedIconChange(), setLinkViewObject(), unlink(), and updateLink().
The documentation for this class was generated from the following files:
ViewProviderLink.h
ViewProviderLink.cpp