FreeCAD: TechDrawGui::ViewProviderPage Class Reference
TechDrawGui::ViewProviderPage Class Reference
#include <ViewProviderPage.h>
Public Types
using Connection = boost::signals2::scoped_connection
Public Types inherited from Gui::ViewProvider
enum EditMode { Default = 0, Transform, Cutting, Color }
Public Types inherited from App::ExtensionContainer
using ExtensionIterator = std::map< Base::Type, App::Extension * >::iterator
Public Member Functions
ViewProviderPage ()
constructor
~ViewProviderPage () override
destructor
void attach (App::DocumentObject *) override
bool canDragObjects () const override
bool canDragObject (App::DocumentObject *docObj) const override
bool canDropObject (App::DocumentObject *docObj) const override
void dropObject (App::DocumentObject *docObj) override
void constDropObject (App::DocumentObject *docObj) const
bool canDropObjectEx (App::DocumentObject *obj, App::DocumentObject *owner, const char *subname, const std::vector< std::string > &elements) const override
bool useNewSelectionModel () const override
indicates if the ViewProvider use the new Selection model
void hide () override
Hides the view provider.
void show () override
Shows the view provider.
bool isShow () const override
checks whether the view provider is visible or not
std::vector< App::DocumentObject * > claimChildren () const override
Claim all the views for the page.
bool doubleClicked () override
Is called by the tree if the user double click on the object.
void setupContextMenu (QMenu *, QObject *, const char *) override
set up the context-menu with the supported edit modes
bool onDelete (const std::vector< std::string > &) override
void onChanged (const App::Property *prop) override
Gets called by the container whenever a property has been changed.
void updateData (const App::Property *prop) override
TechDraw::DrawPage * getDrawPage () const
TechDraw::DrawTemplate * getTemplate () const
QGITemplate * getQTemplate (void) const
void onGuiRepaint (const TechDraw::DrawPage *dp)
Redo the whole visual page.
void unsetEdit (int ModNum) override
is called when you lose the edit mode
MDIViewPage * getMDIViewPage () const
bool showMDIViewPage ()
void removeMDIView ()
void switchToMdiViewPage ()
Gui::MDIView * getMDIView () const override
bool getFrameState ()
void setFrameState (bool state)
void toggleFrameState ()
void setTemplateMarkers (bool state)
bool canDelete (App::DocumentObject *obj) const override
Asks the view provider if the given object can be deleted.
void setGrid ()
QGSPage * getQGSPage (void) const
QGVPage * getQGVPage (void) const
ViewProviderPageExtension * getVPPExtension () const
const char * whoAmI () const
void fixSceneDependencies ()
void redrawPage () const
convenient way to ask feature to redraw everything
Public Member Functions inherited from Gui::ViewProviderDocumentObject
ViewProviderDocumentObject ()
constructor.
~ViewProviderDocumentObject () override
destructor.
virtual void reattach (App::DocumentObject *)
void update (const App::Property *) override
void setActiveMode ()
Set the active mode, i.e. the first item of the 'Display' property.
const char * getTransactionText () const override
int replaceObject (App::DocumentObject *, App::DocumentObject *) override
bool showInTree () const override
void getTaskViewContent (std::vector< Gui::TaskView::TaskContent * > &) const override
Get a list of TaskBoxes associated with this object.
void updateView ()
Run a redraw.
App::DocumentObject * getObject () const
Get the object of this ViewProvider object.
template<class T >
T * getObject () const
Get the object of this ViewProvider object as specified type.
virtual bool acceptDeletionsInEdit ()
Ask the view provider if it accepts object deletions while in edit.
Gui::Document * getDocument () const
Get the GUI document to this ViewProvider object.
PyObject * getPyObject () override
Get the python wrapper for that ViewProvider.
bool getElementPicked (const SoPickedPoint *, std::string &subname) const override
return a hit element given the picked point which contains the full node path
bool getDetailPath (const char *subname, SoFullPath *pPath, bool append, SoDetail *&det) const override
return the coin node detail and path to the node of the subname
virtual void forceUpdate (bool enable=true)
virtual bool isUpdateForced () const
virtual void startRestoring ()
virtual void finishRestoring ()
int getTreeRank () const
void setTreeRank (int value)
bool removeDynamicProperty (const char *prop) override
App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false) override
virtual ViewProviderDocumentObject * getLinkedViewProvider (std::string *subname=nullptr, bool recursive=false) const
std::string getFullName () const override
virtual bool allowOverride (const App::DocumentObject &) const
void setShowable (bool enable)
bool isShowable () const
void startDefaultEditMode ()
Public Member Functions inherited from Gui::ViewProvider
ViewProvider ()
constructor.
~ViewProvider () override
destructor.
virtual SoSeparator * getRoot () const
SoSwitch * getModeSwitch () const
SoTransform * getTransformNode () const
SoSeparator * getAnnotation ()
virtual SoSeparator * getFrontRoot () const
virtual SoGroup * getChildRoot () const
virtual SoSeparator * getBackRoot () const
virtual bool canAddToSceneGraph () const
Indicate whether to be added to scene graph or not.
virtual bool isPartOfPhysicalObject () const
virtual std::vector< App::DocumentObject * > claimChildren3D () const
virtual bool isSelectable () const
virtual std::string getElement (const SoDetail *) const
return a hit element to the selection path or 0
virtual SoDetail * getDetail (const char *) const
return the coin node detail of the subelement
int partialRender (const std::vector< std::string > &subelements, bool clear)
virtual std::vector< Base::Vector3d > getModelPoints (const SoPickedPoint *) const
virtual std::vector< Base::Vector3d > getSelectionShape (const char *Element) const
return the highlight lines for a given element or the whole shape
Base::BoundBox3d getBoundingBox (const char *subname=nullptr, bool transform=true, MDIView *view=nullptr) const
virtual void beforeDelete ()
virtual bool canDragObjectToTarget (App::DocumentObject *obj, App::DocumentObject *target) const
virtual void dragObject (App::DocumentObject *)
virtual bool canDropObjects () const
virtual bool canDragAndDropObject (App::DocumentObject *) const
virtual bool acceptReorderingObjects () const
virtual std::string getDropPrefix () const
return a subname referencing the sub-object holding the dropped objects
virtual std::string dropObjectEx (App::DocumentObject *obj, App::DocumentObject *owner, const char *subname, const std::vector< std::string > &elements)
virtual bool canRemoveChildrenFromRoot () const
std::string getActiveDisplayMode () const
virtual void setDisplayMode (const char *ModeName)
set the display mode
virtual const char * getDefaultDisplayMode () const
get the default display mode
virtual std::vector< std::string > getDisplayModes () const
returns a list of all possible display modes
void setVisible (bool)
bool isVisible () const
void setLinkVisible (bool)
bool isLinkVisible () const
virtual void setOverrideMode (const std::string &mode)
Overrides the display mode with mode.
const std::string getOverrideMode ()
virtual bool selectAll ()
virtual bool keyPressed (bool pressed, int key)
is called when the provider is in edit and a key event occurs. Only ESC ends edit.
virtual bool mouseMove (const SbVec2s &cursorPos, View3DInventorViewer *viewer)
is called when the provider is in edit and the mouse is moved
virtual bool mouseButtonPressed (int button, bool pressed, const SbVec2s &cursorPos, const View3DInventorViewer *viewer)
is called when the Provider is in edit and the mouse is clicked
virtual bool mouseWheelEvent (int delta, const SbVec2s &cursorPos, const View3DInventorViewer *viewer)
virtual QIcon getIcon () const
deliver the icon shown in the tree view
virtual QIcon mergeColorfulOverlayIcons (const QIcon &orig) const
virtual std::vector< App::DocumentObject * > claimChildrenRecursive () const
bool isUpdatesEnabled () const
void setUpdatesEnabled (bool enable)
unsigned long getStatus () const
return the status bits
bool testStatus (ViewStatus pos) const
void setStatus (ViewStatus pos, bool on)
std::string toString () const
virtual std::map< std::string, App::Color > getElementColors (const char *element=nullptr) const
virtual void setElementColors (const std::map< std::string, App::Color > &colors)
virtual ViewProvider * startEditing (int ModNum=0)
bool isEditing () const
void finishEditing ()
virtual void setEditViewer (View3DInventorViewer *, int ModNum)
adjust viewer settings when editing a view provider
virtual void unsetEditViewer (View3DInventorViewer *)
restores viewer settings when leaving editing mode
virtual void setTransformation (const Base::Matrix4D &rcMatrix)
set the viewing transformation of the provider
virtual void setTransformation (const SbMatrix &rcMatrix)
void Restore (Base::XMLReader &reader) override
bool isRestoring ()
void addDisplayMaskMode (SoNode *node, const char *type)
Adds a new display mask mode.
void setDisplayMaskMode (const char *type)
Activates the display mask mode type.
SoNode * getDisplayMaskMode (const char *type) const
Get the node to the display mask mode type.
std::vector< std::string > getDisplayMaskModes () const
Returns a list of added display mask modes.
void setDefaultMode (int)
int getDefaultMode () const
virtual void setRenderCacheMode (int)
Public Member Functions inherited from App::TransactionalObject
TransactionalObject ()
Constructor.
~TransactionalObject () override
Public Member Functions inherited from App::ExtensionContainer
ExtensionContainer ()
~ExtensionContainer () override
void registerExtension (Base::Type extension, App::Extension *ext)
bool hasExtension (Base::Type, bool derived=true) const
bool hasExtension (const std::string &name) const
bool hasExtensions () const
App::Extension * getExtension (Base::Type, bool derived=true, bool no_except=false) const
App::Extension * getExtension (const std::string &name) const
template<typename ExtensionT >
ExtensionT * getExtension () const
template<typename ExtensionT >
ExtensionT * getExtensionByType (bool no_except=false, bool derived=true) const
std::vector< Extension * > getExtensionsDerivedFrom (Base::Type type) const
template<typename ExtensionT >
std::vector< ExtensionT * > getExtensionsDerivedFromType () const
ExtensionIterator extensionBegin ()
ExtensionIterator extensionEnd ()
Property * getPropertyByName (const char *name) const override
find a property by its name
template<typename T >
T * getPropertyByName (const char *name) const
find a property by its name, dynamic cased to specified type
const char * getPropertyName (const Property *prop) const override
get the name of a property
void getPropertyMap (std::map< std::string, Property * > &Map) const override
get all properties of the class (including properties of the parent)
void getPropertyList (std::vector< Property * > &List) const override
get all properties of the class (including properties of the parent)
short getPropertyType (const Property *prop) const override
get the Type of a Property
short getPropertyType (const char *name) const override
get the Type of a named Property
const char * getPropertyGroup (const Property *prop) const override
get the Group of a Property
const char * getPropertyGroup (const char *name) const override
get the Group of a named Property
const char * getPropertyDocumentation (const Property *prop) const override
get the Group of a Property
const char * getPropertyDocumentation (const char *name) const override
get the Group of a named Property
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
void saveExtensions (Base::Writer &writer) const
void restoreExtensions (Base::XMLReader &reader)
void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName) override
void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop) override
Public Member Functions inherited from App::PropertyContainer
PropertyContainer ()
~PropertyContainer () override
unsigned int getMemSize () const override
virtual void getPropertyNamedList (std::vector< std::pair< const char *, Property * > > &List) const
get all properties with their names, may contain duplicates and aliases
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
bool isReadOnly (const Property *prop) const
check if the property is read-only
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isHidden (const Property *prop) const
check if the property is hidden
bool isHidden (const char *name) const
check if the named property is hidden
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
bool changeDynamicProperty (const Property *prop, const char *group, const char *doc)
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual App::Property * getDynamicPropertyByName (const char *name) const
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
virtual void beforeSave () const
virtual void editProperty (const char *)
const char * getPropertyPrefix () const
void setPropertyPrefix (const char *prefix)
PropertyContainer (const PropertyContainer &)=delete
PropertyContainer & operator= (const PropertyContainer &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from TechDrawGui::ViewProviderPageExtension
ViewProviderPageExtension ()
Constructor.
~ViewProviderPageExtension () override
bool extensionCanDragObjects () const override
bool extensionCanDragObject (App::DocumentObject *) const override
void extensionDragObject (App::DocumentObject *) override
bool extensionCanDropObjects () const override
bool extensionCanDropObject (App::DocumentObject *) const override
bool extensionCanDropObjectEx (App::DocumentObject *obj, App::DocumentObject *owner, const char *subname, const std::vector< std::string > &elements) const override
void extensionDropObject (App::DocumentObject *) override
void dropObject (App::DocumentObject *docObj)
const ViewProviderPage * getViewProviderPage () const
const char * whoAmI () const
Public Member Functions inherited from Gui::ViewProviderExtension
ViewProviderExtension ()
~ViewProviderExtension () override
Gui::ViewProviderDocumentObject * getExtendedViewProvider ()
const Gui::ViewProviderDocumentObject * getExtendedViewProvider () const
virtual std::vector< App::DocumentObject * > extensionClaimChildren3D () const
virtual bool extensionOnDelete (const std::vector< std::string > &)
virtual void extensionBeforeDelete ()
virtual std::vector< App::DocumentObject * > extensionClaimChildren () const
virtual bool extensionCanDragAndDropObject (App::DocumentObject *) const
virtual std::string extensionDropObjectEx (App::DocumentObject *obj, App::DocumentObject *, const char *, const std::vector< std::string > &)
virtual int extensionReplaceObject (App::DocumentObject *, App::DocumentObject *)
virtual void extensionHide ()
Hides the view provider.
virtual void extensionShow ()
Shows the view provider.
virtual void extensionModeSwitchChange ()
virtual SoSeparator * extensionGetFrontRoot () const
virtual SoGroup * extensionGetChildRoot () const
virtual SoSeparator * extensionGetBackRoot () const
virtual void extensionAttach (App::DocumentObject *)
virtual void extensionReattach (App::DocumentObject *)
virtual void extensionSetDisplayMode (const char *)
virtual std::vector< std::string > extensionGetDisplayModes () const
virtual void extensionSetupContextMenu (QMenu *, QObject *, const char *)
virtual void extensionUpdateData (const App::Property *)
PyObject * getExtensionPyObject () override
void setIgnoreOverlayIcon (bool on)
bool ignoreOverlayIcon () const
virtual QIcon extensionMergeGreyableOverlayIcons (const QIcon &orig) const
virtual QIcon extensionMergeColorfullOverlayIcons (const QIcon &orig) const
virtual void extensionStartRestoring ()
virtual void extensionFinishRestoring ()
virtual bool extensionGetElementPicked (const SoPickedPoint *, std::string &) const
virtual bool extensionGetDetailPath (const char *, SoFullPath *, SoDetail *&) const
Public Member Functions inherited from App::Extension
virtual Base::Type getExtensionTypeId (void) const
Extension ()=default
virtual ~Extension ()
virtual void initExtension (App::ExtensionContainer *obj)
App::ExtensionContainer * getExtendedContainer ()
const App::ExtensionContainer * getExtendedContainer () const
std::string name () const
bool isPythonExtension ()
virtual Property * extensionGetPropertyByName (const char *name) const
find a property by its name
virtual const char * extensionGetPropertyName (const Property *prop) const
get the name of a property
virtual void extensionGetPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual void extensionGetPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual short extensionGetPropertyType (const Property *prop) const
get the Type of a Property
virtual short extensionGetPropertyType (const char *name) const
get the Type of a named Property
virtual const char * extensionGetPropertyGroup (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * extensionGetPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual void extensionSave (Base::Writer &) const
virtual void extensionRestore (Base::XMLReader &)
bool extensionIsDerivedFrom (const Base::Type type) const
Public Attributes
App::PropertyBool ShowFrames
App::PropertyBool ShowGrid
App::PropertyDistance GridSpacing
Connection connectGuiRepaint
Public Attributes inherited from Gui::ViewProviderDocumentObject
App::PropertyEnumeration DisplayMode
App::PropertyBool Visibility
App::PropertyBool ShowInTree
App::PropertyEnumeration OnTopWhenSelected
App::PropertyEnumeration SelectionStyle
Public Attributes inherited from Gui::ViewProvider
boost::signals2::signal< void()> signalChangeIcon
signal on icon change
boost::signals2::signal< void(const QString &)> signalChangeToolTip
signal on tooltip change
boost::signals2::signal< void(const QString &)> signalChangeStatusTip
signal on status tip change
boost::signals2::signal< void(bool, Gui::HighlightMode)> signalChangeHighlight
signal on highlight change
Protected Member Functions
bool setEdit (int ModNum) override
is called by the document when the provider goes in edit mode
void createMDIViewPage ()
Protected Member Functions inherited from Gui::ViewProviderDocumentObject
Gui::MDIView * getActiveView () const
Gui::MDIView * getEditingView () const
Gui::MDIView * getInventorView () const
Gui::MDIView * getViewOfNode (SoNode *node) const
void onBeforeChange (const App::Property *prop) override
get called before the value is changed
SoNode * findFrontRootOfType (const SoType &type) const
bool isAttachedToDocument () const override
const char * detachFromDocument () override
void onPropertyStatusChanged (const App::Property &prop, unsigned long oldStatus) override
get called when a property status has changed
void setModeSwitch () override
Turn on mode switch.
void addDefaultAction (QMenu *, const QString &)
Protected Member Functions inherited from Gui::ViewProvider
virtual QIcon mergeGreyableOverlayIcons (const QIcon &orig) const
int getEditingMode () const
return the edit mode or -1 if nothing is being edited
bool checkRecursion (SoNode *)
SoPickedPoint * getPointOnRay (const SbVec2s &pos, const View3DInventorViewer *viewer) const
SoPickedPoint * getPointOnRay (const SbVec3f &pos, const SbVec3f &dir, const View3DInventorViewer *viewer) const
Protected Member Functions inherited from App::TransactionalObject
void onBeforeChangeProperty (Document *doc, const Property *prop)
Protected Member Functions inherited from App::PropertyContainer
virtual void onEarlyChange (const Property *)
virtual const PropertyData & getPropertyData () const
Protected Member Functions inherited from App::Extension
virtual const App::PropertyData & extensionGetPropertyData (void) const
virtual void extensionOnChanged (const Property *p)
virtual bool extensionHandleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
returns true if the property name change was handled by the extension.
virtual bool extensionHandleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop)
returns true if the property type change was handled by the extension.
void initExtensionType (Base::Type type)
Additional Inherited Members
Static Public Member Functions inherited from Gui::ViewProvider
static const std::string & hiddenMarker ()
static const char * hasHiddenMarker (const char *subname)
static SbMatrix convert (const Base::Matrix4D &rcMatrix)
static Base::Matrix4D convert (const SbMatrix &sbMat)
static void eventCallback (void *ud, SoEventCallback *node)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Public Member Functions inherited from App::Extension
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Static Protected Member Functions inherited from App::Extension
static const App::PropertyData * extensionGetPropertyDataPtr (void)
static void initExtensionSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Base::Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Gui::ViewProviderDocumentObject
App::DocumentObject * pcObject {nullptr}
Gui::Document * pcDocument {nullptr}
Protected Attributes inherited from Gui::ViewProvider
SoSeparator * pcRoot
The root Separator of the ViewProvider.
SoTransform * pcTransform
this is transformation for the provider
const char * sPixmap
SoSwitch * pcModeSwitch
this is the mode switch, all the different viewing modes are collected here
SoSeparator * pcAnnotation {nullptr}
The root separator for annotations.
ViewProviderPy * pyViewObject {nullptr}
std::string overrideMode
std::bitset< 32 > StatusBits
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Protected Attributes inherited from App::Extension
bool m_isPythonExtension = false
Py::SmartPtr ExtensionPythonObject
Detailed Description
Definition at line 53 of file TechDraw/Gui/ViewProviderPage.h.
Member Typedef Documentation
Connection
using TechDrawGui::ViewProviderPage::Connection = boost::signals2::scoped_connection
Definition at line 103 of file TechDraw/Gui/ViewProviderPage.h.
Constructor & Destructor Documentation
ViewProviderPage()
ViewProviderPage::ViewProviderPage ()
constructor
Definition at line 80 of file TechDraw/Gui/ViewProviderPage.cpp.
References ADD_PROPERTY_TYPE, TechDrawGui::PreferencesGui::gridSpacing(), toolbit-attributes::group, App::Property::Hidden, App::Prop_None, and TechDrawGui::PreferencesGui::showGrid().
~ViewProviderPage()
ViewProviderPage::~ViewProviderPage () override
destructor
Definition at line 108 of file TechDraw/Gui/ViewProviderPage.cpp.
Member Function Documentation
attach()
void ViewProviderPage::attach (App::DocumentObject * pcFeat) override virtual
Reimplemented from Gui::ViewProviderDocumentObject.
Definition at line 114 of file TechDraw/Gui/ViewProviderPage.cpp.
References draftgeoutils.faces::bind(), App::DocumentObject::getNameInDocument(), App::DocumentObject::isAttachedToDocument(), onGuiRepaint(), and TechDraw::DrawPage::signalGuiPaint.
canDelete()
bool ViewProviderPage::canDelete (App::DocumentObject * obj) const override virtual
Asks the view provider if the given object can be deleted.
Reimplemented from Gui::ViewProviderDocumentObject.
Definition at line 466 of file TechDraw/Gui/ViewProviderPage.cpp.
canDragObject()
bool ViewProviderPage::canDragObject (App::DocumentObject * obj) const override virtual
Check whether the object can be removed from the view provider by drag and drop
Reimplemented from Gui::ViewProvider.
Definition at line 481 of file TechDraw/Gui/ViewProviderPage.cpp.
canDragObjects()
bool ViewProviderPage::canDragObjects () const override virtual
Check whether children can be removed from the view provider by drag and drop
Reimplemented from Gui::ViewProvider.
Definition at line 476 of file TechDraw/Gui/ViewProviderPage.cpp.
canDropObject()
bool ViewProviderPage::canDropObject (App::DocumentObject * obj) const override virtual
Check whether the object can be dropped to the view provider by drag and drop or drop only
Reimplemented from Gui::ViewProvider.
Definition at line 493 of file TechDraw/Gui/ViewProviderPage.cpp.
canDropObjectEx()
bool ViewProviderPage::canDropObjectEx (App::DocumentObject * obj, App::DocumentObject * owner, const char * subname, const std::vector< std::string > & elements) const override virtual
Query object dropping with full qualified name
Tree view now calls this function instead of canDropObject(), and may query for objects from other document. The default implementation (actually in ViewProviderDocumentObject) inhibites cross document dropping, and calls canDropObject(obj) for the rest. Override this function to enable cross document linking.
Parameters
obj the object being dropped
owner the (grand)parent object of the dropping object. Maybe null. This may not be the top parent object, as tree view will try to find a parent of the dropping object relative to this object to avoid cyclic dependency
subname subname reference to the dropping object
elements non-object sub-elements, e.g. Faces, Edges, selected when the object is being dropped
Returns
Return whether the dropping action is allowed.
Reimplemented from Gui::ViewProviderDocumentObject.
Definition at line 486 of file TechDraw/Gui/ViewProviderPage.cpp.
claimChildren()
std::vector< App::DocumentObject * > ViewProviderPage::claimChildren () const override virtual
Claim all the views for the page.
Reimplemented from Gui::ViewProvider.
Definition at line 388 of file TechDraw/Gui/ViewProviderPage.cpp.
References Base::BaseClass::isDerivedFrom().
constDropObject()
void TechDrawGui::ViewProviderPage::constDropObject (App::DocumentObject * docObj) const
createMDIViewPage()
void ViewProviderPage::createMDIViewPage () protected
Definition at line 317 of file TechDraw/Gui/ViewProviderPage.cpp.
References Gui::MainWindow::addWindow(), Gui::BitmapFactory(), toolbit-attributes::doc, Gui::Application::getDocument(), Gui::getMainWindow(), and Gui::Application::Instance.
doubleClicked()
bool ViewProviderPage::doubleClicked () override virtual
Is called by the tree if the user double click on the object.
Reimplemented from Gui::ViewProvider.
Definition at line 266 of file TechDraw/Gui/ViewProviderPage.cpp.
References assureWorkbench, and bimcommands.BimViews::show().
dropObject()
void ViewProviderPage::dropObject (App::DocumentObject * obj) override virtual
Add an object to the view provider by drag and drop
Reimplemented from Gui::ViewProvider.
Definition at line 498 of file TechDraw/Gui/ViewProviderPage.cpp.
fixSceneDependencies()
void ViewProviderPage::fixSceneDependencies ()
Definition at line 561 of file TechDraw/Gui/ViewProviderPage.cpp.
References toolbit-attributes::doc, TechDrawGui::ViewProviderViewPart::fixSceneDependencies(), Base::Persistence::getClassTypeId(), Gui::Application::getViewProvider(), and Gui::Application::Instance.
getDrawPage()
TechDraw::DrawPage * ViewProviderPage::getDrawPage () const
Definition at line 514 of file TechDraw/Gui/ViewProviderPage.cpp.
Referenced by TechDrawGui::QGSPage::addChildrenToPage(), TechDrawGui::QGVPage::drawBackground(), TechDrawGui::ViewProviderPageExtension::dropObject(), TechDrawGui::QGSPage::fixOrphans(), TechDrawGui::QGVPage::getDrawPage(), TechDrawGui::QGSPage::getDrawPage(), TechDrawGui::PagePrinter::getPaperAttributes(), TechDrawGui::QGSPage::getTemplateCenter(), TechDrawGui::QGSPage::matchSceneRectToTemplate(), TechDrawGui::PagePrinter::print(), TechDrawGui::PagePrinter::printPdf(), TechDrawGui::QGVPage::QGVPage(), TechDrawGui::PagePrinter::saveDXF(), TechDrawGui::QGSPage::saveSvg(), and TechDrawGui::QGSPage::updateTemplate().
getFrameState()
bool ViewProviderPage::getFrameState ()
Definition at line 437 of file TechDraw/Gui/ViewProviderPage.cpp.
Referenced by TechDrawGui::QGIView::getFrameState(), TechDrawGui::PagePrinter::renderPage(), and TechDrawGui::QGSPage::saveSvg().
getMDIView()
Gui::MDIView * ViewProviderPage::getMDIView () const override virtual
Reimplemented from Gui::ViewProvider.
Definition at line 523 of file TechDraw/Gui/ViewProviderPage.cpp.
getMDIViewPage()
MDIViewPage * ViewProviderPage::getMDIViewPage () const
Definition at line 361 of file TechDraw/Gui/ViewProviderPage.cpp.
Referenced by TechDrawGui::TaskCosVertex::accept(), TechDrawGui::TaskLeaderLine::accept(), TechDrawGui::ViewProviderTemplate::getMDIViewPage(), TechDrawGui::ViewProviderDrawingView::getMDIViewPage(), TechDrawGui::QGIView::getMDIViewPage(), TechDrawGui::TaskCosVertex::onTrackerClicked(), TechDrawGui::TaskLeaderLine::onTrackerClicked(), TechDrawGui::TaskCosVertex::onTrackerFinished(), TechDrawGui::TaskCosVertex::reject(), TechDrawGui::TaskLeaderLine::reject(), TechDrawGui::TaskLeaderLine::setUiEdit(), TechDrawGui::TaskLeaderLine::setUiPrimary(), and TechDrawGui::TaskLeaderLine::TaskLeaderLine().
getQGSPage()
QGSPage* TechDrawGui::ViewProviderPage::getQGSPage (void) const inline
Definition at line 123 of file TechDraw/Gui/ViewProviderPage.h.
Referenced by TechDrawGui::QGVPage::centerOnPage(), TechDrawGui::TaskDetail::editByHighlight(), TechDrawGui::DrawGuiUtil::findPage(), TechDrawGui::ViewProviderTemplate::getQTemplate(), TechDrawGui::ViewProviderDrawingView::getQView(), TechDrawGui::TaskLeaderLine::onTrackerClicked(), TechDrawGui::PagePrinter::print(), TechDrawGui::PagePrinter::printAllPdf(), TechDrawGui::PagePrinter::printPdf(), TechDrawGui::TaskCosVertex::removeTracker(), TechDrawGui::TaskLeaderLine::removeTracker(), TechDrawGui::PagePrinter::renderPage(), TechDrawGui::PagePrinter::saveSVG(), TechDrawGui::TaskCosVertex::setEditCursor(), TechDrawGui::TaskLeaderLine::setEditCursor(), TechDrawGui::TaskCosVertex::startTracker(), TechDrawGui::TaskLeaderLine::startTracker(), TechDrawGui::TaskDetail::TaskDetail(), TechDrawGui::TaskLeaderLine::TaskLeaderLine(), TechDrawGui::TaskRichAnno::TaskRichAnno(), and TechDrawGui::ViewProviderTemplate::updateData().
getQGVPage()
QGVPage* TechDrawGui::ViewProviderPage::getQGVPage (void) const inline
Definition at line 124 of file TechDraw/Gui/ViewProviderPage.h.
Referenced by activateHandler().
getQTemplate()
QGITemplate * ViewProviderPage::getQTemplate (void) const
Definition at line 375 of file TechDraw/Gui/ViewProviderPage.cpp.
References Gui::Application::getDocument(), TechDrawGui::ViewProviderTemplate::getQTemplate(), Gui::Document::getViewProvider(), and Gui::Application::Instance.
getTemplate()
DrawTemplate * ViewProviderPage::getTemplate () const
Definition at line 369 of file TechDraw/Gui/ViewProviderPage.cpp.
getVPPExtension()
ViewProviderPageExtension * ViewProviderPage::getVPPExtension () const
Definition at line 551 of file TechDraw/Gui/ViewProviderPage.cpp.
Referenced by TechDrawGui::ViewProviderDrawingViewExtension::extensionCanDropObject(), and TechDrawGui::ViewProviderDrawingViewExtension::extensionDropObject().
hide()
void ViewProviderPage::hide () override virtual
Hides the view provider.
Reimplemented from Gui::ViewProviderDocumentObject.
Definition at line 282 of file TechDraw/Gui/ViewProviderPage.cpp.
References ArchFence::hide().
isShow()
bool ViewProviderPage::isShow () const override virtual
checks whether the view provider is visible or not
Reimplemented from Gui::ViewProvider.
Definition at line 435 of file TechDraw/Gui/ViewProviderPage.cpp.
onChanged()
void ViewProviderPage::onChanged (const App::Property * prop) override virtual
Gets called by the container whenever a property has been changed.
Reimplemented from Gui::ViewProviderDocumentObject.
Definition at line 133 of file TechDraw/Gui/ViewProviderPage.cpp.
References Gui::ViewProviderDocumentObject::onChanged().
onDelete()
bool ViewProviderPage::onDelete (const std::vector< std::string > & subNames) override virtual
Get called if the object is about to get deleted. Here you can delete other objects, switch their visibility or prevent the deletion of the object.
Parameters
subNames list of selected subelements
Returns
true if the deletion is approved by the view provider.
Reimplemented from Gui::ViewProvider.
Definition at line 185 of file TechDraw/Gui/ViewProviderPage.cpp.
References Gui::getMainWindow(), replaceobj::objs, and Path.Log::warning().
onGuiRepaint()
void ViewProviderPage::onGuiRepaint (const TechDraw::DrawPage * dp)
Redo the whole visual page.
Definition at line 504 of file TechDraw/Gui/ViewProviderPage.cpp.
Referenced by attach().
redrawPage()
void ViewProviderPage::redrawPage () const
convenient way to ask feature to redraw everything
Definition at line 581 of file TechDraw/Gui/ViewProviderPage.cpp.
removeMDIView()
void ViewProviderPage::removeMDIView ()
Definition at line 344 of file TechDraw/Gui/ViewProviderPage.cpp.
References Gui::MainWindow::activeWindow(), Gui::getMainWindow(), Gui::MainWindow::removeWindow(), and Gui::MainWindow::windows().
setEdit()
bool ViewProviderPage::setEdit (int ModNum) override protected virtual
is called by the document when the provider goes in edit mode
Reimplemented from Gui::ViewProvider.
Definition at line 241 of file TechDraw/Gui/ViewProviderPage.cpp.
References _SHOWDRAWING, _TOGGLEUPDATE, and Gui::ViewProvider::setEdit().
setFrameState()
void ViewProviderPage::setFrameState (bool state)
Definition at line 439 of file TechDraw/Gui/ViewProviderPage.cpp.
Referenced by TechDrawGui::PagePrinter::renderPage(), and TechDrawGui::QGSPage::saveSvg().
setGrid()
void ViewProviderPage::setGrid ()
Definition at line 525 of file TechDraw/Gui/ViewProviderPage.cpp.
References TechDraw::DrawPage::getPageHeight(), TechDraw::DrawPage::getPageWidth(), TechDrawGui::QGVPage::makeGrid(), TechDrawGui::QGVPage::showGrid(), and TechDrawGui::QGVPage::updateViewport().
setTemplateMarkers()
void ViewProviderPage::setTemplateMarkers (bool state)
Definition at line 450 of file TechDraw/Gui/ViewProviderPage.cpp.
References App::DocumentObject::getDocument(), Gui::Application::getDocument(), Gui::Document::getViewProvider(), Gui::Application::Instance, TechDrawGui::ViewProviderTemplate::setMarkers(), and InitGui::t.
Referenced by TechDrawGui::PagePrinter::renderPage(), and TechDrawGui::QGSPage::saveSvg().
setupContextMenu()
void ViewProviderPage::setupContextMenu (QMenu * menu, QObject * receiver, const char * method) override virtual
set up the context-menu with the supported edit modes
Reimplemented from Gui::ViewProvider.
Definition at line 232 of file TechDraw/Gui/ViewProviderPage.cpp.
References _SHOWDRAWING, _TOGGLEUPDATE, NavigationIndicatorGui::menu, and Gui::ViewProvider::setupContextMenu().
show()
void ViewProviderPage::show () override virtual
Shows the view provider.
Reimplemented from Gui::ViewProviderDocumentObject.
Definition at line 276 of file TechDraw/Gui/ViewProviderPage.cpp.
References bimcommands.BimViews::show().
showMDIViewPage()
bool ViewProviderPage::showMDIViewPage ()
Definition at line 291 of file TechDraw/Gui/ViewProviderPage.cpp.
switchToMdiViewPage()
void ViewProviderPage::switchToMdiViewPage ()
Definition at line 337 of file TechDraw/Gui/ViewProviderPage.cpp.
References bimcommands.BimViews::show().
toggleFrameState()
void ViewProviderPage::toggleFrameState ()
Definition at line 441 of file TechDraw/Gui/ViewProviderPage.cpp.
unsetEdit()
void ViewProviderPage::unsetEdit (int ModNum) override virtual
is called when you lose the edit mode
Reimplemented from Gui::ViewProvider.
Definition at line 260 of file TechDraw/Gui/ViewProviderPage.cpp.
updateData()
void ViewProviderPage::updateData (const App::Property * prop) override virtual
Reimplemented from Gui::ViewProvider.
Definition at line 148 of file TechDraw/Gui/ViewProviderPage.cpp.
References Gui::ViewProvider::updateData().
useNewSelectionModel()
bool TechDrawGui::ViewProviderPage::useNewSelectionModel () const inline override virtual
indicates if the ViewProvider use the new Selection model
Reimplemented from Gui::ViewProvider.
Definition at line 80 of file TechDraw/Gui/ViewProviderPage.h.
whoAmI()
const char * ViewProviderPage::whoAmI () const
Definition at line 558 of file TechDraw/Gui/ViewProviderPage.cpp.
Member Data Documentation
connectGuiRepaint
Connection TechDrawGui::ViewProviderPage::connectGuiRepaint
Definition at line 104 of file TechDraw/Gui/ViewProviderPage.h.
GridSpacing
App::PropertyDistance TechDrawGui::ViewProviderPage::GridSpacing
Definition at line 66 of file TechDraw/Gui/ViewProviderPage.h.
ShowFrames
App::PropertyBool TechDrawGui::ViewProviderPage::ShowFrames
Definition at line 64 of file TechDraw/Gui/ViewProviderPage.h.
ShowGrid
App::PropertyBool TechDrawGui::ViewProviderPage::ShowGrid
Definition at line 65 of file TechDraw/Gui/ViewProviderPage.h.
The documentation for this class was generated from the following files:
TechDraw/Gui/ViewProviderPage.h
TechDraw/Gui/ViewProviderPage.cpp