FreeCAD: Gui::ViewProviderSuppressibleExtension Class Reference
Gui::ViewProviderSuppressibleExtension Class Reference
#include <ViewProviderSuppressibleExtension.h>
Public Member Functions
ViewProviderSuppressibleExtension ()
~ViewProviderSuppressibleExtension () override
void extensionUpdateData (const App::Property *prop) override
void setSuppressedIcon (bool onoff)
QIcon extensionMergeColorfullOverlayIcons (const QIcon &orig) const override
void extensionSetupContextMenu (QMenu *menu, QObject *, const char *) override
Public Member Functions inherited from Gui::ViewProviderExtension
ViewProviderExtension ()
~ViewProviderExtension () override
Gui::ViewProviderDocumentObject * getExtendedViewProvider ()
const Gui::ViewProviderDocumentObject * getExtendedViewProvider () const
virtual std::vector< App::DocumentObject * > extensionClaimChildren3D () const
virtual bool extensionOnDelete (const std::vector< std::string > &)
virtual void extensionBeforeDelete ()
virtual std::vector< App::DocumentObject * > extensionClaimChildren () const
virtual bool extensionCanDragObjects () const
virtual bool extensionCanDragObject (App::DocumentObject *) const
virtual void extensionDragObject (App::DocumentObject *)
virtual bool extensionCanDropObjects () const
virtual bool extensionCanDropObject (App::DocumentObject *) const
virtual bool extensionCanDragAndDropObject (App::DocumentObject *) const
virtual void extensionDropObject (App::DocumentObject *)
virtual bool extensionCanDropObjectEx (App::DocumentObject *, App::DocumentObject *, const char *, const std::vector< std::string > &) const
virtual std::string extensionDropObjectEx (App::DocumentObject *obj, App::DocumentObject *, const char *, const std::vector< std::string > &)
virtual int extensionReplaceObject (App::DocumentObject *, App::DocumentObject *)
virtual void extensionHide ()
Hides the view provider.
virtual void extensionShow ()
Shows the view provider.
virtual void extensionModeSwitchChange ()
virtual SoSeparator * extensionGetFrontRoot () const
virtual SoGroup * extensionGetChildRoot () const
virtual SoSeparator * extensionGetBackRoot () const
virtual void extensionAttach (App::DocumentObject *)
virtual void extensionReattach (App::DocumentObject *)
virtual void extensionSetDisplayMode (const char *)
virtual std::vector< std::string > extensionGetDisplayModes () const
PyObject * getExtensionPyObject () override
void setIgnoreOverlayIcon (bool on)
bool ignoreOverlayIcon () const
virtual QIcon extensionMergeGreyableOverlayIcons (const QIcon &orig) const
virtual void extensionStartRestoring ()
virtual void extensionFinishRestoring ()
virtual bool extensionGetElementPicked (const SoPickedPoint *, std::string &) const
virtual bool extensionGetDetailPath (const char *, SoFullPath *, SoDetail *&) const
Public Member Functions inherited from App::Extension
virtual Base::Type getExtensionTypeId (void) const
Extension ()=default
virtual ~Extension ()
virtual void initExtension (App::ExtensionContainer *obj)
App::ExtensionContainer * getExtendedContainer ()
const App::ExtensionContainer * getExtendedContainer () const
std::string name () const
bool isPythonExtension ()
virtual Property * extensionGetPropertyByName (const char *name) const
find a property by its name
virtual const char * extensionGetPropertyName (const Property *prop) const
get the name of a property
virtual void extensionGetPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual void extensionGetPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual short extensionGetPropertyType (const Property *prop) const
get the Type of a Property
virtual short extensionGetPropertyType (const char *name) const
get the Type of a named Property
virtual const char * extensionGetPropertyGroup (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * extensionGetPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual void extensionSave (Base::Writer &) const
virtual void extensionRestore (Base::XMLReader &)
bool extensionIsDerivedFrom (const Base::Type type) const
Additional Inherited Members
Static Public Member Functions inherited from App::Extension
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Protected Member Functions inherited from App::Extension
virtual const App::PropertyData & extensionGetPropertyData (void) const
virtual void extensionOnChanged (const Property *p)
virtual bool extensionHandleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
returns true if the property name change was handled by the extension.
virtual bool extensionHandleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop)
returns true if the property type change was handled by the extension.
void initExtensionType (Base::Type type)
Static Protected Member Functions inherited from App::Extension
static const App::PropertyData * extensionGetPropertyDataPtr (void)
static void initExtensionSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Base::Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Extension
bool m_isPythonExtension = false
Py::SmartPtr ExtensionPythonObject
Detailed Description
Definition at line 52 of file ViewProviderSuppressibleExtension.h.
Constructor & Destructor Documentation
ViewProviderSuppressibleExtension()
ViewProviderSuppressibleExtension::ViewProviderSuppressibleExtension ()
Definition at line 45 of file ViewProviderSuppressibleExtension.cpp.
References App::Extension::getExtensionClassTypeId().
~ViewProviderSuppressibleExtension()
ViewProviderSuppressibleExtension::~ViewProviderSuppressibleExtension () override default
Member Function Documentation
extensionMergeColorfullOverlayIcons()
QIcon ViewProviderSuppressibleExtension::extensionMergeColorfullOverlayIcons (const QIcon & orig) const override virtual
Reimplemented from Gui::ViewProviderExtension.
Definition at line 75 of file ViewProviderSuppressibleExtension.cpp.
References Gui::BitmapFactory(), Gui::ViewProviderExtension::extensionMergeColorfullOverlayIcons(), Gui::BitmapFactoryInst::mergePixmap(), and Gui::BitmapFactoryInst::TopLeft.
extensionSetupContextMenu()
void ViewProviderSuppressibleExtension::extensionSetupContextMenu (QMenu * menu, QObject * , const char *) override virtual
Reimplemented from Gui::ViewProviderExtension.
Definition at line 88 of file ViewProviderSuppressibleExtension.cpp.
References Gui::ViewProviderExtension::getExtendedViewProvider(), App::Property::Hidden, NavigationIndicatorGui::menu, and Gui::ActionFunction::trigger().
extensionUpdateData()
void ViewProviderSuppressibleExtension::extensionUpdateData (const App::Property * prop) override virtual
Reimplemented from Gui::ViewProviderExtension.
Definition at line 52 of file ViewProviderSuppressibleExtension.cpp.
References create_qrc::ext, Gui::ViewProviderExtension::getExtendedViewProvider(), setSuppressedIcon(), Gui::ViewProvider::signalChangeHighlight, and Gui::StrikeOut.
setSuppressedIcon()
void ViewProviderSuppressibleExtension::setSuppressedIcon (bool onoff)
Definition at line 69 of file ViewProviderSuppressibleExtension.cpp.
References Gui::ViewProviderExtension::getExtendedViewProvider(), and Gui::ViewProvider::signalChangeIcon.
Referenced by extensionUpdateData().
The documentation for this class was generated from the following files:
ViewProviderSuppressibleExtension.h
ViewProviderSuppressibleExtension.cpp