FreeCAD: OpenSCADFeatures.GetWire Class Reference
OpenSCADFeatures.GetWire Class Reference
Public Member Functions
def __init__ (self, obj, child=None)
def onChanged (self, fp, prop)
def execute (self, fp)
Detailed Description
return the first wire from a given shape
Definition at line 310 of file OpenSCADFeatures.py.
Constructor & Destructor Documentation
__init__()
def OpenSCADFeatures.GetWire.__init__ (self, obj, child = None)
Definition at line 312 of file OpenSCADFeatures.py.
Member Function Documentation
execute()
def OpenSCADFeatures.GetWire.execute (self, fp)
Definition at line 322 of file OpenSCADFeatures.py.
Referenced by src.Mod.PartDesign.Scripts.Spring.MySpring.onChanged(), src.Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid.onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped.onChanged(), src.Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt.onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder.onChanged(), and FeaturePython.DistanceBolt.onChanged().
onChanged()
def OpenSCADFeatures.GetWire.onChanged (self, fp, prop)
Definition at line 318 of file OpenSCADFeatures.py.
The documentation for this class was generated from the following file:
OpenSCADFeatures.py