FreeCAD: Gui::Application Class Reference
Gui::Application Class Reference
#include <Application.h>
Public Types
enum Status { UserInitiatedOpenDocument = 0 }
Public Member Functions
Application (bool GUIenabled)
construction
~Application ()
destruction
methods for View handling
bool sendMsgToActiveView (const char *pMsg, const char **ppReturn=nullptr)
send Messages to the active view
bool sendHasMsgToActiveView (const char *pMsg)
send Messages test to the active view
bool sendMsgToFocusView (const char *pMsg, const char **ppReturn=nullptr)
send Messages to the focused view
bool sendHasMsgToFocusView (const char *pMsg)
send Messages test to the focused view
void attachView (Gui::BaseView *pcView)
Attach a view (get called by the FCView constructor)
void detachView (Gui::BaseView *pcView)
Detach a view (get called by the FCView destructor)
void viewActivated (Gui::MDIView *pcView)
get called if a view gets activated, this manage the whole activation scheme
void viewClosed (Gui::MDIView *pcView)
get called if a view gets closed
void onUpdate ()
call update to all documents and all views (costly!)
void updateActive ()
call update to all views of the active document
void updateActions (bool delay=false)
call update to all command actions
workbench handling
bool activateWorkbench (const char *name)
Activate a named workbench.
QPixmap workbenchIcon (const QString &) const
QString workbenchToolTip (const QString &) const
QString workbenchMenuText (const QString &) const
QStringList workbenches () const
void setupContextMenu (const char *recipient, MenuItem *) const
Appearance
void setStyleSheet (const QString &qssFile, bool tiledBackground)
Activate a stylesheet.
QString replaceVariablesInQss (QString qssText)
User Commands
Gui::MacroManager * macroManager ()
Get macro manager.
Gui::CommandManager & commandManager ()
Reference to the command manager.
void createStandardOperations ()
helper which create the commands
Gui::PreferencePackManager * prefPackManager ()
Public Attributes
Signals of the Application
boost::signals2::signal< void(const Gui::Document &, bool)> signalNewDocument
signal on new Document
boost::signals2::signal< void(const Gui::Document &)> signalDeleteDocument
signal on deleted Document
boost::signals2::signal< void(const Gui::Document &)> signalRelabelDocument
signal on relabeling Document
boost::signals2::signal< void(const Gui::Document &)> signalRenameDocument
signal on renaming Document
boost::signals2::signal< void(const Gui::Document &)> signalActiveDocument
signal on activating Document
boost::signals2::signal< void(const Gui::ViewProvider &)> signalNewObject
signal on new Object
boost::signals2::signal< void(const Gui::ViewProvider &)> signalDeletedObject
signal on deleted Object
boost::signals2::signal< void(const Gui::ViewProvider &, const App::Property &)> signalBeforeChangeObject
signal on changed Object
boost::signals2::signal< void(const Gui::ViewProvider &, const App::Property &)> signalChangedObject
signal on changed object property
boost::signals2::signal< void(const Gui::ViewProvider &)> signalRelabelObject
signal on renamed Object
boost::signals2::signal< void(const Gui::ViewProvider &)> signalActivatedObject
signal on activated Object
boost::signals2::signal< void(const char *)> signalActivateWorkbench
signal on activated workbench
boost::signals2::signal< void()> signalRefreshWorkbenches
signal on added/removed workbench
boost::signals2::signal< void(const Gui::Document &)> signalShowHidden
signal on show hidden items
boost::signals2::signal< void(const Gui::MDIView *)> signalActivateView
signal on activating view
boost::signals2::signal< void(const Gui::MDIView *)> signalCloseView
signal on closing view
boost::signals2::signal< void(const Gui::ViewProviderDocumentObject &)> signalInEdit
signal on entering in edit mode
boost::signals2::signal< void(const Gui::ViewProviderDocumentObject &)> signalResetEdit
signal on leaving edit mode
boost::signals2::signal< void(int)> signalUserEditModeChanged
signal on changing user edit mode
methods for support of files
void open (const char *FileName, const char *Module)
open a file
void importFrom (const char *FileName, const char *DocName, const char *Module)
import a file into the document DocName
void exportTo (const char *FileName, const char *DocName, const char *Module)
Export objects from the document DocName to a single file.
App::Document * reopen (App::Document *doc)
Reload a partial opened document.
static void checkForRecomputes ()
Prompt about recomputing if needed.
methods for Document handling
void onLastWindowClosed (Gui::Document *pcDoc)
message when a GuiDocument is about to vanish
Gui::Document * activeDocument () const
Getter for the active document.
void setActiveDocument (Gui::Document *pcDocument)
Set the active document.
Gui::Document * editDocument () const
Getter for the editing document.
Gui::MDIView * editViewOfNode (SoNode *node) const
void setEditDocument (Gui::Document *pcDocument)
Set editing document, which will reset editing of all other document.
Gui::Document * getDocument (const char *name) const
Gui::Document * getDocument (const App::Document *pDoc) const
Gui::MDIView * activeView () const
Getter for the active view of the active document or null.
void activateView (const Base::Type &, bool create=false)
Activate a view of the given type of the active document.
void showViewProvider (const App::DocumentObject *)
Shows the associated view provider of the given object.
void hideViewProvider (const App::DocumentObject *)
Hides the associated view provider of the given object.
Gui::ViewProvider * getViewProvider (const App::DocumentObject *) const
Get the view provider of the given object.
bool isClosing ()
true when the application shutting down
void checkForDeprecatedSettings ()
void checkForPreviousCrashes ()
void slotNewDocument (const App::Document &, bool)
Observer message from the Application.
void slotDeleteDocument (const App::Document &)
void slotRelabelDocument (const App::Document &)
void slotRenameDocument (const App::Document &)
void slotActiveDocument (const App::Document &)
void slotShowHidden (const App::Document &)
void slotNewObject (const ViewProvider &)
void slotDeletedObject (const ViewProvider &)
void slotChangedObject (const ViewProvider &, const App::Property &Prop)
void slotRelabelObject (const ViewProvider &)
void slotActivatedObject (const ViewProvider &)
void slotInEdit (const Gui::ViewProviderDocumentObject &)
void slotResetEdit (const Gui::ViewProviderDocumentObject &)
Init, Destruct an Access methods
static Application * Instance = nullptr
some kind of singleton
void tryClose (QCloseEvent *e)
bool testStatus (Status pos) const
return the status bits
void setStatus (Status pos, bool on)
set the status bits
static void initApplication ()
static void initTypes ()
static void initOpenInventor ()
static void runInitGuiScript ()
static void runApplication ()
static bool hiddenMainWindow ()
whenever GUI is about to start with the main window hidden
User edit mode
const std::map< int, std::pair< std::string, std::string > > userEditModes
int userEditMode = userEditModes.begin()->first
class ApplicationPy
std::map< int, std::pair< std::string, std::string > > listUserEditModes () const
int getUserEditMode (const std::string &mode="") const
std::pair< std::string, std::string > getUserEditModeUIStrings (int mode=-1) const
bool setUserEditMode (int mode)
bool setUserEditMode (const std::string &mode)
Detailed Description
The Application main class This is the central class of the GUI
Author
Jrgen Riegel, Werner Mayer
Definition at line 58 of file Gui/Application.h.
Member Enumeration Documentation
Status
enum Gui::Application::Status
Enumerator
UserInitiatedOpenDocument
Definition at line 61 of file Gui/Application.h.
Constructor & Destructor Documentation
Application()
Application::Application (bool GUIenabled) explicit
construction
Definition at line 367 of file Gui/Application.cpp.
References Gui::Translator::activateLanguage(), Base::InterpreterSingleton::addType(), draftgeoutils.faces::bind(), App::Application::Config(), Path.Base.SetupSheet::dict, femtools.tokrules::False, Gui::FreeCADGui_methods, App::GetApplication(), ParameterGrp::GetASCII(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), Gui::TaskView::ControlPy::getInstance(), App::Application::GetParameterGroupByPath(), App::Application::GetUserParameter(), Gui::GetWidgetFactorySupplier(), Gui::PythonDebugModule::init_module(), Gui::ExpressionBindingPy::init_type(), Gui::View3DInventorPy::init_type(), Gui::PythonStdout::init_type(), Gui::MainWindowPy::init_type(), Gui::MDIViewPy::init_type(), Gui::View3DInventorViewerPy::init_type(), Gui::CommandActionPy::init_type(), Gui::PythonStderr::init_type(), Gui::SoQtOffscreenRendererPy::init_type(), Gui::SelectionFilterPy::init_type(), Gui::OutputStdout::init_type(), Gui::TaskView::ControlPy::init_type(), Gui::AbstractSplitViewPy::init_type(), Gui::TaskView::TaskDialogPy::init_type(), Gui::OutputStderr::init_type(), Gui::PythonStdin::init_type(), Gui::UiLoaderPy::init_type(), Gui::Dialog::TaskPlacementPy::init_type(), Gui::PyResource::init_type(), Gui::Translator::instance(), Instance, Base::Interpreter(), Gui::MacroCommand::load(), Gui::ApplicationPy::Methods, Gui::SelectionSingleton::Methods, src.Mod.PartDesign.fcgear.svggear::module, bimcommands::modules, PyDoc_STRVAR(), App::Application::signalActiveDocument, App::Application::signalDeleteDocument, App::Application::signalNewDocument, App::Application::signalRelabelDocument, App::Application::signalRenameDocument, App::Application::signalShowHidden, slotActiveDocument(), slotDeleteDocument(), slotNewDocument(), slotRelabelDocument(), slotRenameDocument(), and slotShowHidden().
~Application()
Application::~Application ()
destruction
Definition at line 582 of file Gui/Application.cpp.
References Base::Console(), Gui::BitmapFactoryInst::destruct(), Gui::Translator::destruct(), Gui::WorkbenchManager::destruct(), Gui::WidgetFactorySupplier::destruct(), Gui::SelectionSingleton::destruct(), SCL.SimpleDataTypes::e, Instance, Base::ConsoleSingleton::Log(), Gui::WorkbenchManipulator::removeAll(), and Gui::MacroCommand::save().
Member Function Documentation
activateView()
void Application::activateView (const Base::Type & type, bool create = false)
Activate a view of the given type of the active document.
Application::activateView Activates a view of the given type of the active document. If a view of this type doesn't exist and create is true a new view of this type will be created.
Parameters
type
create
Definition at line 1210 of file Gui/Application.cpp.
References importers.importIFClegacy::create(), toolbit-attributes::doc, Base::BaseClass::isDerivedFrom(), and Path.Post.scripts.grbl_post::type.
Referenced by Gui::ApplicationPy::sActivateView(), and Gui::ApplicationPy::sActiveView().
activateWorkbench()
bool Application::activateWorkbench (const char * name)
Activate a named workbench.
Activate the matching workbench to the registered workbench handler with name name. The handler must be an instance of a class written in Python. Normally, if a handler gets activated a workbench with the same name gets created unless it already exists.
The old workbench gets deactivated before. If the workbench to the handler is already active or if the switch fails false is returned.
Definition at line 1525 of file Gui/Application.cpp.
References Gui::Workbench::activated(), Gui::MainWindow::activateWorkbench(), Gui::WorkbenchManager::active(), toolbit-attributes::args, Base::Console(), Gui::WorkbenchManager::createWorkbench(), Gui::Workbench::deactivated(), SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), Base::Type::fromName(), App::GetApplication(), Base::BaseClass::getClassTypeId(), Gui::getMainWindow(), App::Application::GetParameterGroupByPath(), Gui::Workbench::getPyObject(), Gui::WorkbenchManager::getWorkbench(), buildPsets::handler, Gui::WorkbenchManager::instance(), Instance, Base::Type::isDerivedFrom(), Base::ConsoleSingleton::Log(), Path.Op.Surface::msg, Gui::Workbench::name(), src.Mod.AddonManager.addonmanager_devmode_license_selector::QRegularExpression, Gui::WaitCursor::restoreCursor(), result, ParameterGrp::SetASCII(), Gui::WaitCursor::setWaitCursor(), src.Mod.Test.testmakeWireString::String, and Path.Post.scripts.grbl_post::type.
Referenced by StartGui::StartView::newArchFile(), StartGui::StartView::newAssemblyFile(), StartGui::StartView::newDraftFile(), StartGui::StartView::newPartDesignFile(), Gui::Dialog::wbListItem::onLoadClicked(), StartGui::StartView::postStart(), and Gui::ApplicationPy::sActivateWorkbenchHandler().
activeDocument()
Gui::Document * Application::activeDocument () const
Getter for the active document.
Getter for the active view.
Definition at line 1229 of file Gui/Application.cpp.
Referenced by InspectionGui::VisualInspection::accept(), DrawingGui::TaskProjection::accept(), Gui::Dialog::DlgMacroExecuteImp::accept(), TechDrawGui::TaskProjection::accept(), RobotGui::TaskDlgTrajectoryCompound::accept(), RobotGui::TaskDlgEdge2Trac::accept(), RobotGui::TaskDlgTrajectoryDressUp::accept(), StdCmdGroup::activated(), SketcherGui::Workbench::activated(), StdCmdVarSet::activated(), Gui::MacroCommand::activated(), StdViewDockUndockFullscreen::activated(), Gui::RecentMacrosAction::activateFile(), Gui::SelectionSingleton::addSelection(), Gui::Command::adjustCameraPosition(), Gui::Dialog::PlacementHandler::applyPlacement(), StartGui::StartView::changeEvent(), MeshGui::ViewProviderMesh::clipMeshCallback(), Gui::Dialog::TransformStrategy::commitTransform(), SketcherGui::ConstraintView::contextMenuEvent(), ReverseEngineeringGui::SegmentationManual::createSegment(), PartGui::CrossSections::CrossSections(), MeshPartGui::CrossSections::CrossSections(), Gui::MainWindow::customEvent(), PointsGui::ViewProviderScattered::cut(), PointsGui::ViewProviderStructured::cut(), Gui::DocumentIndex::data(), MeshGui::RemoveComponents::deleteSelection(), Gui::Dialog::DlgSettingsGeneral::DlgSettingsGeneral(), PartDesignGui::ViewProviderDatum::doubleClicked(), Gui::ViewProviderDragger::doubleClicked(), Gui::ViewProviderMaterialObject::doubleClicked(), FemGui::ViewProviderFemPostObject::doubleClicked(), FemGui::ViewProviderFemPostFunction::doubleClicked(), SketcherGui::ViewProviderSketch::doubleClicked(), SketcherGui::DrawSketchKeyboardManager::DrawSketchKeyboardManager(), Gui::MainWindow::event(), Gui::ViewProvider::eventCallback(), PartDesignGui::TaskBooleanParameters::exitSelectionMode(), MeshGui::ViewProviderMesh::fillHole(), ReverseEngineeringGui::SegmentationManual::Private::findGeometry(), TechDrawGui::DrawGuiUtil::get3DDirAndRot(), Gui::Command::getActiveGuiDocument(), Gui::DocumentT::getAppDocumentPython(), Gui::ViewProvider::getBoundingBox(), Gui::Command::getDocument(), Gui::DocumentT::getGuiDocumentPython(), SketcherGui::getInactiveHandlerEditModeSketchViewProvider(), Gui::ViewProviderT::getObjectPython(), getSketchObject(), MeshGui::MeshSelection::getViewer(), FemGui::ViewProviderFemPostObject::hide(), StdCmdDrawStyle::isActive(), PartDesignGui::ViewProviderBody::isActiveBody(), Gui::Command::isActiveObjectValid(), Gui::ViewProviderPart::isActivePart(), Gui::Command::isViewOfType(), MeshGui::ViewProviderMesh::markPartCallback(), PartGui::SectionCut::onRefreshCutPBclicked(), Gui::TaskCSysDragger::open(), StartGui::StartView::openExistingFile(), MeshGui::ViewProviderMesh::partMeshCallback(), Gui::Dialog::DlgSettingsGeneral::recreatePreferencePackMenu(), RobotGui::TaskDlgTrajectoryCompound::reject(), RobotGui::TaskDlgTrajectoryDressUp::reject(), PartDesignGui::TaskDlgBooleanParameters::reject(), TechDrawGui::TaskRichAnno::removeFeature(), TechDrawGui::TaskLeaderLine::removeFeature(), Gui::SelectionSingleton::rmvPreselect(), Gui::SelectionSingleton::rmvSelectionGate(), Gui::ApplicationPy::sActiveDocument(), Gui::TreeWidget::scrollItemToTop(), PartGui::SectionCut::SectionCut(), MeshGui::ViewProviderMesh::segmMeshCallback(), SpreadsheetGui::WorkbenchHelper::setBackgroundColor(), SpreadsheetGui::WorkbenchHelper::setForegroundColor(), Gui::SelectionSingleton::setPreselect(), Gui::ApplicationPy::sHide(), Gui::ApplicationPy::sShow(), Gui::TreeWidget::startItemSearch(), RobotGui::TaskTrajectory::TaskTrajectory(), RobotGui::TrajectorySimulate::TrajectorySimulate(), and MeshGui::ViewProviderMesh::trimMeshCallback().
activeView()
Gui::MDIView * Application::activeView () const
Getter for the active view of the active document or null.
Definition at line 1192 of file Gui/Application.cpp.
Referenced by PartDesignGui::getActivePart(), PartGui::getAutoGroupCommandStr(), PartDesignGui::getBody(), Gui::ViewProvider::getBoundingBox(), PartDesignGui::makeBodyActive(), Gui::ApplicationPy::sActiveView(), PartDesignGui::setEdit(), PartDesignGui::Workbench::setupContextMenu(), and PartDesignGui::ViewProvider::unsetEdit().
attachView()
void Application::attachView (Gui::BaseView * pcView)
Attach a view (get called by the FCView constructor)
Definition at line 1375 of file Gui/Application.cpp.
Referenced by Gui::BaseView::BaseView().
checkForDeprecatedSettings()
void Application::checkForDeprecatedSettings ()
Definition at line 2481 of file Gui/Application.cpp.
References Base::Console(), App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), and Base::ConsoleSingleton::Warning().
checkForPreviousCrashes()
void Application::checkForPreviousCrashes ()
Definition at line 2502 of file Gui/Application.cpp.
References Gui::Dialog::ApplicationCache::applyUserSettings(), Gui::Dialog::DocumentRecoveryFinder::checkForPreviousCrashes(), Base::Console(), SCL.SimpleDataTypes::e, Path.Op.Surface::msg, Gui::Dialog::ApplicationCache::performAction(), Gui::Dialog::ApplicationCache::periodicCheckOfSize(), Gui::Dialog::ApplicationCache::size(), and Base::ConsoleSingleton::Warning().
checkForRecomputes()
void Application::checkForRecomputes () static
Prompt about recomputing if needed.
Definition at line 970 of file Gui/Application.cpp.
References App::Application::Config(), toolbit-attributes::doc, SCL.SimpleDataTypes::e, App::GetApplication(), App::Document::getDependentDocuments(), Gui::getMainWindow(), App::Document::RecomputeOnRestore, Gui::WaitCursor::restoreCursor(), and Path.Log::warning().
Referenced by open(), and StartGui::StartView::openExistingFile().
commandManager()
CommandManager & Application::commandManager ()
Reference to the command manager.
Definition at line 1903 of file Gui/Application.cpp.
Referenced by Gui::ViewProviderLink::_setupContextMenu(), Gui::Workbench::activated(), Gui::PythonGroupCommand::activated(), Gui::GroupCommand::addCommand(), Gui::Dialog::DlgCustomToolbarsImp::addCustomCommand(), MatGui::Array2D::Array2D(), Gui::Dialog::DlgCustomToolbars::changeEvent(), Gui::Dialog::DlgCustomKeyboardImp::changeEvent(), Gui::MainWindow::changeEvent(), Gui::CommandManager::checkAcceleratorForConflicts(), Gui::CommandActionPy::CommandActionPy(), Gui::PythonGroupCommand::createAction(), CreateCloudCommands(), PartDesignGui::TaskDressUpParameters::createDeleteAction(), FemGui::TaskFemConstraint::createDeleteAction(), Gui::CreateDocCommands(), CreateDrawingCommands(), Gui::CreateFeatCommands(), CreateFemCommands(), CreateImportCommands(), CreateInspectionCommands(), Gui::CreateLinkCommands(), Gui::Workbench::createLinkMenu(), Gui::CreateMacroCommands(), CreateMaterialCommands(), CreateMeasureCommands(), CreateMeshCommands(), CreateMeshPartCommands(), CreateParamPartCommands(), CreatePartCommands(), CreatePartDesignBodyCommands(), CreatePartDesignCommands(), CreatePartDesignPrimitiveCommands(), CreatePartSelectCommands(), CreatePathCommands(), CreatePointsCommands(), Gui::MainWindow::createPopupMenu(), CreateReverseEngineeringCommands(), CreateRobotCommands(), CreateRobotCommandsExport(), CreateRobotCommandsInsertRobots(), CreateRobotCommandsTrajectory(), CreateSandboxCommands(), CreateSimplePartCommands(), CreateSketcherCommands(), CreateSketcherCommandsAlterGeo(), CreateSketcherCommandsBSpline(), CreateSketcherCommandsConstraintAccel(), CreateSketcherCommandsConstraints(), CreateSketcherCommandsCreateGeo(), CreateSketcherCommandsOverlay(), CreateSketcherCommandsVirtualSpace(), CreateSpreadsheetCommands(), Gui::CreateStdCommands(), Gui::CreateStructureCommands(), CreateSurfaceCommands(), CreateTechDrawCommands(), CreateTechDrawCommandsAnnotate(), CreateTechDrawCommandsDecorate(), CreateTechDrawCommandsDims(), CreateTechDrawCommandsExtensionDims(), CreateTechDrawCommandsExtensions(), CreateTechDrawCommandsStack(), Gui::CreateTestCommands(), Gui::CreateViewStdCommands(), Gui::CreateWindowStdCommands(), PartDesignGui::WorkflowManager::determineWorkflow(), Gui::MainWindow::event(), Gui::CommandActionPy::getAction(), Gui::CommandActionPy::getCommand(), Gui::Dialog::CommandModel::goAddMacro(), Gui::Dialog::DlgCustomKeyboardImp::initCommandCompleter(), Gui::Dialog::DlgCustomKeyboardImp::initCommandList(), Gui::PythonGroupCommand::languageChange(), StartGui::StartLauncher::Launch(), Gui::MacroCommand::load(), MatGui::MaterialSave::MaterialSave(), SpreadsheetGui::SheetTableView::mergeCells(), StartGui::Manipulator::modifyMenuBar(), StartGui::StartView::newArchFile(), StartGui::StartView::newAssemblyFile(), StartGui::StartView::newDraftFile(), StartGui::StartView::newEmptyFile(), Gui::CommandManager::newMacroName(), StartGui::StartView::newPartDesignFile(), Gui::Dialog::DlgCustomActionsImp::onActionListWidgetItemActivated(), Gui::Dialog::DlgCustomActionsImp::onButtonAddActionClicked(), Gui::Dialog::DlgCustomActionsImp::onButtonRemoveActionClicked(), Gui::Dialog::DlgCustomActionsImp::onButtonReplaceActionClicked(), Gui::ShortcutManager::OnChange(), Gui::Dialog::DlgCustomKeyboardImp::onCommandTreeWidgetCurrentItemChanged(), Gui::Dialog::DlgCustomKeyboardImp::onEditShortcutTextChanged(), Gui::Dialog::DemoMode::onFullscreenToggled(), Gui::Dialog::DlgSettingsGeneral::onLinkActivated(), SketcherGui::TaskSketcherConstraints::onListWidgetConstraintsUpdateActiveStatus(), SketcherGui::TaskSketcherConstraints::onListWidgetConstraintsUpdateDrivingStatus(), Gui::Dialog::DlgCustomToolbars::onModifyMacroAction(), Gui::TaskCSysDragger::open(), StartGui::StartView::openExistingFile(), Gui::OverlayTabWidget::OverlayTabWidget(), Gui::Dialog::DlgCustomKeyboardImp::populateCommandGroups(), Gui::Dialog::DlgCustomKeyboardImp::populateCommandList(), Gui::Command::printConflictingAccelerators(), Gui::PythonCommand::PythonCommand(), Gui::PythonGroupCommand::PythonGroupCommand(), Gui::ApplicationPy::sAddCommand(), Gui::MacroCommand::save(), SurfaceGui::SectionsPanel::SectionsPanel(), Gui::CommandActionPy::setattro(), Gui::ToolBoxManager::setup(), Gui::ToolBarManager::setup(), PartDesignGui::TaskExtrudeParameters::setupDialog(), MeshGui::Workbench::setupMenuBar(), PartDesignGui::TaskTransformedParameters::setupUI(), Gui::Dialog::DlgPreferencePackManagementImp::showAddonManager(), SpreadsheetGui::SheetTableView::splitCell(), Gui::ApplicationPy::sRunCommand(), PartDesignGui::TaskBooleanParameters::TaskBooleanParameters(), PartDesignGui::TaskLoftParameters::TaskLoftParameters(), SandboxGui::TaskPanelView::TaskPanelView(), PartDesignGui::TaskPipeOrientation::TaskPipeOrientation(), PartDesignGui::TaskPipeParameters::TaskPipeParameters(), PartDesignGui::TaskPipeScaling::TaskPipeScaling(), FemGui::TaskPostClip::TaskPostClip(), FemGui::TaskPostCut::TaskPostCut(), Gui::TaskView::TaskWatcherCommands::TaskWatcherCommands(), Gui::TaskView::TaskWatcherPython::TaskWatcherPython(), Gui::Command::testActive(), Gui::MainWindow::updateEditorActions(), and Gui::TaskTransform::~TaskTransform().
createStandardOperations()
void Application::createStandardOperations ()
helper which create the commands
Definition at line 863 of file Gui/Application.cpp.
References Gui::CreateDocCommands(), Gui::CreateFeatCommands(), Gui::CreateLinkCommands(), Gui::CreateMacroCommands(), Gui::CreateStdCommands(), Gui::CreateStructureCommands(), Gui::CreateTestCommands(), Gui::CreateViewStdCommands(), and Gui::CreateWindowStdCommands().
detachView()
void Application::detachView (Gui::BaseView * pcView)
Detach a view (get called by the FCView destructor)
Definition at line 1380 of file Gui/Application.cpp.
Referenced by Gui::BaseView::onClose(), and SpreadsheetGui::SheetView::~SheetView().
editDocument()
Gui::Document * Application::editDocument () const
Getter for the editing document.
Definition at line 1234 of file Gui/Application.cpp.
Referenced by Gui::Document::beforeDelete(), Gui::OverlayTabWidget::checkAutoHide(), SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >::finishControlsChanged(), Gui::ViewProviderDragger::forwardToLink(), Gui::ViewProviderLink::initDraggingPlacement(), Gui::TreeWidget::mouseDoubleClickEvent(), SketcherGui::ViewProviderSketch::purgeHandler(), Gui::ApplicationPy::sEditDocument(), SketcherGui::ViewProviderSketch::setEdit(), SketcherGui::ViewProviderSketch::setEditViewer(), Gui::Document::slotDeletedObject(), Gui::DocumentItem::slotInEdit(), Gui::Document::slotSkipRecompute(), SketcherGui::ViewProviderSketch::slotSolverUpdate(), and Gui::ViewProviderLink::startEditing().
editViewOfNode()
Gui::MDIView * Application::editViewOfNode (SoNode * node) const
Definition at line 1239 of file Gui/Application.cpp.
Referenced by SketcherGui::ViewProviderSketch::getScaleFactor().
exportTo()
void Application::exportTo (const char * FileName, const char * DocName, const char * Module)
Export objects from the document DocName to a single file.
Definition at line 786 of file Gui/Application.cpp.
References Gui::Command::App, Gui::MainWindow::appendRecentFile(), toolbit-attributes::doc, SCL.SimpleDataTypes::e, Base::Tools::escapedUnicodeFromUtf8(), Base::Tools::escapeEncodeFilename(), Base::FileInfo::extension(), Base::FileInfo::filePath(), App::GetApplication(), ParameterGrp::GetBool(), Base::Persistence::getClassTypeId(), App::Application::getDocument(), App::Application::getImportFilters(), Gui::getMainWindow(), Gui::SelectionSingleton::getObjectsOfType(), App::Application::GetParameterGroupByPath(), Gui::WaitCursor::NoEvents, Gui::WaitCursor::restoreCursor(), runCommand, Gui::Selection(), Gui::WaitCursor::setIgnoreEvents(), Gui::WaitCursor::setWaitCursor(), Path.Post.scripts.refactored_centroid_post::str, and Path.Log::warning().
Referenced by StdCmdExport::activated().
getDocument() [1/2]
Gui::Document * Application::getDocument (const App::Document * pDoc) const
Retrieves a pointer to the Gui::Document whose App::Document matches to pDoc. If no such document exists 0 is returned.
Definition at line 1343 of file Gui/Application.cpp.
getDocument() [2/2]
Gui::Document * Application::getDocument (const char * name) const
Retrieves a pointer to the Gui::Document whose App::Document has the name name. If no such document exists 0 is returned.
Definition at line 1331 of file Gui/Application.cpp.
References App::GetApplication(), and App::Application::getDocument().
Referenced by TechDrawGui::_createBalloon(), PartGui::LoftWidget::accept(), PartGui::SweepWidget::accept(), PartGui::FaceAppearances::accept(), TechDrawGui::TaskLineDecor::accept(), TechDrawGui::TaskProjGroup::accept(), TechDrawGui::TaskDetail::accept(), TechDrawGui::TaskCosVertex::accept(), TechDrawGui::TaskRichAnno::accept(), TechDrawGui::TaskLeaderLine::accept(), TechDrawGui::TaskCenterLine::accept(), Gui::Dialog::DocumentRecovery::accept(), MeshPartGui::Tessellation::accept(), Gui::TaskCSysDragger::accept(), Gui::Dialog::TransformStrategy::acceptDataTransform(), Gui::AlignmentGroup::addView(), Gui::TransactionViewProvider::applyNew(), Gui::Dialog::TransformStrategy::applyViewTransform(), Gui::TaskView::TaskDialog::associateToObject3dView(), Gui::MainWindow::closeAllDocuments(), TechDrawGui::TaskActiveView::createActiveView(), TechDrawGui::TaskHatch::createHatch(), TechDrawGui::ViewProviderPage::createMDIViewPage(), Gui::TreeWidget::dropEvent(), execStackBottom(), execStackDown(), execStackTop(), execStackUp(), Gui::Document::exportObjects(), Gui::ViewProviderDocumentObject::findFrontRootOfType(), PartGui::DlgScale::findShapes(), PartGui::DlgExtrusion::findShapes(), Gui::ViewProviderDocumentObject::getActiveView(), Gui::DocumentT::getDocument(), Gui::AlignmentGroup::getDocument(), Gui::ViewProviderDocumentObject::getDocument(), Gui::ViewProviderT::getDocument(), Gui::ViewProviderDocumentObject::getEditingView(), TechDrawGui::QGIView::getFrameState(), InspectionGui::ViewProviderInspection::getIcon(), Gui::ViewProviderDocumentObject::getInventorView(), TechDrawGui::ViewProviderTemplate::getMDIViewPage(), TechDrawGui::ViewProviderTemplate::getQTemplate(), TechDrawGui::ViewProviderPage::getQTemplate(), TechDrawGui::ViewProviderDrawingView::getQView(), Gui::LinkInfo::getView(), Gui::ViewProviderDocumentObject::getViewOfNode(), TechDrawGui::QGIView::getViewProvider(), TechDrawGui::ViewProviderDrawingView::getViewProviderPage(), TechDrawGui::QGIView::getViewProviderPage(), Gui::ViewProviderDocumentObjectGroup::getViewProviders(), Gui::MainWindow::insertFromMimeData(), Gui::TreeWidget::isObjectShowable(), Gui::TaskView::TaskView::keyPressEvent(), TechDrawGui::TaskLinkDim::loadAvailDims(), Gui::MergeDocuments::MergeDocuments(), Gui::DAG::Model::mouseDoubleClickEvent(), Gui::TreeWidget::onActivateDocument(), Gui::TreeWidget::onFinishEditing(), TechDrawGui::ViewProviderDrawingView::onGuiRepaint(), PartGui::FaceAppearances::open(), TechDrawGui::PagePrinter::print(), TechDrawGui::PagePrinter::printAll(), TechDrawGui::PagePrinter::printAllPdf(), TechDrawGui::PagePrinter::printPdf(), PartGui::FaceAppearances::Private::Private(), PartGui::FaceAppearances::reject(), TechDrawGui::TaskLineDecor::reject(), TechDrawGui::TaskProjGroup::reject(), TechDrawGui::TaskDetail::reject(), TechDrawGui::TaskCosVertex::reject(), TechDrawGui::TaskRichAnno::reject(), TechDrawGui::TaskLeaderLine::reject(), TechDrawGui::TaskCenterLine::reject(), Gui::TaskCSysDragger::reject(), Gui::Dialog::TransformStrategy::resetViewTransform(), Gui::Dialog::PlacementHandler::revertTransformation(), Gui::Document::save(), Gui::Document::saveAll(), PartGui::DlgSettings3DViewPart::saveSettings(), Gui::TreeWidget::selectAll(), FemGui::ActiveAnalysisObserver::setActiveObject(), TechDrawGui::ViewProviderPage::setTemplateMarkers(), PartDesignGui::ViewProviderBody::setVisualBodyMode(), Gui::ApplicationPy::sExport(), Gui::ApplicationPy::sGetDocument(), DrawingGui::ViewProviderDrawingPage::showDrawingView(), SpreadsheetGui::ViewProviderSheet::showSpreadsheetView(), Gui::ApplicationPy::sSetActiveDocument(), PartGui::TaskAttacher::TaskAttacher(), TechDrawGui::TaskCosVertex::TaskCosVertex(), TechDrawGui::TaskDetail::TaskDetail(), TechDrawGui::TaskLeaderLine::TaskLeaderLine(), TechDrawGui::TaskProjGroup::TaskProjGroup(), TechDrawGui::TaskRichAnno::TaskRichAnno(), TechDrawGui::TaskProjGroup::turnProjGroupToView(), PartDesignGui::ViewProviderBody::unifyVisualProperty(), TechDrawGui::ViewProviderTemplate::updateData(), DrawingGui::ViewProviderDrawingPage::updateData(), MeshGui::ViewProviderMeshCurvature::updateData(), TechDrawGui::ViewProviderGeomHatch::updateGraphic(), and InspectionGui::VisualInspection::VisualInspection().
getUserEditMode()
int Application::getUserEditMode (const std::string & mode = "") const
Definition at line 1472 of file Gui/Application.cpp.
getUserEditModeUIStrings()
std::pair< std::string, std::string > Application::getUserEditModeUIStrings (int mode = -1) const
Definition at line 1485 of file Gui/Application.cpp.
Referenced by StdCmdUserEditMode::languageChange().
getViewProvider()
Gui::ViewProvider * Application::getViewProvider (const App::DocumentObject * obj) const
Get the view provider of the given object.
Definition at line 1370 of file Gui/Application.cpp.
Referenced by Gui::Command::_copyVisual(), PartGui::DlgFilletEdges::accept(), Gui::TaskView::TaskDialog::associateToObject3dView(), Gui::View3DInventorSelection::checkGroupOnTop(), Gui::ViewProvider::claimChildrenRecursive(), SketcherGui::ConstraintView::deleteSelectedItems(), SketcherGui::ElementView::deleteSelectedItems(), Gui::SoFCUnifiedSelection::doAction(), AssemblyGui::ViewProviderAssemblyLink::doubleClicked(), Gui::ViewProviderGeoFeatureGroupExtension::extensionClaimChildren(), ImportGui::ExportOCAFGui::findColors(), Gui::DocumentItem::findRootIndex(), finishDressupFeature(), TechDrawGui::ViewProviderPage::fixSceneDependencies(), AssemblyGui::ViewProviderAssembly::getCenterOfBoundingBox(), Gui::LinkInfo::getDetail(), Gui::ViewProviderDocumentObject::getDetailPath(), TDHandlerDimension::getDimLabel(), TDHandlerDimension::getDimPositionToBe(), Gui::ViewProviderLink::getElementColors(), Gui::ViewProviderLink::getLinkedView(), TechDrawGui::ViewProviderHatch::getMDIView(), TechDrawGui::ViewProviderGeomHatch::getMDIView(), PartDesignGui::ViewProviderDatum::getRelevantBoundBox(), Gui::Document::getTreeRootObjects(), MeshGui::MeshSelection::getViewProviders(), PartGui::TaskCheckGeometryResults::goCheck(), FemGui::ViewProviderFemConstraintOnBoundary::highlightReferences(), SurfaceGui::ViewProviderGeomFillSurface::highlightReferences(), SurfaceGui::ViewProviderSections::highlightReferences(), SurfaceGui::ViewProviderFilling::highlightReferences(), PartDesignGui::ViewProviderDressUp::highlightReferences(), PartDesignGui::ViewProviderShapeBinder::highlightReferences(), PartDesignGui::ViewProviderExtrude::highlightShapeFaces(), PartGui::SectionCut::onBFragTransparencyHSMoved(), PartDesignGui::ViewProvider::onDelete(), PartGui::ViewProviderOffset::onDelete(), PartGui::ViewProviderThickness::onDelete(), PartDesignGui::TaskBooleanParameters::onSelectionChanged(), Gui::PropertyView::onTimer(), PartGui::PropertyEnumAttacherItem::openTask(), TechDrawGui::PagePrinter::printAll(), TechDrawGui::PagePrinter::printAllPdf(), PartGui::OffsetWidget::reject(), PartGui::ThicknessWidget::reject(), PartDesignGui::TaskDlgSketchBasedParameters::reject(), PartDesignGui::TaskDlgFeatureParameters::reject(), Gui::ViewProviderCoordinateSystem::resetTemporarySize(), Gui::TreeWidget::selectAllLinks(), Gui::Document::setActiveView(), MeshPartGui::Tessellation::setFaceColors(), Gui::ViewProviderLink::setOverrideMode(), Gui::ViewProviderCoordinateSystem::setPlaneLabelVisibility(), PartDesignGui::ViewProviderAddSub::setPreviewDisplayMode(), Gui::ViewProviderCoordinateSystem::setTemporaryScale(), Gui::ViewProviderCoordinateSystem::setTemporaryVisibility(), PartGui::DlgFilletEdges::setupFillet(), Gui::SelectionSingleton::setVisible(), Gui::ApplicationPy::sExport(), TechDrawGui::QGIDatumLabel::snapPosition(), PartDesignGui::ViewProviderTransformed::startEditing(), PartDesignGui::TaskBoxPrimitives::TaskBoxPrimitives(), FemGui::TaskCreateElementSet::TaskCreateElementSet(), FemGui::TaskCreateNodeSet::TaskCreateNodeSet(), PartDesignGui::TaskFeaturePick::TaskFeaturePick(), FemGui::ViewProviderFemPostPipeline::updateColorBars(), RobotGui::ViewProviderRobotObject::updateData(), PartDesignGui::ViewProviderBody::updateData(), PartGui::ViewProviderMultiFuse::updateData(), PartGui::ViewProviderBoolean::updateData(), PartGui::ViewProviderFillet::updateData(), PartGui::ViewProviderCompound::updateData(), PartGui::ViewProviderMultiCommon::updateData(), PartGui::ViewProviderChamfer::updateData(), FemGui::ViewProviderFemPostPipeline::updateFunctionSize(), FemGui::ViewProviderFemPostFunctionProvider::updateSize(), Gui::View3DInventorViewer::viewSelection(), PartGui::DlgProjectionOnSurface::~DlgProjectionOnSurface(), PartDesignGui::TaskBoxPrimitives::~TaskBoxPrimitives(), PartDesignGui::TaskHelixParameters::~TaskHelixParameters(), PartDesignGui::TaskLinearPatternParameters::~TaskLinearPatternParameters(), PartDesignGui::TaskMirroredParameters::~TaskMirroredParameters(), and PartDesignGui::TaskPolarPatternParameters::~TaskPolarPatternParameters().
hiddenMainWindow()
bool Application::hiddenMainWindow () static
whenever GUI is about to start with the main window hidden
Definition at line 2320 of file Gui/Application.cpp.
References App::Application::Config().
hideViewProvider()
void Application::hideViewProvider (const App::DocumentObject * obj)
Hides the associated view provider of the given object.
Definition at line 1362 of file Gui/Application.cpp.
References Gui::ViewProvider::hide().
Referenced by FemGui::TaskDlgMeshShapeNetgen::accept(), PartDesignGui::ViewProviderBody::dropObject(), Gui::ApplicationPy::sHideObject(), PathGui::ViewProviderPathShape::updateData(), PartGui::ViewProviderMultiFuse::updateData(), PathGui::ViewProviderArea::updateData(), PartGui::ViewProviderBoolean::updateData(), PathGui::ViewProviderAreaView::updateData(), PartGui::ViewProviderCompound::updateData(), and PartGui::ViewProviderMultiCommon::updateData().
importFrom()
void Application::importFrom (const char * FileName, const char * DocName, const char * Module)
import a file into the document DocName
Definition at line 693 of file Gui/Application.cpp.
References Gui::Command::App, Gui::MainWindow::appendRecentFile(), toolbit-attributes::doc, doCommand, SCL.SimpleDataTypes::e, Base::Tools::escapeEncodeFilename(), Base::FileInfo::extension(), Base::FileInfo::filePath(), App::GetApplication(), ParameterGrp::GetBool(), Gui::getMainWindow(), App::Application::GetParameterGroupByPath(), Base::FileInfo::hasExtension(), Gui::WaitCursor::NoEvents, Gui::MDIView::onMsg(), Arch::QT_TRANSLATE_NOOP, Gui::WaitCursor::restoreCursor(), runCommand, Gui::WaitCursor::setIgnoreEvents(), Gui::WaitCursor::setWaitCursor(), Gui::FileDialog::setWorkingDirectory(), and Path.Log::warning().
Referenced by StdCmdImport::activated(), and Gui::ModuleIO::importFiles().
initApplication()
void Application::initApplication () static
Definition at line 2017 of file Gui/Application.cpp.
References Base::Console(), App::Application::destructObserver(), Base::ConsoleSingleton::Error(), SIM::Coin3D::Quarter::Quarter::init(), init_resources(), messageHandler(), and old_qtmsg_handler.
initOpenInventor()
void Application::initOpenInventor () static
Definition at line 2117 of file Gui/Application.cpp.
References SIM::Coin3D::Quarter::Quarter::init(), and Gui::SoFCDB::init().
initTypes()
void Application::initTypes () static
Definition at line 2040 of file Gui/Application.cpp.
References Base::Persistence::getClassTypeId(), SIM::Coin3D::Quarter::Quarter::init(), Base::Persistence::init(), Base::BaseClass::init(), and App::Extension::init().
isClosing()
bool Application::isClosing ()
true when the application shutting down
Definition at line 1893 of file Gui/Application.cpp.
listUserEditModes()
std::map<int, std::pair<std::string,std::string> > Gui::Application::listUserEditModes () const inline
Definition at line 290 of file Gui/Application.h.
macroManager()
MacroManager * Application::macroManager ()
Get macro manager.
Definition at line 1898 of file Gui/Application.cpp.
Referenced by Gui::Command::_runCommand(), Gui::Dialog::DlgMacroExecuteImp::accept(), StdCmdMacroStartDebug::activated(), StdCmdMacroStopDebug::activated(), StdCmdMacroStepOver::activated(), StdCmdMacroStepInto::activated(), Gui::MacroCommand::activated(), StdCmdViewIvIssueCamPos::activated(), Gui::RecentMacrosAction::activateFile(), Gui::Command::addModule(), PendingLine::cancel(), Gui::SelectionSingleton::clearCompleteSelection(), Gui::SelectionSingleton::clearSelection(), Gui::Dialog::DlgMacroRecordImp::DlgMacroRecordImp(), Gui::SelectionSingleton::enableCommandLog(), Gui::PythonEditorView::executeScript(), StdCmdMacroStopDebug::isActive(), StdCmdMacroStepOver::isActive(), StdCmdMacroStepInto::isActive(), Gui::SelectionSingleton::_SelObj::log(), Gui::TreeWidget::mouseDoubleClickEvent(), PendingLine::PendingLine(), Gui::Command::printCaller(), Gui::PythonEditorP::PythonEditorP(), Gui::ApplicationPy::sDoCommand(), Gui::ApplicationPy::sDoCommandGui(), and Gui::ApplicationPy::sDoCommandSkip().
onLastWindowClosed()
void Application::onLastWindowClosed (Gui::Document * pcDoc)
message when a GuiDocument is about to vanish
Definition at line 1093 of file Gui/Application.cpp.
References Base::Console(), Gui::Command::Doc, doCommand, SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), Base::BaseClass::getClassTypeId(), Gui::Document::getDocument(), Gui::getMainWindow(), App::Document::getName(), Gui::MainWindow::setActiveWindow(), App::Document::TempDoc, and TestSpreadsheet::v.
Referenced by Gui::Document::detachView().
onUpdate()
void Application::onUpdate ()
call update to all documents and all views (costly!)
Definition at line 1385 of file Gui/Application.cpp.
Referenced by Gui::DimensionWidget::setUserSchema(), slotActiveDocument(), and Gui::Command::updateAll().
open()
void Application::open (const char * FileName, const char * Module)
open a file
Definition at line 616 of file Gui/Application.cpp.
References Gui::Command::App, Gui::MainWindow::appendRecentFile(), checkForRecomputes(), App::Document::countObjects(), toolbit-attributes::doc, doCommand, SCL.SimpleDataTypes::e, Base::Tools::escapedUnicodeFromUtf8(), Base::Tools::escapeEncodeFilename(), Base::FileInfo::extension(), Base::FileInfo::filePath(), ifctree::filepath, App::Application::getActiveDocument(), App::GetApplication(), ParameterGrp::GetBool(), Gui::getMainWindow(), App::Document::getName(), App::Application::GetParameterGroupByPath(), Draft::gui, Gui::Command::Gui, Base::FileInfo::hasExtension(), Gui::WaitCursor::NoEvents, Gui::WaitCursor::restoreCursor(), runCommand, Gui::WaitCursor::setIgnoreEvents(), Gui::WaitCursor::setWaitCursor(), Gui::FileDialog::setWorkingDirectory(), TestSpreadsheet::v, and Path.Log::warning().
Referenced by StdCmdOpen::activated(), Gui::GUIApplication::event(), Gui::ModuleIO::openFile(), and Gui::ApplicationPy::sLoadFile().
prefPackManager()
Gui::PreferencePackManager * Application::prefPackManager ()
Definition at line 1908 of file Gui/Application.cpp.
Referenced by Gui::Dialog::DlgPreferencePackManagementImp::deleteUserPack(), Gui::Dialog::DlgSettingsGeneral::DlgSettingsGeneral(), Gui::Dialog::DlgPreferencePackManagementImp::hideBuiltInPack(), Gui::Dialog::DlgPreferencePackManagementImp::hideInstalledPack(), Gui::Dialog::DlgSettingsGeneral::loadThemes(), Gui::Dialog::DlgSettingsGeneral::newPreferencePackDialogAccepted(), Gui::Dialog::DlgSettingsGeneral::onImportConfigClicked(), Gui::Dialog::DlgSettingsGeneral::recreatePreferencePackMenu(), Gui::Dialog::DlgSettingsGeneral::saveThemes(), Gui::Dialog::DlgPreferencePackManagementImp::showEvent(), Gui::Dialog::DlgRevertToBackupConfigImp::showEvent(), and StartGui::ThemeSelectorWidget::themeChanged().
reopen()
App::Document * Application::reopen (App::Document * doc)
Reload a partial opened document.
Definition at line 2524 of file Gui/Application.cpp.
References toolbit-attributes::doc, DrawingExample::file, App::GetApplication(), Base::BaseClass::getClassTypeId(), App::PropertyContainer::getPropertyList(), Gui::WaitCursor::NoEvents, App::Application::openDocument(), App::Document::PartialDoc, App::Document::PartialRestore, Gui::Document::setActiveView(), Gui::WaitCursor::setIgnoreEvents(), and TestSpreadsheet::v.
Referenced by Gui::TreeWidget::onReloadDoc(), and Gui::ApplicationPy::sReload().
replaceVariablesInQss()
QString Application::replaceVariablesInQss (QString qssText)
Definition at line 2449 of file Gui/Application.cpp.
References App::GetApplication(), App::Application::GetParameterGroupByPath(), and ParameterGrp::GetUnsigned().
runApplication()
void Application::runApplication () static
Definition at line 2256 of file Gui/Application.cpp.
References src.Mod.AddonManager.AddonManagerTest.gui.test_python_deps_gui::app, Base::Console(), Gui::StartupPostProcess::execute(), App::Application::GetARGC(), App::Application::GetARGV(), Gui::getMainWindow(), Instance, Base::ConsoleSingleton::Log(), NavigationIndicatorGui::mw, importAirfoilDAT::process(), and Gui::StartupProcess::setupApplication().
runInitGuiScript()
void Application::runInitGuiScript () static
Definition at line 2125 of file Gui/Application.cpp.
References Base::Interpreter(), Base::InterpreterSingleton::runString(), and Base::ScriptFactory().
sendHasMsgToActiveView()
bool Application::sendHasMsgToActiveView (const char * pMsg)
send Messages test to the active view
Definition at line 1155 of file Gui/Application.cpp.
References Gui::MainWindow::activeWindow(), Gui::getMainWindow(), and NavigationIndicatorGui::pView.
Referenced by StdCmdSave::isActive(), StdCmdSaveAs::isActive(), StdCmdPrint::isActive(), StdCmdPrintPreview::isActive(), StdCmdPrintPdf::isActive(), StdCmdUndo::isActive(), StdCmdRedo::isActive(), StdCmdCut::isActive(), StdCmdViewFitAll::isActive(), StdCmdViewFitSelection::isActive(), StdCmdViewVR::isActive(), StdCmdViewExample1::isActive(), StdCmdViewExample2::isActive(), StdCmdViewExample3::isActive(), StdCmdViewIvStereoOff::isActive(), StdCmdViewIvStereoRedGreen::isActive(), StdCmdViewIvStereoQuadBuff::isActive(), StdCmdViewIvStereoInterleavedRows::isActive(), StdCmdViewIvStereoInterleavedColumns::isActive(), StdCmdViewIvIssueCamPos::isActive(), StdViewZoomIn::isActive(), StdViewZoomOut::isActive(), and StdCmdAlignToSelection::isActive().
sendHasMsgToFocusView()
bool Application::sendHasMsgToFocusView (const char * pMsg)
send Messages test to the focused view
Definition at line 1178 of file Gui/Application.cpp.
References Gui::MainWindow::activeWindow(), Gui::getMainWindow(), and NavigationIndicatorGui::pView.
sendMsgToActiveView()
bool Application::sendMsgToActiveView (const char * pMsg, const char ** ppReturn = nullptr)
send Messages to the active view
Definition at line 1147 of file Gui/Application.cpp.
References Gui::MainWindow::activeWindow(), Gui::getMainWindow(), and NavigationIndicatorGui::pView.
Referenced by StdCmdFreezeViews::activated(), StdCmdUndo::activated(), StdCmdRedo::activated(), StdCmdCut::activated(), StdCmdViewIvIssueCamPos::activated(), Gui::Dialog::RedoDialog::onSelected(), and Gui::Dialog::UndoDialog::onSelected().
sendMsgToFocusView()
bool Application::sendMsgToFocusView (const char * pMsg, const char ** ppReturn = nullptr)
send Messages to the focused view
send Messages to the active view
Definition at line 1162 of file Gui/Application.cpp.
References Gui::MainWindow::activeWindow(), Gui::getMainWindow(), and NavigationIndicatorGui::pView.
Referenced by StdCmdCopy::activated(), StdCmdPaste::activated(), StdViewZoomIn::activated(), and StdViewZoomOut::activated().
setActiveDocument()
void Application::setActiveDocument (Gui::Document * pcDocument)
Set the active document.
Definition at line 1259 of file Gui/Application.cpp.
References Gui::MacroManager::Cmt, Base::Console(), toolbit-attributes::doc, SCL.SimpleDataTypes::e, Gui::Document::getDocument(), App::Document::getName(), Base::Interpreter(), Base::ConsoleSingleton::Log(), Base::InterpreterSingleton::runString(), and Base::ConsoleSingleton::Warning().
setEditDocument()
void Application::setEditDocument (Gui::Document * pcDocument)
Set editing document, which will reset editing of all other document.
Definition at line 1244 of file Gui/Application.cpp.
References toolbit-attributes::doc, and TestSpreadsheet::v.
Referenced by Gui::Document::_resetEdit(), Gui::ElementColors::accept(), Gui::Document::beforeDelete(), Gui::ElementColors::reject(), Gui::Document::resetEdit(), and Gui::Document::slotDeletedObject().
setStatus()
void Application::setStatus (Status pos, bool on)
set the status bits
Definition at line 2333 of file Gui/Application.cpp.
References RobotExample::pos.
Referenced by StdCmdOpen::activated().
setStyleSheet()
void Application::setStyleSheet (const QString & qssFile, bool tiledBackground)
Activate a stylesheet.
Definition at line 2338 of file Gui/Application.cpp.
References Gui::ActionStyleEvent::Clear, SCL.SimpleDataTypes::e, SCL.SimpleDataTypes::f, Gui::getMainWindow(), SIM::Coin3D::Quarter::Quarter::init(), src.Mod.PartDesign.Scripts.Gear::l1, src.Mod.PartDesign.Scripts.Gear::l2, NavigationIndicatorGui::mw, Gui::ActionStyleEvent::Restore, and Path.Post.scripts.refactored_centroid_post::str.
Referenced by StdCmdReloadStyleSheet::activated(), and Gui::Dialog::DlgSettingsGeneral::saveThemes().
setupContextMenu()
void Application::setupContextMenu (const char * recipient, MenuItem * items) const
Definition at line 1859 of file Gui/Application.cpp.
References Gui::WorkbenchManager::active(), toolbit-attributes::args, Gui::Workbench::createContextMenu(), SCL.SimpleDataTypes::e, buildPsets::handler, Gui::WorkbenchManager::instance(), Base::BaseClass::isDerivedFrom(), src.Mod.Test.testPathArray::items, Gui::Workbench::name(), src.Mod.Test.testPathArray::o, toolbit-attributes::s, src.Mod.Test.testmakeWireString::String, and Path.Post.scripts.grbl_post::type.
Referenced by Gui::DAG::Model::contextMenuEvent(), Gui::TreeWidget::contextMenuEvent(), SketcherGui::ViewProviderSketch::generateContextMenu(), and Gui::NavigationStyle::openPopupMenu().
setUserEditMode() [1/2]
bool Application::setUserEditMode (const std::string & mode)
Definition at line 1506 of file Gui/Application.cpp.
setUserEditMode() [2/2]
bool Application::setUserEditMode (int mode)
Definition at line 1496 of file Gui/Application.cpp.
Referenced by StdCmdUserEditMode::activated(), StdCmdUserEditMode::createAction(), and Gui::ApplicationPy::sSetUserEditMode().
showViewProvider()
void Application::showViewProvider (const App::DocumentObject * obj)
Shows the associated view provider of the given object.
Definition at line 1354 of file Gui/Application.cpp.
References Gui::ViewProvider::show().
Referenced by PathGui::ViewProviderPathShape::onDelete(), PartGui::ViewProviderCompound::onDelete(), PartGui::ViewProviderMirror::onDelete(), PathGui::ViewProviderArea::onDelete(), PartGui::ViewProviderMultiFuse::onDelete(), PartGui::ViewProviderRuledSurface::onDelete(), PartGui::ViewProviderBoolean::onDelete(), PathGui::ViewProviderAreaView::onDelete(), PartGui::ViewProviderFillet::onDelete(), PartGui::ViewProviderMultiCommon::onDelete(), PartGui::ViewProviderChamfer::onDelete(), PartGui::ViewProviderRevolution::onDelete(), DrawingGui::OrthoViews::OrthoViews(), Gui::ApplicationPy::sShowObject(), PartDesignGui::TaskLoftParameters::TaskLoftParameters(), and PartDesignGui::TaskPipeScaling::TaskPipeScaling().
slotActivatedObject()
void Application::slotActivatedObject (const ViewProvider & vp) protected
Definition at line 1077 of file Gui/Application.cpp.
Referenced by slotNewDocument().
slotActiveDocument()
void Application::slotActiveDocument (const App::Document & Doc) protected
Definition at line 1010 of file Gui/Application.cpp.
References Gui::MainWindow::activeWindow(), toolbit-attributes::doc, App::GetApplication(), ParameterGrp::GetBool(), Base::UnitsApi::getDecimals(), ParameterGrp::GetInt(), Gui::getMainWindow(), App::Application::GetParameterGroupByPath(), App::PropertyEnumeration::getValue(), Instance, onUpdate(), Gui::MainWindow::setActiveWindow(), Base::UnitsApi::setDecimals(), Base::UnitsApi::setSchema(), Gui::MainWindow::setUserSchema(), and App::Document::UnitSystem.
Referenced by Application().
slotChangedObject()
void Application::slotChangedObject (const ViewProvider & vp, const App::Property & Prop) protected
Definition at line 1066 of file Gui/Application.cpp.
Referenced by slotNewDocument().
slotDeletedObject()
void Application::slotDeletedObject (const ViewProvider & vp) protected
Definition at line 1060 of file Gui/Application.cpp.
Referenced by slotNewDocument().
slotDeleteDocument()
void Application::slotDeleteDocument (const App::Document & Doc) protected
Definition at line 906 of file Gui/Application.cpp.
References Gui::SelectionSingleton::clearCompleteSelection(), Base::Console(), toolbit-attributes::doc, App::Document::getName(), Base::ConsoleSingleton::Log(), and Gui::Selection().
Referenced by Application().
slotInEdit()
void Application::slotInEdit (const Gui::ViewProviderDocumentObject & vp) protected
Definition at line 1083 of file Gui/Application.cpp.
Referenced by slotNewDocument().
slotNewDocument()
void Application::slotNewDocument (const App::Document & Doc, bool isMainDoc) protected
Observer message from the Application.
Definition at line 877 of file Gui/Application.cpp.
References draftgeoutils.faces::bind(), Base::BaseClass::getClassTypeId(), slotActivatedObject(), slotChangedObject(), slotDeletedObject(), slotInEdit(), slotNewObject(), slotRelabelObject(), and slotResetEdit().
Referenced by Application().
slotNewObject()
void Application::slotNewObject (const ViewProvider & vp) protected
Definition at line 1054 of file Gui/Application.cpp.
Referenced by slotNewDocument().
slotRelabelDocument()
void Application::slotRelabelDocument (const App::Document & Doc) protected
Definition at line 939 of file Gui/Application.cpp.
References toolbit-attributes::doc.
Referenced by Application().
slotRelabelObject()
void Application::slotRelabelObject (const ViewProvider & vp) protected
Definition at line 1072 of file Gui/Application.cpp.
Referenced by slotNewDocument().
slotRenameDocument()
void Application::slotRenameDocument (const App::Document & Doc) protected
Definition at line 950 of file Gui/Application.cpp.
References toolbit-attributes::doc.
Referenced by Application().
slotResetEdit()
void Application::slotResetEdit (const Gui::ViewProviderDocumentObject & vp) protected
Definition at line 1088 of file Gui/Application.cpp.
Referenced by slotNewDocument().
slotShowHidden()
void Application::slotShowHidden (const App::Document & Doc) protected
Definition at line 960 of file Gui/Application.cpp.
References toolbit-attributes::doc.
Referenced by Application().
testStatus()
bool Application::testStatus (Status pos) const
return the status bits
Definition at line 2328 of file Gui/Application.cpp.
References RobotExample::pos.
tryClose()
void Application::tryClose (QCloseEvent * e)
Definition at line 1439 of file Gui/Application.cpp.
References App::Application::closeAllDocuments(), SCL.SimpleDataTypes::e, App::GetApplication(), and Gui::getMainWindow().
Referenced by Gui::MainWindow::closeEvent().
updateActions()
void Application::updateActions (bool delay = false)
call update to all command actions
Definition at line 1434 of file Gui/Application.cpp.
References Gui::getMainWindow(), and Gui::MainWindow::updateActions().
Referenced by Gui::ViewProvider::onChanged().
updateActive()
void Application::updateActive ()
call update to all views of the active document
Definition at line 1429 of file Gui/Application.cpp.
viewActivated()
void Application::viewActivated (Gui::MDIView * pcView)
get called if a view gets activated, this manage the whole activation scheme
Gets called if a view gets activated, this manages the whole activation scheme.
Definition at line 1400 of file Gui/Application.cpp.
References Gui::MDIView::buildWindowTitle(), Base::Console(), Gui::BaseView::getGuiDocument(), Gui::getMainWindow(), Gui::BaseView::isPassive(), Base::ConsoleSingleton::Log(), and Gui::MainWindow::setWindowTitle().
Referenced by Gui::MainWindow::changeEvent(), and Gui::MainWindow::setActiveWindow().
viewClosed()
void Application::viewClosed (Gui::MDIView * pcView)
get called if a view gets closed
Gets called if a view gets closed.
Definition at line 1424 of file Gui/Application.cpp.
Referenced by Gui::MDIView::closeEvent().
workbenches()
QStringList Application::workbenches () const
Definition at line 1798 of file Gui/Application.cpp.
References App::Application::Config(), src.Mod.Test.testPathArray::items, and RobotExample::pos.
Referenced by Gui::Dialog::DlgCustomToolbars::DlgCustomToolbars(), Gui::Dialog::DlgSettingsWorkbenchesImp::getDisabledWorkbenches(), and Gui::Dialog::DlgSettingsWorkbenchesImp::getEnabledWorkbenches().
workbenchIcon()
QPixmap Application::workbenchIcon (const QString & wb) const
Definition at line 1672 of file Gui/Application.cpp.
References Gui::BitmapFactoryInst::addPixmapToCache(), Gui::BitmapFactory(), SCL.SimpleDataTypes::e, DrawingExample::file, buildPsets::handler, Gui::BitmapFactoryInst::pixmap(), toolbit-attributes::s, Path.Post.scripts.refactored_centroid_post::str, src.Mod.Test.testmakeWireString::String, and Materials::trim().
Referenced by Gui::Dialog::DlgCustomToolbars::DlgCustomToolbars(), Gui::WorkbenchGroup::refreshWorkbenchList(), and Gui::Dialog::wbListItem::wbListItem().
workbenchMenuText()
QString Application::workbenchMenuText (const QString & wb) const
Definition at line 1773 of file Gui/Application.cpp.
References SCL.SimpleDataTypes::e, buildPsets::handler, and src.Mod.Test.testmakeWireString::String.
Referenced by Gui::Dialog::DlgCustomToolbars::DlgCustomToolbars(), Gui::WorkbenchGroup::refreshWorkbenchList(), and Gui::Dialog::wbListItem::wbListItem().
workbenchToolTip()
QString Application::workbenchToolTip (const QString & wb) const
Definition at line 1749 of file Gui/Application.cpp.
References SCL.SimpleDataTypes::e, buildPsets::handler, and src.Mod.Test.testmakeWireString::String.
Referenced by Gui::WorkbenchGroup::refreshWorkbenchList(), and Gui::Dialog::wbListItem::wbListItem().
Friends And Related Function Documentation
ApplicationPy
friend class ApplicationPy friend
Definition at line 303 of file Gui/Application.h.
Member Data Documentation
Instance
Application * Application::Instance = nullptr static
some kind of singleton
Definition at line 242 of file Gui/Application.h.
Referenced by Gui::Command::_copyVisual(), TechDrawGui::_createBalloon(), Gui::Document::_resetEdit(), Gui::Command::_runCommand(), Gui::ViewProviderLink::_setupContextMenu(), PartGui::LoftWidget::accept(), InspectionGui::VisualInspection::accept(), PartGui::SweepWidget::accept(), DrawingGui::TaskProjection::accept(), Gui::Dialog::DlgMacroExecuteImp::accept(), PartGui::FaceAppearances::accept(), TechDrawGui::TaskProjection::accept(), RobotGui::TaskDlgTrajectoryCompound::accept(), FemGui::TaskDlgMeshShapeNetgen::accept(), TechDrawGui::TaskLineDecor::accept(), RobotGui::TaskDlgEdge2Trac::accept(), RobotGui::TaskDlgTrajectoryDressUp::accept(), TechDrawGui::TaskProjGroup::accept(), TechDrawGui::TaskDetail::accept(), TechDrawGui::TaskCosVertex::accept(), TechDrawGui::TaskRichAnno::accept(), Gui::ElementColors::accept(), TechDrawGui::TaskLeaderLine::accept(), TechDrawGui::TaskCenterLine::accept(), Gui::Dialog::DocumentRecovery::accept(), PartGui::DlgFilletEdges::accept(), MeshPartGui::Tessellation::accept(), Gui::TaskCSysDragger::accept(), Gui::Dialog::TransformStrategy::acceptDataTransform(), Gui::Workbench::activated(), StdCmdGroup::activated(), SketcherGui::Workbench::activated(), StdCmdVarSet::activated(), StdCmdMacroStartDebug::activated(), StdCmdMacroStopDebug::activated(), StdCmdMacroStepOver::activated(), StdCmdMacroStepInto::activated(), Gui::PythonGroupCommand::activated(), Gui::MacroCommand::activated(), StdCmdUserEditMode::activated(), StdCmdReloadStyleSheet::activated(), StdViewDockUndockFullscreen::activated(), Gui::RecentMacrosAction::activateFile(), Gui::GroupCommand::addCommand(), Gui::Dialog::DlgCustomToolbarsImp::addCustomCommand(), Gui::Command::addModule(), Gui::SelectionSingleton::addSelection(), addVarSetsVarSetComboBox(), Gui::AlignmentGroup::addView(), Gui::Command::adjustCameraPosition(), Gui::TransactionViewProvider::applyNew(), Gui::Dialog::PlacementHandler::applyPlacement(), Gui::Dialog::TransformStrategy::applyViewTransform(), MatGui::Array2D::Array2D(), Gui::TaskView::TaskDialog::associateToObject3dView(), Gui::BaseView::BaseView(), Gui::Document::beforeDelete(), PendingLine::cancel(), Gui::Dialog::DlgCustomToolbars::changeEvent(), StartGui::StartView::changeEvent(), Gui::Dialog::DlgCustomKeyboardImp::changeEvent(), Gui::MainWindow::changeEvent(), Gui::CommandManager::checkAcceleratorForConflicts(), Gui::OverlayTabWidget::checkAutoHide(), Gui::View3DInventorSelection::checkGroupOnTop(), Gui::TreeWidget::checkTopParent(), Gui::ViewProvider::claimChildrenRecursive(), Gui::SelectionSingleton::clearCompleteSelection(), Gui::SelectionSingleton::clearSelection(), MeshGui::ViewProviderMesh::clipMeshCallback(), Gui::MainWindow::closeAllDocuments(), Gui::MDIView::closeEvent(), Gui::MainWindow::closeEvent(), Gui::CommandActionPy::CommandActionPy(), Gui::Dialog::TransformStrategy::commitTransform(), SketcherGui::ConstraintView::contextMenuEvent(), Gui::DAG::Model::contextMenuEvent(), Gui::TreeWidget::contextMenuEvent(), Gui::PythonGroupCommand::createAction(), StdCmdUserEditMode::createAction(), TechDrawGui::TaskActiveView::createActiveView(), CreateCloudCommands(), PartDesignGui::TaskDressUpParameters::createDeleteAction(), FemGui::TaskFemConstraint::createDeleteAction(), Gui::CreateDocCommands(), CreateDrawingCommands(), Gui::CreateFeatCommands(), CreateFemCommands(), TechDrawGui::TaskHatch::createHatch(), CreateImportCommands(), CreateInspectionCommands(), Gui::CreateLinkCommands(), Gui::Workbench::createLinkMenu(), Gui::CreateMacroCommands(), CreateMaterialCommands(), TechDrawGui::ViewProviderPage::createMDIViewPage(), CreateMeasureCommands(), CreateMeshCommands(), CreateMeshPartCommands(), CreateParamPartCommands(), CreatePartCommands(), CreatePartDesignBodyCommands(), CreatePartDesignCommands(), CreatePartDesignPrimitiveCommands(), CreatePartSelectCommands(), CreatePathCommands(), CreatePointsCommands(), Gui::MainWindow::createPopupMenu(), CreateReverseEngineeringCommands(), CreateRobotCommands(), CreateRobotCommandsExport(), CreateRobotCommandsInsertRobots(), CreateRobotCommandsTrajectory(), CreateSandboxCommands(), ReverseEngineeringGui::SegmentationManual::createSegment(), CreateSimplePartCommands(), CreateSketcherCommands(), CreateSketcherCommandsAlterGeo(), CreateSketcherCommandsBSpline(), CreateSketcherCommandsConstraintAccel(), CreateSketcherCommandsConstraints(), CreateSketcherCommandsCreateGeo(), CreateSketcherCommandsOverlay(), CreateSketcherCommandsVirtualSpace(), CreateSpreadsheetCommands(), Gui::CreateStdCommands(), Gui::CreateStructureCommands(), CreateSurfaceCommands(), CreateTechDrawCommands(), CreateTechDrawCommandsAnnotate(), CreateTechDrawCommandsDecorate(), CreateTechDrawCommandsDims(), CreateTechDrawCommandsExtensionDims(), CreateTechDrawCommandsExtensions(), CreateTechDrawCommandsStack(), Gui::CreateTestCommands(), Gui::CreateViewStdCommands(), Gui::CreateWindowStdCommands(), PartGui::CrossSections::CrossSections(), MeshPartGui::CrossSections::CrossSections(), Gui::MainWindow::customEvent(), PointsGui::ViewProviderScattered::cut(), PointsGui::ViewProviderStructured::cut(), Gui::DocumentIndex::data(), SketcherGui::ConstraintView::deleteSelectedItems(), SketcherGui::ElementView::deleteSelectedItems(), MeshGui::RemoveComponents::deleteSelection(), Gui::Dialog::DlgPreferencePackManagementImp::deleteUserPack(), PartDesignGui::WorkflowManager::determineWorkflow(), Gui::Dialog::DlgCustomKeyboardImp::DlgCustomKeyboardImp(), Gui::Dialog::DlgCustomToolbars::DlgCustomToolbars(), MatGui::DlgDisplayPropertiesImp::DlgDisplayPropertiesImp(), Gui::Dialog::DlgMacroRecordImp::DlgMacroRecordImp(), MatGui::DlgMaterialImp::DlgMaterialImp(), Gui::Dialog::DlgSettingsGeneral::DlgSettingsGeneral(), Gui::SoFCUnifiedSelection::doAction(), Gui::DocumentModel::DocumentModel(), PartDesignGui::ViewProviderDatum::doubleClicked(), Gui::ViewProviderDragger::doubleClicked(), Gui::ViewProviderMaterialObject::doubleClicked(), AssemblyGui::ViewProviderAssemblyLink::doubleClicked(), FemGui::ViewProviderFemPostObject::doubleClicked(), FemGui::ViewProviderFemPostFunction::doubleClicked(), SketcherGui::ViewProviderSketch::doubleClicked(), SketcherGui::DrawSketchKeyboardManager::DrawSketchKeyboardManager(), Gui::TreeWidget::dropEvent(), PartDesignGui::ViewProviderBody::dropObject(), Gui::ElementColors::ElementColors(), Gui::SelectionSingleton::enableCommandLog(), Gui::GUIApplication::event(), Gui::MainWindow::event(), Gui::ViewProvider::eventCallback(), execStackBottom(), execStackDown(), execStackTop(), execStackUp(), Gui::PythonEditorView::executeScript(), PartDesignGui::TaskBooleanParameters::exitSelectionMode(), Gui::Document::exportObjects(), Gui::ViewProviderGeoFeatureGroupExtension::extensionClaimChildren(), PartGui::FaceAppearances::FaceAppearances(), MeshGui::ViewProviderMesh::fillHole(), ImportGui::ExportOCAFGui::findColors(), Gui::ViewProviderDocumentObject::findFrontRootOfType(), ReverseEngineeringGui::SegmentationManual::Private::findGeometry(), Gui::DocumentItem::findRootIndex(), PartGui::DlgScale::findShapes(), PartGui::DlgExtrusion::findShapes(), SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >::finishControlsChanged(), finishDressupFeature(), TechDrawGui::ViewProviderPage::fixSceneDependencies(), Gui::ViewProviderDragger::forwardToLink(), SketcherGui::ViewProviderSketch::generateContextMenu(), TechDrawGui::DrawGuiUtil::get3DDirAndRot(), Gui::CommandActionPy::getAction(), PartDesignGui::getActivePart(), Gui::ViewProviderDocumentObject::getActiveView(), Gui::DocumentT::getAppDocumentPython(), PartGui::getAutoGroupCommandStr(), PartDesignGui::getBody(), Gui::ViewProvider::getBoundingBox(), AssemblyGui::ViewProviderAssembly::getCenterOfBoundingBox(), Gui::CommandActionPy::getCommand(), Gui::LinkInfo::getDetail(), Gui::ViewProviderDocumentObject::getDetailPath(), TDHandlerDimension::getDimLabel(), TDHandlerDimension::getDimPositionToBe(), Gui::Dialog::DlgSettingsWorkbenchesImp::getDisabledWorkbenches(), Gui::DocumentT::getDocument(), Gui::AlignmentGroup::getDocument(), Gui::ViewProviderDocumentObject::getDocument(), Gui::ViewProviderT::getDocument(), Gui::ViewProviderDocumentObject::getEditingView(), Gui::ViewProviderLink::getElementColors(), Gui::Dialog::DlgSettingsWorkbenchesImp::getEnabledWorkbenches(), TechDrawGui::QGIView::getFrameState(), Gui::Command::getGuiApplication(), Gui::DocumentT::getGuiDocumentPython(), InspectionGui::ViewProviderInspection::getIcon(), SketcherGui::getInactiveHandlerEditModeSketchViewProvider(), Gui::ViewProviderDocumentObject::getInventorView(), Gui::ViewProviderLink::getLinkedView(), Gui::ViewProviderDocumentObject::getLinkedViewProvider(), Gui::ViewProviderLink::getLinkedViewProvider(), TechDrawGui::ViewProviderHatch::getMDIView(), TechDrawGui::ViewProviderGeomHatch::getMDIView(), TechDrawGui::ViewProviderTemplate::getMDIViewPage(), Gui::ViewProviderT::getObjectPython(), TechDrawGui::ViewProviderTemplate::getQTemplate(), TechDrawGui::ViewProviderPage::getQTemplate(), TechDrawGui::ViewProviderDrawingView::getQView(), PartDesignGui::ViewProviderDatum::getRelevantBoundBox(), SketcherGui::ViewProviderSketch::getScaleFactor(), Gui::ShortcutManager::getShortcut(), getSketchObject(), MeshPartGui::Tessellation::getStandardParameters(), Gui::Document::getTreeRootObjects(), Gui::LinkInfo::getView(), MeshGui::MeshSelection::getViewer(), Gui::ViewProviderDocumentObject::getViewOfNode(), TechDrawGui::QGIView::getViewProvider(), Gui::DocumentItem::getViewProvider(), TechDrawGui::ViewProviderDrawingView::getViewProviderPage(), TechDrawGui::QGIView::getViewProviderPage(), MeshGui::MeshSelection::getViewProviders(), Gui::ViewProviderDocumentObjectGroup::getViewProviders(), Gui::Dialog::CommandModel::goAddMacro(), PartGui::TaskCheckGeometryResults::goCheck(), FemGui::ViewProviderFemPostObject::hide(), Gui::Dialog::DlgPreferencePackManagementImp::hideBuiltInPack(), Gui::Dialog::DlgPreferencePackManagementImp::hideInstalledPack(), FemGui::ViewProviderFemConstraintOnBoundary::highlightReferences(), SurfaceGui::ViewProviderGeomFillSurface::highlightReferences(), SurfaceGui::ViewProviderSections::highlightReferences(), SurfaceGui::ViewProviderFilling::highlightReferences(), PartDesignGui::ViewProviderDressUp::highlightReferences(), PartDesignGui::ViewProviderShapeBinder::highlightReferences(), PartDesignGui::ViewProviderExtrude::highlightShapeFaces(), Gui::ModuleIO::importFiles(), Gui::Dialog::DlgCustomKeyboardImp::initCommandCompleter(), Gui::Dialog::DlgCustomKeyboardImp::initCommandList(), Gui::ViewProviderLink::initDraggingPlacement(), Gui::MainWindow::insertFromMimeData(), StdCmdMacroStopDebug::isActive(), StdCmdMacroStepOver::isActive(), StdCmdMacroStepInto::isActive(), StdCmdDrawStyle::isActive(), PartDesignGui::ViewProviderBody::isActiveBody(), Gui::Command::isActiveObjectValid(), Gui::ViewProviderPart::isActivePart(), Gui::TreeWidget::isObjectShowable(), Gui::TreeWidget::itemSearch(), Gui::TaskView::TaskView::keyPressEvent(), Gui::PythonGroupCommand::languageChange(), StdCmdUserEditMode::languageChange(), StartGui::StartLauncher::Launch(), Gui::MacroCommand::load(), TechDrawGui::TaskLinkDim::loadAvailDims(), Gui::Dialog::DlgSettingsGeneral::loadThemes(), Gui::SelectionSingleton::_SelObj::log(), PartDesignGui::makeBodyActive(), Gui::ManualAlignment::ManualAlignment(), MeshGui::ViewProviderMesh::markPartCallback(), MatGui::MaterialSave::MaterialSave(), SpreadsheetGui::SheetTableView::mergeCells(), Gui::MergeDocuments::MergeDocuments(), StartGui::Manipulator::modifyMenuBar(), Gui::DAG::Model::mouseDoubleClickEvent(), Gui::TreeView::mouseDoubleClickEvent(), Gui::TreeWidget::mouseDoubleClickEvent(), StartGui::StartView::newArchFile(), StartGui::StartView::newAssemblyFile(), StartGui::StartView::newDraftFile(), StartGui::StartView::newEmptyFile(), Gui::CommandManager::newMacroName(), StartGui::StartView::newPartDesignFile(), Gui::Dialog::DlgSettingsGeneral::newPreferencePackDialogAccepted(), Gui::Dialog::DlgCustomActionsImp::onActionListWidgetItemActivated(), Gui::TreeWidget::onActivateDocument(), Gui::ViewProvider::onBeforeChange(), PartGui::SectionCut::onBFragTransparencyHSMoved(), Gui::Dialog::DlgCustomActionsImp::onButtonAddActionClicked(), Gui::Dialog::DlgCustomActionsImp::onButtonRemoveActionClicked(), Gui::Dialog::DlgCustomActionsImp::onButtonReplaceActionClicked(), Gui::ShortcutManager::OnChange(), PartDesignGui::ViewProvider::onChanged(), Gui::ViewProvider::onChanged(), Gui::BaseView::onClose(), Gui::Dialog::DlgCustomKeyboardImp::onCommandTreeWidgetCurrentItemChanged(), PathGui::ViewProviderPathShape::onDelete(), PartGui::ViewProviderCompound::onDelete(), PartGui::ViewProviderMirror::onDelete(), PartGui::ViewProviderMultiFuse::onDelete(), PathGui::ViewProviderArea::onDelete(), PartDesignGui::ViewProviderHole::onDelete(), PartGui::ViewProviderRuledSurface::onDelete(), PartDesignGui::ViewProviderSketchBased::onDelete(), PartGui::ViewProviderBoolean::onDelete(), PathGui::ViewProviderAreaView::onDelete(), PartDesignGui::ViewProviderHelix::onDelete(), PartGui::ViewProviderFillet::onDelete(), PartDesignGui::ViewProviderBoolean::onDelete(), PartDesignGui::ViewProvider::onDelete(), PartGui::ViewProviderMultiCommon::onDelete(), PartGui::ViewProviderChamfer::onDelete(), PartGui::ViewProviderRevolution::onDelete(), PartGui::ViewProviderOffset::onDelete(), PartGui::ViewProviderThickness::onDelete(), Gui::Dialog::DlgCustomKeyboardImp::onEditShortcutTextChanged(), Gui::TreeWidget::onFinishEditing(), Gui::Dialog::DemoMode::onFullscreenToggled(), TechDrawGui::ViewProviderDrawingView::onGuiRepaint(), Gui::Dialog::DlgSettingsGeneral::onImportConfigClicked(), Gui::Dialog::DlgSettingsGeneral::onLinkActivated(), SketcherGui::TaskSketcherConstraints::onListWidgetConstraintsUpdateActiveStatus(), SketcherGui::TaskSketcherConstraints::onListWidgetConstraintsUpdateDrivingStatus(), Gui::Dialog::wbListItem::onLoadClicked(), Gui::Dialog::DlgSettingsGeneral::onLoadPreferencePackClicked(), Gui::Dialog::DlgCustomToolbars::onModifyMacroAction(), PartGui::SectionCut::onRefreshCutPBclicked(), Gui::TreeWidget::onReloadDoc(), Gui::Dialog::RedoDialog::onSelected(), Gui::Dialog::UndoDialog::onSelected(), PartDesignGui::TaskBooleanParameters::onSelectionChanged(), PathGui::PathSelectionObserver::onSelectionChanged(), Gui::PropertyView::onTimer(), PartGui::FaceAppearances::open(), Gui::TaskCSysDragger::open(), Gui::Document::openEditingView3D(), StartGui::StartView::openExistingFile(), Gui::ModuleIO::openFile(), Gui::NavigationStyle::openPopupMenu(), PartGui::PropertyEnumAttacherItem::openTask(), DrawingGui::OrthoViews::OrthoViews(), Gui::OverlayTabWidget::OverlayTabWidget(), MeshGui::ViewProviderMesh::partMeshCallback(), PendingLine::PendingLine(), Gui::Dialog::DlgCustomKeyboardImp::populateCommandGroups(), Gui::Dialog::DlgCustomKeyboardImp::populateCommandList(), StartGui::StartView::postStart(), TechDrawGui::PagePrinter::print(), TechDrawGui::PagePrinter::printAll(), TechDrawGui::PagePrinter::printAllPdf(), Gui::Command::printCaller(), Gui::Command::printConflictingAccelerators(), TechDrawGui::PagePrinter::printPdf(), PartGui::FaceAppearances::Private::Private(), Gui::PropertyView::PropertyView(), SketcherGui::ViewProviderSketch::purgeHandler(), PyMOD_INIT_FUNC(), Gui::PythonCommand::PythonCommand(), Gui::PythonEditorP::PythonEditorP(), Gui::PythonGroupCommand::PythonGroupCommand(), Gui::Dialog::DlgSettingsGeneral::recreatePreferencePackMenu(), Gui::WorkbenchGroup::refreshWorkbenchList(), PartGui::ThicknessWidget::reject(), PartGui::OffsetWidget::reject(), PartGui::FaceAppearances::reject(), RobotGui::TaskDlgTrajectoryCompound::reject(), TechDrawGui::TaskLineDecor::reject(), RobotGui::TaskDlgTrajectoryDressUp::reject(), TechDrawGui::TaskProjGroup::reject(), TechDrawGui::TaskDetail::reject(), TechDrawGui::TaskCosVertex::reject(), TechDrawGui::TaskRichAnno::reject(), Gui::ElementColors::reject(), TechDrawGui::TaskLeaderLine::reject(), TechDrawGui::TaskCenterLine::reject(), PartDesignGui::TaskDlgSketchBasedParameters::reject(), PartDesignGui::TaskDlgBooleanParameters::reject(), PartDesignGui::TaskDlgFeatureParameters::reject(), Gui::TaskCSysDragger::reject(), TechDrawGui::TaskRichAnno::removeFeature(), TechDrawGui::TaskLeaderLine::removeFeature(), Gui::ShortcutManager::resetAll(), Gui::Document::resetEdit(), Gui::ViewProviderCoordinateSystem::resetTemporarySize(), Gui::Dialog::TransformStrategy::resetViewTransform(), Gui::Dialog::PlacementHandler::revertTransformation(), Gui::SelectionSingleton::rmvPreselect(), Gui::SelectionSingleton::rmvSelectionGate(), Gui::ApplicationPy::sActivateView(), Gui::ApplicationPy::sActivateWorkbenchHandler(), Gui::ApplicationPy::sActiveDocument(), Gui::ApplicationPy::sActiveView(), Gui::ApplicationPy::sActiveWorkbenchHandler(), Gui::ApplicationPy::sAddCommand(), Gui::ApplicationPy::sAddWorkbenchHandler(), Gui::Document::save(), Gui::MacroCommand::save(), Gui::Document::saveAll(), PartGui::DlgSettings3DViewPart::saveSettings(), Gui::Dialog::DlgSettingsWorkbenchesImp::saveSettings(), Gui::Dialog::DlgSettingsGeneral::saveThemes(), Gui::TreeWidget::scrollItemToTop(), Gui::ApplicationPy::sDoCommand(), Gui::ApplicationPy::sDoCommandGui(), Gui::ApplicationPy::sDoCommandSkip(), PartGui::SectionCut::SectionCut(), SurfaceGui::SectionsPanel::SectionsPanel(), Gui::ApplicationPy::sEditDocument(), MeshGui::ViewProviderMesh::segmMeshCallback(), Gui::TreeWidget::selectAll(), Gui::TreeWidget::selectAllLinks(), Gui::TreeWidget::selectLinkedObject(), FemGui::ActiveAnalysisObserver::setActiveObject(), Gui::Document::setActiveView(), Gui::MainWindow::setActiveWindow(), Gui::CommandActionPy::setattro(), SpreadsheetGui::WorkbenchHelper::setBackgroundColor(), PartDesignGui::setEdit(), SketcherGui::ViewProviderSketch::setEdit(), SurfaceGui::FillingEdgePanel::setEditedObject(), SurfaceGui::FillingVertexPanel::setEditedObject(), SurfaceGui::GeomFillSurface::setEditedObject(), SurfaceGui::SectionsPanel::setEditedObject(), SurfaceGui::FillingPanel::setEditedObject(), SketcherGui::ViewProviderSketch::setEditViewer(), MeshPartGui::Tessellation::setFaceColors(), SpreadsheetGui::WorkbenchHelper::setForegroundColor(), Gui::LinkView::setLink(), Gui::ViewProviderLink::setOverrideMode(), Gui::ViewProviderCoordinateSystem::setPlaneLabelVisibility(), Gui::SelectionSingleton::setPreselect(), PartDesignGui::ViewProviderAddSub::setPreviewDisplayMode(), Gui::ShortcutManager::setShortcut(), TechDrawGui::ViewProviderPage::setTemplateMarkers(), Gui::ViewProviderCoordinateSystem::setTemporaryScale(), Gui::ViewProviderCoordinateSystem::setTemporaryVisibility(), Gui::ToolBoxManager::setup(), Gui::ToolBarManager::setup(), PartDesignGui::Workbench::setupContextMenu(), PartDesignGui::TaskExtrudeParameters::setupDialog(), PartGui::DlgFilletEdges::setupFillet(), PartDesignGui::Workbench::setupMenuBar(), MeshGui::Workbench::setupMenuBar(), PartDesignGui::TaskTransformedParameters::setupUI(), Gui::DimensionWidget::setUserSchema(), Gui::SelectionSingleton::setVisible(), PartDesignGui::ViewProviderBody::setVisualBodyMode(), Gui::ApplicationPy::sExport(), Gui::ApplicationPy::sGetDocument(), Gui::ApplicationPy::sGetUserEditMode(), Gui::ApplicationPy::sGetWorkbenchHandler(), Gui::ApplicationPy::sHide(), Gui::ApplicationPy::sHideObject(), Gui::Dialog::DlgPreferencePackManagementImp::showAddonManager(), DrawingGui::ViewProviderDrawingPage::showDrawingView(), Gui::Dialog::DlgPreferencePackManagementImp::showEvent(), Gui::Dialog::DlgRevertToBackupConfigImp::showEvent(), SpreadsheetGui::ViewProviderSheet::showSpreadsheetView(), Gui::ApplicationPy::sListUserEditModes(), Gui::ApplicationPy::sListWorkbenchHandlers(), Gui::ApplicationPy::sLoadFile(), slotActiveDocument(), Gui::Document::slotDeletedObject(), Gui::DocumentItem::slotExpandObject(), Gui::DocumentItem::slotHighlightObject(), Gui::DocumentItem::slotInEdit(), Gui::Document::slotShowHidden(), Gui::Document::slotSkipRecompute(), SketcherGui::ViewProviderSketch::slotSolverUpdate(), TechDrawGui::QGIDatumLabel::snapPosition(), SpreadsheetGui::SheetTableView::splitCell(), Gui::ApplicationPy::sReload(), Gui::ApplicationPy::sRemoveWorkbenchHandler(), Gui::ApplicationPy::sRunCommand(), Gui::ApplicationPy::sSendActiveView(), Gui::ApplicationPy::sSendFocusView(), Gui::ApplicationPy::sSetActiveDocument(), Gui::ApplicationPy::sSetUserEditMode(), Gui::ApplicationPy::sShow(), Gui::ApplicationPy::sShowObject(), PartDesignGui::ViewProviderTransformed::startEditing(), Gui::ViewProviderLink::startEditing(), Gui::TreeWidget::startItemSearch(), Gui::TaskView::TaskAppearance::TaskAppearance(), PartGui::TaskAttacher::TaskAttacher(), PartDesignGui::TaskBooleanParameters::TaskBooleanParameters(), PartDesignGui::TaskBoxPrimitives::TaskBoxPrimitives(), TechDrawGui::TaskCosVertex::TaskCosVertex(), FemGui::TaskCreateElementSet::TaskCreateElementSet(), FemGui::TaskCreateNodeSet::TaskCreateNodeSet(), TechDrawGui::TaskDetail::TaskDetail(), PartDesignGui::TaskFeaturePick::TaskFeaturePick(), TechDrawGui::TaskLeaderLine::TaskLeaderLine(), PartDesignGui::TaskLoftParameters::TaskLoftParameters(), SandboxGui::TaskPanelView::TaskPanelView(), PartDesignGui::TaskPipeOrientation::TaskPipeOrientation(), PartDesignGui::TaskPipeParameters::TaskPipeParameters(), PartDesignGui::TaskPipeScaling::TaskPipeScaling(), FemGui::TaskPostClip::TaskPostClip(), FemGui::TaskPostCut::TaskPostCut(), TechDrawGui::TaskProjGroup::TaskProjGroup(), TechDrawGui::TaskRichAnno::TaskRichAnno(), RobotGui::TaskTrajectory::TaskTrajectory(), Gui::TaskView::TaskView::TaskView(), Gui::TaskView::TaskWatcherCommands::TaskWatcherCommands(), Gui::TaskView::TaskWatcherPython::TaskWatcherPython(), Gui::Command::testActive(), StartGui::ThemeSelectorWidget::themeChanged(), RobotGui::TrajectorySimulate::TrajectorySimulate(), Gui::TreeWidget::TreeWidget(), MeshGui::ViewProviderMesh::trimMeshCallback(), TechDrawGui::TaskProjGroup::turnProjGroupToView(), PartDesignGui::ViewProviderBody::unifyVisualProperty(), PartDesignGui::ViewProvider::unsetEdit(), Gui::Command::updateAll(), FemGui::ViewProviderFemPostPipeline::updateColorBars(), TechDrawGui::ViewProviderTemplate::updateData(), RobotGui::ViewProviderRobotObject::updateData(), PartDesignGui::ViewProviderBody::updateData(), DrawingGui::ViewProviderDrawingPage::updateData(), PathGui::ViewProviderPathShape::updateData(), PartGui::ViewProviderMultiFuse::updateData(), PathGui::ViewProviderArea::updateData(), PartGui::ViewProviderBoolean::updateData(), PathGui::ViewProviderAreaView::updateData(), PartGui::ViewProviderCompound::updateData(), PartGui::ViewProviderFillet::updateData(), MeshGui::ViewProviderMeshCurvature::updateData(), PartGui::ViewProviderMultiCommon::updateData(), PartGui::ViewProviderChamfer::updateData(), Gui::ViewProviderLink::updateDataPrivate(), Gui::MainWindow::updateEditorActions(), Gui::ViewProviderLink::updateElementList(), FemGui::ViewProviderFemPostPipeline::updateFunctionSize(), TechDrawGui::ViewProviderGeomHatch::updateGraphic(), FemGui::ViewProviderFemPostFunctionProvider::updateSize(), Gui::DAG::View::View(), Gui::View3DInventorViewer::viewSelection(), InspectionGui::VisualInspection::VisualInspection(), Gui::Dialog::wbListItem::wbListItem(), Gui::WorkbenchGroup::WorkbenchGroup(), PartGui::DlgProjectionOnSurface::~DlgProjectionOnSurface(), PartGui::SectionCut::~SectionCut(), SpreadsheetGui::SheetView::~SheetView(), PartDesignGui::TaskBoxPrimitives::~TaskBoxPrimitives(), PartDesignGui::TaskHelixParameters::~TaskHelixParameters(), PartDesignGui::TaskLinearPatternParameters::~TaskLinearPatternParameters(), PartDesignGui::TaskMirroredParameters::~TaskMirroredParameters(), PartDesignGui::TaskPolarPatternParameters::~TaskPolarPatternParameters(), and Gui::TaskTransform::~TaskTransform().
signalActivatedObject
boost::signals2::signal<void (const Gui::ViewProvider&)> Gui::Application::signalActivatedObject
signal on activated Object
Definition at line 134 of file Gui/Application.h.
signalActivateView
boost::signals2::signal<void (const Gui::MDIView*)> Gui::Application::signalActivateView
signal on activating view
Definition at line 142 of file Gui/Application.h.
Referenced by StdCmdDrawStyle::StdCmdDrawStyle().
signalActivateWorkbench
boost::signals2::signal<void (const char*)> Gui::Application::signalActivateWorkbench
signal on activated workbench
Definition at line 136 of file Gui/Application.h.
signalActiveDocument
boost::signals2::signal<void (const Gui::Document&)> Gui::Application::signalActiveDocument
signal on activating Document
Definition at line 122 of file Gui/Application.h.
Referenced by Gui::DocumentModel::DocumentModel(), Gui::PropertyView::PropertyView(), Gui::TreeWidget::TreeWidget(), and Gui::DAG::View::View().
signalBeforeChangeObject
boost::signals2::signal<void (const Gui::ViewProvider&, const App::Property&)> Gui::Application::signalBeforeChangeObject
signal on changed Object
Definition at line 128 of file Gui/Application.h.
Referenced by Gui::ViewProvider::onBeforeChange().
signalChangedObject
boost::signals2::signal<void (const Gui::ViewProvider&, const App::Property&)> Gui::Application::signalChangedObject
signal on changed object property
Definition at line 130 of file Gui/Application.h.
Referenced by MatGui::DlgDisplayPropertiesImp::DlgDisplayPropertiesImp(), MatGui::DlgMaterialImp::DlgMaterialImp(), Gui::ViewProvider::onChanged(), Gui::PropertyView::PropertyView(), Gui::TaskView::TaskAppearance::TaskAppearance(), and Gui::TreeWidget::TreeWidget().
signalCloseView
boost::signals2::signal<void (const Gui::MDIView*)> Gui::Application::signalCloseView
signal on closing view
Definition at line 144 of file Gui/Application.h.
Referenced by Gui::TaskView::TaskView::TaskView().
signalDeletedObject
boost::signals2::signal<void (const Gui::ViewProvider&)> Gui::Application::signalDeletedObject
signal on deleted Object
Definition at line 126 of file Gui/Application.h.
Referenced by Gui::ElementColors::ElementColors(), PartGui::FaceAppearances::FaceAppearances(), and Gui::PropertyView::PropertyView().
signalDeleteDocument
boost::signals2::signal<void (const Gui::Document&)> Gui::Application::signalDeleteDocument
signal on deleted Document
Definition at line 116 of file Gui/Application.h.
Referenced by Gui::DocumentModel::DocumentModel(), Gui::ElementColors::ElementColors(), PartGui::FaceAppearances::FaceAppearances(), Gui::ManualAlignment::ManualAlignment(), Gui::PropertyView::PropertyView(), Gui::TreeWidget::TreeWidget(), and Gui::DAG::View::View().
signalInEdit
boost::signals2::signal<void (const Gui::ViewProviderDocumentObject&)> Gui::Application::signalInEdit
signal on entering in edit mode
Definition at line 146 of file Gui/Application.h.
signalNewDocument
boost::signals2::signal<void (const Gui::Document&, bool)> Gui::Application::signalNewDocument
signal on new Document
Definition at line 114 of file Gui/Application.h.
Referenced by Gui::DocumentModel::DocumentModel(), and Gui::TreeWidget::TreeWidget().
signalNewObject
boost::signals2::signal<void (const Gui::ViewProvider&)> Gui::Application::signalNewObject
signal on new Object
Definition at line 124 of file Gui/Application.h.
signalRefreshWorkbenches
boost::signals2::signal<void ()> Gui::Application::signalRefreshWorkbenches
signal on added/removed workbench
Definition at line 138 of file Gui/Application.h.
Referenced by Gui::ApplicationPy::sAddWorkbenchHandler(), Gui::Dialog::DlgSettingsWorkbenchesImp::saveSettings(), Gui::ApplicationPy::sRemoveWorkbenchHandler(), and Gui::WorkbenchGroup::WorkbenchGroup().
signalRelabelDocument
boost::signals2::signal<void (const Gui::Document&)> Gui::Application::signalRelabelDocument
signal on relabeling Document
Definition at line 118 of file Gui/Application.h.
Referenced by Gui::DocumentModel::DocumentModel(), and Gui::TreeWidget::TreeWidget().
signalRelabelObject
boost::signals2::signal<void (const Gui::ViewProvider&)> Gui::Application::signalRelabelObject
signal on renamed Object
Definition at line 132 of file Gui/Application.h.
signalRenameDocument
boost::signals2::signal<void (const Gui::Document&)> Gui::Application::signalRenameDocument
signal on renaming Document
Definition at line 120 of file Gui/Application.h.
Referenced by Gui::DocumentModel::DocumentModel(), and Gui::TreeWidget::TreeWidget().
signalResetEdit
boost::signals2::signal<void (const Gui::ViewProviderDocumentObject&)> Gui::Application::signalResetEdit
signal on leaving edit mode
Definition at line 148 of file Gui/Application.h.
signalShowHidden
boost::signals2::signal<void (const Gui::Document&)> Gui::Application::signalShowHidden
signal on show hidden items
Definition at line 140 of file Gui/Application.h.
Referenced by Gui::Document::slotShowHidden(), and Gui::TreeWidget::TreeWidget().
signalUserEditModeChanged
boost::signals2::signal<void (int)> Gui::Application::signalUserEditModeChanged
signal on changing user edit mode
Definition at line 150 of file Gui/Application.h.
Referenced by StdCmdUserEditMode::StdCmdUserEditMode().
userEditMode
int Gui::Application::userEditMode = userEditModes.begin()->first protected
Definition at line 287 of file Gui/Application.h.
userEditModes
const std::map<int, std::pair<std::string, std::string> > Gui::Application::userEditModes protected
Initial value:
{
        {0,
         std::make_pair(
             QT_TRANSLATE_NOOP("EditMode", "&Default"),
             QT_TRANSLATE_NOOP("EditMode",
                               "The object will be edited using the mode defined internally to be "
                               "the most appropriate for the object type"))},
        {1,
         std::make_pair(QT_TRANSLATE_NOOP("EditMode", "Trans&form"),
                        QT_TRANSLATE_NOOP("EditMode",
                                          "The object will have its placement editable with the "
                                          "Std TransformManip command"))},
        {2,
         std::make_pair(QT_TRANSLATE_NOOP("EditMode", "Cu&tting"),
                        QT_TRANSLATE_NOOP("EditMode",
                                          "This edit mode is implemented as available but "
                                          "currently does not seem to be used by any object"))},
        {3,
         std::make_pair(QT_TRANSLATE_NOOP("EditMode", "&Color"),
                        QT_TRANSLATE_NOOP("EditMode",
                                          "The object will have the color of its individual faces "
                                          "editable with the Part FaceAppearances command"))},
    }
Definition at line 264 of file Gui/Application.h.
The documentation for this class was generated from the following files:
Gui/Application.h
Gui/Application.cpp