FreeCAD: MeshCore::FlatTriangulator Class Reference
MeshCore::FlatTriangulator Class Reference
#include <Triangulation.h>
Public Member Functions
FlatTriangulator ()
void PostProcessing (const std::vector< Base::Vector3f > &) override
Public Member Functions inherited from MeshCore::AbstractPolygonTriangulator
AbstractPolygonTriangulator ()
virtual ~AbstractPolygonTriangulator ()
AbstractPolygonTriangulator (const AbstractPolygonTriangulator &)=delete
AbstractPolygonTriangulator (AbstractPolygonTriangulator &&)=delete
AbstractPolygonTriangulator & operator= (const AbstractPolygonTriangulator &)=delete
AbstractPolygonTriangulator & operator= (AbstractPolygonTriangulator &&)=delete
void SetPolygon (const std::vector< Base::Vector3f > &raclPoints)
void SetIndices (const std::vector< PointIndex > &d)
void SetVerifier (TriangulationVerifier *v)
TriangulationVerifier * GetVerifier () const
virtual bool NeedsReindexing () const
std::vector< Base::Vector3f > GetPolygon () const
std::vector< Base::Vector3f > AddedPoints () const
Base::Matrix4D GetTransformToFitPlane () const
std::vector< Base::Vector3f > ProjectToFitPlane ()
bool TriangulatePolygon ()
const std::vector< MeshGeomFacet > & GetTriangles () const
const std::vector< MeshFacet > & GetFacets () const
virtual MeshGeomFacet GetTriangle (const MeshPointArray &, const MeshFacet &) const
float GetLength () const
std::vector< PointIndex > GetInfo () const
virtual void Discard ()
virtual void Reset ()
Protected Member Functions
bool Triangulate () override
Protected Member Functions inherited from MeshCore::AbstractPolygonTriangulator
void Done ()
Additional Inherited Members
Protected Attributes inherited from MeshCore::AbstractPolygonTriangulator
bool _discard
Base::Matrix4D _inverse
std::vector< PointIndex > _indices
std::vector< Base::Vector3f > _points
std::vector< Base::Vector3f > _newpoints
std::vector< MeshGeomFacet > _triangles
std::vector< MeshFacet > _facets
std::vector< PointIndex > _info
TriangulationVerifier * _verifier
Detailed Description
Definition at line 255 of file Triangulation.h.
Constructor & Destructor Documentation
FlatTriangulator()
FlatTriangulator::FlatTriangulator () default
Member Function Documentation
PostProcessing()
void FlatTriangulator::PostProcessing (const std::vector< Base::Vector3f > & points) override virtual
If points were added then we get the 3D points by projecting the added 2D points onto a surface which fits into the given points.
Reimplemented from MeshCore::AbstractPolygonTriangulator.
Definition at line 785 of file Triangulation.cpp.
Triangulate()
bool FlatTriangulator::Triangulate () override protected virtual
Computes the triangulation of a polygon. The resulting facets can be accessed by GetTriangles() or GetFacets().
Implements MeshCore::AbstractPolygonTriangulator.
Definition at line 758 of file Triangulation.cpp.
References MeshCore::AbstractPolygonTriangulator::_facets, MeshCore::AbstractPolygonTriangulator::_newpoints, MeshCore::AbstractPolygonTriangulator::_triangles, MeshCore::AbstractPolygonTriangulator::GetFacets(), MeshCore::AbstractPolygonTriangulator::GetPolygon(), MeshCore::AbstractPolygonTriangulator::GetTriangles(), MeshCore::AbstractPolygonTriangulator::ProjectToFitPlane(), MeshCore::AbstractPolygonTriangulator::SetPolygon(), and MeshCore::AbstractPolygonTriangulator::TriangulatePolygon().
The documentation for this class was generated from the following files:
Triangulation.h
Triangulation.cpp