FreeCAD: Gui::OverlayProxyWidget Class Reference
Gui::OverlayProxyWidget Class Reference
#include <OverlayWidgets.h>
Public Types
enum HitTest { HitTest::HitNone = 0, HitTest::HitOuter = 1, HitTest::HitInner = 2 }
For representing hit region.
Public Member Functions
OverlayProxyWidget (OverlayTabWidget *)
OverlayTabWidget * getOwner () const
HitTest hitTest (const QPoint &pos, bool delay=true)
bool isActivated () const
Check if the visual hint is showing.
QBrush hintColor () const
void setHintColor (const QBrush &)
QRect getRect () const
void onMousePress ()
Protected Member Functions
void enterEvent (QEnterEvent *ev) override
void hideEvent (QHideEvent *ev) override
void paintEvent (QPaintEvent *ev) override
void onTimer ()
Properties
QBrush hintColor
Detailed Description
Class for handling visual hint for bringing back hidden overlay dock widget
The proxy widget is transparent except a customizable rectangle area with a selectable color shown as the visual hint. The hint is normally hidden, and is shown only if the mouse hovers within the widget. When the hint area is clicked, it will bring back hidden overlay dock panel. Note that the proxy widget itself is mouse transparent as well, meaning that it will not receive any mouse event. It is handled in the OverlayManager event filter.
Definition at line 547 of file OverlayWidgets.h.
Member Enumeration Documentation
HitTest
enum Gui::OverlayProxyWidget::HitTest strong
For representing hit region.
Enumerator
HitNone
Not hitting.
HitOuter
Hitting the proxy widget size but not within the visible hint area.
HitInner
Hitting the visible hint area.
Definition at line 559 of file OverlayWidgets.h.
Constructor & Destructor Documentation
OverlayProxyWidget()
OverlayProxyWidget::OverlayProxyWidget (OverlayTabWidget * tabOverlay) explicit
Definition at line 94 of file OverlayWidgets.cpp.
References draftgeoutils.intersections::connect(), Gui::OverlayTabWidget::getDockArea(), and onTimer().
Member Function Documentation
enterEvent()
void OverlayProxyWidget::enterEvent (QEnterEvent * ev) override protected
Definition at line 226 of file OverlayWidgets.cpp.
References importDXF::drawLine(), Gui::OverlayParams::getDockOverlayHintDelay(), and PersistentToolbarsGui::timer.
getOwner()
OverlayTabWidget* Gui::OverlayProxyWidget::getOwner () const inline
Definition at line 556 of file OverlayWidgets.h.
getRect()
QRect OverlayProxyWidget::getRect () const
Definition at line 264 of file OverlayWidgets.cpp.
References Gui::OverlayParams::getDockOverlayHintBottomLength(), Gui::OverlayParams::getDockOverlayHintBottomOffset(), Gui::OverlayParams::getDockOverlayHintLeftLength(), Gui::OverlayParams::getDockOverlayHintLeftOffset(), Gui::OverlayParams::getDockOverlayHintRightLength(), Gui::OverlayParams::getDockOverlayHintRightOffset(), Gui::OverlayParams::getDockOverlayHintTopLength(), Gui::OverlayParams::getDockOverlayHintTopOffset(), KDL::max(), and KDL::min().
Referenced by hitTest(), and paintEvent().
hideEvent()
void OverlayProxyWidget::hideEvent (QHideEvent * ev) override protected
Definition at line 238 of file OverlayWidgets.cpp.
hintColor()
QBrush Gui::OverlayProxyWidget::hintColor () const
hitTest()
OverlayProxyWidget::HitTest OverlayProxyWidget::hitTest (const QPoint & pos, bool delay = true)
Mouse cursor hit test
Parameters
pos cursor position
delay Whether to delay showing hint on mouse hit
Definition at line 108 of file OverlayWidgets.cpp.
References Gui::MainWindow::activeWindow(), Gui::OverlayParams::getDockOverlayActivateOnHover(), Gui::OverlayParams::getDockOverlayHintDelay(), Gui::OverlayParams::getDockOverlayHintTriggerSize(), Gui::getMainWindow(), getRect(), Gui::OverlayTabWidget::getState(), Gui::OverlayTabWidget::Hidden, Gui::ToolTip::hideText(), Gui::OverlayTabWidget::Hint, Gui::OverlayTabWidget::HintHidden, HitInner, HitNone, HitOuter, Gui::OverlayTabWidget::Normal, Gui::MDIView::onHasMsg(), RobotExample::pos, toolbit-attributes::s, Gui::OverlayTabWidget::setState(), Gui::OverlayTabWidget::Showing, and Gui::ToolTip::showText().
Referenced by onTimer().
isActivated()
bool OverlayProxyWidget::isActivated () const
Check if the visual hint is showing.
Definition at line 103 of file OverlayWidgets.cpp.
onMousePress()
void OverlayProxyWidget::onMousePress ()
Definition at line 243 of file OverlayWidgets.cpp.
References Gui::OverlayTabWidget::getState(), Gui::OverlayTabWidget::HintHidden, Gui::OverlayTabWidget::setState(), and Gui::OverlayTabWidget::Showing.
onTimer()
void OverlayProxyWidget::onTimer () protected
Definition at line 218 of file OverlayWidgets.cpp.
References hitTest(), and RobotExample::pos.
Referenced by OverlayProxyWidget().
paintEvent()
void OverlayProxyWidget::paintEvent (QPaintEvent * ev) override protected
Definition at line 316 of file OverlayWidgets.cpp.
References getRect().
setHintColor()
void OverlayProxyWidget::setHintColor (const QBrush & brush)
Definition at line 259 of file OverlayWidgets.cpp.
Property Documentation
hintColor
QBrush OverlayProxyWidget::hintColor read write
Definition at line 551 of file OverlayWidgets.h.
The documentation for this class was generated from the following files:
OverlayWidgets.h
OverlayWidgets.cpp