FreeCAD: TechDrawGui::QGVNavStyle Class Reference
TechDrawGui::QGVNavStyle Class Reference
#include <QGVNavStyle.h>
Public Member Functions
QGVNavStyle (QGVPage *qgvp)
~QGVNavStyle () override
void setViewer (QGVPage *qgvp)
QGVPage * getViewer ()
virtual void handleEnterEvent (QEvent *event)
virtual void handleFocusOutEvent (QFocusEvent *event)
virtual void handleKeyPressEvent (QKeyEvent *event)
virtual void handleKeyReleaseEvent (QKeyEvent *event)
virtual void handleLeaveEvent (QEvent *event)
virtual void handleMouseMoveEvent (QMouseEvent *event)
virtual void handleMousePressEvent (QMouseEvent *event)
virtual void handleMouseReleaseEvent (QMouseEvent *event)
virtual void handleWheelEvent (QWheelEvent *event)
virtual bool allowContextMenu (QContextMenuEvent *event)
virtual void pseudoContextEvent ()
virtual void startZoom (QPoint p)
virtual void zoom (double factor)
virtual void stopZoom ()
virtual double mouseZoomFactor (QPoint p)
virtual void zoomIn ()
virtual void zoomOut ()
virtual void startPan (QPoint p)
virtual void pan (QPoint p)
virtual void stopPan ()
virtual void startClick (Qt::MouseButton b)
virtual void stopClick ()
virtual void placeBalloon (QPoint p)
virtual void balloonCursorMovement (QMouseEvent *event)
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Member Functions
virtual void initialize ()
virtual void setAnchor ()
Protected Attributes
QGVPage * m_viewer
int m_currentmode
bool ctrldown
bool shiftdown
bool altdown
bool button1down
bool button2down
bool button3down
bool invertZoom
bool zoomAtCursor
double zoomStep
int m_reversePan
int m_reverseScroll
QPoint panOrigin
bool panningActive
QPoint zoomOrigin
bool zoomingActive
bool m_clickPending
bool m_panPending
bool m_zoomPending
Qt::MouseButton m_clickButton
KeyCombination m_keyCombo
QCursor m_saveCursor
int m_wheelDeltaCounter
int m_mouseDeltaCounter
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 62 of file QGVNavStyle.h.
Constructor & Destructor Documentation
QGVNavStyle()
TechDrawGui::QGVNavStyle::QGVNavStyle (QGVPage * qgvp) explicit
Definition at line 46 of file QGVNavStyle.cpp.
References initialize().
~QGVNavStyle()
TechDrawGui::QGVNavStyle::~QGVNavStyle () override
Definition at line 48 of file QGVNavStyle.cpp.
Member Function Documentation
allowContextMenu()
bool TechDrawGui::QGVNavStyle::allowContextMenu (QContextMenuEvent * event) virtual
Reimplemented in TechDrawGui::QGVNavStyleBlender, TechDrawGui::QGVNavStyleCAD, TechDrawGui::QGVNavStyleOCC, TechDrawGui::QGVNavStyleMaya, TechDrawGui::QGVNavStyleOpenSCAD, TechDrawGui::QGVNavStyleGesture, and TechDrawGui::QGVNavStyleRevit.
Definition at line 253 of file QGVNavStyle.cpp.
Referenced by TechDrawGui::QGVPage::contextMenuEvent().
balloonCursorMovement()
void TechDrawGui::QGVNavStyle::balloonCursorMovement (QMouseEvent * event) virtual
Definition at line 402 of file QGVNavStyle.cpp.
References getViewer(), and TechDrawGui::QGVPage::setBalloonCursorPos().
Referenced by TechDrawGui::QGVNavStyleGesture::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleInventor::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleRevit::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleTouchpad::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOCC::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleMaya::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleBlender::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleTinkerCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleCAD::handleMouseMoveEvent(), and handleMouseMoveEvent().
getViewer()
QGVPage* TechDrawGui::QGVNavStyle::getViewer () inline
Definition at line 69 of file QGVNavStyle.h.
Referenced by balloonCursorMovement(), handleEnterEvent(), handleFocusOutEvent(), handleKeyPressEvent(), handleLeaveEvent(), TechDrawGui::QGVNavStyleGesture::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleInventor::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleRevit::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleBlender::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleTinkerCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleTouchpad::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleMaya::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOCC::handleMouseMoveEvent(), handleMouseMoveEvent(), TechDrawGui::QGVNavStyleInventor::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleRevit::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleGesture::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleBlender::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleCAD::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleMaya::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleOCC::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleTinkerCAD::handleMouseReleaseEvent(), handleMouseReleaseEvent(), initialize(), pan(), placeBalloon(), pseudoContextEvent(), startPan(), startZoom(), stopPan(), stopZoom(), and zoom().
handleEnterEvent()
void TechDrawGui::QGVNavStyle::handleEnterEvent (QEvent * event) virtual
Definition at line 96 of file QGVNavStyle.cpp.
References TechDrawGui::QGVPage::getBalloonCursor(), and getViewer().
handleFocusOutEvent()
void TechDrawGui::QGVNavStyle::handleFocusOutEvent (QFocusEvent * event) virtual
Definition at line 104 of file QGVNavStyle.cpp.
References TechDrawGui::QGVPage::cancelBalloonPlacing(), and getViewer().
Referenced by TechDrawGui::QGVPage::focusOutEvent().
handleKeyPressEvent()
void TechDrawGui::QGVNavStyle::handleKeyPressEvent (QKeyEvent * event) virtual
Reimplemented in TechDrawGui::QGVNavStyleTouchpad.
Definition at line 110 of file QGVNavStyle.cpp.
References TechDrawGui::QGVPage::cancelBalloonPlacing(), getViewer(), TechDrawGui::QGVPage::kbPanScroll(), shiftdown, zoomIn(), and zoomOut().
Referenced by TechDrawGui::QGVNavStyleTouchpad::handleKeyPressEvent(), and TechDrawGui::QGVPage::keyPressEvent().
handleKeyReleaseEvent()
void TechDrawGui::QGVNavStyle::handleKeyReleaseEvent (QKeyEvent * event) virtual
Reimplemented in TechDrawGui::QGVNavStyleTouchpad, TechDrawGui::QGVNavStyleBlender, TechDrawGui::QGVNavStyleCAD, TechDrawGui::QGVNavStyleMaya, TechDrawGui::QGVNavStyleOCC, and TechDrawGui::QGVNavStyleOpenSCAD.
Definition at line 171 of file QGVNavStyle.cpp.
References shiftdown.
Referenced by TechDrawGui::QGVPage::keyReleaseEvent().
handleLeaveEvent()
void TechDrawGui::QGVNavStyle::handleLeaveEvent (QEvent * event) virtual
Definition at line 187 of file QGVNavStyle.cpp.
References TechDrawGui::QGVPage::getBalloonCursor(), TechDrawGui::QGVPage::getBalloonCursorPos(), getViewer(), MovieTool::x, and MovieTool::y.
Referenced by TechDrawGui::QGVPage::leaveEvent().
handleMouseMoveEvent()
void TechDrawGui::QGVNavStyle::handleMouseMoveEvent (QMouseEvent * event) virtual
Reimplemented in TechDrawGui::QGVNavStyleBlender, TechDrawGui::QGVNavStyleCAD, TechDrawGui::QGVNavStyleMaya, TechDrawGui::QGVNavStyleOCC, TechDrawGui::QGVNavStyleTinkerCAD, TechDrawGui::QGVNavStyleTouchpad, TechDrawGui::QGVNavStyleGesture, TechDrawGui::QGVNavStyleInventor, TechDrawGui::QGVNavStyleOpenSCAD, and TechDrawGui::QGVNavStyleRevit.
Definition at line 224 of file QGVNavStyle.cpp.
References balloonCursorMovement(), getViewer(), pan(), and panningActive.
Referenced by TechDrawGui::QGVPage::mouseMoveEvent().
handleMousePressEvent()
void TechDrawGui::QGVNavStyle::handleMousePressEvent (QMouseEvent * event) virtual
Reimplemented in TechDrawGui::QGVNavStyleTinkerCAD, TechDrawGui::QGVNavStyleOpenSCAD, TechDrawGui::QGVNavStyleBlender, TechDrawGui::QGVNavStyleCAD, TechDrawGui::QGVNavStyleMaya, TechDrawGui::QGVNavStyleOCC, TechDrawGui::QGVNavStyleGesture, TechDrawGui::QGVNavStyleInventor, and TechDrawGui::QGVNavStyleRevit.
Definition at line 215 of file QGVNavStyle.cpp.
References panningActive, and startPan().
Referenced by TechDrawGui::QGVPage::mousePressEvent().
handleMouseReleaseEvent()
void TechDrawGui::QGVNavStyle::handleMouseReleaseEvent (QMouseEvent * event) virtual
Reimplemented in TechDrawGui::QGVNavStyleTinkerCAD, TechDrawGui::QGVNavStyleBlender, TechDrawGui::QGVNavStyleCAD, TechDrawGui::QGVNavStyleMaya, TechDrawGui::QGVNavStyleOCC, TechDrawGui::QGVNavStyleOpenSCAD, TechDrawGui::QGVNavStyleGesture, TechDrawGui::QGVNavStyleInventor, and TechDrawGui::QGVNavStyleRevit.
Definition at line 240 of file QGVNavStyle.cpp.
References getViewer(), panningActive, placeBalloon(), and stopPan().
Referenced by TechDrawGui::QGVPage::mouseReleaseEvent().
handleWheelEvent()
void TechDrawGui::QGVNavStyle::handleWheelEvent (QWheelEvent * event) virtual
Definition at line 265 of file QGVNavStyle.cpp.
References KDL::abs(), invertZoom, m_wheelDeltaCounter, zoom(), and zoomStep.
Referenced by TechDrawGui::QGVPage::wheelEvent().
initialize()
void TechDrawGui::QGVNavStyle::initialize () protected virtual
Definition at line 50 of file QGVNavStyle.cpp.
References altdown, button1down, button2down, button3down, ctrldown, SCL.SimpleDataTypes::f, App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetFloat(), App::Application::GetParameterGroupByPath(), getViewer(), invertZoom, m_clickButton, m_clickPending, m_mouseDeltaCounter, m_panPending, m_reversePan, m_reverseScroll, m_saveCursor, m_wheelDeltaCounter, m_zoomPending, panningActive, shiftdown, zoomAtCursor, zoomingActive, and zoomStep.
Referenced by QGVNavStyle().
mouseZoomFactor()
double TechDrawGui::QGVNavStyle::mouseZoomFactor (QPoint p) virtual
Definition at line 323 of file QGVNavStyle.cpp.
References KDL::abs(), invertZoom, m_mouseDeltaCounter, buildPsets::p, MovieTool::y, zoomOrigin, and zoomStep.
Referenced by TechDrawGui::QGVNavStyleInventor::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOCC::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleMaya::handleMouseMoveEvent(), and TechDrawGui::QGVNavStyleTouchpad::handleMouseMoveEvent().
pan()
void TechDrawGui::QGVNavStyle::pan (QPoint p) virtual
Definition at line 360 of file QGVNavStyle.cpp.
References getViewer(), m_reversePan, m_reverseScroll, buildPsets::p, and panOrigin.
Referenced by TechDrawGui::QGVNavStyleGesture::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleInventor::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleRevit::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleTouchpad::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOCC::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleMaya::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleBlender::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleTinkerCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleCAD::handleMouseMoveEvent(), and handleMouseMoveEvent().
placeBalloon()
void TechDrawGui::QGVNavStyle::placeBalloon (QPoint p) virtual
Definition at line 392 of file QGVNavStyle.cpp.
References TechDrawGui::QGSPage::createBalloon(), TechDrawGui::QGVPage::getBalloonCursor(), TechDrawGui::QGVPage::getScene(), getViewer(), buildPsets::p, and TechDrawGui::QGVPage::setBalloonPlacing().
Referenced by TechDrawGui::QGVNavStyleGesture::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleInventor::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleRevit::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleOCC::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleMaya::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleBlender::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleCAD::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleTinkerCAD::handleMouseReleaseEvent(), and handleMouseReleaseEvent().
pseudoContextEvent()
void TechDrawGui::QGVNavStyle::pseudoContextEvent () virtual
Definition at line 263 of file QGVNavStyle.cpp.
References getViewer(), and TechDrawGui::QGVPage::pseudoContextEvent().
Referenced by TechDrawGui::QGVNavStyleGesture::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleRevit::handleMouseReleaseEvent(), and TechDrawGui::QGVNavStyleOpenSCAD::handleMouseReleaseEvent().
setAnchor()
void TechDrawGui::QGVNavStyle::setAnchor () protected virtual
Reimplemented in TechDrawGui::QGVNavStyleTouchpad.
Definition at line 82 of file QGVNavStyle.cpp.
References m_viewer, and zoomAtCursor.
Referenced by zoom().
setViewer()
void TechDrawGui::QGVNavStyle::setViewer (QGVPage * qgvp) inline
Definition at line 68 of file QGVNavStyle.h.
startClick()
void TechDrawGui::QGVNavStyle::startClick (Qt::MouseButton b) virtual
Definition at line 380 of file QGVNavStyle.cpp.
References SCL.SimpleDataTypes::b, m_clickButton, and m_clickPending.
Referenced by TechDrawGui::QGVNavStyleGesture::handleMousePressEvent(), TechDrawGui::QGVNavStyleRevit::handleMousePressEvent(), TechDrawGui::QGVNavStyleCAD::handleMousePressEvent(), and TechDrawGui::QGVNavStyleOpenSCAD::handleMousePressEvent().
startPan()
void TechDrawGui::QGVNavStyle::startPan (QPoint p) virtual
Definition at line 352 of file QGVNavStyle.cpp.
References getViewer(), m_panPending, buildPsets::p, panningActive, panOrigin, and TechDrawGui::QGVPage::setPanCursor().
Referenced by TechDrawGui::QGVNavStyleGesture::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleInventor::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleRevit::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleTouchpad::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOCC::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleMaya::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleBlender::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleTinkerCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleCAD::handleMouseMoveEvent(), and handleMousePressEvent().
startZoom()
void TechDrawGui::QGVNavStyle::startZoom (QPoint p) virtual
Definition at line 306 of file QGVNavStyle.cpp.
References getViewer(), m_zoomPending, buildPsets::p, TechDrawGui::QGVPage::setZoomCursor(), zoomingActive, and zoomOrigin.
Referenced by TechDrawGui::QGVNavStyleInventor::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOCC::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleMaya::handleMouseMoveEvent(), and TechDrawGui::QGVNavStyleTouchpad::handleMouseMoveEvent().
stopClick()
void TechDrawGui::QGVNavStyle::stopClick () virtual
Definition at line 386 of file QGVNavStyle.cpp.
References m_clickButton, and m_clickPending.
Referenced by TechDrawGui::QGVNavStyleGesture::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleRevit::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleGesture::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleRevit::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseReleaseEvent(), and TechDrawGui::QGVNavStyleCAD::handleMouseReleaseEvent().
stopPan()
void TechDrawGui::QGVNavStyle::stopPan () virtual
Definition at line 372 of file QGVNavStyle.cpp.
References getViewer(), m_panPending, panningActive, and TechDrawGui::QGVPage::resetCursor().
Referenced by TechDrawGui::QGVNavStyleBlender::handleKeyReleaseEvent(), TechDrawGui::QGVNavStyleCAD::handleKeyReleaseEvent(), TechDrawGui::QGVNavStyleMaya::handleKeyReleaseEvent(), TechDrawGui::QGVNavStyleOCC::handleKeyReleaseEvent(), TechDrawGui::QGVNavStyleTouchpad::handleKeyReleaseEvent(), TechDrawGui::QGVNavStyleTouchpad::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleInventor::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleRevit::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleGesture::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleOCC::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleCAD::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleMaya::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleBlender::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleTinkerCAD::handleMouseReleaseEvent(), and handleMouseReleaseEvent().
stopZoom()
void TechDrawGui::QGVNavStyle::stopZoom () virtual
Definition at line 315 of file QGVNavStyle.cpp.
References getViewer(), m_zoomPending, TechDrawGui::QGVPage::resetCursor(), and zoomingActive.
Referenced by TechDrawGui::QGVNavStyleCAD::handleKeyReleaseEvent(), TechDrawGui::QGVNavStyleOCC::handleKeyReleaseEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleKeyReleaseEvent(), TechDrawGui::QGVNavStyleTouchpad::handleKeyReleaseEvent(), TechDrawGui::QGVNavStyleTouchpad::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseReleaseEvent(), and TechDrawGui::QGVNavStyleOCC::handleMouseReleaseEvent().
zoom()
void TechDrawGui::QGVNavStyle::zoom (double factor) virtual
Definition at line 291 of file QGVNavStyle.cpp.
References getViewer(), m_zoomPending, and setAnchor().
Referenced by TechDrawGui::QGVNavStyleInventor::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleTouchpad::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOCC::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleMaya::handleMouseMoveEvent(), handleWheelEvent(), zoomIn(), and zoomOut().
zoomIn()
void TechDrawGui::QGVNavStyle::zoomIn () virtual
Definition at line 342 of file QGVNavStyle.cpp.
References zoom(), and zoomStep.
Referenced by TechDrawGui::QGVNavStyleTouchpad::handleKeyPressEvent(), handleKeyPressEvent(), and TechDrawGui::QGVPage::zoomIn().
zoomOut()
void TechDrawGui::QGVNavStyle::zoomOut () virtual
Definition at line 347 of file QGVNavStyle.cpp.
References zoom(), and zoomStep.
Referenced by TechDrawGui::QGVNavStyleTouchpad::handleKeyPressEvent(), handleKeyPressEvent(), and TechDrawGui::QGVPage::zoomOut().
Member Data Documentation
altdown
bool TechDrawGui::QGVNavStyle::altdown protected
Definition at line 108 of file QGVNavStyle.h.
Referenced by initialize().
button1down
bool TechDrawGui::QGVNavStyle::button1down protected
Definition at line 109 of file QGVNavStyle.h.
Referenced by initialize().
button2down
bool TechDrawGui::QGVNavStyle::button2down protected
Definition at line 109 of file QGVNavStyle.h.
Referenced by initialize().
button3down
bool TechDrawGui::QGVNavStyle::button3down protected
Definition at line 109 of file QGVNavStyle.h.
Referenced by initialize().
ctrldown
bool TechDrawGui::QGVNavStyle::ctrldown protected
Definition at line 108 of file QGVNavStyle.h.
Referenced by initialize().
invertZoom
bool TechDrawGui::QGVNavStyle::invertZoom protected
Definition at line 110 of file QGVNavStyle.h.
Referenced by handleWheelEvent(), initialize(), and mouseZoomFactor().
m_clickButton
Qt::MouseButton TechDrawGui::QGVNavStyle::m_clickButton protected
Definition at line 122 of file QGVNavStyle.h.
Referenced by TechDrawGui::QGVNavStyleGesture::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleRevit::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleCAD::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseReleaseEvent(), initialize(), startClick(), and stopClick().
m_clickPending
bool TechDrawGui::QGVNavStyle::m_clickPending protected
Definition at line 119 of file QGVNavStyle.h.
Referenced by TechDrawGui::QGVNavStyleRevit::allowContextMenu(), TechDrawGui::QGVNavStyleOpenSCAD::allowContextMenu(), TechDrawGui::QGVNavStyleGesture::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleRevit::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleRevit::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleGesture::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleCAD::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseReleaseEvent(), initialize(), startClick(), and stopClick().
m_currentmode
int TechDrawGui::QGVNavStyle::m_currentmode protected
Definition at line 106 of file QGVNavStyle.h.
m_keyCombo
KeyCombination TechDrawGui::QGVNavStyle::m_keyCombo protected
Definition at line 124 of file QGVNavStyle.h.
m_mouseDeltaCounter
int TechDrawGui::QGVNavStyle::m_mouseDeltaCounter protected
Definition at line 127 of file QGVNavStyle.h.
Referenced by initialize(), and mouseZoomFactor().
m_panPending
bool TechDrawGui::QGVNavStyle::m_panPending protected
Definition at line 120 of file QGVNavStyle.h.
Referenced by TechDrawGui::QGVNavStyleCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleCAD::handleMouseReleaseEvent(), initialize(), startPan(), and stopPan().
m_reversePan
int TechDrawGui::QGVNavStyle::m_reversePan protected
Definition at line 113 of file QGVNavStyle.h.
Referenced by initialize(), and pan().
m_reverseScroll
int TechDrawGui::QGVNavStyle::m_reverseScroll protected
Definition at line 114 of file QGVNavStyle.h.
Referenced by initialize(), and pan().
m_saveCursor
QCursor TechDrawGui::QGVNavStyle::m_saveCursor protected
Definition at line 125 of file QGVNavStyle.h.
Referenced by initialize().
m_viewer
QGVPage* TechDrawGui::QGVNavStyle::m_viewer protected
Definition at line 105 of file QGVNavStyle.h.
Referenced by TechDrawGui::QGVNavStyleTouchpad::setAnchor(), and setAnchor().
m_wheelDeltaCounter
int TechDrawGui::QGVNavStyle::m_wheelDeltaCounter protected
Definition at line 126 of file QGVNavStyle.h.
Referenced by handleWheelEvent(), and initialize().
m_zoomPending
bool TechDrawGui::QGVNavStyle::m_zoomPending protected
Definition at line 121 of file QGVNavStyle.h.
Referenced by TechDrawGui::QGVNavStyleCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleCAD::handleMouseReleaseEvent(), initialize(), startZoom(), stopZoom(), and zoom().
panningActive
bool TechDrawGui::QGVNavStyle::panningActive protected
Definition at line 116 of file QGVNavStyle.h.
Referenced by TechDrawGui::QGVNavStyleBlender::handleKeyReleaseEvent(), TechDrawGui::QGVNavStyleCAD::handleKeyReleaseEvent(), TechDrawGui::QGVNavStyleMaya::handleKeyReleaseEvent(), TechDrawGui::QGVNavStyleOCC::handleKeyReleaseEvent(), TechDrawGui::QGVNavStyleTouchpad::handleKeyReleaseEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleRevit::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleGesture::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleInventor::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleMaya::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleTouchpad::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOCC::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleBlender::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleTinkerCAD::handleMouseMoveEvent(), handleMouseMoveEvent(), handleMousePressEvent(), TechDrawGui::QGVNavStyleRevit::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleInventor::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleBlender::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleMaya::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleOCC::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleCAD::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleTinkerCAD::handleMouseReleaseEvent(), handleMouseReleaseEvent(), initialize(), startPan(), and stopPan().
panOrigin
QPoint TechDrawGui::QGVNavStyle::panOrigin protected
Definition at line 115 of file QGVNavStyle.h.
Referenced by pan(), and startPan().
shiftdown
bool TechDrawGui::QGVNavStyle::shiftdown protected
Definition at line 108 of file QGVNavStyle.h.
Referenced by handleKeyPressEvent(), handleKeyReleaseEvent(), and initialize().
zoomAtCursor
bool TechDrawGui::QGVNavStyle::zoomAtCursor protected
Definition at line 111 of file QGVNavStyle.h.
Referenced by initialize(), and setAnchor().
zoomingActive
bool TechDrawGui::QGVNavStyle::zoomingActive protected
Definition at line 118 of file QGVNavStyle.h.
Referenced by TechDrawGui::QGVNavStyleCAD::handleKeyReleaseEvent(), TechDrawGui::QGVNavStyleMaya::handleKeyReleaseEvent(), TechDrawGui::QGVNavStyleOCC::handleKeyReleaseEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleKeyReleaseEvent(), TechDrawGui::QGVNavStyleTouchpad::handleKeyReleaseEvent(), TechDrawGui::QGVNavStyleInventor::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleCAD::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleMaya::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleTouchpad::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleOCC::handleMouseMoveEvent(), TechDrawGui::QGVNavStyleInventor::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleOpenSCAD::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleMaya::handleMouseReleaseEvent(), TechDrawGui::QGVNavStyleOCC::handleMouseReleaseEvent(), initialize(), startZoom(), and stopZoom().
zoomOrigin
QPoint TechDrawGui::QGVNavStyle::zoomOrigin protected
Definition at line 117 of file QGVNavStyle.h.
Referenced by mouseZoomFactor(), and startZoom().
zoomStep
double TechDrawGui::QGVNavStyle::zoomStep protected
Definition at line 112 of file QGVNavStyle.h.
Referenced by handleWheelEvent(), initialize(), mouseZoomFactor(), zoomIn(), and zoomOut().
The documentation for this class was generated from the following files:
QGVNavStyle.h
QGVNavStyle.cpp