FreeCAD: SketcherGui::TaskSketcherConstraints Class Reference
SketcherGui::TaskSketcherConstraints Class Reference
#include <TaskSketcherConstraints.h>
Public Member Functions
TaskSketcherConstraints (ViewProviderSketch *sketchView)
~TaskSketcherConstraints () override
void onSelectionChanged (const Gui::SelectionChanges &msg) override
Observer message from the Selection.
void OnChange (Base::Subject< const char * > &rCaller, const char *rcReason) override
void onListWidgetConstraintsItemSelectionChanged ()
void onListWidgetConstraintsItemActivated (QListWidgetItem *item)
void onListWidgetConstraintsItemChanged (QListWidgetItem *item)
void onListWidgetConstraintsUpdateDrivingStatus (QListWidgetItem *item, bool status)
void onListWidgetConstraintsUpdateActiveStatus (QListWidgetItem *item, bool status)
void onListWidgetConstraintsEmitCenterSelectedItems ()
void onListWidgetConstraintsEmitShowSelection3DVisibility ()
void onListWidgetConstraintsEmitHideSelection3DVisibility ()
void onFilterBoxStateChanged (int val)
void onShowHideButtonClicked (bool)
void onSettingsRestrictVisibilityChanged (bool value=false)
void onSettingsExtendedInformationChanged (bool value=false)
void onSettingsHideInternalAligmentChanged (bool value=false)
void onSettingsAutoConstraintsChanged (bool value=false)
void onSettingsAutoRemoveRedundantChanged (bool value=false)
void onFilterListItemChanged (QListWidgetItem *item)
Public Member Functions inherited from Gui::TaskView::TaskBox
TaskBox (QWidget *parent=nullptr)
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
QSize minimumSizeHint () const override
~TaskBox () override
void hideGroupBox ()
bool isGroupVisible () const
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (QWidget *parent=nullptr)
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
QBoxLayout * groupLayout ()
void setScheme (ActionPanelScheme *pointer)
bool isExpandable () const
bool hasHeader () const
QString headerText () const
QSize minimumSizeHint () const override
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Public Attributes
SpecialFilterType specialFilterMode
Protected Types
using Connection = boost::signals2::connection
Protected Member Functions
void changeEvent (QEvent *e) override
Protected Member Functions inherited from Gui::TaskView::TaskBox
void showEvent (QShowEvent *) override
void actionEvent (QActionEvent *) override
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
void paintEvent (QPaintEvent *event) override
Protected Attributes
ViewProviderSketch * sketchView
Connection connectionConstraintsChanged
Protected Attributes inherited from QSint::ActionGroup
double m_foldStep
double m_foldDelta
double m_fullHeight
double m_tempHeight
int m_foldDirection
QPixmap m_foldPixmap
class TaskHeader * myHeader
class TaskGroup * myGroup
QWidget * myDummy
ActionPanelScheme * myScheme
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void showHide ()
void setExpandable (bool expandable=true)
void setHeader (bool enable=true)
void setHeaderText (const QString &title)
void setHeaderIcon (const QPixmap &icon)
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Detailed Description
Definition at line 138 of file TaskSketcherConstraints.h.
Member Typedef Documentation
Connection
using SketcherGui::TaskSketcherConstraints::Connection = boost::signals2::connection protected
Definition at line 199 of file TaskSketcherConstraints.h.
Constructor & Destructor Documentation
TaskSketcherConstraints()
TaskSketcherConstraints::TaskSketcherConstraints (ViewProviderSketch * sketchView) explicit
Definition at line 816 of file TaskSketcherConstraints.cpp.
~TaskSketcherConstraints()
TaskSketcherConstraints::~TaskSketcherConstraints () override
Definition at line 973 of file TaskSketcherConstraints.cpp.
References connectionConstraintsChanged, Base::Subject< MsgType >::Detach(), App::GetApplication(), and App::Application::GetParameterGroupByPath().
Member Function Documentation
changeEvent()
void TaskSketcherConstraints::changeEvent (QEvent * e) override protected
Definition at line 1719 of file TaskSketcherConstraints.cpp.
References SCL.SimpleDataTypes::e.
OnChange()
void TaskSketcherConstraints::OnChange (Base::Subject< const char * > & rCaller, const char * rcReason) override
Definition at line 1410 of file TaskSketcherConstraints.cpp.
References App::GetApplication(), ParameterGrp::GetBool(), and App::Application::GetParameterGroupByPath().
onFilterBoxStateChanged()
void TaskSketcherConstraints::onFilterBoxStateChanged (int val)
Definition at line 1053 of file TaskSketcherConstraints.cpp.
References App::GetApplication(), App::Application::GetParameterGroupByPath(), ParameterGrp::SetBool(), and toolbit-attributes::val.
onFilterListItemChanged()
void TaskSketcherConstraints::onFilterListItemChanged (QListWidgetItem * item)
Definition at line 1728 of file TaskSketcherConstraints.cpp.
References SketcherGui::ConstraintFilterList::associatedFilterIndex, SketcherGui::ConstraintFilter::filterAggregates, App::GetApplication(), App::Application::GetParameterGroupByPath(), SplineSurface::i, SketcherGui::ConstraintFilterList::normalFilterCount, SketcherGui::ConstraintFilterList::selectedFilterIndex, ParameterGrp::SetInt(), SketcherGui::ConstraintFilterList::setPartiallyChecked(), and specialFilterMode.
onListWidgetConstraintsEmitCenterSelectedItems()
void TaskSketcherConstraints::onListWidgetConstraintsEmitCenterSelectedItems ()
Definition at line 1465 of file TaskSketcherConstraints.cpp.
References SketcherGui::ViewProviderSketch::centerSelection(), and sketchView.
onListWidgetConstraintsEmitHideSelection3DVisibility()
void TaskSketcherConstraints::onListWidgetConstraintsEmitHideSelection3DVisibility ()
Definition at line 1079 of file TaskSketcherConstraints.cpp.
onListWidgetConstraintsEmitShowSelection3DVisibility()
void TaskSketcherConstraints::onListWidgetConstraintsEmitShowSelection3DVisibility ()
Definition at line 1083 of file TaskSketcherConstraints.cpp.
onListWidgetConstraintsItemActivated()
void TaskSketcherConstraints::onListWidgetConstraintsItemActivated (QListWidgetItem * item)
Definition at line 1185 of file TaskSketcherConstraints.cpp.
References ConstraintItem::ConstraintNbr, SketcherGui::EditDatumDialog::exec(), ConstraintItem::isDimensional(), and sketchView.
onListWidgetConstraintsItemChanged()
void TaskSketcherConstraints::onListWidgetConstraintsItemChanged (QListWidgetItem * item)
Definition at line 1199 of file TaskSketcherConstraints.cpp.
References Gui::Command::abortCommand(), Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), ConstraintItem::ConstraintNbr, Sketcher::SketchObject::Constraints, ConstraintItem::data(), SCL.SimpleDataTypes::e, Base::Tools::escapedUnicodeFromUtf8(), Sketcher::PropertyConstraintList::getConstraintName(), SketcherGui::ViewProviderSketch::getIsShownVirtualSpace(), SketcherGui::ViewProviderSketch::getSketchObject(), Sketcher::PropertyConstraintList::getValues(), Gui::NotifyUserError(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, sketchView, and TestSpreadsheet::v.
onListWidgetConstraintsItemSelectionChanged()
void TaskSketcherConstraints::onListWidgetConstraintsItemSelectionChanged ()
Definition at line 1470 of file TaskSketcherConstraints.cpp.
References Gui::SelectionSingleton::addSelections(), Gui::SelectionObserver::blockSelection(), Gui::SelectionSingleton::clearSelection(), ConstraintItem::ConstraintNbr, Sketcher::PropertyConstraintList::getConstraintName(), App::DocumentObject::getDocument(), App::Document::getName(), App::DocumentObject::getNameInDocument(), SketcherGui::ViewProviderSketch::getSketchObject(), src.Mod.Test.testPathArray::items, Gui::Selection(), and sketchView.
onListWidgetConstraintsUpdateActiveStatus()
void TaskSketcherConstraints::onListWidgetConstraintsUpdateActiveStatus (QListWidgetItem * item, bool status)
Definition at line 1172 of file TaskSketcherConstraints.cpp.
References Gui::Application::commandManager(), Gui::Application::Instance, and Gui::CommandManager::runCommandByName().
onListWidgetConstraintsUpdateDrivingStatus()
void TaskSketcherConstraints::onListWidgetConstraintsUpdateDrivingStatus (QListWidgetItem * item, bool status)
Definition at line 1159 of file TaskSketcherConstraints.cpp.
References Gui::Application::commandManager(), Gui::Application::Instance, and Gui::CommandManager::runCommandByName().
onSelectionChanged()
void TaskSketcherConstraints::onSelectionChanged (const Gui::SelectionChanges & msg) override virtual
Observer message from the Selection.
Implements Gui::SelectionObserver.
Definition at line 1329 of file TaskSketcherConstraints.cpp.
References Gui::SelectionChanges::AddSelection, Gui::SelectionObserver::blockSelection(), Gui::SelectionChanges::ClrSelection, ConstraintItem::ConstraintNbr, countItems, Sketcher::GeoUndef, App::DocumentObject::getDocument(), App::Document::getName(), App::DocumentObject::getNameInDocument(), SketcherGui::ViewProviderSketch::getSketchObject(), SplineSurface::i, Path.Op.Surface::msg, Sketcher::none, src.Mod.AddonManager.addonmanager_devmode_license_selector::QRegularExpression, Gui::SelectionChanges::RmvSelection, Path.Op.Gui.Selection::select(), Gui::SelectionChanges::SetSelection, sketchView, and specialFilterMode.
onSettingsAutoConstraintsChanged()
void TaskSketcherConstraints::onSettingsAutoConstraintsChanged (bool value = false)
Definition at line 1021 of file TaskSketcherConstraints.cpp.
References SketcherGui::ViewProviderSketch::Autoconstraints, App::GetApplication(), App::Application::GetParameterGroupByPath(), App::PropertyBool::setValue(), and sketchView.
onSettingsAutoRemoveRedundantChanged()
void TaskSketcherConstraints::onSettingsAutoRemoveRedundantChanged (bool value = false)
Definition at line 1030 of file TaskSketcherConstraints.cpp.
References App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), and ParameterGrp::SetBool().
onSettingsExtendedInformationChanged()
void TaskSketcherConstraints::onSettingsExtendedInformationChanged (bool value = false)
Definition at line 981 of file TaskSketcherConstraints.cpp.
References App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), and ParameterGrp::SetBool().
onSettingsHideInternalAligmentChanged()
void TaskSketcherConstraints::onSettingsHideInternalAligmentChanged (bool value = false)
Definition at line 993 of file TaskSketcherConstraints.cpp.
References App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), and ParameterGrp::SetBool().
onSettingsRestrictVisibilityChanged()
void TaskSketcherConstraints::onSettingsRestrictVisibilityChanged (bool value = false)
Definition at line 1006 of file TaskSketcherConstraints.cpp.
References App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), and ParameterGrp::SetBool().
onShowHideButtonClicked()
void TaskSketcherConstraints::onShowHideButtonClicked (bool val)
Definition at line 1064 of file TaskSketcherConstraints.cpp.
References SplineSurface::i, and toolbit-attributes::val.
Member Data Documentation
connectionConstraintsChanged
Connection SketcherGui::TaskSketcherConstraints::connectionConstraintsChanged protected
Definition at line 200 of file TaskSketcherConstraints.h.
Referenced by ~TaskSketcherConstraints().
sketchView
ViewProviderSketch* SketcherGui::TaskSketcherConstraints::sketchView protected
Definition at line 198 of file TaskSketcherConstraints.h.
Referenced by onListWidgetConstraintsEmitCenterSelectedItems(), onListWidgetConstraintsItemActivated(), onListWidgetConstraintsItemChanged(), onListWidgetConstraintsItemSelectionChanged(), onSelectionChanged(), and onSettingsAutoConstraintsChanged().
specialFilterMode
SpecialFilterType SketcherGui::TaskSketcherConstraints::specialFilterMode
Definition at line 165 of file TaskSketcherConstraints.h.
Referenced by onFilterListItemChanged(), and onSelectionChanged().
The documentation for this class was generated from the following files:
TaskSketcherConstraints.h
TaskSketcherConstraints.cpp