FreeCAD: Gui::TaskView::TaskView Class Reference
Gui::TaskView::TaskView Class Reference
#include <TaskView.h>
Signals
void taskUpdate ()
Public Member Functions
TaskView (QWidget *parent=nullptr)
~TaskView () override
void OnChange (Gui::SelectionSingleton::SubjectType &rCaller, Gui::SelectionSingleton::MessageType Reason) override
Observer message from the Selection.
void addTaskWatcher (const std::vector< TaskWatcher * > &Watcher)
void clearTaskWatcher ()
void takeTaskWatcher (TaskView *other)
bool isEmpty (bool includeWatcher=true) const
void clearActionStyle ()
void restoreActionStyle ()
QSize minimumSizeHint () const override
void setRestoreWidth (bool on)
bool shouldRestoreWidth () const
Protected Slots
void accept ()
void reject ()
void helpRequested ()
void clicked (QAbstractButton *button)
Protected Member Functions
void keyPressEvent (QKeyEvent *event) override
bool event (QEvent *event) override
void addTaskWatcher ()
void removeTaskWatcher ()
void updateWatcher ()
update the visibility of the TaskWatcher accordant to the selection
void showDialog (TaskDialog *dlg)
used by Gui::Control to register Dialogs
void removeDialog ()
Protected Attributes
std::vector< TaskWatcher * > ActiveWatcher
QSint::ActionPanel * taskPanel
TaskDialog * ActiveDialog
TaskEditControl * ActiveCtrl
bool restoreWidth = false
int currentWidth = 0
Connection connectApplicationActiveDocument
Connection connectApplicationDeleteDocument
Connection connectApplicationClosedView
Connection connectApplicationUndoDocument
Connection connectApplicationRedoDocument
Friends
class Gui::DockWnd::ComboView
class Gui::ControlSingleton
Detailed Description
TaskView class handles the FreeCAD task view panel. Keeps track of the inserted content elements. This elements get injected mostly by the ViewProvider classes of the selected DocumentObjects.
Definition at line 141 of file TaskView.h.
Constructor & Destructor Documentation
TaskView()
TaskView::TaskView (QWidget * parent = nullptr) explicit
Definition at line 270 of file TaskView.cpp.
References Base::Subject< MsgType >::Attach(), draftgeoutils.faces::bind(), connectApplicationActiveDocument, connectApplicationClosedView, connectApplicationDeleteDocument, connectApplicationRedoDocument, connectApplicationUndoDocument, QSint::FreeCADPanelScheme::defaultScheme(), App::GetApplication(), Gui::Application::Instance, Gui::Selection(), QSint::ActionPanel::setScheme(), App::Application::signalActiveDocument, Gui::Application::signalCloseView, App::Application::signalDeleteDocument, App::Application::signalRedoDocument, App::Application::signalUndoDocument, taskPanel, and updateWatcher().
~TaskView()
TaskView::~TaskView () override
Definition at line 312 of file TaskView.cpp.
References connectApplicationActiveDocument, connectApplicationClosedView, connectApplicationDeleteDocument, connectApplicationRedoDocument, connectApplicationUndoDocument, Base::Subject< MsgType >::Detach(), and Gui::Selection().
Member Function Documentation
accept
void TaskView::accept () protected slot
Definition at line 828 of file TaskView.cpp.
References Gui::TaskView::TaskDialog::accept(), ActiveDialog, Base::Console(), removeDialog(), and Base::ConsoleSingleton::Warning().
Referenced by Gui::ControlSingleton::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), showDialog(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
addTaskWatcher() [1/2]
void TaskView::addTaskWatcher () protected
Definition at line 740 of file TaskView.cpp.
References ActiveWatcher, QSint::ActionPanel::addStretch(), QSint::ActionPanel::addWidget(), MengerSponge::box, QSint::FreeCADPanelScheme::defaultScheme(), event(), QSint::ActionPanel::setScheme(), taskPanel, updateWatcher(), and src.Mod.PartDesign.fcgear.svggear::w.
Referenced by addTaskWatcher(), clearTaskWatcher(), removeDialog(), and takeTaskWatcher().
addTaskWatcher() [2/2]
void TaskView::addTaskWatcher (const std::vector< TaskWatcher * > & Watcher)
Definition at line 712 of file TaskView.cpp.
References ActiveCtrl, ActiveDialog, ActiveWatcher, and addTaskWatcher().
Referenced by Gui::Workbench::addTaskWatcher(), and Gui::TaskView::ControlPy::addTaskWatcher().
clearActionStyle()
void TaskView::clearActionStyle ()
Definition at line 871 of file TaskView.cpp.
References QSint::FreeCADPanelScheme::defaultScheme(), QSint::ActionPanel::setScheme(), and taskPanel.
clearTaskWatcher()
void TaskView::clearTaskWatcher ()
Definition at line 732 of file TaskView.cpp.
References addTaskWatcher(), and removeTaskWatcher().
Referenced by Gui::TaskView::ControlPy::clearTaskWatcher(), Gui::Workbench::removeTaskWatcher(), and takeTaskWatcher().
clicked
void TaskView::clicked (QAbstractButton * button) protected slot
Definition at line 865 of file TaskView.cpp.
References ActiveCtrl, ActiveDialog, Gui::TaskView::TaskEditControl::buttonBox, and Gui::TaskView::TaskDialog::clicked().
Referenced by showDialog().
event()
bool TaskView::event (QEvent * event) override protected
Definition at line 336 of file TaskView.cpp.
Referenced by addTaskWatcher().
helpRequested
void TaskView::helpRequested () protected slot
Definition at line 860 of file TaskView.cpp.
References ActiveDialog, and Gui::TaskView::TaskDialog::helpRequested().
Referenced by showDialog().
isEmpty()
bool TaskView::isEmpty (bool includeWatcher = true) const
Definition at line 322 of file TaskView.cpp.
References ActiveCtrl, ActiveDialog, and ActiveWatcher.
Referenced by Gui::OverlayTabWidget::checkAutoHide(), and takeTaskWatcher().
keyPressEvent()
void TaskView::keyPressEvent (QKeyEvent * event) override protected
Definition at line 370 of file TaskView.cpp.
References ActiveCtrl, ActiveDialog, MengerSponge::box, toolbit-attributes::doc, Gui::Application::getDocument(), Gui::TaskView::TaskDialog::getDocumentName(), Gui::Application::Instance, Gui::TaskView::TaskDialog::isEscapeButtonEnabled(), RobotExample::pos, and Gui::TaskView::TaskEditControl::standardButtons().
minimumSizeHint()
QSize TaskView::minimumSizeHint () const override
Definition at line 445 of file TaskView.cpp.
References QSint::ActionPanel::minimumSizeHint(), and taskPanel.
OnChange()
void Gui::TaskView::TaskView::OnChange (Gui::SelectionSingleton::SubjectType & rCaller, Gui::SelectionSingleton::MessageType Reason) override
Observer message from the Selection.
reject
void TaskView::reject () protected slot
Definition at line 844 of file TaskView.cpp.
References ActiveDialog, Base::Console(), Gui::TaskView::TaskDialog::reject(), removeDialog(), and Base::ConsoleSingleton::Warning().
Referenced by bimcommands.BimReorder.BIM_Reorder_TaskPanel::accept(), draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), draftguitools.gui_selectplane.Draft_SelectPlane::action(), JointObject.TaskAssemblyCreateJoint::autoClosedOnTransactionChange(), femexamples.examplesgui.FemExamples::clicked(), CommandCreateView.TaskAssemblyCreateView::KeyboardEvent(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), bimcommands.BimProjectManager.BIM_ProjectManager::loadTemplate(), bimcommands.BimLibrary.BIM_Library_TaskPanel::mouseClick(), Gui::ControlSingleton::reject(), bimcommands.BimProjectManager.BIM_ProjectManager::saveTemplate(), showDialog(), and Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit().
removeDialog()
void TaskView::removeDialog () protected
Definition at line 624 of file TaskView.cpp.
References ActiveCtrl, ActiveDialog, addTaskWatcher(), Gui::TaskView::TaskDialog::closed(), Gui::TaskView::TaskDialog::emitDestructionSignal(), Gui::TaskView::TaskDialog::getDialogContent(), Gui::getMainWindow(), QSint::ActionPanel::removeStretch(), QSint::ActionPanel::removeWidget(), taskPanel, and Gui::MainWindow::updateActions().
Referenced by accept(), Gui::ControlSingleton::closeDialog(), and reject().
removeTaskWatcher()
void TaskView::removeTaskWatcher () protected
Definition at line 798 of file TaskView.cpp.
References ActiveWatcher, QSint::ActionPanel::removeStretch(), QSint::ActionPanel::removeWidget(), taskPanel, and src.Mod.PartDesign.fcgear.svggear::w.
Referenced by clearTaskWatcher(), and showDialog().
restoreActionStyle()
void TaskView::restoreActionStyle ()
Definition at line 877 of file TaskView.cpp.
References QSint::FreeCADPanelScheme::defaultScheme(), QSint::ActionPanel::setScheme(), and taskPanel.
setRestoreWidth()
void TaskView::setRestoreWidth (bool on)
Definition at line 788 of file TaskView.cpp.
References restoreWidth.
shouldRestoreWidth()
bool TaskView::shouldRestoreWidth () const
Definition at line 793 of file TaskView.cpp.
References restoreWidth.
showDialog()
void TaskView::showDialog (TaskDialog * dlg) protected
used by Gui::Control to register Dialogs
Definition at line 560 of file TaskView.cpp.
References accept(), ActiveCtrl, ActiveDialog, QSint::ActionPanel::addStretch(), QSint::ActionPanel::addWidget(), Gui::TaskView::TaskEditControl::buttonBox, Gui::TaskView::TaskDialog::buttonPosition(), clicked(), draftgeoutils.intersections::connect(), QSint::FreeCADPanelScheme::defaultScheme(), Gui::TaskView::TaskDialog::getDialogContent(), Gui::getMainWindow(), Gui::TaskView::TaskDialog::getStandardButtons(), helpRequested(), Gui::TaskView::TaskDialog::modifyStandardButtons(), Gui::TaskView::TaskDialog::needsFullSpace(), Gui::TaskView::TaskDialog::North, Gui::TaskView::TaskDialog::open(), reject(), removeTaskWatcher(), QSint::ActionPanel::setScheme(), taskPanel, taskUpdate(), and Gui::MainWindow::updateActions().
Referenced by Gui::ControlSingleton::showDialog().
takeTaskWatcher()
void TaskView::takeTaskWatcher (TaskView * other)
Definition at line 723 of file TaskView.cpp.
References ActiveWatcher, addTaskWatcher(), clearTaskWatcher(), and isEmpty().
Referenced by updateWatcher().
taskUpdate
void Gui::TaskView::TaskView::taskUpdate () signal
Referenced by showDialog(), and updateWatcher().
updateWatcher()
void TaskView::updateWatcher () protected
update the visibility of the TaskWatcher accordant to the selection
Definition at line 665 of file TaskView.cpp.
References ActiveWatcher, Gui::Control(), takeTaskWatcher(), Gui::ControlSingleton::taskPanel(), and taskUpdate().
Referenced by addTaskWatcher(), and TaskView().
Friends And Related Function Documentation
Gui::ControlSingleton
friend class Gui::ControlSingleton friend
Definition at line 154 of file TaskView.h.
Gui::DockWnd::ComboView
friend class Gui::DockWnd::ComboView friend
Definition at line 153 of file TaskView.h.
Member Data Documentation
ActiveCtrl
TaskEditControl* Gui::TaskView::TaskView::ActiveCtrl protected
Definition at line 209 of file TaskView.h.
Referenced by addTaskWatcher(), clicked(), isEmpty(), keyPressEvent(), removeDialog(), and showDialog().
ActiveDialog
TaskDialog* Gui::TaskView::TaskView::ActiveDialog protected
Definition at line 208 of file TaskView.h.
Referenced by accept(), addTaskWatcher(), clicked(), helpRequested(), isEmpty(), keyPressEvent(), reject(), removeDialog(), and showDialog().
ActiveWatcher
std::vector<TaskWatcher*> Gui::TaskView::TaskView::ActiveWatcher protected
Definition at line 205 of file TaskView.h.
Referenced by addTaskWatcher(), isEmpty(), removeTaskWatcher(), takeTaskWatcher(), and updateWatcher().
connectApplicationActiveDocument
Connection Gui::TaskView::TaskView::connectApplicationActiveDocument protected
Definition at line 213 of file TaskView.h.
Referenced by TaskView(), and ~TaskView().
connectApplicationClosedView
Connection Gui::TaskView::TaskView::connectApplicationClosedView protected
Definition at line 215 of file TaskView.h.
Referenced by TaskView(), and ~TaskView().
connectApplicationDeleteDocument
Connection Gui::TaskView::TaskView::connectApplicationDeleteDocument protected
Definition at line 214 of file TaskView.h.
Referenced by TaskView(), and ~TaskView().
connectApplicationRedoDocument
Connection Gui::TaskView::TaskView::connectApplicationRedoDocument protected
Definition at line 217 of file TaskView.h.
Referenced by TaskView(), and ~TaskView().
connectApplicationUndoDocument
Connection Gui::TaskView::TaskView::connectApplicationUndoDocument protected
Definition at line 216 of file TaskView.h.
Referenced by TaskView(), and ~TaskView().
currentWidth
int Gui::TaskView::TaskView::currentWidth = 0 protected
Definition at line 211 of file TaskView.h.
restoreWidth
bool Gui::TaskView::TaskView::restoreWidth = false protected
Definition at line 210 of file TaskView.h.
Referenced by setRestoreWidth(), and shouldRestoreWidth().
taskPanel
QSint::ActionPanel* Gui::TaskView::TaskView::taskPanel protected
Definition at line 207 of file TaskView.h.
Referenced by addTaskWatcher(), Path.Main.Gui.Job.ViewProvider::attach(), clearActionStyle(), minimumSizeHint(), Path.Main.Gui.Job.ViewProvider::openTaskPanel(), removeDialog(), removeTaskWatcher(), Path.Main.Gui.Job.ViewProvider::resetTaskPanel(), restoreActionStyle(), showDialog(), TaskView(), and Path.Main.Gui.Job.ViewProvider::unsetEdit().
The documentation for this class was generated from the following files:
TaskView.h
TaskView.cpp