FreeCAD: App::DynamicProperty Class Reference
App::DynamicProperty Class Reference
#include <DynamicProperty.h>
Classes
struct PropData
Public Member Functions
DynamicProperty ()
virtual ~DynamicProperty ()
Access properties
void getPropertyList (std::vector< Property * > &List) const
Get all properties of the class (including parent)
void getPropertyNamedList (std::vector< std::pair< const char *, Property * >> &List) const
get all properties with their names
void getPropertyMap (std::map< std::string, Property * > &Map) const
Get all properties of the class (including parent)
Property * getDynamicPropertyByName (const char *name) const
Find a dynamic property by its name.
Property * addDynamicProperty (PropertyContainer &pc, const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false)
bool addProperty (Property *prop)
bool removeDynamicProperty (const char *name)
bool removeProperty (const Property *prop)
Remove pre-existing property, which will not be deleted.
std::vector< std::string > getDynamicPropertyNames () const
Get a list of all dynamic properties.
const char * getPropertyName (const Property *prop) const
Get the name of a property.
Property attributes
short getPropertyType (const Property *prop) const
Get the attributes of a property.
short getPropertyType (const char *name) const
Get the attributes of a named property.
const char * getPropertyGroup (const Property *prop) const
Get the group name of a property.
const char * getPropertyGroup (const char *name) const
Get the group name of a named property.
const char * getPropertyDocumentation (const Property *prop) const
Get the documentation of a property.
const char * getPropertyDocumentation (const char *name) const
Get the documentation of a named property.
void clear ()
Remove all properties.
size_t size () const
Get property count.
void save (const Property *prop, Base::Writer &writer) const
Property * restore (PropertyContainer &pc, const char *PropName, const char *TypeName, Base::XMLReader &reader)
PropData getDynamicPropertyData (const Property *prop) const
bool changeDynamicProperty (const Property *prop, const char *group, const char *doc)
Detailed Description
This class implements an interface to add properties at run-time to an object derived from PropertyContainer. The additional properties are made persistent.
Author
Werner Mayer
Definition at line 78 of file DynamicProperty.h.
Constructor & Destructor Documentation
DynamicProperty()
DynamicProperty::DynamicProperty () default
~DynamicProperty()
DynamicProperty::~DynamicProperty () virtual
Definition at line 44 of file DynamicProperty.cpp.
References Path.Op.Gui.Selection::clear().
Member Function Documentation
addDynamicProperty()
Property * DynamicProperty::addDynamicProperty (PropertyContainer & pc, const char * type, const char * name = nullptr, const char * group = nullptr, const char * doc = nullptr, short attr = 0, bool ro = false, bool hidden = false)
Add a dynamic property of the type type and with the name name. Group gives the grouping name which appears in the property editor and doc shows the tooltip there. With attr, ro and hidden the behaviour of the property can be controlled. attr is an OR'ed value of the PropertyType enumeration. If no special attribute should be set Prop_None can be set (or leave the default of 0). For convenience the attributes for 'Read-Only' and 'Hidden' can also be controlled with the values ro or hidden. This means,
addDynamicProperty(..., ..., "Base","blah", Prop_ReadOnly | Prop_Hidden);
is equivalent to
addDynamicProperty(..., ..., "Base","blah", Prop_None, true, true);
Definition at line 163 of file DynamicProperty.cpp.
References Base::Type::createInstance(), toolbit-attributes::doc, FC_THROWM, FC_WARN, App::GetApplication(), ParameterGrp::GetBool(), Base::Persistence::getClassTypeId(), App::PropertyContainer::getFullName(), Base::Tools::getIdentifier(), App::Application::GetParameterGroupByPath(), App::PropertyContainer::getPropertyByName(), Base::Type::getTypeIfDerivedFrom(), toolbit-attributes::group, Base::Type::isBad(), App::Prop_Hidden, App::Prop_ReadOnly, App::Property::PropDynamic, App::Property::setContainer(), App::Application::signalAppendDynamicProperty, App::Property::StatusBits, and Path.Post.scripts.grbl_post::type.
Referenced by App::PropertyContainer::addDynamicProperty(), and restore().
addProperty()
bool DynamicProperty::addProperty (Property * prop)
Add a pre-existing property
The property is not treated as dynamic, and will not trigger signal.
Returns
Return false if there is a property exist with the same name.
Definition at line 241 of file DynamicProperty.cpp.
References App::Property::getDocumentation(), App::Property::getGroup(), App::Property::getName(), App::Property::getType(), and App::Property::hasName().
Referenced by femobjects.constraint_selfweight.ConstraintSelfWeight::__init__(), bimcommands.BimIfcProperties.BIM_IfcProperties::addPset(), DocumentObject.Box::init(), DocumentObject.DocumentObject::onChanged(), and femobjects.constraint_selfweight.ConstraintSelfWeight::onDocumentRestored().
changeDynamicProperty()
bool DynamicProperty::changeDynamicProperty (const Property * prop, const char * group, const char * doc)
Definition at line 384 of file DynamicProperty.cpp.
References toolbit-attributes::doc, and toolbit-attributes::group.
clear()
void DynamicProperty::clear ()
Remove all properties.
Definition at line 49 of file DynamicProperty.cpp.
References TestSpreadsheet::v.
Referenced by src.Mod.Test.Document.DocumentObserverCases.Observer::__init__(), and src.Mod.Test.Document.DocumentObserverCases.GuiObserver::__init__().
getDynamicPropertyByName()
Property * DynamicProperty::getDynamicPropertyByName (const char * name) const
Find a dynamic property by its name.
Definition at line 80 of file DynamicProperty.cpp.
Referenced by Spreadsheet::Sheet::clear(), Spreadsheet::Sheet::getProperty(), App::PropertyContainer::getPropertyByName(), Spreadsheet::Sheet::setFloatProperty(), Spreadsheet::Sheet::setIntegerProperty(), Spreadsheet::Sheet::setObjectProperty(), Spreadsheet::Sheet::setQuantityProperty(), and Spreadsheet::Sheet::setStringProperty().
getDynamicPropertyData()
DynamicProperty::PropData DynamicProperty::getDynamicPropertyData (const Property * prop) const
Definition at line 374 of file DynamicProperty.cpp.
getDynamicPropertyNames()
std::vector< std::string > DynamicProperty::getDynamicPropertyNames () const
Get a list of all dynamic properties.
Definition at line 90 of file DynamicProperty.cpp.
References femtools.tokrules::names, and TestSpreadsheet::v.
Referenced by Spreadsheet::Sheet::clearAll().
getPropertyDocumentation() [1/2]
const char * DynamicProperty::getPropertyDocumentation (const char * name) const
Get the documentation of a named property.
Definition at line 153 of file DynamicProperty.cpp.
getPropertyDocumentation() [2/2]
const char * DynamicProperty::getPropertyDocumentation (const Property * prop) const
Get the documentation of a property.
Definition at line 143 of file DynamicProperty.cpp.
Referenced by App::PropertyContainer::getPropertyDocumentation().
getPropertyGroup() [1/2]
const char * DynamicProperty::getPropertyGroup (const char * name) const
Get the group name of a named property.
Definition at line 133 of file DynamicProperty.cpp.
getPropertyGroup() [2/2]
const char * DynamicProperty::getPropertyGroup (const Property * prop) const
Get the group name of a property.
Definition at line 123 of file DynamicProperty.cpp.
Referenced by App::PropertyContainer::getPropertyGroup().
getPropertyList()
void DynamicProperty::getPropertyList (std::vector< Property * > & List) const
Get all properties of the class (including parent)
Definition at line 58 of file DynamicProperty.cpp.
References TestSpreadsheet::v.
Referenced by App::PropertyContainer::getPropertyList().
getPropertyMap()
void DynamicProperty::getPropertyMap (std::map< std::string, Property * > & Map) const
Get all properties of the class (including parent)
Definition at line 73 of file DynamicProperty.cpp.
References TestSpreadsheet::v.
Referenced by App::PropertyContainer::getPropertyMap().
getPropertyName()
const char * DynamicProperty::getPropertyName (const Property * prop) const
Get the name of a property.
Definition at line 402 of file DynamicProperty.cpp.
Referenced by App::PropertyContainer::getPropertyName().
getPropertyNamedList()
void DynamicProperty::getPropertyNamedList (std::vector< std::pair< const char *, Property * >> & List) const
get all properties with their names
Definition at line 65 of file DynamicProperty.cpp.
References TestSpreadsheet::v.
Referenced by App::PropertyContainer::getPropertyNamedList().
getPropertyType() [1/2]
short DynamicProperty::getPropertyType (const char * name) const
Get the attributes of a named property.
Definition at line 106 of file DynamicProperty.cpp.
References App::Prop_Hidden, and App::Prop_ReadOnly.
getPropertyType() [2/2]
short DynamicProperty::getPropertyType (const Property * prop) const
Get the attributes of a property.
Definition at line 101 of file DynamicProperty.cpp.
References App::Property::getType().
removeDynamicProperty()
bool DynamicProperty::removeDynamicProperty (const char * name)
Removes a dynamic property by name. Returns true if the property is part of the container, otherwise false is returned.
Definition at line 272 of file DynamicProperty.cpp.
References App::Property::destroy(), App::GetApplication(), App::Property::LockDynamic, App::Property::PropDynamic, and App::Application::signalRemoveDynamicProperty.
removeProperty()
bool DynamicProperty::removeProperty (const Property * prop)
Remove pre-existing property, which will not be deleted.
Definition at line 261 of file DynamicProperty.cpp.
restore()
Property * DynamicProperty::restore (PropertyContainer & pc, const char * PropName, const char * TypeName, Base::XMLReader & reader)
Definition at line 335 of file DynamicProperty.cpp.
References addDynamicProperty(), toolbit-attributes::doc, toolbit-attributes::group, ArchFence::hide(), TechDrawTools.TaskFillTemplateFields::reader, and Path.Post.scripts.refactored_centroid_post::str.
Referenced by src.Mod.Show.mTempoVis.TempoVis::__del__(), Part::Box::Restore(), and App::PropertyContainer::Restore().
save()
void DynamicProperty::save (const Property * prop, Base::Writer & writer) const
Definition at line 322 of file DynamicProperty.cpp.
References Base::Persistence::encodeAttribute(), and Base::Writer::Stream().
Referenced by src.Mod.Show.mTempoVis.TempoVis::modify(), src.Mod.Show.mTempoVis.TempoVis::modifyVPProperty(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onSaveStyle(), App::PropertyContainer::Save(), src.Mod.Show.mTempoVis.TempoVis::saveCamera(), and nativeifc.ifc_viewproviders.ifc_vp_document::setupContextMenu().
size()
size_t App::DynamicProperty::size () const inline
Get property count.
Definition at line 159 of file DynamicProperty.h.
Referenced by Path.Post.Utils.GCodeEditorDialog::done().
The documentation for this class was generated from the following files:
DynamicProperty.h
DynamicProperty.cpp