FreeCAD: Gui::LabelEditor Class Reference
Gui::LabelEditor Class Reference
#include <Widgets.h>
Public Types
enum InputType { String, Float, Integer }
Public Slots
virtual void setText (const QString &)
virtual void setButtonText (const QString &)
virtual void validateText (const QString &)
Signals
void textChanged (const QString &)
Public Member Functions
LabelEditor (QWidget *parent=nullptr)
~LabelEditor () override
QString text () const
QString buttonText () const
void setInputType (InputType)
Protected Member Functions
void resizeEvent (QResizeEvent *) override
Properties
QString text
QString buttonText
Detailed Description
Definition at line 523 of file Widgets.h.
Member Enumeration Documentation
InputType
enum Gui::LabelEditor::InputType
Enumerator
String
Float
Integer
Definition at line 531 of file Widgets.h.
Constructor & Destructor Documentation
LabelEditor()
LabelEditor::LabelEditor (QWidget * parent = nullptr)
Definition at line 1444 of file Widgets.cpp.
References draftgeoutils.intersections::connect(), String, and validateText().
~LabelEditor()
LabelEditor::~LabelEditor () override default
Member Function Documentation
buttonText()
QString Gui::LabelEditor::buttonText () const
Returns the button's text.
resizeEvent()
void LabelEditor::resizeEvent (QResizeEvent * e) override protected
Definition at line 1471 of file Widgets.cpp.
References SCL.SimpleDataTypes::e.
setButtonText
void LabelEditor::setButtonText (const QString & txt) virtual slot
Sets the browse button's text to txt.
Definition at line 1530 of file Widgets.cpp.
References Gui::QtTools::horizontalAdvance(), and create_qrc::txt.
setInputType()
void LabelEditor::setInputType (InputType t)
Set the input type.
Definition at line 1546 of file Widgets.cpp.
References InitGui::t.
setText
void LabelEditor::setText (const QString & s) virtual slot
Definition at line 1482 of file Widgets.cpp.
References toolbit-attributes::s.
Referenced by src.Mod.AddonManager.Widgets.addonmanager_widget_readme_browser.WidgetReadmeBrowser::setMarkdown().
text()
QString Gui::LabelEditor::text () const
Returns the text.
textChanged
void Gui::LabelEditor::textChanged (const QString &) signal
Referenced by Gui::PropertyEditor::PropertyStringListItem::createEditor(), Gui::PropertyEditor::PropertyFloatListItem::createEditor(), Gui::PropertyEditor::PropertyIntegerListItem::createEditor(), and validateText().
validateText
void LabelEditor::validateText (const QString & text) virtual slot
Validates if the input of the lineedit is a valid list.
Definition at line 1519 of file Widgets.cpp.
References textChanged().
Referenced by LabelEditor().
Property Documentation
buttonText
QString LabelEditor::buttonText read write
Returns the browse button's text.
Definition at line 528 of file Widgets.h.
text
QString LabelEditor::text read write
Definition at line 527 of file Widgets.h.
Referenced by importSVG.svgHandler::characters(), bimcommands.BimText.BIM_Text::createObject(), draftguitools.gui_texts.Text::createObject(), draftviewproviders.view_text.ViewProviderText::createObject(), importSVG.svgHandler::endElement(), importers.exportIFCHelper.SIUnitCreator::getSIPrefix(), importers.exportIFCHelper.SIUnitCreator::getSIUnitName(), and src.Mod.Test.unittestgui.ProgressBar::paint().
The documentation for this class was generated from the following files:
Widgets.h
Widgets.cpp