FreeCAD: SketcherGui::CoinMapping Struct Reference
SketcherGui::CoinMapping Struct Reference
Helper struct containing index conversions (mappings) between {GeoId, PointPos} and MF indices per layer, sublayers, and VertexId and MF indices per layer.
#include <EditModeCoinManagerParameters.h>
Public Member Functions
void clear ()
int getCurveGeoId (int curveindex, int layerindex, int sublayerindex=0)
int getPointGeoId (int pointindex, int layerindex)
Sketcher::PointPos getPointPosId (int pointindex, int layerindex)
int getPointVertexId (int pointindex, int layerindex)
MultiFieldId getIndexLayer (int geoid, Sketcher::PointPos pos)
MultiFieldId getIndexLayer (int vertexId)
Public Attributes
std::vector< std::vector< std::vector< int > > > CurvIdToGeoId
std::vector< std::vector< int > > PointIdToGeoId
std::vector< std::vector< Sketcher::PointPos > > PointIdToPosId
std::vector< std::vector< int > > PointIdToVertexId
std::map< Sketcher::GeoElementId, MultiFieldId > GeoElementId2SetId
Detailed Description
Helper struct containing index conversions (mappings) between {GeoId, PointPos} and MF indices per layer, sublayers, and VertexId and MF indices per layer.
These are updated with every draw of the scenegraph.
Definition at line 453 of file EditModeCoinManagerParameters.h.
Member Function Documentation
clear()
void SketcherGui::CoinMapping::clear () inline
Definition at line 456 of file EditModeCoinManagerParameters.h.
References CurvIdToGeoId, GeoElementId2SetId, RobotExample::l, PointIdToGeoId, PointIdToPosId, and PointIdToVertexId.
Referenced by src.Mod.Test.Document.DocumentObserverCases.Observer::__init__(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::__init__(), and SketcherGui::EditModeGeometryCoinConverter::convert().
getCurveGeoId()
int SketcherGui::CoinMapping::getCurveGeoId (int curveindex, int layerindex, int sublayerindex = 0) inline
given the MF index of a curve and the coin layer in which it is drawn returns the GeoId of the curve
Definition at line 470 of file EditModeCoinManagerParameters.h.
References CurvIdToGeoId.
Referenced by SketcherGui::EditModeCoinManager::detectPreselection(), and SketcherGui::EditModeGeometryCoinManager::updateGeometryColor().
getIndexLayer() [1/2]
MultiFieldId SketcherGui::CoinMapping::getIndexLayer (int geoid, Sketcher::PointPos pos) inline
given the {GeoId, PointPos} of a curve or point, returns MultiFieldId containing the MF index and the coin layer of the curve or point
Definition at line 495 of file EditModeCoinManagerParameters.h.
References GeoElementId2SetId, SketcherGui::MultiFieldId::Invalid, and RobotExample::pos.
Referenced by SketcherGui::EditModeConstraintCoinManager::updateConstraintColor(), and SketcherGui::EditModeGeometryCoinManager::updateGeometryColor().
getIndexLayer() [2/2]
MultiFieldId SketcherGui::CoinMapping::getIndexLayer (int vertexId) inline
given the VertexId of a point, returns MultiFieldId containing the MF index and the coin layer of the point
Definition at line 508 of file EditModeCoinManagerParameters.h.
References DraftVecUtils::find(), SketcherGui::MultiFieldId::Invalid, RobotExample::l, and PointIdToVertexId.
getPointGeoId()
int SketcherGui::CoinMapping::getPointGeoId (int pointindex, int layerindex) inline
given the MF index of a point and the coin layer in which it is drawn returns the GeoId of the point
Definition at line 476 of file EditModeCoinManagerParameters.h.
References PointIdToGeoId.
Referenced by SketcherGui::EditModeGeometryCoinManager::updateGeometryColor().
getPointPosId()
Sketcher::PointPos SketcherGui::CoinMapping::getPointPosId (int pointindex, int layerindex) inline
given the MF index of a point and the coin layer in which it is drawn returns the PosId of the point
Definition at line 482 of file EditModeCoinManagerParameters.h.
References PointIdToPosId.
Referenced by SketcherGui::EditModeGeometryCoinManager::updateGeometryColor().
getPointVertexId()
int SketcherGui::CoinMapping::getPointVertexId (int pointindex, int layerindex) inline
given the MF index of a point and the coin layer in which it is drawn returns the VertexId of the point
Definition at line 488 of file EditModeCoinManagerParameters.h.
References PointIdToVertexId.
Referenced by SketcherGui::EditModeCoinManager::detectPreselection().
Member Data Documentation
CurvIdToGeoId
std::vector<std::vector<std::vector<int> > > SketcherGui::CoinMapping::CurvIdToGeoId
Definition at line 526 of file EditModeCoinManagerParameters.h.
Referenced by clear(), SketcherGui::EditModeGeometryCoinConverter::convert(), and getCurveGeoId().
GeoElementId2SetId
std::map<Sketcher::GeoElementId, MultiFieldId> SketcherGui::CoinMapping::GeoElementId2SetId
This maps GeoElementId index {GeoId, PointPos} to a {coin layer and MF index} of a curve or point.
Definition at line 536 of file EditModeCoinManagerParameters.h.
Referenced by clear(), SketcherGui::EditModeGeometryCoinConverter::convert(), and getIndexLayer().
PointIdToGeoId
std::vector<std::vector<int> > SketcherGui::CoinMapping::PointIdToGeoId
Definition at line 527 of file EditModeCoinManagerParameters.h.
Referenced by clear(), SketcherGui::EditModeGeometryCoinConverter::convert(), and getPointGeoId().
PointIdToPosId
std::vector<std::vector<Sketcher::PointPos> > SketcherGui::CoinMapping::PointIdToPosId
Definition at line 528 of file EditModeCoinManagerParameters.h.
Referenced by clear(), SketcherGui::EditModeGeometryCoinConverter::convert(), and getPointPosId().
PointIdToVertexId
std::vector<std::vector<int> > SketcherGui::CoinMapping::PointIdToVertexId
Definition at line 532 of file EditModeCoinManagerParameters.h.
Referenced by clear(), SketcherGui::EditModeGeometryCoinConverter::convert(), getIndexLayer(), and getPointVertexId().
The documentation for this struct was generated from the following file:
EditModeCoinManagerParameters.h