FreeCAD: AppWeb.cpp File Reference
AppWeb.cpp File Reference
#include "PreCompiled.h"
#include <sstream>
#include <Base/Console.h>
#include <Base/Interpreter.h>
#include <Base/PyObjectBase.h>
#include "Server.h"
Classes
class Web::Module
Namespaces
Web
Functions
PyObject * Web::initModule ()
PyMOD_INIT_FUNC (Web)
Function Documentation
PyMOD_INIT_FUNC()
PyMOD_INIT_FUNC (Web)
Definition at line 182 of file AppWeb.cpp.
References Base::Console(), Web::initModule(), Base::ConsoleSingleton::Log(), mod, and PyMOD_Return.