FreeCAD: TechDrawGui::TaskDlgProjGroup Class Reference
TechDrawGui::TaskDlgProjGroup Class Reference
#include <TaskProjGroup.h>
Public Member Functions
TaskDlgProjGroup (TechDraw::DrawView *featView, bool mode)
~TaskDlgProjGroup () override=default
const ViewProviderDrawingView * getViewProvider () const
TechDraw::DrawView * getView () const
QDialogButtonBox::StandardButtons getStandardButtons () const override
tells the framework which buttons are wished for the dialog
void modifyStandardButtons (QDialogButtonBox *box) override
void open () override
is called the TaskView when the dialog is opened
void clicked (int ikey) override
is called by the framework if an button is clicked which has no accept or reject role
bool accept () override
is called by the framework if the dialog is accepted (Ok)
bool reject () override
is called by the framework if the dialog is rejected (Cancel)
bool isAllowedAlterDocument () const override
is called by the framework if the user presses the help button
void setCreateMode (bool mode)
void update ()
Public Member Functions inherited from Gui::TaskView::TaskDialog
TaskDialog ()
~TaskDialog () override
QWidget * addTaskBox (QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBox (const QPixmap &icon, QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBoxWithoutHeader (QWidget *widget)
void setButtonPosition (ButtonPosition p)
ButtonPosition buttonPosition () const
const std::vector< QWidget * > & getDialogContent () const
bool canClose () const
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
bool isEscapeButtonEnabled () const
void setAutoCloseOnTransactionChange (bool on)
bool isAutoCloseOnTransactionChange () const
void setAutoCloseOnDeletedDocument (bool on)
bool isAutoCloseOnDeletedDocument () const
const std::string & getDocumentName () const
void setDocumentName (const std::string &doc)
void setAutoCloseOnClosedView (bool on)
bool isAutoCloseOnClosedView () const
void associateToObject3dView (App::DocumentObject *obj)
const Gui::MDIView * getAssociatedView () const
void setAssociatedView (const Gui::MDIView *view)
virtual bool isAllowedAlterView () const
virtual bool isAllowedAlterSelection () const
virtual bool needsFullSpace () const
virtual void closed ()
is called by the framework when the dialog is closed
virtual void autoClosedOnTransactionChange ()
virtual void autoClosedOnDeletedDocument ()
virtual void autoClosedOnClosedView ()
virtual void helpRequested ()
is called by the framework if the user press the help button
void emitDestructionSignal ()
Protected Attributes
const ViewProviderDrawingView * viewProvider
TechDraw::DrawView * view
Protected Attributes inherited from Gui::TaskView::TaskDialog
QPointer< QDialogButtonBox > buttonBox
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North, South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Detailed Description
Definition at line 141 of file TaskProjGroup.h.
Constructor & Destructor Documentation
TaskDlgProjGroup()
TaskDlgProjGroup::TaskDlgProjGroup (TechDraw::DrawView * featView, bool mode)
Definition at line 842 of file TaskProjGroup.cpp.
References Gui::BitmapFactory(), Gui::TaskView::TaskDialog::Content, and QSint::ActionGroup::groupLayout().
~TaskDlgProjGroup()
TechDrawGui::TaskDlgProjGroup::~TaskDlgProjGroup () override default
Member Function Documentation
accept()
bool TaskDlgProjGroup::accept () override virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 893 of file TaskProjGroup.cpp.
References TechDrawGui::TaskProjGroup::accept().
clicked()
void TaskDlgProjGroup::clicked (int ikey) override virtual
is called by the framework if an button is clicked which has no accept or reject role
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 885 of file TaskProjGroup.cpp.
References TechDrawGui::TaskProjGroup::apply(), and SplineSurface::i.
getStandardButtons()
QDialogButtonBox::StandardButtons TechDrawGui::TaskDlgProjGroup::getStandardButtons () const inline override virtual
tells the framework which buttons are wished for the dialog
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 152 of file TaskProjGroup.h.
getView()
TechDraw::DrawView* TechDrawGui::TaskDlgProjGroup::getView () const inline
Definition at line 150 of file TaskProjGroup.h.
References view.
getViewProvider()
const ViewProviderDrawingView* TechDrawGui::TaskDlgProjGroup::getViewProvider () const inline
Definition at line 149 of file TaskProjGroup.h.
References viewProvider.
isAllowedAlterDocument()
bool TechDrawGui::TaskDlgProjGroup::isAllowedAlterDocument () const inline override virtual
is called by the framework if the user presses the help button
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 165 of file TaskProjGroup.h.
modifyStandardButtons()
void TaskDlgProjGroup::modifyStandardButtons (QDialogButtonBox * box) override virtual
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 864 of file TaskProjGroup.cpp.
References MengerSponge::box, and TechDrawGui::TaskProjGroup::saveButtons().
open()
void TaskDlgProjGroup::open () override virtual
is called the TaskView when the dialog is opened
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 873 of file TaskProjGroup.cpp.
References App::GetApplication(), TechDrawGui::TaskProjGroup::getCreateMode(), App::Application::setActiveTransaction(), and view.
reject()
bool TaskDlgProjGroup::reject () override virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 899 of file TaskProjGroup.cpp.
References TechDrawGui::TaskProjGroup::reject().
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action().
setCreateMode()
void TaskDlgProjGroup::setCreateMode (bool mode)
Definition at line 859 of file TaskProjGroup.cpp.
References TechDrawGui::TaskProjGroup::setCreateMode().
update()
void TaskDlgProjGroup::update ()
Definition at line 854 of file TaskProjGroup.cpp.
References TechDrawGui::TaskProjGroup::updateTask().
Member Data Documentation
view
TechDraw::DrawView* TechDrawGui::TaskDlgProjGroup::view protected
Definition at line 173 of file TaskProjGroup.h.
Referenced by TechDrawTools.TaskAddOffsetVertex.TaskAddOffsetVertex::accept(), getView(), open(), src.Mod.AddonManager.Widgets.addonmanager_widget_filter_selector.WidgetFilterSelector::set_status_filter(), TDTest.DrawViewDimensionTest.DrawViewDimensionTest::testLengthDimension(), TDTest.DrawViewDetailTest.DrawViewDetailTest::testMakeDrawViewPart(), TDTest.DrawViewSectionTest.DrawViewSectionTest::testMakeDrawViewSection(), and TDTest.DrawHatchTest.DrawHatchTest::testMakeHatchCase().
viewProvider
const ViewProviderDrawingView* TechDrawGui::TaskDlgProjGroup::viewProvider protected
Definition at line 172 of file TaskProjGroup.h.
Referenced by getViewProvider().
The documentation for this class was generated from the following files:
TaskProjGroup.h
TaskProjGroup.cpp