FreeCAD: Data Namespace Reference
Data Namespace Reference
Classes
struct ByteArray
struct ByteArrayHasher
class ComplexGeoData
class ElementMap
struct ElementNameComparator
struct HistoryItem
class IndexedName
struct MappedElement
class MappedName
struct MappedNameRef
class Segment
Typedefs
typedef Base::Flags< SearchOption > SearchOptions
using ElementMapPtr = std::shared_ptr< ElementMap >
typedef std::function< bool(const MappedName &, int, long, long)> TraceCallback
using ElementIDRefs = QVector<::App::StringIDRef >
Enumerations
enum SearchOption { SearchOption::CheckGeometry = 1, SearchOption::SingleResult = 2 }
Option for App::GeoFeature::searchElementCache()
enum ElementMapResetPolicy { AllowNoMap, ForceEmptyMap }
Functions
AppExport bool hasMissingElement (const char *subname)
Check if a subname contains missing element.
const AppExport char * isMappedElement (const char *name)
AppExport std::string newElementName (const char *name)
Strip out the trailing element name if there is mapped element name precedes it.
AppExport std::string oldElementName (const char *name)
Strip out the mapped element name if there is one.
AppExport std::string noElementName (const char *name)
Strip out the old and new element name if there is one.
const AppExport char * findElementName (const char *subname)
Find the start of an element name in a subname.
const AppExport char * hasMappedElementName (const char *subname)
const AppExport std::string indexSuffix (int index, const char *label=ELEMENT_MAP_INDEX)
Variables
static std::unordered_map< const ElementMap *, unsigned > _elementMapToId
static std::unordered_map< unsigned, ElementMapPtr > _idToElementMap
constexpr const char * ELEMENT_MAP_PREFIX = ";"
Special prefix to mark the beginning of a mapped sub-element name.
constexpr size_t ELEMENT_MAP_PREFIX_SIZE = 1
constexpr const char * MISSING_PREFIX = "?"
Special prefix to mark a missing element.
constexpr const char * MAPPED_CHILD_ELEMENTS_PREFIX = ";:R"
constexpr const char * POSTFIX_TAG = ";:H"
Special postfix to mark the following tag.
constexpr size_t POSTFIX_TAG_SIZE = 3
constexpr const char * POSTFIX_DECIMAL_TAG = ";:T"
constexpr const char * POSTFIX_EXTERNAL_TAG = ";:X"
constexpr const char * POSTFIX_CHILD = ";:C"
constexpr const char * POSTFIX_INDEX = ";:I"
Special postfix to mark the index of an array element.
constexpr const char * POSTFIX_UPPER = ";:U"
constexpr const char * POSTFIX_LOWER = ";:L"
constexpr const char * POSTFIX_MOD = ";:M"
constexpr const char * POSTFIX_GEN = ";:G"
constexpr const char * POSTFIX_MODGEN = ";:MG"
constexpr const char * POSTFIX_DUPLICATE = ";D"
constexpr const char * ELEMENT_MAP_INDEX = "_"
Typedef Documentation
ElementIDRefs
using Data::ElementIDRefs = typedef QVector<::App::StringIDRef>
Definition at line 953 of file MappedName.h.
ElementMapPtr
using Data::ElementMapPtr = typedef std::shared_ptr<ElementMap>
Definition at line 67 of file ElementMap.h.
SearchOptions
typedef Base::Flags<SearchOption> Data::SearchOptions
Definition at line 66 of file ComplexGeoData.h.
TraceCallback
typedef std::function<bool(const MappedName&, int, long, long)> Data::TraceCallback
Element trace callback
The callback has the following call signature (const std::string &name, size_t offset, long encodedTag, long tag) -> bool
Parameters
name the current element name.
offset the offset skipping the encoded element name for the next iteration.
encodedTag the tag encoded inside the current element, which is usually the tag of the previous step in the shape history.
tag the tag of the current shape element.
See also
traceElement()
Definition at line 82 of file ElementMap.h.
Enumeration Type Documentation
ElementMapResetPolicy
enum Data::ElementMapResetPolicy
Enumerator
AllowNoMap
ForceEmptyMap
Definition at line 81 of file ComplexGeoData.h.
SearchOption
enum Data::SearchOption strong
Option for App::GeoFeature::searchElementCache()
Enumerator
CheckGeometry
Whether to compare shape geometry.
SingleResult
Definition at line 60 of file ComplexGeoData.h.
Function Documentation
findElementName()
const char * Data::findElementName (const char * subname)
Find the start of an element name in a subname.
Definition at line 71 of file ElementNamingUtils.cpp.
References dot(), and isMappedElement().
Referenced by _getTopoShape(), App::PropertyLinkBase::_updateElementReference(), StdCmdLinkMakeRelative::activated(), Gui::DocumentP::findElementName(), Part::Feature::getElementFromSource(), App::SubObjectT::getElementName(), PartDesign::Feature::getFeatureBody(), PartDesign::SubShapeBinder::getSubObject(), Sketcher::SketchObject::getSubObject(), App::PropertyLinkSub::getSubValuesStartsWith(), Part::Feature::getTopoShape(), hasMappedElementName(), App::SubObjectT::hasSubObject(), Data::ComplexGeoData::isElementName(), noElementName(), Part::Feature::onBeforeChange(), App::LinkBaseExtension::onExtendedDocumentRestored(), App::LinkBaseExtension::parseSubName(), App::GeoFeature::resolveElement(), Gui::LinkView::setLinkViewObject(), and Gui::DocumentP::tryStartEditing().
hasMappedElementName()
const char * Data::hasMappedElementName (const char * subname)
Definition at line 112 of file ElementNamingUtils.cpp.
References findElementName(), and isMappedElement().
Referenced by App::PropertyLinkBase::_updateElementReference().
hasMissingElement()
bool Data::hasMissingElement (const char * subname)
Check if a subname contains missing element.
Definition at line 100 of file ElementNamingUtils.cpp.
References dot(), and MISSING_PREFIX.
Referenced by App::PropertyLinkBase::_updateElementReference(), Attacher::AttachEngine::calculateAttachedPlacement(), Part::Feature::getExportElementName(), getSubNameWithStyle(), App::GeoFeature::hasMissingElement(), Part::Feature::onBeforeChange(), and Part::TopoShape::shapeType().
indexSuffix()
const std::string Data::indexSuffix (int index, const char * label = ELEMENT_MAP_INDEX)
Definition at line 117 of file ElementNamingUtils.cpp.
Referenced by PartDesign::Transformed::execute().
isMappedElement()
const char * Data::isMappedElement (const char * name)
Check if the name starts with elementMapPrefix()
Parameters
name input name
Returns
Returns the name stripped with elementMapPrefix(), or 0 if not start with the prefix
Definition at line 7 of file ElementNamingUtils.cpp.
References ELEMENT_MAP_PREFIX, and ELEMENT_MAP_PREFIX_SIZE.
Referenced by Gui::View3DInventorSelection::checkGroupOnTop(), Sketcher::SketchObject::checkSubName(), Gui::SoFCUnifiedSelection::doAction(), Data::ComplexGeoData::elementType(), App::LinkBaseExtension::extensionGetSubObject(), findElementName(), App::LinkBaseExtension::getArrayIndex(), Gui::LinkInfo::getDetail(), Part::Feature::getElementFromSource(), Part::Feature::getElementHistory(), App::LinkBaseExtension::getElementIndex(), Data::ComplexGeoData::getElementName(), Sketcher::SketchObject::getElementName(), Part::Feature::getSubObject(), PartDesign::Body::getSubObject(), Sketcher::SketchObject::getSubObject(), hasMappedElementName(), newElementName(), and oldElementName().
newElementName()
std::string Data::newElementName (const char * name)
Strip out the trailing element name if there is mapped element name precedes it.
Definition at line 15 of file ElementNamingUtils.cpp.
References SCL.SimpleDataTypes::c, dot(), and isMappedElement().
Referenced by Part::Feature::getElementFromSource(), Part::Feature::getElementHistory(), Gui::SelectionSingleton::setPreselect(), Gui::SelectionSingleton::slotSelectionChanged(), and Sketcher::SketchObject::updateGeometryRefs().
noElementName()
std::string Data::noElementName (const char * name)
Strip out the old and new element name if there is one.
Definition at line 59 of file ElementNamingUtils.cpp.
References findElementName().
Referenced by StdCmdLinkMakeRelative::activated(), Part::Feature::getElementFromSource(), App::SubObjectT::getSubNameNoElement(), PartDesign::SubShapeBinder::getSubObject(), and Gui::ElementColors::Private::Private().
oldElementName()
std::string Data::oldElementName (const char * name)
Strip out the mapped element name if there is one.
Definition at line 37 of file ElementNamingUtils.cpp.
References SCL.SimpleDataTypes::c, dot(), and isMappedElement().
Referenced by Gui::ElementColors::Private::addItem(), Attacher::AttachEngine::calculateAttachedPlacement(), App::GeoFeature::resolveElement(), Gui::SelectionSingleton::setPreselect(), Gui::SelectionSingleton::slotSelectionChanged(), PartDesign::SubShapeBinder::update(), and Sketcher::SketchObject::updateGeometryRefs().
Variable Documentation
_elementMapToId
std::unordered_map<const ElementMap*, unsigned> Data::_elementMapToId static
Definition at line 44 of file ElementMap.cpp.
Referenced by Data::ElementMap::beforeSave().
_idToElementMap
std::unordered_map<unsigned, ElementMapPtr> Data::_idToElementMap static
Definition at line 45 of file ElementMap.cpp.
Referenced by Data::ElementMap::restore().
ELEMENT_MAP_INDEX
constexpr const char* Data::ELEMENT_MAP_INDEX = "_" constexpr
Definition at line 72 of file ElementNamingUtils.h.
ELEMENT_MAP_PREFIX
constexpr const char* Data::ELEMENT_MAP_PREFIX = ";" constexpr
Special prefix to mark the beginning of a mapped sub-element name.
Definition at line 44 of file ElementNamingUtils.h.
Referenced by Data::ElementMap::addChildElements(), Sketcher::SketchObject::convertSubName(), Data::ComplexGeoData::elementMapPrefix(), Data::ElementMap::encodeElementName(), Data::MappedName::findTagInElementName(), Data::ElementMap::getElementHistory(), isMappedElement(), Data::MappedName::toBytes(), and Data::ElementMap::traceElement().
ELEMENT_MAP_PREFIX_SIZE
constexpr size_t Data::ELEMENT_MAP_PREFIX_SIZE = 1 constexpr
Definition at line 45 of file ElementNamingUtils.h.
Referenced by Data::ElementMap::getElementHistory(), isMappedElement(), and Data::ElementMap::traceElement().
MAPPED_CHILD_ELEMENTS_PREFIX
constexpr const char* Data::MAPPED_CHILD_ELEMENTS_PREFIX = ";:R" constexpr
Definition at line 53 of file ElementNamingUtils.h.
Referenced by Data::ElementMap::getElementHistory(), and Data::ElementMap::hashChildMaps().
MISSING_PREFIX
constexpr const char* Data::MISSING_PREFIX = "?" constexpr
Special prefix to mark a missing element.
Definition at line 48 of file ElementNamingUtils.h.
Referenced by App::GeoFeature::_getElementName(), Sketcher::SketchObject::getElementName(), Part::Feature::getExportElementName(), hasMissingElement(), and PartDesignGui::TaskDlgDressUpParameters::TaskDlgDressUpParameters().
POSTFIX_CHILD
constexpr const char* Data::POSTFIX_CHILD = ";:C" constexpr
Definition at line 61 of file ElementNamingUtils.h.
POSTFIX_DECIMAL_TAG
constexpr const char* Data::POSTFIX_DECIMAL_TAG = ";:T" constexpr
Definition at line 59 of file ElementNamingUtils.h.
Referenced by Data::MappedName::findTagInElementName().
POSTFIX_DUPLICATE
constexpr const char* Data::POSTFIX_DUPLICATE = ";D" constexpr
Definition at line 70 of file ElementNamingUtils.h.
POSTFIX_EXTERNAL_TAG
constexpr const char* Data::POSTFIX_EXTERNAL_TAG = ";:X" constexpr
Definition at line 60 of file ElementNamingUtils.h.
Referenced by App::LinkBaseExtension::checkGeoElementMap(), Data::ElementMap::traceElement(), and PartDesign::SubShapeBinder::update().
POSTFIX_GEN
constexpr const char* Data::POSTFIX_GEN = ";:G" constexpr
Definition at line 68 of file ElementNamingUtils.h.
Referenced by FC_LOG_LEVEL_INIT().
POSTFIX_INDEX
constexpr const char* Data::POSTFIX_INDEX = ";:I" constexpr
Special postfix to mark the index of an array element.
Definition at line 64 of file ElementNamingUtils.h.
Referenced by _getTopoShape(), App::LinkBaseExtension::extensionGetSubObject(), and Part::Feature::getExportElementName().
POSTFIX_LOWER
constexpr const char* Data::POSTFIX_LOWER = ";:L" constexpr
Definition at line 66 of file ElementNamingUtils.h.
Referenced by FC_LOG_LEVEL_INIT().
POSTFIX_MOD
constexpr const char* Data::POSTFIX_MOD = ";:M" constexpr
Definition at line 67 of file ElementNamingUtils.h.
Referenced by FC_LOG_LEVEL_INIT().
POSTFIX_MODGEN
constexpr const char* Data::POSTFIX_MODGEN = ";:MG" constexpr
Definition at line 69 of file ElementNamingUtils.h.
Referenced by FC_LOG_LEVEL_INIT().
POSTFIX_TAG
constexpr const char* Data::POSTFIX_TAG = ";:H" constexpr
Special postfix to mark the following tag.
Definition at line 56 of file ElementNamingUtils.h.
Referenced by Data::ElementMap::encodeElementName(), and Data::MappedName::findTagInElementName().
POSTFIX_TAG_SIZE
constexpr size_t Data::POSTFIX_TAG_SIZE = 3 constexpr
Definition at line 57 of file ElementNamingUtils.h.
Referenced by Data::MappedName::findTagInElementName(), and Data::ElementMap::getElementHistory().
POSTFIX_UPPER
constexpr const char* Data::POSTFIX_UPPER = ";:U" constexpr
Definition at line 65 of file ElementNamingUtils.h.
Referenced by FC_LOG_LEVEL_INIT().