FreeCAD: Gui::Dialog::DlgCustomizeSpaceball Class Reference
Gui::Dialog::DlgCustomizeSpaceball Class Reference
#include <DlgCustomizeSpaceball.h>
Public Member Functions
DlgCustomizeSpaceball (QWidget *parent=nullptr)
~DlgCustomizeSpaceball () override
Public Member Functions inherited from Gui::Dialog::CustomizeActionPage
CustomizeActionPage (QWidget *parent=nullptr)
~CustomizeActionPage () override
Protected Slots
void onAddMacroAction (const QByteArray &macroName) override
void onRemoveMacroAction (const QByteArray &macroName) override
void onModifyMacroAction (const QByteArray &macroName) override
Protected Slots inherited from Gui::Dialog::CustomizeActionPage
virtual void onAddMacroAction (const QByteArray &)=0
virtual void onRemoveMacroAction (const QByteArray &)=0
virtual void onModifyMacroAction (const QByteArray &)=0
Protected Member Functions
void changeEvent (QEvent *e) override
bool event (QEvent *event) override
void hideEvent (QHideEvent *event) override
void showEvent (QShowEvent *event) override
Protected Member Functions inherited from Gui::Dialog::CustomizeActionPage
bool event (QEvent *e) override
Detailed Description
Definition at line 141 of file DlgCustomizeSpaceball.h.
Constructor & Destructor Documentation
DlgCustomizeSpaceball()
DlgCustomizeSpaceball::DlgCustomizeSpaceball (QWidget * parent = nullptr) explicit
Definition at line 662 of file DlgCustomizeSpaceball.cpp.
References src.Mod.AddonManager.AddonManagerTest.gui.test_python_deps_gui::app, Gui::Dialog::ButtonView::changeCommandSelection(), Gui::Dialog::CommandView::changedCommand(), draftgeoutils.intersections::connect(), Gui::Dialog::CommandView::goChangeCommandSelection(), and Gui::Dialog::ButtonView::goChangedCommand().
~DlgCustomizeSpaceball()
DlgCustomizeSpaceball::~DlgCustomizeSpaceball () override default
Member Function Documentation
changeEvent()
void DlgCustomizeSpaceball::changeEvent (QEvent * e) override protected virtual
Implements Gui::Dialog::CustomizeActionPage.
Definition at line 846 of file DlgCustomizeSpaceball.cpp.
References SCL.SimpleDataTypes::e.
event()
bool DlgCustomizeSpaceball::event (QEvent * event) override protected
Definition at line 807 of file DlgCustomizeSpaceball.cpp.
References Spaceball::BUTTON_PRESSED, Spaceball::ButtonEvent::ButtonEventType, Gui::Dialog::CustomizeActionPage::event(), Gui::Dialog::ButtonModel::goButtonPress(), Gui::Dialog::ButtonView::selectButton(), and Spaceball::EventBase::setHandled().
Referenced by hideEvent(), and showEvent().
hideEvent()
void DlgCustomizeSpaceball::hideEvent (QHideEvent * event) override protected
Definition at line 822 of file DlgCustomizeSpaceball.cpp.
References event().
onAddMacroAction
void DlgCustomizeSpaceball::onAddMacroAction (const QByteArray & macroName) override protected slot
Definition at line 856 of file DlgCustomizeSpaceball.cpp.
References Gui::Dialog::CommandModel::goAddMacro().
onModifyMacroAction
void DlgCustomizeSpaceball::onModifyMacroAction (const QByteArray & macroName) override protected slot
Definition at line 873 of file DlgCustomizeSpaceball.cpp.
onRemoveMacroAction
void DlgCustomizeSpaceball::onRemoveMacroAction (const QByteArray & macroName) override protected slot
Definition at line 863 of file DlgCustomizeSpaceball.cpp.
References Gui::Dialog::ButtonModel::goMacroRemoved(), and Gui::Dialog::CommandModel::goRemoveMacro().
showEvent()
void DlgCustomizeSpaceball::showEvent (QShowEvent * event) override protected
Definition at line 838 of file DlgCustomizeSpaceball.cpp.
References event().
The documentation for this class was generated from the following files:
DlgCustomizeSpaceball.h
DlgCustomizeSpaceball.cpp