FreeCAD: Base::Rotation Class Reference
Base::Rotation Class Reference
#include <Rotation.h>
Public Types
enum EulerSequence {
Invalid, EulerAngles, YawPitchRoll, Extrinsic_XYZ,
Extrinsic_XZY, Extrinsic_YZX, Extrinsic_YXZ, Extrinsic_ZXY,
Extrinsic_ZYX, Intrinsic_XYZ, Intrinsic_XZY, Intrinsic_YZX,
Intrinsic_YXZ, Intrinsic_ZXY, Intrinsic_ZYX, Extrinsic_XYX,
Extrinsic_XZX, Extrinsic_YZY, Extrinsic_YXY, Extrinsic_ZYZ,
Extrinsic_ZXZ, Intrinsic_XYX, Intrinsic_XZX, Intrinsic_YZY,
Intrinsic_YXY, Intrinsic_ZXZ, Intrinsic_ZYZ, EulerSequenceLast
}
Public Member Functions
Rotation ()
Rotation (const Vector3d &axis, double fAngle)
Rotation (const Matrix4D &matrix)
Rotation (const double q[4])
Rotation (double q0, double q1, double q2, double q3)
Rotation (const Vector3d &rotateFrom, const Vector3d &rotateTo)
Rotation (const Rotation &rot)=default
Rotation (Rotation &&rot)=default
~Rotation ()=default
const double * getValue () const
void getValue (double &q0, double &q1, double &q2, double &q3) const
void setValue (double q0, double q1, double q2, double q3)
void getValue (Vector3d &axis, double &rfAngle) const
If not a null quaternion then axis will be normalized.
void getRawValue (Vector3d &axis, double &rfAngle) const
Does the same as the method above unless normalizing the axis.
void getValue (Matrix4D &matrix) const
void setValue (const double q[4])
void setValue (const Matrix4D &matrix)
void setValue (const Vector3d &axis, double fAngle)
void setValue (const Vector3d &rotateFrom, const Vector3d &rotateTo)
void setYawPitchRoll (double y, double p, double r)
Euler angles in yaw,pitch,roll notation.
void getYawPitchRoll (double &y, double &p, double &r) const
Euler angles in yaw,pitch,roll notation.
void getEulerAngles (EulerSequence theOrder, double &alpha, double &beta, double &gamma) const
void setEulerAngles (EulerSequence theOrder, double alpha, double beta, double gamma)
bool isIdentity () const
bool isIdentity (double tol) const
bool isNull () const
bool isSame (const Rotation &) const
bool isSame (const Rotation &, double tol) const
Rotation & invert ()
Rotation inverse () const
Rotation & operator*= (const Rotation &q)
Rotation operator* (const Rotation &q) const
bool operator== (const Rotation &q) const
bool operator!= (const Rotation &q) const
double & operator[] (unsigned short usIndex)
const double & operator[] (unsigned short usIndex) const
Rotation & operator= (const Rotation &)=default
Rotation & operator= (Rotation &&)=default
Rotation & multRight (const Base::Rotation &q)
Rotation & multLeft (const Base::Rotation &q)
void multVec (const Vector3d &src, Vector3d &dst) const
Vector3d multVec (const Vector3d &src) const
void multVec (const Vector3f &src, Vector3f &dst) const
Vector3f multVec (const Vector3f &src) const
void scaleAngle (double scaleFactor)
Static Public Member Functions
static Rotation fromNormalVector (const Vector3d &normal)
static Rotation fromEulerAngles (EulerSequence theOrder, double alpha, double beta, double gamma)
Utility function to create Rotation based on euler angles.
static const char * eulerSequenceName (EulerSequence seq)
static EulerSequence eulerSequenceFromName (const char *name)
static Rotation slerp (const Rotation &q0, const Rotation &q1, double t)
static Rotation identity ()
static Rotation makeRotationByAxes (Vector3d xdir, Vector3d ydir, Vector3d zdir, const char *priorityOrder="ZXY")
makeRotationByAxes(xdir, ydir, zdir, priorityOrder): creates a rotation that converts a vector in local cs with axes given as arguments, into a vector in global cs.
Detailed Description
Definition at line 58 of file Rotation.h.
Member Enumeration Documentation
EulerSequence
enum Base::Rotation::EulerSequence
Enumerator
Invalid
EulerAngles
Classic Euler angles, alias to Intrinsic_ZXZ.
YawPitchRoll
Yaw Pitch Roll (or nautical) angles, alias to Intrinsic_ZYX.
Extrinsic_XYZ
Extrinsic_XZY
Extrinsic_YZX
Extrinsic_YXZ
Extrinsic_ZXY
Extrinsic_ZYX
Intrinsic_XYZ
Intrinsic_XZY
Intrinsic_YZX
Intrinsic_YXZ
Intrinsic_ZXY
Intrinsic_ZYX
Extrinsic_XYX
Extrinsic_XZX
Extrinsic_YZY
Extrinsic_YXY
Extrinsic_ZYZ
Extrinsic_ZXZ
Intrinsic_XYX
Intrinsic_XZX
Intrinsic_YZY
Intrinsic_YXY
Intrinsic_ZXZ
Intrinsic_ZYZ
EulerSequenceLast
Definition at line 73 of file Rotation.h.
Constructor & Destructor Documentation
Rotation() [1/8]
Rotation::Rotation ()
Construction.
Definition at line 37 of file Rotation.cpp.
Referenced by fromNormalVector(), isIdentity(), and FemGui::ViewProviderFemConstraintTransform::transformSymbol().
Rotation() [2/8]
Rotation::Rotation (const Vector3d & axis, double fAngle)
Construct a rotation by rotation axis and angle
Definition at line 44 of file Rotation.cpp.
References Base::Vector3< float_type >::Set(), and setValue().
Rotation() [3/8]
Rotation::Rotation (const Matrix4D & matrix)
Definition at line 52 of file Rotation.cpp.
References setValue().
Rotation() [4/8]
Rotation::Rotation (const double q[4])
Construct a rotation initialized with the given quaternion components: q[0] = x, q[1] = y, q[2] = z and q[3] = w, where the quaternion is specified by q=w+xi+yj+zk.
Definition at line 62 of file Rotation.cpp.
References setValue().
Rotation() [5/8]
Rotation::Rotation (double q0, double q1, double q2, double q3)
Construct a rotation initialized with the given quaternion components: q0 = x, q1 = y, q2 = z and q3 = w, where the quaternion is specified by q=w+xi+yj+zk.
Definition at line 72 of file Rotation.cpp.
References setValue().
Rotation() [6/8]
Rotation::Rotation (const Vector3d & rotateFrom, const Vector3d & rotateTo)
Definition at line 78 of file Rotation.cpp.
References setValue().
Rotation() [7/8]
Base::Rotation::Rotation (const Rotation & rot) default
Rotation() [8/8]
Base::Rotation::Rotation (Rotation && rot) default
~Rotation()
Base::Rotation::~Rotation () default
Member Function Documentation
eulerSequenceFromName()
Rotation::EulerSequence Rotation::eulerSequenceFromName (const char * name) static
Definition at line 965 of file Rotation.cpp.
References SplineSurface::i, and Invalid.
eulerSequenceName()
const char * Rotation::eulerSequenceName (EulerSequence seq) static
Definition at line 957 of file Rotation.cpp.
References EulerSequenceLast, and Invalid.
fromEulerAngles()
Rotation Rotation::fromEulerAngles (EulerSequence theOrder, double alpha, double beta, double gamma) static
Utility function to create Rotation based on euler angles.
Definition at line 90 of file Rotation.cpp.
References setEulerAngles().
fromNormalVector()
Rotation Rotation::fromNormalVector (const Vector3d & normal) static
Utility function to create Rotation based on direction / normal vector Z base vector is assumed to represent the normal vector
Definition at line 84 of file Rotation.cpp.
References Rotation().
Referenced by Attacher::AttachEngine3D::_calculateAttachedPlacement().
getEulerAngles()
void Rotation::getEulerAngles (EulerSequence theOrder, double & alpha, double & beta, double & gamma) const
Definition at line 1041 of file Rotation.cpp.
References KDL::atan2(), D_PI, getValue(), src.Mod.Test.testPathArray::o, and KDL::sqrt().
getRawValue()
void Rotation::getRawValue (Vector3d & axis, double & rfAngle) const
Does the same as the method above unless normalizing the axis.
Definition at line 154 of file Rotation.cpp.
References Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by Gui::PropertyEditor::RotationHelper::assignProperty(), App::PropertyPlacement::getPathValue(), App::PropertyPlacement::getPyPathValue(), printPlacement(), App::PropertyPlacement::setPathValue(), and Base::Placement::toString().
getValue() [1/4]
const double * Rotation::getValue () const
Methods to get or set rotations.
Definition at line 97 of file Rotation.cpp.
Referenced by FemGui::TaskDlgFemConstraintTransform::accept(), FemGui::TaskDlgFemConstraintRigidBody::accept(), Data::ComplexGeoData::applyRotation(), Import::ExportOCAF::createNode(), Assembly::AssemblyObject::doDragStep(), App::FunctionExpression::evaluate(), Robot::TrajectoryDressUpObject::execute(), Part::Tools::fromPlacement(), getEulerAngles(), Part::FeatureReference::getLocation(), Part::Feature::getLocation(), Assembly::AssemblyObject::makeMbdMarker(), Assembly::AssemblyObject::makeMbdPart(), multLeft(), multRight(), Path::Toolpath::recalculate(), Part::Geometry::rotate(), Import::ExportOCAF::saveShape(), MeshCore::MeshOutput::SaveX3DContent(), scaleAngle(), Gui::PropertyEditor::RotationHelper::setAxis(), Gui::View3DInventorPy::setCameraOrientation(), Gui::EditableDatumLabel::setPlacement(), FemGui::TaskFemConstraintTransform::TaskFemConstraintTransform(), Base::Placement::toDualQuaternion(), Base::Placement::toMatrix(), FemGui::ViewProviderFemConstraintTransform::transformSymbol(), Gui::View3DInventorPy::viewPosition(), and Base::TransformItem::write().
getValue() [2/4]
void Rotation::getValue (double & q0, double & q1, double & q2, double & q3) const
Definition at line 102 of file Rotation.cpp.
getValue() [3/4]
void Rotation::getValue (Matrix4D & matrix) const
Returns this rotation in form of a matrix.
Definition at line 165 of file Rotation.cpp.
References RobotExample::l, KDL::sqrt(), src.Mod.PartDesign.fcgear.svggear::w, MovieTool::x, and MovieTool::y.
getValue() [4/4]
void Rotation::getValue (Vector3d & axis, double & rfAngle) const
If not a null quaternion then axis will be normalized.
Definition at line 145 of file Rotation.cpp.
References Base::Vector3< float_type >::Normalize(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
getYawPitchRoll()
void Rotation::getYawPitchRoll (double & y, double & p, double & r) const
Euler angles in yaw,pitch,roll notation.
Definition at line 712 of file Rotation.cpp.
References KDL::asin(), KDL::atan2(), D_PI, buildPsets::p, and MovieTool::y.
Referenced by PartGui::TaskDlgAttacher::accept(), App::PropertyPlacement::getPathValue(), App::PropertyPlacement::getPyPathValue(), Path::Command::setFromPlacement(), App::PropertyPlacement::setPathValue(), Assembly::AssemblyObject::slidingPartIndex(), Path::Command::transform(), and RobotGui::TaskTrajectoryDressUpParameter::viewPlacement().
identity()
Rotation Rotation::identity () static
Definition at line 526 of file Rotation.cpp.
inverse()
Rotation Rotation::inverse () const
Definition at line 335 of file Rotation.cpp.
Referenced by Gui::View3DInventorViewer::alignToSelection(), Base::Placement::invert(), and Sketcher::SketchObject::rebuildExternalGeometry().
invert()
Rotation & Rotation::invert ()
Invert rotations.
Definition at line 322 of file Rotation.cpp.
References Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
isIdentity() [1/2]
bool Rotation::isIdentity () const
Definition at line 782 of file Rotation.cpp.
Referenced by ArchComponent.Component::applyShape(), ArchComponent.Component::getExtrusionData(), Base::Placement::isIdentity(), ArchComponent.Component::processSubShapes(), Points::PlyWriter::write(), and Points::PcdWriter::write().
isIdentity() [2/2]
bool Rotation::isIdentity (double tol) const
Definition at line 788 of file Rotation.cpp.
References isSame(), and Rotation().
Referenced by ArchComponent.Component::applyShape(), ArchComponent.Component::getExtrusionData(), and ArchComponent.Component::processSubShapes().
isNull()
bool Rotation::isNull () const
Definition at line 793 of file Rotation.cpp.
isSame() [1/2]
bool Rotation::isSame (const Rotation & q) const
Definition at line 752 of file Rotation.cpp.
Referenced by isIdentity(), Base::Placement::isSame(), and operator==().
isSame() [2/2]
bool Rotation::isSame (const Rotation & q, double tol) const
Definition at line 766 of file Rotation.cpp.
References dot().
makeRotationByAxes()
Rotation Rotation::makeRotationByAxes (Vector3d xdir, Vector3d ydir, Vector3d zdir, const char * priorityOrder = "ZXY") static
makeRotationByAxes(xdir, ydir, zdir, priorityOrder): creates a rotation that converts a vector in local cs with axes given as arguments, into a vector in global cs.
Parameters
xdir is wanted direction of local X axis
ydir ...
zdir
priorityOrder sets which directions are followed. It is a string like "ZXY". This means, Z direction is followed precisely; X direction is corrected to be perpendicular to Z direction, and used; Y direction argument is ignored altogether (Y direction is generated from Z and X).
If only one vector provided is nonzero, the other two directions are picked automatically.
Definition at line 532 of file Rotation.cpp.
References Base::Precision::Confusion(), Base::Vector3< float_type >::Cross(), SplineSurface::i, Base::Vector3< float_type >::Length(), test::m, Base::Vector3< float_type >::Normalize(), THROWM, DrawingExample::X, Base::Vector3< float_type >::x, DrawingExample::Y, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by Attacher::AttachEngine3D::_calculateAttachedPlacement().
multLeft()
Rotation & Rotation::multLeft (const Base::Rotation & q)
Let this rotation be left-multiplied by q. Returns reference to self.
See also
multRight()
Definition at line 402 of file Rotation.cpp.
References getValue(), and setValue().
Referenced by Base::Placement::multLeft().
multRight()
Rotation & Rotation::multRight (const Base::Rotation & q)
Let this rotation be right-multiplied by q. Returns reference to self.
See also
multLeft()
Definition at line 374 of file Rotation.cpp.
References getValue(), and setValue().
Referenced by Base::Placement::multRight(), and operator*=().
multVec() [1/4]
Vector3d Rotation::multVec (const Vector3d & src) const
Definition at line 434 of file Rotation.cpp.
References multVec().
multVec() [2/4]
void Rotation::multVec (const Vector3d & src, Vector3d & dst) const
Definition at line 441 of file Rotation.cpp.
References src.Mod.PartDesign.fcgear.svggear::w, MovieTool::x, Base::Vector3< float_type >::x, MovieTool::y, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by ReenGui::FitBSplineSurfaceWidget::accept(), Sketcher::SketchObject::addExternal(), Path::compensateRotation(), Part::Mirroring::execute(), PartDesignGui::fixSketchSupport(), PartDesign::ProfileBased::getAxis(), App::DatumElement::getDirection(), PartDesign::Line::getDirection(), Gui::ViewProviderDragger::getDraggerPlacement(), Import::SketchExportHelper::getFlatSketchXY(), PartDesign::Plane::getNormal(), Gui::View3DInventorViewer::getPointOnXYPlaneOfPlacement(), PartDesign::ProfileBased::getProfileNormal(), Assembly::AssemblyObject::getRackPinionMarkers(), PartDesign::ProfileBased::getReversedAngle(), Gui::View3DInventorViewer::getViewportOnXYPlaneOfPlacement(), PartDesign::CoordinateSystem::getXAxis(), PartDesign::CoordinateSystem::getYAxis(), PartDesign::CoordinateSystem::getZAxis(), Base::Placement::invert(), Sketcher::SketchObject::isCarbonCopyAllowed(), Base::Placement::multRight(), Base::Placement::multVec(), multVec(), Base::Axis::operator*=(), Base::Placement::Placement(), Sketcher::SketchObject::rebuildExternalGeometry(), Gui::EditableDatumLabel::setPlacement(), Base::CoordinateSystem::setPlacement(), Gui::View3DInventorViewer::toggleClippingPlane(), Base::Line3< float >::Transform(), Base::CoordinateSystem::transform(), Base::Polygon3< float_type >::Transform(), Gui::ManualAlignment::Private::transformation2x2(), Gui::ManualAlignment::Private::transformation3x3(), Mesh::MeshObject::trimByPlane(), Path::PathSegmentWalker::walk(), Points::PlyWriter::write(), and Points::PcdWriter::write().
multVec() [3/4]
Vector3f Rotation::multVec (const Vector3f & src) const
Definition at line 470 of file Rotation.cpp.
References multVec().
multVec() [4/4]
void Rotation::multVec (const Vector3f & src, Vector3f & dst) const
Definition at line 463 of file Rotation.cpp.
References multVec().
operator!=()
bool Rotation::operator!= (const Rotation & q) const
Definition at line 429 of file Rotation.cpp.
operator*()
Rotation Rotation::operator* (const Rotation & q) const
Definition at line 361 of file Rotation.cpp.
operator*=()
Rotation & Rotation::operator*= (const Rotation & q)
Operators.
Let this rotation be right-multiplied by q. Returns reference to self.
See also
multRight()
Definition at line 356 of file Rotation.cpp.
References multRight().
operator=() [1/2]
Rotation& Base::Rotation::operator= (const Rotation &) default
operator=() [2/2]
Rotation& Base::Rotation::operator= (Rotation &&) default
operator==()
bool Rotation::operator== (const Rotation & q) const
Definition at line 424 of file Rotation.cpp.
References isSame().
operator[]() [1/2]
double& Base::Rotation::operator[] (unsigned short usIndex) inline
Definition at line 166 of file Rotation.h.
operator[]() [2/2]
const double& Base::Rotation::operator[] (unsigned short usIndex) const inline
Definition at line 170 of file Rotation.h.
scaleAngle()
void Rotation::scaleAngle (double scaleFactor)
Definition at line 477 of file Rotation.cpp.
References getValue(), and setValue().
setEulerAngles()
void Rotation::setEulerAngles (EulerSequence theOrder, double alpha, double beta, double gamma)
Definition at line 977 of file Rotation.cpp.
References a, SCL.SimpleDataTypes::b, SCL.SimpleDataTypes::c, KDL::cos(), D_PI, EulerSequenceLast, Invalid, src.Mod.Test.testPathArray::o, and KDL::sin().
Referenced by fromEulerAngles().
setValue() [1/5]
void Rotation::setValue (const double q[4])
Definition at line 197 of file Rotation.cpp.
setValue() [2/5]
void Rotation::setValue (const Matrix4D & matrix)
Definition at line 207 of file Rotation.cpp.
References SplineSurface::i, test::m, toolbit-attributes::s, and KDL::sqrt().
setValue() [3/5]
void Rotation::setValue (const Vector3d & axis, double fAngle)
Definition at line 247 of file Rotation.cpp.
References KDL::cos(), D_PI, RobotExample::l, Base::Vector3< float_type >::Length(), Base::Vector3< float_type >::Normalize(), draftfunctions.scale::scale(), KDL::sin(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
setValue() [4/5]
void Rotation::setValue (const Vector3d & rotateFrom, const Vector3d & rotateTo)
Definition at line 274 of file Rotation.cpp.
References KDL::acos(), dot(), Base::Vector3< double >::epsilon(), setValue(), InitGui::t, buildPsets::u, TestSpreadsheet::v, src.Mod.PartDesign.fcgear.svggear::w, and Base::Vector3< float_type >::x.
setValue() [5/5]
void Rotation::setValue (double q0, double q1, double q2, double q3)
Definition at line 135 of file Rotation.cpp.
Referenced by Base::Placement::fromMatrix(), multLeft(), multRight(), Rotation(), scaleAngle(), Gui::PropertyEditor::RotationHelper::setAngle(), Gui::PropertyEditor::RotationHelper::setAxis(), App::PropertyPlacement::setPathValue(), setValue(), and setYawPitchRoll().
setYawPitchRoll()
void Rotation::setYawPitchRoll (double y, double p, double r)
Euler angles in yaw,pitch,roll notation.
Definition at line 691 of file Rotation.cpp.
References src.Mod.PartDesign.Scripts.Gear::c1, KDL::cos(), D_PI, buildPsets::p, setValue(), KDL::sin(), and MovieTool::y.
Referenced by Path::Command::getPlacement(), App::PropertyPlacement::setPathValue(), and Path::yawPitchRoll().
slerp()
Rotation Rotation::slerp (const Rotation & q0, const Rotation & q1, double t) static
Specialty constructors
Definition at line 485 of file Rotation.cpp.
References KDL::acos(), dot(), Base::Vector3< double >::epsilon(), DraftVecUtils::neg(), KDL::sin(), InitGui::t, src.Mod.PartDesign.fcgear.svggear::w, MovieTool::x, and MovieTool::y.
Referenced by Base::Placement::slerp().
The documentation for this class was generated from the following files:
Rotation.h
Rotation.cpp