FreeCAD: PartGui::CylinderPrimitive Class Reference
PartGui::CylinderPrimitive Class Reference
#include <DlgPrimitives.h>
Public Member Functions
CylinderPrimitive (std::shared_ptr< Ui_DlgPrimitives > ui, Part::Cylinder *feature=nullptr)
const char * getDefaultName () const override
QString create (const QString &objectName, const QString &placement) const override
QString change (const QString &objectName, const QString &placement) const override
void changeValue (QObject *) override
Public Member Functions inherited from PartGui::AbstractPrimitive
AbstractPrimitive (Part::Primitive *feature=nullptr)
~AbstractPrimitive () override=default
bool hasValidPrimitive () const
Additional Inherited Members
Protected Member Functions inherited from PartGui::AbstractPrimitive
void connectSignalMapper (QSignalMapper *mapper)
Protected Attributes inherited from PartGui::AbstractPrimitive
App::DocumentObjectWeakPtrT featurePtr
Detailed Description
Definition at line 136 of file DlgPrimitives.h.
Constructor & Destructor Documentation
CylinderPrimitive()
CylinderPrimitive::CylinderPrimitive (std::shared_ptr< Ui_DlgPrimitives > ui, Part::Cylinder * feature = nullptr)
Definition at line 391 of file DlgPrimitives.cpp.
References Part::Cylinder::Angle, PartGui::connectMapSignalMapper(), PartGui::AbstractPrimitive::connectSignalMapper(), Part::PrismExtension::FirstAngle, App::PropertyQuantity::getQuantityValue(), Part::Cylinder::Height, Part::Cylinder::Radius, Part::PrismExtension::SecondAngle, and Gui::QuantitySpinBox::valueChanged().
Member Function Documentation
change()
QString CylinderPrimitive::change (const QString & objectName, const QString & placement) const override virtual
Implements PartGui::AbstractPrimitive.
Definition at line 447 of file DlgPrimitives.cpp.
References PartGui::safeQuantityQString().
changeValue()
void CylinderPrimitive::changeValue (QObject * widget) override virtual
Implements PartGui::AbstractPrimitive.
Definition at line 465 of file DlgPrimitives.cpp.
References Part::Cylinder::Angle, App::DocumentObjectWeakPtrT::expired(), PartGui::AbstractPrimitive::featurePtr, Part::PrismExtension::FirstAngle, App::DocumentObjectWeakPtrT::get(), Part::Cylinder::Height, Part::Cylinder::Radius, App::DocumentObject::recomputeFeature(), Part::PrismExtension::SecondAngle, and App::PropertyQuantity::setValue().
create()
QString CylinderPrimitive::create (const QString & objectName, const QString & placement) const override virtual
Implements PartGui::AbstractPrimitive.
Definition at line 426 of file DlgPrimitives.cpp.
References PartGui::safeQuantityQString().
getDefaultName()
const char * CylinderPrimitive::getDefaultName () const override virtual
Implements PartGui::AbstractPrimitive.
Definition at line 421 of file DlgPrimitives.cpp.
The documentation for this class was generated from the following files:
DlgPrimitives.h
DlgPrimitives.cpp