FreeCAD: Spreadsheet::PropertySheet Class Reference
Spreadsheet::PropertySheet Class Reference
#include <PropertySheet.h>
Public Types
enum BindingType { BindingNone, BindingNormal, BindingHiddenRef }
Public Types inherited from App::PropertyLinkBase
enum LinkFlags {
LinkAllowExternal, LinkDetached, LinkRestoring, LinkAllowPartial,
LinkRestoreLabel, LinkSyncSubObject, LinkNewElement, LinkSilentRestore
}
using ShadowSub = ElementNamePair
Public Types inherited from App::Property
enum Status {
Touched = 0, Immutable = 1, ReadOnly = 2, Hidden = 3,
Transient = 4, MaterialEdit = 5, NoMaterialListEdit = 6, Output = 7,
LockDynamic = 8, NoModify = 9, PartialTrigger = 10, NoRecompute = 11,
Single = 12, Ordered = 13, EvalOnRestore = 14, Busy = 15,
CopyOnChange, UserEdit = 17, PropStaticBegin = 21, PropDynamic = 21,
PropNoPersist = 22, PropNoRecompute = 23, PropReadOnly = 24, PropTransient = 25,
PropHidden = 26, PropOutput = 27, PropStaticEnd = 28, User1 = 28,
User2 = 29, User3 = 30, User4 = 31
}
Public Member Functions
PropertySheet (Sheet *_owner=nullptr)
~PropertySheet () override
std::map< App::ObjectIdentifier, const App::Expression * > getExpressions () const override
void setExpressions (std::map< App::ObjectIdentifier, App::ExpressionPtr > &&exprs) override
void onRelabeledDocument (const App::Document &doc) override
void updateElementReference (App::DocumentObject *feature, bool reverse=false, bool notify=false) override
bool referenceChanged () const override
Test if the element reference has changed after restore.
bool adjustLink (const std::set< App::DocumentObject * > &inList) override
Property * CopyOnImportExternal (const std::map< std::string, std::string > &nameMap) const override
Property * CopyOnLabelChange (App::DocumentObject *obj, const std::string &ref, const char *newLabel) const override
Property * CopyOnLinkReplace (const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const override
void breakLink (App::DocumentObject *obj, bool clear) override
void afterRestore () override
void onContainerRestored () override
Property * Copy () const override
Returns a new copy of the property (mainly for Undo/Redo and transactions)
void Paste (const Property &from) override
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
void getLinksTo (std::vector< App::ObjectIdentifier > &identifiers, App::DocumentObject *obj, const char *subname=nullptr, bool all=false) const override
void copyCells (Base::Writer &writer, const std::vector< App::Range > &ranges) const
void pasteCells (Base::XMLReader &reader, App::Range dstRange)
Cell * createCell (App::CellAddress address)
void setValue ()
void setContent (App::CellAddress address, const char *value)
void setAlignment (App::CellAddress address, int _alignment)
void setStyle (App::CellAddress address, const std::set< std::string > &_style)
void setForeground (App::CellAddress address, const App::Color &color)
void setBackground (App::CellAddress address, const App::Color &color)
void setDisplayUnit (App::CellAddress address, const std::string &unit)
void setAlias (App::CellAddress address, const std::string &alias)
void setComputedUnit (App::CellAddress address, const Base::Unit &unit)
void setSpans (App::CellAddress address, int rows, int columns)
void clear (App::CellAddress address, bool toClearAlias=true)
void clear ()
Cell * getValue (App::CellAddress key)
const Cell * getValue (App::CellAddress key) const
Cell * getValueFromAlias (const std::string &alias)
const Cell * getValueFromAlias (const std::string &alias) const
bool isValidAlias (const std::string &candidate)
bool isValidCellAddressName (const std::string &candidate)
std::vector< App::CellAddress > getUsedCells () const
std::tuple< App::CellAddress, App::CellAddress > getUsedRange () const
std::vector< App::CellAddress > getNonEmptyCells () const
std::tuple< App::CellAddress, App::CellAddress > getNonEmptyRange () const
Sheet * sheet () const
const std::set< App::CellAddress > & getDirty ()
void setDirty (App::CellAddress address)
void setDirty ()
void clearDirty (App::CellAddress key)
void clearDirty ()
bool isDirty () const
void pasteCells (const std::map< App::CellAddress, std::string > &cells, int rowOffset, int colOffset)
void insertRows (int row, int count)
std::vector< App::CellAddress > getRows (int row, int count) const
void removeRows (int row, int count)
void insertColumns (int col, int count)
std::vector< App::CellAddress > getColumns (int column, int count) const
void removeColumns (int col, int count)
unsigned int getMemSize () const override
bool mergeCells (App::CellAddress from, App::CellAddress to)
void splitCell (App::CellAddress address)
void getSpans (App::CellAddress address, int &rows, int &cols) const
bool hasSpan () const
App::CellAddress getAnchor (App::CellAddress address) const
bool isMergedCell (App::CellAddress address) const
bool isHidden (App::CellAddress address) const
const std::set< App::CellAddress > & getDeps (const std::string &name) const
const std::set< std::string > & getDeps (App::CellAddress pos) const
void recomputeDependencies (App::CellAddress key)
PyObject * getPyObject () override
void setPyObject (PyObject *) override
PyObject * getPyValue (PyObject *key)
void invalidateDependants (const App::DocumentObject *docObj)
void renameObjectIdentifiers (const std::map< App::ObjectIdentifier, App::ObjectIdentifier > &paths)
void deletedDocumentObject (const App::DocumentObject *docObj)
void documentSet ()
App::CellAddress getCellAddress (const char *addr, bool silent=false) const
App::Range getRange (const char *range, bool silent=false) const
std::string getRow (int offset=0) const
std::string getColumn (int offset=0) const
void setPathValue (const App::ObjectIdentifier &path, const boost::any &value) override
Set value of property.
const boost::any getPathValue (const App::ObjectIdentifier &path) const override
Get value of property.
unsigned getBindingBorder (App::CellAddress address) const
bool isBindingPath (const App::ObjectIdentifier &path, App::CellAddress *from=nullptr, App::CellAddress *to=nullptr, bool *href=nullptr) const
BindingType getBinding (const App::Range &range, App::ExpressionPtr *pStart=nullptr, App::ExpressionPtr *pEnd=nullptr, App::ObjectIdentifier *pTarget=nullptr) const
Public Member Functions inherited from App::PropertyExpressionContainer
PropertyExpressionContainer ()
~PropertyExpressionContainer () override
Public Member Functions inherited from App::PropertyXLinkContainer
PropertyXLinkContainer ()
~PropertyXLinkContainer () override
int checkRestore (std::string *msg=nullptr) const override
void getLinks (std::vector< App::DocumentObject * > &objs, bool all=false, std::vector< std::string > *subs=nullptr, bool newStyle=true) const override
bool isLinkedToDocument (const App::Document &doc) const
Public Member Functions inherited from App::PropertyLinkBase
PropertyLinkBase ()
~PropertyLinkBase () override
void unregisterElementReference ()
Clear internal element reference registration.
void registerLabelReferences (std::vector< std::string > &&labels, bool reset=true)
void checkLabelReferences (const std::vector< std::string > &subs, bool reset=true)
void unregisterLabelReferences ()
Clear internal label references registration.
virtual bool adjustLink (const std::set< App::DocumentObject * > &inList)=0
std::vector< App::DocumentObject * > linkedObjects (bool all=false) const
Helper function to return all linked objects of this property.
template<class T >
void getLinkedObjects (T &inserter, bool all=false) const
Helper function to return linked objects using an std::inserter.
void getLinkedElements (std::map< App::DocumentObject *, std::vector< std::string >> &elements, bool newStyle=true, bool all=false) const
Helper function to return a map of linked object and its subname references.
std::map< App::DocumentObject *, std::vector< std::string > > linkedElements (bool newStyle=true, bool all=false) const
Helper function to return a map of linked object and its subname references.
bool isSame (const Property &other) const override
Compare if this property has the same content as the given one.
void setAllowExternal (bool allow)
bool _updateElementReference (App::DocumentObject *feature, App::DocumentObject *obj, std::string &sub, ShadowSub &shadow, bool reverse, bool notify=false)
void _registerElementReference (App::DocumentObject *obj, std::string &sub, ShadowSub &shadow)
bool testFlag (int flag) const
virtual void setAllowPartial (bool enable)
void setReturnNewElement (bool enable)
void setSilentRestore (bool enable)
Public Member Functions inherited from App::Property
Property ()
~Property () override
const char * getName () const
bool hasName () const
std::string getFullName () const
virtual const char * getEditorName () const
Get the class name of the associated property editor item.
short getType () const
Get the type of the property in the container.
const char * getGroup () const
Get the group of this property.
const char * getDocumentation () const
Get the documentation of this property.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
PropertyContainer * getContainer () const
Get a pointer to the PropertyContainer derived class the property belongs to.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
void touch ()
Set the property touched.
bool isTouched () const
Test if this property is touched.
void purgeTouched ()
Reset this property touched.
unsigned long getStatus () const
return the status bits
bool testStatus (Status pos) const
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
bool isReadOnly () const
void setSinglePrecision (bool single)
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
virtual void Paste (const Property &from)=0
Paste the value from the property (mainly for Undo/Redo and transactions)
int64_t getID () const
virtual void beforeSave () const
Property (const Property &)=delete
Property & operator= (const Property &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from App::ScopedLink
void setScope (LinkScope scope)
Set the links scope Allows to define what kind of links are allowed. Only in the Local GeoFeatureGroup, in this and all Childs or to all objects within the Glocal scope.
LinkScope getScope () const
Get the links scope Retrieve what kind of links are allowed. Only in the Local GeoFeatureGroup, in this and all Childs or to all objects within the Glocal scope.
Protected Member Functions
void hasSetValue () override
Gets called by all setValue() methods after the value has changed.
void hasSetChildValue (App::Property &prop) override
Called when a child property has changed value.
void onBreakLink (App::DocumentObject *obj) override
void onAddDep (App::DocumentObject *obj) override
void onRemoveDep (App::DocumentObject *obj) override
Protected Member Functions inherited from App::PropertyXLinkContainer
void aboutToSetChildValue (App::Property &prop) override
Called before a child property changing value.
virtual PropertyXLink * createXLink ()
void updateDeps (std::map< DocumentObject *, bool > &&newDeps)
void clearDeps ()
void _onBreakLink (App::DocumentObject *obj)
Protected Member Functions inherited from App::PropertyLinkBase
void setFlag (int flag, bool value=true)
void _getLinksTo (std::vector< App::ObjectIdentifier > &identifiers, App::DocumentObject *obj, const char *subname, const std::vector< std::string > &subs, const std::vector< PropertyLinkBase::ShadowSub > &shadows) const
Protected Member Functions inherited from App::Property
virtual void aboutToSetValue ()
Gets called by all setValue() methods before the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
std::string getFileName (const char *postfix=0, const char *prefix=0) const
Return a file name suitable for saving this property.
Friends
class AtomicPropertyChange
class SheetObserver
class Cell
class Sheet
Additional Inherited Members
Static Public Member Functions inherited from App::PropertyLinkBase
static std::pair< App::DocumentObject *, std::string > tryReplaceLink (const App::PropertyContainer *owner, App::DocumentObject *obj, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj, const char *sub=nullptr)
Helper functions.
static std::pair< App::DocumentObject *, std::vector< std::string > > tryReplaceLinkSubs (const App::PropertyContainer *owner, App::DocumentObject *obj, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj, const std::vector< std::string > &subs)
static void updateElementReferences (DocumentObject *feature, bool reverse=false)
Update all element references in all link properties of feature.
static const std::unordered_set< PropertyLinkBase * > & getElementReferences (DocumentObject *)
Obtain link properties that contain element references to a given object.
static void breakLinks (App::DocumentObject *link, const std::vector< App::DocumentObject * > &objs, bool clear)
static std::string tryImportSubName (const App::DocumentObject *obj, const char *sub, const App::Document *doc, const std::map< std::string, std::string > &nameMap)
static App::DocumentObject * tryImport (const App::Document *doc, const App::DocumentObject *obj, const std::map< std::string, std::string > &nameMap)
static const char * exportSubName (std::string &output, const App::DocumentObject *obj, const char *subname, bool first_obj=false)
static std::string importSubName (Base::XMLReader &reader, const char *sub, bool &restoreLabel)
static void restoreLabelReference (const App::DocumentObject *obj, std::string &sub, ShadowSub *shadow=nullptr)
static void getLabelReferences (std::vector< std::string > &labels, const char *subname)
static std::vector< std::pair< Property *, std::unique_ptr< Property > > > updateLabelReferences (App::DocumentObject *obj, const char *newLabel)
static std::string updateLabelReference (const App::DocumentObject *linked, const char *subname, App::DocumentObject *obj, const std::string &ref, const char *newLabel)
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes inherited from App::PropertyLinkBase
boost::signals2::signal< void(const std::string &, const std::string &)> signalUpdateElementReference
Public Attributes inherited from App::Property
boost::signals2::signal< void(const App::Property &)> signalChanged
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::PropertyXLinkContainer
std::map< App::DocumentObject *, bool > _Deps
std::map< std::string, std::unique_ptr< PropertyXLink > > _XLinks
std::map< std::string, std::string > _DocMap
bool _LinkRestored
Protected Attributes inherited from App::PropertyLinkBase
std::bitset< 32 > _Flags
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Protected Attributes inherited from App::ScopedLink
LinkScope _pcScope = LinkScope::Local
Detailed Description
Definition at line 61 of file PropertySheet.h.
Member Enumeration Documentation
BindingType
enum Spreadsheet::PropertySheet::BindingType
Enumerator
BindingNone
BindingNormal
BindingHiddenRef
Definition at line 256 of file PropertySheet.h.
Constructor & Destructor Documentation
PropertySheet()
PropertySheet::PropertySheet (Sheet * _owner = nullptr) explicit
Definition at line 280 of file PropertySheet.cpp.
Referenced by Copy(), CopyOnImportExternal(), CopyOnLabelChange(), and CopyOnLinkReplace().
~PropertySheet()
PropertySheet::~PropertySheet () override
Definition at line 305 of file PropertySheet.cpp.
References clear().
Member Function Documentation
adjustLink()
bool PropertySheet::adjustLink (const std::set< App::DocumentObject * > & inList) override
Definition at line 1783 of file PropertySheet.cpp.
References AtomicPropertyChange, SCL.SimpleDataTypes::e, App::DocumentObject::getFullName(), and TestSpreadsheet::v.
afterRestore()
void PropertySheet::afterRestore () override virtual
Called at the beginning of Document::afterRestore()
This function is called without dependency sorting, because some types of link property can only reconstructs the linking information inside this function.
One example use case of this function is PropertyLinkSub that uses afterRestore() to parse and restore subname references, which may contain sub-object reference from external document, and there will be special mapping required during object import.
Another example is PropertyExpressionEngine which only parse the restored expression in afterRestore(). The reason, in addition to subname mapping like PropertyLinkSub, is that it can handle document name adjustment as well. It internally relies on PropertyXLink to store the external document path for external linking. When the external document is restored, its internal name may change due to name conflict with existing documents. PropertyExpressionEngine can now auto adjust external references without any problem.
Reimplemented from App::PropertyXLinkContainer.
Definition at line 1740 of file PropertySheet.cpp.
References App::PropertyXLinkContainer::_DocMap, App::PropertyXLinkContainer::_XLinks, AtomicPropertyChange, setDirty(), App::Property::touch(), and TestSpreadsheet::v.
breakLink()
void PropertySheet::breakLink (App::DocumentObject * obj, bool clear) override virtual
Called to reset this link property
Parameters
obj reset link property if it is linked to this object
clear if true, then also reset property if the owner of this property is obj
See also
breakLinks()
Reimplemented from App::PropertyXLinkContainer.
Definition at line 1510 of file PropertySheet.cpp.
References AtomicPropertyChange, and clear().
clear() [1/2]
void PropertySheet::clear ()
Definition at line 59 of file PropertySheet.cpp.
Referenced by src.Mod.Test.Document.DocumentObserverCases.Observer::__init__(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::__init__(), breakLink(), mergeCells(), Paste(), removeColumns(), removeRows(), setExpressions(), and ~PropertySheet().
clear() [2/2]
void PropertySheet::clear (App::CellAddress address, bool toClearAlias = true)
Definition at line 823 of file PropertySheet.cpp.
References AtomicPropertyChange, SplineSurface::i, and splitCell().
Referenced by src.Mod.Test.Document.DocumentObserverCases.Observer::__init__(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::__init__(), Spreadsheet::Sheet::clear(), and Spreadsheet::Sheet::clearAll().
clearDirty() [1/2]
void Spreadsheet::PropertySheet::clearDirty () inline
Definition at line 177 of file PropertySheet.h.
clearDirty() [2/2]
void Spreadsheet::PropertySheet::clearDirty (App::CellAddress key) inline
Definition at line 172 of file PropertySheet.h.
Referenced by Spreadsheet::Cell::clearDirty(), and Spreadsheet::Sheet::recomputeCell().
Copy()
App::Property * PropertySheet::Copy () const override virtual
Returns a new copy of the property (mainly for Undo/Redo and transactions)
Implements App::Property.
Definition at line 310 of file PropertySheet.cpp.
References PropertySheet().
copyCells()
void PropertySheet::copyCells (Base::Writer & writer, const std::vector< App::Range > & ranges) const
Definition at line 460 of file PropertySheet.cpp.
References src.Mod.AddonManager.NetworkManager::count, Base::Writer::decInd(), getValue(), Base::Writer::incInd(), Base::Writer::ind(), and Base::Writer::Stream().
Referenced by SpreadsheetGui::SheetTableView::_copySelection().
CopyOnImportExternal()
Property * PropertySheet::CopyOnImportExternal (const std::map< std::string, std::string > & nameMap) const override virtual
Return a copy of the property if any changes caused by importing external linked object
Parameters
nameMap a map from the original external object name to the imported new object name
Returns
Returns a copy of the property with the updated link reference if affected. The copy will later be assgiend to this property by calling its Paste().
Reimplemented from App::PropertyLinkBase.
Definition at line 1852 of file PropertySheet.cpp.
References SCL.SimpleDataTypes::e, Path.Post.scripts.opensbp_post::move(), and PropertySheet().
CopyOnLabelChange()
Property * PropertySheet::CopyOnLabelChange (App::DocumentObject * obj, const std::string & ref, const char * newLabel) const override virtual
Update object label reference in this property
Parameters
obj the object owner of the changing label
ref subname reference to old label
newLabel the future new label
Returns
Returns a copy of the property if its link reference is affected. The copy will later be assgiend to this property by calling its Paste().
Reimplemented from App::PropertyLinkBase.
Definition at line 1876 of file PropertySheet.cpp.
References SCL.SimpleDataTypes::e, Path.Post.scripts.opensbp_post::move(), and PropertySheet().
CopyOnLinkReplace()
Property * PropertySheet::CopyOnLinkReplace (const App::DocumentObject * parent, App::DocumentObject * oldObj, App::DocumentObject * newObj) const override virtual
Return a copy of the property if the link replacement affects this property
Parameters
owner the parent object whose link property is to be replace. Note that The parent may not be the container of this property. Link sub property can use this opportunity to adjust its relative links.
oldObj object to be replaced
newObj object to replace with
Returns
Return a copy of the property that is adjusted for the link replacement operation.
Implements App::PropertyLinkBase.
Definition at line 1902 of file PropertySheet.cpp.
References SCL.SimpleDataTypes::e, Path.Post.scripts.opensbp_post::move(), Init::parent, and PropertySheet().
createCell()
Cell * PropertySheet::createCell (App::CellAddress address)
Definition at line 271 of file PropertySheet.cpp.
References Cell.
Referenced by Spreadsheet::Sheet::getNewCell(), Restore(), and setPathValue().
deletedDocumentObject()
void PropertySheet::deletedDocumentObject (const App::DocumentObject * docObj)
Definition at line 1598 of file PropertySheet.cpp.
Referenced by Spreadsheet::SheetObserver::slotDeletedObject().
documentSet()
void PropertySheet::documentSet ()
Definition at line 1617 of file PropertySheet.cpp.
Referenced by Spreadsheet::Sheet::onSettingDocument().
getAnchor()
App::CellAddress Spreadsheet::PropertySheet::getAnchor (App::CellAddress address) const
Definition at line 1323 of file PropertySheet.cpp.
Referenced by Spreadsheet::Sheet::getAnchor().
getBinding()
PropertySheet::BindingType PropertySheet::getBinding (const App::Range & range, App::ExpressionPtr * pStart = nullptr, App::ExpressionPtr * pEnd = nullptr, App::ObjectIdentifier * pTarget = nullptr) const
Definition at line 2051 of file PropertySheet.cpp.
References BindingHiddenRef, BindingNone, BindingNormal, SCL.SimpleDataTypes::e, App::Range::from(), App::DocumentObject::getExpression(), App::Range::to(), and App::CellAddress::toString().
Referenced by Spreadsheet::Sheet::getCellBinding().
getBindingBorder()
unsigned Spreadsheet::PropertySheet::getBindingBorder (App::CellAddress address) const
getCellAddress()
App::CellAddress PropertySheet::getCellAddress (const char * addr, bool silent = false) const
Definition at line 1961 of file PropertySheet.cpp.
References Spreadsheet::Cell::getAddress(), getValueFromAlias(), Base::silent, and App::stringToAddress().
Referenced by Spreadsheet::Sheet::getCellAddress(), getPyValue(), getRange(), and setPathValue().
getColumn()
std::string Spreadsheet::PropertySheet::getColumn (int offset = 0) const
getColumns()
std::vector< CellAddress > PropertySheet::getColumns (int column, int count) const
Definition at line 1138 of file PropertySheet.cpp.
References App::ExpressionParser::column, src.Mod.AddonManager.NetworkManager::count, and SplineSurface::i.
Referenced by Spreadsheet::Sheet::removeColumns().
getDeps() [1/2]
const std::set< std::string > & PropertySheet::getDeps (App::CellAddress pos) const
Definition at line 1634 of file PropertySheet.cpp.
References SplineSurface::i, and RobotExample::pos.
getDeps() [2/2]
const std::set< CellAddress > & PropertySheet::getDeps (const std::string & name) const
Definition at line 1620 of file PropertySheet.cpp.
References SplineSurface::i.
Referenced by Spreadsheet::Sheet::dependsOn(), and Spreadsheet::Sheet::providesTo().
getDirty()
const std::set<App::CellAddress>& Spreadsheet::PropertySheet::getDirty () inline
Definition at line 163 of file PropertySheet.h.
Referenced by SpreadsheetGui::SheetModel::data(), and Spreadsheet::Sheet::execute().
getExpressions()
std::map< App::ObjectIdentifier, const App::Expression * > PropertySheet::getExpressions () const override virtual
Implements App::PropertyExpressionContainer.
Definition at line 1928 of file PropertySheet.cpp.
getLinksTo()
void PropertySheet::getLinksTo (std::vector< App::ObjectIdentifier > & identifiers, App::DocumentObject * obj, const char * subname = nullptr, bool all = false) const override virtual
Obtain identifiers from this link property that link to a given object
Parameters
identifiers holds the returned identifier to reference the given object
obj the referenced object
subname optional subname reference
all if true, then return all the references regardless of this LinkScope. If false, then return only if the LinkScope is not hidden.
Implements App::PropertyLinkBase.
Definition at line 2280 of file PropertySheet.cpp.
References App::Property::getContainer(), App::SubObjectT::getOldElementName(), and App::SubObjectT::getSubObject().
getMemSize()
unsigned int PropertySheet::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence
See also
Base::Persistence
Reimplemented from App::Property.
Definition at line 1224 of file PropertySheet.cpp.
getNonEmptyCells()
std::vector< CellAddress > PropertySheet::getNonEmptyCells () const
Definition at line 226 of file PropertySheet.cpp.
References SplineSurface::i, and Path.Post.scripts.refactored_centroid_post::str.
Referenced by Spreadsheet::Sheet::exportToFile(), SpreadsheetGui::SheetTableView::finishEditWithMove(), getNonEmptyRange(), setDirty(), and SpreadsheetGui::SheetTableView::toHtml().
getNonEmptyRange()
std::tuple< CellAddress, CellAddress > PropertySheet::getNonEmptyRange () const
Definition at line 241 of file PropertySheet.cpp.
References getNonEmptyCells().
getPathValue()
const boost::any PropertySheet::getPathValue (const App::ObjectIdentifier & path) const override virtual
Get value of property.
Reimplemented from App::Property.
Definition at line 2267 of file PropertySheet.cpp.
References isBindingPath().
getPyObject()
PyObject * PropertySheet::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Definition at line 1687 of file PropertySheet.cpp.
References Py::SmartPtr::is(), and Py::new_reference_to().
getPyValue()
PyObject * PropertySheet::getPyValue (PyObject * key)
Definition at line 1706 of file PropertySheet.cpp.
References App::Range::address(), App::Range::from(), getCellAddress(), App::ExtensionContainer::getPropertyByName(), Base::BaseClass::getPyObject(), getRange(), SplineSurface::i, App::CellAddress::isValid(), Py::new_reference_to(), App::Range::next(), PY_CATCH, Py_Return, PY_TRY, App::Range::size(), App::Range::to(), and App::CellAddress::toString().
getRange()
App::Range PropertySheet::getRange (const char * range, bool silent = false) const
Definition at line 1974 of file PropertySheet.cpp.
References SCL.SimpleDataTypes::c, App::CellAddress::col(), getCellAddress(), getValue(), App::CellAddress::isValid(), App::CellAddress::row(), App::CellAddress::setCol(), App::CellAddress::setRow(), and Base::silent.
Referenced by getPyValue(), and Spreadsheet::Sheet::getRange().
getRow()
std::string Spreadsheet::PropertySheet::getRow (int offset = 0) const
getRows()
std::vector< CellAddress > PropertySheet::getRows (int row, int count) const
Definition at line 982 of file PropertySheet.cpp.
References src.Mod.AddonManager.NetworkManager::count, and SplineSurface::i.
Referenced by Spreadsheet::Sheet::removeRows().
getSpans()
void PropertySheet::getSpans (App::CellAddress address, int & rows, int & cols) const
Definition at line 1304 of file PropertySheet.cpp.
References Spreadsheet::Cell::getSpans(), and SplineSurface::i.
Referenced by Spreadsheet::Sheet::getSpans().
getUsedCells()
std::vector< CellAddress > PropertySheet::getUsedCells () const
Definition at line 207 of file PropertySheet.cpp.
References SplineSurface::i.
Referenced by Spreadsheet::Sheet::getUsedCells(), and getUsedRange().
getUsedRange()
std::tuple< CellAddress, CellAddress > PropertySheet::getUsedRange () const
Definition at line 220 of file PropertySheet.cpp.
References getUsedCells().
Referenced by Spreadsheet::Sheet::getUsedRange().
getValue() [1/2]
Cell * PropertySheet::getValue (App::CellAddress key)
Definition at line 82 of file PropertySheet.cpp.
References SplineSurface::i.
Referenced by copyCells(), Spreadsheet::Sheet::execute(), Spreadsheet::Sheet::getCell(), getRange(), getValueFromAlias(), Spreadsheet::Sheet::hasCell(), invalidateDependants(), Spreadsheet::Sheet::recomputeCell(), and setPathValue().
getValue() [2/2]
const Cell * PropertySheet::getValue (App::CellAddress key) const
Definition at line 94 of file PropertySheet.cpp.
References SplineSurface::i.
getValueFromAlias() [1/2]
Cell * PropertySheet::getValueFromAlias (const std::string & alias)
Definition at line 106 of file PropertySheet.cpp.
References getValue().
Referenced by Spreadsheet::Sheet::getAddressFromAlias(), getCellAddress(), isValidAlias(), setAlias(), and setPathValue().
getValueFromAlias() [2/2]
const Cell * PropertySheet::getValueFromAlias (const std::string & alias) const
Definition at line 118 of file PropertySheet.cpp.
References getValue().
hasSetChildValue()
void PropertySheet::hasSetChildValue (App::Property &) override protected virtual
Called when a child property has changed value.
Reimplemented from App::Property.
Definition at line 1521 of file PropertySheet.cpp.
hasSetValue()
void PropertySheet::hasSetValue () override protected virtual
Gets called by all setValue() methods after the value has changed.
Reimplemented from App::PropertyLinkBase.
Definition at line 1657 of file PropertySheet.cpp.
References App::DocumentObject::isAttachedToDocument(), App::DocumentObject::isRestoring(), App::ExpressionParser::labels, App::PropertyLinkBase::LinkDetached, Path.Post.scripts.opensbp_post::move(), App::PropertyLinkBase::registerLabelReferences(), App::PropertyLinkBase::testFlag(), App::PropertyLinkBase::unregisterElementReference(), App::PropertyXLinkContainer::updateDeps(), and TestSpreadsheet::v.
hasSpan()
bool PropertySheet::hasSpan () const
Definition at line 2275 of file PropertySheet.cpp.
Referenced by SpreadsheetGui::SheetTableView::selectedRanges().
insertColumns()
void PropertySheet::insertColumns (int col, int count)
Definition at line 1068 of file PropertySheet.cpp.
References AtomicPropertyChange, App::ExpressionModifier< P >::changed(), Drawing::copy(), src.Mod.AddonManager.NetworkManager::count, App::Property::getContainer(), App::DocumentObject::getDocument(), SplineSurface::i, recomputeDependencies(), App::Document::renameObjectIdentifiers(), App::ExpressionModifier< P >::reset(), setDirty(), and Spreadsheet::Cell::visit().
Referenced by Spreadsheet::Sheet::insertColumns().
insertRows()
void PropertySheet::insertRows (int row, int count)
Definition at line 910 of file PropertySheet.cpp.
References AtomicPropertyChange, draftgeoutils.faces::bind(), App::ExpressionModifier< P >::changed(), Drawing::copy(), src.Mod.AddonManager.NetworkManager::count, App::Property::getContainer(), App::DocumentObject::getDocument(), SplineSurface::i, recomputeDependencies(), App::Document::renameObjectIdentifiers(), App::ExpressionModifier< P >::reset(), setDirty(), and Spreadsheet::Cell::visit().
Referenced by Spreadsheet::Sheet::insertRows().
invalidateDependants()
void PropertySheet::invalidateDependants (const App::DocumentObject * docObj)
Definition at line 1527 of file PropertySheet.cpp.
References AtomicPropertyChange, App::DocumentObject::getFullName(), getValue(), setDirty(), Spreadsheet::Cell::setResolveException(), and App::Property::touch().
Referenced by onBreakLink(), Spreadsheet::SheetObserver::slotCreatedObject(), and Spreadsheet::SheetObserver::slotDeletedObject().
isBindingPath()
bool PropertySheet::isBindingPath (const App::ObjectIdentifier & path, App::CellAddress * from = nullptr, App::CellAddress * to = nullptr, bool * href = nullptr) const
Definition at line 2027 of file PropertySheet.cpp.
References App::Property::getName().
Referenced by getPathValue(), setPathValue(), and Spreadsheet::Sheet::updateBindings().
isDirty()
bool Spreadsheet::PropertySheet::isDirty () const inline
Definition at line 183 of file PropertySheet.h.
Referenced by Spreadsheet::Sheet::mustExecute().
isHidden()
bool PropertySheet::isHidden (App::CellAddress address) const
Definition at line 1338 of file PropertySheet.cpp.
References SplineSurface::i.
isMergedCell()
bool PropertySheet::isMergedCell (App::CellAddress address) const
Definition at line 1333 of file PropertySheet.cpp.
Referenced by Spreadsheet::Sheet::isMergedCell().
isValidAlias()
bool PropertySheet::isValidAlias (const std::string & candidate)
Definition at line 147 of file PropertySheet.cpp.
References getValueFromAlias(), App::ExpressionParser::isTokenAConstant(), App::ExpressionParser::isTokenAUnit(), and isValidCellAddressName().
Referenced by Spreadsheet::Sheet::isValidAlias(), and setAlias().
isValidCellAddressName()
bool PropertySheet::isValidCellAddressName (const std::string & candidate)
Definition at line 130 of file PropertySheet.cpp.
References SCL.SimpleDataTypes::e, App::validColumn(), and App::validRow().
Referenced by Spreadsheet::Sheet::clearAll(), and isValidAlias().
mergeCells()
bool PropertySheet::mergeCells (App::CellAddress from, App::CellAddress to)
Definition at line 1230 of file PropertySheet.cpp.
References AtomicPropertyChange, SCL.SimpleDataTypes::c, clear(), App::CellAddress::col(), Spreadsheet::Cell::getSpans(), App::CellAddress::row(), setDirty(), setSpans(), and splitCell().
Referenced by Spreadsheet::Sheet::mergeCells(), pasteCells(), removeColumns(), removeRows(), and Restore().
onAddDep()
void PropertySheet::onAddDep (App::DocumentObject * obj) override protected virtual
Reimplemented from App::PropertyXLinkContainer.
Definition at line 1562 of file PropertySheet.cpp.
References draftgeoutils.faces::bind(), and App::DocumentObject::signalChanged.
onBreakLink()
void PropertySheet::onBreakLink (App::DocumentObject * obj) override protected virtual
Reimplemented from App::PropertyXLinkContainer.
Definition at line 1516 of file PropertySheet.cpp.
References invalidateDependants().
onContainerRestored()
void PropertySheet::onContainerRestored () override virtual
Called before calling DocumentObject::onDocumentRestored()
This function is called after finished calling Property::afterRestore() of all properties of objects. By then, the object dependency information is assumed ready. So, unlike Property::afterRestore(), this function is called on objects with dependency order.
Reimplemented from App::Property.
Definition at line 1770 of file PropertySheet.cpp.
References App::PropertyLinkBase::unregisterElementReference(), and TestSpreadsheet::v.
onRelabeledDocument()
void PropertySheet::onRelabeledDocument (const App::Document & doc) override virtual
Implements App::PropertyExpressionContainer.
Definition at line 1576 of file PropertySheet.cpp.
References SCL.SimpleDataTypes::c, toolbit-attributes::doc, and TestSpreadsheet::v.
onRemoveDep()
void PropertySheet::onRemoveDep (App::DocumentObject * obj) override protected virtual
Reimplemented from App::PropertyXLinkContainer.
Definition at line 1570 of file PropertySheet.cpp.
Paste()
void PropertySheet::Paste (const Property & from) override
Definition at line 315 of file PropertySheet.cpp.
References AtomicPropertyChange, SCL.SimpleDataTypes::c, Cell, Spreadsheet::Sheet::cellSpanChanged, clear(), App::Property::getContainer(), Spreadsheet::Cell::getSpans(), Spreadsheet::Cell::isMarked(), recomputeDependencies(), setDirty(), and sheet().
Referenced by setPyObject().
pasteCells() [1/2]
void PropertySheet::pasteCells (Base::XMLReader & reader, App::Range dstRange)
Definition at line 490 of file PropertySheet.cpp.
References AtomicPropertyChange, SCL.SimpleDataTypes::c, App::ExpressionModifier< P >::changed(), Spreadsheet::Sheet::clear(), App::CellAddress::col(), App::Range::colCount(), App::Range::column(), App::Expression::copy(), FC_THROWM, App::Range::from(), Spreadsheet::Sheet::getCell(), App::Property::getFullName(), Spreadsheet::Sheet::getNewCell(), App::CellAddress::isValid(), mergeCells(), App::Range::next(), Spreadsheet::Sheet::rangeUpdated, TechDrawTools.TaskFillTemplateFields::reader, recomputeDependencies(), App::CellAddress::row(), App::Range::row(), App::Range::rowCount(), splitCell(), and App::CellAddress::toString().
Referenced by SpreadsheetGui::SheetTableView::pasteClipboard().
pasteCells() [2/2]
void Spreadsheet::PropertySheet::pasteCells (const std::map< App::CellAddress, std::string > & cells, int rowOffset, int colOffset)
recomputeDependencies()
void PropertySheet::recomputeDependencies (App::CellAddress key)
Definition at line 1648 of file PropertySheet.cpp.
References AtomicPropertyChange.
Referenced by Spreadsheet::Sheet::execute(), insertColumns(), insertRows(), Paste(), pasteCells(), removeColumns(), removeRows(), and renameObjectIdentifiers().
referenceChanged()
bool PropertySheet::referenceChanged () const override virtual
Test if the element reference has changed after restore.
Reimplemented from App::PropertyLinkBase.
Definition at line 1846 of file PropertySheet.cpp.
removeColumns()
void PropertySheet::removeColumns (int col, int count)
Definition at line 1151 of file PropertySheet.cpp.
References AtomicPropertyChange, draftgeoutils.faces::bind(), App::ExpressionModifier< P >::changed(), clear(), Drawing::copy(), src.Mod.AddonManager.NetworkManager::count, App::Property::getContainer(), App::DocumentObject::getDocument(), Spreadsheet::Cell::getSpans(), mergeCells(), recomputeDependencies(), App::Document::renameObjectIdentifiers(), App::ExpressionModifier< P >::reset(), setDirty(), and Spreadsheet::Cell::visit().
Referenced by Spreadsheet::Sheet::removeColumns().
removeRows()
void PropertySheet::removeRows (int row, int count)
Definition at line 995 of file PropertySheet.cpp.
References AtomicPropertyChange, draftgeoutils.faces::bind(), App::ExpressionModifier< P >::changed(), clear(), Drawing::copy(), src.Mod.AddonManager.NetworkManager::count, App::Property::getContainer(), App::DocumentObject::getDocument(), Spreadsheet::Cell::getSpans(), mergeCells(), recomputeDependencies(), App::Document::renameObjectIdentifiers(), App::ExpressionModifier< P >::reset(), setDirty(), and Spreadsheet::Cell::visit().
Referenced by Spreadsheet::Sheet::removeRows().
renameObjectIdentifiers()
void PropertySheet::renameObjectIdentifiers (const std::map< App::ObjectIdentifier, App::ObjectIdentifier > & paths)
Definition at line 1584 of file PropertySheet.cpp.
References SCL.SimpleDataTypes::c, recomputeDependencies(), setDirty(), and TestSpreadsheet::v.
Referenced by Spreadsheet::Sheet::renameObjectIdentifiers().
Restore()
void PropertySheet::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Reimplemented from App::PropertyXLinkContainer.
Definition at line 419 of file PropertySheet.cpp.
References AtomicPropertyChange, App::CellAddress::col(), createCell(), Spreadsheet::Cell::getSpans(), SplineSurface::i, mergeCells(), TechDrawTools.TaskFillTemplateFields::reader, App::Restore, Spreadsheet::Cell::restore(), and App::CellAddress::row().
Save()
void PropertySheet::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Reimplemented from App::PropertyXLinkContainer.
Definition at line 390 of file PropertySheet.cpp.
References src.Mod.AddonManager.NetworkManager::count, Base::Writer::decInd(), Base::Writer::incInd(), Base::Writer::ind(), and Base::Writer::Stream().
setAlias()
void PropertySheet::setAlias (App::CellAddress address, const std::string & alias)
Definition at line 745 of file PropertySheet.cpp.
References AtomicPropertyChange, Spreadsheet::Cell::getAlias(), App::DocumentObject::getDocument(), App::DocumentObject::getFullName(), getValueFromAlias(), isValidAlias(), test::m, App::Document::renameObjectIdentifiers(), Spreadsheet::Cell::setAlias(), setDirty(), and App::CellAddress::toString().
Referenced by Spreadsheet::Sheet::setAlias(), and setPathValue().
setAlignment()
void PropertySheet::setAlignment (App::CellAddress address, int _alignment)
Definition at line 706 of file PropertySheet.cpp.
References Spreadsheet::Cell::setAlignment().
Referenced by Spreadsheet::Sheet::setAlignment().
setBackground()
void PropertySheet::setBackground (App::CellAddress address, const App::Color & color)
Definition at line 730 of file PropertySheet.cpp.
References Spreadsheet::Cell::setBackground().
Referenced by Spreadsheet::Sheet::setBackground().
setComputedUnit()
void PropertySheet::setComputedUnit (App::CellAddress address, const Base::Unit & unit)
Definition at line 798 of file PropertySheet.cpp.
References Spreadsheet::Cell::setComputedUnit(), and unit().
Referenced by Spreadsheet::Sheet::setComputedUnit(), and Spreadsheet::Sheet::setQuantityProperty().
setContent()
void PropertySheet::setContent (App::CellAddress address, const char * value)
Definition at line 699 of file PropertySheet.cpp.
References Spreadsheet::Cell::setContent().
Referenced by Spreadsheet::Sheet::setContent().
setDirty() [1/2]
void PropertySheet::setDirty ()
Definition at line 259 of file PropertySheet.cpp.
References AtomicPropertyChange, and getNonEmptyCells().
Referenced by afterRestore(), Path.Op.Gui.FeatureExtension.TaskPanelExtensionPage::extensionsClear(), insertColumns(), insertRows(), invalidateDependants(), mergeCells(), Paste(), removeColumns(), removeRows(), renameObjectIdentifiers(), setAlias(), Path.Op.Gui.ThreadMilling.TaskPanelOpPage::setFields(), splitCell(), Path.Op.Gui.FeatureExtension.TaskPanelExtensionPage::toggleExtensionCorners(), and Path.Op.Gui.FeatureExtension.TaskPanelExtensionPage::updateItemEnabled().
setDirty() [2/2]
void PropertySheet::setDirty (App::CellAddress address)
Definition at line 247 of file PropertySheet.cpp.
References SplineSurface::i.
Referenced by Path.Op.Gui.FeatureExtension.TaskPanelExtensionPage::extensionsClear(), Spreadsheet::Cell::setDirty(), Path.Op.Gui.ThreadMilling.TaskPanelOpPage::setFields(), Path.Op.Gui.FeatureExtension.TaskPanelExtensionPage::toggleExtensionCorners(), Spreadsheet::Sheet::touchCells(), and Path.Op.Gui.FeatureExtension.TaskPanelExtensionPage::updateItemEnabled().
setDisplayUnit()
void PropertySheet::setDisplayUnit (App::CellAddress address, const std::string & unit)
Definition at line 737 of file PropertySheet.cpp.
References Spreadsheet::Cell::setDisplayUnit(), and unit().
Referenced by Spreadsheet::Sheet::setDisplayUnit().
setExpressions()
void PropertySheet::setExpressions (std::map< App::ObjectIdentifier, App::ExpressionPtr > && exprs) override virtual
Implements App::PropertyExpressionContainer.
Definition at line 1939 of file PropertySheet.cpp.
References AtomicPropertyChange, Cell, clear(), Path.Post.scripts.opensbp_post::move(), and TestSpreadsheet::v.
setForeground()
void PropertySheet::setForeground (App::CellAddress address, const App::Color & color)
Definition at line 723 of file PropertySheet.cpp.
References Spreadsheet::Cell::setForeground().
Referenced by Spreadsheet::Sheet::setForeground().
setPathValue()
void PropertySheet::setPathValue (const App::ObjectIdentifier & path, const boost::any & value) override virtual
Set value of property.
Reimplemented from App::Property.
Definition at line 2099 of file PropertySheet.cpp.
References App::Range::address(), AtomicPropertyChange, App::CellAddress::col(), App::Range::colCount(), createCell(), SCL.SimpleDataTypes::e, FC_THROWM, App::Range::from(), Spreadsheet::Cell::getAlias(), getCellAddress(), App::Property::getContainer(), App::DocumentObject::getDocument(), Spreadsheet::Cell::getExpression(), App::Property::getFullName(), getValue(), getValueFromAlias(), isBindingPath(), KDL::min(), Path.Post.scripts.opensbp_post::move(), App::Range::next(), App::Expression::parse(), App::pyObjectFromAny(), App::CellAddress::row(), App::Range::rowCount(), setAlias(), App::CellAddress::setCol(), App::CellAddress::setRow(), App::Range::size(), and App::Range::to().
setPyObject()
void PropertySheet::setPyObject (PyObject * obj) override virtual
Reimplemented from Base::BaseClass.
Definition at line 1696 of file PropertySheet.cpp.
References Paste(), and Py::SmartPtr::ptr().
setSpans()
void PropertySheet::setSpans (App::CellAddress address, int rows, int columns)
Definition at line 805 of file PropertySheet.cpp.
References Spreadsheet::Sheet::cellSpanChanged, and Spreadsheet::Cell::setSpans().
Referenced by mergeCells(), Spreadsheet::Sheet::setSpans(), and splitCell().
setStyle()
void PropertySheet::setStyle (App::CellAddress address, const std::set< std::string > & _style)
Definition at line 716 of file PropertySheet.cpp.
References Spreadsheet::Cell::setStyle().
Referenced by Spreadsheet::Sheet::setStyle().
setValue()
void Spreadsheet::PropertySheet::setValue () inline
Definition at line 112 of file PropertySheet.h.
sheet()
Sheet* Spreadsheet::PropertySheet::sheet () const inline
Definition at line 158 of file PropertySheet.h.
Referenced by Spreadsheet::Cell::getFormattedQuantity(), Paste(), Spreadsheet::Cell::setContent(), Spreadsheet::Cell::setDisplayUnit(), Spreadsheet::Cell::setException(), and Spreadsheet::Cell::setResolveException().
splitCell()
void PropertySheet::splitCell (App::CellAddress address)
Definition at line 1279 of file PropertySheet.cpp.
References AtomicPropertyChange, SCL.SimpleDataTypes::c, App::CellAddress::col(), Spreadsheet::Cell::getSpans(), SplineSurface::i, App::CellAddress::row(), setDirty(), and setSpans().
Referenced by clear(), mergeCells(), pasteCells(), and Spreadsheet::Sheet::splitCell().
updateElementReference()
void PropertySheet::updateElementReference (App::DocumentObject * feature, bool reverse = false, bool notify = false) override virtual
Link type property interface APIs These APIs are moved here so that any type of property can have the property link behavior, e.g. the PropertyExpressionEngine Called to update the element reference of this link property
See also
_updateElementReference()
Reimplemented from App::PropertyLinkBase.
Definition at line 1824 of file PropertySheet.cpp.
References App::ExpressionModifier< P >::changed(), App::Property::getContainer(), femsolver.signal::notify(), App::DocumentObject::onUpdateElementReference(), and App::PropertyLinkBase::unregisterElementReference().
Friends And Related Function Documentation
AtomicPropertyChange
friend class AtomicPropertyChange friend
Definition at line 280 of file PropertySheet.h.
Referenced by adjustLink(), afterRestore(), breakLink(), clear(), Spreadsheet::Sheet::importFromFile(), insertColumns(), insertRows(), invalidateDependants(), mergeCells(), Spreadsheet::Cell::operator=(), Paste(), pasteCells(), recomputeDependencies(), removeColumns(), removeRows(), Restore(), Spreadsheet::Cell::restore(), Spreadsheet::Cell::setAlias(), setAlias(), Spreadsheet::Cell::setAlignment(), Spreadsheet::Cell::setBackground(), Spreadsheet::Cell::setComputedUnit(), Spreadsheet::Cell::setContent(), setDirty(), Spreadsheet::Cell::setDisplayUnit(), setExpressions(), Spreadsheet::Cell::setForeground(), setPathValue(), Spreadsheet::Cell::setSpans(), Spreadsheet::Cell::setStyle(), and splitCell().
Cell
friend class Cell friend
Definition at line 284 of file PropertySheet.h.
Referenced by createCell(), Paste(), and setExpressions().
Sheet
friend class Sheet friend
Definition at line 286 of file PropertySheet.h.
SheetObserver
friend class SheetObserver friend
Definition at line 282 of file PropertySheet.h.
The documentation for this class was generated from the following files:
PropertySheet.h
PropertySheet.cpp