FreeCAD: Gui::DocumentT Class Reference
Gui::DocumentT Class Reference
#include <DocumentObserver.h>
Public Member Functions
DocumentT ()
DocumentT (Document *)
DocumentT (const std::string &)
DocumentT (const DocumentT &)
~DocumentT ()
void operator= (const DocumentT &)
void operator= (const Document *)
void operator= (const std::string &)
Document * getDocument () const
std::string getDocumentName () const
std::string getGuiDocumentPython () const
std::string getAppDocumentPython () const
Detailed Description
The DocumentT class is a helper class to store the name of a document. This can be useful when you cannot rely on that the document still exists when you have to access it.
Author
Werner Mayer
Definition at line 43 of file Gui/DocumentObserver.h.
Constructor & Destructor Documentation
DocumentT() [1/4]
DocumentT::DocumentT () default
Constructor
DocumentT() [2/4]
DocumentT::DocumentT (Document * doc) explicit
Constructor
Definition at line 45 of file Gui/DocumentObserver.cpp.
References toolbit-attributes::doc.
DocumentT() [3/4]
DocumentT::DocumentT (const std::string & name) explicit
Constructor
Definition at line 50 of file Gui/DocumentObserver.cpp.
DocumentT() [4/4]
DocumentT::DocumentT (const DocumentT & doc)
Constructor
Definition at line 55 of file Gui/DocumentObserver.cpp.
References toolbit-attributes::doc.
~DocumentT()
DocumentT::~DocumentT () default
Destructor
Member Function Documentation
getAppDocumentPython()
std::string DocumentT::getAppDocumentPython () const
Get the App::Document as Python command.
Definition at line 104 of file Gui/DocumentObserver.cpp.
References Gui::Application::activeDocument(), toolbit-attributes::doc, Gui::Application::Instance, and Path.Post.scripts.refactored_centroid_post::str.
Referenced by Gui::ViewProviderT::getAppDocumentPython().
getDocument()
Document * DocumentT::getDocument () const
Get a pointer to the document or 0 if it doesn't exist any more.
Definition at line 79 of file Gui/DocumentObserver.cpp.
References Gui::Application::getDocument(), and Gui::Application::Instance.
getDocumentName()
std::string DocumentT::getDocumentName () const
Get the name of the document.
Definition at line 84 of file Gui/DocumentObserver.cpp.
getGuiDocumentPython()
std::string DocumentT::getGuiDocumentPython () const
Get the Gui::Document as Python command.
Definition at line 89 of file Gui/DocumentObserver.cpp.
References Gui::Application::activeDocument(), toolbit-attributes::doc, Gui::Application::Instance, and Path.Post.scripts.refactored_centroid_post::str.
Referenced by Gui::ViewProviderT::getGuiDocumentPython().
operator=() [1/3]
void DocumentT::operator= (const Document * doc)
Assignment operator
Definition at line 69 of file Gui/DocumentObserver.cpp.
References toolbit-attributes::doc.
operator=() [2/3]
void DocumentT::operator= (const DocumentT & doc)
Assignment operator
Definition at line 62 of file Gui/DocumentObserver.cpp.
References toolbit-attributes::doc.
operator=() [3/3]
void DocumentT::operator= (const std::string & name)
Assignment operator
Definition at line 74 of file Gui/DocumentObserver.cpp.
The documentation for this class was generated from the following files:
Gui/DocumentObserver.h
Gui/DocumentObserver.cpp