FreeCAD: Gui::OpenGLMultiBuffer Class Reference
Gui::OpenGLMultiBuffer Class Reference
#include <GLBuffer.h>
Public Member Functions
OpenGLMultiBuffer (GLenum type)
~OpenGLMultiBuffer ()
void setCurrentContext (uint32_t ctx)
bool create ()
bool isCreated (uint32_t ctx) const
void destroy ()
void allocate (const void *data, int count)
bool bind ()
void release ()
GLuint getBufferId () const
int size () const
Detailed Description
Definition at line 84 of file GLBuffer.h.
Constructor & Destructor Documentation
OpenGLMultiBuffer()
OpenGLMultiBuffer::OpenGLMultiBuffer (GLenum type)
Definition at line 192 of file GLBuffer.cpp.
~OpenGLMultiBuffer()
OpenGLMultiBuffer::~OpenGLMultiBuffer ()
Definition at line 201 of file GLBuffer.cpp.
References destroy().
Member Function Documentation
allocate()
void OpenGLMultiBuffer::allocate (const void * data, int count)
Definition at line 251 of file GLBuffer.cpp.
References src.Mod.AddonManager.NetworkManager::count.
bind()
bool OpenGLMultiBuffer::bind ()
Definition at line 258 of file GLBuffer.cpp.
create()
bool OpenGLMultiBuffer::create ()
Definition at line 215 of file GLBuffer.cpp.
Referenced by draftguitools.gui_labels.Label::action().
destroy()
void OpenGLMultiBuffer::destroy ()
Definition at line 237 of file GLBuffer.cpp.
References TestSpreadsheet::v.
Referenced by ~OpenGLMultiBuffer().
getBufferId()
GLuint OpenGLMultiBuffer::getBufferId () const
Definition at line 275 of file GLBuffer.cpp.
isCreated()
bool OpenGLMultiBuffer::isCreated (uint32_t ctx) const
Definition at line 231 of file GLBuffer.cpp.
release()
void OpenGLMultiBuffer::release ()
Definition at line 268 of file GLBuffer.cpp.
setCurrentContext()
void OpenGLMultiBuffer::setCurrentContext (uint32_t ctx)
Definition at line 208 of file GLBuffer.cpp.
size()
int OpenGLMultiBuffer::size () const
Definition at line 280 of file GLBuffer.cpp.
Referenced by Path.Post.Utils.GCodeEditorDialog::done().
The documentation for this class was generated from the following files:
GLBuffer.h
GLBuffer.cpp