FreeCAD: Base::Exception Class Reference
Base::Exception Class Reference
#include <Exception.h>
Public Member Functions
Base::Type getTypeId (void) const override
~Exception () noexcept override=default
Exception & operator= (const Exception &inst)
Exception & operator= (Exception &&inst) noexcept
virtual const char * what () const noexcept
virtual void ReportException () const
Reports exception. It includes a mechanism to only report an exception once.
void setMessage (const char *sMessage)
void setMessage (const std::string &sMessage)
std::string getMessage () const
std::string getFile () const
int getLine () const
std::string getFunction () const
bool getTranslatable () const
bool getReported () const
void setDebugInformation (const std::string &file, int line, const std::string &function)
void setTranslatable (bool translatable)
void setReported (bool reported)
PyObject * getPyObject () override
returns a Python dictionary containing the exception data
void setPyObject (PyObject *pydict) override
returns sets the exception data from a Python dictionary
virtual PyObject * getPyExceptionType () const
returns the corresponding python exception type
virtual void setPyException () const
Sets the Python error indicator and an error message.
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Protected Member Functions
Exception (const char *sMessage)
Exception (std::string sMessage)
Exception ()
Exception (const Exception &inst)
Exception (Exception &&inst) noexcept
Protected Attributes
std::string _sErrMsg
std::string _file
int _line
std::string _function
bool _isTranslatable
bool _isReported
Additional Inherited Members
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 194 of file Exception.h.
Constructor & Destructor Documentation
~Exception()
Base::Exception::~Exception () override default noexcept
Exception() [1/5]
Exception::Exception (const char * sMessage) explicit protected
Definition at line 51 of file Exception.cpp.
Exception() [2/5]
Exception::Exception (std::string sMessage) explicit protected
Definition at line 58 of file Exception.cpp.
Exception() [3/5]
Exception::Exception () protected
Definition at line 40 of file Exception.cpp.
Exception() [4/5]
Exception::Exception (const Exception & inst) protected default
Exception() [5/5]
Exception::Exception (Exception && inst) protected default noexcept
Member Function Documentation
create()
void * Exception::create (void) static
Definition at line 37 of file Exception.cpp.
Referenced by draftguitools.gui_labels.Label::action().
getClassTypeId()
Base::Type Exception::getClassTypeId (void) static
Definition at line 37 of file Exception.cpp.
Referenced by App::FeatureTestException::FeatureTestException().
getFile()
std::string Exception::getFile () const inline
Definition at line 974 of file Exception.h.
References _file.
Referenced by ArchReference.ArchReference::execute(), ArchReference.ArchReference::getColors(), ArchReference.ArchReference::getPartsList(), and getPyObject().
getFunction()
std::string Exception::getFunction () const inline
Definition at line 984 of file Exception.h.
References _function.
Referenced by getPyObject().
getLine()
int Exception::getLine () const inline
Definition at line 979 of file Exception.h.
References _line.
Referenced by getPyObject().
getMessage()
std::string Exception::getMessage () const inline
Definition at line 969 of file Exception.h.
References _sErrMsg.
Referenced by getPyObject(), and Sketcher::SketchObject::validateExternalLinks().
getPyExceptionType()
PyObject * Exception::getPyExceptionType () const virtual
returns the corresponding python exception type
Reimplemented in Base::RestoreError, Base::CADKernelError, Base::UnitsMismatchError, Base::UnderflowError, Base::OverflowError, Base::UnicodeError, Base::ParserError, Base::ExpressionError, Base::ReferenceError, Base::ZeroDivisionError, Base::NotImplementedError, Base::BadGraphError, Base::RuntimeError, Base::PropertyError, Base::AttributeError, Base::ImportError, Base::NameError, Base::IndexError, Base::ValueError, Base::TypeError, Base::UnknownProgramOption, Base::AbnormalProgramTermination, Base::AccessViolation, Base::MemoryException, Base::BadFormatError, Base::FileSystemError, Base::FileException, Base::XMLAttributeError, Base::XMLParseException, Base::XMLBaseException, Base::AbortException, and Base::PyException.
Definition at line 160 of file Exception.cpp.
References Base::PyExc_FC_GeneralError.
Referenced by setPyException().
getPyObject()
PyObject * Exception::getPyObject () override virtual
returns a Python dictionary containing the exception data
Reimplemented from Base::BaseClass.
Reimplemented in Base::FileException.
Definition at line 113 of file Exception.cpp.
References _isReported, getFile(), getFunction(), getLine(), getMessage(), getTranslatable(), Py::new_reference_to(), src.Mod.Test.testmakeWireString::String, and what().
Referenced by Base::FileException::getPyObject().
getReported()
bool Base::Exception::getReported () const inline
Definition at line 218 of file Exception.h.
getTranslatable()
bool Exception::getTranslatable () const inline
Definition at line 989 of file Exception.h.
References _isTranslatable.
Referenced by getPyObject().
getTypeId()
Base::Type Exception::getTypeId (void) const override virtual
Reimplemented from Base::BaseClass.
Reimplemented in Base::AbortException.
Definition at line 37 of file Exception.cpp.
init()
void Exception::init (void) static
Definition at line 37 of file Exception.cpp.
Referenced by App::Application::initTypes(), and DocumentObject.DocumentObject::onChanged().
operator=() [1/2]
Exception & Exception::operator= (const Exception & inst)
Definition at line 65 of file Exception.cpp.
References _file, _function, _isTranslatable, _line, and _sErrMsg.
Referenced by Base::MemoryException::operator=().
operator=() [2/2]
Exception & Exception::operator= (Exception && inst) noexcept
Definition at line 75 of file Exception.cpp.
References Path.Post.scripts.opensbp_post::move().
ReportException()
void Exception::ReportException () const virtual
Reports exception. It includes a mechanism to only report an exception once.
Reimplemented in Base::FileException, and Base::PyException.
Definition at line 90 of file Exception.cpp.
References _FC_ERR, _file, _function, _isReported, _line, _sErrMsg, and Path.Op.Surface::msg.
Referenced by PartDesignGui::TaskTransformedParameters::exitSelectionMode(), PartDesignGui::TaskRevolutionParameters::fillAxisCombo(), PartDesignGui::TaskRevolutionParameters::TaskRevolutionParameters(), PartDesignGui::TaskHelixParameters::~TaskHelixParameters(), and PartDesignGui::TaskRevolutionParameters::~TaskRevolutionParameters().
setDebugInformation()
void Exception::setDebugInformation (const std::string & file, int line, const std::string & function) inline
setter methods for including debug information intended to use via macro for autofilling of debugging information
Definition at line 995 of file Exception.h.
References _file, _function, _line, and DrawingExample::file.
setMessage() [1/2]
void Exception::setMessage (const char * sMessage) inline
Definition at line 959 of file Exception.h.
References _sErrMsg.
Referenced by Materials::InvalidMaterialType::InvalidMaterialType(), Materials::InvalidModel::InvalidModel(), Materials::LibraryNotFound::LibraryNotFound(), Materials::MaterialExists::MaterialExists(), Materials::MaterialReadError::MaterialReadError(), Materials::PropertyNotFound::PropertyNotFound(), Base::InterpreterSingleton::runInteractiveString(), Materials::Uninitialized::Uninitialized(), and Materials::UnknownValueType::UnknownValueType().
setMessage() [2/2]
void Exception::setMessage (const std::string & sMessage) inline
Definition at line 964 of file Exception.h.
References _sErrMsg.
setPyException()
void Exception::setPyException () const virtual
Sets the Python error indicator and an error message.
Reimplemented in Base::PyException.
Definition at line 165 of file Exception.cpp.
References getPyExceptionType(), Base::PyExc_FC_GeneralError, and what().
setPyObject()
void Exception::setPyObject (PyObject * pydict) override virtual
returns sets the exception data from a Python dictionary
Reimplemented from Base::BaseClass.
Reimplemented in Base::FileException.
Definition at line 127 of file Exception.cpp.
References _file, _function, _isReported, _isTranslatable, _line, _sErrMsg, SCL.SimpleDataTypes::e, and src.Mod.Test.testmakeWireString::String.
Referenced by Base::PyException::PyException(), and Base::FileException::setPyObject().
setReported()
void Base::Exception::setReported (bool reported) inline
Definition at line 229 of file Exception.h.
Referenced by Base::PyException::raiseException().
setTranslatable()
void Exception::setTranslatable (bool translatable) inline
Definition at line 1002 of file Exception.h.
References _isTranslatable.
what()
const char * Exception::what () const virtual noexcept
Reimplemented in Base::FileException, Base::XMLAttributeError, Base::XMLParseException, and Base::AbortException.
Definition at line 85 of file Exception.cpp.
References _sErrMsg.
Referenced by PartGui::DlgRevolution::accept(), PartGui::DlgScale::apply(), PartGui::DlgExtrusion::apply(), App::LocalCoordinateSystem::execute(), App::OriginGroupExtension::extensionExecute(), PartDesignGui::TaskTransformedParameters::fillAxisCombo(), PartDesignGui::TaskTransformedParameters::fillPlanesCombo(), getPyObject(), Base::PyException::ReportException(), Base::PyException::setPyException(), setPyException(), Gui::ViewProviderCoordinateSystem::setTemporaryVisibility(), PartDesignGui::TaskBoxPrimitives::TaskBoxPrimitives(), PartGui::DlgExtrusion::validate(), PartGui::DlgRevolution::validate(), Base::AbortException::what(), Base::XMLParseException::what(), Base::XMLAttributeError::what(), PartDesignGui::TaskBoxPrimitives::~TaskBoxPrimitives(), PartDesignGui::TaskLinearPatternParameters::~TaskLinearPatternParameters(), PartDesignGui::TaskMirroredParameters::~TaskMirroredParameters(), and PartDesignGui::TaskPolarPatternParameters::~TaskPolarPatternParameters().
Member Data Documentation
_file
std::string Base::Exception::_file protected
Definition at line 258 of file Exception.h.
Referenced by getFile(), operator=(), ReportException(), Base::FileException::ReportException(), setDebugInformation(), and setPyObject().
_function
std::string Base::Exception::_function protected
Definition at line 260 of file Exception.h.
Referenced by getFunction(), operator=(), ReportException(), Base::FileException::ReportException(), setDebugInformation(), and setPyObject().
_isReported
bool Base::Exception::_isReported mutable protected
Definition at line 262 of file Exception.h.
Referenced by getPyObject(), Base::PyException::raiseException(), Base::PyException::ReportException(), ReportException(), Base::FileException::ReportException(), and setPyObject().
_isTranslatable
bool Base::Exception::_isTranslatable protected
Definition at line 261 of file Exception.h.
Referenced by getTranslatable(), operator=(), setPyObject(), and setTranslatable().
_line
int Base::Exception::_line protected
Definition at line 259 of file Exception.h.
Referenced by getLine(), operator=(), ReportException(), Base::FileException::ReportException(), setDebugInformation(), and setPyObject().
_sErrMsg
std::string Base::Exception::_sErrMsg protected
Definition at line 257 of file Exception.h.
Referenced by Base::AbnormalProgramTermination::AbnormalProgramTermination(), Base::AbortException::AbortException(), Base::AccessViolation::AccessViolation(), getMessage(), Base::MemoryException::MemoryException(), operator=(), Base::PyException::PyException(), Base::PyException::raiseException(), ReportException(), Base::FileException::setFileName(), setMessage(), setPyObject(), Base::SystemExitException::SystemExitException(), what(), Base::XMLAttributeError::XMLAttributeError(), and Base::XMLParseException::XMLParseException().
The documentation for this class was generated from the following files:
Exception.h
Exception.cpp