FreeCAD: Base::ExceptionFactory Class Reference
Base::ExceptionFactory Class Reference
#include <ExceptionFactory.h>
Public Member Functions
void raiseException (PyObject *pydict) const
Public Member Functions inherited from Base::Factory
void AddProducer (const char *sClassName, AbstractProducer *pcProducer)
Adds a new prducer instance.
bool CanProduce (const char *sClassName) const
returns true if there is a producer for this class registered
std::list< std::string > CanProduce () const
returns a list of all registered producer
virtual ~Factory ()
destruction
Static Public Member Functions
static ExceptionFactory & Instance ()
static void Destruct ()
Additional Inherited Members
Protected Member Functions inherited from Base::Factory
void * Produce (const char *sClassName) const
produce a class with the given name
Factory ()=default
construction
Protected Attributes inherited from Base::Factory
std::map< const std::string, AbstractProducer * > _mpcProducers
Detailed Description
The ExceptionFactory
Definition at line 53 of file ExceptionFactory.h.
Member Function Documentation
Destruct()
void ExceptionFactory::Destruct () static
Definition at line 41 of file ExceptionFactory.cpp.
Instance()
ExceptionFactory & ExceptionFactory::Instance () static
Definition at line 33 of file ExceptionFactory.cpp.
Referenced by Base::ExceptionProducer< CLASS >::ExceptionProducer(), and Base::PyException::raiseException().
raiseException()
void ExceptionFactory::raiseException (PyObject * pydict) const
Definition at line 47 of file ExceptionFactory.cpp.
References Base::Factory::_mpcProducers, raiseException(), and src.Mod.Test.testmakeWireString::String.
Referenced by raiseException(), and Base::PyException::raiseException().
The documentation for this class was generated from the following files:
ExceptionFactory.h
ExceptionFactory.cpp