FreeCAD: ImportOCAF2.cpp File Reference
ImportOCAF2.cpp File Reference
#include "PreCompiled.h"
#include <Interface_Static.hxx>
#include <Quantity_ColorRGBA.hxx>
#include <Standard_Failure.hxx>
#include <Standard_Version.hxx>
#include <TDF_AttributeSequence.hxx>
#include <TDF_Label.hxx>
#include <TDF_LabelSequence.hxx>
#include <TopExp.hxx>
#include <TopExp_Explorer.hxx>
#include <TopoDS_Iterator.hxx>
#include <XCAFDoc_DocumentTool.hxx>
#include <XCAFDoc_GraphNode.hxx>
#include <XCAFDoc_ShapeTool.hxx>
#include <boost/algorithm/string.hpp>
#include <boost/format.hpp>
#include <App/Application.h>
#include <App/Document.h>
#include <App/DocumentObject.h>
#include <App/GroupExtension.h>
#include <App/Link.h>
#include <Base/Console.h>
#include <Base/FileInfo.h>
#include <Base/Parameter.h>
#include <Mod/Part/App/FeatureCompound.h>
#include <Mod/Part/App/Interface.h>
#include <Mod/Part/App/OCAF/ImportExportSettings.h>
#include "ImportOCAF2.h"
Classes
struct ChildInfo
Macros
#define OCC_COLOR_SPACE Quantity_TOC_RGB
Functions
static void setPlacement (App::PropertyPlacement *prop, const TopoDS_Shape &shape)
Macro Definition Documentation
OCC_COLOR_SPACE
#define OCC_COLOR_SPACE Quantity_TOC_RGB
Definition at line 65 of file ImportOCAF2.cpp.
Function Documentation
setPlacement()
static void setPlacement (App::PropertyPlacement * prop, const TopoDS_Shape & shape) static
Definition at line 159 of file ImportOCAF2.cpp.
References Part::TopoShape::convert(), App::PropertyPlacement::getValue(), and App::PropertyPlacement::setValue().