FreeCAD: Part::Geom2dCurve Class Reference
Part::Geom2dCurve Class Reference
#include <Geometry2d.h>
Public Member Functions
Geom2dCurve ()
~Geom2dCurve () override
TopoDS_Shape toShape () const override
bool tangent (double u, gp_Dir2d &) const
Base::Vector2d pointAtParameter (double u) const
Base::Vector2d firstDerivativeAtParameter (double u) const
Base::Vector2d secondDerivativeAtParameter (double u) const
bool normal (double u, gp_Dir2d &dir) const
bool closestParameter (const Base::Vector2d &point, double &u) const
bool closestParameterToBasicCurve (const Base::Vector2d &point, double &u) const
Public Member Functions inherited from Part::Geometry2d
~Geometry2d () override
virtual const Handle (Geom2d_Geometry) &handle() const =0
unsigned int getMemSize () const override
void Save (Base::Writer &) const override
void Restore (Base::XMLReader &) override
virtual Geometry2d * clone () const =0
returns a cloned object
Geometry2d (const Geometry2d &)=delete
Geometry2d & operator= (const Geometry2d &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Protected Member Functions inherited from Part::Geometry2d
Geometry2d ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 121 of file Geometry2d.h.
Constructor & Destructor Documentation
Geom2dCurve()
Geom2dCurve::Geom2dCurve () default
~Geom2dCurve()
Geom2dCurve::~Geom2dCurve () override default
Member Function Documentation
closestParameter()
bool Geom2dCurve::closestParameter (const Base::Vector2d & point, double & u) const
Definition at line 273 of file Geometry2d.cpp.
References SCL.SimpleDataTypes::c, SCL.SimpleDataTypes::e, Handle(), and buildPsets::u.
closestParameterToBasicCurve()
bool Geom2dCurve::closestParameterToBasicCurve (const Base::Vector2d & point, double & u) const
Definition at line 293 of file Geometry2d.cpp.
References SCL.SimpleDataTypes::c, SCL.SimpleDataTypes::e, Handle(), and buildPsets::u.
firstDerivativeAtParameter()
Base::Vector2d Geom2dCurve::firstDerivativeAtParameter (double u) const
Definition at line 243 of file Geometry2d.cpp.
References SCL.SimpleDataTypes::c, Handle(), buildPsets::u, and SurfaceTests.TestBlendCurve::vec.
normal()
bool Geom2dCurve::normal (double u, gp_Dir2d & dir) const
Definition at line 261 of file Geometry2d.cpp.
References SCL.SimpleDataTypes::c, Handle(), and buildPsets::u.
Referenced by ArchRoof._Roof::getPerpendicular().
pointAtParameter()
Base::Vector2d Geom2dCurve::pointAtParameter (double u) const
Definition at line 234 of file Geometry2d.cpp.
References SCL.SimpleDataTypes::c, Handle(), and buildPsets::u.
secondDerivativeAtParameter()
Base::Vector2d Geom2dCurve::secondDerivativeAtParameter (double u) const
Definition at line 252 of file Geometry2d.cpp.
References SCL.SimpleDataTypes::c, Handle(), buildPsets::u, and SurfaceTests.TestBlendCurve::vec.
tangent()
bool Geom2dCurve::tangent (double u, gp_Dir2d & dir) const
Definition at line 222 of file Geometry2d.cpp.
References SCL.SimpleDataTypes::c, Handle(), and buildPsets::u.
toShape()
TopoDS_Shape Geom2dCurve::toShape () const override virtual
Implements Part::Geometry2d.
Definition at line 215 of file Geometry2d.cpp.
References SCL.SimpleDataTypes::c, and Handle().
The documentation for this class was generated from the following files:
Geometry2d.h
Geometry2d.cpp