FreeCAD: TechDraw::LineGroup Class Reference
TechDraw::LineGroup Class Reference
#include <LineGroup.h>
Public Member Functions
LineGroup ()
LineGroup (std::string groupName)
~LineGroup ()
double getWeight (std::string s)
void setWeight (std::string s, double weight)
void dump (const char *title)
std::string getName (void)
void setName (std::string s)
Static Public Member Functions
static std::vector< double > split (std::string line)
static std::string getRecordFromFile (std::string parmFile, int groupNumber)
static LineGroup * lineGroupFactory (int groupNumber)
static double getDefaultWidth (std::string weightName, int groupNumber=-1)
Returns the default line width given a weight name and group number.
static std::string getGroupNamesFromFile (std::string FileName)
Protected Member Functions
void init (void)
Protected Attributes
std::string m_name
double m_thin
double m_graphic
double m_thick
double m_extra
Detailed Description
Definition at line 57 of file LineGroup.h.
Constructor & Destructor Documentation
LineGroup() [1/2]
LineGroup::LineGroup ()
Definition at line 42 of file LineGroup.cpp.
References init().
Referenced by lineGroupFactory().
LineGroup() [2/2]
LineGroup::LineGroup (std::string groupName)
Definition at line 47 of file LineGroup.cpp.
References init(), and m_name.
~LineGroup()
LineGroup::~LineGroup ()
Definition at line 54 of file LineGroup.cpp.
Member Function Documentation
dump()
void LineGroup::dump (const char * title)
Definition at line 94 of file LineGroup.cpp.
References Base::Console(), m_extra, m_graphic, m_name, m_thick, m_thin, Base::ConsoleSingleton::Message(), and Plot::title().
getDefaultWidth()
double LineGroup::getDefaultWidth (std::string weightName, int lineGroupNumber = -1) static
Returns the default line width given a weight name and group number.
Parameters
weightName can be "Thick", "Thin", "Graphic" or "Extra"
lineGroupNumber if -1 will then use groupNumber in preferences. Default value is -1.
Returns
the default line width.
Definition at line 188 of file LineGroup.cpp.
References TechDraw::Preferences::lineGroup(), and lineGroupFactory().
Referenced by TechDrawGui::TaskSelectLineAttributes::accept(), TechDraw::CosmeticVertex::CosmeticVertex(), TechDrawGui::QGIMatting::draw(), TechDrawGui::TaskCenterLine::getCenterWidth(), TechDraw::DrawUtil::getDefaultLineWeight(), TechDraw::LineFormat::getDefEdgeWidth(), TechDrawGui::ViewProviderLeader::getDefLineWeight(), TechDrawGui::ViewProviderRichAnno::getDefLineWeight(), TechDrawGui::ViewProviderGeomHatch::getParameters(), TechDrawGui::makeObliqueChainDimension(), TechDrawGui::makeObliqueCoordDimension(), TechDrawGui::TaskRichAnno::prefWeight(), TechDrawGui::ViewProviderDimension::prefWeight(), TechDrawGui::TaskSelectLineAttributes::setUiEdit(), TechDrawGui::TaskLeaderLine::setUiPrimary(), TechDrawGui::ViewProviderBalloon::ViewProviderBalloon(), and TechDrawGui::ViewProviderViewPart::ViewProviderViewPart().
getGroupNamesFromFile()
std::string LineGroup::getGroupNamesFromFile (std::string FileName) static
Definition at line 201 of file LineGroup.cpp.
References Base::Console(), importOCA::getline(), and Base::ConsoleSingleton::Message().
getName()
std::string TechDraw::LineGroup::getName (void) inline
Definition at line 87 of file LineGroup.h.
getRecordFromFile()
std::string LineGroup::getRecordFromFile (std::string parmFile, int groupNumber) static
Definition at line 130 of file LineGroup.cpp.
References Base::Console(), Base::ConsoleSingleton::Error(), importOCA::getline(), and Base::ConsoleSingleton::Message().
Referenced by lineGroupFactory().
getWeight()
double LineGroup::getWeight (std::string s)
Definition at line 67 of file LineGroup.cpp.
References m_extra, m_graphic, m_thick, m_thin, and toolbit-attributes::s.
init()
void LineGroup::init (void) protected
Definition at line 58 of file LineGroup.cpp.
References m_extra, m_graphic, m_name, m_thick, and m_thin.
Referenced by LineGroup(), and DocumentObject.DocumentObject::onChanged().
lineGroupFactory()
LineGroup * LineGroup::lineGroupFactory (int groupNumber) static
Definition at line 161 of file LineGroup.cpp.
References Base::Console(), Base::ConsoleSingleton::Error(), getRecordFromFile(), LineGroup(), TechDraw::Preferences::lineGroupFile(), setWeight(), and split().
Referenced by getDefaultWidth().
setName()
void TechDraw::LineGroup::setName (std::string s) inline
Definition at line 88 of file LineGroup.h.
setWeight()
void LineGroup::setWeight (std::string s, double weight)
Definition at line 81 of file LineGroup.cpp.
References m_extra, m_graphic, m_thick, m_thin, and toolbit-attributes::s.
Referenced by lineGroupFactory().
split()
std::vector< double > LineGroup::split (std::string line) static
Definition at line 105 of file LineGroup.cpp.
References Base::Console(), importOCA::getline(), result, and Base::ConsoleSingleton::Warning().
Referenced by lineGroupFactory().
Member Data Documentation
m_extra
double TechDraw::LineGroup::m_extra protected
Definition at line 111 of file LineGroup.h.
Referenced by dump(), getWeight(), init(), and setWeight().
m_graphic
double TechDraw::LineGroup::m_graphic protected
Definition at line 109 of file LineGroup.h.
Referenced by dump(), getWeight(), init(), and setWeight().
m_name
std::string TechDraw::LineGroup::m_name protected
Definition at line 107 of file LineGroup.h.
Referenced by dump(), init(), and LineGroup().
m_thick
double TechDraw::LineGroup::m_thick protected
Definition at line 110 of file LineGroup.h.
Referenced by dump(), getWeight(), init(), and setWeight().
m_thin
double TechDraw::LineGroup::m_thin protected
Definition at line 108 of file LineGroup.h.
Referenced by dump(), getWeight(), init(), and setWeight().
The documentation for this class was generated from the following files:
LineGroup.h
LineGroup.cpp