FreeCAD: MeshGui::MeshSelection Class Reference
MeshGui::MeshSelection Class Reference
#include <MeshSelection.h>
Public Member Functions
MeshSelection ()
~MeshSelection ()
MeshSelection (const MeshSelection &)=delete
MeshSelection (MeshSelection &&)=delete
MeshSelection & operator= (const MeshSelection &)=delete
MeshSelection & operator= (MeshSelection &&)=delete
void setEnabledViewerSelection (bool)
void startSelection ()
void startDeselection ()
void stopSelection ()
bool deleteSelection ()
bool deleteSelectionBorder ()
void fullSelection ()
void clearSelection ()
void invertSelection ()
void selectComponent (int)
void deselectComponent (int)
void selectTriangle ()
void deselectTriangle ()
void setCheckOnlyPointToUserTriangles (bool)
bool isCheckedOnlyPointToUserTriangles () const
void setCheckOnlyVisibleTriangles (bool)
bool isCheckedOnlyVisibleTriangles () const
void setAddComponentOnClick (bool)
void setRemoveComponentOnClick (bool)
void setObjects (const std::vector< Gui::SelectionObject > &)
std::vector< App::DocumentObject * > getObjects () const
void setViewer (Gui::View3DInventorViewer *v)
Protected Member Functions
void setCallback (SoEventCallbackCB *cb)
std::list< ViewProviderMesh * > getViewProviders () const
Gui::View3DInventorViewer * getViewer () const
void prepareFreehandSelection (bool, SoEventCallbackCB *cb)
void startInteractiveCallback (Gui::View3DInventorViewer *viewer, SoEventCallbackCB *cb)
void stopInteractiveCallback (Gui::View3DInventorViewer *viewer)
Detailed Description
Definition at line 46 of file MeshSelection.h.
Constructor & Destructor Documentation
MeshSelection() [1/3]
MeshSelection::MeshSelection ()
Definition at line 79 of file MeshSelection.cpp.
References setCallback().
~MeshSelection()
MeshSelection::~MeshSelection ()
Definition at line 84 of file MeshSelection.cpp.
References getViewer(), stopInteractiveCallback(), and OfflineRenderingUtils::viewer().
MeshSelection() [2/3]
MeshGui::MeshSelection::MeshSelection (const MeshSelection &) delete
MeshSelection() [3/3]
MeshGui::MeshSelection::MeshSelection (MeshSelection &&) delete
Member Function Documentation
clearSelection()
void MeshSelection::clearSelection ()
Definition at line 266 of file MeshSelection.cpp.
References getViewProviders().
Referenced by ReverseEngineeringGui::SegmentationManual::createSegment(), MeshGui::RemoveComponents::onDeselectAllClicked(), ReverseEngineeringGui::SegmentationManual::onDeselectAllClicked(), MeshGui::RemoveComponents::reject(), ReverseEngineeringGui::SegmentationManual::reject(), MeshGui::ParametersDialog::~ParametersDialog(), and MeshGui::Selection::~Selection().
deleteSelection()
bool MeshSelection::deleteSelection ()
Definition at line 274 of file MeshSelection.cpp.
References MeshCore::MeshAlgorithm::CountFacetFlag(), Mesh::MeshObject::getKernel(), Mesh::PropertyMeshKernel::getValue(), getViewProviders(), Mesh::Feature::Mesh, and MeshCore::MeshFacet::SELECTED.
Referenced by MeshGui::RemoveComponents::deleteSelection().
deleteSelectionBorder()
bool MeshSelection::deleteSelectionBorder ()
Definition at line 299 of file MeshSelection.cpp.
References MeshCore::MeshFacet::_aulPoints, MeshCore::MeshAlgorithm::GetBorderPoints(), MeshCore::MeshKernel::GetFacets(), MeshCore::MeshAlgorithm::GetFacetsFlag(), Mesh::MeshObject::getKernel(), MeshCore::MeshKernel::GetPoints(), Mesh::PropertyMeshKernel::getValue(), getViewProviders(), SplineSurface::i, MeshCore::MeshFacet::IsFlag(), Mesh::Feature::Mesh, MeshCore::MeshAlgorithm::ResetFacetFlag(), MeshCore::MeshAlgorithm::ResetPointFlag(), MeshCore::MeshFacet::SELECTED, Path.Dressup.Utils::selection(), MeshCore::MeshAlgorithm::SetFacetsFlag(), MeshCore::MeshAlgorithm::SetPointsFlag(), MeshCore::MeshPoint::VISIT, and MeshCore::MeshFacet::VISIT.
deselectComponent()
void MeshSelection::deselectComponent (int size)
Definition at line 382 of file MeshSelection.cpp.
References Mesh2Shape::faces, Mesh::PropertyMeshKernel::getValuePtr(), getViewProviders(), Mesh::Feature::Mesh, MeshCore::MeshComponents::OverEdge, and MeshCore::MeshComponents::SearchForComponents().
Referenced by MeshGui::RemoveComponents::onDeselectComponentsClicked().
deselectTriangle()
void MeshSelection::deselectTriangle ()
Definition at line 417 of file MeshSelection.cpp.
References getViewer(), startInteractiveCallback(), stopInteractiveCallback(), and OfflineRenderingUtils::viewer().
Referenced by MeshGui::RemoveComponents::onDeselectTriangleClicked().
fullSelection()
void MeshSelection::fullSelection ()
Definition at line 253 of file MeshSelection.cpp.
References Mesh2Shape::faces, Path.Base.Generator.dogboneII::generate(), Mesh::PropertyMeshKernel::getValuePtr(), getViewProviders(), and Mesh::Feature::Mesh.
Referenced by MeshGui::RemoveComponents::onSelectAllClicked(), and ReverseEngineeringGui::SegmentationManual::onSelectAllClicked().
getObjects()
std::vector< App::DocumentObject * > MeshSelection::getObjects () const
Definition at line 112 of file MeshSelection.cpp.
References toolbit-attributes::doc, App::Application::getActiveDocument(), App::GetApplication(), Base::Persistence::getClassTypeId(), and replaceobj::objs.
Referenced by MeshGui::Selection::getObjects(), and getViewProviders().
getViewer()
Gui::View3DInventorViewer * MeshSelection::getViewer () const protected
Definition at line 155 of file MeshSelection.cpp.
References Gui::Application::activeDocument(), toolbit-attributes::doc, Gui::Application::Instance, Base::BaseClass::isDerivedFrom(), and OfflineRenderingUtils::viewer().
Referenced by deselectTriangle(), prepareFreehandSelection(), selectTriangle(), setEnabledViewerSelection(), stopSelection(), and ~MeshSelection().
getViewProviders()
std::list< ViewProviderMesh * > MeshSelection::getViewProviders () const protected
Definition at line 134 of file MeshSelection.cpp.
References Base::Persistence::getClassTypeId(), getObjects(), Gui::Application::getViewProvider(), Gui::Application::Instance, Gui::ViewProvider::isVisible(), and replaceobj::objs.
Referenced by clearSelection(), deleteSelection(), deleteSelectionBorder(), deselectComponent(), fullSelection(), invertSelection(), and selectComponent().
invertSelection()
void MeshSelection::invertSelection ()
Definition at line 352 of file MeshSelection.cpp.
References getViewProviders().
Referenced by MeshGui::RemoveComponents::invertSelection().
isCheckedOnlyPointToUserTriangles()
bool MeshSelection::isCheckedOnlyPointToUserTriangles () const
Definition at line 435 of file MeshSelection.cpp.
isCheckedOnlyVisibleTriangles()
bool MeshSelection::isCheckedOnlyVisibleTriangles () const
Definition at line 445 of file MeshSelection.cpp.
operator=() [1/2]
MeshSelection& MeshGui::MeshSelection::operator= (const MeshSelection &) delete
operator=() [2/2]
MeshSelection& MeshGui::MeshSelection::operator= (MeshSelection &&) delete
prepareFreehandSelection()
void MeshSelection::prepareFreehandSelection (bool add, SoEventCallbackCB * cb) protected
Definition at line 196 of file MeshSelection.cpp.
References draftgeoutils.intersections::connect(), CROSS_HEIGHT, CROSS_HOT_X, CROSS_HOT_Y, CROSS_WIDTH, SIM::Coin3D::Quarter::QuarterWidget::devicePixelRatioChanged(), getViewer(), Gui::FreehandSelection::setClosed(), Gui::PolyPickerSelection::setColor(), Gui::PolyPickerSelection::setLineWidth(), startInteractiveCallback(), stopInteractiveCallback(), and OfflineRenderingUtils::viewer().
Referenced by startDeselection(), and startSelection().
selectComponent()
void MeshSelection::selectComponent (int size)
Definition at line 360 of file MeshSelection.cpp.
References Mesh2Shape::faces, Mesh::PropertyMeshKernel::getValuePtr(), getViewProviders(), Mesh::Feature::Mesh, MeshCore::MeshComponents::OverEdge, and MeshCore::MeshComponents::SearchForComponents().
Referenced by MeshGui::RemoveComponents::onSelectComponentsClicked(), and ReverseEngineeringGui::SegmentationManual::onSelectComponentsClicked().
selectTriangle()
void MeshSelection::selectTriangle ()
Definition at line 404 of file MeshSelection.cpp.
References getViewer(), startInteractiveCallback(), stopInteractiveCallback(), and OfflineRenderingUtils::viewer().
Referenced by MeshGui::RemoveComponents::onSelectTriangleClicked(), and ReverseEngineeringGui::SegmentationManual::onSelectTriangleClicked().
setAddComponentOnClick()
void MeshSelection::setAddComponentOnClick (bool on)
Definition at line 450 of file MeshSelection.cpp.
Referenced by ReverseEngineeringGui::SegmentationManual::onSelectCompToggled(), MeshGui::RemoveComponents::onSelectCompToggled(), MeshGui::RemoveComponents::onSelectTriangleClicked(), and ReverseEngineeringGui::SegmentationManual::onSelectTriangleClicked().
setCallback()
void MeshSelection::setCallback (SoEventCallbackCB * cb) protected
Definition at line 102 of file MeshSelection.cpp.
Referenced by MeshSelection().
setCheckOnlyPointToUserTriangles()
void MeshSelection::setCheckOnlyPointToUserTriangles (bool on)
Definition at line 430 of file MeshSelection.cpp.
Referenced by ReverseEngineeringGui::SegmentationManual::onScreenTrianglesToggled(), MeshGui::RemoveComponents::onScreenTrianglesToggled(), MeshGui::ParametersDialog::ParametersDialog(), MeshGui::RemoveComponents::RemoveComponents(), ReverseEngineeringGui::SegmentationManual::SegmentationManual(), and MeshGui::Selection::Selection().
setCheckOnlyVisibleTriangles()
void MeshSelection::setCheckOnlyVisibleTriangles (bool on)
Definition at line 440 of file MeshSelection.cpp.
Referenced by ReverseEngineeringGui::SegmentationManual::onVisibleTrianglesToggled(), MeshGui::RemoveComponents::onVisibleTrianglesToggled(), MeshGui::ParametersDialog::ParametersDialog(), MeshGui::RemoveComponents::RemoveComponents(), ReverseEngineeringGui::SegmentationManual::SegmentationManual(), and MeshGui::Selection::Selection().
setEnabledViewerSelection()
void MeshSelection::setEnabledViewerSelection (bool on)
Definition at line 94 of file MeshSelection.cpp.
References getViewer(), and OfflineRenderingUtils::viewer().
Referenced by MeshGui::ParametersDialog::ParametersDialog(), MeshGui::RemoveComponents::reject(), ReverseEngineeringGui::SegmentationManual::reject(), MeshGui::RemoveComponents::RemoveComponents(), ReverseEngineeringGui::SegmentationManual::SegmentationManual(), MeshGui::Selection::Selection(), MeshGui::ParametersDialog::~ParametersDialog(), and MeshGui::Selection::~Selection().
setObjects()
void MeshSelection::setObjects (const std::vector< Gui::SelectionObject > & obj)
Definition at line 107 of file MeshSelection.cpp.
Referenced by MeshGui::ParametersDialog::ParametersDialog(), MeshGui::SegmentationBestFit::SegmentationBestFit(), and MeshGui::Selection::setObjects().
setRemoveComponentOnClick()
void MeshSelection::setRemoveComponentOnClick (bool on)
Definition at line 455 of file MeshSelection.cpp.
Referenced by MeshGui::RemoveComponents::onDeselectCompToggled(), and MeshGui::RemoveComponents::onDeselectTriangleClicked().
setViewer()
void MeshSelection::setViewer (Gui::View3DInventorViewer * v)
Definition at line 150 of file MeshSelection.cpp.
References TestSpreadsheet::v.
startDeselection()
void MeshSelection::startDeselection ()
Definition at line 239 of file MeshSelection.cpp.
References prepareFreehandSelection().
Referenced by MeshGui::RemoveComponents::onDeselectRegionClicked().
startInteractiveCallback()
void MeshSelection::startInteractiveCallback (Gui::View3DInventorViewer * viewer, SoEventCallbackCB * cb) protected
Definition at line 175 of file MeshSelection.cpp.
References OfflineRenderingUtils::viewer().
Referenced by deselectTriangle(), prepareFreehandSelection(), and selectTriangle().
startSelection()
void MeshSelection::startSelection ()
Definition at line 234 of file MeshSelection.cpp.
References prepareFreehandSelection().
Referenced by MeshGui::RemoveComponents::onSelectRegionClicked(), and ReverseEngineeringGui::SegmentationManual::onSelectRegionClicked().
stopInteractiveCallback()
void MeshSelection::stopInteractiveCallback (Gui::View3DInventorViewer * viewer) protected
Definition at line 186 of file MeshSelection.cpp.
References OfflineRenderingUtils::viewer().
Referenced by deselectTriangle(), prepareFreehandSelection(), selectTriangle(), stopSelection(), and ~MeshSelection().
stopSelection()
void MeshSelection::stopSelection ()
Definition at line 244 of file MeshSelection.cpp.
References getViewer(), stopInteractiveCallback(), and OfflineRenderingUtils::viewer().
The documentation for this class was generated from the following files:
MeshSelection.h
MeshSelection.cpp