FreeCAD: Gui::OverlayManager Class Reference
Gui::OverlayManager Class Reference
Class that manages overlay dockable widgets.
#include <OverlayManager.h>
Classes
class Private
Public Types
enum ReloadMode { ReloadMode::ReloadPending = 0, ReloadMode::ReloadPause = 1, ReloadMode::ReloadResume = 2 }
Reload mode.
enum OverlayMode {
OverlayMode::ToggleActive, OverlayMode::ToggleTransparent, OverlayMode::EnableActive, OverlayMode::DisableActive,
OverlayMode::EnableAll, OverlayMode::DisableAll, OverlayMode::ToggleAll, OverlayMode::TransparentAll,
OverlayMode::TransparentNone, OverlayMode::ToggleTransparentAll, OverlayMode::ToggleLeft, OverlayMode::ToggleRight,
OverlayMode::ToggleTop, OverlayMode::ToggleBottom
}
Overlay mode.
Public Member Functions
OverlayManager ()
~OverlayManager () override
void restore ()
restore states
void save ()
save states
void retranslate ()
Retranslate text on language change.
void refreshIcons ()
Reload icon images.
void reload (ReloadMode mode=ReloadMode::ReloadPending)
void refresh (QWidget *widget=nullptr, bool refreshStyle=false)
void setupTitleBar (QDockWidget *)
Setup title bar for a QDockWidget.
void setOverlayMode (OverlayMode mode)
Set overlay mode.
void setMouseTransparent (bool enabled)
Enable/disable mouse transparent mode.
bool isMouseTransparent () const
Report if mouse transparent mode is active.
bool isUnderOverlay () const
Check if the cursor is within an overlay docked widget.
void initDockWidget (QDockWidget *)
Initialize a newly created dock widget.
void setupDockWidget (QDockWidget *, int dockArea=Qt::NoDockWidgetArea)
Prepare a dock widget for overlay display.
void unsetupDockWidget (QDockWidget *)
Switch a dock widget back to normal display.
void dragDockWidget (const QPoint &pos, QWidget *widget, const QPoint &offset, const QSize &size, bool drop=false)
void floatDockWidget (QDockWidget *)
Float an overlay docked widget.
QWidget * getLastMouseInterceptWidget () const
Return the last widget whose mouse event got intercepted by the overlay manager for mouse pass through.
const QString & getStyleSheet () const
Return the stylesheet for overlay widgets.
bool getHideTab () const
Check whether to hide tab in overlay dock widget.
Static Public Member Functions
static void setFocusView ()
Helper function to set focus when switching active sub window.
static OverlayManager * instance ()
Return the singleton instance of the overlay manager.
static void destruct ()
Destroy the overlay manager.
Protected Member Functions
bool eventFilter (QObject *obj, QEvent *ev) override
void registerDockWidget (const QString &name, OverlayTabWidget *)
Register a named docked widget with an overlay tab widget.
void unregisterDockWidget (const QString &name, OverlayTabWidget *)
Unregister a named docked widget with an overlay tab widget.
Friends
class Private
class OverlayTabWidget
Detailed Description
Class that manages overlay dockable widgets.
Definition at line 41 of file OverlayManager.h.
Member Enumeration Documentation
OverlayMode
enum Gui::OverlayManager::OverlayMode strong
Overlay mode.
Enumerator
ToggleActive
Toggle the focused widget between normal and overlay on top of MDI client area.
ToggleTransparent
Toggle overlay dock widget background between opaque and transparent.
EnableActive
Make the focused widget switch to overlay on top of MDI client area.
DisableActive
Make the focused widget switch back to normal dockable widget.
EnableAll
Make all docked widget switch to overlay.
DisableAll
Make all docked widget switch back to normal.
ToggleAll
Toggle all docked widget between normal and overlay.
TransparentAll
Set all overlay dock widget to transparent background.
TransparentNone
Set all overlay dock widget to opaque background.
ToggleTransparentAll
Toggle all overlay dock widget background between opaque and transparent.
ToggleLeft
Toggle show/hide of the left docked widgets.
ToggleRight
Toggle show/hide of the right docked widgets.
ToggleTop
Toggle show/hide of the top docked widgets.
ToggleBottom
Toggle show/hide of the bottom docked widgets.
Definition at line 83 of file OverlayManager.h.
ReloadMode
enum Gui::OverlayManager::ReloadMode strong
Reload mode.
Enumerator
ReloadPending
Reload is pending.
ReloadPause
Reload is paused.
ReloadResume
Resume state reload.
Definition at line 57 of file OverlayManager.h.
Constructor & Destructor Documentation
OverlayManager()
OverlayManager::OverlayManager ()
Definition at line 1457 of file OverlayManager.cpp.
References Gui::getMainWindow(), and Private.
Referenced by instance().
~OverlayManager()
OverlayManager::~OverlayManager () override
Definition at line 1463 of file OverlayManager.cpp.
Member Function Documentation
destruct()
void OverlayManager::destruct () static
Destroy the overlay manager.
Definition at line 1451 of file OverlayManager.cpp.
References _instance.
dragDockWidget()
void OverlayManager::dragDockWidget (const QPoint & pos, QWidget * widget, const QPoint & offset, const QSize & size, bool drop = false)
Mouse event handler for dragging a dock widget
Parameters
pos mouse cursor position
widget dragging widget, can either be a QDockWidget if it is floating, or a OverlayTabWidget if docked in overlay mode
offset offset from the mouse cursor to the widget origin
size widget size before dragging start
drop whether to drop after drag to the position
Definition at line 2027 of file OverlayManager.cpp.
References RobotExample::pos.
Referenced by Gui::OverlayTitleBar::mouseMoveEvent(), Gui::OverlaySplitterHandle::mouseMoveEvent(), Gui::OverlayTitleBar::mouseReleaseEvent(), and Gui::OverlaySplitterHandle::mouseReleaseEvent().
eventFilter()
bool OverlayManager::eventFilter (QObject * obj, QEvent * ev) override protected
Definition at line 1617 of file OverlayManager.cpp.
References Gui::OverlayManager::Private::_lastPos, _Overlays, Gui::OverlayManager::Private::_trackingOverlay, Gui::OverlayManager::Private::_trackingWidget, findTabWidget(), Gui::OverlayParams::getDockOverlayAutoMouseThrough(), Gui::OverlayParams::getDockOverlayWheelDelay(), Gui::OverlayParams::getDockOverlayWheelPassThrough(), Gui::getMainWindow(), Gui::MainWindow::getMdiArea(), Gui::OverlayProxyWidget::HitInner, Gui::OverlayManager::Private::interceptEvent(), Gui::OverlayManager::Private::intercepting, isNear(), Gui::OverlayTabWidget::isTransparent(), Gui::isTreeViewDragging(), isUnderOverlay(), Gui::OverlayManager::Private::lastIntercept, Gui::OverlayManager::Private::mouseTransparent, src.Mod.Test.testPathArray::o, Init::parent, RobotExample::pos, Gui::OverlayManager::Private::raising, refresh(), Gui::SelectionSingleton::rmvPreselect(), Gui::Selection(), Gui::OverlayManager::Private::setMouseTransparent(), Path.Post.scripts.grbl_post::type, Gui::OverlayManager::Private::wheelDelay, and Gui::OverlayManager::Private::wheelPos.
floatDockWidget()
void OverlayManager::floatDockWidget (QDockWidget * dock)
Float an overlay docked widget.
Definition at line 2036 of file OverlayManager.cpp.
Referenced by Gui::OverlaySplitterHandle::onAction().
getHideTab()
bool OverlayManager::getHideTab () const
Check whether to hide tab in overlay dock widget.
Definition at line 2061 of file OverlayManager.cpp.
References OverlayStyleSheet::hideTab, and OverlayStyleSheet::instance().
getLastMouseInterceptWidget()
QWidget * OverlayManager::getLastMouseInterceptWidget () const
Return the last widget whose mouse event got intercepted by the overlay manager for mouse pass through.
Definition at line 2051 of file OverlayManager.cpp.
getStyleSheet()
const QString & OverlayManager::getStyleSheet () const
Return the stylesheet for overlay widgets.
Definition at line 2056 of file OverlayManager.cpp.
References OverlayStyleSheet::activeStyleSheet, and OverlayStyleSheet::instance().
Referenced by Gui::OverlayTabWidget::setOverlayMode().
initDockWidget()
void OverlayManager::initDockWidget (QDockWidget * dw)
Initialize a newly created dock widget.
Definition at line 1474 of file OverlayManager.cpp.
References Gui::OverlayManager::Private::_dockWidgetNameMap, Gui::OverlayManager::Private::_overlayInfos, draftgeoutils.intersections::connect(), src.Mod.Test.testPathArray::o, Gui::OverlayManager::Private::onToggleDockWidget(), and Gui::OverlayManager::Private::refresh().
instance()
OverlayManager * OverlayManager::instance () static
Return the singleton instance of the overlay manager.
Definition at line 1444 of file OverlayManager.cpp.
References _instance, and OverlayManager().
Referenced by Gui::OverlayTabWidget::_setOverlayMode(), _updateDockWidget(), Gui::OverlayTabWidget::addWidget(), Gui::OverlayTabWidget::enterEvent(), Gui::OverlayTabWidget::leaveEvent(), Gui::MainWindow::loadWindowSettings(), Gui::MainWindow::MainWindow(), Gui::OverlayTitleBar::mouseMoveEvent(), Gui::OverlaySplitterHandle::mouseMoveEvent(), Gui::OverlayTitleBar::mouseReleaseEvent(), Gui::OverlaySplitterHandle::mouseReleaseEvent(), Gui::OverlayTabWidget::onAction(), Gui::OverlaySplitterHandle::onAction(), Gui::OverlayManager::Private::onAction(), Gui::OverlayTabWidget::onAnimationStateChanged(), OverlayStyleSheet::OnChange(), Gui::OverlayTabWidget::onSizeGripMove(), Gui::OverlayTitleBar::paintEvent(), Gui::OverlayTabWidget::removeWidget(), Gui::OverlayTabWidget::restore(), Gui::MainWindow::saveWindowSettings(), Gui::OverlayTabWidget::setAutoMode(), Gui::OverlayTabWidget::setOverlayMode(), Gui::OverlayTabWidget::setState(), and Gui::OverlayTabWidget::setTransparent().
isMouseTransparent()
bool OverlayManager::isMouseTransparent () const
Report if mouse transparent mode is active.
Definition at line 1985 of file OverlayManager.cpp.
isUnderOverlay()
bool OverlayManager::isUnderOverlay () const
Check if the cursor is within an overlay docked widget.
Definition at line 1990 of file OverlayManager.cpp.
References findTabWidget(), and RobotExample::pos.
Referenced by eventFilter().
refresh()
void OverlayManager::refresh (QWidget * widget = nullptr, bool refreshStyle = false)
Refresh overlay internal layout
Parameters
widget optional source widget that triggers the refresh
refreshStyle whether to reload stylesheet
Definition at line 1975 of file OverlayManager.cpp.
Referenced by _updateDockWidget(), Path.Tool.Gui.BitEdit.ToolBitEditor::accept(), Gui::OverlayTabWidget::enterEvent(), eventFilter(), Gui::OverlayTabWidget::leaveEvent(), Gui::OverlayTabWidget::onAction(), Gui::OverlayTabWidget::onAnimationStateChanged(), OverlayStyleSheet::OnChange(), Gui::OverlayTabWidget::onSizeGripMove(), Gui::OverlayTabWidget::setAutoMode(), Gui::OverlayTabWidget::setState(), Gui::OverlayTabWidget::setTransparent(), Path.Tool.Gui.Controller.ToolControllerEditor::setupUi(), and Path.Tool.Gui.BitEdit.ToolBitEditor::setupUI().
refreshIcons()
void OverlayManager::refreshIcons ()
Reload icon images.
Definition at line 1595 of file OverlayManager.cpp.
References Gui::OverlayManager::Private::refreshIcons().
registerDockWidget()
void OverlayManager::registerDockWidget (const QString & name, OverlayTabWidget * widget) protected
Register a named docked widget with an overlay tab widget.
Definition at line 2041 of file OverlayManager.cpp.
Referenced by Gui::OverlayTabWidget::addWidget(), and Gui::OverlayTabWidget::restore().
reload()
void OverlayManager::reload (ReloadMode mode = ReloadMode::ReloadPending)
Set reload mode
An internal timer is used to batch handle all relevant parameter changes. The function is provided to let other code temporarily disable the timer before changing the parameter, and then resume it after done.
Definition at line 1600 of file OverlayManager.cpp.
References Gui::OverlayManager::Private::reload().
Referenced by Gui::MainWindow::MainWindow().
restore()
void OverlayManager::restore ()
restore states
Definition at line 2001 of file OverlayManager.cpp.
References draftgeoutils.intersections::connect(), and Gui::Control().
Referenced by src.Mod.Show.mTempoVis.TempoVis::__del__(), and Gui::MainWindow::loadWindowSettings().
retranslate()
void OverlayManager::retranslate ()
Retranslate text on language change.
Definition at line 1590 of file OverlayManager.cpp.
References Gui::OverlayManager::Private::retranslate().
save()
void OverlayManager::save ()
save states
Definition at line 1996 of file OverlayManager.cpp.
Referenced by src.Mod.Show.mTempoVis.TempoVis::modify(), src.Mod.Show.mTempoVis.TempoVis::modifyVPProperty(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onSaveStyle(), src.Mod.Show.mTempoVis.TempoVis::saveCamera(), Gui::MainWindow::saveWindowSettings(), and nativeifc.ifc_viewproviders.ifc_vp_document::setupContextMenu().
setFocusView()
void OverlayManager::setFocusView () static
Helper function to set focus when switching active sub window.
Definition at line 2066 of file OverlayManager.cpp.
References Gui::MainWindow::activeWindow(), Gui::getMainWindow(), and Instance.
Referenced by Gui::OverlayTabWidget::addWidget(), Gui::OverlayManager::Private::dragDockWidget(), Gui::OverlayManager::Private::floatDockWidget(), Gui::OverlayManager::Private::onAction(), and Gui::OverlayTabWidget::removeWidget().
setMouseTransparent()
void OverlayManager::setMouseTransparent (bool enabled)
Enable/disable mouse transparent mode.
Definition at line 1980 of file OverlayManager.cpp.
setOverlayMode()
void OverlayManager::setOverlayMode (OverlayMode mode)
Set overlay mode.
Definition at line 1468 of file OverlayManager.cpp.
References Gui::OverlayManager::Private::setOverlayMode().
Referenced by Gui::OverlayTabWidget::onAction(), and Gui::OverlayManager::Private::onAction().
setupDockWidget()
void OverlayManager::setupDockWidget (QDockWidget * dw, int dockArea = Qt::NoDockWidgetArea)
Prepare a dock widget for overlay display.
Definition at line 1503 of file OverlayManager.cpp.
References Gui::OverlayManager::Private::setupTitleBar().
setupTitleBar()
void OverlayManager::setupTitleBar (QDockWidget * dock)
Setup title bar for a QDockWidget.
Definition at line 2010 of file OverlayManager.cpp.
Referenced by Gui::OverlayTabWidget::removeWidget().
unregisterDockWidget()
void OverlayManager::unregisterDockWidget (const QString & name, OverlayTabWidget * widget) protected
Unregister a named docked widget with an overlay tab widget.
Definition at line 2046 of file OverlayManager.cpp.
Referenced by Gui::OverlayTabWidget::removeWidget().
unsetupDockWidget()
void OverlayManager::unsetupDockWidget (QDockWidget * dw)
Switch a dock widget back to normal display.
Definition at line 1509 of file OverlayManager.cpp.
References Gui::OverlayManager::Private::toggleOverlay(), and Unset.
Friends And Related Function Documentation
OverlayTabWidget
friend class OverlayTabWidget friend
Definition at line 189 of file OverlayManager.h.
Private
friend class Private friend
Definition at line 188 of file OverlayManager.h.
Referenced by OverlayManager().
The documentation for this class was generated from the following files:
OverlayManager.h
OverlayManager.cpp