FreeCAD: Import::WriterStep Class Reference
Import::WriterStep Class Reference
#include <WriterStep.h>
Public Member Functions
WriterStep (const Base::FileInfo &file)
void write (Handle(TDocStd_Document) hDoc) const
Detailed Description
Definition at line 53 of file WriterStep.h.
Constructor & Destructor Documentation
WriterStep()
WriterStep::WriterStep (const Base::FileInfo & file) explicit
Definition at line 40 of file WriterStep.cpp.
References DrawingExample::file.
Member Function Documentation
write()
void WriterStep::write (Handle(TDocStd_Document) hDoc) const
Definition at line 44 of file WriterStep.cpp.
References Part::encodeFilename(), DrawingExample::file, App::GetApplication(), ParameterGrp::GetASCII(), App::Application::getExecutableName(), ParameterGrp::GetGroup(), App::Application::GetUserParameter(), Part::Interface::On, and Part::Interface::writeStepAssembly().
The documentation for this class was generated from the following files:
WriterStep.h
WriterStep.cpp