FreeCAD: Exporter.cpp File Reference
Exporter.cpp File Reference
#include "PreCompiled.h"
#include <algorithm>
#include <boost/algorithm/string/replace.hpp>
#include <boost/core/ignore_unused.hpp>
#include <vector>
#include <App/Application.h>
#include <App/ComplexGeoData.h>
#include <App/ComplexGeoDataPy.h>
#include <App/DocumentObject.h>
#include <Base/Exception.h>
#include <Base/FileInfo.h>
#include <Base/Interpreter.h>
#include <Base/Sequencer.h>
#include <Base/Stream.h>
#include <Base/Tools.h>
#include "Core/Iterator.h"
#include "Core/IO/Writer3MF.h"
#include <zipios++/zipoutputstream.h>
#include "Exporter.h"
Classes
class Mesh::Exporter3MF::Private
class Mesh::ExporterAMF::VertLess
Functions
static std::vector< std::string > expandSubObjectNames (const App::DocumentObject *obj, std::map< const App::DocumentObject *, std::vector< std::string >> &subObjectNameCache, int depth)
Function Documentation
expandSubObjectNames()
static std::vector<std::string> expandSubObjectNames (const App::DocumentObject * obj, std::map< const App::DocumentObject *, std::vector< std::string >> & subObjectNameCache, int depth) static
Definition at line 51 of file Exporter.cpp.
References App::GetApplication(), App::DocumentObject::getLinkedObject(), App::DocumentObject::getSubObject(), App::DocumentObject::getSubObjects(), App::DocumentObject::isElementVisible(), and importers.importIFCmulticore::subs.
Referenced by Mesh::Exporter::addObject().