FreeCAD: Gui::Dialog::DlgCheckableMessageBox Class Reference
Gui::Dialog::DlgCheckableMessageBox Class Reference
#include <DlgCheckableMessageBox.h>
Public Member Functions
DlgCheckableMessageBox (QWidget *parent)
~DlgCheckableMessageBox () override
QString text () const
void setText (const QString &)
void setPrefEntry (const QString &entry)
void setPrefPath (const QString &path)
void accept () override
void reject () override
bool isChecked () const
void setChecked (bool s)
QString checkBoxText () const
void setCheckBoxText (const QString &)
QDialogButtonBox::StandardButtons standardButtons () const
void setStandardButtons (QDialogButtonBox::StandardButtons s)
QDialogButtonBox::StandardButton defaultButton () const
void setDefaultButton (QDialogButtonBox::StandardButton s)
QPixmap iconPixmap () const
void setIconPixmap (const QPixmap &p)
QAbstractButton * clickedButton () const
QDialogButtonBox::StandardButton clickedStandardButton () const
Static Public Member Functions
static QDialogButtonBox::StandardButton question (QWidget *parent, const QString &title, const QString &question, const QString &checkBoxText, bool *checkBoxSetting, QDialogButtonBox::StandardButtons buttons=QDialogButtonBox::Yes|QDialogButtonBox::No, QDialogButtonBox::StandardButton defaultButton=QDialogButtonBox::No)
static QMessageBox::StandardButton dialogButtonBoxToMessageBoxButton (QDialogButtonBox::StandardButton)
static void showMessage (const QString &header, const QString &message, bool check=false, const QString &checkText=QString::fromLatin1("Don't show me again"))
static void showMessage (const QString &header, const QString &message, const QString &prefPath, const QString &paramEntry, bool entryDefault=false, bool check=false, const QString &checkText=QString::fromLatin1("Don't show me again"))
Same as showMessage above, but it checks the specific preference path and parameter provided, defaulting to entryDefault value if the parameter is not present.
Properties
QString text
QPixmap iconPixmap
bool isChecked
QString checkBoxText
QDialogButtonBox::StandardButtons buttons
QDialogButtonBox::StandardButton defaultButton
Detailed Description
Definition at line 101 of file DlgCheckableMessageBox.h.
Constructor & Destructor Documentation
DlgCheckableMessageBox()
Gui::Dialog::DlgCheckableMessageBox::DlgCheckableMessageBox (QWidget * parent) explicit
Definition at line 168 of file DlgCheckableMessageBox.cpp.
References InitGui::t.
~DlgCheckableMessageBox()
Gui::Dialog::DlgCheckableMessageBox::~DlgCheckableMessageBox () override
Definition at line 183 of file DlgCheckableMessageBox.cpp.
References buildPsets::p.
Member Function Documentation
accept()
void Gui::Dialog::DlgCheckableMessageBox::accept () override
Definition at line 291 of file DlgCheckableMessageBox.cpp.
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
checkBoxText()
QString Gui::Dialog::DlgCheckableMessageBox::checkBoxText () const
clickedButton()
QAbstractButton * Gui::Dialog::DlgCheckableMessageBox::clickedButton () const
Definition at line 205 of file DlgCheckableMessageBox.cpp.
References InitGui::t.
clickedStandardButton()
QDialogButtonBox::StandardButton Gui::Dialog::DlgCheckableMessageBox::clickedStandardButton () const
Definition at line 210 of file DlgCheckableMessageBox.cpp.
defaultButton()
QDialogButtonBox::StandardButton Gui::Dialog::DlgCheckableMessageBox::defaultButton () const
dialogButtonBoxToMessageBoxButton()
QMessageBox::StandardButton Gui::Dialog::DlgCheckableMessageBox::dialogButtonBoxToMessageBoxButton (QDialogButtonBox::StandardButton db) static
Definition at line 327 of file DlgCheckableMessageBox.cpp.
iconPixmap()
QPixmap Gui::Dialog::DlgCheckableMessageBox::iconPixmap () const
isChecked()
bool Gui::Dialog::DlgCheckableMessageBox::isChecked () const
Referenced by draftguitools.gui_snaps.Draft_Snap_Lock::GetResources(), draftguitools.gui_snaps.Draft_Snap_Midpoint::GetResources(), draftguitools.gui_snaps.Draft_Snap_Perpendicular::GetResources(), draftguitools.gui_snaps.Draft_Snap_Grid::GetResources(), draftguitools.gui_snaps.Draft_Snap_Intersection::GetResources(), draftguitools.gui_snaps.Draft_Snap_Parallel::GetResources(), draftguitools.gui_snaps.Draft_Snap_Endpoint::GetResources(), draftguitools.gui_snaps.Draft_Snap_Angle::GetResources(), draftguitools.gui_snaps.Draft_Snap_Center::GetResources(), draftguitools.gui_snaps.Draft_Snap_Extension::GetResources(), draftguitools.gui_snaps.Draft_Snap_Near::GetResources(), draftguitools.gui_snaps.Draft_Snap_Ortho::GetResources(), draftguitools.gui_snaps.Draft_Snap_Special::GetResources(), draftguitools.gui_snaps.Draft_Snap_Dimensions::GetResources(), and draftguitools.gui_snaps.Draft_Snap_WorkingPlane::GetResources().
question()
QDialogButtonBox::StandardButton Gui::Dialog::DlgCheckableMessageBox::question (QWidget * parent, const QString & title, const QString & question, const QString & checkBoxText, bool * checkBoxSetting, QDialogButtonBox::StandardButtons buttons = QDialogButtonBox::Yes|QDialogButtonBox::No, QDialogButtonBox::StandardButton defaultButton = QDialogButtonBox::No) static
Definition at line 306 of file DlgCheckableMessageBox.cpp.
reject()
void Gui::Dialog::DlgCheckableMessageBox::reject () override
Definition at line 298 of file DlgCheckableMessageBox.cpp.
Referenced by bimcommands.BimReorder.BIM_Reorder_TaskPanel::accept(), draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), draftguitools.gui_selectplane.Draft_SelectPlane::action(), JointObject.TaskAssemblyCreateJoint::autoClosedOnTransactionChange(), femexamples.examplesgui.FemExamples::clicked(), CommandCreateView.TaskAssemblyCreateView::KeyboardEvent(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), bimcommands.BimProjectManager.BIM_ProjectManager::loadTemplate(), bimcommands.BimLibrary.BIM_Library_TaskPanel::mouseClick(), bimcommands.BimProjectManager.BIM_ProjectManager::saveTemplate(), and Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit().
setCheckBoxText()
void Gui::Dialog::DlgCheckableMessageBox::setCheckBoxText (const QString & t)
Definition at line 259 of file DlgCheckableMessageBox.cpp.
References Gui::Dialog::getStandardIcon(), Init::parent, setIconPixmap(), setText(), and Plot::title().
setChecked()
void Gui::Dialog::DlgCheckableMessageBox::setChecked (bool s)
Definition at line 249 of file DlgCheckableMessageBox.cpp.
setDefaultButton()
void Gui::Dialog::DlgCheckableMessageBox::setDefaultButton (QDialogButtonBox::StandardButton s)
Definition at line 283 of file DlgCheckableMessageBox.cpp.
setIconPixmap()
void Gui::Dialog::DlgCheckableMessageBox::setIconPixmap (const QPixmap & p)
Definition at line 238 of file DlgCheckableMessageBox.cpp.
References App::GetApplication(), App::Application::GetParameterGroupByPath(), and ParameterGrp::SetBool().
Referenced by setCheckBoxText().
setPrefEntry()
void Gui::Dialog::DlgCheckableMessageBox::setPrefEntry (const QString & entry)
Definition at line 188 of file DlgCheckableMessageBox.cpp.
setPrefPath()
void Gui::Dialog::DlgCheckableMessageBox::setPrefPath (const QString & path)
Definition at line 195 of file DlgCheckableMessageBox.cpp.
References toolbit-attributes::s.
setStandardButtons()
void Gui::Dialog::DlgCheckableMessageBox::setStandardButtons (QDialogButtonBox::StandardButtons s)
Definition at line 269 of file DlgCheckableMessageBox.cpp.
setText()
void Gui::Dialog::DlgCheckableMessageBox::setText (const QString & t)
Definition at line 222 of file DlgCheckableMessageBox.cpp.
References SCL.SimpleDataTypes::b, and toolbit-attributes::s.
Referenced by setCheckBoxText(), and src.Mod.AddonManager.Widgets.addonmanager_widget_readme_browser.WidgetReadmeBrowser::setMarkdown().
showMessage() [1/2]
void Gui::Dialog::DlgCheckableMessageBox::showMessage (const QString & header, const QString & message, bool check = false, const QString & checkText = QString::fromLatin1("Don't show me again")) static
convenient show method It shows a dialog with header and message provided and a checkbox in check state with the message provided. It uses a parameter in path "User parameter:BaseApp/CheckMessages" derived from the header test, defaulting to false, to store the status of the checkbox, when the user exits the modal dialog.
Definition at line 121 of file DlgCheckableMessageBox.cpp.
Referenced by SketcherGui::notifyConstraintSubstitutions(), and Gui::Dialog::DocumentRecovery::onButtonCleanupClicked().
showMessage() [2/2]
void Gui::Dialog::DlgCheckableMessageBox::showMessage (const QString & header, const QString & message, const QString & prefPath, const QString & paramEntry, bool entryDefault = false, bool check = false, const QString & checkText = QString::fromLatin1("Don't show me again")) static
Same as showMessage above, but it checks the specific preference path and parameter provided, defaulting to entryDefault value if the parameter is not present.
Definition at line 140 of file DlgCheckableMessageBox.cpp.
standardButtons()
QDialogButtonBox::StandardButtons Gui::Dialog::DlgCheckableMessageBox::standardButtons () const
Definition at line 264 of file DlgCheckableMessageBox.cpp.
text()
QString Gui::Dialog::DlgCheckableMessageBox::text () const
Property Documentation
buttons
QDialogButtonBox::StandardButtons Gui::Dialog::DlgCheckableMessageBox::buttons read write
Definition at line 109 of file DlgCheckableMessageBox.h.
Referenced by src.Mod.PartDesign.WizardShaft.WizardShaft.TaskWizardShaft::updateButton(), and src.Mod.PartDesign.WizardShaft.WizardShaft.TaskWizardShaft::updateButtons().
checkBoxText
QString Gui::Dialog::DlgCheckableMessageBox::checkBoxText read write
Definition at line 108 of file DlgCheckableMessageBox.h.
defaultButton
QDialogButtonBox::StandardButton Gui::Dialog::DlgCheckableMessageBox::defaultButton read write
Definition at line 110 of file DlgCheckableMessageBox.h.
iconPixmap
QPixmap Gui::Dialog::DlgCheckableMessageBox::iconPixmap read write
Definition at line 105 of file DlgCheckableMessageBox.h.
isChecked
bool Gui::Dialog::DlgCheckableMessageBox::isChecked read write
Definition at line 106 of file DlgCheckableMessageBox.h.
Referenced by draftguitools.gui_snaps.Draft_Snap_Lock::GetResources(), draftguitools.gui_snaps.Draft_Snap_Midpoint::GetResources(), draftguitools.gui_snaps.Draft_Snap_Perpendicular::GetResources(), draftguitools.gui_snaps.Draft_Snap_Grid::GetResources(), draftguitools.gui_snaps.Draft_Snap_Intersection::GetResources(), draftguitools.gui_snaps.Draft_Snap_Parallel::GetResources(), draftguitools.gui_snaps.Draft_Snap_Endpoint::GetResources(), draftguitools.gui_snaps.Draft_Snap_Angle::GetResources(), draftguitools.gui_snaps.Draft_Snap_Center::GetResources(), draftguitools.gui_snaps.Draft_Snap_Extension::GetResources(), draftguitools.gui_snaps.Draft_Snap_Near::GetResources(), draftguitools.gui_snaps.Draft_Snap_Ortho::GetResources(), draftguitools.gui_snaps.Draft_Snap_Special::GetResources(), draftguitools.gui_snaps.Draft_Snap_Dimensions::GetResources(), and draftguitools.gui_snaps.Draft_Snap_WorkingPlane::GetResources().
text
QString Gui::Dialog::DlgCheckableMessageBox::text read write
Definition at line 104 of file DlgCheckableMessageBox.h.
Referenced by importSVG.svgHandler::characters(), bimcommands.BimText.BIM_Text::createObject(), draftguitools.gui_texts.Text::createObject(), draftviewproviders.view_text.ViewProviderText::createObject(), importSVG.svgHandler::endElement(), importers.exportIFCHelper.SIUnitCreator::getSIPrefix(), importers.exportIFCHelper.SIUnitCreator::getSIUnitName(), and src.Mod.Test.unittestgui.ProgressBar::paint().
The documentation for this class was generated from the following files:
DlgCheckableMessageBox.h
DlgCheckableMessageBox.cpp