FreeCAD: Gui::Dialog::DlgCustomKeyboardImp Class Reference
Gui::Dialog::DlgCustomKeyboardImp Class Reference
#include <DlgKeyboardImp.h>
Public Member Functions
DlgCustomKeyboardImp (QWidget *parent=nullptr)
~DlgCustomKeyboardImp () override
Public Member Functions inherited from Gui::Dialog::CustomizeActionPage
CustomizeActionPage (QWidget *parent=nullptr)
~CustomizeActionPage () override
Static Public Member Functions
static boost::signals2::connection initCommandWidgets (QTreeWidget *commandTreeWidget, QTreeWidgetItem *separatorItem, QComboBox *comboGroups, QLineEdit *editCommand, QTreeWidget *priorityList=nullptr, QAbstractButton *buttonUp=nullptr, QAbstractButton *buttonDown=nullptr, Gui::AccelLineEdit *editShortcut=nullptr, Gui::AccelLineEdit *currentShortcut=nullptr)
Internal helper function for handling command list widgets
static void initCommandCompleter (QLineEdit *, QComboBox *combo, QTreeWidget *treeWidget, QTreeWidgetItem *separatorItem)
static boost::signals2::connection initCommandList (QTreeWidget *, QTreeWidgetItem *, QComboBox *combo)
static void initPriorityList (QTreeWidget *, QAbstractButton *buttonUp, QAbstractButton *buttonDown)
static void populateCommandGroups (QComboBox *)
static void populateCommandList (QTreeWidget *, QTreeWidgetItem *, QComboBox *)
static void populatePriorityList (QTreeWidget *priorityList, AccelLineEdit *editor, AccelLineEdit *current)
void setupConnections ()
void onCategoryBoxActivated (int index)
void onCommandTreeWidgetCurrentItemChanged (QTreeWidgetItem *)
void onButtonAssignClicked ()
void onButtonClearClicked ()
void onButtonResetClicked ()
void onButtonResetAllClicked ()
void onEditShortcutTextChanged (const QString &)
void showEvent (QShowEvent *e) override
void changeEvent (QEvent *e) override
void setShortcutOfCurrentAction (const QString &)
void onAddMacroAction (const QByteArray &) override
void onRemoveMacroAction (const QByteArray &) override
void onModifyMacroAction (const QByteArray &) override
Additional Inherited Members
Protected Slots inherited from Gui::Dialog::CustomizeActionPage
virtual void onAddMacroAction (const QByteArray &)=0
virtual void onRemoveMacroAction (const QByteArray &)=0
virtual void onModifyMacroAction (const QByteArray &)=0
Protected Member Functions inherited from Gui::Dialog::CustomizeActionPage
bool event (QEvent *e) override
Detailed Description
Shows an overview of all available commands of all groups and modules. You can customize your workbenches just by drag&dropping any commands onto the toolbars or commandbars. But you cannot modify any standard toolbars or commandbars such as "File, View, ...". It is only possible to customize your own toolbars or commandbars.
Author
Werner Mayer
Definition at line 53 of file DlgKeyboardImp.h.
Constructor & Destructor Documentation
DlgCustomKeyboardImp()
DlgCustomKeyboardImp::DlgCustomKeyboardImp (QWidget * parent = nullptr) explicit
Constructs a DlgCustomKeyboardImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'
The dialog will by default be modeless, unless you set 'modal' to true to construct a modal dialog.
Definition at line 80 of file DlgKeyboardImp.cpp.
References draftgeoutils.intersections::connect(), initCommandWidgets(), Gui::ShortcutManager::instance(), Gui::Application::Instance, setupConnections(), Gui::ShortcutManager::shortcutChanged(), and PersistentToolbarsGui::timer.
~DlgCustomKeyboardImp()
DlgCustomKeyboardImp::~DlgCustomKeyboardImp () override default
Destroys the object and frees any allocated resources
Member Function Documentation
changeEvent()
void DlgCustomKeyboardImp::changeEvent (QEvent * e) override protected virtual
Implements Gui::Dialog::CustomizeActionPage.
Definition at line 589 of file DlgKeyboardImp.cpp.
References Gui::Application::commandManager(), src.Mod.AddonManager.NetworkManager::count, SCL.SimpleDataTypes::e, Gui::CommandManager::getGroupCommands(), SplineSurface::i, and Gui::Application::Instance.
initCommandCompleter()
void DlgCustomKeyboardImp::initCommandCompleter (QLineEdit * edit, QComboBox * combo, QTreeWidget * treeWidget, QTreeWidgetItem * separatorItem) static protected
Definition at line 147 of file DlgKeyboardImp.cpp.
References Gui::CommandCompleter::commandActivated(), Gui::Application::commandManager(), draftgeoutils.intersections::connect(), Gui::CommandManager::getCommandByName(), Gui::Command::getGroupName(), toolbit-attributes::group, SplineSurface::i, Gui::Application::Instance, and populateCommandList().
Referenced by initCommandWidgets().
initCommandList()
boost::signals2::connection DlgCustomKeyboardImp::initCommandList (QTreeWidget * commandTreeWidget, QTreeWidgetItem * separatorItem, QComboBox * combo) static protected
Definition at line 229 of file DlgKeyboardImp.cpp.
References Gui::Application::commandManager(), draftgeoutils.intersections::connect(), Gui::ShortcutManager::instance(), Gui::Application::Instance, App::ExpressionParser::labels, populateCommandGroups(), populateCommandList(), Gui::ShortcutManager::shortcutChanged(), Gui::CommandManager::signalChanged, and PersistentToolbarsGui::timer.
Referenced by initCommandWidgets().
initCommandWidgets()
boost::signals2::connection DlgCustomKeyboardImp::initCommandWidgets (QTreeWidget * commandTreeWidget, QTreeWidgetItem * separatorItem, QComboBox * comboGroups, QLineEdit * editCommand, QTreeWidget * priorityList = nullptr, QAbstractButton * buttonUp = nullptr, QAbstractButton * buttonDown = nullptr, Gui::AccelLineEdit * editShortcut = nullptr, Gui::AccelLineEdit * currentShortcut = nullptr) static
Public helper function for handling command widgets
Parameters
commandTreeWidget a tree widget listing commands
separatorItem optional separator item
comboGroups a combo box widget for choosing categories of commands
editCommand a line edit for searching command with auto complete
priroityList a tree widget listing commands with the same shortcut in order of priority
buttonUp a button widget to increase command priority
buttonDown a button widget to decrease command priority
editShortcut an accelerator editor for setting user defined shortcut
currentShortcut optional accelerator editor showing the current shortcut of a command
Returns
Return a boost signal connection for monitoring command changes. Most disconnect the signal before widgets gets destroyed.
Definition at line 320 of file DlgKeyboardImp.cpp.
References draftgeoutils.intersections::connect(), initCommandCompleter(), initCommandList(), initPriorityList(), Gui::ShortcutManager::instance(), populatePriorityList(), Gui::ShortcutManager::priorityChanged(), and PersistentToolbarsGui::timer.
Referenced by DlgCustomKeyboardImp(), and Gui::Dialog::DlgCustomToolbars::DlgCustomToolbars().
initPriorityList()
void DlgCustomKeyboardImp::initPriorityList (QTreeWidget * priorityList, QAbstractButton * buttonUp, QAbstractButton * buttonDown) static protected
Definition at line 270 of file DlgKeyboardImp.cpp.
References draftgeoutils.intersections::connect(), SplineSurface::i, Gui::ShortcutManager::instance(), App::ExpressionParser::labels, and Gui::ShortcutManager::setPriorities().
Referenced by initCommandWidgets().
onAddMacroAction
void DlgCustomKeyboardImp::onAddMacroAction (const QByteArray &) override protected slot
Definition at line 574 of file DlgKeyboardImp.cpp.
onButtonAssignClicked()
void DlgCustomKeyboardImp::onButtonAssignClicked () protected
Assigns a new accelerator to the selected command.
Definition at line 517 of file DlgKeyboardImp.cpp.
References setShortcutOfCurrentAction().
Referenced by setupConnections().
onButtonClearClicked()
void DlgCustomKeyboardImp::onButtonClearClicked () protected
Clears the accelerator of the selected command.
Definition at line 523 of file DlgKeyboardImp.cpp.
References setShortcutOfCurrentAction().
Referenced by setupConnections().
onButtonResetAllClicked()
void DlgCustomKeyboardImp::onButtonResetAllClicked () protected
Resets the accelerator of all commands to the default.
Definition at line 546 of file DlgKeyboardImp.cpp.
References Gui::ShortcutManager::instance(), and Gui::ShortcutManager::resetAll().
Referenced by setupConnections().
onButtonResetClicked()
void DlgCustomKeyboardImp::onButtonResetClicked () protected
Resets the accelerator of the selected command to the default.
Definition at line 529 of file DlgKeyboardImp.cpp.
References Gui::ShortcutManager::getShortcut(), Gui::ShortcutManager::instance(), Gui::ShortcutManager::reset(), and create_qrc::txt.
Referenced by setupConnections().
onCategoryBoxActivated()
void DlgCustomKeyboardImp::onCategoryBoxActivated (int index) protected
Shows all commands of this category
Definition at line 481 of file DlgKeyboardImp.cpp.
Referenced by setupConnections().
onCommandTreeWidgetCurrentItemChanged()
void DlgCustomKeyboardImp::onCommandTreeWidgetCurrentItemChanged (QTreeWidgetItem * item) protected
Shows the description for the corresponding command
Definition at line 453 of file DlgKeyboardImp.cpp.
References Gui::Application::commandManager(), Gui::CommandBase::getAccel(), Gui::CommandManager::getCommandByName(), Gui::Command::getName(), Gui::ShortcutManager::getShortcut(), Gui::ShortcutManager::instance(), and Gui::Application::Instance.
Referenced by setupConnections().
onEditShortcutTextChanged()
void DlgCustomKeyboardImp::onEditShortcutTextChanged (const QString &) protected
Checks for an already occupied shortcut.
Definition at line 553 of file DlgKeyboardImp.cpp.
References Gui::Application::commandManager(), Gui::CommandBase::getAction(), Gui::CommandManager::getCommandByName(), Gui::Application::Instance, and Gui::Action::shortcut().
Referenced by setupConnections().
onModifyMacroAction
void DlgCustomKeyboardImp::onModifyMacroAction (const QByteArray &) override protected slot
Definition at line 580 of file DlgKeyboardImp.cpp.
References toolbit-attributes::group.
onRemoveMacroAction
void DlgCustomKeyboardImp::onRemoveMacroAction (const QByteArray &) override protected slot
Definition at line 577 of file DlgKeyboardImp.cpp.
populateCommandGroups()
void DlgCustomKeyboardImp::populateCommandGroups (QComboBox * combo) static protected
Definition at line 401 of file DlgKeyboardImp.cpp.
References Gui::Application::commandManager(), Gui::CommandManager::getCommands(), toolbit-attributes::group, and Gui::Application::Instance.
Referenced by initCommandList().
populateCommandList()
void DlgCustomKeyboardImp::populateCommandList (QTreeWidget * commandTreeWidget, QTreeWidgetItem * separatorItem, QComboBox * combo) static protected
Definition at line 182 of file DlgKeyboardImp.cpp.
References Gui::BitmapFactory(), Gui::Application::commandManager(), Gui::Action::commandMenuText(), Gui::Action::commandToolTip(), Gui::CommandManager::getAllCommands(), Gui::CommandManager::getGroupCommands(), toolbit-attributes::group, Gui::Application::Instance, and DraftVecUtils::toString().
Referenced by initCommandCompleter(), and initCommandList().
populatePriorityList()
void DlgCustomKeyboardImp::populatePriorityList (QTreeWidget * priorityList, Gui::AccelLineEdit * editor, Gui::AccelLineEdit * curShortcut) static protected
Definition at line 360 of file DlgKeyboardImp.cpp.
References Gui::Action::cleanTitle(), Path.Post.Utils::editor(), Gui::ShortcutManager::getActionsByShortcut(), Path.Log::info(), Gui::ShortcutManager::instance(), and Gui::AccelLineEdit::isNone().
Referenced by initCommandWidgets().
setShortcutOfCurrentAction()
void DlgCustomKeyboardImp::setShortcutOfCurrentAction (const QString & accelText) protected
Definition at line 489 of file DlgKeyboardImp.cpp.
References Gui::ShortcutManager::instance(), and Gui::ShortcutManager::setShortcut().
Referenced by onButtonAssignClicked(), and onButtonClearClicked().
setupConnections()
void DlgCustomKeyboardImp::setupConnections () protected
Definition at line 127 of file DlgKeyboardImp.cpp.
References draftgeoutils.intersections::connect(), onButtonAssignClicked(), onButtonClearClicked(), onButtonResetAllClicked(), onButtonResetClicked(), onCategoryBoxActivated(), onCommandTreeWidgetCurrentItemChanged(), and onEditShortcutTextChanged().
Referenced by DlgCustomKeyboardImp().
showEvent()
void DlgCustomKeyboardImp::showEvent (QShowEvent * e) override protected
Definition at line 441 of file DlgKeyboardImp.cpp.
References SCL.SimpleDataTypes::e.
The documentation for this class was generated from the following files:
DlgKeyboardImp.h
DlgKeyboardImp.cpp