FreeCAD: Spreadsheet::Cell Class Reference
Spreadsheet::Cell Class Reference
#include <Cell.h>
Public Member Functions
Cell (const App::CellAddress &_address, PropertySheet *_owner)
Cell (PropertySheet *_owner, const Cell &other)
Cell & operator= (const Cell &rhs)
~Cell ()
const App::Expression * getExpression (bool withFormat=false) const
bool getStringContent (std::string &s, bool persistent=false) const
void setContent (const char *value)
void setAlignment (int _alignment)
bool getAlignment (int &_alignment) const
void setStyle (const std::set< std::string > &_style)
bool getStyle (std::set< std::string > &style) const
void setForeground (const App::Color &color)
bool getForeground (App::Color &color) const
void setBackground (const App::Color &color)
bool getBackground (App::Color &color) const
void setDisplayUnit (const std::string &unit)
bool getDisplayUnit (DisplayUnit &unit) const
void setAlias (const std::string &n)
bool getAlias (std::string &n) const
void setComputedUnit (const Base::Unit &unit)
bool getComputedUnit (Base::Unit &unit) const
void setSpans (int rows, int columns)
bool getSpans (int &rows, int &columns) const
void setException (const std::string &e, bool silent=false)
void clearException ()
void clearDirty ()
void setDirty ()
void setResolveException (const std::string &e)
void clearResolveException ()
const std::string & getException () const
bool hasException () const
void moveAbsolute (App::CellAddress newAddress)
void restore (Base::XMLReader &reader, bool checkAlias=false)
void afterRestore ()
void save (Base::Writer &writer) const
void save (std::ostream &os, const char *indent, bool noContent) const
bool isUsed () const
void mark ()
bool isMarked () const
void visit (App::ExpressionVisitor &v)
App::CellAddress getAddress () const
std::string getFormattedQuantity ()
Static Public Member Functions
static int decodeAlignment (const std::string &itemStr, int alignment)
static std::string encodeAlignment (int alignment)
static std::string encodeStyle (const std::set< std::string > &style)
static std::string encodeColor (const App::Color &color)
static App::Color decodeColor (const std::string &color, const App::Color &defaultColor)
Static Public Attributes
static const int ALIGNMENT_LEFT = 0x01
static const int ALIGNMENT_HCENTER = 0x02
static const int ALIGNMENT_RIGHT = 0x04
static const int ALIGNMENT_HORIZONTAL = 0x0f
static const int ALIGNMENT_HIMPLIED = 0x08
static const int ALIGNMENT_TOP = 0x10
static const int ALIGNMENT_VCENTER = 0x20
static const int ALIGNMENT_BOTTOM = 0x40
static const int ALIGNMENT_VERTICAL = 0xf0
static const int ALIGNMENT_VIMPLIED = 0x80
Friends
class PropertySheet
Detailed Description
Definition at line 49 of file Cell.h.
Constructor & Destructor Documentation
Cell() [1/2]
Cell::Cell (const App::CellAddress & _address, PropertySheet * _owner)
Construct a CellContent object.
Parameters
_address The address of the cell (i.e. row and column)
_owner The spreadsheet that owns this cell.
Definition at line 110 of file Cell.cpp.
References App::CellAddress::isValid().
Cell() [2/2]
Cell::Cell (PropertySheet * _owner, const Cell & other)
Definition at line 128 of file Cell.cpp.
References setAlias(), and setDirty().
~Cell()
Cell::~Cell () default
Destroy a CellContent object.
Referenced by decodeAlignment().
Member Function Documentation
afterRestore()
void Cell::afterRestore ()
Definition at line 275 of file Cell.cpp.
References setContent().
clearDirty()
void Cell::clearDirty ()
Definition at line 704 of file Cell.cpp.
References Spreadsheet::PropertySheet::clearDirty().
clearException()
void Cell::clearException ()
Definition at line 696 of file Cell.cpp.
Referenced by setContent().
clearResolveException()
void Cell::clearResolveException ()
Definition at line 691 of file Cell.cpp.
decodeAlignment()
int Cell::decodeAlignment (const std::string & itemStr, int alignment) static
Decode alignment into its internal value.
Parameters
itemStr Alignment as a string
alignment Current alignment. This is or'ed with the one in itemStr.
Returns
New alignment.
Definition at line 925 of file Cell.cpp.
References ALIGNMENT_BOTTOM, ALIGNMENT_HCENTER, ALIGNMENT_HIMPLIED, ALIGNMENT_HORIZONTAL, ALIGNMENT_LEFT, ALIGNMENT_RIGHT, ALIGNMENT_TOP, ALIGNMENT_VCENTER, ALIGNMENT_VERTICAL, ALIGNMENT_VIMPLIED, and ~Cell().
Referenced by restore().
decodeColor()
App::Color Cell::decodeColor (const std::string & color, const App::Color & defaultColor) static
Decode a string of the format #rrggbb or #rrggbbaa into a Color.
Parameters
color The color to decode.
defaultColor A default color in case the decoding fails.
Returns
Decoded color.
Definition at line 1067 of file Cell.cpp.
References SCL.SimpleDataTypes::c.
Referenced by restore().
encodeAlignment()
std::string Cell::encodeAlignment (int alignment) static
Encode internal alignment value as a string.
Parameters
alignment Alignment as a binary value.
Returns
Alignment represented as a string.
Definition at line 973 of file Cell.cpp.
References ALIGNMENT_BOTTOM, ALIGNMENT_HCENTER, ALIGNMENT_HIMPLIED, ALIGNMENT_LEFT, ALIGNMENT_RIGHT, ALIGNMENT_TOP, ALIGNMENT_VCENTER, ALIGNMENT_VERTICAL, ALIGNMENT_VIMPLIED, and toolbit-attributes::s.
Referenced by save().
encodeColor()
std::string Cell::encodeColor (const App::Color & color) static
Encode color as a #rrggbbaa string.
Parameters
color Color to encode.
Returns
String with encoded color.
Definition at line 1019 of file Cell.cpp.
References App::Color::a, App::Color::b, App::Color::g, and App::Color::r.
Referenced by save().
encodeStyle()
std::string Cell::encodeStyle (const std::set< std::string > & style) static
Encode set of styles as a string.
Parameters
style Set of string describing the style.
Returns
Set encoded as a string.
Definition at line 1040 of file Cell.cpp.
References toolbit-attributes::s.
Referenced by save().
getAddress()
App::CellAddress Spreadsheet::Cell::getAddress () const inline
Definition at line 139 of file Cell.h.
Referenced by Spreadsheet::Sheet::getAddressFromAlias(), Spreadsheet::PropertySheet::getCellAddress(), and getFormattedQuantity().
getAlias()
bool Cell::getAlias (std::string & n) const
Definition at line 598 of file Cell.cpp.
References isUsed().
Referenced by SpreadsheetGui::SheetModel::data(), SpreadsheetGui::PropertiesDialog::PropertiesDialog(), Spreadsheet::PropertySheet::setAlias(), and Spreadsheet::PropertySheet::setPathValue().
getAlignment()
bool Cell::getAlignment (int & _alignment) const
Get alignment.
Definition at line 430 of file Cell.cpp.
References isUsed().
Referenced by SpreadsheetGui::SheetModel::data(), Drawing::FeatureViewSpreadsheet::execute(), TechDraw::DrawViewSpreadsheet::getSheetImage(), and SpreadsheetGui::PropertiesDialog::PropertiesDialog().
getBackground()
bool Cell::getBackground (App::Color & color) const
Get the background color of the cell into color.
Returns
true if the background color was previously set.
Definition at line 519 of file Cell.cpp.
References isUsed().
Referenced by SpreadsheetGui::SheetModel::data(), Drawing::FeatureViewSpreadsheet::execute(), TechDraw::DrawViewSpreadsheet::getSheetImage(), and SpreadsheetGui::PropertiesDialog::PropertiesDialog().
getComputedUnit()
bool Cell::getComputedUnit (Base::Unit & unit) const
Get the computed unit into unit.
Returns
true if the computed unit was previously set.
Definition at line 627 of file Cell.cpp.
References isUsed(), and unit().
getDisplayUnit()
bool Cell::getDisplayUnit (DisplayUnit & unit) const
Get the display unit for the cell into unit.
Returns
true if the display unit was previously set.
Definition at line 561 of file Cell.cpp.
References isUsed(), and unit().
Referenced by SpreadsheetGui::SheetModel::data(), getFormattedQuantity(), and SpreadsheetGui::PropertiesDialog::PropertiesDialog().
getException()
const std::string& Spreadsheet::Cell::getException () const inline
Definition at line 105 of file Cell.h.
Referenced by SpreadsheetGui::SheetModel::data().
getExpression()
const App::Expression * Cell::getExpression (bool withFormat = false) const
Get the expression tree.
Definition at line 227 of file Cell.cpp.
References save().
Referenced by SpreadsheetGui::SheetModel::data(), SpreadsheetGui::DlgSheetConf::prepare(), Spreadsheet::PropertySheet::setPathValue(), and Spreadsheet::Sheet::updateProperty().
getForeground()
bool Cell::getForeground (App::Color & color) const
Get foreground color of the cell.
Definition at line 488 of file Cell.cpp.
References isUsed().
Referenced by SpreadsheetGui::SheetModel::data(), Drawing::FeatureViewSpreadsheet::execute(), TechDraw::DrawViewSpreadsheet::getSheetImage(), and SpreadsheetGui::PropertiesDialog::PropertiesDialog().
getFormattedQuantity()
std::string Cell::getFormattedQuantity ()
Definition at line 1090 of file Cell.cpp.
References getAddress(), Base::Persistence::getClassTypeId(), Base::UnitsApi::getDecimals(), getDisplayUnit(), Spreadsheet::Sheet::getPropertyByName(), App::PropertyQuantity::getUnit(), getValue(), App::PropertyString::getValue(), Base::BaseClass::isDerivedFrom(), Base::Unit::isEmpty(), Spreadsheet::DisplayUnit::scaler, Spreadsheet::PropertySheet::sheet(), Spreadsheet::DisplayUnit::stringRep, App::CellAddress::toString(), and Spreadsheet::DisplayUnit::unit.
Referenced by TechDraw::DrawViewSpreadsheet::getSheetImage().
getSpans()
bool Cell::getSpans (int & rows, int & columns) const
Get the row and column spans for the cell into rows and columns.
Definition at line 657 of file Cell.cpp.
References isUsed().
Referenced by Drawing::FeatureViewSpreadsheet::execute(), TechDraw::DrawViewSpreadsheet::getSheetImage(), Spreadsheet::PropertySheet::getSpans(), Spreadsheet::PropertySheet::mergeCells(), Spreadsheet::PropertySheet::Paste(), Spreadsheet::PropertySheet::removeColumns(), Spreadsheet::PropertySheet::removeRows(), Spreadsheet::PropertySheet::Restore(), and Spreadsheet::PropertySheet::splitCell().
getStringContent()
bool Cell::getStringContent (std::string & s, bool persistent = false) const
Get string content.
Definition at line 246 of file Cell.cpp.
References importers.exportIFC::getText(), and toolbit-attributes::s.
Referenced by SpreadsheetGui::SheetModel::data(), Assembly::BomObject::getText(), Spreadsheet::Sheet::recomputeCell(), save(), SpreadsheetGui::SheetModel::setData(), and Spreadsheet::Sheet::updateProperty().
getStyle()
bool Cell::getStyle (std::set< std::string > & _style) const
Get the style of the cell.
Definition at line 459 of file Cell.cpp.
References isUsed().
Referenced by SpreadsheetGui::SheetModel::data(), Drawing::FeatureViewSpreadsheet::execute(), TechDraw::DrawViewSpreadsheet::getSheetImage(), and SpreadsheetGui::PropertiesDialog::PropertiesDialog().
hasException()
bool Spreadsheet::Cell::hasException () const inline
Definition at line 110 of file Cell.h.
Referenced by SpreadsheetGui::SheetModel::data(), and Spreadsheet::Sheet::recomputeCell().
isMarked()
bool Spreadsheet::Cell::isMarked () const inline
Definition at line 132 of file Cell.h.
Referenced by Spreadsheet::PropertySheet::Paste().
isUsed()
bool Cell::isUsed () const
Determine if the any of the contents of the cell is set a non-default value.
Definition at line 903 of file Cell.cpp.
Referenced by SpreadsheetGui::SheetTableView::finishEditWithMove(), getAlias(), getAlignment(), getBackground(), getComputedUnit(), getDisplayUnit(), getForeground(), getSpans(), getStyle(), and save().
mark()
void Spreadsheet::Cell::mark () inline
Definition at line 127 of file Cell.h.
moveAbsolute()
void Cell::moveAbsolute (App::CellAddress newAddress)
Move the cell to a new position given by _row and _col.
Definition at line 723 of file Cell.cpp.
operator=()
Cell & Cell::operator= (const Cell & rhs)
Definition at line 147 of file Cell.cpp.
References Spreadsheet::PropertySheet::AtomicPropertyChange, setAlias(), setAlignment(), setBackground(), setComputedUnit(), setDirty(), setDisplayUnit(), setForeground(), setSpans(), setStyle(), and Spreadsheet::DisplayUnit::stringRep.
restore()
void Cell::restore (Base::XMLReader & reader, bool checkAlias = false)
Restore cell contents from reader.
Definition at line 733 of file Cell.cpp.
References Spreadsheet::PropertySheet::AtomicPropertyChange, decodeAlignment(), decodeColor(), SCL.SimpleDataTypes::e, SplineSurface::i, TechDrawTools.TaskFillTemplateFields::reader, setAlias(), setAlignment(), setBackground(), setContent(), setDisplayUnit(), setForeground(), setSpans(), and setStyle().
Referenced by Spreadsheet::PropertySheet::Restore().
save() [1/2]
void Cell::save (Base::Writer & writer) const
Save cell contents into writer.
Definition at line 815 of file Cell.cpp.
References Base::Writer::ind(), and Base::Writer::Stream().
Referenced by getExpression().
save() [2/2]
void Cell::save (std::ostream & os, const char * indent, bool noContent) const
Definition at line 820 of file Cell.cpp.
References encodeAlignment(), Base::Persistence::encodeAttribute(), encodeColor(), encodeStyle(), getStringContent(), indent, isUsed(), Spreadsheet::DisplayUnit::stringRep, and App::CellAddress::toString().
setAlias()
void Cell::setAlias (const std::string & n)
Definition at line 567 of file Cell.cpp.
References Spreadsheet::PropertySheet::AtomicPropertyChange, App::Property::getContainer(), App::DocumentObject::removeDynamicProperty(), and setDirty().
Referenced by Cell(), operator=(), restore(), and Spreadsheet::PropertySheet::setAlias().
setAlignment()
void Cell::setAlignment (int _alignment)
Set alignment of this cell. Alignment is the or'ed value of vertical and horizontal alignment, given by the constants defined in the class.
Definition at line 410 of file Cell.cpp.
References ALIGNMENT_HIMPLIED, ALIGNMENT_LEFT, ALIGNMENT_VCENTER, ALIGNMENT_VIMPLIED, Spreadsheet::PropertySheet::AtomicPropertyChange, and setDirty().
Referenced by operator=(), restore(), and Spreadsheet::PropertySheet::setAlignment().
setBackground()
void Cell::setBackground (const App::Color & color)
Set background color of the cell to color.
Definition at line 499 of file Cell.cpp.
References Spreadsheet::PropertySheet::AtomicPropertyChange, and setDirty().
Referenced by operator=(), restore(), and Spreadsheet::PropertySheet::setBackground().
setComputedUnit()
void Cell::setComputedUnit (const Base::Unit & unit)
Set the computed unit for the cell to unit.
Definition at line 609 of file Cell.cpp.
References Spreadsheet::PropertySheet::AtomicPropertyChange, Base::Unit::isEmpty(), setDirty(), and unit().
Referenced by operator=(), and Spreadsheet::PropertySheet::setComputedUnit().
setContent()
void Cell::setContent (const char * value)
Definition at line 283 of file Cell.cpp.
References Spreadsheet::PropertySheet::AtomicPropertyChange, clearException(), SCL.SimpleDataTypes::e, App::DocumentObject::isRestoring(), Path.Post.scripts.opensbp_post::move(), App::ExpressionParser::parse(), Spreadsheet::PropertySheet::sheet(), and UNIT.
Referenced by afterRestore(), Spreadsheet::Sheet::recomputeCell(), restore(), and Spreadsheet::PropertySheet::setContent().
setDirty()
void Cell::setDirty ()
Definition at line 711 of file Cell.cpp.
References Spreadsheet::PropertySheet::setDirty().
Referenced by Cell(), Path.Op.Gui.FeatureExtension.TaskPanelExtensionPage::extensionsClear(), operator=(), setAlias(), setAlignment(), setBackground(), setComputedUnit(), setDisplayUnit(), Path.Op.Gui.ThreadMilling.TaskPanelOpPage::setFields(), setForeground(), setSpans(), setStyle(), Path.Op.Gui.FeatureExtension.TaskPanelExtensionPage::toggleExtensionCorners(), and Path.Op.Gui.FeatureExtension.TaskPanelExtensionPage::updateItemEnabled().
setDisplayUnit()
void Cell::setDisplayUnit (const std::string & unit)
Set the display unit for the cell.
Definition at line 530 of file Cell.cpp.
References Spreadsheet::PropertySheet::AtomicPropertyChange, SCL.SimpleDataTypes::e, Spreadsheet::DisplayUnit::isEmpty(), App::ExpressionParser::parseUnit(), setDirty(), Spreadsheet::PropertySheet::sheet(), and unit().
Referenced by operator=(), restore(), and Spreadsheet::PropertySheet::setDisplayUnit().
setException()
void Cell::setException (const std::string & e, bool silent = false)
Definition at line 664 of file Cell.cpp.
References SCL.SimpleDataTypes::e, FC_ERR, App::DocumentObject::getFullName(), Spreadsheet::PropertySheet::sheet(), Base::silent, and App::CellAddress::toString().
Referenced by Spreadsheet::Sheet::execute(), and Spreadsheet::Sheet::recomputeCell().
setForeground()
void Cell::setForeground (const App::Color & color)
Set foreground (i.e text) color of the cell to color.
Definition at line 470 of file Cell.cpp.
References Spreadsheet::PropertySheet::AtomicPropertyChange, and setDirty().
Referenced by operator=(), restore(), and Spreadsheet::PropertySheet::setForeground().
setResolveException()
void Cell::setResolveException (const std::string & e)
Definition at line 682 of file Cell.cpp.
References SCL.SimpleDataTypes::e, FC_LOG, App::DocumentObject::getFullName(), Spreadsheet::PropertySheet::sheet(), and App::CellAddress::toString().
Referenced by Spreadsheet::PropertySheet::invalidateDependants().
setSpans()
void Cell::setSpans (int rows, int columns)
Set the cell's row and column span to rows and columns. This is done when cells are merged.
Definition at line 639 of file Cell.cpp.
References Spreadsheet::PropertySheet::AtomicPropertyChange, and setDirty().
Referenced by operator=(), restore(), and Spreadsheet::PropertySheet::setSpans().
setStyle()
void Cell::setStyle (const std::set< std::string > & _style)
Set style to the given set _style.
Definition at line 441 of file Cell.cpp.
References Spreadsheet::PropertySheet::AtomicPropertyChange, and setDirty().
Referenced by operator=(), restore(), and Spreadsheet::PropertySheet::setStyle().
visit()
void Cell::visit (App::ExpressionVisitor & v)
Definition at line 908 of file Cell.cpp.
References TestSpreadsheet::v.
Referenced by Spreadsheet::PropertySheet::insertColumns(), Spreadsheet::PropertySheet::insertRows(), Spreadsheet::PropertySheet::removeColumns(), and Spreadsheet::PropertySheet::removeRows().
Friends And Related Function Documentation
PropertySheet
friend class PropertySheet friend
Definition at line 211 of file Cell.h.
Member Data Documentation
ALIGNMENT_BOTTOM
const int Cell::ALIGNMENT_BOTTOM = 0x40 static
Definition at line 154 of file Cell.h.
Referenced by decodeAlignment(), and encodeAlignment().
ALIGNMENT_HCENTER
const int Cell::ALIGNMENT_HCENTER = 0x02 static
Definition at line 148 of file Cell.h.
Referenced by decodeAlignment(), encodeAlignment(), Drawing::FeatureViewSpreadsheet::execute(), and TechDraw::DrawViewSpreadsheet::getSheetImage().
ALIGNMENT_HIMPLIED
const int Cell::ALIGNMENT_HIMPLIED = 0x08 static
Definition at line 151 of file Cell.h.
Referenced by decodeAlignment(), encodeAlignment(), and setAlignment().
ALIGNMENT_HORIZONTAL
const int Cell::ALIGNMENT_HORIZONTAL = 0x0f static
Definition at line 150 of file Cell.h.
Referenced by decodeAlignment().
ALIGNMENT_LEFT
const int Cell::ALIGNMENT_LEFT = 0x01 static
Definition at line 147 of file Cell.h.
Referenced by decodeAlignment(), encodeAlignment(), Drawing::FeatureViewSpreadsheet::execute(), TechDraw::DrawViewSpreadsheet::getSheetImage(), and setAlignment().
ALIGNMENT_RIGHT
const int Cell::ALIGNMENT_RIGHT = 0x04 static
Definition at line 149 of file Cell.h.
Referenced by decodeAlignment(), encodeAlignment(), Drawing::FeatureViewSpreadsheet::execute(), and TechDraw::DrawViewSpreadsheet::getSheetImage().
ALIGNMENT_TOP
const int Cell::ALIGNMENT_TOP = 0x10 static
Definition at line 152 of file Cell.h.
Referenced by decodeAlignment(), and encodeAlignment().
ALIGNMENT_VCENTER
const int Cell::ALIGNMENT_VCENTER = 0x20 static
Definition at line 153 of file Cell.h.
Referenced by decodeAlignment(), encodeAlignment(), and setAlignment().
ALIGNMENT_VERTICAL
const int Cell::ALIGNMENT_VERTICAL = 0xf0 static
Definition at line 155 of file Cell.h.
Referenced by decodeAlignment(), and encodeAlignment().
ALIGNMENT_VIMPLIED
const int Cell::ALIGNMENT_VIMPLIED = 0x80 static
Definition at line 156 of file Cell.h.
Referenced by decodeAlignment(), encodeAlignment(), and setAlignment().
The documentation for this class was generated from the following files:
Cell.h
Cell.cpp