FreeCAD: PathGui::ViewProviderPath Class Reference
PathGui::ViewProviderPath Class Reference
#include <ViewProviderPath.h>
Public Member Functions
ViewProviderPath ()
constructor.
~ViewProviderPath () override
destructor.
void attach (App::DocumentObject *pcObject) override
void setDisplayMode (const char *ModeName) override
set the display mode
std::vector< std::string > getDisplayModes () const override
returns a list of all possible display modes
void updateData (const App::Property *) override
void recomputeBoundingBox ()
QIcon getIcon () const override
deliver the icon shown in the tree view
bool useNewSelectionModel () const override
indicates if the ViewProvider use the new Selection model
std::string getElement (const SoDetail *) const override
return a hit element to the selection path or 0
SoDetail * getDetail (const char *subelement) const override
return the coin node detail of the subelement
void updateShowConstraints ()
void updateVisual (bool rebuild=false)
void hideSelection ()
void showBoundingBox (bool show) override
Public Member Functions inherited from Gui::ViewProviderGeometryObject
ViewProviderGeometryObject ()
constructor.
~ViewProviderGeometryObject () override
destructor.
bool isSelectable () const override
SoPickedPointList getPickedPoints (const SbVec2s &pos, const View3DInventorViewer &viewer, bool pickAll=false) const
SoPickedPoint * getPickedPoint (const SbVec2s &pos, const View3DInventorViewer &viewer) const
PyObject * getPyObject () override
Get the python wrapper for that ViewProvider.
Public Member Functions inherited from Gui::ViewProviderDragger
ViewProviderDragger ()
constructor.
~ViewProviderDragger () override
destructor.
Base::Placement getTransformOrigin () const
Convenience method to obtain the transform origin.
void setTransformOrigin (const Base::Placement &placement)
Convenience method to set the transform origin.
void resetTransformOrigin ()
Resets transform origin to the object origin.
bool doubleClicked () override
is called by the tree if the user double clicks on the object
void setupContextMenu (QMenu *, QObject *, const char *) override
set up the context-menu with the supported edit modes
ViewProvider * startEditing (int ModNum=0) override
void updatePlacementFromDragger ()
updates placement of object based on dragger position
void updateTransformFromDragger ()
updates transform of object based on dragger position, can be used to preview movement
Base::Placement getObjectPlacement () const
Gets object placement relative to its coordinate system.
Base::Placement getDraggerPlacement () const
Gets current dragger placement, including current dragger movement.
Base::Placement getOriginalDraggerPlacement () const
Gets original dragger placement, without current dragger movement.
void setDraggerPlacement (const Base::Placement &placement)
Sets placement of dragger relative to objects origin.
Public Member Functions inherited from Gui::ViewProviderDocumentObject
ViewProviderDocumentObject ()
constructor.
~ViewProviderDocumentObject () override
destructor.
virtual void reattach (App::DocumentObject *)
void update (const App::Property *) override
void setActiveMode ()
Set the active mode, i.e. the first item of the 'Display' property.
void hide () override
Hide the object in the view.
void show () override
Show the object in the view.
const char * getTransactionText () const override
bool canDropObjectEx (App::DocumentObject *, App::DocumentObject *, const char *, const std::vector< std::string > &) const override
int replaceObject (App::DocumentObject *, App::DocumentObject *) override
bool showInTree () const override
void getTaskViewContent (std::vector< Gui::TaskView::TaskContent * > &) const override
Get a list of TaskBoxes associated with this object.
void updateView ()
Run a redraw.
App::DocumentObject * getObject () const
Get the object of this ViewProvider object.
template<class T >
T * getObject () const
Get the object of this ViewProvider object as specified type.
bool canDelete (App::DocumentObject *obj) const override
Asks the view provider if the given object can be deleted.
virtual bool acceptDeletionsInEdit ()
Ask the view provider if it accepts object deletions while in edit.
Gui::Document * getDocument () const
Get the GUI document to this ViewProvider object.
bool getElementPicked (const SoPickedPoint *, std::string &subname) const override
return a hit element given the picked point which contains the full node path
bool getDetailPath (const char *subname, SoFullPath *pPath, bool append, SoDetail *&det) const override
return the coin node detail and path to the node of the subname
virtual void forceUpdate (bool enable=true)
virtual bool isUpdateForced () const
virtual void startRestoring ()
virtual void finishRestoring ()
int getTreeRank () const
void setTreeRank (int value)
bool removeDynamicProperty (const char *prop) override
App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false) override
virtual ViewProviderDocumentObject * getLinkedViewProvider (std::string *subname=nullptr, bool recursive=false) const
std::string getFullName () const override
virtual bool allowOverride (const App::DocumentObject &) const
void setShowable (bool enable)
bool isShowable () const
void startDefaultEditMode ()
Public Member Functions inherited from Gui::ViewProvider
ViewProvider ()
constructor.
~ViewProvider () override
destructor.
virtual SoSeparator * getRoot () const
SoSwitch * getModeSwitch () const
SoTransform * getTransformNode () const
SoSeparator * getAnnotation ()
virtual SoSeparator * getFrontRoot () const
virtual SoGroup * getChildRoot () const
virtual SoSeparator * getBackRoot () const
virtual bool canAddToSceneGraph () const
Indicate whether to be added to scene graph or not.
virtual bool isPartOfPhysicalObject () const
virtual std::vector< App::DocumentObject * > claimChildren3D () const
int partialRender (const std::vector< std::string > &subelements, bool clear)
virtual std::vector< Base::Vector3d > getModelPoints (const SoPickedPoint *) const
virtual std::vector< Base::Vector3d > getSelectionShape (const char *Element) const
return the highlight lines for a given element or the whole shape
Base::BoundBox3d getBoundingBox (const char *subname=nullptr, bool transform=true, MDIView *view=nullptr) const
virtual bool onDelete (const std::vector< std::string > &subNames)
virtual void beforeDelete ()
virtual bool canDragObjects () const
virtual bool canDragObject (App::DocumentObject *) const
virtual bool canDragObjectToTarget (App::DocumentObject *obj, App::DocumentObject *target) const
virtual void dragObject (App::DocumentObject *)
virtual bool canDropObjects () const
virtual bool canDropObject (App::DocumentObject *) const
virtual bool canDragAndDropObject (App::DocumentObject *) const
virtual void dropObject (App::DocumentObject *)
virtual bool acceptReorderingObjects () const
virtual std::string getDropPrefix () const
return a subname referencing the sub-object holding the dropped objects
virtual std::string dropObjectEx (App::DocumentObject *obj, App::DocumentObject *owner, const char *subname, const std::vector< std::string > &elements)
virtual bool canRemoveChildrenFromRoot () const
std::string getActiveDisplayMode () const
virtual const char * getDefaultDisplayMode () const
get the default display mode
virtual bool isShow () const
checks whether the view provider is visible or not
void setVisible (bool)
bool isVisible () const
void setLinkVisible (bool)
bool isLinkVisible () const
virtual void setOverrideMode (const std::string &mode)
Overrides the display mode with mode.
const std::string getOverrideMode ()
virtual bool selectAll ()
virtual bool keyPressed (bool pressed, int key)
is called when the provider is in edit and a key event occurs. Only ESC ends edit.
virtual bool mouseMove (const SbVec2s &cursorPos, View3DInventorViewer *viewer)
is called when the provider is in edit and the mouse is moved
virtual bool mouseButtonPressed (int button, bool pressed, const SbVec2s &cursorPos, const View3DInventorViewer *viewer)
is called when the Provider is in edit and the mouse is clicked
virtual bool mouseWheelEvent (int delta, const SbVec2s &cursorPos, const View3DInventorViewer *viewer)
virtual QIcon mergeColorfulOverlayIcons (const QIcon &orig) const
virtual std::vector< App::DocumentObject * > claimChildren () const
virtual std::vector< App::DocumentObject * > claimChildrenRecursive () const
bool isUpdatesEnabled () const
void setUpdatesEnabled (bool enable)
unsigned long getStatus () const
return the status bits
bool testStatus (ViewStatus pos) const
void setStatus (ViewStatus pos, bool on)
std::string toString () const
virtual std::map< std::string, App::Color > getElementColors (const char *element=nullptr) const
virtual void setElementColors (const std::map< std::string, App::Color > &colors)
bool isEditing () const
void finishEditing ()
virtual void setTransformation (const Base::Matrix4D &rcMatrix)
set the viewing transformation of the provider
virtual void setTransformation (const SbMatrix &rcMatrix)
virtual MDIView * getMDIView () const
void Restore (Base::XMLReader &reader) override
bool isRestoring ()
void addDisplayMaskMode (SoNode *node, const char *type)
Adds a new display mask mode.
void setDisplayMaskMode (const char *type)
Activates the display mask mode type.
SoNode * getDisplayMaskMode (const char *type) const
Get the node to the display mask mode type.
std::vector< std::string > getDisplayMaskModes () const
Returns a list of added display mask modes.
void setDefaultMode (int)
int getDefaultMode () const
virtual void setRenderCacheMode (int)
Public Member Functions inherited from App::TransactionalObject
TransactionalObject ()
Constructor.
~TransactionalObject () override
Public Member Functions inherited from App::ExtensionContainer
ExtensionContainer ()
~ExtensionContainer () override
void registerExtension (Base::Type extension, App::Extension *ext)
bool hasExtension (Base::Type, bool derived=true) const
bool hasExtension (const std::string &name) const
bool hasExtensions () const
App::Extension * getExtension (Base::Type, bool derived=true, bool no_except=false) const
App::Extension * getExtension (const std::string &name) const
template<typename ExtensionT >
ExtensionT * getExtension () const
template<typename ExtensionT >
ExtensionT * getExtensionByType (bool no_except=false, bool derived=true) const
std::vector< Extension * > getExtensionsDerivedFrom (Base::Type type) const
template<typename ExtensionT >
std::vector< ExtensionT * > getExtensionsDerivedFromType () const
ExtensionIterator extensionBegin ()
ExtensionIterator extensionEnd ()
Property * getPropertyByName (const char *name) const override
find a property by its name
template<typename T >
T * getPropertyByName (const char *name) const
find a property by its name, dynamic cased to specified type
const char * getPropertyName (const Property *prop) const override
get the name of a property
void getPropertyMap (std::map< std::string, Property * > &Map) const override
get all properties of the class (including properties of the parent)
void getPropertyList (std::vector< Property * > &List) const override
get all properties of the class (including properties of the parent)
short getPropertyType (const Property *prop) const override
get the Type of a Property
short getPropertyType (const char *name) const override
get the Type of a named Property
const char * getPropertyGroup (const Property *prop) const override
get the Group of a Property
const char * getPropertyGroup (const char *name) const override
get the Group of a named Property
const char * getPropertyDocumentation (const Property *prop) const override
get the Group of a Property
const char * getPropertyDocumentation (const char *name) const override
get the Group of a named Property
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
void saveExtensions (Base::Writer &writer) const
void restoreExtensions (Base::XMLReader &reader)
void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName) override
void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop) override
Public Member Functions inherited from App::PropertyContainer
PropertyContainer ()
~PropertyContainer () override
unsigned int getMemSize () const override
virtual void getPropertyNamedList (std::vector< std::pair< const char *, Property * > > &List) const
get all properties with their names, may contain duplicates and aliases
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
bool isReadOnly (const Property *prop) const
check if the property is read-only
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isHidden (const Property *prop) const
check if the property is hidden
bool isHidden (const char *name) const
check if the named property is hidden
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
bool changeDynamicProperty (const Property *prop, const char *group, const char *doc)
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual App::Property * getDynamicPropertyByName (const char *name) const
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
virtual void beforeSave () const
virtual void editProperty (const char *)
const char * getPropertyPrefix () const
void setPropertyPrefix (const char *prefix)
PropertyContainer (const PropertyContainer &)=delete
PropertyContainer & operator= (const PropertyContainer &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Attributes
App::PropertyInteger LineWidth
App::PropertyColor NormalColor
App::PropertyColor MarkerColor
App::PropertyBool ShowNodes
App::PropertyVector StartPosition
App::PropertyIntegerConstraint StartIndex
App::PropertyIntegerConstraint::Constraints StartIndexConstraints
App::PropertyIntegerConstraint ShowCount
App::PropertyIntegerConstraint::Constraints ShowCountConstraints
Public Attributes inherited from Gui::ViewProviderGeometryObject
App::PropertyPercent Transparency
App::PropertyMaterialList ShapeAppearance
App::PropertyBool BoundingBox
App::PropertyBool Selectable
Public Attributes inherited from Gui::ViewProviderDragger
App::PropertyPlacement TransformOrigin
Public Attributes inherited from Gui::ViewProviderDocumentObject
App::PropertyEnumeration DisplayMode
App::PropertyBool Visibility
App::PropertyBool ShowInTree
App::PropertyEnumeration OnTopWhenSelected
App::PropertyEnumeration SelectionStyle
Public Attributes inherited from Gui::ViewProvider
boost::signals2::signal< void()> signalChangeIcon
signal on icon change
boost::signals2::signal< void(const QString &)> signalChangeToolTip
signal on tooltip change
boost::signals2::signal< void(const QString &)> signalChangeStatusTip
signal on status tip change
boost::signals2::signal< void(bool, Gui::HighlightMode)> signalChangeHighlight
signal on highlight change
Protected Member Functions
void onChanged (const App::Property *prop) override
get called by the container whenever a property has been changed
unsigned long getBoundColor () const override
Protected Member Functions inherited from Gui::ViewProviderGeometryObject
void setSelectable (bool Selectable=true)
void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName) override
PropertyContainer::handleChangedPropertyName is called during restore to possibly fix reading of older versions of this property container. This method is typically called if the property on file has changed its name in more recent versions.
void setCoinAppearance (const App::Material &source)
Protected Member Functions inherited from Gui::ViewProviderDragger
bool setEdit (int ModNum) override
is called by the document when the provider goes in edit mode
void unsetEdit (int ModNum) override
is called when you lose the edit mode
void setEditViewer (View3DInventorViewer *, int ModNum) override
adjust viewer settings when editing a view provider
void unsetEditViewer (View3DInventorViewer *) override
restores viewer settings when leaving editing mode
bool forwardToLink ()
virtual TaskView::TaskDialog * getTransformDialog ()
Protected Member Functions inherited from Gui::ViewProviderDocumentObject
Gui::MDIView * getActiveView () const
Gui::MDIView * getEditingView () const
Gui::MDIView * getInventorView () const
Gui::MDIView * getViewOfNode (SoNode *node) const
void onBeforeChange (const App::Property *prop) override
get called before the value is changed
SoNode * findFrontRootOfType (const SoType &type) const
bool isAttachedToDocument () const override
const char * detachFromDocument () override
void onPropertyStatusChanged (const App::Property &prop, unsigned long oldStatus) override
get called when a property status has changed
void setModeSwitch () override
Turn on mode switch.
void addDefaultAction (QMenu *, const QString &)
Protected Member Functions inherited from Gui::ViewProvider
virtual QIcon mergeGreyableOverlayIcons (const QIcon &orig) const
int getEditingMode () const
return the edit mode or -1 if nothing is being edited
bool checkRecursion (SoNode *)
SoPickedPoint * getPointOnRay (const SbVec2s &pos, const View3DInventorViewer *viewer) const
SoPickedPoint * getPointOnRay (const SbVec3f &pos, const SbVec3f &dir, const View3DInventorViewer *viewer) const
Protected Member Functions inherited from App::TransactionalObject
void onBeforeChangeProperty (Document *doc, const Property *prop)
Protected Member Functions inherited from App::PropertyContainer
virtual void onEarlyChange (const Property *)
virtual const PropertyData & getPropertyData () const
Protected Attributes
SoCoordinate3 * pcLineCoords
SoCoordinate3 * pcMarkerCoords
SoDrawStyle * pcDrawStyle
SoDrawStyle * pcMarkerStyle
PartGui::SoBrepEdgeSet * pcLines
SoMaterial * pcLineColor
SoBaseColor * pcMarkerColor
SoMaterialBinding * pcMatBind
std::vector< int > colorindex
SoSwitch * pcMarkerSwitch
SoSwitch * pcArrowSwitch
SoTransform * pcArrowTransform
std::vector< int > command2Edge
std::deque< int > edge2Command
std::deque< int > edgeIndices
int pt0Index
bool blockPropertyChange
int edgeStart
int coordStart
int coordEnd
Protected Attributes inherited from Gui::ViewProviderGeometryObject
SoMaterial * pcShapeMaterial {nullptr}
SoFCBoundingBox * pcBoundingBox {nullptr}
SoSwitch * pcBoundSwitch {nullptr}
SoBaseColor * pcBoundColor {nullptr}
SoPickStyle * pickStyle {nullptr}
App::Material materialAppearance
Protected Attributes inherited from Gui::ViewProviderDragger
CoinPtr< SoFCCSysDragger > csysDragger = nullptr
ViewProvider * forwardedViewProvider = nullptr
Protected Attributes inherited from Gui::ViewProviderDocumentObject
App::DocumentObject * pcObject {nullptr}
Gui::Document * pcDocument {nullptr}
Protected Attributes inherited from Gui::ViewProvider
SoSeparator * pcRoot
The root Separator of the ViewProvider.
SoTransform * pcTransform
this is transformation for the provider
const char * sPixmap
SoSwitch * pcModeSwitch
this is the mode switch, all the different viewing modes are collected here
SoSeparator * pcAnnotation {nullptr}
The root separator for annotations.
ViewProviderPy * pyViewObject {nullptr}
std::string overrideMode
std::bitset< 32 > StatusBits
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Friends
class PathSelectionObserver
Additional Inherited Members
Public Types inherited from Gui::ViewProvider
enum EditMode { Default = 0, Transform, Cutting, Color }
Public Types inherited from App::ExtensionContainer
using ExtensionIterator = std::map< Base::Type, App::Extension * >::iterator
Static Public Member Functions inherited from Gui::ViewProviderDragger
static void updateTransform (const Base::Placement &from, SoTransform *to)
Static Public Member Functions inherited from Gui::ViewProvider
static const std::string & hiddenMarker ()
static const char * hasHiddenMarker (const char *subname)
static SbMatrix convert (const Base::Matrix4D &rcMatrix)
static Base::Matrix4D convert (const SbMatrix &sbMat)
static void eventCallback (void *ud, SoEventCallback *node)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 47 of file ViewProviderPath.h.
Constructor & Destructor Documentation
ViewProviderPath()
ViewProviderPath::ViewProviderPath ()
constructor.
Definition at line 145 of file ViewProviderPath.cpp.
References ADD_PROPERTY_TYPE, App::GetApplication(), ParameterGrp::GetInt(), App::Application::GetParameterGroupByPath(), ParameterGrp::GetUnsigned(), SIM::Coin3D::Quarter::Quarter::init(), MeshCore::MeshIO::OVERALL, and App::Prop_None.
~ViewProviderPath()
ViewProviderPath::~ViewProviderPath () override
destructor.
Definition at line 277 of file ViewProviderPath.cpp.
Member Function Documentation
attach()
void ViewProviderPath::attach (App::DocumentObject * pcObject) override virtual
Attaches the document object to this view provider.
Reimplemented from Gui::ViewProviderGeometryObject.
Definition at line 291 of file ViewProviderPath.cpp.
Referenced by Path.Dressup.Gui.Boundary.DressupPathBoundaryViewProvider::__init__().
getBoundColor()
unsigned long ViewProviderPath::getBoundColor () const override protected virtual
Reimplemented from Gui::ViewProviderGeometryObject.
Definition at line 473 of file ViewProviderPath.cpp.
References App::GetApplication(), App::Application::GetParameterGroupByPath(), and ParameterGrp::GetUnsigned().
getDetail()
SoDetail * ViewProviderPath::getDetail (const char *) const override virtual
return the coin node detail of the subelement
Reimplemented from Gui::ViewProvider.
Definition at line 365 of file ViewProviderPath.cpp.
getDisplayModes()
std::vector< std::string > ViewProviderPath::getDisplayModes () const override virtual
returns a list of all possible display modes
Reimplemented from Gui::ViewProvider.
Definition at line 333 of file ViewProviderPath.cpp.
getElement()
std::string ViewProviderPath::getElement (const SoDetail *) const override virtual
return a hit element to the selection path or 0
Reimplemented from Gui::ViewProvider.
Definition at line 340 of file ViewProviderPath.cpp.
References Path::Toolpath::getCommand(), Path::Toolpath::getSize(), Path::PropertyPath::getValue(), Path::Feature::Path, Path.Post.scripts.refactored_centroid_post::str, and Path::Command::toGCode().
getIcon()
QIcon ViewProviderPath::getIcon () const override virtual
deliver the icon shown in the tree view
Reimplemented from Gui::ViewProvider.
Reimplemented in PathGui::ViewProviderPathShape, and PathGui::ViewProviderPathCompound.
Definition at line 831 of file ViewProviderPath.cpp.
References Gui::BitmapFactory(), and Gui::BitmapFactoryInst::pixmap().
hideSelection()
void ViewProviderPath::hideSelection ()
Definition at line 518 of file ViewProviderPath.cpp.
References Gui::SoSelectionElementAction::None.
onChanged()
void ViewProviderPath::onChanged (const App::Property * prop) override protected virtual
get called by the container whenever a property has been changed
Reimplemented from Gui::ViewProviderGeometryObject.
Definition at line 379 of file ViewProviderPath.cpp.
References SCL.SimpleDataTypes::c, importers.importIFCmulticore::colors, src.Mod.AddonManager.NetworkManager::count, App::GetApplication(), App::Application::GetParameterGroupByPath(), ParameterGrp::GetUnsigned(), ArchFence::hide(), SplineSurface::i, bimcommands.BimViews::show(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by draftviewproviders.view_base.ViewProviderDraft::attach(), draftviewproviders.view_wpproxy.ViewProviderWorkingPlaneProxy::updateData(), draftviewproviders.view_layer.ViewProviderLayer::updateData(), draftviewproviders.view_label.ViewProviderLabel::updateData(), and draftviewproviders.view_dimension.ViewProviderLinearDimension::updateData().
recomputeBoundingBox()
void ViewProviderPath::recomputeBoundingBox ()
Definition at line 790 of file ViewProviderPath.cpp.
References App::PropertyPlacement::getValue(), SplineSurface::i, Base::Placement::multVec(), App::GeoFeature::Placement, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
setDisplayMode()
void ViewProviderPath::setDisplayMode (const char * ModeName) override virtual
set the display mode
If you add new viewing modes in getDisplayModes() then you need to reimplement also seDisplaytMode() to handle these new modes by setting the appropriate display mode.
Reimplemented from Gui::ViewProvider.
Definition at line 325 of file ViewProviderPath.cpp.
showBoundingBox()
void ViewProviderPath::showBoundingBox (bool show) override virtual
Reimplemented from Gui::ViewProviderGeometryObject.
Definition at line 463 of file ViewProviderPath.cpp.
References bimcommands.BimViews::show().
updateData()
void ViewProviderPath::updateData (const App::Property * prop) override virtual
Reimplemented from Gui::ViewProviderGeometryObject.
Reimplemented in PathGui::ViewProviderPathShape.
Definition at line 508 of file ViewProviderPath.cpp.
References Path::Feature::Path.
Referenced by Path.Main.Gui.JobDlg.JobCreate::exec_(), draftviewproviders.view_wire.ViewProviderWire::onChanged(), draftviewproviders.view_dimension.ViewProviderLinearDimension::onChanged(), draftviewproviders.view_dimension.ViewProviderAngularDimension::onChanged(), Path.Op.Gui.Base.TaskPanelPage::pageUpdateData(), Path.Base.Gui.SetupSheet.OpTaskPanel::setupUi(), Path.Base.Gui.PropertyBag.TaskPanel::setupUi(), and PathGui::ViewProviderPathShape::updateData().
updateShowConstraints()
void ViewProviderPath::updateShowConstraints ()
Definition at line 485 of file ViewProviderPath.cpp.
References Path::Toolpath::getSize(), Path::PropertyPath::getValue(), OpenSCADFeatures::long, and Path::Feature::Path.
updateVisual()
void ViewProviderPath::updateVisual (bool rebuild = false)
Definition at line 693 of file ViewProviderPath.cpp.
References src.Mod.AddonManager.NetworkManager::count, SCL.SimpleDataTypes::e, Path::PropertyPath::getValue(), SplineSurface::i, Path::Feature::Path, segments, MovieTool::x, and MovieTool::y.
useNewSelectionModel()
bool ViewProviderPath::useNewSelectionModel () const override virtual
indicates if the ViewProvider use the new Selection model
Reimplemented from Gui::ViewProvider.
Definition at line 320 of file ViewProviderPath.cpp.
Friends And Related Function Documentation
PathSelectionObserver
friend class PathSelectionObserver friend
Definition at line 88 of file ViewProviderPath.h.
Member Data Documentation
blockPropertyChange
bool PathGui::ViewProviderPath::blockPropertyChange protected
Definition at line 112 of file ViewProviderPath.h.
colorindex
std::vector<int> PathGui::ViewProviderPath::colorindex protected
Definition at line 102 of file ViewProviderPath.h.
command2Edge
std::vector<int> PathGui::ViewProviderPath::command2Edge protected
Definition at line 107 of file ViewProviderPath.h.
coordEnd
int PathGui::ViewProviderPath::coordEnd protected
Definition at line 115 of file ViewProviderPath.h.
coordStart
int PathGui::ViewProviderPath::coordStart protected
Definition at line 114 of file ViewProviderPath.h.
edge2Command
std::deque<int> PathGui::ViewProviderPath::edge2Command protected
Definition at line 108 of file ViewProviderPath.h.
edgeIndices
std::deque<int> PathGui::ViewProviderPath::edgeIndices protected
Definition at line 109 of file ViewProviderPath.h.
edgeStart
int PathGui::ViewProviderPath::edgeStart protected
Definition at line 113 of file ViewProviderPath.h.
LineWidth
App::PropertyInteger PathGui::ViewProviderPath::LineWidth
Definition at line 60 of file ViewProviderPath.h.
MarkerColor
App::PropertyColor PathGui::ViewProviderPath::MarkerColor
Definition at line 62 of file ViewProviderPath.h.
NormalColor
App::PropertyColor PathGui::ViewProviderPath::NormalColor
Definition at line 61 of file ViewProviderPath.h.
pcArrowSwitch
SoSwitch* PathGui::ViewProviderPath::pcArrowSwitch protected
Definition at line 104 of file ViewProviderPath.h.
pcArrowTransform
SoTransform* PathGui::ViewProviderPath::pcArrowTransform protected
Definition at line 105 of file ViewProviderPath.h.
pcDrawStyle
SoDrawStyle* PathGui::ViewProviderPath::pcDrawStyle protected
Definition at line 96 of file ViewProviderPath.h.
pcLineColor
SoMaterial* PathGui::ViewProviderPath::pcLineColor protected
Definition at line 99 of file ViewProviderPath.h.
pcLineCoords
SoCoordinate3* PathGui::ViewProviderPath::pcLineCoords protected
Definition at line 94 of file ViewProviderPath.h.
pcLines
PartGui::SoBrepEdgeSet* PathGui::ViewProviderPath::pcLines protected
Definition at line 98 of file ViewProviderPath.h.
pcMarkerColor
SoBaseColor* PathGui::ViewProviderPath::pcMarkerColor protected
Definition at line 100 of file ViewProviderPath.h.
pcMarkerCoords
SoCoordinate3* PathGui::ViewProviderPath::pcMarkerCoords protected
Definition at line 95 of file ViewProviderPath.h.
pcMarkerStyle
SoDrawStyle* PathGui::ViewProviderPath::pcMarkerStyle protected
Definition at line 97 of file ViewProviderPath.h.
pcMarkerSwitch
SoSwitch* PathGui::ViewProviderPath::pcMarkerSwitch protected
Definition at line 103 of file ViewProviderPath.h.
pcMatBind
SoMaterialBinding* PathGui::ViewProviderPath::pcMatBind protected
Definition at line 101 of file ViewProviderPath.h.
pt0Index
int PathGui::ViewProviderPath::pt0Index mutable protected
Definition at line 111 of file ViewProviderPath.h.
ShowCount
App::PropertyIntegerConstraint PathGui::ViewProviderPath::ShowCount
Definition at line 68 of file ViewProviderPath.h.
ShowCountConstraints
App::PropertyIntegerConstraint::Constraints PathGui::ViewProviderPath::ShowCountConstraints
Definition at line 69 of file ViewProviderPath.h.
ShowNodes
App::PropertyBool PathGui::ViewProviderPath::ShowNodes
Definition at line 63 of file ViewProviderPath.h.
StartIndex
App::PropertyIntegerConstraint PathGui::ViewProviderPath::StartIndex
Definition at line 66 of file ViewProviderPath.h.
StartIndexConstraints
App::PropertyIntegerConstraint::Constraints PathGui::ViewProviderPath::StartIndexConstraints
Definition at line 67 of file ViewProviderPath.h.
StartPosition
App::PropertyVector PathGui::ViewProviderPath::StartPosition
Definition at line 64 of file ViewProviderPath.h.
The documentation for this class was generated from the following files:
ViewProviderPath.h
ViewProviderPath.cpp