FreeCAD: ifc4.ifcreldeclares Class Reference
ifc4.ifcreldeclares Class Reference
Public Member Functions
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, relatingcontext, relateddefinitions)
def relatingcontext ()
def relateddefinitions ()
def noselfreference (self)
Public Member Functions inherited from ifc4.ifcrelationship
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description)
Public Member Functions inherited from ifc4.ifcroot
def globalid ()
def ownerhistory ()
def name ()
def description ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
relatingcontext
relateddefinitions
Public Attributes inherited from ifc4.ifcroot
globalid
ownerhistory
name
description
Detailed Description
Entity ifcreldeclares definition.
:param relatingcontext
:type relatingcontext:ifccontext
:param relateddefinitions
:type relateddefinitions:SET(1,None,'ifcdefinitionselect', scope = schema_scope)
Definition at line 37708 of file ifc4.py.
Constructor & Destructor Documentation
__init__()
def ifc4.ifcreldeclares.__init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, relatingcontext, relateddefinitions)
Definition at line 37717 of file ifc4.py.
Member Function Documentation
noselfreference()
def ifc4.ifcreldeclares.noselfreference (self)
Definition at line 37749 of file ifc4.py.
References SCL.Builtin.SIZEOF().
relateddefinitions()
def ifc4.ifcreldeclares.relateddefinitions ()
Definition at line 37737 of file ifc4.py.
References ifc4.ifcreldeclares._relateddefinitions, SCL.TypeChecker.check_type(), and ifc4.ifcreldeclares.relateddefinitions.
relatingcontext()
def ifc4.ifcreldeclares.relatingcontext ()
Definition at line 37723 of file ifc4.py.
References ifc4.ifcreldeclares._relatingcontext, SCL.TypeChecker.check_type(), and ifc4.ifcreldeclares.relatingcontext.
Member Data Documentation
relateddefinitions
ifc4.ifcreldeclares.relateddefinitions
Definition at line 37720 of file ifc4.py.
Referenced by ifc4.ifcreldeclares.relateddefinitions().
relatingcontext
ifc4.ifcreldeclares.relatingcontext
Definition at line 37719 of file ifc4.py.
Referenced by ifc4.ifcreldeclares.relatingcontext().
The documentation for this class was generated from the following file:
ifc4.py