FreeCAD: geoff_geometry::Kurve Class Reference
geoff_geometry::Kurve Class Reference
#include <geometry.h>
Classes
struct spanCompare
Public Member Functions
Kurve ()
Kurve (const Kurve &k0)
const Kurve & operator= (const Kurve &k)
const Kurve & operator= (const Matrix &m)
bool operator== (const Kurve &k) const
bool operator!= (const Kurve &k) const
~Kurve ()
int nSpans () const
bool Closed () const
bool Started () const
void FullCircle (int dir, const Point &c, double radius)
void Start ()
void Start (const Point &p)
bool Add (const spVertex &spv, bool AddNullSpans=true)
void Get (int vertex, spVertex &spv) const
bool Add (const Span &sp, bool AddNullSpans=true)
bool Add (int type, const Point &p0, const Point &pc, bool AddNullSpans=true)
void AddSpanID (int ID)
bool Add (const Point &p0, bool AddNullSpans=true)
void Add ()
void Add (const Kurve *k, bool AddNullSpans=true)
void StoreAllSpans (std::vector< Span > &kSpans) const
void Clear ()
void Replace (int vertexnumber, const spVertex &spv)
void Replace (int vertexnumber, int type, const Point &p, const Point &pc, int ID=UNMARKED)
int GetSpanID (int spanVertexNumber) const
int Get (int spanVertexNumber, Point &p, Point &pc) const
void Get (std::vector< Span > *all, bool ignoreNullSpans) const
int Get (int spanVertexNumber, Point3d &p, Point3d &pc) const
int Get (int spannumber, Span &sp, bool returnSpanProperties=false, bool transform=false) const
void Get (Point &ps, Point &pe) const
const SpanDataObject * GetIndex (int vertexNumber) const
double GetLength () const
void minmax (Point &pmin, Point &pmax)
void minmax (Box &b)
Point NearToVertex (const Point &p, int &nearSpanNumber) const
Point NearToVertex (const Point &p) const
Point Near (const Point &p, int &nearSpanNumber) const
Point Near (const Point &p) const
double Perim () const
double Area () const
void Reverse ()
bool Reverse (bool isReversed)
int Reduce (double tolerance)
int Offset (vector< Kurve * > &OffsetKurves, double offset, int direction, int method, int &ret) const
int OffsetMethod1 (Kurve &kOffset, double off, int direction, int method, int &ret) const
int OffsetISOMethod (Kurve &kOffset, double off, int direction, bool BlendAll) const
int Intof (const Span &sp, vector< Point > &p) const
int Intof (const Kurve &k, vector< Point > &p) const
bool Compare (const Kurve *k, Matrix *m, bool bAllowMirror=true) const
void ChangeStart (const Point *pNewStart, int startSpanno)
void ChangeEnd (const Point *pNewEnd, int endSpanno)
void AddIndex (int vertexNumber, const SpanDataObject *data)
bool Split (double MaximumRadius, double reslution)
int IntExtWire (Kurve &kSec, double Ref, double Sec, double height, Kurve *kOut)
void SetZ (double z)
void Part (int startVertex, int EndVertex, Kurve *part)
Kurve Part (int fromSpanno, const Point &fromPt, int toSpanno, const Point &toPt)
int Break (double atParam, const Kurve *secInput, Kurve *refOut, Kurve *secOut)
void Part (double fromParam, double toParam, const Kurve *secInput, Kurve *refOut, Kurve *secOut)
Kurve Part (double fromParam, double toParam)
void AddSections (const Kurve *k, bool endOfSection)
void AddEllipse (int dir, const Point &pStart, const Point &pEnd, const Point &pCentre, const Vector2d &majorAxis, double majorRadius, double minorRadius, double tolerance)
void Spiral (const Point &centre, double startAngle, double startRadius, double radiusRisePerRevolution, double endRadius)
Public Member Functions inherited from geoff_geometry::Matrix
Matrix ()
Matrix (double m[16])
~Matrix ()
bool operator== (const Matrix &m) const
bool operator!= (const Matrix &m) const
void Unit ()
void Get (double *p) const
void Put (double *p)
void Translate (double x, double y, double z=0)
void Rotate (double sinang, double cosang, Vector3d *rotAxis)
void Rotate (double angle, Vector3d *rotAxis)
void Rotate (double sinang, double cosang, int Axis)
void Rotate (double angle, int Axis)
void Scale (double scale)
void Scale (double scalex, double scaley, double scalez)
void Multiply (Matrix &m)
void Transform (double p0[3]) const
void Transform (double p0[3], double p1[3]) const
void Transform2d (double p0[2], double p1[2]) const
int IsMirrored ()
int IsUnit ()
void GetTranslate (double &x, double &y, double &z) const
void GetScale (double &sx, double &sy, double &sz) const
bool GetScale (double &sx) const
void GetRotation (double &ax, double &ay, double &az) const
Matrix Inverse ()
Protected Attributes
vector< SpanVertex * > m_spans
bool m_started
int m_nVertices
bool m_isReversed
Friends
wofstream & operator<< (wofstream &op, Kurve &k)
wifstream & operator>> (wifstream &op, Kurve &k)
Additional Inherited Members
Public Attributes inherited from geoff_geometry::Matrix
double e [16]
bool m_unit
int m_mirrored
Detailed Description
Definition at line 1357 of file geometry.h.
Constructor & Destructor Documentation
Kurve() [1/2]
geoff_geometry::Kurve::Kurve () inline
Definition at line 1378 of file geometry.h.
Referenced by Offset().
Kurve() [2/2]
geoff_geometry::Kurve::Kurve (const Kurve & k0)
copy constructor
Definition at line 472 of file kurve.cpp.
References geoff_geometry::Matrix::e, SplineSurface::i, m_isReversed, geoff_geometry::Matrix::m_mirrored, m_nVertices, m_spans, m_started, and geoff_geometry::Matrix::m_unit.
~Kurve()
geoff_geometry::Kurve::~Kurve ()
Definition at line 570 of file kurve.cpp.
References Clear().
Member Function Documentation
Add() [1/6]
void geoff_geometry::Kurve::Add ()
Definition at line 688 of file kurve.cpp.
References geoff_geometry::FAILURE(), Get(), m_nVertices, and buildPsets::p.
Referenced by Add(), FullCircle(), and Start().
Add() [2/6]
void geoff_geometry::Kurve::Add (const Kurve * k, bool AddNullSpans = true)
Definition at line 705 of file kurve.cpp.
References Add(), AddIndex(), geoff_geometry::Span::dir, geoff_geometry::Point::Dist(), Get(), GetIndex(), SplineSurface::i, geoff_geometry::Matrix::Inverse(), test::m, geoff_geometry::Matrix::m_unit, geoff_geometry::Matrix::Multiply(), nSpans(), geoff_geometry::Span::p0, geoff_geometry::Span::p1, geoff_geometry::Span::pc, geoff_geometry::TOLERANCE, and geoff_geometry::Span::Transform().
Add() [3/6]
bool geoff_geometry::Kurve::Add (const Point & p0, bool AddNullSpans = true)
Definition at line 699 of file kurve.cpp.
References Add().
Add() [4/6]
bool geoff_geometry::Kurve::Add (const Span & sp, bool AddNullSpans = true)
Definition at line 620 of file kurve.cpp.
References Add(), AddSpanID(), geoff_geometry::Span::dir, geoff_geometry::Span::ID, m_started, geoff_geometry::Span::p0, geoff_geometry::Span::p1, geoff_geometry::Span::pc, and Start().
Add() [5/6]
bool geoff_geometry::Kurve::Add (const spVertex & spv, bool AddNullSpans = true)
Definition at line 633 of file kurve.cpp.
References Add(), AddSpanID(), geoff_geometry::spVertex::p, geoff_geometry::spVertex::pc, geoff_geometry::spVertex::spanid, and geoff_geometry::spVertex::type.
Referenced by ChangeEnd(), ChangeStart(), geoff_geometry::eliminateLoops(), MakeKurve(), OffsetISOMethod(), OffsetMethod1(), Part(), Reduce(), and Split().
Add() [6/6]
bool geoff_geometry::Kurve::Add (int type, const Point & p0, const Point & pc, bool AddNullSpans = true)
Definition at line 642 of file kurve.cpp.
References geoff_geometry::Point::Dist(), Get(), LINEAR, m_nVertices, m_spans, m_started, buildPsets::p, SPANSTORAGE, Start(), and geoff_geometry::TOLERANCE.
AddEllipse()
void geoff_geometry::Kurve::AddEllipse (int dir, const Point & pStart, const Point & pEnd, const Point & pCentre, const Vector2d & majorAxis, double majorRadius, double minorRadius, double tolerance)
AddIndex()
void geoff_geometry::Kurve::AddIndex (int vertexNumber, const SpanDataObject * data)
Definition at line 787 of file kurve.cpp.
References geoff_geometry::FAILURE(), m_nVertices, m_spans, buildPsets::p, and SPANSTORAGE.
Referenced by Add().
AddSections()
void geoff_geometry::Kurve::AddSections (const Kurve * k, bool endOfSection)
AddSpanID()
void geoff_geometry::Kurve::AddSpanID (int ID)
Definition at line 680 of file kurve.cpp.
References m_nVertices, m_spans, buildPsets::p, and SPANSTORAGE.
Referenced by Add(), geoff_geometry::eliminateLoops(), FullCircle(), and OffsetMethod1().
Area()
double geoff_geometry::Kurve::Area () const
Definition at line 1272 of file kurve.cpp.
References geoff_geometry::Span::angle, Closed(), geoff_geometry::FAILURE(), Get(), geoff_geometry::getMessage(), geoff_geometry::Matrix::GetScale(), SplineSurface::i, m_nVertices, geoff_geometry::Span::p0, geoff_geometry::Span::p1, geoff_geometry::Span::pc, geoff_geometry::Span::radius, geoff_geometry::Point::x, and geoff_geometry::Point::y.
Referenced by OffsetMethod1().
Break()
int geoff_geometry::Kurve::Break (double atParam, const Kurve * secInput, Kurve * refOut, Kurve * secOut)
ChangeEnd()
void geoff_geometry::Kurve::ChangeEnd (const Point * pNewEnd, int endSpanno)
Definition at line 1148 of file kurve.cpp.
References Add(), geoff_geometry::Span::dir, Get(), nSpans(), geoff_geometry::Span::p0, geoff_geometry::Span::p1, geoff_geometry::Span::pc, and Start().
ChangeStart()
void geoff_geometry::Kurve::ChangeStart (const Point * pNewStart, int startSpanno)
Definition at line 1098 of file kurve.cpp.
References Add(), Closed(), geoff_geometry::Span::dir, Get(), nSpans(), geoff_geometry::Span::p0, geoff_geometry::Span::p1, geoff_geometry::Span::pc, and Start().
Clear()
void geoff_geometry::Kurve::Clear ()
Definition at line 1225 of file kurve.cpp.
References m_isReversed, m_nVertices, m_spans, and m_started.
Referenced by FullCircle(), operator=(), Start(), and ~Kurve().
Closed()
bool geoff_geometry::Kurve::Closed () const
Definition at line 576 of file kurve.cpp.
References Get(), and m_nVertices.
Referenced by Area(), ChangeStart(), OffsetMethod1(), and Part().
Compare()
bool geoff_geometry::Kurve::Compare (const Kurve * k, Matrix * m, bool bAllowMirror = true) const
FullCircle()
void geoff_geometry::Kurve::FullCircle (int dir, const Point & c, double radius)
make a full circle Kurve (2 spans) mark the first span for later
Definition at line 590 of file kurve.cpp.
References Add(), AddSpanID(), SCL.SimpleDataTypes::c, Clear(), geoff_geometry::FULL_CIRCLE_KURVE, Start(), and geoff_geometry::Point::x.
Get() [1/6]
int geoff_geometry::Kurve::Get (int spannumber, Span & sp, bool returnSpanProperties = false, bool transform = false) const
Definition at line 865 of file kurve.cpp.
References geoff_geometry::Span::dir, geoff_geometry::FAILURE(), Get(), geoff_geometry::getMessage(), GetSpanID(), geoff_geometry::Span::ID, test::m, m_isReversed, m_nVertices, m_spans, geoff_geometry::Matrix::m_unit, geoff_geometry::Point::ok, buildPsets::p, geoff_geometry::Span::p0, geoff_geometry::Span::p1, geoff_geometry::Span::pc, geoff_geometry::Span::SetProperties(), SPANSTORAGE, geoff_geometry::Span::Transform(), geoff_geometry::Point::x, and geoff_geometry::Point::y.
Get() [2/6]
int geoff_geometry::Kurve::Get (int spanVertexNumber, Point & p, Point & pc) const
Definition at line 826 of file kurve.cpp.
References geoff_geometry::FAILURE(), geoff_geometry::getMessage(), LINEAR, m_isReversed, m_nVertices, m_spans, buildPsets::p, and SPANSTORAGE.
Get() [3/6]
int geoff_geometry::Kurve::Get (int spanVertexNumber, Point3d & p, Point3d & pc) const inline
Definition at line 1428 of file geometry.h.
References buildPsets::p.
Get() [4/6]
void geoff_geometry::Kurve::Get (int vertex, spVertex & spv) const
Definition at line 820 of file kurve.cpp.
References GetSpanID(), geoff_geometry::spVertex::p, geoff_geometry::spVertex::pc, geoff_geometry::spVertex::spanid, and geoff_geometry::spVertex::type.
Referenced by Add(), Area(), ChangeEnd(), ChangeStart(), Closed(), geoff_geometry::DoesIntersInterfere(), geoff_geometry::eliminateLoops(), Get(), Intof(), MakeCCurve(), minmax(), Near(), NearToVertex(), OffsetISOMethod(), OffsetMethod1(), operator==(), Part(), Perim(), Reduce(), Reverse(), Split(), and StoreAllSpans().
Get() [5/6]
void geoff_geometry::Kurve::Get (Point & ps, Point & pe) const
Definition at line 924 of file kurve.cpp.
References Get(), m_nVertices, geoff_geometry::Span::p0, and geoff_geometry::Span::p1.
Get() [6/6]
void geoff_geometry::Kurve::Get (std::vector< Span > * all, bool ignoreNullSpans) const
put all spans to vector
Definition at line 807 of file kurve.cpp.
References Get(), SplineSurface::i, nSpans(), and geoff_geometry::Span::NullSpan.
GetIndex()
const SpanDataObject * geoff_geometry::Kurve::GetIndex (int vertexNumber) const
Definition at line 796 of file kurve.cpp.
References geoff_geometry::FAILURE(), m_nVertices, m_spans, buildPsets::p, and SPANSTORAGE.
Referenced by Add().
GetLength()
double geoff_geometry::Kurve::GetLength () const inline
Definition at line 1444 of file geometry.h.
GetSpanID()
int geoff_geometry::Kurve::GetSpanID (int spanVertexNumber) const
Definition at line 853 of file kurve.cpp.
References geoff_geometry::FAILURE(), geoff_geometry::getMessage(), m_isReversed, m_nVertices, m_spans, buildPsets::p, and SPANSTORAGE.
Referenced by geoff_geometry::eliminateLoops(), Get(), and Reverse().
IntExtWire()
int geoff_geometry::Kurve::IntExtWire (Kurve & kSec, double Ref, double Sec, double height, Kurve * kOut)
Intof() [1/2]
int geoff_geometry::Kurve::Intof (const Kurve & k, vector< Point > & p) const
Definition at line 1354 of file kurve.cpp.
References geoff_geometry::Dist(), Get(), SplineSurface::i, Intof(), nSpans(), buildPsets::p, and geoff_geometry::TOLERANCE.
Intof() [2/2]
int geoff_geometry::Kurve::Intof (const Span & sp, vector< Point > & p) const
Definition at line 1301 of file kurve.cpp.
References geoff_geometry::bubblesort(), Get(), SplineSurface::i, geoff_geometry::Span::Intof(), geoff_geometry::Span::length, nSpans(), buildPsets::p, geoff_geometry::Span::p1, geoff_geometry::Span::SetProperties(), and InitGui::t.
Referenced by Intof().
minmax() [1/2]
void geoff_geometry::Kurve::minmax (Box & b)
Definition at line 1211 of file kurve.cpp.
References SCL.SimpleDataTypes::b, and minmax().
minmax() [2/2]
void geoff_geometry::Kurve::minmax (Point & pmin, Point & pmax)
Definition at line 1190 of file kurve.cpp.
References geoff_geometry::FAILURE(), Get(), geoff_geometry::getMessage(), geoff_geometry::Matrix::GetScale(), SplineSurface::i, m_nVertices, KDL::max(), KDL::min(), geoff_geometry::MinMax(), geoff_geometry::Span::minmax(), and geoff_geometry::Span::p0.
Referenced by minmax().
Near() [1/2]
Point geoff_geometry::Kurve::Near (const Point & p) const inline
Definition at line 1459 of file geometry.h.
References geoff_geometry::Near(), and buildPsets::p.
Near() [2/2]
Point geoff_geometry::Kurve::Near (const Point & p, int & nearSpanNumber) const
Definition at line 1044 of file kurve.cpp.
References geoff_geometry::Point::Dist(), Get(), SplineSurface::i, geoff_geometry::Span::NearOn(), nSpans(), buildPsets::p, and geoff_geometry::TOLERANCE.
Referenced by Part().
NearToVertex() [1/2]
Point geoff_geometry::Kurve::NearToVertex (const Point & p) const inline
Definition at line 1453 of file geometry.h.
References buildPsets::p.
NearToVertex() [2/2]
Point geoff_geometry::Kurve::NearToVertex (const Point & p, int & nearSpanNumber) const
Definition at line 1069 of file kurve.cpp.
References Get(), SplineSurface::i, geoff_geometry::Matrix::Inverse(), m_nVertices, geoff_geometry::Matrix::m_unit, buildPsets::p, and geoff_geometry::Point::Transform().
nSpans()
int geoff_geometry::Kurve::nSpans () const inline
Definition at line 1399 of file geometry.h.
Referenced by Add(), ChangeEnd(), ChangeStart(), geoff_geometry::DoesIntersInterfere(), geoff_geometry::eliminateLoops(), Get(), Intof(), MakeCCurve(), Near(), OffsetISOMethod(), OffsetMethod1(), operator==(), Part(), Reduce(), and StoreAllSpans().
Offset()
int geoff_geometry::Kurve::Offset (vector< Kurve * > & OffsetKurves, double offset, int direction, int method, int & ret) const
Definition at line 17 of file offset.cpp.
References geoff_geometry::BASIC_OFFSET, geoff_geometry::FAILURE(), Kurve(), geoff_geometry::NO_ELIMINATION, and OffsetMethod1().
OffsetISOMethod()
int Kurve::OffsetISOMethod (Kurve & kOffset, double off, int direction, bool BlendAll) const
Definition at line 327 of file offset.cpp.
References Add(), geoff_geometry::Matrix::e, geoff_geometry::FEQZ(), GEOFF_LEFT, Get(), SplineSurface::i, isodata, isoRadius(), geoff_geometry::Span::JoinSeparateSpans(), nSpans(), iso::off, geoff_geometry::Span::Offset(), iso::sp, and Start().
OffsetMethod1()
int geoff_geometry::Kurve::OffsetMethod1 (Kurve & kOffset, double off, int direction, int method, int & ret) const
Definition at line 39 of file offset.cpp.
References a, Add(), AddSpanID(), Area(), Closed(), geoff_geometry::Span::dir, geoff_geometry::Point::Dist(), geoff_geometry::eliminateLoops(), geoff_geometry::FAILURE(), GEOFF_LEFT, GEOFF_RIGHT, Get(), geoff_geometry::Matrix::GetScale(), geoff_geometry::Span::ID, geoff_geometry::Span::Intof(), geoff_geometry::Matrix::m_mirrored, m_nVertices, m_started, geoff_geometry::Matrix::Matrix(), geoff_geometry::NO_ELIMINATION, nSpans(), geoff_geometry::Span::NullSpan, geoff_geometry::Span::Offset(), geoff_geometry::Span::p0, geoff_geometry::Span::p1, geoff_geometry::Span::pc, Replace(), geoff_geometry::ROLL_AROUND, Start(), InitGui::t, geoff_geometry::TOLERANCE, geoff_geometry::Span::ve, and geoff_geometry::Span::vs.
Referenced by CCurve::Offset(), and Offset().
operator!=()
bool geoff_geometry::Kurve::operator!= (const Kurve & k) const inline
Definition at line 1389 of file geometry.h.
operator=() [1/2]
const Kurve & geoff_geometry::Kurve::operator= (const Kurve & k)
Definition at line 489 of file kurve.cpp.
References Clear(), geoff_geometry::Matrix::e, SplineSurface::i, m_isReversed, geoff_geometry::Matrix::m_mirrored, m_nVertices, m_spans, m_started, and geoff_geometry::Matrix::m_unit.
operator=() [2/2]
const Kurve & geoff_geometry::Kurve::operator= (const Matrix & m)
Definition at line 557 of file kurve.cpp.
References geoff_geometry::Matrix::e, SplineSurface::i, test::m, geoff_geometry::Matrix::m_mirrored, and geoff_geometry::Matrix::m_unit.
operator==()
bool geoff_geometry::Kurve::operator== (const Kurve & k) const
Definition at line 1237 of file kurve.cpp.
References Get(), SplineSurface::i, and nSpans().
Part() [1/4]
Kurve geoff_geometry::Kurve::Part (double fromParam, double toParam)
return a part Kurve - perimeter parameterisation fromParam & toParam 0 - 1 perimeter parameter
Definition at line 1639 of file kurve.cpp.
References Add(), geoff_geometry::FEQ(), Get(), SplineSurface::i, geoff_geometry::Span::length, m_started, geoff_geometry::Span::MidPerim(), nSpans(), geoff_geometry::Span::p0, geoff_geometry::Span::p1, Perim(), and Start().
Part() [2/4]
void geoff_geometry::Kurve::Part (double fromParam, double toParam, const Kurve * secInput, Kurve * refOut, Kurve * secOut)
Part() [3/4]
Kurve geoff_geometry::Kurve::Part (int fromSpanno, const Point & fromPt, int toSpanno, const Point & toPt)
Definition at line 1576 of file kurve.cpp.
References Add(), Closed(), geoff_geometry::Span::dir, Get(), SplineSurface::i, Near(), nSpans(), geoff_geometry::Span::p0, geoff_geometry::Span::p1, geoff_geometry::Span::pc, and Start().
Part() [4/4]
void geoff_geometry::Kurve::Part (int startVertex, int EndVertex, Kurve * part)
Definition at line 1564 of file kurve.cpp.
References Add(), Get(), and SplineSurface::i.
Perim()
double geoff_geometry::Kurve::Perim () const
Definition at line 1254 of file kurve.cpp.
References geoff_geometry::Span::angle, geoff_geometry::FAILURE(), Get(), geoff_geometry::getMessage(), geoff_geometry::Matrix::GetScale(), SplineSurface::i, geoff_geometry::Span::length, m_nVertices, and geoff_geometry::Span::radius.
Referenced by Part().
Reduce()
int geoff_geometry::Kurve::Reduce (double tolerance)
Definition at line 1497 of file kurve.cpp.
References Add(), geoff_geometry::CLine::Dist(), Get(), SplineSurface::i, m_nVertices, geoff_geometry::Matrix::Matrix(), nSpans(), geoff_geometry::CLine::ok, Start(), and draftutils.utils::tolerance().
Replace() [1/2]
void geoff_geometry::Kurve::Replace (int vertexnumber, const spVertex & spv)
Definition at line 755 of file kurve.cpp.
References geoff_geometry::spVertex::p, geoff_geometry::spVertex::pc, geoff_geometry::spVertex::spanid, and geoff_geometry::spVertex::type.
Referenced by OffsetMethod1(), and Reverse().
Replace() [2/2]
void geoff_geometry::Kurve::Replace (int vertexnumber, int type, const Point & p, const Point & pc, int ID = UNMARKED)
Definition at line 762 of file kurve.cpp.
References geoff_geometry::FAILURE(), geoff_geometry::getMessage(), m_nVertices, m_spans, buildPsets::p, SPANSTORAGE, and Path.Post.scripts.grbl_post::type.
Reverse() [1/2]
void geoff_geometry::Kurve::Reverse ()
Definition at line 1430 of file kurve.cpp.
References Get(), GetSpanID(), SplineSurface::i, m_nVertices, and Replace().
Reverse() [2/2]
bool geoff_geometry::Kurve::Reverse (bool isReversed) inline
Definition at line 1467 of file geometry.h.
SetZ()
void geoff_geometry::Kurve::SetZ (double z) inline
Definition at line 1506 of file geometry.h.
References SCL.SimpleDataTypes::e.
Spiral()
void geoff_geometry::Kurve::Spiral (const Point & centre, double startAngle, double startRadius, double radiusRisePerRevolution, double endRadius)
Split()
bool geoff_geometry::Kurve::Split (double MaximumRadius, double reslution)
Definition at line 1388 of file kurve.cpp.
References Add(), geoff_geometry::Span::dir, Get(), SplineSurface::i, LINEAR, test::m, m_nVertices, geoff_geometry::Span::p0, geoff_geometry::Span::p1, geoff_geometry::Span::pc, geoff_geometry::Span::radius, geoff_geometry::Span::SetProperties(), geoff_geometry::Span::Split(), geoff_geometry::Span::SplitMatrix(), Start(), and geoff_geometry::Point::Transform().
Start() [1/2]
void geoff_geometry::Kurve::Start ()
Definition at line 605 of file kurve.cpp.
References Clear(), and m_started.
Referenced by Add(), ChangeEnd(), ChangeStart(), geoff_geometry::eliminateLoops(), FullCircle(), OffsetISOMethod(), OffsetMethod1(), Part(), Reduce(), Split(), and Start().
Start() [2/2]
void geoff_geometry::Kurve::Start (const Point & p)
Definition at line 614 of file kurve.cpp.
References Add(), buildPsets::p, and Start().
Started()
bool geoff_geometry::Kurve::Started () const inline
Definition at line 1404 of file geometry.h.
StoreAllSpans()
void geoff_geometry::Kurve::StoreAllSpans (std::vector< Span > & kSpans) const
Definition at line 1216 of file kurve.cpp.
References Get(), SplineSurface::i, and nSpans().
Friends And Related Function Documentation
operator<<
wofstream& operator<< (wofstream & op, Kurve & k) friend
operator>>
wifstream& operator>> (wifstream & op, Kurve & k) friend
Member Data Documentation
m_isReversed
bool geoff_geometry::Kurve::m_isReversed protected
Definition at line 1366 of file geometry.h.
Referenced by Clear(), Get(), GetSpanID(), Kurve(), and operator=().
m_nVertices
int geoff_geometry::Kurve::m_nVertices protected
Definition at line 1365 of file geometry.h.
Referenced by Add(), AddIndex(), AddSpanID(), Area(), Clear(), Closed(), Get(), GetIndex(), GetSpanID(), Kurve(), minmax(), NearToVertex(), OffsetMethod1(), operator=(), Perim(), Reduce(), Replace(), Reverse(), and Split().
m_spans
vector<SpanVertex*> geoff_geometry::Kurve::m_spans protected
Definition at line 1363 of file geometry.h.
Referenced by Add(), AddIndex(), AddSpanID(), Clear(), Get(), GetIndex(), GetSpanID(), Kurve(), operator=(), and Replace().
m_started
bool geoff_geometry::Kurve::m_started protected
Definition at line 1364 of file geometry.h.
Referenced by Add(), Clear(), Kurve(), OffsetMethod1(), operator=(), Part(), and Start().
The documentation for this class was generated from the following files:
geometry.h
kurve.cpp
offset.cpp