FreeCAD: TechDrawGui::QGCustomClip Class Reference
TechDrawGui::QGCustomClip Class Reference
#include <QGCustomClip.h>
Public Types
enum { Type = QGraphicsItem::UserType + 132 }
Public Member Functions
QGCustomClip ()
~QGCustomClip () override
int type () const override
QRectF boundingRect () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
virtual void centerAt (QPointF centerPos)
virtual void centerAt (double cX, double cY)
virtual void setRect (QRectF r)
virtual void setRect (double x, double y, double w, double h)
virtual QRectF rect ()
void makeMark (double x, double y)
void makeMark (Base::Vector3d v)
Detailed Description
Definition at line 42 of file QGCustomClip.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 48 of file QGCustomClip.h.
Constructor & Destructor Documentation
QGCustomClip()
QGCustomClip::QGCustomClip () explicit
Definition at line 38 of file QGCustomClip.cpp.
~QGCustomClip()
TechDrawGui::QGCustomClip::~QGCustomClip () inline override
Definition at line 46 of file QGCustomClip.h.
Member Function Documentation
boundingRect()
QRectF QGCustomClip::boundingRect () const override
Definition at line 91 of file QGCustomClip.cpp.
Referenced by centerAt(), and TechDrawGui::QGIViewImage::rotateView().
centerAt() [1/2]
void QGCustomClip::centerAt (double cX, double cY) virtual
Definition at line 55 of file QGCustomClip.cpp.
References boundingRect(), and MengerSponge::box.
centerAt() [2/2]
void QGCustomClip::centerAt (QPointF centerPos) virtual
Definition at line 50 of file QGCustomClip.cpp.
Referenced by TechDrawGui::QGIViewImage::draw(), and TechDrawGui::QGIViewImage::QGIViewImage().
makeMark() [1/2]
void QGCustomClip::makeMark (Base::Vector3d v)
Definition at line 106 of file QGCustomClip.cpp.
References makeMark(), and TestSpreadsheet::v.
makeMark() [2/2]
void QGCustomClip::makeMark (double x, double y)
Definition at line 96 of file QGCustomClip.cpp.
References TechDrawGui::QGICMark::setSize(), TechDrawGui::QGICMark::setThick(), ZVALUE::VERTEX, MovieTool::x, and MovieTool::y.
Referenced by makeMark().
paint()
void QGCustomClip::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) override
Definition at line 82 of file QGCustomClip.cpp.
rect()
QRectF QGCustomClip::rect () virtual
Definition at line 77 of file QGCustomClip.cpp.
Referenced by TechDrawGui::QGIViewImage::drawImage().
setRect() [1/2]
void QGCustomClip::setRect (double x, double y, double w, double h) virtual
Definition at line 71 of file QGCustomClip.cpp.
References setRect(), src.Mod.PartDesign.fcgear.svggear::w, MovieTool::x, and MovieTool::y.
setRect() [2/2]
void QGCustomClip::setRect (QRectF r) virtual
Definition at line 65 of file QGCustomClip.cpp.
Referenced by TechDrawGui::QGIViewImage::draw(), TechDrawGui::QGIViewClip::drawClip(), TechDrawGui::QGIViewClip::QGIViewClip(), TechDrawGui::QGIViewImage::QGIViewImage(), and setRect().
type()
int TechDrawGui::QGCustomClip::type () const inline override
Definition at line 49 of file QGCustomClip.h.
The documentation for this class was generated from the following files:
QGCustomClip.h
QGCustomClip.cpp