FreeCAD: Gui::MDIView Class Reference
Gui::MDIView Class Reference
#include <MDIView.h>
Public Member Functions
MDIView (Gui::Document *pcDocument, QWidget *parent, Qt::WindowFlags wflags=Qt::WindowFlags())
~MDIView () override
void onRelabel (Gui::Document *pDoc) override
get called when the document is updated
virtual void viewAll ()
QString buildWindowTitle () const
build window title
bool onMsg (const char *pMsg, const char **ppReturn) override
Message handler.
bool onHasMsg (const char *pMsg) const override
Message handler test.
bool canClose () override
overwrite when checking on close state
void deleteSelf () override
delete itself
PyObject * getPyObject () override
Public Member Functions inherited from Gui::BaseView
BaseView (Gui::Document *pcDocument=nullptr)
~BaseView () override
void setDocument (Gui::Document *pcDocument)
sets the view to another document (called by Application)
void onClose ()
is sent from the document in order to close the document
Gui::Document * getGuiDocument () const
returns the document the view is attached to
App::Document * getAppDocument () const
returns the document the view is attached to
bool isPassive () const
indicates if the view is in passive mode
virtual void onUpdate ()
get called when the document is updated
virtual void onRename (Gui::Document *)
get called when the document is renamed (change of its internal name)
virtual const char * getName () const
returns the name of the view (important for messages)
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Printing
virtual void print ()
virtual void printPdf ()
virtual void printPreview ()
void savePrinterSettings (QPrinter *printer)
void restorePrinterSettings (QPrinter *printer)
virtual void print (QPrinter *printer)
Undo/Redo actions
enum ViewMode { Child, TopLevel, FullScreen }
MDI view mode enum.
PyObject * pythonObject
class MainWindow
virtual QStringList undoActions () const
virtual QStringList redoActions () const
QSize minimumSizeHint () const override
virtual void setCurrentViewMode (ViewMode mode)
ViewMode currentViewMode () const
template<typename _T >
_T getActiveObject (const char *name, App::DocumentObject **parent=nullptr, std::string *subname=nullptr) const
access getter for the active object list
void setActiveObject (App::DocumentObject *o, const char *n, const char *subname=nullptr)
bool hasActiveObject (const char *n) const
bool isActiveObject (App::DocumentObject *o, const char *n, const char *subname=nullptr) const
virtual bool containsViewProvider (const ViewProvider *) const
containsViewProvider Checks if the given view provider is part of this view. The default implementation returns false.
virtual void setOverrideCursor (const QCursor &)
virtual void restoreOverrideCursor ()
void message (const QString &, int)
virtual void windowStateChanged (QWidget *)
void closeEvent (QCloseEvent *e) override
void changeEvent (QEvent *e) override
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Gui::BaseView
Gui::Document * _pcDocument
bool bIsDetached {false}
bool bIsPassive {false}
Detailed Description
Base class of all windows belonging to a document. There are two ways of belonging to a document:
belong to a fix document
always belong to the active document The latter means whenever the active document is changing the view belongs to this document. It also means that the view belongs sometimes to no document at all.
See also
TreeView
Gui::Document
Application
Author
Jürgen Riegel, Werner Mayer
Definition at line 55 of file MDIView.h.
Member Enumeration Documentation
ViewMode
enum Gui::MDIView::ViewMode
MDI view mode enum.
Enumerator
Child
Child viewing, view is docked inside the MDI application window
TopLevel
The view becomes a top level window and can be moved outsinde the application window
FullScreen
The view goes to full screen viewing
Definition at line 116 of file MDIView.h.
Constructor & Destructor Documentation
MDIView()
MDIView::MDIView (Gui::Document * pcDocument, QWidget * parent, Qt::WindowFlags wflags = Qt::WindowFlags())
View constructor Attach the view to the given document. If the document is zero the view will attach to the active document. Be aware, there isn't always an active document.
Definition at line 58 of file MDIView.cpp.
References draftgeoutils.faces::bind(), and Gui::ActiveObjectList::objectDeleted().
~MDIView()
MDIView::~MDIView () override
View destructor Detach the view from the document, if attached.
Definition at line 78 of file MDIView.cpp.
References Gui::getMainWindow(), and pythonObject.
Member Function Documentation
buildWindowTitle()
QString MDIView::buildWindowTitle () const
build window title
Definition at line 453 of file MDIView.cpp.
References Gui::BaseView::getAppDocument().
Referenced by Gui::Application::viewActivated().
canClose()
bool MDIView::canClose () override virtual
overwrite when checking on close state
Reimplemented from Gui::BaseView.
Reimplemented in Gui::MDIViewPyWrap.
Definition at line 195 of file MDIView.cpp.
References Gui::BaseView::bIsPassive, Gui::BaseView::getAppDocument(), Gui::BaseView::getGuiDocument(), and App::Document::TempDoc.
Referenced by Gui::MDIViewPyWrap::canClose(), and closeEvent().
changeEvent()
void MDIView::changeEvent (QEvent * e) override protected
Definition at line 351 of file MDIView.cpp.
References SCL.SimpleDataTypes::e, Gui::getMainWindow(), Gui::MainWindow::setActiveWindow(), and Gui::MainWindow::tabChanged().
Referenced by StartGui::StartView::changeEvent().
closeEvent()
void MDIView::closeEvent (QCloseEvent * e) override protected
Definition at line 208 of file MDIView.cpp.
References Gui::BaseView::bIsPassive, canClose(), toolbit-attributes::doc, SCL.SimpleDataTypes::e, Gui::BaseView::getGuiDocument(), Gui::Application::Instance, and Gui::Application::viewClosed().
Referenced by Gui::EditorView::closeEvent(), and Gui::TextDocumentEditorView::closeEvent().
containsViewProvider()
virtual bool Gui::MDIView::containsViewProvider (const ViewProvider *) const inline virtual
containsViewProvider Checks if the given view provider is part of this view. The default implementation returns false.
Returns
bool
Reimplemented in Gui::View3DInventor, and Gui::AbstractSplitView.
Definition at line 156 of file MDIView.h.
Referenced by Gui::Document::setActiveView().
currentViewMode()
ViewMode Gui::MDIView::currentViewMode () const inline
Definition at line 128 of file MDIView.h.
Referenced by StdViewDockUndockFullscreen::activated(), StdViewDockUndockFullscreen::isActive(), and Gui::View3DInventor::setCurrentViewMode().
deleteSelf()
void MDIView::deleteSelf () override virtual
delete itself
Reimplemented from Gui::BaseView.
Reimplemented in SpreadsheetGui::SheetView, Gui::View3DInventor, and Gui::AbstractSplitView.
Definition at line 108 of file MDIView.cpp.
References Gui::BaseView::_pcDocument, Gui::BaseView::onClose(), and Init::parent.
Referenced by StdViewDockUndockFullscreen::activated(), Gui::AbstractSplitView::deleteSelf(), Gui::View3DInventor::deleteSelf(), and SpreadsheetGui::SheetView::deleteSelf().
getActiveObject()
template<typename _T > _T Gui::MDIView::getActiveObject (const char * name, App::DocumentObject ** parent = nullptr, std::string * subname = nullptr) const inline
access getter for the active object list
Definition at line 133 of file MDIView.h.
References Init::parent.
Referenced by PartDesignGui::getActivePart(), Gui::View3DInventorPy::getattr(), PartGui::getAutoGroupCommandStr(), PartDesignGui::getBody(), and PartDesignGui::ViewProvider::unsetEdit().
getPyObject()
PyObject * MDIView::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Reimplemented in SpreadsheetGui::SheetView, Gui::View3DInventor, TechDrawGui::MDIViewPage, Gui::AbstractSplitView, Gui::MDIViewPyWrap, and DrawingGui::DrawingView.
Definition at line 130 of file MDIView.cpp.
References pythonObject.
Referenced by Gui::MainWindowPy::getActiveWindow(), Gui::MDIViewPyWrap::getPyObject(), DrawingGui::DrawingView::getPyObject(), and Gui::ApplicationPy::sActiveView().
hasActiveObject()
bool Gui::MDIView::hasActiveObject (const char * n) const inline
Definition at line 141 of file MDIView.h.
isActiveObject()
bool Gui::MDIView::isActiveObject (App::DocumentObject * o, const char * n, const char * subname = nullptr) const inline
Definition at line 145 of file MDIView.h.
References src.Mod.Test.testPathArray::o.
message
void Gui::MDIView::message (const QString & , int) signal
Referenced by Gui::MainWindow::addWindow(), and Gui::MainWindow::removeWindow().
minimumSizeHint()
QSize MDIView::minimumSizeHint () const override
Definition at line 346 of file MDIView.cpp.
onHasMsg()
bool MDIView::onHasMsg (const char * pMsg) const override virtual
Message handler test.
Implements Gui::BaseView.
Reimplemented in Gui::View3DInventor, TechDrawGui::MDIViewPage, Gui::MDIViewPyWrap, Gui::AbstractSplitView, SpreadsheetGui::SheetView, StartGui::StartView, DrawingGui::DrawingView, and Gui::TextDocumentEditorView.
Definition at line 189 of file MDIView.cpp.
Referenced by Gui::OverlayProxyWidget::hitTest(), and Gui::MDIViewPyWrap::onHasMsg().
onMsg()
bool MDIView::onMsg (const char * pMsg, const char ** ppReturn) override virtual
Message handler.
receive a message
Implements Gui::BaseView.
Reimplemented in Gui::View3DInventor, TechDrawGui::MDIViewPage, Gui::MDIViewPyWrap, Gui::AbstractSplitView, SpreadsheetGui::SheetView, DrawingGui::DrawingView, and Gui::TextDocumentEditorView.
Definition at line 182 of file MDIView.cpp.
Referenced by StdViewDockUndockFullscreen::activated(), Gui::Application::importFrom(), Gui::MDIViewPyWrap::onMsg(), and Gui::Document::sendMsgToFirstView().
onRelabel()
void MDIView::onRelabel (Gui::Document * pDoc) override virtual
get called when the document is updated
Reimplemented from Gui::BaseView.
Reimplemented in DrawingGui::DrawingView.
Definition at line 148 of file MDIView.cpp.
References Gui::BaseView::bIsPassive, Gui::Document::getDocument(), App::PropertyString::getValue(), App::Document::Label, and src.Mod.AddonManager.addonmanager_devmode_license_selector::QRegularExpression.
print() [1/2]
void MDIView::print () virtual
Print content of view
Reimplemented in Gui::View3DInventor, Gui::EditorView, Gui::MDIViewPyWrap, SpreadsheetGui::SheetView, TechDrawGui::MDIViewPage, Gui::GraphvizView, and DrawingGui::DrawingView.
Definition at line 247 of file MDIView.cpp.
Referenced by Gui::ImageView::onMsg(), Gui::MDIViewPyWrap::print(), printPdf(), and printPreview().
print [2/2]
void MDIView::print (QPrinter * printer) virtual slot
Reimplemented in TechDrawGui::MDIViewPage, Gui::ImageView, Gui::GraphvizView, DrawingGui::DrawingView, Gui::View3DInventor, Gui::EditorView, and SpreadsheetGui::SheetView.
Definition at line 241 of file MDIView.cpp.
Referenced by StdCmdPrint::activated(), and Gui::ApplicationPy::sExport().
printPdf()
void MDIView::printPdf () virtual
Print to PDF file
Reimplemented in Gui::View3DInventor, Gui::EditorView, Gui::MDIViewPyWrap, TechDrawGui::MDIViewPage, SpreadsheetGui::SheetView, Gui::GraphvizView, and DrawingGui::DrawingView.
Definition at line 257 of file MDIView.cpp.
References Gui::FileDialog::getSaveFileName(), and print().
Referenced by StdCmdPrintPdf::activated(), Gui::ImageView::onMsg(), and Gui::MDIViewPyWrap::printPdf().
printPreview()
void MDIView::printPreview () virtual
Show a preview dialog
Reimplemented in Gui::View3DInventor, Gui::MDIViewPyWrap, Gui::EditorView, TechDrawGui::MDIViewPage, SpreadsheetGui::SheetView, Gui::GraphvizView, and DrawingGui::DrawingView.
Definition at line 271 of file MDIView.cpp.
References draftgeoutils.intersections::connect(), and print().
Referenced by StdCmdPrintPreview::activated(), Gui::ImageView::onMsg(), and Gui::MDIViewPyWrap::printPreview().
redoActions()
QStringList MDIView::redoActions () const virtual
Reimplemented in Gui::TextDocumentEditorView, Gui::MDIViewPyWrap, and Gui::EditorView.
Definition at line 332 of file MDIView.cpp.
References toolbit-attributes::doc, Gui::BaseView::getGuiDocument(), and src.Mod.AddonManager.Addon::translate.
Referenced by Gui::Dialog::RedoDialog::onFetchInfo(), and Gui::MDIViewPyWrap::redoActions().
restoreOverrideCursor
void MDIView::restoreOverrideCursor () virtual slot
Definition at line 144 of file MDIView.cpp.
Referenced by Gui::SelectionSingleton::rmvPreselect(), Gui::SelectionSingleton::rmvSelectionGate(), and Gui::SelectionSingleton::setPreselect().
restorePrinterSettings()
void MDIView::restorePrinterSettings (QPrinter * printer)
Restore the printer configuration
Definition at line 296 of file MDIView.cpp.
References App::GetApplication(), ParameterGrp::GetGroup(), App::Application::GetParameterGroupByPath(), Path.Log::info(), and ClipperLib::Orientation().
Referenced by Gui::View3DInventor::print(), and Gui::View3DInventor::printPreview().
savePrinterSettings()
void MDIView::savePrinterSettings (QPrinter * printer)
Save the printer configuration
Definition at line 280 of file MDIView.cpp.
References App::GetApplication(), ParameterGrp::GetGroup(), App::Application::GetParameterGroupByPath(), and ParameterGrp::SetInt().
Referenced by Gui::View3DInventor::print(), and Gui::View3DInventor::printPreview().
setActiveObject()
void Gui::MDIView::setActiveObject (App::DocumentObject * o, const char * n, const char * subname = nullptr) inline
Definition at line 137 of file MDIView.h.
References src.Mod.Test.testPathArray::o.
setCurrentViewMode()
void MDIView::setCurrentViewMode (ViewMode mode) virtual
If b is set to FullScreen the MDI view is displayed in full screen mode, if b is set to TopLevel then it is displayed as an own top-level window, otherwise (Normal) as tabbed window. For more hints refer to the Qt documentation to QWidget::showFullScreen ().
Reimplemented in Gui::View3DInventor.
Definition at line 380 of file MDIView.cpp.
References Gui::MainWindow::addWindow(), Child, FullScreen, Gui::getMainWindow(), Gui::MainWindow::removeWindow(), and TopLevel.
Referenced by StdMainFullscreen::activated(), and Gui::View3DInventor::setCurrentViewMode().
setOverrideCursor
void MDIView::setOverrideCursor (const QCursor & c) virtual slot
Reimplemented in Gui::AbstractSplitView.
Definition at line 139 of file MDIView.cpp.
References SCL.SimpleDataTypes::c.
Referenced by Gui::SelectionSingleton::addSelection(), and Gui::SelectionSingleton::setPreselect().
undoActions()
QStringList MDIView::undoActions () const virtual
Reimplemented in Gui::TextDocumentEditorView, Gui::MDIViewPyWrap, and Gui::EditorView.
Definition at line 318 of file MDIView.cpp.
References toolbit-attributes::doc, Gui::BaseView::getGuiDocument(), and src.Mod.AddonManager.Addon::translate.
Referenced by Gui::Dialog::UndoDialog::onFetchInfo(), and Gui::MDIViewPyWrap::undoActions().
viewAll()
void MDIView::viewAll () virtual
Reimplemented in Gui::View3DInventor, and Gui::AbstractSplitView.
Definition at line 177 of file MDIView.cpp.
Referenced by StdCmdViewCreate::activated().
windowStateChanged
void MDIView::windowStateChanged (QWidget * view) protected virtual slot
This method gets called from the main window this view is attached to whenever the window state of the active view changes. The default implementation does nothing.
Reimplemented in Gui::View3DInventor.
Definition at line 236 of file MDIView.cpp.
Referenced by Gui::MainWindow::addWindow(), and Gui::MainWindow::removeWindow().
Friends And Related Function Documentation
MainWindow
friend class MainWindow friend
Definition at line 190 of file MDIView.h.
Member Data Documentation
pythonObject
PyObject* Gui::MDIView::pythonObject protected
Definition at line 180 of file MDIView.h.
Referenced by getPyObject(), and ~MDIView().
The documentation for this class was generated from the following files:
MDIView.h
MDIView.cpp