FreeCAD: Base::Line2d Class Reference
Base::Line2d Class Reference
#include <Tools2D.h>
Public Member Functions
Line2d ()=default
~Line2d ()=default
Line2d (const Line2d &)=default
Line2d (Line2d &&)=default
Line2d (const Vector2d &rclV1, const Vector2d &rclV2)
double Length () const
BoundBox2d CalcBoundBox () const
Line2d & operator= (const Line2d &)=default
Line2d & operator= (Line2d &&)=default
bool operator== (const Line2d &rclLine) const
bool Contains (const Vector2d &rclV) const
bool Intersect (const Line2d &rclLine, Vector2d &rclV) const
bool Intersect (const Vector2d &rclV, double eps) const
bool IntersectAndContain (const Line2d &rclLine, Vector2d &rclV) const
Vector2d FromPos (double fDistance) const
Public Attributes
Vector2d clV1
Vector2d clV2
Detailed Description
Line2d 2D line class.
Definition at line 163 of file Tools2D.h.
Constructor & Destructor Documentation
Line2d() [1/4]
Base::Line2d::Line2d () default
~Line2d()
Base::Line2d::~Line2d () default
Line2d() [2/4]
Base::Line2d::Line2d (const Line2d &) inline default
Line2d() [3/4]
Base::Line2d::Line2d (Line2d &&) inline default
Line2d() [4/4]
Base::Line2d::Line2d (const Vector2d & rclV1, const Vector2d & rclV2) inline
Definition at line 456 of file Tools2D.h.
References DOUBLE_MAX, Base::BoundBox2d::MaxX, Base::BoundBox2d::MaxY, Base::BoundBox2d::MinX, and Base::BoundBox2d::MinY.
Member Function Documentation
CalcBoundBox()
BoundBox2d Line2d::CalcBoundBox () const
LINE2D
Definition at line 155 of file Tools2D.cpp.
References clV1, clV2, Base::BoundBox2d::MaxX, Base::BoundBox2d::MaxY, Base::BoundBox2d::MinX, Base::BoundBox2d::MinY, Base::Vector2d::x, and Base::Vector2d::y.
Referenced by Base::Polygon2d::At().
Contains()
bool Base::Line2d::Contains (const Vector2d & rclV) const inline
Definition at line 471 of file Tools2D.h.
Referenced by IntersectAndContain().
FromPos()
Vector2d Line2d::FromPos (double fDistance) const
Definition at line 230 of file Tools2D.cpp.
References clV1, clV2, Base::Vector2d::Normalize(), Base::Vector2d::x, and Base::Vector2d::y.
Referenced by Base::Polygon2d::Intersect().
Intersect() [1/2]
bool Line2d::Intersect (const Line2d & rclLine, Vector2d & rclV) const
Definition at line 165 of file Tools2D.cpp.
References clV1, clV2, DOUBLE_MAX, SCL.SimpleDataTypes::e, Base::Vector2d::x, and Base::Vector2d::y.
Referenced by SketcherGui::calculateAngle(), and IntersectAndContain().
Intersect() [2/2]
bool Line2d::Intersect (const Vector2d & rclV, double eps) const
Definition at line 209 of file Tools2D.cpp.
References clV1, clV2, dot(), Base::Vector2d::x, and Base::Vector2d::y.
IntersectAndContain()
bool Line2d::IntersectAndContain (const Line2d & rclLine, Vector2d & rclV) const
Definition at line 237 of file Tools2D.cpp.
References Contains(), and Intersect().
Referenced by Base::BoundBox2d::Intersect(), and Base::Polygon2d::Intersect().
Length()
double Base::Line2d::Length () const inline
Definition at line 461 of file Tools2D.h.
operator=() [1/2]
Line2d& Base::Line2d::operator= (const Line2d &) inline default
operator=() [2/2]
Line2d& Base::Line2d::operator= (Line2d &&) inline default
operator==()
bool Base::Line2d::operator== (const Line2d & rclLine) const inline
Definition at line 466 of file Tools2D.h.
Member Data Documentation
clV1
Vector2d Base::Line2d::clV1
Definition at line 166 of file Tools2D.h.
Referenced by Base::Polygon2d::At(), CalcBoundBox(), FromPos(), Base::BoundBox2d::Intersect(), Intersect(), and Base::Polygon2d::operator[]().
clV2
Vector2d Base::Line2d::clV2
Definition at line 166 of file Tools2D.h.
Referenced by Base::Polygon2d::At(), CalcBoundBox(), FromPos(), Base::BoundBox2d::Intersect(), Intersect(), and Base::Polygon2d::operator[]().
The documentation for this class was generated from the following files:
Tools2D.h
Tools2D.cpp