FreeCAD: Gui::DlgObjectSelection Class Reference
Gui::DlgObjectSelection Class Reference
#include <DlgObjectSelection.h>
Public Types
enum SelectionOptions { SelectionOptions::Invert = 1, SelectionOptions::Sort = 2, SelectionOptions::InvertSort = 3 }
Options for getSelections()
Public Member Functions
DlgObjectSelection (const std::vector< App::DocumentObject * > &objs, QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
DlgObjectSelection (const std::vector< App::DocumentObject * > &objs, const std::vector< App::DocumentObject * > &excludes, QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~DlgObjectSelection () override
Destructor.
std::vector< App::DocumentObject * > getSelections (SelectionOptions options=SelectionOptions()) const
Get the selected objects.
void addCheckBox (QCheckBox *box)
Add a user defined checkbox at the bottom of the dialog.
void setMessage (const QString &)
Override the prompt message.
void accept () override
void reject () override
Detailed Description
Dialog for object dependency selection
Definition at line 41 of file DlgObjectSelection.h.
Member Enumeration Documentation
SelectionOptions
enum Gui::DlgObjectSelection::SelectionOptions strong
Options for getSelections()
Enumerator
Invert
Invert the selection, i.e. return the unselected objects.
Sort
Sort the returned object in depending order.
InvertSort
Return the unselected objects sorted in depending order.
Definition at line 77 of file DlgObjectSelection.h.
Constructor & Destructor Documentation
DlgObjectSelection() [1/2]
DlgObjectSelection::DlgObjectSelection (const std::vector< App::DocumentObject * > & objs, QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags())
Constructor
Creates a dialog for selecting the given objects and their dependent objects
Parameters
objs initial objects
parent optional parent widget
fl optional window flags
Definition at line 47 of file DlgObjectSelection.cpp.
References SIM::Coin3D::Quarter::Quarter::init(), and replaceobj::objs.
DlgObjectSelection() [2/2]
DlgObjectSelection::DlgObjectSelection (const std::vector< App::DocumentObject * > & objs, const std::vector< App::DocumentObject * > & excludes, QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags())
Constructor
Creates a dialog for selecting the given objects and their dependent objects with exclusions
Parameters
objs initial objects
excludes excluded objects. The objects and their dependents will still be in the list but unchecked.
parent optional parent widget
fl optional window flags
Definition at line 54 of file DlgObjectSelection.cpp.
References replaceobj::objs.
~DlgObjectSelection()
DlgObjectSelection::~DlgObjectSelection () override
Destructor.
Destroys the object and frees any allocated resources
Definition at line 179 of file DlgObjectSelection.cpp.
Member Function Documentation
accept()
void DlgObjectSelection::accept () override
Definition at line 623 of file DlgObjectSelection.cpp.
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
addCheckBox()
void DlgObjectSelection::addCheckBox (QCheckBox * box)
Add a user defined checkbox at the bottom of the dialog.
Definition at line 631 of file DlgObjectSelection.cpp.
References MengerSponge::box.
getSelections()
std::vector< App::DocumentObject * > DlgObjectSelection::getSelections (SelectionOptions options = SelectionOptions()) const
Get the selected objects.
Definition at line 339 of file DlgObjectSelection.cpp.
References Invert, Sort, Base::Flags< Enum >::testFlag(), and TestSpreadsheet::v.
Referenced by StdCmdDuplicateSelection::activated(), and Gui::MainWindow::createMimeDataFromSelection().
reject()
void DlgObjectSelection::reject () override
Definition at line 627 of file DlgObjectSelection.cpp.
Referenced by bimcommands.BimReorder.BIM_Reorder_TaskPanel::accept(), draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), draftguitools.gui_selectplane.Draft_SelectPlane::action(), JointObject.TaskAssemblyCreateJoint::autoClosedOnTransactionChange(), femexamples.examplesgui.FemExamples::clicked(), CommandCreateView.TaskAssemblyCreateView::KeyboardEvent(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), bimcommands.BimProjectManager.BIM_ProjectManager::loadTemplate(), bimcommands.BimLibrary.BIM_Library_TaskPanel::mouseClick(), bimcommands.BimProjectManager.BIM_ProjectManager::saveTemplate(), and Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit().
setMessage()
void DlgObjectSelection::setMessage (const QString & msg)
Override the prompt message.
Definition at line 635 of file DlgObjectSelection.cpp.
References Path.Op.Surface::msg.
Referenced by Gui::ViewProviderLink::setupContextMenu().
The documentation for this class was generated from the following files:
DlgObjectSelection.h
DlgObjectSelection.cpp