FreeCAD: MeshCore::MeshOrientationCollector Class Reference
MeshCore::MeshOrientationCollector Class Reference
#include <Evaluation.h>
Public Member Functions
MeshOrientationCollector (std::vector< FacetIndex > &aulIndices, std::vector< FacetIndex > &aulComplement)
bool Visit (const MeshFacet &, const MeshFacet &, FacetIndex, unsigned long) override
Public Member Functions inherited from MeshCore::MeshOrientationVisitor
MeshOrientationVisitor ()
bool HasNonUnifomOrientedFacets () const
Public Member Functions inherited from MeshCore::MeshFacetVisitor
MeshFacetVisitor ()=default
Construction.
virtual ~MeshFacetVisitor ()=default
Denstruction.
virtual bool AllowVisit (const MeshFacet &rclFacet, const MeshFacet &rclFrom, FacetIndex ulFInd, unsigned long ulLevel, unsigned short neighbourIndex)
Detailed Description
This class searches for inconsistent orientation of neighboured facets. Note: The 'TMP0' flag for facets must be reset before using this class.
Author
Werner Mayer
Definition at line 147 of file Evaluation.h.
Constructor & Destructor Documentation
MeshOrientationCollector()
MeshOrientationCollector::MeshOrientationCollector (std::vector< FacetIndex > & aulIndices, std::vector< FacetIndex > & aulComplement)
Definition at line 67 of file Evaluation.cpp.
Member Function Documentation
Visit()
bool MeshOrientationCollector::Visit (const MeshFacet & rclFacet, const MeshFacet & rclFrom, FacetIndex ulFInd, unsigned long ulLevel) override virtual
Returns always true and collects the indices with wrong orientation.
Reimplemented from MeshCore::MeshOrientationVisitor.
Definition at line 73 of file Evaluation.cpp.
References MeshCore::MeshFacet::HasSameOrientation(), MeshCore::MeshFacet::IsFlag(), MeshCore::MeshFacet::SetFlag(), and MeshCore::MeshFacet::TMP0.
The documentation for this class was generated from the following files:
Evaluation.h
Evaluation.cpp