FreeCAD: Gui::SoFCSelectionContextEx Struct Reference
Gui::SoFCSelectionContextEx Struct Reference
#include <SoFCSelectionContext.h>
Public Member Functions
bool setColors (const std::map< std::string, App::Color > &colors, const std::string &element)
uint32_t packColor (const App::Color &c, bool &hasTransparency)
bool applyColor (int idx, std::vector< uint32_t > &packedColors, bool &hasTransparency)
bool isSingleColor (uint32_t &color, bool &hasTransparency)
SoFCSelectionContextBasePtr copy () override
Public Member Functions inherited from Gui::SoFCSelectionContext
~SoFCSelectionContext () override
bool isSelected () const
void selectAll ()
bool isSelectAll () const
bool isHighlighted () const
bool isHighlightAll () const
void highlightAll ()
void removeHighlight ()
bool removeIndex (int index)
bool checkGlobal (SoFCSelectionContextPtr ctx)
Public Member Functions inherited from Gui::SoFCSelectionContextBase
virtual ~SoFCSelectionContextBase ()=default
Public Attributes
std::map< int, App::Color > colors
float trans0 = 0.0
Public Attributes inherited from Gui::SoFCSelectionContext
int highlightIndex = -1
std::set< int > selectionIndex
SbColor selectionColor
SbColor highlightColor
std::shared_ptr< int > counter
Static Public Attributes
static MergeFunc merge
Static Public Attributes inherited from Gui::SoFCSelectionContext
static MergeFunc merge
Additional Inherited Members
Public Types inherited from Gui::SoFCSelectionContextBase
using MergeFunc = int(int status, SoFCSelectionContextBasePtr &output, SoFCSelectionContextBasePtr input, SoNode *node)
Detailed Description
Definition at line 106 of file SoFCSelectionContext.h.
Member Function Documentation
applyColor()
bool SoFCSelectionContextEx::applyColor (int idx, std::vector< uint32_t > & packedColors, bool & hasTransparency)
Definition at line 159 of file SoFCSelectionContext.cpp.
References colors, and packColor().
copy()
SoFCSelectionContextBasePtr Gui::SoFCSelectionContextEx::copy () inline override virtual
Reimplemented from Gui::SoFCSelectionContext.
Definition at line 116 of file SoFCSelectionContext.h.
isSingleColor()
bool SoFCSelectionContextEx::isSingleColor (uint32_t & color, bool & hasTransparency)
Definition at line 172 of file SoFCSelectionContext.cpp.
References colors, and packColor().
packColor()
uint32_t SoFCSelectionContextEx::packColor (const App::Color & c, bool & hasTransparency)
Definition at line 152 of file SoFCSelectionContext.cpp.
References SCL.SimpleDataTypes::c, KDL::max(), and trans0.
Referenced by applyColor(), and isSingleColor().
setColors()
bool SoFCSelectionContextEx::setColors (const std::map< std::string, App::Color > & colors, const std::string & element)
Definition at line 127 of file SoFCSelectionContext.cpp.
References colors.
Member Data Documentation
colors
std::map<int,App::Color> Gui::SoFCSelectionContextEx::colors
Definition at line 108 of file SoFCSelectionContext.h.
Referenced by applyColor(), isSingleColor(), setColors(), Path.Dressup.Gui.Tags.PathDressupTagViewProvider::setupColors(), and Path.Dressup.Gui.Tags.PathDressupTagViewProvider::updatePositions().
merge
int SoFCSelectionContextEx::merge static
Definition at line 120 of file SoFCSelectionContext.h.
trans0
float Gui::SoFCSelectionContextEx::trans0 = 0.0
Definition at line 109 of file SoFCSelectionContext.h.
Referenced by packColor().
The documentation for this struct was generated from the following files:
SoFCSelectionContext.h
SoFCSelectionContext.cpp