FreeCAD: MeshCore::MeshFixTopology Class Reference
MeshCore::MeshFixTopology Class Reference
#include <Evaluation.h>
Public Member Functions
MeshFixTopology (MeshKernel &rclB, const std::list< std::vector< FacetIndex >> &mf)
bool Fixup () override
const std::vector< FacetIndex > & GetDeletedFaces () const
Public Member Functions inherited from MeshCore::MeshValidation
MeshValidation (MeshKernel &rclB)
virtual ~MeshValidation ()=default
MeshValidation (const MeshValidation &)=delete
MeshValidation (MeshValidation &&)=delete
MeshValidation & operator= (const MeshValidation &)=delete
MeshValidation & operator= (MeshValidation &&)=delete
Additional Inherited Members
Protected Attributes inherited from MeshCore::MeshValidation
MeshKernel & _rclMesh
Detailed Description
The MeshFixTopology class tries to fix a few cases of non-manifolds.
See also
MeshEvalTopology
Definition at line 252 of file Evaluation.h.
Constructor & Destructor Documentation
MeshFixTopology()
MeshCore::MeshFixTopology::MeshFixTopology (MeshKernel & rclB, const std::list< std::vector< FacetIndex >> & mf) inline
Definition at line 255 of file Evaluation.h.
Member Function Documentation
Fixup()
bool MeshFixTopology::Fixup () override virtual
This function attempts to change the mesh kernel to be valid according to the checked criterion: True is returned if the errors could be fixed, false otherwise.
Implements MeshCore::MeshValidation.
Definition at line 419 of file Evaluation.cpp.
References MeshCore::MeshValidation::_rclMesh, MeshCore::MeshKernel::DeleteFacets(), MeshCore::MeshEvalTopology::Evaluate(), MeshCore::MeshEvalTopology::GetFacetManifolds(), MeshCore::MeshKernel::GetFacets(), and MeshCore::MeshKernel::RebuildNeighbours().
Referenced by Mesh::MeshObject::removeNonManifolds().
GetDeletedFaces()
const std::vector<FacetIndex>& MeshCore::MeshFixTopology::GetDeletedFaces () const inline
Definition at line 261 of file Evaluation.h.
Referenced by Mesh::MeshObject::removeNonManifolds().
The documentation for this class was generated from the following files:
Evaluation.h
Evaluation.cpp