FreeCAD: TechDrawGui::PagePrinter Class Reference
TechDrawGui::PagePrinter Class Reference
#include <PagePrinter.h>
Static Public Member Functions
static void printBannerPage (QPrinter *printer, QPainter &painter, QPageLayout &pageLayout, App::Document *doc, std::vector< App::DocumentObject * > &docObjs)
we don't need the banner page any more, but it might become useful again in the future.
static void renderPage (ViewProviderPage *vpp, QPainter &painter, QRectF &sourceRect, QRect &targetRect)
static void makePageLayout (TechDraw::DrawPage *dPage, QPageLayout &pageLayout, double &width, double &height)
construct a page layout object that reflects the characteristics of a DrawPage
static PaperAttributes getPaperAttributes (TechDraw::DrawPage *pageObject)
retrieve the attributes of a DrawPage and its Template
static PaperAttributes getPaperAttributes (ViewProviderPage *vpPage)
retrieve the attributes of a DrawPage by its viewProvider
static void print (ViewProviderPage *vpPage, QPrinter *printer)
print the Page associated with the view provider
static void printPdf (ViewProviderPage *vpPage, const std::string &file)
print the Page associated with the ViewProvider as a Pdf file
static void printAll (QPrinter *printer, App::Document *doc)
print all pages in a document
static void printAllPdf (QPrinter *printer, App::Document *doc)
print all pages in a document to pdf
static void saveSVG (ViewProviderPage *vpPage, const std::string &file)
save the page associated with the view provider as an svg file
static void saveDXF (ViewProviderPage *vpPage, const std::string &file)
save the page associated with the view provider as an svg file
static void savePDF (ViewProviderPage *vpPage, const std::string &file)
Detailed Description
Definition at line 88 of file PagePrinter.h.
Member Function Documentation
getPaperAttributes() [1/2]
PaperAttributes PagePrinter::getPaperAttributes (TechDraw::DrawPage * pageObject) static
retrieve the attributes of a DrawPage and its Template
Definition at line 75 of file PagePrinter.cpp.
References A4Heightmm, A4Widthmm, TechDraw::DrawPage::getOrientation(), App::PropertyLink::getValue(), SplineSurface::id, KDL::max(), KDL::min(), ClipperLib::Orientation(), result, and TechDraw::DrawPage::Template.
Referenced by TechDrawGui::MDIViewPage::print(), and TechDrawGui::MDIViewPage::printPreview().
getPaperAttributes() [2/2]
PaperAttributes PagePrinter::getPaperAttributes (ViewProviderPage * vpPage) static
retrieve the attributes of a DrawPage by its viewProvider
Definition at line 108 of file PagePrinter.cpp.
References TechDrawGui::ViewProviderPage::getDrawPage().
makePageLayout()
void PagePrinter::makePageLayout (TechDraw::DrawPage * dPage, QPageLayout & pageLayout, double & width, double & height) static
construct a page layout object that reflects the characteristics of a DrawPage
Definition at line 116 of file PagePrinter.cpp.
References TechDrawGui::PaperAttributes::orientation(), TechDrawGui::PaperAttributes::pageHeight(), TechDrawGui::PaperAttributes::pageSize(), and TechDrawGui::PaperAttributes::pageWidth().
print()
void PagePrinter::print (ViewProviderPage * vpPage, QPrinter * printer) static
print the Page associated with the view provider
Definition at line 309 of file PagePrinter.cpp.
References A4Heightmm, A4Widthmm, App::DocumentObject::getDocument(), Gui::Application::getDocument(), TechDrawGui::ViewProviderPage::getDrawPage(), TechDrawGui::ViewProviderPage::getQGSPage(), TechDrawGui::Rez::guiX(), Gui::Application::Instance, Gui::Document::isModified(), TechDraw::DrawPage::redrawCommand(), and TechDrawGui::QGSPage::setExportingPdf().
Referenced by TechDrawGui::MDIViewPage::print().
printAll()
void PagePrinter::printAll (QPrinter * printer, App::Document * doc) static
print all pages in a document
Definition at line 130 of file PagePrinter.cpp.
References A4Heightmm, A4Widthmm, toolbit-attributes::doc, Base::Persistence::getClassTypeId(), Gui::Application::getDocument(), Gui::Application::getViewProvider(), TechDrawGui::Rez::guiX(), Gui::Application::Instance, and Gui::Document::isModified().
Referenced by TechDrawGui::MDIViewPage::printAll(), and TechDrawGui::MDIViewPage::printAllPages().
printAllPdf()
void PagePrinter::printAllPdf (QPrinter * printer, App::Document * doc) static
print all pages in a document to pdf
Definition at line 178 of file PagePrinter.cpp.
References A4Heightmm, A4Widthmm, toolbit-attributes::doc, Base::Persistence::getClassTypeId(), Gui::Application::getDocument(), TechDrawGui::ViewProviderPage::getQGSPage(), Gui::Application::getViewProvider(), TechDrawGui::Rez::guiX(), Gui::Application::Instance, Gui::Document::isModified(), mmPerInch, and TechDrawGui::QGSPage::setExportingPdf().
Referenced by TechDrawGui::MDIViewPage::printAllPages().
printBannerPage()
void PagePrinter::printBannerPage (QPrinter * printer, QPainter & painter, QPageLayout & pageLayout, App::Document * doc, std::vector< App::DocumentObject * > & docObjs) static
we don't need the banner page any more, but it might become useful again in the future.
Definition at line 249 of file PagePrinter.cpp.
References toolbit-attributes::doc, and mmPerInch.
printPdf()
void PagePrinter::printPdf (ViewProviderPage * vpPage, const std::string & file) static
print the Page associated with the ViewProvider as a Pdf file
Definition at line 339 of file PagePrinter.cpp.
References A4Heightmm, A4Widthmm, TechDraw::DrawUtil::cleanFilespecBackslash(), Base::Console(), Base::Tools::escapeEncodeFilename(), DrawingExample::file, Gui::Application::getDocument(), TechDrawGui::ViewProviderPage::getDrawPage(), App::DocumentObject::getNameInDocument(), TechDrawGui::ViewProviderPage::getQGSPage(), TechDrawGui::Rez::guiX(), Gui::Application::Instance, Gui::Document::isModified(), mmPerInch, TechDrawGui::QGSPage::setExportingPdf(), and Base::ConsoleSingleton::Warning().
Referenced by TechDrawGui::MDIViewPage::printPdf().
renderPage()
void PagePrinter::renderPage (ViewProviderPage * vpp, QPainter & painter, QRectF & sourceRect, QRect & targetRect) static
Definition at line 281 of file PagePrinter.cpp.
References TechDrawGui::ViewProviderPage::getFrameState(), TechDrawGui::ViewProviderPage::getQGSPage(), TechDrawGui::QGSPage::redrawAllViews(), TechDrawGui::QGSPage::refreshViews(), TechDrawGui::ViewProviderPage::setFrameState(), and TechDrawGui::ViewProviderPage::setTemplateMarkers().
saveDXF()
void PagePrinter::saveDXF (ViewProviderPage * vpPage, const std::string & file) static
save the page associated with the view provider as an svg file
Definition at line 415 of file PagePrinter.cpp.
References TechDraw::DrawUtil::cleanFilespecBackslash(), Gui::Command::commitCommand(), Gui::Command::Doc, doCommand, Base::Tools::escapeEncodeFilename(), TechDrawGui::ViewProviderPage::getDrawPage(), App::DocumentObject::getNameInDocument(), Gui::Command::openCommand(), and Arch::QT_TRANSLATE_NOOP.
Referenced by TechDrawGui::MDIViewPage::saveDXF().
savePDF()
void PagePrinter::savePDF (ViewProviderPage * vpPage, const std::string & file) static
Definition at line 432 of file PagePrinter.cpp.
References DrawingExample::file.
Referenced by TechDrawGui::MDIViewPage::savePDF().
saveSVG()
void PagePrinter::saveSVG (ViewProviderPage * vpPage, const std::string & file) static
save the page associated with the view provider as an svg file
Definition at line 391 of file PagePrinter.cpp.
References TechDraw::DrawUtil::cleanFilespecBackslash(), Base::Console(), Base::Tools::escapeEncodeFilename(), DrawingExample::file, Gui::ViewProviderDocumentObject::getDocument(), TechDrawGui::ViewProviderPage::getQGSPage(), Gui::Document::isModified(), TechDrawGui::QGSPage::setExportingSvg(), and Base::ConsoleSingleton::Warning().
Referenced by TechDrawGui::MDIViewPage::saveSVG().
The documentation for this class was generated from the following files:
PagePrinter.h
PagePrinter.cpp