FreeCAD: Gui::RecentFilesAction::Private Class Reference
Gui::RecentFilesAction::Private Class Reference
Public Member Functions
Private (const Private &)=delete
Private (Private &&)=delete
void operator= (const Private &)=delete
void operator= (Private &&)=delete
Private (RecentFilesAction *master, const char *path)
~Private () override
void OnChange (Base::Subject< const char * > &sub, const char *reason) override
void trySaveUserParameter ()
void saveUserParameter ()
Public Attributes
RecentFilesAction * master
ParameterGrp::handle handle
bool updating = false
Detailed Description
Definition at line 768 of file Action.cpp.
Constructor & Destructor Documentation
Private() [1/3]
Gui::RecentFilesAction::Private::Private (const Private &) delete
Private() [2/3]
Gui::RecentFilesAction::Private::Private (Private &&) delete
Private() [3/3]
Gui::RecentFilesAction::Private::Private (RecentFilesAction * master, const char * path) inline
Definition at line 776 of file Action.cpp.
References Base::Subject< MsgType >::Attach(), App::GetApplication(), App::Application::GetParameterGroupByPath(), and Gui::RecentFilesAction::Private::handle.
~Private()
Gui::RecentFilesAction::Private::~Private () inline override
Definition at line 782 of file Action.cpp.
References Base::Subject< MsgType >::Detach(), and Gui::RecentFilesAction::Private::handle.
Member Function Documentation
OnChange()
void Gui::RecentFilesAction::Private::OnChange (Base::Subject< const char * > & sub, const char * reason) inline override
Definition at line 787 of file Action.cpp.
References Gui::RecentFilesAction::Private::master, and Gui::RecentFilesAction::Private::updating.
operator=() [1/2]
void Gui::RecentFilesAction::Private::operator= (const Private &) delete
operator=() [2/2]
void Gui::RecentFilesAction::Private::operator= (Private &&) delete
saveUserParameter()
void Gui::RecentFilesAction::Private::saveUserParameter () inline
Definition at line 806 of file Action.cpp.
References App::Application::Config(), App::GetApplication(), App::Application::GetParameterSet(), and ParameterManager::SaveDocument().
Referenced by Gui::RecentFilesAction::Private::trySaveUserParameter().
trySaveUserParameter()
void Gui::RecentFilesAction::Private::trySaveUserParameter () inline
Definition at line 796 of file Action.cpp.
References App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), and Gui::RecentFilesAction::Private::saveUserParameter().
Member Data Documentation
handle
ParameterGrp::handle Gui::RecentFilesAction::Private::handle
Definition at line 814 of file Action.cpp.
Referenced by Gui::RecentFilesAction::Private::Private(), and Gui::RecentFilesAction::Private::~Private().
master
RecentFilesAction* Gui::RecentFilesAction::Private::master
Definition at line 813 of file Action.cpp.
Referenced by Gui::RecentFilesAction::Private::OnChange().
updating
bool Gui::RecentFilesAction::Private::updating = false
Definition at line 815 of file Action.cpp.
Referenced by Path.Tool.Gui.Controller.TaskPanel::edit(), ArchAxis._AxisTaskPanel::edit(), ArchRoof._RoofTaskPanel::edit(), Gui::RecentFilesAction::Private::OnChange(), ArchAxis._AxisTaskPanel::update(), ArchRoof._RoofTaskPanel::update(), Path.Op.Gui.CircularHoleBase.TaskPanelHoleGeometryPage::updateBase(), and Path.Op.Gui.CircularHoleBase.TaskPanelHoleGeometryPage::updateData().
The documentation for this class was generated from the following file:
Action.cpp