FreeCAD: MeshCore::MeshComponents Class Reference
MeshCore::MeshComponents Class Reference
#include <TopoAlgorithm.h>
Classes
struct CNofFacetsCompare
Public Types
enum TMode { OverEdge, OverPoint }
Public Member Functions
MeshComponents (const MeshKernel &rclMesh)
void SearchForComponents (TMode tMode, std::vector< std::vector< FacetIndex >> &aclT) const
void SearchForComponents (TMode tMode, const std::vector< FacetIndex > &aSegment, std::vector< std::vector< FacetIndex >> &aclT) const
Detailed Description
The MeshComponents class searches for topologic independent segments of the given mesh structure.
Author
Werner Mayer
Definition at line 352 of file TopoAlgorithm.h.
Member Enumeration Documentation
TMode
enum MeshCore::MeshComponents::TMode
Enumerator
OverEdge
OverPoint
Definition at line 355 of file TopoAlgorithm.h.
Constructor & Destructor Documentation
MeshComponents()
MeshComponents::MeshComponents (const MeshKernel & rclMesh) explicit
Some important formulas:
Ne = 3Nv - Nb + 3B + 6(G-R) Nt = 2Nv - Nb + 2B + 4(G-R)
Ne <= 3Nv + 6(G-R) Nt <= 2Nv + 4(G-R)
Ne ~ 3Nv, Nv >> G, Nv >> R Nt ~ 2Nv, Nv >> G, Nv >> R
Ne = #Edges Nt = #Facets Nv = #Vertices Nb = #Boundary vertices B = #Boundaries G = Genus (Number of holes) R = #components
See also http://max-limper.de/publications/Euler/
Definition at line 1814 of file TopoAlgorithm.cpp.
Member Function Documentation
SearchForComponents() [1/2]
void MeshComponents::SearchForComponents (TMode tMode, const std::vector< FacetIndex > & aSegment, std::vector< std::vector< FacetIndex >> & aclT) const
Does basically the same as the method above escept that only the faces in aSegment are regarded.
Definition at line 1831 of file TopoAlgorithm.cpp.
References MeshCore::MeshAlgorithm::CountFacetFlag(), MeshCore::MeshKernel::CountFacets(), SCL.SimpleDataTypes::f, MeshCore::FACET_INDEX_MAX, MeshCore::MeshKernel::GetFacets(), OverEdge, OverPoint, MeshCore::MeshAlgorithm::ResetFacetsFlag(), MeshCore::MeshAlgorithm::SetFacetFlag(), MeshCore::MeshFacet::VISIT, MeshCore::MeshKernel::VisitNeighbourFacets(), and MeshCore::MeshKernel::VisitNeighbourFacetsOverCorners().
SearchForComponents() [2/2]
void MeshComponents::SearchForComponents (TMode tMode, std::vector< std::vector< FacetIndex >> & aclT) const
Searches for 'isles' of the mesh. If tMode is OverEdge then facets sharing the same edge are regarded as connected, if tMode is OverPoint then facets sharing a common point are regarded as connected.
Definition at line 1818 of file TopoAlgorithm.cpp.
References MeshCore::MeshKernel::CountFacets().
Referenced by Mesh::MeshObject::countComponents(), MeshGui::MeshSelection::deselectComponent(), MeshCore::MeshTopoAlgorithm::FindComponents(), Mesh::MeshObject::getComponents(), and MeshGui::MeshSelection::selectComponent().
The documentation for this class was generated from the following files:
TopoAlgorithm.h
TopoAlgorithm.cpp