FreeCAD: App::PropertyXLink Class Reference
App::PropertyXLink Class Reference
#include <PropertyLinks.h>
Public Member Functions
PropertyXLink (bool allowPartial=false, PropertyLinkBase *parent=nullptr)
~PropertyXLink () override
PropertyLinkBase * parent () const
void afterRestore () override
void onContainerRestored () override
void setValue (App::DocumentObject *) override
void setValue (App::DocumentObject *, const char *subname)
void setValue (std::string &&filePath, std::string &&objectName, std::vector< std::string > &&SubList, std::vector< ShadowSub > &&ShadowSubList={})
void setValue (App::DocumentObject *, std::vector< std::string > &&SubList, std::vector< ShadowSub > &&ShadowSubList={})
void setValue (App::DocumentObject *, const std::vector< std::string > &SubList, std::vector< ShadowSub > &&ShadowSubList={})
void setSubValues (std::vector< std::string > &&SubList, std::vector< ShadowSub > &&ShadowSubList={})
const char * getSubName (bool newStyle=true) const
void setSubName (const char *subname)
bool hasSubName () const
App::Document * getDocument () const
const char * getDocumentPath () const
const char * getObjectName () const
int checkRestore (std::string *msg=nullptr) const override
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
Property * Copy () const override
Returns a new copy of the property (mainly for Undo/Redo and transactions)
void Paste (const Property &from) override
Paste the value from the property (mainly for Undo/Redo and transactions)
Property * CopyOnImportExternal (const std::map< std::string, std::string > &nameMap) const override
Return a copy of the property if any changes caused by importing external object.
Property * CopyOnLabelChange (App::DocumentObject *obj, const std::string &ref, const char *newLabel) const override
Property * CopyOnLinkReplace (const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const override
PyObject * getPyObject () override
void setPyObject (PyObject *) override
void updateElementReference (DocumentObject *feature, bool reverse=false, bool notify=false) override
bool referenceChanged () const override
Test if the element reference has changed after restore.
void getLinks (std::vector< App::DocumentObject * > &objs, bool all=false, std::vector< std::string > *subs=nullptr, bool newStyle=true) const override
void getLinksTo (std::vector< App::ObjectIdentifier > &identifiers, App::DocumentObject *obj, const char *subname=nullptr, bool all=false) const override
bool adjustLink (const std::set< App::DocumentObject * > &inList) override
const std::vector< std::string > & getSubValues () const
const std::vector< ShadowSub > & getShadowSubs () const
std::vector< std::string > getSubValues (bool newStyle) const
std::vector< std::string > getSubValuesStartsWith (const char *, bool newStyle=false) const
void setAllowPartial (bool enable) override
const char * getFilePath () const
virtual bool upgrade (Base::XMLReader &reader, const char *typeName)
void setSyncSubObject (bool enable)
Public Member Functions inherited from App::PropertyLinkGlobal
PropertyLinkGlobal ()
Public Member Functions inherited from App::PropertyLink
PropertyLink ()
~PropertyLink () override
void resetLink ()
App::DocumentObject * getValue () const
App::DocumentObject * getValue (Base::Type t) const
template<typename _type >
_type getValue () const
unsigned int getMemSize () const override
const char * getEditorName () const override
Get the class name of the associated property editor item.
void breakLink (App::DocumentObject *obj, bool clear) override
Public Member Functions inherited from App::PropertyLinkBase
PropertyLinkBase ()
~PropertyLinkBase () override
void unregisterElementReference ()
Clear internal element reference registration.
void registerLabelReferences (std::vector< std::string > &&labels, bool reset=true)
void checkLabelReferences (const std::vector< std::string > &subs, bool reset=true)
void unregisterLabelReferences ()
Clear internal label references registration.
std::vector< App::DocumentObject * > linkedObjects (bool all=false) const
Helper function to return all linked objects of this property.
template<class T >
void getLinkedObjects (T &inserter, bool all=false) const
Helper function to return linked objects using an std::inserter.
void getLinkedElements (std::map< App::DocumentObject *, std::vector< std::string >> &elements, bool newStyle=true, bool all=false) const
Helper function to return a map of linked object and its subname references.
std::map< App::DocumentObject *, std::vector< std::string > > linkedElements (bool newStyle=true, bool all=false) const
Helper function to return a map of linked object and its subname references.
bool isSame (const Property &other) const override
Compare if this property has the same content as the given one.
void setAllowExternal (bool allow)
bool _updateElementReference (App::DocumentObject *feature, App::DocumentObject *obj, std::string &sub, ShadowSub &shadow, bool reverse, bool notify=false)
void _registerElementReference (App::DocumentObject *obj, std::string &sub, ShadowSub &shadow)
bool testFlag (int flag) const
void setReturnNewElement (bool enable)
void setSilentRestore (bool enable)
Public Member Functions inherited from App::Property
Property ()
~Property () override
const char * getName () const
bool hasName () const
std::string getFullName () const
short getType () const
Get the type of the property in the container.
const char * getGroup () const
Get the group of this property.
const char * getDocumentation () const
Get the documentation of this property.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
PropertyContainer * getContainer () const
Get a pointer to the PropertyContainer derived class the property belongs to.
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
void touch ()
Set the property touched.
bool isTouched () const
Test if this property is touched.
void purgeTouched ()
Reset this property touched.
unsigned long getStatus () const
return the status bits
bool testStatus (Status pos) const
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
bool isReadOnly () const
void setSinglePrecision (bool single)
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
int64_t getID () const
virtual void beforeSave () const
Property (const Property &)=delete
Property & operator= (const Property &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from App::ScopedLink
void setScope (LinkScope scope)
Set the links scope Allows to define what kind of links are allowed. Only in the Local GeoFeatureGroup, in this and all Childs or to all objects within the Glocal scope.
LinkScope getScope () const
Get the links scope Retrieve what kind of links are allowed. Only in the Local GeoFeatureGroup, in this and all Childs or to all objects within the Glocal scope.
Static Public Member Functions
static bool supportXLink (const App::Property *prop)
static bool hasXLink (const App::Document *doc)
static bool hasXLink (const std::vector< App::DocumentObject * > &objs, std::vector< App::Document * > *unsaved=nullptr)
static std::map< App::Document *, std::set< App::Document * > > getDocumentOutList (App::Document *doc=nullptr)
static std::map< App::Document *, std::set< App::Document * > > getDocumentInList (App::Document *doc=nullptr)
static void restoreDocument (const App::Document &doc)
Static Public Member Functions inherited from App::PropertyLinkBase
static std::pair< App::DocumentObject *, std::string > tryReplaceLink (const App::PropertyContainer *owner, App::DocumentObject *obj, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj, const char *sub=nullptr)
Helper functions.
static std::pair< App::DocumentObject *, std::vector< std::string > > tryReplaceLinkSubs (const App::PropertyContainer *owner, App::DocumentObject *obj, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj, const std::vector< std::string > &subs)
static void updateElementReferences (DocumentObject *feature, bool reverse=false)
Update all element references in all link properties of feature.
static const std::unordered_set< PropertyLinkBase * > & getElementReferences (DocumentObject *)
Obtain link properties that contain element references to a given object.
static void breakLinks (App::DocumentObject *link, const std::vector< App::DocumentObject * > &objs, bool clear)
static std::string tryImportSubName (const App::DocumentObject *obj, const char *sub, const App::Document *doc, const std::map< std::string, std::string > &nameMap)
static App::DocumentObject * tryImport (const App::Document *doc, const App::DocumentObject *obj, const std::map< std::string, std::string > &nameMap)
static const char * exportSubName (std::string &output, const App::DocumentObject *obj, const char *subname, bool first_obj=false)
static std::string importSubName (Base::XMLReader &reader, const char *sub, bool &restoreLabel)
static void restoreLabelReference (const App::DocumentObject *obj, std::string &sub, ShadowSub *shadow=nullptr)
static void getLabelReferences (std::vector< std::string > &labels, const char *subname)
static std::vector< std::pair< Property *, std::unique_ptr< Property > > > updateLabelReferences (App::DocumentObject *obj, const char *newLabel)
static std::string updateLabelReference (const App::DocumentObject *linked, const char *subname, App::DocumentObject *obj, const std::string &ref, const char *newLabel)
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Protected Member Functions
void unlink ()
void detach ()
void restoreLink (App::DocumentObject *)
void copyTo (PropertyXLink &other, App::DocumentObject *linked=nullptr, std::vector< std::string > *subs=nullptr) const
void aboutToSetValue () override
Gets called by all setValue() methods before the value has changed.
void hasSetValue () override
Gets called by all setValue() methods after the value has changed.
Protected Member Functions inherited from App::PropertyLinkBase
void setFlag (int flag, bool value=true)
void _getLinksTo (std::vector< App::ObjectIdentifier > &identifiers, App::DocumentObject *obj, const char *subname, const std::vector< std::string > &subs, const std::vector< PropertyLinkBase::ShadowSub > &shadows) const
Protected Member Functions inherited from App::Property
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
std::string getFileName (const char *postfix=0, const char *prefix=0) const
Return a file name suitable for saving this property.
Protected Attributes
DocInfoPtr docInfo
std::string filePath
std::string docName
std::string objectName
std::string stamp
std::vector< std::string > _SubList
std::vector< ShadowSub > _ShadowSubList
std::vector< int > _mapped
PropertyLinkBase * parentProp
std::string tmpShadow
Protected Attributes inherited from App::PropertyLink
App::DocumentObject * _pcLink {nullptr}
Protected Attributes inherited from App::PropertyLinkBase
std::bitset< 32 > _Flags
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Protected Attributes inherited from App::ScopedLink
LinkScope _pcScope = LinkScope::Local
Friends
class DocInfo
class PropertyXLinkSubList
Additional Inherited Members
Public Types inherited from App::PropertyLinkBase
enum LinkFlags {
LinkAllowExternal, LinkDetached, LinkRestoring, LinkAllowPartial,
LinkRestoreLabel, LinkSyncSubObject, LinkNewElement, LinkSilentRestore
}
using ShadowSub = ElementNamePair
Public Types inherited from App::Property
enum Status {
Touched = 0, Immutable = 1, ReadOnly = 2, Hidden = 3,
Transient = 4, MaterialEdit = 5, NoMaterialListEdit = 6, Output = 7,
LockDynamic = 8, NoModify = 9, PartialTrigger = 10, NoRecompute = 11,
Single = 12, Ordered = 13, EvalOnRestore = 14, Busy = 15,
CopyOnChange, UserEdit = 17, PropStaticBegin = 21, PropDynamic = 21,
PropNoPersist = 22, PropNoRecompute = 23, PropReadOnly = 24, PropTransient = 25,
PropHidden = 26, PropOutput = 27, PropStaticEnd = 28, User1 = 28,
User2 = 29, User3 = 30, User4 = 31
}
Public Attributes inherited from App::PropertyLinkBase
boost::signals2::signal< void(const std::string &, const std::string &)> signalUpdateElementReference
Public Attributes inherited from App::Property
boost::signals2::signal< void(const App::Property &)> signalChanged
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Link to an (sub)object in the same or different document
Definition at line 1241 of file PropertyLinks.h.
Constructor & Destructor Documentation
PropertyXLink()
PropertyXLink::PropertyXLink (bool allowPartial = false, PropertyLinkBase * parent = nullptr) explicit
Definition at line 3739 of file PropertyLinks.cpp.
References Init::parent.
~PropertyXLink()
PropertyXLink::~PropertyXLink () override
Definition at line 3750 of file PropertyLinks.cpp.
References unlink().
Member Function Documentation
aboutToSetValue()
void PropertyXLink::aboutToSetValue () override protected virtual
Gets called by all setValue() methods before the value has changed.
Reimplemented from App::Property.
Definition at line 3780 of file PropertyLinks.cpp.
References App::Property::aboutToSetChildValue(), App::Property::aboutToSetValue(), and parentProp.
Referenced by detach(), restoreLink(), and setSubName().
adjustLink()
bool PropertyXLink::adjustLink (const std::set< App::DocumentObject * > & inList) override virtual
Called to adjust the link to avoid potential cyclic dependency
Parameters
inList recursive in-list of the would-be parent
Returns
Return whether the link has been adjusted
This function tries to correct the link to avoid any (sub)object inside in-list. If the adjustment is impossible, exception will be raised
Reimplemented from App::PropertyLink.
Definition at line 4669 of file PropertyLinks.cpp.
References App::PropertyLink::_pcLink, App::ScopedLink::_pcScope, _SubList, adjustLinkSubs(), App::Hidden, App::DocumentObject::isAttachedToDocument(), Path.Post.scripts.opensbp_post::move(), setValue(), and importers.importIFCmulticore::subs.
afterRestore()
void PropertyXLink::afterRestore () override virtual
Called at the beginning of Document::afterRestore()
This function is called without dependency sorting, because some types of link property can only reconstructs the linking information inside this function.
One example use case of this function is PropertyLinkSub that uses afterRestore() to parse and restore subname references, which may contain sub-object reference from external document, and there will be special mapping required during object import.
Another example is PropertyExpressionEngine which only parse the restored expression in afterRestore(). The reason, in addition to subname mapping like PropertyLinkSub, is that it can handle document name adjustment as well. It internally relies on PropertyXLink to store the external document path for external linking. When the external document is restored, its internal name may change due to name conflict with existing documents. PropertyExpressionEngine can now auto adjust external references without any problem.
Reimplemented from App::Property.
Definition at line 4078 of file PropertyLinks.cpp.
References App::PropertyLink::_pcLink, _ShadowSubList, _SubList, SplineSurface::i, App::DocumentObject::isAttachedToDocument(), App::PropertyLinkBase::LinkRestoreLabel, App::PropertyLinkBase::restoreLabelReference(), App::PropertyLinkBase::setFlag(), and App::PropertyLinkBase::testFlag().
checkRestore()
int PropertyXLink::checkRestore (std::string * msg = nullptr) const override virtual
Test if the link is restored unchanged
Parameters
msg optional error message
Returns
For external linked object, return 2 in case the link is missing, and 1 if the time stamp has changed.
Reimplemented from App::PropertyLinkBase.
Definition at line 4026 of file PropertyLinks.cpp.
References App::PropertyLink::_pcLink, docInfo, filePath, App::DocumentObject::getFullName(), App::PropertyLinkBase::LinkAllowPartial, App::PropertyLinkBase::LinkSilentRestore, Path.Op.Surface::msg, objectName, App::Document::PartialDoc, stamp, and App::PropertyLinkBase::testFlag().
Copy()
Property * PropertyXLink::Copy () const override virtual
Returns a new copy of the property (mainly for Undo/Redo and transactions)
Reimplemented from App::PropertyLink.
Definition at line 4424 of file PropertyLinks.cpp.
References copyTo(), and buildPsets::p.
CopyOnImportExternal()
Property * PropertyXLink::CopyOnImportExternal (const std::map< std::string, std::string > & nameMap) const override virtual
Return a copy of the property if any changes caused by importing external object.
Reimplemented from App::PropertyLinkBase.
Definition at line 4347 of file PropertyLinks.cpp.
References App::PropertyLink::_pcLink, _SubList, copyTo(), App::Property::getContainer(), App::DocumentObject::isAttachedToDocument(), buildPsets::p, importers.importIFCmulticore::subs, App::PropertyLinkBase::tryImport(), App::PropertyLinkBase::tryImportSubName(), and updateLinkSubs().
CopyOnLabelChange()
Property * PropertyXLink::CopyOnLabelChange (App::DocumentObject * obj, const std::string & ref, const char * newLabel) const override virtual
Update object label reference in this property
Parameters
obj the object owner of the changing label
ref subname reference to old label
newLabel the future new label
Returns
Returns a copy of the property if its link reference is affected. The copy will later be assgiend to this property by calling its Paste().
Reimplemented from App::PropertyLinkBase.
Definition at line 4378 of file PropertyLinks.cpp.
References App::PropertyLink::_pcLink, _SubList, copyTo(), App::Property::getContainer(), App::DocumentObject::isAttachedToDocument(), buildPsets::p, importers.importIFCmulticore::subs, App::PropertyLinkBase::updateLabelReference(), and updateLinkSubs().
CopyOnLinkReplace()
Property * PropertyXLink::CopyOnLinkReplace (const App::DocumentObject * parent, App::DocumentObject * oldObj, App::DocumentObject * newObj) const override virtual
Return a copy of the property if the link replacement affects this property
Parameters
owner the parent object whose link property is to be replace. Note that The parent may not be the container of this property. Link sub property can use this opportunity to adjust its relative links.
oldObj object to be replaced
newObj object to replace with
Returns
Return a copy of the property that is adjusted for the link replacement operation.
Reimplemented from App::PropertyLink.
Definition at line 4365 of file PropertyLinks.cpp.
References App::PropertyLink::_pcLink, _SubList, copyTo(), App::Property::getContainer(), buildPsets::p, parent(), and App::PropertyLinkBase::tryReplaceLinkSubs().
copyTo()
void PropertyXLink::copyTo (PropertyXLink & other, App::DocumentObject * linked = nullptr, std::vector< std::string > * subs = nullptr) const protected
Definition at line 4395 of file PropertyLinks.cpp.
References App::PropertyLinkBase::_Flags, App::PropertyLink::_pcLink, _ShadowSubList, _SubList, docInfo, docName, filePath, App::DocumentObject::getDocument(), App::Document::getName(), App::DocumentObject::getNameInDocument(), App::DocumentObject::isAttachedToDocument(), Path.Post.scripts.opensbp_post::move(), objectName, and importers.importIFCmulticore::subs.
Referenced by Copy(), CopyOnImportExternal(), App::PropertyXLinkSubList::CopyOnImportExternal(), CopyOnLabelChange(), App::PropertyXLinkSubList::CopyOnLabelChange(), CopyOnLinkReplace(), and App::PropertyXLinkSubList::CopyOnLinkReplace().
detach()
void PropertyXLink::detach () protected
Definition at line 3770 of file PropertyLinks.cpp.
References App::PropertyLink::_pcLink, aboutToSetValue(), docInfo, hasSetValue(), App::PropertyLink::resetLink(), and updateElementReference().
getDocument()
App::Document * PropertyXLink::getDocument () const
Definition at line 3999 of file PropertyLinks.cpp.
References docInfo.
getDocumentInList()
std::map< App::Document *, std::set< App::Document * > > PropertyXLink::getDocumentInList (App::Document * doc = nullptr) static
Definition at line 4532 of file PropertyLinks.cpp.
References _DocInfoMap, toolbit-attributes::doc, App::DocumentObject::getDocument(), App::Hidden, App::DocumentObject::isAttachedToDocument(), App::Property::PropNoPersist, App::Property::PropTransient, App::DocumentObject::testStatus(), App::Property::Transient, and TestSpreadsheet::v.
Referenced by Gui::Document::canClose(), and Gui::Document::detachView().
getDocumentOutList()
std::map< App::Document *, std::set< App::Document * > > PropertyXLink::getDocumentOutList (App::Document * doc = nullptr) static
Definition at line 4507 of file PropertyLinks.cpp.
References _DocInfoMap, toolbit-attributes::doc, App::DocumentObject::getDocument(), App::Hidden, App::DocumentObject::isAttachedToDocument(), App::Property::PropNoPersist, App::Property::PropTransient, App::DocumentObject::testStatus(), App::Property::Transient, and TestSpreadsheet::v.
Referenced by StdCmdDelete::activated(), and App::Document::getDependentDocuments().
getDocumentPath()
const char * PropertyXLink::getDocumentPath () const
Definition at line 4004 of file PropertyLinks.cpp.
References docInfo, and filePath.
getFilePath()
const char* App::PropertyXLink::getFilePath () const inline
Definition at line 1355 of file PropertyLinks.h.
References Path.Preferences::filePath().
getLinks()
void PropertyXLink::getLinks (std::vector< App::DocumentObject * > & objs, bool all = false, std::vector< std::string > * subs = nullptr, bool newStyle = true) const override virtual
Obtain the linked objects
Parameters
objs hold the returned linked objects on output
all if true, then return all the linked object regardless of this LinkScope. If false, then return only if the LinkScope is not hidden.
sub if given, then return subname references.
newStyle whether to return new or old style subname reference
Reimplemented from App::PropertyLink.
Definition at line 4644 of file PropertyLinks.cpp.
References App::PropertyLink::_pcLink, App::ScopedLink::_pcScope, _ShadowSubList, _SubList, getSubValues(), App::Hidden, App::DocumentObject::isAttachedToDocument(), replaceobj::objs, and importers.importIFCmulticore::subs.
getLinksTo()
void PropertyXLink::getLinksTo (std::vector< App::ObjectIdentifier > & identifiers, App::DocumentObject * obj, const char * subname = nullptr, bool all = false) const override virtual
Obtain identifiers from this link property that link to a given object
Parameters
identifiers holds the returned identifier to reference the given object
obj the referenced object
subname optional subname reference
all if true, then return all the references regardless of this LinkScope. If false, then return only if the LinkScope is not hidden.
Reimplemented from App::PropertyLink.
Definition at line 4657 of file PropertyLinks.cpp.
References App::PropertyLinkBase::_getLinksTo(), App::PropertyLink::_pcLink, App::ScopedLink::_pcScope, _ShadowSubList, _SubList, and App::Hidden.
getObjectName()
const char * PropertyXLink::getObjectName () const
Definition at line 4009 of file PropertyLinks.cpp.
References objectName.
getPyObject()
PyObject * PropertyXLink::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from App::PropertyLink.
Reimplemented in App::PropertyXLinkSub.
Definition at line 4555 of file PropertyLinks.cpp.
References App::PropertyLink::_pcLink, App::DocumentObject::getPyObject(), App::PropertyString::getPyObject(), getSubValues(), SplineSurface::i, Py::new_reference_to(), Py_Return, App::PropertyString::setValue(), and importers.importIFCmulticore::subs.
getShadowSubs()
const std::vector<ShadowSub>& App::PropertyXLink::getShadowSubs () const inline
Definition at line 1346 of file PropertyLinks.h.
getSubName()
const char * PropertyXLink::getSubName (bool newStyle = true) const
Definition at line 4636 of file PropertyLinks.cpp.
References _ShadowSubList, _SubList, getSubNameWithStyle(), and tmpShadow.
getSubValues() [1/2]
const std::vector<std::string>& App::PropertyXLink::getSubValues () const inline
Definition at line 1342 of file PropertyLinks.h.
Referenced by App::PropertyXLinkSubList::CopyOnLinkReplace(), App::GeoFeature::getGlobalPlacement(), getLinks(), getPyObject(), App::PropertyXLinkSub::getPyObject(), and PartDesign::SubShapeBinder::update().
getSubValues() [2/2]
std::vector< std::string > PropertyXLink::getSubValues (bool newStyle) const
Definition at line 4686 of file PropertyLinks.cpp.
References _ShadowSubList, _SubList, getSubNameWithStyle(), and SplineSurface::i.
getSubValuesStartsWith()
std::vector< std::string > PropertyXLink::getSubValuesStartsWith (const char * starter, bool newStyle = false) const
Definition at line 4698 of file PropertyLinks.cpp.
References _SubList.
hasSetValue()
void PropertyXLink::hasSetValue () override protected virtual
Gets called by all setValue() methods after the value has changed.
Reimplemented from App::PropertyLinkBase.
Definition at line 3790 of file PropertyLinks.cpp.
References App::Property::hasSetChildValue(), App::PropertyLinkBase::hasSetValue(), and parentProp.
Referenced by detach(), restoreLink(), setSubName(), and updateElementReference().
hasSubName()
bool App::PropertyXLink::hasSubName () const inline
Definition at line 1280 of file PropertyLinks.h.
hasXLink() [1/2]
bool PropertyXLink::hasXLink (const App::Document * doc) static
Definition at line 4469 of file PropertyLinks.cpp.
References _DocInfoMap, toolbit-attributes::doc, and TestSpreadsheet::v.
Referenced by StdCmdDuplicateSelection::activated(), App::Document::copyObject(), Gui::MainWindow::createMimeDataFromSelection(), hasXLink(), StdCmdLinkImportAll::isActive(), and App::Document::mustExecute().
hasXLink() [2/2]
bool PropertyXLink::hasXLink (const std::vector< App::DocumentObject * > & objs, std::vector< App::Document * > * unsaved = nullptr) static
Definition at line 4479 of file PropertyLinks.cpp.
References hasXLink(), src.Mod.Test.testPathArray::o, and replaceobj::objs.
onContainerRestored()
void PropertyXLink::onContainerRestored () override virtual
Called before calling DocumentObject::onDocumentRestored()
This function is called after finished calling Property::afterRestore() of all properties of objects. By then, the object dependency information is assumed ready. So, unlike Property::afterRestore(), this function is called on objects with dependency order.
Reimplemented from App::Property.
Definition at line 4090 of file PropertyLinks.cpp.
References App::PropertyLink::_pcLink, App::PropertyLinkBase::_registerElementReference(), _ShadowSubList, _SubList, SplineSurface::i, and App::DocumentObject::isAttachedToDocument().
Referenced by setSubValues().
parent()
PropertyLinkBase* App::PropertyXLink::parent () const inline
Definition at line 1250 of file PropertyLinks.h.
Referenced by CopyOnLinkReplace(), and Restore().
Paste()
void PropertyXLink::Paste (const Property & from) override virtual
Paste the value from the property (mainly for Undo/Redo and transactions)
Reimplemented from App::PropertyLink.
Definition at line 4431 of file PropertyLinks.cpp.
References toolbit-attributes::doc, FC_WARN, App::GetApplication(), Base::Persistence::getClassTypeId(), App::Application::getDocument(), Base::BaseClass::isDerivedFrom(), App::PropertyLinkBase::LinkAllowPartial, App::PropertyLinkBase::setFlag(), and setValue().
referenceChanged()
bool PropertyXLink::referenceChanged () const override virtual
Test if the element reference has changed after restore.
Reimplemented from App::PropertyLinkBase.
Definition at line 4117 of file PropertyLinks.cpp.
References _mapped.
Restore()
void PropertyXLink::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Reimplemented from App::PropertyLink.
Definition at line 4243 of file PropertyLinks.cpp.
References _mapped, ATTR_MAPPED, ATTR_SHADOW, ATTR_SHADOWED, src.Mod.AddonManager.NetworkManager::count, FC_WARN, DrawingExample::file, App::Property::getContainer(), App::Document::getObject(), SplineSurface::i, IGNORE_SHADOW, App::PropertyLinkBase::importSubName(), App::PropertyLinkBase::LinkAllowPartial, App::PropertyLinkBase::LinkRestoreLabel, Path.Post.scripts.opensbp_post::move(), parent(), TechDrawTools.TaskFillTemplateFields::reader, App::PropertyLinkBase::setFlag(), setValue(), stamp, and importers.importIFCmulticore::subs.
restoreDocument()
void PropertyXLink::restoreDocument (const App::Document & doc) static
Definition at line 4501 of file PropertyLinks.cpp.
References toolbit-attributes::doc, and App::DocInfo::restoreDocument().
Referenced by App::Application::openDocuments().
restoreLink()
void PropertyXLink::restoreLink (App::DocumentObject * lValue) protected
Definition at line 3839 of file PropertyLinks.cpp.
References App::DocumentObject::_addBackLink(), App::PropertyLink::_pcLink, App::ScopedLink::_pcScope, aboutToSetValue(), App::Destroy, docInfo, App::Property::getContainer(), hasSetValue(), App::Hidden, App::PropertyLinkBase::LinkDetached, App::PropertyLinkBase::LinkRestoring, App::PropertyLinkBase::setFlag(), stamp, and updateElementReference().
Save()
void PropertyXLink::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Reimplemented from App::PropertyLink.
Definition at line 4122 of file PropertyLinks.cpp.
References App::PropertyLink::_pcLink, _ShadowSubList, _SubList, ATTR_MAPPED, ATTR_SHADOW, ATTR_SHADOWED, Base::Writer::decInd(), docInfo, Base::Persistence::encodeAttribute(), App::PropertyLinkBase::exportSubName(), FC_WARN, filePath, App::Property::getContainer(), App::DocInfo::getDocPath(), App::DocumentObject::getExportName(), SplineSurface::i, Base::Writer::incInd(), Base::Writer::ind(), App::DocumentObject::isExporting(), App::PropertyLinkBase::LinkAllowPartial, objectName, Base::Writer::Stream(), and App::PropertyLinkBase::testFlag().
setAllowPartial()
void PropertyXLink::setAllowPartial (bool enable) override virtual
Reimplemented from App::PropertyLinkBase.
Definition at line 4712 of file PropertyLinks.cpp.
References App::PropertyLink::_pcLink, docInfo, filePath, App::GetApplication(), App::Property::getContainer(), App::Application::isRestoring(), App::PropertyLinkBase::LinkAllowPartial, objectName, App::Application::openDocument(), App::Document::PartialDoc, and App::PropertyLinkBase::setFlag().
setPyObject()
void PropertyXLink::setPyObject (PyObject * value) override virtual
Reimplemented from App::PropertyLink.
Definition at line 4583 of file PropertyLinks.cpp.
References App::PropertyString::getStrValue(), SplineSurface::i, Path.Post.scripts.opensbp_post::move(), App::PropertyString::setPyObject(), setValue(), and importers.importIFCmulticore::subs.
setSubName()
void PropertyXLink::setSubName (const char * subname)
Definition at line 3800 of file PropertyLinks.cpp.
References aboutToSetValue(), hasSetValue(), Path.Post.scripts.opensbp_post::move(), setSubValues(), and importers.importIFCmulticore::subs.
setSubValues()
void PropertyXLink::setSubValues (std::vector< std::string > && SubList, std::vector< ShadowSub > && ShadowSubList = {})
Definition at line 3811 of file PropertyLinks.cpp.
References _ShadowSubList, _SubList, App::PropertyLinkBase::checkLabelReferences(), Path.Post.scripts.opensbp_post::move(), onContainerRestored(), importers.importIFCmulticore::subs, and updateElementReference().
Referenced by setSubName().
setSyncSubObject()
void PropertyXLink::setSyncSubObject (bool enable)
Definition at line 3755 of file PropertyLinks.cpp.
References App::PropertyLinkBase::_Flags, and App::PropertyLinkBase::LinkSyncSubObject.
setValue() [1/5]
void PropertyXLink::setValue (App::DocumentObject * lValue) override virtual
Sets the property
Reimplemented from App::PropertyLink.
Definition at line 3825 of file PropertyLinks.cpp.
Referenced by adjustLink(), PartDesign::SubShapeBinder::clearCopiedObjects(), Paste(), Restore(), setPyObject(), setValue(), PartDesign::SubShapeBinder::update(), and App::PropertyXLinkSub::upgrade().
setValue() [2/5]
void PropertyXLink::setValue (App::DocumentObject * lValue, const char * subname)
Definition at line 3830 of file PropertyLinks.cpp.
References Path.Post.scripts.opensbp_post::move(), setValue(), and importers.importIFCmulticore::subs.
setValue() [3/5]
void App::PropertyXLink::setValue (App::DocumentObject * , const std::vector< std::string > & SubList, std::vector< ShadowSub > && ShadowSubList = {})
setValue() [4/5]
void App::PropertyXLink::setValue (App::DocumentObject * , std::vector< std::string > && SubList, std::vector< ShadowSub > && ShadowSubList = {})
setValue() [5/5]
void App::PropertyXLink::setValue (std::string && filePath, std::string && objectName, std::vector< std::string > && SubList, std::vector< ShadowSub > && ShadowSubList = {})
supportXLink()
bool PropertyXLink::supportXLink (const App::Property * prop) static
Definition at line 4462 of file PropertyLinks.cpp.
References Base::Persistence::getClassTypeId(), and Base::BaseClass::isDerivedFrom().
Referenced by Gui::Dialog::DlgPropertyLink::init().
unlink()
void PropertyXLink::unlink () protected
Definition at line 3760 of file PropertyLinks.cpp.
References docInfo, objectName, and App::PropertyLink::resetLink().
Referenced by ~PropertyXLink().
updateElementReference()
void PropertyXLink::updateElementReference (DocumentObject * feature, bool reverse = false, bool notify = false) override virtual
Link type property interface APIs These APIs are moved here so that any type of property can have the property link behavior, e.g. the PropertyExpressionEngine Called to update the element reference of this link property
See also
_updateElementReference()
Reimplemented from App::PropertyLinkBase.
Definition at line 4100 of file PropertyLinks.cpp.
References _mapped, App::PropertyLink::_pcLink, _ShadowSubList, _SubList, hasSetValue(), femsolver.signal::notify(), and updateLinkReference().
Referenced by detach(), restoreLink(), and setSubValues().
upgrade()
bool PropertyXLink::upgrade (Base::XMLReader & reader, const char * typeName) virtual
Reimplemented in App::PropertyXLinkSub.
Definition at line 4014 of file PropertyLinks.cpp.
References FC_ERR, Base::Persistence::getClassTypeId(), App::Property::getName(), TechDrawTools.TaskFillTemplateFields::reader, and App::PropertyLink::Restore().
Referenced by App::PropertyXLinkSub::upgrade().
Friends And Related Function Documentation
DocInfo
friend class DocInfo friend
Definition at line 1312 of file PropertyLinks.h.
PropertyXLinkSubList
friend class PropertyXLinkSubList friend
Definition at line 1378 of file PropertyLinks.h.
Member Data Documentation
_mapped
std::vector<int> App::PropertyXLink::_mapped protected
Definition at line 1388 of file PropertyLinks.h.
Referenced by referenceChanged(), Restore(), and updateElementReference().
_ShadowSubList
std::vector<ShadowSub> App::PropertyXLink::_ShadowSubList protected
Definition at line 1387 of file PropertyLinks.h.
Referenced by afterRestore(), copyTo(), getLinks(), getLinksTo(), getSubName(), getSubValues(), onContainerRestored(), Save(), setSubValues(), and updateElementReference().
_SubList
std::vector<std::string> App::PropertyXLink::_SubList protected
Definition at line 1386 of file PropertyLinks.h.
Referenced by adjustLink(), afterRestore(), CopyOnImportExternal(), CopyOnLabelChange(), CopyOnLinkReplace(), App::PropertyXLinkSubList::CopyOnLinkReplace(), copyTo(), getLinks(), getLinksTo(), getSubName(), getSubValues(), getSubValuesStartsWith(), onContainerRestored(), Save(), setSubValues(), and updateElementReference().
docInfo
DocInfoPtr App::PropertyXLink::docInfo protected
Definition at line 1381 of file PropertyLinks.h.
Referenced by checkRestore(), copyTo(), detach(), getDocument(), getDocumentPath(), restoreLink(), Save(), setAllowPartial(), and unlink().
docName
std::string App::PropertyXLink::docName protected
Definition at line 1383 of file PropertyLinks.h.
Referenced by copyTo().
filePath
std::string App::PropertyXLink::filePath protected
Definition at line 1382 of file PropertyLinks.h.
Referenced by checkRestore(), copyTo(), getDocumentPath(), Save(), and setAllowPartial().
objectName
std::string App::PropertyXLink::objectName protected
Definition at line 1384 of file PropertyLinks.h.
Referenced by checkRestore(), copyTo(), getObjectName(), Save(), setAllowPartial(), and unlink().
parentProp
PropertyLinkBase* App::PropertyXLink::parentProp protected
Definition at line 1389 of file PropertyLinks.h.
Referenced by aboutToSetValue(), and hasSetValue().
stamp
std::string App::PropertyXLink::stamp protected
Definition at line 1385 of file PropertyLinks.h.
Referenced by checkRestore(), Restore(), and restoreLink().
tmpShadow
std::string App::PropertyXLink::tmpShadow mutable protected
Definition at line 1390 of file PropertyLinks.h.
Referenced by getSubName().
The documentation for this class was generated from the following files:
PropertyLinks.h
PropertyLinks.cpp