FreeCAD: TechDraw::AOC Class Reference
TechDraw::AOC Class Reference
#include <Geometry.h>
Public Member Functions
AOC (const TopoDS_Edge &e)
AOC (Base::Vector3d c, double r, double s, double e)
AOC ()
~AOC () override=default
BaseGeomPtr copy () override
double getStartAngle () override
double getEndAngle () override
bool clockwiseAngle () override
void clockwiseAngle (bool direction) override
std::string toString () const override
void Save (Base::Writer &w) const override
void Restore (Base::XMLReader &r) override
bool isOnArc (Base::Vector3d v)
bool intersectsArc (Base::Vector3d p1, Base::Vector3d p2)
double distToArc (Base::Vector3d p)
Public Member Functions inherited from TechDraw::Circle
Circle ()
Circle (const TopoDS_Edge &e)
Circle (Base::Vector3d center, double radius)
~Circle () override=default
Public Member Functions inherited from TechDraw::BaseGeom
BaseGeom ()
virtual ~BaseGeom ()=default
std::vector< Base::Vector3d > findEndPoints ()
Base::Vector3d getStartPoint ()
Base::Vector3d getEndPoint ()
Base::Vector3d getMidPoint ()
std::vector< Base::Vector3d > getQuads ()
double minDist (Base::Vector3d p)
Base::Vector3d nearPoint (Base::Vector3d p)
Base::Vector3d nearPoint (const BaseGeomPtr p)
find point on me nearest to p
bool closed ()
std::string dump ()
std::vector< Base::Vector3d > intersection (TechDraw::BaseGeomPtr geom2)
boost::uuids::uuid getTag () const
virtual std::string getTagAsString () const
std::string geomTypeName ()
BaseGeomPtr inverted ()
GeomType getGeomType ()
void setGeomType (GeomType type)
edgeClass getClassOfEdge ()
void setClassOfEdge (edgeClass newClass)
bool getHlrVisible ()
void setHlrVisible (bool state)
bool getReversed ()
void setReversed (bool state)
int getRef3d ()
void setRef3d (int ref)
TopoDS_Edge getOCCEdge ()
void setOCCEdge (TopoDS_Edge newEdge)
bool getCosmetic ()
void setCosmetic (bool state)
int source ()
void source (int s)
int sourceIndex ()
void sourceIndex (int si)
std::string getCosmeticTag ()
void setCosmeticTag (std::string t)
Part::TopoShape asTopoShape (double scale=1.0)
Public Attributes
Base::Vector3d startPnt
Base::Vector3d endPnt
Base::Vector3d midPnt
double startAngle
Angle in radian ??angle with horizontal?
double endAngle
Angle in radian.
bool cw
Arc is drawn clockwise from startAngle to endAngle if true, counterclockwise if false.
bool largeArc
Public Attributes inherited from TechDraw::Circle
Base::Vector3d center
double radius
Additional Inherited Members
Static Public Member Functions inherited from TechDraw::BaseGeom
static BaseGeomPtr baseFactory (TopoDS_Edge edge, bool isCosmetic=false)
Convert 1 OCC edge into 1 BaseGeom (static factory method)
static bool validateEdge (TopoDS_Edge edge)
static TopoDS_Edge completeEdge (const TopoDS_Edge &edge)
Protected Member Functions inherited from TechDraw::BaseGeom
void createNewTag ()
Protected Attributes inherited from TechDraw::BaseGeom
GeomType geomType
ExtractionType extractType
edgeClass classOfEdge
bool hlrVisible
bool reversed
int ref3D
TopoDS_Edge occEdge
bool cosmetic
int m_source
int m_sourceIndex
std::string cosmeticTag
boost::uuids::uuid tag
Detailed Description
Definition at line 238 of file TechDraw/App/Geometry.h.
Constructor & Destructor Documentation
AOC() [1/3]
AOC::AOC (const TopoDS_Edge & e) explicit
Definition at line 803 of file TechDraw/App/Geometry.cpp.
References a, TechDraw::ARCOFCIRCLE, SCL.SimpleDataTypes::c, cw, SCL.SimpleDataTypes::e, endAngle, endPnt, SCL.SimpleDataTypes::f, Base::fmod(), TechDraw::BaseGeom::geomType, RobotExample::l, largeArc, test::m, M_PI, midPnt, TechDraw::BaseGeom::reversed, toolbit-attributes::s, startAngle, startPnt, TechDraw::DrawUtil::toVector3d(), and draftgeoutils.general::v1().
AOC() [2/3]
AOC::AOC (Base::Vector3d c, double r, double s, double e)
Definition at line 835 of file TechDraw/App/Geometry.cpp.
References a, TechDraw::ARCOFCIRCLE, SCL.SimpleDataTypes::c, TechDraw::Circle::center, cw, endAngle, endPnt, SCL.SimpleDataTypes::f, Base::fmod(), TechDraw::BaseGeom::geomType, Handle(), RobotExample::l, largeArc, test::m, M_PI, midPnt, TechDraw::BaseGeom::occEdge, TechDraw::Circle::radius, TechDraw::BaseGeom::reversed, toolbit-attributes::s, startAngle, startPnt, TechDraw::DrawUtil::toVector3d(), and draftgeoutils.general::v1().
AOC() [3/3]
AOC::AOC ()
Definition at line 884 of file TechDraw/App/Geometry.cpp.
References TechDraw::ARCOFCIRCLE, cw, endAngle, endPnt, TechDraw::BaseGeom::geomType, largeArc, M_PI, midPnt, startAngle, and startPnt.
~AOC()
TechDraw::AOC::~AOC () override default
Member Function Documentation
clockwiseAngle() [1/2]
bool TechDraw::AOC::clockwiseAngle () inline override virtual
Reimplemented from TechDraw::BaseGeom.
Definition at line 250 of file TechDraw/App/Geometry.h.
Referenced by copy().
clockwiseAngle() [2/2]
void TechDraw::AOC::clockwiseAngle (bool direction) inline override virtual
Reimplemented from TechDraw::BaseGeom.
Definition at line 251 of file TechDraw/App/Geometry.h.
copy()
BaseGeomPtr AOC::copy () override virtual
Reimplemented from TechDraw::BaseGeom.
Definition at line 913 of file TechDraw/App/Geometry.cpp.
References importers.importWebGL::base, clockwiseAngle(), TechDraw::BaseGeom::copy(), endAngle, endPnt, largeArc, startAngle, and startPnt.
distToArc()
double AOC::distToArc (Base::Vector3d p)
Definition at line 929 of file TechDraw/App/Geometry.cpp.
References TechDraw::BaseGeom::minDist(), and buildPsets::p.
getEndAngle()
double TechDraw::AOC::getEndAngle () inline override virtual
Reimplemented from TechDraw::BaseGeom.
Definition at line 249 of file TechDraw/App/Geometry.h.
getStartAngle()
double TechDraw::AOC::getStartAngle () inline override virtual
Reimplemented from TechDraw::BaseGeom.
Definition at line 248 of file TechDraw/App/Geometry.h.
intersectsArc()
bool AOC::intersectsArc (Base::Vector3d p1, Base::Vector3d p2)
Definition at line 935 of file TechDraw/App/Geometry.cpp.
References TechDraw::BaseGeom::minDist(), TechDraw::BaseGeom::occEdge, draftgeoutils.general::v1(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
isOnArc()
bool AOC::isOnArc (Base::Vector3d v)
Definition at line 898 of file TechDraw/App/Geometry.cpp.
References TechDraw::BaseGeom::minDist(), TechDraw::BaseGeom::occEdge, buildPsets::p, and TestSpreadsheet::v.
Restore()
void AOC::Restore (Base::XMLReader & r) override virtual
Reimplemented from TechDraw::Circle.
Definition at line 1002 of file TechDraw/App/Geometry.cpp.
References cw, endAngle, endPnt, largeArc, midPnt, TechDrawTools.TaskFillTemplateFields::reader, TechDraw::Circle::Restore(), startAngle, startPnt, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Save()
void AOC::Save (Base::Writer & w) const override virtual
Reimplemented from TechDraw::Circle.
Definition at line 976 of file TechDraw/App/Geometry.cpp.
References SCL.SimpleDataTypes::c, cw, endAngle, endPnt, Base::Writer::ind(), src.Mod.PartDesign.Scripts.Gear::la, largeArc, midPnt, TechDraw::Circle::Save(), startAngle, startPnt, Base::Writer::Stream(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
toString()
std::string AOC::toString () const override virtual
Reimplemented from TechDraw::Circle.
Definition at line 954 of file TechDraw/App/Geometry.cpp.
References cw, endAngle, endPnt, largeArc, midPnt, startAngle, startPnt, TechDraw::Circle::toString(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Member Data Documentation
cw
bool TechDraw::AOC::cw
Arc is drawn clockwise from startAngle to endAngle if true, counterclockwise if false.
Definition at line 268 of file TechDraw/App/Geometry.h.
Referenced by AOC(), Restore(), Save(), and toString().
endAngle
double TechDraw::AOC::endAngle
Angle in radian.
Definition at line 265 of file TechDraw/App/Geometry.h.
Referenced by AOC(), copy(), Restore(), Save(), and toString().
endPnt
Base::Vector3d TechDraw::AOC::endPnt
Definition at line 258 of file TechDraw/App/Geometry.h.
Referenced by AOC(), copy(), Restore(), Save(), and toString().
largeArc
bool TechDraw::AOC::largeArc
Definition at line 269 of file TechDraw/App/Geometry.h.
Referenced by AOC(), copy(), Restore(), Save(), and toString().
midPnt
Base::Vector3d TechDraw::AOC::midPnt
Definition at line 259 of file TechDraw/App/Geometry.h.
Referenced by AOC(), Restore(), Save(), and toString().
startAngle
double TechDraw::AOC::startAngle
Angle in radian ??angle with horizontal?
Definition at line 262 of file TechDraw/App/Geometry.h.
Referenced by AOC(), copy(), Restore(), Save(), and toString().
startPnt
Base::Vector3d TechDraw::AOC::startPnt
Definition at line 257 of file TechDraw/App/Geometry.h.
Referenced by AOC(), copy(), Restore(), Save(), and toString().
The documentation for this class was generated from the following files:
TechDraw/App/Geometry.h
TechDraw/App/Geometry.cpp