FreeCAD: ifc4.ifcstructuralloadtemperature Class Reference
ifc4.ifcstructuralloadtemperature Class Reference
Public Member Functions
def __init__ (self, inherited0__name, deltatconstant, deltaty, deltatz)
def deltatconstant ()
def deltaty ()
def deltatz ()
Public Member Functions inherited from ifc4.ifcstructuralloadstatic
def __init__ (self, inherited0__name)
Public Member Functions inherited from ifc4.ifcstructuralload
def name ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
deltatconstant
deltaty
deltatz
Public Attributes inherited from ifc4.ifcstructuralload
name
Detailed Description
Entity ifcstructuralloadtemperature definition.
:param deltatconstant
:type deltatconstant:ifcthermodynamictemperaturemeasure
:param deltaty
:type deltaty:ifcthermodynamictemperaturemeasure
:param deltatz
:type deltatz:ifcthermodynamictemperaturemeasure
Definition at line 35725 of file ifc4.py.
Constructor & Destructor Documentation
__init__()
def ifc4.ifcstructuralloadtemperature.__init__ (self, inherited0__name, deltatconstant, deltaty, deltatz)
Definition at line 35737 of file ifc4.py.
Member Function Documentation
deltatconstant()
def ifc4.ifcstructuralloadtemperature.deltatconstant ()
Definition at line 35744 of file ifc4.py.
References ifc4.ifcstructuralloadtemperature._deltatconstant, SCL.TypeChecker.check_type(), and ifc4.ifcstructuralloadtemperature.deltatconstant.
deltaty()
def ifc4.ifcstructuralloadtemperature.deltaty ()
Definition at line 35758 of file ifc4.py.
References ifc4.ifcstructuralloadtemperature._deltaty, SCL.TypeChecker.check_type(), and ifc4.ifcstructuralloadtemperature.deltaty.
deltatz()
def ifc4.ifcstructuralloadtemperature.deltatz ()
Definition at line 35772 of file ifc4.py.
References ifc4.ifcstructuralloadtemperature._deltatz, SCL.TypeChecker.check_type(), and ifc4.ifcstructuralloadtemperature.deltatz.
Member Data Documentation
deltatconstant
ifc4.ifcstructuralloadtemperature.deltatconstant
Definition at line 35739 of file ifc4.py.
Referenced by ifc4.ifcstructuralloadtemperature.deltatconstant().
deltaty
ifc4.ifcstructuralloadtemperature.deltaty
Definition at line 35740 of file ifc4.py.
Referenced by ifc4.ifcstructuralloadtemperature.deltaty().
deltatz
ifc4.ifcstructuralloadtemperature.deltatz
Definition at line 35741 of file ifc4.py.
Referenced by ifc4.ifcstructuralloadtemperature.deltatz().
The documentation for this class was generated from the following file:
ifc4.py