FreeCAD: TechDraw::EdgeWalker Class Reference
TechDraw::EdgeWalker Class Reference
#include <EdgeWalker.h>
Public Member Functions
EdgeWalker ()
virtual ~EdgeWalker ()
bool loadEdges (std::vector< TechDraw::WalkerEdge > &edges)
bool loadEdges (std::vector< TopoDS_Edge > edges)
bool setSize (std::size_t size)
std::vector< TopoDS_Wire > execute (std::vector< TopoDS_Edge > edgeList, bool biggie=true)
ewWireList getResult ()
std::vector< TopoDS_Wire > getResultWires ()
std::vector< TopoDS_Wire > getResultNoDups ()
std::vector< TopoDS_Vertex > makeUniqueVList (std::vector< TopoDS_Edge > edges)
std::vector< WalkerEdge > makeWalkerEdges (std::vector< TopoDS_Edge > edges, std::vector< TopoDS_Vertex > verts)
make WalkerEdges (unique Vertex index pairs) from edge list
size_t findUniqueVert (TopoDS_Vertex vx, std::vector< TopoDS_Vertex > &uniqueVert)
std::vector< TopoDS_Wire > sortStrip (std::vector< TopoDS_Wire > fw, bool includeBiggest)
std::vector< TopoDS_Wire > sortWiresBySize (std::vector< TopoDS_Wire > &w, bool reverse=false)
std::vector< int > getEmbeddingRowIx (int v)
get incidence row as edge indices for v'th vertex
std::vector< edge_t > getEmbeddingRow (int v)
get incidence row as edgeDescriptors for v'th vertex
std::vector< embedItem > makeEmbedding (const std::vector< TopoDS_Edge > edges, const std::vector< TopoDS_Vertex > uniqueVList)
Static Public Member Functions
static TopoDS_Wire makeCleanWire (std::vector< TopoDS_Edge > edges, double tol=0.10)
make a clean wire with sorted, oriented, connected, etc edges
Protected Member Functions
bool prepare ()
Static Protected Member Functions
static bool wireCompare (const TopoDS_Wire &w1, const TopoDS_Wire &w2)
return true if w1 enclosed area is bigger than w2 enclosed area
Protected Attributes
std::vector< TechDraw::WalkerEdge > m_saveWalkerEdges
std::vector< TopoDS_Edge > m_saveInEdges
std::vector< embedItem > m_embedding
Detailed Description
Definition at line 171 of file EdgeWalker.h.
Constructor & Destructor Documentation
EdgeWalker()
EdgeWalker::EdgeWalker ()
Definition at line 94 of file EdgeWalker.cpp.
~EdgeWalker()
EdgeWalker::~EdgeWalker () virtual
Definition at line 98 of file EdgeWalker.cpp.
Member Function Documentation
execute()
std::vector< TopoDS_Wire > EdgeWalker::execute (std::vector< TopoDS_Edge > edgeList, bool biggie = true)
Definition at line 172 of file EdgeWalker.cpp.
Referenced by TechDraw::DrawViewPart::findFacesNew(), TechDraw::DrawViewPart::findFacesOld(), and FeaturePython.DistanceBolt::onChanged().
findUniqueVert()
size_t EdgeWalker::findUniqueVert (TopoDS_Vertex vx, std::vector< TopoDS_Vertex > & uniqueVert)
Definition at line 329 of file EdgeWalker.cpp.
References EWTOLERANCE, Base::Vector3< float_type >::IsEqual(), TestSpreadsheet::v, and TechDraw::DrawUtil::vertex2Vector().
getEmbeddingRow()
std::vector< edge_t > EdgeWalker::getEmbeddingRow (int v)
get incidence row as edgeDescriptors for v'th vertex
Definition at line 437 of file EdgeWalker.cpp.
References TechDraw::embedItem::incidenceList, result, and TestSpreadsheet::v.
getEmbeddingRowIx()
std::vector< int > EdgeWalker::getEmbeddingRowIx (int v)
get incidence row as edge indices for v'th vertex
Definition at line 425 of file EdgeWalker.cpp.
References TechDraw::embedItem::incidenceList, result, and TestSpreadsheet::v.
getResult()
ewWireList EdgeWalker::getResult ()
Definition at line 183 of file EdgeWalker.cpp.
getResultNoDups()
std::vector< TopoDS_Wire > EdgeWalker::getResultNoDups ()
Definition at line 213 of file EdgeWalker.cpp.
References SCL.SimpleDataTypes::e, EWTOLERANCE, result, and src.Mod.PartDesign.fcgear.svggear::w.
getResultWires()
std::vector< TopoDS_Wire > EdgeWalker::getResultWires ()
Definition at line 190 of file EdgeWalker.cpp.
References SCL.SimpleDataTypes::e, EWTOLERANCE, result, and src.Mod.PartDesign.fcgear.svggear::w.
loadEdges() [1/2]
bool EdgeWalker::loadEdges (std::vector< TechDraw::WalkerEdge > & edges)
Definition at line 103 of file EdgeWalker.cpp.
References SCL.SimpleDataTypes::e, and buildPsets::p.
loadEdges() [2/2]
bool EdgeWalker::loadEdges (std::vector< TopoDS_Edge > edges)
Definition at line 119 of file EdgeWalker.cpp.
makeCleanWire()
TopoDS_Wire EdgeWalker::makeCleanWire (std::vector< TopoDS_Edge > edges, double tol = 0.10) static
make a clean wire with sorted, oriented, connected, etc edges
Definition at line 240 of file EdgeWalker.cpp.
References SCL.SimpleDataTypes::e, EWTOLERANCE, Handle(), and result.
Referenced by TechDraw::DrawViewPart::getWireForFace(), and TechDraw::DrawViewSection::mapToPage().
makeEmbedding()
std::vector< embedItem > EdgeWalker::makeEmbedding (const std::vector< TopoDS_Edge > edges, const std::vector< TopoDS_Vertex > uniqueVList)
Definition at line 385 of file EdgeWalker.cpp.
References SCL.SimpleDataTypes::e, EWTOLERANCE, FirstVertex(), TechDraw::DrawUtil::incidenceAngleAtVertex(), LastVertex(), result, TechDraw::embedItem::sortIncidenceList(), TestSpreadsheet::v, and TechDraw::DrawUtil::vertexEqual().
makeUniqueVList()
std::vector< TopoDS_Vertex > EdgeWalker::makeUniqueVList (std::vector< TopoDS_Edge > edges)
Definition at line 269 of file EdgeWalker.cpp.
References SCL.SimpleDataTypes::e, EWTOLERANCE, FirstVertex(), Base::Vector3< float_type >::IsEqual(), LastVertex(), TestSpreadsheet::v, draftgeoutils.general::v1(), and TechDraw::DrawUtil::vertex2Vector().
makeWalkerEdges()
std::vector< WalkerEdge > EdgeWalker::makeWalkerEdges (std::vector< TopoDS_Edge > edges, std::vector< TopoDS_Vertex > verts)
make WalkerEdges (unique Vertex index pairs) from edge list
Definition at line 300 of file EdgeWalker.cpp.
References SCL.SimpleDataTypes::e, FirstVertex(), TechDraw::WalkerEdge::idx, LastVertex(), TechDraw::WalkerEdge::v1, and TechDraw::WalkerEdge::v2.
prepare()
bool EdgeWalker::prepare () protected
Definition at line 146 of file EdgeWalker.cpp.
References SCL.SimpleDataTypes::e, SplineSurface::i, num_vertices(), and Path.Post.scripts.grbl_post::type.
setSize()
bool EdgeWalker::setSize (std::size_t size)
Definition at line 136 of file EdgeWalker.cpp.
References SplineSurface::i, and CAMTests.TestPathVoronoi::vd.
sortStrip()
std::vector< TopoDS_Wire > EdgeWalker::sortStrip (std::vector< TopoDS_Wire > fw, bool includeBiggest)
Definition at line 344 of file EdgeWalker.cpp.
References Base::Console(), Base::ConsoleSingleton::Message(), and src.Mod.PartDesign.fcgear.svggear::w.
sortWiresBySize()
std::vector< TopoDS_Wire > EdgeWalker::sortWiresBySize (std::vector< TopoDS_Wire > & w, bool reverse = false)
Definition at line 366 of file EdgeWalker.cpp.
References src.Mod.PartDesign.fcgear.svggear::w, wireCompare(), and Mesh2Shape::wires.
Referenced by TechDraw::DrawViewPart::findFacesNew(), and TechDraw::DrawViewSection::makeFaceFromWires().
wireCompare()
bool EdgeWalker::wireCompare (const TopoDS_Wire & w1, const TopoDS_Wire & w2) static protected
return true if w1 enclosed area is bigger than w2 enclosed area
Definition at line 378 of file EdgeWalker.cpp.
Referenced by sortWiresBySize().
Member Data Documentation
m_embedding
std::vector<embedItem> TechDraw::EdgeWalker::m_embedding protected
Definition at line 205 of file EdgeWalker.h.
m_saveInEdges
std::vector<TopoDS_Edge> TechDraw::EdgeWalker::m_saveInEdges protected
Definition at line 204 of file EdgeWalker.h.
m_saveWalkerEdges
std::vector<TechDraw::WalkerEdge> TechDraw::EdgeWalker::m_saveWalkerEdges protected
Definition at line 203 of file EdgeWalker.h.
The documentation for this class was generated from the following files:
EdgeWalker.h
EdgeWalker.cpp