FreeCAD: PartGui::DlgProjectOnSurface Class Reference
PartGui::DlgProjectOnSurface Class Reference
#include <DlgProjectionOnSurface.h>
Public Member Functions
DlgProjectOnSurface (Part::ProjectOnSurface *feature, QWidget *parent=nullptr)
~DlgProjectOnSurface () override
void accept ()
void reject ()
void onSelectionChanged (const Gui::SelectionChanges &msg) override
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Detailed Description
Definition at line 198 of file DlgProjectionOnSurface.h.
Constructor & Destructor Documentation
DlgProjectOnSurface()
DlgProjectOnSurface::DlgProjectOnSurface (Part::ProjectOnSurface * feature, QWidget * parent = nullptr) explicit
Definition at line 1193 of file DlgProjectionOnSurface.cpp.
References App::PropertyQuantity::getValue(), Part::ProjectOnSurface::Height, and Part::ProjectOnSurface::Offset.
~DlgProjectOnSurface()
DlgProjectOnSurface::~DlgProjectOnSurface () override
Definition at line 1213 of file DlgProjectionOnSurface.cpp.
References Gui::SelectionSingleton::rmvSelectionGate(), and Gui::Selection().
Member Function Documentation
accept()
void DlgProjectOnSurface::accept ()
Definition at line 1272 of file DlgProjectionOnSurface.cpp.
References App::Document::commitTransaction(), App::WeakPtrT< T >::expired(), and App::DocumentObject::getDocument().
Referenced by PartGui::TaskProjectOnSurface::accept().
onSelectionChanged()
void DlgProjectOnSurface::onSelectionChanged (const Gui::SelectionChanges & msg) override virtual
Implements Gui::SelectionObserver.
Definition at line 1252 of file DlgProjectionOnSurface.cpp.
References Gui::SelectionChanges::AddSelection, and Path.Op.Surface::msg.
reject()
void DlgProjectOnSurface::reject ()
Definition at line 1281 of file DlgProjectionOnSurface.cpp.
References App::Document::abortTransaction(), App::WeakPtrT< T >::expired(), and App::DocumentObject::getDocument().
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and PartGui::TaskProjectOnSurface::reject().
The documentation for this class was generated from the following files:
DlgProjectionOnSurface.h
DlgProjectionOnSurface.cpp