FreeCAD: Gui::Gui::GestureNavigationStyle ::AwaitingMoveState Class Reference
Gui::Gui::GestureNavigationStyle ::AwaitingMoveState Class Reference
Public Types
using reactions = sc::custom_reaction< Gui::GestureNavigationStyle ::Event >
Public Member Functions
AwaitingMoveState (my_context ctx)
virtual ~AwaitingMoveState ()
sc::result react (const Gui::GestureNavigationStyle ::Event &ev)
Detailed Description
Definition at line 342 of file GestureNavigationStyle.cpp.
Member Typedef Documentation
reactions
using Gui::Gui::GestureNavigationStyle ::AwaitingMoveState::reactions = sc::custom_reaction< Gui::GestureNavigationStyle ::Event>
Definition at line 345 of file GestureNavigationStyle.cpp.
Constructor & Destructor Documentation
AwaitingMoveState()
Gui::Gui::GestureNavigationStyle ::AwaitingMoveState::AwaitingMoveState (my_context ctx) inline explicit
Definition at line 353 of file GestureNavigationStyle.cpp.
References Base::Console(), App::GetApplication(), ParameterGrp::GetInt(), App::Application::GetParameterGroupByPath(), Gui::NavigationStyle::IDLE, and Base::ConsoleSingleton::Log().
~AwaitingMoveState()
virtual Gui::Gui::GestureNavigationStyle ::AwaitingMoveState::~AwaitingMoveState () inline virtual
Definition at line 377 of file GestureNavigationStyle.cpp.
Member Function Documentation
react()
sc::result Gui::Gui::GestureNavigationStyle ::AwaitingMoveState::react (const Gui::GestureNavigationStyle ::Event & ev) inline
refire(): forwards all postponed events + this event
Definition at line 382 of file GestureNavigationStyle.cpp.
References getValue(), and Gui::NavigationStyle::SELECTION.
The documentation for this class was generated from the following file:
GestureNavigationStyle.cpp