FreeCAD: MeshGui::DlgEvaluateMeshImp Class Reference
MeshGui::DlgEvaluateMeshImp Class Reference
#include <DlgEvaluateMeshImp.h>
Classes
class Private
Public Member Functions
DlgEvaluateMeshImp (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~DlgEvaluateMeshImp () override
void setMesh (Mesh::Feature *)
Public Member Functions inherited from App::DocumentObserver
DocumentObserver ()
Constructor.
DocumentObserver (Document *)
virtual ~DocumentObserver ()
void attachDocument (Document *)
void detachDocument ()
Protected Member Functions
void refreshList ()
void showInformation ()
void cleanInformation ()
void addViewProvider (const char *vp, const std::vector< Mesh::ElementIndex > &indices)
void removeViewProvider (const char *vp)
void removeViewProviders ()
void changeEvent (QEvent *e) override
Protected Member Functions inherited from App::DocumentObserver
Document * getDocument () const
Detailed Description
Author
Werner Mayer
Definition at line 71 of file DlgEvaluateMeshImp.h.
Constructor & Destructor Documentation
DlgEvaluateMeshImp()
DlgEvaluateMeshImp::DlgEvaluateMeshImp (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags()) explicit
Constructs a DlgEvaluateMeshImp which is a child of 'parent', with the widget flags set to 'f'.
Definition at line 102 of file DlgEvaluateMeshImp.cpp.
References MeshCore::MeshDefinitions::_fMinPointDistanceP2, MeshGui::DlgEvaluateMeshImp::Private::checkNonManfoldPoints, MeshGui::DlgEvaluateMeshImp::Private::enableFoldsCheck, MeshGui::DlgEvaluateMeshImp::Private::epsilonDegenerated, App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), MeshGui::DlgEvaluateMeshImp::Private::showFoldsFunction(), MeshGui::DlgEvaluateMeshImp::Private::strictlyDegenerated, and MeshGui::DlgEvaluateMeshImp::Private::ui.
~DlgEvaluateMeshImp()
DlgEvaluateMeshImp::~DlgEvaluateMeshImp () override
Destroys the object and frees any allocated resources
Definition at line 150 of file DlgEvaluateMeshImp.cpp.
References MeshGui::DlgEvaluateMeshImp::Private::checkNonManfoldPoints, MeshGui::DlgEvaluateMeshImp::Private::enableFoldsCheck, App::GetApplication(), App::Application::GetParameterGroupByPath(), ParameterGrp::SetBool(), MeshGui::DlgEvaluateMeshImp::Private::strictlyDegenerated, MeshGui::DlgEvaluateMeshImp::Private::view, and MeshGui::DlgEvaluateMeshImp::Private::vp.
Member Function Documentation
addViewProvider()
void DlgEvaluateMeshImp::addViewProvider (const char * vp, const std::vector< Mesh::ElementIndex > & indices) protected
Definition at line 347 of file DlgEvaluateMeshImp.cpp.
References Base::Type::createInstanceByName(), MeshGui::DlgEvaluateMeshImp::Private::meshFeature, removeViewProvider(), MeshGui::DlgEvaluateMeshImp::Private::view, and MeshGui::DlgEvaluateMeshImp::Private::vp.
changeEvent()
void DlgEvaluateMeshImp::changeEvent (QEvent * e) override protected
Definition at line 249 of file DlgEvaluateMeshImp.cpp.
References SCL.SimpleDataTypes::e, and MeshGui::DlgEvaluateMeshImp::Private::ui.
cleanInformation()
void DlgEvaluateMeshImp::cleanInformation () protected
Definition at line 448 of file DlgEvaluateMeshImp.cpp.
References MeshGui::DlgEvaluateMeshImp::Private::ui.
Referenced by refreshList().
refreshList()
void DlgEvaluateMeshImp::refreshList () protected
Definition at line 407 of file DlgEvaluateMeshImp.cpp.
References cleanInformation(), Base::Persistence::getClassTypeId(), App::DocumentObserver::getDocument(), App::Document::getObjectsOfType(), src.Mod.Test.testPathArray::items, replaceobj::objs, and MeshGui::DlgEvaluateMeshImp::Private::ui.
Referenced by setMesh().
removeViewProvider()
void DlgEvaluateMeshImp::removeViewProvider (const char * vp) protected
Definition at line 362 of file DlgEvaluateMeshImp.cpp.
References MeshGui::DlgEvaluateMeshImp::Private::view, and MeshGui::DlgEvaluateMeshImp::Private::vp.
Referenced by addViewProvider().
removeViewProviders()
void DlgEvaluateMeshImp::removeViewProviders () protected
Definition at line 374 of file DlgEvaluateMeshImp.cpp.
References MeshGui::DlgEvaluateMeshImp::Private::view, and MeshGui::DlgEvaluateMeshImp::Private::vp.
setMesh()
void DlgEvaluateMeshImp::setMesh (Mesh::Feature * m)
Definition at line 327 of file DlgEvaluateMeshImp.cpp.
References App::DocumentObserver::attachDocument(), toolbit-attributes::doc, App::DocumentObserver::getDocument(), SplineSurface::i, test::m, refreshList(), and MeshGui::DlgEvaluateMeshImp::Private::ui.
showInformation()
void DlgEvaluateMeshImp::showInformation () protected
Definition at line 428 of file DlgEvaluateMeshImp.cpp.
References MeshCore::MeshKernel::CountEdges(), MeshCore::MeshKernel::CountFacets(), MeshCore::MeshKernel::CountPoints(), Mesh::MeshObject::getKernel(), Mesh::PropertyMeshKernel::getValue(), Mesh::Feature::Mesh, MeshGui::DlgEvaluateMeshImp::Private::meshFeature, and MeshGui::DlgEvaluateMeshImp::Private::ui.
The documentation for this class was generated from the following files:
DlgEvaluateMeshImp.h
DlgEvaluateMeshImp.cpp