FreeCAD: ImportGui::OCAFBrowser Class Reference
ImportGui::OCAFBrowser Class Reference
#include <OCAFBrowser.h>
Public Member Functions
OCAFBrowser (const Handle(TDocStd_Document) &hDoc)
void load (QTreeWidget *)
Static Public Member Functions
static void showDialog (const QString &title, const Handle(TDocStd_Document) &hDoc)
Detailed Description
Definition at line 41 of file OCAFBrowser.h.
Constructor & Destructor Documentation
OCAFBrowser()
OCAFBrowser::OCAFBrowser (const Handle(TDocStd_Document) & hDoc) explicit
Definition at line 66 of file OCAFBrowser.cpp.
Member Function Documentation
load()
void OCAFBrowser::load (QTreeWidget * theTree)
Definition at line 96 of file OCAFBrowser.cpp.
Referenced by showDialog().
showDialog()
void OCAFBrowser::showDialog (const QString & title, const Handle(TDocStd_Document) & hDoc) static
Definition at line 313 of file OCAFBrowser.cpp.
References draftgeoutils.intersections::connect(), Gui::getMainWindow(), load(), and Plot::title().
The documentation for this class was generated from the following files:
OCAFBrowser.h
OCAFBrowser.cpp