FreeCAD: TechDrawGui::QGITile Class Reference
TechDrawGui::QGITile Class Reference
#include <QGITile.h>
Public Types
enum { Type = QGraphicsItem::UserType + 325 }
Public Types inherited from TechDrawGui::QGIDecoration
enum { Type = QGraphicsItem::UserType + 173 }
Public Member Functions
QGITile (TechDraw::DrawTileWeld *)
~QGITile () override=default
int type () const override
QRectF boundingRect () const override
void setTileTextLeft (const std::string &text)
void setTileTextRight (const std::string &text)
void setTileTextCenter (const std::string &text)
void setFont (const QFont &font, double fSizePx)
void setFont (const std::string &fName, double fSizePx)
void setSymbolFile (const std::string &fileSpec)
void setTilePosition (QPointF org, int row, int col)
void setTileScale (double scale)
void setTailRight (bool state)
void setAltWeld (bool state)
bool isTailRight () const
void draw () override
void setLocalAxes (Base::Vector3d xdir, Base::Vector3d ydir)
QPointF mapPointToRotation (Base::Vector3d pointIn)
QPointF calcTilePosition ()
determine where to position the tile based on which fields are used.
Public Member Functions inherited from TechDrawGui::QGIDecoration
QGIDecoration ()
~QGIDecoration () override=default
int type () const override
QRectF boundingRect () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
virtual void onDragFinished ()
void setWidth (double w)
double getWidth ()
void setStyle (Qt::PenStyle s)
void setColor (QColor c)
QColor getColor ()
void setFill (Qt::BrushStyle bs)
void makeMark (double x, double y)
void makeMark (Base::Vector3d v)
Protected Member Functions
QColor getTileColor () const
void setPrettyNormal ()
void setPrettyPre ()
void setPrettySel ()
double getSymbolWidth () const
double getSymbolHeight () const
double getSymbolFactor () const
QByteArray getSvgString (QString svgPath)
QString prefTextFont () const
double prefFontSize () const
void makeSymbol ()
void makeText ()
bool getAltWeld () const
bool isReadable (QString filePath)
std::string getStringFromFile (const std::string &inSpec)
Protected Member Functions inherited from TechDrawGui::QGIDecoration
void setPrettyNormal ()
void setPrettyPre ()
void setPrettySel ()
virtual QColor prefNormalColor ()
virtual QColor prefPreColor ()
virtual QColor prefSelectColor ()
Additional Inherited Members
Protected Attributes inherited from TechDrawGui::QGIDecoration
QPen m_pen
QBrush m_brush
QColor m_colCurrent
QColor m_colNormal
double m_width
Qt::PenStyle m_styleCurrent
Qt::BrushStyle m_brushCurrent
int m_dragState
Detailed Description
Definition at line 46 of file QGITile.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 52 of file QGITile.h.
Constructor & Destructor Documentation
QGITile()
QGITile::QGITile (TechDraw::DrawTileWeld * dtw) explicit
Definition at line 47 of file QGITile.cpp.
References getSymbolHeight(), getSymbolWidth(), TechDrawGui::QGIDecoration::m_colCurrent, TechDrawGui::QGIDecoration::m_colNormal, TechDrawGui::QGIDecoration::prefNormalColor(), and prefTextFont().
~QGITile()
TechDrawGui::QGITile::~QGITile () override default
Member Function Documentation
boundingRect()
QRectF QGITile::boundingRect () const override
Definition at line 323 of file QGITile.cpp.
calcTilePosition()
QPointF QGITile::calcTilePosition ()
determine where to position the tile based on which fields are used.
Definition at line 330 of file QGITile.cpp.
References dot(), getAltWeld(), getSymbolHeight(), isTailRight(), and TechDraw::DrawUtil::toQPointF().
draw()
void QGITile::draw () override virtual
Reimplemented from TechDrawGui::QGIDecoration.
Definition at line 91 of file QGITile.cpp.
References getSymbolHeight(), getSymbolWidth(), makeSymbol(), and makeText().
Referenced by setPrettyNormal(), setPrettyPre(), and setPrettySel().
getAltWeld()
bool QGITile::getAltWeld () const protected
Definition at line 275 of file QGITile.cpp.
Referenced by calcTilePosition().
getStringFromFile()
std::string QGITile::getStringFromFile (const std::string & inSpec) protected
Definition at line 179 of file QGITile.cpp.
References SCL.SimpleDataTypes::f.
Referenced by makeSymbol().
getSvgString()
QByteArray TechDrawGui::QGITile::getSvgString (QString svgPath) protected
getSymbolFactor()
double QGITile::getSymbolFactor () const protected
Definition at line 308 of file QGITile.cpp.
Referenced by getSymbolHeight(), getSymbolWidth(), and makeSymbol().
getSymbolHeight()
double QGITile::getSymbolHeight () const protected
Definition at line 298 of file QGITile.cpp.
References getSymbolFactor().
Referenced by calcTilePosition(), draw(), and QGITile().
getSymbolWidth()
double QGITile::getSymbolWidth () const protected
Definition at line 287 of file QGITile.cpp.
References getSymbolFactor().
Referenced by draw(), and QGITile().
getTileColor()
QColor QGITile::getTileColor () const protected
Definition at line 281 of file QGITile.cpp.
References App::Color::asValue(), and TechDrawGui::PreferencesGui::getAccessibleQColor().
isReadable()
bool TechDrawGui::QGITile::isReadable (QString filePath) protected
isTailRight()
bool QGITile::isTailRight () const
Definition at line 270 of file QGITile.cpp.
Referenced by calcTilePosition().
makeSymbol()
void QGITile::makeSymbol () protected
Definition at line 101 of file QGITile.cpp.
References TechDrawGui::QGCustomSvg::centerAt(), Base::Console(), Base::ConsoleSingleton::Error(), getStringFromFile(), getSymbolFactor(), App::PropertyString::getValue(), TechDrawGui::QGCustomSvg::load(), and TechDraw::DrawTileWeld::SymbolFile.
Referenced by draw().
makeText()
void QGITile::makeText () protected
Definition at line 119 of file QGITile.cpp.
References TechDrawGui::QGCustomText::centerAt(), TechDrawGui::QGCustomText::justifyLeftAt(), TechDrawGui::QGCustomText::justifyRightAt(), TechDrawGui::PreferencesGui::labelFontSizePX(), TechDrawGui::QGIDecoration::m_colCurrent, and TechDrawGui::QGCustomText::setColor().
Referenced by draw().
mapPointToRotation()
QPointF TechDrawGui::QGITile::mapPointToRotation (Base::Vector3d pointIn)
prefFontSize()
double QGITile::prefFontSize () const protected
Definition at line 313 of file QGITile.cpp.
prefTextFont()
QString QGITile::prefTextFont () const protected
Definition at line 318 of file QGITile.cpp.
Referenced by QGITile().
setAltWeld()
void TechDrawGui::QGITile::setAltWeld (bool state) inline
Definition at line 66 of file QGITile.h.
setFont() [1/2]
void QGITile::setFont (const QFont & font, double fSizePx)
Definition at line 215 of file QGITile.cpp.
Referenced by setFont().
setFont() [2/2]
void QGITile::setFont (const std::string & fName, double fSizePx)
Definition at line 222 of file QGITile.cpp.
References setFont().
setLocalAxes()
void QGITile::setLocalAxes (Base::Vector3d xdir, Base::Vector3d ydir)
Definition at line 379 of file QGITile.cpp.
setPrettyNormal()
void QGITile::setPrettyNormal () protected
Definition at line 237 of file QGITile.cpp.
References draw(), TechDrawGui::QGIDecoration::m_colCurrent, TechDrawGui::QGIDecoration::m_colNormal, and TechDrawGui::QGCustomText::setColor().
setPrettyPre()
void QGITile::setPrettyPre () protected
Definition at line 248 of file QGITile.cpp.
References draw(), TechDrawGui::QGIDecoration::m_colCurrent, TechDrawGui::QGIDecoration::prefPreColor(), and TechDrawGui::QGCustomText::setColor().
setPrettySel()
void QGITile::setPrettySel () protected
Definition at line 259 of file QGITile.cpp.
References draw(), TechDrawGui::QGIDecoration::m_colCurrent, TechDrawGui::QGIDecoration::prefSelectColor(), and TechDrawGui::QGCustomText::setColor().
setSymbolFile()
void QGITile::setSymbolFile (const std::string & fileSpec)
Definition at line 230 of file QGITile.cpp.
setTailRight()
void TechDrawGui::QGITile::setTailRight (bool state) inline
Definition at line 65 of file QGITile.h.
setTilePosition()
void QGITile::setTilePosition (QPointF org, int row, int col)
Definition at line 188 of file QGITile.cpp.
References SCL.SimpleDataTypes::c.
setTileScale()
void QGITile::setTileScale (double scale)
Definition at line 195 of file QGITile.cpp.
References toolbit-attributes::s.
setTileTextCenter()
void QGITile::setTileTextCenter (const std::string & text)
Definition at line 210 of file QGITile.cpp.
setTileTextLeft()
void QGITile::setTileTextLeft (const std::string & text)
Definition at line 200 of file QGITile.cpp.
setTileTextRight()
void QGITile::setTileTextRight (const std::string & text)
Definition at line 205 of file QGITile.cpp.
type()
int TechDrawGui::QGITile::type () const inline override
Definition at line 53 of file QGITile.h.
The documentation for this class was generated from the following files:
QGITile.h
QGITile.cpp