FreeCAD: Simplify Class Reference
Simplify Class Reference
#include <Simplify.h>
Classes
struct Ref
struct Triangle
struct Vertex
Public Member Functions
void simplify_mesh (int target_count, double tolerance, double aggressiveness=7)
Public Attributes
std::vector< Triangle > triangles
std::vector< Vertex > vertices
std::vector< Ref > refs
Detailed Description
Definition at line 84 of file Simplify.h.
Member Function Documentation
simplify_mesh()
void Simplify::simplify_mesh (int target_count, double tolerance, double aggressiveness = 7)
Definition at line 120 of file Simplify.h.
References Simplify::Vertex::border, SplineSurface::i, Simplify::Vertex::p, buildPsets::p, Base::pow(), Simplify::Vertex::q, refs, InitGui::t, Simplify::Vertex::tcount, draftutils.utils::tolerance(), triangles, Simplify::Vertex::tstart, draftgeoutils.general::v1(), and vertices.
Referenced by MeshCore::MeshSimplify::simplify().
Member Data Documentation
refs
std::vector<Ref> Simplify::refs
Definition at line 92 of file Simplify.h.
Referenced by simplify_mesh().
triangles
std::vector<Triangle> Simplify::triangles
Definition at line 90 of file Simplify.h.
Referenced by MeshCore::MeshSimplify::simplify(), and simplify_mesh().
vertices
std::vector<Vertex> Simplify::vertices
Definition at line 91 of file Simplify.h.
Referenced by MeshCore::MeshSimplify::simplify(), and simplify_mesh().
The documentation for this class was generated from the following file:
Simplify.h