FreeCAD: App::GeoFeatureGroupExtension Class Reference
App::GeoFeatureGroupExtension Class Reference
The base class for placeable group of DocumentObjects. It represents a local coordnate system.
#include <GeoFeatureGroupExtension.h>
Public Member Functions
PropertyPlacement & placement ()
void initExtension (ExtensionContainer *obj) override
virtual void transformPlacement (const Base::Placement &transform)
transformPlacement applies transform to placement of this shape. Override this function to propagate the change of placement to base features.
GeoFeatureGroupExtension ()
Constructor.
~GeoFeatureGroupExtension () override
void extensionOnChanged (const Property *p) override
Base::Placement globalGroupPlacement ()
Calculates the global placement of this group.
bool extensionGetSubObject (DocumentObject *&ret, const char *subname, PyObject **pyObj, Base::Matrix4D *mat, bool transform, int depth) const override
bool extensionGetSubObjects (std::vector< std::string > &ret, int reason) const override
std::vector< DocumentObject * > addObjects (std::vector< DocumentObject * > obj) override
std::vector< DocumentObject * > removeObjects (std::vector< DocumentObject * > obj) override
Public Member Functions inherited from App::GroupExtension
GroupExtension ()
Constructor.
~GroupExtension () override
virtual DocumentObject * addObject (const char *sType, const char *pObjectName)
virtual std::vector< DocumentObject * > addObject (DocumentObject *obj)
virtual std::vector< DocumentObject * > setObjects (std::vector< DocumentObject * > obj)
virtual bool allowObject (DocumentObject *)
virtual std::vector< DocumentObject * > removeObject (DocumentObject *obj)
virtual void removeObjectsFromDocument ()
DocumentObject * getObject (const char *Name) const
virtual bool hasObject (const DocumentObject *obj, bool recursive=false) const
bool isChildOf (const GroupExtension *group, bool recursive=true) const
const std::vector< DocumentObject * > & getObjects () const
std::vector< DocumentObject * > getObjectsOfType (const Base::Type &typeId) const
int countObjectsOfType (const Base::Type &typeId) const
PyObject * getExtensionPyObject () override
void extensionOnChanged (const Property *p) override
bool extensionGetSubObject (DocumentObject *&ret, const char *subname, PyObject **pyObj, Base::Matrix4D *mat, bool transform, int depth) const override
bool extensionGetSubObjects (std::vector< std::string > &ret, int reason) const override
App::DocumentObjectExecReturn * extensionExecute () override
std::vector< DocumentObject * > getAllChildren () const
void getAllChildren (std::vector< DocumentObject * > &, std::set< DocumentObject * > &) const
Public Member Functions inherited from App::DocumentObjectExtension
virtual Base::Type getExtensionTypeId (void) const override
DocumentObjectExtension ()
~DocumentObjectExtension () override
App::DocumentObject * getExtendedObject ()
const App::DocumentObject * getExtendedObject () const
virtual short extensionMustExecute ()
virtual void onExtendedSettingDocument ()
get called after setting the document
virtual void onExtendedDocumentRestored ()
get called after a document has been fully restored
virtual void onExtendedSetupObject ()
get called after a brand new object was created
virtual void onExtendedUnsetupObject ()
get called when object is going to be removed from the document
virtual const char * getViewProviderExtensionName () const
virtual bool extensionGetLinkedObject (DocumentObject *&ret, bool recursive, Base::Matrix4D *mat, bool transform, int depth) const
virtual int extensionSetElementVisible (const char *, bool)
virtual int extensionIsElementVisible (const char *)
virtual bool extensionHasChildElement () const
Public Member Functions inherited from App::Extension
Extension ()=default
virtual ~Extension ()
App::ExtensionContainer * getExtendedContainer ()
const App::ExtensionContainer * getExtendedContainer () const
std::string name () const
bool isPythonExtension ()
virtual Property * extensionGetPropertyByName (const char *name) const
find a property by its name
virtual const char * extensionGetPropertyName (const Property *prop) const
get the name of a property
virtual void extensionGetPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual void extensionGetPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual short extensionGetPropertyType (const Property *prop) const
get the Type of a Property
virtual short extensionGetPropertyType (const char *name) const
get the Type of a named Property
virtual const char * extensionGetPropertyGroup (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * extensionGetPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual void extensionSave (Base::Writer &) const
virtual void extensionRestore (Base::XMLReader &)
bool extensionIsDerivedFrom (const Base::Type type) const
Static Public Member Functions
static DocumentObject * getGroupOfObject (const DocumentObject *obj)
static bool isNonGeoGroup (const DocumentObject *obj)
Returns true if the given DocumentObject is DocumentObjectGroup but not GeoFeatureGroup.
static std::vector< App::DocumentObject * > getCSRelevantLinks (const App::DocumentObject *obj)
static bool areLinksValid (const App::DocumentObject *obj)
static bool isLinkValid (App::Property *link)
static void getInvalidLinkObjects (const App::DocumentObject *obj, std::vector< App::DocumentObject * > &vec)
Static Public Member Functions inherited from App::GroupExtension
static DocumentObject * getGroupOfObject (const DocumentObject *obj)
Static Public Member Functions inherited from App::DocumentObjectExtension
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Static Public Member Functions inherited from App::Extension
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Additional Inherited Members
Public Attributes inherited from App::GroupExtension
PropertyLinkList Group
Properties.
PropertyBool _GroupTouched
Protected Member Functions inherited from App::DocumentObjectExtension
virtual const App::PropertyData & extensionGetPropertyData (void) const override
Protected Member Functions inherited from App::Extension
virtual bool extensionHandleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
returns true if the property name change was handled by the extension.
virtual bool extensionHandleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop)
returns true if the property type change was handled by the extension.
void initExtensionType (Base::Type type)
Static Protected Member Functions inherited from App::DocumentObjectExtension
static const App::PropertyData * extensionGetPropertyDataPtr (void)
Static Protected Member Functions inherited from App::Extension
static const App::PropertyData * extensionGetPropertyDataPtr (void)
static void initExtensionSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Base::Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Extension
bool m_isPythonExtension = false
Py::SmartPtr ExtensionPythonObject
Detailed Description
The base class for placeable group of DocumentObjects. It represents a local coordnate system.
This class is the FreeCAD way of representing local coordinate systems. It groups its children beneath it and transforms them all with the GeoFeatureGroup placement. A few important properties:
Every child that belongs to the CS must be in the Group property. Even if a sketch is part of a pad, it must be in the Group property of the same GeoFeatureGroup as pad. This also holds for normal GroupExtensions. They can be added to a GeoFeatureGroup, but all objects that the group holds must also be added to the GeoFeatureGroup
Objects can be only in a single GeoFeatureGroup. It is not allowed to have a document object in multiple GeoFeatureGroups
PropertyLinks between different GeoFeatureGroups are forbidden. There are special link properties that allow such cross-CS links.
Expressions can cross GeoFeatureGroup borders
Definition at line 75 of file GeoFeatureGroupExtension.h.
Constructor & Destructor Documentation
GeoFeatureGroupExtension()
GeoFeatureGroupExtension::GeoFeatureGroupExtension ()
Constructor.
Definition at line 47 of file GeoFeatureGroupExtension.cpp.
References App::Child, and App::DocumentObjectExtension::getExtensionClassTypeId().
~GeoFeatureGroupExtension()
GeoFeatureGroupExtension::~GeoFeatureGroupExtension () override default
Member Function Documentation
addObjects()
std::vector< DocumentObject * > GeoFeatureGroupExtension::addObjects (std::vector< DocumentObject * > obj) override virtual
Reimplemented from App::GroupExtension.
Reimplemented in App::OriginGroupExtension.
Definition at line 148 of file GeoFeatureGroupExtension.cpp.
References App::GroupExtension::allowObject(), getCSRelevantLinks(), App::DocumentObjectExtension::getExtendedObject(), getGroupOfObject(), App::PropertyListsT< T, ListT, ParentT >::getValues(), toolbit-attributes::group, App::GroupExtension::Group, toolbit-attributes::grp, App::GroupExtension::hasObject(), importers.importIFCmulticore::objects, App::GroupExtension::removeObject(), and App::PropertyLinkList::setValues().
Referenced by App::OriginGroupExtension::addObjects(), and PartDesignGui::TaskBooleanParameters::onSelectionChanged().
areLinksValid()
bool GeoFeatureGroupExtension::areLinksValid (const App::DocumentObject * obj) static
Checks if the links of the given object comply with all GeoFeatureGroup requirements, that means if normal links are only within the parent GeoFeatureGroup.
Definition at line 460 of file GeoFeatureGroupExtension.cpp.
References App::ExtensionContainer::getPropertyList(), and isLinkValid().
extensionGetSubObject()
bool GeoFeatureGroupExtension::extensionGetSubObject (DocumentObject *& ret, const char * subname, PyObject ** pyObj, Base::Matrix4D * mat, bool transform, int depth) const override virtual
Get the sub object by name
See also
DocumentObject::getSubObject()
Returns
Return turn if handled, the sub object is returned in ret
Reimplemented from App::DocumentObjectExtension.
Reimplemented in App::OriginGroupExtension.
Definition at line 394 of file GeoFeatureGroupExtension.cpp.
References dot(), App::PropertyLinkList::findUsingMap(), App::Extension::getExtendedContainer(), App::DocumentObjectExtension::getExtensionClassTypeId(), App::LinkBaseExtension::getExtensionClassTypeId(), App::DocumentObject::getSubObject(), App::PropertyPlacement::getValue(), App::PropertyListsT< T, ListT, ParentT >::getValues(), App::GroupExtension::Group, App::ExtensionContainer::hasExtension(), App::Extension::name(), placement(), and Base::Placement::toMatrix().
Referenced by App::OriginGroupExtension::extensionGetSubObject().
extensionGetSubObjects()
bool GeoFeatureGroupExtension::extensionGetSubObjects (std::vector< std::string > & ret, int reason) const override virtual
Get name references of all sub objects
See also
DocumentObject::getSubObjects()
Returns
Return turn if handled, the sub object is returned in ret
Reimplemented from App::DocumentObjectExtension.
Definition at line 545 of file GeoFeatureGroupExtension.cpp.
References App::GeoExcluded, App::DocumentObject::getNameInDocument(), App::PropertyListsT< T, ListT, ParentT >::getValues(), App::GroupExtension::Group, App::DocumentObject::isAttachedToDocument(), and App::DocumentObject::testStatus().
extensionOnChanged()
void GeoFeatureGroupExtension::extensionOnChanged (const Property * p) override virtual
Reimplemented from App::Extension.
Reimplemented in App::OriginGroupExtension.
Definition at line 211 of file GeoFeatureGroupExtension.cpp.
References Path.Log::error(), App::GroupExtension::extensionOnChanged(), App::DocumentObjectExtension::getExtendedObject(), App::PropertyListsT< T, ListT, ParentT >::getValues(), App::GroupExtension::Group, App::Document::Importing, Gui::isRestoring, buildPsets::p, Init::parent, App::PropertyLinkList::setValues(), App::Property::testStatus(), and App::Property::User3.
Referenced by App::OriginGroupExtension::extensionOnChanged().
getCSRelevantLinks()
std::vector< DocumentObject * > GeoFeatureGroupExtension::getCSRelevantLinks (const App::DocumentObject * obj) static
Collects all links that are relevant for the coordinate system, meaning all recursive links to obj and from obj excluding expressions and stopping the recursion at other geofeaturegroups. The result is the combination of CSOutList and CSInList.
Definition at line 351 of file GeoFeatureGroupExtension.cpp.
References SurfaceTests.TestBlendCurve::vec.
Referenced by addObjects(), and removeObjects().
getGroupOfObject()
DocumentObject * GeoFeatureGroupExtension::getGroupOfObject (const DocumentObject * obj) static
Returns the geo feature group which contains this object. In case this object is not part of any geoFeatureGroup 0 is returned. Unlike DocumentObjectGroup::getGroupOfObject searches only for GeoFeatureGroups
Parameters
obj the object to search for
Definition at line 84 of file GeoFeatureGroupExtension.cpp.
References Base::Persistence::getClassTypeId(), App::OriginGroupExtension::getGroupOfObject(), App::DocumentObject::getInList(), toolbit-attributes::group, and Base::BaseClass::isDerivedFrom().
Referenced by App::GroupExtension::addObjects(), addObjects(), Gui::View3DInventorSelection::checkGroupOnTop(), doSelect(), App::Document::exportGraphviz(), App::GeoFeature::getGlobalPlacement(), getInvalidLinkObjects(), and isLinkValid().
getInvalidLinkObjects()
void GeoFeatureGroupExtension::getInvalidLinkObjects (const App::DocumentObject * obj, std::vector< App::DocumentObject * > & vec) static
Definition at line 514 of file GeoFeatureGroupExtension.cpp.
References App::Child, App::DocumentObjectExtension::getExtensionClassTypeId(), getGroupOfObject(), toolbit-attributes::group, App::ExtensionContainer::hasExtension(), App::Local, result, and SurfaceTests.TestBlendCurve::vec.
Referenced by App::Document::exportGraphviz().
globalGroupPlacement()
Base::Placement GeoFeatureGroupExtension::globalGroupPlacement ()
Calculates the global placement of this group.
The returned placement describes the transformation from the global reference coordinate system to the local coordinate system of this geo feature group. If this group has a no parent GeoFeatureGroup the returned placement is the one of this group. For multiple stacked GeoFeatureGroups the returned Placement is the combination of all parent placements including the one of this group.
Returns
Base::Placement The transformation from global reference system to the groups local system
Definition at line 114 of file GeoFeatureGroupExtension.cpp.
References App::DocumentObjectExtension::getExtendedObject().
initExtension()
void GeoFeatureGroupExtension::initExtension (ExtensionContainer * obj) override virtual
Reimplemented from App::Extension.
Definition at line 55 of file GeoFeatureGroupExtension.cpp.
References Base::Persistence::getClassTypeId(), App::Extension::initExtension(), and Base::BaseClass::isDerivedFrom().
Referenced by PartDesign::Boolean::Boolean().
isLinkValid()
bool GeoFeatureGroupExtension::isLinkValid (App::Property * link) static
Checks if the given link complies with all GeoFeatureGroup requirements, that means if normal links are only within the parent GeoFeatureGroup.
Definition at line 478 of file GeoFeatureGroupExtension.cpp.
References App::Child, Base::Persistence::getClassTypeId(), App::Property::getContainer(), App::ExtensionContainer::getExtensionByType(), App::DocumentObjectExtension::getExtensionClassTypeId(), getGroupOfObject(), toolbit-attributes::group, App::ExtensionContainer::hasExtension(), Base::BaseClass::isDerivedFrom(), App::Local, and result.
Referenced by areLinksValid().
isNonGeoGroup()
static bool App::GeoFeatureGroupExtension::isNonGeoGroup (const DocumentObject * obj) inline static
Returns true if the given DocumentObject is DocumentObjectGroup but not GeoFeatureGroup.
Definition at line 141 of file GeoFeatureGroupExtension.h.
Referenced by _getTopoShape().
placement()
PropertyPlacement & GeoFeatureGroupExtension::placement ()
Definition at line 65 of file GeoFeatureGroupExtension.cpp.
References App::Extension::getExtendedContainer().
Referenced by App::OriginGroupExtension::extensionGetSubObject(), extensionGetSubObject(), and transformPlacement().
removeObjects()
std::vector< DocumentObject * > GeoFeatureGroupExtension::removeObjects (std::vector< DocumentObject * > obj) override virtual
Removes objects from this group. Returns all objects that have been removed.
Reimplemented from App::GroupExtension.
Definition at line 183 of file GeoFeatureGroupExtension.cpp.
References getCSRelevantLinks(), App::PropertyListsT< T, ListT, ParentT >::getValues(), App::GroupExtension::Group, toolbit-attributes::grp, importers.importIFCmulticore::objects, and App::PropertyLinkList::setValues().
Referenced by PartDesignGui::ViewProviderBody::dropObject().
transformPlacement()
void GeoFeatureGroupExtension::transformPlacement (const Base::Placement & transform) virtual
transformPlacement applies transform to placement of this shape. Override this function to propagate the change of placement to base features.
Parameters
transform (input).
Definition at line 76 of file GeoFeatureGroupExtension.cpp.
References App::PropertyPlacement::getValue(), placement(), and App::PropertyPlacement::setValue().
The documentation for this class was generated from the following files:
GeoFeatureGroupExtension.h
GeoFeatureGroupExtension.cpp