FreeCAD: ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.unary_generic_expression Class Reference
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.unary_generic_expression Class Reference
Public Member Functions
def __init__ (self, operand)
def operand ()
Public Member Functions inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.generic_expression
def wr1 (self)
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
operand
Detailed Description
Entity unary_generic_expression definition.
:param operand
:type operand:generic_expression
Definition at line 8336 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Constructor & Destructor Documentation
__init__()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.unary_generic_expression.__init__ (self, operand)
Definition at line 8342 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Member Function Documentation
operand()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.unary_generic_expression.operand ()
Definition at line 8347 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.unary_generic_expression._operand, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.unary_generic_expression.operand.
Referenced by automotive_design.index_expression.wr1(), and automotive_design.substring_expression.wr1().
Member Data Documentation
operand
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.unary_generic_expression.operand
Definition at line 8344 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.unary_generic_expression.operand(), automotive_design.index_expression.wr1(), and automotive_design.substring_expression.wr1().
The documentation for this class was generated from the following file:
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py