FreeCAD: Gui::ViewParams Class Reference
Gui::ViewParams Class Reference
#include <ViewParams.h>
Public Member Functions
ViewParams ()
~ViewParams () override
void OnChange (Base::Subject< const char * > &, const char *sReason) override
ParameterGrp::handle getHandle ()
bool getUseNewSelection () const
void setUseNewSelection (bool _v)
bool getUseSelectionRoot () const
void setUseSelectionRoot (bool _v)
bool getEnableSelection () const
void setEnableSelection (bool _v)
int getRenderCache () const
void setRenderCache (int _v)
bool getRandomColor () const
void setRandomColor (bool _v)
unsigned long getBoundingBoxColor () const
void setBoundingBoxColor (unsigned long _v)
unsigned long getAnnotationTextColor () const
void setAnnotationTextColor (unsigned long _v)
int getMarkerSize () const
void setMarkerSize (int _v)
unsigned long getDefaultLinkColor () const
void setDefaultLinkColor (unsigned long _v)
unsigned long getDefaultShapeLineColor () const
void setDefaultShapeLineColor (unsigned long _v)
unsigned long getDefaultShapeVertexColor () const
void setDefaultShapeVertexColor (unsigned long _v)
unsigned long getDefaultShapeColor () const
void setDefaultShapeColor (unsigned long _v)
int getDefaultShapeTransparency () const
void setDefaultShapeTransparency (int _v)
int getDefaultShapeLineWidth () const
void setDefaultShapeLineWidth (int _v)
int getDefaultShapePointSize () const
void setDefaultShapePointSize (int _v)
bool getCoinCycleCheck () const
void setCoinCycleCheck (bool _v)
bool getEnablePropertyViewForInactiveDocument () const
void setEnablePropertyViewForInactiveDocument (bool _v)
bool getShowSelectionBoundingBox () const
void setShowSelectionBoundingBox (bool _v)
unsigned long getPropertyViewTimer () const
void setPropertyViewTimer (unsigned long _v)
unsigned long getAxisXColor () const
void setAxisXColor (unsigned long _v)
unsigned long getAxisYColor () const
void setAxisYColor (unsigned long _v)
unsigned long getAxisZColor () const
void setAxisZColor (unsigned long _v)
double getDraggerScale () const
void setDraggerScale (double _v)
Static Public Member Functions
static ViewParams * instance ()
Detailed Description
Convenient class to obtain view provider related parameters
The parameters are under group "User parameter:BaseApp/Preferences/View"
Definition at line 55 of file ViewParams.h.
Constructor & Destructor Documentation
ViewParams()
ViewParams::ViewParams ()
Definition at line 29 of file ViewParams.cpp.
References Base::Subject< MsgType >::Attach(), FC_VIEW_PARAMS, App::GetApplication(), and App::Application::GetParameterGroupByPath().
Referenced by instance().
~ViewParams()
ViewParams::~ViewParams () override default
Member Function Documentation
getAnnotationTextColor()
unsigned long Gui::ViewParams::getAnnotationTextColor () const inline
Definition at line 117 of file ViewParams.h.
getAxisXColor()
unsigned long Gui::ViewParams::getAxisXColor () const inline
Definition at line 117 of file ViewParams.h.
Referenced by Gui::ViewProviderPlane::getColor().
getAxisYColor()
unsigned long Gui::ViewParams::getAxisYColor () const inline
Definition at line 117 of file ViewParams.h.
Referenced by Gui::ViewProviderPlane::getColor().
getAxisZColor()
unsigned long Gui::ViewParams::getAxisZColor () const inline
Definition at line 117 of file ViewParams.h.
Referenced by Gui::ViewProviderPlane::getColor().
getBoundingBoxColor()
unsigned long Gui::ViewParams::getBoundingBoxColor () const inline
Definition at line 117 of file ViewParams.h.
getCoinCycleCheck()
bool Gui::ViewParams::getCoinCycleCheck () const inline
Definition at line 117 of file ViewParams.h.
getDefaultLinkColor()
unsigned long Gui::ViewParams::getDefaultLinkColor () const inline
Definition at line 117 of file ViewParams.h.
getDefaultShapeColor()
unsigned long Gui::ViewParams::getDefaultShapeColor () const inline
Definition at line 117 of file ViewParams.h.
getDefaultShapeLineColor()
unsigned long Gui::ViewParams::getDefaultShapeLineColor () const inline
Definition at line 117 of file ViewParams.h.
Referenced by PartGui::ViewProviderPartExt::ViewProviderPartExt().
getDefaultShapeLineWidth()
int Gui::ViewParams::getDefaultShapeLineWidth () const inline
Definition at line 117 of file ViewParams.h.
Referenced by PartDesignGui::ViewProviderSubShapeBinder::onChanged(), Gui::ViewProviderLink::ViewProviderLink(), and PartGui::ViewProviderPartExt::ViewProviderPartExt().
getDefaultShapePointSize()
int Gui::ViewParams::getDefaultShapePointSize () const inline
Definition at line 117 of file ViewParams.h.
Referenced by PartGui::ViewProviderPartExt::ViewProviderPartExt().
getDefaultShapeTransparency()
int Gui::ViewParams::getDefaultShapeTransparency () const inline
Definition at line 117 of file ViewParams.h.
Referenced by PartDesignGui::ViewProviderSubShapeBinder::onChanged().
getDefaultShapeVertexColor()
unsigned long Gui::ViewParams::getDefaultShapeVertexColor () const inline
Definition at line 117 of file ViewParams.h.
Referenced by PartGui::ViewProviderPartExt::ViewProviderPartExt().
getDraggerScale()
double Gui::ViewParams::getDraggerScale () const inline
Definition at line 117 of file ViewParams.h.
getEnablePropertyViewForInactiveDocument()
bool Gui::ViewParams::getEnablePropertyViewForInactiveDocument () const inline
Definition at line 117 of file ViewParams.h.
getEnableSelection()
bool Gui::ViewParams::getEnableSelection () const inline
Definition at line 117 of file ViewParams.h.
getHandle()
ParameterGrp::handle Gui::ViewParams::getHandle () inline
Definition at line 82 of file ViewParams.h.
getMarkerSize()
int Gui::ViewParams::getMarkerSize () const inline
Definition at line 117 of file ViewParams.h.
getPropertyViewTimer()
unsigned long Gui::ViewParams::getPropertyViewTimer () const inline
Definition at line 117 of file ViewParams.h.
getRandomColor()
bool Gui::ViewParams::getRandomColor () const inline
Definition at line 117 of file ViewParams.h.
getRenderCache()
int Gui::ViewParams::getRenderCache () const inline
Definition at line 117 of file ViewParams.h.
Referenced by Gui::View3DInventorViewer::setRenderCache().
getShowSelectionBoundingBox()
bool Gui::ViewParams::getShowSelectionBoundingBox () const inline
Definition at line 117 of file ViewParams.h.
Referenced by Gui::SoFCPathAnnotation::GLRenderBelowPath().
getUseNewSelection()
bool Gui::ViewParams::getUseNewSelection () const inline
Definition at line 117 of file ViewParams.h.
Referenced by Gui::SoFCSelection::SoFCSelection(), and Gui::ViewProvider::useNewSelectionModel().
getUseSelectionRoot()
bool Gui::ViewParams::getUseSelectionRoot () const inline
Definition at line 117 of file ViewParams.h.
instance()
ViewParams * ViewParams::instance () static
Definition at line 54 of file ViewParams.cpp.
References ViewParams().
Referenced by Gui::SoFCSelectionRoot::_renderPrivate(), Gui::ViewProviderLine::attach(), Gui::ViewProviderPlane::getColor(), Gui::LinkInfo::getSnapshot(), Gui::SoFCPathAnnotation::GLRenderBelowPath(), PartDesignGui::ViewProviderSubShapeBinder::onChanged(), Gui::SoFCSelectionRoot::renderPrivate(), AssemblyGui::ViewProviderAssembly::setDragger(), Gui::ViewProviderDragger::setEdit(), Gui::View3DInventorViewer::setRenderCache(), Gui::PropertyView::showEvent(), Gui::SoFCSelection::SoFCSelection(), Gui::ViewProvider::useNewSelectionModel(), Gui::ViewProviderLink::ViewProviderLink(), MeasureGui::ViewProviderMeasureDistance::ViewProviderMeasureDistance(), and PartGui::ViewProviderPartExt::ViewProviderPartExt().
OnChange()
void ViewParams::OnChange (Base::Subject< const char * > & , const char * sReason) override
Definition at line 42 of file ViewParams.cpp.
References FC_VIEW_PARAMS.
setAnnotationTextColor()
void Gui::ViewParams::setAnnotationTextColor (unsigned long _v) inline
Definition at line 117 of file ViewParams.h.
setAxisXColor()
void Gui::ViewParams::setAxisXColor (unsigned long _v) inline
Definition at line 117 of file ViewParams.h.
setAxisYColor()
void Gui::ViewParams::setAxisYColor (unsigned long _v) inline
Definition at line 117 of file ViewParams.h.
setAxisZColor()
void Gui::ViewParams::setAxisZColor (unsigned long _v) inline
Definition at line 117 of file ViewParams.h.
setBoundingBoxColor()
void Gui::ViewParams::setBoundingBoxColor (unsigned long _v) inline
Definition at line 117 of file ViewParams.h.
setCoinCycleCheck()
void Gui::ViewParams::setCoinCycleCheck (bool _v) inline
Definition at line 117 of file ViewParams.h.
setDefaultLinkColor()
void Gui::ViewParams::setDefaultLinkColor (unsigned long _v) inline
Definition at line 117 of file ViewParams.h.
setDefaultShapeColor()
void Gui::ViewParams::setDefaultShapeColor (unsigned long _v) inline
Definition at line 117 of file ViewParams.h.
setDefaultShapeLineColor()
void Gui::ViewParams::setDefaultShapeLineColor (unsigned long _v) inline
Definition at line 117 of file ViewParams.h.
setDefaultShapeLineWidth()
void Gui::ViewParams::setDefaultShapeLineWidth (int _v) inline
Definition at line 117 of file ViewParams.h.
setDefaultShapePointSize()
void Gui::ViewParams::setDefaultShapePointSize (int _v) inline
Definition at line 117 of file ViewParams.h.
setDefaultShapeTransparency()
void Gui::ViewParams::setDefaultShapeTransparency (int _v) inline
Definition at line 117 of file ViewParams.h.
setDefaultShapeVertexColor()
void Gui::ViewParams::setDefaultShapeVertexColor (unsigned long _v) inline
Definition at line 117 of file ViewParams.h.
setDraggerScale()
void Gui::ViewParams::setDraggerScale (double _v) inline
Definition at line 117 of file ViewParams.h.
setEnablePropertyViewForInactiveDocument()
void Gui::ViewParams::setEnablePropertyViewForInactiveDocument (bool _v) inline
Definition at line 117 of file ViewParams.h.
setEnableSelection()
void Gui::ViewParams::setEnableSelection (bool _v) inline
Definition at line 117 of file ViewParams.h.
setMarkerSize()
void Gui::ViewParams::setMarkerSize (int _v) inline
Definition at line 117 of file ViewParams.h.
setPropertyViewTimer()
void Gui::ViewParams::setPropertyViewTimer (unsigned long _v) inline
Definition at line 117 of file ViewParams.h.
setRandomColor()
void Gui::ViewParams::setRandomColor (bool _v) inline
Definition at line 117 of file ViewParams.h.
setRenderCache()
void Gui::ViewParams::setRenderCache (int _v) inline
Definition at line 117 of file ViewParams.h.
setShowSelectionBoundingBox()
void Gui::ViewParams::setShowSelectionBoundingBox (bool _v) inline
Definition at line 117 of file ViewParams.h.
setUseNewSelection()
void Gui::ViewParams::setUseNewSelection (bool _v) inline
Definition at line 117 of file ViewParams.h.
setUseSelectionRoot()
void Gui::ViewParams::setUseSelectionRoot (bool _v) inline
Definition at line 117 of file ViewParams.h.
The documentation for this class was generated from the following files:
ViewParams.h
ViewParams.cpp