FreeCAD: MeshCore::MeshPoint Class Reference
MeshCore::MeshPoint Class Reference
#include <Elements.h>
Public Types
enum TFlagType {
INVALID = 1, VISIT = 2, SEGMENT = 4, MARKED = 8,
SELECTED = 16, REV = 32, TMP0 = 64, TMP1 = 128
}
Public Types inherited from Base::Vector3< float_type >
using num_type = float_type
using traits_type = float_traits< num_type >
Public Member Functions
Construction
MeshPoint ()
MeshPoint (float x, float y, float z)
MeshPoint (const Base::Vector3f &rclPt)
MeshPoint (const MeshPoint &rclPt)=default
MeshPoint (MeshPoint &&rclPt)=default
~MeshPoint ()=default
Public Member Functions inherited from Base::Vector3< float_type >
float_type & operator[] (unsigned short usIndex)
Returns a reference to a coordinate. usIndex must be in the range [0,2].
const float_type & operator[] (unsigned short usIndex) const
Returns a const reference to a coordinate. usIndex must be in the range [0,2].
Vector3 operator+ (const Vector3< float_type > &rcVct) const
Vector addition.
Vector3 operator& (const Vector3< float_type > &rcVct) const
Vector3 operator- (const Vector3< float_type > &rcVct) const
Vector subtraction.
Vector3 operator- () const
Negative vector.
Vector3 & operator+= (const Vector3< float_type > &rcVct)
Vector summation.
Vector3 & operator-= (const Vector3< float_type > &rcVct)
Vector subtraction.
Vector3 operator* (float_type fScale) const
Vector scaling.
Vector3 operator/ (float_type fDiv) const
Vector3 & operator*= (float_type fScale)
Vector3 & operator/= (float_type fDiv)
Vector3 & operator= (const Vector3< float_type > &v)=default
Assignment.
Vector3 & operator= (Vector3< float_type > &&v) noexcept=default
float_type operator* (const Vector3< float_type > &rcVct) const
Scalar product.
float_type Dot (const Vector3< float_type > &rcVct) const
Scalar product.
Vector3 operator% (const Vector3< float_type > &rcVct) const
Cross product.
Vector3 Cross (const Vector3< float_type > &rcVct) const
Cross product.
bool operator!= (const Vector3< float_type > &rcVct) const
Comparing for inequality.
bool operator== (const Vector3< float_type > &rcVct) const
Comparing for equality.
bool IsOnLineSegment (const Vector3< float_type > &startVct, const Vector3< float_type > &endVct) const
Check if Vector is on a line segment.
void ScaleX (float_type f)
void ScaleY (float_type f)
void ScaleZ (float_type f)
void Scale (float_type fX, float_type fY, float_type fZ)
void MoveX (float_type f)
void MoveY (float_type f)
void MoveZ (float_type f)
void Move (float_type fX, float_type fY, float_type fZ)
void RotateX (float_type f)
void RotateY (float_type f)
void RotateZ (float_type f)
void Set (float_type fX, float_type fY, float_type fZ)
float_type Length () const
Length of the vector.
float_type Sqr () const
Squared length of the vector.
Vector3 & Normalize ()
Set length to 1.
bool IsNull () const
Checks whether this is the null vector.
float_type GetAngle (const Vector3 &rcVect) const
Get angle between both vectors. The returned value lies in the interval [0,pi].
float_type GetAngleOriented (const Vector3 &rcVect, const Vector3 &norm) const
void TransformToCoordinateSystem (const Vector3 &rclBase, const Vector3 &rclDirX, const Vector3 &rclDirY)
bool IsEqual (const Vector3 &rclPnt, float_type tol) const
IsEqual.
bool IsParallel (const Vector3 &rclDir, float_type tol) const
bool IsNormal (const Vector3 &rclDir, float_type tol) const
Vector3 & ProjectToPlane (const Vector3 &rclBase, const Vector3 &rclNorm)
Projects this point onto the plane given by the base rclBase and the normal rclNorm.
void ProjectToPlane (const Vector3 &rclBase, const Vector3 &rclNorm, Vector3 &rclProj) const
Vector3 & ProjectToLine (const Vector3 &rclPoint, const Vector3 &rclLine)
Vector3 Perpendicular (const Vector3 &rclBase, const Vector3 &rclDir) const
float_type DistanceToPlane (const Vector3 &rclBase, const Vector3 &rclNorm) const
float_type DistanceToLine (const Vector3 &rclBase, const Vector3 &rclDirect) const
Computes the distance from this point to the line given by rclBase and rclDirect.
Vector3 DistanceToLineSegment (const Vector3 &rclP1, const Vector3 &rclP2) const
Vector3 (float_type fx=0.0, float_type fy=0.0, float_type fz=0.0)
Construction.
Vector3 (const Vector3< float_type > &v)=default
Vector3 (Vector3< float_type > &&v) noexcept=default
~Vector3 ()=default
Flag state
Note
All flag methods are const as they do NOT change the actual behaviour of the object
unsigned char _ucFlag
unsigned long _ulProp
void SetFlag (TFlagType tF) const
void ResetFlag (TFlagType tF) const
bool IsFlag (TFlagType tF) const
void ResetInvalid () const
void SetInvalid () const
bool IsValid () const
void SetProperty (unsigned long uP) const
MeshPoint & operator= (const MeshPoint &rclPt)=default
MeshPoint & operator= (MeshPoint &&rclPt)=default
bool operator== (const MeshPoint &rclPt) const
bool operator== (const Base::Vector3f &rclV) const
bool operator< (const MeshPoint &rclPt) const
Additional Inherited Members
Static Public Member Functions inherited from Base::Vector3< float_type >
static num_type epsilon ()
Public Attributes inherited from Base::Vector3< float_type >
float_type x
float_type y
float_type z
Detailed Description
The MeshPoint class represents a point in the mesh data structure. The class inherits from Vector3f and provides some additional information such as flag state and property value. The flags can be modified by the Set() and Reset() and queried by IsFlag(). A point can temporary be in an invalid state (e.g during deletion of several points), but must not be set in general, i.e. always usable within a mesh-internal algorithm.
Note: The status flag SEGMENT mark a point to be part of certain subset, a segment. This flag must not be set by any algorithm unless it adds or removes points to a segment.
Note: The status flag SELECTED mark a point to be selected which is e.g. used in the GUI. This flag must not be set by any algorithm unless it adds or removes points to the selection.
Definition at line 124 of file Elements.h.
Member Enumeration Documentation
TFlagType
enum MeshCore::MeshPoint::TFlagType
Enumerator
INVALID
VISIT
SEGMENT
MARKED
SELECTED
REV
TMP0
TMP1
Definition at line 127 of file Elements.h.
Constructor & Destructor Documentation
MeshPoint() [1/5]
MeshCore::MeshPoint::MeshPoint () inline
Definition at line 141 of file Elements.h.
MeshPoint() [2/5]
MeshCore::MeshPoint::MeshPoint (float x, float y, float z) inline
Definition at line 876 of file Elements.h.
MeshPoint() [3/5]
MeshCore::MeshPoint::MeshPoint (const Base::Vector3f & rclPt) inline
Definition at line 882 of file Elements.h.
MeshPoint() [4/5]
MeshCore::MeshPoint::MeshPoint (const MeshPoint & rclPt) inline default
MeshPoint() [5/5]
MeshCore::MeshPoint::MeshPoint (MeshPoint && rclPt) inline default
~MeshPoint()
MeshCore::MeshPoint::~MeshPoint () default
Member Function Documentation
IsFlag()
bool MeshCore::MeshPoint::IsFlag (TFlagType tF) const inline
Definition at line 165 of file Elements.h.
Referenced by MeshCore::MeshKernel::GetPointFacets().
IsValid()
bool MeshCore::MeshPoint::IsValid () const inline
Definition at line 177 of file Elements.h.
Referenced by MeshCore::MeshKernel::DeletePoints().
operator<()
bool MeshCore::MeshPoint::operator< (const MeshPoint & rclPt) const inline
Definition at line 898 of file Elements.h.
References MeshCore::MeshGeomFacet::_aclPoints, and Base::Vector3< float_type >::Normalize().
operator=() [1/2]
MeshPoint& MeshCore::MeshPoint::operator= (const MeshPoint & rclPt) inline default
operator=() [2/2]
MeshPoint& MeshCore::MeshPoint::operator= (MeshPoint && rclPt) inline default
operator==() [1/2]
bool MeshCore::MeshPoint::operator== (const Base::Vector3f & rclV) const inline
Definition at line 893 of file Elements.h.
References MeshCore::MeshGeomFacet::_aclPoints, Base::Vector3< float_type >::DistanceToPlane(), and MeshCore::MeshGeomFacet::GetNormal().
operator==() [2/2]
bool MeshCore::MeshPoint::operator== (const MeshPoint & rclPt) const inline
Definition at line 888 of file Elements.h.
ResetFlag()
void MeshCore::MeshPoint::ResetFlag (TFlagType tF) const inline
Definition at line 161 of file Elements.h.
ResetInvalid()
void MeshCore::MeshPoint::ResetInvalid () const inline
Definition at line 169 of file Elements.h.
SetFlag()
void MeshCore::MeshPoint::SetFlag (TFlagType tF) const inline
Definition at line 157 of file Elements.h.
SetInvalid()
void MeshCore::MeshPoint::SetInvalid () const inline
Definition at line 173 of file Elements.h.
SetProperty()
void MeshCore::MeshPoint::SetProperty (unsigned long uP) const inline
Definition at line 181 of file Elements.h.
Member Data Documentation
_ucFlag
unsigned char MeshCore::MeshPoint::_ucFlag mutable
Flag member
Definition at line 197 of file Elements.h.
_ulProp
unsigned long MeshCore::MeshPoint::_ulProp mutable
Free usable property
Definition at line 198 of file Elements.h.
Referenced by MeshCore::MeshBuilder::AddFacet(), and MeshCore::MeshKernel::DeletePoints().
The documentation for this class was generated from the following file:
Elements.h