FreeCAD: Gui::VectorListEditor Class Reference
Gui::VectorListEditor Class Reference
#include <VectorListEditor.h>
Public Member Functions
VectorListEditor (int decimals, QWidget *parent=nullptr)
~VectorListEditor () override
void setValues (const QList< Base::Vector3d > &)
const QList< Base::Vector3d > & getValues () const
void accept () override
void reject () override
Detailed Description
Definition at line 106 of file VectorListEditor.h.
Constructor & Destructor Documentation
VectorListEditor()
VectorListEditor::VectorListEditor (int decimals, QWidget * parent = nullptr) explicit
Definition at line 288 of file VectorListEditor.cpp.
References accept(), draftgeoutils.intersections::connect(), and reject().
~VectorListEditor()
VectorListEditor::~VectorListEditor () override default
Member Function Documentation
accept()
void VectorListEditor::accept () override
Definition at line 360 of file VectorListEditor.cpp.
References Gui::VectorTableModel::values().
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), VectorListEditor(), and MaterialEditor.MaterialEditor::verify().
getValues()
const QList< Base::Vector3d > & VectorListEditor::getValues () const
Definition at line 355 of file VectorListEditor.cpp.
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::loadDefaults(), and draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onSaveStyle().
reject()
void VectorListEditor::reject () override
Definition at line 366 of file VectorListEditor.cpp.
Referenced by bimcommands.BimReorder.BIM_Reorder_TaskPanel::accept(), draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), draftguitools.gui_selectplane.Draft_SelectPlane::action(), JointObject.TaskAssemblyCreateJoint::autoClosedOnTransactionChange(), femexamples.examplesgui.FemExamples::clicked(), CommandCreateView.TaskAssemblyCreateView::KeyboardEvent(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), bimcommands.BimProjectManager.BIM_ProjectManager::loadTemplate(), bimcommands.BimLibrary.BIM_Library_TaskPanel::mouseClick(), bimcommands.BimProjectManager.BIM_ProjectManager::saveTemplate(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and VectorListEditor().
setValues()
void VectorListEditor::setValues (const QList< Base::Vector3d > & v)
Definition at line 337 of file VectorListEditor.cpp.
References Gui::VectorTableModel::data(), Gui::VectorTableModel::setValues(), and TestSpreadsheet::v.
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onLoadStyle().
The documentation for this class was generated from the following files:
VectorListEditor.h
VectorListEditor.cpp