FreeCAD: Gui::TaskView::TaskSketcherCreateCommands Class Reference
Gui::TaskView::TaskSketcherCreateCommands Class Reference
#include <TaskSketcherCreateCommands.h>
Public Member Functions
TaskSketcherCreateCommands (QWidget *parent=nullptr)
~TaskSketcherCreateCommands () override
void OnChange (Gui::SelectionSingleton::SubjectType &rCaller, Gui::SelectionSingleton::MessageType Reason) override
Observer message from the Selection.
Public Member Functions inherited from Gui::TaskView::TaskBox
TaskBox (QWidget *parent=nullptr)
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
QSize minimumSizeHint () const override
~TaskBox () override
void hideGroupBox ()
bool isGroupVisible () const
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (QWidget *parent=nullptr)
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
QBoxLayout * groupLayout ()
void setScheme (ActionPanelScheme *pointer)
bool isExpandable () const
bool hasHeader () const
QString headerText () const
QSize minimumSizeHint () const override
Protected Member Functions
void changeEvent (QEvent *e) override
Protected Member Functions inherited from Gui::TaskView::TaskBox
void showEvent (QShowEvent *) override
void actionEvent (QActionEvent *) override
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
void paintEvent (QPaintEvent *event) override
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void showHide ()
void setExpandable (bool expandable=true)
void setHeader (bool enable=true)
void setHeaderText (const QString &title)
void setHeaderIcon (const QPixmap &icon)
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Protected Attributes inherited from QSint::ActionGroup
double m_foldStep
double m_foldDelta
double m_fullHeight
double m_tempHeight
int m_foldDirection
QPixmap m_foldPixmap
class TaskHeader * myHeader
class TaskGroup * myGroup
QWidget * myDummy
ActionPanelScheme * myScheme
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Detailed Description
Definition at line 42 of file TaskSketcherCreateCommands.h.
Constructor & Destructor Documentation
TaskSketcherCreateCommands()
TaskSketcherCreateCommands::TaskSketcherCreateCommands (QWidget * parent = nullptr) explicit
Definition at line 35 of file TaskSketcherCreateCommands.cpp.
References Base::Subject< MsgType >::Attach(), and Gui::Selection().
~TaskSketcherCreateCommands()
TaskSketcherCreateCommands::~TaskSketcherCreateCommands () override
Definition at line 56 of file TaskSketcherCreateCommands.cpp.
References Base::Subject< MsgType >::Detach(), and Gui::Selection().
Member Function Documentation
changeEvent()
void TaskSketcherCreateCommands::changeEvent (QEvent * e) override protected
Definition at line 62 of file TaskSketcherCreateCommands.cpp.
References SCL.SimpleDataTypes::e.
OnChange()
void Gui::TaskView::TaskSketcherCreateCommands::OnChange (Gui::SelectionSingleton::SubjectType & rCaller, Gui::SelectionSingleton::MessageType Reason) override
Observer message from the Selection.
The documentation for this class was generated from the following files:
TaskSketcherCreateCommands.h
TaskSketcherCreateCommands.cpp