FreeCAD: App::PropertyVectorDistance Class Reference
App::PropertyVectorDistance Class Reference
#include <PropertyGeo.h>
Public Member Functions
PropertyVectorDistance ()
~PropertyVectorDistance () override
Base::Unit getUnit () const override
const char * getEditorName () const override
Get the class name of the associated property editor item.
Public Member Functions inherited from App::PropertyVector
PropertyVector ()
~PropertyVector () override
void setValue (const Base::Vector3d &vec)
void setValue (double x, double y, double z)
void getPaths (std::vector< ObjectIdentifier > &paths) const override
Get valid paths for this property; used by auto completer.
const Base::Vector3d & getValue () const
PyObject * getPyObject () override
void setPyObject (PyObject *) override
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
Property * Copy () const override
Returns a new copy of the property (mainly for Undo/Redo and transactions)
void Paste (const Property &from) override
Paste the value from the property (mainly for Undo/Redo and transactions)
unsigned int getMemSize () const override
const boost::any getPathValue (const ObjectIdentifier &path) const override
Get value of property.
bool getPyPathValue (const ObjectIdentifier &path, Py::Object &res) const override
Get Python value of property.
bool isSame (const Property &other) const override
Compare if this property has the same content as the given one.
Public Member Functions inherited from App::Property
Property ()
~Property () override
const char * getName () const
bool hasName () const
std::string getFullName () const
short getType () const
Get the type of the property in the container.
const char * getGroup () const
Get the group of this property.
const char * getDocumentation () const
Get the documentation of this property.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
PropertyContainer * getContainer () const
Get a pointer to the PropertyContainer derived class the property belongs to.
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual void afterRestore ()
virtual void onContainerRestored ()
void touch ()
Set the property touched.
bool isTouched () const
Test if this property is touched.
void purgeTouched ()
Reset this property touched.
unsigned long getStatus () const
return the status bits
bool testStatus (Status pos) const
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
bool isReadOnly () const
void setSinglePrecision (bool single)
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
int64_t getID () const
virtual void beforeSave () const
Property (const Property &)=delete
Property & operator= (const Property &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Public Types inherited from App::Property
enum Status {
Touched = 0, Immutable = 1, ReadOnly = 2, Hidden = 3,
Transient = 4, MaterialEdit = 5, NoMaterialListEdit = 6, Output = 7,
LockDynamic = 8, NoModify = 9, PartialTrigger = 10, NoRecompute = 11,
Single = 12, Ordered = 13, EvalOnRestore = 14, Busy = 15,
CopyOnChange, UserEdit = 17, PropStaticBegin = 21, PropDynamic = 21,
PropNoPersist = 22, PropNoRecompute = 23, PropReadOnly = 24, PropTransient = 25,
PropHidden = 26, PropOutput = 27, PropStaticEnd = 28, User1 = 28,
User2 = 29, User3 = 30, User4 = 31
}
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes inherited from App::Property
boost::signals2::signal< void(const App::Property &)> signalChanged
Protected Member Functions inherited from App::Property
virtual void hasSetValue ()
Gets called by all setValue() methods after the value has changed.
virtual void aboutToSetValue ()
Gets called by all setValue() methods before the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
std::string getFileName (const char *postfix=0, const char *prefix=0) const
Return a file name suitable for saving this property.
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Detailed Description
Definition at line 125 of file PropertyGeo.h.
Constructor & Destructor Documentation
PropertyVectorDistance()
PropertyVectorDistance::PropertyVectorDistance () default
A constructor. A more elaborate description of the constructor.
~PropertyVectorDistance()
PropertyVectorDistance::~PropertyVectorDistance () override default
A destructor. A more elaborate description of the destructor.
Member Function Documentation
getEditorName()
const char* App::PropertyVectorDistance::getEditorName () const inline override virtual
Get the class name of the associated property editor item.
Reimplemented from App::PropertyVector.
Definition at line 147 of file PropertyGeo.h.
getUnit()
Base::Unit App::PropertyVectorDistance::getUnit () const inline override virtual
Reimplemented from App::PropertyVector.
Definition at line 142 of file PropertyGeo.h.
References Base::Unit::Length.
Referenced by FemGui::BoxWidget::setViewProvider(), FemGui::CylinderWidget::setViewProvider(), FemGui::PlaneWidget::setViewProvider(), and FemGui::SphereWidget::setViewProvider().
The documentation for this class was generated from the following files:
PropertyGeo.h
PropertyGeo.cpp