FreeCAD: Path::Toolpath Class Reference
Path::Toolpath Class Reference
#include <Path.h>
Public Member Functions
Toolpath ()
Toolpath (const Toolpath &)
~Toolpath () override
Toolpath & operator= (const Toolpath &)
unsigned int getMemSize () const override
void Save (Base::Writer &) const override
void Restore (Base::XMLReader &) override
void SaveDocFile (Base::Writer &writer) const override
void RestoreDocFile (Base::Reader &reader) override
void clear ()
void addCommand (const Command &Cmd)
void insertCommand (const Command &Cmd, int)
void deleteCommand (int)
double getLength ()
double getCycleTime (double, double, double, double)
void recalculate ()
void setFromGCode (const std::string)
std::string toGCode () const
Base::BoundBox3d getBoundBox () const
unsigned int getSize () const
const std::vector< Command * > & getCommands () const
const Command & getCommand (unsigned int pos) const
const Base::Vector3d & getCenter () const
void setCenter (const Base::Vector3d &c)
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Static Public Attributes
static const int SchemaVersion = 2
Protected Attributes
std::vector< Command * > vpcCommands
Base::Vector3d center
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
The representation of a CNC Toolpath
Definition at line 58 of file Mod/CAM/App/Path.h.
Constructor & Destructor Documentation
Toolpath() [1/2]
Toolpath::Toolpath ()
Definition at line 40 of file Mod/CAM/App/Path.cpp.
Toolpath() [2/2]
Toolpath::Toolpath (const Toolpath & otherPath)
Definition at line 43 of file Mod/CAM/App/Path.cpp.
References recalculate().
~Toolpath()
Toolpath::~Toolpath () override
Definition at line 51 of file Mod/CAM/App/Path.cpp.
References clear().
Member Function Documentation
addCommand()
void Toolpath::addCommand (const Command & Cmd)
Definition at line 84 of file Mod/CAM/App/Path.cpp.
References Path.Op.Gui.Adaptive::Command, recalculate(), and vpcCommands.
Referenced by insertCommand().
clear()
void Toolpath::clear ()
Definition at line 75 of file Mod/CAM/App/Path.cpp.
References recalculate(), and vpcCommands.
Referenced by src.Mod.Test.Document.DocumentObserverCases.Observer::__init__(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::__init__(), operator=(), setFromGCode(), and ~Toolpath().
deleteCommand()
void Toolpath::deleteCommand (int pos)
Definition at line 106 of file Mod/CAM/App/Path.cpp.
References RobotExample::pos, recalculate(), and vpcCommands.
getBoundBox()
Base::BoundBox3d Toolpath::getBoundBox () const
Definition at line 298 of file Mod/CAM/App/Path.cpp.
References BoundBoxSegmentVisitor::bb, and Path::PathSegmentWalker::walk().
getCenter()
const Base::Vector3d& Path::Toolpath::getCenter () const inline
Definition at line 124 of file Mod/CAM/App/Path.h.
Referenced by Path::PathSegmentWalker::walk().
getCommand()
const Command& Path::Toolpath::getCommand (unsigned int pos) const inline
Definition at line 118 of file Mod/CAM/App/Path.h.
Referenced by PathGui::ViewProviderPath::getElement(), and Path::PathSegmentWalker::walk().
getCommands()
const std::vector<Command*>& Path::Toolpath::getCommands () const inline
Definition at line 114 of file Mod/CAM/App/Path.h.
Referenced by Path::FeatureCompound::execute().
getCycleTime()
double Toolpath::getCycleTime (double hFeed, double vFeed, double hRapid, double vRapid)
Definition at line 150 of file Mod/CAM/App/Path.cpp.
References center, Base::Console(), App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), RobotExample::l, FreeCADInit::Length, vpcCommands, Base::ConsoleSingleton::Warning(), and Base::Vector3< float_type >::z.
Referenced by Path.Main.Job.ObjectJob::execute().
getLength()
double Toolpath::getLength ()
Definition at line 121 of file Mod/CAM/App/Path.cpp.
References center, RobotExample::l, FreeCADInit::Length, and vpcCommands.
getMemSize()
unsigned int Toolpath::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Implements Base::Persistence.
Definition at line 459 of file Mod/CAM/App/Path.cpp.
References toGCode().
Referenced by Path::PropertyPath::getMemSize().
getSize()
unsigned int Path::Toolpath::getSize () const inline
Definition at line 110 of file Mod/CAM/App/Path.h.
Referenced by PathGui::ViewProviderPath::getElement(), Save(), PathGui::ViewProviderPath::updateShowConstraints(), VisualPathSegmentVisitor::VisualPathSegmentVisitor(), and Path::PathSegmentWalker::walk().
insertCommand()
void Toolpath::insertCommand (const Command & Cmd, int pos)
Definition at line 91 of file Mod/CAM/App/Path.cpp.
References addCommand(), Path.Op.Gui.Adaptive::Command, RobotExample::pos, recalculate(), and vpcCommands.
operator=()
Toolpath & Toolpath::operator= (const Toolpath & otherPath)
Definition at line 56 of file Mod/CAM/App/Path.cpp.
References center, clear(), Path.Op.Gui.Adaptive::Command, SplineSurface::i, recalculate(), and vpcCommands.
recalculate()
void Toolpath::recalculate ()
Definition at line 393 of file Mod/CAM/App/Path.cpp.
References center, SCL.SimpleDataTypes::e, Base::Placement::getPosition(), Base::Rotation::getValue(), buildPsets::p, Robot::toFrame(), Robot::toPlacement(), vpcCommands, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by addCommand(), clear(), deleteCommand(), insertCommand(), operator=(), setCenter(), setFromGCode(), and Toolpath().
Restore()
void Toolpath::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Definition at line 507 of file Mod/CAM/App/Path.cpp.
References DrawingExample::file, and TechDrawTools.TaskFillTemplateFields::reader.
RestoreDocFile()
void Toolpath::RestoreDocFile (Base::Reader &) override virtual
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data. Again you have to apply for the call of this method in the Restore() call:
void PropertyMeshKernel::Restore(Base::XMLReader &reader)
{
  reader.readElement("Mesh");
  std::string file (reader.getAttribute("file") );
  if(file == "")
  {
    // read XML
    MeshCore::MeshDocXML restorer(*_pcMesh);
    restorer.Restore(reader);
  }else{
    // initiate a file read
    reader.addFile(file.c_str(),this);
 }
}
After you issued the reader.addFile() your RestoreDocFile() is called:
void PropertyMeshKernel::RestoreDocFile(Base::Reader &reader)
{
    _pcMesh->Read( reader );
}
See also
Base::Reader,Base::XMLReader
Reimplemented from Base::Persistence.
Definition at line 518 of file Mod/CAM/App/Path.cpp.
References TechDrawTools.TaskFillTemplateFields::reader, and setFromGCode().
Referenced by Path::PropertyPath::RestoreDocFile().
Save()
void Toolpath::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Definition at line 476 of file Mod/CAM/App/Path.cpp.
References Base::Writer::addFile(), center, Base::Writer::decInd(), getSize(), SplineSurface::i, Base::Writer::incInd(), Base::Writer::ind(), Base::Writer::isForceXML(), Base::Writer::ObjectName, saveCenter(), SchemaVersion, Base::Writer::Stream(), and vpcCommands.
Referenced by Path::PropertyPath::Save().
SaveDocFile()
void Toolpath::SaveDocFile (Base::Writer &) const override virtual
This method is used to save large amounts of data to a binary file. Sometimes it makes no sense to write property data as XML. In case the amount of data is too big or the data type has a more effective way to save itself. In this cases it is possible to write the data in a separate file inside the document archive. In case you want do so you have to re-implement SaveDocFile(). First, you have to inform the framework in Save() that you want do so. Here an example from the Mesh module which can save a (pontetionaly big) triangle mesh:
void PropertyMeshKernel::Save (Base::Writer &writer) const
{
  if (writer.isForceXML())
  {
    writer << writer.ind() << "<Mesh>" << std::endl;
    MeshCore::MeshDocXML saver(*_pcMesh);
    saver.Save(writer);
  }else{
   writer << writer.ind() << "<Mesh file=\"" << writer.addFile("MeshKernel.bms", this) <<
"\"/>" << std::endl;
}
The writer.isForceXML() is an indication to force you to write XML. Regardless of size and effectiveness. The second part informs the Base::writer through writer.addFile("MeshKernel.bms", this) that this object wants to write a file with the given name. The method addFile() returns a unique name that then is written in the XML stream. This allows your RestoreDocFile() method to identify and read the file again. Later your SaveDocFile() method is called as many times as you issued the addFile() call:
 void
PropertyMeshKernel::SaveDocFile (Base::Writer &writer) const
{
    _pcMesh->Write( writer );
}
In this method you can simply stream your content to the file (Base::Writer inheriting from ostream).
Reimplemented from Base::Persistence.
Definition at line 499 of file Mod/CAM/App/Path.cpp.
References Base::Writer::Stream(), and toGCode().
setCenter()
void Toolpath::setCenter (const Base::Vector3d & c)
Definition at line 464 of file Mod/CAM/App/Path.cpp.
References SCL.SimpleDataTypes::c, center, and recalculate().
Referenced by Path::PropertyPath::Restore(), and draftguitools.gui_trackers.arcTracker::setBy3Points().
setFromGCode()
void Toolpath::setFromGCode (const std::string instr)
Definition at line 328 of file Mod/CAM/App/Path.cpp.
References bulkAddCommand(), clear(), recalculate(), Path.Post.scripts.refactored_centroid_post::str, and vpcCommands.
Referenced by RestoreDocFile().
toGCode()
std::string Toolpath::toGCode () const
Definition at line 382 of file Mod/CAM/App/Path.cpp.
References result, and vpcCommands.
Referenced by getMemSize(), and SaveDocFile().
Member Data Documentation
center
Base::Vector3d Path::Toolpath::center protected
Definition at line 134 of file Mod/CAM/App/Path.h.
Referenced by drafttaskpanels.task_polararray.TaskPanelPolarArray::accept(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::accept(), draftguitools.gui_polygons.Polygon::action(), draftguitools.gui_arcs.Arc::action(), draftguitools.gui_offset.Offset::action(), draftguitools.gui_dimensions.Dimension::action(), draftguitools.gui_scale.Scale::build_copy_subelements_command(), draftguitools.gui_rotate.Rotate::build_copy_subelements_command(), draftguitools.gui_rotate.Rotate::build_rotate_subelements_command(), draftguitools.gui_scale.Scale::build_scale_subelements_command(), draftguitools.gui_dimensions.Dimension::create_angle_dimension(), drafttaskpanels.task_polararray.TaskPanelPolarArray::create_object(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::create_object(), draftguitools.gui_arcs.Arc::drawArc(), draftguitools.gui_polygons.Polygon::drawPolygon(), Path.Dressup.Gui.AxisMap.ObjectDressup::execute(), getCycleTime(), getLength(), draftguitools.gui_rotate.Rotate::handle_mouse_move_event(), draftguitools.gui_polygons.Polygon::numericInput(), draftguitools.gui_rotate.Rotate::numericInput(), draftguitools.gui_arcs.Arc::numericInput(), draftguitools.gui_polygons.Polygon::numericRadius(), draftguitools.gui_arcs.Arc::numericRadius(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_align(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_front(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_side(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_top(), draftguitools.gui_selectplane.Draft_SelectPlane::on_set_center(), Path.Dressup.Gui.AxisMap.ObjectDressup::onChanged(), operator=(), drafttaskpanels.task_polararray.TaskPanelPolarArray::print_messages(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::print_messages(), recalculate(), drafttaskpanels.task_polararray.TaskPanelPolarArray::reset_point(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::reset_point(), draftguitools.gui_rotate.Rotate::rotate_object(), Save(), draftguitools.gui_scale.Scale::scale_object(), draftguitools.gui_rotate.Rotate::set_center(), draftguitools.gui_rotate.Rotate::set_ghosts(), draftguitools.gui_rotate.Rotate::set_rotation_angle(), and setCenter().
SchemaVersion
const int Path::Toolpath::SchemaVersion = 2 static
Definition at line 130 of file Mod/CAM/App/Path.h.
Referenced by Path::PropertyPath::Restore(), and Save().
vpcCommands
std::vector<Command*> Path::Toolpath::vpcCommands protected
Definition at line 133 of file Mod/CAM/App/Path.h.
Referenced by addCommand(), clear(), deleteCommand(), getCycleTime(), getLength(), insertCommand(), operator=(), recalculate(), Save(), setFromGCode(), and toGCode().
The documentation for this class was generated from the following files:
Mod/CAM/App/Path.h
Mod/CAM/App/Path.cpp