FreeCAD: femexamples.ccx_cantilever_ele_tria6 Namespace Reference
femexamples.ccx_cantilever_ele_tria6 Namespace Reference
Functions
def get_information ()
def get_explanation (header="")
def setup (doc=None, solvertype="ccxtools")
Function Documentation
get_explanation()
def femexamples.ccx_cantilever_ele_tria6.get_explanation (header = "")
Definition at line 41 of file ccx_cantilever_ele_tria6.py.
Referenced by femexamples.ccx_cantilever_ele_tria6.setup().
get_information()
def femexamples.ccx_cantilever_ele_tria6.get_information ()
Definition at line 29 of file ccx_cantilever_ele_tria6.py.
Referenced by femexamples.ccx_cantilever_ele_tria6.setup().
setup()
def femexamples.ccx_cantilever_ele_tria6.setup (doc = None, solvertype = "ccxtools")
Definition at line 59 of file ccx_cantilever_ele_tria6.py.
References femexamples.ccx_cantilever_ele_tria6.get_explanation(), femexamples.ccx_cantilever_ele_tria6.get_information(), femexamples.manager.init_doc(), and femexamples.ccx_cantilever_base_face.setup_cantilever_base_face().