FreeCAD: MeshPartGui::Tessellation Class Reference
MeshPartGui::Tessellation Class Reference
#include <Tessellation.h>
Public Member Functions
Tessellation (QWidget *parent=nullptr)
~Tessellation () override
bool accept ()
Protected Member Functions
void changeEvent (QEvent *e) override
void process (int method, App::Document *doc, const std::list< App::SubObjectT > &)
void saveParameters (int method)
void setFaceColors (int method, App::Document *doc, App::DocumentObject *obj)
void addFaceColors (Mesh::Feature *mesh, const std::vector< App::Color > &colorPerSegm)
QString getMeshingParameters (int method, App::DocumentObject *obj) const
QString getStandardParameters (App::DocumentObject *obj) const
QString getMefistoParameters () const
QString getNetgenParameters () const
std::vector< App::Color > getUniqueColors (const std::vector< App::Color > &colors) const
Detailed Description
Definition at line 69 of file Tessellation.h.
Constructor & Destructor Documentation
Tessellation()
Tessellation::Tessellation (QWidget * parent = nullptr) explicit
Definition at line 54 of file Tessellation.cpp.
References Gui::Command::Doc, doCommand, App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetFloat(), and App::Application::GetParameterGroupByPath().
~Tessellation()
Tessellation::~Tessellation () override default
Member Function Documentation
accept()
bool Tessellation::accept ()
Definition at line 232 of file Tessellation.cpp.
References App::Application::getActiveDocument(), App::GetApplication(), Base::Persistence::getClassTypeId(), Gui::Application::getDocument(), App::Document::getName(), draftutils.gui_utils::getSelection, Part::Feature::getTopoShape(), Gui::Application::Instance, Gui::NoResolve, process(), and Gui::Selection().
Referenced by MeshPartGui::TaskTessellation::accept().
addFaceColors()
void Tessellation::addFaceColors (Mesh::Feature * mesh, const std::vector< App::Color > & colorPerSegm) protected
Definition at line 393 of file Tessellation.cpp.
References Mesh::MeshObject::countFacets(), Mesh::MeshObject::countSegments(), Base::Persistence::getClassTypeId(), Mesh::Segment::getIndices(), Mesh::MeshObject::getSegment(), SplineSurface::i, and Mesh2Shape::mesh.
Referenced by setFaceColors().
changeEvent()
void Tessellation::changeEvent (QEvent * e) override protected
Definition at line 196 of file Tessellation.cpp.
References SCL.SimpleDataTypes::e.
getMefistoParameters()
QString Tessellation::getMefistoParameters () const protected
Definition at line 490 of file Tessellation.cpp.
Referenced by getMeshingParameters().
getMeshingParameters()
QString Tessellation::getMeshingParameters (int method, App::DocumentObject * obj) const protected
Definition at line 432 of file Tessellation.cpp.
References getMefistoParameters(), getNetgenParameters(), getStandardParameters(), and Init::param.
Referenced by process().
getNetgenParameters()
QString Tessellation::getNetgenParameters () const protected
Definition at line 499 of file Tessellation.cpp.
References Init::param.
Referenced by getMeshingParameters().
getStandardParameters()
QString Tessellation::getStandardParameters (App::DocumentObject * obj) const protected
Definition at line 448 of file Tessellation.cpp.
References App::DocumentObject::getDocument(), App::Document::getName(), App::DocumentObject::getNameInDocument(), Gui::Application::Instance, and Init::param.
Referenced by getMeshingParameters().
getUniqueColors()
std::vector< App::Color > Tessellation::getUniqueColors (const std::vector< App::Color > & colors) const protected
Definition at line 416 of file Tessellation.cpp.
References importers.importIFCmulticore::colors.
Referenced by setFaceColors().
process()
void Tessellation::process (int method, App::Document * doc, const std::list< App::SubObjectT > & shapeObjects) protected
Definition at line 302 of file Tessellation.cpp.
References Base::Console(), toolbit-attributes::doc, Gui::Command::Doc, SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), getMeshingParameters(), Path.Log::info(), Init::param, runCommand, saveParameters(), and setFaceColors().
Referenced by accept().
saveParameters()
void Tessellation::saveParameters (int method) protected
Definition at line 355 of file Tessellation.cpp.
References App::GetApplication(), App::Application::GetParameterGroupByPath(), ParameterGrp::SetBool(), and ParameterGrp::SetFloat().
Referenced by process().
setFaceColors()
void Tessellation::setFaceColors (int method, App::Document * doc, App::DocumentObject * obj) protected
Definition at line 369 of file Tessellation.cpp.
References addFaceColors(), toolbit-attributes::doc, getUniqueColors(), Gui::Application::getViewProvider(), and Gui::Application::Instance.
Referenced by process().
The documentation for this class was generated from the following files:
Tessellation.h
Tessellation.cpp