FreeCAD: Gui::TaskMeasure Class Reference
Gui::TaskMeasure Class Reference
#include <TaskMeasure.h>
Public Member Functions
TaskMeasure ()
~TaskMeasure () override
void modifyStandardButtons (QDialogButtonBox *box) override
QDialogButtonBox::StandardButtons getStandardButtons () const override
tells the framework which buttons are wished for the dialog
void invoke ()
void update ()
void close ()
bool apply ()
bool apply (bool reset)
bool reject () override
is called by the framework if the dialog is rejected (Cancel)
void reset ()
bool hasSelection ()
void clearSelection ()
bool eventFilter (QObject *obj, QEvent *event) override
Public Member Functions inherited from Gui::TaskView::TaskDialog
TaskDialog ()
~TaskDialog () override
QWidget * addTaskBox (QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBox (const QPixmap &icon, QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBoxWithoutHeader (QWidget *widget)
void setButtonPosition (ButtonPosition p)
ButtonPosition buttonPosition () const
const std::vector< QWidget * > & getDialogContent () const
bool canClose () const
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
bool isEscapeButtonEnabled () const
void setAutoCloseOnTransactionChange (bool on)
bool isAutoCloseOnTransactionChange () const
void setAutoCloseOnDeletedDocument (bool on)
bool isAutoCloseOnDeletedDocument () const
const std::string & getDocumentName () const
void setDocumentName (const std::string &doc)
void setAutoCloseOnClosedView (bool on)
bool isAutoCloseOnClosedView () const
void associateToObject3dView (App::DocumentObject *obj)
const Gui::MDIView * getAssociatedView () const
void setAssociatedView (const Gui::MDIView *view)
virtual bool isAllowedAlterDocument () const
virtual bool isAllowedAlterView () const
virtual bool isAllowedAlterSelection () const
virtual bool needsFullSpace () const
virtual void open ()
is called by the framework when the dialog is opened
virtual void closed ()
is called by the framework when the dialog is closed
virtual void autoClosedOnTransactionChange ()
virtual void autoClosedOnDeletedDocument ()
virtual void autoClosedOnClosedView ()
virtual void clicked (int)
is called by the framework if a button is clicked which has no accept or reject role
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual void helpRequested ()
is called by the framework if the user press the help button
void emitDestructionSignal ()
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North, South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Protected Attributes inherited from Gui::TaskView::TaskDialog
QPointer< QDialogButtonBox > buttonBox
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Detailed Description
Definition at line 66 of file TaskMeasure.h.
Constructor & Destructor Documentation
TaskMeasure()
TaskMeasure::TaskMeasure ()
Definition at line 63 of file TaskMeasure.cpp.
References Gui::SelectionObserver::attachSelection(), Gui::BitmapFactory(), draftgeoutils.intersections::connect(), Gui::TaskView::TaskDialog::Content, App::GetApplication(), App::MeasureManager::getMeasureTypes(), invoke(), NavigationIndicatorGui::menu, Gui::Selection(), App::Application::setActiveTransaction(), Gui::TaskView::TaskDialog::setAutoCloseOnDeletedDocument(), Gui::TaskView::TaskDialog::setButtonPosition(), Gui::SelectionSingleton::setSelectionStyle(), and Gui::TaskView::TaskDialog::South.
~TaskMeasure()
TaskMeasure::~TaskMeasure () override
Definition at line 170 of file TaskMeasure.cpp.
References Gui::SelectionObserver::detachSelection(), Gui::Selection(), and Gui::SelectionSingleton::setSelectionStyle().
Member Function Documentation
apply() [1/2]
bool TaskMeasure::apply ()
Definition at line 391 of file TaskMeasure.cpp.
Referenced by modifyStandardButtons().
apply() [2/2]
bool TaskMeasure::apply (bool reset)
Definition at line 396 of file TaskMeasure.cpp.
References App::Application::closeActiveTransaction(), App::GetApplication(), reset(), and App::Application::setActiveTransaction().
clearSelection()
void TaskMeasure::clearSelection ()
Definition at line 451 of file TaskMeasure.cpp.
References Gui::SelectionSingleton::clearSelection(), and Gui::Selection().
Referenced by reset(), and update().
close()
void TaskMeasure::close ()
Definition at line 353 of file TaskMeasure.cpp.
References Gui::ControlSingleton::closeDialog(), and Gui::Control().
Referenced by femsolver.reportdialog.ReportDialog::__init__(), TechDrawTools.TaskFillTemplateFields.TaskFillTemplateFields::proceed(), reject(), and femexamples.examplesgui.FemExamples::reject().
eventFilter()
bool TaskMeasure::eventFilter (QObject * obj, QEvent * event) override
Definition at line 484 of file TaskMeasure.cpp.
References Gui::TaskView::TaskDialog::buttonBox, hasSelection(), reject(), and reset().
getStandardButtons()
QDialogButtonBox::StandardButtons Gui::TaskMeasure::getStandardButtons () const inline override virtual
tells the framework which buttons are wished for the dialog
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 93 of file TaskMeasure.h.
hasSelection()
bool TaskMeasure::hasSelection ()
Definition at line 446 of file TaskMeasure.cpp.
References Gui::SelectionSingleton::getSelection(), and Gui::Selection().
Referenced by eventFilter().
invoke()
void TaskMeasure::invoke ()
Definition at line 386 of file TaskMeasure.cpp.
References update().
Referenced by TaskMeasure().
modifyStandardButtons()
void TaskMeasure::modifyStandardButtons (QDialogButtonBox * box) override virtual
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 178 of file TaskMeasure.cpp.
References apply(), MengerSponge::box, draftgeoutils.intersections::connect(), and reset().
reject()
bool TaskMeasure::reject () override virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 410 of file TaskMeasure.cpp.
References close(), App::Application::closeActiveTransaction(), and App::GetApplication().
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and eventFilter().
reset()
void TaskMeasure::reset ()
Definition at line 420 of file TaskMeasure.cpp.
References clearSelection(), and update().
Referenced by apply(), eventFilter(), and modifyStandardButtons().
update()
void TaskMeasure::update ()
Definition at line 242 of file TaskMeasure.cpp.
References clearSelection(), Base::Console(), toolbit-attributes::doc, App::Application::getActiveDocument(), App::GetApplication(), App::DocumentObject::getDocument(), App::DocumentObject::getLinkedObject(), Base::Type::getModuleName(), Base::Type::getName(), Measure::MeasureBase::getResultString(), draftutils.gui_utils::getSelection, App::DocumentObject::getSubObject(), Base::Persistence::getTypeId(), App::MeasureManager::getValidMeasureTypes(), App::MeasureManager::hasMeasureHandler(), Base::BaseClass::isDerivedFrom(), App::MeasureType::measureObject, Base::ConsoleSingleton::Message(), mod, Gui::NoResolve, Measure::MeasureBase::parseSelection(), toolbit-attributes::s, Path.Dressup.Utils::selection(), and Gui::Selection().
Referenced by invoke(), Plot.Plot::plot(), and reset().
The documentation for this class was generated from the following files:
TaskMeasure.h
TaskMeasure.cpp