FreeCAD: ifc2x3.ifcspaceprogram Class Reference
ifc2x3.ifcspaceprogram Class Reference
Public Member Functions
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, inherited4__objecttype, spaceprogramidentifier, maxrequiredarea, minrequiredarea, requestedlocation, standardrequiredarea)
def spaceprogramidentifier ()
def maxrequiredarea ()
def minrequiredarea ()
def requestedlocation ()
def standardrequiredarea ()
def hasinteractionreqsfrom ()
def hasinteractionreqsto ()
Public Member Functions inherited from ifc2x3.ifccontrol
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, inherited4__objecttype)
def controls ()
Public Member Functions inherited from ifc2x3.ifcobject
def objecttype ()
def isdefinedby ()
def wr1 (self)
Public Member Functions inherited from ifc2x3.ifcobjectdefinition
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description)
def hasassignments ()
def isdecomposedby ()
def decomposes ()
def hasassociations ()
Public Member Functions inherited from ifc2x3.ifcroot
def globalid ()
def ownerhistory ()
def name ()
def description ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
spaceprogramidentifier
maxrequiredarea
minrequiredarea
requestedlocation
standardrequiredarea
Public Attributes inherited from ifc2x3.ifcobject
objecttype
Public Attributes inherited from ifc2x3.ifcroot
globalid
ownerhistory
name
description
Detailed Description
Entity ifcspaceprogram definition.
:param spaceprogramidentifier
:type spaceprogramidentifier:ifcidentifier
:param maxrequiredarea
:type maxrequiredarea:ifcareameasure
:param minrequiredarea
:type minrequiredarea:ifcareameasure
:param requestedlocation
:type requestedlocation:ifcspatialstructureelement
:param standardrequiredarea
:type standardrequiredarea:ifcareameasure
:param hasinteractionreqsfrom
:type hasinteractionreqsfrom:SET(0,None,'ifcrelinteractionrequirements', scope = schema_scope)
:param hasinteractionreqsto
:type hasinteractionreqsto:SET(0,None,'ifcrelinteractionrequirements', scope = schema_scope)
Definition at line 25027 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcspaceprogram.__init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, inherited4__objecttype, spaceprogramidentifier, maxrequiredarea, minrequiredarea, requestedlocation, standardrequiredarea)
Definition at line 25051 of file ifc2x3.py.
Member Function Documentation
hasinteractionreqsfrom()
def ifc2x3.ifcspaceprogram.hasinteractionreqsfrom ()
Definition at line 25130 of file ifc2x3.py.
hasinteractionreqsto()
def ifc2x3.ifcspaceprogram.hasinteractionreqsto ()
Definition at line 25139 of file ifc2x3.py.
maxrequiredarea()
def ifc2x3.ifcspaceprogram.maxrequiredarea ()
Definition at line 25074 of file ifc2x3.py.
References ifc2x3.ifcspaceprogram._maxrequiredarea, SCL.TypeChecker.check_type(), and ifc2x3.ifcspaceprogram.maxrequiredarea.
minrequiredarea()
def ifc2x3.ifcspaceprogram.minrequiredarea ()
Definition at line 25088 of file ifc2x3.py.
References ifc2x3.ifcspaceprogram._minrequiredarea, SCL.TypeChecker.check_type(), and ifc2x3.ifcspaceprogram.minrequiredarea.
requestedlocation()
def ifc2x3.ifcspaceprogram.requestedlocation ()
Definition at line 25102 of file ifc2x3.py.
References ifc2x3.ifcspaceprogram._requestedlocation, SCL.TypeChecker.check_type(), and ifc2x3.ifcspaceprogram.requestedlocation.
spaceprogramidentifier()
def ifc2x3.ifcspaceprogram.spaceprogramidentifier ()
Definition at line 25060 of file ifc2x3.py.
References ifc2x3.ifcspaceprogram._spaceprogramidentifier, SCL.TypeChecker.check_type(), and ifc2x3.ifcspaceprogram.spaceprogramidentifier.
standardrequiredarea()
def ifc2x3.ifcspaceprogram.standardrequiredarea ()
Definition at line 25116 of file ifc2x3.py.
References ifc2x3.ifcspaceprogram._standardrequiredarea, SCL.TypeChecker.check_type(), and ifc2x3.ifcspaceprogram.standardrequiredarea.
Member Data Documentation
maxrequiredarea
ifc2x3.ifcspaceprogram.maxrequiredarea
Definition at line 25054 of file ifc2x3.py.
Referenced by ifc2x3.ifcspaceprogram.maxrequiredarea().
minrequiredarea
ifc2x3.ifcspaceprogram.minrequiredarea
Definition at line 25055 of file ifc2x3.py.
Referenced by ifc2x3.ifcspaceprogram.minrequiredarea().
requestedlocation
ifc2x3.ifcspaceprogram.requestedlocation
Definition at line 25056 of file ifc2x3.py.
Referenced by ifc2x3.ifcspaceprogram.requestedlocation().
spaceprogramidentifier
ifc2x3.ifcspaceprogram.spaceprogramidentifier
Definition at line 25053 of file ifc2x3.py.
Referenced by ifc2x3.ifcspaceprogram.spaceprogramidentifier().
standardrequiredarea
ifc2x3.ifcspaceprogram.standardrequiredarea
Definition at line 25057 of file ifc2x3.py.
Referenced by ifc2x3.ifcspaceprogram.standardrequiredarea().
The documentation for this class was generated from the following file:
ifc2x3.py