FreeCAD: ParameterGrp Class Reference
ParameterGrp Class Reference
#include <Parameter.h>
Public Member Functions
ParameterGrp (const ParameterGrp &)=delete
ParameterGrp (ParameterGrp &&)=delete
ParameterGrp & operator= (const ParameterGrp &)=delete
ParameterGrp & operator= (ParameterGrp &&)=delete
copy and insertation
void copyTo (const Base::Reference< ParameterGrp > &)
make a deep copy to the other group
void insertTo (const Base::Reference< ParameterGrp > &)
overwrite everything similar, leave the others alone
void exportTo (const char *FileName)
export this group to a file
void importFrom (const char *FileName)
import from a file to this group
void insert (const char *FileName)
insert from a file to this group, overwrite only the similar
void revert (const char *FileName)
revert to default value by deleting any parameter that has the same value in the given file
void revert (const Base::Reference< ParameterGrp > &)
revert to default value by deleting any parameter that has the same value in the given group
methods for bool handling
bool GetBool (const char *Name, bool bPreset=false) const
read bool values or give default
void SetBool (const char *Name, bool bValue)
set a bool value
std::vector< bool > GetBools (const char *sFilter=nullptr) const
get a vector of all bool values in this group
std::vector< std::pair< std::string, bool > > GetBoolMap (const char *sFilter=nullptr) const
get a map with all bool values and the keys of this group
void RemoveBool (const char *Name)
remove a bool value from this group
methods for Int handling
long GetInt (const char *Name, long lPreset=0) const
read bool values or give default
void SetInt (const char *Name, long lValue)
set a int value
std::vector< long > GetInts (const char *sFilter=nullptr) const
get a vector of all int values in this group
std::vector< std::pair< std::string, long > > GetIntMap (const char *sFilter=nullptr) const
get a map with all int values and the keys of this group
void RemoveInt (const char *Name)
remove a int value from this group
methods for Unsigned Int handling
unsigned long GetUnsigned (const char *Name, unsigned long lPreset=0) const
read uint values or give default
void SetUnsigned (const char *Name, unsigned long lValue)
set a uint value
std::vector< unsigned long > GetUnsigneds (const char *sFilter=nullptr) const
get a vector of all uint values in this group
std::vector< std::pair< std::string, unsigned long > > GetUnsignedMap (const char *sFilter=nullptr) const
get a map with all uint values and the keys of this group
void RemoveUnsigned (const char *Name)
remove a uint value from this group
methods for Float handling
double GetFloat (const char *Name, double dPreset=0.0) const
set a float value
void SetFloat (const char *Name, double dValue)
read float values or give default
std::vector< double > GetFloats (const char *sFilter=nullptr) const
get a vector of all float values in this group
std::vector< std::pair< std::string, double > > GetFloatMap (const char *sFilter=nullptr) const
get a map with all float values and the keys of this group
void RemoveFloat (const char *Name)
remove a float value from this group
Public Member Functions inherited from Base::Handled
Handled ()
virtual ~Handled ()
void ref () const
void unref () const
int unrefNoDelete () const
int getRefCount () const
Handled & operator= (const Handled &)
Handled (const Handled &)=delete
Handled (Handled &&)=delete
Handled & operator= (Handled &&)=delete
Public Member Functions inherited from Base::Subject< const char * >
Subject ()=default
virtual ~Subject ()
void Attach (Observer< const char * > *ToObserv)
void Detach (Observer< const char * > *ToObserv)
void Notify (const char * rcReason)
Observer< const char * > * Get (const char *Name)
void ClearObserver ()
methods for group handling
using handle = Base::Reference< ParameterGrp >
type of the handle
Base::Reference< ParameterGrp > GetGroup (const char *Name)
get a handle to a sub group or create one
std::vector< Base::Reference< ParameterGrp > > GetGroups ()
get a vector of all sub groups in this group
bool IsEmpty () const
test if this group is empty
bool HasGroup (const char *Name) const
test if a special sub group is in this group
void RemoveGrp (const char *Name)
remove a sub group from this group
bool RenameGrp (const char *OldName, const char *NewName)
rename a sub group from this group
void Clear (bool notify=false)
methods for generic attribute handling
enum ParamType {
ParamType::FCInvalid = 0, ParamType::FCText = 1, ParamType::FCBool = 2, ParamType::FCInt = 3,
ParamType::FCUInt = 4, ParamType::FCFloat = 5, ParamType::FCGroup = 6
}
void SetAttribute (ParamType Type, const char *Name, const char *Value)
void RemoveAttribute (ParamType Type, const char *Name)
const char * GetAttribute (ParamType Type, const char *Name, std::string &Value, const char *Default) const
std::vector< std::pair< std::string, std::string > > GetAttributeMap (ParamType Type, const char *sFilter=nullptr) const
std::vector< std::pair< ParamType, std::string > > GetParameterNames (const char *sFilter=nullptr) const
static const char * TypeName (ParamType type)
static ParamType TypeValue (const char *)
methods for String handling
class ParameterManager
DOMElement * _pGroupNode
DOM Node of the Base node of this group.
std::string _cName
the own name
std::map< std::string, Base::Reference< ParameterGrp > > _GroupMap
map of already exported groups
ParameterGrp * _Parent = nullptr
ParameterManager * _Manager = nullptr
bool _Detached = false
Means this group xml element has not been added to its parent yet.
bool _Clearing = false
void SetASCII (const char *Name, const char *sValue)
set a string value
void SetASCII (const char *Name, const std::string &sValue)
set a string value
std::string GetASCII (const char *Name, const char *pPreset=nullptr) const
read a string values
void RemoveASCII (const char *Name)
remove a string value from this group
std::vector< std::string > GetASCIIs (const char *sFilter=nullptr) const
std::vector< std::pair< std::string, std::string > > GetASCIIMap (const char *sFilter=nullptr) const
Same as GetASCIIs() but with key,value map.
const char * GetGroupName () const
returns the name
std::string GetPath () const
return the full path of this group
void GetPath (std::string &) const
void NotifyAll ()
ParameterGrp * Parent () const
ParameterManager * Manager () const
ParameterGrp (DOMElement *GroupNode=nullptr, const char *sName=nullptr, ParameterGrp *Parent=nullptr)
constructor is protected (handle concept)
~ParameterGrp () override
destructor is protected (handle concept)
Base::Reference< ParameterGrp > _GetGroup (const char *Name)
helper function for GetGroup
bool ShouldRemove () const
void _Reset ()
void _SetAttribute (ParamType Type, const char *Name, const char *Value)
void _Notify (ParamType Type, const char *Name, const char *Value)
DOMElement * FindNextElement (DOMNode *Prev, const char *Type) const
DOMElement * FindElement (DOMElement *Start, const char *Type, const char *Name=nullptr) const
DOMElement * FindOrCreateElement (DOMElement *Start, const char *Type, const char *Name)
DOMElement * CreateElement (DOMElement *Start, const char *Type, const char *Name)
DOMNode * FindAttribute (DOMNode *Node, const char *Name) const
Additional Inherited Members
Public Types inherited from Base::Subject< const char * >
using ObserverType = Observer< const char * >
using MessageType = const char *
using SubjectType = Subject< const char * >
Detailed Description
The parameter container class This is the base class of all classes handle parameter. The class contains a map of key-value pairs in a grouping structure, not unlike the windows registry. It allows the user to set and retrieve values of the type float, long and string. Also it handles importing and exporting groups of parameters and enables streaming to a persistent medium via XML.
Its main task is making user parameter persistent, saving last used values in dialog boxes, setting and retrieving all kind of preferences and so on.
See also
ParameterManager
Definition at line 106 of file Parameter.h.
Member Typedef Documentation
handle
using ParameterGrp::handle = Base::Reference<ParameterGrp>
type of the handle
Definition at line 143 of file Parameter.h.
Member Enumeration Documentation
ParamType
enum ParameterGrp::ParamType strong
Enumerator
FCInvalid
FCText
FCBool
FCInt
FCUInt
FCFloat
FCGroup
Definition at line 155 of file Parameter.h.
Constructor & Destructor Documentation
ParameterGrp() [1/3]
ParameterGrp::ParameterGrp (const ParameterGrp &) delete
Referenced by _GetGroup(), GetGroup(), and GetGroups().
ParameterGrp() [2/3]
ParameterGrp::ParameterGrp (ParameterGrp &&) delete
ParameterGrp() [3/3]
ParameterGrp::ParameterGrp (DOMElement * GroupNode = nullptr, const char * sName = nullptr, ParameterGrp * Parent = nullptr) protected
constructor is protected (handle concept)
Default construction
Definition at line 178 of file Parameter.cpp.
References _cName, _Manager, and _Parent.
~ParameterGrp()
ParameterGrp::~ParameterGrp () override protected
destructor is protected (handle concept)
Destruction complete destruction of the object
Definition at line 196 of file Parameter.cpp.
References _Detached, _GroupMap, _pGroupNode, and TestSpreadsheet::v.
Member Function Documentation
_GetGroup()
Base::Reference< ParameterGrp > ParameterGrp::_GetGroup (const char * Name) protected
helper function for GetGroup
Definition at line 418 of file Parameter.cpp.
References _Clearing, _cName, _Detached, _GetGroup(), _GroupMap, _Notify(), _Parent, _pGroupNode, CreateElement(), FC_LOG_INSTANCE, FC_LOGLEVEL_LOG, FC_WARN, FCGroup, FindElement(), GetPath(), femsolver.elmer.sifio::isValid(), and ParameterGrp().
Referenced by _GetGroup(), CreateElement(), and GetGroup().
_Notify()
void ParameterGrp::_Notify (ParamType Type, const char * Name, const char * Value) protected
Definition at line 677 of file Parameter.cpp.
References _Manager, and ParameterManager::signalParamChanged.
Referenced by _GetGroup(), _SetAttribute(), Clear(), RemoveASCII(), RemoveBool(), RemoveFloat(), RemoveInt(), RemoveUnsigned(), RenameGrp(), and SetASCII().
_Reset()
void ParameterGrp::_Reset () protected
Definition at line 1527 of file Parameter.cpp.
References _GroupMap, _pGroupNode, and TestSpreadsheet::v.
Referenced by ParameterManager::~ParameterManager().
_SetAttribute()
void ParameterGrp::_SetAttribute (ParamType Type, const char * Name, const char * Value) protected
Definition at line 684 of file Parameter.cpp.
References _Clearing, _cName, _Notify(), _pGroupNode, StrX::c_str(), FC_LOG_INSTANCE, FC_LOGLEVEL_LOG, FC_WARN, FindOrCreateElement(), GetPath(), Base::Subject< const char * >::Notify(), TypeName(), and XStr::unicodeForm().
Referenced by SetAttribute(), SetBool(), SetFloat(), SetInt(), and SetUnsigned().
Clear()
void ParameterGrp::Clear (bool notify = false)
clears everything in this group (all types)
Parameters
notify whether to notify on deleted parameters using the Observer interface.
Definition at line 1309 of file Parameter.cpp.
References _Clearing, _GroupMap, _Notify(), _pGroupNode, StrX::c_str(), FCGroup, FCInvalid, femsolver.signal::notify(), Base::Subject< const char * >::Notify(), nativeifc.ifc_observer::params, Path.Post.scripts.grbl_post::type, TypeValue(), and TestSpreadsheet::v.
Referenced by copyTo(), Gui::Dialog::ButtonModel::goClear(), Gui::Dialog::DlgCustomizeSpNavSettings::on_ButtonDefaultSpNavMotions_clicked(), Base::ParameterGrpPy::remFloat(), Gui::ShortcutManager::resetAll(), and Gui::MacroCommand::save().
copyTo()
void ParameterGrp::copyTo (const Base::Reference< ParameterGrp > & Grp)
make a deep copy to the other group
Definition at line 210 of file Parameter.cpp.
References Clear(), and insertTo().
Referenced by Gui::Dialog::DlgRevertToBackupConfigImp::accept(), and Base::ParameterGrpPy::hasGroup().
CreateElement()
DOMElement * ParameterGrp::CreateElement (DOMElement * Start, const char * Type, const char * Name) protected
Definition at line 361 of file Parameter.cpp.
References _cName, _Detached, _GetGroup(), _Parent, StrX::c_str(), Base::Console(), Base::ConsoleSingleton::Warning(), and XERCES_CPP_NAMESPACE_QUALIFIER.
Referenced by _GetGroup(), FindOrCreateElement(), and SetASCII().
exportTo()
void ParameterGrp::exportTo (const char * FileName)
export this group to a file
Definition at line 272 of file Parameter.cpp.
References ParameterManager::Create(), and insertTo().
Referenced by Gui::Dialog::ParameterGroup::onExportToFile().
FindAttribute()
DOMNode * ParameterGrp::FindAttribute (DOMNode * Node, const char * Name) const protected
Find an attribute specified by Name
Definition at line 1455 of file Parameter.cpp.
Referenced by FindElement().
FindElement()
DOMElement * ParameterGrp::FindElement (DOMElement * Start, const char * Type, const char * Name = nullptr) const protected
Find an element specified by Type and Name Search in the parent element Start for the first occurrence of an element of Type and with the attribute Name=Name. On success it returns the pointer to that element, otherwise NULL If the names not given it returns the first occurrence of Type.
Definition at line 1386 of file Parameter.cpp.
References StrX::c_str(), Base::Console(), FindAttribute(), and Base::ConsoleSingleton::Warning().
Referenced by _GetGroup(), FindOrCreateElement(), GetASCII(), GetASCIIMap(), GetASCIIs(), GetAttribute(), GetAttributeMap(), GetBool(), GetBoolMap(), GetBools(), GetFloat(), GetFloatMap(), GetFloats(), GetGroups(), GetInt(), GetIntMap(), GetInts(), GetUnsigned(), GetUnsignedMap(), GetUnsigneds(), HasGroup(), ParameterManager::LoadDocument(), RemoveASCII(), RemoveBool(), RemoveFloat(), RemoveInt(), RemoveUnsigned(), RenameGrp(), and SetASCII().
FindNextElement()
DOMElement * ParameterGrp::FindNextElement (DOMNode * Prev, const char * Type) const protected
Definition at line 1422 of file Parameter.cpp.
References StrX::c_str().
Referenced by GetASCIIMap(), GetASCIIs(), GetAttributeMap(), GetBoolMap(), GetBools(), GetFloatMap(), GetFloats(), GetGroups(), GetIntMap(), GetInts(), GetUnsignedMap(), and GetUnsigneds().
FindOrCreateElement()
DOMElement * ParameterGrp::FindOrCreateElement (DOMElement * Start, const char * Type, const char * Name) protected
Find an element specified by Type and Name or create it if not found Search in the parent element Start for the first occurrence of an element of Type and with the attribute Name=Name. On success it returns the pointer to that element, otherwise it creates the element and returns the pointer.
Definition at line 1441 of file Parameter.cpp.
References CreateElement(), and FindElement().
Referenced by _SetAttribute().
GetASCII()
std::string ParameterGrp::GetASCII (const char * Name, const char * pPreset = nullptr) const
read a string values
Definition at line 1055 of file Parameter.cpp.
References _pGroupNode, StrXUTF8::c_str(), and FindElement().
Referenced by Gui::StdCmdDownloadOnlineHelp::activated(), StdCmdImport::activated(), StdCmdExport::activated(), StdCmdOnlineHelpWebsite::activated(), StdCmdFreeCADDonation::activated(), StdCmdFreeCADWebsite::activated(), StdCmdFreeCADUserHub::activated(), StdCmdFreeCADPowerUserHub::activated(), StdCmdFreeCADForum::activated(), StdCmdFreeCADFAQ::activated(), StdCmdReportBug::activated(), Gui::MacroCommand::activated(), StdCmdViewHome::activated(), StdViewScreenShot::activated(), Gui::Dialog::DlgSettingsNavigation::addOrientations(), Gui::Application::Application(), Fem::Tools::checkIfBinaryExists(), Cloud::Module::cloudSave(), Gui::Dialog::AboutDialog::copyToClipboard(), Gui::Dialog::DlgCustomActionsImp::DlgCustomActionsImp(), Gui::Dialog::DlgMacroExecuteImp::DlgMacroExecuteImp(), App::Document::Document(), Gui::MainWindow::event(), Gui::GraphvizView::exportGraph(), GetAttribute(), Gui::Dialog::DlgSettingsWorkbenchesImp::getDisabledWorkbenches(), Gui::Dialog::DlgSettingsWorkbenchesImp::getEnabledWorkbenches(), Gui::InputField::getHistory(), Gui::View3DInventorViewer::getInternalTextureFormat(), TechDrawGui::QGVPage::getNavStyleParameter(), Gui::InputField::getSavedValues(), Gui::ShortcutManager::getShortcut(), Part::STEP::ImportExportSettings::getWriteSurfaceCurveMode(), TechDrawGui::DrawGuiUtil::iconForLine(), Part::STEP::ImportExportSettings::ImportExportSettings(), Part::OCAF::ImportExportSettings::initialize(), TechDrawGui::DrawGuiUtil::loadArrowBox(), TechDrawGui::DrawGuiUtil::loadBalloonShapeBox(), TechDrawGui::DrawGuiUtil::loadMattingStyleBox(), Start::RecentFilesModel::loadRecentFiles(), Gui::Dialog::DlgSettingsNavigation::loadSettings(), Gui::Dialog::DlgSettingsEditor::loadSettings(), Gui::Dialog::DlgSettingsGeneral::loadSettings(), SpreadsheetGui::DlgSettingsImp::loadSettings(), MeshGui::DlgSettingsImportExport::loadSettings(), Gui::Dialog::DlgSettingsMacroImp::loadSettings(), Gui::Dialog::DlgSettingsGeneral::loadThemes(), Gui::MainWindow::loadWindowSettings(), Gui::View3DSettings::OnChange(), Gui::TextEditor::OnChange(), TechDrawGui::QGVPage::Private::OnChange(), Gui::DockWnd::ReportOutput::OnChange(), Gui::Dialog::DlgParameterImp::onChangeParameterSet(), Gui::GestureNavigationStyle::onRollGesture(), FemGui::DlgSettingsFemGmshImp::populateLogVerbosity(), StartGui::StartView::postStart(), TechDraw::DrawGeomHatch::prefGeomHatchName(), Gui::InputField::pushToHistory(), Gui::InputField::pushToSavedValues(), PyMOD_INIT_FUNC(), Gui::OverlayTabWidget::refreshIcons(), Gui::Dialog::ParameterText::replace(), Gui::OverlayTabWidget::restore(), Gui::FileDialog::restoreLocation(), Gui::PrefFontBox::restorePreferences(), revert(), App::Document::save(), Gui::View3DInventorViewer::savePicture(), Gui::Dialog::DlgSettingsGeneral::saveSettings(), Gui::Dialog::DlgSettingsGeneral::saveThemes(), App::Document::saveToFile(), Part::IGES::ImportExportSettings::setSkipBlankEntities(), SpreadsheetGui::SheetModel::SheetModel(), Gui::Dialog::DlgParameterImp::showEvent(), Gui::OverlayTabWidget::syncAutoMode(), SketcherGui::ViewProviderSketch::unsetEdit(), SketcherGui::TaskSketcherSolverAdvanced::updateDefaultMethodParameters(), SketcherGui::TaskSketcherSolverAdvanced::updateRedundantMethodParameters(), Gui::View3DInventorPy::viewDefaultOrientation(), and Import::WriterStep::write().
GetASCIIMap()
std::vector< std::pair< std::string, std::string > > ParameterGrp::GetASCIIMap (const char * sFilter = nullptr) const
Same as GetASCIIs() but with key,value map.
Definition at line 1108 of file Parameter.cpp.
References _pGroupNode, StrXUTF8::c_str(), FindElement(), and FindNextElement().
Referenced by copyTemplateParameters(), insertTo(), NotifyAll(), Gui::Dialog::ParameterValue::onCreateTextItem(), Gui::Dialog::DlgParameterImp::onGroupSelected(), revert(), and Gui::StatefulLabel::setState().
GetASCIIs()
std::vector< std::string > ParameterGrp::GetASCIIs (const char * sFilter = nullptr) const
Return all string elements in this group as a vector of strings Its also possible to set a filter criteria.
Parameters
sFilter only strings which name includes sFilter are put in the vector
Returns
std::vector of std::strings
Definition at line 1078 of file Parameter.cpp.
References _pGroupNode, StrXUTF8::c_str(), FindElement(), and FindNextElement().
Referenced by Gui::PrefQuantitySpinBoxPrivate::clearHistory(), and Gui::PrefQuantitySpinBoxPrivate::restoreHistory().
GetAttribute()
const char * ParameterGrp::GetAttribute (ParamType Type, const char * Name, std::string & Value, const char * Default) const
Definition at line 610 of file Parameter.cpp.
References _pGroupNode, StrX::c_str(), FCGroup, FCText, FindElement(), GetASCII(), and TypeName().
GetAttributeMap()
std::vector< std::pair< std::string, std::string > > ParameterGrp::GetAttributeMap (ParamType Type, const char * sFilter = nullptr) const
Definition at line 639 of file Parameter.cpp.
References _pGroupNode, StrX::c_str(), FCGroup, FindElement(), FindNextElement(), and TypeName().
GetBool()
bool ParameterGrp::GetBool (const char * Name, bool bPreset = false) const
read bool values or give default
Definition at line 720 of file Parameter.cpp.
References _pGroupNode, and FindElement().
Referenced by Gui::StdCmdDownloadOnlineHelp::activated(), StdCmdDlgPreferences::activated(), StdCmdNew::activated(), CmdSketcherConstrainLock::activated(), CmdSketcherConstrainBlock::activated(), CmdSketcherConstrainDistance::activated(), CmdSketcherConstrainDistanceX::activated(), CmdSketcherConstrainDistanceY::activated(), CmdSketcherConstrainParallel::activated(), CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainRadius::activated(), CmdSketcherConstrainDiameter::activated(), CmdSketcherConstrainRadiam::activated(), CmdSketcherConstrainAngle::activated(), CmdSketcherConstrainEqual::activated(), CmdSketcherConstrainSymmetric::activated(), Gui::MainWindow::activateWorkbench(), App::DynamicProperty::addDynamicProperty(), TechDraw::DrawPage::AllowPageOverride(), Gui::RecentMacrosAction::appendFile(), Gui::Application::Application(), PartGui::DlgScale::apply(), PartGui::DlgExtrusion::apply(), CmdSketcherConstrainLock::applyConstraint(), Gui::SoFCUnifiedSelection::applySettings(), Gui::SoFCSelection::applySettings(), PartDesign::Body::Body(), Gui::Application::checkForDeprecatedSettings(), Fem::Tools::checkIfBinaryExists(), Cloud::Module::cloudSave(), CmdSketcherConstrainCoincident::CmdSketcherConstrainCoincident(), CmdSketcherConstrainCoincidentUnified::CmdSketcherConstrainCoincidentUnified(), Gui::MainWindow::confirmSave(), Gui::TreeWidget::contextMenuEvent(), Gui::PythonConsole::contextMenuEvent(), DrawSketchHandlerDimension::createRadiusDiameterConstrain(), TDHandlerDimension::createRadiusDiameterDimension(), Gui::ViewProviderBuilder::createSelection(), Gui::View3DInventor::customEvent(), Gui::DockWnd::ReportOutput::customEvent(), ConstraintItem::data(), TechDraw::DrawViewDetail::debugDetail(), TechDraw::DrawViewSection::debugSection(), Materials::MaterialManager::defaultAppearance(), MeshGui::DlgEvaluateMeshImp::DlgEvaluateMeshImp(), Gui::Dialog::DlgExpressionInput::DlgExpressionInput(), Gui::Document::Document(), DrawingGui::DrawingView::DrawingView(), TechDraw::DrawProjGroup::DrawProjGroup(), Gui::ElementColors::ElementColors(), AssemblyGui::ViewProviderAssembly::endMove(), Assembly::AssemblyObject::execute(), Gui::GraphvizView::exportGraph(), App::Document::exportGraphviz(), Gui::Application::exportTo(), MeshGui::ViewProviderMesh::faceInfoCallback(), TDHandlerDimension::finalizeCommand(), DrawSketchHandlerDimension::finalizeCommand(), finishDatumConstraint(), Gui::GestureNavigationStyle::GestureNavigationStyle(), Gui::Gui::GestureNavigationStyle ::GestureState::GestureState(), Path::Toolpath::getCycleTime(), App::Material::getDefaultAppearance(), TechDraw::DrawLeaderLine::getDefAuto(), Part::OCAF::ImportExportSettings::getExportHiddenObject(), Part::OCAF::ImportExportSettings::getExportKeepPlacement(), Part::OCAF::ImportExportSettings::getExportLegacy(), Part::OCAF::ImportExportSettings::getImportHiddenObject(), TechDraw::DrawViewSection::getParameters(), FemGui::FemSettings::getPostAutoRecompute(), Part::OCAF::ImportExportSettings::getReadShapeCompoundMode(), Part::getRefineModelParameter(), Part::Feature::getSubObject(), Part::OCAF::ImportExportSettings::getUseLinkGroup(), TechDraw::DrawPage::GlobalUpdateDrawings(), Gui::GraphvizView::GraphvizView(), TechDraw::DrawViewPart::handleFaces(), SketcherGui::hideUnits(), horVerActivated(), Part::OCAF::ImportExportSettings::ImportExportSettings(), Gui::Application::importFrom(), TechDrawGui::QGVPage::Private::init(), Part::OCAF::ImportExportSettings::initialize(), TechDrawGui::QGVNavStyle::initialize(), Gui::NavigationStyle::initialize(), Gui::ExpressionParameter::isCaseSensitive(), TechDraw::DrawUtil::isCrazy(), Gui::ExpressionParameter::isExactMatch(), PartDesignGui::TaskFeaturePick::isSingleSelectionEnabled(), AssemblyGui::ViewProviderAssembly::keyPressed(), Gui::PythonEditor::keyPressEvent(), Gui::PythonTextEditor::keyPressEvent(), StartGui::StartLauncher::Launch(), PartGui::ViewProviderPartExt::loadParameter(), Gui::Dialog::DlgSettingsNavigation::loadSettings(), Gui::Dialog::DlgSettingsGeneral::loadSettings(), TechDrawGui::DlgPrefsTechDrawDimensionsImp::loadSettings(), SketcherGui::SketcherSettings::loadSettings(), MeshGui::DlgSettingsMeshView::loadSettings(), Gui::Dialog::DlgSettingsNotificationArea::loadSettings(), Gui::DockWindowManager::loadState(), Gui::MainWindow::loadWindowSettings(), Gui::MainWindow::MainWindow(), Assembly::AssemblyObject::makeMbdAssembly(), TechDraw::DrawViewPart::newFaceFinder(), Gui::Notify(), CmdSketcherConstrainCoincidentUnified::onActivated(), Gui::View3DSettings::OnChange(), Gui::TextEditor::OnChange(), Gui::PythonConsole::OnChange(), TechDrawGui::QGVPage::Private::OnChange(), Gui::DockWnd::ReportOutput::OnChange(), SketcherGui::TaskSketcherConstraints::OnChange(), Gui::MacroManager::OnChange(), CmdSketcherSnap::OnChange(), SketcherGui::TaskSketcherConstraints::onSettingsAutoRemoveRedundantChanged(), SketcherGui::TaskSketcherConstraints::onSettingsExtendedInformationChanged(), SketcherGui::TaskSketcherConstraints::onSettingsHideInternalAligmentChanged(), SketcherGui::TaskSketcherConstraints::onSettingsRestrictVisibilityChanged(), Gui::Application::open(), App::Application::openDocuments(), Gui::NotificationArea::ParameterObserver::ParameterObserver(), TechDrawGui::QGIViewPart::prefFaceEdges(), TechDrawGui::QGIViewPart::prefPrintCenters(), Import::ReaderIges::read(), App::Document::recompute(), DrawSketchHandlerBSplineInsertKnot::releaseButton(), Gui::Dialog::ParameterBool::replace(), Gui::Dialog::DlgSettingsWorkbenchesImp::resetSettingsToDefaults(), Gui::OverlayTabWidget::restore(), TechDraw::CosmeticVertex::restoreCosmetic(), Part::PropertyPartShape::RestoreDocFile(), Gui::PrefCheckBox::restorePreferences(), Gui::PrefRadioButton::restorePreferences(), Gui::ToolBarManager::restoreState(), Gui::MainWindowP::restoreWindowState(), revert(), Gui::GraphvizWorker::run(), Gui::MacroManager::run(), Gui::Document::Save(), App::Document::save(), Part::PropertyPartShape::SaveDocFile(), Gui::AutoSaver::saveDocument(), Gui::Dialog::DlgSettingsGeneral::saveSettings(), Gui::Dialog::DlgSettingsGeneral::saveThemes(), App::Document::saveToFile(), SketcherGui::ViewProviderSketch::setEditViewer(), Gui::DocumentObjectItem::setHighlight(), Import::ImpExpDxfRead::setOptions(), Import::ImpExpDxfWrite::setOptions(), Gui::ToolBarManager::setState(), Gui::DockWindowManager::setup(), Gui::ToolBarManager::setup(), Gui::StartupProcess::setupApplication(), Sketcher::SketchObject::setupObject(), FemGui::ViewProviderFemPostObject::setupPipeline(), TechDrawGui::Workbench::setupToolBars(), App::PropertyString::setValue(), Gui::MainWindow::setWindowTitle(), SketcherGui::showCursorCoords(), PartDesignGui::TaskHelixParameters::showPreview(), ShowRestoreInformationLayer(), Gui::View3DInventorViewer::showRotationCenter(), TechDraw::DrawViewSection::showSectionEdges(), TechDraw::DrawViewDimension::showUnits(), SketcherGui::SketcherAddWorkbenchConstraints< Gui::MenuItem >(), SketcherGui::SketcherAddWorkbenchConstraints< Gui::ToolBarItem >(), Gui::Application::slotActiveDocument(), Gui::MainWindow::startSplasher(), StdCmdRefresh::StdCmdRefresh(), SketcherGui::TaskDlgEditSketch::TaskDlgEditSketch(), SketcherGui::TaskSketcherElements::TaskSketcherElements(), SketcherGui::TaskSketcherMessages::TaskSketcherMessages(), MeshPartGui::Tessellation::Tessellation(), Part::throwIfInvalidIfCheckModel(), SketcherGui::tryAutoRecompute(), Gui::RecentFilesAction::Private::trySaveUserParameter(), SketcherGui::ViewProviderSketch::unsetEdit(), SnapSpaceAction::updateWidget(), SketcherGui::useSystemDecimals(), and PartGui::ViewProviderPartExt::ViewProviderPartExt().
GetBoolMap()
std::vector< std::pair< std::string, bool > > ParameterGrp::GetBoolMap (const char * sFilter = nullptr) const
get a map with all bool values and the keys of this group
Definition at line 769 of file Parameter.cpp.
References _pGroupNode, StrX::c_str(), FindElement(), and FindNextElement().
Referenced by copyTemplateParameters(), insertTo(), NotifyAll(), Gui::Dialog::ParameterValue::onCreateBoolItem(), Gui::Dialog::DlgParameterImp::onGroupSelected(), Gui::ToolBarAreaWidget::restoreState(), and revert().
GetBools()
std::vector< bool > ParameterGrp::GetBools (const char * sFilter = nullptr) const
get a vector of all bool values in this group
Definition at line 742 of file Parameter.cpp.
References _pGroupNode, StrX::c_str(), FindElement(), and FindNextElement().
GetFloat()
double ParameterGrp::GetFloat (const char * Name, double dPreset = 0.0) const
set a float value
Definition at line 943 of file Parameter.cpp.
References _pGroupNode, and FindElement().
Referenced by Gui::Dialog::DlgSettingsNavigation::addOrientations(), Gui::ViewProviderLine::attach(), Gui::ViewProviderPlane::attach(), Gui::ViewProviderDatum::attach(), Gui::ViewProviderPoint::attach(), Gui::ViewProviderCoordinateSystem::defaultSize(), PartGui::DlgSettings3DViewPart::DlgSettings3DViewPart(), TechDrawGui::QGIViewPart::drawAllVertexes(), TechDraw::DrawPage::DrawPage(), finishDatumConstraint(), TechDrawGui::Rez::getParameter(), TechDrawGui::ViewProviderViewSection::getParameters(), TechDrawGui::QGVPage::Private::init(), TechDrawGui::QGVNavStyle::initialize(), Gui::NavigationStyle::initialize(), PartGui::ViewProviderPartExt::loadParameter(), InspectionGui::VisualInspection::loadSettings(), MeshGui::DlgSettingsImportExport::loadSettings(), Gui::View3DSettings::OnChange(), TechDrawGui::QGVPage::Private::OnChange(), TechDraw::DrawView::prefScale(), PyMOD_INIT_FUNC(), Gui::Dialog::ParameterFloat::replace(), Gui::ViewProviderDatum::resetTemporarySize(), Gui::PrefDoubleSpinBox::restorePreferences(), Gui::PrefUnitSpinBox::restorePreferences(), revert(), Import::ImpExpDxfRead::setOptions(), Import::ImpExpDxfWrite::setOptions(), Sketcher::SketchObject::setupObject(), Gui::View3DInventorViewer::showRotationCenter(), MeshPartGui::Tessellation::Tessellation(), SnapSpaceAction::updateWidget(), Gui::View3DInventorPy::viewDefaultOrientation(), PartGui::ViewProviderPartExt::ViewProviderPartExt(), and Path::PathSegmentWalker::walk().
GetFloatMap()
std::vector< std::pair< std::string, double > > ParameterGrp::GetFloatMap (const char * sFilter = nullptr) const
get a map with all float values and the keys of this group
Definition at line 989 of file Parameter.cpp.
References _pGroupNode, StrX::c_str(), FindElement(), and FindNextElement().
Referenced by copyTemplateParameters(), insertTo(), NotifyAll(), Gui::Dialog::ParameterValue::onCreateFloatItem(), Gui::Dialog::DlgParameterImp::onGroupSelected(), and revert().
GetFloats()
std::vector< double > ParameterGrp::GetFloats (const char * sFilter = nullptr) const
get a vector of all float values in this group
Definition at line 966 of file Parameter.cpp.
References _pGroupNode, StrX::c_str(), FindElement(), and FindNextElement().
GetGroup()
Base::Reference< ParameterGrp > ParameterGrp::GetGroup (const char * Name)
get a handle to a sub group or create one
Definition at line 389 of file Parameter.cpp.
References _cName, _GetGroup(), ParameterGrp(), split(), femtools.tokrules::tokens, and Materials::trim().
Referenced by Gui::Dialog::DlgRevertToBackupConfigImp::accept(), Gui::StdCmdDownloadOnlineHelp::activated(), StdCmdImport::activated(), StdCmdExport::activated(), StdViewScreenShot::activated(), Gui::ParamHandlers::addDelayedHandler(), Gui::ParamHandlers::addHandler(), Gui::Dialog::DlgSettingsNavigation::addOrientations(), Gui::Application::Application(), PartGui::DlgScale::apply(), PartGui::DlgExtrusion::apply(), Gui::SoFCUnifiedSelection::applySettings(), Gui::SoFCSelection::applySettings(), Gui::ViewProviderAnnotation::attach(), MeshGui::ViewProviderMeshFaceSet::attach(), MeshGui::ViewProviderIndexedFaceSet::attach(), MeshGui::ViewProviderMeshObject::attach(), Gui::Dialog::DlgSettingsGeneral::attachObserver(), PartDesign::Body::Body(), Gui::Dialog::DlgParameterImp::closeEvent(), Gui::MainWindow::confirmSave(), copyTemplateParameters(), Gui::ViewProviderBuilder::createSelection(), Gui::DialogOptions::dontUseNativeColorDialog(), Gui::DialogOptions::dontUseNativeFileDialog(), Gui::MainWindow::event(), MeshGui::ViewProviderMesh::fillHole(), Gui::Dialog::ApplicationCacheSettings::getCacheSizeLimit(), Gui::Dialog::ApplicationCacheSettings::getCheckPeriod(), Gui::WindowParameter::getDefaultParameter(), TechDrawGui::QGIView::getParmGroupCol(), Part::getRefineModelParameter(), PartGui::TaskCheckGeometryResults::goCheck(), SketcherGui::hideUnits(), Part::OCAF::ImportExportSettings::initialize(), Gui::Dialog::ButtonModel::insertButtonRows(), insertTo(), PartDesignGui::TaskFeaturePick::isSingleSelectionEnabled(), Gui::MacroCommand::load(), Gui::Dialog::DlgSettingsEditor::loadSettings(), Gui::Dialog::DlgSettingsGeneral::loadSettings(), MeshGui::DlgSettingsImportExport::loadSettings(), MeshGui::DlgSettingsMeshView::loadSettings(), Gui::Dialog::DlgSettingsMacroImp::loadSettings(), Gui::DockWindowManager::loadState(), Gui::DAG::Model::Model(), Gui::Notify(), Gui::Dialog::DlgParameterImp::onChangeParameterSet(), Gui::Dialog::ParameterGroup::onCreateSubgroup(), OverlayInfo::OverlayInfo(), PyMOD_INIT_FUNC(), Gui::PythonConsole::PythonConsole(), Import::ReaderIges::read(), Gui::DockWnd::ReportOutput::ReportOutput(), Gui::DockWnd::ReportView::ReportView(), Gui::Dialog::DlgSettingsNavigation::resetSettingsToDefaults(), Gui::Dialog::DlgSettingsEditor::resetSettingsToDefaults(), Gui::Dialog::DlgSettingsGeneral::resetSettingsToDefaults(), Gui::Dialog::DlgSettingsCacheDirectory::resetSettingsToDefaults(), Gui::Dialog::DlgSettingsMacroImp::resetSettingsToDefaults(), Gui::FileDialog::restoreLocation(), Gui::PrefQuantitySpinBox::restorePreferences(), Gui::MDIView::restorePrinterSettings(), revert(), Gui::MacroManager::run(), Gui::MacroCommand::save(), Gui::FileDialog::saveLocation(), Gui::PrefQuantitySpinBox::savePreferences(), Gui::MDIView::savePrinterSettings(), Gui::Dialog::DlgSettingsNavigation::saveSettings(), Gui::Dialog::DlgSettingsEditor::saveSettings(), Gui::Dialog::DlgSettingsGeneral::saveSettings(), MeshGui::DlgSettingsImportExport::saveSettings(), Gui::Dialog::DlgSettingsMacroImp::saveSettings(), Gui::Dialog::ApplicationCacheSettings::setCacheSizeLimit(), Gui::Dialog::ApplicationCacheSettings::setCheckPeriod(), Gui::WindowParameter::setGroupName(), Gui::ToolBarManager::setup(), Gui::StdWorkbench::setupDockWindows(), App::PropertyString::setValue(), Gui::ShortcutManager::ShortcutManager(), SketcherGui::showCursorCoords(), Gui::Dialog::DlgParameterImp::showEvent(), Gui::MainWindow::startSplasher(), PartGui::TaskCheckGeometryDialog::TaskCheckGeometryDialog(), Part::throwIfInvalidIfCheckModel(), SketcherGui::useSystemDecimals(), Gui::WindowParameter::WindowParameter(), and Import::WriterStep::write().
GetGroupName()
const char* ParameterGrp::GetGroupName () const inline
returns the name
Definition at line 267 of file Parameter.h.
References _cName.
Referenced by Gui::Dialog::ParameterGroupItem::fillUp().
GetGroups()
std::vector< Base::Reference< ParameterGrp > > ParameterGrp::GetGroups ()
get a vector of all sub groups in this group
Definition at line 478 of file Parameter.cpp.
References _GroupMap, _pGroupNode, StrX::c_str(), FindElement(), FindNextElement(), femsolver.elmer.sifio::isValid(), and ParameterGrp().
Referenced by copyTemplateParameters(), Gui::Dialog::ButtonModel::data(), Gui::Dialog::ParameterGroupItem::fillUp(), Gui::Dialog::ButtonModel::goMacroRemoved(), Gui::Dialog::ButtonModel::insertButtonRows(), insertTo(), Gui::PreferencePackManager::isVisible(), Gui::MacroCommand::load(), Gui::Dialog::DlgParameterImp::onChangeParameterSet(), Gui::Dialog::ParameterGroup::onImportFromFile(), revert(), Gui::Dialog::ButtonModel::rowCount(), Gui::Dialog::ButtonModel::setCommand(), and Gui::PreferencePackManager::toggleVisibility().
GetInt()
long ParameterGrp::GetInt (const char * Name, long lPreset = 0) const
read bool values or give default
Definition at line 796 of file Parameter.cpp.
References _pGroupNode, and FindElement().
Referenced by StdViewScreenShot::activated(), Gui::WorkbenchGroup::addTo(), MeshGui::ViewProviderMeshFaceSet::attach(), PartDesignGui::ViewProviderDatumPoint::attach(), MeshGui::ViewProviderIndexedFaceSet::attach(), MeshGui::ViewProviderMeshObject::attach(), Gui::Gui::GestureNavigationStyle ::AwaitingMoveState::AwaitingMoveState(), CmdRenderingOrder::CmdRenderingOrder(), StartGui::StartView::configureRecentFilesListWidget(), SketcherGui::ConstraintFilterList::ConstraintFilterList(), PartGui::ViewProvider2DObjectGrid::createGrid(), Materials::MaterialManager::defaultAppearance(), FemGui::DlgSettingsFemGeneralImp::DlgSettingsFemGeneralImp(), Gui::Document::Document(), App::Document::Document(), SketcherGui::ElementFilterList::ElementFilterList(), MeshGui::ViewProviderMesh::fillHole(), FileCardDelegate::generateThumbnail(), TechDrawGui::PreferencesGui::get3dMarkerSize(), TechDrawGui::QGICenterLine::getCenterStyle(), Gui::Dialog::ApplicationCacheSettings::getCheckPeriod(), App::Material::getDefaultAppearance(), TechDraw::LineFormat::getDefEdgeStyle(), getPreferencesViewParameter(), getSketcherGeneralParameter(), Part::OCAF::ImportExportSettings::getUseBaseName(), Part::OCAF::ImportExportSettings::initialize(), Gui::NavigationStyle::initialize(), Part::STEP::ImportExportSettings::isVisibleExportDialog(), Gui::WorkbenchTabWidget::itemStyle(), Gui::PythonEditor::keyPressEvent(), Gui::PythonTextEditor::keyPressEvent(), Start::RecentFilesModel::loadRecentFiles(), Gui::Dialog::DlgSettingsNavigation::loadSettings(), Gui::Dialog::DlgSettingsEditor::loadSettings(), Gui::Dialog::DlgSettingsGeneral::loadSettings(), FemGui::DlgSettingsFemExportAbaqusImp::loadSettings(), FemGui::DlgSettingsFemInOutVtkImp::loadSettings(), FemGui::DlgSettingsFemGmshImp::loadSettings(), SketcherGui::SketcherSettings::loadSettings(), FemGui::DlgSettingsFemZ88Imp::loadSettings(), FemGui::DlgSettingsFemCcxImp::loadSettings(), SketcherGui::SketcherSettingsGrid::loadSettings(), SketcherGui::SketcherSettingsAppearance::loadSettings(), Gui::View3DSettings::OnChange(), Gui::ShortcutManager::OnChange(), Gui::TextEditor::OnChange(), Gui::DockWnd::ReportOutput::OnChange(), CmdRenderingOrder::OnChange(), Gui::OverlayManager::Private::onTimer(), FileCardDelegate::paint(), Gui::NotificationArea::ParameterObserver::ParameterObserver(), TechDraw::DrawViewSection::prefCutSurface(), TechDraw::DrawView::prefScaleType(), Gui::PropertyEditor::PropertyEditor::PropertyEditor(), Gui::PropertyView::PropertyView(), Gui::Multisample::readMSAAFromSettings(), Gui::WorkbenchComboBox::refreshList(), Gui::Dialog::ParameterInt::replace(), Gui::DockWnd::ReportOutput::ReportOutput(), Gui::DockWnd::ReportView::ReportView(), ZoomableView::resetZoom(), Gui::OverlayTabWidget::restore(), Gui::PrefSpinBox::restorePreferences(), Gui::PrefComboBox::restorePreferences(), Gui::PrefSlider::restorePreferences(), Gui::ToolBarManager::restoreState(), revert(), Gui::Document::Save(), App::Document::saveToFile(), Gui::SelectionSingleton::selStackPush(), Import::ImpExpDxfWrite::setOptions(), Gui::ShortcutManager::ShortcutManager(), FileCardDelegate::sizeHint(), Gui::Application::slotActiveDocument(), Gui::View3DInventorViewer::startAnimation(), Gui::View3DSettings::stopAnimatingIfDeactivated(), PartDesignGui::ViewProviderDatumCoordinateSystem::ViewProviderDatumCoordinateSystem(), PathGui::ViewProviderPath::ViewProviderPath(), and SandboxGui::Workbench::Workbench().
GetIntMap()
std::vector< std::pair< std::string, long > > ParameterGrp::GetIntMap (const char * sFilter = nullptr) const
get a map with all int values and the keys of this group
Definition at line 841 of file Parameter.cpp.
References _pGroupNode, StrX::c_str(), FindElement(), and FindNextElement().
Referenced by copyTemplateParameters(), insertTo(), NotifyAll(), Gui::Dialog::ParameterValue::onCreateIntItem(), Gui::Dialog::DlgParameterImp::onGroupSelected(), revert(), Gui::ToolBarAreaWidget::saveState(), Base::ParameterGrpPy::setInt(), and Gui::ShortcutManager::ShortcutManager().
GetInts()
std::vector< long > ParameterGrp::GetInts (const char * sFilter = nullptr) const
get a vector of all int values in this group
Definition at line 818 of file Parameter.cpp.
References _pGroupNode, StrX::c_str(), FindElement(), and FindNextElement().
GetParameterNames()
std::vector< std::pair< ParameterGrp::ParamType, std::string > > ParameterGrp::GetParameterNames (const char * sFilter = nullptr) const
Return the type and name of all parameters with optional filter
Parameters
sFilter only strings which name includes sFilter are put in the vector
Returns
std::vector of pair(type, name)
Definition at line 1465 of file Parameter.cpp.
References _pGroupNode, StrX::c_str(), FCGroup, FCInvalid, Path.Post.scripts.grbl_post::type, and TypeValue().
Referenced by Gui::Dialog::PreferencePage::resetSettingsToDefaults().
GetPath() [1/2]
std::string ParameterGrp::GetPath () const
return the full path of this group
Definition at line 465 of file Parameter.cpp.
References _cName, _Manager, _Parent, GetPath(), and src.Mod.Test.testPathArray::path.
Referenced by _GetGroup(), _SetAttribute(), GetPath(), and SetASCII().
GetPath() [2/2]
void ParameterGrp::GetPath (std::string &) const
GetUnsigned()
unsigned long ParameterGrp::GetUnsigned (const char * Name, unsigned long lPreset = 0) const
read uint values or give default
Definition at line 865 of file Parameter.cpp.
References _pGroupNode, and FindElement().
Referenced by Gui::SoFCUnifiedSelection::applySettings(), Gui::SoFCSelection::applySettings(), Gui::ViewProviderAnnotation::attach(), Gui::PythonConsole::changeEvent(), Gui::DockWnd::ReportOutput::changeEvent(), Gui::ViewProviderBuilder::createSelection(), Materials::MaterialManager::defaultAppearance(), PathGui::ViewProviderPath::getBoundColor(), Gui::ViewProviderGeometryObject::getBoundColor(), Gui::Dialog::ApplicationCacheSettings::getCacheSizeLimit(), Gui::ToolHandler::getCrosshairColor(), App::Material::getDefaultAppearance(), getPreferencesViewParameter(), getSketcherGeneralParameter(), Gui::Dialog::DlgSettingsEditor::loadSettings(), Gui::View3DSettings::OnChange(), Gui::TextEditor::OnChange(), Gui::DockWnd::ReportOutput::OnChange(), Gui::GraphicsView3D::OnChange(), Gui::StatusBarObserver::OnChange(), PathGui::ViewProviderPath::onChanged(), PartDesignGui::ViewProviderSubShapeBinder::onChanged(), Gui::Dialog::ParameterUInt::replace(), Gui::Application::replaceVariablesInQss(), Gui::PrefColorButton::restorePreferences(), revert(), Gui::DocumentObjectItem::setHighlight(), Gui::View3DInventorViewer::showRotationCenter(), Gui::DocumentItem::slotInEdit(), StartGui::ThemeSelectorWidget::themeChanged(), Gui::ViewProviderAnnotation::ViewProviderAnnotation(), PartDesignGui::ViewProviderDatum::ViewProviderDatum(), PathGui::ViewProviderPath::ViewProviderPath(), and PartDesignGui::ViewProviderShapeBinder::ViewProviderShapeBinder().
GetUnsignedMap()
std::vector< std::pair< std::string, unsigned long > > ParameterGrp::GetUnsignedMap (const char * sFilter = nullptr) const
get a map with all uint values and the keys of this group
Definition at line 916 of file Parameter.cpp.
References _pGroupNode, StrX::c_str(), FindElement(), and FindNextElement().
Referenced by copyTemplateParameters(), insertTo(), NotifyAll(), Gui::Dialog::ParameterValue::onCreateUIntItem(), Gui::Dialog::DlgParameterImp::onGroupSelected(), revert(), Gui::StatefulLabel::setState(), and Base::ParameterGrpPy::setUnsigned().
GetUnsigneds()
std::vector< unsigned long > ParameterGrp::GetUnsigneds (const char * sFilter = nullptr) const
get a vector of all uint values in this group
Definition at line 889 of file Parameter.cpp.
References _pGroupNode, StrX::c_str(), FindElement(), and FindNextElement().
HasGroup()
bool ParameterGrp::HasGroup (const char * Name) const
test if a special sub group is in this group
Definition at line 514 of file Parameter.cpp.
References _GroupMap, _pGroupNode, and FindElement().
Referenced by Gui::MacroCommand::load(), Gui::Dialog::ParameterGroup::onCreateSubgroup(), and revert().
importFrom()
void ParameterGrp::importFrom (const char * FileName)
import from a file to this group
Definition at line 284 of file Parameter.cpp.
References ParameterManager::Create().
Referenced by Gui::Dialog::ParameterGroup::onImportFromFile(), and Base::ParameterGrpPy::~ParameterGrpPy().
insert()
void ParameterGrp::insert (const char * FileName)
insert from a file to this group, overwrite only the similar
Definition at line 295 of file Parameter.cpp.
References ParameterManager::Create().
insertTo()
void ParameterGrp::insertTo (const Base::Reference< ParameterGrp > & Grp)
overwrite everything similar, leave the others alone
Definition at line 223 of file Parameter.cpp.
References GetASCIIMap(), GetBoolMap(), GetFloatMap(), GetGroup(), GetGroups(), GetIntMap(), GetUnsignedMap(), SetASCII(), SetBool(), SetFloat(), SetInt(), and SetUnsigned().
Referenced by copyTo(), and exportTo().
IsEmpty()
bool ParameterGrp::IsEmpty () const
test if this group is empty
Definition at line 508 of file Parameter.cpp.
References _pGroupNode.
Referenced by Base::ParameterGrpPy::notify(), and Base::ParameterGrpPy::remString().
Manager()
ParameterManager* ParameterGrp::Manager () const inline
Definition at line 284 of file Parameter.h.
References _Manager.
Referenced by Gui::NaviCubeSettings::NaviCubeSettings().
NotifyAll()
void ParameterGrp::NotifyAll ()
Notifies all observers for all entries except of sub-groups.
Definition at line 1494 of file Parameter.cpp.
References GetASCIIMap(), GetBoolMap(), GetFloatMap(), GetIntMap(), GetUnsignedMap(), and Base::Subject< const char * >::Notify().
Referenced by Gui::EditorView::EditorView(), Gui::MacroManager::MacroManager(), Gui::PythonConsole::PythonConsole(), Gui::DockWnd::ReportOutput::ReportOutput(), Gui::StatusBarObserver::StatusBarObserver(), and Gui::TextEditor::TextEditor().
operator=() [1/2]
ParameterGrp& ParameterGrp::operator= (const ParameterGrp &) delete
operator=() [2/2]
ParameterGrp& ParameterGrp::operator= (ParameterGrp &&) delete
Parent()
ParameterGrp* ParameterGrp::Parent () const inline
Definition at line 280 of file Parameter.h.
References _Parent.
RemoveASCII()
void ParameterGrp::RemoveASCII (const char * Name)
remove a string value from this group
Definition at line 1142 of file Parameter.cpp.
References _Notify(), _pGroupNode, FCText, FindElement(), and Base::Subject< const char * >::Notify().
Referenced by Gui::PrefQuantitySpinBoxPrivate::clearHistory(), Base::ParameterGrpPy::remGroup(), RemoveAttribute(), Gui::Dialog::ParameterText::removeFromGroup(), Gui::Dialog::ParameterText::replace(), Gui::ShortcutManager::reset(), Gui::Dialog::DlgSettingsNavigation::resetSettingsToDefaults(), Gui::Dialog::DlgSettingsEditor::resetSettingsToDefaults(), Gui::Dialog::DlgSettingsGeneral::resetSettingsToDefaults(), Gui::Dialog::DlgSettingsMacroImp::resetSettingsToDefaults(), Gui::Dialog::DlgSettingsWorkbenchesImp::resetSettingsToDefaults(), revert(), Gui::Dialog::DlgSettingsNavigation::saveSettings(), and Gui::ShortcutManager::setShortcut().
RemoveAttribute()
void ParameterGrp::RemoveAttribute (ParamType Type, const char * Name)
Definition at line 590 of file Parameter.cpp.
References FCBool, FCFloat, FCGroup, FCInt, FCText, FCUInt, RemoveASCII(), RemoveBool(), RemoveFloat(), RemoveGrp(), RemoveInt(), and RemoveUnsigned().
Referenced by Gui::Dialog::PreferencePage::resetSettingsToDefaults().
RemoveBool()
void ParameterGrp::RemoveBool (const char * Name)
remove a bool value from this group
Definition at line 1163 of file Parameter.cpp.
References _Notify(), _pGroupNode, FCBool, FindElement(), and Base::Subject< const char * >::Notify().
Referenced by Base::ParameterGrpPy::remInt(), RemoveAttribute(), Gui::Dialog::ParameterBool::removeFromGroup(), Gui::Dialog::ParameterBool::replace(), Gui::Dialog::DlgSettingsNavigation::resetSettingsToDefaults(), Gui::Dialog::DlgSettingsGeneral::resetSettingsToDefaults(), TechDrawGui::DlgPrefsTechDrawDimensionsImp::resetSettingsToDefaults(), SketcherGui::SketcherSettings::resetSettingsToDefaults(), and revert().
RemoveFloat()
void ParameterGrp::RemoveFloat (const char * Name)
remove a float value from this group
Definition at line 1185 of file Parameter.cpp.
References _Notify(), _pGroupNode, FCFloat, FindElement(), and Base::Subject< const char * >::Notify().
Referenced by Base::ParameterGrpPy::remBool(), RemoveAttribute(), Gui::Dialog::ParameterFloat::removeFromGroup(), Gui::Dialog::ParameterFloat::replace(), Gui::Dialog::DlgSettingsNavigation::resetSettingsToDefaults(), and revert().
RemoveGrp()
void ParameterGrp::RemoveGrp (const char * Name)
remove a sub group from this group
Definition at line 1248 of file Parameter.cpp.
References _GroupMap, _pGroupNode, and Base::Subject< const char * >::Notify().
Referenced by Gui::Dialog::ParameterGroup::onDeleteSelectedItem(), RemoveAttribute(), and Base::ParameterGrpPy::remUnsigned().
RemoveInt()
void ParameterGrp::RemoveInt (const char * Name)
remove a int value from this group
Definition at line 1206 of file Parameter.cpp.
References _Notify(), _pGroupNode, FCInt, FindElement(), and Base::Subject< const char * >::Notify().
Referenced by RemoveAttribute(), Gui::Dialog::ParameterInt::removeFromGroup(), Gui::ToolBarAreaWidget::removeWidget(), Gui::Dialog::ParameterInt::replace(), Gui::ShortcutManager::reset(), Gui::Dialog::DlgSettings3DViewImp::resetSettingsToDefaults(), Gui::Dialog::DlgSettingsNavigation::resetSettingsToDefaults(), Gui::Dialog::DlgSettingsEditor::resetSettingsToDefaults(), Gui::Dialog::DlgSettingsGeneral::resetSettingsToDefaults(), SketcherGui::SketcherSettings::resetSettingsToDefaults(), Gui::Dialog::DlgSettingsCacheDirectory::resetSettingsToDefaults(), revert(), Gui::ToolBarAreaWidget::saveState(), and Gui::ShortcutManager::setPriority().
RemoveUnsigned()
void ParameterGrp::RemoveUnsigned (const char * Name)
remove a uint value from this group
Definition at line 1227 of file Parameter.cpp.
References _Notify(), _pGroupNode, FCUInt, FindElement(), and Base::Subject< const char * >::Notify().
Referenced by RemoveAttribute(), Gui::Dialog::ParameterUInt::removeFromGroup(), Gui::Dialog::ParameterUInt::replace(), Gui::Dialog::DlgSettingsEditor::resetSettingsToDefaults(), Gui::Dialog::DlgSettingsCacheDirectory::resetSettingsToDefaults(), and revert().
RenameGrp()
bool ParameterGrp::RenameGrp (const char * OldName, const char * NewName)
rename a sub group from this group
Definition at line 1279 of file Parameter.cpp.
References _GroupMap, _Notify(), _pGroupNode, FCGroup, and FindElement().
Referenced by SetAttribute().
revert() [1/2]
void ParameterGrp::revert (const Base::Reference< ParameterGrp > & Grp)
revert to default value by deleting any parameter that has the same value in the given group
Definition at line 317 of file Parameter.cpp.
References GetASCII(), GetASCIIMap(), GetBool(), GetBoolMap(), GetFloat(), GetFloatMap(), GetGroup(), GetGroups(), GetInt(), GetIntMap(), GetUnsigned(), GetUnsignedMap(), toolbit-attributes::grp, HasGroup(), RemoveASCII(), RemoveBool(), RemoveFloat(), RemoveInt(), RemoveUnsigned(), revert(), and TestSpreadsheet::v.
revert() [2/2]
void ParameterGrp::revert (const char * FileName)
revert to default value by deleting any parameter that has the same value in the given file
Definition at line 306 of file Parameter.cpp.
References ParameterManager::Create().
Referenced by revert().
SetASCII() [1/2]
void ParameterGrp::SetASCII (const char * Name, const char * sValue)
set a string value
Definition at line 1014 of file Parameter.cpp.
References _Clearing, _cName, _Notify(), _pGroupNode, StrXUTF8::c_str(), CreateElement(), FC_LOG_INSTANCE, FC_LOGLEVEL_LOG, FC_WARN, FCText, FindElement(), GetPath(), Base::Subject< const char * >::Notify(), and XERCES_CPP_NAMESPACE_QUALIFIER.
Referenced by Gui::Dialog::DlgAddProperty::accept(), Gui::Dialog::DlgAddPropertyVarSet::accept(), StdCmdImport::activated(), StdCmdExport::activated(), StdCmdOnlineHelpWebsite::activated(), StdCmdFreeCADDonation::activated(), StdCmdFreeCADWebsite::activated(), StdCmdFreeCADUserHub::activated(), StdCmdFreeCADPowerUserHub::activated(), StdCmdFreeCADForum::activated(), StdCmdFreeCADFAQ::activated(), StdCmdReportBug::activated(), StdViewScreenShot::activated(), Gui::Application::activateWorkbench(), Gui::Dialog::ParameterText::appendToGroup(), Gui::Dialog::ParameterText::changeValue(), Gui::Dialog::DlgParameterImp::closeEvent(), copyTemplateParameters(), Gui::CreateViewStdCommands(), Gui::View3DInventor::customEvent(), Part::IGES::ImportExportSettings::getBRepMode(), Gui::Dialog::ButtonModel::insertButtonRows(), insertTo(), Gui::Dialog::DlgSettingsGeneral::loadThemes(), Gui::Dialog::DlgMacroRecordImp::onButtonChooseDirClicked(), Gui::InputField::pushToHistory(), Gui::InputField::pushToSavedValues(), Gui::Dialog::ParameterText::replace(), Gui::MacroCommand::save(), Gui::PrefQuantitySpinBoxPrivate::saveHistory(), Gui::FileDialog::saveLocation(), Gui::PrefLineEdit::savePreferences(), Gui::PrefTextEdit::savePreferences(), Gui::PrefFileChooser::savePreferences(), Gui::PrefComboBox::savePreferences(), MatGui::PrefMaterialTreeWidget::savePreferences(), Gui::PrefQuantitySpinBox::savePreferences(), Gui::PrefFontBox::savePreferences(), Gui::Dialog::DlgSettingsNavigation::saveSettings(), Gui::Dialog::DlgSettingsEditor::saveSettings(), SpreadsheetGui::DlgSettingsImp::saveSettings(), MeshGui::DlgSettingsImportExport::saveSettings(), Gui::Dialog::DlgSettingsMacroImp::saveSettings(), Gui::Dialog::DlgSettingsWorkbenchesImp::saveSettings(), Gui::OverlayTabWidget::saveTabs(), Gui::Dialog::DlgSettingsGeneral::saveThemes(), Gui::MainWindow::saveWindowSettings(), SetAttribute(), SketcherGui::ViewProviderSketch::setEditViewer(), Gui::ShortcutManager::setShortcut(), and Part::STEP::ImportExportSettings::setVisibleExportDialog().
SetASCII() [2/2]
void ParameterGrp::SetASCII (const char * Name, const std::string & sValue) inline
set a string value
Definition at line 245 of file Parameter.h.
SetAttribute()
void ParameterGrp::SetAttribute (ParamType Type, const char * Name, const char * Value)
Definition at line 572 of file Parameter.cpp.
References _SetAttribute(), FCBool, FCFloat, FCGroup, FCInt, FCText, FCUInt, RenameGrp(), and SetASCII().
SetBool()
void ParameterGrp::SetBool (const char * Name, bool bValue)
set a bool value
Definition at line 737 of file Parameter.cpp.
References _SetAttribute(), and FCBool.
Referenced by CmdSketcherSnap::activated(), Gui::Dialog::ParameterBool::appendToGroup(), Gui::Dialog::ParameterBool::changeValue(), Gui::MainWindow::confirmSave(), Gui::TreeWidget::contextMenuEvent(), Gui::PythonConsole::contextMenuEvent(), copyTemplateParameters(), SnapSpaceAction::createWidget(), MeshGui::ViewProviderMesh::faceInfoCallback(), StartGui::StartView::firstStartWidgetDismissed(), Part::OCAF::ImportExportSettings::getIGESSettings(), Part::OCAF::ImportExportSettings::getSTEPSettings(), insertTo(), Gui::Dialog::DlgCustomizeSpNavSettings::on_ButtonCalibrate_clicked(), Gui::Dialog::DlgCustomizeSpNavSettings::on_CBDominant_clicked(), Gui::Dialog::DlgCustomizeSpNavSettings::on_CBEnablePanLR_clicked(), Gui::Dialog::DlgCustomizeSpNavSettings::on_CBEnablePanUD_clicked(), Gui::Dialog::DlgCustomizeSpNavSettings::on_CBEnableRoll_clicked(), Gui::Dialog::DlgCustomizeSpNavSettings::on_CBEnableSpin_clicked(), Gui::Dialog::DlgCustomizeSpNavSettings::on_CBEnableTilt_clicked(), Gui::Dialog::DlgCustomizeSpNavSettings::on_CBEnableZoom_clicked(), Gui::Dialog::DlgCustomizeSpNavSettings::on_CBFlipYZ_clicked(), Gui::Dialog::DlgCustomizeSpNavSettings::on_CBReversePanLR_clicked(), Gui::Dialog::DlgCustomizeSpNavSettings::on_CBReversePanUD_clicked(), Gui::Dialog::DlgCustomizeSpNavSettings::on_CBReverseRoll_clicked(), Gui::Dialog::DlgCustomizeSpNavSettings::on_CBReverseSpin_clicked(), Gui::Dialog::DlgCustomizeSpNavSettings::on_CBReverseTilt_clicked(), Gui::Dialog::DlgCustomizeSpNavSettings::on_CBReverseZoom_clicked(), Gui::Dialog::DlgCustomizeSpNavSettings::on_CBRotations_clicked(), Gui::Dialog::DlgCustomizeSpNavSettings::on_CBTranslations_clicked(), Gui::OverlayTabWidget::onAction(), SketcherGui::TaskSketcherElements::onFilterBoxStateChanged(), SketcherGui::TaskSketcherConstraints::onFilterBoxStateChanged(), SketcherGui::TaskSketcherConstraints::onSettingsAutoRemoveRedundantChanged(), SketcherGui::TaskSketcherElements::onSettingsExtendedInformationChanged(), SketcherGui::TaskSketcherConstraints::onSettingsExtendedInformationChanged(), SketcherGui::TaskSketcherConstraints::onSettingsHideInternalAligmentChanged(), SketcherGui::TaskSketcherConstraints::onSettingsRestrictVisibilityChanged(), Gui::DockWnd::ReportOutput::onToggleCritical(), Gui::DockWnd::ReportOutput::onToggleError(), Gui::DockWnd::ReportOutput::onToggleGoToEnd(), Gui::DockWnd::ReportOutput::onToggleLogMessage(), Gui::DockWnd::ReportOutput::onToggleNormalMessage(), Gui::DockWnd::ReportOutput::onToggleRedirectPythonStderr(), Gui::DockWnd::ReportOutput::onToggleRedirectPythonStdout(), Gui::ToolBarManager::onToggleStatusBarWidget(), Gui::DockWnd::ReportOutput::onToggleWarning(), SketcherGui::TaskDlgEditSketch::reject(), Gui::Dialog::ParameterBool::replace(), Gui::MainWindowP::restoreWindowState(), Gui::MacroCommand::save(), Gui::AutoSaver::saveDocument(), MeshPartGui::Tessellation::saveParameters(), Gui::PrefComboBox::savePreferences(), Gui::PrefCheckBox::savePreferences(), Gui::PrefRadioButton::savePreferences(), Gui::Dialog::DlgSettingsNavigation::saveSettings(), Gui::Dialog::DlgSettingsGeneral::saveSettings(), TechDrawGui::DlgPrefsTechDrawDimensionsImp::saveSettings(), SketcherGui::SketcherSettings::saveSettings(), Gui::Dialog::DlgSettingsNotificationArea::saveSettings(), Gui::DockWindowManager::saveState(), Gui::ToolBarManager::saveState(), Gui::MainWindow::saveWindowSettings(), Gui::OverlayTabWidget::setAutoMode(), Part::OCAF::ImportExportSettings::setExportHiddenObject(), Part::OCAF::ImportExportSettings::setExportKeepPlacement(), Part::OCAF::ImportExportSettings::setExportLegacy(), Gui::Dialog::DlgCheckableMessageBox::setIconPixmap(), Part::OCAF::ImportExportSettings::setImportHiddenObject(), FemGui::FemSettings::setPostAutoRecompute(), Gui::ToolBarManager::setState(), Gui::OverlayTabWidget::setTransparent(), Part::OCAF::ImportExportSettings::setUseLinkGroup(), StartGui::StartView::showOnStartupChanged(), ShowRestoreInformationLayer(), and MeshGui::DlgEvaluateMeshImp::~DlgEvaluateMeshImp().
SetFloat()
void ParameterGrp::SetFloat (const char * Name, double dValue)
read float values or give default
Definition at line 959 of file Parameter.cpp.
References _SetAttribute(), and FCFloat.
Referenced by Gui::Dialog::ParameterFloat::appendToGroup(), Gui::Dialog::ParameterFloat::changeValue(), copyTemplateParameters(), SnapSpaceAction::createWidget(), insertTo(), Gui::Dialog::ParameterFloat::replace(), MeshPartGui::Tessellation::saveParameters(), Gui::PrefDoubleSpinBox::savePreferences(), Gui::PrefComboBox::savePreferences(), Gui::PrefUnitSpinBox::savePreferences(), InspectionGui::VisualInspection::saveSettings(), Gui::Dialog::DlgSettingsNavigation::saveSettings(), and MeshGui::DlgSettingsImportExport::saveSettings().
SetInt()
void ParameterGrp::SetInt (const char * Name, long lValue)
set a int value
Definition at line 812 of file Parameter.cpp.
References _SetAttribute(), and FCInt.
Referenced by StdViewScreenShot::activated(), Gui::ToolBarAreaWidget::addWidget(), Gui::Dialog::ParameterInt::appendToGroup(), Gui::Dialog::ParameterInt::changeValue(), copyTemplateParameters(), Gui::PropertyEditor::PropertyEditor::eventFilter(), insertTo(), Gui::Dialog::DlgCustomizeSpNavSettings::on_SliderGlobal_sliderReleased(), Gui::Dialog::DlgCustomizeSpNavSettings::on_SliderPanLR_sliderReleased(), Gui::Dialog::DlgCustomizeSpNavSettings::on_SliderPanUD_sliderReleased(), Gui::Dialog::DlgCustomizeSpNavSettings::on_SliderRoll_sliderReleased(), Gui::Dialog::DlgCustomizeSpNavSettings::on_SliderSpin_sliderReleased(), Gui::Dialog::DlgCustomizeSpNavSettings::on_SliderTilt_sliderReleased(), Gui::Dialog::DlgCustomizeSpNavSettings::on_SliderZoom_sliderReleased(), SketcherGui::TaskSketcherConstraints::onFilterListItemChanged(), Gui::Dialog::DlgSettingsGeneral::onLinkActivated(), SketcherGui::TaskSketcherElements::onListMultiFilterItemChanged(), Gui::Dialog::ParameterInt::replace(), Gui::PrefSpinBox::savePreferences(), Gui::PrefComboBox::savePreferences(), Gui::PrefSlider::savePreferences(), Gui::MDIView::savePrinterSettings(), Gui::Dialog::DlgSettingsNavigation::saveSettings(), Gui::Dialog::DlgSettingsEditor::saveSettings(), Gui::Dialog::DlgSettingsGeneral::saveSettings(), FemGui::DlgSettingsFemExportAbaqusImp::saveSettings(), FemGui::DlgSettingsFemInOutVtkImp::saveSettings(), SketcherGui::SketcherSettings::saveSettings(), FemGui::DlgSettingsFemZ88Imp::saveSettings(), FemGui::DlgSettingsFemCcxImp::saveSettings(), SketcherGui::SketcherSettingsGrid::saveSettings(), SketcherGui::SketcherSettingsAppearance::saveSettings(), Gui::ToolBarAreaWidget::saveState(), Gui::Dialog::ApplicationCacheSettings::setCheckPeriod(), Gui::OverlayTabWidget::setOffset(), Gui::ShortcutManager::setPriority(), Gui::OverlayTabWidget::setRect(), Gui::OverlayTabWidget::setSizeDelta(), Gui::ShortcutManager::setTopPriority(), Part::OCAF::ImportExportSettings::setUseBaseName(), Part::STEP::ImportExportSettings::setVisibleImportDialog(), Gui::Dialog::DlgPreferencePackManagementImp::showAddonManager(), Gui::PropertyView::tabChanged(), and Gui::Multisample::writeMSAAToSettings().
SetUnsigned()
void ParameterGrp::SetUnsigned (const char * Name, unsigned long lValue)
set a uint value
Definition at line 883 of file Parameter.cpp.
References _SetAttribute(), and FCUInt.
Referenced by Gui::Dialog::ParameterUInt::appendToGroup(), Gui::PythonConsole::changeEvent(), Gui::DockWnd::ReportOutput::changeEvent(), Gui::Dialog::ParameterUInt::changeValue(), copyTemplateParameters(), insertTo(), Gui::Dialog::ParameterUInt::replace(), Gui::PrefComboBox::savePreferences(), Gui::PrefColorButton::savePreferences(), Gui::Dialog::DlgSettingsEditor::saveSettings(), Gui::Dialog::ApplicationCacheSettings::setCacheSizeLimit(), and StartGui::ThemeSelectorWidget::themeChanged().
ShouldRemove()
bool ParameterGrp::ShouldRemove () const protected
Definition at line 1374 of file Parameter.cpp.
References _GroupMap, and Base::Handled::getRefCount().
TypeName()
const char * ParameterGrp::TypeName (ParamType type) static
Definition at line 527 of file Parameter.cpp.
References FCBool, FCFloat, FCGroup, FCInt, FCText, and FCUInt.
Referenced by _SetAttribute(), GetAttribute(), and GetAttributeMap().
TypeValue()
ParameterGrp::ParamType ParameterGrp::TypeValue (const char * Name) static
Definition at line 547 of file Parameter.cpp.
References DraftVecUtils::equals(), FCBool, FCFloat, FCGroup, FCInt, FCInvalid, FCText, and FCUInt.
Referenced by Clear(), and GetParameterNames().
Friends And Related Function Documentation
ParameterManager
friend class ParameterManager friend
Definition at line 264 of file Parameter.h.
Member Data Documentation
_Clearing
bool ParameterGrp::_Clearing = false protected
Indicate this group is currently being cleared
This is used to prevent anynew value/sub-group to be added in observer
Definition at line 353 of file Parameter.h.
Referenced by _GetGroup(), _SetAttribute(), Clear(), and SetASCII().
_cName
std::string ParameterGrp::_cName protected
the own name
Definition at line 342 of file Parameter.h.
Referenced by _GetGroup(), _SetAttribute(), CreateElement(), GetGroup(), GetGroupName(), GetPath(), ParameterGrp(), and SetASCII().
_Detached
bool ParameterGrp::_Detached = false protected
Means this group xml element has not been added to its parent yet.
Definition at line 348 of file Parameter.h.
Referenced by _GetGroup(), CreateElement(), and ~ParameterGrp().
_GroupMap
std::map<std::string, Base::Reference<ParameterGrp> > ParameterGrp::_GroupMap protected
map of already exported groups
Definition at line 344 of file Parameter.h.
Referenced by _GetGroup(), _Reset(), Clear(), GetGroups(), HasGroup(), RemoveGrp(), RenameGrp(), ShouldRemove(), and ~ParameterGrp().
_Manager
ParameterManager* ParameterGrp::_Manager = nullptr protected
Definition at line 346 of file Parameter.h.
Referenced by _Notify(), GetPath(), Manager(), and ParameterGrp().
_Parent
ParameterGrp* ParameterGrp::_Parent = nullptr protected
Definition at line 345 of file Parameter.h.
Referenced by _GetGroup(), CreateElement(), GetPath(), ParameterGrp(), and Parent().
_pGroupNode
DOMElement* ParameterGrp::_pGroupNode protected
DOM Node of the Base node of this group.
Definition at line 340 of file Parameter.h.
Referenced by _GetGroup(), _Reset(), _SetAttribute(), Clear(), ParameterManager::CreateDocument(), GetASCII(), GetASCIIMap(), GetASCIIs(), GetAttribute(), GetAttributeMap(), GetBool(), GetBoolMap(), GetBools(), GetFloat(), GetFloatMap(), GetFloats(), GetGroups(), GetInt(), GetIntMap(), GetInts(), GetParameterNames(), GetUnsigned(), GetUnsignedMap(), GetUnsigneds(), HasGroup(), IsEmpty(), ParameterManager::LoadDocument(), RemoveASCII(), RemoveBool(), RemoveFloat(), RemoveGrp(), RemoveInt(), RemoveUnsigned(), RenameGrp(), SetASCII(), and ~ParameterGrp().
The documentation for this class was generated from the following files:
Parameter.h
Parameter.cpp