FreeCAD: Path.Post.scripts.marlin_post Namespace Reference
Path.Post.scripts.marlin_post Namespace Reference
Functions
def processArguments (argstring)
def dump (obj)
def export (objectslist, filename, argstring)
def linenumber ()
def format_outlist (strTable)
def parse (pathobj)
def drill_translate (outlist, cmd, params)
Variables
Revised
TOOLTIP
MOTION_MODE
WORK_PLANE
UNITS
UNIT_FORMAT
UNIT_FEED_FORMAT
PRECISION
DRILL_RETRACT_MODE
TRANSLATE_DRILL_CYCLES
OUTPUT_TOOL_CHANGE
RETURN_TO
SPINDLE_WAIT
MODAL
LINENR
LINEINCR
PRE_OPERATION
POST_OPERATION
TOOL_CHANGE
OUTPUT_HEADER
OUTPUT_COMMENTS
OUTPUT_FINISH
OUTPUT_PATH
OUTPUT_MARLIN_CONFIG
OUTPUT_LINE_NUMBERS
OUTPUT_BCNC
SHOW_EDITOR
parser
prog
add_help
action = "store_true",
help = "suppress finish-comment output (default)",
default = 3,
type = int,
TOOLTIP_ARGS
PREAMBLE
POSTAMBLE
MOTION_COMMANDS
RAPID_MOVES
SUPPRESS_COMMANDS
COMMAND_SPACE
CURRENT_X
CURRENT_Y
CURRENT_Z
Function Documentation
drill_translate()
def Path.Post.scripts.marlin_post.drill_translate (outlist, cmd, params)
Definition at line 651 of file marlin_post.py.
References Path.Post.scripts.marlin_post.format_outlist(), Path.Post.scripts.marlin_post.linenumber(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.scripts.marlin_post.parse().
dump()
def Path.Post.scripts.marlin_post.dump (obj)
Definition at line 294 of file marlin_post.py.
export()
def Path.Post.scripts.marlin_post.export (objectslist, filename, argstring)
Definition at line 310 of file marlin_post.py.
References Path.Post.scripts.marlin_post.linenumber(), AssemblyImport.open(), Path.Post.scripts.marlin_post.parse(), Path.Post.scripts.marlin_post.processArguments(), and Path.Post.scripts.refactored_centroid_post.str.
format_outlist()
def Path.Post.scripts.marlin_post.format_outlist (strTable)
Definition at line 473 of file marlin_post.py.
Referenced by Path.Post.scripts.marlin_post.drill_translate(), and Path.Post.scripts.marlin_post.parse().
linenumber()
def Path.Post.scripts.marlin_post.linenumber ()
Definition at line 464 of file marlin_post.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.scripts.marlin_post.drill_translate(), Path.Post.scripts.marlin_post.export(), and Path.Post.scripts.marlin_post.parse().
parse()
def Path.Post.scripts.marlin_post.parse (pathobj)
Definition at line 482 of file marlin_post.py.
References Path.Post.scripts.marlin_post.drill_translate(), DraftVecUtils.find(), Path.Post.scripts.marlin_post.format_outlist(), Path.Post.scripts.marlin_post.linenumber(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.scripts.marlin_post.export().
processArguments()
def Path.Post.scripts.marlin_post.processArguments (argstring)
Definition at line 214 of file marlin_post.py.
Referenced by Path.Post.scripts.marlin_post.export().
Variable Documentation
action
string Path.Post.scripts.marlin_post.action = "store_true",
Definition at line 106 of file marlin_post.py.
add_help
Path.Post.scripts.marlin_post.add_help
Definition at line 105 of file marlin_post.py.
COMMAND_SPACE
Path.Post.scripts.marlin_post.COMMAND_SPACE
Definition at line 207 of file marlin_post.py.
CURRENT_X
Path.Post.scripts.marlin_post.CURRENT_X
Definition at line 209 of file marlin_post.py.
CURRENT_Y
Path.Post.scripts.marlin_post.CURRENT_Y
Definition at line 210 of file marlin_post.py.
CURRENT_Z
Path.Post.scripts.marlin_post.CURRENT_Z
Definition at line 211 of file marlin_post.py.
default
string Path.Post.scripts.marlin_post.default = 3,
Definition at line 144 of file marlin_post.py.
DRILL_RETRACT_MODE
Path.Post.scripts.marlin_post.DRILL_RETRACT_MODE
Definition at line 71 of file marlin_post.py.
help
string Path.Post.scripts.marlin_post.help = "suppress finish-comment output (default)",
Definition at line 106 of file marlin_post.py.
LINEINCR
Path.Post.scripts.marlin_post.LINEINCR
Definition at line 81 of file marlin_post.py.
LINENR
Path.Post.scripts.marlin_post.LINENR
Definition at line 80 of file marlin_post.py.
MODAL
Path.Post.scripts.marlin_post.MODAL
Definition at line 78 of file marlin_post.py.
MOTION_COMMANDS
Path.Post.scripts.marlin_post.MOTION_COMMANDS
Definition at line 204 of file marlin_post.py.
MOTION_MODE
Path.Post.scripts.marlin_post.MOTION_MODE
Definition at line 61 of file marlin_post.py.
OUTPUT_BCNC
Path.Post.scripts.marlin_post.OUTPUT_BCNC
Definition at line 98 of file marlin_post.py.
OUTPUT_COMMENTS
Path.Post.scripts.marlin_post.OUTPUT_COMMENTS
Definition at line 93 of file marlin_post.py.
OUTPUT_FINISH
Path.Post.scripts.marlin_post.OUTPUT_FINISH
Definition at line 94 of file marlin_post.py.
OUTPUT_HEADER
Path.Post.scripts.marlin_post.OUTPUT_HEADER
Definition at line 92 of file marlin_post.py.
OUTPUT_LINE_NUMBERS
Path.Post.scripts.marlin_post.OUTPUT_LINE_NUMBERS
Definition at line 97 of file marlin_post.py.
OUTPUT_MARLIN_CONFIG
Path.Post.scripts.marlin_post.OUTPUT_MARLIN_CONFIG
Definition at line 96 of file marlin_post.py.
OUTPUT_PATH
Path.Post.scripts.marlin_post.OUTPUT_PATH
Definition at line 95 of file marlin_post.py.
OUTPUT_TOOL_CHANGE
Path.Post.scripts.marlin_post.OUTPUT_TOOL_CHANGE
Definition at line 75 of file marlin_post.py.
parser
Path.Post.scripts.marlin_post.parser
Definition at line 105 of file marlin_post.py.
POST_OPERATION
Path.Post.scripts.marlin_post.POST_OPERATION
Definition at line 84 of file marlin_post.py.
POSTAMBLE
Path.Post.scripts.marlin_post.POSTAMBLE
Definition at line 198 of file marlin_post.py.
PRE_OPERATION
Path.Post.scripts.marlin_post.PRE_OPERATION
Definition at line 82 of file marlin_post.py.
PREAMBLE
Path.Post.scripts.marlin_post.PREAMBLE
Definition at line 195 of file marlin_post.py.
PRECISION
Path.Post.scripts.marlin_post.PRECISION
Definition at line 70 of file marlin_post.py.
prog
Path.Post.scripts.marlin_post.prog
Definition at line 105 of file marlin_post.py.
RAPID_MOVES
Path.Post.scripts.marlin_post.RAPID_MOVES
Definition at line 205 of file marlin_post.py.
RETURN_TO
Path.Post.scripts.marlin_post.RETURN_TO
Definition at line 76 of file marlin_post.py.
Revised
Path.Post.scripts.marlin_post.Revised
Definition at line 40 of file marlin_post.py.
SHOW_EDITOR
Path.Post.scripts.marlin_post.SHOW_EDITOR
Definition at line 100 of file marlin_post.py.
SPINDLE_WAIT
Path.Post.scripts.marlin_post.SPINDLE_WAIT
Definition at line 77 of file marlin_post.py.
SUPPRESS_COMMANDS
Path.Post.scripts.marlin_post.SUPPRESS_COMMANDS
Definition at line 206 of file marlin_post.py.
TOOL_CHANGE
Path.Post.scripts.marlin_post.TOOL_CHANGE
Definition at line 86 of file marlin_post.py.
TOOLTIP
Path.Post.scripts.marlin_post.TOOLTIP
Definition at line 52 of file marlin_post.py.
TOOLTIP_ARGS
Path.Post.scripts.marlin_post.TOOLTIP_ARGS
Definition at line 182 of file marlin_post.py.
TRANSLATE_DRILL_CYCLES
Path.Post.scripts.marlin_post.TRANSLATE_DRILL_CYCLES
Definition at line 73 of file marlin_post.py.
type
Path.Post.scripts.marlin_post.type = int,
Definition at line 164 of file marlin_post.py.
UNIT_FEED_FORMAT
Path.Post.scripts.marlin_post.UNIT_FEED_FORMAT
Definition at line 65 of file marlin_post.py.
UNIT_FORMAT
Path.Post.scripts.marlin_post.UNIT_FORMAT
Definition at line 64 of file marlin_post.py.
UNITS
Path.Post.scripts.marlin_post.UNITS
Definition at line 63 of file marlin_post.py.
WORK_PLANE
Path.Post.scripts.marlin_post.WORK_PLANE
Definition at line 62 of file marlin_post.py.