FreeCAD: AppCloud.cpp File Reference
AppCloud.cpp File Reference
#include "PreCompiled.h"
#include <openssl/hmac.h>
#include <openssl/md5.h>
#include <openssl/pem.h>
#include <openssl/sha.h>
#include <curl/curl.h>
#include <App/Application.h>
#include <App/Document.h>
#include <App/DocumentObject.h>
#include <App/DocumentPy.h>
#include <Base/Console.h>
#include <Base/Tools.h>
#include <Base/PyObjectBase.h>
#include <CXX/Extensions.hxx>
#include <CXX/Objects.hxx>
#include "AppCloud.h"
Classes
struct data_buffer
Functions
XERCES_CPP_NAMESPACE_USE PyMOD_INIT_FUNC (Cloud)
static size_t read_callback (void *ptr, size_t size, size_t nmemb, void *stream)
void readFiles (Cloud::CloudReader reader, Base::XMLReader *xmlreader)
Function Documentation
PyMOD_INIT_FUNC()
XERCES_CPP_NAMESPACE_USE PyMOD_INIT_FUNC (Cloud)
Definition at line 57 of file AppCloud.cpp.
References Base::Console(), Cloud::initModule(), Base::ConsoleSingleton::Log(), mod, and PyMOD_Return.
read_callback()
static size_t read_callback (void * ptr, size_t size, size_t nmemb, void * stream) static
Definition at line 195 of file AppCloud.cpp.
References data_buffer::ptr, and data_buffer::remaining_size.
Referenced by Cloud::CloudWriter::createBucket(), and Cloud::CloudWriter::pushCloud().
readFiles()
void readFiles (Cloud::CloudReader reader, Base::XMLReader * xmlreader)
Definition at line 1407 of file AppCloud.cpp.
References Base::XMLReader::FileList, Base::XMLReader::FileVersion, Base::Reader::getLocalReader(), Base::Reader::getStream(), TechDrawTools.TaskFillTemplateFields::reader, and readFiles().
Referenced by Cloud::Module::cloudRestore(), and readFiles().