FreeCAD: Gui::ProgressDialog Class Reference
Gui::ProgressDialog Class Reference
#include <ProgressDialog.h>
Public Member Functions
ProgressDialog (SequencerDialog *s, QWidget *parent=nullptr)
~ProgressDialog () override
Protected Slots
void onCancel ()
Protected Member Functions
bool canAbort () const
Friends
class SequencerDialog
Detailed Description
Definition at line 100 of file ProgressDialog.h.
Constructor & Destructor Documentation
ProgressDialog()
ProgressDialog::ProgressDialog (SequencerDialog * s, QWidget * parent = nullptr) explicit
Construction
Definition at line 296 of file ProgressDialog.cpp.
References draftgeoutils.intersections::connect(), and onCancel().
~ProgressDialog()
ProgressDialog::~ProgressDialog () override default
Destruction
Member Function Documentation
canAbort()
bool ProgressDialog::canAbort () const protected
Definition at line 313 of file ProgressDialog.cpp.
References Gui::getMainWindow().
Referenced by Gui::SequencerDialog::nextStep().
onCancel
void ProgressDialog::onCancel () protected slot
Definition at line 308 of file ProgressDialog.cpp.
References Base::SequencerBase::tryToCancel().
Referenced by ProgressDialog().
Friends And Related Function Documentation
SequencerDialog
friend class SequencerDialog friend
Definition at line 134 of file ProgressDialog.h.
The documentation for this class was generated from the following files:
ProgressDialog.h
ProgressDialog.cpp