FreeCAD: src.Mod.PartDesign.fcgear.involute Namespace Reference
src.Mod.PartDesign.fcgear.involute Namespace Reference
Functions
def CreateExternalGear (w, m, Z, phi, split=True, addCoeff=1.0, dedCoeff=1.25, filletCoeff=0.375, shiftCoeff=0.0)
def CreateInternalGear (w, m, Z, phi, split=True, addCoeff=0.6, dedCoeff=1.25, filletCoeff=0.375, shiftCoeff=0.0)
def genInvolutePolar (Rb, R)
def rotate (pt, rads)
def mirror (pt)
def toCartesian (radius, angle)
def findRootNewton (f, f_prime, x_min, x_max)
def chebyExpnCoeffs (j, func)
def chebyPolyCoeffs (p, func)
def bezCoeff (i, p, polyCoeffs)
def BezCoeffs (baseRadius, limitRadius, order, fstart, fstop)
Function Documentation
bezCoeff()
def src.Mod.PartDesign.fcgear.involute.bezCoeff (i, p, polyCoeffs)
generate the polynomial coeffs in one go
Definition at line 430 of file involute.py.
Referenced by src.Mod.PartDesign.fcgear.involute.BezCoeffs().
BezCoeffs()
def src.Mod.PartDesign.fcgear.involute.BezCoeffs (baseRadius, limitRadius, order, fstart, fstop)
Approximates an involute using a Bezier-curve
Parameters:
baseRadius - the radius of base circle of the involute.
    This is where the involute starts, too.
limitRadius - the radius of an outer circle, where the involute ends.
order - the order of the Bezier curve to be fitted e.g. 3, 4, 5, ...
fstart - fraction of distance along the involute to start the approximation.
fstop - fraction of distance along the involute to stop the approximation.
Definition at line 435 of file involute.py.
References src.Mod.PartDesign.fcgear.involute.bezCoeff(), src.Mod.PartDesign.fcgear.involute.chebyPolyCoeffs(), KDL.cos(), KDL.sin(), and KDL.sqrt().
Referenced by src.Mod.PartDesign.fcgear.involute.CreateInternalGear().
chebyExpnCoeffs()
def src.Mod.PartDesign.fcgear.involute.chebyExpnCoeffs (j, func)
Definition at line 387 of file involute.py.
References KDL.cos().
Referenced by src.Mod.PartDesign.fcgear.involute.chebyPolyCoeffs().
chebyPolyCoeffs()
def src.Mod.PartDesign.fcgear.involute.chebyPolyCoeffs (p, func)
Definition at line 395 of file involute.py.
References src.Mod.PartDesign.fcgear.involute.chebyExpnCoeffs().
Referenced by src.Mod.PartDesign.fcgear.involute.BezCoeffs().
CreateExternalGear()
def src.Mod.PartDesign.fcgear.involute.CreateExternalGear (w, m, Z, phi, split = True, addCoeff = 1.0, dedCoeff = 1.25, filletCoeff = 0.375, shiftCoeff = 0.0)
Create an external gear
w is wire builder object (in which the gear will be constructed)
m is the gear's module (pitch diameter divided by the number of teeth)
Z is the number of teeth
phi is the gear's pressure angle, in degrees
addCoeff is the addendum coefficient (addendum normalized by module)
dedCoeff is the dedendum coefficient (dedendum normalized by module)
filletCoeff is the root fillet radius, normalized by the module.
    The default of 0.375 matches the hard-coded value (1.5 * 0.25) of the implementation
    up to v0.20. The ISO Rack specified 0.38, though.
shiftCoeff is the profile shift coefficient (profile shift normalized by module)
if split is True, each profile of a teeth will consist in 2 Bezier
curves of degree 3, otherwise it will be made of one Bezier curve
of degree 4
Definition at line 30 of file involute.py.
CreateInternalGear()
def src.Mod.PartDesign.fcgear.involute.CreateInternalGear (w, m, Z, phi, split = True, addCoeff = 0.6, dedCoeff = 1.25, filletCoeff = 0.375, shiftCoeff = 0.0)
Create an internal gear
w is wire builder object (in which the gear will be constructed)
m is the gear's module (pitch diameter divided by the number of teeth)
Z is the number of teeth
phi is the gear's pressure angle, in degrees
addCoeff is the addendum coefficient (addendum normalized by module)
    The default of 0.6 comes from the "Handbook of Gear Design" by Gitin M. Maitra,
    with the goal to push the addendum circle beyond the base circle to avoid non-involute
    flanks on the tips.
    It in turn assumes, however, that the mating pinion uses a larger value of 1.25.
    And it's only required for a small number of teeth and/or a relatively large mating gear.
    Anyways, it's kept here as this was the hard-coded value of the implementation up to v0.20.
dedCoeff is the dedendum coefficient (dedendum normalized by module)
filletCoeff is the root fillet radius, normalized by the module.
    The default of 0.375 matches the hard-coded value (1.5 * 0.25) of the implementation
    up to v0.20. The ISO Rack specified 0.38, though.
shiftCoeff is the profile shift coefficient (profile shift normalized by module)
if split is True, each profile of a teeth will consist in 2 Bezier
curves of degree 3, otherwise it will be made of one Bezier curve
of degree 4
Definition at line 65 of file involute.py.
References KDL.asin(), KDL.atan(), src.Mod.PartDesign.fcgear.involute.BezCoeffs(), KDL.cos(), src.Mod.PartDesign.fcgear.involute.findRootNewton(), src.Mod.PartDesign.fcgear.involute.genInvolutePolar(), KDL.max(), KDL.sqrt(), KDL.tan(), and src.Mod.PartDesign.fcgear.involute.toCartesian().
findRootNewton()
def src.Mod.PartDesign.fcgear.involute.findRootNewton (f, f_prime, x_min, x_max)
Apply Newton's Method to find the root of f within x_min and x_max
We assume that there is a root in that range and that f is strictly monotonic,
i.e. we don't take precautions for overshooting beyond the input range.
Definition at line 365 of file involute.py.
References KDL.abs(), and SCL.SimpleDataTypes.f.
Referenced by src.Mod.PartDesign.fcgear.involute.CreateInternalGear().
genInvolutePolar()
def src.Mod.PartDesign.fcgear.involute.genInvolutePolar (Rb, R)
return the involute angle as function of radius R.
Rb = base circle radius
Definition at line 340 of file involute.py.
References KDL.acos(), and KDL.sqrt().
Referenced by src.Mod.PartDesign.fcgear.involute.CreateInternalGear().
mirror()
def src.Mod.PartDesign.fcgear.involute.mirror (pt)
mirror pt on the X axis, i.e. flip its Y
Definition at line 355 of file involute.py.
rotate()
def src.Mod.PartDesign.fcgear.involute.rotate (pt, rads)
rotate pt by rads radians about origin
Definition at line 347 of file involute.py.
References KDL.cos(), and KDL.sin().
toCartesian()
def src.Mod.PartDesign.fcgear.involute.toCartesian (radius, angle)
convert polar coords to cartesian
Definition at line 360 of file involute.py.
References KDL.cos(), and KDL.sin().
Referenced by src.Mod.PartDesign.fcgear.involute.CreateInternalGear().