FreeCAD: Gui::SplashScreen Class Reference
Gui::SplashScreen Class Reference
#include <SplashScreen.h>
Public Member Functions
SplashScreen (const QPixmap &pixmap=QPixmap(), Qt::WindowFlags f=Qt::WindowFlags())
~SplashScreen () override
void setShowMessages (bool on)
Static Public Member Functions
static QPixmap splashImage ()
Protected Member Functions
void drawContents (QPainter *painter) override
Detailed Description
This widget provides a splash screen that can be shown during application startup.
Author
Werner Mayer
Definition at line 57 of file SplashScreen.h.
Constructor & Destructor Documentation
SplashScreen()
SplashScreen::SplashScreen (const QPixmap & pixmap = QPixmap(), Qt::WindowFlags f = Qt::WindowFlags()) explicit
Constructs a splash screen that will display the pixmap.
Definition at line 229 of file SplashScreen.cpp.
~SplashScreen()
SplashScreen::~SplashScreen () override
Destruction.
Definition at line 237 of file SplashScreen.cpp.
Member Function Documentation
drawContents()
void SplashScreen::drawContents (QPainter * painter) override protected
Draws the contents of the splash screen using painter painter. The default implementation draws the message passed by message().
Definition at line 246 of file SplashScreen.cpp.
setShowMessages()
void SplashScreen::setShowMessages (bool on)
Definition at line 251 of file SplashScreen.cpp.
Referenced by Gui::MainWindow::startSplasher().
splashImage()
QPixmap SplashScreen::splashImage () static
Definition at line 259 of file SplashScreen.cpp.
References Gui::BitmapFactory(), App::Application::Config(), Gui::BitmapFactoryInst::findIconFiles(), App::Application::getHomePath(), Path.Post.scripts.rml_post::home(), Gui::QtTools::horizontalAdvance(), RobotExample::l, Gui::BitmapFactoryInst::pixmap(), src.Mod.AddonManager.addonmanager_devmode_license_selector::QRegularExpression, KDL::random(), Gui::renderDevBuildWarning(), Plot::title(), TestSpreadsheet::v, Dice3DS::version, src.Mod.PartDesign.fcgear.svggear::w, MovieTool::x, and MovieTool::y.
Referenced by Gui::Dialog::AboutDialog::AboutDialog(), and Gui::MainWindow::startSplasher().
The documentation for this class was generated from the following files:
SplashScreen.h
SplashScreen.cpp