FreeCAD: ifc2x3.ifclocalplacement Class Reference
ifc2x3.ifclocalplacement Class Reference
Public Member Functions
def __init__ (self, placementrelto, relativeplacement)
def placementrelto ()
def relativeplacement ()
def wr21 (self)
Public Member Functions inherited from ifc2x3.ifcobjectplacement
def placesobject ()
def referencedbyplacements ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
placementrelto
relativeplacement
Detailed Description
Entity ifclocalplacement definition.
:param placementrelto
:type placementrelto:ifcobjectplacement
:param relativeplacement
:type relativeplacement:ifcaxis2placement
Definition at line 33192 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifclocalplacement.__init__ (self, placementrelto, relativeplacement)
Definition at line 33201 of file ifc2x3.py.
Member Function Documentation
placementrelto()
def ifc2x3.ifclocalplacement.placementrelto ()
Definition at line 33207 of file ifc2x3.py.
References ifc2x3.ifclocalplacement._placementrelto, SCL.TypeChecker.check_type(), and ifc2x3.ifclocalplacement.placementrelto.
relativeplacement()
def ifc2x3.ifclocalplacement.relativeplacement ()
Definition at line 33221 of file ifc2x3.py.
References ifc2x3.ifclocalplacement._relativeplacement, SCL.TypeChecker.check_type(), ifc2x3.ifcaxis2placement, and ifc2x3.ifclocalplacement.relativeplacement.
wr21()
def ifc2x3.ifclocalplacement.wr21 (self)
Definition at line 33233 of file ifc2x3.py.
References ifc2x3.ifccorrectlocalplacement(), ifc2x3.ifclocalplacement.placementrelto, and ifc2x3.ifclocalplacement.relativeplacement.
Referenced by ifc4.ifcphmeasure.__init__().
Member Data Documentation
placementrelto
ifc2x3.ifclocalplacement.placementrelto
Definition at line 33203 of file ifc2x3.py.
Referenced by ifc2x3.ifclocalplacement.placementrelto(), ifc2x3.ifclocalplacement.wr21(), and ifc4.ifclocalplacement.wr21().
relativeplacement
ifc2x3.ifclocalplacement.relativeplacement
Definition at line 33204 of file ifc2x3.py.
Referenced by ifc2x3.ifclocalplacement.relativeplacement(), ifc2x3.ifclocalplacement.wr21(), and ifc4.ifclocalplacement.wr21().
The documentation for this class was generated from the following file:
ifc2x3.py