FreeCAD: TechDrawGui::SymbolChooser Class Reference
TechDrawGui::SymbolChooser Class Reference
#include <SymbolChooser.h>
Public Slots
void onOKClicked ()
void onCancelClicked ()
void onItemClicked (QListWidgetItem *item)
void onDirectoryChanged (const QString &newDir)
Signals
void symbolSelected (QString symbolPath, QString source)
Public Member Functions
SymbolChooser (QWidget *parent=nullptr, QString startDir=QString(), QString source=QString())
~SymbolChooser () override
Protected Member Functions
void setUiPrimary (void)
void loadSymbolNames (QString pathToSymbols)
Detailed Description
Definition at line 34 of file SymbolChooser.h.
Constructor & Destructor Documentation
SymbolChooser()
SymbolChooser::SymbolChooser (QWidget * parent = nullptr, QString startDir = QString(), QString source = QString())
Definition at line 37 of file SymbolChooser.cpp.
References draftgeoutils.intersections::connect(), onDirectoryChanged(), onItemClicked(), and setUiPrimary().
~SymbolChooser()
SymbolChooser::~SymbolChooser () override
Definition at line 54 of file SymbolChooser.cpp.
Member Function Documentation
loadSymbolNames()
void SymbolChooser::loadSymbolNames (QString pathToSymbols) protected
Definition at line 127 of file SymbolChooser.cpp.
Referenced by onDirectoryChanged(), and setUiPrimary().
onCancelClicked
void SymbolChooser::onCancelClicked () slot
Definition at line 98 of file SymbolChooser.cpp.
onDirectoryChanged
void SymbolChooser::onDirectoryChanged (const QString & newDir) slot
Definition at line 119 of file SymbolChooser.cpp.
References loadSymbolNames().
Referenced by SymbolChooser().
onItemClicked
void SymbolChooser::onItemClicked (QListWidgetItem * item) slot
Definition at line 103 of file SymbolChooser.cpp.
References symbolSelected().
Referenced by SymbolChooser().
onOKClicked
void SymbolChooser::onOKClicked () slot
Definition at line 84 of file SymbolChooser.cpp.
References symbolSelected().
setUiPrimary()
void SymbolChooser::setUiPrimary (void) protected
Definition at line 58 of file SymbolChooser.cpp.
References App::Application::getResourceDir(), and loadSymbolNames().
Referenced by SymbolChooser().
symbolSelected
void TechDrawGui::SymbolChooser::symbolSelected (QString symbolPath, QString source) signal
Referenced by onItemClicked(), onOKClicked(), and TechDrawGui::TaskWeldingSymbol::symbolDialog().
The documentation for this class was generated from the following files:
SymbolChooser.h
SymbolChooser.cpp