FreeCAD: CommandExtensionPack.cpp File Reference
CommandExtensionPack.cpp File Reference
#include "PreCompiled.h"
#include <QApplication>
#include <QMessageBox>
#include <BRepGProp.hxx>
#include <GProp_GProps.hxx>
#include <BRepAdaptor_Curve.hxx>
#include <GCPnts_AbscissaPoint.hxx>
#include <App/Document.h>
#include <App/DocumentObject.h>
#include <Base/Console.h>
#include <Base/Type.h>
#include <Gui/Action.h>
#include <Gui/Application.h>
#include <Gui/BitmapFactory.h>
#include <Gui/Command.h>
#include <Gui/Control.h>
#include <Gui/Document.h>
#include <Gui/MainWindow.h>
#include <Gui/Selection.h>
#include <Gui/SelectionObject.h>
#include <Gui/ViewProvider.h>
#include <Mod/Part/App/Geometry2d.h>
#include <Mod/TechDraw/App/CenterLine.h>
#include <Mod/TechDraw/App/Cosmetic.h>
#include <Mod/TechDraw/App/DrawPage.h>
#include <Mod/TechDraw/App/DrawProjGroup.h>
#include <Mod/TechDraw/App/DrawProjGroupItem.h>
#include <Mod/TechDraw/App/DrawUtil.h>
#include <Mod/TechDraw/App/DrawViewBalloon.h>
#include <Mod/TechDraw/App/DrawViewDimension.h>
#include <Mod/TechDraw/App/DrawViewPart.h>
#include <Mod/TechDraw/App/DrawViewSection.h>
#include <Mod/TechDraw/App/Preferences.h>
#include <Mod/TechDraw/App/LineFormat.h>
#include <Mod/TechDraw/App/LineGenerator.h>
#include <Mod/TechDraw/App/LineGroup.h>
#include "DrawGuiUtil.h"
#include "QGSPage.h"
#include "TaskSelectLineAttributes.h"
#include "ViewProviderBalloon.h"
#include "ViewProviderDimension.h"
#include "ViewProviderPage.h"
Namespaces
TechDrawGui
Typedefs
using DU = DrawUtil
Functions
TechDraw::LineFormat & TechDrawGui::_getActiveLineAttributes ()
Base::Vector3d TechDrawGui::_circleCenter (Base::Vector3d p1, Base::Vector3d p2, Base::Vector3d p3)
void TechDrawGui::_createThreadCircle (const std::string Name, TechDraw::DrawViewPart *objFeat, double factor)
void TechDrawGui::_createThreadLines (const std::vector< std::string > &SubNames, TechDraw::DrawViewPart *objFeat, double factor)
void TechDrawGui::_setLineAttributes (TechDraw::CosmeticEdge *cosEdge)
void TechDrawGui::_setLineAttributes (TechDraw::CenterLine *cosEdge)
void TechDrawGui::_setLineAttributes (TechDraw::CosmeticEdge *cosEdge, int style, float weight, App::Color color)
void TechDrawGui::_setLineAttributes (TechDraw::CenterLine *cosEdge, int style, float weight, App::Color color)
double TechDrawGui::_getAngle (Base::Vector3d center, Base::Vector3d point)
std::vector< Base::Vector3d > TechDrawGui::_getVertexPoints (const std::vector< std::string > &SubNames, TechDraw::DrawViewPart *objFeat)
return the vertices in the selection as [Base::Vector3d]
bool TechDrawGui::_checkSel (Gui::Command *cmd, std::vector< Gui::SelectionObject > &selection, TechDraw::DrawViewPart *&objFeat, const std::string &message)
std::string TechDrawGui::_createBalloon (Gui::Command *cmd, TechDraw::DrawViewPart *objFeat)
void TechDrawGui::execHoleCircle (Gui::Command *cmd)
void execCircleCenterLines (Gui::Command *cmd)
void execThreadHoleSide (Gui::Command *cmd)
void execThreadBoltSide (Gui::Command *cmd)
void execThreadHoleBottom (Gui::Command *cmd)
void execThreadBoltBottom (Gui::Command *cmd)
void execDrawCosmArc (Gui::Command *cmd)
void execDrawCosmCircle (Gui::Command *cmd)
void execDrawCosmCircle3Points (Gui::Command *cmd)
void execLineParallelPerpendicular (Gui::Command *cmd, bool isParallel)
void execExtendShortenLine (Gui::Command *cmd, bool extend)
void CreateTechDrawCommandsExtensions ()
Typedef Documentation
DU
using DU = DrawUtil
Definition at line 73 of file CommandExtensionPack.cpp.
Function Documentation
CreateTechDrawCommandsExtensions()
void CreateTechDrawCommandsExtensions ()
Definition at line 2225 of file CommandExtensionPack.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
execCircleCenterLines()
void execCircleCenterLines (Gui::Command * cmd)
Definition at line 200 of file CommandExtensionPack.cpp.
References TechDrawGui::_checkSel(), TechDrawGui::_setLineAttributes(), TechDraw::ARCOFCIRCLE, exportCSG::center(), TechDraw::CIRCLE, Gui::SelectionSingleton::clearSelection(), Gui::Command::commitCommand(), TechDraw::DrawUtil::getGeomTypeFromName(), TechDraw::DrawUtil::getIndexFromName(), Gui::Command::getSelection(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, and Path.Dressup.Utils::selection().
execDrawCosmArc()
void execDrawCosmArc (Gui::Command * cmd)
adds an anti-clockwise arc based on a center point, a radius/start angle point and an end angle point. Selection order is significant - center, start end.
Definition at line 898 of file CommandExtensionPack.cpp.
References TechDrawGui::_checkSel(), TechDrawGui::_getAngle(), TechDrawGui::_getVertexPoints(), TechDrawGui::_setLineAttributes(), exportCSG::center(), Gui::SelectionSingleton::clearSelection(), Gui::Command::commitCommand(), Gui::Command::getSelection(), TechDraw::DrawUtil::invertY(), FreeCADInit::Length, Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, and Path.Dressup.Utils::selection().
execDrawCosmCircle()
void execDrawCosmCircle (Gui::Command * cmd)
Definition at line 971 of file CommandExtensionPack.cpp.
References TechDrawGui::_checkSel(), TechDrawGui::_getVertexPoints(), TechDrawGui::_setLineAttributes(), exportCSG::center(), Gui::SelectionSingleton::clearSelection(), Gui::Command::commitCommand(), Gui::Command::getSelection(), FreeCADInit::Length, Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, and Path.Dressup.Utils::selection().
execDrawCosmCircle3Points()
void execDrawCosmCircle3Points (Gui::Command * cmd)
Definition at line 1034 of file CommandExtensionPack.cpp.
References TechDrawGui::_checkSel(), TechDrawGui::_circleCenter(), TechDrawGui::_getVertexPoints(), TechDrawGui::_setLineAttributes(), Gui::SelectionSingleton::clearSelection(), Gui::Command::commitCommand(), Gui::Command::getSelection(), FreeCADInit::Length, Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, and Path.Dressup.Utils::selection().
execExtendShortenLine()
void execExtendShortenLine (Gui::Command * cmd, bool extend)
Definition at line 1502 of file CommandExtensionPack.cpp.
References TechDrawGui::_checkSel(), TechDrawGui::_setLineAttributes(), activeDimAttributes, Gui::Command::commitCommand(), TechDraw::GENERIC, TechDraw::DrawUtil::getGeomTypeFromName(), dimAttributes::getLineStretch(), TechDraw::CenterLine::m_extendBy, Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, and Path.Dressup.Utils::selection().
execLineParallelPerpendicular()
void execLineParallelPerpendicular (Gui::Command * cmd, bool isParallel)
Definition at line 1225 of file CommandExtensionPack.cpp.
References TechDrawGui::_checkSel(), TechDrawGui::_setLineAttributes(), Gui::SelectionSingleton::clearSelection(), Gui::Command::commitCommand(), TechDraw::DrawUtil::getGeomTypeFromName(), TechDraw::DrawUtil::getIndexFromName(), Gui::Command::getSelection(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, Path.Dressup.Utils::selection(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
execThreadBoltBottom()
void execThreadBoltBottom (Gui::Command * cmd)
Definition at line 542 of file CommandExtensionPack.cpp.
References TechDrawGui::_checkSel(), TechDrawGui::_createThreadCircle(), Gui::SelectionSingleton::clearSelection(), Gui::Command::commitCommand(), Gui::Command::getSelection(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, and Path.Dressup.Utils::selection().
execThreadBoltSide()
void execThreadBoltSide (Gui::Command * cmd)
Definition at line 434 of file CommandExtensionPack.cpp.
References TechDrawGui::_checkSel(), TechDrawGui::_createThreadLines(), Gui::SelectionSingleton::clearSelection(), Gui::Command::commitCommand(), Gui::Command::getSelection(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, and Path.Dressup.Utils::selection().
execThreadHoleBottom()
void execThreadHoleBottom (Gui::Command * cmd)
Definition at line 488 of file CommandExtensionPack.cpp.
References TechDrawGui::_checkSel(), TechDrawGui::_createThreadCircle(), Gui::SelectionSingleton::clearSelection(), Gui::Command::commitCommand(), Gui::Command::getSelection(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, and Path.Dressup.Utils::selection().
execThreadHoleSide()
void execThreadHoleSide (Gui::Command * cmd)
Definition at line 380 of file CommandExtensionPack.cpp.
References TechDrawGui::_checkSel(), TechDrawGui::_createThreadLines(), Gui::SelectionSingleton::clearSelection(), Gui::Command::commitCommand(), Gui::Command::getSelection(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, and Path.Dressup.Utils::selection().