FreeCAD: MeshCore::AbstractSurfaceFit Class Reference
MeshCore::AbstractSurfaceFit Class Reference abstract
#include <Segmentation.h>
Public Member Functions
AbstractSurfaceFit ()=default
virtual ~AbstractSurfaceFit ()=default
AbstractSurfaceFit (const AbstractSurfaceFit &)=delete
AbstractSurfaceFit (AbstractSurfaceFit &&)=delete
AbstractSurfaceFit & operator= (const AbstractSurfaceFit &)=delete
AbstractSurfaceFit & operator= (AbstractSurfaceFit &&)=delete
virtual const char * GetType () const =0
virtual void Initialize (const MeshGeomFacet &)=0
virtual bool TestTriangle (const MeshGeomFacet &) const =0
virtual void AddTriangle (const MeshGeomFacet &)=0
virtual bool Done () const =0
virtual float Fit ()=0
virtual float GetDistanceToSurface (const Base::Vector3f &) const =0
virtual std::vector< float > Parameters () const =0
Detailed Description
Definition at line 137 of file Mesh/App/Core/Segmentation.h.
Constructor & Destructor Documentation
AbstractSurfaceFit() [1/3]
MeshCore::AbstractSurfaceFit::AbstractSurfaceFit () default
~AbstractSurfaceFit()
virtual MeshCore::AbstractSurfaceFit::~AbstractSurfaceFit () virtual default
AbstractSurfaceFit() [2/3]
MeshCore::AbstractSurfaceFit::AbstractSurfaceFit (const AbstractSurfaceFit &) delete
AbstractSurfaceFit() [3/3]
MeshCore::AbstractSurfaceFit::AbstractSurfaceFit (AbstractSurfaceFit &&) delete
Member Function Documentation
AddTriangle()
virtual void MeshCore::AbstractSurfaceFit::AddTriangle (const MeshGeomFacet &) pure virtual
Implemented in MeshCore::SphereSurfaceFit, MeshCore::CylinderSurfaceFit, and MeshCore::PlaneSurfaceFit.
Referenced by MeshCore::MeshDistanceGenericSurfaceFitSegment::AddFacet().
Done()
virtual bool MeshCore::AbstractSurfaceFit::Done () const pure virtual
Implemented in MeshCore::SphereSurfaceFit, MeshCore::CylinderSurfaceFit, and MeshCore::PlaneSurfaceFit.
Referenced by MeshCore::MeshDistanceGenericSurfaceFitSegment::TestFacet().
Fit()
virtual float MeshCore::AbstractSurfaceFit::Fit () pure virtual
Implemented in MeshCore::SphereSurfaceFit, MeshCore::CylinderSurfaceFit, and MeshCore::PlaneSurfaceFit.
Referenced by MeshCore::MeshDistanceGenericSurfaceFitSegment::TestFacet().
GetDistanceToSurface()
virtual float MeshCore::AbstractSurfaceFit::GetDistanceToSurface (const Base::Vector3f &) const pure virtual
Implemented in MeshCore::SphereSurfaceFit, MeshCore::CylinderSurfaceFit, and MeshCore::PlaneSurfaceFit.
Referenced by MeshCore::MeshDistanceGenericSurfaceFitSegment::TestFacet(), and MeshCore::MeshDistanceGenericSurfaceFitSegment::TestInitialFacet().
GetType()
virtual const char* MeshCore::AbstractSurfaceFit::GetType () const pure virtual
Implemented in MeshCore::SphereSurfaceFit, MeshCore::CylinderSurfaceFit, and MeshCore::PlaneSurfaceFit.
Initialize()
virtual void MeshCore::AbstractSurfaceFit::Initialize (const MeshGeomFacet &) pure virtual
Implemented in MeshCore::SphereSurfaceFit, MeshCore::CylinderSurfaceFit, and MeshCore::PlaneSurfaceFit.
Referenced by MeshCore::MeshDistanceGenericSurfaceFitSegment::Initialize().
operator=() [1/2]
AbstractSurfaceFit& MeshCore::AbstractSurfaceFit::operator= (AbstractSurfaceFit &&) delete
operator=() [2/2]
AbstractSurfaceFit& MeshCore::AbstractSurfaceFit::operator= (const AbstractSurfaceFit &) delete
Parameters()
virtual std::vector<float> MeshCore::AbstractSurfaceFit::Parameters () const pure virtual
Implemented in MeshCore::SphereSurfaceFit, MeshCore::CylinderSurfaceFit, and MeshCore::PlaneSurfaceFit.
Referenced by MeshCore::MeshDistanceGenericSurfaceFitSegment::Parameters().
TestTriangle()
virtual bool MeshCore::AbstractSurfaceFit::TestTriangle (const MeshGeomFacet &) const pure virtual
Implemented in MeshCore::SphereSurfaceFit, MeshCore::CylinderSurfaceFit, and MeshCore::PlaneSurfaceFit.
Referenced by MeshCore::MeshDistanceGenericSurfaceFitSegment::TestFacet(), and MeshCore::MeshDistanceGenericSurfaceFitSegment::TestInitialFacet().
The documentation for this class was generated from the following file:
Mesh/App/Core/Segmentation.h