FreeCAD: StartGui Namespace Reference
StartGui Namespace Reference
Classes
class FileCardView
class FirstStartWidget
class FlowLayout
The FlowLayout class Based on https://forum.qt.io/topic/109408/is-there-a-qt-layout-grid-that-can-dynamically- change-row-and-column-counts-to-best-fit-the-space.
class GeneralSettingsWidget
class Manipulator
class Module
class StartLauncher
class StartView
class ThemeSelectorWidget
A widget to allow selection of the UI theme (color scheme).
Enumerations
enum Theme { Theme::Classic, Theme::Light, Theme::Dark }
Functions
PyObject * initModule ()
Enumeration Type Documentation
Theme
enum StartGui::Theme strong
Enumerator
Classic
Light
Dark
Definition at line 37 of file ThemeSelectorWidget.h.
Function Documentation
initModule()
PyObject * StartGui::initModule ()
Definition at line 106 of file AppStartGui.cpp.
References Base::InterpreterSingleton::addModule(), and Base::Interpreter().
Referenced by PyMOD_INIT_FUNC().