FreeCAD: Drawing::DrawingOutput Class Reference
Drawing::DrawingOutput Class Reference
#include <DrawingExport.h>
Public Member Functions
TopoDS_Edge asCircle (const BRepAdaptor_Curve &) const
TopoDS_Edge asBSpline (const BRepAdaptor_Curve &, int maxDegree) const
Detailed Description
Definition at line 37 of file DrawingExport.h.
Member Function Documentation
asBSpline()
TopoDS_Edge DrawingOutput::asBSpline (const BRepAdaptor_Curve & c, int maxDegree) const
Definition at line 139 of file DrawingExport.cpp.
References SCL.SimpleDataTypes::c, and Handle().
asCircle()
TopoDS_Edge DrawingOutput::asCircle (const BRepAdaptor_Curve & c) const
Definition at line 68 of file DrawingExport.cpp.
References KDL::abs(), SCL.SimpleDataTypes::c, exportCSG::center(), DraftVecUtils::dist(), Handle(), SplineSurface::i, and buildPsets::p.
The documentation for this class was generated from the following files:
DrawingExport.h
DrawingExport.cpp