FreeCAD: BOPTools.JoinFeatures.FeatureConnect Class Reference
BOPTools.JoinFeatures.FeatureConnect Class Reference
Public Member Functions
def __init__ (self, obj)
def execute (self, selfobj)
Public Attributes
Type
Detailed Description
The PartJoinFeature object.
Definition at line 113 of file BOPTools/JoinFeatures.py.
Constructor & Destructor Documentation
__init__()
def BOPTools.JoinFeatures.FeatureConnect.__init__ (self, obj)
Definition at line 116 of file BOPTools/JoinFeatures.py.
References BOPTools.JoinFeatures.getParamRefine().
Member Function Documentation
execute()
def BOPTools.JoinFeatures.FeatureConnect.execute (self, selfobj)
Definition at line 128 of file BOPTools/JoinFeatures.py.
Referenced by src.Mod.PartDesign.Scripts.Spring.MySpring.onChanged(), src.Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid.onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped.onChanged(), src.Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt.onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder.onChanged(), and FeaturePython.DistanceBolt.onChanged().
Member Data Documentation
Type
BOPTools.JoinFeatures.FeatureConnect.Type
Definition at line 126 of file BOPTools/JoinFeatures.py.
The documentation for this class was generated from the following file:
BOPTools/JoinFeatures.py