FreeCAD: ifc4.ifceventtime Class Reference
ifc4.ifceventtime Class Reference
Public Member Functions
def __init__ (self, inherited0__name, inherited1__dataorigin, inherited2__userdefineddataorigin, actualdate, earlydate, latedate, scheduledate)
def actualdate ()
def earlydate ()
def latedate ()
def scheduledate ()
Public Member Functions inherited from ifc4.ifcschedulingtime
def __init__ (self, name, dataorigin, userdefineddataorigin)
def name ()
def dataorigin ()
def userdefineddataorigin ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
actualdate
earlydate
latedate
scheduledate
Public Attributes inherited from ifc4.ifcschedulingtime
name
dataorigin
userdefineddataorigin
Detailed Description
Entity ifceventtime definition.
:param actualdate
:type actualdate:ifcdatetime
:param earlydate
:type earlydate:ifcdatetime
:param latedate
:type latedate:ifcdatetime
:param scheduledate
:type scheduledate:ifcdatetime
Definition at line 6478 of file ifc4.py.
Constructor & Destructor Documentation
__init__()
def ifc4.ifceventtime.__init__ (self, inherited0__name, inherited1__dataorigin, inherited2__userdefineddataorigin, actualdate, earlydate, latedate, scheduledate)
Definition at line 6493 of file ifc4.py.
Member Function Documentation
actualdate()
def ifc4.ifceventtime.actualdate ()
Definition at line 6501 of file ifc4.py.
References ifc4.ifceventtime._actualdate, ifc4.ifceventtime.actualdate, and SCL.TypeChecker.check_type().
earlydate()
def ifc4.ifceventtime.earlydate ()
Definition at line 6515 of file ifc4.py.
References ifc4.ifceventtime._earlydate, SCL.TypeChecker.check_type(), and ifc4.ifceventtime.earlydate.
latedate()
def ifc4.ifceventtime.latedate ()
Definition at line 6529 of file ifc4.py.
References ifc4.ifceventtime._latedate, SCL.TypeChecker.check_type(), and ifc4.ifceventtime.latedate.
scheduledate()
def ifc4.ifceventtime.scheduledate ()
Definition at line 6543 of file ifc4.py.
References ifc4.ifceventtime._scheduledate, SCL.TypeChecker.check_type(), and ifc4.ifceventtime.scheduledate.
Member Data Documentation
actualdate
ifc4.ifceventtime.actualdate
Definition at line 6495 of file ifc4.py.
Referenced by ifc4.ifceventtime.actualdate().
earlydate
ifc4.ifceventtime.earlydate
Definition at line 6496 of file ifc4.py.
Referenced by ifc4.ifceventtime.earlydate().
latedate
ifc4.ifceventtime.latedate
Definition at line 6497 of file ifc4.py.
Referenced by ifc4.ifceventtime.latedate().
scheduledate
ifc4.ifceventtime.scheduledate
Definition at line 6498 of file ifc4.py.
Referenced by ifc4.ifceventtime.scheduledate().
The documentation for this class was generated from the following file:
ifc4.py