FreeCAD: ifc2x3.ifcmateriallayersetusage Class Reference
ifc2x3.ifcmateriallayersetusage Class Reference
Public Member Functions
def __init__ (self, forlayerset, layersetdirection, directionsense, offsetfromreferenceline)
def forlayerset ()
def layersetdirection ()
def directionsense ()
def offsetfromreferenceline ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
forlayerset
layersetdirection
directionsense
offsetfromreferenceline
Detailed Description
Entity ifcmateriallayersetusage definition.
:param forlayerset
:type forlayerset:ifcmateriallayerset
:param layersetdirection
:type layersetdirection:ifclayersetdirectionenum
:param directionsense
:type directionsense:ifcdirectionsenseenum
:param offsetfromreferenceline
:type offsetfromreferenceline:ifclengthmeasure
Definition at line 12902 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcmateriallayersetusage.__init__ (self, forlayerset, layersetdirection, directionsense, offsetfromreferenceline)
Definition at line 12917 of file ifc2x3.py.
Member Function Documentation
directionsense()
def ifc2x3.ifcmateriallayersetusage.directionsense ()
Definition at line 12952 of file ifc2x3.py.
References ifc2x3.ifcmateriallayersetusage._directionsense, SCL.TypeChecker.check_type(), and ifc2x3.ifcmateriallayersetusage.directionsense.
forlayerset()
def ifc2x3.ifcmateriallayersetusage.forlayerset ()
Definition at line 12924 of file ifc2x3.py.
References ifc2x3.ifcmateriallayersetusage._forlayerset, SCL.TypeChecker.check_type(), and ifc2x3.ifcmateriallayersetusage.forlayerset.
layersetdirection()
def ifc2x3.ifcmateriallayersetusage.layersetdirection ()
Definition at line 12938 of file ifc2x3.py.
References ifc2x3.ifcmateriallayersetusage._layersetdirection, SCL.TypeChecker.check_type(), and ifc2x3.ifcmateriallayersetusage.layersetdirection.
offsetfromreferenceline()
def ifc2x3.ifcmateriallayersetusage.offsetfromreferenceline ()
Definition at line 12966 of file ifc2x3.py.
References ifc2x3.ifcmateriallayersetusage._offsetfromreferenceline, SCL.TypeChecker.check_type(), and ifc2x3.ifcmateriallayersetusage.offsetfromreferenceline.
Member Data Documentation
directionsense
ifc2x3.ifcmateriallayersetusage.directionsense
Definition at line 12920 of file ifc2x3.py.
Referenced by ifc2x3.ifcmateriallayersetusage.directionsense().
forlayerset
ifc2x3.ifcmateriallayersetusage.forlayerset
Definition at line 12918 of file ifc2x3.py.
Referenced by ifc2x3.ifcmateriallayersetusage.forlayerset().
layersetdirection
ifc2x3.ifcmateriallayersetusage.layersetdirection
Definition at line 12919 of file ifc2x3.py.
Referenced by ifc2x3.ifcmateriallayersetusage.layersetdirection().
offsetfromreferenceline
ifc2x3.ifcmateriallayersetusage.offsetfromreferenceline
Definition at line 12921 of file ifc2x3.py.
Referenced by ifc2x3.ifcmateriallayersetusage.offsetfromreferenceline().
The documentation for this class was generated from the following file:
ifc2x3.py