FreeCAD: Gui::DockWnd::ReportHighlighter Class Reference
Gui::DockWnd::ReportHighlighter Class Reference
#include <ReportView.h>
Public Types
enum Paragraph {
Message = 0, Warning = 1, Error = 2, LogText = 3,
Critical = 4
}
Public Member Functions
ReportHighlighter (QTextEdit *)
~ReportHighlighter () override
void highlightBlock (const QString &text) override
void setParagraphType (Paragraph)
void setTextColor (const QColor &col)
void setLogColor (const QColor &col)
void setWarningColor (const QColor &col)
void setErrorColor (const QColor &col)
void setCriticalColor (const QColor &col)
Detailed Description
Syntax highlighter to write log or normal messages, warnings and errors in different colors.
Author
Werner Mayer
Definition at line 69 of file ReportView.h.
Member Enumeration Documentation
Paragraph
enum Gui::DockWnd::ReportHighlighter::Paragraph
Enumerator
Message
normal text
Warning
Warning
Error
Error text
LogText
Log text
Critical
critical text
Definition at line 72 of file ReportView.h.
Constructor & Destructor Documentation
ReportHighlighter()
ReportHighlighter::ReportHighlighter (QTextEdit * edit) explicit
Definition at line 124 of file ReportView.cpp.
References Message().
~ReportHighlighter()
ReportHighlighter::~ReportHighlighter () override default
Member Function Documentation
highlightBlock()
void ReportHighlighter::highlightBlock (const QString & text) override
Parses the given text and highlight it in the right colors.
Definition at line 136 of file ReportView.cpp.
References SCL.SimpleDataTypes::b, Critical, Error, LogText, Message, and Warning.
setCriticalColor()
void ReportHighlighter::setCriticalColor (const QColor & col)
Sets the text color to col.
Definition at line 204 of file ReportView.cpp.
setErrorColor()
void ReportHighlighter::setErrorColor (const QColor & col)
Sets the color for error messages to col.
Definition at line 199 of file ReportView.cpp.
Referenced by Gui::DockWnd::ReportOutput::OnChange().
setLogColor()
void ReportHighlighter::setLogColor (const QColor & col)
Sets the color for log messages to col.
Definition at line 189 of file ReportView.cpp.
Referenced by Gui::DockWnd::ReportOutput::OnChange().
setParagraphType()
void ReportHighlighter::setParagraphType (ReportHighlighter::Paragraph t)
Sets the current paragraph type used in ReportOutput
See also
ReportOutput::Message
ReportOutput::Warning
ReportOutput::Error
ReportOutput::Critical
Definition at line 179 of file ReportView.cpp.
References InitGui::t.
Referenced by Gui::DockWnd::ReportOutput::customEvent().
setTextColor()
void ReportHighlighter::setTextColor (const QColor & col)
Sets the text color to col.
Definition at line 184 of file ReportView.cpp.
Referenced by Gui::DockWnd::ReportOutput::OnChange().
setWarningColor()
void ReportHighlighter::setWarningColor (const QColor & col)
Sets the color for warnings to col.
Definition at line 194 of file ReportView.cpp.
Referenced by Gui::DockWnd::ReportOutput::OnChange().
The documentation for this class was generated from the following files:
ReportView.h
ReportView.cpp