FreeCAD: PartDesignGui::ComboLinks Class Reference
PartDesignGui::ComboLinks Class Reference
The ComboLinks class is a helper class that binds to a combo box and provides an interface to add links, retrieve links and select items by link value.
#include <TaskTransformedParameters.h>
Public Member Functions
ComboLinks (QComboBox &combo)
ComboLinks constructor.
ComboLinks ()=default
void setCombo (QComboBox &combo)
int addLink (const App::PropertyLinkSub &lnk, QString const &itemText)
addLink adds an item to the combo. Doesn't check for duplicates.
int addLink (App::DocumentObject *linkObj, std::string const &linkSubname, QString const &itemText)
void clear ()
App::PropertyLinkSub & getLink (int index) const
App::PropertyLinkSub & getCurrentLink () const
getCurrentLink
int setCurrentLink (const App::PropertyLinkSub &lnk)
setCurrentLink selects the item with the link that matches the argument. If there is no such link in the list, -1 is returned and selected item is not changed. Signals from combo are blocked in this function.
QComboBox & combo () const
~ComboLinks ()
Detailed Description
The ComboLinks class is a helper class that binds to a combo box and provides an interface to add links, retrieve links and select items by link value.
Definition at line 63 of file TaskTransformedParameters.h.
Constructor & Destructor Documentation
ComboLinks() [1/2]
ComboLinks::ComboLinks (QComboBox & combo) explicit
ComboLinks constructor.
Parameters
combo. It will be cleared as soon as it is bound. Don't add or remove items from the combo directly, otherwise internal tracking list will go out of sync, and crashes may result.
Definition at line 650 of file TaskTransformedParameters.cpp.
ComboLinks() [2/2]
PartDesignGui::ComboLinks::ComboLinks () default
~ComboLinks()
PartDesignGui::ComboLinks::~ComboLinks () inline
Definition at line 118 of file TaskTransformedParameters.h.
References clear().
Member Function Documentation
addLink() [1/2]
int ComboLinks::addLink (App::DocumentObject * linkObj, std::string const & linkSubname, QString const & itemText)
Definition at line 671 of file TaskTransformedParameters.cpp.
References App::DocumentObject::getDocument(), App::PropertyLinkSub::getValue(), and App::PropertyLinkSub::setValue().
addLink() [2/2]
int ComboLinks::addLink (const App::PropertyLinkSub & lnk, QString const & itemText)
addLink adds an item to the combo. Doesn't check for duplicates.
Parameters
lnk can be a link to NULL, which is usually used for special item "Select Reference"
itemText
Returns
Definition at line 656 of file TaskTransformedParameters.cpp.
References App::DocumentObject::getDocument(), App::PropertyLinkSub::getValue(), and App::PropertyLinkSub::Paste().
Referenced by PartDesignGui::TaskTransformedParameters::fillAxisCombo(), and PartDesignGui::TaskTransformedParameters::fillPlanesCombo().
clear()
void ComboLinks::clear ()
Definition at line 688 of file TaskTransformedParameters.cpp.
References SplineSurface::i.
Referenced by src.Mod.Test.Document.DocumentObserverCases.Observer::__init__(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::__init__(), PartDesignGui::TaskTransformedParameters::fillAxisCombo(), PartDesignGui::TaskTransformedParameters::fillPlanesCombo(), and ~ComboLinks().
combo()
QComboBox& PartDesignGui::ComboLinks::combo () const inline
Definition at line 112 of file TaskTransformedParameters.h.
Referenced by setCombo().
getCurrentLink()
App::PropertyLinkSub & ComboLinks::getCurrentLink () const
getCurrentLink
Returns
the link corresponding to the selected item. May be null link, which is usually used to indicate a "Select reference..." special item. Otherwise, the link is automatically tested for validity (oif an object doesn't exist in the document, an exception will be thrown.)
Definition at line 709 of file TaskTransformedParameters.cpp.
References getLink().
getLink()
App::PropertyLinkSub & ComboLinks::getLink (int index) const
Definition at line 698 of file TaskTransformedParameters.cpp.
References getValue(), and App::Document::isIn().
Referenced by getCurrentLink().
setCombo()
void PartDesignGui::ComboLinks::setCombo (QComboBox & combo) inline
Definition at line 75 of file TaskTransformedParameters.h.
References combo().
setCurrentLink()
int ComboLinks::setCurrentLink (const App::PropertyLinkSub & lnk)
setCurrentLink selects the item with the link that matches the argument. If there is no such link in the list, -1 is returned and selected item is not changed. Signals from combo are blocked in this function.
Parameters
lnk
Returns
the index of an item that was selected, -1 if link is not in the list yet.
Definition at line 715 of file TaskTransformedParameters.cpp.
References App::PropertyLinkSub::getSubValues(), App::PropertyLinkSub::getValue(), and SplineSurface::i.
The documentation for this class was generated from the following files:
TaskTransformedParameters.h
TaskTransformedParameters.cpp