FreeCAD: Sketcher::ExternalGeometryExtension Class Reference
Sketcher::ExternalGeometryExtension Class Reference
#include <ExternalGeometryExtension.h>
Public Types
enum Flag {
Defining = 0, Frozen = 1, Detached = 2, Missing = 3,
Sync = 4, NumFlags
}
Public Member Functions
ExternalGeometryExtension ()=default
~ExternalGeometryExtension () override=default
std::unique_ptr< Part::GeometryExtension > copy () const override
PyObject * getPyObject () override
bool testFlag (int flag) const override
void setFlag (int flag, bool v=true) override
unsigned long getFlags () const override
void setFlags (unsigned long flags) override
bool isClear () const override
size_t flagSize () const override
const std::string & getRef () const override
void setRef (const std::string &ref) override
int getRefIndex () const override
void setRefIndex (int index) override
Public Member Functions inherited from Part::GeometryMigrationPersistenceExtension
virtual void postSave (Base::Writer &) const
Public Member Functions inherited from Part::GeometryPersistenceExtension
~GeometryPersistenceExtension () override=default
void Save (Base::Writer &) const
void Restore (Base::XMLReader &)
bool isSame (const GeometryPersistenceExtension &other) const
Public Member Functions inherited from Part::GeometryExtension
~GeometryExtension () override=default
PyObject * copyPyObject () const
void setName (const std::string &str)
const std::string & getName () const
virtual void notifyAttachment (Part::Geometry *)
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static bool getFlagsFromName (std::string str, ExternalGeometryExtension::Flag &flag)
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Public Attributes
constexpr static std::array< const char *, NumFlags > flag2str
Protected Member Functions
void copyAttributes (Part::GeometryExtension *cpy) const override
void restoreAttributes (Base::XMLReader &reader) override
void saveAttributes (Base::Writer &writer) const override
void preSave (Base::Writer &writer) const override
Protected Member Functions inherited from Part::GeometryExtension
GeometryExtension ()
GeometryExtension (const GeometryExtension &obj)=default
GeometryExtension & operator= (const GeometryExtension &obj)=default
Additional Inherited Members
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 86 of file ExternalGeometryExtension.h.
Member Enumeration Documentation
Flag
enum Sketcher::ExternalGeometryExtension::Flag
Enumerator
Defining
Frozen
Detached
Missing
Sync
NumFlags
Definition at line 94 of file ExternalGeometryExtension.h.
Constructor & Destructor Documentation
ExternalGeometryExtension()
Sketcher::ExternalGeometryExtension::ExternalGeometryExtension () default
Referenced by getPyObject().
~ExternalGeometryExtension()
Sketcher::ExternalGeometryExtension::~ExternalGeometryExtension () override default
Member Function Documentation
copy()
std::unique_ptr< Part::GeometryExtension > ExternalGeometryExtension::copy () const override virtual
Implements Part::GeometryExtension.
Definition at line 82 of file ExternalGeometryExtension.cpp.
References copyAttributes(), and Path.Post.scripts.opensbp_post::move().
copyAttributes()
void ExternalGeometryExtension::copyAttributes (Part::GeometryExtension * cpy) const override protected virtual
Reimplemented from Part::GeometryExtension.
Definition at line 41 of file ExternalGeometryExtension.cpp.
References Part::GeometryExtension::copyAttributes().
Referenced by copy().
flagSize()
size_t Sketcher::ExternalGeometryExtension::flagSize () const inline override virtual
Implements Sketcher::ISketchExternalGeometryExtension.
Definition at line 147 of file ExternalGeometryExtension.h.
getFlags()
unsigned long Sketcher::ExternalGeometryExtension::getFlags () const inline override virtual
Implements Sketcher::ISketchExternalGeometryExtension.
Definition at line 130 of file ExternalGeometryExtension.h.
getFlagsFromName()
bool ExternalGeometryExtension::getFlagsFromName (std::string str, ExternalGeometryExtension::Flag & flag) static
Definition at line 100 of file ExternalGeometryExtension.cpp.
References Sketcher::end, flag2str, RobotExample::pos, Path.Post.scripts.refactored_centroid_post::str, and toolbit-attributes::val.
getPyObject()
PyObject * ExternalGeometryExtension::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Implements Part::GeometryExtension.
Definition at line 95 of file ExternalGeometryExtension.cpp.
References ExternalGeometryExtension().
getRef()
const std::string& Sketcher::ExternalGeometryExtension::getRef () const inline override virtual
Implements Sketcher::ISketchExternalGeometryExtension.
Definition at line 152 of file ExternalGeometryExtension.h.
getRefIndex()
int Sketcher::ExternalGeometryExtension::getRefIndex () const inline override virtual
Implements Sketcher::ISketchExternalGeometryExtension.
Definition at line 162 of file ExternalGeometryExtension.h.
isClear()
bool Sketcher::ExternalGeometryExtension::isClear () const inline override virtual
Implements Sketcher::ISketchExternalGeometryExtension.
Definition at line 142 of file ExternalGeometryExtension.h.
preSave()
void ExternalGeometryExtension::preSave (Base::Writer & writer) const override protected virtual
Reimplemented from Part::GeometryMigrationPersistenceExtension.
Definition at line 69 of file ExternalGeometryExtension.cpp.
References Base::Persistence::encodeAttribute(), and Base::Writer::Stream().
restoreAttributes()
void ExternalGeometryExtension::restoreAttributes (Base::XMLReader & reader) override protected virtual
Reimplemented from Part::GeometryPersistenceExtension.
Definition at line 50 of file ExternalGeometryExtension.cpp.
References TechDrawTools.TaskFillTemplateFields::reader, and Part::GeometryPersistenceExtension::restoreAttributes().
saveAttributes()
void ExternalGeometryExtension::saveAttributes (Base::Writer & writer) const override protected virtual
Reimplemented from Part::GeometryPersistenceExtension.
Definition at line 59 of file ExternalGeometryExtension.cpp.
References Base::Persistence::encodeAttribute(), Part::GeometryPersistenceExtension::saveAttributes(), and Base::Writer::Stream().
setFlag()
void Sketcher::ExternalGeometryExtension::setFlag (int flag, bool v = true) inline override virtual
Implements Sketcher::ISketchExternalGeometryExtension.
Definition at line 125 of file ExternalGeometryExtension.h.
setFlags()
void Sketcher::ExternalGeometryExtension::setFlags (unsigned long flags) inline override virtual
Implements Sketcher::ISketchExternalGeometryExtension.
Definition at line 135 of file ExternalGeometryExtension.h.
setRef()
void Sketcher::ExternalGeometryExtension::setRef (const std::string & ref) inline override virtual
Implements Sketcher::ISketchExternalGeometryExtension.
Definition at line 157 of file ExternalGeometryExtension.h.
setRefIndex()
void Sketcher::ExternalGeometryExtension::setRefIndex (int index) inline override virtual
Implements Sketcher::ISketchExternalGeometryExtension.
Definition at line 167 of file ExternalGeometryExtension.h.
testFlag()
bool Sketcher::ExternalGeometryExtension::testFlag (int flag) const inline override virtual
Implements Sketcher::ISketchExternalGeometryExtension.
Definition at line 120 of file ExternalGeometryExtension.h.
Member Data Documentation
flag2str
constexpr std::array< const char *, ExternalGeometryExtension::NumFlags > ExternalGeometryExtension::flag2str static constexpr
Initial value:
{
        {"Defining", "Frozen", "Detached", "Missing", "Sync"}}
Definition at line 106 of file ExternalGeometryExtension.h.
Referenced by getFlagsFromName().
The documentation for this class was generated from the following files:
ExternalGeometryExtension.h
ExternalGeometryExtension.cpp