FreeCAD: ifc2x3.ifcsurfacestylelighting Class Reference
ifc2x3.ifcsurfacestylelighting Class Reference
Public Member Functions
def __init__ (self, diffusetransmissioncolour, diffusereflectioncolour, transmissioncolour, reflectancecolour)
def diffusetransmissioncolour ()
def diffusereflectioncolour ()
def transmissioncolour ()
def reflectancecolour ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
diffusetransmissioncolour
diffusereflectioncolour
transmissioncolour
reflectancecolour
Detailed Description
Entity ifcsurfacestylelighting definition.
:param diffusetransmissioncolour
:type diffusetransmissioncolour:ifccolourrgb
:param diffusereflectioncolour
:type diffusereflectioncolour:ifccolourrgb
:param transmissioncolour
:type transmissioncolour:ifccolourrgb
:param reflectancecolour
:type reflectancecolour:ifccolourrgb
Definition at line 20539 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcsurfacestylelighting.__init__ (self, diffusetransmissioncolour, diffusereflectioncolour, transmissioncolour, reflectancecolour)
Definition at line 20554 of file ifc2x3.py.
Member Function Documentation
diffusereflectioncolour()
def ifc2x3.ifcsurfacestylelighting.diffusereflectioncolour ()
Definition at line 20575 of file ifc2x3.py.
References ifc2x3.ifcsurfacestylelighting._diffusereflectioncolour, SCL.TypeChecker.check_type(), and ifc2x3.ifcsurfacestylelighting.diffusereflectioncolour.
diffusetransmissioncolour()
def ifc2x3.ifcsurfacestylelighting.diffusetransmissioncolour ()
Definition at line 20561 of file ifc2x3.py.
References ifc2x3.ifcsurfacestylelighting._diffusetransmissioncolour, SCL.TypeChecker.check_type(), and ifc2x3.ifcsurfacestylelighting.diffusetransmissioncolour.
reflectancecolour()
def ifc2x3.ifcsurfacestylelighting.reflectancecolour ()
Definition at line 20603 of file ifc2x3.py.
References ifc2x3.ifcsurfacestylelighting._reflectancecolour, SCL.TypeChecker.check_type(), and ifc2x3.ifcsurfacestylelighting.reflectancecolour.
transmissioncolour()
def ifc2x3.ifcsurfacestylelighting.transmissioncolour ()
Definition at line 20589 of file ifc2x3.py.
References ifc2x3.ifcsurfacestylelighting._transmissioncolour, SCL.TypeChecker.check_type(), and ifc2x3.ifcsurfacestylelighting.transmissioncolour.
Member Data Documentation
diffusereflectioncolour
ifc2x3.ifcsurfacestylelighting.diffusereflectioncolour
Definition at line 20556 of file ifc2x3.py.
Referenced by ifc2x3.ifcsurfacestylelighting.diffusereflectioncolour().
diffusetransmissioncolour
ifc2x3.ifcsurfacestylelighting.diffusetransmissioncolour
Definition at line 20555 of file ifc2x3.py.
Referenced by ifc2x3.ifcsurfacestylelighting.diffusetransmissioncolour().
reflectancecolour
ifc2x3.ifcsurfacestylelighting.reflectancecolour
Definition at line 20558 of file ifc2x3.py.
Referenced by ifc2x3.ifcsurfacestylelighting.reflectancecolour().
transmissioncolour
ifc2x3.ifcsurfacestylelighting.transmissioncolour
Definition at line 20557 of file ifc2x3.py.
Referenced by ifc2x3.ifcsurfacestylelighting.transmissioncolour().
The documentation for this class was generated from the following file:
ifc2x3.py