FreeCAD: Gui::Dialog::DlgCustomToolbars Class Reference
Gui::Dialog::DlgCustomToolbars Class Reference
#include <DlgToolbarsImp.h>
Public Member Functions
void activateWorkbenchBox (int index)
Public Member Functions inherited from Gui::Dialog::CustomizeActionPage
CustomizeActionPage (QWidget *parent=nullptr)
~CustomizeActionPage () override
Protected Types
enum Type { Toolbar, Toolboxbar }
Protected Slots
void onAddMacroAction (const QByteArray &) override
void onRemoveMacroAction (const QByteArray &) override
void onModifyMacroAction (const QByteArray &) override
Protected Slots inherited from Gui::Dialog::CustomizeActionPage
virtual void onAddMacroAction (const QByteArray &)=0
virtual void onRemoveMacroAction (const QByteArray &)=0
virtual void onModifyMacroAction (const QByteArray &)=0
Protected Member Functions
DlgCustomToolbars (Type, QWidget *parent=nullptr)
~DlgCustomToolbars () override
void setupConnections ()
void onWorkbenchBoxActivated (int index)
void onMoveActionRightButtonClicked ()
void onMoveActionLeftButtonClicked ()
void onMoveActionUpButtonClicked ()
void onMoveActionDownButtonClicked ()
void onNewButtonClicked ()
void onRenameButtonClicked ()
void onDeleteButtonClicked ()
void changeEvent (QEvent *e) override
void hideEvent (QHideEvent *event) override
virtual void addCustomToolbar (const QString &)
virtual void removeCustomToolbar (const QString &)
virtual void renameCustomToolbar (const QString &, const QString &)
virtual void addCustomCommand (const QString &, const QByteArray &)
virtual void removeCustomCommand (const QString &, const QByteArray &)
virtual void moveUpCustomCommand (const QString &, const QByteArray &)
virtual void moveDownCustomCommand (const QString &, const QByteArray &)
void onActivateCategoryBox ()
Protected Member Functions inherited from Gui::Dialog::CustomizeActionPage
bool event (QEvent *e) override
Protected Attributes
std::unique_ptr< Ui_DlgCustomToolbars > ui
Detailed Description
This class implements the creation of user defined toolbars. In the left panel are shown all command groups with their command objects. If any changeable toolbar was created in the left panel are shown all commands of the currently edited toolbar, otherwise it is empty. All changes to a toolbar is done immediately.
Author
Werner Mayer
Definition at line 45 of file DlgToolbarsImp.h.
Member Enumeration Documentation
Type
enum Gui::Dialog::DlgCustomToolbars::Type protected
Enumerator
Toolbar
Toolboxbar
Definition at line 50 of file DlgToolbarsImp.h.
Constructor & Destructor Documentation
DlgCustomToolbars()
DlgCustomToolbars::DlgCustomToolbars (DlgCustomToolbars::Type t, QWidget * parent = nullptr) explicit protected
Constructs a DlgCustomToolbars which is a child of 'parent', with the name 'name' and widget flags set to 'f'
The dialog will by default be modeless, unless you set 'modal' to true to construct a modal dialog.
Definition at line 59 of file DlgToolbarsImp.cpp.
References Gui::WorkbenchManager::active(), Gui::BitmapFactory(), Gui::Dialog::DlgCustomKeyboardImp::initCommandWidgets(), Gui::WorkbenchManager::instance(), Gui::Application::Instance, App::ExpressionParser::labels, onWorkbenchBoxActivated(), setupConnections(), ui, src.Mod.PartDesign.fcgear.svggear::w, Gui::Application::workbenches(), Gui::Application::workbenchIcon(), and Gui::Application::workbenchMenuText().
~DlgCustomToolbars()
DlgCustomToolbars::~DlgCustomToolbars () override protected default
Destroys the object and frees any allocated resources
Member Function Documentation
activateWorkbenchBox()
void DlgCustomToolbars::activateWorkbenchBox (int index)
Definition at line 176 of file DlgToolbarsImp.cpp.
References onWorkbenchBoxActivated().
addCustomCommand()
void DlgCustomToolbars::addCustomCommand (const QString & , const QByteArray &) protected virtual
Reimplemented in Gui::Dialog::DlgCustomToolbarsImp.
Definition at line 151 of file DlgToolbarsImp.cpp.
Referenced by onMoveActionRightButtonClicked().
addCustomToolbar()
void DlgCustomToolbars::addCustomToolbar (const QString &) protected virtual
Reimplemented in Gui::Dialog::DlgCustomToolbarsImp.
Definition at line 142 of file DlgToolbarsImp.cpp.
Referenced by onNewButtonClicked().
changeEvent()
void DlgCustomToolbars::changeEvent (QEvent * e) override protected virtual
Implements Gui::Dialog::CustomizeActionPage.
Reimplemented in Gui::Dialog::DlgCustomToolBoxbarsImp, and Gui::Dialog::DlgCustomToolbarsImp.
Definition at line 562 of file DlgToolbarsImp.cpp.
References Gui::Application::commandManager(), src.Mod.AddonManager.NetworkManager::count, SCL.SimpleDataTypes::e, Gui::CommandManager::getGroupCommands(), SplineSurface::i, Gui::Application::Instance, and ui.
Referenced by Gui::Dialog::DlgCustomToolbarsImp::changeEvent(), and Gui::Dialog::DlgCustomToolBoxbarsImp::changeEvent().
hideEvent()
void DlgCustomToolbars::hideEvent (QHideEvent * event) override protected
Definition at line 163 of file DlgToolbarsImp.cpp.
References Gui::Dialog::CustomizeActionPage::event(), and ui.
moveDownCustomCommand()
void DlgCustomToolbars::moveDownCustomCommand (const QString & , const QByteArray &) protected virtual
Reimplemented in Gui::Dialog::DlgCustomToolbarsImp.
Definition at line 160 of file DlgToolbarsImp.cpp.
Referenced by onMoveActionDownButtonClicked().
moveUpCustomCommand()
void DlgCustomToolbars::moveUpCustomCommand (const QString & , const QByteArray &) protected virtual
Reimplemented in Gui::Dialog::DlgCustomToolbarsImp.
Definition at line 157 of file DlgToolbarsImp.cpp.
Referenced by onMoveActionUpButtonClicked().
onActivateCategoryBox()
void DlgCustomToolbars::onActivateCategoryBox () protected
Definition at line 172 of file DlgToolbarsImp.cpp.
onAddMacroAction
void DlgCustomToolbars::onAddMacroAction (const QByteArray &) override protected slot
Definition at line 530 of file DlgToolbarsImp.cpp.
onDeleteButtonClicked()
void DlgCustomToolbars::onDeleteButtonClicked () protected
Definition at line 475 of file DlgToolbarsImp.cpp.
References removeCustomToolbar(), and ui.
Referenced by setupConnections().
onModifyMacroAction
void DlgCustomToolbars::onModifyMacroAction (const QByteArray & macro) override protected slot
Definition at line 536 of file DlgToolbarsImp.cpp.
References Gui::BitmapFactory(), Gui::Application::commandManager(), Gui::Action::commandMenuText(), Gui::Action::commandToolTip(), Gui::CommandManager::getCommandByName(), Gui::CommandBase::getPixmap(), toolbit-attributes::group, SplineSurface::i, Gui::Application::Instance, and ui.
onMoveActionDownButtonClicked()
void DlgCustomToolbars::onMoveActionDownButtonClicked () protected
Moves down an action
Definition at line 401 of file DlgToolbarsImp.cpp.
References SplineSurface::i, moveDownCustomCommand(), Init::parent, and ui.
Referenced by setupConnections().
onMoveActionLeftButtonClicked()
void DlgCustomToolbars::onMoveActionLeftButtonClicked () protected
Removes an action
Definition at line 329 of file DlgToolbarsImp.cpp.
References SplineSurface::i, Init::parent, removeCustomCommand(), and ui.
Referenced by setupConnections().
onMoveActionRightButtonClicked()
void DlgCustomToolbars::onMoveActionRightButtonClicked () protected
Adds a new action
Definition at line 301 of file DlgToolbarsImp.cpp.
References addCustomCommand(), and ui.
Referenced by setupConnections().
onMoveActionUpButtonClicked()
void DlgCustomToolbars::onMoveActionUpButtonClicked () protected
Moves up an action
Definition at line 363 of file DlgToolbarsImp.cpp.
References SplineSurface::i, moveUpCustomCommand(), Init::parent, and ui.
Referenced by setupConnections().
onNewButtonClicked()
void DlgCustomToolbars::onNewButtonClicked () protected
Definition at line 438 of file DlgToolbarsImp.cpp.
References addCustomToolbar(), importers.exportIFC::getText(), SplineSurface::i, geoff_geometry::Normal(), ui, and Path.Log::warning().
Referenced by setupConnections().
onRemoveMacroAction
void DlgCustomToolbars::onRemoveMacroAction (const QByteArray &) override protected slot
Definition at line 533 of file DlgToolbarsImp.cpp.
onRenameButtonClicked()
void DlgCustomToolbars::onRenameButtonClicked () protected
Definition at line 490 of file DlgToolbarsImp.cpp.
References importers.exportIFC::getText(), SplineSurface::i, geoff_geometry::Normal(), renameCustomToolbar(), ui, and Path.Log::warning().
Referenced by setupConnections().
onWorkbenchBoxActivated()
void DlgCustomToolbars::onWorkbenchBoxActivated (int index) protected
Definition at line 180 of file DlgToolbarsImp.cpp.
References ui.
Referenced by activateWorkbenchBox(), DlgCustomToolbars(), and setupConnections().
removeCustomCommand()
void DlgCustomToolbars::removeCustomCommand (const QString & , const QByteArray &) protected virtual
Reimplemented in Gui::Dialog::DlgCustomToolbarsImp.
Definition at line 154 of file DlgToolbarsImp.cpp.
Referenced by onMoveActionLeftButtonClicked().
removeCustomToolbar()
void DlgCustomToolbars::removeCustomToolbar (const QString &) protected virtual
Reimplemented in Gui::Dialog::DlgCustomToolbarsImp.
Definition at line 145 of file DlgToolbarsImp.cpp.
Referenced by onDeleteButtonClicked().
renameCustomToolbar()
void DlgCustomToolbars::renameCustomToolbar (const QString & , const QString &) protected virtual
Reimplemented in Gui::Dialog::DlgCustomToolbarsImp.
Definition at line 148 of file DlgToolbarsImp.cpp.
Referenced by onRenameButtonClicked().
setupConnections()
void DlgCustomToolbars::setupConnections () protected
Definition at line 120 of file DlgToolbarsImp.cpp.
References draftgeoutils.intersections::connect(), onDeleteButtonClicked(), onMoveActionDownButtonClicked(), onMoveActionLeftButtonClicked(), onMoveActionRightButtonClicked(), onMoveActionUpButtonClicked(), onNewButtonClicked(), onRenameButtonClicked(), onWorkbenchBoxActivated(), and ui.
Referenced by DlgCustomToolbars().
Member Data Documentation
ui
std::unique_ptr<Ui_DlgCustomToolbars> Gui::Dialog::DlgCustomToolbars::ui protected
Definition at line 91 of file DlgToolbarsImp.h.
Referenced by draftguitools.gui_splines.BSpline::action(), draftguitools.gui_beziers.BezCurve::action(), draftguitools.gui_lines.Line::action(), draftguitools.gui_mirror.Mirror::action(), draftguitools.gui_texts.Text::action(), draftguitools.gui_rectangles.Rectangle::action(), draftguitools.gui_offset.Offset::action(), draftguitools.gui_ellipses.Ellipse::action(), draftguitools.gui_labels.Label::action(), draftguitools.gui_dimensions.Dimension::action(), draftguitools.gui_split.Split::Activated(), draftguitools.gui_join.Join::Activated(), draftguitools.gui_rectangles.Rectangle::Activated(), draftguitools.gui_polygons.Polygon::Activated(), draftguitools.gui_draft2sketch.Draft2Sketch::Activated(), draftguitools.gui_downgrade.Downgrade::Activated(), draftguitools.gui_upgrade.Upgrade::Activated(), draftguitools.gui_shape2dview.Shape2DView::Activated(), draftguitools.gui_ellipses.Ellipse::Activated(), draftguitools.gui_move.Move::Activated(), draftguitools.gui_texts.Text::Activated(), draftguitools.gui_facebinders.Facebinder::Activated(), draftguitools.gui_points.Point::Activated(), draftguitools.gui_rotate.Rotate::Activated(), draftguitools.gui_lines.Line::Activated(), draftguitools.gui_arcs.Arc::Activated(), draftguitools.gui_circulararray.CircularArray::Activated(), draftguitools.gui_orthoarray.OrthoArray::Activated(), draftguitools.gui_polararray.PolarArray::Activated(), draftguitools.gui_shapestrings.ShapeString::Activated(), draftguitools.gui_fillets.Fillet::Activated(), draftguitools.gui_clone.Clone::Activated(), draftguitools.gui_scale.Scale::Activated(), draftguitools.gui_dimensions.Dimension::Activated(), Gui::Dialog::DlgCustomToolbarsImp::addCustomCommand(), Gui::Dialog::DlgCustomToolbarsImp::addCustomToolbar(), draftguitools.gui_stretch.Stretch::addPoint(), draftguitools.gui_rectangles.Rectangle::appendPoint(), draftguitools.gui_ellipses.Ellipse::appendPoint(), src.Mod.AddonManager.addonmanager_package_details_controller.PackageDetailsController::branch_changed(), src.Mod.AddonManager.addonmanager_package_details_controller.PackageDetailsController::change_branch_clicked(), changeEvent(), DraftGui.DraftToolBar::changeEvent(), draftguitools.gui_orthoarray.OrthoArray::click(), draftguitools.gui_polararray.PolarArray::click(), draftguitools.gui_circulararray.CircularArray::click(), draftguitools.gui_dimensions.Dimension::createObject(), src.Mod.AddonManager.addonmanager_package_details_controller.PackageDetailsController::disable_clicked(), DlgCustomToolbars(), draftguitools.gui_polygons.Polygon::drawPolygon(), src.Mod.AddonManager.addonmanager_package_details_controller.PackageDetailsController::enable_clicked(), draftguitools.gui_edit.Edit::endEditing(), src.Mod.AddonManager.change_branch.ChangeBranchDialog::exec(), draftguitools.gui_rectangles.Rectangle::finish(), draftguitools.gui_ellipses.Ellipse::finish(), draftguitools.gui_texts.Text::finish(), draftguitools.gui_polygons.Polygon::finish(), draftguitools.gui_arcs.Arc::finish(), draftguitools.gui_move.Move::finish(), draftguitools.gui_points.Point::finish(), draftguitools.gui_lines.Line::finish(), draftguitools.gui_base_original.DraftTool::finish(), draftguitools.gui_splines.BSpline::finish(), draftguitools.gui_dimensions.Dimension::finish(), draftguitools.gui_beziers.BezCurve::finish(), draftguitools.gui_rotate.Rotate::finish(), draftguitools.gui_edit.Edit::finish(), draftguitools.gui_beziers.CubicBezCurve::finish(), draftguitools.gui_trimex.Trimex::finish(), draftguitools.gui_move.Move::get_object_selection(), draftguitools.gui_rotate.Rotate::get_object_selection(), draftguitools.gui_scale.Scale::get_object_selection(), draftguitools.gui_subelements.SubelementHighlight::get_selection(), draftguitools.gui_base_original.DraftTool::getStrings(), draftguitools.gui_move.Move::handle_mouse_click_event(), hideEvent(), draftguitools.gui_polararray.PolarArray::move(), draftguitools.gui_circulararray.CircularArray::move(), draftguitools.gui_move.Move::move(), Gui::Dialog::DlgCustomToolbarsImp::moveDownCustomCommand(), Gui::Dialog::DlgCustomToolbarsImp::moveUpCustomCommand(), draftguitools.gui_polygons.Polygon::numericInput(), draftguitools.gui_rotate.Rotate::numericInput(), draftguitools.gui_arcs.Arc::numericInput(), draftguitools.gui_offset.Offset::numericRadius(), draftguitools.gui_rotate.Rotate::numericRadius(), draftguitools.gui_arcs.Arc::numericRadius(), onDeleteButtonClicked(), onModifyMacroAction(), onMoveActionDownButtonClicked(), onMoveActionLeftButtonClicked(), onMoveActionRightButtonClicked(), onMoveActionUpButtonClicked(), onNewButtonClicked(), onRenameButtonClicked(), onWorkbenchBoxActivated(), draftguitools.gui_groups.AddToGroup::proceed(), draftguitools.gui_groups.SetAutoGroup::proceed(), draftguitools.gui_edit.Edit::proceed(), Gui::Dialog::DlgCustomToolbarsImp::removeCustomCommand(), Gui::Dialog::DlgCustomToolbarsImp::removeCustomToolbar(), Gui::Dialog::DlgCustomToolbarsImp::renameCustomToolbar(), draftguitools.gui_rotate.Rotate::rotate(), src.Mod.AddonManager.package_list.PackageList::select_addon(), draftguitools.gui_fillets.Fillet::set_chamfer(), src.Mod.AddonManager.addonmanager_package_details_controller.PackageDetailsController::set_change_branch_button_state(), draftguitools.gui_fillets.Fillet::set_delete(), draftguitools.gui_move.Move::set_ghosts(), draftguitools.gui_rotate.Rotate::set_ghosts(), src.Mod.AddonManager.package_list.PackageList::set_loading(), draftguitools.gui_rotate.Rotate::set_start_point(), src.Mod.AddonManager.package_list.PackageList::set_view_style(), src.Mod.AddonManager.package_list.PackageList::setModel(), setupConnections(), src.Mod.AddonManager.addonmanager_package_details_controller.PackageDetailsController::show_repo(), Gui::Dialog::DlgCustomToolbarsImp::showEvent(), draftguitools.gui_edit.Edit::startEditing(), src.Mod.AddonManager.package_list.PackageList::update_loading_progress(), and draftguitools.gui_edit.Edit::updateTrackerAndGhost().
The documentation for this class was generated from the following files:
DlgToolbarsImp.h
DlgToolbarsImp.cpp