FreeCAD: MeshCore::CylinderFit Class Reference
MeshCore::CylinderFit Class Reference
#include <Approximation.h>
Public Member Functions
CylinderFit ()
float GetRadius () const
Base::Vector3f GetBase () const
void SetInitialValues (const Base::Vector3f &, const Base::Vector3f &)
Base::Vector3f GetAxis () const
Base::Vector3f GetInitialAxisFromNormals (const std::vector< Base::Vector3f > &n) const
float Fit () override
float GetDistanceToCylinder (const Base::Vector3f &rcPoint) const
float GetStdDeviation () const
void ProjectToCylinder ()
void GetBounding (Base::Vector3f &bottom, Base::Vector3f &top) const
Public Member Functions inherited from MeshCore::Approximation
Approximation ()
virtual ~Approximation ()
void AddPoint (const Base::Vector3f &point)
void AddPoints (const std::vector< Base::Vector3f > &points)
void AddPoints (const std::set< Base::Vector3f > &points)
void AddPoints (const std::list< Base::Vector3f > &points)
void AddPoints (const MeshPointArray &points)
const std::list< Base::Vector3f > & GetPoints () const
Base::Vector3f GetGravity () const
std::size_t CountPoints () const
void Clear ()
float GetLastResult () const
bool Done () const
Additional Inherited Members
Protected Member Functions inherited from MeshCore::Approximation
void GetMgcVectorArray (std::vector< Wm4::Vector3< double >> &rcPts) const
Approximation (const Approximation &)=default
Approximation (Approximation &&)=default
Approximation & operator= (const Approximation &)=default
Approximation & operator= (Approximation &&)=default
Protected Attributes inherited from MeshCore::Approximation
std::list< Base::Vector3f > _vPoints
bool _bIsFitted {false}
float _fLastResult {FLOAT_MAX}
Detailed Description
Approximation of a cylinder into a given set of points.
Definition at line 405 of file Approximation.h.
Constructor & Destructor Documentation
CylinderFit()
CylinderFit::CylinderFit ()
Definition at line 1083 of file Approximation.cpp.
Member Function Documentation
Fit()
float CylinderFit::Fit () override virtual
Fit a cylinder into the given points. If the fit fails FLOAT_MAX is returned.
Implements MeshCore::Approximation.
Definition at line 1165 of file Approximation.cpp.
References MeshCore::Approximation::_bIsFitted, MeshCore::Approximation::_fLastResult, MeshCore::Approximation::_vPoints, MeshCore::Approximation::AddPoints(), Base::Console(), MeshCore::Approximation::CountPoints(), MeshCoreFit::CylinderFit::Fit(), FLOAT_MAX, MeshCoreFit::CylinderFit::GetAxis(), MeshCoreFit::CylinderFit::GetBase(), MeshCoreFit::CylinderFit::GetNumIterations(), MeshCoreFit::CylinderFit::GetRadius(), MeshCoreFit::CylinderFit::GetStdDeviation(), Base::ConsoleSingleton::Log(), test::m, MeshCore::LMCylinderFunctor::m, MeshCore::LMCylinderFunctor::measuredValues, MeshCore::LMCylinderFunctor::n, Base::Vector3< float_type >::Normalize(), result, MeshCoreFit::CylinderFit::SetApproximations(), MovieTool::x, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by MeshCore::CylinderSurfaceFit::Fit(), MeshGui::CylinderFitParameter::getParameter(), and ReverseEngineeringGui::SegmentationManual::onCylinderDetectClicked().
GetAxis()
Base::Vector3f CylinderFit::GetAxis () const
Returns the axis of the fitted cylinder. If Fit() has not been called the null vector is returned.
Definition at line 1276 of file Approximation.cpp.
References MeshCore::Approximation::_bIsFitted.
Referenced by MeshCore::CylinderSurfaceFit::Fit(), MeshGui::CylinderFitParameter::getParameter(), ReverseEngineeringGui::SegmentationManual::onCylinderDetectClicked(), MeshCore::CylinderSurfaceFit::Parameters(), and ProjectToCylinder().
GetBase()
Base::Vector3f CylinderFit::GetBase () const
Definition at line 1267 of file Approximation.cpp.
References MeshCore::Approximation::_bIsFitted.
Referenced by MeshCore::CylinderSurfaceFit::Fit(), ReverseEngineeringGui::SegmentationManual::onCylinderDetectClicked(), MeshCore::CylinderSurfaceFit::Parameters(), and ProjectToCylinder().
GetBounding()
void CylinderFit::GetBounding (Base::Vector3f & bottom, Base::Vector3f & top) const
Get the bottom and top points of the cylinder. The distance of these points gives the height of the cylinder.
Definition at line 1319 of file Approximation.cpp.
References MeshCore::Approximation::_vPoints, DraftVecUtils::dist(), and Base::Vector3< float_type >::Perpendicular().
Referenced by MeshGui::CylinderFitParameter::getParameter().
GetDistanceToCylinder()
float CylinderFit::GetDistanceToCylinder (const Base::Vector3f & rcPoint) const
Returns the distance from the point rcPoint to the fitted cylinder. If Fit() has not been called FLOAT_MAX is returned.
Definition at line 1285 of file Approximation.cpp.
References MeshCore::Approximation::_bIsFitted, Base::Vector3< float_type >::DistanceToLine(), and FLOAT_MAX.
Referenced by GetStdDeviation().
GetInitialAxisFromNormals()
Base::Vector3f CylinderFit::GetInitialAxisFromNormals (const std::vector< Base::Vector3f > & n) const
Returns an initial axis based on point normals.
Definition at line 1088 of file Approximation.cpp.
References MeshCore::Approximation::AddPoints(), MeshCore::PlaneFit::Fit(), MeshCore::PlaneFit::GetNormal(), SplineSurface::i, Base::Vector3< float_type >::Normalize(), Base::Vector3< float_type >::Set(), Base::Vector3< float_type >::Sqr(), src.Mod.PartDesign.fcgear.svggear::w, MovieTool::x, Base::Vector3< float_type >::x, MovieTool::y, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by MeshGui::CylinderFitParameter::getParameter(), and ReverseEngineeringGui::SegmentationManual::onCylinderDetectClicked().
GetRadius()
float CylinderFit::GetRadius () const
Definition at line 1262 of file Approximation.cpp.
Referenced by MeshCore::CylinderSurfaceFit::Fit(), MeshGui::CylinderFitParameter::getParameter(), ReverseEngineeringGui::SegmentationManual::onCylinderDetectClicked(), and MeshCore::CylinderSurfaceFit::Parameters().
GetStdDeviation()
float CylinderFit::GetStdDeviation () const
Returns the standard deviation from the points to the fitted cylinder. If Fit() has not been called FLOAT_MAX is returned.
Definition at line 1294 of file Approximation.cpp.
References MeshCore::Approximation::_bIsFitted, MeshCore::Approximation::_vPoints, MeshCore::Approximation::CountPoints(), FLOAT_MAX, GetDistanceToCylinder(), and KDL::sqrt().
ProjectToCylinder()
void CylinderFit::ProjectToCylinder ()
Projects the points onto the fitted cylinder.
Definition at line 1342 of file Approximation.cpp.
References MeshCore::Approximation::_vPoints, KDL::diff(), Base::Vector3< float_type >::DistanceToLine(), GetAxis(), GetBase(), Base::Vector3< float_type >::Move(), Base::Vector3< float_type >::ProjectToPlane(), MovieTool::x, and MovieTool::y.
SetInitialValues()
void CylinderFit::SetInitialValues (const Base::Vector3f & b, const Base::Vector3f & n)
Definition at line 1158 of file Approximation.cpp.
References SCL.SimpleDataTypes::b.
Referenced by MeshGui::CylinderFitParameter::getParameter(), and ReverseEngineeringGui::SegmentationManual::onCylinderDetectClicked().
The documentation for this class was generated from the following files:
Approximation.h
Approximation.cpp