FreeCAD: MeshCore::TriangulationVerifier Class Reference
MeshCore::TriangulationVerifier Class Reference
#include <Triangulation.h>
Public Member Functions
TriangulationVerifier ()=default
virtual ~TriangulationVerifier ()=default
TriangulationVerifier (const TriangulationVerifier &)=delete
TriangulationVerifier (TriangulationVerifier &&)=delete
TriangulationVerifier & operator= (const TriangulationVerifier &)=delete
TriangulationVerifier & operator= (TriangulationVerifier &&)=delete
virtual bool Accept (const Base::Vector3f &n, const Base::Vector3f &p1, const Base::Vector3f &p2, const Base::Vector3f &p3) const
virtual bool MustFlip (const Base::Vector3f &n1, const Base::Vector3f &n2) const
Detailed Description
Definition at line 53 of file Triangulation.h.
Constructor & Destructor Documentation
TriangulationVerifier() [1/3]
MeshCore::TriangulationVerifier::TriangulationVerifier () default
~TriangulationVerifier()
virtual MeshCore::TriangulationVerifier::~TriangulationVerifier () virtual default
TriangulationVerifier() [2/3]
MeshCore::TriangulationVerifier::TriangulationVerifier (const TriangulationVerifier &) delete
TriangulationVerifier() [3/3]
MeshCore::TriangulationVerifier::TriangulationVerifier (TriangulationVerifier &&) delete
Member Function Documentation
Accept()
bool TriangulationVerifier::Accept (const Base::Vector3f & n, const Base::Vector3f & p1, const Base::Vector3f & p2, const Base::Vector3f & p3) const virtual
Reimplemented in MeshCore::TriangulationVerifierV2.
Definition at line 41 of file Triangulation.cpp.
Referenced by MeshCore::MeshAlgorithm::FillupHole().
MustFlip()
bool TriangulationVerifier::MustFlip (const Base::Vector3f & n1, const Base::Vector3f & n2) const virtual
Reimplemented in MeshCore::TriangulationVerifierV2.
Definition at line 51 of file Triangulation.cpp.
References Base::Vector3< float_type >::Dot().
Referenced by MeshCore::MeshAlgorithm::FillupHole().
operator=() [1/2]
TriangulationVerifier& MeshCore::TriangulationVerifier::operator= (const TriangulationVerifier &) delete
operator=() [2/2]
TriangulationVerifier& MeshCore::TriangulationVerifier::operator= (TriangulationVerifier &&) delete
The documentation for this class was generated from the following files:
Triangulation.h
Triangulation.cpp