FreeCAD: CAMTests.TestPathThreadMilling.TestPathThreadMilling Class Reference
CAMTests.TestPathThreadMilling.TestPathThreadMilling Class Reference
Public Member Functions
def assertRadii (self, have, want)
def assertList (self, have, want)
def assertSetupInternal (self, obj, c, begin, end)
def assertSetupExternal (self, obj, c, begin, end)
def test00 (self)
def test01 (self)
def test10 (self)
def test20 (self)
def test21 (self)
def test30 (self)
def test40 (self)
def test41 (self)
def test50 (self)
def test51 (self)
Public Member Functions inherited from CAMTests.PathTestUtils.PathTestBase
def assertRoughly (self, f1, f2, error=0.00001)
def assertCoincide (self, pt1, pt2, error=0.0001)
def assertPlacement (self, p1, p2)
def assertLine (self, edge, pt1, pt2)
def assertLines (self, edgs, tail, points)
def assertArc (self, edge, pt1, pt2, direction="CW")
def assertCircle (self, edge, pt, r)
def assertCurve (self, edge, p1, p2, p3)
def assertCylinderAt (self, solid, pt, r, h)
def assertConeAt (self, solid, pt, r1, r2, h)
def assertCommandEqual (self, c1, c2)
def assertEqualLocale (self, s1, s2)
def assertEdgeShapesMatch (self, e1, e2)
def assertPointsMatch (self, pts0, pts1)
def assertSuccessfulRecompute (self, doc, *objs, msg=None)
Detailed Description
Test thread milling basics.
Definition at line 46 of file TestPathThreadMilling.py.
Member Function Documentation
assertList()
def CAMTests.TestPathThreadMilling.TestPathThreadMilling.assertList (self, have, want)
Definition at line 53 of file TestPathThreadMilling.py.
References CAMTests.PathTestUtils.PathTestBase.assertRoughly().
Referenced by CAMTests.TestPathThreadMilling.TestPathThreadMilling.test10(), and CAMTests.TestPathThreadMilling.TestPathThreadMilling.test30().
assertRadii()
def CAMTests.TestPathThreadMilling.TestPathThreadMilling.assertRadii (self, have, want)
Definition at line 49 of file TestPathThreadMilling.py.
References CAMTests.PathTestUtils.PathTestBase.assertRoughly().
Referenced by CAMTests.TestPathThreadMilling.TestPathThreadMilling.test00(), CAMTests.TestPathThreadMilling.TestPathThreadMilling.test01(), CAMTests.TestPathThreadMilling.TestPathThreadMilling.test20(), and CAMTests.TestPathThreadMilling.TestPathThreadMilling.test21().
assertSetupExternal()
def CAMTests.TestPathThreadMilling.TestPathThreadMilling.assertSetupExternal (self, obj, c, begin, end)
Definition at line 66 of file TestPathThreadMilling.py.
Referenced by CAMTests.TestPathThreadMilling.TestPathThreadMilling.test50(), and CAMTests.TestPathThreadMilling.TestPathThreadMilling.test51().
assertSetupInternal()
def CAMTests.TestPathThreadMilling.TestPathThreadMilling.assertSetupInternal (self, obj, c, begin, end)
Definition at line 58 of file TestPathThreadMilling.py.
Referenced by CAMTests.TestPathThreadMilling.TestPathThreadMilling.test40(), and CAMTests.TestPathThreadMilling.TestPathThreadMilling.test41().
test00()
def CAMTests.TestPathThreadMilling.TestPathThreadMilling.test00 (self)
Verify internal radii.
Definition at line 74 of file TestPathThreadMilling.py.
References CAMTests.TestPathThreadMilling.TestPathThreadMilling.assertRadii().
Referenced by CAMTests.TestPathToolController.TestPathToolController.test01().
test01()
def CAMTests.TestPathThreadMilling.TestPathThreadMilling.test01 (self)
Verify internal radii with tool crest.
Definition at line 79 of file TestPathThreadMilling.py.
References CAMTests.TestPathThreadMilling.TestPathThreadMilling.assertRadii().
test10()
def CAMTests.TestPathThreadMilling.TestPathThreadMilling.test10 (self)
Verify internal thread passes.
Definition at line 83 of file TestPathThreadMilling.py.
References CAMTests.TestPathThreadMilling.TestPathThreadMilling.assertList().
test20()
def CAMTests.TestPathThreadMilling.TestPathThreadMilling.test20 (self)
Verify external radii.
Definition at line 92 of file TestPathThreadMilling.py.
References CAMTests.TestPathThreadMilling.TestPathThreadMilling.assertRadii().
test21()
def CAMTests.TestPathThreadMilling.TestPathThreadMilling.test21 (self)
Verify external radii with tool crest.
Definition at line 97 of file TestPathThreadMilling.py.
References CAMTests.TestPathThreadMilling.TestPathThreadMilling.assertRadii().
test30()
def CAMTests.TestPathThreadMilling.TestPathThreadMilling.test30 (self)
Verify external thread passes.
Definition at line 101 of file TestPathThreadMilling.py.
References CAMTests.TestPathThreadMilling.TestPathThreadMilling.assertList().
test40()
def CAMTests.TestPathThreadMilling.TestPathThreadMilling.test40 (self)
Verify internal right hand thread setup.
Definition at line 110 of file TestPathThreadMilling.py.
References CAMTests.TestPathThreadMilling.TestPathThreadMilling.assertSetupInternal().
test41()
def CAMTests.TestPathThreadMilling.TestPathThreadMilling.test41 (self)
Verify internal left hand thread setup.
Definition at line 122 of file TestPathThreadMilling.py.
References CAMTests.TestPathThreadMilling.TestPathThreadMilling.assertSetupInternal().
test50()
def CAMTests.TestPathThreadMilling.TestPathThreadMilling.test50 (self)
Verify exteranl right hand thread setup.
Definition at line 134 of file TestPathThreadMilling.py.
References CAMTests.TestPathThreadMilling.TestPathThreadMilling.assertSetupExternal().
test51()
def CAMTests.TestPathThreadMilling.TestPathThreadMilling.test51 (self)
Verify exteranl left hand thread setup.
Definition at line 146 of file TestPathThreadMilling.py.
References CAMTests.TestPathThreadMilling.TestPathThreadMilling.assertSetupExternal().
The documentation for this class was generated from the following file:
TestPathThreadMilling.py