FreeCAD: Gui::View3DInventorViewerPy Class Reference
Gui::View3DInventorViewerPy Class Reference
Python interface for View3DInventorViewer.
#include <View3DViewerPy.h>
Public Member Functions
View3DInventorViewerPy (View3DInventorViewer *vi)
~View3DInventorViewerPy () override
Py::Object repr () override
Py::Object getattr (const char *) override
int setattr (const char *, const Py::Object &) override
Py::Object getSoEventManager (const Py::Tuple &)
Py::Object getSoRenderManager (const Py::Tuple &)
Py::Object getSceneGraph (const Py::Tuple &)
Py::Object setSceneGraph (const Py::Tuple &)
Py::Object seekToPoint (const Py::Tuple &)
Py::Object setFocalDistance (const Py::Tuple &args)
Py::Object getFocalDistance (const Py::Tuple &args)
Py::Object getPointOnFocalPlane (const Py::Tuple &args)
Py::Object getPickRadius (const Py::Tuple &args)
Py::Object setPickRadius (const Py::Tuple &args)
Py::Object setupEditingRoot (const Py::Tuple &args)
Py::Object resetEditingRoot (const Py::Tuple &args)
Py::Object setGradientBackground (const Py::Tuple &args)
Py::Object setGradientBackgroundColor (const Py::Tuple &args)
Py::Object setBackgroundColor (const Py::Tuple &args)
Py::Object setRedirectToSceneGraph (const Py::Tuple &args)
Py::Object isRedirectedToSceneGraph (const Py::Tuple &args)
Py::Object grabFramebuffer (const Py::Tuple &args)
Py::Object setEnabledNaviCube (const Py::Tuple &args)
Py::Object isEnabledNaviCube (const Py::Tuple &args)
Py::Object setNaviCubeCorner (const Py::Tuple &args)
Py::Object getNavigationStyle (const Py::Tuple &)
Static Public Member Functions
static void init_type ()
Friends
class View3DInventorViewer
Detailed Description
Python interface for View3DInventorViewer.
The interface does not offer all methods the c++ View3DInventorViewer counterpart has, respectively also not everything the QuarterWidget and the SoQtQuarterAdaptor offers. It only exposes methods with additional functionality in comparison to the View3DInventorPy class. Everything that can be done from there has no interface here.
Definition at line 62 of file View3DViewerPy.h.
Constructor & Destructor Documentation
View3DInventorViewerPy()
View3DInventorViewerPy::View3DInventorViewerPy (View3DInventorViewer * vi) explicit
Definition at line 113 of file View3DViewerPy.cpp.
~View3DInventorViewerPy()
View3DInventorViewerPy::~View3DInventorViewerPy () override
Definition at line 118 of file View3DViewerPy.cpp.
Member Function Documentation
getattr()
Py::Object View3DInventorViewerPy::getattr (const char * attr) override
Definition at line 153 of file View3DViewerPy.cpp.
References toolbit-attributes::s.
getFocalDistance()
Py::Object View3DInventorViewerPy::getFocalDistance (const Py::Tuple & args)
Definition at line 316 of file View3DViewerPy.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, and SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager().
Referenced by init_type().
getNavigationStyle()
Py::Object View3DInventorViewerPy::getNavigationStyle (const Py::Tuple & args)
Definition at line 612 of file View3DViewerPy.cpp.
References toolbit-attributes::args, Gui::NavigationStyle::getPyObject(), and Gui::View3DInventorViewer::navigationStyle().
Referenced by init_type().
getPickRadius()
Py::Object View3DInventorViewerPy::getPickRadius (const Py::Tuple & args)
Definition at line 357 of file View3DViewerPy.cpp.
References toolbit-attributes::args, and SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getPickRadius().
Referenced by init_type().
getPointOnFocalPlane()
Py::Object View3DInventorViewerPy::getPointOnFocalPlane (const Py::Tuple & args)
Definition at line 336 of file View3DViewerPy.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, Gui::View3DInventorViewer::getPointOnFocalPlane(), InitGui::t, MovieTool::x, and MovieTool::y.
Referenced by init_type().
getSceneGraph()
Py::Object View3DInventorViewerPy::getSceneGraph (const Py::Tuple & args)
Definition at line 202 of file View3DViewerPy.cpp.
References toolbit-attributes::args, Base::InterpreterSingleton::createSWIGPointerObj(), SCL.SimpleDataTypes::e, SIM::Coin3D::Quarter::QuarterWidget::getSceneGraph(), and Base::Interpreter().
Referenced by init_type().
getSoEventManager()
Py::Object View3DInventorViewerPy::getSoEventManager (const Py::Tuple & args)
Definition at line 240 of file View3DViewerPy.cpp.
References toolbit-attributes::args, Base::InterpreterSingleton::createSWIGPointerObj(), SCL.SimpleDataTypes::e, SIM::Coin3D::Quarter::QuarterWidget::getSoEventManager(), and Base::Interpreter().
Referenced by init_type().
getSoRenderManager()
Py::Object View3DInventorViewerPy::getSoRenderManager (const Py::Tuple & args)
Definition at line 186 of file View3DViewerPy.cpp.
References toolbit-attributes::args, Base::InterpreterSingleton::createSWIGPointerObj(), SCL.SimpleDataTypes::e, SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), and Base::Interpreter().
Referenced by init_type().
grabFramebuffer()
Py::Object View3DInventorViewerPy::grabFramebuffer (const Py::Tuple & args)
Definition at line 573 of file View3DViewerPy.cpp.
References toolbit-attributes::args, Gui::PythonWrapper::fromQImage(), Gui::View3DInventorViewer::grabFramebuffer(), and Gui::PythonWrapper::loadGuiModule().
Referenced by init_type().
init_type()
void View3DInventorViewerPy::init_type () static
Definition at line 42 of file View3DViewerPy.cpp.
References getFocalDistance(), getNavigationStyle(), getPickRadius(), getPointOnFocalPlane(), getSceneGraph(), getSoEventManager(), getSoRenderManager(), grabFramebuffer(), isEnabledNaviCube(), isRedirectedToSceneGraph(), resetEditingRoot(), seekToPoint(), setBackgroundColor(), setEnabledNaviCube(), setFocalDistance(), setGradientBackground(), setGradientBackgroundColor(), setNaviCubeCorner(), setPickRadius(), setRedirectToSceneGraph(), setSceneGraph(), and setupEditingRoot().
Referenced by Gui::Application::Application().
isEnabledNaviCube()
Py::Object View3DInventorViewerPy::isEnabledNaviCube (const Py::Tuple & args)
Definition at line 593 of file View3DViewerPy.cpp.
References toolbit-attributes::args, and Gui::View3DInventorViewer::isEnabledNaviCube().
Referenced by init_type().
isRedirectedToSceneGraph()
Py::Object View3DInventorViewerPy::isRedirectedToSceneGraph (const Py::Tuple & args)
Definition at line 565 of file View3DViewerPy.cpp.
References toolbit-attributes::args, and Gui::View3DInventorViewer::isRedirectedToSceneGraph().
Referenced by init_type().
repr()
Py::Object View3DInventorViewerPy::repr () override
Definition at line 126 of file View3DViewerPy.cpp.
References src.Mod.Test.testmakeWireString::String.
resetEditingRoot()
Py::Object View3DInventorViewerPy::resetEditingRoot (const Py::Tuple & args)
Definition at line 428 of file View3DViewerPy.cpp.
References toolbit-attributes::args, Base::asBoolean(), SCL.SimpleDataTypes::e, and Gui::View3DInventorViewer::resetEditingRoot().
Referenced by init_type().
seekToPoint()
Py::Object View3DInventorViewerPy::seekToPoint (const Py::Tuple & args)
Definition at line 256 of file View3DViewerPy.cpp.
References toolbit-attributes::args, SIM::Coin3D::Quarter::SoQTQuarterAdaptor::seekToPoint(), MovieTool::x, and MovieTool::y.
Referenced by init_type().
setattr()
int View3DInventorViewerPy::setattr (const char * attr, const Py::Object & value) override
Definition at line 173 of file View3DViewerPy.cpp.
References toolbit-attributes::s.
setBackgroundColor()
Py::Object View3DInventorViewerPy::setBackgroundColor (const Py::Tuple & args)
Definition at line 525 of file View3DViewerPy.cpp.
References toolbit-attributes::args, blue, SCL.SimpleDataTypes::e, green, red, SIM::Coin3D::Quarter::QuarterWidget::redraw(), SIM::Coin3D::Quarter::QuarterWidget::setBackgroundColor(), and Gui::View3DInventorViewer::setGradientBackgroundColor().
Referenced by init_type().
setEnabledNaviCube()
Py::Object View3DInventorViewerPy::setEnabledNaviCube (const Py::Tuple & args)
Definition at line 584 of file View3DViewerPy.cpp.
References toolbit-attributes::args, Base::asBoolean(), test::m, and Gui::View3DInventorViewer::setEnabledNaviCube().
Referenced by init_type().
setFocalDistance()
Py::Object View3DInventorViewerPy::setFocalDistance (const Py::Tuple & args)
Definition at line 289 of file View3DViewerPy.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, and SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager().
Referenced by init_type().
setGradientBackground()
Py::Object View3DInventorViewerPy::setGradientBackground (const Py::Tuple & args)
Definition at line 450 of file View3DViewerPy.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, SIM::Coin3D::Quarter::QuarterWidget::redraw(), and Gui::View3DInventorViewer::setGradientBackground().
Referenced by init_type().
setGradientBackgroundColor()
Py::Object View3DInventorViewerPy::setGradientBackgroundColor (const Py::Tuple & args)
Definition at line 480 of file View3DViewerPy.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, SplineSurface::i, SIM::Coin3D::Quarter::QuarterWidget::redraw(), and Gui::View3DInventorViewer::setGradientBackgroundColor().
Referenced by init_type().
setNaviCubeCorner()
Py::Object View3DInventorViewerPy::setNaviCubeCorner (const Py::Tuple & args)
Definition at line 601 of file View3DViewerPy.cpp.
References toolbit-attributes::args, RobotExample::pos, and Gui::View3DInventorViewer::setNaviCubeCorner().
Referenced by init_type().
setPickRadius()
Py::Object View3DInventorViewerPy::setPickRadius (const Py::Tuple & args)
Definition at line 366 of file View3DViewerPy.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, and SIM::Coin3D::Quarter::SoQTQuarterAdaptor::setPickRadius().
Referenced by init_type().
setRedirectToSceneGraph()
Py::Object View3DInventorViewerPy::setRedirectToSceneGraph (const Py::Tuple & args)
Definition at line 556 of file View3DViewerPy.cpp.
References toolbit-attributes::args, Base::asBoolean(), test::m, and Gui::View3DInventorViewer::setRedirectToSceneGraph().
Referenced by init_type().
setSceneGraph()
Py::Object View3DInventorViewerPy::setSceneGraph (const Py::Tuple & args)
Definition at line 219 of file View3DViewerPy.cpp.
References toolbit-attributes::args, Base::InterpreterSingleton::convertSWIGPointerObj(), SCL.SimpleDataTypes::e, Base::Interpreter(), and Gui::View3DInventorViewer::setSceneGraph().
Referenced by init_type().
setupEditingRoot()
Py::Object View3DInventorViewerPy::setupEditingRoot (const Py::Tuple & args)
Definition at line 391 of file View3DViewerPy.cpp.
References toolbit-attributes::args, Base::InterpreterSingleton::convertSWIGPointerObj(), SCL.SimpleDataTypes::e, Base::Interpreter(), and Gui::View3DInventorViewer::setupEditingRoot().
Referenced by init_type().
Friends And Related Function Documentation
View3DInventorViewer
friend class View3DInventorViewer friend
Definition at line 112 of file View3DViewerPy.h.
The documentation for this class was generated from the following files:
View3DViewerPy.h
View3DViewerPy.cpp