FreeCAD: MeshGui::SoFCMeshObjectBoundary Class Reference
MeshGui::SoFCMeshObjectBoundary Class Reference
#include <SoFCMeshObject.h>
Public Member Functions
SoFCMeshObjectBoundary ()
Static Public Member Functions
static void initClass ()
Protected Member Functions
void GLRender (SoGLRenderAction *action) override
void computeBBox (SoAction *action, SbBox3f &box, SbVec3f &center) override
void getPrimitiveCount (SoGetPrimitiveCountAction *action) override
void generatePrimitives (SoAction *action) override
~SoFCMeshObjectBoundary () override=default
Detailed Description
Definition at line 284 of file SoFCMeshObject.h.
Constructor & Destructor Documentation
SoFCMeshObjectBoundary()
SoFCMeshObjectBoundary::SoFCMeshObjectBoundary ()
Definition at line 1649 of file SoFCMeshObject.cpp.
~SoFCMeshObjectBoundary()
MeshGui::SoFCMeshObjectBoundary::~SoFCMeshObjectBoundary () override protected default
Member Function Documentation
computeBBox()
void SoFCMeshObjectBoundary::computeBBox (SoAction * action, SbBox3f & box, SbVec3f & center) override protected
Sets the bounding box of the mesh to box and its center to center.
Definition at line 1751 of file SoFCMeshObject.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Base::BoundBox3< Precision >::Add(), MengerSponge::box, exportCSG::center(), MeshGui::SoFCMeshObjectElement::get(), Base::BoundBox3< Precision >::GetCenter(), Base::BoundBox3< Precision >::MaxX, Base::BoundBox3< Precision >::MaxY, Base::BoundBox3< Precision >::MaxZ, Mesh2Shape::mesh, Base::BoundBox3< Precision >::MinX, Base::BoundBox3< Precision >::MinY, and Base::BoundBox3< Precision >::MinZ.
generatePrimitives()
void SoFCMeshObjectBoundary::generatePrimitives (SoAction * action) override protected
Definition at line 1703 of file SoFCMeshObject.cpp.
References Path.Post.scripts.dynapath_4060_post::action, MeshCore::FACET_INDEX_MAX, MeshGui::SoFCMeshObjectElement::get(), SplineSurface::i, Mesh2Shape::mesh, sbvec3f(), and draftgeoutils.general::v1().
getPrimitiveCount()
void SoFCMeshObjectBoundary::getPrimitiveCount (SoGetPrimitiveCountAction * action) override protected
Adds the number of the triangles to the SoGetPrimitiveCountAction.
Definition at line 1778 of file SoFCMeshObject.cpp.
References Path.Post.scripts.dynapath_4060_post::action, MeshCore::FACET_INDEX_MAX, MeshGui::SoFCMeshObjectElement::get(), and Mesh2Shape::mesh.
GLRender()
void SoFCMeshObjectBoundary::GLRender (SoGLRenderAction * action) override protected
Renders the open edges only.
Definition at line 1657 of file SoFCMeshObject.cpp.
References Path.Post.scripts.dynapath_4060_post::action, MeshGui::SoFCMeshObjectElement::get(), and Mesh2Shape::mesh.
initClass()
void SoFCMeshObjectBoundary::initClass () static
Definition at line 1644 of file SoFCMeshObject.cpp.
Referenced by PyMOD_INIT_FUNC().
The documentation for this class was generated from the following files:
SoFCMeshObject.h
SoFCMeshObject.cpp