FreeCAD: PropertyListDialog Class Reference
PropertyListDialog Class Reference
Public Member Functions
PropertyListDialog (int type, QWidget *parent)
void accept () override
Detailed Description
Definition at line 1396 of file Widgets.cpp.
Constructor & Destructor Documentation
PropertyListDialog()
PropertyListDialog::PropertyListDialog (int type, QWidget * parent) inline
Definition at line 1401 of file Widgets.cpp.
Member Function Documentation
accept()
void PropertyListDialog::accept () inline override
Definition at line 1405 of file Widgets.cpp.
References Path.Post.scripts.grbl_post::type.
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
The documentation for this class was generated from the following file:
Widgets.cpp