FreeCAD: SafeMode Namespace Reference
SafeMode Namespace Reference
Functions
AppExport bool SafeModeEnabled ()
AppExport void StartSafeMode ()
AppExport void Destruct ()
Function Documentation
Destruct()
void SafeMode::Destruct ()
Definition at line 79 of file SafeMode.cpp.
References tempDir.
Referenced by App::Application::destruct().
SafeModeEnabled()
bool SafeMode::SafeModeEnabled ()
Definition at line 74 of file SafeMode.cpp.
References tempDir.
Referenced by Gui::MainWindow::setWindowTitle().
StartSafeMode()
void SafeMode::StartSafeMode ()
Definition at line 67 of file SafeMode.cpp.
References _createTemporaryBaseDir(), and _replaceDirs().