FreeCAD: src.Mod.AddonManager.AddonManagerTest.app.test_utilities.TestUtilities Class Reference
src.Mod.AddonManager.AddonManagerTest.app.test_utilities.TestUtilities Class Reference
Public Member Functions
def tearDownClass (cls)
def test_recognized_git_location (self)
def test_get_readme_url (self)
def test_get_assigned_string_literal (self)
def test_get_macro_version_from_file_good_metadata (self)
def test_get_macro_version_from_file_missing_quotes (self)
def test_get_macro_version_from_file_no_version (self)
def test_run_interruptable_subprocess_success_instant_return (self, mock_popen)
def test_run_interruptable_subprocess_returns_nonzero (self, mock_popen)
def test_run_interruptable_subprocess_timeout_five_times (self, mock_popen)
def test_run_interruptable_subprocess_timeout_exceeded (self, mock_popen)
def test_process_date_string_to_python_datetime_non_numeric (self)
def test_process_date_string_to_python_datetime_year_first (self)
def test_process_date_string_to_python_datetime_day_first (self)
def test_process_date_string_to_python_datetime_month_first (self)
def test_process_date_string_to_python_datetime_ambiguous (self)
def test_process_date_string_to_python_datetime_invalid_date (self)
def test_process_date_string_to_python_datetime_too_many_components (self)
def test_process_date_string_to_python_datetime_too_few_components (self)
def test_process_date_string_to_python_datetime_unrecognizable (self)
def test_process_date_string_to_python_datetime_valid_separators (self)
def test_process_date_string_to_python_datetime_invalid_separators (self)
Static Public Attributes
string MODULE = "test_utilities"
Detailed Description
Definition at line 50 of file test_utilities.py.
Member Function Documentation
tearDownClass()
def src.Mod.AddonManager.AddonManagerTest.app.test_utilities.TestUtilities.tearDownClass (cls)
Definition at line 55 of file test_utilities.py.
test_get_assigned_string_literal()
def src.Mod.AddonManager.AddonManagerTest.app.test_utilities.TestUtilities.test_get_assigned_string_literal (self)
Definition at line 111 of file test_utilities.py.
References src.Mod.AddonManager.addonmanager_utilities.get_assigned_string_literal().
test_get_macro_version_from_file_good_metadata()
def src.Mod.AddonManager.AddonManagerTest.app.test_utilities.TestUtilities.test_get_macro_version_from_file_good_metadata (self)
Definition at line 134 of file test_utilities.py.
References src.Mod.AddonManager.addonmanager_utilities.get_macro_version_from_file().
test_get_macro_version_from_file_missing_quotes()
def src.Mod.AddonManager.AddonManagerTest.app.test_utilities.TestUtilities.test_get_macro_version_from_file_missing_quotes (self)
Definition at line 140 of file test_utilities.py.
References src.Mod.AddonManager.addonmanager_utilities.get_macro_version_from_file().
test_get_macro_version_from_file_no_version()
def src.Mod.AddonManager.AddonManagerTest.app.test_utilities.TestUtilities.test_get_macro_version_from_file_no_version (self)
Definition at line 146 of file test_utilities.py.
References src.Mod.AddonManager.addonmanager_utilities.get_macro_version_from_file().
test_get_readme_url()
def src.Mod.AddonManager.AddonManagerTest.app.test_utilities.TestUtilities.test_get_readme_url (self)
Definition at line 82 of file test_utilities.py.
References src.Mod.AddonManager.addonmanager_utilities.get_readme_url().
test_process_date_string_to_python_datetime_ambiguous()
def src.Mod.AddonManager.AddonManagerTest.app.test_utilities.TestUtilities.test_process_date_string_to_python_datetime_ambiguous (self)
In the ambiguous case, the code should assume that the date is in the DD-MM-YYYY format.
Definition at line 244 of file test_utilities.py.
References src.Mod.AddonManager.addonmanager_utilities.process_date_string_to_python_datetime().
test_process_date_string_to_python_datetime_day_first()
def src.Mod.AddonManager.AddonManagerTest.app.test_utilities.TestUtilities.test_process_date_string_to_python_datetime_day_first (self)
Definition at line 234 of file test_utilities.py.
References src.Mod.AddonManager.addonmanager_utilities.process_date_string_to_python_datetime().
test_process_date_string_to_python_datetime_invalid_date()
def src.Mod.AddonManager.AddonManagerTest.app.test_utilities.TestUtilities.test_process_date_string_to_python_datetime_invalid_date (self)
Definition at line 250 of file test_utilities.py.
References src.Mod.AddonManager.addonmanager_utilities.process_date_string_to_python_datetime().
test_process_date_string_to_python_datetime_invalid_separators()
def src.Mod.AddonManager.AddonManagerTest.app.test_utilities.TestUtilities.test_process_date_string_to_python_datetime_invalid_separators (self)
Only the four separators [ ./-] are supported: ensure others fail
Definition at line 277 of file test_utilities.py.
References src.Mod.AddonManager.addonmanager_utilities.process_date_string_to_python_datetime().
test_process_date_string_to_python_datetime_month_first()
def src.Mod.AddonManager.AddonManagerTest.app.test_utilities.TestUtilities.test_process_date_string_to_python_datetime_month_first (self)
Definition at line 239 of file test_utilities.py.
References src.Mod.AddonManager.addonmanager_utilities.process_date_string_to_python_datetime().
test_process_date_string_to_python_datetime_non_numeric()
def src.Mod.AddonManager.AddonManagerTest.app.test_utilities.TestUtilities.test_process_date_string_to_python_datetime_non_numeric (self)
Definition at line 225 of file test_utilities.py.
References src.Mod.AddonManager.addonmanager_utilities.process_date_string_to_python_datetime().
test_process_date_string_to_python_datetime_too_few_components()
def src.Mod.AddonManager.AddonManagerTest.app.test_utilities.TestUtilities.test_process_date_string_to_python_datetime_too_few_components (self)
Month-Year-only dates are not supported
Definition at line 258 of file test_utilities.py.
References src.Mod.AddonManager.addonmanager_utilities.process_date_string_to_python_datetime().
test_process_date_string_to_python_datetime_too_many_components()
def src.Mod.AddonManager.AddonManagerTest.app.test_utilities.TestUtilities.test_process_date_string_to_python_datetime_too_many_components (self)
Definition at line 254 of file test_utilities.py.
References src.Mod.AddonManager.addonmanager_utilities.process_date_string_to_python_datetime().
test_process_date_string_to_python_datetime_unrecognizable()
def src.Mod.AddonManager.AddonManagerTest.app.test_utilities.TestUtilities.test_process_date_string_to_python_datetime_unrecognizable (self)
Two-digit years are not supported
Definition at line 263 of file test_utilities.py.
References src.Mod.AddonManager.addonmanager_utilities.process_date_string_to_python_datetime().
test_process_date_string_to_python_datetime_valid_separators()
def src.Mod.AddonManager.AddonManagerTest.app.test_utilities.TestUtilities.test_process_date_string_to_python_datetime_valid_separators (self)
Four individual separators are supported, plus any combination of multiple of those separators
Definition at line 268 of file test_utilities.py.
References src.Mod.AddonManager.addonmanager_utilities.process_date_string_to_python_datetime().
test_process_date_string_to_python_datetime_year_first()
def src.Mod.AddonManager.AddonManagerTest.app.test_utilities.TestUtilities.test_process_date_string_to_python_datetime_year_first (self)
Definition at line 229 of file test_utilities.py.
References src.Mod.AddonManager.addonmanager_utilities.process_date_string_to_python_datetime().
test_recognized_git_location()
def src.Mod.AddonManager.AddonManagerTest.app.test_utilities.TestUtilities.test_recognized_git_location (self)
Definition at line 61 of file test_utilities.py.
References src.Mod.AddonManager.addonmanager_utilities.recognized_git_location().
test_run_interruptable_subprocess_returns_nonzero()
def src.Mod.AddonManager.AddonManagerTest.app.test_utilities.TestUtilities.test_run_interruptable_subprocess_returns_nonzero (self, mock_popen)
Definition at line 166 of file test_utilities.py.
References src.Mod.AddonManager.addonmanager_utilities.run_interruptable_subprocess().
test_run_interruptable_subprocess_success_instant_return()
def src.Mod.AddonManager.AddonManagerTest.app.test_utilities.TestUtilities.test_run_interruptable_subprocess_success_instant_return (self, mock_popen)
Definition at line 153 of file test_utilities.py.
References src.Mod.AddonManager.addonmanager_utilities.run_interruptable_subprocess().
test_run_interruptable_subprocess_timeout_exceeded()
def src.Mod.AddonManager.AddonManagerTest.app.test_utilities.TestUtilities.test_run_interruptable_subprocess_timeout_exceeded (self, mock_popen)
Exceeding the set timeout gives a CalledProcessError exception
Definition at line 197 of file test_utilities.py.
References src.Mod.AddonManager.addonmanager_utilities.run_interruptable_subprocess().
test_run_interruptable_subprocess_timeout_five_times()
def src.Mod.AddonManager.AddonManagerTest.app.test_utilities.TestUtilities.test_run_interruptable_subprocess_timeout_five_times (self, mock_popen)
Five times is below the limit for an error to be raised
Definition at line 176 of file test_utilities.py.
References src.Mod.AddonManager.addonmanager_utilities.run_interruptable_subprocess().
Member Data Documentation
MODULE
string src.Mod.AddonManager.AddonManagerTest.app.test_utilities.TestUtilities.MODULE = "test_utilities" static
Definition at line 52 of file test_utilities.py.
Referenced by CAMTests.TestPathLog.TestPathLog.test00(), CAMTests.TestPathLog.TestPathLog.test10(), CAMTests.TestPathLog.TestPathLog.test11(), CAMTests.TestPathLog.TestPathLog.test12(), CAMTests.TestPathLog.TestPathLog.test13(), CAMTests.TestPathLog.TestPathLog.test14(), CAMTests.TestPathLog.TestPathLog.test51(), CAMTests.TestPathLog.TestPathLog.test60(), and CAMTests.TestPathLog.TestPathLog.test61().
The documentation for this class was generated from the following file:
test_utilities.py