FreeCAD: Gui::ButtonGroup Class Reference
Gui::ButtonGroup Class Reference
The ButtonGroup class Unlike Qt's QButtonGroup this class allows it that in exclusive mode all buttons can be unchecked.
#include <Widgets.h>
Public Member Functions
ButtonGroup (QObject *parent=nullptr)
void setExclusive (bool on)
bool exclusive () const
Detailed Description
The ButtonGroup class Unlike Qt's QButtonGroup this class allows it that in exclusive mode all buttons can be unchecked.
Definition at line 604 of file Widgets.h.
Constructor & Destructor Documentation
ButtonGroup()
ButtonGroup::ButtonGroup (QObject * parent = nullptr)
Definition at line 1710 of file Widgets.cpp.
References draftgeoutils.intersections::connect(), and exclusive().
Member Function Documentation
exclusive()
bool ButtonGroup::exclusive () const
Definition at line 1733 of file Widgets.cpp.
Referenced by ButtonGroup().
setExclusive()
void ButtonGroup::setExclusive (bool on)
Definition at line 1728 of file Widgets.cpp.
Referenced by SurfaceGui::GeomFillSurface::GeomFillSurface(), SurfaceGui::SectionsPanel::SectionsPanel(), PartDesignGui::TaskDlgPipeParameters::TaskDlgPipeParameters(), FemGui::TaskFemConstraintOnBoundary::TaskFemConstraintOnBoundary(), and SurfaceGui::TaskFilling::TaskFilling().
The documentation for this class was generated from the following files:
Widgets.h
Widgets.cpp