FreeCAD: GCS::ConstraintPerpendicular Class Reference
GCS::ConstraintPerpendicular Class Reference
#include <Constraints.h>
Public Member Functions
ConstraintPerpendicular (Line &l1, Line &l2)
ConstraintPerpendicular (Point &l1p1, Point &l1p2, Point &l2p1, Point &l2p2)
ConstraintType getTypeId () override
void rescale (double coef=1.) override
double error () override
double grad (double *) override
Public Member Functions inherited from GCS::Constraint
Constraint ()
virtual ~Constraint ()
VEC_pD params ()
void redirectParams (const MAP_pD_pD &redirectionmap)
void revertParams ()
void setTag (int tagId)
int getTag ()
void setDriving (bool isdriving)
bool isDriving () const
void setInternalAlignment (Alignment isinternalalignment)
Alignment isInternalAlignment () const
virtual double maxStep (MAP_pD_D &dir, double lim=1.)
int findParamInPvec (double *param)
Additional Inherited Members
Public Types inherited from GCS::Constraint
enum Alignment { Alignment::NoInternalAlignment, Alignment::InternalAlignment }
Protected Attributes inherited from GCS::Constraint
VEC_pD origpvec
VEC_pD pvec
double scale
int tag
bool pvecChangedFlag
bool driving
Alignment internalAlignment
Detailed Description
Definition at line 644 of file Constraints.h.
Constructor & Destructor Documentation
ConstraintPerpendicular() [1/2]
GCS::ConstraintPerpendicular::ConstraintPerpendicular (Line & l1, Line & l2)
Definition at line 1248 of file Constraints.cpp.
References src.Mod.PartDesign.Scripts.Gear::l1, src.Mod.PartDesign.Scripts.Gear::l2, GCS::Constraint::origpvec, GCS::Constraint::pvec, and rescale().
ConstraintPerpendicular() [2/2]
GCS::ConstraintPerpendicular::ConstraintPerpendicular (Point & l1p1, Point & l1p2, Point & l2p1, Point & l2p2)
Definition at line 1262 of file Constraints.cpp.
References GCS::Constraint::origpvec, GCS::Constraint::pvec, rescale(), GCS::Point::x, and GCS::Point::y.
Member Function Documentation
error()
double GCS::ConstraintPerpendicular::error () override virtual
Reimplemented from GCS::Constraint.
Definition at line 1290 of file Constraints.cpp.
getTypeId()
ConstraintType GCS::ConstraintPerpendicular::getTypeId () override virtual
Reimplemented from GCS::Constraint.
Definition at line 1276 of file Constraints.cpp.
References GCS::Perpendicular.
grad()
double GCS::ConstraintPerpendicular::grad (double * param) override virtual
Reimplemented from GCS::Constraint.
Definition at line 1299 of file Constraints.cpp.
References Init::param.
rescale()
void GCS::ConstraintPerpendicular::rescale (double coef = 1.) override virtual
Reimplemented from GCS::Constraint.
Definition at line 1281 of file Constraints.cpp.
References KDL::sqrt().
Referenced by ConstraintPerpendicular().
The documentation for this class was generated from the following files:
Constraints.h
Constraints.cpp