FreeCAD: ifc2x3.ifcpresentationlayerwithstyle Class Reference
ifc2x3.ifcpresentationlayerwithstyle Class Reference
Public Member Functions
def __init__ (self, inherited0__name, inherited1__description, inherited2__assigneditems, inherited3__identifier, layeron, layerfrozen, layerblocked, layerstyles)
def layeron ()
def layerfrozen ()
def layerblocked ()
def layerstyles ()
Public Member Functions inherited from ifc2x3.ifcpresentationlayerassignment
def __init__ (self, name, description, assigneditems, identifier)
def name ()
def description ()
def assigneditems ()
def identifier ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
layeron
layerfrozen
layerblocked
layerstyles
Public Attributes inherited from ifc2x3.ifcpresentationlayerassignment
name
description
assigneditems
identifier
Detailed Description
Entity ifcpresentationlayerwithstyle definition.
:param layeron
:type layeron:LOGICAL
:param layerfrozen
:type layerfrozen:LOGICAL
:param layerblocked
:type layerblocked:LOGICAL
:param layerstyles
:type layerstyles:SET(0,None,'ifcpresentationstyleselect', scope = schema_scope)
Definition at line 34247 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcpresentationlayerwithstyle.__init__ (self, inherited0__name, inherited1__description, inherited2__assigneditems, inherited3__identifier, layeron, layerfrozen, layerblocked, layerstyles)
Definition at line 34262 of file ifc2x3.py.
Member Function Documentation
layerblocked()
def ifc2x3.ifcpresentationlayerwithstyle.layerblocked ()
Definition at line 34298 of file ifc2x3.py.
References ifc2x3.ifcpresentationlayerwithstyle._layerblocked, SCL.TypeChecker.check_type(), and ifc2x3.ifcpresentationlayerwithstyle.layerblocked.
layerfrozen()
def ifc2x3.ifcpresentationlayerwithstyle.layerfrozen ()
Definition at line 34284 of file ifc2x3.py.
References ifc2x3.ifcpresentationlayerwithstyle._layerfrozen, SCL.TypeChecker.check_type(), and ifc2x3.ifcpresentationlayerwithstyle.layerfrozen.
layeron()
def ifc2x3.ifcpresentationlayerwithstyle.layeron ()
Definition at line 34270 of file ifc2x3.py.
References ifc2x3.ifcpresentationlayerwithstyle._layeron, SCL.TypeChecker.check_type(), and ifc2x3.ifcpresentationlayerwithstyle.layeron.
layerstyles()
def ifc2x3.ifcpresentationlayerwithstyle.layerstyles ()
Definition at line 34312 of file ifc2x3.py.
References ifc2x3.ifcpresentationlayerwithstyle._layerstyles, SCL.TypeChecker.check_type(), and ifc2x3.ifcpresentationlayerwithstyle.layerstyles.
Member Data Documentation
layerblocked
ifc2x3.ifcpresentationlayerwithstyle.layerblocked
Definition at line 34266 of file ifc2x3.py.
Referenced by ifc2x3.ifcpresentationlayerwithstyle.layerblocked().
layerfrozen
ifc2x3.ifcpresentationlayerwithstyle.layerfrozen
Definition at line 34265 of file ifc2x3.py.
Referenced by ifc2x3.ifcpresentationlayerwithstyle.layerfrozen().
layeron
ifc2x3.ifcpresentationlayerwithstyle.layeron
Definition at line 34264 of file ifc2x3.py.
Referenced by ifc2x3.ifcpresentationlayerwithstyle.layeron().
layerstyles
ifc2x3.ifcpresentationlayerwithstyle.layerstyles
Definition at line 34267 of file ifc2x3.py.
Referenced by ifc2x3.ifcpresentationlayerwithstyle.layerstyles().
The documentation for this class was generated from the following file:
ifc2x3.py