FreeCAD: Path.Base.Drillable Namespace Reference
Path.Base.Drillable Namespace Reference
Functions
def checkForBlindHole (baseshape, selectedFace)
def isDrillableCylinder (obj, candidate, tooldiameter=None, vector=App.Vector(0, 0, 1))
def isDrillableFace (obj, candidate, tooldiameter=None, vector=App.Vector(0, 0, 1))
def isDrillableEdge (obj, candidate, tooldiameter=None, vector=App.Vector(0, 0, 1), allowPartial=False)
def isDrillable (obj, candidate, tooldiameter=None, vector=App.Vector(0, 0, 1), allowPartial=False)
def compareVecs (vec1, vec2, exact=False)
def getDrillableTargets (obj, ToolDiameter=None, vector=App.Vector(0, 0, 1))
Function Documentation
checkForBlindHole()
def Path.Base.Drillable.checkForBlindHole (baseshape, selectedFace)
check for blind holes, returns the bottom face if found, none
if the hole is a thru-hole
Definition at line 14 of file Drillable.py.
References Path.Post.scripts.grbl_post.type.
Referenced by Path.Base.Drillable.isDrillableCylinder().
compareVecs()
def Path.Base.Drillable.compareVecs (vec1, vec2, exact = False)
compare the two vectors to see if they are aligned for drilling.
if exact is True, vectors must match direction. Otherwise,
alignment can indicate the vectors are the same or exactly opposite
Definition at line 252 of file Drillable.py.
References Path.Log.debug().
Referenced by Path.Base.Drillable.isDrillableCylinder(), Path.Base.Drillable.isDrillableEdge(), and Path.Base.Drillable.isDrillableFace().
getDrillableTargets()
def Path.Base.Drillable.getDrillableTargets (obj, ToolDiameter = None, vector = App.Vector(0, 0, 1))
Returns a list of tuples for drillable subelements from the given object
[(obj,'Face1'),(obj,'Face3')]
Finds cylindrical faces that are larger than the tool diameter (if provided) and
oriented with the vector.  If vector is None, all drillables are returned
Definition at line 270 of file Drillable.py.
References Path.Log.debug(), and Path.Base.Drillable.isDrillable().
isDrillable()
def Path.Base.Drillable.isDrillable (obj, candidate, tooldiameter = None, vector = App.Vector(0, 0, 1), allowPartial = False)
Checks candidates to see if they can be drilled at the given vector.
Candidates can be either faces - circular or cylindrical or circular edges.
The tooldiameter can be optionally passed.  if passed, the check will return
False for any holes smaller than the tooldiameter.
vector defaults to (0,0,1) which aligns with the Z axis.  By default will return False
for any candidate not drillable in this orientation.  Pass 'None' to vector to test whether
the hole is drillable at any orientation.
allowPartial will permit selecting partial circular arcs manually.
obj=Shape
candidate = Face or Edge
tooldiameter=float
vector=App.Vector or None
allowPartial boolean
Definition at line 200 of file Drillable.py.
References Path.Log.debug(), Path.Base.Drillable.isDrillableCylinder(), Path.Base.Drillable.isDrillableEdge(), Path.Base.Drillable.isDrillableFace(), and Path.Post.scripts.grbl_post.type.
Referenced by Path.Base.Drillable.getDrillableTargets().
isDrillableCylinder()
def Path.Base.Drillable.isDrillableCylinder (obj, candidate, tooldiameter = None, vector = App.Vector(0, 0, 1))
checks if a candidate cylindrical face is drillable
Definition at line 39 of file Drillable.py.
References Path.Base.Drillable.checkForBlindHole(), Path.Base.Drillable.compareVecs(), Path.Log.debug(), and Path.Log.track().
Referenced by Path.Base.Drillable.isDrillable().
isDrillableEdge()
def Path.Base.Drillable.isDrillableEdge (obj, candidate, tooldiameter = None, vector = App.Vector(0, 0, 1), allowPartial = False)
checks if an edge is drillable
Definition at line 159 of file Drillable.py.
References Path.Base.Drillable.compareVecs(), and Path.Log.debug().
Referenced by Path.Base.Drillable.isDrillable().
isDrillableFace()
def Path.Base.Drillable.isDrillableFace (obj, candidate, tooldiameter = None, vector = App.Vector(0, 0, 1))
checks if a flat face or edge is drillable
Definition at line 112 of file Drillable.py.
References Path.Base.Drillable.compareVecs(), Path.Log.debug(), and Path.Post.scripts.grbl_post.type.
Referenced by Path.Base.Drillable.isDrillable().