FreeCAD: Path.Post.UtilsExport Namespace Reference
Path.Post.UtilsExport Namespace Reference
Functions
None check_canned_cycles (Values values)
str determine_coolant_mode (obj)
None output_coolant_off (Values values, Gcode gcode, str coolant_mode)
None output_coolant_on (Values values, Gcode gcode, str coolant_mode)
None output_end_bcnc (Values values, Gcode gcode)
None output_header (Values values, Gcode gcode)
None output_motion_mode (Values values, Gcode gcode)
None output_postamble_header (Values values, Gcode gcode)
None output_postamble (Values values, Gcode gcode)
None output_postop (Values values, Gcode gcode, obj)
None output_preamble (Values values, Gcode gcode)
None output_preop (Values values, Gcode gcode, obj)
None output_return_to (Values values, Gcode gcode)
None output_safetyblock (Values values, Gcode gcode)
None output_start_bcnc (Values values, Gcode gcode, obj)
None output_tool_list (Values values, Gcode gcode, objectslist)
None output_tool_return (Values values, Gcode gcode)
None output_units (Values values, Gcode gcode)
str export_common (Values values, objectslist, str filename)
Variables
Gcode
Values
Function Documentation
check_canned_cycles()
None Path.Post.UtilsExport.check_canned_cycles (Values values)
Check canned cycles for drilling.
Definition at line 44 of file UtilsExport.py.
Referenced by Path.Post.UtilsExport.export_common().
determine_coolant_mode()
str Path.Post.UtilsExport.determine_coolant_mode (obj)
Determine the coolant mode.
Definition at line 53 of file UtilsExport.py.
Referenced by Path.Post.UtilsExport.export_common().
export_common()
str Path.Post.UtilsExport.export_common (Values values, objectslist, str filename)
Do the common parts of postprocessing the objects in objectslist to filename.
Definition at line 291 of file UtilsExport.py.
References Path.Post.UtilsExport.check_canned_cycles(), Path.Post.UtilsExport.determine_coolant_mode(), AssemblyImport.open(), Path.Post.UtilsExport.output_coolant_off(), Path.Post.UtilsExport.output_coolant_on(), Path.Post.UtilsExport.output_end_bcnc(), Path.Post.UtilsExport.output_header(), Path.Post.UtilsExport.output_motion_mode(), Path.Post.UtilsExport.output_postamble(), Path.Post.UtilsExport.output_postamble_header(), Path.Post.UtilsExport.output_postop(), Path.Post.UtilsExport.output_preamble(), Path.Post.UtilsExport.output_preop(), Path.Post.UtilsExport.output_return_to(), Path.Post.UtilsExport.output_safetyblock(), Path.Post.UtilsExport.output_start_bcnc(), Path.Post.UtilsExport.output_tool_list(), Path.Post.UtilsExport.output_tool_return(), and Path.Post.UtilsExport.output_units().
output_coolant_off()
None Path.Post.UtilsExport.output_coolant_off (Values values, Gcode gcode, str coolant_mode)
Output the commands to turn coolant off if necessary.
Definition at line 62 of file UtilsExport.py.
Referenced by Path.Post.UtilsExport.export_common().
output_coolant_on()
None Path.Post.UtilsExport.output_coolant_on (Values values, Gcode gcode, str coolant_mode)
Output the commands to turn coolant on if necessary.
Definition at line 74 of file UtilsExport.py.
Referenced by Path.Post.UtilsExport.export_common().
output_end_bcnc()
None Path.Post.UtilsExport.output_end_bcnc (Values values, Gcode gcode)
Output the ending BCNC header.
Definition at line 89 of file UtilsExport.py.
Referenced by Path.Post.UtilsExport.export_common().
output_header()
None Path.Post.UtilsExport.output_header (Values values, Gcode gcode)
Output the header.
Definition at line 103 of file UtilsExport.py.
Referenced by Path.Post.UtilsExport.export_common().
output_motion_mode()
None Path.Post.UtilsExport.output_motion_mode (Values values, Gcode gcode)
Verify if PREAMBLE or SAFETYBLOCK have changed MOTION_MODE.
Definition at line 127 of file UtilsExport.py.
Referenced by Path.Post.UtilsExport.export_common().
output_postamble()
None Path.Post.UtilsExport.output_postamble (Values values, Gcode gcode)
Output the postamble.
Definition at line 149 of file UtilsExport.py.
Referenced by Path.Post.UtilsExport.export_common().
output_postamble_header()
None Path.Post.UtilsExport.output_postamble_header (Values values, Gcode gcode)
Output the postamble header.
Definition at line 139 of file UtilsExport.py.
Referenced by Path.Post.UtilsExport.export_common().
output_postop()
None Path.Post.UtilsExport.output_postop (Values values, Gcode gcode, obj)
Output the post-operation information.
Definition at line 158 of file UtilsExport.py.
Referenced by Path.Post.UtilsExport.export_common().
output_preamble()
None Path.Post.UtilsExport.output_preamble (Values values, Gcode gcode)
Output the preamble.
Definition at line 173 of file UtilsExport.py.
Referenced by Path.Post.UtilsExport.export_common().
output_preop()
None Path.Post.UtilsExport.output_preop (Values values, Gcode gcode, obj)
Output the pre-operation information.
Definition at line 186 of file UtilsExport.py.
Referenced by Path.Post.UtilsExport.export_common().
output_return_to()
None Path.Post.UtilsExport.output_return_to (Values values, Gcode gcode)
Output the RETURN_TO command.
Definition at line 213 of file UtilsExport.py.
Referenced by Path.Post.UtilsExport.export_common().
output_safetyblock()
None Path.Post.UtilsExport.output_safetyblock (Values values, Gcode gcode)
Output the safety block.
Definition at line 231 of file UtilsExport.py.
Referenced by Path.Post.UtilsExport.export_common().
output_start_bcnc()
None Path.Post.UtilsExport.output_start_bcnc (Values values, Gcode gcode, obj)
Output the starting BCNC header.
Definition at line 240 of file UtilsExport.py.
Referenced by Path.Post.UtilsExport.export_common().
output_tool_list()
None Path.Post.UtilsExport.output_tool_list (Values values, Gcode gcode, objectslist)
Output a list of the tools used in the objects.
Definition at line 254 of file UtilsExport.py.
Referenced by Path.Post.UtilsExport.export_common().
output_tool_return()
None Path.Post.UtilsExport.output_tool_return (Values values, Gcode gcode)
Output the tool return block.
Definition at line 266 of file UtilsExport.py.
Referenced by Path.Post.UtilsExport.export_common().
output_units()
None Path.Post.UtilsExport.output_units (Values values, Gcode gcode)
Verify if PREAMBLE or SAFETYBLOCK have changed UNITS.
Definition at line 275 of file UtilsExport.py.
Referenced by Path.Post.UtilsExport.export_common().
Variable Documentation
Gcode
Path.Post.UtilsExport.Gcode
Definition at line 40 of file UtilsExport.py.
Values
Path.Post.UtilsExport.Values
Definition at line 41 of file UtilsExport.py.