FreeCAD: TechDrawGui::TaskProjection Class Reference
TechDrawGui::TaskProjection Class Reference
#include <TaskProjection.h>
Public Member Functions
TaskProjection ()
~TaskProjection () override
bool accept ()
bool reject ()
virtual bool isAllowedAlterDocument () const
Detailed Description
Definition at line 44 of file TaskProjection.h.
Constructor & Destructor Documentation
TaskProjection()
TaskProjection::TaskProjection ()
Definition at line 48 of file TaskProjection.cpp.
~TaskProjection()
TaskProjection::~TaskProjection () override
Definition at line 55 of file TaskProjection.cpp.
Member Function Documentation
accept()
bool TaskProjection::accept ()
Definition at line 60 of file TaskProjection.cpp.
References Gui::Application::activeDocument(), Gui::Command::addModule(), Gui::Command::commitCommand(), Gui::Command::Doc, doCommand, Base::BaseClass::getClassTypeId(), Gui::getMainWindow(), Gui::Document::getMDIViewsOfType(), Gui::SelectionSingleton::getObjectsOfType(), Gui::Application::Instance, Gui::Command::openCommand(), Gui::Selection(), Gui::Command::updateActive(), OfflineRenderingUtils::viewer(), Path.Log::warning(), MovieTool::x, and MovieTool::y.
Referenced by TechDrawGui::TaskDlgProjection::accept().
isAllowedAlterDocument()
virtual bool TechDrawGui::TaskProjection::isAllowedAlterDocument () const inline virtual
Definition at line 56 of file TaskProjection.h.
reject()
bool TaskProjection::reject ()
Definition at line 118 of file TaskProjection.cpp.
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and TechDrawGui::TaskDlgProjection::reject().
The documentation for this class was generated from the following files:
TaskProjection.h
TaskProjection.cpp