FreeCAD: src.Mod.PartDesign.fcsprocket.sprocket Namespace Reference
src.Mod.PartDesign.fcsprocket.sprocket Namespace Reference
Functions
def CreateSprocket (w, P, N, Dr)
def rotate (pt, rads)
Function Documentation
CreateSprocket()
def src.Mod.PartDesign.fcsprocket.sprocket.CreateSprocket (w, P, N, Dr)
Create a sprocket
w is the wirebuilder object (in which the sprocket will be constructed)
P is the chain pitch
N is the number of teeth
Dr is the roller diameter
Remaining variables can be found in Standard Handbook of Chains
Definition at line 21 of file sprocket.py.
References KDL.asin(), KDL.atan(), KDL.cos(), KDL.sin(), KDL.sqrt(), and KDL.tan().
rotate()
def src.Mod.PartDesign.fcsprocket.sprocket.rotate (pt, rads)
rotate pt by rads radians about origin
Definition at line 126 of file sprocket.py.
References KDL.cos(), and KDL.sin().