FreeCAD: Gui::LocationUi< Ui > Class Template Reference
Gui::LocationUi< Ui > Class Template Reference
#include <InputVector.h>
Public Member Functions
LocationUi (QDialog *dlg)
~LocationUi ()=default
void retranslate (QDialog *dlg)
void setPosition (const Base::Vector3d &v)
Base::Vector3d getPosition () const
Base::Vector3d getDirection () const
void setDirection (const Base::Vector3d &dir)
bool directionActivated (LocationDialog *dlg, int index)
Detailed Description
template<class Ui>
class Gui::LocationUi< Ui >
This template class does basically the same as LocationDialogUi unless that it doesn inherit from a widget but only from the UI_-generated class. Thus, this class can be used as composition in dialog-based classes without including the ui_-generated header file. The Ui_-class can simply be forward declared, then.
Author
Werner Mayer
Definition at line 242 of file InputVector.h.
Constructor & Destructor Documentation
LocationUi()
template<class Ui > Gui::LocationUi< Ui >::LocationUi (QDialog * dlg) inline
Definition at line 245 of file InputVector.h.
References Gui::LocationUi< Ui >::retranslate().
~LocationUi()
template<class Ui > Gui::LocationUi< Ui >::~LocationUi () default
Member Function Documentation
directionActivated()
template<class Ui > bool Gui::LocationUi< Ui >::directionActivated (LocationDialog * dlg, int index) inline
Definition at line 333 of file InputVector.h.
References Base::Vector3< double >::epsilon(), Gui::LocationDialog::getUserDirection(), Base::Vector3< float_type >::Length(), and Gui::LocationUi< Ui >::setDirection().
getDirection()
template<class Ui > Base::Vector3d Gui::LocationUi< Ui >::getDirection () const inline
Definition at line 294 of file InputVector.h.
getPosition()
template<class Ui > Base::Vector3d Gui::LocationUi< Ui >::getPosition () const inline
Definition at line 287 of file InputVector.h.
retranslate()
template<class Ui > void Gui::LocationUi< Ui >::retranslate (QDialog * dlg) inline
Definition at line 252 of file InputVector.h.
References NavigationIndicatorGui::retranslateUi(), and src.Mod.AddonManager.Addon::translate.
Referenced by Gui::LocationUi< Ui >::LocationUi().
setDirection()
template<class Ui > void Gui::LocationUi< Ui >::setDirection (const Base::Vector3d & dir) inline
Definition at line 306 of file InputVector.h.
References femsolver.report::display(), Base::Vector3< double >::epsilon(), SplineSurface::i, Base::Vector3< float_type >::Length(), toolbit-attributes::val, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by Gui::LocationUi< Ui >::directionActivated().
setPosition()
template<class Ui > void Gui::LocationUi< Ui >::setPosition (const Base::Vector3d & v) inline
Definition at line 280 of file InputVector.h.
References TestSpreadsheet::v.
The documentation for this class was generated from the following file:
InputVector.h