FreeCAD: MeshGui::SoFCMeshSegmentShape Class Reference
MeshGui::SoFCMeshSegmentShape Class Reference
#include <SoFCMeshObject.h>
Public Member Functions
SoFCMeshSegmentShape ()
Static Public Member Functions
static void initClass ()
Public Attributes
SoSFUInt32 index
unsigned int renderTriangleLimit
Protected Member Functions
void GLRender (SoGLRenderAction *action) override
void computeBBox (SoAction *action, SbBox3f &box, SbVec3f &center) override
void getPrimitiveCount (SoGetPrimitiveCountAction *action) override
void generatePrimitives (SoAction *action) override
~SoFCMeshSegmentShape () override=default
Detailed Description
Definition at line 243 of file SoFCMeshObject.h.
Constructor & Destructor Documentation
SoFCMeshSegmentShape()
SoFCMeshSegmentShape::SoFCMeshSegmentShape ()
Definition at line 1237 of file SoFCMeshObject.cpp.
References index.
~SoFCMeshSegmentShape()
MeshGui::SoFCMeshSegmentShape::~SoFCMeshSegmentShape () override protected default
Member Function Documentation
computeBBox()
void SoFCMeshSegmentShape::computeBBox (SoAction * action, SbBox3f & box, SbVec3f & center) override protected
Sets the bounding box of the mesh to box and its center to center.
Definition at line 1594 of file SoFCMeshObject.cpp.
References MeshCore::MeshFacet::_aulPoints, Path.Post.scripts.dynapath_4060_post::action, Base::BoundBox3< Precision >::Add(), MengerSponge::box, exportCSG::center(), MeshGui::SoFCMeshObjectElement::get(), Base::BoundBox3< Precision >::GetCenter(), Mesh::Segment::getIndices(), index, Base::BoundBox3< Precision >::MaxX, Base::BoundBox3< Precision >::MaxY, Base::BoundBox3< Precision >::MaxZ, Mesh2Shape::mesh, Base::BoundBox3< Precision >::MinX, Base::BoundBox3< Precision >::MinY, and Base::BoundBox3< Precision >::MinZ.
generatePrimitives()
void SoFCMeshSegmentShape::generatePrimitives (SoAction * action) override protected
Sets the point indices, the geometric points and the normal for each triangle. If the number of triangles exceeds renderTriangleLimit then only a triangulation of a rough model is filled in instead. This is due to performance issues.
See also
createTriangleDetail().
Definition at line 1505 of file SoFCMeshObject.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Base::Console(), SCL.SimpleDataTypes::f, MeshGui::SoFCMeshObjectElement::get(), Base::ConsoleSingleton::Log(), Mesh2Shape::mesh, sbvec3f(), draftgeoutils.general::v1(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
getPrimitiveCount()
void SoFCMeshSegmentShape::getPrimitiveCount (SoGetPrimitiveCountAction * action) override protected
Adds the number of the triangles to the SoGetPrimitiveCountAction.
Definition at line 1627 of file SoFCMeshObject.cpp.
References Path.Post.scripts.dynapath_4060_post::action, MeshGui::SoFCMeshObjectElement::get(), Mesh::Segment::getIndices(), and Mesh2Shape::mesh.
GLRender()
void SoFCMeshSegmentShape::GLRender (SoGLRenderAction * action) override protected
Either renders the complete mesh or only a subset of the points.
Definition at line 1247 of file SoFCMeshObject.cpp.
References Path.Post.scripts.dynapath_4060_post::action, MeshGui::SoFCMeshObjectElement::get(), Gui::SoFCInteractiveElement::get(), and Mesh2Shape::mesh.
initClass()
void SoFCMeshSegmentShape::initClass () static
Definition at line 1232 of file SoFCMeshObject.cpp.
Referenced by PyMOD_INIT_FUNC().
Member Data Documentation
index
SoSFUInt32 MeshGui::SoFCMeshSegmentShape::index
Definition at line 253 of file SoFCMeshObject.h.
Referenced by src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::addSegment(), src.Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::begin(), computeBBox(), src.Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::interval(), src.Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::length(), SoFCMeshSegmentShape(), automotive_design.index_expression::wr1(), and automotive_design.index_expression::wr2().
renderTriangleLimit
unsigned int MeshGui::SoFCMeshSegmentShape::renderTriangleLimit
Definition at line 254 of file SoFCMeshObject.h.
The documentation for this class was generated from the following files:
SoFCMeshObject.h
SoFCMeshObject.cpp