FreeCAD: Part::Geom2dPoint Class Reference
Part::Geom2dPoint Class Reference
#include <Geometry2d.h>
Public Member Functions
Geom2dPoint ()
Geom2dPoint (const Handle(Geom2d_CartesianPoint)&)
Geom2dPoint (const Base::Vector2d &)
~Geom2dPoint () override
Geometry2d * clone () const override
returns a cloned object
TopoDS_Shape toShape () const override
unsigned int getMemSize () const override
void Save (Base::Writer &) const override
void Restore (Base::XMLReader &) override
PyObject * getPyObject () override
const Handle (Geom2d_Geometry) &handle() const override
Base::Vector2d getPoint () const
void setPoint (const Base::Vector2d &)
Public Member Functions inherited from Part::Geometry2d
~Geometry2d () override
Geometry2d (const Geometry2d &)=delete
Geometry2d & operator= (const Geometry2d &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Protected Member Functions inherited from Part::Geometry2d
Geometry2d ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 94 of file Geometry2d.h.
Constructor & Destructor Documentation
Geom2dPoint() [1/3]
Geom2dPoint::Geom2dPoint ()
Definition at line 112 of file Geometry2d.cpp.
Geom2dPoint() [2/3]
Geom2dPoint::Geom2dPoint (const Handle(Geom2d_CartesianPoint)& p)
Definition at line 117 of file Geometry2d.cpp.
References Handle(), and buildPsets::p.
Geom2dPoint() [3/3]
Geom2dPoint::Geom2dPoint (const Base::Vector2d & p)
Definition at line 122 of file Geometry2d.cpp.
References buildPsets::p.
~Geom2dPoint()
Geom2dPoint::~Geom2dPoint () override default
Member Function Documentation
clone()
Geometry2d* Part::Geom2dPoint::clone () const override virtual
returns a cloned object
Implements Part::Geometry2d.
Referenced by src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::integrated().
getMemSize()
unsigned int Geom2dPoint::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Reimplemented from Part::Geometry2d.
Definition at line 161 of file Geometry2d.cpp.
getPoint()
Base::Vector2d Part::Geom2dPoint::getPoint () const
getPyObject()
PyObject * Geom2dPoint::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Definition at line 196 of file Geometry2d.cpp.
References SCL.SimpleDataTypes::c, Handle(), Py::new_reference_to(), and Path.Geom::xy().
Handle()
const Part::Geom2dPoint::Handle (Geom2d_Geometry) const & override virtual
Implements Part::Geometry2d.
Restore()
void Geom2dPoint::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Reimplemented from Part::Geometry2d.
Definition at line 180 of file Geometry2d.cpp.
References TechDrawTools.TaskFillTemplateFields::reader, Part::Geometry2d::Restore(), DrawingExample::X, and DrawingExample::Y.
Save()
void Geom2dPoint::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Reimplemented from Part::Geometry2d.
Definition at line 166 of file Geometry2d.cpp.
References draftguitools.gui_tool_utils::getPoint, Base::Writer::ind(), Part::Geometry2d::Save(), Base::Writer::Stream(), Point::x, and Point::y.
setPoint()
void Part::Geom2dPoint::setPoint (const Base::Vector2d &)
toShape()
TopoDS_Shape Geom2dPoint::toShape () const override virtual
Implements Part::Geometry2d.
Definition at line 129 of file Geometry2d.cpp.
References SCL.SimpleDataTypes::c, Handle(), and Path.Geom::xy().
The documentation for this class was generated from the following files:
Geometry2d.h
Geometry2d.cpp