FreeCAD: PartDesignGui::TaskDraftParameters Class Reference
PartDesignGui::TaskDraftParameters Class Reference
#include <TaskDraftParameters.h>
Public Member Functions
TaskDraftParameters (ViewProviderDressUp *DressUpView, QWidget *parent=nullptr)
~TaskDraftParameters () override
void apply () override
Apply the changes made to the object to it.
double getAngle () const
bool getReversed () const
const std::vector< std::string > getFaces () const
void getPlane (App::DocumentObject *&obj, std::vector< std::string > &sub) const
void getLine (App::DocumentObject *&obj, std::vector< std::string > &sub) const
Public Member Functions inherited from PartDesignGui::TaskDressUpParameters
TaskDressUpParameters (ViewProviderDressUp *DressUpView, bool selectEdges, bool selectFaces, QWidget *parent=nullptr)
~TaskDressUpParameters () override
const std::vector< std::string > getReferences () const
Part::Feature * getBase () const
void hideObject ()
void showObject ()
void setupTransaction ()
int getTransactionID () const
bool event (QEvent *event) override
Public Member Functions inherited from Gui::TaskView::TaskBox
TaskBox (QWidget *parent=nullptr)
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
QSize minimumSizeHint () const override
~TaskBox () override
void hideGroupBox ()
bool isGroupVisible () const
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (QWidget *parent=nullptr)
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
QBoxLayout * groupLayout ()
void setScheme (ActionPanelScheme *pointer)
bool isExpandable () const
bool hasHeader () const
QString headerText () const
QSize minimumSizeHint () const override
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Protected Member Functions
void setButtons (const selectionModes mode) override
void changeEvent (QEvent *e) override
void onSelectionChanged (const Gui::SelectionChanges &msg) override
Protected Member Functions inherited from PartDesignGui::TaskDressUpParameters
void referenceSelected (const Gui::SelectionChanges &msg, QListWidget *widget)
void keyPressEvent (QKeyEvent *ke) override
void hideOnError ()
void addAllEdges (QListWidget *listWidget)
void deleteRef (QListWidget *listWidget)
void updateFeature (PartDesign::DressUp *pcDressUp, const std::vector< std::string > &refs)
void setSelectionMode (selectionModes mode)
ViewProviderDressUp * getDressUpView () const
template<typename T = App::DocumentObject>
T * getObject () const
Protected Member Functions inherited from Gui::TaskView::TaskBox
void showEvent (QShowEvent *) override
void actionEvent (QActionEvent *) override
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
void paintEvent (QPaintEvent *event) override
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void showHide ()
void setExpandable (bool expandable=true)
void setHeader (bool enable=true)
void setHeaderText (const QString &title)
void setHeaderIcon (const QPixmap &icon)
Protected Types inherited from PartDesignGui::TaskDressUpParameters
enum selectionModes { none, refSel, plane, line }
Protected Slots inherited from PartDesignGui::TaskDressUpParameters
void onButtonRefSel (const bool checked)
void doubleClicked (QListWidgetItem *item)
void setSelection (QListWidgetItem *current)
void itemClickedTimeout ()
virtual void onRefDeleted ()=0
void createDeleteAction (QListWidget *parentList)
void createAddAllEdgesAction (QListWidget *parentList)
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Static Protected Member Functions inherited from PartDesignGui::TaskDressUpParameters
static void removeItemFromListWidget (QListWidget *widget, const char *itemstr)
static const QString btnPreviewStr ()
static const QString btnSelectStr ()
Protected Attributes inherited from PartDesignGui::TaskDressUpParameters
bool wasDoubleClicked = false
QWidget * proxy
QAction * deleteAction
QAction * addAllEdgesAction
bool allowFaces
bool allowEdges
selectionModes selectionMode
int transactionID
Protected Attributes inherited from QSint::ActionGroup
double m_foldStep
double m_foldDelta
double m_fullHeight
double m_tempHeight
int m_foldDirection
QPixmap m_foldPixmap
class TaskHeader * myHeader
class TaskGroup * myGroup
QWidget * myDummy
ActionPanelScheme * myScheme
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Detailed Description
Definition at line 35 of file TaskDraftParameters.h.
Constructor & Destructor Documentation
TaskDraftParameters()
TaskDraftParameters::TaskDraftParameters (ViewProviderDressUp * DressUpView, QWidget * parent = nullptr) explicit
Definition at line 51 of file TaskDraftParameters.cpp.
References a, PartDesign::Draft::Angle, PartDesign::DressUp::Base, draftgeoutils.intersections::connect(), PartDesignGui::TaskDressUpParameters::createDeleteAction(), PartDesignGui::TaskDressUpParameters::deleteAction, PartDesignGui::TaskDressUpParameters::doubleClicked(), App::PropertyQuantityConstraint::getMaximum(), App::PropertyQuantityConstraint::getMinimum(), Gui::ViewProviderDocumentObject::getObject(), PartDesignGui::getRefStr(), App::PropertyLinkSub::getSubValues(), App::PropertyQuantity::getValue(), App::PropertyLinkSub::getValue(), App::PropertyBool::getValue(), QSint::ActionGroup::groupLayout(), PartDesignGui::TaskDressUpParameters::hideOnError(), PartDesign::Draft::NeutralPlane, PartDesignGui::TaskDressUpParameters::onButtonRefSel(), PartDesignGui::TaskDressUpParameters::proxy, PartDesign::Draft::PullDirection, PartDesignGui::TaskDressUpParameters::refSel, PartDesign::Draft::Reversed, PartDesignGui::TaskDressUpParameters::setSelection(), PartDesignGui::TaskDressUpParameters::setSelectionMode(), and Gui::QuantitySpinBox::valueChanged().
~TaskDraftParameters()
TaskDraftParameters::~TaskDraftParameters () override
Definition at line 263 of file TaskDraftParameters.cpp.
References Gui::SelectionSingleton::clearSelection(), SCL.SimpleDataTypes::e, Gui::SelectionSingleton::rmvSelectionGate(), and Gui::Selection().
Member Function Documentation
apply()
void TaskDraftParameters::apply () override virtual
Apply the changes made to the object to it.
Reimplemented from PartDesignGui::TaskDressUpParameters.
Definition at line 283 of file TaskDraftParameters.cpp.
References PartDesignGui::TaskDressUpParameters::apply(), Base::Console(), and Base::ConsoleSingleton::Warning().
changeEvent()
void TaskDraftParameters::changeEvent (QEvent * e) override protected
Definition at line 275 of file TaskDraftParameters.cpp.
References SCL.SimpleDataTypes::e, and PartDesignGui::TaskDressUpParameters::proxy.
getAngle()
double TaskDraftParameters::getAngle () const
Definition at line 241 of file TaskDraftParameters.cpp.
Referenced by PartDesignGui::TaskDlgDraftParameters::accept().
getFaces()
const std::vector<std::string> PartDesignGui::TaskDraftParameters::getFaces () const
getLine()
void TaskDraftParameters::getLine (App::DocumentObject *& obj, std::vector< std::string > & sub) const
Definition at line 219 of file TaskDraftParameters.cpp.
References PartDesignGui::TaskDressUpParameters::getObject().
Referenced by PartDesignGui::TaskDlgDraftParameters::accept().
getPlane()
void TaskDraftParameters::getPlane (App::DocumentObject *& obj, std::vector< std::string > & sub) const
Definition at line 209 of file TaskDraftParameters.cpp.
References PartDesignGui::TaskDressUpParameters::getObject().
Referenced by PartDesignGui::TaskDlgDraftParameters::accept().
getReversed()
bool TaskDraftParameters::getReversed () const
Definition at line 258 of file TaskDraftParameters.cpp.
Referenced by PartDesignGui::TaskDlgDraftParameters::accept().
onSelectionChanged()
void TaskDraftParameters::onSelectionChanged (const Gui::SelectionChanges & msg) override protected virtual
Implements Gui::SelectionObserver.
Definition at line 123 of file TaskDraftParameters.cpp.
References Gui::SelectionChanges::AddSelection, PartDesignGui::TaskDressUpParameters::getDressUpView(), PartDesignGui::getReferencedSelection(), PartDesignGui::getRefStr(), PartDesignGui::TaskDressUpParameters::hideOnError(), PartDesignGui::ViewProviderDressUp::highlightReferences(), PartDesignGui::TaskDressUpParameters::line, Path.Op.Surface::msg, PartDesignGui::TaskDressUpParameters::plane, PartDesignGui::TaskDressUpParameters::referenceSelected(), PartDesignGui::TaskDressUpParameters::refSel, PartDesignGui::TaskDressUpParameters::selectionMode, and PartDesignGui::TaskDressUpParameters::setupTransaction().
setButtons()
void TaskDraftParameters::setButtons (const selectionModes mode) override protected virtual
Implements PartDesignGui::TaskDressUpParameters.
Definition at line 171 of file TaskDraftParameters.cpp.
References PartDesignGui::TaskDressUpParameters::btnPreviewStr(), PartDesignGui::TaskDressUpParameters::btnSelectStr(), PartDesignGui::TaskDressUpParameters::line, PartDesignGui::TaskDressUpParameters::plane, and PartDesignGui::TaskDressUpParameters::refSel.
The documentation for this class was generated from the following files:
TaskDraftParameters.h
TaskDraftParameters.cpp