FreeCAD: TechDrawGui::DlgStringListEditor Class Reference
TechDrawGui::DlgStringListEditor Class Reference
#include <DlgStringListEditor.h>
Public Slots
void slotItemActivated (QListWidgetItem *item)
void slotAddItem ()
void slotRemoveItem ()
Public Member Functions
DlgStringListEditor (const std::vector< std::string > texts, QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~DlgStringListEditor () override
std::vector< std::string > getTexts () const
void accept () override
void reject () override
Detailed Description
Definition at line 36 of file DlgStringListEditor.h.
Constructor & Destructor Documentation
DlgStringListEditor()
DlgStringListEditor::DlgStringListEditor (const std::vector< std::string > texts, QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags())
Definition at line 36 of file DlgStringListEditor.cpp.
References accept(), draftgeoutils.intersections::connect(), reject(), slotAddItem(), slotItemActivated(), and slotRemoveItem().
~DlgStringListEditor()
DlgStringListEditor::~DlgStringListEditor () override
Destroys the object and frees any allocated resources
Definition at line 59 of file DlgStringListEditor.cpp.
Member Function Documentation
accept()
void DlgStringListEditor::accept () override
Definition at line 134 of file DlgStringListEditor.cpp.
Referenced by DlgStringListEditor().
getTexts()
std::vector< std::string > DlgStringListEditor::getTexts () const
Definition at line 117 of file DlgStringListEditor.cpp.
Referenced by TechDrawGui::QGIViewAnnotation::mouseDoubleClickEvent().
reject()
void DlgStringListEditor::reject () override
Definition at line 139 of file DlgStringListEditor.cpp.
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and DlgStringListEditor().
slotAddItem
void DlgStringListEditor::slotAddItem () slot
Definition at line 87 of file DlgStringListEditor.cpp.
Referenced by DlgStringListEditor().
slotItemActivated
void DlgStringListEditor::slotItemActivated (QListWidgetItem * item) slot
Definition at line 82 of file DlgStringListEditor.cpp.
Referenced by DlgStringListEditor().
slotRemoveItem
void DlgStringListEditor::slotRemoveItem () slot
Definition at line 105 of file DlgStringListEditor.cpp.
Referenced by DlgStringListEditor().
The documentation for this class was generated from the following files:
DlgStringListEditor.h
DlgStringListEditor.cpp