FreeCAD: FemGui::ShapeNodes Namespace Reference
FemGui::ShapeNodes Namespace Reference
Functions
SoGroup * postBox ()
SoGroup * postCylinder ()
SoGroup * postPlane ()
SoGroup * postSphere ()
Function Documentation
postBox()
SoGroup * FemGui::ShapeNodes::postBox ()
Definition at line 1147 of file ViewProviderFemPostFunction.cpp.
References toolbit-attributes::group.
Referenced by FemGui::ViewProviderFemPostBoxFunction::ViewProviderFemPostBoxFunction().
postCylinder()
SoGroup * FemGui::ShapeNodes::postCylinder ()
Definition at line 1189 of file ViewProviderFemPostFunction.cpp.
References KDL::cos(), toolbit-attributes::group, SplineSurface::i, M_PI, and KDL::sin().
Referenced by FemGui::ViewProviderFemPostCylinderFunction::ViewProviderFemPostCylinderFunction().
postPlane()
SoGroup * FemGui::ShapeNodes::postPlane ()
Definition at line 1236 of file ViewProviderFemPostFunction.cpp.
References toolbit-attributes::group.
Referenced by FemGui::ViewProviderFemPostPlaneFunction::ViewProviderFemPostPlaneFunction().
postSphere()
SoGroup * FemGui::ShapeNodes::postSphere ()
Definition at line 1254 of file ViewProviderFemPostFunction.cpp.
References KDL::cos(), toolbit-attributes::group, SplineSurface::i, M_PI, and KDL::sin().
Referenced by FemGui::ViewProviderFemPostSphereFunction::ViewProviderFemPostSphereFunction().