FreeCAD: Part::GeometryPersistenceExtension Class Reference
Part::GeometryPersistenceExtension Class Reference
#include <GeometryExtension.h>
Public Member Functions
~GeometryPersistenceExtension () override=default
void Save (Base::Writer &) const
void Restore (Base::XMLReader &)
bool isSame (const GeometryPersistenceExtension &other) const
Public Member Functions inherited from Part::GeometryExtension
~GeometryExtension () override=default
virtual std::unique_ptr< GeometryExtension > copy () const =0
PyObject * getPyObject () override=0
PyObject * copyPyObject () const
void setName (const std::string &str)
const std::string & getName () const
virtual void notifyAttachment (Part::Geometry *)
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Member Functions
virtual void restoreAttributes (Base::XMLReader &)
virtual void saveAttributes (Base::Writer &writer) const
Protected Member Functions inherited from Part::GeometryExtension
GeometryExtension ()
GeometryExtension (const GeometryExtension &obj)=default
GeometryExtension & operator= (const GeometryExtension &obj)=default
virtual void copyAttributes (Part::GeometryExtension *cpy) const
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 88 of file GeometryExtension.h.
Constructor & Destructor Documentation
~GeometryPersistenceExtension()
Part::GeometryPersistenceExtension::~GeometryPersistenceExtension () override default
Member Function Documentation
isSame()
bool GeometryPersistenceExtension::isSame (const GeometryPersistenceExtension & other) const
Definition at line 82 of file GeometryExtension.cpp.
References Base::StringWriter::getString(), and Save().
Restore()
void GeometryPersistenceExtension::Restore (Base::XMLReader & reader)
Definition at line 77 of file GeometryExtension.cpp.
References TechDrawTools.TaskFillTemplateFields::reader, and restoreAttributes().
Referenced by Part::Geometry::Restore().
restoreAttributes()
void GeometryPersistenceExtension::restoreAttributes (Base::XMLReader & reader) protected virtual
Reimplemented in Sketcher::SketchGeometryExtension, Sketcher::ExternalGeometryExtension, SketcherGui::ViewProviderSketchGeometryExtension, Part::GeometryDefaultExtension< T >, Part::GeometryDefaultExtension< T >, Part::GeometryDefaultExtension< T >, and Part::GeometryDefaultExtension< T >.
Definition at line 52 of file GeometryExtension.cpp.
References TechDrawTools.TaskFillTemplateFields::reader.
Referenced by Restore(), Part::GeometryDefaultExtension< T >::restoreAttributes(), SketcherGui::ViewProviderSketchGeometryExtension::restoreAttributes(), Sketcher::ExternalGeometryExtension::restoreAttributes(), and Sketcher::SketchGeometryExtension::restoreAttributes().
Save()
void GeometryPersistenceExtension::Save (Base::Writer & writer) const
Definition at line 68 of file GeometryExtension.cpp.
References Base::Type::getName(), Base::BaseClass::getTypeId(), Base::Writer::ind(), saveAttributes(), and Base::Writer::Stream().
Referenced by isSame().
saveAttributes()
void GeometryPersistenceExtension::saveAttributes (Base::Writer & writer) const protected virtual
Reimplemented in Sketcher::SketchGeometryExtension, Sketcher::ExternalGeometryExtension, SketcherGui::ViewProviderSketchGeometryExtension, and Part::GeometryDefaultExtension< T >.
Definition at line 59 of file GeometryExtension.cpp.
References Part::GeometryExtension::getName(), and Base::Writer::Stream().
Referenced by Save(), Part::GeometryDefaultExtension< T >::saveAttributes(), SketcherGui::ViewProviderSketchGeometryExtension::saveAttributes(), Sketcher::ExternalGeometryExtension::saveAttributes(), and Sketcher::SketchGeometryExtension::saveAttributes().
The documentation for this class was generated from the following files:
GeometryExtension.h
GeometryExtension.cpp