FreeCAD: TechDrawGui::QGTracker Class Reference
TechDrawGui::QGTracker Class Reference
#include <QGTracker.h>
Public Types
enum TrackerMode {
None, Line, Circle, Rectangle,
Point
}
enum { Type = QGraphicsItem::UserType + 210 }
Public Types inherited from TechDrawGui::QGIPrimPath
enum { Type = QGraphicsItem::UserType + 170 }
Signals
void drawingFinished (std::vector< QPointF > pts, TechDrawGui::QGIView *qgParent)
void qViewPicked (QPointF pos, TechDrawGui::QGIView *qgParent)
Public Member Functions
QGTracker (QGSPage *scene=nullptr, QGTracker::TrackerMode m=QGTracker::TrackerMode::None)
~QGTracker () override
int type () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
QPainterPath shape () const override
QRectF boundingRect () const override
void onMousePress (QPointF)
void onMouseMove (QPointF pos)
void onDoubleClick (QPointF pos)
void drawTrackLine (QPointF pos)
void drawTrackSquare (QPointF pos)
void drawTrackCircle (QPointF pos)
void drawTrackPoint (QPointF pos)
void setPathFromPoints (std::vector< QPointF > pts)
void setSquareFromPoints (std::vector< QPointF > pts)
void setCircleFromPoints (std::vector< QPointF > pts)
void setPoint (std::vector< QPointF > pts)
std::vector< Base::Vector3d > convertPoints ()
void terminateDrawing ()
void sleep (bool b)
TrackerMode getTrackerMode ()
void setTrackerMode (TrackerMode m)
QPointF snapToAngle (QPointF pt)
Public Member Functions inherited from TechDrawGui::QGIPrimPath
QGIPrimPath ()
~QGIPrimPath () override=default
int type () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
QPainterPath shape () const override
virtual void setPrettyNormal ()
virtual void setPrettyPre ()
virtual void setPrettySel ()
virtual void setWidth (double w)
virtual double getWidth ()
Qt::PenStyle getStyle ()
void setStyle (Qt::PenStyle s)
void setStyle (int s)
virtual void setNormalColor (QColor c)
virtual void setCapStyle (Qt::PenCapStyle c)
void setFillStyle (Qt::BrushStyle f)
Qt::BrushStyle getFillStyle ()
void setFill (QColor c, Qt::BrushStyle s)
void setFill (QBrush b)
void resetFill ()
void setFillColor (QColor c)
QColor getFillColor ()
void setFillOverride (bool b)
virtual void setCurrentPen ()
Protected Member Functions
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event) override
void hoverMoveEvent (QGraphicsSceneHoverEvent *event) override
void keyPressEvent (QKeyEvent *event) override
void getPickedQGIV (QPointF pos)
QColor getTrackerColor ()
double getTrackerWeight ()
Protected Member Functions inherited from TechDrawGui::QGIPrimPath
void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
virtual bool multiselectEligible ()
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
virtual QColor getNormalColor ()
virtual QColor getPreColor ()
virtual QColor getSelectColor ()
Base::Reference< ParameterGrp > getParmGroup ()
virtual Qt::PenCapStyle prefCapStyle ()
Additional Inherited Members
Protected Attributes inherited from TechDrawGui::QGIPrimPath
bool isHighlighted
bool multiselectActivated
QPen m_pen
QColor m_colCurrent
QColor m_colNormal
bool m_colOverride
Qt::PenStyle m_styleCurrent
Qt::PenStyle m_styleNormal
double m_width
Qt::PenCapStyle m_capStyle
QBrush m_brush
Qt::BrushStyle m_fillStyleCurrent
QColor m_fillColorCurrent
QColor m_colDefFill
QColor m_colNormalFill
Qt::BrushStyle m_fillDef
Qt::BrushStyle m_fillNormal
Qt::BrushStyle m_fillSelect
bool m_fillOverride
Detailed Description
Definition at line 57 of file QGTracker.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 67 of file QGTracker.h.
TrackerMode
enum TechDrawGui::QGTracker::TrackerMode
Enumerator
None
Line
Circle
Rectangle
Point
Definition at line 61 of file QGTracker.h.
Constructor & Destructor Documentation
QGTracker()
QGTracker::QGTracker (QGSPage * scene = nullptr, QGTracker::TrackerMode m = QGTracker::TrackerMode::None) explicit
Definition at line 53 of file QGTracker.cpp.
References getTrackerColor(), getTrackerWeight(), test::m, TechDrawGui::QGIPrimPath::setNormalColor(), TechDrawGui::QGIPrimPath::setPrettyNormal(), TechDrawGui::QGIPrimPath::setStyle(), setTrackerMode(), TechDrawGui::QGIPrimPath::setWidth(), and ZVALUE::TRACKER.
~QGTracker()
QGTracker::~QGTracker () override
Definition at line 102 of file QGTracker.cpp.
Member Function Documentation
boundingRect()
QRectF QGTracker::boundingRect () const override
Definition at line 322 of file QGTracker.cpp.
Referenced by shape().
convertPoints()
std::vector< Base::Vector3d > QGTracker::convertPoints ()
Definition at line 449 of file QGTracker.cpp.
References buildPsets::p, result, and TestSpreadsheet::v.
drawingFinished
void TechDrawGui::QGTracker::drawingFinished (std::vector< QPointF > pts, TechDrawGui::QGIView * qgParent) signal
Referenced by TechDrawGui::TaskCosVertex::startTracker(), TechDrawGui::TaskLeaderLine::startTracker(), and terminateDrawing().
drawTrackCircle()
void QGTracker::drawTrackCircle (QPointF pos)
Definition at line 364 of file QGTracker.cpp.
References exportCSG::center(), RobotExample::pos, Base::pow(), and KDL::sqrt().
Referenced by onMouseMove().
drawTrackLine()
void QGTracker::drawTrackLine (QPointF pos)
Definition at line 336 of file QGTracker.cpp.
References RobotExample::pos.
Referenced by onMouseMove().
drawTrackPoint()
void QGTracker::drawTrackPoint (QPointF pos)
Definition at line 379 of file QGTracker.cpp.
References RobotExample::pos.
drawTrackSquare()
void QGTracker::drawTrackSquare (QPointF pos)
Definition at line 350 of file QGTracker.cpp.
References RobotExample::pos.
Referenced by onMouseMove().
getPickedQGIV()
void QGTracker::getPickedQGIV (QPointF pos) protected
Definition at line 300 of file QGTracker.cpp.
References RobotExample::pos.
Referenced by onMousePress().
getTrackerColor()
QColor QGTracker::getTrackerColor () protected
Definition at line 478 of file QGTracker.cpp.
References App::Color::asValue(), and TechDrawGui::PreferencesGui::getAccessibleQColor().
Referenced by QGTracker().
getTrackerMode()
TrackerMode TechDrawGui::QGTracker::getTrackerMode () inline
Definition at line 88 of file QGTracker.h.
Referenced by onDoubleClick(), onMouseMove(), and onMousePress().
getTrackerWeight()
double QGTracker::getTrackerWeight () protected
Definition at line 484 of file QGTracker.cpp.
Referenced by QGTracker().
hoverMoveEvent()
void QGTracker::hoverMoveEvent (QGraphicsSceneHoverEvent * event) override protected
Definition at line 152 of file QGTracker.cpp.
References onMouseMove(), and snapToAngle().
keyPressEvent()
void QGTracker::keyPressEvent (QKeyEvent * event) override protected
Definition at line 164 of file QGTracker.cpp.
References terminateDrawing().
mouseDoubleClickEvent()
void QGTracker::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * event) override protected
Definition at line 142 of file QGTracker.cpp.
References onDoubleClick().
mousePressEvent()
void QGTracker::mousePressEvent (QGraphicsSceneMouseEvent * event) override protected
Definition at line 106 of file QGTracker.cpp.
References TechDrawGui::Rez::guiX(), TechDrawGui::QGIPrimPath::mousePressEvent(), onMousePress(), snapToAngle(), and terminateDrawing().
mouseReleaseEvent()
void QGTracker::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) override protected
Definition at line 134 of file QGTracker.cpp.
References TechDrawGui::QGIPrimPath::mouseReleaseEvent().
onDoubleClick()
void QGTracker::onDoubleClick (QPointF pos)
Definition at line 289 of file QGTracker.cpp.
References getTrackerMode(), RobotExample::pos, setPoint(), and terminateDrawing().
Referenced by mouseDoubleClickEvent().
onMouseMove()
void QGTracker::onMouseMove (QPointF pos)
Definition at line 267 of file QGTracker.cpp.
References drawTrackCircle(), drawTrackLine(), drawTrackSquare(), getTrackerMode(), TechDraw::Line, test::m, Gui::None, RobotExample::pos, and TechDraw::Rectangle.
Referenced by hoverMoveEvent().
onMousePress()
void QGTracker::onMousePress (QPointF pos)
Definition at line 226 of file QGTracker.cpp.
References getPickedQGIV(), getTrackerMode(), TechDraw::Line, Gui::None, RobotExample::pos, TechDraw::Rectangle, setCircleFromPoints(), setPathFromPoints(), setPoint(), setSquareFromPoints(), and terminateDrawing().
Referenced by mousePressEvent().
paint()
void QGTracker::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) override
Definition at line 467 of file QGTracker.cpp.
References TechDrawGui::QGIPrimPath::paint(), and shape().
qViewPicked
void TechDrawGui::QGTracker::qViewPicked (QPointF pos, TechDrawGui::QGIView * qgParent) signal
setCircleFromPoints()
void QGTracker::setCircleFromPoints (std::vector< QPointF > pts)
Definition at line 416 of file QGTracker.cpp.
References exportCSG::center(), Base::pow(), TechDrawGui::QGIPrimPath::setPrettyNormal(), and KDL::sqrt().
Referenced by onMousePress().
setPathFromPoints()
void QGTracker::setPathFromPoints (std::vector< QPointF > pts)
Definition at line 384 of file QGTracker.cpp.
References TechDrawGui::QGIPrimPath::setPrettyNormal().
Referenced by onMousePress().
setPoint()
void QGTracker::setPoint (std::vector< QPointF > pts)
Definition at line 433 of file QGTracker.cpp.
References exportCSG::center(), Base::Console(), Base::ConsoleSingleton::Message(), and TechDrawGui::QGIPrimPath::setPrettyNormal().
Referenced by onDoubleClick(), and onMousePress().
setSquareFromPoints()
void QGTracker::setSquareFromPoints (std::vector< QPointF > pts)
Definition at line 400 of file QGTracker.cpp.
References TechDrawGui::QGIPrimPath::setPrettyNormal().
Referenced by onMousePress().
setTrackerMode()
void TechDrawGui::QGTracker::setTrackerMode (TrackerMode m) inline
Definition at line 89 of file QGTracker.h.
References test::m.
Referenced by QGTracker().
shape()
QPainterPath QGTracker::shape () const override
Definition at line 327 of file QGTracker.cpp.
References boundingRect(), and result.
Referenced by paint().
sleep()
void QGTracker::sleep (bool b)
Definition at line 175 of file QGTracker.cpp.
References SCL.SimpleDataTypes::b.
Referenced by TechDrawGui::TaskCosVertex::onTrackerFinished(), and TechDrawGui::TaskLeaderLine::onTrackerFinished().
snapToAngle()
QPointF QGTracker::snapToAngle (QPointF pt)
Definition at line 185 of file QGTracker.cpp.
References KDL::atan2(), KDL::cos(), TechDraw::DrawUtil::fpCompare(), M_PI, Base::pow(), result, KDL::sin(), and KDL::sqrt().
Referenced by hoverMoveEvent(), and mousePressEvent().
terminateDrawing()
void QGTracker::terminateDrawing ()
Definition at line 459 of file QGTracker.cpp.
References drawingFinished().
Referenced by keyPressEvent(), mousePressEvent(), onDoubleClick(), onMousePress(), and TechDrawGui::TaskLeaderLine::onTrackerClicked().
type()
int TechDrawGui::QGTracker::type () const inline override
Definition at line 69 of file QGTracker.h.
The documentation for this class was generated from the following files:
QGTracker.h
QGTracker.cpp