FreeCAD: ifc2x3.ifcgeometriccurveset Class Reference
ifc2x3.ifcgeometriccurveset Class Reference
Public Member Functions
def __init__ (self, inherited0__elements)
def wr1 (self)
Public Member Functions inherited from ifc2x3.ifcgeometricset
def elements ()
def dim ()
def wr21 (self)
Public Member Functions inherited from ifc2x3.ifcgeometricrepresentationitem
def __init__ (self)
Public Member Functions inherited from ifc2x3.ifcrepresentationitem
def layerassignments ()
def styledbyitem ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Additional Inherited Members
Public Attributes inherited from ifc2x3.ifcgeometricset
elements
Detailed Description
Entity ifcgeometriccurveset definition.
Definition at line 17908 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcgeometriccurveset.__init__ (self, inherited0__elements)
Reimplemented from ifc2x3.ifcgeometricset.
Definition at line 17911 of file ifc2x3.py.
Member Function Documentation
wr1()
def ifc2x3.ifcgeometriccurveset.wr1 (self)
Definition at line 17913 of file ifc2x3.py.
References SCL.Builtin.SIZEOF().
Referenced by ifc4.ifctextalignment.__init__(), ifc4.ifcspecularroughness.__init__(), ifc4.ifcheatingvaluemeasure.__init__(), ifc4.ifctexttransformation.__init__(), ifc4.ifcfontstyle.__init__(), ifc4.ifcboxalignment.__init__(), ifc4.ifcpositiveplaneanglemeasure.__init__(), ifc4.ifcdimensioncount.__init__(), ifc4.ifcfontvariant.__init__(), ifc4.ifcfontweight.__init__(), ifc4.ifcnormalisedratiomeasure.__init__(), ifc4.ifcpositivelengthmeasure.__init__(), ifc4.ifcpositiveratiomeasure.__init__(), and ifc4.ifctextdecoration.__init__().
The documentation for this class was generated from the following file:
ifc2x3.py