FreeCAD: Base::Placement Class Reference
Base::Placement Class Reference
#include <Placement.h>
Public Member Functions
Placement ()
default constructor
Placement (const Placement &)=default
Placement (Placement &&)=default
Placement (const Base::Matrix4D &matrix)
Placement (const Vector3d &Pos, const Rotation &Rot)
Placement (const Vector3d &Pos, const Rotation &Rot, const Vector3d &Cnt)
~Placement ()=default
Destruction.
Matrix4D toMatrix () const
void fromMatrix (const Matrix4D &m)
DualQuat toDualQuaternion () const
const Vector3d & getPosition () const
const Rotation & getRotation () const
void setPosition (const Vector3d &Pos)
void setRotation (const Rotation &Rot)
bool isIdentity () const
bool isIdentity (double tol) const
void invert ()
Placement inverse () const
void move (const Vector3d &MovVec)
bool isSame (const Placement &) const
bool isSame (const Placement &, double tol) const
Placement & operator*= (const Placement &p)
Placement operator* (const Placement &p) const
bool operator== (const Placement &) const
bool operator!= (const Placement &) const
Placement & operator= (const Placement &)=default
Placement & operator= (Placement &&)=default
Placement pow (double t, bool shorten=true) const
Placement & multRight (const Base::Placement &p)
Placement & multLeft (const Base::Placement &p)
void multVec (const Vector3d &src, Vector3d &dst) const
void multVec (const Vector3f &src, Vector3f &dst) const
std::string toString () const
Returns string representation of the placement, useful for debugging.
Static Public Member Functions
static Placement fromDualQuaternion (DualQuat qq)
static Placement slerp (const Placement &p0, const Placement &p1, double t)
static Placement sclerp (const Placement &p0, const Placement &p1, double t, bool shorten=true)
Detailed Description
The Placement class.
Definition at line 61 of file Base/Placement.h.
Constructor & Destructor Documentation
Placement() [1/6]
Placement::Placement () default
default constructor
Referenced by PartDesign::ProfileBased::getProfileNormal(), isIdentity(), PartGui::SectionCut::onCutXvalueChanged(), PartGui::SectionCut::onCutYvalueChanged(), PartGui::SectionCut::onCutZvalueChanged(), and Sketcher::SketchObject::rebuildExternalGeometry().
Placement() [2/6]
Base::Placement::Placement (const Placement &) default
Placement() [3/6]
Base::Placement::Placement (Placement &&) default
Placement() [4/6]
Placement::Placement (const Base::Matrix4D & matrix)
Definition at line 36 of file Base/Placement.cpp.
References fromMatrix().
Placement() [5/6]
Placement::Placement (const Vector3d & Pos, const Rotation & Rot)
Definition at line 41 of file Base/Placement.cpp.
Placement() [6/6]
Placement::Placement (const Vector3d & Pos, const Rotation & Rot, const Vector3d & Cnt)
Definition at line 46 of file Base/Placement.cpp.
References Base::Rotation::multVec().
~Placement()
Base::Placement::~Placement () default
Destruction.
Member Function Documentation
fromDualQuaternion()
Placement Placement::fromDualQuaternion (DualQuat qq) static
specialty constructors
Definition at line 54 of file Base/Placement.cpp.
References Base::DualQuat::conj(), Base::DualQuat::dual(), Base::DualNumber::re, Base::DualQuat::real(), Base::DualQuat::w, Base::DualQuat::x, Base::DualQuat::y, and Base::DualQuat::z.
Referenced by pow().
fromMatrix()
void Placement::fromMatrix (const Matrix4D & m)
Definition at line 71 of file Base/Placement.cpp.
References Base::Rotation::setValue(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by WriterInventorImp::addTransformNode(), Part::Feature::onChanged(), Placement(), and Base::TransformItem::TransformItem().
getPosition()
const Vector3d& Base::Placement::getPosition () const inline
Definition at line 83 of file Base/Placement.h.
Referenced by Attacher::AttachEngine3D::_calculateAttachedPlacement(), PartGui::TaskDlgAttacher::accept(), Sketcher::SketchObject::addExternal(), Attacher::AttachEngine::calculateAttachedPlacement(), Import::ExportOCAF::createNode(), Assembly::AssemblyObject::doDragStep(), Robot::TrajectoryDressUpObject::execute(), PartDesignGui::fixSketchSupport(), Part::Tools::fromPlacement(), PartDesign::ProfileBased::getAxis(), App::DatumElement::getBasePoint(), MeasureGui::ViewProviderMeasure::getBasePosition(), Gui::ViewProviderDragger::getDraggerPlacement(), Part::FeatureReference::getLocation(), Part::Feature::getLocation(), Gui::View3DInventorViewer::getPointOnXYPlaneOfPlacement(), Gui::View3DInventorViewer::getViewportOnXYPlaneOfPlacement(), Sketcher::SketchObject::isCarbonCopyAllowed(), Assembly::AssemblyObject::makeMbdMarker(), Assembly::AssemblyObject::makeMbdPart(), PartGui::SectionCut::onCutXvalueChanged(), PartGui::SectionCut::onCutYvalueChanged(), PartGui::SectionCut::onCutZvalueChanged(), Measure::ShapeFinder::PlacementAsString(), printPlacement(), Sketcher::SketchObject::rebuildExternalGeometry(), Path::Toolpath::recalculate(), Part::Geometry::rotate(), Robot::Robot6Axis::Save(), Robot::Waypoint::Save(), Import::ExportOCAF::saveShape(), RobotGui::ViewProviderRobotObject::setDragger(), Gui::ViewProviderDragger::setDraggerPlacement(), AssemblyGui::ViewProviderAssembly::setDraggerPlacement(), SketcherGui::ViewProviderSketch::setEdit(), SketcherGui::ViewProviderSketch::setEditViewer(), Path::Command::setFromPlacement(), Gui::EditableDatumLabel::setPlacement(), Base::CoordinateSystem::setPlacement(), Robot::Robot6Axis::setTo(), slerp(), Gui::View3DInventorViewer::toggleClippingPlane(), toString(), Path::Command::transform(), Point3D::UpdateCmd(), RobotGui::ViewProviderTrajectory::updateData(), RobotGui::ViewProviderRobotObject::updateData(), Gui::ViewProviderDragger::updateTransform(), RobotGui::TaskTrajectoryDressUpParameter::viewPlacement(), Gui::View3DInventorPy::viewPosition(), Path::PathSegmentWalker::walk(), Points::PcdWriter::write(), and Base::TransformItem::write().
getRotation()
const Rotation& Base::Placement::getRotation () const inline
Definition at line 87 of file Base/Placement.h.
Referenced by Attacher::AttachEngine3D::_calculateAttachedPlacement(), PartGui::TaskDlgAttacher::accept(), Sketcher::SketchObject::addExternal(), Gui::View3DInventorViewer::alignToSelection(), Attacher::AttachEngine::calculateAttachedPlacement(), Import::ExportOCAF::createNode(), Assembly::AssemblyObject::doDragStep(), Robot::TrajectoryDressUpObject::execute(), PartDesignGui::fixSketchSupport(), Part::Tools::fromPlacement(), PartDesign::ProfileBased::getAxis(), App::DatumElement::getDirection(), Gui::ViewProviderDragger::getDraggerPlacement(), Part::FeatureReference::getLocation(), Part::Feature::getLocation(), Gui::View3DInventorViewer::getPointOnXYPlaneOfPlacement(), PartDesign::ProfileBased::getProfileNormal(), Assembly::AssemblyObject::getRackPinionMarkers(), PartDesign::ProfileBased::getReversedAngle(), Gui::View3DInventorViewer::getViewportOnXYPlaneOfPlacement(), Sketcher::SketchObject::isCarbonCopyAllowed(), Assembly::AssemblyObject::makeMbdMarker(), Assembly::AssemblyObject::makeMbdPart(), Base::Axis::operator*=(), Measure::ShapeFinder::PlacementAsString(), printPlacement(), Sketcher::SketchObject::rebuildExternalGeometry(), Part::Geometry::rotate(), Robot::Robot6Axis::Save(), Robot::Waypoint::Save(), Import::ExportOCAF::saveShape(), RobotGui::ViewProviderRobotObject::setDragger(), Gui::ViewProviderDragger::setDraggerPlacement(), AssemblyGui::ViewProviderAssembly::setDraggerPlacement(), SketcherGui::ViewProviderSketch::setEdit(), SketcherGui::ViewProviderSketch::setEditViewer(), Path::Command::setFromPlacement(), Gui::EditableDatumLabel::setPlacement(), Base::CoordinateSystem::setPlacement(), Robot::Robot6Axis::setTo(), slerp(), Assembly::AssemblyObject::slidingPartIndex(), Gui::TaskTransform::TaskTransform(), Gui::View3DInventorViewer::toggleClippingPlane(), toString(), Path::Command::transform(), Base::CoordinateSystem::transform(), Mesh::MeshObject::trimByPlane(), RobotGui::ViewProviderRobotObject::updateData(), Gui::ViewProviderDragger::updateTransform(), RobotGui::TaskTrajectoryDressUpParameter::viewPlacement(), Gui::View3DInventorPy::viewPosition(), Points::PlyWriter::write(), Points::PcdWriter::write(), and Base::TransformItem::write().
inverse()
Placement Placement::inverse () const
Definition at line 117 of file Base/Placement.cpp.
References buildPsets::p.
Referenced by AttacherSubObjectPlacement::calculate(), AssemblyGui::ViewProviderAssembly::draggerMotionCallback(), PartDesign::Boolean::execute(), Mesh::MeshObject::foraminate(), AssemblyGui::ViewProviderAssembly::getCenterOfBoundingBox(), Assembly::AssemblyObject::getMbDData(), Sketcher::SketchAnalysis::getOpenVertices(), Assembly::AssemblyObject::getRackPinionMarkers(), Fem::Tools::getSubShapeGlobalLocation(), Assembly::AssemblyObject::handleOneSideOfJoint(), Gui::ViewProviderLink::initDraggingPlacement(), Mesh::MeshObject::nearestFacetOnRay(), Part::AttachExtension::positionBySupport(), Sketcher::SketchObject::rebuildExternalGeometry(), Robot::Simulation::reset(), sclerp(), RobotGui::ViewProviderRobotObject::setAxisTo(), Gui::ViewProviderDragger::setEditViewer(), PartDesignGui::ViewProviderDatumLine::setExtents(), PartDesignGui::ViewProviderDatumPlane::setExtents(), Robot::Simulation::setToTime(), Gui::TaskTransform::TaskTransform(), RobotGui::ViewProviderRobotObject::updateData(), PartDesign::ShapeBinder::updatedShape(), Gui::ViewProviderDragger::updatePlacementFromDragger(), and Gui::ViewProviderDragger::updateTransformFromDragger().
invert()
void Placement::invert ()
Definition at line 110 of file Base/Placement.cpp.
References Base::Rotation::inverse(), and Base::Rotation::multVec().
Referenced by Gui::View3DInventorViewer::getViewportOnXYPlaneOfPlacement(), MeshGui::ViewProviderMesh::partMeshCallback(), MeshGui::ViewProviderMesh::segmMeshCallback(), Mesh::MeshObject::trimByPlane(), and PartGui::ViewProvider2DObjectGrid::updateData().
isIdentity() [1/2]
bool Placement::isIdentity () const
Definition at line 88 of file Base/Placement.cpp.
References Base::Rotation::isIdentity().
Referenced by ArchComponent.Component::applyShape(), Assembly::AssemblyObject::ensureIdentityPlacements(), ArchComponent.Component::getExtrusionData(), Assembly::AssemblyObject::getRackPinionMarkers(), Assembly::AssemblyObject::handleOneSideOfJoint(), Assembly::AssemblyLink::onChanged(), Assembly::AssemblyObject::preDrag(), ArchComponent.Component::processSubShapes(), Points::AscWriter::write(), Points::PlyWriter::write(), and Points::PcdWriter::write().
isIdentity() [2/2]
bool Placement::isIdentity (double tol) const
Definition at line 95 of file Base/Placement.cpp.
References isSame(), and Placement().
Referenced by ArchComponent.Component::applyShape(), ArchComponent.Component::getExtrusionData(), and ArchComponent.Component::processSubShapes().
isSame() [1/2]
bool Placement::isSame (const Placement & p) const
Definition at line 100 of file Base/Placement.cpp.
References Base::Vector3< float_type >::IsEqual(), Base::Rotation::isSame(), and buildPsets::p.
Referenced by isIdentity(), and Assembly::AssemblyObject::validateNewPlacements().
isSame() [2/2]
bool Placement::isSame (const Placement & p, double tol) const
Definition at line 105 of file Base/Placement.cpp.
References Base::Vector3< float_type >::IsEqual(), Base::Rotation::isSame(), and buildPsets::p.
move()
void Placement::move (const Vector3d & MovVec)
Definition at line 124 of file Base/Placement.cpp.
Referenced by draftguitools.gui_circulararray.CircularArray::Activated(), and draftguitools.gui_polararray.PolarArray::Activated().
multLeft()
Placement & Placement::multLeft (const Base::Placement & p)
Let this placement be left-multiplied by p. Returns reference to self.
See also
multRight()
Definition at line 183 of file Base/Placement.cpp.
References Base::Rotation::multLeft(), and buildPsets::p.
Referenced by App::FeatureTestPlacement::execute().
multRight()
Placement & Placement::multRight (const Base::Placement & p)
Let this placement be right-multiplied by p. Returns reference to self.
See also
multLeft()
Definition at line 168 of file Base/Placement.cpp.
References Base::Rotation::multRight(), Base::Rotation::multVec(), and buildPsets::p.
Referenced by App::FeatureTestPlacement::execute(), and operator*=().
multVec() [1/2]
void Placement::multVec (const Vector3d & src, Vector3d & dst) const
Definition at line 190 of file Base/Placement.cpp.
References Base::Rotation::multVec().
Referenced by Mesh::MeshObject::foraminate(), Sketcher::SketchAnalysis::getOpenVertices(), Mesh::MeshObject::nearestFacetOnRay(), Base::Axis::operator*=(), Sketcher::SketchObject::rebuildExternalGeometry(), PathGui::ViewProviderPath::recomputeBoundingBox(), Base::Line3< float >::Transform(), Base::Polygon3< float_type >::Transform(), Mesh::MeshObject::trimByPlane(), Points::PlyWriter::write(), and Points::PcdWriter::write().
multVec() [2/2]
void Placement::multVec (const Vector3f & src, Vector3f & dst) const
Definition at line 196 of file Base/Placement.cpp.
References Base::Rotation::multVec().
operator!=()
bool Placement::operator!= (const Placement & that) const
Definition at line 134 of file Base/Placement.cpp.
operator*()
Placement Placement::operator* (const Placement & p) const
Definition at line 150 of file Base/Placement.cpp.
References buildPsets::p.
operator*=()
Placement & Placement::operator*= (const Placement & p)
Operators.
Let this placement be right-multiplied by p. Returns reference to self.
See also
multRight()
Definition at line 145 of file Base/Placement.cpp.
References multRight(), and buildPsets::p.
operator=() [1/2]
Placement& Base::Placement::operator= (const Placement &) default
operator=() [2/2]
Placement& Base::Placement::operator= (Placement &&) default
operator==()
bool Placement::operator== (const Placement & that) const
Definition at line 129 of file Base/Placement.cpp.
pow()
Placement Placement::pow (double t, bool shorten = true) const
Definition at line 157 of file Base/Placement.cpp.
References fromDualQuaternion(), and toDualQuaternion().
Referenced by sclerp().
sclerp()
Placement Placement::sclerp (const Placement & p0, const Placement & p1, double t, bool shorten = true) static
Definition at line 209 of file Base/Placement.cpp.
References inverse(), pow(), and InitGui::t.
setPosition()
void Base::Placement::setPosition (const Vector3d & Pos) inline
Definition at line 91 of file Base/Placement.h.
Referenced by Attacher::AttachEngine3D::_calculateAttachedPlacement(), PathSimulator::PathSim::ApplyCommand(), Gui::ManualAlignment::computeAlignment(), Robot::TrajectoryDressUpObject::execute(), Measure::MeasurePosition::getPlacement(), PartGui::SectionCut::onCutXvalueChanged(), PartGui::SectionCut::onCutYvalueChanged(), PartGui::SectionCut::onCutZvalueChanged(), and Part::Box::Restore().
setRotation()
void Base::Placement::setRotation (const Rotation & Rot) inline
Definition at line 95 of file Base/Placement.h.
Referenced by Attacher::AttachEngine3D::_calculateAttachedPlacement(), Attacher::AttachEngineLine::_calculateAttachedPlacement(), Robot::TrajectoryDressUpObject::execute(), Assembly::AssemblyObject::getRackPinionMarkers(), and Part::Box::Restore().
slerp()
Placement Placement::slerp (const Placement & p0, const Placement & p1, double t) static
Definition at line 202 of file Base/Placement.cpp.
References getPosition(), getRotation(), RobotExample::pos, Base::Rotation::slerp(), and InitGui::t.
toDualQuaternion()
DualQuat Placement::toDualQuaternion () const
Definition at line 79 of file Base/Placement.cpp.
References Base::Rotation::getValue(), Base::DualNumber::re, Base::DualQuat::w, Base::DualQuat::x, Base::Vector3< float_type >::x, Base::DualQuat::y, Base::Vector3< float_type >::y, Base::DualQuat::z, and Base::Vector3< float_type >::z.
Referenced by pow().
toMatrix()
Base::Matrix4D Placement::toMatrix () const
Definition at line 61 of file Base/Placement.cpp.
References Base::Rotation::getValue(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by Gui::Dialog::TransformStrategy::acceptDataTransform(), Gui::Dialog::TransformStrategy::applyViewTransform(), MeshGui::ViewProviderMesh::clipMeshCallback(), App::OriginGroupExtension::extensionGetSubObject(), App::GeoFeatureGroupExtension::extensionGetSubObject(), Part::Feature::getSubObject(), PartDesign::Body::getSubObject(), PartDesign::SubShapeBinder::getSubObject(), Sketcher::SketchObject::getSubObject(), Part::Feature::getTopoShape(), Gui::View3DInventorViewer::getViewportOnXYPlaneOfPlacement(), TechDraw::ShapeExtractor::getXShapes(), Gui::ViewProviderLink::initDraggingPlacement(), Gui::Dialog::Transform::onApplyButtonClicked(), Mesh::Feature::onChanged(), Points::Feature::onChanged(), Part::Feature::onChanged(), MeshGui::ViewProviderMesh::partMeshCallback(), Sketcher::SketchObject::rebuildExternalGeometry(), Gui::Dialog::TransformStrategy::resetViewTransform(), MeshGui::ViewProviderMesh::segmMeshCallback(), Gui::ViewProviderDragger::setEditViewer(), PartDesignGui::ViewProviderDatumLine::setExtents(), PartDesignGui::ViewProviderDatumPlane::setExtents(), Data::ComplexGeoData::setPlacement(), MeshGui::ViewProviderMesh::trimMeshCallback(), PartDesign::SubShapeBinder::update(), PartGui::ViewProvider2DObjectGrid::updateData(), and Points::AscWriter::write().
toString()
std::string Placement::toString () const
Returns string representation of the placement, useful for debugging.
Definition at line 215 of file Base/Placement.cpp.
References getPosition(), Base::Rotation::getRawValue(), getRotation(), RobotExample::pos, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
The documentation for this class was generated from the following files:
Base/Placement.h
Base/Placement.cpp