FreeCAD: ImportGui::ExportOCAFGui Class Reference
ImportGui::ExportOCAFGui Class Reference
#include <ExportOCAFGui.h>
Public Member Functions
ExportOCAFGui (Handle(TDocStd_Document) hDoc, bool explicitPlacement)
void findColors (Part::Feature *part, std::vector< App::Color > &colors) const override
Public Member Functions inherited from Import::ExportOCAF
ExportOCAF (Handle(TDocStd_Document) hDoc, bool explicitPlacement)
virtual ~ExportOCAF ()
void exportObjects (std::vector< App::DocumentObject * > &objs)
int exportObject (App::DocumentObject *obj, std::vector< TDF_Label > &hierarchical_label, std::vector< TopLoc_Location > &hierarchical_loc, std::vector< App::DocumentObject * > &hierarchical_part)
int saveShape (Part::Feature *part, const std::vector< App::Color > &, std::vector< TDF_Label > &hierarchical_label, std::vector< TopLoc_Location > &hierarchical_loc, std::vector< App::DocumentObject * > &hierarchical_part)
void getPartColors (std::vector< App::DocumentObject * > hierarchical_part, std::vector< TDF_Label > FreeLabels, std::vector< int > part_id, std::vector< std::vector< App::Color >> &Colors) const
void reallocateFreeShape (std::vector< App::DocumentObject * > hierarchical_part, std::vector< TDF_Label > FreeLabels, std::vector< int > part_id, std::vector< std::vector< App::Color >> &Colors)
void getFreeLabels (std::vector< TDF_Label > &hierarchical_label, std::vector< TDF_Label > &labels, std::vector< int > &label_part_id)
void createNode (App::Part *part, int &root_it, std::vector< TDF_Label > &hierarchical_label, std::vector< TopLoc_Location > &hierarchical_loc, std::vector< App::DocumentObject * > &hierarchical_part)
void pushNode (int root, int node, std::vector< TDF_Label > &hierarchical_label, std::vector< TopLoc_Location > &hierarchical_loc)
Detailed Description
Definition at line 51 of file ExportOCAFGui.h.
Constructor & Destructor Documentation
ExportOCAFGui()
ExportOCAFGui::ExportOCAFGui (Handle(TDocStd_Document) hDoc, bool explicitPlacement)
Definition at line 34 of file ExportOCAFGui.cpp.
Member Function Documentation
findColors()
void ExportOCAFGui::findColors (Part::Feature * part, std::vector< App::Color > & colors) const override virtual
Reimplemented from Import::ExportOCAF.
Definition at line 38 of file ExportOCAFGui.cpp.
References importers.importIFCmulticore::colors, Base::Persistence::getClassTypeId(), Gui::Application::getViewProvider(), Gui::Application::Instance, and Base::BaseClass::isDerivedFrom().
The documentation for this class was generated from the following files:
ExportOCAFGui.h
ExportOCAFGui.cpp