FreeCAD: AppReverseEngineeringGui.cpp File Reference
AppReverseEngineeringGui.cpp File Reference
#include "PreCompiled.h"
#include <Base/Console.h>
#include <Base/Interpreter.h>
#include <Base/PyObjectBase.h>
#include <Gui/Application.h>
#include <Gui/Language/Translator.h>
#include "Workbench.h"
Classes
class ReverseEngineeringGui::Module
Namespaces
ReverseEngineeringGui
Functions
void CreateReverseEngineeringCommands ()
void loadReverseEngineeringResource ()
PyObject * ReverseEngineeringGui::initModule ()
PyMOD_INIT_FUNC (ReverseEngineeringGui)
Function Documentation
CreateReverseEngineeringCommands()
void CreateReverseEngineeringCommands ()
Definition at line 682 of file Mod/ReverseEngineering/Gui/Command.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
loadReverseEngineeringResource()
void loadReverseEngineeringResource ()
Definition at line 37 of file AppReverseEngineeringGui.cpp.
References Gui::Translator::instance(), and Gui::Translator::refresh().
Referenced by PyMOD_INIT_FUNC().
PyMOD_INIT_FUNC()
PyMOD_INIT_FUNC (ReverseEngineeringGui)
Definition at line 68 of file AppReverseEngineeringGui.cpp.
References Base::Console(), CreateReverseEngineeringCommands(), SCL.SimpleDataTypes::e, Base::BaseClass::init(), ReverseEngineeringGui::initModule(), Gui::Application::Instance, Base::Interpreter(), Base::InterpreterSingleton::loadModule(), loadReverseEngineeringResource(), Base::ConsoleSingleton::Log(), mod, and PyMOD_Return.