FreeCAD: Wm4::Matrix3< Real > Class Template Reference
Wm4::Matrix3< Real > Class Template Reference
#include <Wm4Matrix3.h>
Public Member Functions
Matrix3 (bool bZero=true)
Matrix3 (const Matrix3 &rkM)
Matrix3 (Real fM00, Real fM01, Real fM02, Real fM10, Real fM11, Real fM12, Real fM20, Real fM21, Real fM22)
Matrix3 (const Real afEntry[9], bool bRowMajor)
Matrix3 (const Vector3< Real > &rkU, const Vector3< Real > &rkV, const Vector3< Real > &rkW, bool bColumns)
Matrix3 (const Vector3< Real > *akV, bool bColumns)
Matrix3 (Real fM00, Real fM11, Real fM22)
Matrix3 (const Vector3< Real > &rkAxis, Real fAngle)
Matrix3 (const Vector3< Real > &rkU, const Vector3< Real > &rkV)
Matrix3 & MakeZero ()
Matrix3 & MakeIdentity ()
Matrix3 & MakeDiagonal (Real fM00, Real fM11, Real fM22)
Matrix3 & FromAxisAngle (const Vector3< Real > &rkAxis, Real fAngle)
Matrix3 & MakeTensorProduct (const Vector3< Real > &rkU, const Vector3< Real > &rkV)
operator const Real * () const
operator Real * ()
const Real * operator[] (int iRow) const
Real * operator[] (int iRow)
Real operator() (int iRow, int iCol) const
Real & operator() (int iRow, int iCol)
void SetRow (int iRow, const Vector3< Real > &rkV)
Vector3< Real > GetRow (int iRow) const
void SetColumn (int iCol, const Vector3< Real > &rkV)
Vector3< Real > GetColumn (int iCol) const
void GetColumnMajor (Real *afCMajor) const
Matrix3 & operator= (const Matrix3 &rkM)
bool operator== (const Matrix3 &rkM) const
bool operator!= (const Matrix3 &rkM) const
bool operator< (const Matrix3 &rkM) const
bool operator<= (const Matrix3 &rkM) const
bool operator> (const Matrix3 &rkM) const
bool operator>= (const Matrix3 &rkM) const
Matrix3 operator+ (const Matrix3 &rkM) const
Matrix3 operator- (const Matrix3 &rkM) const
Matrix3 operator* (const Matrix3 &rkM) const
Matrix3 operator* (Real fScalar) const
Matrix3 operator/ (Real fScalar) const
Matrix3 operator- () const
Matrix3 & operator+= (const Matrix3 &rkM)
Matrix3 & operator-= (const Matrix3 &rkM)
Matrix3 & operator*= (Real fScalar)
Matrix3 & operator/= (Real fScalar)
Vector3< Real > operator* (const Vector3< Real > &rkV) const
Matrix3 Transpose () const
Matrix3 TransposeTimes (const Matrix3 &rkM) const
Matrix3 TimesTranspose (const Matrix3 &rkM) const
Matrix3 Inverse () const
Matrix3 Adjoint () const
Real Determinant () const
Real QForm (const Vector3< Real > &rkU, const Vector3< Real > &rkV) const
Matrix3 TimesDiagonal (const Vector3< Real > &rkDiag) const
Matrix3 DiagonalTimes (const Vector3< Real > &rkDiag) const
void ToAxisAngle (Vector3< Real > &rkAxis, Real &rfAngle) const
void Orthonormalize ()
void EigenDecomposition (Matrix3 &rkRot, Matrix3 &rkDiag) const
Matrix3 & FromEulerAnglesXYZ (Real fXAngle, Real fYAngle, Real fZAngle)
Matrix3 & FromEulerAnglesXZY (Real fXAngle, Real fZAngle, Real fYAngle)
Matrix3 & FromEulerAnglesYXZ (Real fYAngle, Real fXAngle, Real fZAngle)
Matrix3 & FromEulerAnglesYZX (Real fYAngle, Real fZAngle, Real fXAngle)
Matrix3 & FromEulerAnglesZXY (Real fZAngle, Real fXAngle, Real fYAngle)
Matrix3 & FromEulerAnglesZYX (Real fZAngle, Real fYAngle, Real fXAngle)
bool ToEulerAnglesXYZ (Real &rfXAngle, Real &rfYAngle, Real &rfZAngle) const
bool ToEulerAnglesXZY (Real &rfXAngle, Real &rfZAngle, Real &rfYAngle) const
bool ToEulerAnglesYXZ (Real &rfYAngle, Real &rfXAngle, Real &rfZAngle) const
bool ToEulerAnglesYZX (Real &rfYAngle, Real &rfZAngle, Real &rfXAngle) const
bool ToEulerAnglesZXY (Real &rfZAngle, Real &rfXAngle, Real &rfYAngle) const
bool ToEulerAnglesZYX (Real &rfZAngle, Real &rfYAngle, Real &rfXAngle) const
Matrix3 & Slerp (Real fT, const Matrix3 &rkR0, const Matrix3 &rkR1)
void SingularValueDecomposition (Matrix3 &rkL, Matrix3 &rkS, Matrix3 &rkR) const
void SingularValueComposition (const Matrix3 &rkL, const Matrix3 &rkS, const Matrix3 &rkR)
void QDUDecomposition (Matrix3 &rkQ, Matrix3 &rkD, Matrix3 &rkU) const
const Matrix3< float > ZERO (0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f)
const Matrix3< float > IDENTITY (1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f)
const Matrix3< double > ZERO (0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0)
const Matrix3< double > IDENTITY (1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0)
Static Public Attributes
static const Matrix3 ZERO
static const Matrix3 IDENTITY
Detailed Description
template<class Real>
class Wm4::Matrix3< Real >
Definition at line 61 of file Wm4Matrix3.h.
Constructor & Destructor Documentation
Matrix3() [1/9]
template<class Real > Wm4::Matrix3< Real >::Matrix3 (bool bZero = true)
Matrix3() [2/9]
template<class Real > Wm4::Matrix3< Real >::Matrix3 (const Matrix3< Real > & rkM)
Matrix3() [3/9]
template<class Real > Wm4::Matrix3< Real >::Matrix3 (Real fM00, Real fM01, Real fM02, Real fM10, Real fM11, Real fM12, Real fM20, Real fM21, Real fM22)
Matrix3() [4/9]
template<class Real > Wm4::Matrix3< Real >::Matrix3 (const Real afEntry[9], bool bRowMajor)
Matrix3() [5/9]
template<class Real > Wm4::Matrix3< Real >::Matrix3 (const Vector3< Real > & rkU, const Vector3< Real > & rkV, const Vector3< Real > & rkW, bool bColumns)
Matrix3() [6/9]
template<class Real > Wm4::Matrix3< Real >::Matrix3 (const Vector3< Real > * akV, bool bColumns)
Matrix3() [7/9]
template<class Real > Wm4::Matrix3< Real >::Matrix3 (Real fM00, Real fM11, Real fM22)
Matrix3() [8/9]
template<class Real > Wm4::Matrix3< Real >::Matrix3 (const Vector3< Real > & rkAxis, Real fAngle)
Matrix3() [9/9]
template<class Real > Wm4::Matrix3< Real >::Matrix3 (const Vector3< Real > & rkU, const Vector3< Real > & rkV)
Member Function Documentation
Adjoint()
template<class Real > Matrix3 Wm4::Matrix3< Real >::Adjoint () const
Determinant()
template<class Real > Real Wm4::Matrix3< Real >::Determinant () const
DiagonalTimes()
template<class Real > Matrix3 Wm4::Matrix3< Real >::DiagonalTimes (const Vector3< Real > & rkDiag) const
EigenDecomposition()
template<class Real > void Wm4::Matrix3< Real >::EigenDecomposition (Matrix3< Real > & rkRot, Matrix3< Real > & rkDiag) const
Referenced by MeshCore::QuadraticFit::CalcEigenValues(), and MeshCore::PlaneFit::Fit().
FromAxisAngle()
template<class Real > Matrix3& Wm4::Matrix3< Real >::FromAxisAngle (const Vector3< Real > & rkAxis, Real fAngle)
FromEulerAnglesXYZ()
template<class Real > Matrix3& Wm4::Matrix3< Real >::FromEulerAnglesXYZ (Real fXAngle, Real fYAngle, Real fZAngle)
FromEulerAnglesXZY()
template<class Real > Matrix3& Wm4::Matrix3< Real >::FromEulerAnglesXZY (Real fXAngle, Real fZAngle, Real fYAngle)
FromEulerAnglesYXZ()
template<class Real > Matrix3& Wm4::Matrix3< Real >::FromEulerAnglesYXZ (Real fYAngle, Real fXAngle, Real fZAngle)
FromEulerAnglesYZX()
template<class Real > Matrix3& Wm4::Matrix3< Real >::FromEulerAnglesYZX (Real fYAngle, Real fZAngle, Real fXAngle)
FromEulerAnglesZXY()
template<class Real > Matrix3& Wm4::Matrix3< Real >::FromEulerAnglesZXY (Real fZAngle, Real fXAngle, Real fYAngle)
FromEulerAnglesZYX()
template<class Real > Matrix3& Wm4::Matrix3< Real >::FromEulerAnglesZYX (Real fZAngle, Real fYAngle, Real fXAngle)
GetColumn()
template<class Real > Vector3<Real> Wm4::Matrix3< Real >::GetColumn (int iCol) const
Referenced by MeshCore::QuadraticFit::CalcEigenValues(), and MeshCore::PlaneFit::Fit().
GetColumnMajor()
template<class Real > void Wm4::Matrix3< Real >::GetColumnMajor (Real * afCMajor) const
GetRow()
template<class Real > Vector3<Real> Wm4::Matrix3< Real >::GetRow (int iRow) const
IDENTITY() [1/2]
const Matrix3< double > Wm4::Matrix3< double >::IDENTITY (1. 0, 0. 0, 0. 0, 0. 0, 1. 0, 0. 0, 0. 0, 0. 0, 1. 0)
IDENTITY() [2/2]
const Matrix3< float > Wm4::Matrix3< float >::IDENTITY (1. 0f, 0. 0f, 0. 0f, 0. 0f, 1. 0f, 0. 0f, 0. 0f, 0. 0f, 1. 0f)
Inverse()
template<class Real > Matrix3 Wm4::Matrix3< Real >::Inverse () const
Referenced by Wm4::MeshCurvature< Real >::MeshCurvature().
MakeDiagonal()
template<class Real > Matrix3& Wm4::Matrix3< Real >::MakeDiagonal (Real fM00, Real fM11, Real fM22)
MakeIdentity()
template<class Real > Matrix3& Wm4::Matrix3< Real >::MakeIdentity ()
MakeTensorProduct()
template<class Real > Matrix3& Wm4::Matrix3< Real >::MakeTensorProduct (const Vector3< Real > & rkU, const Vector3< Real > & rkV)
MakeZero()
template<class Real > Matrix3& Wm4::Matrix3< Real >::MakeZero ()
operator const Real *()
template<class Real > Wm4::Matrix3< Real >::operator const Real * () const
operator Real *()
template<class Real > Wm4::Matrix3< Real >::operator Real * ()
operator!=()
template<class Real > bool Wm4::Matrix3< Real >::operator!= (const Matrix3< Real > & rkM) const
operator()() [1/2]
template<class Real > Real& Wm4::Matrix3< Real >::operator() (int iRow, int iCol)
operator()() [2/2]
template<class Real > Real Wm4::Matrix3< Real >::operator() (int iRow, int iCol) const
operator*() [1/3]
template<class Real > Matrix3 Wm4::Matrix3< Real >::operator* (const Matrix3< Real > & rkM) const
operator*() [2/3]
template<class Real > Vector3<Real> Wm4::Matrix3< Real >::operator* (const Vector3< Real > & rkV) const
operator*() [3/3]
template<class Real > Matrix3 Wm4::Matrix3< Real >::operator* (Real fScalar) const
operator*=()
template<class Real > Matrix3& Wm4::Matrix3< Real >::operator*= (Real fScalar)
operator+()
template<class Real > Matrix3 Wm4::Matrix3< Real >::operator+ (const Matrix3< Real > & rkM) const
operator+=()
template<class Real > Matrix3& Wm4::Matrix3< Real >::operator+= (const Matrix3< Real > & rkM)
operator-() [1/2]
template<class Real > Matrix3 Wm4::Matrix3< Real >::operator- () const
operator-() [2/2]
template<class Real > Matrix3 Wm4::Matrix3< Real >::operator- (const Matrix3< Real > & rkM) const
operator-=()
template<class Real > Matrix3& Wm4::Matrix3< Real >::operator-= (const Matrix3< Real > & rkM)
operator/()
template<class Real > Matrix3 Wm4::Matrix3< Real >::operator/ (Real fScalar) const
operator/=()
template<class Real > Matrix3& Wm4::Matrix3< Real >::operator/= (Real fScalar)
operator<()
template<class Real > bool Wm4::Matrix3< Real >::operator< (const Matrix3< Real > & rkM) const
operator<=()
template<class Real > bool Wm4::Matrix3< Real >::operator<= (const Matrix3< Real > & rkM) const
operator=()
template<class Real > Matrix3& Wm4::Matrix3< Real >::operator= (const Matrix3< Real > & rkM)
operator==()
template<class Real > bool Wm4::Matrix3< Real >::operator== (const Matrix3< Real > & rkM) const
operator>()
template<class Real > bool Wm4::Matrix3< Real >::operator> (const Matrix3< Real > & rkM) const
operator>=()
template<class Real > bool Wm4::Matrix3< Real >::operator>= (const Matrix3< Real > & rkM) const
operator[]() [1/2]
template<class Real > Real* Wm4::Matrix3< Real >::operator[] (int iRow)
operator[]() [2/2]
template<class Real > const Real* Wm4::Matrix3< Real >::operator[] (int iRow) const
Orthonormalize()
template<class Real > void Wm4::Matrix3< Real >::Orthonormalize ()
QDUDecomposition()
template<class Real > void Wm4::Matrix3< Real >::QDUDecomposition (Matrix3< Real > & rkQ, Matrix3< Real > & rkD, Matrix3< Real > & rkU) const
QForm()
template<class Real > Real Wm4::Matrix3< Real >::QForm (const Vector3< Real > & rkU, const Vector3< Real > & rkV) const
SetColumn()
template<class Real > void Wm4::Matrix3< Real >::SetColumn (int iCol, const Vector3< Real > & rkV)
SetRow()
template<class Real > void Wm4::Matrix3< Real >::SetRow (int iRow, const Vector3< Real > & rkV)
SingularValueComposition()
template<class Real > void Wm4::Matrix3< Real >::SingularValueComposition (const Matrix3< Real > & rkL, const Matrix3< Real > & rkS, const Matrix3< Real > & rkR)
SingularValueDecomposition()
template<class Real > void Wm4::Matrix3< Real >::SingularValueDecomposition (Matrix3< Real > & rkL, Matrix3< Real > & rkS, Matrix3< Real > & rkR) const
Slerp()
template<class Real > Matrix3& Wm4::Matrix3< Real >::Slerp (Real fT, const Matrix3< Real > & rkR0, const Matrix3< Real > & rkR1)
TimesDiagonal()
template<class Real > Matrix3 Wm4::Matrix3< Real >::TimesDiagonal (const Vector3< Real > & rkDiag) const
TimesTranspose()
template<class Real > Matrix3 Wm4::Matrix3< Real >::TimesTranspose (const Matrix3< Real > & rkM) const
ToAxisAngle()
template<class Real > void Wm4::Matrix3< Real >::ToAxisAngle (Vector3< Real > & rkAxis, Real & rfAngle) const
ToEulerAnglesXYZ()
template<class Real > bool Wm4::Matrix3< Real >::ToEulerAnglesXYZ (Real & rfXAngle, Real & rfYAngle, Real & rfZAngle) const
ToEulerAnglesXZY()
template<class Real > bool Wm4::Matrix3< Real >::ToEulerAnglesXZY (Real & rfXAngle, Real & rfZAngle, Real & rfYAngle) const
ToEulerAnglesYXZ()
template<class Real > bool Wm4::Matrix3< Real >::ToEulerAnglesYXZ (Real & rfYAngle, Real & rfXAngle, Real & rfZAngle) const
ToEulerAnglesYZX()
template<class Real > bool Wm4::Matrix3< Real >::ToEulerAnglesYZX (Real & rfYAngle, Real & rfZAngle, Real & rfXAngle) const
ToEulerAnglesZXY()
template<class Real > bool Wm4::Matrix3< Real >::ToEulerAnglesZXY (Real & rfZAngle, Real & rfXAngle, Real & rfYAngle) const
ToEulerAnglesZYX()
template<class Real > bool Wm4::Matrix3< Real >::ToEulerAnglesZYX (Real & rfZAngle, Real & rfYAngle, Real & rfXAngle) const
Transpose()
template<class Real > Matrix3 Wm4::Matrix3< Real >::Transpose () const
TransposeTimes()
template<class Real > Matrix3 Wm4::Matrix3< Real >::TransposeTimes (const Matrix3< Real > & rkM) const
ZERO() [1/2]
const Matrix3< double > Wm4::Matrix3< double >::ZERO (0. 0, 0. 0, 0. 0, 0. 0, 0. 0, 0. 0, 0. 0, 0. 0, 0. 0)
ZERO() [2/2]
const Matrix3< float > Wm4::Matrix3< float >::ZERO (0. 0f, 0. 0f, 0. 0f, 0. 0f, 0. 0f, 0. 0f, 0. 0f, 0. 0f, 0. 0f)
Member Data Documentation
IDENTITY
template<class Real > const Matrix3 Wm4::Matrix3< Real >::IDENTITY static
Definition at line 220 of file Wm4Matrix3.h.
ZERO
template<class Real > const Matrix3 Wm4::Matrix3< Real >::ZERO static
Definition at line 219 of file Wm4Matrix3.h.
The documentation for this class was generated from the following file:
Wm4Matrix3.h