FreeCAD: CAMTests.TestPathToolBit Namespace Reference
CAMTests.TestPathToolBit Namespace Reference
Classes
class TestPathToolBit
Functions
def testToolShape (path=TestToolDir, name=TestToolShapeName)
def testToolBit (path=TestToolDir, name=TestToolBitName)
def testToolLibrary (path=TestToolDir, name=TestToolLibraryName)
def printTree (path, indent)
Variables
TestToolDir = os.path.join(os.path.dirname(os.path.realpath(__file__)), "Tools")
TestInvalidDir
string TestToolBitName = "test-path-tool-bit-bit-00.fctb"
string TestToolShapeName = "test-path-tool-bit-shape-00.fcstd"
string TestToolLibraryName = "test-path-tool-bit-library-00.fctl"
Function Documentation
printTree()
def CAMTests.TestPathToolBit.printTree (path, indent)
Definition at line 50 of file TestPathToolBit.py.
Referenced by CAMTests.TestPathToolBit.TestPathToolBit.test().
testToolBit()
def CAMTests.TestPathToolBit.testToolBit (path = TestToolDir, name = TestToolBitName)
Definition at line 42 of file TestPathToolBit.py.
Referenced by CAMTests.TestPathToolBit.TestPathToolBit.test02(), CAMTests.TestPathToolBit.TestPathToolBit.test12(), CAMTests.TestPathToolBit.TestPathToolBit.test13(), CAMTests.TestPathToolBit.TestPathToolBit.test14(), and CAMTests.TestPathToolBit.TestPathToolBit.test24().
testToolLibrary()
def CAMTests.TestPathToolBit.testToolLibrary (path = TestToolDir, name = TestToolLibraryName)
Definition at line 46 of file TestPathToolBit.py.
Referenced by CAMTests.TestPathToolBit.TestPathToolBit.test12(), and CAMTests.TestPathToolBit.TestPathToolBit.test23().
testToolShape()
def CAMTests.TestPathToolBit.testToolShape (path = TestToolDir, name = TestToolShapeName)
Definition at line 38 of file TestPathToolBit.py.
Referenced by CAMTests.TestPathToolBit.TestPathToolBit.test02(), CAMTests.TestPathToolBit.TestPathToolBit.test03(), and CAMTests.TestPathToolBit.TestPathToolBit.test04().
Variable Documentation
TestInvalidDir
CAMTests.TestPathToolBit.TestInvalidDir
Initial value:
 =  os.path.join(
     TestToolDir, "some", "silly", "path", "that", "should", "not", "exist"
 )
Definition at line 29 of file TestPathToolBit.py.
TestToolBitName
string CAMTests.TestPathToolBit.TestToolBitName = "test-path-tool-bit-bit-00.fctb"
Definition at line 33 of file TestPathToolBit.py.
TestToolDir
CAMTests.TestPathToolBit.TestToolDir = os.path.join(os.path.dirname(os.path.realpath(__file__)), "Tools")
Definition at line 28 of file TestPathToolBit.py.
TestToolLibraryName
string CAMTests.TestPathToolBit.TestToolLibraryName = "test-path-tool-bit-library-00.fctl"
Definition at line 35 of file TestPathToolBit.py.
TestToolShapeName
string CAMTests.TestPathToolBit.TestToolShapeName = "test-path-tool-bit-shape-00.fcstd"
Definition at line 34 of file TestPathToolBit.py.