FreeCAD: Gui::TPlanarDragger Class Reference
Gui::TPlanarDragger Class Reference
Planar Translation Dragger.
#include <SoFCCSysDragger.h>
Public Member Functions
TPlanarDragger ()
Static Public Member Functions
static void initClass ()
Public Attributes
SoSFVec3f translation
set from outside and used from outside for single precision.
SoSFDouble translationIncrement
set from outside and used for rounding.
SoSFInt32 translationIncrementXCount
number of steps. used from outside.
SoSFInt32 translationIncrementYCount
number of steps. used from outside.
SoSFFloat autoScaleResult
set from parent dragger.
Protected Member Functions
~TPlanarDragger () override
SbBool setUpConnections (SbBool onoff, SbBool doitalways=FALSE) override
void dragStart ()
void drag ()
void dragFinish ()
Static Protected Member Functions
static void startCB (void *, SoDragger *d)
static void motionCB (void *, SoDragger *d)
static void finishCB (void *, SoDragger *d)
static void fieldSensorCB (void *f, SoSensor *)
static void valueChangedCB (void *, SoDragger *d)
Protected Attributes
SoFieldSensor fieldSensor
SbPlaneProjector projector
Detailed Description
Planar Translation Dragger.
used for translating on a plane. Set the translationIncrement to desired step. Use 'translationIncrementXCount' or 'translationIncrementYCount' multiplied with 'translationIncrement' for a full double precision vector scalar.
Author
qewer33
Definition at line 118 of file SoFCCSysDragger.h.
Constructor & Destructor Documentation
TPlanarDragger()
TPlanarDragger::TPlanarDragger ()
Definition at line 430 of file SoFCCSysDragger.cpp.
References autoScaleResult, fieldSensor, fieldSensorCB(), finishCB(), motionCB(), setUpConnections(), startCB(), translation, translationIncrement, translationIncrementXCount, translationIncrementYCount, SCL.Builtin::TRUE, and valueChangedCB().
~TPlanarDragger()
TPlanarDragger::~TPlanarDragger () override protected
Definition at line 481 of file SoFCCSysDragger.cpp.
References fieldSensor, finishCB(), motionCB(), startCB(), and valueChangedCB().
Member Function Documentation
drag()
void TPlanarDragger::drag () protected
Definition at line 611 of file SoFCCSysDragger.cpp.
References autoScaleResult, SCL.SimpleDataTypes::f, Gui::getMainWindow(), Base::Quantity::getUserString(), Base::Unit::Length, projector, Gui::MainWindow::showMessage(), translationIncrement, translationIncrementXCount, and translationIncrementYCount.
dragFinish()
void TPlanarDragger::dragFinish () protected
Definition at line 652 of file SoFCCSysDragger.cpp.
dragStart()
void TPlanarDragger::dragStart () protected
Definition at line 591 of file SoFCCSysDragger.cpp.
References projector, translationIncrementXCount, and translationIncrementYCount.
fieldSensorCB()
void TPlanarDragger::fieldSensorCB (void * f, SoSensor *) static protected
Definition at line 560 of file SoFCCSysDragger.cpp.
References SCL.SimpleDataTypes::f.
Referenced by setUpConnections(), and TPlanarDragger().
finishCB()
void TPlanarDragger::finishCB (void * , SoDragger * d) static protected
Definition at line 553 of file SoFCCSysDragger.cpp.
Referenced by TPlanarDragger(), and ~TPlanarDragger().
initClass()
void TPlanarDragger::initClass () static
Definition at line 425 of file SoFCCSysDragger.cpp.
Referenced by Gui::SoFCCSysDragger::initClass(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
motionCB()
void TPlanarDragger::motionCB (void * , SoDragger * d) static protected
Definition at line 546 of file SoFCCSysDragger.cpp.
Referenced by TPlanarDragger(), and ~TPlanarDragger().
setUpConnections()
SbBool TPlanarDragger::setUpConnections (SbBool onoff, SbBool doitalways = FALSE) override protected
Definition at line 659 of file SoFCCSysDragger.cpp.
References fieldSensor, fieldSensorCB(), and translation.
Referenced by TPlanarDragger().
startCB()
void TPlanarDragger::startCB (void * , SoDragger * d) static protected
Definition at line 539 of file SoFCCSysDragger.cpp.
Referenced by TPlanarDragger(), and ~TPlanarDragger().
valueChangedCB()
void TPlanarDragger::valueChangedCB (void * , SoDragger * d) static protected
Definition at line 573 of file SoFCCSysDragger.cpp.
Referenced by TPlanarDragger(), and ~TPlanarDragger().
Member Data Documentation
autoScaleResult
SoSFFloat Gui::TPlanarDragger::autoScaleResult
set from parent dragger.
Definition at line 131 of file SoFCCSysDragger.h.
Referenced by drag(), Gui::SoFCCSysDragger::SoFCCSysDragger(), and TPlanarDragger().
fieldSensor
SoFieldSensor Gui::TPlanarDragger::fieldSensor protected
Definition at line 147 of file SoFCCSysDragger.h.
Referenced by setUpConnections(), TPlanarDragger(), and ~TPlanarDragger().
projector
SbPlaneProjector Gui::TPlanarDragger::projector protected
Definition at line 148 of file SoFCCSysDragger.h.
Referenced by drag(), and dragStart().
translation
SoSFVec3f Gui::TPlanarDragger::translation
set from outside and used from outside for single precision.
Definition at line 127 of file SoFCCSysDragger.h.
Referenced by setUpConnections(), and TPlanarDragger().
translationIncrement
SoSFDouble Gui::TPlanarDragger::translationIncrement
set from outside and used for rounding.
Definition at line 128 of file SoFCCSysDragger.h.
Referenced by drag(), Gui::SoFCCSysDragger::SoFCCSysDragger(), and TPlanarDragger().
translationIncrementXCount
SoSFInt32 Gui::TPlanarDragger::translationIncrementXCount
number of steps. used from outside.
Definition at line 129 of file SoFCCSysDragger.h.
Referenced by drag(), dragStart(), Gui::SoFCCSysDragger::SoFCCSysDragger(), and TPlanarDragger().
translationIncrementYCount
SoSFInt32 Gui::TPlanarDragger::translationIncrementYCount
number of steps. used from outside.
Definition at line 130 of file SoFCCSysDragger.h.
Referenced by drag(), dragStart(), Gui::SoFCCSysDragger::SoFCCSysDragger(), and TPlanarDragger().
The documentation for this class was generated from the following files:
SoFCCSysDragger.h
SoFCCSysDragger.cpp