FreeCAD: Materials::Material Class Reference
Materials::Material Class Reference
#include <Materials.h>
Public Types
enum ModelEdit { ModelEdit_None, ModelEdit_Alter, ModelEdit_Extend }
Public Member Functions
Material ()
Material (const std::shared_ptr< MaterialLibrary > &library, const QString &directory, const QString &uuid, const QString &name)
Material (const Material &other)
~Material () override=default
std::shared_ptr< MaterialLibrary > getLibrary () const
QString getDirectory () const
QString getUUID () const
QString getName () const
QString getAuthorAndLicense () const
QString getAuthor () const
QString getLicense () const
QString getParentUUID () const
QString getDescription () const
QString getURL () const
QString getReference () const
ModelEdit getEditState () const
const QSet< QString > & getTags () const
const QSet< QString > * getPhysicalModels () const
const QSet< QString > * getAppearanceModels () const
App::Material getMaterialAppearance () const
void setLibrary (const std::shared_ptr< MaterialLibrary > &library)
void setDirectory (const QString &directory)
void setUUID (const QString &uuid)
void setName (const QString &name)
void setAuthor (const QString &author)
void setLicense (const QString &license)
void setParentUUID (const QString &uuid)
void setDescription (const QString &description)
void setURL (const QString &url)
void setReference (const QString &reference)
void setEditState (ModelEdit newState)
void setEditStateAlter ()
void setEditStateExtend ()
void setPropertyEditState (const QString &name)
void setPhysicalEditState (const QString &name)
void setAppearanceEditState (const QString &name)
void resetEditState ()
void addTag (const QString &tag)
void removeTag (const QString &tag)
void addPhysical (const QString &uuid)
void removePhysical (const QString &uuid)
void addAppearance (const QString &uuid)
void removeAppearance (const QString &uuid)
void clearModels ()
void clearInherited ()
void newUuid ()
void setPhysicalValue (const QString &name, const QString &value)
void setPhysicalValue (const QString &name, int value)
void setPhysicalValue (const QString &name, double value)
void setPhysicalValue (const QString &name, const Base::Quantity &value)
void setPhysicalValue (const QString &name, const std::shared_ptr< MaterialValue > &value)
void setPhysicalValue (const QString &name, const std::shared_ptr< QList< QVariant >> &value)
void setPhysicalValue (const QString &name, const QVariant &value)
void setAppearanceValue (const QString &name, const QString &value)
void setAppearanceValue (const QString &name, const std::shared_ptr< MaterialValue > &value)
void setAppearanceValue (const QString &name, const std::shared_ptr< QList< QVariant >> &value)
void setAppearanceValue (const QString &name, const QVariant &value)
void setValue (const QString &name, const QString &value)
void setValue (const QString &name, const QVariant &value)
void setLegacyValue (const QString &name, const QString &value)
std::shared_ptr< MaterialProperty > getPhysicalProperty (const QString &name)
std::shared_ptr< MaterialProperty > getPhysicalProperty (const QString &name) const
std::shared_ptr< MaterialProperty > getAppearanceProperty (const QString &name)
std::shared_ptr< MaterialProperty > getAppearanceProperty (const QString &name) const
std::shared_ptr< MaterialProperty > getProperty (const QString &name)
std::shared_ptr< MaterialProperty > getProperty (const QString &name) const
QVariant getPhysicalValue (const QString &name) const
Base::Quantity getPhysicalQuantity (const QString &name) const
QString getPhysicalValueString (const QString &name) const
QVariant getAppearanceValue (const QString &name) const
Base::Quantity getAppearanceQuantity (const QString &name) const
QString getAppearanceValueString (const QString &name) const
bool hasPhysicalProperty (const QString &name) const
bool hasAppearanceProperty (const QString &name) const
bool hasNonLegacyProperty (const QString &name) const
bool hasLegacyProperty (const QString &name) const
bool hasLegacyProperties () const
bool hasPhysicalProperties () const
bool hasAppearanceProperties () const
bool hasModel (const QString &uuid) const
bool hasPhysicalModel (const QString &uuid) const
bool hasAppearanceModel (const QString &uuid) const
bool isInherited (const QString &uuid) const
bool isModelComplete (const QString &uuid) const
bool isPhysicalModelComplete (const QString &uuid) const
bool isAppearanceModelComplete (const QString &uuid) const
std::map< QString, std::shared_ptr< MaterialProperty > > & getPhysicalProperties ()
const std::map< QString, std::shared_ptr< MaterialProperty > > & getPhysicalProperties () const
std::map< QString, std::shared_ptr< MaterialProperty > > & getAppearanceProperties ()
const std::map< QString, std::shared_ptr< MaterialProperty > > & getAppearanceProperties () const
std::map< QString, QString > & getLegacyProperties ()
QString getModelByName (const QString &name) const
bool getDereferenced () const
void markDereferenced ()
void clearDereferenced ()
bool isOldFormat () const
void setOldFormat (bool isOld)
void updateInheritance (const QString &parent)
QStringList inheritedMissingModels (const Material &parent) const
QStringList inheritedAddedModels (const Material &parent) const
void inheritedPropertyDiff (const QString &parent)
void save (QTextStream &stream, bool overwrite, bool saveAsCopy, bool saveInherited)
Material & operator= (const Material &other)
Material & operator= (const App::Material &other)
bool operator== (const Material &other) const
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static QStringList normalizeModels (const QStringList &models)
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Protected Member Functions
void addModel (const QString &uuid)
bool modelChanged (const std::shared_ptr< Material > &parent, const std::shared_ptr< Model > &model) const
bool modelAppearanceChanged (const std::shared_ptr< Material > &parent, const std::shared_ptr< Model > &model) const
void saveGeneral (QTextStream &stream) const
void saveInherits (QTextStream &stream) const
void saveModels (QTextStream &stream, bool saveInherited) const
void saveAppearanceModels (QTextStream &stream, bool saveInherited) const
Static Protected Member Functions
static void removeUUID (QSet< QString > &uuidList, const QString &uuid)
static QVariant getValue (const std::map< QString, std::shared_ptr< MaterialProperty >> &propertyList, const QString &name)
static QString getValueString (const std::map< QString, std::shared_ptr< MaterialProperty >> &propertyList, const QString &name)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 178 of file Materials.h.
Member Enumeration Documentation
ModelEdit
enum Materials::Material::ModelEdit
Enumerator
ModelEdit_None
ModelEdit_Alter
ModelEdit_Extend
Definition at line 183 of file Materials.h.
Constructor & Destructor Documentation
Material() [1/3]
Material::Material ()
Definition at line 453 of file Materials.cpp.
Material() [2/3]
Material::Material (const std::shared_ptr< MaterialLibrary > & library, const QString & directory, const QString & uuid, const QString & name)
Definition at line 462 of file Materials.cpp.
References setDirectory().
Material() [3/3]
Material::Material (const Material & other)
Definition at line 476 of file Materials.cpp.
~Material()
Materials::Material::~Material () override default
Member Function Documentation
addAppearance()
void Material::addAppearance (const QString & uuid)
Definition at line 715 of file Materials.cpp.
References addModel(), Base::Console(), hasAppearanceModel(), hasAppearanceProperty(), Base::ConsoleSingleton::Log(), propertyName(), removeUUID(), and setEditStateExtend().
Referenced by operator=().
addModel()
void Material::addModel (const QString & uuid) protected
Definition at line 534 of file Materials.cpp.
Referenced by addAppearance(), and addPhysical().
addPhysical()
void Material::addPhysical (const QString & uuid)
Definition at line 638 of file Materials.cpp.
References addModel(), Base::Console(), Base::ConsoleSingleton::Error(), hasPhysicalModel(), hasPhysicalProperty(), propertyName(), removeUUID(), and setEditStateExtend().
addTag()
void Materials::Material::addTag (const QString & tag) inline
Definition at line 294 of file Materials.h.
clearDereferenced()
void Materials::Material::clearDereferenced () inline
Definition at line 398 of file Materials.h.
clearInherited()
void Material::clearInherited ()
Definition at line 566 of file Materials.cpp.
clearModels()
void Material::clearModels ()
Definition at line 557 of file Materials.cpp.
getAppearanceModels()
const QSet<QString>* Materials::Material::getAppearanceModels () const inline
Definition at line 251 of file Materials.h.
getAppearanceProperties() [1/2]
std::map<QString, std::shared_ptr<MaterialProperty> >& Materials::Material::getAppearanceProperties () inline
Definition at line 375 of file Materials.h.
getAppearanceProperties() [2/2]
const std::map<QString, std::shared_ptr<MaterialProperty> >& Materials::Material::getAppearanceProperties () const inline
Definition at line 379 of file Materials.h.
getAppearanceProperty() [1/2]
std::shared_ptr< MaterialProperty > Material::getAppearanceProperty (const QString & name)
Definition at line 973 of file Materials.cpp.
Referenced by getMaterialAppearance(), getProperty(), isAppearanceModelComplete(), modelAppearanceChanged(), operator=(), saveAppearanceModels(), and setAppearanceEditState().
getAppearanceProperty() [2/2]
std::shared_ptr< MaterialProperty > Material::getAppearanceProperty (const QString & name) const
Definition at line 983 of file Materials.cpp.
getAppearanceQuantity()
Base::Quantity Material::getAppearanceQuantity (const QString & name) const
Definition at line 1078 of file Materials.cpp.
References getValue().
getAppearanceValue()
QVariant Material::getAppearanceValue (const QString & name) const
Definition at line 1073 of file Materials.cpp.
References getValue().
getAppearanceValueString()
QString Material::getAppearanceValueString (const QString & name) const
Definition at line 1083 of file Materials.cpp.
References getValueString().
getAuthor()
QString Materials::Material::getAuthor () const inline
Definition at line 215 of file Materials.h.
getAuthorAndLicense()
QString Material::getAuthorAndLicense () const
Definition at line 516 of file Materials.cpp.
getDereferenced()
bool Materials::Material::getDereferenced () const inline
Definition at line 390 of file Materials.h.
getDescription()
QString Materials::Material::getDescription () const inline
Definition at line 227 of file Materials.h.
getDirectory()
QString Materials::Material::getDirectory () const inline
Definition at line 202 of file Materials.h.
getEditState()
ModelEdit Materials::Material::getEditState () const inline
Definition at line 239 of file Materials.h.
getLegacyProperties()
std::map<QString, QString>& Materials::Material::getLegacyProperties () inline
Definition at line 383 of file Materials.h.
getLibrary()
std::shared_ptr<MaterialLibrary> Materials::Material::getLibrary () const inline
Definition at line 198 of file Materials.h.
getLicense()
QString Materials::Material::getLicense () const inline
Definition at line 219 of file Materials.h.
getMaterialAppearance()
App::Material Material::getMaterialAppearance () const
Definition at line 1650 of file Materials.cpp.
References App::Material::ambientColor, Base::Console(), App::Material::DEFAULT, App::Material::diffuseColor, App::Material::emissiveColor, getAppearanceProperty(), getUUID(), hasAppearanceProperty(), App::Material::image, App::Material::imagePath, Base::ConsoleSingleton::Log(), App::Material::setType(), App::Material::shininess, App::Material::specularColor, App::Material::transparency, App::Material::USER_DEFINED, and App::Material::uuid.
Referenced by Part::Feature::getMaterialAppearance().
getModelByName()
QString Material::getModelByName (const QString & name) const
Definition at line 1422 of file Materials.cpp.
getName()
QString Materials::Material::getName () const inline
Definition at line 210 of file Materials.h.
getParentUUID()
QString Materials::Material::getParentUUID () const inline
Definition at line 223 of file Materials.h.
getPhysicalModels()
const QSet<QString>* Materials::Material::getPhysicalModels () const inline
Definition at line 247 of file Materials.h.
getPhysicalProperties() [1/2]
std::map<QString, std::shared_ptr<MaterialProperty> >& Materials::Material::getPhysicalProperties () inline
Definition at line 367 of file Materials.h.
getPhysicalProperties() [2/2]
const std::map<QString, std::shared_ptr<MaterialProperty> >& Materials::Material::getPhysicalProperties () const inline
Definition at line 371 of file Materials.h.
getPhysicalProperty() [1/2]
std::shared_ptr< MaterialProperty > Material::getPhysicalProperty (const QString & name)
Definition at line 953 of file Materials.cpp.
Referenced by getProperty(), isPhysicalModelComplete(), modelChanged(), saveModels(), and setPhysicalEditState().
getPhysicalProperty() [2/2]
std::shared_ptr< MaterialProperty > Material::getPhysicalProperty (const QString & name) const
Definition at line 963 of file Materials.cpp.
getPhysicalQuantity()
Base::Quantity Material::getPhysicalQuantity (const QString & name) const
Definition at line 1063 of file Materials.cpp.
References getValue().
getPhysicalValue()
QVariant Material::getPhysicalValue (const QString & name) const
Definition at line 1058 of file Materials.cpp.
References getValue().
getPhysicalValueString()
QString Material::getPhysicalValueString (const QString & name) const
Definition at line 1068 of file Materials.cpp.
References getValueString().
getProperty() [1/2]
std::shared_ptr< MaterialProperty > Material::getProperty (const QString & name)
Definition at line 993 of file Materials.cpp.
References getAppearanceProperty(), getPhysicalProperty(), hasAppearanceProperty(), and hasPhysicalProperty().
getProperty() [2/2]
std::shared_ptr< MaterialProperty > Material::getProperty (const QString & name) const
Definition at line 1004 of file Materials.cpp.
References getAppearanceProperty(), getPhysicalProperty(), hasAppearanceProperty(), and hasPhysicalProperty().
getReference()
QString Materials::Material::getReference () const inline
Definition at line 235 of file Materials.h.
getTags()
const QSet<QString>& Materials::Material::getTags () const inline
Definition at line 243 of file Materials.h.
getURL()
QString Materials::Material::getURL () const inline
Definition at line 231 of file Materials.h.
getUUID()
QString Materials::Material::getUUID () const inline
Definition at line 206 of file Materials.h.
Referenced by Part::Feature::copyMaterial(), getMaterialAppearance(), PartDesign::Body::onChanged(), and Materials::PropertyMaterial::Save().
getValue()
QVariant Material::getValue (const std::map< QString, std::shared_ptr< MaterialProperty >> & propertyList, const QString & name) static protected
Definition at line 1016 of file Materials.cpp.
Referenced by getAppearanceQuantity(), getAppearanceValue(), getPhysicalQuantity(), and getPhysicalValue().
getValueString()
QString Material::getValueString (const std::map< QString, std::shared_ptr< MaterialProperty >> & propertyList, const QString & name) static protected
Definition at line 1028 of file Materials.cpp.
References Materials::MaterialValue::Float, Base::Quantity::getUserString(), Materials::MaterialValue::PRECISION, and Materials::MaterialValue::Quantity.
Referenced by getAppearanceValueString(), and getPhysicalValueString().
hasAppearanceModel()
bool Material::hasAppearanceModel (const QString & uuid) const
Definition at line 1158 of file Materials.cpp.
References hasModel(), and Materials::Model::ModelType_Appearance.
Referenced by addAppearance(), isAppearanceModelComplete(), operator=(), and removeAppearance().
hasAppearanceProperties()
bool Material::hasAppearanceProperties () const
Definition at line 1116 of file Materials.cpp.
hasAppearanceProperty()
bool Material::hasAppearanceProperty (const QString & name) const
Definition at line 1093 of file Materials.cpp.
Referenced by addAppearance(), getMaterialAppearance(), getProperty(), hasNonLegacyProperty(), setAppearanceValue(), setPropertyEditState(), and setValue().
hasLegacyProperties()
bool Material::hasLegacyProperties () const
Definition at line 1106 of file Materials.cpp.
hasLegacyProperty()
bool Materials::Material::hasLegacyProperty (const QString & name) const
hasModel()
bool Material::hasModel (const QString & uuid) const
Definition at line 1133 of file Materials.cpp.
Referenced by hasAppearanceModel(), hasPhysicalModel(), and inheritedMissingModels().
hasNonLegacyProperty()
bool Material::hasNonLegacyProperty (const QString & name) const
Definition at line 1098 of file Materials.cpp.
References hasAppearanceProperty(), and hasPhysicalProperty().
hasPhysicalModel()
bool Material::hasPhysicalModel (const QString & uuid) const
Definition at line 1138 of file Materials.cpp.
References hasModel(), and Materials::Model::ModelType_Physical.
Referenced by addPhysical(), isPhysicalModelComplete(), and removePhysical().
hasPhysicalProperties()
bool Material::hasPhysicalProperties () const
Definition at line 1111 of file Materials.cpp.
hasPhysicalProperty()
bool Material::hasPhysicalProperty (const QString & name) const
Definition at line 1088 of file Materials.cpp.
Referenced by addPhysical(), getProperty(), hasNonLegacyProperty(), setPhysicalValue(), setPropertyEditState(), and setValue().
inheritedAddedModels()
QStringList Material::inheritedAddedModels (const Material & parent) const
Definition at line 1627 of file Materials.cpp.
References normalizeModels(), and Init::parent.
inheritedMissingModels()
QStringList Material::inheritedMissingModels (const Material & parent) const
Definition at line 1612 of file Materials.cpp.
References hasModel(), normalizeModels(), and Init::parent.
inheritedPropertyDiff()
void Material::inheritedPropertyDiff (const QString & parent)
Definition at line 1643 of file Materials.cpp.
isAppearanceModelComplete()
bool Material::isAppearanceModelComplete (const QString & uuid) const
Definition at line 1204 of file Materials.cpp.
References getAppearanceProperty(), hasAppearanceModel(), and propertyName().
isInherited()
bool Material::isInherited (const QString & uuid) const
Definition at line 1121 of file Materials.cpp.
Referenced by removeAppearance(), and removePhysical().
isModelComplete()
bool Materials::Material::isModelComplete (const QString & uuid) const inline
Definition at line 360 of file Materials.h.
isOldFormat()
bool Materials::Material::isOldFormat () const inline
Definition at line 402 of file Materials.h.
isPhysicalModelComplete()
bool Material::isPhysicalModelComplete (const QString & uuid) const
Definition at line 1178 of file Materials.cpp.
References getPhysicalProperty(), hasPhysicalModel(), and propertyName().
markDereferenced()
void Materials::Material::markDereferenced () inline
Definition at line 394 of file Materials.h.
modelAppearanceChanged()
bool Material::modelAppearanceChanged (const std::shared_ptr< Material > & parent, const std::shared_ptr< Model > & model) const protected
Definition at line 1290 of file Materials.cpp.
References getAppearanceProperty(), Init::parent, and propertyName().
Referenced by saveAppearanceModels().
modelChanged()
bool Material::modelChanged (const std::shared_ptr< Material > & parent, const std::shared_ptr< Model > & model) const protected
Definition at line 1269 of file Materials.cpp.
References getPhysicalProperty(), Init::parent, and propertyName().
Referenced by saveModels().
newUuid()
void Material::newUuid ()
Definition at line 1417 of file Materials.cpp.
Referenced by save().
normalizeModels()
QStringList Material::normalizeModels (const QStringList & models) static
Definition at line 1573 of file Materials.cpp.
Referenced by inheritedAddedModels(), and inheritedMissingModels().
operator=() [1/2]
Material & Material::operator= (const App::Material & other)
Definition at line 1545 of file Materials.cpp.
References addAppearance(), App::Material::ambientColor, App::Material::diffuseColor, App::Material::emissiveColor, getAppearanceProperty(), hasAppearanceModel(), App::Material::image, App::Material::imagePath, Materials::ModelUUIDs::ModelUUID_Rendering_Basic, Materials::ModelUUIDs::ModelUUID_Rendering_Texture, App::Material::shininess, App::Material::specularColor, and App::Material::transparency.
operator=() [2/2]
Material & Material::operator= (const Material & other)
Definition at line 1489 of file Materials.cpp.
operator==()
bool Materials::Material::operator== (const Material & other) const inline
Definition at line 446 of file Materials.h.
removeAppearance()
void Material::removeAppearance (const QString & uuid)
Definition at line 751 of file Materials.cpp.
References hasAppearanceModel(), isInherited(), removeUUID(), and setEditStateAlter().
removePhysical()
void Material::removePhysical (const QString & uuid)
Definition at line 680 of file Materials.cpp.
References Base::Console(), hasPhysicalModel(), isInherited(), Base::ConsoleSingleton::Log(), removeUUID(), and setEditStateAlter().
removeTag()
void Materials::Material::removeTag (const QString & tag) inline
Definition at line 298 of file Materials.h.
removeUUID()
void Material::removeUUID (QSet< QString > & uuidList, const QString & uuid) static protected
Definition at line 633 of file Materials.cpp.
Referenced by addAppearance(), addPhysical(), removeAppearance(), and removePhysical().
resetEditState()
void Materials::Material::resetEditState () inline
Definition at line 290 of file Materials.h.
save()
void Material::save (QTextStream & stream, bool overwrite, bool saveAsCopy, bool saveInherited)
Definition at line 1440 of file Materials.cpp.
References App::Application::Config(), Materials::MaterialManager::exists(), newUuid(), saveAppearanceModels(), saveGeneral(), saveInherits(), saveModels(), setOldFormat(), and setParentUUID().
Referenced by src.Mod.Show.mTempoVis.TempoVis::modify(), src.Mod.Show.mTempoVis.TempoVis::modifyVPProperty(), and src.Mod.Show.mTempoVis.TempoVis::saveCamera().
saveAppearanceModels()
void Material::saveAppearanceModels (QTextStream & stream, bool saveInherited) const protected
Definition at line 1365 of file Materials.cpp.
References Materials::MaterialValue::escapeString(), getAppearanceProperty(), Materials::MaterialManager::getMaterial(), Materials::ModelManager::getModel(), modelAppearanceChanged(), Init::parent, and propertyName().
Referenced by save().
saveGeneral()
void Material::saveGeneral (QTextStream & stream) const protected
Definition at line 1230 of file Materials.cpp.
References Materials::MaterialValue::escapeString().
Referenced by save().
saveInherits()
void Material::saveInherits (QTextStream & stream) const protected
Definition at line 1252 of file Materials.cpp.
Referenced by save().
saveModels()
void Material::saveModels (QTextStream & stream, bool saveInherited) const protected
Definition at line 1311 of file Materials.cpp.
References Base::Console(), Materials::MaterialValue::escapeString(), Materials::MaterialManager::getMaterial(), Materials::ModelManager::getModel(), getPhysicalProperty(), Base::ConsoleSingleton::Log(), modelChanged(), Init::parent, and propertyName().
Referenced by save().
setAppearanceEditState()
void Material::setAppearanceEditState (const QString & name)
Definition at line 809 of file Materials.cpp.
References getAppearanceProperty(), draftgeoutils.general::isNull(), setEditStateAlter(), and setEditStateExtend().
Referenced by setAppearanceValue(), and setPropertyEditState().
setAppearanceValue() [1/4]
void Material::setAppearanceValue (const QString & name, const QString & value)
Definition at line 886 of file Materials.cpp.
References hasAppearanceProperty(), and setAppearanceEditState().
Referenced by setValue().
setAppearanceValue() [2/4]
void Material::setAppearanceValue (const QString & name, const QVariant & value)
Definition at line 914 of file Materials.cpp.
References hasAppearanceProperty(), and setAppearanceEditState().
setAppearanceValue() [3/4]
void Material::setAppearanceValue (const QString & name, const std::shared_ptr< MaterialValue > & value)
Definition at line 895 of file Materials.cpp.
References hasAppearanceProperty(), and setAppearanceEditState().
setAppearanceValue() [4/4]
void Material::setAppearanceValue (const QString & name, const std::shared_ptr< QList< QVariant >> & value)
Definition at line 904 of file Materials.cpp.
References hasAppearanceProperty(), and setAppearanceEditState().
setAuthor()
void Material::setAuthor (const QString & author)
Definition at line 585 of file Materials.cpp.
References setEditStateExtend().
setDescription()
void Material::setDescription (const QString & description)
Definition at line 603 of file Materials.cpp.
References setEditStateExtend().
setDirectory()
void Materials::Material::setDirectory (const QString & directory) inline
Definition at line 262 of file Materials.h.
Referenced by Material().
setEditState()
void Material::setEditState (ModelEdit newState)
Definition at line 621 of file Materials.cpp.
References ModelEdit_Alter, and ModelEdit_Extend.
setEditStateAlter()
void Materials::Material::setEditStateAlter () inline
Definition at line 279 of file Materials.h.
References Dice3DS.dom3ds::tag.
Referenced by removeAppearance(), removePhysical(), setAppearanceEditState(), setLegacyValue(), and setPhysicalEditState().
setEditStateExtend()
void Materials::Material::setEditStateExtend () inline
Definition at line 283 of file Materials.h.
Referenced by addAppearance(), addPhysical(), setAppearanceEditState(), setAuthor(), setDescription(), setLicense(), setName(), setParentUUID(), setPhysicalEditState(), setReference(), and setURL().
setLegacyValue()
void Material::setLegacyValue (const QString & name, const QString & value)
Definition at line 946 of file Materials.cpp.
References setEditStateAlter().
setLibrary()
void Materials::Material::setLibrary (const std::shared_ptr< MaterialLibrary > & library) inline
Definition at line 258 of file Materials.h.
setLicense()
void Material::setLicense (const QString & license)
Definition at line 591 of file Materials.cpp.
References setEditStateExtend().
setName()
void Material::setName (const QString & name)
Definition at line 579 of file Materials.cpp.
References setEditStateExtend().
setOldFormat()
void Materials::Material::setOldFormat (bool isOld) inline
Definition at line 406 of file Materials.h.
Referenced by save().
setParentUUID()
void Material::setParentUUID (const QString & uuid)
Definition at line 597 of file Materials.cpp.
References setEditStateExtend().
Referenced by save().
setPhysicalEditState()
void Material::setPhysicalEditState (const QString & name)
Definition at line 799 of file Materials.cpp.
References getPhysicalProperty(), draftgeoutils.general::isNull(), setEditStateAlter(), and setEditStateExtend().
Referenced by setPhysicalValue(), and setPropertyEditState().
setPhysicalValue() [1/7]
void Material::setPhysicalValue (const QString & name, const Base::Quantity & value)
Definition at line 850 of file Materials.cpp.
References hasPhysicalProperty(), and setPhysicalEditState().
setPhysicalValue() [2/7]
void Material::setPhysicalValue (const QString & name, const QString & value)
Definition at line 823 of file Materials.cpp.
References hasPhysicalProperty(), and setPhysicalEditState().
Referenced by setValue().
setPhysicalValue() [3/7]
void Material::setPhysicalValue (const QString & name, const QVariant & value)
Definition at line 877 of file Materials.cpp.
References hasPhysicalProperty(), and setPhysicalEditState().
setPhysicalValue() [4/7]
void Material::setPhysicalValue (const QString & name, const std::shared_ptr< MaterialValue > & value)
Definition at line 859 of file Materials.cpp.
References hasPhysicalProperty(), and setPhysicalEditState().
setPhysicalValue() [5/7]
void Material::setPhysicalValue (const QString & name, const std::shared_ptr< QList< QVariant >> & value)
Definition at line 868 of file Materials.cpp.
References hasPhysicalProperty(), and setPhysicalEditState().
setPhysicalValue() [6/7]
void Material::setPhysicalValue (const QString & name, double value)
Definition at line 841 of file Materials.cpp.
References hasPhysicalProperty(), and setPhysicalEditState().
setPhysicalValue() [7/7]
void Material::setPhysicalValue (const QString & name, int value)
Definition at line 832 of file Materials.cpp.
References hasPhysicalProperty(), and setPhysicalEditState().
setPropertyEditState()
void Material::setPropertyEditState (const QString & name)
Definition at line 785 of file Materials.cpp.
References hasAppearanceProperty(), hasPhysicalProperty(), setAppearanceEditState(), and setPhysicalEditState().
setReference()
void Material::setReference (const QString & reference)
Definition at line 615 of file Materials.cpp.
References setEditStateExtend().
setURL()
void Material::setURL (const QString & url)
Definition at line 609 of file Materials.cpp.
References setEditStateExtend().
setUUID()
void Materials::Material::setUUID (const QString & uuid) inline
Definition at line 266 of file Materials.h.
setValue() [1/2]
void Material::setValue (const QString & name, const QString & value)
Definition at line 923 of file Materials.cpp.
References hasAppearanceProperty(), hasPhysicalProperty(), setAppearanceValue(), and setPhysicalValue().
setValue() [2/2]
void Material::setValue (const QString & name, const QVariant & value)
Definition at line 936 of file Materials.cpp.
References hasPhysicalProperty(), and setPhysicalValue().
updateInheritance()
void Material::updateInheritance (const QString & parent)
Definition at line 1605 of file Materials.cpp.
The documentation for this class was generated from the following files:
Materials.h
Materials.cpp