FreeCAD: CommandSketcherOverlay.cpp File Reference
CommandSketcherOverlay.cpp File Reference
#include "PreCompiled.h"
#include <Inventor/SbString.h>
#include <QApplication>
#include <cfloat>
#include <App/Application.h>
#include <Base/Console.h>
#include <Gui/Action.h>
#include <Gui/Application.h>
#include <Gui/BitmapFactory.h>
#include <Gui/CommandT.h>
#include <Gui/Document.h>
#include <Gui/MainWindow.h>
#include <Gui/Notifications.h>
#include <Gui/Selection.h>
#include <Gui/SelectionObject.h>
#include <Mod/Sketcher/App/SketchObject.h>
#include "DrawSketchHandler.h"
#include "Utils.h"
#include "ViewProviderSketch.h"
Functions
void ShowRestoreInformationLayer (const char *visibleelementname)
void CreateSketcherCommandsOverlay ()
Function Documentation
CreateSketcherCommandsOverlay()
void CreateSketcherCommandsOverlay ()
Definition at line 385 of file CommandSketcherOverlay.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
ShowRestoreInformationLayer()
void ShowRestoreInformationLayer (const char * visibleelementname)
Definition at line 52 of file CommandSketcherOverlay.cpp.
References App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), and ParameterGrp::SetBool().