FreeCAD: Gui::Dialog::Transform Class Reference
Gui::Dialog::Transform Class Reference
#include <Transform.h>
Public Member Functions
Transform (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~Transform () override
void accept () override
void reject () override
void showStandardButtons (bool)
void setTransformStrategy (TransformStrategy *ts)
void onApplyButtonClicked ()
Protected Member Functions
Base::Vector3d getDirection () const
void changeEvent (QEvent *e) override
Detailed Description
Definition at line 111 of file Transform.h.
Constructor & Destructor Documentation
Transform()
Transform::Transform (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags())
Definition at line 277 of file Transform.cpp.
References draftgeoutils.intersections::connect(), onApplyButtonClicked(), setTransformStrategy(), and Gui::QuantitySpinBox::valueChanged().
~Transform()
Transform::~Transform () override
Definition at line 312 of file Transform.cpp.
Member Function Documentation
accept()
void Transform::accept () override
Definition at line 343 of file Transform.cpp.
References onApplyButtonClicked().
Referenced by Gui::Dialog::TaskTransform::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
changeEvent()
void Transform::changeEvent (QEvent * e) override protected
Definition at line 409 of file Transform.cpp.
References SCL.SimpleDataTypes::e.
getDirection()
Base::Vector3d Transform::getDirection () const protected
Definition at line 376 of file Transform.cpp.
References MovieTool::x, and MovieTool::y.
onApplyButtonClicked()
void Transform::onApplyButtonClicked ()
Definition at line 355 of file Transform.cpp.
References Gui::Dialog::TransformStrategy::commitTransform(), Gui::Dialog::TransformStrategy::getRotationCenter(), Base::Unit::Length, Base::Placement::toMatrix(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by accept(), Gui::Dialog::TaskTransform::clicked(), and Transform().
reject()
void Transform::reject () override
Definition at line 349 of file Transform.cpp.
References Gui::Dialog::TransformStrategy::resetTransform().
Referenced by bimcommands.BimReorder.BIM_Reorder_TaskPanel::accept(), draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), draftguitools.gui_selectplane.Draft_SelectPlane::action(), JointObject.TaskAssemblyCreateJoint::autoClosedOnTransactionChange(), femexamples.examplesgui.FemExamples::clicked(), CommandCreateView.TaskAssemblyCreateView::KeyboardEvent(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), bimcommands.BimProjectManager.BIM_ProjectManager::loadTemplate(), bimcommands.BimLibrary.BIM_Library_TaskPanel::mouseClick(), Gui::Dialog::TaskTransform::reject(), bimcommands.BimProjectManager.BIM_ProjectManager::saveTemplate(), and Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit().
setTransformStrategy()
void Transform::setTransformStrategy (TransformStrategy * ts)
Definition at line 318 of file Transform.cpp.
References Gui::Dialog::TransformStrategy::getRotationCenter(), Base::Unit::Length, Gui::Dialog::TransformStrategy::transformObjects(), src.Mod.Test.UnitTests::ts(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by Gui::Dialog::TaskTransform::setTransformStrategy(), and Transform().
showStandardButtons()
void Transform::showStandardButtons (bool b)
Definition at line 332 of file Transform.cpp.
References SCL.SimpleDataTypes::b.
Referenced by Gui::Dialog::TaskTransform::TaskTransform().
The documentation for this class was generated from the following files:
Transform.h
Transform.cpp