FreeCAD: MeshGui::ViewProviderMeshBuilder Class Reference
MeshGui::ViewProviderMeshBuilder Class Reference
#include <ViewProvider.h>
Public Member Functions
ViewProviderMeshBuilder ()=default
void buildNodes (const App::Property *prop, std::vector< SoNode * > &nodes) const override
void createMesh (const App::Property *, SoCoordinate3 *, SoIndexedFaceSet *) const
void createMesh (const MeshCore::MeshKernel &, SoCoordinate3 *, SoIndexedFaceSet *) const
Public Member Functions inherited from Gui::ViewProviderBuilder
ViewProviderBuilder ()
Constructor.
virtual ~ViewProviderBuilder ()
Additional Inherited Members
Static Public Member Functions inherited from Gui::ViewProviderBuilder
static void add (const Base::Type &, const Base::Type &)
static ViewProvider * create (const Base::Type &)
static SoFCSelection * createSelection ()
Detailed Description
Definition at line 88 of file Mod/Mesh/Gui/ViewProvider.h.
Constructor & Destructor Documentation
ViewProviderMeshBuilder()
MeshGui::ViewProviderMeshBuilder::ViewProviderMeshBuilder () default
Member Function Documentation
buildNodes()
void ViewProviderMeshBuilder::buildNodes (const App::Property * prop, std::vector< SoNode * > & nodes) const override virtual
Implements Gui::ViewProviderBuilder.
Definition at line 108 of file Mod/Mesh/Gui/ViewProvider.cpp.
References createMesh().
createMesh() [1/2]
void ViewProviderMeshBuilder::createMesh (const App::Property * prop, SoCoordinate3 * coords, SoIndexedFaceSet * faces) const
Definition at line 134 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Mesh2Shape::mesh.
Referenced by MeshGui::ThumbnailExtension3MF::addMesh(), buildNodes(), MeshGui::ViewProviderMesh::exportToVrml(), MeshGui::ViewProviderMeshFaceSet::updateData(), and MeshGui::ViewProviderIndexedFaceSet::updateData().
createMesh() [2/2]
void ViewProviderMeshBuilder::createMesh (const MeshCore::MeshKernel & kernel, SoCoordinate3 * coords, SoIndexedFaceSet * faces) const
Definition at line 143 of file Mod/Mesh/Gui/ViewProvider.cpp.
References MeshCore::MeshKernel::CountFacets(), MeshCore::MeshKernel::CountPoints(), MeshCore::MeshKernel::GetFacets(), MeshCore::MeshKernel::GetPoints(), and SplineSurface::i.
The documentation for this class was generated from the following files:
Mod/Mesh/Gui/ViewProvider.h
Mod/Mesh/Gui/ViewProvider.cpp