FreeCAD: App::GroupExtension Class Reference
App::GroupExtension Class Reference
#include <GroupExtension.h>
Public Member Functions
GroupExtension ()
Constructor.
~GroupExtension () override
Public Member Functions inherited from App::DocumentObjectExtension
virtual Base::Type getExtensionTypeId (void) const override
DocumentObjectExtension ()
~DocumentObjectExtension () override
App::DocumentObject * getExtendedObject ()
const App::DocumentObject * getExtendedObject () const
virtual short extensionMustExecute ()
virtual void onExtendedSettingDocument ()
get called after setting the document
virtual void onExtendedDocumentRestored ()
get called after a document has been fully restored
virtual void onExtendedSetupObject ()
get called after a brand new object was created
virtual void onExtendedUnsetupObject ()
get called when object is going to be removed from the document
virtual const char * getViewProviderExtensionName () const
virtual bool extensionGetLinkedObject (DocumentObject *&ret, bool recursive, Base::Matrix4D *mat, bool transform, int depth) const
virtual int extensionSetElementVisible (const char *, bool)
virtual int extensionIsElementVisible (const char *)
virtual bool extensionHasChildElement () const
Public Member Functions inherited from App::Extension
Extension ()=default
virtual ~Extension ()
virtual void initExtension (App::ExtensionContainer *obj)
App::ExtensionContainer * getExtendedContainer ()
const App::ExtensionContainer * getExtendedContainer () const
std::string name () const
bool isPythonExtension ()
virtual Property * extensionGetPropertyByName (const char *name) const
find a property by its name
virtual const char * extensionGetPropertyName (const Property *prop) const
get the name of a property
virtual void extensionGetPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual void extensionGetPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual short extensionGetPropertyType (const Property *prop) const
get the Type of a Property
virtual short extensionGetPropertyType (const char *name) const
get the Type of a named Property
virtual const char * extensionGetPropertyGroup (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * extensionGetPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual void extensionSave (Base::Writer &) const
virtual void extensionRestore (Base::XMLReader &)
bool extensionIsDerivedFrom (const Base::Type type) const
Object handling
PropertyLinkList Group
Properties.
PropertyBool _GroupTouched
virtual DocumentObject * addObject (const char *sType, const char *pObjectName)
virtual std::vector< DocumentObject * > addObject (DocumentObject *obj)
virtual std::vector< DocumentObject * > addObjects (std::vector< DocumentObject * > obj)
virtual std::vector< DocumentObject * > setObjects (std::vector< DocumentObject * > obj)
virtual bool allowObject (DocumentObject *)
virtual std::vector< DocumentObject * > removeObject (DocumentObject *obj)
virtual std::vector< DocumentObject * > removeObjects (std::vector< DocumentObject * > obj)
virtual void removeObjectsFromDocument ()
DocumentObject * getObject (const char *Name) const
virtual bool hasObject (const DocumentObject *obj, bool recursive=false) const
bool isChildOf (const GroupExtension *group, bool recursive=true) const
const std::vector< DocumentObject * > & getObjects () const
std::vector< DocumentObject * > getObjectsOfType (const Base::Type &typeId) const
int countObjectsOfType (const Base::Type &typeId) const
PyObject * getExtensionPyObject () override
void extensionOnChanged (const Property *p) override
bool extensionGetSubObject (DocumentObject *&ret, const char *subname, PyObject **pyObj, Base::Matrix4D *mat, bool transform, int depth) const override
bool extensionGetSubObjects (std::vector< std::string > &ret, int reason) const override
App::DocumentObjectExecReturn * extensionExecute () override
std::vector< DocumentObject * > getAllChildren () const
void getAllChildren (std::vector< DocumentObject * > &, std::set< DocumentObject * > &) const
static DocumentObject * getGroupOfObject (const DocumentObject *obj)
Additional Inherited Members
Static Public Member Functions inherited from App::DocumentObjectExtension
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Static Public Member Functions inherited from App::Extension
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Protected Member Functions inherited from App::DocumentObjectExtension
virtual const App::PropertyData & extensionGetPropertyData (void) const override
Protected Member Functions inherited from App::Extension
virtual bool extensionHandleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
returns true if the property name change was handled by the extension.
virtual bool extensionHandleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop)
returns true if the property type change was handled by the extension.
void initExtensionType (Base::Type type)
Static Protected Member Functions inherited from App::DocumentObjectExtension
static const App::PropertyData * extensionGetPropertyDataPtr (void)
Static Protected Member Functions inherited from App::Extension
static const App::PropertyData * extensionGetPropertyDataPtr (void)
static void initExtensionSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Base::Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Extension
bool m_isPythonExtension = false
Py::SmartPtr ExtensionPythonObject
Detailed Description
Definition at line 58 of file GroupExtension.h.
Constructor & Destructor Documentation
GroupExtension()
GroupExtension::GroupExtension ()
Constructor.
Definition at line 46 of file GroupExtension.cpp.
References EXTENSION_ADD_PROPERTY_TYPE, App::DocumentObjectExtension::getExtensionClassTypeId(), App::Prop_Hidden, App::Prop_None, and App::Prop_Transient.
Referenced by PartDesign::Body::addObject().
~GroupExtension()
GroupExtension::~GroupExtension () override default
Member Function Documentation
addObject() [1/2]
DocumentObject * GroupExtension::addObject (const char * sType, const char * pObjectName) virtual
Adds an object of sType with pObjectName to the document this group belongs to and append it to this group as well.
Definition at line 65 of file GroupExtension.cpp.
References App::Document::addObject(), allowObject(), App::DocumentObject::getDocument(), App::DocumentObjectExtension::getExtendedObject(), App::DocumentObject::getNameInDocument(), and App::Document::removeObject().
Referenced by addObjects(), ArchBuildingPart.BuildingPart::autogroup(), bimcommands.BimPanel.NestTaskPanel::getContainer(), bimcommands.BimPanel.NestTaskPanel::getShapes(), Assembly::AssemblyLink::synchronizeComponents(), and Assembly::AssemblyLink::synchronizeJoints().
addObject() [2/2]
std::vector< DocumentObject * > GroupExtension::addObject (DocumentObject * obj) virtual
Reimplemented in PartDesign::Body.
Definition at line 76 of file GroupExtension.cpp.
References addObjects(), and SurfaceTests.TestBlendCurve::vec.
Referenced by ArchBuildingPart.BuildingPart::autogroup(), bimcommands.BimPanel.NestTaskPanel::getContainer(), and bimcommands.BimPanel.NestTaskPanel::getShapes().
addObjects()
std::vector< DocumentObject * > GroupExtension::addObjects (std::vector< DocumentObject * > obj) virtual
Reimplemented in App::GeoFeatureGroupExtension, and App::OriginGroupExtension.
Definition at line 82 of file GroupExtension.cpp.
References addObject(), allowObject(), App::DocumentObjectExtension::getExtendedObject(), App::GeoFeatureGroupExtension::getGroupOfObject(), getGroupOfObject(), App::PropertyListsT< T, ListT, ParentT >::getValues(), toolbit-attributes::group, Group, toolbit-attributes::grp, hasObject(), replaceobj::objs, removeObject(), and App::PropertyLinkList::setValues().
Referenced by addObject(), and setObjects().
allowObject()
virtual bool App::GroupExtension::allowObject (DocumentObject *) inline virtual
Definition at line 87 of file GroupExtension.h.
Referenced by addObject(), addObjects(), and App::GeoFeatureGroupExtension::addObjects().
countObjectsOfType()
int GroupExtension::countObjectsOfType (const Base::Type & typeId) const
Returns the number of objects of typeId this group does have.
Definition at line 307 of file GroupExtension.cpp.
References App::PropertyListsT< T, ListT, ParentT >::getValues(), Group, toolbit-attributes::grp, and Path.Post.scripts.grbl_post::type.
extensionExecute()
App::DocumentObjectExecReturn * GroupExtension::extensionExecute () override virtual
Reimplemented from App::DocumentObjectExtension.
Reimplemented in App::OriginGroupExtension.
Definition at line 453 of file GroupExtension.cpp.
References _GroupTouched, App::DocumentObjectExtension::extensionExecute(), and App::Property::touch().
Referenced by App::OriginGroupExtension::extensionExecute().
extensionGetSubObject()
bool GroupExtension::extensionGetSubObject (DocumentObject *& ret, const char * subname, PyObject ** pyObj, Base::Matrix4D * mat, bool transform, int depth) const override virtual
Get the sub object by name
See also
DocumentObject::getSubObject()
Returns
Return turn if handled, the sub object is returned in ret
Reimplemented from App::DocumentObjectExtension.
Reimplemented in App::OriginGroupExtension.
Definition at line 408 of file GroupExtension.cpp.
References dot(), App::PropertyLinkList::findUsingMap(), App::Extension::getExtendedContainer(), App::DocumentObject::getSubObject(), App::PropertyListsT< T, ListT, ParentT >::getValues(), Group, and App::Extension::name().
extensionGetSubObjects()
bool GroupExtension::extensionGetSubObjects (std::vector< std::string > & ret, int reason) const override virtual
Get name references of all sub objects
See also
DocumentObject::getSubObjects()
Returns
Return turn if handled, the sub object is returned in ret
Reimplemented from App::DocumentObjectExtension.
Definition at line 443 of file GroupExtension.cpp.
References App::DocumentObject::getNameInDocument(), App::PropertyListsT< T, ListT, ParentT >::getValues(), Group, and App::DocumentObject::isAttachedToDocument().
extensionOnChanged()
void GroupExtension::extensionOnChanged (const Property * p) override virtual
Reimplemented from App::Extension.
Reimplemented in App::OriginGroupExtension.
Definition at line 349 of file GroupExtension.cpp.
References draftgeoutils.faces::bind(), Path.Log::error(), App::Extension::extensionOnChanged(), App::DocumentObjectExtension::getExtendedObject(), App::DocumentObjectExtension::getExtensionClassTypeId(), App::DocumentObjectExtension::getExtensionTypeId(), App::DocumentObject::getInList(), App::PropertyListsT< T, ListT, ParentT >::getValue(), App::PropertyListsT< T, ListT, ParentT >::getValues(), Group, App::DocumentObject::isAttachedToDocument(), Gui::isRestoring, buildPsets::p, App::PropertyLinkList::setValues(), App::DocumentObject::signalChanged, App::Property::testStatus(), and App::Property::User3.
Referenced by App::GeoFeatureGroupExtension::extensionOnChanged().
getAllChildren() [1/2]
std::vector< App::DocumentObject * > GroupExtension::getAllChildren () const
Definition at line 460 of file GroupExtension.cpp.
Referenced by src.Mod.Show.Containers.Container::hasObject().
getAllChildren() [2/2]
void App::GroupExtension::getAllChildren (std::vector< DocumentObject * > & , std::set< DocumentObject * > &) const
Referenced by src.Mod.Show.Containers.Container::hasObject().
getExtensionPyObject()
PyObject * GroupExtension::getExtensionPyObject () override virtual
Reimplemented from App::DocumentObjectExtension.
Definition at line 338 of file GroupExtension.cpp.
References App::Extension::ExtensionPythonObject, toolbit-attributes::grp, Py::SmartPtr::is(), and Py::new_reference_to().
getGroupOfObject()
DocumentObject * GroupExtension::getGroupOfObject (const DocumentObject * obj) static
Returns the object group of the document which the given object obj is part of. In case this object is not part of a group 0 is returned.
Note
This only returns objects that are normal groups, not any special derived type like GeoFeatureGroups or OriginGroups. To retrieve those please use their appropriate functions
Definition at line 320 of file GroupExtension.cpp.
References App::DocumentObjectExtension::getExtensionClassTypeId(), App::ExtensionPythonT< ExtensionT >::getExtensionClassTypeId(), App::DocumentObject::getInList(), and src.Mod.Test.testPathArray::o.
Referenced by PartDesign::Body::addObject(), addObjects(), App::LinkBaseExtension::elementNameFromIndex(), PartDesignGui::ViewProviderDatum::getRelevantBoundBox(), and Gui::LinkView::setChildren().
getObject()
DocumentObject * GroupExtension::getObject (const char * Name) const
Returns the object of this group with Name. If the group doesn't have such an object 0 is returned.
Note
This method might return 0 even if the document this group belongs to contains an object with this name.
Definition at line 194 of file GroupExtension.cpp.
References App::DocumentObject::getDocument(), App::DocumentObjectExtension::getExtendedObject(), App::Document::getObject(), and hasObject().
getObjects()
const std::vector< DocumentObject * > & GroupExtension::getObjects () const
Returns a list of all objects this group does have.
Definition at line 289 of file GroupExtension.cpp.
References App::PropertyListsT< T, ListT, ParentT >::getValues(), and Group.
Referenced by Assembly::AssemblyObject::getGroundedJoints(), Assembly::JointGroup::getJoints(), Assembly::AssemblyObject::getJoints(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testBuildings(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCommonPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testExtrusions(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testHierarchy(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testMaterials(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testQuantities(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSites(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSolid(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandardCases(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandards(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStoreys(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testTinyLines(), and bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testUndefined().
getObjectsOfType()
std::vector< DocumentObject * > GroupExtension::getObjectsOfType (const Base::Type & typeId) const
Returns a list of all objects of typeId this group does have.
Definition at line 294 of file GroupExtension.cpp.
References App::PropertyListsT< T, ListT, ParentT >::getValues(), Group, toolbit-attributes::grp, and Path.Post.scripts.grbl_post::type.
hasObject()
bool GroupExtension::hasObject (const DocumentObject * obj, bool recursive = false) const virtual
Checks whether the object obj is part of this group.
Parameters
obj the object to check for.
recursive if true check also if the obj is child of some sub group (default is false).
Reimplemented in App::OriginGroupExtension.
Definition at line 203 of file GroupExtension.cpp.
References SCL.SimpleDataTypes::e, App::DocumentObjectExtension::getExtendedObject(), App::DocumentObjectExtension::getExtensionClassTypeId(), App::PropertyListsT< T, ListT, ParentT >::getValues(), Group, and toolbit-attributes::grp.
Referenced by addObjects(), App::GeoFeatureGroupExtension::addObjects(), getObject(), and App::OriginGroupExtension::hasObject().
isChildOf()
bool GroupExtension::isChildOf (const GroupExtension * group, bool recursive = true) const
Checks whether this group object is a child (or sub-child if enabled) of the given group object.
Definition at line 284 of file GroupExtension.cpp.
References App::DocumentObjectExtension::getExtendedObject(), and toolbit-attributes::group.
removeObject()
std::vector< DocumentObject * > GroupExtension::removeObject (DocumentObject * obj) virtual
Removes an object from this group. Returns all objects that have been removed.
Definition at line 134 of file GroupExtension.cpp.
References removeObjects(), and SurfaceTests.TestBlendCurve::vec.
Referenced by addObjects(), and App::GeoFeatureGroupExtension::addObjects().
removeObjects()
std::vector< DocumentObject * > GroupExtension::removeObjects (std::vector< DocumentObject * > obj) virtual
Removes objects from this group. Returns all objects that have been removed.
Reimplemented in App::GeoFeatureGroupExtension.
Definition at line 140 of file GroupExtension.cpp.
References App::PropertyListsT< T, ListT, ParentT >::getValues(), Group, toolbit-attributes::grp, replaceobj::objs, and App::PropertyLinkList::setValues().
Referenced by removeObject().
removeObjectsFromDocument()
void GroupExtension::removeObjectsFromDocument () virtual
Removes all children objects from this group and the document.
Definition at line 164 of file GroupExtension.cpp.
References App::PropertyListsT< T, ListT, ParentT >::getSize(), App::PropertyListsT< T, ListT, ParentT >::getValues(), Group, and toolbit-attributes::grp.
Referenced by Assembly::AssemblyLink::ensureNoJointGroup().
setObjects()
std::vector< DocumentObject * > GroupExtension::setObjects (std::vector< DocumentObject * > obj) virtual
Definition at line 127 of file GroupExtension.cpp.
References addObjects(), Group, and App::PropertyLinkList::setValues().
Referenced by PartDesignGui::TaskBooleanParameters::onSelectionChanged().
Member Data Documentation
_GroupTouched
PropertyBool App::GroupExtension::_GroupTouched
Definition at line 157 of file GroupExtension.h.
Referenced by extensionExecute(), and PartDesign::Body::onDocumentRestored().
Group
PropertyLinkList App::GroupExtension::Group
Properties.
Definition at line 156 of file GroupExtension.h.
Referenced by ReverseEngineeringGui::Segmentation::accept(), PartDesign::Body::addObject(), addObjects(), App::GeoFeatureGroupExtension::addObjects(), AssemblyGui::ViewProviderAssembly::canDelete(), countObjectsOfType(), Assembly::AssemblyObject::ensureIdentityPlacements(), Assembly::AssemblyLink::ensureJointGroup(), Drawing::FeaturePage::execute(), PartDesign::Boolean::execute(), Import::ExportOCAF::exportObject(), extensionGetSubObject(), App::GeoFeatureGroupExtension::extensionGetSubObject(), extensionGetSubObjects(), App::GeoFeatureGroupExtension::extensionGetSubObjects(), App::GeoFeatureGroupExtension::extensionOnChanged(), extensionOnChanged(), Assembly::AssemblyObject::getGroundedParts(), PartDesign::Body::getNextSolidFeature(), getObjects(), getObjectsOfType(), PartDesign::Body::getPrevSolidFeature(), TechDraw::ShapeExtractor::getShapesFromObject(), PartDesign::Body::getSubObject(), PartDesign::Boolean::handleChangedPropertyName(), hasObject(), PartDesign::Body::insertObject(), PartDesign::Boolean::mustExecute(), Part::BodyBase::onBeforeChange(), PartDesignGui::ViewProvider::onChanged(), Assembly::AssemblyLink::onChanged(), PartDesign::Body::onChanged(), PartDesignGui::ViewProviderBoolean::onDelete(), PartDesign::Body::onDocumentRestored(), PartDesignGui::TaskBooleanParameters::onSelectionChanged(), PartDesignGui::TaskDlgBooleanParameters::reject(), PartDesign::Body::removeObject(), removeObjects(), App::GeoFeatureGroupExtension::removeObjects(), removeObjectsFromDocument(), setObjects(), PartDesignGui::ViewProviderBody::setVisualBodyMode(), Assembly::AssemblyLink::synchronizeComponents(), PartDesignGui::TaskBooleanParameters::TaskBooleanParameters(), PartDesignGui::ViewProviderBody::unifyVisualProperty(), and PartDesignGui::ViewProviderBody::updateData().
The documentation for this class was generated from the following files:
GroupExtension.h
GroupExtension.cpp