FreeCAD: Gui::PrefWidget Class Reference
Gui::PrefWidget Class Reference abstract
#include <PrefWidgets.h>
Public Member Functions
void setEntryName (const QByteArray &name)
QByteArray entryName () const
void setPrefEntry (const QByteArray &name)
void setParamGrpPath (const QByteArray &path)
QByteArray paramGrpPath () const
void setPrefPath (const QByteArray &name)
void OnChange (Base::Subject< const char * > &rCaller, const char *sReason) override
void onSave ()
void onRestore ()
Public Member Functions inherited from Gui::WindowParameter
WindowParameter (const char *name)
~WindowParameter () override
void OnChange (Base::Subject< const char * > &rCaller, const char *sReason) override
ParameterGrp::handle getWindowParameter ()
return the parameter group of this window
Protected Member Functions
virtual void restorePreferences ()=0
virtual void savePreferences ()=0
void failedToSave (const QString &) const
void failedToRestore (const QString &) const
PrefWidget ()
~PrefWidget () override
Protected Member Functions inherited from Gui::WindowParameter
bool setGroupName (const char *name)
template<typename S , typename T >
void setSlotParamChanged (S slot, T *obsPtr)
connect slot to ParameterManager signal
Protected Attributes
bool m_Restored = false
Friends
class Gui::WidgetFactoryInst
Additional Inherited Members
Static Public Member Functions inherited from Gui::WindowParameter
static ParameterGrp::handle getDefaultParameter ()
get the parameters
Detailed Description
The preference widget class. If you want to extend a QWidget class to save/restore its data you just have to derive from this class and implement the methods restorePreferences() and savePreferences().
To restore and save the settings of any widgets in own dialogs you have call onRestore() e.g. in the dialog's constructor and call onSave() e.g. in accept() for each widget you want to enable this mechanism.
For more information of how to use these widgets in normal container widgets which are again in a dialog refer to the description of Gui::Dialog::DlgPreferencesImp.
Author
Werner Mayer
Definition at line 79 of file PrefWidgets.h.
Constructor & Destructor Documentation
PrefWidget()
PrefWidget::PrefWidget () protected
Constructs a preference widget.
Definition at line 43 of file PrefWidgets.cpp.
~PrefWidget()
PrefWidget::~PrefWidget () override protected
Destroys the widget and detaches it from its parameter group.
Definition at line 51 of file PrefWidgets.cpp.
References Base::Subject< MsgType >::Detach(), Gui::WindowParameter::getWindowParameter(), and femsolver.elmer.sifio::isValid().
Member Function Documentation
entryName()
QByteArray PrefWidget::entryName () const
Returns the widget's preference name.
Definition at line 70 of file PrefWidgets.cpp.
Referenced by onSave(), Gui::PrefSpinBox::restorePreferences(), Gui::PrefDoubleSpinBox::restorePreferences(), Gui::PrefLineEdit::restorePreferences(), Gui::PrefTextEdit::restorePreferences(), Gui::PrefFileChooser::restorePreferences(), Gui::PrefComboBox::restorePreferences(), Gui::PrefCheckBox::restorePreferences(), Gui::PrefRadioButton::restorePreferences(), MatGui::PrefMaterialTreeWidget::restorePreferences(), Gui::PrefSlider::restorePreferences(), Gui::PrefColorButton::restorePreferences(), Gui::PrefUnitSpinBox::restorePreferences(), Gui::PrefQuantitySpinBox::restorePreferences(), Gui::PrefFontBox::restorePreferences(), Gui::PrefSpinBox::savePreferences(), Gui::PrefDoubleSpinBox::savePreferences(), Gui::PrefLineEdit::savePreferences(), Gui::PrefTextEdit::savePreferences(), Gui::PrefFileChooser::savePreferences(), Gui::PrefComboBox::savePreferences(), Gui::PrefCheckBox::savePreferences(), Gui::PrefRadioButton::savePreferences(), MatGui::PrefMaterialTreeWidget::savePreferences(), Gui::PrefSlider::savePreferences(), Gui::PrefColorButton::savePreferences(), Gui::PrefUnitSpinBox::savePreferences(), Gui::PrefQuantitySpinBox::savePreferences(), and Gui::PrefFontBox::savePreferences().
failedToRestore()
void PrefWidget::failedToRestore (const QString & name) const protected
Print warning that restoring failed.
Definition at line 159 of file PrefWidgets.cpp.
References src.Mod.AddonManager.addonmanager_freecad_interface::Console.
Referenced by Gui::PrefSpinBox::restorePreferences(), Gui::PrefDoubleSpinBox::restorePreferences(), Gui::PrefLineEdit::restorePreferences(), Gui::PrefTextEdit::restorePreferences(), Gui::PrefFileChooser::restorePreferences(), Gui::PrefComboBox::restorePreferences(), Gui::PrefCheckBox::restorePreferences(), Gui::PrefRadioButton::restorePreferences(), MatGui::PrefMaterialTreeWidget::restorePreferences(), Gui::PrefSlider::restorePreferences(), Gui::PrefColorButton::restorePreferences(), Gui::PrefUnitSpinBox::restorePreferences(), Gui::PrefQuantitySpinBox::restorePreferences(), and Gui::PrefFontBox::restorePreferences().
failedToSave()
void PrefWidget::failedToSave (const QString & name) const protected
Print warning that saving failed.
Definition at line 151 of file PrefWidgets.cpp.
References src.Mod.AddonManager.addonmanager_freecad_interface::Console.
Referenced by Gui::PrefSpinBox::savePreferences(), Gui::PrefDoubleSpinBox::savePreferences(), Gui::PrefLineEdit::savePreferences(), Gui::PrefTextEdit::savePreferences(), Gui::PrefFileChooser::savePreferences(), Gui::PrefComboBox::savePreferences(), Gui::PrefCheckBox::savePreferences(), Gui::PrefRadioButton::savePreferences(), MatGui::PrefMaterialTreeWidget::savePreferences(), Gui::PrefSlider::savePreferences(), Gui::PrefColorButton::savePreferences(), Gui::PrefUnitSpinBox::savePreferences(), Gui::PrefQuantitySpinBox::savePreferences(), and Gui::PrefFontBox::savePreferences().
OnChange()
void PrefWidget::OnChange (Base::Subject< const char * > & rCaller, const char * sReason) override
This method is called if one or more values in the parameter settings are changed where getParamGrp() points to. Note: This method is called for each parameter inside the parameter group. So you have to filter out the appropriate parameter with the name sReason. rCaller calls this method.
Definition at line 116 of file PrefWidgets.cpp.
References restorePreferences().
onRestore()
void PrefWidget::onRestore ()
Restores the preferences of the widget.
Definition at line 141 of file PrefWidgets.cpp.
References Gui::WindowParameter::getWindowParameter(), draftgeoutils.general::isNull(), m_Restored, and restorePreferences().
Referenced by Gui::Dialog::DlgSettingsUI::populateStylesheets(), SketcherGui::SketcherToolDefaultWidget::restoreCheckBoxPref(), and SketcherGui::SketcherToolDefaultWidget::restoreComboboxPref().
onSave()
void PrefWidget::onSave ()
Saves the current preferences of the widget. All preference widget attached to the same parameter group are notified.
Definition at line 127 of file PrefWidgets.cpp.
References entryName(), Gui::WindowParameter::getWindowParameter(), femsolver.elmer.sifio::isValid(), Base::Subject< MsgType >::Notify(), and savePreferences().
Referenced by Gui::PrefQuantitySpinBox::pushToHistory().
paramGrpPath()
QByteArray PrefWidget::paramGrpPath () const
Returns the widget's preferences path.
Definition at line 104 of file PrefWidgets.cpp.
Referenced by setParamGrpPath().
restorePreferences()
virtual void Gui::PrefWidget::restorePreferences () protected pure virtual
Restores the preferences Must be reimplemented in any subclasses.
Implemented in Gui::PrefFontBox, Gui::PrefQuantitySpinBox, Gui::PrefUnitSpinBox, Gui::PrefColorButton, Gui::PrefSlider, Gui::PrefRadioButton, MatGui::PrefMaterialTreeWidget, Gui::PrefCheckBox, Gui::PrefComboBox, Gui::PrefFileChooser, Gui::PrefTextEdit, Gui::PrefLineEdit, Gui::PrefDoubleSpinBox, and Gui::PrefSpinBox.
Referenced by OnChange(), and onRestore().
savePreferences()
virtual void Gui::PrefWidget::savePreferences () protected pure virtual
Save the preferences Must be reimplemented in any subclasses.
Implemented in Gui::PrefFontBox, Gui::PrefQuantitySpinBox, Gui::PrefUnitSpinBox, Gui::PrefColorButton, Gui::PrefSlider, Gui::PrefRadioButton, MatGui::PrefMaterialTreeWidget, Gui::PrefCheckBox, Gui::PrefComboBox, Gui::PrefFileChooser, Gui::PrefTextEdit, Gui::PrefLineEdit, Gui::PrefDoubleSpinBox, and Gui::PrefSpinBox.
Referenced by onSave().
setEntryName()
void PrefWidget::setEntryName (const QByteArray & name)
Sets the preference name to name.
Definition at line 58 of file PrefWidgets.cpp.
Referenced by Gui::WidgetFactoryInst::createPrefWidget(), SketcherGui::SketcherToolDefaultWidget::setCheckboxPrefEntry(), SketcherGui::SketcherToolDefaultWidget::setComboboxPrefEntry(), and setPrefEntry().
setParamGrpPath()
void PrefWidget::setParamGrpPath (const QByteArray & path)
Sets the preference path to path.
Definition at line 76 of file PrefWidgets.cpp.
References Base::Subject< MsgType >::Attach(), Base::Console(), Gui::WindowParameter::getWindowParameter(), femsolver.elmer.sifio::isValid(), paramGrpPath(), Gui::WindowParameter::setGroupName(), and Base::ConsoleSingleton::Warning().
Referenced by setPrefPath().
setPrefEntry()
void PrefWidget::setPrefEntry (const QByteArray & name)
Does the same as setEntryName(). This function is added for convenience because the ui compiler will use this function if the attribute stdset isn't set to 0 in a .ui file.
Sets the preference name to name.
Definition at line 64 of file PrefWidgets.cpp.
References setEntryName().
setPrefPath()
void PrefWidget::setPrefPath (const QByteArray & name)
Does the same as setParamGrpPath(). This function is added for convenience because the ui compiler will use this function if the attribute stdset isn't set to 0 in a .ui file.
Sets the preference path to path.
Definition at line 98 of file PrefWidgets.cpp.
References setParamGrpPath().
Friends And Related Function Documentation
Gui::WidgetFactoryInst
friend class Gui::WidgetFactoryInst friend
Definition at line 126 of file PrefWidgets.h.
Member Data Documentation
m_Restored
bool Gui::PrefWidget::m_Restored = false protected
Definition at line 128 of file PrefWidgets.h.
Referenced by onRestore(), Gui::PrefComboBox::restorePreferences(), and Gui::PrefColorButton::restorePreferences().
The documentation for this class was generated from the following files:
PrefWidgets.h
PrefWidgets.cpp