FreeCAD: SketcherGui::ViewProviderCustom Class Reference
SketcherGui::ViewProviderCustom Class Reference
#include <ViewProviderPython.h>
Public Member Functions
ViewProviderCustom ()
constructor
~ViewProviderCustom () override
destructor
void updateData (const App::Property *) override
Public Member Functions inherited from SketcherGui::ViewProviderSketch
ViewProviderSketch ()
constructor
~ViewProviderSketch () override
destructor
void activateHandler (std::unique_ptr< DrawSketchHandler > newHandler)
sets an DrawSketchHandler in control
void purgeHandler ()
removes the active handler
void draw (bool temp=false, bool rebuildinformationoverlay=true)
void updateColor ()
helper change the color of the sketch according to selection and solver status
void setAngleSnapping (bool enable, Base::Vector2d referencePoint=Base::Vector2d(0., 0.))
Toggle angle snapping and set the reference point.
Sketcher::SketchObject * getSketchObject () const
get the pointer to the sketch document object
const Sketcher::Sketch & getSolvedSketch () const
void updateVirtualSpace ()
updates the visibility of the virtual space of constraints
void setIsShownVirtualSpace (bool isshownvirtualspace)
bool getIsShownVirtualSpace () const
returns whether the virtual space is being shown
template<typename F >
boost::signals2::connection registerToolChanged (F &&f)
void setSketchMode (SketchMode mode)
is called by GuiCommands to set the drawing mode
SketchMode getSketchMode () const
get the sketch mode
void generateContextMenu ()
void attach (App::DocumentObject *) override
void updateData (const App::Property *) override
void setupContextMenu (QMenu *menu, QObject *receiver, const char *member) override
set up the context-menu with the supported edit modes
bool onDelete (const std::vector< std::string > &) override
is called when the Provider is in edit and a deletion request occurs
const char * getTransactionText () const override
bool selectAll () override
bool doubleClicked () override
is called by the tree if the user double clicks on the object
bool mouseMove (const SbVec2s &pos, Gui::View3DInventorViewer *viewer) override
is called when the Provider is in edit and the mouse is moved
bool keyPressed (bool pressed, int key) override
is called when the Provider is in edit and a key event ocours. Only ESC ends edit.
bool mouseButtonPressed (int Button, bool pressed, const SbVec2s &cursorPos, const Gui::View3DInventorViewer *viewer) override
is called when the Provider is in edit and the mouse is clicked
bool mouseWheelEvent (int delta, const SbVec2s &cursorPos, const Gui::View3DInventorViewer *viewer) override
void deleteSelected ()
QIcon mergeColorfulOverlayIcons (const QIcon &orig) const override
Control the overlays appearing on the Tree and reflecting different sketcher states.
bool isSelectable () const override
Is the view provider selectable.
void onSelectionChanged (const Gui::SelectionChanges &msg) override
Observer message from the Selection.
void centerSelection ()
float getScaleFactor () const
returns the scale factor
int getViewOrientationFactor () const
returns view orientation factor
Public Member Functions inherited from PartGui::ViewProvider2DObject
ViewProvider2DObject ()
constructor
~ViewProvider2DObject () override
destructor
std::vector< std::string > getDisplayModes () const override
returns a list of all possible display modes
const char * getDefaultDisplayMode () const override
get the default display mode
Public Member Functions inherited from PartGui::ViewProviderPart
ViewProviderPart ()
constructor
~ViewProviderPart () override
destructor
Public Member Functions inherited from PartGui::ViewProviderPartExt
ViewProviderPartExt ()
constructor
~ViewProviderPartExt () override
destructor
void setDisplayMode (const char *ModeName) override
set the display mode
std::vector< std::string > getDisplayModes () const override
returns a list of all possible modes
void reload ()
Update the view representation.
bool changeFaceAppearances ()
If no other task is pending it opens a dialog to allow one to change face colors.
bool useNewSelectionModel () const override
indicates if the ViewProvider use the new Selection model
std::string getElement (const SoDetail *) const override
return a hit element to the selection path or 0
SoDetail * getDetail (const char *) const override
return the coin node detail of the subelement
std::vector< Base::Vector3d > getModelPoints (const SoPickedPoint *) const override
std::vector< Base::Vector3d > getSelectionShape (const char *Element) const override
return the highlight lines for a given element or the whole shape
void setHighlightedFaces (const std::vector< App::Material > &materials)
void setHighlightedFaces (const App::PropertyMaterialList &appearance)
void unsetHighlightedFaces ()
void setHighlightedEdges (const std::vector< App::Color > &colors)
void unsetHighlightedEdges ()
void setHighlightedPoints (const std::vector< App::Color > &colors)
void unsetHighlightedPoints ()
std::map< std::string, App::Color > getElementColors (const char *element=nullptr) const override
bool isUpdateForced () const override
void forceUpdate (bool enable=true) override
bool allowOverride (const App::DocumentObject &) const override
PyObject * getPyObject () override
Get the python wrapper for that ViewProvider.
Public Member Functions inherited from Gui::ViewProviderGeometryObject
ViewProviderGeometryObject ()
constructor.
~ViewProviderGeometryObject () override
destructor.
SoPickedPointList getPickedPoints (const SbVec2s &pos, const View3DInventorViewer &viewer, bool pickAll=false) const
SoPickedPoint * getPickedPoint (const SbVec2s &pos, const View3DInventorViewer &viewer) const
virtual void showBoundingBox (bool)
Public Member Functions inherited from Gui::ViewProviderDragger
ViewProviderDragger ()
constructor.
~ViewProviderDragger () override
destructor.
Base::Placement getTransformOrigin () const
Convenience method to obtain the transform origin.
void setTransformOrigin (const Base::Placement &placement)
Convenience method to set the transform origin.
void resetTransformOrigin ()
Resets transform origin to the object origin.
ViewProvider * startEditing (int ModNum=0) override
void updatePlacementFromDragger ()
updates placement of object based on dragger position
void updateTransformFromDragger ()
updates transform of object based on dragger position, can be used to preview movement
Base::Placement getObjectPlacement () const
Gets object placement relative to its coordinate system.
Base::Placement getDraggerPlacement () const
Gets current dragger placement, including current dragger movement.
Base::Placement getOriginalDraggerPlacement () const
Gets original dragger placement, without current dragger movement.
void setDraggerPlacement (const Base::Placement &placement)
Sets placement of dragger relative to objects origin.
Public Member Functions inherited from Gui::ViewProviderDocumentObject
ViewProviderDocumentObject ()
constructor.
~ViewProviderDocumentObject () override
destructor.
virtual void reattach (App::DocumentObject *)
void update (const App::Property *) override
void setActiveMode ()
Set the active mode, i.e. the first item of the 'Display' property.
void hide () override
Hide the object in the view.
void show () override
Show the object in the view.
bool canDropObjectEx (App::DocumentObject *, App::DocumentObject *, const char *, const std::vector< std::string > &) const override
int replaceObject (App::DocumentObject *, App::DocumentObject *) override
bool showInTree () const override
void getTaskViewContent (std::vector< Gui::TaskView::TaskContent * > &) const override
Get a list of TaskBoxes associated with this object.
void updateView ()
Run a redraw.
App::DocumentObject * getObject () const
Get the object of this ViewProvider object.
template<class T >
T * getObject () const
Get the object of this ViewProvider object as specified type.
bool canDelete (App::DocumentObject *obj) const override
Asks the view provider if the given object can be deleted.
virtual bool acceptDeletionsInEdit ()
Ask the view provider if it accepts object deletions while in edit.
Gui::Document * getDocument () const
Get the GUI document to this ViewProvider object.
bool getElementPicked (const SoPickedPoint *, std::string &subname) const override
return a hit element given the picked point which contains the full node path
bool getDetailPath (const char *subname, SoFullPath *pPath, bool append, SoDetail *&det) const override
return the coin node detail and path to the node of the subname
int getTreeRank () const
void setTreeRank (int value)
bool removeDynamicProperty (const char *prop) override
App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false) override
virtual ViewProviderDocumentObject * getLinkedViewProvider (std::string *subname=nullptr, bool recursive=false) const
std::string getFullName () const override
void setShowable (bool enable)
bool isShowable () const
void startDefaultEditMode ()
Public Member Functions inherited from Gui::ViewProvider
ViewProvider ()
constructor.
~ViewProvider () override
destructor.
virtual SoSeparator * getRoot () const
SoSwitch * getModeSwitch () const
SoTransform * getTransformNode () const
SoSeparator * getAnnotation ()
virtual SoSeparator * getFrontRoot () const
virtual SoGroup * getChildRoot () const
virtual SoSeparator * getBackRoot () const
virtual bool canAddToSceneGraph () const
Indicate whether to be added to scene graph or not.
virtual bool isPartOfPhysicalObject () const
virtual std::vector< App::DocumentObject * > claimChildren3D () const
int partialRender (const std::vector< std::string > &subelements, bool clear)
Base::BoundBox3d getBoundingBox (const char *subname=nullptr, bool transform=true, MDIView *view=nullptr) const
virtual void beforeDelete ()
virtual bool canDragObjects () const
virtual bool canDragObject (App::DocumentObject *) const
virtual bool canDragObjectToTarget (App::DocumentObject *obj, App::DocumentObject *target) const
virtual void dragObject (App::DocumentObject *)
virtual bool canDropObjects () const
virtual bool canDropObject (App::DocumentObject *) const
virtual bool canDragAndDropObject (App::DocumentObject *) const
virtual void dropObject (App::DocumentObject *)
virtual bool acceptReorderingObjects () const
virtual std::string getDropPrefix () const
return a subname referencing the sub-object holding the dropped objects
virtual std::string dropObjectEx (App::DocumentObject *obj, App::DocumentObject *owner, const char *subname, const std::vector< std::string > &elements)
virtual bool canRemoveChildrenFromRoot () const
std::string getActiveDisplayMode () const
virtual bool isShow () const
checks whether the view provider is visible or not
void setVisible (bool)
bool isVisible () const
void setLinkVisible (bool)
bool isLinkVisible () const
virtual void setOverrideMode (const std::string &mode)
Overrides the display mode with mode.
const std::string getOverrideMode ()
virtual QIcon getIcon () const
deliver the icon shown in the tree view
virtual std::vector< App::DocumentObject * > claimChildren () const
virtual std::vector< App::DocumentObject * > claimChildrenRecursive () const
bool isUpdatesEnabled () const
void setUpdatesEnabled (bool enable)
unsigned long getStatus () const
return the status bits
bool testStatus (ViewStatus pos) const
void setStatus (ViewStatus pos, bool on)
std::string toString () const
virtual void setElementColors (const std::map< std::string, App::Color > &colors)
bool isEditing () const
void finishEditing ()
virtual void setTransformation (const Base::Matrix4D &rcMatrix)
set the viewing transformation of the provider
virtual void setTransformation (const SbMatrix &rcMatrix)
virtual MDIView * getMDIView () const
void Restore (Base::XMLReader &reader) override
bool isRestoring ()
void addDisplayMaskMode (SoNode *node, const char *type)
Adds a new display mask mode.
void setDisplayMaskMode (const char *type)
Activates the display mask mode type.
SoNode * getDisplayMaskMode (const char *type) const
Get the node to the display mask mode type.
std::vector< std::string > getDisplayMaskModes () const
Returns a list of added display mask modes.
void setDefaultMode (int)
int getDefaultMode () const
virtual void setRenderCacheMode (int)
Public Member Functions inherited from App::TransactionalObject
TransactionalObject ()
Constructor.
~TransactionalObject () override
Public Member Functions inherited from App::ExtensionContainer
ExtensionContainer ()
~ExtensionContainer () override
void registerExtension (Base::Type extension, App::Extension *ext)
bool hasExtension (Base::Type, bool derived=true) const
bool hasExtension (const std::string &name) const
bool hasExtensions () const
App::Extension * getExtension (Base::Type, bool derived=true, bool no_except=false) const
App::Extension * getExtension (const std::string &name) const
template<typename ExtensionT >
ExtensionT * getExtension () const
template<typename ExtensionT >
ExtensionT * getExtensionByType (bool no_except=false, bool derived=true) const
std::vector< Extension * > getExtensionsDerivedFrom (Base::Type type) const
template<typename ExtensionT >
std::vector< ExtensionT * > getExtensionsDerivedFromType () const
ExtensionIterator extensionBegin ()
ExtensionIterator extensionEnd ()
Property * getPropertyByName (const char *name) const override
find a property by its name
template<typename T >
T * getPropertyByName (const char *name) const
find a property by its name, dynamic cased to specified type
const char * getPropertyName (const Property *prop) const override
get the name of a property
void getPropertyMap (std::map< std::string, Property * > &Map) const override
get all properties of the class (including properties of the parent)
void getPropertyList (std::vector< Property * > &List) const override
get all properties of the class (including properties of the parent)
short getPropertyType (const Property *prop) const override
get the Type of a Property
short getPropertyType (const char *name) const override
get the Type of a named Property
const char * getPropertyGroup (const Property *prop) const override
get the Group of a Property
const char * getPropertyGroup (const char *name) const override
get the Group of a named Property
const char * getPropertyDocumentation (const Property *prop) const override
get the Group of a Property
const char * getPropertyDocumentation (const char *name) const override
get the Group of a named Property
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
void saveExtensions (Base::Writer &writer) const
void restoreExtensions (Base::XMLReader &reader)
void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop) override
Public Member Functions inherited from App::PropertyContainer
PropertyContainer ()
~PropertyContainer () override
unsigned int getMemSize () const override
virtual void getPropertyNamedList (std::vector< std::pair< const char *, Property * > > &List) const
get all properties with their names, may contain duplicates and aliases
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
bool isReadOnly (const Property *prop) const
check if the property is read-only
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isHidden (const Property *prop) const
check if the property is hidden
bool isHidden (const char *name) const
check if the named property is hidden
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
bool changeDynamicProperty (const Property *prop, const char *group, const char *doc)
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual App::Property * getDynamicPropertyByName (const char *name) const
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
virtual void beforeSave () const
virtual void editProperty (const char *)
const char * getPropertyPrefix () const
void setPropertyPrefix (const char *prefix)
PropertyContainer (const PropertyContainer &)=delete
PropertyContainer & operator= (const PropertyContainer &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from PartGui::ViewProviderGridExtension
ViewProviderGridExtension ()
constructor
~ViewProviderGridExtension () override
void setGridEnabled (bool enable)
void drawGrid (bool cameraUpdate)
void extensionUpdateData (const App::Property *) override
SoSeparator * getGridNode ()
void setGridOrientation (Base::Vector3d origin, Base::Rotation rotation)
void getClosestGridPoint (double &x, double &y) const
double getGridSize () const
Public Member Functions inherited from Gui::ViewProviderExtension
ViewProviderExtension ()
~ViewProviderExtension () override
Gui::ViewProviderDocumentObject * getExtendedViewProvider ()
const Gui::ViewProviderDocumentObject * getExtendedViewProvider () const
virtual std::vector< App::DocumentObject * > extensionClaimChildren3D () const
virtual bool extensionOnDelete (const std::vector< std::string > &)
virtual void extensionBeforeDelete ()
virtual std::vector< App::DocumentObject * > extensionClaimChildren () const
virtual bool extensionCanDragObjects () const
virtual bool extensionCanDragObject (App::DocumentObject *) const
virtual void extensionDragObject (App::DocumentObject *)
virtual bool extensionCanDropObjects () const
virtual bool extensionCanDropObject (App::DocumentObject *) const
virtual bool extensionCanDragAndDropObject (App::DocumentObject *) const
virtual void extensionDropObject (App::DocumentObject *)
virtual bool extensionCanDropObjectEx (App::DocumentObject *, App::DocumentObject *, const char *, const std::vector< std::string > &) const
virtual std::string extensionDropObjectEx (App::DocumentObject *obj, App::DocumentObject *, const char *, const std::vector< std::string > &)
virtual int extensionReplaceObject (App::DocumentObject *, App::DocumentObject *)
virtual void extensionHide ()
Hides the view provider.
virtual void extensionShow ()
Shows the view provider.
virtual void extensionModeSwitchChange ()
virtual SoSeparator * extensionGetFrontRoot () const
virtual SoGroup * extensionGetChildRoot () const
virtual SoSeparator * extensionGetBackRoot () const
virtual void extensionAttach (App::DocumentObject *)
virtual void extensionReattach (App::DocumentObject *)
virtual void extensionSetDisplayMode (const char *)
virtual std::vector< std::string > extensionGetDisplayModes () const
PyObject * getExtensionPyObject () override
void setIgnoreOverlayIcon (bool on)
bool ignoreOverlayIcon () const
virtual QIcon extensionMergeGreyableOverlayIcons (const QIcon &orig) const
virtual void extensionStartRestoring ()
virtual void extensionFinishRestoring ()
virtual bool extensionGetElementPicked (const SoPickedPoint *, std::string &) const
virtual bool extensionGetDetailPath (const char *, SoFullPath *, SoDetail *&) const
Public Member Functions inherited from App::Extension
virtual Base::Type getExtensionTypeId (void) const
Extension ()=default
virtual ~Extension ()
virtual void initExtension (App::ExtensionContainer *obj)
App::ExtensionContainer * getExtendedContainer ()
const App::ExtensionContainer * getExtendedContainer () const
std::string name () const
bool isPythonExtension ()
virtual Property * extensionGetPropertyByName (const char *name) const
find a property by its name
virtual const char * extensionGetPropertyName (const Property *prop) const
get the name of a property
virtual void extensionGetPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual void extensionGetPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual short extensionGetPropertyType (const Property *prop) const
get the Type of a Property
virtual short extensionGetPropertyType (const char *name) const
get the Type of a named Property
virtual const char * extensionGetPropertyGroup (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * extensionGetPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual void extensionSave (Base::Writer &) const
virtual void extensionRestore (Base::XMLReader &)
bool extensionIsDerivedFrom (const Base::Type type) const
Public Member Functions inherited from PartGui::ViewProviderAttachExtension
ViewProviderAttachExtension ()
Constructor.
~ViewProviderAttachExtension () override=default
QIcon extensionMergeColorfullOverlayIcons (const QIcon &orig) const override
void extensionUpdateData (const App::Property *) override
void extensionSetupContextMenu (QMenu *, QObject *, const char *) override
void showAttachmentEditor ()
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Protected Member Functions
void onChanged (const App::Property *prop) override
get called by the container whenever a property has been changed
Protected Member Functions inherited from SketcherGui::ViewProviderSketch
void deactivateHandler ()
purges the DrawHandler if existing and tidies up
void editDoubleClicked ()
get called if a subelement is double clicked while editing
void toggleWireSelelection (int geoId)
get called when an edge is double clicked to select/unselect the whole wire
void slotUndoDocument (const Gui::Document &)
void slotRedoDocument (const Gui::Document &)
void slotSolverUpdate ()
void forceUpdateData ()
void onChanged (const App::Property *prop) override
get called by the container whenever a property has been changed
void startRestoring () override
hook after property restoring to change some property statuses
void finishRestoring () override
bool setEdit (int ModNum) override
is called by the document when the provider goes in edit mode
void unsetEdit (int ModNum) override
is called when you lose the edit mode
void setEditViewer (Gui::View3DInventorViewer *, int ModNum) override
adjust viewer settings when editing a view provider
void unsetEditViewer (Gui::View3DInventorViewer *) override
restores viewer settings when leaving editing mode
void onCameraChanged (SoCamera *cam)
void UpdateSolverInformation ()
update solver information based on last solving at SketchObject
Protected Member Functions inherited from PartGui::ViewProviderPart
void applyColor (const Part::ShapeHistory &hist, const std::vector< App::Color > &colBase, std::vector< App::Color > &colBool)
void applyMaterial (const Part::ShapeHistory &hist, const std::vector< App::Material > &colBase, std::vector< App::Material > &colBool)
void applyTransparency (float transparency, std::vector< App::Color > &colors)
void applyTransparency (float transparency, std::vector< App::Material > &colors)
Protected Member Functions inherited from PartGui::ViewProviderPartExt
bool loadParameter ()
void updateVisual ()
void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName) override
PropertyContainer::handleChangedPropertyName is called during restore to possibly fix reading of older versions of this property container. This method is typically called if the property on file has changed its name in more recent versions.
Protected Member Functions inherited from Gui::ViewProviderGeometryObject
void setSelectable (bool Selectable=true)
virtual unsigned long getBoundColor () const
void setCoinAppearance (const App::Material &source)
Protected Member Functions inherited from Gui::ViewProviderDragger
bool forwardToLink ()
virtual TaskView::TaskDialog * getTransformDialog ()
Protected Member Functions inherited from Gui::ViewProviderDocumentObject
Gui::MDIView * getActiveView () const
Gui::MDIView * getEditingView () const
Gui::MDIView * getInventorView () const
Gui::MDIView * getViewOfNode (SoNode *node) const
void onBeforeChange (const App::Property *prop) override
get called before the value is changed
SoNode * findFrontRootOfType (const SoType &type) const
bool isAttachedToDocument () const override
const char * detachFromDocument () override
void onPropertyStatusChanged (const App::Property &prop, unsigned long oldStatus) override
get called when a property status has changed
void setModeSwitch () override
Turn on mode switch.
void addDefaultAction (QMenu *, const QString &)
Protected Member Functions inherited from Gui::ViewProvider
virtual QIcon mergeGreyableOverlayIcons (const QIcon &orig) const
int getEditingMode () const
return the edit mode or -1 if nothing is being edited
bool checkRecursion (SoNode *)
SoPickedPoint * getPointOnRay (const SbVec2s &pos, const View3DInventorViewer *viewer) const
SoPickedPoint * getPointOnRay (const SbVec3f &pos, const SbVec3f &dir, const View3DInventorViewer *viewer) const
Protected Member Functions inherited from App::TransactionalObject
void onBeforeChangeProperty (Document *doc, const Property *prop)
Protected Member Functions inherited from App::PropertyContainer
virtual void onEarlyChange (const Property *)
virtual const PropertyData & getPropertyData () const
Protected Member Functions inherited from PartGui::ViewProviderGridExtension
void extensionOnChanged (const App::Property *) override
void setGridSizePixelThreshold (int value)
void setGridNumberSubdivision (int value)
void setGridLinePattern (int pattern)
void setGridDivLinePattern (int pattern)
void setGridLineWidth (int width)
void setGridDivLineWidth (int width)
void setGridLineColor (const App::Color &color)
void setGridDivLineColor (const App::Color &color)
bool extensionHandleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, App::Property *prop) override
returns true if the property type change was handled by the extension.
Protected Member Functions inherited from App::Extension
virtual const App::PropertyData & extensionGetPropertyData (void) const
virtual bool extensionHandleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
returns true if the property name change was handled by the extension.
void initExtensionType (Base::Type type)
Protected Attributes
std::map< const App::Property *, Gui::ViewProvider * > propView
Protected Attributes inherited from PartGui::ViewProviderPartExt
SoMaterialBinding * pcFaceBind
SoMaterialBinding * pcLineBind
SoMaterialBinding * pcPointBind
SoMaterial * pcLineMaterial
SoMaterial * pcPointMaterial
SoDrawStyle * pcLineStyle
SoDrawStyle * pcPointStyle
SoShapeHints * pShapeHints
SoCoordinate3 * coords
SoBrepFaceSet * faceset
SoNormal * norm
SoNormalBinding * normb
SoBrepEdgeSet * lineset
SoBrepPointSet * nodeset
bool VisualTouched
bool NormalsFromUV
Protected Attributes inherited from Gui::ViewProviderGeometryObject
SoMaterial * pcShapeMaterial {nullptr}
SoFCBoundingBox * pcBoundingBox {nullptr}
SoSwitch * pcBoundSwitch {nullptr}
SoBaseColor * pcBoundColor {nullptr}
SoPickStyle * pickStyle {nullptr}
App::Material materialAppearance
Protected Attributes inherited from Gui::ViewProviderDragger
CoinPtr< SoFCCSysDragger > csysDragger = nullptr
ViewProvider * forwardedViewProvider = nullptr
Protected Attributes inherited from Gui::ViewProviderDocumentObject
App::DocumentObject * pcObject {nullptr}
Gui::Document * pcDocument {nullptr}
Protected Attributes inherited from Gui::ViewProvider
SoSeparator * pcRoot
The root Separator of the ViewProvider.
SoTransform * pcTransform
this is transformation for the provider
const char * sPixmap
SoSwitch * pcModeSwitch
this is the mode switch, all the different viewing modes are collected here
SoSeparator * pcAnnotation {nullptr}
The root separator for annotations.
ViewProviderPy * pyViewObject {nullptr}
std::string overrideMode
std::bitset< 32 > StatusBits
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Protected Attributes inherited from App::Extension
bool m_isPythonExtension = false
Py::SmartPtr ExtensionPythonObject
Additional Inherited Members
Public Types inherited from SketcherGui::ViewProviderSketch
enum SketchMode {
STATUS_NONE, STATUS_SELECT_Point, STATUS_SELECT_Edge, STATUS_SELECT_Constraint,
STATUS_SELECT_Cross, STATUS_SELECT_Wire, STATUS_SKETCH_Drag, STATUS_SKETCH_DragConstraint,
STATUS_SKETCH_UseHandler, STATUS_SKETCH_StartRubberBand, STATUS_SKETCH_UseRubberBand
}
mode table
Public Types inherited from Gui::ViewProvider
enum EditMode { Default = 0, Transform, Cutting, Color }
Public Types inherited from App::ExtensionContainer
using ExtensionIterator = std::map< Base::Type, App::Extension * >::iterator
Static Public Member Functions inherited from Gui::ViewProviderDragger
static void updateTransform (const Base::Placement &from, SoTransform *to)
Static Public Member Functions inherited from Gui::ViewProvider
static const std::string & hiddenMarker ()
static const char * hasHiddenMarker (const char *subname)
static SbMatrix convert (const Base::Matrix4D &rcMatrix)
static Base::Matrix4D convert (const SbMatrix &sbMat)
static void eventCallback (void *ud, SoEventCallback *node)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Public Member Functions inherited from App::Extension
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Public Attributes inherited from SketcherGui::ViewProviderSketch
App::PropertyBool Autoconstraints
App::PropertyBool AvoidRedundant
App::PropertyPythonObject TempoVis
App::PropertyBool HideDependent
App::PropertyBool ShowLinks
App::PropertyBool ShowSupport
App::PropertyBool RestoreCamera
App::PropertyBool ForceOrtho
App::PropertyBool SectionView
App::PropertyBool AutoColor
App::PropertyString EditingWorkbench
SketcherGui::PropertyVisualLayerList VisualLayerList
const ToolManager toolManager
boost::signals2::signal< void()> signalConstraintsChanged
signals if the constraints list has changed
boost::signals2::signal< void(const QString &state, const QString &msg, const QString &url, const QString &linkText)> signalSetUp
signals if the sketch has been set up
boost::signals2::signal< void()> signalElementsChanged
signals if the elements list has changed
Public Attributes inherited from PartGui::ViewProviderPartExt
App::PropertyFloatConstraint Deviation
App::PropertyBool ControlPoints
App::PropertyAngle AngularDeflection
App::PropertyEnumeration Lighting
App::PropertyEnumeration DrawStyle
App::PropertyFloatConstraint PointSize
App::PropertyColor PointColor
App::PropertyMaterial PointMaterial
App::PropertyColorList PointColorArray
App::PropertyFloatConstraint LineWidth
App::PropertyColor LineColor
App::PropertyMaterial LineMaterial
App::PropertyColorList LineColorArray
Public Attributes inherited from Gui::ViewProviderGeometryObject
App::PropertyPercent Transparency
App::PropertyMaterialList ShapeAppearance
App::PropertyBool BoundingBox
App::PropertyBool Selectable
Public Attributes inherited from Gui::ViewProviderDragger
App::PropertyPlacement TransformOrigin
Public Attributes inherited from Gui::ViewProviderDocumentObject
App::PropertyEnumeration DisplayMode
App::PropertyBool Visibility
App::PropertyBool ShowInTree
App::PropertyEnumeration OnTopWhenSelected
App::PropertyEnumeration SelectionStyle
Public Attributes inherited from Gui::ViewProvider
boost::signals2::signal< void()> signalChangeIcon
signal on icon change
boost::signals2::signal< void(const QString &)> signalChangeToolTip
signal on tooltip change
boost::signals2::signal< void(const QString &)> signalChangeStatusTip
signal on status tip change
boost::signals2::signal< void(bool, Gui::HighlightMode)> signalChangeHighlight
signal on highlight change
Public Attributes inherited from PartGui::ViewProviderGridExtension
App::PropertyBool ShowGrid
App::PropertyLength GridSize
App::PropertyBool GridAuto
Static Protected Member Functions inherited from SketcherGui::ViewProviderSketch
static void camSensCB (void *data, SoSensor *)
static void camSensDeleteCB (void *data, SoSensor *)
static QString appendConstraintMsg (const QString &singularmsg, const QString &pluralmsg, const std::vector< int > &vector)
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Static Protected Member Functions inherited from App::Extension
static const App::PropertyData * extensionGetPropertyDataPtr (void)
static void initExtensionSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Base::Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 53 of file Sketcher/Gui/ViewProviderPython.h.
Constructor & Destructor Documentation
ViewProviderCustom()
ViewProviderCustom::ViewProviderCustom ()
constructor
Definition at line 37 of file Sketcher/Gui/ViewProviderPython.cpp.
~ViewProviderCustom()
ViewProviderCustom::~ViewProviderCustom () override
destructor
Definition at line 40 of file Sketcher/Gui/ViewProviderPython.cpp.
Member Function Documentation
onChanged()
void ViewProviderCustom::onChanged (const App::Property * prop) override protected virtual
get called by the container whenever a property has been changed
Reimplemented from PartGui::ViewProviderPartExt.
Definition at line 43 of file Sketcher/Gui/ViewProviderPython.cpp.
References App::Property::Copy(), App::Property::getName(), SketcherGui::ViewProviderSketch::onChanged(), App::Property::Paste(), and propView.
updateData()
void ViewProviderCustom::updateData (const App::Property * prop) override virtual
Reimplemented from PartGui::ViewProviderPartExt.
Definition at line 59 of file Sketcher/Gui/ViewProviderPython.cpp.
References SketcherGui::ViewProviderSketch::attach(), Gui::ViewProviderBuilder::create(), Gui::ViewProvider::getActiveDisplayMode(), Gui::ViewProviderDocumentObject::getObject(), Gui::ViewProvider::getRoot(), Base::Persistence::getTypeId(), Base::BaseClass::isDerivedFrom(), propView, PartGui::ViewProviderPartExt::setDisplayMode(), and Gui::ViewProvider::updateData().
Member Data Documentation
propView
std::map<const App::Property*, Gui::ViewProvider*> SketcherGui::ViewProviderCustom::propView protected
Definition at line 86 of file Sketcher/Gui/ViewProviderPython.h.
Referenced by onChanged(), and updateData().
The documentation for this class was generated from the following files:
Sketcher/Gui/ViewProviderPython.h
Sketcher/Gui/ViewProviderPython.cpp