FreeCAD: Document.cpp File Reference
Gui/Document.cpp File Reference
#include "PreCompiled.h"
#include <cctype>
#include <mutex>
#include <QApplication>
#include <QFileInfo>
#include <QMessageBox>
#include <QTextStream>
#include <QTimer>
#include <QStatusBar>
#include <Inventor/actions/SoSearchAction.h>
#include <Inventor/nodes/SoSeparator.h>
#include <App/AutoTransaction.h>
#include <App/Document.h>
#include <App/DocumentObject.h>
#include <App/DocumentObjectGroup.h>
#include <App/Transactions.h>
#include <App/ElementNamingUtils.h>
#include <Base/Console.h>
#include <Base/Exception.h>
#include <Base/Matrix.h>
#include <Base/Reader.h>
#include <Base/Writer.h>
#include <Base/Tools.h>
#include "Document.h"
#include "DocumentPy.h"
#include "Application.h"
#include "Command.h"
#include "Control.h"
#include "FileDialog.h"
#include "MainWindow.h"
#include "MDIView.h"
#include "NotificationArea.h"
#include "Selection.h"
#include "Thumbnail.h"
#include "Tree.h"
#include "View3DInventor.h"
#include "View3DInventorViewer.h"
#include "ViewProviderDocumentObject.h"
#include "ViewProviderDocumentObjectGroup.h"
#include "WaitCursor.h"
Classes
struct Gui::DocumentP
class Gui::ParentFinder
Namespaces
Gui
Functions
static bool checkCanonicalPath (const std::map< App::Document *, bool > &docs)
Function Documentation
checkCanonicalPath()
static bool checkCanonicalPath (const std::map< App::Document *, bool > & docs) static
Definition at line 1278 of file Gui/Document.cpp.
References src.Mod.AddonManager.NetworkManager::count, toolbit-attributes::doc, FC_WARN, App::GetApplication(), Gui::getMainWindow(), Path.Log::info(), Path.Op.Surface::msg, src.Mod.Test.UnitTests::ts(), TestSpreadsheet::v, importDXF::warn(), and Path.Log::warning().
Referenced by Gui::Document::save(), and Gui::Document::saveAll().