FreeCAD: MeshCore::MeshPointIterator Class Reference
MeshCore::MeshPointIterator Class Reference
#include <Iterator.h>
Public Member Functions
Construction
MeshPointIterator (const MeshKernel &rclM)
MeshPointIterator (const MeshKernel &rclM, PointIndex ulPos)
MeshPointIterator (const MeshPointIterator &rclI)
MeshPointIterator (MeshPointIterator &&rclI)
~MeshPointIterator ()=default
Transformation
void Transform (const Base::Matrix4D &rclTrf)
Transforms the returned points with the current transformation.
Access methods
const MeshPoint & operator* () const
Access to the element the iterator points to.
const MeshPoint * operator-> () const
Access to the element the iterator points to.
const MeshPointIterator & operator++ ()
const MeshPointIterator & operator-- ()
MeshPointIterator & operator= (const MeshPointIterator &rpI)
Assignment.
MeshPointIterator & operator= (MeshPointIterator &&rpI)
bool operator< (const MeshPointIterator &rclI) const
Compares if this iterator points to a lower element than the other one.
bool operator> (const MeshPointIterator &rclI) const
Compares if this iterator points to a higher element than the other one.
bool operator== (const MeshPointIterator &rclI) const
Checks if the iterators points to the same element.
void Begin ()
Sets the iterator to the beginning of the array.
void End ()
Sets the iterator to the end of the array.
PointIndex Position () const
Returns the current position of the iterator in the array.
bool EndReached () const
Checks if the end is already reached.
void Init ()
Sets the iterator to the beginning of the array.
bool More () const
Checks if the end is not yet reached.
void Next ()
Increments the iterator.
bool Set (PointIndex ulIndex)
Sets the iterator to a given position.
bool IsValid () const
Checks if the iterator points to a valid element inside the array.
Flag state
class MeshKernel
void SetFlag (MeshPoint::TFlagType tF) const
void ResetFlag (MeshPoint::TFlagType tF) const
bool IsFlag (MeshPoint::TFlagType tF) const
void SetProperty (unsigned long uP) const
Detailed Description
The MeshPointIterator allows one to iterate over the vertices of the mesh and provides access to their geometric information.
Note
This class is not thread-safe.
Definition at line 248 of file Iterator.h.
Constructor & Destructor Documentation
MeshPointIterator() [1/4]
MeshCore::MeshPointIterator::MeshPointIterator (const MeshKernel & rclM) inline explicit
Definition at line 563 of file Iterator.h.
MeshPointIterator() [2/4]
MeshCore::MeshPointIterator::MeshPointIterator (const MeshKernel & rclM, PointIndex ulPos) inline
Definition at line 571 of file Iterator.h.
MeshPointIterator() [3/4]
MeshCore::MeshPointIterator::MeshPointIterator (const MeshPointIterator & rclI) inline
Definition at line 579 of file Iterator.h.
MeshPointIterator() [4/4]
MeshCore::MeshPointIterator::MeshPointIterator (MeshPointIterator && rclI) inline
Definition at line 587 of file Iterator.h.
~MeshPointIterator()
MeshCore::MeshPointIterator::~MeshPointIterator () default
Member Function Documentation
Begin()
void MeshCore::MeshPointIterator::Begin () inline
Sets the iterator to the beginning of the array.
Definition at line 311 of file Iterator.h.
Referenced by MeshCore::MeshKernel::PointIterator(), and MeshCore::PlaneFitSmoothing::Smooth().
End()
void MeshCore::MeshPointIterator::End () inline
Sets the iterator to the end of the array.
Definition at line 316 of file Iterator.h.
Referenced by MeshCore::MeshInfo::DetailedPointInfo(), and MeshCore::MeshInfo::InternalPointInfo().
EndReached()
bool MeshCore::MeshPointIterator::EndReached () const inline
Checks if the end is already reached.
Definition at line 326 of file Iterator.h.
References Set().
Init()
void MeshCore::MeshPointIterator::Init () inline
Sets the iterator to the beginning of the array.
Definition at line 331 of file Iterator.h.
Referenced by MeshCore::MeshTopoAlgorithm::AdjustEdgesToCurvatureDirection(), MeshCore::MeshCurvature::ComputePerVertex(), MeshCore::MeshAlgorithm::GetGravityPoint(), MeshCore::MeshPointGrid::RebuildGrid(), MeshCore::MeshOutput::SaveNastran(), MeshCore::MeshOutput::SaveVRML(), and MeshCore::MeshAlgorithm::SubSampleAllPoints().
IsFlag()
bool MeshCore::MeshPointIterator::IsFlag (MeshPoint::TFlagType tF) const inline
Definition at line 364 of file Iterator.h.
IsValid()
bool MeshCore::MeshPointIterator::IsValid () const inline
Checks if the iterator points to a valid element inside the array.
Definition at line 348 of file Iterator.h.
More()
bool MeshCore::MeshPointIterator::More () const inline
Checks if the end is not yet reached.
Definition at line 336 of file Iterator.h.
Referenced by MeshCore::MeshTopoAlgorithm::AdjustEdgesToCurvatureDirection(), MeshCore::MeshCurvature::ComputePerVertex(), MeshCore::MeshAlgorithm::GetGravityPoint(), MeshCore::MeshPointGrid::RebuildGrid(), MeshCore::MeshOutput::SaveNastran(), MeshCore::MeshOutput::SaveVRML(), MeshCore::PlaneFitSmoothing::Smooth(), and MeshCore::MeshAlgorithm::SubSampleAllPoints().
Next()
void MeshCore::MeshPointIterator::Next () inline
Increments the iterator.
Definition at line 341 of file Iterator.h.
Referenced by MeshCore::MeshTopoAlgorithm::AdjustEdgesToCurvatureDirection(), MeshCore::MeshCurvature::ComputePerVertex(), MeshCore::MeshAlgorithm::GetGravityPoint(), MeshCore::MeshPointGrid::RebuildGrid(), MeshCore::MeshOutput::SaveNastran(), MeshCore::MeshOutput::SaveVRML(), MeshCore::PlaneFitSmoothing::Smooth(), and MeshCore::MeshAlgorithm::SubSampleAllPoints().
operator*()
const MeshPoint& MeshCore::MeshPointIterator::operator* () const inline
Access to the element the iterator points to.
Definition at line 269 of file Iterator.h.
operator++()
const MeshPointIterator& MeshCore::MeshPointIterator::operator++ () inline
Increments the iterator. It points then to the next element if the end is not reached.
Definition at line 280 of file Iterator.h.
operator--()
const MeshPointIterator& MeshCore::MeshPointIterator::operator-- () inline
Decrements the iterator. It points then to the previous element if the beginning is not reached.
Definition at line 287 of file Iterator.h.
operator->()
const MeshPoint* MeshCore::MeshPointIterator::operator-> () const inline
Access to the element the iterator points to.
Definition at line 274 of file Iterator.h.
operator<()
bool MeshCore::MeshPointIterator::operator< (const MeshPointIterator & rclI) const inline
Compares if this iterator points to a lower element than the other one.
Definition at line 296 of file Iterator.h.
operator=() [1/2]
MeshPointIterator & MeshCore::MeshPointIterator::operator= (const MeshPointIterator & rpI) inline
Assignment.
Definition at line 624 of file Iterator.h.
operator=() [2/2]
MeshPointIterator & MeshCore::MeshPointIterator::operator= (MeshPointIterator && rpI) inline
Definition at line 632 of file Iterator.h.
operator==()
bool MeshCore::MeshPointIterator::operator== (const MeshPointIterator & rclI) const inline
Checks if the iterators points to the same element.
Definition at line 306 of file Iterator.h.
operator>()
bool MeshCore::MeshPointIterator::operator> (const MeshPointIterator & rclI) const inline
Compares if this iterator points to a higher element than the other one.
Definition at line 301 of file Iterator.h.
Position()
PointIndex MeshCore::MeshPointIterator::Position () const inline
Returns the current position of the iterator in the array.
Definition at line 321 of file Iterator.h.
Referenced by MeshCore::MeshKernel::HasFacets(), MeshCore::PlaneFitSmoothing::Smooth(), and MeshCore::PlaneFitSmoothing::SmoothPoints().
ResetFlag()
void MeshCore::MeshPointIterator::ResetFlag (MeshPoint::TFlagType tF) const inline
Definition at line 360 of file Iterator.h.
Set()
bool MeshCore::MeshPointIterator::Set (PointIndex ulIndex) inline
Sets the iterator to a given position.
Definition at line 613 of file Iterator.h.
Referenced by Mesh::MeshObject::const_point_iterator::const_point_iterator(), MeshCore::MeshKernel::DeletePoint(), MeshCore::MeshFaceIterator::MeshFaceIterator(), MeshPart::MeshProjection::projectEdgeToEdge(), MeshGui::ViewProviderMeshNonManifolds::showDefects(), MeshGui::ViewProviderMeshNonManifoldPoints::showDefects(), MeshGui::ViewProviderMeshDuplicatedPoints::showDefects(), MeshCore::PlaneFitSmoothing::SmoothPoints(), and MeshCore::MeshPointGrid::Verify().
SetFlag()
void MeshCore::MeshPointIterator::SetFlag (MeshPoint::TFlagType tF) const inline
Definition at line 356 of file Iterator.h.
SetProperty()
void MeshCore::MeshPointIterator::SetProperty (unsigned long uP) const inline
Definition at line 368 of file Iterator.h.
References MeshCore::MeshFastFacetIterator::_afPoints, MeshCore::MeshFastFacetIterator::Init(), MeshCore::MeshFastFacetIterator::MeshFastFacetIterator(), MeshCore::MeshFastFacetIterator::More(), MeshCore::MeshFastFacetIterator::Next(), and MeshCore::MeshFastFacetIterator::~MeshFastFacetIterator().
Transform()
void MeshCore::MeshPointIterator::Transform (const Base::Matrix4D & rclTrf) inline
Transforms the returned points with the current transformation.
Definition at line 595 of file Iterator.h.
Referenced by Mesh::MeshObject::const_point_iterator::const_point_iterator(), MeshCore::MeshOutput::SaveNastran(), and MeshCore::MeshOutput::SaveVRML().
Friends And Related Function Documentation
MeshKernel
friend class MeshKernel friend
Definition at line 386 of file Iterator.h.
The documentation for this class was generated from the following file:
Iterator.h