FreeCAD: Base::InventorLoader Class Reference
Base::InventorLoader Class Reference
#include <Builder3D.h>
Classes
struct Face
Public Member Functions
InventorLoader (std::istream &inp)
bool read ()
bool isValid () const
Checks if the loaded data are valid.
bool isNonIndexed () const
const std::vector< Vector3f > & getVector () const
Return the vectors of an SoNormal node.
const std::vector< Vector3f > & getPoints () const
Return the points of an SoCoordinate3 node.
const std::vector< Face > & getFaces () const
Return the faces of an SoIndexedFaceSet node.
Detailed Description
Loads an OpenInventor file.
Author
Werner Mayer
Definition at line 792 of file Builder3D.h.
Constructor & Destructor Documentation
InventorLoader()
Base::InventorLoader::InventorLoader (std::istream & inp) inline explicit
Definition at line 805 of file Builder3D.h.
Member Function Documentation
getFaces()
const std::vector<Face>& Base::InventorLoader::getFaces () const inline
Return the faces of an SoIndexedFaceSet node.
Definition at line 836 of file Builder3D.h.
Referenced by MeshCore::MeshInput::LoadInventor().
getPoints()
const std::vector<Vector3f>& Base::InventorLoader::getPoints () const inline
Return the points of an SoCoordinate3 node.
Definition at line 830 of file Builder3D.h.
Referenced by MeshCore::MeshInput::LoadInventor().
getVector()
const std::vector<Vector3f>& Base::InventorLoader::getVector () const inline
Return the vectors of an SoNormal node.
Definition at line 824 of file Builder3D.h.
isNonIndexed()
bool Base::InventorLoader::isNonIndexed () const inline
Returns true if the data come from a non-indexed node as SoFaceSet. This means that the read points contain duplicates.
Definition at line 818 of file Builder3D.h.
Referenced by MeshCore::MeshInput::LoadInventor().
isValid()
bool InventorLoader::isValid () const
Checks if the loaded data are valid.
Definition at line 1238 of file Builder3D.cpp.
Referenced by MeshCore::MeshInput::LoadInventor().
read()
bool InventorLoader::read ()
Start the read process. Returns true if successful and false otherwise. The obtained data can be accessed with the appropriate getter functions.
Definition at line 1204 of file Builder3D.cpp.
References importOCA::getline().
Referenced by MeshCore::MeshInput::LoadInventor().
The documentation for this class was generated from the following files:
Builder3D.h
Builder3D.cpp