FreeCAD: Gui::LocationImpUi< Ui > Class Template Reference
Gui::LocationImpUi< Ui > Class Template Reference
#include <InputVector.h>
Public Member Functions
LocationImpUi (Ui *ui)
~LocationImpUi () override=default
boost::any get () override
void retranslate (QDialog *dlg) override
void setPosition (const Base::Vector3d &v) override
Base::Vector3d getPosition () const override
Base::Vector3d getDirection () const override
void setDirection (const Base::Vector3d &dir) override
bool directionActivated (LocationDialog *dlg, int index) override
Public Member Functions inherited from Gui::AbstractUi
virtual ~AbstractUi ()=default
Detailed Description
template<class Ui>
class Gui::LocationImpUi< Ui >
This is the template class that implements the interface of AbstractUi. The template argument is the Ui interface class built by uic out of a .ui file.
Author
Werner Mayer
Definition at line 420 of file InputVector.h.
Constructor & Destructor Documentation
LocationImpUi()
template<class Ui > Gui::LocationImpUi< Ui >::LocationImpUi (Ui * ui) inline
Definition at line 423 of file InputVector.h.
~LocationImpUi()
template<class Ui > Gui::LocationImpUi< Ui >::~LocationImpUi () override default
Member Function Documentation
directionActivated()
template<class Ui > bool Gui::LocationImpUi< Ui >::directionActivated (LocationDialog * dlg, int index) inline override virtual
Implements Gui::AbstractUi.
Definition at line 514 of file InputVector.h.
References Base::Vector3< double >::epsilon(), Gui::LocationDialog::getUserDirection(), Base::Vector3< float_type >::Length(), and Gui::LocationImpUi< Ui >::setDirection().
get()
template<class Ui > boost::any Gui::LocationImpUi< Ui >::get () inline override virtual
Implements Gui::AbstractUi.
Definition at line 428 of file InputVector.h.
Referenced by draftguitools.gui_trackers.editTracker::move().
getDirection()
template<class Ui > Base::Vector3d Gui::LocationImpUi< Ui >::getDirection () const inline override virtual
Implements Gui::AbstractUi.
Definition at line 475 of file InputVector.h.
getPosition()
template<class Ui > Base::Vector3d Gui::LocationImpUi< Ui >::getPosition () const inline override virtual
Implements Gui::AbstractUi.
Definition at line 468 of file InputVector.h.
retranslate()
template<class Ui > void Gui::LocationImpUi< Ui >::retranslate (QDialog * dlg) inline override virtual
Implements Gui::AbstractUi.
Definition at line 433 of file InputVector.h.
References src.Mod.AddonManager.Addon::translate.
setDirection()
template<class Ui > void Gui::LocationImpUi< Ui >::setDirection (const Base::Vector3d & dir) inline override virtual
Implements Gui::AbstractUi.
Definition at line 487 of file InputVector.h.
References femsolver.report::display(), Base::Vector3< double >::epsilon(), SplineSurface::i, Base::Vector3< float_type >::Length(), toolbit-attributes::val, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by Gui::LocationImpUi< Ui >::directionActivated().
setPosition()
template<class Ui > void Gui::LocationImpUi< Ui >::setPosition (const Base::Vector3d & v) inline override virtual
Implements Gui::AbstractUi.
Definition at line 461 of file InputVector.h.
References TestSpreadsheet::v.
The documentation for this class was generated from the following file:
InputVector.h