FreeCAD: Mesh::MeshObject::const_point_iterator Class Reference
Mesh::MeshObject::const_point_iterator Class Reference
#include <Mesh.h>
Public Member Functions
const_point_iterator (const MeshObject *, PointIndex index)
const_point_iterator (const const_point_iterator &pi)
const_point_iterator (const_point_iterator &&pi)
~const_point_iterator ()
const_point_iterator & operator= (const const_point_iterator &pi)
const_point_iterator & operator= (const_point_iterator &&pi)
const MeshPoint & operator* ()
const MeshPoint * operator-> ()
bool operator== (const const_point_iterator &pi) const
bool operator!= (const const_point_iterator &pi) const
const_point_iterator & operator++ ()
const_point_iterator & operator-- ()
Detailed Description
Definition at line 380 of file Mesh.h.
Constructor & Destructor Documentation
const_point_iterator() [1/3]
MeshObject::const_point_iterator::const_point_iterator (const MeshObject * mesh, PointIndex index)
Definition at line 2132 of file Mesh.cpp.
References Mesh::MeshPoint::Mesh, MeshCore::MeshPointIterator::Set(), and MeshCore::MeshPointIterator::Transform().
const_point_iterator() [2/3]
MeshObject::const_point_iterator::const_point_iterator (const const_point_iterator & pi) default
const_point_iterator() [3/3]
MeshObject::const_point_iterator::const_point_iterator (const_point_iterator && pi) default
~const_point_iterator()
MeshObject::const_point_iterator::~const_point_iterator () default
Member Function Documentation
operator!=()
bool MeshObject::const_point_iterator::operator!= (const const_point_iterator & pi) const
Definition at line 2180 of file Mesh.cpp.
References KDL::operator==(), and ClipperLib::pi.
operator*()
const MeshPoint & MeshObject::const_point_iterator::operator* ()
Definition at line 2163 of file Mesh.cpp.
operator++()
MeshObject::const_point_iterator & MeshObject::const_point_iterator::operator++ ()
Definition at line 2185 of file Mesh.cpp.
operator--()
MeshObject::const_point_iterator & MeshObject::const_point_iterator::operator-- ()
Definition at line 2191 of file Mesh.cpp.
operator->()
const MeshPoint * MeshObject::const_point_iterator::operator-> ()
Definition at line 2169 of file Mesh.cpp.
operator=() [1/2]
MeshObject::const_point_iterator & MeshObject::const_point_iterator::operator= (const const_point_iterator & pi) default
operator=() [2/2]
MeshObject::const_point_iterator & MeshObject::const_point_iterator::operator= (const_point_iterator && pi) default
operator==()
bool MeshObject::const_point_iterator::operator== (const const_point_iterator & pi) const
Definition at line 2175 of file Mesh.cpp.
References ClipperLib::pi.
The documentation for this class was generated from the following files:
Mesh.h
Mesh.cpp