FreeCAD: Gui::SelectionFilter Class Reference
Gui::SelectionFilter Class Reference
#include <SelectionFilter.h>
Public Member Functions
SelectionFilter (const char *filter)
SelectionFilter (const std::string &filter)
virtual ~SelectionFilter ()
void setFilter (const char *filter)
Set a new filter string.
const std::string & getFilter () const
bool match ()
bool test (App::DocumentObject *pObj, const char *sSubName)
void addError (const char *e)
bool isValid () const
true if a valid filter is set
Public Attributes
std::vector< std::vector< SelectionObject > > Result
Protected Member Functions
bool parse ()
Protected Attributes
std::string Filter
std::string Errors
std::shared_ptr< Node_Block > Ast
Friends
class SelectionSingleton
Detailed Description
Selection filter definition This class builds up a type/count tree out of a string to test very fast a selection or object/subelement type against it.
Example strings are: "SELECT Part::Feature SUBELEMENT Edge", "SELECT Robot::RobotObject", "SELECT Robot::RobotObject COUNT 1..5"
Definition at line 50 of file SelectionFilter.h.
Constructor & Destructor Documentation
SelectionFilter() [1/2]
SelectionFilter::SelectionFilter (const char * filter) explicit
Constructs a SelectionFilter object.
Definition at line 134 of file SelectionFilter.cpp.
References setFilter().
SelectionFilter() [2/2]
SelectionFilter::SelectionFilter (const std::string & filter) explicit
Definition at line 140 of file SelectionFilter.cpp.
References setFilter().
~SelectionFilter()
SelectionFilter::~SelectionFilter () virtual default
Member Function Documentation
addError()
void SelectionFilter::addError (const char * e)
Definition at line 225 of file SelectionFilter.cpp.
References SCL.SimpleDataTypes::e, and Errors.
Referenced by yyerror().
getFilter()
const std::string& Gui::SelectionFilter::getFilter () const inline
Definition at line 61 of file SelectionFilter.h.
isValid()
bool Gui::SelectionFilter::isValid () const inline
true if a valid filter is set
Definition at line 84 of file SelectionFilter.h.
match()
bool SelectionFilter::match ()
Test to current selection This method tests the current selection set against the filter and returns true if the described object(s) are selected.
Definition at line 161 of file SelectionFilter.cpp.
References Ast, Gui::SelectionSingleton::getSelectionEx(), KDL::max(), KDL::min(), Result, and Gui::Selection().
Referenced by WorkingPlane.PlaneBase::copy(), WorkingPlane.Plane::copy(), WorkingPlane.PlaneGui::copy(), Gui::SelectionFilterPy::match(), RobotGui::TaskWatcherRobot::shouldShow(), Gui::TaskView::TaskWatcherPython::shouldShow(), and Gui::TaskView::TaskWatcherCommands::shouldShow().
parse()
bool SelectionFilter::parse () protected
Definition at line 324 of file SelectionFilter.cpp.
References ActFilter, Ast, SelectionParser::StringFactory::clear(), Errors, Filter, SelectionParser::StringFactory::instance(), TopBlock, and yyparse().
Referenced by BOPTools.GeneralFuseResult.GeneralFuseResult::__init__(), BOPTools.GeneralFuseResult.GeneralFuseResult::explodeCompounds(), setFilter(), and BOPTools.GeneralFuseResult.GeneralFuseResult::splitAggregates().
setFilter()
void SelectionFilter::setFilter (const char * filter)
Set a new filter string.
Definition at line 146 of file SelectionFilter.cpp.
References Ast, Errors, Filter, and parse().
Referenced by SelectionFilter(), and Gui::TaskView::TaskWatcherPython::TaskWatcherPython().
test()
bool SelectionFilter::test (App::DocumentObject * pObj, const char * sSubName)
Test objects This method tests if a given object is described in the filter. If SubName is not NULL the Subelement gets also tested.
Definition at line 207 of file SelectionFilter.cpp.
References Ast, DraftVecUtils::find(), Base::Persistence::getTypeId(), and Base::Type::isDerivedFrom().
Referenced by Gui::SelectionFilterGate::allow(), and Gui::SelectionFilterGatePython::allow().
Friends And Related Function Documentation
SelectionSingleton
friend class SelectionSingleton friend
Definition at line 79 of file SelectionFilter.h.
Member Data Documentation
Ast
std::shared_ptr<Node_Block> Gui::SelectionFilter::Ast protected
Definition at line 91 of file SelectionFilter.h.
Referenced by match(), parse(), setFilter(), and test().
Errors
std::string Gui::SelectionFilter::Errors protected
Definition at line 88 of file SelectionFilter.h.
Referenced by addError(), parse(), and setFilter().
Filter
std::string Gui::SelectionFilter::Filter protected
Definition at line 87 of file SelectionFilter.h.
Referenced by parse(), setFilter(), and Gui::TaskView::TaskWatcherPython::shouldShow().
Result
std::vector<std::vector<SelectionObject> > Gui::SelectionFilter::Result
Definition at line 81 of file SelectionFilter.h.
Referenced by match(), and RobotGui::TaskWatcherRobot::shouldShow().
The documentation for this class was generated from the following files:
SelectionFilter.h
SelectionFilter.cpp