FreeCAD: Gui::ShortcutManager Class Reference
Gui::ShortcutManager Class Reference
#include <ShortcutManager.h>
Signals
void shortcutChanged (const char *name, const QKeySequence &oldShortcut)
void actionShortcutChanged (QAction *, const QKeySequence &oldShortcut)
void priorityChanged (const char *name, int priority)
Public Member Functions
ShortcutManager ()
~ShortcutManager () override
void OnChange (Base::Subject< const char * > &, const char *reason) override
void resetAll ()
Clear all user defined shortcut.
void reset (const char *cmd)
Clear the user defined shortcut of a given command.
void setShortcut (const char *cmd, const char *accel)
Set shortcut of a given command.
QString getShortcut (const char *cmd, const char *defaultAccel=nullptr)
std::vector< std::pair< QByteArray, QAction * > > getActionsByShortcut (const QKeySequence &shortcut)
Return actions having a given shortcut in order of decreasing priority.
void setPriorities (const std::vector< QByteArray > &actions)
Set properties for a given list of actions in order of decreasing priority.
void setPriority (const char *cmd, int priority)
int getPriority (const char *cmd)
Get the priority of a given command.
void setTopPriority (const char *cmd)
Static Public Member Functions
static ShortcutManager * instance ()
static void destroy ()
Protected Member Functions
bool eventFilter (QObject *, QEvent *ev) override
bool checkShortcut (QObject *o, const QKeySequence &key)
void onTimer ()
Detailed Description
Definition at line 65 of file ShortcutManager.h.
Constructor & Destructor Documentation
ShortcutManager()
ShortcutManager::ShortcutManager ()
Definition at line 40 of file ShortcutManager.cpp.
References Base::Subject< MsgType >::Attach(), draftgeoutils.intersections::connect(), Gui::WindowParameter::getDefaultParameter(), ParameterGrp::GetGroup(), ParameterGrp::GetInt(), ParameterGrp::GetIntMap(), onTimer(), and TestSpreadsheet::v.
Referenced by instance().
~ShortcutManager()
ShortcutManager::~ShortcutManager () override
Definition at line 65 of file ShortcutManager.cpp.
References Base::Subject< MsgType >::Detach().
Member Function Documentation
actionShortcutChanged
void Gui::ShortcutManager::actionShortcutChanged (QAction * , const QKeySequence & oldShortcut) signal
Referenced by eventFilter().
checkShortcut()
bool ShortcutManager::checkShortcut (QObject * o, const QKeySequence & key) protected
Definition at line 192 of file ShortcutManager.cpp.
References Path.Post.scripts.dynapath_4060_post::action, getPriority(), SplineSurface::i, src.Mod.Test.testPathArray::o, and onTimer().
Referenced by eventFilter().
destroy()
void ShortcutManager::destroy () static
Definition at line 80 of file ShortcutManager.cpp.
References Instance.
eventFilter()
bool ShortcutManager::eventFilter (QObject * o, QEvent * ev) override protected
Definition at line 275 of file ShortcutManager.cpp.
References Path.Post.scripts.dynapath_4060_post::action, actionShortcutChanged(), checkShortcut(), Path.Log::info(), and src.Mod.Test.testPathArray::o.
getActionsByShortcut()
std::vector< std::pair< QByteArray, QAction * > > ShortcutManager::getActionsByShortcut (const QKeySequence & shortcut)
Return actions having a given shortcut in order of decreasing priority.
Definition at line 343 of file ShortcutManager.cpp.
References getPriority(), and TestSpreadsheet::v.
Referenced by Gui::Dialog::DlgCustomKeyboardImp::populatePriorityList().
getPriority()
int ShortcutManager::getPriority (const char * cmd)
Get the priority of a given command.
Definition at line 383 of file ShortcutManager.cpp.
Referenced by checkShortcut(), getActionsByShortcut(), reset(), and setPriorities().
getShortcut()
QString ShortcutManager::getShortcut (const char * cmd, const char * defaultAccel = nullptr)
Get shortcut of a given command
Parameters
cmd command name
defaultAccel default shortcut
Definition at line 156 of file ShortcutManager.cpp.
References ParameterGrp::GetASCII(), and Gui::Application::Instance.
Referenced by Gui::Command::getShortcut(), Gui::Dialog::DlgCustomActionsImp::onButtonReplaceActionClicked(), Gui::Dialog::DlgCustomKeyboardImp::onButtonResetClicked(), OnChange(), Gui::Dialog::DlgCustomKeyboardImp::onCommandTreeWidgetCurrentItemChanged(), reset(), and resetAll().
instance()
ShortcutManager * ShortcutManager::instance () static
Definition at line 73 of file ShortcutManager.cpp.
References Instance, and ShortcutManager().
Referenced by Gui::Dialog::DlgCustomKeyboardImp::DlgCustomKeyboardImp(), Gui::Command::getShortcut(), Gui::Command::initAction(), Gui::Dialog::DlgCustomKeyboardImp::initCommandList(), Gui::Dialog::DlgCustomKeyboardImp::initCommandWidgets(), Gui::Dialog::DlgCustomKeyboardImp::initPriorityList(), Gui::Dialog::DlgCustomActionsImp::onActionListWidgetItemActivated(), Gui::Dialog::DlgCustomActionsImp::onButtonAddActionClicked(), Gui::Dialog::DlgCustomActionsImp::onButtonReplaceActionClicked(), Gui::Dialog::DlgCustomKeyboardImp::onButtonResetAllClicked(), Gui::Dialog::DlgCustomKeyboardImp::onButtonResetClicked(), Gui::Dialog::DlgCustomKeyboardImp::onCommandTreeWidgetCurrentItemChanged(), Gui::Dialog::DlgCustomActionsImp::onRemoveMacroAction(), Gui::Dialog::DlgCustomKeyboardImp::populatePriorityList(), and Gui::Dialog::DlgCustomKeyboardImp::setShortcutOfCurrentAction().
OnChange()
void ShortcutManager::OnChange (Base::Subject< const char * > & src, const char * reason) override
Definition at line 86 of file ShortcutManager.cpp.
References Gui::Application::commandManager(), DraftVecUtils::equals(), Gui::CommandBase::getAccel(), Gui::CommandManager::getCommandByName(), ParameterGrp::GetInt(), getShortcut(), Gui::Application::Instance, buildPsets::p, priorityChanged(), and shortcutChanged().
onTimer()
void ShortcutManager::onTimer () protected
Definition at line 407 of file ShortcutManager.cpp.
References Path.Log::info(), and toolbit-attributes::s.
Referenced by checkShortcut(), and ShortcutManager().
priorityChanged
void Gui::ShortcutManager::priorityChanged (const char * name, int priority) signal
Referenced by Gui::Dialog::DlgCustomKeyboardImp::initCommandWidgets(), OnChange(), reset(), and resetAll().
reset()
void ShortcutManager::reset (const char * cmd)
Clear the user defined shortcut of a given command.
Definition at line 123 of file ShortcutManager.cpp.
References getPriority(), getShortcut(), priorityChanged(), ParameterGrp::RemoveASCII(), ParameterGrp::RemoveInt(), and shortcutChanged().
Referenced by ArchVRM.Renderer::__init__(), Gui::Dialog::DlgCustomKeyboardImp::onButtonResetClicked(), Gui::Dialog::DlgCustomActionsImp::onRemoveMacroAction(), draftguitools.gui_trackers.gridTracker::set(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testAll(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testBuildings(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCommonPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCustom(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testExtrusions(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testHierarchy(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testIFC4(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testMaterials(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testQuantities(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testRectangleProfileDef(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSites(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSolid(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandardCases(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandards(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStoreys(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testTinyLines(), and bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testUndefined().
resetAll()
void ShortcutManager::resetAll ()
Clear all user defined shortcut.
Definition at line 138 of file ShortcutManager.cpp.
References ParameterGrp::Clear(), getShortcut(), Gui::Application::Instance, priorityChanged(), and shortcutChanged().
Referenced by Gui::Dialog::DlgCustomKeyboardImp::onButtonResetAllClicked().
setPriorities()
void ShortcutManager::setPriorities (const std::vector< QByteArray > & actions)
Set properties for a given list of actions in order of decreasing priority.
Definition at line 359 of file ShortcutManager.cpp.
References getPriority(), KDL::max(), buildPsets::p, and setPriority().
Referenced by Gui::Dialog::DlgCustomKeyboardImp::initPriorityList().
setPriority()
void ShortcutManager::setPriority (const char * cmd, int priority)
Set the priority of a given command
Parameters
cmd command name
priority priority of the command, bigger value means higher priority
Definition at line 393 of file ShortcutManager.cpp.
References buildPsets::p, ParameterGrp::RemoveInt(), and ParameterGrp::SetInt().
Referenced by setPriorities().
setShortcut()
void ShortcutManager::setShortcut (const char * cmd, const char * accel)
Set shortcut of a given command.
Definition at line 173 of file ShortcutManager.cpp.
References Gui::Application::Instance, ParameterGrp::RemoveASCII(), ParameterGrp::SetASCII(), and setTopPriority().
Referenced by Gui::Dialog::DlgCustomActionsImp::onButtonAddActionClicked(), and Gui::Dialog::DlgCustomKeyboardImp::setShortcutOfCurrentAction().
setTopPriority()
void ShortcutManager::setTopPriority (const char * cmd)
Set the top priority of a given command Make the given command the top priority of all commands.
Parameters
cmd command name
Definition at line 401 of file ShortcutManager.cpp.
References ParameterGrp::SetInt().
Referenced by setShortcut().
shortcutChanged
void Gui::ShortcutManager::shortcutChanged (const char * name, const QKeySequence & oldShortcut) signal
Referenced by Gui::Dialog::DlgCustomKeyboardImp::DlgCustomKeyboardImp(), Gui::Dialog::DlgCustomKeyboardImp::initCommandList(), OnChange(), reset(), and resetAll().
The documentation for this class was generated from the following files:
ShortcutManager.h
ShortcutManager.cpp