FreeCAD: Wm4::Delaunay1< Real > Class Template Reference
Wm4::Delaunay1< Real > Class Template Reference
#include <Wm4Delaunay1.h>
Public Member Functions
Delaunay1 (int iVertexQuantity, Real *afVertex, Real fEpsilon, bool bOwner, Query::Type eQueryType)
virtual ~Delaunay1 ()
const Real * GetVertices () const
bool GetHull (int aiIndex[2])
int GetContainingSegment (const Real fP) const
bool GetVertexSet (int i, Real afV[2]) const
bool GetIndexSet (int i, int aiIndex[2]) const
bool GetAdjacentSet (int i, int aiAdjacent[2]) const
bool GetBarycentricSet (int i, const Real fP, Real afBary[2]) const
Delaunay1 (const char *acFilename)
bool Load (const char *acFilename)
bool Save (const char *acFilename) const
Public Member Functions inherited from Wm4::Delaunay< Real >
virtual ~Delaunay ()
int GetQueryType () const
int GetVertexQuantity () const
Real GetEpsilon () const
bool GetOwner () const
int GetDimension () const
int GetSimplexQuantity () const
const int * GetIndices () const
const int * GetAdjacencies () const
Additional Inherited Members
Protected Member Functions inherited from Wm4::Delaunay< Real >
Delaunay (int iVertexQuantity, Real fEpsilon, bool bOwner, Query::Type eQueryType)
bool Load (FILE *pkIFile)
bool Save (FILE *pkOFile) const
Protected Attributes inherited from Wm4::Delaunay< Real >
Query::Type m_eQueryType
int m_iVertexQuantity
int m_iDimension
int m_iSimplexQuantity
int * m_aiIndex
int * m_aiAdjacent
Real m_fEpsilon
bool m_bOwner
Detailed Description
template<class Real>
class Wm4::Delaunay1< Real >
Definition at line 33 of file Wm4Delaunay1.h.
Constructor & Destructor Documentation
Delaunay1() [1/2]
template<class Real > Wm4::Delaunay1< Real >::Delaunay1 (int iVertexQuantity, Real * afVertex, Real fEpsilon, bool bOwner, Query::Type eQueryType)
Definition at line 24 of file Wm4Delaunay1.cpp.
References SplineSurface::i, Wm4::Delaunay< Real >::m_aiAdjacent, Wm4::Delaunay< Real >::m_aiIndex, Wm4::Delaunay< Real >::m_fEpsilon, Wm4::Delaunay< Real >::m_iDimension, Wm4::Delaunay< Real >::m_iSimplexQuantity, Wm4::Delaunay< Real >::m_iVertexQuantity, and WM4_NEW.
~Delaunay1()
template<class Real > Wm4::Delaunay1< Real >::~Delaunay1 virtual
Definition at line 64 of file Wm4Delaunay1.cpp.
References WM4_DELETE.
Delaunay1() [2/2]
template<class Real > Wm4::Delaunay1< Real >::Delaunay1 (const char * acFilename)
Definition at line 209 of file Wm4Delaunay1.cpp.
References Wm4::Delaunay1< Real >::Load().
Member Function Documentation
GetAdjacentSet()
template<class Real > bool Wm4::Delaunay1< Real >::GetAdjacentSet (int i, int aiAdjacent[2]) const
Definition at line 161 of file Wm4Delaunay1.cpp.
References SplineSurface::i.
GetBarycentricSet()
template<class Real > bool Wm4::Delaunay1< Real >::GetBarycentricSet (int i, const Real fP, Real afBary[2]) const
Definition at line 179 of file Wm4Delaunay1.cpp.
References SplineSurface::i.
GetContainingSegment()
template<class Real > int Wm4::Delaunay1< Real >::GetContainingSegment (const Real fP) const
Definition at line 93 of file Wm4Delaunay1.cpp.
References SplineSurface::i.
GetHull()
template<class Real > bool Wm4::Delaunay1< Real >::GetHull (int aiIndex[2])
Definition at line 79 of file Wm4Delaunay1.cpp.
GetIndexSet()
template<class Real > bool Wm4::Delaunay1< Real >::GetIndexSet (int i, int aiIndex[2]) const
Definition at line 143 of file Wm4Delaunay1.cpp.
References SplineSurface::i.
GetVertexSet()
template<class Real > bool Wm4::Delaunay1< Real >::GetVertexSet (int i, Real afV[2]) const
Definition at line 125 of file Wm4Delaunay1.cpp.
References SplineSurface::i.
GetVertices()
template<class Real > const Real * Wm4::Delaunay1< Real >::GetVertices
Definition at line 73 of file Wm4Delaunay1.cpp.
Load()
template<class Real > bool Wm4::Delaunay1< Real >::Load (const char * acFilename)
Definition at line 220 of file Wm4Delaunay1.cpp.
References Wm4::System::Fclose(), Wm4::System::Fopen(), Wm4::Delaunay< Real >::Load(), Wm4::System::Read4le(), Wm4::System::Read8le(), WM4_DELETE, and WM4_NEW.
Referenced by Wm4::Delaunay1< Real >::Delaunay1().
Save()
template<class Real > bool Wm4::Delaunay1< Real >::Save (const char * acFilename) const
Definition at line 253 of file Wm4Delaunay1.cpp.
References Wm4::System::Fclose(), Wm4::System::Fopen(), Wm4::Delaunay< Real >::Save(), Wm4::System::Write4le(), and Wm4::System::Write8le().
The documentation for this class was generated from the following files:
Wm4Delaunay1.h
Wm4Delaunay1.cpp