FreeCAD: SketcherGui::EditModeGeometryCoinConverter Class Reference
SketcherGui::EditModeGeometryCoinConverter Class Reference
Class for creating the Geometry layer into coin nodes.
#include <EditModeGeometryCoinConverter.h>
Public Member Functions
EditModeGeometryCoinConverter (ViewProviderSketch &vp, GeometryLayerNodes &geometrylayernodes, DrawingParameters &drawingparameters, GeometryLayerParameters &geometryLayerParams, CoinMapping &coinMap)
void convert (const Sketcher::GeoListFacade &geolistfacade)
float getBoundingBoxMaxMagnitude ()
double getCombRepresentationScale ()
auto getBSplineGeoIds ()
auto getArcGeoIds ()
Detailed Description
Class for creating the Geometry layer into coin nodes.
Responsibility: To create and update GeometryLayer nodes provided as constructor parameter for the provided geometry, taking into account the drawing parameters provided as constructor parameters.
Interface: A single entry point convert(), performing the following flow:
[Geometry] => Analysis => construct drawing elements => Create mappings GeoId coin => populate coin nodes
Analysis performs analysis such as maximum boundingbox magnitude of all geometries and maximum curvature of BSplines
Definition at line 74 of file EditModeGeometryCoinConverter.h.
Constructor & Destructor Documentation
EditModeGeometryCoinConverter()
EditModeGeometryCoinConverter::EditModeGeometryCoinConverter (ViewProviderSketch & vp, GeometryLayerNodes & geometrylayernodes, DrawingParameters & drawingparameters, GeometryLayerParameters & geometryLayerParams, CoinMapping & coinMap)
Constructs an GeometryCoinConverter responsible for generating the points and line sets for drawing the geometry defined by a GeometryLayer into the coin nodes provided by GeometryLayerNodes.
Parameters
geometrylayernodes The coin nodes to be populated with the geometry
drawingparameters Parameters for drawing the overlay information
Definition at line 37 of file EditModeGeometryCoinConverter.cpp.
Member Function Documentation
convert()
void EditModeGeometryCoinConverter::convert (const Sketcher::GeoListFacade & geolistfacade)
converts the geometry defined by GeometryLayer into the coin nodes.
Parameters
geometry the geometry to be processed
Definition at line 50 of file EditModeGeometryCoinConverter.cpp.
References SketcherGui::CoinMapping::clear(), SketcherGui::GeometryLayerNodes::CurvesCoordinate, SketcherGui::GeometryLayerNodes::CurveSet, SketcherGui::GeometryLayerNodes::CurvesMaterials, SketcherGui::CoinMapping::CurvIdToGeoId, Sketcher::end, SketcherGui::CoinMapping::GeoElementId2SetId, Sketcher::GeoListModel< T >::geomlist, Base::Persistence::getClassTypeId(), SketcherGui::GeometryLayerParameters::getCoinLayerCount(), Sketcher::GeoListModel< T >::getGeoIdFromGeomListIndex(), Sketcher::GeoListModel< T >::getGeometryFacadeFromGeoId(), SketcherGui::GeometryLayerParameters::getSafeCoinLayer(), getSafeGeomLayerId(), SketcherGui::GeometryLayerParameters::getSubLayerCount(), SketcherGui::GeometryLayerParameters::getSubLayerIndex(), SplineSurface::i, RobotExample::l, Sketcher::mid, Sketcher::none, SketcherGui::CoinMapping::PointIdToGeoId, SketcherGui::CoinMapping::PointIdToPosId, SketcherGui::CoinMapping::PointIdToVertexId, SketcherGui::GeometryLayerNodes::PointsCoordinate, SketcherGui::GeometryLayerNodes::PointsMaterials, RobotExample::pos, Sketcher::GeoElementId::RtPnt, Sketcher::start, InitGui::t, Path.Post.scripts.grbl_post::type, SketcherGui::DrawingParameters::zLowLines, and SketcherGui::DrawingParameters::zLowPoints.
Referenced by SketcherGui::EditModeGeometryCoinManager::processGeometry().
getArcGeoIds()
auto SketcherGui::EditModeGeometryCoinConverter::getArcGeoIds () inline
returns the GeoIds of Arc geometries
Definition at line 148 of file EditModeGeometryCoinConverter.h.
References Path.Post.scripts.opensbp_post::move().
Referenced by SketcherGui::EditModeGeometryCoinManager::processGeometry().
getBoundingBoxMaxMagnitude()
float EditModeGeometryCoinConverter::getBoundingBoxMaxMagnitude ()
returns the maximum of the vertical and horizontal magnitudes of the coordinates of the points and lines added to coin by this layer (local responsibility).
Definition at line 466 of file EditModeGeometryCoinConverter.cpp.
Referenced by SketcherGui::EditModeGeometryCoinManager::processGeometry().
getBSplineGeoIds()
auto SketcherGui::EditModeGeometryCoinConverter::getBSplineGeoIds () inline
returns the GeoIds of BSpline geometries
Definition at line 140 of file EditModeGeometryCoinConverter.h.
References Path.Post.scripts.opensbp_post::move().
Referenced by SketcherGui::EditModeGeometryCoinManager::processGeometry().
getCombRepresentationScale()
double EditModeGeometryCoinConverter::getCombRepresentationScale ()
returns the Comb representation scale that should be used to represent the B-Splines of this layer (local responsibility).
Definition at line 471 of file EditModeGeometryCoinConverter.cpp.
Referenced by SketcherGui::EditModeGeometryCoinManager::processGeometry().
The documentation for this class was generated from the following files:
EditModeGeometryCoinConverter.h
EditModeGeometryCoinConverter.cpp