FreeCAD: automotive_design.feature_definition Class Reference
automotive_design.feature_definition Class Reference
Public Member Functions
def __init__ (self, inherited0__name, inherited1__description)
def wr1 (self)
def wr2 (self)
def wr3 (self)
def wr4 (self)
def wr5 (self)
def wr6 (self)
Public Member Functions inherited from automotive_design.characterized_object
def name ()
def description ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Additional Inherited Members
Public Attributes inherited from automotive_design.characterized_object
name
description
Detailed Description
Entity feature_definition definition.
Definition at line 2475 of file automotive_design.py.
Constructor & Destructor Documentation
__init__()
def automotive_design.feature_definition.__init__ (self, inherited0__name, inherited1__description)
Reimplemented from automotive_design.characterized_object.
Reimplemented in automotive_design.general_feature, automotive_design.rectangular_pattern, automotive_design.joggle, automotive_design.thread, automotive_design.pocket, automotive_design.modified_pattern, automotive_design.bead, automotive_design.round_hole, automotive_design.feature_pattern, automotive_design.circular_pattern, automotive_design.replicate_feature, automotive_design.rib, automotive_design.locator, automotive_design.slot, automotive_design.hole_in_panel, automotive_design.feature_in_panel, automotive_design.boss, automotive_design.barring_hole, automotive_design.composite_hole, and automotive_design.compound_feature.
Definition at line 2478 of file automotive_design.py.
Member Function Documentation
wr1()
def automotive_design.feature_definition.wr1 (self)
Reimplemented in automotive_design.general_feature, automotive_design.rectangular_pattern, automotive_design.joggle, automotive_design.thread, automotive_design.pocket, automotive_design.modified_pattern, automotive_design.bead, automotive_design.round_hole, automotive_design.feature_pattern, automotive_design.instanced_feature, automotive_design.externally_defined_feature_definition, automotive_design.circular_pattern, automotive_design.replicate_feature, automotive_design.rib, automotive_design.locator, automotive_design.slot, automotive_design.hole_in_panel, automotive_design.feature_in_panel, automotive_design.boss, automotive_design.barring_hole, automotive_design.composite_hole, and automotive_design.compound_feature.
Definition at line 2480 of file automotive_design.py.
References SCL.Builtin.SIZEOF().
Referenced by config_control_design.week_in_year_number.__init__(), config_control_design.minute_in_hour.__init__(), config_control_design.dimension_count.__init__(), config_control_design.positive_length_measure.__init__(), config_control_design.hour_in_day.__init__(), config_control_design.positive_plane_angle_measure.__init__(), ifc2x3.ifctextalignment.__init__(), config_control_design.day_in_week_number.__init__(), ifc4.ifctextalignment.__init__(), ifc2x3.ifcspecularroughness.__init__(), config_control_design.month_in_year_number.__init__(), ifc2x3.ifcheatingvaluemeasure.__init__(), config_control_design.second_in_minute.__init__(), ifc4.ifcspecularroughness.__init__(), ifc2x3.ifctexttransformation.__init__(), ifc4.ifcheatingvaluemeasure.__init__(), ifc4.ifctexttransformation.__init__(), ifc2x3.ifcfontstyle.__init__(), ifc2x3.ifcboxalignment.__init__(), ifc2x3.ifcminuteinhour.__init__(), ifc4.ifcfontstyle.__init__(), ifc2x3.ifcpositiveplaneanglemeasure.__init__(), ifc4.ifcboxalignment.__init__(), ifc2x3.ifcdimensioncount.__init__(), ifc4.ifcpositiveplaneanglemeasure.__init__(), ifc4.ifcdimensioncount.__init__(), ifc2x3.ifcdaylightsavinghour.__init__(), ifc2x3.ifcmonthinyearnumber.__init__(), ifc2x3.ifcsecondinminute.__init__(), ifc2x3.ifcfontvariant.__init__(), ifc2x3.ifcfontweight.__init__(), ifc2x3.ifchourinday.__init__(), ifc2x3.ifcnormalisedratiomeasure.__init__(), ifc2x3.ifcpositivelengthmeasure.__init__(), ifc2x3.ifcpositiveratiomeasure.__init__(), ifc4.ifcfontvariant.__init__(), ifc4.ifcfontweight.__init__(), ifc2x3.ifctextdecoration.__init__(), ifc4.ifcnormalisedratiomeasure.__init__(), ifc4.ifcpositivelengthmeasure.__init__(), ifc4.ifcpositiveratiomeasure.__init__(), and ifc4.ifctextdecoration.__init__().
wr2()
def automotive_design.feature_definition.wr2 (self)
Reimplemented in automotive_design.general_feature, automotive_design.rectangular_pattern, automotive_design.joggle, automotive_design.thread, automotive_design.pocket, automotive_design.modified_pattern, automotive_design.bead, automotive_design.round_hole, automotive_design.feature_pattern, automotive_design.instanced_feature, automotive_design.externally_defined_feature_definition, automotive_design.circular_pattern, automotive_design.replicate_feature, automotive_design.rib, automotive_design.locator, automotive_design.slot, automotive_design.hole_in_panel, automotive_design.feature_in_panel, automotive_design.boss, automotive_design.barring_hole, automotive_design.composite_hole, and automotive_design.compound_feature.
Definition at line 2487 of file automotive_design.py.
References SCL.Builtin.SIZEOF().
wr3()
def automotive_design.feature_definition.wr3 (self)
Reimplemented in automotive_design.general_feature, automotive_design.rectangular_pattern, automotive_design.joggle, automotive_design.thread, automotive_design.pocket, automotive_design.bead, automotive_design.round_hole, automotive_design.instanced_feature, automotive_design.externally_defined_feature_definition, automotive_design.circular_pattern, automotive_design.replicate_feature, automotive_design.rib, automotive_design.locator, automotive_design.slot, automotive_design.feature_in_panel, automotive_design.boss, automotive_design.barring_hole, automotive_design.composite_hole, and automotive_design.compound_feature.
Definition at line 2494 of file automotive_design.py.
References SCL.Builtin.SIZEOF(), and SCL.Builtin.TYPEOF().
wr4()
def automotive_design.feature_definition.wr4 (self)
Reimplemented in automotive_design.general_feature, automotive_design.rectangular_pattern, automotive_design.joggle, automotive_design.thread, automotive_design.pocket, automotive_design.bead, automotive_design.round_hole, automotive_design.externally_defined_feature_definition, automotive_design.circular_pattern, automotive_design.rib, automotive_design.locator, automotive_design.slot, automotive_design.feature_in_panel, automotive_design.boss, automotive_design.barring_hole, automotive_design.composite_hole, and automotive_design.compound_feature.
Definition at line 2501 of file automotive_design.py.
References SCL.Builtin.SIZEOF().
wr5()
def automotive_design.feature_definition.wr5 (self)
Reimplemented in automotive_design.general_feature, automotive_design.rectangular_pattern, automotive_design.joggle, automotive_design.thread, automotive_design.pocket, automotive_design.bead, automotive_design.round_hole, automotive_design.externally_defined_feature_definition, automotive_design.circular_pattern, automotive_design.rib, automotive_design.locator, automotive_design.slot, automotive_design.feature_in_panel, automotive_design.boss, automotive_design.barring_hole, automotive_design.composite_hole, and automotive_design.compound_feature.
Definition at line 2508 of file automotive_design.py.
References SCL.Builtin.SIZEOF(), and SCL.Builtin.TYPEOF().
wr6()
def automotive_design.feature_definition.wr6 (self)
Reimplemented in automotive_design.rectangular_pattern, automotive_design.joggle, automotive_design.thread, automotive_design.pocket, automotive_design.bead, automotive_design.externally_defined_feature_definition, automotive_design.rib, automotive_design.feature_in_panel, automotive_design.boss, and automotive_design.compound_feature.
Definition at line 2515 of file automotive_design.py.
References SCL.Builtin.SIZEOF(), and SCL.Builtin.TYPEOF().
The documentation for this class was generated from the following file:
automotive_design.py