FreeCAD: CAMTests.TestPathSetupSheet.SomeOp Class Reference
CAMTests.TestPathSetupSheet.SomeOp Class Reference
Public Member Functions
def __init__ (self, obj)
def SetupProperties (cls)
def Create (cls, name, obj=None, parentJob=None)
Detailed Description
Definition at line 38 of file TestPathSetupSheet.py.
Constructor & Destructor Documentation
__init__()
def CAMTests.TestPathSetupSheet.SomeOp.__init__ (self, obj)
Definition at line 39 of file TestPathSetupSheet.py.
References Path.Log.track(), and Path.Post.scripts.grbl_post.type.
Referenced by draftguitools.gui_subelements.SubelementHighlight.finish().
Member Function Documentation
Create()
def CAMTests.TestPathSetupSheet.SomeOp.Create (cls, name, obj = None, parentJob = None)
Definition at line 48 of file TestPathSetupSheet.py.
References Path.Log.track().
SetupProperties()
def CAMTests.TestPathSetupSheet.SomeOp.SetupProperties (cls)
Definition at line 44 of file TestPathSetupSheet.py.
The documentation for this class was generated from the following file:
TestPathSetupSheet.py