FreeCAD: ifc2x3.ifcmechanicalsteelmaterialproperties Class Reference
ifc2x3.ifcmechanicalsteelmaterialproperties Class Reference
Public Member Functions
def __init__ (self, inherited0__material, inherited1__dynamicviscosity, inherited2__youngmodulus, inherited3__shearmodulus, inherited4__poissonratio, inherited5__thermalexpansioncoefficient, yieldstress, ultimatestress, ultimatestrain, hardeningmodule, proportionalstress, plasticstrain, relaxations)
def yieldstress ()
def ultimatestress ()
def ultimatestrain ()
def hardeningmodule ()
def proportionalstress ()
def plasticstrain ()
def relaxations ()
def wr31 (self)
def wr32 (self)
def wr33 (self)
def wr34 (self)
Public Member Functions inherited from ifc2x3.ifcmechanicalmaterialproperties
def __init__ (self, inherited0__material, dynamicviscosity, youngmodulus, shearmodulus, poissonratio, thermalexpansioncoefficient)
def dynamicviscosity ()
def youngmodulus ()
def shearmodulus ()
def poissonratio ()
def thermalexpansioncoefficient ()
def wr21 (self)
def wr22 (self)
Public Member Functions inherited from ifc2x3.ifcmaterialproperties
def __init__ (self, material)
def material ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
yieldstress
ultimatestress
ultimatestrain
hardeningmodule
proportionalstress
plasticstrain
relaxations
Public Attributes inherited from ifc2x3.ifcmechanicalmaterialproperties
dynamicviscosity
youngmodulus
shearmodulus
poissonratio
thermalexpansioncoefficient
Public Attributes inherited from ifc2x3.ifcmaterialproperties
material
Detailed Description
Entity ifcmechanicalsteelmaterialproperties definition.
:param yieldstress
:type yieldstress:ifcpressuremeasure
:param ultimatestress
:type ultimatestress:ifcpressuremeasure
:param ultimatestrain
:type ultimatestrain:ifcpositiveratiomeasure
:param hardeningmodule
:type hardeningmodule:ifcmodulusofelasticitymeasure
:param proportionalstress
:type proportionalstress:ifcpressuremeasure
:param plasticstrain
:type plasticstrain:ifcpositiveratiomeasure
:param relaxations
:type relaxations:SET(1,None,'ifcrelaxation', scope = schema_scope)
Definition at line 14292 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcmechanicalsteelmaterialproperties.__init__ (self, inherited0__material, inherited1__dynamicviscosity, inherited2__youngmodulus, inherited3__shearmodulus, inherited4__poissonratio, inherited5__thermalexpansioncoefficient, yieldstress, ultimatestress, ultimatestrain, hardeningmodule, proportionalstress, plasticstrain, relaxations)
Definition at line 14316 of file ifc2x3.py.
Member Function Documentation
hardeningmodule()
def ifc2x3.ifcmechanicalsteelmaterialproperties.hardeningmodule ()
Definition at line 14369 of file ifc2x3.py.
References ifc2x3.ifcmechanicalsteelmaterialproperties._hardeningmodule, SCL.TypeChecker.check_type(), and ifc2x3.ifcmechanicalsteelmaterialproperties.hardeningmodule.
plasticstrain()
def ifc2x3.ifcmechanicalsteelmaterialproperties.plasticstrain ()
Definition at line 14397 of file ifc2x3.py.
References ifc2x3.ifcmechanicalsteelmaterialproperties._plasticstrain, SCL.TypeChecker.check_type(), and ifc2x3.ifcmechanicalsteelmaterialproperties.plasticstrain.
proportionalstress()
def ifc2x3.ifcmechanicalsteelmaterialproperties.proportionalstress ()
Definition at line 14383 of file ifc2x3.py.
References ifc2x3.ifcmechanicalsteelmaterialproperties._proportionalstress, SCL.TypeChecker.check_type(), and ifc2x3.ifcmechanicalsteelmaterialproperties.proportionalstress.
relaxations()
def ifc2x3.ifcmechanicalsteelmaterialproperties.relaxations ()
Definition at line 14411 of file ifc2x3.py.
References ifc2x3.ifcmechanicalsteelmaterialproperties._relaxations, SCL.TypeChecker.check_type(), and ifc2x3.ifcmechanicalsteelmaterialproperties.relaxations.
ultimatestrain()
def ifc2x3.ifcmechanicalsteelmaterialproperties.ultimatestrain ()
Definition at line 14355 of file ifc2x3.py.
References ifc2x3.ifcmechanicalsteelmaterialproperties._ultimatestrain, SCL.TypeChecker.check_type(), and ifc2x3.ifcmechanicalsteelmaterialproperties.ultimatestrain.
ultimatestress()
def ifc2x3.ifcmechanicalsteelmaterialproperties.ultimatestress ()
Definition at line 14341 of file ifc2x3.py.
References ifc2x3.ifcmechanicalsteelmaterialproperties._ultimatestress, SCL.TypeChecker.check_type(), and ifc2x3.ifcmechanicalsteelmaterialproperties.ultimatestress.
wr31()
def ifc2x3.ifcmechanicalsteelmaterialproperties.wr31 (self)
Definition at line 14423 of file ifc2x3.py.
References SCL.Builtin.EXISTS(), and ifc2x3.ifcmechanicalsteelmaterialproperties.yieldstress.
wr32()
def ifc2x3.ifcmechanicalsteelmaterialproperties.wr32 (self)
Definition at line 14430 of file ifc2x3.py.
References SCL.Builtin.EXISTS(), and ifc2x3.ifcmechanicalsteelmaterialproperties.ultimatestress.
wr33()
def ifc2x3.ifcmechanicalsteelmaterialproperties.wr33 (self)
Definition at line 14437 of file ifc2x3.py.
References SCL.Builtin.EXISTS(), and ifc2x3.ifcmechanicalsteelmaterialproperties.hardeningmodule.
wr34()
def ifc2x3.ifcmechanicalsteelmaterialproperties.wr34 (self)
Definition at line 14444 of file ifc2x3.py.
References SCL.Builtin.EXISTS(), and ifc2x3.ifcmechanicalsteelmaterialproperties.proportionalstress.
yieldstress()
def ifc2x3.ifcmechanicalsteelmaterialproperties.yieldstress ()
Definition at line 14327 of file ifc2x3.py.
References ifc2x3.ifcmechanicalsteelmaterialproperties._yieldstress, SCL.TypeChecker.check_type(), and ifc2x3.ifcmechanicalsteelmaterialproperties.yieldstress.
Member Data Documentation
hardeningmodule
ifc2x3.ifcmechanicalsteelmaterialproperties.hardeningmodule
Definition at line 14321 of file ifc2x3.py.
Referenced by ifc2x3.ifcmechanicalsteelmaterialproperties.hardeningmodule(), and ifc2x3.ifcmechanicalsteelmaterialproperties.wr33().
plasticstrain
ifc2x3.ifcmechanicalsteelmaterialproperties.plasticstrain
Definition at line 14323 of file ifc2x3.py.
Referenced by ifc2x3.ifcmechanicalsteelmaterialproperties.plasticstrain().
proportionalstress
ifc2x3.ifcmechanicalsteelmaterialproperties.proportionalstress
Definition at line 14322 of file ifc2x3.py.
Referenced by ifc2x3.ifcmechanicalsteelmaterialproperties.proportionalstress(), and ifc2x3.ifcmechanicalsteelmaterialproperties.wr34().
relaxations
ifc2x3.ifcmechanicalsteelmaterialproperties.relaxations
Definition at line 14324 of file ifc2x3.py.
Referenced by ifc2x3.ifcmechanicalsteelmaterialproperties.relaxations().
ultimatestrain
ifc2x3.ifcmechanicalsteelmaterialproperties.ultimatestrain
Definition at line 14320 of file ifc2x3.py.
Referenced by ifc2x3.ifcmechanicalsteelmaterialproperties.ultimatestrain().
ultimatestress
ifc2x3.ifcmechanicalsteelmaterialproperties.ultimatestress
Definition at line 14319 of file ifc2x3.py.
Referenced by ifc2x3.ifcmechanicalsteelmaterialproperties.ultimatestress(), and ifc2x3.ifcmechanicalsteelmaterialproperties.wr32().
yieldstress
ifc2x3.ifcmechanicalsteelmaterialproperties.yieldstress
Definition at line 14318 of file ifc2x3.py.
Referenced by ifc2x3.ifcmechanicalsteelmaterialproperties.wr31(), and ifc2x3.ifcmechanicalsteelmaterialproperties.yieldstress().
The documentation for this class was generated from the following file:
ifc2x3.py