FreeCAD: TechDrawGui::TaskHatch Class Reference
TechDrawGui::TaskHatch Class Reference
#include <TaskHatch.h>
Public Member Functions
TaskHatch (TechDraw::DrawViewPart *inDvp, std::vector< std::string > subs)
TaskHatch (TechDrawGui::ViewProviderHatch *inVp)
~TaskHatch () override
virtual bool accept ()
virtual bool reject ()
Protected Slots
void onFileChanged ()
void onScaleChanged ()
void onColorChanged ()
void onRotationChanged ()
void onOffsetChanged ()
Protected Member Functions
void changeEvent (QEvent *e) override
void apply (bool forceUpdate=false)
void createHatch ()
void updateHatch ()
void setUiPrimary ()
void setUiEdit ()
void saveHatchState ()
void restoreHatchState ()
void getParameters ()
Detailed Description
Definition at line 46 of file TaskHatch.h.
Constructor & Destructor Documentation
TaskHatch() [1/2]
TaskHatch::TaskHatch (TechDraw::DrawViewPart * inDvp, std::vector< std::string > subs)
Definition at line 53 of file TaskHatch.cpp.
References draftgeoutils.intersections::connect(), onColorChanged(), onFileChanged(), onOffsetChanged(), onRotationChanged(), onScaleChanged(), and setUiPrimary().
TaskHatch() [2/2]
TaskHatch::TaskHatch (TechDrawGui::ViewProviderHatch * inVp) explicit
Definition at line 71 of file TaskHatch.cpp.
References draftgeoutils.intersections::connect(), App::PropertyLinkSub::getValue(), TechDrawGui::ViewProviderHatch::getViewObject(), onColorChanged(), onFileChanged(), onOffsetChanged(), onRotationChanged(), onScaleChanged(), saveHatchState(), setUiEdit(), and TechDraw::DrawHatch::Source.
~TaskHatch()
TaskHatch::~TaskHatch () override
Definition at line 91 of file TaskHatch.cpp.
Member Function Documentation
accept()
bool TaskHatch::accept () virtual
Definition at line 257 of file TaskHatch.cpp.
References apply(), doCommand, and Gui::Command::Gui.
Referenced by TechDrawGui::TaskDlgHatch::accept().
apply()
void TaskHatch::apply (bool forceUpdate = false) protected
Definition at line 175 of file TaskHatch.cpp.
References createHatch(), App::DocumentObject::recomputeFeature(), and updateHatch().
Referenced by accept(), onColorChanged(), onFileChanged(), onOffsetChanged(), onRotationChanged(), and onScaleChanged().
changeEvent()
void TaskHatch::changeEvent (QEvent * e) override protected
Definition at line 275 of file TaskHatch.cpp.
References SCL.SimpleDataTypes::e.
createHatch()
void TaskHatch::createHatch () protected
Definition at line 193 of file TaskHatch.cpp.
References TechDraw::DrawUtil::cleanFilespecBackslash(), Base::Console(), toolbit-attributes::doc, doCommand, Base::ConsoleSingleton::Error(), App::DocumentObject::getDocument(), Gui::Application::getDocument(), Gui::Document::getViewProvider(), TechDrawGui::ViewProviderHatch::HatchColor, TechDrawGui::ViewProviderHatch::HatchOffset, TechDrawGui::ViewProviderHatch::HatchRotation, TechDrawGui::ViewProviderHatch::HatchScale, Gui::Application::Instance, Arch::QT_TRANSLATE_NOOP, App::PropertyVector::setValue(), App::Color::setValue(), App::PropertyFloat::setValue(), App::PropertyLinkSub::setValue(), App::PropertyColor::setValue(), and TechDraw::DrawHatch::Source.
Referenced by apply().
getParameters()
void TechDrawGui::TaskHatch::getParameters () protected
onColorChanged
void TaskHatch::onColorChanged () protected slot
Definition at line 156 of file TaskHatch.cpp.
References apply(), and App::Color::setValue().
Referenced by TaskHatch().
onFileChanged
void TaskHatch::onFileChanged () protected slot
Definition at line 144 of file TaskHatch.cpp.
References apply().
Referenced by TaskHatch().
onOffsetChanged
void TaskHatch::onOffsetChanged () protected slot
Definition at line 168 of file TaskHatch.cpp.
References apply(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by TaskHatch().
onRotationChanged
void TaskHatch::onRotationChanged () protected slot
Definition at line 162 of file TaskHatch.cpp.
References apply().
Referenced by TaskHatch().
onScaleChanged
void TaskHatch::onScaleChanged () protected slot
Definition at line 150 of file TaskHatch.cpp.
References apply().
Referenced by TaskHatch().
reject()
bool TaskHatch::reject () virtual
Definition at line 267 of file TaskHatch.cpp.
References doCommand, Gui::Command::Gui, and restoreHatchState().
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and TechDrawGui::TaskDlgHatch::reject().
restoreHatchState()
void TaskHatch::restoreHatchState () protected
Definition at line 132 of file TaskHatch.cpp.
References TechDrawGui::ViewProviderHatch::HatchColor, TechDrawGui::ViewProviderHatch::HatchOffset, TechDraw::DrawHatch::HatchPattern, TechDrawGui::ViewProviderHatch::HatchRotation, TechDrawGui::ViewProviderHatch::HatchScale, App::PropertyVector::setValue(), App::PropertyFloat::setValue(), App::PropertyString::setValue(), and App::PropertyColor::setValue().
Referenced by reject().
saveHatchState()
void TaskHatch::saveHatchState () protected
Definition at line 121 of file TaskHatch.cpp.
References App::PropertyVector::getValue(), App::PropertyFloat::getValue(), App::PropertyString::getValue(), App::PropertyColor::getValue(), TechDrawGui::ViewProviderHatch::HatchColor, TechDrawGui::ViewProviderHatch::HatchOffset, TechDraw::DrawHatch::HatchPattern, TechDrawGui::ViewProviderHatch::HatchRotation, and TechDrawGui::ViewProviderHatch::HatchScale.
Referenced by TaskHatch().
setUiEdit()
void TaskHatch::setUiEdit () protected
Definition at line 107 of file TaskHatch.cpp.
References App::Color::asValue(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by TaskHatch().
setUiPrimary()
void TaskHatch::setUiPrimary () protected
Definition at line 95 of file TaskHatch.cpp.
References TechDraw::DrawHatch::prefSvgHatchColor().
Referenced by TaskHatch().
updateHatch()
void TaskHatch::updateHatch () protected
Definition at line 234 of file TaskHatch.cpp.
References TechDraw::DrawUtil::cleanFilespecBackslash(), doCommand, App::DocumentObject::getNameInDocument(), TechDrawGui::ViewProviderHatch::HatchColor, TechDrawGui::ViewProviderHatch::HatchOffset, TechDrawGui::ViewProviderHatch::HatchRotation, TechDrawGui::ViewProviderHatch::HatchScale, Arch::QT_TRANSLATE_NOOP, App::PropertyVector::setValue(), App::Color::setValue(), App::PropertyFloat::setValue(), and App::PropertyColor::setValue().
Referenced by apply().
The documentation for this class was generated from the following files:
TaskHatch.h
TaskHatch.cpp