FreeCAD: MeshCore::PlaneSurfaceFit Class Reference
MeshCore::PlaneSurfaceFit Class Reference
#include <Segmentation.h>
Public Member Functions
PlaneSurfaceFit ()
PlaneSurfaceFit (const Base::Vector3f &b, const Base::Vector3f &n)
~PlaneSurfaceFit () override
PlaneSurfaceFit (const PlaneSurfaceFit &)=delete
PlaneSurfaceFit (PlaneSurfaceFit &&)=delete
PlaneSurfaceFit & operator= (const PlaneSurfaceFit &)=delete
PlaneSurfaceFit & operator= (PlaneSurfaceFit &&)=delete
const char * GetType () const override
void Initialize (const MeshGeomFacet &) override
bool TestTriangle (const MeshGeomFacet &) const override
void AddTriangle (const MeshGeomFacet &) override
bool Done () const override
float Fit () override
float GetDistanceToSurface (const Base::Vector3f &) const override
std::vector< float > Parameters () const override
Public Member Functions inherited from MeshCore::AbstractSurfaceFit
AbstractSurfaceFit ()=default
virtual ~AbstractSurfaceFit ()=default
AbstractSurfaceFit (const AbstractSurfaceFit &)=delete
AbstractSurfaceFit (AbstractSurfaceFit &&)=delete
AbstractSurfaceFit & operator= (const AbstractSurfaceFit &)=delete
AbstractSurfaceFit & operator= (AbstractSurfaceFit &&)=delete
Detailed Description
Definition at line 158 of file Mesh/App/Core/Segmentation.h.
Constructor & Destructor Documentation
PlaneSurfaceFit() [1/4]
PlaneSurfaceFit::PlaneSurfaceFit ()
Definition at line 113 of file Mesh/App/Core/Segmentation.cpp.
PlaneSurfaceFit() [2/4]
PlaneSurfaceFit::PlaneSurfaceFit (const Base::Vector3f & b, const Base::Vector3f & n)
Definition at line 117 of file Mesh/App/Core/Segmentation.cpp.
~PlaneSurfaceFit()
PlaneSurfaceFit::~PlaneSurfaceFit () override
Definition at line 123 of file Mesh/App/Core/Segmentation.cpp.
PlaneSurfaceFit() [3/4]
MeshCore::PlaneSurfaceFit::PlaneSurfaceFit (const PlaneSurfaceFit &) delete
PlaneSurfaceFit() [4/4]
MeshCore::PlaneSurfaceFit::PlaneSurfaceFit (PlaneSurfaceFit &&) delete
Member Function Documentation
AddTriangle()
void PlaneSurfaceFit::AddTriangle (const MeshGeomFacet & tria) override virtual
Implements MeshCore::AbstractSurfaceFit.
Definition at line 148 of file Mesh/App/Core/Segmentation.cpp.
References MeshCore::Approximation::AddPoint(), and MeshCore::MeshGeomFacet::GetGravityPoint().
Done()
bool PlaneSurfaceFit::Done () const override virtual
Implements MeshCore::AbstractSurfaceFit.
Definition at line 155 of file Mesh/App/Core/Segmentation.cpp.
References MeshCore::Approximation::Done().
Fit()
float PlaneSurfaceFit::Fit () override virtual
Implements MeshCore::AbstractSurfaceFit.
Definition at line 164 of file Mesh/App/Core/Segmentation.cpp.
References MeshCore::PlaneFit::Fit().
GetDistanceToSurface()
float PlaneSurfaceFit::GetDistanceToSurface (const Base::Vector3f & pnt) const override virtual
Implements MeshCore::AbstractSurfaceFit.
Definition at line 173 of file Mesh/App/Core/Segmentation.cpp.
References Base::Vector3< float_type >::DistanceToPlane(), and MeshCore::PlaneFit::GetDistanceToPlane().
GetType()
const char* MeshCore::PlaneSurfaceFit::GetType () const inline override virtual
Implements MeshCore::AbstractSurfaceFit.
Definition at line 170 of file Mesh/App/Core/Segmentation.h.
Initialize()
void PlaneSurfaceFit::Initialize (const MeshGeomFacet & tria) override virtual
Implements MeshCore::AbstractSurfaceFit.
Definition at line 128 of file Mesh/App/Core/Segmentation.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, MeshCore::Approximation::AddPoint(), MeshCore::Approximation::Clear(), MeshCore::PlaneFit::Fit(), MeshCore::MeshGeomFacet::GetGravityPoint(), and MeshCore::MeshGeomFacet::GetNormal().
operator=() [1/2]
PlaneSurfaceFit& MeshCore::PlaneSurfaceFit::operator= (const PlaneSurfaceFit &) delete
operator=() [2/2]
PlaneSurfaceFit& MeshCore::PlaneSurfaceFit::operator= (PlaneSurfaceFit &&) delete
Parameters()
std::vector< float > PlaneSurfaceFit::Parameters () const override virtual
Implements MeshCore::AbstractSurfaceFit.
Definition at line 182 of file Mesh/App/Core/Segmentation.cpp.
References SCL.SimpleDataTypes::c, MeshCore::PlaneFit::GetBase(), MeshCore::PlaneFit::GetNormal(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
TestTriangle()
bool PlaneSurfaceFit::TestTriangle (const MeshGeomFacet &) const override virtual
Implements MeshCore::AbstractSurfaceFit.
Definition at line 143 of file Mesh/App/Core/Segmentation.cpp.
The documentation for this class was generated from the following files:
Mesh/App/Core/Segmentation.h
Mesh/App/Core/Segmentation.cpp