FreeCAD: Measure::ShapeFinder Class Reference
Measure::ShapeFinder Class Reference
a class to obtain the located shape pointed at by a selection
#include <ShapeFinder.h>
Static Public Member Functions
static TopoDS_Shape getLocatedShape (const App::DocumentObject &rootObject, const std::string &leafSub)
static Part::TopoShape getLocatedTopoShape (const App::DocumentObject &rootObject, const std::string &leafSub)
convenient version of previous method
static std::pair< Base::Placement, Base::Matrix4D > getGlobalTransform (const App::DocumentObject &rootObject, const std::string &leafSub)
static std::pair< Base::Placement, Base::Matrix4D > getGlobalTransform (const App::DocumentObject *cursorObject)
static void crawlPlacementChain (std::vector< Base::Placement > &plmStack, std::vector< Base::Matrix4D > &scaleStack, const App::DocumentObject &rootObj, const std::string &leafSub)
static ResolveResult resolveSelection (const App::DocumentObject &selectObj, const std::string &selectLongSub)
static Base::Placement getPlacement (const App::DocumentObject *root)
this getter should work for any object, not just links
static Base::Matrix4D getScale (const App::DocumentObject *root)
static bool isLinkLike (const App::DocumentObject *obj)
static std::string PlacementAsString (const Base::Placement &inPlacement)
debugging routine that returns a string representation of a placement.
static std::string LocationAsString (const TopLoc_Location &location)
debug routine. return readable form of TopLoc_Location from OCC
static TopoDS_Shape transformShape (TopoDS_Shape &inShape, const Base::Placement &placement, const Base::Matrix4D &scaler)
static TopoDS_Shape stripInfiniteShapes (const TopoDS_Shape &inShape)
static bool isShapeReallyNull (const TopoDS_Shape &shape)
static std::pair< Base::Placement, Base::Matrix4D > sumTransforms (const std::vector< Base::Placement > &plmStack, const std::vector< Base::Matrix4D > &scaleStack)
static App::DocumentObject * getLinkAttachParent (const App::DocumentObject *attachedObject)
static Base::Placement getAttachedPlacement (const App::DocumentObject *cursorObject)
static std::string getFullPath (const App::DocumentObject *object)
static std::vector< App::DocumentObject * > getGeometryRootObjects (const App::Document *doc)
static std::vector< std::list< App::DocumentObject * > > getGeometryPathsFromOutList (const App::DocumentObject *object)
Static Public Member Functions inherited from Measure::SubnameHelper
static std::string getLastTerm (const std::string &inString)
return the last term of a dot separated string - A.B.C returns C
static std::string getFirstTerm (const std::string &inString)
return the first term of a dot separated string - A.B.C returns A
static std::string namesToLongSub (const std::vector< std::string > &pathElementNames)
static std::string pruneLastTerm (const std::string &inString)
return a dot separated string without its last term - A.B.C returns A.B.
static std::string pruneFirstTerm (const std::string &inString)
remove the first term of a dot separated string - A.B.C returns B.C
static std::string removeGeometryTerm (const std::string &longSubname)
static std::string pathToLongSub (std::list< App::DocumentObject * > path)
static std::string removeTnpInfo (const std::string &inString)
Detailed Description
a class to obtain the located shape pointed at by a selection
Definition at line 85 of file ShapeFinder.h.
Member Function Documentation
crawlPlacementChain()
void ShapeFinder::crawlPlacementChain (std::vector< Base::Placement > & plmStack, std::vector< Base::Matrix4D > & scaleStack, const App::DocumentObject & rootObject, const std::string & leafSub) static
traverse the tree from leafSub up to rootObject, obtaining placements along the way. Note that the placements will need to be applied in the reverse order (ie top down) of what is delivered in plm stack. leafSub is a dot separated longSubName which DOES NOT include rootObject. the result does not include rootObject's transform.
Definition at line 147 of file ShapeFinder.cpp.
References getPlacement(), getScale(), Measure::SubnameHelper::pruneLastTerm(), and resolveSelection().
Referenced by getGlobalTransform().
getAttachedPlacement()
static Base::Placement Measure::ShapeFinder::getAttachedPlacement (const App::DocumentObject * cursorObject) static
getFullPath()
static std::string Measure::ShapeFinder::getFullPath (const App::DocumentObject * object) static
getGeometryPathsFromOutList()
static std::vector<std::list<App::DocumentObject*> > Measure::ShapeFinder::getGeometryPathsFromOutList (const App::DocumentObject * object) static
getGeometryRootObjects()
static std::vector<App::DocumentObject*> Measure::ShapeFinder::getGeometryRootObjects (const App::Document * doc) static
getGlobalTransform() [1/2]
std::pair< Base::Placement, Base::Matrix4D > ShapeFinder::getGlobalTransform (const App::DocumentObject & rootObject, const std::string & leafSub) static
Returns the net transformation of a path from rootObject to leafSub. rootObject's transform is included in the result.
Definition at line 300 of file ShapeFinder.cpp.
References crawlPlacementChain(), Measure::SubnameHelper::removeGeometryTerm(), and sumTransforms().
Referenced by getLocatedShape().
getGlobalTransform() [2/2]
std::pair< Base::Placement, Base::Matrix4D > ShapeFinder::getGlobalTransform (const App::DocumentObject * cursorObject) static
trys to get the global position and scale for a object with no information about the path through the tree from a root to cursor object.
Definition at line 327 of file ShapeFinder.cpp.
References getPlacement(), getScale(), and isLinkLike().
getLinkAttachParent()
App::DocumentObject * ShapeFinder::getLinkAttachParent (const App::DocumentObject * attachedObject) static
get the parent to which attachObject is attached via Links (not regular Part::Attacher attachment)
Definition at line 373 of file ShapeFinder.cpp.
References App::ExtensionContainer::getPropertyByName(), and App::PropertyLink::getValue().
getLocatedShape()
TopoDS_Shape ShapeFinder::getLocatedShape (const App::DocumentObject & rootObject, const std::string & leafSub) static
returns the shape of rootObject+leafSub. Any transforms from objects in the path from rootObject to leafSub are applied to the shape. leafSub is typically obtained from Selection as it provides the appropriate longSubname. The leaf sub string can also be constructed by walking the tree.
Definition at line 107 of file ShapeFinder.cpp.
References getGlobalTransform(), Part::Feature::getShape(), Part::TopoShape::getShape(), Part::TopoShape::getSubTopoShape(), isShapeReallyNull(), Measure::SubnameHelper::removeTnpInfo(), resolveSelection(), and transformShape().
Referenced by getLocatedTopoShape(), and Measure::Measurement::getShape().
getLocatedTopoShape()
Part::TopoShape ShapeFinder::getLocatedTopoShape (const App::DocumentObject & rootObject, const std::string & leafSub) static
convenient version of previous method
Definition at line 136 of file ShapeFinder.cpp.
References getLocatedShape().
getPlacement()
Base::Placement ShapeFinder::getPlacement (const App::DocumentObject * root) static
this getter should work for any object, not just links
Definition at line 205 of file ShapeFinder.cpp.
References App::ExtensionContainer::getPropertyByName(), and App::PropertyPlacement::getValue().
Referenced by crawlPlacementChain(), and getGlobalTransform().
getScale()
Base::Matrix4D ShapeFinder::getScale (const App::DocumentObject * root) static
get root's scale property. If root is not a Link related object, then the identity matrrix will be returned.
Definition at line 218 of file ShapeFinder.cpp.
References App::ExtensionContainer::getPropertyByName(), isLinkLike(), and Base::Matrix4D::scale().
Referenced by crawlPlacementChain(), and getGlobalTransform().
isLinkLike()
bool ShapeFinder::isLinkLike (const App::DocumentObject * obj) static
there isn't convenient common ancestor for the members of the Link family. We use isLinkLike(obj) instead of obj->isDerivedFrom<ConvenientCommonAncestor>(). Some links have proxy objects and will not be detected by isDerivedFrom().
Definition at line 237 of file ShapeFinder.cpp.
References App::ExtensionContainer::getPropertyByName(), and Base::BaseClass::isDerivedFrom().
Referenced by getGlobalTransform(), and getScale().
isShapeReallyNull()
bool ShapeFinder::isShapeReallyNull (const TopoDS_Shape & shape) static
check for shape is null or shape has no subshapes(vertex/edge/face/etc) this handles the case of an empty compound which is not IsNull, but has no content.
Definition at line 290 of file ShapeFinder.cpp.
Referenced by getLocatedShape(), and transformShape().
LocationAsString()
std::string ShapeFinder::LocationAsString (const TopLoc_Location & location) static
debug routine. return readable form of TopLoc_Location from OCC
Definition at line 401 of file ShapeFinder.cpp.
References Base::toDegrees(), and Base::Vector3< float_type >::x.
PlacementAsString()
std::string ShapeFinder::PlacementAsString (const Base::Placement & inPlacement) static
debugging routine that returns a string representation of a placement.
Definition at line 386 of file ShapeFinder.cpp.
References Base::Placement::getPosition(), Base::Placement::getRotation(), Base::toDegrees(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
resolveSelection()
ResolveResult ShapeFinder::resolveSelection (const App::DocumentObject & selectObj, const std::string & selectLongSub) static
returns the actual target object and subname pointed to by selectObj and selectLongSub (which is likely a result from getSelection or getSelectionEx)
Definition at line 87 of file ShapeFinder.cpp.
References Measure::SubnameHelper::getLastTerm(), and App::DocumentObject::resolve().
Referenced by crawlPlacementChain(), and getLocatedShape().
stripInfiniteShapes()
TopoDS_Shape ShapeFinder::stripInfiniteShapes (const TopoDS_Shape & inShape) static
Infinite shapes can not be projected, so they need to be removed. inShape is usually a compound. Datum features (Axis, Plane and CS) are examples of infinite shapes.
Definition at line 262 of file ShapeFinder.cpp.
References Path.Post.scripts.opensbp_post::move().
Referenced by transformShape().
sumTransforms()
std::pair< Base::Placement, Base::Matrix4D > ShapeFinder::sumTransforms (const std::vector< Base::Placement > & plmStack, const std::vector< Base::Matrix4D > & scaleStack) static
combine a series of placement & scale transforms. The input stacks are expected in leaf to root order, but the result is in the expected root to leaf order.
Definition at line 352 of file ShapeFinder.cpp.
Referenced by getGlobalTransform().
transformShape()
TopoDS_Shape ShapeFinder::transformShape (TopoDS_Shape & inShape, const Base::Placement & placement, const Base::Matrix4D & scaler) static
return inShape with placement and scaler applied. If inShape contains any infinite subshapes (such as Datum planes), the infinite shapes will not be included in the result.
Definition at line 174 of file ShapeFinder.cpp.
References isShapeReallyNull(), and stripInfiniteShapes().
Referenced by getLocatedShape().
The documentation for this class was generated from the following files:
ShapeFinder.h
ShapeFinder.cpp