FreeCAD: Gui::FreehandSelection Class Reference
Gui::FreehandSelection Class Reference
#include <MouseSelection.h>
Public Member Functions
FreehandSelection ()
~FreehandSelection () override
void setClosed (bool c)
Public Member Functions inherited from Gui::PolyPickerSelection
PolyPickerSelection ()
~PolyPickerSelection () override
void setLineWidth (float l)
void setColor (float r, float g, float b, float a=1.0)
void initialize () override
implement this in derived classes
void terminate (bool abort=false) override
implement this in derived classes
Public Member Functions inherited from Gui::BaseMouseSelection
BaseMouseSelection ()
~BaseMouseSelection () override=default
Public Member Functions inherited from Gui::AbstractMouseSelection
AbstractMouseSelection ()
virtual ~AbstractMouseSelection ()=default
void grabMouseModel (Gui::View3DInventorViewer *)
void releaseMouseModel (bool abort=false)
const std::vector< SbVec2s > & getPositions () const
SelectionRole selectedRole () const
int handleEvent (const SoEvent *const ev, const SbViewportRegion &vp)
Protected Member Functions
int popupMenu () override
int mouseButtonEvent (const SoMouseButtonEvent *const e, const QPoint &pos) override
int locationEvent (const SoLocation2Event *const e, const QPoint &pos) override
Protected Member Functions inherited from Gui::PolyPickerSelection
int keyboardEvent (const SoKeyboardEvent *const e) override
void draw () override
draw the polygon
Protected Member Functions inherited from Gui::AbstractMouseSelection
Additional Inherited Members
Public Types inherited from Gui::AbstractMouseSelection
enum {
Continue =0, Restart =1, Finish =2, Cancel =3,
Ignore =4
}
Protected Attributes inherited from Gui::PolyPickerSelection
Gui::Polyline polyline
bool lastConfirmed
Protected Attributes inherited from Gui::AbstractMouseSelection
Gui::View3DInventorViewer * _pcView3D {nullptr}
QCursor m_cPrevCursor
int m_iXold
int m_iYold
int m_iXnew
int m_iYnew
SelectionRole m_selectedRole
std::vector< SbVec2s > _clPoly
Detailed Description
The freehand selection class
Author
Werner Mayer
Definition at line 183 of file MouseSelection.h.
Constructor & Destructor Documentation
FreehandSelection()
FreehandSelection::FreehandSelection () default
~FreehandSelection()
FreehandSelection::~FreehandSelection () override default
Member Function Documentation
locationEvent()
int FreehandSelection::locationEvent (const SoLocation2Event *const e, const QPoint & pos) override protected virtual
Reimplemented from Gui::PolyPickerSelection.
Definition at line 507 of file MouseSelection.cpp.
References Gui::AbstractMouseSelection::_clPoly, Gui::AbstractMouseSelection::_pcView3D, KDL::abs(), Gui::Polyline::addNode(), Gui::AbstractMouseSelection::Continue, Gui::PolyPickerSelection::draw(), SCL.SimpleDataTypes::e, SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getGLWidget(), Gui::Polyline::isWorking(), Gui::AbstractMouseSelection::m_iXnew, Gui::AbstractMouseSelection::m_iXold, Gui::AbstractMouseSelection::m_iYnew, Gui::AbstractMouseSelection::m_iYold, Gui::PolyPickerSelection::polyline, RobotExample::pos, and Gui::Polyline::setCoords().
mouseButtonEvent()
int FreehandSelection::mouseButtonEvent (const SoMouseButtonEvent *const e, const QPoint & pos) override protected virtual
Reimplemented from Gui::PolyPickerSelection.
Definition at line 437 of file MouseSelection.cpp.
References Gui::AbstractMouseSelection::_pcView3D, Gui::Polyline::addNode(), Gui::AbstractMouseSelection::Cancel, Gui::Polyline::clear(), Gui::AbstractMouseSelection::Continue, SCL.SimpleDataTypes::e, Gui::AbstractMouseSelection::Finish, SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getWidget(), SplineSurface::id, Gui::Polyline::isWorking(), Gui::AbstractMouseSelection::m_cPrevCursor, Gui::AbstractMouseSelection::m_iXnew, Gui::AbstractMouseSelection::m_iXold, Gui::AbstractMouseSelection::m_iYnew, Gui::AbstractMouseSelection::m_iYold, Gui::PolyPickerSelection::polyline, popupMenu(), RobotExample::pos, Gui::AbstractMouseSelection::releaseMouseModel(), Gui::AbstractMouseSelection::Restart, Gui::Polyline::setCoords(), and Gui::Polyline::setWorking().
popupMenu()
int FreehandSelection::popupMenu () override protected virtual
Reimplemented from Gui::PolyPickerSelection.
Definition at line 414 of file MouseSelection.cpp.
References Gui::AbstractMouseSelection::Cancel, Gui::AbstractMouseSelection::Finish, Gui::AbstractMouseSelection::getPositions(), NavigationIndicatorGui::menu, RobotExample::pos, and Gui::AbstractMouseSelection::Restart.
Referenced by mouseButtonEvent().
setClosed()
void FreehandSelection::setClosed (bool c)
Definition at line 408 of file MouseSelection.cpp.
References Gui::PolyPickerSelection::polyline, Gui::Polyline::setClosed(), and Gui::Polyline::setCloseStippled().
Referenced by MeshGui::MeshSelection::prepareFreehandSelection().
The documentation for this class was generated from the following files:
MouseSelection.h
MouseSelection.cpp