FreeCAD: draftutils.params Namespace Reference
draftutils.params Namespace Reference
Classes
class ParamObserverDraft
class ParamObserverView
Functions
def get_param (entry, path="Mod/Draft", ret_default=False)
def get_param_arch (entry, ret_default=False)
def get_param_view (entry, ret_default=False)
def set_param (entry, value, path="Mod/Draft")
def set_param_arch (entry, value)
def set_param_view (entry, value)
Variables
PARAM_DICT
Function Documentation
get_param()
def draftutils.params.get_param (entry, path = "Mod/Draft", ret_default = False)
Return a stored parameter value or its default.
Parameters
----------
entry: str
    Name of the parameter.
path: str, optional
    Defaults to "Mod/Draft".
    The path where the parameter can be found.
    This string is appended to "User parameter:BaseApp/Preferences/".
ret_default: bool, optional
    Defaults to `False`.
    If `True`, always return the default value even if a stored value is available.
Returns
-------
bool, float, int or str (if successful) or `None`.
Definition at line 610 of file params.py.
Referenced by draftutils.params.get_param_arch(), and draftutils.params.get_param_view().
get_param_arch()
def draftutils.params.get_param_arch (entry, ret_default = False)
Definition at line 649 of file params.py.
References draftutils.params.get_param().
Referenced by importers.importSH3DHelper.SH3DImporter.import_sh3d_from_filename().
get_param_view()
def draftutils.params.get_param_view (entry, ret_default = False)
Definition at line 653 of file params.py.
References draftutils.params.get_param().
set_param()
def draftutils.params.set_param (entry, value, path = "Mod/Draft")
Store a parameter value.
Parameters
----------
entry: str
    Name of the parameter.
value: bool, float, int or str
    New value of the correct type.
path: str, optional
    Defaults to "Mod/Draft".
    The path where the parameter can be found.
    This string is appended to "User parameter:BaseApp/Preferences/".
Returns
-------
`True` (if successful) or `False`.
Definition at line 657 of file params.py.
Referenced by draftutils.params.set_param_arch(), and draftutils.params.set_param_view().
set_param_arch()
def draftutils.params.set_param_arch (entry, value)
Definition at line 696 of file params.py.
References draftutils.params.set_param().
set_param_view()
def draftutils.params.set_param_view (entry, value)
Definition at line 700 of file params.py.
References draftutils.params.set_param().
Variable Documentation
PARAM_DICT
draftutils.params.PARAM_DICT
Definition at line 607 of file params.py.