FreeCAD: Robot::Trajectory Class Reference
Robot::Trajectory Class Reference
#include <Trajectory.h>
Public Member Functions
Trajectory ()
Trajectory (const Trajectory &)
~Trajectory () override
Trajectory & operator= (const Trajectory &)
unsigned int getMemSize () const override
void Save (Base::Writer &) const override
void Restore (Base::XMLReader &) override
void generateTrajectory ()
void addWaypoint (const Waypoint &WPnt)
unsigned int getSize () const
const Waypoint & getWaypoint (unsigned int pos) const
std::string getUniqueWaypointName (const char *Name) const
const std::vector< Waypoint * > & getWaypoints () const
void deleteLast (unsigned int n=1)
delete the last n waypoints
double getLength (int n=-1) const
return the Length (mm) of the Trajectory if -1 or of the Waypoint with the given number
double getDuration (int n=-1) const
return the duration (s) of the Trajectory if -1 or of the Waypoint with the given number
Base::Placement getPosition (double time) const
double getVelocity (double time) const
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Attributes
std::vector< Waypoint * > vpcWaypoints
KDL::Trajectory_Composite * pcTrajectory {nullptr}
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
The representation of a Trajectory
Definition at line 45 of file Trajectory.h.
Constructor & Destructor Documentation
Trajectory() [1/2]
Trajectory::Trajectory () default
Trajectory() [2/2]
Trajectory::Trajectory (const Trajectory & Trac)
Definition at line 53 of file Trajectory.cpp.
References operator=().
~Trajectory()
Trajectory::~Trajectory () override
Definition at line 60 of file Trajectory.cpp.
References pcTrajectory, and vpcWaypoints.
Member Function Documentation
addWaypoint()
void Trajectory::addWaypoint (const Waypoint & WPnt)
Definition at line 307 of file Trajectory.cpp.
References getUniqueWaypointName(), Robot::Waypoint::Name, and vpcWaypoints.
Referenced by Robot::Edge2TracObject::execute().
deleteLast()
void Trajectory::deleteLast (unsigned int n = 1)
delete the last n waypoints
Definition at line 141 of file Trajectory.cpp.
References SplineSurface::i, and vpcWaypoints.
generateTrajectory()
void Trajectory::generateTrajectory ()
Definition at line 149 of file Trajectory.cpp.
References SCL.SimpleDataTypes::e, Robot::Waypoint::LINE, pcTrajectory, Robot::Waypoint::PTP, Robot::toFrame(), vpcWaypoints, and Robot::Waypoint::WAIT.
Referenced by operator=(), and Restore().
getDuration()
double Trajectory::getDuration (int n = -1) const
return the duration (s) of the Trajectory if -1 or of the Waypoint with the given number
Definition at line 106 of file Trajectory.cpp.
References pcTrajectory.
Referenced by RobotGui::TaskTrajectory::TaskTrajectory(), and RobotGui::TrajectorySimulate::TrajectorySimulate().
getLength()
double Trajectory::getLength (int n = -1) const
return the Length (mm) of the Trajectory if -1 or of the Waypoint with the given number
Definition at line 91 of file Trajectory.cpp.
References pcTrajectory.
getMemSize()
unsigned int Trajectory::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Implements Base::Persistence.
Definition at line 316 of file Trajectory.cpp.
Referenced by Robot::PropertyTrajectory::getMemSize().
getPosition()
Placement Trajectory::getPosition (double time) const
Definition at line 121 of file Trajectory.cpp.
References pcTrajectory, and Robot::toPlacement().
Referenced by Robot::Simulation::reset(), and Robot::Simulation::setToTime().
getSize()
unsigned int Robot::Trajectory::getSize () const inline
Definition at line 64 of file Trajectory.h.
Referenced by Save(), Robot::Simulation::Simulation(), RobotGui::TaskTrajectory::TaskTrajectory(), RobotGui::TrajectorySimulate::TrajectorySimulate(), and RobotGui::ViewProviderTrajectory::updateData().
getUniqueWaypointName()
std::string Trajectory::getUniqueWaypointName (const char * Name) const
Definition at line 253 of file Trajectory.cpp.
References Path.Post.scripts.refactored_centroid_post::str, and vpcWaypoints.
Referenced by addWaypoint().
getVelocity()
double Trajectory::getVelocity (double time) const
Definition at line 129 of file Trajectory.cpp.
References pcTrajectory, and SurfaceTests.TestBlendCurve::vec.
getWaypoint()
const Waypoint& Robot::Trajectory::getWaypoint (unsigned int pos) const inline
Definition at line 68 of file Trajectory.h.
References RobotExample::pos.
Referenced by RobotGui::TaskTrajectory::TaskTrajectory(), RobotGui::TrajectorySimulate::TrajectorySimulate(), and RobotGui::ViewProviderTrajectory::updateData().
getWaypoints()
const std::vector<Waypoint*>& Robot::Trajectory::getWaypoints () const inline
Definition at line 73 of file Trajectory.h.
Referenced by Robot::TrajectoryCompound::execute(), and Robot::TrajectoryDressUpObject::execute().
operator=()
Trajectory & Trajectory::operator= (const Trajectory & Trac)
Definition at line 68 of file Trajectory.cpp.
References generateTrajectory(), SplineSurface::i, and vpcWaypoints.
Referenced by Trajectory().
Restore()
void Trajectory::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Definition at line 332 of file Trajectory.cpp.
References src.Mod.AddonManager.NetworkManager::count, generateTrajectory(), SplineSurface::i, TechDrawTools.TaskFillTemplateFields::reader, Robot::Waypoint::Restore(), and vpcWaypoints.
Referenced by Robot::PropertyTrajectory::Restore().
Save()
void Trajectory::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Definition at line 321 of file Trajectory.cpp.
References Base::Writer::decInd(), getSize(), SplineSurface::i, Base::Writer::incInd(), Base::Writer::ind(), Base::Writer::Stream(), and vpcWaypoints.
Referenced by Robot::PropertyTrajectory::Save().
Member Data Documentation
pcTrajectory
KDL::Trajectory_Composite* Robot::Trajectory::pcTrajectory {nullptr} protected
Definition at line 91 of file Trajectory.h.
Referenced by generateTrajectory(), getDuration(), getLength(), getPosition(), getVelocity(), and ~Trajectory().
vpcWaypoints
std::vector<Waypoint*> Robot::Trajectory::vpcWaypoints protected
Definition at line 89 of file Trajectory.h.
Referenced by addWaypoint(), deleteLast(), generateTrajectory(), getUniqueWaypointName(), operator=(), Restore(), Save(), and ~Trajectory().
The documentation for this class was generated from the following files:
Trajectory.h
Trajectory.cpp