FreeCAD: ifc4.ifcsolidmodel Class Reference
ifc4.ifcsolidmodel Class Reference
Public Member Functions
def __init__ (self)
def dim ()
Public Member Functions inherited from ifc4.ifcrepresentationitem
def layerassignment ()
def styledbyitem ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Detailed Description
Entity ifcsolidmodel definition.
:param dim
:type dim:ifcdimensioncount
Definition at line 5246 of file ifc4.py.
Constructor & Destructor Documentation
__init__()
def ifc4.ifcsolidmodel.__init__ (self)
Reimplemented from ifc4.ifcgeometricrepresentationitem.
Definition at line 5252 of file ifc4.py.
Member Function Documentation
dim()
def ifc4.ifcsolidmodel.dim ()
Definition at line 5256 of file ifc4.py.
Referenced by ifc4.ifccompositecurvesegment.dim(), ifc4.ifcplacement.dim(), ifc4.ifccartesiantransformationoperator.dim(), ifc4.ifcgeometricset.dim(), ifc4.ifcpointoncurve.dim(), ifc4.ifcpointonsurface.dim(), and ifc4.ifcvector.dim().
The documentation for this class was generated from the following file:
ifc4.py