FreeCAD: Materials Namespace Reference
Materials Namespace Reference
Classes
class DeleteError
class FolderTreeNode
class InvalidIndex
class InvalidMaterialType
class InvalidModel
class LibraryBase
class LibraryNotFound
class Material
class Material2DArray
class Material3DArray
class MaterialConfigLoader
class MaterialEntry
class MaterialExists
class MaterialExternalLibrary
class MaterialFilter
class MaterialFilterOptions
class MaterialFilterTreeWidgetOptions
class MaterialLibrary
class MaterialLoader
class MaterialManager
class MaterialNotFound
class MaterialProperty
class MaterialReadError
class MaterialValue
class MaterialYamlEntry
class Model
class ModelEntry
class ModelLibrary
class ModelLoader
class ModelManager
class ModelNotFound
class ModelProperty
class ModelUUIDs
class Module
class PropertyMaterial
class PropertyNotFound
class Uninitialized
class UnknownValueType
Typedefs
using MaterialTreeNode = FolderTreeNode< Material >
typedef FolderTreeNode< Model > ModelTreeNode
Enumerations
enum ModelFilter { ModelFilter_None, ModelFilter_Physical, ModelFilter_Appearance }
Functions
PyObject * initModule ()
QTextStream & operator<< (QTextStream &output, const MaterialProperty &property)
static void ltrim (std::string &s)
static void rtrim (std::string &s)
static void trim (std::string &s)
static std::string ltrim_copy (std::string s)
static std::string rtrim_copy (std::string s)
static std::string trim_copy (std::string s)
Typedef Documentation
MaterialTreeNode
using Materials::MaterialTreeNode = typedef FolderTreeNode<Material>
Definition at line 503 of file Materials.h.
ModelTreeNode
typedef FolderTreeNode<Model> Materials::ModelTreeNode
Definition at line 341 of file Model.h.
Enumeration Type Documentation
ModelFilter
enum Materials::ModelFilter
Enumerator
ModelFilter_None
ModelFilter_Physical
ModelFilter_Appearance
Definition at line 64 of file Model.h.
Function Documentation
initModule()
PyObject* Materials::initModule ()
Definition at line 77 of file AppMaterial.cpp.
Referenced by PyMOD_INIT_FUNC().
ltrim()
static void Materials::ltrim (std::string & s) inline static
Definition at line 51 of file trim.h.
References rtrim(), and toolbit-attributes::s.
Referenced by rtrim().
ltrim_copy()
static std::string Materials::ltrim_copy (std::string s) inline static
Definition at line 78 of file trim.h.
operator<<()
QTextStream& Materials::operator<< (QTextStream & output, const MaterialProperty & property) inline
Definition at line 497 of file Materials.h.
rtrim()
static void Materials::rtrim (std::string & s) inline static
Definition at line 59 of file trim.h.
References ltrim(), and toolbit-attributes::s.
Referenced by ltrim().
rtrim_copy()
static std::string Materials::rtrim_copy (std::string s) inline static
Definition at line 85 of file trim.h.
trim()
static void Materials::trim (std::string & s) inline static
Definition at line 71 of file trim.h.
References toolbit-attributes::s.
Referenced by Cloud::CloudReader::checkText(), Cloud::CloudWriter::checkText(), PartGui::CircleFromThreePoints::command(), Surface::GeomFillSurface::createBSplineSurface(), Sketcher::SketchObject::fillet(), ParameterGrp::GetGroup(), Gui::ViewProviderFeaturePythonImp::getIcon(), Sketcher::SketchObject::isSupportedGeometry(), Import::Tools::labelName(), App::ExpressionTokenizer::perform(), src.Mod.PartDesign.PartDesignTests.TestTopologicalNamingProblem.TestTopologicalNamingProblem::testRectanglewithArcChangeinGlobalUpperRight(), and Gui::Application::workbenchIcon().
trim_copy()
static std::string Materials::trim_copy (std::string s) inline static
Definition at line 92 of file trim.h.
Referenced by MeshCore::MeshInput::LoadNastran().