FreeCAD: MeshCore::SphereSurfaceFit Class Reference
MeshCore::SphereSurfaceFit Class Reference
#include <Segmentation.h>
Public Member Functions
SphereSurfaceFit ()
SphereSurfaceFit (const Base::Vector3f &c, float r)
~SphereSurfaceFit () override
SphereSurfaceFit (const SphereSurfaceFit &)=delete
SphereSurfaceFit (SphereSurfaceFit &&)=delete
SphereSurfaceFit & operator= (const SphereSurfaceFit &)=delete
SphereSurfaceFit & operator= (SphereSurfaceFit &&)=delete
const char * GetType () const override
void Initialize (const MeshGeomFacet &) override
bool TestTriangle (const MeshGeomFacet &) const override
void AddTriangle (const MeshGeomFacet &) override
bool Done () const override
float Fit () override
float GetDistanceToSurface (const Base::Vector3f &) const override
std::vector< float > Parameters () const override
Public Member Functions inherited from MeshCore::AbstractSurfaceFit
AbstractSurfaceFit ()=default
virtual ~AbstractSurfaceFit ()=default
AbstractSurfaceFit (const AbstractSurfaceFit &)=delete
AbstractSurfaceFit (AbstractSurfaceFit &&)=delete
AbstractSurfaceFit & operator= (const AbstractSurfaceFit &)=delete
AbstractSurfaceFit & operator= (AbstractSurfaceFit &&)=delete
Detailed Description
Definition at line 219 of file Mesh/App/Core/Segmentation.h.
Constructor & Destructor Documentation
SphereSurfaceFit() [1/4]
SphereSurfaceFit::SphereSurfaceFit ()
Definition at line 311 of file Mesh/App/Core/Segmentation.cpp.
References Base::Vector3< float_type >::Set().
SphereSurfaceFit() [2/4]
SphereSurfaceFit::SphereSurfaceFit (const Base::Vector3f & c, float r)
Definition at line 318 of file Mesh/App/Core/Segmentation.cpp.
~SphereSurfaceFit()
SphereSurfaceFit::~SphereSurfaceFit () override
Definition at line 324 of file Mesh/App/Core/Segmentation.cpp.
SphereSurfaceFit() [3/4]
MeshCore::SphereSurfaceFit::SphereSurfaceFit (const SphereSurfaceFit &) delete
SphereSurfaceFit() [4/4]
MeshCore::SphereSurfaceFit::SphereSurfaceFit (SphereSurfaceFit &&) delete
Member Function Documentation
AddTriangle()
void SphereSurfaceFit::AddTriangle (const MeshGeomFacet & tria) override virtual
Implements MeshCore::AbstractSurfaceFit.
Definition at line 339 of file Mesh/App/Core/Segmentation.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, and MeshCore::Approximation::AddPoint().
Done()
bool SphereSurfaceFit::Done () const override virtual
Implements MeshCore::AbstractSurfaceFit.
Definition at line 354 of file Mesh/App/Core/Segmentation.cpp.
References MeshCore::Approximation::Done().
Fit()
float SphereSurfaceFit::Fit () override virtual
Implements MeshCore::AbstractSurfaceFit.
Definition at line 363 of file Mesh/App/Core/Segmentation.cpp.
References MeshCore::SphereFit::Fit(), FLOAT_MAX, MeshCore::SphereFit::GetCenter(), and MeshCore::SphereFit::GetRadius().
GetDistanceToSurface()
float SphereSurfaceFit::GetDistanceToSurface (const Base::Vector3f & pnt) const override virtual
Implements MeshCore::AbstractSurfaceFit.
Definition at line 377 of file Mesh/App/Core/Segmentation.cpp.
References DraftVecUtils::dist(), and Base::Distance().
GetType()
const char* MeshCore::SphereSurfaceFit::GetType () const inline override virtual
Implements MeshCore::AbstractSurfaceFit.
Definition at line 231 of file Mesh/App/Core/Segmentation.h.
Initialize()
void SphereSurfaceFit::Initialize (const MeshGeomFacet & tria) override virtual
Implements MeshCore::AbstractSurfaceFit.
Definition at line 329 of file Mesh/App/Core/Segmentation.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, MeshCore::Approximation::AddPoint(), and MeshCore::Approximation::Clear().
operator=() [1/2]
SphereSurfaceFit& MeshCore::SphereSurfaceFit::operator= (const SphereSurfaceFit &) delete
operator=() [2/2]
SphereSurfaceFit& MeshCore::SphereSurfaceFit::operator= (SphereSurfaceFit &&) delete
Parameters()
std::vector< float > SphereSurfaceFit::Parameters () const override virtual
Implements MeshCore::AbstractSurfaceFit.
Definition at line 383 of file Mesh/App/Core/Segmentation.cpp.
References SCL.SimpleDataTypes::c, MeshCore::SphereFit::GetCenter(), and MeshCore::SphereFit::GetRadius().
TestTriangle()
bool SphereSurfaceFit::TestTriangle (const MeshGeomFacet &) const override virtual
Implements MeshCore::AbstractSurfaceFit.
Definition at line 348 of file Mesh/App/Core/Segmentation.cpp.
The documentation for this class was generated from the following files:
Mesh/App/Core/Segmentation.h
Mesh/App/Core/Segmentation.cpp