FreeCAD: Gui::ViewProviderGeoFeatureGroupExtension Class Reference
Gui::ViewProviderGeoFeatureGroupExtension Class Reference
#include <ViewProviderGeoFeatureGroupExtension.h>
Public Member Functions
ViewProviderGeoFeatureGroupExtension ()
Constructor.
~ViewProviderGeoFeatureGroupExtension () override
std::vector< App::DocumentObject * > extensionClaimChildren3D () const override
std::vector< App::DocumentObject * > extensionClaimChildren () const override
SoSeparator * extensionGetFrontRoot () const override
SoSeparator * extensionGetBackRoot () const override
SoGroup * extensionGetChildRoot () const override
void extensionAttach (App::DocumentObject *pcObject) override
void extensionSetDisplayMode (const char *ModeName) override
std::vector< std::string > extensionGetDisplayModes () const override
void extensionFinishRestoring () override
void extensionShow () override
Show the object in the view: suppresses behavior of DocumentObjectGroup.
void extensionHide () override
Hide the object in the view: suppresses behavior of DocumentObjectGroup.
void extensionUpdateData (const App::Property *) override
Public Member Functions inherited from Gui::ViewProviderGroupExtension
ViewProviderGroupExtension ()
Constructor.
~ViewProviderGroupExtension () override
std::vector< App::DocumentObject * > extensionClaimChildren () const override
bool extensionCanDragObjects () const override
bool extensionCanDragObject (App::DocumentObject *) const override
void extensionDragObject (App::DocumentObject *) override
bool extensionCanDropObjects () const override
bool extensionCanDropObject (App::DocumentObject *) const override
void extensionDropObject (App::DocumentObject *) override
void extensionHide () override
Hides the view provider.
void extensionShow () override
Shows the view provider.
bool extensionOnDelete (const std::vector< std::string > &) override
Public Member Functions inherited from Gui::ViewProviderExtension
ViewProviderExtension ()
~ViewProviderExtension () override
Gui::ViewProviderDocumentObject * getExtendedViewProvider ()
const Gui::ViewProviderDocumentObject * getExtendedViewProvider () const
virtual void extensionBeforeDelete ()
virtual bool extensionCanDragAndDropObject (App::DocumentObject *) const
virtual bool extensionCanDropObjectEx (App::DocumentObject *, App::DocumentObject *, const char *, const std::vector< std::string > &) const
virtual std::string extensionDropObjectEx (App::DocumentObject *obj, App::DocumentObject *, const char *, const std::vector< std::string > &)
virtual int extensionReplaceObject (App::DocumentObject *, App::DocumentObject *)
virtual void extensionModeSwitchChange ()
virtual void extensionReattach (App::DocumentObject *)
virtual void extensionSetupContextMenu (QMenu *, QObject *, const char *)
PyObject * getExtensionPyObject () override
void setIgnoreOverlayIcon (bool on)
bool ignoreOverlayIcon () const
virtual QIcon extensionMergeGreyableOverlayIcons (const QIcon &orig) const
virtual QIcon extensionMergeColorfullOverlayIcons (const QIcon &orig) const
virtual void extensionStartRestoring ()
virtual bool extensionGetElementPicked (const SoPickedPoint *, std::string &) const
virtual bool extensionGetDetailPath (const char *, SoFullPath *, SoDetail *&) const
Public Member Functions inherited from App::Extension
virtual Base::Type getExtensionTypeId (void) const
Extension ()=default
virtual ~Extension ()
virtual void initExtension (App::ExtensionContainer *obj)
App::ExtensionContainer * getExtendedContainer ()
const App::ExtensionContainer * getExtendedContainer () const
std::string name () const
bool isPythonExtension ()
virtual Property * extensionGetPropertyByName (const char *name) const
find a property by its name
virtual const char * extensionGetPropertyName (const Property *prop) const
get the name of a property
virtual void extensionGetPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual void extensionGetPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual short extensionGetPropertyType (const Property *prop) const
get the Type of a Property
virtual short extensionGetPropertyType (const char *name) const
get the Type of a named Property
virtual const char * extensionGetPropertyGroup (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * extensionGetPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual void extensionSave (Base::Writer &) const
virtual void extensionRestore (Base::XMLReader &)
bool extensionIsDerivedFrom (const Base::Type type) const
Protected Attributes
SoSeparator * pcGroupFront
SoSeparator * pcGroupBack
SoGroup * pcGroupChildren
Protected Attributes inherited from App::Extension
bool m_isPythonExtension = false
Py::SmartPtr ExtensionPythonObject
Additional Inherited Members
Static Public Member Functions inherited from App::Extension
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Protected Member Functions inherited from App::Extension
virtual const App::PropertyData & extensionGetPropertyData (void) const
virtual void extensionOnChanged (const Property *p)
virtual bool extensionHandleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
returns true if the property name change was handled by the extension.
virtual bool extensionHandleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop)
returns true if the property type change was handled by the extension.
void initExtensionType (Base::Type type)
Static Protected Member Functions inherited from App::Extension
static const App::PropertyData * extensionGetPropertyDataPtr (void)
static void initExtensionSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Base::Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 56 of file ViewProviderGeoFeatureGroupExtension.h.
Constructor & Destructor Documentation
ViewProviderGeoFeatureGroupExtension()
ViewProviderGeoFeatureGroupExtension::ViewProviderGeoFeatureGroupExtension ()
Constructor.
Definition at line 44 of file ViewProviderGeoFeatureGroupExtension.cpp.
References App::Extension::getExtensionClassTypeId().
~ViewProviderGeoFeatureGroupExtension()
ViewProviderGeoFeatureGroupExtension::~ViewProviderGeoFeatureGroupExtension () override
Definition at line 56 of file ViewProviderGeoFeatureGroupExtension.cpp.
References pcGroupBack, pcGroupChildren, and pcGroupFront.
Member Function Documentation
extensionAttach()
void ViewProviderGeoFeatureGroupExtension::extensionAttach (App::DocumentObject * pcObject) override virtual
Reimplemented from Gui::ViewProviderExtension.
Definition at line 124 of file ViewProviderGeoFeatureGroupExtension.cpp.
References Gui::ViewProvider::addDisplayMaskMode(), Gui::ViewProviderExtension::extensionAttach(), Gui::ViewProviderExtension::getExtendedViewProvider(), and pcGroupChildren.
extensionClaimChildren()
std::vector< App::DocumentObject * > ViewProviderGeoFeatureGroupExtension::extensionClaimChildren () const override virtual
Reimplemented from Gui::ViewProviderExtension.
Reimplemented in Gui::ViewProviderOriginGroupExtension.
Definition at line 79 of file ViewProviderGeoFeatureGroupExtension.cpp.
References Gui::ViewProvider::claimChildren(), App::GeoExcluded, Gui::ViewProviderExtension::getExtendedViewProvider(), App::DocumentObjectExtension::getExtensionClassTypeId(), Gui::ViewProviderDocumentObject::getObject(), Gui::Application::getViewProvider(), toolbit-attributes::group, and Gui::Application::Instance.
Referenced by Gui::ViewProviderOriginGroupExtension::extensionClaimChildren(), and extensionFinishRestoring().
extensionClaimChildren3D()
std::vector< App::DocumentObject * > ViewProviderGeoFeatureGroupExtension::extensionClaimChildren3D () const override virtual
Reimplemented from Gui::ViewProviderExtension.
Reimplemented in Gui::ViewProviderOriginGroupExtension.
Definition at line 67 of file ViewProviderGeoFeatureGroupExtension.cpp.
References create_qrc::ext, Gui::ViewProviderExtension::getExtendedViewProvider(), Gui::ViewProviderDocumentObject::getObject(), and replaceobj::objs.
Referenced by Gui::ViewProviderOriginGroupExtension::extensionClaimChildren3D().
extensionFinishRestoring()
void ViewProviderGeoFeatureGroupExtension::extensionFinishRestoring () override virtual
Reimplemented from Gui::ViewProviderExtension.
Definition at line 117 of file ViewProviderGeoFeatureGroupExtension.cpp.
References extensionClaimChildren(), and Gui::ViewProviderExtension::extensionFinishRestoring().
extensionGetBackRoot()
SoSeparator* Gui::ViewProviderGeoFeatureGroupExtension::extensionGetBackRoot () const inline override virtual
Reimplemented from Gui::ViewProviderExtension.
Definition at line 90 of file ViewProviderGeoFeatureGroupExtension.h.
extensionGetChildRoot()
SoGroup* Gui::ViewProviderGeoFeatureGroupExtension::extensionGetChildRoot () const inline override virtual
Reimplemented from Gui::ViewProviderExtension.
Definition at line 91 of file ViewProviderGeoFeatureGroupExtension.h.
extensionGetDisplayModes()
std::vector< std::string > ViewProviderGeoFeatureGroupExtension::extensionGetDisplayModes () const override virtual
Reimplemented from Gui::ViewProviderExtension.
Definition at line 138 of file ViewProviderGeoFeatureGroupExtension.cpp.
References Gui::ViewProviderExtension::extensionGetDisplayModes().
extensionGetFrontRoot()
SoSeparator* Gui::ViewProviderGeoFeatureGroupExtension::extensionGetFrontRoot () const inline override virtual
Reimplemented from Gui::ViewProviderExtension.
Definition at line 89 of file ViewProviderGeoFeatureGroupExtension.h.
extensionHide()
void Gui::ViewProviderGeoFeatureGroupExtension::extensionHide () inline override virtual
Hide the object in the view: suppresses behavior of DocumentObjectGroup.
Reimplemented from Gui::ViewProviderExtension.
Definition at line 102 of file ViewProviderGeoFeatureGroupExtension.h.
extensionSetDisplayMode()
void ViewProviderGeoFeatureGroupExtension::extensionSetDisplayMode (const char * ModeName) override virtual
Reimplemented from Gui::ViewProviderExtension.
Definition at line 130 of file ViewProviderGeoFeatureGroupExtension.cpp.
References Gui::ViewProviderExtension::extensionSetDisplayMode(), Gui::ViewProviderExtension::getExtendedViewProvider(), and Gui::ViewProvider::setDisplayMaskMode().
extensionShow()
void Gui::ViewProviderGeoFeatureGroupExtension::extensionShow () inline override virtual
Show the object in the view: suppresses behavior of DocumentObjectGroup.
Reimplemented from Gui::ViewProviderExtension.
Definition at line 98 of file ViewProviderGeoFeatureGroupExtension.h.
extensionUpdateData()
void ViewProviderGeoFeatureGroupExtension::extensionUpdateData (const App::Property * prop) override virtual
Reimplemented from Gui::ViewProviderExtension.
Definition at line 149 of file ViewProviderGeoFeatureGroupExtension.cpp.
References Gui::ViewProviderExtension::extensionUpdateData(), Gui::ViewProviderExtension::getExtendedViewProvider(), Gui::ViewProviderDocumentObject::getObject(), toolbit-attributes::grp, and Gui::ViewProvider::setTransformation().
Member Data Documentation
pcGroupBack
SoSeparator* Gui::ViewProviderGeoFeatureGroupExtension::pcGroupBack protected
Definition at line 110 of file ViewProviderGeoFeatureGroupExtension.h.
Referenced by ~ViewProviderGeoFeatureGroupExtension().
pcGroupChildren
SoGroup* Gui::ViewProviderGeoFeatureGroupExtension::pcGroupChildren protected
Definition at line 111 of file ViewProviderGeoFeatureGroupExtension.h.
Referenced by extensionAttach(), and ~ViewProviderGeoFeatureGroupExtension().
pcGroupFront
SoSeparator* Gui::ViewProviderGeoFeatureGroupExtension::pcGroupFront protected
Definition at line 109 of file ViewProviderGeoFeatureGroupExtension.h.
Referenced by ~ViewProviderGeoFeatureGroupExtension().
The documentation for this class was generated from the following files:
ViewProviderGeoFeatureGroupExtension.h
ViewProviderGeoFeatureGroupExtension.cpp