FreeCAD: App::FeaturePythonT< FeatureT > Class Template Reference
App::FeaturePythonT< FeatureT > Class Template Reference
#include <FeaturePython.h>
Public Member Functions
FeaturePythonT ()
~FeaturePythonT () override
methods override DocumentObject
short mustExecute () const override
DocumentObjectExecReturn * execute () override
recalculate the Feature
const char * getViewProviderNameOverride () const override
const char * getViewProviderName () const override
returns the type name of the ViewProvider
App::DocumentObject * getSubObject (const char *subname, PyObject **pyObj, Base::Matrix4D *mat, bool transform, int depth) const override
std::vector< std::string > getSubObjects (int reason=0) const override
App::DocumentObject * getLinkedObject (bool recurse, Base::Matrix4D *mat, bool transform, int depth) const override
bool hasChildElement () const override
return true to activate tree view group object handling
int isElementVisible (const char *element) const override
Get sub-element visibility.
int setElementVisible (const char *element, bool visible) override
Set sub-element visibility.
bool canLinkProperties () const override
bool allowDuplicateLabel () const override
bool redirectSubName (std::ostringstream &ss, App::DocumentObject *topParent, App::DocumentObject *child) const override
int canLoadPartial () const override
void editProperty (const char *propName) override
PyObject * getPyObject () override
void setPyObject (PyObject *obj) override
FeaturePythonT (const FeaturePythonT &)=delete
FeaturePythonT (FeaturePythonT &&)=delete
FeaturePythonT & operator= (const FeaturePythonT &)=delete
FeaturePythonT & operator= (FeaturePythonT &&)=delete
void onBeforeChange (const Property *prop) override
void onBeforeChangeLabel (std::string &newLabel) override
void onChanged (const Property *prop) override
void onDocumentRestored () override
void unsetupObject () override
Detailed Description
template<class FeatureT>
class App::FeaturePythonT< FeatureT >
Generic Python feature class which allows one to behave every DocumentObject derived class as Python feature – simply by subclassing.
Author
Werner Mayer
Definition at line 190 of file FeaturePython.h.
Constructor & Destructor Documentation
FeaturePythonT() [1/3]
template<class FeatureT > App::FeaturePythonT< FeatureT >::FeaturePythonT () inline
Definition at line 195 of file FeaturePython.h.
~FeaturePythonT()
template<class FeatureT > App::FeaturePythonT< FeatureT >::~FeaturePythonT () inline override
Definition at line 201 of file FeaturePython.h.
References App::FeaturePythonImp::execute().
FeaturePythonT() [2/3]
template<class FeatureT > App::FeaturePythonT< FeatureT >::FeaturePythonT (const FeaturePythonT< FeatureT > &) delete
FeaturePythonT() [3/3]
template<class FeatureT > App::FeaturePythonT< FeatureT >::FeaturePythonT (FeaturePythonT< FeatureT > &&) delete
Member Function Documentation
allowDuplicateLabel()
template<class FeatureT > bool App::FeaturePythonT< FeatureT >::allowDuplicateLabel () const inline override
Definition at line 322 of file FeaturePython.h.
canLinkProperties()
template<class FeatureT > bool App::FeaturePythonT< FeatureT >::canLinkProperties () const inline override
Definition at line 310 of file FeaturePython.h.
canLoadPartial()
template<class FeatureT > int App::FeaturePythonT< FeatureT >::canLoadPartial () const inline override
Definition at line 348 of file FeaturePython.h.
editProperty()
template<class FeatureT > void App::FeaturePythonT< FeatureT >::editProperty (const char * propName) inline override
Definition at line 357 of file FeaturePython.h.
execute()
template<class FeatureT > DocumentObjectExecReturn* App::FeaturePythonT< FeatureT >::execute () inline override
recalculate the Feature
Definition at line 220 of file FeaturePython.h.
Referenced by draftobjects.facebinder.Facebinder::addSubobjects(), Path.Dressup.Gui.Dogbone.ObjectDressup::boneStateList(), Path.Dressup.Tags.ObjectTagDressup::generateTags(), ArchRoof._Roof::getSubVolume(), ArchPanel.PanelCut::getWires(), src.Mod.PartDesign.Scripts.Spring.MySpring::onChanged(), src.Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid::onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped::onChanged(), src.Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt::onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder::onChanged(), MeasureCOM.MeasureCOM::onChanged(), Path.Main.Stock.StockFromBase::onChanged(), Path.Main.Stock.StockCreateBox::onChanged(), Path.Main.Stock.StockCreateCylinder::onChanged(), FeaturePython.DistanceBolt::onChanged(), draftobjects.draftlink.DraftLink::onDocumentRestored(), ArchSchedule._ArchSchedule::setSpreadsheetData(), and draftobjects.array.Array::update_properties_0v21().
getLinkedObject()
template<class FeatureT > App::DocumentObject* App::FeaturePythonT< FeatureT >::getLinkedObject (bool recurse, Base::Matrix4D * mat, bool transform, int depth) const inline override
Definition at line 270 of file FeaturePython.h.
getPyObject()
PyObject * App::FeaturePython::getPyObject inline override
Definition at line 364 of file FeaturePython.h.
References App::FeaturePythonImp::onBeforeChange().
getSubObject()
template<class FeatureT > App::DocumentObject* App::FeaturePythonT< FeatureT >::getSubObject (const char * subname, PyObject ** pyObj, Base::Matrix4D * mat, bool transform, int depth) const inline override
Definition at line 247 of file FeaturePython.h.
getSubObjects()
template<class FeatureT > std::vector<std::string> App::FeaturePythonT< FeatureT >::getSubObjects (int reason = 0) const inline override
Definition at line 260 of file FeaturePython.h.
References App::FeaturePythonImp::Accepted, App::FeaturePythonImp::hasChildElement(), and App::FeaturePythonImp::Rejected.
getViewProviderName()
const char * App::PlacementPython::getViewProviderName inline override
returns the type name of the ViewProvider
Definition at line 242 of file FeaturePython.h.
getViewProviderNameOverride()
template<class FeatureT > const char* App::FeaturePythonT< FeatureT >::getViewProviderNameOverride () const inline override
Definition at line 233 of file FeaturePython.h.
hasChildElement()
template<class FeatureT > bool App::FeaturePythonT< FeatureT >::hasChildElement () const inline override
return true to activate tree view group object handling
Definition at line 280 of file FeaturePython.h.
isElementVisible()
template<class FeatureT > int App::FeaturePythonT< FeatureT >::isElementVisible (const char * element) const inline override
Get sub-element visibility.
Definition at line 292 of file FeaturePython.h.
References App::FeaturePythonImp::Accepted, and App::FeaturePythonImp::Rejected.
mustExecute()
template<class FeatureT > short App::FeaturePythonT< FeatureT >::mustExecute () const inline override
Definition at line 208 of file FeaturePython.h.
References SCL.SimpleDataTypes::e.
onBeforeChange()
template<class FeatureT > void App::FeaturePythonT< FeatureT >::onBeforeChange (const Property * prop) inline override protected
Definition at line 383 of file FeaturePython.h.
References App::FeaturePythonImp::onDocumentRestored().
onBeforeChangeLabel()
template<class FeatureT > void App::FeaturePythonT< FeatureT >::onBeforeChangeLabel (std::string & newLabel) inline override protected
Definition at line 388 of file FeaturePython.h.
References App::FeaturePythonImp::unsetupObject().
onChanged()
template<class FeatureT > void App::FeaturePythonT< FeatureT >::onChanged (const Property * prop) inline override protected
Definition at line 394 of file FeaturePython.h.
Referenced by draftviewproviders.view_base.ViewProviderDraft::attach(), ArchSpace._ViewProviderSpace::onChanged(), ArchSchedule._ArchSchedule::setProperties(), draftviewproviders.view_wpproxy.ViewProviderWorkingPlaneProxy::updateData(), draftviewproviders.view_layer.ViewProviderLayer::updateData(), draftviewproviders.view_label.ViewProviderLabel::updateData(), ArchAxis._ViewProviderAxis::updateData(), draftviewproviders.view_dimension.ViewProviderLinearDimension::updateData(), ArchSpace._ViewProviderSpace::updateData(), ArchBuildingPart.ViewProviderBuildingPart::updateData(), ArchPanel.ViewProviderPanelCut::updateData(), ArchSite._ViewProviderSite::updateData(), ArchSectionPlane._ViewProviderSectionPlane::updateData(), and ArchPanel.ViewProviderPanelSheet::updateData().
onDocumentRestored()
template<class FeatureT > void App::FeaturePythonT< FeatureT >::onDocumentRestored () inline override protected
Definition at line 402 of file FeaturePython.h.
Referenced by Path.Base.PropertyBag.PropertyBag::__init__(), and Path.Dressup.DogboneII.Proxy::__init__().
operator=() [1/2]
template<class FeatureT > FeaturePythonT& App::FeaturePythonT< FeatureT >::operator= (const FeaturePythonT< FeatureT > &) delete
operator=() [2/2]
template<class FeatureT > FeaturePythonT& App::FeaturePythonT< FeatureT >::operator= (FeaturePythonT< FeatureT > &&) delete
redirectSubName()
template<class FeatureT > bool App::FeaturePythonT< FeatureT >::redirectSubName (std::ostringstream & ss, App::DocumentObject * topParent, App::DocumentObject * child) const inline override
Definition at line 334 of file FeaturePython.h.
setElementVisible()
template<class FeatureT > int App::FeaturePythonT< FeatureT >::setElementVisible (const char * element, bool visible) inline override
Set sub-element visibility.
Definition at line 301 of file FeaturePython.h.
References App::FeaturePythonImp::Accepted, App::FeaturePythonImp::allowDuplicateLabel(), and App::FeaturePythonImp::Rejected.
setPyObject()
template<class FeatureT > void App::FeaturePythonT< FeatureT >::setPyObject (PyObject * obj) inline override
Definition at line 372 of file FeaturePython.h.
unsetupObject()
template<class FeatureT > void App::FeaturePythonT< FeatureT >::unsetupObject () inline override protected
Definition at line 407 of file FeaturePython.h.
The documentation for this class was generated from the following files:
FeaturePython.h
FeaturePython.cpp
Link.cpp
App/Placement.cpp