FreeCAD: Wm4::Math< Real > Class Template Reference
Wm4::Math< Real > Class Template Reference
#include <Wm4Math.h>
Public Member Functions
const float EPSILON
const float ZERO_TOLERANCE
const float MAX_REAL
const float PI
const float TWO_PI
const float HALF_PI
const float INV_PI
const float INV_TWO_PI
const float DEG_TO_RAD
const float RAD_TO_DEG
const float LN_2
const float LN_10
const float INV_LN_2
const float INV_LN_10
const double EPSILON
const double ZERO_TOLERANCE
const double MAX_REAL
const double PI
const double TWO_PI
const double HALF_PI
const double INV_PI
const double INV_TWO_PI
const double DEG_TO_RAD
const double RAD_TO_DEG
const double LN_2
const double LN_10
const double INV_LN_2
const double INV_LN_10
Static Public Member Functions
static Real ACos (Real fValue)
static Real ASin (Real fValue)
static Real ATan (Real fValue)
static Real ATan2 (Real fY, Real fX)
static Real Ceil (Real fValue)
static Real Cos (Real fValue)
static Real Exp (Real fValue)
static Real FAbs (Real fValue)
static Real Floor (Real fValue)
static Real FMod (Real fX, Real fY)
static Real InvSqrt (Real fValue)
static Real Log (Real fValue)
static Real Log2 (Real fValue)
static Real Log10 (Real fValue)
static Real Pow (Real fBase, Real fExponent)
static Real Sin (Real fValue)
static Real Sqr (Real fValue)
static Real Sqrt (Real fValue)
static Real Tan (Real fValue)
static int Sign (int iValue)
static Real Sign (Real fValue)
static Real UnitRandom (unsigned int uiSeed=0)
static Real SymmetricRandom (unsigned int uiSeed=0)
static Real IntervalRandom (Real fMin, Real fMax, unsigned int uiSeed=0)
static Real FastSin0 (Real fAngle)
static Real FastSin1 (Real fAngle)
static Real FastCos0 (Real fAngle)
static Real FastCos1 (Real fAngle)
static Real FastTan0 (Real fAngle)
static Real FastTan1 (Real fAngle)
static Real FastInvSin0 (Real fValue)
static Real FastInvSin1 (Real fValue)
static Real FastInvCos0 (Real fValue)
static Real FastInvCos1 (Real fValue)
static Real FastInvTan0 (Real fValue)
static Real FastInvTan1 (Real fValue)
static Real FastInvSqrt (Real fValue)
static Real FastNegExp0 (Real fValue)
static Real FastNegExp1 (Real fValue)
static Real FastNegExp2 (Real fValue)
static Real FastNegExp3 (Real fValue)
Static Public Attributes
static const Real EPSILON
static const Real ZERO_TOLERANCE
static const Real MAX_REAL
static const Real PI
static const Real TWO_PI
static const Real HALF_PI
static const Real INV_PI
static const Real INV_TWO_PI
static const Real DEG_TO_RAD
static const Real RAD_TO_DEG
static const Real LN_2
static const Real LN_10
static const Real INV_LN_2
static const Real INV_LN_10
Detailed Description
template<class Real>
class Wm4::Math< Real >
Definition at line 27 of file Wm4Math.h.
Member Function Documentation
ACos()
template<class Real > static Real Wm4::Math< Real >::ACos (Real fValue) static
ASin()
template<class Real > static Real Wm4::Math< Real >::ASin (Real fValue) static
ATan()
template<class Real > static Real Wm4::Math< Real >::ATan (Real fValue) static
ATan2()
template<class Real > static Real Wm4::Math< Real >::ATan2 (Real fY, Real fX) static
Referenced by Wm4::PolynomialRoots< Real >::FindA().
Ceil()
template<class Real > static Real Wm4::Math< Real >::Ceil (Real fValue) static
Cos()
template<class Real > static Real Wm4::Math< Real >::Cos (Real fValue) static
Referenced by Wm4::PolynomialRoots< Real >::FindA(), and Wm4::Quaternion< Real >::Constraints::SetAngles().
DEG_TO_RAD() [1/2]
const float Wm4::Math< float >::DEG_TO_RAD
Definition at line 30 of file Wm4Math.cpp.
DEG_TO_RAD() [2/2]
const double Wm4::Math< double >::DEG_TO_RAD
Definition at line 45 of file Wm4Math.cpp.
EPSILON() [1/2]
const float Wm4::Math< float >::EPSILON
Definition at line 22 of file Wm4Math.cpp.
EPSILON() [2/2]
const double Wm4::Math< double >::EPSILON
Definition at line 37 of file Wm4Math.cpp.
Exp()
template<class Real > static Real Wm4::Math< Real >::Exp (Real fValue) static
FAbs()
template<class Real > static Real Wm4::Math< Real >::FAbs (Real fValue) static
Referenced by Wm4::IntrSegment3Plane3< Real >::Find(), Wm4::DistVector3Plane3< Real >::Get(), Wm4::PolynomialRoots< Real >::GetBound(), Wm4::DistSegment3Segment3< Real >::GetSquared(), Wm4::DistVector3Triangle3< Real >::GetSquared(), Wm4::DistLine3Segment3< Real >::GetSquared(), Wm4::LinearSystem< Real >::Inverse(), Wm4::ImplicitSurface< double >::IsOnSurface(), Wm4::QuadraticFit3(), Wm4::QuadraticSphereFit3(), Wm4::LinearSystem< Real >::Solve(), Wm4::IntrLine3Box3< Real >::Test(), and Wm4::IntrSegment3Box3< Real >::Test().
FastCos0()
template<class Real > static Real Wm4::Math< Real >::FastCos0 (Real fAngle) static
FastCos1()
template<class Real > static Real Wm4::Math< Real >::FastCos1 (Real fAngle) static
FastInvCos0()
template<class Real > static Real Wm4::Math< Real >::FastInvCos0 (Real fValue) static
FastInvCos1()
template<class Real > static Real Wm4::Math< Real >::FastInvCos1 (Real fValue) static
FastInvSin0()
template<class Real > static Real Wm4::Math< Real >::FastInvSin0 (Real fValue) static
FastInvSin1()
template<class Real > static Real Wm4::Math< Real >::FastInvSin1 (Real fValue) static
FastInvSqrt()
template<class Real > static Real Wm4::Math< Real >::FastInvSqrt (Real fValue) static
FastInvTan0()
template<class Real > static Real Wm4::Math< Real >::FastInvTan0 (Real fValue) static
FastInvTan1()
template<class Real > static Real Wm4::Math< Real >::FastInvTan1 (Real fValue) static
FastNegExp0()
template<class Real > static Real Wm4::Math< Real >::FastNegExp0 (Real fValue) static
FastNegExp1()
template<class Real > static Real Wm4::Math< Real >::FastNegExp1 (Real fValue) static
FastNegExp2()
template<class Real > static Real Wm4::Math< Real >::FastNegExp2 (Real fValue) static
FastNegExp3()
template<class Real > static Real Wm4::Math< Real >::FastNegExp3 (Real fValue) static
FastSin0()
template<class Real > static Real Wm4::Math< Real >::FastSin0 (Real fAngle) static
FastSin1()
template<class Real > static Real Wm4::Math< Real >::FastSin1 (Real fAngle) static
FastTan0()
template<class Real > static Real Wm4::Math< Real >::FastTan0 (Real fAngle) static
FastTan1()
template<class Real > static Real Wm4::Math< Real >::FastTan1 (Real fAngle) static
Floor()
template<class Real > static Real Wm4::Math< Real >::Floor (Real fValue) static
FMod()
template<class Real > static Real Wm4::Math< Real >::FMod (Real fX, Real fY) static
HALF_PI() [1/2]
const float Wm4::Math< float >::HALF_PI
Definition at line 27 of file Wm4Math.cpp.
HALF_PI() [2/2]
const double Wm4::Math< double >::HALF_PI
Definition at line 42 of file Wm4Math.cpp.
IntervalRandom()
template<class Real > static Real Wm4::Math< Real >::IntervalRandom (Real fMin, Real fMax, unsigned int uiSeed = 0) static
INV_LN_10() [1/2]
const float Wm4::Math< float >::INV_LN_10
Definition at line 35 of file Wm4Math.cpp.
INV_LN_10() [2/2]
const double Wm4::Math< double >::INV_LN_10
Definition at line 50 of file Wm4Math.cpp.
References SplineSurface::i.
INV_LN_2() [1/2]
const float Wm4::Math< float >::INV_LN_2
Definition at line 34 of file Wm4Math.cpp.
INV_LN_2() [2/2]
const double Wm4::Math< double >::INV_LN_2
Definition at line 49 of file Wm4Math.cpp.
INV_PI() [1/2]
const float Wm4::Math< float >::INV_PI
Definition at line 28 of file Wm4Math.cpp.
INV_PI() [2/2]
const double Wm4::Math< double >::INV_PI
Definition at line 43 of file Wm4Math.cpp.
INV_TWO_PI() [1/2]
const float Wm4::Math< float >::INV_TWO_PI
Definition at line 29 of file Wm4Math.cpp.
INV_TWO_PI() [2/2]
const double Wm4::Math< double >::INV_TWO_PI
Definition at line 44 of file Wm4Math.cpp.
InvSqrt()
template<class Real > static Real Wm4::Math< Real >::InvSqrt (Real fValue) static
Referenced by Wm4::CylinderFit3< Real >::CylinderFit3(), and Wm4::MergeBoxes().
LN_10() [1/2]
const float Wm4::Math< float >::LN_10
Definition at line 33 of file Wm4Math.cpp.
LN_10() [2/2]
const double Wm4::Math< double >::LN_10
Definition at line 48 of file Wm4Math.cpp.
LN_2() [1/2]
const float Wm4::Math< float >::LN_2
Definition at line 32 of file Wm4Math.cpp.
LN_2() [2/2]
const double Wm4::Math< double >::LN_2
Definition at line 47 of file Wm4Math.cpp.
Log()
template<class Real > static Real Wm4::Math< Real >::Log (Real fValue) static
Log10()
template<class Real > static Real Wm4::Math< Real >::Log10 (Real fValue) static
Log2()
template<class Real > static Real Wm4::Math< Real >::Log2 (Real fValue) static
MAX_REAL() [1/2]
const float Wm4::Math< float >::MAX_REAL
Definition at line 24 of file Wm4Math.cpp.
MAX_REAL() [2/2]
const double Wm4::Math< double >::MAX_REAL
Definition at line 39 of file Wm4Math.cpp.
PI() [1/2]
const float Wm4::Math< float >::PI
Definition at line 25 of file Wm4Math.cpp.
PI() [2/2]
const double Wm4::Math< double >::PI
Definition at line 40 of file Wm4Math.cpp.
Pow()
template<class Real > static Real Wm4::Math< Real >::Pow (Real fBase, Real fExponent) static
Referenced by Wm4::PolynomialRoots< Real >::FindA(), and Wm4::PolynomialRoots< Real >::SpecialCubic().
RAD_TO_DEG() [1/2]
const float Wm4::Math< float >::RAD_TO_DEG
Definition at line 31 of file Wm4Math.cpp.
RAD_TO_DEG() [2/2]
const double Wm4::Math< double >::RAD_TO_DEG
Definition at line 46 of file Wm4Math.cpp.
Sign() [1/2]
template<class Real > static int Wm4::Math< Real >::Sign (int iValue) static
Sign() [2/2]
template<class Real > static Real Wm4::Math< Real >::Sign (Real fValue) static
Sin()
template<class Real > static Real Wm4::Math< Real >::Sin (Real fValue) static
Referenced by Wm4::PolynomialRoots< Real >::FindA(), and Wm4::Quaternion< Real >::Constraints::SetAngles().
Sqr()
template<class Real > static Real Wm4::Math< Real >::Sqr (Real fValue) static
Sqrt()
template<class Real > static Real Wm4::Math< Real >::Sqrt (Real fValue) static
Referenced by Wm4::ParametricSurface< Real >::ComputePrincipalCurvatureInfo(), Wm4::ImplicitSurface< double >::ComputePrincipalCurvatureInfo(), Wm4::PolynomialRoots< Real >::FindA(), Wm4::DistSegment3Segment3< Real >::Get(), Wm4::DistVector3Segment3< Real >::Get(), Wm4::DistVector3Triangle3< Real >::Get(), Wm4::DistLine3Segment3< Real >::Get(), Wm4::DistSegment3Triangle3< Real >::Get(), Wm4::DistLine3Triangle3< Real >::Get(), Wm4::MeshCurvature< Real >::MeshCurvature(), Wm4::QuadraticSphereFit3(), Wm4::LinearSystem< Real >::SolveSymmetricCG(), and Wm4::PolynomialRoots< Real >::SpecialCubic().
SymmetricRandom()
template<class Real > static Real Wm4::Math< Real >::SymmetricRandom (unsigned int uiSeed = 0) static
Tan()
template<class Real > static Real Wm4::Math< Real >::Tan (Real fValue) static
TWO_PI() [1/2]
const float Wm4::Math< float >::TWO_PI
Definition at line 26 of file Wm4Math.cpp.
TWO_PI() [2/2]
const double Wm4::Math< double >::TWO_PI
Definition at line 41 of file Wm4Math.cpp.
UnitRandom()
template<class Real > static Real Wm4::Math< Real >::UnitRandom (unsigned int uiSeed = 0) static
ZERO_TOLERANCE() [1/2]
const float Wm4::Math< float >::ZERO_TOLERANCE
Definition at line 23 of file Wm4Math.cpp.
ZERO_TOLERANCE() [2/2]
const double Wm4::Math< double >::ZERO_TOLERANCE
Definition at line 38 of file Wm4Math.cpp.
Member Data Documentation
DEG_TO_RAD
template<class Real > const Real Wm4::Math< Real >::DEG_TO_RAD static
Definition at line 136 of file Wm4Math.h.
EPSILON
template<class Real > const Real Wm4::Math< Real >::EPSILON static
Definition at line 128 of file Wm4Math.h.
HALF_PI
template<class Real > const Real Wm4::Math< Real >::HALF_PI static
Definition at line 133 of file Wm4Math.h.
INV_LN_10
template<class Real > const Real Wm4::Math< Real >::INV_LN_10 static
Definition at line 141 of file Wm4Math.h.
INV_LN_2
template<class Real > const Real Wm4::Math< Real >::INV_LN_2 static
Definition at line 140 of file Wm4Math.h.
INV_PI
template<class Real > const Real Wm4::Math< Real >::INV_PI static
Definition at line 134 of file Wm4Math.h.
INV_TWO_PI
template<class Real > const Real Wm4::Math< Real >::INV_TWO_PI static
Definition at line 135 of file Wm4Math.h.
LN_10
template<class Real > const Real Wm4::Math< Real >::LN_10 static
Definition at line 139 of file Wm4Math.h.
LN_2
template<class Real > const Real Wm4::Math< Real >::LN_2 static
Definition at line 138 of file Wm4Math.h.
MAX_REAL
template<class Real > const Real Wm4::Math< Real >::MAX_REAL static
Definition at line 130 of file Wm4Math.h.
PI
template<class Real > const Real Wm4::Math< Real >::PI static
Definition at line 131 of file Wm4Math.h.
RAD_TO_DEG
template<class Real > const Real Wm4::Math< Real >::RAD_TO_DEG static
Definition at line 137 of file Wm4Math.h.
TWO_PI
template<class Real > const Real Wm4::Math< Real >::TWO_PI static
Definition at line 132 of file Wm4Math.h.
ZERO_TOLERANCE
template<class Real > const Real Wm4::Math< Real >::ZERO_TOLERANCE static
Definition at line 129 of file Wm4Math.h.
The documentation for this class was generated from the following file:
Wm4Math.h