FreeCAD: ifc2x3.ifcboundaryedgecondition Class Reference
ifc2x3.ifcboundaryedgecondition Class Reference
Public Member Functions
def __init__ (self, inherited0__name, linearstiffnessbylengthx, linearstiffnessbylengthy, linearstiffnessbylengthz, rotationalstiffnessbylengthx, rotationalstiffnessbylengthy, rotationalstiffnessbylengthz)
def linearstiffnessbylengthx ()
def linearstiffnessbylengthy ()
def linearstiffnessbylengthz ()
def rotationalstiffnessbylengthx ()
def rotationalstiffnessbylengthy ()
def rotationalstiffnessbylengthz ()
Public Member Functions inherited from ifc2x3.ifcboundarycondition
def __init__ (self, name)
def name ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
linearstiffnessbylengthx
linearstiffnessbylengthy
linearstiffnessbylengthz
rotationalstiffnessbylengthx
rotationalstiffnessbylengthy
rotationalstiffnessbylengthz
Public Attributes inherited from ifc2x3.ifcboundarycondition
name
Detailed Description
Entity ifcboundaryedgecondition definition.
:param linearstiffnessbylengthx
:type linearstiffnessbylengthx:ifcmodulusoflinearsubgradereactionmeasure
:param linearstiffnessbylengthy
:type linearstiffnessbylengthy:ifcmodulusoflinearsubgradereactionmeasure
:param linearstiffnessbylengthz
:type linearstiffnessbylengthz:ifcmodulusoflinearsubgradereactionmeasure
:param rotationalstiffnessbylengthx
:type rotationalstiffnessbylengthx:ifcmodulusofrotationalsubgradereactionmeasure
:param rotationalstiffnessbylengthy
:type rotationalstiffnessbylengthy:ifcmodulusofrotationalsubgradereactionmeasure
:param rotationalstiffnessbylengthz
:type rotationalstiffnessbylengthz:ifcmodulusofrotationalsubgradereactionmeasure
Definition at line 9584 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcboundaryedgecondition.__init__ (self, inherited0__name, linearstiffnessbylengthx, linearstiffnessbylengthy, linearstiffnessbylengthz, rotationalstiffnessbylengthx, rotationalstiffnessbylengthy, rotationalstiffnessbylengthz)
Definition at line 9605 of file ifc2x3.py.
Member Function Documentation
linearstiffnessbylengthx()
def ifc2x3.ifcboundaryedgecondition.linearstiffnessbylengthx ()
Definition at line 9615 of file ifc2x3.py.
References ifc2x3.ifcboundaryedgecondition._linearstiffnessbylengthx, SCL.TypeChecker.check_type(), and ifc2x3.ifcboundaryedgecondition.linearstiffnessbylengthx.
linearstiffnessbylengthy()
def ifc2x3.ifcboundaryedgecondition.linearstiffnessbylengthy ()
Definition at line 9629 of file ifc2x3.py.
References ifc2x3.ifcboundaryedgecondition._linearstiffnessbylengthy, SCL.TypeChecker.check_type(), and ifc2x3.ifcboundaryedgecondition.linearstiffnessbylengthy.
linearstiffnessbylengthz()
def ifc2x3.ifcboundaryedgecondition.linearstiffnessbylengthz ()
Definition at line 9643 of file ifc2x3.py.
References ifc2x3.ifcboundaryedgecondition._linearstiffnessbylengthz, SCL.TypeChecker.check_type(), and ifc2x3.ifcboundaryedgecondition.linearstiffnessbylengthz.
rotationalstiffnessbylengthx()
def ifc2x3.ifcboundaryedgecondition.rotationalstiffnessbylengthx ()
Definition at line 9657 of file ifc2x3.py.
References ifc2x3.ifcboundaryedgecondition._rotationalstiffnessbylengthx, SCL.TypeChecker.check_type(), and ifc2x3.ifcboundaryedgecondition.rotationalstiffnessbylengthx.
rotationalstiffnessbylengthy()
def ifc2x3.ifcboundaryedgecondition.rotationalstiffnessbylengthy ()
Definition at line 9671 of file ifc2x3.py.
References ifc2x3.ifcboundaryedgecondition._rotationalstiffnessbylengthy, SCL.TypeChecker.check_type(), and ifc2x3.ifcboundaryedgecondition.rotationalstiffnessbylengthy.
rotationalstiffnessbylengthz()
def ifc2x3.ifcboundaryedgecondition.rotationalstiffnessbylengthz ()
Definition at line 9685 of file ifc2x3.py.
References ifc2x3.ifcboundaryedgecondition._rotationalstiffnessbylengthz, SCL.TypeChecker.check_type(), and ifc2x3.ifcboundaryedgecondition.rotationalstiffnessbylengthz.
Member Data Documentation
linearstiffnessbylengthx
ifc2x3.ifcboundaryedgecondition.linearstiffnessbylengthx
Definition at line 9607 of file ifc2x3.py.
Referenced by ifc2x3.ifcboundaryedgecondition.linearstiffnessbylengthx().
linearstiffnessbylengthy
ifc2x3.ifcboundaryedgecondition.linearstiffnessbylengthy
Definition at line 9608 of file ifc2x3.py.
Referenced by ifc2x3.ifcboundaryedgecondition.linearstiffnessbylengthy().
linearstiffnessbylengthz
ifc2x3.ifcboundaryedgecondition.linearstiffnessbylengthz
Definition at line 9609 of file ifc2x3.py.
Referenced by ifc2x3.ifcboundaryedgecondition.linearstiffnessbylengthz().
rotationalstiffnessbylengthx
ifc2x3.ifcboundaryedgecondition.rotationalstiffnessbylengthx
Definition at line 9610 of file ifc2x3.py.
Referenced by ifc2x3.ifcboundaryedgecondition.rotationalstiffnessbylengthx().
rotationalstiffnessbylengthy
ifc2x3.ifcboundaryedgecondition.rotationalstiffnessbylengthy
Definition at line 9611 of file ifc2x3.py.
Referenced by ifc2x3.ifcboundaryedgecondition.rotationalstiffnessbylengthy().
rotationalstiffnessbylengthz
ifc2x3.ifcboundaryedgecondition.rotationalstiffnessbylengthz
Definition at line 9612 of file ifc2x3.py.
Referenced by ifc2x3.ifcboundaryedgecondition.rotationalstiffnessbylengthz().
The documentation for this class was generated from the following file:
ifc2x3.py