FreeCAD: SurfaceGui Namespace Reference
SurfaceGui Namespace Reference
Classes
class FillingEdgePanel
class FillingPanel
class FillingVertexPanel
class GeomFillSurface
class Module
class SectionsPanel
class TaskFilling
class TaskGeomFillSurface
class TaskSections
class ViewProviderBlendCurve
class ViewProviderExtend
class ViewProviderFilling
class ViewProviderGeomFillSurface
class ViewProviderSections
class Workbench
Enumerations
enum SelectionMode {
None = 0, InitFace = 1, AppendEdge = 2, RemoveEdge = 3,
AppendEdgeConstraint = 4, RemoveEdgeConstraint = 5, AppendVertexConstraint = 6, RemoveVertexConstraint = 7
}
Functions
PyObject * initModule ()
Enumeration Type Documentation
SelectionMode
enum SurfaceGui::SelectionMode
Enumerator
None
InitFace
AppendEdge
RemoveEdge
AppendEdgeConstraint
RemoveEdgeConstraint
AppendVertexConstraint
RemoveVertexConstraint
Definition at line 49 of file SelectionMode.h.
Function Documentation
initModule()
PyObject* SurfaceGui::initModule ()
Definition at line 58 of file AppSurfaceGui.cpp.
References Base::InterpreterSingleton::addModule(), and Base::Interpreter().
Referenced by PyMOD_INIT_FUNC().