FreeCAD: Gui::BitmapFactoryInst Class Reference
Gui::BitmapFactoryInst Class Reference
#include <BitmapFactory.h>
Public Types
enum Position { TopLeft, TopRight, BottomLeft, BottomRight }
Public Member Functions
void addPath (const QString &path)
Adds a path where pixmaps can be found.
void removePath (const QString &path)
Removes a path from the list of pixmap paths.
QStringList getPaths () const
Returns the list of search paths.
QStringList findIconFiles () const
Returns the absolute file names of icons found in the given search paths.
void addPixmapToCache (const char *name, const QPixmap &icon)
Adds a build in XPM pixmap under a given name.
bool findPixmapInCache (const char *name, QPixmap &icon) const
Checks whether the pixmap is already registered.
QIcon iconFromTheme (const char *name, const QIcon &fallback=QIcon())
QIcon iconFromDefaultTheme (const char *name, const QIcon &fallback=QIcon())
QPixmap pixmap (const char *name) const
Retrieves a pixmap by name.
QPixmap pixmapFromSvg (const char *name, const QSizeF &size, const ColorMap &colorMapping=ColorMap()) const
QPixmap pixmapFromSvg (const char *name, const QSizeF &size, qreal dpr, const ColorMap &colorMapping=ColorMap()) const
QPixmap pixmapFromSvg (const QByteArray &contents, const QSizeF &size, const ColorMap &colorMapping=ColorMap()) const
QStringList pixmapNames () const
QPixmap resize (int w, int h, const QPixmap &p, Qt::BGMode bgmode) const
QPixmap fillRect (int x, int y, int w, int h, const QPixmap &p, Qt::BGMode) const
QPixmap merge (const QPixmap &p1, const QPixmap &p2, bool vertical) const
QPixmap merge (const QPixmap &p1, const QPixmap &p2, Position pos=BitmapFactoryInst::BottomLeft) const
QPixmap disabled (const QPixmap &p) const
void convert (const QImage &img, SoSFImage &out) const
void convert (const SoSFImage &img, QImage &out) const
Public Member Functions inherited from Base::Factory
void AddProducer (const char *sClassName, AbstractProducer *pcProducer)
Adds a new prducer instance.
bool CanProduce (const char *sClassName) const
returns true if there is a producer for this class registered
std::list< std::string > CanProduce () const
returns a list of all registered producer
virtual ~Factory ()
destruction
Static Public Member Functions
static BitmapFactoryInst & instance ()
static void destruct ()
static QIcon mergePixmap (const QIcon &base, const QPixmap &px, Gui::BitmapFactoryInst::Position position)
Helper method to merge a pixmap into one corner of a QIcon.
Additional Inherited Members
Protected Member Functions inherited from Base::Factory
void * Produce (const char *sClassName) const
produce a class with the given name
Factory ()=default
construction
Protected Attributes inherited from Base::Factory
std::map< const std::string, AbstractProducer * > _mpcProducers
Detailed Description
Definition at line 46 of file BitmapFactory.h.
Member Enumeration Documentation
Position
enum Gui::BitmapFactoryInst::Position
Enumerator
TopLeft
Place to the top left corner
TopRight
Place to the top right corner
BottomLeft
Place to the bottom left corner
BottomRight
Place to the bottom right corner
Definition at line 49 of file BitmapFactory.h.
Member Function Documentation
addPath()
void BitmapFactoryInst::addPath (const QString & path)
Adds a path where pixmaps can be found.
Definition at line 125 of file BitmapFactory.cpp.
Referenced by instance(), PyMOD_INIT_FUNC(), Gui::ApplicationPy::sAddIconPath(), and Gui::ApplicationPy::sAddResPath().
addPixmapToCache()
void BitmapFactoryInst::addPixmapToCache (const char * name, const QPixmap & icon)
Adds a build in XPM pixmap under a given name.
Definition at line 166 of file BitmapFactory.cpp.
References Gui::BitmapFactoryInstP::xpmCache.
Referenced by Gui::ApplicationPy::sAddIcon(), and Gui::Application::workbenchIcon().
convert() [1/2]
void BitmapFactoryInst::convert (const QImage & img, SoSFImage & out) const
Converts a QImage into a SoSFImage to use it inside a SoImage node.
Definition at line 527 of file BitmapFactory.cpp.
References buildPsets::p, MovieTool::x, and MovieTool::y.
Referenced by Gui::ViewProviderAnnotationLabel::drawImage(), femsolver.elmer.writer.Writer::getDensity(), femsolver.elmer.writer.Writer::getFromUi(), Gui::ViewProviderTextureExtension::setCoinAppearance(), MatGui::AppearancePreview::setTexture(), Gui::AlignmentView::setupHeadUpDisplay(), and Gui::SoFCOffscreenRenderer::writeToImage().
convert() [2/2]
void BitmapFactoryInst::convert (const SoSFImage & img, QImage & out) const
Converts a SoSFImage into a QImage.
Definition at line 627 of file BitmapFactory.cpp.
References buildPsets::p, MovieTool::x, and MovieTool::y.
Referenced by femsolver.elmer.writer.Writer::getDensity(), and femsolver.elmer.writer.Writer::getFromUi().
destruct()
void BitmapFactoryInst::destruct () static
Definition at line 87 of file BitmapFactory.cpp.
Referenced by Gui::Application::~Application().
disabled()
QPixmap BitmapFactoryInst::disabled (const QPixmap & p) const
Creates a disabled pixmap of the given pixmap p by changing the brightness of all opaque pixels to a higher value.
Definition at line 520 of file BitmapFactory.cpp.
References buildPsets::p.
fillRect()
QPixmap BitmapFactoryInst::fillRect (int x, int y, int w, int h, const QPixmap & p, Qt::BGMode bgmode) const
Creates an opaque or transparent area in a pixmap If the background mode is opaque then this method can be used for drawing a smaller pixmap into pixmap p. Note: To draw a smaller pixmap into another one the area in the resulting pixmap for the small pixmapmust be opaque in every pixel, otherwise the drawing may fail.
If the background mode is transparent then this method can be used for resizing the pixmap p and make the new space transparent.
Definition at line 423 of file BitmapFactory.cpp.
References SCL.SimpleDataTypes::b, buildPsets::p, src.Mod.PartDesign.fcgear.svggear::w, MovieTool::x, and MovieTool::y.
Referenced by merge(), and resize().
findIconFiles()
QStringList BitmapFactoryInst::findIconFiles () const
Returns the absolute file names of icons found in the given search paths.
Definition at line 145 of file BitmapFactory.cpp.
References Path.Preferences::searchPaths().
Referenced by Gui::Dialog::IconDialog::IconDialog(), and Gui::SplashScreen::splashImage().
findPixmapInCache()
bool BitmapFactoryInst::findPixmapInCache (const char * name, QPixmap & icon) const
Checks whether the pixmap is already registered.
Definition at line 171 of file BitmapFactory.cpp.
References Gui::BitmapFactoryInstP::xpmCache.
getPaths()
QStringList BitmapFactoryInst::getPaths () const
Returns the list of search paths.
Definition at line 140 of file BitmapFactory.cpp.
References Path.Preferences::searchPaths().
iconFromDefaultTheme()
QIcon Gui::BitmapFactoryInst::iconFromDefaultTheme (const char * name, const QIcon & fallback = QIcon())
Returns the QIcon corresponding to name in the default (FreeCAD's) icon theme. If no such icon is found in the current theme fallback is returned instead.
Definition at line 219 of file BitmapFactory.cpp.
Referenced by iconFromTheme().
iconFromTheme()
QIcon BitmapFactoryInst::iconFromTheme (const char * name, const QIcon & fallback = QIcon())
Returns the QIcon corresponding to name in the current icon theme. If no such icon is found in the current theme fallback is returned instead.
Definition at line 181 of file BitmapFactory.cpp.
References iconFromDefaultTheme(), pixmap(), and Gui::BitmapFactoryInstP::useIconTheme.
Referenced by PartGui::ViewProviderMultiFuse::getIcon(), PartGui::ViewProviderBoolean::getIcon(), PartGui::ViewProviderMultiCommon::getIcon(), Gui::PythonGroupCommand::languageChange(), and Gui::GroupCommand::setup().
instance()
BitmapFactoryInst & BitmapFactoryInst::instance () static
Definition at line 63 of file BitmapFactory.cpp.
References addPath(), App::Application::Config(), App::GetApplication(), App::Application::getHomePath(), App::Application::getUserAppDataDir(), and Path.Post.scripts.rml_post::home().
Referenced by Gui::BitmapFactory().
merge() [1/2]
QPixmap BitmapFactoryInst::merge (const QPixmap & p1, const QPixmap & p2, bool vertical) const
Merges the two pixmaps p1 and p2 to one pixmap in vertical order if vertical is true, in horizontal order otherwise. The method resizes the resulting pixmap.
Definition at line 445 of file BitmapFactory.cpp.
References MovieTool::x, and MovieTool::y.
Referenced by mergePixmap(), Gui::Thumbnail::SaveDocFile(), Gui::CallTipsList::showTips(), and Gui::DocumentObjectItem::testStatus().
merge() [2/2]
QPixmap BitmapFactoryInst::merge (const QPixmap & p1, const QPixmap & p2, Position pos = BitmapFactoryInst::BottomLeft) const
Merges the two pixmaps p1 and p2 to one pixmap. The position of the smaller pixmap p2 is drawn into the given position pos of the bigger pixmap p1. This method does not resize the resulting pixmap.
Definition at line 484 of file BitmapFactory.cpp.
References BottomLeft, BottomRight, fillRect(), buildPsets::p, RobotExample::pos, TopLeft, TopRight, MovieTool::x, and MovieTool::y.
mergePixmap()
QIcon BitmapFactoryInst::mergePixmap (const QIcon & base, const QPixmap & px, Gui::BitmapFactoryInst::Position position) static
Helper method to merge a pixmap into one corner of a QIcon.
Definition at line 669 of file BitmapFactory.cpp.
References Gui::BitmapFactory(), merge(), geoff_geometry::Normal(), geoff_geometry::On(), and src.Mod.PartDesign.fcgear.svggear::w.
Referenced by PartGui::ViewProviderAttachExtension::extensionMergeColorfullOverlayIcons(), Gui::ViewProviderSuppressibleExtension::extensionMergeColorfullOverlayIcons(), PartDesignGui::ViewProvider::mergeColorfulOverlayIcons(), and SketcherGui::ViewProviderSketch::mergeColorfulOverlayIcons().
pixmap()
QPixmap BitmapFactoryInst::pixmap (const char * name) const
Retrieves a pixmap by name.
Definition at line 234 of file BitmapFactory.cpp.
References Gui::BitmapFactory(), Base::Console(), pixmapFromSvg(), Base::ConsoleSingleton::Warning(), and Gui::BitmapFactoryInstP::xpmCache.
Referenced by Gui::Dialog::AboutDialog::aboutImage(), StdViewScreenShot::activated(), Gui::ElementColors::Private::addItem(), SurfaceGui::GeomFillSurface::flipOrientation(), SurfaceGui::ViewProviderGeomFillSurface::getIcon(), SurfaceGui::ViewProviderSections::getIcon(), SurfaceGui::ViewProviderFilling::getIcon(), MeasureGui::ViewProviderMeasureGroup::getIcon(), PathGui::ViewProviderPath::getIcon(), SurfaceGui::ViewProviderExtend::getIcon(), PathGui::ViewProviderPathCompound::getIcon(), AssemblyGui::ViewProviderSimulationGroup::getIcon(), AssemblyGui::ViewProviderViewGroup::getIcon(), AssemblyGui::ViewProviderBom::getIcon(), AssemblyGui::ViewProviderBomGroup::getIcon(), AssemblyGui::ViewProviderJointGroup::getIcon(), PartGui::ViewProviderSpline::getIcon(), AssemblyGui::ViewProviderAssemblyLink::getIcon(), PathGui::ViewProviderPathShape::getIcon(), MeshGui::ViewProviderMeshCurvature::getIcon(), AssemblyGui::ViewProviderAssembly::getIcon(), MeshGui::ViewProviderExport::getIcon(), MeshGui::ViewProviderMesh::getIcon(), Gui::ViewProviderLink::getIcon(), iconFromTheme(), Gui::Dialog::DlgCustomActionsImp::onActionListWidgetItemActivated(), Gui::Dialog::DlgCustomActionsImp::onButtonReplaceActionClicked(), Gui::OverlayTabWidget::refreshIcons(), Gui::Thumbnail::SaveDocFile(), SurfaceGui::GeomFillSurface::setEditedObject(), Gui::ApplicationPy::sGetIcon(), Gui::CallTipsList::showTips(), Gui::SplashScreen::splashImage(), Gui::OverlayTabWidget::syncAutoMode(), Gui::TaskView::TaskWatcherPython::TaskWatcherPython(), Gui::DocumentObjectItem::testStatus(), and Gui::Application::workbenchIcon().
pixmapFromSvg() [1/3]
QPixmap BitmapFactoryInst::pixmapFromSvg (const char * name, const QSizeF & size, const ColorMap & colorMapping = ColorMap()) const
Retrieves a pixmap by name and size created by an scalable vector graphics (SVG).
Parameters
colorMapping - a dictionary of substitute colors. Can be used to customize icon color scheme, e.g. crosshair color
Definition at line 277 of file BitmapFactory.cpp.
References DrawingExample::file.
Referenced by DrawSketchHandlerDimension::activated(), Gui::ExpressionWidget::getIcon(), ExpressionDelegate::getIcon(), Gui::ViewProviderLink::getOverlayPixmap(), TDHandlerDimension::icon(), pixmap(), pixmapFromSvg(), TechDrawGui::QGVPage::prepareCursorPixmap(), SketcherGui::DrawSketchHandler::suggestedConstraintsPixmaps(), and Gui::DocumentObjectItem::testStatus().
pixmapFromSvg() [2/3]
QPixmap BitmapFactoryInst::pixmapFromSvg (const char * name, const QSizeF & size, qreal dpr, const ColorMap & colorMapping = ColorMap()) const
Retrieves a pixmap by name and size created by an scalable vector graphics (SVG) and a device pixel ratio
Parameters
colorMapping - a dictionary of substitute colors. Can be used to customize icon color scheme, e.g. crosshair color
Definition at line 314 of file BitmapFactory.cpp.
References pixmapFromSvg().
pixmapFromSvg() [3/3]
QPixmap BitmapFactoryInst::pixmapFromSvg (const QByteArray & contents, const QSizeF & size, const ColorMap & colorMapping = ColorMap()) const
This method is provided for convenience and does the same as the method above except that it creates the pixmap from a byte array.
Parameters
colorMapping - see above.
Definition at line 324 of file BitmapFactory.cpp.
References Base::ConsoleSingleton::MsgType_Wrn, and buildPsets::p.
pixmapNames()
QStringList BitmapFactoryInst::pixmapNames () const
Returns the names of all registered pixmaps. To get the appropriate pixmaps call pixmap() for each name.
Definition at line 353 of file BitmapFactory.cpp.
References femtools.tokrules::names, and Gui::BitmapFactoryInstP::xpmCache.
removePath()
void BitmapFactoryInst::removePath (const QString & path)
Removes a path from the list of pixmap paths.
Definition at line 130 of file BitmapFactory.cpp.
References RobotExample::pos, and Path.Preferences::searchPaths().
resize()
QPixmap BitmapFactoryInst::resize (int w, int h, const QPixmap & p, Qt::BGMode bgmode) const
Resizes the area of a pixmap If the new size is greater than the old one the pixmap will be placed in the center. The border area will be made depending on bgmode transparent or opaque.
Definition at line 364 of file BitmapFactory.cpp.
References fillRect(), buildPsets::p, src.Mod.PartDesign.fcgear.svggear::w, MovieTool::x, and MovieTool::y.
Referenced by femsolver.reportdialog.ReportDialog::__init__().
The documentation for this class was generated from the following files:
BitmapFactory.h
BitmapFactory.cpp