FreeCAD: MatGui::MaterialTreeWidget Class Reference
MatGui::MaterialTreeWidget Class Reference
#include <MaterialTreeWidget.h>
Signals
void materialSelected (const std::shared_ptr< Materials::Material > &material)
void onMaterial (const QString &uuid)
void onExpanded (bool expanded)
Public Member Functions
MaterialTreeWidget (const std::shared_ptr< Materials::MaterialFilter > &filter, QWidget *parent=nullptr)
MaterialTreeWidget (const std::shared_ptr< std::list< std::shared_ptr< Materials::MaterialFilter >>> &filterList, QWidget *parent=nullptr)
MaterialTreeWidget (QWidget *parent=nullptr)
~MaterialTreeWidget () override
void setMaterial (const QString &uuid)
QString getMaterialUUID () const
void setFilter (const std::shared_ptr< Materials::MaterialFilter > &filter)
void setFilter (const std::shared_ptr< std::list< std::shared_ptr< Materials::MaterialFilter >>> &filterList)
void setActiveFilter (const QString &name)
void setExpanded (bool open)
bool getExpanded ()
bool includeFavorites () const
void setIncludeFavorites (bool value)
bool includeRecent () const
void setIncludeRecent (bool value)
bool includeEmptyFolders () const
void setIncludeEmptyFolders (bool value)
bool includeEmptyLibraries () const
void setIncludeEmptyLibraries (bool value)
bool includeLegacy () const
void setIncludeLegacy (bool legacy)
QSize sizeHint () const override
QSize treeSizeHint () const
void setTreeSizeHint (const QSize &hint)
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Member Functions
Materials::MaterialManager & getMaterialManager ()
void getFavorites ()
void getRecents ()
void saveRecents ()
void addRecent (const QString &uuid)
bool isRecent (const QString &uuid) const
void saveWidgetSettings ()
void saveMaterialTreeChildren (const Base::Reference< ParameterGrp > &param, QTreeView *tree, QStandardItemModel *model, QStandardItem *item)
void saveMaterialTree ()
void createLayout ()
bool findInTree (const QStandardItem &node, QModelIndex *index, const QString &uuid)
QModelIndex findInTree (const QString &uuid)
void updateMaterial (const QString &uuid)
void createMaterialTree ()
void fillMaterialTree ()
void updateMaterialTree ()
void addExpanded (QStandardItem *parent, QStandardItem *child)
void addExpanded (QStandardItem *parent, QStandardItem *child, const Base::Reference< ParameterGrp > &param)
void addExpanded (QStandardItemModel *model, QStandardItem *child)
void addExpanded (QStandardItemModel *model, QStandardItem *child, const Base::Reference< ParameterGrp > &param)
void addRecents (QStandardItem *parent)
void addFavorites (QStandardItem *parent)
void addMaterials (QStandardItem &parent, const std::shared_ptr< std::map< QString, std::shared_ptr< Materials::MaterialTreeNode >>> &modelTree, const QIcon &folderIcon, const QIcon &icon, const Base::Reference< ParameterGrp > &param)
void setFilterVisible (bool open)
void fillFilterCombo ()
bool hasMultipleFilters () const
Properties
QSize treeSizeHint
Friends
class Gui::WidgetFactoryInst
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
The Material Tree widget class This widget is intended for use wherever materials are used. It is a light weight alternative to the full Materials editor.
The widget itself is the combination of a number of smaller widgets. A simple text field shows any currently selected material. An arrow will expand a tree to show the widget library, allowing the user to select the material they require.
When expanded, the user will be presented the option to launch the full material editor. This will allow them to create/copy/modify as required.
Additionally, they will be given the option to create a material card based on the current settings.
Author
David Carter
Definition at line 90 of file MaterialTreeWidget.h.
Constructor & Destructor Documentation
MaterialTreeWidget() [1/3]
MaterialTreeWidget::MaterialTreeWidget (const std::shared_ptr< Materials::MaterialFilter > & filter, QWidget * parent = nullptr) explicit
Constructs a Material tree widget.
Definition at line 58 of file MaterialTreeWidget.cpp.
References importers.exportIFCStructuralTools::setup().
MaterialTreeWidget() [2/3]
MaterialTreeWidget::MaterialTreeWidget (const std::shared_ptr< std::list< std::shared_ptr< Materials::MaterialFilter >>> & filterList, QWidget * parent = nullptr) explicit
Definition at line 69 of file MaterialTreeWidget.cpp.
MaterialTreeWidget() [3/3]
MaterialTreeWidget::MaterialTreeWidget (QWidget * parent = nullptr) explicit
Definition at line 82 of file MaterialTreeWidget.cpp.
~MaterialTreeWidget()
MaterialTreeWidget::~MaterialTreeWidget () override
Destroys the widget and detaches it from its parameter group.
Definition at line 104 of file MaterialTreeWidget.cpp.
References addRecent(), saveMaterialTree(), and saveWidgetSettings().
Member Function Documentation
addExpanded() [1/4]
void MaterialTreeWidget::addExpanded (QStandardItem * parent, QStandardItem * child) protected
Definition at line 580 of file MaterialTreeWidget.cpp.
References Init::parent.
Referenced by addFavorites(), addMaterials(), addRecents(), and fillMaterialTree().
addExpanded() [2/4]
void MaterialTreeWidget::addExpanded (QStandardItem * parent, QStandardItem * child, const Base::Reference< ParameterGrp > & param) protected
Definition at line 586 of file MaterialTreeWidget.cpp.
References Init::param, and Init::parent.
addExpanded() [3/4]
void MaterialTreeWidget::addExpanded (QStandardItemModel * model, QStandardItem * child) protected
Definition at line 597 of file MaterialTreeWidget.cpp.
addExpanded() [4/4]
void MaterialTreeWidget::addExpanded (QStandardItemModel * model, QStandardItem * child, const Base::Reference< ParameterGrp > & param) protected
Definition at line 603 of file MaterialTreeWidget.cpp.
References Init::param.
addFavorites()
void MaterialTreeWidget::addFavorites (QStandardItem * parent) protected
Definition at line 632 of file MaterialTreeWidget.cpp.
References addExpanded(), Materials::MaterialManager::getMaterial(), getMaterialManager(), and Init::parent.
Referenced by fillMaterialTree().
addMaterials()
void MaterialTreeWidget::addMaterials (QStandardItem & parent, const std::shared_ptr< std::map< QString, std::shared_ptr< Materials::MaterialTreeNode >>> & modelTree, const QIcon & folderIcon, const QIcon & icon, const Base::Reference< ParameterGrp > & param) protected
Definition at line 649 of file MaterialTreeWidget.cpp.
References addExpanded(), Materials::FolderTreeNode< T >::DataNode, Init::param, and Init::parent.
Referenced by fillMaterialTree().
addRecent()
void MaterialTreeWidget::addRecent (const QString & uuid) protected
Definition at line 483 of file MaterialTreeWidget.cpp.
References Materials::MaterialManager::getMaterial(), isRecent(), and saveRecents().
Referenced by ~MaterialTreeWidget().
addRecents()
void MaterialTreeWidget::addRecents (QStandardItem * parent) protected
Definition at line 614 of file MaterialTreeWidget.cpp.
References addExpanded(), Materials::MaterialManager::getMaterial(), getMaterialManager(), and Init::parent.
Referenced by fillMaterialTree().
createLayout()
void MaterialTreeWidget::createLayout () protected
Create the widgets UI objects
Definition at line 135 of file MaterialTreeWidget.cpp.
References draftgeoutils.intersections::connect(), fillFilterCombo(), App::GetApplication(), App::Application::GetParameterGroupByPath(), hasMultipleFilters(), Init::param, and setExpanded().
createMaterialTree()
void MaterialTreeWidget::createMaterialTree () protected
Definition at line 520 of file MaterialTreeWidget.cpp.
References draftgeoutils.intersections::connect(), and fillMaterialTree().
fillFilterCombo()
void MaterialTreeWidget::fillFilterCombo () protected
Definition at line 223 of file MaterialTreeWidget.cpp.
References hasMultipleFilters().
Referenced by createLayout(), and setFilter().
fillMaterialTree()
void MaterialTreeWidget::fillMaterialTree () protected
Definition at line 537 of file MaterialTreeWidget.cpp.
References addExpanded(), addFavorites(), addMaterials(), addRecents(), App::GetApplication(), Materials::MaterialManager::getMaterialLibraries(), Materials::MaterialManager::getMaterialTree(), App::Application::GetParameterGroupByPath(), Materials::MaterialFilterOptions::includeEmptyLibraries(), Materials::MaterialFilterOptions::includeFavorites(), Materials::MaterialFilterOptions::includeRecent(), and Init::param.
Referenced by createMaterialTree(), and updateMaterialTree().
findInTree() [1/2]
bool MaterialTreeWidget::findInTree (const QStandardItem & node, QModelIndex * index, const QString & uuid) protected
Definition at line 284 of file MaterialTreeWidget.cpp.
References SplineSurface::i.
Referenced by findInTree(), and setMaterial().
findInTree() [2/2]
QModelIndex MaterialTreeWidget::findInTree (const QString & uuid) protected
Definition at line 306 of file MaterialTreeWidget.cpp.
References findInTree(), and SplineSurface::i.
getExpanded()
bool MatGui::MaterialTreeWidget::getExpanded () inline
Definition at line 121 of file MaterialTreeWidget.h.
getFavorites()
void MaterialTreeWidget::getFavorites () protected
Definition at line 420 of file MaterialTreeWidget.cpp.
References src.Mod.AddonManager.NetworkManager::count, App::GetApplication(), App::Application::GetParameterGroupByPath(), SplineSurface::i, and Init::param.
Referenced by updateMaterialTree().
getMaterialManager()
Materials::MaterialManager& MatGui::MaterialTreeWidget::getMaterialManager () inline protected
Definition at line 237 of file MaterialTreeWidget.h.
Referenced by addFavorites(), addRecents(), and updateMaterial().
getMaterialUUID()
QString MaterialTreeWidget::getMaterialUUID () const
get the material UUID
Definition at line 347 of file MaterialTreeWidget.cpp.
Referenced by MatGui::PrefMaterialTreeWidget::savePreferences().
getRecents()
void MaterialTreeWidget::getRecents () protected
Definition at line 436 of file MaterialTreeWidget.cpp.
References src.Mod.AddonManager.NetworkManager::count, App::GetApplication(), App::Application::GetParameterGroupByPath(), SplineSurface::i, and Init::param.
Referenced by updateMaterialTree().
hasMultipleFilters()
bool MatGui::MaterialTreeWidget::hasMultipleFilters () const inline protected
Definition at line 284 of file MaterialTreeWidget.h.
Referenced by createLayout(), fillFilterCombo(), setFilter(), and setFilterVisible().
includeEmptyFolders()
bool MatGui::MaterialTreeWidget::includeEmptyFolders () const inline
Definition at line 150 of file MaterialTreeWidget.h.
includeEmptyLibraries()
bool MatGui::MaterialTreeWidget::includeEmptyLibraries () const inline
Definition at line 161 of file MaterialTreeWidget.h.
includeFavorites()
bool MatGui::MaterialTreeWidget::includeFavorites () const inline
Definition at line 128 of file MaterialTreeWidget.h.
includeLegacy()
bool MatGui::MaterialTreeWidget::includeLegacy () const inline
Definition at line 173 of file MaterialTreeWidget.h.
includeRecent()
bool MatGui::MaterialTreeWidget::includeRecent () const inline
Definition at line 139 of file MaterialTreeWidget.h.
isRecent()
bool MaterialTreeWidget::isRecent (const QString & uuid) const protected
Definition at line 510 of file MaterialTreeWidget.cpp.
Referenced by addRecent().
materialSelected
void MatGui::MaterialTreeWidget::materialSelected (const std::shared_ptr< Materials::Material > & material) signal
Emits this signal when a material has been selected
onExpanded
void MatGui::MaterialTreeWidget::onExpanded (bool expanded) signal
Referenced by setExpanded().
onMaterial
void MatGui::MaterialTreeWidget::onMaterial (const QString & uuid) signal
saveMaterialTree()
void MaterialTreeWidget::saveMaterialTree () protected
Definition at line 735 of file MaterialTreeWidget.cpp.
References App::GetApplication(), App::Application::GetParameterGroupByPath(), SplineSurface::i, Init::param, and saveMaterialTreeChildren().
Referenced by setActiveFilter(), and ~MaterialTreeWidget().
saveMaterialTreeChildren()
void MaterialTreeWidget::saveMaterialTreeChildren (const Base::Reference< ParameterGrp > & param, QTreeView * tree, QStandardItemModel * model, QStandardItem * item) protected
Definition at line 751 of file MaterialTreeWidget.cpp.
References SplineSurface::i, and Init::param.
Referenced by saveMaterialTree().
saveRecents()
void MaterialTreeWidget::saveRecents () protected
Definition at line 453 of file MaterialTreeWidget.cpp.
References src.Mod.AddonManager.NetworkManager::count, App::GetApplication(), App::Application::GetParameterGroupByPath(), SplineSurface::i, and Init::param.
Referenced by addRecent().
saveWidgetSettings()
void MaterialTreeWidget::saveWidgetSettings () protected
Definition at line 728 of file MaterialTreeWidget.cpp.
References App::GetApplication(), App::Application::GetParameterGroupByPath(), and Init::param.
Referenced by ~MaterialTreeWidget().
setActiveFilter()
void MaterialTreeWidget::setActiveFilter (const QString & name)
Definition at line 388 of file MaterialTreeWidget.cpp.
References saveMaterialTree(), and updateMaterialTree().
setExpanded()
void MaterialTreeWidget::setExpanded (bool open)
Definition at line 192 of file MaterialTreeWidget.cpp.
References onExpanded(), AssemblyImport::open(), and setFilterVisible().
Referenced by createLayout().
setFilter() [1/2]
void MaterialTreeWidget::setFilter (const std::shared_ptr< Materials::MaterialFilter > & filter)
Set the material filter
Definition at line 352 of file MaterialTreeWidget.cpp.
References fillFilterCombo(), setFilterVisible(), and updateMaterialTree().
setFilter() [2/2]
void MaterialTreeWidget::setFilter (const std::shared_ptr< std::list< std::shared_ptr< Materials::MaterialFilter >>> & filterList)
Definition at line 369 of file MaterialTreeWidget.cpp.
References fillFilterCombo(), hasMultipleFilters(), setFilterVisible(), and updateMaterialTree().
setFilterVisible()
void MaterialTreeWidget::setFilterVisible (bool open) protected
Definition at line 213 of file MaterialTreeWidget.cpp.
References hasMultipleFilters(), and AssemblyImport::open().
Referenced by setExpanded(), and setFilter().
setIncludeEmptyFolders()
void MatGui::MaterialTreeWidget::setIncludeEmptyFolders (bool value) inline
Definition at line 154 of file MaterialTreeWidget.h.
setIncludeEmptyLibraries()
void MatGui::MaterialTreeWidget::setIncludeEmptyLibraries (bool value) inline
Definition at line 165 of file MaterialTreeWidget.h.
setIncludeFavorites()
void MatGui::MaterialTreeWidget::setIncludeFavorites (bool value) inline
Definition at line 132 of file MaterialTreeWidget.h.
setIncludeLegacy()
void MatGui::MaterialTreeWidget::setIncludeLegacy (bool legacy) inline
Definition at line 177 of file MaterialTreeWidget.h.
setIncludeRecent()
void MatGui::MaterialTreeWidget::setIncludeRecent (bool value) inline
Definition at line 143 of file MaterialTreeWidget.h.
setMaterial()
void MaterialTreeWidget::setMaterial (const QString & uuid)
Set the material by specifying its UUID
Definition at line 325 of file MaterialTreeWidget.cpp.
References findInTree(), and updateMaterial().
Referenced by MatGui::PrefMaterialTreeWidget::restorePreferences().
setTreeSizeHint()
void MaterialTreeWidget::setTreeSizeHint (const QSize & hint)
Definition at line 127 of file MaterialTreeWidget.cpp.
sizeHint()
QSize MaterialTreeWidget::sizeHint () const override
Definition at line 111 of file MaterialTreeWidget.cpp.
treeSizeHint()
QSize MatGui::MaterialTreeWidget::treeSizeHint () const
updateMaterial()
void MaterialTreeWidget::updateMaterial (const QString & uuid) protected
Definition at line 263 of file MaterialTreeWidget.cpp.
References Base::Console(), getMaterialManager(), and Base::ConsoleSingleton::Log().
Referenced by setMaterial().
updateMaterialTree()
void MaterialTreeWidget::updateMaterialTree () protected
Definition at line 407 of file MaterialTreeWidget.cpp.
References fillMaterialTree(), getFavorites(), and getRecents().
Referenced by setActiveFilter(), and setFilter().
Friends And Related Function Documentation
Gui::WidgetFactoryInst
friend class Gui::WidgetFactoryInst friend
Definition at line 232 of file MaterialTreeWidget.h.
Property Documentation
treeSizeHint
QSize MaterialTreeWidget::treeSizeHint read write
Definition at line 94 of file MaterialTreeWidget.h.
The documentation for this class was generated from the following files:
MaterialTreeWidget.h
MaterialTreeWidget.cpp