FreeCAD: NotificationAreaObserver Class Reference
NotificationAreaObserver Class Reference
Public Member Functions
NotificationAreaObserver (NotificationArea *notificationarea)
~NotificationAreaObserver () override
NotificationAreaObserver (const NotificationAreaObserver &)=delete
NotificationAreaObserver (NotificationAreaObserver &&)=delete
NotificationAreaObserver & operator= (const NotificationAreaObserver &)=delete
NotificationAreaObserver & operator= (NotificationAreaObserver &&)=delete
void SendLog (const std::string &notifiername, const std::string &msg, Base::LogStyle level, Base::IntendedRecipient recipient, Base::ContentType content) override
const char * Name () override
Name of the observer.
Public Member Functions inherited from Base::ILogger
ILogger ()=default
ILogger (const ILogger &)=delete
ILogger (ILogger &&)=delete
ILogger & operator= (const ILogger &)=delete
ILogger & operator= (ILogger &&)=delete
virtual ~ILogger ()=0
bool isActive (Base::LogStyle category) const
Additional Inherited Members
Public Attributes inherited from Base::ILogger
bool bErr {true}
bool bMsg {true}
bool bLog {true}
bool bWrn {true}
bool bCritical {true}
bool bNotification {false}
Detailed Description
This class listens to all messages sent via the console interface and feeds the non-intrusive notification system and the notifications widget
Definition at line 224 of file NotificationArea.cpp.
Constructor & Destructor Documentation
NotificationAreaObserver() [1/3]
NotificationAreaObserver::NotificationAreaObserver (NotificationArea * notificationarea)
Definition at line 250 of file NotificationArea.cpp.
References Base::ConsoleSingleton::AttachObserver(), Base::ILogger::bLog, Base::ILogger::bMsg, Base::ILogger::bNotification, and Base::Console().
~NotificationAreaObserver()
NotificationAreaObserver::~NotificationAreaObserver () override
Definition at line 259 of file NotificationArea.cpp.
References Base::Console(), and Base::ConsoleSingleton::DetachObserver().
NotificationAreaObserver() [2/3]
NotificationAreaObserver::NotificationAreaObserver (const NotificationAreaObserver &) delete
NotificationAreaObserver() [3/3]
NotificationAreaObserver::NotificationAreaObserver (NotificationAreaObserver &&) delete
Member Function Documentation
Name()
const char* NotificationAreaObserver::Name () inline override virtual
Name of the observer.
Reimplemented from Base::ILogger.
Definition at line 241 of file NotificationArea.cpp.
operator=() [1/2]
NotificationAreaObserver& NotificationAreaObserver::operator= (const NotificationAreaObserver &) delete
operator=() [2/2]
NotificationAreaObserver& NotificationAreaObserver::operator= (NotificationAreaObserver &&) delete
SendLog()
void NotificationAreaObserver::SendLog (const std::string & notifiername, const std::string & msg, Base::LogStyle level, Base::IntendedRecipient recipient, Base::ContentType content) override virtual
Function that is called by the console interface for this observer with the message information
Implements Base::ILogger.
Definition at line 264 of file NotificationArea.cpp.
References Gui::NotificationArea::areDeveloperErrorsActive(), Gui::NotificationArea::areDeveloperWarningsActive(), Base::Developer, Base::Error, level(), Path.Op.Surface::msg, Gui::NotificationArea::pushNotification(), src.Mod.AddonManager.Addon::translate, Base::Translated, Base::Untranslatable, and Base::Warning.
The documentation for this class was generated from the following file:
NotificationArea.cpp