FreeCAD: Gui::ActiveObjectList Class Reference
Gui::ActiveObjectList Class Reference
#include <ActiveObjectList.h>
Public Member Functions
ActiveObjectList (Document *doc)
template<typename _T >
_T getObject (const char *name, App::DocumentObject **parent=nullptr, std::string *subname=nullptr) const
void setObject (App::DocumentObject *, const char *, const char *subname=nullptr, const Gui::HighlightMode &m=HighlightMode::UserDefined)
bool hasObject (const char *) const
void objectDeleted (const ViewProviderDocumentObject &viewProviderIn)
bool hasObject (App::DocumentObject *obj, const char *, const char *subname=nullptr) const
Detailed Description
List of active or special objects This class holds a list of objects with a special name. Its mainly used to points to something like the active Body or Part in a edit session. The class is used the viewer (editor) of a document.
See also
Gui::MDIViewer
Author
Jürgen Riegel
Definition at line 50 of file ActiveObjectList.h.
Constructor & Destructor Documentation
ActiveObjectList()
Gui::ActiveObjectList::ActiveObjectList (Document * doc) inline explicit
Definition at line 53 of file ActiveObjectList.h.
Member Function Documentation
getObject()
template<typename _T > _T Gui::ActiveObjectList::getObject (const char * name, App::DocumentObject ** parent = nullptr, std::string * subname = nullptr) const inline
Definition at line 58 of file ActiveObjectList.h.
References UtilsAssembly::getObject(), and Init::parent.
hasObject() [1/2]
bool Gui::ActiveObjectList::hasObject (App::DocumentObject * obj, const char * name, const char * subname = nullptr) const
Definition at line 145 of file ActiveObjectList.cpp.
References Path.Log::info().
hasObject() [2/2]
bool Gui::ActiveObjectList::hasObject (const char * name) const
Definition at line 180 of file ActiveObjectList.cpp.
objectDeleted()
void ActiveObjectList::objectDeleted (const ViewProviderDocumentObject & viewProviderIn)
Definition at line 185 of file ActiveObjectList.cpp.
References Gui::ViewProviderDocumentObject::getObject().
Referenced by Gui::MDIView::MDIView().
setObject()
void Gui::ActiveObjectList::setObject (App::DocumentObject * obj, const char * name, const char * subname = nullptr, const Gui::HighlightMode & m = HighlightMode::UserDefined)
Definition at line 155 of file ActiveObjectList.cpp.
References FC_ERR, App::DocumentObject::getFullName(), and Path.Log::info().
The documentation for this class was generated from the following files:
ActiveObjectList.h
ActiveObjectList.cpp