FreeCAD: AverageCollector Class Reference
AverageCollector Class Reference
Public Member Functions
AverageCollector ()
void collect (Quantity value) override
Quantity getQuantity () const override
Public Member Functions inherited from Collector
Collector ()=default
virtual ~Collector ()=default
Additional Inherited Members
Protected Attributes inherited from Collector
bool first {true}
Quantity q
Detailed Description
Definition at line 1901 of file Expression.cpp.
Constructor & Destructor Documentation
AverageCollector()
AverageCollector::AverageCollector () inline
Definition at line 1903 of file Expression.cpp.
Member Function Documentation
collect()
void AverageCollector::collect (Quantity value) inline override virtual
Reimplemented from Collector.
Definition at line 1905 of file Expression.cpp.
References Collector::collect().
getQuantity()
Quantity AverageCollector::getQuantity () const inline override virtual
Reimplemented from Collector.
Definition at line 1912 of file Expression.cpp.
Referenced by materialtests.TestMaterials.MaterialTestCases::test2DArray(), materialtests.TestMaterials.MaterialTestCases::test3DArray(), materialtests.TestMaterials.MaterialTestCases::testCalculiXSteel(), and materialtests.TestMaterialCreation.MaterialCreationTestCases::testCreateMaterial().
The documentation for this class was generated from the following file:
Expression.cpp