FreeCAD: Path.Base.Gui.Util Namespace Reference
Path.Base.Gui.Util Namespace Reference
Classes
class QuantitySpinBox
Functions
def populateCombobox (form, enumTups, comboBoxesPropertyMap)
def updateInputField (obj, prop, widget, onBeforeChange=None)
def getDocNode ()
def disableItem (item)
def findItem (docitem, objname)
Function Documentation
disableItem()
def Path.Base.Gui.Util.disableItem (item)
Definition at line 240 of file Base/Gui/Util.py.
Referenced by Path.Op.Gui.FeatureExtension.TaskPanelExtensionPage.extensionsClear().
findItem()
def Path.Base.Gui.Util.findItem (docitem, objname)
Definition at line 249 of file Base/Gui/Util.py.
getDocNode()
def Path.Base.Gui.Util.getDocNode ()
Definition at line 225 of file Base/Gui/Util.py.
populateCombobox()
def Path.Base.Gui.Util.populateCombobox (form, enumTups, comboBoxesPropertyMap)
populateCombobox(form, enumTups, comboBoxesPropertyMap) ... populate comboboxes with translated enumerations
** comboBoxesPropertyMap will be unnecessary if UI files use strict combobox naming protocol.
Args:
    form = UI form
    enumTups = list of (translated_text, data_string) tuples
    comboBoxesPropertyMap = list of (translated_text, data_string) tuples
Definition at line 44 of file Base/Gui/Util.py.
References Path.Log.track().
updateInputField()
def Path.Base.Gui.Util.updateInputField (obj, prop, widget, onBeforeChange = None)
updateInputField(obj, prop, widget) ... update obj's property prop with the value of widget.
The property's value is only assigned if the new value differs from the current value.
This prevents onChanged notifications where the value didn't actually change.
Gui::InputField and Gui::QuantitySpinBox widgets are supported - and the property can
be of type Quantity or Float.
If onBeforeChange is specified it is called before a new value is assigned to the property.
Returns True if a new value was assigned, False otherwise (new value is the same as the current).
Definition at line 62 of file Base/Gui/Util.py.
References Path.Log.debug(), Path.Geom.isRoughly(), and Path.Log.track().
Referenced by Path.Base.Gui.Util.QuantitySpinBox.updateProperty().