FreeCAD: FemGui::TaskFemConstraintContact Class Reference
FemGui::TaskFemConstraintContact Class Reference
#include <TaskFemConstraintContact.h>
Public Member Functions
TaskFemConstraintContact (ViewProviderFemConstraintContact *ConstraintView, QWidget *parent=nullptr)
~TaskFemConstraintContact () override
const std::string getReferences () const override
const std::string getAdjust () const
const std::string getSlope () const
bool getFriction () const
const std::string getStickSlope () const
double getFrictionCoeff () const
Public Member Functions inherited from FemGui::TaskFemConstraint
TaskFemConstraint (ViewProviderFemConstraint *ConstraintView, QWidget *parent=nullptr, const char *pixmapname="")
~TaskFemConstraint () override=default
const std::string getReferences (const std::vector< std::string > &items) const
const std::string getScale () const
Public Member Functions inherited from Gui::TaskView::TaskBox
TaskBox (QWidget *parent=nullptr)
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
QSize minimumSizeHint () const override
~TaskBox () override
void hideGroupBox ()
bool isGroupVisible () const
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (QWidget *parent=nullptr)
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
QBoxLayout * groupLayout ()
void setScheme (ActionPanelScheme *pointer)
bool isExpandable () const
bool hasHeader () const
QString headerText () const
QSize minimumSizeHint () const override
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Protected Member Functions
void changeEvent (QEvent *e) override
Protected Member Functions inherited from FemGui::TaskFemConstraint
void changeEvent (QEvent *e) override
const QString makeRefText (const std::string &objName, const std::string &subName) const
const QString makeRefText (const App::DocumentObject *obj, const std::string &subName) const
void keyPressEvent (QKeyEvent *ke) override
void createDeleteAction (QListWidget *parentList)
void onSelectionChanged (const Gui::SelectionChanges &) override
Protected Member Functions inherited from Gui::TaskView::TaskBox
void showEvent (QShowEvent *) override
void actionEvent (QActionEvent *) override
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
void paintEvent (QPaintEvent *event) override
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void showHide ()
void setExpandable (bool expandable=true)
void setHeader (bool enable=true)
void setHeaderText (const QString &title)
void setHeaderIcon (const QPixmap &icon)
Protected Types inherited from FemGui::TaskFemConstraint
enum { seldir, selref, selloc, selnone }
Protected Slots inherited from FemGui::TaskFemConstraint
void onReferenceDeleted (const int row)
void onButtonReference (const bool pressed=true)
void setSelection (QListWidgetItem *item)
bool event (QEvent *event) override
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Protected Attributes inherited from FemGui::TaskFemConstraint
QWidget * proxy
QAction * deleteAction
Gui::WeakPtrT< ViewProviderFemConstraint > ConstraintView
enum FemGui::TaskFemConstraint:: { ... } selectionMode
Protected Attributes inherited from QSint::ActionGroup
double m_foldStep
double m_foldDelta
double m_fullHeight
double m_tempHeight
int m_foldDirection
QPixmap m_foldPixmap
class TaskHeader * myHeader
class TaskGroup * myGroup
QWidget * myDummy
ActionPanelScheme * myScheme
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Detailed Description
Definition at line 40 of file TaskFemConstraintContact.h.
Constructor & Destructor Documentation
TaskFemConstraintContact()
TaskFemConstraintContact::TaskFemConstraintContact (ViewProviderFemConstraintContact * ConstraintView, QWidget * parent = nullptr) explicit
Definition at line 48 of file TaskFemConstraintContact.cpp.
References Fem::ConstraintContact::Adjust, draftgeoutils.intersections::connect(), FemGui::TaskFemConstraint::ConstraintView, FLOAT_MAX, Fem::ConstraintContact::Friction, Fem::ConstraintContact::FrictionCoefficient, App::PropertyQuantity::getQuantityValue(), App::PropertyLinkSubList::getSubValues(), App::PropertyQuantity::getUnit(), App::PropertyFloat::getValue(), App::PropertyBool::getValue(), App::PropertyLinkSubList::getValues(), QSint::ActionGroup::groupLayout(), FemGui::TaskFemConstraint::makeRefText(), FemGui::TaskFemConstraint::proxy, Fem::Constraint::References, FemGui::TaskFemConstraint::setSelection(), Fem::ConstraintContact::Slope, Fem::ConstraintContact::StickSlope, and Path.Log::warning().
~TaskFemConstraintContact()
TaskFemConstraintContact::~TaskFemConstraintContact () override default
Member Function Documentation
changeEvent()
void TaskFemConstraintContact::changeEvent (QEvent * e) override protected
Definition at line 499 of file TaskFemConstraintContact.cpp.
getAdjust()
const std::string TaskFemConstraintContact::getAdjust () const
Definition at line 479 of file TaskFemConstraintContact.cpp.
Referenced by FemGui::TaskDlgFemConstraintContact::accept().
getFriction()
bool TaskFemConstraintContact::getFriction () const
Definition at line 484 of file TaskFemConstraintContact.cpp.
Referenced by FemGui::TaskDlgFemConstraintContact::accept().
getFrictionCoeff()
double TaskFemConstraintContact::getFrictionCoeff () const
Definition at line 489 of file TaskFemConstraintContact.cpp.
Referenced by FemGui::TaskDlgFemConstraintContact::accept().
getReferences()
const std::string TaskFemConstraintContact::getReferences () const override virtual
Reimplemented from FemGui::TaskFemConstraint.
Definition at line 459 of file TaskFemConstraintContact.cpp.
References FemGui::TaskFemConstraint::getReferences(), and src.Mod.Test.testPathArray::items.
getSlope()
const std::string TaskFemConstraintContact::getSlope () const
Definition at line 474 of file TaskFemConstraintContact.cpp.
Referenced by FemGui::TaskDlgFemConstraintContact::accept().
getStickSlope()
const std::string TaskFemConstraintContact::getStickSlope () const
Definition at line 494 of file TaskFemConstraintContact.cpp.
Referenced by FemGui::TaskDlgFemConstraintContact::accept().
The documentation for this class was generated from the following files:
TaskFemConstraintContact.h
TaskFemConstraintContact.cpp