FreeCAD: MeshCore::MeshFastBuilder Class Reference
MeshCore::MeshFastBuilder Class Reference
#include <Builder.h>
Classes
struct Private
Public Types
using size_type = int
Public Member Functions
MeshFastBuilder (MeshKernel &rclM)
~MeshFastBuilder ()
MeshFastBuilder (const MeshFastBuilder &)=delete
MeshFastBuilder (MeshFastBuilder &&)=delete
MeshFastBuilder & operator= (const MeshFastBuilder &)=delete
MeshFastBuilder & operator= (MeshFastBuilder &&)=delete
void Initialize (size_type ctFacets)
void AddFacet (const Base::Vector3f *facetPoints)
void AddFacet (const MeshGeomFacet &facetPoints)
void Finish ()
Detailed Description
Class for creating the mesh structure by adding facets. Building the structure needs 3 steps:
initializing
adding the facets
finishing
// Sample Code for building a mesh structure
MeshFastBuilder builder(someMeshReference);
builder.Initialize(numberOfFacets);
...
for (...)
  builder.AddFacet(...);
...
builder.Finish();
Author
Werner Mayer
Definition at line 196 of file Builder.h.
Member Typedef Documentation
size_type
using MeshCore::MeshFastBuilder::size_type = int
Definition at line 202 of file Builder.h.
Constructor & Destructor Documentation
MeshFastBuilder() [1/3]
MeshFastBuilder::MeshFastBuilder (MeshKernel & rclM) explicit
Definition at line 324 of file Builder.cpp.
~MeshFastBuilder()
MeshFastBuilder::~MeshFastBuilder ()
Definition at line 329 of file Builder.cpp.
MeshFastBuilder() [2/3]
MeshCore::MeshFastBuilder::MeshFastBuilder (const MeshFastBuilder &) delete
MeshFastBuilder() [3/3]
MeshCore::MeshFastBuilder::MeshFastBuilder (MeshFastBuilder &&) delete
Member Function Documentation
AddFacet() [1/2]
void MeshFastBuilder::AddFacet (const Base::Vector3f * facetPoints)
Add new facet
Definition at line 339 of file Builder.cpp.
References SplineSurface::i, TestSpreadsheet::v, MeshCore::MeshFastBuilder::Private::verts, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by MeshCore::MeshInput::LoadAsciiSTL(), and MeshCore::MeshInput::LoadBinarySTL().
AddFacet() [2/2]
void MeshFastBuilder::AddFacet (const MeshGeomFacet & facetPoints)
Add new facet
Definition at line 350 of file Builder.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, TestSpreadsheet::v, and MeshCore::MeshFastBuilder::Private::verts.
Finish()
void MeshFastBuilder::Finish ()
Finishes building up the mesh structure. Must be done after adding facets.
Definition at line 361 of file Builder.cpp.
References MeshCore::MeshKernel::Adopt(), SplineSurface::i, MeshCore::parallel_sort(), TestSpreadsheet::v, and MeshCore::MeshFastBuilder::Private::verts.
Referenced by MeshCore::MeshInput::LoadAsciiSTL(), and MeshCore::MeshInput::LoadBinarySTL().
Initialize()
void MeshFastBuilder::Initialize (size_type ctFacets)
Initializes the class. Must be done before adding facets
Parameters
ctFacets count of facets.
Definition at line 334 of file Builder.cpp.
References MeshCore::MeshFastBuilder::Private::verts.
Referenced by MeshCore::MeshInput::LoadAsciiSTL(), and MeshCore::MeshInput::LoadBinarySTL().
operator=() [1/2]
MeshFastBuilder& MeshCore::MeshFastBuilder::operator= (const MeshFastBuilder &) delete
operator=() [2/2]
MeshFastBuilder& MeshCore::MeshFastBuilder::operator= (MeshFastBuilder &&) delete
The documentation for this class was generated from the following files:
Builder.h
Builder.cpp