FreeCAD: SCL.BaseType.Type Class Reference
SCL.BaseType.Type Class Reference
Public Member Functions
def __init__ (self, typedef, scope)
def get_scope (self)
def get_type (self)
Detailed Description
A type can be defined from its name and scope
Looking into the scope dict returns the python type class.
This is the base class for aggregated data types or constructed data types
Definition at line 33 of file BaseType.py.
Constructor & Destructor Documentation
__init__()
def SCL.BaseType.Type.__init__ (self, typedef, scope)
Definition at line 40 of file BaseType.py.
References SCL.BaseType.Type._scope, and SCL.BaseType.Type._typedef.
Member Function Documentation
get_scope()
def SCL.BaseType.Type.get_scope (self)
Definition at line 44 of file BaseType.py.
References SCL.BaseType.Type._scope.
get_type()
def SCL.BaseType.Type.get_type (self)
Definition at line 47 of file BaseType.py.
References SCL.BaseType.Type._scope, SCL.BaseType.Type._typedef, and Path.Post.scripts.grbl_post.type.
Referenced by SCL.AggregationDataTypes.ARRAY.__setitem__(), SCL.AggregationDataTypes.LIST.__setitem__(), SCL.AggregationDataTypes.BAG.add(), and SCL.AggregationDataTypes.SET.add().
The documentation for this class was generated from the following file:
BaseType.py