FreeCAD: Gui::TDragger Class Reference
Gui::TDragger Class Reference
Translation Dragger.
#include <SoFCCSysDragger.h>
Public Member Functions
TDragger ()
Static Public Member Functions
static void initClass ()
Public Attributes
SoSFString label
set from outside and used to label
SoSFVec3f translation
set from outside and used from outside for single precision.
SoSFDouble translationIncrement
set from outside and used for rounding.
SoSFInt32 translationIncrementCount
number of steps. used from outside.
SoSFFloat autoScaleResult
set from parent dragger.
Protected Member Functions
~TDragger () override
SbBool setUpConnections (SbBool onoff, SbBool doitalways=FALSE) override
void dragStart ()
void drag ()
void dragFinish ()
Static Protected Member Functions
static void startCB (void *, SoDragger *d)
static void motionCB (void *, SoDragger *d)
static void finishCB (void *, SoDragger *d)
static void fieldSensorCB (void *f, SoSensor *)
static void valueChangedCB (void *, SoDragger *d)
Protected Attributes
SoFieldSensor fieldSensor
SbLineProjector projector
Detailed Description
Translation Dragger.
used for translating along axis. Set the translationIncrement to desired step. Use 'translationIncrementCount' multiplied with 'translationIncrement' for a full double precision vector scalar.
Definition at line 52 of file SoFCCSysDragger.h.
Constructor & Destructor Documentation
TDragger()
TDragger::TDragger ()
Definition at line 98 of file SoFCCSysDragger.cpp.
References autoScaleResult, fieldSensor, fieldSensorCB(), finishCB(), motionCB(), setUpConnections(), startCB(), translation, translationIncrement, translationIncrementCount, SCL.Builtin::TRUE, and valueChangedCB().
~TDragger()
TDragger::~TDragger () override protected
Definition at line 153 of file SoFCCSysDragger.cpp.
References fieldSensor, finishCB(), motionCB(), startCB(), and valueChangedCB().
Member Function Documentation
drag()
void TDragger::drag () protected
Definition at line 328 of file SoFCCSysDragger.cpp.
References autoScaleResult, SCL.SimpleDataTypes::f, Gui::getMainWindow(), Base::Quantity::getUserString(), Base::Unit::Length, projector, Gui::MainWindow::showMessage(), translationIncrement, and translationIncrementCount.
dragFinish()
void TDragger::dragFinish () protected
Definition at line 364 of file SoFCCSysDragger.cpp.
dragStart()
void TDragger::dragStart () protected
Definition at line 304 of file SoFCCSysDragger.cpp.
References projector, and translationIncrementCount.
fieldSensorCB()
void TDragger::fieldSensorCB (void * f, SoSensor *) static protected
Definition at line 273 of file SoFCCSysDragger.cpp.
References SCL.SimpleDataTypes::f.
Referenced by setUpConnections(), and TDragger().
finishCB()
void TDragger::finishCB (void * , SoDragger * d) static protected
Definition at line 266 of file SoFCCSysDragger.cpp.
Referenced by TDragger(), and ~TDragger().
initClass()
void TDragger::initClass () static
Definition at line 93 of file SoFCCSysDragger.cpp.
Referenced by Gui::SoFCCSysDragger::initClass(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
motionCB()
void TDragger::motionCB (void * , SoDragger * d) static protected
Definition at line 259 of file SoFCCSysDragger.cpp.
Referenced by TDragger(), and ~TDragger().
setUpConnections()
SbBool TDragger::setUpConnections (SbBool onoff, SbBool doitalways = FALSE) override protected
Definition at line 371 of file SoFCCSysDragger.cpp.
References fieldSensor, fieldSensorCB(), and translation.
Referenced by TDragger().
startCB()
void TDragger::startCB (void * , SoDragger * d) static protected
Definition at line 252 of file SoFCCSysDragger.cpp.
Referenced by TDragger(), and ~TDragger().
valueChangedCB()
void TDragger::valueChangedCB (void * , SoDragger * d) static protected
Definition at line 286 of file SoFCCSysDragger.cpp.
Referenced by TDragger(), and ~TDragger().
Member Data Documentation
autoScaleResult
SoSFFloat Gui::TDragger::autoScaleResult
set from parent dragger.
Definition at line 75 of file SoFCCSysDragger.h.
Referenced by drag(), Gui::SoFCCSysDragger::SoFCCSysDragger(), and TDragger().
fieldSensor
SoFieldSensor Gui::TDragger::fieldSensor protected
Definition at line 91 of file SoFCCSysDragger.h.
Referenced by setUpConnections(), TDragger(), and ~TDragger().
label
SoSFString Gui::TDragger::label
set from outside and used to label
Definition at line 71 of file SoFCCSysDragger.h.
Referenced by WorkingPlane.PlaneGui::align_to_obj_placement(), WorkingPlane.PlaneGui::align_to_selection(), WorkingPlane.PlaneGui::align_view(), WorkingPlane.PlaneGui::center_on_view(), Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.TrackChunk::dump_array(), Dice3DS.dom3ds.ChunkBase::dump_header(), Dice3DS.dom3ds.ChunkBase::get_chunk(), ArchSpace._ViewProviderSpace::onChanged(), WorkingPlane.PlaneGui::set_to_auto(), WorkingPlane.PlaneGui::set_to_front(), WorkingPlane.PlaneGui::set_to_position(), WorkingPlane.PlaneGui::set_to_side(), WorkingPlane.PlaneGui::set_to_top(), WorkingPlane.PlaneGui::set_to_view(), and Gui::SoFCCSysDragger::SoFCCSysDragger().
projector
SbLineProjector Gui::TDragger::projector protected
Definition at line 92 of file SoFCCSysDragger.h.
Referenced by drag(), and dragStart().
translation
SoSFVec3f Gui::TDragger::translation
set from outside and used from outside for single precision.
Definition at line 72 of file SoFCCSysDragger.h.
Referenced by setUpConnections(), and TDragger().
translationIncrement
SoSFDouble Gui::TDragger::translationIncrement
set from outside and used for rounding.
Definition at line 73 of file SoFCCSysDragger.h.
Referenced by drag(), Gui::SoFCCSysDragger::SoFCCSysDragger(), and TDragger().
translationIncrementCount
SoSFInt32 Gui::TDragger::translationIncrementCount
number of steps. used from outside.
Definition at line 74 of file SoFCCSysDragger.h.
Referenced by drag(), dragStart(), Gui::SoFCCSysDragger::SoFCCSysDragger(), and TDragger().
The documentation for this class was generated from the following files:
SoFCCSysDragger.h
SoFCCSysDragger.cpp