FreeCAD: src.Mod.AddonManager.addonmanager_python_deps_gui.CheckForPythonPackageUpdatesWorker Class Reference
src.Mod.AddonManager.addonmanager_python_deps_gui.CheckForPythonPackageUpdatesWorker Class Reference
Public Member Functions
def __init__ (self)
def run (self)
Static Public Attributes
python_package_updates_available = QtCore.Signal()
Detailed Description
Perform non-blocking Python library update availability checking
Definition at line 70 of file addonmanager_python_deps_gui.py.
Constructor & Destructor Documentation
__init__()
def src.Mod.AddonManager.addonmanager_python_deps_gui.CheckForPythonPackageUpdatesWorker.__init__ (self)
Definition at line 75 of file addonmanager_python_deps_gui.py.
Referenced by draftguitools.gui_subelements.SubelementHighlight.finish().
Member Function Documentation
run()
def src.Mod.AddonManager.addonmanager_python_deps_gui.CheckForPythonPackageUpdatesWorker.run (self)
Usually not called directly: instead, instantiate this class and call its start()
function in a parent thread. emits a python_package_updates_available signal if updates
are available for any of the installed Python packages.
Definition at line 78 of file addonmanager_python_deps_gui.py.
References src.Mod.AddonManager.addonmanager_python_deps_gui.python_package_updates_are_available(), and src.Mod.AddonManager.addonmanager_python_deps_gui.CheckForPythonPackageUpdatesWorker.python_package_updates_available.
Referenced by femexamples.examplesgui.FemExamples.clicked(), and femsolver.task.Task.protector().
Member Data Documentation
python_package_updates_available
src.Mod.AddonManager.addonmanager_python_deps_gui.CheckForPythonPackageUpdatesWorker.python_package_updates_available = QtCore.Signal() static
Definition at line 73 of file addonmanager_python_deps_gui.py.
Referenced by src.Mod.AddonManager.addonmanager_python_deps_gui.CheckForPythonPackageUpdatesWorker.run().
The documentation for this class was generated from the following file:
addonmanager_python_deps_gui.py