FreeCAD: DrawSketchHandlerGenConstraint Class Reference
DrawSketchHandlerGenConstraint Class Reference
Public Member Functions
DrawSketchHandlerGenConstraint (CmdSketcherConstraint *_cmd)
~DrawSketchHandlerGenConstraint () override
void mouseMove (Base::Vector2d) override
bool pressButton (Base::Vector2d) override
bool releaseButton (Base::Vector2d onSketchPos) override
Public Member Functions inherited from SketcherGui::DrawSketchHandler
DrawSketchHandler ()
virtual ~DrawSketchHandler ()
void activate (ViewProviderSketch *)
void deactivate () override
virtual void registerPressedKey (bool pressed, int key)
virtual void pressRightButton (Base::Vector2d pos)
virtual bool onSelectionChanged (const Gui::SelectionChanges &)
void quit () override
int getHighestVertexIndex ()
int getHighestCurveIndex ()
int seekAutoConstraint (std::vector< AutoConstraint > &suggestedConstraints, const Base::Vector2d &Pos, const Base::Vector2d &Dir, AutoConstraint::TargetType type=AutoConstraint::VERTEX)
int seekAndRenderAutoConstraint (std::vector< AutoConstraint > &suggestedConstraints, const Base::Vector2d &Pos, const Base::Vector2d &Dir, AutoConstraint::TargetType type=AutoConstraint::VERTEX)
void createAutoConstraints (const std::vector< AutoConstraint > &autoConstrs, int geoId, Sketcher::PointPos pointPos=Sketcher::PointPos::none, bool createowncommand=true)
void setPositionText (const Base::Vector2d &Pos, const SbString &text)
void setPositionText (const Base::Vector2d &Pos)
void resetPositionText ()
void renderSuggestConstraintsCursor (std::vector< AutoConstraint > &suggestedConstraints)
void toolWidgetChanged (QWidget *newwidget)
Slot to receive signaling that a widget intended for the tool has changed and is available ant the provided pointer.
std::unique_ptr< QWidget > createToolWidget () const
Factory function returning a tool widget of the type necessary for the specific tool. This is a NVI interface and specific handlers must overload the corresponding virtual function.
bool isToolWidgetVisible () const
Returns whether this tool expects/supports a visible tool widget. Emphasis is in visibility, so to allow one to adapt the interface accordingly. This is an NVI interface and specific handlers must overload the corresponding virtual function.
QPixmap getToolWidgetHeaderIcon () const
Returns a pixmap icon intended for a visible tool widget. This is an NVI interface and specific handlers must overload the corresponding virtual function.
QString getToolWidgetHeaderText () const
Returns a header text intended for a visible tool widget. This is an NVI interface and specific handlers must overload the corresponding virtual function.
Public Member Functions inherited from Gui::ToolHandler
ToolHandler ()=default
virtual ~ToolHandler ()=default
bool activate ()
void updateCursor ()
Protected Member Functions
void resetOngoingSequences ()
Protected Member Functions inherited from SketcherGui::DrawSketchHandler
virtual std::string getToolName () const
virtual std::unique_ptr< QWidget > createWidget () const
virtual bool isWidgetVisible () const
virtual QPixmap getToolIcon () const
virtual QString getToolWidgetText () const
void drawEdit (const std::vector< Base::Vector2d > &EditCurve) const
void drawEdit (const std::list< std::vector< Base::Vector2d >> &list) const
void drawEdit (const std::vector< Part::Geometry * > &geometries) const
void drawEditMarkers (const std::vector< Base::Vector2d > &EditMarkers, unsigned int augmentationlevel=0) const
void clearEdit () const
void clearEditMarkers () const
void setAxisPickStyle (bool on)
void moveCursorToSketchPoint (Base::Vector2d point)
void ensureFocus ()
void preselectAtPoint (Base::Vector2d point)
void drawPositionAtCursor (const Base::Vector2d &position)
void drawDirectionAtCursor (const Base::Vector2d &position, const Base::Vector2d &origin)
void drawWidthHeightAtCursor (const Base::Vector2d &position, const double val1, const double val2)
void drawDoubleAtCursor (const Base::Vector2d &position, const double radius, Base::Unit unit=Base::Unit::Length)
int getPreselectPoint () const
int getPreselectCurve () const
int getPreselectCross () const
Sketcher::SketchObject * getSketchObject ()
void setAngleSnapping (bool enable, Base::Vector2d referencePoint=Base::Vector2d(0., 0.))
void moveConstraint (int constNum, const Base::Vector2d &toPos)
void signalToolChanged () const
std::vector< QPixmap > suggestedConstraintsPixmaps (std::vector< AutoConstraint > &suggestedConstraints)
Protected Member Functions inherited from Gui::ToolHandler
virtual QString getCrosshairCursorSVGName () const
void setCursor (const QPixmap &pixmap, int x, int y, bool autoScale=true)
void unsetCursor ()
void applyCursor ()
restitutes the DSH cached cursor (without any tail due to autoconstraints, ...)
void addCursorTail (std::vector< QPixmap > &pixmaps)
unsigned long getCrosshairColor ()
returns the color to be used for the crosshair (configurable as a parameter)
qreal devicePixelRatio ()
functions to set the cursor to a given svgName (to be migrated to NVI style)
View3DInventorViewer * getViewer ()
virtual QWidget * getCursorWidget ()
virtual void setWidgetCursor (QCursor cursor)
Protected Attributes
CmdSketcherConstraint * cmd
GenericConstraintSelection * selFilterGate = nullptr
std::vector< SelIdPair > selSeq
unsigned int allowedSelTypes = 0
std::set< int > ongoingSequences
indices of currently ongoing sequences in cmd->allowedSequences
std::set< int > _tempOnSequences
unsigned int seqIndex
Index within the selection sequences active.
Protected Attributes inherited from SketcherGui::DrawSketchHandler
ViewProviderSketch * sketchgui
QWidget * toolwidget
Protected Attributes inherited from Gui::ToolHandler
QCursor oldCursor
QCursor actCursor
QPixmap actCursorPixmap
Detailed Description
Definition at line 1003 of file CommandConstraints.cpp.
Constructor & Destructor Documentation
DrawSketchHandlerGenConstraint()
DrawSketchHandlerGenConstraint::DrawSketchHandlerGenConstraint (CmdSketcherConstraint * _cmd) inline explicit
Definition at line 1006 of file CommandConstraints.cpp.
~DrawSketchHandlerGenConstraint()
DrawSketchHandlerGenConstraint::~DrawSketchHandlerGenConstraint () inline override
Definition at line 1010 of file CommandConstraints.cpp.
References Gui::SelectionSingleton::rmvSelectionGate(), and Gui::Selection().
Member Function Documentation
mouseMove()
void DrawSketchHandlerGenConstraint::mouseMove (Base::Vector2d) inline override virtual
Implements SketcherGui::DrawSketchHandler.
Definition at line 1015 of file CommandConstraints.cpp.
pressButton()
bool DrawSketchHandlerGenConstraint::pressButton (Base::Vector2d) inline override virtual
Implements SketcherGui::DrawSketchHandler.
Definition at line 1018 of file CommandConstraints.cpp.
releaseButton()
bool DrawSketchHandlerGenConstraint::releaseButton (Base::Vector2d onSketchPos) inline override virtual
Implements SketcherGui::DrawSketchHandler.
Definition at line 1023 of file CommandConstraints.cpp.
References Gui::SelectionSingleton::addSelection(), Gui::SelectionSingleton::clearSelection(), SketcherGui::SelIdPair::GeoId, Sketcher::GeoUndef, Sketcher::HAxis, Sketcher::none, SketcherGui::SelIdPair::PosId, Sketcher::RefExt, Sketcher::RtPnt, Gui::Selection(), SketcherGui::SelEdge, SketcherGui::SelEdgeOrAxis, SketcherGui::SelExternalEdge, SketcherGui::SelHAxis, SketcherGui::SelRoot, SketcherGui::SelUnknown, SketcherGui::SelVAxis, SketcherGui::SelVertex, SketcherGui::SelVertexOrRoot, Sketcher::start, Sketcher::VAxis, Base::Vector2d::x, and Base::Vector2d::y.
resetOngoingSequences()
void DrawSketchHandlerGenConstraint::resetOngoingSequences () inline protected
Definition at line 1168 of file CommandConstraints.cpp.
References CmdSketcherConstraint::allowedSelSequences, Gui::SelectionSingleton::clearSelection(), SplineSurface::i, Gui::Selection(), and SketcherGui::GenericConstraintSelection::setAllowedSelTypes().
Member Data Documentation
_tempOnSequences
std::set<int> DrawSketchHandlerGenConstraint::_tempOnSequences protected
Definition at line 1164 of file CommandConstraints.cpp.
allowedSelTypes
unsigned int DrawSketchHandlerGenConstraint::allowedSelTypes = 0 protected
Definition at line 1161 of file CommandConstraints.cpp.
cmd
CmdSketcherConstraint* DrawSketchHandlerGenConstraint::cmd protected
Definition at line 1156 of file CommandConstraints.cpp.
ongoingSequences
std::set<int> DrawSketchHandlerGenConstraint::ongoingSequences protected
indices of currently ongoing sequences in cmd->allowedSequences
Definition at line 1164 of file CommandConstraints.cpp.
selFilterGate
GenericConstraintSelection* DrawSketchHandlerGenConstraint::selFilterGate = nullptr protected
Definition at line 1158 of file CommandConstraints.cpp.
selSeq
std::vector<SelIdPair> DrawSketchHandlerGenConstraint::selSeq protected
Definition at line 1160 of file CommandConstraints.cpp.
seqIndex
unsigned int DrawSketchHandlerGenConstraint::seqIndex protected
Index within the selection sequences active.
Definition at line 1166 of file CommandConstraints.cpp.
The documentation for this class was generated from the following file:
CommandConstraints.cpp