FreeCAD: Base::XMLReader Class Reference
Base::XMLReader Class Reference
#include <Reader.h>
Classes
struct FileEntry
Public Types
enum ReaderStatus { PartialRestore, PartialRestoreInDocumentObject = 1, PartialRestoreInProperty = 2, PartialRestoreInObject = 3 }
Public Member Functions
XMLReader (const char *FileName, std::istream &)
open the file and read the first element
~XMLReader () override
Parser handling
const char * localName () const
get the local name of the current Element
int level () const
get the current element level
bool isEndOfElement () const
return true if the end of an element is reached, false otherwise
bool isStartOfDocument () const
return true if the on the start of the document, false otherwise
bool isEndOfDocument () const
return true if the end of the document is reached, false otherwise
void readElement (const char *ElementName=nullptr)
bool readNextElement ()
Read in the next element. Return true if it succeeded and false otherwise.
void readEndElement (const char *ElementName=nullptr, int level=-1)
void readCharacters (const char *filename, CharStreamFormat format=CharStreamFormat::Raw)
read until characters are found
std::istream & beginCharStream (CharStreamFormat format=CharStreamFormat::Raw)
void endCharStream ()
Manually end the current character stream.
std::istream & charStream ()
Obtain the current character stream.
void readBinFile (const char *)
read binary file
Attribute handling
unsigned int getAttributeCount () const
get the number of attributes of the current element
bool hasAttribute (const char *AttrName) const
check if the read element has a special attribute
long getAttributeAsInteger (const char *AttrName, const char *defaultValue=nullptr) const
unsigned long getAttributeAsUnsigned (const char *AttrName, const char *defaultValue=nullptr) const
double getAttributeAsFloat (const char *AttrName, const char *defaultValue=nullptr) const
const char * getAttribute (const char *AttrName, const char *defaultValue=nullptr) const
Protected Member Functions
Content handler
void startDocument () override
void endDocument () override
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const Attributes &attrs) override
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) override
void characters (const XMLCh *const chars, const XMLSize_t length) override
void ignorableWhitespace (const XMLCh *const chars, const XMLSize_t length) override
Lexical handler
void startCDATA () override
void endCDATA () override
Document handler
void resetDocument () override
boost iostream device interface
using category = boost::iostreams::source_tag
using char_type = char
std::streamsize read (char_type *s, std::streamsize n)
bool isValid () const
bool isVerbose () const
void setVerbose (bool on)
additional file reading
int DocumentSchema {0}
Schema Version of the document.
std::string ProgramVersion
Version of FreeCAD that wrote this document.
int FileVersion {0}
Version of the file format.
const char * addFile (const char *Name, Base::Persistence *Object)
add a read request of a persistent object
void readFiles (zipios::ZipInputStream &zipstream) const
process the requested file writes
const std::vector< std::string > & getFilenames () const
get all registered file names
bool hasReadFailed (const std::string &filename) const
returns true if reading the file filename has failed
bool isRegistered (Base::Persistence *Object) const
virtual void addName (const char *, const char *)
virtual const char * getName (const char *) const
virtual bool doNameMapping () const
void setPartialRestore (bool on)
sets simultaneously the global and local PartialRestore bits
void clearPartialRestoreDocumentObject ()
void clearPartialRestoreProperty ()
void clearPartialRestoreObject ()
bool testStatus (ReaderStatus pos) const
return the status bits
void setStatus (ReaderStatus pos, bool on)
set the status bits
bool read ()
read the next element
Error handler
std::vector< FileEntry > FileList
void warning (const SAXParseException &exc) override
void error (const SAXParseException &exc) override
void fatalError (const SAXParseException &exc) override
void resetErrors () override
Detailed Description
The XML reader class This is an important helper class for the store and retrieval system of objects in FreeCAD. These classes mainly inherit the App::Persitance base class and implement the Restore() method.
The reader gets mainly initialized by the App::Document on retrieving a document out of a file. From there subsequently the Restore() method will by called on all object stored.
A simple example is the Restore of App::PropertyString:
void PropertyString::Save (short indent,std::ostream &str)
{
    str << "<String value=\"" <<  _cValue.c_str() <<"\"/>" ;
}
void PropertyString::Restore(Base::Reader &reader)
{
    // read my Element
    reader.readElement("String");
    // get the value of my Attribute
    _cValue = reader.getAttribute("value");
}
An more complicated example is the retrieval of the App::PropertyContainer:
void PropertyContainer::Save (short indent,std::ostream &str)
{
    std::map<std::string,Property*> Map;
    getPropertyMap(Map);
    str << ind(indent) << "<Properties Count=\"" << Map.size() << "\">" << endl;
    std::map<std::string,Property*>::iterator it;
    for(it = Map.begin(); it != Map.end(); ++it)
    {
        str << ind(indent+1) << "<Property name=\"" << it->first << "\" type=\"" <<
it->second->getTypeId().getName() << "\">" ; it->second->Save(indent+2,str); str << "</Property>" <<
endl;
    }
    str << ind(indent) << "</Properties>" << endl;
}
void PropertyContainer::Restore(Base::Reader &reader)
{
    reader.readElement("Properties");
    int Cnt = reader.getAttributeAsInteger("Count");
    for(int i=0 ;i<Cnt ;i++)
    {
        reader.readElement("Property");
        string PropName = reader.getAttribute("name");
        Property* prop = getPropertyByName(PropName.c_str());
        if(prop)
            prop->Restore(reader);
        reader.readEndElement("Property");
    }
    reader.readEndElement("Properties");
}
See also
Base::Persistence
Author
Juergen Riegel
Definition at line 129 of file Reader.h.
Member Typedef Documentation
category
using Base::XMLReader::category = boost::iostreams::source_tag
Definition at line 147 of file Reader.h.
char_type
using Base::XMLReader::char_type = char
Definition at line 148 of file Reader.h.
Member Enumeration Documentation
ReaderStatus
enum Base::XMLReader::ReaderStatus
Enumerator
PartialRestore
PartialRestoreInDocumentObject
PartialRestoreInProperty
PartialRestoreInObject
Definition at line 132 of file Reader.h.
Constructor & Destructor Documentation
XMLReader()
Base::XMLReader::XMLReader (const char * FileName, std::istream & str)
open the file and read the first element
Definition at line 63 of file Reader.cpp.
References DrawingExample::file, Base::FileInfo::filePath(), and Path.Post.scripts.refactored_centroid_post::str.
~XMLReader()
Base::XMLReader::~XMLReader () override
Definition at line 100 of file Reader.cpp.
References getIfcElements::parser.
Member Function Documentation
addFile()
const char * Base::XMLReader::addFile (const char * Name, Base::Persistence * Object)
add a read request of a persistent object
Definition at line 459 of file Reader.cpp.
References Base::XMLReader::FileEntry::FileName, and Base::XMLReader::FileEntry::Object.
Referenced by Gui::MergeDocuments::Restore(), and App::MergeDocuments::Restore().
addName()
void Base::XMLReader::addName (const char * , const char *) virtual
Reimplemented in App::XMLMergeReader, and Gui::XMLMergeReader.
Definition at line 495 of file Reader.cpp.
beginCharStream()
std::istream & Base::XMLReader::beginCharStream (CharStreamFormat format = CharStreamFormat::Raw)
Obtain an input stream for reading characters
Returns
Return a input stream for reading characters. The stream will be auto destroyed when you call with readElement() or readEndElement(), or you can end it explicitly with endCharStream().
Definition at line 340 of file Reader.cpp.
References Base::base64DefaultBufferSize, Base::Base64Encoded, importers.import3DS::read(), and Base::silent.
characters()
void Base::XMLReader::characters (const XMLCh *const chars, const XMLSize_t length) override protected
Definition at line 563 of file Reader.cpp.
References StrX::c_str().
charStream()
std::istream & Base::XMLReader::charStream ()
Obtain the current character stream.
Definition at line 332 of file Reader.cpp.
clearPartialRestoreDocumentObject()
void Base::XMLReader::clearPartialRestoreDocumentObject ()
Definition at line 635 of file Reader.cpp.
clearPartialRestoreObject()
void Base::XMLReader::clearPartialRestoreObject ()
Definition at line 648 of file Reader.cpp.
clearPartialRestoreProperty()
void Base::XMLReader::clearPartialRestoreProperty ()
Definition at line 642 of file Reader.cpp.
doNameMapping()
bool Base::XMLReader::doNameMapping () const virtual
Reimplemented in App::XMLMergeReader, and Gui::XMLMergeReader.
Definition at line 503 of file Reader.cpp.
endCDATA()
void Base::XMLReader::endCDATA () override protected
Definition at line 558 of file Reader.cpp.
endCharStream()
void Base::XMLReader::endCharStream ()
Manually end the current character stream.
Definition at line 326 of file Reader.cpp.
endDocument()
void Base::XMLReader::endDocument () override protected
Definition at line 516 of file Reader.cpp.
endElement()
void Base::XMLReader::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) override protected
Definition at line 538 of file Reader.cpp.
References StrX::c_str().
error()
void Base::XMLReader::error (const SAXParseException & exc) override protected
Definition at line 587 of file Reader.cpp.
References SCL.SimpleDataTypes::e.
fatalError()
void Base::XMLReader::fatalError (const SAXParseException & exc) override protected
Definition at line 596 of file Reader.cpp.
References SCL.SimpleDataTypes::e.
getAttribute()
const char * Base::XMLReader::getAttribute (const char * AttrName, const char * defaultValue = nullptr) const
return the named attribute as a double floating point (does type checking); if missing return defaultValue
Definition at line 132 of file Reader.cpp.
References Path.Op.Surface::msg, and RobotExample::pos.
getAttributeAsFloat()
double Base::XMLReader::getAttributeAsFloat (const char * AttrName, const char * defaultValue = nullptr) const
return the named attribute as a double floating point (does type checking); if missing return defaultValue
Definition at line 127 of file Reader.cpp.
getAttributeAsInteger()
long Base::XMLReader::getAttributeAsInteger (const char * AttrName, const char * defaultValue = nullptr) const
return the named attribute as an integer (does type checking); if missing return defaultValue
Definition at line 116 of file Reader.cpp.
getAttributeAsUnsigned()
unsigned long Base::XMLReader::getAttributeAsUnsigned (const char * AttrName, const char * defaultValue = nullptr) const
return the named attribute as unsigned integer (does type checking); if missing return defaultValue
Definition at line 121 of file Reader.cpp.
getAttributeCount()
unsigned int Base::XMLReader::getAttributeCount () const
get the number of attributes of the current element
Definition at line 111 of file Reader.cpp.
getFilenames()
const std::vector< std::string > & Base::XMLReader::getFilenames () const
get all registered file names
Definition at line 471 of file Reader.cpp.
getName()
const char * Base::XMLReader::getName (const char * name) const virtual
Reimplemented in App::XMLMergeReader, and Gui::XMLMergeReader.
Definition at line 498 of file Reader.cpp.
hasAttribute()
bool Base::XMLReader::hasAttribute (const char * AttrName) const
check if the read element has a special attribute
Definition at line 149 of file Reader.cpp.
hasReadFailed()
bool Base::XMLReader::hasReadFailed (const std::string & filename) const
returns true if reading the file filename has failed
Definition at line 476 of file Reader.cpp.
References DraftVecUtils::find().
ignorableWhitespace()
void Base::XMLReader::ignorableWhitespace (const XMLCh *const chars, const XMLSize_t length) override protected
Definition at line 570 of file Reader.cpp.
isEndOfDocument()
bool Base::XMLReader::isEndOfDocument () const
return true if the end of the document is reached, false otherwise
Definition at line 246 of file Reader.cpp.
isEndOfElement()
bool Base::XMLReader::isEndOfElement () const
return true if the end of an element is reached, false otherwise
Definition at line 236 of file Reader.cpp.
isRegistered()
bool Base::XMLReader::isRegistered (Base::Persistence * Object) const
Definition at line 482 of file Reader.cpp.
isStartOfDocument()
bool Base::XMLReader::isStartOfDocument () const
return true if the on the start of the document, false otherwise
Definition at line 241 of file Reader.cpp.
isValid()
bool Base::XMLReader::isValid () const inline
Definition at line 152 of file Reader.h.
isVerbose()
bool Base::XMLReader::isVerbose () const inline
Definition at line 156 of file Reader.h.
level()
int Base::XMLReader::level () const
get the current element level
Definition at line 231 of file Reader.cpp.
localName()
const char * Base::XMLReader::localName () const
get the local name of the current Element
Definition at line 106 of file Reader.cpp.
read() [1/2]
bool Base::XMLReader::read () protected
read the next element
Definition at line 154 of file Reader.cpp.
References getIfcElements::parser.
read() [2/2]
std::streamsize Base::XMLReader::read (char_type * s, std::streamsize n)
Definition at line 291 of file Reader.cpp.
References importers.import3DS::read(), and toolbit-attributes::s.
readBinFile()
void Base::XMLReader::readBinFile (const char * filename)
read binary file
Definition at line 374 of file Reader.cpp.
References Base::base64_decode(), and importers.import3DS::read().
readCharacters()
void Base::XMLReader::readCharacters (const char * filename, CharStreamFormat format = CharStreamFormat::Raw)
read until characters are found
Definition at line 278 of file Reader.cpp.
readElement()
void Base::XMLReader::readElement (const char * ElementName = nullptr)
read until a start element is found (<name>) or start-end element (<name/>) (with special name if given)
Definition at line 181 of file Reader.cpp.
References importers.import3DS::read().
readEndElement()
void Base::XMLReader::readEndElement (const char * ElementName = nullptr, int level = -1)
read until an end element is found
Parameters
ElementName optional end element name to look for. If given, then the parser will read until this name is found.
level optional level to look for. If given, then the parser will read until this level. Note that the parse only increase the level when finding a start element, not start-end element, and decrease the level after finding an end element. So, if you obtain the parser level after calling readElement(), you should specify a level minus one when calling this function. This level parameter is only useful if you know the child element may have the same name as its parent, otherwise, using ElementName is enough.
Definition at line 251 of file Reader.cpp.
References level(), and importers.import3DS::read().
Referenced by Part::Box::Restore().
readFiles()
void Base::XMLReader::readFiles (zipios::ZipInputStream & zipstream) const
process the requested file writes
Definition at line 394 of file Reader.cpp.
References Base::Console(), Base::ConsoleSingleton::Error(), Base::SequencerLauncher::next(), and TechDrawTools.TaskFillTemplateFields::reader.
Referenced by Gui::MergeDocuments::importObject(), and App::MergeDocuments::importObject().
readNextElement()
bool Base::XMLReader::readNextElement ()
Read in the next element. Return true if it succeeded and false otherwise.
Definition at line 206 of file Reader.cpp.
References importers.import3DS::read().
resetDocument()
void Base::XMLReader::resetDocument () override protected
Definition at line 575 of file Reader.cpp.
resetErrors()
void Base::XMLReader::resetErrors () override protected
Definition at line 614 of file Reader.cpp.
setPartialRestore()
void Base::XMLReader::setPartialRestore (bool on)
sets simultaneously the global and local PartialRestore bits
Definition at line 627 of file Reader.cpp.
setStatus()
void Base::XMLReader::setStatus (ReaderStatus pos, bool on)
set the status bits
Definition at line 622 of file Reader.cpp.
References RobotExample::pos.
setVerbose()
void Base::XMLReader::setVerbose (bool on) inline
Definition at line 160 of file Reader.h.
startCDATA()
void Base::XMLReader::startCDATA () override protected
Definition at line 553 of file Reader.cpp.
startDocument()
void Base::XMLReader::startDocument () override protected
Definition at line 511 of file Reader.cpp.
startElement()
void Base::XMLReader::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const Attributes & attrs) override protected
Definition at line 521 of file Reader.cpp.
References StrX::c_str(), StrXUTF8::c_str(), and SplineSurface::i.
testStatus()
bool Base::XMLReader::testStatus (ReaderStatus pos) const
return the status bits
Definition at line 617 of file Reader.cpp.
References RobotExample::pos.
warning()
void Base::XMLReader::warning (const SAXParseException & exc) override protected
Definition at line 605 of file Reader.cpp.
References SCL.SimpleDataTypes::e.
Member Data Documentation
DocumentSchema
int Base::XMLReader::DocumentSchema {0}
Schema Version of the document.
Definition at line 265 of file Reader.h.
FileList
std::vector<FileEntry> Base::XMLReader::FileList
Definition at line 364 of file Reader.h.
Referenced by readFiles().
FileVersion
int Base::XMLReader::FileVersion {0}
Version of the file format.
Definition at line 269 of file Reader.h.
Referenced by readFiles().
ProgramVersion
std::string Base::XMLReader::ProgramVersion
Version of FreeCAD that wrote this document.
Definition at line 267 of file Reader.h.
The documentation for this class was generated from the following files:
Reader.h
Reader.cpp