FreeCAD: StartGui::ThemeSelectorWidget Class Reference
StartGui::ThemeSelectorWidget Class Reference
A widget to allow selection of the UI theme (color scheme).
#include <ThemeSelectorWidget.h>
Public Member Functions
ThemeSelectorWidget (QWidget *parent=nullptr)
bool eventFilter (QObject *object, QEvent *event) override
Protected Member Functions
void themeChanged (Theme newTheme)
Detailed Description
A widget to allow selection of the UI theme (color scheme).
Definition at line 45 of file ThemeSelectorWidget.h.
Constructor & Destructor Documentation
ThemeSelectorWidget()
ThemeSelectorWidget::ThemeSelectorWidget (QWidget * parent = nullptr) explicit
Definition at line 93 of file ThemeSelectorWidget.cpp.
Member Function Documentation
eventFilter()
bool ThemeSelectorWidget::eventFilter (QObject * object, QEvent * event) override
Definition at line 228 of file ThemeSelectorWidget.cpp.
themeChanged()
void ThemeSelectorWidget::themeChanged (Theme newTheme) protected
Definition at line 201 of file ThemeSelectorWidget.cpp.
References StartGui::Classic, StartGui::Dark, App::GetApplication(), App::Application::GetParameterGroupByPath(), ParameterGrp::GetUnsigned(), Gui::Application::Instance, StartGui::Light, Gui::Application::prefPackManager(), and ParameterGrp::SetUnsigned().
The documentation for this class was generated from the following files:
ThemeSelectorWidget.h
ThemeSelectorWidget.cpp