FreeCAD: SketcherGui::SketcherSettingsAppearance Class Reference
SketcherGui::SketcherSettingsAppearance Class Reference
#include <SketcherSettings.h>
Public Member Functions
SketcherSettingsAppearance (QWidget *parent=nullptr)
~SketcherSettingsAppearance () override
void saveSettings () override
void loadSettings () override
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Protected Member Functions
void changeEvent (QEvent *e) override
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void resetSettingsToDefaults ()
Detailed Description
The SketcherSettings class implements a preference page to change sketcher settings.
Author
Werner Mayer
Definition at line 133 of file SketcherSettings.h.
Constructor & Destructor Documentation
SketcherSettingsAppearance()
SketcherSettingsAppearance::SketcherSettingsAppearance (QWidget * parent = nullptr) explicit
Definition at line 505 of file SketcherSettings.cpp.
References binaryPatternToDashPattern(), and getPenStyles().
~SketcherSettingsAppearance()
SketcherSettingsAppearance::~SketcherSettingsAppearance () override
Destroys the object and frees any allocated resources
Definition at line 542 of file SketcherSettings.cpp.
Member Function Documentation
changeEvent()
void SketcherSettingsAppearance::changeEvent (QEvent * e) override protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
Definition at line 660 of file SketcherSettings.cpp.
References SCL.SimpleDataTypes::e.
loadSettings()
void SketcherSettingsAppearance::loadSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 596 of file SketcherSettings.cpp.
References App::GetApplication(), ParameterGrp::GetInt(), and App::Application::GetParameterGroupByPath().
saveSettings()
void SketcherSettingsAppearance::saveSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 547 of file SketcherSettings.cpp.
References App::GetApplication(), App::Application::GetParameterGroupByPath(), and ParameterGrp::SetInt().
The documentation for this class was generated from the following files:
SketcherSettings.h
SketcherSettings.cpp