FreeCAD: App::OriginGroupExtension Class Reference
App::OriginGroupExtension Class Reference
#include <OriginGroupExtension.h>
Public Member Functions
OriginGroupExtension ()
~OriginGroupExtension () override
App::Origin * getOrigin () const
Returns the origin link or throws an exception.
virtual const char * getViewProviderName () const
returns the type name of the ViewProvider
short extensionMustExecute () override
Returns true on changing OriginFeature set.
void relinkToOrigin (App::DocumentObject *obj)
std::vector< DocumentObject * > addObjects (std::vector< DocumentObject * > obj) override
bool hasObject (const DocumentObject *obj, bool recursive=false) const override
bool extensionGetSubObject (DocumentObject *&ret, const char *subname, PyObject **pyObj, Base::Matrix4D *mat, bool transform, int depth) const override
void extensionOnChanged (const Property *p) override
Public Member Functions inherited from App::GeoFeatureGroupExtension
PropertyPlacement & placement ()
void initExtension (ExtensionContainer *obj) override
virtual void transformPlacement (const Base::Placement &transform)
transformPlacement applies transform to placement of this shape. Override this function to propagate the change of placement to base features.
GeoFeatureGroupExtension ()
Constructor.
~GeoFeatureGroupExtension () override
Base::Placement globalGroupPlacement ()
Calculates the global placement of this group.
bool extensionGetSubObjects (std::vector< std::string > &ret, int reason) const override
std::vector< DocumentObject * > removeObjects (std::vector< DocumentObject * > obj) override
Public Member Functions inherited from App::GroupExtension
GroupExtension ()
Constructor.
~GroupExtension () override
virtual DocumentObject * addObject (const char *sType, const char *pObjectName)
virtual std::vector< DocumentObject * > addObject (DocumentObject *obj)
virtual std::vector< DocumentObject * > setObjects (std::vector< DocumentObject * > obj)
virtual bool allowObject (DocumentObject *)
virtual std::vector< DocumentObject * > removeObject (DocumentObject *obj)
virtual void removeObjectsFromDocument ()
DocumentObject * getObject (const char *Name) const
bool isChildOf (const GroupExtension *group, bool recursive=true) const
const std::vector< DocumentObject * > & getObjects () const
std::vector< DocumentObject * > getObjectsOfType (const Base::Type &typeId) const
int countObjectsOfType (const Base::Type &typeId) const
PyObject * getExtensionPyObject () override
bool extensionGetSubObjects (std::vector< std::string > &ret, int reason) const override
std::vector< DocumentObject * > getAllChildren () const
void getAllChildren (std::vector< DocumentObject * > &, std::set< DocumentObject * > &) const
Public Member Functions inherited from App::DocumentObjectExtension
virtual Base::Type getExtensionTypeId (void) const override
DocumentObjectExtension ()
~DocumentObjectExtension () override
App::DocumentObject * getExtendedObject ()
const App::DocumentObject * getExtendedObject () const
virtual void onExtendedSettingDocument ()
get called after setting the document
virtual void onExtendedDocumentRestored ()
get called after a document has been fully restored
virtual const char * getViewProviderExtensionName () const
virtual bool extensionGetLinkedObject (DocumentObject *&ret, bool recursive, Base::Matrix4D *mat, bool transform, int depth) const
virtual int extensionSetElementVisible (const char *, bool)
virtual int extensionIsElementVisible (const char *)
virtual bool extensionHasChildElement () const
Public Member Functions inherited from App::Extension
Extension ()=default
virtual ~Extension ()
App::ExtensionContainer * getExtendedContainer ()
const App::ExtensionContainer * getExtendedContainer () const
std::string name () const
bool isPythonExtension ()
virtual Property * extensionGetPropertyByName (const char *name) const
find a property by its name
virtual const char * extensionGetPropertyName (const Property *prop) const
get the name of a property
virtual void extensionGetPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual void extensionGetPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual short extensionGetPropertyType (const Property *prop) const
get the Type of a Property
virtual short extensionGetPropertyType (const char *name) const
get the Type of a named Property
virtual const char * extensionGetPropertyGroup (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * extensionGetPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual void extensionSave (Base::Writer &) const
virtual void extensionRestore (Base::XMLReader &)
bool extensionIsDerivedFrom (const Base::Type type) const
Static Public Member Functions
static DocumentObject * getGroupOfObject (const DocumentObject *obj)
Static Public Member Functions inherited from App::GeoFeatureGroupExtension
static DocumentObject * getGroupOfObject (const DocumentObject *obj)
static bool isNonGeoGroup (const DocumentObject *obj)
Returns true if the given DocumentObject is DocumentObjectGroup but not GeoFeatureGroup.
static std::vector< App::DocumentObject * > getCSRelevantLinks (const App::DocumentObject *obj)
static bool areLinksValid (const App::DocumentObject *obj)
static bool isLinkValid (App::Property *link)
static void getInvalidLinkObjects (const App::DocumentObject *obj, std::vector< App::DocumentObject * > &vec)
Static Public Member Functions inherited from App::GroupExtension
static DocumentObject * getGroupOfObject (const DocumentObject *obj)
Static Public Member Functions inherited from App::DocumentObjectExtension
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Static Public Member Functions inherited from App::Extension
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Public Attributes
PropertyLink Origin
Origin linked to the group.
Public Attributes inherited from App::GroupExtension
PropertyLinkList Group
Properties.
PropertyBool _GroupTouched
Protected Member Functions
App::DocumentObjectExecReturn * extensionExecute () override
Checks integrity of the Origin.
void onExtendedSetupObject () override
Creates the corresponding Origin object.
void onExtendedUnsetupObject () override
Removes all planes and axis if they are still linked to the document.
Protected Member Functions inherited from App::DocumentObjectExtension
virtual const App::PropertyData & extensionGetPropertyData (void) const override
Protected Member Functions inherited from App::Extension
virtual bool extensionHandleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
returns true if the property name change was handled by the extension.
virtual bool extensionHandleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop)
returns true if the property type change was handled by the extension.
void initExtensionType (Base::Type type)
Additional Inherited Members
Static Protected Member Functions inherited from App::DocumentObjectExtension
static const App::PropertyData * extensionGetPropertyDataPtr (void)
Static Protected Member Functions inherited from App::Extension
static const App::PropertyData * extensionGetPropertyDataPtr (void)
static void initExtensionSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Base::Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Extension
bool m_isPythonExtension = false
Py::SmartPtr ExtensionPythonObject
Detailed Description
Represents an abstract placeable group of objects with an associated Origin
Definition at line 56 of file OriginGroupExtension.h.
Constructor & Destructor Documentation
OriginGroupExtension()
OriginGroupExtension::OriginGroupExtension ()
Definition at line 41 of file OriginGroupExtension.cpp.
References EXTENSION_ADD_PROPERTY_TYPE, and App::Prop_Hidden.
~OriginGroupExtension()
OriginGroupExtension::~OriginGroupExtension () override default
Member Function Documentation
addObjects()
std::vector< DocumentObject * > OriginGroupExtension::addObjects (std::vector< DocumentObject * > obj) override virtual
Reimplemented from App::GeoFeatureGroupExtension.
Definition at line 293 of file OriginGroupExtension.cpp.
References App::GeoFeatureGroupExtension::addObjects(), replaceobj::objs, and relinkToOrigin().
extensionExecute()
App::DocumentObjectExecReturn * OriginGroupExtension::extensionExecute () override protected virtual
Checks integrity of the Origin.
Reimplemented from App::GroupExtension.
Definition at line 146 of file OriginGroupExtension.cpp.
References App::GroupExtension::extensionExecute(), getOrigin(), and Base::Exception::what().
extensionGetSubObject()
bool OriginGroupExtension::extensionGetSubObject (DocumentObject *& ret, const char * subname, PyObject ** pyObj, Base::Matrix4D * mat, bool transform, int depth) const override virtual
Get the sub object by name
See also
DocumentObject::getSubObject()
Returns
Return turn if handled, the sub object is returned in ret
Reimplemented from App::GeoFeatureGroupExtension.
Definition at line 77 of file OriginGroupExtension.cpp.
References dot(), App::GeoFeatureGroupExtension::extensionGetSubObject(), App::DocumentObject::getNameInDocument(), App::DocumentObject::getSubObject(), App::PropertyPlacement::getValue(), App::PropertyString::getValue(), App::DocumentObject::isAttachedToDocument(), App::DocumentObject::Label, App::GeoFeatureGroupExtension::placement(), and Base::Placement::toMatrix().
extensionMustExecute()
short OriginGroupExtension::extensionMustExecute () override virtual
Returns true on changing OriginFeature set.
Reimplemented from App::DocumentObjectExtension.
Definition at line 136 of file OriginGroupExtension.cpp.
References App::DocumentObjectExtension::extensionMustExecute(), and App::DocumentObject::isTouched().
extensionOnChanged()
void OriginGroupExtension::extensionOnChanged (const Property * p) override virtual
Reimplemented from App::GeoFeatureGroupExtension.
Definition at line 189 of file OriginGroupExtension.cpp.
References App::GeoFeatureGroupExtension::extensionOnChanged(), FC_WARN, App::DocumentObject::getDocument(), App::DocumentObjectExtension::getExtendedObject(), App::DocumentObjectExtension::getExtensionClassTypeId(), App::DocumentObject::getFullName(), App::DocumentObject::getInList(), App::Document::Importing, src.Mod.Test.testPathArray::o, buildPsets::p, App::Document::Restoring, and App::Document::testStatus().
getGroupOfObject()
App::DocumentObject * OriginGroupExtension::getGroupOfObject (const DocumentObject * obj) static
Returns the origin group which contains this object. In case this object is not part of any geoFeatureGroup, 0 is returned.
Parameters
obj the object to search for
Definition at line 110 of file OriginGroupExtension.cpp.
References Base::Persistence::getClassTypeId(), App::DocumentObjectExtension::getExtensionClassTypeId(), App::DocumentObject::getInList(), Base::BaseClass::isDerivedFrom(), src.Mod.Test.testPathArray::o, and result.
Referenced by App::GeoFeatureGroupExtension::getGroupOfObject().
getOrigin()
App::Origin * OriginGroupExtension::getOrigin () const
Returns the origin link or throws an exception.
Definition at line 56 of file OriginGroupExtension.cpp.
References Base::Persistence::getClassTypeId(), App::DocumentObjectExtension::getExtendedObject(), App::DocumentObject::getFullName(), Base::Type::getName(), Base::Persistence::getTypeId(), and Base::BaseClass::isDerivedFrom().
Referenced by extensionExecute(), PartDesignGui::TaskRevolutionParameters::fillAxisCombo(), PartDesignGui::TaskTransformedParameters::fillAxisCombo(), PartDesignGui::TaskTransformedParameters::fillPlanesCombo(), PartDesignGui::fixSketchSupport(), hasObject(), relinkToOrigin(), PartDesignGui::relinkToOrigin(), PartDesignGui::TaskHelixParameters::~TaskHelixParameters(), PartDesignGui::TaskLinearPatternParameters::~TaskLinearPatternParameters(), PartDesignGui::TaskMirroredParameters::~TaskMirroredParameters(), and PartDesignGui::TaskPolarPatternParameters::~TaskPolarPatternParameters().
getViewProviderName()
virtual const char* App::OriginGroupExtension::getViewProviderName () const inline virtual
returns the type name of the ViewProvider
Reimplemented in App::Part, Assembly::AssemblyObject, Assembly::AssemblyLink, and PartDesign::Body.
Definition at line 69 of file OriginGroupExtension.h.
hasObject()
bool OriginGroupExtension::hasObject (const DocumentObject * obj, bool recursive = false) const override virtual
Checks whether the object obj is part of this group.
Parameters
obj the object to check for.
recursive if true check also if the obj is child of some sub group (default is false).
Reimplemented from App::GroupExtension.
Definition at line 303 of file OriginGroupExtension.cpp.
References getOrigin(), and App::GroupExtension::hasObject().
Referenced by PartDesignGui::getBodyFor(), Assembly::AssemblyObject::getExplodedViewGroup(), Assembly::AssemblyObject::getGroup(), PartDesign::Body::getNextSolidFeature(), PartDesign::Body::getPrevSolidFeature(), Assembly::AssemblyObject::getSubAssemblies(), PartDesign::Body::insertObject(), PartDesignGui::Workbench::setupContextMenu(), and validateSketches().
onExtendedSetupObject()
void OriginGroupExtension::onExtendedSetupObject () override protected virtual
Creates the corresponding Origin object.
Reimplemented from App::DocumentObjectExtension.
Definition at line 167 of file OriginGroupExtension.cpp.
References toolbit-attributes::doc, Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), App::DocumentObjectExtension::getExtendedObject(), Base::BaseClass::isDerivedFrom(), and App::DocumentObjectExtension::onExtendedSetupObject().
onExtendedUnsetupObject()
void OriginGroupExtension::onExtendedUnsetupObject () override protected virtual
Removes all planes and axis if they are still linked to the document.
Reimplemented from App::DocumentObjectExtension.
Definition at line 179 of file OriginGroupExtension.cpp.
References App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), App::DocumentObject::isRemoving(), App::DocumentObjectExtension::onExtendedUnsetupObject(), and App::Document::removeObject().
relinkToOrigin()
void OriginGroupExtension::relinkToOrigin (App::DocumentObject * obj)
Definition at line 218 of file OriginGroupExtension.cpp.
References App::LocalCoordinateSystem::getDatumElement(), getOrigin(), App::ExtensionContainer::getPropertyList(), App::PropertyString::getValue(), src.Mod.Test.testPathArray::o, buildPsets::p, result, App::DatumElement::Role, TestSpreadsheet::v, and SurfaceTests.TestBlendCurve::vec.
Referenced by addObjects(), and PartDesign::Body::insertObject().
Member Data Documentation
Origin
PropertyLink App::OriginGroupExtension::Origin
Origin linked to the group.
Definition at line 85 of file OriginGroupExtension.h.
Referenced by Assembly::AssemblyObject::getGroundedParts().
The documentation for this class was generated from the following files:
OriginGroupExtension.h
OriginGroupExtension.cpp