FreeCAD: MeshCore::MeshCleanup Class Reference
MeshCore::MeshCleanup Class Reference
#include <MeshIO.h>
Public Member Functions
MeshCleanup (MeshPointArray &p, MeshFacetArray &f)
Construction.
void SetMaterial (Material *mat)
Set the material array. In case the material array sets the colors per vertex and RemoveInvalids() removes points from the array the material array will be adjusted.
void RemoveInvalids ()
Remove unreferenced and invalid facets.
Detailed Description
The MeshCleanup class is a helper class to remove points from the point array that are not referenced by any facet. It also removes facet with point indices that are out of range.
Definition at line 275 of file MeshIO.h.
Constructor & Destructor Documentation
MeshCleanup()
MeshCleanup::MeshCleanup (MeshPointArray & p, MeshFacetArray & f)
Construction.
Parameters
p – the point array
f – the facet array
Definition at line 2778 of file MeshIO.cpp.
Member Function Documentation
RemoveInvalids()
void MeshCleanup::RemoveInvalids ()
Remove unreferenced and invalid facets.
Definition at line 2788 of file MeshIO.cpp.
References MeshCore::MeshPoint::INVALID, MeshCore::MeshPointArray::ResetInvalid(), and MeshCore::MeshPointArray::SetFlag().
Referenced by MeshCore::MeshKernel::Cleanup(), MeshCore::ReaderOBJ::Load(), MeshCore::MeshInput::LoadInventor(), MeshCore::MeshInput::LoadMeshNode(), MeshCore::MeshInput::LoadOFF(), and MeshCore::MeshInput::LoadSMF().
SetMaterial()
void MeshCleanup::SetMaterial (Material * mat)
Set the material array. In case the material array sets the colors per vertex and RemoveInvalids() removes points from the array the material array will be adjusted.
Definition at line 2783 of file MeshIO.cpp.
Referenced by MeshCore::ReaderOBJ::Load(), and MeshCore::MeshInput::LoadOFF().
The documentation for this class was generated from the following files:
MeshIO.h
MeshIO.cpp