FreeCAD: MeshCore::MeshSurfaceSegment Class Reference
MeshCore::MeshSurfaceSegment Class Reference abstract
#include <Segmentation.h>
Public Member Functions
MeshSurfaceSegment (unsigned long minFacets)
virtual ~MeshSurfaceSegment ()=default
MeshSurfaceSegment (const MeshSurfaceSegment &)=delete
MeshSurfaceSegment (MeshSurfaceSegment &&)=delete
MeshSurfaceSegment & operator= (const MeshSurfaceSegment &)=delete
MeshSurfaceSegment & operator= (MeshSurfaceSegment &&)=delete
virtual bool TestFacet (const MeshFacet &rclFacet) const =0
virtual const char * GetType () const =0
virtual void Initialize (FacetIndex)
virtual bool TestInitialFacet (FacetIndex) const
virtual void AddFacet (const MeshFacet &rclFacet)
void AddSegment (const std::vector< FacetIndex > &)
const std::vector< MeshSegment > & GetSegments () const
MeshSegment FindSegment (FacetIndex) const
Detailed Description
Definition at line 63 of file Mesh/App/Core/Segmentation.h.
Constructor & Destructor Documentation
MeshSurfaceSegment() [1/3]
MeshCore::MeshSurfaceSegment::MeshSurfaceSegment (unsigned long minFacets) inline explicit
Definition at line 66 of file Mesh/App/Core/Segmentation.h.
~MeshSurfaceSegment()
virtual MeshCore::MeshSurfaceSegment::~MeshSurfaceSegment () virtual default
MeshSurfaceSegment() [2/3]
MeshCore::MeshSurfaceSegment::MeshSurfaceSegment (const MeshSurfaceSegment &) delete
MeshSurfaceSegment() [3/3]
MeshCore::MeshSurfaceSegment::MeshSurfaceSegment (MeshSurfaceSegment &&) delete
Member Function Documentation
AddFacet()
void MeshSurfaceSegment::AddFacet (const MeshFacet & rclFacet) virtual
Reimplemented in MeshCore::MeshDistanceGenericSurfaceFitSegment, and MeshCore::MeshDistancePlanarSegment.
Definition at line 43 of file Mesh/App/Core/Segmentation.cpp.
Referenced by MeshCore::MeshSurfaceVisitor::Visit().
AddSegment()
void MeshSurfaceSegment::AddSegment (const std::vector< FacetIndex > & segm)
Definition at line 46 of file Mesh/App/Core/Segmentation.cpp.
FindSegment()
MeshSegment MeshSurfaceSegment::FindSegment (FacetIndex index) const
Definition at line 53 of file Mesh/App/Core/Segmentation.cpp.
References DraftVecUtils::find().
GetSegments()
const std::vector<MeshSegment>& MeshCore::MeshSurfaceSegment::GetSegments () const inline
Definition at line 82 of file Mesh/App/Core/Segmentation.h.
GetType()
virtual const char* MeshCore::MeshSurfaceSegment::GetType () const pure virtual
Implemented in MeshCore::MeshCurvatureFreeformSegment, MeshCore::MeshCurvatureSphericalSegment, MeshCore::MeshCurvatureCylindricalSegment, MeshCore::MeshCurvaturePlanarSegment, MeshCore::MeshDistanceGenericSurfaceFitSegment, and MeshCore::MeshDistancePlanarSegment.
Initialize()
void MeshSurfaceSegment::Initialize (FacetIndex) virtual
Reimplemented in MeshCore::MeshDistanceGenericSurfaceFitSegment, and MeshCore::MeshDistancePlanarSegment.
Definition at line 35 of file Mesh/App/Core/Segmentation.cpp.
operator=() [1/2]
MeshSurfaceSegment& MeshCore::MeshSurfaceSegment::operator= (const MeshSurfaceSegment &) delete
operator=() [2/2]
MeshSurfaceSegment& MeshCore::MeshSurfaceSegment::operator= (MeshSurfaceSegment &&) delete
TestFacet()
virtual bool MeshCore::MeshSurfaceSegment::TestFacet (const MeshFacet & rclFacet) const pure virtual
Implemented in MeshCore::MeshCurvatureFreeformSegment, MeshCore::MeshCurvatureSphericalSegment, MeshCore::MeshCurvatureCylindricalSegment, MeshCore::MeshCurvaturePlanarSegment, MeshCore::MeshDistanceGenericSurfaceFitSegment, and MeshCore::MeshDistancePlanarSegment.
Referenced by MeshCore::MeshSurfaceVisitor::AllowVisit().
TestInitialFacet()
bool MeshSurfaceSegment::TestInitialFacet (FacetIndex) const virtual
Reimplemented in MeshCore::MeshDistanceGenericSurfaceFitSegment.
Definition at line 38 of file Mesh/App/Core/Segmentation.cpp.
The documentation for this class was generated from the following files:
Mesh/App/Core/Segmentation.h
Mesh/App/Core/Segmentation.cpp