FreeCAD: Points::PcdWriter Class Reference
Points::PcdWriter Class Reference
#include <PointsAlgos.h>
Public Member Functions
PcdWriter (const PointKernel &)
void write (const std::string &filename) override
Public Member Functions inherited from Points::Writer
Writer (const PointKernel &)
virtual ~Writer ()
void setIntensities (const std::vector< float > &)
void setColors (const std::vector< App::Color > &)
void setNormals (const std::vector< Base::Vector3f > &)
void setWidth (int)
void setHeight (int)
void setPlacement (const Base::Placement &)
Writer (const Writer &)=delete
Writer (Writer &&)=delete
Writer & operator= (const Writer &)=delete
Writer & operator= (Writer &&)=delete
Additional Inherited Members
Protected Attributes inherited from Points::Writer
const PointKernel & points
std::vector< float > intensity
std::vector< App::Color > colors
std::vector< Base::Vector3f > normals
int width
int height
Base::Placement placement
Detailed Description
Definition at line 208 of file PointsAlgos.h.
Constructor & Destructor Documentation
PcdWriter()
PcdWriter::PcdWriter (const PointKernel & p) explicit
Definition at line 2023 of file PointsAlgos.cpp.
Member Function Documentation
write()
void PcdWriter::write (const std::string & filename) override virtual
Implements Points::Writer.
Definition at line 2027 of file PointsAlgos.cpp.
References SCL.SimpleDataTypes::c, Points::Writer::colors, Points::PointKernel::getBasicPoints(), Base::Placement::getPosition(), Base::Placement::getRotation(), Points::Writer::height, SplineSurface::i, Points::Writer::intensity, Base::Placement::isIdentity(), Base::Rotation::isIdentity(), Base::Placement::multVec(), Base::Rotation::multVec(), Points::Writer::normals, src.Mod.Test.testPathArray::o, buildPsets::p, Points::Writer::placement, Points::Writer::points, Points::PointKernel::size(), Path.Post.scripts.grbl_post::type, src.Mod.PartDesign.fcgear.svggear::w, Points::Writer::width, MovieTool::x, Base::Vector3< float_type >::x, MovieTool::y, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
The documentation for this class was generated from the following files:
PointsAlgos.h
PointsAlgos.cpp