FreeCAD: Base::ifstream Class Reference
Base::ifstream Class Reference
#include <Stream.h>
Public Member Functions
ifstream ()=default
ifstream (const ifstream &)=delete
ifstream (ifstream &&)=delete
ifstream (const FileInfo &fi, ios_base::openmode mode=std::ios::in)
~ifstream () override=default
void open (const FileInfo &fi, ios_base::openmode mode=std::ios::in)
ifstream & operator= (const ifstream &)=delete
ifstream & operator= (ifstream &&)=delete
Detailed Description
The ofstream class is provided for convenience. On Windows platforms it opens a stream with UCS-2 encoded file name while on Linux platforms the file name is UTF-8 encoded.
Author
Werner Mayer
Definition at line 605 of file Stream.h.
Constructor & Destructor Documentation
ifstream() [1/4]
Base::ifstream::ifstream () default
ifstream() [2/4]
Base::ifstream::ifstream (const ifstream &) delete
ifstream() [3/4]
Base::ifstream::ifstream (ifstream &&) delete
ifstream() [4/4]
Base::ifstream::ifstream (const FileInfo & fi, ios_base::openmode mode = std::ios::in) inline explicit
Definition at line 611 of file Stream.h.
~ifstream()
Base::ifstream::~ifstream () override default
Member Function Documentation
open()
void Base::ifstream::open (const FileInfo & fi, ios_base::openmode mode = std::ios::in) inline
Definition at line 619 of file Stream.h.
References Base::FileInfo::filePath(), AssemblyImport::open(), and Base::FileInfo::toStdWString().
Referenced by TechDraw::PATLineSpec::getPatternList(), and TechDraw::PATLineSpec::getSpecsForPattern().
operator=() [1/2]
ifstream& Base::ifstream::operator= (const ifstream &) delete
operator=() [2/2]
ifstream& Base::ifstream::operator= (ifstream &&) delete
The documentation for this class was generated from the following file:
Stream.h