FreeCAD: TechDraw::CosmeticExtension Class Reference
TechDraw::CosmeticExtension Class Reference
#include <CosmeticExtension.h>
Public Member Functions
CosmeticExtension ()
~CosmeticExtension () override
virtual CosmeticVertex * getCosmeticVertexBySelection (const int i) const
retrieve a cosmetic vertex by index (the 5 in Vertex5)
virtual CosmeticVertex * getCosmeticVertexBySelection (const std::string &name) const
virtual CosmeticVertex * getCosmeticVertex (const std::string &tag) const
retrieve a cosmetic vertex by unique id
virtual int add1CVToGV (const std::string &tag)
add a single cosmetic vertex in the property list to the view's vertex geometry list
virtual int getCVIndex (const std::string &tag)
find the position of a cosmetic vertex with the given tag in the parent view's geometry list
virtual std::string addCosmeticVertex (const Base::Vector3d &pos, bool invert=true)
virtual void addCosmeticVertexesToGeom ()
add the cosmetic verts in the property list to view's vertex geometry list
virtual void clearCosmeticVertexes ()
remove all the cosmetic vertices in the property list
virtual void refreshCVGeoms ()
update the parent view's vertex geometry with all the cosmetic vertices in the list property
virtual void removeCosmeticVertex (const std::string &tag)
remove the cosmetic vertex with the given tag from the list property
virtual void removeCosmeticVertex (const std::vector< std::string > &tags)
remove the cosmetic vertices with the given tags from the list property
virtual std::string addCosmeticEdge (Base::Vector3d start, Base::Vector3d end)
virtual std::string addCosmeticEdge (TechDraw::BaseGeomPtr bg)
virtual CosmeticEdge * getCosmeticEdgeBySelection (const std::string &name) const
virtual CosmeticEdge * getCosmeticEdgeBySelection (int i) const
find the cosmetic edge corresponding to the input parameter (the 5 in Edge5)
virtual CosmeticEdge * getCosmeticEdge (const std::string &id) const
retrieve a CE by unique id
virtual void removeCosmeticEdge (const std::string &tag)
remove the cosmetic edge with the given tag from the list property
virtual void removeCosmeticEdge (const std::vector< std::string > &delTags)
remove the cosmetic edges with the given tags from the list property
virtual void clearCosmeticEdges ()
remove all the cosmetic edges for this view
virtual int add1CEToGE (const std::string &tag)
add a single cosmetic edge to the geometry edge list
virtual void addCosmeticEdgesToGeom ()
add the cosmetic edges to geometry edge list
virtual void refreshCEGeoms ()
update Edge geometry with current CE's
virtual void refreshCLGeoms ()
virtual void addCenterLinesToGeom ()
virtual int add1CLToGE (const std::string &tag)
virtual std::string addCenterLine (Base::Vector3d start, Base::Vector3d end)
virtual std::string addCenterLine (TechDraw::CenterLine *cl)
virtual std::string addCenterLine (TechDraw::BaseGeomPtr bg)
virtual CenterLine * getCenterLineBySelection (const std::string &name) const
virtual CenterLine * getCenterLineBySelection (int i) const
virtual CenterLine * getCenterLine (const std::string &tag) const
virtual void removeCenterLine (const std::string &tag)
virtual void removeCenterLine (const std::vector< std::string > &delTags)
virtual void clearCenterLines ()
virtual std::string addGeomFormat (TechDraw::GeomFormat *gf)
virtual GeomFormat * getGeomFormatBySelection (const std::string &name) const
virtual GeomFormat * getGeomFormatBySelection (int i) const
virtual GeomFormat * getGeomFormat (const std::string &id) const
virtual void removeGeomFormat (const std::string &tag)
virtual void clearGeomFormats ()
void deleteCosmeticElements (std::vector< std::string > removables)
remove cosmetic elements for a list of subelement names
TechDraw::DrawViewPart * getOwner ()
get a pointer to the parent view
PyObject * getExtensionPyObject () override
Public Member Functions inherited from App::DocumentObjectExtension
virtual Base::Type getExtensionTypeId (void) const override
DocumentObjectExtension ()
~DocumentObjectExtension () override
App::DocumentObject * getExtendedObject ()
const App::DocumentObject * getExtendedObject () const
virtual short extensionMustExecute ()
virtual App::DocumentObjectExecReturn * extensionExecute ()
virtual void onExtendedSettingDocument ()
get called after setting the document
virtual void onExtendedDocumentRestored ()
get called after a document has been fully restored
virtual void onExtendedSetupObject ()
get called after a brand new object was created
virtual void onExtendedUnsetupObject ()
get called when object is going to be removed from the document
virtual const char * getViewProviderExtensionName () const
virtual bool extensionGetSubObject (DocumentObject *&ret, const char *subname, PyObject **pyObj, Base::Matrix4D *mat, bool transform, int depth) const
virtual bool extensionGetSubObjects (std::vector< std::string > &ret, int reason) const
virtual bool extensionGetLinkedObject (DocumentObject *&ret, bool recursive, Base::Matrix4D *mat, bool transform, int depth) const
virtual int extensionSetElementVisible (const char *, bool)
virtual int extensionIsElementVisible (const char *)
virtual bool extensionHasChildElement () const
Public Member Functions inherited from App::Extension
Extension ()=default
virtual ~Extension ()
virtual void initExtension (App::ExtensionContainer *obj)
App::ExtensionContainer * getExtendedContainer ()
const App::ExtensionContainer * getExtendedContainer () const
std::string name () const
bool isPythonExtension ()
virtual Property * extensionGetPropertyByName (const char *name) const
find a property by its name
virtual const char * extensionGetPropertyName (const Property *prop) const
get the name of a property
virtual void extensionGetPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual void extensionGetPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual short extensionGetPropertyType (const Property *prop) const
get the Type of a Property
virtual short extensionGetPropertyType (const char *name) const
get the Type of a named Property
virtual const char * extensionGetPropertyGroup (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * extensionGetPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual void extensionSave (Base::Writer &) const
virtual void extensionRestore (Base::XMLReader &)
bool extensionIsDerivedFrom (const Base::Type type) const
Public Attributes
TechDraw::PropertyCosmeticVertexList CosmeticVertexes
TechDraw::PropertyCosmeticEdgeList CosmeticEdges
TechDraw::PropertyCenterLineList CenterLines
TechDraw::PropertyGeomFormatList GeomFormats
Additional Inherited Members
Static Public Member Functions inherited from App::DocumentObjectExtension
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Static Public Member Functions inherited from App::Extension
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Protected Member Functions inherited from App::DocumentObjectExtension
virtual const App::PropertyData & extensionGetPropertyData (void) const override
Protected Member Functions inherited from App::Extension
virtual void extensionOnChanged (const Property *p)
virtual bool extensionHandleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
returns true if the property name change was handled by the extension.
virtual bool extensionHandleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop)
returns true if the property type change was handled by the extension.
void initExtensionType (Base::Type type)
Static Protected Member Functions inherited from App::DocumentObjectExtension
static const App::PropertyData * extensionGetPropertyDataPtr (void)
Static Protected Member Functions inherited from App::Extension
static const App::PropertyData * extensionGetPropertyDataPtr (void)
static void initExtensionSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Base::Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Extension
bool m_isPythonExtension = false
Py::SmartPtr ExtensionPythonObject
Detailed Description
Definition at line 62 of file CosmeticExtension.h.
Constructor & Destructor Documentation
CosmeticExtension()
CosmeticExtension::CosmeticExtension ()
Definition at line 41 of file CosmeticExtension.cpp.
References EXTENSION_ADD_PROPERTY_TYPE, App::DocumentObjectExtension::getExtensionClassTypeId(), and App::Prop_Output.
~CosmeticExtension()
CosmeticExtension::~CosmeticExtension () override
Definition at line 53 of file CosmeticExtension.cpp.
Member Function Documentation
add1CEToGE()
int CosmeticExtension::add1CEToGE (const std::string & tag) virtual
add a single cosmetic edge to the geometry edge list
Definition at line 308 of file CosmeticExtension.cpp.
References Base::Console(), Base::ConsoleSingleton::Message(), TechDraw::CosmeticEdge::scaledAndRotatedGeometry(), and Dice3DS.dom3ds::tag.
Referenced by TechDrawGui::TaskCosmeticCircle::accept(), and TechDrawGui::TaskCosmeticLine::accept().
add1CLToGE()
int CosmeticExtension::add1CLToGE (const std::string & tag) virtual
Definition at line 449 of file CosmeticExtension.cpp.
References TechDraw::CenterLine::scaledAndRotatedGeometry(), and Dice3DS.dom3ds::tag.
add1CVToGV()
int CosmeticExtension::add1CVToGV (const std::string & tag) virtual
add a single cosmetic vertex in the property list to the view's vertex geometry list
Definition at line 128 of file CosmeticExtension.cpp.
References Base::Console(), TechDraw::CosmeticVertex::getTagAsString(), TechDraw::CosmeticVertex::linkGeom, Base::ConsoleSingleton::Message(), TechDraw::CosmeticVertex::rotatedAndScaled(), and Dice3DS.dom3ds::tag.
Referenced by TechDraw::DrawDimHelper::makeDistDim().
addCenterLine() [1/3]
std::string CosmeticExtension::addCenterLine (Base::Vector3d start, Base::Vector3d end) virtual
Definition at line 496 of file CosmeticExtension.cpp.
References TechDraw::CenterLine::getTagAsString().
Referenced by TechDrawGui::TaskCenterLine::createCenterLine().
addCenterLine() [2/3]
std::string CosmeticExtension::addCenterLine (TechDraw::BaseGeomPtr bg) virtual
Definition at line 519 of file CosmeticExtension.cpp.
References TechDraw::CenterLine::getTagAsString().
addCenterLine() [3/3]
std::string CosmeticExtension::addCenterLine (TechDraw::CenterLine * cl) virtual
Definition at line 509 of file CosmeticExtension.cpp.
References TechDraw::CenterLine::getTagAsString().
addCenterLinesToGeom()
void CosmeticExtension::addCenterLinesToGeom () virtual
Definition at line 479 of file CosmeticExtension.cpp.
References Base::Console(), and Base::ConsoleSingleton::Error().
Referenced by TechDraw::DrawViewPart::postFaceExtractionTasks().
addCosmeticEdge() [1/2]
std::string CosmeticExtension::addCosmeticEdge (Base::Vector3d start, Base::Vector3d end) virtual
adds a new cosmetic edge to the list property. does not add to display geometry until dvp executes. returns unique CE id
Definition at line 341 of file CosmeticExtension.cpp.
References TechDraw::CosmeticEdge::getTagAsString().
Referenced by TechDrawGui::_createThreadCircle(), TechDrawGui::_createThreadLines(), TechDrawGui::TaskCosmeticCircle::createCosmeticCircle(), TechDrawGui::TaskCosmeticLine::createCosmeticLine(), and TechDrawGui::execHoleCircle().
addCosmeticEdge() [2/2]
std::string CosmeticExtension::addCosmeticEdge (TechDraw::BaseGeomPtr bg) virtual
adds a new cosmetic edge to the list property. does not add to display geometry until dvp executes. returns unique CE id
Definition at line 354 of file CosmeticExtension.cpp.
References TechDraw::CosmeticEdge::getTagAsString().
addCosmeticEdgesToGeom()
void CosmeticExtension::addCosmeticEdgesToGeom () virtual
add the cosmetic edges to geometry edge list
Definition at line 292 of file CosmeticExtension.cpp.
Referenced by TechDraw::DrawViewPart::postHlrTasks().
addCosmeticVertex()
std::string CosmeticExtension::addCosmeticVertex (const Base::Vector3d & pos, bool invert = true) virtual
adds a cosmetic vertex to the property list. does not add to display geometry until dvp executes. returns unique CV id. if the pos parameter is in real world coordinates, then invert should be true (the default). if pos is in TD geometry or scene coordinates, then it is already inverted, and invert should be set to false.
Definition at line 196 of file CosmeticExtension.cpp.
References TechDraw::CosmeticVertex::getTagAsString(), draftgeoutils.edges::invert(), TechDraw::DrawUtil::invertY(), and RobotExample::pos.
Referenced by TechDrawGui::TaskCosVertex::addCosVertex(), execMidpoints(), execQuadrants(), and TechDraw::DrawDimHelper::makeDistDim().
addCosmeticVertexesToGeom()
void CosmeticExtension::addCosmeticVertexesToGeom () virtual
add the cosmetic verts in the property list to view's vertex geometry list
Definition at line 114 of file CosmeticExtension.cpp.
Referenced by TechDraw::DrawViewPart::postHlrTasks().
addGeomFormat()
std::string CosmeticExtension::addGeomFormat (TechDraw::GeomFormat * gf) virtual
Definition at line 607 of file CosmeticExtension.cpp.
References TechDraw::GeomFormat::getTagAsString().
Referenced by TechDrawGui::TaskLineDecor::getFormatAccessPtr().
clearCenterLines()
void CosmeticExtension::clearCenterLines () virtual
Definition at line 439 of file CosmeticExtension.cpp.
clearCosmeticEdges()
void CosmeticExtension::clearCosmeticEdges () virtual
remove all the cosmetic edges for this view
Definition at line 281 of file CosmeticExtension.cpp.
clearCosmeticVertexes()
void CosmeticExtension::clearCosmeticVertexes () virtual
remove all the cosmetic vertices in the property list
Definition at line 103 of file CosmeticExtension.cpp.
clearGeomFormats()
void CosmeticExtension::clearGeomFormats () virtual
Definition at line 595 of file CosmeticExtension.cpp.
References SCL.SimpleDataTypes::f.
deleteCosmeticElements()
void CosmeticExtension::deleteCosmeticElements (std::vector< std::string > removables)
remove cosmetic elements for a list of subelement names
Definition at line 66 of file CosmeticExtension.cpp.
References TechDraw::DrawUtil::getGeomTypeFromName(), TechDraw::CosmeticVertex::getTagAsString(), TechDraw::CenterLine::getTagAsString(), TechDraw::DrawUtil::isCenterLine(), TechDraw::DrawUtil::isCosmeticEdge(), and TechDraw::DrawUtil::isCosmeticVertex().
getCenterLine()
TechDraw::CenterLine * CosmeticExtension::getCenterLine (const std::string & tag) const virtual
Definition at line 530 of file CosmeticExtension.cpp.
References TechDraw::CenterLine::getTagAsString().
Referenced by TechDrawGui::TaskCenterLine::TaskCenterLine().
getCenterLineBySelection() [1/2]
TechDraw::CenterLine * CosmeticExtension::getCenterLineBySelection (const std::string & name) const virtual
Definition at line 545 of file CosmeticExtension.cpp.
References TechDraw::DrawViewPart::getGeomByIndex(), and TechDraw::DrawUtil::getIndexFromName().
Referenced by exec2LineCenterLine(), exec2PointCenterLine(), execCenterLine(), and TechDrawGui::TaskLineDecor::getFormatAccessPtr().
getCenterLineBySelection() [2/2]
TechDraw::CenterLine * CosmeticExtension::getCenterLineBySelection (int i) const virtual
Definition at line 562 of file CosmeticExtension.cpp.
References SplineSurface::i.
getCosmeticEdge()
TechDraw::CosmeticEdge * CosmeticExtension::getCosmeticEdge (const std::string & id) const virtual
retrieve a CE by unique id
Definition at line 365 of file CosmeticExtension.cpp.
Referenced by TechDrawGui::_createThreadCircle(), TechDrawGui::_createThreadLines(), TechDrawGui::TaskCosmeticCircle::createCosmeticCircle(), TechDrawGui::TaskCosmeticLine::createCosmeticLine(), and TechDrawGui::execHoleCircle().
getCosmeticEdgeBySelection() [1/2]
TechDraw::CosmeticEdge * CosmeticExtension::getCosmeticEdgeBySelection (const std::string & name) const virtual
find the cosmetic edge corresponding to selection name (Edge5) used when selecting
Definition at line 383 of file CosmeticExtension.cpp.
References TechDraw::DrawViewPart::getGeomByIndex(), and TechDraw::DrawUtil::getIndexFromName().
Referenced by execCosmeticCircle(), execLine2Points(), TechDrawGui::TaskLineDecor::getFormatAccessPtr(), TechDrawGui::TaskCosmeticCircle::TaskCosmeticCircle(), and TechDrawGui::TaskCosmeticLine::TaskCosmeticLine().
getCosmeticEdgeBySelection() [2/2]
TechDraw::CosmeticEdge * CosmeticExtension::getCosmeticEdgeBySelection (int i) const virtual
find the cosmetic edge corresponding to the input parameter (the 5 in Edge5)
Definition at line 401 of file CosmeticExtension.cpp.
References SplineSurface::i.
getCosmeticVertex()
TechDraw::CosmeticVertex * CosmeticExtension::getCosmeticVertex (const std::string & tag) const virtual
retrieve a cosmetic vertex by unique id
Definition at line 212 of file CosmeticExtension.cpp.
References TechDraw::CosmeticVertex::getTagAsString().
getCosmeticVertexBySelection() [1/2]
TechDraw::CosmeticVertex * CosmeticExtension::getCosmeticVertexBySelection (const int i) const virtual
retrieve a cosmetic vertex by index (the 5 in Vertex5)
Definition at line 244 of file CosmeticExtension.cpp.
References SplineSurface::i.
getCosmeticVertexBySelection() [2/2]
TechDraw::CosmeticVertex * CosmeticExtension::getCosmeticVertexBySelection (const std::string & name) const virtual
retrieve a cosmetic vertex by selection name (Vertex5) used when selecting
Definition at line 227 of file CosmeticExtension.cpp.
References TechDraw::DrawUtil::getIndexFromName(), TechDraw::DrawViewPart::getProjVertexByIndex(), and TestSpreadsheet::v.
getCVIndex()
int CosmeticExtension::getCVIndex (const std::string & tag) virtual
find the position of a cosmetic vertex with the given tag in the parent view's geometry list
Definition at line 162 of file CosmeticExtension.cpp.
References SplineSurface::i, and Dice3DS.dom3ds::tag.
getExtensionPyObject()
PyObject * CosmeticExtension::getExtensionPyObject () override virtual
Reimplemented from App::DocumentObjectExtension.
Definition at line 679 of file CosmeticExtension.cpp.
References Py::new_reference_to().
getGeomFormat()
TechDraw::GeomFormat * CosmeticExtension::getGeomFormat (const std::string & id) const virtual
Definition at line 619 of file CosmeticExtension.cpp.
References TechDraw::GeomFormat::getTagAsString().
Referenced by TechDrawGui::TaskLineDecor::getFormatAccessPtr().
getGeomFormatBySelection() [1/2]
TechDraw::GeomFormat * CosmeticExtension::getGeomFormatBySelection (const std::string & name) const virtual
Definition at line 636 of file CosmeticExtension.cpp.
References TechDraw::DrawUtil::getIndexFromName().
Referenced by TechDrawGui::TaskLineDecor::getFormatAccessPtr().
getGeomFormatBySelection() [2/2]
TechDraw::GeomFormat * CosmeticExtension::getGeomFormatBySelection (int i) const virtual
Definition at line 657 of file CosmeticExtension.cpp.
References SplineSurface::i.
getOwner()
TechDraw::DrawViewPart * CosmeticExtension::getOwner ()
get a pointer to the parent view
Definition at line 60 of file CosmeticExtension.cpp.
refreshCEGeoms()
void CosmeticExtension::refreshCEGeoms () virtual
update Edge geometry with current CE's
Definition at line 325 of file CosmeticExtension.cpp.
References TechDraw::COSEDGE.
Referenced by TechDrawGui::TaskCosmeticCircle::accept(), TechDrawGui::TaskCosmeticLine::accept(), execCreateHorizChainDimension(), execCreateHorizCoordDimension(), execCreateObliqueChainDimension(), execCreateVertChainDimension(), execCreateVertCoordDimension(), and TechDrawGui::execHoleCircle().
refreshCLGeoms()
void CosmeticExtension::refreshCLGeoms () virtual
Definition at line 464 of file CosmeticExtension.cpp.
References CENTERLINE.
refreshCVGeoms()
void CosmeticExtension::refreshCVGeoms () virtual
update the parent view's vertex geometry with all the cosmetic vertices in the list property
Definition at line 145 of file CosmeticExtension.cpp.
removeCenterLine() [1/2]
void CosmeticExtension::removeCenterLine (const std::string & tag) virtual
Definition at line 570 of file CosmeticExtension.cpp.
removeCenterLine() [2/2]
void CosmeticExtension::removeCenterLine (const std::vector< std::string > & delTags) virtual
Definition at line 585 of file CosmeticExtension.cpp.
References InitGui::t.
removeCosmeticEdge() [1/2]
void CosmeticExtension::removeCosmeticEdge (const std::string & tag) virtual
remove the cosmetic edge with the given tag from the list property
Definition at line 410 of file CosmeticExtension.cpp.
removeCosmeticEdge() [2/2]
void CosmeticExtension::removeCosmeticEdge (const std::vector< std::string > & delTags) virtual
remove the cosmetic edges with the given tags from the list property
Definition at line 427 of file CosmeticExtension.cpp.
References InitGui::t.
removeCosmeticVertex() [1/2]
void CosmeticExtension::removeCosmeticVertex (const std::string & tag) virtual
remove the cosmetic vertex with the given tag from the list property
Definition at line 254 of file CosmeticExtension.cpp.
removeCosmeticVertex() [2/2]
void CosmeticExtension::removeCosmeticVertex (const std::vector< std::string > & tags) virtual
remove the cosmetic vertices with the given tags from the list property
Definition at line 270 of file CosmeticExtension.cpp.
References InitGui::t.
removeGeomFormat()
void CosmeticExtension::removeGeomFormat (const std::string & tag) virtual
Definition at line 665 of file CosmeticExtension.cpp.
Referenced by TechDrawGui::TaskLineDecor::reject().
Member Data Documentation
CenterLines
TechDraw::PropertyCenterLineList TechDraw::CosmeticExtension::CenterLines
Definition at line 71 of file CosmeticExtension.h.
Referenced by TechDrawGui::TaskRestoreLines::countInvisibleCenters(), TechDraw::DrawViewPart::mustExecute(), and TechDrawGui::TaskRestoreLines::restoreInvisibleCenters().
CosmeticEdges
TechDraw::PropertyCosmeticEdgeList TechDraw::CosmeticExtension::CosmeticEdges
Definition at line 70 of file CosmeticExtension.h.
Referenced by TechDrawGui::TaskRestoreLines::countInvisibleCosmetics(), TechDraw::DrawViewPart::dumpCosEdges(), TechDraw::DrawViewPart::mustExecute(), and TechDrawGui::TaskRestoreLines::restoreInvisibleCosmetics().
CosmeticVertexes
TechDraw::PropertyCosmeticVertexList TechDraw::CosmeticExtension::CosmeticVertexes
Definition at line 69 of file CosmeticExtension.h.
Referenced by TechDraw::DrawViewPart::dumpCosVerts(), and TechDraw::DrawViewPart::mustExecute().
GeomFormats
TechDraw::PropertyGeomFormatList TechDraw::CosmeticExtension::GeomFormats
Definition at line 72 of file CosmeticExtension.h.
Referenced by TechDrawGui::TaskRestoreLines::countInvisibleGeoms(), and TechDrawGui::TaskRestoreLines::restoreInvisibleGeoms().
The documentation for this class was generated from the following files:
CosmeticExtension.h
CosmeticExtension.cpp