FreeCAD: Gui::ExpLineEdit Class Reference
Gui::ExpLineEdit Class Reference
#include <Widgets.h>
Public Member Functions
ExpLineEdit (QWidget *parent=nullptr, bool expressionOnly=false)
void setExpression (std::shared_ptr< App::Expression > expr) override
void bind (const App::ObjectIdentifier &_path) override
bool apply (const std::string &propName) override
void keyPressEvent (QKeyEvent *event) override
void resizeEvent (QResizeEvent *event) override
Public Member Functions inherited from Gui::ExpressionWidget
ExpressionWidget ()
QPixmap getIcon (const char *name, const QSize &size) const
Public Member Functions inherited from Gui::ExpressionBinding
ExpressionBinding ()
virtual ~ExpressionBinding ()
virtual void bind (const App::Property &prop)
bool isBound () const
void unbind ()
virtual bool apply ()
bool hasExpression () const
bool autoApply () const
void setAutoApply (bool value)
Additional Inherited Members
Protected Member Functions inherited from Gui::ExpressionWidget
void makeLabel (QLineEdit *parent)
Protected Member Functions inherited from Gui::ExpressionBinding
const App::ObjectIdentifier & getPath () const
std::shared_ptr< App::Expression > getExpression () const
std::string getExpressionString (bool no_throw=true) const
std::string getEscapedExpressionString () const
bool assignToProperty (const std::string &propName, double)
virtual void onChange ()
void expressionChange (const App::ObjectIdentifier &id)
void objectDeleted (const App::DocumentObject &)
Protected Attributes inherited from Gui::ExpressionWidget
ExpressionLabel * iconLabel {nullptr}
QPalette defaultPalette
int iconHeight {-1}
Protected Attributes inherited from Gui::ExpressionBinding
boost::signals2::scoped_connection expressionchanged
boost::signals2::scoped_connection objectdeleted
bool m_autoApply {false}
Detailed Description
The ExpLineEdit class provides a lineedit that support expressing binding.
Author
realthunder
Definition at line 576 of file Widgets.h.
Constructor & Destructor Documentation
ExpLineEdit()
ExpLineEdit::ExpLineEdit (QWidget * parent = nullptr, bool expressionOnly = false)
Definition at line 1553 of file Widgets.cpp.
References ExpressionLabel::clicked(), draftgeoutils.intersections::connect(), Gui::ExpressionWidget::iconLabel, and Gui::ExpressionWidget::makeLabel().
Member Function Documentation
apply()
bool ExpLineEdit::apply (const std::string & propName) override virtual
Reimplemented from Gui::ExpressionBinding.
Definition at line 1563 of file Widgets.cpp.
References Gui::ExpressionBinding::apply(), Gui::Command::Doc, doCommand, Base::Interpreter(), and toolbit-attributes::val.
bind()
void ExpLineEdit::bind (const App::ObjectIdentifier & _path) override virtual
Reimplemented from Gui::ExpressionBinding.
Definition at line 1576 of file Widgets.cpp.
References Gui::ExpressionBinding::bind(), and Gui::ExpressionWidget::iconLabel.
Referenced by Gui::TreeWidgetItemDelegate::createEditor().
keyPressEvent()
void ExpLineEdit::keyPressEvent (QKeyEvent * event) override
Definition at line 1702 of file Widgets.cpp.
References Gui::ExpressionBinding::hasExpression().
Referenced by DynamicQLineEdit::keyPressEvent().
resizeEvent()
void ExpLineEdit::resizeEvent (QResizeEvent * event) override
Definition at line 1629 of file Widgets.cpp.
References exportCSG::center(), Gui::ExpressionWidget::defaultPalette, Gui::ExpressionBinding::getExpression(), Gui::ExpressionWidget::getIcon(), Gui::ExpressionWidget::iconHeight, Gui::ExpressionWidget::iconLabel, Gui::ExpressionBinding::isBound(), buildPsets::p, ExpressionLabel::setExpressionText(), DraftVecUtils::toString(), and MovieTool::y.
setExpression()
void ExpLineEdit::setExpression (std::shared_ptr< App::Expression > expr) override virtual
Reimplemented from Gui::ExpressionBinding.
Definition at line 1586 of file Widgets.cpp.
References Gui::ExpressionWidget::iconLabel, Gui::ExpressionBinding::isBound(), buildPsets::p, and Gui::ExpressionBinding::setExpression().
The documentation for this class was generated from the following files:
Widgets.h
Widgets.cpp