FreeCAD: Path.Base.Generator.dogboneII.GeneratorTBoneOnShort Class Reference
Path.Base.Generator.dogboneII.GeneratorTBoneOnShort Class Reference
Public Member Functions
def angle (self, kink)
Public Member Functions inherited from Path.Base.Generator.dogboneII.Generator
def __init__ (self, calc_length, nominal_length, custom_length)
def length (self, kink, angle)
def generate_func (self)
def generate (self, kink)
Additional Inherited Members
Public Attributes inherited from Path.Base.Generator.dogboneII.Generator
calc_length
nominal_length
custom_length
Detailed Description
Definition at line 184 of file dogboneII.py.
Member Function Documentation
angle()
def Path.Base.Generator.dogboneII.GeneratorTBoneOnShort.angle (self, kink)
Definition at line 185 of file dogboneII.py.
References Path.Geom.normalizeAngle().
Referenced by Path.Dressup.Gui.Dogbone.Bone.adaptiveLength(), Path.Dressup.Gui.Dogbone.Bone.corner(), Path.Dressup.Gui.Dogbone.Bone.distance(), and Path.Base.Generator.dogboneII.Generator.generate().
The documentation for this class was generated from the following file:
dogboneII.py