FreeCAD: TechDrawGui::TaskDlgRichAnno Class Reference
TechDrawGui::TaskDlgRichAnno Class Reference
#include <TaskRichAnno.h>
Public Member Functions
TaskDlgRichAnno (TechDraw::DrawView *baseFeat, TechDraw::DrawPage *page)
TaskDlgRichAnno (TechDrawGui::ViewProviderRichAnno *annoVP)
~TaskDlgRichAnno () override
void open () override
is called the TaskView when the dialog is opened
void clicked (int) override
is called by the framework if an button is clicked which has no accept or reject role
bool accept () override
is called by the framework if the dialog is accepted (Ok)
bool reject () override
is called by the framework if the dialog is rejected (Cancel)
bool isAllowedAlterDocument () const override
is called by the framework if the user presses the help button
void update ()
void modifyStandardButtons (QDialogButtonBox *box) override
Public Member Functions inherited from Gui::TaskView::TaskDialog
TaskDialog ()
~TaskDialog () override
QWidget * addTaskBox (QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBox (const QPixmap &icon, QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBoxWithoutHeader (QWidget *widget)
void setButtonPosition (ButtonPosition p)
ButtonPosition buttonPosition () const
const std::vector< QWidget * > & getDialogContent () const
bool canClose () const
virtual QDialogButtonBox::StandardButtons getStandardButtons () const
tells the framework which buttons are wished for the dialog
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
bool isEscapeButtonEnabled () const
void setAutoCloseOnTransactionChange (bool on)
bool isAutoCloseOnTransactionChange () const
void setAutoCloseOnDeletedDocument (bool on)
bool isAutoCloseOnDeletedDocument () const
const std::string & getDocumentName () const
void setDocumentName (const std::string &doc)
void setAutoCloseOnClosedView (bool on)
bool isAutoCloseOnClosedView () const
void associateToObject3dView (App::DocumentObject *obj)
const Gui::MDIView * getAssociatedView () const
void setAssociatedView (const Gui::MDIView *view)
virtual bool isAllowedAlterView () const
virtual bool isAllowedAlterSelection () const
virtual bool needsFullSpace () const
virtual void closed ()
is called by the framework when the dialog is closed
virtual void autoClosedOnTransactionChange ()
virtual void autoClosedOnDeletedDocument ()
virtual void autoClosedOnClosedView ()
virtual void helpRequested ()
is called by the framework if the user press the help button
void emitDestructionSignal ()
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North, South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Protected Attributes inherited from Gui::TaskView::TaskDialog
QPointer< QDialogButtonBox > buttonBox
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Detailed Description
Definition at line 121 of file TaskRichAnno.h.
Constructor & Destructor Documentation
TaskDlgRichAnno() [1/2]
TaskDlgRichAnno::TaskDlgRichAnno (TechDraw::DrawView * baseFeat, TechDraw::DrawPage * page)
Definition at line 519 of file TaskRichAnno.cpp.
References Gui::BitmapFactory(), Gui::TaskView::TaskDialog::Content, and QSint::ActionGroup::groupLayout().
TaskDlgRichAnno() [2/2]
TaskDlgRichAnno::TaskDlgRichAnno (TechDrawGui::ViewProviderRichAnno * annoVP) explicit
Definition at line 530 of file TaskRichAnno.cpp.
References Gui::BitmapFactory(), Gui::TaskView::TaskDialog::Content, and QSint::ActionGroup::groupLayout().
~TaskDlgRichAnno()
TaskDlgRichAnno::~TaskDlgRichAnno () override
Definition at line 540 of file TaskRichAnno.cpp.
Member Function Documentation
accept()
bool TaskDlgRichAnno::accept () override virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 565 of file TaskRichAnno.cpp.
References TechDrawGui::TaskRichAnno::accept().
clicked()
void TaskDlgRichAnno::clicked (int) override virtual
is called by the framework if an button is clicked which has no accept or reject role
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 561 of file TaskRichAnno.cpp.
isAllowedAlterDocument()
bool TechDrawGui::TaskDlgRichAnno::isAllowedAlterDocument () const inline override virtual
is called by the framework if the user presses the help button
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 141 of file TaskRichAnno.h.
modifyStandardButtons()
void TaskDlgRichAnno::modifyStandardButtons (QDialogButtonBox * box) override virtual
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 549 of file TaskRichAnno.cpp.
References MengerSponge::box, and TechDrawGui::TaskRichAnno::saveButtons().
open()
void TaskDlgRichAnno::open () override virtual
is called the TaskView when the dialog is opened
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 557 of file TaskRichAnno.cpp.
reject()
bool TaskDlgRichAnno::reject () override virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 571 of file TaskRichAnno.cpp.
References TechDrawGui::TaskRichAnno::reject().
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action().
update()
void TaskDlgRichAnno::update ()
Definition at line 544 of file TaskRichAnno.cpp.
The documentation for this class was generated from the following files:
TaskRichAnno.h
TaskRichAnno.cpp