FreeCAD: SmSwitchboard Class Reference
SmSwitchboard Class Reference
The SmSwitchboard class is a group node that can toggle children on and off arbitrarily.
#include <SmallChange/nodes/SmSwitchboard.h>
Public Member Functions
SmSwitchboard ()
SmSwitchboard (int numchildren)
void doAction (SoAction *action) override
void callback (SoCallbackAction *action) override
void GLRender (SoGLRenderAction *action) override
void pick (SoPickAction *action) override
void getBoundingBox (SoGetBoundingBoxAction *action) override
void handleEvent (SoHandleEventAction *action) override
void getMatrix (SoGetMatrixAction *action) override
void search (SoSearchAction *action) override
Static Public Member Functions
static void initClass ()
Public Attributes
SoMFBool enable
Protected Member Functions
~SmSwitchboard () override
Detailed Description
The SmSwitchboard class is a group node that can toggle children on and off arbitrarily.
FIXME: write doc
Definition at line 41 of file SmSwitchboard.h.
Constructor & Destructor Documentation
SmSwitchboard() [1/2]
SmSwitchboard::SmSwitchboard ()
Default constructor.
Definition at line 90 of file SmSwitchboard.cpp.
References SCL.Builtin::FALSE.
SmSwitchboard() [2/2]
SmSwitchboard::SmSwitchboard (int numchildren)
Constructor.
The argument should be the approximate number of children which is expected to be inserted below this node. The number need not be exact, as it is only used as a hint for better memory resource allocation.
Definition at line 105 of file SmSwitchboard.cpp.
References enable, and SCL.Builtin::FALSE.
~SmSwitchboard()
SmSwitchboard::~SmSwitchboard () override protected default
Destructor.
Member Function Documentation
callback()
void SmSwitchboard::callback (SoCallbackAction * action) override
Definition at line 181 of file SmSwitchboard.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and doAction().
Referenced by Path.Main.Gui.Camotics.CamoticsSimulation::execute().
doAction()
void SmSwitchboard::doAction (SoAction * action) override
Definition at line 120 of file SmSwitchboard.cpp.
References Path.Post.scripts.dynapath_4060_post::action, enable, SCL.SimpleDataTypes::f, and SCL.Builtin::FALSE.
Referenced by callback(), getBoundingBox(), getMatrix(), GLRender(), handleEvent(), pick(), and search().
getBoundingBox()
void SmSwitchboard::getBoundingBox (SoGetBoundingBoxAction * action) override
Definition at line 162 of file SmSwitchboard.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and doAction().
getMatrix()
void SmSwitchboard::getMatrix (SoGetMatrixAction * action) override
Definition at line 168 of file SmSwitchboard.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and doAction().
GLRender()
void SmSwitchboard::GLRender (SoGLRenderAction * action) override
Definition at line 156 of file SmSwitchboard.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and doAction().
handleEvent()
void SmSwitchboard::handleEvent (SoHandleEventAction * action) override
Definition at line 195 of file SmSwitchboard.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and doAction().
initClass()
void SmSwitchboard::initClass () static
Definition at line 80 of file SmSwitchboard.cpp.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
pick()
void SmSwitchboard::pick (SoPickAction * action) override
Definition at line 188 of file SmSwitchboard.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and doAction().
search()
void SmSwitchboard::search (SoSearchAction * action) override
Definition at line 201 of file SmSwitchboard.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and doAction().
Referenced by importers.importIFClegacy.IfcDocument::find().
Member Data Documentation
enable
SoMFBool SmSwitchboard::enable
Selects which child to traverse during rendering (and some other) actions.
When the length of this multifield is larger than the number of children this group has, the enable list is modulated over the children. This lets you have full control over the number of times and order each child is traversed.
Default enabled value is FALSE.
Definition at line 50 of file SmSwitchboard.h.
Referenced by doAction(), SketcherGui::EditModeGeometryCoinManager::processGeometry(), src.Mod.AddonManager.Widgets.addonmanager_widget_addon_buttons.WidgetAddonButtons::retranslateUi(), SmSwitchboard(), and SketcherGui::EditModeConstraintCoinManager::updateVirtualSpace().
The documentation for this class was generated from the following files:
SmSwitchboard.h
SmSwitchboard.cpp