FreeCAD: Path.Tool.Controller Namespace Reference
Path.Tool.Controller Namespace Reference
Classes
class ToolController
class ToolControllerTemplate
Functions
def Create (name="TC: Default Tool", tool=None, toolNumber=1, assignViewProvider=True, assignTool=True)
def FromTemplate (template, assignViewProvider=True)
Variables
translate
Function Documentation
Create()
def Path.Tool.Controller.Create (name = "TC: Default Tool", tool = None, toolNumber = 1, assignViewProvider = True, assignTool = True)
Definition at line 296 of file Controller.py.
References Path.Log.track().
Referenced by Path.Tool.Controller.FromTemplate().
FromTemplate()
def Path.Tool.Controller.FromTemplate (template, assignViewProvider = True)
Definition at line 329 of file Controller.py.
References Path.Tool.Controller.Create(), and Path.Log.track().
Variable Documentation
translate
Path.Tool.Controller.translate
Definition at line 38 of file Controller.py.