FreeCAD: TechDrawGui::QGIViewClip Class Reference
TechDrawGui::QGIViewClip Class Reference
#include <QGIViewClip.h>
Public Types
enum { Type = QGraphicsItem::UserType + 123 }
Public Types inherited from TechDrawGui::QGIView
enum { Type = QGraphicsItem::UserType + 101 }
Public Member Functions
QGIViewClip ()
~QGIViewClip () override=default
int type () const override
void updateView (bool update=false) override
void draw () override
QGCustomRect * getFrame ()
QGCustomClip * getClipArea ()
Public Member Functions inherited from TechDrawGui::QGIView
QGIView ()
int type () const override
QRectF boundingRect () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
const char * getViewName () const
const std::string getViewNameAsString () const
void setViewFeature (TechDraw::DrawView *obj)
TechDraw::DrawView * getViewObject () const
MDIViewPage * getMDIViewPage () const
double getScale ()
void hideFrame ()
virtual bool getFrameState ()
virtual void toggleCache (bool state)
virtual void drawBorder ()
virtual void isVisible (bool state)
virtual bool isVisible ()
virtual bool getGroupSelection ()
virtual void setGroupSelection (bool isSelected)
virtual void setGroupSelection (bool isSelected, const std::vector< std::string > &subNames)
virtual void drawCaption ()
virtual void rotateView ()
void makeMark (double xPos, double yPos, QColor color=Qt::red)
void makeMark (Base::Vector3d pos, QColor color=Qt::red)
void makeMark (QPointF pos, QColor color=Qt::red)
void setPosition (qreal xPos, qreal yPos)
qreal getY ()
bool isInnerView () const
void isInnerView (bool state)
QGIViewClip * getClipGroup ()
bool isSnapping ()
void snapPosition (QPointF &position)
void snapSectionView (const TechDraw::DrawViewSection *sectionView, QPointF &newPosition)
Base::Vector3d projItemPagePos (TechDraw::DrawViewPart *item)
void alignTo (QGraphicsItem *, const QString &alignment)
QColor prefNormalColor ()
QColor getNormalColor ()
void setNormalColor (QColor color)
QColor getPreColor ()
QColor getSelectColor ()
QColor getCurrentColor ()
void setCurrentColor (QColor color)
QColor getSettingColor ()
void setSettingColor (QColor color)
virtual void setStack (int z)
virtual void setStackFromVP ()
QFont getFont ()
void setFont (QFont font)
virtual void removeChild (QGIView *child)
virtual void addArbitraryItem (QGraphicsItem *qgi)
virtual void switchParentItem (QGIView *targetParent)
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
Protected Member Functions
void drawClip ()
Protected Member Functions inherited from TechDrawGui::QGIView
QGIView * getQGIVByName (std::string name)
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
virtual QRectF customChildrenBoundingRect () const
void dumpRect (const char *text, QRectF rect)
Base::Reference< ParameterGrp > getParmGroupCol ()
Additional Inherited Members
Static Public Member Functions inherited from TechDrawGui::QGIView
static Gui::ViewProvider * getViewProvider (App::DocumentObject *obj)
static ViewProviderPage * getViewProviderPage (TechDraw::DrawView *dView)
static int calculateFontPixelSize (double sizeInMillimetres)
static int calculateFontPixelWidth (const QFont &font)
static QString getPrefFont ()
static double getPrefFontSize ()
static double getDimFontSize ()
static int exactFontSize (std::string fontFamily, double nominalSize)
Static Public Attributes inherited from TechDrawGui::QGIView
static const double DefaultFontSizeInMM = 5.0
Detailed Description
Definition at line 55 of file QGIViewClip.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 62 of file QGIViewClip.h.
Constructor & Destructor Documentation
QGIViewClip()
QGIViewClip::QGIViewClip ()
Definition at line 41 of file QGIViewClip.cpp.
References TechDrawGui::Rez::guiX(), and TechDrawGui::QGCustomClip::setRect().
~QGIViewClip()
TechDrawGui::QGIViewClip::~QGIViewClip () override default
Member Function Documentation
draw()
void QGIViewClip::draw () override virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 79 of file QGIViewClip.cpp.
References TechDrawGui::QGIView::drawBorder(), drawClip(), TechDrawGui::QGIView::getFrameState(), and TechDrawGui::QGIView::isVisible().
Referenced by updateView().
drawClip()
void QGIViewClip::drawClip () protected
Definition at line 91 of file QGIViewClip.cpp.
References Base::Console(), DraftVecUtils::find(), TechDrawGui::QGIView::getQGIVByName(), App::PropertyQuantity::getValue(), TechDrawGui::QGIView::getViewName(), TechDrawGui::QGIView::getViewObject(), TechDrawGui::Rez::guiX(), TechDrawGui::QGIView::isInnerView(), TechDrawGui::QGIView::setPosition(), TechDrawGui::QGCustomClip::setRect(), src.Mod.PartDesign.fcgear.svggear::w, Base::ConsoleSingleton::Warning(), MovieTool::x, TechDraw::DrawView::X, MovieTool::y, and TechDraw::DrawView::Y.
Referenced by draw().
getClipArea()
QGCustomClip* TechDrawGui::QGIViewClip::getClipArea () inline
Definition at line 69 of file QGIViewClip.h.
getFrame()
QGCustomRect* TechDrawGui::QGIViewClip::getFrame () inline
Definition at line 68 of file QGIViewClip.h.
type()
int TechDrawGui::QGIViewClip::type () const inline override
Definition at line 63 of file QGIViewClip.h.
updateView()
void QGIViewClip::updateView (bool update = false) override virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 60 of file QGIViewClip.cpp.
References draw(), TechDrawGui::QGIView::getViewObject(), and TechDrawGui::QGIView::updateView().
The documentation for this class was generated from the following files:
QGIViewClip.h
QGIViewClip.cpp