FreeCAD: Gui::WindowParameter Class Reference
Gui::WindowParameter Class Reference
#include <Window.h>
Public Member Functions
WindowParameter (const char *name)
~WindowParameter () override
void OnChange (Base::Subject< const char * > &rCaller, const char *sReason) override
ParameterGrp::handle getWindowParameter ()
return the parameter group of this window
Static Public Member Functions
static ParameterGrp::handle getDefaultParameter ()
get the parameters
Protected Member Functions
bool setGroupName (const char *name)
template<typename S , typename T >
void setSlotParamChanged (S slot, T *obsPtr)
connect slot to ParameterManager signal
Detailed Description
Adapter class to the parameter of FreeCAD for all windows Retrieve the parameter group of the specific window by the windowname.
Author
Jürgen Riegel
Definition at line 55 of file Window.h.
Constructor & Destructor Documentation
WindowParameter()
WindowParameter::WindowParameter (const char * name)
Definition at line 45 of file Window.cpp.
References getDefaultParameter(), and ParameterGrp::GetGroup().
~WindowParameter()
WindowParameter::~WindowParameter () override
Definition at line 56 of file Window.cpp.
Member Function Documentation
getDefaultParameter()
ParameterGrp::handle WindowParameter::getDefaultParameter () static
get the parameters
Returns a handle to the parameter group to the user parameter under BaseApp/Preferences.
Definition at line 103 of file Window.cpp.
References App::GetApplication(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
Referenced by Gui::SoFCUnifiedSelection::applySettings(), Gui::SoFCSelection::applySettings(), Gui::ViewProviderAnnotation::attach(), MeshGui::ViewProviderMeshFaceSet::attach(), MeshGui::ViewProviderIndexedFaceSet::attach(), MeshGui::ViewProviderMeshObject::attach(), Gui::ViewProviderBuilder::createSelection(), MeshGui::ViewProviderMesh::fillHole(), Gui::Dialog::ApplicationCacheSettings::getCacheSizeLimit(), Gui::Dialog::ApplicationCacheSettings::getCheckPeriod(), Gui::Dialog::DlgSettingsEditor::loadSettings(), Gui::Dialog::DlgSettingsGeneral::loadSettings(), MeshGui::DlgSettingsMeshView::loadSettings(), Gui::Dialog::DlgSettingsMacroImp::loadSettings(), Gui::PythonConsole::onSaveHistoryAs(), Gui::PythonConsole::PythonConsole(), Gui::DockWnd::ReportOutput::ReportOutput(), Gui::DockWnd::ReportView::ReportView(), Gui::Dialog::DlgSettingsEditor::resetSettingsToDefaults(), Gui::Dialog::DlgSettingsGeneral::resetSettingsToDefaults(), Gui::Dialog::DlgSettingsCacheDirectory::resetSettingsToDefaults(), Gui::Dialog::DlgSettingsMacroImp::resetSettingsToDefaults(), Gui::Dialog::DlgSettingsEditor::saveSettings(), Gui::Dialog::DlgSettingsGeneral::saveSettings(), Gui::Dialog::DlgSettingsMacroImp::saveSettings(), Gui::Dialog::ApplicationCacheSettings::setCacheSizeLimit(), Gui::Dialog::ApplicationCacheSettings::setCheckPeriod(), setGroupName(), Gui::ShortcutManager::ShortcutManager(), and WindowParameter().
getWindowParameter()
ParameterGrp::handle WindowParameter::getWindowParameter ()
return the parameter group of this window
Definition at line 94 of file Window.cpp.
Referenced by Gui::PythonConsole::changeEvent(), Gui::DockWnd::ReportOutput::changeEvent(), Gui::DockWnd::ReportOutput::customEvent(), Gui::Dialog::DlgMacroExecuteImp::DlgMacroExecuteImp(), Gui::Dialog::DlgMacroRecordImp::DlgMacroRecordImp(), Gui::PythonEditor::keyPressEvent(), Gui::PythonTextEditor::keyPressEvent(), Gui::Dialog::DlgMacroRecordImp::onButtonChooseDirClicked(), Gui::EditorView::OnChange(), Gui::TextEditor::OnChange(), Gui::PrefWidget::onRestore(), Gui::PrefWidget::onSave(), Gui::DockWnd::ReportOutput::onToggleCritical(), Gui::DockWnd::ReportOutput::onToggleError(), Gui::DockWnd::ReportOutput::onToggleGoToEnd(), Gui::DockWnd::ReportOutput::onToggleLogMessage(), Gui::DockWnd::ReportOutput::onToggleNormalMessage(), Gui::DockWnd::ReportOutput::onToggleRedirectPythonStderr(), Gui::DockWnd::ReportOutput::onToggleRedirectPythonStdout(), Gui::DockWnd::ReportOutput::onToggleWarning(), Gui::PythonConsole::PythonConsole(), Gui::DockWnd::ReportOutput::ReportOutput(), Gui::PrefSpinBox::restorePreferences(), Gui::PrefDoubleSpinBox::restorePreferences(), Gui::PrefLineEdit::restorePreferences(), Gui::PrefTextEdit::restorePreferences(), Gui::PrefFileChooser::restorePreferences(), Gui::PrefComboBox::restorePreferences(), Gui::PrefCheckBox::restorePreferences(), MatGui::PrefMaterialTreeWidget::restorePreferences(), Gui::PrefRadioButton::restorePreferences(), Gui::PrefSlider::restorePreferences(), Gui::PrefColorButton::restorePreferences(), Gui::PrefUnitSpinBox::restorePreferences(), Gui::PrefQuantitySpinBox::restorePreferences(), Gui::PrefFontBox::restorePreferences(), Gui::PrefSpinBox::savePreferences(), Gui::PrefDoubleSpinBox::savePreferences(), Gui::PrefLineEdit::savePreferences(), Gui::PrefTextEdit::savePreferences(), Gui::PrefFileChooser::savePreferences(), Gui::PrefComboBox::savePreferences(), Gui::PrefCheckBox::savePreferences(), MatGui::PrefMaterialTreeWidget::savePreferences(), Gui::PrefRadioButton::savePreferences(), Gui::PrefSlider::savePreferences(), Gui::PrefColorButton::savePreferences(), Gui::PrefUnitSpinBox::savePreferences(), Gui::PrefQuantitySpinBox::savePreferences(), Gui::PrefFontBox::savePreferences(), Gui::PrefWidget::setParamGrpPath(), Gui::StatusBarObserver::StatusBarObserver(), Gui::TextEditor::TextEditor(), Gui::EditorView::~EditorView(), Gui::PrefWidget::~PrefWidget(), Gui::DockWnd::ReportOutput::~ReportOutput(), Gui::StatusBarObserver::~StatusBarObserver(), and Gui::TextEditor::~TextEditor().
OnChange()
void WindowParameter::OnChange (Base::Subject< const char * > & rCaller, const char * sReason) override
Definition at line 88 of file Window.cpp.
setGroupName()
bool WindowParameter::setGroupName (const char * name) protected
Sets the group of the window to name
Definition at line 62 of file Window.cpp.
References App::GetApplication(), getDefaultParameter(), ParameterGrp::GetGroup(), App::Application::GetParameterGroupByPath(), App::Application::GetParameterSetList(), and Base::Reference< T >::isValid().
Referenced by Gui::PrefWidget::setParamGrpPath().
setSlotParamChanged()
template<typename S , typename T > void Gui::WindowParameter::setSlotParamChanged (S slot, T * obsPtr) inline protected
connect slot to ParameterManager signal
Definition at line 81 of file Window.h.
The documentation for this class was generated from the following files:
Window.h
Window.cpp