FreeCAD: AppTechDraw.cpp File Reference
AppTechDraw.cpp File Reference
#include "PreCompiled.h"
#include <Base/Console.h>
#include <Base/Interpreter.h>
#include <Base/PyObjectBase.h>
#include "CenterLine.h"
#include "CosmeticExtension.h"
#include "Cosmetic.h"
#include "DrawComplexSection.h"
#include "DrawGeomHatch.h"
#include "DrawHatch.h"
#include "DrawLeaderLine.h"
#include "DrawPage.h"
#include "DrawParametricTemplate.h"
#include "DrawProjGroup.h"
#include "DrawProjGroupItem.h"
#include "DrawRichAnno.h"
#include "DrawSVGTemplate.h"
#include "DrawTile.h"
#include "DrawTileWeld.h"
#include "DrawViewAnnotation.h"
#include "DrawViewArch.h"
#include "DrawViewBalloon.h"
#include "DrawViewClip.h"
#include "DrawViewCollection.h"
#include "DrawViewDetail.h"
#include "DrawViewDimension.h"
#include "DrawViewDimExtent.h"
#include "DrawViewDraft.h"
#include "DrawView.h"
#include "DrawViewImage.h"
#include "DrawViewPart.h"
#include "DrawViewSection.h"
#include "DrawViewSpreadsheet.h"
#include "DrawViewSymbol.h"
#include "DrawWeldSymbol.h"
#include "FeatureProjection.h"
#include "LandmarkDimension.h"
#include "PropertyCenterLineList.h"
#include "PropertyCosmeticEdgeList.h"
#include "PropertyCosmeticVertexList.h"
#include "PropertyGeomFormatList.h"
#include "DrawBrokenViewPy.h"
Namespaces
TechDraw
a class to the projection of shapes, removal/identifying hidden lines and
Functions
PyObject * TechDraw::initModule ()
PyMOD_INIT_FUNC (TechDraw)
Function Documentation
PyMOD_INIT_FUNC()
PyMOD_INIT_FUNC (TechDraw)
Definition at line 73 of file AppTechDraw.cpp.
References Base::Console(), SCL.SimpleDataTypes::e, SIM::Coin3D::Quarter::Quarter::init(), App::DocumentObjectExtension::init(), Base::Persistence::init(), App::ExtensionPythonT< ExtensionT >::init(), TechDraw::LineFormat::initCurrentLineFormat(), TechDraw::initModule(), Base::Interpreter(), Base::InterpreterSingleton::loadModule(), Base::ConsoleSingleton::Log(), mod, and PyMOD_Return.