FreeCAD: ifc2x3.ifcsurfacetexture Class Reference
ifc2x3.ifcsurfacetexture Class Reference
Public Member Functions
def __init__ (self, repeats, repeatt, texturetype, texturetransform)
def repeats ()
def repeatt ()
def texturetype ()
def texturetransform ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
repeats
repeatt
texturetype
texturetransform
Detailed Description
Entity ifcsurfacetexture definition.
:param repeats
:type repeats:BOOLEAN
:param repeatt
:type repeatt:BOOLEAN
:param texturetype
:type texturetype:ifcsurfacetextureenum
:param texturetransform
:type texturetransform:ifccartesiantransformationoperator2d
Definition at line 6534 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcsurfacetexture.__init__ (self, repeats, repeatt, texturetype, texturetransform)
Definition at line 6549 of file ifc2x3.py.
Member Function Documentation
repeats()
def ifc2x3.ifcsurfacetexture.repeats ()
Definition at line 6556 of file ifc2x3.py.
References ifc2x3.ifcsurfacetexture._repeats, SCL.SimpleDataTypes.BOOLEAN, SCL.TypeChecker.check_type(), and ifc2x3.ifcsurfacetexture.repeats.
repeatt()
def ifc2x3.ifcsurfacetexture.repeatt ()
Definition at line 6570 of file ifc2x3.py.
References ifc2x3.ifcsurfacetexture._repeatt, SCL.SimpleDataTypes.BOOLEAN, SCL.TypeChecker.check_type(), and ifc2x3.ifcsurfacetexture.repeatt.
texturetransform()
def ifc2x3.ifcsurfacetexture.texturetransform ()
Definition at line 6598 of file ifc2x3.py.
References ifc2x3.ifcsurfacetexture._texturetransform, SCL.TypeChecker.check_type(), and ifc2x3.ifcsurfacetexture.texturetransform.
texturetype()
def ifc2x3.ifcsurfacetexture.texturetype ()
Definition at line 6584 of file ifc2x3.py.
References ifc2x3.ifcsurfacetexture._texturetype, SCL.TypeChecker.check_type(), and ifc2x3.ifcsurfacetexture.texturetype.
Member Data Documentation
repeats
ifc2x3.ifcsurfacetexture.repeats
Definition at line 6550 of file ifc2x3.py.
Referenced by ifc2x3.ifcsurfacetexture.repeats().
repeatt
ifc2x3.ifcsurfacetexture.repeatt
Definition at line 6551 of file ifc2x3.py.
Referenced by ifc2x3.ifcsurfacetexture.repeatt().
texturetransform
ifc2x3.ifcsurfacetexture.texturetransform
Definition at line 6553 of file ifc2x3.py.
Referenced by ifc2x3.ifcsurfacetexture.texturetransform().
texturetype
ifc2x3.ifcsurfacetexture.texturetype
Definition at line 6552 of file ifc2x3.py.
Referenced by ifc2x3.ifcsurfacetexture.texturetype().
The documentation for this class was generated from the following file:
ifc2x3.py