FreeCAD: AppReverseEngineering.cpp File Reference
AppReverseEngineering.cpp File Reference
#include "PreCompiled.h"
#include <Geom_BSplineSurface.hxx>
#include <TColgp_Array1OfPnt.hxx>
#include <Base/Console.h>
#include <Base/Converter.h>
#include <Base/GeometryPyCXX.h>
#include <Base/Interpreter.h>
#include <Base/PyWrapParseTupleAndKeywords.h>
#include <Mod/Mesh/App/MeshPy.h>
#include <Mod/Part/App/BSplineSurfacePy.h>
#include <Mod/Points/App/PointsPy.h>
#include "ApproxSurface.h"
#include "BSplineFitting.h"
#include "RegionGrowing.h"
#include "SampleConsensus.h"
#include "Segmentation.h"
#include "SurfaceTriangulation.h"
Classes
class Reen::Module
Namespaces
Reen
Functions
PyObject * Reen::initModule ()
PyMOD_INIT_FUNC (ReverseEngineering)
Function Documentation
PyMOD_INIT_FUNC()
PyMOD_INIT_FUNC (ReverseEngineering)
Definition at line 989 of file AppReverseEngineering.cpp.
References Base::Console(), SCL.SimpleDataTypes::e, Reen::initModule(), Base::Interpreter(), Base::InterpreterSingleton::loadModule(), Base::ConsoleSingleton::Log(), mod, and PyMOD_Return.