FreeCAD: Gui::MacroManager Class Reference
Gui::MacroManager Class Reference
#include <Macro.h>
Public Types
enum MacroType { File, User, Doc }
enum LineType { App, Gui, Cmt }
Public Member Functions
void open (MacroType eType, const char *sName)
void commit ()
close (and save) the recording session
void cancel ()
cancels the recording session
bool isOpen () const
indicates if a macro recording is in progress
void addLine (LineType Type, const char *sLine)
insert a new line in the macro
void addPendingLine (LineType type, const char *line)
insert a new pending line in the macro
void setModule (const char *sModule)
void run (MacroType eType, const char *sName)
PythonDebugger * debugger () const
Get the Python debugger.
PythonConsole * getPythonConsole () const
void OnChange (Base::Subject< const char * > &rCaller, const char *sReason) override
long getLines () const
Return the added lines regardless of recording or not.
Public Member Functions inherited from Base::Observer< const char * >
Observer ()=default
virtual ~Observer ()=default
virtual void OnDestroy (Subject< const char * > &rCaller)
virtual const char * Name ()
Protected Member Functions
MacroManager ()
~MacroManager () override
Friends
struct ApplicationP
Detailed Description
Macro recording and play back management The purpos of this class is to handle record function calls from a command and save it in a macro file (so far).
Author
Jürgen Riegel
Definition at line 122 of file Macro.h.
Member Enumeration Documentation
LineType
enum Gui::MacroManager::LineType
Line type enumeration
Enumerator
App
The line effects only the document and Application (FreeCAD)
Gui
The line effects the Gui (FreeCADGui)
Cmt
The line is handled as a comment
Definition at line 138 of file Macro.h.
MacroType
enum Gui::MacroManager::MacroType
Macro type enumeration
Enumerator
File
The macro will be saved in a file
User
The macro belongs to the Application and will be saved in the UserParameter
Doc
The macro belongs to the Document and will be saved and restored with the Document
Definition at line 131 of file Macro.h.
Constructor & Destructor Documentation
MacroManager()
MacroManager::MacroManager () protected
Definition at line 206 of file Macro.cpp.
References Base::Subject< MsgType >::Attach(), App::GetApplication(), App::Application::GetParameterGroupByPath(), and ParameterGrp::NotifyAll().
~MacroManager()
MacroManager::~MacroManager () override protected
Definition at line 215 of file Macro.cpp.
References Base::Subject< MsgType >::Detach().
Member Function Documentation
addLine()
void MacroManager::addLine (LineType Type, const char * sLine)
insert a new line in the macro
Definition at line 269 of file Macro.cpp.
References Gui::MacroOutputBuffer::addPendingLineIfComment(), Gui::MacroOutputBuffer::hasPendingLines(), and Gui::MacroOutputBuffer::incrementIfNoComment().
Referenced by Gui::Command::_runCommand(), StdCmdViewIvIssueCamPos::activated(), Gui::Command::addModule(), Gui::SelectionSingleton::clearCompleteSelection(), Gui::SelectionSingleton::clearSelection(), Gui::SelectionSingleton::_SelObj::log(), Gui::Command::printCaller(), Gui::ApplicationPy::sDoCommand(), Gui::ApplicationPy::sDoCommandGui(), and Gui::ApplicationPy::sDoCommandSkip().
addPendingLine()
void MacroManager::addPendingLine (LineType type, const char * line)
insert a new pending line in the macro
Definition at line 264 of file Macro.cpp.
References Gui::MacroOutputBuffer::addPendingLine(), and Path.Post.scripts.grbl_post::type.
Referenced by PendingLine::cancel(), and PendingLine::PendingLine().
cancel()
void MacroManager::cancel ()
cancels the recording session
Definition at line 257 of file Macro.cpp.
References Gui::MacroFile::cancel(), Base::Console(), Gui::MacroFile::fileName(), and Base::ConsoleSingleton::Log().
Referenced by commit(), and Gui::Dialog::DlgMacroRecordImp::onButtonCloseClicked().
commit()
void MacroManager::commit ()
close (and save) the recording session
Definition at line 244 of file Macro.cpp.
References cancel(), Gui::MacroFile::commit(), Base::Console(), Base::ConsoleSingleton::Error(), Gui::MacroFile::fileName(), and Base::ConsoleSingleton::Log().
Referenced by draftguitools.gui_offset.Offset::action(), draftguitools.gui_styles.ApplyStyle::Activated(), draftguitools.gui_points.Point::click(), draftguitools.gui_labels.Label::create(), draftguitools.gui_dimensions.Dimension::create_angle_dimension(), draftguitools.gui_dimensions.Dimension::create_linear_dimension(), draftguitools.gui_dimensions.Dimension::create_linear_dimension_obj(), draftguitools.gui_dimensions.Dimension::create_radial_dimension_obj(), draftguitools.gui_rectangles.Rectangle::createObject(), draftguitools.gui_ellipses.Ellipse::createObject(), draftguitools.gui_texts.Text::createObject(), draftguitools.gui_stretch.Stretch::doStretch(), draftguitools.gui_fillets.Fillet::draw_arc(), draftguitools.gui_arcs.Arc::drawArc(), draftguitools.gui_polygons.Polygon::drawPolygon(), draftguitools.gui_lines.Line::finish(), draftguitools.gui_splines.BSpline::finish(), draftguitools.gui_beziers.BezCurve::finish(), draftguitools.gui_beziers.CubicBezCurve::finish(), draftguitools.gui_arcs.Arc_3Points::getPoint(), draftguitools.gui_mirror.Mirror::mirror(), draftguitools.gui_move.Move::move_object(), draftguitools.gui_move.Move::move_subelements(), draftguitools.gui_offset.Offset::numericRadius(), Gui::Dialog::DlgMacroRecordImp::onButtonStopClicked(), bimcommands.BimShape2DView.BIM_Shape2DView::proceed(), draftguitools.gui_join.Join::proceed(), draftguitools.gui_draft2sketch.Draft2Sketch::proceed(), draftguitools.gui_downgrade.Downgrade::proceed(), draftguitools.gui_upgrade.Upgrade::proceed(), draftguitools.gui_pathtwistedarray.PathTwistedArray::proceed(), draftguitools.gui_shape2dview.Shape2DView::proceed(), draftguitools.gui_split.Split::proceed(), draftguitools.gui_pointarray.PointArray::proceed(), draftguitools.gui_patharray.PathArray::proceed(), draftguitools.gui_rotate.Rotate::rotate_object(), draftguitools.gui_rotate.Rotate::rotate_subelements(), draftguitools.gui_scale.Scale::scale_object(), draftguitools.gui_scale.Scale::scale_subelements(), and draftguitools.gui_scale.Scale::scale_with_clone().
debugger()
PythonDebugger * MacroManager::debugger () const
Get the Python debugger.
Definition at line 398 of file Macro.cpp.
Referenced by StdCmdMacroStartDebug::activated(), StdCmdMacroStopDebug::activated(), StdCmdMacroStepOver::activated(), StdCmdMacroStepInto::activated(), StdCmdMacroStopDebug::isActive(), StdCmdMacroStepOver::isActive(), StdCmdMacroStepInto::isActive(), and Gui::PythonEditorP::PythonEditorP().
getLines()
long Gui::MacroManager::getLines () const inline
Return the added lines regardless of recording or not.
Definition at line 180 of file Macro.h.
getPythonConsole()
PythonConsole * MacroManager::getPythonConsole () const
Definition at line 336 of file Macro.cpp.
References Gui::getMainWindow().
isOpen()
bool Gui::MacroManager::isOpen () const inline
indicates if a macro recording is in progress
Definition at line 159 of file Macro.h.
Referenced by Gui::Dialog::DlgMacroRecordImp::DlgMacroRecordImp(), Gui::Dialog::DlgMacroRecordImp::onButtonCloseClicked(), and Gui::Dialog::DlgMacroRecordImp::onButtonStopClicked().
OnChange()
void MacroManager::OnChange (Base::Subject< const char * > & rCaller, const char * sReason) override virtual
Observes its parameter group.
Implements Base::Observer< const char * >.
Definition at line 221 of file Macro.cpp.
References ParameterGrp::GetBool(), Gui::MacroOutputOption::guiAsComment, Gui::MacroOutputOption::recordGui, and Gui::MacroOutputOption::scriptToPyConsole.
open()
void MacroManager::open (MacroType eType, const char * sName)
Opens a new Macro recording session Starts a session with the type and the name of the macro. All user interactions will be recorded as long as the commit() or cancel() isn't called. There is only one recording session possible. Trying to open a second one causes an exception:
Parameters
eType Type of the macro
sName Name or path of the macro
See also
commit()
cancel()
Definition at line 231 of file Macro.cpp.
References Base::Console(), File, Base::ConsoleSingleton::Log(), and Gui::MacroFile::open().
Referenced by Gui::Dialog::DlgMacroRecordImp::onButtonStartClicked().
run()
void MacroManager::run (MacroType eType, const char * sName)
Definition at line 373 of file Macro.cpp.
References SCL.SimpleDataTypes::e, App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), App::Application::GetUserParameter(), Base::Interpreter(), and Base::InterpreterSingleton::runFile().
Referenced by Gui::Dialog::DlgMacroExecuteImp::accept(), Gui::MacroCommand::activated(), Gui::RecentMacrosAction::activateFile(), femexamples.examplesgui.FemExamples::clicked(), Gui::PythonEditorView::executeScript(), and femsolver.task.Task::protector().
setModule()
void MacroManager::setModule (const char * sModule)
Set the active module This is normally done by the workbench switch. It sets the actually active application module so when the macro gets started the right import can be issued.
Definition at line 329 of file Macro.cpp.
References Gui::MacroFile::append(), and Gui::MacroFile::isOpen().
Friends And Related Function Documentation
ApplicationP
friend struct ApplicationP friend
Definition at line 198 of file Macro.h.
The documentation for this class was generated from the following files:
Macro.h
Macro.cpp