FreeCAD: Gui::WaitCursor Class Reference
Gui::WaitCursor Class Reference
#include <WaitCursor.h>
Public Types
enum FilterEventsFlag { NoEvents = 0x00, KeyEvents = 0x01, MouseEvents = 0x02, AllEvents = KeyEvents | MouseEvents }
Public Member Functions
WaitCursor ()
~WaitCursor ()
void setWaitCursor ()
void restoreCursor ()
FilterEventsFlags ignoreEvents () const
void setIgnoreEvents (FilterEventsFlags flags=AllEvents)
Detailed Description
This class sets a waitcursor automatically while a slow operation is running. Therefore you just have to create an instance of WaitCursor before the time consuming operation starts.
 :
WaitCursor ac;
...
...                   // slow operation
...
Sometimes you have two slow operations with some user interactions in between them. Avoiding to show the waiting cursor then you have to call the methods restoreCursor() and setWaitCursor manually, like:
 :
WaitCursor ac;
...
...                   // 1st slow operation
ac.restoreCursor();
...
...                  // some dialog stuff
ac.setWaitCursor();
...
...                  // 2nd slow operation
Author
Werner Mayer
Definition at line 79 of file WaitCursor.h.
Member Enumeration Documentation
FilterEventsFlag
enum Gui::WaitCursor::FilterEventsFlag
Enumerator
NoEvents
KeyEvents
MouseEvents
AllEvents
Definition at line 102 of file WaitCursor.h.
Constructor & Destructor Documentation
WaitCursor()
WaitCursor::WaitCursor ()
Constructs this object and shows the wait cursor immediately. If you need to open a dialog as long as an instance of WaitCursor exists you must call restoreCursor() before and setWaitCursor() afterwards because all key events and mouse button events are filtered, otherwise you will run into strange behaviour.
Definition at line 152 of file WaitCursor.cpp.
References Gui::WaitCursorP::getInstance(), Gui::WaitCursorP::ignoreEvents(), and setWaitCursor().
~WaitCursor()
WaitCursor::~WaitCursor ()
Restores the last cursor again.
Definition at line 160 of file WaitCursor.cpp.
References Gui::WaitCursorP::getInstance(), restoreCursor(), and Gui::WaitCursorP::setIgnoreEvents().
Member Function Documentation
ignoreEvents()
WaitCursor::FilterEventsFlags WaitCursor::ignoreEvents () const
Definition at line 183 of file WaitCursor.cpp.
References Gui::WaitCursorP::getInstance(), and Gui::WaitCursorP::ignoreEvents().
restoreCursor()
void WaitCursor::restoreCursor ()
Restores the last cursor if needed.
Definition at line 178 of file WaitCursor.cpp.
References Gui::WaitCursorP::getInstance(), and Gui::WaitCursorP::setBusy().
Referenced by FemGui::TaskDlgMeshShapeNetgen::accept(), RobotGui::Workbench::activated(), Gui::Application::activateWorkbench(), TechDrawGui::TaskSectionView::apply(), TechDrawGui::TaskComplexSection::apply(), Gui::Application::checkForRecomputes(), Gui::Application::exportTo(), Gui::Application::importFrom(), Gui::Application::open(), Gui::SequencerBar::pause(), Gui::ApplicationPy::sShowPreferences(), Gui::ApplicationPy::sShowPreferencesByName(), TechDrawGui::TaskProjGroup::viewToggled(), and ~WaitCursor().
setIgnoreEvents()
void WaitCursor::setIgnoreEvents (FilterEventsFlags flags = AllEvents)
Definition at line 188 of file WaitCursor.cpp.
References Gui::WaitCursorP::getInstance(), and Gui::WaitCursorP::setIgnoreEvents().
Referenced by StdCmdLinkImport::activated(), StdCmdLinkImportAll::activated(), Gui::Application::exportTo(), Gui::Application::importFrom(), Gui::Application::open(), and Gui::Application::reopen().
setWaitCursor()
void WaitCursor::setWaitCursor ()
Sets the wait cursor if needed.
Definition at line 170 of file WaitCursor.cpp.
References Gui::WaitCursorP::getInstance(), and Gui::WaitCursorP::setBusy().
Referenced by RobotGui::Workbench::activated(), Gui::Application::activateWorkbench(), Gui::Application::exportTo(), Gui::Application::importFrom(), Gui::Application::open(), Gui::SequencerBar::resume(), Gui::ApplicationPy::sShowPreferences(), Gui::ApplicationPy::sShowPreferencesByName(), and WaitCursor().
The documentation for this class was generated from the following files:
WaitCursor.h
WaitCursor.cpp