FreeCAD: Gui::Dialog::DlgEditFileIncludePropertyExternal Class Reference
Gui::Dialog::DlgEditFileIncludePropertyExternal Class Reference
#include <DlgEditFileIncludePropertyExternal.h>
Public Member Functions
DlgEditFileIncludePropertyExternal (App::PropertyFileIncluded &Prop, QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~DlgEditFileIncludePropertyExternal () override
int processFile ()
Public Member Functions inherited from Gui::Dialog::DlgRunExternal
DlgRunExternal (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~DlgRunExternal () override
void addArgument (const QString &)
int runProcess ()
Additional Inherited Members
Protected Slots inherited from Gui::Dialog::DlgRunExternal
void reject () override
void accept () override
virtual void abort ()
virtual void advanced ()
void finished (int exitCode, QProcess::ExitStatus exitStatus)
void onChooseProgramClicked ()
Detailed Description
Author
Jürgen Riegel
Definition at line 77 of file DlgEditFileIncludePropertyExternal.h.
Constructor & Destructor Documentation
DlgEditFileIncludePropertyExternal()
DlgEditFileIncludePropertyExternal::DlgEditFileIncludePropertyExternal (App::PropertyFileIncluded & Prop, QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags())
Constructs a DlgEditFileIncludePropertyExternal which is a child of 'parent', with the name 'name' and widget flags set to 'f'
The dialog will by default be modeless, unless you set 'modal' to true to construct a modal dialog.
Definition at line 42 of file DlgEditFileIncludePropertyExternal.cpp.
~DlgEditFileIncludePropertyExternal()
DlgEditFileIncludePropertyExternal::~DlgEditFileIncludePropertyExternal () override default
Destroys the object and frees any allocated resources
Member Function Documentation
processFile()
int DlgEditFileIncludePropertyExternal::processFile ()
Definition at line 54 of file DlgEditFileIncludePropertyExternal.cpp.
References Gui::Dialog::DlgRunExternal::addArgument(), Drawing::copy(), DrawingExample::file, App::Application::getUserCachePath(), App::PropertyFileIncluded::getValue(), Gui::Dialog::DlgRunExternal::runProcess(), and App::PropertyFileIncluded::setValue().
The documentation for this class was generated from the following files:
DlgEditFileIncludePropertyExternal.h
DlgEditFileIncludePropertyExternal.cpp