FreeCAD: TechDrawGui::QGVPage::Private Class Reference
TechDrawGui::QGVPage::Private Class Reference
Public Member Functions
Private (QGVPage *page)
void init ()
void OnChange (ParameterGrp::SubjectType &rCaller, ParameterGrp::MessageType Reason) override
Observer message from the ParameterGrp.
void detach ()
Public Attributes
ParameterGrp::handle hGrp
handle to the viewer parameter group
QGVPage * page
Detailed Description
Definition at line 111 of file QGVPage.cpp.
Constructor & Destructor Documentation
Private()
TechDrawGui::QGVPage::Private::Private (QGVPage * page) inline explicit
Definition at line 117 of file QGVPage.cpp.
References Base::Subject< MsgType >::Attach(), App::GetApplication(), and App::Application::GetParameterGroupByPath().
Member Function Documentation
detach()
void TechDrawGui::QGVPage::Private::detach () inline
Definition at line 160 of file QGVPage.cpp.
References Base::Subject< MsgType >::Detach(), App::GetApplication(), and App::Application::GetParameterGroupByPath().
init()
void TechDrawGui::QGVPage::Private::init () inline
Definition at line 124 of file QGVPage.cpp.
References ParameterGrp::GetBool(), and ParameterGrp::GetFloat().
Referenced by DocumentObject.DocumentObject::onChanged().
OnChange()
void TechDrawGui::QGVPage::Private::OnChange (ParameterGrp::SubjectType & rCaller, ParameterGrp::MessageType Reason) inline override
Observer message from the ParameterGrp.
Definition at line 134 of file QGVPage.cpp.
References SCL.SimpleDataTypes::f, ParameterGrp::GetASCII(), ParameterGrp::GetBool(), Base::BaseClass::getClassTypeId(), ParameterGrp::GetFloat(), Base::Type::getName(), and TechDrawGui::QGVPage::setNavigationStyle().
Member Data Documentation
hGrp
ParameterGrp::handle TechDrawGui::QGVPage::Private::hGrp
handle to the viewer parameter group
Definition at line 115 of file QGVPage.cpp.
page
QGVPage* TechDrawGui::QGVPage::Private::page
Definition at line 116 of file QGVPage.cpp.
Referenced by TechDrawTools.TaskFillTemplateFields.TaskFillTemplateFields::proceed(), TDTest.DrawViewDimensionTest.DrawViewDimensionTest::testLengthDimension(), TDTest.DrawViewAnnotationTest.DrawViewAnnotationTest::testMakeAnnotation(), TDTest.DrawViewBalloonTest.DrawViewBalloonTest::testMakeDrawViewBalloon(), TDTest.DrawViewPartTest.DrawViewPartTest::testMakeDrawViewPart(), TDTest.DrawViewDetailTest.DrawViewDetailTest::testMakeDrawViewPart(), TDTest.DrawViewSectionTest.DrawViewSectionTest::testMakeDrawViewSection(), TDTest.DrawViewImageTest.DrawViewImageTest::testMakeImage(), TDTest.DrawProjectionGroupTest.DrawProjectionGroupTest::testMakeProjectionGroup(), TDTest.DrawViewSymbolTest.DrawViewSymbolTest::testMakeSymbol(), TDTest.DrawViewSymbolTest.DrawViewSymbolTest::testNonAsciiSymbol(), and TDTest.DrawViewDimensionTest.DrawViewDimensionTest::testRadiusDimension().
The documentation for this class was generated from the following file:
QGVPage.cpp