FreeCAD: ifc4.ifcdayinweeknumber Class Reference
ifc4.ifcdayinweeknumber Class Reference
Public Member Functions
def __init__ (self, *kargs)
def validrange (self)
Detailed Description
Definition at line 612 of file ifc4.py.
Constructor & Destructor Documentation
__init__()
def ifc4.ifcdayinweeknumber.__init__ (self, * kargs)
Definition at line 613 of file ifc4.py.
References ifc4.ifcdayinweeknumber.validrange().
Member Function Documentation
validrange()
def ifc4.ifcdayinweeknumber.validrange (self)
Definition at line 617 of file ifc4.py.
Referenced by ifc4.ifcdayinweeknumber.__init__(), ifc4.ifcdayinmonthnumber.__init__(), and ifc4.ifcmonthinyearnumber.__init__().
The documentation for this class was generated from the following file:
ifc4.py