FreeCAD: TechDraw::ReferenceEntry Class Reference
TechDraw::ReferenceEntry Class Reference
#include <DimensionReferences.h>
Public Member Functions
ReferenceEntry ()=default
ReferenceEntry (App::DocumentObject *docObject, const std::string &subName, App::Document *document=nullptr)
ReferenceEntry (const ReferenceEntry &other)
~ReferenceEntry ()=default
ReferenceEntry & operator= (const ReferenceEntry &otherRef)
bool operator== (const ReferenceEntry &otherRef) const
App::DocumentObject * getObject () const
template<class T >
T * getObject () const
void setObject (App::DocumentObject *docObj)
std::string getSubName (bool longForm=false) const
void setSubName (const std::string &subName)
std::string getObjectName () const
void setObjectName (const std::string &name)
App::Document * getDocument () const
void setDocument (App::Document *document)
TopoDS_Shape getGeometry () const
std::string geomType () const
GeomType geomEdgeType () const
bool isWholeObject () const
Part::TopoShape asTopoShape () const
return the reference geometry as a Part::TopoShape.
Part::TopoShape asCanonicalTopoShape () const
returns unscaled, unrotated version of inShape. inShape is assumed to be a 2d shape, but this is not enforced.
bool is3d () const
true if this reference point to 3d model geometry
bool hasGeometry () const
true if the target of this reference has a shape
Static Public Member Functions
static Part::TopoShape asCanonicalTopoShape (const Part::TopoShape &inShape, const DrawViewPart &dvp)
Detailed Description
Definition at line 54 of file DimensionReferences.h.
Constructor & Destructor Documentation
ReferenceEntry() [1/3]
TechDraw::ReferenceEntry::ReferenceEntry () default
ReferenceEntry() [2/3]
ReferenceEntry::ReferenceEntry (App::DocumentObject * docObject, const std::string & subName, App::Document * document = nullptr)
Definition at line 56 of file DimensionReferences.cpp.
References App::DocumentObject::getDocument(), and App::DocumentObject::getNameInDocument().
ReferenceEntry() [3/3]
ReferenceEntry::ReferenceEntry (const ReferenceEntry & other)
Definition at line 70 of file DimensionReferences.cpp.
References getDocument(), getObject(), getObjectName(), and getSubName().
~ReferenceEntry()
TechDraw::ReferenceEntry::~ReferenceEntry () default
Member Function Documentation
asCanonicalTopoShape() [1/2]
Part::TopoShape ReferenceEntry::asCanonicalTopoShape () const
returns unscaled, unrotated version of inShape. inShape is assumed to be a 2d shape, but this is not enforced.
Definition at line 207 of file DimensionReferences.cpp.
asCanonicalTopoShape() [2/2]
Part::TopoShape ReferenceEntry::asCanonicalTopoShape (const Part::TopoShape & inShape, const DrawViewPart & dvp) static
static public method returns unscaled, unrotated version of inShape. inShape is assumed to be a 2d shape, but this is not enforced. 3d shapes should not be made canonical. 2d shapes are inverted in Y direction and need to be inverted before and after rotation operations.
Definition at line 224 of file DimensionReferences.cpp.
References TechDraw::DrawView::getScale(), Part::TopoShape::getShape(), App::PropertyQuantity::getValue(), TechDraw::ShapeUtils::invertGeometry(), TechDraw::ShapeUtils::rotateShape(), TechDraw::DrawView::Rotation, and TechDraw::ShapeUtils::scaleShape().
asTopoShape()
Part::TopoShape ReferenceEntry::asTopoShape () const
return the reference geometry as a Part::TopoShape.
Definition at line 185 of file DimensionReferences.cpp.
geomEdgeType()
GeomType ReferenceEntry::geomEdgeType () const
Definition at line 258 of file DimensionReferences.cpp.
References draftgeoutils.general::geomType(), TechDraw::DrawUtil::getIndexFromName(), and TechDraw::NOTDEF.
geomType()
std::string ReferenceEntry::geomType () const
Definition at line 253 of file DimensionReferences.cpp.
References TechDraw::DrawUtil::getGeomTypeFromName().
getDocument()
App::Document* TechDraw::ReferenceEntry::getDocument () const inline
Definition at line 72 of file DimensionReferences.h.
Referenced by operator=(), and ReferenceEntry().
getGeometry()
TopoDS_Shape ReferenceEntry::getGeometry () const
Definition at line 99 of file DimensionReferences.cpp.
References Base::Persistence::getClassTypeId(), getLocatedShape(), and UtilsAssembly::getObject().
Referenced by TechDraw::isValidSingleEdge3d(), and TechDraw::isValidSingleFace3d().
getObject() [1/2]
App::DocumentObject * ReferenceEntry::getObject () const
Definition at line 170 of file DimensionReferences.cpp.
Referenced by TechDraw::DimensionAutoCorrect::fixBrokenReferences(), TDHandlerDimension::getSelectionVector(), TechDraw::isValidSingleEdge(), TechDraw::isValidSingleFace(), TechDrawGui::makeArcLengthDimension(), operator=(), and ReferenceEntry().
getObject() [2/2]
template<class T > T* TechDraw::ReferenceEntry::getObject () const inline
Definition at line 66 of file DimensionReferences.h.
References getObject().
Referenced by getObject().
getObjectName()
std::string TechDraw::ReferenceEntry::getObjectName () const inline
Definition at line 70 of file DimensionReferences.h.
Referenced by operator=(), operator==(), and ReferenceEntry().
getSubName()
std::string ReferenceEntry::getSubName (bool longForm = false) const
Definition at line 160 of file DimensionReferences.cpp.
Referenced by TDHandlerDimension::createRadiusDiameterDimension(), TDHandlerDimension::getSelectionVector(), TechDraw::isValidSingleEdge(), TechDraw::isValidSingleEdge3d(), TechDraw::isValidSingleFace(), TechDraw::isValidSingleFace3d(), TechDrawGui::makeArcLengthDimension(), operator=(), operator==(), and ReferenceEntry().
hasGeometry()
bool ReferenceEntry::hasGeometry () const
true if the target of this reference has a shape
Definition at line 299 of file DimensionReferences.cpp.
References Base::Persistence::getClassTypeId(), UtilsAssembly::getObject(), and Part::Feature::getTopoShape().
is3d()
bool ReferenceEntry::is3d () const
true if this reference point to 3d model geometry
Definition at line 277 of file DimensionReferences.cpp.
References Base::Persistence::getClassTypeId(), and UtilsAssembly::getObject().
isWholeObject()
bool ReferenceEntry::isWholeObject () const
Definition at line 271 of file DimensionReferences.cpp.
operator=()
ReferenceEntry & ReferenceEntry::operator= (const ReferenceEntry & otherRef)
Definition at line 80 of file DimensionReferences.cpp.
References getDocument(), getObject(), getObjectName(), and getSubName().
operator==()
bool ReferenceEntry::operator== (const ReferenceEntry & otherRef) const
Definition at line 93 of file DimensionReferences.cpp.
References getObjectName(), and getSubName().
setDocument()
void TechDraw::ReferenceEntry::setDocument (App::Document * document) inline
Definition at line 73 of file DimensionReferences.h.
setObject()
void TechDraw::ReferenceEntry::setObject (App::DocumentObject * docObj) inline
Definition at line 67 of file DimensionReferences.h.
setObjectName()
void TechDraw::ReferenceEntry::setObjectName (const std::string & name) inline
Definition at line 71 of file DimensionReferences.h.
setSubName()
void TechDraw::ReferenceEntry::setSubName (const std::string & subName) inline
Definition at line 69 of file DimensionReferences.h.
The documentation for this class was generated from the following files:
DimensionReferences.h
DimensionReferences.cpp