FreeCAD: CommandLink.cpp File Reference
CommandLink.cpp File Reference
#include "PreCompiled.h"
#include <sstream>
#include <QMessageBox>
#include <App/Application.h>
#include <App/ElementNamingUtils.h>
#include <App/Document.h>
#include <App/DocumentObject.h>
#include <App/Link.h>
#include <Base/Exception.h>
#include <Base/Tools.h>
#include "Action.h"
#include "Application.h"
#include "Command.h"
#include "Document.h"
#include "MainWindow.h"
#include "Selection.h"
#include "Tree.h"
#include "ViewProviderDocumentObject.h"
#include "WaitCursor.h"
Classes
class StdCmdLinkMakeGroup
class StdCmdLinkMake
class StdCmdLinkMakeRelative
struct Info
class StdCmdLinkReplace
class StdCmdLinkUnlink
class StdCmdLinkImport
class StdCmdLinkImportAll
class StdCmdLinkSelectLinked
class StdCmdLinkSelectLinkedFinal
class StdCmdLinkSelectAllLinks
class StdCmdLinkSelectActions
class StdCmdLinkActions
Namespaces
Gui
Functions
static void setLinkLabel (App::DocumentObject *obj, const char *doc, const char *name)
static void linkConvert (bool unlink)
static bool linkConvertible (bool unlink)
static std::map< App::Document *, std::vector< App::DocumentObject * > > getLinkImportSelections ()
static App::DocumentObject * getSelectedLink (bool finalLink, std::string *subname=nullptr)
void Gui::CreateLinkCommands ()
Function Documentation
getLinkImportSelections()
static std::map<App::Document*, std::vector<App::DocumentObject*> > getLinkImportSelections () static
Definition at line 552 of file CommandLink.cpp.
References src.Mod.Test.testPathArray::o, and Gui::Selection().
Referenced by StdCmdLinkImport::activated(), and StdCmdLinkImport::isActive().
getSelectedLink()
static App::DocumentObject* getSelectedLink (bool finalLink, std::string * subname = nullptr) static
Definition at line 658 of file CommandLink.cpp.
References dot(), Gui::SelectionSingleton::getSelection(), Instance, toolbit-attributes::s, Gui::Selection(), and TestSpreadsheet::v.
Referenced by StdCmdLinkSelectLinked::activated(), StdCmdLinkSelectLinkedFinal::activated(), StdCmdLinkSelectLinked::isActive(), and StdCmdLinkSelectLinkedFinal::isActive().
linkConvert()
static void linkConvert (bool unlink) static
Definition at line 353 of file CommandLink.cpp.
References Gui::SelectionSingleton::clearCompleteSelection(), toolbit-attributes::doc, SCL.SimpleDataTypes::e, FC_THROWM, FC_WARN, App::DocumentObject::getLinkedObject(), Gui::getMainWindow(), App::DocumentObject::getNameInDocument(), draftutils.gui_utils::getSelection, Path.Log::info(), Instance, App::DocumentObject::isAttachedToDocument(), Init::parent, RobotExample::pos, Gui::Selection(), Gui::SelectionSingleton::selStackPush(), Plot::title(), and TestSpreadsheet::v.
Referenced by StdCmdLinkReplace::activated(), and StdCmdLinkUnlink::activated().
linkConvertible()
static bool linkConvertible (bool unlink) static
Definition at line 471 of file CommandLink.cpp.
References src.Mod.AddonManager.NetworkManager::count, draftutils.gui_utils::getSelection, and Init::parent.
Referenced by StdCmdLinkReplace::isActive(), and StdCmdLinkUnlink::isActive().
setLinkLabel()
static void setLinkLabel (App::DocumentObject * obj, const char * doc, const char * name) static
Definition at line 53 of file CommandLink.cpp.
References toolbit-attributes::doc, doCommand, and Base::Tools::escapeEncodeString().
Referenced by StdCmdLinkMakeGroup::activated(), StdCmdLinkMake::activated(), and StdCmdLinkMakeRelative::activated().