FreeCAD: PartGui::DlgImportExportStep Class Reference
PartGui::DlgImportExportStep Class Reference
#include <DlgSettingsGeneral.h>
Public Member Functions
DlgImportExportStep (QWidget *parent=nullptr)
~DlgImportExportStep () override
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Protected Member Functions
void saveSettings () override
void loadSettings () override
void changeEvent (QEvent *e) override
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void resetSettingsToDefaults ()
Detailed Description
Definition at line 73 of file Mod/Part/Gui/DlgSettingsGeneral.h.
Constructor & Destructor Documentation
DlgImportExportStep()
DlgImportExportStep::DlgImportExportStep (QWidget * parent = nullptr) explicit
Definition at line 168 of file Mod/Part/Gui/DlgSettingsGeneral.cpp.
~DlgImportExportStep()
DlgImportExportStep::~DlgImportExportStep () override default
Destroys the object and frees any allocated resources
Member Function Documentation
changeEvent()
void DlgImportExportStep::changeEvent (QEvent * e) override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 207 of file Mod/Part/Gui/DlgSettingsGeneral.cpp.
loadSettings()
void DlgImportExportStep::loadSettings () override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 200 of file Mod/Part/Gui/DlgSettingsGeneral.cpp.
References PartGui::DlgExportStep::loadSettings(), PartGui::DlgImportStep::loadSettings(), and PartGui::DlgExportHeaderStep::loadSettings().
saveSettings()
void DlgImportExportStep::saveSettings () override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 193 of file Mod/Part/Gui/DlgSettingsGeneral.cpp.
References PartGui::DlgExportStep::saveSettings(), PartGui::DlgImportStep::saveSettings(), and PartGui::DlgExportHeaderStep::saveSettings().
The documentation for this class was generated from the following files:
Mod/Part/Gui/DlgSettingsGeneral.h
Mod/Part/Gui/DlgSettingsGeneral.cpp