FreeCAD: ifc2x3.ifcdimensionalexponents Class Reference
ifc2x3.ifcdimensionalexponents Class Reference
Public Member Functions
def __init__ (self, lengthexponent, massexponent, timeexponent, electriccurrentexponent, thermodynamictemperatureexponent, amountofsubstanceexponent, luminousintensityexponent)
def lengthexponent ()
def massexponent ()
def timeexponent ()
def electriccurrentexponent ()
def thermodynamictemperatureexponent ()
def amountofsubstanceexponent ()
def luminousintensityexponent ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
lengthexponent
massexponent
timeexponent
electriccurrentexponent
thermodynamictemperatureexponent
amountofsubstanceexponent
luminousintensityexponent
Detailed Description
Entity ifcdimensionalexponents definition.
:param lengthexponent
:type lengthexponent:INTEGER
:param massexponent
:type massexponent:INTEGER
:param timeexponent
:type timeexponent:INTEGER
:param electriccurrentexponent
:type electriccurrentexponent:INTEGER
:param thermodynamictemperatureexponent
:type thermodynamictemperatureexponent:INTEGER
:param amountofsubstanceexponent
:type amountofsubstanceexponent:INTEGER
:param luminousintensityexponent
:type luminousintensityexponent:INTEGER
Definition at line 18796 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcdimensionalexponents.__init__ (self, lengthexponent, massexponent, timeexponent, electriccurrentexponent, thermodynamictemperatureexponent, amountofsubstanceexponent, luminousintensityexponent)
Definition at line 18820 of file ifc2x3.py.
Member Function Documentation
amountofsubstanceexponent()
def ifc2x3.ifcdimensionalexponents.amountofsubstanceexponent ()
Definition at line 18900 of file ifc2x3.py.
References ifc2x3.ifcdimensionalexponents._amountofsubstanceexponent, ifc2x3.ifcdimensionalexponents.amountofsubstanceexponent, and SCL.TypeChecker.check_type().
electriccurrentexponent()
def ifc2x3.ifcdimensionalexponents.electriccurrentexponent ()
Definition at line 18872 of file ifc2x3.py.
References ifc2x3.ifcdimensionalexponents._electriccurrentexponent, SCL.TypeChecker.check_type(), and ifc2x3.ifcdimensionalexponents.electriccurrentexponent.
lengthexponent()
def ifc2x3.ifcdimensionalexponents.lengthexponent ()
Definition at line 18830 of file ifc2x3.py.
References ifc2x3.ifcdimensionalexponents._lengthexponent, SCL.TypeChecker.check_type(), and ifc2x3.ifcdimensionalexponents.lengthexponent.
luminousintensityexponent()
def ifc2x3.ifcdimensionalexponents.luminousintensityexponent ()
Definition at line 18914 of file ifc2x3.py.
References ifc2x3.ifcdimensionalexponents._luminousintensityexponent, SCL.TypeChecker.check_type(), and ifc2x3.ifcdimensionalexponents.luminousintensityexponent.
massexponent()
def ifc2x3.ifcdimensionalexponents.massexponent ()
Definition at line 18844 of file ifc2x3.py.
References ifc2x3.ifcdimensionalexponents._massexponent, SCL.TypeChecker.check_type(), and ifc2x3.ifcdimensionalexponents.massexponent.
thermodynamictemperatureexponent()
def ifc2x3.ifcdimensionalexponents.thermodynamictemperatureexponent ()
Definition at line 18886 of file ifc2x3.py.
References ifc2x3.ifcdimensionalexponents._thermodynamictemperatureexponent, SCL.TypeChecker.check_type(), and ifc2x3.ifcdimensionalexponents.thermodynamictemperatureexponent.
timeexponent()
def ifc2x3.ifcdimensionalexponents.timeexponent ()
Definition at line 18858 of file ifc2x3.py.
References ifc2x3.ifcdimensionalexponents._timeexponent, SCL.TypeChecker.check_type(), and ifc2x3.ifcdimensionalexponents.timeexponent.
Member Data Documentation
amountofsubstanceexponent
ifc2x3.ifcdimensionalexponents.amountofsubstanceexponent
Definition at line 18826 of file ifc2x3.py.
Referenced by ifc2x3.ifcdimensionalexponents.amountofsubstanceexponent().
electriccurrentexponent
ifc2x3.ifcdimensionalexponents.electriccurrentexponent
Definition at line 18824 of file ifc2x3.py.
Referenced by ifc2x3.ifcdimensionalexponents.electriccurrentexponent().
lengthexponent
ifc2x3.ifcdimensionalexponents.lengthexponent
Definition at line 18821 of file ifc2x3.py.
Referenced by ifc2x3.ifcdimensionalexponents.lengthexponent().
luminousintensityexponent
ifc2x3.ifcdimensionalexponents.luminousintensityexponent
Definition at line 18827 of file ifc2x3.py.
Referenced by ifc2x3.ifcdimensionalexponents.luminousintensityexponent().
massexponent
ifc2x3.ifcdimensionalexponents.massexponent
Definition at line 18822 of file ifc2x3.py.
Referenced by ifc2x3.ifcdimensionalexponents.massexponent().
thermodynamictemperatureexponent
ifc2x3.ifcdimensionalexponents.thermodynamictemperatureexponent
Definition at line 18825 of file ifc2x3.py.
Referenced by ifc2x3.ifcdimensionalexponents.thermodynamictemperatureexponent().
timeexponent
ifc2x3.ifcdimensionalexponents.timeexponent
Definition at line 18823 of file ifc2x3.py.
Referenced by ifc2x3.ifcdimensionalexponents.timeexponent().
The documentation for this class was generated from the following file:
ifc2x3.py