FreeCAD: src.Mod.PartDesign.Scripts.FilletArc Namespace Reference
src.Mod.PartDesign.Scripts.FilletArc Namespace Reference
Classes
class Vector
Functions
def sgn (val)
def makeFilletArc (M1, P, Q, N, r2, ccw)
def test ()
Function Documentation
makeFilletArc()
def src.Mod.PartDesign.Scripts.FilletArc.makeFilletArc (M1, P, Q, N, r2, ccw)
Definition at line 71 of file FilletArc.py.
References KDL.abs(), and src.Mod.PartDesign.Scripts.FilletArc.sgn().
sgn()
def src.Mod.PartDesign.Scripts.FilletArc.sgn (val)
Definition at line 54 of file FilletArc.py.
Referenced by src.Mod.PartDesign.Scripts.FilletArc.makeFilletArc().
test()
def src.Mod.PartDesign.Scripts.FilletArc.test ()
Definition at line 111 of file FilletArc.py.