FreeCAD: BOPTools.SplitFeatures.FeatureBooleanFragments Class Reference
BOPTools.SplitFeatures.FeatureBooleanFragments Class Reference
Public Member Functions
def __init__ (self, obj)
def execute (self, selfobj)
Public Attributes
Type
Detailed Description
The BooleanFragments feature object.
Definition at line 64 of file SplitFeatures.py.
Constructor & Destructor Documentation
__init__()
def BOPTools.SplitFeatures.FeatureBooleanFragments.__init__ (self, obj)
Definition at line 67 of file SplitFeatures.py.
Member Function Documentation
execute()
def BOPTools.SplitFeatures.FeatureBooleanFragments.execute (self, selfobj)
Definition at line 81 of file SplitFeatures.py.
Referenced by src.Mod.PartDesign.Scripts.Spring.MySpring.onChanged(), src.Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid.onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped.onChanged(), src.Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt.onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder.onChanged(), and FeaturePython.DistanceBolt.onChanged().
Member Data Documentation
Type
BOPTools.SplitFeatures.FeatureBooleanFragments.Type
Definition at line 79 of file SplitFeatures.py.
The documentation for this class was generated from the following file:
SplitFeatures.py