FreeCAD: Gui::CallTipsList Class Reference
Gui::CallTipsList Class Reference
#include <CallTips.h>
Public Member Functions
CallTipsList (QPlainTextEdit *parent)
Construction.
~CallTipsList () override
Destruction.
void keyboardSearch (const QString &) override
void showTips (const QString &)
void validateCursor ()
Protected Member Functions
bool eventFilter (QObject *, QEvent *) override
void showEvent (QShowEvent *) override
void hideEvent (QHideEvent *) override
Detailed Description
Author
Werner Mayer
Definition at line 50 of file CallTips.h.
Constructor & Destructor Documentation
CallTipsList()
CallTipsList::CallTipsList (QPlainTextEdit * parent)
Construction.
Definition at line 81 of file CallTips.cpp.
References draftgeoutils.intersections::connect(), and Init::parent.
~CallTipsList()
CallTipsList::~CallTipsList () override default
Destruction.
Member Function Documentation
eventFilter()
bool CallTipsList::eventFilter (QObject * watched, QEvent * event) override protected
Get all incoming events of the text edit and redirect some of them, like key up and down, mouse press events, ... to the widget itself.
Definition at line 610 of file CallTips.cpp.
References ArchFence::hide(), src.Mod.Test.testPathArray::items, and buildPsets::p.
hideEvent()
void CallTipsList::hideEvent (QHideEvent * e) override protected
Definition at line 600 of file CallTips.cpp.
References SCL.SimpleDataTypes::e.
keyboardSearch()
void CallTipsList::keyboardSearch (const QString & wordPrefix) override
Definition at line 125 of file CallTips.cpp.
References src.Mod.AddonManager.NetworkManager::count, and SplineSurface::i.
Referenced by validateCursor().
showEvent()
void CallTipsList::showEvent (QShowEvent * e) override protected
Definition at line 593 of file CallTips.cpp.
References SCL.SimpleDataTypes::e.
showTips()
void CallTipsList::showTips (const QString & line)
Definition at line 497 of file CallTips.cpp.
References Gui::BitmapFactory(), Gui::BitmapFactoryInst::BottomLeft, Gui::CallTip::Class, Path.Op.Gui.Selection::clear(), src.Mod.AddonManager.NetworkManager::count, SplineSurface::i, Gui::CallTip::Member, Gui::BitmapFactoryInst::merge(), Gui::CallTip::Method, Gui::CallTip::Module, Gui::BitmapFactoryInst::pixmap(), Gui::CallTip::Property, bimcommands.BimViews::show(), and src.Mod.PartDesign.fcgear.svggear::w.
Referenced by Gui::PythonConsole::keyPressEvent().
validateCursor()
void CallTipsList::validateCursor ()
Definition at line 149 of file CallTips.cpp.
References ArchFence::hide(), and keyboardSearch().
Referenced by Gui::PythonConsole::keyPressEvent().
The documentation for this class was generated from the following files:
CallTips.h
CallTips.cpp