FreeCAD: ResourceManager Class Reference
ResourceManager Class Reference
Static Public Member Functions
static auto ErrorPixmap ()
static auto WarningPixmap ()
static auto CriticalPixmap ()
static auto InfoPixmap ()
static auto NotificationAreaIcon ()
static auto notificationAreaMissedNotificationsIcon ()
Detailed Description
Simple class to manage Notification Area Resources
Definition at line 150 of file NotificationArea.cpp.
Member Function Documentation
CriticalPixmap()
static auto ResourceManager::CriticalPixmap () inline static
Definition at line 187 of file NotificationArea.cpp.
Referenced by NotificationItem::data().
ErrorPixmap()
static auto ResourceManager::ErrorPixmap () inline static
Definition at line 175 of file NotificationArea.cpp.
Referenced by NotificationItem::data().
InfoPixmap()
static auto ResourceManager::InfoPixmap () inline static
Definition at line 193 of file NotificationArea.cpp.
Referenced by NotificationItem::data().
NotificationAreaIcon()
static auto ResourceManager::NotificationAreaIcon () inline static
Definition at line 199 of file NotificationArea.cpp.
notificationAreaMissedNotificationsIcon()
static auto ResourceManager::notificationAreaMissedNotificationsIcon () inline static
Definition at line 205 of file NotificationArea.cpp.
WarningPixmap()
static auto ResourceManager::WarningPixmap () inline static
Definition at line 181 of file NotificationArea.cpp.
Referenced by NotificationItem::data().
The documentation for this class was generated from the following file:
NotificationArea.cpp