FreeCAD: importers.importOBJ Namespace Reference
importers.importOBJ Namespace Reference
Functions
def findVert (aVertex, aList)
def getIndices (obj, shape, offsetv, offsetvn)
def export (exportList, filename, colors=None)
def open (filename)
def insert (filename, docname)
def makeMesh (doc, activeobject, verts, facets, material, colortable)
Function Documentation
export()
def importers.importOBJ.export (exportList, filename, colors = None)
export(exportList,filename,colors=None):
Called when freecad exports a file. exportList is a list
of objects, filename is the .obj file to export (a .mtl
file with same name will also be created together), and
optionally colors can be a dict containing ["objectName:colorTuple"]
pairs for use in non-GUI mode.
Definition at line 133 of file importOBJ.py.
References importers.importOBJ.getIndices(), and Path.Post.scripts.refactored_centroid_post.str.
findVert()
def importers.importOBJ.findVert (aVertex, aList)
Definition at line 52 of file importOBJ.py.
Referenced by importers.importOBJ.getIndices().
getIndices()
def importers.importOBJ.getIndices (obj, shape, offsetv, offsetvn)
Definition at line 62 of file importOBJ.py.
References importers.importOBJ.findVert(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by importers.importOBJ.export().
insert()
def importers.importOBJ.insert (filename, docname)
Definition at line 291 of file importOBJ.py.
References importers.importOBJ.makeMesh().
Referenced by importers.importOBJ.open().
makeMesh()
def importers.importOBJ.makeMesh (doc, activeobject, verts, facets, material, colortable)
Definition at line 366 of file importOBJ.py.
Referenced by importers.importOBJ.insert().
open()
def importers.importOBJ.open (filename)
Definition at line 284 of file importOBJ.py.
References importers.importOBJ.insert().