FreeCAD: CommandCreateView.ViewProviderExplodedViewStep Class Reference
CommandCreateView.ViewProviderExplodedViewStep Class Reference
Public Member Functions
def __init__ (self, vobj)
def attach (self, vobj)
def updateData (self, stepObj, prop)
def redrawLines (self, stepObj, positions)
def getDisplayModes (self, obj)
def getDefaultDisplayMode (self)
def onChanged (self, vp, prop)
def getIcon (self)
def dumps (self)
def loads (self, state)
Public Attributes
app_obj
line_thickness
so_color
draw_style
lineSetGroup
display_mode
Detailed Description
Definition at line 357 of file CommandCreateView.py.
Constructor & Destructor Documentation
__init__()
def CommandCreateView.ViewProviderExplodedViewStep.__init__ (self, vobj)
Set this object to the proxy object of the actual view provider
Definition at line 358 of file CommandCreateView.py.
Referenced by draftguitools.gui_subelements.SubelementHighlight.finish().
Member Function Documentation
attach()
def CommandCreateView.ViewProviderExplodedViewStep.attach (self, vobj)
Setup the scene sub-graph of the view provider, this method is mandatory
Definition at line 362 of file CommandCreateView.py.
Referenced by Path.Dressup.Gui.Boundary.DressupPathBoundaryViewProvider.__init__().
dumps()
def CommandCreateView.ViewProviderExplodedViewStep.dumps (self)
When saving the document this object gets stored using Python's json module.\
Since we have some un-serializable parts here -- the Coin stuff -- we must define this method\
to return a tuple of all serializable objects or None.
Definition at line 430 of file CommandCreateView.py.
getDefaultDisplayMode()
def CommandCreateView.ViewProviderExplodedViewStep.getDefaultDisplayMode (self)
Return the name of the default display mode. It must be defined in getDisplayModes.
Definition at line 418 of file CommandCreateView.py.
getDisplayModes()
def CommandCreateView.ViewProviderExplodedViewStep.getDisplayModes (self, obj)
Return a list of display modes.
Definition at line 412 of file CommandCreateView.py.
getIcon()
def CommandCreateView.ViewProviderExplodedViewStep.getIcon (self)
Definition at line 427 of file CommandCreateView.py.
Referenced by ArchAxisSystem.AxisSystemTaskPanel.update(), ArchWindow._ArchWindowTaskPanel.update(), ArchSectionPlane.SectionPlaneTaskPanel.update(), ArchComponent.ComponentTaskPanel.update(), bimcommands.BimClassification.BIM_Classification.updateByMaterial(), bimcommands.BimClassification.BIM_Classification.updateByTree(), bimcommands.BimClassification.BIM_Classification.updateByType(), and bimcommands.BimClassification.BIM_Classification.updateDefault().
loads()
def CommandCreateView.ViewProviderExplodedViewStep.loads (self, state)
When restoring the serialized object from document we have the chance to set some internals here.\
Since no data were serialized nothing needs to be done here.
Definition at line 436 of file CommandCreateView.py.
Referenced by nativeifc.ifc_objects.ifc_object.__setstate__().
onChanged()
def CommandCreateView.ViewProviderExplodedViewStep.onChanged (self, vp, prop)
Here we can do something when a single property got changed
Definition at line 422 of file CommandCreateView.py.
Referenced by draftviewproviders.view_base.ViewProviderDraft.attach(), ArchSpace._ViewProviderSpace.onChanged(), ArchSchedule._ArchSchedule.setProperties(), draftviewproviders.view_wpproxy.ViewProviderWorkingPlaneProxy.updateData(), draftviewproviders.view_layer.ViewProviderLayer.updateData(), draftviewproviders.view_label.ViewProviderLabel.updateData(), ArchAxis._ViewProviderAxis.updateData(), draftviewproviders.view_dimension.ViewProviderLinearDimension.updateData(), ArchSpace._ViewProviderSpace.updateData(), ArchBuildingPart.ViewProviderBuildingPart.updateData(), ArchPanel.ViewProviderPanelCut.updateData(), ArchSite._ViewProviderSite.updateData(), ArchSectionPlane._ViewProviderSectionPlane.updateData(), and ArchPanel.ViewProviderPanelSheet.updateData().
redrawLines()
def CommandCreateView.ViewProviderExplodedViewStep.redrawLines (self, stepObj, positions)
Definition at line 391 of file CommandCreateView.py.
updateData()
def CommandCreateView.ViewProviderExplodedViewStep.updateData (self, stepObj, prop)
If a property of the handled feature has changed we have the chance to handle this here
Definition at line 386 of file CommandCreateView.py.
Referenced by Path.Main.Gui.JobDlg.JobCreate.exec_(), draftviewproviders.view_wire.ViewProviderWire.onChanged(), draftviewproviders.view_dimension.ViewProviderLinearDimension.onChanged(), draftviewproviders.view_dimension.ViewProviderAngularDimension.onChanged(), Path.Op.Gui.Base.TaskPanelPage.pageUpdateData(), Path.Base.Gui.SetupSheet.OpTaskPanel.setupUi(), and Path.Base.Gui.PropertyBag.TaskPanel.setupUi().
Member Data Documentation
app_obj
CommandCreateView.ViewProviderExplodedViewStep.app_obj
Definition at line 364 of file CommandCreateView.py.
Referenced by JointObject.ViewProviderJoint.getIcon().
display_mode
CommandCreateView.ViewProviderExplodedViewStep.display_mode
Definition at line 382 of file CommandCreateView.py.
draw_style
CommandCreateView.ViewProviderExplodedViewStep.draw_style
Definition at line 374 of file CommandCreateView.py.
Referenced by SoSwitchMarker.SoSwitchMarker.line_sep().
line_thickness
CommandCreateView.ViewProviderExplodedViewStep.line_thickness
Definition at line 368 of file CommandCreateView.py.
lineSetGroup
CommandCreateView.ViewProviderExplodedViewStep.lineSetGroup
Definition at line 380 of file CommandCreateView.py.
so_color
CommandCreateView.ViewProviderExplodedViewStep.so_color
Definition at line 371 of file CommandCreateView.py.
The documentation for this class was generated from the following file:
CommandCreateView.py