FreeCAD: stepZ Namespace Reference
stepZ Namespace Reference
Functions
def mkz_string (input)
def mkz_unicode (input)
def sayz (msg)
def sayzw (msg)
def sayzerr (msg)
def import_stpz (fn, fc, doc)
def open (filename, doc=None)
def insert (filename, doc)
def export (objs, filename)
Function Documentation
export()
def stepZ.export (objs, filename)
exporting to file folder
Definition at line 138 of file stepZ.py.
References sayz(), and sayzw().
import_stpz()
def stepZ.import_stpz (fn, fc, doc)
Definition at line 80 of file stepZ.py.
References sayzerr().
Referenced by open().
insert()
def stepZ.insert (filename, doc)
Definition at line 129 of file stepZ.py.
References open().
mkz_string()
def stepZ.mkz_string (input)
Definition at line 42 of file stepZ.py.
mkz_unicode()
def stepZ.mkz_unicode (input)
Definition at line 51 of file stepZ.py.
open()
def stepZ.open (filename, doc = None)
Definition at line 108 of file stepZ.py.
References import_stpz(), and sayz().
Referenced by insert().
sayz()
def stepZ.sayz (msg)
Definition at line 60 of file stepZ.py.
Referenced by export(), and open().
sayzerr()
def stepZ.sayzerr (msg)
Definition at line 72 of file stepZ.py.
Referenced by import_stpz().
sayzw()
def stepZ.sayzw (msg)
Definition at line 66 of file stepZ.py.
Referenced by export().