FreeCAD: AppTechDrawGui.cpp File Reference
AppTechDrawGui.cpp File Reference
#include "PreCompiled.h"
#include <QFontDatabase>
#include <Base/Console.h>
#include <Base/Interpreter.h>
#include <Gui/Application.h>
#include <Gui/Language/Translator.h>
#include <Gui/WidgetFactory.h>
#include "DlgPrefsTechDrawAdvancedImp.h"
#include "DlgPrefsTechDrawAnnotationImp.h"
#include "DlgPrefsTechDrawColorsImp.h"
#include "DlgPrefsTechDrawDimensionsImp.h"
#include "DlgPrefsTechDrawGeneralImp.h"
#include "DlgPrefsTechDrawHLRImp.h"
#include "DlgPrefsTechDrawScaleImp.h"
#include "MDIViewPage.h"
#include "ViewProviderAnnotation.h"
#include "ViewProviderBalloon.h"
#include "ViewProviderCosmeticExtension.h"
#include "ViewProviderDimension.h"
#include "ViewProviderDrawingView.h"
#include "ViewProviderDrawingViewExtension.h"
#include "ViewProviderGeomHatch.h"
#include "ViewProviderHatch.h"
#include "ViewProviderImage.h"
#include "ViewProviderLeader.h"
#include "ViewProviderPage.h"
#include "ViewProviderPageExtension.h"
#include "ViewProviderProjGroup.h"
#include "ViewProviderProjGroupItem.h"
#include "ViewProviderRichAnno.h"
#include "ViewProviderSpreadsheet.h"
#include "ViewProviderSymbol.h"
#include "ViewProviderTemplate.h"
#include "ViewProviderTemplateExtension.h"
#include "ViewProviderTile.h"
#include "ViewProviderViewClip.h"
#include "ViewProviderViewPart.h"
#include "ViewProviderViewSection.h"
#include "ViewProviderWeld.h"
#include "Workbench.h"
Namespaces
TechDrawGui
Functions
void CreateTechDrawCommands ()
void CreateTechDrawCommandsDims ()
void CreateTechDrawCommandsDecorate ()
void CreateTechDrawCommandsAnnotate ()
void CreateTechDrawCommandsExtensionDims ()
void CreateTechDrawCommandsExtensions ()
void CreateTechDrawCommandsStack ()
void loadTechDrawResource ()
PyObject * TechDrawGui::initModule ()
PyMOD_INIT_FUNC (TechDrawGui)
Function Documentation
CreateTechDrawCommands()
void CreateTechDrawCommands ()
Definition at line 1932 of file Mod/TechDraw/Gui/Command.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
CreateTechDrawCommandsAnnotate()
void CreateTechDrawCommandsAnnotate ()
Definition at line 1671 of file CommandAnnotate.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
CreateTechDrawCommandsDecorate()
void CreateTechDrawCommandsDecorate ()
Definition at line 368 of file CommandDecorate.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
CreateTechDrawCommandsDims()
void CreateTechDrawCommandsDims ()
Definition at line 2356 of file CommandCreateDims.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
CreateTechDrawCommandsExtensionDims()
void CreateTechDrawCommandsExtensionDims ()
Definition at line 2536 of file CommandExtensionDims.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
CreateTechDrawCommandsExtensions()
void CreateTechDrawCommandsExtensions ()
Definition at line 2225 of file CommandExtensionPack.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
CreateTechDrawCommandsStack()
void CreateTechDrawCommandsStack ()
Definition at line 407 of file CommandStack.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
loadTechDrawResource()
void loadTechDrawResource ()
Definition at line 78 of file AppTechDrawGui.cpp.
References Base::Console(), App::Application::getResourceDir(), Gui::Translator::instance(), Gui::Translator::refresh(), and Base::ConsoleSingleton::Warning().
Referenced by PyMOD_INIT_FUNC().
PyMOD_INIT_FUNC()
PyMOD_INIT_FUNC (TechDrawGui)
Definition at line 107 of file AppTechDrawGui.cpp.
References Base::Console(), CreateTechDrawCommands(), CreateTechDrawCommandsAnnotate(), CreateTechDrawCommandsDecorate(), CreateTechDrawCommandsDims(), CreateTechDrawCommandsExtensionDims(), CreateTechDrawCommandsExtensions(), CreateTechDrawCommandsStack(), SCL.SimpleDataTypes::e, Base::Persistence::init(), Base::BaseClass::init(), App::Extension::init(), TechDrawGui::MDIViewPagePy::init_type(), TechDrawGui::initModule(), Gui::Application::Instance, Base::Interpreter(), Base::InterpreterSingleton::loadModule(), loadTechDrawResource(), Base::ConsoleSingleton::Log(), mod, PyMOD_Return, and Arch::QT_TRANSLATE_NOOP.