FreeCAD: Gui::PolyClipSelection Class Reference
Gui::PolyClipSelection Class Reference
#include <MouseSelection.h>
Public Member Functions
PolyClipSelection ()
~PolyClipSelection () override
void setRole (SelectionRole pos, bool on)
bool testRole (SelectionRole pos) const
Public Member Functions inherited from Gui::PolyPickerSelection
PolyPickerSelection ()
~PolyPickerSelection () override
void setLineWidth (float l)
void setColor (float r, float g, float b, float a=1.0)
void initialize () override
implement this in derived classes
void terminate (bool abort=false) override
implement this in derived classes
Public Member Functions inherited from Gui::BaseMouseSelection
BaseMouseSelection ()
~BaseMouseSelection () override=default
Public Member Functions inherited from Gui::AbstractMouseSelection
AbstractMouseSelection ()
virtual ~AbstractMouseSelection ()=default
void grabMouseModel (Gui::View3DInventorViewer *)
void releaseMouseModel (bool abort=false)
const std::vector< SbVec2s > & getPositions () const
SelectionRole selectedRole () const
int handleEvent (const SoEvent *const ev, const SbViewportRegion &vp)
Protected Member Functions
int popupMenu () override
Protected Member Functions inherited from Gui::PolyPickerSelection
int mouseButtonEvent (const SoMouseButtonEvent *const e, const QPoint &pos) override
int locationEvent (const SoLocation2Event *const e, const QPoint &pos) override
int keyboardEvent (const SoKeyboardEvent *const e) override
void draw () override
draw the polygon
Protected Member Functions inherited from Gui::AbstractMouseSelection
Additional Inherited Members
Public Types inherited from Gui::AbstractMouseSelection
enum {
Continue =0, Restart =1, Finish =2, Cancel =3,
Ignore =4
}
Protected Attributes inherited from Gui::PolyPickerSelection
Gui::Polyline polyline
bool lastConfirmed
Protected Attributes inherited from Gui::AbstractMouseSelection
Gui::View3DInventorViewer * _pcView3D {nullptr}
QCursor m_cPrevCursor
int m_iXold
int m_iYold
int m_iXnew
int m_iYnew
SelectionRole m_selectedRole
std::vector< SbVec2s > _clPoly
Detailed Description
The poly clip mouse model class Create a polygon
Author
Werner Mayer
Definition at line 157 of file MouseSelection.h.
Constructor & Destructor Documentation
PolyClipSelection()
PolyClipSelection::PolyClipSelection ()
Definition at line 353 of file MouseSelection.cpp.
~PolyClipSelection()
PolyClipSelection::~PolyClipSelection () override default
Member Function Documentation
popupMenu()
int PolyClipSelection::popupMenu () override protected virtual
Reimplemented from Gui::PolyPickerSelection.
Definition at line 361 of file MouseSelection.cpp.
References Gui::AbstractMouseSelection::Cancel, Gui::AbstractMouseSelection::Finish, Gui::AbstractMouseSelection::getPositions(), Gui::Inner, Gui::AbstractMouseSelection::m_selectedRole, NavigationIndicatorGui::menu, Gui::None, Gui::Outer, RobotExample::pos, Gui::AbstractMouseSelection::Restart, Gui::Split, and testRole().
setRole()
void Gui::PolyClipSelection::setRole (SelectionRole pos, bool on) inline
Definition at line 163 of file MouseSelection.h.
References RobotExample::pos.
testRole()
bool Gui::PolyClipSelection::testRole (SelectionRole pos) const inline
Definition at line 166 of file MouseSelection.h.
References RobotExample::pos.
Referenced by popupMenu().
The documentation for this class was generated from the following files:
MouseSelection.h
MouseSelection.cpp