FreeCAD: ifc2x3.ifctablerow Class Reference
ifc2x3.ifctablerow Class Reference
Public Member Functions
def __init__ (self, rowcells, isheading)
def rowcells ()
def isheading ()
def oftable ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
rowcells
isheading
Detailed Description
Entity ifctablerow definition.
:param rowcells
:type rowcells:LIST(1,None,'ifcvalue', scope = schema_scope)
:param isheading
:type isheading:BOOLEAN
:param oftable
:type oftable:ifctable
Definition at line 17924 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifctablerow.__init__ (self, rowcells, isheading)
Definition at line 17936 of file ifc2x3.py.
Member Function Documentation
isheading()
def ifc2x3.ifctablerow.isheading ()
Definition at line 17955 of file ifc2x3.py.
References ifc2x3.ifctablerow._isheading, SCL.SimpleDataTypes.BOOLEAN, SCL.TypeChecker.check_type(), and ifc2x3.ifctablerow.isheading.
oftable()
def ifc2x3.ifctablerow.oftable ()
Definition at line 17969 of file ifc2x3.py.
rowcells()
def ifc2x3.ifctablerow.rowcells ()
Definition at line 17941 of file ifc2x3.py.
References ifc2x3.ifctablerow._rowcells, SCL.TypeChecker.check_type(), and ifc2x3.ifctablerow.rowcells.
Referenced by ifc2x3.ifctable.numberofcellsinrow(), and ifc4.ifctable.numberofcellsinrow().
Member Data Documentation
isheading
ifc2x3.ifctablerow.isheading
Definition at line 17938 of file ifc2x3.py.
Referenced by ifc2x3.ifctablerow.isheading().
rowcells
ifc2x3.ifctablerow.rowcells
Definition at line 17937 of file ifc2x3.py.
Referenced by ifc2x3.ifctable.numberofcellsinrow(), ifc4.ifctable.numberofcellsinrow(), and ifc2x3.ifctablerow.rowcells().
The documentation for this class was generated from the following file:
ifc2x3.py