FreeCAD: Base::Polygon2d Class Reference
Base::Polygon2d Class Reference
#include <Tools2D.h>
Public Member Functions
Polygon2d ()=default
Polygon2d (const Polygon2d &)=default
Polygon2d (Polygon2d &&)=default
~Polygon2d ()=default
Polygon2d & operator= (const Polygon2d &rclP)
Polygon2d & operator= (Polygon2d &&rclP) noexcept
size_t GetCtVectors () const
bool Add (const Vector2d &rclVct)
const Vector2d & operator[] (size_t ulNdx) const
const Vector2d & At (size_t ulNdx) const
Vector2d & operator[] (size_t ulNdx)
Vector2d & At (size_t ulNdx)
bool Delete (size_t ulNdx)
void DeleteAll ()
BoundBox2d CalcBoundBox () const
bool Contains (const Vector2d &rclV) const
void Intersect (const Polygon2d &rclPolygon, std::list< Polygon2d > &rclResultPolygonList) const
bool Intersect (const Polygon2d &other) const
bool Intersect (const Vector2d &rclV, double eps) const
Detailed Description
Polygon2d 2D polygon class.
Definition at line 196 of file Tools2D.h.
Constructor & Destructor Documentation
Polygon2d() [1/3]
Base::Polygon2d::Polygon2d () default
Polygon2d() [2/3]
Base::Polygon2d::Polygon2d (const Polygon2d &) inline default
Polygon2d() [3/3]
Base::Polygon2d::Polygon2d (Polygon2d &&) inline default
~Polygon2d()
Base::Polygon2d::~Polygon2d () default
Member Function Documentation
Add()
bool Base::Polygon2d::Add (const Vector2d & rclVct) inline
Definition at line 417 of file Tools2D.h.
Referenced by PointsGui::ViewProviderScattered::cut(), PointsGui::ViewProviderStructured::cut(), getBoxSelection(), Intersect(), and MeshGui::ViewProviderMesh::trimMesh().
At() [1/2]
Vector2d & Base::Polygon2d::At (size_t ulNdx) inline
Definition at line 450 of file Tools2D.h.
References Base::Line2d::CalcBoundBox(), and Base::BoundBox2d::Contains().
At() [2/2]
const Vector2d & Base::Polygon2d::At (size_t ulNdx) const inline
Definition at line 440 of file Tools2D.h.
References Base::Line2d::clV1, and Base::Line2d::clV2.
Referenced by Intersect().
CalcBoundBox()
BoundBox2d Polygon2d::CalcBoundBox () const
POLYGON2d
Definition at line 249 of file Tools2D.cpp.
References SplineSurface::i, Base::BoundBox2d::MaxX, Base::BoundBox2d::MaxY, Base::BoundBox2d::MinX, and Base::BoundBox2d::MinY.
Referenced by MeshCore::MeshTrimming::CheckFacets(), MeshCore::MeshAlgorithm::CheckFacets(), and getBoxSelection().
Contains()
bool Polygon2d::Contains (const Vector2d & rclV) const
Definition at line 301 of file Tools2D.cpp.
References CalcTorsion(), GetCtVectors(), SplineSurface::i, Base::Vector2d::x, and Base::Vector2d::y.
Referenced by MeshCore::MeshAlgorithm::CheckFacets(), PointsGui::ViewProviderScattered::cut(), PointsGui::ViewProviderStructured::cut(), Base::BoundBox2d::Intersect(), and Intersect().
Delete()
bool Base::Polygon2d::Delete (size_t ulNdx) inline
Definition at line 423 of file Tools2D.h.
DeleteAll()
void Base::Polygon2d::DeleteAll () inline
Definition at line 407 of file Tools2D.h.
Referenced by Intersect().
GetCtVectors()
size_t Base::Polygon2d::GetCtVectors () const inline
Definition at line 412 of file Tools2D.h.
Referenced by Contains(), Base::BoundBox2d::Intersect(), and Intersect().
Intersect() [1/3]
bool Polygon2d::Intersect (const Polygon2d & other) const
Definition at line 416 of file Tools2D.cpp.
References At(), Contains(), GetCtVectors(), SplineSurface::i, Base::Line2d::IntersectAndContain(), TestSpreadsheet::v, and draftgeoutils.general::v1().
Intersect() [2/3]
void Polygon2d::Intersect (const Polygon2d & rclPolygon, std::list< Polygon2d > & rclResultPolygonList) const
Definition at line 341 of file Tools2D.cpp.
References Add(), At(), Contains(), DeleteAll(), Base::Line2d::FromPos(), GetCtVectors(), SplineSurface::i, Base::Line2d::IntersectAndContain(), and FreeCADInit::Length.
Intersect() [3/3]
bool Polygon2d::Intersect (const Vector2d & rclV, double eps) const
Definition at line 453 of file Tools2D.cpp.
References GetCtVectors(), and SplineSurface::i.
operator=() [1/2]
Polygon2d & Base::Polygon2d::operator= (const Polygon2d & rclP) inline default
operator=() [2/2]
Polygon2d & Base::Polygon2d::operator= (Polygon2d && rclP) inline default noexcept
operator[]() [1/2]
Vector2d & Base::Polygon2d::operator[] (size_t ulNdx) inline
Definition at line 445 of file Tools2D.h.
References Base::Line2d::clV1, and Base::Line2d::clV2.
operator[]() [2/2]
const Vector2d & Base::Polygon2d::operator[] (size_t ulNdx) const inline
Definition at line 435 of file Tools2D.h.
The documentation for this class was generated from the following files:
Tools2D.h
Tools2D.cpp