FreeCAD: Gui::Dialog::CustomizeActionPage Class Reference
Gui::Dialog::CustomizeActionPage Class Reference abstract
#include <PropertyPage.h>
Public Member Functions
CustomizeActionPage (QWidget *parent=nullptr)
~CustomizeActionPage () override
Protected Slots
virtual void onAddMacroAction (const QByteArray &)=0
virtual void onRemoveMacroAction (const QByteArray &)=0
virtual void onModifyMacroAction (const QByteArray &)=0
Protected Member Functions
bool event (QEvent *e) override
void changeEvent (QEvent *e) override=0
Detailed Description
Base class for custom pages.
Author
Werner Mayer
Definition at line 167 of file PropertyPage.h.
Constructor & Destructor Documentation
CustomizeActionPage()
CustomizeActionPage::CustomizeActionPage (QWidget * parent = nullptr) explicit
Construction
Definition at line 239 of file PropertyPage.cpp.
~CustomizeActionPage()
CustomizeActionPage::~CustomizeActionPage () override default
Destruction
Member Function Documentation
changeEvent()
void CustomizeActionPage::changeEvent (QEvent * e) override protected pure virtual
Implemented in Gui::Dialog::DlgCustomizeSpaceball, Gui::Dialog::DlgCustomToolBoxbarsImp, Gui::Dialog::DlgCustomKeyboardImp, Gui::Dialog::DlgCustomToolbarsImp, Gui::Dialog::DlgCustomizeSpNavSettings, Gui::Dialog::DlgCustomToolbars, and Gui::Dialog::DlgCustomActionsImp.
Definition at line 280 of file PropertyPage.cpp.
References SCL.SimpleDataTypes::e.
event()
bool CustomizeActionPage::event (QEvent * e) override protected
Definition at line 246 of file PropertyPage.cpp.
References draftgeoutils.intersections::connect(), SCL.SimpleDataTypes::e, onAddMacroAction(), onModifyMacroAction(), and onRemoveMacroAction().
Referenced by Gui::Dialog::DlgCustomizeSpaceball::event(), Gui::Dialog::DlgCustomToolbars::hideEvent(), and Gui::Dialog::DlgCustomToolbarsImp::showEvent().
onAddMacroAction
virtual void Gui::Dialog::CustomizeActionPage::onAddMacroAction (const QByteArray &) protected pure virtual slot
Referenced by event().
onModifyMacroAction
virtual void Gui::Dialog::CustomizeActionPage::onModifyMacroAction (const QByteArray &) protected pure virtual slot
Referenced by event().
onRemoveMacroAction
virtual void Gui::Dialog::CustomizeActionPage::onRemoveMacroAction (const QByteArray &) protected pure virtual slot
Referenced by event().
The documentation for this class was generated from the following files:
PropertyPage.h
PropertyPage.cpp