FreeCAD: Wm4::IntrTriangle3Triangle3< Real > Class Template Reference
Wm4::IntrTriangle3Triangle3< Real > Class Template Reference
#include <Wm4IntrTriangle3Triangle3.h>
Public Member Functions
IntrTriangle3Triangle3 (const Triangle3< Real > &rkTriangle0, const Triangle3< Real > &rkTriangle1)
const Triangle3< Real > & GetTriangle0 () const
const Triangle3< Real > & GetTriangle1 () const
virtual bool Test ()
virtual bool Find ()
virtual bool Test (Real fTMax, const Vector3< Real > &rkVelocity0, const Vector3< Real > &rkVelocity1)
virtual bool Find (Real fTMax, const Vector3< Real > &rkVelocity0, const Vector3< Real > &rkVelocity1)
int GetQuantity () const
const Vector3< Real > & GetPoint (int i) const
Public Member Functions inherited from Wm4::Intersector< Real, Vector3< Real > >
virtual ~Intersector ()
Real GetContactTime () const
int GetIntersectionType () const
Public Attributes
bool ReportCoplanarIntersections
Additional Inherited Members
Public Types inherited from Wm4::Intersector< Real, Vector3< Real > >
enum
Protected Member Functions inherited from Wm4::Intersector< Real, Vector3< Real > >
Intersector ()
Protected Attributes inherited from Wm4::Intersector< Real, Vector3< Real > >
Real m_fContactTime
int m_iIntersectionType
Detailed Description
template<class Real>
class Wm4::IntrTriangle3Triangle3< Real >
Definition at line 30 of file Wm4IntrTriangle3Triangle3.h.
Constructor & Destructor Documentation
IntrTriangle3Triangle3()
template<class Real > Wm4::IntrTriangle3Triangle3< Real >::IntrTriangle3Triangle3 (const Triangle3< Real > & rkTriangle0, const Triangle3< Real > & rkTriangle1)
Definition at line 27 of file Wm4IntrTriangle3Triangle3.cpp.
References Wm4::IntrTriangle3Triangle3< Real >::ReportCoplanarIntersections.
Member Function Documentation
Find() [1/2]
template<class Real > bool Wm4::IntrTriangle3Triangle3< Real >::Find virtual
Reimplemented from Wm4::Intersector< Real, Vector3< Real > >.
Definition at line 147 of file Wm4IntrTriangle3Triangle3.cpp.
References SplineSurface::i.
Find() [2/2]
template<class Real > bool Wm4::IntrTriangle3Triangle3< Real >::Find (Real fTMax, const Vector3< Real > & rkVelocity0, const Vector3< Real > & rkVelocity1) virtual
Reimplemented from Wm4::Intersector< Real, Vector3< Real > >.
Definition at line 339 of file Wm4IntrTriangle3Triangle3.cpp.
References Wm4::Vector3< Real >::Dot(), Wm4::Vector3< Real >::UnitCross(), and Wm4::Triangle3< Real >::V.
GetPoint()
template<class Real > const Vector3< Real > & Wm4::IntrTriangle3Triangle3< Real >::GetPoint (int i) const
Definition at line 451 of file Wm4IntrTriangle3Triangle3.cpp.
References SplineSurface::i.
GetQuantity()
template<class Real > int Wm4::IntrTriangle3Triangle3< Real >::GetQuantity
Definition at line 445 of file Wm4IntrTriangle3Triangle3.cpp.
GetTriangle0()
template<class Real > const Triangle3< Real > & Wm4::IntrTriangle3Triangle3< Real >::GetTriangle0
Definition at line 38 of file Wm4IntrTriangle3Triangle3.cpp.
GetTriangle1()
template<class Real > const Triangle3< Real > & Wm4::IntrTriangle3Triangle3< Real >::GetTriangle1
Definition at line 44 of file Wm4IntrTriangle3Triangle3.cpp.
Test() [1/2]
template<class Real > bool Wm4::IntrTriangle3Triangle3< Real >::Test virtual
Reimplemented from Wm4::Intersector< Real, Vector3< Real > >.
Definition at line 50 of file Wm4IntrTriangle3Triangle3.cpp.
References Wm4::Vector3< Real >::Dot(), and Wm4::Vector3< Real >::UnitCross().
Test() [2/2]
template<class Real > bool Wm4::IntrTriangle3Triangle3< Real >::Test (Real fTMax, const Vector3< Real > & rkVelocity0, const Vector3< Real > & rkVelocity1) virtual
Reimplemented from Wm4::Intersector< Real, Vector3< Real > >.
Definition at line 254 of file Wm4IntrTriangle3Triangle3.cpp.
References Wm4::Vector3< Real >::Dot(), and Wm4::Vector3< Real >::UnitCross().
Member Data Documentation
ReportCoplanarIntersections
template<class Real > bool Wm4::IntrTriangle3Triangle3< Real >::ReportCoplanarIntersections
Definition at line 41 of file Wm4IntrTriangle3Triangle3.h.
Referenced by Wm4::IntrTriangle3Triangle3< Real >::IntrTriangle3Triangle3().
The documentation for this class was generated from the following files:
Wm4IntrTriangle3Triangle3.h
Wm4IntrTriangle3Triangle3.cpp