FreeCAD: Path.Op.Gui.ThreadMilling Namespace Reference
Path.Op.Gui.ThreadMilling Namespace Reference
Classes
class TaskPanelOpPage
Functions
def fillThreads (form, dataFile, defaultSelect)
Variables
translate
Command
Function Documentation
fillThreads()
def Path.Op.Gui.ThreadMilling.fillThreads (form, dataFile, defaultSelect)
Definition at line 53 of file Gui/ThreadMilling.py.
References Path.Log.debug(), and AssemblyImport.open().
Referenced by Path.Op.Gui.ThreadMilling.TaskPanelOpPage.setFields().
Variable Documentation
Command
Path.Op.Gui.ThreadMilling.Command
Definition at line 244 of file Gui/ThreadMilling.py.
translate
Path.Op.Gui.ThreadMilling.translate
Definition at line 50 of file Gui/ThreadMilling.py.