FreeCAD: ZoomableView Class Reference
ZoomableView Class Reference
#include <ZoomableView.h>
Public Slots
void zoomIn (void)
void zoomOut (void)
This function is the slot for the zoomIn button and a keyboard shortcut.
void resetZoom (void)
This function is the slot for the zoomOut button and a keyboard shortcut.
Signals
void zoomLevelChanged (int)
Public Member Functions
ZoomableView (Ui::Sheet *ui)
A descendant of QGraphicsView to show a SheetTableView object in its viewport, allowing magnification.
~ZoomableView () override=default
int zoomLevel () const
void setZoomLevel (int new_scale)
Static Public Member Functions
static void checkLimits (int &zoom_level)
Static Public Attributes
static constexpr int min {60}
static constexpr int max {160}
Protected Member Functions
void keyPressEvent (QKeyEvent *event) override
void resizeEvent (QResizeEvent *event) override
void wheelEvent (QWheelEvent *event) override
Static Protected Attributes
static constexpr int zoom_step_mwheel {5}
static constexpr int zoom_step_kb {10}
Properties
int zoomLevel
Detailed Description
Definition at line 36 of file ZoomableView.h.
Constructor & Destructor Documentation
ZoomableView()
ZoomableView::ZoomableView (Ui::Sheet * ui) explicit
A descendant of QGraphicsView to show a SheetTableView object in its viewport, allowing magnification.
Parameters
ui The object replaces SheetTableView in layout, handling mouse and keyboard events.
Definition at line 31 of file ZoomableView.cpp.
~ZoomableView()
ZoomableView::~ZoomableView () override default
Member Function Documentation
checkLimits()
void ZoomableView::checkLimits (int & zoom_level) inline static
Definition at line 145 of file ZoomableView.cpp.
References max, and min.
Referenced by setZoomLevel().
keyPressEvent()
void ZoomableView::keyPressEvent (QKeyEvent * event) override protected
Definition at line 190 of file ZoomableView.cpp.
References resetZoom(), zoomIn(), and zoomOut().
resetZoom
void ZoomableView::resetZoom (void) slot
This function is the slot for the zoomOut button and a keyboard shortcut.
Definition at line 160 of file ZoomableView.cpp.
References App::GetApplication(), ParameterGrp::GetInt(), App::Application::GetParameterGroupByPath(), src.Mod.Test.testPathArray::path, and setZoomLevel().
Referenced by keyPressEvent().
resizeEvent()
void ZoomableView::resizeEvent (QResizeEvent * event) override protected
Definition at line 215 of file ZoomableView.cpp.
setZoomLevel()
void ZoomableView::setZoomLevel (int new_scale)
Definition at line 132 of file ZoomableView.cpp.
References checkLimits(), and zoomLevelChanged().
Referenced by resetZoom(), wheelEvent(), zoomIn(), and zoomOut().
wheelEvent()
void ZoomableView::wheelEvent (QWheelEvent * event) override protected
Definition at line 221 of file ZoomableView.cpp.
References setZoomLevel(), MovieTool::y, and zoom_step_mwheel.
zoomIn
void ZoomableView::zoomIn (void) slot
This signal is emitted whenever zoom level is changed. It is used to show the zoom level in the zoom button.
Definition at line 150 of file ZoomableView.cpp.
References setZoomLevel(), and zoom_step_kb.
Referenced by keyPressEvent().
zoomLevel()
int ZoomableView::zoomLevel () const
zoomLevelChanged
void ZoomableView::zoomLevelChanged (int) signal
Referenced by setZoomLevel().
zoomOut
void ZoomableView::zoomOut (void) slot
This function is the slot for the zoomIn button and a keyboard shortcut.
Definition at line 155 of file ZoomableView.cpp.
References setZoomLevel(), and zoom_step_kb.
Referenced by keyPressEvent().
Member Data Documentation
max
constexpr int ZoomableView::max {160} static
Definition at line 53 of file ZoomableView.h.
Referenced by checkLimits().
min
constexpr int ZoomableView::min {60} static constexpr
Definition at line 53 of file ZoomableView.h.
Referenced by checkLimits().
zoom_step_kb
constexpr int ZoomableView::zoom_step_kb {10} static protected
Definition at line 80 of file ZoomableView.h.
Referenced by zoomIn(), and zoomOut().
zoom_step_mwheel
constexpr int ZoomableView::zoom_step_mwheel {5} static constexpr protected
Definition at line 80 of file ZoomableView.h.
Referenced by wheelEvent().
Property Documentation
zoomLevel
int ZoomableView::zoomLevel read
Definition at line 39 of file ZoomableView.h.
The documentation for this class was generated from the following files:
ZoomableView.h
ZoomableView.cpp