FreeCAD: Import::ReaderStep Class Reference
Import::ReaderStep Class Reference
#include <ReaderStep.h>
Public Member Functions
ReaderStep (const Base::FileInfo &file)
void setCodePage (Resource_FormatType cp)
void read (Handle(TDocStd_Document) hDoc)
Detailed Description
Definition at line 56 of file ReaderStep.h.
Constructor & Destructor Documentation
ReaderStep()
ReaderStep::ReaderStep (const Base::FileInfo & file) explicit
Definition at line 41 of file ReaderStep.cpp.
Member Function Documentation
read()
void ReaderStep::read (Handle(TDocStd_Document) hDoc)
Definition at line 49 of file ReaderStep.cpp.
References Part::encodeFilename(), Base::FileInfo::filePath(), Handle(), and ClipperLib::pi.
setCodePage()
void Import::ReaderStep::setCodePage (Resource_FormatType cp) inline
Definition at line 79 of file ReaderStep.h.
The documentation for this class was generated from the following files:
ReaderStep.h
ReaderStep.cpp