FreeCAD: Base::Builder3D Class Reference
Base::Builder3D Class Reference
#include <Builder3D.h>
Public Member Functions
Builder3D ()
~Builder3D ()
void clear ()
clear the string buffer
write the result
void saveToLog ()
sends the result to the log and gui
void saveToFile (const char *FileName)
save the result to a file (*.iv)
void addNode (const NodeItem &)
addNode Writes the content of the added node to the output stream.
void beginSeparator ()
Sets a separator node.
void endSeparator ()
Closes the last added separator node.
Builder3D (const Builder3D &)=delete
Builder3D (Builder3D &&)=delete
Builder3D & operator= (const Builder3D &)=delete
Builder3D & operator= (Builder3D &&)=delete
Detailed Description
A Builder class for 3D representations on App level On the application level nothing is known of the visual representation of data. Nevertheless it's often needed to see some 3D information, e.g. points, directions, when you program or debug an algorithm. Builder3D was made for this specific purpose. This class allows you to easily build up a 3D representation of some mathematical and algorithm internals. You can save this representation to a file and view it in an Inventor viewer, or send it to the log. In the case of using the log and a debug FreeCAD the representation will be loaded into the active viewer.
The workflow goes as follows: Create the a Builder3D object and call the methods to insert the graphical elements. After that call either saveToLog() or saveToFile().
Usage:
Base::Builder3D log3D;
for (unsigned long i=0; i<pMesh->CountPoints(); i++)
{
  log3D.addSinglePoint(pMesh->GetPoint(i));
  log3D.addText(pMesh->GetPoint(i),"Point");
  ...
}
log3D.saveToLog();
See also
Base::ConsoleSingleton
Definition at line 746 of file Builder3D.h.
Constructor & Destructor Documentation
Builder3D() [1/3]
Builder3D::Builder3D ()
A constructor. A more elaborate description of the constructor.
Definition at line 989 of file Builder3D.cpp.
~Builder3D()
Builder3D::~Builder3D () default
A destructor. A more elaborate description of the destructor.
Builder3D() [2/3]
Base::Builder3D::Builder3D (const Builder3D &) delete
Builder3D() [3/3]
Base::Builder3D::Builder3D (Builder3D &&) delete
Member Function Documentation
addNode()
void Builder3D::addNode (const NodeItem & item)
addNode Writes the content of the added node to the output stream.
Definition at line 1047 of file Builder3D.cpp.
References Base::InventorBuilder::addNode().
Referenced by MeshPart::MeshAlgos::offsetSpecial2(), and Mesh::MeshObject::offsetSpecial2().
beginSeparator()
void Builder3D::beginSeparator ()
Sets a separator node.
Definition at line 1052 of file Builder3D.cpp.
References Base::InventorBuilder::beginSeparator().
clear()
void Builder3D::clear ()
clear the string buffer
Definition at line 1000 of file Builder3D.cpp.
Referenced by src.Mod.Test.Document.DocumentObserverCases.Observer::__init__(), and src.Mod.Test.Document.DocumentObserverCases.GuiObserver::__init__().
endSeparator()
void Builder3D::endSeparator ()
Closes the last added separator node.
Definition at line 1057 of file Builder3D.cpp.
References Base::InventorBuilder::endSeparator().
operator=() [1/2]
Builder3D& Base::Builder3D::operator= (Builder3D &&) delete
operator=() [2/2]
Builder3D& Base::Builder3D::operator= (const Builder3D &) delete
saveToFile()
void Builder3D::saveToFile (const char * FileName)
save the result to a file (*.iv)
Save the resulting inventor 3D representation to a file. Ending should be *.iv. That enables you to show the result in a Inventor Viewer or in FreeCAD by: /code Gui.document().addAnnotation("Debug","MyFile.iv") /endcode
See also
saveToFile()
Definition at line 1036 of file Builder3D.cpp.
References DrawingExample::file.
saveToLog()
void Builder3D::saveToLog ()
sends the result to the log and gui
Save the resulting inventor 3D representation to the Console().Log() facility. In DEBUG mode the Gui (if running) will trigger on that and show the representation in the active Viewer/Document. It shows only one representation on time. If you need to show more then one representation use saveToFile() instead.
See also
saveToFile()
Definition at line 1016 of file Builder3D.cpp.
References Base::Console(), Base::Developer, Base::ConsoleSingleton::Get(), Base::Log, Base::ILogger::SendLog(), and Base::Untranslatable.
Referenced by MeshPart::MeshAlgos::offsetSpecial2(), and Mesh::MeshObject::offsetSpecial2().
The documentation for this class was generated from the following files:
Builder3D.h
Builder3D.cpp