FreeCAD: MeshCore::MeshDistanceGenericSurfaceFitSegment Class Reference
MeshCore::MeshDistanceGenericSurfaceFitSegment Class Reference
#include <Segmentation.h>
Public Member Functions
MeshDistanceGenericSurfaceFitSegment (AbstractSurfaceFit *, const MeshKernel &mesh, unsigned long minFacets, float tol)
~MeshDistanceGenericSurfaceFitSegment () override
MeshDistanceGenericSurfaceFitSegment (const MeshDistanceGenericSurfaceFitSegment &)=delete
MeshDistanceGenericSurfaceFitSegment (MeshDistanceGenericSurfaceFitSegment &&)=delete
MeshDistanceGenericSurfaceFitSegment & operator= (const MeshDistanceGenericSurfaceFitSegment &)=delete
MeshDistanceGenericSurfaceFitSegment & operator= (MeshDistanceGenericSurfaceFitSegment &&)=delete
bool TestFacet (const MeshFacet &face) const override
const char * GetType () const override
void Initialize (FacetIndex) override
bool TestInitialFacet (FacetIndex) const override
void AddFacet (const MeshFacet &face) override
std::vector< float > Parameters () const
Public Member Functions inherited from MeshCore::MeshDistanceSurfaceSegment
MeshDistanceSurfaceSegment (const MeshKernel &mesh, unsigned long minFacets, float tol)
Public Member Functions inherited from MeshCore::MeshSurfaceSegment
MeshSurfaceSegment (unsigned long minFacets)
virtual ~MeshSurfaceSegment ()=default
MeshSurfaceSegment (const MeshSurfaceSegment &)=delete
MeshSurfaceSegment (MeshSurfaceSegment &&)=delete
MeshSurfaceSegment & operator= (const MeshSurfaceSegment &)=delete
MeshSurfaceSegment & operator= (MeshSurfaceSegment &&)=delete
void AddSegment (const std::vector< FacetIndex > &)
const std::vector< MeshSegment > & GetSegments () const
MeshSegment FindSegment (FacetIndex) const
Additional Inherited Members
Protected Attributes inherited from MeshCore::MeshDistanceSurfaceSegment
const MeshKernel & kernel
float tolerance
Detailed Description
Definition at line 249 of file Mesh/App/Core/Segmentation.h.
Constructor & Destructor Documentation
MeshDistanceGenericSurfaceFitSegment() [1/3]
MeshDistanceGenericSurfaceFitSegment::MeshDistanceGenericSurfaceFitSegment (AbstractSurfaceFit * fit, const MeshKernel & mesh, unsigned long minFacets, float tol)
Definition at line 402 of file Mesh/App/Core/Segmentation.cpp.
~MeshDistanceGenericSurfaceFitSegment()
MeshDistanceGenericSurfaceFitSegment::~MeshDistanceGenericSurfaceFitSegment () override
Definition at line 410 of file Mesh/App/Core/Segmentation.cpp.
MeshDistanceGenericSurfaceFitSegment() [2/3]
MeshCore::MeshDistanceGenericSurfaceFitSegment::MeshDistanceGenericSurfaceFitSegment (const MeshDistanceGenericSurfaceFitSegment &) delete
MeshDistanceGenericSurfaceFitSegment() [3/3]
MeshCore::MeshDistanceGenericSurfaceFitSegment::MeshDistanceGenericSurfaceFitSegment (MeshDistanceGenericSurfaceFitSegment &&) delete
Member Function Documentation
AddFacet()
void MeshDistanceGenericSurfaceFitSegment::AddFacet (const MeshFacet & face) override virtual
Reimplemented from MeshCore::MeshSurfaceSegment.
Definition at line 447 of file Mesh/App/Core/Segmentation.cpp.
References MeshCore::AbstractSurfaceFit::AddTriangle(), MeshCore::MeshKernel::GetFacet(), and MeshCore::MeshDistanceSurfaceSegment::kernel.
GetType()
const char* MeshCore::MeshDistanceGenericSurfaceFitSegment::GetType () const inline override virtual
Implements MeshCore::MeshSurfaceSegment.
Definition at line 266 of file Mesh/App/Core/Segmentation.h.
Initialize()
void MeshDistanceGenericSurfaceFitSegment::Initialize (FacetIndex index) override virtual
Reimplemented from MeshCore::MeshSurfaceSegment.
Definition at line 415 of file Mesh/App/Core/Segmentation.cpp.
References MeshCore::MeshKernel::GetFacet(), MeshCore::AbstractSurfaceFit::Initialize(), and MeshCore::MeshDistanceSurfaceSegment::kernel.
operator=() [1/2]
MeshDistanceGenericSurfaceFitSegment& MeshCore::MeshDistanceGenericSurfaceFitSegment::operator= (const MeshDistanceGenericSurfaceFitSegment &) delete
operator=() [2/2]
MeshDistanceGenericSurfaceFitSegment& MeshCore::MeshDistanceGenericSurfaceFitSegment::operator= (MeshDistanceGenericSurfaceFitSegment &&) delete
Parameters()
std::vector< float > MeshDistanceGenericSurfaceFitSegment::Parameters () const
Definition at line 453 of file Mesh/App/Core/Segmentation.cpp.
References MeshCore::AbstractSurfaceFit::Parameters().
TestFacet()
bool MeshDistanceGenericSurfaceFitSegment::TestFacet (const MeshFacet & face) const override virtual
Implements MeshCore::MeshSurfaceSegment.
Definition at line 432 of file Mesh/App/Core/Segmentation.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, MeshCore::AbstractSurfaceFit::Done(), MeshCore::AbstractSurfaceFit::Fit(), MeshCore::AbstractSurfaceFit::GetDistanceToSurface(), MeshCore::MeshKernel::GetFacet(), MeshCore::MeshDistanceSurfaceSegment::kernel, MeshCore::AbstractSurfaceFit::TestTriangle(), and MeshCore::MeshDistanceSurfaceSegment::tolerance.
TestInitialFacet()
bool MeshDistanceGenericSurfaceFitSegment::TestInitialFacet (FacetIndex index) const override virtual
Reimplemented from MeshCore::MeshSurfaceSegment.
Definition at line 421 of file Mesh/App/Core/Segmentation.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, MeshCore::AbstractSurfaceFit::GetDistanceToSurface(), MeshCore::MeshKernel::GetFacet(), MeshCore::MeshDistanceSurfaceSegment::kernel, MeshCore::AbstractSurfaceFit::TestTriangle(), and MeshCore::MeshDistanceSurfaceSegment::tolerance.
The documentation for this class was generated from the following files:
Mesh/App/Core/Segmentation.h
Mesh/App/Core/Segmentation.cpp