FreeCAD: Gui::OverlayTitleBar Class Reference
Gui::OverlayTitleBar Class Reference
Title bar for OverlayTabWidget.
#include <OverlayWidgets.h>
Public Member Functions
OverlayTitleBar (QWidget *parent)
void setTitleItem (QLayoutItem *)
void endDrag ()
Protected Member Functions
void mouseMoveEvent (QMouseEvent *ev) override
void mousePressEvent (QMouseEvent *ev) override
void mouseReleaseEvent (QMouseEvent *ev) override
void paintEvent (QPaintEvent *ev) override
void keyPressEvent (QKeyEvent *ke) override
void timerEvent (QTimerEvent *te) override
Detailed Description
Title bar for OverlayTabWidget.
Definition at line 420 of file OverlayWidgets.h.
Constructor & Destructor Documentation
OverlayTitleBar()
OverlayTitleBar::OverlayTitleBar (QWidget * parent) explicit
Definition at line 1962 of file OverlayWidgets.cpp.
Member Function Documentation
endDrag()
void OverlayTitleBar::endDrag ()
Definition at line 2052 of file OverlayWidgets.cpp.
Referenced by keyPressEvent(), and mouseMoveEvent().
keyPressEvent()
void OverlayTitleBar::keyPressEvent (QKeyEvent * ke) override protected
Definition at line 2178 of file OverlayWidgets.cpp.
References endDrag().
mouseMoveEvent()
void OverlayTitleBar::mouseMoveEvent (QMouseEvent * ev) override protected
Definition at line 2064 of file OverlayWidgets.cpp.
References Gui::OverlayManager::dragDockWidget(), endDrag(), Gui::OverlayManager::instance(), and isNear().
mousePressEvent()
void OverlayTitleBar::mousePressEvent (QMouseEvent * ev) override protected
Definition at line 2102 of file OverlayWidgets.cpp.
References Gui::OverlayParams::getDockOverlayMinimumSize(), Gui::getMainWindow(), Gui::OverlayTabWidget::getSplitter(), KDL::max(), KDL::min(), Init::parent, and toolbit-attributes::s.
mouseReleaseEvent()
void OverlayTitleBar::mouseReleaseEvent (QMouseEvent * ev) override protected
Definition at line 2145 of file OverlayWidgets.cpp.
References Gui::OverlayManager::dragDockWidget(), and Gui::OverlayManager::instance().
paintEvent()
void OverlayTitleBar::paintEvent (QPaintEvent * ev) override protected
Definition at line 1975 of file OverlayWidgets.cpp.
References Gui::OverlayTabWidget::dockWidget(), Gui::OverlayTabWidget::getDockArea(), Gui::OverlayManager::instance(), and Plot::title().
setTitleItem()
void OverlayTitleBar::setTitleItem (QLayoutItem * item)
Definition at line 1970 of file OverlayWidgets.cpp.
Referenced by Gui::OverlayManager::Private::createTitleBar().
timerEvent()
void OverlayTitleBar::timerEvent (QTimerEvent * te) override protected
Definition at line 2037 of file OverlayWidgets.cpp.
The documentation for this class was generated from the following files:
OverlayWidgets.h
OverlayWidgets.cpp