FreeCAD: Gui::PrefQuantitySpinBox Class Reference
Gui::PrefQuantitySpinBox Class Reference
#include <PrefWidgets.h>
Public Member Functions
PrefQuantitySpinBox (QWidget *parent=nullptr)
~PrefQuantitySpinBox () override
void setToLastUsedValue ()
set the input field to the last used value (works only if the setParamGrpPath() was called)
int historySize () const
get the value of the history size property
void setHistorySize (int)
set the value of the history size property
Public Member Functions inherited from Gui::QuantitySpinBox
QuantitySpinBox (QWidget *parent=nullptr)
~QuantitySpinBox () override
Base::Quantity value () const
Get the current quantity.
double rawValue () const
Get the current quantity without unit.
void normalize ()
bool isNormalized ()
bool hasValidInput () const
Base::Unit unit () const
void setUnit (const Base::Unit &unit)
void setUnitText (const QString &)
Set the unit property.
QString unitText ()
Get the unit property.
double singleStep () const
Get the value of the singleStep property.
void setSingleStep (double val)
Set the value of the singleStep property.
double minimum () const
Gets the value of the minimum property.
void setMinimum (double min)
Sets the value of the minimum property.
double maximum () const
Gets the value of the maximum property.
void setMaximum (double max)
Sets the value of the maximum property.
int decimals () const
Gets the number of decimals.
void setDecimals (int v)
Sets the number of decimals.
void setSchema (const Base::UnitSystem &s)
void clearSchema ()
Clears the schemaand again use the system-wide schema.
QString boundToName () const
Gets the path of the bound property.
void setBoundToByName (const QString &path)
Sets the path of the bound property.
QString expressionText () const
Gets the expression as a string.
void evaluateExpression ()
void selectNumber ()
Set the number portion selected.
void setRange (double min, double max)
void checkRangeInExpression (bool)
bool isCheckedRangeInExpresion () const
Base::Quantity valueFromText (const QString &text) const
QString textFromValue (const Base::Quantity &val) const
void stepBy (int steps) override
void clear () override
QValidator::State validate (QString &input, int &pos) const override
void fixup (QString &str) const override
QSize sizeForText (const QString &) const
This is a helper function to determine the size this widget requires to fully display the text.
QSize sizeHint () const override
QSize minimumSizeHint () const override
bool event (QEvent *event) override
void setNumberExpression (App::NumberExpression *) override
void bind (const App::ObjectIdentifier &_path) override
bool apply (const std::string &propName) override
Public Member Functions inherited from Gui::ExpressionSpinBox
ExpressionSpinBox (QAbstractSpinBox *)
~ExpressionSpinBox () override
void bind (const App::ObjectIdentifier &_path) override
void setExpression (std::shared_ptr< App::Expression > expr) override
Public Member Functions inherited from Gui::ExpressionWidget
ExpressionWidget ()
QPixmap getIcon (const char *name, const QSize &size) const
Public Member Functions inherited from Gui::ExpressionBinding
ExpressionBinding ()
virtual ~ExpressionBinding ()
virtual void bind (const App::Property &prop)
bool isBound () const
void unbind ()
virtual bool apply ()
bool hasExpression () const
bool autoApply () const
void setAutoApply (bool value)
Public Member Functions inherited from Gui::PrefWidget
void setEntryName (const QByteArray &name)
QByteArray entryName () const
void setPrefEntry (const QByteArray &name)
void setParamGrpPath (const QByteArray &path)
QByteArray paramGrpPath () const
void setPrefPath (const QByteArray &name)
void OnChange (Base::Subject< const char * > &rCaller, const char *sReason) override
void onSave ()
void onRestore ()
Public Member Functions inherited from Gui::WindowParameter
WindowParameter (const char *name)
~WindowParameter () override
void OnChange (Base::Subject< const char * > &rCaller, const char *sReason) override
ParameterGrp::handle getWindowParameter ()
return the parameter group of this window
Properties
QByteArray prefEntry
QByteArray prefPath
int historySize
Properties inherited from Gui::QuantitySpinBox
QString unit
double minimum
double maximum
double singleStep
double rawValue
Base::Quantity value
QString binding
QString expression
history and default management
void pushToHistory (const QString &value=QString())
push a new value to the history, if no string given the actual text of the input field is used.
QStringList getHistory () const
get the history of the field, newest first
void contextMenuEvent (QContextMenuEvent *event) override
void restorePreferences () override
void savePreferences () override
Additional Inherited Members
Public Slots inherited from Gui::QuantitySpinBox
void setValue (const Base::Quantity &val)
Sets the field with a quantity.
void setValue (double)
Set a numerical value which gets converted to a quantity with the currently set unit type.
Signals inherited from Gui::QuantitySpinBox
void valueChanged (const Base::Quantity &)
void valueChanged (double)
void textChanged (const QString &)
void showFormulaDialog (bool)
Static Public Member Functions inherited from Gui::WindowParameter
static ParameterGrp::handle getDefaultParameter ()
get the parameters
Protected Types inherited from Gui::ExpressionSpinBox
enum Number { Number::KeepCurrent = 0, Number::SetIfNumber = 1 }
Protected Slots inherited from Gui::QuantitySpinBox
void userInput (const QString &text)
void handlePendingEmit (bool updateUnit=true)
Protected Member Functions inherited from Gui::QuantitySpinBox
void setExpression (std::shared_ptr< App::Expression > expr) override
void openFormulaDialog () override
void showIcon () override
StepEnabled stepEnabled () const override
void showEvent (QShowEvent *event) override
void hideEvent (QHideEvent *event) override
void closeEvent (QCloseEvent *event) override
void focusInEvent (QFocusEvent *event) override
void focusOutEvent (QFocusEvent *event) override
void keyPressEvent (QKeyEvent *event) override
void resizeEvent (QResizeEvent *event) override
void paintEvent (QPaintEvent *event) override
Protected Member Functions inherited from Gui::ExpressionSpinBox
void showInvalidExpression (const QString &)
void showValidExpression (Number number)
void clearExpression ()
void updateExpression ()
void onChange () override
void resizeWidget ()
bool handleKeyEvent (const QString &)
void drawControl (QStyleOptionSpinBox &)
Protected Member Functions inherited from Gui::ExpressionWidget
void makeLabel (QLineEdit *parent)
Protected Member Functions inherited from Gui::ExpressionBinding
const App::ObjectIdentifier & getPath () const
std::shared_ptr< App::Expression > getExpression () const
std::string getExpressionString (bool no_throw=true) const
std::string getEscapedExpressionString () const
bool assignToProperty (const std::string &propName, double)
void expressionChange (const App::ObjectIdentifier &id)
void objectDeleted (const App::DocumentObject &)
Protected Member Functions inherited from Gui::PrefWidget
void failedToSave (const QString &) const
void failedToRestore (const QString &) const
PrefWidget ()
~PrefWidget () override
Protected Member Functions inherited from Gui::WindowParameter
bool setGroupName (const char *name)
template<typename S , typename T >
void setSlotParamChanged (S slot, T *obsPtr)
connect slot to ParameterManager signal
Protected Attributes inherited from Gui::ExpressionSpinBox
QLineEdit * lineedit
QAbstractSpinBox * spinbox
Protected Attributes inherited from Gui::ExpressionWidget
ExpressionLabel * iconLabel {nullptr}
QPalette defaultPalette
int iconHeight {-1}
Protected Attributes inherited from Gui::ExpressionBinding
boost::signals2::scoped_connection expressionchanged
boost::signals2::scoped_connection objectdeleted
bool m_autoApply {false}
Protected Attributes inherited from Gui::PrefWidget
bool m_Restored = false
Detailed Description
The PrefQuantitySpinBox class.
Author
Werner Mayer
Definition at line 385 of file PrefWidgets.h.
Constructor & Destructor Documentation
PrefQuantitySpinBox()
PrefQuantitySpinBox::PrefQuantitySpinBox (QWidget * parent = nullptr) explicit
Definition at line 661 of file PrefWidgets.cpp.
~PrefQuantitySpinBox()
PrefQuantitySpinBox::~PrefQuantitySpinBox () override default
Member Function Documentation
contextMenuEvent()
void PrefQuantitySpinBox::contextMenuEvent (QContextMenuEvent * event) override protected
Definition at line 669 of file PrefWidgets.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Gui::QuantitySpinBox::event(), NavigationIndicatorGui::menu, and pushToHistory().
getHistory()
QStringList PrefQuantitySpinBox::getHistory () const
get the history of the field, newest first
Definition at line 757 of file PrefWidgets.cpp.
Referenced by setToLastUsedValue().
historySize()
int Gui::PrefQuantitySpinBox::historySize () const
get the value of the history size property
pushToHistory()
void PrefQuantitySpinBox::pushToHistory (const QString & value = QString())
push a new value to the history, if no string given the actual text of the input field is used.
Definition at line 748 of file PrefWidgets.cpp.
References Gui::PrefWidget::onSave(), and Gui::QuantitySpinBox::value.
Referenced by contextMenuEvent().
restorePreferences()
void PrefQuantitySpinBox::restorePreferences () override protected virtual
Restores the preferences Must be reimplemented in any subclasses.
Implements Gui::PrefWidget.
Definition at line 711 of file PrefWidgets.cpp.
References Gui::PrefWidget::entryName(), Gui::PrefWidget::failedToRestore(), ParameterGrp::GetGroup(), Gui::WindowParameter::getWindowParameter(), and draftgeoutils.general::isNull().
savePreferences()
void PrefQuantitySpinBox::savePreferences () override protected virtual
Save the preferences Must be reimplemented in any subclasses.
Implements Gui::PrefWidget.
Definition at line 733 of file PrefWidgets.cpp.
References Gui::PrefWidget::entryName(), Gui::PrefWidget::failedToSave(), ParameterGrp::GetGroup(), Gui::WindowParameter::getWindowParameter(), draftgeoutils.general::isNull(), and ParameterGrp::SetASCII().
setHistorySize()
void PrefQuantitySpinBox::setHistorySize (int i)
set the value of the history size property
Definition at line 776 of file PrefWidgets.cpp.
References SplineSurface::i.
setToLastUsedValue()
void PrefQuantitySpinBox::setToLastUsedValue ()
set the input field to the last used value (works only if the setParamGrpPath() was called)
Definition at line 763 of file PrefWidgets.cpp.
References getHistory().
Property Documentation
historySize
int PrefQuantitySpinBox::historySize read write
Definition at line 391 of file PrefWidgets.h.
prefEntry
QByteArray Gui::PrefQuantitySpinBox::prefEntry read write
Definition at line 389 of file PrefWidgets.h.
prefPath
QByteArray Gui::PrefQuantitySpinBox::prefPath read write
Definition at line 390 of file PrefWidgets.h.
The documentation for this class was generated from the following files:
PrefWidgets.h
PrefWidgets.cpp