FreeCAD: TechDrawGui::PATPathMaker Class Reference
TechDrawGui::PATPathMaker Class Reference
#include <PATPathMaker.h>
Public Member Functions
PATPathMaker (QGraphicsItem *parent=nullptr, double lineWidth=0.50, double fillScale=1.0)
~PATPathMaker ()=default
void setLineWidth (double width)
void setScale (double scale)
void setPen (QPen pen)
QPen getPen ()
void setParent (QGraphicsItem *parent)
void lineSetToFillItems (TechDraw::LineSet &ls)
convert the PAT line set to QGraphicsPathItems
Protected Member Functions
QGraphicsPathItem * geomToLine (TechDraw::BaseGeomPtr base, TechDraw::LineSet &ls)
create a PAT fill line from geometry
QGraphicsPathItem * geomToStubbyLine (TechDraw::BaseGeomPtr base, double offset, TechDraw::LineSet &ls)
make a fragment (length = remain) of a dashed line, with pattern starting at +offset
QGraphicsPathItem * lineFromPoints (Base::Vector3d start, Base::Vector3d end, TechDraw::DashSpec ds)
create a PAT fill line from 2 points and a dash configuration
std::vector< double > offsetDash (const std::vector< double > dv, const double offset)
convert a dash pattern to an offset dash pattern (ie offset -> end)
QPainterPath dashedPPath (const std::vector< double > dv, const Base::Vector3d start, const Base::Vector3d end)
make a dashed QPainterPath from start to end in scene coords
double dashRemain (const std::vector< double > dv, const double offset)
find remaining length of a dash pattern after offset
double calcOffset (TechDraw::BaseGeomPtr g, TechDraw::LineSet ls)
std::vector< double > decodeDashSpec (TechDraw::DashSpec d)
convert from mm to scene units
Detailed Description
Definition at line 57 of file PATPathMaker.h.
Constructor & Destructor Documentation
PATPathMaker()
PATPathMaker::PATPathMaker (QGraphicsItem * parent = nullptr, double lineWidth = 0.50, double fillScale = 1.0) explicit
Definition at line 45 of file PATPathMaker.cpp.
References RobotExample::l.
~PATPathMaker()
TechDrawGui::PATPathMaker::~PATPathMaker () default
Member Function Documentation
calcOffset()
double TechDrawGui::PATPathMaker::calcOffset (TechDraw::BaseGeomPtr g, TechDraw::LineSet ls) protected
dashedPPath()
QPainterPath PATPathMaker::dashedPPath (const std::vector< double > dv, const Base::Vector3d start, const Base::Vector3d end) protected
make a dashed QPainterPath from start to end in scene coords
Definition at line 182 of file PATPathMaker.cpp.
References Base::Console(), FreeCADInit::Length, Base::Vector3< float_type >::Normalize(), result, Base::ConsoleSingleton::Warning(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by geomToLine(), geomToStubbyLine(), and lineFromPoints().
dashRemain()
double PATPathMaker::dashRemain (const std::vector< double > dv, const double offset) protected
find remaining length of a dash pattern after offset
Definition at line 267 of file PATPathMaker.cpp.
Referenced by lineSetToFillItems().
decodeDashSpec()
std::vector< double > PATPathMaker::decodeDashSpec (TechDraw::DashSpec d) protected
convert from mm to scene units
Definition at line 160 of file PATPathMaker.cpp.
References TechDraw::DashSpec::get(), TechDrawGui::Rez::guiX(), and result.
Referenced by geomToLine(), geomToStubbyLine(), lineFromPoints(), and lineSetToFillItems().
geomToLine()
QGraphicsPathItem * PATPathMaker::geomToLine (TechDraw::BaseGeomPtr base, TechDraw::LineSet & ls) protected
create a PAT fill line from geometry
Definition at line 112 of file PATPathMaker.cpp.
References dashedPPath(), decodeDashSpec(), TechDraw::LineSet::getDashSpec(), and TechDrawGui::Rez::guiX().
Referenced by lineSetToFillItems().
geomToStubbyLine()
QGraphicsPathItem * PATPathMaker::geomToStubbyLine (TechDraw::BaseGeomPtr base, double offset, TechDraw::LineSet & ls) protected
make a fragment (length = remain) of a dashed line, with pattern starting at +offset
Definition at line 129 of file PATPathMaker.cpp.
References TechDrawGui::Rez::appX(), dashedPPath(), decodeDashSpec(), TechDraw::LineSet::getDashSpec(), TechDraw::LineSet::getUnitDir(), TechDrawGui::Rez::guiX(), TechDraw::DashSpec::length(), FreeCADInit::Length, and offsetDash().
Referenced by lineSetToFillItems().
getPen()
QPen TechDrawGui::PATPathMaker::getPen () inline
Definition at line 86 of file PATPathMaker.h.
Referenced by lineSetToFillItems().
lineFromPoints()
QGraphicsPathItem * PATPathMaker::lineFromPoints (Base::Vector3d start, Base::Vector3d end, TechDraw::DashSpec ds) protected
create a PAT fill line from 2 points and a dash configuration
Definition at line 101 of file PATPathMaker.cpp.
References dashedPPath(), decodeDashSpec(), and TechDrawGui::Rez::guiX().
Referenced by lineSetToFillItems().
lineSetToFillItems()
void PATPathMaker::lineSetToFillItems (TechDraw::LineSet & ls)
convert the PAT line set to QGraphicsPathItems
Definition at line 55 of file PATPathMaker.cpp.
References Base::Console(), dashRemain(), decodeDashSpec(), geomToLine(), geomToStubbyLine(), TechDraw::LineSet::getDashSpec(), TechDraw::LineSet::getGeoms(), TechDraw::LineSet::getPatternStartPoint(), getPen(), TechDrawGui::Rez::guiX(), TechDraw::LineSet::isDashed(), Base::Vector3< float_type >::IsEqual(), lineFromPoints(), TechDraw::DashSpec::reversed(), and Base::ConsoleSingleton::Warning().
Referenced by TechDrawGui::QGIFace::lineSetToFillItems().
offsetDash()
std::vector< double > PATPathMaker::offsetDash (const std::vector< double > dv, const double offset) protected
convert a dash pattern to an offset dash pattern (ie offset -> end)
Definition at line 229 of file PATPathMaker.cpp.
References SplineSurface::i, and result.
Referenced by geomToStubbyLine().
setLineWidth()
void TechDrawGui::PATPathMaker::setLineWidth (double width) inline
Definition at line 83 of file PATPathMaker.h.
Referenced by TechDrawGui::QGIFace::lineSetToFillItems().
setParent()
void TechDrawGui::PATPathMaker::setParent (QGraphicsItem * parent) inline
Definition at line 87 of file PATPathMaker.h.
setPen()
void TechDrawGui::PATPathMaker::setPen (QPen pen) inline
Definition at line 85 of file PATPathMaker.h.
Referenced by TechDrawGui::QGIFace::lineSetToFillItems().
setScale()
void TechDrawGui::PATPathMaker::setScale (double scale) inline
Definition at line 84 of file PATPathMaker.h.
Referenced by TechDrawGui::QGIFace::lineSetToFillItems().
The documentation for this class was generated from the following files:
PATPathMaker.h
PATPathMaker.cpp