FreeCAD: feminout.importFenicsMesh Namespace Reference
feminout.importFenicsMesh Namespace Reference
Classes
class WriteXDMFTaskPanel
Functions
def open (filename)
def insert (filename, docname)
def export (objectslist, fileString, group_values_dict_nogui=None)
def import_fenics_mesh (filename, analysis=None)
Function Documentation
export()
def feminout.importFenicsMesh.export (objectslist, fileString, group_values_dict_nogui = None)
Called when freecad exports a file.
group_dict_no_gui: dictionary with group_numbers as keys and tuples
of (marked_value (default=1), default_value (default=0))
Definition at line 154 of file importFenicsMesh.py.
import_fenics_mesh()
def feminout.importFenicsMesh.import_fenics_mesh (filename, analysis = None)
insert a FreeCAD FEM Mesh object in the ActiveDocument
Definition at line 197 of file importFenicsMesh.py.
Referenced by feminout.importFenicsMesh.insert().
insert()
def feminout.importFenicsMesh.insert (filename, docname)
Definition at line 144 of file importFenicsMesh.py.
References feminout.importFenicsMesh.import_fenics_mesh().
Referenced by feminout.importFenicsMesh.open().
open()
def feminout.importFenicsMesh.open (filename)
Definition at line 138 of file importFenicsMesh.py.
References feminout.importFenicsMesh.insert().