FreeCAD: Gui::SoFCPathAnnotation Class Reference
Gui::SoFCPathAnnotation Class Reference
#include <SoFCUnifiedSelection.h>
Public Member Functions
SoFCPathAnnotation ()
void setPath (SoPath *)
SoPath * getPath ()
void setDetail (SoDetail *d)
SoDetail * getDetail ()
void GLRenderBelowPath (SoGLRenderAction *action) override
void GLRender (SoGLRenderAction *action) override
void GLRenderInPath (SoGLRenderAction *action) override
void getBoundingBox (SoGetBoundingBoxAction *action) override
Static Public Member Functions
static void initClass ()
static void finish ()
Protected Member Functions
~SoFCPathAnnotation () override
Protected Attributes
SoPath * path
SoTempPath * tmpPath
SoDetail * det
Detailed Description
Definition at line 131 of file SoFCUnifiedSelection.h.
Constructor & Destructor Documentation
SoFCPathAnnotation()
SoFCPathAnnotation::SoFCPathAnnotation ()
Definition at line 1705 of file SoFCUnifiedSelection.cpp.
~SoFCPathAnnotation()
SoFCPathAnnotation::~SoFCPathAnnotation () override protected
Definition at line 1713 of file SoFCUnifiedSelection.cpp.
Member Function Documentation
finish()
void SoFCPathAnnotation::finish () static
Definition at line 1720 of file SoFCUnifiedSelection.cpp.
Referenced by drafttaskpanels.task_polararray.TaskPanelPolarArray::accept(), drafttaskpanels.task_orthoarray.TaskPanelOrthoArray::accept(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::accept(), draftguitools.gui_split.Split::action(), draftguitools.gui_splines.BSpline::action(), draftguitools.gui_beziers.BezCurve::action(), draftguitools.gui_lines.Line::action(), draftguitools.gui_subelements.SubelementHighlight::action(), draftguitools.gui_polygons.Polygon::action(), draftguitools.gui_rotate.Rotate::action(), draftguitools.gui_fillets.Fillet::action(), draftguitools.gui_move.Move::action(), draftguitools.gui_mirror.Mirror::action(), draftguitools.gui_stretch.Stretch::action(), draftguitools.gui_arcs.Arc::action(), draftguitools.gui_texts.Text::action(), draftguitools.gui_scale.Scale::action(), draftguitools.gui_rectangles.Rectangle::action(), draftguitools.gui_offset.Offset::action(), draftguitools.gui_ellipses.Ellipse::action(), draftguitools.gui_labels.Label::action(), draftguitools.gui_trimex.Trimex::action(), draftguitools.gui_beziers.CubicBezCurve::action(), draftguitools.gui_dimensions.Dimension::action(), draftguitools.gui_styles.ApplyStyle::Activated(), draftguitools.gui_join.Join::Activated(), draftguitools.gui_draft2sketch.Draft2Sketch::Activated(), draftguitools.gui_downgrade.Downgrade::Activated(), draftguitools.gui_upgrade.Upgrade::Activated(), draftguitools.gui_shape2dview.Shape2DView::Activated(), draftguitools.gui_facebinders.Facebinder::Activated(), draftguitools.gui_subelements.SubelementHighlight::Activated(), draftguitools.gui_wire2spline.WireToBSpline::Activated(), draftguitools.gui_clone.Clone::Activated(), draftguitools.gui_dimensions.Dimension::Activated(), draftguitools.gui_edit.Edit::Activated(), draftguitools.gui_selectplane.Draft_SelectPlane::check_selection(), DraftGui.DraftToolBar::checkSpecialChars(), draftguitools.gui_points.Point::click(), draftguitools.gui_orthoarray.OrthoArray::completed(), draftguitools.gui_polararray.PolarArray::completed(), draftguitools.gui_circulararray.CircularArray::completed(), draftguitools.gui_labels.Label::create(), bimcommands.BimText.BIM_Text::createObject(), draftguitools.gui_rectangles.Rectangle::createObject(), draftguitools.gui_ellipses.Ellipse::createObject(), draftguitools.gui_texts.Text::createObject(), draftviewproviders.view_text.ViewProviderText::createObject(), draftguitools.gui_stretch.Stretch::doStretch(), draftguitools.gui_fillets.Fillet::draw_arc(), draftguitools.gui_arcs.Arc::drawArc(), draftguitools.gui_polygons.Polygon::drawPolygon(), DraftGui.DraftToolBar::editUi(), DraftGui.DraftToolBar::escape(), Gui::SoFCDB::finish(), draftguitools.gui_move.Move::get_object_selection(), draftguitools.gui_rotate.Rotate::get_object_selection(), draftguitools.gui_scale.Scale::get_object_selection(), draftguitools.gui_arcs.Arc_3Points::getPoint(), draftguitools.gui_edit.Edit::keyPressed(), draftguitools.gui_dimensions.Dimension::numericInput(), draftguitools.gui_offset.Offset::numericRadius(), draftguitools.gui_rotate.Rotate::numericRadius(), draftguitools.gui_trimex.Trimex::numericRadius(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_align(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_auto(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_center(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_front(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_move(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_next(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_previous(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_side(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_top(), bimcommands.BimShape2DView.BIM_Shape2DView::proceed(), draftguitools.gui_join.Join::proceed(), draftguitools.gui_subelements.SubelementHighlight::proceed(), draftguitools.gui_draft2sketch.Draft2Sketch::proceed(), draftguitools.gui_downgrade.Downgrade::proceed(), bimcommands.BimSlab.BIM_Slab::proceed(), draftguitools.gui_upgrade.Upgrade::proceed(), draftguitools.gui_facebinders.Facebinder::proceed(), draftguitools.gui_pathtwistedarray.PathTwistedArray::proceed(), draftguitools.gui_shape2dview.Shape2DView::proceed(), draftguitools.gui_clone.Clone::proceed(), draftguitools.gui_split.Split::proceed(), draftguitools.gui_pointarray.PointArray::proceed(), draftguitools.gui_patharray.PathArray::proceed(), draftguitools.gui_trimex.Trimex::proceed(), draftguitools.gui_edit.Edit::proceed(), draftguitools.gui_selectplane.Draft_SelectPlane::reject(), drafttaskpanels.task_orthoarray.TaskPanelOrthoArray::reject(), drafttaskpanels.task_polararray.TaskPanelPolarArray::reject(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::reject(), and draftguitools.gui_edit.Edit::setTrackers().
getBoundingBox()
void SoFCPathAnnotation::getBoundingBox (SoGetBoundingBoxAction * action) override
Definition at line 1852 of file SoFCUnifiedSelection.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and Gui::SoFCSelectionRoot::moveActionStack().
getDetail()
SoDetail* Gui::SoFCPathAnnotation::getDetail () inline
Definition at line 143 of file SoFCUnifiedSelection.h.
getPath()
SoPath* Gui::SoFCPathAnnotation::getPath () inline
Definition at line 141 of file SoFCUnifiedSelection.h.
GLRender()
void SoFCPathAnnotation::GLRender (SoGLRenderAction * action) override
Definition at line 1730 of file SoFCUnifiedSelection.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Gui::SoFCSelectionRoot::GLRenderBelowPath(), and Gui::SoFCSelectionRoot::GLRenderInPath().
GLRenderBelowPath()
void SoFCPathAnnotation::GLRenderBelowPath (SoGLRenderAction * action) override
Definition at line 1745 of file SoFCUnifiedSelection.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Gui::SoFCSelectionRoot::Box, Gui::SoFCSelectionRoot::checkSelection(), src.Mod.AddonManager.NetworkManager::count, getLength(), Gui::ViewParams::getShowSelectionBoundingBox(), glDisable, glEnable, SplineSurface::i, Gui::ViewParams::instance(), and Gui::SoFCSelectionRoot::renderBBox().
GLRenderInPath()
void SoFCPathAnnotation::GLRenderInPath (SoGLRenderAction * action) override
Definition at line 1818 of file SoFCUnifiedSelection.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and Gui::SoFCSelectionRoot::GLRenderBelowPath().
initClass()
void SoFCPathAnnotation::initClass () static
Definition at line 1725 of file SoFCUnifiedSelection.cpp.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
setDetail()
void SoFCPathAnnotation::setDetail (SoDetail * d)
Definition at line 1823 of file SoFCUnifiedSelection.cpp.
setPath()
void SoFCPathAnnotation::setPath (SoPath * newPath)
Definition at line 1830 of file SoFCUnifiedSelection.cpp.
References Gui::coinRemoveAllChildren(), and SplineSurface::i.
Referenced by Gui::View3DInventorSelection::checkGroupOnTop().
Member Data Documentation
det
SoDetail* Gui::SoFCPathAnnotation::det protected
Definition at line 157 of file SoFCUnifiedSelection.h.
path
SoPath* Gui::SoFCPathAnnotation::path protected
Definition at line 155 of file SoFCUnifiedSelection.h.
Referenced by src.Mod.AddonManager.addonmanager_devmode.AddonGitInterface::authors(), src.Mod.AddonManager.addonmanager_devmode.AddonGitInterface::branches(), src.Mod.AddonManager.addonmanager_devmode.AddonGitInterface::committers(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::librarySave(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::librarySaveAs(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::loadData(), src.Mod.AddonManager.addonmanager_devmode_predictor.Predictor::predict_metadata(), and TDTest.DrawHatchTest.DrawHatchTest::testMakeHatchCase().
tmpPath
SoTempPath* Gui::SoFCPathAnnotation::tmpPath protected
Definition at line 156 of file SoFCUnifiedSelection.h.
The documentation for this class was generated from the following files:
SoFCUnifiedSelection.h
SoFCUnifiedSelection.cpp