FreeCAD: ReverseEngineeringGui::SegmentationManual::Private Class Reference
ReverseEngineeringGui::SegmentationManual::Private Class Reference
Static Public Member Functions
static void findGeometry (int minFaces, double tolerance, std::function< MeshCore::AbstractSurfaceFit *(const std::vector< Base::Vector3f > &, const std::vector< Base::Vector3f > &)> fitFunc)
Detailed Description
Definition at line 150 of file SegmentationManual.cpp.
Member Function Documentation
findGeometry()
static void ReverseEngineeringGui::SegmentationManual::Private::findGeometry (int minFaces, double tolerance, std::function< MeshCore::AbstractSurfaceFit *(const std::vector< Base::Vector3f > &, const std::vector< Base::Vector3f > &)> fitFunc) inline static
Definition at line 153 of file SegmentationManual.cpp.
References Gui::Application::activeDocument(), MeshGui::ViewProviderMesh::addSelection(), MeshCore::MeshSegmentAlgorithm::FindSegments(), Gui::Document::getDocument(), MeshCore::MeshKernel::GetFacetNormals(), App::Document::getObjectsOfType(), MeshCore::MeshKernel::GetPoints(), Gui::Document::getViewProvider(), Gui::Application::Instance, Mesh2Shape::mesh, and draftutils.utils::tolerance().
Referenced by ReverseEngineeringGui::SegmentationManual::onCylinderDetectClicked(), ReverseEngineeringGui::SegmentationManual::onPlaneDetectClicked(), and ReverseEngineeringGui::SegmentationManual::onSphereDetectClicked().
The documentation for this class was generated from the following file:
SegmentationManual.cpp