FreeCAD: Wm4::LinearSystem< Real > Class Template Reference
Wm4::LinearSystem< Real > Class Template Reference
#include <Wm4LinearSystem.h>
Public Types
typedef std::map< std::pair< int, int >, Real > SparseMatrix
Public Member Functions
LinearSystem ()
bool Solve2 (const Real aafA[2][2], const Real afB[2], Real afX[2])
bool Solve3 (const Real aafA[3][3], const Real afB[3], Real afX[3])
bool Inverse (const GMatrix< Real > &rkA, GMatrix< Real > &rkInvA)
bool Solve (const GMatrix< Real > &rkA, const Real *afB, Real *afX)
bool SolveTri (int iSize, Real *afA, Real *afB, Real *afC, Real *afR, Real *afU)
bool SolveConstTri (int iSize, Real fA, Real fB, Real fC, Real *afR, Real *afU)
bool SolveSymmetricCG (const GMatrix< Real > &rkA, const Real *afB, Real *afX)
bool SolveSymmetricCG (int iSize, const SparseMatrix &rkA, const Real *afB, Real *afX)
bool SolveBanded (const BandedMatrix< Real > &rkA, const Real *afB, Real *afX)
bool Invert (const BandedMatrix< Real > &rkA, GMatrix< Real > &rkInvA)
Public Attributes
Real ZeroTolerance
Detailed Description
template<class Real>
class Wm4::LinearSystem< Real >
Definition at line 28 of file Wm4LinearSystem.h.
Member Typedef Documentation
SparseMatrix
template<class Real > typedef std::map<std::pair<int,int>,Real> Wm4::LinearSystem< Real >::SparseMatrix
Definition at line 96 of file Wm4LinearSystem.h.
Constructor & Destructor Documentation
LinearSystem()
template<class Real > Wm4::LinearSystem< Real >::LinearSystem
Definition at line 24 of file Wm4LinearSystem.cpp.
Member Function Documentation
Inverse()
template<class Real > bool Wm4::LinearSystem< Real >::Inverse (const GMatrix< Real > & rkA, GMatrix< Real > & rkInvA)
Definition at line 83 of file Wm4LinearSystem.cpp.
References Wm4::Math< Real >::FAbs(), Wm4::GMatrix< Real >::GetColumns(), Wm4::GMatrix< Real >::GetRows(), Wm4::GMatrix< Real >::SwapRows(), WM4_DELETE, and WM4_NEW.
Invert()
template<class Real > bool Wm4::LinearSystem< Real >::Invert (const BandedMatrix< Real > & rkA, GMatrix< Real > & rkInvA)
Definition at line 728 of file Wm4LinearSystem.cpp.
References Wm4::BandedMatrix< Real >::GetSize().
Solve()
template<class Real > bool Wm4::LinearSystem< Real >::Solve (const GMatrix< Real > & rkA, const Real * afB, Real * afX)
Definition at line 189 of file Wm4LinearSystem.cpp.
References Wm4::Math< Real >::FAbs(), Wm4::GMatrix< Real >::GetColumns(), Wm4::System::Memcpy(), Wm4::GMatrix< Real >::SwapRows(), WM4_DELETE, and WM4_NEW.
Referenced by Wm4::PolyFit3().
Solve2()
template<class Real > bool Wm4::LinearSystem< Real >::Solve2 (const Real aafA[2][2], const Real afB[2], Real afX[2])
Definition at line 30 of file Wm4LinearSystem.cpp.
Solve3()
template<class Real > bool Wm4::LinearSystem< Real >::Solve3 (const Real aafA[3][3], const Real afB[3], Real afX[3])
Definition at line 46 of file Wm4LinearSystem.cpp.
Referenced by Wm4::HeightPlaneFit3().
SolveBanded()
template<class Real > bool Wm4::LinearSystem< Real >::SolveBanded (const BandedMatrix< Real > & rkA, const Real * afB, Real * afX)
Definition at line 612 of file Wm4LinearSystem.cpp.
References Wm4::BandedMatrix< Real >::GetSize(), Wm4::BandedMatrix< Real >::GetUBands(), and Wm4::System::Memcpy().
SolveConstTri()
template<class Real > bool Wm4::LinearSystem< Real >::SolveConstTri (int iSize, Real fA, Real fB, Real fC, Real * afR, Real * afU)
Definition at line 337 of file Wm4LinearSystem.cpp.
References WM4_DELETE, and WM4_NEW.
SolveSymmetricCG() [1/2]
template<class Real > bool Wm4::LinearSystem< Real >::SolveSymmetricCG (const GMatrix< Real > & rkA, const Real * afB, Real * afX)
Definition at line 452 of file Wm4LinearSystem.cpp.
References Wm4::GMatrix< Real >::GetColumns(), Wm4::GMatrix< Real >::GetRows(), SplineSurface::i, Wm4::System::Memcpy(), KDL::Multiply(), Wm4::Math< Real >::Sqrt(), WM4_DELETE, and WM4_NEW.
SolveSymmetricCG() [2/2]
template<class Real > bool Wm4::LinearSystem< Real >::SolveSymmetricCG (int iSize, const SparseMatrix & rkA, const Real * afB, Real * afX)
Definition at line 505 of file Wm4LinearSystem.cpp.
References SplineSurface::i, Wm4::System::Memcpy(), KDL::Multiply(), Wm4::Math< Real >::Sqrt(), WM4_DELETE, and WM4_NEW.
SolveTri()
template<class Real > bool Wm4::LinearSystem< Real >::SolveTri (int iSize, Real * afA, Real * afB, Real * afC, Real * afR, Real * afU)
Definition at line 300 of file Wm4LinearSystem.cpp.
References WM4_DELETE, and WM4_NEW.
Member Data Documentation
ZeroTolerance
template<class Real > Real Wm4::LinearSystem< Real >::ZeroTolerance
Definition at line 119 of file Wm4LinearSystem.h.
The documentation for this class was generated from the following files:
Wm4LinearSystem.h
Wm4LinearSystem.cpp