FreeCAD: Gui::Dialog::DlgSettingsMacroImp Class Reference
Gui::Dialog::DlgSettingsMacroImp Class Reference
#include <DlgSettingsMacroImp.h>
Public Member Functions
DlgSettingsMacroImp (QWidget *parent=nullptr)
~DlgSettingsMacroImp () override
void saveSettings () override
void loadSettings () override
void resetSettingsToDefaults () override
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Protected Member Functions
void changeEvent (QEvent *e) override
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
Detailed Description
The DlgSettingsMacroImp class implements a preference page to change settings for macro stuff.
Author
Jürgen Riegel
Definition at line 79 of file DlgSettingsMacroImp.h.
Constructor & Destructor Documentation
DlgSettingsMacroImp()
DlgSettingsMacroImp::DlgSettingsMacroImp (QWidget * parent = nullptr) explicit
Constructs a DlgSettingsMacroImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'
Definition at line 40 of file DlgSettingsMacroImp.cpp.
References App::GetApplication(), and src.Mod.AddonManager.addonmanager_freecad_interface::getUserMacroDir.
~DlgSettingsMacroImp()
DlgSettingsMacroImp::~DlgSettingsMacroImp () override default
Destroys the object and frees any allocated resources
Member Function Documentation
changeEvent()
void DlgSettingsMacroImp::changeEvent (QEvent * e) override protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
Definition at line 119 of file DlgSettingsMacroImp.cpp.
References SCL.SimpleDataTypes::e.
loadSettings()
void DlgSettingsMacroImp::loadSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 90 of file DlgSettingsMacroImp.cpp.
References ParameterGrp::GetASCII(), Gui::WindowParameter::getDefaultParameter(), and ParameterGrp::GetGroup().
resetSettingsToDefaults()
void DlgSettingsMacroImp::resetSettingsToDefaults () override virtual
Reimplemented from Gui::Dialog::PreferencePage.
Definition at line 105 of file DlgSettingsMacroImp.cpp.
References Gui::WindowParameter::getDefaultParameter(), ParameterGrp::GetGroup(), ParameterGrp::RemoveASCII(), and Gui::Dialog::PreferencePage::resetSettingsToDefaults().
saveSettings()
void DlgSettingsMacroImp::saveSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 74 of file DlgSettingsMacroImp.cpp.
References Gui::WindowParameter::getDefaultParameter(), ParameterGrp::GetGroup(), and ParameterGrp::SetASCII().
The documentation for this class was generated from the following files:
DlgSettingsMacroImp.h
DlgSettingsMacroImp.cpp