FreeCAD: Gui::DAG::FilterTyped Class Reference
Gui::DAG::FilterTyped Class Reference
#include <DAGFilter.h>
Public Member Functions
FilterTyped (const std::string &typeIn)
bool goFilter (const Vertex &vertexIn, const Graph &graphIn, const GraphLinkContainer &linkIn) const override
Public Member Functions inherited from Gui::DAG::FilterBase
FilterBase ()
Public Attributes
std::string type
Public Attributes inherited from Gui::DAG::FilterBase
QString name
bool enabled = true
Type type = Type::Exclusion
Additional Inherited Members
Public Types inherited from Gui::DAG::FilterBase
enum Type { Type::None = 0, Type::Inclusion, Type::Exclusion }
Detailed Description
Hide nodes of type
Definition at line 83 of file DAGFilter.h.
Constructor & Destructor Documentation
FilterTyped()
FilterTyped::FilterTyped (const std::string & typeIn) explicit
Definition at line 64 of file DAGFilter.cpp.
References Gui::DAG::FilterBase::name.
Member Function Documentation
goFilter()
bool FilterTyped::goFilter (const Vertex & vertexIn, const Graph & graphIn, const GraphLinkContainer & linkIn) const override virtual
Returns
is whether we have a match or not.
Implements Gui::DAG::FilterBase.
Definition at line 69 of file DAGFilter.cpp.
References Base::Type::badType(), Gui::DAG::GraphLinkRecord::DObject, Gui::DAG::findRecord(), Base::Type::fromName(), Base::Persistence::getTypeId(), and type.
Member Data Documentation
type
std::string Gui::DAG::FilterTyped::type
Definition at line 87 of file DAGFilter.h.
Referenced by importers.importIFClegacy.IfcEntity::__repr__(), goFilter(), and ArchProfile.ProfileTaskPanel::retranslateUi().
The documentation for this class was generated from the following files:
DAGFilter.h
DAGFilter.cpp