FreeCAD: PartGui::DlgImportExportIges Class Reference
PartGui::DlgImportExportIges Class Reference
#include <DlgSettingsGeneral.h>
Public Member Functions
DlgImportExportIges (QWidget *parent=nullptr)
~DlgImportExportIges () override
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Protected Member Functions
void saveSettings () override
void loadSettings () override
void changeEvent (QEvent *e) override
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void resetSettingsToDefaults ()
Detailed Description
Definition at line 52 of file Mod/Part/Gui/DlgSettingsGeneral.h.
Constructor & Destructor Documentation
DlgImportExportIges()
DlgImportExportIges::DlgImportExportIges (QWidget * parent = nullptr) explicit
Definition at line 91 of file Mod/Part/Gui/DlgSettingsGeneral.cpp.
References src.Mod.AddonManager.addonmanager_devmode_license_selector::QRegularExpression, and src.Mod.AddonManager.addonmanager_devmode_license_selector::QRegularExpressionValidator.
~DlgImportExportIges()
DlgImportExportIges::~DlgImportExportIges () override default
Destroys the object and frees any allocated resources
Member Function Documentation
changeEvent()
void DlgImportExportIges::changeEvent (QEvent * e) override protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
Definition at line 156 of file Mod/Part/Gui/DlgSettingsGeneral.cpp.
References SCL.SimpleDataTypes::e.
loadSettings()
void DlgImportExportIges::loadSettings () override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 132 of file Mod/Part/Gui/DlgSettingsGeneral.cpp.
References Part::IGES::ImportExportSettings::getAuthor(), Part::IGES::ImportExportSettings::getBRepMode(), Part::IGES::ImportExportSettings::getCompany(), Part::IGES::ImportExportSettings::getProductName(), Part::IGES::ImportExportSettings::getSkipBlankEntities(), and Part::IGES::ImportExportSettings::getUnit().
saveSettings()
void DlgImportExportIges::saveSettings () override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 116 of file Mod/Part/Gui/DlgSettingsGeneral.cpp.
References Part::IGES::ImportExportSettings::setAuthor(), Part::IGES::ImportExportSettings::setBRepMode(), Part::IGES::ImportExportSettings::setCompany(), Part::IGES::ImportExportSettings::setSkipBlankEntities(), Part::IGES::ImportExportSettings::setUnit(), and unit().
The documentation for this class was generated from the following files:
Mod/Part/Gui/DlgSettingsGeneral.h
Mod/Part/Gui/DlgSettingsGeneral.cpp