FreeCAD: MillSim Namespace Reference
MillSim Namespace Reference
Classes
class EndMill
class GCodeParser
struct GCToken
class GuiDisplay
struct GuiItem
struct MillMotion
class MillPathLine
struct MillPathPosition
class MillPathSegment
class MillSimulation
struct Point3D
class Shader
class Shape
class SimDisplay
class SolidObject
class StockObject
class Texture
struct TextureItem
class TextureLoader
struct Vertex
struct Vertex2D
Typedefs
typedef struct MillSim::Vertex Vertex
typedef unsigned int uint
Enumerations
enum eGuiItems {
eGuiItemSlider, eGuiItemThumb, eGuiItemPause, eGuiItemPlay,
eGuiItemSingleStep, eGuiItemFaster, eGuiItemRotate, eGuiItemCharXImg,
eGuiItemChar0Img, eGuiItemChar1Img, eGuiItemChar4Img, eGuiItemPath,
eGuiItemAmbientOclusion, eGuiItemView, eGuiItemMax
}
enum eEndMillType { eEndmillFlat, eEndmillV, eEndmillBall, eEndmillFillet }
enum eCmdType {
eNop, eMoveLiner, eRotateCW, eRotateCCW,
eDril, eChangeTool
}
enum MotionType { MTVertical = 0, MTHorizontal, MTCurved }
Functions
void GLClearError ()
bool GLLogError ()
static void MotionPosToVec (vec3 vec, const MillMotion *motion)
bool IsVerticalMotion (MillMotion *m1, MillMotion *m2)
bool IsArcMotion (MillMotion *m)
bool CheckCompileResult (int shaderId, const char *shaderName, bool isVertex)
Variables
int gWindowSizeW = 800
int gWindowSizeH = 600
int gDebug = -1
mat4x4 identityMat = {{1, 0, 0, 0}, {0, 1, 0, 0}, {0, 0, 1, 0}, {0, 0, 0, 1}}
Shader * CurrentShader = nullptr
const char * VertShader3DNorm
const char * VertShader3DInvNorm
const char * VertShader2DTex
const char * FragShader2dTex
const char * FragShaderNorm
const char * FragShaderFlat
const char * VertShader2DFbo
const char * FragShader2dFbo
const char * VertShaderGeom
const char * FragShaderGeom
const char * FragShaderSSAO
const char * FragShaderSSAOBlur
const char * FragShaderSSAOLighting
const char * VertShader3DLine
const char * FragShader3DLine
const char * FragShaderStdLighting
Typedef Documentation
uint
typedef unsigned int MillSim::uint
Definition at line 49 of file SimShapes.h.
Vertex
typedef struct MillSim::Vertex MillSim::Vertex
Enumeration Type Documentation
eCmdType
enum MillSim::eCmdType
Enumerator
eNop
eMoveLiner
eRotateCW
eRotateCCW
eDril
eChangeTool
Definition at line 59 of file MillMotion.h.
eEndMillType
enum MillSim::eEndMillType
Enumerator
eEndmillFlat
eEndmillV
eEndmillBall
eEndmillFillet
Definition at line 51 of file MillMotion.h.
eGuiItems
enum MillSim::eGuiItems
Enumerator
eGuiItemSlider
eGuiItemThumb
eGuiItemPause
eGuiItemPlay
eGuiItemSingleStep
eGuiItemFaster
eGuiItemRotate
eGuiItemCharXImg
eGuiItemChar0Img
eGuiItemChar1Img
eGuiItemChar4Img
eGuiItemPath
eGuiItemAmbientOclusion
eGuiItemView
eGuiItemMax
Definition at line 55 of file GuiDisplay.h.
MotionType
enum MillSim::MotionType
Enumerator
MTVertical
MTHorizontal
MTCurved
Definition at line 55 of file MillPathSegment.h.
Function Documentation
CheckCompileResult()
bool MillSim::CheckCompileResult (int shaderId, const char * shaderName, bool isVertex)
Definition at line 207 of file Shader.cpp.
GLClearError()
void MillSim::GLClearError ()
Definition at line 55 of file GlUtils.cpp.
Referenced by MillSim::Shape::GenerateModel().
GLLogError()
bool MillSim::GLLogError ()
Definition at line 61 of file GlUtils.cpp.
Referenced by MillSim::Shape::GenerateModel().
IsArcMotion()
bool MillSim::IsArcMotion (MillMotion * m)
Definition at line 47 of file MillPathSegment.cpp.
References EPSILON, eRotateCCW, eRotateCW, and test::m.
Referenced by MillSim::MillPathSegment::MillPathSegment().
IsVerticalMotion()
bool MillSim::IsVerticalMotion (MillMotion * m1, MillMotion * m2)
Definition at line 42 of file MillPathSegment.cpp.
References EQ_FLOAT, MillSim::MillMotion::x, MillSim::MillMotion::y, and MillSim::MillMotion::z.
Referenced by MillSim::MillPathSegment::MillPathSegment().
MotionPosToVec()
static void MillSim::MotionPosToVec (vec3 vec, const MillMotion * motion) inline static
Definition at line 78 of file MillMotion.h.
Referenced by MillSim::MillPathSegment::MillPathSegment(), and MillSim::MillSimulation::RenderTool().
Variable Documentation
CurrentShader
Shader * MillSim::CurrentShader = nullptr
Definition at line 67 of file Shader.cpp.
Referenced by MillSim::Shape::Render().
FragShader2dFbo
const char * MillSim::FragShader2dFbo
Initial value:
= R"(
    #version 330
    out vec4 FragColor;
    in vec2 texCoord;
    uniform sampler2D texSlot;
    void main()
    {
        vec4 tc = texture(texSlot, texCoord);
        FragColor = tc;
    }
)"
Definition at line 447 of file Shader.cpp.
FragShader2dTex
const char * MillSim::FragShader2dTex
Initial value:
= R"(
    #version 330
    out vec4 FragColor;
    in vec2 texCoord;
    uniform vec3 objectColor;
    uniform sampler2D texSlot;
    void main()
    {
        vec4 texColor = texture(texSlot, texCoord);
        FragColor = vec4(objectColor, 1.0) * texColor;
    }
)"
Definition at line 375 of file Shader.cpp.
Referenced by MillSim::GuiDisplay::InitGui().
FragShader3DLine
const char * MillSim::FragShader3DLine
Initial value:
= R"(
    #version 330
    out vec4 FragColor;
    flat in int Index;
    uniform vec4 objectColorAlpha;
    uniform vec3 objectColor;
    uniform int curSegment;
    void main()
    {
        if (Index > curSegment) FragColor = objectColorAlpha;
        else FragColor = vec4(objectColor, objectColorAlpha.a);
    }
)"
Definition at line 643 of file Shader.cpp.
FragShaderFlat
const char * MillSim::FragShaderFlat
Initial value:
= R"(
    #version 330
    out vec4 FragColor;
    in vec3 Normal;
    in vec3 Position;
    uniform vec3 objectColor;
    void main()
    {
        FragColor = vec4(objectColor, 1.0);
    }
)"
Definition at line 416 of file Shader.cpp.
FragShaderGeom
const char * MillSim::FragShaderGeom
Initial value:
= R"(
    #version 330 core
    layout (location = 0) out vec4 ColorTex;
    layout (location = 1) out vec3 PositionTex;
    layout (location = 2) out vec3 NormalTex;
    in vec3 Position;
    in vec3 Normal;
    uniform vec3 objectColor;
    void main()
    {
        // Store position, normal, and diffuse color in textures
        PositionTex = Position;
        NormalTex = normalize(Normal);
        ColorTex = vec4(objectColor, 1.0f);
    }
)"
Definition at line 488 of file Shader.cpp.
FragShaderNorm
const char * MillSim::FragShaderNorm
Initial value:
= R"(
    #version 330
    out vec4 FragColor;
    in vec3 Normal;
    in vec3 Position;
    uniform vec3 lightPos;
    uniform vec3 lightColor;
    uniform vec3 objectColor;
    uniform vec3 lightAmbient;
    void main()
    {
        vec3 norm = normalize(Normal);
        vec3 lightDir = normalize(lightPos - Position);
        float diff = max(dot(norm, lightDir), 0.0);
        vec3 diffuse = diff * lightColor;
        vec3 result = (lightAmbient + diffuse) * objectColor;
        FragColor = vec4(result, 1.0);
    }
)"
Definition at line 392 of file Shader.cpp.
FragShaderSSAO
const char * MillSim::FragShaderSSAO
Definition at line 508 of file Shader.cpp.
FragShaderSSAOBlur
const char * MillSim::FragShaderSSAOBlur
Initial value:
= R"(
    #version 330 core
    layout (location = 0) out float AoData;
    in vec2 texCoord;
    uniform sampler2D AoTex;
    void main()
    {
        ivec2 pix = ivec2( gl_FragCoord.xy );
        float sum = 0.0;
        for( int x = -1; x <= 2; ++x ) {
            for( int y = -1; y <= 2; y++ ) {
                sum += texelFetch( AoTex, pix + ivec2(x,y), 0).r;
            }
        }
        float ao = sum * (1.0 / 16.0);
        AoData = ao;
    }
)"
Definition at line 563 of file Shader.cpp.
FragShaderSSAOLighting
const char * MillSim::FragShaderSSAOLighting
Definition at line 586 of file Shader.cpp.
FragShaderStdLighting
const char* MillSim::FragShaderStdLighting
gDebug
int MillSim::gDebug = -1
Definition at line 51 of file GlUtils.cpp.
Referenced by MillSim::MillSimulation::HandleKeyPress().
gWindowSizeH
int MillSim::gWindowSizeH = 600
Definition at line 49 of file GlUtils.cpp.
Referenced by CAMSimulator::DlgCAMSimulator::GetInstance(), and MillSim::MillSimulation::UpdateWindowScale().
gWindowSizeW
int MillSim::gWindowSizeW = 800
Definition at line 48 of file GlUtils.cpp.
Referenced by CAMSimulator::DlgCAMSimulator::GetInstance(), and MillSim::MillSimulation::UpdateWindowScale().
identityMat
mat4x4 MillSim::identityMat = {{1, 0, 0, 0}, {0, 1, 0, 0}, {0, 0, 1, 0}, {0, 0, 0, 1}}
Definition at line 53 of file GlUtils.cpp.
Referenced by MillSim::MillSimulation::RenderTool().
VertShader2DFbo
const char * MillSim::VertShader2DFbo
Initial value:
= R"(
    #version 330 core
    layout(location = 0) in vec2 aPosition;
    layout(location = 1) in vec2 aTexCoord;
    out vec2 texCoord;
    void main(void)
    {
        gl_Position = vec4(aPosition.x, aPosition.y, 0.0, 1.0);
        texCoord = aTexCoord;
    }
)"
Definition at line 432 of file Shader.cpp.
VertShader2DTex
const char * MillSim::VertShader2DTex
Initial value:
= R"(
    #version 330 core
    layout(location = 0) in vec2 aPosition;
    layout(location = 1) in vec2 aTexCoord;
    out vec2 texCoord;
    uniform mat4 projection;
    uniform mat4 model;
    void main(void)
    {
        gl_Position = projection * model * vec4(aPosition, 0.0, 1.0);
        texCoord = aTexCoord;
    }
)"
Definition at line 357 of file Shader.cpp.
Referenced by MillSim::GuiDisplay::InitGui().
VertShader3DInvNorm
const char * MillSim::VertShader3DInvNorm
Initial value:
= R"(
    #version 330 core
    layout(location = 0) in vec3 aPosition;
    layout(location = 1) in vec3 aNormal;
    out vec3 Normal;
    out vec3 Position;
    uniform mat4 model;
    uniform mat4 view;
    uniform mat4 projection;
    uniform mat4 normalRot;
    void main(void)
    {
        gl_Position = projection * view * model * vec4(aPosition, 1.0);
        Position = vec3(model * vec4(aPosition, 1.0));
        Normal = -vec3(normalRot * vec4(aNormal, 1.0));
    }
)"
Definition at line 334 of file Shader.cpp.
VertShader3DLine
const char * MillSim::VertShader3DLine
Initial value:
= R"(
    #version 330 core
    layout(location = 0) in vec3 aPosition;
    layout(location = 1) in int aIndex;
    flat out int Index;
    uniform mat4 view;
    uniform mat4 projection;
    void main(void)
    {
        gl_Position = projection * view * vec4(aPosition, 1.0);
        Index = aIndex;
    }
)"
Definition at line 626 of file Shader.cpp.
VertShader3DNorm
const char * MillSim::VertShader3DNorm
Initial value:
= R"(
    #version 330 core
    layout(location = 0) in vec3 aPosition;
    layout(location = 1) in vec3 aNormal;
    out vec3 Normal;
    out vec3 Position;
    uniform mat4 model;
    uniform mat4 view;
    uniform mat4 projection;
    uniform mat4 normalRot;
    void main(void)
    {
        vec4 viewPos = view * model * vec4(aPosition, 1.0);
        Position = vec3(model * vec4(aPosition, 1.0));
        Normal = vec3(normalRot * vec4(aNormal, 1.0));
        gl_Position = projection * viewPos;
    }
)"
Definition at line 311 of file Shader.cpp.
VertShaderGeom
const char * MillSim::VertShaderGeom
Initial value:
= R"(
    #version 330 core
    layout (location = 0) in vec3 aPos;
    layout (location = 1) in vec3 aNormal;
    out vec3 Position;
    out vec3 Normal;
    uniform bool invertedNormals;
    uniform mat4 model;
    uniform mat4 view;
    uniform mat4 projection;
    void main()
    {
        vec4 viewPos = view * model * vec4(aPos, 1.0);
        Position = viewPos.xyz;
        mat3 normalMatrix = transpose(inverse(mat3(view * model)));
        Normal = normalMatrix * (invertedNormals ? -aNormal : aNormal);
        gl_Position = projection * viewPos;
    }
)"
Definition at line 462 of file Shader.cpp.