FreeCAD: Import::ReaderIges Class Reference
Import::ReaderIges Class Reference
#include <ReaderIges.h>
Public Member Functions
ReaderIges (const Base::FileInfo &file)
void read (Handle(TDocStd_Document) hDoc)
Detailed Description
Definition at line 53 of file ReaderIges.h.
Constructor & Destructor Documentation
ReaderIges()
ReaderIges::ReaderIges (const Base::FileInfo & file) explicit
Definition at line 46 of file ReaderIges.cpp.
Member Function Documentation
read()
void ReaderIges::read (Handle(TDocStd_Document) hDoc)
Definition at line 50 of file ReaderIges.cpp.
References Part::encodeFilename(), Base::FileInfo::filePath(), App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), App::Application::GetUserParameter(), Handle(), and ClipperLib::pi.
The documentation for this class was generated from the following files:
ReaderIges.h
ReaderIges.cpp