FreeCAD: src.Mod.AddonManager.install_to_toolbar Namespace Reference
src.Mod.AddonManager.install_to_toolbar Namespace Reference
Functions
None ask_to_install_toolbar_button (Addon repo)
bool check_for_button (Addon repo)
object ask_for_toolbar (Addon repo, custom_toolbars)
object get_toolbar_with_name (str name)
object create_new_custom_toolbar ()
bool check_for_toolbar (str toolbar_name)
None install_toolbar_button (Addon repo)
str find_installed_icon (Addon repo)
None install_macro_to_toolbar (Addon repo, object toolbar)
None remove_custom_toolbar_button (Addon repo)
Variables
translate = FreeCAD.Qt.translate
Function Documentation
ask_for_toolbar()
object src.Mod.AddonManager.install_to_toolbar.ask_for_toolbar (Addon repo, custom_toolbars)
Determine what toolbar to add the icon to. The first time it is called it prompts the
user to select or create a toolbar. After that, the prompt is optional and can be configured
via a preference. Returns the pref group for the new toolbar.
Definition at line 67 of file install_to_toolbar.py.
References src.Mod.AddonManager.install_to_toolbar.create_new_custom_toolbar(), and src.Mod.AddonManager.install_to_toolbar.get_toolbar_with_name().
Referenced by src.Mod.AddonManager.install_to_toolbar.install_toolbar_button().
ask_to_install_toolbar_button()
None src.Mod.AddonManager.install_to_toolbar.ask_to_install_toolbar_button (Addon repo)
Presents a dialog to the user asking if they want to install a toolbar button for
a particular macro, and walks through that process if they agree to do so.
Definition at line 36 of file install_to_toolbar.py.
References src.Mod.AddonManager.install_to_toolbar.check_for_button(), and src.Mod.AddonManager.install_to_toolbar.install_toolbar_button().
check_for_button()
bool src.Mod.AddonManager.install_to_toolbar.check_for_button (Addon repo)
Returns True if a button already exists for this macro, or False if not.
Definition at line 53 of file install_to_toolbar.py.
Referenced by src.Mod.AddonManager.install_to_toolbar.ask_to_install_toolbar_button().
check_for_toolbar()
bool src.Mod.AddonManager.install_to_toolbar.check_for_toolbar (str toolbar_name)
Returns True if the toolbar exists, otherwise False
Definition at line 167 of file install_to_toolbar.py.
References src.Mod.AddonManager.install_to_toolbar.get_toolbar_with_name().
Referenced by src.Mod.AddonManager.install_to_toolbar.create_new_custom_toolbar().
create_new_custom_toolbar()
object src.Mod.AddonManager.install_to_toolbar.create_new_custom_toolbar ()
Create a new custom toolbar and returns its preference group.
Definition at line 131 of file install_to_toolbar.py.
References src.Mod.AddonManager.install_to_toolbar.check_for_toolbar(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by src.Mod.AddonManager.install_to_toolbar.ask_for_toolbar().
find_installed_icon()
str src.Mod.AddonManager.install_to_toolbar.find_installed_icon (Addon repo)
The icon the macro specifies is usually not the actual installed icon, but rather a cached
copy. This function looks for a file with the same name located in the macro installation
path.
Definition at line 218 of file install_to_toolbar.py.
Referenced by src.Mod.AddonManager.install_to_toolbar.install_macro_to_toolbar().
get_toolbar_with_name()
object src.Mod.AddonManager.install_to_toolbar.get_toolbar_with_name (str name)
Try to find a toolbar with a given name. Returns the preference group for the toolbar
if found, or None if it does not exist.
Definition at line 118 of file install_to_toolbar.py.
Referenced by src.Mod.AddonManager.install_to_toolbar.ask_for_toolbar(), and src.Mod.AddonManager.install_to_toolbar.check_for_toolbar().
install_macro_to_toolbar()
None src.Mod.AddonManager.install_to_toolbar.install_macro_to_toolbar (Addon repo, object toolbar)
Adds an icon for the given macro to the given toolbar.
Definition at line 240 of file install_to_toolbar.py.
References src.Mod.AddonManager.install_to_toolbar.find_installed_icon().
Referenced by src.Mod.AddonManager.install_to_toolbar.install_toolbar_button().
install_toolbar_button()
None src.Mod.AddonManager.install_to_toolbar.install_toolbar_button (Addon repo)
If the user has requested a toolbar button be installed, this function is called
to continue the process and request any additional required information.
Definition at line 172 of file install_to_toolbar.py.
References src.Mod.AddonManager.install_to_toolbar.ask_for_toolbar(), and src.Mod.AddonManager.install_to_toolbar.install_macro_to_toolbar().
Referenced by src.Mod.AddonManager.install_to_toolbar.ask_to_install_toolbar_button().
remove_custom_toolbar_button()
None src.Mod.AddonManager.install_to_toolbar.remove_custom_toolbar_button (Addon repo)
If this repo contains a macro, look through the custom commands and
see if one is set up for this macro. If so, remove it, including any
toolbar entries.
Definition at line 274 of file install_to_toolbar.py.
Variable Documentation
translate
src.Mod.AddonManager.install_to_toolbar.translate = FreeCAD.Qt.translate
Definition at line 33 of file install_to_toolbar.py.