FreeCAD: Gui::Dialog::ParameterText Class Reference
Gui::Dialog::ParameterText Class Reference
#include <DlgParameterImp.h>
Public Member Functions
ParameterText (QTreeWidget *parent, QString label1, const char *value, const Base::Reference< ParameterGrp > &hcGrp)
Constructor.
~ParameterText () override
void changeValue () override
void appendToGroup () override
void removeFromGroup () override
Public Member Functions inherited from Gui::Dialog::ParameterValueItem
ParameterValueItem (QTreeWidget *parent, const Base::Reference< ParameterGrp > &hcGrp)
Constructor.
~ParameterValueItem () override
void setData (int column, int role, const QVariant &value) override
Protected Member Functions
void replace (const QString &oldName, const QString &newName) override
Additional Inherited Members
Protected Attributes inherited from Gui::Dialog::ParameterValueItem
Base::Reference< ParameterGrp > _hcGrp
Detailed Description
The ParameterText class allows interaction with "text" parameter leaves.
Author
Werner Mayer
Definition at line 305 of file DlgParameterImp.h.
Constructor & Destructor Documentation
ParameterText()
ParameterText::ParameterText (QTreeWidget * parent, QString label1, const char * value, const Base::Reference< ParameterGrp > & hcGrp)
Constructor.
Definition at line 1133 of file DlgParameterImp.cpp.
References Gui::BitmapFactory().
~ParameterText()
ParameterText::~ParameterText () override default
Member Function Documentation
appendToGroup()
void ParameterText::appendToGroup () override virtual
Append this item as leaf to the parameter group.
Implements Gui::Dialog::ParameterValueItem.
Definition at line 1175 of file DlgParameterImp.cpp.
References Gui::Dialog::ParameterValueItem::_hcGrp, and ParameterGrp::SetASCII().
changeValue()
void ParameterText::changeValue () override virtual
Opens an input dialog to change the value.
Implements Gui::Dialog::ParameterValueItem.
Definition at line 1147 of file DlgParameterImp.cpp.
References Gui::Dialog::ParameterValueItem::_hcGrp, importers.exportIFC::getText(), geoff_geometry::Normal(), ParameterGrp::SetASCII(), and create_qrc::txt.
removeFromGroup()
void ParameterText::removeFromGroup () override virtual
Remove the leaf from the parameter group.
Implements Gui::Dialog::ParameterValueItem.
Definition at line 1163 of file DlgParameterImp.cpp.
References Gui::Dialog::ParameterValueItem::_hcGrp, and ParameterGrp::RemoveASCII().
replace()
void ParameterText::replace (const QString & oldName, const QString & newName) override protected virtual
Replaces the name of the leaf from oldName to newName.
Implements Gui::Dialog::ParameterValueItem.
Definition at line 1168 of file DlgParameterImp.cpp.
References Gui::Dialog::ParameterValueItem::_hcGrp, ParameterGrp::GetASCII(), ParameterGrp::RemoveASCII(), ParameterGrp::SetASCII(), and toolbit-attributes::val.
The documentation for this class was generated from the following files:
DlgParameterImp.h
DlgParameterImp.cpp