FreeCAD: ViewProviderLink.cpp File Reference
ViewProviderLink.cpp File Reference
#include "PreCompiled.h"
#include <atomic>
#include <cctype>
#include <boost/algorithm/string/predicate.hpp>
#include <Inventor/SoPickedPoint.h>
#include <Inventor/actions/SoGetBoundingBoxAction.h>
#include <Inventor/details/SoDetail.h>
#include <Inventor/draggers/SoCenterballDragger.h>
#include <Inventor/misc/SoChildList.h>
#include <Inventor/nodes/SoAnnotation.h>
#include <Inventor/nodes/SoCube.h>
#include <Inventor/nodes/SoDrawStyle.h>
#include <Inventor/nodes/SoPickStyle.h>
#include <Inventor/nodes/SoSeparator.h>
#include <Inventor/nodes/SoShapeHints.h>
#include <Inventor/nodes/SoSurroundScale.h>
#include <Inventor/nodes/SoSwitch.h>
#include <Inventor/nodes/SoTransform.h>
#include <Inventor/sensors/SoNodeSensor.h>
#include <QApplication>
#include <QMenu>
#include <QCheckBox>
#include <boost/range.hpp>
#include <App/ElementNamingUtils.h>
#include <App/Document.h>
#include <Base/BoundBoxPy.h>
#include <Base/MatrixPy.h>
#include <Base/PlacementPy.h>
#include <Base/Tools.h>
#include "Action.h"
#include "MainWindow.h"
#include "ViewProviderLink.h"
#include "ViewProviderLinkPy.h"
#include "Application.h"
#include "BitmapFactory.h"
#include "Control.h"
#include "LinkViewPy.h"
#include "Selection.h"
#include "SoFCCSysDragger.h"
#include "SoFCUnifiedSelection.h"
#include "TaskCSysDragger.h"
#include "TaskElementColors.h"
#include "View3DInventor.h"
#include "ViewParams.h"
#include "ViewProviderGeometryObject.h"
#include "ActionFunction.h"
#include "Command.h"
#include "DlgObjectSelection.h"
Classes
class Gui::LinkInfo
class Gui::LinkView::SubInfo
class Gui::LinkView::Element
Namespaces
Gui
Macros
#define appendPath(_path, _node) (_path)->append(_node)
#define CHECK_NAME(_name, _end)
#define CHECK_EXCLUDE_PROP(_name) if(strcmp(name,#_name)==0) return true;
Typedefs
using CharRange = boost::iterator_range< const char * >
Functions
static bool appendPathSafe (SoPath *path, SoNode *node)
Base::BoundBox3d _getBoundBox (ViewProviderDocumentObject *vpd, SoNode *rootNode)
static bool canScale (const Base::Vector3d &v)
static bool isExcludedProperties (const char *name)
Variables
static const char * _LinkIcon = "Link"
static const char * _LinkGroupIcon = "LinkGroup"
static const char * _LinkElementIcon = "LinkElement"
template class GuiExport Gui::ViewProviderFeaturePythonT< ViewProviderLink >
Macro Definition Documentation
appendPath
#define appendPath (_path, _node) (_path)->append(_node)
Definition at line 105 of file ViewProviderLink.cpp.
CHECK_EXCLUDE_PROP
#define CHECK_EXCLUDE_PROP (_name) if(strcmp(name,#_name)==0) return true;
CHECK_NAME
#define CHECK_NAME (_name, _end)
Value:
            do{\
            if(!_name) return 0;\
            const char *_n = _name;\
            for(;*subname && *_n; ++subname,++_n)\
                if(*subname != *_n) break;\
            if(*_n || (*subname!=0 && *subname!=_end))\
                    return 0;\
            if(*subname == _end) ++subname;\
        }while(0)
Typedef Documentation
CharRange
using CharRange = boost::iterator_range<const char*>
Definition at line 84 of file ViewProviderLink.cpp.
Function Documentation
_getBoundBox()
Base::BoundBox3d _getBoundBox (ViewProviderDocumentObject * vpd, SoNode * rootNode)
Definition at line 913 of file ViewProviderLink.cpp.
References toolbit-attributes::doc, Gui::ViewProviderDocumentObject::getDocument(), LINK_THROW, and OfflineRenderingUtils::viewer().
Referenced by Gui::LinkView::getBoundBox().
appendPathSafe()
static bool appendPathSafe (SoPath * path, SoNode * node) inline static
Definition at line 87 of file ViewProviderLink.cpp.
References src.Mod.Test.testPathArray::path.
Referenced by Gui::LinkInfo::getDetail(), and Gui::LinkView::linkGetDetailPath().
canScale()
static bool canScale (const Base::Vector3d & v) inline static
Definition at line 1825 of file ViewProviderLink.cpp.
References SCL.SimpleDataTypes::e, and TestSpreadsheet::v.
Referenced by Gui::ViewProviderLink::updateDataPrivate().
isExcludedProperties()
static bool isExcludedProperties (const char * name) static
Definition at line 3253 of file ViewProviderLink.cpp.
References CHECK_EXCLUDE_PROP.
Referenced by Gui::ViewProviderLink::getPropertyByName().
Variable Documentation
_LinkElementIcon
const char* _LinkElementIcon = "LinkElement" static
Definition at line 1623 of file ViewProviderLink.cpp.
Referenced by Gui::ViewProviderLink::checkIcon().
_LinkGroupIcon
const char* _LinkGroupIcon = "LinkGroup" static
Definition at line 1622 of file ViewProviderLink.cpp.
Referenced by Gui::ViewProviderLink::checkIcon().
_LinkIcon
const char* _LinkIcon = "Link" static
Definition at line 1620 of file ViewProviderLink.cpp.
Referenced by Gui::ViewProviderLink::checkIcon(), and Gui::ViewProviderLink::ViewProviderLink().