FreeCAD: SketcherGui::ConstraintView Class Reference
SketcherGui::ConstraintView Class Reference
#include <TaskSketcherConstraints.h>
Signals
void onUpdateDrivingStatus (QListWidgetItem *item, bool status)
void onUpdateActiveStatus (QListWidgetItem *item, bool status)
void emitCenterSelectedItems ()
void emitHideSelection3DVisibility ()
void emitShowSelection3DVisibility ()
Public Member Functions
ConstraintView (QWidget *parent=nullptr)
~ConstraintView () override
Protected Slots
void modifyCurrentItem ()
void renameCurrentItem ()
void centerSelectedItems ()
void deleteSelectedItems ()
void doSelectConstraints ()
void updateDrivingStatus ()
void updateActiveStatus ()
void swapNamedOfSelectedItems ()
void showConstraints ()
void hideConstraints ()
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *event) override
Detailed Description
Definition at line 54 of file TaskSketcherConstraints.h.
Constructor & Destructor Documentation
ConstraintView()
ConstraintView::ConstraintView (QWidget * parent = nullptr) explicit
Definition at line 500 of file TaskSketcherConstraints.cpp.
~ConstraintView()
ConstraintView::~ConstraintView () override
Definition at line 507 of file TaskSketcherConstraints.cpp.
Member Function Documentation
centerSelectedItems
void ConstraintView::centerSelectedItems () protected slot
Definition at line 653 of file TaskSketcherConstraints.cpp.
References emitCenterSelectedItems().
Referenced by contextMenuEvent().
contextMenuEvent()
void ConstraintView::contextMenuEvent (QContextMenuEvent * event) override protected
Definition at line 510 of file TaskSketcherConstraints.cpp.
References Gui::Application::activeDocument(), Gui::SelectionSingleton::addSelections(), exportCSG::center(), centerSelectedItems(), Gui::SelectionSingleton::clearSelection(), CONTEXT_ITEM, deleteSelectedItems(), toolbit-attributes::doc, doSelectConstraints(), Sketcher::PropertyConstraintList::getConstraintName(), ArchFence::hide(), hideConstraints(), Gui::Application::Instance, ConstraintItem::isActive(), ConstraintItem::isDimensional(), ConstraintItem::isEnforceable(), src.Mod.Test.testPathArray::items, NavigationIndicatorGui::menu, modifyCurrentItem(), SketcherGui::ReleaseHandler(), renameCurrentItem(), Gui::Selection(), bimcommands.BimViews::show(), showConstraints(), swapNamedOfSelectedItems(), updateActiveStatus(), and updateDrivingStatus().
deleteSelectedItems
void ConstraintView::deleteSelectedItems () protected slot
Definition at line 658 of file TaskSketcherConstraints.cpp.
References toolbit-attributes::doc, App::Application::getActiveDocument(), App::GetApplication(), Gui::SelectionSingleton::getSelectionEx(), Gui::Application::getViewProvider(), Gui::Application::Instance, Gui::ViewProvider::onDelete(), and Gui::Selection().
Referenced by contextMenuEvent().
doSelectConstraints
void ConstraintView::doSelectConstraints () protected slot
Definition at line 608 of file TaskSketcherConstraints.cpp.
Referenced by contextMenuEvent().
emitCenterSelectedItems
void SketcherGui::ConstraintView::emitCenterSelectedItems () signal
Referenced by centerSelectedItems().
emitHideSelection3DVisibility
void SketcherGui::ConstraintView::emitHideSelection3DVisibility () signal
Referenced by hideConstraints().
emitShowSelection3DVisibility
void SketcherGui::ConstraintView::emitShowSelection3DVisibility () signal
Referenced by showConstraints().
hideConstraints
void ConstraintView::hideConstraints () protected slot
Definition at line 635 of file TaskSketcherConstraints.cpp.
References emitHideSelection3DVisibility().
Referenced by contextMenuEvent().
modifyCurrentItem
void ConstraintView::modifyCurrentItem () protected slot
Definition at line 640 of file TaskSketcherConstraints.cpp.
Referenced by contextMenuEvent().
onUpdateActiveStatus
void SketcherGui::ConstraintView::onUpdateActiveStatus (QListWidgetItem * item, bool status) signal
Referenced by updateActiveStatus().
onUpdateDrivingStatus
void SketcherGui::ConstraintView::onUpdateDrivingStatus (QListWidgetItem * item, bool status) signal
renameCurrentItem
void ConstraintView::renameCurrentItem () protected slot
Definition at line 645 of file TaskSketcherConstraints.cpp.
Referenced by contextMenuEvent().
showConstraints
void ConstraintView::showConstraints () protected slot
Definition at line 630 of file TaskSketcherConstraints.cpp.
References emitShowSelection3DVisibility().
Referenced by contextMenuEvent().
swapNamedOfSelectedItems
void ConstraintView::swapNamedOfSelectedItems () protected slot
Definition at line 675 of file TaskSketcherConstraints.cpp.
References Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), ConstraintItem::ConstraintNbr, Sketcher::SketchObject::Constraints, Base::Tools::escapedUnicodeFromUtf8(), src.Mod.Test.testPathArray::items, Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, ConstraintItem::sketch, and Gui::TranslatedUserWarning().
Referenced by contextMenuEvent().
updateActiveStatus
void ConstraintView::updateActiveStatus () protected slot
Definition at line 620 of file TaskSketcherConstraints.cpp.
References ConstraintItem::isActive(), and onUpdateActiveStatus().
Referenced by contextMenuEvent().
updateDrivingStatus
void ConstraintView::updateDrivingStatus () protected slot
Definition at line 610 of file TaskSketcherConstraints.cpp.
References ConstraintItem::isDriving().
Referenced by contextMenuEvent().
The documentation for this class was generated from the following files:
TaskSketcherConstraints.h
TaskSketcherConstraints.cpp