FreeCAD: ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents Class Reference
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents Class Reference
Public Member Functions
def __init__ (self, length_exponent, mass_exponent, time_exponent, electric_current_exponent, thermodynamic_temperature_exponent, amount_of_substance_exponent, luminous_intensity_exponent)
def length_exponent ()
def mass_exponent ()
def time_exponent ()
def electric_current_exponent ()
def thermodynamic_temperature_exponent ()
def amount_of_substance_exponent ()
def luminous_intensity_exponent ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
length_exponent
mass_exponent
time_exponent
electric_current_exponent
thermodynamic_temperature_exponent
amount_of_substance_exponent
luminous_intensity_exponent
Detailed Description
Entity dimensional_exponents definition.
:param length_exponent
:type length_exponent:REAL
:param mass_exponent
:type mass_exponent:REAL
:param time_exponent
:type time_exponent:REAL
:param electric_current_exponent
:type electric_current_exponent:REAL
:param thermodynamic_temperature_exponent
:type thermodynamic_temperature_exponent:REAL
:param amount_of_substance_exponent
:type amount_of_substance_exponent:REAL
:param luminous_intensity_exponent
:type luminous_intensity_exponent:REAL
Definition at line 23977 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Constructor & Destructor Documentation
__init__()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents.__init__ (self, length_exponent, mass_exponent, time_exponent, electric_current_exponent, thermodynamic_temperature_exponent, amount_of_substance_exponent, luminous_intensity_exponent)
Definition at line 24001 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Member Function Documentation
amount_of_substance_exponent()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents.amount_of_substance_exponent ()
Definition at line 24081 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents._amount_of_substance_exponent, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents.amount_of_substance_exponent, and SCL.TypeChecker.check_type().
electric_current_exponent()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents.electric_current_exponent ()
Definition at line 24053 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents._electric_current_exponent, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents.electric_current_exponent.
length_exponent()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents.length_exponent ()
Definition at line 24011 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents._length_exponent, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents.length_exponent.
luminous_intensity_exponent()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents.luminous_intensity_exponent ()
Definition at line 24095 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents._luminous_intensity_exponent, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents.luminous_intensity_exponent.
mass_exponent()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents.mass_exponent ()
Definition at line 24025 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents._mass_exponent, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents.mass_exponent.
thermodynamic_temperature_exponent()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents.thermodynamic_temperature_exponent ()
Definition at line 24067 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents._thermodynamic_temperature_exponent, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents.thermodynamic_temperature_exponent.
time_exponent()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents.time_exponent ()
Definition at line 24039 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents._time_exponent, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents.time_exponent.
Member Data Documentation
amount_of_substance_exponent
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents.amount_of_substance_exponent
Definition at line 24007 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents.amount_of_substance_exponent().
electric_current_exponent
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents.electric_current_exponent
Definition at line 24005 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents.electric_current_exponent().
length_exponent
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents.length_exponent
Definition at line 24002 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents.length_exponent().
luminous_intensity_exponent
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents.luminous_intensity_exponent
Definition at line 24008 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents.luminous_intensity_exponent().
mass_exponent
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents.mass_exponent
Definition at line 24003 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents.mass_exponent().
thermodynamic_temperature_exponent
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents.thermodynamic_temperature_exponent
Definition at line 24006 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents.thermodynamic_temperature_exponent().
time_exponent
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents.time_exponent
Definition at line 24004 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_exponents.time_exponent().
The documentation for this class was generated from the following file:
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py