FreeCAD: Base::Uuid Class Reference
Base::Uuid Class Reference
#include <Uuid.h>
Public Member Functions
Uuid ()
Construction.
Uuid (const Uuid &)=default
Uuid (Uuid &&)=default
Uuid & operator= (const Uuid &)=default
Uuid & operator= (Uuid &&)=default
virtual ~Uuid ()
Destruction.
void setValue (const char *sString)
void setValue (const std::string &sString)
const std::string & getValue () const
bool operator== (const Uuid &other) const
bool operator< (const Uuid &other) const
Static Public Member Functions
static std::string createUuid ()
Detailed Description
Creates a Uuid
Author
Jürgen Riegel
Definition at line 60 of file Uuid.h.
Constructor & Destructor Documentation
Uuid() [1/3]
Uuid::Uuid ()
Construction.
A constructor. A more elaborate description of the constructor.
Definition at line 45 of file Uuid.cpp.
References createUuid().
Referenced by createUuid().
Uuid() [2/3]
Base::Uuid::Uuid (const Uuid &) default
Uuid() [3/3]
Base::Uuid::Uuid (Uuid &&) default
~Uuid()
Uuid::~Uuid () virtual default
Destruction.
A destructor. A more elaborate description of the destructor.
Member Function Documentation
createUuid()
std::string Uuid::createUuid () static
Definition at line 60 of file Uuid.cpp.
References Uuid().
Referenced by App::Document::exportObjects(), App::Document::importObjects(), App::ProjectFile::replaceInputFile(), App::ProjectFile::replaceInputFiles(), App::ProjectFile::replaceProjectFile(), App::ProjectFile::replacePropertyFiles(), Sandbox::DocumentSaverThread::run(), App::Document::saveToFile(), and Uuid().
getValue()
const std::string & Uuid::getValue () const
Definition at line 90 of file Uuid.cpp.
Referenced by App::PropertyFileIncluded::getUniqueFileName().
operator<()
bool Base::Uuid::operator< (const Uuid & other) const inline
Definition at line 101 of file Uuid.h.
operator=() [1/2]
Uuid& Base::Uuid::operator= (const Uuid &) default
operator=() [2/2]
Uuid& Base::Uuid::operator= (Uuid &&) default
operator==()
bool Base::Uuid::operator== (const Uuid & other) const inline
Definition at line 97 of file Uuid.h.
setValue() [1/2]
void Uuid::setValue (const char * sString)
Definition at line 70 of file Uuid.cpp.
Referenced by setValue().
setValue() [2/2]
void Uuid::setValue (const std::string & sString)
Definition at line 85 of file Uuid.cpp.
References setValue().
The documentation for this class was generated from the following files:
Uuid.h
Uuid.cpp