FreeCAD: Gui::Dialog::PreferencePage Class Reference
Gui::Dialog::PreferencePage Class Reference abstract
#include <PropertyPage.h>
Public Slots
virtual void loadSettings ()=0
virtual void saveSettings ()=0
virtual void resetSettingsToDefaults ()
Public Member Functions
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Protected Member Functions
void changeEvent (QEvent *event) override=0
Detailed Description
Base class for preferences pages.
Author
Werner Mayer
Definition at line 108 of file PropertyPage.h.
Constructor & Destructor Documentation
PreferencePage()
PreferencePage::PreferencePage (QWidget * parent = nullptr) explicit
Construction
Definition at line 102 of file PropertyPage.cpp.
~PreferencePage()
Gui::Dialog::PreferencePage::~PreferencePage () override default
Member Function Documentation
changeEvent()
void PreferencePage::changeEvent (QEvent * event) override protected pure virtual
Implemented in Gui::Dialog::DlgSettingsLightSources, TechDrawGui::DlgPrefsTechDrawAdvancedImp, Gui::Dialog::DlgSettingsGeneral, Gui::Dialog::PreferencePagePython, Gui::Dialog::PreferenceUiForm, SketcherGui::SketcherSettingsAppearance, SketcherGui::SketcherSettingsDisplay, Gui::Dialog::DlgSettingsWorkbenchesImp, SketcherGui::SketcherSettingsGrid, Gui::Dialog::DlgSettingsDocumentImp, Gui::Dialog::DlgOnlineHelpImp, Gui::Dialog::DlgSettingsCacheDirectory, Gui::Dialog::DlgSettingsMacroImp, Gui::Dialog::DlgSettingsPythonConsole, Gui::Dialog::DlgSettingsViewColor, Gui::Dialog::DlgSettingsNotificationArea, Gui::Dialog::DlgSettingsReportView, PartGui::DlgImportExportStep, PartGui::DlgExportHeaderStep, Gui::Dialog::DlgSettingsUI, SketcherGui::SketcherSettings, FemGui::DlgSettingsFemCcxImp, FemGui::DlgSettingsFemElmerImp, MeshGui::DlgSettingsMeshView, FemGui::DlgSettingsFemMystranImp, FemGui::DlgSettingsFemZ88Imp, FemGui::DlgSettingsFemGmshImp, MeshGui::DlgSettingsImportExport, TechDrawGui::DlgPrefsTechDrawScaleImp, FemGui::DlgSettingsFemExportAbaqusImp, FemGui::DlgSettingsFemInOutVtkImp, PartGui::DlgSettingsObjectColor, SpreadsheetGui::DlgSettingsImp, TechDrawGui::DlgPrefsTechDrawDimensionsImp, FemGui::DlgSettingsFemGeneralImp, PartGui::DlgSettings3DViewPart, TechDrawGui::DlgPrefsTechDrawColorsImp, TechDrawGui::DlgPrefsTechDrawGeneralImp, TechDrawGui::DlgPrefsTechDrawHLRImp, PathGui::DlgSettingsPathColor, MeasureGui::DlgPrefsMeasureAppearanceImp, Gui::Dialog::DlgSettingsEditor, PartGui::DlgImportStep, MatGui::DlgSettingsDefaultMaterial, MatGui::DlgSettingsMaterial, PartGui::DlgImportExportIges, PartGui::DlgExportStep, Gui::Dialog::DlgSettingsNavigation, Gui::Dialog::DlgSettings3DViewImp, TechDrawGui::DlgPrefsTechDrawAnnotationImp, Gui::Dialog::DlgSettingsSelection, PartGui::DlgSettingsGeneral, and Gui::Dialog::DlgSettingsAdvanced.
Definition at line 106 of file PropertyPage.cpp.
Referenced by Gui::Dialog::DlgSettings3DViewImp::changeEvent(), and Gui::Dialog::DlgSettingsLightSources::changeEvent().
hasHeightForWidth()
bool Gui::Dialog::PreferencePage::hasHeightForWidth () const inline override
Definition at line 121 of file PropertyPage.h.
isRestartRequired()
bool PreferencePage::isRestartRequired () const
Definition at line 111 of file PropertyPage.cpp.
loadSettings
virtual void Gui::Dialog::PreferencePage::loadSettings () pure virtual slot
Implemented in Gui::Dialog::PreferencePagePython, Gui::Dialog::PreferenceUiForm, SketcherGui::SketcherSettingsAppearance, SketcherGui::SketcherSettingsDisplay, SketcherGui::SketcherSettingsGrid, Gui::Dialog::DlgOnlineHelpImp, Gui::Dialog::DlgSettingsWorkbenchesImp, Gui::Dialog::DlgSettingsCacheDirectory, Gui::Dialog::DlgSettingsDocumentImp, Gui::Dialog::DlgSettingsMacroImp, Gui::Dialog::DlgSettingsPythonConsole, Gui::Dialog::DlgSettingsViewColor, Gui::Dialog::DlgSettingsNotificationArea, Gui::Dialog::DlgSettingsReportView, PartGui::DlgImportExportStep, PartGui::DlgExportHeaderStep, FemGui::DlgSettingsFemCcxImp, FemGui::DlgSettingsFemElmerImp, MeshGui::DlgSettingsMeshView, FemGui::DlgSettingsFemMystranImp, FemGui::DlgSettingsFemZ88Imp, Gui::Dialog::DlgSettingsUI, FemGui::DlgSettingsFemGmshImp, MeshGui::DlgSettingsImportExport, SketcherGui::SketcherSettings, TechDrawGui::DlgPrefsTechDrawScaleImp, FemGui::DlgSettingsFemExportAbaqusImp, FemGui::DlgSettingsFemInOutVtkImp, SpreadsheetGui::DlgSettingsImp, TechDrawGui::DlgPrefsTechDrawDimensionsImp, FemGui::DlgSettingsFemGeneralImp, PartGui::DlgSettings3DViewPart, PartGui::DlgSettingsObjectColor, TechDrawGui::DlgPrefsTechDrawAdvancedImp, TechDrawGui::DlgPrefsTechDrawColorsImp, TechDrawGui::DlgPrefsTechDrawGeneralImp, TechDrawGui::DlgPrefsTechDrawHLRImp, MeasureGui::DlgPrefsMeasureAppearanceImp, PathGui::DlgSettingsPathColor, MatGui::DlgSettingsDefaultMaterial, MatGui::DlgSettingsMaterial, PartGui::DlgImportExportIges, PartGui::DlgImportStep, Gui::Dialog::DlgSettingsGeneral, Gui::Dialog::DlgSettingsLightSources, PartGui::DlgExportStep, Gui::Dialog::DlgSettingsEditor, TechDrawGui::DlgPrefsTechDrawAnnotationImp, Gui::Dialog::DlgSettingsNavigation, Gui::Dialog::DlgSettings3DViewImp, Gui::Dialog::DlgSettingsSelection, PartGui::DlgSettingsGeneral, and Gui::Dialog::DlgSettingsAdvanced.
requireRestart()
void PreferencePage::requireRestart ()
Definition at line 116 of file PropertyPage.cpp.
Referenced by SketcherGui::SketcherSettings::checkForRestart(), Gui::Dialog::DlgSettingsWorkbenchesImp::onWbByTabToggled(), Gui::Dialog::DlgSettingsWorkbenchesImp::resetSettingsToDefaults(), Gui::Dialog::DlgSettingsNavigation::saveSettings(), Gui::Dialog::DlgSettingsGeneral::saveSettings(), and TechDrawGui::DlgPrefsTechDrawDimensionsImp::saveSettings().
resetSettingsToDefaults
void PreferencePage::resetSettingsToDefaults () virtual slot
Reimplemented in Gui::Dialog::DlgSettingsWorkbenchesImp, Gui::Dialog::DlgSettingsCacheDirectory, Gui::Dialog::DlgSettingsMacroImp, SketcherGui::SketcherSettings, TechDrawGui::DlgPrefsTechDrawDimensionsImp, Gui::Dialog::DlgSettingsGeneral, Gui::Dialog::DlgSettingsLightSources, Gui::Dialog::DlgSettingsEditor, Gui::Dialog::DlgSettingsNavigation, and Gui::Dialog::DlgSettings3DViewImp.
Definition at line 218 of file PropertyPage.cpp.
References App::GetApplication(), App::Application::GetParameterGroupByPath(), ParameterGrp::GetParameterNames(), and ParameterGrp::RemoveAttribute().
Referenced by Gui::Dialog::DlgSettings3DViewImp::resetSettingsToDefaults(), Gui::Dialog::DlgSettingsNavigation::resetSettingsToDefaults(), Gui::Dialog::DlgSettingsEditor::resetSettingsToDefaults(), Gui::Dialog::DlgSettingsGeneral::resetSettingsToDefaults(), Gui::Dialog::DlgSettingsLightSources::resetSettingsToDefaults(), Gui::Dialog::DlgSettingsCacheDirectory::resetSettingsToDefaults(), Gui::Dialog::DlgSettingsMacroImp::resetSettingsToDefaults(), and Gui::Dialog::DlgSettingsWorkbenchesImp::resetSettingsToDefaults().
saveSettings
virtual void Gui::Dialog::PreferencePage::saveSettings () pure virtual slot
Implemented in Gui::Dialog::PreferencePagePython, Gui::Dialog::PreferenceUiForm, SketcherGui::SketcherSettingsAppearance, SketcherGui::SketcherSettingsDisplay, SketcherGui::SketcherSettingsGrid, Gui::Dialog::DlgOnlineHelpImp, Gui::Dialog::DlgSettingsWorkbenchesImp, Gui::Dialog::DlgSettingsCacheDirectory, Gui::Dialog::DlgSettingsDocumentImp, Gui::Dialog::DlgSettingsMacroImp, Gui::Dialog::DlgSettingsPythonConsole, Gui::Dialog::DlgSettingsViewColor, Gui::Dialog::DlgSettingsNotificationArea, Gui::Dialog::DlgSettingsReportView, PartGui::DlgImportExportStep, PartGui::DlgExportHeaderStep, FemGui::DlgSettingsFemCcxImp, FemGui::DlgSettingsFemElmerImp, MeshGui::DlgSettingsMeshView, FemGui::DlgSettingsFemMystranImp, FemGui::DlgSettingsFemZ88Imp, Gui::Dialog::DlgSettingsUI, FemGui::DlgSettingsFemGmshImp, MeshGui::DlgSettingsImportExport, SketcherGui::SketcherSettings, TechDrawGui::DlgPrefsTechDrawScaleImp, FemGui::DlgSettingsFemExportAbaqusImp, FemGui::DlgSettingsFemInOutVtkImp, SpreadsheetGui::DlgSettingsImp, TechDrawGui::DlgPrefsTechDrawDimensionsImp, FemGui::DlgSettingsFemGeneralImp, PartGui::DlgSettings3DViewPart, PartGui::DlgSettingsObjectColor, TechDrawGui::DlgPrefsTechDrawAdvancedImp, TechDrawGui::DlgPrefsTechDrawColorsImp, TechDrawGui::DlgPrefsTechDrawGeneralImp, TechDrawGui::DlgPrefsTechDrawHLRImp, MeasureGui::DlgPrefsMeasureAppearanceImp, PathGui::DlgSettingsPathColor, MatGui::DlgSettingsDefaultMaterial, MatGui::DlgSettingsMaterial, PartGui::DlgImportExportIges, PartGui::DlgImportStep, Gui::Dialog::DlgSettingsGeneral, Gui::Dialog::DlgSettingsLightSources, PartGui::DlgExportStep, Gui::Dialog::DlgSettingsEditor, TechDrawGui::DlgPrefsTechDrawAnnotationImp, Gui::Dialog::DlgSettingsNavigation, Gui::Dialog::DlgSettings3DViewImp, Gui::Dialog::DlgSettingsSelection, PartGui::DlgSettingsGeneral, and Gui::Dialog::DlgSettingsAdvanced.
The documentation for this class was generated from the following files:
PropertyPage.h
PropertyPage.cpp