FreeCAD: src.Mod.AddonManager.AddonManagerTest.gui.test_python_deps_gui.TestPythonPackageManager Class Reference
src.Mod.AddonManager.AddonManagerTest.gui.test_python_deps_gui.TestPythonPackageManager Class Reference
Public Member Functions
None setUp (self)
None tearDown (self)
def test_show (self, patched_create_list_from_pip)
Public Attributes
manager
Detailed Description
Definition at line 30 of file test_python_deps_gui.py.
Member Function Documentation
setUp()
None src.Mod.AddonManager.AddonManagerTest.gui.test_python_deps_gui.TestPythonPackageManager.setUp (self)
Definition at line 32 of file test_python_deps_gui.py.
tearDown()
None src.Mod.AddonManager.AddonManagerTest.gui.test_python_deps_gui.TestPythonPackageManager.tearDown (self)
Definition at line 35 of file test_python_deps_gui.py.
References src.Mod.AddonManager.AddonManagerTest.gui.test_python_deps_gui.TestPythonPackageManager.manager.
Referenced by CAMTests.TestPathHelix.TestPathHelix.test03(), CAMTests.TestPathHelix.TestPathHelix.test04(), and CAMTests.TestPathHelix.TestPathHelix.testRecomputeHelixFromV021().
test_show()
def src.Mod.AddonManager.AddonManagerTest.gui.test_python_deps_gui.TestPythonPackageManager.test_show (self, patched_create_list_from_pip)
Definition at line 41 of file test_python_deps_gui.py.
References src.Mod.AddonManager.AddonManagerTest.gui.test_python_deps_gui.TestPythonPackageManager.manager, and bimcommands.BimViews.show().
Member Data Documentation
manager
src.Mod.AddonManager.AddonManagerTest.gui.test_python_deps_gui.TestPythonPackageManager.manager
Definition at line 33 of file test_python_deps_gui.py.
Referenced by src.Mod.AddonManager.AddonManagerTest.gui.test_python_deps_gui.TestPythonPackageManager.tearDown(), and src.Mod.AddonManager.AddonManagerTest.gui.test_python_deps_gui.TestPythonPackageManager.test_show().
The documentation for this class was generated from the following file:
test_python_deps_gui.py