FreeCAD: MeshGui::ViewProviderMesh Class Reference
MeshGui::ViewProviderMesh Class Reference
#include <ViewProvider.h>
Public Member Functions
ViewProviderMesh ()
~ViewProviderMesh () override
void attach (App::DocumentObject *obj) override
void updateData (const App::Property *prop) override
bool useNewSelectionModel () const override
indicates if the ViewProvider use the new Selection model
Gui::SoFCSelection * getHighlightNode () const
QIcon getIcon () const override
deliver the icon shown in the tree view
void setDisplayMode (const char *ModeName) override
Sets the correct display mode.
std::vector< std::string > getDisplayModes () const override
returns a list of all possible modes
bool exportToVrml (const char *filename, const MeshCore::Material &, bool binary=false) const
void exportMesh (const char *filename, const char *fmt=nullptr) const
void setupContextMenu (QMenu *menu, QObject *receiver, const char *member) override
set up the context-menu with the supported edit modes
PyObject * getPyObject () override
Get the python wrapper for that ViewProvider.
Editing
bool doubleClicked () override
is called by the tree if the user double clicks on the object
bool isFacetSelected (Mesh::FacetIndex facet)
void selectComponent (Mesh::FacetIndex facet)
void deselectComponent (Mesh::FacetIndex facet)
void selectFacet (Mesh::FacetIndex facet)
void deselectFacet (Mesh::FacetIndex facet)
void setSelection (const std::vector< Mesh::FacetIndex > &)
void addSelection (const std::vector< Mesh::FacetIndex > &)
void removeSelection (const std::vector< Mesh::FacetIndex > &)
void invertSelection ()
void clearSelection ()
void deleteSelection ()
bool hasSelection () const
void getFacetsFromPolygon (const std::vector< SbVec2f > &picked, const Base::ViewProjMethod &proj, SbBool inner, std::vector< Mesh::FacetIndex > &indices) const
std::vector< Mesh::FacetIndex > getFacetsOfRegion (const SbViewportRegion &, const SbViewportRegion &, SoCamera *) const
std::vector< Mesh::FacetIndex > getVisibleFacetsAfterZoom (const SbBox2s &, const SbViewportRegion &, SoCamera *) const
std::vector< Mesh::FacetIndex > getVisibleFacets (const SbViewportRegion &, SoCamera *) const
virtual void cutMesh (const std::vector< SbVec2f > &polygon, const Base::ViewProjMethod &proj, SbBool inner)
virtual void trimMesh (const std::vector< SbVec2f > &polygon, const Base::ViewProjMethod &proj, SbBool inner)
virtual void appendFacets (const std::vector< Mesh::FacetIndex > &)
virtual void removeFacets (const std::vector< Mesh::FacetIndex > &)
void setFacetTransparency (const std::vector< float > &)
void resetFacetTransparency ()
void highlightSegments (const std::vector< App::Color > &)
Public Member Functions inherited from Gui::ViewProviderGeometryObject
ViewProviderGeometryObject ()
constructor.
~ViewProviderGeometryObject () override
destructor.
bool isSelectable () const override
SoPickedPointList getPickedPoints (const SbVec2s &pos, const View3DInventorViewer &viewer, bool pickAll=false) const
SoPickedPoint * getPickedPoint (const SbVec2s &pos, const View3DInventorViewer &viewer) const
virtual void showBoundingBox (bool)
Public Member Functions inherited from Gui::ViewProviderDragger
ViewProviderDragger ()
constructor.
~ViewProviderDragger () override
destructor.
Base::Placement getTransformOrigin () const
Convenience method to obtain the transform origin.
void setTransformOrigin (const Base::Placement &placement)
Convenience method to set the transform origin.
void resetTransformOrigin ()
Resets transform origin to the object origin.
ViewProvider * startEditing (int ModNum=0) override
void updatePlacementFromDragger ()
updates placement of object based on dragger position
void updateTransformFromDragger ()
updates transform of object based on dragger position, can be used to preview movement
Base::Placement getObjectPlacement () const
Gets object placement relative to its coordinate system.
Base::Placement getDraggerPlacement () const
Gets current dragger placement, including current dragger movement.
Base::Placement getOriginalDraggerPlacement () const
Gets original dragger placement, without current dragger movement.
void setDraggerPlacement (const Base::Placement &placement)
Sets placement of dragger relative to objects origin.
Public Member Functions inherited from Gui::ViewProviderDocumentObject
ViewProviderDocumentObject ()
constructor.
~ViewProviderDocumentObject () override
destructor.
virtual void reattach (App::DocumentObject *)
void update (const App::Property *) override
void setActiveMode ()
Set the active mode, i.e. the first item of the 'Display' property.
void hide () override
Hide the object in the view.
void show () override
Show the object in the view.
const char * getTransactionText () const override
bool canDropObjectEx (App::DocumentObject *, App::DocumentObject *, const char *, const std::vector< std::string > &) const override
int replaceObject (App::DocumentObject *, App::DocumentObject *) override
bool showInTree () const override
void getTaskViewContent (std::vector< Gui::TaskView::TaskContent * > &) const override
Get a list of TaskBoxes associated with this object.
void updateView ()
Run a redraw.
App::DocumentObject * getObject () const
Get the object of this ViewProvider object.
template<class T >
T * getObject () const
Get the object of this ViewProvider object as specified type.
bool canDelete (App::DocumentObject *obj) const override
Asks the view provider if the given object can be deleted.
virtual bool acceptDeletionsInEdit ()
Ask the view provider if it accepts object deletions while in edit.
Gui::Document * getDocument () const
Get the GUI document to this ViewProvider object.
bool getElementPicked (const SoPickedPoint *, std::string &subname) const override
return a hit element given the picked point which contains the full node path
bool getDetailPath (const char *subname, SoFullPath *pPath, bool append, SoDetail *&det) const override
return the coin node detail and path to the node of the subname
virtual void forceUpdate (bool enable=true)
virtual bool isUpdateForced () const
virtual void startRestoring ()
int getTreeRank () const
void setTreeRank (int value)
bool removeDynamicProperty (const char *prop) override
App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false) override
virtual ViewProviderDocumentObject * getLinkedViewProvider (std::string *subname=nullptr, bool recursive=false) const
std::string getFullName () const override
virtual bool allowOverride (const App::DocumentObject &) const
void setShowable (bool enable)
bool isShowable () const
void startDefaultEditMode ()
Public Member Functions inherited from Gui::ViewProvider
ViewProvider ()
constructor.
~ViewProvider () override
destructor.
virtual SoSeparator * getRoot () const
SoSwitch * getModeSwitch () const
SoTransform * getTransformNode () const
SoSeparator * getAnnotation ()
virtual SoSeparator * getFrontRoot () const
virtual SoGroup * getChildRoot () const
virtual SoSeparator * getBackRoot () const
virtual bool canAddToSceneGraph () const
Indicate whether to be added to scene graph or not.
virtual bool isPartOfPhysicalObject () const
virtual std::vector< App::DocumentObject * > claimChildren3D () const
virtual std::string getElement (const SoDetail *) const
return a hit element to the selection path or 0
virtual SoDetail * getDetail (const char *) const
return the coin node detail of the subelement
int partialRender (const std::vector< std::string > &subelements, bool clear)
virtual std::vector< Base::Vector3d > getModelPoints (const SoPickedPoint *) const
virtual std::vector< Base::Vector3d > getSelectionShape (const char *Element) const
return the highlight lines for a given element or the whole shape
Base::BoundBox3d getBoundingBox (const char *subname=nullptr, bool transform=true, MDIView *view=nullptr) const
virtual bool onDelete (const std::vector< std::string > &subNames)
virtual void beforeDelete ()
virtual bool canDragObjects () const
virtual bool canDragObject (App::DocumentObject *) const
virtual bool canDragObjectToTarget (App::DocumentObject *obj, App::DocumentObject *target) const
virtual void dragObject (App::DocumentObject *)
virtual bool canDropObjects () const
virtual bool canDropObject (App::DocumentObject *) const
virtual bool canDragAndDropObject (App::DocumentObject *) const
virtual void dropObject (App::DocumentObject *)
virtual bool acceptReorderingObjects () const
virtual std::string getDropPrefix () const
return a subname referencing the sub-object holding the dropped objects
virtual std::string dropObjectEx (App::DocumentObject *obj, App::DocumentObject *owner, const char *subname, const std::vector< std::string > &elements)
virtual bool canRemoveChildrenFromRoot () const
std::string getActiveDisplayMode () const
virtual const char * getDefaultDisplayMode () const
get the default display mode
virtual bool isShow () const
checks whether the view provider is visible or not
void setVisible (bool)
bool isVisible () const
void setLinkVisible (bool)
bool isLinkVisible () const
virtual void setOverrideMode (const std::string &mode)
Overrides the display mode with mode.
const std::string getOverrideMode ()
virtual bool selectAll ()
virtual bool keyPressed (bool pressed, int key)
is called when the provider is in edit and a key event occurs. Only ESC ends edit.
virtual bool mouseMove (const SbVec2s &cursorPos, View3DInventorViewer *viewer)
is called when the provider is in edit and the mouse is moved
virtual bool mouseButtonPressed (int button, bool pressed, const SbVec2s &cursorPos, const View3DInventorViewer *viewer)
is called when the Provider is in edit and the mouse is clicked
virtual bool mouseWheelEvent (int delta, const SbVec2s &cursorPos, const View3DInventorViewer *viewer)
virtual QIcon mergeColorfulOverlayIcons (const QIcon &orig) const
virtual std::vector< App::DocumentObject * > claimChildren () const
virtual std::vector< App::DocumentObject * > claimChildrenRecursive () const
bool isUpdatesEnabled () const
void setUpdatesEnabled (bool enable)
unsigned long getStatus () const
return the status bits
bool testStatus (ViewStatus pos) const
void setStatus (ViewStatus pos, bool on)
std::string toString () const
virtual std::map< std::string, App::Color > getElementColors (const char *element=nullptr) const
virtual void setElementColors (const std::map< std::string, App::Color > &colors)
bool isEditing () const
void finishEditing ()
virtual void setTransformation (const Base::Matrix4D &rcMatrix)
set the viewing transformation of the provider
virtual void setTransformation (const SbMatrix &rcMatrix)
virtual MDIView * getMDIView () const
void Restore (Base::XMLReader &reader) override
bool isRestoring ()
void addDisplayMaskMode (SoNode *node, const char *type)
Adds a new display mask mode.
void setDisplayMaskMode (const char *type)
Activates the display mask mode type.
SoNode * getDisplayMaskMode (const char *type) const
Get the node to the display mask mode type.
std::vector< std::string > getDisplayMaskModes () const
Returns a list of added display mask modes.
void setDefaultMode (int)
int getDefaultMode () const
virtual void setRenderCacheMode (int)
Public Member Functions inherited from App::TransactionalObject
TransactionalObject ()
Constructor.
~TransactionalObject () override
Public Member Functions inherited from App::ExtensionContainer
ExtensionContainer ()
~ExtensionContainer () override
void registerExtension (Base::Type extension, App::Extension *ext)
bool hasExtension (Base::Type, bool derived=true) const
bool hasExtension (const std::string &name) const
bool hasExtensions () const
App::Extension * getExtension (Base::Type, bool derived=true, bool no_except=false) const
App::Extension * getExtension (const std::string &name) const
template<typename ExtensionT >
ExtensionT * getExtension () const
template<typename ExtensionT >
ExtensionT * getExtensionByType (bool no_except=false, bool derived=true) const
std::vector< Extension * > getExtensionsDerivedFrom (Base::Type type) const
template<typename ExtensionT >
std::vector< ExtensionT * > getExtensionsDerivedFromType () const
ExtensionIterator extensionBegin ()
ExtensionIterator extensionEnd ()
Property * getPropertyByName (const char *name) const override
find a property by its name
template<typename T >
T * getPropertyByName (const char *name) const
find a property by its name, dynamic cased to specified type
const char * getPropertyName (const Property *prop) const override
get the name of a property
void getPropertyMap (std::map< std::string, Property * > &Map) const override
get all properties of the class (including properties of the parent)
void getPropertyList (std::vector< Property * > &List) const override
get all properties of the class (including properties of the parent)
short getPropertyType (const Property *prop) const override
get the Type of a Property
short getPropertyType (const char *name) const override
get the Type of a named Property
const char * getPropertyGroup (const Property *prop) const override
get the Group of a Property
const char * getPropertyGroup (const char *name) const override
get the Group of a named Property
const char * getPropertyDocumentation (const Property *prop) const override
get the Group of a Property
const char * getPropertyDocumentation (const char *name) const override
get the Group of a named Property
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
void saveExtensions (Base::Writer &writer) const
void restoreExtensions (Base::XMLReader &reader)
void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName) override
void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop) override
Public Member Functions inherited from App::PropertyContainer
PropertyContainer ()
~PropertyContainer () override
unsigned int getMemSize () const override
virtual void getPropertyNamedList (std::vector< std::pair< const char *, Property * > > &List) const
get all properties with their names, may contain duplicates and aliases
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
bool isReadOnly (const Property *prop) const
check if the property is read-only
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isHidden (const Property *prop) const
check if the property is hidden
bool isHidden (const char *name) const
check if the named property is hidden
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
bool changeDynamicProperty (const Property *prop, const char *group, const char *doc)
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual App::Property * getDynamicPropertyByName (const char *name) const
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
virtual void beforeSave () const
virtual void editProperty (const char *)
const char * getPropertyPrefix () const
void setPropertyPrefix (const char *prefix)
PropertyContainer (const PropertyContainer &)=delete
PropertyContainer & operator= (const PropertyContainer &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Attributes
App::PropertyPercent LineTransparency
App::PropertyFloatConstraint LineWidth
App::PropertyFloatConstraint PointSize
App::PropertyFloatConstraint CreaseAngle
App::PropertyBool OpenEdges
App::PropertyBool Coloring
App::PropertyEnumeration Lighting
App::PropertyColor LineColor
Public Attributes inherited from Gui::ViewProviderGeometryObject
App::PropertyPercent Transparency
App::PropertyMaterialList ShapeAppearance
App::PropertyBool BoundingBox
App::PropertyBool Selectable
Public Attributes inherited from Gui::ViewProviderDragger
App::PropertyPlacement TransformOrigin
Public Attributes inherited from Gui::ViewProviderDocumentObject
App::PropertyEnumeration DisplayMode
App::PropertyBool Visibility
App::PropertyBool ShowInTree
App::PropertyEnumeration OnTopWhenSelected
App::PropertyEnumeration SelectionStyle
Public Attributes inherited from Gui::ViewProvider
boost::signals2::signal< void()> signalChangeIcon
signal on icon change
boost::signals2::signal< void(const QString &)> signalChangeToolTip
signal on tooltip change
boost::signals2::signal< void(const QString &)> signalChangeStatusTip
signal on status tip change
boost::signals2::signal< void(bool, Gui::HighlightMode)> signalChangeHighlight
signal on highlight change
Restoring view provider from document load
enum HighlighMode { HighlighMode::None, HighlighMode::Component, HighlighMode::Segment, HighlighMode::Color }
HighlighMode highlightMode
Gui::SoFCSelection * pcHighlight {nullptr}
SoGroup * pcShapeGroup {nullptr}
SoDrawStyle * pcLineStyle {nullptr}
SoDrawStyle * pcPointStyle {nullptr}
SoSeparator * pcOpenEdge {nullptr}
SoBaseColor * pOpenColor {nullptr}
SoMaterial * pLineColor {nullptr}
SoShapeHints * pShapeHints {nullptr}
SoMaterialBinding * pcMatBinding {nullptr}
void finishRestoring () override
bool setEdit (int ModNum) override
Sets the edit mode.
void unsetEdit (int ModNum) override
Unsets the edit mode.
void onChanged (const App::Property *prop) override
get called by the container whenever a property has been changed
virtual void showOpenEdges (bool)
void setOpenEdgeColorFrom (const App::Color &col)
virtual void splitMesh (const MeshCore::MeshKernel &toolMesh, const Base::Vector3f &normal, SbBool inner)
virtual void segmentMesh (const MeshCore::MeshKernel &toolMesh, const Base::Vector3f &normal, SbBool inner)
virtual void faceInfo (Mesh::FacetIndex facet)
virtual void fillHole (Mesh::FacetIndex facet)
virtual void selectArea (short, short, short, short, const SbViewportRegion &, SoCamera *)
virtual void highlightSelection ()
virtual void unhighlightSelection ()
void highlightComponents ()
void setHighlightedComponents (bool)
void highlightSegments ()
void setHighlightedSegments (bool)
void setHighlightedColors (bool)
void highlightColors ()
bool canHighlightColors () const
App::PropertyColorList * getColorProperty () const
Mesh::PropertyMaterial * getMaterialProperty () const
void tryColorPerVertexOrFace (bool)
void setColorPerVertex (const App::PropertyColorList *)
void setColorPerFace (const App::PropertyColorList *)
const Mesh::MeshObject & getMeshObject () const
const Mesh::PropertyMeshKernel & getMeshProperty () const
Mesh::PropertyMeshKernel & getMeshProperty ()
void setColorField (const std::vector< App::Color > &, SoMFColor &)
void setAmbientColor (const std::vector< App::Color > &)
void setDiffuseColor (const std::vector< App::Color > &)
void setSpecularColor (const std::vector< App::Color > &)
void setEmissiveColor (const std::vector< App::Color > &)
virtual SoShape * getShapeNode () const
virtual SoNode * getCoordNode () const
static void faceInfoCallback (void *ud, SoEventCallback *cb)
static void fillHoleCallback (void *ud, SoEventCallback *cb)
static void markPartCallback (void *ud, SoEventCallback *cb)
static void clipMeshCallback (void *ud, SoEventCallback *cb)
static void trimMeshCallback (void *ud, SoEventCallback *cb)
static void partMeshCallback (void *ud, SoEventCallback *cb)
static void segmMeshCallback (void *ud, SoEventCallback *cb)
static void selectGLCallback (void *ud, SoEventCallback *cb)
static bool createToolMesh (const std::vector< SbVec2f > &rclPoly, const SbViewVolume &vol, const Base::Vector3f &rcNormal, std::vector< MeshCore::MeshGeomFacet > &)
Creates a tool mesh from the previous picked polygon on the viewer.
Additional Inherited Members
Public Types inherited from Gui::ViewProvider
enum EditMode { Default = 0, Transform, Cutting, Color }
Public Types inherited from App::ExtensionContainer
using ExtensionIterator = std::map< Base::Type, App::Extension * >::iterator
Static Public Member Functions inherited from Gui::ViewProviderDragger
static void updateTransform (const Base::Placement &from, SoTransform *to)
Static Public Member Functions inherited from Gui::ViewProvider
static const std::string & hiddenMarker ()
static const char * hasHiddenMarker (const char *subname)
static SbMatrix convert (const Base::Matrix4D &rcMatrix)
static Base::Matrix4D convert (const SbMatrix &sbMat)
static void eventCallback (void *ud, SoEventCallback *node)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Protected Member Functions inherited from Gui::ViewProviderGeometryObject
void setSelectable (bool Selectable=true)
virtual unsigned long getBoundColor () const
void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName) override
PropertyContainer::handleChangedPropertyName is called during restore to possibly fix reading of older versions of this property container. This method is typically called if the property on file has changed its name in more recent versions.
void setCoinAppearance (const App::Material &source)
Protected Member Functions inherited from Gui::ViewProviderDragger
void setEditViewer (View3DInventorViewer *, int ModNum) override
adjust viewer settings when editing a view provider
void unsetEditViewer (View3DInventorViewer *) override
restores viewer settings when leaving editing mode
bool forwardToLink ()
virtual TaskView::TaskDialog * getTransformDialog ()
Protected Member Functions inherited from Gui::ViewProviderDocumentObject
Gui::MDIView * getActiveView () const
Gui::MDIView * getEditingView () const
Gui::MDIView * getInventorView () const
Gui::MDIView * getViewOfNode (SoNode *node) const
void onBeforeChange (const App::Property *prop) override
get called before the value is changed
SoNode * findFrontRootOfType (const SoType &type) const
bool isAttachedToDocument () const override
const char * detachFromDocument () override
void onPropertyStatusChanged (const App::Property &prop, unsigned long oldStatus) override
get called when a property status has changed
void setModeSwitch () override
Turn on mode switch.
void addDefaultAction (QMenu *, const QString &)
Protected Member Functions inherited from Gui::ViewProvider
virtual QIcon mergeGreyableOverlayIcons (const QIcon &orig) const
int getEditingMode () const
return the edit mode or -1 if nothing is being edited
bool checkRecursion (SoNode *)
SoPickedPoint * getPointOnRay (const SbVec2s &pos, const View3DInventorViewer *viewer) const
SoPickedPoint * getPointOnRay (const SbVec3f &pos, const SbVec3f &dir, const View3DInventorViewer *viewer) const
Protected Member Functions inherited from App::TransactionalObject
void onBeforeChangeProperty (Document *doc, const Property *prop)
Protected Member Functions inherited from App::PropertyContainer
virtual void onEarlyChange (const Property *)
virtual const PropertyData & getPropertyData () const
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Gui::ViewProviderGeometryObject
SoMaterial * pcShapeMaterial {nullptr}
SoFCBoundingBox * pcBoundingBox {nullptr}
SoSwitch * pcBoundSwitch {nullptr}
SoBaseColor * pcBoundColor {nullptr}
SoPickStyle * pickStyle {nullptr}
App::Material materialAppearance
Protected Attributes inherited from Gui::ViewProviderDragger
CoinPtr< SoFCCSysDragger > csysDragger = nullptr
ViewProvider * forwardedViewProvider = nullptr
Protected Attributes inherited from Gui::ViewProviderDocumentObject
App::DocumentObject * pcObject {nullptr}
Gui::Document * pcDocument {nullptr}
Protected Attributes inherited from Gui::ViewProvider
SoSeparator * pcRoot
The root Separator of the ViewProvider.
SoTransform * pcTransform
this is transformation for the provider
const char * sPixmap
SoSwitch * pcModeSwitch
this is the mode switch, all the different viewing modes are collected here
SoSeparator * pcAnnotation {nullptr}
The root separator for annotations.
ViewProviderPy * pyViewObject {nullptr}
std::string overrideMode
std::bitset< 32 > StatusBits
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Detailed Description
The ViewProviderMesh class offers the visualization of the mesh data structure and many algorithms to work on or edit the mesh.
Author
Werner Mayer
Definition at line 125 of file Mod/Mesh/Gui/ViewProvider.h.
Member Enumeration Documentation
HighlighMode
enum MeshGui::ViewProviderMesh::HighlighMode strong protected
Enumerator
None
Component
Segment
Color
Definition at line 274 of file Mod/Mesh/Gui/ViewProvider.h.
Constructor & Destructor Documentation
ViewProviderMesh()
ViewProviderMesh::ViewProviderMesh ()
Definition at line 207 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Gui::None.
~ViewProviderMesh()
ViewProviderMesh::~ViewProviderMesh () override
Definition at line 313 of file Mod/Mesh/Gui/ViewProvider.cpp.
References pcHighlight, pcLineStyle, pcMatBinding, pcPointStyle, pcShapeGroup, pLineColor, pOpenColor, and pShapeHints.
Member Function Documentation
addSelection()
void ViewProviderMesh::addSelection (const std::vector< Mesh::FacetIndex > & indices)
Definition at line 2183 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Mesh::MeshObject::addFacetsToSelection(), getMeshObject(), and highlightSelection().
Referenced by ReverseEngineeringGui::SegmentationManual::Private::findGeometry().
appendFacets()
void ViewProviderMesh::appendFacets (const std::vector< Mesh::FacetIndex > & facets) virtual
The triangles with the passed indices are already added to the mesh.
Definition at line 2013 of file Mod/Mesh/Gui/ViewProvider.cpp.
attach()
void ViewProviderMesh::attach (App::DocumentObject * obj) override virtual
Extracts the mesh data from the feature pcFeature and creates an Inventor node SoNode with these data.
Reimplemented from Gui::ViewProviderGeometryObject.
Reimplemented in MeshGui::ViewProviderMeshObject, MeshGui::ViewProviderIndexedFaceSet, MeshGui::ViewProviderMeshFaceSet, MeshGui::ViewProviderMeshTransformDemolding, and MeshGui::ViewProviderMeshTransform.
Definition at line 416 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Gui::ViewProvider::addDisplayMaskMode(), Coloring, Gui::SoFCSelection::documentName, getColorProperty(), App::DocumentObject::getDocument(), getMaterialProperty(), App::Document::getName(), App::DocumentObject::getNameInDocument(), App::Property::Hidden, Gui::SoFCSelection::objectName, MeshCore::MeshIO::OVERALL, pcHighlight, pcLineStyle, pcMatBinding, pcPointStyle, pcShapeGroup, Gui::ViewProviderGeometryObject::pcShapeMaterial, pLineColor, pShapeHints, App::Property::setStatus(), and Gui::SoFCSelection::subElementName.
Referenced by MeshGui::ViewProviderMeshTransform::attach(), MeshGui::ViewProviderMeshTransformDemolding::attach(), MeshGui::ViewProviderMeshFaceSet::attach(), MeshGui::ViewProviderIndexedFaceSet::attach(), and MeshGui::ViewProviderMeshObject::attach().
canHighlightColors()
bool ViewProviderMesh::canHighlightColors () const protected
Definition at line 2438 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Mesh::MeshObject::countFacets(), Mesh::MeshObject::countPoints(), getMeshObject(), App::ExtensionContainer::getPropertyByName(), and Gui::ViewProviderDocumentObject::pcObject.
Referenced by setupContextMenu().
clearSelection()
void ViewProviderMesh::clearSelection ()
Definition at line 2227 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Mesh::MeshObject::clearFacetSelection(), getMeshObject(), and unhighlightSelection().
Referenced by markPartCallback().
clipMeshCallback()
void ViewProviderMesh::clipMeshCallback (void * ud, SoEventCallback * cb) static
Definition at line 993 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Gui::Document::abortCommand(), Gui::Application::activeDocument(), Gui::Document::commitCommand(), Gui::ViewProvider::finishEditing(), Base::Persistence::getClassTypeId(), App::PropertyPlacement::getValue(), Gui::Inner, Gui::Application::Instance, Gui::Document::openCommand(), Gui::Outer, App::GeoFeature::Placement, Arch::QT_TRANSLATE_NOOP, Gui::View3DInventorViewer::setEditing(), Base::ViewProjMethod::setTransform(), Gui::Split, and Base::Placement::toMatrix().
createToolMesh()
bool ViewProviderMesh::createToolMesh (const std::vector< SbVec2f > & rclPoly, const SbViewVolume & vol, const Base::Vector3f & rcNormal, std::vector< MeshCore::MeshGeomFacet > & aFaces) static
Creates a tool mesh from the previous picked polygon on the viewer.
Definition at line 841 of file Mod/Mesh/Gui/ViewProvider.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, MeshCore::MeshGeomFacet::Area(), MeshCore::MeshGeomFacet::CalcNormal(), MeshCore::AbstractPolygonTriangulator::GetFacets(), MeshCore::MeshGeomFacet::GetNormal(), Base::Vector3< float_type >::Set(), MeshCore::AbstractPolygonTriangulator::SetPolygon(), and MeshCore::AbstractPolygonTriangulator::TriangulatePolygon().
Referenced by partMeshCallback(), and segmMeshCallback().
cutMesh()
void ViewProviderMesh::cutMesh (const std::vector< SbVec2f > & polygon, const Base::ViewProjMethod & proj, SbBool inner) virtual
Definition at line 1576 of file Mod/Mesh/Gui/ViewProvider.cpp.
References getFacetsFromPolygon(), and removeFacets().
Referenced by MeshGui::MeshSplit::cutMesh().
deleteSelection()
void ViewProviderMesh::deleteSelection ()
Definition at line 2234 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Mesh::MeshObject::clearFacetSelection(), Mesh::MeshObject::getFacetsFromSelection(), getMeshObject(), removeFacets(), and unhighlightSelection().
Referenced by markPartCallback().
deselectComponent()
void ViewProviderMesh::deselectComponent (Mesh::FacetIndex facet)
Definition at line 2147 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Mesh::MeshObject::getKernel(), getMeshObject(), Mesh::MeshObject::hasSelectedFacets(), highlightSelection(), Mesh::MeshObject::removeFacetsFromSelection(), MeshCore::MeshAlgorithm::ResetFacetFlag(), Path.Dressup.Utils::selection(), unhighlightSelection(), MeshCore::MeshFacet::VISIT, and MeshCore::MeshKernel::VisitNeighbourFacets().
deselectFacet()
void ViewProviderMesh::deselectFacet (Mesh::FacetIndex facet)
Definition at line 2098 of file Mod/Mesh/Gui/ViewProvider.cpp.
References SCL.SimpleDataTypes::c, Mesh::MeshObject::countFacets(), App::PropertyMaterialList::getDiffuseColor(), getMeshObject(), Mesh::MeshObject::hasSelectedFacets(), highlightSelection(), pcMatBinding, Gui::ViewProviderGeometryObject::pcShapeMaterial, MeshCore::MeshIO::PER_FACE, Mesh::MeshObject::removeFacetsFromSelection(), Path.Dressup.Utils::selection(), Gui::ViewProviderGeometryObject::ShapeAppearance, and unhighlightSelection().
doubleClicked()
bool MeshGui::ViewProviderMesh::doubleClicked () inline override virtual
is called by the tree if the user double clicks on the object
Reimplemented from Gui::ViewProviderDragger.
Definition at line 168 of file Mod/Mesh/Gui/ViewProvider.h.
exportMesh()
void ViewProviderMesh::exportMesh (const char * filename, const char * fmt = nullptr) const
Definition at line 756 of file Mod/Mesh/Gui/ViewProvider.cpp.
References MeshCore::Material::binding, SCL.SimpleDataTypes::c, importers.importIFCmulticore::colors, MeshCore::Material::diffuseColor, Path.Post.scripts.comparams_post::fmt(), MeshCore::MeshOutput::GetFormat(), Gui::ViewProviderDocumentObject::getObject(), SplineSurface::i, Mesh2Shape::mesh, MeshCore::MeshIO::OVERALL, Gui::ViewProviderGeometryObject::pcShapeMaterial, MeshCore::MeshIO::PER_FACE, MeshCore::MeshIO::PER_VERTEX, and MeshCore::MeshIO::Undefined.
exportToVrml()
bool ViewProviderMesh::exportToVrml (const char * filename, const MeshCore::Material & mat, bool binary = false) const
Definition at line 690 of file Mod/Mesh/Gui/ViewProvider.cpp.
References importers.importIFCmulticore::colors, MeshGui::ViewProviderMeshBuilder::createMesh(), MeshCore::Material::diffuseColor, toolbit-attributes::group, SplineSurface::i, Gui::ViewProviderDocumentObject::pcObject, Path.Post.scripts.refactored_centroid_post::str, and Gui::SoFCDB::writeNodesToString().
faceInfo()
void ViewProviderMesh::faceInfo (Mesh::FacetIndex facet) protected virtual
Definition at line 1884 of file Mod/Mesh/Gui/ViewProvider.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, MeshCore::MeshFacet::_aulNeighbours, MeshCore::MeshFacet::_aulPoints, Base::Console(), MeshCore::MeshKernel::GetFacet(), MeshCore::MeshKernel::GetFacets(), Mesh::MeshObject::getKernel(), getMeshObject(), Gui::ViewProviderDocumentObject::getObject(), Base::ConsoleSingleton::Message(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
faceInfoCallback()
void ViewProviderMesh::faceInfoCallback (void * ud, SoEventCallback * cb) static
Definition at line 1669 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Gui::GLFlagWindow::addFlag(), Base::Console(), App::GetApplication(), ParameterGrp::GetBool(), Base::BaseClass::getClassTypeId(), App::Application::GetParameterGroupByPath(), Base::BaseClass::isDerivedFrom(), NavigationIndicatorGui::menu, Base::ConsoleSingleton::Message(), RobotExample::pos, ParameterGrp::SetBool(), Gui::Flag::setText(), and Gui::FlagLayout::TopRight.
fillHole()
void ViewProviderMesh::fillHole (Mesh::FacetIndex facet) protected virtual
Definition at line 1914 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Gui::Application::activeDocument(), Mesh::MeshObject::addFacets(), Gui::Document::commitCommand(), MeshCore::MeshKernel::CountPoints(), Mesh2Shape::faces, MeshCore::MeshAlgorithm::FillupHole(), Gui::WindowParameter::getDefaultParameter(), MeshCore::MeshAlgorithm::GetFacetBorder(), ParameterGrp::GetGroup(), ParameterGrp::GetInt(), Mesh::MeshObject::getKernel(), getMeshObject(), getMeshProperty(), SplineSurface::i, Gui::Application::Instance, level(), updateLeaderLines::newPoints, Gui::Document::openCommand(), Arch::QT_TRANSLATE_NOOP, MeshCore::AbstractPolygonTriangulator::SetVerifier(), and MeshCore::MeshAlgorithm::SplitBoundaryLoops().
fillHoleCallback()
void ViewProviderMesh::fillHoleCallback (void * ud, SoEventCallback * cb) static
Definition at line 1762 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Base::Console(), NavigationIndicatorGui::menu, Base::ConsoleSingleton::Message(), and RobotExample::pos.
finishRestoring()
void ViewProviderMesh::finishRestoring () override virtual
Reimplemented from Gui::ViewProviderDocumentObject.
Definition at line 501 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Coloring, Gui::ViewProviderDocumentObject::finishRestoring(), App::PropertyBool::getValue(), and App::Property::touch().
getColorProperty()
App::PropertyColorList * ViewProviderMesh::getColorProperty () const protected
Definition at line 515 of file Mod/Mesh/Gui/ViewProvider.cpp.
References importers.importIFCmulticore::colors, Base::Persistence::getClassTypeId(), App::ExtensionContainer::getPropertyMap(), Gui::ViewProviderDocumentObject::pcObject, and Path.Post.scripts.grbl_post::type.
Referenced by attach(), removeFacets(), and tryColorPerVertexOrFace().
getCoordNode()
SoNode * ViewProviderMesh::getCoordNode () const protected virtual
Reimplemented in MeshGui::ViewProviderMeshObject, MeshGui::ViewProviderIndexedFaceSet, and MeshGui::ViewProviderMeshFaceSet.
Definition at line 407 of file Mod/Mesh/Gui/ViewProvider.cpp.
Referenced by getFacetsOfRegion(), and getVisibleFacets().
getDisplayModes()
std::vector< std::string > ViewProviderMesh::getDisplayModes () const override virtual
returns a list of all possible modes
Reimplemented from Gui::ViewProvider.
Reimplemented in MeshGui::ViewProviderMeshTransformDemolding, and MeshGui::ViewProviderMeshTransform.
Definition at line 677 of file Mod/Mesh/Gui/ViewProvider.cpp.
Referenced by MeshGui::ViewProviderMeshTransform::getDisplayModes(), and MeshGui::ViewProviderMeshTransformDemolding::getDisplayModes().
getFacetsFromPolygon()
void ViewProviderMesh::getFacetsFromPolygon (const std::vector< SbVec2f > & picked, const Base::ViewProjMethod & proj, SbBool inner, std::vector< Mesh::FacetIndex > & indices) const
Definition at line 1341 of file Mod/Mesh/Gui/ViewProvider.cpp.
References MeshCore::MeshAlgorithm::CheckFacets(), Base::Console(), Path.Base.Generator.dogboneII::generate(), getMeshObject(), Mesh2Shape::mesh, and Base::ConsoleSingleton::Message().
Referenced by cutMesh().
getFacetsOfRegion()
std::vector< Mesh::FacetIndex > ViewProviderMesh::getFacetsOfRegion (const SbViewportRegion & select, const SbViewportRegion & region, SoCamera * camera) const
Definition at line 1374 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Mesh2Shape::faces, getCoordNode(), getShapeNode(), Gui::SoGLSelectAction::indices, and Path.Op.Gui.Selection::select().
Referenced by selectArea().
getHighlightNode()
Gui::SoFCSelection* MeshGui::ViewProviderMesh::getHighlightNode () const inline
Definition at line 151 of file Mod/Mesh/Gui/ViewProvider.h.
getIcon()
QIcon ViewProviderMesh::getIcon () const override virtual
deliver the icon shown in the tree view
Reimplemented from Gui::ViewProvider.
Definition at line 509 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Gui::BitmapFactory(), and Gui::BitmapFactoryInst::pixmap().
getMaterialProperty()
Mesh::PropertyMaterial * ViewProviderMesh::getMaterialProperty () const protected
Definition at line 642 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Base::Persistence::getClassTypeId(), App::ExtensionContainer::getPropertyMap(), Gui::ViewProviderDocumentObject::pcObject, and Path.Post.scripts.grbl_post::type.
Referenced by attach(), and tryColorPerVertexOrFace().
getMeshObject()
const Mesh::MeshObject & ViewProviderMesh::getMeshObject () const protected
Definition at line 397 of file Mod/Mesh/Gui/ViewProvider.cpp.
References getMeshProperty(), and Mesh::PropertyMeshKernel::getValue().
Referenced by addSelection(), MeshGui::ViewProviderMeshTransformDemolding::calcNormalVector(), canHighlightColors(), clearSelection(), deleteSelection(), deselectComponent(), deselectFacet(), faceInfo(), fillHole(), getFacetsFromPolygon(), getVisibleFacets(), hasSelection(), highlightColors(), highlightComponents(), highlightSegments(), highlightSelection(), invertSelection(), isFacetSelected(), removeSelection(), selectArea(), selectComponent(), selectFacet(), MeshGui::ViewProviderMeshTransformDemolding::setCenterPoint(), setSelection(), MeshGui::ViewProviderMeshFaceSet::showOpenEdges(), MeshGui::ViewProviderIndexedFaceSet::showOpenEdges(), and tryColorPerVertexOrFace().
getMeshProperty() [1/2]
Mesh::PropertyMeshKernel& MeshGui::ViewProviderMesh::getMeshProperty () protected
getMeshProperty() [2/2]
Mesh::PropertyMeshKernel & ViewProviderMesh::getMeshProperty () const protected
Definition at line 387 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Gui::ViewProviderDocumentObject::getObject().
Referenced by fillHole(), getMeshObject(), removeFacets(), segmentMesh(), splitMesh(), and trimMesh().
getPyObject()
PyObject * ViewProviderMesh::getPyObject () override virtual
Get the python wrapper for that ViewProvider.
Reimplemented from Gui::ViewProviderGeometryObject.
Definition at line 2459 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Gui::ViewProvider::pyViewObject.
getShapeNode()
SoShape * ViewProviderMesh::getShapeNode () const protected virtual
Reimplemented in MeshGui::ViewProviderMeshObject, MeshGui::ViewProviderIndexedFaceSet, and MeshGui::ViewProviderMeshFaceSet.
Definition at line 402 of file Mod/Mesh/Gui/ViewProvider.cpp.
Referenced by getFacetsOfRegion(), and getVisibleFacets().
getVisibleFacets()
std::vector< Mesh::FacetIndex > ViewProviderMesh::getVisibleFacets (const SbViewportRegion & vp, SoCamera * camera) const
Definition at line 1514 of file Mod/Mesh/Gui/ViewProvider.cpp.
References draftgeoutils.faces::bind(), src.Mod.AddonManager.NetworkManager::count, Mesh2Shape::faces, getCoordNode(), getMeshObject(), getShapeNode(), SplineSurface::i, Mesh2Shape::mesh, MeshCore::MeshIO::PER_FACE, Gui::SoQtOffscreenRenderer::render(), Gui::SoQtOffscreenRenderer::setBackgroundColor(), InitGui::t, Gui::SoQtOffscreenRenderer::writeToImage(), MovieTool::x, and MovieTool::y.
Referenced by getVisibleFacetsAfterZoom().
getVisibleFacetsAfterZoom()
std::vector< Mesh::FacetIndex > ViewProviderMesh::getVisibleFacetsAfterZoom (const SbBox2s & rect, const SbViewportRegion & vp, SoCamera * camera) const
Definition at line 1466 of file Mod/Mesh/Gui/ViewProvider.cpp.
References getVisibleFacets().
hasSelection()
bool ViewProviderMesh::hasSelection () const
Definition at line 2246 of file Mod/Mesh/Gui/ViewProvider.cpp.
References getMeshObject(), and Mesh::MeshObject::hasSelectedFacets().
highlightColors()
void ViewProviderMesh::highlightColors () protected
Definition at line 2419 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Mesh::MeshObject::countFacets(), Mesh::MeshObject::countPoints(), getMeshObject(), App::ExtensionContainer::getPropertyByName(), Gui::ViewProviderDocumentObject::pcObject, setColorPerFace(), and setColorPerVertex().
Referenced by setHighlightedColors().
highlightComponents()
void ViewProviderMesh::highlightComponents () protected
Definition at line 2317 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Mesh::MeshObject::countFacets(), Mesh::MeshObject::getComponents(), getMeshObject(), KDL::max(), pcMatBinding, Gui::ViewProviderGeometryObject::pcShapeMaterial, and MeshCore::MeshIO::PER_FACE.
Referenced by setEdit(), and setHighlightedComponents().
highlightSegments() [1/2]
void ViewProviderMesh::highlightSegments () protected
Definition at line 2359 of file Mod/Mesh/Gui/ViewProvider.cpp.
References importers.importIFCmulticore::colors, Mesh::MeshObject::countSegments(), App::Color::fromHexString(), Mesh::Segment::getColor(), App::PropertyMaterialList::getDiffuseColor(), getMeshObject(), Mesh::MeshObject::getSegment(), SplineSurface::i, and Gui::ViewProviderGeometryObject::ShapeAppearance.
Referenced by setHighlightedSegments().
highlightSegments() [2/2]
void ViewProviderMesh::highlightSegments (const std::vector< App::Color > & colors)
Definition at line 2376 of file Mod/Mesh/Gui/ViewProvider.cpp.
References importers.importIFCmulticore::colors, Mesh::MeshObject::countFacets(), Mesh::MeshObject::countSegments(), Mesh::Segment::getIndices(), getMeshObject(), Mesh::MeshObject::getSegment(), SplineSurface::i, MeshCore::MeshIO::OVERALL, pcMatBinding, Gui::ViewProviderGeometryObject::pcShapeMaterial, and MeshCore::MeshIO::PER_FACE.
highlightSelection()
void ViewProviderMesh::highlightSelection () protected virtual
Definition at line 2270 of file Mod/Mesh/Gui/ViewProvider.cpp.
References SCL.SimpleDataTypes::c, Mesh::MeshObject::countFacets(), App::PropertyMaterialList::getDiffuseColor(), Mesh::MeshObject::getFacetsFromSelection(), getMeshObject(), SplineSurface::i, pcMatBinding, Gui::ViewProviderGeometryObject::pcShapeMaterial, MeshCore::MeshIO::PER_FACE, Path.Dressup.Utils::selection(), and Gui::ViewProviderGeometryObject::ShapeAppearance.
Referenced by addSelection(), deselectComponent(), deselectFacet(), removeSelection(), selectArea(), selectComponent(), selectFacet(), setSelection(), MeshGui::ViewProviderMeshFaceSet::updateData(), and MeshGui::ViewProviderIndexedFaceSet::updateData().
invertSelection()
void ViewProviderMesh::invertSelection ()
Definition at line 2206 of file Mod/Mesh/Gui/ViewProvider.cpp.
References SCL.SimpleDataTypes::f, MeshCore::MeshKernel::GetFacets(), Mesh::MeshObject::getKernel(), getMeshObject(), MeshCore::MeshFacet::SELECTED, and setSelection().
isFacetSelected()
bool ViewProviderMesh::isFacetSelected (Mesh::FacetIndex facet)
Definition at line 2124 of file Mod/Mesh/Gui/ViewProvider.cpp.
References MeshCore::MeshKernel::GetFacets(), Mesh::MeshObject::getKernel(), getMeshObject(), and MeshCore::MeshFacet::SELECTED.
markPartCallback()
void ViewProviderMesh::markPartCallback (void * ud, SoEventCallback * cb) static
Definition at line 1807 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Gui::Application::activeDocument(), clearSelection(), Gui::Document::commitCommand(), Base::Console(), deleteSelection(), Base::Persistence::getClassTypeId(), Gui::Application::Instance, NavigationIndicatorGui::menu, Base::ConsoleSingleton::Message(), Gui::Document::openCommand(), RobotExample::pos, and Arch::QT_TRANSLATE_NOOP.
onChanged()
void ViewProviderMesh::onChanged (const App::Property * prop) override protected virtual
get called by the container whenever a property has been changed
Reimplemented from Gui::ViewProviderGeometryObject.
Definition at line 325 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Gui::SoFCSelection::BOX, SCL.SimpleDataTypes::c, Coloring, CreaseAngle, Gui::SoFCSelection::EMISSIVE, App::PropertyMaterialList::getDiffuseColor(), App::PropertyInteger::getValue(), App::PropertyEnumeration::getValue(), App::PropertyFloat::getValue(), App::PropertyBool::getValue(), App::PropertyColor::getValue(), Lighting, LineColor, LineTransparency, LineWidth, OpenEdges, MeshCore::MeshIO::OVERALL, pcHighlight, pcLineStyle, pcMatBinding, pcPointStyle, pLineColor, PointSize, pShapeHints, Gui::ViewProviderDocumentObject::SelectionStyle, setOpenEdgeColorFrom(), Gui::ViewProviderGeometryObject::ShapeAppearance, showOpenEdges(), Gui::SoFCSelection::style, and tryColorPerVertexOrFace().
partMeshCallback()
void ViewProviderMesh::partMeshCallback (void * ud, SoEventCallback * cb) static
Definition at line 1131 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Gui::Application::activeDocument(), SCL.SimpleDataTypes::b, Gui::Document::commitCommand(), Base::Console(), createToolMesh(), Gui::ViewProvider::finishEditing(), Base::Persistence::getClassTypeId(), Gui::Inner, Gui::Application::Instance, Base::Placement::invert(), Base::ConsoleSingleton::Message(), Gui::Document::openCommand(), Arch::QT_TRANSLATE_NOOP, Base::Sequencer(), Gui::View3DInventorViewer::setEditing(), Base::SequencerBase::setLocked(), Base::Placement::toMatrix(), and MeshCore::MeshKernel::Transform().
removeFacets()
void ViewProviderMesh::removeFacets (const std::vector< Mesh::FacetIndex > & facets) virtual
Definition at line 2018 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Coloring, importers.importIFCmulticore::colors, Mesh::MeshObject::countFacets(), Mesh::MeshObject::countPoints(), Mesh::MeshObject::deleteFacets(), Mesh::PropertyMeshKernel::finishEditing(), getColorProperty(), getMeshProperty(), Mesh::MeshObject::getPointDegree(), App::PropertyListsT< T, ListT, ParentT >::getSize(), App::PropertyBool::getValue(), App::PropertyListsT< T, ListT, ParentT >::getValues(), Gui::ViewProviderDocumentObject::pcObject, App::DocumentObject::purgeTouched(), App::PropertyBool::setValue(), App::PropertyListsT< T, ListT, ParentT >::setValues(), and Mesh::PropertyMeshKernel::startEditing().
Referenced by cutMesh(), deleteSelection(), and splitMesh().
removeSelection()
void ViewProviderMesh::removeSelection (const std::vector< Mesh::FacetIndex > & indices)
Definition at line 2192 of file Mod/Mesh/Gui/ViewProvider.cpp.
References getMeshObject(), Mesh::MeshObject::hasSelectedFacets(), highlightSelection(), Mesh::MeshObject::removeFacetsFromSelection(), and unhighlightSelection().
resetFacetTransparency()
void ViewProviderMesh::resetFacetTransparency ()
Definition at line 2004 of file Mod/Mesh/Gui/ViewProvider.cpp.
References SCL.SimpleDataTypes::c, App::PropertyMaterialList::getDiffuseColor(), MeshCore::MeshIO::OVERALL, pcMatBinding, Gui::ViewProviderGeometryObject::pcShapeMaterial, and Gui::ViewProviderGeometryObject::ShapeAppearance.
segmentMesh()
void ViewProviderMesh::segmentMesh (const MeshCore::MeshKernel & toolMesh, const Base::Vector3f & normal, SbBool inner) protected virtual
Definition at line 1639 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Mesh::MeshObject::addSegment(), MeshCore::MeshKernel::CountFacets(), Mesh::PropertyMeshKernel::finishEditing(), Path.Base.Generator.dogboneII::generate(), MeshCore::MeshAlgorithm::GetFacetsFromToolMesh(), Mesh::MeshObject::getKernel(), getMeshProperty(), Gui::ViewProviderDocumentObject::getObject(), Mesh::PropertyMeshKernel::getValue(), App::DocumentObject::purgeTouched(), and Mesh::PropertyMeshKernel::startEditing().
segmMeshCallback()
void ViewProviderMesh::segmMeshCallback (void * ud, SoEventCallback * cb) static
Definition at line 1204 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Gui::Application::activeDocument(), SCL.SimpleDataTypes::b, Gui::Document::commitCommand(), Base::Console(), createToolMesh(), Gui::ViewProvider::finishEditing(), Base::Persistence::getClassTypeId(), Gui::Inner, Gui::Application::Instance, Base::Placement::invert(), Base::ConsoleSingleton::Message(), Gui::Document::openCommand(), Arch::QT_TRANSLATE_NOOP, Base::Sequencer(), Gui::View3DInventorViewer::setEditing(), Base::SequencerBase::setLocked(), Base::Placement::toMatrix(), and MeshCore::MeshKernel::Transform().
selectArea()
void ViewProviderMesh::selectArea (short x, short y, short w, short h, const SbViewportRegion & region, SoCamera * camera) protected virtual
Definition at line 2252 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Mesh::MeshObject::addFacetsToSelection(), getFacetsOfRegion(), getMeshObject(), highlightSelection(), src.Mod.PartDesign.fcgear.svggear::w, MovieTool::x, and MovieTool::y.
selectComponent()
void ViewProviderMesh::selectComponent (Mesh::FacetIndex facet)
Definition at line 2131 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Mesh::MeshObject::addFacetsToSelection(), Mesh::MeshObject::getKernel(), getMeshObject(), highlightSelection(), MeshCore::MeshAlgorithm::ResetFacetFlag(), Path.Dressup.Utils::selection(), MeshCore::MeshFacet::VISIT, and MeshCore::MeshKernel::VisitNeighbourFacets().
selectFacet()
void ViewProviderMesh::selectFacet (Mesh::FacetIndex facet)
Definition at line 2078 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Mesh::MeshObject::addFacetsToSelection(), Mesh::MeshObject::countFacets(), getMeshObject(), highlightSelection(), pcMatBinding, Gui::ViewProviderGeometryObject::pcShapeMaterial, MeshCore::MeshIO::PER_FACE, and Path.Dressup.Utils::selection().
selectGLCallback()
void ViewProviderMesh::selectGLCallback (void * ud, SoEventCallback * cb) static
Definition at line 1277 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Gui::ViewProvider::finishEditing(), Base::Persistence::getClassTypeId(), RobotExample::pos, Gui::View3DInventorViewer::setEditing(), src.Mod.PartDesign.fcgear.svggear::w, MovieTool::x, and MovieTool::y.
setAmbientColor()
void ViewProviderMesh::setAmbientColor (const std::vector< App::Color > & val) protected
Definition at line 622 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Gui::ViewProviderGeometryObject::pcShapeMaterial, setColorField(), and toolbit-attributes::val.
Referenced by tryColorPerVertexOrFace().
setColorField()
void ViewProviderMesh::setColorField (const std::vector< App::Color > & val, SoMFColor & field) protected
Definition at line 609 of file Mod/Mesh/Gui/ViewProvider.cpp.
References SplineSurface::i, and toolbit-attributes::val.
Referenced by setAmbientColor(), setDiffuseColor(), setEmissiveColor(), and setSpecularColor().
setColorPerFace()
void ViewProviderMesh::setColorPerFace (const App::PropertyColorList * prop) protected
Definition at line 603 of file Mod/Mesh/Gui/ViewProvider.cpp.
References App::PropertyListsT< T, ListT, ParentT >::getValues(), pcMatBinding, MeshCore::MeshIO::PER_FACE, and setDiffuseColor().
Referenced by highlightColors(), and tryColorPerVertexOrFace().
setColorPerVertex()
void ViewProviderMesh::setColorPerVertex (const App::PropertyColorList * prop) protected
Definition at line 597 of file Mod/Mesh/Gui/ViewProvider.cpp.
References App::PropertyListsT< T, ListT, ParentT >::getValues(), pcMatBinding, and setDiffuseColor().
Referenced by highlightColors(), and tryColorPerVertexOrFace().
setDiffuseColor()
void ViewProviderMesh::setDiffuseColor (const std::vector< App::Color > & val) protected
Definition at line 627 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Gui::ViewProviderGeometryObject::pcShapeMaterial, setColorField(), and toolbit-attributes::val.
Referenced by setColorPerFace(), setColorPerVertex(), and tryColorPerVertexOrFace().
setDisplayMode()
void ViewProviderMesh::setDisplayMode (const char * ModeName) override virtual
Sets the correct display mode.
Reimplemented from Gui::ViewProvider.
Reimplemented in MeshGui::ViewProviderMeshTransformDemolding, and MeshGui::ViewProviderMeshTransform.
Definition at line 659 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Gui::ViewProvider::setDisplayMaskMode().
Referenced by MeshGui::ViewProviderMeshTransform::setDisplayMode(), and MeshGui::ViewProviderMeshTransformDemolding::setDisplayMode().
setEdit()
bool ViewProviderMesh::setEdit (int ModNum) override protected virtual
Sets the edit mode.
Reimplemented from Gui::ViewProviderDragger.
Definition at line 820 of file Mod/Mesh/Gui/ViewProvider.cpp.
References highlightComponents(), and PartDesignGui::setEdit().
setEmissiveColor()
void ViewProviderMesh::setEmissiveColor (const std::vector< App::Color > & val) protected
Definition at line 637 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Gui::ViewProviderGeometryObject::pcShapeMaterial, setColorField(), and toolbit-attributes::val.
Referenced by tryColorPerVertexOrFace().
setFacetTransparency()
void ViewProviderMesh::setFacetTransparency (const std::vector< float > & facetTransparency)
The size of the array must be equal to the number of facets.
Definition at line 1982 of file Mod/Mesh/Gui/ViewProvider.cpp.
References SCL.SimpleDataTypes::c, App::PropertyMaterialList::getDiffuseColor(), pcMatBinding, Gui::ViewProviderGeometryObject::pcShapeMaterial, MeshCore::MeshIO::PER_FACE, and Gui::ViewProviderGeometryObject::ShapeAppearance.
Referenced by tryColorPerVertexOrFace().
setHighlightedColors()
void ViewProviderMesh::setHighlightedColors (bool on) protected
Definition at line 2407 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Color, highlightColors(), highlightMode, None, and unhighlightSelection().
Referenced by setupContextMenu().
setHighlightedComponents()
void ViewProviderMesh::setHighlightedComponents (bool on) protected
Definition at line 2305 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Component, highlightComponents(), highlightMode, None, and unhighlightSelection().
Referenced by setupContextMenu().
setHighlightedSegments()
void ViewProviderMesh::setHighlightedSegments (bool on) protected
Definition at line 2347 of file Mod/Mesh/Gui/ViewProvider.cpp.
References highlightMode, highlightSegments(), None, Segment, and unhighlightSelection().
Referenced by setupContextMenu().
setOpenEdgeColorFrom()
void ViewProviderMesh::setOpenEdgeColorFrom (const App::Color & col) protected
Definition at line 376 of file Mod/Mesh/Gui/ViewProvider.cpp.
References SCL.SimpleDataTypes::b, SCL.SimpleDataTypes::c, toolbit-attributes::g, and pOpenColor.
Referenced by onChanged().
setSelection()
void ViewProviderMesh::setSelection (const std::vector< Mesh::FacetIndex > & indices)
Definition at line 2168 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Mesh::MeshObject::addFacetsToSelection(), Mesh::MeshObject::clearFacetSelection(), getMeshObject(), highlightSelection(), and unhighlightSelection().
Referenced by invertSelection().
setSpecularColor()
void ViewProviderMesh::setSpecularColor (const std::vector< App::Color > & val) protected
Definition at line 632 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Gui::ViewProviderGeometryObject::pcShapeMaterial, setColorField(), and toolbit-attributes::val.
Referenced by tryColorPerVertexOrFace().
setupContextMenu()
void ViewProviderMesh::setupContextMenu (QMenu * menu, QObject * receiver, const char * method) override virtual
set up the context-menu with the supported edit modes
Reimplemented from Gui::ViewProviderDragger.
Definition at line 789 of file Mod/Mesh/Gui/ViewProvider.cpp.
References canHighlightColors(), Color, Component, highlightMode, NavigationIndicatorGui::menu, pcMatBinding, MeshCore::MeshIO::PER_FACE, Segment, setHighlightedColors(), setHighlightedComponents(), and setHighlightedSegments().
showOpenEdges()
void ViewProviderMesh::showOpenEdges (bool show) protected virtual
Reimplemented in MeshGui::ViewProviderMeshObject, MeshGui::ViewProviderIndexedFaceSet, and MeshGui::ViewProviderMeshFaceSet.
Definition at line 936 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Gui::ViewProviderDocumentObject::show().
Referenced by onChanged().
splitMesh()
void ViewProviderMesh::splitMesh (const MeshCore::MeshKernel & toolMesh, const Base::Vector3f & normal, SbBool inner) protected virtual
Definition at line 1604 of file Mod/Mesh/Gui/ViewProvider.cpp.
References MeshCore::MeshKernel::CountFacets(), toolbit-attributes::doc, Path.Base.Generator.dogboneII::generate(), App::Application::getActiveDocument(), App::GetApplication(), MeshCore::MeshAlgorithm::GetFacetsFromToolMesh(), Mesh::MeshObject::getKernel(), getMeshProperty(), App::DocumentObject::getNameInDocument(), Gui::ViewProviderDocumentObject::getObject(), Mesh::PropertyMeshKernel::getValue(), Mesh::MeshObject::meshFromSegment(), Gui::ViewProviderDocumentObject::pcObject, App::DocumentObject::purgeTouched(), and removeFacets().
trimMesh()
void ViewProviderMesh::trimMesh (const std::vector< SbVec2f > & polygon, const Base::ViewProjMethod & proj, SbBool inner) virtual
Definition at line 1586 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Base::Polygon2d::Add(), Mesh::PropertyMeshKernel::finishEditing(), getMeshProperty(), Gui::ViewProviderDocumentObject::getObject(), Mesh::MeshObject::INNER, Mesh2Shape::mesh, Mesh::MeshObject::OUTER, App::DocumentObject::purgeTouched(), Mesh::PropertyMeshKernel::startEditing(), and Path.Post.scripts.grbl_post::type.
Referenced by MeshGui::MeshSplit::trimMesh().
trimMeshCallback()
void ViewProviderMesh::trimMeshCallback (void * ud, SoEventCallback * cb) static
Definition at line 1062 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Gui::Document::abortCommand(), Gui::Application::activeDocument(), Gui::Document::commitCommand(), Gui::ViewProvider::finishEditing(), Base::Persistence::getClassTypeId(), App::PropertyPlacement::getValue(), Gui::Inner, Gui::Application::Instance, Gui::Document::openCommand(), Gui::Outer, App::GeoFeature::Placement, Arch::QT_TRANSLATE_NOOP, Gui::View3DInventorViewer::setEditing(), Base::ViewProjMethod::setTransform(), Gui::Split, and Base::Placement::toMatrix().
tryColorPerVertexOrFace()
void ViewProviderMesh::tryColorPerVertexOrFace (bool on) protected
Definition at line 531 of file Mod/Mesh/Gui/ViewProvider.cpp.
References draftgeoutils.faces::bind(), SCL.SimpleDataTypes::c, importers.importIFCmulticore::colors, getColorProperty(), App::PropertyMaterialList::getDiffuseColor(), getMaterialProperty(), getMeshObject(), App::PropertyInteger::getValue(), Mesh2Shape::mesh, MeshCore::MeshIO::OVERALL, pcMatBinding, Gui::ViewProviderGeometryObject::pcShapeMaterial, MeshCore::MeshIO::PER_FACE, MeshCore::MeshIO::PER_VERTEX, setAmbientColor(), setColorPerFace(), setColorPerVertex(), setDiffuseColor(), setEmissiveColor(), setFacetTransparency(), setSpecularColor(), Gui::ViewProviderGeometryObject::ShapeAppearance, and Gui::ViewProviderGeometryObject::Transparency.
Referenced by onChanged().
unhighlightSelection()
void ViewProviderMesh::unhighlightSelection () protected virtual
Definition at line 2297 of file Mod/Mesh/Gui/ViewProvider.cpp.
References SCL.SimpleDataTypes::c, App::PropertyMaterialList::getDiffuseColor(), MeshCore::MeshIO::OVERALL, pcMatBinding, Gui::ViewProviderGeometryObject::pcShapeMaterial, and Gui::ViewProviderGeometryObject::ShapeAppearance.
Referenced by clearSelection(), deleteSelection(), deselectComponent(), deselectFacet(), removeSelection(), setHighlightedColors(), setHighlightedComponents(), setHighlightedSegments(), setSelection(), unsetEdit(), and MeshGui::ViewProviderMeshFaceSet::updateData().
unsetEdit()
void ViewProviderMesh::unsetEdit (int ModNum) override protected virtual
Unsets the edit mode.
Reimplemented from Gui::ViewProviderDragger.
Definition at line 831 of file Mod/Mesh/Gui/ViewProvider.cpp.
References unhighlightSelection().
updateData()
void ViewProviderMesh::updateData (const App::Property * prop) override virtual
Reimplemented from Gui::ViewProviderGeometryObject.
Reimplemented in MeshGui::ViewProviderMeshObject, MeshGui::ViewProviderIndexedFaceSet, MeshGui::ViewProviderMeshFaceSet, and MeshGui::ViewProviderMeshTransform.
Definition at line 489 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Coloring, App::Property::Hidden, Base::BaseClass::is(), App::Property::setStatus(), and Gui::ViewProviderGeometryObject::updateData().
Referenced by MeshGui::ViewProviderMeshTransform::updateData(), MeshGui::ViewProviderMeshFaceSet::updateData(), MeshGui::ViewProviderIndexedFaceSet::updateData(), and MeshGui::ViewProviderMeshObject::updateData().
useNewSelectionModel()
bool MeshGui::ViewProviderMesh::useNewSelectionModel () const inline override virtual
indicates if the ViewProvider use the new Selection model
Reimplemented from Gui::ViewProvider.
Definition at line 147 of file Mod/Mesh/Gui/ViewProvider.h.
Member Data Documentation
Coloring
App::PropertyBool MeshGui::ViewProviderMesh::Coloring
Definition at line 140 of file Mod/Mesh/Gui/ViewProvider.h.
Referenced by attach(), finishRestoring(), onChanged(), removeFacets(), and updateData().
CreaseAngle
App::PropertyFloatConstraint MeshGui::ViewProviderMesh::CreaseAngle
Definition at line 138 of file Mod/Mesh/Gui/ViewProvider.h.
Referenced by onChanged().
highlightMode
HighlighMode MeshGui::ViewProviderMesh::highlightMode protected
Definition at line 282 of file Mod/Mesh/Gui/ViewProvider.h.
Referenced by setHighlightedColors(), setHighlightedComponents(), setHighlightedSegments(), and setupContextMenu().
Lighting
App::PropertyEnumeration MeshGui::ViewProviderMesh::Lighting
Definition at line 141 of file Mod/Mesh/Gui/ViewProvider.h.
Referenced by onChanged().
LineColor
App::PropertyColor MeshGui::ViewProviderMesh::LineColor
Definition at line 142 of file Mod/Mesh/Gui/ViewProvider.h.
Referenced by onChanged().
LineTransparency
App::PropertyPercent MeshGui::ViewProviderMesh::LineTransparency
Definition at line 135 of file Mod/Mesh/Gui/ViewProvider.h.
Referenced by onChanged().
LineWidth
App::PropertyFloatConstraint MeshGui::ViewProviderMesh::LineWidth
Definition at line 136 of file Mod/Mesh/Gui/ViewProvider.h.
Referenced by onChanged().
OpenEdges
App::PropertyBool MeshGui::ViewProviderMesh::OpenEdges
Definition at line 139 of file Mod/Mesh/Gui/ViewProvider.h.
Referenced by onChanged(), MeshGui::ViewProviderMeshFaceSet::updateData(), and MeshGui::ViewProviderIndexedFaceSet::updateData().
pcHighlight
Gui::SoFCSelection* MeshGui::ViewProviderMesh::pcHighlight {nullptr} protected
Definition at line 283 of file Mod/Mesh/Gui/ViewProvider.h.
Referenced by MeshGui::ViewProviderMeshTransform::attach(), MeshGui::ViewProviderMeshTransformDemolding::attach(), attach(), MeshGui::ViewProviderIndexedFaceSet::attach(), MeshGui::ViewProviderMeshObject::attach(), onChanged(), and ~ViewProviderMesh().
pcLineStyle
SoDrawStyle* MeshGui::ViewProviderMesh::pcLineStyle {nullptr} protected
Definition at line 285 of file Mod/Mesh/Gui/ViewProvider.h.
Referenced by attach(), onChanged(), MeshGui::ViewProviderMeshFaceSet::showOpenEdges(), MeshGui::ViewProviderIndexedFaceSet::showOpenEdges(), MeshGui::ViewProviderMeshObject::showOpenEdges(), and ~ViewProviderMesh().
pcMatBinding
SoMaterialBinding* MeshGui::ViewProviderMesh::pcMatBinding {nullptr} protected
Definition at line 291 of file Mod/Mesh/Gui/ViewProvider.h.
Referenced by MeshGui::ViewProviderMeshTransformDemolding::attach(), attach(), deselectFacet(), highlightComponents(), highlightSegments(), highlightSelection(), onChanged(), resetFacetTransparency(), selectFacet(), setColorPerFace(), setColorPerVertex(), setFacetTransparency(), setupContextMenu(), tryColorPerVertexOrFace(), unhighlightSelection(), and ~ViewProviderMesh().
pcOpenEdge
SoSeparator* MeshGui::ViewProviderMesh::pcOpenEdge {nullptr} protected
Definition at line 287 of file Mod/Mesh/Gui/ViewProvider.h.
Referenced by MeshGui::ViewProviderMeshFaceSet::showOpenEdges(), MeshGui::ViewProviderIndexedFaceSet::showOpenEdges(), and MeshGui::ViewProviderMeshObject::showOpenEdges().
pcPointStyle
SoDrawStyle* MeshGui::ViewProviderMesh::pcPointStyle {nullptr} protected
Definition at line 286 of file Mod/Mesh/Gui/ViewProvider.h.
Referenced by attach(), onChanged(), and ~ViewProviderMesh().
pcShapeGroup
SoGroup* MeshGui::ViewProviderMesh::pcShapeGroup {nullptr} protected
Definition at line 284 of file Mod/Mesh/Gui/ViewProvider.h.
Referenced by MeshGui::ViewProviderMeshFaceSet::attach(), attach(), MeshGui::ViewProviderMeshFaceSet::updateData(), and ~ViewProviderMesh().
pLineColor
SoMaterial* MeshGui::ViewProviderMesh::pLineColor {nullptr} protected
Definition at line 289 of file Mod/Mesh/Gui/ViewProvider.h.
Referenced by attach(), onChanged(), and ~ViewProviderMesh().
PointSize
App::PropertyFloatConstraint MeshGui::ViewProviderMesh::PointSize
Definition at line 137 of file Mod/Mesh/Gui/ViewProvider.h.
Referenced by onChanged().
pOpenColor
SoBaseColor* MeshGui::ViewProviderMesh::pOpenColor {nullptr} protected
Definition at line 288 of file Mod/Mesh/Gui/ViewProvider.h.
Referenced by setOpenEdgeColorFrom(), MeshGui::ViewProviderMeshFaceSet::showOpenEdges(), MeshGui::ViewProviderIndexedFaceSet::showOpenEdges(), MeshGui::ViewProviderMeshObject::showOpenEdges(), and ~ViewProviderMesh().
pShapeHints
SoShapeHints* MeshGui::ViewProviderMesh::pShapeHints {nullptr} protected
Definition at line 290 of file Mod/Mesh/Gui/ViewProvider.h.
Referenced by attach(), onChanged(), and ~ViewProviderMesh().
The documentation for this class was generated from the following files:
Mod/Mesh/Gui/ViewProvider.h
Mod/Mesh/Gui/ViewProvider.cpp