FreeCAD: TechDrawGui::DlgPrefsTechDrawDimensionsImp Class Reference
TechDrawGui::DlgPrefsTechDrawDimensionsImp Class Reference
#include <DlgPrefsTechDrawDimensionsImp.h>
Public Member Functions
DlgPrefsTechDrawDimensionsImp (QWidget *parent=nullptr)
~DlgPrefsTechDrawDimensionsImp () override
void resetSettingsToDefaults () override
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Protected Member Functions
void saveSettings () override
void loadSettings () override
void changeEvent (QEvent *e) override
void dimensioningModeChanged (int index)
int prefArrowStyle () const
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
Detailed Description
Definition at line 57 of file DlgPrefsTechDrawDimensionsImp.h.
Constructor & Destructor Documentation
DlgPrefsTechDrawDimensionsImp()
DlgPrefsTechDrawDimensionsImp::DlgPrefsTechDrawDimensionsImp (QWidget * parent = nullptr) explicit
Definition at line 39 of file DlgPrefsTechDrawDimensionsImp.cpp.
References Base::Unit::Length.
~DlgPrefsTechDrawDimensionsImp()
DlgPrefsTechDrawDimensionsImp::~DlgPrefsTechDrawDimensionsImp () override
Definition at line 50 of file DlgPrefsTechDrawDimensionsImp.cpp.
Member Function Documentation
changeEvent()
void DlgPrefsTechDrawDimensionsImp::changeEvent (QEvent * e) override protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
Definition at line 200 of file DlgPrefsTechDrawDimensionsImp.cpp.
References SCL.SimpleDataTypes::e.
dimensioningModeChanged()
void DlgPrefsTechDrawDimensionsImp::dimensioningModeChanged (int index) protected
Definition at line 192 of file DlgPrefsTechDrawDimensionsImp.cpp.
Referenced by loadSettings().
loadSettings()
void DlgPrefsTechDrawDimensionsImp::loadSettings () override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 127 of file DlgPrefsTechDrawDimensionsImp.cpp.
References draftgeoutils.intersections::connect(), dimensioningModeChanged(), App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), TechDrawGui::DrawGuiUtil::loadArrowBox(), prefArrowStyle(), and Path.Base.Util::setProperty().
prefArrowStyle()
int DlgPrefsTechDrawDimensionsImp::prefArrowStyle () const protected
Definition at line 228 of file DlgPrefsTechDrawDimensionsImp.cpp.
References TechDrawGui::PreferencesGui::dimArrowStyle().
Referenced by loadSettings().
resetSettingsToDefaults()
void DlgPrefsTechDrawDimensionsImp::resetSettingsToDefaults () override virtual
Reimplemented from Gui::Dialog::PreferencePage.
Definition at line 210 of file DlgPrefsTechDrawDimensionsImp.cpp.
References App::GetApplication(), App::Application::GetParameterGroupByPath(), and ParameterGrp::RemoveBool().
saveSettings()
void DlgPrefsTechDrawDimensionsImp::saveSettings () override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 55 of file DlgPrefsTechDrawDimensionsImp.cpp.
References App::GetApplication(), App::Application::GetParameterGroupByPath(), Gui::Dialog::PreferencePage::requireRestart(), and ParameterGrp::SetBool().
The documentation for this class was generated from the following files:
DlgPrefsTechDrawDimensionsImp.h
DlgPrefsTechDrawDimensionsImp.cpp