FreeCAD: Gui::NavigationAnimator Class Reference
Gui::NavigationAnimator Class Reference
#include <NavigationAnimator.h>
Public Member Functions
NavigationAnimator ()
~NavigationAnimator ()
void start (const std::shared_ptr< NavigationAnimation > &animation)
Start an animation.
bool startAndWait (const std::shared_ptr< NavigationAnimation > &animation)
Start an animation and wait for it to finish.
void stop ()
Stops an active animation and releases shared ownership of the animation.
bool isAnimating () const
Detailed Description
Definition at line 56 of file NavigationAnimator.h.
Constructor & Destructor Documentation
NavigationAnimator()
NavigationAnimator::NavigationAnimator ()
Definition at line 31 of file NavigationAnimator.cpp.
~NavigationAnimator()
NavigationAnimator::~NavigationAnimator ()
Definition at line 35 of file NavigationAnimator.cpp.
References stop().
Member Function Documentation
isAnimating()
bool NavigationAnimator::isAnimating () const
Returns
Whether or not an animation is active
Definition at line 97 of file NavigationAnimator.cpp.
Referenced by Gui::NavigationStyle::isAnimating().
start()
void NavigationAnimator::start (const std::shared_ptr< NavigationAnimation > & animation)
Start an animation.
Parameters
animation The animation to start
Definition at line 45 of file NavigationAnimator.cpp.
References draftgeoutils.intersections::connect(), and stop().
Referenced by startAndWait(), and Gui::NavigationStyle::startAnimating().
startAndWait()
bool NavigationAnimator::startAndWait (const std::shared_ptr< NavigationAnimation > & animation)
Start an animation and wait for it to finish.
Parameters
animation The animation to start
Returns
True if the animation finished, false if interrupted
Definition at line 65 of file NavigationAnimator.cpp.
References draftgeoutils.intersections::connect(), Gui::NavigationAnimation::interrupted(), start(), and stop().
Referenced by Gui::NavigationStyle::startAnimating().
stop()
void NavigationAnimator::stop ()
Stops an active animation and releases shared ownership of the animation.
Definition at line 83 of file NavigationAnimator.cpp.
Referenced by bimcommands.BimPanel.NestTaskPanel::accept(), bimcommands.BimPanel.NestTaskPanel::reject(), Gui::NavigationStyle::setAnimationEnabled(), Gui::NavigationStyle::setCameraOrientation(), Gui::NavigationStyle::setSpinningAnimationEnabled(), Gui::NavigationStyle::setViewingMode(), start(), startAndWait(), Gui::NavigationStyle::stopAnimating(), Gui::NavigationStyle::translateCamera(), Gui::NavigationStyle::zoom(), and ~NavigationAnimator().
The documentation for this class was generated from the following files:
NavigationAnimator.h
NavigationAnimator.cpp