FreeCAD: PartGui::PrismPrimitive Class Reference
PartGui::PrismPrimitive Class Reference
#include <DlgPrimitives.h>
Public Member Functions
PrismPrimitive (std::shared_ptr< Ui_DlgPrimitives > ui, Part::Prism *feature=nullptr)
const char * getDefaultName () const override
QString create (const QString &objectName, const QString &placement) const override
QString change (const QString &objectName, const QString &placement) const override
void changeValue (QObject *) override
Public Member Functions inherited from PartGui::AbstractPrimitive
AbstractPrimitive (Part::Primitive *feature=nullptr)
~AbstractPrimitive () override=default
bool hasValidPrimitive () const
Additional Inherited Members
Protected Member Functions inherited from PartGui::AbstractPrimitive
void connectSignalMapper (QSignalMapper *mapper)
Protected Attributes inherited from PartGui::AbstractPrimitive
App::DocumentObjectWeakPtrT featurePtr
Detailed Description
Definition at line 226 of file DlgPrimitives.h.
Constructor & Destructor Documentation
PrismPrimitive()
PrismPrimitive::PrismPrimitive (std::shared_ptr< Ui_DlgPrimitives > ui, Part::Prism * feature = nullptr)
Definition at line 889 of file DlgPrimitives.cpp.
References Part::Prism::Circumradius, PartGui::connectMapSignalMapper(), PartGui::AbstractPrimitive::connectSignalMapper(), Part::PrismExtension::FirstAngle, App::PropertyQuantity::getQuantityValue(), App::PropertyInteger::getValue(), Part::Prism::Height, Part::Prism::Polygon, Part::PrismExtension::SecondAngle, and Gui::QuantitySpinBox::valueChanged().
Member Function Documentation
change()
QString PrismPrimitive::change (const QString & objectName, const QString & placement) const override virtual
Implements PartGui::AbstractPrimitive.
Definition at line 943 of file DlgPrimitives.cpp.
References PartGui::safeQuantityQString().
changeValue()
void PrismPrimitive::changeValue (QObject * widget) override virtual
Implements PartGui::AbstractPrimitive.
Definition at line 961 of file DlgPrimitives.cpp.
References Part::Prism::Circumradius, App::DocumentObjectWeakPtrT::expired(), PartGui::AbstractPrimitive::featurePtr, Part::PrismExtension::FirstAngle, App::DocumentObjectWeakPtrT::get(), Part::Prism::Height, Part::Prism::Polygon, App::DocumentObject::recomputeFeature(), Part::PrismExtension::SecondAngle, App::PropertyInteger::setValue(), and App::PropertyQuantity::setValue().
create()
QString PrismPrimitive::create (const QString & objectName, const QString & placement) const override virtual
Implements PartGui::AbstractPrimitive.
Definition at line 922 of file DlgPrimitives.cpp.
References PartGui::safeQuantityQString().
getDefaultName()
const char * PrismPrimitive::getDefaultName () const override virtual
Implements PartGui::AbstractPrimitive.
Definition at line 917 of file DlgPrimitives.cpp.
The documentation for this class was generated from the following files:
DlgPrimitives.h
DlgPrimitives.cpp