FreeCAD: MeshCore::MeshEvalSolid Class Reference
MeshCore::MeshEvalSolid Class Reference
#include <Evaluation.h>
Public Member Functions
MeshEvalSolid (const MeshKernel &rclM)
bool Evaluate () override
Public Member Functions inherited from MeshCore::MeshEvaluation
MeshEvaluation (const MeshKernel &rclB)
virtual ~MeshEvaluation ()=default
MeshEvaluation (const MeshEvaluation &)=delete
MeshEvaluation (MeshEvaluation &&)=delete
MeshEvaluation & operator= (const MeshEvaluation &)=delete
MeshEvaluation & operator= (MeshEvaluation &&)=delete
Additional Inherited Members
Protected Attributes inherited from MeshCore::MeshEvaluation
const MeshKernel & _rclMesh
Detailed Description
The MeshEvalSolid class checks if the mesh represents a solid.
Author
Werner Mayer
Definition at line 207 of file Evaluation.h.
Constructor & Destructor Documentation
MeshEvalSolid()
MeshEvalSolid::MeshEvalSolid (const MeshKernel & rclM) explicit
Definition at line 286 of file Evaluation.cpp.
Member Function Documentation
Evaluate()
bool MeshEvalSolid::Evaluate () override virtual
Evaluates the mesh kernel with respect to certain criteria. Must be reimplemented by every subclass. This pure virtual function returns false if the mesh kernel is invalid according to this criterion and true if the mesh kernel is correct.
Implements MeshCore::MeshEvaluation.
Definition at line 290 of file Evaluation.cpp.
References MeshCore::MeshEvaluation::_rclMesh, and MeshCore::MeshKernel::GetEdges().
Referenced by MeshCore::MeshKernel::HasOpenEdges(), and Mesh::MeshObject::isSolid().
The documentation for this class was generated from the following files:
Evaluation.h
Evaluation.cpp