FreeCAD: TechDrawGui::QGIVertex Class Reference
TechDrawGui::QGIVertex Class Reference
#include <QGIVertex.h>
Public Types
enum { Type = QGraphicsItem::UserType + 105 }
Public Types inherited from TechDrawGui::QGIPrimPath
enum { Type = QGraphicsItem::UserType + 170 }
Public Member Functions
QGIVertex (int index)
~QGIVertex () override=default
int type () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
int getProjIndex () const
float getRadius ()
virtual void setRadius (float r)
Public Member Functions inherited from TechDrawGui::QGIPrimPath
QGIPrimPath ()
~QGIPrimPath () override=default
int type () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
QPainterPath shape () const override
virtual void setPrettyNormal ()
virtual void setPrettyPre ()
virtual void setPrettySel ()
virtual void setWidth (double w)
virtual double getWidth ()
Qt::PenStyle getStyle ()
void setStyle (Qt::PenStyle s)
void setStyle (int s)
virtual void setNormalColor (QColor c)
virtual void setCapStyle (Qt::PenCapStyle c)
void setFillStyle (Qt::BrushStyle f)
Qt::BrushStyle getFillStyle ()
void setFill (QColor c, Qt::BrushStyle s)
void setFill (QBrush b)
void resetFill ()
void setFillColor (QColor c)
QColor getFillColor ()
void setFillOverride (bool b)
virtual void setCurrentPen ()
Protected Member Functions
bool multiselectEligible () override
Protected Member Functions inherited from TechDrawGui::QGIPrimPath
void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
virtual QColor getNormalColor ()
virtual QColor getPreColor ()
virtual QColor getSelectColor ()
Base::Reference< ParameterGrp > getParmGroup ()
virtual Qt::PenCapStyle prefCapStyle ()
Protected Attributes
int projIndex
float m_radius
Protected Attributes inherited from TechDrawGui::QGIPrimPath
bool isHighlighted
bool multiselectActivated
QPen m_pen
QColor m_colCurrent
QColor m_colNormal
bool m_colOverride
Qt::PenStyle m_styleCurrent
Qt::PenStyle m_styleNormal
double m_width
Qt::PenCapStyle m_capStyle
QBrush m_brush
Qt::BrushStyle m_fillStyleCurrent
QColor m_fillColorCurrent
QColor m_colDefFill
QColor m_colNormalFill
Qt::BrushStyle m_fillDef
Qt::BrushStyle m_fillNormal
Qt::BrushStyle m_fillSelect
bool m_fillOverride
Detailed Description
Definition at line 53 of file QGIVertex.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 79 of file QGIVertex.h.
Constructor & Destructor Documentation
QGIVertex()
QGIVertex::QGIVertex (int index) explicit
Definition at line 39 of file QGIVertex.cpp.
References m_radius, TechDrawGui::QGIPrimPath::setFill(), setRadius(), and TechDrawGui::PreferencesGui::vertexQColor().
~QGIVertex()
TechDrawGui::QGIVertex::~QGIVertex () override default
Member Function Documentation
getProjIndex()
int TechDrawGui::QGIVertex::getProjIndex () const inline
Definition at line 83 of file QGIVertex.h.
Referenced by TechDrawGui::QGMarker::mousePressEvent(), TechDrawGui::QGMarker::mouseReleaseEvent(), and TechDrawGui::MDIViewPage::preSelectionChanged().
getRadius()
float TechDrawGui::QGIVertex::getRadius () inline
Definition at line 85 of file QGIVertex.h.
multiselectEligible()
bool TechDrawGui::QGIVertex::multiselectEligible () inline override protected virtual
Reimplemented from TechDrawGui::QGIPrimPath.
Definition at line 89 of file QGIVertex.h.
paint()
void QGIVertex::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) override
Definition at line 57 of file QGIVertex.cpp.
References TechDrawGui::QGIPrimPath::paint().
Referenced by TechDrawGui::QGICMark::paint().
setRadius()
void QGIVertex::setRadius (float r) virtual
Reimplemented in TechDrawGui::QGMarker.
Definition at line 49 of file QGIVertex.cpp.
References m_radius, and buildPsets::p.
Referenced by TechDrawGui::QGIWeldSymbol::drawAllAround(), TechDrawGui::QGIViewPart::drawAllVertexes(), TechDrawGui::QGIView::makeMark(), TechDrawGui::QGIViewDimension::makeMarkC(), and QGIVertex().
type()
int TechDrawGui::QGIVertex::type () const inline override
Definition at line 80 of file QGIVertex.h.
Member Data Documentation
m_radius
float TechDrawGui::QGIVertex::m_radius protected
Definition at line 92 of file QGIVertex.h.
Referenced by QGIVertex(), TechDrawGui::QGMarker::setRadius(), and setRadius().
projIndex
int TechDrawGui::QGIVertex::projIndex protected
Definition at line 91 of file QGIVertex.h.
The documentation for this class was generated from the following files:
QGIVertex.h
QGIVertex.cpp