FreeCAD: PartGui::FaceAppearances Class Reference
PartGui::FaceAppearances Class Reference
#include <TaskFaceAppearances.h>
Classes
class Private
Public Member Functions
FaceAppearances (ViewProviderPartExt *vp, QWidget *parent=nullptr)
~FaceAppearances () override
void open ()
bool accept ()
bool reject ()
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Protected Member Functions
void onSelectionChanged (const Gui::SelectionChanges &msg) override
void changeEvent (QEvent *e) override
void slotUndoDocument (const Gui::Document &Doc)
void slotDeleteDocument (const Gui::Document &)
void slotDeleteObject (const Gui::ViewProvider &)
void updatePanel ()
int getFirstIndex () const
Detailed Description
Definition at line 42 of file TaskFaceAppearances.h.
Constructor & Destructor Documentation
FaceAppearances()
FaceAppearances::FaceAppearances (ViewProviderPartExt * vp, QWidget * parent = nullptr) explicit
Definition at line 241 of file TaskFaceAppearances.cpp.
References Gui::SelectionSingleton::addSelectionGate(), draftgeoutils.faces::bind(), PartGui::FaceAppearances::Private::connectDelDoc, PartGui::FaceAppearances::Private::connectDelObj, PartGui::FaceAppearances::Private::connectUndoDoc, PartGui::FaceAppearances::Private::doc, Gui::ViewProviderDocumentObject::getObject(), App::PropertyString::getValue(), Gui::Application::Instance, App::DocumentObject::Label, Init::parent, Gui::Selection(), Gui::Application::signalDeletedObject, Gui::Application::signalDeleteDocument, Gui::Document::signalUndoDocument, slotDeleteDocument(), slotDeleteObject(), slotUndoDocument(), PartGui::FaceAppearances::Private::ui, and PartGui::FaceAppearances::Private::vp.
~FaceAppearances()
FaceAppearances::~FaceAppearances () override
Definition at line 264 of file TaskFaceAppearances.cpp.
References PartGui::FaceAppearances::Private::connectDelDoc, PartGui::FaceAppearances::Private::connectDelObj, PartGui::FaceAppearances::Private::connectUndoDoc, Gui::SelectionSingleton::rmvSelectionGate(), Gui::Selection(), PartGui::FaceAppearances::Private::selectionCallback(), and PartGui::FaceAppearances::Private::view.
Member Function Documentation
accept()
bool FaceAppearances::accept ()
Definition at line 457 of file TaskFaceAppearances.cpp.
References toolbit-attributes::doc, App::DocumentObject::getDocument(), Gui::Application::getDocument(), Gui::ViewProviderDocumentObject::getObject(), Gui::Application::Instance, and PartGui::FaceAppearances::Private::vp.
Referenced by PartGui::TaskFaceAppearances::accept().
changeEvent()
void FaceAppearances::changeEvent (QEvent * e) override protected
Definition at line 473 of file TaskFaceAppearances.cpp.
References SCL.SimpleDataTypes::e, and PartGui::FaceAppearances::Private::ui.
getFirstIndex()
int FaceAppearances::getFirstIndex () const protected
Definition at line 419 of file TaskFaceAppearances.cpp.
References PartGui::FaceAppearances::Private::index.
onSelectionChanged()
void FaceAppearances::onSelectionChanged (const Gui::SelectionChanges & msg) override protected virtual
Implements Gui::SelectionObserver.
Definition at line 356 of file TaskFaceAppearances.cpp.
References App::Color::a, Gui::SelectionChanges::AddSelection, App::Color::b, PartGui::FaceAppearances::Private::boxSelection, Gui::SelectionChanges::ClrSelection, toolbit-attributes::doc, App::Color::g, App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), PartGui::FaceAppearances::Private::index, Path.Op.Surface::msg, PartGui::FaceAppearances::Private::obj, PartGui::FaceAppearances::Private::perface, App::Color::r, Gui::SelectionChanges::RmvSelection, and updatePanel().
open()
void FaceAppearances::open ()
Definition at line 451 of file TaskFaceAppearances.cpp.
References toolbit-attributes::doc, App::DocumentObject::getDocument(), Gui::Application::getDocument(), Gui::ViewProviderDocumentObject::getObject(), Gui::Application::Instance, Arch::QT_TRANSLATE_NOOP, and PartGui::FaceAppearances::Private::vp.
Referenced by PartGui::TaskFaceAppearances::open().
reject()
bool FaceAppearances::reject ()
Definition at line 465 of file TaskFaceAppearances.cpp.
References toolbit-attributes::doc, App::DocumentObject::getDocument(), Gui::Application::getDocument(), Gui::ViewProviderDocumentObject::getObject(), Gui::Application::Instance, and PartGui::FaceAppearances::Private::vp.
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and PartGui::TaskFaceAppearances::reject().
slotDeleteDocument()
void FaceAppearances::slotDeleteDocument (const Gui::Document & Doc) protected
Definition at line 301 of file TaskFaceAppearances.cpp.
References Gui::ControlSingleton::closeDialog(), Gui::Control(), and PartGui::FaceAppearances::Private::doc.
Referenced by FaceAppearances().
slotDeleteObject()
void FaceAppearances::slotDeleteObject (const Gui::ViewProvider & obj) protected
Definition at line 307 of file TaskFaceAppearances.cpp.
References Gui::ControlSingleton::closeDialog(), Gui::Control(), and PartGui::FaceAppearances::Private::vp.
Referenced by FaceAppearances().
slotUndoDocument()
void FaceAppearances::slotUndoDocument (const Gui::Document & Doc) protected
Definition at line 293 of file TaskFaceAppearances.cpp.
References Gui::ControlSingleton::closeDialog(), Gui::Control(), PartGui::FaceAppearances::Private::doc, and Gui::Document::resetEdit().
Referenced by FaceAppearances().
updatePanel()
void FaceAppearances::updatePanel () protected
Definition at line 398 of file TaskFaceAppearances.cpp.
References Gui::QtTools::horizontalAdvance(), PartGui::FaceAppearances::Private::index, and PartGui::FaceAppearances::Private::ui.
Referenced by onSelectionChanged().
The documentation for this class was generated from the following files:
TaskFaceAppearances.h
TaskFaceAppearances.cpp