FreeCAD: ifc2x3.ifcsectionreinforcementproperties Class Reference
ifc2x3.ifcsectionreinforcementproperties Class Reference
Public Member Functions
def __init__ (self, longitudinalstartposition, longitudinalendposition, transverseposition, reinforcementrole, sectiondefinition, crosssectionreinforcementdefinitions)
def longitudinalstartposition ()
def longitudinalendposition ()
def transverseposition ()
def reinforcementrole ()
def sectiondefinition ()
def crosssectionreinforcementdefinitions ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
longitudinalstartposition
longitudinalendposition
transverseposition
reinforcementrole
sectiondefinition
crosssectionreinforcementdefinitions
Detailed Description
Entity ifcsectionreinforcementproperties definition.
:param longitudinalstartposition
:type longitudinalstartposition:ifclengthmeasure
:param longitudinalendposition
:type longitudinalendposition:ifclengthmeasure
:param transverseposition
:type transverseposition:ifclengthmeasure
:param reinforcementrole
:type reinforcementrole:ifcreinforcingbarroleenum
:param sectiondefinition
:type sectiondefinition:ifcsectionproperties
:param crosssectionreinforcementdefinitions
:type crosssectionreinforcementdefinitions:SET(1,None,'ifcreinforcementbarproperties', scope = schema_scope)
Definition at line 28677 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcsectionreinforcementproperties.__init__ (self, longitudinalstartposition, longitudinalendposition, transverseposition, reinforcementrole, sectiondefinition, crosssectionreinforcementdefinitions)
Definition at line 28698 of file ifc2x3.py.
Member Function Documentation
crosssectionreinforcementdefinitions()
def ifc2x3.ifcsectionreinforcementproperties.crosssectionreinforcementdefinitions ()
Definition at line 28777 of file ifc2x3.py.
References ifc2x3.ifcsectionreinforcementproperties._crosssectionreinforcementdefinitions, SCL.TypeChecker.check_type(), and ifc2x3.ifcsectionreinforcementproperties.crosssectionreinforcementdefinitions.
longitudinalendposition()
def ifc2x3.ifcsectionreinforcementproperties.longitudinalendposition ()
Definition at line 28721 of file ifc2x3.py.
References ifc2x3.ifcsectionreinforcementproperties._longitudinalendposition, SCL.TypeChecker.check_type(), and ifc2x3.ifcsectionreinforcementproperties.longitudinalendposition.
longitudinalstartposition()
def ifc2x3.ifcsectionreinforcementproperties.longitudinalstartposition ()
Definition at line 28707 of file ifc2x3.py.
References ifc2x3.ifcsectionreinforcementproperties._longitudinalstartposition, SCL.TypeChecker.check_type(), and ifc2x3.ifcsectionreinforcementproperties.longitudinalstartposition.
reinforcementrole()
def ifc2x3.ifcsectionreinforcementproperties.reinforcementrole ()
Definition at line 28749 of file ifc2x3.py.
References ifc2x3.ifcsectionreinforcementproperties._reinforcementrole, SCL.TypeChecker.check_type(), and ifc2x3.ifcsectionreinforcementproperties.reinforcementrole.
sectiondefinition()
def ifc2x3.ifcsectionreinforcementproperties.sectiondefinition ()
Definition at line 28763 of file ifc2x3.py.
References ifc2x3.ifcsectionreinforcementproperties._sectiondefinition, SCL.TypeChecker.check_type(), and ifc2x3.ifcsectionreinforcementproperties.sectiondefinition.
transverseposition()
def ifc2x3.ifcsectionreinforcementproperties.transverseposition ()
Definition at line 28735 of file ifc2x3.py.
References ifc2x3.ifcsectionreinforcementproperties._transverseposition, SCL.TypeChecker.check_type(), and ifc2x3.ifcsectionreinforcementproperties.transverseposition.
Member Data Documentation
crosssectionreinforcementdefinitions
ifc2x3.ifcsectionreinforcementproperties.crosssectionreinforcementdefinitions
Definition at line 28704 of file ifc2x3.py.
Referenced by ifc2x3.ifcsectionreinforcementproperties.crosssectionreinforcementdefinitions().
longitudinalendposition
ifc2x3.ifcsectionreinforcementproperties.longitudinalendposition
Definition at line 28700 of file ifc2x3.py.
Referenced by ifc2x3.ifcsectionreinforcementproperties.longitudinalendposition().
longitudinalstartposition
ifc2x3.ifcsectionreinforcementproperties.longitudinalstartposition
Definition at line 28699 of file ifc2x3.py.
Referenced by ifc2x3.ifcsectionreinforcementproperties.longitudinalstartposition().
reinforcementrole
ifc2x3.ifcsectionreinforcementproperties.reinforcementrole
Definition at line 28702 of file ifc2x3.py.
Referenced by ifc2x3.ifcsectionreinforcementproperties.reinforcementrole().
sectiondefinition
ifc2x3.ifcsectionreinforcementproperties.sectiondefinition
Definition at line 28703 of file ifc2x3.py.
Referenced by ifc2x3.ifcsectionreinforcementproperties.sectiondefinition().
transverseposition
ifc2x3.ifcsectionreinforcementproperties.transverseposition
Definition at line 28701 of file ifc2x3.py.
Referenced by ifc2x3.ifcsectionreinforcementproperties.transverseposition().
The documentation for this class was generated from the following file:
ifc2x3.py