FreeCAD: ParameterManager Class Reference
ParameterManager Class Reference
#include <Parameter.h>
Public Member Functions
int LoadDocument (const char *sFileName)
int LoadDocument (const InputSource &)
bool LoadOrCreateDocument (const char *sFileName)
void SaveDocument (const char *sFileName) const
void SaveDocument (XMLFormatTarget *pFormatTarget) const
void CreateDocument ()
void CheckDocument () const
Public Member Functions inherited from ParameterGrp
ParameterGrp (const ParameterGrp &)=delete
ParameterGrp (ParameterGrp &&)=delete
ParameterGrp & operator= (const ParameterGrp &)=delete
ParameterGrp & operator= (ParameterGrp &&)=delete
void copyTo (const Base::Reference< ParameterGrp > &)
make a deep copy to the other group
void insertTo (const Base::Reference< ParameterGrp > &)
overwrite everything similar, leave the others alone
void exportTo (const char *FileName)
export this group to a file
void importFrom (const char *FileName)
import from a file to this group
void insert (const char *FileName)
insert from a file to this group, overwrite only the similar
void revert (const char *FileName)
revert to default value by deleting any parameter that has the same value in the given file
void revert (const Base::Reference< ParameterGrp > &)
revert to default value by deleting any parameter that has the same value in the given group
bool GetBool (const char *Name, bool bPreset=false) const
read bool values or give default
void SetBool (const char *Name, bool bValue)
set a bool value
std::vector< bool > GetBools (const char *sFilter=nullptr) const
get a vector of all bool values in this group
std::vector< std::pair< std::string, bool > > GetBoolMap (const char *sFilter=nullptr) const
get a map with all bool values and the keys of this group
void RemoveBool (const char *Name)
remove a bool value from this group
long GetInt (const char *Name, long lPreset=0) const
read bool values or give default
void SetInt (const char *Name, long lValue)
set a int value
std::vector< long > GetInts (const char *sFilter=nullptr) const
get a vector of all int values in this group
std::vector< std::pair< std::string, long > > GetIntMap (const char *sFilter=nullptr) const
get a map with all int values and the keys of this group
void RemoveInt (const char *Name)
remove a int value from this group
unsigned long GetUnsigned (const char *Name, unsigned long lPreset=0) const
read uint values or give default
void SetUnsigned (const char *Name, unsigned long lValue)
set a uint value
std::vector< unsigned long > GetUnsigneds (const char *sFilter=nullptr) const
get a vector of all uint values in this group
std::vector< std::pair< std::string, unsigned long > > GetUnsignedMap (const char *sFilter=nullptr) const
get a map with all uint values and the keys of this group
void RemoveUnsigned (const char *Name)
remove a uint value from this group
double GetFloat (const char *Name, double dPreset=0.0) const
set a float value
void SetFloat (const char *Name, double dValue)
read float values or give default
std::vector< double > GetFloats (const char *sFilter=nullptr) const
get a vector of all float values in this group
std::vector< std::pair< std::string, double > > GetFloatMap (const char *sFilter=nullptr) const
get a map with all float values and the keys of this group
void RemoveFloat (const char *Name)
remove a float value from this group
Base::Reference< ParameterGrp > GetGroup (const char *Name)
get a handle to a sub group or create one
std::vector< Base::Reference< ParameterGrp > > GetGroups ()
get a vector of all sub groups in this group
bool IsEmpty () const
test if this group is empty
bool HasGroup (const char *Name) const
test if a special sub group is in this group
void RemoveGrp (const char *Name)
remove a sub group from this group
bool RenameGrp (const char *OldName, const char *NewName)
rename a sub group from this group
void Clear (bool notify=false)
void SetAttribute (ParamType Type, const char *Name, const char *Value)
void RemoveAttribute (ParamType Type, const char *Name)
const char * GetAttribute (ParamType Type, const char *Name, std::string &Value, const char *Default) const
std::vector< std::pair< std::string, std::string > > GetAttributeMap (ParamType Type, const char *sFilter=nullptr) const
std::vector< std::pair< ParamType, std::string > > GetParameterNames (const char *sFilter=nullptr) const
void SetASCII (const char *Name, const char *sValue)
set a string value
void SetASCII (const char *Name, const std::string &sValue)
set a string value
std::string GetASCII (const char *Name, const char *pPreset=nullptr) const
read a string values
void RemoveASCII (const char *Name)
remove a string value from this group
std::vector< std::string > GetASCIIs (const char *sFilter=nullptr) const
std::vector< std::pair< std::string, std::string > > GetASCIIMap (const char *sFilter=nullptr) const
Same as GetASCIIs() but with key,value map.
const char * GetGroupName () const
returns the name
std::string GetPath () const
return the full path of this group
void GetPath (std::string &) const
void NotifyAll ()
ParameterGrp * Parent () const
ParameterManager * Manager () const
Public Member Functions inherited from Base::Handled
Handled ()
virtual ~Handled ()
void ref () const
void unref () const
int unrefNoDelete () const
int getRefCount () const
Handled & operator= (const Handled &)
Handled (const Handled &)=delete
Handled (Handled &&)=delete
Handled & operator= (Handled &&)=delete
Public Member Functions inherited from Base::Subject< const char * >
Subject ()=default
virtual ~Subject ()
void Attach (Observer< const char * > *ToObserv)
void Detach (Observer< const char * > *ToObserv)
void Notify (const char * rcReason)
Observer< const char * > * Get (const char *Name)
void ClearObserver ()
Static Public Member Functions
static Base::Reference< ParameterManager > Create ()
Create a reference counted ParameterManager.
static void Init ()
static void Terminate ()
Static Public Member Functions inherited from ParameterGrp
static const char * TypeName (ParamType type)
static ParamType TypeValue (const char *)
Public Attributes
boost::signals2::signal< void(ParameterGrp *, ParamType, const char *, const char *)> signalParamChanged
Parameter serialization
void SetSerializer (ParameterSerializer *)
Sets a serializer. The ParameterManager takes ownership of the serializer.
bool HasSerializer () const
Returns true if a serializer is set, otherwise false is returned.
const std::string & GetSerializeFileName () const
Returns the filename of the serialize.
int LoadDocument ()
Loads an XML document by calling the serializer's load method.
bool LoadOrCreateDocument ()
Loads or creates an XML document by calling the serializer's load method.
void SaveDocument () const
Saves an XML document by calling the serializer's save method.
void SetIgnoreSave (bool value)
bool IgnoreSave () const
~ParameterManager () override
ParameterManager (const ParameterManager &)=delete
ParameterManager (ParameterManager &&)=delete
ParameterManager & operator= (const ParameterManager &)=delete
ParameterManager & operator= (ParameterManager &&)=delete
Additional Inherited Members
Public Types inherited from ParameterGrp
using handle = Base::Reference< ParameterGrp >
type of the handle
enum ParamType {
ParamType::FCInvalid = 0, ParamType::FCText = 1, ParamType::FCBool = 2, ParamType::FCInt = 3,
ParamType::FCUInt = 4, ParamType::FCFloat = 5, ParamType::FCGroup = 6
}
Public Types inherited from Base::Subject< const char * >
using ObserverType = Observer< const char * >
using MessageType = const char *
using SubjectType = Subject< const char * >
Protected Member Functions inherited from ParameterGrp
ParameterGrp (DOMElement *GroupNode=nullptr, const char *sName=nullptr, ParameterGrp *Parent=nullptr)
constructor is protected (handle concept)
~ParameterGrp () override
destructor is protected (handle concept)
Base::Reference< ParameterGrp > _GetGroup (const char *Name)
helper function for GetGroup
bool ShouldRemove () const
void _Reset ()
void _SetAttribute (ParamType Type, const char *Name, const char *Value)
void _Notify (ParamType Type, const char *Name, const char *Value)
DOMElement * FindNextElement (DOMNode *Prev, const char *Type) const
DOMElement * FindElement (DOMElement *Start, const char *Type, const char *Name=nullptr) const
DOMElement * FindOrCreateElement (DOMElement *Start, const char *Type, const char *Name)
DOMElement * CreateElement (DOMElement *Start, const char *Type, const char *Name)
DOMNode * FindAttribute (DOMNode *Node, const char *Name) const
Protected Attributes inherited from ParameterGrp
DOMElement * _pGroupNode
DOM Node of the Base node of this group.
std::string _cName
the own name
std::map< std::string, Base::Reference< ParameterGrp > > _GroupMap
map of already exported groups
ParameterGrp * _Parent = nullptr
ParameterManager * _Manager = nullptr
bool _Detached = false
Means this group xml element has not been added to its parent yet.
bool _Clearing = false
Detailed Description
The parameter manager class This class manages a parameter XML document. Does loading, saving and handling the DOM document.
See also
ParameterGrp
Definition at line 391 of file Parameter.h.
Constructor & Destructor Documentation
~ParameterManager()
ParameterManager::~ParameterManager () override
Destruction complete destruction of the object
Definition at line 1640 of file Parameter.cpp.
References ParameterGrp::_Reset().
ParameterManager() [1/2]
ParameterManager::ParameterManager (const ParameterManager &) delete
ParameterManager() [2/2]
ParameterManager::ParameterManager (ParameterManager &&) delete
Member Function Documentation
CheckDocument()
void ParameterManager::CheckDocument () const
Definition at line 1986 of file Parameter.cpp.
References Base::Console(), SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), getIfcElements::parser, and SaveDocument().
Referenced by Gui::Dialog::DlgParameterImp::onChangeParameterSet().
Create()
Base::Reference< ParameterManager > ParameterManager::Create () static
Create a reference counted ParameterManager.
Definition at line 1647 of file Parameter.cpp.
Referenced by Gui::Dialog::DlgRevertToBackupConfigImp::accept(), App::Application::AddParameterSet(), ParameterGrp::exportTo(), ParameterGrp::importFrom(), ParameterGrp::insert(), ParameterGrp::revert(), and Gui::PreferencePackManager::save().
CreateDocument()
void ParameterManager::CreateDocument ()
Definition at line 1969 of file Parameter.cpp.
References ParameterGrp::_pGroupNode.
Referenced by LoadDocument(), and LoadOrCreateDocument().
GetSerializeFileName()
const std::string & ParameterManager::GetSerializeFileName () const
Returns the filename of the serialize.
Definition at line 1697 of file Parameter.cpp.
References ParameterSerializer::GetFileName().
HasSerializer()
bool ParameterManager::HasSerializer () const
Returns true if a serializer is set, otherwise false is returned.
Definition at line 1692 of file Parameter.cpp.
Referenced by Gui::Dialog::DlgParameterImp::onChangeParameterSet().
IgnoreSave()
bool ParameterManager::IgnoreSave () const
Definition at line 1733 of file Parameter.cpp.
Referenced by App::Application::destruct().
Init()
void ParameterManager::Init () static
Definition at line 1652 of file Parameter.cpp.
LoadDocument() [1/3]
int ParameterManager::LoadDocument ()
Loads an XML document by calling the serializer's load method.
Definition at line 1703 of file Parameter.cpp.
References ParameterSerializer::LoadDocument().
Referenced by LoadDocument(), and LoadOrCreateDocument().
LoadDocument() [2/3]
int ParameterManager::LoadDocument (const char * sFileName)
Definition at line 1768 of file Parameter.cpp.
References CreateDocument(), SCL.SimpleDataTypes::e, DrawingExample::file, LoadDocument(), SetIgnoreSave(), and XStr::unicodeForm().
Referenced by Gui::PreferencePack::apply(), and ParameterSerializer::LoadDocument().
LoadDocument() [3/3]
int ParameterManager::LoadDocument (const InputSource & inputSource)
Definition at line 1799 of file Parameter.cpp.
References ParameterGrp::_pGroupNode, SCL.SimpleDataTypes::e, ParameterGrp::FindElement(), gValScheme, and getIfcElements::parser.
LoadOrCreateDocument() [1/2]
bool ParameterManager::LoadOrCreateDocument ()
Loads or creates an XML document by calling the serializer's load method.
Definition at line 1712 of file Parameter.cpp.
References ParameterSerializer::LoadOrCreateDocument().
LoadOrCreateDocument() [2/2]
bool ParameterManager::LoadOrCreateDocument (const char * sFileName)
Definition at line 1756 of file Parameter.cpp.
References CreateDocument(), DrawingExample::file, and LoadDocument().
Referenced by ParameterSerializer::LoadOrCreateDocument().
operator=() [1/2]
ParameterManager& ParameterManager::operator= (const ParameterManager &) delete
operator=() [2/2]
ParameterManager& ParameterManager::operator= (ParameterManager &&) delete
SaveDocument() [1/3]
void ParameterManager::SaveDocument () const
Saves an XML document by calling the serializer's save method.
Definition at line 1721 of file Parameter.cpp.
References ParameterSerializer::SaveDocument().
Referenced by CheckDocument(), and SaveDocument().
SaveDocument() [2/3]
void ParameterManager::SaveDocument (const char * sFileName) const
Definition at line 1867 of file Parameter.cpp.
References SCL.SimpleDataTypes::e, DrawingExample::file, and SaveDocument().
Referenced by Gui::RecentMacrosAction::appendFile(), Gui::PreferencePack::apply(), App::Application::destruct(), Gui::Dialog::DlgParameterImp::onButtonSaveToDiskClicked(), ParameterSerializer::SaveDocument(), and Gui::RecentFilesAction::Private::saveUserParameter().
SaveDocument() [3/3]
void ParameterManager::SaveDocument (XMLFormatTarget * pFormatTarget) const
Definition at line 1900 of file Parameter.cpp.
References SCL.SimpleDataTypes::e.
SetIgnoreSave()
void ParameterManager::SetIgnoreSave (bool value)
Definition at line 1728 of file Parameter.cpp.
Referenced by LoadDocument().
SetSerializer()
void ParameterManager::SetSerializer (ParameterSerializer * ps)
Sets a serializer. The ParameterManager takes ownership of the serializer.
Definition at line 1684 of file Parameter.cpp.
Terminate()
void ParameterManager::Terminate () static
Definition at line 1675 of file Parameter.cpp.
References XMLTools::terminate().
Referenced by App::Application::destruct().
Member Data Documentation
signalParamChanged
boost::signals2::signal<void(ParameterGrp* , ParamType , const char* , const char*)> ParameterManager::signalParamChanged
Signal on parameter changes
The signal is triggered on adding, removing, renaming or modifying on all individual parameters and group. The signature of the signal is
void (ParameterGrp *param, ParamType type, const char *name, const char *value)
where 'param' is the parameter group causing the change, 'type' is the type of the parameter, 'name' is the name of the parameter, and 'value' is the current value.
The possible values of 'type' are, 'FCBool', 'FCInt', 'FCUint', 'FCFloat', 'FCText', and 'FCParamGroup'. The notification is triggered when value is changed, in which case 'value' contains the new value in text form, or, when the parameter is removed, in which case 'value' is empty.
For 'FCParamGroup' type, the observer will be notified in the following events.
Group creation: both 'name' and 'value' contain the name of the new group
Group removal: both 'name' and 'value' are empty
Group rename: 'name' is the new name, and 'value' is the old name
Definition at line 425 of file Parameter.h.
Referenced by ParameterGrp::_Notify(), Gui::ParamHandlers::addHandler(), Gui::MainWindow::MainWindow(), Gui::NaviCubeSettings::NaviCubeSettings(), and OverlayInfo::OverlayInfo().
The documentation for this class was generated from the following files:
Parameter.h
Parameter.cpp