FreeCAD: SketcherGui::EditModeCoinManager Class Reference
SketcherGui::EditModeCoinManager Class Reference
Helper class for managing the Coin nodes of ViewProviderSketch.
#include <EditModeCoinManager.h>
Classes
struct PreselectionResult
This struct defines the information provided to other classes about preselection.
Public Member Functions
EditModeCoinManager (ViewProviderSketch &vp)
~EditModeCoinManager ()
Temporary edit curves and markers
void drawEditMarkers (const std::vector< Base::Vector2d > &EditMarkers, unsigned int augmentationlevel)
void drawEdit (const std::vector< Base::Vector2d > &EditCurve)
void drawEdit (const std::list< std::vector< Base::Vector2d >> &list)
void setPositionText (const Base::Vector2d &Pos, const SbString &txt)
void setPositionText (const Base::Vector2d &Pos)
void resetPositionText ()
void setAxisPickStyle (bool on)
handle preselection and selection of points
PreselectionResult detectPreselection (SoPickedPoint *Point, const SbVec2s &cursorPos)
SoGroup * getSelectedConstraints ()
The client is responsible for unref-ing the SoGroup to release the memory.
update coin nodes
void processGeometryConstraintsInformationOverlay (const GeoListFacade &geolistfacade, bool rebuildinformationlayer)
void updateVirtualSpace ()
void drawConstraintIcons ()
Draw all constraint icons.
void drawConstraintIcons (const GeoListFacade &geolistfacade)
void updateGeometryLayersConfiguration ()
coin node access
SoSeparator * getRootEditNode ()
update coin colors
void updateColor ()
void updateColor (const GeoListFacade &geolistfacade)
change constraints selectability
void setConstraintSelectability (bool enabled=true)
void updateAxesLength (const Base::BoundBox2d &bb)
Detailed Description
Helper class for managing the Coin nodes of ViewProviderSketch.
Given the substantial amount of code involved in coin node management, EditModeCoinManager further delegates on other specialised helper classes. Some of them share the ViewProviderSketchCoinAttorney, which defines the maximum coupling and minimum encapsulation.
The most important such delegates are: EditModeGeometryCoinManager and EditModeConstraintCoinManager.
EditModeCoinManager takes over the responsibility of creating the Coin (Inventor) scenegraph and modifying it, including all the drawing of geometry, constraints and overlay layer. This is an exclusive responsibility under the Single Responsibility Principle.
EditModeCoinManager exposes a public interface to be used by ViewProviderSketch. Where, EditModeCoinManager needs special access to facilities of ViewProviderSketch in order to fulfil its responsibility, this access is defined by ViewProviderSketchCoinAttorney.
EditModeCoinManager is responsible, under the Single Responsibility Principle, to manage the coin EditRoot node. This node is ref-ed on creation and unref-ed on destruction to ensure that its lifetime matches the one of EditModeCoinManager.
EditRoot is added on request to pcRoot by ViewProviderSketch. The node pcRoot belongs, under the Single Responsibility Principle, to ViewProviderSketch. EditModeCoinManager delegates addition and removal of child notes of EditRoot to specialised helper classes.
EditModeCoinManager is designed to define the span of time in which ViewProviderSketch is in edit mode.
In addition to the scenegraph, EditModeCoinManager is responsible for keeping any necessary mapping between indices used at ViewProviderSketch level, and internal indexing used by EditModeCoinManager and its subclasses.
Definition at line 106 of file EditModeCoinManager.h.
Constructor & Destructor Documentation
EditModeCoinManager()
EditModeCoinManager::EditModeCoinManager (ViewProviderSketch & vp) explicit
Definition at line 529 of file EditModeCoinManager.cpp.
~EditModeCoinManager()
EditModeCoinManager::~EditModeCoinManager ()
Definition at line 555 of file EditModeCoinManager.cpp.
References Gui::coinRemoveAllChildren(), and SketcherGui::EditModeScenegraphNodes::EditRoot.
Member Function Documentation
detectPreselection()
EditModeCoinManager::PreselectionResult EditModeCoinManager::detectPreselection (SoPickedPoint * Point, const SbVec2s & cursorPos)
Definition at line 710 of file EditModeCoinManager.cpp.
References SketcherGui::EditModeScenegraphNodes::CurveSet, SketcherGui::GeometryLayerParameters::getCoinLayerCount(), SketcherGui::CoinMapping::getCurveGeoId(), SketcherGui::CoinMapping::getPointVertexId(), SketcherGui::GeometryLayerParameters::getSubLayerCount(), SketcherGui::EditModeCoinManager::PreselectionResult::HorizontalAxis, RobotExample::l, SketcherGui::EditModeScenegraphNodes::PointSet, result, SketcherGui::EditModeScenegraphNodes::RootCrossSet, SketcherGui::EditModeCoinManager::PreselectionResult::RootPoint, InitGui::t, and SketcherGui::EditModeCoinManager::PreselectionResult::VerticalAxis.
drawConstraintIcons() [1/2]
void EditModeCoinManager::drawConstraintIcons ()
Draw all constraint icons.
Except maybe the radius and lock ones?
Definition at line 1053 of file EditModeCoinManager.cpp.
drawConstraintIcons() [2/2]
void EditModeCoinManager::drawConstraintIcons (const GeoListFacade & geolistfacade)
Definition at line 1058 of file EditModeCoinManager.cpp.
drawEdit() [1/2]
void EditModeCoinManager::drawEdit (const std::list< std::vector< Base::Vector2d >> & list)
Definition at line 637 of file EditModeCoinManager.cpp.
References SketcherGui::DrawingParameters::CreateCurveColor, SketcherGui::EditModeScenegraphNodes::EditCurvesCoordinate, SketcherGui::EditModeScenegraphNodes::EditCurveSet, SketcherGui::EditModeScenegraphNodes::EditCurvesMaterials, buildPsets::p, TestSpreadsheet::v, and SketcherGui::DrawingParameters::zEdit.
drawEdit() [2/2]
void EditModeCoinManager::drawEdit (const std::vector< Base::Vector2d > & EditCurve)
Definition at line 612 of file EditModeCoinManager.cpp.
References SketcherGui::DrawingParameters::CreateCurveColor, SketcherGui::EditModeScenegraphNodes::EditCurvesCoordinate, SketcherGui::EditModeScenegraphNodes::EditCurveSet, SketcherGui::EditModeScenegraphNodes::EditCurvesMaterials, SplineSurface::i, and SketcherGui::DrawingParameters::zEdit.
drawEditMarkers()
void EditModeCoinManager::drawEditMarkers (const std::vector< Base::Vector2d > & EditMarkers, unsigned int augmentationlevel)
Definition at line 565 of file EditModeCoinManager.cpp.
References SketcherGui::EditModeScenegraphNodes::EditMarkersCoordinate, SketcherGui::EditModeScenegraphNodes::EditMarkerSet, SketcherGui::EditModeScenegraphNodes::EditMarkersMaterials, DraftVecUtils::find(), Gui::Inventor::MarkerBitmaps::getMarkerIndex(), Gui::Inventor::MarkerBitmaps::getSupportedSizes(), SplineSurface::i, SketcherGui::DrawingParameters::InformationColor, SketcherGui::DrawingParameters::markerSize, and SketcherGui::DrawingParameters::zEdit.
getRootEditNode()
SoSeparator * EditModeCoinManager::getRootEditNode ()
Definition at line 1148 of file EditModeCoinManager.cpp.
References SketcherGui::EditModeScenegraphNodes::EditRoot.
getSelectedConstraints()
SoGroup * EditModeCoinManager::getSelectedConstraints ()
The client is responsible for unref-ing the SoGroup to release the memory.
Definition at line 780 of file EditModeCoinManager.cpp.
References SketcherGui::EditModeScenegraphNodes::constrGroup, toolbit-attributes::group, and SplineSurface::i.
processGeometryConstraintsInformationOverlay()
void EditModeCoinManager::processGeometryConstraintsInformationOverlay (const GeoListFacade & geolistfacade, bool rebuildinformationlayer)
Definition at line 799 of file EditModeCoinManager.cpp.
References SketcherGui::OverlayParameters::rebuildInformationLayer.
resetPositionText()
void EditModeCoinManager::resetPositionText ()
Definition at line 694 of file EditModeCoinManager.cpp.
References SketcherGui::EditModeScenegraphNodes::textX.
setAxisPickStyle()
void EditModeCoinManager::setAxisPickStyle (bool on)
Definition at line 699 of file EditModeCoinManager.cpp.
References SketcherGui::EditModeScenegraphNodes::pickStyleAxes.
setConstraintSelectability()
void EditModeCoinManager::setConstraintSelectability (bool enabled = true)
Definition at line 891 of file EditModeCoinManager.cpp.
setPositionText() [1/2]
void EditModeCoinManager::setPositionText (const Base::Vector2d & Pos)
Definition at line 683 of file EditModeCoinManager.cpp.
References SketcherGui::lengthToDisplayFormat(), setPositionText(), SketcherGui::showCursorCoords(), Base::Vector2d::x, and Base::Vector2d::y.
setPositionText() [2/2]
void EditModeCoinManager::setPositionText (const Base::Vector2d & Pos, const SbString & txt)
Definition at line 673 of file EditModeCoinManager.cpp.
References SketcherGui::EditModeScenegraphNodes::textPos, SketcherGui::EditModeScenegraphNodes::textX, Base::Vector2d::x, Base::Vector2d::y, and SketcherGui::DrawingParameters::zText.
Referenced by setPositionText().
updateAxesLength()
void EditModeCoinManager::updateAxesLength (const Base::BoundBox2d & bb)
Definition at line 853 of file EditModeCoinManager.cpp.
References SCL.SimpleDataTypes::f, Base::BoundBox2d::MaxX, Base::BoundBox2d::MaxY, Base::BoundBox2d::MinX, Base::BoundBox2d::MinY, SketcherGui::EditModeScenegraphNodes::RootCrossCoordinate, and SketcherGui::DrawingParameters::zCross.
updateColor() [1/2]
void EditModeCoinManager::updateColor ()
Definition at line 867 of file EditModeCoinManager.cpp.
updateColor() [2/2]
void EditModeCoinManager::updateColor (const GeoListFacade & geolistfacade)
Definition at line 874 of file EditModeCoinManager.cpp.
updateGeometryLayersConfiguration()
void EditModeCoinManager::updateGeometryLayersConfiguration ()
Definition at line 897 of file EditModeCoinManager.cpp.
updateVirtualSpace()
void EditModeCoinManager::updateVirtualSpace ()
Definition at line 1063 of file EditModeCoinManager.cpp.
The documentation for this class was generated from the following files:
EditModeCoinManager.h
EditModeCoinManager.cpp