FreeCAD: Gui::View3DInventor Class Reference
Gui::View3DInventor Class Reference
#include <View3DInventor.h>
Public Slots
void setOverrideCursor (const QCursor &) override
override the cursor in this view
void restoreOverrideCursor () override
void dump (const char *filename, bool onlyVisible=false)
Public Slots inherited from Gui::MDIView
virtual void setOverrideCursor (const QCursor &)
virtual void restoreOverrideCursor ()
Public Member Functions
View3DInventor (Gui::Document *pcDocument, QWidget *parent, const QtGLWidget *sharewidget=nullptr, Qt::WindowFlags wflags=Qt::WindowFlags())
~View3DInventor () override
bool onMsg (const char *pMsg, const char **ppReturn) override
Message handler.
bool onHasMsg (const char *pMsg) const override
Message handler test.
void deleteSelf () override
delete itself
void onRename (Gui::Document *pDoc) override
get called when the document is updated
void onUpdate () override
get called when the document is updated
void viewAll () override
const char * getName () const override
returns the name of the view (important for messages)
void print () override
print function of the view
void printPdf () override
void printPreview () override
void print (QPrinter *) override
PyObject * getPyObject () override
void setCurrentViewMode (ViewMode b) override
RayPickInfo getObjInfoRay (Base::Vector3d *startvec, Base::Vector3d *dirvec)
bool setCamera (const char *pCamera)
void toggleClippingPlane ()
bool hasClippingPlane () const
void setOverlayWidget (QWidget *)
void removeOverlayWidget ()
View3DInventorViewer * getViewer () const
bool containsViewProvider (const ViewProvider *) const override
containsViewProvider Checks if the given view provider is part of this view. The default implementation returns false.
bool eventFilter (QObject *, QEvent *) override
Public Member Functions inherited from Gui::MDIView
MDIView (Gui::Document *pcDocument, QWidget *parent, Qt::WindowFlags wflags=Qt::WindowFlags())
~MDIView () override
void onRelabel (Gui::Document *pDoc) override
get called when the document is updated
QString buildWindowTitle () const
build window title
bool canClose () override
overwrite when checking on close state
void savePrinterSettings (QPrinter *printer)
void restorePrinterSettings (QPrinter *printer)
virtual QStringList undoActions () const
virtual QStringList redoActions () const
QSize minimumSizeHint () const override
ViewMode currentViewMode () const
template<typename _T >
_T getActiveObject (const char *name, App::DocumentObject **parent=nullptr, std::string *subname=nullptr) const
access getter for the active object list
void setActiveObject (App::DocumentObject *o, const char *n, const char *subname=nullptr)
bool hasActiveObject (const char *n) const
bool isActiveObject (App::DocumentObject *o, const char *n, const char *subname=nullptr) const
Public Member Functions inherited from Gui::BaseView
BaseView (Gui::Document *pcDocument=nullptr)
~BaseView () override
void setDocument (Gui::Document *pcDocument)
sets the view to another document (called by Application)
void onClose ()
is sent from the document in order to close the document
Gui::Document * getGuiDocument () const
returns the document the view is attached to
App::Document * getAppDocument () const
returns the document the view is attached to
bool isPassive () const
indicates if the view is in passive mode
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Slots
void stopAnimating ()
Protected Slots inherited from Gui::MDIView
Protected Member Functions
void windowStateChanged (QWidget *view) override
void dropEvent (QDropEvent *e) override
void dragEnterEvent (QDragEnterEvent *e) override
void keyPressEvent (QKeyEvent *e) override
void keyReleaseEvent (QKeyEvent *e) override
void focusInEvent (QFocusEvent *e) override
void customEvent (QEvent *e) override
void contextMenuEvent (QContextMenuEvent *e) override
Protected Member Functions inherited from Gui::MDIView
void closeEvent (QCloseEvent *e) override
void changeEvent (QEvent *e) override
Friends
class View3DPy
Additional Inherited Members
Public Types inherited from Gui::MDIView
enum ViewMode { Child, TopLevel, FullScreen }
MDI view mode enum.
Signals inherited from Gui::MDIView
void message (const QString &, int)
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Gui::MDIView
PyObject * pythonObject
Protected Attributes inherited from Gui::BaseView
Gui::Document * _pcDocument
bool bIsDetached {false}
bool bIsPassive {false}
Detailed Description
The 3D view window It consists out of the 3D view
Author
Juergen Riegel
Definition at line 78 of file View3DInventor.h.
Constructor & Destructor Documentation
View3DInventor()
View3DInventor::View3DInventor (Gui::Document * pcDocument, QWidget * parent, const QtGLWidget * sharewidget = nullptr, Qt::WindowFlags wflags = Qt::WindowFlags())
Definition at line 93 of file View3DInventor.cpp.
References Gui::BitmapFactory(), draftgeoutils.intersections::connect(), SCL.SimpleDataTypes::f, Gui::View3DInventorViewer::getNumSamples(), and stopAnimating().
~View3DInventor()
View3DInventor::~View3DInventor () override
Definition at line 145 of file View3DInventor.cpp.
References Gui::BaseView::_pcDocument, SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), Gui::Document::saveCameraSettings(), and Gui::SoFCDB::writeNodesToString().
Member Function Documentation
containsViewProvider()
bool View3DInventor::containsViewProvider (const ViewProvider *) const override virtual
containsViewProvider Checks if the given view provider is part of this view. The default implementation returns false.
Returns
bool
Reimplemented from Gui::MDIView.
Definition at line 296 of file View3DInventor.cpp.
References Gui::View3DInventorViewer::containsViewProvider().
contextMenuEvent()
void View3DInventor::contextMenuEvent (QContextMenuEvent * e) override protected
Definition at line 913 of file View3DInventor.cpp.
References SCL.SimpleDataTypes::e.
customEvent()
void View3DInventor::customEvent (QEvent * e) override protected
Definition at line 918 of file View3DInventor.cpp.
References SCL.SimpleDataTypes::e, App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), ParameterGrp::SetASCII(), and Gui::View3DInventorViewer::setNavigationType().
deleteSelf()
void View3DInventor::deleteSelf () override virtual
delete itself
Reimplemented from Gui::MDIView.
Definition at line 181 of file View3DInventor.cpp.
References Gui::MDIView::deleteSelf(), Gui::View3DInventorViewer::setDocument(), and Gui::View3DInventorViewer::setSceneGraph().
dragEnterEvent()
void View3DInventor::dragEnterEvent (QDragEnterEvent * e) override protected
Definition at line 709 of file View3DInventor.cpp.
References SCL.SimpleDataTypes::e.
dropEvent()
void View3DInventor::dropEvent (QDropEvent * e) override protected
Drops the event e and writes the right Python command.
Definition at line 698 of file View3DInventor.cpp.
References SCL.SimpleDataTypes::e, Gui::BaseView::getAppDocument(), Gui::getMainWindow(), and Gui::MainWindow::loadUrls().
dump
void View3DInventor::dump (const char * filename, bool onlyVisible = false) slot
Definition at line 642 of file View3DInventor.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Gui::View3DInventorViewer::dumpToFile(), SIM::Coin3D::Quarter::QuarterWidget::getSceneGraph(), and replaceSwitchesInSceneGraph().
Referenced by Gui::View3DInventorPy::dump(), and onMsg().
eventFilter()
bool View3DInventor::eventFilter (QObject * watched, QEvent * e) override
Definition at line 871 of file View3DInventor.cpp.
References a, Path.Post.scripts.dynapath_4060_post::action, and SCL.SimpleDataTypes::e.
focusInEvent()
void View3DInventor::focusInEvent (QFocusEvent * e) override protected
Definition at line 908 of file View3DInventor.cpp.
References SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getGLWidget().
getName()
const char * View3DInventor::getName () const override virtual
returns the name of the view (important for messages)
Reimplemented from Gui::BaseView.
Definition at line 229 of file View3DInventor.cpp.
getObjInfoRay()
RayPickInfo View3DInventor::getObjInfoRay (Base::Vector3d * startvec, Base::Vector3d * dirvec)
Definition at line 780 of file View3DInventor.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Gui::RayPickInfo::component, Gui::SoFCDocumentObjectAction::componentName, Gui::RayPickInfo::document, Gui::SoFCDocumentObjectAction::documentName, Base::Persistence::getClassTypeId(), Gui::ViewProvider::getElementPicked(), getViewer(), Gui::View3DInventorViewer::getViewProviderByPath(), Base::BaseClass::isDerivedFrom(), Gui::SoFCDocumentObjectAction::isHandled(), Gui::ViewProvider::isSelectable(), Gui::RayPickInfo::isValid, App::ElementNamePair::newName, Gui::RayPickInfo::object, Gui::SoFCDocumentObjectAction::objectName, App::ElementNamePair::oldName, Gui::RayPickInfo::parentObject, Gui::RayPickInfo::point, App::GeoFeature::resolveElement(), Gui::RayPickInfo::subName, Gui::ViewProvider::useNewSelectionModel(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by Gui::View3DInventorPy::getObjectInfoRay().
getPyObject()
PyObject * View3DInventor::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Gui::MDIView.
Definition at line 188 of file View3DInventor.cpp.
getViewer()
View3DInventorViewer* Gui::View3DInventor::getViewer () const inline
Definition at line 122 of file View3DInventor.h.
Referenced by Gui::Document::_resetEdit(), Gui::View3DInventorPy::addEventCallback(), Gui::View3DInventorPy::addEventCallbackPivy(), Gui::View3DInventorPy::boxZoom(), SketcherGui::ViewProviderSketch::centerSelection(), StartGui::StartView::changeEvent(), Gui::Dialog::Clipping::Clipping(), Gui::Document::cloneView(), Gui::Document::createView(), Gui::Dialog::DlgSettingsGeneral::DlgSettingsGeneral(), AssemblyGui::ViewProviderAssembly::endMove(), MeshGui::MeshFaceAddition::finishEditing(), MeshGui::MeshFillHole::finishEditing(), Gui::View3DInventorPy::fitAll(), TechDrawGui::DrawGuiUtil::get3DDirAndRot(), FemGui::ViewProviderFemPostFunction::getBoundingsOfView(), Gui::View3DInventorPy::getCamera(), Gui::View3DInventorPy::getCameraNode(), Gui::View3DInventorPy::getCameraOrientation(), Gui::View3DInventorPy::getCameraType(), Gui::View3DInventorPy::getCornerCrossSize(), Gui::View3DInventorPy::getCursorPos(), Gui::View3DInventorPy::getNavigationType(), Gui::View3DInventorPy::getObjectInfo(), Gui::View3DInventorPy::getObjectsInfo(), getObjInfoRay(), Gui::View3DInventorPy::getPointOnFocalPlane(), Gui::View3DInventorPy::getPointOnViewport(), PartDesignGui::ViewProviderDatum::getRelevantBoundBox(), Gui::View3DInventorPy::getSceneGraph(), Gui::View3DInventorPy::getSize(), MeasureGui::ViewProviderMeasureBase::getTextDirection(), MeasureGui::ViewProviderMeasure::getTextPosition(), Gui::View3DInventorPy::getUpDirection(), Gui::View3DInventorPy::getViewDirection(), Gui::View3DInventorPy::getViewer(), Gui::View3DInventorPy::getViewProvidersOfType(), MeasureGui::ViewProviderMeasureBase::getViewScale(), Gui::View3DInventorPy::hasAxisCross(), Gui::View3DInventorPy::isAnimationEnabled(), Gui::View3DInventorPy::isCornerCrossVisible(), Gui::View3DInventorPy::isPopupMenuEnabled(), Gui::Dialog::DemoMode::onAngleSliderValueChanged(), Gui::Dialog::DemoMode::onAutoPlay(), SketcherGui::ViewProviderSketch::onCameraChanged(), onMsg(), Gui::Dialog::DemoMode::onPlayButtonToggled(), Gui::Dialog::DemoMode::onSpeedSliderValueChanged(), MeasureGui::ViewProviderMeasure::positionAnno(), Gui::View3DInventorPy::projectPointToLine(), TechDrawGui::Grabber3d::quickView(), Gui::Dialog::DlgSettingsGeneral::recreatePreferencePackMenu(), Gui::View3DInventorPy::redraw(), Gui::View3DInventorPy::removeEventCallback(), Gui::View3DInventorPy::removeEventCallbackPivy(), Gui::View3DInventorPy::saveImage(), Gui::View3DInventorPy::saveVectorGraphic(), Gui::View3DInventorPy::setAnimationEnabled(), Gui::Document::setAnnotationViewProvider(), Gui::View3DInventorPy::setAxisCross(), Gui::View3DInventorPy::setCameraOrientation(), Gui::View3DInventorPy::setCameraType(), Gui::View3DInventorPy::setCornerCrossSize(), Gui::View3DInventorPy::setCornerCrossVisible(), Gui::Document::setEditingTransform(), Gui::DocumentP::setEditingViewerIfPossible(), Gui::View3DInventorPy::setNavigationType(), Gui::View3DInventorPy::setPopupMenuEnabled(), Gui::View3DInventorPy::setStereoType(), Gui::View3DInventorPy::setViewDirection(), Gui::Document::slotDeletedObject(), Gui::Document::slotNewObject(), PartGui::BoxSelection::start(), Gui::View3DInventorPy::startAnimating(), MeshGui::MeshFaceAddition::startEditing(), Gui::View3DInventorPy::stopAnimating(), Gui::View3DInventorPy::toggleClippingPlane(), Gui::View3DInventorPy::viewBottom(), Gui::View3DInventorPy::viewDefaultOrientation(), Gui::View3DInventorPy::viewDimetric(), Gui::View3DInventorPy::viewFront(), Gui::View3DInventorPy::viewIsometric(), Gui::View3DInventorPy::viewLeft(), Gui::View3DInventorPy::viewPosition(), Gui::View3DInventorPy::viewRear(), Gui::View3DInventorPy::viewRight(), Gui::View3DInventorPy::viewRotateLeft(), Gui::View3DInventorPy::viewRotateRight(), Gui::View3DInventorPy::viewTop(), Gui::View3DInventorPy::viewTrimetric(), Gui::View3DInventorPy::zoomIn(), and Gui::View3DInventorPy::zoomOut().
hasClippingPlane()
bool View3DInventor::hasClippingPlane () const
Definition at line 610 of file View3DInventor.cpp.
References Gui::View3DInventorViewer::hasClippingPlane().
keyPressEvent()
void View3DInventor::keyPressEvent (QKeyEvent * e) override protected
Definition at line 892 of file View3DInventor.cpp.
References SCL.SimpleDataTypes::e.
keyReleaseEvent()
void View3DInventor::keyReleaseEvent (QKeyEvent * e) override protected
Definition at line 903 of file View3DInventor.cpp.
References SCL.SimpleDataTypes::e.
onHasMsg()
bool View3DInventor::onHasMsg (const char * pMsg) const override virtual
Message handler test.
Reimplemented from Gui::MDIView.
Definition at line 433 of file View3DInventor.cpp.
References toolbit-attributes::doc, and Gui::BaseView::getAppDocument().
onMsg()
bool View3DInventor::onMsg (const char * pMsg, const char ** ppReturn) override virtual
Message handler.
Reimplemented from Gui::MDIView.
Definition at line 303 of file View3DInventor.cpp.
References Gui::View3DInventorViewer::alignToSelection(), SIM::Coin3D::Quarter::QuarterWidget::ANAGLYPH, Gui::Camera::Bottom, dump(), Gui::Camera::Front, Gui::BaseView::getGuiDocument(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), getViewer(), SIM::Coin3D::Quarter::QuarterWidget::INTERLEAVED_COLUMNS, SIM::Coin3D::Quarter::QuarterWidget::INTERLEAVED_ROWS, Gui::Camera::Isometric, Gui::Camera::Left, SIM::Coin3D::Quarter::QuarterWidget::MONO, SIM::Coin3D::Quarter::QuarterWidget::QUAD_BUFFER, Gui::Camera::Rear, Gui::Document::redo(), Gui::Camera::Right, Gui::Camera::rotation(), Gui::Document::save(), Gui::Document::saveAs(), Gui::Document::saveCopy(), setCamera(), Gui::View3DInventorViewer::setCameraOrientation(), Gui::View3DInventorViewer::setCameraType(), SIM::Coin3D::Quarter::QuarterWidget::setStereoMode(), Gui::Camera::Top, Gui::Document::undo(), Gui::View3DInventorViewer::viewAll(), OfflineRenderingUtils::viewer(), Gui::View3DInventorViewer::viewSelection(), Gui::View3DInventorViewer::viewVR(), and Gui::SoFCDB::writeNodesToString().
onRename()
void View3DInventor::onRename (Gui::Document * pDoc) override virtual
get called when the document is updated
Reimplemented from Gui::BaseView.
Definition at line 207 of file View3DInventor.cpp.
References Gui::Document::getDocument(), App::Document::getName(), and SIM::Coin3D::Quarter::QuarterWidget::getSceneGraph().
onUpdate()
void View3DInventor::onUpdate () override virtual
get called when the document is updated
Reimplemented from Gui::BaseView.
Definition at line 215 of file View3DInventor.cpp.
References Base::Console(), Base::ConsoleSingleton::Log(), and SIM::Coin3D::Quarter::QuarterWidget::redraw().
print() [1/2]
void View3DInventor::print () override virtual
print function of the view
Reimplemented from Gui::MDIView.
Definition at line 234 of file View3DInventor.cpp.
References Gui::MDIView::restorePrinterSettings(), and Gui::MDIView::savePrinterSettings().
Referenced by printPdf(), and printPreview().
print() [2/2]
void View3DInventor::print (QPrinter * printer) override virtual
Reimplemented from Gui::MDIView.
Definition at line 277 of file View3DInventor.cpp.
References Gui::View3DInventorViewer::imageFromFramebuffer(), and buildPsets::p.
printPdf()
void View3DInventor::printPdf () override virtual
Print to PDF file
Reimplemented from Gui::MDIView.
Definition at line 248 of file View3DInventor.cpp.
References Gui::FileDialog::getSaveFileName(), and print().
printPreview()
void View3DInventor::printPreview () override virtual
Show a preview dialog
Reimplemented from Gui::MDIView.
Definition at line 264 of file View3DInventor.cpp.
References draftgeoutils.intersections::connect(), print(), Gui::MDIView::restorePrinterSettings(), and Gui::MDIView::savePrinterSettings().
removeOverlayWidget()
void View3DInventor::removeOverlayWidget ()
Definition at line 622 of file View3DInventor.cpp.
References nativeifc.ifc_viewproviders::overlay().
Referenced by setOverlayWidget().
restoreOverrideCursor
void View3DInventor::restoreOverrideCursor () override slot
Definition at line 634 of file View3DInventor.cpp.
References SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getWidget().
setCamera()
bool View3DInventor::setCamera (const char * pCamera)
Definition at line 538 of file View3DInventor.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), importers.import3DS::read(), and Gui::View3DInventorViewer::setCameraType().
Referenced by onMsg(), and Gui::View3DInventorPy::setCamera().
setCurrentViewMode()
void View3DInventor::setCurrentViewMode (ViewMode b) override virtual
If b is set to FullScreen the MDI view is displayed in full screen mode, if b is set to TopLevel then it is displayed as an own top-level window, otherwise (Normal) as tabbed window. This method is reimplemented from MDIView to set the this widget as the proxy of the embedded GL widget to get all key events in TopLevel or Fullscreen mode.
Reimplemented from Gui::MDIView.
Definition at line 719 of file View3DInventor.cpp.
References Gui::MDIView::Child, Gui::MDIView::currentViewMode(), SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getGLWidget(), Gui::getMainWindow(), and Gui::MDIView::setCurrentViewMode().
setOverlayWidget()
void View3DInventor::setOverlayWidget (QWidget * widget)
Definition at line 615 of file View3DInventor.cpp.
References removeOverlayWidget().
setOverrideCursor
void View3DInventor::setOverrideCursor (const QCursor & aCursor) override slot
override the cursor in this view
Definition at line 629 of file View3DInventor.cpp.
References SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getWidget().
stopAnimating
void View3DInventor::stopAnimating () protected slot
Definition at line 690 of file View3DInventor.cpp.
References Gui::View3DInventorViewer::stopAnimating().
Referenced by View3DInventor().
toggleClippingPlane()
void View3DInventor::toggleClippingPlane ()
Definition at line 605 of file View3DInventor.cpp.
References Gui::View3DInventorViewer::toggleClippingPlane().
viewAll()
void View3DInventor::viewAll () override virtual
Reimplemented from Gui::MDIView.
Definition at line 224 of file View3DInventor.cpp.
References Gui::View3DInventorViewer::viewAll().
windowStateChanged()
void View3DInventor::windowStateChanged (QWidget * view) override protected virtual
This method gets called from the main window this view is attached to whenever the window state of the active view changes. The default implementation does nothing.
Reimplemented from Gui::MDIView.
Definition at line 664 of file View3DInventor.cpp.
Friends And Related Function Documentation
View3DPy
friend class View3DPy friend
Definition at line 160 of file View3DInventor.h.
The documentation for this class was generated from the following files:
View3DInventor.h
View3DInventor.cpp