FreeCAD: Gui::SoVisibleFaceAction Class Reference
Gui::SoVisibleFaceAction Class Reference
#include <SoFCSelectionAction.h>
Public Member Functions
SoVisibleFaceAction ()
~SoVisibleFaceAction () override
void setHandled ()
SbBool isHandled () const
Static Public Member Functions
static void initClass ()
Protected Member Functions
void beginTraversal (SoNode *node) override
Detailed Description
Author
Werner Mayer
Definition at line 285 of file SoFCSelectionAction.h.
Constructor & Destructor Documentation
SoVisibleFaceAction()
SoVisibleFaceAction::SoVisibleFaceAction ()
Definition at line 836 of file SoFCSelectionAction.cpp.
~SoVisibleFaceAction()
SoVisibleFaceAction::~SoVisibleFaceAction () override default
Member Function Documentation
beginTraversal()
void SoVisibleFaceAction::beginTraversal (SoNode * node) override protected
Definition at line 843 of file SoFCSelectionAction.cpp.
initClass()
void SoVisibleFaceAction::initClass () static
The order of the defined SO_ACTION_ADD_METHOD statements is very important. First the base classes and afterwards subclasses of them must be listed, otherwise the registered methods of subclasses will be overridden. For more details see the thread in the Coin3d forum https://www.coin3d.org/pipermail/coin-discuss/2004-May/004346.html. This means that SoSwitch must be listed after SoGroup and SoFCSelection after SoSeparator because both classes inherits the others.
Definition at line 808 of file SoFCSelectionAction.cpp.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
isHandled()
SbBool SoVisibleFaceAction::isHandled () const
Definition at line 858 of file SoFCSelectionAction.cpp.
setHandled()
void SoVisibleFaceAction::setHandled ()
Definition at line 853 of file SoFCSelectionAction.cpp.
The documentation for this class was generated from the following files:
SoFCSelectionAction.h
SoFCSelectionAction.cpp