FreeCAD: AreaPocket.cpp File Reference
AreaPocket.cpp File Reference
#include "Area.h"
#include <map>
#include <set>
Classes
class IslandAndOffset
class CurveTree
class GetCurveItem
class IslandAndOffsetLink
Functions
static Point GetNearestPoint (CurveTree *curve_tree, std::list< CurveTree * > &islands_added, const CCurve &test_curve, CurveTree **best_curve_tree)
void recur (std::list< CArea > &arealist, const CArea &a1, const CAreaPocketParams &params, int level)
void MarkOverlappingOffsetIslands (std::list< IslandAndOffset > &offset_islands)
Variables
static const CAreaPocketParams * pocket_params = NULL
Function Documentation
GetNearestPoint()
static Point GetNearestPoint (CurveTree * curve_tree, std::list< CurveTree * > & islands_added, const CCurve & test_curve, CurveTree ** best_curve_tree) static
Definition at line 205 of file AreaPocket.cpp.
References CurveTree::curve, DraftVecUtils::dist(), CCurve::NearestPoint(), and buildPsets::p.
MarkOverlappingOffsetIslands()
void MarkOverlappingOffsetIslands (std::list< IslandAndOffset > & offset_islands)
Definition at line 501 of file AreaPocket.cpp.
References eCrossing, GetOverlapType(), IslandAndOffset::offset, and IslandAndOffset::touching_offsets.
Referenced by CArea::MakeOnePocketCurve().
recur()
void recur (std::list< CArea > & arealist, const CArea & a1, const CAreaPocketParams & params, int level)
Definition at line 440 of file AreaPocket.cpp.
References NavigationIndicatorGui::a1, NavigationIndicatorGui::a2, CArea::HolesLinked(), CCurve::IsClockwise(), level(), CArea::m_curves, CArea::Offset(), nativeifc.ifc_observer::params, and CArea::Reorder().
Referenced by CArea::MakeOnePocketCurve().
Variable Documentation
pocket_params
const CAreaPocketParams* pocket_params = NULL static
Definition at line 12 of file AreaPocket.cpp.
Referenced by IslandAndOffset::IslandAndOffset(), and CArea::MakeOnePocketCurve().