FreeCAD: FemGui::ViewProviderFEMMeshBuilder Class Reference
FemGui::ViewProviderFEMMeshBuilder Class Reference
#include <ViewProviderFemMesh.h>
Public Member Functions
ViewProviderFEMMeshBuilder ()=default
~ViewProviderFEMMeshBuilder () override=default
void buildNodes (const App::Property *, std::vector< SoNode * > &) const override
void createMesh (const App::Property *, SoCoordinate3 *, SoIndexedFaceSet *, SoIndexedLineSet *, std::vector< unsigned long > &, std::vector< unsigned long > &, bool &edgeOnly, bool ShowInner, int MaxFacesShowInner) const
Public Member Functions inherited from Gui::ViewProviderBuilder
ViewProviderBuilder ()
Constructor.
virtual ~ViewProviderBuilder ()
Additional Inherited Members
Static Public Member Functions inherited from Gui::ViewProviderBuilder
static void add (const Base::Type &, const Base::Type &)
static ViewProvider * create (const Base::Type &)
static SoFCSelection * createSelection ()
Detailed Description
Definition at line 42 of file ViewProviderFemMesh.h.
Constructor & Destructor Documentation
ViewProviderFEMMeshBuilder()
FemGui::ViewProviderFEMMeshBuilder::ViewProviderFEMMeshBuilder () default
~ViewProviderFEMMeshBuilder()
FemGui::ViewProviderFEMMeshBuilder::~ViewProviderFEMMeshBuilder () override default
Member Function Documentation
buildNodes()
void ViewProviderFEMMeshBuilder::buildNodes (const App::Property * prop, std::vector< SoNode * > & nodes) const override virtual
Implements Gui::ViewProviderBuilder.
Definition at line 875 of file ViewProviderFemMesh.cpp.
References createMesh().
createMesh()
void ViewProviderFEMMeshBuilder::createMesh (const App::Property * prop, SoCoordinate3 * coords, SoIndexedFaceSet * faces, SoIndexedLineSet * lines, std::vector< unsigned long > & vFaceElementIdx, std::vector< unsigned long > & vNodeElementIdx, bool & edgeOnly, bool ShowInner, int MaxFacesShowInner) const
Definition at line 930 of file ViewProviderFemMesh.cpp.
References Base::BoundBox3< Precision >::Add(), Base::BoundBox3< Precision >::CalcDiagonalLength(), Base::Console(), Base::TimeElapsed::diffTimeF(), ElemFold(), Base::BoundBox3< Precision >::Enlarge(), ArchFence::hide(), SplineSurface::i, Path.Log::info(), insEdgeVec(), RobotExample::l, Base::BoundBox3< Precision >::LengthX(), Base::BoundBox3< Precision >::LengthY(), Base::BoundBox3< Precision >::LengthZ(), Base::ConsoleSingleton::Log(), KDL::max(), Mesh2Shape::mesh, Base::BoundBox3< Precision >::MinX, Base::BoundBox3< Precision >::MinY, Base::BoundBox3< Precision >::MinZ, updateLeaderLines::point, Base::pow(), RobotExample::Start, MovieTool::x, and MovieTool::y.
Referenced by buildNodes(), FemGui::ViewProviderFemMesh::onChanged(), and FemGui::ViewProviderFemMesh::updateData().
The documentation for this class was generated from the following files:
ViewProviderFemMesh.h
ViewProviderFemMesh.cpp