FreeCAD: PartGui::TaskImportStep Class Reference
PartGui::TaskImportStep Class Reference
#include <DlgImportStep.h>
Public Member Functions
TaskImportStep (QWidget *parent=nullptr)
~TaskImportStep () override
bool showDialog () const
void accept () override
StepImportSettings getSettings () const
Detailed Description
Definition at line 72 of file DlgImportStep.h.
Constructor & Destructor Documentation
TaskImportStep()
TaskImportStep::TaskImportStep (QWidget * parent = nullptr) explicit
Definition at line 135 of file DlgImportStep.cpp.
References accept(), and draftgeoutils.intersections::connect().
~TaskImportStep()
TaskImportStep::~TaskImportStep () override
Definition at line 160 of file DlgImportStep.cpp.
Member Function Documentation
accept()
void TaskImportStep::accept () override
Definition at line 165 of file DlgImportStep.cpp.
References Part::STEP::ImportExportSettings::setVisibleImportDialog().
Referenced by TaskImportStep().
getSettings()
StepImportSettings TaskImportStep::getSettings () const
Definition at line 180 of file DlgImportStep.cpp.
Referenced by ImportGui::Module::Module().
showDialog()
bool TaskImportStep::showDialog () const
Definition at line 174 of file DlgImportStep.cpp.
References Part::STEP::ImportExportSettings::isVisibleImportDialog().
Referenced by ImportGui::Module::Module().
The documentation for this class was generated from the following files:
DlgImportStep.h
DlgImportStep.cpp