FreeCAD: TechDraw::DrawBrokenView Class Reference
TechDraw::DrawBrokenView Class Reference
#include <DrawBrokenView.h>
Public Types
enum BreakType { NONE, ZIGZAG, SIMPLE }
Public Types inherited from App::DocumentObject
enum OutListOption { OutListNoExpression = 1, OutListNoHidden = 2, OutListNoXLinked = 4 }
OutList options.
enum GSReason { GS_DEFAULT, GS_SELECT }
reason of calling getSubObjects()
Public Types inherited from App::ExtensionContainer
using ExtensionIterator = std::map< Base::Type, App::Extension * >::iterator
Public Member Functions
DrawBrokenView ()
~DrawBrokenView () override
App::DocumentObjectExecReturn * execute () override
short mustExecute () const override
PyObject * getPyObject (void) override
const char * getViewProviderName () const override
returns the type name of the ViewProvider
std::pair< Base::Vector3d, Base::Vector3d > breakPointsFromObj (const App::DocumentObject &breakObj) const
extract the break points from the break object.
std::pair< Base::Vector3d, Base::Vector3d > breakBoundsFromObj (const App::DocumentObject &breakObj) const
determine the rectangle to be occupied by the break lines. used by gui.
Base::Vector3d directionFromObj (const App::DocumentObject &breakObj) const
Base::Vector3d guiDirectionFromObj (const App::DocumentObject &breakObj) const
extract the breakDirection from the break object in a form the gui will understand.
Base::Vector3d mapPoint3dToView (Base::Vector3d point3d) const
Base::Vector3d mapPoint2dFromView (Base::Vector3d point2d) const
Base::Vector3d getCompressedCentroid () const
double breaklineLength (const App::DocumentObject &breakObj) const
calculate the unscaled length of the breakline
Public Member Functions inherited from TechDraw::DrawViewPart
DrawViewPart ()
~DrawViewPart () override
short mustExecute () const override
App::DocumentObjectExecReturn * execute () override
recalculate the Feature
const char * getViewProviderName () const override
returns the type name of the ViewProvider
PyObject * getPyObject () override
std::vector< TechDraw::DrawHatch * > getHatches () const
std::vector< TechDraw::DrawGeomHatch * > getGeomHatches () const
std::vector< TechDraw::DrawViewDimension * > getDimensions () const
std::vector< TechDraw::DrawViewBalloon * > getBalloons () const
virtual std::vector< DrawViewSection * > getSectionRefs () const
virtual std::vector< DrawViewDetail * > getDetailRefs () const
const std::vector< TechDraw::VertexPtr > getVertexGeometry () const
const BaseGeomPtrVector getEdgeGeometry () const
const BaseGeomPtrVector getVisibleFaceEdges () const
const std::vector< TechDraw::FacePtr > getFaceGeometry () const
bool hasGeometry () const
TechDraw::GeometryObjectPtr getGeometryObject () const
TechDraw::VertexPtr getVertex (std::string vertexName) const
TechDraw vertex names run from 0 to n-1.
TechDraw::BaseGeomPtr getEdge (std::string edgeName) const
TechDraw::FacePtr getFace (std::string faceName) const
TechDraw::BaseGeomPtr getGeomByIndex (int idx) const
returns existing BaseGeom of 2D Edge(idx)
TechDraw::VertexPtr getProjVertexByIndex (int idx) const
returns existing geometry of 2D Vertex(idx)
TechDraw::VertexPtr getProjVertexByCosTag (std::string cosTag)
std::vector< TechDraw::BaseGeomPtr > getFaceEdgesByIndex (int idx) const
returns existing geometry of 2D Face(idx)
virtual std::vector< TopoDS_Wire > getWireForFace (int idx) const
TopoDS_Shape getEdgeCompound () const
virtual Base::BoundBox3d getBoundingBox () const
double getBoxX () const
double getBoxY () const
QRectF getRect () const override
double getSizeAlongVector (Base::Vector3d alignmentVector)
virtual Base::Vector3d projectPoint (const Base::Vector3d &pt, bool invert=true) const
virtual BaseGeomPtr projectEdge (const TopoDS_Edge &e) const
virtual gp_Ax2 getViewAxis (const Base::Vector3d &pt, const Base::Vector3d &direction, const bool flip=true) const
virtual gp_Ax2 getProjectionCS (Base::Vector3d pt=Base::Vector3d(0.0, 0.0, 0.0)) const
virtual gp_Ax2 getRotatedCS (Base::Vector3d basePoint=Base::Vector3d(0.0, 0.0, 0.0)) const
virtual Base::Vector3d getXDirection () const
virtual Base::Vector3d getOriginalCentroid () const
virtual Base::Vector3d getCurrentCentroid () const
virtual Base::Vector3d getLegacyX (const Base::Vector3d &pt, const Base::Vector3d &axis, const bool flip=true) const
void rotate (const std::string &rotationdirection)
void spin (const std::string &spindirection)
void spin (double val)
std::pair< Base::Vector3d, Base::Vector3d > getDirsFromFront (std::string viewType)
Base::Vector3d dir2vec (gp_Dir d)
gp_Ax2 localVectorToCS (const Base::Vector3d localUnit) const
Base::Vector3d localVectorToDirection (const Base::Vector3d localUnit) const
bool handleFaces ()
bool newFaceFinder ()
bool isUnsetting ()
virtual TopoDS_Shape getSourceShape (bool fuse=false) const
virtual TopoDS_Shape getShapeForDetail () const
std::vector< App::DocumentObject * > getAllSources () const
combine the regular links and xlinks into a single list
void dumpVerts (const std::string text)
void dumpCosVerts (const std::string text)
void dumpCosEdges (const std::string text)
std::string addReferenceVertex (Base::Vector3d v)
void addReferencesToGeom ()
void removeReferenceVertex (std::string tag)
void updateReferenceVert (std::string tag, Base::Vector3d loc2d)
void removeAllReferencesFromGeom ()
remove reference vertexes from the view geometry
void resetReferenceVerts ()
virtual void postHlrTasks (void)
run any tasks that need to been done after geometry is available
virtual void postFaceExtractionTasks (void)
bool waitingForFaces () const
void waitingForFaces (bool s)
bool waitingForHlr () const
void waitingForHlr (bool s)
virtual bool waitingForResult () const
void progressValueChanged (int v)
Public Member Functions inherited from TechDraw::DrawView
DrawView ()
Constructor.
~DrawView () override
void onDocumentRestored () override
get called after a document has been fully restored
void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, App::Property *prop) override
bool isInClip ()
DrawViewClip * getClipGroup ()
DrawViewCollection * getCollection () const
virtual DrawPage * findParentPage () const
virtual std::vector< DrawPage * > findAllParentPages () const
virtual DrawView * claimParent () const
virtual int countParentPages () const
DrawView::countParentPages Fixes a crash in TechDraw when user creates duplicate page without dependencies In fixOrphans() we check how many parent pages an object has before deleting in case it is also a child of another duplicate page.
QRectF getRectAligned () const
virtual double autoScale () const
virtual double autoScale (double w, double h) const
virtual bool checkFit () const
virtual bool checkFit (DrawPage *) const
check if View is too big for page
virtual void setPosition (double x, double y, bool force=false)
virtual Base::Vector3d getPosition () const
virtual bool keepUpdated (void)
void requestPaint (void)
void showProgressMessage (std::string featureName, std::string text)
virtual double getScale (void) const
virtual int getScaleType () const
void checkScale (void)
virtual void handleXYLock (void)
virtual bool isLocked (void) const
virtual bool showLock (void) const
std::vector< TechDraw::DrawLeaderLine * > getLeaders (void) const
void setScaleAttribute ()
void overrideKeepUpdated (bool s)
bool overrideKeepUpdated (void)
void translateLabel (std::string context, std::string baseName, std::string uniqueName)
virtual App::PropertyLink * getOwnerProperty ()
Public Member Functions inherited from App::DocumentObject
virtual const char * getViewProviderNameOverride () const
DocumentObject ()
Constructor.
~DocumentObject () override
const char * getDagKey () const
returns a value that uniquely identifies this DocumentObject.
const char * getNameInDocument () const
returns the name which is set in the document for this object (not the name property!)
long getID () const
Return the object ID that is unique within its owner document.
std::string getExportName (bool forced=false) const
returns the name that is safe to be exported to other document
std::string getFullName () const override
Return the object full name of the form DocName::ObjName.
std::string getFullLabel () const
Return the object full label in the form DocName::ObjName.
bool isAttachedToDocument () const override
const char * detachFromDocument () override
App::Document * getDocument () const
gets the document in which this Object is handled
void touch (bool noRecompute=false)
set this document object touched (cause recomputation on dependent features)
bool isTouched () const
test if this document object is touched
void enforceRecompute ()
Enforce this document object to be recomputed.
bool mustRecompute () const
Test if this document object must be recomputed.
void purgeTouched ()
reset this document object touched
bool isError () const
set this feature to error
bool isValid () const
void purgeError ()
remove the error from the object
bool isRecomputing () const
returns true if this objects is currently recomputing
bool isRestoring () const
returns true if this objects is currently restoring from file
bool isRemoving () const
returns true if this objects is currently removed from the document
void freeze ()
set this document object freezed (prevent recomputation)
void unfreeze (bool noRecompute=false)
set this document object unfreezed (and touch it)
bool isFreezed () const
returns true if this objects is currently freezed
unsigned long getStatus () const
return the status bits
bool testStatus (ObjectStatus pos) const
void setStatus (ObjectStatus pos, bool on)
int isExporting () const
virtual int setElementVisible (const char *element, bool visible)
virtual int isElementVisible (const char *element) const
virtual bool hasChildElement () const
return true to activate tree view group object handling and element visibility
const std::vector< App::DocumentObject * > & getOutList () const
returns a list of objects this object is pointing to by Links
std::vector< App::DocumentObject * > getOutList (int option) const
void getOutList (int option, std::vector< App::DocumentObject * > &res) const
std::vector< App::DocumentObject * > getOutListOfProperty (App::Property *) const
returns a list of objects linked by the property
std::vector< App::DocumentObject * > getOutListRecursive () const
returns a list of objects this object is pointing to by Links and all further descended
void clearOutListCache () const
clear internal out list cache
std::vector< std::list< App::DocumentObject * > > getPathsByOutList (App::DocumentObject *to) const
get all possible paths from this to another object following the OutList
const std::vector< App::DocumentObject * > & getInList () const
std::vector< App::DocumentObject * > getInListRecursive () const
get all objects link directly or indirectly to this object
void getInListEx (std::set< App::DocumentObject * > &inSet, bool recursive, std::vector< App::DocumentObject * > *inList=nullptr) const
std::set< App::DocumentObject * > getInListEx (bool recursive) const
DocumentObjectGroup * getGroup () const
get group if object is part of a group, otherwise 0 is returned
bool isInInListRecursive (DocumentObject *objToTest) const
test if this object is in the InList and recursive further down
bool isInInList (DocumentObject *objToTest) const
test if this object is directly (non recursive) in the InList
bool isInOutListRecursive (DocumentObject *objToTest) const
test if the given object is in the OutList and recursive further down
bool isInOutList (DocumentObject *objToTest) const
test if this object is directly (non recursive) in the OutList
void _removeBackLink (DocumentObject *)
internal, used by PropertyLink to maintain DAG back links
void _addBackLink (DocumentObject *)
internal, used by PropertyLink to maintain DAG back links
bool testIfLinkDAGCompatible (DocumentObject *linkTo) const
testIfLinkIsDAG tests a link that is about to be created for circular references.
bool testIfLinkDAGCompatible (const std::vector< DocumentObject * > &linksTo) const
bool testIfLinkDAGCompatible (App::PropertyLinkSubList &linksTo) const
bool testIfLinkDAGCompatible (App::PropertyLinkSub &linkTo) const
virtual std::string getElementMapVersion (const App::Property *prop, bool restored=false) const
virtual bool checkElementMapVersion (const App::Property *prop, const char *ver) const
Return true to signal re-generation of geometry element names.
bool recomputeFeature (bool recursive=false)
const char * getStatusString () const
get the status Message
virtual void onLostLinkToObject (DocumentObject *)
virtual DocumentObject * getSubObject (const char *subname, PyObject **pyObj=nullptr, Base::Matrix4D *mat=nullptr, bool transform=true, int depth=0) const
std::vector< DocumentObject * > getSubObjectList (const char *subname, std::vector< int > *subsizes=nullptr, bool flatten=false) const
virtual std::vector< std::string > getSubObjects (int reason=0) const
std::vector< std::pair< App::DocumentObject *, std::string > > getParents (int depth=0) const
Obtain top parents and subnames of this object using its InList.
App::DocumentObject * getFirstParent () const
Obtain the first parent group of this object.
virtual DocumentObject * getLinkedObject (bool recurse=true, Base::Matrix4D *mat=nullptr, bool transform=false, int depth=0) const
virtual bool canLinkProperties () const
virtual bool isLink () const
virtual bool isLinkGroup () const
virtual bool allowDuplicateLabel () const
virtual void onBeforeChangeLabel (std::string &newLabel)
void Save (Base::Writer &writer) const override
virtual void setExpression (const ObjectIdentifier &path, std::shared_ptr< App::Expression > expr)
void clearExpression (const ObjectIdentifier &path)
virtual const PropertyExpressionEngine::ExpressionInfo getExpression (const ObjectIdentifier &path) const
virtual void renameObjectIdentifiers (const std::map< App::ObjectIdentifier, App::ObjectIdentifier > &paths)
const std::string & getOldLabel () const
const char * getViewProviderNameStored () const
bool removeDynamicProperty (const char *prop) override
App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false) override
App::DocumentObject * resolve (const char *subname, App::DocumentObject **parent=nullptr, std::string *childName=nullptr, const char **subElement=nullptr, PyObject **pyObj=nullptr, Base::Matrix4D *mat=nullptr, bool transform=true, int depth=0) const
App::DocumentObject * resolveRelativeLink (std::string &subname, App::DocumentObject *&link, std::string &linkSub) const
virtual bool adjustRelativeLinks (const std::set< App::DocumentObject * > &inList, std::set< App::DocumentObject * > *visited=nullptr)
virtual int canLoadPartial () const
virtual void onUpdateElementReference (const Property *)
virtual bool redirectSubName (std::ostringstream &ss, DocumentObject *topParent, DocumentObject *child) const
Public Member Functions inherited from App::TransactionalObject
TransactionalObject ()
Constructor.
~TransactionalObject () override
Public Member Functions inherited from App::ExtensionContainer
ExtensionContainer ()
~ExtensionContainer () override
void registerExtension (Base::Type extension, App::Extension *ext)
bool hasExtension (Base::Type, bool derived=true) const
bool hasExtension (const std::string &name) const
bool hasExtensions () const
App::Extension * getExtension (Base::Type, bool derived=true, bool no_except=false) const
App::Extension * getExtension (const std::string &name) const
template<typename ExtensionT >
ExtensionT * getExtension () const
template<typename ExtensionT >
ExtensionT * getExtensionByType (bool no_except=false, bool derived=true) const
std::vector< Extension * > getExtensionsDerivedFrom (Base::Type type) const
template<typename ExtensionT >
std::vector< ExtensionT * > getExtensionsDerivedFromType () const
ExtensionIterator extensionBegin ()
ExtensionIterator extensionEnd ()
Property * getPropertyByName (const char *name) const override
find a property by its name
template<typename T >
T * getPropertyByName (const char *name) const
find a property by its name, dynamic cased to specified type
const char * getPropertyName (const Property *prop) const override
get the name of a property
void getPropertyMap (std::map< std::string, Property * > &Map) const override
get all properties of the class (including properties of the parent)
void getPropertyList (std::vector< Property * > &List) const override
get all properties of the class (including properties of the parent)
short getPropertyType (const Property *prop) const override
get the Type of a Property
short getPropertyType (const char *name) const override
get the Type of a named Property
const char * getPropertyGroup (const Property *prop) const override
get the Group of a Property
const char * getPropertyGroup (const char *name) const override
get the Group of a named Property
const char * getPropertyDocumentation (const Property *prop) const override
get the Group of a Property
const char * getPropertyDocumentation (const char *name) const override
get the Group of a named Property
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
void saveExtensions (Base::Writer &writer) const
void restoreExtensions (Base::XMLReader &reader)
void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName) override
Public Member Functions inherited from App::PropertyContainer
PropertyContainer ()
~PropertyContainer () override
unsigned int getMemSize () const override
virtual void getPropertyNamedList (std::vector< std::pair< const char *, Property * > > &List) const
get all properties with their names, may contain duplicates and aliases
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
bool isReadOnly (const Property *prop) const
check if the property is read-only
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isHidden (const Property *prop) const
check if the property is hidden
bool isHidden (const char *name) const
check if the named property is hidden
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
bool changeDynamicProperty (const Property *prop, const char *group, const char *doc)
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual App::Property * getDynamicPropertyByName (const char *name) const
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
virtual void beforeSave () const
virtual void editProperty (const char *)
const char * getPropertyPrefix () const
void setPropertyPrefix (const char *prefix)
PropertyContainer (const PropertyContainer &)=delete
PropertyContainer & operator= (const PropertyContainer &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from TechDraw::CosmeticExtension
CosmeticExtension ()
~CosmeticExtension () override
virtual CosmeticVertex * getCosmeticVertexBySelection (const int i) const
retrieve a cosmetic vertex by index (the 5 in Vertex5)
virtual CosmeticVertex * getCosmeticVertexBySelection (const std::string &name) const
virtual CosmeticVertex * getCosmeticVertex (const std::string &tag) const
retrieve a cosmetic vertex by unique id
virtual int add1CVToGV (const std::string &tag)
add a single cosmetic vertex in the property list to the view's vertex geometry list
virtual int getCVIndex (const std::string &tag)
find the position of a cosmetic vertex with the given tag in the parent view's geometry list
virtual std::string addCosmeticVertex (const Base::Vector3d &pos, bool invert=true)
virtual void addCosmeticVertexesToGeom ()
add the cosmetic verts in the property list to view's vertex geometry list
virtual void clearCosmeticVertexes ()
remove all the cosmetic vertices in the property list
virtual void refreshCVGeoms ()
update the parent view's vertex geometry with all the cosmetic vertices in the list property
virtual void removeCosmeticVertex (const std::string &tag)
remove the cosmetic vertex with the given tag from the list property
virtual void removeCosmeticVertex (const std::vector< std::string > &tags)
remove the cosmetic vertices with the given tags from the list property
virtual std::string addCosmeticEdge (Base::Vector3d start, Base::Vector3d end)
virtual std::string addCosmeticEdge (TechDraw::BaseGeomPtr bg)
virtual CosmeticEdge * getCosmeticEdgeBySelection (const std::string &name) const
virtual CosmeticEdge * getCosmeticEdgeBySelection (int i) const
find the cosmetic edge corresponding to the input parameter (the 5 in Edge5)
virtual CosmeticEdge * getCosmeticEdge (const std::string &id) const
retrieve a CE by unique id
virtual void removeCosmeticEdge (const std::string &tag)
remove the cosmetic edge with the given tag from the list property
virtual void removeCosmeticEdge (const std::vector< std::string > &delTags)
remove the cosmetic edges with the given tags from the list property
virtual void clearCosmeticEdges ()
remove all the cosmetic edges for this view
virtual int add1CEToGE (const std::string &tag)
add a single cosmetic edge to the geometry edge list
virtual void addCosmeticEdgesToGeom ()
add the cosmetic edges to geometry edge list
virtual void refreshCEGeoms ()
update Edge geometry with current CE's
virtual void refreshCLGeoms ()
virtual void addCenterLinesToGeom ()
virtual int add1CLToGE (const std::string &tag)
virtual std::string addCenterLine (Base::Vector3d start, Base::Vector3d end)
virtual std::string addCenterLine (TechDraw::CenterLine *cl)
virtual std::string addCenterLine (TechDraw::BaseGeomPtr bg)
virtual CenterLine * getCenterLineBySelection (const std::string &name) const
virtual CenterLine * getCenterLineBySelection (int i) const
virtual CenterLine * getCenterLine (const std::string &tag) const
virtual void removeCenterLine (const std::string &tag)
virtual void removeCenterLine (const std::vector< std::string > &delTags)
virtual void clearCenterLines ()
virtual std::string addGeomFormat (TechDraw::GeomFormat *gf)
virtual GeomFormat * getGeomFormatBySelection (const std::string &name) const
virtual GeomFormat * getGeomFormatBySelection (int i) const
virtual GeomFormat * getGeomFormat (const std::string &id) const
virtual void removeGeomFormat (const std::string &tag)
virtual void clearGeomFormats ()
void deleteCosmeticElements (std::vector< std::string > removables)
remove cosmetic elements for a list of subelement names
TechDraw::DrawViewPart * getOwner ()
get a pointer to the parent view
PyObject * getExtensionPyObject () override
Public Member Functions inherited from App::DocumentObjectExtension
virtual Base::Type getExtensionTypeId (void) const override
DocumentObjectExtension ()
~DocumentObjectExtension () override
App::DocumentObject * getExtendedObject ()
const App::DocumentObject * getExtendedObject () const
virtual short extensionMustExecute ()
virtual App::DocumentObjectExecReturn * extensionExecute ()
virtual void onExtendedSettingDocument ()
get called after setting the document
virtual void onExtendedDocumentRestored ()
get called after a document has been fully restored
virtual void onExtendedSetupObject ()
get called after a brand new object was created
virtual void onExtendedUnsetupObject ()
get called when object is going to be removed from the document
virtual const char * getViewProviderExtensionName () const
virtual bool extensionGetSubObject (DocumentObject *&ret, const char *subname, PyObject **pyObj, Base::Matrix4D *mat, bool transform, int depth) const
virtual bool extensionGetSubObjects (std::vector< std::string > &ret, int reason) const
virtual bool extensionGetLinkedObject (DocumentObject *&ret, bool recursive, Base::Matrix4D *mat, bool transform, int depth) const
virtual int extensionSetElementVisible (const char *, bool)
virtual int extensionIsElementVisible (const char *)
virtual bool extensionHasChildElement () const
Public Member Functions inherited from App::Extension
Extension ()=default
virtual ~Extension ()
virtual void initExtension (App::ExtensionContainer *obj)
App::ExtensionContainer * getExtendedContainer ()
const App::ExtensionContainer * getExtendedContainer () const
std::string name () const
bool isPythonExtension ()
virtual Property * extensionGetPropertyByName (const char *name) const
find a property by its name
virtual const char * extensionGetPropertyName (const Property *prop) const
get the name of a property
virtual void extensionGetPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual void extensionGetPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual short extensionGetPropertyType (const Property *prop) const
get the Type of a Property
virtual short extensionGetPropertyType (const char *name) const
get the Type of a named Property
virtual const char * extensionGetPropertyGroup (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * extensionGetPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual void extensionSave (Base::Writer &) const
virtual void extensionRestore (Base::XMLReader &)
bool extensionIsDerivedFrom (const Base::Type type) const
Static Public Member Functions
static bool isBreakObject (const App::DocumentObject &breakObj)
determine if a given object can be used as a break object
static bool isBreakObjectSketch (const App::DocumentObject &breakObj)
static std::vector< App::DocumentObject * > removeBreakObjects (std::vector< App::DocumentObject * > breaks, std::vector< App::DocumentObject * > shapes)
static std::vector< TopoDS_Edge > edgesFromCompound (TopoDS_Shape compound)
Static Public Member Functions inherited from TechDraw::DrawViewPart
static TopoDS_Shape centerScaleRotate (const DrawViewPart *dvp, TopoDS_Shape &inOutShape, Base::Vector3d centroid)
Modify a shape by centering, scaling and rotating and return the centered (but not rotated) shape.
Static Public Member Functions inherited from TechDraw::DrawView
static bool isProjGroupItem (DrawViewPart *item)
Static Public Member Functions inherited from App::DocumentObject
static const std::string & hiddenMarker ()
static const char * hasHiddenMarker (const char *subname)
Check if the subname reference ends with hidden marker.
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Public Member Functions inherited from App::DocumentObjectExtension
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Static Public Member Functions inherited from App::Extension
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Public Attributes
App::PropertyLinkList Breaks
App::PropertyLength Gap
Public Attributes inherited from TechDraw::DrawViewPart
App::PropertyLinkList Source
App::PropertyXLinkList XSource
App::PropertyVector Direction
App::PropertyVector XDirection
App::PropertyBool Perspective
App::PropertyDistance Focus
App::PropertyBool CoarseView
App::PropertyBool SeamVisible
App::PropertyBool SmoothVisible
App::PropertyBool IsoVisible
App::PropertyBool HardHidden
App::PropertyBool SmoothHidden
App::PropertyBool SeamHidden
App::PropertyBool IsoHidden
App::PropertyInteger IsoCount
App::PropertyInteger ScrubCount
Public Attributes inherited from TechDraw::DrawView
App::PropertyDistance X
App::PropertyDistance Y
App::PropertyBool LockPosition
App::PropertyFloatConstraint Scale
App::PropertyEnumeration ScaleType
App::PropertyAngle Rotation
App::PropertyString Caption
boost::signals2::signal< void(const DrawView *)> signalGuiPaint
boost::signals2::signal< void(const DrawView *, std::string, std::string)> signalProgressMessage
Public Attributes inherited from App::DocumentObject
PropertyString Label
PropertyString Label2
PropertyExpressionEngine ExpressionEngine
PropertyBool Visibility
Allow control visibility status in App name space.
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalBeforeChange
signal before changing a property of this object
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalChanged
signal on changed property of this object
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalEarlyChanged
signal on changed property of this object before document scoped signalChangedObject
Public Attributes inherited from TechDraw::CosmeticExtension
TechDraw::PropertyCosmeticVertexList CosmeticVertexes
TechDraw::PropertyCosmeticEdgeList CosmeticEdges
TechDraw::PropertyCenterLineList CenterLines
TechDraw::PropertyGeomFormatList GeomFormats
Static Public Attributes
static const char * BreakTypeEnums []
Static Public Attributes inherited from App::DocumentObject
static DocumentObjectExecReturn * StdReturn
Additional Inherited Members
Public Slots inherited from TechDraw::DrawViewPart
void onHlrFinished (void)
continue processing after hlr thread completes
void onFacesFinished (void)
Protected Member Functions inherited from TechDraw::DrawViewPart
bool checkXDirection () const
void onChanged (const App::Property *prop) override
get called by the container when a property was changed
void unsetupObject () override
virtual TechDraw::GeometryObjectPtr buildGeometryObject (TopoDS_Shape &shape, const gp_Ax2 &viewAxis)
create a geometry object and trigger the HLR process in another thread
virtual TechDraw::GeometryObjectPtr makeGeometryForShape (TopoDS_Shape &shape)
prepare the shape for HLR processing by centering, scaling and rotating it
void partExec (TopoDS_Shape &shape)
virtual void addPoints (void)
void extractFaces ()
make faces from the edge geometry
void findFacesNew (const std::vector< TechDraw::BaseGeomPtr > &goEdges)
void findFacesOld (const std::vector< TechDraw::BaseGeomPtr > &goEdges)
Protected Member Functions inherited from TechDraw::DrawView
void onBeforeChange (const App::Property *prop) override
get called before the value is changed
virtual void validateScale ()
int prefScaleType ()
double prefScale ()
void touchTreeOwner (App::DocumentObject *owner) const
Protected Member Functions inherited from App::DocumentObject
virtual App::DocumentObjectExecReturn * recompute ()
recompute only this object
App::DocumentObjectExecReturn * executeExtensions ()
void setError ()
void resetError ()
void setDocument (App::Document *doc)
void onEarlyChange (const Property *prop) override
get called by the container when a property was changed
virtual void onUndoRedoFinished ()
get called after an undo/redo transaction is finished
virtual void onSettingDocument ()
get called after setting the document
virtual void setupObject ()
get called after a brand new object was created
void onPropertyStatusChanged (const Property &prop, unsigned long oldStatus) override
get called when a property status has changed
Protected Member Functions inherited from App::TransactionalObject
void onBeforeChangeProperty (Document *doc, const Property *prop)
Protected Member Functions inherited from App::PropertyContainer
virtual const PropertyData & getPropertyData () const
Protected Member Functions inherited from App::DocumentObjectExtension
virtual const App::PropertyData & extensionGetPropertyData (void) const override
Protected Member Functions inherited from App::Extension
virtual void extensionOnChanged (const Property *p)
virtual bool extensionHandleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
returns true if the property name change was handled by the extension.
virtual bool extensionHandleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop)
returns true if the property type change was handled by the extension.
void initExtensionType (Base::Type type)
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Static Protected Member Functions inherited from App::DocumentObjectExtension
static const App::PropertyData * extensionGetPropertyDataPtr (void)
Static Protected Member Functions inherited from App::Extension
static const App::PropertyData * extensionGetPropertyDataPtr (void)
static void initExtensionSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Base::Type::instantiationMethod method=nullptr)
Protected Attributes inherited from TechDraw::DrawViewPart
TechDraw::GeometryObjectPtr geometryObject
TechDraw::GeometryObjectPtr m_tempGeometryObject
Base::BoundBox3d bbox
Base::Vector3d shapeCentroid
bool m_handleFaces
TopoDS_Shape m_saveShape
Base::Vector3d m_saveCentroid
std::vector< TechDraw::VertexPtr > m_referenceVerts
Protected Attributes inherited from TechDraw::DrawView
std::string pageFeatName
bool autoPos
bool mouseMove
Protected Attributes inherited from App::DocumentObject
std::bitset< 32 > StatusBits
Py::SmartPtr PythonObject
python object of this class and all descendent
App::Document * _pDoc {nullptr}
pointer to the document this object belongs to
std::string oldLabel
Old label; used for renaming expressions.
const std::string * pcNameInDocument {nullptr}
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Protected Attributes inherited from App::Extension
bool m_isPythonExtension = false
Py::SmartPtr ExtensionPythonObject
Detailed Description
Definition at line 78 of file DrawBrokenView.h.
Member Enumeration Documentation
BreakType
enum TechDraw::DrawBrokenView::BreakType
Enumerator
NONE
ZIGZAG
SIMPLE
Definition at line 83 of file DrawBrokenView.h.
Constructor & Destructor Documentation
DrawBrokenView()
DrawBrokenView::DrawBrokenView ()
Definition at line 108 of file DrawBrokenView.cpp.
References ADD_PROPERTY_TYPE, App::Global, and App::Prop_None.
~DrawBrokenView()
DrawBrokenView::~DrawBrokenView () override
Definition at line 122 of file DrawBrokenView.cpp.
Member Function Documentation
breakBoundsFromObj()
std::pair< Base::Vector3d, Base::Vector3d > DrawBrokenView::breakBoundsFromObj (const App::DocumentObject & breakObj) const
determine the rectangle to be occupied by the break lines. used by gui.
Definition at line 507 of file DrawBrokenView.cpp.
References TechDraw::ShapeExtractor::getLocatedShape(), and TechDraw::ShapeExtractor::isSketchObject().
breaklineLength()
double DrawBrokenView::breaklineLength (const App::DocumentObject & breakObj) const
calculate the unscaled length of the breakline
Definition at line 594 of file DrawBrokenView.cpp.
References TechDraw::ShapeExtractor::getLocatedShape(), and TechDraw::ShapeExtractor::isSketchObject().
breakPointsFromObj()
std::pair< Base::Vector3d, Base::Vector3d > DrawBrokenView::breakPointsFromObj (const App::DocumentObject & breakObj) const
extract the break points from the break object.
Definition at line 351 of file DrawBrokenView.cpp.
References TechDraw::ShapeExtractor::getLocatedShape(), and TechDraw::ShapeExtractor::isSketchObject().
Referenced by directionFromObj().
directionFromObj()
Base::Vector3d DrawBrokenView::directionFromObj (const App::DocumentObject & breakObj) const
extract the breakDirection from the break object. The break direction is perpendicular to the break lines.
Definition at line 368 of file DrawBrokenView.cpp.
References breakPointsFromObj(), TechDraw::DrawUtil::closestBasis(), and Base::Vector3< float_type >::Normalize().
Referenced by guiDirectionFromObj().
edgesFromCompound()
std::vector< TopoDS_Edge > DrawBrokenView::edgesFromCompound (TopoDS_Shape compound) static
Definition at line 751 of file DrawBrokenView.cpp.
execute()
App::DocumentObjectExecReturn * DrawBrokenView::execute () override virtual
get called by the document to recompute this feature Normally this method get called in the processing of Document::recompute(). In execute() the output properties get recomputed with the data from linked objects and objects own properties.
Reimplemented from App::DocumentObject.
Definition at line 141 of file DrawBrokenView.cpp.
References Base::Console(), TechDraw::DrawView::execute(), TechDraw::ShapeUtils::findCentroidVec(), App::DocumentObject::getNameInDocument(), TechDraw::DrawViewPart::getProjectionCS(), TechDraw::DrawViewPart::getSourceShape(), TechDraw::DrawView::keepUpdated(), Base::ConsoleSingleton::Message(), TechDraw::DrawViewPart::partExec(), App::DocumentObject::StdReturn, and TechDraw::DrawViewPart::waitingForResult().
Referenced by FeaturePython.DistanceBolt::onChanged().
getCompressedCentroid()
Base::Vector3d DrawBrokenView::getCompressedCentroid () const
Definition at line 1236 of file DrawBrokenView.cpp.
References TechDraw::ShapeUtils::findCentroid(), TechDraw::DrawViewPart::getProjectionCS(), and TechDraw::DrawUtil::toVector3d().
Referenced by mapPoint2dFromView(), and mapPoint3dToView().
getPyObject()
PyObject * DrawBrokenView::getPyObject (void) override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from App::DocumentObject.
Definition at line 1315 of file DrawBrokenView.cpp.
References Py::SmartPtr::is(), Py::new_reference_to(), and App::DocumentObject::PythonObject.
getViewProviderName()
const char* TechDraw::DrawBrokenView::getViewProviderName () const inline override virtual
returns the type name of the ViewProvider
Reimplemented from App::DocumentObject.
Definition at line 101 of file DrawBrokenView.h.
guiDirectionFromObj()
Base::Vector3d DrawBrokenView::guiDirectionFromObj (const App::DocumentObject & breakObj) const
extract the breakDirection from the break object in a form the gui will understand.
Definition at line 380 of file DrawBrokenView.cpp.
References directionFromObj(), and TechDraw::DrawViewPart::projectPoint().
isBreakObject()
bool DrawBrokenView::isBreakObject (const App::DocumentObject & breakObj) static
determine if a given object can be used as a break object
Definition at line 394 of file DrawBrokenView.cpp.
References TechDraw::ShapeExtractor::getLocatedShape(), isBreakObjectSketch(), and TechDraw::ShapeExtractor::isSketchObject().
isBreakObjectSketch()
bool DrawBrokenView::isBreakObjectSketch (const App::DocumentObject & breakObj) static
determine if a sketch object can be used as a break object to be a break object the sketch must contain 2 edges, both of which are horizontal or vertical
Definition at line 410 of file DrawBrokenView.cpp.
References Base::Console(), TechDraw::ShapeUtils::edgesAreParallel(), TechDraw::ShapeExtractor::getLocatedShape(), and Base::ConsoleSingleton::Message().
Referenced by isBreakObject().
mapPoint2dFromView()
Base::Vector3d DrawBrokenView::mapPoint2dFromView (Base::Vector3d point2d) const
transform a 2d point in the broken view into the equivalent point on the XY paper plane. used in creating dimensions from points on the broken view.
Definition at line 958 of file DrawBrokenView.cpp.
References Breaks, TechDraw::DrawUtil::closestBasisOriented(), TechDraw::DrawUtil::coordinateForDirection(), getCompressedCentroid(), TechDraw::DrawViewPart::getProjectionCS(), App::PropertyListsT< T, ListT, ParentT >::getValues(), TechDraw::DrawUtil::togp_Pnt(), TechDraw::DrawUtil::toVector3d(), and TechDraw::DrawViewPart::XDirection.
mapPoint3dToView()
Base::Vector3d DrawBrokenView::mapPoint3dToView (Base::Vector3d point3d) const
transform a 3d point into its position within the broken view. used in creating dimensions.
Definition at line 924 of file DrawBrokenView.cpp.
References Breaks, TechDraw::DrawUtil::closestBasisOriented(), TechDraw::DrawUtil::coordinateForDirection(), getCompressedCentroid(), TechDraw::DrawViewPart::getProjectionCS(), App::PropertyListsT< T, ListT, ParentT >::getValues(), TechDraw::DrawViewPart::projectPoint(), result, TechDraw::DrawUtil::toVector3d(), and TechDraw::DrawViewPart::XDirection.
mustExecute()
short DrawBrokenView::mustExecute () const override virtual
mustExecute We call this method to check if the object was modified to be invoked. If the object label or an argument is modified. If we must recompute the object - to call the method execute(). 0: no recomputation is needed 1: recomputation needed
Remarks
If an object is marked as 'touched' then this does not necessarily mean that it will be recomputed. It only means that all objects that link it (i.e. its InList) will be recomputed.
Reimplemented from App::DocumentObject.
Definition at line 126 of file DrawBrokenView.cpp.
References Breaks, Gap, App::DocumentObject::isRestoring(), App::Property::isTouched(), and TechDraw::DrawViewPart::mustExecute().
removeBreakObjects()
std::vector< App::DocumentObject * > DrawBrokenView::removeBreakObjects (std::vector< App::DocumentObject * > breaks, std::vector< App::DocumentObject * > shapes) static
removes break objects from a list of document objects and returns the rest of the objects. used by TechDrawGui::Command
Definition at line 731 of file DrawBrokenView.cpp.
References result.
Member Data Documentation
Breaks
App::PropertyLinkList TechDraw::DrawBrokenView::Breaks
Definition at line 94 of file DrawBrokenView.h.
Referenced by mapPoint2dFromView(), mapPoint3dToView(), and mustExecute().
BreakTypeEnums
const char * DrawBrokenView::BreakTypeEnums static
Initial value:
= {
    QT_TRANSLATE_NOOP("DrawBrokenView", "None"),
    QT_TRANSLATE_NOOP("DrawBrokenView", "ZigZag"),
    QT_TRANSLATE_NOOP("DrawBrokenView", "Simple"),
    nullptr}
Definition at line 89 of file DrawBrokenView.h.
Gap
App::PropertyLength TechDraw::DrawBrokenView::Gap
Definition at line 95 of file DrawBrokenView.h.
Referenced by mustExecute().
The documentation for this class was generated from the following files:
DrawBrokenView.h
DrawBrokenView.cpp