FreeCAD: CAMTests.TestPathLanguage.TestPathLanguage Class Reference
CAMTests.TestPathLanguage.TestPathLanguage Class Reference
Public Member Functions
def assertTangents (self, instr, t1)
def test00 (self)
def test10 (self)
def test20 (self)
def test30 (self)
def test40 (self)
def test50 (self)
Public Member Functions inherited from CAMTests.PathTestUtils.PathTestBase
def assertRoughly (self, f1, f2, error=0.00001)
def assertCoincide (self, pt1, pt2, error=0.0001)
def assertPlacement (self, p1, p2)
def assertLine (self, edge, pt1, pt2)
def assertLines (self, edgs, tail, points)
def assertArc (self, edge, pt1, pt2, direction="CW")
def assertCircle (self, edge, pt, r)
def assertCurve (self, edge, p1, p2, p3)
def assertCylinderAt (self, solid, pt, r, h)
def assertConeAt (self, solid, pt, r1, r2, h)
def assertCommandEqual (self, c1, c2)
def assertEqualLocale (self, s1, s2)
def assertEdgeShapesMatch (self, e1, e2)
def assertPointsMatch (self, pts0, pts1)
def assertSuccessfulRecompute (self, doc, *objs, msg=None)
Detailed Description
Unit tests for the Language classes.
Definition at line 40 of file TestPathLanguage.py.
Member Function Documentation
assertTangents()
def CAMTests.TestPathLanguage.TestPathLanguage.assertTangents (self, instr, t1)
Assert that the two tangent angles are identical
Definition at line 43 of file TestPathLanguage.py.
References CAMTests.PathTestUtils.PathTestBase.assertRoughly().
Referenced by CAMTests.TestPathLanguage.TestPathLanguage.test50().
test00()
def CAMTests.TestPathLanguage.TestPathLanguage.test00 (self)
Verify G0 instruction construction
Definition at line 49 of file TestPathLanguage.py.
References CAMTests.TestPathLanguage.MNVR(), Path.Post.scripts.refactored_centroid_post.str, and Path.Post.scripts.grbl_post.type.
Referenced by CAMTests.TestPathToolController.TestPathToolController.test01().
test10()
def CAMTests.TestPathLanguage.TestPathLanguage.test10 (self)
Verify G1 instruction construction
Definition at line 62 of file TestPathLanguage.py.
References CAMTests.TestPathLanguage.MNVR(), Path.Post.scripts.refactored_centroid_post.str, and Path.Post.scripts.grbl_post.type.
test20()
def CAMTests.TestPathLanguage.TestPathLanguage.test20 (self)
Verify G2 instruction construction
Definition at line 72 of file TestPathLanguage.py.
References CAMTests.TestPathLanguage.MNVR(), Path.Post.scripts.refactored_centroid_post.str, and Path.Post.scripts.grbl_post.type.
test30()
def CAMTests.TestPathLanguage.TestPathLanguage.test30 (self)
Verify G3 instruction construction
Definition at line 78 of file TestPathLanguage.py.
References CAMTests.TestPathLanguage.MNVR(), Path.Post.scripts.refactored_centroid_post.str, and Path.Post.scripts.grbl_post.type.
test40()
def CAMTests.TestPathLanguage.TestPathLanguage.test40 (self)
Verify pathLength correctness
Definition at line 84 of file TestPathLanguage.py.
References CAMTests.PathTestUtils.PathTestBase.assertRoughly(), and CAMTests.TestPathLanguage.MNVR().
test50()
def CAMTests.TestPathLanguage.TestPathLanguage.test50 (self)
Verify tangents of moves.
Definition at line 101 of file TestPathLanguage.py.
References CAMTests.TestPathLanguage.TestPathLanguage.assertTangents(), and CAMTests.TestPathLanguage.INSTR().
The documentation for this class was generated from the following file:
TestPathLanguage.py