FreeCAD: MeshCore::MeshFixSelfIntersection Class Reference
MeshCore::MeshFixSelfIntersection Class Reference
#include <Evaluation.h>
Public Member Functions
MeshFixSelfIntersection (MeshKernel &rclB, const std::vector< std::pair< FacetIndex, FacetIndex >> &si)
std::vector< FacetIndex > GetFacets () const
bool Fixup () override
Public Member Functions inherited from MeshCore::MeshValidation
MeshValidation (MeshKernel &rclB)
virtual ~MeshValidation ()=default
MeshValidation (const MeshValidation &)=delete
MeshValidation (MeshValidation &&)=delete
MeshValidation & operator= (const MeshValidation &)=delete
MeshValidation & operator= (MeshValidation &&)=delete
Additional Inherited Members
Protected Attributes inherited from MeshCore::MeshValidation
MeshKernel & _rclMesh
Detailed Description
The MeshFixSelfIntersection class tries to fix self-intersections.
See also
MeshEvalSingleFacet
Definition at line 366 of file Evaluation.h.
Constructor & Destructor Documentation
MeshFixSelfIntersection()
MeshCore::MeshFixSelfIntersection::MeshFixSelfIntersection (MeshKernel & rclB, const std::vector< std::pair< FacetIndex, FacetIndex >> & si) inline
Definition at line 369 of file Evaluation.h.
Member Function Documentation
Fixup()
bool MeshFixSelfIntersection::Fixup () override virtual
This function attempts to change the mesh kernel to be valid according to the checked criterion: True is returned if the errors could be fixed, false otherwise.
Implements MeshCore::MeshValidation.
Definition at line 808 of file Evaluation.cpp.
References MeshCore::MeshValidation::_rclMesh, MeshCore::MeshKernel::DeleteFacets(), and GetFacets().
Referenced by Mesh::MeshObject::removeSelfIntersections().
GetFacets()
std::vector< FacetIndex > MeshFixSelfIntersection::GetFacets () const
Definition at line 779 of file Evaluation.cpp.
References MeshCore::MeshValidation::_rclMesh, and MeshCore::MeshKernel::GetFacets().
Referenced by Fixup(), and Mesh::MeshObject::removeSelfIntersections().
The documentation for this class was generated from the following files:
Evaluation.h
Evaluation.cpp