FreeCAD: bimcommands.BimMaterial.MatLineEdit Class Reference
bimcommands.BimMaterial.MatLineEdit Class Reference
Public Member Functions
def __init__ (self, parent=None)
def keyPressEvent (self, event)
Static Public Attributes
up = QtCore.Signal()
down = QtCore.Signal()
Detailed Description
Definition at line 36 of file BimMaterial.py.
Constructor & Destructor Documentation
__init__()
def bimcommands.BimMaterial.MatLineEdit.__init__ (self, parent = None)
Definition at line 42 of file BimMaterial.py.
Referenced by draftguitools.gui_subelements.SubelementHighlight.finish().
Member Function Documentation
keyPressEvent()
def bimcommands.BimMaterial.MatLineEdit.keyPressEvent (self, event)
Definition at line 45 of file BimMaterial.py.
References bimcommands.BimMaterial.MatLineEdit.down, and bimcommands.BimMaterial.MatLineEdit.up.
Member Data Documentation
down
bimcommands.BimMaterial.MatLineEdit.down = QtCore.Signal() static
Definition at line 40 of file BimMaterial.py.
Referenced by bimcommands.BimMaterial.MatLineEdit.keyPressEvent().
up
bimcommands.BimMaterial.MatLineEdit.up = QtCore.Signal() static
Definition at line 39 of file BimMaterial.py.
Referenced by bimcommands.BimMaterial.MatLineEdit.keyPressEvent().
The documentation for this class was generated from the following file:
BimMaterial.py