FreeCAD: Gui::SoGLSelectAction Class Reference
Gui::SoGLSelectAction Class Reference
#include <SoFCSelectionAction.h>
Public Member Functions
SoGLSelectAction (const SbViewportRegion &region, const SbViewportRegion &select)
~SoGLSelectAction () override
void setHandled ()
SbBool isHandled () const
const SbViewportRegion & getViewportRegion () const
Static Public Member Functions
static void initClass ()
Public Attributes
std::vector< unsigned long > indices
Protected Member Functions
void beginTraversal (SoNode *node) override
Detailed Description
The SoGLSelectAction class is used to get all data under a selected area.
Author
Werner Mayer
Definition at line 253 of file SoFCSelectionAction.h.
Constructor & Destructor Documentation
SoGLSelectAction()
SoGLSelectAction::SoGLSelectAction (const SbViewportRegion & region, const SbViewportRegion & select)
Definition at line 761 of file SoFCSelectionAction.cpp.
~SoGLSelectAction()
SoGLSelectAction::~SoGLSelectAction () override default
Member Function Documentation
beginTraversal()
void SoGLSelectAction::beginTraversal (SoNode * node) override protected
Definition at line 775 of file SoFCSelectionAction.cpp.
getViewportRegion()
const SbViewportRegion & SoGLSelectAction::getViewportRegion () const
Definition at line 770 of file SoFCSelectionAction.cpp.
initClass()
void SoGLSelectAction::initClass () static
The order of the defined SO_ACTION_ADD_METHOD statements is very important. First the base classes and afterwards subclasses of them must be listed, otherwise the registered methods of subclasses will be overridden. For more details see the thread in the Coin3d forum https://www.coin3d.org/pipermail/coin-discuss/2004-May/004346.html. This means that SoSwitch must be listed after SoGroup and SoFCSelection after SoSeparator because both classes inherits the others.
Definition at line 734 of file SoFCSelectionAction.cpp.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
isHandled()
SbBool SoGLSelectAction::isHandled () const
Definition at line 791 of file SoFCSelectionAction.cpp.
setHandled()
void SoGLSelectAction::setHandled ()
Definition at line 786 of file SoFCSelectionAction.cpp.
Member Data Documentation
indices
std::vector<unsigned long> Gui::SoGLSelectAction::indices
Definition at line 274 of file SoFCSelectionAction.h.
Referenced by MeshGui::ViewProviderMesh::getFacetsOfRegion(), and draftguitools.gui_dimensions.Dimension::set_selection().
The documentation for this class was generated from the following files:
SoFCSelectionAction.h
SoFCSelectionAction.cpp