FreeCAD: MeshPart::CurveProjectorWithToolMesh Class Reference
MeshPart::CurveProjectorWithToolMesh Class Reference
#include <CurveProjector.h>
Classes
struct LineSeg
Public Member Functions
CurveProjectorWithToolMesh (const TopoDS_Shape &aShape, const MeshKernel &pMesh, MeshKernel &rToolMesh)
~CurveProjectorWithToolMesh () override=default
void makeToolMesh (const TopoDS_Edge &aEdge, std::vector< MeshGeomFacet > &cVAry)
Public Member Functions inherited from MeshPart::CurveProjector
CurveProjector (const TopoDS_Shape &aShape, const MeshKernel &pMesh)
virtual ~CurveProjector ()=default
result_type & result ()
void writeIntersectionPointsToFile (const char *name="export_pts.asc")
Public Attributes
MeshKernel & ToolMesh
Protected Member Functions
void Do () override
Additional Inherited Members
Public Types inherited from MeshPart::CurveProjector
using result_type = std::map< TopoDS_Edge, std::vector< FaceSplitEdge >, TopoDSLess< TopoDS_Edge > >
Protected Attributes inherited from MeshPart::CurveProjector
const TopoDS_Shape & _Shape
const MeshKernel & _Mesh
result_type mvEdgeSplitPoints
Detailed Description
Project by projecting a sampled curve to the mesh
Definition at line 143 of file CurveProjector.h.
Constructor & Destructor Documentation
CurveProjectorWithToolMesh()
CurveProjectorWithToolMesh::CurveProjectorWithToolMesh (const TopoDS_Shape & aShape, const MeshKernel & pMesh, MeshKernel & rToolMesh)
Definition at line 394 of file CurveProjector.cpp.
References Do().
~CurveProjectorWithToolMesh()
MeshPart::CurveProjectorWithToolMesh::~CurveProjectorWithToolMesh () override default
Member Function Documentation
Do()
void CurveProjectorWithToolMesh::Do () override protected virtual
Implements MeshPart::CurveProjector.
Definition at line 404 of file CurveProjector.cpp.
References MeshPart::CurveProjector::_Shape, MeshCore::MeshKernel::AddFacets(), makeToolMesh(), and ToolMesh.
Referenced by CurveProjectorWithToolMesh().
makeToolMesh()
void CurveProjectorWithToolMesh::makeToolMesh (const TopoDS_Edge & aEdge, std::vector< MeshGeomFacet > & cVAry)
Definition at line 419 of file CurveProjector.cpp.
References MeshPart::CurveProjector::_Mesh, Base::Console(), Base::Distance(), FLOAT_MAX, MeshCore::MeshGeomFacet::GetNormal(), Handle(), SplineSurface::i, MeshCore::MeshFacetIterator::Init(), MeshCore::MeshGeomFacet::IntersectWithLine(), Base::ConsoleSingleton::Log(), MeshCore::MeshFacetIterator::More(), MeshCore::MeshFacetIterator::Next(), Base::SequencerLauncher::next(), Base::Vector3< float_type >::Normalize(), ClipperLib::PointCount(), and toolbit-attributes::s.
Referenced by Do().
Member Data Documentation
ToolMesh
MeshKernel& MeshPart::CurveProjectorWithToolMesh::ToolMesh
Definition at line 161 of file CurveProjector.h.
Referenced by Do().
The documentation for this class was generated from the following files:
CurveProjector.h
CurveProjector.cpp