FreeCAD: Gui::NavigationAnimation Class Reference
Gui::NavigationAnimation Class Reference abstract
#include <NavigationAnimation.h>
Signals
void interrupted ()
Public Member Functions
NavigationAnimation (NavigationStyle *navigation)
Protected Member Functions
virtual void initialize ()=0
virtual void update (const QVariant &value)=0
virtual void onStop (bool finished)
Protected Attributes
NavigationStyle * navigation
Friends
class NavigationAnimator
class QObject
Detailed Description
Definition at line 55 of file NavigationAnimation.h.
Constructor & Destructor Documentation
NavigationAnimation()
NavigationAnimation::NavigationAnimation (NavigationStyle * navigation) explicit
Definition at line 30 of file NavigationAnimation.cpp.
Member Function Documentation
initialize()
virtual void Gui::NavigationAnimation::initialize () protected pure virtual
interrupted
void Gui::NavigationAnimation::interrupted () signal
Referenced by Gui::NavigationAnimator::startAndWait().
onStop()
void NavigationAnimation::onStop (bool finished) protected virtual
Definition at line 42 of file NavigationAnimation.cpp.
update()
virtual void Gui::NavigationAnimation::update (const QVariant & value) protected pure virtual
Referenced by bimcommands.BimViews.BIM_Views::Activated(), ArchAxisSystem.AxisSystemTaskPanel::addElement(), ArchSectionPlane.SectionPlaneTaskPanel::addElement(), DraftGui.FacebinderTaskPanel::addElement(), ArchComponent.ComponentTaskPanel::addElement(), bimcommands.BimViews.BIM_Views::addLevel(), bimcommands.BimViews.BIM_Views::addProxy(), femtaskpanels.task_result_mechanical._TaskPanel::calculate(), bimcommands.BimIfcElements.BIM_IfcElements::checkMatChanged(), ArchWindow._ArchWindowTaskPanel::create(), bimcommands.BimViews.BIM_Views::delete(), draftguitools.gui_edit.Edit::endEditing(), bimcommands.BimWall.Arch_Wall::getPoint(), ArchStructure._CommandStructure::getPoint(), draftguitools.gui_trackers.boxTracker::height(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), bimcommands.BimTutorial.BIM_Tutorial::next(), bimcommands.BimIfcElements.BIM_IfcElements::onMaterialChanged(), bimcommands.BimIfcElements.BIM_IfcElements::onObjectTypeChanged(), bimcommands.BimIfcProperties.BIM_IfcProperties::onSelected(), bimcommands.BimIfcProperties.BIM_IfcProperties::onVisible(), draftguitools.gui_trackers.rectangleTracker::p3(), Plot.Plot::plot(), bimcommands.BimTutorial.BIM_Tutorial::previous(), ArchAxisSystem.AxisSystemTaskPanel::removeElement(), ArchAxis._AxisTaskPanel::removeElement(), ArchWindow._ArchWindowTaskPanel::removeElement(), ArchSectionPlane.SectionPlaneTaskPanel::removeElement(), DraftGui.FacebinderTaskPanel::removeElement(), ArchComponent.ComponentTaskPanel::removeElement(), draftguitools.gui_trackers.gridTracker::reset(), ArchRoof._RoofTaskPanel::resetObject(), ArchNesting.Nester::run(), bimcommands.BimWindows.BIM_Windows_TaskPanel::setDescription(), bimcommands.BimWindows.BIM_Windows_TaskPanel::setHeight(), bimcommands.BimWindows.BIM_Windows_TaskPanel::setLabel(), draftguitools.gui_trackers.gridTracker::setMainlines(), bimcommands.BimWindows.BIM_Windows_TaskPanel::setMaterial(), draftguitools.gui_trackers.gridTracker::setSize(), draftguitools.gui_trackers.gridTracker::setSpacing(), bimcommands.BimWindows.BIM_Windows_TaskPanel::setTag(), bimcommands.BimWindows.BIM_Windows_TaskPanel::setWidth(), and bimcommands.BimViews.BIM_Views::update().
Friends And Related Function Documentation
NavigationAnimator
friend class NavigationAnimator friend
Definition at line 94 of file NavigationAnimation.h.
QObject
friend class QObject friend
Definition at line 95 of file NavigationAnimation.h.
Member Data Documentation
navigation
NavigationStyle* Gui::NavigationAnimation::navigation protected
Definition at line 85 of file NavigationAnimation.h.
The documentation for this class was generated from the following files:
NavigationAnimation.h
NavigationAnimation.cpp