FreeCAD: PartDesignGui::TaskDressUpParameters Class Reference
PartDesignGui::TaskDressUpParameters Class Reference abstract
#include <TaskDressUpParameters.h>
Public Member Functions
TaskDressUpParameters (ViewProviderDressUp *DressUpView, bool selectEdges, bool selectFaces, QWidget *parent=nullptr)
~TaskDressUpParameters () override
const std::vector< std::string > getReferences () const
Part::Feature * getBase () const
void hideObject ()
void showObject ()
void setupTransaction ()
virtual void apply ()
Apply the changes made to the object to it.
int getTransactionID () const
bool event (QEvent *event) override
Public Member Functions inherited from Gui::TaskView::TaskBox
TaskBox (QWidget *parent=nullptr)
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
QSize minimumSizeHint () const override
~TaskBox () override
void hideGroupBox ()
bool isGroupVisible () const
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (QWidget *parent=nullptr)
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
QBoxLayout * groupLayout ()
void setScheme (ActionPanelScheme *pointer)
bool isExpandable () const
bool hasHeader () const
QString headerText () const
QSize minimumSizeHint () const override
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Protected Types
enum selectionModes { none, refSel, plane, line }
Protected Slots
void onButtonRefSel (const bool checked)
void doubleClicked (QListWidgetItem *item)
void setSelection (QListWidgetItem *current)
void itemClickedTimeout ()
virtual void onRefDeleted ()=0
void createDeleteAction (QListWidget *parentList)
void createAddAllEdgesAction (QListWidget *parentList)
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Protected Member Functions
void referenceSelected (const Gui::SelectionChanges &msg, QListWidget *widget)
void keyPressEvent (QKeyEvent *ke) override
void hideOnError ()
void addAllEdges (QListWidget *listWidget)
void deleteRef (QListWidget *listWidget)
void updateFeature (PartDesign::DressUp *pcDressUp, const std::vector< std::string > &refs)
void setSelectionMode (selectionModes mode)
virtual void setButtons (const selectionModes mode)=0
ViewProviderDressUp * getDressUpView () const
template<typename T = App::DocumentObject>
T * getObject () const
Protected Member Functions inherited from Gui::TaskView::TaskBox
void showEvent (QShowEvent *) override
void actionEvent (QActionEvent *) override
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
void paintEvent (QPaintEvent *event) override
Static Protected Member Functions
static void removeItemFromListWidget (QListWidget *widget, const char *itemstr)
static const QString btnPreviewStr ()
static const QString btnSelectStr ()
Protected Attributes
bool wasDoubleClicked = false
QWidget * proxy
QAction * deleteAction
QAction * addAllEdgesAction
bool allowFaces
bool allowEdges
selectionModes selectionMode
int transactionID
Protected Attributes inherited from QSint::ActionGroup
double m_foldStep
double m_foldDelta
double m_fullHeight
double m_tempHeight
int m_foldDirection
QPixmap m_foldPixmap
class TaskHeader * myHeader
class TaskGroup * myGroup
QWidget * myDummy
ActionPanelScheme * myScheme
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void showHide ()
void setExpandable (bool expandable=true)
void setHeader (bool enable=true)
void setHeaderText (const QString &title)
void setHeaderIcon (const QPixmap &icon)
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Detailed Description
Definition at line 45 of file TaskDressUpParameters.h.
Member Enumeration Documentation
selectionModes
enum PartDesignGui::TaskDressUpParameters::selectionModes protected
Enumerator
none
refSel
plane
line
Definition at line 88 of file TaskDressUpParameters.h.
Constructor & Destructor Documentation
TaskDressUpParameters()
TaskDressUpParameters::TaskDressUpParameters (ViewProviderDressUp * DressUpView, bool selectEdges, bool selectFaces, QWidget * parent = nullptr)
Definition at line 57 of file TaskDressUpParameters.cpp.
References App::Application::getActiveTransaction(), and App::GetApplication().
~TaskDressUpParameters()
TaskDressUpParameters::~TaskDressUpParameters () override
Definition at line 76 of file TaskDressUpParameters.cpp.
References Gui::SelectionSingleton::rmvSelectionGate(), and Gui::Selection().
Member Function Documentation
addAllEdges()
void TaskDressUpParameters::addAllEdges (QListWidget * listWidget) protected
Definition at line 141 of file TaskDressUpParameters.cpp.
References PartDesign::DressUp::Base, src.Mod.AddonManager.NetworkManager::count, Part::TopoShape::countSubShapes(), SCL.SimpleDataTypes::e, DraftVecUtils::find(), App::PropertyLinkSub::getSubValues(), Part::Feature::getTopoShape(), App::PropertyLinkSub::getValue(), SplineSurface::i, setupTransaction(), and App::PropertyLinkSub::setValue().
apply()
virtual void PartDesignGui::TaskDressUpParameters::apply () inline virtual
Apply the changes made to the object to it.
Reimplemented in PartDesignGui::TaskThicknessParameters, PartDesignGui::TaskChamferParameters, PartDesignGui::TaskDraftParameters, and PartDesignGui::TaskFilletParameters.
Definition at line 61 of file TaskDressUpParameters.h.
Referenced by PartDesignGui::TaskDlgFilletParameters::accept(), PartDesignGui::TaskDlgDraftParameters::accept(), PartDesignGui::TaskDlgChamferParameters::accept(), PartDesignGui::TaskDlgThicknessParameters::accept(), and PartDesignGui::TaskDraftParameters::apply().
btnPreviewStr()
const QString TaskDressUpParameters::btnPreviewStr () static protected
Definition at line 82 of file TaskDressUpParameters.cpp.
Referenced by PartDesignGui::TaskFilletParameters::setButtons(), PartDesignGui::TaskChamferParameters::setButtons(), PartDesignGui::TaskDraftParameters::setButtons(), and PartDesignGui::TaskThicknessParameters::setButtons().
btnSelectStr()
const QString TaskDressUpParameters::btnSelectStr () static protected
Definition at line 88 of file TaskDressUpParameters.cpp.
Referenced by PartDesignGui::TaskFilletParameters::setButtons(), PartDesignGui::TaskChamferParameters::setButtons(), PartDesignGui::TaskDraftParameters::setButtons(), and PartDesignGui::TaskThicknessParameters::setButtons().
createAddAllEdgesAction
void TaskDressUpParameters::createAddAllEdgesAction (QListWidget * parentList) protected slot
Definition at line 289 of file TaskDressUpParameters.cpp.
References addAllEdgesAction.
Referenced by PartDesignGui::TaskChamferParameters::TaskChamferParameters(), and PartDesignGui::TaskFilletParameters::TaskFilletParameters().
createDeleteAction
void TaskDressUpParameters::createDeleteAction (QListWidget * parentList) protected slot
Definition at line 304 of file TaskDressUpParameters.cpp.
References Gui::Application::commandManager(), deleteAction, Gui::CommandManager::getCommandByName(), Gui::Command::getShortcut(), and Gui::Application::Instance.
Referenced by PartDesignGui::TaskChamferParameters::TaskChamferParameters(), PartDesignGui::TaskDraftParameters::TaskDraftParameters(), and PartDesignGui::TaskFilletParameters::TaskFilletParameters().
deleteRef()
void TaskDressUpParameters::deleteRef (QListWidget * listWidget) protected
Definition at line 176 of file TaskDressUpParameters.cpp.
References PartDesign::DressUp::Base, Gui::SelectionSingleton::clearSelection(), App::PropertyLinkSub::getSubValues(), SplineSurface::i, Gui::Selection(), and updateFeature().
doubleClicked
void TaskDressUpParameters::doubleClicked (QListWidgetItem * item) protected slot
Definition at line 219 of file TaskDressUpParameters.cpp.
References itemClickedTimeout(), none, setSelectionMode(), and wasDoubleClicked.
Referenced by PartDesignGui::TaskChamferParameters::TaskChamferParameters(), PartDesignGui::TaskDraftParameters::TaskDraftParameters(), and PartDesignGui::TaskFilletParameters::TaskFilletParameters().
event()
bool TaskDressUpParameters::event (QEvent * event) override
Definition at line 322 of file TaskDressUpParameters.cpp.
References addAllEdgesAction, deleteAction, and Gui::QtTools::matches().
getBase()
Part::Feature * TaskDressUpParameters::getBase () const
Definition at line 412 of file TaskDressUpParameters.cpp.
References PartDesign::DressUp::getBaseObject(), and getDressUpView().
Referenced by PartDesignGui::TaskDlgDressUpParameters::accept(), referenceSelected(), and setSelectionMode().
getDressUpView()
ViewProviderDressUp * TaskDressUpParameters::getDressUpView () const protected
Definition at line 407 of file TaskDressUpParameters.cpp.
Referenced by getBase(), and PartDesignGui::TaskDraftParameters::onSelectionChanged().
getObject()
template<typename T = App::DocumentObject> T* PartDesignGui::TaskDressUpParameters::getObject () const inline protected
Definition at line 95 of file TaskDressUpParameters.h.
References Gui::ViewProviderDocumentObject::getObject().
Referenced by PartDesignGui::TaskDraftParameters::getLine(), and PartDesignGui::TaskDraftParameters::getPlane().
getReferences()
const std::vector< std::string > TaskDressUpParameters::getReferences () const
Definition at line 355 of file TaskDressUpParameters.cpp.
References PartDesign::DressUp::Base, App::PropertyLinkSub::getSubValues(), and result.
Referenced by PartDesignGui::TaskDlgDressUpParameters::accept().
getTransactionID()
int PartDesignGui::TaskDressUpParameters::getTransactionID () const inline
Definition at line 63 of file TaskDressUpParameters.h.
References transactionID.
hideObject()
void TaskDressUpParameters::hideObject ()
Definition at line 397 of file TaskDressUpParameters.cpp.
Referenced by hideOnError(), and setSelectionMode().
hideOnError()
void TaskDressUpParameters::hideOnError () protected
Definition at line 374 of file TaskDressUpParameters.cpp.
References hideObject(), App::DocumentObject::isError(), and showObject().
Referenced by PartDesignGui::TaskDraftParameters::onSelectionChanged(), PartDesignGui::TaskChamferParameters::TaskChamferParameters(), PartDesignGui::TaskDraftParameters::TaskDraftParameters(), PartDesignGui::TaskFilletParameters::TaskFilletParameters(), and updateFeature().
itemClickedTimeout
void TaskDressUpParameters::itemClickedTimeout () protected slot
Definition at line 284 of file TaskDressUpParameters.cpp.
References wasDoubleClicked.
Referenced by doubleClicked(), and setSelection().
keyPressEvent()
void TaskDressUpParameters::keyPressEvent (QKeyEvent * ke) override protected
Definition at line 339 of file TaskDressUpParameters.cpp.
References addAllEdgesAction, deleteAction, and Gui::QtTools::matches().
onButtonRefSel
void TaskDressUpParameters::onButtonRefSel (const bool checked) protected slot
Definition at line 214 of file TaskDressUpParameters.cpp.
References none, refSel, and setSelectionMode().
Referenced by PartDesignGui::TaskChamferParameters::TaskChamferParameters(), PartDesignGui::TaskDraftParameters::TaskDraftParameters(), and PartDesignGui::TaskFilletParameters::TaskFilletParameters().
onRefDeleted
virtual void PartDesignGui::TaskDressUpParameters::onRefDeleted () protected pure virtual slot
referenceSelected()
void TaskDressUpParameters::referenceSelected (const Gui::SelectionChanges & msg, QListWidget * widget) protected
Definition at line 110 of file TaskDressUpParameters.cpp.
References PartDesign::DressUp::Base, Gui::SelectionSingleton::clearSelection(), SCL.SimpleDataTypes::f, DraftVecUtils::find(), getBase(), App::PropertyLinkSub::getSubValues(), Path.Op.Surface::msg, removeItemFromListWidget(), Gui::Selection(), and updateFeature().
Referenced by PartDesignGui::TaskFilletParameters::onSelectionChanged(), PartDesignGui::TaskChamferParameters::onSelectionChanged(), PartDesignGui::TaskDraftParameters::onSelectionChanged(), and PartDesignGui::TaskThicknessParameters::onSelectionChanged().
removeItemFromListWidget()
void TaskDressUpParameters::removeItemFromListWidget (QListWidget * widget, const char * itemstr) static protected
Definition at line 363 of file TaskDressUpParameters.cpp.
References src.Mod.Test.testPathArray::items.
Referenced by referenceSelected().
setButtons()
virtual void PartDesignGui::TaskDressUpParameters::setButtons (const selectionModes mode) protected pure virtual
Implemented in PartDesignGui::TaskThicknessParameters, PartDesignGui::TaskDraftParameters, PartDesignGui::TaskChamferParameters, and PartDesignGui::TaskFilletParameters.
Referenced by setSelectionMode().
setSelection
void TaskDressUpParameters::setSelection (QListWidgetItem * current) protected slot
Definition at line 233 of file TaskDressUpParameters.cpp.
References Gui::SelectionObserver::blockSelection(), Gui::SelectionSingleton::clearSelection(), PartDesign::Body::findBodyOf(), App::DocumentObject::getNameInDocument(), itemClickedTimeout(), none, refSel, Gui::Selection(), selectionMode, setSelectionMode(), and wasDoubleClicked.
Referenced by PartDesignGui::TaskChamferParameters::TaskChamferParameters(), PartDesignGui::TaskDraftParameters::TaskDraftParameters(), and PartDesignGui::TaskFilletParameters::TaskFilletParameters().
setSelectionMode()
void TaskDressUpParameters::setSelectionMode (selectionModes mode) protected
Definition at line 426 of file TaskDressUpParameters.cpp.
References Gui::SelectionSingleton::addSelectionGate(), allowEdges, allowFaces, Gui::SelectionSingleton::clearSelection(), PartDesignGui::EDGE, PartDesignGui::FACE, getBase(), hideObject(), none, Gui::SelectionSingleton::rmvSelectionGate(), Gui::Selection(), selectionMode, setButtons(), and showObject().
Referenced by doubleClicked(), onButtonRefSel(), setSelection(), PartDesignGui::TaskChamferParameters::TaskChamferParameters(), PartDesignGui::TaskDraftParameters::TaskDraftParameters(), and PartDesignGui::TaskFilletParameters::TaskFilletParameters().
setupTransaction()
void TaskDressUpParameters::setupTransaction ()
Definition at line 94 of file TaskDressUpParameters.cpp.
References App::Application::getActiveTransaction(), App::GetApplication(), App::Application::setActiveTransaction(), and transactionID.
Referenced by addAllEdges(), PartDesignGui::TaskDraftParameters::onSelectionChanged(), and updateFeature().
showObject()
void TaskDressUpParameters::showObject ()
Definition at line 402 of file TaskDressUpParameters.cpp.
Referenced by PartDesignGui::TaskDlgFilletParameters::accept(), PartDesignGui::TaskDlgDraftParameters::accept(), PartDesignGui::TaskDlgChamferParameters::accept(), PartDesignGui::TaskDlgThicknessParameters::accept(), hideOnError(), and setSelectionMode().
updateFeature()
void TaskDressUpParameters::updateFeature (PartDesign::DressUp * pcDressUp, const std::vector< std::string > & refs) protected
Definition at line 200 of file TaskDressUpParameters.cpp.
References PartDesign::DressUp::Base, App::PropertyLinkSub::getValue(), hideOnError(), App::DocumentObject::recomputeFeature(), refSel, selectionMode, setupTransaction(), and App::PropertyLinkSub::setValue().
Referenced by deleteRef(), and referenceSelected().
Member Data Documentation
addAllEdgesAction
QAction* PartDesignGui::TaskDressUpParameters::addAllEdgesAction protected
Definition at line 113 of file TaskDressUpParameters.h.
Referenced by createAddAllEdgesAction(), event(), keyPressEvent(), PartDesignGui::TaskChamferParameters::TaskChamferParameters(), and PartDesignGui::TaskFilletParameters::TaskFilletParameters().
allowEdges
bool PartDesignGui::TaskDressUpParameters::allowEdges protected
Definition at line 115 of file TaskDressUpParameters.h.
Referenced by setSelectionMode().
allowFaces
bool PartDesignGui::TaskDressUpParameters::allowFaces protected
Definition at line 115 of file TaskDressUpParameters.h.
Referenced by setSelectionMode().
deleteAction
QAction* PartDesignGui::TaskDressUpParameters::deleteAction protected
Definition at line 112 of file TaskDressUpParameters.h.
Referenced by createDeleteAction(), event(), keyPressEvent(), PartDesignGui::TaskChamferParameters::TaskChamferParameters(), PartDesignGui::TaskDraftParameters::TaskDraftParameters(), and PartDesignGui::TaskFilletParameters::TaskFilletParameters().
proxy
QWidget* PartDesignGui::TaskDressUpParameters::proxy protected
Definition at line 111 of file TaskDressUpParameters.h.
Referenced by PartDesignGui::TaskFilletParameters::changeEvent(), PartDesignGui::TaskChamferParameters::changeEvent(), PartDesignGui::TaskDraftParameters::changeEvent(), PartDesignGui::TaskThicknessParameters::changeEvent(), PartDesignGui::TaskChamferParameters::TaskChamferParameters(), PartDesignGui::TaskDraftParameters::TaskDraftParameters(), and PartDesignGui::TaskFilletParameters::TaskFilletParameters().
selectionMode
selectionModes PartDesignGui::TaskDressUpParameters::selectionMode protected
Definition at line 116 of file TaskDressUpParameters.h.
Referenced by PartDesignGui::TaskFilletParameters::onSelectionChanged(), PartDesignGui::TaskChamferParameters::onSelectionChanged(), PartDesignGui::TaskDraftParameters::onSelectionChanged(), PartDesignGui::TaskThicknessParameters::onSelectionChanged(), setSelection(), setSelectionMode(), and updateFeature().
transactionID
int PartDesignGui::TaskDressUpParameters::transactionID protected
Definition at line 117 of file TaskDressUpParameters.h.
Referenced by getTransactionID(), and setupTransaction().
wasDoubleClicked
bool PartDesignGui::TaskDressUpParameters::wasDoubleClicked = false protected
Definition at line 80 of file TaskDressUpParameters.h.
Referenced by doubleClicked(), itemClickedTimeout(), and setSelection().
The documentation for this class was generated from the following files:
TaskDressUpParameters.h
TaskDressUpParameters.cpp