FreeCAD: Gui::SequencerDialog Class Reference
Gui::SequencerDialog Class Reference
#include <ProgressDialog.h>
Public Member Functions
void pause () override
void resume () override
bool isBlocking () const override
bool canAbort () const
Public Member Functions inherited from Base::SequencerBase
virtual ~SequencerBase ()
bool setLocked (bool bLock)
bool isLocked () const
bool isRunning () const
bool wasCanceled () const
virtual void checkAbort ()
Check if the operation is aborted by user.
Static Public Member Functions
static SequencerDialog * instance ()
Static Public Member Functions inherited from Base::SequencerBase
static SequencerBase & Instance ()
Protected Member Functions
SequencerDialog ()
~SequencerDialog () override
void setText (const char *pszTxt) override
void startStep () override
void nextStep (bool canAbort) override
void setProgress (size_t) override
void resetData () override
void showRemainingTime ()
Protected Member Functions inherited from Base::SequencerBase
bool start (const char *pszStr, size_t steps)
size_t numberOfSteps () const
int progressInPercent () const
bool next (bool canAbort=false)
bool stop ()
void tryToCancel ()
void rejectCancel ()
SequencerBase ()
SequencerBase (const SequencerBase &)=default
SequencerBase (SequencerBase &&)=default
SequencerBase & operator= (const SequencerBase &)=default
SequencerBase & operator= (SequencerBase &&)=default
for internal use only
class ProgressDialog
Additional Inherited Members
Protected Attributes inherited from Base::SequencerBase
size_t nProgress {0}
size_t nTotalSteps {0}
Detailed Description
Definition at line 59 of file ProgressDialog.h.
Constructor & Destructor Documentation
SequencerDialog()
SequencerDialog::SequencerDialog () protected
Construction
Definition at line 61 of file ProgressDialog.cpp.
References Gui::SequencerDialogPrivate::canabort, Gui::SequencerDialogPrivate::dlg, Gui::getMainWindow(), Gui::SequencerDialogPrivate::guiThread, and ProgressDialog.
Referenced by instance().
~SequencerDialog()
SequencerDialog::~SequencerDialog () override protected
Destruction
Definition at line 71 of file ProgressDialog.cpp.
Member Function Documentation
canAbort()
bool SequencerDialog::canAbort () const
Definition at line 257 of file ProgressDialog.cpp.
References Gui::SequencerDialogPrivate::canabort.
Referenced by nextStep().
instance()
SequencerDialog * SequencerDialog::instance () static
Definition at line 53 of file ProgressDialog.cpp.
References SequencerDialog().
isBlocking()
bool SequencerDialog::isBlocking () const override virtual
Returns true if the running sequencer is blocking any user input. This might be only of interest of the GUI where the progress bar or dialog is used from a thread. If started from a thread this method should return false, otherwise true. The default implementation always returns true.
Reimplemented from Base::SequencerBase.
Definition at line 287 of file ProgressDialog.cpp.
References Gui::SequencerDialogPrivate::guiThread.
nextStep()
void SequencerDialog::nextStep (bool canAbort) override protected virtual
Increase the step indicator of the progress dialog.
Reimplemented from Base::SequencerBase.
Definition at line 116 of file ProgressDialog.cpp.
References Gui::SequencerDialogPrivate::canabort, canAbort(), Gui::ProgressDialog::canAbort(), Gui::SequencerDialogPrivate::dlg, Base::SequencerBase::nProgress, pause(), Base::SequencerBase::rejectCancel(), resume(), and Base::SequencerBase::wasCanceled().
pause()
void SequencerDialog::pause () override virtual
Breaks the sequencer if needed. The default implementation does nothing. Every pause() must eventually be followed by a corresponding resume().
See also
Gui::ProgressBar.
Reimplemented from Base::SequencerBase.
Definition at line 76 of file ProgressDialog.cpp.
Referenced by nextStep().
resetData()
void SequencerDialog::resetData () override protected virtual
Resets the sequencer
Reimplemented from Base::SequencerBase.
Definition at line 234 of file ProgressDialog.cpp.
References Gui::SequencerDialogPrivate::dlg.
resume()
void SequencerDialog::resume () override virtual
Continues with progress. The default implementation does nothing.
See also
pause(),
Gui::ProgressBar.
Reimplemented from Base::SequencerBase.
Definition at line 80 of file ProgressDialog.cpp.
Referenced by nextStep().
setProgress()
void SequencerDialog::setProgress (size_t step) override protected virtual
Sets the progress indicator to a certain position.
Reimplemented from Base::SequencerBase.
Definition at line 151 of file ProgressDialog.cpp.
References Gui::SequencerDialogPrivate::dlg.
setText()
void SequencerDialog::setText (const char * pszTxt) override protected virtual
Puts text to the progress dialog
Reimplemented from Base::SequencerBase.
Definition at line 270 of file ProgressDialog.cpp.
References Gui::SequencerDialogPrivate::dlg, and Gui::SequencerDialogPrivate::text.
Referenced by src.Mod.AddonManager.Widgets.addonmanager_widget_readme_browser.WidgetReadmeBrowser::setMarkdown().
showRemainingTime()
void SequencerDialog::showRemainingTime () protected
Definition at line 201 of file ProgressDialog.cpp.
References Gui::SequencerDialogPrivate::dlg, Gui::SequencerDialogPrivate::measureTime, Gui::SequencerDialogPrivate::text, and create_qrc::txt.
startStep()
void SequencerDialog::startStep () override protected virtual
Starts the progress dialog
Reimplemented from Base::SequencerBase.
Definition at line 84 of file ProgressDialog.cpp.
References Gui::SequencerDialogPrivate::dlg, Gui::SequencerDialogPrivate::guiThread, Gui::SequencerDialogPrivate::measureTime, Base::SequencerBase::nTotalSteps, and Gui::SequencerDialogPrivate::progressTime.
Friends And Related Function Documentation
ProgressDialog
friend class ProgressDialog friend
Definition at line 97 of file ProgressDialog.h.
Referenced by SequencerDialog().
The documentation for this class was generated from the following files:
ProgressDialog.h
ProgressDialog.cpp