FreeCAD: Wm4::ConvexHull2< Real > Class Template Reference
Wm4::ConvexHull2< Real > Class Template Reference
#include <Wm4ConvexHull2.h>
Public Member Functions
ConvexHull2 (int iVertexQuantity, Vector2< Real > *akVertex, Real fEpsilon, bool bOwner, Query::Type eQueryType)
virtual ~ConvexHull2 ()
const Vector2< Real > & GetLineOrigin () const
const Vector2< Real > & GetLineDirection () const
ConvexHull1< Real > * GetConvexHull1 () const
Public Member Functions inherited from Wm4::ConvexHull< Real >
virtual ~ConvexHull ()
int GetQueryType () const
int GetVertexQuantity () const
Real GetEpsilon () const
bool GetOwner () const
int GetDimension () const
int GetSimplexQuantity () const
const int * GetIndices () const
Additional Inherited Members
Protected Member Functions inherited from Wm4::ConvexHull< Real >
ConvexHull (int iVertexQuantity, Real fEpsilon, bool bOwner, Query::Type eQueryType)
bool Load (FILE *pkIFile)
bool Save (FILE *pkOFile) const
Protected Attributes inherited from Wm4::ConvexHull< Real >
Query::Type m_eQueryType
int m_iVertexQuantity
int m_iDimension
int m_iSimplexQuantity
int * m_aiIndex
Real m_fEpsilon
bool m_bOwner
Detailed Description
template<class Real>
class Wm4::ConvexHull2< Real >
Definition at line 20 of file Wm4ConvexHull2.h.
Constructor & Destructor Documentation
ConvexHull2()
template<class Real > Wm4::ConvexHull2< Real >::ConvexHull2 (int iVertexQuantity, Vector2< Real > * akVertex, Real fEpsilon, bool bOwner, Query::Type eQueryType)
Definition at line 22 of file Wm4ConvexHull2.cpp.
References Wm4::Mapper2< Real >::GetDimension(), Wm4::Mapper2< Real >::GetDirection(), Wm4::Mapper2< Real >::GetExtremeCCW(), Wm4::Mapper2< Real >::GetExtremeIndex(), Wm4::Mapper2< Real >::GetMaxRange(), Wm4::Mapper2< Real >::GetMin(), Wm4::Mapper2< Real >::GetOrigin(), SplineSurface::i, Wm4::ConvexHull< Real >::m_aiIndex, Wm4::ConvexHull< Real >::m_fEpsilon, Wm4::ConvexHull< Real >::m_iDimension, Wm4::ConvexHull< Real >::m_iSimplexQuantity, Wm4::ConvexHull< Real >::m_iVertexQuantity, Wm4::System::Memcpy(), Wm4::Query::QT_FILTERED, Wm4::Query::QT_INT64, Wm4::Query::QT_INTEGER, Wm4::Query::QT_RATIONAL, and WM4_NEW.
~ConvexHull2()
template<class Real > Wm4::ConvexHull2< Real >::~ConvexHull2 virtual
Definition at line 155 of file Wm4ConvexHull2.cpp.
References WM4_DELETE.
Member Function Documentation
GetConvexHull1()
template<class Real > ConvexHull1< Real > * Wm4::ConvexHull2< Real >::GetConvexHull1
Definition at line 178 of file Wm4ConvexHull2.cpp.
References Wm4::Vector2< Real >::Dot(), SplineSurface::i, and WM4_NEW.
Referenced by Wm4::ContMinBox().
GetLineDirection()
template<class Real > const Vector2< Real > & Wm4::ConvexHull2< Real >::GetLineDirection
Definition at line 172 of file Wm4ConvexHull2.cpp.
GetLineOrigin()
template<class Real > const Vector2< Real > & Wm4::ConvexHull2< Real >::GetLineOrigin
Definition at line 166 of file Wm4ConvexHull2.cpp.
The documentation for this class was generated from the following files:
Wm4ConvexHull2.h
Wm4ConvexHull2.cpp