FreeCAD: Path.Dressup.DogboneII Namespace Reference
Path.Dressup.DogboneII Namespace Reference
Classes
class BoneState
class Incision
class Proxy
class Side
class Style
Functions
def calc_length_adaptive (kink, angle, nominal_length, custom_length)
def calc_length_nominal (kink, angle, nominal_length, custom_length)
def calc_length_custom (kink, angle, nominal_length, custom_length)
def insertBone (obj, kink)
def Create (base, name="DressupDogbone")
Variables
PI
the value of pi
Function Documentation
calc_length_adaptive()
def Path.Dressup.DogboneII.calc_length_adaptive (kink, angle, nominal_length, custom_length)
Definition at line 39 of file DogboneII.py.
References KDL.abs(), Path.Log.debug(), Path.Geom.isRoughly(), Path.Geom.normalizeAngle(), and Path.Log.track().
Referenced by CAMTests.TestPathDressupDogboneII.TestDressupDogboneII.test00().
calc_length_custom()
def Path.Dressup.DogboneII.calc_length_custom (kink, angle, nominal_length, custom_length)
Definition at line 100 of file DogboneII.py.
Referenced by CAMTests.TestPathDressupDogboneII.TestDressupDogboneII.test02().
calc_length_nominal()
def Path.Dressup.DogboneII.calc_length_nominal (kink, angle, nominal_length, custom_length)
Definition at line 96 of file DogboneII.py.
Referenced by CAMTests.TestPathDressupDogboneII.TestDressupDogboneII.test01().
Create()
def Path.Dressup.DogboneII.Create (base, name = "DressupDogbone")
Definition at line 353 of file DogboneII.py.
insertBone()
def Path.Dressup.DogboneII.insertBone (obj, kink)
insertBone(kink, side) - return True if a bone should be inserted into the kink
Definition at line 154 of file DogboneII.py.
References Path.Log.debug().
Referenced by Path.Dressup.DogboneII.Proxy.createBone().
Variable Documentation
PI
Path.Dressup.DogboneII.PI
the value of pi
Definition at line 36 of file DogboneII.py.