FreeCAD: Gui::ExpressionBinding Class Reference
Gui::ExpressionBinding Class Reference
#include <ExpressionBinding.h>
Public Member Functions
ExpressionBinding ()
virtual ~ExpressionBinding ()
virtual void bind (const App::ObjectIdentifier &_path)
virtual void bind (const App::Property &prop)
bool isBound () const
void unbind ()
virtual bool apply (const std::string &propName)
virtual bool apply ()
bool hasExpression () const
bool autoApply () const
void setAutoApply (bool value)
Protected Member Functions
const App::ObjectIdentifier & getPath () const
std::shared_ptr< App::Expression > getExpression () const
std::string getExpressionString (bool no_throw=true) const
std::string getEscapedExpressionString () const
bool assignToProperty (const std::string &propName, double)
virtual void setExpression (std::shared_ptr< App::Expression > expr)
virtual void onChange ()
void expressionChange (const App::ObjectIdentifier &id)
void objectDeleted (const App::DocumentObject &)
Protected Attributes
boost::signals2::scoped_connection expressionchanged
boost::signals2::scoped_connection objectdeleted
bool m_autoApply {false}
Detailed Description
Definition at line 42 of file ExpressionBinding.h.
Constructor & Destructor Documentation
ExpressionBinding()
ExpressionBinding::ExpressionBinding () default
~ExpressionBinding()
ExpressionBinding::~ExpressionBinding () virtual default
Member Function Documentation
apply() [1/2]
bool ExpressionBinding::apply () virtual
Reimplemented in Gui::InputField.
Definition at line 241 of file ExpressionBinding.cpp.
References Gui::Command::getObjectCmd(), getPath(), App::Property::isReadOnly(), src.Mod.Test.testPathArray::path, and App::ObjectIdentifier::toEscapedString().
Referenced by Gui::UIntSpinBox::apply(), Gui::QuantitySpinBox::apply(), Gui::IntSpinBox::apply(), Gui::InputField::apply(), Gui::DoubleSpinBox::apply(), Gui::ExpLineEdit::apply(), and Gui::PropertyEditor::VectorLineEdit::apply().
apply() [2/2]
bool ExpressionBinding::apply (const std::string & propName) virtual
Reimplemented in Gui::PropertyEditor::VectorLineEdit, Gui::ExpLineEdit, Gui::DoubleSpinBox, Gui::InputField, Gui::IntSpinBox, Gui::QuantitySpinBox, and Gui::UIntSpinBox.
Definition at line 190 of file ExpressionBinding.cpp.
References App::Application::closeActiveTransaction(), Gui::Command::Doc, doCommand, App::Application::getActiveTransaction(), App::GetApplication(), App::DocumentObject::getDocument(), getEscapedExpressionString(), App::Document::getName(), App::DocumentObject::getNameInDocument(), App::PropertyString::getValue(), hasExpression(), isBound(), App::DocumentObject::Label, src.Mod.Test.testPathArray::path, and App::Application::setActiveTransaction().
Referenced by Gui::ExpressionBindingPy::apply().
assignToProperty()
bool ExpressionBinding::assignToProperty (const std::string & propName, double value) protected
Definition at line 168 of file ExpressionBinding.cpp.
References Gui::Command::Doc, doCommand, getPath(), isBound(), Base::BaseClass::isDerivedFrom(), App::Property::isReadOnly(), buildPsets::p, src.Mod.Test.testPathArray::path, and Base::toRadians().
Referenced by Gui::QuantitySpinBox::apply().
autoApply()
bool Gui::ExpressionBinding::autoApply () const inline
Definition at line 58 of file ExpressionBinding.h.
Referenced by Gui::ExpressionBindingPy::autoApply(), and Gui::PropertyEditor::PropertyVectorDistanceItem::createEditor().
bind() [1/2]
void ExpressionBinding::bind (const App::ObjectIdentifier & _path) virtual
Reimplemented in Gui::ExpLineEdit, Gui::InputField, Gui::PropertyEditor::PropertyItem, Gui::QuantitySpinBox, and Gui::ExpressionSpinBox.
Definition at line 97 of file ExpressionBinding.cpp.
References draftgeoutils.faces::bind(), App::Property::canonicalPath(), toolbit-attributes::doc, expressionChange(), expressionchanged, App::PropertyExpressionEngine::expressionChanged, App::DocumentObject::ExpressionEngine, App::DocumentObject::getDocument(), App::ObjectIdentifier::getProperty(), objectDeleted(), objectdeleted, and src.Mod.Test.testPathArray::path.
Referenced by Gui::ExpressionBindingPy::bind(), Gui::ExpressionSpinBox::bind(), bind(), Gui::PropertyEditor::PropertyItem::bind(), Gui::InputField::bind(), and Gui::ExpLineEdit::bind().
bind() [2/2]
void ExpressionBinding::bind (const App::Property & prop) virtual
Reimplemented in Gui::PropertyEditor::PropertyItem.
Definition at line 116 of file ExpressionBinding.cpp.
References bind().
expressionChange()
void ExpressionBinding::expressionChange (const App::ObjectIdentifier & id) protected
Definition at line 264 of file ExpressionBinding.cpp.
References onChange(), and src.Mod.Test.testPathArray::path.
Referenced by bind().
getEscapedExpressionString()
std::string ExpressionBinding::getEscapedExpressionString () const protected
Definition at line 160 of file ExpressionBinding.cpp.
References Base::Tools::escapedUnicodeFromUtf8(), Base::Tools::escapeQuotesFromString(), and getExpressionString().
Referenced by apply().
getExpression()
std::shared_ptr< App::Expression > ExpressionBinding::getExpression () const protected
Definition at line 126 of file ExpressionBinding.cpp.
References App::PropertyExpressionEngine::ExpressionInfo::expression, App::DocumentObject::getExpression(), isBound(), and src.Mod.Test.testPathArray::path.
Referenced by Gui::QuantitySpinBox::evaluateExpression(), Gui::QuantitySpinBox::focusInEvent(), getExpressionString(), hasExpression(), Gui::InputField::newInput(), Gui::ExpressionSpinBox::onChange(), Gui::ExpressionSpinBox::openFormulaDialog(), Gui::QuantitySpinBox::openFormulaDialog(), Gui::ExpLineEdit::resizeEvent(), Gui::ExpressionSpinBox::showValidExpression(), and Gui::ExpressionSpinBox::updateExpression().
getExpressionString()
std::string ExpressionBinding::getExpressionString (bool no_throw = true) const protected
Definition at line 135 of file ExpressionBinding.cpp.
References SCL.SimpleDataTypes::e, FC_ERR, and getExpression().
Referenced by getEscapedExpressionString(), Gui::PropertyEditor::PropertyVectorListItem::toString(), and Gui::PropertyEditor::PropertyVectorDistanceItem::toString().
getPath()
const App::ObjectIdentifier& Gui::ExpressionBinding::getPath () const inline protected
Definition at line 62 of file ExpressionBinding.h.
Referenced by apply(), assignToProperty(), Gui::InputField::bind(), Gui::QuantitySpinBox::boundToName(), Gui::PropertyEditor::PropertyVectorDistanceItem::createEditor(), Gui::InputField::newInput(), Gui::ExpressionSpinBox::openFormulaDialog(), Gui::QuantitySpinBox::openFormulaDialog(), Gui::PropertyEditor::PropertyVectorDistanceItem::propertyBound(), Gui::PropertyEditor::PropertyRotationItem::propertyBound(), Gui::PropertyEditor::PropertyPlacementItem::propertyBound(), Gui::PropertyEditor::PropertyEnumItem::propertyBound(), Gui::QuantitySpinBox::userInput(), Gui::QuantitySpinBox::validate(), and Gui::QuantitySpinBox::valueFromText().
hasExpression()
bool ExpressionBinding::hasExpression () const
Definition at line 121 of file ExpressionBinding.cpp.
References getExpression(), and isBound().
Referenced by apply(), Gui::ExpressionSpinBox::drawControl(), Gui::PropertyEditor::PropertyItem::hasAnyExpression(), Gui::ExpressionBindingPy::hasExpression(), Gui::ExpLineEdit::keyPressEvent(), Gui::PropertyEditor::PropertyVectorDistanceItem::setValue(), Gui::PropertyEditor::PropertyMatrixItem::setValue(), Gui::PropertyEditor::PropertyPlacementItem::setValue(), Gui::PropertyEditor::PropertyEnumItem::setValue(), Gui::PropertyEditor::PropertyStringListItem::setValue(), Gui::PropertyEditor::PropertyFloatListItem::setValue(), Gui::PropertyEditor::PropertyIntegerListItem::setValue(), Gui::PropertyEditor::PropertyColorItem::setValue(), Gui::PropertyEditor::PropertyMaterialItem::setValue(), Gui::PropertyEditor::PropertyMaterialListItem::setValue(), Gui::PropertyEditor::PropertyFileItem::setValue(), Gui::PropertyEditor::PropertyPathItem::setValue(), Gui::PropertyEditor::PropertyTransientFileItem::setValue(), Gui::PropertyEditor::PropertyVectorListItem::toString(), Gui::PropertyEditor::PropertyVectorDistanceItem::toString(), Gui::PropertyEditor::PropertyRotationItem::value(), and Gui::PropertyEditor::PropertyPlacementItem::value().
isBound()
bool ExpressionBinding::isBound () const
Definition at line 54 of file ExpressionBinding.cpp.
References src.Mod.Test.testPathArray::path.
Referenced by apply(), assignToProperty(), Gui::QuantitySpinBox::boundToName(), Gui::PropertyEditor::PropertyVectorDistanceItem::createEditor(), Gui::QuantitySpinBox::evaluateExpression(), Gui::QuantitySpinBox::focusInEvent(), getExpression(), Gui::ExpressionSpinBox::handleKeyEvent(), hasExpression(), Gui::ExpressionBindingPy::isBound(), Gui::InputField::newInput(), Gui::ExpressionSpinBox::onChange(), Gui::ExpressionSpinBox::openFormulaDialog(), Gui::QuantitySpinBox::openFormulaDialog(), Gui::PropertyEditor::PropertyVectorDistanceItem::propertyBound(), Gui::PropertyEditor::PropertyRotationItem::propertyBound(), Gui::PropertyEditor::PropertyPlacementItem::propertyBound(), Gui::PropertyEditor::PropertyEnumItem::propertyBound(), Gui::ExpLineEdit::resizeEvent(), Gui::ExpressionSpinBox::setExpression(), Gui::ExpLineEdit::setExpression(), and Gui::ExpressionSpinBox::updateExpression().
objectDeleted()
void ExpressionBinding::objectDeleted (const App::DocumentObject & obj) protected
Definition at line 270 of file ExpressionBinding.cpp.
References src.Mod.Test.testPathArray::path, and unbind().
Referenced by bind().
onChange()
virtual void Gui::ExpressionBinding::onChange () inline protected virtual
Reimplemented in Gui::PropertyEditor::PropertyItem, and Gui::ExpressionSpinBox.
Definition at line 70 of file ExpressionBinding.h.
Referenced by expressionChange().
setAutoApply()
void Gui::ExpressionBinding::setAutoApply (bool value) inline
Definition at line 59 of file ExpressionBinding.h.
Referenced by Gui::TreeWidgetItemDelegate::createEditor(), SketcherGui::PropertyConstraintListItem::initialize(), and Gui::ExpressionBindingPy::setAutoApply().
setExpression()
void Gui::ExpressionBinding::setExpression (std::shared_ptr< App::Expression > expr) protected virtual
Reimplemented in Gui::ExpLineEdit, Gui::QuantitySpinBox, and Gui::ExpressionSpinBox.
Definition at line 66 of file ExpressionBinding.cpp.
References App::Application::closeActiveTransaction(), Path.Log::error(), App::DocumentObject::ExpressionEngine, App::Application::getActiveTransaction(), App::GetApplication(), App::PropertyString::getValue(), App::DocumentObject::Label, src.Mod.Test.testPathArray::path, App::Application::setActiveTransaction(), App::PropertyExpressionEngine::setValue(), and App::PropertyExpressionEngine::validateExpression().
Referenced by Gui::InputField::newInput(), Gui::ExpressionSpinBox::setExpression(), Binding::setExpression(), and Gui::ExpLineEdit::setExpression().
unbind()
void ExpressionBinding::unbind ()
Definition at line 59 of file ExpressionBinding.cpp.
References expressionchanged, objectdeleted, and src.Mod.Test.testPathArray::path.
Referenced by objectDeleted().
Member Data Documentation
expressionchanged
boost::signals2::scoped_connection Gui::ExpressionBinding::expressionchanged protected
Definition at line 79 of file ExpressionBinding.h.
Referenced by bind(), and unbind().
m_autoApply
bool Gui::ExpressionBinding::m_autoApply {false} protected
Definition at line 81 of file ExpressionBinding.h.
objectdeleted
boost::signals2::scoped_connection Gui::ExpressionBinding::objectdeleted protected
Definition at line 80 of file ExpressionBinding.h.
Referenced by bind(), and unbind().
The documentation for this class was generated from the following files:
ExpressionBinding.h
ExpressionBinding.cpp