FreeCAD: App::DocumentWeakPtrT::Private Class Reference
App::DocumentWeakPtrT::Private Class Reference
Public Types
using Connection = boost::signals2::scoped_connection
using Connection = boost::signals2::scoped_connection
Public Member Functions
Private (Gui::Document *doc)
void deletedDocument (const Gui::Document &doc)
void reset ()
Private (App::Document *doc)
void deletedDocument (const App::Document &doc)
void reset ()
Public Attributes
Gui::Document * _document
Connection connectApplicationDeletedDocument
App::Document * _document
Detailed Description
Definition at line 231 of file Gui/DocumentObserver.cpp.
Member Typedef Documentation
Connection [1/2]
using App::DocumentWeakPtrT::Private::Connection = boost::signals2::scoped_connection
Definition at line 252 of file Gui/DocumentObserver.cpp.
Connection [2/2]
using App::DocumentWeakPtrT::Private::Connection = boost::signals2::scoped_connection
Definition at line 713 of file App/DocumentObserver.cpp.
Constructor & Destructor Documentation
Private() [1/2]
App::DocumentWeakPtrT::Private::Private (Gui::Document * doc) inline
Definition at line 233 of file Gui/DocumentObserver.cpp.
References draftgeoutils.faces::bind(), and toolbit-attributes::doc.
Private() [2/2]
App::DocumentWeakPtrT::Private::Private (App::Document * doc) inline explicit
Definition at line 689 of file App/DocumentObserver.cpp.
References draftgeoutils.faces::bind(), App::DocumentWeakPtrT::Private::connectApplicationDeletedDocument, App::DocumentWeakPtrT::Private::deletedDocument(), toolbit-attributes::doc, App::GetApplication(), and App::Application::signalDeleteDocument.
Member Function Documentation
deletedDocument() [1/2]
void App::DocumentWeakPtrT::Private::deletedDocument (const App::Document & doc) inline
Definition at line 700 of file App/DocumentObserver.cpp.
References App::DocumentWeakPtrT::Private::_document, toolbit-attributes::doc, and App::DocumentWeakPtrT::Private::reset().
deletedDocument() [2/2]
void App::DocumentWeakPtrT::Private::deletedDocument (const Gui::Document & doc) inline
Definition at line 242 of file Gui/DocumentObserver.cpp.
References toolbit-attributes::doc, and Gui::DocumentWeakPtrT::reset().
Referenced by App::DocumentWeakPtrT::Private::Private().
reset() [1/2]
void App::DocumentWeakPtrT::Private::reset () inline
Definition at line 246 of file Gui/DocumentObserver.cpp.
Referenced by ArchVRM.Renderer::__init__(), App::DocumentWeakPtrT::Private::deletedDocument(), draftguitools.gui_trackers.gridTracker::set(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testAll(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testBuildings(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCommonPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCustom(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testExtrusions(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testHierarchy(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testIFC4(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testMaterials(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testQuantities(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testRectangleProfileDef(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSites(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSolid(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandardCases(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandards(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStoreys(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testTinyLines(), and bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testUndefined().
reset() [2/2]
void App::DocumentWeakPtrT::Private::reset () inline
Definition at line 706 of file App/DocumentObserver.cpp.
References App::DocumentWeakPtrT::Private::_document, and App::DocumentWeakPtrT::Private::connectApplicationDeletedDocument.
Referenced by ArchVRM.Renderer::__init__(), draftguitools.gui_trackers.gridTracker::set(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testAll(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testBuildings(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCommonPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCustom(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testExtrusions(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testHierarchy(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testIFC4(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testMaterials(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testQuantities(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testRectangleProfileDef(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSites(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSolid(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandardCases(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandards(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStoreys(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testTinyLines(), and bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testUndefined().
Member Data Documentation
_document [1/2]
Gui::Document* App::DocumentWeakPtrT::Private::_document
Definition at line 251 of file Gui/DocumentObserver.cpp.
Referenced by App::DocumentWeakPtrT::Private::deletedDocument(), and App::DocumentWeakPtrT::Private::reset().
_document [2/2]
App::Document* App::DocumentWeakPtrT::Private::_document
Definition at line 712 of file App/DocumentObserver.cpp.
connectApplicationDeletedDocument
Connection App::DocumentWeakPtrT::Private::connectApplicationDeletedDocument
Definition at line 253 of file Gui/DocumentObserver.cpp.
Referenced by App::DocumentWeakPtrT::Private::Private(), and App::DocumentWeakPtrT::Private::reset().
The documentation for this class was generated from the following file:
Gui/DocumentObserver.cpp