FreeCAD: TechDrawGui::DrawGuiUtil Class Reference
TechDrawGui::DrawGuiUtil Class Reference
Convenient utility functions for TechDraw Gui Module.
#include <DrawGuiUtil.h>
Static Public Member Functions
static TechDraw::DrawPage * findPage (Gui::Command *cmd, bool findAny=false)
static bool isDraftObject (App::DocumentObject *obj)
static bool isArchObject (App::DocumentObject *obj)
static bool isArchSection (App::DocumentObject *obj)
static bool needPage (Gui::Command *cmd, bool findAny=false)
static bool needView (Gui::Command *cmd, bool partOnly=true)
static void dumpRectF (const char *text, const QRectF &r)
static void dumpPointF (const char *text, const QPointF &p)
static std::pair< Base::Vector3d, Base::Vector3d > get3DDirAndRot ()
static std::pair< Base::Vector3d, Base::Vector3d > getProjDirFromFace (App::DocumentObject *obj, std::string faceName)
static void loadArrowBox (QComboBox *qcb)
static void loadBalloonShapeBox (QComboBox *qballooncb)
static void loadMattingStyleBox (QComboBox *qmattingcb)
static void loadLineStandardsChoices (QComboBox *combo)
static void loadLineStyleChoices (QComboBox *combo, TechDraw::LineGenerator *generator=nullptr)
static void loadLineGroupChoices (QComboBox *combo)
static QIcon iconForLine (size_t lineNumber, TechDraw::LineGenerator *generator)
make an icon that shows a sample of lineNumber in the current line standard
static double roundToDigits (double original, int digits)
static bool isSelectedInTree (QGraphicsItem *item)
static void setSelectedTree (QGraphicsItem *item, bool selected)
static bool isStyleSheetDark (std::string curStyleSheet)
static QIcon maskBlackPixels (QIcon itemIcon, QSize iconSize, QColor textColor)
static Base::Vector3d fromSceneCoords (const Base::Vector3d &sceneCoord, bool invert=true)
convert point from scene coords to mm and conventional Y axis (page coords).
static Base::Vector3d toSceneCoords (const Base::Vector3d &pageCoord, bool invert=true)
convert point from printed page coords to scene units (Rez(mm) and inverted Y axis (scene coords)
static Base::Vector3d toGuiPoint (TechDraw::DrawView *obj, const Base::Vector3d &toConvert)
convert unscaled, unrotated point to scaled, rotated view coordinates
static bool findObjectInSelection (const std::vector< Gui::SelectionObject > &selection, const App::DocumentObject &targetObject)
true if targetObj is in the selection list
static std::vector< std::string > getSubsForSelectedObject (const std::vector< Gui::SelectionObject > &selection, App::DocumentObject *selectedObj)
Detailed Description
Convenient utility functions for TechDraw Gui Module.
Definition at line 57 of file DrawGuiUtil.h.
Member Function Documentation
dumpPointF()
void DrawGuiUtil::dumpPointF (const char * text, const QPointF & p) static
Definition at line 561 of file DrawGuiUtil.cpp.
References Base::Console(), Base::ConsoleSingleton::Message(), and buildPsets::p.
dumpRectF()
void DrawGuiUtil::dumpRectF (const char * text, const QRectF & r) static
Definition at line 545 of file DrawGuiUtil.cpp.
References Base::Console(), and Base::ConsoleSingleton::Message().
findObjectInSelection()
bool DrawGuiUtil::findObjectInSelection (const std::vector< Gui::SelectionObject > & selection, const App::DocumentObject & targetObject) static
true if targetObj is in the selection list
Definition at line 738 of file DrawGuiUtil.cpp.
References Path.Dressup.Utils::selection().
Referenced by TechDrawGui::QGIPrimPath::mousePressEvent().
findPage()
TechDraw::DrawPage * DrawGuiUtil::findPage (Gui::Command * cmd, bool findAny = false) static
Definition at line 283 of file DrawGuiUtil.cpp.
References toolbit-attributes::doc, App::GetApplication(), Base::Persistence::getClassTypeId(), Gui::Command::getDocument(), App::Application::getDocuments(), TechDrawGui::QGSPage::getDrawPage(), Gui::getMainWindow(), App::DocumentObject::getNameInDocument(), App::Document::getObjectsOfType(), Gui::SelectionSingleton::getObjectsOfType(), TechDrawGui::ViewProviderPage::getQGSPage(), TechDrawGui::DlgPageChooser::getSelection(), Gui::Command::getSelection(), TechDrawGui::MDIViewPage::getViewProviderPage(), App::ExpressionParser::labels, femtools.tokrules::names, src.Mod.PartDesign.fcgear.svggear::w, and Path.Log::warning().
fromSceneCoords()
Base::Vector3d DrawGuiUtil::fromSceneCoords (const Base::Vector3d & sceneCoord, bool invert = true) static
convert point from scene coords to mm and conventional Y axis (page coords).
Definition at line 698 of file DrawGuiUtil.cpp.
References TechDrawGui::Rez::appX(), draftgeoutils.edges::invert(), TechDraw::DrawUtil::invertY(), and result.
get3DDirAndRot()
std::pair< Base::Vector3d, Base::Vector3d > DrawGuiUtil::get3DDirAndRot () static
Definition at line 567 of file DrawGuiUtil.cpp.
References Gui::Application::activeDocument(), Base::Vector3< float_type >::Cross(), Gui::Document::getMDIViews(), Gui::View3DInventor::getViewer(), Gui::Application::Instance, test::m, result, and OfflineRenderingUtils::viewer().
Referenced by TechDrawGui::TaskProjGroup::rotateButtonClicked(), and TechDrawGui::TaskComplexSection::setUiPrimary().
getProjDirFromFace()
std::pair< Base::Vector3d, Base::Vector3d > DrawGuiUtil::getProjDirFromFace (App::DocumentObject * obj, std::string faceName) static
Definition at line 616 of file DrawGuiUtil.cpp.
References Base::Console(), Part::Feature::getShape(), src.Mod.Test.testPathArray::orient, src.Mod.Test.UnitTests::ts(), draftgeoutils.general::v1(), SurfaceTests.TestBlendCurve::vec, and Base::ConsoleSingleton::Warning().
Referenced by TechDrawGui::TaskProjGroup::rotateButtonClicked().
getSubsForSelectedObject()
std::vector< std::string > DrawGuiUtil::getSubsForSelectedObject (const std::vector< Gui::SelectionObject > & selection, App::DocumentObject * selectedObj) static
Definition at line 749 of file DrawGuiUtil.cpp.
References Path.Dressup.Utils::selection().
Referenced by TechDrawGui::QGIView::mousePressEvent().
iconForLine()
QIcon DrawGuiUtil::iconForLine (size_t lineNumber, TechDraw::LineGenerator * generator) static
make an icon that shows a sample of lineNumber in the current line standard
Definition at line 214 of file DrawGuiUtil.cpp.
References App::GetApplication(), ParameterGrp::GetASCII(), TechDraw::LineGenerator::getLinePen(), and App::Application::GetParameterGroupByPath().
isArchObject()
bool DrawGuiUtil::isArchObject (App::DocumentObject * obj) static
Definition at line 432 of file DrawGuiUtil.cpp.
References SCL.SimpleDataTypes::e, App::ExtensionContainer::getPropertyByName(), App::PropertyPythonObject::getValue(), mod, result, and src.Mod.Test.testmakeWireString::String.
isArchSection()
bool DrawGuiUtil::isArchSection (App::DocumentObject * obj) static
Definition at line 463 of file DrawGuiUtil.cpp.
References SCL.SimpleDataTypes::e, App::ExtensionContainer::getPropertyByName(), App::PropertyPythonObject::getValue(), mod, result, and src.Mod.Test.testmakeWireString::String.
isDraftObject()
bool DrawGuiUtil::isDraftObject (App::DocumentObject * obj) static
Definition at line 399 of file DrawGuiUtil.cpp.
References SCL.SimpleDataTypes::e, App::ExtensionContainer::getPropertyByName(), App::PropertyPythonObject::getValue(), mod, result, and src.Mod.Test.testmakeWireString::String.
isSelectedInTree()
bool DrawGuiUtil::isSelectedInTree (QGraphicsItem * item) static
Definition at line 667 of file DrawGuiUtil.cpp.
isStyleSheetDark()
bool DrawGuiUtil::isStyleSheetDark (std::string curStyleSheet) static
Definition at line 760 of file DrawGuiUtil.cpp.
loadArrowBox()
void DrawGuiUtil::loadArrowBox (QComboBox * qcb) static
Definition at line 85 of file DrawGuiUtil.cpp.
References App::GetApplication(), ParameterGrp::GetASCII(), App::Application::GetParameterGroupByPath(), SplineSurface::i, and src.Mod.AddonManager.Addon::translate.
Referenced by TechDrawGui::DlgPrefsTechDrawAnnotationImp::loadSettings(), TechDrawGui::DlgPrefsTechDrawDimensionsImp::loadSettings(), TechDrawGui::TaskLeaderLine::setUiEdit(), TechDrawGui::TaskLeaderLine::setUiPrimary(), and TechDrawGui::TaskBalloon::TaskBalloon().
loadBalloonShapeBox()
void DrawGuiUtil::loadBalloonShapeBox (QComboBox * qballooncb) static
Definition at line 111 of file DrawGuiUtil.cpp.
References App::GetApplication(), ParameterGrp::GetASCII(), App::Application::GetParameterGroupByPath(), SplineSurface::i, and src.Mod.AddonManager.Addon::translate.
Referenced by TechDrawGui::DlgPrefsTechDrawAnnotationImp::loadSettings().
loadLineGroupChoices()
void DrawGuiUtil::loadLineGroupChoices (QComboBox * combo) static
Definition at line 195 of file DrawGuiUtil.cpp.
References importOCA::getline().
Referenced by TechDrawGui::DlgPrefsTechDrawAnnotationImp::loadSettings().
loadLineStandardsChoices()
void DrawGuiUtil::loadLineStandardsChoices (QComboBox * combo) static
Definition at line 162 of file DrawGuiUtil.cpp.
Referenced by TechDrawGui::DlgPrefsTechDrawAnnotationImp::loadSettings().
loadLineStyleChoices()
void DrawGuiUtil::loadLineStyleChoices (QComboBox * combo, TechDraw::LineGenerator * generator = nullptr) static
Definition at line 172 of file DrawGuiUtil.cpp.
References TechDraw::LineGenerator::getLoadedDescriptions(), and src.Mod.AddonManager.Addon::translate.
Referenced by TechDrawGui::TaskLineDecor::initUi(), TechDrawGui::DlgPrefsTechDrawAnnotationImp::loadLineStyleBoxes(), TechDrawGui::TaskCenterLine::setUiEdit(), TechDrawGui::TaskSelectLineAttributes::setUiEdit(), and TechDrawGui::TaskCenterLine::setUiPrimary().
loadMattingStyleBox()
void DrawGuiUtil::loadMattingStyleBox (QComboBox * qmattingcb) static
Definition at line 137 of file DrawGuiUtil.cpp.
References App::GetApplication(), ParameterGrp::GetASCII(), App::Application::GetParameterGroupByPath(), SplineSurface::i, and src.Mod.AddonManager.Addon::translate.
Referenced by TechDrawGui::DlgPrefsTechDrawAnnotationImp::loadSettings().
maskBlackPixels()
QIcon DrawGuiUtil::maskBlackPixels (QIcon itemIcon, QSize iconSize, QColor textColor) static
Definition at line 770 of file DrawGuiUtil.cpp.
References geoff_geometry::Normal(), and geoff_geometry::On().
needPage()
bool DrawGuiUtil::needPage (Gui::Command * cmd, bool findAny = false) static
Definition at line 494 of file DrawGuiUtil.cpp.
References toolbit-attributes::doc, App::GetApplication(), Base::Persistence::getClassTypeId(), Gui::Command::getDocument(), App::Application::getDocuments(), App::Document::getObjectsOfType(), and Gui::Command::hasActiveDocument().
Referenced by isDimCmdActive().
needView()
bool DrawGuiUtil::needView (Gui::Command * cmd, bool partOnly = true) static
Definition at line 523 of file DrawGuiUtil.cpp.
References Base::Persistence::getClassTypeId(), Gui::Command::getDocument(), App::Document::getObjectsOfType(), Gui::Command::hasActiveDocument(), and TechDrawTools.TDToolsUtil::haveView().
Referenced by isDimCmdActive().
roundToDigits()
double DrawGuiUtil::roundToDigits (double original, int digits) static
Definition at line 657 of file DrawGuiUtil.cpp.
References Base::pow(), and DraftVecUtils::rounded().
setSelectedTree()
void DrawGuiUtil::setSelectedTree (QGraphicsItem * item, bool selected) static
Definition at line 685 of file DrawGuiUtil.cpp.
toGuiPoint()
Base::Vector3d DrawGuiUtil::toGuiPoint (TechDraw::DrawView * obj, const Base::Vector3d & toConvert) static
convert unscaled, unrotated point to scaled, rotated view coordinates
Definition at line 722 of file DrawGuiUtil.cpp.
References TechDraw::DrawView::getScale(), App::PropertyQuantity::getValue(), TechDrawGui::Rez::guiX(), TechDraw::DrawUtil::invertY(), result, TechDraw::DrawView::Rotation, and Base::toRadians().
Referenced by TechDrawGui::QGIViewBalloon::getBalloonPoints().
toSceneCoords()
Base::Vector3d DrawGuiUtil::toSceneCoords (const Base::Vector3d & pageCoord, bool invert = true) static
convert point from printed page coords to scene units (Rez(mm) and inverted Y axis (scene coords)
Definition at line 710 of file DrawGuiUtil.cpp.
References TechDrawGui::Rez::guiX(), draftgeoutils.edges::invert(), TechDraw::DrawUtil::invertY(), and result.
Referenced by TechDrawGui::TaskLeaderLine::onTrackerClicked().
The documentation for this class was generated from the following files:
DrawGuiUtil.h
DrawGuiUtil.cpp