FreeCAD: Gui::PreferencePackManager Class Reference
Gui::PreferencePackManager Class Reference
#include <PreferencePackManager.h>
Classes
struct TemplateFile
Public Member Functions
PreferencePackManager ()
~PreferencePackManager ()=default
void rescan ()
std::vector< std::string > preferencePackNames () const
std::map< std::string, PreferencePack > preferencePacks () const
bool apply (const std::string &preferencePackName) const
bool isVisible (const std::string &addonName, const std::string &preferencePackName) const
void toggleVisibility (const std::string &addonName, const std::string &preferencePackName)
void deleteUserPack (const std::string &name)
void save (const std::string &name, const std::string &directory, const std::vector< TemplateFile > &templates)
std::vector< TemplateFile > templateFiles (bool rescan=false)
std::vector< boost::filesystem::path > configBackups () const
void importConfig (const std::string &packName, const boost::filesystem::path &path)
std::vector< boost::filesystem::path > modPaths () const
boost::filesystem::path getSavedPreferencePacksPath () const
boost::filesystem::path getResourcePreferencePacksPath () const
std::vector< std::string > getPacksFromDirectory (const boost::filesystem::path &path) const
Detailed Description
and loadable collections of user preferences
This class provides some additional utility functions for allowing users to save their current preferences as a PreferencePack based on a set of template files provided either in the main FreeCAD distribution, or inside various installed mods.
Definition at line 106 of file PreferencePackManager.h.
Constructor & Destructor Documentation
PreferencePackManager()
PreferencePackManager::PreferencePackManager ()
Definition at line 149 of file PreferencePackManager.cpp.
References getResourcePreferencePacksPath(), getSavedPreferencePacksPath(), and rescan().
~PreferencePackManager()
Gui::PreferencePackManager::~PreferencePackManager () default
Member Function Documentation
apply()
bool PreferencePackManager::apply (const std::string & preferencePackName) const
Apply the named preferencePack
Returns
True if the preferencePack was applied, or false if it was not
Definition at line 351 of file PreferencePackManager.cpp.
References Gui::ToolBarManager::getInstance(), Gui::DockWindowManager::instance(), Gui::DockWindowManager::loadState(), and Gui::ToolBarManager::restoreState().
configBackups()
std::vector< boost::filesystem::path > Gui::PreferencePackManager::configBackups () const
Get a list of all available config file backups. Backups are currently stored for one week.
Definition at line 645 of file PreferencePackManager.cpp.
Referenced by Gui::Dialog::DlgSettingsGeneral::DlgSettingsGeneral(), and Gui::Dialog::DlgRevertToBackupConfigImp::showEvent().
deleteUserPack()
void Gui::PreferencePackManager::deleteUserPack (const std::string & name)
Deletes the user-saved pack specified by name
Definition at line 426 of file PreferencePackManager.cpp.
Referenced by Gui::Dialog::DlgPreferencePackManagementImp::deleteUserPack().
getPacksFromDirectory()
std::vector< std::string > Gui::PreferencePackManager::getPacksFromDirectory (const boost::filesystem::path & path) const
Collect all preference packs of a directory.
Definition at line 275 of file PreferencePackManager.cpp.
References Base::Console(), App::Metadata::content(), Base::ConsoleSingleton::Error(), and src.Mod.Test.testPathArray::path.
Referenced by Gui::Dialog::DlgPreferencePackManagementImp::showEvent().
getResourcePreferencePacksPath()
boost::filesystem::path Gui::PreferencePackManager::getResourcePreferencePacksPath () const
Get the path to the preference packs of the resource directory.
Definition at line 270 of file PreferencePackManager.cpp.
References getResourcePrefPacksPath().
Referenced by PreferencePackManager(), and Gui::Dialog::DlgPreferencePackManagementImp::showEvent().
getSavedPreferencePacksPath()
boost::filesystem::path Gui::PreferencePackManager::getSavedPreferencePacksPath () const
Get the path to the saved preference packs.
Definition at line 265 of file PreferencePackManager.cpp.
References getSavedPrefPacksPath().
Referenced by PreferencePackManager(), save(), and Gui::Dialog::DlgPreferencePackManagementImp::showEvent().
importConfig()
void Gui::PreferencePackManager::importConfig (const std::string & packName, const boost::filesystem::path & path)
Import an existing config file as a preference pack with a given name.
Definition at line 230 of file PreferencePackManager.cpp.
References src.Mod.Test.testPathArray::path.
Referenced by Gui::Dialog::DlgSettingsGeneral::onImportConfigClicked().
isVisible()
bool PreferencePackManager::isVisible (const std::string & addonName, const std::string & preferencePackName) const
Check the visibility of the specified pack
Returns
True if the preferencePack is visible, or false if not. All packs are visible by default, but can be marked as "invisible" (i.e. not returned by the manager in lists of packs) by using the toggleVisibility function.
Definition at line 387 of file PreferencePackManager.cpp.
References App::GetApplication(), ParameterGrp::GetGroups(), and App::Application::GetParameterGroupByPath().
Referenced by ArchVRM.Renderer::removeHidden().
modPaths()
std::vector< boost::filesystem::path > Gui::PreferencePackManager::modPaths () const
Get a list of all mod directories.
Definition at line 247 of file PreferencePackManager.cpp.
References App::Application::Config(), App::Application::getUserAppDataDir(), src.Mod.Test.testPathArray::path, result, split(), and Base::FileInfo::stringToPath().
Referenced by Gui::Dialog::DlgPreferencePackManagementImp::showEvent(), and templateFiles().
preferencePackNames()
std::vector< std::string > PreferencePackManager::preferencePackNames () const
Get an alphabetical list of names of all visible PreferencePacks
Definition at line 337 of file PreferencePackManager.cpp.
References femtools.tokrules::names.
Referenced by Gui::Dialog::DlgSettingsGeneral::onImportConfigClicked().
preferencePacks()
std::map< std::string, PreferencePack > Gui::PreferencePackManager::preferencePacks () const
Get a map of all visible PreferencePack names and their associated packs
Definition at line 346 of file PreferencePackManager.cpp.
Referenced by Gui::Dialog::DlgSettingsGeneral::loadThemes(), Gui::Dialog::DlgSettingsGeneral::recreatePreferencePackMenu(), and Gui::Dialog::DlgSettingsGeneral::saveThemes().
rescan()
void PreferencePackManager::rescan ()
Rescan the preferencePack directory and update the available PreferencePacks
Definition at line 162 of file PreferencePackManager.cpp.
References mod, and src.Mod.Test.testPathArray::path.
Referenced by Gui::Dialog::DlgSettingsGeneral::loadThemes(), bimcommands.BimMaterial.BIM_Material::onDelete(), bimcommands.BimMaterial.BIM_Material::onDeleteUnused(), bimcommands.BimMaterial.BIM_Material::onDuplicate(), bimcommands.BimMaterial.BIM_Material::onMergeDupes(), bimcommands.BimMaterial.BIM_Material::onMergeTo(), PreferencePackManager(), Gui::Dialog::DlgSettingsGeneral::recreatePreferencePackMenu(), Gui::Dialog::DlgSettingsGeneral::saveThemes(), templateFiles(), and toggleVisibility().
save()
void PreferencePackManager::save (const std::string & name, const std::string & directory, const std::vector< TemplateFile > & templates)
Save current settings as a (possibly new) preferencePack
If the named preferencePack does not exist, this creates it on disk. If it does exist, this overwrites the original.
Definition at line 507 of file PreferencePackManager.cpp.
References copyTemplateParameters(), ParameterManager::Create(), getSavedPreferencePacksPath(), src.Mod.Test.testPathArray::path, Base::FileInfo::pathToString(), and InitGui::t.
Referenced by src.Mod.Show.mTempoVis.TempoVis::modify(), src.Mod.Show.mTempoVis.TempoVis::modifyVPProperty(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onSaveStyle(), src.Mod.Show.mTempoVis.TempoVis::saveCamera(), and nativeifc.ifc_viewproviders.ifc_vp_document::setupContextMenu().
templateFiles()
std::vector< PreferencePackManager::TemplateFile > PreferencePackManager::templateFiles (bool rescan = false)
Definition at line 580 of file PreferencePackManager.cpp.
References App::Application::getResourceDir(), toolbit-attributes::group, mod, modPaths(), src.Mod.Test.testPathArray::path, Base::FileInfo::pathToString(), rescan(), scanForTemplateFiles(), and Base::FileInfo::stringToPath().
Referenced by Gui::Dialog::DlgSettingsGeneral::newPreferencePackDialogAccepted().
toggleVisibility()
void PreferencePackManager::toggleVisibility (const std::string & addonName, const std::string & preferencePackName)
Toggle the visibility of the named preference pack in a named addon
Definition at line 403 of file PreferencePackManager.cpp.
References findUnusedName(), App::GetApplication(), ParameterGrp::GetGroups(), App::Application::GetParameterGroupByPath(), toolbit-attributes::group, and rescan().
Referenced by Gui::Dialog::DlgPreferencePackManagementImp::hideBuiltInPack(), and Gui::Dialog::DlgPreferencePackManagementImp::hideInstalledPack().
The documentation for this class was generated from the following files:
PreferencePackManager.h
PreferencePackManager.cpp