FreeCAD: Materials::MaterialProperty Class Reference
Materials::MaterialProperty Class Reference
#include <Materials.h>
Public Member Functions
MaterialProperty ()
MaterialProperty (const MaterialProperty &other)
MaterialProperty (const ModelProperty &other, QString modelUUID)
MaterialProperty (const std::shared_ptr< MaterialProperty > &other)
~MaterialProperty () override=default
MaterialValue::ValueType getType () const
const QString getModelUUID () const
QVariant getValue ()
QVariant getValue () const
QList< QVariant > getList ()
QList< QVariant > getList () const
bool isNull () const
std::shared_ptr< MaterialValue > getMaterialValue ()
std::shared_ptr< MaterialValue > getMaterialValue () const
QString getString () const
QString getYAMLString () const
QString getDictionaryString () const
bool getBoolean () const
int getInt () const
double getFloat () const
const Base::Quantity & getQuantity () const
QString getURL () const
App::Color getColor () const
MaterialProperty & getColumn (int column)
const MaterialProperty & getColumn (int column) const
MaterialValue::ValueType getColumnType (int column) const
QString getColumnUnits (int column) const
QVariant getColumnNull (int column) const
void setModelUUID (const QString &uuid)
void setPropertyType (const QString &type) override
void setValue (const QVariant &value)
void setValue (const QString &value)
void setValue (const std::shared_ptr< MaterialValue > &value)
void setString (const QString &value)
void setString (const std::string &value)
void setBoolean (bool value)
void setBoolean (int value)
void setBoolean (const QString &value)
void setInt (int value)
void setInt (const QString &value)
void setFloat (double value)
void setFloat (const QString &value)
void setQuantity (const Base::Quantity &value)
void setQuantity (double value, const QString &units)
void setQuantity (const QString &value)
void setList (const QList< QVariant > &value)
void setURL (const QString &value)
void setColor (const App::Color &value)
MaterialProperty & operator= (const MaterialProperty &other)
bool operator== (const MaterialProperty &other) const
bool operator!= (const MaterialProperty &other) const
Public Member Functions inherited from Materials::ModelProperty
ModelProperty ()
ModelProperty (const QString &name, const QString &header, const QString &type, const QString &units, const QString &url, const QString &description)
ModelProperty (const ModelProperty &other)
~ModelProperty () override=default
const QString getName () const
const QString getDisplayName () const
const QString getPropertyType () const
const QString getUnits () const
const QString getURL () const
const QString getDescription () const
const QString getInheritance () const
bool isInherited () const
void setName (const QString &name)
void setColumnHeader (const QString &header)
void setUnits (const QString &units)
void setURL (const QString &url)
void setDescription (const QString &description)
void setInheritance (const QString &uuid)
void addColumn (ModelProperty &column)
const std::vector< ModelProperty > & getColumns () const
int columns () const
ModelProperty & operator= (const ModelProperty &other)
bool operator== (const ModelProperty &other) const
bool operator!= (const ModelProperty &other) const
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Member Functions
void setType (const QString &type)
void copyValuePtr (const std::shared_ptr< MaterialValue > &value)
void addColumn (MaterialProperty &column)
Friends
QTextStream & operator<< (QTextStream &output, const MaterialProperty &property)
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 67 of file Materials.h.
Constructor & Destructor Documentation
MaterialProperty() [1/4]
MaterialProperty::MaterialProperty ()
Definition at line 46 of file Materials.cpp.
References Materials::MaterialValue::None.
MaterialProperty() [2/4]
MaterialProperty::MaterialProperty (const MaterialProperty & other)
Definition at line 79 of file Materials.cpp.
References copyValuePtr().
MaterialProperty() [3/4]
MaterialProperty::MaterialProperty (const ModelProperty & other, QString modelUUID) explicit
Definition at line 51 of file Materials.cpp.
References addColumn(), Materials::ModelProperty::columns(), Materials::ModelProperty::getColumns(), Materials::ModelProperty::getPropertyType(), and setType().
MaterialProperty() [4/4]
MaterialProperty::MaterialProperty (const std::shared_ptr< MaterialProperty > & other) explicit
Definition at line 90 of file Materials.cpp.
~MaterialProperty()
Materials::MaterialProperty::~MaterialProperty () override default
Member Function Documentation
addColumn()
void Materials::MaterialProperty::addColumn (MaterialProperty & column) inline protected
Definition at line 167 of file Materials.h.
Referenced by MaterialProperty(), and src.Mod.PartDesign.WizardShaft.WizardShaftTable.WizardShaftTable::slotInsertColumn().
copyValuePtr()
void MaterialProperty::copyValuePtr (const std::shared_ptr< MaterialValue > & value) protected
Definition at line 64 of file Materials.cpp.
References Materials::MaterialValue::Array2D, and Materials::MaterialValue::Array3D.
Referenced by MaterialProperty(), and operator=().
getBoolean()
bool Materials::MaterialProperty::getBoolean () const inline
Definition at line 107 of file Materials.h.
getColor()
App::Color MaterialProperty::getColor () const
Definition at line 145 of file Materials.cpp.
References blue, SCL.SimpleDataTypes::c, getValue(), green, and red.
getColumn() [1/2]
MaterialProperty & MaterialProperty::getColumn (int column)
Definition at line 223 of file Materials.cpp.
References App::ExpressionParser::column.
getColumn() [2/2]
const MaterialProperty & MaterialProperty::getColumn (int column) const
Definition at line 233 of file Materials.cpp.
References App::ExpressionParser::column.
getColumnNull()
QVariant MaterialProperty::getColumnNull (int column) const
Definition at line 263 of file Materials.cpp.
References App::ExpressionParser::column, Materials::MaterialValue::Float, getColumnType(), getColumnUnits(), Materials::MaterialValue::Integer, src.Mod.PartDesign.PartDesignTests.TestInvoluteGear::Quantity, and Materials::MaterialValue::Quantity.
getColumnType()
MaterialValue::ValueType MaterialProperty::getColumnType (int column) const
Definition at line 243 of file Materials.cpp.
References App::ExpressionParser::column.
Referenced by getColumnNull().
getColumnUnits()
QString MaterialProperty::getColumnUnits (int column) const
Definition at line 253 of file Materials.cpp.
References App::ExpressionParser::column.
Referenced by getColumnNull().
getDictionaryString()
QString MaterialProperty::getDictionaryString () const
Definition at line 171 of file Materials.cpp.
References Materials::MaterialValue::Float, getType(), getValue(), isNull(), Materials::MaterialValue::PRECISION, and Materials::MaterialValue::Quantity.
getFloat()
double Materials::MaterialProperty::getFloat () const inline
Definition at line 115 of file Materials.h.
getInt()
int Materials::MaterialProperty::getInt () const inline
Definition at line 111 of file Materials.h.
getList() [1/2]
QList<QVariant> Materials::MaterialProperty::getList () inline
Definition at line 90 of file Materials.h.
getList() [2/2]
QList<QVariant> Materials::MaterialProperty::getList () const inline
Definition at line 94 of file Materials.h.
getMaterialValue() [1/2]
std::shared_ptr< MaterialValue > MaterialProperty::getMaterialValue ()
Definition at line 109 of file Materials.cpp.
getMaterialValue() [2/2]
std::shared_ptr<MaterialValue> Materials::MaterialProperty::getMaterialValue () const
getModelUUID()
const QString Materials::MaterialProperty::getModelUUID () const inline
Definition at line 83 of file Materials.h.
getQuantity()
const Base::Quantity& Materials::MaterialProperty::getQuantity () const
Referenced by materialtests.TestMaterials.MaterialTestCases::test2DArray(), materialtests.TestMaterials.MaterialTestCases::test3DArray(), materialtests.TestMaterials.MaterialTestCases::testCalculiXSteel(), and materialtests.TestMaterialCreation.MaterialCreationTestCases::testCreateMaterial().
getString()
QString MaterialProperty::getString () const
Definition at line 119 of file Materials.cpp.
References Materials::MaterialValue::Float, getType(), getValue(), isNull(), Materials::MaterialValue::PRECISION, and Materials::MaterialValue::Quantity.
getType()
MaterialValue::ValueType Materials::MaterialProperty::getType () const inline
Definition at line 78 of file Materials.h.
Referenced by getDictionaryString(), and getString().
getURL()
QString Materials::MaterialProperty::getURL () const inline
Definition at line 120 of file Materials.h.
getValue() [1/2]
QVariant MaterialProperty::getValue ()
Definition at line 99 of file Materials.cpp.
Referenced by getColor(), getDictionaryString(), and getString().
getValue() [2/2]
QVariant Materials::MaterialProperty::getValue () const
getYAMLString()
QString MaterialProperty::getYAMLString () const
Definition at line 140 of file Materials.cpp.
isNull()
bool Materials::MaterialProperty::isNull () const inline
Definition at line 98 of file Materials.h.
Referenced by getDictionaryString(), and getString().
operator!=()
bool Materials::MaterialProperty::operator!= (const MaterialProperty & other) const inline
Definition at line 157 of file Materials.h.
operator=()
MaterialProperty & MaterialProperty::operator= (const MaterialProperty & other)
Definition at line 420 of file Materials.cpp.
References copyValuePtr(), and Materials::ModelProperty::operator=().
operator==()
bool MaterialProperty::operator== (const MaterialProperty & other) const
Definition at line 439 of file Materials.cpp.
setBoolean() [1/3]
void MaterialProperty::setBoolean (bool value)
Definition at line 339 of file Materials.cpp.
Referenced by setBoolean(), and setValue().
setBoolean() [2/3]
void MaterialProperty::setBoolean (const QString & value)
Definition at line 349 of file Materials.cpp.
References setBoolean(), and toolbit-attributes::val.
setBoolean() [3/3]
void MaterialProperty::setBoolean (int value)
Definition at line 344 of file Materials.cpp.
setColor()
void MaterialProperty::setColor (const App::Color & value)
Definition at line 413 of file Materials.cpp.
References App::Color::a, App::Color::b, App::Color::g, and App::Color::r.
setFloat() [1/2]
void MaterialProperty::setFloat (const QString & value)
Definition at line 381 of file Materials.cpp.
setFloat() [2/2]
void MaterialProperty::setFloat (double value)
Definition at line 376 of file Materials.cpp.
Referenced by setValue().
setInt() [1/2]
void MaterialProperty::setInt (const QString & value)
Definition at line 371 of file Materials.cpp.
setInt() [2/2]
void MaterialProperty::setInt (int value)
Definition at line 366 of file Materials.cpp.
Referenced by setValue().
setList()
void MaterialProperty::setList (const QList< QVariant > & value)
Definition at line 403 of file Materials.cpp.
setModelUUID()
void MaterialProperty::setModelUUID (const QString & uuid)
Definition at line 94 of file Materials.cpp.
setPropertyType()
void MaterialProperty::setPropertyType (const QString & type) override virtual
Reimplemented from Materials::ModelProperty.
Definition at line 195 of file Materials.cpp.
References Materials::ModelProperty::setPropertyType(), setType(), and Path.Post.scripts.grbl_post::type.
setQuantity() [1/3]
void MaterialProperty::setQuantity (const Base::Quantity & value)
Definition at line 386 of file Materials.cpp.
References Materials::MaterialValue::getQuantityFormat(), and Base::Quantity::setFormat().
Referenced by setQuantity(), and setValue().
setQuantity() [2/3]
void MaterialProperty::setQuantity (const QString & value)
Definition at line 398 of file Materials.cpp.
References Base::Quantity::parse(), and setQuantity().
setQuantity() [3/3]
void MaterialProperty::setQuantity (double value, const QString & units)
Definition at line 393 of file Materials.cpp.
References setQuantity().
setString() [1/2]
void MaterialProperty::setString (const QString & value)
Definition at line 329 of file Materials.cpp.
Referenced by setValue().
setString() [2/2]
void MaterialProperty::setString (const std::string & value)
Definition at line 334 of file Materials.cpp.
setType()
void MaterialProperty::setType (const QString & type) protected
Definition at line 201 of file Materials.cpp.
References Materials::MaterialValue::Array2D, Materials::MaterialValue::Array3D, Materials::ModelProperty::columns(), Materials::MaterialValue::mapType(), Materials::MaterialValue::None, and Path.Post.scripts.grbl_post::type.
Referenced by MaterialProperty(), and setPropertyType().
setURL()
void MaterialProperty::setURL (const QString & value)
Definition at line 408 of file Materials.cpp.
Referenced by setValue().
setValue() [1/3]
void MaterialProperty::setValue (const QString & value)
Definition at line 289 of file Materials.cpp.
References Materials::MaterialValue::Array2D, Materials::MaterialValue::Array3D, Materials::MaterialValue::Boolean, Base::Console(), SCL.SimpleDataTypes::e, Materials::MaterialValue::Float, Materials::MaterialValue::Integer, Base::ConsoleSingleton::Log(), Base::Quantity::parse(), Materials::MaterialValue::Quantity, setBoolean(), setFloat(), setInt(), setQuantity(), setString(), setURL(), and Materials::MaterialValue::URL.
setValue() [2/3]
void MaterialProperty::setValue (const QVariant & value)
Definition at line 284 of file Materials.cpp.
setValue() [3/3]
void MaterialProperty::setValue (const std::shared_ptr< MaterialValue > & value)
Definition at line 324 of file Materials.cpp.
Friends And Related Function Documentation
operator<<
QTextStream& operator<< (QTextStream & output, const MaterialProperty & property) friend
Definition at line 497 of file Materials.h.
The documentation for this class was generated from the following files:
Materials.h
Materials.cpp