FreeCAD: Gui::TaskTransform Class Reference
Gui::TaskTransform Class Reference
#include <TaskCSysDragger.h>
Classes
struct CoordinateSystem
Public Types
enum SelectionMode { SelectionMode::None, SelectionMode::SelectTransformOrigin, SelectionMode::SelectAlignTarget }
enum PlacementMode { PlacementMode::ObjectOrigin, PlacementMode::Centroid, PlacementMode::Custom }
enum PositionMode { PositionMode::Local, PositionMode::Global }
Public Member Functions
TaskTransform (Gui::ViewProviderDragger *vp, Gui::SoFCCSysDragger *dragger, QWidget *parent=nullptr, App::SubObjectPlacementProvider *subObjectPlacementProvider=Base::provideService< App::SubObjectPlacementProvider >(), App::CenterOfMassProvider *centerOfMassProvider=Base::provideService< App::CenterOfMassProvider >())
~TaskTransform () override
Public Member Functions inherited from Gui::TaskView::TaskBox
TaskBox (QWidget *parent=nullptr)
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
QSize minimumSizeHint () const override
~TaskBox () override
void hideGroupBox ()
bool isGroupVisible () const
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (QWidget *parent=nullptr)
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
QBoxLayout * groupLayout ()
void setScheme (ActionPanelScheme *pointer)
bool isExpandable () const
bool hasHeader () const
QString headerText () const
QSize minimumSizeHint () const override
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void showHide ()
void setExpandable (bool expandable=true)
void setHeader (bool enable=true)
void setHeaderText (const QString &title)
void setHeaderIcon (const QPixmap &icon)
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Protected Member Functions inherited from Gui::TaskView::TaskBox
void showEvent (QShowEvent *) override
void actionEvent (QActionEvent *) override
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
void paintEvent (QPaintEvent *event) override
Protected Attributes inherited from QSint::ActionGroup
double m_foldStep
double m_foldDelta
double m_fullHeight
double m_tempHeight
int m_foldDirection
QPixmap m_foldPixmap
class TaskHeader * myHeader
class TaskGroup * myGroup
QWidget * myDummy
ActionPanelScheme * myScheme
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Detailed Description
Definition at line 48 of file TaskCSysDragger.h.
Member Enumeration Documentation
PlacementMode
enum Gui::TaskTransform::PlacementMode strong
Enumerator
ObjectOrigin
Centroid
Custom
Definition at line 56 of file TaskCSysDragger.h.
PositionMode
enum Gui::TaskTransform::PositionMode strong
Enumerator
Local
Global
Definition at line 57 of file TaskCSysDragger.h.
SelectionMode
enum Gui::TaskTransform::SelectionMode strong
Enumerator
None
SelectTransformOrigin
SelectAlignTarget
Definition at line 55 of file TaskCSysDragger.h.
Constructor & Destructor Documentation
TaskTransform()
TaskTransform::TaskTransform (Gui::ViewProviderDragger * vp, Gui::SoFCCSysDragger * dragger, QWidget * parent = nullptr, App::SubObjectPlacementProvider * subObjectPlacementProvider = Base::provideService<App::SubObjectPlacementProvider>(), App::CenterOfMassProvider * centerOfMassProvider = Base::provideService<App::CenterOfMassProvider>())
Definition at line 83 of file TaskCSysDragger.cpp.
References Gui::SelectionObserver::blockSelection(), App::GeoFeature::getGlobalPlacement(), Gui::ViewProviderDocumentObject::getObject(), Gui::ViewProviderDragger::getObjectPlacement(), Base::Placement::getRotation(), Base::Placement::inverse(), and Gui::ViewProviderDragger::resetTransformOrigin().
~TaskTransform()
TaskTransform::~TaskTransform () override
Definition at line 110 of file TaskCSysDragger.cpp.
References Gui::Application::commandManager(), Gui::CommandManager::getCommandByName(), Gui::Application::Instance, and Gui::Command::setEnabled().
The documentation for this class was generated from the following files:
TaskCSysDragger.h
TaskCSysDragger.cpp