FreeCAD: Gui::Command Class Reference
Gui::Command Class Reference abstract
#include <Command.h>
Classes
class LogDisabler
Helper class to disable python console log.
Public Member Functions
Helper methods to generate help pages
const char * beginCmdHelp ()
returns the begin of a online help page
const char * endCmdHelp ()
returns the end of a online help page
virtual const char * getHelpUrl () const
Get the help URL.
Helper methods for the Active tests
bool hasActiveDocument () const
true when there is a document
bool hasObject (const char *Name)
true when there is a document and a Feature with Name
checking of internal state
const char * getAppModuleName () const
returns the name to which the command belongs
void setAppModuleName (const char *)
const char * getName () const
Get the command name.
const char * getGroupName () const
Get the name of the grouping of the command.
void setGroupName (const char *)
QString translatedGroupName () const
virtual void setShortcut (const QString &)
Override shortcut of this command.
virtual QString getShortcut () const
Obtain the current shortcut of this command.
Public Member Functions inherited from Gui::CommandBase
Action * getAction () const
virtual const char * getMenuText () const
virtual const char * getToolTipText () const
virtual const char * getStatusTip () const
virtual const char * getWhatsThis () const
virtual const char * getPixmap () const
virtual const char * getAccel () const
void setWhatsThis (const char *)
void setMenuText (const char *)
void setToolTipText (const char *)
void setStatusTip (const char *)
void setPixmap (const char *)
void setAccel (const char *)
virtual const char * className () const =0
The C++ class name is needed as context for the translation framework.
Protected Member Functions
Command (const char *name)
~Command () override
Methods to override when creating a new command
virtual void activated (int iMsg)=0
Methods which gets called when activated, needs to be reimplemented!
Action * createAction () override
Creates the used Action.
void applyCommandData (const char *context, Action *)
Applies the menu text, tool and status tip to the passed action object.
const char * keySequenceToAccel (int) const
void printConflictingAccelerators () const
Protected Member Functions inherited from Gui::CommandBase
CommandBase (const char *sMenu, const char *sToolTip=nullptr, const char *sWhat=nullptr, const char *sStatus=nullptr, const char *sPixmap=nullptr, const char *sAccel=nullptr)
virtual ~CommandBase ()
interface used by the CommandManager and the Action
enum TriggerSource { TriggerNone, TriggerAction, TriggerChildAction }
Command trigger source.
class CommandManager
CommandManager is a friend.
virtual bool isActive ()
Override this method if your Cmd is not always active.
void testActive ()
Get somtile called to check the state of the command.
void setEnabled (bool)
Enables or disables the command.
TriggerSource triggerSource () const
Return the current command trigger source.
void invoke (int index, TriggerSource trigger=TriggerNone)
void addTo (QWidget *)
adds this command to arbitrary widgets
void addToGroup (ActionGroup *, bool checkable)
void addToGroup (ActionGroup *)
void initAction ()
Create the action if not exist.
Helper methods to get important classes
Gui::Document * getActiveGuiDocument () const
Get pointer to the active gui document.
App::Document * getDocument (const char *Name=nullptr) const
bool isViewOfType (Base::Type t) const
checks if the active view is of a special type or derived
App::DocumentObject * getObject (const char *Name) const
returns the named feature or the active one from the active document or NULL
std::string getUniqueObjectName (const char *BaseName, const App::DocumentObject *obj=nullptr) const
static Application * getGuiApplication ()
Get pointer to the Application Window.
static Gui::SelectionSingleton & getSelection ()
Get a reference to the selection.
static std::string getObjectCmd (const char *Name, const App::Document *doc=nullptr, const char *prefix=nullptr, const char *postfix=nullptr, bool gui=false)
returns a python command string to retrieve an object from a document
static std::string getObjectCmd (const App::DocumentObject *obj, const char *prefix=nullptr, const char *postfix=nullptr, bool gui=false)
returns a python command string to retrieve the given object
Helper methods for the Undo/Redo and Update handling
void languageChange () override
Translate command.
void updateAction (int mode) override
Updates the QAction with respect to the passed mode.
void setupCheckable (int iMsg)
Setup checkable actions based on current TriggerSource.
static void openCommand (const char *sName=nullptr)
Open a new Undo transaction on the active document.
static void commitCommand ()
Commit the Undo transaction on the active document.
static void abortCommand ()
Abort the Undo transaction on the active document.
static bool hasPendingCommand ()
Check if an Undo transaction is open on the active document.
static void updateActive ()
Updates the (active) document (propagate changes)
static void updateAll (std::list< Gui::Document * > cList)
Updates the (all or listed) documents (propagate changes)
static bool isActiveObjectValid ()
Checks if the active object of the active document is valid.
Helper methods for issuing commands to the Python interpreter
enum DoCmd_Type { Doc, App, Gui }
types of application level actions for DoCommand()
static void blockCommand (bool)
Blocks all command objects.
static void printPyCaller ()
Print to Python console the current Python calling source file and line number.
static void printCaller (const char *file, int line)
Print to Python console the current calling source file and line number.
static void _doCommand (const char *file, int line, DoCmd_Type eType, const char *sCmd,...)
Run a App level Action.
static void _runCommand (const char *file, int line, DoCmd_Type eType, const char *sCmd)
Run a App level Action.
static void _runCommand (const char *file, int line, DoCmd_Type eType, const QByteArray &sCmd)
Run a App level Action.
static void addModule (DoCmd_Type eType, const char *sModuleName)
import an external (or own) module only once
static std::string _assureWorkbench (const char *file, int line, const char *sName)
Methods for copying visiual properties
const std::string strToPython (const char *Str)
translate a string to a python string literal (needed e.g. in file names for windows...)
const std::string strToPython (const std::string &Str)
static void _copyVisual (const char *file, int line, const char *to, const char *attr, const char *from)
static void _copyVisual (const char *file, int line, const char *to, const char *attr_to, const char *from, const char *attr_from)
static void _copyVisual (const char *file, int line, const App::DocumentObject *to, const char *attr, const App::DocumentObject *from)
static void _copyVisual (const char *file, int line, const App::DocumentObject *to, const char *attr_to, const App::DocumentObject *from, const char *attr_from)
static std::string getPythonTuple (const std::string &name, const std::vector< std::string > &subnames)
Get Python tuple from object and sub-elements.
arbitrary helper methods
enum CmdType {
AlterDoc = 1, Alter3DView = 2, AlterSelection = 4, ForEdit = 8,
NoTransaction = 16
}
class LogDisabler
void adjustCameraPosition ()
Attributes
Set by the inherited constructor to set up the most important properties of the command. In the Command constructor are set default values! The real values should be set in the constructor of the inheriting class.
const char * sAppModule
const char * sGroup
const char * sName
const char * sHelpUrl
int eType
bool bCanLog
Indicate if the command shall log to MacroManager.
Additional Inherited Members
Protected Attributes inherited from Gui::CommandBase
const char * sMenuText
const char * sToolTipText
const char * sWhatsThis
const char * sStatusTip
const char * sPixmap
const char * sAccel
Action * _pcAction
std::string displayText
Detailed Description
The Command class.
This class is mostly used for commands implemented directly in C++ (see PythonCommand). It contains also a lot of helper methods to make implementing commands for FreeCAD as easy as possible.
Note
This class is intended to handle the GUI interaction like:
starting a dialog
doing view and window stuff
anything else, especially altering the document must be done on application level. See doCommand() for details.
See also
CommandManager
Author
Jrgen Riegel
Definition at line 317 of file Gui/Command.h.
Member Enumeration Documentation
CmdType
enum Gui::Command::CmdType protected
Enumerator
AlterDoc
Command change the Document
Alter3DView
Command change the Gui
AlterSelection
Command change the Selection
ForEdit
Command is in a special edit mode active
NoTransaction
Do not setup auto transaction
Definition at line 601 of file Gui/Command.h.
DoCmd_Type
enum Gui::Command::DoCmd_Type
types of application level actions for DoCommand()
Enumerator
Doc
Action alters the document.
App
Action alters only the application.
Gui
Action alters only the Gui.
Definition at line 436 of file Gui/Command.h.
TriggerSource
enum Gui::Command::TriggerSource
Command trigger source.
Enumerator
TriggerNone
No external trigger, e.g. invoked through Python.
TriggerAction
Command triggered by an action.
TriggerChildAction
Command triggered by a child action inside an action group.
Definition at line 349 of file Gui/Command.h.
Constructor & Destructor Documentation
Command()
Command::Command (const char * name) explicit protected
Definition at line 219 of file Gui/Command.cpp.
References Alter3DView, AlterDoc, AlterSelection, bCanLog, eType, sAppModule, and sGroup.
~Command()
Command::~Command () override protected default
Member Function Documentation
_assureWorkbench()
std::string Command::_assureWorkbench (const char * file, int line, const char * sName) static
Assures the switch to a certain workbench
Parameters
file the calling file path (for debugging purpose)
line the calling line number (for debugging purpose)
sName workbench name
Returns
Return the current active workbench name before switching.
If already in the workbench, does nothing.
Definition at line 754 of file Gui/Command.cpp.
References _doCommand(), Gui::WorkbenchManager::active(), DrawingExample::file, Gui::WorkbenchManager::instance(), Gui::Workbench::name(), and sName.
_copyVisual() [1/4]
void Command::_copyVisual (const char * file, int line, const App::DocumentObject * to, const char * attr, const App::DocumentObject * from) static
Definition at line 823 of file Gui/Command.cpp.
References _copyVisual(), and DrawingExample::file.
_copyVisual() [2/4]
void Command::_copyVisual (const char * file, int line, const App::DocumentObject * to, const char * attr_to, const App::DocumentObject * from, const char * attr_from) static
Definition at line 783 of file Gui/Command.cpp.
References _doCommand(), DrawingExample::file, getObjectCmd(), Gui::Application::getViewProvider(), Gui::Application::Instance, and App::DocumentObject::isAttachedToDocument().
_copyVisual() [3/4]
void Command::_copyVisual (const char * file, int line, const char * to, const char * attr, const char * from) static
Definition at line 769 of file Gui/Command.cpp.
References DrawingExample::file.
Referenced by _copyVisual().
_copyVisual() [4/4]
void Command::_copyVisual (const char * file, int line, const char * to, const char * attr_to, const char * from, const char * attr_from) static
Definition at line 774 of file Gui/Command.cpp.
References _copyVisual(), toolbit-attributes::doc, DrawingExample::file, App::Application::getActiveDocument(), and App::GetApplication().
_doCommand()
void Command::_doCommand (const char * file, int line, DoCmd_Type eType, const char * sCmd, ...) static
Run a App level Action.
Run a command with printf like formatter
Parameters
file the calling file path (for debugging purpose)
line the calling line number (for debugging purpose)
eType command type, See DoCmd_Type
sCmd command string that supports printf like formatter
You can use the convenience macro doCommand() to automate file and line arguments. You may also want to use various helper Helper macros for running commands through Python interpreter.
Definition at line 658 of file Gui/Command.cpp.
References _runCommand(), Base::Console(), eType, DrawingExample::file, Base::ConsoleSingleton::Log(), and toolbit-attributes::s.
Referenced by _assureWorkbench(), and _copyVisual().
_runCommand() [1/2]
void Command::_runCommand (const char * file, int line, DoCmd_Type eType, const char * sCmd) static
Run a App level Action.
Run a command
Parameters
file the calling file path (for debugging purpose)
line the calling line number (for debugging purpose)
eType command type, See DoCmd_Type
sCmd command string
See also
_doCommand()
Definition at line 712 of file Gui/Command.cpp.
References Gui::MacroManager::addLine(), Gui::MacroManager::App, eType, DrawingExample::file, Gui::MacroManager::Gui, Gui::Application::Instance, Base::Interpreter(), Gui::Application::macroManager(), printCaller(), Base::InterpreterSingleton::runString(), and Base::PyException::ThrowException().
Referenced by _doCommand(), and _runCommand().
_runCommand() [2/2]
void Command::_runCommand (const char * file, int line, DoCmd_Type eType, const QByteArray & sCmd) static
Run a App level Action.
Run a command
Parameters
file the calling file path (for debugging purpose)
line the calling line number (for debugging purpose)
eType command type, See DoCmd_Type
sCmd command string
See also
_doCommand()
Definition at line 733 of file Gui/Command.cpp.
References _runCommand(), eType, and DrawingExample::file.
abortCommand()
void Command::abortCommand () static
Abort the Undo transaction on the active document.
Definition at line 640 of file Gui/Command.cpp.
References App::Application::closeActiveTransaction(), and App::GetApplication().
Referenced by SpreadsheetGui::DlgSheetConf::accept(), SpreadsheetGui::DlgBindSheet::accept(), TechDrawGui::TaskBalloon::accept(), ReenGui::FitBSplineCurveWidget::accept(), ReenGui::FitBSplineSurfaceWidget::accept(), ReenGui::PoissonWidget::accept(), MeshGui::TaskSmoothing::accept(), CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainCoincidentUnified::activatedCoincident(), CmdSketcherConstrainCoincidentUnified::activatedPointOnObject(), addConstraintSafely(), SpreadsheetGui::PropertiesDialog::apply(), CmdSketcherConstrainPerpendicular::applyConstraint(), CmdSketcherConstrainCoincidentUnified::applyConstraintCoincident(), CmdSketcherConstrainCoincidentUnified::applyConstraintPointOnObject(), TDHandlerDimension::clearAndRestartCommand(), TechDrawGui::TaskCenterLine::createCenterLine(), TDHandlerDimension::deactivated(), DrawSketchHandlerDimension::deactivated(), PartDesignGui::ViewProvider::doubleClicked(), PartDesignGui::ViewProviderBase::doubleClicked(), execCreateObliqueChainDimension(), execCreateObliqueCoordDimension(), SketcherGui::DrawSketchHandlerTrimming::executeCommands(), DrawSketchHandlerDimension::isRadiusDoF(), SketcherGui::makeTangentToArcOfEllipseviaNewPoint(), SketcherGui::makeTangentToArcOfHyperbolaviaNewPoint(), SketcherGui::makeTangentToArcOfParabolaviaNewPoint(), SketcherGui::makeTangentToEllipseviaNewPoint(), SpreadsheetGui::DlgBindSheet::onDiscard(), SpreadsheetGui::DlgSheetConf::onDiscard(), SketcherGui::TaskSketcherConstraints::onListWidgetConstraintsItemChanged(), StdCmdExpression::pasteExpressions(), PartGui::OffsetWidget::reject(), PartGui::ThicknessWidget::reject(), FemGui::TaskDlgMeshShapeNetgen::reject(), TechDrawGui::TaskProjGroup::reject(), FemGui::TaskDlgCreateNodeSet::reject(), FemGui::TaskDlgCreateElementSet::reject(), SurfaceGui::GeomFillSurface::reject(), PartDesignGui::TaskDlgShapeBinder::reject(), PartDesignGui::TaskDlgBooleanParameters::reject(), FemGui::TaskDlgFemConstraint::reject(), PartDesignGui::TaskPrimitiveParameters::reject(), SurfaceGui::TaskSections::reject(), SurfaceGui::TaskFilling::reject(), PartDesignGui::TaskDlgFeatureParameters::reject(), PartGui::TaskDlgAttacher::reject(), FemGui::TaskDlgPost::reject(), DrawSketchHandlerBSplineInsertKnot::releaseButton(), DrawSketchHandlerCopy::releaseButton(), DrawSketchHandlerRectangularArray::releaseButton(), DrawSketchHandlerDimension::resetTool(), TDHandlerDimension::restartCommand(), and DrawSketchHandlerDimension::restartCommand().
activated()
virtual void Gui::Command::activated (int iMsg) protected pure virtual
Methods which gets called when activated, needs to be reimplemented!
Implemented in CmdSketcherConstraint, CmdSketcherConstrainSymmetric, CmdSketcherConstrainEqual, CmdSketcherConstrainAngle, CmdSketcherConstrainRadiam, CmdSketcherConstrainDiameter, CmdSketcherConstrainRadius, CmdSketcherConstrainTangent, CmdSketcherConstrainPerpendicular, CmdSketcherConstrainParallel, CmdSketcherConstrainDistanceY, CmdSketcherConstrainDistanceX, CmdSketcherConstrainDistance, CmdSketcherConstrainPointOnObject, CmdSketcherConstrainCoincident, CmdSketcherConstrainCoincidentUnified, CmdSketcherConstrainBlock, CmdSketcherConstrainLock, CmdSketcherConstrainVertical, CmdSketcherConstrainHorizontal, CmdSketcherConstrainHorVer, StdCmdExpression, CmdRenderingOrder, CmdSketcherMove, CmdSketcherClone, CmdSketcherSnap, CmdSketcherCopy, CmdSketcherGrid, StdCmdUserEditMode, Gui::MacroCommand, Gui::PythonGroupCommand, Gui::PythonCommand, Gui::GroupCommand, StdCmdDrawStyle, StdCmdFreezeViews, Gui::StdCmdPythonHelp, Gui::StdCmdDownloadOnlineHelp, Gui::StdCmdDescription, StdCmdLinkMakeGroup, StdCmdAlignToSelection, StdRecallWorkingView, StdStoreWorkingView, StdCmdDockOverlayMouseTransparent, StdCmdDockOverlayToggleBottom, StdCmdDockOverlayToggleTop, StdCmdDockOverlayToggleRight, StdCmdDockOverlayToggleLeft, StdCmdDockOverlayToggleTransparent, StdCmdDockOverlayToggle, StdCmdDockOverlayTransparentAll, StdCmdDockOverlayAll, StdCmdSelBoundingBox, StdTreeDrag, StdTreeRecordSelection, StdTreePreSelection, StdTreeSyncPlacement, StdTreeSyncSelection, StdTreeSyncView, StdTreeCollapseDocument, StdTreeMultiDocument, StdTreeSingleDocument, StdCmdSelForward, StdCmdSelBack, StdCmdDemoMode, StdCmdTextureMapping, StdCmdSceneInspector, StdCmdTreeSelectAllInstances, StdCmdTreeExpand, StdCmdTreeCollapse, StdTreeSelection, StdBoxElementSelection, StdBoxSelection, StdViewBoxZoom, StdViewZoomOut, StdViewZoomIn, StdCmdViewIvIssueCamPos, StdCmdViewIvStereoInterleavedColumns, StdCmdViewIvStereoInterleavedRows, StdCmdViewIvStereoQuadBuff, StdCmdViewIvStereoRedGreen, StdCmdViewIvStereoOff, StdCmdViewExample3, StdCmdViewExample2, StdCmdViewExample1, StdCmdAxisCross, StdCmdToggleNavigation, StdCmdViewCreate, StdViewLoadImage, StdViewScreenShot, StdCmdViewVR, StdViewDockUndockFullscreen, StdCmdProperties, StdViewFullscreen, StdMainFullscreen, StdCmdEdit, StdViewUndock, StdViewDock, StdCmdAlignment, StdCmdTransformManip, StdCmdViewFitSelection, StdCmdPlacement, StdCmdViewFitAll, StdCmdTransform, StdCmdViewRotateRight, StdCmdViewRotateLeft, StdCmdViewTrimetric, StdCmdRefresh, StdCmdViewDimetric, StdCmdViewIsometric, StdCmdViewTop, StdCmdViewRight, StdCmdViewRear, StdCmdViewLeft, StdCmdDelete, StdCmdViewFront, StdCmdSelectAll, StdCmdViewBottom, StdCmdViewHome, StdCmdHideObjects, StdCmdDuplicateSelection, StdCmdShowObjects, NaviCubeDraggableCmd, StdCmdPaste, StdCmdToggleObjects, StdCmdCopy, StdCmdCut, StdCmdSelectVisibleObjects, StdCmdHideSelection, StdCmdRedo, StdCmdShowSelection, StdCmdUndo, StdCmdToggleSelectability, StdCmdQuit, StdCmdPrintPdf, StdCmdReloadStyleSheet, StdCmdPrintPreview, StdCmdPrint, StdCmdToggleTransparency, StdCmdProjectUtil, StdCmdToggleVisibility, StdCmdProjectInfo, StdCmdUnitsCalculator, StdCmdRevert, StdCmdLinkSelectAllLinks, StdCmdTextDocument, StdCmdSaveAll, StdCmdLinkSelectLinkedFinal, StdCmdReportBug, StdCmdSaveCopy, StdCmdPythonWebsite, StdCmdSaveAs, StdCmdFreeCADFAQ, CmdTestConsoleOutput, StdCmdSave, StdCmdFreeCADForum, CmdTestMDI3, StdCmdNew, StdCmdFreeCADPowerUserHub, CmdTestMDI2, StdCmdLinkSelectLinked, CmdTestMDI1, StdCmdFreeCADUserHub, StdCmdExportDependencyGraph, StdCmdLinkImportAll, StdCmdFreeCADWebsite, StdCmdDependencyGraph, StdCmdToggleClipPlane, StdCmdFreeCADDonation, CmdSandboxMeshLoader, CmdTestProgress5, StdCmdOnlineHelpWebsite, StdCmdLinkImport, StdCmdMergeProjects, StdCmdOnlineHelp, StdCmdLinkUnlink, CmdSandboxEventLoop, CmdTestProgress4, StdCmdLinkReplace, StdCmdCommandLine, StdCmdWindowsMenu, StdCmdDlgCustomize, CmdTestProgress3, StdCmdStatusBar, StdCmdDlgPreferences, CmdTestProgress2, StdCmdDlgParameter, StdCmdToggleToolBarLock, CmdTestProgress1, StdCmdRestartInSafeMode, StdCmdToolBarMenu, StdCmdWhatsThis, CmdTestCmdFuncs, StdCmdExport, StdCmdAboutQt, StdCmdToggleBreakpoint, StdCmdDockViewMenu, StdCmdLinkMakeRelative, FCCmdTest6, StdCmdViewRestoreCamera, StdCmdUserInterface, StdCmdMacroStepInto, StdCmdViewSaveCamera, FCCmdTest5, StdCmdWindows, StdCmdMacroStepOver, StdCmdAbout, StdCmdLinkMake, FCCmdTest4, StdCmdMacroStopDebug, StdCmdImport, StdCmdActivatePrevWindow, StdPerspectiveCamera, StdCmdRecentMacros, FCCmdTest3, StdCmdMacroStartDebug, StdCmdActivateNextWindow, FCCmdTest2, StdCmdMacroAttachDebugger, StdCmdCloseAllWindows, StdCmdRecentFiles, StdCmdVarSet, StdOrthographicCamera, StdCmdDlgMacroExecuteDirect, FCCmdTest1, StdCmdCloseActiveWindow, Std_TestReloadQM, StdCmdGroup, StdCmdDlgMacroExecute, StdCmdOpen, StdCmdCascadeWindows, StdCmdWorkbench, Std_TestQM, StdCmdTileWindows, StdCmdPart, and StdCmdDlgMacroRecord.
Referenced by src.Mod.AddonManager.Widgets.addonmanager_widget_filter_selector.WidgetFilterSelector::set_status_filter().
addModule()
void Command::addModule (DoCmd_Type eType, const char * sModuleName) static
import an external (or own) module only once
Definition at line 738 of file Gui/Command.cpp.
References Gui::MacroManager::addLine(), alreadyLoadedModule, Gui::MacroManager::App, eType, Gui::MacroManager::Gui, Gui::Application::Instance, Base::Interpreter(), Gui::Application::macroManager(), and Base::InterpreterSingleton::runString().
Referenced by DrawingGui::TaskProjection::accept(), TechDrawGui::TaskProjection::accept(), ReenGui::FitBSplineSurfaceWidget::accept(), ReenGui::PoissonWidget::accept(), FemGui::ViewProviderFemAnalysis::doubleClicked(), Gui::ApplicationPy::sAddModule(), SketcherGui::ViewProviderSketch::setEdit(), and Gui::MainWindow::showDocumentation().
addTo()
void Command::addTo (QWidget * pcWidget)
adds this command to arbitrary widgets
Definition at line 274 of file Gui/Command.cpp.
References Gui::CommandBase::_pcAction, Gui::Action::addTo(), and initAction().
Referenced by Gui::CommandManager::addTo(), NaviCubeImplementation::createContextMenu(), Gui::MainWindow::createPopupMenu(), src.Mod.PartDesign.WizardShaft.Shaft.Shaft::equilibrium(), and Gui::OverlayTabWidget::OverlayTabWidget().
addToGroup() [1/2]
void Command::addToGroup (ActionGroup * group)
Definition at line 286 of file Gui/Command.cpp.
References Gui::CommandBase::_pcAction, toolbit-attributes::group, and initAction().
addToGroup() [2/2]
void Command::addToGroup (ActionGroup * group, bool checkable)
Definition at line 280 of file Gui/Command.cpp.
References Gui::CommandBase::_pcAction, toolbit-attributes::group, and Gui::Action::setCheckable().
Referenced by StdViewDockUndockFullscreen::createAction().
adjustCameraPosition()
void Command::adjustCameraPosition ()
Definition at line 933 of file Gui/Command.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Gui::Application::activeDocument(), MengerSponge::box, SplineSurface::bs, toolbit-attributes::doc, Gui::Application::Instance, and OfflineRenderingUtils::viewer().
Referenced by prepareProfileBased().
applyCommandData()
void Command::applyCommandData (const char * context, Action * action) protected
Applies the menu text, tool and status tip to the passed action object.
Definition at line 898 of file Gui/Command.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Gui::CommandBase::getMenuText(), Gui::CommandBase::getStatusTip(), Gui::CommandBase::getToolTipText(), Gui::CommandBase::getWhatsThis(), Gui::CommandBase::sStatusTip, and src.Mod.AddonManager.Addon::translate.
Referenced by StdCmdLinkMakeGroup::createAction(), StdCmdFreezeViews::createAction(), createAction(), StdCmdDrawStyle::createAction(), Gui::PythonCommand::createAction(), Gui::PythonGroupCommand::createAction(), StdCmdUserEditMode::createAction(), StdCmdUndo::createAction(), StdCmdRedo::createAction(), CmdSketcherGrid::createAction(), CmdSketcherSnap::createAction(), CmdRenderingOrder::createAction(), StdCmdExpression::createAction(), languageChange(), Gui::PythonCommand::languageChange(), Gui::PythonGroupCommand::languageChange(), and Gui::GroupCommand::setup().
beginCmdHelp()
const char * Command::beginCmdHelp ()
returns the begin of a online help page
Definition at line 881 of file Gui/Command.cpp.
blockCommand()
void Command::blockCommand (bool block) static
Blocks all command objects.
Definition at line 652 of file Gui/Command.cpp.
commitCommand()
void Command::commitCommand () static
Commit the Undo transaction on the active document.
Definition at line 635 of file Gui/Command.cpp.
References App::Application::closeActiveTransaction(), and App::GetApplication().
Referenced by _copyShape(), PartGui::ThicknessWidget::accept(), PartGui::OffsetWidget::accept(), SpreadsheetGui::DlgSheetConf::accept(), SpreadsheetGui::DlgBindSheet::accept(), DrawingGui::TaskProjection::accept(), TechDrawGui::TaskProjection::accept(), TechDrawGui::TaskDimRepair::accept(), FemGui::TaskDlgMeshShapeNetgen::accept(), TechDrawGui::TaskActiveView::accept(), TechDrawGui::TaskCosmeticCircle::accept(), TechDrawGui::TaskCosmeticLine::accept(), FemGui::TaskDlgFemConstraintInitialTemperature::accept(), TechDrawGui::TaskCustomizeFormat::accept(), TechDrawGui::TaskCenterLine::accept(), ReenGui::FitBSplineSurfaceWidget::accept(), ReenGui::PoissonWidget::accept(), TechDrawGui::TaskSurfaceFinishSymbols::accept(), PartDesignGui::TaskPipeParameters::accept(), SurfaceGui::GeomFillSurface::accept(), MeshGui::TaskDecimating::accept(), PartDesignGui::TaskDlgShapeBinder::accept(), PartDesignGui::TaskDlgBooleanParameters::accept(), TechDrawGui::TaskWeldingSymbol::accept(), FemGui::TaskDlgFemConstraint::accept(), MeshGui::TaskSmoothing::accept(), SurfaceGui::TaskSections::accept(), SurfaceGui::TaskFilling::accept(), PartDesignGui::TaskDlgFeatureParameters::accept(), PartGui::TaskDlgAttacher::accept(), StdCmdDelete::activated(), CmdSketcherConstrainLock::activated(), CmdSketcherConstrainBlock::activated(), CmdSketcherConstrainParallel::activated(), CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainRadius::activated(), CmdSketcherConstrainDiameter::activated(), CmdSketcherConstrainRadiam::activated(), CmdSketcherConstrainEqual::activated(), CmdSketcherConstrainSymmetric::activated(), CmdSketcherConstrainCoincidentUnified::activatedCoincident(), CmdSketcherConstrainCoincidentUnified::activatedPointOnObject(), TechDrawGui::TaskCosVertex::addCosVertex(), SpreadsheetGui::PropertiesDialog::apply(), CmdSketcherConstrainLock::applyConstraint(), CmdSketcherConstrainBlock::applyConstraint(), CmdSketcherConstrainParallel::applyConstraint(), CmdSketcherConstrainPerpendicular::applyConstraint(), CmdSketcherConstrainTangent::applyConstraint(), CmdSketcherConstrainRadius::applyConstraint(), CmdSketcherConstrainDiameter::applyConstraint(), CmdSketcherConstrainRadiam::applyConstraint(), CmdSketcherConstrainEqual::applyConstraint(), CmdSketcherConstrainSymmetric::applyConstraint(), CmdSketcherConstrainCoincidentUnified::applyConstraintCoincident(), CmdSketcherConstrainCoincidentUnified::applyConstraintPointOnObject(), TechDrawGui::QGIViewBalloon::balloonLabelDragFinished(), TechDrawGui::TaskRichAnno::createAnnoFeature(), SketcherGui::DrawSketchHandler::createAutoConstraints(), TechDrawGui::QGSPage::createBalloon(), TechDrawGui::TaskCenterLine::createCenterLine(), TechDrawGui::TaskCosmeticCircle::createCosmeticCircle(), TechDrawGui::TaskCosmeticLine::createCosmeticLine(), TechDrawGui::TaskDetail::createDetail(), TechDrawGui::TaskLeaderLine::createLeaderFeature(), TechDrawGui::TaskSectionView::createSectionView(), TechDrawGui::QGIViewDimension::datumLabelDragFinished(), DefineElementsCallback(), DefineNodesCallback(), SpreadsheetGui::SheetTableView::deleteSelection(), dimensionMaker(), AssemblyGui::ViewProviderAssembly::endMove(), execCascadeHorizDimension(), execCascadeObliqueDimension(), execCascadeVertDimension(), execCircleCenterLines(), execCreateHorizChainDimension(), execCreateHorizChamferDimension(), execCreateHorizCoordDimension(), execCreateObliqueChainDimension(), execCreateObliqueCoordDimension(), execCreateVertChainDimension(), execCreateVertChamferDimension(), execCreateVertCoordDimension(), execDrawCosmArc(), execDrawCosmCircle(), execDrawCosmCircle3Points(), execExtendShortenLine(), TechDrawGui::execHoleCircle(), execIncreaseDecreaseDecimal(), execInsertPrefixChar(), execLineParallelPerpendicular(), execMidpoints(), execPosHorizChainDimension(), execPosObliqueChainDimension(), execPosVertChainDimension(), execQuadrants(), execRemovePrefixChar(), execSimpleSection(), execThreadBoltBottom(), execThreadBoltSide(), execThreadHoleBottom(), execThreadHoleSide(), TDHandlerDimension::finalizeCommand(), DrawSketchHandlerDimension::finalizeCommand(), finishDatumConstraint(), horVerActivated(), horVerApplyConstraint(), SpreadsheetGui::SheetTableView::insertColumns(), SpreadsheetGui::SheetTableView::insertColumnsAfter(), SpreadsheetGui::SheetTableView::insertRows(), SpreadsheetGui::SheetTableView::insertRowsAfter(), SketcherGui::makeTangentToArcOfEllipseviaNewPoint(), SketcherGui::makeTangentToArcOfHyperbolaviaNewPoint(), SketcherGui::makeTangentToArcOfParabolaviaNewPoint(), SketcherGui::makeTangentToEllipseviaNewPoint(), SpreadsheetGui::DlgBindSheet::onDiscard(), SpreadsheetGui::DlgSheetConf::onDiscard(), SketcherGui::TaskSketcherConstraints::onListWidgetConstraintsItemChanged(), SpreadsheetGui::SheetView::onMsg(), SpreadsheetGui::SheetTableView::onRecompute(), StdCmdExpression::pasteExpressions(), DrawSketchHandlerBSplineInsertKnot::releaseButton(), DrawSketchHandlerCopy::releaseButton(), DrawSketchHandlerRectangularArray::releaseButton(), SpreadsheetGui::SheetTableView::removeColumns(), SpreadsheetGui::SheetTableView::removeRows(), TechDrawGui::PagePrinter::saveDXF(), SpreadsheetGui::WorkbenchHelper::setBackgroundColor(), SpreadsheetGui::WorkbenchHelper::setForegroundColor(), AssemblyGui::ViewProviderAssemblyLink::setupContextMenu(), CmdSketcherConstrainTangent::substituteConstraintCombinations(), SketcherGui::ConstraintView::swapNamedOfSelectedItems(), TechDrawGui::TaskRichAnno::updateAnnoFeature(), TechDrawGui::TaskDetail::updateDetail(), TechDrawGui::TaskLeaderLine::updateLeaderFeature(), and TechDrawGui::TaskSectionView::updateSectionView().
createAction()
Action * Command::createAction () override protected virtual
Creates the used Action.
Reimplemented from Gui::CommandBase.
Reimplemented in StdCmdDockOverlayMouseTransparent, StdCmdSelBoundingBox, StdTreeRecordSelection, StdTreePreSelection, StdTreeSyncPlacement, StdTreeSyncSelection, StdTreeSyncView, StdTreeCollapseDocument, StdTreeMultiDocument, StdTreeSingleDocument, StdViewDockUndockFullscreen, NaviCubeDraggableCmd, StdCmdRedo, StdCmdUndo, StdCmdToggleClipPlane, StdCmdWindowsMenu, StdCmdStatusBar, StdCmdDlgPreferences, StdCmdToggleToolBarLock, StdCmdToolBarMenu, StdCmdDockViewMenu, StdCmdAbout, StdPerspectiveCamera, StdCmdRecentMacros, StdCmdRecentFiles, StdOrthographicCamera, StdCmdWorkbench, StdCmdExpression, CmdRenderingOrder, CmdSketcherSnap, CmdSketcherGrid, StdCmdUserEditMode, Gui::MacroCommand, Gui::PythonGroupCommand, Gui::PythonCommand, Gui::GroupCommand, StdCmdDrawStyle, StdCmdFreezeViews, Gui::StdCmdDownloadOnlineHelp, Gui::StdCmdDescription, and StdCmdLinkMakeGroup.
Definition at line 981 of file Gui/Command.cpp.
References applyCommandData(), Gui::BitmapFactory(), Gui::CommandBase::className(), Gui::getMainWindow(), Gui::Action::setIcon(), and Gui::CommandBase::sPixmap.
Referenced by Gui::StdCmdDescription::createAction(), StdOrthographicCamera::createAction(), StdPerspectiveCamera::createAction(), StdCmdToggleToolBarLock::createAction(), StdCmdDlgPreferences::createAction(), StdCmdStatusBar::createAction(), and initAction().
endCmdHelp()
const char * Command::endCmdHelp ()
returns the end of a online help page
Definition at line 893 of file Gui/Command.cpp.
getActiveGuiDocument()
Gui::Document * Command::getActiveGuiDocument () const
Get pointer to the active gui document.
Definition at line 297 of file Gui/Command.cpp.
References Gui::Application::activeDocument(), and getGuiApplication().
Referenced by SketcherCopy::activate(), StdCmdImport::activated(), StdCmdExport::activated(), StdCmdDrawStyle::activated(), StdCmdProjectInfo::activated(), StdCmdToggleVisibility::activated(), StdCmdToggleTransparency::activated(), CmdSketcherGrid::activated(), StdCmdRefresh::activated(), StdCmdTransformManip::activated(), StdCmdViewCreate::activated(), CmdSketcherConstrainLock::activated(), CmdSketcherConstrainBlock::activated(), CmdSketcherConstrainDistance::activated(), CmdSketcherConstrainDistanceX::activated(), CmdSketcherConstrainDistanceY::activated(), CmdSketcherConstrainParallel::activated(), CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainRadius::activated(), CmdSketcherConstrainDiameter::activated(), CmdSketcherConstrainRadiam::activated(), CmdSketcherConstrainAngle::activated(), CmdSketcherConstrainEqual::activated(), CmdSketcherConstrainSymmetric::activated(), CmdSketcherConstrainLock::applyConstraint(), CmdSketcherConstrainBlock::applyConstraint(), CmdSketcherConstrainDistance::applyConstraint(), CmdSketcherConstrainDistanceX::applyConstraint(), CmdSketcherConstrainDistanceY::applyConstraint(), CmdSketcherConstrainParallel::applyConstraint(), CmdSketcherConstrainPerpendicular::applyConstraint(), CmdSketcherConstrainTangent::applyConstraint(), CmdSketcherConstrainRadius::applyConstraint(), CmdSketcherConstrainDiameter::applyConstraint(), CmdSketcherConstrainRadiam::applyConstraint(), CmdSketcherConstrainAngle::applyConstraint(), CmdSketcherConstrainEqual::applyConstraint(), CmdSketcherConstrainSymmetric::applyConstraint(), CmdSketcherConstrainCoincidentUnified::applyConstraintCoincident(), CmdSketcherConstrainCoincidentUnified::applyConstraintPointOnObject(), finishDatumConstraint(), hasActiveDocument(), horVerActivated(), horVerApplyConstraint(), StdCmdImport::isActive(), StdCmdExport::isActive(), StdCmdDependencyGraph::isActive(), StdCmdExportDependencyGraph::isActive(), StdCmdSaveCopy::isActive(), StdCmdSaveAll::isActive(), StdCmdRevert::isActive(), StdCmdProjectInfo::isActive(), CmdSketcherCompCreateFillets::isActive(), CmdSketcherCompCurveEdition::isActive(), CmdSketcherCopy::isActive(), CmdSketcherCompExternal::isActive(), CmdSketcherClone::isActive(), CmdSketcherMove::isActive(), CmdSketcherCompSlot::isActive(), CmdRenderingOrder::isActive(), StdCmdViewCreate::isActive(), CmdSketcherCompHorizontalVertical::isActive(), and CmdSketcherConstrainCoincidentUnified::onActivated().
getAppModuleName()
const char* Gui::Command::getAppModuleName () const inline
returns the name to which the command belongs
Definition at line 564 of file Gui/Command.h.
getDocument()
App::Document * Command::getDocument (const char * Name = nullptr) const
Get pointer to the named or active App document Returns a pointer to the named document or the active document when no name is given. NULL is returned when the name does not exist or no document is active!
Definition at line 302 of file Gui/Command.cpp.
References Gui::Application::activeDocument(), App::GetApplication(), App::Application::getDocument(), Gui::Document::getDocument(), and getGuiApplication().
Referenced by _checkSelection(), _checkSelectionBalloon(), _checkSelectionHatch(), SketcherCopy::activate(), StdCmdImport::activated(), StdCmdExport::activated(), StdCmdProjectInfo::activated(), CmdSketcherConstrainEqual::activated(), CmdSketcherConstrainSymmetric::activated(), execComplexSection(), execStackBottom(), execStackDown(), execStackTop(), execStackUp(), TechDrawGui::DrawGuiUtil::findPage(), getObject(), TechDraw::CommandHelpers::getSelectedShapes(), getSelectedShapes(), hasObject(), StdCmdRefresh::isActive(), TechDrawGui::DrawGuiUtil::needPage(), TechDrawGui::DrawGuiUtil::needView(), and prepareProfileBased().
getGroupName()
const char* Gui::Command::getGroupName () const inline
Get the name of the grouping of the command.
Definition at line 569 of file Gui/Command.h.
Referenced by Gui::Dialog::CommandModel::data(), Gui::Dialog::DlgCustomKeyboardImp::initCommandCompleter(), and translatedGroupName().
getGuiApplication()
Application * Command::getGuiApplication () static
Get pointer to the Application Window.
Definition at line 292 of file Gui/Command.cpp.
References Gui::Application::Instance.
Referenced by StdCmdOpen::activated(), StdCmdImport::activated(), StdCmdExport::activated(), StdCmdFreezeViews::activated(), StdCmdUndo::activated(), StdCmdRedo::activated(), StdCmdCut::activated(), StdCmdCopy::activated(), StdCmdPaste::activated(), StdCmdDelete::activated(), StdCmdViewIvIssueCamPos::activated(), StdViewZoomIn::activated(), StdViewZoomOut::activated(), getActiveGuiDocument(), getDocument(), StdCmdSave::isActive(), StdCmdSaveAs::isActive(), StdCmdPrint::isActive(), StdCmdPrintPreview::isActive(), StdCmdPrintPdf::isActive(), StdCmdUndo::isActive(), StdCmdRedo::isActive(), StdCmdCut::isActive(), StdCmdCopy::isActive(), StdCmdPaste::isActive(), StdCmdViewFitAll::isActive(), StdCmdViewFitSelection::isActive(), StdCmdViewVR::isActive(), StdCmdViewExample1::isActive(), StdCmdViewExample2::isActive(), StdCmdViewExample3::isActive(), StdCmdViewIvStereoOff::isActive(), StdCmdViewIvStereoRedGreen::isActive(), StdCmdViewIvStereoQuadBuff::isActive(), StdCmdViewIvStereoInterleavedRows::isActive(), StdCmdViewIvStereoInterleavedColumns::isActive(), StdCmdViewIvIssueCamPos::isActive(), StdViewZoomIn::isActive(), StdViewZoomOut::isActive(), StdCmdAlignToSelection::isActive(), isViewOfType(), StdCmdDrawStyle::StdCmdDrawStyle(), and StdCmdUserEditMode::StdCmdUserEditMode().
getHelpUrl()
virtual const char* Gui::Command::getHelpUrl () const inline virtual
Get the help URL.
Reimplemented in Gui::PythonGroupCommand, and Gui::PythonCommand.
Definition at line 550 of file Gui/Command.h.
getName()
const char* Gui::Command::getName () const inline
Get the command name.
Definition at line 567 of file Gui/Command.h.
Referenced by Gui::Action::Action(), StdCmdImport::activated(), StdCmdExport::activated(), StdCmdDelete::activated(), Gui::CommandManager::addCommand(), Gui::Action::commandMenuText(), Gui::PythonCommand::createAction(), Gui::PythonGroupCommand::createAction(), Gui::Action::createToolTip(), Gui::Dialog::CommandModel::data(), getShortcut(), Gui::PythonCommand::getWhatsThis(), Gui::PythonGroupCommand::getWhatsThis(), initAction(), invoke(), Gui::PythonCommand::languageChange(), Gui::PythonGroupCommand::languageChange(), Gui::Dialog::DlgCustomKeyboardImp::onCommandTreeWidgetCurrentItemChanged(), Gui::CommandManager::removeCommand(), and Gui::GroupCommand::setup().
getObject()
App::DocumentObject * Command::getObject (const char * Name) const
returns the named feature or the active one from the active document or NULL
Definition at line 316 of file Gui/Command.cpp.
References getDocument(), and App::Document::getObject().
Referenced by CmdSketcherConstrainLock::activated(), CmdSketcherConstrainDistance::activated(), CmdSketcherConstrainDistanceX::activated(), CmdSketcherConstrainDistanceY::activated(), CmdSketcherConstrainParallel::activated(), CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainRadius::activated(), CmdSketcherConstrainAngle::activated(), CmdSketcherConstrainEqual::activated(), and CmdSketcherConstrainSymmetric::activated().
getObjectCmd() [1/2]
std::string Command::getObjectCmd (const App::DocumentObject * obj, const char * prefix = nullptr, const char * postfix = nullptr, bool gui = false) static
returns a python command string to retrieve the given object
Definition at line 591 of file Gui/Command.cpp.
References App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), getObjectCmd(), Draft::gui, and App::DocumentObject::isAttachedToDocument().
getObjectCmd() [2/2]
std::string Command::getObjectCmd (const char * Name, const App::Document * doc = nullptr, const char * prefix = nullptr, const char * postfix = nullptr, bool gui = false) static
returns a python command string to retrieve an object from a document
Definition at line 575 of file Gui/Command.cpp.
References toolbit-attributes::doc, App::Application::getActiveDocument(), App::GetApplication(), Draft::gui, and Path.Post.scripts.refactored_centroid_post::str.
Referenced by _copyShape(), _copyVisual(), PartDesignGui::TaskDlgBooleanParameters::accept(), PartDesignGui::TaskDlgDressUpParameters::accept(), StdCmdLinkMakeRelative::activated(), Gui::ExpressionBinding::apply(), PartDesignGui::TaskMultiTransformParameters::apply(), PartDesignGui::buildLinkListPythonStr(), PartDesignGui::buildLinkSingleSubPythonStr(), PartDesignGui::buildLinkSubListPythonStr(), copySelectionToClipboard(), SketcherGui::DrawSketchDefaultHandler< ControllerT::HandlerType, ControllerT::SelectModeType, ControllerT::AutoConstraintInitialSize, ControllerT::ContructionMethodType >::createGeneratedAutoConstraints(), PartDesignGui::ViewProviderDatum::doubleClicked(), finishDressupFeature(), PartDesignGui::fixSketchSupport(), Gui::SelectionObject::getAsPropertyLinkSubString(), getObjectCmd(), PartDesignGui::makeBodyActive(), Gui::TreeWidget::mouseDoubleClickEvent(), PartDesignGui::ViewProvider::onDelete(), prepareProfileBased(), prepareTransformed(), PartDesignGui::relinkToBody(), PartDesignGui::setEdit(), SketcherGui::ViewProviderSketch::setEdit(), PartDesignGui::TaskBoxPrimitives::setPrimitive(), and PartDesignGui::ViewProviderBody::toggleActiveBody().
getPythonTuple()
std::string Command::getPythonTuple (const std::string & name, const std::vector< std::string > & subnames) static
Get Python tuple from object and sub-elements.
Definition at line 828 of file Gui/Command.cpp.
References Path.Post.scripts.refactored_centroid_post::str.
getSelection()
Gui::SelectionSingleton & Command::getSelection () static
Get a reference to the selection.
Definition at line 563 of file Gui/Command.cpp.
References Gui::Selection().
Referenced by _checkDrawViewPart(), _checkDrawViewPartBalloon(), TechDrawGui::_checkSel(), TechDrawGui::_checkSelection(), _checkSelection(), _checkSelectionBalloon(), _checkSelectionHatch(), SketcherCopy::activate(), CmdSketcherConstrainLock::activated(), CmdSketcherConstrainBlock::activated(), CmdSketcherConstrainDistance::activated(), CmdSketcherConstrainDistanceX::activated(), CmdSketcherConstrainDistanceY::activated(), CmdSketcherConstrainParallel::activated(), CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainRadius::activated(), CmdSketcherConstrainDiameter::activated(), CmdSketcherConstrainRadiam::activated(), CmdSketcherConstrainAngle::activated(), CmdSketcherConstrainEqual::activated(), CmdSketcherConstrainSymmetric::activated(), CmdSketcherConstrainCoincidentUnified::activatedCoincident(), CmdSketcherConstrainCoincidentUnified::activatedPointOnObject(), CmdSketcherConstrainPerpendicular::applyConstraint(), CmdSketcherConstrainTangent::applyConstraint(), CmdSketcherConstrainRadius::applyConstraint(), CmdSketcherConstrainDiameter::applyConstraint(), CmdSketcherConstrainRadiam::applyConstraint(), CmdSketcherConstrainSymmetric::applyConstraint(), dressupGetSelected(), exec2PointCenterLine(), execCenterLine(), execCircleCenterLines(), execComplexSection(), execCosmeticCircle(), execCosmeticVertex(), execCreateHorizChainDimension(), execCreateHorizChamferDimension(), execCreateHorizCoordDimension(), execCreateObliqueChainDimension(), execCreateObliqueCoordDimension(), execCreateVertChainDimension(), execCreateVertChamferDimension(), execCreateVertCoordDimension(), execDrawCosmArc(), execDrawCosmCircle(), execDrawCosmCircle3Points(), TechDrawGui::execHoleCircle(), execLine2Points(), execLineParallelPerpendicular(), execSimpleSection(), execStackBottom(), execStackDown(), execStackTop(), execStackUp(), execThreadBoltBottom(), execThreadBoltSide(), execThreadHoleBottom(), execThreadHoleSide(), TechDrawGui::DrawGuiUtil::findPage(), finishDatumConstraint(), TechDraw::CommandHelpers::firstNonSpreadsheetInSelection(), TechDraw::CommandHelpers::firstViewInSelection(), TechDraw::CommandHelpers::getSelectedShapes(), getSelectedShapes(), TechDraw::CommandHelpers::getSelectedSubElements(), horVerActivated(), CmdSketcherConstrainCoincidentUnified::onActivated(), prepareProfileBased(), prepareTransformed(), TechDrawGui::TaskProjGroup::rotateButtonClicked(), femguiutils.selection_widgets._Selector::setHelpText(), CmdSketcherConstrainTangent::substituteConstraintCombinations(), CmdSketcherConstrainCoincidentUnified::substituteConstraintCombinationsCoincident(), and CmdSketcherConstrainCoincidentUnified::substituteConstraintCombinationsPointOnObject().
getShortcut()
QString Command::getShortcut () const virtual
Obtain the current shortcut of this command.
Reimplemented in StdCmdFreezeViews.
Definition at line 239 of file Gui/Command.cpp.
References Gui::CommandBase::_pcAction, getName(), Gui::ShortcutManager::getShortcut(), Gui::ShortcutManager::instance(), and Gui::Action::shortcut().
Referenced by MatGui::Array2D::Array2D(), Gui::Action::commandToolTip(), FemGui::TaskFemConstraint::createDeleteAction(), PartDesignGui::TaskDressUpParameters::createDeleteAction(), initAction(), MatGui::MaterialSave::MaterialSave(), SurfaceGui::SectionsPanel::SectionsPanel(), PartDesignGui::TaskExtrudeParameters::setupDialog(), PartDesignGui::TaskTransformedParameters::setupUI(), PartDesignGui::TaskBooleanParameters::TaskBooleanParameters(), PartDesignGui::TaskLoftParameters::TaskLoftParameters(), PartDesignGui::TaskPipeOrientation::TaskPipeOrientation(), PartDesignGui::TaskPipeParameters::TaskPipeParameters(), and PartDesignGui::TaskPipeScaling::TaskPipeScaling().
getUniqueObjectName()
std::string Command::getUniqueObjectName (const char * BaseName, const App::DocumentObject * obj = nullptr) const
Get unique Feature name from the active document
Parameters
BaseName the base name
obj if not zero, then request the unique name in the document of the given object.
Definition at line 568 of file Gui/Command.cpp.
References toolbit-attributes::doc, App::Application::getActiveDocument(), App::GetApplication(), and App::DocumentObject::getDocument().
Referenced by finishDressupFeature(), prepareProfileBased(), and prepareTransformed().
hasActiveDocument()
bool Command::hasActiveDocument () const
true when there is a document
Definition at line 553 of file Gui/Command.cpp.
References getActiveGuiDocument().
Referenced by StdCmdMergeProjects::isActive(), CmdSandboxMeshLoader::isActive(), StdCmdLinkActions::isActive(), StdCmdViewGroup::isActive(), CmdPartDatums::isActive(), CmdPartDesignCompDatums::isActive(), CmdPartDesignCompSketches::isActive(), TechDrawGui::DrawGuiUtil::needPage(), and TechDrawGui::DrawGuiUtil::needView().
hasObject()
bool Command::hasObject (const char * Name)
true when there is a document and a Feature with Name
Definition at line 558 of file Gui/Command.cpp.
References getDocument(), and App::Document::getObject().
hasPendingCommand()
bool Command::hasPendingCommand () static
Check if an Undo transaction is open on the active document.
Definition at line 645 of file Gui/Command.cpp.
References App::Application::getActiveTransaction(), and App::GetApplication().
Referenced by SurfaceGui::FillingEdgePanel::checkOpenCommand(), SurfaceGui::FillingVertexPanel::checkOpenCommand(), SurfaceGui::GeomFillSurface::checkOpenCommand(), SurfaceGui::SectionsPanel::checkOpenCommand(), SurfaceGui::FillingPanel::checkOpenCommand(), FemGui::TaskDlgMeshShapeNetgen::open(), FemGui::TaskDlgFemConstraint::open(), PartGui::TaskDlgAttacher::open(), TechDrawGui::TaskProjGroup::reject(), TechDrawGui::TaskRichAnno::removeFeature(), and TechDrawGui::TaskLeaderLine::removeFeature().
initAction()
void Command::initAction ()
Create the action if not exist.
Definition at line 260 of file Gui/Command.cpp.
References Gui::CommandBase::_pcAction, createAction(), Gui::CommandBase::getAccel(), getName(), getShortcut(), Gui::ShortcutManager::instance(), setShortcut(), and testActive().
Referenced by addTo(), and addToGroup().
invoke()
void Command::invoke (int index, TriggerSource trigger = TriggerNone)
Called to invoke the command
Parameters
index in case of group command, this is the index of the child command. For checkable command, this indicates the checkable state.
trigger indicate the command triggering source, see TriggerSource.
Definition at line 393 of file Gui/Command.cpp.
References bCanLog, Base::Console(), Gui::CommandBase::displayText, Gui::CommandBase::getMenuText(), getName(), SplineSurface::i, Base::ConsoleSingleton::Log(), and sName.
Referenced by Gui::PythonGroupCommand::activated(), Gui::Action::onActivated(), Gui::ActionGroup::onActivated(), Gui::Dialog::DemoMode::onFullscreenToggled(), Gui::Action::onToggled(), Gui::CommandManager::runCommandByName(), and Gui::ApplicationPy::sRunCommand().
isActive()
virtual bool Gui::Command::isActive () inline virtual
Override this method if your Cmd is not always active.
Reimplemented in StdCmdAlignToSelection, StdRecallWorkingView, StdStoreWorkingView, StdCmdDockOverlayMouseTransparent, StdCmdSelBoundingBox, StdTreeRecordSelection, StdTreePreSelection, StdTreeSyncPlacement, StdTreeSyncSelection, StdTreeSyncView, StdTreeCollapseDocument, StdTreeMultiDocument, StdTreeSingleDocument, StdCmdSelForward, StdCmdSelBack, StdCmdTextureMapping, StdCmdSceneInspector, StdCmdTreeSelectAllInstances, StdBoxElementSelection, StdBoxSelection, StdViewBoxZoom, StdViewZoomOut, StdViewZoomIn, StdCmdViewIvIssueCamPos, StdCmdViewIvStereoInterleavedColumns, StdCmdViewIvStereoInterleavedRows, StdCmdViewIvStereoQuadBuff, StdCmdViewIvStereoRedGreen, StdCmdViewIvStereoOff, StdCmdViewExample3, StdCmdViewExample2, StdCmdViewExample1, StdCmdAxisCross, StdCmdToggleNavigation, StdCmdViewCreate, StdViewScreenShot, StdCmdViewVR, StdViewDockUndockFullscreen, StdCmdProperties, StdViewFullscreen, StdCmdEdit, StdViewUndock, StdViewDock, StdCmdAlignment, StdCmdTransformManip, StdCmdViewFitSelection, StdCmdPlacement, StdCmdViewFitAll, StdCmdTransform, StdCmdViewRotateRight, StdCmdViewRotateLeft, StdCmdViewTrimetric, StdCmdRefresh, StdCmdViewDimetric, StdCmdViewIsometric, StdCmdViewTop, StdCmdViewRight, StdCmdViewRear, StdCmdViewLeft, StdCmdDelete, StdCmdViewFront, StdCmdSelectAll, StdCmdViewBottom, StdCmdViewHome, StdCmdHideObjects, StdCmdDuplicateSelection, StdCmdShowObjects, NaviCubeDraggableCmd, StdCmdPaste, StdCmdToggleObjects, StdCmdCopy, StdCmdCut, StdCmdSelectVisibleObjects, StdCmdHideSelection, StdCmdRedo, StdCmdShowSelection, StdCmdUndo, StdCmdToggleSelectability, StdCmdPrintPdf, StdCmdPrintPreview, StdCmdPrint, StdCmdToggleTransparency, StdCmdProjectUtil, StdCmdToggleVisibility, StdCmdProjectInfo, StdCmdRevert, StdCmdLinkSelectAllLinks, StdCmdTextDocument, StdCmdSaveAll, StdCmdLinkSelectLinkedFinal, StdCmdSaveCopy, StdCmdSaveAs, StdCmdSave, CmdTestMDI3, CmdTestMDI2, StdCmdLinkSelectLinked, CmdTestMDI1, StdCmdExportDependencyGraph, StdCmdLinkImportAll, StdCmdDependencyGraph, StdCmdToggleClipPlane, CmdSandboxMeshLoader, CmdTestProgress5, StdCmdLinkImport, StdCmdMergeProjects, StdCmdLinkUnlink, CmdSandboxEventLoop, CmdTestProgress4, StdCmdLinkReplace, StdCmdWindowsMenu, CmdTestProgress3, StdCmdStatusBar, CmdTestProgress2, CmdTestProgress1, StdCmdToolBarMenu, CmdTestCmdFuncs, StdCmdExport, StdCmdToggleBreakpoint, StdCmdDockViewMenu, StdCmdLinkMakeRelative, FCCmdTest6, StdCmdViewRestoreCamera, StdCmdMacroStepInto, StdCmdViewSaveCamera, FCCmdTest5, StdCmdMacroStepOver, StdCmdAbout, StdCmdLinkMake, FCCmdTest4, StdCmdMacroStopDebug, StdCmdImport, StdCmdActivatePrevWindow, StdPerspectiveCamera, FCCmdTest3, StdCmdMacroStartDebug, StdCmdActivateNextWindow, FCCmdTest2, StdCmdMacroAttachDebugger, StdCmdCloseAllWindows, StdCmdVarSet, StdOrthographicCamera, StdCmdDlgMacroExecuteDirect, FCCmdTest1, StdCmdCloseActiveWindow, StdCmdGroup, StdCmdDlgMacroExecute, StdCmdCascadeWindows, StdCmdWorkbench, StdCmdTileWindows, StdCmdPart, StdCmdDlgMacroRecord, CmdSketcherCompHorizontalVertical, CmdPartDesignCompSketches, CmdPartDesignCompDatums, CmdPartDatums, StdCmdExpression, CmdRenderingOrder, StdCmdViewGroup, CmdSketcherCompSlot, CmdSketcherMove, CmdSketcherClone, CmdSketcherCompExternal, CmdTechDrawCompDimensionTools, CmdSketcherSnap, CmdSketcherCopy, CmdSketcherCompCurveEdition, CmdSketcherCompToggleConstraints, CmdSketcherCompCreateFillets, CmdSketcherGrid, CmdSketcherConstraint, StdCmdLinkActions, StdCmdUserEditMode, CmdSketcherCompCreateConic, Gui::PythonGroupCommand, Gui::PythonCommand, StdCmdDrawStyle, CmdSketcherCompCreateArc, StdCmdFreezeViews, CmdSketcherCompLine, and StdCmdLinkMakeGroup.
Definition at line 343 of file Gui/Command.h.
Referenced by testActive().
isActiveObjectValid()
bool Command::isActiveObjectValid () static
Checks if the active object of the active document is valid.
Definition at line 854 of file Gui/Command.cpp.
References Gui::Application::activeDocument(), App::Document::getActiveObject(), Gui::Document::getDocument(), and Gui::Application::Instance.
isViewOfType()
bool Command::isViewOfType (Base::Type t) const
checks if the active view is of a special type or derived
Definition at line 246 of file Gui/Command.cpp.
References Gui::Application::activeDocument(), Gui::Document::getActiveView(), getGuiApplication(), InitGui::t, and TestSpreadsheet::v.
Referenced by StdViewScreenShot::isActive().
keySequenceToAccel()
const char * Command::keySequenceToAccel (int sk) const protected
Definition at line 915 of file Gui/Command.cpp.
References SplineSurface::i, and Path.Post.scripts.grbl_post::type.
languageChange()
void Command::languageChange () override virtual
Translate command.
Implements Gui::CommandBase.
Reimplemented in CmdRenderingOrder, CmdSketcherSnap, CmdSketcherGrid, StdCmdUserEditMode, Gui::MacroCommand, Gui::PythonGroupCommand, Gui::PythonCommand, Gui::GroupCommand, StdCmdDrawStyle, StdCmdFreezeViews, Gui::StdCmdDownloadOnlineHelp, StdCmdLinkMakeGroup, and StdCmdAbout.
Definition at line 991 of file Gui/Command.cpp.
References Gui::CommandBase::_pcAction, applyCommandData(), and Gui::CommandBase::className().
Referenced by Gui::GroupCommand::languageChange().
openCommand()
void Command::openCommand (const char * sCmdName = nullptr) static
Open a new Undo transaction on the active document.
Open a new Undo transaction on the active document This method opens a new UNDO transaction on the active document. This transaction will later appear in the UNDO REDO dialog with the name of the command. If the user recall the transaction everything changed on the document between OpenCommand() and CommitCommand will be undone (or redone). You can use an alternative name for the operation default is the Command name.
See also
CommitCommand(),AbortCommand()
Definition at line 628 of file Gui/Command.cpp.
References App::GetApplication(), and App::Application::setActiveTransaction().
Referenced by _copyShape(), SpreadsheetGui::DlgBindSheet::accept(), DrawingGui::TaskProjection::accept(), TechDrawGui::TaskProjection::accept(), TechDrawGui::TaskDimRepair::accept(), TechDrawGui::TaskActiveView::accept(), TechDrawGui::TaskCosmeticCircle::accept(), TechDrawGui::TaskCosmeticLine::accept(), TechDrawGui::TaskCustomizeFormat::accept(), ReenGui::FitBSplineSurfaceWidget::accept(), ReenGui::PoissonWidget::accept(), TechDrawGui::TaskSurfaceFinishSymbols::accept(), MeshGui::TaskDecimating::accept(), TechDrawGui::TaskWeldingSymbol::accept(), MeshGui::TaskSmoothing::accept(), TDHandlerDimension::activated(), StdCmdDelete::activated(), DrawSketchHandlerDimension::activated(), CmdSketcherConstrainLock::activated(), CmdSketcherConstrainBlock::activated(), CmdSketcherConstrainDistance::activated(), CmdSketcherConstrainDistanceX::activated(), CmdSketcherConstrainDistanceY::activated(), CmdSketcherConstrainParallel::activated(), CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainRadius::activated(), CmdSketcherConstrainDiameter::activated(), CmdSketcherConstrainRadiam::activated(), CmdSketcherConstrainAngle::activated(), CmdSketcherConstrainEqual::activated(), CmdSketcherConstrainSymmetric::activated(), CmdSketcherConstrainCoincidentUnified::activatedCoincident(), CmdSketcherConstrainCoincidentUnified::activatedPointOnObject(), TechDrawGui::TaskCosVertex::addCosVertex(), SpreadsheetGui::PropertiesDialog::apply(), CmdSketcherConstrainLock::applyConstraint(), CmdSketcherConstrainBlock::applyConstraint(), CmdSketcherConstrainDistance::applyConstraint(), CmdSketcherConstrainDistanceX::applyConstraint(), CmdSketcherConstrainDistanceY::applyConstraint(), CmdSketcherConstrainParallel::applyConstraint(), CmdSketcherConstrainPerpendicular::applyConstraint(), CmdSketcherConstrainTangent::applyConstraint(), CmdSketcherConstrainRadius::applyConstraint(), CmdSketcherConstrainDiameter::applyConstraint(), CmdSketcherConstrainRadiam::applyConstraint(), CmdSketcherConstrainAngle::applyConstraint(), CmdSketcherConstrainEqual::applyConstraint(), CmdSketcherConstrainSymmetric::applyConstraint(), CmdSketcherConstrainCoincidentUnified::applyConstraintCoincident(), CmdSketcherConstrainCoincidentUnified::applyConstraintPointOnObject(), TechDrawGui::QGIViewBalloon::balloonLabelDragFinished(), SurfaceGui::FillingEdgePanel::checkOpenCommand(), SurfaceGui::FillingVertexPanel::checkOpenCommand(), SurfaceGui::GeomFillSurface::checkOpenCommand(), SurfaceGui::SectionsPanel::checkOpenCommand(), SurfaceGui::FillingPanel::checkOpenCommand(), TDHandlerDimension::clearAndRestartCommand(), TechDrawGui::TaskRichAnno::createAnnoFeature(), SketcherGui::DrawSketchHandler::createAutoConstraints(), TechDrawGui::QGSPage::createBalloon(), TechDrawGui::TaskCenterLine::createCenterLine(), TechDrawGui::TaskCosmeticCircle::createCosmeticCircle(), TechDrawGui::TaskCosmeticLine::createCosmeticLine(), TechDrawGui::TaskDetail::createDetail(), TechDrawGui::TaskLeaderLine::createLeaderFeature(), TechDrawGui::TaskSectionView::createSectionView(), TechDrawGui::QGIViewDimension::datumLabelDragFinished(), DefineElementsCallback(), DefineNodesCallback(), SpreadsheetGui::SheetTableView::deleteSelection(), dimensionMaker(), PartGui::ViewProviderPart::doubleClicked(), PartDesignGui::ViewProviderDatum::doubleClicked(), PartDesignGui::ViewProvider::doubleClicked(), PartDesignGui::ViewProviderBase::doubleClicked(), SketcherGui::ViewProviderSketch::editDoubleClicked(), execCascadeHorizDimension(), execCascadeObliqueDimension(), execCascadeVertDimension(), execCircleCenterLines(), execCreateHorizChainDimension(), execCreateHorizChamferDimension(), execCreateHorizCoordDimension(), execCreateObliqueChainDimension(), execCreateObliqueCoordDimension(), execCreateVertChainDimension(), execCreateVertChamferDimension(), execCreateVertCoordDimension(), execDrawCosmArc(), execDrawCosmCircle(), execDrawCosmCircle3Points(), execExtendShortenLine(), TechDrawGui::execHoleCircle(), execIncreaseDecreaseDecimal(), execInsertPrefixChar(), execLineParallelPerpendicular(), execMidpoints(), execPosHorizChainDimension(), execPosObliqueChainDimension(), execPosVertChainDimension(), execQuadrants(), execRemovePrefixChar(), execThreadBoltBottom(), execThreadBoltSide(), execThreadHoleBottom(), execThreadHoleSide(), finishDressupFeature(), horVerActivated(), horVerApplyConstraint(), SpreadsheetGui::SheetTableView::insertColumns(), SpreadsheetGui::SheetTableView::insertColumnsAfter(), SpreadsheetGui::SheetTableView::insertRows(), SpreadsheetGui::SheetTableView::insertRowsAfter(), SketcherGui::makeAngleBetweenTwoLines(), SpreadsheetGui::DlgBindSheet::onDiscard(), SketcherGui::TaskSketcherConstraints::onListWidgetConstraintsItemChanged(), SpreadsheetGui::SheetView::onMsg(), SpreadsheetGui::SheetTableView::onRecompute(), FemGui::TaskDlgMeshShapeNetgen::open(), FemGui::TaskDlgFemConstraint::open(), PartGui::TaskDlgAttacher::open(), FemGui::TaskDlgPost::open(), StdCmdExpression::pasteExpressions(), prepareProfileBased(), prepareTransformed(), SketcherGui::DrawSketchHandlerExternal::releaseButton(), SketcherGui::DrawSketchHandlerCarbonCopy::releaseButton(), DrawSketchHandlerBSplineInsertKnot::releaseButton(), DrawSketchHandlerCopy::releaseButton(), DrawSketchHandlerRectangularArray::releaseButton(), SpreadsheetGui::SheetTableView::removeColumns(), SpreadsheetGui::SheetTableView::removeRows(), DrawSketchHandlerDimension::resetTool(), TDHandlerDimension::restartCommand(), DrawSketchHandlerDimension::restartCommand(), TechDrawGui::PagePrinter::saveDXF(), SpreadsheetGui::WorkbenchHelper::setBackgroundColor(), SpreadsheetGui::WorkbenchHelper::setForegroundColor(), PartDesignGui::ViewProviderShapeBinder::setupContextMenu(), AssemblyGui::ViewProviderAssemblyLink::setupContextMenu(), Gui::ViewProviderDocumentObject::startDefaultEditMode(), CmdSketcherConstrainTangent::substituteConstraintCombinations(), SketcherGui::ConstraintView::swapNamedOfSelectedItems(), TechDrawGui::TaskRichAnno::updateAnnoFeature(), TechDrawGui::TaskDetail::updateDetail(), TechDrawGui::TaskLeaderLine::updateLeaderFeature(), and TechDrawGui::TaskSectionView::updateSectionView().
printCaller()
void Command::printCaller (const char * file, int line) static
Print to Python console the current calling source file and line number.
Definition at line 698 of file Gui/Command.cpp.
References Gui::MacroManager::addLine(), Gui::MacroManager::Cmt, FC_LOG_INSTANCE, FC_LOGLEVEL_LOG, DrawingExample::file, Gui::Application::Instance, Gui::Application::macroManager(), and Path.Post.scripts.refactored_centroid_post::str.
Referenced by _runCommand(), and printPyCaller().
printConflictingAccelerators()
void Command::printConflictingAccelerators () const protected
Definition at line 974 of file Gui/Command.cpp.
References Gui::CommandManager::checkAcceleratorForConflicts(), Gui::Application::commandManager(), Base::Console(), Gui::Application::Instance, Gui::CommandBase::sAccel, sName, and Base::ConsoleSingleton::Warning().
printPyCaller()
void Command::printPyCaller () static
Print to Python console the current Python calling source file and line number.
Definition at line 680 of file Gui/Command.cpp.
References FC_LOG_INSTANCE, FC_LOGLEVEL_LOG, DrawingExample::file, printCaller(), and PyFrame_GetCode().
Referenced by Gui::ApplicationPy::sDoCommand(), Gui::ApplicationPy::sDoCommandGui(), and Gui::ApplicationPy::sDoCommandSkip().
setAppModuleName()
void Command::setAppModuleName (const char * s)
Definition at line 599 of file Gui/Command.cpp.
References StringCache::New(), and sAppModule.
Referenced by Gui::ApplicationPy::sAddCommand().
setEnabled()
void Command::setEnabled (bool on)
Enables or disables the command.
Definition at line 541 of file Gui/Command.cpp.
References Gui::CommandBase::_pcAction, and Gui::Action::setEnabled().
Referenced by Gui::TaskCSysDragger::open(), Path.Dressup.Gui.Tags.HoldingTagMarker::setSelected(), and Gui::TaskTransform::~TaskTransform().
setGroupName()
void Command::setGroupName (const char * s)
Definition at line 604 of file Gui/Command.cpp.
References StringCache::New(), and sGroup.
Referenced by Gui::ApplicationPy::sAddCommand().
setShortcut()
void Command::setShortcut (const QString & shortcut) virtual
Override shortcut of this command.
Reimplemented in StdCmdFreezeViews.
Definition at line 233 of file Gui/Command.cpp.
References Gui::CommandBase::_pcAction, and Gui::Action::setShortcut().
Referenced by initAction().
setupCheckable()
void Command::setupCheckable (int iMsg)
Setup checkable actions based on current TriggerSource.
Definition at line 356 of file Gui/Command.cpp.
References Gui::CommandBase::_pcAction, a, Path.Post.scripts.dynapath_4060_post::action, Gui::Action::action(), Gui::Action::isChecked(), Gui::Action::setCheckable(), Gui::Action::setChecked(), TriggerAction, TriggerChildAction, TriggerNone, and triggerSource().
Referenced by Gui::PythonGroupCommand::activated().
strToPython() [1/2]
const std::string Command::strToPython (const char * Str)
translate a string to a python string literal (needed e.g. in file names for windows...)
Definition at line 842 of file Gui/Command.cpp.
References Base::InterpreterSingleton::strToPython().
strToPython() [2/2]
const std::string Gui::Command::strToPython (const std::string & Str) inline
Definition at line 539 of file Gui/Command.h.
testActive()
void Command::testActive ()
Get somtile called to check the state of the command.
Definition at line 503 of file Gui/Command.cpp.
References Gui::CommandBase::_pcAction, Path.Post.scripts.dynapath_4060_post::action, Alter3DView, AlterDoc, AlterSelection, Gui::Application::commandManager(), Gui::Control(), eType, ForEdit, Gui::CommandManager::getCommandByName(), Gui::Application::Instance, isActive(), and Gui::Action::setEnabled().
Referenced by initAction(), and Gui::MainWindow::updateEditorActions().
translatedGroupName()
QString Command::translatedGroupName () const
Definition at line 609 of file Gui/Command.cpp.
References Gui::CommandBase::className(), and getGroupName().
triggerSource()
TriggerSource Gui::Command::triggerSource () const inline
Return the current command trigger source.
Definition at line 358 of file Gui/Command.h.
Referenced by Gui::GroupCommand::activated(), and setupCheckable().
updateAction()
void Command::updateAction (int mode) override virtual
Updates the QAction with respect to the passed mode.
Implements Gui::CommandBase.
Reimplemented in CmdSketcherConstrainAngle, CmdSketcherConstrainRadiam, CmdSketcherConstrainDiameter, CmdSketcherConstrainRadius, CmdSketcherConstrainDistanceY, CmdSketcherConstrainDistanceX, CmdSketcherConstrainDistance, CmdSketcherConstrainLock, CmdSketcherCompSlot, CmdSketcherCompExternal, CmdSketcherCompDimensionTools, CmdSketcherCompCreateConic, CmdSketcherCompCreateArc, and CmdSketcherCompLine.
Definition at line 998 of file Gui/Command.cpp.
Referenced by Gui::CommandManager::updateCommands().
updateActive()
void Command::updateActive () static
Updates the (active) document (propagate changes)
Definition at line 848 of file Gui/Command.cpp.
References doCommand.
Referenced by _copyShape(), Gui::ViewProviderLink::_setupContextMenu(), DrawingGui::TaskProjection::accept(), TechDrawGui::TaskProjection::accept(), TechDrawGui::TaskActiveView::accept(), TechDrawGui::TaskCosmeticCircle::accept(), TechDrawGui::TaskCosmeticLine::accept(), TechDrawGui::TaskCenterLine::accept(), ReenGui::FitBSplineSurfaceWidget::accept(), ReenGui::PoissonWidget::accept(), SurfaceGui::GeomFillSurface::accept(), TechDrawGui::TaskWeldingSymbol::accept(), SurfaceGui::TaskSections::accept(), SurfaceGui::TaskFilling::accept(), PartGui::DlgScale::apply(), PartGui::DlgExtrusion::apply(), CmdSketcherConstrainLock::applyConstraint(), TechDrawGui::TaskRichAnno::createAnnoFeature(), TechDrawGui::TaskCenterLine::createCenterLine(), TechDrawGui::TaskDetail::createDetail(), TechDrawGui::TaskLeaderLine::createLeaderFeature(), execSimpleSection(), finishFeature(), SketcherGui::ViewProviderSketch::forceUpdateData(), SketcherGui::ViewProviderSketch::onDelete(), TechDrawGui::MDIViewPage::onMsg(), prepareProfileBased(), prepareTransformed(), PartGui::ThicknessWidget::reject(), PartGui::OffsetWidget::reject(), TechDrawGui::TaskSectionView::reject(), TechDrawGui::TaskBalloon::reject(), TechDrawGui::TaskComplexSection::reject(), SurfaceGui::GeomFillSurface::reject(), FemGui::TaskDlgFemConstraint::reject(), SurfaceGui::TaskSections::reject(), SurfaceGui::TaskFilling::reject(), Gui::ViewProviderLink::setupContextMenu(), SketcherGui::tryAutoRecompute(), SketcherGui::ViewProviderSketch::unsetEdit(), TechDrawGui::TaskRichAnno::updateAnnoFeature(), TechDrawGui::TaskDetail::updateDetail(), and TechDrawGui::TaskLeaderLine::updateLeaderFeature().
updateAll()
void Command::updateAll (std::list< Gui::Document * > cList) static
Updates the (all or listed) documents (propagate changes)
Definition at line 865 of file Gui/Command.cpp.
References Gui::Application::Instance, and Gui::Application::onUpdate().
Friends And Related Function Documentation
CommandManager
friend class CommandManager friend
CommandManager is a friend.
Definition at line 341 of file Gui/Command.h.
LogDisabler
friend class LogDisabler friend
Definition at line 595 of file Gui/Command.h.
Member Data Documentation
bCanLog
bool Gui::Command::bCanLog protected
Indicate if the command shall log to MacroManager.
Definition at line 621 of file Gui/Command.h.
Referenced by Command(), invoke(), StdCmdDockOverlay::StdCmdDockOverlay(), StdCmdLinkActions::StdCmdLinkActions(), StdCmdLinkSelectActions::StdCmdLinkSelectActions(), and StdCmdTreeViewActions::StdCmdTreeViewActions().
eType
int Gui::Command::eType protected
Definition at line 619 of file Gui/Command.h.
Referenced by _doCommand(), _runCommand(), StdCmdRefresh::activated(), addModule(), CmdPartDesignCompDatums::CmdPartDesignCompDatums(), CmdPartDesignCompSketches::CmdPartDesignCompSketches(), CmdRenderingOrder::CmdRenderingOrder(), CmdSketcherClone::CmdSketcherClone(), CmdSketcherCompCreateArc::CmdSketcherCompCreateArc(), CmdSketcherCompCreateConic::CmdSketcherCompCreateConic(), CmdSketcherCompCreateFillets::CmdSketcherCompCreateFillets(), CmdSketcherCompCurveEdition::CmdSketcherCompCurveEdition(), CmdSketcherCompExternal::CmdSketcherCompExternal(), CmdSketcherCompHorizontalVertical::CmdSketcherCompHorizontalVertical(), CmdSketcherCompSlot::CmdSketcherCompSlot(), CmdSketcherConstrainAngle::CmdSketcherConstrainAngle(), CmdSketcherConstrainBlock::CmdSketcherConstrainBlock(), CmdSketcherConstrainCoincident::CmdSketcherConstrainCoincident(), CmdSketcherConstrainCoincidentUnified::CmdSketcherConstrainCoincidentUnified(), CmdSketcherConstrainDiameter::CmdSketcherConstrainDiameter(), CmdSketcherConstrainDistance::CmdSketcherConstrainDistance(), CmdSketcherConstrainDistanceX::CmdSketcherConstrainDistanceX(), CmdSketcherConstrainDistanceY::CmdSketcherConstrainDistanceY(), CmdSketcherConstrainEqual::CmdSketcherConstrainEqual(), CmdSketcherConstrainHorizontal::CmdSketcherConstrainHorizontal(), CmdSketcherConstrainHorVer::CmdSketcherConstrainHorVer(), CmdSketcherConstrainLock::CmdSketcherConstrainLock(), CmdSketcherConstrainParallel::CmdSketcherConstrainParallel(), CmdSketcherConstrainPerpendicular::CmdSketcherConstrainPerpendicular(), CmdSketcherConstrainPointOnObject::CmdSketcherConstrainPointOnObject(), CmdSketcherConstrainRadiam::CmdSketcherConstrainRadiam(), CmdSketcherConstrainRadius::CmdSketcherConstrainRadius(), CmdSketcherConstrainSymmetric::CmdSketcherConstrainSymmetric(), CmdSketcherConstrainTangent::CmdSketcherConstrainTangent(), CmdSketcherConstrainVertical::CmdSketcherConstrainVertical(), CmdSketcherCopy::CmdSketcherCopy(), CmdSketcherGrid::CmdSketcherGrid(), CmdSketcherMove::CmdSketcherMove(), CmdSketcherSnap::CmdSketcherSnap(), Command(), Gui::MacroCommand::MacroCommand(), Gui::PythonCommand::PythonCommand(), Gui::PythonGroupCommand::PythonGroupCommand(), StdCmdDockOverlay::StdCmdDockOverlay(), StdCmdDrawStyle::StdCmdDrawStyle(), StdCmdExpression::StdCmdExpression(), StdCmdFreezeViews::StdCmdFreezeViews(), StdCmdLinkActions::StdCmdLinkActions(), StdCmdLinkMakeGroup::StdCmdLinkMakeGroup(), StdCmdLinkSelectActions::StdCmdLinkSelectActions(), StdCmdTreeViewActions::StdCmdTreeViewActions(), StdCmdUserEditMode::StdCmdUserEditMode(), StdCmdViewGroup::StdCmdViewGroup(), and testActive().
sAppModule
const char* Gui::Command::sAppModule protected
Definition at line 615 of file Gui/Command.h.
Referenced by CmdPartDesignCompDatums::CmdPartDesignCompDatums(), CmdPartDesignCompSketches::CmdPartDesignCompSketches(), CmdRenderingOrder::CmdRenderingOrder(), CmdSandboxEventLoop::CmdSandboxEventLoop(), CmdSandboxMeshLoader::CmdSandboxMeshLoader(), CmdSketcherClone::CmdSketcherClone(), CmdSketcherCompCreateArc::CmdSketcherCompCreateArc(), CmdSketcherCompCreateConic::CmdSketcherCompCreateConic(), CmdSketcherCompCreateFillets::CmdSketcherCompCreateFillets(), CmdSketcherCompCurveEdition::CmdSketcherCompCurveEdition(), CmdSketcherCompExternal::CmdSketcherCompExternal(), CmdSketcherCompHorizontalVertical::CmdSketcherCompHorizontalVertical(), CmdSketcherCompSlot::CmdSketcherCompSlot(), CmdSketcherConstrainAngle::CmdSketcherConstrainAngle(), CmdSketcherConstrainBlock::CmdSketcherConstrainBlock(), CmdSketcherConstrainCoincident::CmdSketcherConstrainCoincident(), CmdSketcherConstrainCoincidentUnified::CmdSketcherConstrainCoincidentUnified(), CmdSketcherConstrainDiameter::CmdSketcherConstrainDiameter(), CmdSketcherConstrainDistance::CmdSketcherConstrainDistance(), CmdSketcherConstrainDistanceX::CmdSketcherConstrainDistanceX(), CmdSketcherConstrainDistanceY::CmdSketcherConstrainDistanceY(), CmdSketcherConstrainEqual::CmdSketcherConstrainEqual(), CmdSketcherConstrainHorizontal::CmdSketcherConstrainHorizontal(), CmdSketcherConstrainHorVer::CmdSketcherConstrainHorVer(), CmdSketcherConstrainLock::CmdSketcherConstrainLock(), CmdSketcherConstrainParallel::CmdSketcherConstrainParallel(), CmdSketcherConstrainPerpendicular::CmdSketcherConstrainPerpendicular(), CmdSketcherConstrainPointOnObject::CmdSketcherConstrainPointOnObject(), CmdSketcherConstrainRadiam::CmdSketcherConstrainRadiam(), CmdSketcherConstrainRadius::CmdSketcherConstrainRadius(), CmdSketcherConstrainSymmetric::CmdSketcherConstrainSymmetric(), CmdSketcherConstrainTangent::CmdSketcherConstrainTangent(), CmdSketcherConstrainVertical::CmdSketcherConstrainVertical(), CmdSketcherCopy::CmdSketcherCopy(), CmdSketcherGrid::CmdSketcherGrid(), CmdSketcherMove::CmdSketcherMove(), CmdSketcherSnap::CmdSketcherSnap(), CmdTechDrawCompDimensionTools::CmdTechDrawCompDimensionTools(), Command(), and setAppModuleName().
sGroup
const char* Gui::Command::sGroup protected
Definition at line 616 of file Gui/Command.h.
Referenced by CmdPartDatums::CmdPartDatums(), CmdPartDesignCompDatums::CmdPartDesignCompDatums(), CmdPartDesignCompSketches::CmdPartDesignCompSketches(), CmdRenderingOrder::CmdRenderingOrder(), CmdSandboxEventLoop::CmdSandboxEventLoop(), CmdSandboxMeshLoader::CmdSandboxMeshLoader(), CmdSketcherClone::CmdSketcherClone(), CmdSketcherCompCreateArc::CmdSketcherCompCreateArc(), CmdSketcherCompCreateConic::CmdSketcherCompCreateConic(), CmdSketcherCompCreateFillets::CmdSketcherCompCreateFillets(), CmdSketcherCompCurveEdition::CmdSketcherCompCurveEdition(), CmdSketcherCompExternal::CmdSketcherCompExternal(), CmdSketcherCompHorizontalVertical::CmdSketcherCompHorizontalVertical(), CmdSketcherCompSlot::CmdSketcherCompSlot(), CmdSketcherConstrainAngle::CmdSketcherConstrainAngle(), CmdSketcherConstrainBlock::CmdSketcherConstrainBlock(), CmdSketcherConstrainCoincident::CmdSketcherConstrainCoincident(), CmdSketcherConstrainCoincidentUnified::CmdSketcherConstrainCoincidentUnified(), CmdSketcherConstrainDiameter::CmdSketcherConstrainDiameter(), CmdSketcherConstrainDistance::CmdSketcherConstrainDistance(), CmdSketcherConstrainDistanceX::CmdSketcherConstrainDistanceX(), CmdSketcherConstrainDistanceY::CmdSketcherConstrainDistanceY(), CmdSketcherConstrainEqual::CmdSketcherConstrainEqual(), CmdSketcherConstrainHorizontal::CmdSketcherConstrainHorizontal(), CmdSketcherConstrainHorVer::CmdSketcherConstrainHorVer(), CmdSketcherConstrainLock::CmdSketcherConstrainLock(), CmdSketcherConstrainParallel::CmdSketcherConstrainParallel(), CmdSketcherConstrainPerpendicular::CmdSketcherConstrainPerpendicular(), CmdSketcherConstrainPointOnObject::CmdSketcherConstrainPointOnObject(), CmdSketcherConstrainRadiam::CmdSketcherConstrainRadiam(), CmdSketcherConstrainRadius::CmdSketcherConstrainRadius(), CmdSketcherConstrainSymmetric::CmdSketcherConstrainSymmetric(), CmdSketcherConstrainTangent::CmdSketcherConstrainTangent(), CmdSketcherConstrainVertical::CmdSketcherConstrainVertical(), CmdSketcherCopy::CmdSketcherCopy(), CmdSketcherGrid::CmdSketcherGrid(), CmdSketcherMove::CmdSketcherMove(), CmdSketcherSnap::CmdSketcherSnap(), CmdTechDrawCompDimensionTools::CmdTechDrawCompDimensionTools(), Command(), Gui::MacroCommand::MacroCommand(), Gui::PythonCommand::PythonCommand(), Gui::PythonGroupCommand::PythonGroupCommand(), setGroupName(), Gui::StdCmdDescription::StdCmdDescription(), StdCmdDockOverlay::StdCmdDockOverlay(), Gui::StdCmdDownloadOnlineHelp::StdCmdDownloadOnlineHelp(), StdCmdDrawStyle::StdCmdDrawStyle(), StdCmdExpression::StdCmdExpression(), StdCmdFreezeViews::StdCmdFreezeViews(), StdCmdLinkActions::StdCmdLinkActions(), StdCmdLinkMakeGroup::StdCmdLinkMakeGroup(), StdCmdLinkSelectActions::StdCmdLinkSelectActions(), Gui::StdCmdPythonHelp::StdCmdPythonHelp(), StdCmdTreeViewActions::StdCmdTreeViewActions(), StdCmdUserEditMode::StdCmdUserEditMode(), and StdCmdViewGroup::StdCmdViewGroup().
sHelpUrl
const char* Gui::Command::sHelpUrl protected
Definition at line 618 of file Gui/Command.h.
sName
const char* Gui::Command::sName protected
Definition at line 617 of file Gui/Command.h.
Referenced by _assureWorkbench(), Gui::PythonCommand::activated(), Gui::PythonGroupCommand::activated(), Gui::PythonGroupCommand::createAction(), Gui::PythonCommand::getResource(), Gui::PythonGroupCommand::getResource(), invoke(), and printConflictingAccelerators().
The documentation for this class was generated from the following files:
Gui/Command.h
Gui/Command.cpp