FreeCAD: WireJoiner::WireJoinerP::VectorSet< T > Struct Template Reference
WireJoiner::WireJoinerP::VectorSet< T > Struct Template Reference
Public Member Functions
void sort ()
bool contains (const T &vForContains)
bool intersects (const VectorSet< T > &other)
void insert (const T &vToInsert)
bool insertUnique (const T &vToInsertUnique)
void erase (const T &vToErase)
void clear ()
std::size_t size () const
bool empty () const
Detailed Description
template<class T>
struct WireJoiner::WireJoinerP::VectorSet< T >
Definition at line 283 of file WireJoiner.cpp.
Member Function Documentation
clear()
template<class T > void WireJoiner::WireJoinerP::VectorSet< T >::clear () inline
Definition at line 374 of file WireJoiner.cpp.
Referenced by src.Mod.Test.Document.DocumentObserverCases.Observer::__init__(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::__init__(), WireJoiner::WireJoinerP::buildClosedWire(), WireJoiner::WireJoinerP::clear(), WireJoiner::WireJoinerP::exhaustTightBound(), WireJoiner::WireJoinerP::exhaustTightBoundWithAdjacent(), WireJoiner::WireJoinerP::findClosedWires(), WireJoiner::WireJoinerP::findSuperEdge(), and WireJoiner::WireJoinerP::findTightBound().
contains()
template<class T > bool WireJoiner::WireJoinerP::VectorSet< T >::contains (const T & vForContains) inline
Definition at line 291 of file WireJoiner.cpp.
Referenced by WireJoiner::WireJoinerP::_findClosedWiresUpdateStack(), WireJoiner::WireJoinerP::findSuperEdgeFromAdjacent(), WireJoiner::WireJoinerP::VectorSet< WireInfo * >::insertUnique(), and WireJoiner::WireJoinerP::VectorSet< WireInfo * >::intersects().
empty()
template<class T > bool WireJoiner::WireJoinerP::VectorSet< T >::empty () const inline
Definition at line 383 of file WireJoiner.cpp.
Referenced by WireJoiner::WireJoinerP::_findClosedWiresUpdateEdges(), and WireJoiner::WireJoinerP::_findClosedWiresUpdateStack().
erase()
template<class T > void WireJoiner::WireJoinerP::VectorSet< T >::erase (const T & vToErase) inline
Definition at line 356 of file WireJoiner.cpp.
Referenced by WireJoiner::WireJoinerP::_findClosedWiresUpdateEdges(), WireJoiner::WireJoinerP::exhaustTightBoundUpdateVertex(), and WireJoiner::WireJoinerP::findTightBoundByVertices().
insert()
template<class T > void WireJoiner::WireJoinerP::VectorSet< T >::insert (const T & vToInsert) inline
Definition at line 330 of file WireJoiner.cpp.
Referenced by WireJoiner::WireJoinerP::_findClosedWiresUpdateEdges(), WireJoiner::WireJoinerP::exhaustTightBoundUpdateEdge(), WireJoiner::WireJoinerP::exhaustTightBoundUpdateVertex(), WireJoiner::WireJoinerP::exhaustTightBoundWithAdjacent(), WireJoiner::WireJoinerP::findSuperEdgeFromAdjacent(), WireJoiner::WireJoinerP::findTightBound(), WireJoiner::WireJoinerP::findTightBoundByVertices(), and WireJoiner::WireJoinerP::VectorSet< WireInfo * >::insertUnique().
insertUnique()
template<class T > bool WireJoiner::WireJoinerP::VectorSet< T >::insertUnique (const T & vToInsertUnique) inline
Definition at line 339 of file WireJoiner.cpp.
Referenced by WireJoiner::WireJoinerP::addWire().
intersects()
template<class T > bool WireJoiner::WireJoinerP::VectorSet< T >::intersects (const VectorSet< T > & other) inline
Definition at line 303 of file WireJoiner.cpp.
Referenced by WireJoiner::WireJoinerP::VectorSet< WireInfo * >::intersects().
size()
template<class T > std::size_t WireJoiner::WireJoinerP::VectorSet< T >::size () const inline
Definition at line 379 of file WireJoiner.cpp.
Referenced by Path.Post.Utils.GCodeEditorDialog::done(), and WireJoiner::WireJoinerP::VectorSet< WireInfo * >::intersects().
sort()
template<class T > void WireJoiner::WireJoinerP::VectorSet< T >::sort () inline
Definition at line 284 of file WireJoiner.cpp.
Referenced by WireJoiner::WireJoinerP::VectorSet< WireInfo * >::contains(), and WireJoiner::WireJoinerP::VectorSet< WireInfo * >::intersects().
The documentation for this struct was generated from the following file:
WireJoiner.cpp