FreeCAD: App::FeatureCustomT< FeatureT > Class Template Reference
App::FeatureCustomT< FeatureT > Class Template Reference
#include <FeatureCustom.h>
Public Member Functions
FeatureCustomT ()=default
~FeatureCustomT () override=default
methods override DocumentObject
short mustExecute () const override
DocumentObjectExecReturn * execute () override
recalculate the Feature
const char * getViewProviderName () const override
returns the type name of the ViewProvider
PyObject * getPyObject () override
void setPyObject (PyObject *obj) override
FeatureCustomT (const FeatureCustomT &)=delete
FeatureCustomT (FeatureCustomT &&)=delete
FeatureCustomT & operator= (const FeatureCustomT &)=delete
FeatureCustomT & operator= (FeatureCustomT &&)=delete
void onBeforeChange (const Property *prop) override
void onChanged (const Property *prop) override
void onDocumentRestored () override
void onSettingDocument () override
Detailed Description
template<class FeatureT>
class App::FeatureCustomT< FeatureT >
FeatureCustomT is a template class to be used with DocumentObject or any of its subclasses as template parameter. FeatureCustomT offers a way to add or remove a property at runtime. This class is similar to FeaturePythonT with the difference that it has no support for in Python written feature classes.
Author
Werner Mayer
Definition at line 64 of file FeatureCustom.h.
Constructor & Destructor Documentation
FeatureCustomT() [1/3]
template<class FeatureT > App::FeatureCustomT< FeatureT >::FeatureCustomT () default
~FeatureCustomT()
template<class FeatureT > App::FeatureCustomT< FeatureT >::~FeatureCustomT () override default
FeatureCustomT() [2/3]
template<class FeatureT > App::FeatureCustomT< FeatureT >::FeatureCustomT (const FeatureCustomT< FeatureT > &) delete
FeatureCustomT() [3/3]
template<class FeatureT > App::FeatureCustomT< FeatureT >::FeatureCustomT (FeatureCustomT< FeatureT > &&) delete
Member Function Documentation
execute()
template<class FeatureT > DocumentObjectExecReturn* App::FeatureCustomT< FeatureT >::execute () inline override
recalculate the Feature
Definition at line 80 of file FeatureCustom.h.
Referenced by draftobjects.facebinder.Facebinder::addSubobjects(), Path.Dressup.Gui.Dogbone.ObjectDressup::boneStateList(), Path.Dressup.Tags.ObjectTagDressup::generateTags(), ArchRoof._Roof::getSubVolume(), ArchPanel.PanelCut::getWires(), src.Mod.PartDesign.Scripts.Spring.MySpring::onChanged(), src.Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid::onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped::onChanged(), src.Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt::onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder::onChanged(), MeasureCOM.MeasureCOM::onChanged(), Path.Main.Stock.StockFromBase::onChanged(), Path.Main.Stock.StockCreateBox::onChanged(), Path.Main.Stock.StockCreateCylinder::onChanged(), FeaturePython.DistanceBolt::onChanged(), draftobjects.draftlink.DraftLink::onDocumentRestored(), ArchSchedule._ArchSchedule::setSpreadsheetData(), and draftobjects.array.Array::update_properties_0v21().
getPyObject()
template<class FeatureT > PyObject* App::FeatureCustomT< FeatureT >::getPyObject () inline override
Definition at line 90 of file FeatureCustom.h.
getViewProviderName()
template<class FeatureT > const char* App::FeatureCustomT< FeatureT >::getViewProviderName () const inline override
returns the type name of the ViewProvider
Definition at line 85 of file FeatureCustom.h.
mustExecute()
template<class FeatureT > short App::FeatureCustomT< FeatureT >::mustExecute () const inline override
Definition at line 75 of file FeatureCustom.h.
onBeforeChange()
template<class FeatureT > void App::FeatureCustomT< FeatureT >::onBeforeChange (const Property * prop) inline override protected
Definition at line 100 of file FeatureCustom.h.
onChanged()
template<class FeatureT > void App::FeatureCustomT< FeatureT >::onChanged (const Property * prop) inline override protected
Definition at line 104 of file FeatureCustom.h.
Referenced by draftviewproviders.view_base.ViewProviderDraft::attach(), ArchSpace._ViewProviderSpace::onChanged(), ArchSchedule._ArchSchedule::setProperties(), draftviewproviders.view_wpproxy.ViewProviderWorkingPlaneProxy::updateData(), draftviewproviders.view_layer.ViewProviderLayer::updateData(), draftviewproviders.view_label.ViewProviderLabel::updateData(), ArchAxis._ViewProviderAxis::updateData(), draftviewproviders.view_dimension.ViewProviderLinearDimension::updateData(), ArchSpace._ViewProviderSpace::updateData(), ArchBuildingPart.ViewProviderBuildingPart::updateData(), ArchPanel.ViewProviderPanelCut::updateData(), ArchSite._ViewProviderSite::updateData(), ArchSectionPlane._ViewProviderSectionPlane::updateData(), and ArchPanel.ViewProviderPanelSheet::updateData().
onDocumentRestored()
template<class FeatureT > void App::FeatureCustomT< FeatureT >::onDocumentRestored () inline override protected
Definition at line 108 of file FeatureCustom.h.
Referenced by Path.Base.PropertyBag.PropertyBag::__init__(), and Path.Dressup.DogboneII.Proxy::__init__().
onSettingDocument()
template<class FeatureT > void App::FeatureCustomT< FeatureT >::onSettingDocument () inline override protected
Definition at line 112 of file FeatureCustom.h.
operator=() [1/2]
template<class FeatureT > FeatureCustomT& App::FeatureCustomT< FeatureT >::operator= (const FeatureCustomT< FeatureT > &) delete
operator=() [2/2]
template<class FeatureT > FeatureCustomT& App::FeatureCustomT< FeatureT >::operator= (FeatureCustomT< FeatureT > &&) delete
setPyObject()
template<class FeatureT > void App::FeatureCustomT< FeatureT >::setPyObject (PyObject * obj) inline override
Definition at line 94 of file FeatureCustom.h.
The documentation for this class was generated from the following file:
FeatureCustom.h