FreeCAD: importXLSX Namespace Reference
importXLSX Namespace Reference
Classes
class exprNode
class FormulaTranslator
Functions
def getText (nodelist)
def handleWorkSheet (theDom, actSheet, strList)
def handleCells (cellList, actCellSheet, sList)
def handleWorkBook (theBook, sheetDict, Doc)
def handleStrings (theStr, sList)
def open (nameXLSX)
def insert (nameXLSX, docname)
Variables
bool gui = False
dictionary sepToken
dictionary branchLower = {">": None, "=": None}
dictionary branchHigher = {"=": None}
dictionary treeDict = {"branchLower": branchLower, "branchHigher": branchHigher}
dictionary tokenDic
Function Documentation
getText()
def importXLSX.getText (nodelist)
Definition at line 308 of file importXLSX.py.
Referenced by handleCells(), handleStrings(), and handleWorkBook().
handleCells()
def importXLSX.handleCells (cellList, actCellSheet, sList)
Definition at line 322 of file importXLSX.py.
References getText().
Referenced by handleWorkSheet().
handleStrings()
def importXLSX.handleStrings (theStr, sList)
Definition at line 399 of file importXLSX.py.
References getText().
Referenced by insert(), and open().
handleWorkBook()
def importXLSX.handleWorkBook (theBook, sheetDict, Doc)
Definition at line 367 of file importXLSX.py.
References getText().
Referenced by insert(), and open().
handleWorkSheet()
def importXLSX.handleWorkSheet (theDom, actSheet, strList)
Definition at line 316 of file importXLSX.py.
References handleCells().
Referenced by insert(), and open().
insert()
def importXLSX.insert (nameXLSX, docname)
Definition at line 445 of file importXLSX.py.
References Path.Base.SetupSheet.dict, handleStrings(), handleWorkBook(), and handleWorkSheet().
open()
def importXLSX.open (nameXLSX)
Definition at line 407 of file importXLSX.py.
References Path.Base.SetupSheet.dict, handleStrings(), handleWorkBook(), and handleWorkSheet().
Variable Documentation
branchHigher
dictionary importXLSX.branchHigher = {"=": None}
Definition at line 91 of file importXLSX.py.
branchLower
dictionary importXLSX.branchLower = {">": None, "=": None}
Definition at line 89 of file importXLSX.py.
gui
bool importXLSX.gui = False
Definition at line 62 of file importXLSX.py.
sepToken
dictionary importXLSX.sepToken
Initial value:
 =  {
     "(": None,
     "=": None,
     "<": "branchLower",
     ">": "branchHigher",
     ")": None,
     #  '"':None,
     #  ';':None,
     " ": None,
     ",": None,  # Separator on lists
     "!": None,  # Connector to cells on other Sheets
     "+": None,
     "-": None,
     "*": None,
     "/": None,
     "^": None,
 }
Definition at line 71 of file importXLSX.py.
tokenDic
dictionary importXLSX.tokenDic
Definition at line 106 of file importXLSX.py.
treeDict
dictionary importXLSX.treeDict = {"branchLower": branchLower, "branchHigher": branchHigher}
Definition at line 95 of file importXLSX.py.