FreeCAD: TechDrawGui::QGMarker Class Reference
TechDrawGui::QGMarker Class Reference
QGMarker provides movable symbols.
#include <QGEPath.h>
Public Types
enum { Type = QGraphicsItem::UserType + 302 }
Public Types inherited from TechDrawGui::QGIVertex
enum { Type = QGraphicsItem::UserType + 105 }
Public Types inherited from TechDrawGui::QGIPrimPath
enum { Type = QGraphicsItem::UserType + 170 }
Signals
void dragging (QPointF pos, int idx)
void dragFinished (QPointF pos, int idx)
void doubleClick (QPointF pos, int idx)
void endEdit ()
Public Member Functions
QGMarker (int idx)
~QGMarker () override=default
int type () const override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event) override
void keyPressEvent (QKeyEvent *event) override
void setRadius (float radius) override
adjust the size of this marker
Public Member Functions inherited from TechDrawGui::QGIVertex
QGIVertex (int index)
~QGIVertex () override=default
int type () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
int getProjIndex () const
float getRadius ()
Public Member Functions inherited from TechDrawGui::QGIPrimPath
QGIPrimPath ()
~QGIPrimPath () override=default
int type () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
QPainterPath shape () const override
virtual void setPrettyNormal ()
virtual void setPrettyPre ()
virtual void setPrettySel ()
virtual void setWidth (double w)
virtual double getWidth ()
Qt::PenStyle getStyle ()
void setStyle (Qt::PenStyle s)
void setStyle (int s)
virtual void setNormalColor (QColor c)
virtual void setCapStyle (Qt::PenCapStyle c)
void setFillStyle (Qt::BrushStyle f)
Qt::BrushStyle getFillStyle ()
void setFill (QColor c, Qt::BrushStyle s)
void setFill (QBrush b)
void resetFill ()
void setFillColor (QColor c)
QColor getFillColor ()
void setFillOverride (bool b)
virtual void setCurrentPen ()
Protected Member Functions
bool multiselectEligible () override
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
Protected Member Functions inherited from TechDrawGui::QGIVertex
bool multiselectEligible () override
Protected Member Functions inherited from TechDrawGui::QGIPrimPath
void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
virtual QColor getNormalColor ()
virtual QColor getPreColor ()
virtual QColor getSelectColor ()
Base::Reference< ParameterGrp > getParmGroup ()
virtual Qt::PenCapStyle prefCapStyle ()
Additional Inherited Members
Protected Attributes inherited from TechDrawGui::QGIVertex
int projIndex
float m_radius
Protected Attributes inherited from TechDrawGui::QGIPrimPath
bool isHighlighted
bool multiselectActivated
QPen m_pen
QColor m_colCurrent
QColor m_colNormal
bool m_colOverride
Qt::PenStyle m_styleCurrent
Qt::PenStyle m_styleNormal
double m_width
Qt::PenCapStyle m_capStyle
QBrush m_brush
Qt::BrushStyle m_fillStyleCurrent
QColor m_fillColorCurrent
QColor m_colDefFill
QColor m_colNormalFill
Qt::BrushStyle m_fillDef
Qt::BrushStyle m_fillNormal
Qt::BrushStyle m_fillSelect
bool m_fillOverride
Detailed Description
QGMarker provides movable symbols.
Definition at line 64 of file QGEPath.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 71 of file QGEPath.h.
Constructor & Destructor Documentation
QGMarker()
QGMarker::QGMarker (int idx) explicit
Definition at line 52 of file QGEPath.cpp.
~QGMarker()
TechDrawGui::QGMarker::~QGMarker () override default
Member Function Documentation
doubleClick
void TechDrawGui::QGMarker::doubleClick (QPointF pos, int idx) signal
Referenced by TechDrawGui::QGEPath::showMarkers().
dragFinished
void TechDrawGui::QGMarker::dragFinished (QPointF pos, int idx) signal
Referenced by mouseReleaseEvent(), and TechDrawGui::QGEPath::showMarkers().
dragging
void TechDrawGui::QGMarker::dragging (QPointF pos, int idx) signal
Referenced by mousePressEvent(), and TechDrawGui::QGEPath::showMarkers().
endEdit
void TechDrawGui::QGMarker::endEdit () signal
Referenced by keyPressEvent(), mouseDoubleClickEvent(), mousePressEvent(), mouseReleaseEvent(), and TechDrawGui::QGEPath::showMarkers().
keyPressEvent()
void QGMarker::keyPressEvent (QKeyEvent * event) override
Definition at line 110 of file QGEPath.cpp.
References endEdit().
mouseDoubleClickEvent()
void QGMarker::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * event) override
Definition at line 98 of file QGEPath.cpp.
References endEdit().
mousePressEvent()
void QGMarker::mousePressEvent (QGraphicsSceneMouseEvent * event) override protected
Definition at line 59 of file QGEPath.cpp.
References dragging(), endEdit(), TechDrawGui::QGIVertex::getProjIndex(), TechDrawGui::QGIPrimPath::mousePressEvent(), and RobotExample::pos.
mouseReleaseEvent()
void QGMarker::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) override
Definition at line 78 of file QGEPath.cpp.
References dragFinished(), endEdit(), TechDrawGui::QGIVertex::getProjIndex(), TechDrawGui::QGIPrimPath::mouseReleaseEvent(), and RobotExample::pos.
multiselectEligible()
bool TechDrawGui::QGMarker::multiselectEligible () inline override protected virtual
Reimplemented from TechDrawGui::QGIPrimPath.
Definition at line 87 of file QGEPath.h.
setRadius()
void QGMarker::setRadius (float radius) override virtual
adjust the size of this marker
Reimplemented from TechDrawGui::QGIVertex.
Definition at line 121 of file QGEPath.cpp.
References TechDrawGui::QGIVertex::m_radius.
type()
int TechDrawGui::QGMarker::type () const inline override
Definition at line 72 of file QGEPath.h.
The documentation for this class was generated from the following files:
QGEPath.h
QGEPath.cpp