FreeCAD: Wm4::ParametricSurface< Real > Class Template Reference
Wm4::ParametricSurface< Real > Class Template Reference abstract
#include <Wm4ParametricSurface.h>
Public Member Functions
virtual ~ParametricSurface ()
Real GetUMin () const
Real GetUMax () const
Real GetVMin () const
Real GetVMax () const
bool IsRectangular () const
virtual Vector3< Real > P (Real fU, Real fV) const =0
virtual Vector3< Real > PU (Real fU, Real fV) const =0
virtual Vector3< Real > PV (Real fU, Real fV) const =0
virtual Vector3< Real > PUU (Real fU, Real fV) const =0
virtual Vector3< Real > PUV (Real fU, Real fV) const =0
virtual Vector3< Real > PVV (Real fU, Real fV) const =0
void GetFrame (Real fU, Real fV, Vector3< Real > &rkPosition, Vector3< Real > &rkTangent0, Vector3< Real > &rkTangent1, Vector3< Real > &rkNormal) const
void ComputePrincipalCurvatureInfo (Real fU, Real fV, Real &rfCurv0, Real &rfCurv1, Vector3< Real > &rkDir0, Vector3< Real > &rkDir1)
Public Member Functions inherited from Wm4::Surface< Real >
virtual ~Surface ()
Protected Member Functions
ParametricSurface (Real fUMin, Real fUMax, Real fVMin, Real fVMax, bool bRectangular)
Protected Member Functions inherited from Wm4::Surface< Real >
Surface ()
Protected Attributes
Real m_fUMin
Real m_fUMax
Real m_fVMin
Real m_fVMax
bool m_bRectangular
Detailed Description
template<class Real>
class Wm4::ParametricSurface< Real >
Definition at line 28 of file Wm4ParametricSurface.h.
Constructor & Destructor Documentation
~ParametricSurface()
template<class Real > Wm4::ParametricSurface< Real >::~ParametricSurface virtual
Definition at line 38 of file Wm4ParametricSurface.cpp.
ParametricSurface()
template<class Real > Wm4::ParametricSurface< Real >::ParametricSurface (Real fUMin, Real fUMax, Real fVMin, Real fVMax, bool bRectangular) protected
Definition at line 25 of file Wm4ParametricSurface.cpp.
Member Function Documentation
ComputePrincipalCurvatureInfo()
template<class Real > void Wm4::ParametricSurface< Real >::ComputePrincipalCurvatureInfo (Real fU, Real fV, Real & rfCurv0, Real & rfCurv1, Vector3< Real > & rkDir0, Vector3< Real > & rkDir1)
Definition at line 91 of file Wm4ParametricSurface.cpp.
References Wm4::Vector3< Real >::Cross(), Wm4::Matrix2< Real >::Determinant(), Wm4::Vector3< Real >::Dot(), Wm4::Vector3< Real >::Normalize(), Wm4::Math< Real >::Sqrt(), and Wm4::Vector3< Real >::UnitCross().
GetFrame()
template<class Real > void Wm4::ParametricSurface< Real >::GetFrame (Real fU, Real fV, Vector3< Real > & rkPosition, Vector3< Real > & rkTangent0, Vector3< Real > & rkTangent1, Vector3< Real > & rkNormal) const
Definition at line 73 of file Wm4ParametricSurface.cpp.
References Wm4::Vector3< Real >::Cross(), Wm4::Vector3< Real >::Normalize(), and Wm4::Vector3< Real >::UnitCross().
GetUMax()
template<class Real > Real Wm4::ParametricSurface< Real >::GetUMax
Definition at line 49 of file Wm4ParametricSurface.cpp.
GetUMin()
template<class Real > Real Wm4::ParametricSurface< Real >::GetUMin
Definition at line 43 of file Wm4ParametricSurface.cpp.
GetVMax()
template<class Real > Real Wm4::ParametricSurface< Real >::GetVMax
Definition at line 61 of file Wm4ParametricSurface.cpp.
GetVMin()
template<class Real > Real Wm4::ParametricSurface< Real >::GetVMin
Definition at line 55 of file Wm4ParametricSurface.cpp.
IsRectangular()
template<class Real > bool Wm4::ParametricSurface< Real >::IsRectangular
Definition at line 67 of file Wm4ParametricSurface.cpp.
P()
template<class Real > virtual Vector3<Real> Wm4::ParametricSurface< Real >::P (Real fU, Real fV) const pure virtual
PU()
template<class Real > virtual Vector3<Real> Wm4::ParametricSurface< Real >::PU (Real fU, Real fV) const pure virtual
PUU()
template<class Real > virtual Vector3<Real> Wm4::ParametricSurface< Real >::PUU (Real fU, Real fV) const pure virtual
PUV()
template<class Real > virtual Vector3<Real> Wm4::ParametricSurface< Real >::PUV (Real fU, Real fV) const pure virtual
PV()
template<class Real > virtual Vector3<Real> Wm4::ParametricSurface< Real >::PV (Real fU, Real fV) const pure virtual
PVV()
template<class Real > virtual Vector3<Real> Wm4::ParametricSurface< Real >::PVV (Real fU, Real fV) const pure virtual
Member Data Documentation
m_bRectangular
template<class Real > bool Wm4::ParametricSurface< Real >::m_bRectangular protected
Definition at line 71 of file Wm4ParametricSurface.h.
m_fUMax
template<class Real > Real Wm4::ParametricSurface< Real >::m_fUMax protected
Definition at line 70 of file Wm4ParametricSurface.h.
m_fUMin
template<class Real > Real Wm4::ParametricSurface< Real >::m_fUMin protected
Definition at line 70 of file Wm4ParametricSurface.h.
m_fVMax
template<class Real > Real Wm4::ParametricSurface< Real >::m_fVMax protected
Definition at line 70 of file Wm4ParametricSurface.h.
m_fVMin
template<class Real > Real Wm4::ParametricSurface< Real >::m_fVMin protected
Definition at line 70 of file Wm4ParametricSurface.h.
The documentation for this class was generated from the following files:
Wm4ParametricSurface.h
Wm4ParametricSurface.cpp