FreeCAD: Base::Factory Class Reference
Base::Factory Class Reference
#include <Factory.h>
Public Member Functions
void AddProducer (const char *sClassName, AbstractProducer *pcProducer)
Adds a new prducer instance.
bool CanProduce (const char *sClassName) const
returns true if there is a producer for this class registered
std::list< std::string > CanProduce () const
returns a list of all registered producer
virtual ~Factory ()
destruction
Protected Member Functions
void * Produce (const char *sClassName) const
produce a class with the given name
Factory ()=default
construction
Protected Attributes
std::map< const std::string, AbstractProducer * > _mpcProducers
Detailed Description
Base class of all factories This class has the purpose to produce instances of classes at runtime that are unknown at compile time. It holds a map of so called producers which are able to produce an instance of a special class. Producer can be registered at runtime through e.g. application modules
Definition at line 79 of file Factory.h.
Constructor & Destructor Documentation
~Factory()
Factory::~Factory () virtual
destruction
Definition at line 38 of file Factory.cpp.
References _mpcProducers.
Factory()
Base::Factory::Factory () protected default
construction
Member Function Documentation
AddProducer()
void Factory::AddProducer (const char * sClassName, AbstractProducer * pcProducer)
Adds a new prducer instance.
Definition at line 57 of file Factory.cpp.
References _mpcProducers.
Referenced by Gui::CustomPageProducer< CLASS >::CustomPageProducer(), Base::ExceptionProducer< CLASS >::ExceptionProducer(), Gui::PrefPageProducer< CLASS >::PrefPageProducer(), Gui::PrefPagePyProducer::PrefPagePyProducer(), Gui::PrefPageUiProducer::PrefPageUiProducer(), Gui::PropertyEditor::PropertyItemProducer< CLASS >::PropertyItemProducer(), and Gui::WidgetProducer< CLASS >::WidgetProducer().
CanProduce() [1/2]
std::list< std::string > Factory::CanProduce () const
returns a list of all registered producer
Definition at line 67 of file Factory.cpp.
References _mpcProducers.
CanProduce() [2/2]
bool Factory::CanProduce (const char * sClassName) const
returns true if there is a producer for this class registered
Definition at line 62 of file Factory.cpp.
References _mpcProducers.
Referenced by Gui::UiLoaderPy::availableWidgets().
Produce()
void * Factory::Produce (const char * sClassName) const protected
produce a class with the given name
Definition at line 45 of file Factory.cpp.
References _mpcProducers.
Referenced by Gui::WidgetFactoryInst::createPreferencePage(), Gui::WidgetFactoryInst::createWidget(), Gui::WorkbenchFactoryInst::createWorkbench(), and Base::ScriptFactorySingleton::ProduceScript().
Member Data Documentation
_mpcProducers
std::map<const std::string, AbstractProducer*> Base::Factory::_mpcProducers protected
Definition at line 99 of file Factory.h.
Referenced by AddProducer(), CanProduce(), Produce(), Base::ExceptionFactory::raiseException(), Gui::WorkbenchFactoryInst::workbenches(), and ~Factory().
The documentation for this class was generated from the following files:
Factory.h
Factory.cpp