FreeCAD: Gui::Dialog::NumberRange Class Reference
Gui::Dialog::NumberRange Class Reference
#include <DlgExpressionInput.h>
Public Member Functions
void setRange (double minimum, double maximum)
void clearRange ()
void throwIfOutOfRange (const Base::Quantity &) const
Detailed Description
Definition at line 51 of file DlgExpressionInput.h.
Member Function Documentation
clearRange()
void NumberRange::clearRange ()
Definition at line 234 of file DlgExpressionInput.cpp.
Referenced by Gui::Dialog::DlgExpressionInput::clearRange().
setRange()
void NumberRange::setRange (double minimum, double maximum)
Definition at line 227 of file DlgExpressionInput.cpp.
References KDL::max(), and KDL::min().
Referenced by Gui::Dialog::DlgExpressionInput::setRange().
throwIfOutOfRange()
void NumberRange::throwIfOutOfRange (const Base::Quantity & value) const
Definition at line 239 of file DlgExpressionInput.cpp.
References Base::Quantity::getUnit(), Base::Quantity::getUserString(), and Base::Quantity::getValue().
The documentation for this class was generated from the following files:
DlgExpressionInput.h
DlgExpressionInput.cpp