FreeCAD: FemGui::TaskFemConstraintBearing Class Reference
FemGui::TaskFemConstraintBearing Class Reference
#include <TaskFemConstraintBearing.h>
Public Member Functions
TaskFemConstraintBearing (ViewProviderFemConstraint *ConstraintView, QWidget *parent=nullptr, const char *pixmapname="FEM_ConstraintBearing")
~TaskFemConstraintBearing () override
double getDistance () const
const std::string getReferences () const override
const std::string getLocationName () const
const std::string getLocationObject () const
bool getAxial () const
Public Member Functions inherited from FemGui::TaskFemConstraint
TaskFemConstraint (ViewProviderFemConstraint *ConstraintView, QWidget *parent=nullptr, const char *pixmapname="")
~TaskFemConstraint () override=default
const std::string getReferences (const std::vector< std::string > &items) const
const std::string getScale () const
Public Member Functions inherited from Gui::TaskView::TaskBox
TaskBox (QWidget *parent=nullptr)
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
QSize minimumSizeHint () const override
~TaskBox () override
void hideGroupBox ()
bool isGroupVisible () const
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (QWidget *parent=nullptr)
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
QBoxLayout * groupLayout ()
void setScheme (ActionPanelScheme *pointer)
bool isExpandable () const
bool hasHeader () const
QString headerText () const
QSize minimumSizeHint () const override
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Protected Member Functions
void changeEvent (QEvent *e) override
void onSelectionChanged (const Gui::SelectionChanges &msg) override
Protected Member Functions inherited from FemGui::TaskFemConstraint
void changeEvent (QEvent *e) override
const QString makeRefText (const std::string &objName, const std::string &subName) const
const QString makeRefText (const App::DocumentObject *obj, const std::string &subName) const
void keyPressEvent (QKeyEvent *ke) override
void createDeleteAction (QListWidget *parentList)
Protected Member Functions inherited from Gui::TaskView::TaskBox
void showEvent (QShowEvent *) override
void actionEvent (QActionEvent *) override
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
void paintEvent (QPaintEvent *event) override
Protected Attributes
std::unique_ptr< Ui_TaskFemConstraintBearing > ui
Protected Attributes inherited from FemGui::TaskFemConstraint
QWidget * proxy
QAction * deleteAction
Gui::WeakPtrT< ViewProviderFemConstraint > ConstraintView
enum FemGui::TaskFemConstraint:: { ... } selectionMode
Protected Attributes inherited from QSint::ActionGroup
double m_foldStep
double m_foldDelta
double m_fullHeight
double m_tempHeight
int m_foldDirection
QPixmap m_foldPixmap
class TaskHeader * myHeader
class TaskGroup * myGroup
QWidget * myDummy
ActionPanelScheme * myScheme
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void showHide ()
void setExpandable (bool expandable=true)
void setHeader (bool enable=true)
void setHeaderText (const QString &title)
void setHeaderIcon (const QPixmap &icon)
Protected Types inherited from FemGui::TaskFemConstraint
enum { seldir, selref, selloc, selnone }
Protected Slots inherited from FemGui::TaskFemConstraint
void onReferenceDeleted (const int row)
void onButtonReference (const bool pressed=true)
void setSelection (QListWidgetItem *item)
bool event (QEvent *event) override
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Detailed Description
Definition at line 49 of file TaskFemConstraintBearing.h.
Constructor & Destructor Documentation
TaskFemConstraintBearing()
TaskFemConstraintBearing::TaskFemConstraintBearing (ViewProviderFemConstraint * ConstraintView, QWidget * parent = nullptr, const char * pixmapname = "FEM_ConstraintBearing") explicit
Definition at line 51 of file TaskFemConstraintBearing.cpp.
References Fem::ConstraintBearing::AxialFree, draftgeoutils.intersections::connect(), FemGui::TaskFemConstraint::ConstraintView, FemGui::TaskFemConstraint::createDeleteAction(), FemGui::TaskFemConstraint::deleteAction, Fem::ConstraintBearing::Dist, FLOAT_MAX, App::PropertyLinkSub::getSubValues(), App::PropertyLinkSubList::getSubValues(), App::PropertyFloat::getValue(), App::PropertyLinkSub::getValue(), App::PropertyBool::getValue(), App::PropertyLinkSubList::getValues(), QSint::ActionGroup::groupLayout(), SplineSurface::i, Fem::ConstraintBearing::Location, FemGui::TaskFemConstraint::makeRefText(), FemGui::TaskFemConstraint::onButtonReference(), FemGui::TaskFemConstraint::proxy, Fem::Constraint::References, and ui.
~TaskFemConstraintBearing()
TaskFemConstraintBearing::~TaskFemConstraintBearing () override default
Member Function Documentation
changeEvent()
void TaskFemConstraintBearing::changeEvent (QEvent * e) override protected
Definition at line 308 of file TaskFemConstraintBearing.cpp.
References SCL.SimpleDataTypes::e, FemGui::TaskFemConstraint::proxy, and ui.
getAxial()
bool TaskFemConstraintBearing::getAxial () const
Definition at line 301 of file TaskFemConstraintBearing.cpp.
References ui.
Referenced by FemGui::TaskDlgFemConstraintBearing::accept().
getDistance()
double TaskFemConstraintBearing::getDistance () const
Definition at line 263 of file TaskFemConstraintBearing.cpp.
References ui.
Referenced by FemGui::TaskDlgFemConstraintBearing::accept().
getLocationName()
const std::string TaskFemConstraintBearing::getLocationName () const
Definition at line 279 of file TaskFemConstraintBearing.cpp.
References RobotExample::pos, and ui.
Referenced by FemGui::TaskDlgFemConstraintBearing::accept().
getLocationObject()
const std::string TaskFemConstraintBearing::getLocationObject () const
Definition at line 290 of file TaskFemConstraintBearing.cpp.
References RobotExample::pos, and ui.
Referenced by FemGui::TaskDlgFemConstraintBearing::accept().
getReferences()
const std::string TaskFemConstraintBearing::getReferences () const override virtual
Reimplemented from FemGui::TaskFemConstraint.
Definition at line 268 of file TaskFemConstraintBearing.cpp.
References FemGui::TaskFemConstraint::getReferences(), src.Mod.Test.testPathArray::items, and ui.
onSelectionChanged()
void TaskFemConstraintBearing::onSelectionChanged (const Gui::SelectionChanges & msg) override protected virtual
Reimplemented from FemGui::TaskFemConstraint.
Reimplemented in FemGui::TaskFemConstraintGear.
Definition at line 139 of file TaskFemConstraintBearing.cpp.
References Gui::SelectionChanges::AddSelection, Gui::SelectionSingleton::clearSelection(), FemGui::TaskFemConstraint::ConstraintView, Part::PropertyPartShape::getShape(), Part::TopoShape::getSubShape(), App::PropertyLinkSubList::getSubValues(), App::PropertyLinkSubList::getValues(), Fem::Tools::isLinear(), Fem::Tools::isPlanar(), Fem::ConstraintBearing::Location, FemGui::TaskFemConstraint::makeRefText(), Path.Op.Surface::msg, FemGui::TaskFemConstraint::onButtonReference(), Fem::Constraint::References, Gui::Selection(), FemGui::TaskFemConstraint::selectionMode, FemGui::TaskFemConstraint::selloc, FemGui::TaskFemConstraint::selnone, FemGui::TaskFemConstraint::selref, App::PropertyLinkSub::setValue(), App::PropertyLinkSubList::setValues(), Part::Feature::Shape, ui, and Path.Log::warning().
Referenced by FemGui::TaskFemConstraintGear::onSelectionChanged().
Member Data Documentation
ui
std::unique_ptr<Ui_TaskFemConstraintBearing> FemGui::TaskFemConstraintBearing::ui protected
Definition at line 76 of file TaskFemConstraintBearing.h.
Referenced by changeEvent(), FemGui::TaskFemConstraintPulley::changeEvent(), FemGui::TaskFemConstraintGear::changeEvent(), DraftGui.DraftToolBar::changeEvent(), getAxial(), FemGui::TaskFemConstraintPulley::getCenterDistance(), FemGui::TaskFemConstraintGear::getDiameter(), FemGui::TaskFemConstraintGear::getDirectionName(), FemGui::TaskFemConstraintGear::getDirectionObject(), getDistance(), FemGui::TaskFemConstraintGear::getForce(), FemGui::TaskFemConstraintGear::getForceAngle(), FemGui::TaskFemConstraintPulley::getIsDriven(), getLocationName(), getLocationObject(), FemGui::TaskFemConstraintPulley::getOtherDiameter(), getReferences(), FemGui::TaskFemConstraintGear::getReverse(), FemGui::TaskFemConstraintPulley::getTensionForce(), FemGui::TaskFemConstraintPulley::getTorque(), onSelectionChanged(), FemGui::TaskFemConstraintGear::onSelectionChanged(), TaskFemConstraintBearing(), FemGui::TaskFemConstraintGear::TaskFemConstraintGear(), and FemGui::TaskFemConstraintPulley::TaskFemConstraintPulley().
The documentation for this class was generated from the following files:
TaskFemConstraintBearing.h
TaskFemConstraintBearing.cpp