FreeCAD: Sandbox::DocumentObjectProtectorPy Class Reference
Sandbox::DocumentObjectProtectorPy Class Reference
#include <DocumentProtectorPy.h>
Public Member Functions
DocumentObjectProtectorPy (App::DocumentObject *obj)
DocumentObjectProtectorPy (App::DocumentObjectPy *obj)
~DocumentObjectProtectorPy ()
Py::Object repr ()
Py::Object getattr (const char *)
Py::Object getObject () const
int setattr (const char *, const Py::Object &)
Py::Object purgeTouched (const Py::Tuple &)
Static Public Member Functions
static void init_type (void)
Friends
class DocumentObjectProtector
Detailed Description
Definition at line 64 of file DocumentProtectorPy.h.
Constructor & Destructor Documentation
DocumentObjectProtectorPy() [1/2]
DocumentObjectProtectorPy::DocumentObjectProtectorPy (App::DocumentObject * obj)
Definition at line 169 of file DocumentProtectorPy.cpp.
References DocumentObjectProtector.
DocumentObjectProtectorPy() [2/2]
DocumentObjectProtectorPy::DocumentObjectProtectorPy (App::DocumentObjectPy * obj)
Definition at line 174 of file DocumentProtectorPy.cpp.
References DocumentObjectProtector.
~DocumentObjectProtectorPy()
DocumentObjectProtectorPy::~DocumentObjectProtectorPy ()
Definition at line 179 of file DocumentProtectorPy.cpp.
Member Function Documentation
getattr()
Py::Object DocumentObjectProtectorPy::getattr (const char * attr)
Definition at line 201 of file DocumentProtectorPy.cpp.
References Sandbox::DocumentObjectProtector::getObject(), App::ExtensionContainer::getPropertyByName(), Base::BaseClass::getPyObject(), and toolbit-attributes::s.
getObject()
Py::Object DocumentObjectProtectorPy::getObject () const
Definition at line 184 of file DocumentProtectorPy.cpp.
References Sandbox::DocumentObjectProtector::getObject(), and App::DocumentObject::getPyObject().
Referenced by setattr().
init_type()
void DocumentObjectProtectorPy::init_type (void) static
Definition at line 157 of file DocumentProtectorPy.cpp.
References purgeTouched().
purgeTouched()
Py::Object DocumentObjectProtectorPy::purgeTouched (const Py::Tuple &)
Definition at line 254 of file DocumentProtectorPy.cpp.
References Sandbox::DocumentObjectProtector::purgeTouched().
Referenced by init_type().
repr()
Py::Object DocumentObjectProtectorPy::repr ()
Definition at line 191 of file DocumentProtectorPy.cpp.
References toolbit-attributes::s, and src.Mod.Test.testmakeWireString::String.
setattr()
int DocumentObjectProtectorPy::setattr (const char * attr, const Py::Object & value)
Definition at line 224 of file DocumentProtectorPy.cpp.
References Base::Type::createInstance(), getObject(), Sandbox::DocumentObjectProtector::getObject(), App::ExtensionContainer::getPropertyByName(), Base::Persistence::getTypeId(), toolbit-attributes::s, and Sandbox::DocumentObjectProtector::setProperty().
Friends And Related Function Documentation
DocumentObjectProtector
friend class DocumentObjectProtector friend
Definition at line 81 of file DocumentProtectorPy.h.
Referenced by DocumentObjectProtectorPy().
The documentation for this class was generated from the following files:
DocumentProtectorPy.h
DocumentProtectorPy.cpp