FreeCAD: Gui::SoAutoZoomTranslation Class Reference
Gui::SoAutoZoomTranslation Class Reference
#include <SoAutoZoomTranslation.h>
Public Member Functions
SoAutoZoomTranslation ()
Static Public Member Functions
static void initClass ()
Public Attributes
SoSFFloat scaleFactor
Protected Member Functions
~SoAutoZoomTranslation () override=default
void doAction (SoAction *action) override
void getPrimitiveCount (SoGetPrimitiveCountAction *action) override
void getMatrix (SoGetMatrixAction *action) override
void GLRender (SoGLRenderAction *action) override
void getBoundingBox (SoGetBoundingBoxAction *action) override
void callback (SoCallbackAction *action) override
void pick (SoPickAction *action) override
float getScaleFactor (SoAction *) const
Detailed Description
Definition at line 53 of file SoAutoZoomTranslation.h.
Constructor & Destructor Documentation
SoAutoZoomTranslation()
SoAutoZoomTranslation::SoAutoZoomTranslation ()
Definition at line 81 of file SoAutoZoomTranslation.cpp.
References SCL.SimpleDataTypes::f, and scaleFactor.
~SoAutoZoomTranslation()
Gui::SoAutoZoomTranslation::~SoAutoZoomTranslation () override protected default
Member Function Documentation
callback()
void SoAutoZoomTranslation::callback (SoCallbackAction * action) override protected
Definition at line 135 of file SoAutoZoomTranslation.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and doAction().
Referenced by Path.Main.Gui.Camotics.CamoticsSimulation::execute().
doAction()
void SoAutoZoomTranslation::doAction (SoAction * action) override protected
Definition at line 95 of file SoAutoZoomTranslation.cpp.
References Path.Post.scripts.dynapath_4060_post::action, getScaleFactor(), toolbit-attributes::s, and InitGui::t.
Referenced by callback(), getBoundingBox(), getPrimitiveCount(), GLRender(), and pick().
getBoundingBox()
void SoAutoZoomTranslation::getBoundingBox (SoGetBoundingBoxAction * action) override protected
Definition at line 140 of file SoAutoZoomTranslation.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and doAction().
getMatrix()
void SoAutoZoomTranslation::getMatrix (SoGetMatrixAction * action) override protected
Definition at line 120 of file SoAutoZoomTranslation.cpp.
References Path.Post.scripts.dynapath_4060_post::action, getScaleFactor(), test::m, toolbit-attributes::s, and InitGui::t.
getPrimitiveCount()
void SoAutoZoomTranslation::getPrimitiveCount (SoGetPrimitiveCountAction * action) override protected
Definition at line 151 of file SoAutoZoomTranslation.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and doAction().
getScaleFactor()
float SoAutoZoomTranslation::getScaleFactor (SoAction * action) const protected
Definition at line 69 of file SoAutoZoomTranslation.cpp.
References Path.Post.scripts.dynapath_4060_post::action, SCL.SimpleDataTypes::f, draftfunctions.scale::scale(), and scaleFactor.
Referenced by doAction(), and getMatrix().
GLRender()
void SoAutoZoomTranslation::GLRender (SoGLRenderAction * action) override protected
Definition at line 88 of file SoAutoZoomTranslation.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and doAction().
initClass()
void SoAutoZoomTranslation::initClass () static
Definition at line 47 of file SoAutoZoomTranslation.cpp.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
pick()
void SoAutoZoomTranslation::pick (SoPickAction * action) override protected
Definition at line 145 of file SoAutoZoomTranslation.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and doAction().
Member Data Documentation
scaleFactor
SoSFFloat Gui::SoAutoZoomTranslation::scaleFactor
Definition at line 82 of file SoAutoZoomTranslation.h.
Referenced by PartDesignGui::ViewProviderDatumCoordinateSystem::attach(), Gui::AxisOrigin::getNode(), getScaleFactor(), SoSwitchMarker.SoSwitchMarker::line_sep(), PartDesignGui::ViewProviderDatumCoordinateSystem::onChanged(), SoSwitchMarker.SoSwitchMarker::plane_sep(), and SoAutoZoomTranslation().
The documentation for this class was generated from the following files:
SoAutoZoomTranslation.h
SoAutoZoomTranslation.cpp