FreeCAD: MeshGui::MeshRenderer::Private Class Reference
MeshGui::MeshRenderer::Private Class Reference
Public Member Functions
Private ()
bool canRenderGLArray (SoGLRenderAction *) const
void generateGLArrays (SoGLRenderAction *action, SoMaterialBindingElement::Binding matbind, std::vector< float > &vertex, std::vector< int32_t > &index)
void renderFacesGLArray (SoGLRenderAction *)
void renderCoordsGLArray (SoGLRenderAction *)
void update ()
bool needUpdate (SoGLRenderAction *)
Public Attributes
Gui::OpenGLMultiBuffer vertices
Gui::OpenGLMultiBuffer indices
const SbColor * pcolors {nullptr}
SoMaterialBindingElement::Binding matbinding {SoMaterialBindingElement::OVERALL}
bool initialized {false}
Detailed Description
Definition at line 73 of file SoFCIndexedFaceSet.cpp.
Constructor & Destructor Documentation
Private()
MeshGui::MeshRenderer::Private::Private ()
Definition at line 97 of file SoFCIndexedFaceSet.cpp.
Member Function Documentation
canRenderGLArray()
bool MeshGui::MeshRenderer::Private::canRenderGLArray (SoGLRenderAction * action) const
Definition at line 102 of file SoFCIndexedFaceSet.cpp.
References Path.Post.scripts.dynapath_4060_post::action, SIM::Coin3D::Quarter::Quarter::init(), and Gui::OpenGLBuffer::isVBOSupported().
Referenced by MeshGui::MeshRenderer::canRenderGLArray().
generateGLArrays()
void MeshGui::MeshRenderer::Private::generateGLArrays (SoGLRenderAction * action, SoMaterialBindingElement::Binding matbind, std::vector< float > & vertex, std::vector< int32_t > & index)
Definition at line 118 of file SoFCIndexedFaceSet.cpp.
References Path.Post.scripts.dynapath_4060_post::action.
Referenced by MeshGui::MeshRenderer::generateGLArrays().
needUpdate()
bool MeshGui::MeshRenderer::Private::needUpdate (SoGLRenderAction * action)
Definition at line 195 of file SoFCIndexedFaceSet.cpp.
References Path.Post.scripts.dynapath_4060_post::action.
Referenced by MeshGui::MeshRenderer::needUpdate().
renderCoordsGLArray()
void MeshGui::MeshRenderer::Private::renderCoordsGLArray (SoGLRenderAction * action)
Definition at line 184 of file SoFCIndexedFaceSet.cpp.
References Path.Post.scripts.dynapath_4060_post::action.
Referenced by MeshGui::MeshRenderer::renderCoordsGLArray().
renderFacesGLArray()
void MeshGui::MeshRenderer::Private::renderFacesGLArray (SoGLRenderAction * action)
Definition at line 179 of file SoFCIndexedFaceSet.cpp.
References Path.Post.scripts.dynapath_4060_post::action.
Referenced by MeshGui::MeshRenderer::renderFacesGLArray().
update()
void MeshGui::MeshRenderer::Private::update ()
Definition at line 189 of file SoFCIndexedFaceSet.cpp.
Referenced by Plot.Plot::plot(), and MeshGui::MeshRenderer::update().
Member Data Documentation
indices
Gui::OpenGLMultiBuffer MeshGui::MeshRenderer::Private::indices
Definition at line 77 of file SoFCIndexedFaceSet.cpp.
initialized
bool MeshGui::MeshRenderer::Private::initialized {false}
Definition at line 80 of file SoFCIndexedFaceSet.cpp.
matbinding
SoMaterialBindingElement::Binding MeshGui::MeshRenderer::Private::matbinding {SoMaterialBindingElement::OVERALL}
Definition at line 79 of file SoFCIndexedFaceSet.cpp.
Referenced by MeshGui::MeshRenderer::matchMaterial().
pcolors
const SbColor* MeshGui::MeshRenderer::Private::pcolors {nullptr}
Definition at line 78 of file SoFCIndexedFaceSet.cpp.
Referenced by MeshGui::MeshRenderer::generateGLArrays(), and MeshGui::MeshRenderer::matchMaterial().
vertices
Gui::OpenGLMultiBuffer MeshGui::MeshRenderer::Private::vertices
Definition at line 76 of file SoFCIndexedFaceSet.cpp.
The documentation for this class was generated from the following file:
SoFCIndexedFaceSet.cpp