FreeCAD: MeshCore::MeshBuilder Class Reference
MeshCore::MeshBuilder Class Reference
#include <Builder.h>
Helper class
class MeshKernel
MeshBuilder (MeshKernel &kernel)
~MeshBuilder ()
MeshBuilder (const MeshBuilder &)=delete
MeshBuilder (MeshBuilder &&)=delete
MeshBuilder & operator= (const MeshBuilder &)=delete
MeshBuilder & operator= (MeshBuilder &&)=delete
void SetTolerance (float)
void Initialize (size_t ctFacets, bool deletion=true)
void AddFacet (const MeshGeomFacet &facet, bool takeFlag=false, bool takeProperty=false)
void AddFacet (const Base::Vector3f &pt1, const Base::Vector3f &pt2, const Base::Vector3f &pt3, const Base::Vector3f &normal, unsigned char flag=0, unsigned long prop=0)
void AddFacet (Base::Vector3f *facetPoints, unsigned char flag=0, unsigned long prop=0)
void Finish (bool freeMemory=false)
Detailed Description
Class for creating the mesh structure by adding facets. Building the structure needs 3 steps:
initializing
adding the facets
finishing
// Sample Code for building a mesh structure
MeshBuilder builder(someMeshReference);
builder.Initialize(numberOfFacets);
...
for (...)
  builder.AddFacet(...);
...
builder.Finish();
Author
Berthold Grupp
Definition at line 60 of file Builder.h.
Constructor & Destructor Documentation
MeshBuilder() [1/3]
MeshBuilder::MeshBuilder (MeshKernel & kernel) explicit
Definition at line 41 of file Builder.cpp.
References MeshCore::MeshDefinitions::_fMinPointDistanceD1.
~MeshBuilder()
MeshBuilder::~MeshBuilder ()
Definition at line 46 of file Builder.cpp.
References MeshCore::MeshDefinitions::_fMinPointDistanceD1.
MeshBuilder() [2/3]
MeshCore::MeshBuilder::MeshBuilder (const MeshBuilder &) delete
MeshBuilder() [3/3]
MeshCore::MeshBuilder::MeshBuilder (MeshBuilder &&) delete
Member Function Documentation
AddFacet() [1/3]
void MeshBuilder::AddFacet (Base::Vector3f * facetPoints, unsigned char flag = 0, unsigned long prop = 0)
Add new facet
Parameters
facetPoints Array of vectors (size 4) in order of vec1, vec2, vec3, normal
flag
prop
Definition at line 129 of file Builder.cpp.
References MeshCore::MeshFacet::_aulPoints, MeshCore::MeshFacet::_ucFlag, MeshCore::MeshPoint::_ulProp, MeshCore::MeshFacet::_ulProp, SplineSurface::i, Base::SequencerLauncher::next(), and buildPsets::p.
AddFacet() [2/3]
void MeshBuilder::AddFacet (const Base::Vector3f & pt1, const Base::Vector3f & pt2, const Base::Vector3f & pt3, const Base::Vector3f & normal, unsigned char flag = 0, unsigned long prop = 0)
Add new facet
Definition at line 118 of file Builder.cpp.
References AddFacet().
AddFacet() [3/3]
void MeshBuilder::AddFacet (const MeshGeomFacet & facet, bool takeFlag = false, bool takeProperty = false)
adding facets Add new facet
Parameters
facet the facet
takeFlag if true the flag from the MeshGeomFacet will be taken
takeProperty
Definition at line 99 of file Builder.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, MeshCore::MeshGeomFacet::_ucFlag, MeshCore::MeshGeomFacet::_ulProp, and MeshCore::MeshGeomFacet::GetNormal().
Referenced by AddFacet(), and MeshCore::MeshKernel::operator=().
Finish()
void MeshBuilder::Finish (bool freeMemory = false)
Finishes building up the mesh structure. Must be done after adding facets.
Parameters
freeMemory if false (default) only the memory of internal structures gets freed, otherwise additional unneeded memory in the mesh structure is tried to be freed.
Remarks
If you have called AddFacet() as many times as specified in Initialize() then absolutely no memory is wasted and you can leave the default value.
Definition at line 230 of file Builder.cpp.
References Mesh2Shape::faces, SplineSurface::i, and MeshCore::MeshKernel::RecalcBoundBox().
Referenced by MeshCore::MeshKernel::operator=().
Initialize()
void MeshBuilder::Initialize (size_t ctFacets, bool deletion = true)
Initializes the class. Must be done before adding facets
Parameters
ctFacets count of facets.
deletion if true (default) the mesh-kernel will be cleared otherwise you can add new facets on an existing mesh-kernel
Remarks
To be efficient you should add exactly ctFacets with AddFacet(), otherwise you'll possibly run into wastage of memory and performance problems.
Definition at line 57 of file Builder.cpp.
References MeshCore::MeshKernel::Clear().
Referenced by MeshCore::MeshKernel::operator=().
operator=() [1/2]
MeshBuilder& MeshCore::MeshBuilder::operator= (const MeshBuilder &) delete
operator=() [2/2]
MeshBuilder& MeshCore::MeshBuilder::operator= (MeshBuilder &&) delete
SetTolerance()
void MeshBuilder::SetTolerance (float fTol)
Set the tolerance for the comparison of points. Normally you don't need to set the tolerance.
Definition at line 52 of file Builder.cpp.
References MeshCore::MeshDefinitions::_fMinPointDistanceD1.
Friends And Related Function Documentation
MeshKernel
friend class MeshKernel friend
Definition at line 173 of file Builder.h.
The documentation for this class was generated from the following files:
Builder.h
Builder.cpp