FreeCAD: AppMeshGui.cpp File Reference
AppMeshGui.cpp File Reference
#include "PreCompiled.h"
#include <Inventor/SoDB.h>
#include <Inventor/SoInput.h>
#include <Inventor/annex/ForeignFiles/SoSTLFileKit.h>
#include <Inventor/nodes/SoSeparator.h>
#include <QApplication>
#include <Base/Console.h>
#include <Base/Interpreter.h>
#include <Base/PyObjectBase.h>
#include <Gui/Application.h>
#include <Gui/BitmapFactory.h>
#include <Gui/Language/Translator.h>
#include <Gui/WidgetFactory.h>
#include "DlgEvaluateMeshImp.h"
#include "DlgSettingsImportExportImp.h"
#include "DlgSettingsMeshView.h"
#include "PropertyEditorMesh.h"
#include "SoFCIndexedFaceSet.h"
#include "SoFCMeshObject.h"
#include "SoPolygon.h"
#include "ThumbnailExtension.h"
#include "ViewProvider.h"
#include "ViewProviderCurvature.h"
#include "ViewProviderDefects.h"
#include "ViewProviderMeshFaceSet.h"
#include "ViewProviderPython.h"
#include "ViewProviderTransform.h"
#include "ViewProviderTransformDemolding.h"
#include "Workbench.h"
Classes
class MeshGui::Module
Namespaces
MeshGui
The namespace of the Mesh Graphical interface layer library.
Functions
void CreateMeshCommands ()
void loadMeshResource ()
PyObject * MeshGui::initModule ()
PyMOD_INIT_FUNC (MeshGui)
Function Documentation
CreateMeshCommands()
void CreateMeshCommands ()
Definition at line 1836 of file Mod/Mesh/Gui/Command.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
loadMeshResource()
void loadMeshResource ()
Definition at line 62 of file AppMeshGui.cpp.
References Gui::Translator::instance(), and Gui::Translator::refresh().
Referenced by PyMOD_INIT_FUNC().
PyMOD_INIT_FUNC()
PyMOD_INIT_FUNC (MeshGui)
Definition at line 122 of file AppMeshGui.cpp.
References Gui::ViewProviderBuilder::add(), Mesh::Extension3MFFactory::addProducer(), Base::Console(), CreateMeshCommands(), SCL.SimpleDataTypes::e, Base::Persistence::getClassTypeId(), SIM::Coin3D::Quarter::Quarter::init(), Base::Persistence::init(), Gui::PropertyEditor::PropertyItem::init(), Base::BaseClass::init(), MeshGui::SoFCMeshObjectElement::initClass(), MeshGui::SoFCMaterialEngine::initClass(), MeshGui::SoPolygon::initClass(), MeshGui::SoFCMeshPickNode::initClass(), MeshGui::SoFCIndexedFaceSet::initClass(), MeshGui::SoFCMeshGridNode::initClass(), MeshGui::SoFCMeshObjectNode::initClass(), MeshGui::SoFCMeshObjectShape::initClass(), MeshGui::SoFCMeshSegmentShape::initClass(), MeshGui::SoFCMeshObjectBoundary::initClass(), MeshGui::initModule(), Gui::Application::Instance, Base::Interpreter(), loadMeshResource(), Base::InterpreterSingleton::loadModule(), Base::ConsoleSingleton::Log(), mod, PyMOD_Return, Arch::QT_TRANSLATE_NOOP, Base::PyException::ReportException(), and Base::InterpreterSingleton::runString().