FreeCAD: SpreadsheetGui::SheetView Class Reference
SpreadsheetGui::SheetView Class Reference
#include <SpreadsheetView.h>
Public Member Functions
SheetView (Gui::Document *pcDocument, App::DocumentObject *docObj, QWidget *parent)
~SheetView () override
const char * getName () const override
returns the name of the view (important for messages)
bool onMsg (const char *pMsg, const char **ppReturn) override
Message handler.
bool onHasMsg (const char *pMsg) const override
Message handler test.
Public Member Functions inherited from Gui::MDIView
MDIView (Gui::Document *pcDocument, QWidget *parent, Qt::WindowFlags wflags=Qt::WindowFlags())
~MDIView () override
void onRelabel (Gui::Document *pDoc) override
get called when the document is updated
virtual void viewAll ()
QString buildWindowTitle () const
build window title
bool canClose () override
overwrite when checking on close state
void savePrinterSettings (QPrinter *printer)
void restorePrinterSettings (QPrinter *printer)
virtual QStringList undoActions () const
virtual QStringList redoActions () const
QSize minimumSizeHint () const override
virtual void setCurrentViewMode (ViewMode mode)
ViewMode currentViewMode () const
template<typename _T >
_T getActiveObject (const char *name, App::DocumentObject **parent=nullptr, std::string *subname=nullptr) const
access getter for the active object list
void setActiveObject (App::DocumentObject *o, const char *n, const char *subname=nullptr)
bool hasActiveObject (const char *n) const
bool isActiveObject (App::DocumentObject *o, const char *n, const char *subname=nullptr) const
virtual bool containsViewProvider (const ViewProvider *) const
containsViewProvider Checks if the given view provider is part of this view. The default implementation returns false.
Public Member Functions inherited from Gui::BaseView
BaseView (Gui::Document *pcDocument=nullptr)
~BaseView () override
void setDocument (Gui::Document *pcDocument)
sets the view to another document (called by Application)
void onClose ()
is sent from the document in order to close the document
Gui::Document * getGuiDocument () const
returns the document the view is attached to
App::Document * getAppDocument () const
returns the document the view is attached to
bool isPassive () const
indicates if the view is in passive mode
virtual void onUpdate ()
get called when the document is updated
virtual void onRename (Gui::Document *)
get called when the document is renamed (change of its internal name)
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Printing
Ui::Sheet * ui
Spreadsheet::Sheet * sheet
SpreadsheetDelegate * delegate
SheetModel * model
boost::signals2::scoped_connection columnWidthChangedConnection
boost::signals2::scoped_connection rowHeightChangedConnection
boost::signals2::scoped_connection positionChangedConnection
std::map< int, int > newColumnSizes
std::map< int, int > newRowSizes
void print () override
void printPdf () override
void printPreview () override
void print (QPrinter *) override
void updateCell (const App::Property *prop)
Spreadsheet::Sheet * getSheet ()
std::vector< App::Range > selectedRanges () const
QModelIndexList selectedIndexes () const
QModelIndexList selectedIndexesRaw () const
void select (App::CellAddress cell, QItemSelectionModel::SelectionFlags flags)
void select (App::CellAddress topLeft, App::CellAddress bottomRight, QItemSelectionModel::SelectionFlags flags)
QModelIndex currentIndex () const
void setCurrentIndex (App::CellAddress cell) const
void deleteSelection ()
PyObject * getPyObject () override
void deleteSelf () override
delete itself
void editingFinishedWithKey (int key, Qt::KeyboardModifiers modifiers)
void confirmAliasChanged (const QString &text)
void aliasChanged (const QString &text)
void confirmContentChanged (const QString &text)
void currentChanged (const QModelIndex &current, const QModelIndex &previous)
void columnResized (int col, int oldSize, int newSize)
void rowResized (int row, int oldSize, int newSize)
void columnResizeFinished ()
void rowResizeFinished ()
void modelUpdated (const QModelIndex &topLeft, const QModelIndex &bottomRight)
void updateContentLine ()
void updateAliasLine ()
void setCurrentCell (QString str)
void resizeColumn (int col, int newSize)
void resizeRow (int col, int newSize)
Additional Inherited Members
Public Types inherited from Gui::MDIView
enum ViewMode { Child, TopLevel, FullScreen }
MDI view mode enum.
Public Slots inherited from Gui::MDIView
virtual void setOverrideCursor (const QCursor &)
virtual void restoreOverrideCursor ()
Signals inherited from Gui::MDIView
void message (const QString &, int)
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Protected Slots inherited from Gui::MDIView
virtual void windowStateChanged (QWidget *)
Protected Member Functions inherited from Gui::MDIView
void closeEvent (QCloseEvent *e) override
void changeEvent (QEvent *e) override
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Gui::MDIView
PyObject * pythonObject
Protected Attributes inherited from Gui::BaseView
Gui::Document * _pcDocument
bool bIsDetached {false}
bool bIsPassive {false}
Detailed Description
Definition at line 59 of file SpreadsheetView.h.
Constructor & Destructor Documentation
SheetView()
SheetView::SheetView (Gui::Document * pcDocument, App::DocumentObject * docObj, QWidget * parent)
Definition at line 64 of file SpreadsheetView.cpp.
References aliasChanged(), draftgeoutils.faces::bind(), columnResized(), columnResizeFinished(), draftgeoutils.intersections::connect(), currentChanged(), editingFinishedWithKey(), SpreadsheetGui::SpreadsheetDelegate::finishedWithKey(), Gui::getMainWindow(), modelUpdated(), resizeColumn(), SpreadsheetGui::SheetViewHeader::resizeFinished(), resizeRow(), rowResized(), rowResizeFinished(), QtColorPicker::setCurrentColor(), and src.Mod.PartDesign.fcgear.svggear::w.
~SheetView()
SheetView::~SheetView () override
Definition at line 151 of file SpreadsheetView.cpp.
References Gui::Application::detachView(), and Gui::Application::Instance.
Member Function Documentation
aliasChanged
void SheetView::aliasChanged (const QString & text) protected slot
Definition at line 469 of file SpreadsheetView.cpp.
Referenced by SheetView().
columnResized
void SheetView::columnResized (int col, int oldSize, int newSize) protected slot
Definition at line 397 of file SpreadsheetView.cpp.
Referenced by SheetView().
columnResizeFinished
void SheetView::columnResizeFinished () protected slot
Definition at line 357 of file SpreadsheetView.cpp.
References TestSpreadsheet::v.
Referenced by SheetView().
confirmAliasChanged
void SheetView::confirmAliasChanged (const QString & text) protected slot
Definition at line 432 of file SpreadsheetView.cpp.
References Gui::cmdAppDocument(), Gui::cmdAppObjectArgs(), Base::Console(), Base::ConsoleSingleton::Error(), SplineSurface::i, and App::CellAddress::toString().
confirmContentChanged
void SheetView::confirmContentChanged (const QString & text) protected slot
Definition at line 462 of file SpreadsheetView.cpp.
References SplineSurface::i.
currentChanged
void SheetView::currentChanged (const QModelIndex & current, const QModelIndex & previous) protected slot
Definition at line 501 of file SpreadsheetView.cpp.
Referenced by SheetView().
currentIndex()
QModelIndex SheetView::currentIndex () const
Definition at line 569 of file SpreadsheetView.cpp.
Referenced by SpreadsheetGui::SheetViewPy::currentIndex().
deleteSelection()
void SheetView::deleteSelection ()
Definition at line 564 of file SpreadsheetView.cpp.
deleteSelf()
void SheetView::deleteSelf () override virtual
delete itself
Reimplemented from Gui::MDIView.
Definition at line 589 of file SpreadsheetView.cpp.
References Gui::MDIView::deleteSelf().
editingFinishedWithKey
void SheetView::editingFinishedWithKey (int key, Qt::KeyboardModifiers modifiers) protected slot
Definition at line 423 of file SpreadsheetView.cpp.
References SplineSurface::i.
Referenced by SheetView().
getName()
const char* SpreadsheetGui::SheetView::getName () const inline override virtual
returns the name of the view (important for messages)
Reimplemented from Gui::BaseView.
Definition at line 69 of file SpreadsheetView.h.
getPyObject()
PyObject * SheetView::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Gui::MDIView.
Definition at line 579 of file SpreadsheetView.cpp.
getSheet()
Spreadsheet::Sheet* SpreadsheetGui::SheetView::getSheet () inline
Definition at line 87 of file SpreadsheetView.h.
Referenced by SpreadsheetGui::WorkbenchHelper::setBackgroundColor(), and SpreadsheetGui::WorkbenchHelper::setForegroundColor().
modelUpdated
void SheetView::modelUpdated (const QModelIndex & topLeft, const QModelIndex & bottomRight) protected slot
Definition at line 385 of file SpreadsheetView.cpp.
Referenced by SheetView().
onHasMsg()
bool SheetView::onHasMsg (const char * pMsg) const override virtual
Message handler test.
Reimplemented from Gui::MDIView.
Definition at line 215 of file SpreadsheetView.cpp.
References toolbit-attributes::doc.
onMsg()
bool SheetView::onMsg (const char * pMsg, const char ** ppReturn) override virtual
Message handler.
receive a message
Reimplemented from Gui::MDIView.
Definition at line 159 of file SpreadsheetView.cpp.
References Gui::Command::commitCommand(), toolbit-attributes::doc, Gui::Command::Doc, doCommand, FCMD_OBJ_CMD, SplineSurface::i, Gui::Command::openCommand(), and Arch::QT_TRANSLATE_NOOP.
print() [1/2]
void SheetView::print () override virtual
Shows the printer dialog.
Reimplemented from Gui::MDIView.
Definition at line 259 of file SpreadsheetView.cpp.
Referenced by printPreview().
print() [2/2]
void SheetView::print (QPrinter * printer) override virtual
Reimplemented from Gui::MDIView.
Definition at line 282 of file SpreadsheetView.cpp.
printPdf()
void SheetView::printPdf () override virtual
Prints the document into a Pdf file.
Reimplemented from Gui::MDIView.
Definition at line 295 of file SpreadsheetView.cpp.
printPreview()
void SheetView::printPreview () override virtual
Show a preview dialog
Reimplemented from Gui::MDIView.
Definition at line 270 of file SpreadsheetView.cpp.
References draftgeoutils.intersections::connect(), and print().
resizeColumn()
void SheetView::resizeColumn (int col, int newSize) protected
Definition at line 409 of file SpreadsheetView.cpp.
Referenced by SheetView().
resizeRow()
void SheetView::resizeRow (int col, int newSize) protected
Definition at line 416 of file SpreadsheetView.cpp.
Referenced by SheetView().
rowResized
void SheetView::rowResized (int row, int oldSize, int newSize) protected slot
Definition at line 403 of file SpreadsheetView.cpp.
Referenced by SheetView().
rowResizeFinished
void SheetView::rowResizeFinished () protected slot
Definition at line 371 of file SpreadsheetView.cpp.
References TestSpreadsheet::v.
Referenced by SheetView().
select() [1/2]
void SpreadsheetGui::SheetView::select (App::CellAddress cell, QItemSelectionModel::SelectionFlags flags)
Definition at line 548 of file SpreadsheetView.cpp.
References App::CellAddress::col(), and App::CellAddress::row().
Referenced by SpreadsheetGui::SheetViewPy::select().
select() [2/2]
void SpreadsheetGui::SheetView::select (App::CellAddress topLeft, App::CellAddress bottomRight, QItemSelectionModel::SelectionFlags flags)
Definition at line 554 of file SpreadsheetView.cpp.
References App::CellAddress::col(), and App::CellAddress::row().
selectedIndexes()
QModelIndexList SheetView::selectedIndexes () const
Definition at line 538 of file SpreadsheetView.cpp.
Referenced by SpreadsheetGui::SheetViewPy::selectedCells().
selectedIndexesRaw()
QModelIndexList SheetView::selectedIndexesRaw () const
Definition at line 543 of file SpreadsheetView.cpp.
selectedRanges()
std::vector< Range > SheetView::selectedRanges () const
Definition at line 533 of file SpreadsheetView.cpp.
Referenced by SpreadsheetGui::SheetViewPy::selectedRanges(), SpreadsheetGui::WorkbenchHelper::setBackgroundColor(), and SpreadsheetGui::WorkbenchHelper::setForegroundColor().
setCurrentCell()
void SheetView::setCurrentCell (QString str) protected
Definition at line 314 of file SpreadsheetView.cpp.
References Path.Post.scripts.refactored_centroid_post::str.
setCurrentIndex()
void SpreadsheetGui::SheetView::setCurrentIndex (App::CellAddress cell) const
Definition at line 574 of file SpreadsheetView.cpp.
References App::CellAddress::col(), and App::CellAddress::row().
Referenced by src.Mod.AddonManager.Widgets.addonmanager_widget_filter_selector.WidgetFilterSelector::retranslateUi(), and SpreadsheetGui::SheetViewPy::setCurrentIndex().
updateAliasLine()
void SheetView::updateAliasLine () protected
Definition at line 339 of file SpreadsheetView.cpp.
References SplineSurface::i, and Path.Post.scripts.refactored_centroid_post::str.
updateCell()
void SheetView::updateCell (const App::Property * prop)
Definition at line 509 of file SpreadsheetView.cpp.
References App::CellAddress::col(), App::ExpressionParser::column, and App::CellAddress::row().
updateContentLine()
void SheetView::updateContentLine () protected
Definition at line 321 of file SpreadsheetView.cpp.
References SplineSurface::i, and Path.Post.scripts.refactored_centroid_post::str.
Member Data Documentation
columnWidthChangedConnection
boost::signals2::scoped_connection SpreadsheetGui::SheetView::columnWidthChangedConnection protected
Definition at line 136 of file SpreadsheetView.h.
delegate
SpreadsheetDelegate* SpreadsheetGui::SheetView::delegate protected
Definition at line 134 of file SpreadsheetView.h.
model
SheetModel* SpreadsheetGui::SheetView::model protected
Definition at line 135 of file SpreadsheetView.h.
Referenced by Path.Op.Pocket.ObjectPocket::areaOpShapes(), Path.Op.Vcarve.ObjectVcarve::buildCommandList(), Path.Op.Engrave.ObjectEngrave::opExecute(), Path.Op.Vcarve.ObjectVcarve::opExecute(), Path.Op.Deburr.ObjectDeburr::opRejectAddBase(), src.Mod.AddonManager.Widgets.addonmanager_widget_filter_selector.WidgetFilterSelector::retranslateUi(), src.Mod.AddonManager.Widgets.addonmanager_widget_filter_selector.WidgetFilterSelector::set_contents_filter(), and src.Mod.AddonManager.Widgets.addonmanager_widget_filter_selector.WidgetFilterSelector::set_status_filter().
newColumnSizes
std::map<int, int> SpreadsheetGui::SheetView::newColumnSizes protected
Definition at line 140 of file SpreadsheetView.h.
newRowSizes
std::map<int, int> SpreadsheetGui::SheetView::newRowSizes protected
Definition at line 141 of file SpreadsheetView.h.
positionChangedConnection
boost::signals2::scoped_connection SpreadsheetGui::SheetView::positionChangedConnection protected
Definition at line 138 of file SpreadsheetView.h.
rowHeightChangedConnection
boost::signals2::scoped_connection SpreadsheetGui::SheetView::rowHeightChangedConnection protected
Definition at line 137 of file SpreadsheetView.h.
sheet
Spreadsheet::Sheet* SpreadsheetGui::SheetView::sheet protected
Definition at line 133 of file SpreadsheetView.h.
Referenced by TestSpreadsheetGui.SpreadsheetGuiCases::testCopySingleCell().
ui
Ui::Sheet* SpreadsheetGui::SheetView::ui protected
Definition at line 132 of file SpreadsheetView.h.
Referenced by DraftGui.DraftToolBar::changeEvent().
The documentation for this class was generated from the following files:
SpreadsheetView.h
SpreadsheetView.cpp