FreeCAD: Part::TopoShapeCache::Ancestry Class Reference
Part::TopoShapeCache::Ancestry Class Reference
Class for caching the ancestor and children shapes mapping.
#include <TopoShapeCache.h>
Public Member Functions
void clear ()
TopoShape getTopoShape (const TopoShape &parent, int index)
std::vector< TopoShape > getTopoShapes (const TopoShape &parent)
TopoDS_Shape stripLocation (const TopoDS_Shape &parent, const TopoDS_Shape &child)
int find (const TopoDS_Shape &parent, const TopoDS_Shape &subShape)
TopoDS_Shape find (const TopoDS_Shape &parent, int index)
int count () const
Public Attributes
friend TopoShapeCache
Detailed Description
Class for caching the ancestor and children shapes mapping.
Definition at line 110 of file TopoShapeCache.h.
Member Function Documentation
clear()
void TopoShapeCache::Ancestry::clear ()
Definition at line 93 of file TopoShapeCache.cpp.
Referenced by src.Mod.Test.Document.DocumentObserverCases.Observer::__init__(), and src.Mod.Test.Document.DocumentObserverCases.GuiObserver::__init__().
count()
int TopoShapeCache::Ancestry::count () const
Definition at line 149 of file TopoShapeCache.cpp.
Referenced by Part::TopoShapeCache::countShape(), and src.Mod.AddonManager.Widgets.addonmanager_widget_filter_selector.WidgetFilterSelector::set_status_filter().
find() [1/2]
int TopoShapeCache::Ancestry::find (const TopoDS_Shape & parent, const TopoDS_Shape & subShape)
Definition at line 130 of file TopoShapeCache.cpp.
References Init::parent.
Referenced by Part::TopoShapeCache::findShape().
find() [2/2]
TopoDS_Shape TopoShapeCache::Ancestry::find (const TopoDS_Shape & parent, int index)
Definition at line 138 of file TopoShapeCache.cpp.
References Part::TopoShape::moved(), and Init::parent.
getTopoShape()
TopoShape TopoShapeCache::Ancestry::getTopoShape (const TopoShape & parent, int index)
Definition at line 98 of file TopoShapeCache.cpp.
References _getTopoShape(), and Init::parent.
getTopoShapes()
std::vector< TopoShape > TopoShapeCache::Ancestry::getTopoShapes (const TopoShape & parent)
Definition at line 108 of file TopoShapeCache.cpp.
References _getTopoShape(), src.Mod.AddonManager.NetworkManager::count, SplineSurface::i, and Init::parent.
stripLocation()
TopoDS_Shape TopoShapeCache::Ancestry::stripLocation (const TopoDS_Shape & parent, const TopoDS_Shape & child)
Definition at line 120 of file TopoShapeCache.cpp.
References Part::TopoShape::located(), and Init::parent.
Member Data Documentation
TopoShapeCache
friend Part::TopoShapeCache::Ancestry::TopoShapeCache
Definition at line 139 of file TopoShapeCache.h.
The documentation for this class was generated from the following files:
TopoShapeCache.h
TopoShapeCache.cpp