FreeCAD: AppDrawing.cpp File Reference
AppDrawing.cpp File Reference
#include "PreCompiled.h"
#include <Base/Console.h>
#include <Base/Interpreter.h>
#include <Base/PyObjectBase.h>
#include "FeatureClip.h"
#include "FeaturePage.h"
#include "FeatureProjection.h"
#include "FeatureView.h"
#include "FeatureViewAnnotation.h"
#include "FeatureViewPart.h"
#include "FeatureViewSpreadsheet.h"
#include "FeatureViewSymbol.h"
#include "PageGroup.h"
Namespaces
Drawing
Functions
PyObject * Drawing::initModule ()
PyMOD_INIT_FUNC (Drawing)
Function Documentation
PyMOD_INIT_FUNC()
PyMOD_INIT_FUNC (Drawing)
Definition at line 35 of file AppDrawing.cpp.
References Base::Console(), SCL.SimpleDataTypes::e, SIM::Coin3D::Quarter::Quarter::init(), App::DocumentObjectExtension::init(), Base::Persistence::init(), Drawing::initModule(), Base::Interpreter(), Base::InterpreterSingleton::loadModule(), Base::ConsoleSingleton::Log(), mod, and PyMOD_Return.