FreeCAD: PartGui::GridExtensionP Class Reference
PartGui::GridExtensionP Class Reference
Public Member Functions
GridExtensionP (ViewProviderGridExtension *)
~GridExtensionP ()
void drawGrid (bool cameraUpdate=false)
void setEnabled (bool enable)
bool getEnabled ()
SoSeparator * getGridRoot ()
void getClosestGridPoint (double &x, double &y) const
double getGridSize () const
void setGridOrientation (Base::Vector3d origin, Base::Rotation rotation)
Public Attributes
int GridSizePixelThreshold = 15
int GridNumberSubdivision = 10
int GridLinePattern = 0x0f0f
int GridDivLinePattern = 0xffff
int GridLineWidth = 1
int GridDivLineWidth = 2
unsigned int GridLineColor
unsigned int GridDivLineColor
Detailed Description
Definition at line 67 of file ViewProviderGridExtension.cpp.
Constructor & Destructor Documentation
GridExtensionP()
GridExtensionP::GridExtensionP (ViewProviderGridExtension * vp) explicit
Definition at line 127 of file ViewProviderGridExtension.cpp.
References SCL.SimpleDataTypes::f, GridDivLineColor, and GridLineColor.
~GridExtensionP()
GridExtensionP::~GridExtensionP ()
Definition at line 140 of file ViewProviderGridExtension.cpp.
References Gui::coinRemoveAllChildren().
Member Function Documentation
drawGrid()
void GridExtensionP::drawGrid (bool cameraUpdate = false)
Definition at line 413 of file ViewProviderGridExtension.cpp.
References Gui::coinRemoveAllChildren(), App::PropertyBool::getValue(), and PartGui::ViewProviderGridExtension::ShowGrid.
Referenced by setEnabled().
getClosestGridPoint()
void GridExtensionP::getClosestGridPoint (double & x, double & y) const
Definition at line 157 of file ViewProviderGridExtension.cpp.
References MovieTool::x, and MovieTool::y.
getEnabled()
bool GridExtensionP::getEnabled ()
Definition at line 394 of file ViewProviderGridExtension.cpp.
getGridRoot()
SoSeparator * GridExtensionP::getGridRoot ()
Definition at line 408 of file ViewProviderGridExtension.cpp.
getGridSize()
double GridExtensionP::getGridSize () const
Definition at line 152 of file ViewProviderGridExtension.cpp.
setEnabled()
void GridExtensionP::setEnabled (bool enable)
Definition at line 386 of file ViewProviderGridExtension.cpp.
References drawGrid().
setGridOrientation()
void GridExtensionP::setGridOrientation (Base::Vector3d origin, Base::Rotation rotation)
Definition at line 146 of file ViewProviderGridExtension.cpp.
Member Data Documentation
GridDivLineColor
unsigned int PartGui::GridExtensionP::GridDivLineColor
Definition at line 92 of file ViewProviderGridExtension.cpp.
Referenced by GridExtensionP().
GridDivLinePattern
int PartGui::GridExtensionP::GridDivLinePattern = 0xffff
Definition at line 88 of file ViewProviderGridExtension.cpp.
GridDivLineWidth
int PartGui::GridExtensionP::GridDivLineWidth = 2
Definition at line 90 of file ViewProviderGridExtension.cpp.
GridLineColor
unsigned int PartGui::GridExtensionP::GridLineColor
Definition at line 91 of file ViewProviderGridExtension.cpp.
Referenced by GridExtensionP().
GridLinePattern
int PartGui::GridExtensionP::GridLinePattern = 0x0f0f
Definition at line 87 of file ViewProviderGridExtension.cpp.
GridLineWidth
int PartGui::GridExtensionP::GridLineWidth = 1
Definition at line 89 of file ViewProviderGridExtension.cpp.
GridNumberSubdivision
int PartGui::GridExtensionP::GridNumberSubdivision = 10
Definition at line 86 of file ViewProviderGridExtension.cpp.
GridSizePixelThreshold
int PartGui::GridExtensionP::GridSizePixelThreshold = 15
Definition at line 85 of file ViewProviderGridExtension.cpp.
The documentation for this class was generated from the following file:
ViewProviderGridExtension.cpp