FreeCAD: nativeifc.ifc_psets Namespace Reference
nativeifc.ifc_psets Namespace Reference
Functions
def has_psets (obj)
def get_psets (element)
def get_pset (psetname, element)
def show_psets (obj)
def edit_pset (obj, prop, value=None, force=False, ifcfile=None, element=None)
def load_psets (obj)
def add_pset (obj, psetname)
def add_property (ifcfile, pset, name, value="")
def get_freecad_type (ptype)
def get_ifc_type (fctype)
def read_properties_conversion ()
def remove_property (obj, prop)
Variables
translate = FreeCAD.Qt.translate
Function Documentation
add_property()
def nativeifc.ifc_psets.add_property (ifcfile, pset, name, value = "")
Adds a property with the given name to the given pset. The type is deduced from
the value: string is IfcLabel, True/False is IfcBoolean, number is IfcLengthMeasure.
To force a certain type, value can also be an IFC element such as IfcLabel
Definition at line 317 of file ifc_psets.py.
add_pset()
def nativeifc.ifc_psets.add_pset (obj, psetname)
Adds a pset with the given name to the given object
Definition at line 305 of file ifc_psets.py.
edit_pset()
def nativeifc.ifc_psets.edit_pset (obj, prop, value = None, force = False, ifcfile = None, element = None)
Edits the corresponding property. If force is True,
the property is created even if it has no value
Definition at line 171 of file ifc_psets.py.
References nativeifc.ifc_psets.get_pset(), nativeifc.ifc_psets.get_psets(), Path.Post.scripts.refactored_centroid_post.str, and Path.Post.scripts.grbl_post.type.
get_freecad_type()
def nativeifc.ifc_psets.get_freecad_type (ptype)
Returns a FreeCAD property type corresponding to an IFC property type
Definition at line 325 of file ifc_psets.py.
References nativeifc.ifc_psets.read_properties_conversion().
get_ifc_type()
def nativeifc.ifc_psets.get_ifc_type (fctype)
Returns an IFC property type corresponding to a FreeCAD property type
Definition at line 335 of file ifc_psets.py.
References nativeifc.ifc_psets.read_properties_conversion().
get_pset()
def nativeifc.ifc_psets.get_pset (psetname, element)
Returns an IfcPropertySet with the given name
Definition at line 77 of file ifc_psets.py.
Referenced by nativeifc.ifc_psets.edit_pset(), and nativeifc.ifc_psets.remove_property().
get_psets()
def nativeifc.ifc_psets.get_psets (element)
Returns a dictionary of dictionaries representing the
properties of an element in the form:
{ pset_name : { property_name : IfcType(value), ... }, ... }
Definition at line 48 of file ifc_psets.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by nativeifc.ifc_psets.edit_pset(), nativeifc.ifc_psets.remove_property(), and nativeifc.ifc_psets.show_psets().
has_psets()
def nativeifc.ifc_psets.has_psets (obj)
Returns True if an object has attached psets
Definition at line 34 of file ifc_psets.py.
load_psets()
def nativeifc.ifc_psets.load_psets (obj)
Recursively loads psets of child objects
Definition at line 293 of file ifc_psets.py.
References nativeifc.ifc_psets.show_psets().
read_properties_conversion()
def nativeifc.ifc_psets.read_properties_conversion ()
Reads the properties conversion table
Definition at line 345 of file ifc_psets.py.
References AssemblyImport.open().
Referenced by nativeifc.ifc_psets.get_freecad_type(), and nativeifc.ifc_psets.get_ifc_type().
remove_property()
def nativeifc.ifc_psets.remove_property (obj, prop)
Removes a custom property
Definition at line 361 of file ifc_psets.py.
References nativeifc.ifc_psets.get_pset(), and nativeifc.ifc_psets.get_psets().
show_psets()
def nativeifc.ifc_psets.show_psets (obj)
Shows the psets attached to the given object as properties
Definition at line 89 of file ifc_psets.py.
References nativeifc.ifc_psets.get_psets().
Referenced by nativeifc.ifc_psets.load_psets().
Variable Documentation
translate
nativeifc.ifc_psets.translate = FreeCAD.Qt.translate
Definition at line 31 of file ifc_psets.py.