FreeCAD: MeshCore::MeshEvalRangePoint Class Reference
MeshCore::MeshEvalRangePoint Class Reference
#include <Degeneration.h>
Public Member Functions
MeshEvalRangePoint (const MeshKernel &rclM)
bool Evaluate () override
std::vector< PointIndex > GetIndices () const
Public Member Functions inherited from MeshCore::MeshEvaluation
MeshEvaluation (const MeshKernel &rclB)
virtual ~MeshEvaluation ()=default
MeshEvaluation (const MeshEvaluation &)=delete
MeshEvaluation (MeshEvaluation &&)=delete
MeshEvaluation & operator= (const MeshEvaluation &)=delete
MeshEvaluation & operator= (MeshEvaluation &&)=delete
Additional Inherited Members
Protected Attributes inherited from MeshCore::MeshEvaluation
const MeshKernel & _rclMesh
Detailed Description
The MeshEvalRangePoint class searches for facets that has point indices out of range.
See also
MeshFixRangePoint
Author
Werner Mayer
Definition at line 666 of file Degeneration.h.
Constructor & Destructor Documentation
MeshEvalRangePoint()
MeshCore::MeshEvalRangePoint::MeshEvalRangePoint (const MeshKernel & rclM) inline explicit
Construction.
Definition at line 672 of file Degeneration.h.
Member Function Documentation
Evaluate()
bool MeshEvalRangePoint::Evaluate () override virtual
Searches for facets that has point indices out of range.
Implements MeshCore::MeshEvaluation.
Definition at line 1111 of file Degeneration.cpp.
References MeshCore::MeshEvaluation::_rclMesh, MeshCore::MeshKernel::CountPoints(), MeshCore::MeshKernel::GetFacets(), and SplineSurface::i.
Referenced by Mesh::MeshObject::hasPointsOutOfRange(), and Mesh::MeshObject::validateIndices().
GetIndices()
std::vector< PointIndex > MeshEvalRangePoint::GetIndices () const
Returns the indices of all facets with invalid point indices.
Definition at line 1130 of file Degeneration.cpp.
References MeshCore::MeshEvaluation::_rclMesh, MeshCore::MeshKernel::CountPoints(), MeshCore::MeshKernel::GetFacets(), and SplineSurface::i.
Referenced by MeshCore::MeshFixRangePoint::Fixup().
The documentation for this class was generated from the following files:
Degeneration.h
Degeneration.cpp