FreeCAD: draftutils
draftutils
DRAFT
Utility modules that are used throughout the workbench.
Namespaces
groups
Provides utility functions to do operations with groups.
gui_utils
Provides utility functions that deal with GUI interactions.
init_draft_statusbar
Provides the initialization code for the workbench's status bar.
init_tools
Provides lists of commands to set up toolbars of the workbench.
messages
Provides utility functions that wrap around the Console methods.
todo
Provides the ToDo static class to run commands with a time delay.
translate
Provides utility functions that wrap around the Qt translate function.
units
Provides utility functions to handle quantities and units.
utils
Provides general utility functions used throughout the workbench.
Classes
class draftutils.todo.ToDo
Functions
def draftutils.groups.is_group (obj)
def draftutils.groups.get_group_names (doc=None)
def draftutils.groups.getGroupNames ()
def draftutils.groups.ungroup (obj)
def draftutils.groups.get_windows (obj)
def draftutils.groups.get_group_contents (objectslist, walls=False, addgroups=False, spaces=False, noarchchild=False)
def draftutils.groups.getGroupContents (objectslist, walls=False, addgroups=False, spaces=False, noarchchild=False)
def draftutils.groups.get_movable_children (objectslist, recursive=True, _donelist=[])
def draftutils.groups.getMovableChildren (objectslist, recursive=True)
def draftutils.gui_utils.get_3d_view ()
def draftutils.gui_utils.autogroup (obj)
def draftutils.gui_utils.dim_symbol (symbol=None, invert=False)
def draftutils.gui_utils.dim_dash (p1, p2)
def draftutils.gui_utils.remove_hidden (objectslist)
def draftutils.gui_utils.get_diffuse_color (objs)
def draftutils.gui_utils.apply_current_style (objs)
def draftutils.gui_utils.restore_view_object (obj, vp_module, vp_class, format=True, format_ref=None)
def draftutils.gui_utils.format_object (target, origin=None)
def draftutils.gui_utils.get_selection (gui=App.GuiUp)
def draftutils.gui_utils.get_selection_ex (gui=App.GuiUp)
def draftutils.gui_utils.select (objs=None, gui=App.GuiUp)
def draftutils.gui_utils.load_texture (filename, size=None, gui=App.GuiUp)
def draftutils.gui_utils.migrate_text_display_mode (obj_type="Text", mode="3D text", doc=None)
def draftutils.gui_utils.get_bbox (obj, debug=False)
def draftutils.gui_utils.find_coin_node (parent, nodetype)
def draftutils.gui_utils.end_all_events ()
def draftutils.init_draft_statusbar.get_scales (unit_system=0)
def draftutils.init_draft_statusbar.scale_to_label (scale)
def draftutils.init_draft_statusbar.label_to_scale (label)
def draftutils.init_draft_statusbar.init_draft_statusbar_scale ()
def draftutils.init_draft_statusbar.init_draft_statusbar_snap ()
def draftutils.init_draft_statusbar.show_draft_statusbar ()
def draftutils.init_draft_statusbar.hide_draft_statusbar ()
def draftutils.init_tools.get_draft_drawing_commands ()
def draftutils.init_tools.get_draft_annotation_commands ()
def draftutils.init_tools.get_draft_modification_commands ()
def draftutils.init_tools.get_draft_utility_commands_menu ()
def draftutils.init_tools.get_draft_utility_commands_toolbar ()
def draftutils.init_tools.get_draft_snap_commands ()
def draftutils.init_tools.get_draft_context_commands ()
def draftutils.init_tools.init_toolbar (workbench, toolbar, cmd_list)
def draftutils.init_tools.init_menu (workbench, menu_list, cmd_list)
def draftutils.translate.translate (context, text, comment=None)
def draftutils.units.get_default_unit (dim)
def draftutils.units.make_format_spec (decimals=4, dim='Length')
def draftutils.units.display_external (internal_value, decimals=None, dim='Length', showUnit=True, unit=None)
def draftutils.utils.get_default_annotation_style ()
def draftutils.utils.get_default_shape_style ()
def draftutils.utils.get_view_material ()
def draftutils.utils.string_encode_coin (ustr)
def draftutils.utils.type_check (args_and_types, name="?")
def draftutils.utils.get_param_type (param)
def draftutils.utils.get_param (param, default=None)
def draftutils.utils.set_param (param, value)
def draftutils.utils.precision ()
def draftutils.utils.tolerance ()
def draftutils.utils.get_real_name (name)
def draftutils.utils.get_type (obj)
def draftutils.utils.get_objects_of_type (objects, typ)
def draftutils.utils.is_clone (obj, objtype=None, recursive=False)
def draftutils.utils.get_clone_base (obj, strict=False, recursive=True)
def draftutils.utils.shapify (obj)
def draftutils.utils.print_shape (shape)
def draftutils.utils.compare_objects (obj1, obj2)
def draftutils.utils.load_svg_patterns ()
def draftutils.utils.svg_patterns ()
def draftutils.utils.get_rgb (color, testbw=True)
def draftutils.utils.argb_to_rgba (color)
def draftutils.utils.rgba_to_argb (color)
def draftutils.utils.get_rgba_tuple (color, typ=1.0)
def draftutils.utils.filter_objects_for_modifiers (objects, isCopied=False)
def draftutils.utils.is_closed_edge (edge_index, object)
def draftutils.utils.utf8_decode (text)
def draftutils.utils.print_header (name, description, debug=True)
def draftutils.utils.find_doc (doc=None)
def draftutils.utils.find_object (obj, doc=None)
def draftutils.utils.use_instead (function, version="")
Variables
draftutils.gui_utils.get3DView
draftutils.gui_utils.dimSymbol
draftutils.gui_utils.dimDash
draftutils.gui_utils.removeHidden
draftutils.gui_utils.formatObject
draftutils.gui_utils.getSelection
draftutils.gui_utils.getSelectionEx
draftutils.gui_utils.loadTexture
draftutils.init_draft_statusbar.draft_scales_metrics
draftutils.init_draft_statusbar.draft_scales_arch_imperial
draftutils.init_draft_statusbar.draft_scales_eng_imperial
draftutils.todo.todo
draftutils.translate.Qtranslate
draftutils.translate.QT_TRANSLATE_NOOP
draftutils.units.getDefaultUnit
draftutils.units.makeFormatSpec
draftutils.units.displayExternal
draftutils.utils.ARROW_TYPES
draftutils.utils.DISPLAY_MODES
draftutils.utils.DRAW_STYLES
draftutils.utils.arrowtypes
draftutils.utils.stringencodecoin
draftutils.utils.typecheck
draftutils.utils.getParamType
draftutils.utils.getParam
draftutils.utils.setParam
draftutils.utils.getRealName
draftutils.utils.getType
draftutils.utils.getObjectsOfType
draftutils.utils.isClone
draftutils.utils.getCloneBase
draftutils.utils.printShape
draftutils.utils.compareObjects
draftutils.utils.loadSvgPatterns
draftutils.utils.svgpatterns
draftutils.utils.getrgb
Detailed Description
Utility modules that are used throughout the workbench.
Function Documentation
apply_current_style()
def draftutils.gui_utils.apply_current_style (objs)
Apply the current style to one or more objects.
Parameters
----------
objs: a single object or an iterable with objects.
Definition at line 443 of file gui_utils.py.
argb_to_rgba()
def draftutils.utils.argb_to_rgba (color)
Change byte order of a 4 byte color int from ARGB (Qt) to RGBA (FreeCAD).
Alpha in both integers is always 255.
Alpha in color properties, although ignored, is always zero however.
Usage:
    qt_int = self.form.ShapeColor.property("color").rgba() # Note: returns ARGB int
    qt_int = self.form.ShapeColor.property("color").rgb()  # Note: returns ARGB int
    fc_int = argb_to_rgba(qt_int)
    FreeCAD.ParamGet("User parameter:BaseApp/Preferences/View")\
        .SetUnsigned("DefaultShapeColor", fc_int)
    obj.ViewObject.ShapeColor = fc_int & 0xFFFFFF00
Related:
    getRgbF() returns an RGBA tuple. 4 floats in the range 0.0 - 1.0. Alpha is always 1.
    Alpha should be set to zero or removed before using the tuple to change a color property:
    obj.ViewObject.ShapeColor = self.form.ShapeColor.property("color").getRgbF()[:3]
Definition at line 833 of file utils.py.
autogroup()
def draftutils.gui_utils.autogroup (obj)
Add a given object to the defined Draft autogroup, if applicable.
This function only works if the graphical interface is available.
It checks that the `App.draftToolBar` class is available,
which contains the group to use to automatically store
new created objects.
Originally, it worked with standard groups (`App::DocumentObjectGroup`),
and Arch Workbench containers like `'Site'`, `'Building'`, `'Floor'`,
and `'BuildingPart'`.
Now it works with Draft Layers.
Parameters
----------
obj: App::DocumentObject
    Any type of object that will be stored in the group.
Definition at line 85 of file gui_utils.py.
compare_objects()
def draftutils.utils.compare_objects (obj1, obj2)
Print the differences between 2 objects.
The two objects are compared through their `TypeId` attribute,
or by using the `get_type` function.
If they are the same type their properties are compared
looking for differences.
Neither `Shape` nor `Label` attributes are compared.
Parameters
----------
obj1 : App::DocumentObject
    Any type of scripted object.
obj2 : App::DocumentObject
    Any type of scripted object.
Definition at line 687 of file utils.py.
References draftutils.utils.get_type(), draftutils.utils.getType, and Path.Post.scripts.refactored_centroid_post.str.
dim_dash()
def draftutils.gui_utils.dim_dash (p1, p2)
Return a SoSeparator with a line used to make dimension dashes.
It is used by `dim_symbol` to create line end symbols
like `'Tick-2'`, `'DimOvershoot'`, and `'ExtOvershoot'` dashes.
Parameters
----------
p1: tuple of three floats or Base::Vector3
    A point to define a line vertex.
p2: tuple of three floats or Base::Vector3
    A point to define a line vertex.
Returns
-------
Coin.SoSeparator
    A Coin object with a `SoLineSet` created from `p1` and `p2`
    as vertices.
Definition at line 278 of file gui_utils.py.
Referenced by draftutils.gui_utils.dim_symbol().
dim_symbol()
def draftutils.gui_utils.dim_symbol (symbol = None, invert = False)
Return the specified dimension symbol.
Parameters
----------
symbol: int, optional
    It defaults to `None`, in which it gets the value from the parameter
    database, `get_param("dimsymbol")`.
    A numerical value defines different markers
     * 0, `SoSphere`
     * 1, `SoSeparator` with a `SoLineSet`, a circle (in fact a 24 sided polygon)
     * 2, `SoSeparator` with a `soCone`
     * 3, `SoSeparator` with a `SoFaceSet`
     * 4, `SoSeparator` with a `SoLineSet`, calling `dim_dash`
     * Otherwise, `SoSphere`
invert: bool, optional
    It defaults to `False`.
    If it is `True` and `symbol=2`, the cone will be rotated
    -90 degrees around the Z axis, otherwise the rotation is positive,
    +90 degrees.
Returns
-------
Coin.SoNode
    A `Coin.SoSphere`, or `Coin.SoSeparator` (circle, cone, face, line)
    that will be used as a dimension symbol.
Definition at line 190 of file gui_utils.py.
References draftutils.gui_utils.dim_dash().
display_external()
def draftutils.units.display_external (internal_value, decimals = None, dim = 'Length', showUnit = True, unit = None)
Return a converted value for display, according to the unit schema.
Parameters
----------
internal_value: float
    A value that will be transformed depending on the other parameters.
decimals: float, optional
    It defaults ot `None`, in which case, the decimals are 2.
dim: str, optional
    It defaults to `'Length'`. It can also be `'Angle'`.
showUnit: bool, optional
    It defaults to `True`.
    If it is `False` it won't show the unit.
unit: str, optional
    A unit string such as `'mm'`, `'cm'`, `'m'`, `'in'`, `'ft'`,
    in which to express the returned value.
Definition at line 72 of file units.py.
References KDL.abs(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by DraftGui.DraftToolBar.displayPoint(), DraftGui.DraftToolBar.setRadiusValue(), DraftGui.DraftToolBar.update_cartesian_coords(), and DraftGui.DraftToolBar.update_spherical_coords().
end_all_events()
def draftutils.gui_utils.end_all_events ()
Definition at line 910 of file gui_utils.py.
References draftutils.gui_utils.get_3d_view().
filter_objects_for_modifiers()
def draftutils.utils.filter_objects_for_modifiers (objects, isCopied = False)
Definition at line 887 of file utils.py.
References Gui.getMainWindow().
find_coin_node()
def draftutils.gui_utils.find_coin_node (parent, nodetype)
Definition at line 900 of file gui_utils.py.
find_doc()
def draftutils.utils.find_doc (doc = None)
Return the active document or find a document by name.
Parameters
----------
doc: App::Document or str, optional
    The document that will be searched in the session.
    It defaults to `None`, in which case it tries to find
    the active document.
    If `doc` is a string, it will try to get the document by `Name`.
Returns
-------
bool, App::Document
    A tuple containing the information on whether the search
    was successful. In this case, the boolean is `True`,
    and the second value is the document instance.
False, None
    If there is no active document, or the string in `doc`
    doesn't correspond to an open document in the session.
Definition at line 1006 of file utils.py.
Referenced by draftutils.utils.find_object().
find_object()
def draftutils.utils.find_object (obj, doc = None)
Find object in the document, inclusive by Label.
Parameters
----------
obj: App::DocumentObject or str
    The object to search in `doc`.
    Or if the `obj` is a string, it will search the object by `Label`.
    Since Labels are not guaranteed to be unique, it will get the first
    object with that label in the document.
doc: App::Document or str, optional
    The document in which the object will be searched.
    It defaults to `None`, in which case it tries to search in the
    active document.
    If `doc` is a string, it will search the document by `Name`.
Returns
-------
bool, App::DocumentObject
    A tuple containing the information on whether the search
    was successful. In this case, the boolean is `True`,
    and the second value is the object found.
False, None
    If the object doesn't exist in the document.
Definition at line 1045 of file utils.py.
References draftutils.utils.find_doc().
format_object()
def draftutils.gui_utils.format_object (target, origin = None)
Apply visual properties to an object.
This function only works if the graphical interface is available.
If origin is `None` and target is not an annotation, the DefaultDrawStyle
and DefaultDisplayMode preferences are applied. Else, the properties of
origin are applied to target.
If construction mode is active target is then placed in the construction
group and the `constr` color is applied to its applicable color properties:
TextColor, PointColor, LineColor, and ShapeColor.
Parameters
----------
target: App::DocumentObject
origin: App::DocumentObject, optional
    Defaults to `None`.
    If construction mode is not active, its visual properties are assigned
    to `target`, with the exception of `BoundingBox`, `Proxy`, `RootNode`
    and `Visibility`.
Definition at line 504 of file gui_utils.py.
References draftutils.gui_utils.get_diffuse_color().
Referenced by draftutils.gui_utils.restore_view_object().
get_3d_view()
def draftutils.gui_utils.get_3d_view ()
Return the current 3D view.
Returns
-------
Gui::View3DInventor
    The Active 3D View or `None`.
Definition at line 57 of file gui_utils.py.
References Gui.getMainWindow().
Referenced by draftutils.gui_utils.end_all_events().
get_bbox()
def draftutils.gui_utils.get_bbox (obj, debug = False)
Return a BoundBox from any object that has a Coin RootNode.
Normally the bounding box of an object can be taken
from its `Part::TopoShape`.
::
    >>> print(obj.Shape.BoundBox)
However, for objects without a `Shape`, such as those
derived from `App::FeaturePython` like `Draft Text` and `Draft Dimension`,
the bounding box can be calculated from the `RootNode` of the viewprovider.
Parameters
----------
obj: App::DocumentObject
    Any object that has a `ViewObject.RootNode`.
Returns
-------
Base::BoundBox
    It returns a `BoundBox` object which has information like
    minimum and maximum values of X, Y, and Z, as well as bounding box
    center.
None
    If there is a problem it will return `None`.
Definition at line 834 of file gui_utils.py.
References getValue().
get_clone_base()
def draftutils.utils.get_clone_base (obj, strict = False, recursive = True)
Return the object cloned by this object, if any.
Parameters
----------
obj: App::DocumentObject
    Any type of object.
strict: bool, optional
    It defaults to `False`.
    If it is `True`, and this object is not a clone,
    this function will return `False`.
recursive: bool, optional
    It defaults to `True`
    If it is `True`, it call recursively to itself to
    get base object and if it is `False` then it just
    return base object, not call recursively to find
    base object.
Returns
-------
App::DocumentObject
    It `obj` is a `Draft Clone`, it will return the first object
    that is in its `Objects` property.
    If `obj` has a `CloneOf` property, it will search iteratively
    inside the object pointed to by this property.
obj
    If `obj` is not a `Draft Clone`, nor it has a `CloneOf` property,
    it will return the same `obj`, as long as `strict` is `False`.
False
    It will return `False` if `obj` is not a clone,
    and `strict` is `True`.
Definition at line 546 of file utils.py.
References draftutils.utils.get_type().
get_default_annotation_style()
def draftutils.utils.get_default_annotation_style ()
Definition at line 63 of file utils.py.
get_default_shape_style()
def draftutils.utils.get_default_shape_style ()
Definition at line 86 of file utils.py.
References draftutils.utils.get_view_material().
get_default_unit()
def draftutils.units.get_default_unit (dim)
Return default Unit of Measure for a dimension.
It is based on the user preferences.
Definition at line 36 of file units.py.
Referenced by draftutils.units.make_format_spec().
get_diffuse_color()
def draftutils.gui_utils.get_diffuse_color (objs)
Get a (cumulative) diffuse color from one or more objects.
If all tuples in the result are identical a list with a single tuple is
returned. In theory all faces of an object can be set to the same diffuse
color that is different from its shape color, but that seems rare. The
function does not take that into account.
Parameters
----------
objs: a single object or an iterable with objects.
Returns
-------
list of tuples
    The list will be empty if no valid object is found.
Definition at line 343 of file gui_utils.py.
Referenced by draftutils.gui_utils.format_object().
get_draft_annotation_commands()
def draftutils.init_tools.get_draft_annotation_commands ()
Return the annotation commands list.
Definition at line 67 of file init_tools.py.
get_draft_context_commands()
def draftutils.init_tools.get_draft_context_commands ()
Return the context menu commands list.
Definition at line 166 of file init_tools.py.
get_draft_drawing_commands()
def draftutils.init_tools.get_draft_drawing_commands ()
Return the drawing commands list.
Definition at line 40 of file init_tools.py.
References Arch.QT_TRANSLATE_NOOP.
get_draft_modification_commands()
def draftutils.init_tools.get_draft_modification_commands ()
Return the modification commands list.
Definition at line 75 of file init_tools.py.
References Arch.QT_TRANSLATE_NOOP.
get_draft_snap_commands()
def draftutils.init_tools.get_draft_snap_commands ()
Return the snapping commands list.
Definition at line 142 of file init_tools.py.
Referenced by draftutils.init_draft_statusbar.init_draft_statusbar_snap().
get_draft_utility_commands_menu()
def draftutils.init_tools.get_draft_utility_commands_menu ()
Return the utility commands list for the menu.
Definition at line 109 of file init_tools.py.
get_draft_utility_commands_toolbar()
def draftutils.init_tools.get_draft_utility_commands_toolbar ()
Return the utility commands list for the toolbar.
Definition at line 131 of file init_tools.py.
get_group_contents()
def draftutils.groups.get_group_contents (objectslist, walls = False, addgroups = False, spaces = False, noarchchild = False)
Return a list of objects from expanding the input groups.
The function accepts any type of object, although it is most useful
with "groups", as it is meant to unpack the objects inside these groups.
Parameters
----------
objectslist: list
    If any object in the list is considered a group, see the `is_group`
    function, its contents (`obj.Group`) are extracted and added to the
    output list.
    Single items that aren't groups are added to the output list
    as is.
walls: bool, optional
    It defaults to `False`.
    If it is `True`, Wall and Structure objects (Arch Workbench)
    are treated as groups; they are scanned for Window, Door,
    and Rebar objects, and these are added to the output list.
addgroups: bool, optional
    It defaults to `False`.
    If it is `True`, the group itself is kept as part of the output list.
spaces: bool, optional
    It defaults to `False`.
    If it is `True`, Arch Spaces are added to the output list even
    when addgroups is False (their contents are always added).
noarchchild: bool, optional
    It defaults to `False`.
    If it is `True`, the objects inside Building and BuildingParts
    (Arch Workbench) aren't added to the output list.
Returns
-------
list
    The list of objects from each group present in `objectslist`,
    plus any other individual object given in `objectslist`.
Definition at line 192 of file groups.py.
References draftutils.groups.get_windows(), and draftutils.groups.is_group().
Referenced by draftutils.groups.getGroupContents().
get_group_names()
def draftutils.groups.get_group_names (doc = None)
Return a list of names of existing groups in the document.
Parameters
----------
doc: App::Document, optional
    It defaults to `None`.
    A document on which to search group names.
    It if is `None` it will search the current document.
Returns
-------
list of str
    A list of names of objects that are considered groups.
    See the is_group function.
    Otherwise returns an empty list.
Definition at line 73 of file groups.py.
References draftutils.groups.is_group().
Referenced by draftutils.groups.getGroupNames(), and draftutils.groups.ungroup().
get_movable_children()
def draftutils.groups.get_movable_children (objectslist, recursive = True, _donelist = [])
Return a list of objects with child objects that move with a host.
Builds a list of objects with all child objects (`obj.OutList`)
that have their `MoveWithHost` attribute set to `True`.
This function is mostly useful for Arch Workbench objects.
Parameters
----------
objectslist: list of App::DocumentObject
    A single scripted object or list of objects.
recursive: bool, optional
    It defaults to `True`, in which case the function
    is called recursively to also extract the children of children
    objects.
    Otherwise, only direct children of the input objects
    are added to the output list.
_donelist: list
    List of object names. Used internally to prevent an endless loop.
Returns
-------
list
    List of children objects that have their `MoveWithHost` attribute
    set to `True`.
Definition at line 278 of file groups.py.
Referenced by draftutils.groups.getMovableChildren().
get_objects_of_type()
def draftutils.utils.get_objects_of_type (objects, typ)
Return only the objects that match the type in the list of objects.
Parameters
----------
objects : list of App::DocumentObject
    A list of objects which will be tested.
typ : str
    A string that indicates a type. This should be one of the types
    that can be returned by `get_type`.
Returns
-------
list of objects
    Only the objects that match `typ` will be added to the output list.
Definition at line 452 of file utils.py.
References draftutils.utils.getType.
get_param()
def draftutils.utils.get_param (param, default = None)
Return a parameter value from the current parameter database.
The parameter database is located in the tree
::
    'User parameter:BaseApp/Preferences/Mod/Draft'
In the case that `param` is `'linewidth'` or `'color'` it will get
the values from the View parameters
::
    'User parameter:BaseApp/Preferences/View/DefaultShapeLineWidth'
    'User parameter:BaseApp/Preferences/View/DefaultShapeLineColor'
Parameters
----------
param : str
    A string that indicates a parameter in the parameter database.
default : optional
    It indicates the default value of the given parameter.
    It defaults to `None`, in which case it will use a specific
    value depending on the type of parameter determined
    with `get_param_type`.
Returns
-------
int, or str, or float, or bool
    Depending on `param` and its type, by returning `ParameterGrp.GetInt`,
    `ParameterGrp.GetString`, `ParameterGrp.GetFloat`,
    `ParameterGrp.GetBool`, or `ParameterGrp.GetUnsinged`.
Definition at line 234 of file utils.py.
References draftutils.utils.get_param_type().
get_param_type()
def draftutils.utils.get_param_type (param)
Return the type of the parameter entered.
Parameters
----------
param : str
    A string that indicates a parameter in the parameter database.
Returns
-------
str or None
    The returned string could be `'int'`, `'string'`, `'float'`,
    `'bool'`, `'unsigned'`, depending on the parameter.
    It returns `None` for unhandled situations.
Definition at line 184 of file utils.py.
Referenced by draftutils.utils.get_param(), and draftutils.utils.set_param().
get_real_name()
def draftutils.utils.get_real_name (name)
Strip the trailing numbers from a string to get only the letters.
Parameters
----------
name : str
    A string that may have a number at the end, `Line001`.
Returns
-------
str
    A string without the numbers at the end, `Line`.
    The returned string cannot be empty; it will have
    at least one letter.
Definition at line 390 of file utils.py.
get_rgb()
def draftutils.utils.get_rgb (color, testbw = True)
Return an RRGGBB value #000000 from a FreeCAD color.
Parameters
----------
color : list or tuple with RGB values
    The values must be in the 0.0-1.0 range.
testwb : bool (default = True)
    Pure white will be converted into pure black.
Definition at line 808 of file utils.py.
References Path.Post.scripts.refactored_centroid_post.str.
get_rgba_tuple()
def draftutils.utils.get_rgba_tuple (color, typ = 1.0)
Return an RGBA tuple.
Parameters
----------
color: int
    RGBA integer.
typ: any float (default = 1.0) or int (use 255)
    If float the values in the returned tuple are in the 0.0-1.0 range.
    Else the values are in the 0-255 range.
Definition at line 866 of file utils.py.
References Path.Post.scripts.grbl_post.type.
get_scales()
def draftutils.init_draft_statusbar.get_scales (unit_system = 0)
returns the list of preset scales according to unit system.
Parameters:
unit_system =   0 : default from user preferences
                1 : metrics
                2 : imperial architectural
                3 : imperial engineering
Definition at line 69 of file init_draft_statusbar.py.
Referenced by draftutils.init_draft_statusbar.init_draft_statusbar_scale().
get_selection()
def draftutils.gui_utils.get_selection (gui = App.GuiUp)
Return the current selected objects.
This function only works if the graphical interface is available
as the selection module only works on the 3D view.
It wraps around `Gui.Selection.getSelection`
Parameters
----------
gui: bool, optional
    It defaults to the value of `App.GuiUp`, which is `True`
    when the interface exists, and `False` otherwise.
    This value can be set to `False` to simulate
    when the interface is not available.
Returns
-------
list of App::DocumentObject
    Returns a list of objects in the current selection.
    It can be an empty list if no object is selected.
    If the interface is not available, it returns `None`.
Definition at line 589 of file gui_utils.py.
get_selection_ex()
def draftutils.gui_utils.get_selection_ex (gui = App.GuiUp)
Return the current selected objects together with their subelements.
This function only works if the graphical interface is available
as the selection module only works on the 3D view.
It wraps around `Gui.Selection.getSelectionEx`
Parameters
----------
gui: bool, optional
    It defaults to the value of `App.GuiUp`, which is `True`
    when the interface exists, and `False` otherwise.
    This value can be set to `False` to simulate
    when the interface is not available.
Returns
-------
list of Gui::SelectionObject
    Returns a list of `Gui::SelectionObject` in the current selection.
    It can be an empty list if no object is selected.
    If the interface is not available, it returns `None`.
Selection objects
-----------------
One `Gui::SelectionObject` has attributes that indicate which specific
subelements, that is, vertices, wires, and faces, were selected.
This can be useful to operate on the subelements themselves.
If `G` is a `Gui::SelectionObject`
 * `G.Object` is the selected object
 * `G.ObjectName` is the name of the selected object
 * `G.HasSubObjects` is `True` if there are subelements in the selection
 * `G.SubObjects` is a tuple of the subelements' shapes
 * `G.SubElementNames` is a tuple of the subelements' names
`SubObjects` and `SubElementNames` should be empty tuples
if `HasSubObjects` is `False`.
Definition at line 622 of file gui_utils.py.
get_type()
def draftutils.utils.get_type (obj)
Return a string indicating the type of the given object.
Parameters
----------
obj : App::DocumentObject
    Any type of scripted object created with Draft,
    or any other workbench.
Returns
-------
str
    If `obj` has a `Proxy`, it will return the value of `obj.Proxy.Type`.
    * If `obj` is a `Part.Shape`, returns `'Shape'`
    * If `obj` has a `TypeId`, returns `obj.TypeId`
    In other cases, it will return `'Unknown'`,
    or `None` if `obj` is `None`.
Definition at line 414 of file utils.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by draftutils.utils.compare_objects(), and draftutils.utils.get_clone_base().
get_view_material()
def draftutils.utils.get_view_material ()
Return a ShapeAppearance material with properties based on the preferences.
Definition at line 101 of file utils.py.
Referenced by draftutils.utils.get_default_shape_style().
get_windows()
def draftutils.groups.get_windows (obj)
Return the windows and rebars inside a host.
Parameters
----------
obj: App::DocumentObject
    A scripted object of type `'Wall'` or `'Structure'`
    (Arch Workbench).
    This will be searched for objects of type `'Window'` and `'Rebar'`,
    and clones of them, and the found elements will be added
    to the output list.
    The function will search recursively all elements under `obj.OutList`,
    in case the windows and rebars are nested under other walls
    and structures.
Returns
-------
list
    A list of all found windows and rebars in `obj`.
    If `obj` is itself a `'Window'` or a `'Rebar'`, or a clone of them,
    it will return the same `obj` element.
Definition at line 147 of file groups.py.
Referenced by draftutils.groups.get_group_contents().
getGroupContents()
def draftutils.groups.getGroupContents (objectslist, walls = False, addgroups = False, spaces = False, noarchchild = False)
Return a list of objects from groups. DEPRECATED.
Definition at line 267 of file groups.py.
References draftutils.groups.get_group_contents().
getGroupNames()
def draftutils.groups.getGroupNames ()
Return a list of group names. DEPRECATED.
Definition at line 107 of file groups.py.
References draftutils.groups.get_group_names().
getMovableChildren()
def draftutils.groups.getMovableChildren (objectslist, recursive = True)
Return a list of objects with child objects. DEPRECATED.
Definition at line 341 of file groups.py.
References draftutils.groups.get_movable_children().
hide_draft_statusbar()
def draftutils.init_draft_statusbar.hide_draft_statusbar ()
hides draft statusbar if present
Definition at line 326 of file init_draft_statusbar.py.
References Gui.getMainWindow().
init_draft_statusbar_scale()
def draftutils.init_draft_statusbar.init_draft_statusbar_scale ()
this function initializes draft statusbar scale widget
Definition at line 176 of file init_draft_statusbar.py.
References draftutils.init_draft_statusbar.get_scales(), Gui.getMainWindow(), and draftutils.init_draft_statusbar.scale_to_label().
init_draft_statusbar_snap()
def draftutils.init_draft_statusbar.init_draft_statusbar_snap ()
this function initializes draft statusbar snap widget
Definition at line 222 of file init_draft_statusbar.py.
References draftutils.init_tools.get_draft_snap_commands(), and Gui.getMainWindow().
init_menu()
def draftutils.init_tools.init_menu (workbench, menu_list, cmd_list)
Initialize a menu.
Parameters
----------
workbench: Gui.Workbench
    The workbench. The commands from cmd_list must be available.
menu_list: list of strings
    The main and optional submenu(s). The commands, and additional
    submenus (if any), are added to the last (sub)menu in the list.
cmd_list: list of strings or list of strings and tuples
    See f.e. the return value of get_draft_drawing_commands.
Definition at line 206 of file init_tools.py.
init_toolbar()
def draftutils.init_tools.init_toolbar (workbench, toolbar, cmd_list)
Initialize a toolbar.
Parameters
----------
workbench: Gui.Workbench
    The workbench. The commands from cmd_list must be available.
toolbar: string
    The name of the toolbar.
cmd_list: list of strings or list of strings and tuples
    See f.e. the return value of get_draft_drawing_commands.
Definition at line 184 of file init_tools.py.
is_clone()
def draftutils.utils.is_clone (obj, objtype = None, recursive = False)
Return True if the given object is a clone of a certain type.
A clone is of type `'Clone'`, and has a reference
to the original object inside its `Objects` attribute,
which is an `'App::PropertyLinkListGlobal'`.
The `Objects` attribute can point to another `'Clone'` object.
If `recursive` is `True`, the function will be called recursively
to further test this clone, until the type of the original object
can be compared to `objtype`.
Parameters
----------
obj : App::DocumentObject
    The clone object that will be tested for a certain type.
objtype : str or list of str
    A type string such as one obtained from `get_type`.
    Or a list of such types.
recursive : bool, optional
    It defaults to `False`.
    If it is `True`, this same function will be called recursively
    with `obj.Object[0]` as input.
    This option only works if `obj.Object[0]` is of type `'Clone'`,
    that is, if `obj` is a clone of a clone.
Returns
-------
bool
    Returns `True` if `obj` is of type `'Clone'`,
    and `obj.Object[0]` is of type `objtype`.
    If `objtype` is a list, then `obj.Objects[0]`
    will be tested against each of the elements in the list,
    and it will return `True` if at least one element matches the type.
    If `obj` isn't of type `'Clone'` but has the `CloneOf` attribute,
    it will also return `True`.
    It returns `False` otherwise, for example,
    if `obj` is not even a clone.
Definition at line 479 of file utils.py.
References draftutils.utils.getType.
is_closed_edge()
def draftutils.utils.is_closed_edge (edge_index, object)
Definition at line 909 of file utils.py.
is_group()
def draftutils.groups.is_group (obj)
Return True if the given object is considered a group.
Parameters
----------
obj : App::DocumentObject
    The object to check.
Returns
-------
bool
    Returns `True` if `obj` is considered a group:
    The object is derived from `App::DocumentObjectGroup` but not
    a `'LayerContainer'`.
    Or the object is of the type `'Project'`, `'Site'`, `'Building'`,
    `'Floor'`, `'BuildingPart'` or `'Space'` from the Arch Workbench.
    Note that `'Floor'` and `'Building'` are obsolete types.
    Otherwise returns `False`.
Definition at line 44 of file groups.py.
Referenced by draftutils.groups.get_group_contents(), and draftutils.groups.get_group_names().
label_to_scale()
def draftutils.init_draft_statusbar.label_to_scale (label)
transform a scale string into scale factor as float
Definition at line 116 of file init_draft_statusbar.py.
References Gui.getMainWindow(), and draftutils.init_draft_statusbar.scale_to_label().
load_svg_patterns()
def draftutils.utils.load_svg_patterns ()
Load the default Draft SVG patterns and user defined patterns.
The SVG patterns are added as a dictionary to the `App.svgpatterns`
attribute.
Definition at line 734 of file utils.py.
References importSVG.getContents(), and Path.Post.scripts.refactored_centroid_post.str.
load_texture()
def draftutils.gui_utils.load_texture (filename, size = None, gui = App.GuiUp)
Return a Coin.SoSFImage to use as a texture for a 2D plane.
This function only works if the graphical interface is available
as the visual properties that can be applied to a shape
are attributes of the view provider (`obj.ViewObject`).
Parameters
----------
filename: str
    A path to a pixel image file (PNG) that can be used as a texture
    on the face of an object.
size: tuple of two int, or a single int, optional
    It defaults to `None`.
    If a tuple is given, the two values define the width and height
    in pixels to which the loaded image will be scaled.
    If it is a single value, it is used for both dimensions.
    If it is `None`, the size will be determined from the `QImage`
    created from `filename`.
    CURRENTLY the input `size` parameter IS NOT USED.
    It always uses the `QImage` to determine this information.
gui: bool, optional
    It defaults to the value of `App.GuiUp`, which is `True`
    when the interface exists, and `False` otherwise.
    This value can be set to `False` to simulate
    when the interface is not available.
Returns
-------
coin.SoSFImage
    An image object with the appropriate size, number of components
    (grayscale, grayscale and transparency, color,
    color and transparency), and byte data.
    It returns `None` if the interface is not available,
    or if there is a problem creating the image.
Definition at line 700 of file gui_utils.py.
References Path.Post.scripts.refactored_centroid_post.str.
make_format_spec()
def draftutils.units.make_format_spec (decimals = 4, dim = 'Length')
Return a string format specifier with decimals for a dimension.
It is based on the user preferences.
Definition at line 55 of file units.py.
References draftutils.units.get_default_unit(), and Path.Post.scripts.refactored_centroid_post.str.
migrate_text_display_mode()
def draftutils.gui_utils.migrate_text_display_mode (obj_type = "Text", mode = "3D text", doc = None)
Migrate the display mode of objects of certain type.
Definition at line 824 of file gui_utils.py.
precision()
def draftutils.utils.precision ()
Return the precision value from the parameter database.
It is the number of decimal places that a float will have.
Example
::
    precision=6, 0.123456
    precision=5, 0.12345
    precision=4, 0.1234
Due to floating point operations there may be rounding errors.
Therefore, this precision number is used to round up values
so that all operations are consistent.
By default the precision is 6 decimal places.
Returns
-------
int
    params.get_param("precision")
Definition at line 356 of file utils.py.
Referenced by draftutils.utils.tolerance().
print_header()
def draftutils.utils.print_header (name, description, debug = True)
Print a line to the console when something is called, and log it.
Parameters
----------
name: str
    The name of the function or class that is being called.
    This `name` will be logged in the log file, so if there are problems
    the log file can be investigated for clues.
description: str
    Arbitrary text that will be printed to the console
    when the function or class is called.
debug: bool, optional
    It defaults to `True`.
    If it is `False` the `description` will not be printed
    to the console.
    On the other hand the `name` will always be logged.
Definition at line 980 of file utils.py.
print_shape()
def draftutils.utils.print_shape (shape)
Print detailed information of a topological shape.
Parameters
----------
shape : Part::TopoShape
    Any topological shape in an object, usually obtained from `obj.Shape`.
Definition at line 655 of file utils.py.
remove_hidden()
def draftutils.gui_utils.remove_hidden (objectslist)
Return only the visible objects in the list.
This function only works if the graphical interface is available
as the `Visibility` attribute is a property of the view provider
(`obj.ViewObject`).
Parameters
----------
objectslist: list of App::DocumentObject
    List of any type of object.
Returns
-------
list
    Return a copy of the input list without those objects
    for which `obj.ViewObject.Visibility` is `False`.
    If the graphical interface is not loaded
    the returned list is just a copy of the input list.
Definition at line 311 of file gui_utils.py.
restore_view_object()
def draftutils.gui_utils.restore_view_object (obj, vp_module, vp_class, format = True, format_ref = None)
Restore the ViewObject if the object was saved without the GUI.
Parameters
----------
obj: App::DocumentObject
    Object whose ViewObject needs to be restored.
vp_module: string
    View provider module. Must be in the draftviewproviders directory.
vp_class: string
    View provider class.
format: bool, optional
    Defaults to `True`.
    If `True` the `format_object` function is called to update the
    properties of the ViewObject.
format_ref: App::DocumentObject, optional
    Defaults to `None`.
    Reference object to copy ViewObject properties from.
Definition at line 471 of file gui_utils.py.
References draftutils.gui_utils.format_object().
rgba_to_argb()
def draftutils.utils.rgba_to_argb (color)
Change byte order of a 4 byte color int from RGBA (FreeCAD) to ARGB (Qt).
Definition at line 860 of file utils.py.
scale_to_label()
def draftutils.init_draft_statusbar.scale_to_label (scale)
transform a float number into a 1:X or X:1 scale and return it as label
Definition at line 96 of file init_draft_statusbar.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by draftutils.init_draft_statusbar.init_draft_statusbar_scale(), and draftutils.init_draft_statusbar.label_to_scale().
select()
def draftutils.gui_utils.select (objs = None, gui = App.GuiUp)
Unselects everything and selects only the given list of objects.
This function only works if the graphical interface is available
as the selection module only works on the 3D view.
Parameters
----------
objs: list of App::DocumentObject, optional
    It defaults to `None`.
    Any type of scripted object.
    It may be a list of objects or a single object.
gui: bool, optional
    It defaults to the value of `App.GuiUp`, which is `True`
    when the interface exists, and `False` otherwise.
    This value can be set to `False` to simulate
    when the interface is not available.
Definition at line 670 of file gui_utils.py.
set_param()
def draftutils.utils.set_param (param, value)
Set a Draft parameter with the given value.
The parameter database is located in the tree
::
    'User parameter:BaseApp/Preferences/Mod/Draft'
In the case that `param` is `'linewidth'` or `'color'` it will set
the View parameters
::
    'User parameter:BaseApp/Preferences/View/DefaultShapeLineWidth'
    'User parameter:BaseApp/Preferences/View/DefaultShapeLineColor'
Parameters
----------
param : str
    A string that indicates a parameter in the parameter database.
value : int, or str, or float, or bool
    The appropriate value of the parameter.
    Depending on `param` and its type, determined with `get_param_type`,
    it sets the appropriate value by calling `ParameterGrp.SetInt`,
    `ParameterGrp.SetString`, `ParameterGrp.SetFloat`,
    `ParameterGrp.SetBool`, or `ParameterGrp.SetUnsinged`.
Definition at line 303 of file utils.py.
References draftutils.utils.get_param_type().
shapify()
def draftutils.utils.shapify (obj)
Transform a parametric object into a static, non-parametric shape.
Parameters
----------
obj : App::DocumentObject
    Any type of scripted object.
    This object will be removed, and a non-parametric object
    with the same topological shape (`Part::TopoShape`)
    will be created.
Returns
-------
Part::Feature
    The new object that takes `obj.Shape` as its own.
    Depending on the contents of the Shape, the resulting object
    will be named `'Face'`, `'Solid'`, `'Compound'`,
    `'Shell'`, `'Wire'`, `'Line'`, `'Circle'`,
    or the name returned by `get_real_name(obj.Name)`.
    If there is a problem with `obj.Shape`, it will return `None`,
    and the original object will not be modified.
Definition at line 599 of file utils.py.
References draftutils.utils.getRealName.
show_draft_statusbar()
def draftutils.init_draft_statusbar.show_draft_statusbar ()
shows draft statusbar if present or initializes it
Definition at line 290 of file init_draft_statusbar.py.
References Gui.getMainWindow().
string_encode_coin()
def draftutils.utils.string_encode_coin (ustr)
Encode a unicode object to be used as a string in coin.
Parameters
----------
ustr : str
    A string to be encoded
Returns
-------
str
    Encoded string. If the coin version is >= 4
    it will encode the string to `'utf-8'`, otherwise
    it will encode it to `'latin-1'`.
Definition at line 113 of file utils.py.
svg_patterns()
def draftutils.utils.svg_patterns ()
Return a dictionary with installed SVG patterns.
Returns
-------
dict
    Returns `App.svgpatterns` if it exists.
    Otherwise it calls `load_svg_patterns` to create it
    before returning it.
Definition at line 786 of file utils.py.
References draftutils.utils.loadSvgPatterns.
tolerance()
def draftutils.utils.tolerance ()
Return a tolerance based on the precision() value
Returns
-------
float
    10 ** -precision()
Definition at line 379 of file utils.py.
References draftutils.utils.precision().
Referenced by MeshGui::TaskDecimating.accept(), TechDraw::DrawUtil.angleWithX(), BOOST_PYTHON_MODULE(), TechDraw::DrawUtil.checkParallel(), AdaptivePath.CleanPath(), Part::TopoShape.common(), Part::TopoShape.cut(), Sketcher::SketchAnalysis.detectDegeneratedGeometries(), Sketcher::SketchObject.detectDegeneratedGeometries(), FC_LOG_LEVEL_INIT(), geoff_geometry.FEQ(), geoff_geometry.FEQZ(), ReverseEngineeringGui::SegmentationManual::Private.findGeometry(), geoff_geometry.FNE(), geoff_geometry.FNEZ(), TechDraw::DrawUtil.fpCompare(), Part::TopoShape.fuse(), Part::TopoShape.generalFuse(), Drawing::ProjectionAlgos.getDXF(), TechDraw::ProjectionAlgos.getDXF(), TechDraw::DimensionFormatter.getFormattedDimensionValue(), Drawing::ProjectionAlgos.getSVG(), TechDraw::ProjectionAlgos.getSVG(), MeasureGui::ViewProviderMeasureDistance.getTextDirection(), MeasureGui::ViewProviderMeasureBase.getTextDirection(), TechDraw::DrawUtil.incidenceAngleAtVertex(), init_pyarea(), TechDraw::DrawUtil.isFirstVert(), TechDraw::DrawUtil.isLastVert(), geoff_geometry.IsPtsLine(), Part::TangentialArc.isRadiusEqual(), TechDraw::DrawUtil.isSamePoint(), TechDraw::DrawUtil.isZeroEdge(), TechDraw::GeometryUtils.nextGeom(), MeshPart::MeshProjection.projectOnMesh(), geoff_geometry::Kurve.Reduce(), Sketcher::SketchAnalysis.removeDegeneratedGeometries(), Sketcher::SketchObject.removeDegeneratedGeometries(), Part::GeomBSplineCurve.removeKnot(), Part::TopoShape.section(), Part::TopoShape.setFaces(), Part::TopoShape.sewShape(), MeshCore::MeshSimplify.simplify(), Simplify.simplify_mesh(), geoff_geometry.Split(), Part::BSplineCurveBiArcs.toBiArcs(), and Part::GeomBSplineCurve.toBiArcs().
translate()
def draftutils.translate.translate (context, text, comment = None)
Translate the text using the Qt translate function.
It wraps around `QtWidgets.QApplication.translate`,
which is the same as `QtCore.QCoreApplication.translate`.
Parameters
----------
context: str
    In C++ it is typically a class name.
    But it can also be any other string to categorize the translation,
    for example, the name of a workbench, tool, or function
    that is being translated. Usually it will be the name
    of the workbench.
text: str
    Text that will be translated. It could be a single word,
    a full sentence, paragraph, or multiple paragraphs with new lines.
    Usually the last endline character '\n'
    that finishes the string doesn't need to be included
    for translation.
Returns
-------
str
    A unicode string returned by `QtWidgets.QApplication.translate`.
Unicode strings
---------------
Reference: https://doc.qt.io/qtforpython/PySide2/QtCore
In Qt5 the strings are always assumed unicode
>>> QtCore.QCoreApplication.translate(context, text, None)
>>> QtWidgets.QApplication.translate(context, text, None)
Definition at line 46 of file translate.py.
References draftutils.translate.Qtranslate.
type_check()
def draftutils.utils.type_check (args_and_types, name = "?")
Check that the arguments are instances of certain types.
Parameters
----------
args_and_types : list
    A list of tuples. The first element of a tuple is tested as being
    an instance of the second element.
    ::
        args_and_types = [(a, Type), (b, Type2), ...]
    Then
    ::
        isinstance(a, Type)
        isinstance(b, Type2)
    A `Type` can also be a tuple of many types, in which case
    the check is done for any of them.
    ::
        args_and_types = [(a, (Type3, int, float)), ...]
        isinstance(a, (Type3, int, float))
name : str, optional
    Defaults to `'?'`. The name of the check.
Raises
------
TypeError
    If the first element in the tuple is not an instance of the second
    element, it raises `Draft.name`.
Definition at line 142 of file utils.py.
References Path.Post.scripts.refactored_centroid_post.str.
ungroup()
def draftutils.groups.ungroup (obj)
Remove the object from any group to which it belongs.
A "group" is any object returned by `get_group_names`.
Parameters
----------
obj: App::DocumentObject or str
    Any type of object.
    If it is a string, it must be the `Label` of that object.
    Since a label is not guaranteed to be unique in a document,
    it will use the first object found with this label.
Definition at line 113 of file groups.py.
References draftutils.groups.get_group_names().
use_instead()
def draftutils.utils.use_instead (function, version = "")
Print a deprecation message and suggest another function.
This function must be used inside the definition of a function
that has been considered for deprecation, so we must provide
an alternative.
::
    def old_function():
        use_instead('new_function', 1.0)
    def someFunction():
        use_instead('some_function')
Parameters
----------
function: str
    The name of the function to use instead of the current one.
version: float or str, optional
    It defaults to the empty string `''`.
    The version where this command is to be deprecated, if it is known.
    If we don't know when this command will be deprecated
    then we should not give a version.
Definition at line 1091 of file utils.py.
utf8_decode()
def draftutils.utils.utf8_decode (text)
Decode the input string and return a unicode string.
Python 2:
::
    str -> unicode
    unicode -> unicode
Python 3:
::
    str -> str
    bytes -> str
It runs
::
    try:
        return text.decode("utf-8")
    except AttributeError:
        return text
Parameters
----------
text : str, unicode or bytes
    A str, unicode, or bytes object that may have unicode characters
    like accented characters.
    In Python 2, a `bytes` object can include accented characters,
    but in Python 3 it must only contain ASCII literal characters.
Returns
-------
unicode or str
    In Python 2 it will try decoding the `bytes` string
    and return a `'utf-8'` decoded string.
    >>> "A".decode("utf-8")
    >>> b"A".decode("utf-8")
    u'A\xe1'
    In Python 2 the unicode string is prefixed with `u`,
    and unicode characters are replaced by their two-digit hexadecimal
    representation, or four digit unicode escape.
    >>> "ABC".decode("utf-8")
    u'A\xe1B\u1e83C\xf1'
    In Python 2 it will always return a `unicode` object.
    In Python 3 a regular string is already unicode encoded,
    so strings have no `decode` method. In this case, `text`
    will be returned as is.
    In Python 3, if `text` is a `bytes` object, then it will be converted
    to `str`; in this case, the `bytes` object cannot have accents,
    it must only contain ASCII literal characters.
    >>> b"ABC".decode("utf-8")
    'ABC'
    In Python 3 it will always return a `str` object, with no prefix.
Definition at line 913 of file utils.py.
Variable Documentation
ARROW_TYPES
draftutils.utils.ARROW_TYPES
Definition at line 57 of file utils.py.
arrowtypes
draftutils.utils.arrowtypes
Definition at line 60 of file utils.py.
compareObjects
draftutils.utils.compareObjects
Definition at line 731 of file utils.py.
dimDash
draftutils.gui_utils.dimDash
Definition at line 308 of file gui_utils.py.
dimSymbol
draftutils.gui_utils.dimSymbol
Definition at line 275 of file gui_utils.py.
DISPLAY_MODES
draftutils.utils.DISPLAY_MODES
Definition at line 58 of file utils.py.
displayExternal
draftutils.units.displayExternal
Definition at line 137 of file units.py.
draft_scales_arch_imperial
draftutils.init_draft_statusbar.draft_scales_arch_imperial
Definition at line 55 of file init_draft_statusbar.py.
draft_scales_eng_imperial
draftutils.init_draft_statusbar.draft_scales_eng_imperial
Definition at line 62 of file init_draft_statusbar.py.
draft_scales_metrics
draftutils.init_draft_statusbar.draft_scales_metrics
Definition at line 48 of file init_draft_statusbar.py.
DRAW_STYLES
draftutils.utils.DRAW_STYLES
Definition at line 59 of file utils.py.
formatObject
draftutils.gui_utils.formatObject
Definition at line 586 of file gui_utils.py.
Referenced by Gui::PropertyEditor::LinkLabel.updatePropertyLink().
get3DView
draftutils.gui_utils.get3DView
Definition at line 82 of file gui_utils.py.
getCloneBase
draftutils.utils.getCloneBase
Definition at line 596 of file utils.py.
getDefaultUnit
draftutils.units.getDefaultUnit
Definition at line 52 of file units.py.
getObjectsOfType
draftutils.utils.getObjectsOfType
Definition at line 476 of file utils.py.
Referenced by PartGui::CrossSections.apply(), PartGui::DlgExtrusion.DlgExtrusion(), PartGui::DlgRevolution.DlgRevolution(), PartGui::DlgScale.DlgScale(), execCosmeticVertex(), Gui::SelectionSingleton.getObjectsOfType(), and PartGui::Mirroring.Mirroring().
getParam
draftutils.utils.getParam
Definition at line 300 of file utils.py.
Referenced by Path::Command.getCenter(), Path::Command.getPlacement(), and Path::Command.getValue().
getParamType
draftutils.utils.getParamType
Definition at line 231 of file utils.py.
getRealName
draftutils.utils.getRealName
Definition at line 411 of file utils.py.
Referenced by draftutils.utils.shapify().
getrgb
draftutils.utils.getrgb
Definition at line 830 of file utils.py.
getSelection
draftutils.gui_utils.getSelection
Definition at line 619 of file gui_utils.py.
Referenced by MeshPartGui::Tessellation.accept(), CmdSketcherConstraint.activated(), PartDesignGui::DlgActiveBody.DlgActiveBody(), linkConvert(), linkConvertible(), PartDesignGui::TaskFeaturePick.onSelectionChanged(), Gui::TaskMeasure.update(), and Gui::View3DInventorViewer.viewSelection().
getSelectionEx
draftutils.gui_utils.getSelectionEx
Definition at line 667 of file gui_utils.py.
Referenced by _copyShape(), RobotGui::TaskRobot6Axis.createPlacementDlg(), AssemblyGui::ViewProviderAssembly.getSelectedObjectsWithinAssembly(), Gui::ElementColors::Private.onSelectionChanged(), and MeshGui::TaskSmoothing.TaskSmoothing().
getType
draftutils.utils.getType
Definition at line 449 of file utils.py.
Referenced by draftutils.utils.compare_objects(), Gui::MainWindow.customEvent(), draftutils.utils.get_objects_of_type(), and draftutils.utils.is_clone().
isClone
draftutils.utils.isClone
Definition at line 543 of file utils.py.
loadSvgPatterns
draftutils.utils.loadSvgPatterns
Definition at line 783 of file utils.py.
Referenced by draftutils.utils.svg_patterns().
loadTexture
draftutils.gui_utils.loadTexture
Definition at line 821 of file gui_utils.py.
makeFormatSpec
draftutils.units.makeFormatSpec
Definition at line 69 of file units.py.
printShape
draftutils.utils.printShape
Definition at line 684 of file utils.py.
QT_TRANSLATE_NOOP
draftutils.translate.QT_TRANSLATE_NOOP
Definition at line 142 of file translate.py.
Qtranslate
draftutils.translate.Qtranslate
Definition at line 38 of file translate.py.
Referenced by draftutils.translate.translate().
removeHidden
draftutils.gui_utils.removeHidden
Definition at line 340 of file gui_utils.py.
setParam
draftutils.utils.setParam
Definition at line 353 of file utils.py.
stringencodecoin
draftutils.utils.stringencodecoin
Definition at line 139 of file utils.py.
svgpatterns
draftutils.utils.svgpatterns
Definition at line 805 of file utils.py.
todo
draftutils.todo.todo
Definition at line 287 of file todo.py.
Referenced by MeshCore::MeshRemoveNeedles.Fixup(), MeshCore::MeshFixCaps.Fixup(), and MeshCore::MeshTopoAlgorithm.OptimizeTopology().
typecheck
draftutils.utils.typecheck
Definition at line 181 of file utils.py.