FreeCAD: MatGui::PrefMaterialTreeWidget Class Reference
MatGui::PrefMaterialTreeWidget Class Reference
#include <MaterialTreeWidget.h>
Public Member Functions
PrefMaterialTreeWidget (QWidget *parent=nullptr)
~PrefMaterialTreeWidget () override
Public Member Functions inherited from MatGui::MaterialTreeWidget
MaterialTreeWidget (const std::shared_ptr< Materials::MaterialFilter > &filter, QWidget *parent=nullptr)
MaterialTreeWidget (const std::shared_ptr< std::list< std::shared_ptr< Materials::MaterialFilter >>> &filterList, QWidget *parent=nullptr)
MaterialTreeWidget (QWidget *parent=nullptr)
~MaterialTreeWidget () override
void setMaterial (const QString &uuid)
QString getMaterialUUID () const
void setFilter (const std::shared_ptr< Materials::MaterialFilter > &filter)
void setFilter (const std::shared_ptr< std::list< std::shared_ptr< Materials::MaterialFilter >>> &filterList)
void setActiveFilter (const QString &name)
void setExpanded (bool open)
bool getExpanded ()
bool includeFavorites () const
void setIncludeFavorites (bool value)
bool includeRecent () const
void setIncludeRecent (bool value)
bool includeEmptyFolders () const
void setIncludeEmptyFolders (bool value)
bool includeEmptyLibraries () const
void setIncludeEmptyLibraries (bool value)
bool includeLegacy () const
void setIncludeLegacy (bool legacy)
QSize sizeHint () const override
QSize treeSizeHint () const
void setTreeSizeHint (const QSize &hint)
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from Gui::PrefWidget
void setEntryName (const QByteArray &name)
QByteArray entryName () const
void setPrefEntry (const QByteArray &name)
void setParamGrpPath (const QByteArray &path)
QByteArray paramGrpPath () const
void setPrefPath (const QByteArray &name)
void OnChange (Base::Subject< const char * > &rCaller, const char *sReason) override
void onSave ()
void onRestore ()
Public Member Functions inherited from Gui::WindowParameter
WindowParameter (const char *name)
~WindowParameter () override
void OnChange (Base::Subject< const char * > &rCaller, const char *sReason) override
ParameterGrp::handle getWindowParameter ()
return the parameter group of this window
Protected Member Functions
void restorePreferences () override
void savePreferences () override
Protected Member Functions inherited from MatGui::MaterialTreeWidget
Materials::MaterialManager & getMaterialManager ()
void getFavorites ()
void getRecents ()
void saveRecents ()
void addRecent (const QString &uuid)
bool isRecent (const QString &uuid) const
void saveWidgetSettings ()
void saveMaterialTreeChildren (const Base::Reference< ParameterGrp > &param, QTreeView *tree, QStandardItemModel *model, QStandardItem *item)
void saveMaterialTree ()
void createLayout ()
bool findInTree (const QStandardItem &node, QModelIndex *index, const QString &uuid)
QModelIndex findInTree (const QString &uuid)
void updateMaterial (const QString &uuid)
void createMaterialTree ()
void fillMaterialTree ()
void updateMaterialTree ()
void addExpanded (QStandardItem *parent, QStandardItem *child)
void addExpanded (QStandardItem *parent, QStandardItem *child, const Base::Reference< ParameterGrp > &param)
void addExpanded (QStandardItemModel *model, QStandardItem *child)
void addExpanded (QStandardItemModel *model, QStandardItem *child, const Base::Reference< ParameterGrp > &param)
void addRecents (QStandardItem *parent)
void addFavorites (QStandardItem *parent)
void addMaterials (QStandardItem &parent, const std::shared_ptr< std::map< QString, std::shared_ptr< Materials::MaterialTreeNode >>> &modelTree, const QIcon &folderIcon, const QIcon &icon, const Base::Reference< ParameterGrp > &param)
void setFilterVisible (bool open)
void fillFilterCombo ()
bool hasMultipleFilters () const
Protected Member Functions inherited from Gui::PrefWidget
void failedToSave (const QString &) const
void failedToRestore (const QString &) const
PrefWidget ()
~PrefWidget () override
Protected Member Functions inherited from Gui::WindowParameter
bool setGroupName (const char *name)
template<typename S , typename T >
void setSlotParamChanged (S slot, T *obsPtr)
connect slot to ParameterManager signal
Properties
QByteArray prefEntry
QByteArray prefPath
Properties inherited from MatGui::MaterialTreeWidget
QSize treeSizeHint
Additional Inherited Members
Signals inherited from MatGui::MaterialTreeWidget
void materialSelected (const std::shared_ptr< Materials::Material > &material)
void onMaterial (const QString &uuid)
void onExpanded (bool expanded)
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Public Member Functions inherited from Gui::WindowParameter
static ParameterGrp::handle getDefaultParameter ()
get the parameters
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Gui::PrefWidget
bool m_Restored = false
Detailed Description
The PrefColorButton class.
Definition at line 293 of file MaterialTreeWidget.h.
Constructor & Destructor Documentation
PrefMaterialTreeWidget()
PrefMaterialTreeWidget::PrefMaterialTreeWidget (QWidget * parent = nullptr) explicit
Definition at line 770 of file MaterialTreeWidget.cpp.
~PrefMaterialTreeWidget()
PrefMaterialTreeWidget::~PrefMaterialTreeWidget () override default
Member Function Documentation
restorePreferences()
void PrefMaterialTreeWidget::restorePreferences () override protected virtual
Restores the preferences Must be reimplemented in any subclasses.
Implements Gui::PrefWidget.
Definition at line 777 of file MaterialTreeWidget.cpp.
References Gui::PrefWidget::entryName(), Gui::PrefWidget::failedToRestore(), Gui::WindowParameter::getWindowParameter(), draftgeoutils.general::isNull(), and MatGui::MaterialTreeWidget::setMaterial().
savePreferences()
void PrefMaterialTreeWidget::savePreferences () override protected virtual
Save the preferences Must be reimplemented in any subclasses.
Implements Gui::PrefWidget.
Definition at line 789 of file MaterialTreeWidget.cpp.
References Gui::PrefWidget::entryName(), Gui::PrefWidget::failedToSave(), MatGui::MaterialTreeWidget::getMaterialUUID(), Gui::WindowParameter::getWindowParameter(), draftgeoutils.general::isNull(), and ParameterGrp::SetASCII().
Property Documentation
prefEntry
QByteArray MatGui::PrefMaterialTreeWidget::prefEntry read write
Definition at line 298 of file MaterialTreeWidget.h.
prefPath
QByteArray MatGui::PrefMaterialTreeWidget::prefPath read write
Definition at line 300 of file MaterialTreeWidget.h.
The documentation for this class was generated from the following files:
MaterialTreeWidget.h
MaterialTreeWidget.cpp