FreeCAD: Gui::Dialog::IconDialog Class Reference
Gui::Dialog::IconDialog Class Reference
#include <DlgActionsImp.h>
Public Member Functions
IconDialog (QWidget *parent)
~IconDialog () override
void resizeEvent (QResizeEvent *) override
QListWidgetItem * currentItem () const
Detailed Description
Definition at line 98 of file DlgActionsImp.h.
Constructor & Destructor Documentation
IconDialog()
IconDialog::IconDialog (QWidget * parent) explicit
Definition at line 417 of file DlgActionsImp.cpp.
References Gui::BitmapFactory(), draftgeoutils.intersections::connect(), Gui::BitmapFactoryInst::findIconFiles(), and femtools.tokrules::names.
~IconDialog()
IconDialog::~IconDialog () override
Definition at line 437 of file DlgActionsImp.cpp.
Member Function Documentation
currentItem()
QListWidgetItem * IconDialog::currentItem () const
Definition at line 442 of file DlgActionsImp.cpp.
Referenced by Gui::Dialog::DlgCustomActionsImp::onButtonChoosePixmapClicked().
resizeEvent()
void IconDialog::resizeEvent (QResizeEvent *) override
Definition at line 447 of file DlgActionsImp.cpp.
The documentation for this class was generated from the following files:
DlgActionsImp.h
DlgActionsImp.cpp