FreeCAD: Part::OCAF::ImportExportSettings Class Reference
Part::OCAF::ImportExportSettings Class Reference
#include <ImportExportSettings.h>
Classes
struct CodePage
Public Types
enum ImportMode {
ImportMode::SingleDocument = 0, ImportMode::GroupPerDocument = 1, ImportMode::GroupPerDirectory = 2, ImportMode::ObjectPerDocument = 3,
ImportMode::ObjectPerDirectory = 4
}
Public Member Functions
ImportExportSettings ()
STEP::ImportExportSettingsPtr getSTEPSettings () const
IGES::ImportExportSettingsPtr getIGESSettings () const
void setReadShapeCompoundMode (bool)
bool getReadShapeCompoundMode () const
void setExportHiddenObject (bool)
bool getExportHiddenObject () const
void setImportHiddenObject (bool)
bool getImportHiddenObject () const
void setExportLegacy (bool)
bool getExportLegacy () const
void setExportKeepPlacement (bool)
bool getExportKeepPlacement () const
void setUseLinkGroup (bool)
bool getUseLinkGroup () const
void setUseBaseName (bool)
bool getUseBaseName () const
void setReduceObjects (bool)
bool getReduceObjects () const
void setExpandCompound (bool)
bool getExpandCompound () const
void setShowProgress (bool)
bool getShowProgress () const
void setImportMode (ImportMode)
ImportMode getImportMode () const
void setImportCodePage (int)
Resource_FormatType getImportCodePage () const
std::list< ImportExportSettings::CodePage > getCodePageList () const
Static Public Member Functions
static void initialize ()
Detailed Description
Definition at line 68 of file OCAF/ImportExportSettings.h.
Member Enumeration Documentation
ImportMode
enum Part::OCAF::ImportExportSettings::ImportMode strong
Enumerator
SingleDocument
GroupPerDocument
GroupPerDirectory
ObjectPerDocument
ObjectPerDirectory
Definition at line 71 of file OCAF/ImportExportSettings.h.
Constructor & Destructor Documentation
ImportExportSettings()
Part::OCAF::ImportExportSettings::ImportExportSettings ()
Definition at line 190 of file OCAF/ImportExportSettings.cpp.
References ParameterGrp::GetBool().
Member Function Documentation
getCodePageList()
std::list< ImportExportSettings::CodePage > Part::OCAF::ImportExportSettings::getCodePageList () const
Definition at line 162 of file OCAF/ImportExportSettings.cpp.
Referenced by PartGui::DlgImportStep::DlgImportStep().
getExpandCompound()
bool Part::OCAF::ImportExportSettings::getExpandCompound () const
Definition at line 300 of file OCAF/ImportExportSettings.cpp.
Referenced by Import::ImportOCAF2::customImportOptions(), PartGui::DlgImportStep::DlgImportStep(), and PartGui::DlgImportStep::getSettings().
getExportHiddenObject()
bool Part::OCAF::ImportExportSettings::getExportHiddenObject () const
Definition at line 230 of file OCAF/ImportExportSettings.cpp.
References ParameterGrp::GetBool().
Referenced by Import::ExportOCAF2::customExportOptions(), and PartGui::DlgExportStep::DlgExportStep().
getExportKeepPlacement()
bool Part::OCAF::ImportExportSettings::getExportKeepPlacement () const
Definition at line 260 of file OCAF/ImportExportSettings.cpp.
References ParameterGrp::GetBool().
Referenced by Import::ExportOCAF2::customExportOptions(), and PartGui::DlgExportStep::DlgExportStep().
getExportLegacy()
bool Part::OCAF::ImportExportSettings::getExportLegacy () const
Definition at line 250 of file OCAF/ImportExportSettings.cpp.
References ParameterGrp::GetBool().
Referenced by PartGui::DlgExportStep::DlgExportStep().
getIGESSettings()
IGES::ImportExportSettingsPtr Part::OCAF::ImportExportSettings::getIGESSettings () const
Definition at line 204 of file OCAF/ImportExportSettings.cpp.
References Part::on, and ParameterGrp::SetBool().
getImportCodePage()
Resource_FormatType Part::OCAF::ImportExportSettings::getImportCodePage () const
Definition at line 147 of file OCAF/ImportExportSettings.cpp.
Referenced by PartGui::DlgImportStep::getSettings().
getImportHiddenObject()
bool Part::OCAF::ImportExportSettings::getImportHiddenObject () const
Definition at line 240 of file OCAF/ImportExportSettings.cpp.
References ParameterGrp::GetBool().
Referenced by Import::ImportOCAF2::customImportOptions(), PartGui::DlgImportStep::DlgImportStep(), and PartGui::DlgImportStep::getSettings().
getImportMode()
ImportExportSettings::ImportMode Part::OCAF::ImportExportSettings::getImportMode () const
Definition at line 320 of file OCAF/ImportExportSettings.cpp.
Referenced by Import::ImportOCAF2::customImportOptions(), and PartGui::DlgImportStep::getSettings().
getReadShapeCompoundMode()
bool Part::OCAF::ImportExportSettings::getReadShapeCompoundMode () const
Definition at line 219 of file OCAF/ImportExportSettings.cpp.
References ParameterGrp::GetBool().
Referenced by Import::ImportOCAF2::customImportOptions(), PartGui::DlgImportStep::DlgImportStep(), and PartGui::DlgImportStep::getSettings().
getReduceObjects()
bool Part::OCAF::ImportExportSettings::getReduceObjects () const
Definition at line 290 of file OCAF/ImportExportSettings.cpp.
Referenced by Import::ImportOCAF2::customImportOptions(), PartGui::DlgImportStep::DlgImportStep(), and PartGui::DlgImportStep::getSettings().
getShowProgress()
bool Part::OCAF::ImportExportSettings::getShowProgress () const
Definition at line 310 of file OCAF/ImportExportSettings.cpp.
Referenced by Import::ImportOCAF2::customImportOptions(), PartGui::DlgImportStep::DlgImportStep(), and PartGui::DlgImportStep::getSettings().
getSTEPSettings()
STEP::ImportExportSettingsPtr Part::OCAF::ImportExportSettings::getSTEPSettings () const
Definition at line 195 of file OCAF/ImportExportSettings.cpp.
References Part::on, and ParameterGrp::SetBool().
getUseBaseName()
bool Part::OCAF::ImportExportSettings::getUseBaseName () const
Definition at line 280 of file OCAF/ImportExportSettings.cpp.
References ParameterGrp::GetInt().
Referenced by Import::ImportOCAF2::customImportOptions(), PartGui::DlgImportStep::DlgImportStep(), and PartGui::DlgImportStep::getSettings().
getUseLinkGroup()
bool Part::OCAF::ImportExportSettings::getUseLinkGroup () const
Definition at line 270 of file OCAF/ImportExportSettings.cpp.
References ParameterGrp::GetBool().
Referenced by Import::ImportOCAF2::customImportOptions(), PartGui::DlgImportStep::DlgImportStep(), and PartGui::DlgImportStep::getSettings().
initialize()
void Part::OCAF::ImportExportSettings::initialize () static
Definition at line 77 of file OCAF/ImportExportSettings.cpp.
References ParameterGrp::GetASCII(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), and ParameterGrp::GetInt().
Referenced by PyMOD_INIT_FUNC().
setExpandCompound()
void Part::OCAF::ImportExportSettings::setExpandCompound (bool on)
Definition at line 295 of file OCAF/ImportExportSettings.cpp.
setExportHiddenObject()
void Part::OCAF::ImportExportSettings::setExportHiddenObject (bool on)
Definition at line 225 of file OCAF/ImportExportSettings.cpp.
References Part::on, and ParameterGrp::SetBool().
setExportKeepPlacement()
void Part::OCAF::ImportExportSettings::setExportKeepPlacement (bool on)
Definition at line 255 of file OCAF/ImportExportSettings.cpp.
References Part::on, and ParameterGrp::SetBool().
setExportLegacy()
void Part::OCAF::ImportExportSettings::setExportLegacy (bool on)
Definition at line 245 of file OCAF/ImportExportSettings.cpp.
References Part::on, and ParameterGrp::SetBool().
setImportCodePage()
void Part::OCAF::ImportExportSettings::setImportCodePage (int cpIndex)
Definition at line 142 of file OCAF/ImportExportSettings.cpp.
setImportHiddenObject()
void Part::OCAF::ImportExportSettings::setImportHiddenObject (bool on)
Definition at line 235 of file OCAF/ImportExportSettings.cpp.
References Part::on, and ParameterGrp::SetBool().
setImportMode()
void Part::OCAF::ImportExportSettings::setImportMode (ImportExportSettings::ImportMode mode)
Definition at line 315 of file OCAF/ImportExportSettings.cpp.
setReadShapeCompoundMode()
void Part::OCAF::ImportExportSettings::setReadShapeCompoundMode (bool on)
Definition at line 213 of file OCAF/ImportExportSettings.cpp.
setReduceObjects()
void Part::OCAF::ImportExportSettings::setReduceObjects (bool on)
Definition at line 285 of file OCAF/ImportExportSettings.cpp.
setShowProgress()
void Part::OCAF::ImportExportSettings::setShowProgress (bool on)
Definition at line 305 of file OCAF/ImportExportSettings.cpp.
setUseBaseName()
void Part::OCAF::ImportExportSettings::setUseBaseName (bool on)
Definition at line 275 of file OCAF/ImportExportSettings.cpp.
References ParameterGrp::SetInt().
setUseLinkGroup()
void Part::OCAF::ImportExportSettings::setUseLinkGroup (bool on)
Definition at line 265 of file OCAF/ImportExportSettings.cpp.
References Part::on, and ParameterGrp::SetBool().
The documentation for this class was generated from the following files:
OCAF/ImportExportSettings.h
OCAF/ImportExportSettings.cpp