FreeCAD: Gui::PythonTextEditor Class Reference
Gui::PythonTextEditor Class Reference
#include <TextEdit.h>
Public Member Functions
PythonTextEditor (QWidget *parent=nullptr)
~PythonTextEditor () override
Public Member Functions inherited from Gui::TextEditor
TextEditor (QWidget *parent=nullptr)
~TextEditor () override
void setSyntaxHighlighter (SyntaxHighlighter *)
void OnChange (Base::Subject< const char * > &rCaller, const char *rcReason) override
void lineNumberAreaPaintEvent (QPaintEvent *)
int lineNumberAreaWidth ()
void setVisibleLineNumbers (bool value)
bool isVisibleLineNumbers () const
void setEnabledHighlightCurrentLine (bool value)
bool isEnabledHighlightCurrentLine () const
Public Member Functions inherited from Gui::TextEdit
TextEdit (QWidget *parent=nullptr)
~TextEdit () override
Public Member Functions inherited from Gui::WindowParameter
WindowParameter (const char *name)
~WindowParameter () override
void OnChange (Base::Subject< const char * > &rCaller, const char *sReason) override
ParameterGrp::handle getWindowParameter ()
return the parameter group of this window
Protected Member Functions
void keyPressEvent (QKeyEvent *) override
Protected Member Functions inherited from Gui::TextEditor
void resizeEvent (QResizeEvent *e) override
QWidget * getMarker () const
virtual void drawMarker (int line, int x, int y, QPainter *)
Protected Member Functions inherited from Gui::TextEdit
void keyPressEvent (QKeyEvent *) override
void wheelEvent (QWheelEvent *e) override
Protected Member Functions inherited from Gui::WindowParameter
bool setGroupName (const char *name)
template<typename S , typename T >
void setSlotParamChanged (S slot, T *obsPtr)
connect slot to ParameterManager signal
Additional Inherited Members
Signals inherited from Gui::TextEdit
void showSearchBar ()
void findNext ()
void findPrevious ()
Static Public Member Functions inherited from Gui::WindowParameter
static ParameterGrp::handle getDefaultParameter ()
get the parameters
Detailed Description
subclass of TextEditor that serves as base class for the python editor and the python console where we handle the tab key conversion to spaces, depending on user settings
Definition at line 147 of file Gui/TextEdit.h.
Constructor & Destructor Documentation
PythonTextEditor()
PythonTextEditor::PythonTextEditor (QWidget * parent = nullptr) explicit
Definition at line 448 of file Gui/TextEdit.cpp.
~PythonTextEditor()
PythonTextEditor::~PythonTextEditor () override default
Member Function Documentation
keyPressEvent()
void PythonTextEditor::keyPressEvent (QKeyEvent * e) override protected
Definition at line 456 of file Gui/TextEdit.cpp.
References SCL.SimpleDataTypes::e, ParameterGrp::GetBool(), ParameterGrp::GetInt(), Gui::WindowParameter::getWindowParameter(), SplineSurface::i, indent, Gui::TextEdit::keyPressEvent(), and RobotExample::pos.
Referenced by Gui::PythonEditor::keyPressEvent(), and Gui::PythonConsole::keyPressEvent().
The documentation for this class was generated from the following files:
Gui/TextEdit.h
Gui/TextEdit.cpp