FreeCAD: TechDrawGui::PaperAttributes Class Reference
TechDrawGui::PaperAttributes Class Reference
#include <PagePrinter.h>
Public Member Functions
PaperAttributes ()
PaperAttributes (QPageLayout::Orientation orientation, QPageSize::PageSizeId paperSize, double pageWidth, double pageHeight)
QPageLayout::Orientation orientation () const
QPageSize::PageSizeId pageSize () const
double pageWidth () const
double pageHeight () const
Detailed Description
Definition at line 50 of file PagePrinter.h.
Constructor & Destructor Documentation
PaperAttributes() [1/2]
PaperAttributes::PaperAttributes ()
Definition at line 438 of file PagePrinter.cpp.
References A4Heightmm, and A4Widthmm.
PaperAttributes() [2/2]
TechDrawGui::PaperAttributes::PaperAttributes (QPageLayout::Orientation orientation, QPageSize::PageSizeId paperSize, double pageWidth, double pageHeight) inline
Definition at line 54 of file PagePrinter.h.
Member Function Documentation
orientation()
QPageLayout::Orientation TechDrawGui::PaperAttributes::orientation () const inline
Definition at line 64 of file PagePrinter.h.
Referenced by TechDrawGui::PagePrinter::makePageLayout().
pageHeight()
double TechDrawGui::PaperAttributes::pageHeight () const inline
Definition at line 76 of file PagePrinter.h.
Referenced by TechDrawGui::PagePrinter::makePageLayout().
pageSize()
QPageSize::PageSizeId TechDrawGui::PaperAttributes::pageSize () const inline
Definition at line 68 of file PagePrinter.h.
Referenced by TechDrawGui::PagePrinter::makePageLayout().
pageWidth()
double TechDrawGui::PaperAttributes::pageWidth () const inline
Definition at line 72 of file PagePrinter.h.
Referenced by TechDrawGui::PagePrinter::makePageLayout().
The documentation for this class was generated from the following files:
PagePrinter.h
PagePrinter.cpp