FreeCAD: Gui::NavigationStyle Class Reference
Gui::NavigationStyle Class Reference
#include <NavigationStyle.h>
Public Types
enum ViewerMode {
IDLE, INTERACT, ZOOMING, BOXZOOM,
PANNING, DRAGGING, SPINNING, SEEK_WAIT_MODE,
SEEK_MODE, SELECTION
}
enum SelectionMode {
Lasso = 0, Rectangle = 1, Rubberband = 2, BoxZoom = 3,
Clip = 4
}
enum OrbitStyle { Turntable, Trackball, FreeTurntable }
enum RotationCenterMode { RotationCenterMode::WindowCenter = 0, RotationCenterMode::ScenePointAtCursor = 1, RotationCenterMode::FocalPointAtCursor = 2, RotationCenterMode::BoundingBoxCenter = 4 }
Public Member Functions
NavigationStyle ()
~NavigationStyle () override
NavigationStyle (const NavigationStyle &)=delete
NavigationStyle & operator= (const NavigationStyle &ns)
void setViewer (View3DInventorViewer *)
void setAnimationEnabled (const SbBool enable)
Decide if it should be possible to start any animation.
void setSpinningAnimationEnabled (const SbBool enable)
Decide if it should be possible to start a spin animation of the model in the viewer by releasing the mouse button while dragging.
SbBool isAnimationEnabled () const
SbBool isSpinningAnimationEnabled () const
SbBool isAnimating () const
SbBool isSpinning () const
void startAnimating (const std::shared_ptr< NavigationAnimation > &animation, bool wait=false) const
void stopAnimating () const
void setSensitivity (float)
float getSensitivity () const
void setResetCursorPosition (SbBool)
SbBool isResetCursorPosition () const
void setZoomInverted (SbBool)
SbBool isZoomInverted () const
void setZoomStep (float)
void setZoomAtCursor (SbBool)
SbBool isZoomAtCursor () const
void zoomIn ()
void zoomOut ()
void setRotationCenterMode (RotationCenterModes)
RotationCenterModes getRotationCenterMode () const
void setRotationCenter (const SbVec3f &cnt)
SbVec3f getFocalPoint () const
SoCamera * getCamera () const
void setCameraOrientation (const SbRotation &orientation, SbBool moveToCenter=false)
void translateCamera (const SbVec3f &translation)
void findBoundingSphere ()
void reorientCamera (SoCamera *camera, const SbRotation &rotation)
void reorientCamera (SoCamera *camera, const SbRotation &rotation, const SbVec3f &rotationCenter)
void boxZoom (const SbBox2s &box)
virtual void viewAll ()
void setViewingMode (const ViewerMode newmode)
int getViewingMode () const
virtual SbBool processEvent (const SoEvent *const ev)
virtual SbBool processMotionEvent (const SoMotion3Event *const ev)
virtual SbBool processKeyboardEvent (const SoKeyboardEvent *const event)
virtual SbBool processClickEvent (const SoMouseButtonEvent *const event)
virtual SbBool processWheelEvent (const SoMouseWheelEvent *const event)
void setPopupMenuEnabled (const SbBool on)
SbBool isPopupMenuEnabled () const
void startSelection (AbstractMouseSelection *)
void startSelection (SelectionMode=Lasso)
void abortSelection ()
void stopSelection ()
SbBool isSelecting () const
const std::vector< SbVec2s > & getPolygon (SelectionRole *role=nullptr) const
void setOrbitStyle (OrbitStyle style)
OrbitStyle getOrbitStyle () const
SbBool isViewing () const
void setViewing (SbBool)
SbVec3f getRotationCenter (SbBool &) const
PyObject * getPyObject () override
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Member Functions
void initialize ()
void finalize ()
void interactiveCountInc ()
void interactiveCountDec ()
int getInteractiveCount () const
SbBool isSeekMode () const
void setSeekMode (SbBool enable)
SbBool seekToPoint (const SbVec2s screenpos)
void seekToPoint (const SbVec3f &scenepos)
void lookAtPoint (const SbVec2s screenpos)
void lookAtPoint (const SbVec3f &position)
void panCamera (SoCamera *camera, float vpaspect, const SbPlane &panplane, const SbVec2f &previous, const SbVec2f &current)
void setupPanningPlane (const SoCamera *camera)
int getDelta () const
void zoom (SoCamera *camera, float diffvalue)
void zoomByCursor (const SbVec2f &thispos, const SbVec2f &prevpos)
void doZoom (SoCamera *camera, int wheeldelta, const SbVec2f &pos)
void doZoom (SoCamera *camera, float logzoomfactor, const SbVec2f &pos)
NavigationStyle::doZoom Zooms in or out by specified factor, keeping the point on screen specified by parameter pos fixed or not according to user preference (NavigationStyle::zoomAtCursor). Ignores invertZoom user preference.
void doRotate (SoCamera *camera, float angle, const SbVec2f &pos)
void spin (const SbVec2f &pointerpos)
SbBool doSpin ()
void spin_simplified (SoCamera *cam, SbVec2f curpos, SbVec2f prevpos)
NavigationStyle::spin_simplified is a simplified version of NavigationStyle::spin(..), which uses less global variables. Doesn't support starting an animated spinning.
void moveCursorPosition ()
void saveCursorPosition (const SoEvent *const ev)
SbVec2f normalizePixelPos (SbVec2s pixpos)
SbVec2f normalizePixelPos (SbVec2f pixpos)
SbBool handleEventInForeground (const SoEvent *const e)
virtual SbBool processSoEvent (const SoEvent *const ev)
void syncWithEvent (const SoEvent *const ev)
virtual void openPopupMenu (const SbVec2s &position)
void clearLog ()
void addToLog (const SbVec2s pos, const SbTime time)
void syncModifierKeys (const SoEvent *const ev)
Protected Attributes
struct {
short size
short historysize
SbVec2s * position
SbTime * time
} log
View3DInventorViewer * viewer {nullptr}
NavigationAnimator * animator
SbBool animationEnabled
ViewerMode currentmode
SoMouseButtonEvent mouseDownConsumedEvent
SbVec2f lastmouseposition
SbVec2s globalPos
SbVec2s localPos
SbPlane panningplane
SbTime centerTime
SbBool lockrecenter
SbBool menuenabled
SbBool ctrldown
SbBool shiftdown
SbBool altdown
SbBool button1down
SbBool button2down
SbBool button3down
SbBool invertZoom
SbBool zoomAtCursor
float zoomStep
SbBool hasDragged
SbBool hasPanned
SbBool hasZoomed
Mouse model
AbstractMouseSelection * mouseSelection {nullptr}
std::vector< SbVec2s > pcPolygon
SelectionRole selectedRole
Spinning data
SbBool spinningAnimationEnabled
int spinsamplecounter
SbRotation spinincrement
SbSphereSheetProjector * spinprojector
PyObject * pythonObject
class NavigationAnimator
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
The navigation style base class
Author
Werner Mayer
Definition at line 77 of file NavigationStyle.h.
Member Enumeration Documentation
OrbitStyle
enum Gui::NavigationStyle::OrbitStyle
Enumerator
Turntable
Trackball
FreeTurntable
Definition at line 103 of file NavigationStyle.h.
RotationCenterMode
enum Gui::NavigationStyle::RotationCenterMode strong
Enumerator
WindowCenter
The center of the window
ScenePointAtCursor
Find the point in the scene at the cursor position. If there is no point then the focal plane is used
FocalPointAtCursor
Find the point on the focal plane at the cursor position.
BoundingBoxCenter
Find the center point of the bounding box of the scene.
Definition at line 109 of file NavigationStyle.h.
SelectionMode
enum Gui::NavigationStyle::SelectionMode
Enumerator
Lasso
Select objects using a lasso.
Rectangle
Select objects using a rectangle.
Rubberband
Select objects using a rubberband.
BoxZoom
Perform a box zoom.
Clip
Clip objects using a lasso.
Definition at line 95 of file NavigationStyle.h.
ViewerMode
enum Gui::NavigationStyle::ViewerMode
Enumerator
IDLE
INTERACT
ZOOMING
BOXZOOM
PANNING
DRAGGING
SPINNING
SEEK_WAIT_MODE
SEEK_MODE
SELECTION
Definition at line 82 of file NavigationStyle.h.
Constructor & Destructor Documentation
NavigationStyle() [1/2]
NavigationStyle::NavigationStyle ()
Definition at line 183 of file NavigationStyle.cpp.
References FocalPointAtCursor, and ScenePointAtCursor.
~NavigationStyle()
NavigationStyle::~NavigationStyle () override
Definition at line 190 of file NavigationStyle.cpp.
References animator, finalize(), and pythonObject.
NavigationStyle() [2/2]
Gui::NavigationStyle::NavigationStyle (const NavigationStyle &) delete
Member Function Documentation
abortSelection()
void NavigationStyle::abortSelection ()
Definition at line 1338 of file NavigationStyle.cpp.
References mouseSelection, pcPolygon, and Gui::AbstractMouseSelection::releaseMouseModel().
Referenced by Gui::View3DInventorViewer::abortSelection().
addToLog()
void NavigationStyle::addToLog (const SbVec2s pos, const SbTime time) protected
Definition at line 1372 of file NavigationStyle.cpp.
References SplineSurface::i, log, RobotExample::pos, and time.
Referenced by Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::TouchpadNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), and Gui::TinkerCADNavigationStyle::processSoEvent().
boxZoom()
void NavigationStyle::boxZoom (const SbBox2s & box)
Definition at line 447 of file NavigationStyle.cpp.
References KDL::atan(), MengerSponge::box, exportCSG::center(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), KDL::max(), panCamera(), WorkingPlane::plane, draftfunctions.scale::scale(), size, KDL::tan(), and viewer.
Referenced by Gui::View3DInventorViewer::boxZoom().
clearLog()
void NavigationStyle::clearLog () protected
Definition at line 1400 of file NavigationStyle.cpp.
References log.
Referenced by setViewingMode().
doRotate()
void NavigationStyle::doRotate (SoCamera * camera, float angle, const SbVec2f & pos) protected
Definition at line 808 of file NavigationStyle.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), panCamera(), RobotExample::pos, viewer, and zoomAtCursor.
Referenced by Gui::MayaGestureNavigationStyle::processSoEvent().
doSpin()
SbBool NavigationStyle::doSpin () protected
Definition at line 1018 of file NavigationStyle.cpp.
References SCL.SimpleDataTypes::f, SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), isSpinningAnimationEnabled(), lastmouseposition, log, KDL::max(), spinprojector, Gui::View3DInventorViewer::startSpinningAnimation(), and viewer.
Referenced by Gui::InventorNavigationStyle::processSoEvent(), and Gui::CADNavigationStyle::processSoEvent().
doZoom() [1/2]
void NavigationStyle::doZoom (SoCamera * camera, float logzoomfactor, const SbVec2f & pos) protected
NavigationStyle::doZoom Zooms in or out by specified factor, keeping the point on screen specified by parameter pos fixed or not according to user preference (NavigationStyle::zoomAtCursor). Ignores invertZoom user preference.
Definition at line 772 of file NavigationStyle.cpp.
References Gui::View3DInventorViewer::changeRotationCenterPosition(), findBoundingSphere(), getFocalPoint(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), panCamera(), RobotExample::pos, viewer, zoom(), and zoomAtCursor.
doZoom() [2/2]
void NavigationStyle::doZoom (SoCamera * camera, int wheeldelta, const SbVec2f & pos) protected
Definition at line 760 of file NavigationStyle.cpp.
References getDelta(), invertZoom, RobotExample::pos, and zoomStep.
Referenced by processKeyboardEvent(), Gui::MayaGestureNavigationStyle::processSoEvent(), and processWheelEvent().
finalize()
void NavigationStyle::finalize () protected
Definition at line 277 of file NavigationStyle.cpp.
References log, and spinprojector.
Referenced by Gui::MayaGestureNavigationStyle::processSoEvent(), draftguitools.gui_trackers.ghostTracker::remove(), and ~NavigationStyle().
findBoundingSphere()
void NavigationStyle::findBoundingSphere ()
Definition at line 531 of file NavigationStyle.cpp.
References Path.Post.scripts.dynapath_4060_post::action, SIM::Coin3D::Quarter::QuarterWidget::getSceneGraph(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), and viewer.
Referenced by doZoom(), Gui::View3DInventorViewer::setEditingViewProvider(), Gui::View3DInventorViewer::setSceneGraph(), and setViewingMode().
getCamera()
SoCamera * NavigationStyle::getCamera () const
Definition at line 384 of file NavigationStyle.cpp.
References SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getCamera(), and viewer.
Referenced by Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), Gui::TinkerCADNavigationStyle::processSoEvent(), setCameraOrientation(), and translateCamera().
getDelta()
int NavigationStyle::getDelta () const protected
Returns the steps if the mouse wheel is rotated
Definition at line 755 of file NavigationStyle.cpp.
Referenced by doZoom(), bimcommands.BimLibrary.BIM_Library_TaskPanel::mouseClick(), bimcommands.BimLibrary.BIM_Library_TaskPanel::mouseMove(), processKeyboardEvent(), and Gui::MayaGestureNavigationStyle::processSoEvent().
getFocalPoint()
SbVec3f NavigationStyle::getFocalPoint () const
Definition at line 849 of file NavigationStyle.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), and viewer.
Referenced by doZoom(), lookAtPoint(), Gui::MayaGestureNavigationStyle::processSoEvent(), reorientCamera(), saveCursorPosition(), and setCameraOrientation().
getInteractiveCount()
int NavigationStyle::getInteractiveCount () const protected
Definition at line 294 of file NavigationStyle.cpp.
References SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getInteractiveCount(), and viewer.
getOrbitStyle()
NavigationStyle::OrbitStyle NavigationStyle::getOrbitStyle () const
Definition at line 305 of file NavigationStyle.cpp.
References spinprojector.
Referenced by spin().
getPolygon()
const std::vector< SbVec2s > & NavigationStyle::getPolygon (SelectionRole * role = nullptr) const
Definition at line 1363 of file NavigationStyle.cpp.
References pcPolygon, and selectedRole.
Referenced by Gui::View3DInventorViewer::getGLPolygon(), and Gui::View3DInventorViewer::getPolygon().
getPyObject()
PyObject * NavigationStyle::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Definition at line 1804 of file NavigationStyle.cpp.
References pythonObject.
Referenced by Gui::View3DInventorViewerPy::getNavigationStyle().
getRotationCenter()
SbVec3f NavigationStyle::getRotationCenter (SbBool & found) const
Definition at line 837 of file NavigationStyle.cpp.
Referenced by Gui::View3DInventorViewer::showRotationCenter().
getRotationCenterMode()
NavigationStyle::RotationCenterModes NavigationStyle::getRotationCenterMode () const
Definition at line 1287 of file NavigationStyle.cpp.
getSensitivity()
float NavigationStyle::getSensitivity () const
Definition at line 1242 of file NavigationStyle.cpp.
Referenced by spin(), and spin_simplified().
getViewingMode()
int NavigationStyle::getViewingMode () const
Definition at line 1501 of file NavigationStyle.cpp.
References currentmode.
Referenced by Gui::View3DInventorViewer::afterRealizeHook(), and Gui::View3DInventorViewer::setCursorEnabled().
handleEventInForeground()
SbBool NavigationStyle::handleEventInForeground (const SoEvent *const e) protected
Definition at line 1155 of file NavigationStyle.cpp.
References Path.Post.scripts.dynapath_4060_post::action, SCL.SimpleDataTypes::e, SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getPickRadius(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), and viewer.
Referenced by Gui::GestureNavigationStyle::processSoEvent(), Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::MayaGestureNavigationStyle::processSoEvent(), Gui::TouchpadNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), and Gui::TinkerCADNavigationStyle::processSoEvent().
initialize()
void NavigationStyle::initialize () protected
Definition at line 218 of file NavigationStyle.cpp.
References altdown, animationEnabled, animator, BoundingBoxCenter, button1down, button2down, button3down, ctrldown, currentmode, FCSphereSheetProjector::defaultSphereRadius, SCL.SimpleDataTypes::f, FocalPointAtCursor, App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetFloat(), ParameterGrp::GetInt(), App::Application::GetParameterGroupByPath(), hasDragged, hasPanned, hasZoomed, IDLE, invertZoom, log, menuenabled, NavigationAnimator, ScenePointAtCursor, setRotationCenterMode(), shiftdown, spinincrement, spinningAnimationEnabled, spinprojector, spinsamplecounter, WindowCenter, zoomAtCursor, and zoomStep.
interactiveCountDec()
void NavigationStyle::interactiveCountDec () protected
Definition at line 289 of file NavigationStyle.cpp.
References SIM::Coin3D::Quarter::SoQTQuarterAdaptor::interactiveCountDec(), and viewer.
Referenced by setViewingMode().
interactiveCountInc()
void NavigationStyle::interactiveCountInc () protected
Definition at line 284 of file NavigationStyle.cpp.
References SIM::Coin3D::Quarter::SoQTQuarterAdaptor::interactiveCountInc(), and viewer.
Referenced by setViewingMode().
isAnimating()
SbBool NavigationStyle::isAnimating () const
Returns
Whether or not any animation is currently active
Definition at line 1209 of file NavigationStyle.cpp.
References animator, and Gui::NavigationAnimator::isAnimating().
Referenced by Gui::View3DInventorViewer::isAnimating(), Gui::GestureNavigationStyle::processSoEvent(), Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::MayaGestureNavigationStyle::processSoEvent(), Gui::TouchpadNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), Gui::TinkerCADNavigationStyle::processSoEvent(), and setAnimationEnabled().
isAnimationEnabled()
SbBool NavigationStyle::isAnimationEnabled () const
Returns
Whether or not it is possible to start any animation
Definition at line 1193 of file NavigationStyle.cpp.
References animationEnabled.
Referenced by Gui::View3DInventorViewer::isAnimationEnabled(), setCameraOrientation(), and translateCamera().
isPopupMenuEnabled()
SbBool NavigationStyle::isPopupMenuEnabled () const
Definition at line 1758 of file NavigationStyle.cpp.
References menuenabled.
Referenced by Gui::View3DInventorViewer::isPopupMenuEnabled(), Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::MayaGestureNavigationStyle::processSoEvent(), Gui::TouchpadNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), and Gui::TinkerCADNavigationStyle::processSoEvent().
isResetCursorPosition()
SbBool NavigationStyle::isResetCursorPosition () const
Definition at line 1252 of file NavigationStyle.cpp.
Referenced by moveCursorPosition().
isSeekMode()
SbBool NavigationStyle::isSeekMode () const protected
Definition at line 321 of file NavigationStyle.cpp.
References SIM::Coin3D::Quarter::SoQTQuarterAdaptor::isSeekMode(), and viewer.
Referenced by Gui::GestureNavigationStyle::processSoEvent(), Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::MayaGestureNavigationStyle::processSoEvent(), Gui::TouchpadNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), Gui::TinkerCADNavigationStyle::processSoEvent(), and syncWithEvent().
isSelecting()
SbBool NavigationStyle::isSelecting () const
Definition at line 1358 of file NavigationStyle.cpp.
References mouseSelection.
Referenced by Gui::View3DInventorViewer::isSelecting(), and startSelection().
isSpinning()
SbBool NavigationStyle::isSpinning () const
Returns
Whether or not a spinning animation is currently active e.g. after a user drag
Definition at line 1217 of file NavigationStyle.cpp.
References currentmode, and SPINNING.
Referenced by Gui::View3DInventorViewer::isSpinning(), and setSpinningAnimationEnabled().
isSpinningAnimationEnabled()
SbBool NavigationStyle::isSpinningAnimationEnabled () const
Returns
Whether or not it is possible to start a spinning animation e.g. after dragging
Definition at line 1201 of file NavigationStyle.cpp.
References animationEnabled, and spinningAnimationEnabled.
Referenced by doSpin(), and Gui::View3DInventorViewer::isSpinningAnimationEnabled().
isViewing()
SbBool NavigationStyle::isViewing () const
Definition at line 311 of file NavigationStyle.cpp.
References SIM::Coin3D::Quarter::SoQTQuarterAdaptor::isViewing(), and viewer.
Referenced by processKeyboardEvent(), Gui::GestureNavigationStyle::processSoEvent(), Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::MayaGestureNavigationStyle::processSoEvent(), Gui::TouchpadNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), and Gui::TinkerCADNavigationStyle::processSoEvent().
isZoomAtCursor()
SbBool NavigationStyle::isZoomAtCursor () const
Definition at line 1277 of file NavigationStyle.cpp.
References zoomAtCursor.
isZoomInverted()
SbBool NavigationStyle::isZoomInverted () const
Definition at line 1262 of file NavigationStyle.cpp.
References invertZoom.
lookAtPoint() [1/2]
void NavigationStyle::lookAtPoint (const SbVec2s screenpos) protected
Definition at line 341 of file NavigationStyle.cpp.
References SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getCamera(), SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getPickRadius(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getViewportRegion(), normalizePixelPos(), panningplane, updateLeaderLines::point, and viewer.
Referenced by Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), and Gui::MayaGestureNavigationStyle::processSoEvent().
lookAtPoint() [2/2]
void NavigationStyle::lookAtPoint (const SbVec3f & position) protected
Definition at line 378 of file NavigationStyle.cpp.
References getFocalPoint(), position, and translateCamera().
moveCursorPosition()
void NavigationStyle::moveCursorPosition () protected
Definition at line 1141 of file NavigationStyle.cpp.
References KDL::abs(), globalPos, isResetCursorPosition(), localPos, log, and RobotExample::pos.
Referenced by Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::TouchpadNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), and Gui::TinkerCADNavigationStyle::processSoEvent().
normalizePixelPos() [1/2]
SbVec2f NavigationStyle::normalizePixelPos (SbVec2f pixpos) protected
Definition at line 1133 of file NavigationStyle.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), KDL::max(), size, and viewer.
normalizePixelPos() [2/2]
SbVec2f NavigationStyle::normalizePixelPos (SbVec2s pixpos) protected
Definition at line 1125 of file NavigationStyle.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), KDL::max(), size, and viewer.
Referenced by lookAtPoint(), processKeyboardEvent(), Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::MayaGestureNavigationStyle::processSoEvent(), Gui::TouchpadNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), Gui::TinkerCADNavigationStyle::processSoEvent(), processWheelEvent(), and spin().
openPopupMenu()
void NavigationStyle::openPopupMenu (const SbVec2s & position) protected virtual
Definition at line 1763 of file NavigationStyle.cpp.
References SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getGLWidget(), Gui::MenuManager::getInstance(), Gui::UserNavigationStyle::getUserFriendlyNames(), SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getWidget(), Gui::Application::Instance, RobotExample::pos, position, Gui::MenuManager::setupContextMenu(), Gui::Application::setupContextMenu(), src.Mod.AddonManager.Addon::translate, and viewer.
Referenced by Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::MayaGestureNavigationStyle::processSoEvent(), Gui::TouchpadNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), and Gui::TinkerCADNavigationStyle::processSoEvent().
operator=()
NavigationStyle & NavigationStyle::operator= (const NavigationStyle & ns)
Definition at line 202 of file NavigationStyle.cpp.
References animationEnabled, FCSphereSheetProjector::getOrbitStyle(), menuenabled, panningplane, setOrbitStyle(), spinningAnimationEnabled, and spinprojector.
panCamera()
void NavigationStyle::panCamera (SoCamera * camera, float vpaspect, const SbPlane & panplane, const SbVec2f & previous, const SbVec2f & current) protected
Definition at line 592 of file NavigationStyle.cpp.
References currentmode, hasPanned, and IDLE.
Referenced by boxZoom(), doRotate(), doZoom(), Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::MayaGestureNavigationStyle::processSoEvent(), Gui::TouchpadNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), Gui::TinkerCADNavigationStyle::processSoEvent(), spin(), and spin_simplified().
processClickEvent()
SbBool NavigationStyle::processClickEvent (const SoMouseButtonEvent *const event) virtual
Definition at line 1709 of file NavigationStyle.cpp.
References mouseDownConsumedEvent, and processSoEvent().
Referenced by Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::TouchpadNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), and Gui::TinkerCADNavigationStyle::processSoEvent().
processEvent()
SbBool NavigationStyle::processEvent (const SoEvent *const ev) virtual
Definition at line 1506 of file NavigationStyle.cpp.
References Gui::AbstractMouseSelection::Cancel, Gui::SelectionSingleton::clearSelection(), Gui::AbstractMouseSelection::Continue, currentmode, Gui::AbstractMouseSelection::Finish, Gui::AbstractMouseSelection::getPositions(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), Gui::AbstractMouseSelection::handleEvent(), IDLE, mouseSelection, pcPolygon, processSoEvent(), Gui::AbstractMouseSelection::Restart, Gui::AbstractMouseSelection::selectedRole(), selectedRole, SELECTION, Gui::Selection(), syncWithEvent(), and viewer.
Referenced by Gui::View3DInventorViewer::processSoEvent().
processKeyboardEvent()
SbBool NavigationStyle::processKeyboardEvent (const SoKeyboardEvent *const event) virtual
Definition at line 1662 of file NavigationStyle.cpp.
References altdown, ctrldown, doZoom(), getDelta(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), isViewing(), normalizePixelPos(), setViewing(), shiftdown, and viewer.
Referenced by Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::TouchpadNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), and Gui::TinkerCADNavigationStyle::processSoEvent().
processMotionEvent()
SbBool NavigationStyle::processMotionEvent (const SoMotion3Event *const ev) virtual
Definition at line 1631 of file NavigationStyle.cpp.
References exportCSG::center(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), draftfunctions.scale::scale(), and viewer.
Referenced by Gui::GestureNavigationStyle::processSoEvent(), Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::MayaGestureNavigationStyle::processSoEvent(), Gui::TouchpadNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), and Gui::TinkerCADNavigationStyle::processSoEvent().
processSoEvent()
SbBool NavigationStyle::processSoEvent (const SoEvent *const ev) protected virtual
Reimplemented in Gui::TinkerCADNavigationStyle, Gui::OpenSCADNavigationStyle, Gui::OpenCascadeNavigationStyle, Gui::TouchpadNavigationStyle, Gui::MayaGestureNavigationStyle, Gui::BlenderNavigationStyle, Gui::RevitNavigationStyle, Gui::CADNavigationStyle, Gui::InventorNavigationStyle, and Gui::GestureNavigationStyle.
Definition at line 1551 of file NavigationStyle.cpp.
References Gui::View3DInventorViewer::processSoEventBase(), processWheelEvent(), and viewer.
Referenced by processClickEvent(), processEvent(), Gui::GestureNavigationStyle::processSoEvent(), Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::MayaGestureNavigationStyle::processSoEvent(), Gui::TouchpadNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), Gui::TinkerCADNavigationStyle::processSoEvent(), and Gui::GestureNavigationStyle::processSoEvent_bypass().
processWheelEvent()
SbBool NavigationStyle::processWheelEvent (const SoMouseWheelEvent *const event) virtual
Definition at line 1742 of file NavigationStyle.cpp.
References doZoom(), SoMouseWheelEvent::getDelta(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), normalizePixelPos(), RobotExample::pos, and viewer.
Referenced by processSoEvent().
reorientCamera() [1/2]
void NavigationStyle::reorientCamera (SoCamera * camera, const SbRotation & rotation)
Rotate the camera by the given amount, then reposition it so we're still pointing at the same focal point
Definition at line 542 of file NavigationStyle.cpp.
References getFocalPoint().
Referenced by spin(), and spin_simplified().
reorientCamera() [2/2]
void NavigationStyle::reorientCamera (SoCamera * camera, const SbRotation & rotation, const SbVec3f & rotationCenter)
Rotate the camera by the given amount, then reposition it so the rotation center stays in the same place
Definition at line 550 of file NavigationStyle.cpp.
References exportCSG::center().
saveCursorPosition()
void NavigationStyle::saveCursorPosition (const SoEvent *const ev) protected
Definition at line 1048 of file NavigationStyle.cpp.
References Path.Post.scripts.dynapath_4060_post::action, BoundingBoxCenter, FocalPointAtCursor, getFocalPoint(), SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getPickRadius(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), globalPos, localPos, RobotExample::pos, ScenePointAtCursor, setRotationCenter(), size, viewer, MovieTool::x, and MovieTool::y.
Referenced by Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::MayaGestureNavigationStyle::processSoEvent(), Gui::TouchpadNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), and Gui::TinkerCADNavigationStyle::processSoEvent().
seekToPoint() [1/2]
SbBool NavigationStyle::seekToPoint (const SbVec2s screenpos) protected
Definition at line 331 of file NavigationStyle.cpp.
References SIM::Coin3D::Quarter::SoQTQuarterAdaptor::seekToPoint(), and viewer.
Referenced by Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::MayaGestureNavigationStyle::processSoEvent(), Gui::TouchpadNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), and Gui::TinkerCADNavigationStyle::processSoEvent().
seekToPoint() [2/2]
void NavigationStyle::seekToPoint (const SbVec3f & scenepos) protected
Definition at line 336 of file NavigationStyle.cpp.
References SIM::Coin3D::Quarter::SoQTQuarterAdaptor::seekToPoint(), and viewer.
setAnimationEnabled()
void NavigationStyle::setAnimationEnabled (const SbBool enable)
Decide if it should be possible to start any animation.
If the enable flag is false and we're currently animating, the animation will be stopped
Definition at line 1169 of file NavigationStyle.cpp.
References animationEnabled, animator, isAnimating(), and Gui::NavigationAnimator::stop().
Referenced by Gui::View3DInventorViewer::setAnimationEnabled().
setCameraOrientation()
void NavigationStyle::setCameraOrientation (const SbRotation & orientation, SbBool moveToCenter = false)
Definition at line 389 of file NavigationStyle.cpp.
References Path.Post.scripts.dynapath_4060_post::action, animator, MengerSponge::box, getCamera(), getFocalPoint(), SIM::Coin3D::Quarter::QuarterWidget::getSceneGraph(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), isAnimationEnabled(), Gui::View3DInventorViewer::startAnimation(), Gui::NavigationAnimator::stop(), and viewer.
Referenced by Gui::View3DInventorViewer::setCameraOrientation().
setOrbitStyle()
void NavigationStyle::setOrbitStyle (NavigationStyle::OrbitStyle style)
Definition at line 299 of file NavigationStyle.cpp.
References FCSphereSheetProjector::setOrbitStyle(), and spinprojector.
Referenced by operator=().
setPopupMenuEnabled()
void NavigationStyle::setPopupMenuEnabled (const SbBool on)
Definition at line 1753 of file NavigationStyle.cpp.
References menuenabled.
Referenced by Gui::View3DInventorViewer::setPopupMenuEnabled().
setResetCursorPosition()
void NavigationStyle::setResetCursorPosition (SbBool on)
Definition at line 1247 of file NavigationStyle.cpp.
setRotationCenter()
void NavigationStyle::setRotationCenter (const SbVec3f & cnt)
Definition at line 843 of file NavigationStyle.cpp.
Referenced by Gui::MayaGestureNavigationStyle::processSoEvent(), and saveCursorPosition().
setRotationCenterMode()
void NavigationStyle::setRotationCenterMode (RotationCenterModes)
Definition at line 1282 of file NavigationStyle.cpp.
Referenced by initialize().
setSeekMode()
void NavigationStyle::setSeekMode (SbBool enable) protected
Definition at line 326 of file NavigationStyle.cpp.
References Gui::View3DInventorViewer::setSeekMode(), and viewer.
setSensitivity()
void NavigationStyle::setSensitivity (float val)
Definition at line 1237 of file NavigationStyle.cpp.
References toolbit-attributes::val.
setSpinningAnimationEnabled()
void NavigationStyle::setSpinningAnimationEnabled (const SbBool enable)
Decide if it should be possible to start a spin animation of the model in the viewer by releasing the mouse button while dragging.
If the enable flag is false and we're currently animating, the spin animation will be stopped
Definition at line 1182 of file NavigationStyle.cpp.
References animator, isSpinning(), spinningAnimationEnabled, and Gui::NavigationAnimator::stop().
Referenced by Gui::View3DInventorViewer::setSpinningAnimationEnabled().
setupPanningPlane()
void NavigationStyle::setupPanningPlane (const SoCamera * camera) protected
Definition at line 625 of file NavigationStyle.cpp.
References SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getViewportRegion(), panningplane, and viewer.
Referenced by Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::MayaGestureNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), Gui::TinkerCADNavigationStyle::processSoEvent(), and setViewingMode().
setViewer()
void NavigationStyle::setViewer (View3DInventorViewer * view)
Definition at line 213 of file NavigationStyle.cpp.
References viewer.
Referenced by Gui::View3DInventorViewer::setNavigationType().
setViewing()
void NavigationStyle::setViewing (SbBool enable)
Definition at line 316 of file NavigationStyle.cpp.
References Gui::View3DInventorViewer::setViewing(), and viewer.
Referenced by processKeyboardEvent(), Gui::GestureNavigationStyle::processSoEvent(), Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::MayaGestureNavigationStyle::processSoEvent(), Gui::TouchpadNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), and Gui::TinkerCADNavigationStyle::processSoEvent().
setViewingMode()
void NavigationStyle::setViewingMode (const ViewerMode newmode)
Definition at line 1422 of file NavigationStyle.cpp.
References animator, BOXZOOM, Gui::View3DInventorViewer::changeRotationCenterPosition(), clearLog(), currentmode, DRAGGING, findBoundingSphere(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), hasDragged, hasPanned, hasZoomed, IDLE, interactiveCountDec(), interactiveCountInc(), lastmouseposition, PANNING, setupPanningPlane(), Gui::View3DInventorViewer::showRotationCenter(), SPINNING, spinprojector, Gui::NavigationAnimator::stop(), viewer, and ZOOMING.
Referenced by Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::MayaGestureNavigationStyle::processSoEvent(), Gui::TouchpadNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), Gui::TinkerCADNavigationStyle::processSoEvent(), Gui::View3DInventorViewer::setSeekMode(), and Gui::View3DInventorViewer::setViewing().
setZoomAtCursor()
void NavigationStyle::setZoomAtCursor (SbBool on)
Definition at line 1272 of file NavigationStyle.cpp.
References zoomAtCursor.
setZoomInverted()
void NavigationStyle::setZoomInverted (SbBool on)
Definition at line 1257 of file NavigationStyle.cpp.
References invertZoom.
setZoomStep()
void NavigationStyle::setZoomStep (float val)
Definition at line 1267 of file NavigationStyle.cpp.
References toolbit-attributes::val, and zoomStep.
spin()
void NavigationStyle::spin (const SbVec2f & pointerpos) protected
Uses the sphere sheet projector to map the mouse position onto a 3D point and find a rotation from this and the last calculated point.
Definition at line 866 of file NavigationStyle.cpp.
References currentmode, FCSphereSheetProjector::defaultSphereRadius, SCL.SimpleDataTypes::f, getOrbitStyle(), Gui::View3DInventorViewer::getPointOnViewport(), getSensitivity(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), hasDragged, IDLE, localPos, log, KDL::max(), normalizePixelPos(), panCamera(), reorientCamera(), ScenePointAtCursor, spinincrement, spinprojector, spinsamplecounter, Trackball, viewer, MovieTool::x, and MovieTool::y.
Referenced by Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::TouchpadNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), and Gui::TinkerCADNavigationStyle::processSoEvent().
spin_simplified()
void NavigationStyle::spin_simplified (SoCamera * cam, SbVec2f curpos, SbVec2f prevpos) protected
NavigationStyle::spin_simplified is a simplified version of NavigationStyle::spin(..), which uses less global variables. Doesn't support starting an animated spinning.
Parameters
cam the camera to affect. The rotation amount is determined by delta (curpos-prevpos), and rotation axis is also affected by average pos.
curpos current normalized position or mouse pointer
prevpos previous normalized position of mouse pointer
Definition at line 970 of file NavigationStyle.cpp.
References SCL.SimpleDataTypes::f, getSensitivity(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), hasDragged, localPos, KDL::max(), panCamera(), reorientCamera(), spinprojector, and viewer.
Referenced by Gui::MayaGestureNavigationStyle::processSoEvent().
startAnimating()
void NavigationStyle::startAnimating (const std::shared_ptr< NavigationAnimation > & animation, bool wait = false) const
Definition at line 1222 of file NavigationStyle.cpp.
References animator, Gui::NavigationAnimator::start(), and Gui::NavigationAnimator::startAndWait().
Referenced by Gui::View3DInventorViewer::startAnimation(), and Gui::View3DInventorViewer::startSpinningAnimation().
startSelection() [1/2]
void NavigationStyle::startSelection (AbstractMouseSelection * mouse)
Definition at line 1292 of file NavigationStyle.cpp.
References Gui::AbstractMouseSelection::grabMouseModel(), mouseSelection, and viewer.
Referenced by Gui::View3DInventorViewer::startSelection().
startSelection() [2/2]
void NavigationStyle::startSelection (NavigationStyle::SelectionMode mode = Lasso)
Definition at line 1306 of file NavigationStyle.cpp.
References BoxZoom, Clip, Gui::AbstractMouseSelection::grabMouseModel(), isSelecting(), Lasso, mouseSelection, Rectangle, Rubberband, stopSelection(), and viewer.
stopAnimating()
void NavigationStyle::stopAnimating () const
Definition at line 1232 of file NavigationStyle.cpp.
References animator, and Gui::NavigationAnimator::stop().
Referenced by Gui::View3DInventorViewer::stopAnimating().
stopSelection()
void NavigationStyle::stopSelection ()
Definition at line 1348 of file NavigationStyle.cpp.
References mouseSelection, pcPolygon, and Gui::AbstractMouseSelection::releaseMouseModel().
Referenced by startSelection(), and Gui::View3DInventorViewer::stopSelection().
syncModifierKeys()
void NavigationStyle::syncModifierKeys (const SoEvent *const ev) protected
Definition at line 1405 of file NavigationStyle.cpp.
References altdown, ctrldown, and shiftdown.
Referenced by Gui::GestureNavigationStyle::processSoEvent(), Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::MayaGestureNavigationStyle::processSoEvent(), Gui::TouchpadNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), Gui::TinkerCADNavigationStyle::processSoEvent(), and syncWithEvent().
syncWithEvent()
void NavigationStyle::syncWithEvent (const SoEvent *const ev) protected
Definition at line 1571 of file NavigationStyle.cpp.
References altdown, button1down, button2down, button3down, ctrldown, isSeekMode(), shiftdown, syncModifierKeys(), and Path.Post.scripts.grbl_post::type.
Referenced by processEvent().
translateCamera()
void NavigationStyle::translateCamera (const SbVec3f & translation)
Definition at line 430 of file NavigationStyle.cpp.
References animator, getCamera(), isAnimationEnabled(), Gui::View3DInventorViewer::startAnimation(), Gui::NavigationAnimator::stop(), and viewer.
Referenced by lookAtPoint().
viewAll()
void NavigationStyle::viewAll () virtual
Definition at line 488 of file NavigationStyle.cpp.
References Path.Post.scripts.dynapath_4060_post::action, MengerSponge::box, SCL.SimpleDataTypes::f, SIM::Coin3D::Quarter::QuarterWidget::getSceneGraph(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), toolbit-attributes::s, size, and viewer.
zoom()
void NavigationStyle::zoom (SoCamera * cam, float diffvalue) protected
Dependent on the camera type this will either shrink or expand the height of the viewport (orthogonal camera) or move the camera closer or further away from the focal point in the scene.
Definition at line 651 of file NavigationStyle.cpp.
References animator, currentmode, KDL::exp(), hasZoomed, IDLE, KDL::sqrt(), Gui::NavigationAnimator::stop(), and InitGui::t.
Referenced by doZoom(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), zoomByCursor(), zoomIn(), and zoomOut().
zoomByCursor()
void NavigationStyle::zoomByCursor (const SbVec2f & thispos, const SbVec2f & prevpos) protected
Definition at line 732 of file NavigationStyle.cpp.
References SCL.SimpleDataTypes::f, SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), invertZoom, viewer, and zoom().
Referenced by Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::MayaGestureNavigationStyle::processSoEvent(), and Gui::TouchpadNavigationStyle::processSoEvent().
zoomIn()
void NavigationStyle::zoomIn ()
Definition at line 742 of file NavigationStyle.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), viewer, and zoom().
Referenced by Gui::View3DInventorPy::zoomIn().
zoomOut()
void NavigationStyle::zoomOut ()
Definition at line 747 of file NavigationStyle.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), viewer, and zoom().
Referenced by Gui::View3DInventorPy::zoomOut().
Friends And Related Function Documentation
NavigationAnimator
friend class NavigationAnimator friend
Definition at line 287 of file NavigationStyle.h.
Referenced by initialize().
Member Data Documentation
altdown
SbBool Gui::NavigationStyle::altdown protected
Definition at line 260 of file NavigationStyle.h.
Referenced by draftguitools.gui_dimensions.Dimension::action(), initialize(), processKeyboardEvent(), Gui::GestureNavigationStyle::processSoEvent(), Gui::MayaGestureNavigationStyle::processSoEvent(), Gui::TouchpadNavigationStyle::processSoEvent(), syncModifierKeys(), and syncWithEvent().
animationEnabled
SbBool Gui::NavigationStyle::animationEnabled protected
Definition at line 250 of file NavigationStyle.h.
Referenced by initialize(), isAnimationEnabled(), isSpinningAnimationEnabled(), operator=(), and setAnimationEnabled().
animator
NavigationAnimator* Gui::NavigationStyle::animator protected
Definition at line 249 of file NavigationStyle.h.
Referenced by initialize(), isAnimating(), setAnimationEnabled(), setCameraOrientation(), setSpinningAnimationEnabled(), setViewingMode(), startAnimating(), stopAnimating(), translateCamera(), zoom(), and ~NavigationStyle().
button1down
SbBool Gui::NavigationStyle::button1down protected
Definition at line 261 of file NavigationStyle.h.
Referenced by initialize(), Gui::GestureNavigationStyle::processSoEvent(), Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::MayaGestureNavigationStyle::processSoEvent(), Gui::TouchpadNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), Gui::TinkerCADNavigationStyle::processSoEvent(), and syncWithEvent().
button2down
SbBool Gui::NavigationStyle::button2down protected
Definition at line 261 of file NavigationStyle.h.
Referenced by initialize(), Gui::GestureNavigationStyle::processSoEvent(), Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::MayaGestureNavigationStyle::processSoEvent(), Gui::TouchpadNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), Gui::TinkerCADNavigationStyle::processSoEvent(), and syncWithEvent().
button3down
SbBool Gui::NavigationStyle::button3down protected
Definition at line 261 of file NavigationStyle.h.
Referenced by initialize(), Gui::GestureNavigationStyle::processSoEvent(), Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::MayaGestureNavigationStyle::processSoEvent(), Gui::TouchpadNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), Gui::TinkerCADNavigationStyle::processSoEvent(), and syncWithEvent().
centerTime
SbTime Gui::NavigationStyle::centerTime protected
Definition at line 257 of file NavigationStyle.h.
Referenced by Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::TouchpadNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), and Gui::TinkerCADNavigationStyle::processSoEvent().
ctrldown
SbBool Gui::NavigationStyle::ctrldown protected
Definition at line 260 of file NavigationStyle.h.
Referenced by initialize(), processKeyboardEvent(), Gui::GestureNavigationStyle::processSoEvent(), Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::MayaGestureNavigationStyle::processSoEvent(), Gui::TouchpadNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), Gui::TinkerCADNavigationStyle::processSoEvent(), syncModifierKeys(), and syncWithEvent().
currentmode
ViewerMode Gui::NavigationStyle::currentmode protected
Definition at line 251 of file NavigationStyle.h.
Referenced by getViewingMode(), initialize(), isSpinning(), panCamera(), processEvent(), Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::MayaGestureNavigationStyle::processSoEvent(), Gui::TouchpadNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), Gui::TinkerCADNavigationStyle::processSoEvent(), setViewingMode(), spin(), and zoom().
globalPos
SbVec2s Gui::NavigationStyle::globalPos protected
Definition at line 254 of file NavigationStyle.h.
Referenced by moveCursorPosition(), and saveCursorPosition().
hasDragged
SbBool Gui::NavigationStyle::hasDragged protected
Definition at line 265 of file NavigationStyle.h.
Referenced by initialize(), Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::TouchpadNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), Gui::TinkerCADNavigationStyle::processSoEvent(), setViewingMode(), spin(), and spin_simplified().
hasPanned
SbBool Gui::NavigationStyle::hasPanned protected
Definition at line 266 of file NavigationStyle.h.
Referenced by initialize(), panCamera(), Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::TouchpadNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), Gui::TinkerCADNavigationStyle::processSoEvent(), and setViewingMode().
hasZoomed
SbBool Gui::NavigationStyle::hasZoomed protected
Definition at line 267 of file NavigationStyle.h.
Referenced by initialize(), Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::TouchpadNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), Gui::TinkerCADNavigationStyle::processSoEvent(), setViewingMode(), and zoom().
historysize
short Gui::NavigationStyle::historysize
Definition at line 243 of file NavigationStyle.h.
invertZoom
SbBool Gui::NavigationStyle::invertZoom protected
Definition at line 262 of file NavigationStyle.h.
Referenced by doZoom(), initialize(), isZoomInverted(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), setZoomInverted(), and zoomByCursor().
lastmouseposition
SbVec2f Gui::NavigationStyle::lastmouseposition protected
Definition at line 253 of file NavigationStyle.h.
Referenced by doSpin(), Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::MayaGestureNavigationStyle::processSoEvent(), Gui::TouchpadNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), Gui::TinkerCADNavigationStyle::processSoEvent(), and setViewingMode().
localPos
SbVec2s Gui::NavigationStyle::localPos protected
Definition at line 255 of file NavigationStyle.h.
Referenced by moveCursorPosition(), saveCursorPosition(), spin(), and spin_simplified().
lockrecenter
SbBool Gui::NavigationStyle::lockrecenter protected
Definition at line 258 of file NavigationStyle.h.
Referenced by Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::TouchpadNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), and Gui::OpenSCADNavigationStyle::processSoEvent().
log
struct { ... } Gui::NavigationStyle::log
Referenced by addToLog(), clearLog(), doSpin(), finalize(), initialize(), src.Mod.AddonManager.AddonManagerTest.app.mocks.MockConsole::missing_newlines(), moveCursorPosition(), src.Mod.AddonManager.AddonManagerTest.app.mocks.MockConsole::PrintLog(), and spin().
menuenabled
SbBool Gui::NavigationStyle::menuenabled protected
Definition at line 259 of file NavigationStyle.h.
Referenced by initialize(), isPopupMenuEnabled(), operator=(), and setPopupMenuEnabled().
mouseDownConsumedEvent
SoMouseButtonEvent Gui::NavigationStyle::mouseDownConsumedEvent protected
Definition at line 252 of file NavigationStyle.h.
Referenced by processClickEvent(), and Gui::TinkerCADNavigationStyle::processSoEvent().
mouseSelection
AbstractMouseSelection* Gui::NavigationStyle::mouseSelection {nullptr} protected
Definition at line 271 of file NavigationStyle.h.
Referenced by abortSelection(), isSelecting(), processEvent(), startSelection(), and stopSelection().
panningplane
SbPlane Gui::NavigationStyle::panningplane protected
Definition at line 256 of file NavigationStyle.h.
Referenced by lookAtPoint(), operator=(), and setupPanningPlane().
pcPolygon
std::vector<SbVec2s> Gui::NavigationStyle::pcPolygon protected
Definition at line 272 of file NavigationStyle.h.
Referenced by abortSelection(), getPolygon(), processEvent(), and stopSelection().
position
SbVec2s* Gui::NavigationStyle::position
Definition at line 244 of file NavigationStyle.h.
Referenced by WorkingPlane.PlaneBase::__repr__(), WorkingPlane.PlaneBase::align_to_edge_or_wire(), WorkingPlane.PlaneBase::align_to_face(), WorkingPlane.PlaneBase::align_to_placement(), WorkingPlane.PlaneBase::align_to_point_and_axis(), WorkingPlane.PlaneBase::align_to_point_and_axis_svg(), WorkingPlane.PlaneGui::align_view(), WorkingPlane.PlaneGui::center_on_view(), ifc2x3.ifcsweptsurface::dim(), ifc2x3.ifcelementarysurface::dim(), draftguitools.gui_trackers.editTracker::get(), WorkingPlane.PlaneBase::get_global_coords(), WorkingPlane.PlaneBase::get_local_coords(), WorkingPlane.PlaneBase::get_placement(), WorkingPlane.PlaneBase::is_global(), lookAtPoint(), WorkingPlane.Plane::offsetToPoint(), openPopupMenu(), WorkingPlane.PlaneBase::project_point(), WorkingPlane.Plane::restore(), WorkingPlane.Plane::save(), draftguitools.gui_trackers.editTracker::set(), WorkingPlane.PlaneBase::set_to_front(), WorkingPlane.PlaneGui::set_to_position(), WorkingPlane.PlaneBase::set_to_side(), WorkingPlane.PlaneBase::set_to_top(), WorkingPlane.PlaneGui::set_to_view(), Path.Base.Generator.dogboneII.Bone::tip(), Path.Base.Generator.dogboneII.Kink::x(), and Path.Base.Generator.dogboneII.Kink::y().
pythonObject
PyObject* Gui::NavigationStyle::pythonObject protected
Definition at line 284 of file NavigationStyle.h.
Referenced by getPyObject(), and ~NavigationStyle().
selectedRole
SelectionRole Gui::NavigationStyle::selectedRole protected
Definition at line 273 of file NavigationStyle.h.
Referenced by getPolygon(), and processEvent().
shiftdown
SbBool Gui::NavigationStyle::shiftdown protected
Definition at line 260 of file NavigationStyle.h.
Referenced by initialize(), processKeyboardEvent(), Gui::GestureNavigationStyle::processSoEvent(), Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::MayaGestureNavigationStyle::processSoEvent(), Gui::TouchpadNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), Gui::TinkerCADNavigationStyle::processSoEvent(), syncModifierKeys(), and syncWithEvent().
size
short Gui::NavigationStyle::size
Definition at line 242 of file NavigationStyle.h.
Referenced by boxZoom(), Path.Post.Utils.GCodeEditorDialog::done(), CommandCreateView.TaskAssemblyCreateView::draggerMoved(), normalizePixelPos(), CommandCreateView.TaskAssemblyCreateView::onMovesChanged(), saveCursorPosition(), and viewAll().
spinincrement
SbRotation Gui::NavigationStyle::spinincrement protected
Definition at line 280 of file NavigationStyle.h.
Referenced by initialize(), and spin().
spinningAnimationEnabled
SbBool Gui::NavigationStyle::spinningAnimationEnabled protected
Definition at line 278 of file NavigationStyle.h.
Referenced by initialize(), isSpinningAnimationEnabled(), operator=(), and setSpinningAnimationEnabled().
spinprojector
SbSphereSheetProjector* Gui::NavigationStyle::spinprojector protected
Definition at line 281 of file NavigationStyle.h.
Referenced by doSpin(), finalize(), getOrbitStyle(), initialize(), operator=(), setOrbitStyle(), setViewingMode(), spin(), and spin_simplified().
spinsamplecounter
int Gui::NavigationStyle::spinsamplecounter protected
Definition at line 279 of file NavigationStyle.h.
Referenced by initialize(), and spin().
time
SbTime* Gui::NavigationStyle::time
Definition at line 245 of file NavigationStyle.h.
Referenced by addToLog().
viewer
View3DInventorViewer* Gui::NavigationStyle::viewer {nullptr} protected
Definition at line 248 of file NavigationStyle.h.
Referenced by boxZoom(), doRotate(), doSpin(), doZoom(), findBoundingSphere(), getCamera(), getFocalPoint(), getInteractiveCount(), handleEventInForeground(), interactiveCountDec(), interactiveCountInc(), Gui::GestureNavigationStyle::is2DViewing(), Gui::GestureNavigationStyle::isDraggerUnderCursor(), isSeekMode(), isViewing(), lookAtPoint(), normalizePixelPos(), openPopupMenu(), processEvent(), processKeyboardEvent(), processMotionEvent(), Gui::GestureNavigationStyle::processSoEvent(), processSoEvent(), Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::MayaGestureNavigationStyle::processSoEvent(), Gui::TouchpadNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), Gui::TinkerCADNavigationStyle::processSoEvent(), processWheelEvent(), saveCursorPosition(), seekToPoint(), setCameraOrientation(), setSeekMode(), setupPanningPlane(), setViewer(), setViewing(), setViewingMode(), spin(), spin_simplified(), startSelection(), translateCamera(), viewAll(), zoomByCursor(), zoomIn(), and zoomOut().
zoomAtCursor
SbBool Gui::NavigationStyle::zoomAtCursor protected
Definition at line 263 of file NavigationStyle.h.
Referenced by doRotate(), doZoom(), initialize(), isZoomAtCursor(), Gui::MayaGestureNavigationStyle::processSoEvent(), and setZoomAtCursor().
zoomStep
float Gui::NavigationStyle::zoomStep protected
Definition at line 264 of file NavigationStyle.h.
Referenced by doZoom(), initialize(), and setZoomStep().
The documentation for this class was generated from the following files:
NavigationStyle.h
NavigationStyle.cpp