FreeCAD: TechDrawGui::QGILeaderLine Class Reference
TechDrawGui::QGILeaderLine Class Reference
#include <QGILeaderLine.h>
Public Types
enum { Type = QGraphicsItem::UserType + 232 }
Public Types inherited from TechDrawGui::QGIView
enum { Type = QGraphicsItem::UserType + 101 }
Public Slots
void onLineEditFinished (QPointF tipDisplace, std::vector< QPointF > points)
Signals
void editComplete ()
Public Member Functions
QGILeaderLine ()
~QGILeaderLine () override=default
int type () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
QRectF boundingRect () const override
void drawBorder () override
void updateView (bool update=false) override
virtual TechDraw::DrawLeaderLine * getLeaderFeature ()
void startPathEdit ()
void setArrows (std::vector< QPointF > pathPoints)
void abandonEdit ()
void closeEdit ()
double getLineWidth ()
double getEdgeFuzz () const
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event) override
start editor on double click
void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
void setPrettyNormal ()
void setPrettyPre ()
void setPrettySel ()
void setLeaderFeature (TechDraw::DrawLeaderLine *feat)
bool useOldCoords () const
Base::Vector3d getAttachPoint ()
return the position of the tip of the leader's arrow
Public Member Functions inherited from TechDrawGui::QGIView
QGIView ()
int type () const override
QRectF boundingRect () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
const char * getViewName () const
const std::string getViewNameAsString () const
void setViewFeature (TechDraw::DrawView *obj)
TechDraw::DrawView * getViewObject () const
MDIViewPage * getMDIViewPage () const
double getScale ()
void hideFrame ()
virtual bool getFrameState ()
virtual void toggleCache (bool state)
virtual void isVisible (bool state)
virtual bool isVisible ()
virtual bool getGroupSelection ()
virtual void setGroupSelection (bool isSelected)
virtual void setGroupSelection (bool isSelected, const std::vector< std::string > &subNames)
virtual void drawCaption ()
virtual void rotateView ()
void makeMark (double xPos, double yPos, QColor color=Qt::red)
void makeMark (Base::Vector3d pos, QColor color=Qt::red)
void makeMark (QPointF pos, QColor color=Qt::red)
void setPosition (qreal xPos, qreal yPos)
qreal getY ()
bool isInnerView () const
void isInnerView (bool state)
QGIViewClip * getClipGroup ()
bool isSnapping ()
void snapPosition (QPointF &position)
void snapSectionView (const TechDraw::DrawViewSection *sectionView, QPointF &newPosition)
Base::Vector3d projItemPagePos (TechDraw::DrawViewPart *item)
void alignTo (QGraphicsItem *, const QString &alignment)
QColor prefNormalColor ()
QColor getNormalColor ()
void setNormalColor (QColor color)
QColor getPreColor ()
QColor getSelectColor ()
QColor getCurrentColor ()
void setCurrentColor (QColor color)
QColor getSettingColor ()
void setSettingColor (QColor color)
virtual void setStack (int z)
virtual void setStackFromVP ()
QFont getFont ()
void setFont (QFont font)
virtual void removeChild (QGIView *child)
virtual void addArbitraryItem (QGraphicsItem *qgi)
virtual void switchParentItem (QGIView *targetParent)
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
Protected Member Functions
void draw () override
QPainterPath makeLeaderPath (std::vector< QPointF > qPoints)
std::vector< QPointF > getWayPointsFromFeature ()
QPointF getAttachFromFeature ()
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
void saveState ()
void restoreState ()
QColor prefNormalColor ()
void setNormalColorAll ()
Protected Member Functions inherited from TechDrawGui::QGIView
QGIView * getQGIVByName (std::string name)
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
virtual QRectF customChildrenBoundingRect () const
void dumpRect (const char *text, QRectF rect)
Base::Reference< ParameterGrp > getParmGroupCol ()
Additional Inherited Members
Static Public Member Functions inherited from TechDrawGui::QGIView
static Gui::ViewProvider * getViewProvider (App::DocumentObject *obj)
static ViewProviderPage * getViewProviderPage (TechDraw::DrawView *dView)
static int calculateFontPixelSize (double sizeInMillimetres)
static int calculateFontPixelWidth (const QFont &font)
static QString getPrefFont ()
static double getPrefFontSize ()
static double getDimFontSize ()
static int exactFontSize (std::string fontFamily, double nominalSize)
Static Public Attributes inherited from TechDrawGui::QGIView
static const double DefaultFontSizeInMM = 5.0
Detailed Description
Definition at line 54 of file QGILeaderLine.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 59 of file QGILeaderLine.h.
Constructor & Destructor Documentation
QGILeaderLine()
QGILeaderLine::QGILeaderLine () explicit
Definition at line 60 of file QGILeaderLine.cpp.
References black, draftgeoutils.intersections::connect(), ZVALUE::DIMENSION, onLineEditFinished(), and TechDrawGui::QGEPath::pointsUpdated().
~QGILeaderLine()
TechDrawGui::QGILeaderLine::~QGILeaderLine () override default
Member Function Documentation
abandonEdit()
void QGILeaderLine::abandonEdit ()
Definition at line 599 of file QGILeaderLine.cpp.
References TechDrawGui::QGEPath::clearMarkers(), and restoreState().
Referenced by TechDrawGui::TaskLeaderLine::abandonEditSession().
boundingRect()
QRectF QGILeaderLine::boundingRect () const override
Definition at line 639 of file QGILeaderLine.cpp.
Referenced by draw().
closeEdit()
void QGILeaderLine::closeEdit ()
Definition at line 226 of file QGILeaderLine.cpp.
References TechDrawGui::QGEPath::onEndEdit().
Referenced by TechDrawGui::TaskLeaderLine::onTrackerClicked().
draw()
void QGILeaderLine::draw () override protected virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 342 of file QGILeaderLine.cpp.
References boundingRect(), Base::Console(), getAttachPoint(), TechDraw::DrawLeaderLine::getBaseView(), getLeaderFeature(), getLineWidth(), TechDrawGui::QGIView::getViewObject(), TechDrawGui::QGIView::getViewProvider(), getWayPointsFromFeature(), TechDrawGui::QGEPath::inEdit(), TechDraw::DrawView::isLocked(), TechDrawGui::QGIView::isVisible(), makeLeaderPath(), Base::ConsoleSingleton::Message(), Init::parent, setArrows(), TechDrawGui::QGIPrimPath::setFillStyle(), setNormalColorAll(), setPrettyNormal(), setPrettyPre(), setPrettySel(), TechDrawGui::QGIPrimPath::setStyle(), TechDrawGui::QGIPrimPath::setWidth(), and TechDraw::DrawUtil::toQPointF().
Referenced by itemChange(), onLineEditFinished(), and updateView().
drawBorder()
void QGILeaderLine::drawBorder () override virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 563 of file QGILeaderLine.cpp.
editComplete
void TechDrawGui::QGILeaderLine::editComplete () signal
Referenced by onLineEditFinished(), and TechDrawGui::TaskLeaderLine::onTrackerClicked().
getAttachFromFeature()
QPointF QGILeaderLine::getAttachFromFeature () protected
returns the point (on the parent) to which the leader is attached. result is relative to the center of the unscaled, unrotated parent. result is is not inverted (Y grows upwards).
Definition at line 463 of file QGILeaderLine.cpp.
References getLeaderFeature(), App::PropertyQuantity::getValue(), TechDrawGui::Rez::guiX(), MovieTool::x, TechDraw::DrawView::X, MovieTool::y, and TechDraw::DrawView::Y.
Referenced by onLineEditFinished().
getAttachPoint()
Base::Vector3d QGILeaderLine::getAttachPoint ()
return the position of the tip of the leader's arrow
Definition at line 571 of file QGILeaderLine.cpp.
References DegreesHalfCircle, TechDraw::DrawLeaderLine::getBaseScale(), TechDraw::DrawLeaderLine::getBaseView(), getLeaderFeature(), App::PropertyQuantity::getValue(), TechDrawGui::Rez::guiX(), TechDraw::DrawUtil::invertY(), M_PI, Init::parent, TechDraw::DrawView::X, and TechDraw::DrawView::Y.
Referenced by draw().
getEdgeFuzz()
double QGILeaderLine::getEdgeFuzz () const
Definition at line 621 of file QGILeaderLine.cpp.
References TechDrawGui::PreferencesGui::edgeFuzz().
getLeaderFeature()
TechDraw::DrawLeaderLine * QGILeaderLine::getLeaderFeature () virtual
Definition at line 616 of file QGILeaderLine.cpp.
References TechDrawGui::QGIView::getViewObject().
Referenced by draw(), getAttachFromFeature(), getAttachPoint(), getWayPointsFromFeature(), makeLeaderPath(), mouseDoubleClickEvent(), onLineEditFinished(), restoreState(), saveState(), and setArrows().
getLineWidth()
double QGILeaderLine::getLineWidth ()
Definition at line 607 of file QGILeaderLine.cpp.
References TechDrawGui::QGIView::getViewObject(), TechDrawGui::QGIView::getViewProvider(), and TechDrawGui::Rez::guiX().
Referenced by draw(), and setArrows().
getWayPointsFromFeature()
std::vector< QPointF > QGILeaderLine::getWayPointsFromFeature () protected
Definition at line 476 of file QGILeaderLine.cpp.
References TechDraw::DrawLeaderLine::AutoHorizontal, Base::Console(), TechDraw::DrawLeaderLine::getBaseView(), getLeaderFeature(), TechDraw::DrawLeaderLine::getScaledAndRotatedPoints(), App::PropertyQuantity::getValue(), App::PropertyBool::getValue(), TechDrawGui::Rez::guiX(), TechDraw::DrawLeaderLine::RotatesWithParent, TechDraw::DrawView::Rotation, TechDraw::DrawLeaderLine::Scalable, TechDraw::DrawUtil::toQPointF(), useOldCoords(), and Base::ConsoleSingleton::Warning().
Referenced by draw().
hoverEnterEvent()
void QGILeaderLine::hoverEnterEvent (QGraphicsSceneHoverEvent * event) override
Definition at line 169 of file QGILeaderLine.cpp.
References TechDrawGui::QGIView::hoverEnterEvent(), and setPrettyPre().
hoverLeaveEvent()
void QGILeaderLine::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) override
Definition at line 179 of file QGILeaderLine.cpp.
References TechDrawGui::QGIView::hoverLeaveEvent(), and setPrettyNormal().
itemChange()
QVariant QGILeaderLine::itemChange (GraphicsItemChange change, const QVariant & value) override protected
Definition at line 125 of file QGILeaderLine.cpp.
References draw(), TechDrawGui::QGIView::itemChange(), setPrettyNormal(), and setPrettySel().
makeLeaderPath()
QPainterPath QGILeaderLine::makeLeaderPath (std::vector< QPointF > qPoints) protected
Definition at line 414 of file QGILeaderLine.cpp.
References TechDraw::DrawLeaderLine::EndSymbol, getLeaderFeature(), TechDrawGui::QGIArrow::getOverlapAdjust(), TechDrawGui::QGIArrow::getPrefArrowSize(), App::PropertyEnumeration::getValue(), SplineSurface::i, NONE, result, and TechDraw::DrawLeaderLine::StartSymbol.
Referenced by draw().
mouseDoubleClickEvent()
void QGILeaderLine::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * event) override
start editor on double click
Definition at line 156 of file QGILeaderLine.cpp.
References getLeaderFeature(), TechDrawGui::QGIView::getViewProvider(), and Gui::ViewProviderDocumentObject::startDefaultEditMode().
mousePressEvent()
void QGILeaderLine::mousePressEvent (QGraphicsSceneMouseEvent * event) override
Definition at line 144 of file QGILeaderLine.cpp.
mouseReleaseEvent()
void QGILeaderLine::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) override
Definition at line 150 of file QGILeaderLine.cpp.
onLineEditFinished
void QGILeaderLine::onLineEditFinished (QPointF tipDisplace, std::vector< QPointF > scenePoints) slot
scene coordinates of leaderline points are converted to real page coordinates as deltas from first point. line start point (X,Y of leader feature) is recomputed as displacement from parent's (0,0). signaled from QEPath
Definition at line 237 of file QGILeaderLine.cpp.
References TechDrawGui::Rez::appX(), draw(), editComplete(), TechDraw::DrawUtil::fpCompare(), getAttachFromFeature(), getLeaderFeature(), and TechDraw::DrawUtil::toVector3d().
Referenced by QGILeaderLine().
paint()
void QGILeaderLine::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) override
Definition at line 644 of file QGILeaderLine.cpp.
References TechDrawGui::QGIView::paint().
prefNormalColor()
QColor QGILeaderLine::prefNormalColor () protected
Definition at line 626 of file QGILeaderLine.cpp.
References App::Color::asValue(), TechDrawGui::ViewProviderLeader::Color, TechDrawGui::PreferencesGui::getAccessibleQColor(), TechDrawGui::QGIView::getNormalColor(), App::PropertyColor::getValue(), TechDrawGui::QGIView::getViewObject(), TechDrawGui::QGIView::getViewProvider(), TechDrawGui::PreferencesGui::leaderQColor(), and TechDrawGui::QGIView::setNormalColor().
Referenced by setNormalColorAll().
restoreState()
void QGILeaderLine::restoreState () protected
Definition at line 311 of file QGILeaderLine.cpp.
References getLeaderFeature().
Referenced by abandonEdit().
saveState()
void QGILeaderLine::saveState () protected
Definition at line 300 of file QGILeaderLine.cpp.
References getLeaderFeature().
Referenced by startPathEdit().
setArrows()
void QGILeaderLine::setArrows (std::vector< QPointF > pathPoints)
Definition at line 511 of file QGILeaderLine.cpp.
References TechDrawGui::QGIArrow::draw(), SCL.SimpleDataTypes::e, TechDraw::DrawLeaderLine::EndSymbol, getLeaderFeature(), getLineWidth(), TechDrawGui::QGIArrow::getPrefArrowSize(), App::PropertyEnumeration::getValue(), NONE, toolbit-attributes::s, TechDrawGui::QGIArrow::setDirection(), TechDrawGui::QGIArrow::setDirMode(), TechDrawGui::QGIArrow::setSize(), TechDrawGui::QGIArrow::setStyle(), TechDrawGui::QGIPrimPath::setWidth(), and TechDraw::DrawLeaderLine::StartSymbol.
Referenced by draw().
setLeaderFeature()
void QGILeaderLine::setLeaderFeature (TechDraw::DrawLeaderLine * feat)
Definition at line 110 of file QGILeaderLine.cpp.
References App::PropertyQuantity::getValue(), TechDrawGui::Rez::guiX(), setNormalColorAll(), setPrettyNormal(), TechDrawGui::QGIView::setViewFeature(), updateView(), MovieTool::x, TechDraw::DrawView::X, MovieTool::y, and TechDraw::DrawView::Y.
setNormalColorAll()
void QGILeaderLine::setNormalColorAll () protected
Definition at line 189 of file QGILeaderLine.cpp.
References prefNormalColor(), TechDrawGui::QGIPrimPath::setFillColor(), and TechDrawGui::QGIPrimPath::setNormalColor().
Referenced by draw(), and setLeaderFeature().
setPrettyNormal()
void QGILeaderLine::setPrettyNormal ()
Definition at line 201 of file QGILeaderLine.cpp.
References TechDrawGui::QGIPrimPath::setPrettyNormal().
Referenced by draw(), hoverLeaveEvent(), itemChange(), and setLeaderFeature().
setPrettyPre()
void QGILeaderLine::setPrettyPre ()
Definition at line 209 of file QGILeaderLine.cpp.
References TechDrawGui::QGIPrimPath::setPrettyPre().
Referenced by draw(), and hoverEnterEvent().
setPrettySel()
void QGILeaderLine::setPrettySel ()
Definition at line 217 of file QGILeaderLine.cpp.
References TechDrawGui::QGIPrimPath::setPrettySel().
Referenced by draw(), and itemChange().
startPathEdit()
void QGILeaderLine::startPathEdit ()
Definition at line 278 of file QGILeaderLine.cpp.
References TechDrawGui::QGIView::getViewObject(), TechDrawGui::Rez::guiX(), TechDrawGui::QGEPath::inEdit(), saveState(), TechDrawGui::QGEPath::setScale(), TechDrawGui::QGEPath::startPathEdit(), and TechDraw::DrawUtil::toQPointF().
type()
int TechDrawGui::QGILeaderLine::type () const inline override
Definition at line 67 of file QGILeaderLine.h.
updateView()
void QGILeaderLine::updateView (bool update = false) override virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 325 of file QGILeaderLine.cpp.
References Base::Console(), draw(), TechDrawGui::QGIView::getViewObject(), TechDrawGui::QGIView::getViewProvider(), and Base::ConsoleSingleton::Warning().
Referenced by setLeaderFeature().
useOldCoords()
bool QGILeaderLine::useOldCoords () const
Definition at line 656 of file QGILeaderLine.cpp.
References App::PropertyBool::getValue(), TechDrawGui::QGIView::getViewObject(), TechDrawGui::QGIView::getViewProvider(), and TechDrawGui::ViewProviderLeader::UseOldCoords.
Referenced by getWayPointsFromFeature().
The documentation for this class was generated from the following files:
QGILeaderLine.h
QGILeaderLine.cpp