FreeCAD: Sandbox::PythonThread Class Reference
Sandbox::PythonThread Class Reference
#include <DocumentThread.h>
Public Member Functions
PythonThread (QObject *parent=0)
~PythonThread ()
Protected Member Functions
void run ()
Static Protected Attributes
static QRecursiveMutex mutex
Detailed Description
Definition at line 58 of file DocumentThread.h.
Constructor & Destructor Documentation
PythonThread()
PythonThread::PythonThread (QObject * parent = 0)
Definition at line 94 of file DocumentThread.cpp.
~PythonThread()
PythonThread::~PythonThread ()
Definition at line 99 of file DocumentThread.cpp.
Member Function Documentation
run()
void PythonThread::run () protected
Definition at line 103 of file DocumentThread.cpp.
References Base::Console(), Path.Base.SetupSheet::dict, SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), Base::Interpreter(), src.Mod.PartDesign.fcgear.svggear::module, mutex, and Base::InterpreterSingleton::runString().
Member Data Documentation
mutex
QRecursiveMutex PythonThread::mutex static protected
Definition at line 66 of file DocumentThread.h.
Referenced by run().
The documentation for this class was generated from the following files:
DocumentThread.h
DocumentThread.cpp