FreeCAD: ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.polyline Class Reference
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.polyline Class Reference
Public Member Functions
def __init__ (self, inherited0__name, points)
def points ()
Public Member Functions inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.bounded_curve
def __init__ (self, inherited0__name)
Public Member Functions inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometric_representation_item
def dim ()
def wr1 (self)
Public Member Functions inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.representation_item
def name ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
points
Public Attributes inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.representation_item
name
Detailed Description
Entity polyline definition.
:param points
:type points:LIST(2,None,'cartesian_point', scope = schema_scope)
Definition at line 36208 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Constructor & Destructor Documentation
__init__()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.polyline.__init__ (self, inherited0__name, points)
Definition at line 36214 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Member Function Documentation
points()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.polyline.points ()
Definition at line 36219 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.polyline._points, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.polyline.points.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.fill_area_style_tile_coloured_region.wr1(), config_control_design.advanced_face.wr10(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.advanced_face.wr10(), and automotive_design.advanced_face.wr10().
Member Data Documentation
points
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.polyline.points
Definition at line 36216 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.polyline.points(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.fill_area_style_tile_coloured_region.wr1(), config_control_design.advanced_face.wr10(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.advanced_face.wr10(), and automotive_design.advanced_face.wr10().
The documentation for this class was generated from the following file:
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py