FreeCAD: MeshCore::MeshGridIterator Class Reference
MeshCore::MeshGridIterator Class Reference
#include <Grid.h>
Public Member Functions
MeshGridIterator (const MeshGrid &rclG)
Construction.
Base::BoundBox3f GetBoundBox () const
void GetElements (std::vector< ElementIndex > &raulElements) const
unsigned long GetCtElements () const
Iteration
void Init ()
bool More () const
void Next ()
Tests with rays
bool InitOnRay (const Base::Vector3f &rclPt, const Base::Vector3f &rclDir, std::vector< ElementIndex > &raulElements)
bool InitOnRay (const Base::Vector3f &rclPt, const Base::Vector3f &rclDir, float fMaxSearchArea, std::vector< ElementIndex > &raulElements)
bool NextOnRay (std::vector< ElementIndex > &raulElements)
void GetGridPos (unsigned long &rulX, unsigned long &rulY, unsigned long &rulZ) const
const MeshGrid & GetGrid () const
Detailed Description
The MeshGridIterator class provides an interface to walk through all grid elements of a mesh grid.
Definition at line 360 of file Grid.h.
Constructor & Destructor Documentation
MeshGridIterator()
MeshGridIterator::MeshGridIterator (const MeshGrid & rclG) explicit
Construction.
Definition at line 1134 of file Grid.cpp.
Member Function Documentation
GetBoundBox()
Base::BoundBox3f MeshCore::MeshGridIterator::GetBoundBox () const inline
Returns the bounding box of the current grid element.
Definition at line 366 of file Grid.h.
Referenced by MeshCore::MeshTrimByPlane::CheckFacets(), MeshCore::MeshTrimming::CheckFacets(), MeshCore::MeshAlgorithm::CheckFacets(), MeshCore::MeshAlgorithm::CutWithPlane(), MeshCore::MeshAlgorithm::GetFacetsFromPlane(), MeshCore::MeshAlgorithm::GetFacetsFromToolMesh(), MeshCore::MeshProjection::projectLineOnMesh(), MeshCore::MeshFacetGrid::Verify(), and MeshCore::MeshPointGrid::Verify().
GetCtElements()
unsigned long MeshCore::MeshGridIterator::GetCtElements () const inline
Returns the number of elements in the current grid.
Definition at line 378 of file Grid.h.
GetElements()
void MeshCore::MeshGridIterator::GetElements (std::vector< ElementIndex > & raulElements) const inline
Returns indices of the elements in the current grid.
Definition at line 371 of file Grid.h.
Referenced by MeshCore::MeshTrimByPlane::CheckFacets(), MeshCore::MeshTrimming::CheckFacets(), MeshCore::MeshAlgorithm::CheckFacets(), MeshCore::MeshAlgorithm::CutWithPlane(), MeshCore::MeshEvalSelfIntersection::Evaluate(), MeshCore::MeshAlgorithm::GetFacetsFromPlane(), MeshCore::MeshAlgorithm::GetFacetsFromToolMesh(), MeshCore::MeshEvalSelfIntersection::GetIntersections(), MeshCore::MeshProjection::projectLineOnMesh(), MeshCore::MeshFacetGrid::Verify(), and MeshCore::MeshPointGrid::Verify().
GetGrid()
const MeshGrid& MeshCore::MeshGridIterator::GetGrid () const inline protected
Definition at line 437 of file Grid.h.
GetGridPos()
void MeshCore::MeshGridIterator::GetGridPos (unsigned long & rulX, unsigned long & rulY, unsigned long & rulZ) const inline
Returns the grid number of the current position.
Definition at line 429 of file Grid.h.
Init()
void MeshCore::MeshGridIterator::Init () inline
Sets the iterator to the first element
Definition at line 385 of file Grid.h.
Referenced by MeshCore::MeshTrimByPlane::CheckFacets(), MeshCore::MeshTrimming::CheckFacets(), MeshCore::MeshAlgorithm::CheckFacets(), MeshCore::MeshAlgorithm::CutWithPlane(), MeshCore::MeshEvalSelfIntersection::Evaluate(), MeshCore::MeshAlgorithm::GetFacetsFromPlane(), MeshCore::MeshAlgorithm::GetFacetsFromToolMesh(), MeshCore::MeshEvalSelfIntersection::GetIntersections(), MeshCore::MeshProjection::projectLineOnMesh(), MeshCore::MeshFacetGrid::Verify(), and MeshCore::MeshPointGrid::Verify().
InitOnRay() [1/2]
bool MeshGridIterator::InitOnRay (const Base::Vector3f & rclPt, const Base::Vector3f & rclDir, float fMaxSearchArea, std::vector< ElementIndex > & raulElements)
Searches for facets around the ray.
Definition at line 1140 of file Grid.cpp.
References InitOnRay().
InitOnRay() [2/2]
bool MeshGridIterator::InitOnRay (const Base::Vector3f & rclPt, const Base::Vector3f & rclDir, std::vector< ElementIndex > & raulElements)
Searches for facets around the ray.
Definition at line 1150 of file Grid.cpp.
References MeshCore::MeshGrid::_aulGrid, FLOAT_MAX, MeshCore::MeshGrid::GetBoundBox(), Base::BoundBox3< Precision >::IntersectWithLine(), Base::BoundBox3< Precision >::IsInBox(), FreeCADInit::Length, and MeshCore::MeshGrid::Position().
Referenced by InitOnRay(), and MeshCore::MeshAlgorithm::NearestFacetOnRay().
More()
bool MeshCore::MeshGridIterator::More () const inline
Checks if the iterator has not yet reached the end position.
Definition at line 390 of file Grid.h.
Referenced by MeshCore::MeshTrimByPlane::CheckFacets(), MeshCore::MeshTrimming::CheckFacets(), MeshCore::MeshAlgorithm::CheckFacets(), MeshCore::MeshAlgorithm::CutWithPlane(), MeshCore::MeshEvalSelfIntersection::Evaluate(), MeshCore::MeshAlgorithm::GetFacetsFromPlane(), MeshCore::MeshAlgorithm::GetFacetsFromToolMesh(), MeshCore::MeshEvalSelfIntersection::GetIntersections(), MeshCore::MeshProjection::projectLineOnMesh(), MeshCore::MeshFacetGrid::Verify(), and MeshCore::MeshPointGrid::Verify().
Next()
void MeshCore::MeshGridIterator::Next () inline
Go to the next grid.
Definition at line 395 of file Grid.h.
Referenced by MeshCore::MeshTrimByPlane::CheckFacets(), MeshCore::MeshTrimming::CheckFacets(), MeshCore::MeshAlgorithm::CheckFacets(), MeshCore::MeshAlgorithm::CutWithPlane(), MeshCore::MeshEvalSelfIntersection::Evaluate(), MeshCore::MeshAlgorithm::GetFacetsFromPlane(), MeshCore::MeshAlgorithm::GetFacetsFromToolMesh(), MeshCore::MeshEvalSelfIntersection::GetIntersections(), MeshCore::MeshProjection::projectLineOnMesh(), MeshCore::MeshFacetGrid::Verify(), and MeshCore::MeshPointGrid::Verify().
NextOnRay()
bool MeshGridIterator::NextOnRay (std::vector< ElementIndex > & raulElements)
Searches for facets around the ray.
Definition at line 1195 of file Grid.cpp.
References MeshCore::MeshGrid::_aulGrid, Base::BoundBox3< Precision >::BACK, Base::BoundBox3< Precision >::BOTTOM, MeshCore::MeshGrid::CheckPos(), Base::BoundBox3< Precision >::FRONT, MeshCore::MeshGrid::GetBoundBox(), Base::BoundBox3< Precision >::GetSideFromRay(), Base::BoundBox3< Precision >::INVALID, Base::BoundBox3< Precision >::LEFT, FreeCADInit::Length, RobotExample::pos, Base::BoundBox3< Precision >::RIGHT, and Base::BoundBox3< Precision >::TOP.
Referenced by MeshCore::MeshAlgorithm::NearestFacetOnRay().
The documentation for this class was generated from the following files:
Grid.h
Grid.cpp