FreeCAD: Fem::StdMeshers_Deflection1DPy Class Reference
Fem::StdMeshers_Deflection1DPy Class Reference
#include <HypothesisPy.h>
Public Member Functions
StdMeshers_Deflection1DPy (int hypId, int studyId, SMESH_Gen *gen)
~StdMeshers_Deflection1DPy () override
Py::Object setDeflection (const Py::Tuple &args)
Public Member Functions inherited from Fem::SMESH_HypothesisPy< StdMeshers_Deflection1DPy >
SMESH_HypothesisPy (SMESH_Hypothesis *)
~SMESH_HypothesisPy () override
Py::Object getattr (const char *name) override
Py::Object repr () override
Py::Object getLibName (const Py::Tuple &args)
Py::Object setLibName (const Py::Tuple &args)
Py::Object isAuxiliary (const Py::Tuple &args)
Py::Object setParametersByMesh (const Py::Tuple &args)
std::shared_ptr< SMESH_Hypothesis > getHypothesis () const
Static Public Member Functions
static void init_type (PyObject *)
Static Public Member Functions inherited from Fem::SMESH_HypothesisPy< StdMeshers_Deflection1DPy >
static void init_type (PyObject *)
Additional Inherited Members
Public Types inherited from Fem::SMESH_HypothesisPy< StdMeshers_Deflection1DPy >
using SMESH_HypothesisPyBase = SMESH_HypothesisPy< StdMeshers_Deflection1DPy >
Protected Member Functions inherited from Fem::SMESH_HypothesisPy< StdMeshers_Deflection1DPy >
type * hypothesis () const
Detailed Description
Definition at line 510 of file HypothesisPy.h.
Constructor & Destructor Documentation
StdMeshers_Deflection1DPy()
StdMeshers_Deflection1DPy::StdMeshers_Deflection1DPy (int hypId, int studyId, SMESH_Gen * gen)
Definition at line 680 of file HypothesisPy.cpp.
~StdMeshers_Deflection1DPy()
StdMeshers_Deflection1DPy::~StdMeshers_Deflection1DPy () override default
Member Function Documentation
init_type()
void StdMeshers_Deflection1DPy::init_type (PyObject * module) static
Definition at line 664 of file HypothesisPy.cpp.
References Fem::SMESH_HypothesisPy< StdMeshers_Deflection1DPy >::init_type(), src.Mod.PartDesign.fcgear.svggear::module, and setDeflection().
Referenced by PyMOD_INIT_FUNC().
setDeflection()
Py::Object StdMeshers_Deflection1DPy::setDeflection (const Py::Tuple & args)
Definition at line 687 of file HypothesisPy.cpp.
References toolbit-attributes::args.
Referenced by init_type().
The documentation for this class was generated from the following files:
HypothesisPy.h
HypothesisPy.cpp