FreeCAD: Gui::Dialog::find_placement Class Reference
Gui::Dialog::find_placement Class Reference
Public Member Functions
find_placement (const std::string &name)
bool operator() (const std::pair< std::string, App::Property * > &elem) const
Static Public Member Functions
static App::PropertyPlacement * getProperty (const App::DocumentObject *obj, const std::string &propertyName)
Public Attributes
std::string propertyname
Detailed Description
Definition at line 57 of file Gui/Placement.cpp.
Constructor & Destructor Documentation
find_placement()
Gui::Dialog::find_placement::find_placement (const std::string & name) inline explicit
Definition at line 60 of file Gui/Placement.cpp.
Member Function Documentation
getProperty()
static App::PropertyPlacement* Gui::Dialog::find_placement::getProperty (const App::DocumentObject * obj, const std::string & propertyName) inline static
Definition at line 83 of file Gui/Placement.cpp.
References App::ExtensionContainer::getPropertyMap(), and propertyName().
Referenced by Gui::Dialog::Placement::setPlacementAndBindObject().
operator()()
bool Gui::Dialog::find_placement::operator() (const std::pair< std::string, App::Property * > & elem) const inline
Definition at line 63 of file Gui/Placement.cpp.
References Base::Type::fromName(), App::Property::Hidden, Init::parent, and App::Property::ReadOnly.
Member Data Documentation
propertyname
std::string Gui::Dialog::find_placement::propertyname
Definition at line 99 of file Gui/Placement.cpp.
The documentation for this class was generated from the following file:
Gui/Placement.cpp