FreeCAD: TechDrawGui::QGIProjGroup Class Reference
TechDrawGui::QGIProjGroup Class Reference
#include <QGIProjGroup.h>
Public Types
enum { Type = QGraphicsItem::UserType + 113 }
Public Types inherited from TechDrawGui::QGIViewCollection
enum { Type = QGraphicsItem::UserType + 110 }
Public Types inherited from TechDrawGui::QGIView
enum { Type = QGraphicsItem::UserType + 101 }
Public Member Functions
QGIProjGroup ()
~QGIProjGroup () override=default
int type () const override
void alignTo (QGIProjGroup *, const QString &alignment)
void rotateView () override
void drawBorder () override
Public Member Functions inherited from TechDrawGui::QGIViewCollection
QGIViewCollection ()
~QGIViewCollection () override=default
int type () const override
Public Member Functions inherited from TechDrawGui::QGIView
QGIView ()
int type () const override
QRectF boundingRect () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
const char * getViewName () const
const std::string getViewNameAsString () const
void setViewFeature (TechDraw::DrawView *obj)
TechDraw::DrawView * getViewObject () const
MDIViewPage * getMDIViewPage () const
double getScale ()
void hideFrame ()
virtual bool getFrameState ()
virtual void toggleCache (bool state)
virtual void updateView (bool update=false)
virtual void isVisible (bool state)
virtual bool isVisible ()
virtual bool getGroupSelection ()
virtual void setGroupSelection (bool isSelected)
virtual void setGroupSelection (bool isSelected, const std::vector< std::string > &subNames)
virtual void draw ()
virtual void drawCaption ()
void makeMark (double xPos, double yPos, QColor color=Qt::red)
void makeMark (Base::Vector3d pos, QColor color=Qt::red)
void makeMark (QPointF pos, QColor color=Qt::red)
void setPosition (qreal xPos, qreal yPos)
qreal getY ()
bool isInnerView () const
void isInnerView (bool state)
QGIViewClip * getClipGroup ()
bool isSnapping ()
void snapPosition (QPointF &position)
void snapSectionView (const TechDraw::DrawViewSection *sectionView, QPointF &newPosition)
Base::Vector3d projItemPagePos (TechDraw::DrawViewPart *item)
void alignTo (QGraphicsItem *, const QString &alignment)
QColor prefNormalColor ()
QColor getNormalColor ()
void setNormalColor (QColor color)
QColor getPreColor ()
QColor getSelectColor ()
QColor getCurrentColor ()
void setCurrentColor (QColor color)
QColor getSettingColor ()
void setSettingColor (QColor color)
virtual void setStack (int z)
virtual void setStackFromVP ()
QFont getFont ()
void setFont (QFont font)
virtual void removeChild (QGIView *child)
virtual void addArbitraryItem (QGraphicsItem *qgi)
virtual void switchParentItem (QGIView *targetParent)
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
Protected Member Functions
bool sceneEventFilter (QGraphicsItem *watched, QEvent *event) override
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
QGIView * getAnchorQItem () const
Protected Member Functions inherited from TechDrawGui::QGIView
QGIView * getQGIVByName (std::string name)
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
virtual QRectF customChildrenBoundingRect () const
void dumpRect (const char *text, QRectF rect)
Base::Reference< ParameterGrp > getParmGroupCol ()
Additional Inherited Members
Static Public Member Functions inherited from TechDrawGui::QGIView
static Gui::ViewProvider * getViewProvider (App::DocumentObject *obj)
static ViewProviderPage * getViewProviderPage (TechDraw::DrawView *dView)
static int calculateFontPixelSize (double sizeInMillimetres)
static int calculateFontPixelWidth (const QFont &font)
static QString getPrefFont ()
static double getPrefFontSize ()
static double getDimFontSize ()
static int exactFontSize (std::string fontFamily, double nominalSize)
Static Public Attributes inherited from TechDrawGui::QGIView
static const double DefaultFontSizeInMM = 5.0
Detailed Description
Definition at line 44 of file QGIProjGroup.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 52 of file QGIProjGroup.h.
Constructor & Destructor Documentation
QGIProjGroup()
QGIProjGroup::QGIProjGroup ()
Definition at line 42 of file QGIProjGroup.cpp.
~QGIProjGroup()
TechDrawGui::QGIProjGroup::~QGIProjGroup () override default
Member Function Documentation
alignTo()
void TechDrawGui::QGIProjGroup::alignTo (QGIProjGroup * , const QString & alignment)
drawBorder()
void QGIProjGroup::drawBorder () override virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 201 of file QGIProjGroup.cpp.
getAnchorQItem()
QGIView * QGIProjGroup::getAnchorQItem () const protected
Definition at line 174 of file QGIProjGroup.cpp.
References TechDraw::DrawProjGroup::Anchor, App::PropertyLink::getValue(), and TechDrawGui::QGIView::getViewName().
Referenced by mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and sceneEventFilter().
itemChange()
QVariant QGIProjGroup::itemChange (GraphicsItemChange change, const QVariant & value) override protected
Definition at line 94 of file QGIProjGroup.cpp.
References Base::BaseClass::isDerivedFrom(), TechDrawGui::QGIView::itemChange(), and type().
mouseMoveEvent()
void QGIProjGroup::mouseMoveEvent (QGraphicsSceneMouseEvent * event) override protected
Definition at line 144 of file QGIProjGroup.cpp.
References getAnchorQItem(), and TechDrawGui::QGIView::mouseMoveEvent().
Referenced by sceneEventFilter().
mousePressEvent()
void QGIProjGroup::mousePressEvent (QGraphicsSceneMouseEvent * event) override protected
Definition at line 132 of file QGIProjGroup.cpp.
References getAnchorQItem().
Referenced by sceneEventFilter().
mouseReleaseEvent()
void QGIProjGroup::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) override protected
Definition at line 156 of file QGIProjGroup.cpp.
References TechDrawGui::Rez::appX(), getAnchorQItem(), TechDrawGui::QGIView::getViewObject(), TechDrawGui::QGIView::getY(), TechDrawGui::QGIView::mouseReleaseEvent(), TechDraw::DrawView::setPosition(), and MovieTool::x.
Referenced by sceneEventFilter().
rotateView()
void QGIProjGroup::rotateView () override virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 196 of file QGIProjGroup.cpp.
References Base::Console(), and Base::ConsoleSingleton::Warning().
sceneEventFilter()
bool QGIProjGroup::sceneEventFilter (QGraphicsItem * watched, QEvent * event) override protected
Definition at line 59 of file QGIProjGroup.cpp.
References getAnchorQItem(), mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
type()
int TechDrawGui::QGIProjGroup::type () const inline override
Definition at line 53 of file QGIProjGroup.h.
Referenced by itemChange().
The documentation for this class was generated from the following files:
QGIProjGroup.h
QGIProjGroup.cpp