FreeCAD: Path.Post.scripts.jtech_post Namespace Reference
Path.Post.scripts.jtech_post Namespace Reference
Functions
def processArguments (argstring)
def export (objectslist, filename, argstring)
def linenumber ()
def parse (pathobj)
Variables
TOOLTIP
now
parser
prog
add_help
action = "store_true",
help = "don't pop up editor before writing output",
default = "255",
TOOLTIP_ARGS
OUTPUT_COMMENTS
OUTPUT_HEADER
OUTPUT_LINE_NUMBERS
SHOW_EDITOR
MODAL
OUTPUT_DOUBLES
COMMAND_SPACE
LINENR
UNITS
UNIT_SPEED_FORMAT
UNIT_FORMAT
MACHINE_NAME
PRECISION
PREAMBLE
POSTAMBLE
PRE_FEED
POST_FEED
PRE_OPERATION
POST_OPERATION
TOOL_CHANGE
POWER_ON_DELAY
Function Documentation
export()
def Path.Post.scripts.jtech_post.export (objectslist, filename, argstring)
Definition at line 178 of file jtech_post.py.
References Path.Post.scripts.jtech_post.linenumber(), Path.Post.scripts.jtech_post.parse(), Path.Post.scripts.jtech_post.processArguments(), and Path.Post.scripts.refactored_centroid_post.str.
linenumber()
def Path.Post.scripts.jtech_post.linenumber ()
Definition at line 248 of file jtech_post.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.scripts.jtech_post.export(), and Path.Post.scripts.jtech_post.parse().
parse()
def Path.Post.scripts.jtech_post.parse (pathobj)
Definition at line 256 of file jtech_post.py.
References Path.Post.scripts.jtech_post.linenumber(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.scripts.jtech_post.export().
processArguments()
def Path.Post.scripts.jtech_post.processArguments (argstring)
Definition at line 130 of file jtech_post.py.
Referenced by Path.Post.scripts.jtech_post.export().
Variable Documentation
action
string Path.Post.scripts.jtech_post.action = "store_true",
Definition at line 48 of file jtech_post.py.
add_help
Path.Post.scripts.jtech_post.add_help
Definition at line 47 of file jtech_post.py.
COMMAND_SPACE
Path.Post.scripts.jtech_post.COMMAND_SPACE
Definition at line 90 of file jtech_post.py.
default
string Path.Post.scripts.jtech_post.default = "255",
Definition at line 56 of file jtech_post.py.
help
string Path.Post.scripts.jtech_post.help = "don't pop up editor before writing output",
Definition at line 48 of file jtech_post.py.
LINENR
Path.Post.scripts.jtech_post.LINENR
Definition at line 91 of file jtech_post.py.
MACHINE_NAME
Path.Post.scripts.jtech_post.MACHINE_NAME
Definition at line 98 of file jtech_post.py.
MODAL
Path.Post.scripts.jtech_post.MODAL
Definition at line 88 of file jtech_post.py.
now
Path.Post.scripts.jtech_post.now
Definition at line 45 of file jtech_post.py.
OUTPUT_COMMENTS
Path.Post.scripts.jtech_post.OUTPUT_COMMENTS
Definition at line 84 of file jtech_post.py.
OUTPUT_DOUBLES
Path.Post.scripts.jtech_post.OUTPUT_DOUBLES
Definition at line 89 of file jtech_post.py.
OUTPUT_HEADER
Path.Post.scripts.jtech_post.OUTPUT_HEADER
Definition at line 85 of file jtech_post.py.
OUTPUT_LINE_NUMBERS
Path.Post.scripts.jtech_post.OUTPUT_LINE_NUMBERS
Definition at line 86 of file jtech_post.py.
parser
Path.Post.scripts.jtech_post.parser
Definition at line 47 of file jtech_post.py.
POST_FEED
Path.Post.scripts.jtech_post.POST_FEED
Definition at line 115 of file jtech_post.py.
POST_OPERATION
Path.Post.scripts.jtech_post.POST_OPERATION
Definition at line 122 of file jtech_post.py.
POSTAMBLE
Path.Post.scripts.jtech_post.POSTAMBLE
Definition at line 107 of file jtech_post.py.
POWER_ON_DELAY
Path.Post.scripts.jtech_post.POWER_ON_DELAY
Definition at line 127 of file jtech_post.py.
PRE_FEED
Path.Post.scripts.jtech_post.PRE_FEED
Definition at line 111 of file jtech_post.py.
PRE_OPERATION
Path.Post.scripts.jtech_post.PRE_OPERATION
Definition at line 119 of file jtech_post.py.
PREAMBLE
Path.Post.scripts.jtech_post.PREAMBLE
Definition at line 102 of file jtech_post.py.
PRECISION
Path.Post.scripts.jtech_post.PRECISION
Definition at line 99 of file jtech_post.py.
prog
Path.Post.scripts.jtech_post.prog
Definition at line 47 of file jtech_post.py.
SHOW_EDITOR
Path.Post.scripts.jtech_post.SHOW_EDITOR
Definition at line 87 of file jtech_post.py.
TOOL_CHANGE
Path.Post.scripts.jtech_post.TOOL_CHANGE
Definition at line 125 of file jtech_post.py.
TOOLTIP
Path.Post.scripts.jtech_post.TOOLTIP
Definition at line 34 of file jtech_post.py.
TOOLTIP_ARGS
Path.Post.scripts.jtech_post.TOOLTIP_ARGS
Definition at line 81 of file jtech_post.py.
UNIT_FORMAT
Path.Post.scripts.jtech_post.UNIT_FORMAT
Definition at line 96 of file jtech_post.py.
UNIT_SPEED_FORMAT
Path.Post.scripts.jtech_post.UNIT_SPEED_FORMAT
Definition at line 95 of file jtech_post.py.
UNITS
Path.Post.scripts.jtech_post.UNITS
Definition at line 94 of file jtech_post.py.