FreeCAD: AppSandboxGui.cpp File Reference
AppSandboxGui.cpp File Reference
#include "PreCompiled.h"
#include <Python.h>
#include <Inventor/nodes/SoLineSet.h>
#include <Inventor/nodes/SoBaseColor.h>
#include <Inventor/nodes/SoSeparator.h>
#include <Inventor/nodes/SoCoordinate3.h>
#include <Base/Console.h>
#include <Base/Interpreter.h>
#include <Base/GeometryPyCXX.h>
#include <Base/Reader.h>
#include <Base/VectorPy.h>
#include <CXX/Extensions.hxx>
#include <CXX/Objects.hxx>
#include <App/Application.h>
#include <App/Document.h>
#include <App/DocumentObserver.h>
#include <Gui/Document.h>
#include <Gui/View3DInventor.h>
#include <Gui/View3DInventorViewer.h>
#include <Gui/Application.h>
#include "Workbench.h"
Classes
class ObjectObserver
class SandboxGui::Module
Namespaces
SandboxGui
Functions
void CreateSandboxCommands (void)
PyObject * SandboxGui::initModule ()
PyMOD_INIT_FUNC (SandboxGui)
Function Documentation
CreateSandboxCommands()
void CreateSandboxCommands (void)
Definition at line 1424 of file Mod/Sandbox/Gui/Command.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
PyMOD_INIT_FUNC()
PyMOD_INIT_FUNC (SandboxGui)
Definition at line 256 of file AppSandboxGui.cpp.
References Base::Console(), CreateSandboxCommands(), SCL.SimpleDataTypes::e, Base::BaseClass::init(), SandboxGui::SoWidgetShape::initClass(), SandboxGui::initModule(), Gui::Application::Instance, Base::Interpreter(), Base::InterpreterSingleton::loadModule(), Base::ConsoleSingleton::Log(), mod, and PyMOD_Return.