FreeCAD: TechDrawGui Namespace Reference
TechDrawGui Namespace Reference
Classes
class CompassDialWidget
class CompassWidget
struct dimVertex
class DirectionEditDialog
class DlgPageChooser
class DlgPrefsTechDrawAdvancedImp
class DlgPrefsTechDrawAnnotationImp
class DlgPrefsTechDrawColorsImp
class DlgPrefsTechDrawDimensionsImp
class DlgPrefsTechDrawGeneralImp
class DlgPrefsTechDrawHLRImp
class DlgPrefsTechDrawScaleImp
class DlgStringListEditor
class DlgTemplateField
class DrawGuiUtil
Convenient utility functions for TechDraw Gui Module.
class Grabber3d
Utility functions for obtaining 3d window image.
class KeyCombination
class MDIViewPage
class MDIViewPagePy
class Module
class PagePrinter
class PaperAttributes
class PathBuilder
class PATPathMaker
class PreferencesGui
class QGCustomBorder
class QGCustomClip
class QGCustomImage
class QGCustomLabel
class QGCustomRect
class QGCustomSvg
class QGCustomText
class QGDisplayArea
class QGEPath
class QGIArrow
class QGIBalloonLabel
class QGIBreakLine
class QGICaption
class QGICenterLine
class QGICMark
class QGIDatumLabel
class QGIDecoration
class QGIDimLines
class QGIDrawingTemplate
class QGIEdge
class QGIFace
class QGIGhostHighlight
class QGIHighlight
class QGILeaderLine
class QGIMatting
class QGIPrimPath
class QGIProjGroup
class QGIRichAnno
class QGISectionLine
class QGISVGTemplate
class QGITemplate
class QGITile
class QGIVertex
class QGIView
class QGIViewAnnotation
class QGIViewBalloon
class QGIViewClip
class QGIViewCollection
class QGIViewDimension
class QGIViewImage
class QGIViewPart
class QGIViewSection
class QGIViewSpreadsheet
class QGIViewSymbol
class QGIWeldSymbol
class QGMarker
QGMarker provides movable symbols.
class QGMText
class QGSPage
class QGTracker
class QGVNavStyle
class QGVNavStyleBlender
class QGVNavStyleCAD
class QGVNavStyleGesture
class QGVNavStyleInventor
class QGVNavStyleMaya
class QGVNavStyleOCC
class QGVNavStyleOpenSCAD
class QGVNavStyleRevit
class QGVNavStyleTinkerCAD
class QGVNavStyleTouchpad
class QGVPage
class Rez
Functions to handle mm resolution conversion.
class SvgString
class SymbolChooser
class TaskActiveView
class TaskBalloon
class TaskCenterLine
class TaskComplexSection
class TaskCosmeticCircle
class TaskCosmeticLine
class TaskCosVertex
class TaskCustomizeFormat
class TaskDetail
class TaskDimension
class TaskDimRepair
class TaskDlgActiveView
class TaskDlgBalloon
class TaskDlgCenterLine
class TaskDlgComplexSection
class TaskDlgCosmeticCircle
class TaskDlgCosmeticLine
class TaskDlgCosVertex
class TaskDlgCustomizeFormat
class TaskDlgDetail
class TaskDlgDimension
class TaskDlgDimReference
class TaskDlgGeomHatch
class TaskDlgHatch
class TaskDlgLeaderLine
class TaskDlgLineDecor
class TaskDlgLinkDim
class TaskDlgProjection
class TaskDlgProjGroup
class TaskDlgRichAnno
class TaskDlgSectionView
class TaskDlgSelectLineAttributes
class TaskDlgSurfaceFinishSymbols
class TaskDlgWeldingSymbol
class TaskGeomHatch
class TaskHatch
class TaskLeaderLine
class TaskLineDecor
class TaskLinkDim
class TaskProjection
class TaskProjGroup
class TaskRestoreLines
class TaskRichAnno
class TaskSectionView
class TaskSelectLineAttributes
class TaskSurfaceFinishSymbols
class TaskWeldingSymbol
class TechDrawHandler
class TemplateTextField
QGraphicsItemGroupm-derived class for the text fields in title blocks.
class TileImage
class VectorEditWidget
class ViewProviderAnnotation
class ViewProviderArch
class ViewProviderBalloon
class ViewProviderCosmeticExtension
class ViewProviderDimension
class ViewProviderDraft
class ViewProviderDrawingView
class ViewProviderDrawingViewExtension
class ViewProviderGeomHatch
class ViewProviderHatch
class ViewProviderImage
class ViewProviderLeader
class ViewProviderPage
class ViewProviderPageExtension
class ViewProviderProjGroup
class ViewProviderProjGroupItem
class ViewProviderRichAnno
class ViewProviderSpreadsheet
class ViewProviderSymbol
class ViewProviderTemplate
class ViewProviderTemplateExtension
class ViewProviderTile
class ViewProviderViewClip
class ViewProviderViewPart
class ViewProviderViewSection
class ViewProviderWeld
class Workbench
Typedefs
using ViewProviderCosmeticExtensionPython = Gui::ViewProviderExtensionPythonT< TechDrawGui::ViewProviderCosmeticExtension >
using ViewProviderDrawingViewExtensionPython = Gui::ViewProviderExtensionPythonT< TechDrawGui::ViewProviderDrawingViewExtension >
using ViewProviderPageExtensionPython = Gui::ViewProviderExtensionPythonT< TechDrawGui::ViewProviderPageExtension >
using ViewProviderTemplateExtensionPython = Gui::ViewProviderExtensionPythonT< TechDrawGui::ViewProviderTemplateExtension >
Enumerations
enum TrackerAction {
PICK = 0, EDIT = 1, CANCEL = 2, CANCELEDIT = 3,
FINISHED = 4, SAVE = 5
}
Functions
PyObject * initModule ()
void _selectDimensionAttributes (Gui::Command *cmd)
std::vector< TechDraw::DrawViewDimension * > _getDimensions (std::vector< Gui::SelectionObject > selection, std::string needDimType)
std::vector< dimVertex > _getVertexInfo (TechDraw::DrawViewPart *objFeat, std::vector< std::string > subNames)
TechDraw::DrawViewDimension * _createLinDimension (TechDraw::DrawViewPart *objFeat, std::string startVertex, std::string endVertex, std::string dimType)
bool _checkSelection (Gui::Command *cmd, std::vector< Gui::SelectionObject > &selection, std::string message)
bool _checkSelAndObj (Gui::Command *cmd, std::vector< Gui::SelectionObject > &selection, TechDraw::DrawViewPart *&objFeat, std::string message)
bool _checkSelObjAndSubs (Gui::Command *cmd, std::vector< Gui::SelectionObject > &selection, TechDraw::DrawViewPart *&objFeat, std::string message)
TechDraw::DrawViewDimension * makeArcLengthDimension (const TechDraw::ReferenceEntry &ref)
std::vector< TechDraw::DrawViewDimension * > makeObliqueChainDimension (std::vector< TechDraw::ReferenceEntry > refs)
std::vector< TechDraw::DrawViewDimension * > makeObliqueCoordDimension (std::vector< TechDraw::ReferenceEntry > refs)
TechDraw::LineFormat & _getActiveLineAttributes ()
Base::Vector3d _circleCenter (Base::Vector3d p1, Base::Vector3d p2, Base::Vector3d p3)
void _createThreadCircle (const std::string Name, TechDraw::DrawViewPart *objFeat, double factor)
void _createThreadLines (const std::vector< std::string > &SubNames, TechDraw::DrawViewPart *objFeat, double factor)
void _setLineAttributes (TechDraw::CosmeticEdge *cosEdge)
void _setLineAttributes (TechDraw::CenterLine *cosEdge)
void _setLineAttributes (TechDraw::CosmeticEdge *cosEdge, int style, float weight, App::Color color)
void _setLineAttributes (TechDraw::CenterLine *cosEdge, int style, float weight, App::Color color)
double _getAngle (Base::Vector3d center, Base::Vector3d point)
std::vector< Base::Vector3d > _getVertexPoints (const std::vector< std::string > &SubNames, TechDraw::DrawViewPart *objFeat)
return the vertices in the selection as [Base::Vector3d]
bool _checkSel (Gui::Command *cmd, std::vector< Gui::SelectionObject > &selection, TechDraw::DrawViewPart *&objFeat, const std::string &message)
std::string _createBalloon (Gui::Command *cmd, TechDraw::DrawViewPart *objFeat)
void execHoleCircle (Gui::Command *cmd)
Variables
struct {
} sortX
struct {
} sortY
constexpr int SVGSIZEW {64}
constexpr int SVGSIZEH {64}
constexpr uint32_t COLWHITE {0xfffff}
constexpr int ALPHALOW {0}
constexpr int ALPHAHIGH {255}
constexpr long int MAXSEGMENT {10000L}
constexpr long int MAXTILES {10000L}
const std::string SVGCOLDEFAULT = "#000000"
Typedef Documentation
ViewProviderCosmeticExtensionPython
using TechDrawGui::ViewProviderCosmeticExtensionPython = typedef Gui::ViewProviderExtensionPythonT<TechDrawGui::ViewProviderCosmeticExtension>
Definition at line 65 of file ViewProviderCosmeticExtension.h.
ViewProviderDrawingViewExtensionPython
using TechDrawGui::ViewProviderDrawingViewExtensionPython = typedef Gui::ViewProviderExtensionPythonT<TechDrawGui::ViewProviderDrawingViewExtension>
Definition at line 78 of file ViewProviderDrawingViewExtension.h.
ViewProviderPageExtensionPython
using TechDrawGui::ViewProviderPageExtensionPython = typedef Gui::ViewProviderExtensionPythonT<TechDrawGui::ViewProviderPageExtension>
Definition at line 83 of file ViewProviderPageExtension.h.
ViewProviderTemplateExtensionPython
using TechDrawGui::ViewProviderTemplateExtensionPython = typedef Gui::ViewProviderExtensionPythonT<TechDrawGui::ViewProviderTemplateExtension>
Definition at line 76 of file ViewProviderTemplateExtension.h.
Enumeration Type Documentation
TrackerAction
enum TechDrawGui::TrackerAction
Enumerator
PICK
EDIT
CANCEL
CANCELEDIT
FINISHED
SAVE
Definition at line 47 of file QGTracker.h.
Function Documentation
_checkSel()
bool TechDrawGui::_checkSel (Gui::Command * cmd, std::vector< Gui::SelectionObject > & selection, TechDraw::DrawViewPart *& objFeat, const std::string & message)
Definition at line 2057 of file CommandExtensionPack.cpp.
References Gui::getMainWindow(), Gui::Command::getSelection(), Gui::SelectionSingleton::getSelectionEx(), Path.Dressup.Utils::selection(), and Path.Log::warning().
Referenced by execCircleCenterLines(), execDrawCosmArc(), execDrawCosmCircle(), execDrawCosmCircle3Points(), execExtendShortenLine(), execHoleCircle(), execLineParallelPerpendicular(), execThreadBoltBottom(), execThreadBoltSide(), execThreadHoleBottom(), and execThreadHoleSide().
_checkSelAndObj()
bool TechDrawGui::_checkSelAndObj (Gui::Command * cmd, std::vector< Gui::SelectionObject > & selection, TechDraw::DrawViewPart *& objFeat, std::string message)
Definition at line 2428 of file CommandExtensionDims.cpp.
References _checkSelection(), Gui::getMainWindow(), Path.Dressup.Utils::selection(), and Path.Log::warning().
Referenced by _checkSelObjAndSubs().
_checkSelection()
bool TechDrawGui::_checkSelection (Gui::Command * cmd, std::vector< Gui::SelectionObject > & selection, std::string message)
Definition at line 2414 of file CommandExtensionDims.cpp.
References Gui::getMainWindow(), Gui::Command::getSelection(), Gui::SelectionSingleton::getSelectionEx(), Path.Dressup.Utils::selection(), and Path.Log::warning().
Referenced by _checkSelAndObj(), and execInsertPrefixChar().
_checkSelObjAndSubs()
bool TechDrawGui::_checkSelObjAndSubs (Gui::Command * cmd, std::vector< Gui::SelectionObject > & selection, TechDraw::DrawViewPart *& objFeat, std::string message)
Definition at line 2448 of file CommandExtensionDims.cpp.
References _checkSelAndObj(), Gui::getMainWindow(), Path.Dressup.Utils::selection(), importers.importIFCmulticore::subs, and Path.Log::warning().
Referenced by execCreateHorizChainDimension(), execCreateHorizChamferDimension(), execCreateHorizCoordDimension(), execCreateObliqueChainDimension(), execCreateObliqueCoordDimension(), execCreateVertChainDimension(), execCreateVertChamferDimension(), and execCreateVertCoordDimension().
_circleCenter()
Base::Vector3d TechDrawGui::_circleCenter (Base::Vector3d p1, Base::Vector3d p2, Base::Vector3d p3)
Definition at line 2105 of file CommandExtensionPack.cpp.
References exportCSG::center(), Part::Geom2dCircle::getCircleCenter(), draftgeoutils.general::v1(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by execDrawCosmCircle3Points(), and execHoleCircle().
_createBalloon()
std::string TechDrawGui::_createBalloon (Gui::Command * cmd, TechDraw::DrawViewPart * objFeat)
Definition at line 2034 of file CommandExtensionPack.cpp.
References Gui::Command::Doc, TechDraw::DrawView::findParentPage(), App::DocumentObject::getDocument(), Gui::Application::getDocument(), TechDrawGui::QGSPage::getDrawPage(), App::DocumentObject::getNameInDocument(), App::Document::getUniqueObjectName(), Gui::Document::getViewProvider(), and Gui::Application::Instance.
_createLinDimension()
TechDraw::DrawViewDimension * TechDrawGui::_createLinDimension (TechDraw::DrawViewPart * objFeat, std::string startVertex, std::string endVertex, std::string dimType)
Definition at line 2468 of file CommandExtensionDims.cpp.
References Gui::Command::Doc, doCommand, TechDraw::DrawView::findParentPage(), App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), App::Document::getObject(), App::Document::getUniqueObjectName(), replaceobj::objs, App::DocumentObject::recomputeFeature(), TechDraw::DrawViewDimension::References2D, App::PropertyLinkSubList::setValues(), importers.importIFCmulticore::subs, and App::DocumentObject::touch().
Referenced by execCreateHorizChainDimension(), execCreateHorizChamferDimension(), execCreateHorizCoordDimension(), execCreateVertChainDimension(), execCreateVertChamferDimension(), execCreateVertCoordDimension(), makeArcLengthDimension(), makeObliqueChainDimension(), and makeObliqueCoordDimension().
_createThreadCircle()
void TechDrawGui::_createThreadCircle (const std::string Name, TechDraw::DrawViewPart * objFeat, double factor)
Definition at line 2114 of file CommandExtensionPack.cpp.
References _setLineAttributes(), TechDraw::CosmeticExtension::addCosmeticEdge(), exportCSG::center(), TechDraw::CIRCLE, TechDraw::CosmeticExtension::getCosmeticEdge(), TechDraw::DrawViewPart::getGeomByIndex(), TechDraw::DrawUtil::getGeomTypeFromName(), TechDraw::DrawUtil::getIndexFromName(), TechDraw::DrawView::getScale(), and draftfunctions.scale::scale().
Referenced by execThreadBoltBottom(), and execThreadHoleBottom().
_createThreadLines()
void TechDrawGui::_createThreadLines (const std::vector< std::string > & SubNames, TechDraw::DrawViewPart * objFeat, double factor)
Definition at line 2138 of file CommandExtensionPack.cpp.
References _setLineAttributes(), TechDraw::CosmeticExtension::addCosmeticEdge(), TechDraw::GENERIC, TechDraw::CosmeticExtension::getCosmeticEdge(), TechDraw::DrawViewPart::getGeomByIndex(), TechDraw::DrawUtil::getGeomTypeFromName(), TechDraw::DrawUtil::getIndexFromName(), Gui::getMainWindow(), FreeCADInit::Length, and Path.Log::warning().
Referenced by execThreadBoltSide(), and execThreadHoleSide().
_getActiveLineAttributes()
LineFormat & TechDrawGui::_getActiveLineAttributes ()
Definition at line 2029 of file CommandExtensionPack.cpp.
Referenced by _setLineAttributes().
_getAngle()
double TechDrawGui::_getAngle (Base::Vector3d center, Base::Vector3d point)
get angle between x-axis and the vector from center to point. result is [0, 360]
Definition at line 2097 of file CommandExtensionPack.cpp.
References TechDraw::DrawUtil::angleWithX(), exportCSG::center(), DegreesHalfCircle, and M_PI.
Referenced by execDrawCosmArc().
_getDimensions()
std::vector< TechDraw::DrawViewDimension * > TechDrawGui::_getDimensions (std::vector< Gui::SelectionObject > selection, std::string needDimType)
Definition at line 2519 of file CommandExtensionDims.cpp.
References Base::Persistence::getClassTypeId(), App::PropertyEnumeration::getValueAsString(), Path.Dressup.Utils::selection(), and TechDraw::DrawViewDimension::Type.
Referenced by execCascadeHorizDimension(), execCascadeObliqueDimension(), execCascadeVertDimension(), execPosHorizChainDimension(), execPosObliqueChainDimension(), and execPosVertChainDimension().
_getVertexInfo()
std::vector< dimVertex > TechDrawGui::_getVertexInfo (TechDraw::DrawViewPart * objFeat, std::vector< std::string > subNames)
Definition at line 2499 of file CommandExtensionDims.cpp.
References TechDraw::DrawUtil::getGeomTypeFromName(), TechDraw::DrawUtil::getIndexFromName(), TechDraw::DrawViewPart::getProjVertexByIndex(), TechDrawGui::dimVertex::name, TechDrawGui::dimVertex::point, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by execCreateHorizChainDimension(), execCreateHorizChamferDimension(), execCreateHorizCoordDimension(), execCreateVertChainDimension(), execCreateVertChamferDimension(), execCreateVertCoordDimension(), makeObliqueChainDimension(), and makeObliqueCoordDimension().
_getVertexPoints()
std::vector< Base::Vector3d > TechDrawGui::_getVertexPoints (const std::vector< std::string > & SubNames, TechDraw::DrawViewPart * objFeat)
return the vertices in the selection as [Base::Vector3d]
Definition at line 2080 of file CommandExtensionPack.cpp.
References TechDraw::DrawUtil::getGeomTypeFromName(), TechDraw::DrawUtil::getIndexFromName(), and TechDraw::DrawViewPart::getProjVertexByIndex().
Referenced by execDrawCosmArc(), execDrawCosmCircle(), and execDrawCosmCircle3Points().
_selectDimensionAttributes()
void TechDrawGui::_selectDimensionAttributes (Gui::Command * cmd)
_setLineAttributes() [1/4]
void TechDrawGui::_setLineAttributes (TechDraw::CenterLine * cosEdge)
Definition at line 2194 of file CommandExtensionPack.cpp.
References _getActiveLineAttributes(), importDXF::getColor(), TechDraw::CenterLine::m_format, TechDraw::LineFormat::setColor(), TechDraw::LineFormat::setLineNumber(), TechDraw::LineFormat::setStyle(), TechDraw::LineFormat::setVisible(), and TechDraw::LineFormat::setWidth().
_setLineAttributes() [2/4]
void TechDrawGui::_setLineAttributes (TechDraw::CenterLine * cosEdge, int style, float weight, App::Color color)
Definition at line 2214 of file CommandExtensionPack.cpp.
References _getActiveLineAttributes(), TechDraw::CenterLine::m_format, TechDraw::LineFormat::setColor(), TechDraw::LineFormat::setLineNumber(), TechDraw::LineFormat::setStyle(), TechDraw::LineFormat::setVisible(), and TechDraw::LineFormat::setWidth().
Referenced by execCircleCenterLines(), execDrawCosmArc(), execDrawCosmCircle(), execDrawCosmCircle3Points(), execExtendShortenLine(), and execLineParallelPerpendicular().
_setLineAttributes() [3/4]
void TechDrawGui::_setLineAttributes (TechDraw::CosmeticEdge * cosEdge)
Definition at line 2184 of file CommandExtensionPack.cpp.
References _getActiveLineAttributes(), importDXF::getColor(), TechDraw::CosmeticEdge::m_format, TechDraw::LineFormat::setColor(), TechDraw::LineFormat::setLineNumber(), TechDraw::LineFormat::setStyle(), TechDraw::LineFormat::setVisible(), and TechDraw::LineFormat::setWidth().
Referenced by _createThreadCircle(), _createThreadLines(), and execHoleCircle().
_setLineAttributes() [4/4]
void TechDrawGui::_setLineAttributes (TechDraw::CosmeticEdge * cosEdge, int style, float weight, App::Color color)
Definition at line 2204 of file CommandExtensionPack.cpp.
References _getActiveLineAttributes(), TechDraw::CosmeticEdge::m_format, TechDraw::LineFormat::setColor(), TechDraw::LineFormat::setLineNumber(), TechDraw::LineFormat::setStyle(), TechDraw::LineFormat::setVisible(), and TechDraw::LineFormat::setWidth().
execHoleCircle()
void TechDrawGui::execHoleCircle (Gui::Command * cmd)
Definition at line 101 of file CommandExtensionPack.cpp.
References _checkSel(), _circleCenter(), _setLineAttributes(), TechDraw::CosmeticExtension::addCosmeticEdge(), TechDraw::ARCOFCIRCLE, exportCSG::center(), TechDraw::CIRCLE, Gui::SelectionSingleton::clearSelection(), Gui::Command::commitCommand(), TechDraw::CosmeticExtension::getCosmeticEdge(), TechDraw::DrawViewPart::getGeomByIndex(), TechDraw::DrawUtil::getGeomTypeFromName(), TechDraw::DrawUtil::getIndexFromName(), Gui::getMainWindow(), TechDraw::DrawView::getScale(), Gui::Command::getSelection(), FreeCADInit::Length, Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, TechDraw::CosmeticExtension::refreshCEGeoms(), TechDraw::DrawView::requestPaint(), Path.Dressup.Utils::selection(), and Path.Log::warning().
initModule()
PyObject * TechDrawGui::initModule ()
Definition at line 468 of file AppTechDrawGuiPy.cpp.
Referenced by PyMOD_INIT_FUNC().
makeArcLengthDimension()
DrawViewDimension * TechDrawGui::makeArcLengthDimension (const TechDraw::ReferenceEntry & ref)
Definition at line 2364 of file CommandExtensionDims.cpp.
References _createLinDimension(), TechDraw::DrawViewDimension::Arbitrary, TechDraw::pointPair::first(), TechDraw::DrawViewDimension::FormatSpec, TechDraw::DrawViewDimension::getLinearPoints(), TechDraw::ReferenceEntry::getObject(), TechDraw::ReferenceEntry::getSubName(), length(), TechDraw::pointPair::second(), App::PropertyQuantity::setValue(), App::PropertyString::setValue(), App::PropertyBool::setValue(), TechDraw::DrawView::X, TechDraw::DrawView::Y, and Base::Vector3< float_type >::y.
Referenced by TDHandlerDimension::createArcLengthDimension().
makeObliqueChainDimension()
std::vector< DrawViewDimension * > TechDrawGui::makeObliqueChainDimension (std::vector< TechDraw::ReferenceEntry > refs)
Definition at line 1429 of file CommandExtensionDims.cpp.
References _createLinDimension(), _getVertexInfo(), activeDimAttributes, SCL.SimpleDataTypes::f, TechDraw::pointPair::first(), dimAttributes::getCascadeSpacing(), TechDraw::LineGroup::getDefaultWidth(), TechDraw::DrawViewDimension::getLinearPoints(), TechDrawGui::dimVertex::name, Base::Vector3< float_type >::Normalize(), TechDrawGui::dimVertex::point, TechDraw::pointPair::second(), App::PropertyQuantity::setValue(), sortX, TechDraw::DrawView::X, and TechDraw::DrawView::Y.
Referenced by TDHandlerDimension::createChainDimension(), and execCreateObliqueChainDimension().
makeObliqueCoordDimension()
std::vector< DrawViewDimension * > TechDrawGui::makeObliqueCoordDimension (std::vector< TechDraw::ReferenceEntry > refs)
Definition at line 1814 of file CommandExtensionDims.cpp.
References _createLinDimension(), _getVertexInfo(), activeDimAttributes, TechDraw::pointPair::first(), dimAttributes::getCascadeSpacing(), TechDraw::LineGroup::getDefaultWidth(), TechDraw::DrawViewDimension::getLinearPoints(), TechDrawGui::dimVertex::name, Base::Vector3< float_type >::Normalize(), TechDrawGui::dimVertex::point, TechDraw::pointPair::second(), App::PropertyQuantity::setValue(), sortX, TechDraw::DrawView::X, Base::Vector3< float_type >::x, and TechDraw::DrawView::Y.
Referenced by TDHandlerDimension::createCoordDimension(), and execCreateObliqueCoordDimension().
Variable Documentation
ALPHAHIGH
constexpr int TechDrawGui::ALPHAHIGH {255} constexpr
Definition at line 70 of file QGIFace.h.
Referenced by TechDrawGui::QGIFace::QGIFace().
ALPHALOW
constexpr int TechDrawGui::ALPHALOW {0} constexpr
Definition at line 69 of file QGIFace.h.
Referenced by TechDrawGui::QGIFace::QGIFace().
COLWHITE
constexpr uint32_t TechDrawGui::COLWHITE {0xfffff} constexpr
Definition at line 68 of file QGIFace.h.
Referenced by TechDrawGui::QGIFace::QGIFace().
MAXSEGMENT
constexpr long int TechDrawGui::MAXSEGMENT {10000L} constexpr
Definition at line 71 of file QGIFace.h.
Referenced by TechDrawGui::QGIFace::getParameters().
MAXTILES
constexpr long int TechDrawGui::MAXTILES {10000L} constexpr
Definition at line 72 of file QGIFace.h.
Referenced by TechDrawGui::QGIFace::getParameters().
sortX
struct { ... } TechDrawGui::sortX
Referenced by execCreateHorizChainDimension(), execCreateHorizCoordDimension(), makeObliqueChainDimension(), and makeObliqueCoordDimension().
sortY
struct { ... } TechDrawGui::sortY
Referenced by execCreateVertChainDimension(), and execCreateVertCoordDimension().
SVGCOLDEFAULT
const std::string TechDrawGui::SVGCOLDEFAULT = "#000000"
Definition at line 73 of file QGIFace.h.
Referenced by TechDrawGui::QGIFace::buildPixHatch(), TechDrawGui::QGIFace::buildSvgHatch(), and TechDrawGui::QGIFace::multiselectEligible().
SVGSIZEH
constexpr int TechDrawGui::SVGSIZEH {64} constexpr
Definition at line 67 of file QGIFace.h.
Referenced by TechDrawGui::QGIFace::buildPixHatch(), and TechDrawGui::QGIFace::buildSvgHatch().
SVGSIZEW
constexpr int TechDrawGui::SVGSIZEW {64} constexpr
Definition at line 66 of file QGIFace.h.
Referenced by TechDrawGui::QGIFace::buildPixHatch(), and TechDrawGui::QGIFace::buildSvgHatch().