FreeCAD: ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.conical_stepped_hole_transition Class Reference
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.conical_stepped_hole_transition Class Reference
Public Member Functions
def __init__ (self, inherited0__name, transition_number, cone_apex_angle, cone_base_radius)
def transition_number ()
def cone_apex_angle ()
def cone_base_radius ()
Public Member Functions inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometric_representation_item
def __init__ (self, inherited0__name)
def dim ()
def wr1 (self)
Public Member Functions inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.representation_item
def name ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
transition_number
cone_apex_angle
cone_base_radius
Public Attributes inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.representation_item
name
Detailed Description
Entity conical_stepped_hole_transition definition.
:param transition_number
:type transition_number:positive_integer
:param cone_apex_angle
:type cone_apex_angle:plane_angle_measure
:param cone_base_radius
:type cone_base_radius:positive_length_measure
Definition at line 25932 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Constructor & Destructor Documentation
__init__()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.conical_stepped_hole_transition.__init__ (self, inherited0__name, transition_number, cone_apex_angle, cone_base_radius)
Definition at line 25944 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Member Function Documentation
cone_apex_angle()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.conical_stepped_hole_transition.cone_apex_angle ()
Definition at line 25965 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.conical_stepped_hole_transition._cone_apex_angle, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.conical_stepped_hole_transition.cone_apex_angle.
cone_base_radius()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.conical_stepped_hole_transition.cone_base_radius ()
Definition at line 25979 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.conical_stepped_hole_transition._cone_base_radius, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.conical_stepped_hole_transition.cone_base_radius.
transition_number()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.conical_stepped_hole_transition.transition_number ()
Definition at line 25951 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.conical_stepped_hole_transition._transition_number, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.conical_stepped_hole_transition.transition_number.
Member Data Documentation
cone_apex_angle
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.conical_stepped_hole_transition.cone_apex_angle
Definition at line 25947 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.conical_stepped_hole_transition.cone_apex_angle().
cone_base_radius
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.conical_stepped_hole_transition.cone_base_radius
Definition at line 25948 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.conical_stepped_hole_transition.cone_base_radius().
transition_number
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.conical_stepped_hole_transition.transition_number
Definition at line 25946 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.conical_stepped_hole_transition.transition_number().
The documentation for this class was generated from the following file:
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py