FreeCAD: SpreadsheetGui::DlgSheetConf Class Reference
SpreadsheetGui::DlgSheetConf Class Reference
#include <DlgSheetConf.h>
Public Slots
void onDiscard ()
Public Member Functions
DlgSheetConf (Spreadsheet::Sheet *sheet, App::Range range, QWidget *parent=nullptr)
~DlgSheetConf () override
void accept () override
App::Property * prepare (App::CellAddress &from, App::CellAddress &to, std::string &rangeConf, App::ObjectIdentifier &path, bool init)
Detailed Description
Definition at line 37 of file DlgSheetConf.h.
Constructor & Destructor Documentation
DlgSheetConf()
DlgSheetConf::DlgSheetConf (Spreadsheet::Sheet * sheet, App::Range range, QWidget * parent = nullptr) explicit
Definition at line 42 of file DlgSheetConf.cpp.
References App::Range::colCount(), draftgeoutils.intersections::connect(), App::Range::from(), toolbit-attributes::group, onDiscard(), prepare(), App::CellAddress::setCol(), App::Range::to(), and App::CellAddress::toString().
~DlgSheetConf()
DlgSheetConf::~DlgSheetConf () override
Definition at line 77 of file DlgSheetConf.cpp.
Member Function Documentation
accept()
void DlgSheetConf::accept () override
Definition at line 170 of file DlgSheetConf.cpp.
References Gui::Command::abortCommand(), App::Range::address(), Gui::cmdAppObjectArgs(), App::CellAddress::col(), App::Range::colCount(), Gui::Command::commitCommand(), App::Property::CopyOnChange, src.Mod.AddonManager.NetworkManager::count, Gui::Command::Doc, doCommand, SCL.SimpleDataTypes::e, FC_THROWM, App::Range::from(), Spreadsheet::Sheet::getCell(), Spreadsheet::Sheet::getCellBinding(), Base::BaseClass::getClassTypeId(), App::Property::getFullName(), App::DocumentObject::getFullName(), Spreadsheet::Sheet::getRange(), SplineSurface::i, App::Range::next(), App::Expression::parse(), prepare(), App::CellAddress::row(), App::Range::rowCount(), App::Property::setStatus(), App::Range::to(), and App::CellAddress::toString().
onDiscard
void DlgSheetConf::onDiscard () slot
Definition at line 290 of file DlgSheetConf.cpp.
References Gui::Command::abortCommand(), Gui::cmdAppObjectArgs(), App::Range::colCount(), Gui::Command::commitCommand(), src.Mod.AddonManager.NetworkManager::count, Gui::Command::Doc, doCommand, SCL.SimpleDataTypes::e, FC_THROWM, Spreadsheet::Sheet::getCellBinding(), SplineSurface::i, prepare(), App::Range::rowCount(), and App::CellAddress::toString().
Referenced by DlgSheetConf().
prepare()
App::Property * DlgSheetConf::prepare (App::CellAddress & from, App::CellAddress & to, std::string & rangeConf, App::ObjectIdentifier & path, bool init)
Definition at line 82 of file DlgSheetConf.cpp.
References App::CellAddress::col(), SCL.SimpleDataTypes::e, FC_THROWM, Spreadsheet::Sheet::getCell(), Spreadsheet::Sheet::getCellAddress(), Base::Persistence::getClassTypeId(), Base::BaseClass::getClassTypeId(), Spreadsheet::Cell::getExpression(), draftfunctions.svgshapes::getPath(), SIM::Coin3D::Quarter::Quarter::init(), App::Expression::parse(), App::Property::PropDynamic, App::CellAddress::row(), App::CellAddress::setRow(), and App::CellAddress::toString().
Referenced by accept(), DlgSheetConf(), and onDiscard().
The documentation for this class was generated from the following files:
DlgSheetConf.h
DlgSheetConf.cpp