FreeCAD: TechDrawGui::QGIEdge Class Reference
TechDrawGui::QGIEdge Class Reference
#include <QGIEdge.h>
Public Types
enum { Type = QGraphicsItem::UserType + 103 }
Public Types inherited from TechDrawGui::QGIPrimPath
enum { Type = QGraphicsItem::UserType + 170 }
Public Member Functions
QGIEdge (int index)
~QGIEdge () override=default
int type () const override
QRectF boundingRect () const override
QPainterPath shape () const override
int getProjIndex () const
void setCosmetic (bool state)
void setHiddenEdge (bool b)
bool getHiddenEdge ()
void setSmoothEdge (bool b)
bool getSmoothEdge ()
void setPrettyNormal () override
double getEdgeFuzz () const
void setLinePen (QPen isoPen)
void setSource (int source)
int getSource () const
void setCurrentPen () override
Public Member Functions inherited from TechDrawGui::QGIPrimPath
QGIPrimPath ()
~QGIPrimPath () override=default
int type () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
QPainterPath shape () const override
virtual void setPrettyPre ()
virtual void setPrettySel ()
virtual void setWidth (double w)
virtual double getWidth ()
Qt::PenStyle getStyle ()
void setStyle (Qt::PenStyle s)
void setStyle (int s)
virtual void setNormalColor (QColor c)
virtual void setCapStyle (Qt::PenCapStyle c)
void setFillStyle (Qt::BrushStyle f)
Qt::BrushStyle getFillStyle ()
void setFill (QColor c, Qt::BrushStyle s)
void setFill (QBrush b)
void resetFill ()
void setFillColor (QColor c)
QColor getFillColor ()
void setFillOverride (bool b)
Protected Member Functions
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event) override
bool multiselectEligible () override
QColor getHiddenColor ()
Qt::PenStyle getHiddenStyle ()
Protected Member Functions inherited from TechDrawGui::QGIPrimPath
void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
virtual QColor getNormalColor ()
virtual QColor getPreColor ()
virtual QColor getSelectColor ()
Base::Reference< ParameterGrp > getParmGroup ()
virtual Qt::PenCapStyle prefCapStyle ()
Protected Attributes
int projIndex
bool isCosmetic
bool isHiddenEdge
bool isSmoothEdge
Protected Attributes inherited from TechDrawGui::QGIPrimPath
bool isHighlighted
bool multiselectActivated
QPen m_pen
QColor m_colCurrent
QColor m_colNormal
bool m_colOverride
Qt::PenStyle m_styleCurrent
Qt::PenStyle m_styleNormal
double m_width
Qt::PenCapStyle m_capStyle
QBrush m_brush
Qt::BrushStyle m_fillStyleCurrent
QColor m_fillColorCurrent
QColor m_colDefFill
QColor m_colNormalFill
Qt::BrushStyle m_fillDef
Qt::BrushStyle m_fillNormal
Qt::BrushStyle m_fillSelect
bool m_fillOverride
Detailed Description
Definition at line 53 of file QGIEdge.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 79 of file QGIEdge.h.
Constructor & Destructor Documentation
QGIEdge()
QGIEdge::QGIEdge (int index) explicit
Definition at line 45 of file QGIEdge.cpp.
References isCosmetic, TechDrawGui::QGIPrimPath::m_width, setCosmetic(), and TechDrawGui::QGIPrimPath::setFill().
~QGIEdge()
TechDrawGui::QGIEdge::~QGIEdge () override default
Member Function Documentation
boundingRect()
QRectF QGIEdge::boundingRect () const override
Definition at line 110 of file QGIEdge.cpp.
References shape().
getEdgeFuzz()
double QGIEdge::getEdgeFuzz () const
Definition at line 104 of file QGIEdge.cpp.
References TechDrawGui::PreferencesGui::edgeFuzz().
Referenced by shape().
getHiddenColor()
QColor QGIEdge::getHiddenColor () protected
Definition at line 89 of file QGIEdge.cpp.
References App::Color::asValue(), and TechDrawGui::PreferencesGui::getAccessibleQColor().
Referenced by setPrettyNormal().
getHiddenEdge()
bool TechDrawGui::QGIEdge::getHiddenEdge () inline
Definition at line 89 of file QGIEdge.h.
getHiddenStyle()
Qt::PenStyle QGIEdge::getHiddenStyle () protected
Definition at line 95 of file QGIEdge.cpp.
Referenced by setHiddenEdge().
getProjIndex()
int TechDrawGui::QGIEdge::getProjIndex () const inline
Definition at line 85 of file QGIEdge.h.
Referenced by mouseDoubleClickEvent().
getSmoothEdge()
bool TechDrawGui::QGIEdge::getSmoothEdge () inline
Definition at line 91 of file QGIEdge.h.
getSource()
int TechDrawGui::QGIEdge::getSource () const inline
Definition at line 99 of file QGIEdge.h.
mouseDoubleClickEvent()
void QGIEdge::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * event) override protected
Definition at line 124 of file QGIEdge.cpp.
References Gui::Control(), Base::Persistence::getClassTypeId(), getProjIndex(), Init::parent, and Gui::ControlSingleton::showDialog().
multiselectEligible()
bool TechDrawGui::QGIEdge::multiselectEligible () inline override protected virtual
Reimplemented from TechDrawGui::QGIPrimPath.
Definition at line 107 of file QGIEdge.h.
setCosmetic()
void QGIEdge::setCosmetic (bool state)
Definition at line 61 of file QGIEdge.cpp.
References isCosmetic, and TechDrawGui::QGIPrimPath::setWidth().
Referenced by QGIEdge().
setCurrentPen()
void QGIEdge::setCurrentPen () override virtual
Reimplemented from TechDrawGui::QGIPrimPath.
Definition at line 141 of file QGIEdge.cpp.
References TechDrawGui::QGIPrimPath::m_colCurrent, TechDrawGui::QGIPrimPath::m_pen, and TechDrawGui::QGIPrimPath::m_width.
setHiddenEdge()
void QGIEdge::setHiddenEdge (bool b)
Definition at line 70 of file QGIEdge.cpp.
References SCL.SimpleDataTypes::b, getHiddenStyle(), isHiddenEdge, and TechDrawGui::QGIPrimPath::m_styleCurrent.
Referenced by TechDrawGui::QGIViewPart::drawAllEdges().
setLinePen()
void QGIEdge::setLinePen (QPen isoPen)
Definition at line 136 of file QGIEdge.cpp.
References TechDrawGui::QGIPrimPath::m_pen.
Referenced by TechDrawGui::QGIViewPart::drawAllEdges(), TechDrawGui::QGIViewPart::formatGeomFromCenterLine(), and TechDrawGui::QGIViewPart::formatGeomFromCosmetic().
setPrettyNormal()
void QGIEdge::setPrettyNormal () override virtual
Reimplemented from TechDrawGui::QGIPrimPath.
Definition at line 79 of file QGIEdge.cpp.
References getHiddenColor(), TechDrawGui::QGIPrimPath::getNormalColor(), isHiddenEdge, and TechDrawGui::QGIPrimPath::m_colCurrent.
Referenced by TechDrawGui::QGIViewPart::drawAllEdges().
setSmoothEdge()
void TechDrawGui::QGIEdge::setSmoothEdge (bool b) inline
Definition at line 90 of file QGIEdge.h.
setSource()
void TechDrawGui::QGIEdge::setSource (int source) inline
Definition at line 98 of file QGIEdge.h.
Referenced by TechDrawGui::QGIViewPart::drawAllEdges().
shape()
QPainterPath QGIEdge::shape () const override
Definition at line 115 of file QGIEdge.cpp.
References getEdgeFuzz().
Referenced by boundingRect().
type()
int TechDrawGui::QGIEdge::type () const inline override
Definition at line 81 of file QGIEdge.h.
Member Data Documentation
isCosmetic
bool TechDrawGui::QGIEdge::isCosmetic protected
Definition at line 111 of file QGIEdge.h.
Referenced by QGIEdge(), and setCosmetic().
isHiddenEdge
bool TechDrawGui::QGIEdge::isHiddenEdge protected
Definition at line 112 of file QGIEdge.h.
Referenced by setHiddenEdge(), and setPrettyNormal().
isSmoothEdge
bool TechDrawGui::QGIEdge::isSmoothEdge protected
Definition at line 113 of file QGIEdge.h.
projIndex
int TechDrawGui::QGIEdge::projIndex protected
Definition at line 109 of file QGIEdge.h.
The documentation for this class was generated from the following files:
QGIEdge.h
QGIEdge.cpp