FreeCAD: MatGui::Array2D Class Reference
MatGui::Array2D Class Reference
#include <Array2D.h>
Public Member Functions
Array2D (const QString &propertyName, const std::shared_ptr< Materials::Material > &material, QWidget *parent=nullptr)
~Array2D () override=default
void onDataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight, const QVector< int > &roles=QVector< int >())
void onDelete (bool checked)
void onContextMenu (const QPoint &pos)
void accept () override
void reject () override
Detailed Description
Definition at line 63 of file Array2D.h.
Constructor & Destructor Documentation
Array2D()
Array2D< T >::Array2D (const QString & propertyName, const std::shared_ptr< Materials::Material > & material, QWidget * parent = nullptr)
Definition at line 45 of file Array2D.cpp.
References accept(), Gui::Application::commandManager(), draftgeoutils.intersections::connect(), Base::Console(), Gui::CommandManager::getCommandByName(), Gui::Command::getShortcut(), Gui::Application::Instance, Base::ConsoleSingleton::Log(), onContextMenu(), onDelete(), propertyName(), and reject().
~Array2D()
MatGui::Array2D::~Array2D () override default
Member Function Documentation
accept()
void Array2D< T >::accept () override
Definition at line 201 of file Array2D.cpp.
Referenced by Array2D(), and MaterialEditor.MaterialEditor::verify().
onContextMenu()
void Array2D< T >::onContextMenu (const QPoint & pos)
Definition at line 138 of file Array2D.cpp.
References RobotExample::pos.
Referenced by Array2D().
onDataChanged()
void Array2D< T >::onDataChanged (const QModelIndex & topLeft, const QModelIndex & bottomRight, const QVector< int > & roles = QVector<int>())
Definition at line 127 of file Array2D.cpp.
onDelete()
void Array2D< T >::onDelete (bool checked)
Definition at line 153 of file Array2D.cpp.
Referenced by Array2D().
reject()
void Array2D< T >::reject () override
Definition at line 206 of file Array2D.cpp.
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and Array2D().
The documentation for this class was generated from the following files:
Array2D.h
Array2D.cpp