FreeCAD: MeshCore::MeshEvalPointOnEdge Class Reference
MeshCore::MeshEvalPointOnEdge Class Reference
#include <Degeneration.h>
Public Member Functions
MeshEvalPointOnEdge (const MeshKernel &rclM)
bool Evaluate () override
std::vector< PointIndex > GetPointIndices () const
std::vector< FacetIndex > GetFacetIndices () const
Public Member Functions inherited from MeshCore::MeshEvaluation
MeshEvaluation (const MeshKernel &rclB)
virtual ~MeshEvaluation ()=default
MeshEvaluation (const MeshEvaluation &)=delete
MeshEvaluation (MeshEvaluation &&)=delete
MeshEvaluation & operator= (const MeshEvaluation &)=delete
MeshEvaluation & operator= (MeshEvaluation &&)=delete
Additional Inherited Members
Protected Attributes inherited from MeshCore::MeshEvaluation
const MeshKernel & _rclMesh
Detailed Description
The MeshEvalPointOnEdge class searches for points that lie on or close to an edge of a triangle.
See also
MeshFixPointOnEdge
Author
Werner Mayer
Definition at line 756 of file Degeneration.h.
Constructor & Destructor Documentation
MeshEvalPointOnEdge()
MeshCore::MeshEvalPointOnEdge::MeshEvalPointOnEdge (const MeshKernel & rclM) inline explicit
Construction.
Definition at line 762 of file Degeneration.h.
Member Function Documentation
Evaluate()
bool MeshEvalPointOnEdge::Evaluate () override virtual
Searches for points that lie on edge of triangle.
Implements MeshCore::MeshEvaluation.
Definition at line 1225 of file Degeneration.cpp.
References MeshCore::MeshEvaluation::_rclMesh, MeshCore::MeshKernel::CountPoints(), MeshCore::MeshGrid::GetElements(), MeshCore::MeshKernel::GetFacets(), MeshCore::MeshKernel::GetPoints(), MeshCore::MeshFacet::HasOpenEdge(), and SplineSurface::i.
Referenced by MeshCore::MeshFixPointOnEdge::Fixup(), and Mesh::MeshObject::hasPointsOnEdge().
GetFacetIndices()
std::vector< FacetIndex > MeshEvalPointOnEdge::GetFacetIndices () const
Returns the indices of all facets with an open edge on that a point lies.
Definition at line 1272 of file Degeneration.cpp.
Referenced by MeshCore::MeshFixPointOnEdge::Fixup().
GetPointIndices()
std::vector< PointIndex > MeshEvalPointOnEdge::GetPointIndices () const
Returns the indices of all points on edge.
Definition at line 1267 of file Degeneration.cpp.
Referenced by MeshCore::MeshFixPointOnEdge::Fixup().
The documentation for this class was generated from the following files:
Degeneration.h
Degeneration.cpp