FreeCAD: automotive_design.configuration_interpolation Class Reference
automotive_design.configuration_interpolation Class Reference
Public Member Functions
def __init__ (self, previous_configuration_definition, next_configuration_definition, interpolation)
def previous_configuration_definition ()
def next_configuration_definition ()
def interpolation ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
previous_configuration_definition
next_configuration_definition
interpolation
Detailed Description
Entity configuration_interpolation definition.
:param previous_configuration_definition
:type previous_configuration_definition:configuration_definition
:param next_configuration_definition
:type next_configuration_definition:configuration_definition
:param interpolation
:type interpolation:interpolation_type
Definition at line 20079 of file automotive_design.py.
Constructor & Destructor Documentation
__init__()
def automotive_design.configuration_interpolation.__init__ (self, previous_configuration_definition, next_configuration_definition, interpolation)
Definition at line 20091 of file automotive_design.py.
Member Function Documentation
interpolation()
def automotive_design.configuration_interpolation.interpolation ()
Definition at line 20125 of file automotive_design.py.
References automotive_design.configuration_interpolation._interpolation, SCL.TypeChecker.check_type(), and automotive_design.configuration_interpolation.interpolation.
next_configuration_definition()
def automotive_design.configuration_interpolation.next_configuration_definition ()
Definition at line 20111 of file automotive_design.py.
References automotive_design.configuration_interpolation._next_configuration_definition, SCL.TypeChecker.check_type(), and automotive_design.configuration_interpolation.next_configuration_definition.
previous_configuration_definition()
def automotive_design.configuration_interpolation.previous_configuration_definition ()
Definition at line 20097 of file automotive_design.py.
References automotive_design.configuration_interpolation._previous_configuration_definition, SCL.TypeChecker.check_type(), and automotive_design.configuration_interpolation.previous_configuration_definition.
Member Data Documentation
interpolation
automotive_design.configuration_interpolation.interpolation
Definition at line 20094 of file automotive_design.py.
Referenced by automotive_design.configuration_interpolation.interpolation().
next_configuration_definition
automotive_design.configuration_interpolation.next_configuration_definition
Definition at line 20093 of file automotive_design.py.
Referenced by automotive_design.configuration_interpolation.next_configuration_definition().
previous_configuration_definition
automotive_design.configuration_interpolation.previous_configuration_definition
Definition at line 20092 of file automotive_design.py.
Referenced by automotive_design.configuration_interpolation.previous_configuration_definition().
The documentation for this class was generated from the following file:
automotive_design.py