FreeCAD: Import::ImportOCAF2 Class Reference
Import::ImportOCAF2 Class Reference
#include <ImportOCAF2.h>
Public Types
enum ImportMode {
SingleDoc = 0, GroupPerDoc = 1, GroupPerDir = 2, ObjectPerDoc = 3,
ObjectPerDir = 4, ModeMax
}
Public Member Functions
ImportOCAF2 (Handle(TDocStd_Document) h, App::Document *d, const std::string &name)
virtual ~ImportOCAF2 ()
App::DocumentObject * loadShapes ()
void setImportOptions (ImportOCAFOptions opts)
void setMerge (bool enable)
void setUseLinkGroup (bool enable)
void setBaseName (bool enable)
void setImportHiddenObject (bool enable)
void setReduceObjects (bool enable)
void setShowProgress (bool enable)
void setExpandCompound (bool enable)
void setMode (int m)
int getMode () const
Static Public Member Functions
static ImportOCAFOptions customImportOptions ()
Friends
class ImportLegacy
Detailed Description
Definition at line 77 of file ImportOCAF2.h.
Member Enumeration Documentation
ImportMode
enum Import::ImportOCAF2::ImportMode
Enumerator
SingleDoc
GroupPerDoc
GroupPerDir
ObjectPerDoc
ObjectPerDir
ModeMax
Definition at line 112 of file ImportOCAF2.h.
Constructor & Destructor Documentation
ImportOCAF2()
ImportOCAF2::ImportOCAF2 (Handle(TDocStd_Document) h, App::Document * d, const std::string & name)
Definition at line 81 of file ImportOCAF2.cpp.
References Base::FileInfo::dirPath(), App::Document::FileName, App::PropertyString::getValue(), App::Document::isSaved(), setUseLinkGroup(), and Import::ImportOCAFOptions::useLinkGroup.
~ImportOCAF2()
ImportOCAF2::~ImportOCAF2 () virtual default
Member Function Documentation
customImportOptions()
ImportOCAFOptions ImportOCAF2::customImportOptions () static
Definition at line 99 of file ImportOCAF2.cpp.
References App::Color::a, Import::ImportOCAFOptions::defaultEdgeColor, Import::ImportOCAFOptions::defaultFaceColor, Import::ImportOCAFOptions::expandCompound, App::GetApplication(), Part::OCAF::ImportExportSettings::getExpandCompound(), Part::OCAF::ImportExportSettings::getImportHiddenObject(), Part::OCAF::ImportExportSettings::getImportMode(), App::Color::getPackedValue(), App::Application::GetParameterGroupByPath(), Part::OCAF::ImportExportSettings::getReadShapeCompoundMode(), Part::OCAF::ImportExportSettings::getReduceObjects(), Part::OCAF::ImportExportSettings::getShowProgress(), Part::OCAF::ImportExportSettings::getUseBaseName(), Part::OCAF::ImportExportSettings::getUseLinkGroup(), Import::ImportOCAFOptions::importHidden, Import::ImportOCAFOptions::merge, Import::ImportOCAFOptions::mode, Import::ImportOCAFOptions::reduceObjects, App::Color::setPackedValue(), Import::ImportOCAFOptions::showProgress, Import::ImportOCAFOptions::useBaseName, and Import::ImportOCAFOptions::useLinkGroup.
getMode()
int Import::ImportOCAF2::getMode () const inline
Definition at line 122 of file ImportOCAF2.h.
loadShapes()
App::DocumentObject * ImportOCAF2::loadShapes ()
Definition at line 505 of file ImportOCAF2.cpp.
References App::Document::addObject(), src.Mod.AddonManager.NetworkManager::count, App::Document::DepSort, Import::Tools::dumpLabels(), FC_LOG, FC_LOG_INSTANCE, FC_LOGLEVEL_LOG, Base::Persistence::getClassTypeId(), App::Document::getDependencyList(), Part::Feature::getTopoShape(), SplineSurface::i, Import::ImportOCAFOptions::importHidden, ImportLegacy, Path.Log::info(), Base::BaseClass::isDerivedFrom(), App::DocumentObject::Label, Import::Tools::labelName(), App::ExpressionParser::labels, Import::ImportOCAFOptions::merge, replaceobj::objs, App::DocumentObject::recomputeFeature(), Part::PropertyPartShape::setValue(), App::PropertyString::setValue(), Part::Feature::Shape, Import::ImportOCAFOptions::showProgress, Import::ImportOCAFOptions::useLinkGroup, and TestSpreadsheet::v.
setBaseName()
void Import::ImportOCAF2::setBaseName (bool enable) inline
Definition at line 91 of file ImportOCAF2.h.
setExpandCompound()
void Import::ImportOCAF2::setExpandCompound (bool enable) inline
Definition at line 107 of file ImportOCAF2.h.
setImportHiddenObject()
void Import::ImportOCAF2::setImportHiddenObject (bool enable) inline
Definition at line 95 of file ImportOCAF2.h.
setImportOptions()
void ImportOCAF2::setImportOptions (ImportOCAFOptions opts)
Definition at line 127 of file ImportOCAF2.cpp.
References src.Mod.PartDesign.fcgear.svggear::opts, setUseLinkGroup(), and Import::ImportOCAFOptions::useLinkGroup.
setMerge()
void Import::ImportOCAF2::setMerge (bool enable) inline
Definition at line 86 of file ImportOCAF2.h.
setMode()
void ImportOCAF2::setMode (int m)
Definition at line 139 of file ImportOCAF2.cpp.
References Base::FileInfo::dirPath(), FC_WARN, App::Document::FileName, App::PropertyString::getValue(), App::Document::isSaved(), test::m, Import::ImportOCAFOptions::mode, ModeMax, and SingleDoc.
setReduceObjects()
void Import::ImportOCAF2::setReduceObjects (bool enable) inline
Definition at line 99 of file ImportOCAF2.h.
setShowProgress()
void Import::ImportOCAF2::setShowProgress (bool enable) inline
Definition at line 103 of file ImportOCAF2.h.
setUseLinkGroup()
void ImportOCAF2::setUseLinkGroup (bool enable)
Definition at line 133 of file ImportOCAF2.cpp.
References Import::ImportOCAFOptions::useLinkGroup.
Referenced by ImportOCAF2(), and setImportOptions().
Friends And Related Function Documentation
ImportLegacy
friend class ImportLegacy friend
Definition at line 197 of file ImportOCAF2.h.
Referenced by loadShapes().
The documentation for this class was generated from the following files:
ImportOCAF2.h
ImportOCAF2.cpp