FreeCAD: PartDesignGui::TaskFeaturePick Class Reference
PartDesignGui::TaskFeaturePick Class Reference
#include <TaskFeaturePick.h>
Public Types
enum featureStatus {
validFeature = 0, invalidShape, noWire, isUsed,
otherBody, otherPart, notInBody, basePlane,
afterTip
}
Public Member Functions
TaskFeaturePick (std::vector< App::DocumentObject * > &objects, const std::vector< featureStatus > &status, bool singleFeatureSelect, QWidget *parent=nullptr)
~TaskFeaturePick () override
std::vector< App::DocumentObject * > getFeatures ()
std::vector< App::DocumentObject * > buildFeatures ()
void showExternal (bool val)
bool isSingleSelectionEnabled () const
Public Member Functions inherited from Gui::TaskView::TaskBox
TaskBox (QWidget *parent=nullptr)
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
QSize minimumSizeHint () const override
~TaskBox () override
void hideGroupBox ()
bool isGroupVisible () const
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (QWidget *parent=nullptr)
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
QBoxLayout * groupLayout ()
void setScheme (ActionPanelScheme *pointer)
bool isExpandable () const
bool hasHeader () const
QString headerText () const
QSize minimumSizeHint () const override
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Public Member Functions inherited from Gui::DocumentObserver
DocumentObserver ()
Constructor.
DocumentObserver (Document *)
virtual ~DocumentObserver ()
void attachDocument (Document *)
void detachDocument ()
Static Public Member Functions
static App::DocumentObject * makeCopy (App::DocumentObject *obj, std::string sub, bool independent)
Protected Slots
void onUpdate (bool)
void onSelectionChanged (const Gui::SelectionChanges &msg) override
void onItemSelectionChanged ()
void onDoubleClick (QListWidgetItem *item)
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Protected Member Functions
void slotDeletedObject (const Gui::ViewProviderDocumentObject &Obj) override
void slotUndoDocument (const Gui::Document &Doc) override
void slotDeleteDocument (const Gui::Document &Doc) override
Protected Member Functions inherited from Gui::TaskView::TaskBox
void showEvent (QShowEvent *) override
void actionEvent (QActionEvent *) override
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
void paintEvent (QPaintEvent *event) override
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void showHide ()
void setExpandable (bool expandable=true)
void setHeader (bool enable=true)
void setHeaderText (const QString &title)
void setHeaderIcon (const QPixmap &icon)
Protected Attributes inherited from QSint::ActionGroup
double m_foldStep
double m_foldDelta
double m_fullHeight
double m_tempHeight
int m_foldDirection
QPixmap m_foldPixmap
class TaskHeader * myHeader
class TaskGroup * myGroup
QWidget * myDummy
ActionPanelScheme * myScheme
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Detailed Description
Definition at line 60 of file TaskFeaturePick.h.
Member Enumeration Documentation
featureStatus
enum PartDesignGui::TaskFeaturePick::featureStatus
Enumerator
validFeature
invalidShape
noWire
isUsed
otherBody
otherPart
notInBody
basePlane
afterTip
Definition at line 67 of file TaskFeaturePick.h.
Constructor & Destructor Documentation
TaskFeaturePick()
TaskFeaturePick::TaskFeaturePick (std::vector< App::DocumentObject * > & objects, const std::vector< featureStatus > & status, bool singleFeatureSelect, QWidget * parent = nullptr)
Definition at line 85 of file TaskFeaturePick.cpp.
References Gui::DocumentObserver::attachDocument(), draftgeoutils.intersections::connect(), Base::Persistence::getClassTypeId(), App::Document::getName(), Gui::Application::getViewProvider(), QSint::ActionGroup::groupLayout(), Gui::Application::Instance, invalidShape, importers.importIFCmulticore::objects, onDoubleClick(), onItemSelectionChanged(), onUpdate(), Gui::ViewProviderCoordinateSystem::setPlaneLabelVisibility(), Gui::ViewProviderCoordinateSystem::setTemporaryScale(), and Gui::ViewProviderCoordinateSystem::setTemporaryVisibility().
~TaskFeaturePick()
TaskFeaturePick::~TaskFeaturePick () override
Definition at line 178 of file TaskFeaturePick.cpp.
Member Function Documentation
buildFeatures()
std::vector< App::DocumentObject * > TaskFeaturePick::buildFeatures ()
Definition at line 268 of file TaskFeaturePick.cpp.
References UtilsAssembly::activePart(), Base::Console(), SCL.SimpleDataTypes::e, PartDesignGui::fixSketchSupport(), App::GetApplication(), PartDesignGui::getBody(), PartDesignGui::getBodyFor(), App::Application::getDocument(), App::Document::getObject(), PartDesignGui::getPartFor(), makeCopy(), notInBody, otherBody, otherPart, result, InitGui::t, and Base::ConsoleSingleton::Warning().
Referenced by PartDesignGui::TaskDlgFeaturePick::~TaskDlgFeaturePick().
getFeatures()
std::vector< App::DocumentObject * > TaskFeaturePick::getFeatures ()
Definition at line 242 of file TaskFeaturePick.cpp.
References App::GetApplication(), SplineSurface::i, result, and InitGui::t.
Referenced by PartDesignGui::TaskDlgFeaturePick::accept().
isSingleSelectionEnabled()
bool TaskFeaturePick::isSingleSelectionEnabled () const
Definition at line 506 of file TaskFeaturePick.cpp.
References App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
Referenced by onSelectionChanged().
makeCopy()
App::DocumentObject * TaskFeaturePick::makeCopy (App::DocumentObject * obj, std::string sub, bool independent) static
Definition at line 347 of file TaskFeaturePick.cpp.
References App::Document::addObject(), Part::AttachExtension::AttachmentSupport, PartDesign::ShapeBinder::buildShapeFromReferences(), App::Application::getActiveDocument(), App::GetApplication(), Base::Persistence::getClassTypeId(), Base::Type::getName(), App::DocumentObject::getNameInDocument(), App::ExtensionContainer::getPropertyList(), Part::PropertyPartShape::getShape(), Part::TopoShape::getSubShape(), Base::Persistence::getTypeId(), Part::PropertyPartShape::getValue(), Base::BaseClass::is(), Base::BaseClass::isDerivedFrom(), Part::AttachExtension::MapMode, Attacher::mm0Vertex, Attacher::mm1TwoPoints, Attacher::mmDeactivated, Attacher::mmFlatFace, App::Property::Paste(), Part::PropertyPartShape::setValue(), App::PropertyEnumeration::setValue(), App::PropertyLinkSubList::setValue(), DrawingExample::Shape, and Part::Feature::Shape.
Referenced by PartDesignGui::TaskDlgDatumParameters::accept(), PartDesignGui::TaskPipeParameters::accept(), buildFeatures(), PartDesignGui::getReferencedSelection(), and prepareProfileBased().
onDoubleClick
void TaskFeaturePick::onDoubleClick (QListWidgetItem * item) protected slot
Definition at line 563 of file TaskFeaturePick.cpp.
References Gui::SelectionSingleton::addSelection(), Gui::Control(), Gui::Selection(), and InitGui::t.
Referenced by TaskFeaturePick().
onItemSelectionChanged
void TaskFeaturePick::onItemSelectionChanged () protected slot
Definition at line 544 of file TaskFeaturePick.cpp.
References Gui::SelectionSingleton::addSelection(), Gui::SelectionSingleton::clearSelection(), Gui::Selection(), and InitGui::t.
Referenced by TaskFeaturePick().
onSelectionChanged
void TaskFeaturePick::onSelectionChanged (const Gui::SelectionChanges & msg) override protected slot
Definition at line 516 of file TaskFeaturePick.cpp.
References Gui::SelectionChanges::AddSelection, Gui::Control(), draftutils.gui_utils::getSelection, isSingleSelectionEnabled(), Path.Op.Surface::msg, Gui::Selection(), and InitGui::t.
onUpdate
void TaskFeaturePick::onUpdate (bool) protected slot
Definition at line 228 of file TaskFeaturePick.cpp.
Referenced by TaskFeaturePick().
showExternal()
void TaskFeaturePick::showExternal (bool val)
Definition at line 600 of file TaskFeaturePick.cpp.
References toolbit-attributes::val.
Referenced by PartDesignGui::TaskDlgFeaturePick::showExternal().
slotDeletedObject()
void TaskFeaturePick::slotDeletedObject (const Gui::ViewProviderDocumentObject & Obj) override protected virtual
Notifies when the object is about to be removed.
Reimplemented from Gui::DocumentObserver.
Definition at line 578 of file TaskFeaturePick.cpp.
References DraftVecUtils::find().
slotDeleteDocument()
void TaskFeaturePick::slotDeleteDocument (const Gui::Document & Doc) override protected virtual
Notifies on document deletion
Reimplemented from Gui::DocumentObserver.
Definition at line 594 of file TaskFeaturePick.cpp.
References Gui::ControlSingleton::closeDialog(), and Gui::Control().
slotUndoDocument()
void TaskFeaturePick::slotUndoDocument (const Gui::Document & Doc) override protected virtual
Notifies on undo
Reimplemented from Gui::DocumentObserver.
Definition at line 587 of file TaskFeaturePick.cpp.
References Gui::ControlSingleton::closeDialog(), and Gui::Control().
The documentation for this class was generated from the following files:
TaskFeaturePick.h
TaskFeaturePick.cpp