FreeCAD: App::MeasureManager Class Reference
App::MeasureManager Class Reference
#include <MeasureManager.h>
Public Member Functions
MeasureManager ()
Static Public Member Functions
static void addMeasureHandler (const char *module, MeasureTypeMethod typeCb)
static bool hasMeasureHandler (const char *module)
static MeasureHandler getMeasureHandler (const char *module)
static MeasureHandler getMeasureHandler (const App::MeasureSelectionItem &selectionItem)
static MeasureElementType getMeasureElementType (const App::MeasureSelectionItem &selectionItem)
static void addMeasureType (MeasureType *measureType)
static void addMeasureType (std::string id, std::string label, std::string measureObj, MeasureValidateMethod validatorCb, MeasurePrioritizeMethod prioritizeCb)
static void addMeasureType (const char *id, const char *label, const char *measureObj, MeasureValidateMethod validatorCb, MeasurePrioritizeMethod prioritizeCb)
static const std::vector< MeasureType * > getMeasureTypes ()
static Py::Tuple getSelectionPy (const App::MeasureSelection &selection)
static std::vector< MeasureType * > getValidMeasureTypes (App::MeasureSelection selection, std::string mode)
Detailed Description
Definition at line 115 of file MeasureManager.h.
Constructor & Destructor Documentation
MeasureManager()
App::MeasureManager::MeasureManager ()
Definition at line 57 of file MeasureManager.cpp.
References buildPsets::handler, and src.Mod.PartDesign.fcgear.svggear::module.
Member Function Documentation
addMeasureHandler()
void App::MeasureManager::addMeasureHandler (const char * module, MeasureTypeMethod typeCb) static
Definition at line 63 of file MeasureManager.cpp.
Referenced by PartDesign::Measure::initialize(), Sketcher::Measure::initialize(), Part::MeasureClient::initialize(), and PyMOD_INIT_FUNC().
addMeasureType() [1/3]
void App::MeasureManager::addMeasureType (const char * id, const char * label, const char * measureObj, MeasureValidateMethod validatorCb, MeasurePrioritizeMethod prioritizeCb) static
Definition at line 135 of file MeasureManager.cpp.
References SplineSurface::i, Path.Dressup.Utils::selection(), and src.Mod.Test.testmakeWireString::String.
addMeasureType() [2/3]
void App::MeasureManager::addMeasureType (MeasureType * measureType) static
Definition at line 119 of file MeasureManager.cpp.
addMeasureType() [3/3]
void App::MeasureManager::addMeasureType (std::string id, std::string label, std::string measureObj, MeasureValidateMethod validatorCb, MeasurePrioritizeMethod prioritizeCb) static
Definition at line 124 of file MeasureManager.cpp.
getMeasureElementType()
MeasureElementType App::MeasureManager::getMeasureElementType (const App::MeasureSelectionItem & selectionItem) static
Definition at line 108 of file MeasureManager.cpp.
References SplineSurface::id, and NavigationIndicatorGui::label.
Referenced by Measure::MeasureRadius::isPrioritizedSelection(), Measure::MeasureDistance::isValidSelection(), Measure::MeasureLength::isValidSelection(), Measure::MeasureRadius::isValidSelection(), Measure::MeasureArea::isValidSelection(), Measure::MeasurePosition::isValidSelection(), and Measure::MeasureAngle::isValidSelection().
getMeasureHandler() [1/2]
MeasureHandler App::MeasureManager::getMeasureHandler (const App::MeasureSelectionItem & selectionItem) static
Definition at line 90 of file MeasureManager.cpp.
getMeasureHandler() [2/2]
MeasureHandler App::MeasureManager::getMeasureHandler (const char * module) static
Definition at line 78 of file MeasureManager.cpp.
Referenced by PartDesign::Measure::initialize(), and Sketcher::Measure::initialize().
getMeasureTypes()
const std::vector< MeasureType * > App::MeasureManager::getMeasureTypes () static
Definition at line 148 of file MeasureManager.cpp.
Referenced by getSelectionPy(), and Gui::TaskMeasure::TaskMeasure().
getSelectionPy()
Py::Tuple App::MeasureManager::getSelectionPy (const App::MeasureSelection & selection) static
Definition at line 154 of file MeasureManager.cpp.
References getMeasureTypes(), and Path.Dressup.Utils::selection().
Referenced by Measure::MeasureBase::parseSelection().
getValidMeasureTypes()
std::vector< MeasureType * > App::MeasureManager::getValidMeasureTypes (App::MeasureSelection selection, std::string mode) static
Definition at line 175 of file MeasureManager.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, femtools.tokrules::False, and femsolver.elmer.sifio::isValid().
Referenced by Gui::TaskMeasure::update().
hasMeasureHandler()
bool App::MeasureManager::hasMeasureHandler (const char * module) static
Definition at line 68 of file MeasureManager.cpp.
Referenced by Gui::TaskMeasure::update().
The documentation for this class was generated from the following files:
MeasureManager.h
MeasureManager.cpp