FreeCAD: TaskAttacher.cpp File Reference
TaskAttacher.cpp File Reference
#include "PreCompiled.h"
#include <sstream>
#include <QMessageBox>
#include <QRegularExpression>
#include <QRegularExpressionMatch>
#include <Standard_Failure.hxx>
#include <App/Application.h>
#include <App/Document.h>
#include <App/ElementNamingUtils.h>
#include <App/ObjectIdentifier.h>
#include <App/Datums.h>
#include <App/Part.h>
#include <Gui/Application.h>
#include <Gui/BitmapFactory.h>
#include <Gui/CommandT.h>
#include <Gui/Document.h>
#include <Gui/DocumentObserver.h>
#include <Gui/Selection.h>
#include <Gui/ViewProvider.h>
#include <Base/Tools.h>
#include <Mod/Part/App/AttachExtension.h>
#include <Mod/Part/App/DatumFeature.h>
#include <Mod/Part/Gui/AttacherTexts.h>
#include <Mod/Part/Gui/TaskAttacher.h>
#include "ui_TaskAttacher.h"
#include "moc_TaskAttacher.cpp"
Functions
const QString makeRefString (const App::DocumentObject *obj, const std::string &sub)
const QString makeHintText (std::set< eRefType > hint)
Function Documentation
makeHintText()
const QString makeHintText (std::set< eRefType > hint)
Definition at line 264 of file TaskAttacher.cpp.
References AttacherGui::getShapeTypeText(), result, and InitGui::t.
makeRefString()
const QString makeRefString (const App::DocumentObject * obj, const std::string & sub)
Definition at line 65 of file TaskAttacher.cpp.
References App::DocumentObject::getNameInDocument(), Base::BaseClass::isDerivedFrom(), App::ElementNamePair::oldName, and App::GeoFeature::resolveElement().