FreeCAD: Gui::Dialog::DlgSettingsViewColor Class Reference
Gui::Dialog::DlgSettingsViewColor Class Reference
#include <DlgSettingsViewColor.h>
Public Member Functions
DlgSettingsViewColor (QWidget *parent=nullptr)
~DlgSettingsViewColor () override
void saveSettings () override
void loadSettings () override
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Protected Slots
void onSwitchGradientColorsPressed ()
void onRadioButtonSimpleToggled (bool val)
void onRadioButtonGradientToggled (bool val)
void onRadioButtonRadialGradientToggled (bool val)
void onCheckMidColorToggled (bool val)
Protected Member Functions
void changeEvent (QEvent *e) override
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void resetSettingsToDefaults ()
Detailed Description
The DlgSettingsViewColor class implements a preference page to change color settings for the Inventor viewer like background and selection.
Author
Werner Mayer
Definition at line 79 of file DlgSettingsViewColor.h.
Constructor & Destructor Documentation
DlgSettingsViewColor()
DlgSettingsViewColor::DlgSettingsViewColor (QWidget * parent = nullptr) explicit
Constructs a DlgSettingsViewColor which is a child of 'parent', with the name 'name' and widget flags set to 'f'
Definition at line 40 of file DlgSettingsViewColor.cpp.
References draftgeoutils.intersections::connect(), onCheckMidColorToggled(), onRadioButtonGradientToggled(), onRadioButtonRadialGradientToggled(), onRadioButtonSimpleToggled(), and onSwitchGradientColorsPressed().
~DlgSettingsViewColor()
DlgSettingsViewColor::~DlgSettingsViewColor () override default
Destroys the object and frees any allocated resources
Member Function Documentation
changeEvent()
void DlgSettingsViewColor::changeEvent (QEvent * e) override protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
Definition at line 113 of file DlgSettingsViewColor.cpp.
References SCL.SimpleDataTypes::e.
loadSettings()
void DlgSettingsViewColor::loadSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 84 of file DlgSettingsViewColor.cpp.
References onRadioButtonGradientToggled(), onRadioButtonRadialGradientToggled(), and onRadioButtonSimpleToggled().
onCheckMidColorToggled
void DlgSettingsViewColor::onCheckMidColorToggled (bool val) protected slot
Definition at line 130 of file DlgSettingsViewColor.cpp.
References toolbit-attributes::val.
Referenced by DlgSettingsViewColor().
onRadioButtonGradientToggled
void DlgSettingsViewColor::onRadioButtonGradientToggled (bool val) protected slot
Definition at line 141 of file DlgSettingsViewColor.cpp.
References toolbit-attributes::val.
Referenced by DlgSettingsViewColor(), and loadSettings().
onRadioButtonRadialGradientToggled
void DlgSettingsViewColor::onRadioButtonRadialGradientToggled (bool val) protected slot
Definition at line 149 of file DlgSettingsViewColor.cpp.
References toolbit-attributes::val.
Referenced by DlgSettingsViewColor(), and loadSettings().
onRadioButtonSimpleToggled
void DlgSettingsViewColor::onRadioButtonSimpleToggled (bool val) protected slot
Definition at line 136 of file DlgSettingsViewColor.cpp.
References toolbit-attributes::val.
Referenced by DlgSettingsViewColor(), and loadSettings().
onSwitchGradientColorsPressed
void DlgSettingsViewColor::onSwitchGradientColorsPressed () protected slot
Definition at line 123 of file DlgSettingsViewColor.cpp.
Referenced by DlgSettingsViewColor().
saveSettings()
void DlgSettingsViewColor::saveSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 68 of file DlgSettingsViewColor.cpp.
The documentation for this class was generated from the following files:
DlgSettingsViewColor.h
DlgSettingsViewColor.cpp