FreeCAD: Gui::ExpressionLineEdit Class Reference
Gui::ExpressionLineEdit Class Reference
#include <ExpressionCompleter.h>
Public Slots
void slotTextChanged (const QString &text)
void slotCompleteText (const QString &completionPrefix, bool isActivated)
void slotCompleteTextHighlighted (const QString &completionPrefix)
void slotCompleteTextSelected (const QString &completionPrefix)
Signals
void textChanged2 (QString text, int pos)
Public Member Functions
ExpressionLineEdit (QWidget *parent=nullptr, bool noProperty=false, char checkPrefix=0, bool checkInList=true)
void setDocumentObject (const App::DocumentObject *currentDocObj, bool checkInList=true)
void setPrefix (char prefix)
bool completerActive () const
void hideCompleter ()
void setNoProperty (bool enabled=true)
void setExactMatch (bool enabled=true)
Protected Member Functions
void keyPressEvent (QKeyEvent *event) override
void contextMenuEvent (QContextMenuEvent *event) override
Detailed Description
Definition at line 81 of file ExpressionCompleter.h.
Constructor & Destructor Documentation
ExpressionLineEdit()
ExpressionLineEdit::ExpressionLineEdit (QWidget * parent = nullptr, bool noProperty = false, char checkPrefix = 0, bool checkInList = true)
Definition at line 893 of file ExpressionCompleter.cpp.
References draftgeoutils.intersections::connect(), and slotTextChanged().
Member Function Documentation
completerActive()
bool ExpressionLineEdit::completerActive () const
Definition at line 959 of file ExpressionCompleter.cpp.
Referenced by SpreadsheetGui::LineEdit::event().
contextMenuEvent()
void ExpressionLineEdit::contextMenuEvent (QContextMenuEvent * event) override protected
Definition at line 1025 of file ExpressionCompleter.cpp.
References draftgeoutils.intersections::connect(), NavigationIndicatorGui::menu, and setExactMatch().
hideCompleter()
void ExpressionLineEdit::hideCompleter ()
Definition at line 964 of file ExpressionCompleter.cpp.
keyPressEvent()
void ExpressionLineEdit::keyPressEvent (QKeyEvent * event) override protected
Definition at line 1019 of file ExpressionCompleter.cpp.
References SCL.SimpleDataTypes::e.
setDocumentObject()
void ExpressionLineEdit::setDocumentObject (const App::DocumentObject * currentDocObj, bool checkInList = true)
Definition at line 913 of file ExpressionCompleter.cpp.
References draftgeoutils.intersections::connect(), Gui::ExpressionCompleter::setDocumentObject(), slotCompleteTextHighlighted(), slotCompleteTextSelected(), Gui::ExpressionCompleter::slotUpdate(), and textChanged2().
Referenced by Gui::InputField::bind().
setExactMatch()
void ExpressionLineEdit::setExactMatch (bool enabled = true)
Definition at line 951 of file ExpressionCompleter.cpp.
Referenced by contextMenuEvent().
setNoProperty()
void ExpressionLineEdit::setNoProperty (bool enabled = true)
Definition at line 943 of file ExpressionCompleter.cpp.
References Gui::ExpressionCompleter::setNoProperty().
setPrefix()
void ExpressionLineEdit::setPrefix (char prefix)
Definition at line 908 of file ExpressionCompleter.cpp.
slotCompleteText
void ExpressionLineEdit::slotCompleteText (const QString & completionPrefix, bool isActivated) slot
Definition at line 981 of file ExpressionCompleter.cpp.
References Gui::ExpressionCompleter::getPrefixRange(), slotTextChanged(), and Gui::ExpressionCompleter::updatePrefixEnd().
Referenced by slotCompleteTextHighlighted(), and slotCompleteTextSelected().
slotCompleteTextHighlighted
void ExpressionLineEdit::slotCompleteTextHighlighted (const QString & completionPrefix) slot
Definition at line 1008 of file ExpressionCompleter.cpp.
References slotCompleteText().
Referenced by setDocumentObject().
slotCompleteTextSelected
void ExpressionLineEdit::slotCompleteTextSelected (const QString & completionPrefix) slot
Definition at line 1013 of file ExpressionCompleter.cpp.
References slotCompleteText().
Referenced by setDocumentObject().
slotTextChanged
void ExpressionLineEdit::slotTextChanged (const QString & text) slot
Definition at line 971 of file ExpressionCompleter.cpp.
References textChanged2().
Referenced by ExpressionLineEdit(), and slotCompleteText().
textChanged2
void Gui::ExpressionLineEdit::textChanged2 (QString text, int pos) signal
Referenced by setDocumentObject(), and slotTextChanged().
The documentation for this class was generated from the following files:
ExpressionCompleter.h
ExpressionCompleter.cpp