FreeCAD: StartGui::StartView Class Reference
StartGui::StartView Class Reference
#include <StartView.h>
Public Types
enum PostStartBehavior { PostStartBehavior::switchWorkbench, PostStartBehavior::doNotSwitchWorkbench }
Public Types inherited from Gui::MDIView
enum ViewMode { Child, TopLevel, FullScreen }
MDI view mode enum.
Public Member Functions
StartView (QWidget *parent)
const char * getName () const override
returns the name of the view (important for messages)
void newEmptyFile () const
void newPartDesignFile () const
void openExistingFile () const
void newAssemblyFile () const
void newDraftFile () const
void newArchFile () const
bool onHasMsg (const char *pMsg) const override
Message handler test.
Public Member Functions inherited from Gui::MDIView
MDIView (Gui::Document *pcDocument, QWidget *parent, Qt::WindowFlags wflags=Qt::WindowFlags())
~MDIView () override
void onRelabel (Gui::Document *pDoc) override
get called when the document is updated
virtual void viewAll ()
QString buildWindowTitle () const
build window title
bool onMsg (const char *pMsg, const char **ppReturn) override
Message handler.
bool canClose () override
overwrite when checking on close state
void deleteSelf () override
delete itself
PyObject * getPyObject () override
virtual void print ()
virtual void printPdf ()
virtual void printPreview ()
void savePrinterSettings (QPrinter *printer)
void restorePrinterSettings (QPrinter *printer)
virtual QStringList undoActions () const
virtual QStringList redoActions () const
QSize minimumSizeHint () const override
virtual void setCurrentViewMode (ViewMode mode)
ViewMode currentViewMode () const
template<typename _T >
_T getActiveObject (const char *name, App::DocumentObject **parent=nullptr, std::string *subname=nullptr) const
access getter for the active object list
void setActiveObject (App::DocumentObject *o, const char *n, const char *subname=nullptr)
bool hasActiveObject (const char *n) const
bool isActiveObject (App::DocumentObject *o, const char *n, const char *subname=nullptr) const
virtual bool containsViewProvider (const ViewProvider *) const
containsViewProvider Checks if the given view provider is part of this view. The default implementation returns false.
Public Member Functions inherited from Gui::BaseView
BaseView (Gui::Document *pcDocument=nullptr)
~BaseView () override
void setDocument (Gui::Document *pcDocument)
sets the view to another document (called by Application)
void onClose ()
is sent from the document in order to close the document
Gui::Document * getGuiDocument () const
returns the document the view is attached to
App::Document * getAppDocument () const
returns the document the view is attached to
bool isPassive () const
indicates if the view is in passive mode
virtual void onUpdate ()
get called when the document is updated
virtual void onRename (Gui::Document *)
get called when the document is renamed (change of its internal name)
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Member Functions
void changeEvent (QEvent *e) override
void configureNewFileButtons (QLayout *layout) const
void configureRecentFilesListWidget (QListView *recentFilesListWidget, QLabel *recentFilesLabel)
void configureExamplesListWidget (QListView *examplesListWidget)
void postStart (PostStartBehavior behavior) const
void fileCardSelected (const QModelIndex &index)
void showOnStartupChanged (bool checked)
void openFirstStartClicked ()
void firstStartWidgetDismissed ()
QString fileCardStyle () const
Protected Member Functions inherited from Gui::MDIView
void closeEvent (QCloseEvent *e) override
void changeEvent (QEvent *e) override
Static Protected Member Functions
static void configureFileCardWidget (QListView *fileCardWidget)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Additional Inherited Members
Public Slots inherited from Gui::MDIView
virtual void print (QPrinter *printer)
virtual void setOverrideCursor (const QCursor &)
virtual void restoreOverrideCursor ()
Signals inherited from Gui::MDIView
void message (const QString &, int)
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Protected Slots inherited from Gui::MDIView
virtual void windowStateChanged (QWidget *)
Protected Attributes inherited from Gui::MDIView
PyObject * pythonObject
Protected Attributes inherited from Gui::BaseView
Gui::Document * _pcDocument
bool bIsDetached {false}
bool bIsPassive {false}
Detailed Description
Definition at line 52 of file StartView.h.
Member Enumeration Documentation
PostStartBehavior
enum StartGui::StartView::PostStartBehavior strong
Enumerator
switchWorkbench
doNotSwitchWorkbench
Definition at line 76 of file StartView.h.
Constructor & Destructor Documentation
StartView()
StartView::StartView (QWidget * parent)
Definition at line 182 of file StartView.cpp.
Member Function Documentation
changeEvent()
void StartView::changeEvent (QEvent * e) override protected
Definition at line 498 of file StartView.cpp.
References Gui::Application::activeDocument(), Gui::MDIView::changeEvent(), toolbit-attributes::doc, Gui::View3DInventor::getViewer(), Gui::Application::Instance, and OfflineRenderingUtils::viewer().
configureExamplesListWidget()
void StartView::configureExamplesListWidget (QListView * examplesListWidget) protected
Definition at line 361 of file StartView.cpp.
References configureFileCardWidget(), and Start::ExamplesModel::loadExamples().
configureFileCardWidget()
void StartView::configureFileCardWidget (QListView * fileCardWidget) static protected
Definition at line 329 of file StartView.cpp.
Referenced by configureExamplesListWidget(), and configureRecentFilesListWidget().
configureNewFileButtons()
void StartView::configureNewFileButtons (QLayout * layout) const protected
Definition at line 286 of file StartView.cpp.
References draftgeoutils.intersections::connect(), newArchFile(), newAssemblyFile(), newDraftFile(), newEmptyFile(), newPartDesignFile(), and openExistingFile().
configureRecentFilesListWidget()
void StartView::configureRecentFilesListWidget (QListView * recentFilesListWidget, QLabel * recentFilesLabel) protected
Definition at line 340 of file StartView.cpp.
References configureFileCardWidget(), App::GetApplication(), ParameterGrp::GetInt(), App::Application::GetParameterGroupByPath(), and Start::RecentFilesModel::loadRecentFiles().
fileCardSelected()
void StartView::fileCardSelected (const QModelIndex & index) protected
Definition at line 456 of file StartView.cpp.
References Base::Console(), SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), Start::path, and Gui::ModuleIO::verifyAndOpenFile().
fileCardStyle()
QString StartGui::StartView::fileCardStyle () const protected
firstStartWidgetDismissed()
void StartView::firstStartWidgetDismissed () protected
Definition at line 490 of file StartView.cpp.
References App::GetApplication(), App::Application::GetParameterGroupByPath(), and ParameterGrp::SetBool().
getName()
const char* StartGui::StartView::getName () const inline override virtual
returns the name of the view (important for messages)
Reimplemented from Gui::BaseView.
Definition at line 61 of file StartView.h.
newArchFile()
void StartView::newArchFile () const
Definition at line 412 of file StartView.cpp.
References Gui::Application::activateWorkbench(), Gui::Application::commandManager(), doNotSwitchWorkbench, Gui::Application::Instance, postStart(), and Gui::CommandManager::runCommandByName().
Referenced by configureNewFileButtons().
newAssemblyFile()
void StartView::newAssemblyFile () const
Definition at line 395 of file StartView.cpp.
References Gui::Application::activateWorkbench(), Gui::Application::commandManager(), doNotSwitchWorkbench, Gui::Application::Instance, postStart(), and Gui::CommandManager::runCommandByName().
Referenced by configureNewFileButtons().
newDraftFile()
void StartView::newDraftFile () const
Definition at line 404 of file StartView.cpp.
References Gui::Application::activateWorkbench(), Gui::Application::commandManager(), doNotSwitchWorkbench, Gui::Application::Instance, postStart(), and Gui::CommandManager::runCommandByName().
Referenced by configureNewFileButtons().
newEmptyFile()
void StartView::newEmptyFile () const
Definition at line 369 of file StartView.cpp.
References Gui::Application::commandManager(), Gui::Application::Instance, postStart(), Gui::CommandManager::runCommandByName(), and switchWorkbench.
Referenced by configureNewFileButtons().
newPartDesignFile()
void StartView::newPartDesignFile () const
Definition at line 375 of file StartView.cpp.
References Gui::Application::activateWorkbench(), Gui::Application::commandManager(), doNotSwitchWorkbench, Gui::Application::Instance, postStart(), and Gui::CommandManager::runCommandByName().
Referenced by configureNewFileButtons().
onHasMsg()
bool StartView::onHasMsg (const char * pMsg) const override virtual
Message handler test.
Reimplemented from Gui::MDIView.
Definition at line 424 of file StartView.cpp.
openExistingFile()
void StartView::openExistingFile () const
Definition at line 383 of file StartView.cpp.
References Gui::Application::activeDocument(), Gui::Application::checkForRecomputes(), Gui::Application::commandManager(), Gui::Application::Instance, postStart(), Gui::CommandManager::runCommandByName(), and switchWorkbench.
Referenced by configureNewFileButtons().
openFirstStartClicked()
void StartView::openFirstStartClicked () protected
Definition at line 485 of file StartView.cpp.
postStart()
void StartView::postStart (PostStartBehavior behavior) const protected
Definition at line 433 of file StartView.cpp.
References Gui::Application::activateWorkbench(), App::GetApplication(), ParameterGrp::GetASCII(), App::Application::GetParameterGroupByPath(), Gui::Application::Instance, and switchWorkbench.
Referenced by newArchFile(), newAssemblyFile(), newDraftFile(), newEmptyFile(), newPartDesignFile(), and openExistingFile().
showOnStartupChanged()
void StartView::showOnStartupChanged (bool checked) protected
Definition at line 474 of file StartView.cpp.
References App::GetApplication(), App::Application::GetParameterGroupByPath(), and ParameterGrp::SetBool().
The documentation for this class was generated from the following files:
StartView.h
StartView.cpp