FreeCAD: Gui::Dialog::CommandModel Class Reference
Gui::Dialog::CommandModel Class Reference
#include <DlgCustomizeSpaceball.h>
Public Member Functions
CommandModel (QObject *parent=nullptr)
~CommandModel () override
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const override
QModelIndex parent (const QModelIndex &index) const override
int rowCount (const QModelIndex &parent) const override
int columnCount (const QModelIndex &parent) const override
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const override
Qt::ItemFlags flags (const QModelIndex &index) const override
void goAddMacro (const QByteArray &macroName)
void goRemoveMacro (const QByteArray &macroName)
Detailed Description
Definition at line 104 of file DlgCustomizeSpaceball.h.
Constructor & Destructor Documentation
CommandModel()
CommandModel::CommandModel (QObject * parent = nullptr) explicit
Definition at line 354 of file DlgCustomizeSpaceball.cpp.
~CommandModel()
CommandModel::~CommandModel () override
Definition at line 362 of file DlgCustomizeSpaceball.cpp.
Member Function Documentation
columnCount()
int CommandModel::columnCount (const QModelIndex & parent) const override
Definition at line 410 of file DlgCustomizeSpaceball.cpp.
References parent().
data()
QVariant CommandModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const override
Definition at line 416 of file DlgCustomizeSpaceball.cpp.
References Gui::Dialog::CommandNode::aCommand, Gui::BitmapFactory(), Gui::Dialog::CommandNode::children, Gui::CommandBase::className(), Gui::Dialog::CommandNode::CommandType, Gui::Command::getGroupName(), Gui::CommandBase::getMenuText(), Gui::Command::getName(), Gui::CommandBase::getPixmap(), Gui::CommandBase::getToolTipText(), Gui::Dialog::CommandNode::GroupType, index(), and Gui::Dialog::CommandNode::nodeType.
Referenced by Gui::Dialog::PrintModel::data().
flags()
Qt::ItemFlags CommandModel::flags (const QModelIndex & index) const override
Definition at line 474 of file DlgCustomizeSpaceball.cpp.
References Gui::Dialog::CommandNode::CommandType, index(), and Gui::Dialog::CommandNode::nodeType.
goAddMacro()
void CommandModel::goAddMacro (const QByteArray & macroName)
Definition at line 493 of file DlgCustomizeSpaceball.cpp.
References Gui::Dialog::CommandNode::children, Gui::Application::commandManager(), Gui::Dialog::CommandNode::CommandType, Gui::CommandManager::getCommandByName(), Gui::Dialog::CommandNode::GroupType, index(), and Gui::Application::Instance.
Referenced by Gui::Dialog::DlgCustomizeSpaceball::onAddMacroAction().
goRemoveMacro()
void CommandModel::goRemoveMacro (const QByteArray & macroName)
Definition at line 534 of file DlgCustomizeSpaceball.cpp.
References Gui::Dialog::CommandNode::children, index(), and parent().
Referenced by Gui::Dialog::DlgCustomizeSpaceball::onRemoveMacroAction().
headerData()
QVariant CommandModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const override
Definition at line 467 of file DlgCustomizeSpaceball.cpp.
References Sketcher::Horizontal.
index()
QModelIndex CommandModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const override
Definition at line 368 of file DlgCustomizeSpaceball.cpp.
References Gui::Dialog::CommandNode::children, App::ExpressionParser::column, and parent().
Referenced by src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::addSegment(), src.Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::begin(), data(), Gui::Dialog::PrintModel::data(), flags(), goAddMacro(), goRemoveMacro(), src.Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::interval(), src.Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::length(), parent(), automotive_design.index_expression::wr1(), and automotive_design.index_expression::wr2().
parent()
QModelIndex CommandModel::parent (const QModelIndex & index) const override
Definition at line 381 of file DlgCustomizeSpaceball.cpp.
References Gui::Dialog::CommandNode::children, index(), and Gui::Dialog::CommandNode::parent.
Referenced by columnCount(), goRemoveMacro(), index(), and rowCount().
rowCount()
int CommandModel::rowCount (const QModelIndex & parent) const override
Definition at line 399 of file DlgCustomizeSpaceball.cpp.
References Gui::Dialog::CommandNode::children, and parent().
Referenced by src.Mod.AddonManager.package_list.PackageListItemModel::append_item(), src.Mod.AddonManager.AddonManagerOptions.CustomRepoDataModel::appendData(), and src.Mod.AddonManager.package_list.PackageListItemModel::clear().
The documentation for this class was generated from the following files:
DlgCustomizeSpaceball.h
DlgCustomizeSpaceball.cpp