FreeCAD: Path.Tool.Gui.BitLibrary.ModelFactory Class Reference
Path.Tool.Gui.BitLibrary.ModelFactory Class Reference
Static Public Member Functions
QStandardItemModel find_libraries (model)
def new_tool (QStandardItemModel datamodel, str path)
QStandardItemModel library_open (QStandardItemModel model, str lib="")
Detailed Description
Helper class to generate qtdata models for toolbit libraries
Definition at line 239 of file BitLibrary.py.
Member Function Documentation
find_libraries()
QStandardItemModel Path.Tool.Gui.BitLibrary.ModelFactory.find_libraries (model) static
Finds all the fctl files in a location.
Returns a QStandardItemModel.
Definition at line 243 of file BitLibrary.py.
References Path.Log.debug(), Path.Log.error(), Path.Preferences.lastPathToolLibrary(), AssemblyImport.open(), Path.Preferences.setLastFileToolLibrary(), and Path.Log.track().
library_open()
QStandardItemModel Path.Tool.Gui.BitLibrary.ModelFactory.library_open (QStandardItemModel model, str lib = "") static
Opens the tools in a library.
Returns a QStandardItemModel.
Definition at line 369 of file BitLibrary.py.
References Path.Log.debug(), Path.Preferences.lastFileToolLibrary(), and Path.Log.track().
new_tool()
def Path.Tool.Gui.BitLibrary.ModelFactory.new_tool (QStandardItemModel datamodel, str path) static
Adds a toolbit item to a model.
Definition at line 344 of file BitLibrary.py.
References Path.Log.error(), KDL.max(), and Path.Log.track().
The documentation for this class was generated from the following file:
BitLibrary.py