FreeCAD: Base::UnitsSchemaInternal Class Reference
Base::UnitsSchemaInternal Class Reference
#include <UnitsSchemaInternal.h>
Public Member Functions
std::string schemaTranslate (const Base::Quantity &quant, double &factor, std::string &unitString) override
This method translates the quantity in a string as the user may expect it.
Public Member Functions inherited from Base::UnitsSchema
UnitsSchema ()=default
UnitsSchema (const UnitsSchema &)=default
UnitsSchema (UnitsSchema &&)=default
UnitsSchema & operator= (const UnitsSchema &)=default
UnitsSchema & operator= (UnitsSchema &&)=default
virtual ~UnitsSchema ()=default
virtual void setSchemaUnits ()
virtual void resetSchemaUnits ()
If you use setSchemaUnits() you also have to impment this method to undo your changes!
std::string toLocale (const Base::Quantity &quant, double factor, const std::string &unitString) const
virtual bool isMultiUnitLength () const
virtual bool isMultiUnitAngle () const
virtual std::string getBasicLengthUnit () const
Detailed Description
The standard units schema Here is defined what internal (base) units FreeCAD uses. FreeCAD uses a mm/kg/deg scala. Also it defines how the units get presented.
Definition at line 56 of file UnitsSchemaInternal.h.
Member Function Documentation
schemaTranslate()
std::string UnitsSchemaInternal::schemaTranslate (const Base::Quantity & quant, double & factor, std::string & unitString) override virtual
This method translates the quantity in a string as the user may expect it.
Implements Base::UnitsSchema.
Definition at line 35 of file UnitsSchemaInternal.cpp.
References KDL::abs(), Base::Unit::Angle, Base::Unit::Area, Base::Unit::CurrentDensity, Base::Unit::Density, Base::Unit::DissipationRate, Base::Unit::DynamicViscosity, SCL.SimpleDataTypes::e, Base::Unit::ElectricalCapacitance, Base::Unit::ElectricalConductance, Base::Unit::ElectricalConductivity, Base::Unit::ElectricalInductance, Base::Unit::ElectricalResistance, Base::Unit::ElectricCharge, Base::Unit::ElectricPotential, Base::Unit::ElectromagneticPotential, Base::Unit::Force, Base::Unit::Frequency, Base::Unit::getString(), Base::Quantity::getUnit(), Base::Quantity::getValue(), Base::Unit::HeatFlux, Base::Unit::InverseArea, Base::Unit::InverseLength, Base::Unit::InverseVolume, Base::Unit::KinematicViscosity, Base::Unit::Length, Base::Unit::MagneticFieldStrength, Base::Unit::MagneticFlux, Base::Unit::MagneticFluxDensity, Base::Unit::Magnetization, Base::Unit::Mass, Base::Unit::Power, Base::Unit::Pressure, Base::Unit::SpecificEnergy, Base::Unit::SpecificHeat, Base::Unit::Stiffness, Base::Unit::StiffnessDensity, Base::Unit::Stress, Base::Unit::ThermalConductivity, Base::Unit::ThermalExpansionCoefficient, Base::Unit::ThermalTransferCoefficient, Base::UnitsSchema::toLocale(), unit(), Base::Unit::VacuumPermittivity, Base::Unit::Velocity, Base::Unit::Volume, Base::Unit::VolumeFlowRate, Base::Unit::VolumetricThermalExpansionCoefficient, and Base::Unit::Work.
The documentation for this class was generated from the following files:
UnitsSchemaInternal.h
UnitsSchemaInternal.cpp