FreeCAD: MeshPart::CurveProjectorSimple Class Reference
MeshPart::CurveProjectorSimple Class Reference
#include <CurveProjector.h>
Public Member Functions
CurveProjectorSimple (const TopoDS_Shape &aShape, const MeshKernel &pMesh)
~CurveProjectorSimple () override=default
void GetSampledCurves (const TopoDS_Edge &aEdge, std::vector< Base::Vector3f > &rclPoints, unsigned long ulNbOfPoints=30)
helper to discredicice a Edge...
void projectCurve (const TopoDS_Edge &aEdge, const std::vector< Base::Vector3f > &rclPoints, std::vector< FaceSplitEdge > &vSplitEdges)
bool findStartPoint (const MeshKernel &MeshK, const Base::Vector3f &Pnt, Base::Vector3f &Rslt, MeshCore::FacetIndex &FaceIndex)
Public Member Functions inherited from MeshPart::CurveProjector
CurveProjector (const TopoDS_Shape &aShape, const MeshKernel &pMesh)
virtual ~CurveProjector ()=default
result_type & result ()
void writeIntersectionPointsToFile (const char *name="export_pts.asc")
Protected Member Functions
void Do () override
Additional Inherited Members
Public Types inherited from MeshPart::CurveProjector
using result_type = std::map< TopoDS_Edge, std::vector< FaceSplitEdge >, TopoDSLess< TopoDS_Edge > >
Protected Attributes inherited from MeshPart::CurveProjector
const TopoDS_Shape & _Shape
const MeshKernel & _Mesh
result_type mvEdgeSplitPoints
Detailed Description
Project by projecting a sampled curve to the mesh
Definition at line 115 of file CurveProjector.h.
Constructor & Destructor Documentation
CurveProjectorSimple()
CurveProjectorSimple::CurveProjectorSimple (const TopoDS_Shape & aShape, const MeshKernel & pMesh)
Definition at line 266 of file CurveProjector.cpp.
References Do().
~CurveProjectorSimple()
MeshPart::CurveProjectorSimple::~CurveProjectorSimple () override default
Member Function Documentation
Do()
void CurveProjectorSimple::Do () override protected virtual
Implements MeshPart::CurveProjector.
Definition at line 273 of file CurveProjector.cpp.
References MeshPart::CurveProjector::_Shape, MeshPart::CurveProjector::mvEdgeSplitPoints, and projectCurve().
Referenced by CurveProjectorSimple().
findStartPoint()
bool CurveProjectorSimple::findStartPoint (const MeshKernel & MeshK, const Base::Vector3f & Pnt, Base::Vector3f & Rslt, MeshCore::FacetIndex & FaceIndex)
Definition at line 360 of file CurveProjector.cpp.
References geoff_geometry::Dist(), FLOAT_MAX, MeshCore::MeshGeomFacet::Foraminate(), MeshCore::MeshGeomFacet::GetNormal(), MeshCore::MeshFacetIterator::Init(), FreeCADInit::Length, MeshCore::MeshFacetIterator::More(), MeshCore::MeshFacetIterator::Next(), and MeshCore::MeshFacetIterator::Position().
GetSampledCurves()
void CurveProjectorSimple::GetSampledCurves (const TopoDS_Edge & aEdge, std::vector< Base::Vector3f > & rclPoints, unsigned long ulNbOfPoints = 30)
helper to discredicice a Edge...
Definition at line 285 of file CurveProjector.cpp.
References Handle(), and SplineSurface::i.
projectCurve()
void CurveProjectorSimple::projectCurve (const TopoDS_Edge & aEdge, const std::vector< Base::Vector3f > & rclPoints, std::vector< FaceSplitEdge > & vSplitEdges)
Definition at line 305 of file CurveProjector.cpp.
References MeshPart::CurveProjector::_Mesh, Base::Console(), MeshCore::MeshGeomFacet::GetNormal(), Handle(), SplineSurface::i, MeshCore::MeshFacetIterator::Init(), MeshCore::MeshGeomFacet::IntersectWithLine(), Base::ConsoleSingleton::Log(), MeshCore::MeshFacetIterator::More(), MeshCore::MeshFacetIterator::Next(), Base::SequencerLauncher::next(), ClipperLib::PointCount(), MeshCore::MeshFacetIterator::Position(), Path.Post.scripts.refactored_centroid_post::str, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by Do().
The documentation for this class was generated from the following files:
CurveProjector.h
CurveProjector.cpp