FreeCAD: MeshGui::SoFCMeshObjectShape Class Reference
MeshGui::SoFCMeshObjectShape Class Reference
The SoFCMeshObjectShape class is designed to render huge meshes.
#include <SoFCMeshObject.h>
Public Member Functions
SoFCMeshObjectShape ()
Static Public Member Functions
static void initClass ()
Public Attributes
unsigned int renderTriangleLimit
Protected Member Functions
void doAction (SoAction *action) override
void GLRender (SoGLRenderAction *action) override
void computeBBox (SoAction *action, SbBox3f &box, SbVec3f &center) override
void getPrimitiveCount (SoGetPrimitiveCountAction *action) override
void rayPick (SoRayPickAction *action) override
void generatePrimitives (SoAction *action) override
SoDetail * createTriangleDetail (SoRayPickAction *action, const SoPrimitiveVertex *v1, const SoPrimitiveVertex *v2, const SoPrimitiveVertex *v3, SoPickedPoint *pp) override
~SoFCMeshObjectShape () override
Detailed Description
The SoFCMeshObjectShape class is designed to render huge meshes.
class SoFCMeshObjectShape The SoFCMeshObjectShape is an Inventor shape node that is designed to render huge meshes. If the mesh exceeds a certain number of triangles and the user does some intersections (e.g. moving, rotating, zooming, spinning, etc.) with the mesh then the GLRender() method renders only the gravity points of a subset of the triangles. If there is no user interaction with the mesh then all triangles are rendered. The limit of maximum allowed triangles can be specified in renderTriangleLimit, the default value is set to 100.000.
The GLRender() method checks the status of the SoFCInteractiveElement to decide to be in interactive mode or not. To take advantage of this facility the client programmer must set the status of the SoFCInteractiveElement to true if there is a user interaction and set the status to false if not. This can be done e.g. in the actualRedraw() method of the viewer.
Author
Werner Mayer
Definition at line 177 of file SoFCMeshObject.h.
Constructor & Destructor Documentation
SoFCMeshObjectShape()
SoFCMeshObjectShape::SoFCMeshObjectShape ()
Definition at line 609 of file SoFCMeshObject.cpp.
~SoFCMeshObjectShape()
SoFCMeshObjectShape::~SoFCMeshObjectShape () override protected default
Member Function Documentation
computeBBox()
void SoFCMeshObjectShape::computeBBox (SoAction * action, SbBox3f & box, SbVec3f & center) override protected
Sets the bounding box of the mesh to box and its center to center.
Definition at line 1187 of file SoFCMeshObject.cpp.
References Path.Post.scripts.dynapath_4060_post::action, MengerSponge::box, exportCSG::center(), MeshGui::SoFCMeshObjectElement::get(), Base::BoundBox3< Precision >::GetCenter(), Base::BoundBox3< Precision >::MaxX, Base::BoundBox3< Precision >::MaxY, Base::BoundBox3< Precision >::MaxZ, Mesh2Shape::mesh, Base::BoundBox3< Precision >::MinX, Base::BoundBox3< Precision >::MinY, and Base::BoundBox3< Precision >::MinZ.
createTriangleDetail()
SoDetail * SoFCMeshObjectShape::createTriangleDetail (SoRayPickAction * action, const SoPrimitiveVertex * v1, const SoPrimitiveVertex * v2, const SoPrimitiveVertex * v3, SoPickedPoint * pp) override protected
If the number of triangles exceeds renderTriangleLimit 0 is returned. This means that the client programmer needs to implement itself to get the index of the picked triangle. If the number of triangles doesn't exceed renderTriangleLimit SoShape::createTriangleDetail() gets called. Against the default OpenInventor implementation which returns 0 as well Coin3d fills in the point and face indices.
Definition at line 1174 of file SoFCMeshObject.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and draftgeoutils.general::v1().
doAction()
void SoFCMeshObjectShape::doAction (SoAction * action) override protected
Definition at line 951 of file SoFCMeshObject.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and Mesh2Shape::mesh.
generatePrimitives()
void SoFCMeshObjectShape::generatePrimitives (SoAction * action) override protected
Sets the point indices, the geometric points and the normal for each triangle. If the number of triangles exceeds renderTriangleLimit then only a triangulation of a rough model is filled in instead. This is due to performance issues.
See also
createTriangleDetail().
Definition at line 1086 of file SoFCMeshObject.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Base::Console(), MeshGui::SoFCMeshObjectElement::get(), Base::ConsoleSingleton::Log(), Mesh2Shape::mesh, sbvec3f(), draftgeoutils.general::v1(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
getPrimitiveCount()
void SoFCMeshObjectShape::getPrimitiveCount (SoGetPrimitiveCountAction * action) override protected
Adds the number of the triangles to the SoGetPrimitiveCountAction.
Definition at line 1207 of file SoFCMeshObject.cpp.
References Path.Post.scripts.dynapath_4060_post::action, MeshGui::SoFCMeshObjectElement::get(), and Mesh2Shape::mesh.
GLRender()
void SoFCMeshObjectShape::GLRender (SoGLRenderAction * action) override protected
Either renders the complete mesh or only a subset of the points.
Definition at line 629 of file SoFCMeshObject.cpp.
References Path.Post.scripts.dynapath_4060_post::action, MeshGui::SoFCMeshObjectElement::get(), Gui::SoFCInteractiveElement::get(), and Mesh2Shape::mesh.
initClass()
void SoFCMeshObjectShape::initClass () static
Definition at line 604 of file SoFCMeshObject.cpp.
Referenced by PyMOD_INIT_FUNC().
rayPick()
void SoFCMeshObjectShape::rayPick (SoRayPickAction * action) override protected
Calculates picked point based on primitives generated by subclasses.
Definition at line 1076 of file SoFCMeshObject.cpp.
References Path.Post.scripts.dynapath_4060_post::action.
Member Data Documentation
renderTriangleLimit
unsigned int MeshGui::SoFCMeshObjectShape::renderTriangleLimit
Definition at line 187 of file SoFCMeshObject.h.
Referenced by MeshGui::ViewProviderMeshFaceSet::attach(), and MeshGui::ViewProviderMeshObject::attach().
The documentation for this class was generated from the following files:
SoFCMeshObject.h
SoFCMeshObject.cpp