FreeCAD: PartGui::DlgBooleanOperation Class Reference
PartGui::DlgBooleanOperation Class Reference
#include <DlgBooleanOperation.h>
Public Member Functions
DlgBooleanOperation (QWidget *parent=nullptr)
~DlgBooleanOperation () override
void accept ()
Protected Member Functions
void changeEvent (QEvent *e) override
Detailed Description
Definition at line 40 of file DlgBooleanOperation.h.
Constructor & Destructor Documentation
DlgBooleanOperation()
DlgBooleanOperation::DlgBooleanOperation (QWidget * parent = nullptr) explicit
Definition at line 86 of file DlgBooleanOperation.cpp.
References draftgeoutils.faces::bind(), draftgeoutils.intersections::connect(), App::GetApplication(), App::Application::signalChangedObject, and App::Application::signalNewObject.
~DlgBooleanOperation()
DlgBooleanOperation::~DlgBooleanOperation () override
Definition at line 108 of file DlgBooleanOperation.cpp.
Member Function Documentation
accept()
void DlgBooleanOperation::accept ()
Definition at line 349 of file DlgBooleanOperation.cpp.
References App::Document::commitTransaction(), Gui::Command::Doc, doCommand, SCL.SimpleDataTypes::e, App::Application::getActiveDocument(), App::GetApplication(), App::Document::getObject(), SplineSurface::i, Base::Tools::joinList(), femtools.tokrules::names, App::Document::openTransaction(), Base::Tools::quoted(), and App::Document::recompute().
Referenced by PartGui::TaskBooleanOperation::clicked().
changeEvent()
void DlgBooleanOperation::changeEvent (QEvent * e) override protected
Definition at line 115 of file DlgBooleanOperation.cpp.
References SCL.SimpleDataTypes::e.
The documentation for this class was generated from the following files:
DlgBooleanOperation.h
DlgBooleanOperation.cpp