FreeCAD: Fem::StdMeshers_AutomaticLengthPy Class Reference
Fem::StdMeshers_AutomaticLengthPy Class Reference
#include <HypothesisPy.h>
Public Member Functions
StdMeshers_AutomaticLengthPy (int hypId, int studyId, SMESH_Gen *gen)
~StdMeshers_AutomaticLengthPy () override
Py::Object setFineness (const Py::Tuple &args)
Py::Object getFineness (const Py::Tuple &args)
Py::Object getLength (const Py::Tuple &args)
Public Member Functions inherited from Fem::SMESH_HypothesisPy< StdMeshers_AutomaticLengthPy >
SMESH_HypothesisPy (SMESH_Hypothesis *)
~SMESH_HypothesisPy () override
Py::Object getattr (const char *name) override
Py::Object repr () override
Py::Object getLibName (const Py::Tuple &args)
Py::Object setLibName (const Py::Tuple &args)
Py::Object isAuxiliary (const Py::Tuple &args)
Py::Object setParametersByMesh (const Py::Tuple &args)
std::shared_ptr< SMESH_Hypothesis > getHypothesis () const
Static Public Member Functions
static void init_type (PyObject *)
Static Public Member Functions inherited from Fem::SMESH_HypothesisPy< StdMeshers_AutomaticLengthPy >
static void init_type (PyObject *)
Additional Inherited Members
Public Types inherited from Fem::SMESH_HypothesisPy< StdMeshers_AutomaticLengthPy >
using SMESH_HypothesisPyBase = SMESH_HypothesisPy< StdMeshers_AutomaticLengthPy >
Protected Member Functions inherited from Fem::SMESH_HypothesisPy< StdMeshers_AutomaticLengthPy >
type * hypothesis () const
Detailed Description
Definition at line 401 of file HypothesisPy.h.
Constructor & Destructor Documentation
StdMeshers_AutomaticLengthPy()
StdMeshers_AutomaticLengthPy::StdMeshers_AutomaticLengthPy (int hypId, int studyId, SMESH_Gen * gen)
Definition at line 271 of file HypothesisPy.cpp.
~StdMeshers_AutomaticLengthPy()
StdMeshers_AutomaticLengthPy::~StdMeshers_AutomaticLengthPy () override default
Member Function Documentation
getFineness()
Py::Object StdMeshers_AutomaticLengthPy::getFineness (const Py::Tuple & args)
Definition at line 287 of file HypothesisPy.cpp.
References toolbit-attributes::args.
Referenced by init_type().
getLength()
Py::Object StdMeshers_AutomaticLengthPy::getLength (const Py::Tuple & args)
Definition at line 311 of file HypothesisPy.cpp.
References toolbit-attributes::args, test::m, Mesh2Shape::mesh, and toolbit-attributes::s.
Referenced by init_type().
init_type()
void StdMeshers_AutomaticLengthPy::init_type (PyObject * module) static
Definition at line 255 of file HypothesisPy.cpp.
References getFineness(), getLength(), Fem::SMESH_HypothesisPy< StdMeshers_AutomaticLengthPy >::init_type(), src.Mod.PartDesign.fcgear.svggear::module, and setFineness().
Referenced by PyMOD_INIT_FUNC().
setFineness()
Py::Object StdMeshers_AutomaticLengthPy::setFineness (const Py::Tuple & args)
Definition at line 280 of file HypothesisPy.cpp.
References toolbit-attributes::args.
Referenced by init_type().
The documentation for this class was generated from the following files:
HypothesisPy.h
HypothesisPy.cpp