FreeCAD: MatGui::ListModel Class Reference
MatGui::ListModel Class Reference
#include <ListModel.h>
Public Member Functions
ListModel ()
ListModel (std::shared_ptr< Materials::MaterialProperty > property, QList< QVariant > &value, QObject *parent=nullptr)
~ListModel () override=default
int rowCount (const QModelIndex &parent=QModelIndex()) const override
bool newRow (const QModelIndex &index) const
void deleteRow (const QModelIndex &index)
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const override
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole) override
Qt::ItemFlags flags (const QModelIndex &index) const override
bool insertRows (int row, int count, const QModelIndex &parent=QModelIndex()) override
bool removeRows (int row, int count, const QModelIndex &parent=QModelIndex()) override
Detailed Description
Definition at line 58 of file ListModel.h.
Constructor & Destructor Documentation
ListModel() [1/2]
ListModel::ListModel ()
Definition at line 41 of file ListModel.cpp.
ListModel() [2/2]
ListModel::ListModel (std::shared_ptr< Materials::MaterialProperty > property, QList< QVariant > & value, QObject * parent = nullptr)
Definition at line 44 of file ListModel.cpp.
~ListModel()
MatGui::ListModel::~ListModel () override default
Member Function Documentation
data()
QVariant ListModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const override
Definition at line 72 of file ListModel.cpp.
deleteRow()
void ListModel::deleteRow (const QModelIndex & index)
Definition at line 66 of file ListModel.cpp.
References removeRows().
flags()
Qt::ItemFlags ListModel::flags (const QModelIndex & index) const override
Definition at line 101 of file ListModel.cpp.
headerData()
QVariant ListModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const override
Definition at line 83 of file ListModel.cpp.
insertRows()
bool ListModel::insertRows (int row, int count, const QModelIndex & parent = QModelIndex()) override
Definition at line 108 of file ListModel.cpp.
References src.Mod.AddonManager.NetworkManager::count, newRow(), and Init::parent.
Referenced by setData().
newRow()
bool ListModel::newRow (const QModelIndex & index) const
Definition at line 61 of file ListModel.cpp.
Referenced by insertRows(), and setData().
removeRows()
bool ListModel::removeRows (int row, int count, const QModelIndex & parent = QModelIndex()) override
Definition at line 122 of file ListModel.cpp.
References src.Mod.AddonManager.NetworkManager::count, and Init::parent.
Referenced by deleteRow().
rowCount()
int ListModel::rowCount (const QModelIndex & parent = QModelIndex()) const override
Definition at line 52 of file ListModel.cpp.
References Init::parent.
setData()
bool ListModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) override
Definition at line 88 of file ListModel.cpp.
References insertRows(), and newRow().
Referenced by MatGui::ListDelegate::setValue().
The documentation for this class was generated from the following files:
ListModel.h
ListModel.cpp