FreeCAD: ModelRefine::FaceEqualitySplitter Class Reference
ModelRefine::FaceEqualitySplitter Class Reference
#include <modelRefine.h>
Public Member Functions
FaceEqualitySplitter ()=default
void split (const FaceVectorType &faces, FaceTypedBase *object)
std::size_t getGroupCount () const
const FaceVectorType & getGroup (const std::size_t &index) const
Detailed Description
Definition at line 167 of file modelRefine.h.
Constructor & Destructor Documentation
FaceEqualitySplitter()
ModelRefine::FaceEqualitySplitter::FaceEqualitySplitter () default
Member Function Documentation
getGroup()
const FaceVectorType& ModelRefine::FaceEqualitySplitter::getGroup (const std::size_t & index) const inline
Definition at line 173 of file modelRefine.h.
Referenced by ModelRefine::FaceUniter::process().
getGroupCount()
std::size_t ModelRefine::FaceEqualitySplitter::getGroupCount () const inline
Definition at line 172 of file modelRefine.h.
Referenced by ModelRefine::FaceUniter::process().
split()
void FaceEqualitySplitter::split (const FaceVectorType & faces, FaceTypedBase * object)
Definition at line 256 of file modelRefine.cpp.
References ModelRefine::FaceTypedBase::isEqual().
Referenced by ModelRefine::FaceUniter::process().
The documentation for this class was generated from the following files:
modelRefine.h
modelRefine.cpp