FreeCAD: Gui::PythonEditorView Class Reference
Gui::PythonEditorView Class Reference
#include <EditorView.h>
Public Slots
void executeScript ()
void startDebug ()
void toggleBreakpoint ()
void showDebugMarker (int line)
void hideDebugMarker ()
Public Slots inherited from Gui::MDIView
virtual void setOverrideCursor (const QCursor &)
virtual void restoreOverrideCursor ()
Public Member Functions
PythonEditorView (PythonEditor *editor, QWidget *parent)
~PythonEditorView () override
bool onMsg (const char *pMsg, const char **ppReturn) override
bool onHasMsg (const char *pMsg) const override
Public Member Functions inherited from Gui::EditorView
EditorView (TextEdit *editor, QWidget *parent)
~EditorView () override
QPlainTextEdit * getEditor () const
void setDisplayName (DisplayName)
void OnChange (Base::Subject< const char * > &rCaller, const char *rcReason) override
const char * getName () const override
returns the name of the view (important for messages)
void onUpdate () override
get called when the document is updated
bool canClose () override
bool open (const QString &f)
bool saveAs ()
void cut ()
void copy ()
void paste ()
void undo ()
void redo ()
void print () override
void printPdf () override
void printPreview () override
void print (QPrinter *) override
QStringList undoActions () const override
QStringList redoActions () const override
QString fileName () const
Public Member Functions inherited from Gui::MDIView
MDIView (Gui::Document *pcDocument, QWidget *parent, Qt::WindowFlags wflags=Qt::WindowFlags())
~MDIView () override
void onRelabel (Gui::Document *pDoc) override
get called when the document is updated
virtual void viewAll ()
QString buildWindowTitle () const
build window title
bool onMsg (const char *pMsg, const char **ppReturn) override
Message handler.
bool onHasMsg (const char *pMsg) const override
Message handler test.
bool canClose () override
overwrite when checking on close state
void deleteSelf () override
delete itself
PyObject * getPyObject () override
void savePrinterSettings (QPrinter *printer)
void restorePrinterSettings (QPrinter *printer)
QSize minimumSizeHint () const override
virtual void setCurrentViewMode (ViewMode mode)
ViewMode currentViewMode () const
template<typename _T >
_T getActiveObject (const char *name, App::DocumentObject **parent=nullptr, std::string *subname=nullptr) const
access getter for the active object list
void setActiveObject (App::DocumentObject *o, const char *n, const char *subname=nullptr)
bool hasActiveObject (const char *n) const
bool isActiveObject (App::DocumentObject *o, const char *n, const char *subname=nullptr) const
virtual bool containsViewProvider (const ViewProvider *) const
containsViewProvider Checks if the given view provider is part of this view. The default implementation returns false.
Public Member Functions inherited from Gui::BaseView
BaseView (Gui::Document *pcDocument=nullptr)
~BaseView () override
void setDocument (Gui::Document *pcDocument)
sets the view to another document (called by Application)
void onClose ()
is sent from the document in order to close the document
Gui::Document * getGuiDocument () const
returns the document the view is attached to
App::Document * getAppDocument () const
returns the document the view is attached to
bool isPassive () const
indicates if the view is in passive mode
virtual void onRename (Gui::Document *)
get called when the document is renamed (change of its internal name)
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from Gui::WindowParameter
WindowParameter (const char *name)
~WindowParameter () override
void OnChange (Base::Subject< const char * > &rCaller, const char *sReason) override
ParameterGrp::handle getWindowParameter ()
return the parameter group of this window
Additional Inherited Members
Public Types inherited from Gui::EditorView
enum DisplayName { FullName, FileName, BaseName }
Public Types inherited from Gui::MDIView
enum ViewMode { Child, TopLevel, FullScreen }
MDI view mode enum.
Signals inherited from Gui::EditorView
void changeFileName (const QString &)
Signals inherited from Gui::MDIView
void message (const QString &, int)
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Public Member Functions inherited from Gui::WindowParameter
static ParameterGrp::handle getDefaultParameter ()
get the parameters
Protected Slots inherited from Gui::MDIView
virtual void windowStateChanged (QWidget *)
Protected Member Functions inherited from Gui::EditorView
void focusInEvent (QFocusEvent *e) override
void showEvent (QShowEvent *) override
void hideEvent (QHideEvent *) override
void closeEvent (QCloseEvent *) override
Protected Member Functions inherited from Gui::MDIView
void closeEvent (QCloseEvent *e) override
void changeEvent (QEvent *e) override
Protected Member Functions inherited from Gui::WindowParameter
bool setGroupName (const char *name)
template<typename S , typename T >
void setSlotParamChanged (S slot, T *obsPtr)
connect slot to ParameterManager signal
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Gui::MDIView
PyObject * pythonObject
Protected Attributes inherited from Gui::BaseView
Gui::Document * _pcDocument
bool bIsDetached {false}
bool bIsPassive {false}
Detailed Description
Definition at line 122 of file EditorView.h.
Constructor & Destructor Documentation
PythonEditorView()
PythonEditorView::PythonEditorView (PythonEditor * editor, QWidget * parent)
Definition at line 642 of file EditorView.cpp.
References Gui::EditorView::changeFileName(), draftgeoutils.intersections::connect(), Path.Post.Utils::editor(), and Gui::PythonEditor::setFileName().
~PythonEditorView()
PythonEditorView::~PythonEditorView () override
Definition at line 650 of file EditorView.cpp.
Member Function Documentation
executeScript
void PythonEditorView::executeScript () slot
Runs the opened script in the macro manager.
Definition at line 696 of file EditorView.cpp.
References SCL.SimpleDataTypes::e, Gui::MacroManager::File, Gui::EditorView::fileName(), Gui::getMainWindow(), Gui::PythonTracingWatcher::getTrace(), Gui::Application::Instance, Gui::Application::macroManager(), Gui::EditorView::onHasMsg(), Gui::EditorView::onMsg(), and Gui::MacroManager::run().
Referenced by onMsg().
hideDebugMarker
void PythonEditorView::hideDebugMarker () slot
Definition at line 732 of file EditorView.cpp.
References Gui::PythonEditor::hideDebugMarker().
Referenced by Gui::PythonDebugger::hideDebugMarker().
onHasMsg()
bool PythonEditorView::onHasMsg (const char * pMsg) const override virtual
Checks if the action pMsg is available. This is for enabling/disabling the corresponding buttons or menu items for this action.
Reimplemented from Gui::EditorView.
Definition at line 679 of file EditorView.cpp.
References Gui::EditorView::onHasMsg().
onMsg()
bool PythonEditorView::onMsg (const char * pMsg, const char ** ppReturn) override virtual
Runs the action specified by pMsg.
Reimplemented from Gui::EditorView.
Definition at line 658 of file EditorView.cpp.
References executeScript(), Gui::EditorView::onMsg(), startDebug(), and toggleBreakpoint().
showDebugMarker
void PythonEditorView::showDebugMarker (int line) slot
Definition at line 727 of file EditorView.cpp.
References Gui::PythonEditor::showDebugMarker().
Referenced by Gui::PythonDebugger::showDebugMarker().
startDebug
void PythonEditorView::startDebug () slot
Definition at line 717 of file EditorView.cpp.
References Gui::PythonEditor::startDebug().
Referenced by onMsg().
toggleBreakpoint
void PythonEditorView::toggleBreakpoint () slot
Definition at line 722 of file EditorView.cpp.
References Gui::PythonEditor::toggleBreakpoint().
Referenced by onMsg().
The documentation for this class was generated from the following files:
EditorView.h
EditorView.cpp