FreeCAD: App::DocumentObjectExtension Class Reference
App::DocumentObjectExtension Class Reference
Extension with special document object calls.
#include <DocumentObjectExtension.h>
Public Member Functions
virtual Base::Type getExtensionTypeId (void) const override
DocumentObjectExtension ()
~DocumentObjectExtension () override
App::DocumentObject * getExtendedObject ()
const App::DocumentObject * getExtendedObject () const
virtual short extensionMustExecute ()
virtual App::DocumentObjectExecReturn * extensionExecute ()
virtual void onExtendedSettingDocument ()
get called after setting the document
virtual void onExtendedDocumentRestored ()
get called after a document has been fully restored
virtual void onExtendedSetupObject ()
get called after a brand new object was created
virtual void onExtendedUnsetupObject ()
get called when object is going to be removed from the document
PyObject * getExtensionPyObject () override
virtual const char * getViewProviderExtensionName () const
virtual bool extensionGetSubObject (DocumentObject *&ret, const char *subname, PyObject **pyObj, Base::Matrix4D *mat, bool transform, int depth) const
virtual bool extensionGetSubObjects (std::vector< std::string > &ret, int reason) const
virtual bool extensionGetLinkedObject (DocumentObject *&ret, bool recursive, Base::Matrix4D *mat, bool transform, int depth) const
virtual int extensionSetElementVisible (const char *, bool)
virtual int extensionIsElementVisible (const char *)
virtual bool extensionHasChildElement () const
Public Member Functions inherited from App::Extension
Extension ()=default
virtual ~Extension ()
virtual void initExtension (App::ExtensionContainer *obj)
App::ExtensionContainer * getExtendedContainer ()
const App::ExtensionContainer * getExtendedContainer () const
std::string name () const
bool isPythonExtension ()
virtual Property * extensionGetPropertyByName (const char *name) const
find a property by its name
virtual const char * extensionGetPropertyName (const Property *prop) const
get the name of a property
virtual void extensionGetPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual void extensionGetPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual short extensionGetPropertyType (const Property *prop) const
get the Type of a Property
virtual short extensionGetPropertyType (const char *name) const
get the Type of a named Property
virtual const char * extensionGetPropertyGroup (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * extensionGetPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual void extensionSave (Base::Writer &) const
virtual void extensionRestore (Base::XMLReader &)
bool extensionIsDerivedFrom (const Base::Type type) const
Static Public Member Functions
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Static Public Member Functions inherited from App::Extension
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Protected Member Functions
virtual const App::PropertyData & extensionGetPropertyData (void) const override
Protected Member Functions inherited from App::Extension
virtual void extensionOnChanged (const Property *p)
virtual bool extensionHandleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
returns true if the property name change was handled by the extension.
virtual bool extensionHandleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop)
returns true if the property type change was handled by the extension.
void initExtensionType (Base::Type type)
Static Protected Member Functions
static const App::PropertyData * extensionGetPropertyDataPtr (void)
Static Protected Member Functions inherited from App::Extension
static const App::PropertyData * extensionGetPropertyDataPtr (void)
static void initExtensionSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Base::Type::instantiationMethod method=nullptr)
Additional Inherited Members
Protected Attributes inherited from App::Extension
bool m_isPythonExtension = false
Py::SmartPtr ExtensionPythonObject
Detailed Description
Extension with special document object calls.
Definition at line 42 of file DocumentObjectExtension.h.
Constructor & Destructor Documentation
DocumentObjectExtension()
DocumentObjectExtension::DocumentObjectExtension ()
Definition at line 35 of file DocumentObjectExtension.cpp.
References getExtensionClassTypeId().
~DocumentObjectExtension()
DocumentObjectExtension::~DocumentObjectExtension () override default
Member Function Documentation
create()
void * App::DocumentObjectExtension::create (void) static
Definition at line 33 of file DocumentObjectExtension.cpp.
Referenced by draftguitools.gui_labels.Label::action().
extensionExecute()
App::DocumentObjectExecReturn * DocumentObjectExtension::extensionExecute () virtual
Reimplemented in App::LinkBaseExtension, App::GroupExtension, Part::AttachExtension, App::OriginGroupExtension, and Part::PrismExtension.
Definition at line 48 of file DocumentObjectExtension.cpp.
References App::DocumentObject::StdReturn.
Referenced by Part::PrismExtension::extensionExecute(), Part::AttachExtension::extensionExecute(), App::GroupExtension::extensionExecute(), and App::LinkBaseExtension::extensionExecute().
extensionGetLinkedObject()
bool DocumentObjectExtension::extensionGetLinkedObject (DocumentObject *& ret, bool recursive, Base::Matrix4D * mat, bool transform, int depth) const virtual
Get the linked object
See also
DocumentObject::getLinkedObject()
Returns
Return turn if handled, the linked object is returned in ret
Reimplemented in App::LinkBaseExtension.
Definition at line 105 of file DocumentObjectExtension.cpp.
extensionGetPropertyData()
const App::PropertyData & App::DocumentObjectExtension::extensionGetPropertyData (void) const override protected virtual
Reimplemented from App::Extension.
Reimplemented in App::LinkExtension, and App::LinkBaseExtension.
Definition at line 33 of file DocumentObjectExtension.cpp.
extensionGetPropertyDataPtr()
const App::PropertyData * App::DocumentObjectExtension::extensionGetPropertyDataPtr (void) static protected
Definition at line 33 of file DocumentObjectExtension.cpp.
extensionGetSubObject()
bool DocumentObjectExtension::extensionGetSubObject (DocumentObject *& ret, const char * subname, PyObject ** pyObj, Base::Matrix4D * mat, bool transform, int depth) const virtual
Get the sub object by name
See also
DocumentObject::getSubObject()
Returns
Return turn if handled, the sub object is returned in ret
Reimplemented in App::LinkBaseExtension, App::GeoFeatureGroupExtension, App::GroupExtension, and App::OriginGroupExtension.
Definition at line 90 of file DocumentObjectExtension.cpp.
extensionGetSubObjects()
bool DocumentObjectExtension::extensionGetSubObjects (std::vector< std::string > & ret, int reason) const virtual
Get name references of all sub objects
See also
DocumentObject::getSubObjects()
Returns
Return turn if handled, the sub object is returned in ret
Reimplemented in App::LinkBaseExtension, App::GeoFeatureGroupExtension, and App::GroupExtension.
Definition at line 100 of file DocumentObjectExtension.cpp.
extensionHasChildElement()
virtual bool App::DocumentObjectExtension::extensionHasChildElement () const inline virtual
Reimplemented in App::LinkBaseExtension.
Definition at line 117 of file DocumentObjectExtension.h.
extensionIsElementVisible()
virtual int App::DocumentObjectExtension::extensionIsElementVisible (const char *) inline virtual
Reimplemented in App::LinkBaseExtension.
Definition at line 113 of file DocumentObjectExtension.h.
extensionMustExecute()
short int DocumentObjectExtension::extensionMustExecute () virtual
Reimplemented in App::LinkBaseExtension, Part::AttachExtension, Part::PrismExtension, and App::OriginGroupExtension.
Definition at line 42 of file DocumentObjectExtension.cpp.
Referenced by App::OriginGroupExtension::extensionMustExecute().
extensionSetElementVisible()
virtual int App::DocumentObjectExtension::extensionSetElementVisible (const char * , bool) inline virtual
Reimplemented in App::LinkBaseExtension.
Definition at line 109 of file DocumentObjectExtension.h.
getExtendedObject() [1/2]
DocumentObject * DocumentObjectExtension::getExtendedObject ()
Definition at line 76 of file DocumentObjectExtension.cpp.
References Base::Persistence::getClassTypeId(), and App::Extension::getExtendedContainer().
Referenced by PartDesign::Body::addObject(), App::GroupExtension::addObject(), App::GroupExtension::addObjects(), App::GeoFeatureGroupExtension::addObjects(), App::OriginGroupExtension::extensionOnChanged(), App::GeoFeatureGroupExtension::extensionOnChanged(), App::GroupExtension::extensionOnChanged(), App::GroupExtension::getObject(), App::OriginGroupExtension::getOrigin(), App::GeoFeatureGroupExtension::globalGroupPlacement(), App::GroupExtension::hasObject(), App::GroupExtension::isChildOf(), App::OriginGroupExtension::onExtendedSetupObject(), and App::LinkBaseExtension::updateGroup().
getExtendedObject() [2/2]
const App::DocumentObject* App::DocumentObjectExtension::getExtendedObject () const
getExtensionClassTypeId()
Base::Type App::DocumentObjectExtension::getExtensionClassTypeId (void) static
Definition at line 33 of file DocumentObjectExtension.cpp.
Referenced by Part::AttachExtension::AttachExtension(), Gui::ViewProviderDocumentObject::canDelete(), TechDraw::CosmeticExtension::CosmeticExtension(), DocumentObjectExtension(), App::Document::exportGraphviz(), Gui::ViewProviderGeoFeatureGroupExtension::extensionClaimChildren(), App::GeoFeatureGroupExtension::extensionGetSubObject(), PartGui::ViewProviderAttachExtension::extensionMergeColorfullOverlayIcons(), App::OriginGroupExtension::extensionOnChanged(), App::GroupExtension::extensionOnChanged(), PartGui::ViewProviderAttachExtension::extensionSetupContextMenu(), PartGui::ViewProviderAttachExtension::extensionUpdateData(), Fem::FemPostSmoothFilterExtension::FemPostSmoothFilterExtension(), App::LinkBaseExtension::flattenSubname(), App::GeoFeatureGroupExtension::GeoFeatureGroupExtension(), App::OriginGroupExtension::getGroupOfObject(), App::GroupExtension::getGroupOfObject(), App::GeoFeatureGroupExtension::getInvalidLinkObjects(), App::LinkBaseExtension::getLinkedChildren(), PartDesignGui::getParent(), App::GroupExtension::GroupExtension(), App::GroupExtension::hasObject(), PartDesignGui::isFeatureMovable(), Gui::DocumentObjectItem::isGroup(), App::GeoFeatureGroupExtension::isLinkValid(), PartDesignGui::isPartDesignAwareObjecta(), Part::PrismExtension::PrismExtension(), PartDesignGui::relinkToOrigin(), Gui::LinkView::setChildren(), PartGui::TaskAttacher::TaskAttacher(), and Gui::DocumentObjectItem::testStatus().
getExtensionPyObject()
PyObject * DocumentObjectExtension::getExtensionPyObject () override virtual
Reimplemented from App::Extension.
Reimplemented in App::LinkBaseExtension, Part::AttachExtension, App::GroupExtension, TechDraw::CosmeticExtension, and App::SuppressibleExtension.
Definition at line 66 of file DocumentObjectExtension.cpp.
References App::Extension::ExtensionPythonObject, Py::SmartPtr::is(), and Py::new_reference_to().
getExtensionTypeId()
Base::Type App::DocumentObjectExtension::getExtensionTypeId (void) const override virtual
Reimplemented from App::Extension.
Reimplemented in App::LinkExtension, and App::LinkBaseExtension.
Definition at line 33 of file DocumentObjectExtension.cpp.
Referenced by App::GroupExtension::extensionOnChanged().
getViewProviderExtensionName()
virtual const char* App::DocumentObjectExtension::getViewProviderExtensionName () const inline virtual
returns the type name of the ViewProviderExtension which is automatically attached to the viewprovider object when it is initiated
Definition at line 74 of file DocumentObjectExtension.h.
init()
void App::DocumentObjectExtension::init (void) static
Definition at line 33 of file DocumentObjectExtension.cpp.
Referenced by App::Application::initTypes(), DocumentObject.DocumentObject::onChanged(), and PyMOD_INIT_FUNC().
onExtendedDocumentRestored()
void DocumentObjectExtension::onExtendedDocumentRestored () virtual
get called after a document has been fully restored
Reimplemented in App::LinkBaseExtension, and Part::AttachExtension.
Definition at line 57 of file DocumentObjectExtension.cpp.
Referenced by App::LinkBaseExtension::onExtendedDocumentRestored().
onExtendedSettingDocument()
void DocumentObjectExtension::onExtendedSettingDocument () virtual
get called after setting the document
Definition at line 54 of file DocumentObjectExtension.cpp.
onExtendedSetupObject()
void DocumentObjectExtension::onExtendedSetupObject () virtual
get called after a brand new object was created
Reimplemented in App::OriginGroupExtension.
Definition at line 60 of file DocumentObjectExtension.cpp.
Referenced by App::OriginGroupExtension::onExtendedSetupObject().
onExtendedUnsetupObject()
void DocumentObjectExtension::onExtendedUnsetupObject () virtual
get called when object is going to be removed from the document
Reimplemented in App::LinkBaseExtension, and App::OriginGroupExtension.
Definition at line 63 of file DocumentObjectExtension.cpp.
Referenced by App::OriginGroupExtension::onExtendedUnsetupObject().
The documentation for this class was generated from the following files:
DocumentObjectExtension.h
DocumentObjectExtension.cpp