FreeCAD: App::SubObjectT Class Reference
App::SubObjectT Class Reference
#include <DocumentObserver.h>
Public Types
enum NormalizeOption : uint8_t { NormalizeOption::NoElement = 0x01, NormalizeOption::NoFlatten = 0x02, NormalizeOption::KeepSubName = 0x04, NormalizeOption::ConvertIndex = 0x08 }
Options used by normalize()
using NormalizeOptions = Base::Flags< NormalizeOption >
Public Member Functions
SubObjectT ()
SubObjectT (const SubObjectT &)
SubObjectT (SubObjectT &&)
SubObjectT (const DocumentObjectT &obj, const char *subname)
SubObjectT (const DocumentObject *, const char *subname)
SubObjectT (const DocumentObject *)
SubObjectT (const char *docName, const char *objName, const char *subname)
SubObjectT & operator= (const SubObjectT &)
SubObjectT & operator= (SubObjectT &&)
SubObjectT & operator= (const DocumentObjectT &)
SubObjectT & operator= (const App::DocumentObject *)
bool operator== (const SubObjectT &) const
void setSubName (const char *subname)
Set the subname path to the sub-object.
void setSubName (const std::string &subname)
Set the subname path to the sub-object.
const std::string & getSubName () const
Return the subname path.
std::string getObjectFullName (const char *docName=nullptr) const
std::string getSubObjectFullName (const char *docName=nullptr) const
std::string getSubNameNoElement () const
Return the subname path without sub-element.
const char * getElementName () const
Return the sub-element (Face, Edge, etc) of the subname path.
bool hasSubObject () const
Check if there is any sub object reference.
bool hasSubElement () const
Check if there is any sub element reference.
std::string getNewElementName () const
Return the new style sub-element name.
std::string getOldElementName (int *index=nullptr) const
DocumentObject * getSubObject () const
Return the sub-object.
std::vector< DocumentObject * > getSubObjectList () const
Return all objects along the subname path.
bool operator< (const SubObjectT &other) const
std::string getSubObjectPython (bool force=true) const
bool normalize (NormalizeOptions options=NormalizeOption())
SubObjectT normalized (NormalizeOptions options=NormalizeOption()) const
Return a normalize copy of itself.
Public Member Functions inherited from App::DocumentObjectT
DocumentObjectT ()
DocumentObjectT (const DocumentObjectT &)
DocumentObjectT (DocumentObjectT &&)
DocumentObjectT (const DocumentObject *)
DocumentObjectT (const Document *, const std::string &objName)
DocumentObjectT (const char *docName, const char *objName)
DocumentObjectT (const Property *)
~DocumentObjectT ()
DocumentObjectT & operator= (const DocumentObjectT &)
DocumentObjectT & operator= (DocumentObjectT &&)
void operator= (const DocumentObject *)
void operator= (const Property *)
bool operator== (const DocumentObjectT &) const
Document * getDocument () const
const std::string & getDocumentName () const
std::string getDocumentPython () const
DocumentObject * getObject () const
Property * getProperty () const
const std::string & getObjectName () const
const std::string & getObjectLabel () const
const std::string & getPropertyName () const
std::string getObjectPython () const
std::string getPropertyPython () const
template<typename T >
T * getObjectAs () const
template<typename T >
T * getPropertyAs () const
Detailed Description
Definition at line 186 of file App/DocumentObserver.h.
Member Typedef Documentation
NormalizeOptions
using App::SubObjectT::NormalizeOptions = Base::Flags<NormalizeOption>
Definition at line 302 of file App/DocumentObserver.h.
Member Enumeration Documentation
NormalizeOption
enum App::SubObjectT::NormalizeOption : uint8_t strong
Options used by normalize()
Enumerator
NoElement
Do not include sub-element reference in the output path.
NoFlatten
Do not flatten the output path. If not specified, the output path will be flatten to exclude intermediate objects that belong to the same geo feature group before resolving. For example, Part.Fusion.Box. -> Part.Box.
KeepSubName
Do not change the sub-object component inside the path. Each component of the subname object path can be either the object internal name, the label of the object if starts with '$', or an integer index. If this option is not specified, each component will be converted to object internal name, except for integer index.
ConvertIndex
Convert integer index in the path to sub-object internal name
Definition at line 279 of file App/DocumentObserver.h.
Constructor & Destructor Documentation
SubObjectT() [1/7]
SubObjectT::SubObjectT () default
Constructor
SubObjectT() [2/7]
SubObjectT::SubObjectT (const SubObjectT &) default
Constructor
SubObjectT() [3/7]
SubObjectT::SubObjectT (SubObjectT && other)
Constructor
Definition at line 275 of file App/DocumentObserver.cpp.
SubObjectT() [4/7]
SubObjectT::SubObjectT (const DocumentObjectT & obj, const char * subname)
Constructor
Definition at line 289 of file App/DocumentObserver.cpp.
SubObjectT() [5/7]
SubObjectT::SubObjectT (const DocumentObject * obj, const char * subname)
Constructor
Definition at line 280 of file App/DocumentObserver.cpp.
SubObjectT() [6/7]
SubObjectT::SubObjectT (const DocumentObject * obj)
Constructor
Definition at line 285 of file App/DocumentObserver.cpp.
SubObjectT() [7/7]
SubObjectT::SubObjectT (const char * docName, const char * objName, const char * subname)
Constructor
Definition at line 294 of file App/DocumentObserver.cpp.
Member Function Documentation
getElementName()
const char * SubObjectT::getElementName () const
Return the sub-element (Face, Edge, etc) of the subname path.
Definition at line 467 of file App/DocumentObserver.cpp.
References Data::findElementName().
Referenced by buildAdapter(), getLocatedShape(), getShapeFromStrings(), hasSubElement(), MeasureAngleHandler(), MeasureAreaHandler(), MeasureDistanceHandler(), MeasureLengthHandler(), and MeasurePositionHandler().
getNewElementName()
std::string SubObjectT::getNewElementName () const
Return the new style sub-element name.
Definition at line 483 of file App/DocumentObserver.cpp.
References App::DocumentObjectT::getObject(), Path.Post.scripts.opensbp_post::move(), App::ElementNamePair::newName, and App::GeoFeature::resolveElement().
getObjectFullName()
std::string SubObjectT::getObjectFullName (const char * docName = nullptr) const
Return docname::objname (label)
Parameters
docName optional document name. The document prefix will only be printed if it is different then the given 'doc'.
Definition at line 545 of file App/DocumentObserver.cpp.
References toolbit-attributes::doc, App::DocumentObjectT::getDocument(), App::DocumentObjectT::getDocumentName(), App::DocumentObjectT::getObjectLabel(), and App::DocumentObjectT::getObjectName().
Referenced by getSubObjectFullName().
getOldElementName()
std::string SubObjectT::getOldElementName (int * index = nullptr) const
Return the old style sub-element name
Parameters
index if given, then return the element type, and extract the index
Definition at line 494 of file App/DocumentObserver.cpp.
References App::DocumentObjectT::getObject(), Path.Post.scripts.opensbp_post::move(), App::ElementNamePair::oldName, RobotExample::pos, and App::GeoFeature::resolveElement().
Referenced by App::PropertyLinkBase::_getLinksTo(), App::PropertyXLinkSubList::_getLinksToList(), Spreadsheet::PropertySheet::getLinksTo(), App::PropertyExpressionEngine::getLinksTo(), App::PropertyLinkSubList::getLinksTo(), and normalize().
getSubName()
const std::string & SubObjectT::getSubName () const
Return the subname path.
Definition at line 457 of file App/DocumentObserver.cpp.
Referenced by PartDesign::SubShapeBinder::collapseGeoChildren(), Gui::Dialog::DlgPropertyLink::formatObject(), getLocatedShape(), Measure::ResolveResult::getShortSub(), operator<(), Gui::PropertyEditor::LinkSelection::select(), Gui::SelectionSingleton::slotSelectionChanged(), and MeshPartGui::Mesh2ShapeGmsh::writeProject().
getSubNameNoElement()
std::string SubObjectT::getSubNameNoElement () const
Return the subname path without sub-element.
Definition at line 462 of file App/DocumentObserver.cpp.
References Data::noElementName().
getSubObject()
App::DocumentObject * SubObjectT::getSubObject () const
Return the sub-object.
Definition at line 516 of file App/DocumentObserver.cpp.
References App::DocumentObjectT::getObject().
Referenced by App::PropertyLinkBase::_getLinksTo(), App::PropertyXLinkSubList::_getLinksToList(), Spreadsheet::PropertySheet::getLinksTo(), App::PropertyExpressionEngine::getLinksTo(), App::PropertyLinkSubList::getLinksTo(), getSubObjectFullName(), and Gui::PropertyEditor::LinkSelection::select().
getSubObjectFullName()
std::string SubObjectT::getSubObjectFullName (const char * docName = nullptr) const
Return docname::objname.subname (label)
Parameters
doc optional document name. The document prefix will only be printed if it is different then the given 'doc'.
Definition at line 564 of file App/DocumentObserver.cpp.
References toolbit-attributes::doc, App::DocumentObjectT::getDocument(), App::DocumentObjectT::getDocumentName(), getObjectFullName(), App::DocumentObjectT::getObjectName(), and getSubObject().
Referenced by PartDesign::Loft::getSectionShape().
getSubObjectList()
std::vector< App::DocumentObject * > SubObjectT::getSubObjectList () const
Return all objects along the subname path.
Definition at line 536 of file App/DocumentObserver.cpp.
References App::DocumentObjectT::getObject().
Referenced by getLocatedShape().
getSubObjectPython()
std::string SubObjectT::getSubObjectPython (bool force = true) const
Definition at line 525 of file App/DocumentObserver.cpp.
References Base::Tools::escapedUnicodeFromUtf8(), App::DocumentObjectT::getObjectPython(), and Path.Post.scripts.refactored_centroid_post::str.
hasSubElement()
bool SubObjectT::hasSubElement () const
Check if there is any sub element reference.
Definition at line 477 of file App/DocumentObserver.cpp.
References getElementName().
hasSubObject()
bool SubObjectT::hasSubObject () const
Check if there is any sub object reference.
Definition at line 472 of file App/DocumentObserver.cpp.
References Data::findElementName().
normalize()
bool SubObjectT::normalize (NormalizeOptions options = NormalizeOption())
Normalize the subname path to use only the object internal name and old style element name
Returns
Return whether the subname has been changed
Definition at line 380 of file App/DocumentObserver.cpp.
References ConvertIndex, App::DocumentObjectT::getObject(), getOldElementName(), SplineSurface::i, KeepSubName, Path.Post.scripts.opensbp_post::move(), NoElement, NoFlatten, replaceobj::objs, importers.importIFCmulticore::subs, and Base::Flags< Enum >::testFlag().
Referenced by PartDesign::SubShapeBinder::collapseGeoChildren(), and normalized().
normalized()
SubObjectT App::SubObjectT::normalized (NormalizeOptions options = NormalizeOption()) const
Return a normalize copy of itself.
Definition at line 445 of file App/DocumentObserver.cpp.
References normalize().
operator<()
bool SubObjectT::operator< (const SubObjectT & other) const
Definition at line 299 of file App/DocumentObserver.cpp.
References App::DocumentObjectT::getDocumentName(), App::DocumentObjectT::getObjectName(), App::DocumentObjectT::getPropertyName(), and getSubName().
operator=() [1/4]
SubObjectT & SubObjectT::operator= (const App::DocumentObject * other)
Assignment operator
Definition at line 352 of file App/DocumentObserver.cpp.
operator=() [2/4]
SubObjectT & SubObjectT::operator= (const DocumentObjectT & other)
Assignment operator
Definition at line 342 of file App/DocumentObserver.cpp.
operator=() [3/4]
SubObjectT & SubObjectT::operator= (const SubObjectT & other)
Assignment operator
Definition at line 322 of file App/DocumentObserver.cpp.
operator=() [4/4]
SubObjectT & SubObjectT::operator= (SubObjectT && other)
Assignment operator
Definition at line 332 of file App/DocumentObserver.cpp.
References Path.Post.scripts.opensbp_post::move().
operator==()
bool SubObjectT::operator== (const SubObjectT & other) const
Equality operator
Definition at line 359 of file App/DocumentObserver.cpp.
setSubName() [1/2]
void SubObjectT::setSubName (const char * subname)
Set the subname path to the sub-object.
Definition at line 452 of file App/DocumentObserver.cpp.
References toolbit-attributes::s.
Referenced by Gui::SelectionSingleton::slotSelectionChanged().
setSubName() [2/2]
void App::SubObjectT::setSubName (const std::string & subname) inline
Set the subname path to the sub-object.
Definition at line 229 of file App/DocumentObserver.h.
The documentation for this class was generated from the following files:
App/DocumentObserver.h
App/DocumentObserver.cpp