FreeCAD: Gui::ViewProviderWeakPtrT::Private Class Reference
Gui::ViewProviderWeakPtrT::Private Class Reference
Public Types
using Connection = boost::signals2::scoped_connection
Public Member Functions
Private (ViewProviderDocumentObject *obj)
void deletedDocument (const Gui::Document &doc)
void createdObject (const Gui::ViewProvider &obj) noexcept
void deletedObject (const Gui::ViewProvider &obj) noexcept
void reset ()
void set (ViewProviderDocumentObject *obj)
ViewProviderDocumentObject * get () const
Public Attributes
Gui::ViewProviderDocumentObject * object
bool indocument {false}
Connection connectApplicationDeletedDocument
Connection connectDocumentCreatedObject
Connection connectDocumentDeletedObject
Detailed Description
Definition at line 285 of file Gui/DocumentObserver.cpp.
Member Typedef Documentation
Connection
using Gui::ViewProviderWeakPtrT::Private::Connection = boost::signals2::scoped_connection
Definition at line 342 of file Gui/DocumentObserver.cpp.
Constructor & Destructor Documentation
Private()
Gui::ViewProviderWeakPtrT::Private::Private (ViewProviderDocumentObject * obj) inline
Definition at line 287 of file Gui/DocumentObserver.cpp.
References Gui::ViewProviderWeakPtrT::Private::set().
Member Function Documentation
createdObject()
void Gui::ViewProviderWeakPtrT::Private::createdObject (const Gui::ViewProvider & obj) inline noexcept
Definition at line 296 of file Gui/DocumentObserver.cpp.
References Gui::ViewProviderWeakPtrT::Private::indocument.
Referenced by Gui::ViewProviderWeakPtrT::Private::set().
deletedDocument()
void Gui::ViewProviderWeakPtrT::Private::deletedDocument (const Gui::Document & doc) inline
Definition at line 290 of file Gui/DocumentObserver.cpp.
References toolbit-attributes::doc, Gui::ViewProviderDocumentObject::getDocument(), Gui::ViewProviderWeakPtrT::Private::object, and Gui::ViewProviderWeakPtrT::Private::reset().
Referenced by Gui::ViewProviderWeakPtrT::Private::set().
deletedObject()
void Gui::ViewProviderWeakPtrT::Private::deletedObject (const Gui::ViewProvider & obj) inline noexcept
Definition at line 302 of file Gui/DocumentObserver.cpp.
References Gui::ViewProviderWeakPtrT::Private::indocument.
Referenced by Gui::ViewProviderWeakPtrT::Private::set().
get()
ViewProviderDocumentObject* Gui::ViewProviderWeakPtrT::Private::get () const inline
Definition at line 336 of file Gui/DocumentObserver.cpp.
References Gui::ViewProviderWeakPtrT::Private::indocument, and Gui::ViewProviderWeakPtrT::Private::object.
Referenced by draftguitools.gui_trackers.editTracker::move().
reset()
void Gui::ViewProviderWeakPtrT::Private::reset () inline
Definition at line 307 of file Gui/DocumentObserver.cpp.
References Gui::ViewProviderWeakPtrT::Private::connectApplicationDeletedDocument, Gui::ViewProviderWeakPtrT::Private::connectDocumentCreatedObject, Gui::ViewProviderWeakPtrT::Private::connectDocumentDeletedObject, and Gui::ViewProviderWeakPtrT::Private::indocument.
Referenced by ArchVRM.Renderer::__init__(), Gui::ViewProviderWeakPtrT::Private::deletedDocument(), draftguitools.gui_trackers.gridTracker::set(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testAll(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testBuildings(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCommonPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCustom(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testExtrusions(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testHierarchy(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testIFC4(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testMaterials(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testQuantities(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testRectangleProfileDef(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSites(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSolid(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandardCases(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandards(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStoreys(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testTinyLines(), and bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testUndefined().
set()
void Gui::ViewProviderWeakPtrT::Private::set (ViewProviderDocumentObject * obj) inline
Definition at line 314 of file Gui/DocumentObserver.cpp.
References draftgeoutils.faces::bind(), Gui::ViewProviderWeakPtrT::Private::connectApplicationDeletedDocument, Gui::ViewProviderWeakPtrT::Private::connectDocumentCreatedObject, Gui::ViewProviderWeakPtrT::Private::connectDocumentDeletedObject, Gui::ViewProviderWeakPtrT::Private::createdObject(), Gui::ViewProviderWeakPtrT::Private::deletedDocument(), Gui::ViewProviderWeakPtrT::Private::deletedObject(), toolbit-attributes::doc, Gui::ViewProviderDocumentObject::getDocument(), and Gui::ViewProviderWeakPtrT::Private::indocument.
Referenced by draftguitools.gui_trackers.editTracker::move(), and Gui::ViewProviderWeakPtrT::Private::Private().
Member Data Documentation
connectApplicationDeletedDocument
Connection Gui::ViewProviderWeakPtrT::Private::connectApplicationDeletedDocument
Definition at line 343 of file Gui/DocumentObserver.cpp.
Referenced by Gui::ViewProviderWeakPtrT::Private::reset(), and Gui::ViewProviderWeakPtrT::Private::set().
connectDocumentCreatedObject
Connection Gui::ViewProviderWeakPtrT::Private::connectDocumentCreatedObject
Definition at line 344 of file Gui/DocumentObserver.cpp.
Referenced by Gui::ViewProviderWeakPtrT::Private::reset(), and Gui::ViewProviderWeakPtrT::Private::set().
connectDocumentDeletedObject
Connection Gui::ViewProviderWeakPtrT::Private::connectDocumentDeletedObject
Definition at line 345 of file Gui/DocumentObserver.cpp.
Referenced by Gui::ViewProviderWeakPtrT::Private::reset(), and Gui::ViewProviderWeakPtrT::Private::set().
indocument
bool Gui::ViewProviderWeakPtrT::Private::indocument {false}
Definition at line 341 of file Gui/DocumentObserver.cpp.
Referenced by Gui::ViewProviderWeakPtrT::Private::createdObject(), Gui::ViewProviderWeakPtrT::Private::deletedObject(), Gui::ViewProviderWeakPtrT::Private::get(), Gui::ViewProviderWeakPtrT::Private::reset(), and Gui::ViewProviderWeakPtrT::Private::set().
object
Gui::ViewProviderDocumentObject* Gui::ViewProviderWeakPtrT::Private::object
Definition at line 340 of file Gui/DocumentObserver.cpp.
Referenced by ArchIFCView.IfcContextUI::accept(), Gui::ViewProviderWeakPtrT::Private::deletedDocument(), Gui::ViewProviderWeakPtrT::Private::get(), ArchIFCView.IfcContextUI::prefillMapConversionForm(), importers.importIFCHelper.ProjectImporter::setAttributes(), and importers.importIFCHelper.ProjectImporter::setComplexAttributes().
The documentation for this class was generated from the following file:
Gui/DocumentObserver.cpp