FreeCAD: MeshCore::MeshEvalCorruptedFacets Class Reference
MeshCore::MeshEvalCorruptedFacets Class Reference
#include <Degeneration.h>
Public Member Functions
MeshEvalCorruptedFacets (const MeshKernel &rclM)
bool Evaluate () override
std::vector< FacetIndex > GetIndices () const
Public Member Functions inherited from MeshCore::MeshEvaluation
MeshEvaluation (const MeshKernel &rclB)
virtual ~MeshEvaluation ()=default
MeshEvaluation (const MeshEvaluation &)=delete
MeshEvaluation (MeshEvaluation &&)=delete
MeshEvaluation & operator= (const MeshEvaluation &)=delete
MeshEvaluation & operator= (MeshEvaluation &&)=delete
Additional Inherited Members
Protected Attributes inherited from MeshCore::MeshEvaluation
const MeshKernel & _rclMesh
Detailed Description
The MeshEvalCorruptedFacets class searches for facets with several equal point indices.
See also
MeshFixCorruptedFacets
Author
Werner Mayer
Definition at line 711 of file Degeneration.h.
Constructor & Destructor Documentation
MeshEvalCorruptedFacets()
MeshCore::MeshEvalCorruptedFacets::MeshEvalCorruptedFacets (const MeshKernel & rclM) inline explicit
Construction.
Definition at line 717 of file Degeneration.h.
Member Function Documentation
Evaluate()
bool MeshEvalCorruptedFacets::Evaluate () override virtual
Searches for corrupted facets.
Implements MeshCore::MeshEvaluation.
Definition at line 1175 of file Degeneration.cpp.
References MeshCore::MeshEvaluation::_rclMesh, and MeshCore::MeshKernel::GetFacets().
Referenced by Mesh::MeshObject::hasCorruptedFacets(), and Mesh::MeshObject::validateIndices().
GetIndices()
std::vector< FacetIndex > MeshEvalCorruptedFacets::GetIndices () const
Returns the indices of all corrupt facets.
Definition at line 1189 of file Degeneration.cpp.
References MeshCore::MeshEvaluation::_rclMesh, and MeshCore::MeshKernel::GetFacets().
The documentation for this class was generated from the following files:
Degeneration.h
Degeneration.cpp