FreeCAD: Gui::ViewVolumeProjection Class Reference
Gui::ViewVolumeProjection Class Reference
#include <Utilities.h>
Public Member Functions
ViewVolumeProjection (const SbViewVolume &vv)
~ViewVolumeProjection () override=default
Base::Vector3f operator() (const Base::Vector3f &rclPt) const override
Base::Vector3d operator() (const Base::Vector3d &rclPt) const override
Base::Vector3f inverse (const Base::Vector3f &rclPt) const override
Base::Vector3d inverse (const Base::Vector3d &rclPt) const override
Base::Matrix4D getProjectionMatrix () const override
Public Member Functions inherited from Base::ViewProjMethod
ViewProjMethod (const ViewProjMethod &)=default
ViewProjMethod (ViewProjMethod &&)=default
ViewProjMethod & operator= (const ViewProjMethod &)=default
ViewProjMethod & operator= (ViewProjMethod &&)=default
virtual ~ViewProjMethod ()=default
virtual bool isValid () const
Matrix4D getComposedProjectionMatrix () const
void setTransform (const Base::Matrix4D &)
This method applies an additional transformation to the input points passed with the () operator.
const Base::Matrix4D & getTransform () const
Protected Attributes
SbViewVolume viewVolume
SbMatrix matrix
SbMatrix invert
Additional Inherited Members
Protected Member Functions inherited from Base::ViewProjMethod
ViewProjMethod ()
void transformInput (const Base::Vector3f &, Base::Vector3f &) const
void transformInput (const Base::Vector3d &, Base::Vector3d &) const
Detailed Description
Definition at line 136 of file Gui/Utilities.h.
Constructor & Destructor Documentation
ViewVolumeProjection()
ViewVolumeProjection::ViewVolumeProjection (const SbViewVolume & vv) explicit
Definition at line 40 of file Utilities.cpp.
References invert, matrix, and viewVolume.
~ViewVolumeProjection()
Gui::ViewVolumeProjection::~ViewVolumeProjection () override default
Member Function Documentation
getProjectionMatrix()
Base::Matrix4D ViewVolumeProjection::getProjectionMatrix () const override virtual
Calculate the projection (+ mapping) matrix
Implements Base::ViewProjMethod.
Definition at line 81 of file Utilities.cpp.
References SplineSurface::i, and matrix.
inverse() [1/2]
Base::Vector3d ViewVolumeProjection::inverse (const Base::Vector3d & rclPt) const override virtual
Convert a 2D point on the projection plane in 3D space
Implements Base::ViewProjMethod.
Definition at line 74 of file Utilities.cpp.
References inverse().
inverse() [2/2]
Base::Vector3f ViewVolumeProjection::inverse (const Base::Vector3f & rclPt) const override virtual
Convert a 2D point on the projection plane in 3D space
Implements Base::ViewProjMethod.
Definition at line 67 of file Utilities.cpp.
References SCL.SimpleDataTypes::f, invert, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by inverse().
operator()() [1/2]
Base::Vector3d ViewVolumeProjection::operator() (const Base::Vector3d & rclPt) const override virtual
Convert 3D point to 2D projection plane
Implements Base::ViewProjMethod.
Definition at line 60 of file Utilities.cpp.
References operator()().
operator()() [2/2]
Base::Vector3f ViewVolumeProjection::operator() (const Base::Vector3f & rclPt) const override virtual
Convert 3D point to 2D projection plane
Implements Base::ViewProjMethod.
Definition at line 47 of file Utilities.cpp.
References matrix, and Base::ViewProjMethod::transformInput().
Referenced by operator()().
Member Data Documentation
invert
SbMatrix Gui::ViewVolumeProjection::invert protected
Definition at line 152 of file Gui/Utilities.h.
Referenced by inverse(), and ViewVolumeProjection().
matrix
SbMatrix Gui::ViewVolumeProjection::matrix protected
Definition at line 151 of file Gui/Utilities.h.
Referenced by getProjectionMatrix(), operator()(), and ViewVolumeProjection().
viewVolume
SbViewVolume Gui::ViewVolumeProjection::viewVolume protected
Definition at line 150 of file Gui/Utilities.h.
Referenced by ViewVolumeProjection().
The documentation for this class was generated from the following files:
Gui/Utilities.h
Utilities.cpp