FreeCAD: AppPointsGui.cpp File Reference
AppPointsGui.cpp File Reference
#include "PreCompiled.h"
#include <Base/Console.h>
#include <Base/Interpreter.h>
#include <Base/PyObjectBase.h>
#include <Gui/Application.h>
#include <Gui/Language/Translator.h>
#include <Mod/Points/App/PropertyPointKernel.h>
#include "ViewProvider.h"
#include "Workbench.h"
Classes
class PointsGui::Module
Namespaces
PointsGui
Functions
void CreatePointsCommands ()
void loadPointsResource ()
PyObject * PointsGui::initModule ()
PyMOD_INIT_FUNC (PointsGui)
Function Documentation
CreatePointsCommands()
void CreatePointsCommands ()
Definition at line 543 of file Mod/Points/Gui/Command.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
loadPointsResource()
void loadPointsResource ()
Definition at line 39 of file AppPointsGui.cpp.
References Gui::Translator::instance(), and Gui::Translator::refresh().
Referenced by PyMOD_INIT_FUNC().
PyMOD_INIT_FUNC()
PyMOD_INIT_FUNC (PointsGui)
Definition at line 68 of file AppPointsGui.cpp.
References Gui::ViewProviderBuilder::add(), Base::Console(), CreatePointsCommands(), SCL.SimpleDataTypes::e, Base::Persistence::getClassTypeId(), SIM::Coin3D::Quarter::Quarter::init(), Base::Persistence::init(), Base::BaseClass::init(), PointsGui::initModule(), Gui::Application::Instance, Base::Interpreter(), Base::InterpreterSingleton::loadModule(), loadPointsResource(), Base::ConsoleSingleton::Log(), mod, and PyMOD_Return.