FreeCAD: Part::GeomArcOfConic Class Reference
Part::GeomArcOfConic Class Reference abstract
#include <Geometry.h>
Public Member Functions
~GeomArcOfConic () override
Geometry * copy () const override=0
Base::Vector3d getStartPoint (bool emulateCCWXY) const
GeomArcOfConic::getStartPoint.
Base::Vector3d getEndPoint (bool emulateCCWXY) const
GeomArcOfConic::getEndPoint.
Base::Vector3d getStartPoint () const override
Base::Vector3d getEndPoint () const override
Base::Vector3d getCenter () const
getCenter
Base::Vector3d getLocation () const
void setLocation (const Base::Vector3d &Center)
void setCenter (const Base::Vector3d &Center)
setCenter
Base::Vector3d getAxisDirection () const
virtual void getRange (double &u, double &v, bool emulateCCWXY) const =0
virtual void setRange (double u, double v, bool emulateCCWXY)=0
void getRange (double &u, double &v) const override
void setRange (double u, double v) override
bool isReversed () const
GeomArcOfConic::isReversed.
double getAngleXU () const
GeomArcOfConic::getAngleXU.
void setAngleXU (double angle)
GeomArcOfConic::setAngleXU complements getAngleXU.
Base::Vector3d getXAxisDir () const
GeomArcOfConic::getXAxisDir.
void setXAxisDir (const Base::Vector3d &newdir)
GeomArcOfConic::setXAxisDir Rotates the conic in its plane, so that its symmetry axis is as close as possible to the provided direction.
unsigned int getMemSize () const override=0
PyObject * getPyObject () override=0
const Handle (Geom_Geometry) &handle() const override=0
Public Member Functions inherited from Part::GeomTrimmedCurve
GeomTrimmedCurve ()
GeomTrimmedCurve (const Handle(Geom_TrimmedCurve)&)
~GeomTrimmedCurve () override
GeomCurve * createArc (double first, double last) const override
createArc Generates a curve that is an arc of this curve between given parameters
void Save (Base::Writer &) const override
void Restore (Base::XMLReader &) override
bool isSame (const Geometry &other, double tol, double atol) const override
virtual void setHandle (const Handle(Geom_TrimmedCurve)&)
bool intersectBasisCurves (const GeomTrimmedCurve *c, std::vector< std::pair< Base::Vector3d, Base::Vector3d >> &points, double tol=Precision::Confusion()) const
Public Member Functions inherited from Part::GeomBoundedCurve
GeomBoundedCurve ()
~GeomBoundedCurve () override
Public Member Functions inherited from Part::GeomCurve
GeomCurve ()
~GeomCurve () override
bool isLinear (Base::Vector3d *dir=nullptr, Base::Vector3d *base=nullptr) const
TopoDS_Shape toShape () const override
GeomBSplineCurve * toBSpline (double first, double last) const
toBSpline Converts the curve to a B-spline
virtual GeomBSplineCurve * toNurbs (double first, double last) const
bool tangent (double u, gp_Dir &) const
bool tangent (double u, Base::Vector3d &dir) const
Base::Vector3d pointAtParameter (double u) const
Base::Vector3d firstDerivativeAtParameter (double u) const
Base::Vector3d secondDerivativeAtParameter (double u) const
bool closestParameter (const Base::Vector3d &point, double &u) const
bool closestParameterToBasisCurve (const Base::Vector3d &point, double &u) const
double getFirstParameter () const
double getLastParameter () const
double curvatureAt (double u) const
double length (double u, double v) const
bool normalAt (double u, Base::Vector3d &dir) const
bool normalAt (const Base::Vector3d &curvepoint, Base::Vector3d &dir) const
bool intersect (const GeomCurve *c, std::vector< std::pair< Base::Vector3d, Base::Vector3d >> &points, double tol=Precision::Confusion()) const
void reverse ()
Base::Vector3d value (double u) const
GeomLine * toLine (KeepTag clone=CopyTag) const
GeomLineSegment * toLineSegment (KeepTag clone=CopyTag) const
Public Member Functions inherited from Part::Geometry
~Geometry () override
Geometry * clone () const
boost::uuids::uuid getTag () const
returns the tag of the geometry object
bool hasSameExtensions (const Geometry &other) const
std::vector< std::weak_ptr< const GeometryExtension > > getExtensions () const
bool hasExtension (const Base::Type &type) const
bool hasExtension (const std::string &name) const
std::weak_ptr< const GeometryExtension > getExtension (const Base::Type &type) const
std::weak_ptr< const GeometryExtension > getExtension (const std::string &name) const
std::weak_ptr< GeometryExtension > getExtension (const Base::Type &type)
std::weak_ptr< GeometryExtension > getExtension (const std::string &name)
void setExtension (std::unique_ptr< GeometryExtension > &&geo)
void deleteExtension (const Base::Type &type)
void deleteExtension (const std::string &name)
void mirror (const Base::Vector3d &point) const
void mirror (const Base::Vector3d &point, const Base::Vector3d &dir) const
void rotate (const Base::Placement &plm) const
void scale (const Base::Vector3d &vec, double scale) const
void transform (const Base::Matrix4D &mat) const
void translate (const Base::Vector3d &vec) const
Geometry (const Geometry &)=delete
Geometry & operator= (const Geometry &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Member Functions
GeomArcOfConic ()
Protected Member Functions inherited from Part::GeomTrimmedCurve
Handle (Geom_TrimmedCurve) myCurve
Protected Member Functions inherited from Part::Geometry
void createNewTag ()
create a new tag for the geometry object
void assignTag (const Part::Geometry *)
copies the tag from the geometry passed as a parameter to this object
void copyNonTag (const Part::Geometry *)
Geometry ()
Additional Inherited Members
Static Public Member Functions inherited from Part::GeomCurve
static bool isLinear (const Handle(Geom_Curve) &c, Base::Vector3d *dir=nullptr, Base::Vector3d *base=nullptr)
Static Public Member Functions inherited from Part::Geometry
static std::unique_ptr< Geometry > fromShape (const TopoDS_Shape &s, bool silent=false)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Part::GeomCurve
static bool intersect (const Handle(Geom_Curve)&c, const Handle(Geom_Curve)&c2, std::vector< std::pair< Base::Vector3d, Base::Vector3d >> &points, double tol=Precision::Confusion())
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Part::Geometry
boost::uuids::uuid tag
std::vector< std::shared_ptr< GeometryExtension > > extensions
Detailed Description
Definition at line 490 of file Part/App/Geometry.h.
Constructor & Destructor Documentation
GeomArcOfConic()
GeomArcOfConic::GeomArcOfConic () protected default
~GeomArcOfConic()
GeomArcOfConic::~GeomArcOfConic () override default
Member Function Documentation
copy()
Geometry* Part::GeomArcOfConic::copy () const override pure virtual
returns a copy of this object having a new randomly generated tag. If you also want to copy the tag, you may use clone() instead. For creation of geometry with other handles, with or without the same tag, you may use the constructors and the sethandle functions. The tag of a geometry can be copied to another geometry using the assignTag function.
Reimplemented from Part::GeomTrimmedCurve.
Implemented in Part::GeomArcOfParabola, Part::GeomArcOfHyperbola, Part::GeomArcOfEllipse, and Part::GeomArcOfCircle.
getAngleXU()
double GeomArcOfConic::getAngleXU () const
GeomArcOfConic::getAngleXU.
Returns
The angle between ellipse's major axis (in direction to focus1) and X axis of a default axis system in the plane of ellipse. The angle is counted CCW as seen when looking at the ellipse so that ellipse's axis is pointing at you. Note that this function may give unexpected results when the ellipse is in XY, but reversed, because the X axis of the default axis system is reversed compared to the global X axis. This angle, in conjunction with ellipse's axis, fully defines the orientation of the ellipse.
Definition at line 2516 of file Part/App/Geometry.cpp.
References exportCSG::center(), and Handle().
getAxisDirection()
Base::Vector3d GeomArcOfConic::getAxisDirection () const
Definition at line 2483 of file Part/App/Geometry.cpp.
References Handle().
getCenter()
Base::Vector3d GeomArcOfConic::getCenter () const
getCenter
Deprecated:
use getLocation
Definition at line 2435 of file Part/App/Geometry.cpp.
References Handle().
Referenced by Sketcher::Sketch::addArc(), Sketcher::Sketch::addArcOfEllipse(), Sketcher::Sketch::addArcOfHyperbola(), Sketcher::Sketch::addArcOfParabola(), Sketcher::SketchObject::addCopy(), Sketcher::SketchObject::exposeInternalGeometry(), Sketcher::SketchObject::getPointForGeometry(), SketcherGui::makeTangentToArcOfEllipseviaNewPoint(), SketcherGui::makeTangentToArcOfHyperbolaviaNewPoint(), SketcherGui::EditModeConstraintCoinManager::processConstraints(), and SketcherGui::DrawSketchHandlerLineSet::updateTransitionData().
getEndPoint() [1/2]
Base::Vector3d Part::GeomArcOfConic::getEndPoint () const inline override virtual
Reimplemented from Part::GeomBoundedCurve.
Definition at line 505 of file Part/App/Geometry.h.
References buildPsets::u, and TestSpreadsheet::v.
getEndPoint() [2/2]
Base::Vector3d GeomArcOfConic::getEndPoint (bool emulateCCWXY) const
GeomArcOfConic::getEndPoint.
Parameters
emulateCCWXY if true, the arc will pretent to be a CCW arc in XY plane. For this to work, the arc must lie in XY plane (i.e. Axis is either +Z or -Z).
Returns
Definition at line 2424 of file Part/App/Geometry.cpp.
References Handle(), and isReversed().
Referenced by Sketcher::Sketch::addArc(), Sketcher::Sketch::addArcOfEllipse(), Sketcher::Sketch::addArcOfHyperbola(), Sketcher::Sketch::addArcOfParabola(), and Sketcher::SketchObject::getPointForGeometry().
getLocation()
Base::Vector3d GeomArcOfConic::getLocation () const
Definition at line 2444 of file Part/App/Geometry.cpp.
References Handle().
getMemSize()
unsigned int Part::GeomArcOfConic::getMemSize () const override pure virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Reimplemented from Part::GeomTrimmedCurve.
Implemented in Part::GeomArcOfParabola, Part::GeomArcOfHyperbola, Part::GeomArcOfEllipse, and Part::GeomArcOfCircle.
getPyObject()
PyObject* Part::GeomArcOfConic::getPyObject () override pure virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Part::GeomTrimmedCurve.
Implemented in Part::GeomArcOfParabola, Part::GeomArcOfHyperbola, Part::GeomArcOfEllipse, and Part::GeomArcOfCircle.
getRange() [1/2]
void Part::GeomArcOfConic::getRange (double & u, double & v) const inline override virtual
Reimplemented from Part::GeomTrimmedCurve.
Definition at line 524 of file Part/App/Geometry.h.
getRange() [2/2]
virtual void Part::GeomArcOfConic::getRange (double & u, double & v, bool emulateCCWXY) const pure virtual
Implemented in Part::GeomArcOfParabola, Part::GeomArcOfHyperbola, Part::GeomArcOfEllipse, and Part::GeomArcOfCircle.
getStartPoint() [1/2]
Base::Vector3d Part::GeomArcOfConic::getStartPoint () const inline override virtual
Reimplemented from Part::GeomBoundedCurve.
Definition at line 504 of file Part/App/Geometry.h.
References buildPsets::u, and TestSpreadsheet::v.
getStartPoint() [2/2]
Base::Vector3d GeomArcOfConic::getStartPoint (bool emulateCCWXY) const
GeomArcOfConic::getStartPoint.
Parameters
emulateCCWXY if true, the arc will pretent to be a CCW arc in XY plane. For this to work, the arc must lie in XY plane (i.e. Axis is either +Z or -Z).
Returns
XYZ of the arc's starting point.
Definition at line 2407 of file Part/App/Geometry.cpp.
References Handle(), and isReversed().
Referenced by Sketcher::Sketch::addArc(), Sketcher::Sketch::addArcOfEllipse(), Sketcher::Sketch::addArcOfHyperbola(), Sketcher::Sketch::addArcOfParabola(), Sketcher::SketchObject::addCopy(), Sketcher::SketchObject::getPointForGeometry(), and SketcherGui::DrawSketchHandlerLineSet::updateTransitionData().
getXAxisDir()
Base::Vector3d GeomArcOfConic::getXAxisDir () const
GeomArcOfConic::getXAxisDir.
Returns
the direction vector (unit-length) of symmetry axis of the conic. The direction also points to the focus of a parabola.
Definition at line 2559 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::c, and Handle().
Referenced by SketcherGui::EditModeConstraintCoinManager::processConstraints().
Handle()
const Part::GeomArcOfConic::Handle (Geom_Geometry) const & override pure virtual
Reimplemented from Part::GeomTrimmedCurve.
Implemented in Part::GeomArcOfParabola, Part::GeomArcOfHyperbola, Part::GeomArcOfEllipse, and Part::GeomArcOfCircle.
Referenced by getAngleXU(), getAxisDirection(), getCenter(), getEndPoint(), getLocation(), getStartPoint(), getXAxisDir(), isReversed(), setAngleXU(), setCenter(), setLocation(), and setXAxisDir().
isReversed()
bool GeomArcOfConic::isReversed () const
GeomArcOfConic::isReversed.
Returns
tests if an arc that lies in XY plane is reversed (i.e. drawn from startpoint to endpoint in CW direction instead of CCW.). Returns True if the arc is CW and false if CCW.
Definition at line 2498 of file Part/App/Geometry.cpp.
References Handle().
Referenced by Sketcher::SketchObject::convertToNURBS(), getEndPoint(), Part::GeomArcOfEllipse::getRange(), Part::GeomArcOfHyperbola::getRange(), Part::GeomArcOfParabola::getRange(), getStartPoint(), Sketcher::SketchObject::port_reversedExternalArcs(), Part::GeomArcOfEllipse::setRange(), Part::GeomArcOfHyperbola::setRange(), and Part::GeomArcOfParabola::setRange().
setAngleXU()
void GeomArcOfConic::setAngleXU (double angle)
GeomArcOfConic::setAngleXU complements getAngleXU.
Definition at line 2533 of file Part/App/Geometry.cpp.
References exportCSG::center(), SCL.SimpleDataTypes::e, Handle(), and THROWM.
setCenter()
void GeomArcOfConic::setCenter (const Base::Vector3d & Center)
setCenter
Deprecated:
use setLocation
Definition at line 2453 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::e, Handle(), and THROWM.
Referenced by Sketcher::SketchObject::addCopy().
setLocation()
void GeomArcOfConic::setLocation (const Base::Vector3d & Center)
Definition at line 2468 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::e, Handle(), and THROWM.
setRange() [1/2]
void Part::GeomArcOfConic::setRange (double u, double v) inline override virtual
Reimplemented from Part::GeomTrimmedCurve.
Definition at line 525 of file Part/App/Geometry.h.
setRange() [2/2]
virtual void Part::GeomArcOfConic::setRange (double u, double v, bool emulateCCWXY) pure virtual
Implemented in Part::GeomArcOfParabola, Part::GeomArcOfHyperbola, Part::GeomArcOfEllipse, and Part::GeomArcOfCircle.
setXAxisDir()
void GeomArcOfConic::setXAxisDir (const Base::Vector3d & newdir)
GeomArcOfConic::setXAxisDir Rotates the conic in its plane, so that its symmetry axis is as close as possible to the provided direction.
Parameters
newdir [in] is the new direction. If the vector is small, the orientation of the conic will be preserved. If the vector is not small, but its projection onto plane of the conic is small, an exception will be thrown.
Definition at line 2576 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::c, SCL.SimpleDataTypes::e, Handle(), RobotExample::pos, Base::Vector3< float_type >::Sqr(), THROWM, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
The documentation for this class was generated from the following files:
Part/App/Geometry.h
Part/App/Geometry.cpp