FreeCAD: CommandExtensionDims.cpp File Reference
CommandExtensionDims.cpp File Reference
#include "PreCompiled.h"
#include <QApplication>
#include <QMessageBox>
#include <sstream>
#include <BRepGProp.hxx>
#include <GProp_GProps.hxx>
#include <App/Document.h>
#include <App/DocumentObject.h>
#include <Base/Console.h>
#include <Base/Type.h>
#include <Gui/Action.h>
#include <Gui/Application.h>
#include <Gui/BitmapFactory.h>
#include <Gui/Command.h>
#include <Gui/Control.h>
#include <Gui/MainWindow.h>
#include <Gui/Selection.h>
#include <Gui/SelectionObject.h>
#include <Mod/TechDraw/App/Cosmetic.h>
#include <Mod/TechDraw/App/DrawViewBalloon.h>
#include <Mod/TechDraw/App/DrawViewDimension.h>
#include <Mod/TechDraw/App/DrawPage.h>
#include <Mod/TechDraw/App/DrawUtil.h>
#include <Mod/TechDraw/App/DrawViewPart.h>
#include <Mod/TechDraw/App/Preferences.h>
#include <Mod/TechDraw/App/LineGroup.h>
#include "DlgTemplateField.h"
#include "DrawGuiUtil.h"
#include "TaskCustomizeFormat.h"
#include "TaskSelectLineAttributes.h"
#include "CommandExtensionDims.h"
Classes
struct TechDrawGui::dimVertex
Namespaces
TechDrawGui
Functions
void TechDrawGui::_selectDimensionAttributes (Gui::Command *cmd)
std::vector< TechDraw::DrawViewDimension * > TechDrawGui::_getDimensions (std::vector< Gui::SelectionObject > selection, std::string needDimType)
std::vector< dimVertex > TechDrawGui::_getVertexInfo (TechDraw::DrawViewPart *objFeat, std::vector< std::string > subNames)
TechDraw::DrawViewDimension * TechDrawGui::_createLinDimension (TechDraw::DrawViewPart *objFeat, std::string startVertex, std::string endVertex, std::string dimType)
bool TechDrawGui::_checkSelection (Gui::Command *cmd, std::vector< Gui::SelectionObject > &selection, std::string message)
bool TechDrawGui::_checkSelAndObj (Gui::Command *cmd, std::vector< Gui::SelectionObject > &selection, TechDraw::DrawViewPart *&objFeat, std::string message)
bool TechDrawGui::_checkSelObjAndSubs (Gui::Command *cmd, std::vector< Gui::SelectionObject > &selection, TechDraw::DrawViewPart *&objFeat, std::string message)
void execInsertPrefixChar (Gui::Command *cmd, std::string prefixFormat, const QAction *action=nullptr)
void execRemovePrefixChar (Gui::Command *cmd)
void execIncreaseDecreaseDecimal (Gui::Command *cmd, int delta)
void execPosHorizChainDimension (Gui::Command *cmd)
void execPosVertChainDimension (Gui::Command *cmd)
void execPosObliqueChainDimension (Gui::Command *cmd)
void execCascadeHorizDimension (Gui::Command *cmd)
void execCascadeVertDimension (Gui::Command *cmd)
void execCascadeObliqueDimension (Gui::Command *cmd)
void execCreateHorizChainDimension (Gui::Command *cmd)
void execCreateVertChainDimension (Gui::Command *cmd)
void execCreateObliqueChainDimension (Gui::Command *cmd)
void execCreateHorizCoordDimension (Gui::Command *cmd)
void execCreateVertCoordDimension (Gui::Command *cmd)
void execCreateObliqueCoordDimension (Gui::Command *cmd)
void execCreateHorizChamferDimension (Gui::Command *cmd)
void execCreateVertChamferDimension (Gui::Command *cmd)
void CreateTechDrawCommandsExtensionDims ()
Variables
struct {
} TechDrawGui::sortX
struct {
} TechDrawGui::sortY
Function Documentation
CreateTechDrawCommandsExtensionDims()
void CreateTechDrawCommandsExtensionDims ()
Definition at line 2536 of file CommandExtensionDims.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
execCascadeHorizDimension()
void execCascadeHorizDimension (Gui::Command * cmd)
Definition at line 939 of file CommandExtensionDims.cpp.
References _checkSelection(), TechDrawGui::_getDimensions(), activeDimAttributes, Gui::Command::commitCommand(), TechDraw::pointPair::first(), dimAttributes::getCascadeSpacing(), Gui::getMainWindow(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, TechDraw::pointPair::second(), Path.Dressup.Utils::selection(), Path.Log::warning(), and Base::Vector3< float_type >::x.
execCascadeObliqueDimension()
void execCascadeObliqueDimension (Gui::Command * cmd)
Definition at line 1072 of file CommandExtensionDims.cpp.
References _checkSelection(), TechDrawGui::_getDimensions(), activeDimAttributes, Gui::Command::commitCommand(), TechDraw::pointPair::first(), dimAttributes::getCascadeSpacing(), Gui::getMainWindow(), SplineSurface::i, Base::Vector3< float_type >::Normalize(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, TechDraw::pointPair::second(), Path.Dressup.Utils::selection(), Path.Log::warning(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
execCascadeVertDimension()
void execCascadeVertDimension (Gui::Command * cmd)
Definition at line 1005 of file CommandExtensionDims.cpp.
References _checkSelection(), TechDrawGui::_getDimensions(), activeDimAttributes, Gui::Command::commitCommand(), TechDraw::pointPair::first(), dimAttributes::getCascadeSpacing(), Gui::getMainWindow(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, TechDraw::pointPair::second(), Path.Dressup.Utils::selection(), Path.Log::warning(), and Base::Vector3< float_type >::y.
execCreateHorizChainDimension()
void execCreateHorizChainDimension (Gui::Command * cmd)
Definition at line 1270 of file CommandExtensionDims.cpp.
References TechDrawGui::_checkSelObjAndSubs(), TechDrawGui::_createLinDimension(), TechDrawGui::_getVertexInfo(), Gui::SelectionSingleton::clearSelection(), Gui::Command::commitCommand(), TechDraw::pointPair::first(), TechDraw::DrawViewDimension::getLinearPoints(), Gui::Command::getSelection(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, TechDraw::CosmeticExtension::refreshCEGeoms(), TechDraw::DrawView::requestPaint(), TechDraw::pointPair::second(), Path.Dressup.Utils::selection(), App::PropertyQuantity::setValue(), TechDrawGui::sortX, TechDraw::DrawView::X, and TechDraw::DrawView::Y.
execCreateHorizChamferDimension()
void execCreateHorizChamferDimension (Gui::Command * cmd)
Definition at line 2040 of file CommandExtensionDims.cpp.
References TechDrawGui::_checkSelObjAndSubs(), TechDrawGui::_createLinDimension(), TechDrawGui::_getVertexInfo(), KDL::abs(), KDL::atan(), Gui::SelectionSingleton::clearSelection(), Gui::Command::commitCommand(), TechDraw::pointPair::first(), TechDraw::DrawViewDimension::FormatSpec, TechDraw::DrawViewDimension::getLinearPoints(), Gui::Command::getSelection(), App::PropertyString::getStrValue(), M_PI, KDL::max(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, TechDraw::DrawView::requestPaint(), TechDraw::pointPair::second(), Path.Dressup.Utils::selection(), App::PropertyQuantity::setValue(), App::PropertyString::setValue(), TechDraw::DrawView::X, TechDraw::DrawView::Y, and yMax.
execCreateHorizCoordDimension()
void execCreateHorizCoordDimension (Gui::Command * cmd)
Definition at line 1641 of file CommandExtensionDims.cpp.
References TechDrawGui::_checkSelObjAndSubs(), TechDrawGui::_createLinDimension(), TechDrawGui::_getVertexInfo(), activeDimAttributes, Gui::SelectionSingleton::clearSelection(), Gui::Command::commitCommand(), TechDraw::pointPair::first(), dimAttributes::getCascadeSpacing(), TechDraw::DrawViewDimension::getLinearPoints(), Gui::Command::getSelection(), Gui::Command::openCommand(), TechDrawGui::dimVertex::point, Arch::QT_TRANSLATE_NOOP, TechDraw::CosmeticExtension::refreshCEGeoms(), TechDraw::DrawView::requestPaint(), TechDraw::pointPair::second(), Path.Dressup.Utils::selection(), App::PropertyQuantity::setValue(), TechDrawGui::sortX, TechDraw::DrawView::X, Base::Vector3< float_type >::x, and TechDraw::DrawView::Y.
execCreateObliqueChainDimension()
void execCreateObliqueChainDimension (Gui::Command * cmd)
Definition at line 1402 of file CommandExtensionDims.cpp.
References TechDrawGui::_checkSelObjAndSubs(), Gui::Command::abortCommand(), Gui::SelectionSingleton::clearSelection(), Gui::Command::commitCommand(), Gui::Command::getSelection(), TechDrawGui::makeObliqueChainDimension(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, TechDraw::CosmeticExtension::refreshCEGeoms(), TechDraw::DrawView::requestPaint(), and Path.Dressup.Utils::selection().
execCreateObliqueCoordDimension()
void execCreateObliqueCoordDimension (Gui::Command * cmd)
Definition at line 1787 of file CommandExtensionDims.cpp.
References TechDrawGui::_checkSelObjAndSubs(), Gui::Command::abortCommand(), Gui::SelectionSingleton::clearSelection(), Gui::Command::commitCommand(), Gui::Command::getSelection(), TechDrawGui::makeObliqueCoordDimension(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, and Path.Dressup.Utils::selection().
execCreateVertChainDimension()
void execCreateVertChainDimension (Gui::Command * cmd)
Definition at line 1336 of file CommandExtensionDims.cpp.
References TechDrawGui::_checkSelObjAndSubs(), TechDrawGui::_createLinDimension(), TechDrawGui::_getVertexInfo(), Gui::SelectionSingleton::clearSelection(), Gui::Command::commitCommand(), TechDraw::pointPair::first(), TechDraw::DrawViewDimension::getLinearPoints(), Gui::Command::getSelection(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, TechDraw::CosmeticExtension::refreshCEGeoms(), TechDraw::DrawView::requestPaint(), TechDraw::pointPair::second(), Path.Dressup.Utils::selection(), App::PropertyQuantity::setValue(), TechDrawGui::sortY, TechDraw::DrawView::X, and TechDraw::DrawView::Y.
execCreateVertChamferDimension()
void execCreateVertChamferDimension (Gui::Command * cmd)
Definition at line 2109 of file CommandExtensionDims.cpp.
References TechDrawGui::_checkSelObjAndSubs(), TechDrawGui::_createLinDimension(), TechDrawGui::_getVertexInfo(), KDL::abs(), KDL::atan(), Gui::SelectionSingleton::clearSelection(), Gui::Command::commitCommand(), TechDraw::pointPair::first(), TechDraw::DrawViewDimension::FormatSpec, TechDraw::DrawViewDimension::getLinearPoints(), Gui::Command::getSelection(), App::PropertyString::getStrValue(), M_PI, KDL::max(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, TechDraw::DrawView::requestPaint(), TechDraw::pointPair::second(), Path.Dressup.Utils::selection(), App::PropertyQuantity::setValue(), App::PropertyString::setValue(), TechDraw::DrawView::X, xMax, and TechDraw::DrawView::Y.
execCreateVertCoordDimension()
void execCreateVertCoordDimension (Gui::Command * cmd)
Definition at line 1714 of file CommandExtensionDims.cpp.
References TechDrawGui::_checkSelObjAndSubs(), TechDrawGui::_createLinDimension(), TechDrawGui::_getVertexInfo(), activeDimAttributes, Gui::SelectionSingleton::clearSelection(), Gui::Command::commitCommand(), TechDraw::pointPair::first(), dimAttributes::getCascadeSpacing(), TechDraw::DrawViewDimension::getLinearPoints(), Gui::Command::getSelection(), Gui::Command::openCommand(), TechDrawGui::dimVertex::point, Arch::QT_TRANSLATE_NOOP, TechDraw::CosmeticExtension::refreshCEGeoms(), TechDraw::DrawView::requestPaint(), TechDraw::pointPair::second(), Path.Dressup.Utils::selection(), App::PropertyQuantity::setValue(), TechDrawGui::sortY, TechDraw::DrawView::X, TechDraw::DrawView::Y, and Base::Vector3< float_type >::y.
execIncreaseDecreaseDecimal()
void execIncreaseDecreaseDecimal (Gui::Command * cmd, int delta)
Definition at line 435 of file CommandExtensionDims.cpp.
References _checkSelection(), Gui::Command::commitCommand(), TechDraw::DrawViewDimension::FormatSpec, Base::Persistence::getClassTypeId(), App::PropertyString::getStrValue(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, and Path.Dressup.Utils::selection().
execInsertPrefixChar()
void execInsertPrefixChar (Gui::Command * cmd, std::string prefixFormat, const QAction * action = nullptr)
Definition at line 107 of file CommandExtensionDims.cpp.
References TechDrawGui::_checkSelection(), Path.Post.scripts.dynapath_4060_post::action, Gui::Command::commitCommand(), TechDraw::DrawViewDimension::FormatSpec, Base::Persistence::getClassTypeId(), TechDrawGui::DlgTemplateField::getFieldContent(), App::PropertyString::getStrValue(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, Path.Dressup.Utils::selection(), TechDrawGui::DlgTemplateField::setFieldContent(), TechDrawGui::DlgTemplateField::setFieldLength(), and TechDrawGui::DlgTemplateField::setFieldName().
execPosHorizChainDimension()
void execPosHorizChainDimension (Gui::Command * cmd)
Definition at line 630 of file CommandExtensionDims.cpp.
References _checkSelection(), TechDrawGui::_getDimensions(), Gui::Command::commitCommand(), TechDraw::pointPair::first(), Gui::getMainWindow(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, TechDraw::pointPair::second(), Path.Dressup.Utils::selection(), Path.Log::warning(), and Base::Vector3< float_type >::x.
execPosObliqueChainDimension()
void execPosObliqueChainDimension (Gui::Command * cmd)
Definition at line 753 of file CommandExtensionDims.cpp.
References _checkSelection(), TechDrawGui::_getDimensions(), Gui::Command::commitCommand(), TechDraw::pointPair::first(), Gui::getMainWindow(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, TechDraw::pointPair::second(), Path.Dressup.Utils::selection(), Path.Log::warning(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
execPosVertChainDimension()
void execPosVertChainDimension (Gui::Command * cmd)
Definition at line 691 of file CommandExtensionDims.cpp.
References _checkSelection(), TechDrawGui::_getDimensions(), Gui::Command::commitCommand(), TechDraw::pointPair::first(), Gui::getMainWindow(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, TechDraw::pointPair::second(), Path.Dressup.Utils::selection(), Path.Log::warning(), and Base::Vector3< float_type >::y.
execRemovePrefixChar()
void execRemovePrefixChar (Gui::Command * cmd)
Definition at line 249 of file CommandExtensionDims.cpp.
References _checkSelection(), Gui::Command::commitCommand(), TechDraw::DrawViewDimension::FormatSpec, Base::Persistence::getClassTypeId(), App::PropertyString::getStrValue(), Gui::Command::openCommand(), RobotExample::pos, Arch::QT_TRANSLATE_NOOP, and Path.Dressup.Utils::selection().