FreeCAD: Gui::ViewProviderExtension Class Reference
Gui::ViewProviderExtension Class Reference
Extension with special viewprovider calls.
#include <ViewProviderExtension.h>
Public Member Functions
ViewProviderExtension ()
~ViewProviderExtension () override
Gui::ViewProviderDocumentObject * getExtendedViewProvider ()
const Gui::ViewProviderDocumentObject * getExtendedViewProvider () const
virtual std::vector< App::DocumentObject * > extensionClaimChildren3D () const
virtual bool extensionOnDelete (const std::vector< std::string > &)
virtual void extensionBeforeDelete ()
virtual std::vector< App::DocumentObject * > extensionClaimChildren () const
virtual bool extensionCanDragObjects () const
virtual bool extensionCanDragObject (App::DocumentObject *) const
virtual void extensionDragObject (App::DocumentObject *)
virtual bool extensionCanDropObjects () const
virtual bool extensionCanDropObject (App::DocumentObject *) const
virtual bool extensionCanDragAndDropObject (App::DocumentObject *) const
virtual void extensionDropObject (App::DocumentObject *)
virtual bool extensionCanDropObjectEx (App::DocumentObject *, App::DocumentObject *, const char *, const std::vector< std::string > &) const
virtual std::string extensionDropObjectEx (App::DocumentObject *obj, App::DocumentObject *, const char *, const std::vector< std::string > &)
virtual int extensionReplaceObject (App::DocumentObject *, App::DocumentObject *)
virtual void extensionHide ()
Hides the view provider.
virtual void extensionShow ()
Shows the view provider.
virtual void extensionModeSwitchChange ()
virtual SoSeparator * extensionGetFrontRoot () const
virtual SoGroup * extensionGetChildRoot () const
virtual SoSeparator * extensionGetBackRoot () const
virtual void extensionAttach (App::DocumentObject *)
virtual void extensionReattach (App::DocumentObject *)
virtual void extensionSetDisplayMode (const char *)
virtual std::vector< std::string > extensionGetDisplayModes () const
virtual void extensionSetupContextMenu (QMenu *, QObject *, const char *)
virtual void extensionUpdateData (const App::Property *)
PyObject * getExtensionPyObject () override
void setIgnoreOverlayIcon (bool on)
bool ignoreOverlayIcon () const
virtual QIcon extensionMergeGreyableOverlayIcons (const QIcon &orig) const
virtual QIcon extensionMergeColorfullOverlayIcons (const QIcon &orig) const
virtual void extensionStartRestoring ()
virtual void extensionFinishRestoring ()
virtual bool extensionGetElementPicked (const SoPickedPoint *, std::string &) const
virtual bool extensionGetDetailPath (const char *, SoFullPath *, SoDetail *&) const
Public Member Functions inherited from App::Extension
virtual Base::Type getExtensionTypeId (void) const
Extension ()=default
virtual ~Extension ()
virtual void initExtension (App::ExtensionContainer *obj)
App::ExtensionContainer * getExtendedContainer ()
const App::ExtensionContainer * getExtendedContainer () const
std::string name () const
bool isPythonExtension ()
virtual Property * extensionGetPropertyByName (const char *name) const
find a property by its name
virtual const char * extensionGetPropertyName (const Property *prop) const
get the name of a property
virtual void extensionGetPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual void extensionGetPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual short extensionGetPropertyType (const Property *prop) const
get the Type of a Property
virtual short extensionGetPropertyType (const char *name) const
get the Type of a named Property
virtual const char * extensionGetPropertyGroup (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * extensionGetPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual void extensionSave (Base::Writer &) const
virtual void extensionRestore (Base::XMLReader &)
bool extensionIsDerivedFrom (const Base::Type type) const
Additional Inherited Members
Static Public Member Functions inherited from App::Extension
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Protected Member Functions inherited from App::Extension
virtual const App::PropertyData & extensionGetPropertyData (void) const
virtual void extensionOnChanged (const Property *p)
virtual bool extensionHandleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
returns true if the property name change was handled by the extension.
virtual bool extensionHandleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop)
returns true if the property type change was handled by the extension.
void initExtensionType (Base::Type type)
Static Protected Member Functions inherited from App::Extension
static const App::PropertyData * extensionGetPropertyDataPtr (void)
static void initExtensionSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Base::Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Extension
bool m_isPythonExtension = false
Py::SmartPtr ExtensionPythonObject
Detailed Description
Extension with special viewprovider calls.
Definition at line 49 of file ViewProviderExtension.h.
Constructor & Destructor Documentation
ViewProviderExtension()
ViewProviderExtension::ViewProviderExtension ()
Definition at line 40 of file ViewProviderExtension.cpp.
References App::Extension::getExtensionClassTypeId().
~ViewProviderExtension()
ViewProviderExtension::~ViewProviderExtension () override default
Member Function Documentation
extensionAttach()
virtual void Gui::ViewProviderExtension::extensionAttach (App::DocumentObject *) inline virtual
Reimplemented in Gui::ViewProviderGeoFeatureGroupExtension.
Definition at line 100 of file ViewProviderExtension.h.
Referenced by Gui::ViewProviderGeoFeatureGroupExtension::extensionAttach().
extensionBeforeDelete()
virtual void Gui::ViewProviderExtension::extensionBeforeDelete () inline virtual
Reimplemented in Gui::ViewProviderLinkObserver.
Definition at line 68 of file ViewProviderExtension.h.
extensionCanDragAndDropObject()
virtual bool Gui::ViewProviderExtension::extensionCanDragAndDropObject (App::DocumentObject *) const inline virtual
Definition at line 78 of file ViewProviderExtension.h.
extensionCanDragObject()
virtual bool Gui::ViewProviderExtension::extensionCanDragObject (App::DocumentObject *) const inline virtual
Reimplemented in TechDrawGui::ViewProviderTemplateExtension, Gui::ViewProviderGroupExtension, TechDrawGui::ViewProviderDrawingViewExtension, TechDrawGui::ViewProviderPageExtension, and Gui::ViewProviderLinkObserver.
Definition at line 74 of file ViewProviderExtension.h.
extensionCanDragObjects()
virtual bool Gui::ViewProviderExtension::extensionCanDragObjects () const inline virtual
Reimplemented in Gui::ViewProviderGroupExtension, TechDrawGui::ViewProviderDrawingViewExtension, TechDrawGui::ViewProviderPageExtension, and TechDrawGui::ViewProviderTemplateExtension.
Definition at line 73 of file ViewProviderExtension.h.
extensionCanDropObject()
virtual bool Gui::ViewProviderExtension::extensionCanDropObject (App::DocumentObject *) const inline virtual
Reimplemented in TechDrawGui::ViewProviderTemplateExtension, Gui::ViewProviderGroupExtension, TechDrawGui::ViewProviderDrawingViewExtension, TechDrawGui::ViewProviderPageExtension, and Gui::ViewProviderLinkObserver.
Definition at line 77 of file ViewProviderExtension.h.
extensionCanDropObjectEx()
virtual bool Gui::ViewProviderExtension::extensionCanDropObjectEx (App::DocumentObject * , App::DocumentObject * , const char * , const std::vector< std::string > &) const inline virtual
Reimplemented in TechDrawGui::ViewProviderPageExtension.
Definition at line 80 of file ViewProviderExtension.h.
extensionCanDropObjects()
virtual bool Gui::ViewProviderExtension::extensionCanDropObjects () const inline virtual
Reimplemented in Gui::ViewProviderGroupExtension, TechDrawGui::ViewProviderDrawingViewExtension, TechDrawGui::ViewProviderPageExtension, and TechDrawGui::ViewProviderTemplateExtension.
Definition at line 76 of file ViewProviderExtension.h.
extensionClaimChildren()
virtual std::vector<App::DocumentObject*> Gui::ViewProviderExtension::extensionClaimChildren () const inline virtual
Reimplemented in Gui::ViewProviderGeoFeatureGroupExtension, Gui::ViewProviderOriginGroupExtension, and Gui::ViewProviderGroupExtension.
Definition at line 70 of file ViewProviderExtension.h.
extensionClaimChildren3D()
virtual std::vector<App::DocumentObject*> Gui::ViewProviderExtension::extensionClaimChildren3D () const inline virtual
Reimplemented in Gui::ViewProviderGeoFeatureGroupExtension, and Gui::ViewProviderOriginGroupExtension.
Definition at line 64 of file ViewProviderExtension.h.
extensionDragObject()
virtual void Gui::ViewProviderExtension::extensionDragObject (App::DocumentObject *) inline virtual
Reimplemented in Gui::ViewProviderGroupExtension, TechDrawGui::ViewProviderDrawingViewExtension, and TechDrawGui::ViewProviderPageExtension.
Definition at line 75 of file ViewProviderExtension.h.
extensionDropObject()
virtual void Gui::ViewProviderExtension::extensionDropObject (App::DocumentObject *) inline virtual
Reimplemented in Gui::ViewProviderGroupExtension, TechDrawGui::ViewProviderPageExtension, and TechDrawGui::ViewProviderDrawingViewExtension.
Definition at line 79 of file ViewProviderExtension.h.
extensionDropObjectEx()
virtual std::string Gui::ViewProviderExtension::extensionDropObjectEx (App::DocumentObject * obj, App::DocumentObject * , const char * , const std::vector< std::string > &) inline virtual
Definition at line 83 of file ViewProviderExtension.h.
extensionFinishRestoring()
virtual void Gui::ViewProviderExtension::extensionFinishRestoring () inline virtual
Reimplemented in Gui::ViewProviderGeoFeatureGroupExtension, and Gui::ViewProviderLinkObserver.
Definition at line 120 of file ViewProviderExtension.h.
Referenced by Gui::ViewProviderGeoFeatureGroupExtension::extensionFinishRestoring().
extensionGetBackRoot()
virtual SoSeparator* Gui::ViewProviderExtension::extensionGetBackRoot () const inline virtual
Reimplemented in Gui::ViewProviderGeoFeatureGroupExtension.
Definition at line 99 of file ViewProviderExtension.h.
extensionGetChildRoot()
virtual SoGroup* Gui::ViewProviderExtension::extensionGetChildRoot () const inline virtual
Reimplemented in Gui::ViewProviderGeoFeatureGroupExtension.
Definition at line 98 of file ViewProviderExtension.h.
extensionGetDetailPath()
virtual bool Gui::ViewProviderExtension::extensionGetDetailPath (const char * , SoFullPath * , SoDetail *&) const inline virtual
Definition at line 123 of file ViewProviderExtension.h.
extensionGetDisplayModes()
virtual std::vector<std::string> Gui::ViewProviderExtension::extensionGetDisplayModes () const inline virtual
Reimplemented in Gui::ViewProviderGeoFeatureGroupExtension.
Definition at line 103 of file ViewProviderExtension.h.
Referenced by Gui::ViewProviderGeoFeatureGroupExtension::extensionGetDisplayModes().
extensionGetElementPicked()
virtual bool Gui::ViewProviderExtension::extensionGetElementPicked (const SoPickedPoint * , std::string &) const inline virtual
Definition at line 122 of file ViewProviderExtension.h.
extensionGetFrontRoot()
virtual SoSeparator* Gui::ViewProviderExtension::extensionGetFrontRoot () const inline virtual
Reimplemented in Gui::ViewProviderGeoFeatureGroupExtension.
Definition at line 97 of file ViewProviderExtension.h.
extensionHide()
virtual void Gui::ViewProviderExtension::extensionHide () inline virtual
Hides the view provider.
Reimplemented in Gui::ViewProviderGeoFeatureGroupExtension, and Gui::ViewProviderGroupExtension.
Definition at line 91 of file ViewProviderExtension.h.
Referenced by Gui::ViewProviderGroupExtension::extensionHide().
extensionMergeColorfullOverlayIcons()
virtual QIcon Gui::ViewProviderExtension::extensionMergeColorfullOverlayIcons (const QIcon & orig) const inline virtual
Reimplemented in Gui::ViewProviderSuppressibleExtension, and PartGui::ViewProviderAttachExtension.
Definition at line 117 of file ViewProviderExtension.h.
Referenced by Gui::ViewProviderSuppressibleExtension::extensionMergeColorfullOverlayIcons().
extensionMergeGreyableOverlayIcons()
virtual QIcon Gui::ViewProviderExtension::extensionMergeGreyableOverlayIcons (const QIcon & orig) const inline virtual
Reimplemented in TechDrawGui::ViewProviderCosmeticExtension.
Definition at line 116 of file ViewProviderExtension.h.
extensionModeSwitchChange()
virtual void Gui::ViewProviderExtension::extensionModeSwitchChange () inline virtual
Reimplemented in Gui::ViewProviderLinkObserver.
Definition at line 95 of file ViewProviderExtension.h.
extensionOnDelete()
virtual bool Gui::ViewProviderExtension::extensionOnDelete (const std::vector< std::string > &) inline virtual
Reimplemented in Gui::ViewProviderGroupExtension.
Definition at line 67 of file ViewProviderExtension.h.
extensionReattach()
virtual void Gui::ViewProviderExtension::extensionReattach (App::DocumentObject *) inline virtual
Reimplemented in Gui::ViewProviderLinkObserver.
Definition at line 101 of file ViewProviderExtension.h.
extensionReplaceObject()
virtual int Gui::ViewProviderExtension::extensionReplaceObject (App::DocumentObject * , App::DocumentObject *) inline virtual
Definition at line 87 of file ViewProviderExtension.h.
extensionSetDisplayMode()
virtual void Gui::ViewProviderExtension::extensionSetDisplayMode (const char *) inline virtual
Reimplemented in Gui::ViewProviderGeoFeatureGroupExtension.
Definition at line 102 of file ViewProviderExtension.h.
Referenced by Gui::ViewProviderGeoFeatureGroupExtension::extensionSetDisplayMode().
extensionSetupContextMenu()
virtual void Gui::ViewProviderExtension::extensionSetupContextMenu (QMenu * , QObject * , const char *) inline virtual
Reimplemented in Gui::ViewProviderSuppressibleExtension, PartGui::ViewProviderAttachExtension, and PartGui::ViewProviderSplineExtension.
Definition at line 104 of file ViewProviderExtension.h.
extensionShow()
virtual void Gui::ViewProviderExtension::extensionShow () inline virtual
Shows the view provider.
Reimplemented in Gui::ViewProviderGeoFeatureGroupExtension, and Gui::ViewProviderGroupExtension.
Definition at line 93 of file ViewProviderExtension.h.
Referenced by Gui::ViewProviderGroupExtension::extensionShow().
extensionStartRestoring()
virtual void Gui::ViewProviderExtension::extensionStartRestoring () inline virtual
Definition at line 119 of file ViewProviderExtension.h.
extensionUpdateData()
void ViewProviderExtension::extensionUpdateData (const App::Property *) virtual
Reimplemented in Gui::ViewProviderSuppressibleExtension, Gui::ViewProviderGeoFeatureGroupExtension, PartGui::ViewProviderAttachExtension, PartGui::ViewProviderSplineExtension, PartGui::ViewProviderGridExtension, and Gui::ViewProviderLinkObserver.
Definition at line 59 of file ViewProviderExtension.cpp.
Referenced by PartGui::ViewProviderSplineExtension::extensionUpdateData(), and Gui::ViewProviderGeoFeatureGroupExtension::extensionUpdateData().
getExtendedViewProvider() [1/2]
ViewProviderDocumentObject * ViewProviderExtension::getExtendedViewProvider ()
Definition at line 47 of file ViewProviderExtension.cpp.
References Base::Persistence::getClassTypeId(), and App::Extension::getExtendedContainer().
Referenced by Gui::ViewProviderGeoFeatureGroupExtension::extensionAttach(), Gui::ViewProviderGroupExtension::extensionCanDropObject(), Gui::ViewProviderGroupExtension::extensionClaimChildren(), Gui::ViewProviderGeoFeatureGroupExtension::extensionClaimChildren(), Gui::ViewProviderGeoFeatureGroupExtension::extensionClaimChildren3D(), Gui::ViewProviderGroupExtension::extensionDragObject(), Gui::ViewProviderGroupExtension::extensionDropObject(), Gui::ViewProviderGroupExtension::extensionHide(), PartGui::ViewProviderAttachExtension::extensionMergeColorfullOverlayIcons(), PartGui::ViewProviderSplineExtension::extensionOnChanged(), Gui::ViewProviderGroupExtension::extensionOnDelete(), Gui::ViewProviderGeoFeatureGroupExtension::extensionSetDisplayMode(), Gui::ViewProviderSuppressibleExtension::extensionSetupContextMenu(), PartGui::ViewProviderAttachExtension::extensionSetupContextMenu(), Gui::ViewProviderGroupExtension::extensionShow(), Gui::ViewProviderSuppressibleExtension::extensionUpdateData(), PartGui::ViewProviderAttachExtension::extensionUpdateData(), Gui::ViewProviderGeoFeatureGroupExtension::extensionUpdateData(), TechDrawGui::ViewProviderDrawingViewExtension::getViewProviderDrawingView(), TechDrawGui::ViewProviderPageExtension::getViewProviderPage(), TechDrawGui::ViewProviderTemplateExtension::getViewProviderTemplate(), Gui::ViewProviderSuppressibleExtension::setSuppressedIcon(), PartGui::ViewProviderAttachExtension::showAttachmentEditor(), and PartGui::ViewProviderSplineExtension::showControlPoints().
getExtendedViewProvider() [2/2]
const Gui::ViewProviderDocumentObject* Gui::ViewProviderExtension::getExtendedViewProvider () const
getExtensionPyObject()
PyObject * ViewProviderExtension::getExtensionPyObject () override virtual
Reimplemented from App::Extension.
Definition at line 63 of file ViewProviderExtension.cpp.
References create_qrc::ext, App::Extension::ExtensionPythonObject, Py::SmartPtr::is(), and Py::new_reference_to().
ignoreOverlayIcon()
bool Gui::ViewProviderExtension::ignoreOverlayIcon () const inline
Definition at line 113 of file ViewProviderExtension.h.
setIgnoreOverlayIcon()
void Gui::ViewProviderExtension::setIgnoreOverlayIcon (bool on) inline
Definition at line 110 of file ViewProviderExtension.h.
The documentation for this class was generated from the following files:
ViewProviderExtension.h
ViewProviderExtension.cpp