FreeCAD: Fem::FemMesh Class Reference
Fem::FemMesh Class Reference
#include <FemMesh.h>
Classes
struct FemMeshInfo
Public Member Functions
FemMesh ()
FemMesh (const FemMesh &)
~FemMesh () override
FemMesh & operator= (const FemMesh &)
const SMESH_Mesh * getSMesh () const
SMESH_Mesh * getSMesh ()
void addHypothesis (const TopoDS_Shape &aSubShape, SMESH_HypothesisPtr hyp)
void setStandardHypotheses ()
template<typename T >
SMESH_HypothesisPtr createHypothesis (int hypId)
void compute ()
unsigned int getMemSize () const override
void Save (Base::Writer &) const override
void Restore (Base::XMLReader &) override
void SaveDocFile (Base::Writer &writer) const override
void RestoreDocFile (Base::Reader &reader) override
Subelement management
std::vector< const char * > getElementTypes () const override
unsigned long countSubElements (const char *Type) const override
Data::Segment * getSubElement (const char *Type, unsigned long) const override
get the subelement by type and number
void getPoints (std::vector< Base::Vector3d > &Points, std::vector< Base::Vector3d > &Normals, double Accuracy, uint16_t flags=0) const override
search and retrieval
std::set< long > getSurfaceNodes (long ElemId, short FaceId, float Angle=360) const
retrieving by region growing
std::set< int > getNodesBySolid (const TopoDS_Solid &solid) const
retrieving by solid
std::set< int > getNodesByFace (const TopoDS_Face &face) const
retrieving by face
std::set< int > getNodesByEdge (const TopoDS_Edge &edge) const
retrieving by edge
std::set< int > getNodesByVertex (const TopoDS_Vertex &vertex) const
retrieving by vertex
std::list< int > getElementNodes (int id) const
retrieving node IDs by element ID
std::list< int > getNodeElements (int id, SMDSAbs_ElementType type=SMDSAbs_All) const
retrieving elements IDs by node ID
std::list< int > getFacesByFace (const TopoDS_Face &face) const
retrieving face IDs number by face
std::list< int > getEdgesByEdge (const TopoDS_Edge &edge) const
retrieving edge IDs number by edge
std::list< std::pair< int, int > > getVolumesByFace (const TopoDS_Face &face) const
retrieving volume IDs and face IDs number by face
std::map< int, int > getccxVolumesByFace (const TopoDS_Face &face) const
retrieving volume IDs and CalculiX face number by face
std::set< int > getEdgesOnly () const
retrieving IDs of edges not belonging to any face (and thus not belonging to any volume too)
std::set< int > getFacesOnly () const
retrieving IDs of faces not belonging to any volume
Placement control
void setTransform (const Base::Matrix4D &rclTrf) override
set the transformation
Base::Matrix4D getTransform () const override
get the transformation
Base::BoundBox3d getBoundBox () const override
Bound box from the shape.
Base::Quantity getVolume () const
get the volume (when there are volume elements)
Modification
void transformGeometry (const Base::Matrix4D &rclMat) override
Applies a transformation on the real geometric data type.
Public Member Functions inherited from Data::ComplexGeoData
ComplexGeoData ()
Constructor.
~ComplexGeoData () override=default
Destructor.
void applyTransform (const Base::Matrix4D &rclTrf)
void applyTranslation (const Base::Vector3d &)
void applyRotation (const Base::Rotation &)
void setPlacement (const Base::Placement &rclPlacement)
Base::Placement getPlacement () const
virtual Segment * getSubElementByName (const char *Name) const
get sub-element by combined name
virtual void getLinesFromSubElement (const Segment *, std::vector< Base::Vector3d > &Points, std::vector< Line > &lines) const
virtual void getFacesFromSubElement (const Segment *, std::vector< Base::Vector3d > &Points, std::vector< Base::Vector3d > &PointNormals, std::vector< Facet > &faces) const
virtual double getAccuracy () const
Get the standard accuracy to be used with getPoints, getLines or getFaces.
virtual Base::Vector3d getPointFromLineIntersection (const Base::Vector3f &base, const Base::Vector3f &dir) const
virtual void getLines (std::vector< Base::Vector3d > &Points, std::vector< Line > &lines, double Accuracy, uint16_t flags=0) const
virtual void getFaces (std::vector< Base::Vector3d > &Points, std::vector< Facet > &faces, double Accuracy, uint16_t flags=0) const
virtual bool getCenterOfGravity (Base::Vector3d &center) const
virtual std::optional< Base::Vector3d > centerOfGravity () const
IndexedName getIndexedName (const MappedName &name, ElementIDRefs *sid=nullptr) const
MappedName getMappedName (const IndexedName &element, bool allowUnmapped=false, ElementIDRefs *sid=nullptr) const
MappedElement getElementName (const char *name, ElementIDRefs *sid=nullptr, bool copy=false) const
MappedName setElementName (const IndexedName &element, const MappedName &name, long masterTag, const ElementIDRefs *sid=nullptr, bool overwrite=false)
bool hasElementMap ()
std::vector< std::pair< MappedName, ElementIDRefs > > getElementMappedNames (const IndexedName &element, bool needUnmapped=false) const
void hashChildMaps ()
Hash the child element map postfixes to shorten element name from hierarchical maps.
bool hasChildElementMap () const
Check if there is child element map.
virtual void reTagElementMap (long tag, App::StringHasherRef hasher, const char *postfix=nullptr)
Append the Tag (if and only if it is non zero) into the element map.
long getElementHistory (const MappedName &name, MappedName *original=nullptr, std::vector< MappedName > *history=nullptr) const
void setMappedChildElements (const std::vector< Data::ElementMap::MappedChildElements > &children)
std::vector< Data::ElementMap::MappedChildElements > getMappedChildElements () const
char elementType (const Data::MappedName &) const
char elementType (const Data::IndexedName &) const
char elementType (const char *name) const
virtual ElementMapPtr resetElementMap (ElementMapPtr elementMap=ElementMapPtr())
std::vector< MappedElement > getElementMap () const
Get the entire element map.
void setElementMap (const std::vector< MappedElement > &elements)
Set the entire element map.
size_t getElementMapSize (bool flush=true) const
Get the current element map size.
virtual std::vector< IndexedName > getHigherElements (const char *name, bool silent=false) const
Return the higher level element names of the given element.
virtual std::string getElementMapVersion () const
Return the current element map version.
virtual bool checkElementMapVersion (const char *ver) const
Return true to signal element map version change.
void traceElement (const MappedName &name, TraceCallback cb) const
virtual void flushElementMap () const
void setPersistenceFileName (const char *name) const
virtual void beforeSave () const
bool isRestoreFailed () const
void resetRestoreFailure () const
void dumpElementMap (std::ostream &stream) const
const std::string dumpElementMap () const
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from Base::Handled
Handled ()
virtual ~Handled ()
void ref () const
void unref () const
int unrefNoDelete () const
int getRefCount () const
Handled & operator= (const Handled &)
Handled (const Handled &)=delete
Handled (Handled &&)=delete
Handled & operator= (Handled &&)=delete
Static Public Member Functions
static SMESH_Gen * getGenerator ()
Static Public Member Functions inherited from Data::ComplexGeoData
static std::pair< std::string, unsigned long > getTypeAndIndex (const char *Name)
static const std::string & elementMapPrefix ()
static bool isElementName (const char *subName)
Check if the given sub-name only contains an element name.
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Group management
int addGroup (const std::string, const std::string, const int=-1)
Adds group to mesh.
void addGroupElements (int, const std::set< int > &)
Adds elements to group (int due to int used by raw SMESH functions)
bool removeGroup (int)
Remove group (Name due to similarity to SMESH basis functions)
struct FemMeshInfo getInfo () const
void read (const char *FileName)
import from files
void write (const char *FileName) const
void writeABAQUS (const std::string &Filename, int elemParam, bool groupParam, ABAQUS_VolumeVariant volVariant=ABAQUS_VolumeVariant::Standard, ABAQUS_FaceVariant faceVariant=ABAQUS_FaceVariant::Shell, ABAQUS_EdgeVariant edgeVariant=ABAQUS_EdgeVariant::Beam) const
void writeVTK (const std::string &FileName, bool highest=true) const
void writeZ88 (const std::string &FileName) const
Additional Inherited Members
Public Attributes inherited from Data::ComplexGeoData
long Tag {0}
App::StringHasherRef Hasher
String hasher for element name shortening.
Protected Member Functions inherited from Data::ComplexGeoData
Base::Vector3d transformPointToOutside (const Base::Vector3f &vec) const
from local to outside
template<typename Vec >
std::vector< Base::Vector3d > transformPointsToOutside (const std::vector< Vec > &input) const
from local to outside
Base::Vector3d transformVectorToOutside (const Base::Vector3f &vec) const
template<typename Vec >
std::vector< Base::Vector3d > transformVectorsToOutside (const std::vector< Vec > &input) const
Base::Vector3f transformPointToInside (const Base::Vector3d &vec) const
from local to inside
void restoreStream (std::istream &stream, std::size_t count)
void readElements (Base::XMLReader &reader, size_t count)
Base::Vector3d transformToOutside (const Base::Vector3f &vec) const
from local to outside
Base::Vector3f transformToInside (const Base::Vector3d &vec) const
from local to inside
ElementMapPtr elementMap (bool flush=true) const
ElementMapPtr ensureElementMap (bool flush=true)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Data::ComplexGeoData
std::string _persistenceName
bool _restoreFailed = false
Detailed Description
The representation of a FemMesh
Definition at line 83 of file FemMesh.h.
Constructor & Destructor Documentation
FemMesh() [1/2]
FemMesh::FemMesh ()
Definition at line 89 of file FemMesh.cpp.
FemMesh() [2/2]
FemMesh::FemMesh (const FemMesh & mesh)
Definition at line 100 of file FemMesh.cpp.
References getGenerator(), and Mesh2Shape::mesh.
~FemMesh()
FemMesh::~FemMesh () override
Definition at line 112 of file FemMesh.cpp.
Member Function Documentation
addGroup()
int FemMesh::addGroup (const std::string TypeString, const std::string Name, const int theId = -1)
Adds group to mesh.
Definition at line 2622 of file FemMesh.cpp.
References getSMesh(), and toolbit-attributes::group.
addGroupElements()
void FemMesh::addGroupElements (int GroupId, const std::set< int > & ElementIds)
Adds elements to group (int due to int used by raw SMESH functions)
Definition at line 2662 of file FemMesh.cpp.
References getSMesh(), and toolbit-attributes::group.
addHypothesis()
void FemMesh::addHypothesis (const TopoDS_Shape & aSubShape, SMESH_HypothesisPtr hyp)
Definition at line 283 of file FemMesh.cpp.
Referenced by setStandardHypotheses().
compute()
void FemMesh::compute ()
Definition at line 329 of file FemMesh.cpp.
References getGenerator().
Referenced by Fem::FemMeshShapeObject::execute().
countSubElements()
unsigned long FemMesh::countSubElements (const char * Type) const override virtual
Implements Data::ComplexGeoData.
Definition at line 2460 of file FemMesh.cpp.
createHypothesis()
template<typename T > SMESH_HypothesisPtr Fem::FemMesh::createHypothesis (int hypId) inline
Definition at line 235 of file FemMesh.h.
References getGenerator().
getBoundBox()
Base::BoundBox3d FemMesh::getBoundBox () const override virtual
Bound box from the shape.
Implements Data::ComplexGeoData.
Definition at line 2431 of file FemMesh.cpp.
References MengerSponge::box, getSMesh(), and SurfaceTests.TestBlendCurve::vec.
getccxVolumesByFace()
std::map< int, int > FemMesh::getccxVolumesByFace (const TopoDS_Face & face) const
retrieving volume IDs and CalculiX face number by face
That function returns map containing volume ID and face number as per CalculiX definition for tetrahedral elements. See CalculiX documentation for the details.
Definition at line 477 of file FemMesh.cpp.
References DraftVecUtils::find(), getNodesByFace(), SplineSurface::i, and result.
getEdgesByEdge()
std::list< int > FemMesh::getEdgesByEdge (const TopoDS_Edge & edge) const
retrieving edge IDs number by edge
Definition at line 442 of file FemMesh.cpp.
References getNodesByEdge(), SplineSurface::i, and result.
getEdgesOnly()
std::set< int > FemMesh::getEdgesOnly () const
retrieving IDs of edges not belonging to any face (and thus not belonging to any volume too)
Definition at line 785 of file FemMesh.cpp.
References getElementNodes().
Referenced by writeABAQUS().
getElementNodes()
std::list< int > FemMesh::getElementNodes (int id) const
retrieving node IDs by element ID
Definition at line 757 of file FemMesh.cpp.
References SplineSurface::i, and result.
Referenced by getEdgesOnly(), and getFacesOnly().
getElementTypes()
std::vector< const char * > FemMesh::getElementTypes () const override virtual
Sub type list List of different subelement types it is NOT a list of the subelements itself
Implements Data::ComplexGeoData.
Definition at line 2449 of file FemMesh.cpp.
getFacesByFace()
std::list< int > FemMesh::getFacesByFace (const TopoDS_Face & face) const
retrieving face IDs number by face
That function returns a list of face IDs.
Definition at line 409 of file FemMesh.cpp.
References getNodesByFace(), SplineSurface::i, and result.
getFacesOnly()
std::set< int > FemMesh::getFacesOnly () const
retrieving IDs of faces not belonging to any volume
Definition at line 826 of file FemMesh.cpp.
References getElementNodes().
Referenced by writeABAQUS().
getGenerator()
SMESH_Gen * FemMesh::getGenerator () static
Definition at line 275 of file FemMesh.cpp.
Referenced by compute(), createHypothesis(), Fem::FemMeshShapeNetgenObject::execute(), FemMesh(), and operator=().
getInfo()
struct Fem::FemMesh::FemMeshInfo FemMesh::getInfo () const
Definition at line 2493 of file FemMesh.cpp.
References getSMesh(), Path.Log::info(), Fem::FemMesh::FemMeshInfo::numFaces, Fem::FemMesh::FemMeshInfo::numHedr, Fem::FemMesh::FemMeshInfo::numHexa, Fem::FemMesh::FemMeshInfo::numNode, Fem::FemMesh::FemMeshInfo::numPoly, Fem::FemMesh::FemMeshInfo::numPris, Fem::FemMesh::FemMeshInfo::numPyrd, Fem::FemMesh::FemMeshInfo::numQuad, Fem::FemMesh::FemMeshInfo::numTetr, Fem::FemMesh::FemMeshInfo::numTria, and Fem::FemMesh::FemMeshInfo::numVolu.
Referenced by FemGui::TaskTetParameter::setInfo(), and FemGui::TaskTetParameter::TaskTetParameter().
getMemSize()
unsigned int FemMesh::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Reimplemented from Data::ComplexGeoData.
Definition at line 2302 of file FemMesh.cpp.
getNodeElements()
std::list< int > FemMesh::getNodeElements (int id, SMDSAbs_ElementType type = SMDSAbs_All) const
retrieving elements IDs by node ID
Definition at line 770 of file FemMesh.cpp.
References result, and Path.Post.scripts.grbl_post::type.
getNodesByEdge()
std::set< int > FemMesh::getNodesByEdge (const TopoDS_Edge & edge) const
retrieving by edge
Definition at line 669 of file FemMesh.cpp.
References KDL::Add(), MengerSponge::box, getTransform(), SplineSurface::i, result, toolbit-attributes::s, Path.Geom::Tolerance, and SurfaceTests.TestBlendCurve::vec.
Referenced by getEdgesByEdge().
getNodesByFace()
std::set< int > FemMesh::getNodesByFace (const TopoDS_Face & face) const
retrieving by face
Definition at line 615 of file FemMesh.cpp.
References KDL::Add(), MengerSponge::box, getTransform(), SplineSurface::i, result, toolbit-attributes::s, Path.Geom::Tolerance, and SurfaceTests.TestBlendCurve::vec.
Referenced by getccxVolumesByFace(), getFacesByFace(), and getVolumesByFace().
getNodesBySolid()
std::set< int > FemMesh::getNodesBySolid (const TopoDS_Solid & solid) const
retrieving by solid
Definition at line 560 of file FemMesh.cpp.
References KDL::Add(), MengerSponge::box, Base::Console(), getTransform(), SplineSurface::i, Base::ConsoleSingleton::Log(), result, toolbit-attributes::s, and SurfaceTests.TestBlendCurve::vec.
getNodesByVertex()
std::set< int > FemMesh::getNodesByVertex (const TopoDS_Vertex & vertex) const
retrieving by vertex
Definition at line 720 of file FemMesh.cpp.
References Base::DistanceP2(), getTransform(), SplineSurface::i, result, Path.Geom::Tolerance, and SurfaceTests.TestBlendCurve::vec.
getPoints()
void FemMesh::getPoints (std::vector< Base::Vector3d > & Points, std::vector< Base::Vector3d > & Normals, double Accuracy, uint16_t flags = 0) const override virtual
Get points from object with given accuracy
Reimplemented from Data::ComplexGeoData.
Definition at line 2475 of file FemMesh.cpp.
References getSMesh(), and Data::ComplexGeoData::transformPointsToOutside().
getSMesh() [1/2]
SMESH_Mesh* Fem::FemMesh::getSMesh ()
getSMesh() [2/2]
SMESH_Mesh * FemMesh::getSMesh () const
Definition at line 265 of file FemMesh.cpp.
Referenced by addGroup(), addGroupElements(), Fem::FemMeshShapeObject::execute(), Fem::FemMeshShapeNetgenObject::execute(), getBoundBox(), getInfo(), getPoints(), removeGroup(), setStandardHypotheses(), and FemGui::PropertyFemMeshItem::value().
getSubElement()
Data::Segment * FemMesh::getSubElement (const char * Type, unsigned long) const override virtual
get the subelement by type and number
Implements Data::ComplexGeoData.
Definition at line 2465 of file FemMesh.cpp.
getSurfaceNodes()
std::set< long > FemMesh::getSurfaceNodes (long ElemId, short FaceId, float Angle = 360) const
retrieving by region growing
Definition at line 334 of file FemMesh.cpp.
References result.
getTransform()
Base::Matrix4D FemMesh::getTransform () const override virtual
get the transformation
Implements Data::ComplexGeoData.
Definition at line 2426 of file FemMesh.cpp.
Referenced by getNodesByEdge(), getNodesByFace(), getNodesBySolid(), and getNodesByVertex().
getVolume()
Base::Quantity FemMesh::getVolume () const
get the volume (when there are volume elements)
Definition at line 2516 of file FemMesh.cpp.
References a, SCL.SimpleDataTypes::b, SCL.SimpleDataTypes::c, src.Mod.PartDesign.PartDesignTests.TestInvoluteGear::Quantity, draftgeoutils.general::v1(), FreeCADInit::Volume, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
getVolumesByFace()
std::list< std::pair< int, int > > FemMesh::getVolumesByFace (const TopoDS_Face & face) const
retrieving volume IDs and face IDs number by face
That function returns map containing volume ID and face ID.
Definition at line 342 of file FemMesh.cpp.
References getNodesByFace(), and result.
operator=()
FemMesh & FemMesh::operator= (const FemMesh & mesh)
Definition at line 125 of file FemMesh.cpp.
References getGenerator(), and Mesh2Shape::mesh.
read()
void FemMesh::read (const char * FileName)
import from files
Definition at line 1600 of file FemMesh.cpp.
References Base::FileInfo::fileNamePure(), Base::FileInfo::filePath(), Base::FileInfo::hasExtension(), Base::FileInfo::isReadable(), and Fem::FemVTKTools::readVTKMesh().
removeGroup()
bool FemMesh::removeGroup (int GroupId)
Remove group (Name due to similarity to SMESH basis functions)
Definition at line 2691 of file FemMesh.cpp.
References getSMesh().
Restore()
void FemMesh::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Reimplemented from Data::ComplexGeoData.
Definition at line 2337 of file FemMesh.cpp.
References DrawingExample::file, and TechDrawTools.TaskFillTemplateFields::reader.
RestoreDocFile()
void FemMesh::RestoreDocFile (Base::Reader &) override virtual
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data. Again you have to apply for the call of this method in the Restore() call:
void PropertyMeshKernel::Restore(Base::XMLReader &reader)
{
  reader.readElement("Mesh");
  std::string file (reader.getAttribute("file") );
  if(file == "")
  {
    // read XML
    MeshCore::MeshDocXML restorer(*_pcMesh);
    restorer.Restore(reader);
  }else{
    // initiate a file read
    reader.addFile(file.c_str(),this);
 }
}
After you issued the reader.addFile() your RestoreDocFile() is called:
void PropertyMeshKernel::RestoreDocFile(Base::Reader &reader)
{
    _pcMesh->Read( reader );
}
See also
Base::Reader,Base::XMLReader
Reimplemented from Data::ComplexGeoData.
Definition at line 2387 of file FemMesh.cpp.
References Base::FileInfo::deleteFile(), DrawingExample::file, Base::FileInfo::filePath(), App::Application::getTempFileName(), and TechDrawTools.TaskFillTemplateFields::reader.
Save()
void FemMesh::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Reimplemented from Data::ComplexGeoData.
Definition at line 2307 of file FemMesh.cpp.
References Base::Writer::addFile(), Base::Writer::ind(), Base::Writer::isForceXML(), and Base::Writer::Stream().
SaveDocFile()
void FemMesh::SaveDocFile (Base::Writer &) const override virtual
This method is used to save large amounts of data to a binary file. Sometimes it makes no sense to write property data as XML. In case the amount of data is too big or the data type has a more effective way to save itself. In this cases it is possible to write the data in a separate file inside the document archive. In case you want do so you have to re-implement SaveDocFile(). First, you have to inform the framework in Save() that you want do so. Here an example from the Mesh module which can save a (pontetionaly big) triangle mesh:
void PropertyMeshKernel::Save (Base::Writer &writer) const
{
  if (writer.isForceXML())
  {
    writer << writer.ind() << "<Mesh>" << std::endl;
    MeshCore::MeshDocXML saver(*_pcMesh);
    saver.Save(writer);
  }else{
   writer << writer.ind() << "<Mesh file=\"" << writer.addFile("MeshKernel.bms", this) <<
"\"/>" << std::endl;
}
The writer.isForceXML() is an indication to force you to write XML. Regardless of size and effectiveness. The second part informs the Base::writer through writer.addFile("MeshKernel.bms", this) that this object wants to write a file with the given name. The method addFile() returns a unique name that then is written in the XML stream. This allows your RestoreDocFile() method to identify and read the file again. Later your SaveDocFile() method is called as many times as you issued the addFile() call:
 void
PropertyMeshKernel::SaveDocFile (Base::Writer &writer) const
{
    _pcMesh->Write( writer );
}
In this method you can simply stream your content to the file (Base::Writer inheriting from ostream).
Reimplemented from Data::ComplexGeoData.
Definition at line 2369 of file FemMesh.cpp.
References Base::FileInfo::deleteFile(), DrawingExample::file, Base::FileInfo::filePath(), App::Application::getTempFileName(), and Base::Writer::Stream().
setStandardHypotheses()
void FemMesh::setStandardHypotheses ()
Definition at line 290 of file FemMesh.cpp.
References addHypothesis(), and getSMesh().
Referenced by Fem::FemMeshShapeObject::execute().
setTransform()
void FemMesh::setTransform (const Base::Matrix4D & rclTrf) override virtual
set the transformation
Implements Data::ComplexGeoData.
Definition at line 2420 of file FemMesh.cpp.
Referenced by Fem::FemMeshObject::onChanged().
transformGeometry()
void FemMesh::transformGeometry (const Base::Matrix4D & rclMat) override virtual
Applies a transformation on the real geometric data type.
Implements Data::ComplexGeoData.
Definition at line 2406 of file FemMesh.cpp.
References Base::Vector3< float_type >::Set().
write()
void FemMesh::write (const char * FileName) const
Definition at line 2252 of file FemMesh.cpp.
References Base::Console(), Base::FileInfo::fileNamePure(), Base::FileInfo::filePath(), Base::FileInfo::hasExtension(), Base::ConsoleSingleton::Log(), writeABAQUS(), writeVTK(), and writeZ88().
writeABAQUS()
void FemMesh::writeABAQUS (const std::string & Filename, int elemParam, bool groupParam, ABAQUS_VolumeVariant volVariant = ABAQUS_VolumeVariant::Standard, ABAQUS_FaceVariant faceVariant = ABAQUS_FaceVariant::Shell, ABAQUS_EdgeVariant edgeVariant = ABAQUS_EdgeVariant::Beam) const
Definition at line 1655 of file FemMesh.cpp.
References Fem::Axisymmetric, Fem::Axisymmetric_Reduced, Fem::Beam, Fem::Beam_Reduced, Fem::Fluid, getEdgesOnly(), getFacesOnly(), Fem::Incompatible, Fem::Membrane, Fem::Membrane_Reduced, Fem::Modified, Fem::Network, Fem::Reduced, Base::Vector3< float_type >::Set(), Fem::Shell, Fem::Shell_Reduced, Fem::Standard, Fem::Strain, Fem::Strain_Reduced, Fem::Stress, Fem::Stress_Reduced, Fem::Truss, and Base::Vector3< float_type >::z.
Referenced by write().
writeVTK()
void FemMesh::writeVTK (const std::string & FileName, bool highest = true) const
Definition at line 1650 of file FemMesh.cpp.
References Fem::FemVTKTools::writeVTKMesh().
Referenced by write().
writeZ88()
void FemMesh::writeZ88 (const std::string & FileName) const
Definition at line 2222 of file FemMesh.cpp.
References toolbit-attributes::args, Base::Console(), SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Log(), Mesh2Shape::mesh, src.Mod.PartDesign.fcgear.svggear::module, RobotExample::Start, and src.Mod.Test.testmakeWireString::String.
Referenced by write().
The documentation for this class was generated from the following files:
FemMesh.h
FemMesh.cpp