FreeCAD: MeshCore::MeshSearchNeighbours Class Reference
MeshCore::MeshSearchNeighbours Class Reference
#include <Tools.h>
Classes
struct CDistRad
Public Member Functions
MeshSearchNeighbours (const MeshKernel &rclM, float fSampleDistance=1.0F)
~MeshSearchNeighbours ()=default
void Reinit (float fSampleDistance)
unsigned long NeighboursFromFacet (FacetIndex ulFacetIdx, float fDistance, unsigned long ulMinPoints, std::vector< Base::Vector3f > &raclResultPoints)
unsigned long NeighboursFromSampledFacets (FacetIndex ulFacetIdx, float fDistance, std::vector< Base::Vector3f > &raclResultPoints)
unsigned long NeighboursFacetFromFacet (FacetIndex ulFacetIdx, float fDistance, std::vector< Base::Vector3f > &raclResultPoints, std::vector< FacetIndex > &raclResultFacets)
MeshSearchNeighbours (const MeshSearchNeighbours &)=delete
MeshSearchNeighbours (MeshSearchNeighbours &&)=delete
void operator= (const MeshSearchNeighbours &)=delete
void operator= (MeshSearchNeighbours &&)=delete
Protected Member Functions
void SampleAllFacets ()
bool CheckDistToFacet (const MeshFacet &rclF)
bool AccumulateNeighbours (const MeshFacet &rclF, FacetIndex ulFIdx)
bool InnerPoint (const Base::Vector3f &rclPt) const
bool TriangleCutsSphere (const MeshFacet &rclF) const
bool ExpandRadius (unsigned long ulMinPoints)
Detailed Description
The MeshSearchNeighbours class provides methods to get all points in the neighbourhood of a given facet.
Definition at line 63 of file Mod/Mesh/App/Core/Tools.h.
Constructor & Destructor Documentation
MeshSearchNeighbours() [1/3]
MeshSearchNeighbours::MeshSearchNeighbours (const MeshKernel & rclM, float fSampleDistance = 1.0F) explicit
Definition at line 34 of file Mod/Mesh/App/Core/Tools.cpp.
References MeshCore::MeshPoint::MARKED, MeshCore::MeshFacet::MARKED, MeshCore::MeshAlgorithm::ResetFacetFlag(), and MeshCore::MeshAlgorithm::ResetPointFlag().
~MeshSearchNeighbours()
MeshCore::MeshSearchNeighbours::~MeshSearchNeighbours () default
MeshSearchNeighbours() [2/3]
MeshCore::MeshSearchNeighbours::MeshSearchNeighbours (const MeshSearchNeighbours &) delete
MeshSearchNeighbours() [3/3]
MeshCore::MeshSearchNeighbours::MeshSearchNeighbours (MeshSearchNeighbours &&) delete
Member Function Documentation
AccumulateNeighbours()
bool MeshSearchNeighbours::AccumulateNeighbours (const MeshFacet & rclF, FacetIndex ulFIdx) protected
Definition at line 223 of file Mod/Mesh/App/Core/Tools.cpp.
References MeshCore::MeshFacet::_aulPoints, Base::DistanceP2(), InnerPoint(), and TriangleCutsSphere().
Referenced by NeighboursFromSampledFacets().
CheckDistToFacet()
bool MeshCore::MeshSearchNeighbours::CheckDistToFacet (const MeshFacet & rclF) inline protected
Definition at line 133 of file Mod/Mesh/App/Core/Tools.h.
References Base::DistanceP2().
Referenced by NeighboursFacetFromFacet(), and NeighboursFromFacet().
ExpandRadius()
bool MeshSearchNeighbours::ExpandRadius (unsigned long ulMinPoints) protected
Definition at line 262 of file Mod/Mesh/App/Core/Tools.cpp.
References MeshCore::MeshPoint::MARKED, and MeshCore::MeshPointArray::SetFlag().
Referenced by NeighboursFromFacet().
InnerPoint()
bool MeshCore::MeshSearchNeighbours::InnerPoint (const Base::Vector3f & rclPt) const inline protected
Definition at line 153 of file Mod/Mesh/App/Core/Tools.h.
Referenced by AccumulateNeighbours(), and NeighboursFromSampledFacets().
NeighboursFacetFromFacet()
unsigned long MeshSearchNeighbours::NeighboursFacetFromFacet (FacetIndex ulFacetIdx, float fDistance, std::vector< Base::Vector3f > & raclResultPoints, std::vector< FacetIndex > & raclResultFacets)
Searches for facets from the start facet.
Definition at line 279 of file Mod/Mesh/App/Core/Tools.cpp.
References MeshCore::MeshFacet::_aulPoints, CheckDistToFacet(), Base::DistanceP2(), MeshCore::MeshKernel::GetFacet(), MeshCore::MeshGeomFacet::GetGravityPoint(), SplineSurface::i, MeshCore::MeshFacet::IsFlag(), MeshCore::MeshPoint::MARKED, MeshCore::MeshFacet::MARKED, MeshCore::MeshPointArray::ResetFlag(), MeshCore::MeshFacet::SetFlag(), and MeshCore::MeshFacetArray::SetFlag().
NeighboursFromFacet()
unsigned long MeshSearchNeighbours::NeighboursFromFacet (FacetIndex ulFacetIdx, float fDistance, unsigned long ulMinPoints, std::vector< Base::Vector3f > & raclResultPoints)
Collects all neighbour points from the facet (by index), the result are the points of the facets lying inside a sphere of radius fDistance, center center of the original facet. This method uses the MARKED flags.
Definition at line 53 of file Mod/Mesh/App/Core/Tools.cpp.
References CheckDistToFacet(), ExpandRadius(), MeshCore::MeshKernel::GetFacet(), MeshCore::MeshGeomFacet::GetGravityPoint(), SplineSurface::i, MeshCore::MeshFacet::IsFlag(), MeshCore::MeshPoint::MARKED, MeshCore::MeshFacet::MARKED, MeshCore::MeshPointArray::ResetFlag(), MeshCore::MeshFacet::SetFlag(), and MeshCore::MeshFacetArray::SetFlag().
NeighboursFromSampledFacets()
unsigned long MeshSearchNeighbours::NeighboursFromSampledFacets (FacetIndex ulFacetIdx, float fDistance, std::vector< Base::Vector3f > & raclResultPoints)
Searches for facets from the start facet, sample the neighbour facets and accumulates the points.
Definition at line 157 of file Mod/Mesh/App/Core/Tools.cpp.
References AccumulateNeighbours(), Wm4::Sphere3< Real >::Center, MeshCore::MeshKernel::GetFacet(), MeshCore::MeshGeomFacet::GetGravityPoint(), InnerPoint(), MeshCore::MeshFacet::IsFlag(), MeshCore::MeshFacet::MARKED, Wm4::Sphere3< Real >::Radius, SampleAllFacets(), MeshCore::MeshFacet::SetFlag(), MeshCore::MeshFacetArray::SetFlag(), Base::Vector3< float >, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
operator=() [1/2]
void MeshCore::MeshSearchNeighbours::operator= (const MeshSearchNeighbours &) delete
operator=() [2/2]
void MeshCore::MeshSearchNeighbours::operator= (MeshSearchNeighbours &&) delete
Reinit()
void MeshSearchNeighbours::Reinit (float fSampleDistance)
Re-initilaizes internal structures.
Definition at line 45 of file Mod/Mesh/App/Core/Tools.cpp.
References MeshCore::MeshPoint::MARKED, MeshCore::MeshFacet::MARKED, MeshCore::MeshAlgorithm::ResetFacetFlag(), and MeshCore::MeshAlgorithm::ResetPointFlag().
SampleAllFacets()
void MeshSearchNeighbours::SampleAllFacets () protected
Subsamples the mesh.
Definition at line 139 of file Mod/Mesh/App/Core/Tools.cpp.
References MeshCore::MeshKernel::CountFacets(), SplineSurface::i, MeshCore::MeshFacetIterator::Init(), MeshCore::MeshFacetIterator::More(), MeshCore::MeshFacetIterator::Next(), and MeshCore::MeshGeomFacet::SubSample().
Referenced by NeighboursFromSampledFacets().
TriangleCutsSphere()
bool MeshCore::MeshSearchNeighbours::TriangleCutsSphere (const MeshFacet & rclF) const inline protected
Definition at line 158 of file Mod/Mesh/App/Core/Tools.h.
Referenced by AccumulateNeighbours().
The documentation for this class was generated from the following files:
Mod/Mesh/App/Core/Tools.h
Mod/Mesh/App/Core/Tools.cpp