FreeCAD: FeaturePython.Octahedron Class Reference
FeaturePython.Octahedron Class Reference
Public Member Functions
def __init__ (self, obj)
def execute (self, fp)
def make_face (self, v1, v2, v3)
Detailed Description
Definition at line 150 of file FeaturePython.py.
Constructor & Destructor Documentation
__init__()
def FeaturePython.Octahedron.__init__ (self, obj)
Definition at line 151 of file FeaturePython.py.
Member Function Documentation
execute()
def FeaturePython.Octahedron.execute (self, fp)
Definition at line 159 of file FeaturePython.py.
References FeaturePython.Octahedron.make_face().
Referenced by FeaturePython.DistanceBolt.onChanged().
make_face()
def FeaturePython.Octahedron.make_face (self, v1, v2, v3)
Definition at line 181 of file FeaturePython.py.
Referenced by FeaturePython.Octahedron.execute().
The documentation for this class was generated from the following file:
FeaturePython.py