FreeCAD: Gui::Thumbnail Class Reference
Gui::Thumbnail Class Reference
#include <Thumbnail.h>
Public Member Functions
Thumbnail (int s=128)
~Thumbnail () override
void setViewer (View3DInventorViewer *)
void setSize (int)
void setFileName (const char *)
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
I/O of the document
unsigned int getMemSize () const override
void Save (Base::Writer &writer) const override
This method is used to save properties or very small amounts of data to an XML document.
void Restore (Base::XMLReader &reader) override
This method is used to restore properties from an XML document.
void SaveDocFile (Base::Writer &writer) const override
This method is used to save large amounts of data to a binary file.
void RestoreDocFile (Base::Reader &reader) override
This method is used to restore large amounts of data from a binary file.
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 35 of file Thumbnail.h.
Constructor & Destructor Documentation
Thumbnail()
Thumbnail::Thumbnail (int s = 128)
Definition at line 45 of file Thumbnail.cpp.
~Thumbnail()
Thumbnail::~Thumbnail () override default
Member Function Documentation
getMemSize()
unsigned int Thumbnail::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Implements Base::Persistence.
Definition at line 66 of file Thumbnail.cpp.
Restore()
void Thumbnail::Restore (Base::XMLReader & reader) override virtual
This method is used to restore properties from an XML document.
Implements Base::Persistence.
Definition at line 78 of file Thumbnail.cpp.
References TechDrawTools.TaskFillTemplateFields::reader.
RestoreDocFile()
void Thumbnail::RestoreDocFile (Base::Reader & reader) override virtual
This method is used to restore large amounts of data from a binary file.
Reimplemented from Base::Persistence.
Definition at line 130 of file Thumbnail.cpp.
References TechDrawTools.TaskFillTemplateFields::reader.
Save()
void Thumbnail::Save (Base::Writer & writer) const override virtual
This method is used to save properties or very small amounts of data to an XML document.
Implements Base::Persistence.
Definition at line 71 of file Thumbnail.cpp.
References Base::Writer::addFile(), and Base::Writer::isForceXML().
Referenced by Gui::Document::Save().
SaveDocFile()
void Thumbnail::SaveDocFile (Base::Writer & writer) const override virtual
This method is used to save large amounts of data to a binary file.
Reimplemented from Base::Persistence.
Definition at line 84 of file Thumbnail.cpp.
References Gui::BitmapFactory(), Gui::BitmapFactoryInst::BottomRight, App::Application::Config(), App::GetApplication(), Gui::View3DInventorViewer::imageFromFramebuffer(), Gui::BitmapFactoryInst::merge(), Gui::BitmapFactoryInst::pixmap(), and Base::Writer::Stream().
setFileName()
void Thumbnail::setFileName (const char * fn)
Definition at line 61 of file Thumbnail.cpp.
Referenced by Gui::Document::Save().
setSize()
void Thumbnail::setSize (int s)
Definition at line 56 of file Thumbnail.cpp.
References toolbit-attributes::s.
Referenced by Gui::Document::Save().
setViewer()
void Thumbnail::setViewer (View3DInventorViewer * v)
Definition at line 51 of file Thumbnail.cpp.
References TestSpreadsheet::v.
Referenced by Gui::Document::Save().
The documentation for this class was generated from the following files:
Thumbnail.h
Thumbnail.cpp