FreeCAD: TechDrawGui::QGCustomSvg Class Reference
TechDrawGui::QGCustomSvg Class Reference
#include <QGCustomSvg.h>
Public Types
enum { Type = QGraphicsItem::UserType + 131 }
Public Member Functions
QGCustomSvg ()
~QGCustomSvg () override
int type () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
virtual void centerAt (QPointF centerPos)
virtual void centerAt (double cX, double cY)
virtual bool load (QByteArray *svgString)
virtual bool load (QString filename)
Protected Attributes
QSvgRenderer * m_svgRender
Detailed Description
Definition at line 43 of file QGCustomSvg.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 49 of file QGCustomSvg.h.
Constructor & Destructor Documentation
QGCustomSvg()
QGCustomSvg::QGCustomSvg () explicit
Definition at line 35 of file QGCustomSvg.cpp.
References m_svgRender.
~QGCustomSvg()
QGCustomSvg::~QGCustomSvg () override
Definition at line 46 of file QGCustomSvg.cpp.
References m_svgRender.
Member Function Documentation
centerAt() [1/2]
void QGCustomSvg::centerAt (double cX, double cY) virtual
Definition at line 56 of file QGCustomSvg.cpp.
References MengerSponge::box, and draftfunctions.scale::scale().
centerAt() [2/2]
void QGCustomSvg::centerAt (QPointF centerPos) virtual
Definition at line 51 of file QGCustomSvg.cpp.
Referenced by TechDrawGui::QGITile::makeSymbol().
load() [1/2]
bool QGCustomSvg::load (QByteArray * svgString) virtual
Definition at line 66 of file QGCustomSvg.cpp.
References m_svgRender.
Referenced by TechDrawGui::QGITile::makeSymbol().
load() [2/2]
bool QGCustomSvg::load (QString filename) virtual
Definition at line 74 of file QGCustomSvg.cpp.
References m_svgRender.
paint()
void QGCustomSvg::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) override
Definition at line 82 of file QGCustomSvg.cpp.
type()
int TechDrawGui::QGCustomSvg::type () const inline override
Definition at line 50 of file QGCustomSvg.h.
Member Data Documentation
m_svgRender
QSvgRenderer* TechDrawGui::QGCustomSvg::m_svgRender protected
Definition at line 61 of file QGCustomSvg.h.
Referenced by load(), QGCustomSvg(), and ~QGCustomSvg().
The documentation for this class was generated from the following files:
QGCustomSvg.h
QGCustomSvg.cpp