FreeCAD: TechDrawGui::TaskDimRepair Class Reference
TechDrawGui::TaskDimRepair Class Reference
#include <TaskDimRepair.h>
Public Member Functions
TaskDimRepair (TechDraw::DrawViewDimension *inDvd)
~TaskDimRepair () override
virtual bool accept ()
virtual bool reject ()
Protected Slots
void slotUseSelection ()
Protected Member Functions
void changeEvent (QEvent *e) override
void setUiPrimary ()
void replaceReferences ()
void updateUi ()
void fillList (QListWidget *lwItems, std::vector< std::string > labels, std::vector< std::string > names)
void loadTableWidget (QTableWidget *tw, TechDraw::ReferenceVector refs)
void saveDimState ()
void restoreDimState ()
Detailed Description
Definition at line 45 of file TaskDimRepair.h.
Constructor & Destructor Documentation
TaskDimRepair()
TaskDimRepair::TaskDimRepair (TechDraw::DrawViewDimension * inDvd)
Definition at line 49 of file TaskDimRepair.cpp.
References draftgeoutils.intersections::connect(), saveDimState(), setUiPrimary(), and slotUseSelection().
~TaskDimRepair()
TaskDimRepair::~TaskDimRepair () override
Definition at line 61 of file TaskDimRepair.cpp.
Member Function Documentation
accept()
bool TaskDimRepair::accept () virtual
Definition at line 232 of file TaskDimRepair.cpp.
References Gui::SelectionSingleton::clearSelection(), Gui::Command::commitCommand(), doCommand, Gui::Command::Gui, Gui::Command::openCommand(), App::DocumentObject::recomputeFeature(), replaceReferences(), and Gui::Selection().
Referenced by TechDrawGui::TaskDlgDimReference::accept().
changeEvent()
void TaskDimRepair::changeEvent (QEvent * e) override protected
Definition at line 253 of file TaskDimRepair.cpp.
References SCL.SimpleDataTypes::e.
fillList()
void TaskDimRepair::fillList (QListWidget * lwItems, std::vector< std::string > labels, std::vector< std::string > names) protected
Definition at line 200 of file TaskDimRepair.cpp.
References SplineSurface::i, App::ExpressionParser::labels, and femtools.tokrules::names.
Referenced by setUiPrimary(), and updateUi().
loadTableWidget()
void TaskDimRepair::loadTableWidget (QTableWidget * tw, TechDraw::ReferenceVector refs) protected
Definition at line 178 of file TaskDimRepair.cpp.
Referenced by setUiPrimary(), and updateUi().
reject()
bool TaskDimRepair::reject () virtual
Definition at line 245 of file TaskDimRepair.cpp.
References Gui::SelectionSingleton::clearSelection(), doCommand, Gui::Command::Gui, restoreDimState(), and Gui::Selection().
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and TechDrawGui::TaskDlgDimReference::reject().
replaceReferences()
void TaskDimRepair::replaceReferences () protected
Definition at line 219 of file TaskDimRepair.cpp.
References TechDraw::DrawViewDimension::setReferences2d(), and TechDraw::DrawViewDimension::setReferences3d().
Referenced by accept().
restoreDimState()
void TaskDimRepair::restoreDimState () protected
Definition at line 98 of file TaskDimRepair.cpp.
References TechDraw::DrawViewDimension::setReferences2d(), and TechDraw::DrawViewDimension::setReferences3d().
Referenced by reject().
saveDimState()
void TaskDimRepair::saveDimState () protected
Definition at line 88 of file TaskDimRepair.cpp.
References TechDraw::DrawViewDimension::getReferences2d(), TechDraw::DrawViewDimension::getReferences3d(), App::PropertyEnumeration::getValue(), TechDraw::DrawViewDimension::getViewPart(), TechDraw::DrawViewDimension::MeasureType, and TechDraw::DrawViewDimension::Type.
Referenced by TaskDimRepair().
setUiPrimary()
void TaskDimRepair::setUiPrimary () protected
Definition at line 64 of file TaskDimRepair.cpp.
References fillList(), App::DocumentObject::getNameInDocument(), TechDraw::DrawViewDimension::getReferences3d(), App::PropertyLinkSubList::getSubValues(), App::PropertyString::getValue(), TechDraw::DrawViewDimension::getViewPart(), App::DocumentObject::Label, loadTableWidget(), and TechDraw::DrawViewDimension::References2D.
Referenced by TaskDimRepair().
slotUseSelection
void TaskDimRepair::slotUseSelection () protected slot
Definition at line 108 of file TaskDimRepair.cpp.
References Gui::SelectionSingleton::addSelection(), Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), Gui::getMainWindow(), App::Document::getName(), App::DocumentObject::getNameInDocument(), Gui::SelectionSingleton::getObjectsOfType(), TechDraw::getReferencesFromSelection(), TechDraw::isInvalid, TechDraw::isViewReference, Gui::Selection(), updateUi(), TechDraw::validateDimSelection(), TechDraw::validateDimSelection3d(), and Path.Log::warning().
Referenced by TaskDimRepair().
updateUi()
void TaskDimRepair::updateUi () protected
Definition at line 162 of file TaskDimRepair.cpp.
References fillList(), App::DocumentObject::getNameInDocument(), App::PropertyString::getValue(), TechDraw::DrawViewDimension::getViewPart(), App::DocumentObject::Label, and loadTableWidget().
Referenced by slotUseSelection().
The documentation for this class was generated from the following files:
TaskDimRepair.h
TaskDimRepair.cpp