FreeCAD: CAMSimulator::DlgCAMSimulator Class Reference
CAMSimulator::DlgCAMSimulator Class Reference
#include <DlgCAMSimulator.h>
Public Member Functions
DlgCAMSimulator (QWindow *parent=nullptr)
~DlgCAMSimulator () override=default
virtual void render (QPainter *painter)
virtual void render ()
virtual void initialize ()
void setAnimating (bool animating)
void SetStockShape (const Part::TopoShape &tshape, float resolution)
void SetBaseShape (const Part::TopoShape &tshape, float resolution)
void renderLater ()
void renderNow ()
void startSimulation (const Part::TopoShape &stock, float quality)
void resetSimulation ()
void addGcodeCommand (const char *cmd)
void addTool (const std::vector< float > &toolProfilePoints, int toolNumber, float diameter, float resolution)
Static Public Member Functions
static DlgCAMSimulator * GetInstance ()
Protected Member Functions
bool event (QEvent *event) override
void checkInitialization ()
void doGlCleanup ()
void exposeEvent (QExposeEvent *event) override
void mouseMoveEvent (QMouseEvent *ev) override
void mousePressEvent (QMouseEvent *ev) override
void mouseReleaseEvent (QMouseEvent *ev) override
void wheelEvent (QWheelEvent *ev) override
void hideEvent (QHideEvent *ev) override
void resizeEvent (QResizeEvent *event) override
void GetMeshData (const Part::TopoShape &tshape, float resolution, std::vector< MillSim::Vertex > &verts, std::vector< GLushort > &indices)
Detailed Description
Definition at line 60 of file DlgCAMSimulator.h.
Constructor & Destructor Documentation
DlgCAMSimulator()
CAMSimulator::DlgCAMSimulator::DlgCAMSimulator (QWindow * parent = nullptr) explicit
Definition at line 42 of file DlgCAMSimulator.cpp.
Referenced by GetInstance().
~DlgCAMSimulator()
CAMSimulator::DlgCAMSimulator::~DlgCAMSimulator () override default
Member Function Documentation
addGcodeCommand()
void CAMSimulator::DlgCAMSimulator::addGcodeCommand (const char * cmd)
Definition at line 127 of file DlgCAMSimulator.cpp.
References MillSim::MillSimulation::AddGcodeLine().
addTool()
void CAMSimulator::DlgCAMSimulator::addTool (const std::vector< float > & toolProfilePoints, int toolNumber, float diameter, float resolution)
Definition at line 132 of file DlgCAMSimulator.cpp.
References MillSim::MillSimulation::AddGcodeLine(), MillSim::MillSimulation::AddTool(), and MillSim::MillSimulation::ToolExists().
checkInitialization()
void CAMSimulator::DlgCAMSimulator::checkInitialization () protected
Definition at line 237 of file DlgCAMSimulator.cpp.
References gOpenGlContext, and initialize().
Referenced by renderNow(), and startSimulation().
doGlCleanup()
void CAMSimulator::DlgCAMSimulator::doGlCleanup () protected
Definition at line 261 of file DlgCAMSimulator.cpp.
Referenced by hideEvent().
event()
bool CAMSimulator::DlgCAMSimulator::event (QEvent * event) override protected
Definition at line 64 of file DlgCAMSimulator.cpp.
References renderNow().
Referenced by exposeEvent().
exposeEvent()
void CAMSimulator::DlgCAMSimulator::exposeEvent (QExposeEvent * event) override protected
Definition at line 76 of file DlgCAMSimulator.cpp.
References event(), and renderNow().
GetInstance()
DlgCAMSimulator * CAMSimulator::DlgCAMSimulator::GetInstance () static
Definition at line 309 of file DlgCAMSimulator.cpp.
References DlgCAMSimulator(), Gui::View3DInventorViewer::getNumSamples(), MillSim::gWindowSizeH, and MillSim::gWindowSizeW.
GetMeshData()
void CAMSimulator::DlgCAMSimulator::GetMeshData (const Part::TopoShape & tshape, float resolution, std::vector< MillSim::Vertex > & verts, std::vector< GLushort > & indices) protected
Definition at line 170 of file DlgCAMSimulator.cpp.
References src.Mod.AddonManager.NetworkManager::count, Base::Vector3< float_type >::Cross(), Part::TopoShape::getSubTopoShapes(), SplineSurface::i, Base::Vector3< float_type >::Normalize(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by SetBaseShape(), and SetStockShape().
hideEvent()
void CAMSimulator::DlgCAMSimulator::hideEvent (QHideEvent * ev) override protected
Definition at line 145 of file DlgCAMSimulator.cpp.
References MillSim::MillSimulation::Clear(), and doGlCleanup().
initialize()
void CAMSimulator::DlgCAMSimulator::initialize () virtual
Definition at line 228 of file DlgCAMSimulator.cpp.
References glEnable, and MillSim::MillSimulation::InitSimulation().
Referenced by checkInitialization().
mouseMoveEvent()
void CAMSimulator::DlgCAMSimulator::mouseMoveEvent (QMouseEvent * ev) override protected
Definition at line 85 of file DlgCAMSimulator.cpp.
References MillSim::MillSimulation::MouseMove(), MS_KBD_ALT, MS_KBD_CONTROL, and MS_KBD_SHIFT.
mousePressEvent()
void CAMSimulator::DlgCAMSimulator::mousePressEvent (QMouseEvent * ev) override protected
Definition at line 99 of file DlgCAMSimulator.cpp.
References MillSim::MillSimulation::MousePress().
mouseReleaseEvent()
void CAMSimulator::DlgCAMSimulator::mouseReleaseEvent (QMouseEvent * ev) override protected
Definition at line 109 of file DlgCAMSimulator.cpp.
References MillSim::MillSimulation::MousePress().
render() [1/2]
void CAMSimulator::DlgCAMSimulator::render () virtual
Definition at line 54 of file DlgCAMSimulator.cpp.
References MillSim::MillSimulation::ProcessSim().
Referenced by renderNow().
render() [2/2]
void CAMSimulator::DlgCAMSimulator::render (QPainter * painter) virtual
Definition at line 49 of file DlgCAMSimulator.cpp.
renderLater()
void CAMSimulator::DlgCAMSimulator::renderLater ()
Definition at line 59 of file DlgCAMSimulator.cpp.
Referenced by renderNow(), and setAnimating().
renderNow()
void CAMSimulator::DlgCAMSimulator::renderNow ()
Definition at line 272 of file DlgCAMSimulator.cpp.
References checkInitialization(), render(), and renderLater().
Referenced by event(), and exposeEvent().
resetSimulation()
void CAMSimulator::DlgCAMSimulator::resetSimulation ()
Definition at line 124 of file DlgCAMSimulator.cpp.
resizeEvent()
void CAMSimulator::DlgCAMSimulator::resizeEvent (QResizeEvent * event) override protected
Definition at line 155 of file DlgCAMSimulator.cpp.
References MillSim::MillSimulation::UpdateWindowScale().
setAnimating()
void CAMSimulator::DlgCAMSimulator::setAnimating (bool animating)
Definition at line 300 of file DlgCAMSimulator.cpp.
References renderLater().
Referenced by startSimulation().
SetBaseShape()
void CAMSimulator::DlgCAMSimulator::SetBaseShape (const Part::TopoShape & tshape, float resolution)
Definition at line 340 of file DlgCAMSimulator.cpp.
References GetMeshData(), and MillSim::MillSimulation::SetBaseObject().
SetStockShape()
void CAMSimulator::DlgCAMSimulator::SetStockShape (const Part::TopoShape & tshape, float resolution)
Definition at line 332 of file DlgCAMSimulator.cpp.
References GetMeshData(), and MillSim::MillSimulation::SetArbitraryStock().
Referenced by startSimulation().
startSimulation()
void CAMSimulator::DlgCAMSimulator::startSimulation (const Part::TopoShape & stock, float quality)
Definition at line 218 of file DlgCAMSimulator.cpp.
References checkInitialization(), setAnimating(), SetStockShape(), and bimcommands.BimViews::show().
wheelEvent()
void CAMSimulator::DlgCAMSimulator::wheelEvent (QWheelEvent * ev) override protected
Definition at line 119 of file DlgCAMSimulator.cpp.
References MillSim::MillSimulation::MouseScroll(), and CAMSimulator::MouseScrollDelta.
The documentation for this class was generated from the following files:
DlgCAMSimulator.h
DlgCAMSimulator.cpp