FreeCAD: CArc Class Reference
CArc Class Reference
#include <Arc.h>
Public Member Functions
CArc ()
CArc (const Point &s, const Point &e, const Point &c, bool dir, int user_data)
void SetDirWithPoint (const Point &p)
double IncludedAngle () const
bool AlmostALine () const
Point MidParam (double param) const
void GetSegments (void(*callbackfunc)(const double *p), double pixels_per_mm) const
Public Attributes
Point m_s
Point m_e
Point m_c
bool m_dir
int m_user_data
Detailed Description
Definition at line 9 of file Arc.h.
Constructor & Destructor Documentation
CArc() [1/2]
CArc::CArc () inline
Definition at line 18 of file Arc.h.
CArc() [2/2]
CArc::CArc (const Point & s, const Point & e, const Point & c, bool dir, int user_data) inline
Definition at line 22 of file Arc.h.
Member Function Documentation
AlmostALine()
bool CArc::AlmostALine () const
Definition at line 48 of file Arc.cpp.
References Point::dist(), geoff_geometry::Dist(), TechDraw::Line, m_c, m_e, m_s, Idf::mid_point(), MidParam(), and Point::tolerance.
GetSegments()
void CArc::GetSegments (void(*)(const double *p) callbackfunc, double pixels_per_mm) const
Definition at line 84 of file Arc.cpp.
References KDL::atan2(), KDL::cos(), Point::dist(), SplineSurface::i, m_c, m_dir, m_e, m_s, buildPsets::p, segments, KDL::sin(), KDL::tan(), MovieTool::x, Point::x, MovieTool::y, and Point::y.
IncludedAngle()
double CArc::IncludedAngle () const
Definition at line 28 of file Arc.cpp.
References KDL::atan2(), m_c, m_dir, m_e, m_s, Point::x, and Point::y.
Referenced by MidParam().
MidParam()
Point CArc::MidParam (double param) const
returns a point which is 0-1 along arc
Definition at line 64 of file Arc.cpp.
References IncludedAngle(), m_c, m_e, m_s, buildPsets::p, Init::param, and TestSpreadsheet::v.
Referenced by AlmostALine().
SetDirWithPoint()
void CArc::SetDirWithPoint (const Point & p)
Definition at line 9 of file Arc.cpp.
References KDL::atan2(), m_c, m_dir, m_e, m_s, buildPsets::p, Point::x, and Point::y.
Member Data Documentation
m_c
Point CArc::m_c
Definition at line 14 of file Arc.h.
Referenced by AlmostALine(), GetSegments(), IncludedAngle(), MidParam(), and SetDirWithPoint().
m_dir
bool CArc::m_dir
Definition at line 15 of file Arc.h.
Referenced by GetSegments(), IncludedAngle(), and SetDirWithPoint().
m_e
Point CArc::m_e
Definition at line 13 of file Arc.h.
Referenced by AlmostALine(), GetSegments(), IncludedAngle(), MidParam(), and SetDirWithPoint().
m_s
Point CArc::m_s
Definition at line 12 of file Arc.h.
Referenced by AlmostALine(), GetSegments(), IncludedAngle(), MidParam(), and SetDirWithPoint().
m_user_data
int CArc::m_user_data
Definition at line 16 of file Arc.h.
The documentation for this class was generated from the following files:
Arc.h
Arc.cpp