FreeCAD: AppPartDesign.cpp File Reference
AppPartDesign.cpp File Reference
#include "PreCompiled.h"
#include <Base/Console.h>
#include <Base/Interpreter.h>
#include <Base/PyObjectBase.h>
#include "Body.h"
#include "DatumCS.h"
#include "DatumLine.h"
#include "DatumPlane.h"
#include "DatumPoint.h"
#include "Measure.h"
#include "FeatureBase.h"
#include "FeatureBoolean.h"
#include "FeatureChamfer.h"
#include "FeatureDraft.h"
#include "FeatureDressUp.h"
#include "FeatureFillet.h"
#include "FeatureGroove.h"
#include "FeatureHelix.h"
#include "FeatureHole.h"
#include "FeatureLinearPattern.h"
#include "FeatureLoft.h"
#include "FeatureMirrored.h"
#include "FeatureMultiTransform.h"
#include "FeaturePad.h"
#include "FeaturePipe.h"
#include "FeaturePocket.h"
#include "FeaturePolarPattern.h"
#include "FeaturePrimitive.h"
#include "FeatureRevolution.h"
#include "FeatureScaled.h"
#include "FeatureSketchBased.h"
#include "FeatureSolid.h"
#include "FeatureThickness.h"
#include "FeatureTransformed.h"
#include "ShapeBinder.h"
Namespaces
PartDesign
Base class of all additive features in PartDesign.
Functions
PyObject * PartDesign::initModule ()
PyMOD_INIT_FUNC (_PartDesign)
Function Documentation
PyMOD_INIT_FUNC()
PyMOD_INIT_FUNC (_PartDesign)
Definition at line 68 of file AppPartDesign.cpp.
References Base::Console(), SCL.SimpleDataTypes::e, SIM::Coin3D::Quarter::Quarter::init(), App::DocumentObjectExtension::init(), Base::Persistence::init(), PartDesign::Measure::initialize(), PartDesign::initModule(), Base::Interpreter(), Base::ConsoleSingleton::Log(), mod, PyMOD_Return, and Base::InterpreterSingleton::runString().