FreeCAD: Gui::Dialog::DlgSettingsWorkbenchesImp Class Reference
Gui::Dialog::DlgSettingsWorkbenchesImp Class Reference
#include <DlgSettingsWorkbenchesImp.h>
Public Member Functions
DlgSettingsWorkbenchesImp (QWidget *parent=nullptr)
~DlgSettingsWorkbenchesImp () override
void saveSettings () override
void loadSettings () override
void resetSettingsToDefaults () override
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Static Public Member Functions
static QStringList getEnabledWorkbenches ()
static QStringList getDisabledWorkbenches ()
Protected Slots
void wbToggled (const QString &wbName, bool enabled)
void wbItemMoved ()
void onStartWbChanged (int index)
void onWbByTabToggled (bool val)
Protected Member Functions
void buildWorkbenchList ()
void changeEvent (QEvent *e) override
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
Detailed Description
The DlgSettingsWorkbenchesImp class implements a pseudo-preference page explain why the remaining preference pages aren't loaded yet, and to help the user do so on demand.
Author
Jürgen Riegel
Definition at line 81 of file DlgSettingsWorkbenchesImp.h.
Constructor & Destructor Documentation
DlgSettingsWorkbenchesImp()
DlgSettingsWorkbenchesImp::DlgSettingsWorkbenchesImp (QWidget * parent = nullptr) explicit
Constructs a DlgSettingsWorkbenchesImp
Definition at line 226 of file DlgSettingsWorkbenchesImp.cpp.
References draftgeoutils.intersections::connect(), onStartWbChanged(), onWbByTabToggled(), RobotExample::pos, and wbItemMoved().
~DlgSettingsWorkbenchesImp()
DlgSettingsWorkbenchesImp::~DlgSettingsWorkbenchesImp () override default
Destroys the object and frees any allocated resources
Member Function Documentation
buildWorkbenchList()
void DlgSettingsWorkbenchesImp::buildWorkbenchList () protected
Build the list of unloaded workbenches.
Definition at line 380 of file DlgSettingsWorkbenchesImp.cpp.
References getDisabledWorkbenches(), and getEnabledWorkbenches().
Referenced by loadSettings().
changeEvent()
void DlgSettingsWorkbenchesImp::changeEvent (QEvent * e) override protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
Definition at line 486 of file DlgSettingsWorkbenchesImp.cpp.
References SCL.SimpleDataTypes::e.
getDisabledWorkbenches()
QStringList DlgSettingsWorkbenchesImp::getDisabledWorkbenches () static
Definition at line 452 of file DlgSettingsWorkbenchesImp.cpp.
References Base::Console(), App::GetApplication(), ParameterGrp::GetASCII(), App::Application::GetParameterGroupByPath(), Gui::Application::Instance, Base::ConsoleSingleton::Log(), and Gui::Application::workbenches().
Referenced by buildWorkbenchList(), and getEnabledWorkbenches().
getEnabledWorkbenches()
QStringList DlgSettingsWorkbenchesImp::getEnabledWorkbenches () static
Definition at line 414 of file DlgSettingsWorkbenchesImp.cpp.
References Base::Console(), App::GetApplication(), ParameterGrp::GetASCII(), getDisabledWorkbenches(), App::Application::GetParameterGroupByPath(), Gui::Application::Instance, Base::ConsoleSingleton::Log(), and Gui::Application::workbenches().
Referenced by buildWorkbenchList().
loadSettings()
void DlgSettingsWorkbenchesImp::loadSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 320 of file DlgSettingsWorkbenchesImp.cpp.
References buildWorkbenchList(), App::Application::Config(), App::GetApplication(), importOCA::getline(), and App::Application::GetParameterGroupByPath().
onStartWbChanged
void DlgSettingsWorkbenchesImp::onStartWbChanged (int index) protected slot
Definition at line 630 of file DlgSettingsWorkbenchesImp.cpp.
References SplineSurface::i, and Gui::Dialog::wbListItem::setStartupWb().
Referenced by DlgSettingsWorkbenchesImp().
onWbByTabToggled
void DlgSettingsWorkbenchesImp::onWbByTabToggled (bool val) protected slot
Definition at line 646 of file DlgSettingsWorkbenchesImp.cpp.
References Gui::Dialog::PreferencePage::requireRestart(), and toolbit-attributes::val.
Referenced by DlgSettingsWorkbenchesImp().
resetSettingsToDefaults()
void DlgSettingsWorkbenchesImp::resetSettingsToDefaults () override virtual
Reimplemented from Gui::Dialog::PreferencePage.
Definition at line 352 of file DlgSettingsWorkbenchesImp.cpp.
References App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), ParameterGrp::RemoveASCII(), Gui::Dialog::PreferencePage::requireRestart(), and Gui::Dialog::PreferencePage::resetSettingsToDefaults().
saveSettings()
void DlgSettingsWorkbenchesImp::saveSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 259 of file DlgSettingsWorkbenchesImp.cpp.
References App::GetApplication(), App::Application::GetParameterGroupByPath(), SplineSurface::i, Gui::Application::Instance, Gui::Dialog::wbListItem::isAutoLoading(), Gui::Dialog::wbListItem::isEnabled(), ParameterGrp::SetASCII(), and Gui::Application::signalRefreshWorkbenches.
wbItemMoved
void DlgSettingsWorkbenchesImp::wbItemMoved () protected slot
Definition at line 620 of file DlgSettingsWorkbenchesImp.cpp.
References SplineSurface::i, and Gui::Dialog::wbListItem::setShortcutLabel().
Referenced by DlgSettingsWorkbenchesImp().
wbToggled
void DlgSettingsWorkbenchesImp::wbToggled (const QString & wbName, bool enabled) protected slot
Definition at line 548 of file DlgSettingsWorkbenchesImp.cpp.
References SplineSurface::i, and Gui::Dialog::wbListItem::isEnabled().
The documentation for this class was generated from the following files:
DlgSettingsWorkbenchesImp.h
DlgSettingsWorkbenchesImp.cpp