FreeCAD: ifc4.ifcmaterialprofilesetusage Class Reference
ifc4.ifcmaterialprofilesetusage Class Reference
Public Member Functions
def __init__ (self, forprofileset, cardinalpoint, referenceextent)
def forprofileset ()
def cardinalpoint ()
def referenceextent ()
Public Member Functions inherited from ifc4.ifcmaterialusagedefinition
def associatedto ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
forprofileset
cardinalpoint
referenceextent
Detailed Description
Entity ifcmaterialprofilesetusage definition.
:param forprofileset
:type forprofileset:ifcmaterialprofileset
:param cardinalpoint
:type cardinalpoint:ifccardinalpointreference
:param referenceextent
:type referenceextent:ifcpositivelengthmeasure
Definition at line 10619 of file ifc4.py.
Constructor & Destructor Documentation
__init__()
def ifc4.ifcmaterialprofilesetusage.__init__ (self, forprofileset, cardinalpoint, referenceextent)
Definition at line 10631 of file ifc4.py.
Member Function Documentation
cardinalpoint()
def ifc4.ifcmaterialprofilesetusage.cardinalpoint ()
Definition at line 10652 of file ifc4.py.
References ifc4.ifcmaterialprofilesetusage._cardinalpoint, ifc4.ifcmaterialprofilesetusage.cardinalpoint, and SCL.TypeChecker.check_type().
forprofileset()
def ifc4.ifcmaterialprofilesetusage.forprofileset ()
Definition at line 10638 of file ifc4.py.
References ifc4.ifcmaterialprofilesetusage._forprofileset, SCL.TypeChecker.check_type(), and ifc4.ifcmaterialprofilesetusage.forprofileset.
referenceextent()
def ifc4.ifcmaterialprofilesetusage.referenceextent ()
Definition at line 10666 of file ifc4.py.
References ifc4.ifcmaterialprofilesetusage._referenceextent, SCL.TypeChecker.check_type(), and ifc4.ifcmaterialprofilesetusage.referenceextent.
Member Data Documentation
cardinalpoint
ifc4.ifcmaterialprofilesetusage.cardinalpoint
Definition at line 10634 of file ifc4.py.
Referenced by ifc4.ifcmaterialprofilesetusage.cardinalpoint().
forprofileset
ifc4.ifcmaterialprofilesetusage.forprofileset
Definition at line 10633 of file ifc4.py.
Referenced by ifc4.ifcmaterialprofilesetusage.forprofileset().
referenceextent
ifc4.ifcmaterialprofilesetusage.referenceextent
Definition at line 10635 of file ifc4.py.
Referenced by ifc4.ifcmaterialprofilesetusage.referenceextent().
The documentation for this class was generated from the following file:
ifc4.py