FreeCAD: ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.mechanical_design_geometric_presentation_representation Class Reference
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.mechanical_design_geometric_presentation_representation Class Reference
Public Member Functions
def __init__ (self, inherited0__name, inherited1__items, inherited2__context_of_items, representation_items)
def representation_items ()
def wr1 (self)
def wr2 (self)
def wr3 (self)
def wr4 (self)
def wr5 (self)
def wr6 (self)
def wr7 (self)
def wr8 (self)
def wr9 (self)
def wr10 (self)
def wr11 (self)
def wr12 (self)
def wr13 (self)
Public Member Functions inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.representation
def __init__ (self, name, items, context_of_items)
def name ()
def items ()
def context_of_items ()
def description ()
def id ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
representation_items
Public Attributes inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.representation
name
items
context_of_items
Detailed Description
Entity mechanical_design_geometric_presentation_representation definition.
:param representation_items
:type representation_items:SET(1,None,'mechanical_design_geometric_presentation_representation_items', scope = schema_scope)
Definition at line 4279 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Constructor & Destructor Documentation
__init__()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.mechanical_design_geometric_presentation_representation.__init__ (self, inherited0__name, inherited1__items, inherited2__context_of_items, representation_items)
Definition at line 4285 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Member Function Documentation
representation_items()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.mechanical_design_geometric_presentation_representation.representation_items ()
Definition at line 4290 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.mechanical_design_geometric_presentation_representation._representation_items, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.mechanical_design_geometric_presentation_representation.representation_items.
wr1()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.mechanical_design_geometric_presentation_representation.wr1 (self)
Reimplemented from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.representation.
Definition at line 4302 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF().
Referenced by config_control_design.week_in_year_number.__init__(), config_control_design.minute_in_hour.__init__(), config_control_design.dimension_count.__init__(), config_control_design.positive_length_measure.__init__(), config_control_design.hour_in_day.__init__(), config_control_design.positive_plane_angle_measure.__init__(), ifc2x3.ifctextalignment.__init__(), config_control_design.day_in_week_number.__init__(), ifc4.ifctextalignment.__init__(), ifc2x3.ifcspecularroughness.__init__(), config_control_design.month_in_year_number.__init__(), ifc2x3.ifcheatingvaluemeasure.__init__(), config_control_design.second_in_minute.__init__(), ifc4.ifcspecularroughness.__init__(), automotive_design.minute_in_hour.__init__(), ifc2x3.ifctexttransformation.__init__(), ifc4.ifcheatingvaluemeasure.__init__(), automotive_design.non_negative_length_measure.__init__(), ifc4.ifctexttransformation.__init__(), automotive_design.u_direction_count.__init__(), automotive_design.dimension_count.__init__(), automotive_design.positive_length_measure.__init__(), automotive_design.hour_in_day.__init__(), automotive_design.v_direction_count.__init__(), ifc2x3.ifcfontstyle.__init__(), ifc2x3.ifcboxalignment.__init__(), ifc2x3.ifcminuteinhour.__init__(), automotive_design.day_in_month_number.__init__(), ifc4.ifcfontstyle.__init__(), automotive_design.positive_plane_angle_measure.__init__(), ifc2x3.ifcpositiveplaneanglemeasure.__init__(), ifc4.ifcboxalignment.__init__(), ifc2x3.ifcdimensioncount.__init__(), automotive_design.presentable_text.__init__(), ifc4.ifcpositiveplaneanglemeasure.__init__(), ifc4.ifcdimensioncount.__init__(), ifc2x3.ifcdaylightsavinghour.__init__(), automotive_design.positive_ratio_measure.__init__(), ifc2x3.ifcmonthinyearnumber.__init__(), ifc2x3.ifcsecondinminute.__init__(), ifc2x3.ifcfontvariant.__init__(), automotive_design.month_in_year_number.__init__(), ifc2x3.ifcfontweight.__init__(), ifc2x3.ifchourinday.__init__(), ifc2x3.ifcnormalisedratiomeasure.__init__(), automotive_design.second_in_minute.__init__(), ifc2x3.ifcpositivelengthmeasure.__init__(), ifc2x3.ifcpositiveratiomeasure.__init__(), ifc4.ifcfontvariant.__init__(), ifc4.ifcfontweight.__init__(), ifc2x3.ifctextdecoration.__init__(), ifc4.ifcnormalisedratiomeasure.__init__(), ifc4.ifcpositivelengthmeasure.__init__(), ifc4.ifcpositiveratiomeasure.__init__(), and ifc4.ifctextdecoration.__init__().
wr10()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.mechanical_design_geometric_presentation_representation.wr10 (self)
Definition at line 4365 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF().
wr11()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.mechanical_design_geometric_presentation_representation.wr11 (self)
Definition at line 4372 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF().
wr12()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.mechanical_design_geometric_presentation_representation.wr12 (self)
Definition at line 4379 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF().
wr13()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.mechanical_design_geometric_presentation_representation.wr13 (self)
Definition at line 4386 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF().
wr2()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.mechanical_design_geometric_presentation_representation.wr2 (self)
Reimplemented from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.representation.
Definition at line 4309 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF().
wr3()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.mechanical_design_geometric_presentation_representation.wr3 (self)
Definition at line 4316 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF().
wr4()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.mechanical_design_geometric_presentation_representation.wr4 (self)
Definition at line 4323 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF().
wr5()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.mechanical_design_geometric_presentation_representation.wr5 (self)
Definition at line 4330 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF().
wr6()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.mechanical_design_geometric_presentation_representation.wr6 (self)
Definition at line 4337 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF().
wr7()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.mechanical_design_geometric_presentation_representation.wr7 (self)
Definition at line 4344 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF().
wr8()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.mechanical_design_geometric_presentation_representation.wr8 (self)
Definition at line 4351 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF().
wr9()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.mechanical_design_geometric_presentation_representation.wr9 (self)
Definition at line 4358 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF().
Member Data Documentation
representation_items
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.mechanical_design_geometric_presentation_representation.representation_items
Definition at line 4287 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.mechanical_design_geometric_presentation_representation.representation_items().
The documentation for this class was generated from the following file:
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py