FreeCAD: Gui::StatefulLabel Class Reference
Gui::StatefulLabel Class Reference
#include <Widgets.h>
Public Slots
void setState (QString state)
void setOverridePreference (bool overridePreference)
Public Member Functions
StatefulLabel (QWidget *parent=nullptr)
~StatefulLabel () override
void setDefaultStyle (const QString &defaultStyle)
void setParameterGroup (const std::string &groupName)
void registerState (const QString &state, const QString &styleCSS, const std::string &preferenceName=std::string())
void registerState (const QString &state, const QColor &color, const std::string &preferenceName=std::string())
void registerState (const QString &state, const QColor &foregroundColor, const QColor &backgroundColor, const std::string &preferenceName=std::string())
void OnChange (Base::Subject< const char * > &rCaller, const char *rcReason) override
Public Member Functions inherited from Base::Observer< const char * >
Observer ()=default
virtual ~Observer ()=default
virtual void OnDestroy (Subject< const char * > &rCaller)
virtual const char * Name ()
Properties
bool overridePreference
QString state
Detailed Description
A text label whose appearance can change based on a specified state.
The state is an arbitrary string exposed as a Qt Property (and thus available for selection via a stylesheet). This is intended for things like messages to the user, where a message that is an "error" might be colored differently than one that is a "warning" or a "message".
In order of style precedence for a given state: User preference > Stylesheet > Default unless the stylesheet sets the overridePreference, in which case the stylesheet will take precedence. If a stylesheet sets styles for this widgets states, it should also set the "handledByStyle" property to ensure the style values are used, rather than the defaults.
For example, the .qss might contain: Gui–StatefulLabel { qproperty-overridePreference: true; } Gui–StatefulLabel[state="special_state"] { color: red; } In this case, StatefulLabels with state "special_state" will be colored red, regardless of any entry in preferences. Use the "overridePreference" stylesheet option with care!
Author
Chris Hennes
Definition at line 345 of file Widgets.h.
Constructor & Destructor Documentation
StatefulLabel()
StatefulLabel::StatefulLabel (QWidget * parent = nullptr)
Definition at line 903 of file Widgets.cpp.
References Base::Subject< MsgType >::Attach(), App::GetApplication(), and App::Application::GetParameterGroupByPath().
~StatefulLabel()
StatefulLabel::~StatefulLabel () override
Definition at line 912 of file Widgets.cpp.
References Base::Subject< MsgType >::Detach(), and Base::Reference< T >::isValid().
Member Function Documentation
OnChange()
void StatefulLabel::OnChange (Base::Subject< const char * > & rCaller, const char * rcReason) override virtual
Observes the parameter group and clears the cache if it changes
Implements Base::Observer< const char * >.
Definition at line 963 of file Widgets.cpp.
References state.
registerState() [1/3]
void StatefulLabel::registerState (const QString & state, const QColor & color, const std::string & preferenceName = std::string())
For convenience, allow simple color-only states via QColor (optionally attached to a user preference)
Definition at line 941 of file Widgets.cpp.
References state.
registerState() [2/3]
void StatefulLabel::registerState (const QString & state, const QColor & foregroundColor, const QColor & backgroundColor, const std::string & preferenceName = std::string())
For convenience, allow simple color-only states via QColor (optionally attached to a user preference)
Definition at line 950 of file Widgets.cpp.
References state.
registerState() [3/3]
void StatefulLabel::registerState (const QString & state, const QString & styleCSS, const std::string & preferenceName = std::string())
Register a state and its corresponding style (optionally attached to a user preference)
Definition at line 935 of file Widgets.cpp.
References state.
setDefaultStyle()
void StatefulLabel::setDefaultStyle (const QString & defaultStyle)
If an unrecognized state is set, use this style
Definition at line 919 of file Widgets.cpp.
setOverridePreference
void StatefulLabel::setOverridePreference (bool overridePreference) slot
Definition at line 979 of file Widgets.cpp.
References overridePreference.
setParameterGroup()
void StatefulLabel::setParameterGroup (const std::string & groupName)
If any of the states have user preferences associated with them, this sets the parameter group that stores those preferences. All states must be in the same parameter group, but the group does not have to have entries for all of them.
Definition at line 924 of file Widgets.cpp.
References Base::Subject< MsgType >::Attach(), Base::Subject< MsgType >::Detach(), App::GetApplication(), App::Application::GetParameterGroupByPath(), and Base::Reference< T >::isValid().
setState
void StatefulLabel::setState (QString state) slot
Definition at line 984 of file Widgets.cpp.
References ParameterGrp::GetASCIIMap(), ParameterGrp::GetUnsignedMap(), and state.
Property Documentation
overridePreference
bool Gui::StatefulLabel::overridePreference write
Definition at line 348 of file Widgets.h.
Referenced by setOverridePreference().
state
QString Gui::StatefulLabel::state write
Definition at line 349 of file Widgets.h.
Referenced by src.Mod.Show.mTempoVis.TempoVis::__del__(), src.Mod.Show.mTempoVis.TempoVis::activateWorkbench(), src.Mod.Show.mTempoVis.TempoVis::forget(), src.Mod.AddonManager.addonmanager_readme_controller.WikiCleaner::handle_data(), src.Mod.AddonManager.addonmanager_readme_controller.WikiCleaner::handle_div_end(), src.Mod.AddonManager.addonmanager_readme_controller.WikiCleaner::handle_div_start(), src.Mod.AddonManager.addonmanager_readme_controller.WikiCleaner::handle_endtag(), src.Mod.AddonManager.addonmanager_readme_controller.WikiCleaner::handle_span_end(), src.Mod.AddonManager.addonmanager_readme_controller.WikiCleaner::handle_span_start(), src.Mod.AddonManager.addonmanager_readme_controller.WikiCleaner::handle_starttag(), src.Mod.AddonManager.addonmanager_readme_controller.WikiCleaner::handle_table_end(), src.Mod.AddonManager.addonmanager_readme_controller.WikiCleaner::handle_table_start(), src.Mod.Show.mTempoVis.TempoVis::modifyVPProperty(), OnChange(), registerState(), femsolver.run.Machine::reset(), src.Mod.Show.mTempoVis.TempoVis::restore(), femsolver.run.Machine::run(), setState(), and DraftGui.DraftToolBar::switchUi().
The documentation for this class was generated from the following files:
Widgets.h
Widgets.cpp