FreeCAD: DocOpenGuard Class Reference
DocOpenGuard Class Reference
Public Member Functions
DocOpenGuard (bool &f, boost::signals2::signal< void()> &s)
~DocOpenGuard ()
Public Attributes
bool & flag
boost::signals2::signal< void()> & signal
Detailed Description
Definition at line 680 of file App/Application.cpp.
Constructor & Destructor Documentation
DocOpenGuard()
DocOpenGuard::DocOpenGuard (bool & f, boost::signals2::signal< void()> & s) inline
Definition at line 684 of file App/Application.cpp.
~DocOpenGuard()
DocOpenGuard::~DocOpenGuard () inline
Definition at line 689 of file App/Application.cpp.
References Base::Console(), and Base::ConsoleSingleton::Warning().
Member Data Documentation
flag
bool& DocOpenGuard::flag
Definition at line 682 of file App/Application.cpp.
signal
boost::signals2::signal<void ()>& DocOpenGuard::signal
Definition at line 683 of file App/Application.cpp.
Referenced by src.Mod.Test.Document.DocumentObserverCases.Observer::slotAbortTransaction(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotActivateDocument(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::slotActivateDocument(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotAddedDynamicExtension(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotAppendDynamicProperty(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotBeforeAddingDynamicExtension(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotBeforeChangeDocument(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotBeforeChangeObject(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotChangedDocument(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotChangedObject(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::slotChangedObject(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotChangePropertyEditor(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotCommitTransaction(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotCreatedDocument(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::slotCreatedDocument(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotCreatedObject(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::slotCreatedObject(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotDeletedDocument(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::slotDeletedDocument(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotDeletedObject(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::slotDeletedObject(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotFinishSaveDocument(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::slotInEdit(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotOpenTransaction(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotRecomputedDocument(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotRecomputedObject(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotRedoDocument(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotRelabelDocument(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::slotRelabelDocument(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotRemoveDynamicProperty(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::slotRenameDocument(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::slotResetEdit(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotStartSaveDocument(), and src.Mod.Test.Document.DocumentObserverCases.Observer::slotUndoDocument().
The documentation for this class was generated from the following file:
App/Application.cpp