FreeCAD: App::color_traits< color_type > Struct Template Reference
App::color_traits< color_type > Struct Template Reference
#include <Color.h>
Public Member Functions
color_traits ()=default
color_traits (const color_type &ct)
float redF () const
float greenF () const
float blueF () const
float alphaF () const
int red () const
int green () const
int blue () const
int alpha () const
Static Public Member Functions
static color_type makeColor (int red, int green, int blue, int alpha=255)
Detailed Description
template<class color_type>
struct App::color_traits< color_type >
Definition at line 60 of file Color.h.
Constructor & Destructor Documentation
color_traits() [1/2]
template<class color_type > App::color_traits< color_type >::color_traits () default
Referenced by App::color_traits< SbColor >::blue(), App::color_traits< SbColor4f >::setAlpha(), and App::color_traits< App::Color >::setAlpha().
color_traits() [2/2]
template<class color_type > App::color_traits< color_type >::color_traits (const color_type & ct) inline explicit
Definition at line 83 of file Color.h.
Member Function Documentation
alpha()
template<class color_type > int App::color_traits< color_type >::alpha () const inline
Definition at line 114 of file Color.h.
alphaF()
template<class color_type > float App::color_traits< color_type >::alphaF () const inline
Definition at line 98 of file Color.h.
blue()
template<class color_type > int App::color_traits< color_type >::blue () const inline
Definition at line 110 of file Color.h.
Referenced by App::color_traits< SbColor >::setAlphaF().
blueF()
template<class color_type > float App::color_traits< color_type >::blueF () const inline
Definition at line 94 of file Color.h.
green()
template<class color_type > int App::color_traits< color_type >::green () const inline
Definition at line 106 of file Color.h.
Referenced by App::color_traits< SbColor >::setAlphaF().
greenF()
template<class color_type > float App::color_traits< color_type >::greenF () const inline
Definition at line 90 of file Color.h.
References RobotExample::A, RobotExample::B, and CAMTests.TestPathStock::R.
makeColor()
template<class color_type > static color_type App::color_traits< color_type >::makeColor (int red, int green, int blue, int alpha = 255) inline static
Definition at line 118 of file Color.h.
Referenced by App::Color::fromPackedRGB().
red()
template<class color_type > int App::color_traits< color_type >::red () const inline
Definition at line 102 of file Color.h.
Referenced by App::color_traits< App::Color >::color_traits(), App::color_traits< QColor >::color_traits(), App::color_traits< SbColor >::makeColor(), and App::color_traits< SbColor >::setAlphaF().
redF()
template<class color_type > float App::color_traits< color_type >::redF () const inline
Definition at line 86 of file Color.h.
The documentation for this struct was generated from the following file:
Color.h