FreeCAD: Base::Tools Struct Reference
Base::Tools Struct Reference
#include <Tools.h>
Static Public Member Functions
static std::string getUniqueName (const std::string &, const std::vector< std::string > &, int d=0)
static std::string addNumber (const std::string &, unsigned int, int d=0)
static std::string getIdentifier (const std::string &)
static std::wstring widen (const std::string &str)
static std::string narrow (const std::wstring &str)
static std::string escapedUnicodeFromUtf8 (const char *s)
static std::string escapedUnicodeToUtf8 (const std::string &s)
static std::string escapeQuotesFromString (const std::string &s)
static QString escapeEncodeString (const QString &s)
static std::string escapeEncodeString (const std::string &s)
static QString escapeEncodeFilename (const QString &s)
static std::string escapeEncodeFilename (const std::string &s)
static std::string quoted (const char *)
quoted Creates a quoted string.
static std::string quoted (const std::string &)
quoted Creates a quoted string.
static std::string joinList (const std::vector< std::string > &vec, const std::string &sep=", ")
joinList Join the vector of strings vec using the separator sep
static std::string currentDateTimeString ()
static std::vector< std::string > splitSubName (const std::string &subname)
Detailed Description
Definition at line 287 of file Base/Tools.h.
Member Function Documentation
addNumber()
std::string Base::Tools::addNumber (const std::string & name, unsigned int num, int d = 0) static
Definition at line 148 of file Base/Tools.cpp.
References Path.Post.scripts.refactored_centroid_post::str.
currentDateTimeString()
std::string Base::Tools::currentDateTimeString () static
Definition at line 368 of file Base/Tools.cpp.
Referenced by Cloud::Module::cloudSave(), App::Document::Document(), and App::Document::save().
escapedUnicodeFromUtf8()
std::string Base::Tools::escapedUnicodeFromUtf8 (const char * s) static
Definition at line 202 of file Base/Tools.cpp.
References toolbit-attributes::s, and ArchBuildingPart::unicode.
Referenced by PartGui::Mirroring::accept(), SpreadsheetGui::PropertiesDialog::apply(), Gui::Application::exportTo(), Gui::ExpressionBinding::getEscapedExpressionString(), App::SubObjectT::getSubObjectPython(), Gui::Dialog::DlgPropertyLink::linksToPython(), SketcherGui::TaskSketcherConstraints::onListWidgetConstraintsItemChanged(), Gui::Application::open(), App::Application::processFiles(), MeshCore::WriterOBJ::Save(), Gui::Document::saveAs(), Gui::PropertyEditor::PropertyEnumItem::setValue(), SketcherGui::ConstraintView::swapNamedOfSelectedItems(), and App::ObjectIdentifier::toEscapedString().
escapedUnicodeToUtf8()
std::string Base::Tools::escapedUnicodeToUtf8 (const std::string & s) static
Definition at line 222 of file Base/Tools.cpp.
References toolbit-attributes::s, and ArchBuildingPart::unicode.
Referenced by TechDrawGui::QGIViewAnnotation::drawAnnotation(), MeshCore::ReaderOBJ::Load(), and MeshCore::ReaderOBJ::LoadMaterial().
escapeEncodeFilename() [1/2]
QString Base::Tools::escapeEncodeFilename (const QString & s) static
Definition at line 305 of file Base/Tools.cpp.
References SplineSurface::i, result, and toolbit-attributes::s.
Referenced by Gui::Application::exportTo(), Gui::Application::importFrom(), Gui::Application::open(), TechDrawGui::PagePrinter::printPdf(), App::Application::processCmdLineFiles(), App::Application::processFiles(), Gui::Document::saveAs(), Gui::Document::saveCopy(), TechDrawGui::PagePrinter::saveDXF(), and TechDrawGui::PagePrinter::saveSVG().
escapeEncodeFilename() [2/2]
std::string Base::Tools::escapeEncodeFilename (const std::string & s) static
Definition at line 325 of file Base/Tools.cpp.
References SplineSurface::i, result, and toolbit-attributes::s.
escapeEncodeString() [1/2]
QString Base::Tools::escapeEncodeString (const QString & s) static
Definition at line 259 of file Base/Tools.cpp.
References SplineSurface::i, result, and toolbit-attributes::s.
Referenced by setLinkLabel(), and TechDrawGui::TaskWeldingSymbol::updateTiles().
escapeEncodeString() [2/2]
std::string Base::Tools::escapeEncodeString (const std::string & s) static
Definition at line 282 of file Base/Tools.cpp.
References SplineSurface::i, result, and toolbit-attributes::s.
escapeQuotesFromString()
std::string Base::Tools::escapeQuotesFromString (const std::string & s) static
Definition at line 239 of file Base/Tools.cpp.
References SplineSurface::i, result, and toolbit-attributes::s.
Referenced by SpreadsheetGui::PropertiesDialog::apply(), Gui::ExpressionBinding::getEscapedExpressionString(), and Base::Quantity::getSafeUserString().
getIdentifier()
std::string Base::Tools::getIdentifier (const std::string & name) static
Definition at line 160 of file Base/Tools.cpp.
Referenced by Gui::Dialog::DlgAddProperty::accept(), App::DynamicProperty::addDynamicProperty(), App::Document::addObjects(), App::Application::getUniqueDocumentName(), App::Document::getUniqueObjectName(), isNameGroupOk(), and isNamePropOk().
getUniqueName()
std::string Base::Tools::getUniqueName (const std::string & name, const std::vector< std::string > & names, int d = 0) static
Definition at line 138 of file Base/Tools.cpp.
References Base::unique_name::get(), and femtools.tokrules::names.
Referenced by App::Document::addObjects(), App::Document::getStandardObjectName(), App::Application::getUniqueDocumentName(), Base::Writer::getUniqueFileName(), App::Document::getUniqueObjectName(), App::Application::newDocument(), and App::PropertyString::setValue().
joinList()
std::string Base::Tools::joinList (const std::vector< std::string > & vec, const std::string & sep = ", ") static
joinList Join the vector of strings vec using the separator sep
Parameters
vec
sep
Returns
Definition at line 359 of file Base/Tools.cpp.
References Path.Post.scripts.refactored_centroid_post::str, and SurfaceTests.TestBlendCurve::vec.
Referenced by PartGui::DlgBooleanOperation::accept().
narrow()
std::string Base::Tools::narrow (const std::wstring & str) static
Definition at line 192 of file Base/Tools.cpp.
References SplineSurface::i, and Path.Post.scripts.refactored_centroid_post::str.
quoted() [1/2]
std::string Base::Tools::quoted (const char * name) static
quoted Creates a quoted string.
Parameters
String to be quoted.
Returns
A quoted std::string.
Definition at line 345 of file Base/Tools.cpp.
References Path.Post.scripts.refactored_centroid_post::str.
Referenced by PartGui::DlgBooleanOperation::accept(), Gui::PropertyEditor::PropertyStringItem::setValue(), Gui::PropertyEditor::PropertyFontItem::setValue(), Gui::PropertyEditor::PropertyFileItem::setValue(), Gui::PropertyEditor::PropertyPathItem::setValue(), and Gui::PropertyEditor::PropertyTransientFileItem::setValue().
quoted() [2/2]
std::string Base::Tools::quoted (const std::string & name) static
quoted Creates a quoted string.
Parameters
String to be quoted.
Returns
A quoted std::string.
Definition at line 352 of file Base/Tools.cpp.
References Path.Post.scripts.refactored_centroid_post::str.
splitSubName()
std::vector< std::string > Base::Tools::splitSubName (const std::string & subname) static
Definition at line 376 of file Base/Tools.cpp.
References importOCA::getline().
Referenced by Gui::View3DInventorViewer::alignToSelection(), App::GeoFeature::getGlobalPlacement(), and AssemblyGui::ViewProviderAssembly::getSelectedObjectsWithinAssembly().
widen()
std::wstring Base::Tools::widen (const std::string & str) static
Definition at line 182 of file Base/Tools.cpp.
References SplineSurface::i, and Path.Post.scripts.refactored_centroid_post::str.
The documentation for this struct was generated from the following files:
Base/Tools.h
Base/Tools.cpp