FreeCAD: ifc2x3.ifcopticalmaterialproperties Class Reference
ifc2x3.ifcopticalmaterialproperties Class Reference
Public Member Functions
def __init__ (self, inherited0__material, visibletransmittance, solartransmittance, thermalirtransmittance, thermaliremissivityback, thermaliremissivityfront, visiblereflectanceback, visiblereflectancefront, solarreflectancefront, solarreflectanceback)
def visibletransmittance ()
def solartransmittance ()
def thermalirtransmittance ()
def thermaliremissivityback ()
def thermaliremissivityfront ()
def visiblereflectanceback ()
def visiblereflectancefront ()
def solarreflectancefront ()
def solarreflectanceback ()
Public Member Functions inherited from ifc2x3.ifcmaterialproperties
def __init__ (self, material)
def material ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
visibletransmittance
solartransmittance
thermalirtransmittance
thermaliremissivityback
thermaliremissivityfront
visiblereflectanceback
visiblereflectancefront
solarreflectancefront
solarreflectanceback
Public Attributes inherited from ifc2x3.ifcmaterialproperties
material
Detailed Description
Entity ifcopticalmaterialproperties definition.
:param visibletransmittance
:type visibletransmittance:ifcpositiveratiomeasure
:param solartransmittance
:type solartransmittance:ifcpositiveratiomeasure
:param thermalirtransmittance
:type thermalirtransmittance:ifcpositiveratiomeasure
:param thermaliremissivityback
:type thermaliremissivityback:ifcpositiveratiomeasure
:param thermaliremissivityfront
:type thermaliremissivityfront:ifcpositiveratiomeasure
:param visiblereflectanceback
:type visiblereflectanceback:ifcpositiveratiomeasure
:param visiblereflectancefront
:type visiblereflectancefront:ifcpositiveratiomeasure
:param solarreflectancefront
:type solarreflectancefront:ifcpositiveratiomeasure
:param solarreflectanceback
:type solarreflectanceback:ifcpositiveratiomeasure
Definition at line 18025 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcopticalmaterialproperties.__init__ (self, inherited0__material, visibletransmittance, solartransmittance, thermalirtransmittance, thermaliremissivityback, thermaliremissivityfront, visiblereflectanceback, visiblereflectancefront, solarreflectancefront, solarreflectanceback)
Definition at line 18055 of file ifc2x3.py.
Member Function Documentation
solarreflectanceback()
def ifc2x3.ifcopticalmaterialproperties.solarreflectanceback ()
Definition at line 18180 of file ifc2x3.py.
References ifc2x3.ifcopticalmaterialproperties._solarreflectanceback, SCL.TypeChecker.check_type(), and ifc2x3.ifcopticalmaterialproperties.solarreflectanceback.
solarreflectancefront()
def ifc2x3.ifcopticalmaterialproperties.solarreflectancefront ()
Definition at line 18166 of file ifc2x3.py.
References ifc2x3.ifcopticalmaterialproperties._solarreflectancefront, SCL.TypeChecker.check_type(), and ifc2x3.ifcopticalmaterialproperties.solarreflectancefront.
solartransmittance()
def ifc2x3.ifcopticalmaterialproperties.solartransmittance ()
Definition at line 18082 of file ifc2x3.py.
References ifc2x3.ifcopticalmaterialproperties._solartransmittance, SCL.TypeChecker.check_type(), and ifc2x3.ifcopticalmaterialproperties.solartransmittance.
thermaliremissivityback()
def ifc2x3.ifcopticalmaterialproperties.thermaliremissivityback ()
Definition at line 18110 of file ifc2x3.py.
References ifc2x3.ifcopticalmaterialproperties._thermaliremissivityback, SCL.TypeChecker.check_type(), and ifc2x3.ifcopticalmaterialproperties.thermaliremissivityback.
thermaliremissivityfront()
def ifc2x3.ifcopticalmaterialproperties.thermaliremissivityfront ()
Definition at line 18124 of file ifc2x3.py.
References ifc2x3.ifcopticalmaterialproperties._thermaliremissivityfront, SCL.TypeChecker.check_type(), and ifc2x3.ifcopticalmaterialproperties.thermaliremissivityfront.
thermalirtransmittance()
def ifc2x3.ifcopticalmaterialproperties.thermalirtransmittance ()
Definition at line 18096 of file ifc2x3.py.
References ifc2x3.ifcopticalmaterialproperties._thermalirtransmittance, SCL.TypeChecker.check_type(), and ifc2x3.ifcopticalmaterialproperties.thermalirtransmittance.
visiblereflectanceback()
def ifc2x3.ifcopticalmaterialproperties.visiblereflectanceback ()
Definition at line 18138 of file ifc2x3.py.
References ifc2x3.ifcopticalmaterialproperties._visiblereflectanceback, SCL.TypeChecker.check_type(), and ifc2x3.ifcopticalmaterialproperties.visiblereflectanceback.
visiblereflectancefront()
def ifc2x3.ifcopticalmaterialproperties.visiblereflectancefront ()
Definition at line 18152 of file ifc2x3.py.
References ifc2x3.ifcopticalmaterialproperties._visiblereflectancefront, SCL.TypeChecker.check_type(), and ifc2x3.ifcopticalmaterialproperties.visiblereflectancefront.
visibletransmittance()
def ifc2x3.ifcopticalmaterialproperties.visibletransmittance ()
Definition at line 18068 of file ifc2x3.py.
References ifc2x3.ifcopticalmaterialproperties._visibletransmittance, SCL.TypeChecker.check_type(), and ifc2x3.ifcopticalmaterialproperties.visibletransmittance.
Member Data Documentation
solarreflectanceback
ifc2x3.ifcopticalmaterialproperties.solarreflectanceback
Definition at line 18065 of file ifc2x3.py.
Referenced by ifc2x3.ifcopticalmaterialproperties.solarreflectanceback().
solarreflectancefront
ifc2x3.ifcopticalmaterialproperties.solarreflectancefront
Definition at line 18064 of file ifc2x3.py.
Referenced by ifc2x3.ifcopticalmaterialproperties.solarreflectancefront().
solartransmittance
ifc2x3.ifcopticalmaterialproperties.solartransmittance
Definition at line 18058 of file ifc2x3.py.
Referenced by ifc2x3.ifcopticalmaterialproperties.solartransmittance().
thermaliremissivityback
ifc2x3.ifcopticalmaterialproperties.thermaliremissivityback
Definition at line 18060 of file ifc2x3.py.
Referenced by ifc2x3.ifcopticalmaterialproperties.thermaliremissivityback().
thermaliremissivityfront
ifc2x3.ifcopticalmaterialproperties.thermaliremissivityfront
Definition at line 18061 of file ifc2x3.py.
Referenced by ifc2x3.ifcopticalmaterialproperties.thermaliremissivityfront().
thermalirtransmittance
ifc2x3.ifcopticalmaterialproperties.thermalirtransmittance
Definition at line 18059 of file ifc2x3.py.
Referenced by ifc2x3.ifcopticalmaterialproperties.thermalirtransmittance().
visiblereflectanceback
ifc2x3.ifcopticalmaterialproperties.visiblereflectanceback
Definition at line 18062 of file ifc2x3.py.
Referenced by ifc2x3.ifcopticalmaterialproperties.visiblereflectanceback().
visiblereflectancefront
ifc2x3.ifcopticalmaterialproperties.visiblereflectancefront
Definition at line 18063 of file ifc2x3.py.
Referenced by ifc2x3.ifcopticalmaterialproperties.visiblereflectancefront().
visibletransmittance
ifc2x3.ifcopticalmaterialproperties.visibletransmittance
Definition at line 18057 of file ifc2x3.py.
Referenced by ifc2x3.ifcopticalmaterialproperties.visibletransmittance().
The documentation for this class was generated from the following file:
ifc2x3.py