FreeCAD: CommandConstraints.cpp File Reference
CommandConstraints.cpp File Reference
#include "PreCompiled.h"
#include <Precision.hxx>
#include <QPainter>
#include <cfloat>
#include <boost/range/adaptor/reversed.hpp>
#include <App/Application.h>
#include <Base/Tools.h>
#include <Base/Tools2D.h>
#include <Gui/Action.h>
#include <Gui/Application.h>
#include <Gui/BitmapFactory.h>
#include <Gui/CommandT.h>
#include <Gui/DlgCheckableMessageBox.h>
#include <Gui/Document.h>
#include <Gui/MainWindow.h>
#include <Gui/Notifications.h>
#include <Gui/Selection.h>
#include <Gui/SelectionFilter.h>
#include <Gui/SelectionObject.h>
#include <Mod/Sketcher/App/GeometryFacade.h>
#include <Mod/Sketcher/App/SketchObject.h>
#include <Mod/Sketcher/App/SolverGeometryExtension.h>
#include "CommandConstraints.h"
#include "DrawSketchHandler.h"
#include "EditDatumDialog.h"
#include "Utils.h"
#include "ViewProviderSketch.h"
#include "ui_InsertDatum.h"
#include <Inventor/events/SoKeyboardEvent.h>
Classes
struct SketcherGui::SelIdPair
struct SketcherGui::SketchSelection
struct SketcherGui::SketchSelection::SketchSelectionItem
class SketcherGui::GenericConstraintSelection
The GenericConstraintSelection class SelectionFilterGate with changeable filters. In a constraint creation mode like point on object, if the first selection object can be a point, the next has to be a curve for the constraint to make sense. Thus filters are changeable so that same filter can be kept on while in one mode.
class CmdSketcherConstraint
The CmdSketcherConstraint class Superclass for all sketcher constraints to ease generation of constraint creation modes.
class DrawSketchHandlerGenConstraint
class CmdSketcherCompDimensionTools
class CmdSketcherCompConstrainTools
class CmdSketcherCompToggleConstraints
class GeomSelectionSizes
class DrawSketchHandlerDimension
class CmdSketcherCompHorizontalVertical
class CmdSketcherConstrainHorVer
class CmdSketcherConstrainHorizontal
class CmdSketcherConstrainVertical
class CmdSketcherConstrainLock
class CmdSketcherConstrainBlock
class CmdSketcherConstrainCoincidentUnified
class CmdSketcherConstrainCoincident
class CmdSketcherConstrainPointOnObject
class CmdSketcherConstrainDistance
class CmdSketcherConstrainDistanceX
class CmdSketcherConstrainDistanceY
class CmdSketcherConstrainParallel
class CmdSketcherConstrainPerpendicular
class CmdSketcherConstrainTangent
class CmdSketcherConstrainRadius
class CmdSketcherConstrainDiameter
class CmdSketcherConstrainRadiam
class CmdSketcherConstrainAngle
class CmdSketcherConstrainEqual
class CmdSketcherConstrainSymmetric
Namespaces
SketcherGui
Enumerations
enum SketcherGui::ConstraintCreationMode { SketcherGui::Driving, SketcherGui::Reference }
enum SketcherGui::SelType {
SketcherGui::SelUnknown = 0, SketcherGui::SelVertex = 1, SketcherGui::SelVertexOrRoot = 64, SketcherGui::SelRoot = 2,
SketcherGui::SelEdge = 4, SketcherGui::SelEdgeOrAxis = 128, SketcherGui::SelHAxis = 8, SketcherGui::SelVAxis = 16,
SketcherGui::SelExternalEdge = 32
}
The SelType enum Types of sketch elements that can be (pre)selected. The root/origin and the axes are put up separately so that they can be specifically disallowed, for example, when in lock, horizontal, or vertical constraint modes.
Functions
bool isCreateConstraintActive (Gui::Document *doc)
void finishDatumConstraint (Gui::Command *cmd, Sketcher::SketchObject *sketch, bool isDriving=true, unsigned int numberofconstraints=1)
void showNoConstraintBetweenExternal (const App::DocumentObject *obj)
void showNoConstraintBetweenFixedGeometry (const App::DocumentObject *obj)
bool isGeoConcentricCompatible (const Part::Geometry *geo)
bool removeRedundantPointOnObject (SketchObject *Obj, int GeoId1, int GeoId2, int GeoId3)
bool addConstraintSafely (SketchObject *obj, std::function< void()> constraintadditionfunction)
bool canHorVerBlock (Sketcher::SketchObject *Obj, int geoId)
void horVerActivated (CmdSketcherConstraint *cmd, std::string type)
void horVerApplyConstraint (CmdSketcherConstraint *cmd, std::string type, std::vector< SelIdPair > &selSeq, int seqIndex)
void CreateSketcherCommandsConstraints ()
Variables
ConstraintCreationMode constraintCreationMode = Driving
Function Documentation
addConstraintSafely()
bool addConstraintSafely (SketchObject * obj, std::function< void()> constraintadditionfunction)
Definition at line 765 of file CommandConstraints.cpp.
References Gui::Command::abortCommand(), SCL.SimpleDataTypes::e, Gui::NotifyUserError(), Arch::QT_TRANSLATE_NOOP, Gui::TranslatedUserError(), and SketcherGui::tryAutoRecompute().
Referenced by CmdSketcherConstrainBlock::activated(), CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainBlock::applyConstraint(), CmdSketcherConstrainPerpendicular::applyConstraint(), and CmdSketcherConstrainTangent::applyConstraint().
canHorVerBlock()
bool canHorVerBlock (Sketcher::SketchObject * Obj, int geoId)
Definition at line 2859 of file CommandConstraints.cpp.
References Sketcher::Block, Sketcher::SketchObject::Constraints, Sketcher::PropertyConstraintList::getValues(), Sketcher::Horizontal, Sketcher::none, Gui::TranslatedUserWarning(), and Sketcher::Vertical.
Referenced by horVerActivated(), and horVerApplyConstraint().
CreateSketcherCommandsConstraints()
void CreateSketcherCommandsConstraints ()
Definition at line 10205 of file CommandConstraints.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
finishDatumConstraint()
void finishDatumConstraint (Gui::Command * cmd, Sketcher::SketchObject * sketch, bool isDriving = true, unsigned int numberofconstraints = 1)
Definition at line 95 of file CommandConstraints.cpp.
References Gui::SelectionSingleton::clearSelection(), Gui::Command::commitCommand(), Sketcher::SketchObject::Constraints, Sketcher::Diameter, toolbit-attributes::doc, SketcherGui::ViewProviderSketch::draw(), SketcherGui::EditDatumDialog::exec(), Gui::Command::getActiveGuiDocument(), App::GetApplication(), ParameterGrp::GetBool(), Base::Persistence::getClassTypeId(), ParameterGrp::GetFloat(), Sketcher::SketchObject::getGeometry(), App::Application::GetParameterGroupByPath(), SketcherGui::ViewProviderSketch::getScaleFactor(), Gui::Command::getSelection(), Sketcher::PropertyConstraintList::getValues(), SplineSurface::i, TechDraw::isCircle, M_PI, Sketcher::Radius, bimcommands.BimViews::show(), SketcherGui::tryAutoRecompute(), and Sketcher::Constraint::Type.
Referenced by CmdSketcherConstrainDistance::activated(), CmdSketcherConstrainDistanceX::activated(), CmdSketcherConstrainDistanceY::activated(), CmdSketcherConstrainRadius::activated(), CmdSketcherConstrainDiameter::activated(), CmdSketcherConstrainRadiam::activated(), CmdSketcherConstrainAngle::activated(), CmdSketcherConstrainDistance::applyConstraint(), CmdSketcherConstrainDistanceX::applyConstraint(), CmdSketcherConstrainDistanceY::applyConstraint(), CmdSketcherConstrainRadius::applyConstraint(), CmdSketcherConstrainDiameter::applyConstraint(), CmdSketcherConstrainRadiam::applyConstraint(), CmdSketcherConstrainAngle::applyConstraint(), and SketcherGui::makeAngleBetweenTwoLines().
horVerActivated()
void horVerActivated (CmdSketcherConstraint * cmd, std::string type)
Definition at line 2894 of file CommandConstraints.cpp.
References SketcherGui::ActivateHandler(), Base::Vector2d::Angle(), DraftVecUtils::angle(), canHorVerBlock(), Gui::SelectionSingleton::clearSelection(), Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), KDL::cos(), Gui::Command::getActiveGuiDocument(), App::GetApplication(), ParameterGrp::GetBool(), Base::Persistence::getClassTypeId(), SketcherGui::getIdsFromName(), UtilsAssembly::getObject(), App::Application::GetParameterGroupByPath(), Gui::Command::getSelection(), Gui::SelectionSingleton::getSelectionEx(), SketcherGui::isEdge(), Sketcher::isLineSegment(), SketcherGui::isPointOrSegmentFixed(), SketcherGui::isVertex(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, Path.Dressup.Utils::selection(), KDL::sin(), toVector2d(), Gui::TranslatedUserWarning(), SketcherGui::tryAutoRecompute(), and Path.Post.scripts.grbl_post::type.
Referenced by CmdSketcherConstrainHorVer::activated(), CmdSketcherConstrainHorizontal::activated(), and CmdSketcherConstrainVertical::activated().
horVerApplyConstraint()
void horVerApplyConstraint (CmdSketcherConstraint * cmd, std::string type, std::vector< SelIdPair > & selSeq, int seqIndex)
Definition at line 3030 of file CommandConstraints.cpp.
References Base::Vector2d::Angle(), DraftVecUtils::angle(), SketcherGui::areBothPointsOrSegmentsFixed(), canHorVerBlock(), Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), KDL::cos(), Gui::Command::getActiveGuiDocument(), Sketcher::SketchObject::getGeometry(), Gui::Document::getInEdit(), Sketcher::SketchObject::getPoint(), Sketcher::isLineSegment(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, showNoConstraintBetweenFixedGeometry(), KDL::sin(), toVector2d(), Gui::TranslatedUserWarning(), SketcherGui::tryAutoRecompute(), and Path.Post.scripts.grbl_post::type.
Referenced by CmdSketcherConstrainHorVer::applyConstraint(), CmdSketcherConstrainHorizontal::applyConstraint(), and CmdSketcherConstrainVertical::applyConstraint().
isCreateConstraintActive()
bool isCreateConstraintActive (Gui::Document * doc)
Definition at line 76 of file CommandConstraints.cpp.
References toolbit-attributes::doc, Base::Persistence::getClassTypeId(), SketcherGui::ViewProviderSketch::getSketchMode(), and Gui::Selection().
isGeoConcentricCompatible()
bool isGeoConcentricCompatible (const Part::Geometry * geo)
Definition at line 187 of file CommandConstraints.cpp.
References Sketcher::isArcOfCircle(), Sketcher::isArcOfEllipse(), TechDraw::isCircle, and TechDraw::isEllipse.
Referenced by CmdSketcherConstrainCoincidentUnified::activatedCoincident(), and CmdSketcherConstrainCoincidentUnified::applyConstraintCoincident().
removeRedundantPointOnObject()
bool removeRedundantPointOnObject (SketchObject * Obj, int GeoId1, int GeoId2, int GeoId3)
Definition at line 197 of file CommandConstraints.cpp.
References Gui::cmdAppObjectArgs(), Sketcher::SketchObject::Constraints, Sketcher::SketchObject::getGeometry(), Sketcher::PropertyConstraintList::getValues(), Sketcher::isBSplineCurve(), SketcherGui::notifyConstraintSubstitutions(), Sketcher::PointOnObject, and SketcherGui::tryAutoRecomputeIfNotSolve().
Referenced by CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainAngle::activated(), CmdSketcherConstrainPerpendicular::applyConstraint(), CmdSketcherConstrainTangent::applyConstraint(), and CmdSketcherConstrainAngle::applyConstraint().
showNoConstraintBetweenExternal()
void showNoConstraintBetweenExternal (const App::DocumentObject * obj)
Definition at line 169 of file CommandConstraints.cpp.
References Gui::TranslatedUserWarning().
showNoConstraintBetweenFixedGeometry()
void showNoConstraintBetweenFixedGeometry (const App::DocumentObject * obj)
Definition at line 177 of file CommandConstraints.cpp.
References Gui::TranslatedUserWarning().
Referenced by CmdSketcherConstrainParallel::activated(), CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainEqual::activated(), CmdSketcherConstrainSymmetric::activated(), CmdSketcherConstrainCoincidentUnified::activatedCoincident(), CmdSketcherConstrainCoincidentUnified::activatedPointOnObject(), CmdSketcherConstrainParallel::applyConstraint(), CmdSketcherConstrainPerpendicular::applyConstraint(), CmdSketcherConstrainTangent::applyConstraint(), CmdSketcherConstrainEqual::applyConstraint(), CmdSketcherConstrainSymmetric::applyConstraint(), CmdSketcherConstrainCoincidentUnified::applyConstraintCoincident(), CmdSketcherConstrainCoincidentUnified::applyConstraintPointOnObject(), and horVerApplyConstraint().
Variable Documentation
constraintCreationMode
ConstraintCreationMode constraintCreationMode = Driving
Definition at line 74 of file CommandConstraints.cpp.
Referenced by CmdSketcherConstrainLock::activated(), CmdSketcherConstrainDistance::activated(), CmdSketcherConstrainDistanceX::activated(), CmdSketcherConstrainDistanceY::activated(), CmdSketcherConstrainRadius::activated(), CmdSketcherConstrainDiameter::activated(), CmdSketcherConstrainRadiam::activated(), CmdSketcherConstrainAngle::activated(), CmdSketcherConstrainLock::applyConstraint(), CmdSketcherConstrainDistance::applyConstraint(), CmdSketcherConstrainDistanceX::applyConstraint(), CmdSketcherConstrainDistanceY::applyConstraint(), CmdSketcherConstrainRadius::applyConstraint(), CmdSketcherConstrainDiameter::applyConstraint(), CmdSketcherConstrainRadiam::applyConstraint(), CmdSketcherConstrainAngle::applyConstraint(), DrawSketchHandlerDimension::finishDimensionCreation(), and SketcherGui::makeAngleBetweenTwoLines().