FreeCAD: Gui::ActionFunction Class Reference
Gui::ActionFunction Class Reference
#include <ActionFunction.h>
Public Member Functions
ActionFunction (QObject *)
Constructor.
~ActionFunction () override
void trigger (QAction *a, std::function< void()> func)
void toggle (QAction *a, std::function< void(bool)> func)
void hover (QAction *a, std::function< void()> func)
Detailed Description
The class connects the triggered() signal of a QAction instance with the method of a usual C++ class not derived from QObject.
The class can e.g be used to fill up the context-menu of the view provider classes.
void MyViewProvider::setupContextMenu(QMenu* menu, QObject* receiver, const char* member)
{
    Gui::ActionFunction* func = new Gui::ActionFunction(menu);
    QAction* a1 = menu->addAction(QObject::tr("Menu item 1..."));
    func->triggered(a1, std::bind(&MyViewProvider::doItem1, this));
    QAction* a2 = menu->addAction(QObject::tr("Menu item 2..."));
    func->triggered(a2, std::bind(&MyViewProvider::doItem2, this));
    QAction* a3 = menu->addAction(QObject::tr("Menu item 3..."));
    func->triggered(a3, std::bind(&MyViewProvider::doItem3, this));
}
Author
Werner Mayer
http://www.boost.org/doc/libs/1_57_0/libs/bind/bind.html#with_boost_function
Definition at line 64 of file ActionFunction.h.
Constructor & Destructor Documentation
ActionFunction()
ActionFunction::ActionFunction (QObject * parent) explicit
Constructor.
Definition at line 48 of file ActionFunction.cpp.
~ActionFunction()
ActionFunction::~ActionFunction () override default
Member Function Documentation
hover()
void ActionFunction::hover (QAction * a, std::function< void()> func)
Definition at line 95 of file ActionFunction.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and draftgeoutils.intersections::connect().
toggle()
void ActionFunction::toggle (QAction * a, std::function< void(bool)> func)
Definition at line 75 of file ActionFunction.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and draftgeoutils.intersections::connect().
Referenced by PartGui::ViewProviderSplineExtension::extensionSetupContextMenu(), and SandboxGui::TaskPanelView::TaskPanelView().
trigger()
void ActionFunction::trigger (QAction * a, std::function< void()> func)
Connects the QAction's triggered() signal with the function func
Definition at line 55 of file ActionFunction.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and draftgeoutils.intersections::connect().
Referenced by Gui::ViewProviderSuppressibleExtension::extensionSetupContextMenu(), PartGui::ViewProviderAttachExtension::extensionSetupContextMenu(), Gui::ViewProviderImagePlane::setupContextMenu(), PartDesignGui::ViewProviderBody::setupContextMenu(), PartDesignGui::ViewProviderShapeBinder::setupContextMenu(), PartGui::ViewProviderPrimitive::setupContextMenu(), FemGui::ViewProviderFemAnalysis::setupContextMenu(), Gui::ViewProviderLink::setupContextMenu(), and SandboxGui::TaskPanelView::TaskPanelView().
The documentation for this class was generated from the following files:
ActionFunction.h
ActionFunction.cpp