FreeCAD: Base::Writer Class Reference
Base::Writer Class Reference abstract
#include <Writer.h>
Classes
struct FileEntry
Public Member Functions
Writer ()
virtual ~Writer ()
void setForceXML (bool on)
switch the writer in XML only mode (no files allowed)
bool isForceXML () const
check on state
void setFileVersion (int)
int getFileVersion () const
virtual void putNextEntry (const char *filename, const char *objName=nullptr)
put the next entry with a give name
void insertAsciiFile (const char *FileName)
insert a file as CDATA section in the XML file
void insertBinFile (const char *FileName)
insert a binary file BASE64 coded as CDATA section in the XML file
void insertText (const std::string &str)
insert text string as CDATA
additional file writing
std::string addFile (const char *Name, const Base::Persistence *Object)
add a write request of a persistent object
virtual void writeFiles ()=0
process the requested file storing
const std::vector< std::string > & getFilenames () const
get all registered file names
void setMode (const std::string &mode)
Set mode.
void setModes (const std::set< std::string > &modes)
Set modes.
bool getMode (const std::string &mode) const
Get mode.
std::set< std::string > getModes () const
Get modes.
void clearMode (const std::string &mode)
Clear mode.
void clearModes ()
Clear modes.
Error handling
void addError (const std::string &)
bool hasErrors () const
void clearErrors ()
std::vector< std::string > getErrors () const
pretty formatting for XML
std::string ObjectName
name for underlying file saves
std::vector< FileEntry > FileList
std::vector< std::string > FileNames
std::vector< std::string > Errors
std::set< std::string > Modes
short indent {0}
char indBuf [1024] {}
bool forceXML {false}
int fileVersion {1}
const char * ind () const
get the current indentation
void incInd ()
increase indentation by one tab
void decInd ()
decrease indentation by one tab
virtual std::ostream & Stream ()=0
std::ostream & beginCharStream (CharStreamFormat format=CharStreamFormat::Raw)
std::ostream & endCharStream ()
std::ostream & charStream ()
Return the current character output stream.
Writer (const Writer &)=delete
Writer (Writer &&)=delete
Writer & operator= (const Writer &)=delete
Writer & operator= (Writer &&)=delete
std::string getUniqueFileName (const char *Name)
Detailed Description
The Writer class This is an important helper class for the store and retrieval system of persistent objects in FreeCAD.
See also
Base::Persistence
Author
Juergen Riegel
Definition at line 77 of file Writer.h.
Constructor & Destructor Documentation
Writer() [1/3]
Writer::Writer ()
Definition at line 84 of file Writer.cpp.
~Writer()
Writer::~Writer () virtual default
Writer() [2/3]
Base::Writer::Writer (const Writer &) delete
Writer() [3/3]
Base::Writer::Writer (Writer &&) delete
Member Function Documentation
addError()
void Writer::addError (const std::string & msg)
Definition at line 224 of file Writer.cpp.
References Path.Op.Surface::msg.
Referenced by Fem::PropertyPostDataObject::SaveDocFile().
addFile()
std::string Writer::addFile (const char * Name, const Base::Persistence * Object)
add a write request of a persistent object
Definition at line 244 of file Writer.cpp.
References Base::Writer::FileEntry::FileName, and Base::Writer::FileEntry::Object.
Referenced by Gui::Thumbnail::Save(), Part::PropertyTopoShapeList::Save(), Path::Toolpath::Save(), App::VRMLObject::Save(), App::PropertyFileIncluded::Save(), Mesh::PropertyNormalList::Save(), Points::PropertyGreyValueList::Save(), Fem::FemMesh::Save(), Part::PropertyPartShape::Save(), Fem::PropertyPostDataObject::Save(), Points::PointKernel::Save(), Points::PropertyNormalList::Save(), Gui::Document::Save(), Mesh::PropertyCurvatureList::Save(), Inspection::PropertyDistanceList::Save(), Mesh::PropertyMaterial::Save(), Points::PropertyCurvatureList::Save(), App::PropertyVectorList::Save(), Part::PropertyFilletEdges::Save(), Mesh::PropertyMeshKernel::Save(), Data::ComplexGeoData::Save(), App::PropertyPlacementList::Save(), App::StringHasher::Save(), App::PropertyFloatList::Save(), App::PropertyColorList::Save(), and App::PropertyMaterialList::Save().
beginCharStream()
std::ostream & Writer::beginCharStream (CharStreamFormat format = CharStreamFormat::Raw)
Create an output stream for storing character content The input is assumed to be valid character with the current XML encoding, and will be enclosed inside CDATA section. The stream will scan the input and properly escape any CDATA ending inside.
Parameters
format If Base64Encoded, the input will be base64 encoded before storing. If Raw, the input is assumed to be valid character with the current XML encoding, and will be enclosed inside CDATA section. The stream will scan the input and properly escape any CDATA ending inside.
Returns
Returns an output stream.
You must call endCharStream() to end the current character stream.
Definition at line 91 of file Writer.cpp.
References Base::base64DefaultBufferSize, Base::Base64Encoded, and Base::create_base64_encoder().
Referenced by Part::PropertyTopoShapeList::Save(), Part::PropertyPartShape::Save(), Data::ComplexGeoData::Save(), and App::StringHasher::Save().
charStream()
std::ostream & Writer::charStream ()
Return the current character output stream.
Definition at line 122 of file Writer.cpp.
clearErrors()
void Writer::clearErrors ()
Definition at line 234 of file Writer.cpp.
clearMode()
void Writer::clearMode (const std::string & mode)
Clear mode.
Definition at line 211 of file Writer.cpp.
clearModes()
void Writer::clearModes ()
Clear modes.
Definition at line 219 of file Writer.cpp.
decInd()
void Writer::decInd ()
decrease indentation by one tab
Definition at line 312 of file Writer.cpp.
References indent.
Referenced by Spreadsheet::PropertySheet::copyCells(), Gui::Document::exportObjects(), Robot::Trajectory::Save(), SketcherGui::PropertyVisualLayerList::Save(), TechDraw::PropertyCenterLineList::Save(), TechDraw::PropertyGeomFormatList::Save(), TechDraw::PropertyCosmeticEdgeList::Save(), TechDraw::PropertyCosmeticVertexList::Save(), Part::PropertyGeometryList::Save(), Part::PropertyTopoShapeList::Save(), Path::Toolpath::Save(), App::PropertyFileIncluded::Save(), TechDraw::CenterLine::Save(), Spreadsheet::PropertySheet::Save(), Points::PropertyGreyValueList::Save(), Spreadsheet::PropertyRowHeights::Save(), Spreadsheet::PropertyColumnWidths::Save(), Part::Geometry::Save(), Sketcher::PropertyConstraintList::Save(), App::PropertyExpressionEngine::Save(), Inspection::PropertyDistanceList::Save(), App::PropertyContainer::Save(), App::PropertyEnumeration::Save(), App::Document::Save(), TechDraw::Generic::Save(), App::PropertyIntegerList::Save(), Part::GeomBSplineCurve::Save(), App::PropertyIntegerSet::Save(), App::PropertyMap::Save(), App::PropertyFloatList::Save(), App::PropertyLinkList::Save(), App::PropertyStringList::Save(), App::PropertyLinkSub::Save(), App::PropertyLinkSubList::Save(), App::PropertyXLink::Save(), App::PropertyPersistentObject::Save(), App::PropertyXLinkSubList::Save(), App::PropertyXLinkContainer::Save(), Gui::Document::SaveDocFile(), saveExpandedItem(), App::ExtensionContainer::saveExtensions(), MeshCore::MeshOutput::SaveXML(), and App::Document::writeObjects().
endCharStream()
std::ostream & Writer::endCharStream ()
End the current character output stream
Returns
Returns the normal writer stream for convenience
Definition at line 111 of file Writer.cpp.
References Base::Raw.
Referenced by Part::PropertyTopoShapeList::Save(), Part::PropertyPartShape::Save(), Data::ComplexGeoData::Save(), and App::StringHasher::Save().
getErrors()
std::vector< std::string > Writer::getErrors () const
Definition at line 239 of file Writer.cpp.
getFilenames()
const std::vector< std::string > & Writer::getFilenames () const
get all registered file names
Definition at line 295 of file Writer.cpp.
getFileVersion()
int Writer::getFileVersion () const
Definition at line 185 of file Writer.cpp.
Referenced by App::Document::Save().
getMode()
bool Writer::getMode (const std::string & mode) const
Get mode.
Definition at line 200 of file Writer.cpp.
Referenced by Part::PropertyTopoShapeList::Save(), Part::PropertyPartShape::Save(), and Part::PropertyPartShape::SaveDocFile().
getModes()
std::set< std::string > Writer::getModes () const
Get modes.
Definition at line 206 of file Writer.cpp.
Referenced by Gui::RecoveryWriter::writeFiles().
getUniqueFileName()
std::string Writer::getUniqueFileName (const char * Name) protected
Definition at line 261 of file Writer.cpp.
References create_qrc::ext, Base::FileInfo::extension(), Base::FileInfo::fileNamePure(), DraftVecUtils::find(), Base::Tools::getUniqueName(), femtools.tokrules::names, RobotExample::pos, Base::FileInfo::setFile(), and Path.Post.scripts.refactored_centroid_post::str.
hasErrors()
bool Writer::hasErrors () const
Definition at line 229 of file Writer.cpp.
Referenced by App::Document::saveToFile().
incInd()
void Writer::incInd ()
increase indentation by one tab
Definition at line 300 of file Writer.cpp.
References indent.
Referenced by Spreadsheet::PropertySheet::copyCells(), Gui::Document::exportObjects(), Robot::Trajectory::Save(), SketcherGui::PropertyVisualLayerList::Save(), TechDraw::PropertyCenterLineList::Save(), TechDraw::PropertyGeomFormatList::Save(), TechDraw::PropertyCosmeticEdgeList::Save(), TechDraw::PropertyCosmeticVertexList::Save(), Part::PropertyGeometryList::Save(), Part::PropertyTopoShapeList::Save(), Path::Toolpath::Save(), App::PropertyFileIncluded::Save(), TechDraw::CenterLine::Save(), Spreadsheet::PropertySheet::Save(), Points::PropertyGreyValueList::Save(), Spreadsheet::PropertyRowHeights::Save(), Spreadsheet::PropertyColumnWidths::Save(), Part::Geometry::Save(), Sketcher::PropertyConstraintList::Save(), App::PropertyExpressionEngine::Save(), Inspection::PropertyDistanceList::Save(), App::PropertyContainer::Save(), App::PropertyEnumeration::Save(), App::Document::Save(), TechDraw::Generic::Save(), App::PropertyIntegerList::Save(), Part::GeomBSplineCurve::Save(), App::PropertyIntegerSet::Save(), App::PropertyMap::Save(), App::PropertyFloatList::Save(), App::PropertyLinkList::Save(), App::PropertyStringList::Save(), App::PropertyLinkSub::Save(), App::PropertyLinkSubList::Save(), App::PropertyXLink::Save(), App::PropertyPersistentObject::Save(), App::PropertyXLinkSubList::Save(), App::PropertyXLinkContainer::Save(), Gui::Document::SaveDocFile(), saveExpandedItem(), App::ExtensionContainer::saveExtensions(), MeshCore::MeshOutput::SaveXML(), and App::Document::writeObjects().
ind()
const char* Base::Writer::ind () const inline
get the current indentation
Definition at line 134 of file Writer.h.
Referenced by Spreadsheet::PropertySheet::copyCells(), Gui::Document::exportObjects(), Sketcher::SketchGeometryExtension::postSave(), Robot::Trajectory::Save(), SketcherGui::VisualLayer::Save(), App::PropertyPythonObject::Save(), SketcherGui::PropertyVisualLayerList::Save(), TechDraw::CosmeticVertex::Save(), TechDraw::PropertyCenterLineList::Save(), TechDraw::CosmeticEdge::Save(), Materials::PropertyMaterial::Save(), TechDraw::PropertyGeomFormatList::Save(), App::PropertyInteger::Save(), TechDraw::PropertyCosmeticEdgeList::Save(), TechDraw::PropertyCosmeticVertexList::Save(), Robot::Robot6Axis::Save(), Part::PropertyGeometryList::Save(), Part::PropertyTopoShapeList::Save(), Path::Command::Save(), Path::Toolpath::Save(), App::PropertyVector::Save(), Part::GeometryPersistenceExtension::Save(), App::PropertyFileIncluded::Save(), Spreadsheet::PropertySheet::Save(), TechDraw::CenterLine::Save(), Spreadsheet::PropertyRowHeights::Save(), Mesh::PropertyNormalList::Save(), Points::PropertyGreyValueList::Save(), Spreadsheet::PropertyColumnWidths::Save(), TechDraw::BaseGeom::Save(), Fem::FemMesh::Save(), Robot::Waypoint::Save(), Part::PropertyPartShape::Save(), Part::Geom2dPoint::Save(), Fem::PropertyPostDataObject::Save(), TechDraw::GeomFormat::Save(), Part::Geometry::Save(), Spreadsheet::Cell::save(), Sketcher::PropertyConstraintList::Save(), App::PropertyExpressionEngine::Save(), Sketcher::Constraint::Save(), App::PropertyPath::Save(), Points::PointKernel::Save(), Points::PropertyNormalList::Save(), Mesh::PropertyCurvatureList::Save(), Part::GeomPoint::Save(), TechDraw::Circle::Save(), Inspection::PropertyDistanceList::Save(), App::PropertyContainer::Save(), Mesh::PropertyMaterial::Save(), App::PropertyVectorList::Save(), Points::PropertyCurvatureList::Save(), App::PropertyEnumeration::Save(), TechDraw::AOC::Save(), Part::PropertyFilletEdges::Save(), Part::Geom2dCircle::Save(), App::PropertyMatrix::Save(), Part::Geom2dArcOfCircle::Save(), TechDraw::Generic::Save(), Gui::DocumentItem::Save(), Mesh::PropertyMeshKernel::Save(), Part::Geom2dEllipse::Save(), App::PropertyPlacement::Save(), TechDraw::Vertex::Save(), Part::Geom2dArcOfEllipse::Save(), Data::ComplexGeoData::Save(), App::PropertyIntegerList::Save(), Part::GeomBSplineCurve::Save(), Part::Geom2dHyperbola::Save(), Part::Geom2dArcOfHyperbola::Save(), App::PropertyPlacementList::Save(), App::PropertyIntegerSet::Save(), Part::Geom2dParabola::Save(), Part::Geom2dArcOfParabola::Save(), App::PropertyRotation::Save(), App::PropertyMap::Save(), Part::Geom2dLineSegment::Save(), Part::GeomCircle::Save(), App::PropertyFloat::Save(), Part::GeomArcOfCircle::Save(), Part::GeomEllipse::Save(), App::StringHasher::Save(), Part::GeomArcOfEllipse::Save(), Part::GeomHyperbola::Save(), App::PropertyLink::Save(), App::PropertyFloatList::Save(), Part::GeomArcOfHyperbola::Save(), Part::GeomParabola::Save(), App::PropertyString::Save(), Part::GeomArcOfParabola::Save(), App::PropertyLinkList::Save(), Part::GeomLine::Save(), App::PropertyUUID::Save(), Part::GeomLineSegment::Save(), App::PropertyStringList::Save(), App::PropertyBool::Save(), App::PropertyLinkSub::Save(), App::PropertyBoolList::Save(), App::PropertyColor::Save(), App::PropertyColorList::Save(), App::PropertyLinkSubList::Save(), App::PropertyMaterial::Save(), App::PropertyMaterialList::Save(), App::PropertyXLink::Save(), App::PropertyPersistentObject::Save(), App::PropertyXLinkSubList::Save(), App::PropertyXLinkContainer::Save(), saveCenter(), Gui::Document::SaveDocFile(), saveExpandedItem(), App::ExtensionContainer::saveExtensions(), MeshCore::MeshOutput::SaveXML(), and App::Document::writeObjects().
insertAsciiFile()
void Writer::insertAsciiFile (const char * FileName)
insert a file as CDATA section in the XML file
Definition at line 136 of file Writer.cpp.
insertBinFile()
void Writer::insertBinFile (const char * FileName)
insert a binary file BASE64 coded as CDATA section in the XML file
Definition at line 152 of file Writer.cpp.
References Base::base64_encode().
Referenced by App::PropertyFileIncluded::Save().
insertText()
void Writer::insertText (const std::string & str)
insert text string as CDATA
Definition at line 130 of file Writer.cpp.
References Path.Post.scripts.refactored_centroid_post::str.
isForceXML()
bool Writer::isForceXML () const
check on state
Definition at line 175 of file Writer.cpp.
Referenced by Gui::Document::exportObjects(), Gui::Thumbnail::Save(), Part::PropertyTopoShapeList::Save(), Path::Toolpath::Save(), App::PropertyFileIncluded::Save(), Points::PropertyGreyValueList::Save(), Mesh::PropertyNormalList::Save(), Fem::FemMesh::Save(), Part::PropertyPartShape::Save(), Fem::PropertyPostDataObject::Save(), Points::PointKernel::Save(), Gui::Document::Save(), Points::PropertyNormalList::Save(), Mesh::PropertyCurvatureList::Save(), Inspection::PropertyDistanceList::Save(), Mesh::PropertyMaterial::Save(), App::PropertyVectorList::Save(), Points::PropertyCurvatureList::Save(), Part::PropertyFilletEdges::Save(), Mesh::PropertyMeshKernel::Save(), App::PropertyPlacementList::Save(), App::PropertyFloatList::Save(), App::PropertyColorList::Save(), App::PropertyMaterialList::Save(), and Gui::Document::SaveDocFile().
operator=() [1/2]
Writer& Base::Writer::operator= (const Writer &) delete
operator=() [2/2]
Writer& Base::Writer::operator= (Writer &&) delete
putNextEntry()
void Writer::putNextEntry (const char * filename, const char * objName = nullptr) virtual
put the next entry with a give name
Reimplemented in Base::FileWriter, and Base::ZipWriter.
Definition at line 323 of file Writer.cpp.
References DrawingExample::file.
Referenced by Base::ZipWriter::putNextEntry(), and Base::FileWriter::putNextEntry().
setFileVersion()
void Writer::setFileVersion (int version)
Definition at line 180 of file Writer.cpp.
References Dice3DS::version.
setForceXML()
void Writer::setForceXML (bool on)
switch the writer in XML only mode (no files allowed)
Definition at line 170 of file Writer.cpp.
Referenced by Gui::Document::exportObjects(), and Gui::Document::SaveDocFile().
setMode()
void Writer::setMode (const std::string & mode)
Set mode.
Definition at line 190 of file Writer.cpp.
Referenced by Cloud::Module::cloudSave(), Base::Persistence::dumpToStream(), Gui::AutoSaver::saveDocument(), and App::Document::saveToFile().
setModes()
void Writer::setModes (const std::set< std::string > & modes)
Set modes.
Definition at line 195 of file Writer.cpp.
References modes.
Referenced by Gui::RecoveryRunnable::RecoveryRunnable().
Stream()
virtual std::ostream& Base::Writer::Stream () pure virtual
Implemented in Cloud::CloudWriter, Base::FileWriter, Base::StringWriter, and Base::ZipWriter.
Referenced by Spreadsheet::PropertySheet::copyCells(), Gui::Document::exportObjects(), Sketcher::SketchGeometryExtension::postSave(), Sketcher::ExternalGeometryExtension::preSave(), Sketcher::SketchGeometryExtension::preSave(), Robot::Trajectory::Save(), SketcherGui::VisualLayer::Save(), App::PropertyPythonObject::Save(), SketcherGui::PropertyVisualLayerList::Save(), TechDraw::CosmeticVertex::Save(), TechDraw::PropertyCenterLineList::Save(), TechDraw::CosmeticEdge::Save(), Materials::PropertyMaterial::Save(), TechDraw::PropertyGeomFormatList::Save(), App::PropertyInteger::Save(), TechDraw::PropertyCosmeticEdgeList::Save(), TechDraw::PropertyCosmeticVertexList::Save(), Robot::Robot6Axis::Save(), Part::PropertyGeometryList::Save(), Part::PropertyTopoShapeList::Save(), Path::Command::Save(), Path::Toolpath::Save(), App::PropertyVector::Save(), Part::GeometryPersistenceExtension::Save(), App::PropertyFileIncluded::Save(), Spreadsheet::PropertySheet::Save(), TechDraw::CenterLine::Save(), Points::PropertyGreyValueList::Save(), Spreadsheet::PropertyColumnWidths::Save(), Spreadsheet::PropertyRowHeights::Save(), Mesh::PropertyNormalList::Save(), TechDraw::BaseGeom::Save(), Robot::Waypoint::Save(), Fem::FemMesh::Save(), Part::PropertyPartShape::Save(), Part::Geom2dPoint::Save(), Fem::PropertyPostDataObject::Save(), TechDraw::GeomFormat::Save(), Part::Geometry::Save(), Spreadsheet::Cell::save(), Sketcher::PropertyConstraintList::Save(), App::PropertyExpressionEngine::Save(), Sketcher::Constraint::Save(), App::PropertyPath::Save(), Points::PointKernel::Save(), Points::PropertyNormalList::Save(), App::DynamicProperty::save(), Mesh::PropertyCurvatureList::Save(), Part::GeomPoint::Save(), TechDraw::Circle::Save(), Inspection::PropertyDistanceList::Save(), App::PropertyContainer::Save(), Mesh::PropertyMaterial::Save(), Points::PropertyCurvatureList::Save(), App::PropertyVectorList::Save(), App::PropertyEnumeration::Save(), App::Document::Save(), TechDraw::AOC::Save(), Part::PropertyFilletEdges::Save(), Part::Geom2dCircle::Save(), App::PropertyMatrix::Save(), Part::Geom2dArcOfCircle::Save(), TechDraw::Generic::Save(), Gui::DocumentItem::Save(), Mesh::PropertyMeshKernel::Save(), Part::Geom2dEllipse::Save(), App::PropertyPlacement::Save(), TechDraw::Vertex::Save(), Part::Geom2dArcOfEllipse::Save(), Data::ComplexGeoData::Save(), App::PropertyIntegerList::Save(), Part::GeomBSplineCurve::Save(), Part::Geom2dHyperbola::Save(), Part::Geom2dArcOfHyperbola::Save(), App::PropertyPlacementList::Save(), App::PropertyIntegerSet::Save(), Part::Geom2dParabola::Save(), Part::Geom2dArcOfParabola::Save(), App::PropertyRotation::Save(), App::PropertyMap::Save(), Part::Geom2dLineSegment::Save(), Part::GeomCircle::Save(), App::PropertyFloat::Save(), Part::GeomArcOfCircle::Save(), Part::GeomEllipse::Save(), App::StringHasher::Save(), Part::GeomArcOfEllipse::Save(), Part::GeomHyperbola::Save(), App::PropertyLink::Save(), App::PropertyFloatList::Save(), Part::GeomArcOfHyperbola::Save(), Part::GeomParabola::Save(), App::PropertyString::Save(), Part::GeomArcOfParabola::Save(), App::PropertyLinkList::Save(), Part::GeomLine::Save(), App::PropertyUUID::Save(), Part::GeomLineSegment::Save(), App::PropertyStringList::Save(), App::PropertyBool::Save(), App::PropertyLinkSub::Save(), App::PropertyBoolList::Save(), App::PropertyColor::Save(), App::PropertyColorList::Save(), App::PropertyLinkSubList::Save(), App::PropertyMaterial::Save(), App::PropertyMaterialList::Save(), App::PropertyXLink::Save(), App::PropertyPersistentObject::Save(), App::PropertyXLinkSubList::Save(), App::PropertyXLinkContainer::Save(), Part::GeometryDefaultExtension< T >::saveAttributes(), Part::GeometryPersistenceExtension::saveAttributes(), SketcherGui::ViewProviderSketchGeometryExtension::saveAttributes(), Sketcher::ExternalGeometryExtension::saveAttributes(), Sketcher::SketchGeometryExtension::saveAttributes(), Part::Geom2dConic::SaveAxis(), Part::Geom2dArcOfConic::SaveAxis(), saveCenter(), Gui::Thumbnail::SaveDocFile(), App::PropertyPythonObject::SaveDocFile(), Part::PropertyTopoShapeList::SaveDocFile(), Path::Toolpath::SaveDocFile(), App::VRMLObject::SaveDocFile(), App::PropertyFileIncluded::SaveDocFile(), Mesh::PropertyNormalList::SaveDocFile(), Points::PropertyGreyValueList::SaveDocFile(), Fem::FemMesh::SaveDocFile(), Part::PropertyPartShape::SaveDocFile(), Fem::PropertyPostDataObject::SaveDocFile(), Points::PointKernel::SaveDocFile(), Points::PropertyNormalList::SaveDocFile(), Gui::Document::SaveDocFile(), Mesh::PropertyCurvatureList::SaveDocFile(), Mesh::MeshObject::SaveDocFile(), Inspection::PropertyDistanceList::SaveDocFile(), Mesh::PropertyMaterial::SaveDocFile(), App::PropertyVectorList::SaveDocFile(), Points::PropertyCurvatureList::SaveDocFile(), Part::PropertyFilletEdges::SaveDocFile(), Mesh::PropertyMeshKernel::SaveDocFile(), Data::ComplexGeoData::SaveDocFile(), App::PropertyPlacementList::SaveDocFile(), App::StringHasher::SaveDocFile(), App::PropertyFloatList::SaveDocFile(), App::PropertyColorList::SaveDocFile(), App::PropertyMaterialList::SaveDocFile(), saveExpandedItem(), App::ExtensionContainer::saveExtensions(), MeshCore::MeshOutput::SaveXML(), and App::Document::writeObjects().
writeFiles()
virtual void Base::Writer::writeFiles () pure virtual
process the requested file storing
Implemented in Cloud::CloudWriter, Base::FileWriter, Base::StringWriter, Base::ZipWriter, and Gui::RecoveryWriter.
Member Data Documentation
Errors
std::vector<std::string> Base::Writer::Errors protected
Definition at line 182 of file Writer.h.
FileList
std::vector<FileEntry> Base::Writer::FileList protected
Definition at line 180 of file Writer.h.
Referenced by Gui::RecoveryWriter::writeFiles(), Base::ZipWriter::writeFiles(), and Base::FileWriter::writeFiles().
FileNames
std::vector<std::string> Base::Writer::FileNames protected
Definition at line 181 of file Writer.h.
fileVersion
int Base::Writer::fileVersion {1} protected
Definition at line 189 of file Writer.h.
forceXML
bool Base::Writer::forceXML {false} protected
Definition at line 188 of file Writer.h.
indBuf
char Base::Writer::indBuf[1024] {} protected
Definition at line 186 of file Writer.h.
Referenced by Base::ZipWriter::writeFiles(), and Base::FileWriter::writeFiles().
indent
short Base::Writer::indent {0} protected
Definition at line 185 of file Writer.h.
Referenced by Base::ZipWriter::writeFiles(), and Base::FileWriter::writeFiles().
Modes
std::set<std::string> Base::Writer::Modes protected
Definition at line 183 of file Writer.h.
ObjectName
std::string Base::Writer::ObjectName
name for underlying file saves
Definition at line 171 of file Writer.h.
Referenced by Path::Toolpath::Save(), Points::PointKernel::Save(), and Part::PropertyTopoShapeList::SaveDocFile().
The documentation for this class was generated from the following files:
Writer.h
Writer.cpp