FreeCAD: src.Mod.AddonManager.AddonManagerTest.app.test_freecad_interface.TestConsole Class Reference
src.Mod.AddonManager.AddonManagerTest.app.test_freecad_interface.TestConsole Class Reference
Public Member Functions
None setUp (self)
None tearDown (self)
def test_log_with_freecad (self)
def test_log_no_freecad (self)
def test_message_no_freecad (self)
def test_warning_no_freecad (self)
def test_error_no_freecad (self)
Public Attributes
saved_freecad
Detailed Description
Tests for the Console
Definition at line 36 of file test_freecad_interface.py.
Member Function Documentation
setUp()
None src.Mod.AddonManager.AddonManagerTest.app.test_freecad_interface.TestConsole.setUp (self)
Definition at line 39 of file test_freecad_interface.py.
tearDown()
None src.Mod.AddonManager.AddonManagerTest.app.test_freecad_interface.TestConsole.tearDown (self)
Definition at line 48 of file test_freecad_interface.py.
References src.Mod.AddonManager.AddonManagerTest.app.test_freecad_interface.TestConsole.saved_freecad.
Referenced by CAMTests.TestPathHelix.TestPathHelix.test03(), CAMTests.TestPathHelix.TestPathHelix.test04(), and CAMTests.TestPathHelix.TestPathHelix.testRecomputeHelixFromV021().
test_error_no_freecad()
def src.Mod.AddonManager.AddonManagerTest.app.test_freecad_interface.TestConsole.test_error_no_freecad (self)
Test that if the FreeCAD import fails the logger implements PrintError
Definition at line 92 of file test_freecad_interface.py.
test_log_no_freecad()
def src.Mod.AddonManager.AddonManagerTest.app.test_freecad_interface.TestConsole.test_log_no_freecad (self)
Test that if the FreeCAD import fails, the logger is set up correctly, and
implements PrintLog
Definition at line 63 of file test_freecad_interface.py.
test_log_with_freecad()
def src.Mod.AddonManager.AddonManagerTest.app.test_freecad_interface.TestConsole.test_log_with_freecad (self)
Ensure that if FreeCAD exists, the appropriate function is called
Definition at line 54 of file test_freecad_interface.py.
test_message_no_freecad()
def src.Mod.AddonManager.AddonManagerTest.app.test_freecad_interface.TestConsole.test_message_no_freecad (self)
Test that if the FreeCAD import fails the logger implements PrintMessage
Definition at line 74 of file test_freecad_interface.py.
test_warning_no_freecad()
def src.Mod.AddonManager.AddonManagerTest.app.test_freecad_interface.TestConsole.test_warning_no_freecad (self)
Test that if the FreeCAD import fails the logger implements PrintWarning
Definition at line 83 of file test_freecad_interface.py.
Member Data Documentation
saved_freecad
src.Mod.AddonManager.AddonManagerTest.app.test_freecad_interface.TestConsole.saved_freecad
Definition at line 40 of file test_freecad_interface.py.
Referenced by src.Mod.AddonManager.AddonManagerTest.app.test_freecad_interface.TestConsole.tearDown(), src.Mod.AddonManager.AddonManagerTest.app.test_freecad_interface.TestParameters.tearDown(), and src.Mod.AddonManager.AddonManagerTest.app.test_freecad_interface.TestDataPaths.tearDown().
The documentation for this class was generated from the following file:
test_freecad_interface.py