FreeCAD: ifc2x3.ifcstructuralloadsingleforce Class Reference
ifc2x3.ifcstructuralloadsingleforce Class Reference
Public Member Functions
def __init__ (self, inherited0__name, forcex, forcey, forcez, momentx, momenty, momentz)
def forcex ()
def forcey ()
def forcez ()
def momentx ()
def momenty ()
def momentz ()
Public Member Functions inherited from ifc2x3.ifcstructuralloadstatic
def __init__ (self, inherited0__name)
Public Member Functions inherited from ifc2x3.ifcstructuralload
def name ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
forcex
forcey
forcez
momentx
momenty
momentz
Public Attributes inherited from ifc2x3.ifcstructuralload
name
Detailed Description
Entity ifcstructuralloadsingleforce definition.
:param forcex
:type forcex:ifcforcemeasure
:param forcey
:type forcey:ifcforcemeasure
:param forcez
:type forcez:ifcforcemeasure
:param momentx
:type momentx:ifctorquemeasure
:param momenty
:type momenty:ifctorquemeasure
:param momentz
:type momentz:ifctorquemeasure
Definition at line 8582 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcstructuralloadsingleforce.__init__ (self, inherited0__name, forcex, forcey, forcez, momentx, momenty, momentz)
Definition at line 8603 of file ifc2x3.py.
Member Function Documentation
forcex()
def ifc2x3.ifcstructuralloadsingleforce.forcex ()
Definition at line 8613 of file ifc2x3.py.
References ifc2x3.ifcstructuralloadsingleforce._forcex, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralloadsingleforce.forcex.
forcey()
def ifc2x3.ifcstructuralloadsingleforce.forcey ()
Definition at line 8627 of file ifc2x3.py.
References ifc2x3.ifcstructuralloadsingleforce._forcey, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralloadsingleforce.forcey.
forcez()
def ifc2x3.ifcstructuralloadsingleforce.forcez ()
Definition at line 8641 of file ifc2x3.py.
References ifc2x3.ifcstructuralloadsingleforce._forcez, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralloadsingleforce.forcez.
momentx()
def ifc2x3.ifcstructuralloadsingleforce.momentx ()
Definition at line 8655 of file ifc2x3.py.
References ifc2x3.ifcstructuralloadsingleforce._momentx, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralloadsingleforce.momentx.
momenty()
def ifc2x3.ifcstructuralloadsingleforce.momenty ()
Definition at line 8669 of file ifc2x3.py.
References ifc2x3.ifcstructuralloadsingleforce._momenty, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralloadsingleforce.momenty.
momentz()
def ifc2x3.ifcstructuralloadsingleforce.momentz ()
Definition at line 8683 of file ifc2x3.py.
References ifc2x3.ifcstructuralloadsingleforce._momentz, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralloadsingleforce.momentz.
Member Data Documentation
forcex
ifc2x3.ifcstructuralloadsingleforce.forcex
Definition at line 8605 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralloadsingleforce.forcex().
forcey
ifc2x3.ifcstructuralloadsingleforce.forcey
Definition at line 8606 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralloadsingleforce.forcey().
forcez
ifc2x3.ifcstructuralloadsingleforce.forcez
Definition at line 8607 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralloadsingleforce.forcez().
momentx
ifc2x3.ifcstructuralloadsingleforce.momentx
Definition at line 8608 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralloadsingleforce.momentx().
momenty
ifc2x3.ifcstructuralloadsingleforce.momenty
Definition at line 8609 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralloadsingleforce.momenty().
momentz
ifc2x3.ifcstructuralloadsingleforce.momentz
Definition at line 8610 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralloadsingleforce.momentz().
The documentation for this class was generated from the following file:
ifc2x3.py