FreeCAD: Geometry2d.cpp File Reference
Geometry2d.cpp File Reference
#include "PreCompiled.h"
#include <BRepBuilderAPI_MakeEdge2d.hxx>
#include <BRepBuilderAPI_MakeVertex.hxx>
#include <Geom2dAPI_Interpolate.hxx>
#include <Geom2dAPI_ProjectPointOnCurve.hxx>
#include <Geom2dConvert.hxx>
#include <Geom2dConvert_CompCurveToBSplineCurve.hxx>
#include <Geom2dLProp_CLProps2d.hxx>
#include <gce_ErrorType.hxx>
#include <gp_Ax22d.hxx>
#include <gp_Circ2d.hxx>
#include <gp_Elips2d.hxx>
#include <gp_Hypr2d.hxx>
#include <gp_Lin2d.hxx>
#include <gp_Parab2d.hxx>
#include <Standard_ConstructionError.hxx>
#include <Standard_Version.hxx>
#include <TColgp_Array1OfPnt2d.hxx>
#include <TColgp_Array1OfVec2d.hxx>
#include <TColgp_HArray1OfPnt2d.hxx>
#include <TColStd_Array1OfInteger.hxx>
#include <TColStd_Array1OfReal.hxx>
#include <TColStd_HArray1OfBoolean.hxx>
#include <GCE2d_MakeArcOfCircle.hxx>
#include <GCE2d_MakeArcOfEllipse.hxx>
#include <GCE2d_MakeArcOfHyperbola.hxx>
#include <GCE2d_MakeArcOfParabola.hxx>
#include <GCE2d_MakeCircle.hxx>
#include <GCE2d_MakeEllipse.hxx>
#include <GCE2d_MakeHyperbola.hxx>
#include <GCE2d_MakeLine.hxx>
#include <GCE2d_MakeParabola.hxx>
#include <GCE2d_MakeSegment.hxx>
#include <Precision.hxx>
#include <Base/Exception.h>
#include <Base/Reader.h>
#include <Base/Writer.h>
#include "Geometry2d.h"
#include <Geom2d/ArcOfCircle2dPy.h>
#include <Geom2d/ArcOfEllipse2dPy.h>
#include <Geom2d/ArcOfHyperbola2dPy.h>
#include <Geom2d/ArcOfParabola2dPy.h>
#include <Geom2d/BezierCurve2dPy.h>
#include <Geom2d/BSplineCurve2dPy.h>
#include <Geom2d/Circle2dPy.h>
#include <Geom2d/Ellipse2dPy.h>
#include <Geom2d/Hyperbola2dPy.h>
#include <Geom2d/Line2dSegmentPy.h>
#include <Geom2d/Line2dPy.h>
#include <Geom2d/OffsetCurve2dPy.h>
#include <Geom2d/Parabola2dPy.h>
Namespaces
Part
Functions
const char * gce_ErrorStatusText (gce_ErrorType et)
const Handle (Geom2d_Geometry) &Geom2dPoint
std::unique_ptr< Geom2dCurve > Part::makeFromCurve2d (Handle(Geom2d_Curve) curve)
std::unique_ptr< Geom2dCurve > Part::makeFromTrimmedCurve2d (const Handle(Geom2d_Curve)&c, double f, double l)
std::unique_ptr< Geom2dCurve > Part::makeFromCurveAdaptor2d (const Adaptor2d_Curve2d &adapt)
Function Documentation
gce_ErrorStatusText()
const char* gce_ErrorStatusText (gce_ErrorType et)
Definition at line 162 of file Part/App/Geometry.cpp.
Referenced by Part::Geom2dCircle::Restore(), Part::Geom2dArcOfCircle::Restore(), Part::Geom2dEllipse::Restore(), Part::Geom2dArcOfEllipse::Restore(), Part::Geom2dHyperbola::Restore(), Part::Geom2dArcOfHyperbola::Restore(), Part::Geom2dParabola::Restore(), Part::Geom2dArcOfParabola::Restore(), and Part::Geom2dLineSegment::Restore().
Handle()
const Handle (Geom2d_Geometry) &
Definition at line 140 of file Geometry2d.cpp.
Referenced by Part::Geom2dCurve::closestParameter(), Part::Geom2dCurve::closestParameterToBasicCurve(), Part::Geom2dCurve::firstDerivativeAtParameter(), Part::Geom2dArcOfCircle::Geom2dArcOfCircle(), Part::Geom2dArcOfEllipse::Geom2dArcOfEllipse(), Part::Geom2dArcOfHyperbola::Geom2dArcOfHyperbola(), Part::Geom2dArcOfParabola::Geom2dArcOfParabola(), Part::Geom2dBezierCurve::Geom2dBezierCurve(), Part::Geom2dBSplineCurve::Geom2dBSplineCurve(), Part::Geom2dCircle::Geom2dCircle(), Part::Geom2dEllipse::Geom2dEllipse(), Part::Geom2dHyperbola::Geom2dHyperbola(), Part::Geom2dLine::Geom2dLine(), Part::Geom2dLineSegment::Geom2dLineSegment(), Part::Geom2dOffsetCurve::Geom2dOffsetCurve(), Part::Geom2dParabola::Geom2dParabola(), Part::Geom2dPoint::Geom2dPoint(), Part::Geom2dTrimmedCurve::Geom2dTrimmedCurve(), Part::Geom2dArcOfConic::getEndPoint(), Part::Geom2dConic::getLocation(), Part::Geom2dArcOfConic::getLocation(), Part::Geom2dArcOfEllipse::getMajorAxisDir(), Part::Geom2dEllipse::getMinorRadius(), Part::Geom2dArcOfEllipse::getMinorRadius(), Part::Geom2dHyperbola::getMinorRadius(), Part::Geom2dArcOfHyperbola::getMinorRadius(), Part::Geom2dPoint::getPyObject(), Part::Geom2dTrimmedCurve::getPyObject(), Part::Geom2dArcOfConic::getRange(), Part::Geom2dArcOfConic::getStartPoint(), Part::Geom2dBSplineCurve::interpolate(), Part::Geom2dConic::isReversed(), Part::Geom2dArcOfConic::isReversed(), Part::makeFromCurve2d(), Part::makeFromCurveAdaptor2d(), Part::makeFromTrimmedCurve2d(), Part::Geom2dCurve::normal(), Part::Geom2dCurve::pointAtParameter(), Part::Geom2dArcOfCircle::Restore(), Part::Geom2dArcOfEllipse::Restore(), Part::Geom2dArcOfHyperbola::Restore(), Part::Geom2dArcOfParabola::Restore(), Part::Geom2dCircle::Save(), Part::Geom2dArcOfCircle::Save(), Part::Geom2dArcOfEllipse::Save(), Part::Geom2dArcOfHyperbola::Save(), Part::Geom2dArcOfParabola::Save(), Part::Geom2dCurve::secondDerivativeAtParameter(), Part::Geom2dBezierCurve::setHandle(), Part::Geom2dBSplineCurve::setHandle(), Part::Geom2dArcOfCircle::setHandle(), Part::Geom2dEllipse::setHandle(), Part::Geom2dArcOfEllipse::setHandle(), Part::Geom2dArcOfHyperbola::setHandle(), Part::Geom2dArcOfParabola::setHandle(), Part::Geom2dLineSegment::setHandle(), Part::Geom2dOffsetCurve::setHandle(), Part::Geom2dTrimmedCurve::setHandle(), Part::Geom2dConic::setLocation(), Part::Geom2dArcOfConic::setLocation(), Part::Geom2dArcOfEllipse::setMajorAxisDir(), Part::Geom2dEllipse::setMinorRadius(), Part::Geom2dArcOfEllipse::setMinorRadius(), Part::Geom2dHyperbola::setMinorRadius(), Part::Geom2dArcOfHyperbola::setMinorRadius(), Part::Geom2dArcOfConic::setRange(), Part::Geom2dCurve::tangent(), Part::Geom2dPoint::toShape(), and Part::Geom2dCurve::toShape().