FreeCAD: Gui::Dialog::Clipping Class Reference
Gui::Dialog::Clipping Class Reference
#include <Clipping.h>
Classes
class Private
Public Member Functions
Clipping (Gui::View3DInventor *view, QWidget *parent=nullptr)
~Clipping () override
void reject () override
Static Public Member Functions
static Clipping * makeDockWidget (Gui::View3DInventor *)
Protected Member Functions
void setupConnections ()
void onGroupBoxXToggled (bool)
void onGroupBoxYToggled (bool)
void onGroupBoxZToggled (bool)
void onClipXValueChanged (double)
void onClipYValueChanged (double)
void onClipZValueChanged (double)
void onFlipClipXClicked ()
void onFlipClipYClicked ()
void onFlipClipZClicked ()
void onGroupBoxViewToggled (bool)
void onClipViewValueChanged (double)
void onFromViewClicked ()
void onAdjustViewdirectionToggled (bool)
void onDirXValueChanged (double)
void onDirYValueChanged (double)
void onDirZValueChanged (double)
Detailed Description
Author
Werner Mayer
Definition at line 57 of file Clipping.h.
Constructor & Destructor Documentation
Clipping()
Clipping::Clipping (Gui::View3DInventor * view, QWidget * parent = nullptr)
Definition at line 104 of file Clipping.cpp.
References Path.Post.scripts.dynapath_4060_post::action, MengerSponge::box, Gui::Dialog::Clipping::Private::clipView, Gui::Dialog::Clipping::Private::clipX, Gui::Dialog::Clipping::Private::clipY, Gui::Dialog::Clipping::Private::clipZ, SCL.SimpleDataTypes::f, Gui::View3DInventor::getViewer(), KDL::max(), Gui::Dialog::Clipping::Private::node, Base::pow(), setupConnections(), Gui::Dialog::Clipping::Private::ui, Gui::Dialog::Clipping::Private::view, and OfflineRenderingUtils::viewer().
Referenced by makeDockWidget().
~Clipping()
Clipping::~Clipping () override
Destroys the object and frees any allocated resources
Definition at line 203 of file Clipping.cpp.
References Gui::Dialog::Clipping::Private::clipView, Gui::Dialog::Clipping::Private::clipX, Gui::Dialog::Clipping::Private::clipY, Gui::Dialog::Clipping::Private::clipZ, and Gui::Dialog::Clipping::Private::node.
Member Function Documentation
makeDockWidget()
Clipping * Clipping::makeDockWidget (Gui::View3DInventor * view) static
Definition at line 190 of file Clipping.cpp.
References Gui::DockWindowManager::addDockWindow(), Clipping(), and Gui::DockWindowManager::instance().
Referenced by StdCmdToggleClipPlane::activated().
onAdjustViewdirectionToggled()
void Clipping::onAdjustViewdirectionToggled (bool on) protected
Definition at line 353 of file Clipping.cpp.
References Gui::Dialog::Clipping::Private::sensor, and Gui::Dialog::Clipping::Private::ui.
Referenced by setupConnections().
onClipViewValueChanged()
void Clipping::onClipViewValueChanged (double val) protected
Definition at line 337 of file Clipping.cpp.
References Gui::Dialog::Clipping::Private::clipView, and toolbit-attributes::val.
Referenced by setupConnections().
onClipXValueChanged()
void Clipping::onClipXValueChanged (double val) protected
Definition at line 287 of file Clipping.cpp.
References Gui::Dialog::Clipping::Private::clipX, Gui::Dialog::Clipping::Private::flipX, and toolbit-attributes::val.
Referenced by setupConnections().
onClipYValueChanged()
void Clipping::onClipYValueChanged (double val) protected
Definition at line 293 of file Clipping.cpp.
References Gui::Dialog::Clipping::Private::clipY, Gui::Dialog::Clipping::Private::flipY, and toolbit-attributes::val.
Referenced by setupConnections().
onClipZValueChanged()
void Clipping::onClipZValueChanged (double val) protected
Definition at line 299 of file Clipping.cpp.
References Gui::Dialog::Clipping::Private::clipZ, Gui::Dialog::Clipping::Private::flipZ, and toolbit-attributes::val.
Referenced by setupConnections().
onDirXValueChanged()
void Clipping::onDirXValueChanged (double) protected
Definition at line 368 of file Clipping.cpp.
References Gui::Dialog::Clipping::Private::clipView, Gui::Dialog::Clipping::Private::ui, MovieTool::x, and MovieTool::y.
Referenced by setupConnections().
onDirYValueChanged()
void Clipping::onDirYValueChanged (double) protected
Definition at line 381 of file Clipping.cpp.
References Gui::Dialog::Clipping::Private::clipView, Gui::Dialog::Clipping::Private::ui, MovieTool::x, and MovieTool::y.
Referenced by setupConnections().
onDirZValueChanged()
void Clipping::onDirZValueChanged (double) protected
Definition at line 394 of file Clipping.cpp.
References Gui::Dialog::Clipping::Private::clipView, Gui::Dialog::Clipping::Private::ui, MovieTool::x, and MovieTool::y.
Referenced by setupConnections().
onFlipClipXClicked()
void Clipping::onFlipClipXClicked () protected
Definition at line 305 of file Clipping.cpp.
References Gui::Dialog::Clipping::Private::clipX, and Gui::Dialog::Clipping::Private::flipX.
Referenced by setupConnections().
onFlipClipYClicked()
void Clipping::onFlipClipYClicked () protected
Definition at line 312 of file Clipping.cpp.
References Gui::Dialog::Clipping::Private::clipY, and Gui::Dialog::Clipping::Private::flipY.
Referenced by setupConnections().
onFlipClipZClicked()
void Clipping::onFlipClipZClicked () protected
Definition at line 319 of file Clipping.cpp.
References Gui::Dialog::Clipping::Private::clipZ, and Gui::Dialog::Clipping::Private::flipZ.
Referenced by setupConnections().
onFromViewClicked()
void Clipping::onFromViewClicked () protected
Definition at line 343 of file Clipping.cpp.
References Gui::Dialog::Clipping::Private::clipView, Gui::View3DInventorViewer::getViewDirection(), and Gui::Dialog::Clipping::Private::view.
Referenced by setupConnections().
onGroupBoxViewToggled()
void Clipping::onGroupBoxViewToggled (bool on) protected
Definition at line 326 of file Clipping.cpp.
References Gui::Dialog::Clipping::Private::clipView, and Gui::Dialog::Clipping::Private::ui.
Referenced by setupConnections().
onGroupBoxXToggled()
void Clipping::onGroupBoxXToggled (bool on) protected
Definition at line 260 of file Clipping.cpp.
References Gui::Dialog::Clipping::Private::clipX, and Gui::Dialog::Clipping::Private::ui.
Referenced by setupConnections().
onGroupBoxYToggled()
void Clipping::onGroupBoxYToggled (bool on) protected
Definition at line 269 of file Clipping.cpp.
References Gui::Dialog::Clipping::Private::clipY, and Gui::Dialog::Clipping::Private::ui.
Referenced by setupConnections().
onGroupBoxZToggled()
void Clipping::onGroupBoxZToggled (bool on) protected
Definition at line 278 of file Clipping.cpp.
References Gui::Dialog::Clipping::Private::clipZ, and Gui::Dialog::Clipping::Private::ui.
Referenced by setupConnections().
reject()
void Clipping::reject () override
Definition at line 251 of file Clipping.cpp.
References Init::parent.
Referenced by bimcommands.BimReorder.BIM_Reorder_TaskPanel::accept(), draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), draftguitools.gui_selectplane.Draft_SelectPlane::action(), JointObject.TaskAssemblyCreateJoint::autoClosedOnTransactionChange(), femexamples.examplesgui.FemExamples::clicked(), CommandCreateView.TaskAssemblyCreateView::KeyboardEvent(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), bimcommands.BimProjectManager.BIM_ProjectManager::loadTemplate(), bimcommands.BimLibrary.BIM_Library_TaskPanel::mouseClick(), bimcommands.BimProjectManager.BIM_ProjectManager::saveTemplate(), and Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit().
setupConnections()
void Clipping::setupConnections () protected
Definition at line 213 of file Clipping.cpp.
References draftgeoutils.intersections::connect(), onAdjustViewdirectionToggled(), onClipViewValueChanged(), onClipXValueChanged(), onClipYValueChanged(), onClipZValueChanged(), onDirXValueChanged(), onDirYValueChanged(), onDirZValueChanged(), onFlipClipXClicked(), onFlipClipYClicked(), onFlipClipZClicked(), onFromViewClicked(), onGroupBoxViewToggled(), onGroupBoxXToggled(), onGroupBoxYToggled(), onGroupBoxZToggled(), and Gui::Dialog::Clipping::Private::ui.
Referenced by Clipping().
The documentation for this class was generated from the following files:
Clipping.h
Clipping.cpp