FreeCAD: Fem::StdMeshers_MaxLengthPy Class Reference
Fem::StdMeshers_MaxLengthPy Class Reference
#include <HypothesisPy.h>
Public Member Functions
StdMeshers_MaxLengthPy (int hypId, int studyId, SMESH_Gen *gen)
~StdMeshers_MaxLengthPy () override
Py::Object setLength (const Py::Tuple &args)
Py::Object getLength (const Py::Tuple &args)
Py::Object havePreestimatedLength (const Py::Tuple &args)
Py::Object getPreestimatedLength (const Py::Tuple &args)
Py::Object setPreestimatedLength (const Py::Tuple &args)
Py::Object setUsePreestimatedLength (const Py::Tuple &args)
Py::Object getUsePreestimatedLength (const Py::Tuple &args)
Public Member Functions inherited from Fem::SMESH_HypothesisPy< StdMeshers_MaxLengthPy >
SMESH_HypothesisPy (SMESH_Hypothesis *)
~SMESH_HypothesisPy () override
Py::Object getattr (const char *name) override
Py::Object repr () override
Py::Object getLibName (const Py::Tuple &args)
Py::Object setLibName (const Py::Tuple &args)
Py::Object isAuxiliary (const Py::Tuple &args)
Py::Object setParametersByMesh (const Py::Tuple &args)
std::shared_ptr< SMESH_Hypothesis > getHypothesis () const
Static Public Member Functions
static void init_type (PyObject *)
Static Public Member Functions inherited from Fem::SMESH_HypothesisPy< StdMeshers_MaxLengthPy >
static void init_type (PyObject *)
Additional Inherited Members
Public Types inherited from Fem::SMESH_HypothesisPy< StdMeshers_MaxLengthPy >
using SMESH_HypothesisPyBase = SMESH_HypothesisPy< StdMeshers_MaxLengthPy >
Protected Member Functions inherited from Fem::SMESH_HypothesisPy< StdMeshers_MaxLengthPy >
type * hypothesis () const
Detailed Description
Definition at line 421 of file HypothesisPy.h.
Constructor & Destructor Documentation
StdMeshers_MaxLengthPy()
StdMeshers_MaxLengthPy::StdMeshers_MaxLengthPy (int hypId, int studyId, SMESH_Gen * gen)
Definition at line 383 of file HypothesisPy.cpp.
~StdMeshers_MaxLengthPy()
StdMeshers_MaxLengthPy::~StdMeshers_MaxLengthPy () override default
Member Function Documentation
getLength()
Py::Object StdMeshers_MaxLengthPy::getLength (const Py::Tuple & args)
Definition at line 396 of file HypothesisPy.cpp.
References toolbit-attributes::args.
Referenced by init_type().
getPreestimatedLength()
Py::Object StdMeshers_MaxLengthPy::getPreestimatedLength (const Py::Tuple & args)
Definition at line 412 of file HypothesisPy.cpp.
References toolbit-attributes::args.
Referenced by init_type().
getUsePreestimatedLength()
Py::Object StdMeshers_MaxLengthPy::getUsePreestimatedLength (const Py::Tuple & args)
Definition at line 432 of file HypothesisPy.cpp.
References toolbit-attributes::args.
Referenced by init_type().
havePreestimatedLength()
Py::Object StdMeshers_MaxLengthPy::havePreestimatedLength (const Py::Tuple & args)
Definition at line 404 of file HypothesisPy.cpp.
References toolbit-attributes::args.
Referenced by init_type().
init_type()
void StdMeshers_MaxLengthPy::init_type (PyObject * module) static
Definition at line 353 of file HypothesisPy.cpp.
References getLength(), getPreestimatedLength(), getUsePreestimatedLength(), havePreestimatedLength(), Fem::SMESH_HypothesisPy< StdMeshers_MaxLengthPy >::init_type(), src.Mod.PartDesign.fcgear.svggear::module, setLength(), setPreestimatedLength(), and setUsePreestimatedLength().
Referenced by PyMOD_INIT_FUNC().
setLength()
Py::Object StdMeshers_MaxLengthPy::setLength (const Py::Tuple & args)
Definition at line 390 of file HypothesisPy.cpp.
References toolbit-attributes::args.
Referenced by init_type().
setPreestimatedLength()
Py::Object StdMeshers_MaxLengthPy::setPreestimatedLength (const Py::Tuple & args)
Definition at line 420 of file HypothesisPy.cpp.
References toolbit-attributes::args.
Referenced by init_type().
setUsePreestimatedLength()
Py::Object StdMeshers_MaxLengthPy::setUsePreestimatedLength (const Py::Tuple & args)
Definition at line 426 of file HypothesisPy.cpp.
References toolbit-attributes::args.
Referenced by init_type().
The documentation for this class was generated from the following files:
HypothesisPy.h
HypothesisPy.cpp