FreeCAD: Sketcher::SketchAnalysis Class Reference
Sketcher::SketchAnalysis Class Reference
#include <SketchAnalysis.h>
Public Member Functions
SketchAnalysis (Sketcher::SketchObject *Obj)
~SketchAnalysis ()
int detectMissingPointOnPointConstraints (double precision=Precision::Confusion() *1000, bool includeconstruction=true)
void analyseMissingPointOnPointCoincident (double angleprecision=M_PI/8)
Point on Point constraint simple routine Analyse step (see constructor)
std::vector< ConstraintIds > & getMissingPointOnPointConstraints ()
Point on Point constraint simple routine Get step (see constructor)
void setMissingPointOnPointConstraints (std::vector< ConstraintIds > &cl)
Vertical/Horizontal constraints simple routine Set step (see constructor)
void makeMissingPointOnPointCoincident ()
Point on Point constraint simple routine Make step (see constructor)
void makeMissingPointOnPointCoincidentOneByOne ()
int detectMissingVerticalHorizontalConstraints (double angleprecision=M_PI/8)
Vertical/Horizontal constraints simple routine Detect step (see constructor)
std::vector< ConstraintIds > & getMissingVerticalHorizontalConstraints ()
Vertical/Horizontal constraints simple routine Get step (see constructor)
void setMissingVerticalHorizontalConstraints (std::vector< ConstraintIds > &cl)
Vertical/Horizontal constraints simple routine Set step (see constructor)
void makeMissingVerticalHorizontal ()
Vertical/Horizontal constraints simple routine Make step (see constructor)
void makeMissingVerticalHorizontalOneByOne ()
int detectMissingEqualityConstraints (double precision)
Equality constraints simple routine Detect step (see constructor)
std::vector< ConstraintIds > & getMissingLineEqualityConstraints ()
Equality constraints simple routine Get step for line segments (see constructor)
std::vector< ConstraintIds > & getMissingRadiusConstraints ()
Equality constraints simple routine Get step for radii (see constructor)
void setMissingLineEqualityConstraints (std::vector< ConstraintIds > &cl)
Equality constraints simple routine Set step for line segments (see constructor)
void setMissingRadiusConstraints (std::vector< ConstraintIds > &cl)
Equality constraints simple routine Set step for radii (see constructor)
void makeMissingEquality ()
Equality constraints simple routine Make step (see constructor)
void makeMissingEqualityOneByOne ()
int detectDegeneratedGeometries (double tolerance) const
Detect degenerated geometries.
int removeDegeneratedGeometries (double tolerance)
Remove degenerated geometries.
int autoconstraint (double precision=Precision::Confusion() *1000, double angleprecision=M_PI/8, bool includeconstruction=true)
void solvesketch (int &status, int &dofs, bool updategeo)
std::vector< Base::Vector3d > getOpenVertices () const
Detailed Description
Definition at line 72 of file SketchAnalysis.h.
Constructor & Destructor Documentation
SketchAnalysis()
SketchAnalysis::SketchAnalysis (Sketcher::SketchObject * Obj) explicit
Creates an instance of the SketchAnalysis object, taking as parameter a pointer to an SketchObject.
There is a first type of routines, simple routines, which work in the following order: Detect - (Analyse) - [Get] - [Set] - Make
The Detect step just identifies possible missing constraints.
The Analyse, which is not available for all the routines, operates in detected constraints of the same routine, to look for alternatives. For example, a general pointonpoint detection leads to a search for coincident constraints, which can be later run via Analyse if it is intended to convert endpoint coincidence to endpoint perpendicular and tangent constraints.
The Get retrieves the result of the analysis as a vector of ConstraintIds, indicating the suggested constraints. This step is intended for enabling the user to check the result of the analysis, rather than applying it. If only applying is intended, this step is not necessary as the Make will operate on the result of the Detect - Analyse directly.
The Set changes the detected result. It modifies the SketchAnalysis object. It only modifies the SketchObject as far as the SketchAnalysis is changed. It does not apply any changes to the sketch. It is intended so as to enable the user to change the result that will be applied.
Neither the Detect, nor the Analyse, nor the Get steps modify the Sketch geometry.
Make applies the constraints stored internally in the SketchAnalysis object.
A second type of routines, complex routines, are thought for running fully automatic and they Detect, Analyse and Make. They may also apply a variety of constraint types.
A third type of routines do not relate to autoconstraining at all, and include validation methods for sketches.
Definition at line 48 of file SketchAnalysis.cpp.
~SketchAnalysis()
SketchAnalysis::~SketchAnalysis () default
Member Function Documentation
analyseMissingPointOnPointCoincident()
void SketchAnalysis::analyseMissingPointOnPointCoincident (double angleprecision = M_PI / 8)
Point on Point constraint simple routine Analyse step (see constructor)
Definition at line 552 of file SketchAnalysis.cpp.
References Base::Console(), KDL::cos(), Sketcher::SketchObject::getGeometry(), M_PI, Base::Vector3< float_type >::Normalize(), Sketcher::Perpendicular, Sketcher::Tangent, and Base::ConsoleSingleton::Warning().
Referenced by autoconstraint().
autoconstraint()
int SketchAnalysis::autoconstraint (double precision = Precision::Confusion() * 1000, double angleprecision = M_PI / 8, bool includeconstruction = true)
Fully automated multi-constraint autoconstraining
It DELETES all the constraints currently present in the Sketcher. The reason is that it makes assumptions to avoid redundancies.
It applies coincidents - vertical/horizontal constraints and equality constraints.
Definition at line 909 of file SketchAnalysis.cpp.
References analyseMissingPointOnPointCoincident(), Base::Console(), detectMissingEqualityConstraints(), detectMissingPointOnPointConstraints(), detectMissingVerticalHorizontalConstraints(), Base::ConsoleSingleton::Log(), and draftgeoutils.general::precision().
detectDegeneratedGeometries()
int SketchAnalysis::detectDegeneratedGeometries (double tolerance) const
Detect degenerated geometries.
Definition at line 1005 of file SketchAnalysis.cpp.
References draftutils.utils::tolerance().
detectMissingEqualityConstraints()
int SketchAnalysis::detectMissingEqualityConstraints (double precision)
Equality constraints simple routine Detect step (see constructor)
Definition at line 737 of file SketchAnalysis.cpp.
References Sketcher::SketchObject::Constraints, Sketcher::Equal, toolbit-attributes::g, Sketcher::SketchObject::getInternalGeometry(), Sketcher::PropertyConstraintList::getValues(), SplineSurface::i, RobotExample::pos, and draftgeoutils.general::precision().
Referenced by autoconstraint().
detectMissingPointOnPointConstraints()
int SketchAnalysis::detectMissingPointOnPointConstraints (double precision = Precision::Confusion() * 1000, bool includeconstruction = true)
Point on Point constraint simple routine Detect step (see constructor) Detect detects only coincident constraints, Analyse converts coincident to endpoint perpendicular/tangent where appropriate
Definition at line 504 of file SketchAnalysis.cpp.
References Sketcher::Coincident, Sketcher::SketchObject::Constraints, Sketcher::GeometryFacade::getFacade(), Sketcher::SketchObject::getInternalGeometry(), Sketcher::PropertyConstraintList::getValues(), SplineSurface::i, Sketcher::Perpendicular, draftgeoutils.general::precision(), and Sketcher::Tangent.
Referenced by autoconstraint().
detectMissingVerticalHorizontalConstraints()
int SketchAnalysis::detectMissingVerticalHorizontalConstraints (double angleprecision = M_PI / 8)
Vertical/Horizontal constraints simple routine Detect step (see constructor)
Definition at line 680 of file SketchAnalysis.cpp.
References toolbit-attributes::g, Sketcher::GeoUndef, Sketcher::SketchObject::getInternalGeometry(), Sketcher::Horizontal, SplineSurface::i, SplineSurface::id, Sketcher::none, and Sketcher::Vertical.
Referenced by autoconstraint().
getMissingLineEqualityConstraints()
std::vector<ConstraintIds>& Sketcher::SketchAnalysis::getMissingLineEqualityConstraints () inline
Equality constraints simple routine Get step for line segments (see constructor)
Definition at line 155 of file SketchAnalysis.h.
getMissingPointOnPointConstraints()
std::vector<ConstraintIds>& Sketcher::SketchAnalysis::getMissingPointOnPointConstraints () inline
Point on Point constraint simple routine Get step (see constructor)
Definition at line 120 of file SketchAnalysis.h.
getMissingRadiusConstraints()
std::vector<ConstraintIds>& Sketcher::SketchAnalysis::getMissingRadiusConstraints () inline
Equality constraints simple routine Get step for radii (see constructor)
Definition at line 160 of file SketchAnalysis.h.
getMissingVerticalHorizontalConstraints()
std::vector<ConstraintIds>& Sketcher::SketchAnalysis::getMissingVerticalHorizontalConstraints () inline
Vertical/Horizontal constraints simple routine Get step (see constructor)
Definition at line 139 of file SketchAnalysis.h.
getOpenVertices()
std::vector< Base::Vector3d > SketchAnalysis::getOpenVertices () const
Definition at line 957 of file SketchAnalysis.cpp.
References Part::PropertyPartShape::getValue(), App::PropertyPlacement::getValue(), SplineSurface::i, Base::Placement::inverse(), Base::Placement::multVec(), App::GeoFeature::Placement, RobotExample::pos, and Part::Feature::Shape.
makeMissingEquality()
void SketchAnalysis::makeMissingEquality ()
Equality constraints simple routine Make step (see constructor)
Definition at line 794 of file SketchAnalysis.cpp.
makeMissingEqualityOneByOne()
void SketchAnalysis::makeMissingEqualityOneByOne ()
Definition at line 806 of file SketchAnalysis.cpp.
References Arch::QT_TRANSLATE_NOOP.
makeMissingPointOnPointCoincident()
void SketchAnalysis::makeMissingPointOnPointCoincident ()
Point on Point constraint simple routine Make step (see constructor)
Definition at line 667 of file SketchAnalysis.cpp.
makeMissingPointOnPointCoincidentOneByOne()
void SketchAnalysis::makeMissingPointOnPointCoincidentOneByOne ()
Point on Point constraint simple routine Make step (see constructor) The sketch is solved after each individual constraint addition and any redundancy removed.
Definition at line 672 of file SketchAnalysis.cpp.
References Arch::QT_TRANSLATE_NOOP.
makeMissingVerticalHorizontal()
void SketchAnalysis::makeMissingVerticalHorizontal ()
Vertical/Horizontal constraints simple routine Make step (see constructor)
Definition at line 714 of file SketchAnalysis.cpp.
makeMissingVerticalHorizontalOneByOne()
void SketchAnalysis::makeMissingVerticalHorizontalOneByOne ()
Definition at line 719 of file SketchAnalysis.cpp.
References Arch::QT_TRANSLATE_NOOP.
removeDegeneratedGeometries()
int SketchAnalysis::removeDegeneratedGeometries (double tolerance)
Remove degenerated geometries.
Definition at line 1011 of file SketchAnalysis.cpp.
References Sketcher::SketchObject::delGeometry(), and draftutils.utils::tolerance().
setMissingLineEqualityConstraints()
void Sketcher::SketchAnalysis::setMissingLineEqualityConstraints (std::vector< ConstraintIds > & cl) inline
Equality constraints simple routine Set step for line segments (see constructor)
Definition at line 165 of file SketchAnalysis.h.
setMissingPointOnPointConstraints()
void Sketcher::SketchAnalysis::setMissingPointOnPointConstraints (std::vector< ConstraintIds > & cl) inline
Vertical/Horizontal constraints simple routine Set step (see constructor)
Definition at line 125 of file SketchAnalysis.h.
setMissingRadiusConstraints()
void Sketcher::SketchAnalysis::setMissingRadiusConstraints (std::vector< ConstraintIds > & cl) inline
Equality constraints simple routine Set step for radii (see constructor)
Definition at line 170 of file SketchAnalysis.h.
setMissingVerticalHorizontalConstraints()
void Sketcher::SketchAnalysis::setMissingVerticalHorizontalConstraints (std::vector< ConstraintIds > & cl) inline
Vertical/Horizontal constraints simple routine Set step (see constructor)
Definition at line 144 of file SketchAnalysis.h.
solvesketch()
void SketchAnalysis::solvesketch (int & status, int & dofs, bool updategeo)
solves the sketch and retrieves the error status, and the degrees of freedom. It enables to solve updating the geometry (so moving the geometry to match the constraints) or preserving the geometry.
Definition at line 821 of file SketchAnalysis.cpp.
References Sketcher::ConflictingConstraints, Sketcher::SketchObject::getLastDoF(), Sketcher::SketchObject::getLastHasConflicts(), Sketcher::SketchObject::getLastHasRedundancies(), Sketcher::OverConstrained, Sketcher::RedundantConstraints, Sketcher::SketchObject::setUpSketch(), and Sketcher::SketchObject::solve().
The documentation for this class was generated from the following files:
SketchAnalysis.h
SketchAnalysis.cpp