FreeCAD: TechDrawGui::DlgPrefsTechDrawScaleImp Class Reference
TechDrawGui::DlgPrefsTechDrawScaleImp Class Reference
#include <DlgPrefsTechDrawScaleImp.h>
Public Member Functions
DlgPrefsTechDrawScaleImp (QWidget *parent=nullptr)
~DlgPrefsTechDrawScaleImp () override
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Protected Slots
void onScaleTypeChanged (int index)
Protected Member Functions
void saveSettings () override
void loadSettings () override
void changeEvent (QEvent *e) override
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void resetSettingsToDefaults ()
Detailed Description
Definition at line 57 of file DlgPrefsTechDrawScaleImp.h.
Constructor & Destructor Documentation
DlgPrefsTechDrawScaleImp()
DlgPrefsTechDrawScaleImp::DlgPrefsTechDrawScaleImp (QWidget * parent = nullptr) explicit
Definition at line 33 of file DlgPrefsTechDrawScaleImp.cpp.
References draftgeoutils.intersections::connect(), Base::Unit::Length, and onScaleTypeChanged().
~DlgPrefsTechDrawScaleImp()
DlgPrefsTechDrawScaleImp::~DlgPrefsTechDrawScaleImp () override
Definition at line 46 of file DlgPrefsTechDrawScaleImp.cpp.
Member Function Documentation
changeEvent()
void DlgPrefsTechDrawScaleImp::changeEvent (QEvent * e) override protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
Definition at line 88 of file DlgPrefsTechDrawScaleImp.cpp.
References SCL.SimpleDataTypes::e.
loadSettings()
void DlgPrefsTechDrawScaleImp::loadSettings () override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 72 of file DlgPrefsTechDrawScaleImp.cpp.
onScaleTypeChanged
void DlgPrefsTechDrawScaleImp::onScaleTypeChanged (int index) protected slot
Definition at line 51 of file DlgPrefsTechDrawScaleImp.cpp.
Referenced by DlgPrefsTechDrawScaleImp().
saveSettings()
void DlgPrefsTechDrawScaleImp::saveSettings () override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 61 of file DlgPrefsTechDrawScaleImp.cpp.
The documentation for this class was generated from the following files:
DlgPrefsTechDrawScaleImp.h
DlgPrefsTechDrawScaleImp.cpp