FreeCAD: Path.Post.scripts.refactored_mach3_mach4_post Namespace Reference
Path.Post.scripts.refactored_mach3_mach4_post Namespace Reference
Functions
None init_values (Values values)
None init_argument_defaults (Dict[str, bool] argument_defaults)
None init_arguments_visible (Dict[str, bool] arguments_visible)
Parser init_arguments (Values values, Dict[str, bool] argument_defaults, Dict[str, bool] arguments_visible)
str export (objectslist, filename, argstring)
Variables
Parser
Values
str
Function Documentation
export()
str Path.Post.scripts.refactored_mach3_mach4_post.export (objectslist, filename, argstring)
Postprocess the objects in objectslist to filename.
Definition at line 200 of file refactored_mach3_mach4_post.py.
init_argument_defaults()
None Path.Post.scripts.refactored_mach3_mach4_post.init_argument_defaults (Dict[str, bool] argument_defaults)
Initialize which arguments (in a pair) are shown as the default argument.
Definition at line 125 of file refactored_mach3_mach4_post.py.
Referenced by Path.Post.scripts.refactored_mach3_mach4_post.init_arguments().
init_arguments()
Parser Path.Post.scripts.refactored_mach3_mach4_post.init_arguments (Values values, Dict[str, bool] argument_defaults, Dict[str, bool] arguments_visible)
Initialize the shared argument definitions.
Definition at line 154 of file refactored_mach3_mach4_post.py.
References Path.Post.scripts.refactored_mach3_mach4_post.init_argument_defaults(), Path.Post.scripts.refactored_mach3_mach4_post.init_arguments_visible(), and Path.Post.scripts.refactored_mach3_mach4_post.init_values().
init_arguments_visible()
None Path.Post.scripts.refactored_mach3_mach4_post.init_arguments_visible (Dict[str, bool] arguments_visible)
Initialize which argument pairs are visible in TOOLTIP_ARGS.
Definition at line 145 of file refactored_mach3_mach4_post.py.
Referenced by Path.Post.scripts.refactored_mach3_mach4_post.init_arguments().
init_values()
None Path.Post.scripts.refactored_mach3_mach4_post.init_values (Values values)
Initialize values that are used throughout the postprocessor.
Definition at line 65 of file refactored_mach3_mach4_post.py.
Referenced by Path.Post.scripts.refactored_mach3_mach4_post.init_arguments().
Variable Documentation
Parser
Path.Post.scripts.refactored_mach3_mach4_post.Parser
Definition at line 34 of file refactored_mach3_mach4_post.py.
str
Path.Post.scripts.refactored_mach3_mach4_post.str
Definition at line 49 of file refactored_mach3_mach4_post.py.
Values
Path.Post.scripts.refactored_mach3_mach4_post.Values
Definition at line 35 of file refactored_mach3_mach4_post.py.