FreeCAD: TechDraw::AOE Class Reference
TechDraw::AOE Class Reference
#include <Geometry.h>
Public Member Functions
AOE (const TopoDS_Edge &e)
~AOE () override=default
double getStartAngle () override
double getEndAngle () override
bool clockwiseAngle () override
void clockwiseAngle (bool direction) override
Public Member Functions inherited from TechDraw::Ellipse
Ellipse (const TopoDS_Edge &e)
Ellipse (Base::Vector3d c, double mnr, double mjr)
~Ellipse () override=default
Public Member Functions inherited from TechDraw::BaseGeom
BaseGeom ()
virtual ~BaseGeom ()=default
virtual void Save (Base::Writer &w) const
virtual void Restore (Base::XMLReader &r)
std::vector< Base::Vector3d > findEndPoints ()
Base::Vector3d getStartPoint ()
Base::Vector3d getEndPoint ()
Base::Vector3d getMidPoint ()
std::vector< Base::Vector3d > getQuads ()
double minDist (Base::Vector3d p)
Base::Vector3d nearPoint (Base::Vector3d p)
Base::Vector3d nearPoint (const BaseGeomPtr p)
find point on me nearest to p
bool closed ()
virtual BaseGeomPtr copy ()
std::string dump ()
virtual std::string toString () const
std::vector< Base::Vector3d > intersection (TechDraw::BaseGeomPtr geom2)
boost::uuids::uuid getTag () const
virtual std::string getTagAsString () const
std::string geomTypeName ()
BaseGeomPtr inverted ()
GeomType getGeomType ()
void setGeomType (GeomType type)
edgeClass getClassOfEdge ()
void setClassOfEdge (edgeClass newClass)
bool getHlrVisible ()
void setHlrVisible (bool state)
bool getReversed ()
void setReversed (bool state)
int getRef3d ()
void setRef3d (int ref)
TopoDS_Edge getOCCEdge ()
void setOCCEdge (TopoDS_Edge newEdge)
bool getCosmetic ()
void setCosmetic (bool state)
int source ()
void source (int s)
int sourceIndex ()
void sourceIndex (int si)
std::string getCosmeticTag ()
void setCosmeticTag (std::string t)
Part::TopoShape asTopoShape (double scale=1.0)
Public Attributes
Base::Vector3d startPnt
Base::Vector3d endPnt
Base::Vector3d midPnt
double startAngle
Angle in radian.
double endAngle
Angle in radian.
bool cw
Arc is drawn clockwise from startAngle to endAngle if true, counterclockwise if false.
bool largeArc
Public Attributes inherited from TechDraw::Ellipse
Base::Vector3d center
double minor
double major
double angle
Angle between the major axis of the ellipse and the X axis, in radian.
Additional Inherited Members
Static Public Member Functions inherited from TechDraw::BaseGeom
static BaseGeomPtr baseFactory (TopoDS_Edge edge, bool isCosmetic=false)
Convert 1 OCC edge into 1 BaseGeom (static factory method)
static bool validateEdge (TopoDS_Edge edge)
static TopoDS_Edge completeEdge (const TopoDS_Edge &edge)
Protected Member Functions inherited from TechDraw::BaseGeom
void createNewTag ()
Protected Attributes inherited from TechDraw::BaseGeom
GeomType geomType
ExtractionType extractType
edgeClass classOfEdge
bool hlrVisible
bool reversed
int ref3D
TopoDS_Edge occEdge
bool cosmetic
int m_source
int m_sourceIndex
std::string cosmeticTag
boost::uuids::uuid tag
Detailed Description
Definition at line 212 of file TechDraw/App/Geometry.h.
Constructor & Destructor Documentation
AOE()
AOE::AOE (const TopoDS_Edge & e) explicit
Definition at line 689 of file TechDraw/App/Geometry.cpp.
References a, TechDraw::ARCOFELLIPSE, SCL.SimpleDataTypes::c, Base::Console(), cw, SCL.SimpleDataTypes::e, endAngle, endPnt, Base::ConsoleSingleton::Error(), SCL.SimpleDataTypes::f, Base::fmod(), TechDraw::BaseGeom::geomType, RobotExample::l, largeArc, test::m, M_PI, midPnt, TechDraw::BaseGeom::reversed, toolbit-attributes::s, startAngle, startPnt, and draftgeoutils.general::v1().
~AOE()
TechDraw::AOE::~AOE () override default
Member Function Documentation
clockwiseAngle() [1/2]
bool TechDraw::AOE::clockwiseAngle () inline override virtual
Reimplemented from TechDraw::BaseGeom.
Definition at line 221 of file TechDraw/App/Geometry.h.
clockwiseAngle() [2/2]
void TechDraw::AOE::clockwiseAngle (bool direction) inline override virtual
Reimplemented from TechDraw::BaseGeom.
Definition at line 222 of file TechDraw/App/Geometry.h.
getEndAngle()
double TechDraw::AOE::getEndAngle () inline override virtual
Reimplemented from TechDraw::BaseGeom.
Definition at line 220 of file TechDraw/App/Geometry.h.
getStartAngle()
double TechDraw::AOE::getStartAngle () inline override virtual
Reimplemented from TechDraw::BaseGeom.
Definition at line 219 of file TechDraw/App/Geometry.h.
Member Data Documentation
cw
bool TechDraw::AOE::cw
Arc is drawn clockwise from startAngle to endAngle if true, counterclockwise if false.
Definition at line 234 of file TechDraw/App/Geometry.h.
Referenced by AOE().
endAngle
double TechDraw::AOE::endAngle
Angle in radian.
Definition at line 231 of file TechDraw/App/Geometry.h.
Referenced by AOE().
endPnt
Base::Vector3d TechDraw::AOE::endPnt
Definition at line 224 of file TechDraw/App/Geometry.h.
Referenced by AOE().
largeArc
bool TechDraw::AOE::largeArc
Definition at line 235 of file TechDraw/App/Geometry.h.
Referenced by AOE().
midPnt
Base::Vector3d TechDraw::AOE::midPnt
Definition at line 225 of file TechDraw/App/Geometry.h.
Referenced by AOE().
startAngle
double TechDraw::AOE::startAngle
Angle in radian.
Definition at line 228 of file TechDraw/App/Geometry.h.
Referenced by AOE().
startPnt
Base::Vector3d TechDraw::AOE::startPnt
Definition at line 223 of file TechDraw/App/Geometry.h.
Referenced by AOE().
The documentation for this class was generated from the following files:
TechDraw/App/Geometry.h
TechDraw/App/Geometry.cpp