FreeCAD: Base::Handled Class Reference
Base::Handled Class Reference
#include <Handle.h>
Public Member Functions
Handled ()
virtual ~Handled ()
void ref () const
void unref () const
int unrefNoDelete () const
int getRefCount () const
Handled & operator= (const Handled &)
Handled (const Handled &)=delete
Handled (Handled &&)=delete
Handled & operator= (Handled &&)=delete
Detailed Description
Handled class Implementation of the reference counting pattern.
Definition at line 169 of file Handle.h.
Constructor & Destructor Documentation
Handled() [1/3]
Handled::Handled ()
Definition at line 42 of file Handle.cpp.
~Handled()
Handled::~Handled () virtual
Definition at line 46 of file Handle.cpp.
Handled() [2/3]
Base::Handled::Handled (const Handled &) delete
Handled() [3/3]
Base::Handled::Handled (Handled &&) delete
Member Function Documentation
getRefCount()
int Handled::getRefCount () const
Definition at line 74 of file Handle.cpp.
Referenced by App::StringIDRef::getRefCount(), and ParameterGrp::ShouldRemove().
operator=() [1/2]
Handled & Handled::operator= (const Handled &)
Definition at line 79 of file Handle.cpp.
operator=() [2/2]
Handled& Base::Handled::operator= (Handled &&) delete
ref()
void Handled::ref () const
Definition at line 54 of file Handle.cpp.
Referenced by App::StringHasher::insert(), App::StringIDRef::operator=(), and App::StringIDRef::StringIDRef().
unref()
void Handled::unref () const
Definition at line 59 of file Handle.cpp.
Referenced by App::StringHasher::compact(), App::StringIDRef::operator=(), and App::StringIDRef::~StringIDRef().
unrefNoDelete()
int Handled::unrefNoDelete () const
Definition at line 67 of file Handle.cpp.
The documentation for this class was generated from the following files:
Handle.h
Handle.cpp