FreeCAD: Gui::DoubleSpinBox Class Reference
Gui::DoubleSpinBox Class Reference
#include <SpinBox.h>
Public Member Functions
DoubleSpinBox (QWidget *parent=nullptr)
~DoubleSpinBox () override
bool apply (const std::string &propName) override
void setNumberExpression (App::NumberExpression *) override
void keyPressEvent (QKeyEvent *event) override
void resizeEvent (QResizeEvent *event) override
void paintEvent (QPaintEvent *event) override
Public Member Functions inherited from Gui::ExpressionSpinBox
ExpressionSpinBox (QAbstractSpinBox *)
~ExpressionSpinBox () override
void bind (const App::ObjectIdentifier &_path) override
void setExpression (std::shared_ptr< App::Expression > expr) override
Public Member Functions inherited from Gui::ExpressionWidget
ExpressionWidget ()
QPixmap getIcon (const char *name, const QSize &size) const
Public Member Functions inherited from Gui::ExpressionBinding
ExpressionBinding ()
virtual ~ExpressionBinding ()
virtual void bind (const App::Property &prop)
bool isBound () const
void unbind ()
virtual bool apply ()
bool hasExpression () const
bool autoApply () const
void setAutoApply (bool value)
Additional Inherited Members
Protected Types inherited from Gui::ExpressionSpinBox
enum Number { Number::KeepCurrent = 0, Number::SetIfNumber = 1 }
Protected Member Functions inherited from Gui::ExpressionSpinBox
void showInvalidExpression (const QString &)
void showValidExpression (Number number)
void clearExpression ()
void updateExpression ()
void onChange () override
virtual void showIcon ()
virtual void validateInput ()
void resizeWidget ()
bool handleKeyEvent (const QString &)
virtual void openFormulaDialog ()
void drawControl (QStyleOptionSpinBox &)
Protected Member Functions inherited from Gui::ExpressionWidget
void makeLabel (QLineEdit *parent)
Protected Member Functions inherited from Gui::ExpressionBinding
const App::ObjectIdentifier & getPath () const
std::shared_ptr< App::Expression > getExpression () const
std::string getExpressionString (bool no_throw=true) const
std::string getEscapedExpressionString () const
bool assignToProperty (const std::string &propName, double)
void expressionChange (const App::ObjectIdentifier &id)
void objectDeleted (const App::DocumentObject &)
Protected Attributes inherited from Gui::ExpressionSpinBox
QLineEdit * lineedit
QAbstractSpinBox * spinbox
Protected Attributes inherited from Gui::ExpressionWidget
ExpressionLabel * iconLabel {nullptr}
QPalette defaultPalette
int iconHeight {-1}
Protected Attributes inherited from Gui::ExpressionBinding
boost::signals2::scoped_connection expressionchanged
boost::signals2::scoped_connection objectdeleted
bool m_autoApply {false}
Detailed Description
The DoubleSpinBox class does exactly the same as Qt's QDoubleSpinBox but has expression support
Author
Stefan Tröger
Definition at line 184 of file SpinBox.h.
Constructor & Destructor Documentation
DoubleSpinBox()
DoubleSpinBox::DoubleSpinBox (QWidget * parent = nullptr) explicit
Definition at line 491 of file SpinBox.cpp.
~DoubleSpinBox()
DoubleSpinBox::~DoubleSpinBox () override default
Member Function Documentation
apply()
bool DoubleSpinBox::apply (const std::string & propName) override virtual
Reimplemented from Gui::ExpressionBinding.
Definition at line 499 of file SpinBox.cpp.
References Gui::ExpressionBinding::apply(), Gui::Command::Doc, and doCommand.
keyPressEvent()
void DoubleSpinBox::keyPressEvent (QKeyEvent * event) override
Definition at line 520 of file SpinBox.cpp.
References Gui::ExpressionSpinBox::handleKeyEvent().
paintEvent()
void DoubleSpinBox::paintEvent (QPaintEvent * event) override
Definition at line 526 of file SpinBox.cpp.
References Gui::ExpressionSpinBox::drawControl().
resizeEvent()
void DoubleSpinBox::resizeEvent (QResizeEvent * event) override
Definition at line 514 of file SpinBox.cpp.
References Gui::ExpressionSpinBox::resizeWidget().
setNumberExpression()
void DoubleSpinBox::setNumberExpression (App::NumberExpression * expr) override virtual
Implements Gui::ExpressionSpinBox.
Definition at line 509 of file SpinBox.cpp.
References App::UnitExpression::getValue().
The documentation for this class was generated from the following files:
SpinBox.h
SpinBox.cpp