FreeCAD: Gui::Dialog::DlgSettingsLightSources Class Reference
Gui::Dialog::DlgSettingsLightSources Class Reference
#include <DlgSettingsLightSources.h>
Public Slots
void updateDraggerQS ()
void updateDraggerXYZ ()
void toggleLight (bool on)
void lightIntensity (int value)
void lightColor ()
void pushIn (void)
void pullOut (void)
Public Slots inherited from Gui::Dialog::PreferencePage
Public Member Functions
DlgSettingsLightSources (QWidget *parent=nullptr)
~DlgSettingsLightSources () override=default
void saveSettings () override
void loadSettings () override
void resetSettingsToDefaults () override
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Protected Member Functions
void changeEvent (QEvent *event) override
Detailed Description
The DlgSettingsLightSources class implements a preference page to change settings for the light sources of a 3D view.
Author
Werner Mayer
Definition at line 46 of file DlgSettingsLightSources.h.
Constructor & Destructor Documentation
DlgSettingsLightSources()
DlgSettingsLightSources::DlgSettingsLightSources (QWidget * parent = nullptr) explicit
Definition at line 49 of file DlgSettingsLightSources.cpp.
~DlgSettingsLightSources()
Gui::Dialog::DlgSettingsLightSources::~DlgSettingsLightSources () override default
Member Function Documentation
changeEvent()
void DlgSettingsLightSources::changeEvent (QEvent * event) override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 318 of file DlgSettingsLightSources.cpp.
References Gui::Dialog::PreferencePage::changeEvent().
lightColor
void DlgSettingsLightSources::lightColor () slot
Definition at line 292 of file DlgSettingsLightSources.cpp.
Referenced by loadSettings().
lightIntensity
void DlgSettingsLightSources::lightIntensity (int value) slot
Definition at line 285 of file DlgSettingsLightSources.cpp.
References SCL.SimpleDataTypes::f.
loadSettings()
void DlgSettingsLightSources::loadSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 208 of file DlgSettingsLightSources.cpp.
References lightColor().
pullOut
void DlgSettingsLightSources::pullOut (void) slot
Definition at line 310 of file DlgSettingsLightSources.cpp.
pushIn
void DlgSettingsLightSources::pushIn (void) slot
Definition at line 302 of file DlgSettingsLightSources.cpp.
resetSettingsToDefaults()
void DlgSettingsLightSources::resetSettingsToDefaults () override virtual
Reimplemented from Gui::Dialog::PreferencePage.
Definition at line 217 of file DlgSettingsLightSources.cpp.
References toolbit-attributes::grp, and Gui::Dialog::PreferencePage::resetSettingsToDefaults().
saveSettings()
void DlgSettingsLightSources::saveSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 200 of file DlgSettingsLightSources.cpp.
toggleLight
void DlgSettingsLightSources::toggleLight (bool on) slot
Definition at line 278 of file DlgSettingsLightSources.cpp.
updateDraggerQS
void DlgSettingsLightSources::updateDraggerQS () slot
Definition at line 326 of file DlgSettingsLightSources.cpp.
References getDirectionVector(), setLightDirection(), setLightDraggerDirection(), and setValueSilently().
updateDraggerXYZ
void DlgSettingsLightSources::updateDraggerXYZ () slot
Definition at line 345 of file DlgSettingsLightSources.cpp.
References setLightDirection(), setLightDraggerDirection(), setValueSilently(), MovieTool::x, and MovieTool::y.
The documentation for this class was generated from the following files:
DlgSettingsLightSources.h
DlgSettingsLightSources.cpp