FreeCAD: Path.Tool.Gui.Bit Namespace Reference
Path.Tool.Gui.Bit Namespace Reference
Classes
class TaskPanel
class ToolBitGuiFactory
class ViewProvider
Functions
def isValidFileName (filename)
def GetNewToolFile (parent=None)
def GetToolFile (parent=None)
def GetToolFiles (parent=None)
def GetToolShapeFile (parent=None)
def LoadTool (parent=None)
def LoadTools (parent=None)
Variables
translate
Function Documentation
GetNewToolFile()
def Path.Tool.Gui.Bit.GetNewToolFile (parent = None)
Definition at line 187 of file Gui/Bit.py.
References Path.Tool.Gui.Bit.isValidFileName(), Path.Preferences.lastPathToolBit(), and Path.Preferences.setLastPathToolBit().
GetToolFile()
def Path.Tool.Gui.Bit.GetToolFile (parent = None)
Definition at line 206 of file Gui/Bit.py.
References Path.Preferences.lastPathToolBit(), and Path.Preferences.setLastPathToolBit().
Referenced by Path.Tool.Gui.Bit.LoadTool().
GetToolFiles()
def Path.Tool.Gui.Bit.GetToolFiles (parent = None)
Definition at line 218 of file Gui/Bit.py.
References Path.Preferences.lastPathToolBit(), and Path.Preferences.setLastPathToolBit().
Referenced by Path.Tool.Gui.Bit.LoadTools().
GetToolShapeFile()
def Path.Tool.Gui.Bit.GetToolShapeFile (parent = None)
Definition at line 230 of file Gui/Bit.py.
References Path.Preferences.filePath(), Path.Preferences.lastPathToolShape(), and Path.Preferences.setLastPathToolShape().
isValidFileName()
def Path.Tool.Gui.Bit.isValidFileName (filename)
Definition at line 178 of file Gui/Bit.py.
References AssemblyImport.open().
Referenced by Path.Tool.Gui.Bit.GetNewToolFile().
LoadTool()
def Path.Tool.Gui.Bit.LoadTool (parent = None)
LoadTool(parent=None) ... Open a file dialog to load a tool from a file.
Definition at line 252 of file Gui/Bit.py.
References Path.Tool.Gui.Bit.GetToolFile().
LoadTools()
def Path.Tool.Gui.Bit.LoadTools (parent = None)
LoadTool(parent=None) ... Open a file dialog to load a tool from a file.
Definition at line 260 of file Gui/Bit.py.
References Path.Tool.Gui.Bit.GetToolFiles().
Variable Documentation
translate
Path.Tool.Gui.Bit.translate
Definition at line 45 of file Gui/Bit.py.