FreeCAD: Gui::LocationDialog Class Reference
Gui::LocationDialog Class Reference abstract
#include <InputVector.h>
Public Member Functions
virtual Base::Vector3d getDirection () const =0
Base::Vector3d getUserDirection (bool *ok=nullptr) const
Protected Member Functions
LocationDialog (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~LocationDialog () override
void changeEvent (QEvent *e) override=0
Detailed Description
This is the abstract base dialog class that defines the interface for specifying a direction vector by the user.
Author
Werner Mayer
Definition at line 78 of file InputVector.h.
Constructor & Destructor Documentation
LocationDialog()
LocationDialog::LocationDialog (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags()) protected
Definition at line 223 of file InputVector.cpp.
~LocationDialog()
LocationDialog::~LocationDialog () override protected default
Member Function Documentation
changeEvent()
void Gui::LocationDialog::changeEvent (QEvent * e) override protected pure virtual
Implemented in Gui::LocationDialogUiImp, Gui::LocationDialogImp< Ui >, and Gui::LocationDialogUi< Ui >.
getDirection()
virtual Base::Vector3d Gui::LocationDialog::getDirection () const pure virtual
Implemented in Gui::LocationDialogUiImp, Gui::LocationDialogImp< Ui >, and Gui::LocationDialogUi< Ui >.
getUserDirection()
Base::Vector3d LocationDialog::getUserDirection (bool * ok = nullptr) const
Definition at line 230 of file InputVector.cpp.
References Base::UnitsApi::getDecimals(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by Gui::LocationUi< Ui >::directionActivated(), and Gui::LocationImpUi< Ui >::directionActivated().
The documentation for this class was generated from the following files:
InputVector.h
InputVector.cpp