FreeCAD: App::TransactionLocker Class Reference
App::TransactionLocker Class Reference
#include <AutoTransaction.h>
Public Member Functions
TransactionLocker (bool lock=true)
~TransactionLocker ()
void activate (bool enable)
bool isActive () const
Check if the locker is active.
void * operator new (std::size_t)=delete
Private new operator to prevent heap allocation.
Static Public Member Functions
static bool isLocked ()
Check if transaction is being locked.
Friends
class Application
Detailed Description
Helper class to lock a transaction from being closed or aborted.
The helper class is used to protect some critical transaction from being closed prematurely, e.g. when deleting some object.
Definition at line 115 of file AutoTransaction.h.
Constructor & Destructor Documentation
TransactionLocker()
TransactionLocker::TransactionLocker (bool lock = true)
Constructor
Parameters
lock whether to activate the lock
Definition at line 228 of file AutoTransaction.cpp.
References _TransactionLock.
~TransactionLocker()
TransactionLocker::~TransactionLocker ()
Destructor Unlock the transaction is this locker is active
Definition at line 236 of file AutoTransaction.cpp.
References activate(), SCL.SimpleDataTypes::e, and FC_ERR.
Member Function Documentation
activate()
void TransactionLocker::activate (bool enable)
Activate or deactivate this locker
Parameters
enable whether to activate the locker
An internal counter is used to support recursive locker. When activated, the current active transaction cannot be closed or aborted. But the closing call (Application::closeActiveTransaction()) will be remembered, and performed when the internal lock counter reaches zero.
Definition at line 259 of file AutoTransaction.cpp.
References _TransactionClosed, _TransactionLock, App::Application::closeActiveTransaction(), and App::GetApplication().
Referenced by ArchBuildingPart.ViewProviderBuildingPart::setEdit(), nativeifc.ifc_viewproviders.ifc_vp_object::setupContextMenu(), ArchBuildingPart.ViewProviderBuildingPart::setupContextMenu(), and ~TransactionLocker().
isActive()
bool App::TransactionLocker::isActive () const inline
Check if the locker is active.
Definition at line 139 of file AutoTransaction.h.
isLocked()
bool TransactionLocker::isLocked () static
Check if transaction is being locked.
Definition at line 282 of file AutoTransaction.cpp.
References _TransactionLock.
operator new()
void* App::TransactionLocker::operator new (std::size_t) delete
Private new operator to prevent heap allocation.
Friends And Related Function Documentation
Application
friend class Application friend
Definition at line 147 of file AutoTransaction.h.
The documentation for this class was generated from the following files:
AutoTransaction.h
AutoTransaction.cpp