FreeCAD: Gui::BaseView Class Reference
Gui::BaseView Class Reference abstract
#include <View.h>
Public Member Functions
BaseView (Gui::Document *pcDocument=nullptr)
~BaseView () override
methods used by the Application and the GuiDocument
void setDocument (Gui::Document *pcDocument)
sets the view to another document (called by Application)
void onClose ()
is sent from the document in order to close the document
Gui::Document * getGuiDocument () const
returns the document the view is attached to
App::Document * getAppDocument () const
returns the document the view is attached to
bool isPassive () const
indicates if the view is in passive mode
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
methods to override
Gui::Document * _pcDocument
bool bIsDetached {false}
bool bIsPassive {false}
virtual void onUpdate ()
get called when the document is updated
virtual void onRelabel (Gui::Document *)
get called when the document is relabeled (change of its user name)
virtual void onRename (Gui::Document *)
get called when the document is renamed (change of its internal name)
virtual const char * getName () const
returns the name of the view (important for messages)
virtual bool onMsg (const char *pMsg, const char **ppReturn)=0
Message handler.
virtual bool onHasMsg (const char *pMsg) const =0
Message handler test.
virtual bool canClose ()
overwrite when checking on close state
virtual void deleteSelf ()
delete itself
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Base class of all windows belonging to a document there are two ways of belonging to a document. The first way is to a fixed one. The second way is to always belonging to the Active document. that means switching every time the active document is changing. It also means that the view belongs sometimes to no document at all!
See also
TreeView
Gui::Document
Application
Author
Juergen Riegel
Definition at line 51 of file View.h.
Constructor & Destructor Documentation
BaseView()
BaseView::BaseView (Gui::Document * pcDocument = nullptr)
View constructor Attach the view to the given document. If the document is 0 the view will attach to the active document. Be aware! there isn't always an active document!
Definition at line 39 of file View.cpp.
References Gui::Application::attachView(), and Gui::Application::Instance.
~BaseView()
BaseView::~BaseView () override
View destructor Detach the view from the document, if attached!
Definition at line 52 of file View.cpp.
References onClose().
Member Function Documentation
canClose()
virtual bool Gui::BaseView::canClose () inline virtual
overwrite when checking on close state
Reimplemented in Gui::AlignmentView, Gui::DockWindow, Gui::MDIView, Gui::MDIViewPyWrap, and Gui::EditorView.
Definition at line 101 of file View.h.
deleteSelf()
void BaseView::deleteSelf () virtual
delete itself
Reimplemented in SpreadsheetGui::SheetView, Gui::View3DInventor, Gui::MDIView, and Gui::AbstractSplitView.
Definition at line 76 of file View.cpp.
getAppDocument()
App::Document * BaseView::getAppDocument () const
returns the document the view is attached to
Definition at line 96 of file View.cpp.
References _pcDocument, and Gui::Document::getDocument().
Referenced by Gui::MDIView::buildWindowTitle(), Gui::MDIView::canClose(), Gui::View3DInventor::dropEvent(), PartDesignGui::getBody(), Gui::View3DInventor::onHasMsg(), DrawingGui::DrawingView::onHasMsg(), and PartDesignGui::Workbench::setupContextMenu().
getGuiDocument()
Gui::Document* Gui::BaseView::getGuiDocument () const inline
returns the document the view is attached to
Definition at line 78 of file View.h.
Referenced by Gui::MDIView::canClose(), Gui::MDIView::closeEvent(), DrawingGui::DrawingView::onHasMsg(), Gui::View3DInventor::onMsg(), Gui::TextDocumentEditorView::onMsg(), DrawingGui::DrawingView::onMsg(), Gui::MDIView::redoActions(), Gui::View3DInventorPy::removeAnnotation(), Gui::View3DInventorPy::setAnnotation(), Gui::MDIView::undoActions(), and Gui::Application::viewActivated().
getName()
virtual const char* Gui::BaseView::getName () const inline virtual
returns the name of the view (important for messages)
Reimplemented in Gui::Dialog::LicenseView, Gui::View3DInventor, Gui::DockWindow, Gui::TextDocumentEditorView, Gui::EditorView, Gui::AbstractSplitView, Gui::DockWnd::SelectionView, SpreadsheetGui::SheetView, StartGui::StartView, and Gui::ImageView.
Definition at line 94 of file View.h.
isPassive()
bool Gui::BaseView::isPassive () const inline
indicates if the view is in passive mode
Definition at line 82 of file View.h.
Referenced by Gui::Application::viewActivated().
onClose()
void BaseView::onClose ()
is sent from the document in order to close the document
Definition at line 57 of file View.cpp.
References _pcDocument, bIsDetached, bIsPassive, Gui::Application::detachView(), Gui::Document::detachView(), and Gui::Application::Instance.
Referenced by Gui::MDIView::deleteSelf(), and ~BaseView().
onHasMsg()
virtual bool Gui::BaseView::onHasMsg (const char * pMsg) const pure virtual
Message handler test.
Implemented in Gui::PythonEditorView, Gui::View3DInventor, Gui::MDIView, TechDrawGui::MDIViewPage, Gui::MDIViewPyWrap, Gui::EditorView, Gui::AbstractSplitView, SpreadsheetGui::SheetView, StartGui::StartView, Gui::GraphvizView, Gui::ImageView, DrawingGui::DrawingView, Gui::TextDocumentEditorView, and Gui::DockWindow.
onMsg()
virtual bool Gui::BaseView::onMsg (const char * pMsg, const char ** ppReturn) pure virtual
Message handler.
Implemented in Gui::PythonEditorView, Gui::View3DInventor, Gui::MDIView, TechDrawGui::MDIViewPage, Gui::EditorView, Gui::MDIViewPyWrap, Gui::AbstractSplitView, SpreadsheetGui::SheetView, Gui::DockWnd::SelectionView, Gui::GraphvizView, Gui::ImageView, DrawingGui::DrawingView, Gui::TextDocumentEditorView, and Gui::DockWindow.
onRelabel()
virtual void Gui::BaseView::onRelabel (Gui::Document *) inline virtual
get called when the document is relabeled (change of its user name)
Reimplemented in Gui::MDIView, and DrawingGui::DrawingView.
Definition at line 90 of file View.h.
onRename()
virtual void Gui::BaseView::onRename (Gui::Document *) inline virtual
get called when the document is renamed (change of its internal name)
Reimplemented in Gui::View3DInventor.
Definition at line 92 of file View.h.
onUpdate()
virtual void Gui::BaseView::onUpdate () inline virtual
get called when the document is updated
Reimplemented in Gui::View3DInventor, Gui::DockWindow, Gui::AbstractSplitView, Gui::EditorView, and Gui::DockWnd::SelectionView.
Definition at line 88 of file View.h.
setDocument()
void BaseView::setDocument (Gui::Document * pcDocument)
sets the view to another document (called by Application)
Definition at line 81 of file View.cpp.
References _pcDocument, Gui::Document::attachView(), and Gui::Document::detachView().
Member Data Documentation
_pcDocument
Gui::Document* Gui::BaseView::_pcDocument protected
Definition at line 107 of file View.h.
Referenced by DrawingGui::DrawingView::closeEvent(), Gui::MDIView::deleteSelf(), getAppDocument(), onClose(), setDocument(), and Gui::View3DInventor::~View3DInventor().
bIsDetached
bool Gui::BaseView::bIsDetached {false} protected
Definition at line 108 of file View.h.
Referenced by onClose().
bIsPassive
bool Gui::BaseView::bIsPassive {false} protected
Definition at line 109 of file View.h.
Referenced by Gui::MDIView::canClose(), Gui::MDIView::closeEvent(), onClose(), Gui::MDIView::onRelabel(), and DrawingGui::DrawingView::onRelabel().
The documentation for this class was generated from the following files:
View.h
View.cpp