FreeCAD: Base::CoordinateSystem Class Reference
Base::CoordinateSystem Class Reference
#include <CoordinateSystem.h>
Public Member Functions
CoordinateSystem ()
CoordinateSystem (const CoordinateSystem &)=default
CoordinateSystem (CoordinateSystem &&)=default
~CoordinateSystem ()=default
CoordinateSystem & operator= (const CoordinateSystem &)=default
CoordinateSystem & operator= (CoordinateSystem &&)=default
void setAxis (const Axis &axis)
void setAxes (const Axis &, const Vector3d &xd)
void setAxes (const Vector3d &n, const Vector3d &xd)
const Axis & getAxis () const
void setXDirection (const Vector3d &)
const Vector3d & getXDirection () const
void setYDirection (const Vector3d &)
const Vector3d & getYDirection () const
void setZDirection (const Vector3d &)
const Vector3d & getZDirection () const
void setPosition (const Vector3d &pos)
const Vector3d & getPosition () const
Placement displacement (const CoordinateSystem &cs) const
void transformTo (Vector3d &pnt)
void transform (const Placement &plm)
void transform (const Rotation &rot)
void setPlacement (const Placement &plm)
Detailed Description
Describes a right-handed coordinate system in 3D space.
Author
Werner Mayer
Definition at line 55 of file CoordinateSystem.h.
Constructor & Destructor Documentation
CoordinateSystem() [1/3]
CoordinateSystem::CoordinateSystem ()
Construct a default coordinate system with position in (0,0,0), with X axis (1,0,0), with Y axis (0,1,0) and Z axis (0,0,1)
Definition at line 33 of file CoordinateSystem.cpp.
CoordinateSystem() [2/3]
Base::CoordinateSystem::CoordinateSystem (const CoordinateSystem &) default
CoordinateSystem() [3/3]
Base::CoordinateSystem::CoordinateSystem (CoordinateSystem &&) default
~CoordinateSystem()
Base::CoordinateSystem::~CoordinateSystem () default
Member Function Documentation
displacement()
Placement CoordinateSystem::displacement (const CoordinateSystem & cs) const
This computes the displacement from this coordinate system to the given coordinate system cs
Definition at line 110 of file CoordinateSystem.cpp.
References a, RobotExample::B, SCL.SimpleDataTypes::b, RobotExample::C, Base::Axis::getBase(), Base::Axis::getDirection(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
getAxis()
const Axis& Base::CoordinateSystem::getAxis () const inline
Definition at line 101 of file CoordinateSystem.h.
getPosition()
const Vector3d& Base::CoordinateSystem::getPosition () const inline
Definition at line 132 of file CoordinateSystem.h.
getXDirection()
const Vector3d& Base::CoordinateSystem::getXDirection () const inline
Definition at line 108 of file CoordinateSystem.h.
getYDirection()
const Vector3d& Base::CoordinateSystem::getYDirection () const inline
Definition at line 115 of file CoordinateSystem.h.
getZDirection()
const Vector3d& Base::CoordinateSystem::getZDirection () const inline
Definition at line 124 of file CoordinateSystem.h.
operator=() [1/2]
CoordinateSystem& Base::CoordinateSystem::operator= (const CoordinateSystem &) default
operator=() [2/2]
CoordinateSystem& Base::CoordinateSystem::operator= (CoordinateSystem &&) default
setAxes() [1/2]
void CoordinateSystem::setAxes (const Axis & vec, const Vector3d & xd)
Sets the main axis. X and Y dir are adjusted accordingly. The main axis must not be parallel to xd
Definition at line 39 of file CoordinateSystem.cpp.
References Base::Vector3< double >::epsilon(), Base::Vector3< float_type >::Normalize(), Base::Axis::setBase(), Base::Axis::setDirection(), Base::Vector3< float_type >::Sqr(), and SurfaceTests.TestBlendCurve::vec.
Referenced by setAxis(), and setZDirection().
setAxes() [2/2]
void CoordinateSystem::setAxes (const Vector3d & n, const Vector3d & xd)
Sets the main axis. X and Y dir are adjusted accordingly. The main axis n must not be parallel to xd
Definition at line 58 of file CoordinateSystem.cpp.
References Base::Vector3< double >::epsilon(), Base::Vector3< float_type >::Normalize(), Base::Axis::setDirection(), and Base::Vector3< float_type >::Sqr().
setAxis()
void CoordinateSystem::setAxis (const Axis & axis)
Sets the main axis. X and Y dir are adjusted accordingly. The main axis v must not be parallel to the X axis
Definition at line 76 of file CoordinateSystem.cpp.
References setAxes().
setPlacement()
void CoordinateSystem::setPlacement (const Placement & plm)
Set the placement plm to the coordinate system.
Definition at line 174 of file CoordinateSystem.cpp.
References Base::Placement::getPosition(), Base::Placement::getRotation(), Base::Rotation::multVec(), Base::Axis::setBase(), and Base::Axis::setDirection().
setPosition()
void Base::CoordinateSystem::setPosition (const Vector3d & pos) inline
Definition at line 128 of file CoordinateSystem.h.
setXDirection()
void CoordinateSystem::setXDirection (const Vector3d & dir)
The passed vector must not be parallel to the main axis
Definition at line 81 of file CoordinateSystem.cpp.
References Base::Vector3< double >::epsilon(), Base::Axis::getDirection(), Base::Vector3< float_type >::Normalize(), and Base::Vector3< float_type >::Sqr().
setYDirection()
void CoordinateSystem::setYDirection (const Vector3d & dir)
The passed vector must not be parallel to the main axis
Definition at line 93 of file CoordinateSystem.cpp.
References Base::Vector3< double >::epsilon(), Base::Axis::getDirection(), Base::Vector3< float_type >::Normalize(), and Base::Vector3< float_type >::Sqr().
setZDirection()
void CoordinateSystem::setZDirection (const Vector3d & dir)
Sets the main axis. X and Y dir are adjusted accordingly. The main axis must not be parallel to the X axis
Definition at line 105 of file CoordinateSystem.cpp.
References setAxes().
transform() [1/2]
void CoordinateSystem::transform (const Placement & plm)
Apply the placement plm to the coordinate system.
Definition at line 158 of file CoordinateSystem.cpp.
References Base::Placement::getRotation(), and Base::Rotation::multVec().
Referenced by ArchIFCView.IfcContextView::setupContextMenu(), draftviewproviders.view_hatch.ViewProviderDraftHatch::setupContextMenu(), draftviewproviders.view_base.ViewProviderDraft::setupContextMenu(), ArchAxis._ViewProviderAxis::setupContextMenu(), and ArchSite._ViewProviderSite::setupContextMenu().
transform() [2/2]
void CoordinateSystem::transform (const Rotation & rot)
Apply the rotation rot to the coordinate system.
Definition at line 165 of file CoordinateSystem.cpp.
References Base::Axis::getDirection(), Base::Rotation::multVec(), and Base::Axis::setDirection().
Referenced by ArchIFCView.IfcContextView::setupContextMenu(), draftviewproviders.view_hatch.ViewProviderDraftHatch::setupContextMenu(), draftviewproviders.view_base.ViewProviderDraft::setupContextMenu(), ArchAxis._ViewProviderAxis::setupContextMenu(), and ArchSite._ViewProviderSite::setupContextMenu().
transformTo()
void CoordinateSystem::transformTo (Vector3d & pnt)
Transform the point pnt to be in this coordinate system
Definition at line 153 of file CoordinateSystem.cpp.
References Base::Axis::getBase(), and Base::Vector3< float_type >::TransformToCoordinateSystem().
The documentation for this class was generated from the following files:
CoordinateSystem.h
CoordinateSystem.cpp