FreeCAD: PartGui::CrossSections Class Reference
PartGui::CrossSections Class Reference
#include <CrossSections.h>
Public Member Functions
CrossSections (const Base::BoundBox3d &bb, QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~CrossSections () override
void accept () override
void apply ()
Protected Member Functions
void changeEvent (QEvent *e) override
void keyPressEvent (QKeyEvent *) override
Detailed Description
Definition at line 42 of file Part/Gui/CrossSections.h.
Constructor & Destructor Documentation
CrossSections()
CrossSections::CrossSections (const Base::BoundBox3d & bb, QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags()) explicit
Definition at line 121 of file Part/Gui/CrossSections.cpp.
References Gui::Application::activeDocument(), SCL.SimpleDataTypes::c, toolbit-attributes::doc, Base::BoundBox3< Precision >::GetCenter(), Gui::Application::Instance, and Base::Unit::Length.
~CrossSections()
CrossSections::~CrossSections () override
Definition at line 149 of file Part/Gui/CrossSections.cpp.
Member Function Documentation
accept()
void CrossSections::accept () override
Definition at line 205 of file Part/Gui/CrossSections.cpp.
References apply().
Referenced by PartGui::TaskCrossSections::accept().
apply()
void CrossSections::apply ()
Definition at line 211 of file Part/Gui/CrossSections.cpp.
References a, Gui::Command::App, SCL.SimpleDataTypes::b, draftgeoutils.faces::bind(), SCL.SimpleDataTypes::c, toolbit-attributes::doc, Base::Persistence::getClassTypeId(), draftutils.utils::getObjectsOfType, Part::Feature::getTopoShape(), Part::PropertyPartShape::getValue(), draftgeoutils.general::isNull(), Base::SequencerLauncher::next(), App::DocumentObject::purgeTouched(), runCommand, toolbit-attributes::s, Gui::Selection(), Part::PropertyPartShape::setValue(), Part::Feature::Shape, and src.Mod.PartDesign.fcgear.svggear::w.
Referenced by accept(), and PartGui::TaskCrossSections::clicked().
changeEvent()
void CrossSections::changeEvent (QEvent * e) override protected
Definition at line 188 of file Part/Gui/CrossSections.cpp.
References SCL.SimpleDataTypes::e.
keyPressEvent()
void CrossSections::keyPressEvent (QKeyEvent * ke) override protected
Definition at line 198 of file Part/Gui/CrossSections.cpp.
The documentation for this class was generated from the following files:
Part/Gui/CrossSections.h
Part/Gui/CrossSections.cpp