FreeCAD: Start::ExamplesModel Class Reference
Start::ExamplesModel Class Reference
#include <ExamplesModel.h>
Public Member Functions
ExamplesModel (QObject *parent=nullptr)
void loadExamples ()
Public Member Functions inherited from Start::DisplayedFilesModel
DisplayedFilesModel (QObject *parent=nullptr)
int rowCount (const QModelIndex &parent=QModelIndex()) const override
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
void addFile (const QString &filePath)
void clear ()
Additional Inherited Members
Protected Member Functions inherited from Start::DisplayedFilesModel
QHash< int, QByteArray > roleNames () const override
void reCacheFileInfo ()
Detailed Description
A model for displaying a list of files including a thumbnail or icon, plus various file statistics.
Definition at line 59 of file ExamplesModel.h.
Constructor & Destructor Documentation
ExamplesModel()
ExamplesModel::ExamplesModel (QObject * parent = nullptr) explicit
Definition at line 35 of file ExamplesModel.cpp.
References App::Application::getResourceDir().
Member Function Documentation
loadExamples()
void ExamplesModel::loadExamples ()
Definition at line 42 of file ExamplesModel.cpp.
References Start::DisplayedFilesModel::addFile(), Start::DisplayedFilesModel::clear(), Base::Console(), and Base::ConsoleSingleton::Warning().
Referenced by StartGui::StartView::configureExamplesListWidget().
The documentation for this class was generated from the following files:
ExamplesModel.h
ExamplesModel.cpp