FreeCAD: Gui::Dialog::DlgSettingsNavigation Class Reference
Gui::Dialog::DlgSettingsNavigation Class Reference
#include <DlgSettingsNavigation.h>
Public Member Functions
DlgSettingsNavigation (QWidget *parent=nullptr)
~DlgSettingsNavigation () override
void saveSettings () override
void loadSettings () override
void resetSettingsToDefaults () override
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Protected Member Functions
void changeEvent (QEvent *e) override
void retranslate ()
void addOrientations ()
void translateOrientations ()
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
Detailed Description
The Ui_DlgSettingsNavigation class implements a preference page to change settings for the Inventor viewer.
Author
Werner Mayer
Definition at line 42 of file DlgSettingsNavigation.h.
Constructor & Destructor Documentation
DlgSettingsNavigation()
DlgSettingsNavigation::DlgSettingsNavigation (QWidget * parent = nullptr) explicit
Constructs a DlgSettingsNavigation which is a child of 'parent', with the name 'name' and widget flags set to 'f'
Definition at line 54 of file DlgSettingsNavigation.cpp.
References retranslate().
~DlgSettingsNavigation()
DlgSettingsNavigation::~DlgSettingsNavigation () override default
Destroys the object and frees any allocated resources
Member Function Documentation
addOrientations()
void DlgSettingsNavigation::addOrientations () protected
Definition at line 201 of file DlgSettingsNavigation.cpp.
References draftgeoutils.intersections::connect(), App::GetApplication(), ParameterGrp::GetASCII(), ParameterGrp::GetFloat(), ParameterGrp::GetGroup(), and App::Application::GetParameterGroupByPath().
Referenced by loadSettings().
changeEvent()
void DlgSettingsNavigation::changeEvent (QEvent * e) override protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
Definition at line 309 of file DlgSettingsNavigation.cpp.
References geoff_geometry::corner(), SCL.SimpleDataTypes::e, retranslate(), and translateOrientations().
loadSettings()
void DlgSettingsNavigation::loadSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 136 of file DlgSettingsNavigation.cpp.
References addOrientations(), Base::clamp(), draftgeoutils.intersections::connect(), App::GetApplication(), ParameterGrp::GetASCII(), ParameterGrp::GetBool(), Base::BaseClass::getClassTypeId(), ParameterGrp::GetInt(), App::Application::GetParameterGroupByPath(), Path.Base.Util::setProperty(), and Gui::NavigationStyle::Trackball.
resetSettingsToDefaults()
void DlgSettingsNavigation::resetSettingsToDefaults () override virtual
Reimplemented from Gui::Dialog::PreferencePage.
Definition at line 245 of file DlgSettingsNavigation.cpp.
References App::GetApplication(), ParameterGrp::GetGroup(), App::Application::GetParameterGroupByPath(), ParameterGrp::RemoveASCII(), ParameterGrp::RemoveBool(), ParameterGrp::RemoveFloat(), ParameterGrp::RemoveInt(), and Gui::Dialog::PreferencePage::resetSettingsToDefaults().
retranslate()
void DlgSettingsNavigation::retranslate () protected
Definition at line 327 of file DlgSettingsNavigation.cpp.
References Gui::UserNavigationStyle::getUserFriendlyNames(), and src.Mod.AddonManager.Addon::translate.
Referenced by changeEvent(), and DlgSettingsNavigation().
saveSettings()
void DlgSettingsNavigation::saveSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 73 of file DlgSettingsNavigation.cpp.
References App::GetApplication(), ParameterGrp::GetGroup(), App::Application::GetParameterGroupByPath(), ParameterGrp::RemoveASCII(), Gui::Dialog::PreferencePage::requireRestart(), ParameterGrp::SetASCII(), ParameterGrp::SetBool(), ParameterGrp::SetFloat(), and ParameterGrp::SetInt().
translateOrientations()
void DlgSettingsNavigation::translateOrientations () protected
Definition at line 231 of file DlgSettingsNavigation.cpp.
Referenced by changeEvent().
The documentation for this class was generated from the following files:
DlgSettingsNavigation.h
DlgSettingsNavigation.cpp