FreeCAD: SpreadsheetGui::DlgBindSheet Class Reference
SpreadsheetGui::DlgBindSheet Class Reference
#include <DlgBindSheet.h>
Public Slots
void onDiscard ()
Public Member Functions
DlgBindSheet (Spreadsheet::Sheet *sheet, const std::vector< App::Range > &range, QWidget *parent=nullptr)
~DlgBindSheet () override
void accept () override
Detailed Description
Definition at line 37 of file DlgBindSheet.h.
Constructor & Destructor Documentation
DlgBindSheet()
DlgBindSheet::DlgBindSheet (Spreadsheet::Sheet * sheet, const std::vector< App::Range > & range, QWidget * parent = nullptr) explicit
Definition at line 42 of file DlgBindSheet.cpp.
References App::CellAddress::col(), draftgeoutils.intersections::connect(), toolbit-attributes::doc, App::Range::from(), App::GetApplication(), Spreadsheet::Sheet::getCellBinding(), App::DocumentObject::getDocument(), App::ObjectIdentifier::getDocumentObject(), App::Document::getObjectsOfType(), importers.exportIFC::getText(), App::PropertyString::getValue(), App::DocumentObject::Label, NavigationIndicatorGui::label, onDiscard(), App::CellAddress::row(), App::CellAddress::setCol(), App::CellAddress::setRow(), App::Range::to(), App::CellAddress::toString(), and Path.Post.scripts.grbl_post::type.
~DlgBindSheet()
DlgBindSheet::~DlgBindSheet () override
Definition at line 153 of file DlgBindSheet.cpp.
Member Function Documentation
accept()
void DlgBindSheet::accept () override
Definition at line 158 of file DlgBindSheet.cpp.
References Gui::Command::abortCommand(), Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), toolbit-attributes::doc, Gui::Command::Doc, doCommand, SCL.SimpleDataTypes::e, FC_THROWM, App::GetApplication(), App::Application::getDocument(), App::DocumentObject::getDocument(), App::Document::getObject(), App::CellAddress::isValid(), Path.Op.Surface::msg, Gui::Command::openCommand(), App::quote(), App::Range::size(), App::stringToAddress(), and Path.Log::warning().
onDiscard
void DlgBindSheet::onDiscard () slot
Definition at line 283 of file DlgBindSheet.cpp.
References Gui::Command::abortCommand(), Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), Gui::Command::Doc, doCommand, SCL.SimpleDataTypes::e, and Gui::Command::openCommand().
Referenced by DlgBindSheet().
The documentation for this class was generated from the following files:
DlgBindSheet.h
DlgBindSheet.cpp