FreeCAD: TechDrawGui::QGIHighlight Class Reference
TechDrawGui::QGIHighlight Class Reference
#include <QGIHighlight.h>
Public Types
enum { Type = QGraphicsItem::UserType + 176 }
Public Types inherited from TechDrawGui::QGIDecoration
enum { Type = QGraphicsItem::UserType + 173 }
Public Member Functions
QGIHighlight ()
~QGIHighlight () override
int type () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
void setBounds (double x1, double y1, double x2, double y2)
void setReference (const char *sym)
void setFont (QFont f, double fsize)
void draw () override
void setInteractive (bool state)
void setFeatureName (std::string name)
std::string getFeatureName ()
void setReferenceAngle (double angle)
void onDragFinished () override
void setLinePen (QPen isoPen)
Public Member Functions inherited from TechDrawGui::QGIDecoration
QGIDecoration ()
~QGIDecoration () override=default
int type () const override
QRectF boundingRect () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
void setWidth (double w)
double getWidth ()
void setStyle (Qt::PenStyle s)
void setColor (QColor c)
QColor getColor ()
void setFill (Qt::BrushStyle bs)
void makeMark (double x, double y)
void makeMark (Base::Vector3d v)
Protected Member Functions
QColor getHighlightColor ()
void makeHighlight ()
void makeReference ()
void setTools ()
int getHoleStyle ()
Protected Member Functions inherited from TechDrawGui::QGIDecoration
void setPrettyNormal ()
void setPrettyPre ()
void setPrettySel ()
virtual QColor prefNormalColor ()
virtual QColor prefPreColor ()
virtual QColor prefSelectColor ()
Additional Inherited Members
Protected Attributes inherited from TechDrawGui::QGIDecoration
QPen m_pen
QBrush m_brush
QColor m_colCurrent
QColor m_colNormal
double m_width
Qt::PenStyle m_styleCurrent
Qt::BrushStyle m_brushCurrent
int m_dragState
Detailed Description
Definition at line 62 of file QGIHighlight.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 88 of file QGIHighlight.h.
Constructor & Destructor Documentation
QGIHighlight()
QGIHighlight::QGIHighlight () explicit
Definition at line 40 of file QGIHighlight.cpp.
References TechDrawGui::Rez::guiX(), setInteractive(), and TechDrawGui::QGIDecoration::setWidth().
~QGIHighlight()
QGIHighlight::~QGIHighlight () override
Definition at line 61 of file QGIHighlight.cpp.
Member Function Documentation
draw()
void QGIHighlight::draw () override virtual
Reimplemented from TechDrawGui::QGIDecoration.
Definition at line 77 of file QGIHighlight.cpp.
References makeHighlight(), and makeReference().
Referenced by TechDrawGui::TaskDetail::editByHighlight().
getFeatureName()
std::string TechDrawGui::QGIHighlight::getFeatureName () inline
Definition at line 101 of file QGIHighlight.h.
getHighlightColor()
QColor QGIHighlight::getHighlightColor () protected
Definition at line 170 of file QGIHighlight.cpp.
References TechDrawGui::PreferencesGui::sectionLineQColor().
getHoleStyle()
int QGIHighlight::getHoleStyle () protected
Definition at line 175 of file QGIHighlight.cpp.
References TechDraw::Preferences::mattingStyle().
Referenced by makeHighlight().
makeHighlight()
void QGIHighlight::makeHighlight () protected
Definition at line 85 of file QGIHighlight.cpp.
References getHoleStyle().
Referenced by draw().
makeReference()
void QGIHighlight::makeReference () protected
Definition at line 99 of file QGIHighlight.cpp.
References exportCSG::center(), KDL::cos(), TechDrawGui::QGIView::exactFontSize(), TechDraw::DrawUtil::fpCompare(), M_PI, KDL::sin(), and TechDrawGui::QGCustomText::tightBoundingAdjust().
Referenced by draw().
onDragFinished()
void QGIHighlight::onDragFinished () override virtual
Reimplemented from TechDrawGui::QGIDecoration.
Definition at line 66 of file QGIHighlight.cpp.
References TechDrawGui::QGIViewPart::highlightMoved(), Init::parent, and RobotExample::pos.
paint()
void QGIHighlight::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) override
Definition at line 180 of file QGIHighlight.cpp.
References TechDrawGui::QGIDecoration::paint(), and setTools().
setBounds()
void QGIHighlight::setBounds (double x1, double y1, double x2, double y2)
Definition at line 151 of file QGIHighlight.cpp.
References TechDrawGui::Rez::guiX().
setFeatureName()
void TechDrawGui::QGIHighlight::setFeatureName (std::string name) inline
Definition at line 100 of file QGIHighlight.h.
setFont()
void QGIHighlight::setFont (QFont f, double fsize)
Definition at line 162 of file QGIHighlight.cpp.
References SCL.SimpleDataTypes::f.
setInteractive()
void QGIHighlight::setInteractive (bool state)
Definition at line 142 of file QGIHighlight.cpp.
Referenced by QGIHighlight().
setLinePen()
void QGIHighlight::setLinePen (QPen isoPen)
Definition at line 203 of file QGIHighlight.cpp.
References TechDrawGui::QGIDecoration::m_pen.
setReference()
void QGIHighlight::setReference (const char * sym)
Definition at line 157 of file QGIHighlight.cpp.
setReferenceAngle()
void TechDrawGui::QGIHighlight::setReferenceAngle (double angle) inline
Definition at line 102 of file QGIHighlight.h.
setTools()
void QGIHighlight::setTools () protected
Definition at line 189 of file QGIHighlight.cpp.
References TechDrawGui::QGIDecoration::m_brush, TechDrawGui::QGIDecoration::m_brushCurrent, TechDrawGui::QGIDecoration::m_colCurrent, TechDrawGui::QGIDecoration::m_pen, and TechDrawGui::QGIDecoration::m_width.
Referenced by paint().
type()
int TechDrawGui::QGIHighlight::type () const inline override
Definition at line 89 of file QGIHighlight.h.
The documentation for this class was generated from the following files:
QGIHighlight.h
QGIHighlight.cpp