FreeCAD: SandboxGui::TaskPanelView Class Reference
SandboxGui::TaskPanelView Class Reference
#include <TaskPanelView.h>
Public Member Functions
TaskPanelView (QWidget *parent=0)
virtual ~TaskPanelView ()
void executeAction ()
void on_rbDefaultScheme_toggled (bool b)
void on_rbXPBlueScheme_toggled (bool b)
void on_rbXPBlue2Scheme_toggled (bool b)
void on_rbVistaScheme_toggled (bool b)
void on_rbMacScheme_toggled (bool b)
void on_rbAndroidScheme_toggled (bool b)
Detailed Description
A test class. A more elaborate class description.
Definition at line 54 of file TaskPanelView.h.
Constructor & Destructor Documentation
TaskPanelView()
TaskPanelView::TaskPanelView (QWidget * parent = 0)
A constructor. A more elaborate description of the constructor.
Definition at line 369 of file TaskPanelView.cpp.
References NavigationIndicatorGui::a1, NavigationIndicatorGui::a2, NavigationIndicatorGui::a3, NavigationIndicatorGui::a4, Path.Post.scripts.dynapath_4060_post::action, QSint::ActionGroup::addAction(), Gui::CommandManager::addTo(), QSint::ActionGroup::addWidget(), draftgeoutils.faces::bind(), Gui::Application::commandManager(), draftgeoutils.intersections::connect(), QSint::WinXPPanelScheme::defaultScheme(), executeAction(), QSint::ActionGroup::groupLayout(), Gui::Application::Instance, on_rbAndroidScheme_toggled(), on_rbDefaultScheme_toggled(), on_rbMacScheme_toggled(), on_rbVistaScheme_toggled(), on_rbXPBlue2Scheme_toggled(), on_rbXPBlueScheme_toggled(), nativeifc.ifc_tools::save(), Gui::ActionFunction::toggle(), and Gui::ActionFunction::trigger().
~TaskPanelView()
TaskPanelView::~TaskPanelView () virtual
A destructor. A more elaborate description of the destructor.
Definition at line 584 of file TaskPanelView.cpp.
Member Function Documentation
executeAction()
void TaskPanelView::executeAction ()
Definition at line 588 of file TaskPanelView.cpp.
Referenced by TaskPanelView().
on_rbAndroidScheme_toggled()
void TaskPanelView::on_rbAndroidScheme_toggled (bool b)
Definition at line 633 of file TaskPanelView.cpp.
References SCL.SimpleDataTypes::b, and QSint::AndroidPanelScheme::defaultScheme().
Referenced by TaskPanelView().
on_rbDefaultScheme_toggled()
void TaskPanelView::on_rbDefaultScheme_toggled (bool b)
Definition at line 593 of file TaskPanelView.cpp.
References SCL.SimpleDataTypes::b, and QSint::ActionPanelScheme::defaultScheme().
Referenced by TaskPanelView().
on_rbMacScheme_toggled()
void TaskPanelView::on_rbMacScheme_toggled (bool b)
Definition at line 625 of file TaskPanelView.cpp.
References SCL.SimpleDataTypes::b, and QSint::MacPanelScheme::defaultScheme().
Referenced by TaskPanelView().
on_rbVistaScheme_toggled()
void TaskPanelView::on_rbVistaScheme_toggled (bool b)
Definition at line 617 of file TaskPanelView.cpp.
References SCL.SimpleDataTypes::b, and QSint::WinVistaPanelScheme::defaultScheme().
Referenced by TaskPanelView().
on_rbXPBlue2Scheme_toggled()
void TaskPanelView::on_rbXPBlue2Scheme_toggled (bool b)
Definition at line 609 of file TaskPanelView.cpp.
References SCL.SimpleDataTypes::b, and QSint::WinXPPanelScheme2::defaultScheme().
Referenced by TaskPanelView().
on_rbXPBlueScheme_toggled()
void TaskPanelView::on_rbXPBlueScheme_toggled (bool b)
Definition at line 601 of file TaskPanelView.cpp.
References SCL.SimpleDataTypes::b, and QSint::WinXPPanelScheme::defaultScheme().
Referenced by TaskPanelView().
The documentation for this class was generated from the following files:
TaskPanelView.h
TaskPanelView.cpp