FreeCAD: TechDrawGui::QGIView Class Reference
TechDrawGui::QGIView Class Reference
#include <QGIView.h>
Public Types
enum { Type = QGraphicsItem::UserType + 101 }
Public Member Functions
QGIView ()
int type () const override
QRectF boundingRect () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
const char * getViewName () const
const std::string getViewNameAsString () const
void setViewFeature (TechDraw::DrawView *obj)
TechDraw::DrawView * getViewObject () const
MDIViewPage * getMDIViewPage () const
double getScale ()
void hideFrame ()
virtual bool getFrameState ()
virtual void toggleCache (bool state)
virtual void updateView (bool update=false)
virtual void drawBorder ()
virtual void isVisible (bool state)
virtual bool isVisible ()
virtual bool getGroupSelection ()
virtual void setGroupSelection (bool isSelected)
virtual void setGroupSelection (bool isSelected, const std::vector< std::string > &subNames)
virtual void draw ()
virtual void drawCaption ()
virtual void rotateView ()
void makeMark (double xPos, double yPos, QColor color=Qt::red)
void makeMark (Base::Vector3d pos, QColor color=Qt::red)
void makeMark (QPointF pos, QColor color=Qt::red)
static const double DefaultFontSizeInMM = 5.0
void setPosition (qreal xPos, qreal yPos)
qreal getY ()
bool isInnerView () const
void isInnerView (bool state)
QGIViewClip * getClipGroup ()
bool isSnapping ()
void snapPosition (QPointF &position)
void snapSectionView (const TechDraw::DrawViewSection *sectionView, QPointF &newPosition)
Base::Vector3d projItemPagePos (TechDraw::DrawViewPart *item)
void alignTo (QGraphicsItem *, const QString &alignment)
QColor prefNormalColor ()
QColor getNormalColor ()
void setNormalColor (QColor color)
QColor getPreColor ()
QColor getSelectColor ()
QColor getCurrentColor ()
void setCurrentColor (QColor color)
QColor getSettingColor ()
void setSettingColor (QColor color)
virtual void setStack (int z)
virtual void setStackFromVP ()
QFont getFont ()
void setFont (QFont font)
virtual void removeChild (QGIView *child)
virtual void addArbitraryItem (QGraphicsItem *qgi)
virtual void switchParentItem (QGIView *targetParent)
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
static Gui::ViewProvider * getViewProvider (App::DocumentObject *obj)
static ViewProviderPage * getViewProviderPage (TechDraw::DrawView *dView)
static int calculateFontPixelSize (double sizeInMillimetres)
static int calculateFontPixelWidth (const QFont &font)
static QString getPrefFont ()
static double getPrefFontSize ()
static double getDimFontSize ()
static int exactFontSize (std::string fontFamily, double nominalSize)
QGIView * getQGIVByName (std::string name)
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
virtual QRectF customChildrenBoundingRect () const
void dumpRect (const char *text, QRectF rect)
Base::Reference< ParameterGrp > getParmGroupCol ()
Detailed Description
Definition at line 77 of file QGIView.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 83 of file QGIView.h.
Constructor & Destructor Documentation
QGIView()
QGIView::QGIView ()
Definition at line 76 of file QGIView.cpp.
References TechDrawGui::QGCustomImage::imageSize(), TechDrawGui::QGCustomImage::load(), and prefNormalColor().
Member Function Documentation
addArbitraryItem()
void QGIView::addArbitraryItem (QGraphicsItem * qgi) virtual
Definition at line 846 of file QGIView.cpp.
alignTo()
void QGIView::alignTo (QGraphicsItem * item, const QString & alignment)
Definition at line 155 of file QGIView.cpp.
boundingRect()
QRectF QGIView::boundingRect () const override
Definition at line 753 of file QGIView.cpp.
Referenced by rotateView().
calculateFontPixelSize()
int QGIView::calculateFontPixelSize (double sizeInMillimetres) static
Definition at line 917 of file QGIView.cpp.
References TechDrawGui::Rez::guiX().
Referenced by TechDrawGui::QGIViewBalloon::placeBalloon().
calculateFontPixelWidth()
int QGIView::calculateFontPixelWidth (const QFont & font) static
Definition at line 924 of file QGIView.cpp.
References Gui::QtTools::horizontalAdvance().
customChildrenBoundingRect()
QRectF QGIView::customChildrenBoundingRect () const protected virtual
Definition at line 717 of file QGIView.cpp.
References result.
Referenced by drawBorder(), and drawCaption().
draw()
void QGIView::draw () virtual
Reimplemented in TechDrawGui::QGIViewDimension, TechDrawGui::QGIViewBalloon, TechDrawGui::QGILeaderLine, TechDrawGui::QGIWeldSymbol, TechDrawGui::QGIViewPart, TechDrawGui::QGIRichAnno, TechDrawGui::QGIViewSection, TechDrawGui::QGIViewClip, TechDrawGui::QGIViewSymbol, TechDrawGui::QGIViewAnnotation, and TechDrawGui::QGIViewImage.
Definition at line 583 of file QGIView.cpp.
References drawBorder(), getViewObject(), TechDrawGui::Rez::guiX(), ArchFence::hide(), isVisible(), setPosition(), bimcommands.BimViews::show(), DrawingExample::X, and DrawingExample::Y.
Referenced by TechDrawGui::QGIViewAnnotation::draw(), TechDrawGui::QGIViewSymbol::draw(), TechDrawGui::QGIRichAnno::draw(), setStack(), TechDrawGui::ViewProviderDrawingView::show(), and updateView().
drawBorder()
void QGIView::drawBorder () virtual
Reimplemented in TechDrawGui::QGIViewBalloon, TechDrawGui::QGIViewDimension, TechDrawGui::QGIWeldSymbol, TechDrawGui::QGILeaderLine, TechDrawGui::QGIRichAnno, and TechDrawGui::QGIProjGroup.
Definition at line 628 of file QGIView.cpp.
References SCL.SimpleDataTypes::b, customChildrenBoundingRect(), drawCaption(), exactFontSize(), getFrameState(), getViewObject(), getViewProvider(), labelCaptionFudge, and ZVALUE::LOCK.
Referenced by TechDrawGui::QGIViewClip::draw(), draw(), hoverEnterEvent(), hoverLeaveEvent(), and itemChange().
drawCaption()
void QGIView::drawCaption () virtual
Definition at line 602 of file QGIView.cpp.
References customChildrenBoundingRect(), exactFontSize(), getFrameState(), getViewObject(), getViewProvider(), and labelCaptionFudge.
Referenced by drawBorder().
dumpRect()
void QGIView::dumpRect (const char * text, QRectF rect) protected
Definition at line 932 of file QGIView.cpp.
References Base::Console(), and Base::ConsoleSingleton::Message().
exactFontSize()
int QGIView::exactFontSize (std::string fontFamily, double nominalSize) static
Definition at line 939 of file QGIView.cpp.
References TechDrawGui::Rez::guiX().
Referenced by TechDrawGui::QGIViewAnnotation::drawAnnotation(), drawBorder(), drawCaption(), TechDrawGui::QGIWeldSymbol::drawTailText(), TechDrawGui::QGIWeldSymbol::drawTile(), TechDrawGui::QGIHighlight::makeReference(), TechDrawGui::QGISectionLine::makeSymbolsISO(), TechDrawGui::QGISectionLine::makeSymbolsTrad(), TechDrawGui::QGIViewBalloon::placeBalloon(), TechDrawGui::QGIViewBalloon::updateBalloon(), and TechDrawGui::QGIViewDimension::updateDim().
getClipGroup()
QGIViewClip * QGIView::getClipGroup ()
Definition at line 489 of file QGIView.cpp.
References getViewObject().
getCurrentColor()
QColor TechDrawGui::QGIView::getCurrentColor () inline
Definition at line 139 of file QGIView.h.
Referenced by TechDrawGui::QGIWeldSymbol::drawAllAround(), TechDrawGui::QGIWeldSymbol::drawTailText(), and TechDrawGui::QGIWeldSymbol::drawTile().
getDimFontSize()
static double TechDrawGui::QGIView::getDimFontSize () static
getFont()
QFont TechDrawGui::QGIView::getFont () inline
Definition at line 157 of file QGIView.h.
getFrameState()
bool QGIView::getFrameState () virtual
Definition at line 823 of file QGIView.cpp.
References TechDraw::DrawView::findParentPage(), App::DocumentObject::getDocument(), Gui::Application::getDocument(), TechDrawGui::ViewProviderPage::getFrameState(), getViewObject(), Gui::Document::getViewProvider(), and Gui::Application::Instance.
Referenced by TechDrawGui::QGIViewClip::draw(), drawBorder(), and drawCaption().
getGroupSelection()
bool QGIView::getGroupSelection () virtual
Reimplemented in TechDrawGui::QGIViewBalloon, TechDrawGui::QGIViewDimension, and TechDrawGui::QGIViewPart.
Definition at line 136 of file QGIView.cpp.
Referenced by TechDrawGui::MDIViewPage::clearSceneSelection().
getMDIViewPage()
MDIViewPage * QGIView::getMDIViewPage () const
Definition at line 784 of file QGIView.cpp.
References TechDrawGui::ViewProviderPage::getMDIViewPage(), getViewObject(), and getViewProviderPage().
getNormalColor()
QColor TechDrawGui::QGIView::getNormalColor () inline
Definition at line 135 of file QGIView.h.
Referenced by TechDrawGui::QGIWeldSymbol::hoverLeaveEvent(), TechDrawGui::QGIWeldSymbol::prefNormalColor(), TechDrawGui::QGILeaderLine::prefNormalColor(), TechDrawGui::QGIViewDimension::prefNormalColor(), TechDrawGui::QGIViewBalloon::prefNormalColor(), TechDrawGui::QGIWeldSymbol::QGIWeldSymbol(), and TechDrawGui::QGIWeldSymbol::setPrettyNormal().
getParmGroupCol()
Base::Reference< ParameterGrp > QGIView::getParmGroupCol () protected
Definition at line 907 of file QGIView.cpp.
References App::GetApplication(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
getPreColor()
QColor QGIView::getPreColor ()
Definition at line 897 of file QGIView.cpp.
References TechDrawGui::PreferencesGui::getAccessibleQColor(), and TechDrawGui::PreferencesGui::preselectQColor().
Referenced by TechDrawGui::QGIWeldSymbol::hoverEnterEvent(), hoverEnterEvent(), and TechDrawGui::QGIWeldSymbol::setPrettyPre().
getPrefFont()
static QString TechDrawGui::QGIView::getPrefFont () static
getPrefFontSize()
static double TechDrawGui::QGIView::getPrefFontSize () static
getQGIVByName()
QGIView * QGIView::getQGIVByName (std::string name) protected
Definition at line 758 of file QGIView.cpp.
References getViewNameAsString().
Referenced by TechDrawGui::QGIWeldSymbol::drawAllAround(), TechDrawGui::QGIViewClip::drawClip(), TechDrawGui::QGIWeldSymbol::drawFieldFlag(), and TechDrawGui::ViewProviderDrawingView::updateData().
getScale()
double QGIView::getScale ()
Definition at line 539 of file QGIView.cpp.
References TechDraw::DrawView::getScale(), and getViewObject().
Referenced by TechDrawGui::TaskLeaderLine::onTrackerFinished(), and snapSectionView().
getSelectColor()
QColor QGIView::getSelectColor ()
Definition at line 902 of file QGIView.cpp.
References TechDrawGui::PreferencesGui::getAccessibleQColor(), and TechDrawGui::PreferencesGui::selectQColor().
Referenced by TechDrawGui::QGIWeldSymbol::hoverEnterEvent(), hoverEnterEvent(), TechDrawGui::QGIWeldSymbol::hoverLeaveEvent(), hoverLeaveEvent(), itemChange(), and TechDrawGui::QGIWeldSymbol::setPrettySel().
getSettingColor()
QColor TechDrawGui::QGIView::getSettingColor () inline
Definition at line 141 of file QGIView.h.
getViewName()
const char * QGIView::getViewName () const
Definition at line 547 of file QGIView.cpp.
Referenced by TechDrawGui::QGSPage::addQView(), TechDrawGui::QGIViewClip::drawClip(), TechDrawGui::QGIProjGroup::getAnchorQItem(), and TechDrawGui::QGSPage::getQGIVByName().
getViewNameAsString()
const std::string QGIView::getViewNameAsString () const
Definition at line 551 of file QGIView.cpp.
Referenced by TechDrawGui::MDIViewPage::compareSelections(), and getQGIVByName().
getViewObject()
TechDraw::DrawView * QGIView::getViewObject () const
Definition at line 557 of file QGIView.cpp.
Referenced by _checkDirectPlacement(), TechDrawGui::QGSPage::addItemToParent(), TechDrawGui::QGSPage::addLeaderToParent(), TechDrawGui::QGSPage::addQView(), TechDrawGui::QGSPage::addRichAnnoToParent(), TechDrawGui::QGIViewDimension::arrowPositionsToFeature(), TechDrawGui::QGIViewBalloon::balloonLabelDragFinished(), TechDrawGui::QGIViewBalloon::balloonLabelDragged(), TechDrawGui::QGIViewDimension::datumLabelDragFinished(), TechDrawGui::QGIViewImage::draw(), draw(), TechDrawGui::QGILeaderLine::draw(), TechDrawGui::QGIViewDimension::draw(), TechDrawGui::QGIViewDimension::drawAngle(), TechDrawGui::QGIViewAnnotation::drawAnnotation(), TechDrawGui::QGIViewDimension::drawArrows(), TechDrawGui::QGIViewBalloon::drawBalloon(), drawBorder(), drawCaption(), TechDrawGui::QGIViewClip::drawClip(), TechDrawGui::QGIViewDimension::drawDistanceExecutive(), TechDrawGui::QGIViewDimension::drawDistanceOverride(), TechDrawGui::QGIViewImage::drawImage(), TechDrawGui::QGIViewSection::drawSectionFace(), TechDrawGui::QGIViewDimension::findIsoExt(), TechDrawGui::QGSPage::findParent(), getClipGroup(), TechDrawGui::QGIRichAnno::getFeature(), TechDrawGui::QGIWeldSymbol::getFeature(), getFrameState(), TechDrawGui::QGILeaderLine::getLeaderFeature(), TechDrawGui::QGILeaderLine::getLineWidth(), getMDIViewPage(), getScale(), TechDrawGui::QGIViewBalloon::getSourceView(), isVisible(), itemChange(), TechDrawGui::QGIViewAnnotation::mouseDoubleClickEvent(), TechDrawGui::QGIRichAnno::mouseDoubleClickEvent(), TechDrawGui::QGIDatumLabel::mouseDoubleClickEvent(), TechDrawGui::QGIBalloonLabel::mouseDoubleClickEvent(), mousePressEvent(), TechDrawGui::QGIProjGroup::mouseReleaseEvent(), TechDrawGui::QGIViewBalloon::placeBalloon(), TechDrawGui::QGILeaderLine::prefNormalColor(), TechDrawGui::QGIRichAnno::rectPen(), TechDrawGui::MDIViewPage::removeUnselectedTreeSelection(), TechDrawGui::QGIViewImage::rotateView(), TechDrawGui::QGIViewAnnotation::rotateView(), rotateView(), setStackFromVP(), TechDrawGui::QGIDatumLabel::setToleranceString(), snapPosition(), TechDrawGui::QGILeaderLine::startPathEdit(), TechDrawGui::QGIViewBalloon::updateBalloon(), TechDrawGui::QGIViewDimension::updateDim(), TechDrawGui::QGIViewImage::updateView(), TechDrawGui::QGIViewAnnotation::updateView(), TechDrawGui::QGIViewClip::updateView(), TechDrawGui::QGIRichAnno::updateView(), TechDrawGui::QGILeaderLine::updateView(), TechDrawGui::QGIViewSection::updateView(), updateView(), TechDrawGui::QGIViewDimension::updateView(), TechDrawGui::QGIViewBalloon::updateView(), and TechDrawGui::QGILeaderLine::useOldCoords().
getViewProvider()
Gui::ViewProvider * QGIView::getViewProvider (App::DocumentObject * obj) static
Definition at line 775 of file QGIView.cpp.
References App::DocumentObject::getDocument(), Gui::Application::getDocument(), Gui::Document::getViewProvider(), and Gui::Application::Instance.
Referenced by TechDrawGui::TaskSurfaceFinishSymbols::accept(), TechDrawGui::QGSPage::addQView(), TechDrawGui::TaskRichAnno::createAnnoFeature(), TechDrawGui::TaskLeaderLine::createLeaderFeature(), TechDrawGui::QGIViewImage::draw(), TechDrawGui::QGIRichAnno::draw(), TechDrawGui::QGILeaderLine::draw(), TechDrawGui::QGIViewDimension::draw(), TechDrawGui::QGIViewDimension::drawAngle(), TechDrawGui::QGIViewDimension::drawArrows(), TechDrawGui::QGIViewBalloon::drawBalloon(), drawBorder(), drawCaption(), TechDrawGui::QGIViewDimension::drawDistanceExecutive(), TechDrawGui::QGIViewDimension::drawDistanceOverride(), TechDrawGui::QGIViewSection::drawSectionFace(), TechDrawGui::QGIWeldSymbol::drawTailText(), TechDrawGui::QGIWeldSymbol::drawTile(), TechDrawGui::TaskLeaderLine::findParentQGIV(), TechDrawGui::TaskCenterLine::getCenterWidth(), TechDrawGui::TaskLineDecor::getFormatAccessPtr(), TechDrawGui::QGILeaderLine::getLineWidth(), isVisible(), itemChange(), TechDrawGui::QGILeaderLine::mouseDoubleClickEvent(), TechDrawGui::QGIDatumLabel::mouseDoubleClickEvent(), TechDrawGui::QGIBalloonLabel::mouseDoubleClickEvent(), TechDrawGui::QGIViewBalloon::placeBalloon(), TechDrawGui::QGILeaderLine::prefNormalColor(), TechDrawGui::QGIViewDimension::prefNormalColor(), TechDrawGui::QGIViewBalloon::prefNormalColor(), TechDrawGui::QGIRichAnno::rectPen(), setStackFromVP(), snapSectionView(), TechDrawGui::QGIViewBalloon::updateBalloon(), TechDrawGui::QGIViewDimension::updateDim(), TechDrawGui::QGIRichAnno::updateView(), TechDrawGui::QGILeaderLine::updateView(), TechDrawGui::QGIViewDimension::updateView(), TechDrawGui::QGIViewBalloon::updateView(), and TechDrawGui::QGILeaderLine::useOldCoords().
getViewProviderPage()
ViewProviderPage * QGIView::getViewProviderPage (TechDraw::DrawView * dView) static
Definition at line 796 of file QGIView.cpp.
References TechDraw::DrawView::findParentPage(), App::DocumentObject::getDocument(), Gui::Application::getDocument(), Gui::Document::getViewProvider(), and Gui::Application::Instance.
Referenced by getMDIViewPage(), and snapPosition().
getY()
qreal TechDrawGui::QGIView::getY () inline
Definition at line 122 of file QGIView.h.
References MovieTool::y.
Referenced by TechDrawGui::QGIProjGroup::mouseReleaseEvent().
hideFrame()
void QGIView::hideFrame ()
Definition at line 840 of file QGIView.cpp.
Referenced by TechDrawGui::QGIViewDimension::QGIViewDimension().
hoverEnterEvent()
void QGIView::hoverEnterEvent (QGraphicsSceneHoverEvent * event) override protected
Definition at line 447 of file QGIView.cpp.
References drawBorder(), getPreColor(), and getSelectColor().
Referenced by TechDrawGui::QGILeaderLine::hoverEnterEvent(), and TechDrawGui::QGIWeldSymbol::hoverEnterEvent().
hoverLeaveEvent()
void QGIView::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) override protected
Definition at line 461 of file QGIView.cpp.
References drawBorder(), TechDrawGui::PreferencesGui::getAccessibleQColor(), getSelectColor(), and TechDrawGui::PreferencesGui::normalQColor().
Referenced by TechDrawGui::QGILeaderLine::hoverLeaveEvent(), and TechDrawGui::QGIWeldSymbol::hoverLeaveEvent().
isInnerView() [1/2]
bool TechDrawGui::QGIView::isInnerView () const inline
Definition at line 123 of file QGIView.h.
Referenced by TechDrawGui::QGIViewClip::drawClip().
isInnerView() [2/2]
void TechDrawGui::QGIView::isInnerView (bool state) inline
Definition at line 124 of file QGIView.h.
isSnapping()
bool TechDrawGui::QGIView::isSnapping () inline
Definition at line 127 of file QGIView.h.
Referenced by TechDrawGui::ViewProviderDrawingView::updateData().
isVisible() [1/2]
bool QGIView::isVisible () virtual
Definition at line 124 of file QGIView.cpp.
References App::PropertyBool::getValue(), getViewObject(), getViewProvider(), and Gui::ViewProviderDocumentObject::Visibility.
Referenced by TechDrawGui::QGIViewImage::draw(), TechDrawGui::QGIViewAnnotation::draw(), TechDrawGui::QGIViewClip::draw(), TechDrawGui::QGIViewSection::draw(), TechDrawGui::QGIRichAnno::draw(), TechDrawGui::QGIWeldSymbol::draw(), draw(), TechDrawGui::QGILeaderLine::draw(), and TechDrawGui::QGIViewDimension::draw().
isVisible() [2/2]
void QGIView::isVisible (bool state) virtual
Definition at line 113 of file QGIView.cpp.
References getViewObject(), getViewProvider(), App::PropertyBool::setValue(), and Gui::ViewProviderDocumentObject::Visibility.
itemChange()
QVariant QGIView::itemChange (GraphicsItemChange change, const QVariant & value) override protected
Definition at line 161 of file QGIView.cpp.
References TechDrawGui::Rez::appX(), drawBorder(), TechDrawGui::PreferencesGui::getAccessibleQColor(), getSelectColor(), getViewObject(), getViewProvider(), Gui::ViewProvider::isRestoring(), TechDrawGui::PreferencesGui::normalQColor(), TechDraw::DrawView::setPosition(), and snapPosition().
Referenced by TechDrawGui::QGIProjGroup::itemChange(), TechDrawGui::QGIWeldSymbol::itemChange(), TechDrawGui::QGILeaderLine::itemChange(), TechDrawGui::QGIViewBalloon::itemChange(), and TechDrawGui::QGIViewDimension::itemChange().
makeMark() [1/3]
void QGIView::makeMark (Base::Vector3d pos, QColor color = Qt::red)
Definition at line 965 of file QGIView.cpp.
References makeMark(), and RobotExample::pos.
makeMark() [2/3]
void QGIView::makeMark (double xPos, double yPos, QColor color = Qt::red)
Definition at line 952 of file QGIView.cpp.
References TechDrawGui::QGIPrimPath::setFillColor(), TechDrawGui::QGIPrimPath::setNormalColor(), TechDrawGui::QGIPrimPath::setPrettyNormal(), TechDrawGui::QGIVertex::setRadius(), TechDrawGui::QGIPrimPath::setWidth(), and ZVALUE::VERTEX.
Referenced by makeMark().
makeMark() [3/3]
void QGIView::makeMark (QPointF pos, QColor color = Qt::red)
Definition at line 970 of file QGIView.cpp.
References makeMark(), and RobotExample::pos.
mouseMoveEvent()
void QGIView::mouseMoveEvent (QGraphicsSceneMouseEvent * event) override
Definition at line 426 of file QGIView.cpp.
Referenced by TechDrawGui::QGIProjGroup::mouseMoveEvent().
mousePressEvent()
void QGIView::mousePressEvent (QGraphicsSceneMouseEvent * event) override
Definition at line 402 of file QGIView.cpp.
References Gui::SelectionSingleton::getSelectionEx(), TechDrawGui::DrawGuiUtil::getSubsForSelectedObject(), getViewObject(), TechDrawGui::PreferencesGui::multiSelection(), Path.Dressup.Utils::selection(), and Gui::Selection().
mouseReleaseEvent()
void QGIView::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) override
Definition at line 431 of file QGIView.cpp.
References TechDrawGui::PreferencesGui::multiSelection().
Referenced by TechDrawGui::QGIProjGroup::mouseReleaseEvent().
paint()
void QGIView::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) override
Definition at line 706 of file QGIView.cpp.
Referenced by TechDrawGui::QGIRichAnno::paint(), TechDrawGui::QGIWeldSymbol::paint(), TechDrawGui::QGILeaderLine::paint(), and TechDrawGui::QGIViewBalloon::paint().
prefNormalColor()
QColor QGIView::prefNormalColor ()
Definition at line 892 of file QGIView.cpp.
References TechDrawGui::PreferencesGui::getAccessibleQColor(), and TechDrawGui::PreferencesGui::normalQColor().
Referenced by QGIView().
projItemPagePos()
Base::Vector3d QGIView::projItemPagePos (TechDraw::DrawViewPart * item)
Definition at line 384 of file QGIView.cpp.
References toolbit-attributes::group.
Referenced by snapPosition(), and snapSectionView().
removeChild()
void QGIView::removeChild (QGIView * child) virtual
Definition at line 815 of file QGIView.cpp.
Referenced by TechDrawGui::QGSPage::removeQViewFromScene().
rotateView()
void QGIView::rotateView () virtual
Reimplemented in TechDrawGui::QGIViewPart, TechDrawGui::QGIProjGroup, TechDrawGui::QGIViewSymbol, TechDrawGui::QGIViewAnnotation, and TechDrawGui::QGIViewImage.
Definition at line 528 of file QGIView.cpp.
References boundingRect(), App::PropertyQuantity::getValue(), getViewObject(), TechDraw::DrawView::Rotation, and src.Mod.AddonManager.Addon::translate.
Referenced by updateView().
setCurrentColor()
void TechDrawGui::QGIView::setCurrentColor (QColor color) inline
Definition at line 140 of file QGIView.h.
Referenced by TechDrawGui::QGIWeldSymbol::hoverEnterEvent(), TechDrawGui::QGIWeldSymbol::hoverLeaveEvent(), TechDrawGui::QGIWeldSymbol::QGIWeldSymbol(), TechDrawGui::QGIWeldSymbol::setPrettyNormal(), TechDrawGui::QGIWeldSymbol::setPrettyPre(), and TechDrawGui::QGIWeldSymbol::setPrettySel().
setFont()
void TechDrawGui::QGIView::setFont (QFont font) inline
Definition at line 158 of file QGIView.h.
setGroupSelection() [1/2]
void QGIView::setGroupSelection (bool isSelected) virtual
Reimplemented in TechDrawGui::QGIViewBalloon, TechDrawGui::QGIViewDimension, and TechDrawGui::QGIViewPart.
Definition at line 143 of file QGIView.cpp.
Referenced by TechDrawGui::MDIViewPage::clearSceneSelection(), TechDrawGui::MDIViewPage::selectQGIView(), and setGroupSelection().
setGroupSelection() [2/2]
void QGIView::setGroupSelection (bool isSelected, const std::vector< std::string > & subNames) virtual
Reimplemented in TechDrawGui::QGIViewPart.
Definition at line 149 of file QGIView.cpp.
References setGroupSelection().
setNormalColor()
void TechDrawGui::QGIView::setNormalColor (QColor color) inline
Definition at line 136 of file QGIView.h.
Referenced by TechDrawGui::QGIWeldSymbol::prefNormalColor(), TechDrawGui::QGILeaderLine::prefNormalColor(), TechDrawGui::QGIViewDimension::prefNormalColor(), TechDrawGui::QGIViewBalloon::prefNormalColor(), and TechDrawGui::QGIWeldSymbol::QGIWeldSymbol().
setPosition()
void QGIView::setPosition (qreal xPos, qreal yPos)
Methods to ensure that Y-Coordinates are orientated correctly.
Definition at line 473 of file QGIView.cpp.
References TechDraw::DrawUtil::fpCompare(), and RobotExample::pos.
Referenced by draw(), TechDrawGui::QGIViewClip::drawClip(), and updateView().
setSettingColor()
void TechDrawGui::QGIView::setSettingColor (QColor color) inline
Definition at line 142 of file QGIView.h.
Referenced by TechDrawGui::QGIWeldSymbol::QGIWeldSymbol().
setStack()
void QGIView::setStack (int z) virtual
Definition at line 876 of file QGIView.cpp.
References draw().
Referenced by TechDrawGui::ViewProviderDrawingView::onChanged(), setStackFromVP(), TechDrawGui::ViewProviderDrawingView::stackBottom(), and TechDrawGui::ViewProviderDrawingView::stackTop().
setStackFromVP()
void QGIView::setStackFromVP () virtual
Definition at line 883 of file QGIView.cpp.
References getViewObject(), getViewProvider(), TechDrawGui::ViewProviderDrawingView::getZ(), and setStack().
setViewFeature()
void QGIView::setViewFeature (TechDraw::DrawView * obj)
Definition at line 562 of file QGIView.cpp.
References App::DocumentObject::getNameInDocument().
Referenced by TechDrawGui::QGSPage::addAnnotation(), TechDrawGui::QGSPage::addDrawViewSymbol(), TechDrawGui::QGSPage::addRichAnno(), TechDrawGui::QGSPage::addViewLeader(), TechDrawGui::QGSPage::addWeldSymbol(), TechDrawGui::QGILeaderLine::setLeaderFeature(), TechDrawGui::QGIViewAnnotation::setViewAnnoFeature(), TechDrawGui::QGIViewSpreadsheet::setViewFeature(), TechDrawGui::QGIViewImage::setViewImageFeature(), TechDrawGui::QGIViewDimension::setViewPartFeature(), and TechDrawGui::QGIViewBalloon::setViewPartFeature().
snapPosition()
void QGIView::snapPosition (QPointF & newPosition)
align this view with others. newPosition is in this view's parent's coord system. if this view is not in a ProjectionGroup, then this is the scene position, otherwise it is the position within the ProjectionGroup.
Definition at line 215 of file QGIView.cpp.
References getViewObject(), getViewProviderPage(), TechDrawGui::QGSPage::getViews(), TechDrawGui::Rez::guiX(), TechDraw::DrawUtil::invertY(), projItemPagePos(), snapSectionView(), and TechDraw::DrawUtil::toQPointF().
Referenced by itemChange().
snapSectionView()
void QGIView::snapSectionView (const TechDraw::DrawViewSection * sectionView, QPointF & newPosition)
snap this section view to its base view. The section should be positioned on line from the base view along the section normal direction, ie the same direction as the arrows on the section line.
Definition at line 310 of file QGIView.cpp.
References dot(), TechDraw::DrawViewSection::getBaseDVP(), TechDraw::DrawViewSection::getCutCentroid(), getScale(), TechDraw::DrawView::getScale(), App::PropertyQuantity::getValue(), App::PropertyVector::getValue(), getViewProvider(), TechDrawGui::Rez::guiX(), TechDraw::DrawUtil::invertY(), Base::Vector3< float_type >::Normalize(), TechDraw::DrawViewPart::projectPoint(), projItemPagePos(), TechDraw::DrawView::Rotation, TechDraw::DrawViewSection::SectionNormal, TechDraw::DrawViewSection::SectionOrigin, TechDraw::DrawUtil::toQPointF(), Base::toRadians(), and TechDraw::DrawUtil::toVector3d().
Referenced by snapPosition().
switchParentItem()
void QGIView::switchParentItem (QGIView * targetParent) virtual
Definition at line 855 of file QGIView.cpp.
References updateView().
Referenced by TechDrawGui::ViewProviderDrawingView::updateData().
toggleCache()
void QGIView::toggleCache (bool state) virtual
Reimplemented in TechDrawGui::QGIViewPart.
Definition at line 575 of file QGIView.cpp.
type()
int TechDrawGui::QGIView::type () const inline override
Definition at line 84 of file QGIView.h.
Referenced by TechDrawGui::QGSPage::addItemToParent(), and TechDrawGui::QGSPage::removeQViewByName().
updateView()
void QGIView::updateView (bool update = false) virtual
Reimplemented in TechDrawGui::QGIViewBalloon, TechDrawGui::QGIViewDimension, TechDrawGui::QGIViewSection, TechDrawGui::QGIWeldSymbol, TechDrawGui::QGIViewPart, TechDrawGui::QGILeaderLine, TechDrawGui::QGIRichAnno, TechDrawGui::QGIViewClip, TechDrawGui::QGIViewSymbol, TechDrawGui::QGIViewAnnotation, and TechDrawGui::QGIViewImage.
Definition at line 502 of file QGIView.cpp.
References draw(), TechDraw::DrawUtil::fpCompare(), App::PropertyQuantity::getValue(), getViewObject(), TechDrawGui::Rez::guiX(), rotateView(), TechDraw::DrawView::Rotation, setPosition(), DrawingExample::X, and DrawingExample::Y.
Referenced by TechDrawGui::QGSPage::addQView(), TechDrawGui::MDIViewPage::clearSceneSelection(), TechDrawGui::ViewProviderDrawingView::onChanged(), TechDrawGui::ViewProviderImage::onChanged(), TechDrawGui::ViewProviderWeld::onChanged(), TechDrawGui::ViewProviderBalloon::onChanged(), TechDrawGui::ViewProviderViewPart::onChanged(), TechDrawGui::QGSPage::refreshViews(), TechDrawGui::MDIViewPage::selectQGIView(), switchParentItem(), TechDrawGui::ViewProviderDrawingView::updateData(), TechDrawGui::ViewProviderAnnotation::updateData(), TechDrawGui::ViewProviderBalloon::updateData(), TechDrawGui::ViewProviderDimension::updateData(), TechDrawGui::ViewProviderGeomHatch::updateGraphic(), TechDrawGui::ViewProviderViewSection::updateGraphic(), TechDrawGui::QGIViewImage::updateView(), TechDrawGui::QGIViewAnnotation::updateView(), TechDrawGui::QGIViewSymbol::updateView(), TechDrawGui::QGIViewClip::updateView(), and TechDrawGui::QGIViewSection::updateView().
Member Data Documentation
DefaultFontSizeInMM
const double QGIView::DefaultFontSizeInMM = 5.0 static
Definition at line 152 of file QGIView.h.
The documentation for this class was generated from the following files:
QGIView.h
QGIView.cpp