FreeCAD: CAMTests.TestPathGeom.TestPathGeom Class Reference
CAMTests.TestPathGeom.TestPathGeom Class Reference
Public Member Functions
def test00 (self)
def test01 (self)
def test02 (self)
def test03 (self)
def test04 (self)
def test07 (self)
def test08 (self)
def test10 (self)
def test20 (self)
def test30 (self)
def test40 (self)
def test41 (self)
def test42 (self)
def test50 (self)
def test60 (self)
def test62 (self)
def test65 (self)
def test66 (self)
def test70 (self)
def test71 (self)
def test72 (self)
def test73 (self)
def test74 (self)
def test75 (self)
def test76 (self)
Public Member Functions inherited from CAMTests.PathTestUtils.PathTestBase
def assertRoughly (self, f1, f2, error=0.00001)
def assertCoincide (self, pt1, pt2, error=0.0001)
def assertPlacement (self, p1, p2)
def assertLine (self, edge, pt1, pt2)
def assertLines (self, edgs, tail, points)
def assertArc (self, edge, pt1, pt2, direction="CW")
def assertCircle (self, edge, pt, r)
def assertCurve (self, edge, p1, p2, p3)
def assertCylinderAt (self, solid, pt, r, h)
def assertConeAt (self, solid, pt, r1, r2, h)
def assertCommandEqual (self, c1, c2)
def assertEqualLocale (self, s1, s2)
def assertEdgeShapesMatch (self, e1, e2)
def assertPointsMatch (self, pts0, pts1)
def assertSuccessfulRecompute (self, doc, *objs, msg=None)
Detailed Description
Test Path <-> Wire conversion.
Definition at line 31 of file TestPathGeom.py.
Member Function Documentation
test00()
def CAMTests.TestPathGeom.TestPathGeom.test00 (self)
Verify getAngle functionality.
Definition at line 34 of file TestPathGeom.py.
References CAMTests.PathTestUtils.PathTestBase.assertRoughly(), and Path.Geom.getAngle().
Referenced by CAMTests.TestPathToolController.TestPathToolController.test01().
test01()
def CAMTests.TestPathGeom.TestPathGeom.test01 (self)
Verify diffAngle functionality.
Definition at line 45 of file TestPathGeom.py.
References CAMTests.PathTestUtils.PathTestBase.assertRoughly(), and Path.Geom.diffAngle().
test02()
def CAMTests.TestPathGeom.TestPathGeom.test02 (self)
Verify isVertical/isHorizontal for Vector
Definition at line 100 of file TestPathGeom.py.
References Path.Geom.isHorizontal(), and Path.Geom.isVertical().
test03()
def CAMTests.TestPathGeom.TestPathGeom.test03 (self)
Verify isVertical/isHorizontal for Edges
Definition at line 121 of file TestPathGeom.py.
References Path.Geom.isHorizontal(), and Path.Geom.isVertical().
test04()
def CAMTests.TestPathGeom.TestPathGeom.test04 (self)
Verify isVertical/isHorizontal for faces
Definition at line 205 of file TestPathGeom.py.
References Path.Geom.isHorizontal(), Path.Geom.isVertical(), and Path.Post.scripts.grbl_post.type.
test07()
def CAMTests.TestPathGeom.TestPathGeom.test07 (self)
Verify speed interpolation works for different pitches
Definition at line 269 of file TestPathGeom.py.
References CAMTests.PathTestUtils.PathTestBase.assertRoughly(), and Path.Geom.speedBetweenPoints().
test08()
def CAMTests.TestPathGeom.TestPathGeom.test08 (self)
Verify speed interpolation works for different pitches if vSpeed > hSpeed
Definition at line 335 of file TestPathGeom.py.
References CAMTests.PathTestUtils.PathTestBase.assertRoughly(), and Path.Geom.speedBetweenPoints().
test10()
def CAMTests.TestPathGeom.TestPathGeom.test10 (self)
Verify proper geometry objects for G1 and G01 commands are created.
Definition at line 401 of file TestPathGeom.py.
References CAMTests.PathTestUtils.PathTestBase.assertLine(), and Path.Geom.edgeForCmd().
test20()
def CAMTests.TestPathGeom.TestPathGeom.test20 (self)
Verify proper geometry for arcs in the XY-plane are created.
Definition at line 415 of file TestPathGeom.py.
References CAMTests.PathTestUtils.PathTestBase.assertArc(), and Path.Geom.edgeForCmd().
test30()
def CAMTests.TestPathGeom.TestPathGeom.test30 (self)
Verify proper geometry for arcs with rising and fall ing Z-axis are created.
Definition at line 438 of file TestPathGeom.py.
References CAMTests.PathTestUtils.PathTestBase.assertCurve(), and Path.Geom.edgeForCmd().
test40()
def CAMTests.TestPathGeom.TestPathGeom.test40 (self)
Verify arc results in proper G2/3 command.
Definition at line 488 of file TestPathGeom.py.
References CAMTests.PathTestUtils.PathTestBase.assertCommandEqual(), and Path.Geom.cmdsForEdge().
test41()
def CAMTests.TestPathGeom.TestPathGeom.test41 (self)
Verify circle results in proper G2/G3 commands.
Definition at line 517 of file TestPathGeom.py.
References CAMTests.PathTestUtils.PathTestBase.assertCommandEqual(), and Path.Geom.cmdsForEdge().
test42()
def CAMTests.TestPathGeom.TestPathGeom.test42 (self)
Verify ellipsis results in a proper segmentation of G1 commands.
Definition at line 544 of file TestPathGeom.py.
References Path.Geom.cmdsForEdge().
test50()
def CAMTests.TestPathGeom.TestPathGeom.test50 (self)
Verify proper wire(s) aggregation from a Path.
Definition at line 552 of file TestPathGeom.py.
References CAMTests.PathTestUtils.PathTestBase.assertLine(), Path.Geom.edgesMatch(), Path.Geom.wireForPath(), and Path.Geom.wiresForPath().
test60()
def CAMTests.TestPathGeom.TestPathGeom.test60 (self)
Verify arcToHelix returns proper helix.
Definition at line 577 of file TestPathGeom.py.
References Path.Geom.arcToHelix(), and CAMTests.PathTestUtils.PathTestBase.assertCurve().
test62()
def CAMTests.TestPathGeom.TestPathGeom.test62 (self)
Verify splitArcAt returns proper subarcs.
Definition at line 609 of file TestPathGeom.py.
References CAMTests.PathTestUtils.PathTestBase.assertCurve(), and Path.Geom.splitArcAt().
test65()
def CAMTests.TestPathGeom.TestPathGeom.test65 (self)
Verify splitEdgeAt.
Definition at line 632 of file TestPathGeom.py.
References Path.Geom.arcToHelix(), CAMTests.PathTestUtils.PathTestBase.assertCurve(), CAMTests.PathTestUtils.PathTestBase.assertLine(), and Path.Geom.splitEdgeAt().
test66()
def CAMTests.TestPathGeom.TestPathGeom.test66 (self)
Split arc real world sample
Definition at line 668 of file TestPathGeom.py.
References CAMTests.PathTestUtils.PathTestBase.assertCoincide(), CAMTests.PathTestUtils.PathTestBase.assertRoughly(), and Path.Geom.splitEdgeAt().
test70()
def CAMTests.TestPathGeom.TestPathGeom.test70 (self)
Flip a line.
Definition at line 699 of file TestPathGeom.py.
References CAMTests.PathTestUtils.PathTestBase.assertEdgeShapesMatch(), and Path.Geom.flipEdge().
test71()
def CAMTests.TestPathGeom.TestPathGeom.test71 (self)
Flip a line segment.
Definition at line 706 of file TestPathGeom.py.
References CAMTests.PathTestUtils.PathTestBase.assertEdgeShapesMatch(), and Path.Geom.flipEdge().
test72()
def CAMTests.TestPathGeom.TestPathGeom.test72 (self)
Flip a circle
Definition at line 716 of file TestPathGeom.py.
References CAMTests.PathTestUtils.PathTestBase.assertEdgeShapesMatch(), and Path.Geom.flipEdge().
test73()
def CAMTests.TestPathGeom.TestPathGeom.test73 (self)
Flip an arc
Definition at line 724 of file TestPathGeom.py.
References CAMTests.PathTestUtils.PathTestBase.assertEdgeShapesMatch(), and Path.Geom.flipEdge().
test74()
def CAMTests.TestPathGeom.TestPathGeom.test74 (self)
Flip a rotated arc
Definition at line 749 of file TestPathGeom.py.
References CAMTests.PathTestUtils.PathTestBase.assertEdgeShapesMatch(), and Path.Geom.flipEdge().
test75()
def CAMTests.TestPathGeom.TestPathGeom.test75 (self)
Flip a B-spline
Definition at line 756 of file TestPathGeom.py.
References CAMTests.PathTestUtils.PathTestBase.assertEdgeShapesMatch(), and Path.Geom.flipEdge().
test76()
def CAMTests.TestPathGeom.TestPathGeom.test76 (self)
Flip an offset wire
Definition at line 779 of file TestPathGeom.py.
References Path.Geom.flipWire().
The documentation for this class was generated from the following file:
TestPathGeom.py