FreeCAD: ifc_objects.ifc_object Class Reference
ifc_objects.ifc_object Class Reference
Public Member Functions
def __init__ (self)
def onDocumentRestored (self, obj)
def dumps (self)
def loads (self, state)
Detailed Description
NativeIFC class placeholder
Definition at line 23 of file ifc_objects.py.
Constructor & Destructor Documentation
__init__()
def ifc_objects.ifc_object.__init__ (self)
Definition at line 25 of file ifc_objects.py.
Referenced by draftguitools.gui_subelements.SubelementHighlight.finish().
Member Function Documentation
dumps()
def ifc_objects.ifc_object.dumps (self)
Definition at line 30 of file ifc_objects.py.
loads()
def ifc_objects.ifc_object.loads (self, state)
Definition at line 32 of file ifc_objects.py.
Referenced by nativeifc.ifc_objects.ifc_object.__setstate__().
onDocumentRestored()
def ifc_objects.ifc_object.onDocumentRestored (self, obj)
Definition at line 27 of file ifc_objects.py.
Referenced by Path.Base.PropertyBag.PropertyBag.__init__(), and Path.Dressup.DogboneII.Proxy.__init__().
The documentation for this class was generated from the following file:
ifc_objects.py