FreeCAD: Gui::SoFCVectorizeU3DActionP Class Reference
Gui::SoFCVectorizeU3DActionP Class Reference
Public Member Functions
SoFCVectorizeU3DActionP (SoFCVectorizeU3DAction *p)
void printCircle (const SbVec3f &v, const SbColor &c, const float radius) const
void printSquare (const SbVec3f &v, const SbColor &c, const float size) const
void printTriangle (const SbVec3f *v, const SbColor *c) const
void printTriangle (const SoVectorizeTriangle *item) const
void printLine (const SoVectorizeLine *item) const
void printPoint (const SoVectorizePoint *item) const
void printText (const SoVectorizeText *item) const
void printImage (const SoVectorizeImage *item) const
Detailed Description
Definition at line 174 of file SoFCVectorizeU3DAction.cpp.
Constructor & Destructor Documentation
SoFCVectorizeU3DActionP()
Gui::SoFCVectorizeU3DActionP::SoFCVectorizeU3DActionP (SoFCVectorizeU3DAction * p) inline explicit
Definition at line 177 of file SoFCVectorizeU3DAction.cpp.
References buildPsets::p.
Member Function Documentation
printCircle()
void SoFCVectorizeU3DActionP::printCircle (const SbVec3f & v, const SbColor & c, const float radius) const
Definition at line 238 of file SoFCVectorizeU3DAction.cpp.
References SCL.SimpleDataTypes::c, and TestSpreadsheet::v.
printImage()
void SoFCVectorizeU3DActionP::printImage (const SoVectorizeImage * item) const
Definition at line 284 of file SoFCVectorizeU3DAction.cpp.
Referenced by Gui::SoFCVectorizeU3DAction::printItem().
printLine()
void SoFCVectorizeU3DActionP::printLine (const SoVectorizeLine * item) const
Definition at line 254 of file SoFCVectorizeU3DAction.cpp.
References SCL.SimpleDataTypes::c, SoVectorizeLine::col, SplineSurface::i, InitGui::t, TestSpreadsheet::v, and SoVectorizeLine::vidx.
Referenced by Gui::SoFCVectorizeU3DAction::printItem().
printPoint()
void SoFCVectorizeU3DActionP::printPoint (const SoVectorizePoint * item) const
Definition at line 278 of file SoFCVectorizeU3DAction.cpp.
Referenced by Gui::SoFCVectorizeU3DAction::printItem().
printSquare()
void SoFCVectorizeU3DActionP::printSquare (const SbVec3f & v, const SbColor & c, const float size) const
Definition at line 246 of file SoFCVectorizeU3DAction.cpp.
References SCL.SimpleDataTypes::c, and TestSpreadsheet::v.
printText()
void SoFCVectorizeU3DActionP::printText (const SoVectorizeText * item) const
Definition at line 195 of file SoFCVectorizeU3DAction.cpp.
Referenced by Gui::SoFCVectorizeU3DAction::printItem().
printTriangle() [1/2]
void SoFCVectorizeU3DActionP::printTriangle (const SbVec3f * v, const SbColor * c) const
Definition at line 227 of file SoFCVectorizeU3DAction.cpp.
References SCL.SimpleDataTypes::c, and TestSpreadsheet::v.
Referenced by Gui::SoFCVectorizeU3DAction::printItem(), and printTriangle().
printTriangle() [2/2]
void SoFCVectorizeU3DActionP::printTriangle (const SoVectorizeTriangle * item) const
Definition at line 207 of file SoFCVectorizeU3DAction.cpp.
References SCL.SimpleDataTypes::c, SoVectorizeTriangle::col, SplineSurface::i, printTriangle(), InitGui::t, TestSpreadsheet::v, and SoVectorizeTriangle::vidx.
The documentation for this class was generated from the following file:
SoFCVectorizeU3DAction.cpp