FreeCAD: PartDesign Namespace Reference
PartDesign Namespace Reference
Base class of all additive features in PartDesign.
Classes
class AdditiveBox
class AdditiveCone
class AdditiveCylinder
class AdditiveEllipsoid
class AdditiveHelix
class AdditiveLoft
class AdditivePipe
class AdditivePrism
class AdditiveSphere
class AdditiveTorus
class AdditiveWedge
class Body
class Boolean
class Box
class Chamfer
class Cone
class CoordinateSystem
class Cylinder
class Draft
class DressUp
class Ellipsoid
class Feature
class FeatureAdditivePython
class FeatureAddSub
class FeatureBase
class FeatureExtrude
class FeaturePrimitive
class FeatureSubtractivePython
class Fillet
struct gp_Pnt_Less
class Groove
class Helix
class Hole
class Line
class LinearPattern
class Loft
class Measure
class Mirrored
class Module
class MultiTransform
class Pad
class Pipe
class Plane
class Pocket
class Point
class PolarPattern
class Prism
class ProfileBased
class Revolution
class Scaled
class ShapeBinder
class Solid
class Sphere
class SubShapeBinder
class SubtractiveBox
class SubtractiveCone
class SubtractiveCylinder
class SubtractiveEllipsoid
class SubtractiveHelix
class SubtractiveLoft
class SubtractivePipe
class SubtractivePrism
class SubtractiveSphere
class SubtractiveTorus
class SubtractiveWedge
class Thickness
class Torus
class Transformed
class Wedge
Typedefs
using TopoShape = Part::TopoShape
using FeaturePython = App::FeaturePythonT< Feature >
using FeatureAddSubPython = App::FeaturePythonT< FeatureAddSub >
using SubShapeBinderPython = App::FeaturePythonT< SubShapeBinder >
Enumerations
enum HelixMode { HelixMode::pitch_height_angle, HelixMode::pitch_turns_angle, HelixMode::height_turns_angle, HelixMode::height_turns_growth }
enum LinearPatternMode { LinearPatternMode::length, LinearPatternMode::offset }
enum PolarPatternMode { PolarPatternMode::angle, PolarPatternMode::offset }
Functions
PyObject * initModule ()
bool getPDRefineModelParameter ()
static void computeIntersection (gp_Pnt pa1, gp_Pnt pa2, gp_Pnt pb1, gp_Pnt pb2, double &x, double &y)
static gp_Pnt toPnt (gp_Vec dir)
void from_json (const nlohmann::json &j, Hole::CounterBoreDimension &t)
void from_json (const nlohmann::json &j, Hole::CounterSinkDimension &t)
void from_json (const nlohmann::json &j, Hole::CutDimensionSet &t)
PYTHON_TYPE_DEF (PrimitivePy, PartDesign::FeaturePy) PyObject *FeaturePrimitive
Variables
const App::PropertyQuantityConstraint::Constraints diameterRange = { 10 * Precision::Confusion(), FLT_MAX, 1.0 }
static constexpr size_t ThreadClass_ISOmetric_data_size = 25
static constexpr size_t ThreadRunout_size = 24
const App::PropertyQuantityConstraint::Constraints torusRangeV = { -180.0, 180.0, 1.0 }
const App::PropertyQuantityConstraint::Constraints angleRangeU = { 0.0, 360.0, 1.0 }
const App::PropertyQuantityConstraint::Constraints angleRangeV = { -90.0, 90.0, 1.0 }
const App::PropertyQuantityConstraint::Constraints quantityRange = { 2 * Precision::Confusion(), FLT_MAX, 0.1 }
const App::PropertyQuantityConstraint::Constraints quantityRangeZero = { 0.0, FLT_MAX, 0.1 }
std::array< char const *, 3 > transformModeEnums
Detailed Description
Base class of all additive features in PartDesign.
Typedef Documentation
FeatureAddSubPython
using PartDesign::FeatureAddSubPython = typedef App::FeaturePythonT<FeatureAddSub>
Definition at line 90 of file FeatureAddSub.h.
FeaturePython
using PartDesign::FeaturePython = typedef App::FeaturePythonT<Feature>
Definition at line 127 of file Feature.h.
SubShapeBinderPython
using PartDesign::SubShapeBinderPython = typedef App::FeaturePythonT<SubShapeBinder>
Definition at line 176 of file ShapeBinder.h.
TopoShape
using PartDesign::TopoShape = typedef Part::TopoShape
Definition at line 40 of file Feature.h.
Enumeration Type Documentation
HelixMode
enum PartDesign::HelixMode strong
Enumerator
pitch_height_angle
pitch_turns_angle
height_turns_angle
height_turns_growth
Definition at line 54 of file FeatureHelix.h.
LinearPatternMode
enum PartDesign::LinearPatternMode strong
Enumerator
length
offset
Definition at line 52 of file FeatureLinearPattern.h.
PolarPatternMode
enum PartDesign::PolarPatternMode strong
Enumerator
angle
offset
Definition at line 54 of file FeaturePolarPattern.h.
Function Documentation
computeIntersection()
static void PartDesign::computeIntersection (gp_Pnt pa1, gp_Pnt pa2, gp_Pnt pb1, gp_Pnt pb2, double & x, double & y) static
Computes 2D intersection between the lines (pa1, pa2) and (pb1, pb2). The lines are assumed to be crossing, and it is an error to specify parallel lines. Only the x and y coordinates of the points are used to compute the 2D intersection.
The result are the x and y coordinate of the intersection point.
Definition at line 1808 of file FeatureHole.cpp.
References SCL.SimpleDataTypes::e, SCL.SimpleDataTypes::f, src.Mod.PartDesign.Scripts.Gear::t1, src.Mod.PartDesign.Scripts.Gear::t2, MovieTool::x, and MovieTool::y.
Referenced by PartDesign::Hole::execute().
from_json() [1/3]
void PartDesign::from_json (const nlohmann::json & j, Hole::CounterBoreDimension & t)
Definition at line 2630 of file FeatureHole.cpp.
References InitGui::t.
from_json() [2/3]
void PartDesign::from_json (const nlohmann::json & j, Hole::CounterSinkDimension & t)
Definition at line 2637 of file FeatureHole.cpp.
References InitGui::t.
from_json() [3/3]
void PartDesign::from_json (const nlohmann::json & j, Hole::CutDimensionSet & t)
Definition at line 2643 of file FeatureHole.cpp.
References InitGui::t.
getPDRefineModelParameter()
bool PartDesign::getPDRefineModelParameter ()
Definition at line 72 of file Feature.cpp.
Referenced by PartDesign::Boolean::Boolean(), PartDesign::FeatureAddSub::FeatureAddSub(), PartDesign::SubShapeBinder::setupObject(), and PartDesign::Transformed::Transformed().
initModule()
PyObject * PartDesign::initModule ()
Definition at line 129 of file AppPartDesignPy.cpp.
Referenced by PyMOD_INIT_FUNC().
PYTHON_TYPE_DEF()
PartDesign::PYTHON_TYPE_DEF (PrimitivePy , PartDesign::FeaturePy)
Definition at line 169 of file FeaturePrimitive.cpp.
References Py::SmartPtr::is(), Py::new_reference_to(), and App::DocumentObject::PythonObject.
toPnt()
static gp_Pnt PartDesign::toPnt (gp_Vec dir) static
Definition at line 1913 of file FeatureHole.cpp.
Referenced by PartDesign::Hole::execute().
Variable Documentation
angleRangeU
const App::PropertyQuantityConstraint::Constraints PartDesign::angleRangeU = { 0.0, 360.0, 1.0 }
Definition at line 55 of file FeaturePrimitive.cpp.
Referenced by PartDesign::Cone::Cone(), PartDesign::Cylinder::Cylinder(), PartDesign::Ellipsoid::Ellipsoid(), PartDesign::Sphere::Sphere(), and PartDesign::Torus::Torus().
angleRangeV
const App::PropertyQuantityConstraint::Constraints PartDesign::angleRangeV = { -90.0, 90.0, 1.0 }
Definition at line 56 of file FeaturePrimitive.cpp.
Referenced by PartDesign::Ellipsoid::Ellipsoid(), and PartDesign::Sphere::Sphere().
diameterRange
const App::PropertyQuantityConstraint::Constraints PartDesign::diameterRange = { 10 * Precision::Confusion(), FLT_MAX, 1.0 }
Definition at line 819 of file FeatureHole.cpp.
Referenced by PartDesign::Hole::Hole().
quantityRange
const App::PropertyQuantityConstraint::Constraints PartDesign::quantityRange = { 2 * Precision::Confusion(), FLT_MAX, 0.1 }
Definition at line 59 of file FeaturePrimitive.cpp.
Referenced by PartDesign::Box::Box(), PartDesign::Cone::Cone(), PartDesign::Cylinder::Cylinder(), PartDesign::Ellipsoid::Ellipsoid(), PartDesign::Sphere::Sphere(), and PartDesign::Torus::Torus().
quantityRangeZero
const App::PropertyQuantityConstraint::Constraints PartDesign::quantityRangeZero = { 0.0, FLT_MAX, 0.1 }
Definition at line 60 of file FeaturePrimitive.cpp.
Referenced by PartDesign::Cone::Cone(), and PartDesign::Ellipsoid::Ellipsoid().
ThreadClass_ISOmetric_data_size
constexpr size_t PartDesign::ThreadClass_ISOmetric_data_size = 25 static constexpr
Definition at line 41 of file FeatureHole.h.
ThreadRunout_size
constexpr size_t PartDesign::ThreadRunout_size = 24 static constexpr
Definition at line 42 of file FeatureHole.h.
torusRangeV
const App::PropertyQuantityConstraint::Constraints PartDesign::torusRangeV = { -180.0, 180.0, 1.0 }
Definition at line 54 of file FeaturePrimitive.cpp.
Referenced by PartDesign::Torus::Torus().
transformModeEnums
std::array<char const*, 3> PartDesign::transformModeEnums
Initial value:
= {"Transform tool shapes",
                                                 "Transform body",
                                                 nullptr}
Definition at line 62 of file FeatureTransformed.cpp.
Referenced by PartDesign::Transformed::Transformed().