FreeCAD: MainWindow.cpp File Reference
MainWindow.cpp File Reference
#include "PreCompiled.h"
#include <QActionGroup>
#include <QApplication>
#include <QByteArray>
#include <QCheckBox>
#include <QClipboard>
#include <QCloseEvent>
#include <QContextMenuEvent>
#include <QDesktopServices>
#include <QDockWidget>
#include <QFontMetrics>
#include <QKeySequence>
#include <QLabel>
#include <QMdiSubWindow>
#include <QMenu>
#include <QMenuBar>
#include <QMessageBox>
#include <QMimeData>
#include <QPainter>
#include <QRegularExpression>
#include <QRegularExpressionMatch>
#include <QScreen>
#include <QSettings>
#include <QSignalMapper>
#include <QStatusBar>
#include <QThread>
#include <QTimer>
#include <QToolBar>
#include <QUrlQuery>
#include <QWhatsThis>
#include <QWindow>
#include <QPushButton>
#include <boost/algorithm/string/predicate.hpp>
#include <App/Application.h>
#include <App/Document.h>
#include <App/DocumentObject.h>
#include <App/DocumentObjectGroup.h>
#include <App/SafeMode.h>
#include <Base/ConsoleObserver.h>
#include <Base/Parameter.h>
#include <Base/Exception.h>
#include <Base/FileInfo.h>
#include <Base/Interpreter.h>
#include <Base/Stream.h>
#include <Base/Tools.h>
#include <Base/UnitsApi.h>
#include <DAGView/DAGView.h>
#include <TaskView/TaskView.h>
#include "MainWindow.h"
#include "Action.h"
#include "Assistant.h"
#include "BitmapFactory.h"
#include "ComboView.h"
#include "Command.h"
#include "DockWindowManager.h"
#include "DownloadManager.h"
#include "FileDialog.h"
#include "MenuManager.h"
#include "ModuleIO.h"
#include "NotificationArea.h"
#include "OverlayManager.h"
#include "ProgressBar.h"
#include "PropertyView.h"
#include "PythonConsole.h"
#include "ReportView.h"
#include "SelectionView.h"
#include "SplashScreen.h"
#include "ToolBarManager.h"
#include "ToolBoxManager.h"
#include "Tree.h"
#include "WaitCursor.h"
#include "WorkbenchManager.h"
#include "Workbench.h"
#include "MergeDocuments.h"
#include "ViewProviderExtern.h"
#include "SpaceballEvent.h"
#include "View3DInventor.h"
#include "View3DInventorViewer.h"
#include "DlgObjectSelection.h"
#include <App/Color.h>
#include "moc_MainWindow.cpp"
#include "MainWindow.moc"
Classes
class Gui::CustomMessageEvent
class Gui::DimensionWidget
struct Gui::MainWindowP
Namespaces
Gui
Functions
template<class T >
static void _updateDockWidget (const char *name, bool enabled, bool show, Qt::DockWidgetArea pos, T callback)
static QLatin1String _MimeDocObj ("application/x-documentobject")
static QLatin1String _MimeDocObjX ("application/x-documentobject-x")
static QLatin1String _MimeDocObjFile ("application/x-documentobject-file")
static QLatin1String _MimeDocObjXFile ("application/x-documentobject-x-file")
Function Documentation
_MimeDocObj()
static QLatin1String _MimeDocObj ("application/x-documentobject") static
Referenced by Gui::MainWindow::canInsertFromMimeData(), Gui::MainWindow::createMimeDataFromSelection(), and Gui::MainWindow::insertFromMimeData().
_MimeDocObjFile()
static QLatin1String _MimeDocObjFile ("application/x-documentobject-file") static
Referenced by Gui::MainWindow::canInsertFromMimeData(), Gui::MainWindow::createMimeDataFromSelection(), and Gui::MainWindow::insertFromMimeData().
_MimeDocObjX()
static QLatin1String _MimeDocObjX ("application/x-documentobject-x") static
Referenced by Gui::MainWindow::canInsertFromMimeData(), Gui::MainWindow::createMimeDataFromSelection(), and Gui::MainWindow::insertFromMimeData().
_MimeDocObjXFile()
static QLatin1String _MimeDocObjXFile ("application/x-documentobject-x-file") static
Referenced by Gui::MainWindow::canInsertFromMimeData(), Gui::MainWindow::createMimeDataFromSelection(), and Gui::MainWindow::insertFromMimeData().
_updateDockWidget()
template<class T > static void _updateDockWidget (const char * name, bool enabled, bool show, Qt::DockWidgetArea pos, T callback) inline static
Definition at line 472 of file MainWindow.cpp.
References Gui::DockWindowManager::instance(), Gui::OverlayManager::instance(), RobotExample::pos, Gui::OverlayManager::refresh(), Gui::DockWindowManager::registerDockWindow(), and bimcommands.BimViews::show().