FreeCAD: App::ExtensionContainer Class Reference
App::ExtensionContainer Class Reference
Container which can hold extensions.
#include <ExtensionContainer.h>
Public Types
using ExtensionIterator = std::map< Base::Type, App::Extension * >::iterator
Public Member Functions
ExtensionContainer ()
~ExtensionContainer () override
void registerExtension (Base::Type extension, App::Extension *ext)
bool hasExtension (Base::Type, bool derived=true) const
bool hasExtension (const std::string &name) const
bool hasExtensions () const
App::Extension * getExtension (Base::Type, bool derived=true, bool no_except=false) const
App::Extension * getExtension (const std::string &name) const
template<typename ExtensionT >
ExtensionT * getExtension () const
template<typename ExtensionT >
ExtensionT * getExtensionByType (bool no_except=false, bool derived=true) const
std::vector< Extension * > getExtensionsDerivedFrom (Base::Type type) const
template<typename ExtensionT >
std::vector< ExtensionT * > getExtensionsDerivedFromType () const
ExtensionIterator extensionBegin ()
ExtensionIterator extensionEnd ()
Public Member Functions inherited from App::PropertyContainer
PropertyContainer ()
~PropertyContainer () override
unsigned int getMemSize () const override
virtual std::string getFullName () const
virtual void getPropertyNamedList (std::vector< std::pair< const char *, Property * > > &List) const
get all properties with their names, may contain duplicates and aliases
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
bool isReadOnly (const Property *prop) const
check if the property is read-only
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isHidden (const Property *prop) const
check if the property is hidden
bool isHidden (const char *name) const
check if the named property is hidden
virtual App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false)
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
bool changeDynamicProperty (const Property *prop, const char *group, const char *doc)
virtual bool removeDynamicProperty (const char *name)
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual App::Property * getDynamicPropertyByName (const char *name) const
virtual void onPropertyStatusChanged (const Property &prop, unsigned long oldStatus)
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
virtual void beforeSave () const
virtual void editProperty (const char *)
const char * getPropertyPrefix () const
void setPropertyPrefix (const char *prefix)
PropertyContainer (const PropertyContainer &)=delete
PropertyContainer & operator= (const PropertyContainer &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Access properties
Property * getPropertyByName (const char *name) const override
find a property by its name
template<typename T >
T * getPropertyByName (const char *name) const
find a property by its name, dynamic cased to specified type
const char * getPropertyName (const Property *prop) const override
get the name of a property
void getPropertyMap (std::map< std::string, Property * > &Map) const override
get all properties of the class (including properties of the parent)
void getPropertyList (std::vector< Property * > &List) const override
get all properties of the class (including properties of the parent)
short getPropertyType (const Property *prop) const override
get the Type of a Property
short getPropertyType (const char *name) const override
get the Type of a named Property
const char * getPropertyGroup (const Property *prop) const override
get the Group of a Property
const char * getPropertyGroup (const char *name) const override
get the Group of a named Property
const char * getPropertyDocumentation (const Property *prop) const override
get the Group of a Property
const char * getPropertyDocumentation (const char *name) const override
get the Group of a named Property
void onChanged (const Property *) override
get called by the container when a property has changed
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
void saveExtensions (Base::Writer &writer) const
void restoreExtensions (Base::XMLReader &reader)
void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName) override
void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop) override
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Protected Member Functions inherited from App::PropertyContainer
virtual void onEarlyChange (const Property *)
virtual void onBeforeChange (const Property *)
get called before the value is changed
virtual const PropertyData & getPropertyData () const
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Detailed Description
Container which can hold extensions.
In FreeCAD normally inheritance is a chain, it is not possible to use multiple inheritance. The reason for this is that all objects need to be exposed to python, and it is basically impossible to handle multiple inheritance in the C-API for python extensions. Also using multiple parent classes in python is currently not possible with the default object approach.
The concept of extensions allows one to circumvent those problems. Extensions are FreeCAD objects which work like normal objects in the sense that they use properties and class methods to define their functionality. However, they are not exposed as individual usable entities but are used to extend other objects. A extended object gets all the properties and methods of the extension. Therefore it is like c++ multiple inheritance, which is indeed used to achieve this on c++ side, but provides a few important additional functionalities:
Property persistence is handled, save and restore work out of the box
The objects python API gets extended too with the extension python API
Extensions can be added from c++ and python, even from both together
The interoperability with python is highly important, as in FreeCAD all functionality should be as easily accessible from python as from c++. To ensure this, and as already noted, extensions can be added to a object from python. However, this means that it is not clear from the c++ object type if an extension was added or not. If added from c++ it becomes clear in the type due to the use of multiple inheritance. If added from python it is a runtime extension and not visible from type. Hence querying existing extensions of an object and accessing its methods works not by type casting but by the interface provided in ExtensionContainer. The default workflow is to query if an extension exists and then get the extension object. No matter if added from python or c++ this interface works always the same.
if (object->hasExtension(GroupExtension::getClassTypeId())) {
    App::GroupExtension* group = object->getExtensionByType<GroupExtension>();
    group->hasObject(...);
}
To add a extension to an object, it must comply to a single restriction: it must be derived from ExtensionContainer. This is important to allow adding extensions from python and also to access the universal extension API. As DocumentObject itself derives from ExtensionContainer this should be the case automatically in most circumstances.
Note that two small boilerplate changes are needed next to the multiple inheritance when adding extensions from c++.
It must be ensured that the property and type registration is aware of the extensions by using special macros.
The extensions need to be initialised in the constructor
Here is a working example:
class AppExport Part : public App::DocumentObject, public App::FirstExtension, public
App::SecondExtension { PROPERTY_HEADER_WITH_EXTENSIONS(App::Part);
};
PROPERTY_SOURCE_WITH_EXTENSIONS(App::Part, App::DocumentObject)
Part::Part(void) {
  FirstExtension::initExtension(this);
  SecondExtension::initExtension(this);
}
From python adding an extension is easier, it must be simply registered to a document object at object initialisation like done with properties. Note that the special python extension objects need to be added, not the c++ objects. Normally the only difference in name is the additional "Python" at the end of the extension name.
class Test():
  __init(self)__:
    registerExtension("App::FirstExtensionPython", self)
    registerExtension("App::SecondExtensionPython", self)
Extensions can provide methods that should be overridden by the extended object for customisation of the extension behaviour. In c++ this is as simple as overriding the provided virtual functions. In python a class method must be provided which has the same name as the method to override. This method must not necessarily be in the object that is extended, it must be in the object which is provided to the "registerExtension" call as second argument. This second argument is used as a proxy and enqueired if the method to override exists in this proxy before calling it.
For information on howto create extension see the documentation of Extension
Definition at line 132 of file ExtensionContainer.h.
Member Typedef Documentation
ExtensionIterator
using App::ExtensionContainer::ExtensionIterator = std::map<Base::Type, App::Extension*>::iterator
Definition at line 138 of file ExtensionContainer.h.
Constructor & Destructor Documentation
ExtensionContainer()
ExtensionContainer::ExtensionContainer () default
~ExtensionContainer()
ExtensionContainer::~ExtensionContainer () override
Definition at line 41 of file ExtensionContainer.cpp.
Member Function Documentation
extensionBegin()
ExtensionIterator App::ExtensionContainer::extensionBegin () inline
Definition at line 182 of file ExtensionContainer.h.
extensionEnd()
ExtensionIterator App::ExtensionContainer::extensionEnd () inline
Definition at line 186 of file ExtensionContainer.h.
getExtension() [1/3]
template<typename ExtensionT > ExtensionT* App::ExtensionContainer::getExtension () const inline
Definition at line 154 of file ExtensionContainer.h.
Referenced by restoreExtensions().
getExtension() [2/3]
Extension * ExtensionContainer::getExtension (Base::Type t, bool derived = true, bool no_except = false) const
Definition at line 102 of file ExtensionContainer.cpp.
References result, and InitGui::t.
Referenced by StdCmdVarSet::activated().
getExtension() [3/3]
Extension * ExtensionContainer::getExtension (const std::string & name) const
Definition at line 139 of file ExtensionContainer.cpp.
getExtensionByType()
template<typename ExtensionT > ExtensionT* App::ExtensionContainer::getExtensionByType (bool no_except = false, bool derived = true) const inline
Definition at line 162 of file ExtensionContainer.h.
Referenced by _getTopoShape(), PartGui::TaskDlgAttacher::accept(), Import::ExportOCAF2::canFallback(), App::LinkBaseExtension::detachElement(), App::Document::exportGraphviz(), Gui::ViewProviderGroupExtension::extensionHide(), PartGui::ViewProviderAttachExtension::extensionMergeColorfullOverlayIcons(), Gui::ViewProviderGroupExtension::extensionOnDelete(), Gui::ViewProviderGroupExtension::extensionShow(), PartGui::ViewProviderAttachExtension::extensionUpdateData(), Gui::LinkInfo::get(), Gui::ViewProviderLink::getLinkExtension(), PartDesignGui::isFeatureMovable(), App::GeoFeatureGroupExtension::isLinkValid(), Gui::LinkInfo::release(), PartDesignGui::relinkToOrigin(), App::LinkBaseExtension::slotChangedPlainGroup(), PartGui::TaskAttacher::TaskAttacher(), and Gui::ViewProviderLink::updateLinks().
getExtensionsDerivedFrom()
std::vector< Extension * > ExtensionContainer::getExtensionsDerivedFrom (Base::Type type) const
Definition at line 151 of file ExtensionContainer.cpp.
References Path.Post.scripts.grbl_post::type, and SurfaceTests.TestBlendCurve::vec.
getExtensionsDerivedFromType()
template<typename ExtensionT > std::vector<ExtensionT*> App::ExtensionContainer::getExtensionsDerivedFromType () const inline
Definition at line 171 of file ExtensionContainer.h.
getPropertyByName() [1/2]
template<typename T > T* App::ExtensionContainer::getPropertyByName (const char * name) const inline virtual
find a property by its name, dynamic cased to specified type
Reimplemented from App::PropertyContainer.
Reimplemented in Spreadsheet::Sheet.
Definition at line 198 of file ExtensionContainer.h.
getPropertyByName() [2/2]
Property * ExtensionContainer::getPropertyByName (const char * name) const override virtual
find a property by its name
Reimplemented from App::PropertyContainer.
Reimplemented in Spreadsheet::Sheet.
Definition at line 180 of file ExtensionContainer.cpp.
References App::PropertyContainer::getPropertyByName().
Referenced by App::RangeExpression::_getPyValue(), FemGui::TaskDlgFemConstraintFluidBoundary::accept(), App::ObjectIdentifier::access(), StdCmdToggleTransparency::activated(), AssemblyGui::ViewProviderAssembly::canDragObjectIn3d(), MeshGui::ViewProviderMesh::canHighlightColors(), AssemblyGui::ViewProviderAssembly::draggerMotionCallback(), App::FunctionExpression::evalAggregate(), Mesh::SegmentByMesh::execute(), Mesh::HarmonizeNormals::execute(), TechDraw::DrawViewArch::execute(), Mesh::FlipNormals::execute(), Mesh::FixNonManifolds::execute(), Mesh::FixDuplicatedFaces::execute(), Mesh::FixDuplicatedPoints::execute(), Mesh::FixDegenerations::execute(), Mesh::FixDeformations::execute(), Mesh::FixIndices::execute(), Mesh::FillHoles::execute(), Mesh::RemoveComponents::execute(), Fem::FemVTKTools::exportFreeCADResult(), App::LinkBaseExtension::extensionExecute(), PartGui::ViewProviderSplineExtension::extensionOnChanged(), Sandbox::DocumentObjectProtectorPy::getattr(), App::GeoFeature::getGlobalPlacement(), InspectionGui::ViewProviderInspection::getIcon(), Assembly::getJointGroup(), TechDraw::DrawProjGroupItem::getLegacyX(), Measure::ShapeFinder::getLinkAttachParent(), Assembly::AssemblyObject::getMotionsFromSimulation(), Assembly::getMovingPartFromRef(), Assembly::getObjFromRef(), Measure::ShapeFinder::getPlacement(), App::GeoFeature::getPlacementFromProp(), Gui::ViewProviderLink::getPropertyByName(), Spreadsheet::PropertySheet::getPyValue(), App::ObjectIdentifier::getPyValue(), Assembly::AssemblyObject::getRackPinionMarkers(), Measure::ShapeFinder::getScale(), AssemblyGui::ViewProviderAssembly::getSelectedJoint(), AssemblyGui::ViewProviderAssembly::getSelectedObjectsWithinAssembly(), TechDraw::ShapeExtractor::getShapesFromObject(), App::ObjectIdentifier::getValue(), TechDraw::DrawProjGroupItem::getXDirection(), TechDraw::DrawViewSection::getXDirection(), TechDraw::DrawViewPart::getXDirection(), Assembly::AssemblyLink::handleJointReference(), Assembly::AssemblyObject::handleOneSideOfJoint(), MeshGui::ViewProviderMesh::highlightColors(), InspectionGui::ViewProviderInspection::inspectDistance(), TechDrawGui::DrawGuiUtil::isArchObject(), TechDrawGui::DrawGuiUtil::isArchSection(), TechDrawGui::DrawGuiUtil::isDraftObject(), TechDraw::ShapeExtractor::isDraftPoint(), Measure::ShapeFinder::isLinkLike(), isNamePropOk(), Assembly::AssemblyLink::isRigid(), App::RangeExpression::isTouched(), Assembly::AssemblyObject::makeMbdJoint(), Assembly::AssemblyLink::onChanged(), Gui::ViewProviderAnnotationLabel::onChanged(), Assembly::AssemblyObject::redrawJointPlacement(), App::ObjectIdentifier::resolveProperty(), Part::Box::Restore(), Assembly::AssemblyObject::savePlacementsForUndo(), Sandbox::DocumentObjectProtectorPy::setattr(), InspectionGui::ViewProviderInspection::setDistances(), App::LinkBaseExtension::setLink(), Assembly::AssemblyObject::setNewPlacements(), App::LinkBaseExtension::setOnChangeCopyObject(), Sandbox::DocumentObjectProtector::setProperty(), Assembly::AssemblyLink::synchronizeComponents(), FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary(), Assembly::AssemblyObject::undoSolve(), PartDesign::SubShapeBinder::update(), InspectionGui::ViewProviderInspection::updateData(), and Gui::ViewProviderDragger::updatePlacementFromDragger().
getPropertyDocumentation() [1/2]
const char * ExtensionContainer::getPropertyDocumentation (const char * name) const override virtual
get the Group of a named Property
Reimplemented from App::PropertyContainer.
Definition at line 307 of file ExtensionContainer.cpp.
References App::PropertyContainer::getPropertyDocumentation().
getPropertyDocumentation() [2/2]
const char * ExtensionContainer::getPropertyDocumentation (const Property * prop) const override virtual
get the Group of a Property
Reimplemented from App::PropertyContainer.
Definition at line 289 of file ExtensionContainer.cpp.
References App::PropertyContainer::getPropertyDocumentation().
getPropertyGroup() [1/2]
const char * ExtensionContainer::getPropertyGroup (const char * name) const override virtual
get the Group of a named Property
Reimplemented from App::PropertyContainer.
Definition at line 270 of file ExtensionContainer.cpp.
References App::PropertyContainer::getPropertyGroup().
getPropertyGroup() [2/2]
const char * ExtensionContainer::getPropertyGroup (const Property * prop) const override virtual
get the Group of a Property
Reimplemented from App::PropertyContainer.
Definition at line 252 of file ExtensionContainer.cpp.
References App::PropertyContainer::getPropertyGroup().
getPropertyList()
void ExtensionContainer::getPropertyList (std::vector< Property * > & List) const override virtual
get all properties of the class (including properties of the parent)
Reimplemented from App::PropertyContainer.
Definition at line 164 of file ExtensionContainer.cpp.
References App::PropertyContainer::getPropertyList().
Referenced by addGroupsVarSetComboBox(), App::GeoFeatureGroupExtension::areLinksValid(), App::PropertyLinkBase::breakLinks(), PartDesignGui::TaskFeaturePick::makeCopy(), PartDesign::FeatureAddSub::onlyHasToRefine(), Gui::PropertyView::onTimer(), App::OriginGroupExtension::relinkToOrigin(), PartDesignGui::ViewProvider::setBodyMode(), PartDesign::SubShapeBinder::setupCopyOnChange(), App::LinkBaseExtension::setupCopyOnChange(), and PartDesign::SubShapeBinder::update().
getPropertyMap()
void ExtensionContainer::getPropertyMap (std::map< std::string, Property * > & Map) const override virtual
get all properties of the class (including properties of the parent)
Reimplemented from App::PropertyContainer.
Definition at line 172 of file ExtensionContainer.cpp.
References App::PropertyContainer::getPropertyMap().
Referenced by Gui::Dialog::TransformStrategy::acceptDataTransform(), Gui::Dialog::TransformStrategy::applyViewTransform(), Gui::FreeCADGui_subgraphFromObject(), MeshGui::ViewProviderMesh::getColorProperty(), MeshGui::ViewProviderMesh::getMaterialProperty(), Gui::Dialog::find_placement::getProperty(), Gui::ViewProviderLink::getPropertyMap(), Gui::PropertyView::onTimer(), Gui::Dialog::TransformStrategy::resetViewTransform(), and Gui::ViewProviderDocumentObject::updateView().
getPropertyName()
const char * ExtensionContainer::getPropertyName (const Property * prop) const override virtual
get the name of a property
Reimplemented from App::PropertyContainer.
Definition at line 234 of file ExtensionContainer.cpp.
References App::PropertyContainer::getPropertyName().
Referenced by App::TransactionObject::applyChn(), and Spreadsheet::SheetObserver::slotChangedObject().
getPropertyType() [1/2]
short int ExtensionContainer::getPropertyType (const char * name) const override virtual
get the Type of a named Property
Reimplemented from App::PropertyContainer.
Definition at line 215 of file ExtensionContainer.cpp.
References App::PropertyContainer::getPropertyType().
getPropertyType() [2/2]
short int ExtensionContainer::getPropertyType (const Property * prop) const override virtual
get the Type of a Property
Reimplemented from App::PropertyContainer.
Definition at line 198 of file ExtensionContainer.cpp.
References App::PropertyContainer::getPropertyType().
Referenced by Part::Box::Restore().
handleChangedPropertyName()
void ExtensionContainer::handleChangedPropertyName (Base::XMLReader & reader, const char * TypeName, const char * PropName) override virtual
Extends the rules for handling property name changed, so that extensions are given an opportunity to handle it. If an extension handles a change, neither the rest of the extensions, nor the container itself get to handle it.
Extensions get their extensionHandleChangedPropertyName() called.
If no extension handles the request, then the containers handleChangedPropertyName() is called.
Reimplemented from App::PropertyContainer.
Reimplemented in App::LinkElement, App::Link, Part::Ellipse, PartGui::ViewProviderPartExt, Measure::MeasureDistanceDetached, PartDesign::ProfileBased, Fem::FemAnalysis, Part::BodyBase, PartDesign::Boolean, Surface::Extend, Fem::ConstraintTransform, Part::Circle, FemGui::ViewProviderFemConstraint, and TechDraw::DrawViewBalloon.
Definition at line 479 of file ExtensionContainer.cpp.
References App::PropertyContainer::handleChangedPropertyName(), and TechDrawTools.TaskFillTemplateFields::reader.
Referenced by TechDraw::DrawViewBalloon::handleChangedPropertyName(), Part::Circle::handleChangedPropertyName(), Fem::ConstraintTransform::handleChangedPropertyName(), Surface::Extend::handleChangedPropertyName(), Gui::ViewProviderGeometryObject::handleChangedPropertyName(), Fem::FemAnalysis::handleChangedPropertyName(), PartDesign::ProfileBased::handleChangedPropertyName(), Part::Ellipse::handleChangedPropertyName(), and Part::BodyBase::onBeforeChange().
handleChangedPropertyType()
void ExtensionContainer::handleChangedPropertyType (Base::XMLReader & reader, const char * TypeName, Property * prop) override virtual
Extends the rules for handling property type changed, so that extensions are given an opportunity to handle it. If an extension handles a change, neither the rest of the extensions, nor the container itself get to handle it.
Extensions get their extensionHandleChangedPropertyType() called.
If no extension handles the request, then the containers handleChangedPropertyType() is called.
Reimplemented from App::PropertyContainer.
Reimplemented in Sketcher::SketchObject, Fem::Constraint, Mesh::Cube, TechDraw::DrawProjGroup, Part::Thickness, Mesh::Torus, Fem::FemPostDataAlongLineFilter, Mesh::Cone, PartDesign::SubShapeBinder, PartDesign::Transformed, TechDrawGui::ViewProviderDimension, App::Part, Mesh::Cylinder, TechDraw::DrawViewAnnotation, Fem::ConstraintDisplacement, PartDesign::Pipe, TechDrawGui::ViewProviderViewPart, PartDesign::Helix, TechDrawGui::ViewProviderBalloon, Fem::ConstraintContact, PartDesign::Chamfer, PartDesign::PolarPattern, PartDesign::ShapeBinder, Fem::ConstraintHeatflux, Fem::ConstraintTemperature, Fem::ConstraintInitialTemperature, Part::Mirroring, PartDesign::LinearPattern, PartDesign::Loft, TechDraw::DrawPage, TechDraw::DrawTile, Fem::ConstraintForce, PartDesign::Fillet, Mesh::Ellipsoid, TechDraw::DrawView, Fem::ConstraintPressure, Mesh::Sphere, Part::Primitive, TechDraw::DrawViewBalloon, PartGui::ViewProvider2DObjectGrid, TechDrawGui::ViewProviderLeader, TechDrawGui::ViewProviderRichAnno, and TechDraw::DrawViewDimension.
Definition at line 496 of file ExtensionContainer.cpp.
References App::PropertyContainer::handleChangedPropertyType(), and TechDrawTools.TaskFillTemplateFields::reader.
Referenced by TechDrawGui::ViewProviderLeader::handleChangedPropertyType(), TechDrawGui::ViewProviderRichAnno::handleChangedPropertyType(), PartGui::ViewProvider2DObjectGrid::handleChangedPropertyType(), Mesh::Sphere::handleChangedPropertyType(), Part::Primitive::handleChangedPropertyType(), Mesh::Ellipsoid::handleChangedPropertyType(), PartDesign::Fillet::handleChangedPropertyType(), PartDesign::Loft::handleChangedPropertyType(), Part::Mirroring::handleChangedPropertyType(), PartDesign::Chamfer::handleChangedPropertyType(), PartDesign::ShapeBinder::handleChangedPropertyType(), TechDrawGui::ViewProviderBalloon::handleChangedPropertyType(), PartDesign::Helix::handleChangedPropertyType(), PartDesign::Pipe::handleChangedPropertyType(), TechDrawGui::ViewProviderViewPart::handleChangedPropertyType(), Mesh::Cylinder::handleChangedPropertyType(), TechDrawGui::ViewProviderDimension::handleChangedPropertyType(), PartDesign::Transformed::handleChangedPropertyType(), Mesh::Cone::handleChangedPropertyType(), PartDesign::SubShapeBinder::handleChangedPropertyType(), Fem::FemPostDataAlongLineFilter::handleChangedPropertyType(), Mesh::Torus::handleChangedPropertyType(), Part::Thickness::handleChangedPropertyType(), Mesh::Cube::handleChangedPropertyType(), and Fem::Constraint::handleChangedPropertyType().
hasExtension() [1/2]
bool ExtensionContainer::hasExtension (Base::Type t, bool derived = true) const
Definition at line 72 of file ExtensionContainer.cpp.
References InitGui::t.
Referenced by Gui::ViewProviderDocumentObject::canDelete(), App::Document::exportGraphviz(), App::GeoFeatureGroupExtension::extensionGetSubObject(), PartGui::ViewProviderAttachExtension::extensionSetupContextMenu(), App::LinkBaseExtension::flattenSubname(), App::GeoFeatureGroupExtension::getInvalidLinkObjects(), Part::Feature::getTopoShape(), PartDesignGui::isFeatureMovable(), Gui::DocumentObjectItem::isGroup(), App::GeoFeatureGroupExtension::isLinkValid(), PartDesignGui::isPartDesignAwareObjecta(), registerExtension(), PartDesignGui::relinkToOrigin(), PartGui::TaskAttacher::TaskAttacher(), and Gui::DocumentObjectItem::testStatus().
hasExtension() [2/2]
bool ExtensionContainer::hasExtension (const std::string & name) const
Definition at line 89 of file ExtensionContainer.cpp.
hasExtensions()
bool ExtensionContainer::hasExtensions () const
Definition at line 133 of file ExtensionContainer.cpp.
Referenced by Gui::Document::exportObjects(), Gui::Document::SaveDocFile(), and saveExtensions().
onChanged()
void ExtensionContainer::onChanged (const Property *) override virtual
get called by the container when a property has changed
Reimplemented from App::PropertyContainer.
Reimplemented in App::GeoFeature, App::TextDocument, SketcherGui::ViewProviderSketch, Part::Wedge, Part::Spiral, Fem::FemPostWarpVectorFilter, Part::Helix, Fem::FemPostScalarClipFilter, Fem::FemPostCutFilter, Fem::FemPostContoursFilter, Spreadsheet::Sheet, Fem::FemPostClipFilter, TechDraw::DrawViewPart, TechDraw::DrawViewDimension, MeshGui::ViewProviderMesh, Fem::FemPostSphereFunction, Fem::FemPostDataAtPointFilter, PartDesign::ProfileBased, Fem::Constraint, Fem::FemPostPlaneFunction, MeasureGui::ViewProviderMeasure, Part::Feature, Fem::FemPostDataAlongLineFilter, Fem::FemPostCylinderFunction, PartGui::ViewProviderPartExt, TechDraw::DrawPage, FemGui::ViewProviderFemMesh, TechDraw::DrawProjGroup, Part::Extrusion, TechDraw::DrawView, FemGui::ViewProviderFemPostFunction, PartDesign::SubShapeBinder, Part::Sweep, PartDesign::Body, Fem::FemPostBoxFunction, MeasureGui::ViewProviderMeasureBase, Part::BodyBase, Fem::ConstraintDisplacement, Robot::RobotObject, TechDraw::DrawViewClip, TechDraw::DrawProjGroupItem, TechDraw::DrawViewAnnotation, FemGui::ViewProviderFemPostFunctionProvider, PartDesign::Helix, TechDrawGui::ViewProviderViewPart, TechDraw::DrawViewSection, Part::Loft, TechDraw::DrawViewCollection, Fem::FemPostFunctionProvider, Fem::FemPostPipeline, PartDesign::Hole, Fem::ConstraintFluidBoundary, TechDraw::DrawViewImage, MeshGui::ViewProviderMeshCurvature, PartDesign::DressUp, Assembly::AssemblyLink, Surface::FeatureBlendCurve, Fem::ConstraintBearing, PartDesign::ShapeBinder, Fem::ConstraintContact, Fem::ConstraintRigidBody, Fem::ConstraintPulley, Fem::FemMeshObject, PartDesign::PolarPattern, TechDraw::DrawViewSpreadsheet, Fem::ConstraintHeatflux, Fem::ConstraintTemperature, Robot::TrajectoryDressUpObject, TechDraw::DrawTileWeld, Fem::ConstraintInitialTemperature, PointsGui::ViewProviderPoints, TechDraw::DrawRichAnno, Path::Feature, MeasureGui::ViewProviderMeasureDistance, Robot::TrajectoryObject, Surface::Extend, Fem::ConstraintForce, Fem::ConstraintGear, Fem::ConstraintTransform, PartDesign::Boolean, PartDesign::LinearPattern, TechDrawGui::ViewProviderBalloon, Robot::Edge2TracObject, TechDraw::DrawTile, Part::Mirroring, Part::RuledSurface, Part::Revolution, PartDesignGui::ViewProviderSubShapeBinder, TechDrawGui::ViewProviderViewSection, Part::Box, PartDesign::FeaturePrimitive, FemGui::ViewProviderFemPostObject, PartDesignGui::ViewProviderBoolean, TechDrawGui::ViewProviderPage, Fem::ConstraintFixed, Fem::ConstraintSpring, PartDesign::Point, TechDraw::DrawViewSymbol, PathGui::ViewProviderPath, Part::Primitive, PartDesign::Feature, TechDraw::DrawSVGTemplate, TechDrawGui::ViewProviderImage, Fem::ConstraintPlaneRotation, PartDesign::Plane, PartDesign::FeatureBase, PartDesignGui::ViewProviderDatumPoint, TechDraw::DrawWeldSymbol, FemGui::ViewProviderFemConstraint, PartDesign::Line, FemGui::ViewProviderFemPostDataAtPoint, TechDraw::DrawViewBalloon, InspectionGui::ViewProviderInspection, SketcherGui::ViewProviderCustom, PartGui::ViewProviderCustom, PartGui::ViewProviderPartReference, PartGui::ViewProvider2DObjectGrid, TechDraw::DrawParametricTemplate, Points::Feature, TechDraw::DrawHatch, PartDesignGui::ViewProvider, Mesh::Feature, PartDesignGui::ViewProviderBody, TechDraw::DrawViewDetail, TechDrawGui::ViewProviderDrawingView, TechDraw::DrawGeomHatch, TechDraw::DrawViewMulti, TechDraw::LandmarkDimension, MeshGui::ViewProviderMeshDefects, RobotGui::ViewProviderRobotObject, TechDrawGui::ViewProviderGeomHatch, TechDrawGui::ViewProviderRichAnno, TechDrawGui::ViewProviderHatch, TechDrawGui::ViewProviderTemplate, Drawing::FeatureClip, Drawing::FeaturePage, Drawing::FeatureViewSymbol, Sandbox::SandboxObject, TechDrawGui::ViewProviderDimension, TechDrawGui::ViewProviderWeld, TechDrawGui::ViewProviderLeader, Sketcher::SketchObject, Part::Ellipse, FemGui::ViewProviderFemPostPlaneFunction, Part::FilletBase, Part::Line, App::VRMLObject, PartDesign::Chamfer, Surface::GeomFillSurface, Part::Vertex, Part::Circle, and PartDesignGui::ViewProviderDatumCoordinateSystem.
Definition at line 325 of file ExtensionContainer.cpp.
References App::PropertyContainer::onChanged().
Referenced by draftviewproviders.view_base.ViewProviderDraft::attach(), Gui::ViewProvider::onChanged(), ArchSpace._ViewProviderSpace::onChanged(), ArchSchedule._ArchSchedule::setProperties(), draftviewproviders.view_wpproxy.ViewProviderWorkingPlaneProxy::updateData(), draftviewproviders.view_layer.ViewProviderLayer::updateData(), draftviewproviders.view_label.ViewProviderLabel::updateData(), ArchAxis._ViewProviderAxis::updateData(), draftviewproviders.view_dimension.ViewProviderLinearDimension::updateData(), ArchSpace._ViewProviderSpace::updateData(), ArchBuildingPart.ViewProviderBuildingPart::updateData(), ArchPanel.ViewProviderPanelCut::updateData(), ArchSite._ViewProviderSite::updateData(), ArchSectionPlane._ViewProviderSectionPlane::updateData(), and ArchPanel.ViewProviderPanelSheet::updateData().
registerExtension()
void ExtensionContainer::registerExtension (Base::Type extension, App::Extension * ext)
Definition at line 52 of file ExtensionContainer.cpp.
References create_qrc::ext, hasExtension(), and Base::Type::isDerivedFrom().
Referenced by App::Extension::initExtension().
Restore()
void ExtensionContainer::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Reimplemented in Part::Ellipse, TechDraw::DrawViewDimension, PartDesign::Transformed, PartDesign::ProfileBased, PartDesign::Hole, PartDesign::Chamfer, Part::Circle, PartDesign::Plane, Part::Part2DObject, PartDesign::Fillet, App::VRMLObject, Part::Box, Part::Primitive, PartGui::ViewProvider2DObjectGrid, Points::Feature, Sketcher::SketchObject, and Robot::RobotObject.
Definition at line 348 of file ExtensionContainer.cpp.
References TechDrawTools.TaskFillTemplateFields::reader, App::PropertyContainer::Restore(), and restoreExtensions().
Referenced by App::Document::readObjects(), Part::Primitive::Restore(), App::VRMLObject::Restore(), PartDesign::Fillet::Restore(), Part::Part2DObject::Restore(), Robot::RobotObject::Restore(), PartDesign::Chamfer::Restore(), PartDesign::ProfileBased::Restore(), PartDesign::Transformed::Restore(), TechDraw::DrawViewDimension::Restore(), and App::Document::Restore().
restoreExtensions()
void ExtensionContainer::restoreExtensions (Base::XMLReader & reader)
Definition at line 410 of file ExtensionContainer.cpp.
References Base::Console(), Base::Type::createInstance(), SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), create_qrc::ext, Base::Type::fromName(), getExtension(), App::Extension::getExtensionClassTypeId(), SplineSurface::i, Base::Type::isBad(), Base::Type::isDerivedFrom(), TechDrawTools.TaskFillTemplateFields::reader, and Path.Post.scripts.refactored_centroid_post::str.
Referenced by Restore().
Save()
void ExtensionContainer::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Reimplemented in App::VRMLObject, Sketcher::SketchObject, and Robot::RobotObject.
Definition at line 337 of file ExtensionContainer.cpp.
References App::PropertyContainer::Save(), and saveExtensions().
Referenced by Gui::Document::exportObjects(), and Gui::Document::SaveDocFile().
saveExtensions()
void ExtensionContainer::saveExtensions (Base::Writer & writer) const
Definition at line 361 of file ExtensionContainer.cpp.
References Base::Console(), Base::Writer::decInd(), SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), create_qrc::ext, hasExtensions(), Base::Writer::incInd(), Base::Writer::ind(), and Base::Writer::Stream().
Referenced by Save().
The documentation for this class was generated from the following files:
ExtensionContainer.h
ExtensionContainer.cpp