FreeCAD: TestPartApp Namespace Reference
TestPartApp Namespace Reference
Classes
class BSplineCurve2d
class EmptyEdge
class EmptyFace
class GeometryCurve
class PartBOPTestContainer
class PartTestBSplineCurve
class PartTestBSplineSurface
class PartTestCases
class PartTestChFi2dAlgos
class PartTestCircle2D
class PartTestCone
class PartTestCurveToNurbs
class PartTestNormals
class PartTestRuledSurface
class PartTestShapeFix
class PartTestShapeRotate
Functions
def getCoincidentVertexes (vtx1, vtx2)
Variables
App = FreeCAD
Function Documentation
getCoincidentVertexes()
def TestPartApp.getCoincidentVertexes (vtx1, vtx2)
Definition at line 39 of file TestPartApp.py.
Referenced by TestPartApp.PartTestRuledSurface.testRuledSurfaceFromOneObject(), TestPartApp.PartTestRuledSurface.testRuledSurfaceFromTwoObjects(), and TestPartApp.PartTestRuledSurface.testRuledSurfaceFromTwoObjectsWithSharedVertexs().
Variable Documentation
App
TestPartApp.App = FreeCAD
Definition at line 28 of file TestPartApp.py.