FreeCAD: MeshPart::MeshProjection Class Reference
MeshPart::MeshProjection Class Reference
#include <CurveProjector.h>
Classes
struct Edge
struct PolyLine
struct SplitEdge
Helper class.
Public Member Functions
MeshProjection (const MeshKernel &rMesh)
void findSectionParameters (const TopoDS_Edge &edge, const Base::Vector3f &dir, std::set< double > &parameters) const
findSectionParameters Find the parameters of the edge where when projecting the corresponding point will lie on an edge of the mesh.
void discretize (const TopoDS_Edge &aEdge, std::vector< Base::Vector3f > &polyline, std::size_t minPoints=2) const
void projectToMesh (const TopoDS_Shape &aShape, float fMaxDist, std::vector< PolyLine > &rPolyLines) const
void projectOnMesh (const std::vector< Base::Vector3f > &pointsIn, const Base::Vector3f &dir, float tolerance, std::vector< Base::Vector3f > &pointsOut) const
projectOnMesh Projects the given points onto the mesh along a given direction. The points can can be projected will be saved to pointsOut
void projectParallelToMesh (const TopoDS_Shape &aShape, const Base::Vector3f &dir, std::vector< PolyLine > &rPolyLines) const
void projectParallelToMesh (const std::vector< PolyLine > &aEdges, const Base::Vector3f &dir, std::vector< PolyLine > &rPolyLines) const
void splitMeshByShape (const TopoDS_Shape &aShape, float fMaxDist) const
Protected Member Functions
void projectEdgeToEdge (const TopoDS_Edge &aCurve, float fMaxDist, const MeshCore::MeshFacetGrid &rGrid, std::vector< SplitEdge > &rSplitEdges) const
bool findIntersection (const Edge &, const Edge &, const Base::Vector3f &dir, Base::Vector3f &res) const
Detailed Description
The MeshProjection class projects a shape onto a mesh.
Author
Werner Mayer
Definition at line 171 of file CurveProjector.h.
Constructor & Destructor Documentation
MeshProjection()
MeshProjection::MeshProjection (const MeshKernel & rMesh) explicit
Definition at line 493 of file CurveProjector.cpp.
Member Function Documentation
discretize()
void MeshProjection::discretize (const TopoDS_Edge & aEdge, std::vector< Base::Vector3f > & polyline, std::size_t minPoints = 2) const
Definition at line 497 of file CurveProjector.cpp.
References SCL.SimpleDataTypes::f, and SplineSurface::i.
Referenced by findSectionParameters(), projectEdgeToEdge(), and projectParallelToMesh().
findIntersection()
bool MeshProjection::findIntersection (const Edge & edgeSegm, const Edge & meshEdge, const Base::Vector3f & dir, Base::Vector3f & res) const protected
Definition at line 548 of file CurveProjector.cpp.
References MeshPart::MeshProjection::Edge::cPt1, MeshPart::MeshProjection::Edge::cPt2, Base::Vector3< float_type >::Cross(), Base::Vector3< float_type >::Dot(), and InitGui::t.
Referenced by findSectionParameters().
findSectionParameters()
void MeshProjection::findSectionParameters (const TopoDS_Edge & edge, const Base::Vector3f & dir, std::set< double > & parameters) const
findSectionParameters Find the parameters of the edge where when projecting the corresponding point will lie on an edge of the mesh.
Parameters
edge
dir
parameters
Definition at line 572 of file CurveProjector.cpp.
References MeshPart::MeshProjection::Edge::cPt1, MeshPart::MeshProjection::Edge::cPt2, discretize(), findIntersection(), MeshCore::MeshAlgorithm::GetAverageEdgeLength(), MeshCore::MeshKernel::GetFacets(), MeshCore::MeshKernel::GetPoints(), SplineSurface::i, FreeCADInit::Length, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
projectEdgeToEdge()
void MeshProjection::projectEdgeToEdge (const TopoDS_Edge & aCurve, float fMaxDist, const MeshCore::MeshFacetGrid & rGrid, std::vector< SplitEdge > & rSplitEdges) const protected
Definition at line 855 of file CurveProjector.cpp.
References MeshCore::MeshFacet::_aulPoints, Base::Console(), MeshPart::MeshProjection::SplitEdge::cPt, discretize(), Base::Distance(), SCL.SimpleDataTypes::f, MeshCore::MeshKernel::GetFacets(), MeshCore::MeshGeomFacet::GetNormal(), Handle(), SplineSurface::i, RobotExample::l, Base::ConsoleSingleton::Log(), Base::SequencerLauncher::next(), MeshCore::MeshAlgorithm::SearchFacetsFromPolyline(), MeshCore::MeshFacetIterator::Set(), Base::Vector3< float_type >::Set(), MeshCore::MeshPointIterator::Set(), MeshPart::MeshProjection::SplitEdge::uE0, MeshPart::MeshProjection::SplitEdge::uE1, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by projectToMesh().
projectOnMesh()
void MeshProjection::projectOnMesh (const std::vector< Base::Vector3f > & pointsIn, const Base::Vector3f & dir, float tolerance, std::vector< Base::Vector3f > & pointsOut) const
projectOnMesh Projects the given points onto the mesh along a given direction. The points can can be projected will be saved to pointsOut
projectOnMesh
Parameters
pointsIn
dir
tolerance
pointsOut
Definition at line 662 of file CurveProjector.cpp.
References DraftVecUtils::angle(), ModelRefine::boundaryEdges(), dot(), SCL.SimpleDataTypes::e, SCL.SimpleDataTypes::f, MeshCore::MeshAlgorithm::GetAverageEdgeLength(), MeshCore::MeshKernel::GetFacet(), MeshCore::MeshKernel::GetFacets(), MeshCore::MeshKernel::GetPoints(), SplineSurface::i, MeshCore::MeshGeomFacet::IntersectPlaneWithLine(), MeshCore::MeshGeomFacet::IsPointOfFace(), MeshCore::MeshAlgorithm::NearestFacetOnRay(), Base::SequencerLauncher::next(), result, draftutils.utils::tolerance(), and SurfaceTests.TestBlendCurve::vec.
projectParallelToMesh() [1/2]
void MeshProjection::projectParallelToMesh (const std::vector< PolyLine > & aEdges, const Base::Vector3f & dir, std::vector< PolyLine > & rPolyLines) const
Project all polylines onto the mesh using parallel projection.
Definition at line 803 of file CurveProjector.cpp.
References SCL.SimpleDataTypes::f, MeshCore::MeshAlgorithm::GetAverageEdgeLength(), MeshCore::MeshAlgorithm::NearestFacetOnRay(), Base::SequencerLauncher::next(), MeshPart::MeshProjection::PolyLine::points, MeshCore::MeshProjection::projectLineOnMesh(), and result.
projectParallelToMesh() [2/2]
void MeshProjection::projectParallelToMesh (const TopoDS_Shape & aShape, const Base::Vector3f & dir, std::vector< PolyLine > & rPolyLines) const
Project all edges of the shape onto the mesh using parallel projection.
Definition at line 743 of file CurveProjector.cpp.
References discretize(), SCL.SimpleDataTypes::f, MeshCore::MeshAlgorithm::GetAverageEdgeLength(), MeshCore::MeshAlgorithm::NearestFacetOnRay(), Base::SequencerLauncher::next(), MeshPart::MeshProjection::PolyLine::points, MeshCore::MeshProjection::projectLineOnMesh(), and result.
projectToMesh()
void MeshProjection::projectToMesh (const TopoDS_Shape & aShape, float fMaxDist, std::vector< PolyLine > & rPolyLines) const
Searches all edges that intersect with the projected curve aShape. Therefore aShape must contain shapes of type TopoDS_Edge, other shape types are ignored. A possible solution is taken if the distance between the curve point and the projected point is <= fMaxDist.
Definition at line 630 of file CurveProjector.cpp.
References SCL.SimpleDataTypes::f, MeshCore::MeshAlgorithm::GetAverageEdgeLength(), Base::SequencerLauncher::next(), MeshPart::MeshProjection::PolyLine::points, and projectEdgeToEdge().
Referenced by splitMeshByShape().
splitMeshByShape()
void MeshProjection::splitMeshByShape (const TopoDS_Shape & aShape, float fMaxDist) const
Cuts the mesh at the curve defined by aShape. This method call projectToMesh() to get the split the facet at the found points.
See also
projectToMesh() for more details.
Definition at line 531 of file CurveProjector.cpp.
References projectToMesh(), and Path.Post.scripts.refactored_centroid_post::str.
The documentation for this class was generated from the following files:
CurveProjector.h
CurveProjector.cpp