FreeCAD: draftobjects.ellipse.Ellipse Class Reference
draftobjects.ellipse.Ellipse Class Reference
DRAFT » draftobjects
Public Member Functions
def __init__ (self, obj)
def onDocumentRestored (self, obj)
def execute (self, obj)
def onChanged (self, obj, prop)
Public Member Functions inherited from draftobjects.base.DraftObject
def __init__ (self, obj, tp="Unknown")
def dumps (self)
def loads (self, state)
def props_changed_store (self, prop)
def props_changed_clear (self)
def props_changed_placement_only (self, obj=None)
Additional Inherited Members
Public Attributes inherited from draftobjects.base.DraftObject
Type
props_changed
Detailed Description
The Circle object
Definition at line 38 of file ellipse.py.
Constructor & Destructor Documentation
__init__()
def draftobjects.ellipse.Ellipse.__init__ (self, obj)
Definition at line 41 of file ellipse.py.
References Arch.QT_TRANSLATE_NOOP.
Member Function Documentation
execute()
def draftobjects.ellipse.Ellipse.execute (self, obj)
Run this method when the object is created or recomputed.
Override this method to produce effects when the object
is newly created, and whenever the document is recomputed.
By default it does nothing.
Parameters
----------
obj : the scripted object.
    This commonly may be of types `Part::Part2DObjectPython`,
    `Part::FeaturePython`, or `App::FeaturePython`.
Reimplemented from draftobjects.base.DraftObject.
Definition at line 69 of file ellipse.py.
References draftobjects.base.DraftObject.props_changed_clear(), draftobjects.base.DraftObject.props_changed_placement_only(), and Arch.QT_TRANSLATE_NOOP.
Referenced by src.Mod.PartDesign.Scripts.Spring.MySpring.onChanged(), src.Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid.onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped.onChanged(), src.Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt.onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder.onChanged(), MeasureCOM.MeasureCOM.onChanged(), and FeaturePython.DistanceBolt.onChanged().
onChanged()
def draftobjects.ellipse.Ellipse.onChanged (self, obj, prop)
Run this method when a property is changed.
Override this method to handle the behavior
of the object depending on changes that occur to its properties.
By default it does nothing.
Parameters
----------
obj : the scripted object.
    This commonly may be of types `Part::Part2DObjectPython`,
    `Part::FeaturePython`, or `App::FeaturePython`.
prop : str
    Name of the property that was modified.
Reimplemented from draftobjects.base.DraftObject.
Definition at line 105 of file ellipse.py.
References draftobjects.base.DraftObject.props_changed_store().
Referenced by draftviewproviders.view_base.ViewProviderDraft.attach(), draftviewproviders.view_wpproxy.ViewProviderWorkingPlaneProxy.updateData(), draftviewproviders.view_layer.ViewProviderLayer.updateData(), draftviewproviders.view_label.ViewProviderLabel.updateData(), and draftviewproviders.view_dimension.ViewProviderLinearDimension.updateData().
onDocumentRestored()
def draftobjects.ellipse.Ellipse.onDocumentRestored (self, obj)
Reimplemented from draftobjects.base.DraftObject.
Definition at line 65 of file ellipse.py.
The documentation for this class was generated from the following file:
ellipse.py