FreeCAD: importOCA Namespace Reference
importOCA Namespace Reference
DRAFT
OCA (Open CAD Format) file importer & exporter.
Functions
def translate (context, txt)
def getpoint (data)
def getarea (data)
def getarc (data)
def getline (data)
def gettranslation (data)
def writepoint (vector)
def createobject (oid, doc)
def parse (filename, doc)
def open (filename)
def insert (filename, docname)
def export (exportList, filename)
Detailed Description
OCA (Open CAD Format) file importer & exporter.
Function Documentation
createobject()
def importOCA.createobject (oid, doc)
Create Part::Feature object in the current document.
Parameters
----------
oid : str
    ID number of a particular object in the document.
doc : App::Document
    A FreeCAD document to which the object is added.
Returns
-------
None
Definition at line 252 of file importOCA.py.
Referenced by parse().
export()
def importOCA.export (exportList, filename)
Export the OCA file with a given list of objects.
The objects must be edges or faces, in order to be processed
and exported.
Parameters
----------
exportList : list
    List of document objects to export.
filename : str
    Path to the new file.
Returns
-------
None
    If `exportList` doesn't have shapes to export.
Definition at line 381 of file importOCA.py.
References Path.Post.scripts.refactored_centroid_post.str, and writepoint().
getarc()
def importOCA.getarc (data)
Turn an OCA arc definition into a FreeCAD Part.Edge.
Parameters
----------
data : list
    Different types of data.
Returns
-------
Part.Edge
    An edge object from the points in `data`.
Definition at line 123 of file importOCA.py.
References getpoint().
Referenced by parse().
getarea()
def importOCA.getarea (data)
Turn an OCA area definition into a FreeCAD Part.Wire.
Parameters
----------
data : list
    Different types of data.
Returns
-------
Part.Wire
    A wire object from the points in `data`.
Definition at line 98 of file importOCA.py.
References getpoint().
Referenced by parse().
getline()
def importOCA.getline (data)
Turns an OCA line definition into a FreeCAD Part.Edge.
Parameters
----------
data : list
    Different types of data.
Returns
-------
Part.Edge
    An edge object from the points in `data`.
Definition at line 189 of file importOCA.py.
References getpoint().
Referenced by Drawing::FeaturePage.execute(), FC_LOG_LEVEL_INIT(), TechDraw::PATLineSpec.findPatternStart(), Drawing::FeaturePage.getEditableTextsFromTemplate(), TechDraw::LineGroup.getGroupNamesFromFile(), TechDraw::LineGenerator.getLineDescriptions(), TechDraw::PATLineSpec.getPatternList(), CDxfWrite.getPlateFile(), TechDraw::LineGroup.getRecordFromFile(), getSWIGVersionFromModule(), Spreadsheet::Sheet.importFromFile(), MeshCore::ReaderOBJ.Load(), Points::PointsAlgos.LoadAscii(), MeshCore::MeshInput.LoadAsciiSTL(), TechDrawGui::DrawGuiUtil.loadLineGroupChoices(), MeshCore::ReaderOBJ.LoadMaterial(), MeshCore::MeshInput.LoadMeshNode(), MeshCore::MeshInput.LoadNastran(), MeshCore::MeshInput.LoadOFF(), TechDraw::PATLineSpec.loadPatternDef(), Gui::Dialog::DlgSettingsWorkbenchesImp.loadSettings(), MeshCore::MeshInput.LoadSMF(), TechDrawGui::DlgPrefsTechDrawAnnotationImp.onLineGroupChanged(), pagesize(), parse(), Base::InventorLoader.read(), TechDraw::LineGroup.split(), TechDraw::DrawUtil.split(), and Base::Tools.splitSubName().
getpoint()
def importOCA.getpoint (data)
Turn an OCA point definition into a FreeCAD.Vector.
Parameters
----------
data : list
    Different types of data.
Returns
-------
Base::Vector3
    A vector with the data arranged, depending on the contents of `data`.
Definition at line 58 of file importOCA.py.
Referenced by getarc(), getarea(), getline(), and parse().
gettranslation()
def importOCA.gettranslation (data)
Retrieve a translation (move) vector from `data`.
Parameters
----------
data : list
    Different types of data.
Returns
-------
Base::Vector3
    A vector with X, Y, or Z displacement, or (0, 0, 0).
Definition at line 213 of file importOCA.py.
Referenced by parse().
insert()
def importOCA.insert (filename, docname)
Get an active document and parse.
If no document exist, it is created.
Parameters
----------
filename : str
    The path to the filename to be opened.
docname : str
    The name of the active App::Document if one exists, or
    of the new one created.
Returns
-------
None
Definition at line 355 of file importOCA.py.
References parse().
open()
def importOCA.open (filename)
Open filename and parse.
Parameters
----------
filename : str
    The path to the filename to be opened.
Returns
-------
None
Definition at line 333 of file importOCA.py.
References parse().
parse()
def importOCA.parse (filename, doc)
Import an opened OCA file into the given document.
Parameters
----------
filename : str
    The path to the OCA file.
doc : App::Document
    A FreeCAD document to which the object is added.
Returns
-------
None
Definition at line 273 of file importOCA.py.
References createobject(), getarc(), getarea(), getline(), getpoint(), and gettranslation().
Referenced by insert(), and open().
translate()
def importOCA.translate (context, txt)
Definition at line 52 of file importOCA.py.
writepoint()
def importOCA.writepoint (vector)
Write a FreeCAD.Vector in OCA format.
Parameters
----------
vector : Base::Vector3
    A vector with three components.
Returns
-------
str
    A string "P(X Y Z)" with the information from `vector`.
Definition at line 236 of file importOCA.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by export().