FreeCAD: Gui::PythonStdout Class Reference
Gui::PythonStdout Class Reference
#include <PythonConsolePy.h>
Public Member Functions
PythonStdout (PythonConsole *pc)
~PythonStdout () override
Py::Object getattr (const char *name) override
Py::Object repr () override
Py::Object write (const Py::Tuple &)
Py::Object flush (const Py::Tuple &)
Py::Object isatty ()
Static Public Member Functions
static void init_type ()
Detailed Description
Python class for redirection of stdout to FreeCAD's Python console window. This allows one to show all Python messages in the same window where the commands are performed.
See also
PythonStderr
PythonConsole
Author
Werner Mayer
Definition at line 42 of file PythonConsolePy.h.
Constructor & Destructor Documentation
PythonStdout()
PythonStdout::PythonStdout (PythonConsole * pc) explicit
Definition at line 42 of file PythonConsolePy.cpp.
~PythonStdout()
PythonStdout::~PythonStdout () override default
Member Function Documentation
flush()
Py::Object PythonStdout::flush (const Py::Tuple &)
Definition at line 83 of file PythonConsolePy.cpp.
Referenced by init_type().
getattr()
Py::Object PythonStdout::getattr (const char * name) override
Definition at line 49 of file PythonConsolePy.cpp.
References SplineSurface::i.
init_type()
void PythonStdout::init_type () static
Definition at line 31 of file PythonConsolePy.cpp.
References flush(), isatty(), and write().
Referenced by Gui::Application::Application().
isatty()
Py::Object PythonStdout::isatty ()
Definition at line 88 of file PythonConsolePy.cpp.
References femtools.tokrules::False.
Referenced by init_type().
repr()
Py::Object PythonStdout::repr () override
Definition at line 58 of file PythonConsolePy.cpp.
References toolbit-attributes::s, and src.Mod.Test.testmakeWireString::String.
write()
Py::Object PythonStdout::write (const Py::Tuple & args)
Definition at line 66 of file PythonConsolePy.cpp.
References toolbit-attributes::args, and ArchBuildingPart::unicode.
Referenced by init_type().
The documentation for this class was generated from the following files:
PythonConsolePy.h
PythonConsolePy.cpp