FreeCAD: draftviewproviders.view_base.ViewProviderDraftAlt Class Reference
draftviewproviders.view_base.ViewProviderDraftAlt Class Reference
DRAFT » draftviewproviders
Public Member Functions
def __init__ (self, vobj)
def doubleClicked (self, vobj)
def claimChildren (self)
Public Member Functions inherited from draftviewproviders.view_base.ViewProviderDraft
def dumps (self)
def loads (self, state)
def attach (self, vobj)
def updateData (self, obj, prop)
def getDisplayModes (self, vobj)
def getDefaultDisplayMode (self)
def setDisplayMode (self, mode)
def onChanged (self, vobj, prop)
def execute (self, vobj)
def setEdit (self, vobj, mode)
def unsetEdit (self, vobj, mode)
def setupContextMenu (self, vobj, menu)
def edit (self)
def transform (self)
def getIcon (self)
Additional Inherited Members
Public Attributes inherited from draftviewproviders.view_base.ViewProviderDraft
Object
texture
texcoords
wb_before_edit
Detailed Description
A view provider that doesn't absorb its base object in the tree view.
The `claimChildren` method is overridden to return an empty list.
The `doubleClicked` method is defined.
Only used by the `Shape2DView` object.
Definition at line 540 of file view_base.py.
Constructor & Destructor Documentation
__init__()
def draftviewproviders.view_base.ViewProviderDraftAlt.__init__ (self, vobj)
Reimplemented from draftviewproviders.view_base.ViewProviderDraft.
Reimplemented in draftviewproviders.view_base.ViewProviderDraftPart.
Definition at line 550 of file view_base.py.
Member Function Documentation
claimChildren()
def draftviewproviders.view_base.ViewProviderDraftAlt.claimChildren (self)
Return objects that will be placed under it in the tree view.
Override this method to return a list with objects
that will appear under this object in the tree view.
That is, this object becomes the `parent`,
and all those under it are the `children`.
By default the returned list is composed of objects from
`Object.Base`, `Object.Objects`, `Object.Components`,
and `Object.Group`, if they exist.
Returns
-------
list
    List of objects.
Reimplemented from draftviewproviders.view_base.ViewProviderDraft.
Definition at line 558 of file view_base.py.
Referenced by femviewprovider.view_result_mechanical.VPResultMechanical.onDelete(), BOPTools.SplitFeatures.ViewProviderBooleanFragments.onDelete(), BOPTools.JoinFeatures.ViewProviderConnect.onDelete(), BOPTools.ToleranceFeatures.ViewProviderToleranceSet.onDelete(), femviewprovider.view_mesh_gmsh.VPMeshGmsh.onDelete(), BOPTools.SplitFeatures.ViewProviderSlice.onDelete(), and BOPTools.SplitFeatures.ViewProviderXOR.onDelete().
doubleClicked()
def draftviewproviders.view_base.ViewProviderDraftAlt.doubleClicked (self, vobj)
Definition at line 553 of file view_base.py.
The documentation for this class was generated from the following file:
view_base.py